### ISSUE TITLE
Asset download during nextjs export

### ISSUE THREAD

**Issue by sandys** [vercel/next.js#10147]
# Feature request

A related conversation to this feature happened here https://github.com/zeit/next.js/issues/9524#issuecomment-574568879

if i use a headless CMS (even wordpress or graphcms or whatever), the asset url is used in the static html.

There are two preferences here - that asset links be used as such.
But more likely - download the asset, build the html (link to it locally) and then layer a CDN in front. This is the far more acceptable practice.

This also ties in very well with using deployment systems like Netlify - which have a far, far more suitable globally available infrastructure than something like DatoCMS or Graphcms. So if im using Netlify as deployment, i would want everything to be served from Netlify domain and let it work its magic.

We understand that this increases build times. This is ok for our usecase where we use a CMS just for the sake of usability, but deployment has to follow guidelines of compliance (geographic restriction of assets, etc) so we would like the entire build to be inside the export folder. This would mean that CMS that have CDN in front of it (e.g. datocms and www.datocms-assets.com which is Imgix) may not be ideal.

There are tons of similar requests. 

https://spectrum.chat/next-js/general/how-would-you-handle-importing-remote-images-on-nextjs-static-export~30b2ba84-bc27-4da7-9ec8-21e4d5d287a3

on gatsby side as well - gatsbyjs/gatsby#14076

https://spectrum.chat/gatsby-js/general/adding-remote-images-during-node-creation~e704e6fb-24b2-46c6-b1fc-93189d2e28a4

https://github.com/njosefbeck/gatsby-source-stripe/#downloading-files

**Comment by Timer** [comment]
This is covered by #9524

**Comment by sandys** [comment]
@Timer sorry for the late response. but this is NOT covered by #9524 . In fact, i was told there to open a new issue since this will not be considered for inclusion under SSG improvements.

Is it possible to do this using any kind of custom code, etc ? this is the only thing blocking us from moving entirely to Nextjs from Gatsby.

**Comment by erhankaradeniz** [comment]
@Timer I think @sandys is right here, I'm not seeing anything in that RFC which would solve this issue? Please correct me if I'm wrong, since I'd like to make use of this feature too since I switched to almost 100% SSG pages with the canary builds.

**Comment by sandys** [comment]
hi guys,
now that nextjs 9.3 is released with next-gen SSG support ( https://nextjs.org/blog/next-9-3#next-gen-static-site-generation-ssg-support ), im wondering if there is any way to achieve what was mentioned in this bug ?

**Comment by sandys** [comment]
@timer - any chance you can take a look at this and comment ? if there's a way to do this using the existing Nextjs framework, that would be awesome as well.

**Comment by pancho111203** [comment]
Any news on this? Ideally this should just store images fetched during getStaticProps on .next/static/images like the rest of the images of the website. The fetching will only happen on build time (getStaticProps), so this shouldn't be a problem technically.

**Comment by zommerberg** [comment]
Any news on this?

**Comment by Ecksters** [comment]
In my case my headless CMS is internal-only, and only accessible during the build process, currently I'm having to hack together a solution to copy the uploads folder from the headless CMS into my build export's `out` folder so that the URLs provided by the CMS can be accurate.

It'd be awesome, if NextJS could handle fetching these assets during the build for me, including potentially doing the image optimizations that are already available during the build.

**Comment by sandys** [comment]
Same issue for us. The CMS is private.

We would love this feature.
