### ISSUE TITLE
Renaming files in specific ways causes dev server to hang

### ISSUE THREAD

**Issue by ijjk** [vercel/next.js#10196]
# Bug report

## Describe the bug

When using Next.js in development mode and you rename a file to either `nav.js` -> `nav/index.js` or `nav.js` -> `nav.tsx` the server hangs. This was first reported by @pacocoursey and I am able to reproduce it consistently with or without TypeScript being active on a project.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create new Next.js project `yarn create next-app test-renames`
2. Start dev server `cd test-renames && yarn dev`
3. Open page that uses file being renamed in browser http://localhost:3000/
4. Rename the file to one of the above cases `mkdir components/nav && mv components/nav.js components/nav/index.js`
5. Reload page and notice it hanging 

## Expected behavior

To handle these renames properly

## System information

- OS: macOS
- Browser (if applies): does not apply
- Version of Next.js: latest (v9.2.0)

## Additional context

None at this time, will need further investigation

**Comment by ijjk** [comment]
Potentially related webpack issues:
https://github.com/webpack/webpack-dev-server/issues/1922
https://github.com/webpack/webpack/issues/9195
https://github.com/webpack/webpack/issues/5523

**Comment by pacocoursey** [comment]
I believe this was fixed sometime in Next.js 12

**Comment by samcx** [comment]
Yeah this has been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture>.
