### ISSUE TITLE
.next directory not automatically created when doing production build.

### ISSUE THREAD

**Issue by jon64digital** [vercel/next.js#10368]
# Bug report

## Describe the bug

I just upgraded to version 9.0.7 (from 9.0 I believe) and did a production build. It didn't create the .next directory which I had previously deleted and would only work if I manually created the .next directory.

As a bit of background, I got into the habit of deleting the .next directory between production builds as a simple way of removing all previous builds. Running a new build always automatically created the directory but now it seems not to recognise that the directory doesn't exist.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Delete your .next directory
2. npm run build
3. No built files can be found

## Expected behavior

The built files should be in the .next directory which should have been recreated.

## System information

- OS: Win10
- Version of Next.js: 9.0.7

**Comment by ijjk** [comment]
Hi, we ensure the `.next` or `distDir` is created during each build. If this is not the case there may be a permission or some other error occurring. Here's [the line](https://github.com/zeit/next.js/blob/d04d9766986e3890a0ad66479b06e3fd00bbed6b/packages/next/build/index.ts#L275) in our build where we create the `.next` folder. Is it possible the `.next` folder is being deleted after the build occurs?

**Comment by jon64digital** [comment]
I'm not sure but I've been playing with it all evening and now I keep getting the following error when trying to run the production build...

**Fri Jan 31 2020 23:02:36 GMT+0000 (Greenwich Mean Time): Application has thrown an uncaught exception and is terminated:
Error: Cannot find module '../lib/data-manager-context'**

**Comment by jon64digital** [comment]
I'm not in a position to post a full reproduction unfortunately. The site is massive and under NDA. If I were to start again with a fresh installation to create a reproduction I'm sure the problem would go away. Which is what makes me think I may have to do a fresh install now to get this working, I've upgraded and downgraded the Next JS version and it's now just really confused.

**Comment by timneutkens** [comment]
Not sure what we can do to help then, maybe give support through enterprise support 🤔 feel free to email enterprise@zeit.co.

**Comment by Timer** [comment]
Closing as no reproduction provided.
