### ISSUE TITLE
Next JS Export to static HTML always redirect to home page “/” if page refresh

### ISSUE THREAD

**Issue by yvescoinpass** [vercel/next.js#10522]
# Bug report

## Describe the bug
I am creating a blogging application using Next JS and React. I already understand the basics because of this tutorial https://nextjs.org/learn/basics/getting-started.

So I tried to implement the blogging application. When I try to test it in development mode `yarn dev` the routing are fine. But if I build it `yarn build` and export into static HTML `yarn export`. The routing misses up when I click on the link it goes on the right page but when I refresh the browser it always takes me back to the `/` page.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow this tutorial https://nextjs.org/learn/basics/deploying-a-nextjs-app. But use the "Deploying to Your Own Environment" steps

2. Test it on development mode `yarn dev` and visit the links and refresh each page. It will not redirect to `/` page. 

3. Build it `next build`

4. Export it `next export`

5. Upload it into your own server in my case I use nginx local server or use this package https://www.npmjs.com/package/serve

6. Visit the links and refresh each page. It will always redirect to `/` page.

## Expected behavior

It should not go back to the `/` page when user refresh the page eg. pressing F5 on the browser rather stays on the current page and load the current data of the page.

## System information

- OS: Debian 9 Linux
- Browser: Goog Chrome
- Version of Next.js: "next": "^9.2.1",

**Comment by wulei7528** [comment]
I found the same problem like you！I tried to modify next.config.js by add exportPathMap,but generate ***.html instead of ***/index.html like the document！

**Comment by AmericanWebbery** [comment]
Are you trying to run this on something like Apache? If so, I believe you have to make a tweak in your .htaccess file.

Options -MultiViews
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.html [QSA,L]

**Comment by yvescoinpass** [comment]
In my case I use nginx local server or use this package https://www.npmjs.com/package/serve

**Comment by AmericanWebbery** [comment]
> In my case I use nginx local server or use this package https://www.npmjs.com/package/serve

Hmm, are you hosting the 'out' folder that contains the exported site?

**Comment by alfanzain** [comment]
> > In my case I use nginx local server or use this package https://www.npmjs.com/package/serve
> 
> Hmm, are you hosting the 'out' folder that contains the exported site?

I think, yes. I've found this problem since November 2019 and there is no cure for this yet!

**Comment by yvescoinpass** [comment]
This is sad. I was am currently implementing server side rendering using this package and upload it to the server specifically Aws Amplify.

**Comment by yvescoinpass** [comment]
Does this mean we really need to use `now` setup and Zeit hosting to use Next JS Static HTML?

**Comment by timneutkens** [comment]
Sounds like a wrong AWS Amplify configuration. You can put `next export` output on any static file server really.

**Comment by alfanzain** [comment]
@timneutkens I put ```next export``` output on apache server and I can't access http://humanitysky.com/campaign/20/
I must go to the homepage then click the card to open it.

**Comment by timneutkens** [comment]
@alfanzain sounds like a wrong apache config where `.html` files are not served?

**Comment by yvescoinpass** [comment]
@timneutkens  Did you try to reproduce it? Even if you followed the deployment documentation this issue will come up.

**Comment by AmericanWebbery** [comment]
You are not tied to Now to host. I am running Next JS on Netlify.

**Comment by yvescoinpass** [comment]
@AmericanWebbery  How did you deploy? Are you using the static html deployment? Can you give us some steps?

**Comment by AmericanWebbery** [comment]
Using Netlify I have it do auto deploys from a private Github repo (it's one of the default options). I just had to set the build script for it to use and anytime I do a push to the repo, Netlify will deploy as well. I'm pretty sure it is still just hosting the "out" folder that nextjs produces when you npm run build or yarn build. I'm going to try running a Nextjs site on a static host soon and see if I get similar results.

**Comment by alfanzain** [comment]
@timneutkens I don't know.

**Comment by AmericanWebbery** [comment]
@yvescoinpass I went through the Next JS static export demo and when I run `$:npx serve` on the 'out' folder I get the same behavior that you are describing only on dynamic pages, pages created by returning data from an API. @yvescoinpass are the pages on your site pulling in the data dynamically? Not that it should matter but I'm curious. The current next.js site I've built is not using any dynamic pages so I'm curious if I would see the same behavior on my host.

**Comment by AmericanWebbery** [comment]
@yvescoinpass I also found this: https://nextjs.org/learn/excel/static-html-export/exporting-other-pages which for the demo made the pages render completely before exporting and no longer caused a refresh to fail. Not sure if it's similar to the issue you are having but may be worth checking out.

**Comment by yvescoinpass** [comment]
@AmericanWebbery  Yes some of it are getting the dynamic data using amplify appsync functionality. But some are just plain static html page like about page. I got the same behavior on all pages.

**Comment by yvescoinpass** [comment]
@AmericanWebbery  Someone commented in here. I think this https://github.com/zeit/next.js/issues/10522#issuecomment-586581389 he used exportPathMap on his project also and got the same result as me.

**Comment by yvescoinpass** [comment]
> @yvescoinpass I also found this: https://nextjs.org/learn/excel/static-html-export/exporting-other-pages which for the demo made the pages render completely before exporting and no longer caused a refresh to fail. Not sure if it's similar to the issue you are having but may be worth checking out.

@AmericanWebbery Someone commented in here. I think this #10522 (comment) he used exportPathMap on his project also and got the same result as me.

**Comment by erikdstock** [comment]
I think I'm having this issue as well, both on zeit and running `npx serve`. My home page contains this (nextjs 9.2.2):
```
      <h3>
        <Link href="/foo/test">
          <a>foo/test (Link)</a>
        </Link>
      </h3>
      <h3>
        <a href="/foo/test">foo/test (a)</a>
      </h3>
```
Clicking on the `a` tags cause no change on click, while the `Link` tags do a client-side update without refresh.  However, on refreshing the page i see home page content again. Both link types update the location bar and refreshing does not change it back to `/` - just loads home screen content.

**Comment by timneutkens** [comment]
If you add `-s` it's going to rewrite all files to `index.html` which is not what you want when using Next.js.
```
      -s, --single                        Rewrite all not-found requests to `index.html`
```

**Comment by yvescoinpass** [comment]
@timneutkens Thanks you answer the question about the issue if we use this package https://www.npmjs.com/package/serve. 

How about if serve the static html files on nginx? 
Do you kno what are the configuration we need?

**Comment by alexandrepaivaa** [comment]
I have the same problem here when using the exported static files. Navigating through the website is fine but if I refresh with F5 it displays the homepage instead of the current page. On production is works fine. My .htaccess:

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.html [L,QSA]

**Comment by salazarm** [comment]
In my case it turned out my 404 was being rendered which would redirect them. 
It was rendering 404 because API Routes aren't supported by Next export.

**Comment by Mistwell** [comment]
any htaccess for apache? 
Options -MultiViews
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.html [QSA,L]

This settings gives only redirect to homepage on pages another than '/'.
Moving on site is ok, copy paste urls in browser return me to homepage(.

**Comment by mayuratbillme** [comment]
> If you add `-s` it's going to rewrite all files to `index.html` which is not what you want when using Next.js.
> 
> ```
>       -s, --single                        Rewrite all not-found requests to `index.html`
> ```

Where do I add the `-s` in the `index.html` file?

**Comment by lmuntaner** [comment]
I solved this by adding the following to `next.config.js`:

```
module.exports = {
  exportTrailingSlash: true,
}
```

https://nextjs.org/docs/api-reference/next.config.js/exportPathMap#adding-a-trailing-slash

I guess this depends on your web server.
