### ISSUE TITLE
Implement HTTPS for Development (localhost)

### ISSUE THREAD

**Issue by stramel** [vercel/next.js#10700]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to be able to easily use HTTPS on my localhost

## Describe the solution you'd like

Be able to change the `dev` script like so:

```diff
-"dev": "next",
+"dev": "HTTPS=true next",
``` 

## Additional context

CRA and Gatsby both handle this. Gatsby uses `devcert`.

https://www.gatsbyjs.org/docs/local-https/
https://create-react-app.dev/docs/using-https-in-development/

**Comment by frank-dspeed** [comment]
Sounds logical i do the same

**Comment by RayLuxembourg** [comment]
While at it please add example in custom-server/typescript

**Comment by othneildrew** [comment]
I'm by no means a master developer, but a solution I've been taking advantage of for years is to use Laravel's valet. Using this method I can serve any folder or application on my mac over HTTPS if needed.
[https://laravel.com/docs/5.8/valet](https://laravel.com/docs/5.8/valet)

Hopefully, this is helpful for someone :)

**Comment by frank-dspeed** [comment]
i will do that i issue a pr,

**Comment by sospedra** [comment]
This is very much needed. Most of the modern webApi capabilities are restricted to work only under secure connections. Not to mentions trying to test in a real device. Accessing `http://192.168.x.y:3000` is subpar compared to `https://{same}`

**Comment by frank-dspeed** [comment]
I closed my effort to implement that into this project it is not worth the work a project member also has closed my PullRequest. I jump into the next framework with another name then next :).

https://github.com/direktspeed/next.js/issues/2 has some useful stuff in it if someone is interested in picking this up.

**Comment by timneutkens** [comment]
> I closed my effort to implement that into this project it is not worth the work a project member also has closed my PullRequest

You only opened an issue title "PR", no pull-request was opened hence why it was closed in favor of this issue which already existed 🤔

**Comment by frank-dspeed** [comment]
@timneutkens its ok for me no need to talk about that vercel is dead for me. I will do a little youtube video about that and then forget it and call it a day.

**Comment by malixsys** [comment]
See [This example](https://github.com/vercel/next.js/blob/canary/examples/with-http2/server.js)...

**Comment by mifrej** [comment]
Is there any plan to follow with this issue?
It would be great to have this feature natively baked in in the nextjs.config instead creating custom Node server like in the mentioned example

**Comment by malixsys** [comment]
I suggest using ngrok in the mean time…
