### ISSUE TITLE
Can't type a pure JS component in TypeScript when dynamically imported

### ISSUE THREAD

**Issue by eric-burel** [vercel/next.js#11196]
# Bug report

## Describe the bug

Say you want to import `react-leaflet`, which is not SSR friendly (call to `window` global), and do not include TS typings as far as I know.

You are supposed to do:
```js
const Map = dynamic(() => import("react-leaflet/lib/Map"), {
  ssr: false
});

const MyMap = () => (<Map className="hello" />) // className won't be allowed
```

It won't work, `className` prop is not recognized on `Map`.

Now, install `@types/react-leaflet` to add TypeScript. It still don't work.

Now you may want to add an explicit type to `dynamic`, like this `dynamic<MapProps>`. But you have no way to either load `MapProps` type globally nor to import it from  `@types/react-leaflet` (not allowed in TypeScript, you have to import `react-leaflet`, which you can't server side, back to square 1).

Related: https://github.com/zeit/next.js/issues/4515

## To Reproduce

Code above in a page should be enough to repro in  Next + TS app, VS code will show an error on `className` prop.

## Expected behavior

`Map` component typings should work directly without aditionnal step, as if you imported it directly from `react-leaflet`

## System information

- Version of Next.js: 9.3

## Additional context
I already have the following quickfix:

Eventually I had too:
- Install `@types/react-leaflet` => to get the typings
- Copy paste  `node_modules/@types/react-leaflet/index.d.ts` in my code, as  `typings/react-leaflet.ts` (to bypass @types forbidden import)
- import types from there `import { MapProps } from "~/typings/react-leaflet"`
- `const Map = dynamic<MapProps>(() => import("react-leaflet/lib/Map"), { ssr: false})`
- Enjoy

Related SO question: https://stackoverflow.com/questions/60829472/dynamically-import-a-typescript-type

**Comment by eric-burel** [comment]
You may also want to add `// @ts-nocheck` at the top of `react-leaflet.ts` otherwise `tsc`/`ts-loader` will cry.

**Comment by eric-burel** [comment]
By the way this issue isn't only limited to component props. It also concerns other types exported by client only libraries, say `Feature` from Leaflet for example.

**Comment by eric-burel** [comment]
It seems that [`import type`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#-type-only-imports-and-export) syntax could be a solution (not yet tested).

**Comment by essential-randomness** [comment]
I've tried `import type` (in a similar situation with QuillJS), but it seems like it's a TS 3.8 feature and I believe Next's TS is behind. There might be a way around it, but I've personally decided to wait for now.

**Comment by theone3nu** [comment]
I am able to show react leaflet map using dynamic using next.js. But i am not able to show marker as i am getting object module in the marker path. Any way to fix this please?

**Comment by eric-burel** [comment]
@theone3nu Are you dynamically loading the Marker component? Instead what I do is using `dynamic` as late as possible, eg around my `MyMap` component when I use it in a page. Inside `MyMap`, I import all leaflet stuffs as usual.

**Comment by theone3nu** [comment]
> @theone3nu Are you dynamically loading the Marker component? Instead what I do is using `dynamic` as late as possible, eg around my `MyMap` component when I use it in a page. Inside `MyMap`, I import all leaflet stuffs as usual.

I have loaded my component using dynamic like this. 
`const MapSearch = dynamic(import('../../components/Map'), {
  ssr: false,
  loading: () => (
    <div style={{textAlign: 'center', paddingTop: 20}}>
      Chargement…
    </div>
  )
})`

Only marker image is not coming it is  coming as http://localhost:3000/_next/static/media/marker-icon.1e8408af1a34bdf614570719b0d6e5ce.png%22)marker-icon.png 404 (Not Found). I can inspect the element and see img is there but icon path is not getting. Please help.

**Comment by JanKaifer** [comment]
> I've tried `import type` (in a similar situation with QuillJS), but it seems like it's a TS 3.8 feature and I believe Next's TS is behind. There might be a way around it, but I've personally decided to wait for now.

Next.js currently uses `"typescript": "4.8.2"` so you should be able to use import type` now.
