### ISSUE TITLE
Page files with no write permission are silently ignored in dev

### ISSUE THREAD

**Issue by denis-sokolov** [vercel/next.js#11543]
If a page file has no write permission, the development server silently ignores it and renders 404.

Search Keywords: permissions, writable, +w, dev, chmod, user, group, 404, page not found.

## Reproduction
1. npm init next-app
(1b. npm run dev, open http://localhost:3000/, see welcome page)
2. chmod -w pages/index.js
3. npm run dev
4. Open http://localhost:3000/

## Actual
5. See 404.

## Expected
5. See welcome page

## System information
macOS 10.14.6
next@9.3.3

**Comment by timneutkens** [comment]
Seems like an edge case, feel free to investigate/pr

**Comment by emaohn** [comment]
I'm new to open source--could I work on this?

**Comment by talentlessguy** [comment]
I think I could try working on this, will try to submit the PR

**Comment by Timer** [comment]
This might be a problem with the upstream `watchpack` dependency, too. I'd start by checking that.

**Comment by talentlessguy** [comment]
@Timer thanks for your tip! I'll try checking watchpack outside of Next.js and see if the issue comes from that

**Comment by talentlessguy** [comment]
@Timer I've read the whole watchpack source code, doesn't look like it's the root of this issue. Watchpack doesn't merge files, it only triggers events, checks for file stats etc.

So I added a `checkPagePermissions` function instead. The problem now... is that such check is verryyy sloow. My own integration test was run for ~1s, now it takes ~4s.

I did such implementation:

```ts 
async checkFilePermissions(dir: string) {
    const pages = await collectPages(
      join(dir, '/pages'),
      this.nextConfig.pageExtensions
    )

    for (const page of pages) {
      fs.access(join(dir, `/pages${page}`), fs.constants.W_OK, err => {
        if (err) throw new Error(`Cannot write: ${err}`)
      })
    }
  }
```

And then run in `run` function before any checking ts, running watcher, etc.

For some reason this operation takes a lot of time, so I'm not sure if I did things properly

**Comment by balazsorban44** [comment]
This does not seem to be the issue anymore. The page renders fine, although as pointed out this sounds like an extreme use case, as you would generally want to be able to edit your files in development mode. :shrug:  Please try upgrading to `latest`
