### ISSUE TITLE
Custom server with multiple next.js apps hangs on startup after upgrading from 9.3.3 to 9.3.4

### ISSUE THREAD

**Issue by kidrecursive** [vercel/next.js#12084]
# Bug report

## Describe the bug

A custom server that creates/prepares two or more NextJS apps hangs after upgrading from 9.3.3 to 9.3.4.

## To Reproduce

Example: https://github.com/kidrecursive/nextjs-multiple-apps 

Clone the repository, install the dependencies, and run `npm start`. The `prepare` promises for the two next apps never resolve. Roll back next with `npm install next@9.3.3`, remove the `.next` build folders from both apps, and restart; the server starts and serves both apps.

## Expected behavior

The server starts and serves both next.js apps

## System information

- OS: OSX 10.15.4
- Version of Next.js: 9.3.4
- Version of Node.js: 12.16.1

**Comment by PiotrAdamus** [comment]
We have the same problem, i debugged it a little bit and it seems to stop at enabling hot reload, probably it want's to register hooks on the same port's as the first application

**Comment by kidrecursive** [comment]
I looked into this further and updated the original issue. One thing I left out in recreating was the step of deleting the `.next` build folders inside of the apps after changing the next.js version.

https://github.com/zeit/next.js/releases/tag/v9.3.4 is the tag that appears to have the changes in it that prevent the previous behavior from working, I'll take a look here next.
