### ISSUE TITLE
Stream rendering to reduce TTFB and CPU load

### ISSUE THREAD

**Issue by ghost** [vercel/next.js#1209]
I suggest to stream-render `pages > 50KB` [(hypothetical stream overhead)](https://github.com/aickin/react-dom-stream#when-should-you-use-react-dom-stream) to reduce TTFB and CPU load.

- Inferno offers `streamAsString`, `streamAsStaticMarkup`, `streamQueueAsString`, `streamQueueAsStaticMarkup` with [inferno-server (master)](https://github.com/infernojs/inferno/blob/master/packages/inferno-server/src/index.ts). As of 1.2.1, [the stream renderer was experimental and 10-15% slower than `renderToString`](https://github.com/infernojs/inferno-website/blob/master/src/docs/api/inferno-server.md#render-stream-api). Should wait for 1.3 (currently [RC3](https://github.com/infernojs/inferno/releases/tag/v1.3.0-rc.3)).
- React with [aickin/react-dom-stream](https://github.com/aickin/react-dom-stream), which replaces `renderToString` and `renderToStaticMarkup`.
- [thysultan/dio.js](https://github.com/thysultan/dio.js) with [`renderToStream`](https://github.com/thysultan/dio.js#rendertostream) [(SSR/renderToStream.js)](https://github.com/thysultan/dio.js/blob/master/src/SSR/renderToStream.js).

It would supersede https://github.com/zeit/next.js/pull/767. Preact does not support streaming (https://github.com/developit/preact/issues/23#issuecomment-226954130).

**Comment by arunoda** [comment]
One thing to mention..

Stream rendering usually won't add much CPU improvements since the amount of work to be done is the same. But it'll reduce the response time.

It's a pretty good idea to provide a way to customize the SSR rendering system. But I think for now, we'll stick with the React's renderToString() methods by default.

This is something we could do after 2.0.

**Comment by flagello** [comment]
> Stream rendering usually won't add much CPU improvements since the amount of work to be done is the same.

> _from [aickin/react-dom-stream](https://github.com/aickin/react-dom-stream)_
>
> One call to ReactDOM.renderToString can dominate the CPU and starve out other requests. This is particularly troublesome on servers that serve a mix of small and large pages.

Wouldn't streaming sensibly reduce memory allocation and CPU usage for large pages by being both asynchronous and partial?

**Comment by webular** [comment]
Thought this was along the same lines.  Has anyone tried [https://github.com/FormidableLabs/rapscallion](https://github.com/FormidableLabs/rapscallion) ?

> It provides a streaming interface so that you can start sending content to the client immediately.

Other features from the docs: 

> - Rendering is asynchronous and non-blocking.
> - Rapscallion is roughly 50% faster than renderToString.
> - It provides a streaming interface so that you can start sending content to the client immediately.
> - It provides a templating feature, so that you can wrap your component's HTML in boilerplate without giving up benefits of streaming.
> - It provides a component caching API to further speed-up your rendering.
>

**Comment by gcpantazis** [comment]
Added an example of Rapscallion in #2279... can confirm that Rapscallion + Next is insane. Streamed/promise-based render is awesome, but Component-level caching is a game-changer for us... :godmode:

**Comment by buzinas** [comment]
Now that React 16 has its own `renderToNodeStream`, it would be a huge advantage for next.js to add an option to use it instead of `renderToString`. What do you think, @timneutkens?

**Comment by timneutkens** [comment]
It's on our list of things to add already 👍

**Comment by MicroBenz** [comment]
Any news about this?

**Comment by timneutkens** [comment]
https://github.com/zeit/next.js/pull/4074#issuecomment-466996162

**Comment by gustavoteodoro** [comment]
Any news?

**Comment by revskill10** [comment]
Next.js needs to expose custom `render` (with `renderToString` as default renderer` in order for user to use their custom async renderer i think.

**Comment by bruceman** [comment]
any roadmap / plan of streaming rendering support? so expected have this in next.js .

**Comment by timneutkens** [comment]
The is pending on the React team implementing React Fizz / their plan for it.

**Comment by StarpTech** [comment]
@timneutkens What the issue, PR to track here?

**Comment by lolcoolkat** [comment]
From Facebook's blog post, published on August 8th 2019
https://reactjs.org/blog/2019/08/08/react-v16.9.0.html

**An Update on Server Rendering**
We have started the work on the new Suspense-capable server renderer, but we don’t expect it to be ready for the initial release of Concurrent Mode. This release will, however, provide a temporary solution that lets the existing server renderer emit HTML for Suspense fallbacks immediately, and then render their real content on the client. This is the solution we are currently using at Facebook ourselves until the streaming renderer is ready.

**Comment by manan25386** [comment]
Is there any update or any other method to implement renderToNodeStream in next.js ?

**Comment by superkoh** [comment]
Is there any update?

**Comment by OutThisLife** [comment]
<3

**Comment by aluminick** [comment]
Any update?

**Comment by pepf** [comment]
@StarpTech I'd looked a bit into this (curious for this feature as well!) and it looks like the react team is working on something called [react-flight](https://github.com/facebook/react/tree/master/packages/react-flight), which will probably be the base for the streaming solution we are waiting for here :)

react-flight:
> This is an experimental package for consuming custom React streaming models.


The relevant PR's that shine some light on the inner workings, interpreted by me (not an expert in any of this 🙈 )
[#17285](https://github.com/facebook/react/pull/17285): Basic api for flight, the server should be able to stream everything as a string, but leave placeholders for the chunks that are asynchronously resolved on the server. An incomplete, yet interesting, syntax for how react would know from a stream what data type it actually represents is over [here](https://github.com/sebmarkbage/react/blob/387c233884d76dd55aeec1cb4803fe6610247b90/packages/react-server/src/ReactFlightServer.js#L26).

[#17398](https://github.com/facebook/react/pull/17398) More recent PR, adds an api for Chunks so (if you're feeling lucky) you could try that part out yourself. Not sure how everything would come together but nevertheless I'm kinda happy with seeing all this work being done :)

_This might be slightly off-topic, but hopefully interesting for people subscribing to this issue :)_

**Comment by StarpTech** [comment]
@pepf thanks for the info!

**Comment by egemon** [comment]
Hm. Thank u all guys, interesting info. I am just thinking why should NextJS wait for React support SSR for suspense and stuff, and not just use streamAsString now?

**Comment by wis** [comment]
@arunoda I think it will reduce memory consumption, very important for low memory (FaaS) lambda functions. I see this as the obvious next optimization-to-lower-TTFB/latency after geo-routing to origin (lamdas in my case).

**Comment by alexvandervegt** [comment]
Any news about this?

**Comment by ducdev** [comment]
Any news?

**Comment by nathan-king** [comment]
Any news guys? :P

**Comment by switz** [comment]
Given that react suspense feels like it may never come out, is there any way we can revisit this? I'm seeing initial render times of 800-1000ms on fairly generic, low-content pages (that are rendered from a serverless function on vercel). Streaming the HTML in theory could bump up that initial point of contact and lead to much much faster perceived first-load ux.

<img width="239" alt="image" src="https://user-images.githubusercontent.com/990166/85966060-b0250e80-b98c-11ea-81a2-9943b11fbdb0.png">

**Comment by tills13** [comment]
Is that a limitation of Vercel rather than NextJS? Does Vercel fall victim to the same sort of cold-startup that Lambda does? My team runs a bunch of content heavy sites and our timings are under 50ms for the whole request. I don't think streaming is going to be a silver bullet here.

**Comment by switz** [comment]
I don't expect it to be a silver bullet, but it certainly would be a welcome improvement.

**Comment by wis** [comment]
50ms sounds really low and relatively insignificant to optimize compared to the mentioned cold-start times, but 50ms is a lot when rendering at edge with something like Cloudflare Workers (it is as much as the ping to the nearest Cloudflare edge location, or at least half), Cloudflare Workers respond very quickly, typically in under 5 milliseconds, when cold starting. In contrast, both Lambda and Lambda@Edge functions can take over a second to respond from a cold start.
I know this does not make a better case for Varcel (which builds its own cdn) employed developers of next.js to prioritize this.

**Comment by switz** [comment]
Is there any documentation or repositories where people have successfully deployed next.js to cloudflare workers? I did some googling and couldn’t find much on it. That would be amazing.

**Comment by tills13** [comment]
> 50ms sounds minuscule and relatively too insignificant to optimize compared to the mentioned cold-start times

To clarify, I wasn't complaining about my 50ms response times - I was just pointing out that NextJS' SRR is relatively performant even of north of 3k requests / minute for content-heavy pages, so Switz's problem might lay elsewhere. 

> Is there any documentation or repositories where people have successfully deployed next.js to cloudflare workers

I would also be interested in that. We're currently running in Fargate but pushing our app to the edge would be the next logical step.

**Comment by huggler** [comment]
Eu fiz todas as melhorias possiveis dentro do meu HTML e o tempo de resposta do servidor esta altissimo! :(

**Comment by dimuska139** [comment]
@huggler you can combine [this example](https://github.com/vercel/next.js/tree/canary/examples/custom-server-express) with [cacheable-response](https://www.npmjs.com/package/cacheable-response). You can use Redis (or in-memory cache for example) to store html in cache. It improves server response time.

**Comment by dennisroethig** [comment]
> Is there any documentation or repositories where people have successfully deployed next.js to cloudflare workers? I did some googling and couldn’t find much on it. That would be amazing.

@switz @tills13  did you check out https://fab.dev/ ? We played with it early 2020 and it was in pre-release state, but they seem to have come pretty far. One of the limitations back them was Cloudflare itself, but things might have changed by now.

**Comment by tills13** [comment]
Haven't looked in a while. Would have to reevaluate. Last time I looked, there were some pretty serious tradeoffs.

I am also keeping my eye on https://github.com/flareact/flareact.

**Comment by nikhiltech** [comment]
Any update on this?

**Comment by tomsoderlund** [comment]
Hi @timneutkens any update on this issue? Is React Fizz still the solution you’re waiting for?

(I have a high-traffic site that currently scales really poorly due to `renderToString`)

**Comment by idfunctor** [comment]
@timneutkens I would like to echo the same concern as @tomsoderlund's. If Next isn't deciding to support it any time soon; do you think it's a wise idea for me to run a fork of Next that supports streaming or would you advise against it?

**Comment by Kavian77** [comment]
Hi
Any update on this?
No one is gonna answer us? :)

**Comment by karlAlnebratt** [comment]
Yes any update?

**Comment by timneutkens** [comment]
Still this: https://github.com/vercel/next.js/issues/1209#issuecomment-485270144

Streaming rendering will eventually be added once the React team published the new version of the server renderer, this is currently on the experimental channel.

**Comment by omBratteng** [comment]
If I'm not wrong, it seems it might come in [React 18](https://reactjs.org/blog/2021/06/08/the-plan-for-react-18.html)?

**Comment by datlieu110** [comment]
Any update on this?

**Comment by timneutkens** [comment]
Streaming rendering support is currently being worked on by @devknoll, @shuding, and @huozhi. We'll share when there are relevant proposals here.

**Comment by yulafezmesi** [comment]
Any update on this?

**Comment by matthxc** [comment]
With the launch of Next.js 12v I think this will come out of the box now: https://nextjs.org/blog/next-12#server-side-streaming Next.js 12 introduces a bunch of new performance features, including Suspense and SSR streaming and much more, so I think this issue can be marked as resolved?

**Comment by omBratteng** [comment]
It is under an experimental flag, and requires React 18 which is in alpha. So I'd say it is far from stable. And I wouldn't close this issue until both are available as stable.

**Comment by pats** [comment]
any news?

**Comment by timneutkens** [comment]
The recently launched App Router supports streaming rendering by default, you can add `Suspense` boundaries to flush early loading states.

@kostia1st we're currently not planning to add streaming to the Pages Router as we had to add specific APIs (i.e. metadata) in order to make early flushing work. Without Server Components you can't stream in data so you wouldn't get clear benefits from having it for Pages like you do in App Router.

I'm going to close this issue now as it has been shipped 👍
