### ISSUE TITLE
Can't get correct statusCode on custom error page when running on Vercel

### ISSUE THREAD

**Issue by byte-artisan** [vercel/next.js#12199]
# Bug report

## Describe the bug

When trying to access http statusCode at a custom error page, as illustrated on the [customizing-the-error-page](https://nextjs.org/docs/advanced-features/custom-error-page#customizing-the-error-page) document page, i always get status code 200.

## To Reproduce
A minimal working example is available at [vercel](https://vercel.com/byte-artisan/nextjs-test-statuscode/quxt8a6ib/source).

To reproduce just navigate to [badurl](https://nextjs-test-statuscode-quxt8a6ib.now.sh/badurl)

## Expected behavior
The page should display 404 error code.

## System information
- running on Versel

## Additional context
It works well if run in local server, either with 

> npm run start

 or 

> now  dev

It looks that getInitialProps is not being called.

**Comment by timneutkens** [comment]
Looks like it works fine 🤔 
```
curl -I https://nextjs-test-statuscode-quxt8a6ib.now.sh/badurl
HTTP/2 404
content-type: text/html; charset=utf-8
x-robots-tag: noindex
cache-control: public, max-age=0, must-revalidate
content-length: 0
date: Sat, 25 Apr 2020 18:51:02 GMT
x-vercel-cache: MISS
x-now-cache: MISS
age: 0
x-now-trace: zrh1
server: now
strict-transport-security: max-age=63072000; includeSubDomains; preload
```

**Comment by byte-artisan** [comment]
Unfortunately page 404 doesn't work for me because is not a SSR page.
This this mean that i can expect a fix, or should i look for another solution?

**Comment by ijjk** [comment]
Closing as we now recommend `pages/500.js` or `pages/404.js` be used for customizing the status pages on Vercel, updated documentation can be seen here https://nextjs.org/docs/advanced-features/custom-error-page
