### ISSUE TITLE
styles flickering in dev with tailwind + css modules

### ISSUE THREAD

**Issue by tafelito** [vercel/next.js#12448]
# Bug report

## Describe the bug

I'm using tailwindcss with css modules and I notice that the first time the page loads, all my styles are not loaded. Trying to figure it put what was happening, I run the tailwindcss example and added a style from a css module and it happens there too, even when built for prod.

## To Reproduce

Run the example from https://github.com/zeit/next.js/tree/canary/examples/with-tailwindcss

Add a `index.module.css` file with some style

add the styles form the css module in the `index.js` page

## Expected behavior

Without the use of the css modules, all styles are loaded fine the first time, without flickering. Same behavior is expected using css modules

## Screenshots

![May-03-2020 14-06-19](https://user-images.githubusercontent.com/5973652/80921889-51099b80-8d47-11ea-9aab-d1597e4820f9.gif)

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: v9.3.6
- Version of Node.js: v13.12.0
- Version of tailwindcss: v1.4.4

**Comment by Pytal** [comment]
I suspect this may have something to do with automatic code splitting of css modules 🤔

**Comment by mzygmunt** [comment]
Probably related to https://github.com/zeit/next.js/issues/10268

**Comment by dani97** [comment]
I have used plain css modules for components and styles apply after some ms.

**Comment by Adrianjs42** [comment]
> I have used plain css modules for components and styles apply after some ms.

According to https://stackoverflow.com/a/42969608/943337 i just added an empty script tag and my problem of a sidebar which was popping up at first load, is now solved.
```
import Document, { Html, Head, Main, NextScript } from 'next/document';
import { GA_TRACKING_ID } from '../utils/anayltics';
class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html lang="de">
        <Head>
        </Head>
        <body>
          <Main />
          <NextScript />
          {/* Empty script tag as chrome bug fix, see https://stackoverflow.com/a/42969608/943337 */}
          <script> </script>
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

**Comment by dani97** [comment]
> > I have used plain css modules for components and styles apply after some ms.
> 
> According to https://stackoverflow.com/a/42969608/943337 i just added an empty script tag and my problem of a sidebar which was popping up at first load, is now solved.
> 
> ```
> import Document, { Html, Head, Main, NextScript } from 'next/document';
> import { GA_TRACKING_ID } from '../utils/anayltics';
> class MyDocument extends Document {
>   static async getInitialProps(ctx) {
>     const initialProps = await Document.getInitialProps(ctx);
>     return { ...initialProps };
>   }
> 
>   render() {
>     return (
>       <Html lang="de">
>         <Head>
>         </Head>
>         <body>
>           <Main />
>           <NextScript />
>           {/* Empty script tag as chrome bug fix, see https://stackoverflow.com/a/42969608/943337 */}
>           <script> </script>
>         </body>
>       </Html>
>     );
>   }
> }
> 
> export default MyDocument;
> ```

Thanks @Adrianjs42 the side bar popping in stopped in chrome.

**Comment by webdeb** [comment]
Also related
https://github.com/vercel/next.js/issues/13058

**Comment by fadonascimento** [comment]
There is a workaround to resolve this problem
Create a custom "_document.js" and add the class "no-fouc" in the Html component
Create a custom "_app.js" and add the following code in the "componentDidMount"
```
const removeFouc = (foucElement) => {
      foucElement.className = foucElement.className.replace('no-fouc', 'fouc')
    }
 removeFouc(document.documentElement)
```

Add add this styles in the global styles:

/* Base styles for theme site */
.no-fouc {
  visibility: hidden;
 opacity: 0;
}

.fouc {
 visibility: visible;
 opacity: 1;
}

Html

**Comment by Timer** [comment]
This should be fixed in `next@^9.4.5-canary.15`! Please upgrade and let us know.

**Comment by Prottoy2938** [comment]
@Timer , I have installed `next@^9.4.5-canary.18`. Now the CSS flickering doesn't appear in the **development** mode, but it stays the same on the **production** version. The production version still has the bug.


Note that I'm using **material-ui + css modules**

**Comment by casperle** [comment]
@Prottoy2938 Same here. I made a comment to this issue https://github.com/vercel/next.js/issues/13058#issuecomment-654165987

**Comment by timneutkens** [comment]
> @Timer , I have installed `next@^9.4.5-canary.18`. Now the CSS flickering doesn't appear in the **development** mode, but it stays the same on the **production** version. The production version still has the bug.
> 
> Note that I'm using **material-ui + css modules**
> 
> Heres a version of the app that I've been working on facing this issue: [cluster-11-lwj6nmcgy.vercel.app](https://cluster-11-lwj6nmcgy.vercel.app/) .

Seems this your case is unrelated to css modules / tailwind and more so related to forgetting to implement pre-rendering of material-ui: https://github.com/vercel/next.js/issues/7322#issuecomment-653858948

**Comment by Prottoy2938** [comment]
@casperle , In my case the problem was because I was doing **server side rendering**. I followed this [documentation from material-ui](https://material-ui.com/guides/server-rendering/) and fixed the issue

**Comment by talaikis** [comment]
With v9.4.5-canary.28 not flickering in dev and flickering in production.

**Comment by dalisalvador** [comment]
Having the same issue.... Not solved yet? this is uber frustrating
