### ISSUE TITLE
document.contains does not work in IE 11

### ISSUE THREAD

**Issue by tomdohnal** [vercel/next.js#12777]
# Bug report

## Describe the bug

Using `document.contains(...)` does not work in IE 11. 

An easy workaround is to use `document.body.contains(...)` instead, so it's not such a big of a deal :)

Anyways, it seems like the `document` object does not inherit the method specified on the `Node` prototype, thus causing the `.contains(...)` call to fail. So it's possible that other calling other methods which `document` inherits from `Node` fails too...

## To Reproduce

```
  const ref = useRef(null);
  useEffect(() => {
    console.log(document.body.contains(ref.current)); // works fine even in IE 11
    console.log(document.contains(ref.current)); // fails in IE 11
  }, []);

  return <div ref={ref} className="container"></div>;
```

1. Full repro at https://github.com/tomdohnal/document-contains-repro

## Expected behavior

Using `document.contains(...)` should work even in IE 11.

## System information

- OS: [Windows]
- Browser (if applies) [IE 11]
- Version of Next.js: [9.3, 9.4]
- Version of Node.js: not applicable...

**Comment by tomdohnal** [comment]
Anyways, it's already my third bug related to broken things in IE 11 :) I wonder if I should keep on reporting those bugs.
The "workarounds" on my side have been quite straigforward so far (including an extra pollyfill etc.) and I don't know if it's really realistic to expect that Next.js ensures IE 11 compatibility with *all* the "modern" features and specs...

So I'd like to know what's your take on that :)

**Comment by vitorhsb** [comment]
Please consider reading https://developer.mozilla.org/en-US/docs/Web/API/Document . 

It indicates that:

> Internet Explorer does not support all methods from the Node interface in the Document interface:
> 
> Document.contains
> As a work-around, document.body.contains() can be used.

I believe you should be using only `document.body.contains(ref.current)` as a best practice, since this should not be made as a polyfill.

**Comment by tomdohnal** [comment]
Well, I know what the workaround is :) Nonetheless, using `document.contains(...)` is part of the standard so I'd kind of expect it work out of the box (be pollyfilled).

**Comment by Timer** [comment]
Hmm, there's a larger issue at play here. We don't really support IE11 as a development target... only production.

Happy to take a PR fixing this.

**Comment by tomdohnal** [comment]
Well, this particular issue (as well as https://github.com/zeit/next.js/issues/12713 and https://github.com/zeit/next.js/issues/12722) were present even on the production build...

I can look into this issue as well as the other 2 I created if you'd be interested :) 
However, I'm not sure if the three issues I created are a comprehensive list of the JS/DOM specs which are not working in IE 11. These were only the ones that I discovered were not working in our app. 

So I'd say it's quite likely that there are some more which are not working... I'll try to send a PR for the ones which I discovered but searching for what's working and what's not working is beyond my time capabilities :)

**Comment by tomdohnal** [comment]
So, I tried to add the [document.contains](https://github.com/ljharb/document.contains/) polyfill  but it seems to be broken in IE11. So I created a pull request in their repository which fixes it https://github.com/ljharb/document.contains/pull/12.

Nonetheless, if we want to polyfill the `document.contains` behaviour we either need to wait for it to be merged or use our own fork of it.
