### ISSUE TITLE
next.js 9.4 `fetch` does not support URL as parameter

### ISSUE THREAD

**Issue by Evian-Zhang** [vercel/next.js#12962]
# Bug report

## Describe the bug

After upgrading to next.js 9.4, I see the built-in `fetch` support, so I removed `node-fetch` dependency. However, I found that the build-in `fetch` does not support URL as parameter:

```typescript
const myUrl = new URL("https://some-url");
const res = await fetch(myURL);
```

Then the typescript compiler turns out error:

Argument of type 'URL' is not assignable to parameter of type 'RequestInfo`.

It seems that using URL as `fetch` argument is very nature, although I can use `.href` to come through it.
## Expected behavior

One can use URL as built-in `fetch` parameter.

## System information

- OS: Ubuntu 18.04
- Version of Next.js: 9.4.0
- Version of Node.js: 13.14.0

**Comment by maysam** [comment]
how about just

```
const myUrl = "https://some-url";
const res = await fetch(myURL);

```

**Comment by Evian-Zhang** [comment]
> how about just
> 
> ```
> const myUrl = "https://some-url";
> const res = await fetch(myURL);
> ```

Yes, I can do this to achieve my goal, but as a general tool, I think fetch should support URL type.

**Comment by domainio** [comment]
same as here...

**Comment by leerob** [comment]
Just confirmed with a simple example this is working on `next@canary` 👍 

```js
import Link from "next/link";

export default function IndexPage(props) {
  console.log(props.todos);
  return (
    <div>
      Hello World.{" "}
      <Link href="/about">
        <a>About</a>
      </Link>
    </div>
  );
}

export async function getStaticProps() {
  const myUrl = new URL("https://jsonplaceholder.typicode.com/todos/1");
  const response = await fetch(myUrl);
  const todos = await response.json();

  return {
    props: { todos }
  };
}

```
