### ISSUE TITLE
Unexpected onLoad attribute behaviour in next/head

### ISSUE THREAD

**Issue by joe-bell** [vercel/next.js#12984]
# Bug report

## Describe the bug

In my project [`raam`](https://github.com/joe-bell/raam/pull/20/files) I'm tying set `"Inter"` as my font by linking to a stylesheet from Google Fonts.

In `Head` (a component that extends `next/head`) I'm using:
```jsx
<link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin="" />
<link
  href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
  rel="stylesheet"
/>
```
(note the `preconnect` to the actual font assets, then the `display=swap` which is intended to show the fallback font until the loaded font is swapped in)

When I then go to view the page (in Firefox particularly) I see a flash of unstyled/invisible text:
https://raam-git-chore-inter.joebell.now.sh/

## Screenshots

![ezgif-2-8ea6320f12f1](https://user-images.githubusercontent.com/7349341/82128783-71fdd200-97c6-11ea-9b46-2b0d7713132f.gif)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://raam-git-chore-inter.joebell.now.sh/ (in Firefox where this is more visible)
2. Hard reload and watch the behaviour of fonts

## Expected behavior

The system font is seen first, and 'swapped' to Inter on load.

## System information

- OS: macOS
- Browser (if applies): Firefox 75
- Version of Next.js: 9.3.3
- Version of Node.js: 13.8.0

## Additional context

I appreciate there's a lot of variables here: Theme UI, Google Fonts, Now.sh, Next.js, but it would be good if we can figure out the root cause here for others using Next.js. If it's something that could be resolved by adding some documentation I'd be more than happy to do so.

Thanks again for all of the team's hard work on Next.js, it's a real pleasure to work with

### Prior reading

- @leerob's ["Thing's I've learned Building Next.js apps"](https://leerob.io/blog/things-ive-learned-building-nextjs-apps) 

### Example

- Source: https://github.com/joe-bell/raam/pull/20
- Demo: https://raam-git-chore-inter.joebell.now.sh/

**Comment by joe-bell** [comment]
Did some testing on other devices: iPad OS and iOS have no issues. Seems like it only occurs on macOS but I can’t verify Windows

**Comment by joe-bell** [comment]
As an update I've tested this new approach, which is a mix of font-loading performance suggestions I've found online:

```jsx
<link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin="" />
<link
  rel="preload"
  href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
  as="style"
/>
<link
  href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
  rel="stylesheet"
  media="print"
  // // Next.js doesn't like this but it allows us to load CSS asynchronously
  // @ts-ignore
  onLoad="this.media='all'"
/>
```

| Before | After |
|--------|-------|
| <img width="456" alt="Screenshot 2020-05-17 at 13 40 49" src="https://user-images.githubusercontent.com/7349341/82142623-618d3c00-9846-11ea-95dc-90b70a031afb.png">    | <img width="455" alt="Screenshot 2020-05-17 at 13 58 06" src="https://user-images.githubusercontent.com/7349341/82142639-78cc2980-9846-11ea-8a4f-2bd298a6ef18.png">   |

It's made a significant improvement but I think it's fair to say this isn't a Next.js issue anymore. **However**, TypeScript doesn't like my `onLoad="this.media='all'"` as it doesn't accept string values.

Am I doing this wrong or do I need to raise a PR to update types?

**Comment by joe-bell** [comment]
After some further investigation with @csswizardry, we found that when JS is disabled the `onload` attribute is missing entirely:

<img width="521" alt="Screenshot 2020-05-18 at 16 47 29" src="https://user-images.githubusercontent.com/7349341/82220482-5fe77500-9927-11ea-94fc-4a51bcb04a2a.png">

What's even stranger is once JS is enabled, this behaves as expected **but** moves further down the `<head>` element:

<img width="527" alt="Screenshot 2020-05-18 at 16 48 03" src="https://user-images.githubusercontent.com/7349341/82220567-7b528000-9927-11ea-9663-b251a114b386.png">

This leads me to think `next/head` is rendering without `onLoad` on the server, then shuffling around things upon hydration

**Comment by timneutkens** [comment]
> This leads me to think next/head is rendering without onLoad on the server, then shuffling around things upon hydration

`onload` is handled by React so I assume it's read as if it's a React event handler.

**Comment by joe-bell** [comment]
Thanks for getting back to me @timneutkens, I was just about to update this issue as I've managed to find a solution in the meantime. I'll write this up in a blog post to share with others as I think it would be pretty useful

Essentially I used Josh W Comeau's `useHasMounted()` hook to detect page mount, then applied as follows:
```tsx
import * as React from "react";
import NextHead from "next/head";
import { useHasMounted } from "../hooks";

const googleFontsUrl =
  "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap";

const Head: React.FC = () => {
  const hasMounted = useHasMounted();

  return (
    <NextHead>
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="anonymous"
      />
      <link rel="preload" as="style" href={googleFontsUrl} />
      <link
        href={googleFontsUrl}
        rel="stylesheet"
        media={!hasMounted ? "print" : "all"}
      />
    </NextHead>
  );
};

export default Head;
```

This avoids FOUT all together

**Comment by joe-bell** [comment]
In the meantime, I've built [`next-google-fonts`](https://github.com/joe-bell/next-google-fonts) as a workaround

**Comment by willemmulder** [comment]
Copied from #16065 where I have a problem related to what OP is trying to do. If I want to use 

```CSS
<link rel="preload" href="https://..." as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="https://...></noscript>
```

to make loading CSS async, that does not work because I'd have to rework that to using onLoad with a function, but that function is never executed. So

1. Is there a way to just insert the above HTML as-is, without having to comply to JSX?
2. If not, is there a way to make onLoad work?
3. If not, is there another easy way to make external CSS load async?

**Comment by dsacramone** [comment]
> Copied from #16065 where I have a problem related to what OP is trying to do. If I want to use
> 
> ```css
> <link rel="preload" href="https://..." as="style" onload="this.onload=null;this.rel='stylesheet'">
> <noscript><link rel="stylesheet" href="https://...></noscript>
> ```
> 
> to make loading CSS async, that does not work because I'd have to rework that to using onLoad with a function, but that function is never executed. So
> 
> 1. Is there a way to just insert the above HTML as-is, without having to comply to JSX?
> 2. If not, is there a way to make onLoad work?
> 3. If not, is there another easy way to make external CSS load async?

Did you find a solution to this? I have the same need.

**Comment by willemmulder** [comment]
@dsacramone Nope, I did not find anything yet. Maybe the @tsignore annotation referenced in the 'fix build' commit above works?

**Comment by ssylvia** [comment]
> `onload` is handled by React so I assume it's read as if it's a React event handler.

@timneutkens At least on the client, the react elements are converted to regular DOM elements and all props are converted regular HTML attributes: https://github.com/vercel/next.js/blob/85499b5375dace853e236877510ea6a306014a90/packages/next/client/head-manager.ts#L9-L27

This causes the scope of the function to be lost as it is converted to a string with the `el.setAttribute`. Also, due to the race condition, we would need to make sure the `onload` is set before the href is set.

**Comment by felipedeboni** [comment]
Following seems to work

`
<style dangerouslySetInnerHTML={{
  __html: `</style>
    <link
      rel="stylesheet"
      href="https://...."
      media="print"
      onload="this.media = 'all';"
    />
    <style>`
}}></style>
`

**Comment by rishi-raj-jain** [comment]
Or you could do something like: https://github.com/rishi-raj-jain/rishi-raj-jain.github.io/blob/framer/pages/_app.js#L11 & https://github.com/rishi-raj-jain/rishi-raj-jain.github.io/blob/framer/pages/_app.js#L86

**Comment by balazsorban44** [comment]
Next.js comes with Font Optimization out-of-the-box now, this should not be necessary.

Please check out our docs: https://nextjs.org/docs/basic-features/font-optimization

**Comment by ssylvia** [comment]
@balazsorban44 Please reopen this issue. There are several other use cases besides fonts that would benefit from the `onLoad` case. Also, font optimization only works if the font is known at build time or if it comes from Google Fonts and Typekit. For example, our team runs a website builder on NextJS. The website creators can choose a Google Font configuration per site which is not known at build time. There are also several other popular web font loaders that are not included in font-optimization.

**Comment by balazsorban44** [comment]
Ah, I did not realize from your description you were referring to `next/head`, instead of the one in `_document`.

The documentation says this clearly:

> `title`, `meta` or any other elements (e.g. `script`) need to be contained as direct children of the Head element, or wrapped into maximum one level of `<React.Fragment>` or arrays—otherwise the tags won't be correctly picked up on client-side navigations.

https://nextjs.org/docs/api-reference/next/head

The easiest solution here is to just create your custom `Head` component with the `next/head` as the most outer component like so:

```js
// HeadMeta.js
import Head from "next/head"

export default function HeadMeta(props) {
  return (
    <Head>
      <title>{props.title}</title>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      />
    </Head>
  )
}
```

Note, that Fonts should probably be loaded in `_document`, not per page.

**Comment by balazsorban44** [comment]
Could someone add a reproduction that I could clone and test with the newest version of Next.js? (as of writing `12.0.8`)? I only see a deployed version that is more than a year old.
