### ISSUE TITLE
Make build stats machine readable

### ISSUE THREAD

**Issue by wereHamster** [vercel/next.js#13265]
# Feature request

## Is your feature request related to a problem? Please describe.

The `next build` command prints the sizes of the page JS code to stdout This is very useful to see, but that information is not easily accessible to other tools for further processing. In particular, I'd like to save those numbers in a database and track them over time.

## Describe the solution you'd like

The `next build` command already generates a bunch of json files in the .next folder. My preferred solution would be another such json file which contains the same information as is being printed to stdout, in a structured, stable format.

## Describe alternatives you've considered

Parsing `next build` stdout is not robust enough, and neither is peeking into the .next folder.

**Comment by darshkpatel** [comment]
I'd love to take this up

Here's preliminary proposed JSON structure example
```
{
	"pages": {
		"/": {
			"size": "2.52 kB",
			"firstLoadJS": "61.2 kB",
			"type": "Server"
		},
		"/404": {
			"size": "3.25 kB",
			"firstLoadJS": "61.9 kB",
			"type": "Static"
		},
		"/hello": {
			"size": "4.6 kB",
			"firstLoadJS": "101.1 kB",
			"type": "SSG"
		}
	},
	"sharedFirstLoadJS": {
		"static/pages/_app.js": {
			"size": "2.52 kB"
		},
		"css/67e8b735642195a8a628.css": {
			"size": "3.52 kB"
		},
		"chunks/framework.4dd100.js": {
			"size": "1.52 kB"
		},
		"runtime/main.6df4c2.js": {
			"size": "6.54 kB"
		}
	}
}
```
