### ISSUE TITLE
Option to disable error overlay 

### ISSUE THREAD

**Issue by acifani** [vercel/next.js#13387]
# Feature request

## Is your feature request related to a problem? Please describe.

Hey, the new error overlay is great and I am very thankful of you guys for adding such a feature. 
The problem: it's not that great when running automated tests (with something like Cypress). Any unhandled error/promise will cause the overlay to pop up (it was not the case with the previous react error overlay), causing the test to fail - even when the error originates from some third party code that we cannot handle ourselves

## Describe the solution you'd like

Either a flag to disable the overlay altogether or a global hook to handle the exception ourselves and decide if it's worth throwing or not, like [Cypress does](https://docs.cypress.io/api/events/catalog-of-events.html#Uncaught-Exceptions)

## Describe alternatives you've considered

We have opted to run the tests in prod mode for now, but that's something we'd prefer not to do, because of the development mode goodies that we can use for debugging. 

## Additional context

In our case, the error being thrown is a fetch error from a third party library  to a domain we block in our test config

**Comment by timneutkens** [comment]
Running tests against a development mode server is really uncommon and will allow you to ship bugs to production 🤔

**Comment by acifani** [comment]
@timneutkens totally agree, we have multiple test steps before shipping to production: this will ideally run on pushes/PRs, then we have another one for our staging environment which will run as close to production as possible. 

As integration/e2e tests are both hard to write and slow to fix, we prefer fast iteration locally while making sure to run every test in staging before shipping to production

**Comment by timneutkens** [comment]
> @timneutkens totally agree, we have multiple test steps before shipping to production: this will ideally run on pushes/PRs, then we have another one for our staging environment which will run as close to production as possible.
> 
> As integration/e2e tests are both hard to write and slow to fix, we prefer fast iteration locally while making sure to run every test in staging before shipping to production

But even then the error overlay is shown when errors happen that would crash at runtime 🤔 So you'd fix them, if you're seeing the error overlay in other cases that'd be unexpected

**Comment by acifani** [comment]
@timneutkens actually, that's not always the case for us 😄 we also get the overlay for blocked networks calls (Failed to fetch) and I believe for errors that wouldn't affect the main application as well (think 3rd parties, but I'll have to double check that)

These were errors that did not show up on the old overlay and are not part of the "proper" react application code

**Comment by justincy** [comment]
I also see the error overlay for failed fetch requests.

**Comment by timneutkens** [comment]
> I also see the error overlay for failed network requests.

Because they're uncaught errors in your code, which is expected to show the overlay.

**Comment by acifani** [comment]
> > I also see the error overlay for failed network requests.
> 
> Because they're uncaught errors in your code, which is expected to show the overlay.

Agree, but that's why we might need an escape hatch or a way to control when to show the overlay. Sometimes, you're not in control of the code that is failing and you can't handle those errors at all

**Comment by haymez** [comment]
I'm getting the error overlay on failed network requests, which for us is pretty pointless. We handle the network errors in our thunk actions to dispatch a failure action which can then be handled appropriately in our app. We then rethrow the error from the action so that if we're awaiting the promise we can handle it however we want. Most of the time we don't need to handle the errors because they are expected in certain scenarios. Getting an error overlay for all of these just gets in the way. I never got the overlay before for network failures. Having a way to control when the modal takes over the whole page would be nice.

**Comment by filipesmedeiros** [comment]
Although I agree that having this option would never be bad (more config is rarely bad, especially if it doesn't get in the way), I do agree that the error popping up should first be solved inside your code. I'm not saying that you haven't tried or anything, just that I think it's probably _very_ rare for an uncaught exception to be uncatchable. You can always wrap it, right? Or for example I've had to dynamic import stuff that broke at import time, etc

**Comment by zer0blockchain** [comment]
Were you able to find a way to exclude certain exceptions? We use a library that is notorious for throwing exceptions but continues to work as intended. They are one of the only libraries and we can not just move away from it. It would be ideal to be able to handle these as an exclusion (they happen async/in a Promise).
