### ISSUE TITLE
RFC - add rawBody to NextApiRequest

### ISSUE THREAD

**Issue by mikesol** [vercel/next.js#13405]
# Feature request

As per @timneutkens request, this is an RFC to add `rawBody` to NextApiRequest.

## Is your feature request related to a problem? Please describe.

Currently, there is no way to use both a body parser _and_ recuperate the raw body of a request. This makes things like [securing github webhooks](https://developer.github.com/webhooks/securing/), which rely on calculating a hash based on a raw body, difficult in NextJS.

## Describe the solution you'd like

The solution I proposed in the PR above is to add a raw body field to NextApiRequest.

## Describe alternatives you've considered

The alternative we're currently using is deploying a separate microservice to handle our github webhook. It could be that this feature is outside the scope of nextjs, in which case the separate microservice makes sense.

**Comment by Timer** [comment]
Would [disabling the `bodyParser`](https://nextjs.org/docs/api-routes/api-middlewares#custom-config) be an appropriate action?

This allows you to read the body however you'd like.

**Comment by mikesol** [comment]
Hey! This definitely helps - we were hoping to use the body parser as the body is json, but what we can do as a temporary measure is disable the body parser and then parse the JSON ourselves. Thanks!

**Comment by eknowles** [comment]
I would add to this, I had the same issue with stripe webhooks.
My solution was to reverse the process as described here https://github.com/stripe/stripe-node#testing-webhook-signing
`JSON.stringify(payload, null, 2)`.

**Comment by saiichihashimoto** [comment]
The stringify solution did not work for me. Also, one disabling the bodyParser, `req.body` is undefined, how would one parse the body?
