### ISSUE TITLE
Router.back() not working in new firmware IOS 13,5

### ISSUE THREAD

**Issue by eeeman1** [vercel/next.js#13494]
# Bug report

## Describe the bug

nothing happens when i call an event Router.back()

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. add to component - import Router from 'next/router'
2. call the event - Router.back()
3. nothing will happen after that

## System information

- OS: IOS 13,5
- Browser: safari, chrome
- Version of Next.js: 9.0.2
- Version of Node.js: v10.16.3

**Comment by Timer** [comment]
Can you try on the latest Next.js version? 9.0.2 is older.
