### ISSUE TITLE
Sharing params between nested dynamic routes.

### ISSUE THREAD

**Issue by yassinebridi** [vercel/next.js#13569]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm trying to to create pagination for each category inside my blog, with this structure:
```
pages/[category]/page/[id]
```
the `[category]` page is defined in `pages/[category]/index.tsx`,
the `getStaticPaths` in the [id] page is defined like this:

```
export const getStaticPaths: GetStaticPaths = async () => {
  const posts = getAllPosts(["mainTag"]);
  const rowsPerPage = 7
  const totalResult = posts.length
  const pageCount = Math.ceil(totalResult / rowsPerPage)

  return {
    paths: Array.from({ length: pageCount }).map((_, i) => {
      return {
        params: {
          id: (i + 1).toString(),
          category: ??
        },
      };
    }),
    fallback: false,
  };
};
```
as you can see here, there is no way i can get the category parameter, unless i hard code it.

## Describe the solution you'd like

A way to share the routing params, so it can deeply create pages, without knowing the previews dynamic route. Because in this example, it create category pages, and id pages, separately.

**Comment by revskill10** [comment]
What about you get all `categories` and return all paths from each category then concat the result ?
