### ISSUE TITLE
Static CSS import fails with ERR_FILE_NOT_FOUND in production build

### ISSUE THREAD

**Issue by kokanek** [vercel/next.js#13578]
# Bug report
Everything works just fine when I run 
'next dev' or 'next start' 
Also, 'next export' creates the proper static files, where I can also see the correctly linked css bundle. But when I open index.html, I get error while importing static files.
<img width="613" alt="Screen Shot 2020-05-30 at 3 30 34 PM" src="https://user-images.githubusercontent.com/16059151/83325539-965bb300-a28a-11ea-8ee0-ea30296f4787.png">

Also, deployed the same to github pages using the deploy script: https://kokanek.github.io/portfolio/
```
"deploy": "next build && next export && git add out/ && git commit -m \"Deploy gh-pages\" && git subtree push --prefix out origin gh-pages"
```
But getting the same error there as well. 
<img width="765" alt="Screen Shot 2020-05-30 at 3 40 52 PM" src="https://user-images.githubusercontent.com/16059151/83325709-f868e800-a28b-11ea-93a2-375be619fc63.png">

## Describe the bug
I created a new project using create-next-app. 
Added the <code>_app.js</code> inside the pages folder. 
Also, added a <code>styles.css</code> file and imported it in the _app.js
###  _app.js
```
import '../styles.css'

export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```

The styles.css file contains some basic css:
```
html,
body {
  padding: 0;
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
    Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue,
    sans-serif;
}

* {
  box-sizing: border-box;
}
.container {
  min-height: 100vh;
  padding: 0 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

main {
  padding: 5rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

footer {
  width: 100%;
  height: 100px;
  border-top: 1px solid #eaeaea;
  display: flex;
  justify-content: center;
  align-items: center;
}

footer img {
  margin-left: 0.5rem;
}

footer a {
  display: flex;
  justify-content: center;
  align-items: center;
}
...
<some-more-css>
...
```
Here is the config.js
Added the next-css dependency in order to make it work but it doesn't seem to help.
### next.config.js
```
const withCSS = require('@zeit/next-css')
module.exports = withCSS({
  cssModules: true
})
```

## To Reproduce

1. Clone this repository: https://github.com/kokanek/portfolio
2. checkout the master branch
3. Run the 'npm run build' and 'npm run export' script.
4. Check the /out folder and open the index.html to see the errors.

## Expected behavior
The static files generated in the /out folder should work the same way as the build deployment

## System information

- OS: [e.g. macOS, Windows]
Macos
- Browser (if applies) [e.g. chrome, safari]
Chrome
- Version of Next.js: [e.g. 6.0.2]
9.4.2
- Version of Node.js: [e.g. 10.10.0]

**Comment by jamesmosier** [comment]
Are you just trying to open the `out/index.html` file in your browser on your local computer? If so, this won't work. You need to serve these files on some sort of HTTP server in order for it to load those scripts.

As for why it doesn't work on GitHub pages, your site's url is https://kokanek.github.io/portfolio but Next is looking for scripts at `https://kokanek.github.io/_next/static/css/d4fed0ecf2bef9b3dbc2.css` (notice no `/portfolio` path).
