### ISSUE TITLE
Running `now dev` gives error 'not found: next'

### ISSUE THREAD

**Issue by pranjaljately** [vercel/next.js#13598]
Created a nextjs-blog as per the docs. Can download the code from [here](https://nextjs.org/learn/basics/deploying-nextjs-app/setup)

I am trying to run `now dev` and keep getting the following error: **not found: next**

![image](https://user-images.githubusercontent.com/30666375/83339008-91662600-a2c1-11ea-9a61-92ab0583a113.png)

**OS**: Windows 10 
**Now CLI version**: 19.0.1

**List of project dependencies:** 
- cookie@0.4.1
- date-fns@2.14.0
- gray-matter@4.0.2
- next@9.4.0
- react@16.13.1
- react-dom@16.13.1
- remark@12.0.0
- remark-html@11.0.2

**Comment by TodorTotev** [comment]
Can you please provide a repository to clone so I can reproduce the error?

**Comment by pranjaljately** [comment]
Repo: https://github.com/pranjaljately/nextjs-blog-temp
Or run: `npm init next-app nextjs-blog-temp --example "https://github.com/vercel/next-learn-starter/tree/master/basics-final`

Thanks!

**Comment by pranjaljately** [comment]
I should probably add that I have downloaded and installed the Vercel CLI but same issue when running `vercel dev`

![image](https://user-images.githubusercontent.com/30666375/83340853-ee1f0c00-a2d4-11ea-96f5-a6788db58e78.png)
