### ISSUE TITLE
Error toast hides the background

### ISSUE THREAD

**Issue by mrassili** [vercel/next.js#13728]
# Bug report

## Describe the bug

The new toast introduced in v9.4 seems intrusive and doesn't hide which makes it difficult to see the background when simulating the mobile viewport in chrome

## To Reproduce

1. You should have an error in the console
2. Simulate responsive viewport in chrome

## Expected behavior

it should be closable or not show at all

## Screenshots

<img width="201" alt="Screen Shot 2020-06-03 at 7 05 04 PM" src="https://user-images.githubusercontent.com/25288435/83672006-8109c000-a5cd-11ea-89d7-ca444edc9e67.png">

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of Next.js: 9.4.0
- Version of Node.js: 12.11.1

**Comment by Timer** [comment]
Fixing the error will cause this toast to go away. Once there has been an error, you shouldn't really be interacting with your application any longer.

**Comment by mrassili** [comment]
> Fixing the error will cause this toast to go away. Once there has been an error, you shouldn't really be interacting with your application any longer.

sometimes I have an error that I don't necessarily want to fix at that moment

**Comment by wereHamster** [comment]
@mrassili are those typescript errors or others? You can disable typescript errors during dev and/or production builds through some options in next.config.js.

**Comment by mrassili** [comment]
> @mrassili are those typescript errors or others? You can disable typescript errors during dev and/or production builds through some options in next.config.js.

I am not using TypeScript, I couldn't find an option to disable the new error overlay/toast or fast refresh. I ended up downgrading for a few hours :(
