### ISSUE TITLE
Native Vite Support

### ISSUE THREAD

**Issue by Matelasse** [vercel/next.js#13767]
# Feature request

## Is your feature request related to a problem? Please describe.

Dev-server takes tons of time to spin up, making the overall developer experience worse.

## Describe the solution you'd like

Vite is a modern alternative for faster dev-server builds.

## Describe alternatives you've considered

Next.js could use the inspiration from Vite and provide its own implementation for a fast dev-server.

## Additional context

https://github.com/vitejs/vite

**Comment by borekb** [comment]
This is a [great podcast episode about Vite](https://player.fm/series/series-1401837/ep-140-evan-you-reimagining-the-modern-dev-server-with-vite) with Evan You, got me thinking whether this could be married with Next.js 😄. Vite's approach sounded really quite "sound".

**Comment by rajington** [comment]
Thanks for sharing that podcast, would Vite's use of rollup maybe change how production is built as well? Or maybe something like Snowpack where it's just for dev? There sure are a lot of webpack-based plugins...

**Comment by Matelasse** [comment]
@Timer any thoughts regarding this feature request? i love both next.js and vite, and i would love to be able to use them both

**Comment by Janpot** [comment]
@Matelasse Did you see https://github.com/vercel/next.js/issues/15152 ?

**Comment by Matelasse** [comment]
@Janpot I hadn't seen that. Impressive and hopeful. Is there a way to experiment with wp5 before it's default in next?

**Comment by Matelasse** [comment]
update:
@Janpot webpack v5 is nowhere close to vite in terms of speed

**Comment by capaj** [comment]
why not switch to vite and drop webpack? That would be simpler to support in the future.

**Comment by timneutkens** [comment]
> update:
> @Janpot webpack v5 is nowhere close to vite in terms of speed

webpack 5 as of right now is not exactly ready yet. As said in the blogpost caching is not enabled yet.

> why not switch to vite and drop webpack? That would be simpler to support in the future.

Vite is in the very early days still. I'd be happy to investigate what it takes for compat for you as part of a support contract, feel free to reach out to enterprise@vercel.com.

**Comment by zigomir** [comment]
How about now when it's [stable](https://github.com/vitejs/vite/releases/tag/v2.0.0)? :)
