### ISSUE TITLE
Error: Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by lgoldfish** [vercel/next.js#13935]
# Bug report
[ error ] ./node_modules/@dpfe/header/dist/index.css
Error: Cannot find module 'autoprefixer'
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by timneutkens** [comment]
Closed as the issue template was not followed
