### ISSUE TITLE
`next export` usage with `getInitialProps` should warn

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#13946]
# Feature request

A common pattern in Next.js apps was to use `getInitialProps` for data fetching, then use `next export` to generate a static application.

This was problematic for two main reasons:

1. It **didn't work as expected**: for users who refreshed the page, they'd see the data as captured at build-time. When they navigated on the client-side, they'd see the latest version of data (client-side fetch).
1. To fix the above issue, users would sometimes **opt-out of client-side routing**, by avoiding usage of `NextLink`.

Now that Next.js has proper SSG support, usage of `next export` should always be paired with `getStaticProps`.

## Describe the solution you'd like

We should **not break any applications**. `getInitialProps` must continue to work.

However, when we detect `getInitialProps` in pages paired with `next export`, we should emit a friendly message to instruct the user to rewrite their app to use `getStaticProps`.

**Comment by eKhattak** [comment]
I'll write a fix for this.

**Comment by eKhattak** [comment]
@Timer I see there already exist some booleans in renderToHTML function which check if the page has getInitialProps
but this code snippet from worker.ts doesn't execute renderToHTML because the typeof `components.Component` is always string in case of next export.
![Imgur](https://i.imgur.com/M597u1p.png)

**Comment by kmdev1** [comment]
I see the related PR was closed and marked as stale quite sometime back - I'm happy to pick this up and get a fix in place 👍🏻
