### ISSUE TITLE
Favicon Issue - Not showing (v9.4.4)

### ISSUE THREAD

**Issue by grumpyTofu** [vercel/next.js#13985]
# Bug report

## Describe the bug

Favicon is not showing

## To Reproduce

Insert `<link rel="icon" type="image/x-icon" href="/public/favicon.ico" />` in the custom _document.js file within the `<Head></Head>` tags

## Expected behavior

icon should be displayed in tab

## System information

- Browser: chrome
- Version of Next.js: 9.4.4

## Additional Notes

No errors in console

here is the html head that is produced:

```
<head>
  <link rel="icon" type="image/x-icon" href="/public/favicon.ico">
  <meta charset="utf-8">
  ...
</head>
```

**Comment by mattcarlotta** [comment]
You're not supposed to import `next/head` within `_document`. Soon, it'll throw an error: #13958 

Instead, you'll want to import/utilize it within `_app.js`.

For example:
```js
import App from "next/app";
import Head from "next/head";
import { version } from "../../package.json";

const App = ({ Component, pageProps }) => ( 
  <>
    <Head>
      <meta charSet="utf-8" / >
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="theme-color" content="#000000" />
      <meta name="description" content="Official website for... something." />
      <meta name="build version" content={`${version}`} /> 
      <link rel="icon" href="/favicon.ico" />
    </Head> 
    <Component { ...pageProps }/> 
  </>
);


export default App;
```

With [static file serving](https://nextjs.org/docs/basic-features/static-file-serving), you won't need to include `/public`, instead it'll just be `/`.
