### ISSUE TITLE
Create Next App and Next should validate Node.js version

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14015]
The Create Next App CLI and Next.js itself (during dev only) should validate the Node.js version in the environment and advise to upgrade if it's a version we don't support.

This should stop both `next dev` and the `create-next-app` command with very helpful instructions.

**Comment by eKhattak** [comment]
@Timer  The current Nodejs version check needs to be hardcoded or is there any variable with which I can compare the user's version?

**Comment by eKhattak** [comment]
@Timer  I've few questions

- Is there any variable that holds the value of currently supported NodeJs version, so I can check the user's version with that variable or it needs to be hardcoded?
- What should be the Error message? Should I ` throw new Error()` or just do simple `console.log` and then exit the process?

**Comment by baruchadi** [comment]
👋 Hey @timneutkens !
Is this issue still relevant? If so, mind if I pick it up?

**Comment by balazsorban44** [comment]
Yes, please do!

**Comment by baruchadi** [comment]
Hey @balazsorban44 !

I'm getting close to a solution, I got a quick question that could help me get to a better structure: 
- is there a directory I can place a `TS` file that is accessible by both `CNA` and `Next`? 
  - I'd like to have a `isNodeVersionSupported` that returns the following structure:

```
 function isNodeVersionSupported(supportedNodeRange: string): {
   valid: boolean
   problems?: string[]
   userNodeVersion: string
   minSupportedNodeVersion: string
   }{ ... }
```

- I'm planning on doing one unit test for this function, then add an integration test per usage (once for CNA & once for Next)

Let me know what you think!

**Comment by balazsorban44** [comment]
I don't think there is currently a shared folder. To keep it simple, maybe just put it into both packages for now. :+1: There is other duplicated code between the two, which could be a task to clean up in the future.

**Comment by balazsorban44** [comment]
I wonder though... https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines should make so that unsupported Node.js versions don't even install. :thinking: 

I just tried it, and I got the following error trying Node.js 10:

> next@12.1.1-canary.7: The engine "node" is incompatible with this module. Expected version ">=12.22.0". Got "10.24.1"
