### ISSUE TITLE
Build-time warning when the size of `getStaticProps` exceeds a certain threshold

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14105]
# Feature request

Users may inadvertently return more data than they attended in `getStaticProps`, which can be undesirable for client-side transition speed (FCP unaffected).

## Describe the solution you'd like

We should implement a helpful warning when we detect a large amount of data and suggest users trim it down to only what is required.

**Comment by TodorTotev** [comment]
@Timer Any specific amount that should be considered large?

**Comment by k1148097010** [comment]
``

**Comment by sagar-gavhane** [comment]
@Timer Here is a library (object-sizeof) that will give us size of the object in memory. We can utilize this tool to calculate the size of props. also we can define the threshold on prop size. If user return props size more specific limit then we can warn them in a dev environment. 

object-sizeof: https://github.com/miktam/sizeof

**Comment by mahowa** [comment]
This seems to have been resolved however the message looks like this
 Generating static pages (19/81)Warning: data for page "/[[...index]]" is 154 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
 
 Notice this is a dynamic page. It would be nice if it would output the parameters so when trying to correct this issue we could see what route is acutally causing the problem

**Comment by ijjk** [comment]
Hi, this does seem to be able to be closed now. What version of Next.js are you seeing the above warning without the actual pathname on?

In the latest version `v12.2.5` you should see the below error which includes the actual pathname not the page pathname: `Warning: data for page "/[slug]" (path "/first") is`.
