### ISSUE TITLE
Broken symlink in $HOME causes errors during dev build

### ISSUE THREAD

**Issue by jtyers** [vercel/next.js#14128]
# Bug report

## Describe the bug
When I kick off a development build, and browse to a page (in order to trigger compilation for that page) I see the following:

```
> ui@0.1.0 dev /home/jonny/git/shepd-next/web-ui/ui
> next dev

ready - started server on http://localhost:3000
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

event - compiled successfully
event - build page: /
wait  - compiling...
(node:1129374) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/jonny/.foo'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1129374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

The file `/home/jonny/.foo` is in fact a symlink which points to a non-existent path, hence the ENOENT.

The bug here is: why does a broken symlink in an unrelated directory cause this error? My project I'm running this from is not in my home directory, but several layers down.

After this error appears, dev compilation seems to stop. In my browser I see "localhost didn't send any data. ERR_EMPTY_RESPONSE". Removing the symlink and restarting `next dev` stops the error appearing, and compilation continues.

My `next.config.js`:
```js
const path = require('path')
const withPlugins = require('next-compose-plugins');
const css = require('@zeit/next-css');

const nextConfig = {
  cssModules: true,
  webpack: config => {
    config.resolve.alias = {
      ...config.resolve.alias,
      "Semantic/all$": path.resolve(__dirname, "./semantic/dist/semantic.min.css"),
      "Semantic": path.resolve(__dirname, "./semantic/dist"),
    }
    return config;
  },
};

module.exports = withPlugins([[css]], nextConfig);
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to any NextJS project
2. Create a broken symlink in your $HOME (e.g. `ln -s /foo/bar ~/.foo`)
3. Run `npm run dev`
4. See error during compilation of a page

## Expected behavior

Broken symlinks should not affect compilation.

## System information

- OS: Arch Linux
- Version of Next.js: v9.4.4
- Version of Node.js: v14.4.0

## Additional context

Interestingly I found that if I create the symlink *while a dev build is already in progress* the error also pops up on the console. This makes me think the logic that watches for file changes is causing this, and perhaps the bug is that it is watching `$HOME` rather than my project directory, which is at `$HOME/<dir>/<dir>`.

Running node with `--trace-warnings` as the error mesage suggests gets me this, by the way:

```
(node:1130360) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/jonny/.foo'
    at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(node:1130360) Error: ENOENT: no such file or directory, stat '/home/jonny/.foo'
(node:1130360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:161:11)
    at processPromiseRejections (internal/process/promises.js:213:13)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by JanKaifer** [comment]
I was not able to reproduce it. It was probably already fixed.
