### ISSUE TITLE
[Proposal] Simplifying i18n

### ISSUE THREAD

**Issue by aralroca** [vercel/next.js#14246]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently, integrating i18n libraries with Next.js and working with Automatic Page Optimization (either SSG, or totally static) is quite cumbersome.

It would be great to have something simple and portable, compatible with `next export`.

Using [**Dynamic routes**](https://nextjs.org/docs/routing/dynamic-routes) requires a `/[lang]` folder to have each page as `/en/example`. You have to write a `getStaticPaths` and `getStaticProps` on each subpage to download the corresponding JSONs.  Also, you need a language/locales context provider on the top of the page. And it gets even more complex with nested Dynamic routes and fallbacks. This alternative works in some projects but can be hellish in others.

Using [**rewrites**](https://github.com/vercel/next.js/discussions/9081) looks like a good alternative to simplify [**Dynamic routes**](https://nextjs.org/docs/routing/dynamic-routes). However, you can't do `next export`, because `next export`  does not have any special behavior for rewrites.

## Describe the solution you'd like

I understand that Next.js may give you the freedom to choose which i18n library to use. With that in mind, I propose to keep using any i18n library, but forcing them to work with Automatic Page Optimization by default. And simplifying the process.

### /locales folder

Just as `/pages` folder is useful to directly define pages, it would be great to have a folder `/locales`. Then you could define each supported language with their JSONs.

```
locales
├── de
│   ├── common.json
│   └── about.json
├── en
│   ├── common.json
│   └── about.json
├── es
│   ├── common.json
│   └── about.json
├── fr
│   ├── common.json
│   └── about.json
└── it
    ├── common.json
    └── about.json
```

With this structure, we should know what languages are supported in the app without any extra configuration. The default language could be renamed with some extra special character, like Dynamic routes do. Example of defining `en` as default language:

```
locales
├── de
│   ├── common.json
│   └── about.json
├── _en_
│   ├── common.json
│   └── about.json
├── ...
```

Perhaps, it should allow some config on `next.config.js` for advanced things.

### Usage in pages

```js
import useI18n from 'next/i18n'

export default function About() {
  const { language, locales } = useI18n()
  const { common, about } = locales

  // ...
}

export function getStaticProps({ i18n }) {
  const { language, locales } = i18n

  // ...
}

export const config = {
  i18n: {
    locales: ['about']
  }
}
```

This would facilitate the use of many i18n libraries (or even without libraries) by forcing it to work with Automatic Static Optimization.

You could render the page content using the language on front; `/en` instead of `/`, taking care of dynamic routes. For example, for `/pages/[slug].js` the language is ignored in the slug: `/en/some-slug`.

During the navigation using `<Link />` or `Router.push` would be great to keep the current language on the front, unless you specify another one.

Then each i18n library could manage the `locales` with their API, extending the `useI18n` hook to do the translations.

## Describe alternatives you've considered

I've considered `next export` to take account of **rewrites**. It would still not be a 100% friendly solution, but it would make it quite easy. I suppose there must be a reason behind it not being implemented.

## Additional context

A little more than 6 months ago I published [next-translate](https://github.com/vinissimus/next-translate) trying to make i18n + Next.js easier after seeing its complexity, although I think that the solution I implemented is a bit "hacky". It would be nice if Next.js managed this just like it does with pages. 

I hope this will help us find a simple and efficient solution.

**Comment by revskill10** [comment]
In my case, all of my locales translation is from database, so i don't think an opinion file system based locales folder is good enough to cover some use cases.

**Comment by aralroca** [comment]
@revskill10 you are right. Maybe will be better to define the languages and default language in `next.config.js` level. 

But with this, you will be able to use:

```js
export async function getStaticProps({ i18n }) {
  const { language } = i18n
  const translations = await fetchTranslationsFromDB(language)

  // ...
}
```
