### ISSUE TITLE
Do not emit development JavaScript to file system during `next dev`

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14266]
We could gain a significant HMR speed boost if we do not emit to the file system during `next dev`. This also will allow us to remove the `inline-source-map` usage for Windows users due to Windows Defender scanning `eval-source-map` extra aggressively.

This can likely be accomplished as part of the webpack 5 upgrade.

**Comment by mosesoak** [comment]
Hi, I commented in another issue (link ☝️) where someone figured out that Defender was causing long delays. 

My observation is that WD seems to disable HMR completely. When it's off HTR works, page updates in 1-3 seconds. When on, the app seems to fully recompile and then the browser reloads the page, which takes around 20 seconds, and needless to say is clearly not a hot reload.

**Comment by timneutkens** [comment]
Going to close this issue as it's part of the turbopack architecture by default 👍
