### ISSUE TITLE
Nested SCSS is not working for scoped SCSS.

### ISSUE THREAD

**Issue by ankit-gupta1307** [vercel/next.js#14333]
# Bug report

## Describe the bug
I am writing the SCOPED Nested SCSS like -:

//index.module.scss
```
.container {
  background: #000;
  width: 100px;
  height: 100px;
  & > div{ 
     background: #FFCC00;
     width: 50px;
     height: 50px;
  }
}
```

//index.js
import classes from "./index.module.scss";
```
<div className={classes.container }>
   <div></div>
</div>
```

So, expected behaviour should be my inside div should be of different color and size but it's not taking any css. Please help.

This is a demo example.

**Comment by ankit-gupta1307** [comment]
@jamesmosier This is my use case. Please help how to use nested scss.

**Comment by jamesmosier** [comment]
I'm not seeing this issue 🤔 I'm using Next `9.4.4`.

I used your exact scenario and was able to produce this:

<img width="1164" alt="Screen Shot 2020-06-18 at 8 29 25 PM" src="https://user-images.githubusercontent.com/2854919/85084321-72610280-b1a2-11ea-9341-d208c5641761.png">
