### ISSUE TITLE
Support userland data in SSR contexts

### ISSUE THREAD

**Issue by cdaringe** [vercel/next.js#14396]
# Feature request

## Is your feature request related to a problem? Please describe.

To pass custom data into `getServerSideProps`, I have to mutate `req: IncomingRequest` in my custom-server.

## Describe the solution you'd like

For custom server users--myself included--often there is some business logic needed
to execute before we let next.js do its _great work_. Some of that business logic
may build up some data that we'd like to expose to next.js server side concerns. I'd _my data_ to participate in:

- `GetServerSidePropsContext`: https://github.com/vercel/next.js/blob/canary/packages/next/types/index.d.ts#L106-L115

and/or other SSR handlers where `req`/`res` are currently passed in. Currently `GetServerSidePropsContext` looks like:

```ts
export type GetServerSidePropsContext<
  Q extends ParsedUrlQuery = ParsedUrlQuery
> = {
  req: IncomingMessage
  res: ServerResponse
  params?: Q
  ...snip
}
```

Much like `hapi` has `server.app` (`ApplicationContext`) or koa has `BaseContext` which users can augment, so too would I like to
augment the next.js context. In this respect, the context would look more like:

```ts
export type GetServerSidePropsContext<
  Q extends ParsedUrlQuery = ParsedUrlQuery,
  AppContext=void
> = {
  req: IncomingMessage
  res: ServerResponse
  ...snip
  app?: AppContext // 👀
}
```

To make that happen, there's quite a few touch points, but the lift could be
minimal, if all we did was app _optional arguments_. Here's an example flow
from the next handler to Context construction:

route ingress:

- https://github.com/vercel/next.js/blob/bef9b5610911532689dc251b7ceac72985e6b6dd/packages/next/next-server/server/next-server.ts#L245
- https://github.com/vercel/next.js/blob/bef9b5610911532689dc251b7ceac72985e6b6dd/packages/next/next-server/server/next-server.ts#L773
- https://github.com/vercel/next.js/blob/bef9b5610911532689dc251b7ceac72985e6b6dd/packages/next/next-server/server/router.ts#L159
- https://github.com/vercel/next.js/blob/bef9b5610911532689dc251b7ceac72985e6b6dd/packages/next/next-server/server/router.ts#L283
- https://github.com/vercel/next.js/blob/bef9b5610911532689dc251b7ceac72985e6b6dd/packages/next/next-server/server/router.ts#L19-L31

route setup & processing:
- https://github.com/vercel/next.js/blob/bef9b5610911532689dc251b7ceac72985e6b6dd/packages/next/server/next-dev-server.ts#L135
- eek! ran out of time. will try and pickup later :)

What the general sentiment towards such a feature? I'd be glad to send patches (including docs)
if the maintainers would be open to it, and if we could align around a strategy.

Thanks for the consideration and great tool.

## Describe alternatives you've considered

Augmenting `IncomingRequest` and mutating `req`

## Additional context

n/a

**Comment by timneutkens** [comment]
We are not planning to change the custom server api at this point in time, in general we recommend having all logic inside your Next.js application where possible.
