### ISSUE TITLE
The whitespace stripping in the error overlay does not work when there is an empty line

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14434]
The error overlay's whitespace stripping breaks when there is a new line with no whitespace in the middle of the code frame.

**Comment by eKhattak** [comment]
@Timer  Can you please write reproduction steps? I tried to reproduce it but it's working fine, I tried for both Runtime and Compilation Errors.
![Source Code](https://media.discordapp.net/attachments/717225343148359701/724527367724335104/unknown.png)

![Overlay](https://cdn.discordapp.com/attachments/717225343148359701/724526880606388224/unknown.png)

**Comment by Timer** [comment]
This requires deeply nested code. The whitespace stripping in the above example was not necessary as `export default` already had no whitespace.

![image](https://user-images.githubusercontent.com/616428/85287558-70c56200-b462-11ea-9d4e-c83d19893f39.png)

```js
export default function Home() {
  return (
    <div className="container">
      <h1>Hello</h1>

      <a
        onClick={() => a()}
        href="https://github.com/vercel/next.js/tree/master/examples"
        className="card"
        target="_blank"
      >
        <h3>Examples &rarr;</h3>
        <p>Discover and deploy boilerplate example Next.js projects.</p>
      </a>
    </div>
  );
}
```

**Comment by lOscarl** [comment]
Hello, can I work in this issue?

**Comment by DiKwickley** [comment]
Hi, @timer I would like to try to fix this issue. When the nesting is deeper, the code section can look pretty bad.
![image](https://user-images.githubusercontent.com/31622972/129885964-f6dd4941-aa80-4a55-b6e7-3946f5f57aae.png)
