### ISSUE TITLE
Prop did not match. Client: X, Server: Y

### ISSUE THREAD

**Issue by nandorojo** [vercel/next.js#14469]
# Bug report

## Describe the bug

When I use JS to detect screen width, and then render content based on that screen width, the initial render differs on the server vs. client.

The result is an error saying **prop `style` did not match. Server: X, Client: Y.**

**When this happens, my app loads up with the style value from the server, and doesn't refresh using the client side's styles.**

## To Reproduce

Minimal reproducible example: https://github.com/nandorojo/next-style-issue

1. Create a new next project (`npx create-next-app -e with-expo`)
2. Add a dependency `yarn add @react-native-community/hooks`
3. Paste this in `pages/index.tsx`:

```jsx
// import { useDimensions } from "@react-native-community/hooks";

export default function App() {
  let breakpoint = 0

  // 👇 This generates a fake device width.
  const width = Math.round(Math.random() * 1000)

  // in my real app, I use a dependency:
  // const { width = 0 } = useDimensions().window;

  if (width > 500) breakpoint = 1
  if (width > 900) breakpoint = 2

  /*
   * on server: { breakpoint: 0 }
   * on client: { breakpoint: 0, 1, 2 } (unknown until it loads)
   */
  console.log('[pages/index.tsx]', { breakpoint })

  /* 🚨 Prop `style` did not match.
   * Server: "background-color:green;min-height:100px"
   * Client: "background-color:blue;min-height:200px
   */
  return (
    <div
      style={{
        backgroundColor: ['green', 'blue', 'orange'][breakpoint],
        minHeight: ['100px', '200px', '300px'][breakpoint]
      }}
    >
      {breakpoint}  {/* <- this prints the correct breakpoint... */}
     </div>
  )
}
```

## Expected behavior

My style is generated based on the screen width. Since the style on the client is different from the style generated on the server, I expect the style to rehydrate when the page loads. 

However, the style **only** updates when I resize the window + update component state. If I don't resize and update the component state, it stays the same.

## Screenshots

<img width="1791" alt="Screen Shot 2020-06-22 at 4 46 26 PM" src="https://user-images.githubusercontent.com/13172299/85333662-f91a2600-b4a7-11ea-924e-fb73ba23e64e.png">

## System information

- OS: macOS
- Browser: Chome, Safari
- Version of Next.js: 9.4.4
- Version of Node.js: 14.2

**Comment by mattcarlotta** [comment]
This is to be expected as the server doesn't have a `window` to determine device calculations. Instead, you should defer to CSR (client-side rendering) instead of SSR (server-side rendering). You can either...

Use [next/dynamic](https://nextjs.org/docs/advanced-features/dynamic-import) with `{ ssr: false }` ...

**components/ResizeWindow/index.js**
```js
import PropTypes from "prop-types";
import { useDimensions } from "@react-native-community/hooks";

function ResizeWindow({ children }) {
  let breakpoint = 0;
  const { width = 0 } = useDimensions().window;

  if (width > 500) breakpoint = 1;
  if (width > 900) breakpoint = 2;

  return (
    <div
      style={{
        backgroundColor: ["green", "blue", "orange"][breakpoint],
        minHeight: ["100px", "200px", "300px"][breakpoint],
      }}
    >
      {children}
    </div>
  );
}

ResizeWindow.propTypes = {
  children: PropTypes.node
}

export default ResizeWindow;
```
**pages/index.js** (import the `ResizeWindow` component dynamically):
```js
import dynamic from "next/dynamic";

const ResizeWindow = dynamic(() => import("../components/ResizeWindow"), { ssr: false });

const App = () => <ResizeWindow>Hi</ResizeWindow>;

export default App;

```
**OR**

Use something similar to Material-UI's [NoSsr](https://material-ui.com/api/no-ssr/) component...

**components/NoSSR/index.js**
```js
import { useEffect, useLayoutEffect, useState } from "react";
import PropTypes from "prop-types";

const useEnhancedEffect =
  typeof window !== "undefined" && process.env.NODE_ENV !== "test"
    ? useLayoutEffect
    : useEffect;

const NoSSR = ({ children, defer, fallback }) => {
  const [isMounted, setMountedState] = useState(false);

  useEnhancedEffect(() => {
    if (!defer) setMountedState(true);
  }, [defer]);

  useEffect(() => {
    if (defer) setMountedState(true);
  }, [defer]);

  return isMounted ? children : fallback;
};

NoSSR.propTypes = {
  children: PropTypes.node.isRequired,
  defer: PropTypes.bool,
  fallback: PropTypes.node,
};

NoSSR.defaultProps = {
  defer: false,
  fallback: null,
};

export default NoSSR;
```
**pages/index.js** (import the `NoSSR` component and wrap it over `ResizeWindow`):
```js
import ResizeWindow from "../components/ResizeWindow";
import NoSSR from "../components/NoSSR";

const App = () => (
   <NoSSR>
     <ResizeWindow>Hi</ResizeWindow>
  </NoSSR>
);

export default App;
```

**Comment by nandorojo** [comment]
Hmm, the only problem is, I want the components to render on the server for SEO. Why can’t the props on the client and server be different, and it just rehydrates on the client side?

**Comment by mattcarlotta** [comment]
As mentioned above, the server doesn't have a `window` (it's undefined); therefore, the hook will always fall back to `0`.
