### ISSUE TITLE
how to set cache-control header for public files 

### ISSUE THREAD

**Issue by eretica** [vercel/next.js#14478]
# Feature request

## Is your feature request related to a problem? Please describe.

i want to cache to public files via CloudFront 
but static file header always this `cache-control: public, max-age=0`

## Describe the solution you'd like

set header via next.config

## Describe alternatives you've considered

setting on next.config

```:next.config
public: {
	heders: {
      Cache-Control: max-age=31536000
	}
}
```

**Comment by timneutkens** [comment]
This is covered by this RFC: https://github.com/vercel/next.js/discussions/9081
