### ISSUE TITLE
Custom api routes using Next.js router

### ISSUE THREAD

**Issue by cseas** [vercel/next.js#14634]
# Feature request

## Is your feature request related to a problem? Please describe.

One limitation with the `api/` folder is that it requires you to have your api under `/api`. I'd like to define an API directly from the base url. I understand this is possible when using a custom server but I don't want to switch to a custom server since that would remove some performance optimizations that Next's internal router adds.

## Describe the solution you'd like

Maybe it's possible to decide in each file whether it's a page or an api endpoint, like this:
```js
// pages/index.js
import { api, page } from 'next'

// an api endpoint
export default api((req, res) => 'hello')

// a page
export default page((props) => 'hello')
```

_Originally posted by @lucleray in https://github.com/vercel/next.js/issues/7297#issuecomment-493676012_

Or if we could just use the Next router to custom define the API endpoint, that would be great.

## Describe alternatives you've considered

This example using Express seems to be the best alternative:
https://github.com/vercel/next.js/tree/canary/examples/custom-server-express

**Comment by Janpot** [comment]
@cseas You should be able to leverage the [upcoming custom routes](https://github.com/vercel/next.js/discussions/9081) feature to achieve this:
```js
  rewrites: () => [
    { source: '/my-api-route', destination: '/api/my-api-route' },
  ]
```

**Comment by pratheekhegde** [comment]
@Janpot In your shared snippet will it forward all the query params too? Does it act as a proxy internally like `http-proxy-middleware` ?
