### ISSUE TITLE
html style changes using <Link> same as <a> element

### ISSUE THREAD

**Issue by robert-dm** [vercel/next.js#14776]
# Bug report

## Describe the bug
The html element was changed to yellow background as indicated here: https://nextjs.org/learn/basics/navigate-between-pages/client-side but when I navigate to first-post.js page, the background changes from yellow (index) to white (first-post), but example indicates it should not change the color.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the learn section and follow steps https://nextjs.org/learn/basics/navigate-between-pages/client-side 
2. Click on first-page hyperlink created with <Link>, after updated the html style to background: yellow
3. background is white

## Expected behavior
first-page.js background color should be yellow

## Screenshots
![image](https://user-images.githubusercontent.com/35821871/86275170-3e75dc00-bba9-11ea-8c65-40cc08f6f9aa.png)
![image](https://user-images.githubusercontent.com/35821871/86275187-459cea00-bba9-11ea-9110-739c0639ded5.png)

## System information

- OS: macOS Catalina
- Browser: both Chrome and Safari
- Version of Next.js: not sure how to check my next.js version but I created app following Learn steps.
- Version of Node.js: 12.18.0

## Additional context
<style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          background: yellow;
          font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
            Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue,
            sans-serif;
        }

        * {
          box-sizing: border-box;
        }
      `}</style>

**Comment by jamesmosier** [comment]
Could you create a repository showing the failing case? I'm having trouble reproducing this based on your current steps.
