### ISSUE TITLE
next/link still triggers SSR (getServerSideProps) when shallow prop is set to true

### ISSUE THREAD

**Issue by williamku** [vercel/next.js#14855]
# Bug report

## Describe the bug

Clicking on Link element (from "next/link" lib) with property "shallow" being set to true will still trigger the target page's getServerSideProps method (on the server) every single time.

## To Reproduce:

(1) create 2 pages:  page1 and page2 under "pages" folder.
(2) add getServerSideProps to page1 and return some mock data.  Add console.log to output some msg as the first line.
(3) on page2, add a Link component as such:
```
  import Link from 'next/link';
  return (<Link href="/page1" shallow={true}>Click here</Link>);
```
(4) Run "npm run build" and "npm run start", directly launch the page2 on browser.
(5) Click on link created at the step 3.  Observe the console.log on the server terminal and notice that getServerSideProps function for page1 gets triggered every single time. 

## Expected behavior

The expected behavior is that, if shallow prop is set to true, the target page should only do the client-transition on the browser without going back to the server.  This expectation is based on the NEXT.JS doc site as follows:

Here is the quote from the NEXT.JS doc page "https://nextjs.org/docs/api-reference/next/link":  
"shallow - Update the path of the current page without rerunning getStaticProps, getServerSideProps or getInitialProps. Defaults to false".

To be consistent, Router from "next/router" should behave the same way when calling its push method with option of { shallow: true }.  Unfortunately I am not able to find any mentioning of "getServerSideProps" in the documentation for "next/router" lib.

## A note about convention for SSR (Server-Side-Rendering) capability:

By convention, if a page is SSR-enabled,  SSR operations only gets triggered by a direct hit via browser's address bar URL input or refresh.  The page should still retain client side transition capability whenever it is needed for better user-perceived performance. In such case, the data is usually retrieved via Ajax.   This is the behavior that I am looking for. 

## System information

- OS:  macOS
- Browser: Chrome
- Version of Next.js:  ^9.4.4
- Version of Node.js: v12.16.0

------------
Thanks

**Comment by Janpot** [comment]
You might want to check https://nextjs.org/docs/routing/shallow-routing#caveats

**Comment by williamku** [comment]
@Janpot , thanks for the reply and clarification.  If "shallow" option cannot be used to enable "Client Transition" for SSR-enabled pages, then, would it be correct to say that, under NEXT.JS framework, if a page is marked as SSR capable (via getServerSideProps), this page will never be able to do "Client Transition"?  Please kindly confirm...  Thanks again.

**Comment by Janpot** [comment]
> Every page-hit will mean a complete page reload from the web server?

Not at all, next.js will only download the javascript bundle that is needed and the data generated by `getServerSideProps`. In most cases the javascript will already be cached so it's really just data loading.

**Comment by williamku** [comment]
@Janpot , thanks again for the reply - I also done some learning and reading on my own regarding "getServerSideProps".  What I learned seems to match up with what you just said:  There won't be a full page reloading - it will be just JSON data being fetched to the client side.   I think I will close this ticket since my questions are all resolved.  Thanks again.
