### ISSUE TITLE
v9.4.2 changes ssr devtool and breaks css-to-js-sourcemap

### ISSUE THREAD

**Issue by tajo** [vercel/next.js#14906]
# Bug report

## Describe the bug

[css-to-js-sourcemap](https://github.com/rtsao/css-to-js-sourcemap) expects certain format of the stack trace and relies on server side source maps. This got changed in 9.4.2 and this [PR](https://github.com/vercel/next.js/pull/13123/files) and [broke](https://github.com/styletron/styletron/issues/366) Styletron's debug mode that uses css-to-js-sourcemap.

## To Reproduce

This [repo](https://github.com/tajo/nextjs-baseweb) is a minimal example.

## Expected behavior

Not throwing errors because of the different stack trace.

## Additional context

It's easily fixable by overriding defaults through `next.config.js`:

```js
module.exports = {
  webpack: (config, {dev}) => {
    if (dev) {
      config.devtool = 'inline-source-map';
    }
    return config;
  },
};
```

but since this was just a performance optimization you might want to consider reverting the change until the next major version. Anyway, I thought it should be reported.

EDIT: 

v9.5 seems to break the only workaround:

```
Warning: Reverting webpack devtool to 'eval-source-map'.
Changing the webpack devtool in development mode will cause severe performance regressions.
Read more: https://err.sh/next.js/improper-devtool
```

**Comment by jasonwilliams** [comment]
I've also hit this issue with debugging javascript, switching to `inline-source-map` helped me too, thanks @tajo 
I think anyone else debugging next server side may fall into this problem.

**Comment by jasonwilliams** [comment]
## Steps to reproduce

- Checkout https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example (master branch will do)
- Open in VSCode
- Launch task "launch server"
- add a break point in pages `index.tsx` then go to `localhost:3000` it should hit
- try adding a breakpoint in pages/items/[id].tsx, you'll notice it doesn't go red

Sourcemap sources (once parsed)
`"sources": ["webpack:///./pages/items/.tsx?ace6"],`

the `[id]` has been truncated.
I've actually noticed this happen on `inline-source-map` to so im not sure where this fault is coming from

**Comment by jasonwilliams** [comment]
Looks like a possible regression of https://github.com/vercel/next.js/issues/8295

**Comment by tajo** [comment]
Well, 9.5 makes things worse and breaks our only workaround?

```
Warning: Reverting webpack devtool to 'eval-source-map'.
Changing the webpack devtool in development mode will cause severe performance regressions.
Read more: https://err.sh/next.js/improper-devtool
```

**Comment by jasonwilliams** [comment]
Because im not certain if our issues are exactly the same, i've made a more specific issue at https://github.com/vercel/next.js/issues/15823

**Comment by jasonwilliams** [comment]
My [fix](https://github.com/webpack/webpack/issues/11456) went into Webpack 5.5.0 so could you see if this issue still happens with that version?
