### ISSUE TITLE
CSS variable with built-in color name replaced with color code on build

### ISSUE THREAD

**Issue by prince3339** [vercel/next.js#14935]
# Bug report

## Describe the bug

I have added some css variable using scss map in **global css** with naming like below:

```
$colorPalette: (
	red: #ff0000,
	red1: #fa5e56,
	red2: #DA291C,
	red3: #d0021b,
	red4: #4C191B,
        black: #000000
)
```

```
:root {
  @each $color, $value in $colorPalette {
    --#{$color}: #{$value};
  }  
}
```

After building the project, I see variable becomes like below **but in dev it works fine**:

```
--red: #ff0000;
--red1: #fa5e56;
--red2: #DA291C;
--red3: #d0021b;
--red4: #4C191B;
--#000: #000;
```
## To Reproduce

Just add a css variable with any builtin color name and build the project.

## Expected behavior

After project building variables should remain like below:

```
--red: #ff0000;
--red1: #fa5e56;
--red2: #DA291C;
--red3: #d0021b;
--red4: #4C191B;
--black: #000;
```

## System information

- OS: Ubuntu 20,4
- Browser (if applies) Any browser
- Version of Next.js: 9.4.4
- Version of Node.js: 12.16.1

**Comment by timneutkens** [comment]
Seems unexpected, can you create a repository showing it, that'll make it simpler to look into this.

**Comment by prince3339** [comment]
> Seems unexpected, can you create a repository showing it, that'll make it simpler to look into this.

@timneutkens   Sorry I missed something in description.
I figured out it happens only when I generate variables using sass map.

```
$colorPalette: (
	red: #ff0000,
	red1: #fa5e56,
	red2: #DA291C,
	red3: #d0021b,
	red4: #4C191B,
        black: #000000
)
```

```
:root {
  @each $color, $value in $colorPalette {
    --#{$color}: #{$value};
  }  
}
```

End results:

```
--red: #ff0000;
--red1: #fa5e56;
--red2: #DA291C;
--red3: #d0021b;
--red4: #4C191B;
--#000: 000;
```

**Comment by prince3339** [comment]
@timneutkens  Not only sass map. You can reproduce it with:
$black: black;
:root {
--#{$black}: #{$black};

It results like below:
--#000: #000;

**Comment by panteliselef** [comment]
I believe this has been resolved

```
$colorPalette: (
        red: #ff0000,
        red1: #fa5e56,
        red2: #DA291C,
        red3: #d0021b,
        red4: #4C191B,
        black: #000000
);

:root {
  @each $color, $value in $colorPalette {
    --#{$color}: #{$value};
  }
}
```

my package.json
```
  "dependencies": {
    "next": "12.1.6",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "sass": "^1.49.9",
  },
  "devDependencies": {
    "@types/node": "17.0.39",
    "@types/react": "18.0.0",
    "@types/react-dom": "^18.0.0",
    "typescript": "^4.6.2"
  }
```

**Comment by balazsorban44** [comment]
Closing as this is a pretty old issue, a lot has changed and as suggested above, the problem is probably fixed. If not, please let us know by creating a new issue with a fresh reproduction (using `next@canary`)
