### ISSUE TITLE
Root catch-all custom-route should match the root itself

### ISSUE THREAD

**Issue by ijjk** [vercel/next.js#14930]
A catch-all rewrite e.g. `{ source: '/:path*', destination: '/somewhere' }` should match when `/` is requested, ~after this is corrected we should investigate disabling `strict: true` for custom-routes~.

We also need to make sure this works on Vercel.

**Comment by Timer** [comment]
It seems it's necessary to do this:
```
/:path*{/}?
```

Still discussing in this thread:
https://github.com/pillarjs/path-to-regexp/issues/228

**Comment by NickCrews** [comment]
I believe another, maybe more readable alternative is `/(.*)`. Correct me if I'm wrong. Based off https://github.com/leerob/leerob.io/blob/d3cb3af32b4be2a2fd2be5953d3c16d429f25943/next.config.js#L15, which is written by someone who probably knows Next.js pretty well.

**Comment by gabrielizaias** [comment]
Upstream https://github.com/pillarjs/path-to-regexp/issues/228#issuecomment-894733779 has been closed with a recommendation that consumers apply a fix themselves:
> (…) recommend people put this into logic wrapping this library

What can we expect from NextJS in this case?

**Comment by ijjk** [comment]
Closing as stale
