### ISSUE TITLE
Plz update with-mobx-lite SSR.

### ISSUE THREAD

**Issue by kir931028** [vercel/next.js#15085]
# Feature request

## Is your feature request related to a problem? Please describe.

I want with-mobx-lite SSR. but, I didnt find SSR example.

## Describe the solution you'd like

with-mobx-lite SSR example.

**Comment by jamesmosier** [comment]
Could you elaborate a bit more? The [with-mobx-react-lite](https://github.com/vercel/next.js/tree/canary/examples/with-mobx-react-lite) example works with server rendering. 

Additionally, feel free to contribute a PR for this!

**Comment by kir931028** [comment]
I dont found using getServerSidePorps example.
Can you provide getServerSidePorps example?
