### ISSUE TITLE
Preact example's URL routing fails to route initial page load

### ISSUE THREAD

**Issue by websocket98765** [vercel/next.js#15109]
# Bug report

When using Next.js' [Preact example](https://github.com/vercel/next.js/tree/canary/examples/using-preact), and after building and exporting for a production build, URL routing during the initial page load does not work properly. I.e. visiting `/about` loads the homepage template, not the `about` template.

Note:
- This problem does **not** occur when running in **dev** mode--i.e. visiting `/about` loads the `about` page, as expected.
- Client-side URL routing otherwise works as expected--e.g. if visiting homepage first and then clicking `about` link, it redirect to `/about` and show `about` page content, as expected. 

## To Reproduce

1. Create new project using `npx create-next-app --example using-preact preact-demo`
2. Add `"export": "next export",` to package.json scripts.
3. Run: 
    ```
    npm install
    npm build
    npm export
    npm i -g serve
    serve -s out 
    ```
4. Visit `localhost:5000/about` (Must go directly to `/about` on initial load to see this.)

## Expected behavior

The About page content should appear: `About us!`

## Buggy behavior

The Home page content appears (see screenshots).

## Screenshots

Chrome:
<img width="335" alt="~chrome" src="https://user-images.githubusercontent.com/41795874/87259854-c1e2d780-c49d-11ea-843c-4657315fa32b.png">
Firefox:
<img width="461" alt="~ff" src="https://user-images.githubusercontent.com/41795874/87259877-de7f0f80-c49d-11ea-909b-4560210f4a75.png">

## System information

- OS: MacOS
- Browser: Chrome & Firefox tested.
- Version of Next.js: 9.4.0
- Version of Node.js: v12.13.0

Versions from package.json:
```
  "devDependencies": {
    "react-refresh": "^0.8.3"
  },
  "dependencies": {
    "@prefresh/next": "^0.3.0",
    "next": "^9.4.0",
    "preact": "^10.4.4",
    "preact-render-to-string": "^5.1.9",
    "react": "github:preact-compat/react#1.0.0",
    "react-dom": "github:preact-compat/react-dom#1.0.0",
    "react-ssr-prepass": "npm:preact-ssr-prepass@^1.0.1"
  }
```

Note I have not tried deploying this to see if it occurs when hosted on vercel.

**Comment by awareness481** [comment]
This is a long-shot but I thought I'd rather mention it.
Since the meta tag is called `next-head-count` is it supposed to be **unique** for each page?
I noticed both **index.html** & **about.html** have the same number for the *content* attribute.
`<meta name="next-head-count" content="2" />`

Any chance this could help identifying the issue?

**Comment by websocket98765** [comment]
Maybe @developit would have an idea of the cause, if he would have time to look?

**Comment by maxnewlands** [comment]
I poked around a bit at this one, and saw the issue outside of the Preact example as well, i.e. in a project created with a regular old `npx create-next-app`. Far as I can tell, `out/about.html` is being correctly exported, and the page renders as expected whether I open it from my file system or with a different server tool like http-server. Could the issue relate more to the serve package, like potentially being incompatible with how things are exported in `out`?

**Comment by websocket98765** [comment]
@maxnewlands seems to be onto something--this may be related to the NPM `serve` package. I tested these ways:
- `npm run dev` ✅ 
- `npm run build && npm run export && serve -s out` ❌   (`out/about.html` does exist, but homepage content is shown on initial load when directly visiting `/about`)
- On Vercel with `npm run build` ✅ 
- On Vercel with `npm run build && npm run export` ✅  


I'm new to NextJS. For others in the same boat, this issue isn't blocking, since NextJS has [Automatic Static Optimization](https://nextjs.org/docs/advanced-features/automatic-static-optimization) and I'm deploying to Vercel, it seems I can just use `npm run dev` locally and `npm run build` for production and still get static pages in production. But it might be blocking for someone deploying to a different host that can _only_ serve static content, like S3.

**Comment by JanKaifer** [comment]
Preact example is broken right now so I'll close this in favor of https://github.com/vercel/next.js/issues/42530
