### ISSUE TITLE
Create a new blog starter example with simple layout

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#15133]
Per [this Twitter thread](https://twitter.com/dan_abramov/status/1281712350488387584), we should create a new blog template that is simple in nature:

- [Index with simple top-down layout + post page + Markdown](https://twitter.com/dan_abramov/status/1281716760731947009)
- [SEO](https://twitter.com/dan_abramov/status/1281716811529158656)
- [RSS](https://twitter.com/dan_abramov/status/1281717501949345792)

We're likely going to base this of the beautiful blog found on @pacocoursey's personal website:

https://paco.im/blog

**Comment by jensmeindertsma** [comment]
I'd love it if there was a MDX version of this! If there are more people who also want this, please let me know. I could put up an example.

**Comment by molebox** [comment]
We now have a template in the template marketplace that covers this https://github.com/vercel/nextjs-portfolio-starter
