### ISSUE TITLE
`next run <script>`

### ISSUE THREAD

**Issue by brandonbloom** [vercel/next.js#15279]
# Feature request

## Is your feature request related to a problem? Please describe.

I'd like a way to run scripts for general maintenance tasks with zero config and utilizing all of the Next.js machinery (transpilation, module aliasing, polyfills, configuration loading, etc).

## Additional context

See https://github.com/vercel/next.js/pull/15276#issuecomment-660336199

**Comment by nzjoel1234** [comment]
This would be helpful for me as I want to build a Lunr index at build time and store it as a JSON file in `/public`.

Ideally I would like to use typescript for this.
