### ISSUE TITLE
with-sentry is using workarounds on top of workarounds

### ISSUE THREAD

**Issue by pixelass** [vercel/next.js#15401]
# Bug report

The with-sentry example does not work as expected

## Describe the bug

The with-sentry example uses a lot of workarounds and is incompatible with typescript environments.

## To Reproduce

Look at the with-sentry example and look for related issues 

#14345
#14758
#8592
... probably some more

https://github.com/vercel/next.js/tree/canary/examples/with-sentry

## Expected behavior

As a developer I expect to be able to integrate sentry without numerous workarounds and full typescript support without hacking types or using `any`.

## System information

- OS: [e.g. macOS, Windows] macOS
- Version of Next.js: 9.4.4
- Version of Node.js: v12.15.0

## Additional context

Without proper support we won't be able to add sentry to log errors in a safe and maintainable manner. Reading through the issues quickly shows that the integration is not safe for production usage.

**Comment by BramDecuypere** [comment]
How is this not getting more attention? It's essential to know if things go wrong? 
We've moved to Vercel with our Next.js app, with the static export Sentry seemed to be working properly.

But now I even noticed that I can't get the `with-sentry` example to work?

The server-side is working as expected, but the client Side is not doing what it should, I've tried hacking around it as well. `CLIENT SIDE ERRORS ARE NO LONGER BEING CAUGHT FROM WHAT I SEE IN THE EXAMPLE`...

Try to get a Sentry.captureMessage('logging a simple message') into your dashboard...

**Comment by pixelass** [comment]
I think this topic might have been discussed on the nextjs conference by https://nextjs.org/conf/speakers/zeeg in "Future of Performance and Data in the Modern Web"

I only saw parts of it so let's wait until they release all of the videos.

**Comment by maccman** [comment]
I think having a exception tracking system in Next.js would be super useful.

**Comment by danoc** [comment]
Seems like this is being worked on:

* https://github.com/vercel/next.js/discussions/14758#discussioncomment-340241
* https://twitter.com/zeeg/status/1321135826089070593

**Comment by balazsorban44** [comment]
Hi, this issue was opened a long time ago, and the Sentry team has released many updates and the example has been updated as well since then.

I'll close this for now. Please open a new issue if you are having a specific issue with `latest` versions. A good resource to set up Next.js with Sentry is https://docs.sentry.io/platforms/javascript/guides/nextjs
