### ISSUE TITLE
Ability to opt-out of `web-vitals` package that's currently bundled with Next.js

### ISSUE THREAD

**Issue by dmitrizzle** [vercel/next.js#15414]
# Feature request

Currently, Next.js adds `web-vitals` package and a file that handles it -- into the production bundle. Though it may be useful in many cases, my project does not rely on these metrics. It adds an extra KB of code and whatever the parsing resources it needs from the user's machine. This isn't much, but I think that in line with Next.js's telemetry opt-out we should be able to opt out of this feature as well.

## Describe the solution you'd like

Add a flag/setting in next.config.js to opt-out of `web-vitals`.

## Describe alternatives you've considered

The only thing to do here, as I understand, other than setting up the above flag is to fork Next.js.

## Additional context

https://github.com/vercel/next.js/discussions/15296

**Comment by housseindjirdeh** [comment]
Although it's tiny, I agree it's an additional cost if you're not using it to measure metrics at all.

I wouldn't mind if we keep it included by default and have a flag to opt-out. @timneutkens do you agree?

**Comment by timneutkens** [comment]
There's likely a better approach possible here where we remove the web vitals package during compilation when reporting is not set up
