### ISSUE TITLE
Add configuration to disable ReactDevOverlay

### ISSUE THREAD

**Issue by kylecesmat** [vercel/next.js#15443]
# Feature request
Developers should be able to opt-out of the `ReactDevOverlay` component that blocks the UI by providing configuration to `next.config.js`.

Something like:

```
// next.config.js
module.exports = {
    reactDevOverlay: false
}
```

This is similarly related to the `typescript.ignoreDevErrors` configuration that prevents the UI from breaking, but still provides developers with introspection in their console(s).

## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

Add configuration here:
```
// next.config.js
module.exports = {
    reactDevOverlay: false
}
```

That prevents this component from rendering in development - https://github.com/vercel/next.js/blob/a0c683208abdce84934061f6efd2b90de52d99b9/packages/next/client/index.js#L160

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by timneutkens** [comment]
> Is your feature request related to a problem? Please describe.
> No.

So why do you want to disable the error overlay if there is no problem?

> That prevents this component from rendering in production

There is no error overlay in production as per that branch you linked to.

**Comment by Timer** [comment]
Also—see https://github.com/facebook/create-react-app/issues/6530#issuecomment-662914362 for the reasoning why this overlay cannot be disabled. We're going to improve its ergonomics with error boundaries, though!

**Comment by kylecesmat** [comment]
@timneutkens I apologize, I could have provided a better problem statement in the description.

The goal here would be to disable the development error banner that appears. You are right, it can be clicked away if needed, but that's just a developer annoyance when you are actively working and a known bug is throwing an error.

*Ideally, I'd like to be able to disable the rendering of this error boundary UI for development via a configuration value.*

My (rather unfortunate, but current) use case here is this:
- My nextjs application imports a library thats outputs an error in dev because it is flawed and incorrectly handles hostname parsing with `localhost`
- My team of 12 developers knows this library is an issue in dev, and the error "cannot read .lastIndexOf foo..." will cause this UI to display during every page transition while they are in development
- Ideally, I'd like if my team did not have to click the close button on every page transition just to close the modal of a bug they are ignoring intentionally in dev

yes, I know this is a contrived example, but ideally I'd like to have the control to enable/disable this developer tool and make my team's developer experience better while we work to fix the upstream issue.

To @Timer's point, it looks like this cannot be done currently? I was thinking it'd be as simple as adding a config value like this:

```
if (config.reactDevOverlay && process.env.NODE_ENV !== 'production') {
      const { ReactDevOverlay } = require('@next/react-dev-overlay/lib/client')
      return <ReactDevOverlay>{this.props.children}</ReactDevOverlay>
    }
```

**Comment by pacxiu** [comment]
We have similar usecase for such flag - Unhandled Runtime Error comes from chrome extension so it is displayed as `inpage.js`. It is not critical and we have to click it away on and on - becomes frustrating after a while.
