### ISSUE TITLE
fetch is missing in `next-env.d.ts` TypeScript types?

### ISSUE THREAD

**Issue by borekb** [vercel/next.js#15480]
# Bug report

## Describe the bug

In the Node environment (SSR, SSG), `fetch` is provided by Next.js at runtime but is missing from TypeScript types, leading to TypeScript error

> Cannot find name 'fetch'.ts(2304)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new Next.js app (tested at v9.4.4)
2. Setup TypeScript as described [in the docs](https://nextjs.org/docs/basic-features/typescript)
3. Follow the [Data fetching](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) docs, e.g., create this `pages/index.tsx` page:

```tsx
import React from 'react';

const Index: React.FC = data => (
  <div>
    <pre>{JSON.stringify(data)}</pre>
  </div>
);

export async function getServerSideProps() {
  const res = await fetch('https://example.com/api');
  const data = await res.json();
  return {
    props: data,
  };
}

export default Index;
```

This works at runtime but in VSCode, TypeScript will be marking `fetch` as unknown.

## Workaround

Adding this import seems to work:

```js
import fetch from 'node-fetch';
```

but it shouldn't be necessary I think, see the [Next.js 9.4 blog post](https://nextjs.org/blog/next-9-4#improved-built-in-fetch-support).

## What might be wrong

Briefly looking at the generated next-env.d.ts and the referenced types:

```ts
/// <reference types="next" />
/// <reference types="next/types/global" />
```

I didn't find any mentions of `fetch` in the referenced types, while I think I should have.

<sub>[NEXT-1390](https://linear.app/vercel/issue/NEXT-1390/fetch-is-missing-in-next-envdts-typescript-types)</sub>

**Comment by agamm** [comment]
I'm suspecting the the following error is also related to this:
> error TS2339: Property 'raw' does not exist on type 'Headers'.

When I have the following code:
`response.headers.raw()`

**Comment by timneutkens** [comment]
Tried to reproduce this but couldn't anymore. Going to close the issue 👍
