### ISSUE TITLE
Nextjs ant design

### ISSUE THREAD

**Issue by sadam1807** [vercel/next.js#15530]
I clone the repo from next js examples to integrate nextjs with antd design. 

Every thing works fine but css is loading after html send to the browser. 

How I can resolve this issue

**Comment by modbender** [comment]
I don't know much about ant design, but shouldn't it be similar to this:
https://github.com/mui-org/material-ui/blob/next/examples/nextjs/pages/_app.js
https://github.com/mui-org/material-ui/blob/next/examples/nextjs/pages/_document.js

There was already an issue opened on this:
#12310

Also there's example:
https://github.com/vercel/next.js/tree/canary/examples/with-ant-design

**Comment by modbender** [comment]
Check this out once: https://medium.com/@tanakorn0412/customize-ant-design-theme-in-next-js-version-9-5958fbc531a3

**Comment by sadam1807** [comment]
@modbender thanks for your response. but still I am facing the issue. CSS is flickering, it takes time to load because HTML is sent before the CSS to browser, the issue is not only with antd CSS  but also with all the parent css files loaded in _app.js file.

**Comment by modbender** [comment]
Oh ok, then guess you'll have to ping/tag some other devs or contributors to get a reply...

**Comment by sadam1807** [comment]
@timneutkens @viztor @mvfsillva @awareness481 @jacklee814 @mit123suki

**Comment by awareness481** [comment]
@sadam1807 
This was fixed in the **Next.js 9.5" version, either update your *package.json* to 
`"next": "latest"` and re-install your node-modules or create a new Next.js app using `npx create-next-app` which should use the latest version.

Please refrain from tagging too many people tho.
