### ISSUE TITLE
Cannot destructure property `publicRuntimeConfig` of 'undefined' or 'null'. (v9.5.0)

### ISSUE THREAD

**Issue by stijnvanderlaan** [vercel/next.js#15568]
# Bug report
After upgrading from 9.4.4 to 9.5.0 I get an error after building (in dev mode all works fine):
```
Cannot destructure property `publicRuntimeConfig` of 'undefined' or 'null'.
```

# Code:
```js
import getConfig from "next/config";
const { publicRuntimeConfig } = getConfig()
```

## System information
- OS: macOS
- Browser: chrome
- Version of Next.js: 9.5.0

**Comment by stijnvanderlaan** [comment]
Looks like the results of `runtime_config_default()()` is undefined.
In another project the build works fine, but I can't find `runtime_config_default` inside `.next`.

**Comment by stijnvanderlaan** [comment]
It seems to be related to lerna & different not being installed correctly, installing it in the root of the project with `yarn add next -W` fixed it for me.

**Comment by stijnvanderlaan** [comment]
I installed a package & this error is back! Also tried 9.5.1.

**Comment by stijnvanderlaan** [comment]
Oke, so I found the situation when this is happening. I use next-transpile-modules to import modules from a different component package. But when I try to call `getConfig` inside a component in a different package it fails, a workaround is passing the config to the Component.

**Comment by stijnvanderlaan** [comment]
Oke, so I found the situation when this is happening. I use next-transpile-modules to import modules from a different component package. But when I try to call `getConfig` inside a component in a different package it fails, a workaround is passing the config to the Component.

**Comment by ckeeney** [comment]
I encountered this same error when using yarn workspaces with one workspace depending on next 9.4 and another 9.5.  updating next to the latest version in all workspaces resolved it for me.

**Comment by kogai** [comment]
I've got the same error, it occurred when `next dev` subcommand executed, but the `next build && next start` did not the case.

**Comment by talesmgodois** [comment]
I am geting this error in Next 9.5.5 under *jest* tests, just checking if my component isDefined

**Comment by nersoh** [comment]
I started to get this error when I updated from v10.0.6 to v10.0.7

**Comment by madeinspace** [comment]
I'm getting that error too I'm on v10.0.7 but had it since v9.5

**Comment by gushiguera** [comment]
> Oke, so I found the situation when this is happening. I use next-transpile-modules to import modules from a different component package. But when I try to call `getConfig` inside a component in a different package it fails, a workaround is passing the config to the Component.

I also have next-transpile-modules in my next.config.js and running into this issue when running my tests? Any recommendations?

**Comment by jasonwilliams** [comment]
I had this issue with npm workspaces. turns out i was calling next from the workspace node_modules and not the correct one from the package folder. Basically I was calling the wrong version.

**Comment by alexmcode** [comment]
@gushiguera I have the same situation as you. What I did is mock it with jest.

**Comment by Himself65** [comment]
I will try to build the project in WSL later

**Comment by sebastianupr** [comment]
I solved this issue with this lines in jest.setup file:
```
import { setConfig } from 'next/config'
import config from './next.config'

setConfig(config)
```

**Comment by kushalmahajan** [comment]
For those who encounter this running jest, here is a fix tested 
In my case I was using 

```
import getConfig from 'next/config';
const { publicRuntimeConfig } = getConfig();
```
Changing the above to `import { publicRuntimeConfig } from '<path/to>/next.config.js';`  helped

**Comment by ijjk** [comment]
Per the above if you are relying on this in your tests you do need to call `setConfig()` manually as Next.js isn't managing the tests.
