### ISSUE TITLE
Provide mechanism to disable or override preview mode keys

### ISSUE THREAD

**Issue by Gaelan** [vercel/next.js#15609]
# Feature request

## Is your feature request related to a problem? Please describe.

My app doesn't currently use preview mode. However, every time I run `next build`, I get a new version of the app with different preview keys, needlessly slowing down my deployments.

## Describe the solution you'd like

Provide a mechanism to either a) disable preview mode or b) provide the preview mode keys myself (perhaps something analogous to `generateBuildId`), so the output of next build doesn't change unless my code does.

## Describe alternatives you've considered

I could just deal with updating every page, even if I'm deploying something unrelated. It's a bit annoying, but ultimately not a big deal.

**Comment by Timer** [comment]
Could you elaborate a bit more? Having Preview Mode doesn't slow down your deployments.

**Comment by Gaelan** [comment]
Sure. My deployment mechanism hashes files to determine whether they need to be re-deployed. Using serverless mode, Next 9.5, Webpack 5, and a `generateBuildId` that returns the git commit hash, running `next build` twice in a row still changes every file in `.next/serverless/pages`, because it generates a new `previewModeId`, `previewModeSigningKey`, and `previewModeEncryptionKey`. Without that feature, my deployments would only need to upload the code for pages that actually changed, which would speed things up a fair bit.

**Comment by Timer** [comment]
Ooh interesting! We could probably explore extracting this information into environment variables instead of inlined into the file. Since this is so low-level and an implementation detail, we likely won't be exploring adding a way to omit this from the output—it's not worth increasing the API surface.

**Comment by acburdine** [comment]
I've got a similar issue with the preview build keys using a hashed deployment system. To workaround for the moment (I also don't use preview mode) I'm just wrapping the `next build` process and overwriting the keys in the various files they appear in  to hardcoded constant values. Would definitely be interested in an alternative approach to what I'm currently doing - would also be interested in contributing a solution to said problem if it would be accepted 😄

**Comment by douglasduteil** [comment]
Same issue.
I also don't use preview mode.
I overwrite the keys by mocking the `randomBytes`

```js
// next.config.js
require("crypto").randomBytes = () => "FIXED_PREVIEW_MODE_ID";

module.exports = {
  target: "serverless",
  generateBuildId: () => process.env.BUILD_ID || "build",
};
```

```sh
$ yarn next build 
[...]
$ find .next -not -path "*/cache/*" -type f | xargs sha1sum | sha1sum
a51a886da356988b317546ca4beccc8d0ba7d2c8  -
$ yarn next build 
[...]
$ find .next -not -path "*/cache/*" -type f | xargs sha1sum | sha1sum
a51a886da356988b317546ca4beccc8d0ba7d2c8  -
```
