### ISSUE TITLE
 next export with getServerSideProps

### ISSUE THREAD

**Issue by eric-burel** [vercel/next.js#15674]
# Feature request

### Why using both next export and `getServerSideProps`

I develop apps that may be deployed on premise. For the same codebase, I'd like to leverage as many deployment options as possible.

- `next export` is the simplest of them. The interesting part is that it doesn't depend on Node, or on the build environment: I can deliver it as is to a client that don't have the ability to install Node.js on its server/dev machine.It does happen more than one can think, even in 2020 especially in big/old companies where introducing a new technology is a complicated process, or that do not use SaaS applications at this point.

- "normal" deployment with a Node server and SSR, for other companies

I may need to deploy the same app on dozens of companies, I really do need to keep a "no dependency to Node" strategy around.

Edit: other relevant use cases:

- You can't control 3rd party libraries. Some of them might use `getServerSideProps` for some optional feature, and thus break your export. So even if you just want `next export`, without ever using `getServerSideProps`, you may have some trouble
- You may have difficulties with SSR: handling a refresh token with SSR is still an open subject: https://github.com/vercel/next.js/discussions/17515. Having to support SSR may hinder your development capabilities at early stage of a project. You might still want to have a SSR, but wait a bit later when it's really useful in your app and worth the hassle.

### Problem

`next export` will just fail if a page is using `getServerSideProps`.

### Limitations

I am aware that `next export` is a a secondary feature. However, when you use it for an app, you do use it and it become a very important part of the deployment process.

I am also aware that supporting `next export` and `getServerSideProps` altogether would definitely create confusion for end user. Mostly because static export seems to be confused with Next's build-time server-side rendering+incremental refresh, so people forget that they don't have a server in this scenario.

Of course, for this to work, you need your `getServerSideProps` function to be optional. It should either be limited to a performance boost (eg caching stuff in Apollo, redirecting quickly), or "duplicated" in the client code when it doesn't run.

## Describe the solution you'd like

Possibles solutions, in order of preference:

- Don't throw an error, just a big warning, when exporting pages with `getServerSideProps`. And of course ignore the function itself.
We already ignore API routes during next export so we could ignore `getServerSideProps` too

- Don't deprecate `getInitialProps`, instead consider it as advanced feature that can be used to handle multiple scenarios in the same page, and maybe improve it to make it easier to differentiate the current rendering scenario (client, server, static export). Currently you have to reach the old documentation to get it, and play around with context `req` to guess the current environment.

- Add an option to allow exporting a page that include `getServerSideProps`, eg `allowStaticExport`, `optionalGetServerSideProps`, `makeSureThatYourPageWorkWithoutGetServerSidePropsToo`, whatever

- Create a new callback, `getIsomorphicProps`, that should work both client-side and server-side (unrealistic, because you wouldn't be able to use React hook, or access the server request, so you wouldn't be able to code smth clean, but you get the idea)

- Create a new callback, `getPrecomputedServerSideProps`, that is explicitely meant to be optional

## Describe alternatives you've considered

Using `getInitialProps` is a palliative, see  our [withPrivateAccess HOC](https://github.com/VulcanJS/vulcan-next-starter/blob/devel/packages/%40vulcan/next-utils/routing.tsx) that supports all scenarios.

Other possible alternative proposed by @jescalan: create a Babel plugin/script that removes `getServerSideProps` from the code and imported modules, and tweak `export` command like so `"export": "node ./scripts/remove-server-props.js && next export`.
But again IMO if export doesn't fail when there are API routes in the code it probably should'n't fail when there are `getServerSideProps` in a page.

## Additional context

The apps I develop are almost softwares, so few pages, but high complexity on each page. SSR is cool when you host yourself, but static export is also cool in this scenario, especially when you host on-premise as it is almost similar to an executable you can reuse on any machine.
I can't predict which deployment scenario will be used at the time I write the code, I often get the info mid-project.

Also, I use Apollo massively. It's a good fit for this multi-target export scenario: server-side, you can prefill the cache by running queries. But client-side, Apollo is also able to rerun the query if it failed during server-render or was never run in the first place (basically when it encounter a cache miss).

Eventually, when running Cypress tests, you can't mock server side rendering calls. Since SSR can't be disabled on the fly, one possible path is to use `next export` when your app supports it alongside SSR.

## Related discussions

- Next export and getServerSideProps risk of confusion https://github.com/vercel/next.js/discussions/15440
- Private pages in all scenarios https://github.com/vercel/next.js/discussions/14531 https://stackoverflow.com/questions/58173809/next-js-redirect-from-to-another-page/60616536#60616536
- No possibility to disable SSR https://github.com/vercel/next.js/issues/4381
- This leads to Next export not being supported in next-18nnext. Serverless or `next export`, you have to pick one if you want i18n https://github.com/isaachinman/next-i18next/issues/780#

**Comment by eric-burel** [comment]
I've published a **draftish**, **unsafe**, **untested** Babel plugin that could help removing `getServerSideProps` during `next export`:

- https://github.com/lbke/babel-plugin-next-optional-server
- https://www.npmjs.com/package/babel-plugin-next-optional-server

Still not sure where to put it so it is triggered during export, but unit test are ok.

**Comment by eric-burel** [comment]
I am not very satisfied with the Babel approach after more digging. First it is difficult to setup, I've tried to use `PrebuildPlugin` to run a prebuild step but I still can't tell how to apply a babel plugin programmatically to the files. Then it is costly in terms of performance.

And I still can't consider relying on `next export` safe as long as the mere presence to `getServerSideProps` in a 3rd party package makes the whole thing explode (without even talking of having multiple deployment mode for the same app).

So the cleanest way to handle this would be to add an option to `next export` for this advanced use case.

Digging into Next code, the following steps would be needed:
- in `packages/next/export/worker.ts` do not throw error when `getServerSideProps` is found.
- then, calling `getServerSideProps` during render should be disabled. It is related in `next/dist/next-server/server/render.js`

I am still digging Next code, I'll update this comment when I progress.

**Comment by craigatproperly** [comment]
Wanted to add another +1 to this as a useful scenario. Specifically for the case of the same code base being deployed in different ways.   In our scenario it seems allowing the presence of getServerSideProps in the codebase when exporting (but of course it is inactive in that scenario) would achieve our desired results.    

We are investigating work arounds of splitting our codebase differently; and generally trying to determine how to have those exports conditionally present in different deploy scenarios.

**Comment by eric-burel** [comment]
Note that you may want to check what is bundled into the client export in this scenario, because as far as I understand, Next has some custom logic to remove server-related code from the client bundle when encountering `getServerSideProps`. 
So I wonder if your solution will remove it after the code is "sanitized" for client bundle (in which case it's fine), or before.
