### ISSUE TITLE
Loading chunk {{xxx}} failed. Error after  PC hibernating

### ISSUE THREAD

**Issue by JonCognioDigital** [vercel/next.js#15683]
# Bug report

## Describe the bug

Since upgrading to 9.5.0 and when in dev mode, if you leave your computer to hibernate or sleep you get chunk loading errors when you switch it back on until you restart the dev server. It's usually "Chunk 0" but this time I got chunk 31.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run version 9.5.0
2. Start the dev server and visit a few pages.
3. Put your PC to sleep
4. Switch it back on again and make a change to a file so it recompiles.
5. Try to visit that page.
6. You will probably get the error

## Screenshots

![image](https://user-images.githubusercontent.com/2878796/88922500-1c36b300-d268-11ea-815b-ebb958209adc.png)

## System information

- OS: [Windows]
- Version of Next.js: [9.5.0]
- Version of Node.js: [e.g. 10.16.2]

**Comment by JanKaifer** [comment]
Hi, I'm cleaning up old issues.
We won't spend time on this since we can't easily reproduce it and no one else reported this.
