### ISSUE TITLE
Client Side Rendering Not Working In Dev Mode

### ISSUE THREAD

**Issue by ahurlburt** [vercel/next.js#15782]
# Bug report

## Describe the bug

I'm using a custom server implementation of next. I am having an issue in dev mode which is not reproducible outside of dev mode.

Basically, when I launch next in dev mode then the client React methods are not called (ie ComponentDidMount)

const app = next({ dev, quiet: false });

When I launch the app without dev mode after running 'next build':

const app = next({ quiet: false });

Then the client side lifecycle methods are called appropriately.

I'm guessing I'm probably doing something wrong somewhere in my application but I am new to next and any help / pointing to the right direction would be appreciated. Please let me know what other information may be relevant to help reproduce.

I recently upgraded next, it was previously working (on 8.1.0).

## Expected behavior

I would expect dev mode to call the same lifecycle as the production build.

## System information

- OS: macOS
- Version of Next.js: [9.5.0]
- Version of Node.js: [10.16.0]

**Comment by jamesmosier** [comment]
Hi @ahurlburt. Do you have an example repository of the code that is not working?
