### ISSUE TITLE
fallback: true - fallback page could optionally load ASAP when next.js Link is clicked

### ISSUE THREAD

**Issue by r00dY** [vercel/next.js#15869]
# Feature request

Scenario.
1. We have a page `/product/[handle]` with `fallback: true`.
2. Let's say `/product/123` is not yet generated statically.
3. We have a page `/collection` with next link to `/product/123`, no prefetching, or haven't prefetched yet.
4. We click on a link.
5. Nothing is happening until page is generated and then page reloads. Fallback page wasn't loaded at any point in time.

Last point could have optional alternative behaviour: showing fallback page ASAP.

## Is your feature request related to a problem? Please describe.

We already designed a loading page for when `router.isFallback = true`. I want to reuse this loader for next.js reloads when static site is being generated.

Now after clicking next.js link I have either 1-2 seconds moment of "nothing happening" which is bad UX. I cold build a loader on router events, but then I'd have to maintain two loading states instead of one.

## Describe the solution you'd like

A flag for `Link`? Something like `showFallbackImmediately`? Could default to `false` to preserve backward compatibility. 

Potentially it could be a trait of a page too.

**Comment by Visakeswaran** [comment]
**next 9.0.2**
I am facing a similar issue. I am routing to a dynamic route having around 12 api calls inside getInitialProps(), using next/link. when i trigger routing, the page becomes unresponsive until all the api fetching is done. I have referred to the with-loading example and also disabled prefetch for link, but no good.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17028188/89517172-faed3e00-d7f6-11ea-8ea6-873f51fe8708.gif)

**Comment by yunyong** [comment]
I have same issue.
```
 if (router.isFallback) {
    return <div>Loading...</div>
}
```
'Loading...' does not appear in **PRODUCTION** mode. (in development, it works)
When I click on the link, nothing happens for 1~2 sec.
I want to change the page ASAP and show a spinner for users.

**Comment by danielcolinjames** [comment]
I actually thought this was how `fallback: true` already worked, but just implemented it and realized it doesn't work like that... Did anyone figure out any way to achieve this? I really wanted to eliminate that 1-2 seconds of no-visual-feedback loading time when clicking a Next `<Link />` and `getStaticProps` has to build the page...

**Comment by nathanaelphilip** [comment]
I too would like this. Seems like an essential feature when page loads take a few seconds.

**Comment by danny-dang** [comment]
In my case, `router.isFallBack` doesn't work really well for me. The page still freeze for about few seconds before redirecting to a new route.
After several hours of reading docs. I found these 2 events from router: `routeChangeStart` and `routeChangeComplete`
Basically you can listen when the page has finish redirecting.

I'm doing something like this
```javascript

  useEffect(() => {
    const handleRouteChange = (url) => {
      dispatch(setLoading(true))
      console.log(
        `App is changing to ${url} `
      )
    }

    const handleRouteComplete = (url) => {
      dispatch(setLoading(false))
      console.log(
        `App changed to ${url} `
      )
    }

    router.events.on('routeChangeStart', handleRouteChange)
    router.events.on('routeChangeComplete', handleRouteComplete)

    return () => {
      router.events.off('routeChangeStart', handleRouteChange)
      router.events.on('routeChangeComplete', handleRouteComplete)
    }
  }, [])
  
  if(isLoading){
     return <Loading/>
  }
```

**Comment by meandillar** [comment]
> In my case, `router.isFallBack` doesn't work really well for me. The page still freeze for about few seconds before redirecting to a new route.
> After several hours of reading docs. I found these 2 events from router: `routeChangeStart` and `routeChangeComplete`...

I've tried using the router events as suggested above but I have the same problem as using `router.isFallback`. The `routeChangeStart` event doesn't fire on initial navigation so I still get a delay while the page builds.

Seems like `router.isFallback` works as expected if you go directly to a url and allows you to display a loader, but not when navigating using a next/link.

**Comment by LOLsho** [comment]
I have the same issue.
It would be very nice to render page right after clicking on a link and show loader while data for page is loading
