### ISSUE TITLE
getStaticProps return undefined during build

### ISSUE THREAD

**Issue by rake5h1** [vercel/next.js#15944]
getStaticProps returns undefined while fetching data from external API.

**Comment by filipesmedeiros** [comment]
Can you please provide more information so we can help? Maybe a code excerpt? Is it doing the fetching asynchronously?

**Comment by rake5h1** [comment]
I am using getStaticPaths and getStaticPaths to fetch posts from external API.While development it works fine if we navigate to that page but when I reload it shows an error.getStaticProps returns undefined.

export async function getStaticPaths() {
  
  const res = await axios.get(`${process.env.URL}/recent`);
  const data = await res.data;
  const paths = data.map((post) => {
    return {
      params: { id: post.Title },
    };
  });

  return { paths, fallback: true };
}
export async function getStaticProps({ params }) {
  const id = params.id;
  const res = await axios.get(`${process.env.URL}/postid?title=${id} `);
  const data = await res.data;
  return {
    props: { data: data },
  };
}

It is weird because for one post it works reloading but for other it shows error

**Comment by filipesmedeiros** [comment]
Ok you have some weird things that I will assume are just typos here and are not in the actual code (like the axios argument strings not being inside quotes).

Also I'm not too familiar with axios but I think `res.data` is not a Promise.

Other than that, this seems fine, to be honest. What are the file names for the relevant paths on your project?

**Comment by rake5h1** [comment]
routes are /Post/[id]

**Comment by filipesmedeiros** [comment]
In that case the only thing I can ask/recommend is you log the axios responses and data to make sure it's coming correctly on both functions. Maybe the server is not returning what you expect? Sorry I couldn't help further
