### ISSUE TITLE
Docker runtime Environment Variables doesn't work

### ISSUE THREAD

**Issue by gyto23** [vercel/next.js#16099]
This question was asked here #15651, but I assume that no one checking it. Anyways, this look like not working functionality that proceed even with new clear setup.

So I spend a lot of time debugging this and trying to figure out a better approach to build application on the docker. After running a simple `Dockerfile` I have mention that non of my .env variables doesn't work, and I assume this is really common problem after 9.4 release where we have to specify env var as `NEXT_PUBLIC_` (which doesnt work for on runtime configurations) I know that I can go with a `ARG` on buildtime but this is not a option for me because the application is multi domain application which needs different env var in different domains. My general question to the community of next.js is there a way and how to trigger runtime variables after application image is build and before docker container is running? 

P.S. next.js application uses a `express` server as custom server, and I dont use any of the `serverless` features 

```
FROM node:alpine

ENV TEMP_DIR /app

# Create app directory
RUN mkdir -p ${TEMP_DIR}
WORKDIR ${TEMP_DIR}
RUN apk add --no-cache libc6-compat

ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

COPY .npmrc ${TEMP_DIR}
COPY package.json ${TEMP_DIR}
COPY yarn.lock ${TEMP_DIR}
COPY faviconDist.json ${TEMP_DIR}

RUN yarn install --no-optional
RUN rm -f .npmrc

COPY . ${TEMP_DIR}

RUN yarn build

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

USER nextjs

CMD ["yarn", "start"]

```

**Comment by jamesmosier** [comment]
I don't think this is an issue with Next, so the [discussion you opened](https://github.com/vercel/next.js/discussions/15651) is the best place for questions like these.

> this look like not working functionality that proceed even with new clear setup.

*What* is the issue with Next in this scenario? 

> I assume that no one checking it.

Plenty of people check! It just seems as if no one was able to help with your specific issue at that specific time unfortunately. I  just responded to your Discussion.
