### ISSUE TITLE
trailingSlash not present in tests

### ISSUE THREAD

**Issue by danhodkinson** [vercel/next.js#16094]
# Bug report

## Describe the bug

When setting `trailingSlash: true` in `next.config.js` I would expect the snapshots and toBe style tests to also contain the trailing slash. It seems to ignore this (even when passing the trailing slash as part of the `as` property in `<Link>`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a `<Link passHref href={'/[dynamic]'} as="/page/">` component (or any variant with/without trailing slashes)
2. Create a test that renders a snapshot or `expect` the `href` value `toBe('myurlwithslash/')`
3. Run tests

## Expected behavior

Href's contain trailing slashes to mimic what is actually rendered on the page

## Screenshots

Snippet from snapshot

<img width="378" alt="Screenshot 2020-08-11 at 21 44 58" src="https://user-images.githubusercontent.com/1689209/89947162-f3290180-dc1b-11ea-8ea5-72c809f3c342.png">

## System information

- OS: macOs
- Version of Next.js: v9.5.2
- Version of Node.js: v10.16.3

**Comment by marcklei** [comment]
So I ran into the same issue.

As a temporary workaround I set `__NEXT_TRAILING_SLASH` as environment variable in my jest setup since its used here https://github.com/vercel/next.js/blob/f8534a6e62a494663a91ca83893855827df649be/packages/next/client/normalize-trailing-slash.ts#L12 and set by webpack https://github.com/vercel/next.js/blob/f8534a6e62a494663a91ca83893855827df649be/packages/next/build/webpack-config.ts#L922

So I added the following to my `jest.config.js`:

```js
/**
 * Set __NEXT_TRAILING_SLASH to configure trailing slashes for tests
 * Temp workaround for https://github.com/vercel/next.js/issues/16094
 */
const { trailingSlash } = require('./next.config');

process.env = { ...process.env, __NEXT_TRAILING_SLASH: trailingSlash };
```

At least my tests are passing now again, but I am open for ideas which do not feel that hacky :)

**Comment by eric-burel** [comment]
Hmm I couldn't set this up in Cypress though, I don't know how to set "process" like you did in jest.config.js

**Comment by aboqasem** [comment]
I tested `trailingSlash: true` with the [with-cypress example](https://github.com/vercel/next.js/blob/b173abaf49164e3a7fb0f41a3ca81a48fb58bd2e/examples/with-cypress/cypress/integration/app.spec.js), and [here is the video that it works](https://user-images.githubusercontent.com/62098043/171092459-cd310f79-3214-495d-80e2-c0abe50b6a77.mp4).

Diff:

```diff
diff --git a/examples/with-cypress/cypress/integration/app.spec.js b/examples/with-cypress/cypress/integration/app.spec.js
index a1330a1a9..b66f7b740 100644
--- a/examples/with-cypress/cypress/integration/app.spec.js
+++ b/examples/with-cypress/cypress/integration/app.spec.js
@@ -12,7 +12,7 @@ describe('Navigation', () => {
     cy.get('a[href*="about"]').click()
 
     // The new url should include "/about"
-    cy.url().should('include', '/about')
+    cy.url().should('include', '/about/')
 
     // The new page should contain an h1 with "About page"
     cy.get('h1').contains('About Page')
diff --git a/examples/with-cypress/next.config.js b/examples/with-cypress/next.config.js
new file mode 100644
index 000000000..ce3f975d0
--- /dev/null
+++ b/examples/with-cypress/next.config.js
@@ -0,0 +1,3 @@
+module.exports = {
+  trailingSlash: true,
+}
```

**Comment by samcx** [comment]
@danhodkinson I don't believe this is an issue anymore so I am closing this!

If you are still experiencing an issue, please feel free to submit a new [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml)!
