### ISSUE TITLE
[Next.js /learn] Mark steps as finished after leaving the page

### ISSUE THREAD

**Issue by lfades** [vercel/next.js#16133]
Currently, once you enter a new step in one of our /learn lessons, it's marked as finished. It would be much better if we only mark it as finished after you navigate to the next step or to a different lesson. That way you won't see the blue checkmarks before finishing the course.

**Comment by lachlanjc** [comment]
Transfer this issue, since the site isn’t open source anymore?

**Comment by timneutkens** [comment]
Issues on Next.js are automatically synced into our internal issue tracker hence why this one is kept here, however I've removed the good first issue 👍

**Comment by molebox** [comment]
Is this still valid? cc @lfades if not, can we close please
