### ISSUE TITLE
Ignore spec/test file when building the app

### ISSUE THREAD

**Issue by goenning** [vercel/next.js#16237]
# Feature request

## Is your feature request related to a problem? Please describe.

Next currently exposes spec files as an API route

## Describe the solution you'd like

spec|test files should be ignored by Next.js when compiling the app.

## Describe alternatives you've considered

Right now I just ignore it, but that's being needless deployed to Vercel

## Additional context

<img width="608" alt="Screenshot 2020-08-16 at 19 45 09" src="https://user-images.githubusercontent.com/94755/90341714-b3865f00-dff9-11ea-82d1-1dc52d068c2f.png">

**Comment by davidcalhoun** [comment]
It seems that at the moment they expect all tests to be located in `__tests__` at the root, but I am like you and also want to co-locate the tests with their code.  It appears the only way to do this at the moment is to import a Webpack plugin and configure it to ignore files there.
