### ISSUE TITLE
9.5.2 dev server does not respond to requests

### ISSUE THREAD

**Issue by tomaszrondio** [vercel/next.js#16302]
# Bug report

## Describe the bug

Server is unresponsive in dev mode. Requests are pending forever and get cancelled. In "production" mode it works fine.
Updated from 9.4.6 
I use next-pwa

## Screenshots

<img width="847" alt="Screenshot 2020-08-18 at 12 17 19" src="https://user-images.githubusercontent.com/4939724/90502245-cc078e00-e14d-11ea-9b5c-50196ff3b027.png">

## System information

- OS: macOS
- Browser chrome
- Version of Next.js:  9.5.2
- Version of Node.js: 10.15.0

**Comment by daveteu** [comment]
did u use asPath in your code? #16269

**Comment by tomaszrondio** [comment]
I do to check if menu item should be active or not.
`const indexOfQuestionMark = router.asPath.indexOf("?");
  const asPath = router.asPath.substring(
    0,
    indexOfQuestionMark !== -1 ? indexOfQuestionMark : router.asPath.length
  );
  const linkClassName = asPath === href ? "active" : "";`

All Links are generated like this: 
`<Link href="/[...slug]" as={href}>` 
where `href` is a string from database. `[...slug]` cateches all routes except homepage

**Comment by tomaszrondio** [comment]
funny thing is that sometimes it works and at some point it stops to work. Then if I restart the server it works again. There must be some bug that does not throw an error message.

**Comment by tomaszrondio** [comment]
I disabled next-pwa for dev environment and it looks that it helped.

**Comment by timneutkens** [comment]
Converting to a discussion as there is no reproduction so it's impossible to investigate.
