### ISSUE TITLE
Allow Lazy Incremental Static Regeneration

### ISSUE THREAD

**Issue by NikhilVerma** [vercel/next.js#16303]
# Feature request

We are writing a Next.js app for a blog. The blog has around 100 posts and serves localised content in around 22 languages. They are all static pages generated with a wordpress backend. This means NextJS has to make around 2200 network requests for Wordpress posts before the app can be compiled making the build times long and flaky depending on network conditions.

## Describe the solution you'd like

Lazy incremental static generation. In which Next.js will not pre-compile any static pages (even if they are static) instead it will fetch them on the first request to the page and then cache them for the future visits. This will make build times incredibly fast for large websites while doing a small sacrifice on the performance for the first visitor on a new page.

## Describe alternatives you've considered

Dynamic pages `getServerSideProps ` could fix this too but they will always fetch and not cache. We could consider adding our own cache layer on top of dynamic pages but it seems like if Next.js will have a flag to just "skip" the initial prefetching of pages it will work much better.

**Comment by timneutkens** [comment]
This is already supported, see the docs: https://nextjs.org/docs/basic-features/data-fetching#fallback-true
