### ISSUE TITLE
Trailling slash option enables dynamic route to respond to non supported path

### ISSUE THREAD

**Issue by d3x7r0** [vercel/next.js#16855]
# Bug report

## Describe the bug

After v9.5.3 it looks like a dynamic route will respond to a path that is not in the result of `getStaticPaths` when fallback is false and the `trailingSlash` option is enabled.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the repo and run the example app using `yarn dev`: https://github.com/d3x7r0/nextjs-trailling-slash-issue
1. Go to the home page
2. Click on the "go to bar" link
3. Notice that you ended up at the "/[foo]/" page instead of the expected "/bar"

## Expected behavior

When clicking the "go to bar" link the bar page should be rendered.

## System information

- OS: tested on MacOS and Linux
- Version of Next.js: 9.5.3
- Version of Node.js: v12.18.3

**Comment by JanKaifer** [comment]
`getStaticPaths` will not restrict the paths that can be accessed. It will just prebuild them. So not providing `getStaticPaths` is the same a as returning `[]`.

Docs: https://nextjs.org/docs/basic-features/data-fetching/get-static-paths#generating-paths-on-demand
