### ISSUE TITLE
[documentation] missing page config documentation

### ISSUE THREAD

**Issue by AmazingTurtle** [vercel/next.js#16868]
# Bug report

## Describe the bug

I know there is `config` export for pages and api routes. They are partially described in [api-middlewares#custom-config](https://nextjs.org/docs/api-routes/api-middlewares#custom-config) or in [amp-support](https://nextjs.org/docs/advanced-features/amp-support/introduction) for example.

I was searching for documentation on that `config` export but I couldn't find it.
Also: is a typescript type available for the `config` export?

## To Reproduce

Look at the next.js docs and search for documetation on `config` export for pages or api routes

## Expected behavior

There is no such documentation on the `config` export

**Comment by vuki656** [comment]
This should probably be opened in the repo for the website [here](https://github.com/vercel/next-site)

**Comment by AmazingTurtle** [comment]
@vuki656 doubt it, the docs are part of this repo, see https://github.com/vercel/next.js/blob/canary/docs/basic-features/pages.md for example

**Comment by anshdhinhgra47** [comment]
I would like to work on this issue. Could you please let me know your requirements?

**Comment by lachlanjc** [comment]
Isn't this covered on https://nextjs.org/docs/api-reference/next/amp? I'm not aware there are other config options supported.

**Comment by AmazingTurtle** [comment]
@lachlanjc the amp config is documented there but I'm talking about a more generic and comprehensive documentation on the config object at all, not specifically about the amp subkey inside it.

**Comment by lachlanjc** [comment]
@AmazingTurtle Yeah, but are there other options you can pass to the config object? I may just not know about them, but if there aren't other properties accepted, I don't think it makes sense to have a page that just refers you to the AMP page to read about the one property.

**Comment by AmazingTurtle** [comment]
@lachlanjc read carefully in the first post of this issue, I mentioned two places for different configurations within the `config` object, one of which is for AMP. I am asking for a consolidated central place of documentation for all `config` object subjekeys, not just amp specific, not just middleware specific. There's also some experimental feature flags that you can control via the config object but those are mostly undocumented as well. You find those options in several github issue comments or git diffs but you can't read documentation about them because nobody has written it.

**Comment by lachlanjc** [comment]
Ah yeah, that's intentional—I've asked the Next team at various points & they don't want experimental features to be documented because they don't want most folks using them until they're stable/released/announced.

**Comment by leerob** [comment]
@AmazingTurtle the `config` object changes depending on where you're using it from (e.g. amp). There shouldn't be a single place listing all the config objects, because you need the context of _where_ you're using that value. 

As @lachlanjc, experimental values aren't put into the documentation because they're not stable. Once they're stable, they will be added.

Thank you regardless! 👍
