### ISSUE TITLE
[9.5.3] Next/link not following redirects defined in next.config.js

### ISSUE THREAD

**Issue by reckter** [vercel/next.js#16928]
# Bug report

When specifying redirects in the next.config.js on next.js 9.5.3, `next/link` on the page will not pick that up that redirect correctly, and not redirect accordingly, leading to a navigation to the source of the redirect (instead of the destination).

I made a minimal repository with said error: https://github.com/homefully/next-js-9-5-3-link-redirect-bug

Steps:
- next.js config with a redirect (here from `/failure` to `/success`)
- `<Link passHref href="/failure">...</Link>` 
- It should instead go to `/success`, but doesn't.

To use the provided repository:
- `npm run ci`
- `npm run dev`
- go to "localhost:3000"
- Link should lead to /success, but instead goes to /failure

Happens in both dev and production builds.

## Expected behavior

Link should follow the redirect and go to `/success`, Best case, even show that redirect in the link preview beforehand.

## Additional context

This behavior did work as expected prior to next.js 9.5.3 (in 9.5.2 for example).

**Comment by ijjk** [comment]
Hi, the behavior you're describing does not work in previous versions of Next.js since `href` always maps to the page on the filesystem if it exists with `next/link`. If you want to redirect `/failure` to `/success` you should remove the `failure` file from your pages directory and use a normal anchor tag.

**Comment by vanandmkrtchyan** [comment]
If there were a way, a middlware like functionality BEFORE `getServersideProps`, that would be a great...

in my case I've wrapped my `getServersideProps` with HOF and checking if path exists in redirects list...

```javascript
export const preferRedirects = (callback) => (context) => {
  const { resolvedUrl } = context

  const path = resolvedUrl.split('?')[0]

  const redirect = redirects.find((item) => item.source === path)

  if (redirect) {
    return { redirect }
  }

  return callback(context)
}
```
