### ISSUE TITLE
Serverless functions do not support multi-part data when deployed to Vercel.

### ISSUE THREAD

**Issue by isjackwild** [vercel/next.js#17023]
# Bug report

I have an app with serverless functions to handle form submissions, and this is deployed to Vercel. Vercel does support multipart form data, and if I do not use the Next.js framework, the serverless function works as expected, however when deployed within Next.js, it does not.

## To Reproduce

I've created repositories and deployments to reproduce the issue here. The only difference between the two examples is that on the Next.js one, the serverless function runs in the Next.js ecosystem (ie. within `pages/api/upload`), whereas in the vanilla one, the serverless function runs direct in Vercel (ie. within `api/upload`).

### Serverless alone version:
https://serverless-multipart-form.vercel.app/api/upload
https://github.com/isjackwild/serverless-multipart-form

### Next.js version:
https://serverless-multipart-form-nextjs.vercel.app/api/upload
https://github.com/isjackwild/serverless-multipart-form-nextjs

## Expected behavior

The multipart data should be parsed in the `pages/api/upload` function, as it is in the vanilla version of the repo.

## System information
- Version of Next.js: 9.5.2

**Comment by timneutkens** [comment]
Can you try disabling body parsing on the API route?

```
export const config = {
  api: {
    bodyParser: false,
  },
}
```

 https://nextjs.org/docs/api-routes/api-middlewares#custom-config

**Comment by isjackwild** [comment]
Hi Tim :)

I already tried this approach and it didn't seem to make any difference. I
just re-added it to test again and it's still having the same issue I'm
afraid.

**Comment by ritz078** [comment]
Here is a working example: https://github.com/ritz078/raaga/blob/master/src/pages/api/process-file.ts#L12

**Comment by isjackwild** [comment]
Oh my god this made me realise that the reason mine wasn't working, despite
using `export const config = {...}` was because I was exporting my main
handler with the `module.exports =` syntax, which I think will have
overwritten the config export. I spent hours scratching my head, could not
see the wood through the trees! Wouldn't guess I've been doing this for
years. 🙄😂

Thank you!!

**Comment by devuxer** [comment]
@isjackwild,

So, are you saying this issue is resolved (or a non-issue), or there's still an issue, but @ritz078's workaround worked for you? Or you came up with some other solution? Thx.

**Comment by ijjk** [comment]
Closing as this appears to be resolved and was due to mixing `module.exports` with `export const config`
