### ISSUE TITLE
Invalid Unicode escape sequence from _buildManifest.js

### ISSUE THREAD

**Issue by flybayer** [vercel/next.js#17056]
# Bug report

## Describe the bug

Roughly 5-10% of the time when starting the Next.js dev server in Blitz.js results in the below error in the browser immediately after first page load. This error shows in the dev error overlay and in the browser console.

```
SyntaxError: Invalid Unicode escape sequence        _buildManifest.js:1
```

Before `9.5.3`, it would show as something like `s is undefined`.

Note: we do have concurrent mode enabled, so possibly it could have something to do with that?

## To Reproduce

I'm unable to reliably reproduce, but here's how it happens:

1. `npx blitz new testapp`
2. `cd testapp`
3. `yarn blitz start`
4. Immediately click the `localhost:3000` link as soon as it appears from the Next.js dev server
5. Repeat steps 3 & 4 until you see the error

## Expected behavior

Should not error

## System information

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 614.28 MB / 64.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
  Next.js: 9.5.3

**Comment by ShikChen** [comment]
Just hit this today. Is there update?

**Comment by flybayer** [comment]
@ShikChen did you encounter this in a blitz project or regular next.js?

**Comment by ShikChen** [comment]
It's a blitz project.

**Comment by MisterJimson** [comment]
I just started seeing this when updating from node 16.6.2 to 16.13.0, no other changes.

**Comment by amirho1** [comment]
@flybayer  I don't think it's because of blitz.js. it happened to me in a regular project (version=12.0.4)

**Comment by ppedziwiatr** [comment]
So we're struggling with this in our current project.
It's just a test project that adds our library as a dependency and verifies if next.js works.

All other bundlers that we're testing (webpack 4/5, vite, rollup, parcel) work without any issue.

it builds (i.e. `next build`)
it runs in dev mode (i.e. `next dev`).

It does not run in prod mode (i.e. `next start`):

<img width="757" alt="image" src="https://user-images.githubusercontent.com/84311757/186857785-19c8f223-7942-4396-b89b-d25bfe9ce311.png">
![image](https://user-images.githubusercontent.com/84311757/186858135-9907fef2-748d-4e17-8f14-f065dccd6799.png)

I've verified and `\u` does not come from either our library code, nor from any of the deps that are in the node_modules..

What is going on here?
