### ISSUE TITLE
getting `React is not defined` on brand new project

### ISSUE THREAD

**Issue by chrisdrackett** [vercel/next.js#17146]
# Bug report

## Describe the bug

I just started a new next.js project using `yarn create next-app` I then ran `yarn dev` within the generated folder and immediately get the error: `ReferenceError: React is not defined`

## To Reproduce

- run `yarn create next-app`
- choose a directory
- within the above project run `yarn dev`

## Expected behavior

The app runs without error

## System information

- OS: macOS
- Browser (if applies) Safari
- Version of Next.js: next@9.5.2
- Version of Node.js: 12.14.0

**Comment by vitaliemiron** [comment]
try to update nodejs

**Comment by justAdevTV** [comment]
@vitaliemiron I don't think it's the node version.

> Node.js 10.13 or later

See from here: https://nextjs.org/docs#system-requirements

**Comment by justAdevTV** [comment]
What does your `package.json` look like?
