### ISSUE TITLE
router.push fails when app is ran over file:// not http://

### ISSUE THREAD

**Issue by momakes3** [vercel/next.js#17212]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run https://github.com/vercel/next.js/tree/canary/examples/with-electron _(or an exported Next.js (eg. `out/index.html`) over file:// I do this via an `electron-next` app)_
2. Click on a button that triggers `router.push('/about')`
3. It will not navigate but throw an error: 'Invalid relative URL`

## Expected behavior

Should accept the URL even if it's not served over HTTP, but it's file://.

## Screenshots

When run the static export, any `router.push` call results in this error now: 
![ElectronNext 2020-09-19 at 12 02 30@2x](https://user-images.githubusercontent.com/56743114/93661824-31fa7480-fa70-11ea-8d2f-7da47dda1437.png)

## System information

- OS: macOS
- Browser (if applies) Electron/Chrome
- Version of Next.js: 9.5.3
- Version of Node.js: 12.8

## Additional context

Change of this line I believe is causing Next's router to fail when Next static output is ran in file:// context rather than served on an HTTP server:
https://github.com/vercel/next.js/blob/canary/packages/next/next-server/lib/router/utils/parse-relative-url.ts#L26

We use Next in Electron and it was working perfectly using the next's static export.

**Comment by JanKaifer** [comment]
This seems to be fixed:
https://github.com/vercel/next.js/pull/17216#issuecomment-726645055
