### ISSUE TITLE
Change body background dynamically in css

### ISSUE THREAD

**Issue by yifeikong** [vercel/next.js#17239]
Let's say I have a page called `warnings/[id].js`, I would like to make the `body {background: red}` in my css for this page only. Apparently, I can not add it to the global css file included in `_app.js` because I only want one page to be red. And I can not use `body` in my module.css files since:

```
Syntax error: Selector "body" is not pure (pure selectors must contain at least one local class or id)
```

So I would like nextjs to support change global css in module css files. Maybe like 

```css
:global body {
    background: red;
}
```

## Footnotes

Q: Why do I have to change body background, why not the container `div`?

A: overscrolling in macOS and iOS browsers will reveal body background, see https://stackoverflow.com/a/42264959/1061155

**Comment by manishprivet** [comment]
Use
```jsx
<style jsx global>
  {`
      body {
          background: red;
       }
   `}
</style>
```

in your `warning/[id].js`
