### ISSUE TITLE
Error fetching _devPagesManifest.json

### ISSUE THREAD

**Issue by Unsfer** [vercel/next.js#17274]
# Bug report
I'm proxying my dev app from localhost to `https://` to avoid mixed request.
And when I hover on Next/Link nextjs tried to fetch _devPagesManifest.json but got rejected by SSL and then has error `pages is undefined`;

Could you add `credentials: 'same-origin'` to fetch options when loading `_devPagesManifest.json`?

**Comment by timneutkens** [comment]
Feel free to send a PR including an integration test for your particular use case.

**Comment by jeff-r-koyaltech** [comment]
based on what I'm seeing here, this one can perhaps be closed now:
https://github.com/vercel/next.js/pull/17702

**Comment by Syedhussainsaber** [comment]
Hey @timneutkens can you assign this issue to me ?

**Comment by Syedhussainsaber** [comment]
I will solve this issue

**Comment by itz-Me-Pj** [comment]
@timneutkens created a PR for the fix as suggested. Pls review and suggest if anything else needs to be added in this PR.
