### ISSUE TITLE
.cjs files are not parsed/transpiled correctly by Babel in builds

### ISSUE THREAD

**Issue by jaydenseric** [vercel/next.js#17305]
# Bug report

## Describe the bug

CJS modules with the `.cjs` file extension ([a standard Node.js file extension](https://nodejs.org/api/esm.html#esm_package_scope_and_file_extensions)) that are imported in pages are not parsed or transpiled correctly by Babel in Next.js builds.

## To Reproduce

1. Setup a barebones Next.js project.

2. In `a.cjs`:

   ```js
   const a = { b: 'ok' };
   
   module.exports = a?.b;
   ```
3. In `pages/index.js`:

   ```jsx
   import a from '../a.cjs'
   
   export default function HomePage() {
     return a;
   }
   ```

4. Run `npm run build` (`next build`), and see the logged build error:

   ```
   > next build
 
   info  - Creating an optimized production build  
   Failed to compile.
 
   ./a.cjs 3:19
   Module parse failed: Unexpected token (3:19)
   You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
   | const a = { b: 'ok' };
   | 
   > module.exports = a?.b;
   |
 
 
   > Build error occurred
   Error: > Build failed because of webpack errors
       at build (/Users/jaydenseric/Desktop/next-experiment/node_modules/next/dist/build/index.js:15:918)
   ```

Using the `.cjs` file extension should not result in a build error, this is a Next.js bug.

Note that if you rename the `a.cjs` file to `a.js` and update the import in `pages/index.js` to `import a from '../a'`, the build succeeds and the home page renders in the browser with the expected `ok` text.

## Expected behavior

`.cjs` files should be parsed by Babel with the a `sourceType` of `script`, and (with the exception of ESM import/export syntax due to the source type) all of the usual transpilation (e.g. via `@babel/preset-env`) should occur.

## Screenshots

<img width="1238" alt="Screen Shot 2020-09-23 at 7 28 39 pm" src="https://user-images.githubusercontent.com/1754873/93994289-10342100-fdd3-11ea-9f0e-84984b413107.png">

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Additionally, Next.js should not assume `.js` files are ESM; according to Node.js standards they should be parsed as scripts (CJS), unless the the nearest parent `package.json` to the file contains a [`"type": "module"` field](https://nodejs.org/api/esm.html#esm_package_json_type_field).

These are very frustrating issues.

**Comment by JanKaifer** [comment]
Created a repro: https://github.com/JanKaifer/next.js-repro-16855
Works in dev desn't build on `next@canary`.
