### ISSUE TITLE
meta-tags are placed at bottom of the head when hit via client-side link vs top of head through server request

### ISSUE THREAD

**Issue by jaybytez** [vercel/next.js#17478]
# Bug report

## Describe the bug

We have upgraded to the latest canary to resolve the duplicate meta-data issue reported here: https://github.com/vercel/next.js/issues/17085.  The issue once we did this, is that we see the sorting of meta-tags is inconsistent.  If we hit a URL directly in the browser, then meta-tags are in the order we applied them in code (we need them to execute or become aware prior to a tag manager).  If we hit the URL via a client-side link, then the meta-tags are sorted differently and some of the meta-tags are placed after script tags.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://github.com/jaybytez/nextjs-meta-sort-order'
2. npm install
3, npm run install
4. Load http://localhost:3000/home - and look at meta tags test and pageName
5. Load http://localhost:3000/about - and look at meta tags test and pageName
6. Now click on the [Click here ->] link About or Home - and look at the meta tags test and pageName
7. pageName is now moved to the bottom of the head when the page is accessed via a client-side link

## Expected behavior

Expected behavior is that the meta-tags are in the order specified in the code.  At least, ensuring that meta tags are placed at the top of the head if they are needed by scripts executed in the head.  So not necessarily meta-tag sort order, but more an issue that meta-tags are sorted in different areas of the head.

## Screenshots

![image](https://user-images.githubusercontent.com/100770/94713441-a4d0de80-02ff-11eb-97e0-e24215ff7291.png)
![image](https://user-images.githubusercontent.com/100770/94713620-e9f51080-02ff-11eb-9795-89de60bbe43e.png)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by ssylvia** [comment]
Having a similar issue. Trying to add an analytics script that uses the `document.title` but the title tag gets placed below the script based on component rendering order. It would be good if there was a options to set the order or prioritize some tags.

**Comment by osequi** [comment]
Same issue here

**Comment by osequi** [comment]
> Same issue here

Very funny, Vercel.

**Comment by timneutkens** [comment]
Spam comments are automatically hidden. +1 and "same issue" are spam as they do not add anything to the  issue and GitHub's emoji reactions exist for "upvoting" a certain issue.

**Comment by osequi** [comment]
Ok, I see now. Thanks!

**Comment by JanKaifer** [comment]
Thanks for the reproduction. It behaves correctly on `next@13`.
