### ISSUE TITLE
CSS Combinator selectors does not work in Next.js

### ISSUE THREAD

**Issue by youngnishant** [vercel/next.js#17599]
# CSS Combinator selectors does not work in Next.js

## 
div p {
  background-color: yellow;
}

while using CSS some selectors does not work especially combinators such as given above.
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to index.js
2. use <style jsx> for css
3. write down combinators such as =>.    .link img{}

## Expected behavior

it should work properly according the real css file

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by rawat07102** [comment]
you have to surround your styles with backtick \``
<style jsx>
  { `
    div p {
        backround-color: yellow;
    }
  ` }
</style>

**Comment by youngnishant** [comment]
@rawat07102  yeah, it is still not working
