### ISSUE TITLE
Enormous number of API requests using Incremental Static Generation with revalidation

### ISSUE THREAD

**Issue by howells** [vercel/next.js#17758]
# Bug report

## Describe the bug

On two websites, I have revalidation set ranging from 5 minutes to 1 hour. However, enabling any revalidation time leads to an astonishingly high number of requests to my API, with very low traffic.

## To Reproduce

A typical `getStaticProps` in my apps might look like this:

```
export async function getStaticProps(context) {
  const navigationResponse = await fetchAPI(fetchNavigation);
  const response = await fetchAPI(fetchHomepage);
  const eventsResponse = await fetchAPI(fetchEvents, {
    limit: 12,
    orderBy: 'startDateTime ASC',
  });

  return {
    props: {
      page: response.page,
      navigation: navigationResponse,
      events: eventsResponse.events,
    },
    revalidate: 300,
  };
}
```

`fetchAPI` is a common API function that looks like this: 

```
const fetchAPI = async (query, variables = {}, token = null) => {
  const url = token
    ? `${process.env.NEXT_PUBLIC_API_URL}?token=${token}`
    : `${process.env.NEXT_PUBLIC_API_URL}`;

  try {
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${process.env.NEXT_PUBLIC_GRAPHQL_TOKEN}`,
      },
      body: JSON.stringify({
        query,
        variables,
      }),
    });

    const json = await res.json();

    if (json.errors) {
      console.error(json.errors);
      throw new Error(json.errors);
    }

    return json.data;
  } catch (error) {
    console.error(error);
    throw new Error(error);
  }
};
```

With revalidation enabled, and with hardly 10 visitors per hour, I'm seeing the API be hit almost 20,000 times per hour (!).

With revaliation disabled, my API is hit 0 times per hour. 

## Expected behavior

I'd expect the number of times my API hit with revalidation set to 300 seconds, be close to zero.

## System information

- Version of Next.js: 9.5.4

**Comment by timneutkens** [comment]
Where are you hosting your application?

**Comment by howells** [comment]
@timneutkens sorry for the delay - I've managed to get the traffic under control, partly because there were some requests that were trying to be handled with fallback being set to true, but I'm still seeing quite a high number of requests relative to the revalidation times set.

I'm struggling to work out how to reproduce this issue though, since I don't quite understand what is going on under the hood, so I'm not quite sure how to progress on this one.

**Comment by timneutkens** [comment]
Thanks for getting back to me, but could you let me know how/where you're hosting your application? Is it on Vercel? Somewhere else?

**Comment by howells** [comment]
@timneutkens sorry, Vercel, yes

**Comment by juancampa** [comment]
Do you mind sharing an example url where this is happening?

**Comment by howells** [comment]
@juancampa https://www.plymouthart.ac.uk - still seeing quite high requests to the CMS, more than I would expect, but I'm not sure I know how to analyse which requests aren't being statically handled properly

**Comment by jhinkle97** [comment]
Any update on this issue? May be running into a similar issue for my site hosted on Vercel.

**Comment by scottodea** [comment]
Hi there, having this issue also. Setting the revalidation to 1200 seconds and yet it seems to call the API as soon as the page is loaded. Turning revalidation off results in 0 requests.

**Comment by shootingsupplies** [comment]
I'm also seeing a huge amount of requests, we only have a few visitors an hour generally.

**Comment by alexllao** [comment]
How do you get the user token on the server side?

**Comment by hereisfahad** [comment]
@howells did you figure it out?

**Comment by howells** [comment]
@hereisfahad not really but today I discovered an issue with a large number of `<Links>` on a page, where each was being prefetched when they came into view: with ~100 links, each to a page that had revalidation enabled, hundreds of requests were being made to the server. I simply set `prefetch={false}` (prefetch on hover still works)

**Comment by hereisfahad** [comment]
Yes, prefetching on hover is still causing trouble, I know it's the intended behavior to get the best performance. But I am fetching the data from WordPress, and with ISR ( fallback: 'blocking'). If I keep hovering over the links (first time before static generation), multiple requests are sent and most of them are failed and the failed requests will return 404 page which will then be cached until the next revalidation.

**Comment by dipankarmaikap** [comment]
### Any update on this.? 
re-validation is set to 60 and I also noticed If I switch the browser and visit the same page it also makes a call to DB, this is not suppose to or am i missing anything.? So many unnecessary API calls.

![image](https://user-images.githubusercontent.com/45673791/130821795-a1356d09-5e79-412e-b444-3da3e1bfb1be.png)

**Comment by leerob** [comment]
@howells's comment is accurate. If you have `next/link` on the page, you could be prefetching pages that have revalidation set up, increasing the number of requests. In that case, `prefetch={false}` is a great solution, thank you for suggesting that.

@dipankarmaikap the Vercel logs will show a request for the HTML page (from the Edge) as well as the Serverless Function (that's doing the revalidation). This is expected! For further details into the logs, you can use log integrations too: vercel.com/integrations#logging

**Comment by mathewtrivett** [comment]
Had a similar situation trying to identify huge memory spikes sometimes + 500mb that crashed the container we run out next.js site in. 

We had revalidation set on all pages and were linking to them with next/link. Setting prefetch to false completely smoothed out our memory issue.

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.7-canary.23` of Next.js so that prefetching no longer triggers revalidations, please update and give it a try!
