### ISSUE TITLE
with-http2 example not working

### ISSUE THREAD

**Issue by mkhoussid** [vercel/next.js#17880]
# Bug report

## Describe the bug
The [http2](https://github.com/vercel/next.js/tree/canary/examples/with-http2) example throws an error.

## To Reproduce
In root directory, run
```
openssl req -x509 -newkey rsa:2048 -nodes -sha256 -subj '/CN=localhost' \
  -keyout localhost-privkey.pem -out localhost-cert.pem
```
Then run,
```
npm i && npm run dev
```

## Expected behavior
Should work. It was already raised [here](https://github.com/vercel/next.js/issues/10319) but the issue was closed for some reason.

## Screenshots
<img width="715" alt="Screenshot 2020-10-14 at 17 45 06" src="https://user-images.githubusercontent.com/44326107/96005359-08e9bb80-0e45-11eb-8d09-ce76f2d843e2.png">

## System information

- OS: Mac, Windows
- Browser: Chrome, Firefox
- Version of Next.js: latest
- Version of Node.js: 13.13.0

## Additional context
I've also tried following [this](https://itnext.io/using-http-2-with-next-js-express-917791ca249b) tutorial, to no avail.

**Comment by awareness481** [comment]
I had tried the http2-example earlier this week on 9.5.3 and I had the same error. You might be able to access your website through another browser (ex. Firefox) but in my case I also had issues with styles/assets but I'm using next-sass so that might not be true for projects using the built-in styles functionality (?).

So, error reproduced.

**Comment by souravmondal93** [comment]
@mkhoussid  To bypass "Your connection is not private", you can directly type `thisisunsafe` in the browser window. It should take you to your page. If you want SSL to work on localhost, then you need to trust the generated certificate and run your server with this certificate.
This link can help you: https://www.freecodecamp.org/news/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec/

**Comment by balazsorban44** [comment]
Hi, we now have an `--experimental-https` flag to add https support, please try it out with `next dev --experimental-https`
