### ISSUE TITLE
Route params in getServerSideProps context use query params on Vercel

### ISSUE THREAD

**Issue by andrenarchy** [vercel/next.js#17950]
# Bug report

## Describe the bug

When using `getServerSideProps` in a dynamic route file, e.g. `pages/updates/[article-slug].js`, then the provided `context` should have a property `params` with a property `article-slug` that holds the slug that was used in the request. However, the following URLs lead to a special behaviour when deployed to Vercel (and possibly others):

* `/updates/[article-slug]` -> `params` is the empty object `{}` instead of `{ 'article-slug': '[article-slug]' }`.
* `/updates/[article-slug]?article-slug=test` -> `params` is `{ 'article-slug': 'test' }` instead of `{ 'article-slug': '[article-slug]' }`.

I noticed that these unintended pages get indexed by Google on my site. I can't reproduce this behaviour when running it locally.

## To Reproduce

Use the following in a dynamic route like `pages/updates/[article-slug].js`:
```javascript
export async function getServerSideProps(context) {
  console.log(context.params)
  // ...
}
```
Deploy the site to vercel and request the above URLs.

## Expected behavior

See above.

## System information

- OS: Ubuntu 20.10
- Browser (if applies) Chrome
- Version of Next.js: 9.5.5
- Version of Node.js: 13.12.0

**Comment by ijjk** [comment]
Hi, this has been updated in the latest versions of Next.js `v12.0.10`, please update and give it a try! Example deployment can be seen here https://test-gssp-params.vercel.app/dynamic/first?a

**Comment by andrenarchy** [comment]
This is still not fixed. Check the example deployment: 

https://test-gssp-params.vercel.app/dynamic/[slug]?slug=override results in `"params":{"slug":"override"},"query":{"slug":"override"}` instead of `"params":{"slug":"[slug]"},"query":{"slug":"override"}`.

Please reopen.

**Comment by ijjk** [comment]
@andrenarchy having a different value in `params` vs the `query` for the same field is not supported and this is the expected behavior, the dynamic route param will always take priority.

**Comment by ijjk** [comment]
@andrenarchy the above deployment is not showing that result, it is showing `{"params":{"slug":"[slug]"},"query":{"slug":"[slug]"},"url":"/dynamic/%5Bslug%5D?slug=override"}` which is correct as dynamic route params should always take priority and we ensure dynamic route params are the same in the `query` value as the `params` value so this is the expected behavior.

**Comment by cysp** [comment]
It looks like something different is going on in the specific scenario that the dynamic path parameter's value matches the parameter placeholder (without url encoding):

<img width="797" alt="image" src="https://user-images.githubusercontent.com/742696/152661704-5d81d27e-1347-41b7-b489-bf0ac1f50ccc.png">
<img width="799" alt="image" src="https://user-images.githubusercontent.com/742696/152661724-2a6bc0df-e1f2-42ed-b28c-f05d8cc05dcb.png">

**Comment by andrenarchy** [comment]
@ijjk It seems like github is adding some escaping here. If you replace `%5Bs` with `[` and `%5D` with `]` in the URL you should see the behavior I (and @cysp) are describing.
