### ISSUE TITLE
Allow getServerSideProps to be exported

### ISSUE THREAD

**Issue by mrclay** [vercel/next.js#17960]
# Feature request

## Is your feature request related to a problem? Please describe.

Our app is dual-hosted: In an intranet it shows fresh content from a CMS that editors are working in. However the final product is required to be a static build with the content frozen at build-time.

The final site can't call the CMS, so `getInitialProps` is out. And `getServerSideProps` is--seemingly arbitrarily--banned from export. So we're limping along with `getStaticProps` and `revalidate: 1`. So CMS editors see fresh content on the very next refresh, we have to ignore the props from Next and re-fetch from the client.

## Describe the solution you'd like

`getServerSideProps` could export just like `getStaticProps`, freezing output into JSON files.

**Comment by timneutkens** [comment]
Preview mode exists exactly for this use case: https://nextjs.org/docs/advanced-features/preview-mode
