### ISSUE TITLE
Use a Strapi template for the cms-strapi example

### ISSUE THREAD

**Issue by remidej** [vercel/next.js#18017]
# Feature request

## Is your feature request related to a problem? Please describe.

The process to get started with the Strapi example is quite long and complicated.

## Describe the solution you'd like

Leverage a new Strapi feature: templates ([see their docs](https://strapi.io/documentation/v3.x/concepts/templates.html#templates)).

The steps 1 to 6 in the readme could be replaced by a single command like this:

```bash
yarn create strapi-app my-app-name --template <github-template-url>
```

The template could be a new repository in the Vercel organization. Or you could use Strapi's [official blog template](https://github.com/strapi/strapi-template-blog). Out of the box, it comes with dummy content, the required permissions, and the GraphQL plugin. 

## Describe alternatives you've considered

None

**Comment by ChristopherLMiller** [comment]
yeah i'd agree honestly.  I looked at the strapi example and just quickly gave up.  I don't exactly see what everything is and whats its doing for me and just said meh.  I never knew about the templates though so that could work great honestly.

**Comment by leerob** [comment]
Hey there, the Strapi example in this repo has been migrated to: https://github.com/strapi/foodadvisor/
