### ISSUE TITLE
TypeError: Object(...) is not a function - with useRouter()

### ISSUE THREAD

**Issue by sanders54** [vercel/next.js#18027]
# Bug report

## Describe the bug

I am visiting a dynamic page. The page is a hook. The first line in the hook is  ` const router = useRouter()`. This works 9 out of 10 times, but sometimes it will say `TypeError: Object(...) is not a function` on this line. It happens sometimes when navigating to said page, but sometimes when loading the page fresh without navigating there. 

## To Reproduce
Unable to reproduce in fresh/external project, so I think something I am doing locally is breaking it, I am however unsure what specifically. 

Local code example in project where it sometimes will not work:

/pages/levels/[dynamicPageSlug]/index.js

```
import { useRouter } from 'next/router'
import React from 'react';

export default function DynamicPage() {
  const router = useRouter()   // crashes here sporadically

  const {dynamicPageSlug} = router.query;

  if (!dynamicPageSlug)  { <p> loading </p>}

  return <p>{dynamicPageSlug}</p>
}
```

Is there anything that can happen elsewhere in the application which could invoke such behaviour? Thanks. I am also open to suggestions how to solve this kind of scenario better. 

## Expected behavior
It should not crash, but continue. It should give back the loading paragraph and continue clientside and print the slug. 

## System information

- OS:  macOS
- Version of Next.js: 9.5.5
- Version of Node.js: Node 12

**Comment by jamesmosier** [comment]
Hi @sanders54. Unfortunately this will be pretty tough to track down without any way to reproduce it reliably. This is a pretty common use case for Next and covered by a few dozen unit/integration tests.

If you have a more complete code sample that'd be helpful. Otherwise I'd say just start removing code until it doesn't break. For example remove your custom `_app.js` if you have one, any higher order components, upgrade to the latest React and Next versions, etc.

**Comment by leonardoanalista** [comment]
I accidentally upgraded react to version 17. It worked in my local "npm dev" also "npm build && npm start" but it failed to run at Vercel.

The way I fixed everywhere was to downgrade to version 16:

    "react": "^16.7.0",
    "react-dom": "^16.7.0"

**Comment by smeijer** [comment]
Having the same issue:
 using:

```
os: ubuntu
node: 15.8.0
```

```
react: 17.0.1
react-dom: 17.0.1
next: 10.0.6
```


When clicking the stacktrace link, it boils down to this line:


```js
function Page(_ref2) {
  _s();

  var title = _ref2.title,
      children = _ref2.children,
      noHeader = _ref2.noHeader;
  var router = Object(next_router__WEBPACK_IMPORTED_MODULE_6__["useRouter"])();
  var pathname = router.pathname;
```

**Comment by krizten** [comment]
> Having the same issue:
> 
> ```
> Unhandled Runtime Error
> TypeError: Object(...) is not a function
> ```
> 
> I'm using:
> 
> ```
> os: ubuntu
> node: 15.8.0
> ```
> 
> ```
> react: 17.0.1
> react-dom: 17.0.1
> next: 10.0.6
> ```
> 
> When clicking the stacktrace link, it boils down to this call to `useRouter`:
> 
> ```js
> function Page(_ref2) {
>   _s();
> 
>   var title = _ref2.title,
>       children = _ref2.children;
>   var router = Object(next_router__WEBPACK_IMPORTED_MODULE_6__["useRouter"])();
>   var pathname = router.pathname;
> ```


I had the same issue. All I did to fix it was to upgrade my NextJS dependency from 10.0.7 to 10.0.8 using:

```
npm install next@latest
```

React and React-DOM versions were.
```
react: 17.0.1
react-dom:  17.0.1
```

**Comment by JosiasAurel** [comment]
Just had the same issue here. My solution was to install type definitions for NodeJS.
`yarn add -D @types/node`
I hope it might help

**Comment by Majnuel** [comment]
Same issue here, react 16.8.6 and react-dom 16.8.6
useRouter() is not a function...

**Comment by kevinolivar** [comment]
Same here and I am using NX too,

```
"@types/node": "15.12.2",
"@types/react": "17.0.11",
"@types/react-dom": "17.0.7"
"@nrwl/next": "12.3.6",
"@nrwl/node": "12.3.6",
"@nrwl/react": "12.3.6",
"next": "10.2.3",
"react": "17.0.2",
"react-dom": "17.0.2",
```

**Comment by abdullah-2021-D** [comment]
Same issue here. I want to use a button to navigate dynamically so for that I always use useRouter which has the push property for navigating to a given URL, but now when I import the useRouter and call it inside the component it shows the same error as others mentioned.
here is my code:

import Card from "../ui/Card";
import classes from "./MeetupItem.module.css";
import { useRouter } from "next/router";

function MeetupItem(props) {
  const router = useRouter();  //error here 

  const showDetailsHandler = () => {
    router.push("/" + props.id);
  };
  return (
    <li className={classes.item}>
      <Card>
        <div className={classes.image}>
          <img src={props.image} alt={props.title} />
        </div>
        <div className={classes.content}>
          <h3>{props.title}</h3>
          <address>{props.address}</address>
        </div>
        <div className={classes.actions}>
          <button onClick={showDetailsHandler}>Show Details</button>
        </div>
      </Card>
    </li>
  );
}

export default MeetupItem;

the error that pops up on the localhost is: 

Unhandled Runtime Error

TypeError: Object(...) is not a function
Source

components\meetups\MeetupItem.js (6:26) @ MeetupItem

  4 | 
  5 | function MeetupItem(props) {
> 6 |   const router = useRouter();
    |                          ^
  7 | 
  8 |   const showDetailsHandler = () => {
  9 |     router.push("/" + props.id);

**Comment by abdullah-2021-D** [comment]
> Just had the same issue here. My solution was to install type definitions for NodeJS. `yarn add -D @types/node` I hope it might help

Thank you very much I just used your solution and it worked.
