### ISSUE TITLE
basePath with useFileSystemPublicRoutes:false using rewrites unable to route root page

### ISSUE THREAD

**Issue by IikkaWinter** [vercel/next.js#18049]
# Bug report

## Describe the bug

First of all thank you for the excellent work you are doing with the framework!

Background:
We noticed that `getStaticProps` and `getServerSideProps` tried fetching json data from the root of the domain instead of respecting `assetPrefix` setting which lead us to migrate to `basePath` usage as instructed in other similar bug reports and discussions.

We have a pretty complex routing system and are therefore using `useFileSystemPublicRoutes: false` and relying only on rewrites.

All of the routes seem to work nicely except for the root route (`/`). There is no way to make this work with trailing slash redirect in place:

```
{
  source: '/',
  destination: '/'
}
```

I figured a workaround could be to add the basePath as a route with `basePath: false` flag as per [documentation](https://nextjs.org/docs/api-reference/next.config.js/rewrites#rewrites-with-basepath-support) however that produces the following error: 

> The route /without-basePath rewrites urls outside of the basePath. Please use a destination that starts with `http://` or `https://` https://err.sh/vercel/next.js/invalid-external-rewrite.md

## To Reproduce

Try reaching the root route with the following configuration in `next.config.js`:

```
module.exports = {
  basePath: '/docs',
  useFileSystemPublicRoutes: false,

  async rewrites() {
    return [
      {
        source: '/',
        destination: '/',
      },
    ];
  },
};
```

## Expected behavior

Expecting to have a way to route the basePath root to a page without the need to publish file system routes.

Not urgent: Also expecting to either be able to rewrite urls outside basePath as documented or have that restriction mentioned in the documentation.

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: Tested with 9.5.5. and 9.5.6-canary.5
- Version of Node.js: 12.13.0

**Comment by sirctseb** [comment]
I think you do not need `useFileSystemPublicRoutes: false` for this to occur. I have a minimum reproduction here https://github.com/sirctseb/next-js-base-path-duplication/tree/rewrite-root-18049. I think part of the problem is that the default setting of `trailingSlash` is true, so Next redirects to the base path with no slash, and the rewrite doesn't match. If you set set `trailingSlash: true`, the rewrite works.

**Comment by JanKaifer** [comment]
Thanks `sirctseb` for the the reproduction. I tried it with `next@13` and it works as expected.
