### ISSUE TITLE
trailingSlash redirect removes the urlencoding

### ISSUE THREAD

**Issue by dotomaz** [vercel/next.js#18042]
# Bug report

## Describe the bug

`trailingSlash` redirect url decodes the query string parameter

## To Reproduce

Enter the url:
http://localhost:3000/callback/?state=123%3D%3D

Url is redirected to:
http://localhost:3000/callback?state=123==

## Expected behavior

Url string should keep the url encoded query string values
http://localhost:3000/callback?state=123%3D%3D

## System information

- OS: macOS
- Browser Chrome 86.0.4240.80 (Official Build) (x86_64)
- Version of Next.js: 9.5.5
- Version of Node.js: v12.18.3

**Comment by ijjk** [comment]
Hi, this should have been corrected in https://github.com/vercel/next.js/pull/18149 which is available in the latest version of Next.js `v10.0.3` so I'm going to close this, please upgrade and give it a try!
