### ISSUE TITLE
next/router - push function changes between renders when called

### ISSUE THREAD

**Issue by dan-cooke** [vercel/next.js#18127]
# Bug report
Depending on the `push` function of `useRouter` causes an infinite loop when the `push` function is called from inside a `useEffect`

## To Reproduce

1. Set up a catch-all optional dynamic route `[[...slug]].js`
2. Render the following component from this page
Example component
```
const BugExample = () => {
    useEffect(() => {
        push('/[[...slug]]', '/123/test', { shallow: true })
        console.log('called');
     },[push])

    return null
}
```
You will see an infinite loop of `called` in the console

## Expected behavior
Push should be a non-changing reference, so that the react diff algoirithm knows not to call side effects again uneccesarily

## System information

- OS: macOs
- Browser: Chrome
- Version of Next.js: 9.5
- Version of Node.js: 13.2.0

<sub>[NEXT-1375](https://linear.app/vercel/issue/NEXT-1375/nextrouter-push-function-changes-between-renders-when-called)</sub>

**Comment by jamesmosier** [comment]
Hi @dan-cooke. I don't believe the various `router.*` methods use `useCallback`, therefore between renders `push !== push`. 

Based on [a few of the examples](https://nextjs.org/docs/api-reference/next/router#userouter) from the docs, `router` or `push` are not added as dependencies in the dependency array of `useEffect`.

It seems like a good workaround would be to exclude `push` from the dependency array.

**Comment by dan-cooke** [comment]
Hi @jamesmosier - I would be of the opinion that the various router methods _should_ be using `useCallback`

The React hooks lint rule will complain if you do not include all dependencies in the array - we would prefer to not have to disbale this lint rule.

**Comment by alexhofmandahl** [comment]
I ran into a similar issue in my project. I created a custom hook to handle query parameters using next's router. It relied on a useEffect that had the router in the dependency array. It would be really helpful if the router's methods could use the useCallback hook so my custom hook could properly work.

**Comment by ciampo** [comment]
Same here — it feels like the `push` function could definitely be memoized to avoid this sort of problems

**Comment by dontsave** [comment]
just want to resurface this issue. it would be great for widely consumed callbacks like this to be memoized

**Comment by rpedroni** [comment]
Be careful with this - passed the last 4 hours investigating why my cache stopped working and it was due to the fact that `push` was inside a `useMemo` dependency list. This can lead to some wild unexpected problems down the component tree.

**Comment by stomvi** [comment]
Router dependency warnings are the last things ESLint complains in my codebases.  I agree with the suggestions that `push` should be using `callback`.

**Comment by niksajanjic** [comment]
I don't know the internal workings of `useRouter` methods, but I would propose that this change applies to all methods `router` is exporting, not just `router.push`. If we need to use any of the provided methods in the `useEffect` call, we're currently forced to pass that method to the `ref` to avoid `eslint` warning of missed dependency inside `useEffect`.

**Comment by macrozone** [comment]
just run into the same problem with `useRouter().replace`. I had the impression that this is a memoized function.

Problem is with nextjs 11, the default linting rules will force you to include `replace` to the deps array. Which might result in endless loops.

Its good that nextjs 11 default to these rules, but it should therefore follow conventions to avoid pitfalls like this

**Comment by steida** [comment]
As I see it, Next.js Router has to be split to router commends and route values.

**Comment by andrei-hameza** [comment]
I can suggest another workaround:

```
import Router from 'next/router'

// in component
useEffect(() => {
    if (!loggedIn) {
        Router.push('/login')
    }
}, [loggedIn])
```

`Router` can be used in useEffect only or outside of the React lifecycles. I understand this is not the best solution but I prefer to use it over `eslint-disable-next-line react-hooks/exhaustive-deps`.

Some details:
https://github.com/vercel/next.js/discussions/18522#discussioncomment-836362

**Comment by jordanarldt** [comment]
I ran into this same issue but I seem to have found a simpler solution. Just memoize the router like so:
```tsx
import { useRouter } from "next/router";
import { useMemo, useEffect } from "react";

// ... in component
    const router = useRouter();
    const routerMemo = useMemo(() => router, [router]);

    useEffect(() => {
        if (routerMemo.query.test === "value") {
            // do something here based on the query
            routerMemo.push("/history", undefined, { shallow: true });
        }
    }, [routerMemo]);

```

**Comment by jordanarldt** [comment]
It seems to me like the best workaround for this issue is to simply use `withRouter` instead of the `useRouter` hook. I guess this depends on the use case, but that's what worked better for me.

**Comment by deivoff** [comment]
Hello everyone, are there any plans to fix this behavior?

**Comment by dlwjiang** [comment]
It's been over two years. This seems like an issue that will be encountered by anyone trying to sync state with url query params. so I'm surprised there isn't more activity here... Makes me think I'm doing url state syncing incorrectly or something...

Currently using the fix mentioned above:

```
import Router from 'next/router'
```

**Comment by exneval** [comment]
```
const router = useRouter()
 
useEffect(() => {
  router.push("/");
}, [router])
```

router as hooks dependency (since eslint rules mad about not including it) is not stable to use.

@balazsorban44

**Comment by mkcode** [comment]
Just lost a few hours on this bug. Why has this not been fixed yet? Using next@13.1.1

**Comment by timneutkens** [comment]
This is fixed in the new router that is part of the `app` directory. We've changed the router in `pages` to be a stable reference a few months ago but it broke many existing applications so instead we've focused on making the new router have the right behavior as it'll become the recommended way to build Next.js applications when it's stable.

**Comment by mkcode** [comment]
Thanks for the quick response @timneutkens. I look forward to migrating to the `app` directory when it's stable.

For the record, If the code is already available, I would think an opt-in via an explicit import would be the way to fix this without breaking existing apps. Though it seems that most of us have already solved this via the workaround at this point.

```typescript
import { useRouter } from 'next/router-new-push'
```

**Comment by timneutkens** [comment]
> For the record, If the code is already available, I would think an opt-in via an explicit import would be the way to fix this without breaking existing apps, though I understand that this may not be worth the maintenance effort at this point.

Unfortunately it's not the `useRouter` that is the problem in `pages`. It's the router itself that changes between navigations as the first version was built in 2016 at which point it did not have to consider stable references across navigations, even more so `import Router from 'next/router'` still exists which mutates as well. Hence why App Router doesn't have `router.query` and such, instead it just exposes the minimal amount of apis.

However, since we provide a backwards compat layer for `next/navigation`, I was able to fix this issue by making sure `useRouter` from `next/navigation` is a stable reference across renders. I've opened a PR here: #52177.

Once that lands all you have to do is change to use `import { useRouter } from 'next/navigation'` 👍
