### ISSUE TITLE
Next attempting to serve from invalidated cache ERR_INVALID_ARG_TYPE 

### ISSUE THREAD

**Issue by mousedown** [vercel/next.js#18223]
# Bug report

## Describe the bug

Googlebot's scheduled scans are somehow causing Next to serve from the cache that does not exist anymore causing ERR_INVALID_ARG_TYPE  error on send payload. My error console is littered with errors similar to the below. 

`[GET] /_next/data/3vcGuq3CNcbgBYD-h90CT/deals/SOME-SLUG-URL
01:23:30:61
Status:
-1
Duration:
34.97ms
Memory Used:
172 MB
ID:
2xhjt-1603585410350-4c8f557a12b8
User Agent:
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.140 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
2020-10-25T00:23:30.689Z	8718fb87-1025-4b16-94d9-d022c12720d8	ERROR	Unhandled error during request: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at Function.byteLength (buffer.js:726:11)
    at sendPayload (/var/task/node_modules/next/dist/next-server/server/send-payload.js:1:868)
    at renderReqToHTML (/var/task/.next/serverless/pages/_error.js:6607:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async render (/var/task/.next/serverless/pages/_error.js:6676:22) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

## To Reproduce

This is a production only issue, and I am unable to provide repo to demonstrate. Steps to view the error 

1. View production error logs for my app
2. Note the GET request that caused the unhandled exception 
3. View the output cache folder and see that the requested file does not exist 

## Expected behavior

The correct cache is served, and no unhandled exception is thrown by Next. 

## System information

- Next 9.5.5 

## Additional context

This problem has been around since version 9ish. As this is a production issue, I am unable to provide any more details, or working example. Please work with me to ascertain the cause of this. I am very sorry this is all there is to demonstrate the bug. Please do not add the `please add a complete reproduction` label or similar. I am really at a brick wall with this and unsure how i can possible give you any more information or a way to re-create this reliably. 

![Screenshot 2020-10-25 at 15 27 22](https://user-images.githubusercontent.com/491789/97111454-c642a180-16d6-11eb-90c2-025e099d177d.png)

**Comment by emmekappa** [comment]
having the same issue on next10
