### ISSUE TITLE
_error.js & _app.js: getInitialProps will only be call in _app.js but not in _error.js

### ISSUE THREAD

**Issue by Zauberfisch** [vercel/next.js#18249]
# Bug report

## Describe the bug

If I create both `_app.js` and `_error.js` with each having a `getInitialProps` method, only the `getInitialProps` in `_app.js` will be called, but never the one in `_error.js`  

## To Reproduce

```js
// pages/_app.js
function App({Component, pageProps}) {
	return <Component {...pageProps} />
}
App.getInitialProps = async () => {
	console.log('App.getInitialProps')
	return {}
}
export default App
```
```js
// pages/_error.js
function Error(props) {
	return <div>
		<h1>_error.js</h1>
		<pre>{JSON.stringify({props})}</pre>
	</div>
}
Error.getInitialProps = () => {
	console.log('Error.getInitialProps')
	return {
		thisShouldBePassedToErrorComponent: 'but it is not unless you remove App.getInitialProps'
	}
}
export default Error
```
```js
// pages/index.js
export default function Home() {
	return <h1>index.js</h1>
}
export function getServerSideProps() {
	throw "error in Home.getServerSideProps"
	return {props: {}}
}
```
1. visit `/` to get a 500 error or visit `/non-existing-route` to get a 404 error
1. the console will only show 'App.getInitialProps' but never `Error.getInitialProps`
1. remove `App.getInitialProps` from `_app.js`, now `Error.getInitialProps` will be called

## Expected behavior

`getInitialProps` should be called in both, `_app.js` and `_error.js`

## System information

- Version of Next.js: 9.5.5
- Version of Node.js: v14.12.0

**Comment by timneutkens** [comment]
This is a bug in your code, `_app` getInitialProps implements getInitialProps of pages:

```
App.getInitialProps = async ({Component, ctx}) => {
    let pageProps = {}

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

	return {pageProps}
}
```

**Comment by Zauberfisch** [comment]
Ah, indeed. It's there in the comments of the custom app example to call the parent getInitialProps.

Sorry about that
