### ISSUE TITLE
next/image Styling

### ISSUE THREAD

**Issue by jillmolloy** [vercel/next.js#18312]
I'm working on replacing images in an existing web app with the new Image component, but I've immediately hit a bit of an issue as far as styling is concerned.

For example, I have an image in my app that's being centered with `margin: 0 auto;` being applied to the image. When I swap out the default `<img>` element for `<Image>` it loses that centering. From inspecting I can see the image is now being wrapped in a number of `<div>` elements. So, I then attempted to apply a `className` to the Image, hoping it would get passed to the parent `<div>` so that I could center that, but it seems that this is not being passed to the element.

My current workaround is to now wrap the `<Image>` element in another `<div>` and apply the styles to that, but I feel like this increases the level of effort for upgrading quite a bit across the entire site, between adding new wrappers and new styles.

I was wondering if there was a more straightforward way to achieve this, perhaps it's as simple as allowing the `className` prop for the Image component? Or perhaps there's an even better solution already in place that I've missed entirely – if so, apologies for this pre-emptive issue.

Many thanks for all the work you guys do – big fan!

**Comment by petermanser** [comment]
`className` is allowed for the `Image` component, but that doesn't solve the problem.
