### ISSUE TITLE
Image optimizations for background images

### ISSUE THREAD

**Issue by SogoCZE** [vercel/next.js#18357]
# Feature request

Hello, I would like to use the new feature of automatic images optimization for background images as well.

## Describe the solution you'd like

Export some hook (`useBackgroundImage`) from Next.js where I input image path. The hook would provide me with a path to optimized image and ref (that I could place to the element that will use the background image). Lazy loading could be done with the same technic as in `Image` component over the provided ref.

**Comment by mercteil** [comment]
Yep, just facing the same "issue". Specifically images that are used to cover/contain the background are set via css. Not entirely clear to me how to use `next/image` here.
