### ISSUE TITLE
Image component: ref, complete, loaded event

### ISSUE THREAD

**Issue by endquote** [vercel/next.js#18386]
# Feature request

I'm looking for `ref` and `complete` properties on `next/Image`, as well as a `loaded` event.

## Is your feature request related to a problem? Please describe.

Congrats on launching Next 10! The new image component looks really neat. I was going to port my site to use it, but I'm not sure I can with the current version.

I have some components that watch for the image to be loaded, and then set some CSS to fade the container in. This requires setting a `ref` on `<img>`, accessing a `complete` property, and using the `onLoad` event. Is there a way to implement this with the new `next/Image` component?

```tsx
export const ContentCard = ({ image }:{ image: string }) => {
  const img = useRef<HTMLImageElement>(null!);

  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    if (img.current) {
      setLoaded(img.current.complete);
    }
  }, [img.current]);

  function imageLoaded(e: SyntheticEvent<HTMLImageElement, Event>) {
    if (img.current) {
      setLoaded(img.current.complete);
    }
  }

  return (
    <div className={loaded ? "loaded" : "loading"}>
      <img ref={img} src={image} onLoad={imageLoaded} />
    </div>
  );
};
```

## Describe the solution you'd like

Generally it seems like exposing more of the native `<img>` API in the `next/Image` component would be helpful.

**Comment by vassbence** [comment]
Yes, just replace the img tag with next/image's Image tag. Ref, onLoad etc will be passed down to a regular img tag.

**Comment by endquote** [comment]
I see. What is the proper way to type the ref? I thought the property wasn't there but it looks like I'm just typing it wrong.

![Screen Shot 2020-10-28 at 6 20 44 AM](https://user-images.githubusercontent.com/330010/97441309-d11f5100-18e5-11eb-96a3-716295bd1536.png)
