### ISSUE TITLE
buildManifest 404 causing app failure

### ISSUE THREAD

**Issue by kristojorg** [vercel/next.js#18389]
# Bug report

## Describe the bug

I have a Next.js application which uses `getStaticProps` and `getStaticPaths`. It is running inside a docker container with the `server` target, and I am repeatedly running into a 404 error when trying to fetch the `buildManifest.js` file, which causes all navigation to break. It also causes direct navigation to pages that don't have a cached version yet to hang forever on the fallback page.

## To Reproduce

You can see a hanging fallback page here: https://beta.openebooks.us/app/collection/https%3A%2F%2Fqa-circulation.openebooks.us%2FUSOEI%2Fgroups%2F406

You can see the app working, but navigation not working here (because this path was cached before the problem started): https://beta.openebooks.us/app 

If the buildManifest file is cached in the browser, for example by visiting the working page and then directly navigating to the not-working page, the not-working page will render correctly, though you will now see 404s on other files, like `app.json`, etc in the console. 

The code producing this behavior is here https://github.com/NYPL-Simplified/circulation-patron-web

## Expected behavior

The buildManifest should not 404, and SSG should not hang.

## Screenshots

The `buildManifest` 404:
![image](https://user-images.githubusercontent.com/4398775/97441154-b02c1f80-1928-11eb-99db-bb5a6ee801be.png)

The `app.json` 404:
![image](https://user-images.githubusercontent.com/4398775/97441283-d782ec80-1928-11eb-8600-061c6962d8b9.png)

Other file 404:
![image](https://user-images.githubusercontent.com/4398775/97441342-e9648f80-1928-11eb-9ca4-21ea093e7eb6.png)

## System information

This is running in a docker image built on top of node:12.2.0-alpine with Next.js version ^9.5.3. 

## Additional Context

This doesn't seem to be always happening. The deployment worked totally fine for some time before this began.

**Comment by kristojorg** [comment]
Update: this is not a Next.js issue, but was caused by the load balancer improperly routing traffic to an instance that does not have the necessary file

**Comment by Timer** [comment]
Next.js should still be able to handle this!

**Comment by kristojorg** [comment]
@Timer I did find this documentation on the build-id, which I had not previously seen and am planning to try later today: https://nextjs.org/docs/api-reference/next.config.js/configuring-the-build-id

I will let you know if that solves it

**Comment by steedems** [comment]
Hi! I am having the same (similar) issue.

Not always, but often (specially straight after deploying) the app would load but `buildManifest` would 404 and the navigation would be completely broken. After refreshing a couple (or sometimes several) times, the file would be found and everything would work as expected.

I am trying configuring the build id as suggested and will soon know if it solves the issue 🤞 - @kristojorg did that work for you?

In the meanwhile I am thinking, shouldn't such error be kind of louder or somehow handled?
Is there a good way to find out whether files don't load correctly at render time maybe? 🤔 

Btw I have seen there's been talks about navigation not working in the past and I am now guessing some of those might be related to this. Eg this [old issue](https://github.com/vercel/next.js/issues/5478) maybe 🤔

**Comment by kristojorg** [comment]
@steedems are you running multiple versions of the app behind some kind of load balancer or system like that? That is (I think) the only thing that should cause my issue. I haven't tested the fix yet, but instead got rid of all but one instance. 

Will let you know once I have an opportunity to try it with the deterministic buildId and multiple instances

**Comment by steedems** [comment]
Yes, I have like 2/3 instances behind a load balancer.

I am now using the last commit hash as build id and it _seems_ to have solved the issue 🤞
I have deployed a couple of times already and haven't seen it happening again - it wasn't easy to reproduce so I'll wait for some more deploys before celebrating.

Here's how my `next.config.js` now looks like btw:

```js
const execSync = require("child_process").execSync;

const lastCommitCommand = "git rev-parse HEAD";

module.exports = {
  async generateBuildId() {
    return execSync(lastCommitCommand).toString().trim();
  },
};
```

**Comment by kristojorg** [comment]
I've made a similar change in my `next.config.js` and I believe it will solve my issue. Will reopen this if the issue comes back at some point

**Comment by Timer** [comment]
Please leave this open. We've confirmed it's a bug.

**Comment by kristojorg** [comment]
Sorry about that... I'm not sure what the bug is though? If you've confirmed this is a bug, should I refrain from running the app behind a load balancer in production until this is closed? Even with the deterministic `buildID` setting?

**Comment by chenrui333** [comment]
@Timer 👋  happened to see this issue which caused app failure between deployments, can I get a sense why it did not make to a formal release, but the change is always with the canary releases? Thanks!

**Comment by Lauwed** [comment]
Hey ! Just to know what it the status ? I have the same issue, but it doesn't resolving by itself... Thank youu !

**Comment by MitchEff** [comment]
Yeah that's definitely a bug. We're just using Next with Vercel (no infrastructure on our end), and we're still getting this issue completely randomly.

**Comment by timneutkens** [comment]
Please open a new issue with a reproduction so that it can be investigated.

**Comment by marracheco** [comment]
Any updates on this issue? Was the an issue in prod created for this?

**Comment by St3ve89** [comment]
I'd like to know as well. Experiencing the same issue with the latest version on production.

**Comment by MoSattler** [comment]
We got the same issue.

@timneutkens not sure what the reproduction steps are. It's just a built of a project, and it 404s in production. I couldn't really narrow it down to anything. Any advice on how to properly track down the repro steps?

**Comment by asdillon** [comment]
We have also ran into this issue in a production only build. 
buildmanifest, ssgmanifest, and a chunk all 404. This does not happen in a qa environment with the same code.

<img width="1729" alt="Screen Shot 2021-09-08 at 9 51 47 PM" src="https://user-images.githubusercontent.com/4355245/133092446-e1e4dcbf-2093-4583-91c2-16bf730c45cd.png">

**Comment by MitchEff** [comment]
Unclear if it's helpful or not, but from what I can see I think ours was from CloudFlare - the only affected instance was cached with CF and removing this seemed to fix it

**Comment by dlr1251** [comment]
I am having the same issue here. 
It seems that the BUILD ID is cached somewhere, and when you create a new build, it fails to recognize the new hash id of that new build and instead requests the old one, causing a 404.

**Comment by kristjanmar** [comment]
I'm having the same issue. I just did an aHrefs site audit yesterday and they report 468 pages with "Page has broken JavaScript".

All of these pages are broken because of 404 errors for _buildManifest.js, _middlewareManifest.js, _ssgManifest.js.

I believe this only happens on the first view of a page after a new build. However, I have tons of pages and build fairly often, so this is definitely a problem.

My site is hosted on Vercel.

**Comment by sergioloporto** [comment]
Having the same issue. Site hosted on Ubuntu with Nginx as reverse proxy.
Using `"next": "^11.0.1",`

**Comment by cbfn** [comment]
Having the same issue. Using `"next": "^12.0.8"`

**Comment by timneutkens** [comment]
https://github.com/vercel/next.js/issues/18389#issuecomment-847702435
