### ISSUE TITLE
Image component causes unexpected behavior with Styled-Components

### ISSUE THREAD

**Issue by BjoernRave** [vercel/next.js#18380]
When using the `Image` component together with `styled-components` like this:

```
import Image from 'next/image'
import styled from 'styled-components'

const StyledImage = styled(Image)`
...
`
```
the styles are not applied at the right place, because the image component is rendering a `div` around the img, but applying the styles to the `img` element

**Comment by merodiro** [comment]
I also noticed the same problem when using it with TailwindCSS
