### ISSUE TITLE
Add i18n routing props on getInitialProps context to allow a gradual migration of pages

### ISSUE THREAD

**Issue by aralroca** [vercel/next.js#18396]
# Feature request

## Is your feature request related to a problem? Please describe.

It would be interesting that in the same way that in `getStaticProps` and `getServerSideProps` you can access the **locale** through the **context**, you can also access it from `getInitialProps`. 

Ideally, all data loading methods: `getStaticProps`, `getServerSideProps`, `getInitialProps` should have the i18n in the context.

This would help many projects to adapt the new i18n routing. Although `getInitialProps` is no longer recommended, many projects still use it. In fact for now many libraries that offered HOC the only method they touched is that one.

## Describe the solution you'd like

❌
```js
Page.getInitialProps = async ({ locale }) => { // Right now is not possible to get the "locale" here
  const translations = await import(`../locales/${locale}/translations.json`).then(m => m.default)

  return { translations }
}
```
To work in the same way that:

✅
```js
export function getStaticProps = async ({ locale }) => {
  const translations = await import(`../locales/${locale}/translations.json`).then(m => m.default)

  return { { props: { translations } } }
}
```

or

✅
```js
export function getServerSideProps = async ({ locale }) => {
  const translations = await import(`../locales/${locale}/translations.json`).then(m => m.default)

  return  { { props: { translations } } }
}
```

**Comment by maktouch** [comment]
I would also like to have this in the `getInitialProps` inside of `next/document`

- When modifying Document, we can't use hooks, so we can't use the router hooks there. 
- The ctx.asPath doesn't include the locale (so `/fr/test` shows as `/test`), so we can't even parse it from the locale.

**Comment by santialbo** [comment]
@maktouch I opened an issue (which got moved to a discussion) for that specific case here https://github.com/vercel/next.js/discussions/18329
Do you mind explaining your case to Tim too?
