### ISSUE TITLE
Prefix for default locale

### ISSUE THREAD

**Issue by omgMath** [vercel/next.js#18419]
# Feature request

## Is your feature request related to a problem? Please describe.
Not really. It would just allow the same behaviour we have with our current `i18n` library.

## Describe the solution you'd like
I would like to ask for the feature basically proposed here: https://github.com/vercel/next.js/discussions/17078#discussioncomment-110829 by @Vadorequest, which is a prefix for the default locale.

**Example:**
We have our site available in two languages, `en` and `de`, with `en` being the `defaultLocale`. Assume there is page `home`. Currently, this page would be available under `/home` and `/de/home`. It would be nice to have a configuration option so that the page would be available under `/en/home` and `/de/home`, respectively.

## Describe alternatives you've considered
Use redirects?

**Comment by mathieumagalhaes** [comment]
Ideal, this should be configurable with a boolean.
If not could we have an example on how to solve this use-case?
With redirects I'm running into ERR_TOO_MANY_REDIRECTS
