### ISSUE TITLE
Allow a wildcard for images.domains in next.config.js / ability to disable Next/Image hostname check

### ISSUE THREAD

**Issue by petertenhoor** [vercel/next.js#18429]
# Feature request

A. The ability to use a wildcard or regular expression in the images.domains array within the next.config.js.
B. The ability to disable the hostname check when using Next/Image.

## Is your feature request related to a problem? Please describe.

I'm trying to implement Next/Image in my current project with externally hosted images. My images are hosted on an external server which regularly changes hostnames to a random subdomain (e.g. s1-abc-def.domain.com). This makes it nearly impossible for me to use Next/Image with the current way hostnames are validated.

## Describe the solution you'd like

A. It looks like the Next/Image component uses `Array.includes` to match the hostname of an image with the configured domains array in the next.config.js. It would be great if the ability to use a wildcard (e.g. *.domain.com) or regex could be added.
B. A new parameter in the next.config.js which allows you to disable the domains check for images.

## Describe alternatives you've considered

- Not using Next/Image.
- Set up an extra image proxy and whitelist that as a domain.

## Additional context

N/A

**Comment by klaaz0r** [comment]
I like the idea but I red in the PR the worries about Ddosing which of course is a real issue if you allow any domain.

**Comment by M1ck0** [comment]
> To enable Image Optimization for images hosted on an external website, use an absolute URL for the Image src and specify which domains are allowed to be optimized. This is needed to ensure that external URLs can't be abused.

This is from docs. I do like the reason behind this because it can easily be abused in many ways which would not benefit anyone, especially to the NextJS team.
