### ISSUE TITLE
Importing CSS from Third Party React Components In React Component doesn't work

### ISSUE THREAD

**Issue by okeybond** [vercel/next.js#18421]
<img width="860" alt="Applied this to a react component" src="https://user-images.githubusercontent.com/48156152/97496627-20ef2e00-1961-11eb-8343-4055791c6ebc.png">

Applied CSS imports to react components as part of the NextJS 10 upgrade, removing it from _app.js but the styling did not work.

**Comment by jamesmosier** [comment]
Hi @okeybond. Please add a complete reproduction with a repository in order for this to be investigated.

**Comment by lordvcs** [comment]
https://codesandbox.io/s/nice-mendeleev-oeuw7?file=/pages/index.js shows an example

**Comment by ijjk** [comment]
Hi, the above mentioned codesandbox is importing global CSS outside of `_app` which isn't allowed so this doesn't appear to be a bug in Next.js. 

See more information in the documentation here https://nextjs.org/docs/basic-features/built-in-css-support#adding-a-global-stylesheet
