### ISSUE TITLE
Image component sized by multiplier

### ISSUE THREAD

**Issue by lifeiscontent** [vercel/next.js#18432]
# Bug report

Images I use on my site I follow this practices to have crisp images at different DPIs.

```html
<img
  alt="Design of checkout form"
  height="846"
  src="/images/checkout-form/1x.png"
  srcset="/images/checkout-form/2x.png 2x, /images/checkout-form/3x.png 3x"
  width="270"
  class="jsx-1397468523">
```

from the looks of it, theres no way to define a srcSet with 1x + 2x with the new image component.

is there a way to do this? Its not clear in the docs.

I'm not sure if you'd be interested in creating a different component with more flexibility but if you implemented the picture element you'd allow user to specify all the sources they would need.

e.g.

```html
<picture>
    <source srcset="/media/cc0-images/surfer-240-200.jpg"
            media="(min-width: 800px)">
    <img src="/media/cc0-images/painted-hand-298-332.jpg" alt="" />
</picture>
```

I could see the same markup in Next.js as follows:

```jsx
function MyComponent () {
  return (
    <Picture>
       <Source width="240" height="200" media="(min-width: 800px)" />
       <Img src="/media/cc0-images/painted-hand-298-332.jpg" />
     </Picture>
  );
}
```

where:

**Img** would be the component to specify the source image
**Source** would be the component to specify alternatives
**Picture** to be the wrapper to share logic between Source + Img

**Comment by M1ck0** [comment]
You have more info about the image component [here](https://nextjs.org/docs/basic-features/image-optimization) and you can see all props [here](https://nextjs.org/docs/api-reference/next/image)

`<Image/>` will create different sizes of a provided image and use the one that fits best based on screen size. 

It will use this default configuration
```javascript
module.exports = {
  images: {
    deviceSizes: [320, 420, 768, 1024, 1200],
    iconSizes: [],
    domains: [],
    path: '/_next/image',
    loader: 'default',
  },
}
```
> You can specify a list of device width breakpoints using the deviceSizes property. Since images maintain their aspect ratio using the width and height attributes of the source image, there is no need to specify height in next.config.js – only the width. These values will be used by the browser to determine which size image should load.

You can also use `sizes` props to help it determine which image should load on which screen. More about that [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes)

If this does not answer your question could you elaborate more so I or another member can help you with your issue :)
