### ISSUE TITLE
Sentry is not logging errors on the client side

### ISSUE THREAD

**Issue by BramDecuypere** [vercel/next.js#18478]
# Bug report

## Describe the bug

The bug is described as if it was only the example: `with-sentry`, but it's happening on our production website as well.

I've trying to get the with-sentry example to work in my usecase.
The only thing I'm changing in this example is the `env.local` file:

```
NEXT_PUBLIC_SENTRY_DSN=https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx@xxxxxxxx.ingest.sentry.io/xxxxxxxxx
```

and the _app.tsx file in order to have it come up under a certain environment:

```
if (process.env.NEXT_PUBLIC_SENTRY_DSN) {
  const config = getConfig();
  const distDir = `${config.serverRuntimeConfig.rootDir}/.next`;
  Sentry.init({
    enabled: true,
    environment: "staging",
    beforeSend: function (event) {
      console.log("event", event);
      return event;
    },
    integrations: [
      new RewriteFrames({
        iteratee: (frame) => {
          frame.filename = frame.filename.replace(distDir, "app:///_next");
          return frame;
        },
      }),
    ],
    dsn: process.env.NEXT_PUBLIC_SENTRY_DSN,
  });
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Download the `with-sentry` example and install it
2. Add a Sentry.captureMessage('Test message') somewhere in one of the client files
3. Change the env.local file to have a valid DSN value
4. See nothing showing up in the Sentry dashboard from the example
5. Click on one of the links of the server examples, and validate that your installation is actually working
6. Be really dissapointed.

## Expected behavior

Work both server and client side

Question: Did something change in the way webpack is handling these files? Is the alias towards "@sentry/node" still working?

## System information

- OS: macOS
- Version of Next.js: 10.0.0 & 9.5.2
- Version of Node.js: 13.14.0

>

**Comment by BramDecuypere** [comment]
Just checked and the same configuration works perfectly when using just `create-react-app`. My feeling is there is something not being initiated on the frontend that happens on the backend. 
Problem being that it show a Sentry not found error, I guess? Instead it just doesn't work.

**Comment by BramDecuypere** [comment]
Obviously if you are checking on localhost. Make sure no one has set the settings to have excluded localhost :)

**Comment by chla** [comment]
same issue

**Comment by felipefialho** [comment]
Yes, we still with same issue... I spent the last few days analyzing it, but I still couldn't find a solution.

**Comment by WillTheVideoMan** [comment]
I experienced this issue too, and spent a good few hours scratching my head before uncovering the problem.

It turned out that my privacy-respecting browser was blocking the client-side Sentry requests. 

Try checking for `net::ERROR_BLOCKED_BY_CLIENT` in the browser console alongside any `POST` requests to Sentry. If you use Brave or Firefox with aggressive settings, it might be time to tame your config. For me, client-side logging worked perfectly only after disabling all blockers / shields for the domain.

**Comment by felipefialho** [comment]
Hi, some updates about it.

I've tried use [the Vercel tutorial to add Sentry](https://github.com/vercel/next.js/tree/canary/examples/with-sentry) during some weeks but without success.

So I changed the approach for just use the [React implementation with Sentry](https://docs.sentry.io/platforms/javascript/guides/react/), that doesn't work with Server Side but fixes my problem about Client Side.

As in this project we don't have things resolved using the Server Side this approach has worked for me.

**Comment by geosigno** [comment]
any update on this issue?

**Comment by rikr2sanchez** [comment]
same issue here, there is any update on this ?

**Comment by PossibleAtom** [comment]
I had a similar issue to this, everything functioned correctly with the production build locally, with both client and server-side errors being logged in sentry, however once deployed, only server-side errors were being logged. 

The fix, for my scenario, was to ensure that the correct environment variables were available at build time, before deployment. This includes passing the NEXT_PUBLIC_SENTRY_DSN environment variable along with the other sentry environment variables into the build step of the pipeline (in our case, using docker). Once this was supplied, the errors were logged in sentry from both server and client-side when deployed (staging and production).

This meant that Sentry was able to initialise on the browser (as NEXT_PUBLIC_* variables must be configured in build time or else they do not work on the front-end) and then log. It might not be the solution to your case but could be worth double-checking.
