### ISSUE TITLE
next/image resize not working as expected

### ISSUE THREAD

**Issue by segersniels** [vercel/next.js#18489]
# Bug report

## Describe the bug

First of all thanks for all the efforts building up to the 10.0.0 release! 💪 

I've been experimenting with the `next/image` `<Image />` component to do some auto optimisations for the images on my blog. Unfortunately I quickly ran into some resizing issues. When I resize my viewport to be smaller than the image I would expect the image to resize automatically to a smaller variation but it doesn't.

## To Reproduce

Unsure how to reproduce since it might be user error. I'm experimenting with some basic examples like:

```js
<Image src="/avatar.png" alt="avatar" height={500} width={500} />
```

## Expected behavior

I would expect the image to automatically resize to fit the viewport.

## Screenshots

See a rather extreme example below.

![Screenshot 2020-10-29 at 16 37 57](https://user-images.githubusercontent.com/10974647/97596601-2e5df400-1a05-11eb-8fb1-47560e719046.png)
![Screenshot 2020-10-29 at 16 38 09](https://user-images.githubusercontent.com/10974647/97596610-2f8f2100-1a05-11eb-8b62-df396d308835.png)

## System information

- OS: macOS
- Browser (if applies): chrome
- Version of Next.js: 10.0.0
- Version of Node.js: 14.5.0

**Comment by haydencleary** [comment]
I came across this too, but I wrote it off as an optimisation. If you resize from larger to smaller no additional requests are made and the image should be resized with css. If you resize from smaller to larger however requests are made to get the correct image. At least that was the behaviour I noticed, might want to double check.

**Comment by segersniels** [comment]
> I came across this too, but I wrote it off as an optimisation. If you resize from larger to smaller no additional requests are made and the image should be resized with css. If you resize from smaller to larger however requests are made to get the correct image. At least that was the behaviour I noticed, might want to double check.

If that's the case I would adjust the docs to not state:
> width and height are automatically responsive, unlike the HTML <img> element

Which kind of indicates that it would resize to fit the viewport

**Comment by haydencleary** [comment]
Yes, I agree the docs are a bit vague. Could probably do with some more details + varied examples.

**Comment by Timer** [comment]
We're currently working on adding a `layout="responsive"` prop you can pass to NextImage! We'll have it on canary for you to try soon!

**Comment by g-elwell** [comment]
@Timer I posted a suggestion yesterday which would fix this issue, it got moved to discussions. Is there any reason why you'd need to specify a responsive prop rather than this CSS change?
https://github.com/vercel/next.js/discussions/18462
Thanks!

**Comment by Timer** [comment]
Could you please try out `next@canary`?

**Comment by segersniels** [comment]
@Timer That seems to work as expected. Thanks for the quick response!

**Comment by Timer** [comment]
Great! You'll need to enforce a minimum width for the `responsive` mode. I'll close this as solved!

**Comment by madleo-dk** [comment]
@Timer Can't seem to "enforce" a min width for the responsive mode to work. I referenced the example in docs but unable to make the image appear. The other layout types I tested works as expected (fill, intrinsic) ( https://github.com/vercel/next.js/blob/canary/examples/image-component/pages/layout-responsive.js

` <Img
      quality={100}
      src={comment.imageUrl}
      layout="responsive"
      width={300}
      height={300}
      minWidth={300}
  />
`

Also tried,

` <Img
      quality={100}
      src={comment.imageUrl}
      layout="responsive"
      width={300}
      height={300}
      minWidth={300}
  />
`

as well as,

// stylesheet.module.scss
.image {
    min-width: 30rem !important;
}
  

` <Img
      className={styles.image}
      quality={100}
      src={comment.imageUrl}
      layout="responsive"
      width={300}
      height={300}
  />
`

**Comment by chgara** [comment]
I have the same problem as you. When I set layout="responsive" and width={500} height={500} the image dissapears
![image](https://user-images.githubusercontent.com/57034271/103408687-d1490080-4b63-11eb-82d1-3318ea832642.png)
![image](https://user-images.githubusercontent.com/57034271/103408700-e2920d00-4b63-11eb-9fbb-7d23cccb4465.png)

**Comment by pedroview** [comment]
any way to make height 100% in responsive

**Comment by hpachy** [comment]
looking for the same thing make the img responsive by the height of it

**Comment by racer161** [comment]
The [documentation](https://nextjs.org/docs/api-reference/next/image) still doesn't explain how to solve the disappearing layout="responsive" issue. The provided [example ](https://github.com/vercel/next.js/blob/canary/examples/image-component/pages/layout-responsive.js) doesn't have any reference to minWidth and just seems to magically work. However, when I copy the exact format in a project setup with create-next-app, my images still disappear in Chrome 89.0.4389.82 and Firefox 86.0.1. 

Any guidance would be greatly appreciated and should probably be added to the documentation.

**Comment by AlexandraKlein** [comment]
@racer161 is the image still hidden if you set `position: relative` on its parent container?

**Comment by KugelbergDK** [comment]
Having the same issue...

**Comment by abotsi** [comment]
Hi there,
For people having problem of image disappearing with `layout="responsive"` (like @chgara, @BrunoQuaresma, @KugelbergDK...), look at the parent element of your <Image />. 
It won't work if it have style rule `display=flex`.
Hope it helps

**Comment by gabeodame** [comment]
Fix this issue by adding a class selector to the image container and set min-width to 100%

**jsx**
`<div className={classes[''some-class']}><Image src='some-link' alt='' width={640} height={426} layout='responsive' /><div>`

**css**
`.some-class{
min-width: 100%
}`

that should fix it

**Comment by andy3520** [comment]
> Hi there,
> For people having problem of image disappearing with layout="responsive" (like @chgara, @BrunoQuaresma, @KugelbergDK...), look at the parent element of your .
> It won't work if it have style rule display=flex.
> Hope it helps

Same things, and `display: grid` too.

**Comment by markobozic346** [comment]
Hi, I had the same problem and I manage to solve it by defining the max-width of the container, thats look like this:

const NextImage = ({ src, alt, maxWidth = '100%', ...props }: any) => {
    return (
        <Box w="100%" maxWidth={maxWidth} height="auto">
            <Box position="relative" width="100%" height="auto" {...props}>
                <Image src={src} layout="responsive" alt={alt} objectFit="contain" />
            </Box>
        </Box>
    )
}
