### ISSUE TITLE
Proposal: NextImage should automatically determine width/height for local images

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#18497]
# Feature request

It'd be really cool if NextImage automatically configured `width` and `height` for local images, as well as automatically hashing the image.

## Describe the solution you'd like

```tsx
import Logo from "../logo.png";
import Image from "next/image";

// Logo = { src: '<basePath>/_next/media/logo-<hash>.png', width: 200, height: 150 }
<Image src={Logo} alt="Vercel" />
```

## Describe alternatives you've considered

N/A

## Additional context

Currently, you have to manually set the width and height for a local image. Plus, the image paths aren't statically verified like an import would be.

**Comment by neilpalima** [comment]
This is a reason why I cannot use next/image since I need to provide the width and height. It will be great if it can be used with using css width and height (ex. value of 100%) or something similar.

**Comment by agcty** [comment]
> This is a reason why I cannot use next/image since I need to provide the width and height. It will be great if it can be used with using css width and height (ex. value of 100%) or something similar.

You actually can with the "unsized" property

**Comment by neilpalima** [comment]
@agcty I tried that but got a not good result.

**Comment by agcty** [comment]
@Timer One thing that might be possible is probing for the image dimensions of the remote or local resource without downloading it. I read something about this several weeks ago and it seems a perfect use case for this. If no width and height are set and unsized is not set as well, the image component could probe the dimensions and populate width and height automatically.

I can dimly remember that HTTP3 will make this really easy but not entirely sure. For reference there's a library that does something similar: https://github.com/nodeca/probe-image-size/

**Comment by agcty** [comment]
> @agcty I tried that but got a not good result.

What did you try and what was the result?

**Comment by Timer** [comment]
@neilpalima we're landing a change to `<NextImage />` right now that'll allow you to specify various `layout`s for your image! See https://github.com/vercel/next.js/pull/18491

**Comment by Nicoowr** [comment]
@Timer I don't understand how #18491 is solving the issue tackled by the proposal? 😅

**Comment by gregkonush** [comment]
it would nice infer `width` size if the `height` prop was passed and the opposite way as well

**Comment by leerob** [comment]
One idea: we can read the `width` and `height` with the Node package `image-size`. I used this package to [automate adding widths and heights to my images](https://github.com/leerob/leerob.io/blob/master/scripts/markdown-to-next-image.js).

Maybe it's possible to use this at build time, assuming it doesn't negatively affect build time with lots of images.

**Comment by moaaz-bhnas** [comment]
> Or as a temporary solution, could I use a custom wrapper which reads the dimensions of my image, calculates the missing dimension and injects it to <Image /> ?

@Nicoowr won't a custom wrapper require loading the image to get its aspect ratio and do the calculation?

**Comment by modbender** [comment]
I was checking to open a issue and found this.
What I want is, supposedly I give only width, I want the height to of it to be calculated automatically according to the original image width and height and vice versa. Basically I don't want to lose aspect ratio of the image. I hope this is also a feature.

**Comment by joaogarin** [comment]
Same here, it would be nice that the next image works as a normal `img` tag so that you can specify for example a height and by setting width auto or not set have it use the normal image ratio (like an `img` tag does). For now in such cases it is not possible to really use the image component =/ as seems that when you don't set either height or width you have to use layout fill which is a different use case. I do understand the potential for layout shift but we do have code that is used for different images (e.g. a logo) that we know shouldn't have more than a certain height but have the width calculated dynamically (so that it works for different logos ratios)

**Comment by 7ruth** [comment]
Was struggling with keeping aspects ratios of my images, this is what I ended up using:

```
<div
  style={{
        height: '250px,
> 
  <div
      style={{
        position: 'relative',
        maxWidth: '100%',
        height: '100%'
      }}
    >
      <Image
        src={'./images/001'}
        alt={'picture of a sunrise'}
        layout="fill"
        objectFit="contain"
        quality={100}
      />
  </div>
</div>
```

**Comment by advantiot** [comment]
@7ruth Your solution is a terrific workaround. Except, I needed to add a `width: '100%'` as well to the outermost div otherwise the image would not show. Am I missing something?

**Comment by awareness481** [comment]
Could this issue be closed so there's no confusion? For anyone reading this, this feature has been added in Next 11 https://nextjs.org/blog/next-11#automatic-size-detection-local-images

cc: @leerob

**Comment by Nicoowr** [comment]
@awareness481 As far as I know, the feature released in Next 11 does not work if we only specify `height` or `width` ?
