### ISSUE TITLE
Next.js + Wordpress Example fails to build

### ISSUE THREAD

**Issue by Ihatetomatoes** [vercel/next.js#18525]
# Bug report

## Describe the bug

I am getting an error when I try to build and export the [Next.js + Wordpress example](https://github.com/vercel/next.js/tree/canary/examples/cms-wordpress).

`TypeError: Cannot read property 'edges' of undefined`
`TypeError: Cannot read property 'node' of null`
`FetchError: invalid json response body at https://staging.ihatetomatoes.net/graphql/ reason: Unexpected end of JSON input`

<img width="330" alt="next-wp-error" src="https://user-images.githubusercontent.com/735672/97675385-5459c600-1ae3-11eb-862c-c4ae09e988a9.png">

Is this something related to my WordPress installation or does this happen with other WP sites?

FYI the **dev mode works fine** and shows the site locally without any issues, **but the build fails**.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow the **How to use** guide of the [CMS WordPress example](https://github.com/vercel/next.js/tree/canary/examples/cms-wordpress#how-to-use)
2. You don't need to setup the preview part.
3. Create `.env.local` in the root of the project.
4. Set WP URL to my staging site `WORDPRESS_API_URL=https://staging.ihatetomatoes.net/graphql/`
5. Update `package.json` build script to `"build": "next build && next export"`
6. In terminal run `yarn build` or `npm run build`

## Expected behavior

I would expect a successful build and the `out` folder to have all files.

## Screenshots

<img width="337" alt="next-wp-error-2" src="https://user-images.githubusercontent.com/735672/97676504-deeef500-1ae4-11eb-87a8-ac3d56f5252d.png">

## System information

- OS: macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: latest
- Version of Node.js: v14.13.0

**Comment by cordmitchell** [comment]
I have the same issue. I get the errors on different pages each time I build. Sometimes they build sometimes they don't. Works fine in dev.

**Comment by lfades** [comment]
I'm not sure if this is an issue with the example or with the API failing. I'll try to debug it this week 🤔

**Comment by mikecabana** [comment]
Has anyone got this working? Running into the same issue.

**Comment by Pasqat** [comment]
Same here. It works fine in dev with wordpress on localhost and hosted but if I try to build it fails for the [slug].js pages

**Comment by Hamza-Liaqat1** [comment]
Getting same issue here

**Comment by gac3k** [comment]
@Hamza-Liaqat1 @Pasqat @mikecabana @cordmitchell @Ihatetomatoes I know that I am late to the party, but for anybody having similar issues, this is 99% related to php `memory_limit` configuration value being to low... I had it set to 64M by accident, then after increasing all the issues have been resolved.

So for anybody else having that issue in the future, that might due to the trick :)

**Comment by mattlovell** [comment]
I had this issue with the Next + Wordpress example, fixed it by putting the 'More Posts' block back in side the         {router.isFallback ? ( )}  check.

**Comment by leerob** [comment]
I was not able to reproduce, was able to clone and deploy https://github.com/vercel/next.js/tree/canary/examples/cms-wordpress successfully. Ensure you have the correct environment variables set up to connect to your headless WordPress instance 🙏
