### ISSUE TITLE
Layout fill in nextjs 10.0.1-canary-6 doesn't respect any height, width, maxwidth, maxheight styles

### ISSUE THREAD

**Issue by agcty** [vercel/next.js#18739]
I'm using nextjs 10.0.1-canary-6 with the new fill layout that replaces the unsized prop and i just want to set a maximum height and width for my image but it just isn't possible:

```javascript
import React from "react";
import Image from "next/image";

function test() {
  return (
    <div
      style={{
        width: "200px",
        height: "200px",
        maxHeight: "200px",
        maxWidth: "200px",
      }}
    >
      <Image
        src={"renders/KMxNJT7MKtCGg7QkpKCL/KMxNJT7MKtCGg7QkpKCL.png"}
        layout="fill"
        style={{
          width: "200px",
          height: "200px",
          maxHeight: "200px",
          maxWidth: "200px",
        }}
      />
    </div>
  );
}

export default test;
```

The image component doesn't respect ANY styling that restricts dimensions.

![image](https://user-images.githubusercontent.com/12101091/97984948-caa64300-1dd7-11eb-88ce-31a5f25028d2.png)

It's literally as big as the whole page!

**Comment by Timer** [comment]
You have to configure position relative for the parent:

```tsx
<div
      style={{
        position: "relative",
        width: "200px",
        height: "200px",
        maxHeight: "200px",
        maxWidth: "200px",
      }}
    >
```

**Comment by agcty** [comment]
Adding position relative does work but in this case it seems that you need width and height attributes.

![image](https://user-images.githubusercontent.com/12101091/97988673-a2b9de00-1ddd-11eb-801f-a3ea95bfc31e.png)

For example if I remove width and height attributes and just leave maxWidth and maxHeight: 

```javascript
function test() {
  return (
    <div
      style={{
        position: "relative",
        maxHeight: "200px",
        maxWidth: "200px",
      }}
    >
      <Image
        src="renders/KMxNJT7MKtCGg7QkpKCL/KMxNJT7MKtCGg7QkpKCL.png"
        layout="fill"
      />
    </div>
  );
}
```

I would expect the image to "fill" the available space. But instead, the image is 0x0 big: 


![image](https://user-images.githubusercontent.com/12101091/97989464-dcd7af80-1dde-11eb-960f-9b22cc3c44c2.png)

Even if i explicitly set width and height to 100% the result stays the same:

```javascript
<div
        style={{
          position: "relative",
          maxHeight: "200px",
          maxWidth: "200px",
        }}
      >
        <Image
          src="renders/KMxNJT7MKtCGg7QkpKCL/KMxNJT7MKtCGg7QkpKCL.png"
          layout="fill"
          style={{ width: "100%", height: "100%" }}
        />
      </div>
```

But if I use the normal img tag, everything behaves as expected:

``` javascript
function test() {
  return (
    <div
      style={{
        position: "relative",
        maxHeight: "200px",
        maxWidth: "200px",
      }}
    >
      <img
        style={{ width: "100%", height: "100%" }}
        src="https://images.unsplash.com/photo-1604321951949-e9d5710716db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3578&q=80"
      />
    </div>
  );
}
```

![image](https://user-images.githubusercontent.com/12101091/97989747-40fa7380-1ddf-11eb-8dc3-e6f4aa762b63.png)


Will make a codepen

**Comment by agcty** [comment]
Ok so codesandbox seems to have problems installing the next.js canary and actually rendering anything but I managed to deploy it to vercel:

https://csb-i3hk3-8a8ckr8o5.vercel.app/

And here's the sandbox: https://codesandbox.io/s/quizzical-shannon-i3hk3?file=/pages/index.js

**Comment by Timer** [comment]
What are you trying to get the image to do?

**Comment by agcty** [comment]
I just want the image to not exceed certain dimensions. Basically I want an image container that the image is not allowed to exceed, I also don't want to set the width and height on the image itself because I don't know the exact dimensions ahead of time, hence I need to use layout="fill".

So just what the canary 6 docs describe (https://github.com/vercel/next.js/blob/canary/docs/api-reference/next/image.md)

> If fill, the image will stretch both width and height to the dimensions of the parent element.

**Comment by Timer** [comment]
Have you tried using `layout="responsive"` then instead?

**Comment by agcty** [comment]
yes but responsive requires you to set width and height which I don't want to set because I don't know what the aspect ratio is going to be
