### ISSUE TITLE
Error: Package exports for '<path>\node_modules\next\node_modules\postcss' do not define a valid '.' target

### ISSUE THREAD

**Issue by teamforward-in** [vercel/next.js#18828]
# Bug report

## Describe the bug

After install the new version 10.0.1. I am receiving the following error in the very basic boiler plate version of the Next JS
**Error: Package exports for '<path>\node_modules\next\node_modules\postcss' do not define a valid '.' target**

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

I just followed the basic instructions provided in the Docs.
Please note, It worked and working for the 9.5.3 version for NextJS with no issues.

## Screenshots

![image](https://user-images.githubusercontent.com/72451264/98213903-c3b03980-1f6b-11eb-99eb-c34092555a79.png)

## System information

- OS: Windows 10
- Browser (if applies) : N/A
- Version of Next.js: [10.0.1]
- Version of Node.js: [13.1.0]

**Comment by timneutkens** [comment]
> I just followed the basic instructions provided in the Docs.

This is not enough for us to reproduce the issue. Can you provide a github repo?

**Comment by teamforward-in** [comment]
Found the Issue. I had the Node JS version 15.x.x installed. After down graded to the LTS latest version 14.x.x. It worked.
Thanks for the quick response.

**Comment by jorgenbs** [comment]
I had the same issue, solved by upgrading node from 13.1 to 13.7

**Comment by Mpilo-Pillz** [comment]
I had the exact same issue, it seems that node version 13.1 has an issue. I downgraded to node version 12.1 matching my current config on my local machine where it works. Thank you @jorgenbs for the solution to change my node version. Much and highly appreciated.
