### ISSUE TITLE
TypeError: require.resolveWeak is not a function

### ISSUE THREAD

**Issue by Emiliano-Bucci** [vercel/next.js#18855]
Hi! I've recently (with the latest version of next js) start to face issues during the test (i use `jest` and `ts-jest`) of dynamic components. I start to get `TypeError: require.resolveWeak is not a function`. I've also tried to downgrade to version 8 of next but i'm still facing the issue, so i guess i'm doing something wrong (maybe inside the jest.config.js?). Here's a repo example -> https://github.com/Emiliano-Bucci/nextjs-starter

Thanks :)

**Comment by hellno** [comment]
same here :) any suggestions how to fix this for 10.0.3?

**Comment by sandcastle** [comment]
We are also seeing this issue with `v10` using `babel-jest`.

**Comment by Emiliano-Bucci** [comment]
None? :/
