### ISSUE TITLE
Source of runtime error not showing in Safari

### ISSUE THREAD

**Issue by iiKulakov** [vercel/next.js#19036]
# Bug report

## Describe the bug

Source of runtime error in Safari is blank. Tried multiple Safari versions: 13.1.2, 14.0, mobile Safari.
Bug appear since version 9 of Next.js.
Note: Looks like problem with modal window, because when error displays in separate page it's working normal  

## To Reproduce

Open page with error in Safari and Chrome.

## Expected behavior

Error source should be visible in Safari as it visible in Chrome

## Screenshots

Safari
<img width="962" alt="Screenshot 2020-11-10 at 6 37 42 PM" src="https://user-images.githubusercontent.com/22544922/98747279-36af1b00-2385-11eb-8a1c-b9f2944eb53d.png">

Chrome
<img width="959" alt="Screenshot 2020-11-10 at 6 27 14 PM" src="https://user-images.githubusercontent.com/22544922/98747321-49295480-2385-11eb-82a4-ae5b8378e616.png">

## System information

- OS: macOS
- Browser: Safari 13-14
- Version of Next.js: all versions from 9+
- Version of Node.js: 12.12.0

**Comment by lachlanjc** [comment]
Wow, huge +1. I only use Safari (only option on iPad) & I had no idea Next was capable of showing errors like that outside specific issues in next/image etc. It would be so amazing to have actual errors reported 🙌

**Comment by vitalybaev** [comment]
It's caused because Safari's `stack` property of Error doesn't provide file and line/column information. As a result - we won't be able to show source code at the certain line.

I'll try to investigate opportunities to obtain that info in Safari. At the moment I only know that we can get line number (without column number)

**Comment by anupamamnair** [comment]
Hi @ijjk , I am new to Open source and would like to look into this issue.

**Comment by petercrackthecode** [comment]
Hi @Timer & @timneutkens, can I start working on this issue?

**Comment by gricn** [comment]
> Was not able to reproduce. Can see Error source in `safari 16.0` Using: `create-next-app@12.3.2-canary.32` Newer versions of safari seem to support stack property and hence are able to render the error source **Safari** <img alt="Screenshot 2022-10-20 at 10 26 44 AM" width="1582" src="https://user-images.githubusercontent.com/11258286/196860058-7e292c5b-dcdd-4f4e-94f7-a03b04b0b196.png">
> 
> **Chrome** <img alt="Screenshot 2022-10-20 at 10 29 16 AM" width="1582" src="https://user-images.githubusercontent.com/11258286/196860203-d69ea963-d43b-4903-9baf-b3419dfedc53.png">

@timneutkens  I have also tested in Next.js 13.2.4 and Safari 16.3, Safari could show the error source now. Should we close this issue?

**Comment by timneutkens** [comment]
Sounds good 👍 thanks for checking!
