### ISSUE TITLE
Optimize images during `next build`

### ISSUE THREAD

**Issue by elitan** [vercel/next.js#19065]
# Feature request

## Is your feature request related to a problem? Please describe.

Right now a node server is needed to serve optimized images that can be used with the [Image component](https://nextjs.org/docs/api-reference/next/image).

It would be nice if images also could be optimized at build time and deployed to a static hosting service (any CDN).

## Describe the solution you'd like

Images being optimized during `next export`, perhaps with a flag indicating that images should be optimized during build time. 

## Describe alternatives you've considered

Manually optimize images. Tedious work :(

## Additional context

Users talking a bit around the issue here: https://github.com/vercel/next.js/issues/18356

I made a similar comment here: https://github.com/vercel/next.js/issues/18356#issuecomment-724540795

**Comment by AlexThomas90210** [comment]
I actually expected this functionality when I tried out next/image. Then when it didn't work I couldn't find anything about it in the docs
