### ISSUE TITLE
Image Component with Contentful Throws 400 Errors in Production

### ISSUE THREAD

**Issue by AlexandraKlein** [vercel/next.js#19089]
# Bug report

## Describe the bug

Implementing Next Image works locally, but throws 400 errors in Production with `"url" parameter is required` response.

### next.config.js
```javascript
module.exports = {
  images: {
    domains: [
      'images.ctfassets.net'
    ]
  }
}
```

### Implementaion
```javascript
<Image
  src={`https:${image.fields.file.url}`}
  alt={image.fields.title}
  width={image.fields.file.details.image.width}
  height={image.fields.file.details.image.height}
/>
```

Src url in production with 400 error: `https://mywebsite.com/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2F1xkvhwkgcr51%2F6HODBVSFqUTbEKI7ilXx%2Ff9f16ab3552e973b764c922f06db181a%2Fmy-image.png&w=1200&q=75`

Src url locally with no error/displays fine: `http://localhost:3000/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2F1xkvhwkgcr51%2F6HODBVSFqUTbEKI7ilXx%2Ff9f16ab3552e973b764c922f06db181a%2Fmy-image.png&w=1200&q=75`

- OS: macOS Catalina 10.15.7
- Version of Next.js: 10.0.1
- Version of Node.js: v15.1.0

**Comment by styfle** [comment]
What is "production" in this case?

Does it work with `next build && next start` visiting localhost?

**Comment by AlexandraKlein** [comment]
Yes, it works with `next build && next start`. Production is on the server. Please see the src url's posted in the description.
