### ISSUE TITLE
Expose useIntersection hook for public use

### ISSUE THREAD

**Issue by dohomi** [vercel/next.js#19205]
# Feature request

## Is your feature request related to a problem? Please describe.

The `<Image />` and `<Link />` component make use of `useIntersection`. It would be great if that hook would be publicly available

## Describe the solution you'd like

Expose hook `useIntersection` for public use:
```
import {useIntersection} from 'next/client'
```

**Comment by todortotev** [comment]
Great idea! If accepted I could push a PR for it?
