### ISSUE TITLE
Refreshing page does not show new changes, next dev does not rebuild page

### ISSUE THREAD

**Issue by JulianBuse** [vercel/next.js#19201]
# Bug report

Next js not rebuilding pages when I make a change

## Describe the bug

I make a change in index.js, and even refreshing the page does not reflect the change. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository: https://github.com/JulianBuse/chottoecchi

1. execute npm run dev
2. load the main page
3. Make some change to index.js

## Expected behavior

I would expect it to hot reload, or at least to reflect the changes when I reload the page, especially if I clear browser cache

## System information

- OS: Ubuntu in WSL
- Browser (if applies) Chrome
- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 12.18.2]

**Comment by robinskumar73** [comment]
Having the same issue after i upgraded to NextJS10

**Comment by JulianBuse** [comment]
I solved it. I launched the app in windows instead of wsl, and it works

**Comment by pAditya198** [comment]
I had the same issue. I switched from edge to brave now it works fine.

**Comment by UdaHarry** [comment]
> I had the same issue. I switched from edge to brave now it works fine.

Thanks Brother,  you solve my problems

**Comment by wotori** [comment]
> I had the same issue. I switched from edge to brave now it works fine.

now I have the same Issue with Brave
