### ISSUE TITLE
How to Fix  Capturing groups are not allowed  in rewirtes function in next.config.js

### ISSUE THREAD

**Issue by wildfrontend** [vercel/next.js#19311]
```
module.exports = {
  rewrites: async () => [
    {
      source: '/match/:gameType(^(?!(baseball|basketball|soccer)$))',
      destination: '/**',
    },
  ]
}
```
error message
![截圖 2020-11-19 下午7 40 05](https://user-images.githubusercontent.com/20965813/99661589-06f7c580-2a9f-11eb-8b49-f290f6cde295.png)

**Comment by ijjk** [comment]
Hi, it looks like you need to update your regex a bit for `path-to-regexp`, we have [this error](https://github.com/vercel/next.js/blob/13f8732f86ad449366f29a843af32379be72cacc/errors/invalid-route-source.md) doc that can sometimes show if we notice the issue you're running into although it doesn't seem to be triggered for this case. 

Updating the above source to: `/match/:gameType((?!baseball$|basketball$|soccer$).*)` should work correctly
