### ISSUE TITLE
Support `pages/_document` as a function component

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#19355]
# Feature request

## Is your feature request related to a problem? Please describe.

Converting `_document` to a function component has no real benefits currently besides being able to use `useContext` but there's no context wrapper above _document that you can use with useContext. `useState`, `useEffect`, and other hooks will not work as well given that `_document` is not hydrated client-side. 

Even though there are no benefits the question to support a function instead of a class comes up from time to time in #7515, hence why I'm creating this story.

## Describe the solution you'd like

`_document` is currently not a function component for backwards compat reasons, we can likely take a similar approach to what we did for _app though by having getInitialProps fall back to the default value.

**Comment by hasanzahran** [comment]
Is there any update regarding this issue.

Thanks

**Comment by CoryBall** [comment]
Using the class-based example from the docs, this is working for me:
```
const MyDocument: NextPage<DocumentInitialProps> = () => {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

MyDocument.getInitialProps = async (
  ctx: DocumentContext
): Promise<DocumentInitialProps> => {
  const initialProps = await Document.getInitialProps(ctx);
  return { ...initialProps };
};

export default MyDocument
```

**Comment by CoryBall** [comment]
Also, while I'm not using any hooks in my actual project's _document.tsx, I do like keeping all my components functional vs a mixture of functional and class-based. I'm sure many people who are wanting this want it for the same reason since otherwise there aren't many benefits.
