### ISSUE TITLE
Image Component allow no loader

### ISSUE THREAD

**Issue by SRugina** [vercel/next.js#19372]
# Feature request

## Is your feature request related to a problem? Please describe.

~The image component has a lot of local features, such as preventing Cumulative Layout Shift, using decoding="async", all the layout=... options etc. 
These are all features I would like to use for my images. 
However, the current Image Component is not compatible with `next export` unless you use `next start` or configure one of the third-party loaders. 
In a static context, `next start` is not an option.
All the third-party loaders cost some amount of money.
I would still like to get all the local benefits mentioned above when using `next export` without having to, effectively, pay to use the Image Component.~

As described in [this comment](https://github.com/vercel/next.js/issues/19372#issuecomment-731418069), `unoptimized={true}` can be used as a prop to use only the local benefits of the Image Component. However, `next export` still fails due to Next.js using the default loader.

## Describe the solution you'd like

~Thus, it would be nice to be able to use the Image Component with no loader while still gaining the local benefits mentioned above (i.e. do not modify the src URI to point to a loader and do not provide a srcset, etc.).~

Thus, it would be nice to be able to have `next export` succeed when all images use `unoptimized={true}`, or have a config option in `next.config.js` such as setting the loader to `"none"` or setting unoptimized to `true` globally so that the Image Component and `next export` ignore the loader.

## Describe alternatives you've considered

I could use an alternative image component from npm, but the Next.js one seems the most concise and reduces additional dependencies.

I could also copy the Next.js Image Component and remove the loader aspects, but this being a built-in option would be preferable.

An alternative feature would be to have `next export` download the srcset images for each image file in the public directory from the local/default Image Optimization API.

## Additional context

**Comment by SRugina** [comment]
I should probably pay closer attention to the documentation :)

This can be achieved by setting `unoptimized={true}` as a prop on the Image Component.

However, `next export` still fails, complaining that default loader is not compatible with `next export` despite unoptimized being used for all images. Setting the image loader in `next.config.js` to "" also does not work, as it defaults to the default loader. "none" is not an option.

Thus, this feature request is still valid as, with `unoptimized={true}` and/or the loader set to "none", `next export` should succeed.

**Comment by supperioguy** [comment]
Cool

**Comment by SRugina** [comment]
Temporary Solution:

Set the image loader in `next.config.js` to any of the options except default, do not specify an image path, and use the `unoptimized={true}` prop on every `<Image ... />` tag.

This will mean `next export` succeeds, but it is not clear in the least, as one might think Next.js is using the loader specified in `next.config.js`, when in fact it is not using any loader.
