### ISSUE TITLE
[next/image] with Layout="responsive" load at viewport width even when rendering at smaller size

### ISSUE THREAD

**Issue by nwesthoff** [vercel/next.js#19450]
# Bug report

## Describe the bug

Images with `layout="responsive"` load at viewport size, even if they're rendered at a size many times smaller, causing extremely slow pop-in of these images.

## To Reproduce

Hope this isn't a duplicate, but couldn't find it.
Minimal Repro: [Codesandbox](https://codesandbox.io/s/interesting-mahavira-gogo6?file=/pages/index.js)

1. Use `<Image src="" height={} width={} layout="responsive" />`
2. Wrap it in a smaller container
3. The image loads at a much higher size (suspect it's at viewport width, though not sure)

## Expected behavior
For those images to load according to their rendered size.

## Screenshots

<img width="1680" alt="next:image issue" src="https://user-images.githubusercontent.com/7780722/99993590-2d2ba700-2db8-11eb-861a-584d6a835f1b.png">

## System information

- OS: [e.g. macOS, Windows]
Both MacOS & Windows
- Browser (if applies) [e.g. chrome, safari]
Chrome 87
- Version of Next.js: [e.g. 10.0.1]
10.0.2
- Version of Node.js: [e.g. 12.0.0]
14.8.0
- Deployment: [e.g. next start, next export, Vercel, other platform]
Local with `next start` and `next build` and while deployed at  Vercel

**Comment by styfle** [comment]
This is expected behavior for `layout=responsive`.

The Image component doesn't know the size of its parent container so it assumes it will be (roughly) the device width.

Instead, you can use `layout=intrinsic` (the default behavior) if you don't want the image to grow.

Alternatively, you can use `layout=responsive`  with the [`sizes`](https://nextjs.org/docs/api-reference/next/image#sizes) prop for more fine-control over the media query.

**Comment by styfle** [comment]
> width and height. But you do have to set those, so what's that any good for then

The width/height are necessary to maintain the aspect ratio of the image.

If you don't want to set width/height then you can use `layout=fill` and it will stretch the image to fit the parent width/height.

**Comment by dohomi** [comment]
@nwesthoff you should use sizes prop. For example on your current example you know that don't want the image to get bigger than 360px. This is a small helper I wrote for setting image sizes based on width with known original dimensions and known theme breakpoints for `xs,sm,md` devices:
```js
const {breakpoints} = useTheme() // this is MaterialUI theme
const calculatePxToVw = (absolute: number, breakpoint: number) =>
  absolute > breakpoint ? 100 : Math.round((absolute / breakpoint) * 100)
const imageSizesOnWidthAndBreakpoints = (
  width: number,
  breakpoints: Theme['breakpoints']
) =>
  `(min-width: 0) and (max-width: ${
    breakpoints.values.sm - 1
  }px) ${calculatePxToVw(width, breakpoints.values.sm - 1)}vw, (min-width: ${
    breakpoints.values.sm
  }px) and (max-width: ${breakpoints.values.md - 1}px): ${calculatePxToVw(
    width,
    breakpoints.values.md - 1
  )}vw, ${calculatePxToVw(width, breakpoints.values.lg)}vw`


return (
  <Image sizes={imageSizesOnWidthAndBreakpoints(360, breakpoints)} {...otherProps}/>
)
```

**Comment by styfle** [comment]
Closing in favor of #30640
