### ISSUE TITLE
Server Side URL Redirect with Regexp pattern matching not working (next.config.js)

### ISSUE THREAD

**Issue by everest113** [vercel/next.js#19462]
# Bug report

## Describe the bug

In our next.config.js we have many URL redirects. All of them work as expected except for one that uses regexp to pattern match the URL.

The redirect works expected when built locally but it does not when deployed with Vercel. 

The URL redirect is as follows: 

```
{
        // Uses Regexp to match date params
        source: `/:vertical/:year([12]\d{3})/:month(0[1-9]|1[0-2])/:day(0[1-9]|[12]\d|3[01])`,
        destination: '/:vertical/issues/:year/:month/:day',
        permanent: true,
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add the following redirect to `next.config.js`:
```
{
        // Uses Regexp to match date params
        source: `/:vertical/:year([12]\d{3})/:month(0[1-9]|1[0-2])/:day(0[1-9]|[12]\d|3[01])`,
        destination: '/:vertical/issues/:year/:month/:day',
        permanent: true,
}
```

2. Test that the redirect works as expected locally (it does)
3. Deploy to Vercel
4. Verify that redirect no longer works as expected

## Expected behavior

A URL such as `website.com/business/2020/12/03` should server-side redirect to `website.com/business/issues/2020/12/03`.

## System information

- OS: macOS
- Browser: Chrome + Safari
- Version of Next.js: 10.0.0
- Version of Node.js: 12.x
- Deployment: Vercel

**Comment by ijjk** [comment]
Hi, the source here doesn't appear to be valid locally or on Vercel. Changing the source to `'/:vertical/:year(\\d{4})/:month(\\d{2})/:day(\\d{2})'` appears to be working properly locally and deployed. Example deployment here https://test-redirect-livid.vercel.app/business/2020/03/03`
