### ISSUE TITLE
Brower crashes when running Typescript application

### ISSUE THREAD

**Issue by pattiereaves** [vercel/next.js#19510]
# Bug report

[After carefully following the directions](https://nextjs.org/learn/excel/typescript/setup) to create my Next project with Typescript, when I build and subsequently start the project, the browser tab crashes with thousands of errors referencing `TypeError: Object(...) is not a function.

## Describe the bug

It appears that there might be some kind of Webpack module resolution error that is causing the issue, but because the issue is only on a production build and the errors quickly overwhelm my browser tab, I cannot pin point what is causing the bug.

## To Reproduce

I created [this repository](https://github.com/pattiereaves/next-typescript) by doing the following steps:
1. `npx create-next-app next-typescript`
2. `cd next-typescript; touch tsconfig.json`
3. `yarn add --dev typescript; npm install --save-dev typescript @types/react @types/node`. Next does it's TypeScript magic. ✨ 
4.  Convert [pages/index.tsx](https://github.com/pattiereaves/next-typescript/blob/main/pages/index.tsx), [pages/_app.tsx](https://github.com/pattiereaves/next-typescript/blob/main/pages/_app.tsx), [pages/api/hello.ts](https://github.com/pattiereaves/next-typescript/blob/main/pages/api/hello.ts) to Typescript.

To reproduce the error:
1. `npx next build`
2. `npx next export`
3. `npx next start`
4. Visit http://localhost:3000 with a console tab open and observe the following errors stream by:
![image](https://user-images.githubusercontent.com/44990/100184755-70147a00-2e9f-11eb-9c5a-1be51cef3e05.png)

Note that the app runs as expected with the `npm run dev` task

## Expected behavior

The app will run as expected when running the `npm run dev` task.

## Screenshots

See the steps to reproduce.

## System information

- OS: macOS
- Browser (if applies): observed in Chrome, Firefox
- Version of Next.js: 10.0.3
- Version of Node.js: 14.150
- Deployment: next start

## Additional context

It's possible I just missed a step in the Typescript set up, and if so, it's an opportunity to make the documentation more clear!

**Comment by Janpot** [comment]
Doesn't happen for me when I check out your project, is the problem still there after you delete the `.next` folder and rebuild the project?

**Comment by timneutkens** [comment]
I just tried following the reproduction steps but I can't reproduce as well

**Comment by ozamorowski** [comment]
Probably the same issue.
#18929

**Comment by pattiereaves** [comment]
@ozamorowski thank you for linking! I was looking everywhere 😅 . [Following your advice in this comment](https://github.com/vercel/next.js/issues/18929#issuecomment-733738354) fixed the issue.

**Comment by pattiereaves** [comment]
I'll go ahead and close this issue since it's a dupe of #18929.
