### ISSUE TITLE
Possibly incorrect dynamic params typings

### ISSUE THREAD

**Issue by bstro** [vercel/next.js#19555]
# Bug report

## Describe the bug

Next.js [documentation](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes) states that `Matched parameters will be sent as a query parameter (slug in the example) to the page, and it will always be an array, so, the path /post/a will have the following query object…`. However, in my project, in a file called `[[...myParam]].tsx`, the reported type for `myParam` is always `string | string[]`. In my experience, `myParam` is always of type `string[]` at runtime, and it thus seems incorrectly typed by Next.js

## To Reproduce

https://codesandbox.io/s/compassionate-cdn-8yjhp?file=/pages/%5B%5B...myParams%5D%5D.tsx

1. Go to [above sandbox](https://codesandbox.io/s/compassionate-cdn-8yjhp?file=/pages/%5B%5B...myParams%5D%5D.tsx)
2. Hover cursor over the definition of `IncorrectType` at line 10,

## Expected behavior

Based on the next.js [docs](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes), the type should be `string[]`. Instead, it is `string | string[]`.

Oddly, locally it is `string | string[]`, but at the CodeSandbox, it is `string | string[] | undefined`. Not sure why—I have essentially the same setup, both versions are pointed at `latest`…

## Screenshots
<img width="636" alt="Screen Shot 2020-11-26 at 12 12 21 AM" src="https://user-images.githubusercontent.com/627290/100324431-18980c00-2f7c-11eb-8f30-ea3081bd2a88.png">

## System information

- OS: Mac
- Version of Next.js: `next@latest`
- Version of Node.js: `v12.19.0`

## Additional context

No additional context

**Comment by davidsonsns** [comment]
Investigating it I saw that these divergences really happening between the local environment and codesandbox.

Query parameters type definitions land here:
https://github.com/vercel/next.js/blob/canary/packages/next/next-server/lib/router/router.ts#L257
As you can see, it uses `ParsedUrlQuery` from `querystring` type definitions.

Looking in the `node_modules/@types/node/querystring.d.ts` there are some differences comparing local env and codesandbox:

local: `interface ParsedUrlQuery { [key: string]: string | string[]; }`
codesanbox: `interface ParsedUrlQuery extends NodeJS.Dict<string | string[]> { }`

My guess is that we could discuss two points:
- Why there are these divergences between environments?
- Is there a better approach to type query params? I mean, maybe could have the possibility to add a generic ts parameter providing the possibility to set our own query parameter type.

Not sure if these questions should land here. If not, please let me know, I can do it in another place.

**Comment by bstro** [comment]
@davidsonsns Thanks for your investigative work. I like your idea of being able to specify one's own generic ts param. I'd also be interested in an approach like [use-query-params](https://github.com/pbeshai/use-query-params) which also allows one to write their own custom encoders/decoders.

**Comment by Timer** [comment]
Type systems are not expressive enough to distinguish between `string | string[]` based on external factors. I'd advise to simply cast it via `as string[]`.
