### ISSUE TITLE
Cannot import sass files from node_modules

### ISSUE THREAD

**Issue by minlare** [vercel/next.js#19569]
# Bug report

## Describe the bug

In the docs it states that you can [import styles from `node_modules`](https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules) which works for `.css` files.

Later on in the docs, it then states [Sass support has the same benefits and restrictions as the built-in CSS support detailed above](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support).

However, when attempting to import a `.scss` file from `node_modules` the following error occurs:

**Global CSS cannot be imported from files other than your Custom `<App>`. Please move all global CSS imports to `pages/_app.js`. Or convert the import to Component-Level CSS (CSS Modules).**

## To Reproduce

1. `import styles from 'npm-package/styles.scss`
2. See error

## Expected behavior

`.scss` file should load without error

## Screenshots

![image](https://user-images.githubusercontent.com/71008395/100378394-ebdf0580-300a-11eb-932f-5b99c5f30a4a.png)

## System information

- OS: Ubuntu
- Version of Next.js: 10.0.3
- Version of Node.js: 14.15.0
- Deployment: next dev

**Comment by Timer** [comment]
This is intentional as the Sass may be a different version than what you're using locally. However, we do need to update that error message to say Sass and explain this.

**Comment by michaelwindell26** [comment]
@Timer thanks for explaining that. Are there any plans to allow this in future (perhaps a bypass config like `assumedSassVersion`) ?

**Comment by minlare** [comment]
@Timer thanks for explaining that. Are there any plans to allow this in future (perhaps a bypass config like `assumedSassVersion`) ?

**Comment by zackdotcomputer** [comment]
Is there a way around this? I know that the SCSS file I want to import in node_modules has a compatible sass version to my main app's version - I would like a way to be able to do this rather than having it be simply impossible?

**Comment by reybok** [comment]
@zackdotcomputer I actually came across this limitation last week, so I "debugged" the css loaders. I then found a way to modify them in order to allow SCSS imports from `node_modules` in components:

`next.config.js`
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack: (config, options) => {
    const nextCssLoaders = config.module.rules.find((rule) => typeof rule.oneOf === 'object');
    if (!nextCssLoaders)
      return config;

    const appScssLoader = nextCssLoaders.oneOf.find((rule) => rule && rule.test && rule.test.toString() === '/(?<!\\.module)\\.(scss|sass)$/')
    if (appScssLoader) {
      const componentNodeModulesScssLoader = {
        ...appScssLoader,
        include: {
          and: [ /node_modules/ ]
        },
        issuer: {
          and: [ __dirname ]
        }
      }
      const nextScssLoaderIndex = nextCssLoaders.oneOf.indexOf(appScssLoader)
      nextCssLoaders.oneOf.splice(nextScssLoaderIndex + 1, 0, componentNodeModulesScssLoader)
    }

    return config
  }
}

module.exports = nextConfig
```

As @minlare said, maybe we can implement a flag like _allowGlobalSassInComponents_ in the `nextConfig` that adds a similar loader? Someone from the dev team might be able to further explain the pros and cons.

Thanks everyone for your hard work on this great open source project! :pray:

**Comment by shuding** [comment]
It should be supported now with the `transpilePackages` option: https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages

Let us know if you're running into a problem with that!
