### ISSUE TITLE
Using next/image with priority property and cloudinary loader config, adds space on top of every image on mobile.

### ISSUE THREAD

**Issue by wilson-alcantara** [vercel/next.js#19586]
# Bug report

## Describe the bug

It renders an additional space on top of every image on **mobile** when using `next/image` with `priority` property and cloudinary loader config.

## To Reproduce

[CodeSandbox](https://codesandbox.io/s/nextjs-image-priority-issue-22f17?file=/pages/index.js)
1. Configure loader in `next.config.js` as written below.
2. Render Image using `next/image` with priority property above the fold and another image without priority property, below the fold.
3. **On mobile**, images will have extra space on top of it. https://22f17.sse.codesandbox.io/

```javascript
// next.config.js
module.exports = {
  images: {
    domains: ["assets.wego.com"],
    loader: "cloudinary",
    path: "https://assets.wego.com/image/upload/"
  }
};
```

```javascript
import Image from "next/image";

export default function IndexPage() {
  return (
    <div>
      <div>
        <Image
          width="100"
          height="40"
          src="/v1/makalu/wego.png"
          alt="logo"
          priority
        />
      </div>

      <div style={{ paddingTop: "800px" }}></div>

      <div>
        This image has empty space on top of it.
        <Image
          width="100"
          height="40"
          src="/v1/makalu/wego.png"
          alt="logo"
        />
      </div>
    </div>
  );
}
```

## Expected behavior

Images should not have an extra space on top of it.

## Screenshots

<img width="390" alt="Screenshot 2020-11-27 at 12 58 11" src="https://user-images.githubusercontent.com/275230/100412833-b1c83f00-30b0-11eb-9a93-e540152b4f08.png">

## System information

- OS: macOS
- Browser chrome mobile, chrome device toolbar
- Version of Next.js: ~10.0.3~ `12.0.1`
- Version of Node.js: ~12.4.0~ `16`

**Comment by snazzyjames** [comment]
I saw something similar happening when I was implementing the Image component recently.  I was able to get the problem to stop happening by using `objectFit={'contain'}`.  I don't know if the cause of my issue is the same as yours, but I thought it might be helpful if you want to give it a try.

**Comment by wilson-alcantara** [comment]
@snazzyjames Seems like the `objectFit` can only be used along side `layout="fill"`.
https://nextjs.org/docs/api-reference/next/image#objectfit

Though I still tried your suggestion but the issue is still there. I mostly use layout `responsive`, `fill` and `intrinsic`.

Anyway, thanks for your suggestion! Hope we can find a fix for this soon.

**Comment by sdn90** [comment]
Running into this as well and I'm having trouble figuring out what's causing it.

I've taken some notes and I still haven't really made sense of it.

Here are the cases I've tested out:

### Working cases
- Safari/FF/Chrome macOS full window width
- Safari/FF/Chrome macOS minimum window width
- iPad Pro

### Not working
- Safari/FF/Chrome macOS emulating devices smaller than iPad Mini size
- iPhone 12 Mini


## Hydration
Upon loading page using an affected device, I get a hydration mismatch warning on a style attribute. I don't get this message on the working cases.

Here's a diff of the server rendered HTML and the hydrated
```diff
<div
  style="
    display: block;
    overflow: hidden;
    position: relative;
    box-sizing: border-box;
    margin: 0;
  "
>
  <div style="display: block; box-sizing: border-box; padding-top: 100%"></div>
- <img
-   src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
-   decoding="async"
-   style="
-     visibility: hidden;
-     position: absolute;
-     top: 0;
-     left: 0;
-     bottom: 0;
-     right: 0;
-     box-sizing: border-box;
-     padding: 0;
-     border: none;
-     margin: auto;
-     display: block;
-     width: 0;
-     height: 0;
-     min-width: 100%;
-     max-width: 100%;
-     min-height: 100%;
-     max-height: 100%;
-   "
- />
+ <img
+   src="..."
+   decoding="async"
+   sizes="..."
+   srcset="..."
+   style="visibility: visible"
+ />
</div>
```

Notice the `<img />` tag is missing all of the positioning styles which is set here:
https://github.com/vercel/next.js/blob/7ae76f4326840fb92cc542d867c5b9c27333a80c/packages/next/client/image.tsx#L258-L282

**Comment by wilson-alcantara** [comment]
I have updated `next` version to 11, `react` to 17.0.2 and `react-dom` to 17.0.2 in [codesandbox](https://codesandbox.io/s/nextjs-image-priority-issue-22f17?file=/pages/index.js).

I'm still seeing the issue. https://22f17.sse.codesandbox.io/

**Comment by wilson-alcantara** [comment]
I have updated `next` version to 11.1.2 in [codesandbox](https://codesandbox.io/s/nextjs-image-priority-issue-22f17?file=/pages/index.js).

I'm still seeing the issue. https://22f17.sse.codesandbox.io/

**Comment by sapjax** [comment]
Same issue

**Comment by michelbieleveld** [comment]
Not sure if we are all the same issue but I am using csp , and my browser log showed problems with the inline script if I recall correctly, solved those problems and no longer had this issue.

**Comment by sapjax** [comment]
Hi, guys, I found a solution to avoid this issue:
add `data-cfstyle="22222"` to `Image` component. 😅😅😅
```JSX
<Image
          width="100"
          data-cfstyle="3333"
          height="40"
          src="/v1/makalu/wego.png"
          alt="logo"
        />
```
but didn't know why...
I think it's might be related to Cloudflare services.

**Comment by sapjax** [comment]
I found this issue is that Cloudflare injected a script into HTML,
 https://ajax.cloudflare.com/cdn-cgi/scripts/04b3eb47/cloudflare-static/mirage2.min.js
and this script remove the `style` of `img` tags, if we add `data-cfstyle` attribute on `img`, it will not remove `style` and **merge** style then, so we can found on the rendered html img tags, the style is `3333;position:absolute....`.
🤣

**Comment by wilson-alcantara** [comment]
Cool, that works! Thanks @sapjax @balazsorban44
