### ISSUE TITLE
Add blacklist to PWA

### ISSUE THREAD

**Issue by jhenriquevissotto** [vercel/next.js#19584]
I have too much problens with video play.

I have videos hosted in AWS S3 and a server express that redirect that url in src attr of video tag to correct video file in S3.

Often I have this problem:
https://stackoverflow.com/questions/47676422/video-seeking-does-not-work-in-pwa-progressive-web-app

The crossOrigin="true" in attr video tag solve some cases, but others not.

What I want say?

That the PWA could have a config option for exclude the cache of file that contains some strings.

Example:

```javascript
module.exports = withPWA({
	pwa: {
		dest: 'public',
		runtimeCaching: runtimeCaching,
		notCache: ['/stream-video-path']
	}
})

```

**Comment by radoslawgrochowski** [comment]
@jhenriquevissotto 
I think it should be issued in https://github.com/shadowwalker/next-pwa, not here.

**Comment by lachlanjc** [comment]
Yep, this issue isn't relevant to Next.js core 👍
