### ISSUE TITLE
Add option to disable getServerSideProps on client-side navigation

### ISSUE THREAD

**Issue by ZiiMakc** [vercel/next.js#19611]
# Feature request

## Is your feature request related to a problem? Please describe.

1. Function `getServerSideProps` runs on every request and there is no way to use apollo [existing cache to load data from on client-side navigation.](https://github.com/vercel/next.js/discussions/11957#discussioncomment-48814) It's will do unnecessary request to server if there is data already in client cache.

2. We need SSR only on initial render for SEO, there is no need for it to run every time and block page rander, it's better to show loading or page skeleton.

## Describe the solution you'd like

Add option to disable getServerSideProps on client-side navigation

```
export async function getServerSideProps(context) {
  return {
    props: {},
    disableOnClientSideNavigation: true,
  }
}
```

## Describe alternatives you've considered

Add another function like `getServerSideProps` thats will not run on client navigation.

OR

Add export config from page:
```
export pageConfig = {
    disableOnClientSideNavigation: true,
}
```

OR

Add option to router:
`router.push('user/1', undefined, { disableGetServerSideProps : true })`

## Additional context

Then you can use same graphql query in component and getStaticProps

```
const UserQuery = gql`
  query User {
    getUser {
      id
    }
  }
`

export function User(): JSX.Element {
  const { data } = useQuery(UserQuery)

  return (
      <div>user</div>
  )
}

export const getStaticProps: GetStaticProps = async (ctx) => {
  const apolloClient = initializeApollo(null)

    await apolloClient.query({ query: UserQuery})

  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
    },
  }
}
```

**Comment by balazsorban44** [comment]
From the docs:
> `shallow` - Update the path of the current page without rerunning `getStaticProps`, `getServerSideProps` or `getInitialProps`. Defaults to `fals`


https://nextjs.org/docs/api-reference/next/link
https://nextjs.org/docs/api-reference/next/router#routerpush

**Comment by ZiiMakc** [comment]
@balazsorban44 are you sure it will render new component and not just change the link?

**Comment by balazsorban44** [comment]
I am not sure I understand what you mean. When you transition from a page to another (by `Link` or `router`) you will render a new (page) component, yes. Adding the `shallow` option to either the `Link` or `router.push`, it will disable the `getServerSideProps` call.

**Comment by ZiiMakc** [comment]
@balazsorban44 
From docs:

The URL will get updated to /?counter=10. and the page won't get replaced, only the state of the route is changed.

Shallow routing only works for same page URL changes. For example, let's assume we have another page called pages/about.js, and you run this:

`router.push('/?counter=10', '/about?counter=10', { shallow: true })`

Since that's a new page, it'll unload the current page, load the new one and wait for data fetching even though we asked to do shallow routing.

So it's not a sollution.

**Comment by balazsorban44** [comment]
I see. Sorry I could not help. 😕
