### ISSUE TITLE
Serverless "Body exceeded 1mb limit"

### ISSUE THREAD

**Issue by jose-donato** [vercel/next.js#19684]
# Bug report

## Describe the bug

When sending FormData larger than 1MB in the body of POST request to /api serverless function I'm getting "Body exceeded 1mb limit".

## To Reproduce
```
const formData = new FormData();
formData.append("image", file) //file is an image with more than 1MB
 fetch("/api/dominantColor", {
        method: "POST",
        body: formData
 })
```

## Expected behavior

We should be able to send data with more than 1mb.

## Screenshots

![image](https://user-images.githubusercontent.com/43375532/100635900-fd851d80-3328-11eb-9f9d-bf079634e1f3.png)

## System information

- OS: WSL2 ubuntu 20.10
- Browser (if applies) Chrome
- Version of Next.js: 10.0.1
- Version of Node.js: v12.19.0
- Deployment: next dev

**Comment by jose-donato** [comment]
My bad, I did not see the part where this is stated in the documentation.

[https://nextjs.org/docs/api-routes/api-middlewares#custom-config](https://nextjs.org/docs/api-routes/api-middlewares#custom-config)
![image](https://user-images.githubusercontent.com/43375532/100636729-e98deb80-3329-11eb-960d-2b2c555414a0.png)

**Comment by Joseppi83** [comment]
Thanks for posting when and why you found the answer to your problem!  You saved me some time, because I was scratching my head, when I saw the "1mb limit" notice in the console.

**Comment by rawand121** [comment]
Please Where should i write this code? i mean in which file?

**Comment by jose-donato** [comment]
> Please Where should i write this code? i mean in which file?

@rawand121, In the API function file, for example `pages/api/hello.js`

**Comment by rawand121** [comment]
> > Please Where should i write this code? i mean in which file?
> 
> @rawand121, in the API function file, for example `pages/api/hello.js`

Just add this code into my API Function file? and its all?

**Comment by Soujiro17** [comment]
Who can explain me how can i add the config? I loaded the config file in the API function file, but doesn't work. What more i need to do?

**Comment by jose-donato** [comment]
> Who can explain me how can i add the config? I loaded the config file in the API function file, but doesn't work. What more i need to do?
> 
> ![image](https://user-images.githubusercontent.com/13888213/131226734-19fb754d-bf5c-489d-898b-c86922adeef5.png)

Hey, you need to export the config in that file like in the second comment in this issue

**Comment by Soujiro17** [comment]
> > Who can explain me how can i add the config? I loaded the config file in the API function file, but doesn't work. What more i need to do?
> > ![image](https://user-images.githubusercontent.com/13888213/131226734-19fb754d-bf5c-489d-898b-c86922adeef5.png)
> 
> Hey, you need to export the config in that file like in the second comment in this issue

Thank you so much!

**Comment by JasonBDev** [comment]
Also, I think it is important to note if you are hosting your app on an NGINX server they limit it as well! So make sure to add it like this in the default Nginx config you are using: 

`client_max_body_size 25M; #25mb`

**Comment by ajhanus** [comment]
I have `export const config = {
  api: {
    bodyParser: false
  }
};`

I am still seeing this error message. Any ideas?
