### ISSUE TITLE
[next/image] Images are vertically misaligned when images and texts are arranged horizontally

### ISSUE THREAD

**Issue by chorkaichan** [vercel/next.js#19768]
# Bug report

## Describe the bug

[next/image] Images are vertically misaligned when images and texts are arranged horizontally.

## To Reproduce

Use next/image as below.

```
import Image from 'next/image'
...

<div className="flex justify-between items-center">
  <div className="flex-none mr-6">
    <Image
      src="/path/to/image"
      alt="sample"
      width={...}
      height={...}
    />
  </div>
  <div className="flex-1">
    This is sample text. This is sample text. This is sample text. This is sample text. ...
  </div>
</div>

```

## Expected behavior

Set image's vertical-align as bottom to align correctly.

## Screenshots

<img width="691" alt="スクリーンショット 2020-12-03 17 07 14" src="https://user-images.githubusercontent.com/10989498/100981416-20fad300-358a-11eb-9c96-2a70c7138625.png">

## System information

- OS: macOS
- Browser: chrome
- Version of Next.js: 10.0.3
- Version of Node.js: 12.14.1

**Comment by chorkaichan** [comment]
I've fixed and made a PR. This is my first contribution. Please tell me if there's anything weird.
https://github.com/vercel/next.js/pull/19771

**Comment by styfle** [comment]
We introduced a new component [`next/future/image`](https://nextjs.org/docs/api-reference/next/future/image) that no longer sets inline styles. I'm going to close this issue since we don't plan to change the styles of `next/image` anymore, thanks!
