### ISSUE TITLE
Next/image on Vercel can't fetch external image from not-secured site.

### ISSUE THREAD

**Issue by ayikfour** [vercel/next.js#19791]
# Bug report

## Describe the bug

Next/image broken when I deployed to Vercel. The error message is 500 - `INTERNAL_UNEXPECTED_ERROR `.

For the recap, I'm developing a mini site powered with self-hosted Strapi for the backend. The backend is hosted with a self-signed certificate (not secure), that's why I need to run Next app with `NODE_TLS_REJECT_UNAUTHORIZED='0'` command. It's run on my local development but broken in Vercel.

Then I found this [issue here #19630](https://github.com/vercel/next.js/issues/19630) and try to change my external URL to a secured site, it works fine.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create new Next.js project.
2. add new unsecured domain next.config.js
3. add this argument `NODE_TLS_REJECT_UNAUTHORIZED='0'` eg: `NODE_TLS_REJECT_UNAUTHORIZED='0' npm run dev` to the package.json
4. deploy on vercel

## Expected behavior

Expected to load my backend image on Vercel.

## Screenshots

![image](https://user-images.githubusercontent.com/28996086/101042570-eb68e080-35af-11eb-98e1-2bc2647c0da3.png)

here is the screenshot when I try to open `_next/image` url.

## System information

- OS: Mac OS
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 10.0.2
- Version of Node.js: 14.1.0

**Comment by yakai911** [comment]
I have the same problem,my image from heroku backend displayed  in develop mode,but don't work in production mode.

**Comment by ayikfour** [comment]
> I have the same problem,my image from heroku backend displayed  in develop mode,but don't work in production mode.

How do you solve it?

**Comment by yakai911** [comment]
> > I have the same problem,my image from heroku backend displayed  in develop mode,but don't work in production mode.
> 
> How do you solve it?

I didn't solve it,changed back to normal img to display  pictures

**Comment by ayikfour** [comment]
> > > I have the same problem,my image from heroku backend displayed  in develop mode,but don't work in production mode.
> > 
> > How do you solve it?
> 
> I didn't solve it,changed back to normal img to display  pictures

Ah I see, thank you.

I think I going to change it back too

**Comment by matyushen** [comment]
Got the same issue with images from Contentful. Have you found any solution?

**Comment by lauridskern** [comment]
Bump, having the same issue

**Comment by yakai911** [comment]
> > > > I have the same problem,my image from heroku backend displayed  in develop mode,but don't work in production mode.
> > > 
> > > 
> > > How do you solve it?
> > 
> > 
> > I didn't solve it,changed back to normal img to display  pictures
> 
> Ah I see, thank you.
> 
> I think I going to change it back too

Hi dude,I pick up my website and solved this problem by adding a customer loader like down blellow,you can give it a try.
`const myLoader = ({ src, width, quality }) => {
  return `${process.env.NEXT_PUBLIC_API}${src}?w=${width}&q=${quality || 75}`;
};

export default myLoader;`

**Comment by bakerue-owner** [comment]
> > > > > I have the same problem,my image from heroku backend displayed  in develop mode,but don't work in production mode.
> > > > 
> > > > 
> > > > How do you solve it?
> > > 
> > > 
> > > I didn't solve it,changed back to normal img to display  pictures
> > 
> > 
> > Ah I see, thank you.
> > I think I going to change it back too
> 
> Hi dude,I pick up my website and solved this problem by adding a customer loader like down blellow,you can give it a try.
> `const myLoader = ({ src, width, quality }) => { return`${process.env.NEXT_PUBLIC_API}${src}?w=${width}&q=${quality || 75}`; }; export default myLoader;`

Yes this worked for me as well. From NextJs docs

```import Image from 'next/image'

const myLoader = ({ src, width, quality }) => {
  return `https://example.com/${src}?w=${width}&q=${quality || 75}`
}

const MyImage = (props) => {
  return (
    <Image
      loader={myLoader}
      src="/me.png"
      alt="Picture of the author"
      width={500}
      height={500}
    />
  )
}

**Comment by lauriskuznecovs** [comment]
Here is explained how to use custom loader, that way it is possible to load images from self-signed SSL.
https://nextjs.org/docs/api-reference/next/image#loader

**Comment by styfle** [comment]
From Node.js:

https://github.com/nodejs/node/blob/42dbaed4605f44c393a057aad75a31cac1d0e5f5/lib/_tls_wrap.js#L1311-L1314

> Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

I don't think this is desirable for production websites.

Perhaps you should use `http:` instead of `https:` for the `src` prop if you don't intend to use a valid certificate.

**Comment by balazsorban44** [comment]
I don't think there is anything we can do here, so closing. As said above, it's not really desirable to set NODE_TLS_REJECT_UNAUTHORIZED in production.

Feel free to comment if you need more help, this is not a Next.js bug in any case.
