### ISSUE TITLE
Module path aliases not picking module index.js

### ISSUE THREAD

**Issue by Ne-Ne** [vercel/next.js#19881]
# Bug report

## Describe the bug

I am trying to destructure a named export from the root of the module alias. It fails to load when I won't load the module from `components/index.js`:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["components/*"]
    }
  }
}
```

I cannot get the following code to load:

```js
import { DummyComponent } from "@components";
```

I know the module is fine as I can import directly from the relative path and it works fine. Alas following above it does not work.

Interesting point, if I do not use `paths`, and just import using `baseUrl` it works fine:

```js
import { DummyComponent } from "components";
```

## To Reproduce

Use the alias module config from [alias docs](https://nextjs.org/docs/advanced-features/module-path-aliases) above and re-export a named export within an `index.js` in the root of `/components`

## Expected behaviour

Loads module from either the following imports options:

```
// root
import { DummyComponent } from "@components";
```

or

```
// actual file
import { DummyComponent } from "@components/DummyComponent";
```

## System information

- OSZ
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 12.0.0]
- Deployment: [e.g. next start, next export, Vercel, other platform]

## Additional context

To get the solution to work, I need to create an additional alias config option:

In my example I am using `@components`, I think it reads better but the same without my preference:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@components": ["components/index"],
      "@components/*": ["components/*"]
    }
  }
}
```

In a perfect world, I would rather destructure my components, hooks or utils rather than littering my `/components` directory structure to the `pages` contents.

I am working on the pretence, that if I change my directories or refactor within `/components` I would have git changes outside my components directory.

**Comment by timneutkens** [comment]
The current behavior is correct as per the typescript module resolution algorithm.

**Comment by ianchanning** [comment]
Where as this might match the typescript module resolution algorithm, support was added for `jsconfig.js` - if the [documentation](https://nextjs.org/docs/advanced-features/module-path-aliases) mention that the `jsconfig.js` script might need to be updated to match typescript resolution with reference to the above issue that would help for projects that are migrating to Next.js

**Comment by astrot1988** [comment]
You should set baseUrl.
`// tsconfig.json or jsconfig.json
{
  "compilerOptions": {
    "baseUrl": "."
  }
}`
than all works fine
