### ISSUE TITLE
Router bug with Catch-All routes

### ISSUE THREAD

**Issue by rmsheppard** [vercel/next.js#20058]
# Bug report

## Describe the bug

This appears to be an issue with Catch-All-Routes and the query-string params presented in the asPath.  If query string is present the router url will update but the actual page will not change.  This appears to only happen in dev environment.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Download repo from "https://github.com/rmsheppard/next-router-error"
2. run in "npm run dev"
3. Click on "Managed Project List" link
4. Click on "Project 111 - Package 222" link
5. Notice behavior in url ( url changes, but page route didn't actually change )

## Expected behavior

The router should navigate to the expected page with the params

## Screenshots

See repo/steps to reproduce

## System information

- OS: macOS
- Browser: Tested in Chrome
- Version of Next.js: [e.g. 10.0.3]
- Version of Node.js: [e.g. 12.18.3]
- Deployment: run on local development environment

## Additional context

This issue appears only in the development environment.  The functionality though should be consistent between dev run and prod build.  The router url will update but the page will not update and will be stuck basically on the loading screen.  Removal of the query string params on the asPath allows the page to work but this shouldn't stop the router from working.

**Comment by rmsheppard** [comment]
@lfades Hi, any plans on this getting fixed.  I know this has not been assigned to you but it is stopping us from upgrading to recent versions and the issue exists from 9.5.3 to 10.0.3 ( as of the latest version when I submitted the ticket)

**Comment by lfades** [comment]
@rmsheppard Looks like it's an issue indeed, the behavior in `next start` is different from the one in `next dev`. I'll label it as a bug as it was happening in the latest canary too. However I don't have a timeline to when will it get fixed.

I think you should try using the catch all route to load the content of the other page, instead of loading another page, there's no benefit on the current method you're using in your demo. rewrites and redirects could also be helpful there.

**Comment by rmsheppard** [comment]
@lfades This was a simplified version.  We have 3 and possibly more in the future that all sort of share the same route.  Old business rules that must remain but this redirector catch all route is needed to send to the right place.  Personally, I'd rather them all have their own routes but just don't have that choice.  Thanks for the response though.  This is keeping us from updating and I hope it can be addressed soon.

**Comment by ijjk** [comment]
Hi, this has been updated in the latest version of Next.js `v10.0.6-canary.7`, please upgrade and give it a try!

**Comment by rmsheppard** [comment]
Sure, we will give it a try in the next couple of days.  Thanks for your help.

**Comment by rmsheppard** [comment]
It appears to work for me when I tried in our project.  Thanks @ijjk
