### ISSUE TITLE
next/image img elements missing width and height 

### ISSUE THREAD

**Issue by ystewart** [vercel/next.js#20060]
# Bug report

## Describe the bug

Image elements missing width in height.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Build an app with images served using next/image
2. Go to app in Chrome browser
3. Open devtools
4. Run Lighthouse on desktop
5. Scroll down to Performance section 
6. See error: "Image elements do not have explicit width and height"

## Expected behavior

Image element rendered by next/image to include provide width and height.

## Screenshots

![Screenshot 2020-12-10 at 16 44 18](https://user-images.githubusercontent.com/36882462/101794295-046d1680-3b07-11eb-8a5a-c1bfce50fede.png)

Screenshot from next/image example app running in development mode mode.

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 12.18.4
- Version of Node.js: 6.14.6
- Deployment: next start

## Additional context
-

**Comment by max-lynn** [comment]
Hope you guys fix this, made me question if I should use it as it gives me a negative on lighthouse where as using img tags didn't

**Comment by Timer** [comment]
This is a bug in lighthouse and has no adverse performance affect.

https://github.com/GoogleChrome/lighthouse/issues/11631

**Comment by SalahAdDin** [comment]
> This is a bug in lighthouse and has no adverse performance affect.
> 
> [GoogleChrome/lighthouse#11631](https://github.com/GoogleChrome/lighthouse/issues/11631)

So, it could not be an SEO requirement for the image component, right?

I'm getting the same error in my reports.

**Comment by ceruberu** [comment]
I have same problem and ended up here, i want to get 100 haha

**Comment by dayvista** [comment]
This is holding my score at 99 😭😭😭

**Comment by Timer** [comment]
The best way to get this fixed faster is by upvoting or asking for updates on the **upstream issue**: https://github.com/GoogleChrome/lighthouse/issues/11631

**Comment by mmazzarolo** [comment]
FYI a fix just landed in Lighthouse: [GoogleChrome/lighthouse#12120](https://github.com/GoogleChrome/lighthouse/pull/12120)

**Comment by alan345** [comment]
Im having the same issue but not in lighthouse, in developers.google.com: 
The image is `SVG`
![image](https://user-images.githubusercontent.com/15246526/109358346-76b4e380-7838-11eb-9f9c-612c09580658.png)

I am using the `Image` from `import Image from 'next/image'`

```
                    <Image
                      itemProp="image"
                      alt={`Product ${props.product.name}`}
                      width={50}
                      height={50}
                      src={props.product.nameFile}
                    />
```

Image `nameFile` is `SVG`

**Comment by lachlanjc** [comment]
Yep, that's the placeholder image Next inserts for you. It's unfortunate that they flag that, since I heard that placeholder code was a suggestion from the Google team, but I think they're working out not flagging it in the future for you.
