### ISSUE TITLE
Google AMP Stories Support

### ISSUE THREAD

**Issue by oguzbilgic** [vercel/next.js#20079]
Google recently introduced a product called [Google stories](http://stories.google/)

As far as I can understand, this implements AMP with special HTML tags. Eventually, this ends up being published as an HTML page with a bookend.json file attached. 

Not sure what would be the best way to implement this using next.js

**Comment by Maxgit3** [comment]
this would be an interesting task.  maybe an example could be created in the next js examples.

**Comment by c0b41** [comment]
nextjs already supporting web stories, https://github.com/vercel/next.js/tree/canary/examples/amp-story
