### ISSUE TITLE
/_next/image can give "Invalid body" with /pages/api served images

### ISSUE THREAD

**Issue by 700software** [vercel/next.js#20109]
# Bug report

## Describe the bug

By default (without below Workaround), the `<Image>` tag cannot load images generated from certain `/pages/api` endpoints.

It looks like /_next/image is creating an `object` instead of `http.IncomingMessage` and passing it directly to the `/pages/api` endpoint. While this is a great performance enhancement, the object lacks `.on` so is not compatible by default unless we add `export const config = { api: { bodyParser: false } }` to our endpoint. The error presented provides no clues to the workaround so we need to either document this or make it not error.

## To Reproduce

In any Next.js v10 project,

1. Create `/pages/api/test-would-be-image.js`
```js
export default async function (req, res) {
  res.end('hi!')
}
```

2. Visit http://localhost:3000/_next/image?url=/api/test-would-be-image&w=3840&q=75

(This is the endpoint normally generated by the new `<Image>` tags)

## Expected behavior

Web page `hi!`

(or if it were a real image API endpoint instead of the test file as per step 1, we'd expect the scaled down version of the image)

## Actual behavior 

Web page `Invalid body`

### Source of error
https://github.com/vercel/next.js/blob/17c81cdce3621639a94a8adb1d78dbdd52205e61/packages/next/next-server/server/api-utils.ts#L132
### Cause of error
https://github.com/vercel/next.js/blob/17c81cdce3621639a94a8adb1d78dbdd52205e61/packages/next/next-server/server/api-utils.ts#L128
```
TypeError: stream.on is not a function
    at readStream (...\node_modules\raw-body\index.js:190:10)
    at executor (...\node_modules\raw-body\index.js:112:5)
    at new Promise (<anonymous>)
    at getRawBody (...\node_modules\raw-body\index.js:111:10)
    at parseBody (...\node_modules\next\dist\next-server\server\api-utils.js:13:36)
    at apiResolver (...\node_modules\next\dist\next-server\server\api-utils.js:6:34)
    at DevServer.handleApiRequest (...\node_modules\next\dist\next-server\server\next-server.js:63:433)
    at async Object.fn (...\node_modules\next\dist\next-server\server\next-server.js:55:530)
    at async Router.execute (...\node_modules\next\dist\next-server\server\router.js:24:67)
    at async DevServer.run (...\node_modules\next\dist\next-server\server\next-server.js:65:1023)
```

## Workaround

Simply add `export const config = { api: { bodyParser: false } }` to the api endpoint in step 1 above yields expected behaviour

## Suggested solution

If `apiReq` lacks `.on` then skip `parseBody`. Add comment linking to this issue to explain why.

https://github.com/vercel/next.js/blob/17c81cdce3621639a94a8adb1d78dbdd52205e61/packages/next/next-server/server/api-utils.ts#L60

Perhaps `apiReq.body` can become `{}` in this case.

(Another possible solution is to look at `apiReq.method` but I don't think this is the best idea.)

## System information

- OS: any
- Version of Next.js: [e.g. 10.0.3]
- Version of Node.js: [e.g. 14.3.0]
- Deployment: `next run dev`

**Comment by 700software** [comment]
I would add PR with suggested solution, but I'm not sure if checking `typeof apiReq.on == 'function'` is the desired approach. Perhaps there is a more proper way to see if `apiReq` is a `stream.Readable`... What do you think?

It would need to also be compatible with `express` and any other conceivable framework I imagine that is why I was hesitant to use `instanceof`.

**Comment by ijjk** [comment]
Hi, this has been updated and appears to be working properly in the latest version of Next.js, please update and give it a try!
