### ISSUE TITLE
DYNAMIC ROUTES - ( et::ERR_ABORTED 404 (Not Found) ) NO LINK USAGE!

### ISSUE THREAD

**Issue by Henry-Asante** [vercel/next.js#20140]
Currently facing issues with DYNAMIC Routes, It redirects alright.
But after the redirect, the dynamic component is not shown.

The homepage's extra files ( CSS, JS etc ) are not allowed access resulting in:
![image](https://user-images.githubusercontent.com/30865594/101962642-9b6bc880-3c04-11eb-827e-e8ec12b43cd8.png)

Folder Structure:
![image](https://user-images.githubusercontent.com/30865594/101963272-37e29a80-3c06-11eb-846a-83f2ed573787.png)

URL looks like this:
http://localhost:3000/blog/a-simple-blog-post

Console error looks like this: ( red is the query )
![image](https://user-images.githubusercontent.com/30865594/101962798-fc939c00-3c04-11eb-9f26-f6a13e162a3b.png)

NEXT.J JS VERSION:
"next": "^10.0.3",

**Comment by jamesmosier** [comment]
Hi! Could you please provide a complete reproduction of this issue including a repository? Thanks!
