### ISSUE TITLE
Getting error when using next/image within <Link />

### ISSUE THREAD

**Issue by qb-rivkyb** [vercel/next.js#20434]
# Bug report

When using `<Image /> `inside `<Link /> `I get the following error: 
```
react-dom.development.js?61bb:88 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `EmotionCssPropInternal`.
    in Image (created by EmotionCssPropInternal)
    in EmotionCssPropInternal (at Header/index.jsx:13)
    in Link (at Header/index.jsx:12)
    in div (created by EmotionCssPropInternal)
    in EmotionCssPropInternal (at Header/index.jsx:11)
    in Header (at Layout.jsx:7)
    in Layout (at pages/index.jsx:7)
    in IndexPage (at _app.js:14)
    in MyApp
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root

```

use 
`import Link from "next/link";` and `import Image from "next/image";` in a file. Then 
```
<Link href="/">
          <Image
            src="/logo.svg"
            alt="logo"
            width="97"
            height="40"
            css={s.logo}
          />
  </Link>
```

## Expected behavior

There should be no error when doing this. 

## System information

- OS: MacOS
- Browser Chrome
- Version of Next.js: "10.0.4"
- Version of Node.js: 14.15.1
- Deployment: next dev

**Comment by Maxgit3** [comment]
I believe you need to wrap the the image in an anchor tag

```
 <Link href="/">
      <a>
          <Image
            src="/logo.svg"
            alt="logo"
            width="97"
            height="40"
            css={s.logo}
          />
    </a>
  </Link>

```

**Comment by Kerosz** [comment]
I had the same problem and looked for an issue opened. Even thou wrapping the image component with any element that allows forwarding refs is a workaround, I think it should be better for the image component to be wrapped in a forwardref instead

**Comment by Directgab** [comment]
@kerosz. please how? i am having same error

**Comment by balazsorban44** [comment]
https://github.com/vercel/next.js/issues/20434#issuecomment-750673138 is the correct answer.

**Comment by bluesnooker123** [comment]
In my case the height of the <a> changed.
So I used <> to solve this problem.

`<Link href="/">
      <>
          <Image
            src="/logo.svg"
            alt="logo"
            width="97"
            height="40"
            css={s.logo}
          />
    </>
  </Link>`
