### ISSUE TITLE
Cannot find module 'babel-plugin-macros' 

### ISSUE THREAD

**Issue by juuyan** [vercel/next.js#20463]
# Bug report

## Describe the bug

Start from 10.0.2, build failed with error:  
Cannot find module 'babel-plugin-macros' from '...' at Array.map (<anonymous>)
Build failed because of webpack errors
    at build (.../.yarn/$$virtual/next-virtual-74af85fe1c/0/cache/next-npm-10.0.2-3725094149-6f964e8119.zip/node_modules/next/dist/build/index.js:15:918)

## To Reproduce
Using Yarn Berry Workspaces
```
// package.json
{
  ...,
  "dependencies": {
    "@emotion/babel-preset-css-prop": "^10.0.27",
    "@emotion/core": "^10.0.35",
    "@emotion/styled": "^10.0.27",
    "@emotion/styled-base": "^10.0.31",
    "aws-amplify": "^3.3.4",
    "bezier-easing": "^2.1.0",
    "classnames": "^2.2.6",
    "core-js": "^3.6.5",
    "intersection-observer": "^0.12.0",
    "next": "10.0.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-spring": "next",
    "tailwindcss": "^1.8.10",
    "twin.macro": "^1.10.0",
    "zustand": "^3.1.3"
  },
  "devDependencies": {
    "@mdx-js/react": "^1.6.18",
    "@storybook/addon-actions": "^6.0.22",
    "@storybook/addon-docs": "^6.0.22",
    "@storybook/addon-essentials": "^6.0.22",
    "@storybook/addon-links": "^6.0.22",
    "@storybook/addons": "^6.1.11",
    "@storybook/cli": "^6.0.22",
    "@storybook/react": "^6.0.22",
    "@types/node": "^14.11.2",
    "@types/react": "^16.9.49",
    "babel-loader": "^8.1.0",
    "babel-plugin-macros": "^2.8.0",
    "react-is": "^16.13.1",
    "react-svg-loader": "^3.0.3",
    "typescript": "^4.1.3"
  }
}
```

## System information

- OS: macOS
- Version of Next.js: 10.0.2 ~ latest
- Version of Node.js: 14.4.0

**Comment by IRediTOTO** [comment]
just need `npm i babel-plugin-macros'`

**Comment by juuyan** [comment]
@IRediTOTO 
It is installed already...
![image](https://user-images.githubusercontent.com/48427014/103135304-5494cd00-46f2-11eb-83e2-0ae47a06e541.png)
And if it was because of missing dependency, it should have reported err in early version, isn't it?

**Comment by IRediTOTO** [comment]
You build on server, right? Lets try move it to dêpndencies not dev
