### ISSUE TITLE
Cannot deploy on Google Cloud

### ISSUE THREAD

**Issue by ollydixon** [vercel/next.js#20472]
Running the following command ```rm -rf ./build && npm run build && y | gcloud app deploy --project cyberpunk-2077 app.yaml```

Get the following
```The directory [build/cache/next-babel-loader] has too many files```

I have to run with node 10 btw. Because Google flex environment doesn't support min_instances properly (slow demo's for sales)

Any ideas? We're stuck now. QA department supposed to be testing on Monday 🙈

**Comment by Timer** [comment]
You should be able to skip deployment of the `.next/cache` folder.
