### ISSUE TITLE
with-google-analytics double tracks page views

### ISSUE THREAD

**Issue by cly** [vercel/next.js#20549]
# Bug report

## Describe the bug

with-google-analytics example double counts page_views. The code
``` 
const router = useRouter()
  useEffect(() => {
    const handleRouteChange = (url) => {
      gtag.pageview(url)
    }
    router.events.on('routeChangeComplete', handleRouteChange)
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange)
    }
  }, [router.events])
```
is not necessary.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to with-google-analytics example and run it.
2. Enable Chrome Extension: GA Debugger
3. Look at Google Analytics events.
4. See 
![image](https://user-images.githubusercontent.com/314215/103242223-56d17400-490a-11eb-87a0-52e61f80f387.png)

## Expected behavior

Page views are tracked once.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 10.0.1]
- Version of Node.js: [e.g. 12.0.0]
- Deployment: [e.g. next start, next export, Vercel, other platform]

**Comment by valse** [comment]
Hi, take a look to the example using [react-ga ](https://github.com/vercel/next.js/blob/master/examples/with-react-ga/pages/_app.js).

The Chrome extension add a query string that is the cause of the issue: check for it on `App` component mount.

**Comment by frankjwu** [comment]
I'm having this same issue -- @cly did you find a solution for this?

**Comment by cly** [comment]
I just removed unnecessary `useEffect`.

**Comment by frankjwu** [comment]
Ah yep, that worked -- thanks @cly

**Comment by justincohan** [comment]
Some extra info for anyone running into this issue.  It looks like with the newer GA- tracking ids the useEffect router handling isn't needed.  But for the older UA- tracking id's it is.
