### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by taoqf** [vercel/next.js#20626]
# Bug report

## Describe the bug

```log
Error: xxx:Invalid page config export found. Expected object but got TSAsExpression in file /src/pages/index.tsx. See: https://err.sh/vercel/next.js/invalid-page-config
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create page index.tsx
2. Add page component.
3. Add page config like this:
  ```ts
  import { PageConfig } from 'next';
  export const config = {
  } as PageConfig;
  ```
5. Change the config to:

  ```ts
  export const config: PageConfig = {
  };
  ```
  
6. Error is gone.

## System information

- OS: Debian
- Browser (if applies) Chromium
- Version of Next.js: 10.0.4
- Version of Node.js: 15.5.0
- Develop: next dev
- TypeScript:4.1.3

**Comment by lachlanjc** [comment]
I don't know how Typescript is playing into this, but the error mentions that the config object can't be dynamically modified: https://github.com/vercel/next.js/blob/master/errors/invalid-page-config.md#possible-ways-to-fix-it

**Comment by taoqf** [comment]
I tried compile them with ts, and the compiled js is exactly same.

a.ts

```ts
import { PageConfig } from 'next';

export const config = {
} as PageConfig;
```

b.ts

```ts
import { PageConfig } from 'next';

export const config: PageConfig = {
};
```

a.js

```js
"use strict";
exports.__esModule = true;
exports.config = void 0;
exports.config = {};
```

b.js

```js
"use strict";
exports.__esModule = true;
exports.config = void 0;
exports.config = {};
```
