### ISSUE TITLE
Page aliases for i18n. /en/about-us => /de/ueber-uns

### ISSUE THREAD

**Issue by ottovw** [vercel/next.js#20665]
# Feature request

## Is your feature request related to a problem? Please describe.

The current i18n implementation works great with prefixing. However it's a problem if you want to translate the page-name itself. Which has effects on UX and SEO.
E.g.
`/en/about-us`
should be in german
`/de/ueber-uns`

## Describe the solution you'd like

To solve this, I'd like to define page-name aliases per locale.

## Describe alternatives you've considered

It can be solved with custom routing, but this breaks the easy usage of i18n.

**Comment by dmudro** [comment]
Yes please.

**Comment by dmudro** [comment]
@ottovw what's your current workaround; custom routes for Next/Link (to generate `/de/ueber-uns` in html)  with URL rewrites (to interprate is as `/de/about-us` under the hood)?
