### ISSUE TITLE
tree-shaking doesn't drop certain unused values

### ISSUE THREAD

**Issue by noslouch** [vercel/next.js#20804]
**What version of Next.js are you using?**

10.0.4

**What version of Node.js are you using?**

12.18.1

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

n/a

**Describe the Bug**

When creating a production build, values that are accessed at a static object path are not dropped.

**Expected Behavior**

I'd expect any value that doesn't have a viable codepath to be dropped from the final output.

**To Reproduce**

https://github.com/noslouch/test-next-tree-shaking

Given a next route that looks like this:
```js
const nested = {
  foo: {
    bar: 'NESTED: should be here',
    baz: {
      qux: 'NESTED: should not be here'
    }
  },
};

export default function Home() {
  return nested.foo.bar
}
```
I would expect `NESTED: should not be here` to be dropped from the bundle, because `nested.foo.baz.qux` is not referenced anywhere. But if I look in the built chunk, I see it:
![image](https://user-images.githubusercontent.com/2090382/103727073-58550900-4fa8-11eb-9bec-26eeb657585b.png)

Compare that with referencing a value that isn't nested:
```js
const top = {
  foo: 'TOP: should be here',
  bar: {
    baz: 'TOP: should not be here',
  }
};

export default function Home() {
  return top.foo;
}
```
As you can see, `TOP: should not be here` is absent from the output, as expected:
![image](https://user-images.githubusercontent.com/2090382/103727120-7fabd600-4fa8-11eb-8b96-ddc768afbf20.png)

This was a conventional app created with `create-next-app`. I believe the issue is that the terser plugin is not configured to do more than one pass.

**Comment by noslouch** [comment]
Note you can see the expected behavior if you update terser by hand in `next.config.js`
```js
module.exports = {
  webpack(config) {
    config.optimization.minimizer[0].options.terserOptions.compress.passes = 2;
    return config;
  }
}
```

**Comment by noslouch** [comment]
another way that might be nicer for end users who need custom terser options (like `global_defs`)...

maybe open up a mechanism to pass in custom `terserOptions` from `next.config.js` that can be deep merged with the `terserOptions` specified in the source?

**Comment by kdy1** [comment]
I think this is fixed. Can you try the latest version?

**Comment by kdy1** [comment]
Closing as it's fixed in next 13 and the repro is using next@10
