### ISSUE TITLE
add supprort for snowpack for speed

### ISSUE THREAD

**Issue by zakiAzfar** [vercel/next.js#20847]
**Describe the feature you'd like to request**

next js compilation is slow so we want fast compilation

**Describe the solution you'd like**

please add support of snowpack over webpack because snowpack is very fast.

**Describe alternatives you've considered**

snowpack

**Comment by odc-john** [comment]
https://www.snowpack.dev/guides/server-side-render will solve dev friendliness problem. i was about to just create more own ssr framework if nextjs doesn't do this
