### ISSUE TITLE
Custom path for pages

### ISSUE THREAD

**Issue by mikeborozdin** [vercel/next.js#20980]
**Describe the feature you'd like to request**

Next.js generates routes based on file names in the `./pages` folder, a.k.a. `./pages/info.tsx` will be available on `/info` URL.

There are situations when you want a path to be different from the URL. 

For example, you may want to have a URL `https://my-website.io/app` that would present a web page about a mobile app, but you would not want a file to be called `./pages/App.tsx` because it will create a confusion between it and `./pages/_app.tsx`. 

Of course, you can use a custom server. But it sounds like a heavy-weight solution that would also prevent from deploying to Vercel.

**Describe the solution you'd like**

A better option would be to provide declarative routing. And there are two options for that:

* Co-locate routing information with a page component. For instance, add a new `static` method to the class component:

```tsx
class MyPageComponent extends PureComponent {
  
  static getRoute() {
    return 'different-route';
  }
}
```

* Provide mapping between paths and components in a separate file - `./pages/_routes.json`:

```json
{
  "different-route": "./my-page.tsx"
}
```

**Describe alternatives you've considered**

Of course, you can use a custom server. But it sounds like a heavy-weight solution that would also prevent from deploying to Vercel.

**Comment by lachlanjc** [comment]
You don't need a custom server — you can accomplish this already with rewrites: https://nextjs.org/docs/api-reference/next.config.js/rewrites
