### ISSUE TITLE
ios10，the page is blank

### ISSUE THREAD

**Issue by murongzi** [vercel/next.js#20998]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12.7.0

**What browser are you using?**

Safari

**What operating system are you using?**

ios10

**How are you deploying your application?**

next dev

**Describe the Bug**

Create a project by 'create-next-app'

Run 'npm run dev'

Access the page through the ios  Safari

The page is blank

And the safari's Developer Tools Console displays an error message

ReferenceError: Can't find variable: runtime_1 

**Expected Behavior**

The page render the default content

**To Reproduce**

npx create-next-app

npm run dev

**Comment by gmjjatin** [comment]
Getting same issue

**Comment by jacklaurencegaray** [comment]
Getting the same issue as well on iOS 10 Safari.

**Comment by sgtpenguin** [comment]
@timneutkens Why is it not actionable?

**Comment by timneutkens** [comment]
> @timneutkens Why is it not actionable?

No clear reproduction was given. The steps provided result in a working app.

**Comment by sgtpenguin** [comment]
In my case it turned out react-spring was causing the problem, not next.js.  I ended up removing spring from the project.

**Comment by mattdwardle** [comment]
I am getting the same issue and I have found the variable and where the error is coming from in the @next/react-refresh-utils/internal/helpers.j file. It seems to be happening with slightly older safari browsers.
