### ISSUE TITLE
[i18n] allow overloading the way the locale is detected

### ISSUE THREAD

**Issue by hohl** [vercel/next.js#21042]
**Describe the feature you'd like to request**

The ability to overload the way the locale is detected when visiting `/`.

**Describe the solution you'd like**

As of now, the i18n implementation picks the locale based on the `Accept-Language` header, but I guess there would be quite a variety of other ways to detected that and different use cases might have different requirements on this one. Some might want to use the Maxminds GeoIP database while others have the option to rely on special HTTP headers provided by their CDN network (Cloudflare). An easy solution would be to provide some overloadable function (for example as a method in the`_app.tsx` which takes the request as input and returns the locale as string) to let everybody implement their own solutions.

**Describe alternatives you've considered**

Not really applicable to this feature request.

**Comment by sebastian-nowak** [comment]
I think you can already do that by disabling automatic locale detection and adding your own redirection logic at the beginning of `pages/index.js`. Haven't tried that, but I believe it should be easy to do.
