### ISSUE TITLE
[next/image] Disable auto webp.

### ISSUE THREAD

**Issue by myWsq** [vercel/next.js#21104]
**Describe the feature you'd like to request**

The format of the image is not in the url parameter, which makes it tricky to access the CDN. Could you provide an option to disable auto webp?

**Describe the solution you'd like**

```js
module.exports = {
  images: {
    webp: false
  },
}
```

**Describe alternatives you've considered**

_No response_

**Comment by timneutkens** [comment]
There is no clear benefit in providing such an option.

> makes it tricky to access the CDN

CDNs support serving content in webp so this shouldn't be a problem.

**Comment by thesiti92** [comment]
thats not what hes saying. hes saying if you use a cdn then it will cache webp images and serve it to older browsers like safari because theres no image format in the url.

**Comment by avisra** [comment]
This ticket needs to be opened back up. it is 100% valid @timneutkens.

NextJS delivers webp format automatically. For those of us using a CDN (like Cloudflare), it will cache those assets from the origin. Which then causes non-webp-supporting browsers (Safari on Mac) to not render images.

We should be able to instruct next/image to not convert to webp so we can allow our CDN to do it.
