### ISSUE TITLE
Redirects not working 

### ISSUE THREAD

**Issue by willvlad** [vercel/next.js#21116]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12.20.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next start

**Describe the Bug**

Redirects not working at all. Here is my next.config.js:
```
const withPlugins = require("next-compose-plugins");
const withImages = require("next-images");
const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");
const webpack = require("webpack");
const path = require("path");
require("dotenv").config();

const cssConfig = {
  cssLoaderOptions: {
    url: false,
  },
};

module.exports = withPlugins([[withSass], [withCSS, cssConfig], [withImages]], {
  trailingSlash: true,

//nothing happens here, it still stays on /int-xxx:
  async redirects() {
    return [
      {
        source: "/int-xxx",
        destination: "/international-xxx", 
        permanent: true,
      },
    ];
  },

  webpack(config, { isServer }) {
    const env = Object.keys(process.env).reduce((acc, curr) => {
      acc[`process.env.${curr}`] = JSON.stringify(process.env[curr]);
      return acc;
    }, {});

    if (isServer) {
      require("./scripts/generate-sitemap");
    }

    config.plugins.push(new webpack.DefinePlugin(env));
    config.resolve.modules.push(path.resolve("./"));
    return config;
  },
});

```
Nothing obvious springs out from the above so looks like a bug of redirects implementation. Didn't work in 9.5.0 either.

**Expected Behavior**

Redirects should be working

**To Reproduce**

Run a nextjs site as above

**Comment by apollonian** [comment]
Do not notice anything wrong with the `redirects` config here. Could you try replacing `permanent: true` with `statusCode: 308` and see if that helps.

**Comment by willvlad** [comment]
@apollonian thanks, 308 hasn't made any difference, unfortunately
