### ISSUE TITLE
Must use import to load ES Module (using ky/ky-universal library)

### ISSUE THREAD

**Issue by matveychuk** [vercel/next.js#21244]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

14.15.4

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

localhost

**Describe the Bug**

When trying to use ky/ky-universal with the newly created Next.js app receive such error:
Error: Must use import to load ES Module: /Users/---/node_modules/ky-universal/index.js
require() of ES modules is not supported.
require() of /---/node_modules/ky-universal/index.js from /---/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /---/node_modules/ky-universal/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /---/node_modules/ky-universal/package.json.

Packages version:
Node 14.15.4,
"dependencies": {
    "ky": "^0.26.0",
    "ky-universal": "^0.9.1",
    "next": "10.0.5",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  }
  
  Code extract
```
import ky from "ky-universal";

export default function Home() {
  const fetchData = async () => {
    const res = await ky
      .get("https://jsonplaceholder.typicode.com/todos/1")
      .json();
    setData(res);
    console.log(res);
  };
```
Maintainers of ky state that "This package(ky/ky-universal) is correctly set up for ESM, so Next.js is doing something wrong."

**Expected Behavior**

Possibility to fetch data with ky library

**To Reproduce**

Create new Next.js app, add ky and ky-universal and try to do any HTTP request.

**Comment by Sandreu** [comment]
Hello,
Same problem here.... This is painful !
My guess is that Next transpiles code to ES5 with webpack, excluding node_modules files.
So Ky is "require"(d) from your transpiled page file in .next instead of "import"(ed) (as it's a type:module...)

I'm looking into it.... but I can't find a smatter way to do it than add ky to the transpiling list of webpack...

**Comment by Sandreu** [comment]
Same as #21243
