### ISSUE TITLE
Image Component is not resizing based on device screen sizes with Tailwind CSS

### ISSUE THREAD

**Issue by allabouttech0803** [vercel/next.js#21466]
**What example does this report relate to?**

Image Component

**What version of Next.js are you using?**

10.0.1

**What version of Node.js are you using?**

14.0.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Linux

**How are you deploying your application?**

next start

**Describe the Bug**

Images are not resized when using in Smaller device screen

**Expected Behavior**

The image loaded in smaller screens should be with w=640

**To Reproduce**

Please visit this page : https://www.universal-tutorial.com/angular-tutorials/angular-typography

Hello,

We would like to thank you for amazing work done on the Image component, we have moved our blog pages to Next.js with Tailwind to benefit all the good features, but for some reason we are having issue in utilizing the default Image component from the Next.js

We have used the Image component as below

```
<Image
    src="/static/angular-tutorials/angular-typography/angular-typography-banner.png"
    alt="Angular Typography"
    layout='responsive'
    width={2560}
    height={1440}
    className="rounded-lg"
    />
```
But when we open the pages in small screen mobile devices, we are still seeing the image URL is referred as 

https://res.cloudinary.com/universal-tutorial/f_auto,c_limit,w_1920/universal-tutorial.com/angular-tutorials/angular-typography/angular-typography.png

But we were expecting as w=640 and due to this reason we are getting page speed index is dropped in web.dev as well 
with warning Properly size images (Serve images that are appropriately-sized to save cellular data and improve load time)

![image](https://user-images.githubusercontent.com/34211469/105574961-0117ac80-5d8e-11eb-8deb-8d31cd27a3ce.png)

To reproduce the error you can visit this page : [https://www.universal-tutorial.com/angular-tutorials/angular-typography](https://www.universal-tutorial.com/angular-tutorials/angular-typography)

**Comment by asoutheastasiandessert** [comment]
Same issue for me as well. On thickskin.sg, nextjs is showing a responsive width of 1920 for the mobile version of my hero image.
![image](https://user-images.githubusercontent.com/73132254/122681818-c3c62680-d228-11eb-9cc0-46c2ca3dd148.png)

**Comment by mah51** [comment]
I am having the same problem^

**Comment by lachlanjc** [comment]
The new image component should work much better with Tailwind/className-based styling!

**Comment by leerob** [comment]
Agreed, please give it a shot and let us know. If you are still seeing an issue, if you could open a new issue with a reproduction that would be amazing 🙏 

https://nextjs.org/docs/basic-features/image-optimization
