### ISSUE TITLE
CssSyntaxError in obscure cases when using SCSS and assetPrefix is set

### ISSUE THREAD

**Issue by jleclanche** [vercel/next.js#21461]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

15.6.0

**What browser are you using?**

-

**What operating system are you using?**

Linux

**How are you deploying your application?**

-

**Describe the Bug**

Weird error with postcss, only when using `assetPrefix`.

**Expected Behavior**

No error

**To Reproduce**

You will need the following files:

```
.
├── next.config.js
├── package.json
└── src
    ├── assets
    │   └── test.png
    └── pages
        ├── index.jsx
        └── styles.module.scss
```

`next.config.js`:
```js
module.exports = {
        assetPrefix: "https://example.com/",
};
```

`package.json`:
```
{
	"name": "test-nextjs-bug",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"dev": "next dev",
		"build": "next build",
		"start": "next start"
	},
	"dependencies": {
		"next": "10.0.5",
		"react": "^17.0.1",
		"react-dom": "^17.0.1",
		"sass": "^1.32.4"
	}
}
```

`src/pages/index.jsx`:
```jsx
import styles from "./styles.module.scss";
const IndexPage = () => <div className={styles.test} />;
export default IndexPage;
```

`styles.module.scss`:
```
.test {
	background: center / auto, url(../test.png);
}
```

Anything in `src/test.png`.

Run `yarn build`

The build fails when webpack tries to run postcss on the scss in question:

```
yarn run v1.22.10
$ next build
info  - Creating an optimized production build  
Failed to compile.

CssSyntaxError: <css input>:2:1: Unclosed bracket
  1 | .test {
> 2 |   background: center / auto, url(../test.png);
    | ^
  3 | }
  4 | 


> Build error occurred
Error: > Build failed because of webpack errors
```

Notes:
- The issue happens regardless of whether we're using an SCSS module, or a global SCSS file.
- The issue happens regardless of newlines/indentation in the SCSS file.
- The issue **does not** happen if we use plain CSS files instead of SCSS.
- The issue **does not** happen if we change `../test.png` to `/test.png`.

While debugging this, I found issue postcss/postcss-scss#84 which was fixed in 2018, and triggers the same error in a suspiciously similar part of the code. [Here](https://github.com/postcss/postcss-scss/blob/bda653f2549a24afe9e5509d4a0e2f999adc8099/lib/scss-tokenize.js#L174) is some relevant code which fixed the issue back then and it's uncertain if it's triggering it again.

I've been unable to completely reduce the css property from the original I triggered the bug with. It seems first slash in center / auto before the url() is required to trigger it. I can't quite tell if `background: center / auto, url(../test.png);` is actually the exact input we are feeding to postcss.

### Why file this issue here instead of in postcss?

I've not been able to reproduce the issue using postcss directly yet, and it's almost 6.30 am. My main concern is that this **only** triggers when `assetPrefix` is set to a URL. The fact it says `CssSyntaxError: <css input>:2:1: Unclosed bracket` tells me NextJS may be doing some post-processing of the input iff assetPrefix is set. Furthermore, NextJS is using inlined versions of postcss in various places and I suspect it could be a bug in one of those.

**Comment by ai** [comment]
Try to use stack trace and find the JS source of the error. Then put `console.log` (or use a proper debugger) to find the original source.

PostCSS can show not the input, but source map content in error messages. It could lead to misunderstanding (if we will find the source of the problem, we can change PostCSS error output).

**Comment by jleclanche** [comment]
@ai I couldn't figure out how to get a better stack trace than that. I'm going to try to dig into it a bit more today. I agree with you though, my first instinct was telling me maybe nextjs is inserting some sort of placeholder for the asset prefix which is screwing with the syntax downstream, and postcss is showing the sourcemapped input. It would also explain discrepancies in the line numbers I noticed while debugging it.

**Comment by jleclanche** [comment]
Does look like that's the case, because if I remove `css-loader/dist/cjs.js` from the loaders, it looks like feeds `.test{background:center/auto,url(../assets/test.png)}` to `next/dist/compiled/postcss-loader/cjs.js`.

**Comment by jleclanche** [comment]
@ai Is it possible the `RE_BAD_BRACKET` fix you implemented in postcss-scss is confused by the leading `.` characters in the relative path?

**Comment by jleclanche** [comment]
I tried to get this to reproduce in a clean project without next.js, just with webpack, and I can't get it to. The config is pretty complex to reduce and replicate so I'm gonna have to give up from there. I did further reduce the required input to create the issue to `.test {background: center / auto, url(../test.png);}`, and I suspect it does need to be minified on a single line like so in order to produce the error, but something else in the nextjs pipeline is doing the minification.

**Comment by ai** [comment]
@jleclanche hard to say. We are using real-world CSS-s to test the PostCSS SCSS parser, so it should parse the popular `url(./path)` construction.

But if you will find simple CSS to reproduce, it will be able to fix the parser.

Try to put catch the error directly in `postcss-scss` parser.

**Comment by JanKaifer** [comment]
Hi, thanks for taking the time to post the content of your reproduction example tiles.
It would be a way easier for us to dig into this if you posted a link to the reproduction repo instead (a repo we can clone and run).

We will close this unless someone posts a full reproduction. It's a very old issue and it's probably already fixed.

**Comment by jleclanche** [comment]
@JanKaifer The root issue isn't even in NextJS, it's very likely in postcss-scss. You can close it if you don't want to track this, but to create a proper repro case which triggers the problem in the postcss parser/output is going to be difficult. All the info I could get is in this issue though, it was a difficult one to track down.

**Comment by jleclanche** [comment]
If I have time tonight I'll try to see if it still happens in next13. I suspect the switch from the old webpack system may have "fixed" it.

**Comment by JanKaifer** [comment]
Thanks, that would be helpful.

Also, could you publish that project to GitHub if you are able to reproduce it?
It will save us a lot of time trying to debug/track this (so wee don't need to copy the code from the issue description).

**Comment by JanKaifer** [comment]
@jleclanche After discussion with other maintainers: We probably don't want to track this.
We are trying to clean up our backlog of issues.

If you find an actual bug in next.js please open a new issue.

**Comment by jleclanche** [comment]
https://github.com/jleclanche/nextjs-issue-21461

I'm able to reproduce on NextJS 10, 11, 12, and latest 13.0.5.

As of NextJS 12, the error contains a much more useful traceback, by the way:


```
HookWebpackError: /home/adys/nextjs-issue-21461/static/css/74ad6527fd15c500.css:1:47: Unclosed bracket
    at makeWebpackError (/home/adys/nextjs-issue-21461/node_modules/next/dist/compiled/webpack/bundle5.js:45539:9)
    at /home/adys/nextjs-issue-21461/node_modules/next/dist/compiled/webpack/bundle5.js:29467:12
    at eval (eval at create (/home/adys/nextjs-issue-21461/node_modules/next/dist/compiled/webpack/bundle5.js:140927:10), <anonymous>:34:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
CssSyntaxError: /home/adys/nextjs-issue-21461/static/css/74ad6527fd15c500.css:1:47: Unclosed bracket
    at Input.error (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/input.js:123:16)
    at ScssParser.unclosedBracket (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:514:22)
    at ScssParser.other (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:139:35)
    at ScssParser.parse (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:59:16)
    at scssParse (/home/adys/nextjs-issue-21461/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:335)
    at new LazyResult (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/lazy-result.js:122:16)
    at Processor.process (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/processor.js:33:12)
    at CssMinimizerPlugin.optimizeAsset (/home/adys/nextjs-issue-21461/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:43:12)
    at /home/adys/nextjs-issue-21461/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:77:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
caused by plugins in Compilation.hooks.processAssets
CssSyntaxError: /home/adys/nextjs-issue-21461/static/css/74ad6527fd15c500.css:1:47: Unclosed bracket
    at Input.error (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/input.js:123:16)
    at ScssParser.unclosedBracket (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:514:22)
    at ScssParser.other (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:139:35)
    at ScssParser.parse (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/parser.js:59:16)
    at scssParse (/home/adys/nextjs-issue-21461/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:335)
    at new LazyResult (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/lazy-result.js:122:16)
    at Processor.process (/home/adys/nextjs-issue-21461/node_modules/postcss/lib/processor.js:33:12)
    at CssMinimizerPlugin.optimizeAsset (/home/adys/nextjs-issue-21461/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:43:12)
    at /home/adys/nextjs-issue-21461/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:77:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Interestingly, i was initially unable to reproduce in NextJS 13. It looked like it was not generating the css at all! It was weird, as I looked in the generated code and it did generate the class but did not generate the underlying css. I've had to add a container to force it to reproduce the issue.

Finally, I upgraded sass from 1.32.4 to 1.56.1 (latest as of today) and I can still reproduce the issue.

I have pushed each repro case as individual commits in that repo. I'll try harder to dig into it later tonight.

**Comment by jleclanche** [comment]
@ai I managed to get the generated css from the file.

```css
.styles_container__PmjAL{background:red;width:100px;height:100px}.styles_test__zNcwj{background:center/auto,url(https://example.com/_next/static/media/test.ef46db37.png)}
```

`postcss.process()` on that css appears to fail.

**Comment by jleclanche** [comment]
Identified the issue. Moved to https://github.com/postcss/postcss-scss/issues/142
