### ISSUE TITLE
@next/react-refresh-utils missing main in package.json

### ISSUE THREAD

**Issue by merrywhether** [vercel/next.js#21483]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

12.13

**What browser are you using?**

All

**What operating system are you using?**

macOS

**How are you deploying your application?**

Self-hosted custom server implementation

**Describe the Bug**

The `@next/react-refresh-utils` package is missing the `main` field in its package.json. This means that Node can't resolve the package (`MODULE_NOT_FOUND`). This is relevant for apps that target older browsers (Chromium 38 in this case) during development since this package requires down-transpiling for compatibility (arrow functions in `ReactRefreshWebpackPlugin.js`), and the common community solution [next-transpile-modules](https://github.com/martpie/next-transpile-modules/releases/tag/5.0.0) reasonably switched to using normal `require.resolve`-like logic for finding targets, meaning that `main` fields are now required for it to work.

`@next/react-dev-overlay` is similarly missing a `main` entry, but it is arrow-free for now so hasn't caused a problem.

**Expected Behavior**

`@next/react-refresh-utils` (and maybe `@next/react-dev-overlay` for future-proofing) should have a `main` entry in its `package.json`.

Adding `"main": "runtime.js",` (via `patch-package`) works, though it's a rather random choice. There are a couple of different strategies that would satisfy this (throwaway `main` like above, `index.js` barrel, etc).

I guess an alternative solution would be to build `@next/react-refresh-utils` so that `ReactRefreshWebpackPlugin.js` does not contain arrow functions, but allowing for resolution addressability allows for Next's targets to move independently from that of its consumers. There also might be other reasons to use similar `require.resolve` functionality that I haven't thought of but that would similarly benefit from this change.

**To Reproduce**

Easiest way to test is just starting the Node REPL and attempting to use `require.resolve` on the package.

```
$ node
Welcome to Node.js v12.13.0.
Type ".help" for more information.
> require.resolve('@next/react-refresh-utils')
Thrown:
Error: Cannot find module '@next/react-refresh-utils'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
```
with my patch:
```
> require.resolve('@next/react-refresh-utils')
'<repo_dir>/node_modules/@next/react-refresh-utils/runtime.js'
```

**Comment by timneutkens** [comment]
There is no `main` needed:

<img width="587" alt="Screen Shot 2021-01-27 at 12 33 56" src="https://user-images.githubusercontent.com/6324199/105985617-f9ad1780-609b-11eb-81b3-8a6e290b287b.png">

`ReactRefreshWebpackPlugin` is not meant to run in the browser so I'm not sure how that related to what you're trying to do.

Overall this is not a bug in Next.js, sound like you're trying to do something non-standard / unsupported.
