### ISSUE TITLE
Site only builds a 404 page on Mac but works fine on Windows

### ISSUE THREAD

**Issue by Southclaws** [vercel/next.js#21548]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

v15.6.0

**What browser are you using?**

Chrome, FireFox

**What operating system are you using?**

macOS

**How are you deploying your application?**

next build, next dev

**Describe the Bug**

I usually develop on Windows, and the site has been going well for a while with no issues. I'm fairly certain the rest of the team use Windows too (will have to clarify) but today I fired up my Macbook and wanted to get the development environment set up and found the site doesn't build correctly.

I first ran `npm run dev` and loaded up `localhost:3000` to find the Next.js generic 404 page. All other pages did the same.

Then I ran `npm run build` and this was the result:

```
web/frontend on  master [!] via ⬢ v15.6.0 took 12s 
❯ npm run build

> frontend@0.1.0 build
> next build

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
cache data for documentation pages has been created.
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (31/31)
info  - Finalizing page optimization  

Page                             Size     First Load JS
─ ○ /404                         2.78 kB        66.7 kB
+ First Load JS shared by all    63.9 kB
  ├ chunks/commons.c56a5d.js     14.1 kB
  ├ chunks/framework.2d84bb.js   41.6 kB
  ├ chunks/main.8669cb.js        6.46 kB
  ├ chunks/pages/_app.50343b.js  1.01 kB
  └ chunks/webpack.50bee0.js     751 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
```

Instead of what is normally output on Vercel and Windows, which is all the pages [here](https://github.com/openmultiplayer/web/tree/master/frontend/src/pages) and all the dynamic routes (around ~1000) pre-rendered.

Here's the latest version output from `master` branch, I'm fairly certain this Vercel project is public: https://vercel.com/openmultiplayer/web/c4w237cen

**Expected Behavior**

I assumed it would build the same on both OSes. I used to develop on mac all the time with no issues and switched to Windows with no issues but for some reason switching back has revealed something not quite right about either Next.js itself or our setup.

**To Reproduce**

Clone https://github.com/openmultiplayer/web onto a Mac machine, `cd frontend`, and `npm run build`.

The output should match what's on that Vercel log above, but instead it seems to just build a 404 page and nothing else.

**Comment by JanKaifer** [comment]
Hi, thanks for reaching out.
We haven't looked into this because your repo is very large and It would take us a lot of time to find the issue.

Could you provide a minimal example that you are able to reproduce?
Ideally created with `npx create-next-app --example reproduction-template reproduction-app`.

**Comment by Southclaws** [comment]
Hey, given this one is almost 3 years old and 3 major versions behind, it's probably safe to assume it's not an issue any more. All my sites are running fine currently. Thanks!
