### ISSUE TITLE
.env variables not working in development

### ISSUE THREAD

**Issue by obolland** [vercel/next.js#21541]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

15.4.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

Vercel

**Describe the Bug**

I have a local project and I cannot get .env files to load.

.env.local
`NEXT_PUBLIC_CODE=1234`

example.js
```
const Example = () => { return <h1>My code is {process.env.NEXT_PUBLIC_CODE}</h1> }
export default Example;
```

Have also tried loading them into a node environment, with and without the 'NEXT_PUBLIC_' prefix and they are undefined.

Any ideas?

**Expected Behavior**

I expected the .env variables to load.

**To Reproduce**

.env.local
`NEXT_PUBLIC_CODE=1234`

example.js
```
const Example = () => { return <h1>My code is {process.env.NEXT_PUBLIC_CODE}</h1> }
export default Example;
```

I have a more complicated project then the example above, and noticed the issue when I began integrating authentication.
However I have simplified it and run only the example above and the variable remains undefined.
If I install dotenv via npm then I can create a .env file and load the variable successfully, however this introduces other errors.

**Comment by timneutkens** [comment]
<img width="442" alt="Screen Shot 2021-01-27 at 12 40 57" src="https://user-images.githubusercontent.com/6324199/105986244-f1a1a780-609c-11eb-9986-c5078d7ff4e9.png">

Based on your reproduction this works fine so I'll convert this issue into a help discussion given it's not actionable.

You can verify if the `.env.local` is loaded in the logs. It should output:
```
Loaded env from <projectpath>/.env.local
```
