### ISSUE TITLE
next/link - Query params not passing when directing to API Routes

### ISSUE THREAD

**Issue by meko-deng** [vercel/next.js#21719]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

10.20.1

**What browser are you using?**

Safari, Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next dev

**Describe the Bug**

When using `<Link>` component from `next/link`, query parameters are being stripped when linking to API Routes.

Example:
- `<a href="api/hello?text=world" />` navigates to `https://localhost:3000/api/hello?text=world`
- `<Link href="api/hello?text=world" />` navigates to `https://localhost:3000/api/hello`
- `<Link href={{ pathname: "api/hello", query: { text: "world" }}} />` navigates to `https://localhost:3000/api/hello`

Note that when linking to a non-api page, Link behaves the way it should:
- `<Link href="home?text=world" />` navigates to `https://localhost:3000/home?text=world`

**Expected Behavior**

When navigating to an api route, the query parameters should not be stripped from the url when using Link such that:

- `<Link href="api/hello?text=world" />` navigates to `https://localhost:3000/api/hello?text=world`
- `<Link href={{ pathname: "api/hello", query: { text: "world" }}} />` navigates to `https://localhost:3000/api/hello?text=world`

**To Reproduce**

Create a basic nextjs app:

#### pages/index

```Typescript
import Link from "next/link"
import React from "react"

const Home = () => {
  return (
    <>
      <Link
        href={{
          pathname: "api/hello",
          query: { text: "world" },
        }}
      >
        1 - Link to api/hello
      </Link>
      <Link href="api/hello?text=hi">2 - Link to api/hello with href string</Link>
      <a href="api/hello?text=hi">3 - a to api/hello with href string</a>
    </>
  )
}

export default Home
```

#### pages/api/hello

```Typescript
import { NextApiRequest, NextApiResponse } from "next"

export default (_: NextApiRequest, res: NextApiResponse) => {
  const { text } = _.query
  res.status(200).json({ text: `Hello ${text}` })
}
```

run `yarn dev`, navigate to  `http://localhost:(...)` and check that only the last link works.

**Comment by balazsorban44** [comment]
I could not reproduce this on `latest` (as of writing, this is `12.0.8`). Please try upgrading.
