### ISSUE TITLE
Improve documentation for custom loaders in image component

### ISSUE THREAD

**Issue by atcastle** [vercel/next.js#21786]
I've been working with several large apps that are trying to adopt the image component, and which would benefit from the custom loader pattern. So far none of them have found it while reading the documentation, which I think is because the part about custom loaders is only in the image optimization section, while the part about picking a loader in next.config is in the main "images" section.

I'd recommend mentioning custom loaders and linking to the full documentation from the main image page.

**Comment by atcastle** [comment]
To be a little more specific, I mean mentioning custom loaders in this section: https://nextjs.org/docs/basic-features/image-optimization#loader

**Comment by leerob** [comment]
It is mentioned at the bottom: "If you need a different provider, you can use the loader prop with next/image."

Would it be more clear if it was another bullet point in that list?
