### ISSUE TITLE
Common.js chunk includes code that is not used on all pages

### ISSUE THREAD

**Issue by FBosler** [vercel/next.js#21799]
**What version of Next.js are you using?**

10.0.5

**What version of Node.js are you using?**

14.9.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next start

**Describe the Bug**

The common.js chunk for an application relying on `dynamic(import(...))` to look up components dynamically and render them based on a user input includes dependencies for all dynamic components and not only the ones used.

**Expected Behavior**

For static pages at least I would expect the tree shaking to work insofar as that it uses only code that is a direct dependency of the page to render.

**To Reproduce**

https://github.com/FBosler/fb-dynamicComponent

```
yarn install
yarn dev
NODE_ENV=production yarn build
```

Check common.js bundle on `http://localhost:3000/components/ComponentOne` and note how `victory.js` is also included or vice versa check `http://localhost:3000/components/ComponentTwo` and note how `recharts` is also included.

**Comment by JanKaifer** [comment]
Thanks for the reproduction. After bumping it to `next@canary` it works as expected :tada:.
