### ISSUE TITLE
Preview mode doesn't work on 404 error pages

### ISSUE THREAD

**Issue by vajajak** [vercel/next.js#21890]
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

12.14.1

**What browser are you using?**

Chrome 88.0.4324.96

**What operating system are you using?**

macOS 11.1

**How are you deploying your application?**

Vercel, next start

**Describe the Bug**

Preview mode doesn't work on 404 error pages when using production (`next build && next start` and on Vercel). In development (`next dev`), preview mode is available throughout the entire site (works as expected).

In my case, this production behavior causes inconsistencies in header and footer components when editors make changes to them, as on every other page in this app the changes are visible, and only on 404 pages they're not. This has already caused some confusion amongst our editors and therefore I'd like to avoid it in the future.

I can confirm that both preview mode cookies are set correctly and preview mode is working on all pages except the 404.
When I'm logging the preview property from getStaticProps on client (sent as part of a getStaticProps result to client to display preview mode indicator), I'm always getting null on 404 error page.

**Expected Behavior**

I believe that production behavior should match development behavior, so if in development we're getting working preview mode even inside 404 error pages, we should get so in production.

I expect preview mode to be activated site-wide, like it is in development.

**To Reproduce**

1. Create new Next.js project
2. Setup Preview Mode as described here: https://nextjs.org/docs/advanced-features/preview-mode
3. Start preview mode
4. Navigate to a page that does not exist

**Additional information**
This problem arises regardless of whether you're using a custom 404 or the stock 404.
You can take a look at my deployment where the issue is occuring here: https://zsjaklysa-7hzno8tjm.vercel.app/_src.

**Comment by neevannv** [comment]
This is a critical bug, am also facing same issue, hoping Next.js team will solve this issue soon.

**Comment by vajajak** [comment]
I do believe this is indeed a critical bug, am surprised this isn't getting the attention I was expecting.

**Comment by neevannv** [comment]
No sure how get attention of contributors, am posting this issue on next.js forum

**Comment by vajajak** [comment]
This is still unresolved in 10.2.2.

**Comment by vajajak** [comment]
Closing this issue as it seems to be fixed by https://github.com/vercel/next.js/issues/16681

**Comment by vajajak** [comment]
It's fixed in the newest version of the Vercel platform, it looks like it's still present on localhost with `next build && next start`, but that isn't really important for me. If it is for you, we can reopen.

**Comment by neevannv** [comment]
we are not using Vercel platform, we need this on localhost.

**Comment by vajajak** [comment]
I see, let's reopen then

**Comment by balazsorban44** [comment]
If the OP's problem is resolved, this issue is resolved then. If anyone else has a seemingly similar issue, please open a new bug report, with a reproduction.
