### ISSUE TITLE
IPv6 addresses not properly formatted when using `next dev`

### ISSUE THREAD

**Issue by byhemechi** [vercel/next.js#21979]
**What version of Next.js are you using?**

10.0.6, 10.0.7-canary.6

**What version of Node.js are you using?**

15.8.0

**What browser are you using?**

Firefox, this is a CLI issue

**What operating system are you using?**

Windows

**How are you deploying your application?**

next dev -H :: , next start -H ::

**Describe the Bug**

When running `next dev` or ` next start` with an IPv6 host parameter, the "started server" message does not format URIs correctly

```
> next dev -H ::

ready - started server on :::3000, url: http://:::3000
```

**Expected Behavior**

```
> next dev -H ::

ready - started server on [::]:3000, url: http://[::1]:3000
```

**To Reproduce**

Run `next dev` or `next start` with an ipv6 address as the `-H` parameter

**Comment by ald890** [comment]
Since version 10.0.6+
I have a similar problem but on WSL2 with Windows.
For me, it looks like Nextjs changed the default IPv6 to IPv4.

The application compiles without errors, but cannot be opened 
`http://localhost:3000` in the browser.

Change: 
`> npx next -H ::`
Fixes the bug.

**Comment by karol-f** [comment]
@chulkilee Can You please take a look as it might be related to `Fix hostname message in dev/start` You've touched?

**Comment by byhemechi** [comment]
I've had a quick glance through the code and it looks like fixing this either requires a regex hack or a minor restructure of server code.

My preferred method is to retrieve the `family` key from `http.Server.address()`. Current code architecture doesn't allow for this.

alternatively, we could use a regex. Considering that this is a low-frequency operation, it's not a huge perf issue.

```ts
const isIpv6 = host.match(/^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$/) === null;
const formattedHost = isIpv6 ? `[${host}]` : host;

startServer({ dir }, port, host)
    .then(async (app) => {
      // Check if `host` is a valid ipv6 address
      

      Log.ready(`started server on ${host}:${port}, url: ${appUrl}`)
      await app.prepare()
    })
    .catch((err) => {
      console.error(err)
      process.exit(1)
    })
```

**Comment by byhemechi** [comment]
If the regex method doesn't sound too hacky, I can send in a PR for that.

**Comment by chulkilee** [comment]
> For me, it looks like Nextjs changed the default IPv6 to IPv4

Technically, it switches from any default interface (based on nodejs) to ipv4 0.0.0.0, assuming it's the most common set up.

(I believe it's better to default to loopback interface, but that's a breaking change so the PR used 0.0.0.0)

(Also btw it's hard to know which bind addr or interface will be used **before** listening it 😞 )

To print out the correct bind url and accessible url, it needs to know how to handle and map special ip addrs - and the PR only handles ipv4. So we need to handle ipv6 as well! Probably subset of https://github.com/whitequark/ipaddr.js 

Also please note that I didn't go deep in refactoring - it seems like it's better to pass the original config, not app url for example.

**Comment by byhemechi** [comment]
I'm willing to implement this, just not too sure about introducing too many lines or changing project structure.

**Comment by JanKaifer** [comment]
Hey sorry, sorry that we missed this issue before.
The formatting is still wrong so we would love to review your PR @byhemechi (If you are still interested).

**Comment by akshitsinha** [comment]
I've implemented a fix in the above PR. @JanKaifer can you have a review?
