### ISSUE TITLE
Critical inline css is not working

### ISSUE THREAD

**Issue by glopezep** [vercel/next.js#22083]
**What version of Next.js are you using?**

latest

**What version of Node.js are you using?**

10.22

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

https://demo.vercel.store/es

**Describe the Bug**

the latest version of nextJS does not add critical styles inline, for example, I'm trying to import a CSS file in the _app component but the styles are not reflected in the first SSR request so I'm getting the response page but with no styles pre-rendered.

**Expected Behavior**

the imported styles in the _app component should be inline like previous versions. 

**To Reproduce**

An example of how to reproduce this is in the e-commerce page: https://demo.vercel.store/es, go to the network tab of google chrome and see the first SSR request you will see the response with no styles pre-rendered. but if you go to the nextJS documentation is working properly the first SSR request has its inline styles

**Comment by glopezep** [comment]
NOTE: this is a workaround creating a custom document

`
import { promisify } from 'util'
import { readFile as readFileCallback} from 'fs'
import Document from 'next/document'

const readFile = promisify(readFileCallback)

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    const result = await readFile('./node_modules/library-name/dist/index.css', 'utf-8')

    return { 
      ...initialProps,
      styles: (
        <>
          {initialProps.styles}
          <style>
            ${result}
          </style>
        </>
      )
    }
  }
}

export default MyDocument
`

**Comment by wadamek65** [comment]
I seem to be experiencing the same issue using `next@10.0.3` and `tailwindcss@2.0.2`. I've went over both Next and Tailwindcss documentation and set everything up as instructed but the styles still do not get injected and the returned document is unstyled leading to nasty styling issues.

I've also tried deploying the example project https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss which seems to suffer the exact same issue.

**Comment by timneutkens** [comment]
This is expected behavior and not a bug. Critical css extraction only happens when you use styled-jsx or other css-in-js solutions. When using css imports a stylesheet is generated.

**Comment by gio-work** [comment]
@timneutkens Would it be possible to at least add a supported solution or workaround in documentation? I've seen several [workarounds](https://github.com/vercel/next-plugins/issues/238#issuecomment-696623272) floating around, but not an officially supported solution.

With Google Lighthouse being a major focus on development these days, it is beyond critical to have a good first paint. So for a bad first paint to be "expected behavior" is a bit odd for a framework this widely used. 

Appreciate any additional insight you may have :)

**Comment by balazsorban44** [comment]
If you have suggestions, please open a discussion around it! (Ideas :bulb:)
