### ISSUE TITLE
Fast Refresh is not working in version 10.0.7 (Windows 10)

### ISSUE THREAD

**Issue by DannyFeliz** [vercel/next.js#22209]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

12.18.3

**What browser are you using?**

Chrome 88.0.4324.150 (Official Build) (64-bit)

**What operating system are you using?**

Windows 10 Pro Build 19042.804

**How are you deploying your application?**

next dev

**Describe the Bug**

I created a new project using `create-next-app` and Fast Refresh does not work. To see the changes, I have to reload the page manually. It doesn't work either in the WSL2.

It works fine if I use version 10.0.5.

**Expected Behavior**

Once I save my changes, the page should reload to reflect my changes.

**To Reproduce**

You can use this project to reproduce the issue: [next-fast-refresh-repo](https://github.com/DannyFeliz/next-fast-refresh-repo)

![fast](https://user-images.githubusercontent.com/5460365/108032878-839c3080-7009-11eb-8686-ccded067fcf2.gif)

**Comment by s4sebin** [comment]
I have the same issue
