### ISSUE TITLE
Difference between dev and Vercel build in how `req.url` handles dynamic route slugs: query is appended to URL path on Vercel, but not with next dev.

### ISSUE THREAD

**Issue by aorsten** [vercel/next.js#22234]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14.15.4

**What browser are you using?**

Firefox

**What operating system are you using?**

Windows

**How are you deploying your application?**

vercel

**Describe the Bug**

`req.url` in dynamic api routes are populated differently in `next dev` vs `vercel` prod. In dev, the `req.url` path is unchanged, while in production on Vercel, `req.url` is modified by adding the custom slugs at the end of the URL path.

Basically, visit `/api/[slug].js` and inspect `req.url`.

1. Result in dev: `/api/myslug`
2. Result in prod: `/api/myslug?slug=myslug`

**Expected Behavior**

The expected behavior is that both behave the same way, I suppose the natural thing would be that neither appended the query parameter at the end (both acting like dev does).

**To Reproduce**

1. `npx create-next-app`
2. `npm install --save swr`
3. Modify index.js:

```
import useSWR from "swr";

const fetcher = (...args) => fetch(...args).then(res => res.json())

export default function Home() {
  const { data, error } = useSWR("/api/dudeman", fetcher);

  console.log(data?.name, data?.url, error)

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;
  return <div>hello {data.name}, url was <b>{data.url}</b>!</div>;
}

```

4. Add dynamic api route `/api/[slug].js`

```
export default (req, res) => {
  const {
    query: { slug },
    url,
  } = req;

  res.status(200).json({
    name: slug || "John Doe",
    url,
  });
};
```

4. Run it in development, it prints: `hello dudeman, url was /api/dudeman!`
5. Run `vercel` to deploy to Vercel.
6. The prod version prints: `hello dudeman, url was /api/dudeman?slug=dudeman!`

**Comment by balazsorban44** [comment]
Hi, I could not reproduce this anymore. Please upgrade or open a new issue with a new reproduction if you still encounter this.
