### ISSUE TITLE
Polyfill for `process` not included with Webpack 5 and Yarn 2 PnP

### ISSUE THREAD

**Issue by jacobwgillespie** [vercel/next.js#22247]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14.15.5

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**How are you deploying your application?**

N/A

### Describe the Bug

When enabling the `webpack5` feature flag and using Yarn 2 / Plug'n'Play, the Node polyfills for things like `process` do not appear to be used, causing builds to fail for modules that reference Node built-ins like `process`.

**Configurations**

Yarn Version | `nodeLinker` | `webpack5` | Result
--- | --- | --- | ---
Yarn 1 | n/a | `false` | ✅ works
Yarn 1 | n/a | `true` | ✅ works
Yarn 2 | `node-modules` | `false` | ✅ works
Yarn 2 | `node-modules` | `true` | ✅ works
Yarn 2 | `pnp` | `false` | ✅ works
Yarn 2 | `pnp` | `true` | 🚫 broken

### Expected Behavior

I would expect PnP to not affect the inclusion of Node polyfills.

### To Reproduce

1. Use Yarn 2 with PnP
2. Use the following `next.config.js`:

    ```javascript
    module.exports = {
      future: { webpack5: true },
    }
    ```
3. Reference a Node built-in like `process` in a client file
4. Run `yarn build`

The `styled-components` npm module references `process`, so it's a good candidate module.

👉 Here is a repo demonstrating the issue, taking the `with-styled-components` example and using Yarn 2 / PnP: https://github.com/jacobwgillespie/nextjs-issue-reproduction.

**Comment by merceyz** [comment]
It's not in the list of polyfills so it correctly fails https://github.com/vercel/next.js/blob/fea5c18132146976913f4148210b74d6d9b1ef8c/packages/next/build/webpack-config.ts#L394-L398

**Comment by simnalamburt** [comment]
Is it really due to that part? Adding it to that list of polyfill didn't fixed the issue.

![image](https://user-images.githubusercontent.com/4435445/108606448-7ca46200-73fd-11eb-8285-c433f85c4fd1.png)

###### Reference
- https://github.com/simnalamburt/next-auth-example/commit/c1284953d8e13a1066f931c1ebc15563030e61a1

**Comment by merceyz** [comment]
Yes, but you need to use `require.resolve('process/')` otherwise it will just return `process` again

**Comment by simnalamburt** [comment]
That solution failed like this:

![image](https://user-images.githubusercontent.com/4435445/108606903-6350e500-7400-11eb-8c1c-2ca27e5902ec.png)

###### Refernce
- https://github.com/simnalamburt/next-auth-example/commit/2c37adf1041e373b1a97fc7215c6cfeb59eef797

**Comment by merceyz** [comment]
Ah, it has a browser field, try this:
```js
path.dirname(require.resolve('process/package.json'));
```

**Comment by simnalamburt** [comment]
I think we're getting there but it didn't worked yet, sorry.

![image](https://user-images.githubusercontent.com/4435445/108607409-a2cd0080-7403-11eb-94af-960a72d233ee.png)
