### ISSUE TITLE
Starting with 10.0.6-canary.0 'process.stderr.fd' is not available anymore

### ISSUE THREAD

**Issue by hkogge** [vercel/next.js#22277]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

v15.4.0

**What browser are you using?**

Chrome, Firefox, Safari

**What operating system are you using?**

macOS

**How are you deploying your application?**

next start

**Describe the Bug**

Starting with `10.0.6-canary.0` (we initially upgraded from `10.0.3` to `10.0.7`, but could pinpoint it to this release) there seems the have been a change which prevents access to `process.stderr.fd`.

During `next build` , code depending on the file descriptor `.fd` of `process.stderr` (and/or `process.stdout`) will throw an error, as it will be `undefined`. This is happening in a logging package (`pino`) we use to log things within `getStaticProps`. 

According to the [node.js documentation](https://nodejs.org/api/process.html#process_process_stderr_fd), this field will not exist on worker threads, so I assume this is what's happening during `next build`. 

Note the `console.log('FOOBAR', process.stderr.fd)` in the affected logging function.

```
$ yarn build:next && yarn build:server
$ next build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Loaded env from /Users/.../.env
info  - Using external babel configuration from /Users/.../.babelrc
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data ..FOOBAR 2
info  - Collecting page data  
[    ] info  - Generating static pages (0/2)FOOBAR undefined
[   =] info  - Generating static pages (0/2)
Error occurred prerendering page "/[[...slug]]". Read more: https://err.sh/next.js/prerender-error
Error: SonicBoom supports only file descriptors and files
    at new SonicBoom (/Users/.../node_modules/sonic-boom/index.js:72:11)
    at buildSafeSonicBoom (/Users/.../node_modules/pino/lib/tools.js:254:18)
    at Function.pino.destination (/Users/.../node_modules/pino/pino.js:134:50)
    at createDestination (/Users/.../node_modules/@bahn-x/node-service-logger/dist/lib/index.js:17:49)
    at Object.createLogger [as default] (/Users/.../node_modules/@bahn-x/node-service-logger/dist/lib/index.js:47:23)
    at createLogger (/Users/.../node_modules/@bahn-x/node-service-logger/dist/index.js:8:25)
    at Object.<anonymous> (/Users/.../.next/server/pages/[[...slug]].js:6752:80)
    at Object.i8L1 (/Users/.../.next/server/pages/[[...slug]].js:6758:30)
    at __webpack_require__ (/Users/.../.next/server/pages/[[...slug]].js:29:31)
    at Object.jHzV (/Users/.../.next/server/pages/[[...slug]].js:6782:72)
info  - Generating static pages (2/2)

> Build error occurred
Error: Export encountered errors on following paths:
        /[[...slug]]
    at /Users/.../node_modules/next/dist/export/index.js:30:1103
    at async /Users/.../node_modules/next/dist/build/tracer.js:1:534
    at async /Users/.../node_modules/next/dist/build/index.js:39:69
    at async /Users/.../node_modules/next/dist/build/tracer.js:1:534
    at async /Users/.../node_modules/next/dist/build/index.js:21:712
    at async /Users/.../node_modules/next/dist/build/tracer.js:1:534
error Command failed with exit code 1.
```

**Expected Behavior**

`process.stderr.fd` should be defined when code is run on the server within `getStaticProps`. 

**To Reproduce**

Access `process.stderr.fd` in your code and run `next build`.

Our current workaround is adding a check for `process.stderr.fd` before initializing our logging function:
```js
let logger;
if (process.stderr.fd) {
  logger = loggingfFn();
}
export default logger;
```
This way the build succeeds, but it feels wrong having to do that.

**Comment by balazsorban44** [comment]
Hi, this seems to have been fixed in later versions (`10.2.3` worked for me), please try to upgrade!
