### ISSUE TITLE
Link component throws "cannot read property 'push' of null" error in Storybook

### ISSUE THREAD

**Issue by NathanTrost** [vercel/next.js#22302]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14.5.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows 10

**How are you deploying your application?**

N/A

**Describe the Bug**

I've created a global component for an application which utilizes next's Link component, in setting up the styleguide on Storybook, it started to crash when Link was clicked on.  Initially this issue was with 'prefetch', and all I had to do was update to 10.0.7, but have realized that another error persists with 'push' in the browser console.  In addition to this, the link will not work.

In viewing the fix for the prefetch error, it appears just checking against window and router and returning outside of that function works fine.  This same fix appears to do the trick for me with linkClicked as well.  I've opened a PR #22303 with this fix.

**Expected Behavior**

Clicking on a component within Storybook that is using Link should direct you to the appropriately provided url, and not throw an error in the console.

**To Reproduce**

1. Create a component that uses next's Link component
2. Apply that component to a story in Storybook
3. Click on the area using Link
4. The browser will not go to your requested url
5. If you check the console, you can see a "Cannot read property 'push' of null" error.

Below is the error I recieve in the browser:
![Screenshot 2021-02-18 094259](https://user-images.githubusercontent.com/12831882/108383298-484b5e80-71cf-11eb-9059-10429e16e154.png)

**Comment by balazsorban44** [comment]
@NathanTrost as a reminder, your PR is missing a test case, thus still waiting for a review.

**Comment by balazsorban44** [comment]
Storybook just announced an addon that integrates with Next.js, and routing is part of that! Please have a look. https://storybook.js.org/addons/storybook-addon-next#nextjs-routing I'm closing this issue for now in favor of that.
