### ISSUE TITLE
Locale urls are repeating on second level of the path

### ISSUE THREAD

**Issue by timuric** [vercel/next.js#22336]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14

**What browser are you using?**

Chrome, Safari

**What operating system are you using?**

macOS

**How are you deploying your application?**

Vercel

**Describe the Bug**

Locale urls are repeating on second level of the path

https://demo.vercel.store/es/ -> Spanish, correct
https://demo.vercel.store/es/es/ -> Spanish, but should be 404
https://demo.vercel.store/es/es/es -> 404

**Expected Behavior**

https://demo.vercel.store/es/es/ -> Should be 404

**To Reproduce**

Follow link:
https://demo.vercel.store/es/es/ 

I am trying to build a url structure ```store.com/lng/country``` which would look like ```store.com/de/de``` however due to this bug its impossible to use country code.

**Comment by LuudJanssen** [comment]
Can confirm this. Created a [code sandbox](https://codesandbox.io/s/nextjs-double-locale-routing-bug-pdt5i) to demonstrate the problem. When routing to `/de/de` in the sandbox we expect to see the contents of `[language].js`, however, we're seeing the contents of `index.js`.

**Comment by timuric** [comment]
After some debugging I have managed to fix the issue by removing this ```if``` statement block
https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/next-server.ts#L941

I am not entirely sure what was the original purpose of this block, however it uses ```pathname``` to extract language code which actually never contains language code since ```pathnames``` includes path after the locale. As far as I can see it is a redundant piece of code that only has side effect with URL contains as: ```https://demo.vercel.store/es/es/ ```

**Comment by balazsorban44** [comment]
Hi, @timuric could you try upgrading to `latest` and see if this is still an issue? otherwise could you please create a reproduction I can use to investigate?
