### ISSUE TITLE
env-vars behaves as build-args by design.

### ISSUE THREAD

**Issue by skrhlm** [vercel/next.js#22343]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14.x

**What browser are you using?**

Chrome

**What operating system are you using?**

MacOs

**How are you deploying your application?**

Kubernetes

**Describe the Bug**

Simply put the `env-vars` act as build-args, it is not possible to do any override of env-variables in runtime.

**Expected Behavior**

Env-vars ( when not using export ) should not be bundled, but updatable through the environment in runtime.

**To Reproduce**

I've made a repository showcasing the frustration
https://github.com/skrhlm/NEXT-JS-ENV-VARS

**Comment by LuudJanssen** [comment]
Hi @skrhlm, I think you're looking for [Runtime Configuration](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration). This allows you to pass environment variables (through `process.env`) to runtime configuration. The reason Next.js bundles environment variables during build time by default is explained at the start of the Runtime Configuration documentation:

> Generally you'll want to use build-time environment variables to provide your configuration. The reason for this is that runtime configuration adds rendering / initialization overhead and is incompatible with Automatic Static Optimization.

**Comment by skrhlm** [comment]
Hello @LuudJanssen ! 

Thanks for your answer. You are right that that using runtime configuration does indeed work. However, I made [a new example](https://github.com/skrhlm/NEXT-JS-ENV-VARS/tree/app-get-initial-props), this time using `getInitialProps`in `_app.js` to force pages out of automatic static optimization.

This works for all examples, but the one using getStaticProps. Which makes sense since you're [unable to opt-out of static optimization when using that ](https://github.com/vercel/next.js/blob/master/errors/opt-out-auto-static-optimization.md)

However, the fact still stands that there should be a way to override the default behaviour for getStaticProps. There is still no way to get a site-wide variable through. I understand that this would add some overhead, but a simple bootstrapping process on startup should be able to handle this reasonably efficient.
