### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by popmanhe** [vercel/next.js#22355]
**What example does this report relate to?**

with-ant-design-less

**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

14

**What browser are you using?**

chrome

**What operating system are you using?**

windows 10

**How are you deploying your application?**

local

**Describe the Bug**

If upgrade webpack to v5, I got the error: TypeError: The 'compilation' argument must be an instance of Compilation.

It is working for webpack v4.44.2

**Expected Behavior**

Works with webpack v5

**To Reproduce**

1. Install "webpack": "5.23.0" in package.json
 2. Run "npm run dev"

**Comment by nazywamsiepawel** [comment]
+1, same issue here. Webpack 5.23.0 and next 10.0.3

**Comment by viniciusclerod** [comment]
+1, same issue here. Webpack 5.23.0 and next 10.0.7
