### ISSUE TITLE
Dev server doesn't work on v10.0.6 and v10.0.7 when `node_modules` is a symlink to `node_modules.nosync`.

### ISSUE THREAD

**Issue by burns-brian** [vercel/next.js#22386]
**What version of Next.js are you using?**

10.0.6-10.0.7

**What version of Node.js are you using?**

15.6.0

**What browser are you using?**

Firefox Developer Edition

**What operating system are you using?**

macOS 11.2.1

**How are you deploying your application?**

npm run dev

**Describe the Bug**

On macOS, it's a somewhat common practice to symlink `node_modules` to `node_modules.nosync` in order to keep iCloud from syncing the folder. However, starting in v10.0.6, running `npm run dev` no longer compiles successfully when the `node_modules` is a symlink to `node_modules.nosync`. The 10.0.7 version has the same issue. Running v10.0.0-v10.0.5 works just fine with a symlinked `node_modules` directory. If you don't use a symlinked `node_modules` directory, v10.0.6 and v10.0.7 work just fine.

**Expected Behavior**

- Create a symlink called `node_modules` that points to `node_modules.nosync`. 
- Install Next v10.0.6 or v10.0.7.
- Run `npm run dev`
- You should see `event - compiled successfully`
- Visit `localhost:3000` in your browser.
- Website should render successfully.

**To Reproduce**

- Create a symlink called `node_modules` that points to `node_modules.nosync`. 
- Install Next v10.0.6 or v10.0.7.
- Run `npm run dev`
- You will notice that `event - compiled successfully` never displays. 
- You might also see a message that says, `warn  - ./node_modules.nosync/node-fetch/lib/index.js` and `Module not found: Can't resolve 'encoding' in '/path/to/project/node_modules.nosync/node-fetch/lib'`
- Visit `localhost:3000` in your browser.
- You should see a message that says:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by hajiskyy** [comment]
Hi, this worked for me [#16535](https://github.com/vercel/next.js/issues/16535#issuecomment-738857277)

**Comment by burns-brian** [comment]
> Hi, this worked for me [#16535](https://github.com/vercel/next.js/issues/16535#issuecomment-738857277)

Unless I am missing something, I don't think this has anything to do with a symlinked node_modules folder.

**Comment by noughts** [comment]
same here

**Comment by oyzhen** [comment]
Same with `pnpm` and `next 10.1.3`

**Comment by Dexig** [comment]
Same with symlinked node_modules
next: 10.0.7

**Comment by noughts** [comment]
This problem was not fixed in Next.js 10.2.

**Comment by noughts** [comment]
In my environment, this problem was fixed in Next.js 11.0.1 🎉 

Here is my `package.json`.

```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "11.0.1",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "eslint": "7.29.0",
    "eslint-config-next": "11.0.1"
  }
}

```

**Comment by JanKaifer** [comment]
It looks loke this was already fixed. Closing.
