### ISSUE TITLE
Improve documentation around _app.js 

### ISSUE THREAD

**Issue by MagnusBrzenk** [vercel/next.js#22591]
**Describe the feature you'd like to request**

Just tried nextjs for first time. Found the documentation confusing. In particular, the very first question I had having generated a new project was "What is _app.js?!" Since the first section of the docs is about the pages dir, I naivley tried the extension `/_app` and, of course, that did nothing. So I quickly concluded that files beginning with underscore must mean something else, but there was no mention of it in the pages documentation; this needs to be made clear from the start!

I then searched the site for _app and found this tucked away in the "Advanced Features" (even though it was like the VERY FIRST question I had about nextjs!). Therein it reads, 

"Next.js uses the App component to initialize pages ..."

... as though I already know what "the App" component is (despite there being no such thing in my codebase). It goes on:

"To override the default App, create the file ./pages/_app.js as shown below..."

... but this is confusing because the codebase ALREADY has such a file, so this unintroduced/mysterious App component is already being overidden apparently. In short, you need to update your documentation to reflect the evolution of your CLI/codebase.

**Describe the solution you'd like**

I mean, I'm new to this, so I don't know what to say other than "be clearer". I *assume* that nextjs is built so as to look for files with underscores first; if that is the case, then I want to know that upfront asap when learning. When learning a new framework, I want to be told the stuff that I can't figure out by just looking at the code. 

**Describe alternatives you've considered**

Just sucking it up and accepting that nextjs will be a slog to learn because the authors of the documentation are too close to the product to appreciate that newbies don't have any background knowledge of the codebase.

**Comment by leerob** [comment]
>... but this is confusing because the codebase ALREADY has such a file, so this unintroduced/mysterious App component is already being overidden apparently. In short, you need to update your documentation to reflect the evolution of your CLI/codebase.

You make an excellent point. The fact that create-next-app ships with `_app.js` means it shouldn't be in Advanced Features. 

> Just sucking it up and accepting that nextjs will be a slog to learn because the authors of the documentation are too close to the product to appreciate that newbies don't have any background knowledge of the codebase.

I'm happy to improve the intro documentation and would love any beginner feedback you have! 😄

**Comment by manovotny** [comment]
The Next.js Docs have been completely rewritten since this issue was created. 

`_app.js` is no longer considered an "Advanced Feature" and does a better job at explaining it's intent and purpose. 

https://nextjs.org/docs/pages/building-your-application/routing/custom-app

Still more than happy to hear suggestions on how it can be improved, so leave a follow up comment if there's something better we can do.
