### ISSUE TITLE
City based routing

### ISSUE THREAD

**Issue by vetalstar** [vercel/next.js#22605]
**Describe the feature you'd like to request**

For SEO requirements, you often need to have a city or county-based domain routing (or sub-path routing):
nyc.example.com
msk.example.com
ru.example.com

**Describe the solution you'd like**

I see the possibility of internationalized routing. It'll be very cool to have something like this but for user location.
Of course, we should be able to use our own endpoint to determine the location by IP.
It's also very important to save support of automatically statically optimized pages.

**Describe alternatives you've considered**

I don't see any alternatives right now but I don't have deep knowledge in Next.js

**Comment by leerob** [comment]
You can use `getServerSideProps` to determine what the sub-domain is. 

```
export async function getServerSideProps({ req, res }) {
  return {
    props: {
      host: req.headers.host
    }
  };
}
```

https://multi-domain-first.vercel.app/
