### ISSUE TITLE
Wrong dynamic slug value: [product].json instead of id from url

### ISSUE THREAD

**Issue by Carduelis** [vercel/next.js#22703]
# UPD. The problem occurs only 10.0.7+ including 10.0.8-canary, rollback to 10.0.6 solves the issue

### What version of Next.js are you using?

10.0.7

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

I have a folder products and [product].tsx file inside.
It renders /catalog/products/123456, where number is an id.
I also use ISR and do not prerender all products. They are thousands.

When I open the product page for the first time (cold start), it shows params object from getStaticProps function like this:
```
"params":{
   "product": "[product].json"
}
```
Which lead to a 404 result of my API.

When I reload the page the second time it loads correctly. So every cold start has [product].json as a value for slug.
The same thing is happening, if I open the same page on client, without rerendering a page: it's always [product].json instead of the regular id.

### Expected Behavior

The `params` value is always correct.

### To Reproduce

It can be reproducible only on Vercel platform. When it's running locally, everything is fine and the `params` object is always correct.

**Comment by renanfeluck** [comment]
I'm facing the same issue. Any solution?

**Comment by jharding** [comment]
I'm experiencing the same issue on v10.1.3. Here's an interesting twist though: it works fine if I remove rewrites from my _next.config.js_.
