### ISSUE TITLE
basePath + wildcard rewrite in next.config.js results in empty query object when using useRouter

### ISSUE THREAD

**Issue by chimericdream** [vercel/next.js#22804]
### What version of Next.js are you using?

10.0.7 (confirmed in canary)

### What version of Node.js are you using?

15.10.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

When using a base path along with a wildcard path rewrite, anything I try to add as a query on the destination is stripped and does not get included with the rest of the data returned by `useRouter`.

### Expected Behavior

The `:ctx` param should be part of the query object included when I use the `useRouter` hook.

### To Reproduce

Here is a CodeSandbox link with a minimal reproduction. However, it appears that CS does not support the `basePath` option in the `next.config.js` file, so I cannot even get the routing to resolve properly. However, this example should be sufficient to allow someone to reproduce the issue locally.

https://codesandbox.io/s/jolly-mirzakhani-dvuwl

Assuming a setup like this, navigate to `http(s)://.../my-app/foo-bar/about` to see the contents of the router. (Note: in the CodeSandbox above, this results in a 404 error because of the suspected aforementioned issue with `basePath`.)

`next.config.js`
```js
module.exports = {
  basePath: "/my-app",

  rewrites: async () => [
    {
      source: "/:ctx/:path*",
      destination: "/:path*?ctx=:ctx"
    }
  ]
};
```

`pages/about.js`
```js
import {useRouter} from 'next/router';

const About = () => {
    const router = useRouter();

    return (<pre><code>{JSON.stringify(router, null, 4)}</code></pre>);
};

export default About;
```

**Comment by chimericdream** [comment]
Here are a couple screenshots showing what I'm getting vs what I expect. The latter was manually edited by me to show what I would expect the return value to look like.

Actual
![next-actual](https://user-images.githubusercontent.com/198075/110127257-0acc0100-7d8b-11eb-8650-d30a44e45b55.png)

Expected (manually edited)
![next-expected](https://user-images.githubusercontent.com/198075/110127260-0b649780-7d8b-11eb-8969-41147331a1b2.png)

**Comment by ijjk** [comment]
Hi, this appears to be related to https://github.com/vercel/next.js/issues/23490 so I'm going to close this in favor of that issue
