### ISSUE TITLE
Serverless target creates a very large pages/_error.js

### ISSUE THREAD

**Issue by vbudovski** [vercel/next.js#22814]
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

12 - 14

### What browser are you using?

N/A

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

When building Next.JS with target `serverless`, the build completes, but produces an `_error` page in the serverless directory that is ~5.7MB in size.

### Expected Behavior

Error page size is more in line with all other generated pages (2k - 50k).

### To Reproduce

Set webpack build target to `serverless` and run `next build`

**Comment by sambecker** [comment]
Not sure if this is related, but moving from `10.0.7` to `10.0.8` made my serverless function too large to deploy to Vercel. Offending function went from `under < 50mb` to `51.9mb`.

**Comment by timneutkens** [comment]
`.next/serverless/pages/_error.js` is 996K, same as other pages when using `yarn create next-app`:

```
▲  pages (master) du -sh *
996K	_error.js
996K	index.js
```

It's likely that you're importing some library in `pages/_error.js`. I'll convert this into a help discussion given it's not a bug.
