### ISSUE TITLE
With-firebase-hosting-app deployment issue when styled components was added.

### ISSUE THREAD

**Issue by sajin4dev** [vercel/next.js#22829]
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

nodejs 10

### What browser are you using?

chrome

### What operating system are you using?

macOs

### How are you deploying your application?

Firebase

### Describe the Bug

> with-firebase-hosting@5.0.0 build
> next build src/

/with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1
module.exports=(()=>{var e={618:(e,r,l)=>{const{Container:t}=l(43);class NestedDeclaration extends t{constructor(e){super(e);this.type="decl";this.isNested=true;if(!this.nodes)this.nodes=[]}}e.exports=NestedDeclaration},327:(e,r,l)=>{let{Input:t}=l(43);let i=l(270);e.exports=function scssParse(e,r){let l=new t(e,r);let f=new i(l);f.parse();return f.root}},270:(e,r,l)=>{let{Comment:t}=l(43);let i=l(552);let f=l(618);let a=l(366);class ScssParser extends i{createTokenizer(){this.tokenizer=a(this.input)}rule(e){let r=false;let l=0;let t="";for(let i of e){if(r){if(i[0]!=="comment"&&i[0]!=="{"){t+=i[1]}}else if(i[0]==="space"&&i[1].includes("\n")){break}else if(i[0]==="("){l+=1}else if(i[0]===")"){l-=1}else if(l===0&&i[0]===":"){r=true}}if(!r||t.trim()===""||/^[#:A-Za-z-]/.test(t)){super.rule(e)}else{e.pop();let r=new f;this.init(r,e[0][2]);let l;for(let r=e.length-1;r>=0;r--){if(e[r][0]!=="space"){l=e[r];break}}if(l[3]){let e=this.input.fromOffset(l[3]);r.source.end={offset:l[3],line:e.line,column:e.col}}else{let e=this.input.fromOffset(l[2]);r.source.end={offset:l[2],line:e.line,column:e.col}}while(e[0][0]!=="word"){r.raws.before+=e.shift()[1]}r.source.start={line:e[0][2],column:e[0][3]};r.prop="";while(e.length){let l=e[0][0];if(l===":"||l==="space"||l==="comment"){break}r.prop+=e.shift()[1]}r.raws.between="";let t;while(e.length){t=e.shift();if(t[0]===":"){r.raws.between+=t[1];break}else{r.raws.between+=t[1]}}if(r.prop[0]==="_"||r.prop[0]==="*"){r.raws.before+=r.prop[0];r.prop=r.prop.slice(1)}r.raws.between+=this.spacesAndCommentsFromStart(e);this.precheckMissedSemicolon(e);for(let l=e.length-1;l>0;l--){t=e[l];if(t[1]==="!important"){r.important=true;let t=this.stringFrom(e,l);t=this.spacesFromEnd(e)+t;if(t!==" !important"){r.raws.important=t}break}else if(t[1]==="important"){let t=e.slice(0);let i="";for(let e=l;e>0;e--){let r=t[e][0];if(i.trim().indexOf("!")===0&&r!=="space"){break}i=t.pop()[1]+i}if(i.trim().indexOf("!")===0){r.important=true;r.raws.important=i;e=t}}if(t[0]!=="space"&&t[0]!=="comment"){break}}this.raw(r,"value",e);if(r.value.includes(":")){this.checkMissedSemicolon(e)}this.current=r}}comment(e){if(e[4]==="inline"){let r=new t;this.init(r,e[2]);r.raws.inline=true;let l=this.input.fromOffset(e[3]);r.source.end={offset:e[3],line:l.line,column:l.col};let i=e[1].slice(2);if(/^\s*$/.test(i)){r.text="";r.raws.left=i;r.raws.right=""}else{let e=i.match(/^(\s*)([^]*\S)(\s*)$/);let l=e[2].replace(/(\*\/|\/\*)/g,"*//*");r.text=l;r.raws.left=e[1];r.raws.right=e[3];r.raws.text=e[2]}}else{super.comment(e)}}raw(e,r,l){super.raw(e,r,l);if(e.raws[r]){let t=e.raws[r].raw;e.raws[r].raw=l.reduce((e,r)=>{if(r[0]==="comment"&&r[4]==="inline"){let l=r[1].slice(2).replace(/(\*\/|\/\*)/g,"*//*");return e+"/*"+l+"*/"}else{return e+r[1]}},"");if(t!==e.raws[r].raw){e.raws[r].scss=t}}}}e.exports=ScssParser},139:(e,r,l)=>{let t=l(779);class ScssStringifier extends t{comment(e){let r=this.raw(e,"left","commentLeft");let l=this.raw(e,"right","commentRight");if(e.raws.inline){let t=e.raws.text||e.text;this.builder("//"+r+t+l,e)}else{this.builder("/*"+r+e.text+l+"*/",e)}}decl(e,r){if(!e.isNested){super.decl(e,r)}else{let r=this.raw(e,"between","colon");let l=e.prop+r+this.rawValue(e,"value");if(e.important){l+=e.raws.important||" !important"}this.builder(l+"{",e,"start");let t;if(e.nodes&&e.nodes.length){this.body(e);t=this.raw(e,"after")}else{t=this.raw(e,"after","emptyBody")}if(t)this.builder(t);this.builder("}",e,"end")}}rawValue(e,r){let l=e[r];let t=e.raws[r];if(t&&t.value===l){return t.scss?t.scss:t.raw}else{return l}}}e.exports=ScssStringifier},886:(e,r,l)=>{let t=l(139);e.exports=function scssStringify(e,r){let l=new t(r);l.stringify(e)}},845:(e,r,l)=>{let t=l(886);let i=l(327);e.exports={parse:i,stringify:t}},366:e=>{"use strict";const r="'".charCodeAt(0);const l='"'.charCodeAt(0);const t="\\".charCodeAt(0);const i="/".charCodeAt(0);const f="\n".charCodeAt(0);const a=" ".charCodeAt(0);const s="\f".charCodeAt(0);const h="\t".charCodeAt(0);const w="\r".charCodeAt(0);const o="[".charCodeAt(0);const u="]".charCodeAt(0);const n="(".charCodeAt(0);const c=")".charCodeAt(0);const m="{".charCodeAt(0);const b="}".charCodeAt(0);const p=";".charCodeAt(0);const y="*".charCodeAt(0);const C=":".charCodeAt(0);const A="@".charCodeAt(0);const d=",".charCodeAt(0);const O="#".charCodeAt(0);const D=/[\t\n\f\r "#'()/;[\\\]{}]/g;const g=/[\t\n\f\r !"#'():;@[\\\]{}]|\/(?=\*)/g;const q=/.[\n"'(/\\]/;const z=/[\da-f]/i;const F=/[\n\f\r]/g;e.exports=function scssTokenize(e,V={}){let $=e.css.valueOf();let B=V.ignoreErrors;let k,S,I,_,M;let U,Z,j,G;let J=$.length;let X=0;let Y=[];let v=[];let P;function position(){return X}function unclosed(r){throw e.error("Unclosed "+r,X)}function endOfFile(){return v.length===0&&X>=J}function interpolation(){let e=1;let i=false;let f=false;while(e>0){S+=1;if($.length<=S)unclosed("interpolation");k=$.charCodeAt(S);j=$.charCodeAt(S+1);if(i){if(!f&&k===i){i=false;f=false}else if(k===t){f=!U}else if(f){f=false}}else if(k===r||k===l){i=k}else if(k===b){e-=1}else if(k===O&&j===m){e+=1}}}function nextToken(e){if(v.length)return v.pop();if(X>=J)return;let V=e?e.ignoreUnclosed:false;k=$.charCodeAt(X);switch(k){case f:case a:case h:case w:case s:{S=X;do{S+=1;k=$.charCodeAt(S)}while(k===a||k===f||k===h||k===w||k===s);G=["space",$.slice(X,S)];X=S-1;break}case o:case u:case m:case b:case C:case p:case c:{let e=String.fromCharCode(k);G=[e,e,X];break}case d:{G=["word",",",X,X+1];break}case n:{Z=Y.length?Y.pop()[1]:"";j=$.charCodeAt(X+1);if(Z==="url"&&j!==r&&j!==l){P=1;U=false;S=X+1;while(S<=$.length-1){j=$.charCodeAt(S);if(j===t){U=!U}else if(j===n){P+=1}else if(j===c){P-=1;if(P===0)break}S+=1}_=$.slice(X,S+1);G=["brackets",_,X,S];X=S}else{S=$.indexOf(")",X+1);_=$.slice(X,S+1);if(S===-1||q.test(_)){G=["(","(",X]}else{G=["brackets",_,X,S];X=S}}break}case r:case l:{I=k;S=X;U=false;while(S<J){S++;if(S===J)unclosed("string");k=$.charCodeAt(S);j=$.charCodeAt(S+1);if(!U&&k===I){break}else if(k===t){U=!U}else if(U){U=false}else if(k===O&&j===m){interpolation()}}G=["string",$.slice(X,S+1),X,S];X=S;break}case A:{D.lastIndex=X+1;D.test($);if(D.lastIndex===0){S=$.length-1}else{S=D.lastIndex-2}G=["at-word",$.slice(X,S+1),X,S];X=S;break}case t:{S=X;M=true;while($.charCodeAt(S+1)===t){S+=1;M=!M}k=$.charCodeAt(S+1);if(M&&k!==i&&k!==a&&k!==f&&k!==h&&k!==w&&k!==s){S+=1;if(z.test($.charAt(S))){while(z.test($.charAt(S+1))){S+=1}if($.charCodeAt(S+1)===a){S+=1}}}G=["word",$.slice(X,S+1),X,S];X=S;break}default:j=$.charCodeAt(X+1);if(k===O&&j===m){S=X;interpolation();_=$.slice(X,S+1);G=["word",_,X,S];X=S}else if(k===i&&j===y){S=$.indexOf("*/",X+2)+1;if(S===0){if(B||V){S=$.length}else{unclosed("comment")}}G=["comment",$.slice(X,S+1),X,S];X=S}else if(k===i&&j===i){F.lastIndex=X+1;F.test($);if(F.lastIndex===0){S=$.length-1}else{S=F.lastIndex-2}_=$.slice(X,S+1);G=["comment",_,X,S,"inline"];X=S}else{g.lastIndex=X+1;g.test($);if(g.lastIndex===0){S=$.length-1}else{S=g.lastIndex-2}G=["word",$.slice(X,S+1),X,S];Y.push(G);X=S}break}X++;return G}function back(e){v.push(e)}return{back:back,nextToken:nextToken,endOfFile:endOfFile,position:position}}},779:e=>{"use strict";const r={colon:": ",indent:"    ",beforeDecl:"\n",beforeRule:"\n",beforeOpen:" ",beforeClose:"\n",beforeComment:"\n",after:"\n",emptyBody:"",commentLeft:" ",commentRight:" ",semicolon:false};function capitalize(e){return e[0].toUpperCase()+e.slice(1)}class Stringifier{constructor(e){this.builder=e}stringify(e,r){this[e.type](e,r)}root(e){this.root=e;this.body(e);if(e.raws.after)this.builder(e.raws.after)}comment(e){let r=this.raw(e,"left","commentLeft");let l=this.raw(e,"right","commentRight");this.builder("/*"+r+e.text+l+"*/",e)}decl(e,r){let l=this.raw(e,"between","colon");let t=e.prop+l+this.rawValue(e,"value");if(e.important){t+=e.raws.important||" !important"}if(r)t+=";";this.builder(t,e)}rule(e){this.block(e,this.rawValue(e,"selector"));if(e.raws.ownSemicolon){this.builder(e.raws.ownSemicolon,e,"end")}}atrule(e,r){let l="@"+e.name;let t=e.params?this.rawValue(e,"params"):"";if(typeof e.raws.afterName!=="undefined"){l+=e.raws.afterName}else if(t){l+=" "}if(e.nodes){this.block(e,l+t)}else{let i=(e.raws.between||"")+(r?";":"");this.builder(l+t+i,e)}}body(e){let r=e.nodes.length-1;while(r>0){if(e.nodes[r].type!=="comment")break;r-=1}let l=this.raw(e,"semicolon");for(let t=0;t<e.nodes.length;t++){let i=e.nodes[t];let f=this.raw(i,"before");if(f)this.builder(f);this.stringify(i,r!==t||l)}}block(e,r){let l=this.raw(e,"between","beforeOpen");this.builder(r+l+"{",e,"start");let t;if(e.nodes&&e.nodes.length){this.body(e);t=this.raw(e,"after")}else{t=this.raw(e,"after","emptyBody")}if(t)this.builder(t);this.builder("}",e,"end")}raw(e,l,t){let i;if(!t)t=l;if(l){i=e.raws[l];if(typeof i!=="undefined")return i}let f=e.parent;if(t==="before"){if(!f||f.type==="root"&&f.first===e){return""}}if(!f)return r[t];let a=e.root();if(!a.rawCache)a.rawCache={};if(typeof a.rawCache[t]!=="undefined"){return a.rawCache[t]}if(t==="before"||t==="after"){return this.beforeAfter(e,t)}else{let r="raw"+capitalize(t);if(this[r]){i=this[r](a,e)}else{a.walk(e=>{i=e.raws[l];if(typeof i!=="undefined")return false})}}if(typeof i==="undefined")i=r[t];a.rawCache[t]=i;return i}rawSemicolon(e){let r;e.walk(e=>{if(e.nodes&&e.nodes.length&&e.last.type==="decl"){r=e.raws.semicolon;if(typeof r!=="undefined")return false}});return r}rawEmptyBody(e){let r;e.walk(e=>{if(e.nodes&&e.nodes.length===0){r=e.raws.after;if(typeof r!=="undefined")return false}});return r}rawIndent(e){if(e.raws.indent)return e.raws.indent;let r;e.walk(l=>{let t=l.parent;if(t&&t!==e&&t.parent&&t.parent===e){if(typeof l.raws.before!=="undefined"){let e=l.raws.before.split("\n");r=e[e.length-1];r=r.replace(/\S/g,"");return false}}});return r}rawBeforeComment(e,r){let l;e.walkComments(e=>{if(typeof e.raws.before!=="undefined"){l=e.raws.before;if(l.includes("\n")){l=l.replace(/[^\n]+$/,"")}return false}});if(typeof l==="undefined"){l=this.raw(r,null,"beforeDecl")}else if(l){l=l.replace(/\S/g,"")}return l}rawBeforeDecl(e,r){let l;e.walkDecls(e=>{if(typeof e.raws.before!=="undefined"){l=e.raws.before;if(l.includes("\n")){l=l.replace(/[^\n]+$/,"")}return false}});if(typeof l==="undefined"){l=this.raw(r,null,"beforeRule")}else if(l){l=l.replace(/\S/g,"")}return l}rawBeforeRule(e){let r;e.walk(l=>{if(l.nodes&&(l.parent!==e||e.first!==l)){if(typeof l.raws.before!=="undefined"){r=l.raws.before;if(r.includes("\n")){r=r.replace(/[^\n]+$/,"")}return false}}});if(r)r=r.replace(/\S/g,"");return r}rawBeforeClose(e){let r;e.walk(e=>{if(e.nodes&&e.nodes.length>0){if(typeof e.raws.after!=="undefined"){r=e.raws.after;if(r.includes("\n")){r=r.replace(/[^\n]+$/,"")}return false}}});if(r)r=r.replace(/\S/g,"");return r}rawBeforeOpen(e){let r;e.walk(e=>{if(e.type!=="decl"){r=e.raws.between;if(typeof r!=="undefined")return false}});return r}rawColon(e){let r;e.walkDecls(e=>{if(typeof e.raws.between!=="undefined"){r=e.raws.between.replace(/[^\s:]/g,"");return false}});return r}beforeAfter(e,r){let l;if(e.type==="decl"){l=this.raw(e,null,"beforeDecl")}else if(e.type==="comment"){l=this.raw(e,null,"beforeComment")}else if(r==="before"){l=this.raw(e,null,"beforeRule")}else{l=this.raw(e,null,"beforeClose")}let t=e.parent;let i=0;while(t&&t.type!=="root"){i+=1;t=t.parent}if(l.includes("\n")){let r=this.raw(e,null,"indent");if(r.length){for(let e=0;e<i;e++)l+=r}}return l}rawValue(e,r){let l=e[r];let t=e.raws[r];if(t&&t.value===l){return t.raw}return l}}e.exports=Stringifier},43:e=>{"use strict";e.exports=require("postcss")},552:e=>{"use strict";e.exports=require("postcss/lib/parser")}};var r={};function __nccwpck_require__(l){if(r[l]){return r[l].exports}var t=r[l]={exports:{}};var i=true;try{e[l](t,t.exports,__nccwpck_require__);i=false}finally{if(i)delete r[l]}return t.exports}__nccwpck_require__.ab=__dirname+"/";return __nccwpck_require__(845)})();
                                                                                                   ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.618 (with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:100)
    at __nccwpck_require__ (with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.270 (with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:413)
    at __nccwpck_require__ (/with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.327 (with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
    at __nccwpck_require__ (/with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at Object.845 (with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733)
    at __nccwpck_require__ (with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
    at /with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11863
    at Object.<anonymous> (/with-firebase-hosting-app/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11889)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)

Error: functions predeploy error: Command terminated with non-zero exit code1
error Command failed with exit code 1.

### Expected Behavior

Working fine in local but when tried to deploy in firebase hosting throwing this error. 

### To Reproduce

Add .babalrc file in the root folder
{
    "presets": ["next/babel"],
    "plugins": [["styled-components", { "ssr": true }]]
}

Run 
-> yarn add styled-components

-> yarn build

-> yarn deploy

**Comment by anantasty** [comment]
I ran into the same issue too
