### ISSUE TITLE
next/link not scrolling to top of page in iOS firefox

### ISSUE THREAD

**Issue by pdugan20** [vercel/next.js#22858]
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.4.0

### What browser are you using?

Firefox

### What operating system are you using?

iOS

### How are you deploying your application?

Heroku

### Describe the Bug

When using Firefox on iOS, next/link doesn't scroll to the top for new pages, and keeps a user scrolled even when passing in the scroll prop, which should be a default regardless.

### Expected Behavior

next/link should scroll a user to the top of a new page.

### To Reproduce

Use next/link on a physical iOS device while using Firefox. You can view this in production at https://tryhikearound.com

Here's a code sample, but it's doing this regardless of the link as long as it's viewed on Firefox on iOS. 
```
    renderNearbyHikeLinks() {
        const { prefetch } = this.props;
        const { nearbyHikes } = this.state;

        return nearbyHikes.map(({ name, hid }, index) => (
            <ListItem key={index}>
                <Link href='[hid]' as={hid} prefetch={prefetch} scroll>
                    <RightRailLink href={hid}>{name}</RightRailLink>
                </Link>
            </ListItem>
        ));
    }
```

Using Firefox on Mac works fine, and using all other browsers on iOS works fine (see attached video where the behavior works as expected in Safari).

https://user-images.githubusercontent.com/1837100/110264357-feec6480-7f6d-11eb-8e71-edc181439903.mov

**Comment by pdugan20** [comment]
Bizarrely, even doing trying use window.scroll when the page mounts also doesn't fix this:
```
const HikePage = ({ hike }) => {
    hike = JSON.parse(hike);

    const scrollToTop = () => {
        window.scroll({
            top: 0,
            left: 0,
            behavior: 'auto',
        });
    };

    useEffect(() => {
        scrollToTop();
    });
```

Any ideas?

**Comment by pdugan20** [comment]
If I use window.top.scroll and set a timeout of 5ms on the function, that seems to be working now as far as I can tell?
```
    useEffect(() => {
        setTimeout(() => {
            scrollToTop();
        }, 5);
    });
```

**Comment by Hopp3r** [comment]
I have the same issue on Edge

**Comment by arb0z** [comment]
Same issue on Firefox 88 64bits, but on MacOS.
I can fix it by removing `scroll-behavior` from my css

```css
html {
    /* remove next line to fix scroll to top when page change on Firefox */
    scroll-behavior: smooth;
}
```

**Comment by pecoram** [comment]
any updates?

**Comment by meotimdihia** [comment]
```  
experimental: {
    scrollRestoration: true
}
```
I have to turn on this config to fix the problem.

**Comment by kasim444** [comment]
You can make the scroll-behavior value 'auto' by targeting the Firefox browser.

```css
html {
    scroll-behavior: smooth;
}

// targeting only firefox browser
@-moz-document url-prefix() {
  html {
    scroll-behavior: auto;
  }
}
```

**Comment by meotimdihia** [comment]
In my case, it is related to image DOMs that don't have width + height attributes.

**Comment by thexpand** [comment]
I am facing this issue and it's not only Firefox, but seems to happen on iOS Safari as well. This issue might be related: https://github.com/vercel/next.js/issues/28778

**Comment by WaelYoussfi** [comment]
In my case, the issue was related to the **scroll-margin** attribute in the parent div tag of the page that I want to scroll to. 
Once the scroll-margin value is above a certain value the scrolling doesn't work anymore. However, this is only happening in Firefox, I have no issues in Chromium-based browsers.

**Comment by AminTaiTntra** [comment]
You can set default scroll to false as official next doc [next/routing](https://nextjs.org/docs/api-reference/next/router#routerpush).
`router.push('/', {} ,  { scroll: false }) `
and add window.scroll in your component file.
```
 window.scroll({
   top: 0,
   behavior: 'smooth'
})
```

**Comment by samcx** [comment]
@pdugan20 Hi there!

I will be closing this since this is considered the default behavior.

- https://nextjs.org/docs/pages/api-reference/components/link#scroll

If you have any issues with scrolling with the latest Next.js, please send us a new [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) so we can take a look!
