### ISSUE TITLE
Root redirect with basePath does not redirect

### ISSUE THREAD

**Issue by hagmic** [vercel/next.js#22890]
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next dev / next start

### Describe the Bug

A root redirect when used in combination with `basePath` will not correctly redirect.

### Expected Behavior

I expect the redirect to occur.

### To Reproduce

Given the following Next Config:

```
module.exports = {
  basePath: '/docs',
  async redirects() {
    return [
      {
        source: '/',
        destination: '/test',
        permanent: true
      }
    ]
  }
}
```

And the following pages structure:
```
/pages
    /test.js
```

1. Visit http://localhost:3000/docs
2. Notice you are not redirected to http://localhost:3000/docs/test, as defined in the config

https://github.com/hagmic/nextxjs-base-path-redirects-repro

FWIW -- When removing the `basePath`, the redirect occurs as expected.

**Comment by nicolaserny** [comment]
I noticed the same behavior.
My current workaround is:
```  
module.exports = {
  basePath: '/docs',
  async redirects() {
    return [
      {
        source: '/docs',
        destination: '/docs/test',
        permanent: true,
        basePath: false,
      }
    ]
  }
}          
```
I hope it can help.

**Comment by JanKaifer** [comment]
It works correctly in `next@13`.
