### ISSUE TITLE
ISR Cache Control s-maxage not taking the "revalidate" value for the homepage

### ISSUE THREAD

**Issue by ExtremelyAngryCat** [vercel/next.js#22983]
### What version of Next.js are you using?

10.0.5

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu, Windows, macOs

### How are you deploying your application?

next start

### Describe the Bug

I am using the Incremental Static Generation feature with a wildcard route at the root of the pages folder.
It works fine and all the paths have the right stale-while-validate configured value BUT the homepage (path: /).
The homepage uses the same wildcard route as the other routes, but has a revalidate value of 1 and sets the cache-control to s-maxage: 1.

### Expected Behavior

I expected the homepage (path: /) to take the revalidate value like the others paths do just fine, and not force-set it to 1. Everything else works perfectly.

### To Reproduce

Cannot really provide a full code snippet, but here is the wildcard route name used: "[[...pageRouter]].tsx" which contains:
....
```js
const page = ......;

export const getStaticPaths: GetStaticPaths = async () => ({
  paths: [],
  fallback: 'blocking',
});

export const getStaticProps: GetStaticProps = async (context) => ({
  props: await page.getStaticData(context),
  revalidate: serverRuntimeConfig.STATIC_PAGE_REVALIDATION_DELAY,
});
```

**Comment by youngchingjui** [comment]
I'm also having trouble revalidating the home page (route: `/`). I don't have a wildcard route. Other pages revalidate just fine, just not the home page.

**Comment by korac** [comment]
Any updates on this matter? Facing the same issue as @youngchingjui - on the home page (route: `/`); other pages work fine.
