### ISSUE TITLE
Webpack 5 does not correctly transpile `.js` file with `"type":"module"`

### ISSUE THREAD

**Issue by JacobLey** [vercel/next.js#23029]
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome (unrelated)

### What operating system are you using?

macOS

### How are you deploying your application?

Custom server (unrelated)

### Describe the Bug

NextJS's default configs with Webpack5 does not correctly transpile `.js` files under a `"type":"module"` package, using `import/export` syntax

See example repo+readme for example/details: https://github.com/JacobLey/next-webpack5-jsx-fail

High level is that the provided webpack5 + babel configuration fails to properly transpile `.js`. It improperly treats these modules as pure CommonJS, resulting if failures where `.default` should be used.

See the notable differences in the two out server files:
https://github.com/JacobLey/next-webpack5-jsx-fail/blob/main/fail/next/.next/server/pages/_app.js#L22-L27
https://github.com/JacobLey/next-webpack5-jsx-fail/blob/main/success-1/next/.next/server/pages/_app.js#L24-L29

#### Side note
The `"type":"module"` has benefits outside NextJS, but there have been times Webpack has complained about lack of `"type":"module"` for files that contain `import`/`export`. I would expect babel to handle this automagically with the `sourceType:unambiguous` setting.

I mostly bring it up because:
1) It also seems like a bug (but not an issue enough for me to dig much deeper to consistently reproduce)
2) It _might_ be related, since it would also impact ability to parse/detect ESM

### Expected Behavior

Webpack5 should properly parse `.js` files using `import`/`export` syntax within `"type":"module"` packages.

Considering `"type":"module"` enables ESM syntax like `import`/`export` if anything I would expect this to succeed over things like similar syntax in CommonJS

### To Reproduce

See mini-repo to reproduce error, based on create-next-app boilerplate: https://github.com/JacobLey/next-webpack5-jsx-fail

1) Clone repo locally
2) `npm ci`
3) `npm run build:fail` will fail with `Class extends value #<Object> is not a constructor or null` error.
4) `npm run build:success-N` where N is 1-4. These highlight successful versions of the same code with minor tweaks (showing behavior can/should work). Differences are documented in README.md

**Comment by JacobLey** [comment]
On some further insight, I think this bug is actually caused by how NextJS exports its packages.

Take `document` for example: https://github.com/vercel/next.js/blob/canary/packages/next/document.js

That does not properly propagate `__esModule=true`

See how Babel does it (no overwriting `exports`) https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAKjgMyhAtnA5MiEtA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&prettier=false&targets=&version=7.13.11&externalPlugins=babel-plugin-dedent%402.1.0

**Comment by JacobLey** [comment]
I don't think it is possible for CJS to actually export _both_ a default and named exports, so values like `Document` should get a named export as well, so files loading it can just reference the named export instead.

e.g. `import { Document } from 'next/document.js'`

**Comment by JacobLey** [comment]
@timneutkens would you be open to a PR adding all the default exports as a named one as well?

For all the `.js` files here: https://github.com/vercel/next.js/tree/canary/packages/next
(well in whatever locations those .js files point to)

e.g.
```
export default class Document<P = {}> extends Component<DocumentProps & P> {
...
}

export { Document };
```

**Comment by balazsorban44** [comment]
Hi, Next.js has added native ESM support in Next 12. Please give it a try.

https://nextjs.org/blog/next-12#es-modules-support-and-url-imports

**Comment by JacobLey** [comment]
@balazsorban44 I have updated the example code provided to next12.

The bug still exists.

NextJS does not support writing code as ES modules yet, it only supports importing those files from third parties.

Fingers crossed this sort of issue will be resolved by features like https://github.com/vercel/next.js/pull/33637 or via the solution I provided above

But until then I would appreciate keeping this issue open as it has not been resolved

**Comment by kachkaev** [comment]
I am happy to confirm that #33637 worked for me [in a side project](https://github.com/kachkaev/tooling-for-how-old-is-this-house/commit/2b27ad45fb206eee10a669522b20e5fc5502a430) 🎉

Just upgraded to `12.0.11-canary.16` and removed a [the `.next/package.json` hack](https://github.com/vercel/next.js/discussions/32220#discussioncomment-1766378).

Miraculas times, thanks a lot @timneutkens! ES Modules FTW 🚀
