### ISSUE TITLE
Error with symlinks in .next folder

### ISSUE THREAD

**Issue by clovis1122** [vercel/next.js#23120]
### What version of Next.js are you using?

Latest (also tested with canary)

### What version of Node.js are you using?

14.15.0

### What browser are you using?

-

### What operating system are you using?

-

### How are you deploying your application?

-

### Describe the Bug

When there's a broken symlink in the `.next` folder, `next dev` doesn't work.

### Expected Behavior

`next dev` should work as expected (and clear the symlink).

### To Reproduce

Run `yarn dev`
Then, in the .next folder:
```
touch a_file
mkdir zfile
ln -s a_file zfile/z_file
```

Then restart the dev server.

The problem seems related to recursive-delete.js, which uses `stat` instead of `lstat`. `stat` will fail if the symlink is broken, but `rmdir` won't remove the folder because the symlink is still there.

Some context: I'm working on a plugin that stores some cache files in `.next`, and this came up - let me know if this is expected / what would be the best way to store hidden files.

**Comment by JanKaifer** [comment]
This seems to work in `next@13`.
