### ISSUE TITLE
<Link /> inside an SVG won't allow user to cmd+click and open page in new tab

### ISSUE THREAD

**Issue by klaasman** [vercel/next.js#23252]
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

10.23.0

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

Command+click on a `<Link />` which is rendered inside an SVG does not open the link in a new tab/window.

### Expected Behavior

Command+click on a link rendered inside an SVG should open the link in a new tab/window.

### To Reproduce

Here's a simple codesandbox with the issue: https://codesandbox.io/s/compassionate-morning-ql359

1. create an SVG as follows:
```tsx
<svg>
  <Link href="/about">
    <a>
      <rect width={100} height={100} />
    </a>
  </Link>
</svg>
```

2. Command+click on the `rect` in order to see the window navigate to the link instead of opening a new tab with that link.

I can confirm that disabling javascript will have the expected result (open new tab), which I think means the click handlers of the Link component are the culprit.

**Comment by timneutkens** [comment]
When holding `cmd`/`ctrl` while clicking we just defer to the default browser behavior for `<a>` so it's likely default browser behavior does not allow `<a>` in `<svg>`?

**Comment by klaasman** [comment]
Yep that's also what I thought, hence testing it with javascript disabled which resulted in the desired output.

I've updated the codesandbox example with an extra rect which is not wrapped in a `Link`, this one works as expected.

**Comment by klaasman** [comment]
It appears the nodename of an `<a />` inside svg is a lowercase `a` instead of what's being checked `A`:
https://github.com/vercel/next.js/blob/c9a2e5b8f0ce4ddeeff195cf978e7dd4a362f307/packages/next/client/link.tsx#L89-L92

**Comment by klaasman** [comment]
Here's a plain js/html example, click both links and see the console's output: https://jsfiddle.net/L2p8f4ve/28/

**Comment by klaasman** [comment]
Oh and btw

> so it's likely default browser behavior does not allow `<a>` in `<svg>`?

There actually is an `<a>` for `<svg>`:

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/a

:-)
