### ISSUE TITLE
Deprecated URL API Usage causing errors

### ISSUE THREAD

**Issue by kmdev1** [vercel/next.js#23306]
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

v12.19.0, v14.16.0

### What browser are you using?

Any browser

### What operating system are you using?

Any OS

### How are you deploying your application?

`NODE_ENV=production node server.js`

### Describe the Bug

I am receiving this thrown error when trying to load any image that has been generated with the next/image component:

```
Cannot destructure property 'xxxx' of 'parsedUrl.query' as it is undefined.
```

After debugging the issue I have found that this is being caused because we are using the `WHATWG URL API` instead of the deprecated `legacy urlObject` within the custom `server.js`.

The deprecated `urlObject` `parse` function would indeed return a `query` object that contained all query params. However the new API returns a searchParams object.

In the case where I am seeing this error, the image optimisation function uses a destructuring assignment for `url`, `w` and `q` on the `query` object.

### Expected Behavior

The `legacy urlObject` was deprecated in Node.js v11, so I think ideally this shouldn't throw an error and should cater for both scenarios where the new and legacy APIs are used.

### To Reproduce

Create a simple custom handler that passes `(req, res, parsedUrl)` except create `parsedUrl` with the `WHATWG URL API`.

The next/image component is the only place I've found this is broken at the moment, but I assume it would be in other places.

If you then use a next/image component and try and load the image you'll notice there's a 500 server error.

**Comment by choyan** [comment]
Facing the same problem while trying to upgrade the Next.js version from 9.4 to 10.1 and using next/image.
