### ISSUE TITLE
Less import not working

### ISSUE THREAD

**Issue by anarerdene** [vercel/next.js#23430]
### What version of Next.js are you using?

10.0.9

### What version of Node.js are you using?

v14.6.0

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Less global import not working

### Expected Behavior

updated next v9 to v10 and less not working

### To Reproduce

error - ./styles/main.less
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Require stack:
- /Works/app/program/node_modules/mini-css-extract-plugin/dist/loader.js
- /Works/app/program/node_modules/next/dist/compiled/webpack/bundle4.js
- /Works/app/program/node_modules/next/dist/compiled/webpack/webpack.js

in _app.js less imported globaly.

`import './styles/main.less'`

this is my next.config.js

`
```javascript
/* eslint-disable */
const withPlugins = require('next-compose-plugins');
const withCss = require('@zeit/next-css');
const withLess = require('@zeit/next-less');

// fix: prevents error when .less files are required by node
if (typeof require !== 'undefined') {
  require.extensions['.less'] = () => {};
  require.extensions['.css'] = (file) => {};
}


// Plugins
module.exports = withPlugins([
  [
    withCss,
    {
      lessLoaderOptions: {
        importLoaders: 1,
        sourceMap: true,
      },
    },
  ],
  [
    withLess,
    {
      lessLoaderOptions: {
        javascriptEnabled: true,
      },
    },
  ],

]);
````

**Comment by alexneo2003** [comment]
same issue
