### ISSUE TITLE
Next 10.1 respawns infinite jest-worker child processes

### ISSUE THREAD

**Issue by markerikson** [vercel/next.js#23519]
### What version of Next.js are you using?

10.1.0

### What version of Node.js are you using?

12.18.3

### What browser are you using?

N/A

### What operating system are you using?

Windows 10.1809

### How are you deploying your application?

next dev

### Describe the Bug

I have a Next application that's been running on 10.0.3.  I just tried to update it to 10.1.0, and now every time I start `next dev`, my CPU pegs to 100% and stays there. Inspecting the process tree, I see the parent Next process, a couple children, and then an infinite series of child `jest-worker` processes that are spawning, dying, and re-spawning. The `jest-worker` process respawns appear to be the culprit for the CPU usage:

![image](https://user-images.githubusercontent.com/1128784/112896959-086c7680-90ad-11eb-9285-6c5a7665dcc2.png)

Part of the excess CPU usage is due to this corporate machine having extra process security checks that slow down Windows process creation.  However, previous versions of Next worked just fine, and I can confirm that the behavior first appears in 10.0.10-canary.1 .

### Expected Behavior

Next would start, eat some CPU and spawn a few processes during startup, but then settle down to idle after initial setup is complete.

### To Reproduce

Haven't tried reproducing this as a standalone project or repro. But, I've stepped my way through a dozen different Next versions within our repo, and I can confirm that this first appeared in version 10.0.10-canary.1.

Some of the 10.x versions I tried, and their results:

- 0.6, 0.7: work (no extra processes)
- 0.8, 0.9, 0.10-c.0: crash on startup (EPIPE)
- 0.10-c.1 and up: failure (extra processes)

Each time, all I've done is:

```
yarn add next@10.0.$SOME_VERSION
yarn dev
```

If I compare https://github.com/vercel/next.js/compare/v10.0.10-canary.0...v10.0.10-canary.1 , I see that canary.1 includes https://github.com/vercel/next.js/pull/23077 , which is an update to the `jest-worker` library. 

That PR seems like the likely candidate to have modified the child process behavior.

**Comment by rkrv** [comment]
I'm getting the same error; works for my co-workers don't work for me; the same setup; pinned to 10.0.7 for now.

**Comment by CharlieHess** [comment]
Same problem here after upgrading from 10.0.x → 10.2.x; I see a forever-hang after running `yarn dev`. Sometimes it doesn't hang but crashes immediately with an `EPIPE` error in `jest-worker`. I'm on macOS Big Sur so it looks like this problem is cross-platform.

**Comment by markerikson** [comment]
I'm kinda relieved to see other folks reporting this as well. nice to know it wasn't _just_ me or my machine :)

**Comment by egeriis** [comment]
This is a transient issue for me at least. Resolves by running `yarn dev` again.

**Comment by egeriis** [comment]
I've yet to find the culprit, but my initial findings indicate that this pertains to Node.js 12, and doesn't happen with v14.

**Comment by markerikson** [comment]
@egeriis Good to know. It was _very_ consistent for me when I switched to a version that had the worker upgrade, but yes, I'm running Node 12.18 atm.  

I can push through an upgrade to Node 14 for both our dev and deployment environments, but it'd also be nice to know why this is happening :)

**Comment by egeriis** [comment]
@markerikson Yeah, unfortunately it wasn't apparent where the error happened, so I had to switch away from debugging the issue.

**Comment by rkrv** [comment]
Upgrading node to v14 solved the problem for me

**Comment by xiaomaini** [comment]
Possible work around and not a fix. 

For some reason when updating next `jest-worker` jumps to v27.x in the lock file. 

<img width="1231" alt="Screenshot 2021-04-20 at 21 58 18" src="https://user-images.githubusercontent.com/13072566/115463383-a7573f00-a223-11eb-98b8-f22cdb240bb6.png">

As a workaround I installed jest-worker as a dev dependency to bring the version back down.

**Comment by quinn** [comment]
this is happening for me on next.js 10.2.3 and node version 16.2.0. I have to `kill -9` the parent node process every time (killing it removes all of the jest-workers, around 10 i think)

**Comment by markerikson** [comment]
FWIW, I ended up upgrading our app to run on Node 14, and went from Next 10.0 to 10.2 on the day it came out. Runs fine, no problems here.

So, the workaround is definitely upgrading to Node 14.

**Comment by quinn** [comment]
thanks @markerikson, i downgraded to 14.17.0, same problem. 😔

**Comment by quinn** [comment]
i tried to use debugger, but it got confusing with all of the jest-workers. not sure where things are breaking down

**Comment by quinn-freshly** [comment]
My issue may be unrelated. I tried running with debugger and setting it to break on "uncaught exceptions", and it seems an import was failing. I don't know why this caused the jest-workers to go into an infinite loop. Other broken imports seem ok, but for whatever reason this one in particular doesn't work (its for windi.css)

**Comment by quinn** [comment]
My issue may be unrelated. I tried running with debugger and setting it to break on "uncaught exceptions", and it seems an import was failing. I don't know why this caused the jest-workers to go into an infinite loop. Other broken imports seem ok, but for whatever reason this one in particular doesn't work (its for windi.css)

**Comment by ijjk** [comment]
Hi, we've updated `jest-worker` in the latest versions of Next.js `v12.0.10`, can anyone who was seeing this behavior confirm this is no longer present after updating Next.js versions?

**Comment by markerikson** [comment]
For me the issue was resolved by upgrading from Node 12 to Node 14, per my earlier comment.

**Comment by ijjk** [comment]
Considering this only affected Node.js 12 and it is [EOL in a couple months](https://github.com/nodejs/Release) I'm going to close this issue, if anyone is still encountering this on >= v14 of Node.js please create a new issue with additional information to allow investigation!
