### ISSUE TITLE
re-export HTML files faster and lighter

### ISSUE THREAD

**Issue by FrameJ** [vercel/next.js#23592]
### Describe the feature you'd like to request

Mostly we use `next build && next export` to generate static HTML, which will compile js files again, even my js files never change since last build.
For example, if I have a new path returned from getStaticPaths but no changes in js files, actually I would rather re-use the latest built static files than re-compile. And there is no way to reach this for now.

### Describe the solution you'd like

A "re-export" or "re-build" command in next-cli.

### Describe alternatives you've considered

Provide a way to run `next build` without webpack compilation.
or
Call getStaticPaths and other static function during `next export`.

**Comment by timneutkens** [comment]
Please use the latest version of Next.js and enable webpack 5: https://nextjs.org/docs/messages/webpack5
