### ISSUE TITLE
Disable link prefetching in preview mode

### ISSUE THREAD

**Issue by hatsumatsu** [vercel/next.js#23641]
### Describe the feature you'd like to request

When using next's preview mode links via next/link are automatically prefetched as normal. 
Since preview mode bypasses SSG and ISR, both the prefetch requests and the actual requests when clicking a link are server-rendered on request. this results in a high number of SSR requests in preview mode causing high load on external APIs and hosting services like vercel.

### Describe the solution you'd like

Automatically (or via config) disable link prefetching in preview mode.

### Describe alternatives you've considered

An alternative can be passing next/routers isPreview value to the prefetch prop of next/link. but setting prefetch={false} on next/link still prefetches on mouseenter.

**Comment by jonlow** [comment]
Would love this.

With preview enabled our server is getting hit with over 20 simultaneous uncached serverless requests which take many seconds to resolve. 
[CleanShot 2021-09-13 at 18 26 51](https://user-images.githubusercontent.com/696226/133050587-914fe0fa-d04e-4361-ba4f-1e34fde697bc.png)
