### ISSUE TITLE
Router is not resolving query param without trailing slash

### ISSUE THREAD

**Issue by jpomykala** [vercel/next.js#23706]
### What version of Next.js are you using?

10.0.1

### What version of Node.js are you using?

14.0.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS, Windows

### How are you deploying your application?

next export

### Describe the Bug

For path `/foo?myparam=test`  router `next/router` won't find `myparam` parameter by using `router.query.myparam`. I need to use `/foo/?myparam=test` to make it work

### Expected Behavior

`router.query.myparam` returns `test`, when user opens `/foo?myparam=test`

### To Reproduce

`/redirect?token=my-fancy-token`

`pages/redirect.tsx`

```
export default function OAuth2RedirectHandler() {
  const router = useRouter();
  useEffect(() => {
    const token = router.query.token;
    if (token) {
      if (typeof localStorage !== "undefined") {
        localStorage.setItem(ACCESS_TOKEN, token);
      }
      router.push(DASHBOARD);
    }
  }, [router])

  return <span>Redirecting...</span>;
}
```

**Comment by mikeyharris89** [comment]
I'm having a similar issue, would love to know why my query obect in `useRouter` hook isn't registering my query params, even though i seem them in `asPath`

**Comment by bezreyhan** [comment]
We are also having this issue. We are using `next export` but also have `trailingSlash: true` in our next.config.

**Comment by CalvineHicks** [comment]
Seeing the same issue in Next.js v12.1.4

related issue: https://github.com/vercel/next.js/issues/24483

**Comment by renzit** [comment]
same here, 
trailing slash with export removes query params on prod.
any news?

**Comment by mabdh** [comment]
> I'm having a similar issue, would love to know why my query obect in useRouter hook isn't registering my query params, even though i seem them in asPath

I experience exactly the same thing like this too with Next.js v13.0.7

**Comment by ijjk** [comment]
Hi, this appears to be working properly in the latest version of Next.js `v13.1.1` so I'm gonna close this, if you are still experiencing problems with this please open a fresh issue with a minimal reproduction.
