### ISSUE TITLE
Error: invariant: progress total can not be zero

### ISSUE THREAD

**Issue by SimonSiefke** [vercel/next.js#23724]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.12.0

### What browser are you using?

-

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

-

### Describe the Bug

When running `npm run build` next js throws an error (`Error: invariant: progress total can not be zero`) and the build fails

### Expected Behavior

It builds without an error

### To Reproduce

repo: https://github.com/SimonSiefke/nextjs-progress-bug

```js
// pages/[[...slug.js]]

export default function Home() {
  return <div></div>
}

export const getStaticProps = () => {
  return {}
}

export const getStaticPaths = () => {
  return {
    paths: [], // empty for demo, usually there will be data which comes from a cms
    fallback: false,
  }
}
```

```js
// pages/_error.js
import React from 'react'

class Error extends React.Component {
  static getInitialProps({ res, err }) {
    const statusCode = (res && res.statusCode) || (err && err.statusCode)
    return { statusCode }
  }

  render() {
    return <div></div>
  }
}

export default Error
```

Run `npm run build`
The build fails with `Error: invariant: progress total can not be zero`

![screenshot](https://user-images.githubusercontent.com/23744935/113684678-c2736c00-96c5-11eb-82b7-4879dccfdbcc.png)

**Comment by ijjk** [comment]
Hi, this should be updated in `v10.1.4-canary.2` of Next.js, please update and give it a try!

**Comment by SimonSiefke** [comment]
Can confirm that `v10.1.4-canary.2` works. Thank you!
