### ISSUE TITLE
Next/Image: Blank div added on top of images in production build is separating on mobile views

### ISSUE THREAD

**Issue by NNicoletti93** [vercel/next.js#23774]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

12.x.x

### What browser are you using?

Chrome, Safari, etc.

### What operating system are you using?

Mac and Windows

### How are you deploying your application?

next start, I believe

### Describe the Bug

After upgrading to 10.1.x, images loaded using next/image on mobile sized screens seem to be separating from a wrapper div that next/image adds on top of the image in production. Downgrading does not change anything. The effect is that there is a blank space above every image about the same size as the image and the image is pushed downwards. This occurs until a hard refresh is done. I have been unable to reproduce on development builds, but every production build has this issue.

Does not happen with standard <img> tags which is why I believe it's something with next/image. I don't want to change back as we've already got all of our images loaded with next/image and by switching we lose any optimization we gain.

### Expected Behavior

The image should have the div on top of it and not above it. Should look as normal.

### To Reproduce

Load a page with images using next/image on a mobile screen. Hard refresh to fix the issue.

I'm honestly unsure how to reproduce. The issue only occurred after upgrading to 10.1.x. Since the issue doesn't occur in development it's hard to test and nothing seems to trigger it except using next/image in a production build. I apologize for not having more information on reproduction. I hope the screenshots below provide more context.

**Example of my Images component:** 
         
```
<Image
    src={my_image}
    alt={my_alt}
    layout='intrinsic'
    width='210px'
    height='248px'
    onLoad={() => setLoaded("true")}
    loaded={isLoaded || "true"}
/>
```
Below are some screenshots of what's happening, the html that's causing it, and what the page should look like. That html is added by next/image as just replacing the image with a basic <img> tag gets rid of it. 

All things identifying what the site is is blocked out - sorry if it makes it harder to understand!

**Picture of the problem:**
<img width="923" alt="Screen Shot 2021-04-07 at 10 30 07 AM" src="https://user-images.githubusercontent.com/82106447/113894258-712eaf80-978d-11eb-9531-c3a8cd92d7ce.png">

**How it should look:**
<img width="908" alt="Screen Shot 2021-04-07 at 10 34 07 AM" src="https://user-images.githubusercontent.com/82106447/113894521-b357f100-978d-11eb-9aa4-2da0bb31d5ca.png">

**Comment by MoOx** [comment]
This is a bug I noticed but not especially on mobile views (I don't have it on mobile views, I suspect you have some css that create a conflicts with next/image style for the placeholder).
Instead I am getting this serious issues on any Next.js site when using Safari Reading mode with macOS 11.3 (so Safari 14.1).

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/157534/116788843-3417bd80-aaac-11eb-9338-1bad356fd5ac.png">

I understand that `aria-hidden="true"` on img in the div is not enough. Maybe this should be on the div that wrap this base64 img.

**Comment by jahnavijanu143** [comment]
I am also facing the same issue.
when I deployed my page in vercel platform I didn't got any white spaces and in localhost also there was no white space above the image
But when I deployed my page through Docker ,I am getting the white spaces
Is this because of the platform?
any suggestions please

**Comment by Sofiane-13** [comment]
You can work around the problem: 

` <div className={styles.container}><Image src={my_image} /></div>`

`.container > div > div {
  display: none;
}
`

**Comment by hzavareze** [comment]
I'm facing the same issue:

- A blank image is placed on top of the actual image;
- This only happens in productions;
- Seen on chrome and safari;
- Refreshing makes it go away;

<img width="777" alt="Screen Shot 2022-08-25 at 12 22 34" src="https://user-images.githubusercontent.com/93603559/186705547-4f57c1a7-1ff2-401d-a924-7ad0b472033b.png">

**Comment by hzavareze** [comment]
So, I discovered this has to do with [Mirage 2.0](https://blog.cloudflare.com/mirage2-solving-mobile-speed/), a CloudFlare feature to speed up image delivery. Disabling Mirage 2.0 worked for me as a way to have images working again.

Here's other people complaining about Mirage and Next here https://github.com/vercel/next.js/issues/28810

**Comment by dogcalas** [comment]
Thanks @hzavareze , disabling mirage in Cloudflare fixed the problem.

**Comment by lachlanjc** [comment]
The new Image component in v13 also doesn’t have the wrappings divs, which should help!

**Comment by leerob** [comment]
Yep, no more wrapping divs! I think we can close this out.

https://nextjs.org/docs/basic-features/image-optimization
