### ISSUE TITLE
A Better Link

### ISSUE THREAD

**Issue by machineghost** [vercel/next.js#23778]
### Describe the feature you'd like to request

Link is ... not the friendliest component, especially for library newcomers.  For one thing, all of its documentation explicitly shows that you need to nest (redundant) `<a>` tags inside of it ... but when you do that you get:

> Warning: validateDOMNesting(...): `<a>` cannot appear as a descendant of `<a>`.

But it's not just the documentation: there's also all the issues with having to wrap Links in fragments, forward refs, etc. ... just to make what _should_ be one of the simplest/most basic building blocks of any site.

And then there's styling: it's literally impossible to style the Link tag directly (it doesn't take a `style` prop), and if you want to use a library like StyledComponents instead there are more issues there.

### Describe the solution you'd like

Give Next developers a simpler alternative (Link2? EasyLink?).  I'm sure the current `Link` handles lots of complex cases that require it's current complexity ... but surely that complexity isn't always necessary for every `<a>` on every site?

The dream version of Link would not require you to even *think* about refs to use it.  It would not require any wrapping fragments/tags to use, nor would it require redundant `<a>` tags inside.  It would take a `style` prop, be styleable with StyledComponents ("out of the box") ... and just generally it would be a drop-in replacement for an `<a>`: it would be a brain dead alternative to the current "you need a masters in React/Next.js to use this component" Link ;)

### Describe alternatives you've considered

Making a 3rd party version of such a component ... but surely this belongs in the core framework itself?  And hopefully the wealth of other Link-related issues (and all the thumbs up "votes" inside them) demonstrate the potential value?

To put it another way, if you forgot all the "plumbing" of Next.js for a moment, and asked yourself "if I could just design the easiest/simplest/most welcoming version of this component possible, what would it look like?" ... and then built *that* component (using all your knowledge of Next.js plumbing) ... I think it would be a vastly superior component to the current version, which feels (to me at least) like it was built in the opposite direction.

**Comment by leodr** [comment]
I don't think the `<Link>` component is that bad. It is not a drop-in replacement for an `<a>`-tag, but it is pretty low effort:

1. Wrap the `<a>`-tag with `<Link>`
2. Take the `href`-attribute from the `<a>`-tag and stick it onto `<Link>`

I'm also unsure if it is worth at this point to make a breaking change to the `<Link>` since virtually **every** Next.js project uses it extensively.
