### ISSUE TITLE
Firebase: No Firebase App '[DEFAULT]' has been created 

### ISSUE THREAD

**Issue by shreyas-jadhav** [vercel/next.js#23797]
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome Dev

### What operating system are you using?

Windows

### How are you deploying your application?

not deploying

### Describe the Bug

Unable to initalise app in client's browser, when window was made in scope for initialisation.

I am testing the official example, but change the window to be in scope while initialisation too.
**clientApp.js**
```js

if (!firebase.apps.length) {
  console.log("INITING");
  if (typeof window !== "undefined") {
    firebase.initializeApp(clientCredentials);
    // Check that `window` is in scope for the analytics module!
    // Enable analytics. https://firebase.google.com/docs/analytics/get-started
    if ("measurementId" in clientCredentials) {
      firebase.analytics();
      firebase.performance();
    }
  }
  console.log(firebase.app().options);
}

export default firebase;
```
**Error**
```
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```

### Expected Behavior

If I'm not wrong the Firebase Client SDK, should not be initialised on the server. But it's always getting initialised on server and client. When I run this example, I see initialised on the server terminal. So, I changed the code to be in scope of window, so that it's only initialised on browser. But then it crashes the app and SDK is not getting initialised.

### To Reproduce

1. Clone this example [https://github.com/vercel/next.js/blob/canary/examples/with-firebase](https://github1s.com/vercel/next.js/blob/canary/examples/with-firebase)

2. Change firebase/clientApp - 

```js
import firebase from "firebase/app";
import "firebase/auth"; // If you need it
import "firebase/firestore"; // If you need it
import "firebase/storage"; // If you need it
import "firebase/analytics"; // If you need it
import "firebase/performance"; // If you need it

const clientCredentials = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

if (!firebase.apps.length) {
  console.log("INITING");
  if (typeof window !== "undefined") {
    firebase.initializeApp(clientCredentials);
    // Check that `window` is in scope for the analytics module!
    // Enable analytics. https://firebase.google.com/docs/analytics/get-started
    if ("measurementId" in clientCredentials) {
      firebase.analytics();
      firebase.performance();
    }
  }
  console.log(firebase.app().options);
}

export default firebase;
```

3. See that `INITING` is console logged on the server terminal too, and then the error occurs.

**Comment by dohomi** [comment]
@shreyas-jadhav did you try without `if(typeof window!=="undefined"`? I am using firebase and let the firebase.initializeApp() without that condition.

**Comment by shreyas-jadhav** [comment]
I have tried without that condition, but the console logging of INITING on the server terminal is making me feel something is done wrong. I shouldn't be getting it on the server terminal right? If it's made for clients

**Comment by dohomi** [comment]
@shreyas-jadhav maybe try to use firebase as a component with `next/dynamic` ssr: false flag. Run firebase only wrapped inside of that outermost component.
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by shreyas-jadhav** [comment]
Thanks but I have tried using `next/dynamic` with `ssr: false` that too doesn't work! 

Actually it's wierd because, not only I'm getting console log on server but also on client terminal too (firestore responses when console logged), which means there can be 2 instances running, but when I console logged `firebase.apps` there was only one.

Is this a feature to show console logs on both terminals or a bug?

**Comment by sourcerer52** [comment]
> FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).

You're getting this error because the window object is undefined in the clientApp.js; therefore, it's not getting initialized in the first place. 

I tried recreating this, and dynamic import doesn't work for me too. 

As an alternative, you can try writing this piece of code in useEffect() instead.

I hope this fixes your problem.

**Comment by Andrewnt219** [comment]
Hi @timneutkens, I want to update this example. Do you want it to match the current firebase v9 as well?
