### ISSUE TITLE
nextjs polyfill-nomodule breaks IE11, attempts to call Array.from

### ISSUE THREAD

**Issue by kyle-ssg** [vercel/next.js#23821]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Internet Explorer 11

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

Application doesnt load in IE11, pollyfill-nomodule appaears to try to use Array.from which is unsupported 

### Expected Behavior

The application runs and polyfills are applied

### To Reproduce

N/A, just deploy a web app.

![image](https://user-images.githubusercontent.com/8608314/114043164-f2fe0600-987d-11eb-8c4d-6ee879fb16fd.png)

**Comment by kyle-ssg** [comment]
Seems related to https://github.com/vercel/next.js/issues/21130

**Comment by balazsorban44** [comment]
Hi, I could not reproduce this with a minimal `yarn create next-app` example being deployed. If you still think this is an issue, please let me know.
