### ISSUE TITLE
Internationalized domain routing includes also sub-path routing

### ISSUE THREAD

**Issue by adrianbienias** [vercel/next.js#23829]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start -p 80

### Describe the Bug

When internationalized domain routing is set, sub-path routing works as well.
That leads to multiple paths showing the same content:
- domain.com/page
- domain.com/en/page
- domain.pl/en/page

If you'll add more locales/create additional pages this problem will escalate to numerous pages showing the same content. It's certainly not good for SEO.

### Expected Behavior

When setting internationalized domain routing, sub-path routing should be disabled.

https://nextjs.org/docs/advanced-features/i18n-routing#domain-routing

https://developers.google.com/search/docs/advanced/guidelines/duplicate-content

### To Reproduce

1. Set up default Next app
```
npx create-next-app
```

2. Create `next.config.js` in the root folder
```
module.exports = {
  i18n: {
    locales: ["en", "pl"],
    defaultLocale: "en",
    localeDetection: false,
    domains: [
      {
        domain: `local.domain.com`,
        defaultLocale: "en",
      },
      {
        domain: `local.domain.pl`,
        defaultLocale: "pl",
      },
    ],
  },
}
```

2. Add the following lines to `/etc/hosts`
```
127.0.0.1 local.domain.com
127.0.0.1 local.domain.pl
```

3. Run Next server on port 80
```
next start -p 80
```

4. Now you should be able to visit the following links:

Expected:
- http://localhost/
- http://local.domain.com/
- http://local.domain.pl/

Not expected:
- http://local.domain.com/pl/
- http://local.domain.com/en/
- http://local.domain.pl/pl/
- http://local.domain.pl/en/

5. Optionally you can create example page `/pages/example.js` to see this problem more clearly.

The following links have the same content:

- http://local.domain.com/example
- http://local.domain.com/en/example
- http://local.domain.pl/en/example

**Comment by Tom-Chang-star** [comment]
I also have the same issue.
We have already set up the domains for 18 languages and the locale subpaths are included.
It's causing the issue when using getStaticPath.

**Comment by gesabehrends** [comment]
I have the same issue. Is there any chance to shut down the sub-path routing when using domain routing?

**Comment by adrianbienias** [comment]
I've fixed this issue with a workaround by handling lang sub-paths via a web server (Nginx in my case).
So all routes containing `/<some-lang>` show 404

Example for `/en` lang:
`
        location ~ ^/en(?:/(.*))?$ {
            return 404;
        }
`

**Comment by vahidtakro** [comment]
@adrianbienias I have same problem , still couldn't fix, I am using next.js on vercel, any idea?

**Comment by adrianbienias** [comment]
@vahidtakro I'm not familiar with Vercel service but I see in their docs that you can configure custom redirects with proxy deployment option
https://vercel.com/support/articles/can-i-redirect-from-a-subdomain-to-a-subpath?query=redirect
