### ISSUE TITLE
npx create-react-app --example - "Could not locate example named...."

### ISSUE THREAD

**Issue by Charlydt** [vercel/next.js#23840]
### What version of Next.js are you using?

Latest

### What version of Node.js are you using?

14.16

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I have a corporate proxy and I can't get npx create-next-app to work with any of the "--example example"
I get following error: 

"Could not locate an example named "with-typescript". Please check your spelling and try again."

Notes:
1. I have set up the following npm configs to work with my proxy
npm config set proxy proxy:port
npm config set https.proxy proxy:port
npm config set https-proxy proxy:port
2. npx create-next-app works fine
3. I have tried different examples and none of them work
4. I have also tried npx create-next-app ts --use-npm --example https://github.com/vercel/next.js/tree/canary/examples/with-typescript
I get following error: Could not locate the repository for "https://github.com/vercel/next.js/tree/canary/examples/with-typescript". Please check that the repository exists and try again.
5. I have also tried yarn and get same errors
6. If I disable the proxy and connect from home works fine

Is there any setting or configuration I am missing to get the examples to work with my proxy? I'm sorry if this is not the right place to report this issue but I'm running out of options

Thanks in advance

### Expected Behavior

If I disable the proxy, npx --example works just fine

### To Reproduce

1. npx create-next-app --example with-typescript

**Comment by PostWarnier** [comment]
What I find confusing is that in the title of this issue and in step 1 of To Reproduce you use `**create-react-app** `

**Comment by Charlydt** [comment]
sorry that was just a mistake

**Comment by Charlydt** [comment]
> What I find confusing is that in the title of this issue and in step 1 of To Reproduce you use `**create-react-app** `

Sorry that was just a typing error
