### ISSUE TITLE
Cannot read property 'gssp' of undefined

### ISSUE THREAD

**Issue by jgabriele** [vercel/next.js#23892]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Starting from `v10.0.5` my tests all fail because of the usage of `createRouter` in them. It used to work fine before that but now they throw the following error: `Cannot read property 'gssp' of undefined`.

I could reproduce this issue [with this sandbox](https://codesandbox.io/s/sweet-lumiere-z0f7h).

### Expected Behavior

Tests are not crashing when using `createRouter` in them, as per `v10.0.4`.

### To Reproduce

https://codesandbox.io/s/sweet-lumiere-z0f7h

**Comment by timneutkens** [comment]
`createRouter` and `RouterContext` are not public apis.
