### ISSUE TITLE
Building the application for production fails with collocated tests when using webpack 5.

### ISSUE THREAD

**Issue by schapka** [vercel/next.js#24067]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

none

### Describe the Bug

Given:
- Tests are collocated
- `webpack.IgnorePlugin` is used to exclude test files from build
- Webpack 5 usage is enabled

Building the application for production fails:

```bash
> nextjs-webpack5-collocated-tests@1.0.0 build
> next build

info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build
Failed to compile.

HookWebpackError: Cannot read property 'slice' of undefined

> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/rschapka/Playground-Workspace/nextjs-webpack5/node_modules/next/dist/build/index.js:17:924
    at async Span.traceAsyncFn (/Users/rschapka/Playground-Workspace/nextjs-webpack5/node_modules/next/dist/telemetry/trace/trace.js:5:584)
```

### Expected Behavior

Building the application for production should succeed with Webpack 5 and collocated test files in `/pages` directory.

### To Reproduce

I created a repository showcasing the issue within a reduced project setup:
https://github.com/edekadigital/nextjs-webpack5-collocated-tests

### 1. Install dependencies

```bash
npm install
```

### 2. Start Next.js in development mode [succeeds]

```bash
npm run dev
```

### 3. Build the application for production [fails]

```bash
npm run build
```

```bash
> nextjs-webpack5-collocated-tests@1.0.0 build
> next build

info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build
Failed to compile.

HookWebpackError: Cannot read property 'slice' of undefined

> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/rschapka/Playground-Workspace/nextjs-webpack5/node_modules/next/dist/build/index.js:17:924
    at async Span.traceAsyncFn (/Users/rschapka/Playground-Workspace/nextjs-webpack5/node_modules/next/dist/telemetry/trace/trace.js:5:584)
```

> Both moving tests to a directory outside of /pages and disabling webpack 5 option will make it work. (see `fix/*` branches)

**Comment by sabit990928** [comment]
Have the same issue, will wait for some minor version change

**Comment by la55u** [comment]
I have a similar issue when running `next build`:
`HookWebpackError: [object Object] is not a PostCSS plugin`
I'm using webpack 5 and next.js v10.2.0.
Downgrading to next v10.1.3 solves the issue but disabling webpack5 does not.

**Comment by enes-get-local** [comment]
> I have a similar issue when running `next build`:
> `HookWebpackError: [object Object] is not a PostCSS plugin`
> I'm using webpack 5 and next.js v10.2.0.
> Downgrading to next v10.1.3 solves the issue but disabling webpack5 does not.
> 
> ```
> // next.config.js
> module.exports = {
>   future: {
>     webpack5: true,
>   },
>   webpack(config) {
>     config.module.rules.push({
>       test: /\.svg$/,
>       // issuer: {
>       //   test: /\.(js|ts)x?$/,
>       // },
>       use: [
>         {
>           loader: "@svgr/webpack",
>           options: {
>             svgoConfig: {
>               plugins: {
>                 removeViewBox: false,
>               },
>             },
>           },
>         },
>       ],
>     });
>     return config;
>   },
> };
> ```

@la55u i have exactly same issue after updated next version to 10.2.0. Did you find any solution ?

**Comment by alessbell** [comment]
@la55u @enes-get-local I was seeing the same error and `rm package-lock.json && rm -rf node_modules && npm i` fixed it for me

**Comment by la55u** [comment]
>  `rm package-lock.json && rm -rf node_modules && npm i` fixed it for me

that was the first thing I tried too, but it didn't fix it for me, I had to downgrade for now.

**Comment by joshverd** [comment]
I had to downgrade to `10.1.3` to stop getting the error. Disabling/Enabling webpack5 on `10.2.x` did not change anything for me, unfortunately.

**Comment by empz** [comment]
I've just upgraded from 10 to 11.0.0 and I'm getting this error when running `next build`.

**Comment by ediblecode** [comment]
I _think_ this is an upstream problem in Webpack 5 (which Next@11 uses by default). See https://github.com/webpack/webpack/issues/13557.

One solution, as mentioned in [these](https://github.com/webpack/webpack/issues/13557#issuecomment-864574715) [comments](https://github.com/vercel/next.js/discussions/23959#discussioncomment-894210) is to use [pageExtensions](https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions). Personally I quite like the idea of having files like `blog.page.tsx` co-located with `blog.test.tsx`

An alternative that seems to work for me (although not entirely sure why) is to do the following in _next.config.js_. Note the use of both `resourceRegExp` and `contextRegExp`:

```js
const nextConfig = {
	webpack: (config, { webpack }) => {
		config.plugins.push(
			new webpack.IgnorePlugin({
				resourceRegExp: /.*/,
				contextRegExp: /__tests__/,
			})
		);
		return config;
	},
};

module.exports = nextConfig;
```

I couldn't get the same thing to work with `test.tsx` files for some reason (maybe the webpack bug) so if you're OK with just a `__tests__` folder then that's probably OK as a workaround.

**Comment by lgenzelis** [comment]
I'm dealing with the same issue. @ediblecode's alternative solution did not work for me. 😞

**Comment by empz** [comment]
Deleting node_modules and package-lock.json and doing a clean npm install fixed it for me.

**Comment by trey-m** [comment]
> Deleting node_modules and package-lock.json and doing a clean npm install fixed it for me. El 1 de jul. de 2021 01:26 +0200, Lucas Genzelis ***@***.***>, escribió:
> […](#)
> I'm dealing with the same ***@***.***'s alternative solution did not work for me. 😞 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

This worked for an issue I was having in CI/CD. For some reason the error wasn't shooting locally but only in the pipeline. With clearing node_modules and removing the yarn.lock it started shooting locally which made for a better debugging experience.

**Comment by schapka** [comment]
>
> One solution, as mentioned in [these](https://github.com/webpack/webpack/issues/13557#issuecomment-864574715) [comments](https://github.com/vercel/next.js/discussions/23959#discussioncomment-894210) is to use [pageExtensions](https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions). Personally I quite like the idea of having files like `blog.page.tsx` co-located with `blog.test.tsx`
>

Thank you @ediblecode for the hint.

I think custom page extensions are a good solution to this problem. We added a [new branch (fix/page-extensions)](https://github.com/edekadigital/nextjs-webpack5-collocated-tests/tree/fix/page-extensions) to the example repo.

IMO the problem as described in this issue is solved.

Nevertheless, there seem to be some slightly different issues mentioned in this discussion that are not solved by adding a custom page extensions to the config.
