### ISSUE TITLE
Hook router and Router have different behaviour when accessing in beforeHistoryChange event

### ISSUE THREAD

**Issue by dimisus** [vercel/next.js#24144]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14+

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

next

### Describe the Bug

Given the following hook I am memorizing the previous route/url in order to access it in components.

For example I have a page which is accessible from different routes and I want to know from which route the user came and apply different logic.

When I use the global `Router` everything works fine.
When I use `useRouter` hook the router.asPath is always the same.

```javascript
import { useEffect, useState } from 'react';
import Router from 'next/router';

const useRouteUrlHistory = () => {
  const [previousRoute, setPreviousRoute] = useState('');

  const handleBeforeHistoryChange = (url, { shallow }) => {
    if (!shallow) {
      setPreviousRoute(Router.asPath);
    }
  };

  useEffect(() => {
    Router.events.on('beforeHistoryChange', handleBeforeHistoryChange);

    return () => {
      Router.events.off('beforeHistoryChange', handleBeforeHistoryChange);
    };
  }, []);

  return { previousRoute };
};

export default useRouteUrlHistory;
```

### Expected Behavior

`router.asPath` would return the current url. Basically there should not be any difference between Router and useRouter behaviour.

### To Reproduce

Use the hook as described.

**Comment by dimisus** [comment]
Same here when I try to check to which route the user goes I would conditionally clean up by redux store.

When using `useRouter` the current pathname is returned.
When using `Router` the future/changed pathname is returned. (as expected)

```javascript
  useEffect(() => {
    return () => {
      if (!Router.pathname.includes('/some-future-route') {
        dispatch(somecleanupaction());
      }
    };
  }, []);

```

**Comment by devknoll** [comment]
I don't think this is a bug: if `useRouter` should just always be the same as the global `Router`, why have `useRouter` in the first place? 😉 

It's definitely a bit subtle and confusing though, and there's probably something we could do (documentation or otherwise) to make it clearer when you should use one over the other. The answer is that `useRouter` is a React hook, and so it is tied to the React lifecycle, and specifically refers to the route being rendered by the React tree _at that particular time_. In contrast, the global `Router` always refers to the route _right now_.

**Comment by mercteil** [comment]
Okay, thanks for clarifying. I think the docs should definitely have this statement included

**Comment by JanKaifer** [comment]
This issue is quite old and we don't have a global `Router` anymore so I'll close this.

If you think that we could improve `next/router` open a new issue.
