### ISSUE TITLE
Page crashes with "An unexpected error has occurred." when `fallback: true` is set

### ISSUE THREAD

**Issue by christiankaindl** [vercel/next.js#24198]
### What version of Next.js are you using?

10.1.0

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I get a crash with the error "An unexpected error has occurred." when using [dynamic routes](https://nextjs.org/docs/routing/dynamic-routes) with `fallback: true` and the library [jsonix](https://github.com/highsource/jsonix). The crash does **does not happen, if** the page is included via `paths` in getStaticPaths(), or if it is a regular static route. The crash only occurs on a deployment (to Vercel, did not test other platforms), not when developing locally.

<img width="1280" alt="Screen Shot 2021-04-17 at 19 25 45" src="https://user-images.githubusercontent.com/15364860/115142412-f2b1f780-a041-11eb-8c4f-6eb21844df6e.png">

In addition to the "An unexpected error has occurred." message, the Vercel console logs the following error:

```
ERROR	Error: Cannot find module 'xmldom'
```

<img width="1014" alt="Screen Shot 2021-04-18 at 12 30 19" src="https://user-images.githubusercontent.com/15364860/115142405-ea59bc80-a041-11eb-9c83-5f2edb29284b.png">

### Expected Behavior

I would expect no error to be thrown, `getStaticProps()` to finish normally and the page to be loaded successfully. My page configuration (`{ fallback: true, paths:[] }`) should work just fine. The correct behavior can be observed by

- developing locally (`npm run dev`) _or_
- serving locally (`npm run build` and then `npm run start`)

In both these cases there are no issues with the page.

### To Reproduce

I created a minimal example of a fresh Next.js install, with a single dynamic route and the jsonix library installed. The repository can be found here: https://github.com/christiankaindl/nextjs-bug-repro
The file in question is called "**[id].js**"

1) Open https://nextjs-bug-repro-2r4r9eogj-christiankaindl.vercel.app/ (a Vercel deployment from the branch `crash-fallback-true`)
2) Click the link "Go to route"
3) Observe "An unexpected error has occurred." being shown

---

In addition to the main "crash" branch **`crash-fallback-true`**, I also added two additional branches to show the issue with different configurations:

- `fallback-true-with-paths`: Shows that only routes which are not part of `paths` are affected ([Open Demo](https://nextjs-bug-repro-6v9j39qei-christiankaindl.vercel.app/))
- `no-crash-fallback-false`: Shows that the issue is not present when `fallback` is set to `false` ([Open Demo](https://nextjs-bug-repro-ldgtk3jxk-christiankaindl.vercel.app/))

**Comment by ijjk** [comment]
Hi, it looks like this is due to the `jsonix` using `amdefine` to load modules instead of `require` causing the dependencies to not be included correctly. You can manually ensure these modules are included by adding `require`s for `xmldom` and `xmlhttprequest` before `jsonix` or use a different dependency that uses commonjs syntax correctly e.g. 

```js
import 'xmldom'
import 'xmlhttprequest'
import { Jsonix } from 'jsonix'
```

**Comment by christiankaindl** [comment]
Thanks for your clear and concise explanation and code sample, I just tried it out and your solution does indeed work!

Have a great day :)
