### ISSUE TITLE
next/image Image displays wrongly with Content-Security-Policy header due to inline styles

### ISSUE THREAD

**Issue by sophiekoonin** [vercel/next.js#24309]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

12.22.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

next start

### Describe the Bug

We are using the `next/image` `Image` component to render some of our images, and they are showing up with large empty gaps above the image. The gaps disappear when we disable the Content-Security-Policy header.

There are also numerous console errors typical of CSP violations:
```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-a69d64e4-b013-4309-aeca-a31ba1ffbd9f'". Either the 'unsafe-inline' keyword, a hash ('sha256-Jm/xxsNTmsOOuRob6di/aT5qIoP490QyjtL7m5YnfWM='), or a nonce ('nonce-...') is required to enable inline execution.
```

### Expected Behavior

Expected behaviour: no console errors, and no mysterious gap above the image. Removing the CSP header is not an option.

Ideally, hash the inline styles at build time so we could pass it into the CSP. 

### To Reproduce

[Reproduction in CodeSandbox](https://codesandbox.io/s/nextimage-csp-problem-l0odg?file=/pages/index.js)

**Comment by SSylvain1989** [comment]
Hello , did you find any solution about this issue ? I have the same issue , not exactly the same  , without vercel header , all my image display fine , with vercel header , vercel header block all my image . 
But i can't find the good configuration for allow next/image to call my image ... 
Thanks 

```javascript
{
  "headers": [
    {
      "source": "/(.*)",
      "headers" : [
        {
          "key" : "X-Content-Type-Options",
          "value" : "nosniff"
        },
        {
          "key" : "X-Frame-Options",
          "value" : "DENY"
        },
        {
          "key" : "X-XSS-Protection",
          "value" : "1; mode=block"
        },
        {
          "key" :"Referrer-Policy",
          "value": "same-origin"
        },
        {
          "key" :"Content-Security-Policy",
          "value": "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com ; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' https://ssl.google-analytics.com www.google-analytics.com https://widget.prefinery.com/widget/v2/bj8el6st.js https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js https://www.google-analytics.com https://www.googletagmanager.com www.googletagmanager.com; img-src 'self' https://d2yyb7ppir675o.cloudfront.net/assets/widgets/widget-loading.gif https://website-kappa-coral.vercel.app/ https://vercel.com/ ; connect-src: https://www.google-analytics.com; frame-src 'self'  https://i.prefinery.com/;"
        },
        {
          "key" :"Permissions-Policy",
          "value": "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()"
        }
      ]
    }
  ]
}
```

**Comment by Noubissie** [comment]
@SSylvain1989 "data:https" fixes the problem but the introduction of a <scheme-source> like data: can be used by attackers too.

**Comment by styfle** [comment]
We are working on an experimental `layout=raw` which does not include inline CSS.

It looks like it will solve this problem as seen here https://codesandbox.io/s/next-image-csp-problem-forked-l85iqk?file=/pages/index.js

https://nextjs.org/docs/api-reference/next/image#experimental-raw-layout-mode

**Comment by thaddeusreid** [comment]
Looks like `layout=raw` was removed in `v12.1.1`. Any chance there is going to be an approach that does not include inline CSS @styfle ?

I'm attempting to remove the `style-src: unsafe-line` value in my Content-Security-Policy without breaking the `next/image` component.

**Comment by styfle** [comment]
@thaddeusreid It was removed in 12.2.0 in favor of next/future/image

See the blog post here: https://nextjs.org/blog/next-12-2#improvements-to-nextimage
