### ISSUE TITLE
Next.js Commerce Lighthouse Score "Preload key requests"

### ISSUE THREAD

**Issue by FBosler** [vercel/next.js#24307]
### What version of Next.js are you using?

^10.0.9-canary.5

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When running a lighthouse score on https://demo.vercel.store/ It shows a "preload key requests" - Opportunity with a saving potential of 0.75s, which is huge, given the relatively weak score for "Largest Contentful Paint"

![image](https://user-images.githubusercontent.com/14016698/115546043-d8c41f00-a2a4-11eb-8a95-80a02f960415.png)

### Expected Behavior

Would expect the lighthouse score to encounter no issues whatsoever as next.js is highly optimized for SEO.

### To Reproduce

Navigate to https://demo.vercel.store/ and run lighthouse score.

**Comment by FBosler** [comment]
This still seems to be the case.

**Comment by JanKaifer** [comment]
It's probably just a lighthouse suggestion, which doesn't mean it's a good idea.
Also, this issue is old and it's not true anymore. Closing.
