### ISSUE TITLE
`--open` flag for `next dev` to automatically open in a browser

### ISSUE THREAD

**Issue by Matt-Gleich** [vercel/next.js#24395]
### Describe the feature you'd like to request

It would be great to add a flag to the `next dev` command to have the localhost port automatically opened in the user's default browser. I would love to make a PR for this!

### Describe the solution you'd like

Sindre Sorhus's package [open](https://github.com/sindresorhus/open) seems like it would get the job done.

### Describe alternatives you've considered

I've been running `next dev && open localhost:3000` as an alternative but it isn't a cross-platform solution.

**Comment by darshkpatel** [comment]
+1 for the Feature
I'd love to help get this integrated if the devs give a green flag

**Comment by Matt-Gleich** [comment]
I should be all set but I'll definitely hit ya up @darshkpatel if I need any help :)
