### ISSUE TITLE
Returning `notFound` from `getStaticProps` causes an error during `next export`

### ISSUE THREAD

**Issue by fracture91** [vercel/next.js#24422]
### What version of Next.js are you using?

10.1.3, 10.1.4-canary.16

### What version of Node.js are you using?

14.15.3

### What browser are you using?

Firefox 89.0b3

### What operating system are you using?

Ubuntu 18.04.5 LTS

### How are you deploying your application?

next export

### Describe the Bug

If a page returns `{ notFound: true }` from `getStaticProps`, then running `next build && next export` will result in an error like the following:

```
> next-notfound-ssg-bug@0.1.0 export /home/ahurle/Documents/Programming/next-notfound-ssg-bug
> next export

info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
info  - using build directory: /home/ahurle/Documents/Programming/next-notfound-ssg-bug/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
info  - Launching 7 workers
info  - Copying "public" directory
info  - Exporting (3/3)
[Error: ENOENT: no such file or directory, copyfile '/home/ahurle/Documents/Programming/next-notfound-ssg-bug/.next/server/pages/blog/post.html' -> '/home/ahurle/Documents/Programming/next-notfound-ssg-bug/out/blog/post.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/home/ahurle/Documents/Programming/next-notfound-ssg-bug/.next/server/pages/blog/post.html',
  dest: '/home/ahurle/Documents/Programming/next-notfound-ssg-bug/out/blog/post.html'
}
```

It seems like `next export` expects an html file to be present, but there isn't one.

### Expected Behavior

No error message, `next export` finishes successfully, and visiting `/blog/post` in production results in a 404 just like when I use `next build && next start` locally

### To Reproduce

You can find a minimal reproduction with instructions in the readme here: https://github.com/fracture91/next-notfound-ssg-bug  There's also a [canary branch](https://github.com/fracture91/next-notfound-ssg-bug/compare/canary) showing the issue still exists in 10.1.4-canary.16

For a little context, my use case is I want to be able to see unpublished blog posts in dev mode, but production builds should exclude them and result in a 404.  [Here is my "real" code where I hit the problem, plus a hacky workaround](https://github.com/fracture91/ahurle-dev/blob/83922ad222cce787fec5c222182253b8e50c63ac/helpers/getBlogStaticProps.ts#L50-L54).

Another potential workaround is to avoid using `next export` in my Vercel deploy, since [my example repo seems to work fine with `next build` alone](https://next-notfound-ssg-bug.vercel.app/blog/post).

These comments look like the same problem: https://github.com/vercel/next.js/issues/19578#issuecomment-747113659  https://github.com/vercel/next.js/discussions/20355

**Comment by erosenberg** [comment]
Experiencing the exact same issue.

**Comment by Nazeeh21** [comment]
Can I work on this issue?

**Comment by agauyeung** [comment]
Hi, any update on this?

**Comment by iKonrad** [comment]
Any chance to get this merged soon?

**Comment by berkelmas** [comment]
@iKonrad Sure now waiting for the CI to pass

**Comment by fracture91** [comment]
I can confirm that the issue is fixed in the minimal reproduction, at least: https://github.com/fracture91/next-notfound-ssg-bug/pull/1

Thanks for getting this merged!

**Comment by sdjnes** [comment]
Sorry to resurrect. 

Did this change get reverted? I don't see the changes from the linked PR in the [11.1.3 release](https://github.com/vercel/next.js/blob/v11.1.3/packages/next/export/index.ts#L630). It also doesn't appear in the [patch notes ](https://github.com/vercel/next.js/releases/v12.0.5).

My project is currently sat on `11.1.2`. I'm happy to pin it to `v11.1.3-canary.25`, was just a bit confused when the canary was OK but the release wasn't.

**Comment by timneutkens** [comment]
The code is in the stable branch since 12.0.0 https://github.com/vercel/next.js/blob/v12.0.0/packages/next/export/index.ts#L631-L635. 11.1.3 is only a security patch.
