### ISSUE TITLE
Scroll restoration causing huge memory leak

### ISSUE THREAD

**Issue by VladimirMikulic** [vercel/next.js#24520]
### What version of Next.js are you using?

9.5.5

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

Android, IOS, macOS, Windows, Linux

### How are you deploying your application?

Vercel

### Describe the Bug

Scroll restoration is currently an experimental feature. I've enabled it since I needed it for infinite scroll.
After enabling it, I noticed that my app became utterly slow (scrolling).

This had a huge impact on mobile devices where Safari would simply crash my app due to a memory leak.
It seems to be related to constant URL updating.

Logs from Safari on IOS:

<img width="1285" alt="replace-state-1" src="https://user-images.githubusercontent.com/35997844/116227430-6e075d80-a754-11eb-8ca5-837235755b3b.png">

<img width="1291" alt="replace-state-2" src="https://user-images.githubusercontent.com/35997844/116227747-c3436f00-a754-11eb-8633-e10a66aa028e.png">

### Expected Behavior

I would expect scroll restoration to work without causing any memory leaks.

### To Reproduce

1) Feel free to find any blog template with Next.js
2) Enable scroll restoration
3) Open the website using physical device to see the slowdown and optionally, use BrowserStack to get logs from a virtual IOS/Android device

**Comment by JanKaifer** [comment]
Could you provide a [minimal reproduction](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template) repo, please?
It will help us debug this faster. And could you verify if this issue still exists in `next@canary`?

**Comment by VladimirMikulic** [comment]
@JanKaifer it's been a while now. I just tried it on desktop and it seems ok, but I can't verify IOS.

**Comment by JanKaifer** [comment]
Thanks for confirming.
This sounds like a serious issue so it would probably have a lot of reactions if it was still relevant.
I'll close this, but feel free to open a new one when you find another bug.
