### ISSUE TITLE
dev mode breaks when local variable _a or _b is already defined (ReactRefreshModule runtime)

### ISSUE THREAD

**Issue by wereHamster** [vercel/next.js#24570]
### What version of Next.js are you using?

10.2

### What version of Node.js are you using?

10

### What browser are you using?

all

### What operating system are you using?

macOS

### How are you deploying your application?

I wish I could

### Describe the Bug

With 10.2, create the following page:

```
import { default as _a } from "next/link";

export default function IndexPage() {
  console.log(_a);
  return <div>Hello World.</div>;
}
```

and start the server in dev mode (next dev). It fails with the following error:

```
⠁ error - ./pages/index.js
Module parse failed: Identifier '_a' has already been declared (21:8)
File was processed with these loaders:
 * ./node_modules/@next/react-refresh-utils/loader.js
 * ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js
You may need an additional loader to handle the result of these loaders.
|
| ;
>     var _a, _b;
|     // Legacy CSS implementations will `eval` browser code in a Node.js context
|     // to extract CSS. For backwards compatibility, we need to check we're in a
```

it's caused by the fast refresh plugin concatenating the source code with the runtime code (@next/react-refresh-utils/internal/ReactRefreshModule.runtime.js) which redefines _a and _b vars, causing the error.

There is no reason why ReactRefreshModule.runtime.js needs to use var, it should use let to scope the variables inside the function.

### Expected Behavior

The page works.

### To Reproduce

https://codesandbox.io/s/next-102-react-refresh-bug-qvzg5

**Comment by wereHamster** [comment]
There are a couple other names which cause this bug. Anything really that's defined as a var in https://unpkg.com/browse/@next/react-refresh-utils@10.2.0/internal/ReactRefreshModule.runtime.js. The names are:

 - _a
 - _b
 - currentExports
 - prevExports
 - isNoLongerABoundary

**Comment by ciclentfort** [comment]
This is still present in 12.0.8
