### ISSUE TITLE
Extremely huge memory consumption when resizing large images

### ISSUE THREAD

**Issue by bohdan-shulha** [vercel/next.js#24641]
### What version of Next.js are you using?

10.1

### What version of Node.js are you using?

14.0.0

### What browser are you using?

n/a

### What operating system are you using?

ubuntu, macOS

### How are you deploying your application?

remote: heroku, next start; locally: next dev

### Describe the Bug

Memory consumption spikes are caused by visiting a page where next/image scales down 1200 × 8218 image to 250x400. Usually web app consumes 100-200mb.

![image](https://user-images.githubusercontent.com/533048/116679083-c0de5080-a9b2-11eb-9f50-052297aa2539.png)

I think that Squoosh is not highly optimized at the moment as it was created "to make it easy to experiment with different image codecs, and to showcase the capabilities of the modern web" (from Squoosh v2 announcement).

I'm not sure whether it really shall be fixed today, I just wanted to warn anyone of this slightly unexpected behavior.

Solution to this issue may be adding custom 'loader' along with custom API endpoint which will resize images with the libs one likes.

### Expected Behavior

Memory consumption is much lower.

### To Reproduce

1) Start a new project
2) use next/image to resize huge image

```
          <Image
            src={image}
            alt={title}
            width={250}
            height={height}
            layout={mobile ? "responsive" : "fixed"}
            objectFit={"cover"}
            objectPosition={"top"}
          />
```

3) Watch after memory usage

**Comment by bohdan-shulha** [comment]
Seems that these tickets are related: https://github.com/vercel/next.js/issues/24052

**Comment by JanKaifer** [comment]
The related issue was fixed so I'll close this.
We will reopen if you are able to reproduce in `next@13`.
