### ISSUE TITLE
Styling between neighbouring elements swapped by `styled-jsx`

### ISSUE THREAD

**Issue by jthistle** [vercel/next.js#24680]
### What version of Next.js are you using?

10.0.1

### What version of Node.js are you using?

12.19.0

### What browser are you using?

Chromium

### What operating system are you using?

Ubuntu 20.04.2 LTS

### How are you deploying your application?

Vercel

### Describe the Bug

Styled-jsx seems to be applying a class to the wrong element. ~~To see an example of this, [visit this page](https://jamesthistlewood.co.uk/projects#community).~~ (Link no longer valid.)

The section under 'Community' should appear the same as the other sections, i.e. a line of grey, italic text, followed by a paragraph of normal, white text. However, the styles on these two elements have been interchanged somehow.

### Expected Behavior

The section under 'Community' should appear the same as the other sections, that is, without the styling swapped between the neighbouring `<p>` elements.

### To Reproduce

~~The source code for the website (in particular this part of it) [is available here](https://gitlab.com/jthistle/www/-/blob/master/pages/projects.js#L186). I have checked and double-checked it and it should work in the way that is expected. To reproduce, simply `git clone` the repo, `yarn && yarn dev` and take a look at `localhost:3000/projects`.~~ (Link no longer valid.)

This bug appears both in production and dev, and with `next@canary` too.

**Comment by blahafrank** [comment]
This is happening in my project too. I have no idea why...

https://github.com/vercel/next.js/issues/25187

**Comment by JanKaifer** [comment]
There are not many people that experienced this and the issue is quite old so it might not be relevant anymore.
Could you provide a minimal reproduction so that we are sure that it's actually a next.js bug?
https://github.com/vercel/next.js/tree/canary/examples/reproduction-template

**Comment by jthistle** [comment]
With respect, it's been a year and a half since I submitted this, and I don't care enough about this any more to pursue it further. Sorry!
