### ISSUE TITLE
next/image doesn't play nice with Safari Reader View

### ISSUE THREAD

**Issue by MoOx** [vercel/next.js#24690]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14

### What browser are you using?

Safari 14.1

### What operating system are you using?

macOS 11.3

### How are you deploying your application?

Vercel

### Describe the Bug

An image worth a thousand words:

![](https://user-images.githubusercontent.com/157534/116788843-3417bd80-aaac-11eb-9338-1bad356fd5ac.png)

And it's worst for unloaded image (they don't show up!):

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/157534/116789641-22381980-aab0-11eb-86bd-8be2af32f502.png">

### Expected Behavior

- Placeholders should not show up
- Images should all be visible

### To Reproduce

Open any website with Safari when Reader View is available that use next/image and you will notice.

Example: https://dame-bio-1mkb3jlaj-moox.vercel.app/alimentation/gateau-au-chocolat-vegan-et-sans-gluten

## What I tried

I tried to add aria-hidden on the parent div, no luck.

**Comment by evanxd** [comment]
I more prefer to say that this is a Reader View issue rather than a next.js issue. Because the data source of the reader view is coming from the DOM tree of the browser tab (Firefox does this way, I think Safari probably does the same way), which means if an image is lazy-loaded by default in the page (the `src` of the image is not valid yet at the beginning) and the reader view just doesn't render it. In the [example], images are lazy-loaded. I think that is why the reader view doesn't render it.

If you just want to see all images of the example are displayed on the reader view, you can scroll the page to the bottom at the beginning (not in the reader view yet) and all images will be loaded, then switch to reader view and you will see all images are rendered.

[1]: https://dame-bio-1mkb3jlaj-moox.vercel.app/alimentation/gateau-au-chocolat-vegan-et-sans-gluten

**Comment by JamesSingleton** [comment]
@MoOx and @evanxd I am running into this issue as well. However, the scrolling to the bottom (outside of reader view) and then switching to reader view does not show the picture. I am using Node 16.14.0, Next 12.1.5, Safari Version 15.4 (17613.1.17.1.6), and macOS Monterey v12.3. I am using TailwindCSS, but here is my example

```tsx
export default function Example() {

  return (
    <div className="bg-white">
      {/* Hero section */}
      <div className="relative bg-gray-900">
        {/* Decorative image and overlay */}
        <div aria-hidden="true" className="absolute inset-0 overflow-hidden">
          <Image
            src="https://www.maricopa-az.gov/home/showpublishedimage/2360/637008601897830000"
            alt="Copper Sky Regional Park in Maricopa, AZ"
            className="h-full w-full object-cover object-center"
            width={1920}
            height={1077}
            priority
          />
        </div>
        <div
          aria-hidden="true"
          className="absolute inset-0 bg-gray-900 opacity-50"
        />

        {/* Navigation */}
        <header className="relative z-10">
          <nav aria-label="Top">
            <ul><li>Nav Item 1</li></ul>
          </nav>
        </header>

        <div className="relative mx-auto flex max-w-3xl flex-col items-center py-32 px-6 text-center sm:py-64 lg:px-0">
          <h1 className="text-4xl font-extrabold tracking-tight text-white lg:text-6xl">
            Local Businesses in the City of Maricopa
          </h1>
          <p className="mt-4 text-xl text-white">
            The new arrivals have, well, newly arrived. Check out the latest
            options from our summer small-batch release while they&apos;re still
            in stock.
          </p>
          <a
            href="#"
            className="mt-8 inline-block rounded-md border border-transparent bg-white py-3 px-8 text-base font-medium text-gray-900 hover:bg-gray-100"
          >
            Shop New Arrivals
          </a>
        </div>
      </div>

      <main></main>

      <footer aria-labelledby="footer-heading" className="bg-gray-900">
        <h2 id="footer-heading" className="sr-only">
          Footer
        </h2>
      </footer>
    </div>
  )
}
```

If I switch that `<Image />` tag to an `<img />` everything shows up.

**Comment by styfle** [comment]
This has been fixed in the new component: `next/future/image`

https://nextjs.org/docs/api-reference/next/future/image
