### ISSUE TITLE
Cannot process DELETE request via CORS

### ISSUE THREAD

**Issue by libovness** [vercel/next.js#24731]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

15.11.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel (but I'm running it locally)

### Describe the Bug

I can process `GET` and `POST` via CORS, but cannot process `DELETE`, at least not locally. It's not even reaching my handler, so the middleware solution discussed [here](https://nextjs.org/docs/api-routes/api-middlewares) does not help.

One thing that I don't understand, and this may be he response to the `DELETE` request only includes GET and OPTIONS: 
`Access-Control-Allow-Methods: OPTIONS, GET`

### Expected Behavior

`DELETE` request reaches my handler

### To Reproduce

Add this to `next.config.js`

```
async headers() {
  return [
    {
      source: "/api/:path*",
      headers: [
        { key: "Access-Control-Allow-Credentials", value: "true" },
        { key: "Access-Control-Allow-Origin", value: "*" },
        { key: "Access-Control-Allow-Methods", value: "GET,OPTIONS,PATCH,DELETE,POST,PUT" },
        { key: "Access-Control-Allow-Headers", value: "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version" },
      ]}
  ]
}
```

Here's my api handler: 

```
import { makeUserSupabase } from '../../../../../../../../lib/initSupabase'
import Cors from 'cors'

// I added this per https://nextjs.org/docs/api-routes/api-middlewares but it makes no difference because my request is not even reaching the handler 
const cors = Cors({
  methods: ['GET', 'HEAD','DELETE'],
})

// Helper method to wait for a middleware to execute before continuing
// And to throw an error when an error happens in a middleware
function runMiddleware(req, res, fn) {
  return new Promise((resolve, reject) => {
    fn(req, res, (result) => {
      if (result instanceof Error) {
        return reject(result)
      }

      return resolve(result)
    })
  })
}

async function deleteSavedTemplate(req, res) {

  /* Code */
    
}

const main = async (req, res) => {

  await runMiddleware(req, res, cors)

  // Never logs
  console.log('we have arrived')  
  if (req.method === 'DELETE') {
    return await deleteSavedTemplate(req, res)
  } else {
    return res.status(405).end();
  }

}

export default main
```

I'm calling it like this in `/pages/index.js`
```
const headers = new Headers({
   ...supabase.storage.headers,
  'Content-Type': 'text/plain'
 })

const url = `${apiServer}/v1/users/me/templates/popular/saves/${template.id}`
  await fetch(url, {
    headers: headers,
    method: 'DELETE'              
 })
```
Where ${apiServer} is either http://localhost:8000 or our domain

**Comment by krychaxp** [comment]
i dont know if its help, but you can use https://www.npmjs.com/package/next-connect

**Comment by libovness** [comment]
thanks @krychaxp but I don't believe this will work as the request isn't even hitting my handler
