### ISSUE TITLE
next/image with priority -> preload without crossorigin="anonymous"

### ISSUE THREAD

**Issue by pecoram** [vercel/next.js#24779]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Other platform

### Describe the Bug

Setting priority on the next/image component, the image will be preloaded without crossorigin="anonymous" and not correctly preloaded:

`<link rel="preload" as="image" href="https://external/image.jpg">`

This is the warning reported:
The resource https://external/image.jpg was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### Expected Behavior

`<link rel="preload" as="image" href="image.jpg" crossorigin="anonymous">`

### To Reproduce

```
<Image
      loader={myLoader}
      src="/me.png"
      alt="Picture of the author"
      width={500}
      height={500}
      priority
    />
```

**Comment by pecoram** [comment]
up

**Comment by marcelobaez** [comment]
I can't get the priority option to work. It renders a normal <img> tag instead of <link preload>. How do you configured it? Are you using a custom loader?

**Comment by pecoram** [comment]
> I can't get the priority option to work. It renders a normal  tag instead of . How do you configured it? Are you using a custom loader?

No, just set the priority prop and you will see the preload tag inside the head, but without crossorigin.

**Comment by PudparK** [comment]
Anyone found a workaround for this?

**Comment by georgekrax** [comment]
@PudparK Same issue!

**Comment by styfle** [comment]
This was fixed in https://github.com/vercel/next.js/pull/40676
