### ISSUE TITLE
Fallback to an automatically-generated blurry placeholder

### ISSUE THREAD

**Issue by atcastle** [vercel/next.js#24875]
In PR #24153 @Joonpark13 added a feature to allow the image component to display a blurry placeholder that's passed to it in the form of a URL (inline dataURL or actual URL). Methods for automatically supplying this URL to the image component are currently in development, but I think it would also be a good idea to add a fallback behavior to the component where the specified loader is used to generate a very small (10 px wide or less) image to be used as the blurry placeholder.

The reason this is the fallback behavior rather than the intended general use case is that performance will be better if the placeholder can be rendered (as a dataURL) at serve- or build-time. Having a remote URL for the placeholder introduces an extra network round trip before the placeholder can be displayed.

Having this functionality available as a fallback will allow for wider beta testing of the blurry placeholder feature, and will help cover corner cases where we may not be able to server-side render the placeholder.

**Comment by styfle** [comment]
This was implemented in Next.js 11

https://nextjs.org/blog/next-11#image-placeholders
