### ISSUE TITLE
next/image blinks during the language change

### ISSUE THREAD

**Issue by ivnmood** [vercel/next.js#24891]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.15.0

### What browser are you using?

chrome

### What operating system are you using?

macOs

### How are you deploying your application?

next start

### Describe the Bug

During a language change in my application (I use next-i18next) `next/image` blinks

### Expected Behavior

Images should not blink during the language change

### To Reproduce

https://github.com/isaachinman/next-i18next/tree/master/examples/simple
You can use this example, just insert the `next/image` and see how the pictures blink

**Comment by choutkamartin** [comment]
@JanKaifer 
Not happening with setup below. It did happen to me on older versions, but it's fine from my perspective now.

```js
"next": "^13.0.4",
"next-i18next": "^13.0.0"
```

**Comment by JanKaifer** [comment]
Thanks for confirming.
