### ISSUE TITLE
Rewrites don't work with custom server in production mode

### ISSUE THREAD

**Issue by bkostrowiecki** [vercel/next.js#24904]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next build & next start

### Describe the Bug

If the user calls  `next` method with `dev` equal to `false` then pages defined in `rewrites` throw 404 errors.

They work fine when the method `next` is called with `dev` set to `true`.

### Expected Behavior

Rewrites should work in production mode.

When the user sets `dev` in NextJS server config to `false`, rewrites should still work.

### To Reproduce

**Here is a repository with example app**
https://github.com/bkostrowiecki/nextjs-custom-server-broken-rewrite

### In development mode
**This works as expected**
1. First run the app in development mode using `yarn dev`
2. Open the app in a browser
3. Click the link with label "c"
4. See that it works as expected and you see the page with "a"
![dev](https://user-images.githubusercontent.com/9528111/117520210-642cf800-afa7-11eb-90ce-7f49aedb2b08.gif)

### In production mode
**This is broken**
1. Build the app using `yarn build`
2. Run the app using `yarn start`
3. Open the app in a browser
4. Click the link with label "c"
5. 404 error appears
![prod](https://user-images.githubusercontent.com/9528111/117520217-698a4280-afa7-11eb-983b-b55864dd0e67.gif)

**Comment by bkostrowiecki** [comment]
@AndrewUsher thanks for quick response. Do you have a clue why they work if the configuration is provided by `next.config.js` file instead of variable in the code?

Moving files to `next.config.js` and then importing this to the seems to be a fix here, but also seems to be unexpected behavior. I noticed it's because production build generates file called `routes-manifest.json`. When I have `rewrites` in `next.config.js`, this file has `rewrites` property with all defined rewrites, so then the rewrites start to work. But if the `next.config.js` is not present, the `rewrties` property is empty and then rewrites don't work.

**Comment by JanKaifer** [comment]
Since the original issue seems to be resolved I'll close this.
Could you open a new discussion if you still have questions regarding the behavior?
