### ISSUE TITLE
next dev server crashes by default on pnpm

### ISSUE THREAD

**Issue by Kiskae** [vercel/next.js#24963]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Firefox

### What operating system are you using?

Pop!_OS / Ubuntu 20.10

### How are you deploying your application?

next dev

### Describe the Bug

With the default configuration provided by `create-next-app`, running `next dev` will fail with a webpack error when using `pnpm` as the package manager. The server continues to run but webpack does not produce a usable build/output.

### Expected Behavior

The dev server to start properly with the default app structure.

### To Reproduce

Create a new next app, then use `pnpm install` and `pnpm run dev` to install dependencies and run the dev script through `pnpm`. 

The actual source of the bug is https://github.com/webpack/webpack/issues/13339 so I've created this issue to track it.
The bug does not affect webpack 4 so setting `future.webpack5` to false will temporarily solve the issue until webpack can be updated.

**Comment by JanKaifer** [comment]
It works now with `next@13` and the webpack bug you mentioned got resolved so I'll close this now.
