### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node

### ISSUE THREAD

**Issue by darwin-morocho** [vercel/next.js#25005]
### What version of Next.js are you using?

9.5.5

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I'am implementing the facebook messenger chat using this code
```JSX
import { PureComponent } from 'react';

export default class MessengerChat extends PureComponent {
  initialized = false;

  componentDidMount() {
    if (!this.initialized) {
      this.initialized = true;
      const script = document.createElement('script');
      script.src = 'https://connect.facebook.net/es_LA/sdk/xfbml.customerchat.js';
      script.async = true;
      script.onload = () => {
        (window as any).fbAsyncInit = () => {
          (window as any).FB.init({
            xfbml: true,
            version: 'v10.0',
            appId: 220291656074258,
          });
        };
      };
      document.head.appendChild(script);
    }
  }

  render() {
    return (
      <>
        <div id="fb-root" />
        <div className="fb-customerchat" {...{ attribution: 'biz_inbox', page_id: '103155228155970' }} />
      </>
    );
  }
}
```
And importing it as 
```JSX
import dynamic from 'next/dynamic';
const MessengerChat = dynamic(() => import('./MessengerChat'), { ssr: false });
```

The first time when the page loads it works perfect, but when navigate to another page I have the next error
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
![image](https://user-images.githubusercontent.com/15864336/117864383-58b52780-b25a-11eb-82fe-d6fc268a9550.png)

Using this package https://www.npmjs.com/package/react-messenger-customer-chat I have the same problem

### Expected Behavior

The next page must work without any problem

### To Reproduce

Navigate to pages without refreshing the app

**Comment by ljosberinn** [comment]
doesn't seem related to nextjs
