### ISSUE TITLE
Build doesn't work when using Dynamic Import

### ISSUE THREAD

**Issue by shiftrtech** [vercel/next.js#25077]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

16.1.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next build

### Describe the Bug

When i try to build my app (```next build```) im getting this error:

```bash
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build

.\node_modules\next\dist\compiled\webpack\bundle5.js:114742
                                fn: str => str.startsWith(condition)
                                               ^

TypeError: Cannot read property 'startsWith' of null
    at Object.fn (.\node_modules\next\dist\compiled\webpack\bundle5.js:114742:20)

```

### Expected Behavior

A successful compilation

### To Reproduce
1.
```js
import dynamic from 'next/dynamic'

export default function BlockDynamicRenderer({ blocks = [] }) {
  return <div>
    {blocks.map(({ __typename }, index) => {
            const BlockComponent = dynamic(() =>
              import(`@/components/Blocks/${__typename}`)
            );
    })}
  </div>
}
```
2. ```next build```
3. See error

### To Bypass
When i use this on ```next.config.js``` it works:

```js

module.exports = {
  future: {
    webpack5: false
  },
}
```

**Comment by shiftrtech** [comment]
I can confirm this is related to [this](https://github.com/vercel/next.js/discussions/23498#discussioncomment-707948)

**Comment by valse** [comment]
Hi, I have issues with next/dynamic in production too after upgrading to next 10.2.1... the project built but when it is started javascript isn't executed at all: disabling webpack 5 the issue disappear
