### ISSUE TITLE
Dev server takes ages to start

### ISSUE THREAD

**Issue by amitojsingh366** [vercel/next.js#25118]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying your application?

next dev

### Describe the Bug

When i try running the dev server it takes like 5 tries to get it started. it just quits a few times with no error and other times with `Error: ENOTEMPTY: directory not empty`. Below is a screenshot of my issue:

![bug](https://cdn.discordapp.com/attachments/827969343697584161/842511568662822922/unknown.png)

note `yarn dev` just calls `next dev` in my case

### Expected Behavior

dev server should start on my first command 

### To Reproduce

- get a nextjs project
- run `next dev`

**Comment by simmbiote** [comment]
The issue you raised is not actually about the time it takes to start, but starting at all.
To avoid the ENOTEMPTY error try use this for the `dev` script in package.json:

` "dev": "rm -rf .next/ && next",`

**Comment by logan-anderson** [comment]
I am getting this error **a lot** when on windows. Is there any other solution then adding `rm -rf .next/`  to the dev script ?
