### ISSUE TITLE
Default language isn't detected correctly

### ISSUE THREAD

**Issue by beqramo** [vercel/next.js#25213]
### What version of Next.js are you using?

10.0.8

### What version of Node.js are you using?

v16.1.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

next start

### Describe the Bug

`locale` value is incorrect in `getServerSideProps` because I see even from the browser network tab and also from console.log that `accept-language` is  `sv` but locale value is `en` and I'm confused about what I'm doing wrong. 

Also, I'm using  `next-i18next` package, but I don't think  that this error is  because that package

i18n config:
```ts
 i18n: {
    defaultLocale: 'en',
    locales: ['en', 'sv'],
  },
```

getting `locale`:
```tsx
export const getServerSideProps: GetServerSideProps = async ({
  locale,
}) => {


  const lang = req.headers['accept-language']; // the value of this will be 'sv'

  ...
  };
};
```

from console.log header:
![image](https://user-images.githubusercontent.com/40486471/118615260-9ae9e600-b7d1-11eb-9b77-4e8269869266.png)

thanks
 

### Expected Behavior

value of 'locale' should be 'sv'

### To Reproduce

initiate application, set the config I have and showed you and you will see the same result

**Comment by Snouzy** [comment]
same
