### ISSUE TITLE
With-monaco-editor example is fragile - found drop-in solution

### ISSUE THREAD

**Issue by jeffscottward** [vercel/next.js#25263]
### What version of Next.js are you using?

10.0.5

### What version of Node.js are you using?

15.0.1

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

next dev

### Describe the Bug

This repo works in isolation but does not work alongside ThemeUI.
No pre-xisting config was present - just copied this example exactly.

Highly recommend this instead - worked out of the box - zero config
https://github.com/suren-atoyan/monaco-react#readme

### Expected Behavior

To load correctly given there was no prexisting config.

### To Reproduce

Add theme UI. Watch it fail on Global CSS imports.

Use this instead
https://github.com/suren-atoyan/monaco-react#readme

**Comment by jeffscottward** [comment]
https://github.com/suren-atoyan/monaco-react#for-nextjs-users

**Comment by mertcanaltin** [comment]
@jeffscottward @balazsorban44 i can provide an example for this :thinking: :rocket:

**Comment by jeffscottward** [comment]
> @jeffscottward @balazsorban44 i can provide an example for this :thinking: :rocket: 

Go for it!
I'm back to hacking on something like this for a different project and would be happy to see it happen.
