### ISSUE TITLE
Make the /_next/ URL prefix configurable

### ISSUE THREAD

**Issue by teemuy** [vercel/next.js#25334]
### Describe the feature you'd like to request

We are integrating our NextJS app into our partner's website which is also using NextJS for some of its pages, under a single URL hostname. They have a reverse nginx proxy routing traffic to each app based on URL path. We can't use basePath to prefix our application, as we have specific URL structure requirements for the integration and basePath would prefix those too. While we can rewrite some URLs in nginx, the main problem is the /_next/ URL structure clashing between the apps. To further complicate things, they are also using a language prefix in the URL and support multiple languages based on that.
SEO for the project was done before implementation was ready, and now we are unable to meet the specified URL structure.

### Describe the solution you'd like

Ability to configure a different path to be used instead of /_next/ including everything that goes under its subpaths, without affecting page URLs (as basePath does).

### Describe alternatives you've considered

basePath, assetPath, reverse proxy doing complex URL rewrites.

**Comment by davidsantucci-ph** [comment]
Same here. I really would love to see this soon.
