### ISSUE TITLE
Server Side Rendered portals - `Warning: Expected server HTML to contain a matching <h1> in <div>` 

### ISSUE THREAD

**Issue by sixclones** [vercel/next.js#25489]
### What example does this report relate to?

with-portals-ssr

### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

Windows (running on WSL)

### How are you deploying your application?

next

### Describe the Bug

```
Warning: Expected server HTML to contain a matching <h1> in <div>.
    in h1 (at pages/index.js:12)
    in Unknown (at pages/index.js:11)
    in Index (at _app.js:18)
    in MyApp
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

### Expected Behavior

A clear console without this type of error/warning.

### To Reproduce

Install the example

```bash
npx create-next-app --example with-portals-ssr with-portals-ssr-app
```

Run the project

```bash
cd with-portals-ssr-app
npm run dev
```

Open [localhost:3000](http://localhost:3000), open DevTools.

**Comment by fadhilx** [comment]
+1

**Comment by hongdeyuan** [comment]
This problem is caused by the inconsistency between the server's first rendering and the client's. We can restrict data rendering to the DOM only when the next arrives on the client.

```
// utils.js
function useMounted()
{
  const [hasMounted, setHasMounted] = React.useState<boolean>(false);

  React.useEffect(() => {
    setHasMounted(true);
  }, []);

  return hasMounted;
}
```


```
// XXComponent.jsx
export default function CollectionList(){
  const { data } = useGetCollectionQuery();// ssr data
  const hasMounted = useMounted();
  if (!hasMounted) return null;
  return {list.map(a => (
        <Link href={a.address} passHref key={a.address}>
          <Typography
            variant="h6"
            component="a"
            classes={typographyClasses}
            className={style['item']}
          >
            {a.name}
          </Typography>
        </Link>
}

```

**Comment by balazsorban44** [comment]
This appears to be fixed, as following the reproduction steps, I cannot see a warning anymore.

**Comment by hongdeyuan** [comment]
本人已收到您的邮件，辛苦了！如有重要事情，看到后，将尽快给你回复。。。
