### ISSUE TITLE
passHref: always passing the href

### ISSUE THREAD

**Issue by ybrodsky** [vercel/next.js#25516]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14.14.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

Irrelevant

### Describe the Bug

When using the `Link` component, the href is always passed down to the `<a>` tag.

```
<Link href="/something">
  <a>Something</a>
<Link>

// output
<a href="/something">Something</a>
```

The documentation states that `passHref` defaults to false, so one would expect the  `<a>` not to contain href. 
Anyway, even if you specify `passHref={false}` explicitly, it still passes down the href.

If you take a look here https://github.com/vercel/next.js/blob/canary/packages/next/client/link.tsx#L294 that conditiona will always be true. Either you have `passHref={true}` or the child is a `<a>` without href itself, like the example above `<a>Something</a>`.

### Expected Behavior

Should not passHref by default. Or at least not when specifying false.

### To Reproduce

Create a link

```
<Link href="/something">
  <a>Something</a>
<Link>
```

**Comment by LXSMNSYC** [comment]
According to the documentation, `passHref`'s role is to whether or not force the href to be passed to the children, specially if the direct children is not an anchor tag. I believe the behavior is documented well as well as expected.

https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

**Comment by ybrodsky** [comment]
Well, besides what the initial intention was with this prop, you already have a variable. Why not enforce it correctly when I say I want it to be false.
If you have links in your site that you don't care for google to index (you know rel="nofollow" is not that trustable) having `passHref={false}` can help you to stay within nextjs route without having the href in the rendered links.
