### ISSUE TITLE
redirect with parantheses in destination

### ISSUE THREAD

**Issue by rupyb** [vercel/next.js#25520]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14.16.1

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

I'm trying to write a redirect with () in the destination and receiving a error `destination` has segments not in `source` or `has` (0) for route {"source":"/apple/","destination":"/buy-gift-cards/discount-apple-\\(not-itunes\\)-cards/","permanent":true}

  async redirects() {
    return [
      {
        source: "/apple/",
        destination: "/buy-gift-cards/discount-apple-\\(not-itunes\\)-cards/",
        permanent: true
      }
    ];
  }

### Expected Behavior

to work

### To Reproduce

  async redirects() {
    return [
      {
        source: "/apple/",
        destination: "/buy-gift-cards/discount-apple-\\(not-itunes\\)-cards/",
        permanent: true
      }
    ];
  }

**Comment by wwwdepot** [comment]
Use double backslash `\\` https://nextjs.org/docs/api-reference/next.config.js/rewrites#regex-path-matching

**Comment by ijjk** [comment]
Closing per https://github.com/vercel/next.js/issues/25520#issuecomment-849854608 as this is already mentioned in the docs

**Comment by rupyb** [comment]
that doesn't work when the parentheses is in the destination

**Comment by digeverything** [comment]
Is this being looked at? I'm having a problem with the following redirect:
```
{
    source: "/old-path",
    destination: "/new-(path)",
    permanent: true
}
```
I get the following error
`'destination' has segments not in 'source' or 'has' (0) for route {"source":"/old-path","destination":"/new-(path)","permanent":true}`

If I add the backward slashes:
```
{
    source: "/old-path",
    destination: "/new-\\(path\\)",
    permanent: true,
}
```
I get the same error.
