### ISSUE TITLE
Next/Image fetching Extra sized images when there is proper image size configured 

### ISSUE THREAD

**Issue by MiltonAkash** [vercel/next.js#25523]
### What version of Next.js are you using?

10.2.2

### What version of Node.js are you using?

12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

In the Image width and height specified as 95x95 and where there is a image size configured 96. but still it fetches 256. This doesn't happen in desktop. Only happening in mobile

### Expected Behavior

It should fetch 96

### To Reproduce

https://memedb.app

The actors section images are 95x95 still in network tab you can see it fetching for 256

**Comment by joeynimu** [comment]
@MiltonAkash Could please share the code that renders the image and your config on `next.config.js`? 

[Have you tried to use the `sizes` prop](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset)?

**Comment by MiltonAkash** [comment]
**Rendering Part:** 
		<Image   priority={isATF} width="80" height="80" layout="fixed" objectFit="cover" src={`https://image.tmdb.org/t/p/w200${person.profile_path}`} />
		
		
		
**CONFIG PART**
	`
		 images: {
      domains: ['image.tmdb.org','storage.googleapis.com','images.memedb.app','firebasestorage.googleapis.com'],
      imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    },`

**Comment by JanKaifer** [comment]
This is expected behavior.
Browserpixels are logical and not physical: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio

**Comment by JanKaifer** [comment]
Also as https://github.com/vercel/next.js/issues/25523#issuecomment-850175433 mentions.
You should specify the `sizes` props if you to optimize the fetched size.
