### ISSUE TITLE
eslint rule no-document-import-in-page does not respect `pageExtensions`

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#25548]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu

### How are you deploying your application?

-

### Describe the Bug

when setting `pageExtensions` in `next.config.js` to e.g. `page.tsx`, the "no-document-import-in-page" rule included in `eslint-plugin-next` falsely warns that "next/document should not be imported outside of pages/_document.js."

### Expected Behavior

eslint rule should respect `pageExtensions`

### To Reproduce

- create next project with `yarn create next-app --typescript` and enable eslint
- add `pageExtensions: ["page.tsx"]` to `next.config.js`
- add `pages/_document.page.tsx` and see error

**Comment by pacexy** [comment]
The problem appears again in v11.1.2.
