### ISSUE TITLE
Node-sass 6 support

### ISSUE THREAD

**Issue by lavcraft** [vercel/next.js#25812]
### Describe the feature you'd like to request

Hello everyone. Im trying to use next.js with existed project on node 16. But node-sass 4/5 doesn't work with node 16.

In this case a has a conflict with next.js peer dependencies (node-sass 4 || 5) and node 16 support for old node-sass versions (it doesn't compile, fail when npm rebuild node-sass)

Native node-sass 6 support can be a good choice for node 16 users

### Describe the solution you'd like

Support node-sass (may be need only valid peer dependency, i don't know)

### Describe alternatives you've considered

I can install with `--force` flag, but error about node-sass incompatible version happened when open page after `npm run dev`

**Comment by bnn1** [comment]
It has nothing to do with Next.js. It's just `node-sass` doesn't work with latest `node` yet.

**Comment by lavcraft** [comment]
@bnn1 it's not right i guess. Because node-sass 6 support node 16 (see https://github.com/sass/node-sass/issues/3077)
next.js team should change peerDependency to allow node-sass 6 and fix related problems with node-sass
