### ISSUE TITLE
Missing polyfill for NodeList.prototype.forEach()

### ISSUE THREAD

**Issue by j-jiseophan** [vercel/next.js#25835]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

12.14.1

### What browser are you using?

Chrome

### What operating system are you using?

macOs 11.2.3

### How are you deploying your application?

Aws

### Describe the Bug

The polyfill for NodeList.prototype.forEach() is missing so that IE11 cannot call this function

### Expected Behavior

NodeList.prototype.forEach() should work in IE11

### To Reproduce

```tsx
export default function Home() {
  useEffect(() => {
    const cards = document.querySelectorAll(".card");
    cards.forEach((a) => console.log(cards));
  }, []);
 ...
}
```

**Comment by JanKaifer** [comment]
We don't support IE anymore so you need to add this polyfill yourself.
