### ISSUE TITLE
Query items decodes after redirect 

### ISSUE THREAD

**Issue by AvroraPolnareff** [vercel/next.js#26016]
### What version of Next.js are you using?

10.2.4-canary.14

### What version of Node.js are you using?

v14.15.5

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

Next tries to decode query params if you use them as a part of the route path.

### Example:
```js
// next.config.js
{
        source: "/",
        has: [
          {
            type: "query",
            key: "uid"
          }
        ],
        destination: "/:uid",
        permanent: true,
}
```
If I use this config in the redirects section of `next.config.js` and then go to the link `/uid=%2F%2F%5B%5D%3F` ->
Next tries to decode query item `uid`, then redirects to the  `///[]?` page.

### Expected Behavior

I expect redirecting without decoding of page parameters.

### To Reproduce

I created a repo that reproduces this bug:
https://github.com/AvroraPolnareff/next-redirect-url-decoded-bug

**Comment by eli-viki** [comment]
I can confirm this with Next v9.5.5 and Node 12.22.4

I have a similar scenario where 1 of my query params is a URL path.

So with a `redirects` configuration like:
```javascript
{
  source: "/original",
  destination: "/new",
  permanent: true,
}
```

If I go to something like:
```
/original?return_to=%2Fother%3Ffoo%3Dhello%26bar%3Dworld

Expected query object:
{
  return_to: "/other?foo=hello&bar=world"
}
```

It will decode the query param and merge it as part of the redirected query params like:
```
/new?return_to=/other?foo=hello&bar=world

Actual query object after redirect:
{
  return_to: "/other?foo=hello&bar=world",
  bar: "world"
}
```

I would expect that redirecting does only that: redirect to the correct destination (without decoding query params)

**Comment by rodrigo-arias** [comment]
I can confirm this with Next.js 12.1.5

**Comment by JanKaifer** [comment]
This seems to work correctly now.
