### ISSUE TITLE
Rewrite condition query matching regex breaks in older browsers

### ISSUE THREAD

**Issue by jamsinclair** [vercel/next.js#26106]
### What version of Next.js are you using?

10.2.3

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Safari <=10, IE 11, Edge 14-18

### What operating system are you using?

macOS, Windows

### How are you deploying your application?

next start

### Describe the Bug

When using a rewrite has condition regex errors are thrown in older browsers that Next.js supports.

**Error:**
```
SyntaxError: Invalid regular expression: unrecognized character after (?
```

**Stack**:
```
[native code] in RegExp
/_next/static/chunks/polyfills-283031c735651d1762e0.js in fi at line 1:37280

/_next/static/chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.7b6fc0bd183f5b80ad0c.js at line 1:5376

[native code] in every
/_next/static/chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.7b6fc0bd183f5b80ad0c.js in matchHas at line 1:5059
```

**Example condition:**
```
async rewrites() {
    return [
        {
            source: '/current-host',
            has: [
                {
                    type: 'host',
                    value: '(?<host>.*)',
                },
            ], 
            destination: '/show-host/:host',
        }
    ]
}
```

### Expected Behavior

Regex used in paths and rewrite conditions should be supported in older browsers that Next.js supports. 

### To Reproduce

1. Visit https://next-has-condition-regex-bug.vercel.app/current-host
2. In older browsers, like IE11, Safari 10.1, observe regex error `Invalid regular expression: unrecognized character after (?`
3. Otherwise, text should say: `Current host is next-has-condition-regex-bug.vercel.app`

App Source Code: https://github.com/jamsinclair/next-has-condition-regex-bug

**Comment by jamsinclair** [comment]
We do polyfill some regex features with `core-js`: https://github.com/vercel/next.js/blob/d19935c302ffd780722e6a91bb7a07060b529f3d/packages/next-polyfill-nomodule/src/index.js#L31

Unfortunately, lookbehind regex has yet to be polyfilled https://github.com/zloirock/core-js/issues/876.

**Comment by JanKaifer** [comment]
We don't support these browsers anymore.
