### ISSUE TITLE
[NextJS11] Styled Components and Material Ui Styles stopped displaying after upgrade to NextJS 11

### ISSUE THREAD

**Issue by SushritPasupuleti** [vercel/next.js#26184]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.0.0

### What browser are you using?

Chrome, Edge

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

Just updated to NextJS 11 and the styles stopped working all of a sudden. They render for a second and immediately disappear, like a short flash of the right styles and gone. Making a change in the editor temporarily returns the styles but on a fresh reload they never appear.

It looks like this: 

![localhost_3000_users_sushrit_lawliet - Copy](https://user-images.githubusercontent.com/14891901/122215636-115d2f00-cec9-11eb-9671-e97b675fb4fb.png)

I've applied all the necessary boilerplate to run styled-components and material-ui together from [here](https://github.com/nblthree/nextjs-with-material-ui-and-styled-components)

All help is appreciated! This is my first time posting an issue here, hope everything relevant has been attached, if not do let me know :)

### Expected Behavior

![localhost](https://user-images.githubusercontent.com/14891901/122215235-9b58c800-cec8-11eb-9213-85dcdbad6f93.PNG)

I've a basic page with steppers and the whole thing is wrapped in a style component that handles grids. This is how it looked until the upgrade was done. I rolled back a few times to check, and it still works in the older version.

### To Reproduce

Grab the code from [here](https://github.com/nblthree/nextjs-with-material-ui-and-styled-components) and add a few steppers or any material-ui components from [here](https://material-ui.com/components/steppers/#vertical-stepper).

**Comment by pixelass** [comment]
We encountered this issue when we used `webpack5` in v10.
We removed `{future: {webpack5: true}}`

For v11 `webpack5` was moved from `future` to the first level of the next.config.js.
Try disabling it and see if it helps.

SIDENOTE: For us only certain elements were missing styles while most others didn't have an issue.

**Comment by finnan444** [comment]
It is somehow connected with className mismatch between server and client rendering

<details>
 <summary>Screenshot</summary>

![Screenshot from 2021-06-16 13-33-42](https://user-images.githubusercontent.com/28092100/122217381-08169700-ceb6-11eb-9064-425c96657696.png)
</details>

**Comment by SushritPasupuleti** [comment]
> It is somehow connected with className mismatch between server and client rendering
> 
> Screenshot
> ![Screenshot from 2021-06-16 13-33-42](https://user-images.githubusercontent.com/28092100/122217381-08169700-ceb6-11eb-9064-425c96657696.png)

Yes I noticed the same happening each time. Never had this happen before.

**Comment by SushritPasupuleti** [comment]
> We encountered this issue when we used `webpack5` in v10.
> We removed `{future: {webpack5: true}}`
> 
> For v11 `webpack5` was moved from `future` to the first level of the next.config.js.
> Try disabling it and see if it helps.
> 
> SIDENOTE: For us only certain elements were missing styles while most others didn't have an issue.

@pixelass I've the same issue, some components render perfectly, but I tried commenting the lower level components one by one, can't really seem to find the root cause.

Will try forcing webpack 4 once.

**Comment by SushritPasupuleti** [comment]
UPDATE: disabling webpack5 manually in the config did not yield any changes.

The console shows a warning that is of the form:

```
 Prop `className` did not match. Server: "x-1" Client: "x-2"
```

Simplified the names so that it is more readable.

I did notice other components making use of Styles with a `className` to be working perfectly.

**Comment by BowlingX** [comment]
Same problem here, but it only seems to affect prerendered pages (`getStaticPaths`, `getStaticProps`) to me, pages with `getInitialProps` work properly. It seems like the render process executes multiple times which yields undefined behavior.

**Comment by BowlingX** [comment]
The issue is present since `10.2.2` in my case. `10.2.0` works well.

**Comment by SushritPasupuleti** [comment]
> The issue is present since `10.2.2` in my case. `10.2.0` works well.

I was running 10.1.3 until yesterday. So yeah I guess this has remained unfixed.

**Comment by sdornan** [comment]
Having the same issue, but in my case falling back to webpack v4 fixes the issue. Slows down my builds quite a lot though versus v5.

**Comment by IskanderMustafin** [comment]
Experiencing same problem here.
 - Can confirm that setting `webpack5: false` fixes it
 - In my case page uses `getServerSideProps`
 - Console error: `Warning: Prop `className` did not match. Server: "PrivateNotchedOutline-legendLabelled-50" Client: "PrivateNotchedOutline-legendLabelled-32"` 
 -  I could find component causing problem (custom autocomplete component built on top of Downshift) - if I commenting out it then all works fine. But weird thing is that I'm using exactly same component in another page and that another page works properly

**Comment by SushritPasupuleti** [comment]
> Experiencing same problem here.
> 
> * Can confirm that setting `webpack5: false` fixes it
> * In my case page uses `getServerSideProps`
> * Console error: `Warning: Prop `className` did not match. Server: "PrivateNotchedOutline-legendLabelled-50" Client: "PrivateNotchedOutline-legendLabelled-32"`
> * I could find component causing problem (custom autocomplete component built on top of Downshift) - if I commenting out it then all works fine. But weird thing is that I'm using exactly same component in another page and that another page works properly

Same problem, the component renders perfectly on another page. But the issue is, both pages are roughly the same, only some text has changed between them.

**Comment by SushritPasupuleti** [comment]
Found a solution, in my case the components that were failing were conditionally rendered based on authentication. This caused the problem where for a second there was unauthenticated content and then authenticated content is rendered once auth data is acquired, so during that flash the classnames would change because a different component altogether was rendered.

To counter this, I used a component to wrap such components, which triggers a re-render immediately after first render.

```js
function ClientOnly({ children, ...delegated }) {
  const [hasMounted, setHasMounted] = React.useState(false);
  React.useEffect(() => {
    setHasMounted(true);
  }, []);
  if (!hasMounted) {
    return null;
  }
  return (
    <div {...delegated}>
      {children}
    </div>
  );
}
```

You would pass your component like so: 

```js
<ClientOnly>
  <ConditionalTroublesomeComponent />
</ClientOnly>
```

**Comment by SushritPasupuleti** [comment]
Found a solution, in my case the components that were failing were conditionally rendered based on authentication. This caused the problem where for a second there was unauthenticated content and then authenticated content is rendered once auth data is acquired, so during that flash the classnames would change because a different component altogether was rendered.

To counter this, I used a component to wrap such components, which triggers a re-render immediately after first render.

```js
function ClientOnly({ children, ...delegated }) {
  const [hasMounted, setHasMounted] = React.useState(false);
  React.useEffect(() => {
    setHasMounted(true);
  }, []);
  if (!hasMounted) {
    return null;
  }
  return (
    <div {...delegated}>
      {children}
    </div>
  );
}
```

You would pass your component like so: 

```js
<ClientOnly>
  <ConditionalTroublesomeComponent />
</ClientOnly>
```

Hope this helps the other people here too!

**Comment by BowlingX** [comment]
I also found my issue. In my case, I had an accidental global imports from the material-ui package of the `Paper` component which caused this issue to break on webpack5. It seems like it returns 2 different instances.

`import { Paper } from 'material-ui'` ❌  vs `import Paper from 'material-ui/core/Paper'` ✔️

This was causing duplicate styles for the `Paper` component yielding to mismatches on the server/client.

**Comment by oliviertassinari** [comment]
These two imports point to the same module. It shouldn't matter where you import from.

**Comment by BowlingX** [comment]
Yes I agree, I also found another problem; The same issue seems to happen with the `SvgIcon` component.

**Comment by dohomi** [comment]
I discovered similar like @SushritPasupuleti that from NextJS 10.2.2 onwards client-side code would fail with class hydration errors. The NextJS solution for components which rely on login or other interaction is using 
```js
dynamic(() =>import('./path/to/component.tsx'),{ ssr: false })
```
It seems that the compilation is more strict now in newer versions, especially with the use of webpack5

**Comment by Anam0927** [comment]
I have the same problem but the weird thing is that the classes I've applied using Material UI's `makestyles` are being applied correctly. Only the native Material UI classes are not being applied...
Could it still be related to conditional rendering of components?

**Comment by BowlingX** [comment]
I think the issue should be reopened. @Anam0927 I have the same issue, it's only related to the third-party imports which seem to export different instances of the component based on from where they are imported (root or subfolder). It's not related to conditional renderings, but this will of course solve the problem because they are rendered only on the client.

**Comment by dohomi** [comment]
@BowlingX @Anam0927 just check the props both on server and client run, in the component where it happens you will see a difference where you apply styles (className) 
For me it was also a scroll-listener to apply different styles in a toolbar. So just be aware that all props has to be the same on server and client otherwise extract that part and render it on client side only (or adjust the default props)

**Comment by Anam0927** [comment]
> @BowlingX @Anam0927 just check the props both on server and client run, in the component where it happens you will see a difference where you apply styles (className) 
> For me it was also a scroll-listener to apply different styles in a toolbar. So just be aware that all props has to be the same on server and client otherwise extract that part and render it on client side only (or adjust the default props)

You were right! Thanks a lot! Even in a few small components I realised that if the props change between server and client, flash of un-styled content was seen.

For anyone else stumbling here, must probably you've some conditional rendering where you're passing the condition as prop, whether it be for a page component or otherwise. Try to remove that, maybe using a `useEffect` hook, and it should work.

**Comment by abriginets** [comment]
Is there any progress on this ticket? Disabling webpack5 did not help in my case and using workarounds from the comments is not really a fix. Do we know who needs to fix that - NextJS team or MUI team?

**Comment by dohomi** [comment]
@abriginets I there is no workaround needed just make sure server and client side props are equal, if not you need to conditionally render them differently

**Comment by abriginets** [comment]
@dohomi but Webpack 5 in NextJS 11 is breaking the styles in Material-UI. I tried to use MUI v5 beta recently and couldn't even fix that by disabling webpack5. This seems to be making it imbossible to use those frameworks alongside anymore.

**Comment by pixelass** [comment]
Differences in server and client props are not always the cause of this issue. While this helped for "some" of the reporters here it might not fix the issue for others.

We experienced it in one project with many components/pages (larger code-base) while it does not happen in a different repo that has just been set up and only has a few components (small code-base). 

For some people webpack5 was causing the issue, for others the version `10.2.x` introduced this issue (https://github.com/vercel/next.js/issues/26184#issuecomment-862426926)

This is also the reason why this is hard to replicate or provide a Reproduction-repo to allow finding the root cause. 

Suggesting fixes is the correct way to help solve this issue but keep in mind that the root cause is not always the same and therefore your recommendation might not be valid in all cases.

Since this issue has been closed I suggest reopening it  or referencing it in a new issue, tackling the problem to help find a solution.

Thank you 
# 💖

**Comment by dohomi** [comment]
@abriginets I use Material-UI v5 and NextJS 11 + webpack5 without any issues. I guess there must be some mistake of your setup did you follow the most recent changes in MaterialUI?

**Comment by felixkoch** [comment]
@dohomi Thanks a lot for pointing out the new example! In combination with mitigating this MUI Bug it works like a charm.

https://github.com/mui-org/material-ui/issues/27174

**Comment by camoore1979** [comment]
@dohomi does @emotion/react have to be used to get this to work?? Per your link to this example: https://github.com/mui-org/material-ui/tree/next/examples/nextjs-with-typescript.

**Comment by oliviertassinari** [comment]
@camoore1979 If you are looking to use styled-components, see https://github.com/mui-org/material-ui/tree/HEAD/examples/nextjs-with-styled-components-typescript.

**Comment by dohomi** [comment]
@camoore1979 I don't know which approach you follow. Just checkout the very good examples of MUI and pick what you need: https://github.com/mui-org/material-ui/tree/next/examples

**Comment by SushritPasupuleti** [comment]
Another problem to note when using Something like Material UI treasury which comes with it's own Theme Provider, do not nest that on the app level `_app.js` it will cause problems with styling and the same error pops up.
