### ISSUE TITLE
Script with "beforeInteractive" strategy and innerHTML rendered incorrectly.

### ISSUE THREAD

**Issue by LXSMNSYC** [vercel/next.js#26240]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

15.4.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

Scripts with `"beforeInteractive"` strategy and `dangerouslySetInnerHTML` or inlined script incorrectly renders scripts in SSR.

Code:
```tsx
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Script from 'next/script'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Component {...pageProps} />
      <Script strategy="beforeInteractive">
        {'console.log("DYNAMIC INLINE SCRIPT RENDERED");'}
      </Script>
      <Script
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{ __html: 'console.log("dangerouslySetInnerHTML SCRIPT RENDERED");' }}
      />
    </>
  )
}

export default MyApp
```

Output (notice the `src(unknown)`
![image](https://user-images.githubusercontent.com/4783372/122336725-dcf07e00-cf6f-11eb-8f06-463e29c7063a.png)

Codesandbox: https://codesandbox.io/s/github/LXSMNSYC/next-script-beforeinteractive-repro

### Expected Behavior

It should correctly render the scripts on server-side.

### To Reproduce

Reproduction mentioned and linked above

**Comment by LXSMNSYC** [comment]
It's been 2 months. Hope there's an action for this.

**Comment by devanshj** [comment]
Probably it's because of https://github.com/facebook/react/issues/13838
