### ISSUE TITLE
Failing build when deployed to vercel or netlify

### ISSUE THREAD

**Issue by ExpressGradient** [vercel/next.js#26302]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.15.0

### What browser are you using?

Firefox Developer Edition

### What operating system are you using?

Windows 10

### How are you deploying your application?

Vercel and Netlify

### Describe the Bug

I have a blog built with Next.js and MongoDB.
It's Static Generated with ISR.
When I run build locally, everything works fine.
But when I deploy to vercel or netlify, build fails while generating the latest page.
The error is 
```
Error occurred prerendering page "/blog/<blog_name>". Read more: https://nextjs.org/docs/messages/prerender-error
```
also
```
> Build error occurred
Error: Export encountered errors on following paths:
/blog/<blog_name>
```

### Expected Behavior

Expected behavior is to deploy without no problems. Since everything worked fine locally.

### To Reproduce

You can clone my [github repo](https://github.com/ExpressGradient/praneeth) and deploy it to reproduce the failing build error.

**Comment by timneutkens** [comment]
https://github.com/ExpressGradient/praneeth/blob/main/pages/blog/%5Bslug%5D.tsx#L56
https://github.com/ExpressGradient/praneeth/blob/main/pages/blog/%5Bslug%5D.tsx#L60

You likely return a path named `<blog_name>`
