### ISSUE TITLE
next/script using beforeInteractive strategy don't work with alert

### ISSUE THREAD

**Issue by dudusotero** [vercel/next.js#26343]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When I try to add next/script into "_document" or "_app" files calling a inline alert function, don't work using beforeInteractive strategy, but when I don't explicitly inform a strategy value, it works.

![image](https://user-images.githubusercontent.com/7073199/122619470-e4468300-d066-11eb-8050-84552e1bfa99.png)

### Expected Behavior

Should work with beforeInteractive strategy inside _document.js or _app.js.

### To Reproduce

Just add ```<Script strategy="beforeInteractive">{`alert('Not work')`}</Script>``` to _document.js or _app.js, and try to run with ```next build && next start```.

**Comment by balazsorban44** [comment]
The docs says it shouldn't be used inside `_document`

https://nextjs.org/docs/basic-features/script

haven't tried `_app`

**Comment by prichodko** [comment]
@balazsorban44 is correct regarding the `_document` usage.

There is an issue, however, with a `next/script` used as a `children` or through `dangerouslySetInnerHTML` and `beforeInteractive` strategy.

In this case the value of `src` is `(unknown)`:

![image](https://user-images.githubusercontent.com/14926950/122649821-17087e00-d130-11eb-941c-8f112b0744f6.png)

Looking at this line https://github.com/vercel/next.js/blob/canary/packages/next/client/script.tsx#L120, the default value of `src` is set to empty string, which seems to be propagated to the DOM element as the `unknown` value.

**Comment by prichodko** [comment]
Related: https://github.com/vercel/next.js/issues/26240

**Comment by janicklas-ralph** [comment]
Hi. Apologize for the delayed response. An update on this - It was intentional to not allow inline scripts with beforeInteractive since we noticed it hurt performance. I'm working on adding another strategy to load inline scripts with beforeInteractive.

**Comment by zmarty** [comment]
Thanks, we need this to load the [Application Insights JS SDK](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#snippet-based-setup)

**Comment by prichodko** [comment]
@janicklas-ralph thanks for the heads-up.

My initial idea was to insert a simple code that checks for the presence of the authentication token. But then I had a moment of realization. Isn't inline script together with `beforeInteractive` strategy same as this code?

```js
<Head>
  <script dangerouslySetInnerHTML={{
              __html: ` // your code here`
    }}
  />
<Head />
```js

**Comment by prichodko** [comment]
Another use-case is a code that detects user selected light / dark theme, to avoid flickering on the first load.

**Comment by durdenx** [comment]
Is `next/script` working in _app ?

**Comment by balazsorban44** [comment]
Per the docs, _app is fine:

> Note:
next/script must not be placed in either a next/head component or in pages/_document.js.

https://nextjs.org/docs/basic-features/script#usage

**Comment by RyanClementsHax** [comment]
> Per the docs, _app is fine:
> 
> > Note:
> > next/script must not be placed in either a next/head component or in pages/_document.js.
> 
> https://nextjs.org/docs/basic-features/script#usage

@durdenx `_app` is fine, although be aware of rehyrdation errors as the code that gets interpolated into the script may differ between client and server.

**Comment by RyanClementsHax** [comment]
> @janicklas-ralph thanks for the heads-up.
> 
> My initial idea was to insert a simple code that checks for the presence of the authentication token. But then I had a moment of realization. Isn't inline script together with `beforeInteractive` strategy same as this code?
> 
> ```js
> <Head>
>   <script dangerouslySetInnerHTML={{
>     __html: ` // code here`
>   }}
>   />
> <Head />
> ```



> Another use-case is a code that detects user selected light / dark theme, to avoid flickering on the first load.

Funny enough you should mention it, this is exactly the use case and strategy that Josh Comeau writes about in his article on how to achieve the [perfect dark theme](https://www.joshwcomeau.com/react/dark-mode/), and how Brian Lovin implemented this technique in [his personal site which is written using nextjs](https://github.com/brianlovin/brian-lovin-next/pull/627)

Side note: if anyone is happening to stumble on this looking to load scripts before interactive using this component, it seems to not work on version 12 of next either.

**Comment by imsamad** [comment]
It would not work , bcoz in inline Script only "lazyOnload" and afterInteractive" strategies are are allowed .

**Comment by mishrsoumitra** [comment]
Should this not be added to the docs that dangerouslySetInnerHTML does not work with beforeInteractive strategy?

**Comment by incompletude** [comment]
Can confirm the following works:

```typescript
/* global globalThis */

import styled from "@emotion/styled"
import { useTheme } from "@mui/material"
import Script from "next/script"
import React, { useEffect, useRef } from "react"
import { Head } from "src/components/head"
import { Env } from "src/utils/env"

type AdyenWindow = Window &
  typeof globalThis & {
    AdyenCheckout: {
      new ({}: { locale: string; environment: string; clientKey: string; onChange: (state: any) => void }): any
    }
  }

type Props = {
  onChange: (isValid: boolean, card: string | undefined) => void
}

const Adyen = ({ onChange }: Props) => {
  const theme = useTheme()

  const divRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const interval = setInterval(() => {
      const { AdyenCheckout } = window as AdyenWindow

      if (AdyenCheckout) {
        clearInterval(interval)

        const checkout = new AdyenCheckout({
          locale: "pt-BR",
          environment: Env.ADYEN_ENVIRONMENT,
          clientKey: Env.ADYEN_CLIENT_KEY,
          onChange: (state: any) => onChange(state.isValid, state.isValid ? state.data.paymentMethod : undefined),
        })

        checkout.create("card").mount(divRef.current)
      }
    }, 250)
  }, [])

  // https://docs.adyen.com/online-payments/web-drop-in/customization#css-stylesheet

  const AdyenContainer = styled.div`
    .adyen-checkout__card-input {
      background-color: ${theme.palette.primary.main};
    }
  `

  return (
    <>
      <Head>
        <link
          rel="stylesheet"
          href={`https://checkoutshopper-${Env.ADYEN_ENVIRONMENT}.adyen.com/checkoutshopper/sdk/4.7.4/adyen.css`}
          integrity="sha384-9+LIlWSGAUQhUPJw1dx4xYnF4Z7wNrR+PqDBpWokR+LuOjpusXig9yZsqMslp3Er"
          crossOrigin="anonymous"
        />
      </Head>

      <Script
        src={`https://checkoutshopper-${Env.ADYEN_ENVIRONMENT}.adyen.com/checkoutshopper/sdk/4.7.4/adyen.js`}
        integrity="sha384-lIc4bWIO4g4PCmTLvsRFsCBCszdsZiUJSqxuBUDh5IQjyBW+Ng4YywRTtpMRkHMM"
        crossOrigin="anonymous"
      />

      <AdyenContainer ref={divRef} />
    </>
  )
}

export { Adyen }
```

**Comment by MincePie** [comment]
Where do I put scripts if I can't put them in _document?

**Comment by prichodko** [comment]
Wherever you want. If you need it on every page, then `_app`.

**Comment by MincePie** [comment]
Does it go inside the head tag of _app?

**Comment by prichodko** [comment]
Nope, this should work:

```js
import Script from 'next/script'

export default function App() {
  return (
    <>
      <Script src="https://www.google-analytics.com/analytics.js" />
      <h1>Hello, world!</h1>
    </>
  )
}
```

**Comment by xd-hearst** [comment]
seems the narrative has changed regarding this in the doc: https://nextjs.org/docs/basic-features/script

It is stated that:

`This strategy only works inside _document.js and is designed to load scripts that are needed by the entire site (i.e. the script will load when any page in the application has been loaded server-side).`

However, if you try with their example, it does not work at all:

```
// In _document.js
import { Html, Head, Main, NextScript } from 'next/document'
import Script from 'next/script'

export default function Document() {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js"
          strategy="beforeInteractive"
        ></Script>
      </body>
    </Html>
  )
}

```

Put it in the app does work.

**Comment by martinnabhan** [comment]
We have the same issue. As soon as we moved our next/script polyfills to _document we started catching errors from our users. Moving the script tags back to _app solved it.

**Comment by firebirdsonic** [comment]
Same

> We have the same issue. As soon as we moved our next/script polyfills to _document we started catching errors from our users. Moving the script tags back to _app solved it.

Same here. Script doesn't load and appear in the dom when script is used in _document. I tried it with the example nextjs app and add the code they used on their site.

**Comment by balazsorban44** [comment]
Please try the `next@canary` release. If you still see this issue, please open an issue with a reproduction.

**Comment by aboqasem** [comment]
Hi @balazsorban44, here is an issue regarding the problem https://github.com/vercel/next.js/issues/37741

**Comment by xd-hearst** [comment]
Sorry for saying this, but I think it is bad that next js official doc continues to leave the non-working/erroneous example out there. Knowingly.

**Comment by balazsorban44** [comment]
Sorry for the confusion here, let me try to explain.

Yes, the narrative has changed, when using `Script` together with the `beforeInteractive` strategy, it should now be placed in `_document`. (Reflected in the docs now, and explained why. Please see https://nextjs.org/docs/basic-features/script#beforeinteractive.)

The way it currently works is only if you put `Script` in `Head`. There is a known issue when `Script` is in `Body` as pointed out https://github.com/vercel/next.js/issues/26343#issuecomment-1157267569

We are aware of that, please see: https://github.com/vercel/next.js/issues/37741#issuecomment-1157358712, and going to fix this soon!

Hope that helps! :green_heart:

**Comment by balazsorban44** [comment]
@rmuratov please create an issue with a reproduction and we can have a look! :pray:

**Comment by andrewfritz86** [comment]
This is working perfectly now for me in at `12.1.7-canary.44`. Would highly recommend throwing something in the official documentation to highlight that the `Script` component in the `_document` does not work as described in the current stable release.

**Comment by timneutkens** [comment]
12.2 is out since yesterday!
