### ISSUE TITLE
Proposal: "Wrapper" component for groups of routes in folders

### ISSUE THREAD

**Issue by cassidoo** [vercel/next.js#26371]
### Describe the feature you'd like to request

Right now, it's difficult to share state across only *some* routes. There's a very "all or nothing" approach to sharing state with just React's `useState`/`useReducer` + Context in `_app.js`. You can work around that (or use libraries like swr and react-query), but it's not very intuitive nor ergonomic.

I'm proposing that there's some kind of "wrapper" component for groups of routes in folders, as seen below.

### Describe the solution you'd like

I'm proposing a folder structure similar to this example:

```
pages/
  examplefolder/
    _index.js
    route1.js
    route2.js
  examplefolder2/
    examplefolder3/
      _index.js
      route3a.js
      route3b.js
    _index.js
    route4.js
    route5.js
  _app.js
  index.js
  ...

```

If this could exist in Next.js, where `_index.js` (or some other file name) could "wrap" the other files in that `example` folder, that would be a really sleek solution to sharing state across groups of routes.

As a developer, I would expect the `_index.js` files would act on files in their folder just like `_app.js` does for an entire Next.js application. A developer would able to wrap that component in a Context, or query data, or set up a layout from there.

A solution like this would make for almost a "microsite" type of structure across folders in an app, allowing developers to intuitively make shared layouts and state and have a solid separation of application "sections".

### Describe alternatives you've considered

There are some escape hatches built in now for this that aren't very intuitive. The easiest solutions are using swr and react-query, but it would be nice to have a more "vanilla React" way of doing it.

**Comment by antoinegag** [comment]
Would be cool if that wrapper could also allow for specific rendering. 

For exemple rendering a specific header above every route in a folder without having to include it in every single route or a global navbar (and so on)

**Comment by cassidoo** [comment]
> Would be cool if that wrapper could also allow for rendering stuff for all routes.
> 
> For exemple rendering a specific header above every route in a folder without having to include it in every single route or a global navbar (and so on).

Yes @antoinegag! That's what I meant by "set up a layout from there" exactly. Being able to do it this way would reduce the need to use external libraries [like this one](https://github.com/moxystudio/next-layout) to make easy layout groups.

**Comment by gavinsharp** [comment]
I really like the idea of having a built-in mechanism like this one, it's something I've had to re-create in a couple of different Next apps so far.

I wonder whether tying this to directory tree/routing might be overly restrictive, though. I could see people wanting to specify shared wrapper/layouts with more granularity than what this would allow (i.e. on a page-by-page basis). Maybe a named export on the page could be used to reference a wrapper/layout instead? I guess that would make it more annoying to have the same wrapper used on _all_ pages, so maybe that is just a different proposal with a different set of use cases :)

**Comment by apkoponen** [comment]
Would the wrappers in nested _index.js files override or ”merge” with their top-level wrappers?

E.g. if the `examplefolder2/_index.js` has `<ExampleWrapper2 />` and `examplefolder3/_index.js` has `<ExampleWrapper3 />` should `route3a.js` have both or just `<ExampleWrapper3 />`?

**Comment by Skn0tt** [comment]
This is an interesting proposal! My initial reaction was "ugghh, that sounds complicated". I've yet to fully grasp the difference between `_app` and `_document`, and I'd prefer to not have to learn about `_index`.

Though on second though, I'm growing to like it! Especially the Layout part of it, which allows for much easier nested layouts compared to the [getLayout](https://adamwathan.me/2019/10/17/persistent-layout-patterns-in-nextjs/) pattern.

@apkoponen To enable both nested layouts and deep-nested paths that don't share layout, I'd imagine this to be configurable. Maybe even by importing `ExampleWrapper2` in `ExampleWraper3`:

```ts
import ExampleWrapper2 from "../_index"

export default function ExampleWrapper3(props) {
  return (
    <ExampleWrapper2>
      <h1>This is a header</>
      {props.children}
    </ExampleWrapper2>
}
```

Some more questions:
- would `_index` have support for `getStaticProps` or `getServerSideProps`?
- what are the tradeoffs of this proposal compared to the [getLayout](https://adamwathan.me/2019/10/17/persistent-layout-patterns-in-nextjs/) pattern?

**Comment by JReinhold** [comment]
You all might want to look into SvelteKit's nested layouts for inspiration which is exactly this.

https://kit.svelte.dev/docs#layouts-nested-layouts

**Comment by nandorojo** [comment]
I have a `/dashboard` path with 8 nested screens inside of it: `/dashboard/calendar`, `/dashboard/account`, etc.

These pages all share a common layout that isn’t used anywhere else. It would be awesome to have an `_app.js` used only for those routes. 

At first, to solve this, I conditionally rendered the `/dashboard` layout  component based on `router.pathname` in `_app.tsx`. But it felt wrong for this to be positioned globally, so now I manually wrap every page inside of `/dashboard` with the layout provider. 

This proposal would be a much more elegant solution.

I’d prefer a name other than `_index.js`, since I often use this file name in other parts of my app. But that’s a minor point, and @cassidoo doesn’t seem too tied to the name.
