### ISSUE TITLE
Image of next/image puts <img> tag inside <div>

### ISSUE THREAD

**Issue by shehi** [vercel/next.js#26481]
### Describe the feature you'd like to request

When using `Image` of `next/image`, `<img>` tags generated are placed inside a new `<div>` tags. This shouldn't be happening, as it is affecting our semantic-markup considerations. 

### Describe the solution you'd like

Please remove that extra `<div>` and put its styles to the actual `<img>` tag. Both can act as block-level tags, why introduce a new, unnecessary one?!

### Describe alternatives you've considered

None. I just stopped using `next/image` until this is fixed.

**Comment by whoanuragverma** [comment]
The extra `<div>` tag forces the browser to allocate extra space while the image is loaded, this is needed for two reasons:
1. The UX will be bit bouncy as the contents of the page will move to give space for the newly fetched image.
2. This also reduces Cumulative Layout Shift (CLS) and imporves the lighthouse score.

If you want to learn more about CLS you can go to this great article by [web.dev](https://web.dev/optimize-cls/)
