### ISSUE TITLE
SourceMapping can't process valid typescript

### ISSUE THREAD

**Issue by cefn** [vercel/next.js#26494]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

12.20.2

### What browser are you using?

Chrome

### What operating system are you using?

Chrome OS

### How are you deploying your application?

yarn run dev

### Describe the Bug

I can't establish any config for reliable sourcemaps for Chrome 91 in my Typescript next application. 

Attempts to bind breakpoints at certain lines in the original source files can occasionally create a binding, but on other lines the breakpoint 'jumps' to the top of the function, meaning the line can't be visited. If you do successfully insert and hit a breakpoint, it commonly can only step a few lines within a single function before hitting one of the unvisitable lines, then jumping to the top of the function for multiple steps, then jumping into the innards of some webpack? library losing all stack context.

This applies to the app even if I add `sourceMap:true` or `inlineSourceMap:true` in the tsconfig.json, delete `.next` and rebuild. It applies through all the `target` configs I could try.  I have left the current config without changing the default settings auto-generated by next  deliberately for your reference.

### Expected Behavior

I would expect the default typescript configuration of next.js to not only compile the typescript successfully, but also have a configuration which makes sourcemaps work in Google Chrome.

### To Reproduce

The repo at https://github.com/cefn/nextjs-snake-cna is a app created with next's standard tooling as described [in the docs](https://nextjs.org/docs/basic-features/typescript)

I have deliberately started from the standard next.js template, then just added some Typescript sourcefiles which compile successfully with `npx tsc --noEmit`, and without changing any config. The app loads and runs but can't be reliably debugged by inserting breakpoints in files mounted from the Sources => `Filesystem` tab in the Chrome Inspector.

Yesterday I filed https://github.com/vercel/next.js/issues/26457 but I closed it since I was able to recreate the bug with fewer standardised steps as described.

The repo has [just four commits](https://github.com/cefn/nextjs-snake-cna/commits/main).

1. The empty github repo
2. The result of running `yarn create next-app --typescript .` in the repo
3. Copied three folders of typescript source - `pages` `public` and `src` from the original project - typescript code which successfully compiles a snake game which I need to debug.
4. Added two dependencies for `src` to the package.json

The project can be run by checking out [the repo](https://github.com/cefn/nextjs-snake-cna), then running `yarn` and `yarn run dev`

The application launches successfully at http://localhost:3000 but then can't be reliably debugged. As per https://github.com/vercel/next.js/issues/26457 which I closed, I have tried many distinct next+typescript configurations for this app including 10.0.0 with Webpack 4, 11.0.0 with Webpack 5. However this repro is the simplest so far.

Below you can see the result of attempting to insert a breakpoint at both line 48 and line 51. Both breakpoints 'jump' to line 42. Hitting the breakpoint at line 42 and then attempting to step to the next line causes it to 'stall' at line 42 for multiple steps. Finally it jumps from line 42 into `runtime.js` at the `tryCatch` function as shown.

![image](https://user-images.githubusercontent.com/159819/122976550-62b76380-d38c-11eb-9316-2dc18d18748e.png)

![image](https://user-images.githubusercontent.com/159819/122976819-b4f88480-d38c-11eb-8d04-ddabcae94444.png)

**Comment by leroydev** [comment]
@cefn did you manage to find a workaround for this by any chance? I'm running into what seems like the same bug in NextJS 12.0.3.

**Comment by cefn** [comment]
Sorry for the late reply @leroydev I can't recall any workarounds I arrived at for this particular case (debugging through Next) although shifting context into e.g. a test of the react component via react-testing-library, or a build using create-react-app (using the same component) might be effective.

**Comment by JanKaifer** [comment]
Checked the repro and it seems to fork now with `next@canary`.
