### ISSUE TITLE
Wrong url path and href when specifying current directory path in Next 11.0.1

### ISSUE THREAD

**Issue by trianah** [vercel/next.js#26537]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

Vercel

### Describe the Bug

When usign `new URL()` with current path (`'./'`), `url.path` and `url.href` show `_next` rather than the actual current path.
This only happens on Next 11.0.1, downgrading to 11.0.0  solves this behavior. 

### Expected Behavior

When usign `new URL()` with current path (`'./'`), `url.path` and `url.href` should have the actual current path

### To Reproduce

```
const url = new URL('./file.txt', import.meta.url)
console.log(import.meta.url)
console.log(url.pathname)
console.log(url.href)
```

**Comment by timneutkens** [comment]
Can you provide a reproduction of what you're trying to achieve with `new URL()` so that we can verify if the current behavior is expected or not.
