### ISSUE TITLE
next/script - Can't get Google Analytics inline script to load `beforeInteractive` - before close of <head> tag

### ISSUE THREAD

**Issue by simon-olsen** [vercel/next.js#26591]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

10.23.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I've just upgraded to Next.js v11.0.1 and trying out the <Script> component.

I'm trying to add the Google Analytics tag as they suggest; before the closing <head> tag using `strategy="beforeInteractive"`.

Here is my code for the `index.tsx` page

```
const Home: React.FC<Props> = ({ data }) => {
  return (
    <>
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=[TRACKING-ID]"
        strategy="beforeInteractive"
      />
      <Script
        dangerouslySetInnerHTML={{
          __html: `window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '[TRACKING-ID]');`,
        }}
        strategy="beforeInteractive"
      />
      <ThemeProvider theme={fullySickTheme}>
        <Head>
          <title>My Site</title>
        </Head>
...
```

The first <Script> with the `https://www.googletagmanager.com/gtag...` loads in the <head> but the script doesn't load at all.

The only way I can load it is at the bottom of the document using the default `afterInteractive` or `lazyOnload`.

Is this by design?
Should I just let the inline portion load before the ending body tag and be done with it? I'm only trying to follow what Google recommends in GA.

I've tried the following:

1. In a `page.tsx` file and in `_app.tsx` (docs say NOT to use `_document.tsx`)
2. Tried loading inline script with `dangerouslySetInnerHTML{{}}` and also adding the inline script to a custom function [and loading it that way](https://nextjs.org/docs/basic-features/script#inline-scripts), ala `dangerouslySetInnerHTML={setGoogleTags(stationGA)}` and `{window.dataLayer = window.dataLayer || [];...}`

### Expected Behavior

`beforeInteractive` adding my inline script inside the <head> tags.

### To Reproduce

1. Spin up a Next.js v11 site
2. In the index.js or index.tsx page, add the following.

```
import Script from "next/script";

// Then in the page's component

<Script
  src="https://www.googletagmanager.com/gtag/js?id=[TRACKING-ID]"
  strategy="beforeInteractive"
/>
<Script
  dangerouslySetInnerHTML={{
  __html: `window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', '[TRACKING-ID]');`,
  }}
  strategy="beforeInteractive"
 />
```

## Actual result

No inline script renders at all until you remove `strategy="beforeInteractive"`

**Comment by LetItRock** [comment]
@simon-olsen the `strategy="beforeInteractive"` doesn't pass the `dangerouslySetInnerHTML` prop to the `script` that is created at the end by next. I think that it's for a purpose as the docs are saying to use `afterInteractive` for tag managers and analytics. I've tried the code with `afterInteractive` and it works properly. I think that it might be because it has an impact on Web Vitals when loading with `beforeInteractive`.

**Comment by simon-olsen** [comment]
@LetItRock thanks for the feedback. That all makes sense. I'll go with the inline script of GA at the end of the body tag. We're starting to use `renderWebVitals` as well, so making sure we don't mess with that is a priority.

**Comment by LXSMNSYC** [comment]
Might be related: #26240

**Comment by wedneyyuri** [comment]
> @LetItRock thanks for the feedback. That all makes sense. I'll go with the inline script of GA at the end of the body tag. We're starting to use `renderWebVitals` as well, so making sure we don't mess with that is a priority.

@simon-olsen maybe can be better to initialize Google Analytics as a common javascript code: https://github.com/vercel/next.js/issues/26860#issuecomment-877739555

```tsx
// gtag.ts
const initialize = () => {
  window.dataLayer = window.dataLayer || [];
  window.gtag = function gtag() { window.dataLayer.push(arguments); }
  gtag('js', new Date());
  gtag('config', GA_TRACKING_ID);
};

// app.tsx
export default function MyApp({ Component, pageProps }) {
    useEffect(initialize, []); // this code will run only once

    return <>
        <Script src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`} />
        <Component {...pageProps} />
    </>
}
```

**Comment by janicklas-ralph** [comment]
Hi. Apologize for the delayed response. I'm working on adding another strategy to load inline scripts with beforeInteractive.

I also wanted to know if there was a specific reason for loading GA before first party code? Usually we recommend loading GA with afterInteractive, but wanted to understand if that doesn't work for your usecase?

**Comment by simon-olsen** [comment]
All good @janicklas-ralph.

That is the recommendation from GA. This is the instructions on their _Tracking Code_ page in the Admin section...

_This is the Global Site Tag (gtag.js) tracking code for this property. Copy and paste this code as the first item into the <HEAD> of every webpage you want to track. If you already have a Global Site Tag on your page, simply add the config line from the snippet below to your existing Global Site Tag._
