### ISSUE TITLE
Next.js Local Host shows a blank page for Index.js

### ISSUE THREAD

**Issue by MacCode7110** [vercel/next.js#26657]
### What version of Next.js are you using?

10.0.1

### What version of Node.js are you using?

16.2.0

### What browser are you using?

Microsoft Edge

### What operating system are you using?

Windows 10

### How are you deploying your application?

Vercel

### Describe the Bug

I am new to website development and I am learning how to create a Next.js app. When I load my local host site on my browser, it is completely blank. My homepage is based on my index.js file. I don't think that the local host should be blank since I have reviewed and revised my code, but I am not 100% sure. 
Here is a link to my Github page:  https://github.com/MacCode7110/Personal-Music-Reviews-Website 

Any suggestions on what is causing the blank page and how to resolve it would be appreciated!

### Expected Behavior

I expect a list of links with images to album reviews to be displayed on the homepage. Since I have not added any CSS styling,   the links and images should not be neatly organized.

### To Reproduce

Here is the code for my index.js file:

import Head from 'next/head'
import Image from 'next/image'
import {Fragment} from 'react'; //React fragment blocks allows us to group togther h1 blocks, list blocks, and more for the purposes of returning from a functionmport styles from '../styles/Home.module.css'
import Link from 'next/link';
import {getMetalReviews} from '../reviewdata';
import reviewList from '../components/reviews/review-list'

function HomePage()
{
    const metalReviewList = getMetalReviews();

    return ( 
        <div>
             <reviewList reviews = {metalReviewList}/>
        </div>
            );
}

export default HomePage;

**Comment by rsipakov** [comment]
Try to use a PascalCase for React components. I'm not sure if it helps, but it caught my eye. Also, I think is better change this `<img> src = {'/' + image} alt = {title} </img>` to self closing tag `<img src = {'/' + image} alt = {title} />`


https://www.quora.com/Why-do-React-components-use-PascalCase-for-filenames
