### ISSUE TITLE
The `querystring` API is considered Legacy. New code should use the `URLSearchParams` API instead.

### ISSUE THREAD

**Issue by AryanBeezadhur** [vercel/next.js#27230]
### What version of Next.js are you using?

Latest

### What version of Node.js are you using?

v14.15.0

### Describe the Bug

When I create a new Next.js app using the following command:

```bash
npx create-next-app@latest
```

After following the steps and creating a new Next.js project, I get the following npm warnings:

```bash
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

And from the [querystring npm page](https://www.npmjs.com/package/querystring):

> The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

[From MDN](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams):

> The `URLSearchParams` interface defines utility methods to work with the query string of a URL.

**Comment by Ryz0nd** [comment]
Check these links!
[https://github.com/GoogleChromeLabs/native-url/issues/7](https://github.com/GoogleChromeLabs/native-url/issues/7)
[https://caniuse.com/?search=URLSearchParams](https://caniuse.com/?search=URLSearchParams)

> The main reason for not using URLSearchParams is because it's not supported in Edge 16.
Since Edge 16 supports type=module scripts our polyfilling technique would not work.
So I'm not sure how we can polyfill URLSearchParams for all nomodule browsers + Edge 16 without doing something more complicated like reading the user-agent.

**Comment by dapinto8** [comment]
> Check this link!
> [GoogleChromeLabs/native-url#7](https://github.com/GoogleChromeLabs/native-url/issues/7)
> 
> > The main reason for not using URLSearchParams is because it's not supported in Edge 16.
> > Since Edge 16 supports type=module scripts our polyfilling technique would not work.
> > So I'm not sure how we can polyfill URLSearchParams for all nomodule browsers + Edge 16 without doing something more complicated like reading the user-agent.

It seems Edge 17 has support 
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
https://caniuse.com/urlsearchparams

**Comment by rtritto** [comment]
No warnings since `next.js` v12 (`native-url` dependency was removed and `node-libs-browser` was moved from dependency to devDependency).

I think that this issue can be closed.

FYI @ijjk @timneutkens

**Comment by ijjk** [comment]
Closing per above as these warnings should no longer be present in the latest version of Next.js

**Comment by chentsulin** [comment]
Hi @ijjk,
I recently realized `querystring` has been flagged as legacy by Node and should be replaced with alternatives. Are there any plans to remove `querystring` module entirely from the Next.js codebase? 

ref: https://nodejs.org/api/querystring.html#query-string

![](https://user-images.githubusercontent.com/3382565/151103431-079bc9be-b0ed-434e-a26b-126aef1f9f41.png)
