### ISSUE TITLE
next/script `<Script>` component doesn't render if inside next/head `<Head>` component

### ISSUE THREAD

**Issue by zackdotcomputer** [vercel/next.js#27498]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

Netlify

### Describe the Bug

I'm following the demands of `next lint`, attempting to upgrade all my previous `<script async src=...>` components to the `Script` component. I ran into an issue upgrading the Google Analytics tag: when using `<Script>` analytics is not loaded into the page, but when using `<script>` it is.

Finally correlated this issue with the fact that the `<Script>` component was stuck alongside my `<meta>` tags inside of a Next `<Head>` component. Moving it outside of the `<Head>` also fixed the issue.

### Expected Behavior

Expected behavior would be that `<Script>` would function anywhere that `<script>` functions (except for `_document`, since that caveat is noted in the docs). If it is inside the `<Head>`, it should wind up loading the same as if it weren't.

### To Reproduce

My setup:

`./src/SetupGoogleAnalytics.tsx`
```tsx
const gaId = "UA-XXXXXXXX-1";

export default function SetupGoogleAnalytics() {
  useEffect(() => {
    if (typeof window !== "undefined" && !(window as any).gtag && gaId) {
      const anyWindow = window as any;
      anyWindow.dataLayer = anyWindow.dataLayer || [];
      anyWindow.gtag = function gtag() {
        // eslint-disable-next-line prefer-rest-params
        anyWindow.dataLayer.push(arguments);
      };
      anyWindow.gtag("js", new Date());
      anyWindow.gtag("config", gaId);
    }
  }, []);

  if (!gaId) {
    return null;
  }

  return (
    <>
      <Script src={`https://www.googletagmanager.com/gtag/js?id=${gaId}`} />
    </>
  );
}
```

`./pages/index.tsx`
```tsx
import Head from "next/head";
import SetupGoogleAnalytics from "../components/SetupGoogleAnalytics";

export default function Home() {
  return (
    <article>
      <Head>
        <title>Repro</title>
        <SetupGoogleAnalytics />
      </Head>
      <p>This should not have analytics enabled.</p>
    </article>
  );
}
```

`./pages/works.tsx`
```tsx
import Head from "next/head";
import SetupGoogleAnalytics from "../components/SetupGoogleAnalytics";

export default function Home() {
  return (
    <article>
      <Head>
        <title>Repro</title>
      </Head>
      <SetupGoogleAnalytics />
      <p>This <strong>should</strong> have analytics enabled.</p>
    </article>
  );
}
```

**Comment by stefanprobst** [comment]
The [docs](https://nextjs.org/docs/basic-features/script#usage) say: "With next/script, you no longer need to wrap scripts in next/head."

There is also [this PR](https://github.com/vercel/next.js/pull/27257) to add a new lint rule to check for `next/script` inside `next/head`.

**Comment by zackdotcomputer** [comment]
@stefanprobst I had seen that the documentation says you no longer _need_ to wrap scripts in head, but I did not interpret that meaning that you _must not_ wrap the scripts in `next/head`. If the intention is that it is now a requirement to move scripts outside of any `<Head>` components, I think that requirement should be made more explicit.

(Though as an aside, this does make me curious why `<Script>` would require that? It makes migration more difficult since now it's not just a simple "swap script for Script" change.)

**Comment by zackdotcomputer** [comment]
I followed the trail back and see that [this commit](https://github.com/vercel/next.js/commit/f4aab83d37428f15994080ca8b00c46d77d78231) previously included a clearer caveat that one shouldn't use Script inside of Head, though again I think the documentation really should say "must not" and the tag should potentially throw or console.error rather than silently fail in this case.

Agreed that PR 27257 will help here.

**Comment by zackdotcomputer** [comment]
I added a PR (above) restoring a warning in the docs about this gotcha. I think between that and the new lint rule, this issue could be closed without needing to change functionality of either component.

**Comment by JanKaifer** [comment]
This looks like a forgotten issue. I'll close it.
