### ISSUE TITLE
/api/hello.js not able to call from getServerSideProps

### ISSUE THREAD

**Issue by abhikumar22** [vercel/next.js#27579]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

v10.22.0

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

i have used the default api endpoint which nextjs provides, **/api/hello**. 
in this endpoint i have called my own external backend endpoint (so that it acts as a proxy server to the FE).

I am calling this endpoint from getServerSideProps.

but getting this error :-
`Error: connect ECONNREFUSED 127.0.0.1:80`

When am trying to call the same in client side on button click then its giving result perfectly.

### Expected Behavior

The nextJS endpoint should be called from client as well as from the server

### To Reproduce

1. Create a nextjs API endpoint. -> /api/hello
2. in hello.js call your external api endpoint
3. in any page call **/api/hello** on getServerSideProps.

It will throw the error
`Error: connect ECONNREFUSED 127.0.0.1:80`

**Comment by mikeamarkey** [comment]
Is this related to the problem that you're facing? Problem with calling a next api endpoint from within `getServerSideProps`?
https://github.com/vercel/next.js/discussions/13316

**Comment by abhikumar22** [comment]
yes @mikeamarkey
