### ISSUE TITLE
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies

### ISSUE THREAD

**Issue by Fangston0** [vercel/next.js#27650]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Not deployed yet

### Describe the Bug

Simply creating a new Next.js project and running `yarn dev` / `npm run dev` logs the following warning in the console:

> <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies

I have tried deleting yarn.lock, and running `yarn install` again , but that did not do anything.

I'm not sure if this is related but, when first creating the project, I also get the following warnings:

![image](https://user-images.githubusercontent.com/55170164/127742971-30a5452b-5e98-4a88-acb9-f945203e59de.png)

### Expected Behavior

No warning, or an explanation of the warning.

### To Reproduce

1. `yarn create next-app` or `npx create-next-app`
2. Finish the setup
3. `yarn dev` or `npm run start`

**Comment by sokra** [comment]
Some kind of error happened... You need to enable debug logging to see the error:

``` js
// next.config.js
module.exports = {
  webpack(config) {
    config.infrastructureLogging = { debug: /PackFileCache/ }
    return config;
  }
}
```

**Comment by Fangston0** [comment]
> Some kind of error happened... You need to enable debug logging to see the error:
> 
> ```js
> // next.config.js
> module.exports = {
>   webpack(config) {
>     config.infrastructureLogging = { debug: /PackFileCache/ }
>     return config;
>   }
> }
> ```

Here's what I got on my console after enabling it:

`PS E:\React Projects\testapp> yarn dev
yarn run v1.22.11
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
    [webpack.cache.PackFileCacheStrategy] No pack exists at E:\React Projects\testapp\.next\cache\webpack\client-development.pack: Error: ENOENT: no such f
ile or directory, stat 'E:\React Projects\testapp\.next\cache\webpack\client-development\index.pack'
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 47.1833 ms
    [webpack.cache.PackFileCacheStrategy] No pack exists at E:\React Projects\testapp\.next\cache\webpack\server-development.pack: Error: ENOENT: no such f
ile or directory, stat 'E:\React Projects\testapp\.next\cache\webpack\server-development\index.pack'
<t> [webpack.cache.PackFileCacheStrategy] restore cache container: 44.0038 ms
    [webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to: ResolverCachePlugin|normal|dependencyType=|esm|path=|E:\React Projects\test
app|request=|E:\React Projects\testapp\node_modules\@next\react-refresh-utils\runtime.js
    [webpack.cache.PackFileCacheStrategy] Storing pack...
    [webpack.cache.PackFileCacheStrategy] Capturing build dependencies... (E:\React Projects\testapp\next.config.js, E:\React Projects\testapp\node_modules
\next\dist\compiled\, E:\React Projects\testapp\node_modules\next\dist\build\webpack\loaders\next-client-pages-loader.js, E:\React Projects\testapp\node_mo
dules\@next\react-refresh-utils\loader.js, E:\React Projects\testapp\node_modules\next\dist\build\babel\loader\index.js, E:\React Projects\testapp\node_mod
ules\next\dist\build\webpack\loaders\next-style-loader\index.js, E:\React Projects\testapp\node_modules\next\dist\compiled\css-loader\cjs.js, E:\React Proj
ects\testapp\node_modules\next\dist\compiled\postcss-loader\cjs.js)
event - compiled successfully
    [webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to: ResolverCachePlugin|normal|dependencyType=|esm|path=|E:\React Projects\test
app|request=|private-next-pages/_app.js
    [webpack.cache.PackFileCacheStrategy] Storing pack...
    [webpack.cache.PackFileCacheStrategy] Capturing build dependencies... (E:\React Projects\testapp\next.config.js, E:\React Projects\testapp\node_modules
\next\dist\compiled\, E:\React Projects\testapp\node_modules\next\dist\build\babel\loader\index.js, E:\React Projects\testapp\node_modules\next\dist\compil
ed\ignore-loader\index.js)
<t> [webpack.cache.PackFileCacheStrategy] resolve build dependencies: 2174.4305 ms
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects\testapp: Error: EI
NVAL: invalid argument, read
<t> [webpack.cache.PackFileCacheStrategy] snapshot build dependencies: 10.1572 ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
    [webpack.cache.PackFileCacheStrategy] Error: Unable to snapshot resolve dependencies
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:77909:13
        at jobError (E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:56110:5)
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:56161:10
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:56957:13
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:130615:5
        at Hook.eval [as callAsync] (eval at create (E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:31934:10), <anonymous>:6:
1)
        at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:31736:14)
        at AsyncQueue._handleResult (E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:130585:21)
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:130568:11
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:56906:12
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects: Error: EINVAL: in
valid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\: Error: EINVAL: invalid argument
, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects\testapp\node_modul
es\@next: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects\testapp\node_modul
es: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects\testapp\node_modul
es\@babel: Error: EINVAL: invalid argument, read
<t> [webpack.cache.PackFileCacheStrategy] resolve build dependencies: 1628.2388 ms
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects: Error: EINVAL: in
valid argument, read
<t> [webpack.cache.PackFileCacheStrategy] snapshot build dependencies: 8.8026 ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
    [webpack.cache.PackFileCacheStrategy] Error: Unable to snapshot resolve dependencies
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:77909:13
        at jobError (E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:56110:5)
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:56161:10
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:56957:13
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:130615:5
        at Hook.eval [as callAsync] (eval at create (E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:31934:10), <anonymous>:6:
1)
        at AsyncQueue._handleResult (E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:130585:21)
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:130568:11
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:56906:12
        at E:\React Projects\testapp\node_modules\next\dist\compiled\webpack\bundle5.js:29533:16
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects\testapp: Error: EI
NVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\: Error: EINVAL: invalid argument
, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects\testapp\node_modul
es: Error: EINVAL: invalid argument, read
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting file timestamp hash combination of E:\React Projects\testapp\node_modul
es\@babel: Error: EINVAL: invalid argument, read
`

**Comment by Fangston0** [comment]
Hi @sokra 
Could you have a look at the above log and help me figure out what's wrong?
All I can understand is that some package is missing, but I am not sure how to fix that. 
Any help would be appreciated, thank you!

**Comment by OmarOmeiri** [comment]
I have the same problem running a blank project created with `npx create-next-app@latest --ts`

versions: 
`node@16.2.0`
`next": "12.0.2`
`react": "17.0.2`
`react-dom: "17.0.2`

How this is still unattended?

**Comment by langford-bc** [comment]
I'm having a similar Webpack error. 

The message is the following: [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependenc
ies
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependenc
ies

What version of Next.js are you using?
12.0.7

What version of Node.js are you using?
v14.17.3

What browser are you using?
Chrome

What operating system are you using?
Mac OS Catalina

How are you deploying your application?
Not deployed yet

I enabled debug logging but could not come up with a sense of what the issue could be. There are only three development dependencies in the project: next, react and react-dom 

Thanks

**Comment by balazsorban44** [comment]
Hi, I could not reproduce this with the OP's reproduction steps, but there is a similar issue opened at #33693 (which I could reproduce). If you think your issue is related, feel free to follow along with that one. If you get a similar warning but you don't think it's the same as #33693, please open a new bug report with a reproduction instead.
