### ISSUE TITLE
Barrel files and dynamic import

### ISSUE THREAD

**Issue by patrickedqvist** [vercel/next.js#27814]
### What version of Next.js are you using?

10.0.1

### What version of Node.js are you using?

12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

stackblitz

### Describe the Bug

Using dynamic import together with barrel files makes it so that files all the files (included the dynamic ones) are bundled together, thus rendering the purpose of dynamic imports obsolete. While this is probably a problem with Webpack rather than NextJS it is important that the documentation for using dynamic imports raise this issue unless it can be resolved.

Considering this tree
```
| - Components
  | - Hello
    | - Hello1.js
    | - Hello2.js
    | - index.js
| - Pages
  | - index.js
``` 

```.js
// pages/index.js

import { Hello1 } from '../components/Hello';
const Hello2 = dynamic(() => import('../components/Hello/Hello2.js'));

const IndexPage = () => {
  return (
    <div>
      <Hello1 />
      <Hello2 />
    </div>
  )
}
```

Importing Hello1 and Hello2 in the above fashion creates only a single file for the index page containing both Hello1 and Hello2 rather than splitting Hello2 into its own file.

### Expected Behavior

The code should be bundled into a file for index.js containing Hello1 but not Hello2 and Hello2 should be bundled into its own file.

### To Reproduce

[See original code](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-dynamic-import?file=pages%2Findex.js)
[See bugged example](https://stackblitz.com/edit/github-4snyge-asbvka?file=pages%2Findex.js)

**Comment by sokra** [comment]
> ```js
> import { Hello1 } from '../components/Hello';
> ```

This line will load/"evaluate" both Hello1 and Hello2 components. This is what the ESM spec specifies. Each of these files could have side effects, so they need to be executed.

You can "hint" the compiler to treat all these files are side-effect-free, which would allow further optimizations, which would allow this line to only load the Hello1 file.

Do that by adding a `../components/Hello/package.json` with `{ "sideEffects": false }`.

Next.js will optimize that barrel file further, but only in production mode.

If you like to see the effect in development mode too, you can add this `next.config.js`:

```js
module.exports = {
  webpack(config, { isServer }) {
    if (!isServer) {
      config.optimization.providedExports = true;
    }
    return config;
  }
};
```

It's usually disable for performance reasons

**Comment by patrickedqvist** [comment]
@sokra Thank you so much for your explanation!

**Comment by lunelson** [comment]
@sokra am I correct in understanding your explanation above, to mean that _one should place a `package.json` file with `{ "sideEffects": false }` at every place where a JS file is importing or exporting multiple modules_?, or is a single `sideEffects` rule at the root-level of a package good enough?

**Comment by timneutkens** [comment]
A single package.json (root of your project) is enough.

**Comment by JanKaifer** [comment]
This was resolved. Closing.
