### ISSUE TITLE
Malformed json response in API endpoint

### ISSUE THREAD

**Issue by dorbal** [vercel/next.js#27812]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

next dev, next start

### Describe the Bug

I've got "SyntaxError: Unexpected token / in JSON at position 0":

res.status("200").json("string");
result: string 

### Expected Behavior

res.status("200").json("string");

The result should be: "string"

### To Reproduce

Just make an API route with the following content:

export default function handler(req, res) {
  res.status("200").json("string");
}

**Comment by rishimohan** [comment]
@dorbal Try `res.status(200).json({result: "string"});`

Notice the status code `200`, it shouldn't be in quotes.
