### ISSUE TITLE
ESLint not working with lint-staged

### ISSUE THREAD

**Issue by nghiepit** [vercel/next.js#27997]
### What version of Next.js are you using?

11.1

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next lint

### Describe the Bug

When to use `lint-staged` to run the linter `next lint` command on git staged files.
```
  ❯ Running tasks for *.{ts,tsx}
    ✖ next lint --fix [FAILED]
    ◼ git add
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ next lint --fix:
error - Failed to load env from .env.production.local Error: ENOTDIR: not a directory, stat '/Users/Data/Projects/my_project/components/MyComponent.tsx/.env.production.local'
    at Object.statSync (fs.js:1086:3)
    at Module.loadEnvConfig (/Users/Data/Projects/my_project/node_modules/@next/env/dist/index.js:1:3298)
    at Object.loadConfig [as default] (/Users/Data/Projects/my_project/node_modules/next/dist/server/config.js:331:21)
    at nextLint (/Users/Data/Projects/my_project/node_modules/next/dist/cli/next-lint.js:161:44)
    at /Users/Data/Projects/my_project/node_modules/next/dist/bin/next:137:34 {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '/Users/Data/Projects/my_project/modules/dynamic_layout/layout/DynamicLayoutDatatable.tsx/.env.production.local'
}
```

### Expected Behavior

Just works

### To Reproduce

0/ Clone `with-eslint` example and update latest
1/ Add config into `package.json`
```json
 "lint-staged": {
    "*.{js,jsx}": [
      "next lint --fix",
      "git add"
    ]
  }
```
2/ Edit any component, ex: `pages/index.js`
3/ `git add .`
4/ `npx lint-staged`
5/ See error

**Comment by krall12** [comment]
I've just run into this today setting up lint-staged on my project! Any updates on when this draft PR will get merged, or a workaround in the meantime?

**Comment by housseindjirdeh** [comment]
I just opened #28042 which will fix this. Once it's merged however, It will most likely require a small `lintstagedrc` config. Something like the following in `.lintstagedrc.js` should work:

```
module.exports = {
  "**/*.js?(x)": (filenames) =>
    `next lint --fix --file ${filenames
      .map((file) => file.split(process.cwd())[1])
      .join(" --file ")}`,
};
```

> or a workaround in the meantime?

Just replace `next lint` with `eslint`, and everything will work the same :)

```
"lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ]
  }
  ```
  
`next lint` provides a new custom formatter and makes the developer experience easier for folks setting up ESLint for the first time, but you can easily use `eslint` directly to get the same functionality with `lint-staged`.
