### ISSUE TITLE
Domain Routing bug

### ISSUE THREAD

**Issue by vahidtakro** [vercel/next.js#28120]
### What version of Next.js are you using?

10.0.1

### What version of Node.js are you using?

12.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

I did [domain routing](https://nextjs.org/docs/advanced-features/i18n-routing#domain-routing), like following:
```
{
  "locales": ["en", "fr"],
  "defaultLocale": "en",
  "localeDetection": true,
  "domains": [
    {
      "domain": "domain.com",
      "defaultLocale": "en"
    },
    {
      "domain": "domain.fr",
      "defaultLocale": "fr"
    }
  ],
  "pages": {
    "*": ["common", "headerNavLinks", "404", "archives"],
    "/projects": ["projects"],
    "/resume": ["resume"],
    "/music": ["music"]
  }
}
```
while having next-translate package.

### Expected Behavior

I expected to switch to my locales like this:
domain.com for English,
domain.fr for French,

### To Reproduce

but I'm experiencing this:

domain.com for English
domain.fr for English

domain.com/fr for French
domain.fr/fr for French

**Comment by jfernandomeyer** [comment]
I'm facing the same issue.

Have you found any way to work around the problem?

**Comment by vahidtakro** [comment]
> I'm facing the same issue.
> 
> Have you found any way to work around the problem?

Hi Jose, yes I fixed the issue.
are you using a translator package?

**Comment by jfernandomeyer** [comment]
Hey Vahid.

Awesome to know you found a fix.
In my case I’m not using translator packages like next-translate. The plan was to use domain based routes to rewrite URLs as a migration plan, however, I faced the same issue and it only works either with default locale or when I explicitly set the locale as part of the path ( /fr in your case ).

Can you share more details on how you fixed it?

Thanks a lot for the support

**Comment by vahidtakro** [comment]
in my case I had to 

> Hey Vahid.
> 
> Awesome to know you found a fix.
> In my case I’m not using translator packages like next-translate. The plan was to use domain based routes to rewrite URLs as a migration plan, however, I faced the same issue and it only works either with default locale or when I explicitly set the locale as part of the path ( /fr in your case ).
> 
> Can you share more details on how you fixed it?
> 
> Thanks a lot for the support

in my case I had to use exact domains as I set in Vercel.
may I see your repo?

**Comment by ijjk** [comment]
Closing as this appears to be resolved per https://github.com/vercel/next.js/issues/28120#issuecomment-912743301
