### ISSUE TITLE
Dynamic API route returns 404

### ISSUE THREAD

**Issue by PraveenPeri** [vercel/next.js#28304]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome/Edge

### What operating system are you using?

Linux

### How are you deploying your application?

next dev and next start

### Describe the Bug

Added a dynamic route under api folder like this api/entitySelection/[id].ts but the page hit to /api/entitySelection/1 always returns 404

### Expected Behavior

The path should return the content defined in the API at the route.

### To Reproduce

1. Add a dynamic route under a named folder inside api folder like /api/test/[id].ts
2. Define the API to return something like res.status(200).json({name: "John Doe"})
3. Run next dev and hit the URL http://localhost:3000/api/test/1 and see that it returns 404
4. Now add an index.ts api under test folder and see that hitting http://localhost:3000/api/test returns the expected content

**Comment by DiKwickley** [comment]
Can you send the snippet of your api route?
Also #4 is the expected behaviour. (https://nextjs.org/docs/api-routes/dynamic-api-routes)
