### ISSUE TITLE
Get unexpected warning `<SSRProvider>` from console when upgrade to 11.1.0

### ISSUE THREAD

**Issue by sonck201** [vercel/next.js#28351]
### What example does this report relate to?

Upgrade nextjs to 11.1.0 and start getting this log from console

### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

v16.4.0

### What browser are you using?

Google Chrome - Version 92.0.4515.159 (Official Build) (x86_64)

### What operating system are you using?

maxOS 11.5

### How are you deploying your application?

next dev

### Describe the Bug

Start upgrading to nextjs 11.1.0 and got the log from console
```
When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.
```

### Expected Behavior

How to remove this log

### To Reproduce

Start app in DEV mode

**Comment by stefanprobst** [comment]
are you maybe using `react-aria`? looks like the warning is coming from there

**Comment by sonck201** [comment]
> are you maybe using `react-aria`? looks like the warning is coming from there

I'm using `next-intl` only
