### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by mariovarela99** [vercel/next.js#28399]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.2

### What browser are you using?

Google Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next dev

### Describe the Bug

The document is not defined when i use aos.init that library aos, uses document, and i  see that document is not defined, when a use aos.init() in project.!

### Expected Behavior

I expected that the page run normally

### To Reproduce

![Captura de ecrã de 2021-08-22 21-38-00](https://user-images.githubusercontent.com/72455038/130369824-2e302e05-20df-42e7-a2e5-853c00a46ab8.png)
![Captura de ecrã de 2021-08-22 21-40-50](https://user-images.githubusercontent.com/72455038/130369828-9d956281-d42b-445f-86bf-a88fc64610a1.png)

**Comment by G3root** [comment]
`next/dynamic` only works with React components, for JavaScript functions you have to use **native** [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports).

here is an example for above scenario: https://stackblitz.com/edit/nextjs-dtvwex?file=pages/index.js
