### ISSUE TITLE
assetPrefix is not respected 

### ISSUE THREAD

**Issue by ScriptedAlchemy** [vercel/next.js#28685]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

AWS SLS

### Describe the Bug

Out ephemeral environments are configured during deploy via an env var. As of next 11.1.2, the assetPrefix does not seem to be respected and css & js assets are always loaded from the domain.

We use a pr query string to proxy to the right AWS buckets through stage.site.com.

We change the assetPrefix during SSR like this

```js
export default class Document extends NextDocument {
  constructor(props) {
    super(props);

    const { assetPrefix, __NEXT_DATA__ } = props;
    if (assetPrefix) {
      __NEXT_DATA__.assetPrefix = assetPrefix;
    }
  }
```

If I look in `__NEXT_DATA__`, i see my empheral URL listed there which would point my assets to the right origin, but SSR does not seem to respect it. 

So my assets end up loading from stage.site.com/assets instead of prenv33.preprod.site.com/assets

Elsewhere in out app, we configure the asset prefix as follows

```js
const { stage } = config.get('universal.env');
const { staticAssetsUrl } = config.get('public');

let assetPrefix = '';

if (stage === 'localdev') {
  assetPrefix = '';
} else if (staticAssetsUrl) {
  assetPrefix = staticAssetsUrl;
} else {
  assetPrefix = `https://${stage}.preprod.site.com/static/ecom-web-app`;
}
```

### Expected Behavior

Asset prefix should be respected as its shown in `__NEXT_DATA__` 

### To Reproduce

Try changing the asset prefix dynamically in the route handler or custom app

**Comment by timneutkens** [comment]
Overriding internals like `__NEXT_DATA__` is not supported so I'll convert this into a feature request.
