### ISSUE TITLE
Unhandled 'error' event: write EPIPE when developing or debugging with using yarn zero installs (never in production builds)

### ISSUE THREAD

**Issue by meglio** [vercel/next.js#28783]
### What version of Next.js are you using?

11.1.0

### What version of Node.js are you using?

16.6.1

### What browser are you using?

Latest Firefox on MacOS

### What operating system are you using?

Latest MacOS

### How are you deploying your application?

Debugging locally (NOT within a Docker container)

### Describe the Bug

Please check the screenshot. This error happens randomly when I `yarn dev`, and it usually works again the next time I `yard dev`: 

<img width="686" alt="image" src="https://user-images.githubusercontent.com/282177/132085518-cbe99021-ab18-4f95-bdc2-1b5895c4899e.png">

### Expected Behavior

I expect it to not fire any errors - because if I try `next dev` again immediately without making any changes to the environment and to the codebase, it works.

This bug is pretty annoying - because it is random.

### To Reproduce

The issue here is that it is not clear how to reproduce it. The error is fired randomly, and usually disappears if I try again.

So, `yarn dev` fires the error.
Then I try `yarn dev` again without touching anything, and it just works.

I've attached the screenshot with the hope that it will help your team understand what might be causing the issue.

Note that it never happens when running a version built for production. But it regularly happens when `dev` or `debug` in local environment.

-----

My setup is latest yarn 3.x in the zero-installs mode. In my package.json:

```
"packageManager": "yarn@3.0.1",
"dev": "next dev -H doubleeagle.loc.antonphp.com",
"debug2": "NODE_OPTIONS=\"$NODE_OPTIONS --inspect\" next dev -H example.lvh.me,
```

**Comment by balazsorban44** [comment]
> The error is fired randomly, and usually disappears if I try again.

This is very hard to debug. We need some kind of a reproduction to be able to investigate. Please provide one.
