### ISSUE TITLE
Future <Link> navigation is broken if prefetching that route takes longer than 3.8 sec

### ISSUE THREAD

**Issue by jayphelps** [vercel/next.js#28797]
### What version of Next.js are you using?

11.1.2/Canary

### What version of Node.js are you using?

Any

### What browser are you using?

Any

### What operating system are you using?

Any

### How are you deploying your application?

Any

### Describe the Bug

The internal utility [`withFuture()`](https://github.com/vercel/next.js/blob/e969d226999bb0fcb52ecc203b359f3715ff69bf/packages/next/client/route-loader.ts#L61-L65) sets internal state in the routes Map containing a Promise. When loading or prefetching, the internal [`loadRoute()`](https://github.com/vercel/next.js/blob/e969d226999bb0fcb52ecc203b359f3715ff69bf/packages/next/client/route-loader.ts#L308)  uses the [`resolvePromiseWithTimeout ()`](https://github.com/vercel/next.js/blob/e969d226999bb0fcb52ecc203b359f3715ff69bf/packages/next/client/route-loader.ts#L153), which will reject after the given 3.8 second timeout.

If a route is navigated to for the first time *without* being prefetched, and the 3.8 timeout is triggered due to slow server/connection, an exception is thrown and ultimately the page will do a full navigation. However, if an attempt to prefetch the route is made by Next and it takes longer than 3.8 seconds, that exception is [caught and swallowed](https://github.com/vercel/next.js/blob/4cdb585962b4f17be55848740d6e34106d730217/packages/next/client/link.tsx#L50-L55) in production mode. Because `withFuture()` does not listen for any rejections from the promise returned from [`generator()`](https://github.com/vercel/next.js/blob/e969d226999bb0fcb52ecc203b359f3715ff69bf/packages/next/client/route-loader.ts#L64) (or, unrelated, if generator() synchronously threw) the state stored in `routes` (passed into `withFuture` as the second argument ,`map`) is not cleaned up and the "future" promise stored in there will never be resolved nor rejected.

When induced, the symptom from the user is that clicking a `<Link>` does nothing visually, and no error is logged.

### Expected Behavior

Preloading `<Link>`s that take longer than the timeout do not prevent future navigation to that route.

### To Reproduce

To reproduce, clone/build/start this repo, but do NOT npm install because I've patched next to induce 5 second latency to the /about JS chunk only to make it easily reproducible: https://github.com/jayphelps/next-issue-28797

Alternatively, the general instructions for making your own:

- `<Link href="/something">` to another page (without setting `prefetch={false}`).
- Some how induce latency over 3.8 seconds for only the JS `/_next/static/chunks/pages/file.js` for that particular page; it's much harder to reproduce if you induce general latency on everything, but consistently reproducible if only that one file.
- Visit that page with that `<Link>`.
- See in Network tab that JS resource is being prefetched, but taking longer than 3.8 seconds.
- Wait until JS resource download completes.
- Now click on the `<Link>`.
- See that nothing happens.

To confirm root cause, add a breakpoint to the [prefetch error swallowing line](https://github.com/vercel/next.js/blob/4cdb585962b4f17be55848740d6e34106d730217/packages/next/client/link.tsx#L50-L55), reproduce (seeing debugger pause on that breakpoint), then inspect internal `routes` map to see the hung promise stuck in 'pending' state forever.

If things are unclear, I'm happy to jump on Zoom, etc.

As always, apologies if I'm some how wrong and waste anyone's time 😅  I tried to be thorough. I would PR, but it’s unclear if the right approach is a more extreme refactor or just simply tweaking withFuture to listen for errors and cleanup—that might have consequences I’m unaware of because it’s used in several places.

**Comment by jayphelps** [comment]
This fixes it for us, what we're now running in production: https://github.com/jayphelps/next.js/commit/8daaa0a022db93ae7355f652dbd2955e7721cdda

```diff
-      generator().then((value) => (resolver(value), value))
+      generator()
+        .then((value) => (resolver(value), value))
+        .catch((e) => {
+          map.delete(key)
+          throw e
+        })

**Comment by jayphelps** [comment]
Edited original post to include a repo to reproduce the issue easily; I patched next-server.js in the node_modules (included) so that it always has 5 seconds of latency for the /about route chunk. https://github.com/jayphelps/next-issue-28797

**Comment by seastian** [comment]
#27783
