### ISSUE TITLE
App runs ok with dev but 404's with start

### ISSUE THREAD

**Issue by o-t-w** [vercel/next.js#28868]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.8.0

### What browser are you using?

Latest stable Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

Localhost

### Describe the Bug

When I run npm run build followed by npm run start I get a 404 for my pages/index.js page (which is the only page in my app).
npm run dev works fine.

### Expected Behavior

I should be able to see my app on localhost:3000

### To Reproduce

Not sure

**Comment by LaBiXiaoChen** [comment]
no one answer this question?

**Comment by LaBiXiaoChen** [comment]
no one answer this question?

**Comment by balazsorban44** [comment]
To Reproduce "Not sure".

This is practically impossible to debug for anyone.

A proper reproduction is needed.

@o-t-w could you create a reproduction or at least paste in your `pages/index.js` page and your `next.config.js`?

**Comment by o-t-w** [comment]
To reproduce: clone the following repo (maybe on Windows 10 as that might make a difference?) and then run npm run build and npm run start and then look in a web browser. 
https://github.com/o-t-w/immo-search/settings

**Comment by o-t-w** [comment]
No idea if it’s related but I had also run into this issue earlier today https://stackoverflow.com/questions/58365151/hooks-error-invalid-hook-call-using-nextjs-or-reactjs-on-windows/58365152#58365152

**Comment by balazsorban44** [comment]
Unfortunately, the issue is not reproducible given your linked repository. (Just tried it locally, and everything worked correctly). Try removing the `.next` folder and re-run `npm run build` and `npm run start`
