### ISSUE TITLE
next/script package with custom document

### ISSUE THREAD

**Issue by ch3rn1k** [vercel/next.js#28872]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

No way to use `next/script` optimization package inside custom `_document.js`

### Expected Behavior

Expected to initialize once metric scripts inside custom '_document.js' file.

### To Reproduce

Try to add any script with `next/script` inside `_document.js`

**Comment by ch3rn1k** [comment]
Well, it's not a bug so, but how to optimize metrics scripts using this package? For sure it needs to be initialized only once...

**Comment by stefanprobst** [comment]
you can put the `next/script` component in `pages/_app.js`.
