### ISSUE TITLE
Custom app directory not recognised (v11.1.1+)

### ISSUE THREAD

**Issue by coffeedoughnuts** [vercel/next.js#28875]
### What version of Next.js are you using?

11.1.1

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next export

### Describe the Bug

We have our custom app component in a directory called `_app` instead of being called `_app.tsx` itself:

```
src/pages/_app/index.css
src/pages/_app/index.tsx
src/pages/index.tsx
```

and this has been working fine, until we upgraded to v11.1.1+ (issue is reproducible in 11.1.2 and canary at time of submission)

when using 11.1.1+ the `_app/index.tsx` is ignored, resulting in an error for us as we are using `_app` to inject some additional props to pages (among other things)

Reproduction repo: https://github.com/coffeedoughnuts/next-11.1.1-context-bug

### Expected Behavior

`_app/index.tsx` should function in the same way as `_app.tsx`

### To Reproduce

https://github.com/coffeedoughnuts/next-11.1.1-context-bug

**Comment by balazsorban44** [comment]
This is an unintended/undocumented structure. Just use a top-level `_app` file instead.

**Comment by marktellez** [comment]
That is highly unhelpful and breaks the standard set for years of
javascript and nextjs. This kind of lack of an actual solution and shitty
response is not the hallmark of the team in the past.

**Comment by marktellez** [comment]
Having a folder for this sort of thing with an index.jsx allows for
encapsulationof app level stylesheets and other assets.
