### ISSUE TITLE
Unexpected interaction between `<Link />` and `publicRuntimeConfig`

### ISSUE THREAD

**Issue by cdriesler** [vercel/next.js#28938]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

12.18.1

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows

### How are you deploying your application?

GKE

### Describe the Bug

I have a page that depends on information from the `publicRuntimeConfig` object provided by the `next/config` module. It is populated in `next.config.js` by a `process.env` reference because the information is not available at build time.

When I navigate to this page with a `<Link />` component provided by `next/link`, the `publicRuntimeConfig` object does not contain any environment variables set on the server after build.

This does not appear to be a configuration error because the expected values *do* show up if I navigate directly or use a vanilla `<a>` instead of `<Link />`.

### Expected Behavior

Navigation to a page with the `<Link />` component should behave the same as direct navigation w/r/t `publicRuntimeConfig` values. The page should have access to the latest environment variables set on the server after build.

### To Reproduce

I started with the latest `npx create-next-app` template and made minor modifications to reproduce:

`package.json`
```
{
  "name": "next-link-bug",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "set NEXT_PUBLIC_RUNTIME_VALUE=\"foo\" && next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "11.1.2",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@types/react": "17.0.20",
    "eslint": "7.32.0",
    "eslint-config-next": "11.1.2",
    "typescript": "4.4.2"
  }
}
```

`next.config.js`
```
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  publicRuntimeConfig: {
    runtimeValue: process.env.NEXT_PUBLIC_RUNTIME_VALUE
  }
}
```

`pages/index.tsx`
```
import type { NextPage } from 'next'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <Link href="/ssg">
      <a>With Link</a>
    </Link>
  )
}

export default Home
```

`pages/ssg.tsx`
```
import type { NextPage } from 'next'
import getConfig from 'next/config'

const { publicRuntimeConfig } = getConfig()

const Home: NextPage = () => {
  console.log({ publicRuntimeConfig })
  return (
    <p>{publicRuntimeConfig.runtimeValue}</p>
  )
}

export default Home

export const getServerSideProps = async () => {
    return { props: {} }
}
```

- Run `npm run build` to build the example without any environment variables. Run `npm run start` to populate the `NEXT_PUBLIC_RUNTIME_VALUE` environment variable and start the server.
- Navigate directly to `localhost:3000`
- Click the link
- Observe that the console outputs an empty `publicRuntimeConfig` and that no text is rendered on the page
- Refresh the page (`localhost:3000/ssg`)
- Observe that the console outputs the expected `publicRuntimeConfig` and it is accurately rendered on the page

**Comment by stevethatcodes** [comment]
@cdriesler Did you ever get anywhere with this? I'm running into the same issue where navigating away from our 404 page (statically rendered) results in a pretty broken app as our runtime config doesn't get updated.

**Comment by cdriesler** [comment]
@stevethatcodes No, I'm not much help with this issue, sorry. After some tinkering, I ended up redesigning around it as a constraint.

**Comment by stevethatcodes** [comment]
@cdriesler No worries. We've basically hit a wall with it and will likely just end up revamping how we do runtime config to get around the limitation.

**Comment by cdriesler** [comment]
Understood, thanks for the heads up. With those caveats, I would have just used something else.
