### ISSUE TITLE
Source Maps stopped working on Chrome 92

### ISSUE THREAD

**Issue by Florian-crg** [vercel/next.js#29073]
### What version of Next.js are you using?

11.0.0

### What version of Node.js are you using?

v12.22.1

### What browser are you using?

Chrome 93.0.4577.63 (Build officiel) (arm64)

### What operating system are you using?

macOS M1

### How are you deploying your application?

dev mod

### Describe the Bug

I did not change my package.json nor my next.config but I now get react_devtools_backend.js:4049 in my console on Chrome instead of the file and line of my `console.log()`.  It works fine on Firefox though.

Related post on stackoverflow https://stackoverflow.com/questions/69083933/nextjs-source-maps-stopped-working-on-chrome-92

### Expected Behavior

It should, like in firefox, show the line and the name of the file of the `console.log()`

### To Reproduce

I don't really know. Probably start a new project with the same version and log then try to inspect it using Chrome

Chrome version: 93.0.4577.63 (Build officiel) (arm64)

**Comment by oleics** [comment]
Same here, disabling react-dev-tools "fixes" this for me

**Comment by ljosberinn** [comment]
as far as I'm aware this is unrelated to next but actually a change in the react devtools which now monkey patch the console

**Comment by bvaughn** [comment]
@ljosberinn is correct. We (react devtools) will be improving this experience with the next release.
