### ISSUE TITLE
Add information about how to get great loading performance to the going to production section

### ISSUE THREAD

**Issue by molebox** [vercel/next.js#29319]
### Describe the feature you'd like to request

Add docs that describe how to go about getting great loading performance. We should aim to make this a standard of our users workflow by adding the information to our [Going to production](https://nextjs.org/docs/going-to-production) section.

### Describe the solution you'd like

This notion doc about [Ensuring great loading performance](https://www.notion.so/vercel/Ensuring-Great-Loading-Performance-d9f6a83f9f594fbcab7c8c88d094f4a2) covers what to do.

[This notion doc](https://www.notion.so/vercel/Next-js-Docs-Going-to-Production-80a2188f6a714df9959141a41149e8bf) outlines what to add. 

### Describe alternatives you've considered

N/A

**Comment by plusequalsone** [comment]
Can the contents of notion doc be public until going to main docs?
Trying to improve perf. on some Next.js apps and would be interested to see these tips.
