### ISSUE TITLE
Add link to blog in header

### ISSUE THREAD

**Issue by molebox** [vercel/next.js#29351]
### Describe the feature you'd like to request

A user pointed out that its hard to find our nextjs blog and suggested we move it to the header

### Describe the solution you'd like

Move the link to the blog into the header

### Describe alternatives you've considered

Possibly somewhere else more visible if it doesnt fit in the header

**Comment by MonstraG** [comment]
By the way, can you also add github link to the header?
![image](https://user-images.githubusercontent.com/17963791/134685379-e9917e44-fbac-4444-aa0e-b5d81e1657a8.png)

**Comment by saideepesh000** [comment]
Hey @timneutkens , can I work on this ?

**Comment by balazsorban44** [comment]
![image](https://user-images.githubusercontent.com/18369201/189892970-ee2a16c7-f160-4199-af33-0a617d9eb6fd.png)


This seems to be the case now, so closing.
