### ISSUE TITLE
NextJS Web Font Optimization breaks with custom JSX function

### ISSUE THREAD

**Issue by tills13** [vercel/next.js#29435]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

12.x

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

Using a custom JSX function, NextJS font optimization breaks silently. This seems to be due to checks against the name of the function in the Webpack plugin: [one](https://github.com/vercel/next.js/blob/5b9ad8da909a7870280c39340c189392d6307994/packages/next/build/webpack/plugins/font-stylesheet-gathering-plugin.ts#L260), [two](https://github.com/vercel/next.js/blob/5b9ad8da909a7870280c39340c189392d6307994/packages/next/build/webpack/plugins/font-stylesheet-gathering-plugin.ts#L140), [three](https://github.com/vercel/next.js/blob/5b9ad8da909a7870280c39340c189392d6307994/packages/next/build/webpack/plugins/font-stylesheet-gathering-plugin.ts#L144), etc

We ran into this issue while converting our legacy app to NextJS 11.1.2 + emotion, and using React's classic runtime (via `"runtime": "classic"` in our `.babelrc`). 

```
/** @jsx jsx */
import { jsx } from "@emotion/react" // problem starts here
import Head from "next/head"

function App({ Component }) {
  return <>
    <Head>
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto&display=swap"
    </Head>
    <Component />
  </>
}
```

babelrc: 

```
{
    "presets": [
        [
            "next/babel",
            {
                "preset-react": {
                    "runtime": "classic"
                }
            }
        ]
    ],
    "plugins": ["@emotion"]
}
```

In the output, the JSX function above is obviously named `jsx`.

I specifically say "silently" above because a) it'll work until you specify the custom function (understandable) and b) it'll still have the `data-optimized-fonts` prop from [here](https://github.com/vercel/next.js/blob/5544adc481f8821567e947a6e6d51d9d68ebd367/packages/next/shared/lib/head.tsx#L159) leading to confused developers.

### Expected Behavior

I'm not sure... it's fairly straight forward to just use the automatic runtime. I (personally) cannot think of a scenario where you'd _need_ to use a custom function like this. Specifying the function through the suggested route (automatic + `importSource`) works as expected. If NextJS doesn't want to support arbitrary JSX functions in this manner, a warning might be applicable where usage is detected.

There are two solutions / work-arounds: 

1. the right way: use the automatic runtime. You can use [a codemod](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports) to make your life easier... babel will import the transform as `_jsx` automatically.
2. the "hack": name your jsx function either `_jsx` or `__jsx`. e.g. the above app example could be

```
/** @jsx _jsx */
import { jsx as _jsx } from "@emotion/react"
...
```

### To Reproduce

See the minimal example above.

**Comment by lachlanjc** [comment]
Is this issue still needed with [the new font optimization](https://nextjs.org/docs/basic-features/font-optimization)?

**Comment by tills13** [comment]
@lachlanjc likely no, assuming there's no barrier to using that feature on older versions of NextJS or with custom servers.

**Comment by lachlanjc** [comment]
@leerob can close!
