### ISSUE TITLE
Next dev fails with latest version of Nextjs and enabled webpack 5

### ISSUE THREAD

**Issue by VitaliyInshakov** [vercel/next.js#29456]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

12.19.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When i updated in my project version of nextjs to the latest (11.1.2 or 11.1.1) with enabled feature webpack 5 in my next.condif.js i got some error related with useContext when start `next dev -p 9999`, but `next build` works fine and if i disable webpack 5 `next dev` also works fine

In my _app.tsx:
```
<RootStoreProvider data={someDataForInitialState}>
            <MainLayout>
            </MainLayout>
</RootStoreProvider>
```

And i have helper function, which i use in my pages/components for get data from store context
```
export function useStores(): StoreContextType {
    const context = useContext(StoreContext);
    if (context === undefined) {
        throw new Error("useStores must be used within RootStoreProvider");
    }

    return context;
}
```

So, when i starts next dev i see that error:
![image](https://user-images.githubusercontent.com/22046753/135070461-80b40e46-edb9-4a9d-9da2-816ddcb11ac2.png)

### Expected Behavior

All works fine!

### To Reproduce

yarn run next dev

**Comment by timneutkens** [comment]
Closing as no reproduction was provided.

**Comment by hi-paul** [comment]
exactly same issue after upgrading nextjs from 10.2.3 to 12.0.7
