### ISSUE TITLE
Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by randalpinto** [vercel/next.js#29582]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

12.22.1

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

Other platform

### Describe the Bug

When packaging up my application for serverless deployment the following code:

https://github.com/vercel/next.js/blob/canary/packages/next/server/next-server.ts#L295

gets packaged up to:

true = JSON.stringify(true);

which results in the following exception at runtime:

```
"/var/task/chunks/602.js:429285",
        "            true = JSON.stringify(true);",
        "            ^^^^",
        "",
        "SyntaxError: Invalid left-hand side in assignment",
        "    at wrapSafe (internal/modules/cjs/loader.js:988:16)",
        "    at Module._compile (internal/modules/cjs/loader.js:1036:27)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Module.require (internal/modules/cjs/loader.js:961:19)",
        "    at require (internal/modules/cjs/helpers.js:92:18)",
        "    at Object.__webpack_require__.f.require (/var/task/pages/api/test.js:495:28)",
        "    at /var/task/pages/api/test.js:418:40",
        "    at Array.reduce (<anonymous>)"
```

### Expected Behavior

No exception

### To Reproduce

I am deploying my app using: `https://github.com/serverless-nextjs/serverless-next.js`

A simple API route that returns 200 OK results in this error.

**Comment by PatrickChoDev** [comment]
isn't `true` the JavaScript and TypeScript restricted words?
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html
