### ISSUE TITLE
Add docs explanation for why to use each next/image layout

### ISSUE THREAD

**Issue by kara** [vercel/next.js#29625]
### Describe the feature you'd like to request

We recently got feedback from a partner that it's not clear how to select the "right" layout mode for your next/image instance. In other words, the current docs explain *what* each layout mode does, but not *why* each layout mode might be right for your app. 

### Describe the solution you'd like

Examples of canonical use cases for each layout mode might be helpful. Also might be good to have a short, more general discussion about how to decide. 

### Describe alternatives you've considered

There could also be a dedicated guide for layout modes, but I think the core problem could be solved with a paragraph and a few examples.

**Comment by leerob** [comment]
Closing this since we will be moving forward with `next/future/image` and less magic layouts, more `style` prop.
