### ISSUE TITLE
More simplified examples for redirects and rewrites

### ISSUE THREAD

**Issue by molebox** [vercel/next.js#29727]
More simplified examples for how to do redirects and rewrites

**Comment by ismaelrumzan** [comment]
@molebox Do you see these examples being added to the actual page here:
https://nextjs.org/docs/api-reference/next.config.js/redirects

Or being added as subfolders in the code examples here:
https://github.com/vercel/next.js/tree/canary/examples/redirects

Or possibly both? i.e First being referenced in the doc page and then linking to additional code examples

Are there specific areas that you had in mind? I check with CS common recurring themes

**Comment by molebox** [comment]
@ismaelrumzan I think having the examples on the docs page would be most helpful. If you also want to add them to the examples repo, that would be a great bonus. 👍

**Comment by ismaelrumzan** [comment]
@molebox Great, I'm going to work on a standalone error codes page such as `docs/error/codes.mdx`. 
In terms of navigation, it feels it should reside under the Reference > Error Codes (in the top nav drop-down).

**Comment by molebox** [comment]
How will that page be structured @ismaelrumzan ? I like the idea.
