### ISSUE TITLE
node 16.11.0 and eslint 8.0.0 breaks lint command

### ISSUE THREAD

**Issue by varand-pez** [vercel/next.js#29802]
### What example does this report relate to?

linting 

### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.11.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

locally

### Describe the Bug

I recently upgraded node to v16.11 as it was requirement for eslint latest 8.0.0 version.
I noticed lint command is no longer working throwing an error below

<img width="595" alt="Screen Shot 2021-10-11 at 2 13 46 AM" src="https://user-images.githubusercontent.com/47469980/136764853-67217dbe-0326-4f6c-b42d-7cf2a2f4f965.png">

### Expected Behavior

yarn run lint to work as expected

### To Reproduce

upgrade to latest version of eslint 8.0.0 and try eslint

**Comment by stefanprobst** [comment]
see #29770
