### ISSUE TITLE
Puppeteer does not work on vercel plattform

### ISSUE THREAD

**Issue by 28development** [vercel/next.js#29997]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

npm run build 

### Describe the Bug

I am using puppeteer in my API routes. I basically go to a page and generate a pdf file and sent an email.
This works perfectly fine locally, but it does not work on vercel.

I get a 500 error code with following message:

```
[POST] /api/sendgrid
21:54:39:79
2021-10-17T19:54:40.690Z	089c6c73-09af-48cb-a740-be76fc06b7a0	ERROR	Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912).
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:88:27)
```

### Expected Behavior

I expect to have a successful call so that puppeteer can generate a pdf from my page URL.

### To Reproduce

You can probably reproduce this creating an api file and calling that using fetch or axios.
One needs to install puppeteer and call a function like this:

```
async function generatePdf() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  // GEN_PDF_URL, is the URL which shall be generated later on to a pdf file
  await page.goto(process.env.GEN_PDF_URL, {
    waitUntil: "networkidle2",
  });
  const pdf = await page.pdf({
    path: 'wahlkalender.pdf',
    printBackground: true,
    format: 'a4',
  });
  await browser.close();

  return pdf;
}
```

**Comment by neg4n** [comment]
Hey! I think you need https://www.npmjs.com/package/chrome-aws-lambda to get this working
