### ISSUE TITLE
webpack 5 can't resolve `_http_common` node built in module

### ISSUE THREAD

**Issue by remorses** [vercel/next.js#30091]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

12

### What browser are you using?

Chrome

### What operating system are you using?

Mac Big Sur

### How are you deploying your application?

not relevant

### Describe the Bug

When using webpack 5, you cannot import or require the built in module `_http_common` (this module obviously is only used server side inside `getStaticProps`)

It works on webpack 4

> 

### Expected Behavior

I should be able to import `_http_common`

### To Reproduce

https://github.com/remorses/webpack5-next-bug-code-elimination

**Comment by timneutkens** [comment]
Turns out this is not related to SWC: #31166, I've move it to `area: Compiler`.

**Comment by remorses** [comment]
The problem is `NodeTargetPlugin` here https://github.com/webpack/webpack/blob/14dd4f912c013f060bf7843a3d5462a51ff3051b/lib/node/NodeTargetPlugin.js#L12

It's missing the `_http_common`  builtin module

In nextjs the plugin is imported [here](https://github.com/vercel/next.js/blob/351d225fc57d1e857b1326e2221d61a2a3632630/packages/next/compiled/webpack/webpack.js#L13) i think
