### ISSUE TITLE
next lint conflict with eslint 8 in ts example project

### ISSUE THREAD

**Issue by kaos1478** [vercel/next.js#30115]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.9.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next lint

### Describe the Bug

The command next lint is not working with eslint version 8. 

error - ESLint must be installed: yarn add --dev eslint

### Expected Behavior

lint the project

### To Reproduce

`yarn create next-app --typescript`
`cd project-name`
`yarn lint`

**Comment by gravyboat** [comment]
@kaos1478 Discussion is here: https://github.com/vercel/next.js/discussions/29951 PR for the fix is here: https://github.com/vercel/next.js/pull/29865

**Comment by housseindjirdeh** [comment]
Thanks for sharing relevant links @gravyboat. ESLint 8 is not yet supported so please downgrade to v7 for the meantime:

- `yarn remove eslint && yarn add --dev eslint@"<8.0.0"`
- `npm uninstall eslint && npm install --save-dev eslint@"<8.0.0"`

Closing this since it's a duplicate!
