### ISSUE TITLE
404 page is exported to 404/index.html when trailingSlash is enabled

### ISSUE THREAD

**Issue by fahadlabs** [vercel/next.js#30300]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.12

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu

### How are you deploying your application?

next export

### Describe the Bug

I don't remember the previous version, but it was working well before. When I updated the `next` version to **11.1.2**, `/about` exports as `/about.html`, that's why the doesn't work.
Then I enabled **trailingSlash**, now the mentioned above case is solved but `404.tsx` is also exported as `404/index.html` which is not expected according to the static servers.

### Expected Behavior

`404.tsx` should be exported as `/404.html` even when **trailingSlash** is enabled.

### To Reproduce

N/A

**Comment by romanonatacha** [comment]
any updates? I'm having the same issue

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.7-canary.5` of Next.js, please update and give it a try!
