### ISSUE TITLE
[ERR_MODULE_NOT_FOUND]: Cannot find package 'nanoid'

### ISSUE THREAD

**Issue by mufteev** [vercel/next.js#30363]
### What version of Next.js are you using?

12.0.0

### What version of Node.js are you using?

14.18.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

Importing package 'nanoid' causes error:

```
error - unhandledRejection: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'nanoid' imported from .next\server\pages\datasets\catalog\[catalog_id].js
Did you mean to import nanoid-npm-3.1.30-58cf6fe7ec-276d0d4b0c.zip/node_modules/nanoid/index.cjs?
```

package.json dependencies:
`"nanoid": "^3.1.30"`

### Expected Behavior

Successful import

### To Reproduce

Occurs when:
yarn version 3.1.0 [berry] - without dir _node_modules_ (only _/.yarn/cache_) and PnP

- yarn dev
- yarn build

Minimal reproduce in [https://github.com/mufteev/BUG-debugging-with-new-line-in-template-literals](https://github.com/mufteev/BUG-debugging-with-new-line-in-template-literals)

**Comment by ericvera** [comment]
FYI, while this gets fixed I was able to get unblocked by adding `experimental: { esmExternals: false },` to `next.config.js` as suggested in [#30873](https://github.com/vercel/next.js/issues/30873#issuecomment-961246661).

**Comment by kmvan** [comment]
> FYI, while this gets fixed I was able to get unblocked by adding `experimental: { esmExternals: false },` to `next.config.js` as suggested in [#30873](https://github.com/vercel/next.js/issues/30873#issuecomment-961246661).

Which package?

**Comment by kmvan** [comment]
I think this is a Node bug. Meet it with only node app.

**Comment by rtritto** [comment]
@balazsorban44 This issue can be closed.
