### ISSUE TITLE
Seems NextRequest.ua does not properly extend to the type IResult

### ISSUE THREAD

**Issue by TERADA-DANTE** [vercel/next.js#30597]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

v14.18.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

When it comes to the type of `NextRequest`, it has property ua which refers to useragent.
According to next/server, ua's type is `UserAgent` which is declared as below
```typescript
// in node_modules/next/dist/server/web/spec-extension/request.d.ts

interface UserAgent extends IResult {
    isBot: boolean;
}
``` 

The type `IResult` comes from 3rd party libary(ua-parser-js) and it has properties such as browser, os, etc.

Bug is that when I access to ua in vscode, it only shows isBot property
![Screen Shot 2021-10-29 at 15 39 15](https://user-images.githubusercontent.com/55175301/139387729-89d44b9a-932a-483c-90ec-6cb1ebd18d56.png)
.

### Expected Behavior

it should show other properties such as browser, os, etc.

### To Reproduce

create a file(`_middleware.ts`) in your /pages and try to access request.ua and its properties

**Comment by javivelasco** [comment]
This is working in the most recent version:

<img width="567" alt="CleanShot 2022-01-12 at 13 42 48@2x" src="https://user-images.githubusercontent.com/1634922/149142476-409630a2-6319-49dc-8219-8ee90c88ce41.png">

**Comment by TERADA-DANTE** [comment]
@javivelasco Thanks
