### ISSUE TITLE
V12.0.1 URL Import - `Cannot find module or type declarations` when deploying to Vercel

### ISSUE THREAD

**Issue by mquanten** [vercel/next.js#30627]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

v14.17.6

### What browser are you using?

Safari/Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

Vercel

### Describe the Bug

Importing Confetti and rendering in a simple application, works perfectly on dev server when running `next dev` error shows in IDE and when deploying to Vercel.

Full error message: 
```
Type error: Cannot find module 'https://cdn.skypack.dev/canvas-confetti' or its corresponding type declarations.
```

### Expected Behavior

Deploy to work without issue.

### To Reproduce

Create next.js project on Version 12 using the following code

```index.tsx
import confetti from "https://cdn.skypack.dev/canvas-confetti"
import {useEffect} from "react"

export default function Home() {
  useEffect(() => {
    confetti()
  })
  return <h1>Home</h1>
}
```

**Comment by abdelmomen1985** [comment]
I run into this error also when using typescript with next.js , just add //@ts-ignore before the line of confetti import and it will fix the problem , I think this problem is with your typescript config not with nextjs itself

**Comment by machooper** [comment]
> I run into this error also when using typescript with next.js , just add //@ts-ignore before the line of confetti import and it will fix the problem , I think this problem is with your typescript config not with nextjs itself

That makes sense, thank you.

anyway to fix this in my `tsconfig.json` Permanently for URL imports?

**Comment by Kabil-Boutou** [comment]
@machooper Did you add this code in your next.config : `experimental: {
    urlImports: ['https://cdn.skypack.dev'],
  },` ?  it may be the problem.

**Comment by machooper** [comment]
> @machooper Did you add this code in your next.config : `experimental: { urlImports: ['https://cdn.skypack.dev'], },` ? it may be the problem.

Yes this code is in my ‘next.config.js’ as I said the code works on the dev server, it’s just when deploying.

**Comment by codeflowee** [comment]
@machooper How this issue can be solved is doing some manual re-mapping of type definitions:

Firstly change `tsconfig.json` and add:
```json
{
  "compilerOptions": {
    ...
    "incremental": true
  },
  ...
}
```

Secondly install type definitions for your module, for your case:
```shell
npm install -D @types/canvas-confetti
```

Thirdly add `@types` directory into project root with `canvas-confetti.d.ts` file:
```typescript
declare module 'https://cdn.skypack.dev/canvas-confetti' {
  export default confetti;
}
```

Hope this helps 😄

**Comment by codeflowee** [comment]
@machooper There is some manual module definitions mapping required.

Firstly install type definitions to `devDependencies` for your module:
```shell
npm i @types/canvas-confetti -D
```

Secondly update `tsconfig.json`:
```json
{
  "compilerOptions": {
    ...
    "incremental": true,
    "baseUrl": "./",
    "paths": {
      "https://cdn.skypack.dev/canvas-confetti": [
        "node_modules/@types/canvas-confetti"
      ]
    }
  },
  ...
}
```

Now you should be good to go, hope this helps 😄

**Comment by machooper** [comment]
@codeflowee that’s helpful thank you. It would be nice not to have to install anything when using a CDN including types, I guess this will suffice for now though.

**Comment by codeflowee** [comment]
@machooper I assume that is the reason **URL imports** is still experimental feature. I personally don't find it as a problem compared to the benefit TypeScript provides, although it will become painful to update if modules have non backward compatible updates.

**Comment by machooper** [comment]
@codeflowee perhaps a way of importing `@types` packages via a CDN into the `additional.d.ts` file will be a possible fix in the future?

**Comment by codeflowee** [comment]
It makes sense to see what is in `next.js` roadmap https://github.com/vercel/next.js/milestones

If you don't see something that would benefit engineers you can always request/propose feature.

**Comment by aboveyunhai** [comment]
Well, in some edge special case where your import url is actually a `typescript` files itself then it's not going to work. 
I guess `//@ts-ignore` is the only way to go right now.
