### ISSUE TITLE
[i18n] i18n breaks optional catch-all route for index

### ISSUE THREAD

**Issue by expjazz** [vercel/next.js#30631]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

Vercel

### Describe the Bug

Seems the same issue as #19934. It seems this was resolved, but somewhere along the way it broke again.

We have a project with structure of pages/[userId]/social/[[...socialId]]:

- /user-123/social: does not work when it should.

- /user-123/social/social-123: work as expected 

- The issue only happens whenever the project is i18n configured.

If I revert the Next.js version to 10.0.5-canary.9, it works again.

### Expected Behavior

Both /user-123/social and /user-123/social/social-123 should work.

### To Reproduce

1. Go to [https://routing-test-peach.vercel.app](https://routing-test-peach.vercel.app)
2. Index page shows a 404 [ https://routing-test-peach.vercel.app/user-123/social](https://routing-test-peach.vercel.app/user-123/social)
3. Any other page will work [https://routing-test-peach.vercel.app/user-123/social/social-123](https://routing-test-peach.vercel.app/user-123/social/social-123)

Repo for reproduction: [https://github.com/expjazz/routing-test](https://github.com/expjazz/routing-test)

**Comment by zkwsk** [comment]
Any news on this? We are facing the same problem when upgrading to Next 12 in our application.

**Comment by augustosamame** [comment]
+1

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.0.11-canary.2` of Next.js, please update and give it a try!
