### ISSUE TITLE
Failed to build nextjs app

### ISSUE THREAD

**Issue by thatcatdrout** [vercel/next.js#30636]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

12.22.5

### What browser are you using?

Librewolf 

### What operating system are you using?

Linux

### How are you deploying your application?

Vercel

### Describe the Bug

So i tried to build my nextjs app. Everything worked when i started a development server but failed when tried to build the app.

### Expected Behavior

It should just build a production build

### To Reproduce

```
git clone https://github.com/thatcatdrout/catdrout.to
yarn 
yarn build
```

**Comment by Itshardtopickanusername** [comment]
same here, i'm getting
```
info  - Collecting page data ..New Prisma Client | NODE_ENV: production
info  - Collecting page data ...New Prisma Client | NODE_ENV: production

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (...\node_modules\jest-worker\build\workers\ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (...\node_modules\jest-worker\build\workers\ChildProcessWorker.js:275:12)
    at ChildProcess.emit (node:events:365:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  type: 'WorkerError'
}

```
it was working fine not too long ago, suddenly this happens

**Comment by timneutkens** [comment]
Thanks for the report @thatcatdrout, this seems related to `swcMinify` so in order to unblock yourself you can temporarily disable `swcMinify` in `next.config.js`. We'll investigate it further!
