### ISSUE TITLE
[middlewares via Edge Functions] fetch is not complete, runtime is not addressable

### ISSUE THREAD

**Issue by panva** [vercel/next.js#30739]
### What version of Next.js are you using?

12.0.4-canary.15

### What version of Node.js are you using?

v14.18.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Cloudflare Workers, which powers Edge Functions, has a caveat in the `fetch` implementation. The `referrerPolicy`, `credentials`, and `mode` options cannot be used. When used the code will throw/reject.

This is fine in Cloudflare Workers since it's easy to detect that javascript runtime using something along the lines of `typeof WebSocketPair === 'function'`, but it is not fine for Edge Functions since that global context (e.g. WebSocketPair) is not reachable.

Without a way to detect Edge Function runtime it is not possible to write universal code that uses these options in the browser but omits using them in Edge Functions.

### Expected Behavior

It is possible to uniquely detect the runtime so that workarounds in universal libraries can be made to target said runtime.

If there's a global that is unique to Edge Functions / Middlewares, we can use that, if not, add something fixed to process.env instead?

### To Reproduce

This works in `next dev` but fails deployed to vercel.com. If a universal library does this, it needs a way to detect Edge Functions are used as a runtime to omit adding the `referrerPolicy`, `credentials`, and `mode` options.

```js
export async function middleware(req, ev) {
  let fetchFailed = false;
  try {
    await fetch(new URL('https://www.googleapis.com/oauth2/v3/certs'), {
      redirect: 'manual',
      method: 'GET',
      referrerPolicy: 'no-referrer',
      credentials: 'omit',
      mode: 'cors',
    })
  } catch (err)  {
    fetchFailed = err.stack
  }

  return new Response(JSON.stringify({
    fetchFailed,
  }), { status: 200 });
}
```

**Comment by panva** [comment]
@javivelasco @timneutkens are you planning any way to address/identify the runtime to be able to workaround the deficiencies in CF Workers' `fetch` implementation?

**Comment by leerob** [comment]
Hey @panva! Happy to talk with you about our plans for Edge Functions (and the Edge Runtime in general).

I'll send you a message 😄

**Comment by panva** [comment]
Since CF Workers added navigator.userAgent (and navigator.userAgentData too? not sure, hope so). I would expect both dev and production runtimes of next.js middlewares to have the same method of detecting the runtime the code is running in.

**Comment by panva** [comment]
cc @balazsorban44

**Comment by panva** [comment]
@kodiakhq I kindly ask that you re-open this issue. The runtime is not addressable "at runtime" still. There's no there's no unique global and there's no `navigator.userAgent` that we can interpret.

Compile time may be useful for user land code on your platform, but is of 0 value to end users who employ use of universal js libraries that need to work around the different platform's inconsistencies and quirks.

**Comment by panva** [comment]
@balazsorban44 thank you

**Comment by panva** [comment]
`EdgeRuntime` runtime global can now be used to identify that Edge Functions or `dev/local` is used. But in order to work around the unique quirks of cloudflare workers behind Edge Fucntions, that information is still left to be surfaced.

**Comment by javivelasco** [comment]
Thanks @panva

Please feel free to report any quirk you find in https://github.com/vercel/edge-runtime so if it makes sense there we will update it to make it closer to production. We can also deploy updates into our production runtime to make them work the same in both development and production so it is important that we keep track of what the differences are.

The value that `EdgeRuntime` holds will be different in production and development though. In production you should see `vercel` as the value while in development it will be `edge-runtime`. Do you think that would work for your use case? Still we should address those differences at a runtime level. I already added it to our backlog.

**Comment by panva** [comment]
@javivelasco having a discernible global value works just fine. beta.11 is the last one that works for me, the latter betas have missing globals and broken fetch (had no time to investigate further) but i've opened a [ticket](https://github.com/vercel/edge-runtime/issues/34).

**Comment by javivelasco** [comment]
Thank you! We will work on that one 🙏
