### ISSUE TITLE
Maximum call stack size exceeded on next 11

### ISSUE THREAD

**Issue by joshma** [vercel/next.js#30754]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When running `next dev`, all requests error with `Maximum call stack size exceeded`:

```
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /<redacted>/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

info  - Using external babel configuration from /<redacted>/.babelrc
error - static/chunks/pages/_app.js
Maximum call stack size exceeded
event - build page: /next/dist/pages/_error
wait  - compiling...
error - static/chunks/pages/_app.js
Maximum call stack size exceeded
wait  - compiling...
error - static/chunks/pages/_app.js
Maximum call stack size exceeded
event - build page: /next/dist/pages/_error
wait  - compiling...
error - static/chunks/pages/_app.js
Maximum call stack size exceeded
```

I don't see any other logs, so I'm not entirely sure if this is a Next.js issue or some dependency. Running `rm -rf .next/ node_modules/` and re-installing doesn't work either, but _restarting my laptop_ does.

Is there some way I can get the full stack?

This has been fine for a few months now and only started happening frequently (about once a day) in the last 2 weeks.

### Expected Behavior

I'd expect the page to load normally.

### To Reproduce

I can't repro this unfortunately, so I'm looking for troubleshooting steps to further isolate the error.

**Comment by joshma** [comment]
Alright, I'm now convinced this is coming from some part of webpack (just based on Googling and finding other issues from the past). But setting `--stack-size=10000` in the `next` shebang, just to test, did work - so I don't think this is some recursive loop but just a genuine stack size problem.

Feel free to close if this is out of scope of next.js, but I figured it might be relevant if next.js is fiddling with stack size somewhere, managing the webpack config, or has some flag I can use to make debugging this better.

**Comment by timneutkens** [comment]
You can use the normal debugging methods of profiling during the development run and checking the memory usage. Next.js 12 has many improvements including improved memory management so I'd recommend to start by upgrading to the latest version 👍
