### ISSUE TITLE
Minify breaks on some middleware

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#30798]
Problem middleware: [https://github.com/leerob/leerob.io/blob/main/pages/_middleware.ts](https://github.com/leerob/leerob.io/blob/main/pages/_middleware.ts) 

Error and workaround: [https://github.com/vercel/next.js/pull/30122](https://github.com/vercel/next.js/pull/30122)

Note: Does not present itself in `next start`

**Comment by ijjk** [comment]
Re-opening as this appears to still be an issue although reproduction is not clear currently. This could be caused by ordering of chunks being changed potentially 🤔 

x-ref: https://github.com/vercel/next.js/issues/31153

**Comment by kdy1** [comment]
I think this can be closed. There's no known issue with popular libraries anymore.
