### ISSUE TITLE
"for await" regenerator transform breaks

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#30801]
Reported here: [https://vercel.slack.com/archives/CGU8HUTUH/p1634933363100400?thread_ts=1634931484.096800&cid=CGU8HUTUH](https://vercel.slack.com/archives/CGU8HUTUH/p1634933363100400?thread_ts=1634931484.096800&cid=CGU8HUTUH)

Seems there is a bug with regenerator when using `for await`, at least from seeing the reported error.

**Comment by kdy1** [comment]
I think this is same as https://github.com/swc-project/swc/issues/5383, which is already fixed
