### ISSUE TITLE
Port Relay Babel plugin to SWC

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#30805]
@hanford has done a bunch of research into porting babel-plugin-relay. It comes down to this fairly simple transform: [https://gist.github.com/hanford/10401629eb7d82d47b275f59356d86f5](https://gist.github.com/hanford/10401629eb7d82d47b275f59356d86f5) so I think we can port it to SWC relatively easily without having to implement a GraphQL parser.

Message from @hanford:

All `babel-plugin-relay` does, is look for `graphql``` tagged template literals, performs a regex to extract the name of the operation and then generates appends ImportDefaultSpecifier with that name.

- Before `babel-plugin-relay` running:
    
    ```jsx
    function MyQueryRenderer () {
      return (
        <QueryRenderer
        	query={graphql`
    				query SearchUserQuery {
    					findUser {
    						name
    					}
    				}
    		`}
    	/>
      )
    }
    ```
    
- After `babel-plugin-relay` runs:
    
    ```jsx
    import graphql__a6767a3b from "dazzle-types/SearchUserQuery.graphql";
    
    function MyQueryRenderer () {
      return (
          <QueryRenderer
              query={graphql__a6767a3b}
          />
      );
    }
    ```
    

In addition to the babel plugin I created, I also have a JSCodeshift that I've been running on our frontend to then allow me to begin playing around with SWC.

The source for the JSCodeshift is below:

[https://gist.github.com/hanford/003f07533f7bfc8af7fc90a838f0e963](https://gist.github.com/hanford/003f07533f7bfc8af7fc90a838f0e963)

**Comment by AndrewIngram** [comment]
FYI the links above point to notion pages rather than gists

**Comment by AndrewIngram** [comment]
Something to bare in mind is that because the transforms generate an import declaration, any such plugin would need to be able to read a project's Relay configuration to determine where the `artifactDirectory` is. The default is a `__generated__` directory that's a sibling to whatever module is being transformed, but it could also be a globally configured location.

**Comment by rrdelaney** [comment]
In JS-world `artifactDirectory` is pretty easy to get via the `relay-config` package:

```js
> require('relay-config').loadConfig().artifactDirectory
'src/queries/__generated__'`
```

**Comment by tony** [comment]
The next stable release of relay v13 will be in rust ([their checklist](https://github.com/facebook/relay/issues/3180), [compiler/](https://github.com/facebook/relay/tree/d7cde3a/compiler))

> In the next major Relay Release (v13) the new rust version of the compiler will be the only version.
> \- 2 weeks ago in [Bye, JS Compiler, we love you!@4467ae8](https://github.com/facebook/relay/commit/4467ae84c3cdb24eefb3069ede32a24115ff6d44#diff-b28b1ed9821f38c64524ea13e19264bb0772f8376afffd5d8a1f8277621833eb)

Can relay being in rust benefit this effort in any way?

**Comment by timneutkens** [comment]
> Can relay being in rust benefit this effort in any way?

As far as I'm aware the answer is no because the compiler would already be run next to having the transform.

**Comment by wongmjane** [comment]
fyi: `relay-config` has been removed

facebook/relay#3677

**Comment by aalises** [comment]
🤸‍♂️ What's the status on this? waiting for it to finally move to `SWC`.

**Comment by tbezman** [comment]
@aalises and other folks in this thread. I tried adding support for Relay in https://github.com/vercel/next.js/pull/33240 . Can y'all check it out and give feedback?
