### ISSUE TITLE
_middleware causes truncated main.js in development mode

### ISSUE THREAD

**Issue by pecoram** [vercel/next.js#30886]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

In development mode if there is _middleware file (with some logic inside or empty) when I change something anywhere in the code the page goes blank and I get this error:

```
[Fast Refresh] rebuilding
Refreshing page data due to server-side change
Navigated to http://localhost:3000/
main.js?ts=1635942768734:1014 Uncaught SyntaxError: Invalid or unexpected token
```
or
```
main.js?ts=1635943284319:1442 Uncaught SyntaxError: Unexpected end of input
```

Since the main.js is truncated.

### Expected Behavior

```
[Fast Refresh] rebuilding
[Fast Refresh] done in 302ms
```

### To Reproduce

Create a _middlware file inside pages folder like this:

```
export function middleware(req) {
   console.log(req);
}
```
And try to change something somewhere

**Comment by switz** [comment]
Seeing this quite consistently on my end as well. On firefox the messaging is a bit different, but it's the same issue. Just adding the logs here so firefox users can find this issue as well:

```
Uncaught SyntaxError: missing } after function body
main.js:1238:13note: { opened at line 1235, column 39main.js:1235:39
Uncaught SyntaxError: "" literal not terminated before end of script
```

**Comment by balazsorban44** [comment]
I'm not able to reproduce it locally. You could try upgrading with `npm i next@latest` or add a complete reproduction.

**Comment by switz** [comment]
I tried created a basic reproduction, but the simplest example wouldn't do it. So it must be something complex interacting between my app configuration and middleware. I'll try to break down what's causing the error. Seems to be some kind of race condition (refreshing before compilation is complete). If I refresh again after the error it always works.
