### ISSUE TITLE
Statically imported image doesn't work when next.config.js basePath and images are configured 

### ISSUE THREAD

**Issue by GiancarlosIO** [vercel/next.js#30900]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

12.22.5

### What browser are you using?

Chrome 95

### What operating system are you using?

windows 10

### How are you deploying your application?

vercel

### Describe the Bug

I have set `basePath: /docs` and the Images imported statically work without problems. But once I configured the next config image option all the images give a 404 error .
I have read the docs and I have not found something related to this. I just want to to understand if it's a bug or a feature 🤔 

### Expected Behavior

The images that are imported statically should load without problems if basePath and images nextjconfig options are configured.

### To Reproduce
https://github.com/GiancarlosIO/nextjs-image-404-bug

1. `git clone git@github.com:GiancarlosIO/nextjs-image-404-bug.git`
2. `yarn install` && `yarn dev`, the trophy image load without problems
3. uncomment the images option in the next.config.js
4. `yarn dev`, now the trophy image give 404 error 😢 

Edit: it also gives a 400 bad request error with v11.1.2. The repository contains a v11 branch where you can see the same error.
I have checked the source of the next/dist/server/image-optimized.js and looks like this validation fails 
```
console.log({ upstreamType });
if (!upstreamType.startsWith('image/')) {
    res.statusCode = 400;
    res.end("The requested resource isn't a valid image.");
    return {
        finished: true
    };
}
```
I have added a console.log to see the value of upStreamType:
![image](https://user-images.githubusercontent.com/17274950/140231096-d661bb14-355a-4856-b77d-d6f3f4bc2c77.png)

Edit2: Can confirm that this 'text/html; charset=utf-8'' is because the Image path (that is passed as query param) doesn't have the basePath.
```
/_next/image/?url=%2F_next%2Fstatic%2Fimage/my-image.kj123123.png
```
this query param `%2F_next%2Fstatic%2Fimage/my-image.kj123123.png` gives a 404 error.
It should be: `%2F BASE_PATH %2F_next%2Fstatic%2Fimage/my-image.kj123123.pn`

Is this is the expected behavior?
I can do something like this but maybe it should be handled automatically for images that are statically imported?
```
import myImage from '../../assets/images/my-image.png';
const basePath = '/docs'

<Image
        alt="learning path"
        src={basePath + learningPathImageUrl.src} <== this fixes the 400 bad request
        className="pointer-events-none"
        width={810}
        height={443}
      />
```
Also, the docs don't mention anything about the object that you get when you import an image.
At first, I used `basePath + learningPathImageUrl` but it throw an error because the result was '[object, object]' 😢 
```
{
  blurDataURL: "",
  height: 444,
  src: "",
  width: "",
}
```

**Comment by avaleriani** [comment]
@kara any update about this issue?

**Comment by paul-pro** [comment]
Hey. I've randomly bumped into this bug using `Image` with internal path string for `src` with a combination of `basePath` at next.config.js

```js
<Image src={'/trophy-image.png'} width={120} height={120} />
```

Solution was to prefix path string with base path, and on a second glance https://nextjs.org/docs/basic-features/static-file-serving mentions 

> Files inside public can then be referenced by your code starting from the base URL (/).

it's just not that obvious that when you change base path you should manually provide it to the Image srcs.

```js
<Image src={'/docs/trophy-image.png'} width={120} height={120} />
```

Now I wonder if that is the desired behaviour? And if someone wants to contribute should they improve docs or add a feature that would use basePath in the Image component automatically?
