### ISSUE TITLE
"Global" rewrite + fallback: blocking = prefetch broken

### ISSUE THREAD

**Issue by patricktyndall** [vercel/next.js#30929]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

Safari

### What operating system are you using?

MacOS

### How are you deploying your application?

serverless-next.js

### Describe the Bug

Symptom: When I hover on a `<Link/>` to trigger prefetching, `getStaticProps` is being called without the dynamic route param (`params.all` is undefined). This makes prefetching impossible. I'm running locally using `next build && next start` -- this isn't related to any deployment framework.

My Setup:

The page I'm trying to prefetch is `/pages/listings/id/[...all]`. This page uses `fallback: blocking`, so prefetching involves running `getStaticProps`. As mentioned above, `getStaticProps` is being called without the necessary dynamic route params.

My app has the following "global" rewrite. As soon as I remove this rewrite, the prefetching issue goes away. The rewrite in question (This is used to create clean URLs for CMS-driven pages, which live at `/pages/content/[[...all]]`):

```
{
	source: '/:path*',
	destination: '/content/:path*',
}
```

### Expected Behavior

Prefetching triggers `getStaticProps` with the necessary dynamic route param.

### To Reproduce

Create an app with the above rewrite and hover on a link to prefetch another page. The prefetched page's `getStaticProps` will be called without the dynamic route `params`.

**Comment by balazsorban44** [comment]
I could not reproduce this locally, could you please create a runnable minimal reproduction so we can investigate?
