### ISSUE TITLE
Scheme-relative URLs have slashes merged

### ISSUE THREAD

**Issue by SethFalco** [vercel/next.js#30947]
### What version of Next.js are you using?

11.1.2

### What version of Node.js are you using?

10.19.0

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

next dev

### Describe the Bug

When I specify a URL such as `//example.org`, I would expect this to appear as it in the output.
That way if the user is on `http://example.com` they will be taken to `http://example.org`, but if they're on `https://example.com`, they'll be taken to `https://example.org`.

Next.js merges all repeated forward-slashes if it's not an absolute URL, but this includes relative URLs that want to reuse the protocol.

> ```
> <a href="//example.com">Scheme-relative URL</a>
> ```
> — https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

This changes what should be a scheme-relative URL to a normal relative URL and breaks the link.

### Expected Behavior

Repeated slashes at the start of an `href` shouldn't be merged.

### To Reproduce

```tsx
<Link href="//example.org" passHref>
  <a target="_blank" rel="noopener noreferer">
    Example
  </a>
</Link>
```

**Comment by SethFalco** [comment]
Closing as the PR was denied, looks like this won't be fixed. 😭

**Comment by icyJoseph** [comment]
What about:

```tsx
<Link href={{ pathname: "//example.org", protocol: "https" }}>Example</Link>
```

The protocol is perhaps a bit annoying, but for the most part it'd be `https` anyway, right?

**Comment by JanKaifer** [comment]
Hey, we don't think it's worth the tradeoff as mentioned here: https://github.com/vercel/next.js/pull/31119#pullrequestreview-980899657

What would make sense though is that we could throw an error on `//` to make this more explicit. And avoid some confusion.

It's not really a bug so I'll close this in favor of https://github.com/vercel/next.js/discussions/37128
