### ISSUE TITLE
next/script onLoad run once per cache Key (id, src)

### ISSUE THREAD

**Issue by bordeo** [vercel/next.js#30962]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

codesandbox

### Describe the Bug

When using more than one `Script` with same `id` or `src`, only first script that complete load trigger the `onLoad` prop.
Same problem happens using one `Script` but after unmount and remount, for example when navigating throughout client-side router the `onLoad` will not be called.
@giorgiabosello

### Expected Behavior

`Script` component should load once the src script but run `onLoad` on component did mount and script is loaded.

### To Reproduce

https://codesandbox.io/s/nextjs-script-onload-ltm95

**Comment by havran** [comment]
I just need same feature (fire onLoad every time, when script is added to attach some event listener). Any news here?

Meanwhile I use hook:

```tsx
import { useEffect, useState } from 'react';

type Callback = () => void;

interface ScriptAttributes {
  id: string;
  src: string;
  async: 'async';
  defer: 'defer';
}

function setAttributes<T>(el: Element, attributes: T): void {
  Object.keys(attributes).forEach((key: string) => {
    el.setAttribute(key, attributes[key]);
  });
}

function addScript(scriptUrl: string, elName: string, callback: Callback | undefined): void {
  const elScriptId = `${elName}-script`;
  const elScriptPresent: HTMLElement | null = document.getElementById(elScriptId);

  // Avoid multiple inserting of script element.
  if (elScriptPresent) {
    if (callback) {
      callback();
    }
    return;
  }

  const elScript: HTMLScriptElement = document.createElement('script');

  if (callback) {
    elScript.onload = () => callback();
  }

  setAttributes<ScriptAttributes>(elScript, {
    id: elScriptId,
    src: scriptUrl,
    async: 'async',
    defer: 'defer',
  });
  document.body.appendChild(elScript);
}

function useScript(name: string, src: string): boolean {
  const [loaded, setLoaded] = useState<boolean>(false);
  const callback: Callback = () => setLoaded(true);

  useEffect(() => {
    addScript(src, name, callback);
  });

  return loaded;
}

export default useScript;
```

And usage:

```tsx
  // inside component where is script loaded
   const loaded = useScript();

   useEffect(() => {
    if (elementRef.current && loaded) {
      elementRef.current.addEventListener('someevent', (e) => ...);
    }
  }, [customElementScriptLoaded]);
```

**Comment by giorgiabosello** [comment]
> I just need same feature (fire onLoad every time, when script is added to attach some event listener). Any news here?
> 
> Meanwhile I use hook:
> 
> ```tsx
> import { useEffect, useState } from 'react';
> 
> type Callback = () => void;
> 
> interface ScriptAttributes {
>   id: string;
>   src: string;
>   async: 'async';
>   defer: 'defer';
> }
> 
> function setAttributes<T>(el: Element, attributes: T): void {
>   Object.keys(attributes).forEach((key: string) => {
>     el.setAttribute(key, attributes[key]);
>   });
> }
> 
> function addScript(scriptUrl: string, elName: string, callback: Callback | undefined): void {
>   const elScriptId = `${elName}-script`;
>   const elScriptPresent: HTMLElement | null = document.getElementById(elScriptId);
> 
>   // Avoid multiple inserting of script element.
>   if (elScriptPresent) {
>     if (callback) {
>       callback();
>     }
>     return;
>   }
> 
>   const elScript: HTMLScriptElement = document.createElement('script');
> 
>   if (callback) {
>     elScript.onload = () => callback();
>   }
> 
>   setAttributes<ScriptAttributes>(elScript, {
>     id: elScriptId,
>     src: scriptUrl,
>     async: 'async',
>     defer: 'defer',
>   });
>   document.body.appendChild(elScript);
> }
> 
> function useScript(name: string, src: string): boolean {
>   const [loaded, setLoaded] = useState<boolean>(false);
>   const callback: Callback = () => setLoaded(true);
> 
>   useEffect(() => {
>     addScript(src, name, callback);
>   });
> 
>   return loaded;
> }
> 
> export default useScript;
> ```
> 
> And usage:
> 
> ```tsx
>   // inside component where is script loaded
>    const loaded = useScript();
> 
>    useEffect(() => {
>     if (elementRef.current && loaded) {
>       elementRef.current.addEventListener('someevent', (e) => ...);
>     }
>   }, [loaded]);
> ```

Any words from Next. We also use a hook based on [this one](https://usehooks.com/useScript/) and it's working perfectly.

**Comment by housseindjirdeh** [comment]
This is indeed an issue, so thanks all for flagging this. 

The hook is a workaround for now, but I'll either approve @bordeo's PR (#30966) to remove the current caching functionality or investigate a way to improve it so that it doesn't ignore `onLoad` for repeat scripts.

**Comment by bordeo** [comment]
@housseindjirdeh can I help doing something about this issue?

**Comment by tran-uvaro** [comment]
I get the same issue, my expectation is the script should load once, but onLoad must be called twice

**Comment by eps1lon** [comment]
I think it's technically correct to call `onLoad` only once because we only get the `load` events once. That's what we want in the end.

It seems safer to add a new event handler that fires once the script is ready. So once it basically fire with the `load` event and otherwise it fires at some other point (effect seems not ideal though).

For our use case specifically we were loading a 3rd party library. So we started out with a "pending" state and flipped that to "resolved" in `onload`. Now we immediately start with `resolved` if we know that the 3rd party library is available. And for `<Script />` loading simultaneously we're attaching `onload` to the actual `<script />` HTML element instead of using `<Script onLoad />`.

There are still some race conditions we might be missing though.

**Comment by bordeo** [comment]
I can agree with you that `onLoad` could run once but in this case an `onReady` props is mandatory to handle multiple use of the same 3rd party library.

In my experiences I didn't find a case where I need an `onLoad` event to run once.

**Comment by eps1lon** [comment]
> In my experiences I didn't find a case where I need an onLoad event to run once.

Sure. But that's a documentation issue. When you repurpose the `onLoad` handler you risk confusing people that know the `load` event and expect Next.js to de-duplicate scripts.

**Comment by bordeo** [comment]
Thank you @housseindjirdeh for your reply.

I'm using `Script` to load third-party JS for example "Klarna On-site messaging" or "Google Maps". 
I want use more than one "Klarna message" in a page and more than one "google maps widget".
To achieve that I use `Script` inside a component to render for example a Google Maps and I use that component more than once in page without think if `Script` is loaded or not because `Script` would take care of anything.
At the actual state to keep track if `Script` is already loaded in another component I must save in a persistent Global State the first time it loaded. 

But the problem manifests itself even when one `Script` is used and the component that use it un-mount and re-mount for example when changing route client-side.
I don't think this all this is a correct behavior. Maybe firing an `onReady` event could be the right way to solve this issue.

I didn't find a use case where `onLoad` that fired once is useful

**Comment by housseindjirdeh** [comment]
Thanks for the details @zacharyliu and @bordeo. I think I fully understand the concern now.

I agree that it would probably make more sense to have a separate prop for this (e.g. `onReady` or `onMount`). The easiest solution would be to throw this in a useEffect so that it runs every time the component is mounted:

```js
useEffect(() => {
  if (onReady) {
    onReady()
  }
}, [onReady])
```

There's no guarantee that this would run before `onLoad` though. Is that an issue? Or would it be better if `onReady` ran at the same time as `onLoad` for the first time and then after the component mounts after that?

**Comment by bordeo** [comment]
@zacharyliu explains very well.

It would be better if `onReady` ran at the same time as `onLoad` or after (never before) for the first time and then after the component mounts after that and is successfully loaded before.
Race conditions could occur easily when a user navigates to a page and suddenly click on a `Link` before `Script` is fully loaded. In this case, the component unmount before `onReady` is triggered.

**Comment by housseindjirdeh** [comment]
Thanks for brainstorming with me folks, I appreciate it :)

PR https://github.com/vercel/next.js/pull/38849 should solve for this by introducing `onReady` as a prop. Please feel free to leave any comments directly in the PR if you think anything should be changed, but it's set up to run after `load` for when the script first loads and then again with every component re-mount.

**Comment by Zerebokep** [comment]
Can't wait for it. :)
