### ISSUE TITLE
MongoDB example gives an error

### ISSUE THREAD

**Issue by callumok2004** [vercel/next.js#30976]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

16.12.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 11

### How are you deploying your application?

Development Server | yarn dev

### Describe the Bug

When using the MongoDB example, I receive the following error.
`error - TypeError: Cannot read properties of undefined (reading 'match')`

### To Reproduce

https://github.com/callumok2004/nextjs-reproduction/

**Comment by callumok2004** [comment]
This is an issue I'd like to have resolved asap, any ideas?

**Comment by balazsorban44** [comment]
Could not reproduce. You are also linking to your own code, not the actual example: https://github.com/vercel/next.js/tree/canary/examples/with-mongodb
