### ISSUE TITLE
i18n support with React Server components

### ISSUE THREAD

**Issue by leerob** [vercel/next.js#30987]
### Describe the feature you'd like to request

The alpha support for RSC inside Next.js currently doesn't support [Next.js' Internationalized Routing](https://nextjs.org/docs/advanced-features/i18n-routing).

### Describe the solution you'd like

Add support for this.

### Describe alternatives you've considered

N/A

**Comment by lachlanjc** [comment]
What's the ultimate vision on this? Just an example of how to implement it ourselves with middleware (not preferable, imo) or porting the prev structure to the app dir router?

**Comment by lachlanjc** [comment]
https://github.com/vercel/next.js/issues/42174#issuecomment-1302835862

**Comment by leerob** [comment]
This can be closed now, we will be providing docs and guidance on this per the linked comment!
