### ISSUE TITLE
External scripts added with `next/script` load only once

### ISSUE THREAD

**Issue by ndekross** [vercel/next.js#30984]
### What version of Next.js are you using?

12.0.2

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

While trying to integrate external scripts with `next/script`, I noticed that they load only once on a page or component mount. I've created a quick [demo](https://external-script-routing.vercel.app) to describe it more visually.

### Expected Behavior

I expect the status to turn green every time I visit the page using website navigation links without reloading.

### To Reproduce

[Source](https://github.com/ndekross/external-script-routing)

**Comment by housseindjirdeh** [comment]
Sorry for the delay here, this is indeed reproducible so thanks for flagging this!

Quick question: Would you prefer if this was the default behavior for every `<Script>` added to a page, regardless of strategy, or instead have a separate prop to enable this? I think the former makes more sense, but would like to hear if you have a different opinion :)

**Comment by bobbymart1n** [comment]
I'm also having this issue. If you put a useState function inside the onLoad prop using a boolean value and log the result of that state in a useEffect hook with a dependency on that state value, you can see this bug happen every time. Curious, is there a work around here? I feel like I've tried everything at this point.

**Comment by balazsorban44** [comment]
Hi, since `12.2.4`, you can use the `onReady` prop for this. See the docs: https://nextjs.org/docs/api-reference/next/script#onready
