### ISSUE TITLE
Server Components should have basic support for routing

### ISSUE THREAD

**Issue by devknoll** [vercel/next.js#30995]
At the very least, we should support throwing errors like `PageNotFound` from a Server Component to replace the properties like `notFound: true` supported by `getServerSideProps`/et al.

Throwing this after a fallback has been flushed is fine, but means the suspense boundary will be resolved by the client for now. This seems fine, since this seems like a rather extraordinary occurrence.

**Comment by shuding** [comment]
Another thing to add to this topic is, the router state has to be delegated to React. So we can handle route state transitions with timeouts properly instead of always blocking as of today which sacrifices the benefits of streaming.

**Comment by devknoll** [comment]
Closing as obsolete
