### ISSUE TITLE
Support for API Routes with Web Runtime

### ISSUE THREAD

**Issue by leerob** [vercel/next.js#30990]
### Describe the feature you'd like to request

The web runtime, which is used by Middleware, should also be available for use in API Routes. This would allow users to opt into a more lean & secure runtime to build faster APIs. It is also related to React Server Components efforts.

### Describe the solution you'd like

Each API route could export a config object that defines its runtime:

```js
export config = {
  runtime: 'web'
}
```

### Describe alternatives you've considered

N/A

**Comment by javivelasco** [comment]
I think we can close this :)
