### ISSUE TITLE
Next.js should redirect differing locale casing to the configured casing

### ISSUE THREAD

**Issue by ijjk** [vercel/next.js#31050]
When leveraging i18n we currently ignore casing when matching paths against locales. This can cause issues with duplicate content since we aren't redirecting to one single casing of the locale. 

We should also ensure all paths output with `locales` from `getStaticPaths` are using the configured casing for the locales as well. 

This change will need to be done in a major version as users might currently be relying on the case-insensitive handling of locales. We will also need to ensure this behavior is matched on Vercel on matching Next.js versions.

**Comment by dbbk** [comment]
I actually prefer the current approach, I'd want my URLs to contains `en-us` and the translation files to be `en-US`

You also don't need to redirect if you just provide canonical and optionally hreflang meta tags

**Comment by JanKaifer** [comment]
`pages` will be soon in bugfixes only, so we probably won't implement this (i18n is not supported in app-dir).
If this causes issues for you, you can redirect it yourself using middleware.
