### ISSUE TITLE
Can't access .env.local vars inside getStaticProps()

### ISSUE THREAD

**Issue by nabeards** [vercel/next.js#31068]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

According to [Use .env.local to load environment variables](https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables), I should be able to access environment variables from `.env.local` inside `getStaticProps()`. This is not working, and neither is loading the `PORT` env var from `.env.local`. All env vars defined in `.env.local` are `undefined` when accessed from `getStaticProps()`.

I created this app through the Vercel web site, which created it inside my GitLab account. I then cloned it locally to customize.

### Expected Behavior

I expect `process.env.VARNAME` to be accessible within `getStaticProps()`.

### To Reproduce

.env.local:
```
PORT=3008
KEY=value1
PASS=value2
```

index.js:
```
export async function getStaticProps() {
    console.log('any are undefined:', process.env.KEY, process.env.PASS, process.env.PORT);
};
```

**Comment by timneutkens** [comment]
The code used to test it:
```jsx
export async function getStaticProps() {
  return {
    props: {
      KEY: process.env.KEY,
      PASS: process.env.PASS,
      PORT: process.env.PORT,
    },
  };
}

export default function Home(props) {
  return <pre>{JSON.stringify(props, null, "  ")}</pre>;
}
```


`KEY=1 PASS=234 PORT=8000 yarn dev`:

Result:
```
{
  "KEY": "1",
  "PASS": "234",
  "PORT": "8000"
}
```


---

Same but with `.env.local`:

```
KEY=1
PASS=234
PORT=8000
```

Result:
```
{
  "KEY": "1",
  "PASS": "234",
  "PORT": "8000"
}
```


Seems there's something in your app given that this is working as expected. I'll convert the issue to discussions.
