### ISSUE TITLE
`next.config.js` is not considered for node_modules that import `next/image`

### ISSUE THREAD

**Issue by styfle** [vercel/next.js#31065]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

16.x

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Getting an error during `next dev` when a dependency imports `next/image`:

> Error: Invalid src prop (https://i.imgur.com/CgezKMb.jpg) on `next/image`, hostname "i.imgur.com" is not configured under images in your `next.config.js`
> See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host

### Expected Behavior

Should read the `next.config.js` properly, even for 3rd party packages inside `node_modules` that import `next/image`

### To Reproduce

https://github.com/pacocoursey/next-image-bug

**Comment by styfle** [comment]
Some additional context: this is not just relevant for 3rd party packages published to npm, but also monorepos using workspaces or private packages shared between projects.

**Comment by johnnyomair** [comment]
While investigating a similar issue (see #33228) I've found that the `next.config.js` is also not considered when using the `next/image` component in a 3rd party package in combination with the `priority` flag.

**Comment by trevorgillis** [comment]
I am having this exact issue. What's especially odd is that, when I run `next dev`, I get the error and my app doesn't load (as expected and stated in the issue). If I then, in my Next.js app, temporarily comment out the third-party code that's using next/image and reload, it loads without the error (as expected). But then, while the dev server is still running, if I uncomment the third-party code that's using next/image, it works.

It is also not an issue when I do a build and run in production mode; it only happens in development mode.

**Comment by trevorgillis** [comment]
@styfle have you found any temporary workarounds for the time being?

**Comment by JuniorTour** [comment]
A temp workaround is add `unoptimized` prop to your `next/image` usage.

But next.js won't process `unoptimized` image, be careful.

``` js
<MyCoolImage 
        unoptimized
        src="https://i.imgur.com/CgezKMb.jpg"
        width={1404}
        height={936}
      />
```

**Comment by styfle** [comment]
Theres a PR you could try out: #33559

**Comment by ambrauer** [comment]
Hi @styfle - just curious, any anticipated release milestone for this fix?

**Comment by styfle** [comment]
We'll have it for 12.1.0.

The work is being done in PR #33559
