### ISSUE TITLE
Improve `next/script` documentation

### ISSUE THREAD

**Issue by housseindjirdeh** [vercel/next.js#31062]
### Describe the feature you'd like to request

There has been feedback that the usage of [`next/script`](https://nextjs.org/docs/basic-features/script) can be difficult to understand for Next.js developers looking to optimize loading of third-party scripts. This is a multi-step proposal to improve how the Script component is explained in the documentation.

### Describe the solution you'd like

- [X] Expand the [Script Component](https://nextjs.org/docs/basic-features/script) page in the core documentation to (#31063): 
  - Include additional information on the different loading strategies available and when to use them
  - Explain other useful capabilities of `next/script` in more detail (`onLoad`, inline scripts, etc...)
- [X] Add a `next/script` page to the API reference documentation (#31063)
- [ ] Include "recipes" in the documentation to show how to use the Script component to load some of the most popular third-party scripts (GTM, Google Analytics, etc...)
- [ ] Include an example of how to use the Script component in [nextjs.org/learn](https://nextjs.org/learn)

### Describe alternatives you've considered

N/A

**Comment by lafiosca** [comment]
Along these lines I think it would be nice to have clarity on certain behaviors. For example: what happens if you are using props as values in the dangerous innerHTML for a Script component? Will it re-render and run the code again? What happens if you need multiple scripts with the same strategy to load in a specific order? Etc.

**Comment by manovotny** [comment]
The Next.js Learn course now has a [Third-Party JavaScript](https://nextjs.org/learn/basics/assets-metadata-css/third-party-javascript) section that educates on `next/script` usage. There are also several examples for `next/script` usage, including [with-google-analytics](https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics) in the Next/.js repo. 

Calling this ok for now.
