### ISSUE TITLE
The edge functions are crashing when deployed to Vercel

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#31153]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

The edge functions are crashing when deployed to Vercel

> This is the error
TypeError: (intermediate value)(intermediate value).push(...) is not a function
at Object.<anonymous>

### Expected Behavior

The edge function should redirect to the login page if the cookie is not found 

### To Reproduce

create _middleware.tsx file and add the following content.

```
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export const middleware = (req: NextRequest) => {
  const cookie = req.cookies["auth"];

  if (!cookie) {
    return NextResponse.redirect("/login");
  }
};
```

**Comment by ijjk** [comment]
Hi, do you have `swcMinify` enabled in your `next.config.js`, can you provide a related deployment URL or repo with a minimal reproduction?

**Comment by saurabhguptarock** [comment]
> Hi, do you have `swcMinify` enabled in your `next.config.js`, can you provide a related deployment URL or repo with a minimal reproduction?

yes I have swcMinify enabled

**Comment by saurabhguptarock** [comment]
> Hi, do you have `swcMinify` enabled in your `next.config.js`, can you provide a related deployment URL or repo with a minimal reproduction?

please go to https://www.clense.in and then go to /profile page

**Comment by ijjk** [comment]
Hi, this should be resolved by disabling `swcMinify` for now, we are investigating this though.

**Comment by saurabhguptarock** [comment]
> Hi, this should be resolved by disabling `swcMinify` for now, we are investigating this though.

thanks it worked for me

**Comment by wiesson** [comment]
For me as well - thanks for reporting :)

**Comment by eduardocampo** [comment]
Thanks!!

**Comment by Odas0R** [comment]
> Hi, this might be fixed in the latest version of Next.js `v12.0.10` can anyone who experienced this previously please try upgrading and re-enabling `swcMinify` to confirm?

On next `v12.0.10` I still get this error!

**Comment by balazsorban44** [comment]
@Odas0R could you create a new issue with a reproduction? Following the OP's reproduction and it does not reproduce the issue anymore: https://31153-balazsorban.vercel.app

**Comment by belgattitude** [comment]
Hey @ijjk 

> can anyone who experienced this previously please try upgrading and re-enabling swcMinify to confirm?

It works perfect. Tested with 12.0.10 (react 17) and 12.0.11-canary.15 (react 18). 

That said I had to make a redeploy without cache. Not sure if it was really linked to the switch of swcMinify (history in https://github.com/belgattitude/nextjs-monorepo-example/pull/1319)

**Comment by Odas0R** [comment]
> @Odas0R could you create a new issue with a reproduction? Following the OP's reproduction it does not reproduce the issue anymore: https://31153-balazsorban.vercel.app

Sorry for the late response. It's all working :)

Thank you!
