### ISSUE TITLE
React server components <Head/> element does not work.

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#31220]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

The Head tag in server component file throws and error saying hooks are not allowed in server components

### Expected Behavior

The Head tag should inject corresponding elements to the head of the page like SSR

### To Reproduce

Add Head tag in a server component file (ending with .server.js) and it should throw an error saying hooks are not allowed in server components.

**Comment by lachlanjc** [comment]
There's now the `head.js` file in the `app` dir for this: https://beta.nextjs.org/docs/api-reference/file-conventions/head

**Comment by leerob** [comment]
Indeed - thank you @lachlanjc!
