### ISSUE TITLE
React 18: Updated `Document` Design & Documentation

### ISSUE THREAD

**Issue by devknoll** [vercel/next.js#31225]
# Overview
`Document` today:
* Class Component
* Static `getInitialProps` (w/ `renderPage`) for 3rd party CSS-in-JS support, possibly data fetching
* Only runs on the server, for the initial page load

`Document`'s new design, in order to support Suspense + Streaming + more:
* Becomes a Server Component. As a result, must become a functional component
* Data fetching replaced via Suspense
* CSS-in-JS support replaced via [render prop](https://reactjs.org/docs/render-props.html#gatsby-focus-wrapper) pattern and [`useFlushEffect` hook](https://github.com/vercel/next.js/issues/30997)

# Details

Since `Document` only runs on the server, it's naturally a Server Component. However, Server Components are not finalized yet, and won't be until after React 18 is released. However, there's a chicken and egg problem, as we'd like to support incremental progress towards Server Components (and certainly support for Suspense + Streaming) _today_.

The solution is the _Next.js Document Server Component_, a subset of actual Server Components with additional restrictions. For example, no built-in React hooks (like `useState`) or Suspense are currently supported. This model will be supported until we can officially replace `pages/_document.js` with `pages/_document.server.js`.

The simplest Next.js Document Server Component looks like this:

```jsx
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
```

Conceptually, this is a Server Component that returns a mixed tree of Server/Client Components. There is only one hook supported, `useFlushEffect`, described below.

## Wrapping the Application

Prior to React 18, many CSS-in-JS libraries would use some global variable that they could write data into during rendering, relying on the fact that rendering would complete synchronously to avoid conflicts. With Suspense in React 18, this is no longer possible: one request could be suspended waiting on I/O, allowing another request to start or unsuspend and access that global data.

Instead, the recommendation is that such libraries use [React Context](https://reactjs.org/docs/context.html#gatsby-focus-wrapper) to scope data per request. In order to then allow such libraries to be integrated with Next.js, we add support for a render prop to the `<Main />` component:

```jsx
import { Html, Head, Main, NextScript } from 'next/document'
import MyContext from '../lib/my-context'

export default function Document() {
  return (
    <Html>
      <Head />
      <body>
        <Main>
          {children => (
            <MyContext.Provider value={...}>
              {children}
            </MyContext.Provider>
          )}
        </Main>
        <NextScript />
      </body>
    </Html>
  )
}
```

The render prop will be used to generate the tree that makes up the application content during SSR.

## Flushing Styles

Prior to React 18, many CSS-in-JS libraries would just return a script tag for you to insert into your `Document` at the end of the render. With Suspense, content is generated and flushed incrementally, so this pattern of waiting is no longer possible.

Instead, [the recommendation](https://github.com/reactwg/react-18/discussions/110) is that libraries incrementally flush styles to the stream. To streamline this (and expose the stream to 3rd party libraries), Next.js should expose a `useFlushEffect` hook:

```jsx
useFlushEffect(() => <foo />)
```

As per the recommendation, functions passed to the `useFlushEffect` hook will be called right before writing content generated by React.

# Migration Path

* Applications _without_ a custom `pages/_document`
  * No action required
* Applications _with_ a custom `pages/_document`
  * Without a `getInitialProps`
    * Convert to a functional component
  * With a `getInitialProps`
    * Determine if the CSS-in-JS library being used has released a new version with support for React 18 and guidance for integrating with Next.js.

_Note_: all existing class component `Document`s will continue working, but will not support features like streaming or suspense.

**Comment by carlosagsmendes** [comment]
@devknoll it would be great to have some info on how to access the context when the Documents are Server Components. If this is not the proper place for feedback feel free to delete the comment! Thks in advance

**Comment by devknoll** [comment]
Closing as obsolete
