### ISSUE TITLE
Next 12 middleware imported function build issue

### ISSUE THREAD

**Issue by bluetoken-luke** [vercel/next.js#31253]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

16.9.0

### What browser are you using?

chrome

### What operating system are you using?

popos

### How are you deploying your application?

ECS

### Describe the Bug

Having an issue using Next 12 and new middleware that is a bit odd.  When trying to use functions existing outside the middleware file I am running into build issues.

As an example, we are checking authentication in a route middleware.  All works well if I have the code all in line or even if I pull the code out into functions but they live within that file.

However, being that we are going to be making this check on many pages, I wanted to pull this logic into a shared file so that they could all use it.  By doing this though, I run into the issue.

Our app uses aws-amplify.  That is configured in _app.tsx.  There isn't any reference or anything to amplify in the middleware.  In fact, amplify currently doesn't work with Next 12 middleware as I have submitted to amplify here https://github.com/aws-amplify/amplify-js/issues/9145 and next here https://github.com/vercel/next.js/issues/30884.  Because of this I have gone out of my way to make sure nothing amplify related is in the middleware.  I am checking the authentication manually using jose.

So when I move the working middleware authentication check from within the middleware file and into a file elsewhere in the solution and then import it, the middleware no longer works and I actually receive the same amplify window undefined error that I received in those two issues.  It seems like by importing one file from within the solution, its trying to build all files, including _app.tsx where amplify is configured.

Not sure why this would be.  Not concerned with the amplify error.  Thats expected due to linked issues.  The problem is that amplify shouldnt be included at all just because I imported a function from elsewhere in the solution.

### Expected Behavior

The middleware would build successfully and not include anything related to amplify in _app.tsx.  The shared function could be used around the app.

### To Reproduce

In order to get this specific error you would have to be using amplify and have it configured somewhere in the app.  If you weren't using amplify and nothing else had issues with the NextJS middleware, I assume this would build and work just fine.  So to reproduce you would need a next12 app with amplify configured and attempt to use middleware that calls a function imported from a file elsewhere in the solution.

Using the function from elsewhere will cause an error due to amplify being built for some reason.  Not using an external function will work as expected.  No amplify error.

**Comment by balazsorban44** [comment]
So this is likely an issue with Amplify, which still cites Next.js 10 in their docs, even though it has been out for a while. Middleware is a Next.js 12 feature, so you should check with them about support.

Looks like your issue generates engagement here: https://github.com/aws-amplify/amplify-js/issues/9145 so keep an eye, maybe the Amplify team will pick it up and add first-class support.
