### ISSUE TITLE
Unable to use `dangerouslySetInnerHTML` and `beforeInteractive` strategy in Script component 

### ISSUE THREAD

**Issue by genetschneider** [vercel/next.js#31275]
### What version of Next.js are you using?

14.17.1

### What version of Node.js are you using?

12.0.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

npm run dev

### Describe the Bug

Setting `dangerouslySetInnerHtml` in next Script component while also specifying `beforeInteractive` strategy will result in the Script component doing nothing. Since there is no `src` specified, the src will simply be `(unknown)`.
![script](https://user-images.githubusercontent.com/19775351/141206853-62aed528-260b-46e2-9278-dbc5f8161b70.PNG)

```
<Script
  id="test"
  strategy="beforeInteractive"
  dangerouslySetInnerHTML={{
    // will not run
    __html: `console.log('hello!')`,
  }}
/>
```

### Expected Behavior

Script component can be used with no `src` while using `dangerouslySetInnerHtml` property. 

### To Reproduce

Try to render Script component using `beforeInteractive` while having no `url` and specifying `dangerouslySetInnerHtml` property.

```
<Script
  id="test"
  strategy="beforeInteractive"
  dangerouslySetInnerHTML={{
    // will not run
    __html: `console.log('hello!')`,
  }}
/>
```
This piece of code of next Script will result in the following script tag being added
![script](https://user-images.githubusercontent.com/19775351/141207463-f8d3f16d-44bd-4dae-806e-7fc3f2980ceb.PNG)

**Comment by studiosi** [comment]
Has anyone found a workaround for this?

**Comment by ijjk** [comment]
Hi, this has bee updated in the latest version of Next.js `v12.1.6`, specifically https://github.com/vercel/next.js/pull/36364, please updated and give it a try!

**Comment by alexanderdemchik** [comment]
> Hi, this has bee updated in the latest version of Next.js `v12.1.6`, specifically #36364, please updated and give it a try!

Hi, checked it today. Seems it's still not working with v12.1.6.
Added console log to script:
![image](https://user-images.githubusercontent.com/27238321/168115760-d2f0351a-cd68-4af6-9499-33ac0e0b53ab.png)

And there is nothing in logs:
![image](https://user-images.githubusercontent.com/27238321/168115644-ebc73cdf-fd80-4183-9d72-6b7548200550.png)
![image](https://user-images.githubusercontent.com/27238321/168116825-2e698241-3597-46e0-b98c-f1a553bf44ea.png)

Browser - Chrome 101.0.4951.64

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.7-canary.8` of Next.js, please update and give it a try!

**Comment by Chastrlove** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/17813559/169231094-e00e8fa3-03f8-4ea6-86af-45833672978b.png">
Still break; the script has unknow src , and the inline script dont execute @ijjk  @housseindjirdeh

**Comment by Chastrlove** [comment]
the "scriptProps" should omit src
https://github.com/vercel/next.js/blob/canary/packages/next/pages/_document.tsx#L558
https://github.com/vercel/next.js/blob/5acf9db617747389c7c2ff7eeafa7492086f01f9/packages/next/client/script.tsx#L172
updateScripts always post it  @ijjk
