### ISSUE TITLE
React 18: Separate `concurrentFeatures` and `runtime` options

### ISSUE THREAD

**Issue by devknoll** [vercel/next.js#31317]
- [x] ~~Add the global experimental `runtime` flag to switch the default runtime. If `runtime` is set, we enable Fizz for all pages. It works similar to the `concurrentFeatures` flag. If `runtime` is missing, Fizz will not be enabled.~~
  - [x] ~~Add support for `nodejs` runtime. (@shuding)~~
- [x] ~~Remove `concurrentFeatures` from the config but keep it internal. It will be disabled for now.~~
- [x] Add per-page `runtime` flag to enable Fizz for specific pages. The global `runtime` will now not affect all pages.
  - [x] Pre-parse each page before any compilation happens to collect page configurations. (@huozhi)
  - [x] Generate entries for each compilers based on page and global runtimes. (@shuding)
- [ ] Allow the global `runtime` to be unset. (@shuding)

**Comment by jlarmstrongiv** [comment]
Separating the concurrent and runtime features would be great, as it’s trivial to hit the 1MB limit of the vercel edge runtime https://github.com/vercel/next.js/issues/32907 and break your app

**Comment by wvanrensselaer** [comment]
Heyo, this is an awesome feature, thanks. Just want to flag this here since we are experimenting with Relay + SSR Suspense: https://github.com/vercel/next.js/discussions/32502
