### ISSUE TITLE
良心云 服务器 2核4g8m，198元/3年

### ISSUE THREAD

**Issue by aliyun11** [vercel/next.js#31326]
### What version of Next.js are you using?

https://curl.qcloud.com/AfDope6j

### What version of Node.js are you using?

https://curl.qcloud.com/AfDope6j

### What browser are you using?

https://curl.qcloud.com/AfDope6j

### What operating system are you using?

https://curl.qcloud.com/AfDope6j

### How are you deploying your application?

https://curl.qcloud.com/AfDope6j

### Describe the Bug

https://curl.qcloud.com/AfDope6j
良心云，重新注册个qq就是新用户了
![image](https://user-images.githubusercontent.com/93562479/141396588-fb3f7181-a75f-4118-bc08-46eed43dc429.png)

### Expected Behavior

https://curl.qcloud.com/AfDope6j
良心云，重新注册个qq就是新用户了
![image](https://user-images.githubusercontent.com/93562479/141396588-fb3f7181-a75f-4118-bc08-46eed43dc429.png)

### To Reproduce

https://curl.qcloud.com/AfDope6j
良心云，重新注册个qq就是新用户了
![image](https://user-images.githubusercontent.com/93562479/141396588-fb3f7181-a75f-4118-bc08-46eed43dc429.png)

**Comment by ahwgs** [comment]
丢人

**Comment by Nicenonecb** [comment]
> 丢人

脸都不要了

**Comment by Akitaqaq** [comment]
绝了
