### ISSUE TITLE
/_next paths are being sent to _middleware.ts in dynamic routes

### ISSUE THREAD

**Issue by jordie23** [vercel/next.js#31324]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

The documentation here states:

> Middleware runs directly after redirects and headers, before the first filesystem lookup. **This excludes /_next files.**

https://nextjs.org/docs/middleware

However when I have `/pages/[slug]/_middleware.ts` I can see requests for /_next files.

This does not happen for  `/pages/_middleware.ts`, only for the dynamic route.

I have only tested this using `npm run dev`

### Expected Behavior

There should be no requests for /_next files passed to middleware.

OR

Documentation should be updated to state /_next files will be passed to middleware in this case.

### To Reproduce

Create `pages/[slug]/_middleware.ts` with something like: 

```javascript
import { NextRequest, NextResponse } from 'next/server'

export function middleware(req: NextRequest) {
  console.log('request for', req?.nextUrl.toString())
  return NextResponse.next()
}
```

Run the dev server. When you access a page, you'll see something like this in the server logs:

```
request for /_next/static/chunks/webpack.js?ts=1636680995645
request for /_next/static/chunks/react-refresh.js?ts=1636680995645
request for /_next/static/chunks/pages/index.js?ts=1636680995645
request for /_next/static/development/_buildManifest.js?ts=1636680995645
request for /_next/static/development/_ssgManifest.js?ts=1636680995645
request for /_next/static/development/_middlewareManifest.js?ts=1636680995645
```

**Comment by jonahallibone** [comment]
Any update on this?
