### ISSUE TITLE
Fast Refresh does not compile automatically after saving a change in `pages/index.js`

### ISSUE THREAD

**Issue by ysmike** [vercel/next.js#31355]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.15.0

### What browser are you using?

95.0.4638.69 (Official Build) (arm64)

### What operating system are you using?

macOS Monterey 12.0.1

### How are you deploying your application?

next dev

### Describe the Bug

After creating a project using `yarn create next-app` and running the app using with `yarn dev`, I'm able to see the contents of `pages/index.js` in `http://localhost:3000/`.

However, when I change some text and save the `pages/index.js` file, I see neither the `event - compiling ...` logging in the terminal nor the changed text being reflected in `http://localhost:3000/`. Refreshing the page or clearing cache on the page doesn't trigger the change. The only way to see the change that I've found so far is to kill the server and restart manually. 

I've tried other package installers, different versions of `node` and `next.js`, various browsers, and on both Intel-chip and Apple-chip laptops only to face the same issue. I'm probably doing something wrong here and I need help getting unstuck. Any help?

> 

### Expected Behavior

The text changed and saved in the `index.js` file should be reflected in `localhost` without having to manually restart the server.

### To Reproduce

- create a project using `yarn create next-app` 
- cd into the directory of the created project
- run the app using with `yarn dev`
- change text in `pages/index.js` and save file
- observe that the change is not reflected in `localhost`

**Comment by timneutkens** [comment]
Maybe you have a leftover service worker?
