### ISSUE TITLE
Build Cache with Webpack 5 and PostCSS-PurgeCSS

### ISSUE THREAD

**Issue by toviszsolt** [vercel/next.js#31441]
### What version of Next.js are you using?

11 and 12 (only with Webpack 5)

### What version of Node.js are you using?

14 and 16

### What browser are you using?

does not matter

### What operating system are you using?

Windows 10

### How are you deploying your application?

SSG and/or Vercel Deploy via GitHub

### Describe the Bug

**The issue only occurs with Webpack 5. With Webpack 4 everything is fine.**

- Using external CSS library from `node_modules` with `@fullhuman/postcss-purgecss` PostCSS plugin.
- `PostCSS` and `PurgeCSS` work well.
- After the first `next build`, the purged CSS files are cached during the build.
- If I do not modify the CSS source files, BUT change any class name in any component, the build cache is not updated.

**Example:**
- CSS library contains the following CSS selectors: `color-red`, `color-blue`, `color-green`
- Set `color-red` class name on a html tag.
- **!!** On `next build` won't purge `color-red` and will be cached
- **!!** On `next build` will be purge `color-blue`, `color-green` and won't be cached
- Change the class name of the html tag from `color-red` to `color-blue`
- After `next build` the `color-blue` selector doesn't exists in css files

### Expected Behavior

Cache is always good, but should resolve that cache is updated when needed with Webpack 5.

### To Reproduce

**The issue only occurs with Webpack 5. With Webpack 4 everything is fine.** See Example above.

**Comment by varenya** [comment]
I am looking into this one.

**Comment by varenya** [comment]
I tried to reproduce using the following config https://purgecss.com/guides/next.html#customize-postcss-configuration-next-js-9-3 but its working as expected.

Can you please provide an example as per the instructions :

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by toviszsolt** [comment]
Sorry I have very little time, December and January are a madhouse in the business world.
Now I'm working on a regular CRA project and a problem has come up, I think the cause of the problem will be similar.

- Webpack creates css files with a hash in the filename ( looks to be CRC hash).
- If any postbuild script modifies the css file, the hash is not changed.
- Since the hash is not changed the browser cache will serve the old css file.
- In PWA projects with an Offline First strategy, it is almost impossible to update the browser cache.

**Comment by varenya** [comment]
Looks like this is an issue with `Webpack 5` instead of `next`. Perhaps raising it there would make sense.

**Comment by toviszsolt** [comment]
If you think about it, I think you will find that the problem is not with Webpack, and I would call this an anomaly.
So, there doesn't seem to be a problem with either Webpack or Next, but there is an anomaly on top of the stack.
Finally, let's close that issue. I will look into the anomaly one day when I have more time.
