### ISSUE TITLE
TypeError: Class constructor n cannot be invoked without 'new'

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#31501]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

TypeError: Class constructor n cannot be invoked without 'new'

### Expected Behavior

The component should render perfectly

### To Reproduce

Enable concurrentFeatures and add a file ending with .server.tsx
Add ErrorComponent wrapper to Suspense

ErrorComponent.tsx
```
import React from "react";

class ErrorBoundary extends React.Component {
  state = { hasError: false, error: null };

  static getDerivedStateFromError(error) {
    return {
      hasError: true,
      error,
    };
  }

  componentDidCatch(error, errorInfo) {
    console.log(error, errorInfo);
  }

  render() {
    if (this.state.hasError) {
      return (
        <div>
          Application Error: Please see console for more information -{" "}
          {this.state.error}
        </div>
      );
    }
    return this.props.children;
  }
}

export default ErrorBoundary;
```

**Comment by ljosberinn** [comment]
Please provide a reproduction.

**Comment by saurabhguptarock** [comment]
> Please provide a reproduction.

Added proper reproduction

**Comment by ljosberinn** [comment]
Could you share how you passed the component to Suspense via the fallback property, in code?

**Comment by saurabhguptarock** [comment]
> Could you share how you passed the component to Suspense via the fallback property, in code?

<Suspense loader={<Loading />}>
        <CouponItem />
  </Suspense>

**Comment by ljosberinn** [comment]
Could reproduce this. The error is thrown [here](https://github.com/vercel/next.js/blob/canary/packages/next/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-writer.browser.development.server.js#L223) which - given its style - looks like a compiled/fork of [React Flight](https://github.com/facebook/react/blob/75f3ddebfa0d9885ce8df42571cf0c09ad6c0a3b/packages/react-server/src/ReactFlightServer.js#L147). They simply don't seem to have added support for class components to server components.

As such, it's not a Next.js issue.

**Comment by saurabhguptarock** [comment]
> Could reproduce this. The error is thrown [here](https://github.com/vercel/next.js/blob/canary/packages/next/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-writer.browser.development.server.js#L223) which - given its style - looks like a compiled/fork of [React Flight](https://github.com/facebook/react/blob/75f3ddebfa0d9885ce8df42571cf0c09ad6c0a3b/packages/react-server/src/ReactFlightServer.js#L147). They simply don't seem to have added support for class components to server components.
> 
> As such, it's not a Next.js issue.

ok thanks

**Comment by okaforcj** [comment]
@saurabhguptarock did you eventually get around to this, what did you do ?

**Comment by saurabhguptarock** [comment]
> @saurabhguptarock did you eventually get around to this, what did you do ?

No still the same error. I just commented ErrorBoundary component.

**Comment by huozhi** [comment]
Class components are not supported in react server components
