### ISSUE TITLE
Middleware NextResponse.rewrite() crashes on colons in paths

### ISSUE THREAD

**Issue by klarstrup** [vercel/next.js#31523]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.10.0

### What browser are you using?

Chrome 95

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Using `NextResponse.rewrite("/:blahblah")` in a middleware to navigate to a path with a colon in it causes an obtuse `TypeError: Expected "blahblah" to be a string` style error(ultimately coming from `path-to-regexp`).

### Expected Behavior

Rewriting to a path with a colon in it to simply work without any unexpected replacement being attempted internally.

### To Reproduce

something like this in any middleware

```js
import { NextResponse } from "next/server";

export default function middleware() {
  return NextResponse.rewrite("/not-a:param");
}
```

repro repo here: https://github.com/klarstrup/next-middleware-rewrite-bug

**Comment by Schniz** [comment]
🤩
