### ISSUE TITLE
Inconsistent behaviour of `request.nextUrl.href`

### ISSUE THREAD

**Issue by jonlambert** [vercel/next.js#31533]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

I'm attempting to use Middleware to force a default locale in my application URLs, using [example code from the documentation](https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale).

This worked when accessing the application through `localhost`, but when accessing using any other hostname, `request.nextUrl.href` contains the full URL. I'm not sure whether this is expected behaviour, but it seems like it could be a bug as this breaks the example code provided in the documentation.

### Expected Behavior

For `request.nextUrl.href` to behave consistently. Either return the full URL, or the application path. Ideally the latter, as the example indicates this would be expected behaviour.

### To Reproduce

Take this simple middleware:

```ts
import type { NextFetchEvent, NextRequest } from 'next/server'

export function middleware(request: NextRequest, event: NextFetchEvent) {
  return new Response(request.nextUrl.href)
}
```

`curl` the app using localhost, see the following:

```
$ curl http://localhost:3000/hello
/hello
```

But when using any other IP or hostname:

```
$ curl http://127.0.0.1:3000/hello
https://127.0.0.1:3000/hello
```

**Comment by marcoacierno** [comment]
This doesn't seem to be fixed @Kikobeats? I am using next@12.0.7 and on Vercel `req.nextUrl.href` seems to be an absolute URL while it is a relative URL on Localhost

I am using: https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale

```typescript

export function middleware(req: NextRequest, _ev: NextFetchEvent) {
  const shouldHandleLocale =
    !PUBLIC_FILE.test(req.nextUrl.pathname) &&
    !req.nextUrl.pathname.includes("/api/") &&
    req.nextUrl.locale === "default";
  const locale = getLocale(req.cookies.pyconLocale);

  console.log("req.nextUrl.href =>", req.nextUrl.href)
  return shouldHandleLocale
    ? NextResponse.redirect(`/${locale}${req.nextUrl.href}`)
    : undefined;
}

const getLocale = (cookie: string): string => {
  if (cookie && VALID_LOCALES.findIndex((e) => e === cookie) !== -1) {
    return cookie;
  }

  return DEFAULT_LOCALE;
};
```

Going to https://pycon-git-web-167-use-nextjs-intl-system-python-italia.vercel.app/ redirects to`https://pycon-git-web-167-use-nextjs-intl-system-python-italia.vercel.app/enhttps:/pycon-git-web-167-use-nextjs-intl-system-python-italia.vercel.app/default`

This is the code:

- https://github.com/pythonitalia/pycon/pull/2525/files#diff-e064de65d4610383e665a32e7e32ee1f520c466a6a63ecea8925ff8337f08215R21
- https://github.com/pythonitalia/pycon/pull/2525/files#diff-7a57dd0b93a2d5540e0693d3b430820e5460baf6b79872471e25cc41811ef90cR8

More:

```
  ~/projects/pycon/backend on   WEB-167-use-nextjs-intl-system *12 !4 ❯ curl -I https://pycon-git-web-167-use-nextjs-intl-system-python-italia.vercel.app/
HTTP/2 302
date: Sun, 05 Dec 2021 13:02:41 GMT
content-type: text/plain
x-robots-tag: noindex
location: /enhttps:/pycon-git-web-167-use-nextjs-intl-system-python-italia.vercel.app/default
server: Vercel
x-vercel-id: fra1::mjftx-1638709361021-e0c75daacf94
strict-transport-security: max-age=63072000; includeSubDomains; preload
cache-control: public, max-age=0, must-revalidate
x-vercel-cache: MISS
```

**Comment by ChuckJonas** [comment]
I think it might be related, but I'm seeing that `req.nextUrl.hostname` is an empty string...

**Comment by ndavidson-manticore** [comment]
I agree that this issue is not closed out and was wrongly marked as such. I am still having inconsistent behavior with the request nextUrl object and even the request.url string.

**Comment by arlyon** [comment]
When accessing site using localhost `req.nextUrl` is empty string for all fields, however when accessing using `127.0.0.1`, `req.nextUrl` has the correct fields but protcol `https`.
