### ISSUE TITLE
Custom error page `_error.js` crashes only in Vercel if getInitialProps is defined

### ISSUE THREAD

**Issue by shivangg** [vercel/next.js#31594]
### What example does this report relate to?

with-sentry

### What version of Next.js are you using?

11.1.2, 12.0.4

### What version of Node.js are you using?

14.18

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Vercel Serverless function crashes when error thrown in SSR. 

Also, this deviates from its behaviour when running locally with `yarn build && yarn start`.

### Expected Behavior

Should match the behaviour when run locally with `yarn build && yarn start`. 

Should render the custom error page and not crash.

### To Reproduce

Use the with-sentry example.

Also can be seen https://with-sentry-app.vercel.app/.

Test 1, Test 2, Test 3 - all of these crash the Vercel Serverless function.

![image](https://user-images.githubusercontent.com/10586637/142554426-b82c803a-ba10-40fe-8399-e11c1ddd1fc9.png)

**Comment by shivangg** [comment]
@timneutkens Can you confirm if this is a known issue with Vercel?

**Comment by ijjk** [comment]
Hi, this is currently the expected behavior due to how serverless functions need to be exited. To customize the error page `pages/500` should be used as documented here https://nextjs.org/docs/advanced-features/custom-error-page#500-page
