### ISSUE TITLE
next/image, randomly responding 503 for images hosted on firebase-storage in production

### ISSUE THREAD

**Issue by coolbeatz71** [vercel/next.js#31610]
### What version of Next.js are you using?

12.0.3

### What version of Node.js are you using?

14.5.1

### What browser are you using?

chrome, firefox

### What operating system are you using?

linux/ubuntu

### How are you deploying your application?

next start

### Describe the Bug

my app is deployed to GCP. And I'm using the next/image to optimize my image loading as follow:

```
import Img from 'next/image';
.
.
.

<Img
       priority
       quality={25}
       alt="avatar"
       width="100%"
       height="100%"
       src={data.logo}
/>
```
Here is how my next.config looks like:

```
const withPlugins = require("next-compose-plugins");

const nextConfig = {
  images: {
    domains: ["firebasestorage.googleapis.com"],
  },
};

module.exports = withPlugins(
  nextConfig,
);

```

My npm script looks like:
```
    "build": "next build",
    "start": "next start -p $PORT",
```

Locally I am successfully getting my images, but in the production sometimes I get 503 services unavailable

![image](https://user-images.githubusercontent.com/25999336/142626896-b304bf2f-dc05-4cc1-85cd-fc149d0caea1.png)
![image](https://user-images.githubusercontent.com/25999336/142626980-36fc0766-f63e-4812-a1d3-aa5f328418e3.png)

### Expected Behavior

I am expecting to display the image, not randomly failing.

### To Reproduce

N/A

**Comment by coolbeatz71** [comment]
Hey, @kara any thought on why I'm seeing this?

**Comment by whyDontI** [comment]
I am having the same problem on GCP AppEngine (standard env) with custom domains.
Can see the images in local build and dev.

**Comment by coolbeatz71** [comment]
> I am having the same problem on GCP AppEngine (standard env) with custom domains. Can see the images in local build and dev.

Hey @whyDontI on my side, I just set priority to `false` and It's started working, though the images take some time to fully load

**Comment by whyDontI** [comment]
`Priority false` where?
Can you put some details?

**Comment by coolbeatz71** [comment]
> import Img from 'next/image';
> .
> .
> .
> 
> <Img
>        priority
>        quality={25}
>        alt="avatar"
>        width="100%"
>        height="100%"
```
import Img from 'next/image';
.
.
.

<Img
       priority={false} ----> this
       quality={25}
       alt="avatar"
       width="100%"
       height="100%"
/>
     ```

**Comment by styfle** [comment]
Are you still seeing this behavior with the latest Next.js version?

If so, can you provide the value of the `src` prop that you're passing to the image component?

**Comment by coolbeatz71** [comment]
> Are you still seeing this behavior with the latest Next.js version?
> 
> If so, can you provide the value of the `src` prop that you're passing to the image component?

Hey, @styfle I m no longer getting this error, after disabling the `priority`.
