### ISSUE TITLE
Middleware does not run when concurrentFeatures is enabled

### ISSUE THREAD

**Issue by saurabhguptarock** [vercel/next.js#31654]
### What version of Next.js are you using?

12.0.5-canary.5

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Middleware does not run and redirects user.

### Expected Behavior

Middleware should redirect to login page

### To Reproduce
```
module.exports = {
  images: {
    deviceSizes: [640],
    domains: ["avatars.dicebear.com"],
    formats: ["image/avif", "image/webp"],
  },
  createRoot: true,
  swcMinify: false,
  experimental: {
    reactRoot: true,
    concurrentFeatures: true,
    serverComponents: true,
  },
};
```
_middleware.tsx
```
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export const middleware = (req: NextRequest) => {
  const cookie = req.cookies["auth"];

  if (!cookie) {
    return NextResponse.redirect("/login");
  }
};
```

**Comment by shuding** [comment]
Duplicate of #31803, will track there.
