### ISSUE TITLE
change default _next in request path into something custom

### ISSUE THREAD

**Issue by iljamulders** [vercel/next.js#31718]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

12.22.7 / 14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Local & Docker container

### Describe the Bug

The following no longer works in Next.js 12 in combination with [i18n](https://nextjs.org/docs/advanced-features/i18n-routing)
Requests for static assets return a 404.

```js
module.exports = {
  assetPrefix: '/docs',
  rewrites() {
    return [
      { source: '/docs/_next/:path*', destination: '/_next/:path*' }
    ]
  }
}
```

_Originally posted by @timneutkens in https://github.com/vercel/next.js/issues/5602#issuecomment-673382891_

### Expected Behavior

changes default _next in request path into something custom

### To Reproduce

`$ yarn create next-app --typescript`

_next.config.js_
```js
/** @type {import('next').NextConfig} */
module.exports = {
  reactStrictMode: true,
  i18n: {
    locales: ['nl', 'de'],
    defaultLocale: 'nl'
  },
  assetPrefix: '/docs',
  rewrites() {
    return [
      { source: '/docs/_next/:path*', destination: '/_next/:path*' }
    ]
  }
}
```

`$ yarn build`
`$ yarn start`

Go to [http://localhost:3000/](http://localhost:3000/), static assets are not loaded

**Comment by nmaddp1995** [comment]
Do you have any workaround for that

**Comment by jholster** [comment]
We have a similar need. There are server stacks where internally urls are routed to specific micro-service by using certain url prefix, requiring fully-customizable paths in web application framework.

**Comment by federico-moretti** [comment]
I have also this problem with the following config.

```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  assetPrefix: "/custom",
  async rewrites() {
    return [
      { source: "/custom/_next/:path*", destination: "/_next/:path*" },
      { source: "/custom/api/:path*", destination: "/api/:path*" }
    ];
  },
  i18n: { locales: ["en", "it"], defaultLocale: "en" }
};

module.exports = nextConfig;
```

Does `basePath` also change `api` urls? If it only changes static files I could always use a rewrite for `api` and `basePath` for static files, right?

**Comment by MarsArbiter** [comment]
+1

**Comment by MarsArbiter** [comment]
> 

we want to integration the next page  in android. but the underscore cause the assets loading run into error.
maybe i found the way.  https://stackoverflow.com/questions/59158942/make-android-copy-all-from-next-asset-folder-via-aaptoptions
but i still want next can provide this capability

**Comment by oliviertassinari** [comment]
> It seems like basePath would be more fitting here and doesn't require the additional rewrites be configured.

It doesn't work for us https://github.com/mui/mui-toolpad/issues/660 because it also rewrites the links https://nextjs.org/docs/api-reference/next.config.js/basepath#links.

**Comment by ijjk** [comment]
I see, this sounds similar to https://github.com/vercel/next.js/issues/34371#issuecomment-1151118717 and the shared snippet should allow rewriting correctly with `beforeFiles` rewrites.

**Comment by tom-bart** [comment]
Is there any update on this feature? Currently it is impossible to host more than one Next App on one domain as the webpack-hmr (WebPack Hot Module Replacement) calls will always hit /_next/data.

The assetPrefix is not a solution as it only changes the assets, not the post-load webpack-hmr ajax calls. 

Without this feature NextJS is not suitable for enterprise solutions, just for small microsites. 

Any idea when this feature will be available?

**Comment by hmacafee** [comment]
Setting a `basePath` also breaks parallel routes in the app router currently. I would love to know of a workaround if anyone has found it.

**Comment by willfolsom** [comment]
@hmacafee Your mileage may vary, but I got something working: https://github.com/vercel/next.js/discussions/45422#discussioncomment-7593569

**Comment by jitendra-koodo** [comment]
+1

**Comment by csdiehl** [comment]
I also need this feature. Some static site hosting services ignore any directories with an underscore in the name. On GH pages you can bypass this by simply adding a `.nojekyll` file to your build. But for the CMS I'm working with now, I need to be able to rename the folder to something custom to get rid of the underscore. 

Astro provides this functionality in its config. 

thanks for considering

**Comment by solendil** [comment]
Hello,
Same problem with Cloudflare R2 https://community.cloudflare.com/t/r2-keys-with-multiple-slashes-in-key-require-url-encoding-or-it-404s/641375 : having an underscore in the object path doesn't work. I understand part of the problem is on the Cloudflare side, but part of the problem is also having such a hard-coded requirement, when so many people are begging for a change...

**Comment by timneutkens** [comment]
To answer the original issue, they forgot to add `locale: false` to the rewrite when adding the i18n config.

As said before we're not planning to add additional configuration for the filesystem path.
