### ISSUE TITLE
Redesign the cookies API for NextResponse

### ISSUE THREAD

**Issue by Kikobeats** [vercel/next.js#31719]
Right now [`NextResponse`](https://github.com/vercel/next.js/blob/canary/packages/next/server/web/spec-extension/response.ts) is exposing some public methods for handling cookies:

- clearCookie
- cookie
- cookies

Although they are doing the job, they feel like hard to know they exist or what they do outside the class.

### Describe the solution you'd like

I think cookies methods can be accommodated in a better way.

My proposal is to interact with cookies in a very similar way to a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) instance.

So rather than have some public methods, `NextResponse` just has a `cookie` instance with all cookies methods related living as instance methods,  such as:

- cookie.set (instead of cookie)
- cookie.delete (instead of clearCookie)
- cookie.getAll (instead of cookies)

Also, this way expose a better surface for adding more methods in the future, like:

- cookie.get
- cookie.clear
- cookie.has
- etc

### Describe alternatives you've considered

Internally, it could be implemented using a map instance and just exposing the methods we want to expose.

**Comment by anthonyalayo** [comment]
Would this redesign extend to `NextApiResponse` as well? For example, having your API clear the cookie on /auth/logout?
