### ISSUE TITLE
On the middleware static asset is recognized as a page

### ISSUE THREAD

**Issue by SergeyZubatkin** [vercel/next.js#31721]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

local

### Describe the Bug

When placing middleware file at the root of pages folder (pages/_middleware.ts). it will be called for every single request. Also this includes static assets.
During middleware execution for static asset request page property shown like it is page request for other page from our app:
 
```json
{
    "page": {
        "name": "/[segment]/[[...path]]",
        "params": {
            "segment": "sc_logo.svg"
        }
    },
    "url": {
        "href": "/sc_logo.svg",
        "pathname": "/sc_logo.svg"
    }
}
```

No ability to distinguish static asset with real page request.

### Expected Behavior

Flag indicating current request is for static asset, page property should display correct information about mapped page 

### To Reproduce

Request any static asset from public folder

**Comment by arthurfiorette** [comment]
I'm using a global middleware to redirect unauthenticated users to the login page. But requests for static files are falling into middleware too.

I think adding a property like `req.publicAsset` as a boolean should do the trick.
