### ISSUE TITLE
AMP Components broke in NextJS 12

### ISSUE THREAD

**Issue by MistaPidaus** [vercel/next.js#31735]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

v14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

We're upgrading our project to NextJS version 12 (12.0.4) from version `10.2.2`  and noticed that AMP components are broke - missing or not display correctly in preview and production environment. It was working fine on version `10.2.2`. We're using SSR for our AMP pages. The issue impact most of our visitors/users. 

As a temporary solution, I had to manually import as per [NextJS AMP - Adding components](https://nextjs.org/docs/advanced-features/amp-support/adding-amp-components) docs which is quite opposite of what the docs say - that NextJS will automatically import the component without manually doing it.

### Expected Behavior

It should work the same as previous version. 

### To Reproduce

Reproduce on CSB: 

### Version 10.2.2:
CSB: https://codesandbox.io/s/amp-v10-xze6p
Production: https://csb-xze6p.vercel.app/about
Observation: See that the AMP components working as expected

### Version 12.0.4:
CSB: https://codesandbox.io/s/amp-v12-0yyj0
Production: https://csb-0yyj0.vercel.app/about
Observation: Notice that the `amp-social-share` (facebook) and `amp-youtube` are missing / not displaying as expected

However when I added the AMP components manually via `<script>` from AMP Documentation, it works. 

### Version 12.0.4 with AMP `<script>`:
CSB: https://codesandbox.io/s/amp-components-v12-e6uzi
Production: https://csb-e6uzi.vercel.app/about
Observation: it works when manually import / add AMP components using `<script>` per [NextJS AMP - Adding components](https://nextjs.org/docs/advanced-features/amp-support/adding-amp-components)  docs - which not requires to do it unless want a specific version of AMP component if I understand correctly.

**Comment by thiagoenge** [comment]
Im facing the same issue. If we import the scripts manually the lighthouse report says that request is duplicated

**Comment by thiagoenge** [comment]
After some investigation, i realized that nextjs on v12 is not run AMP Optimizer, when i pass an url builded in this version on AMP page experience tool one of the issues is that AMP optimizer is not present. If i deployed the same page on v11 this issue  disapear.

**Comment by MistaPidaus** [comment]
I've tried reproducing the issue with the latest Next.js version (v13.0.6) and confirmed the issue is already fixed. 

CSB: https://codesandbox.io/s/amp-v13-bohonp
Production: https://csb-bohonp.vercel.app/about

The AMP component (`amp-youtube`) displays as expected. 

Thanks!
