### ISSUE TITLE
Link does not automatically prefetch pages for routes with "has" rewrites

### ISSUE THREAD

**Issue by ericmatthys** [vercel/next.js#31740]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14x

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

A visible `Link` will automatically prefetch page json for static pages (along with the chunk) when visible. However, if a rewrite is used to add something like a country code to the route, then the Link will no longer prefetch.

### Expected Behavior

Links can prefetch routes with or without a rewrite.

### To Reproduce

I've created a minimal case here: https://github.com/ericmatthys/nextjs-prefetch-with-rewrite
It is deployed here: https://nextjs-prefetch-with-rewrite.vercel.app/

If you look at network requests as you browse through the two different paths, you'll see the "Without Rewrite" path is able to prefetch and navigate through the path quicker. The "With Rewrite" path does not prefetch.

**Comment by ericmatthys** [comment]
I've noticed that this only happens when deployed to Vercel. `yarn build / yarn start` works as expected.

**Comment by ijjk** [comment]
This appears to be due to the `rewrite` using `has` when on Vercel but not locally so might be a potential duplicate of https://github.com/vercel/next.js/issues/24798

**Comment by ericmatthys** [comment]
You're right it does happen with the `has` rewrite and the local server. I've updated the example to always have a `has` rewrite.

**Comment by balazsorban44** [comment]
If this is a duplicate, are you OK with closing this in favour of #24798?

**Comment by ericmatthys** [comment]
I think there are at least 3 issues that are all probably closely related, although I haven't experienced a 404 error like #23798 suggests.

#31740 (this one - prefetch breaking with header rewrite)
#26145 (`fallback: true` leading to router error with header rewrite; this is older and I haven't re-tested recently)
#23798 (not sure how exactly to repro the 404 error)

Definitely feel free to merge them as you think fits best.

**Comment by ericmatthys** [comment]
It's best to use middleware for this sort of rewrite now, which avoids the issue.
