### ISSUE TITLE
when SwcMinify true , firestore(firebase) cannot getting data on build and serve

### ISSUE THREAD

**Issue by adyfk** [vercel/next.js#31753]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.13.0

### What browser are you using?

chrome 

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

i tried create next app , and set config next with swcMinify: true

when I use firebase-firestore to fetch data while dev is running smoothly.

but when i do build the result from firestore can be undefined

### Expected Behavior

should result from build and dev produce the same

### To Reproduce

```jsx
import { useEffect } from "react";
import Link from "next/link";
import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore, getDoc, doc } from "@firebase/firestore";

const app = !getApps().length
  ? initializeApp({})
  : getApp();
const store = getFirestore(app);

export default function IndexPage() {
  const testRequest = async () => {
    try {
      // if run with dev will run fine and will get result from firestore
      // if run with build and start , it will only get undefined
      const result = await getDoc(doc(store, "users", "testid"));
      console.log("test result", { docSnap: result.data() });
    } catch (error) {
      console.log(error)
    }
  };

  useEffect(() => {
    testRequest();
  }, []);

  return (
    <div>
      Hello World.{" "}
      <Link href="/about">
        <a>About</a>
      </Link>
    </div>
  );
}
```

```js
//next-config.js
const config = {
  swcMinify:true
};
module.exports = config;
```

sample when i run dev
![Screen Shot 2021-11-23 at 12 40 12](https://user-images.githubusercontent.com/37971908/143162450-40646152-3a5b-4074-8f9e-7d70d5cb08f7.png)

sample when i run build start
![Screen Shot 2021-11-23 at 12 39 47](https://user-images.githubusercontent.com/37971908/143162493-0e0508ec-e421-4ef4-b324-c0d38d5c6944.png)

**Comment by Aliemeka** [comment]
@timneutkens can you check this out too? Seems to be another `swcMinify` issue. Does the `next@canary` release address this as well?

**Comment by michaldev** [comment]
I also have a problem with swcManify when I try use getDoc method from firebase in useEffect hook. When I disable swcManify everything is ok.

**Comment by timneutkens** [comment]
I'm assuming this is a similar issue to #31391 🤔 We've made some improvements for that issue so could you try canary as well: https://github.com/vercel/next.js/issues/31391#issuecomment-1000275551

**Comment by NicholasChoong** [comment]
I have tried the canary but the same issue is still occurring.

**Comment by balazsorban44** [comment]
Hi, we recently fixed some bugs in the minifier, and this has been resolved on `canary`.

You can upgrade to at least `12.0.9-canary.4` or wait for it to be released to `latest`
