### ISSUE TITLE
Build stuck indefinitely in Next.js 12 with ioredis-mock package

### ISSUE THREAD

**Issue by blenderskool** [vercel/next.js#31859]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

Vercel

### Describe the Bug

When using the [ioredis-mock](https://github.com/stipsan/ioredis-mock) package and running `next build`, the command gets stuck indefinitely at
`Creating an optimized production build...`

This also happens on `next@canary`. Not on Next.js 11.
At first, I thought it was the new SWC compiler, but disabling it(using a basic `.babelrc` file) had no effect.

I have also opened an issue in the ioredis-mock repository at https://github.com/stipsan/ioredis-mock/issues/1103 which goes over a peculiar fix in the package that seemed to have fixed it, not exactly sure what caused it to work though.

### Expected Behavior

The `next build` command executes successfully when using ioredis-mock package with Next.js 12

### To Reproduce

1. Create a new Next.js 12 project using `create-next-app`
2. Install `ioredis-mock` and `ioredis` package.
3. Create a `lib/redis.js` file with following content:
```js
import Redis from 'ioredis-mock';
const client = new Redis();
export default client;
```
4. Update the `pages/api/hello.js` file:
```js
import redis from '../../lib/redis';
export default async (req, res) => {
  const val = await redis.incr('test');
  res.status(200).json({ val });
};
```
5. Run `npm run build` or `next build` in the project root.

**Comment by aleksei-savitski-softswiss** [comment]
I have the same issue. I think the reason is [`standalone` build mode](https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files). I have been using ioredis-mock with next.js before and the build got to be infinite only after I turned on `standalone` mode. It took quite a time to find that the reason is the import of `ioredis-mock`.

**Comment by blenderskool** [comment]
@aleksei-savitski-softswiss Yes, this issue was resolved in ioredis-mock https://github.com/stipsan/ioredis-mock/issues/1103, the fix was mostly just syntactic change which makes me think there's an underlying issue somewhere else (either next.js or it's dependencies) that caused this in the first place. Or maybe I'm just overthinking it!

I'll close this issue now as it is resolved with newer versions of ioredis-mock, maybe if it occurs again or if I get more details, I'll reopen this.
