### ISSUE TITLE
Exported members that are used in SSR/SSG/ISG page function are undefined on the client (Attempted import error: '..' is not exported from '..' (imported as '..').)

### ISSUE THREAD

**Issue by bennettdams** [vercel/next.js#31855]
### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome Version 96 (Official Build) (64-bit)

### What operating system are you using?

Ubuntu 20.04 via WSL 2 & Windows 10

### How are you deploying your application?

next start

### Describe the Bug

When you export a member that is used in the page function of `getStaticProps`, it will be `undefined` on the client.

For example:

```ts
// pages/index.tsx
export const revalidateInSeconds = 5 * 60;

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {},
    revalidate: revalidateInSeconds,
  };
};

// components/TestComponent.tsx
import { revalidateInSeconds } from "../pages";

export function TestComponent(): JSX.Element {
  console.log("revalidateInSeconds: ", revalidateInSeconds);
  return <p>Test component</p>;
}
```

### Expected Behavior

Exported variables shouldn't be `undefined` on the client.

## Reproduction repo

I created a reproduction repo for this bug:

[https://github.com/bennettdams/nextjs-bug-export-undefined](https://github.com/bennettdams/nextjs-bug-export-undefined)

1. `git clone git@github.com:bennettdams/nextjs-bug-export-undefined.git`
2. `npm i`
3. `npm run build`
4. `npm run start`

## Manual reproduce

1. [Create Next.js app](https://github.com/bennettdams/nextjs-bug-export-undefined/commit/0c812c6fcc7f86a6d49b6c51c94669fc0574b48e): `npx create-next-app@latest --use-npm --ts .`
2. [Add `getStaticProps` and a `const` to export](https://github.com/bennettdams/nextjs-bug-export-undefined/commit/851a9b4e12699c505dc82cc0c587b9abdf3160c6):
```tsx
export const revalidateInSeconds = 5 * 60;

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {},
    revalidate: revalidateInSeconds,
  };
};
```
3. [Add a test component](https://github.com/bennettdams/nextjs-bug-export-undefined/commit/65064110c06af6b6ef20aa08a1e6f49078af45d4) that logs the imported `const` (`revalidateInSeconds`) and use the component on the page:
```tsx
// components/TestComponent.tsx
import { revalidateInSeconds } from "../pages";

export function TestComponent(): JSX.Element {
  console.log("revalidateInSeconds: ", revalidateInSeconds);
  return <p>Test component</p>;
}

// pages/index.ts
...
  <main className={styles.main}>
        <TestComponent />

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
...
```
4. Build & start the app: `npm run build` & `npm run start`

# Results, looking at the console logs

### Terminal that is used for building:

<details>
  <summary>Click for text!</summary>
  
```
> next build

info  - Checking validity of types  
info  - Creating an optimized production build  
warn  - Compiled with warnings

./components/TestComponent.tsx
Attempted import error: 'revalidateInSeconds' is not exported from '../pages' (imported as 'revalidateInSeconds').

Import trace for requested module:
./pages/index.tsx

info  - Collecting page data  
```
</details>

![image](https://user-images.githubusercontent.com/29319414/143610743-84ce34ea-8ccd-4791-a30b-d765729306c3.png)

### Browser:

![image](https://user-images.githubusercontent.com/29319414/143609672-ac97e487-9700-4285-b1d0-abd36223a28e.png)

---

## Additional information:

- When you run `npm run dev` instead of using the build, you can see that the `console.log` on the server actually has the value, instead of being `undefined`:
![image](https://user-images.githubusercontent.com/29319414/143610000-42fd9e87-2278-42aa-8303-691cc41f3b51.png)
Just on the client it is still `undefined`.

- I checked this behavior also for Next.js `v11.1.2` - there, it is not happening. The variable has its value on the client as expected.

**Comment by carlosbaraza** [comment]
Anyone has a workaround for this?

**Comment by carlosbaraza** [comment]
Somehow this does not happen when I build in my Macbook, but it happens when building in the CI. Could it be related to Linux?

**Comment by santialbo** [comment]
I think this is the same issue as https://github.com/vercel/next.js/issues/30611

**Comment by balazsorban44** [comment]
This has now been fixed, please upgrade to `latest`. (Tested with `12.0.8`)

**Comment by bennettdams** [comment]
Hey @balazsorban44,

I upgraded my [reproduction repo to Next.js `v12.0.8`](https://github.com/bennettdams/nextjs-bug-export-undefined/commit/bb22920a420302128966a7ea9e21d2fdc58c53aa) and the error remains the same:

![image](https://user-images.githubusercontent.com/29319414/149533921-cea091a5-14bd-4b75-8b3a-603e3bcac6fd.png)

**Comment by bennettdams** [comment]
To make sure that the OS has no play in testing this out, I added a [VS Code Docker development container](https://code.visualstudio.com/docs/remote/containers) based on Linux (Debian). With that, even if you don't have Linux, the error can be reproduced.

To test this out:
- In VS Code, install the [Remote Development extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack)
- Open the repo in VS Code and start the container (popup at the bottom right or via command palette: `Remote-Containers: Rebuild and Repoen in Container`)
- VS Code should restart and be inside the container afterwards

  ![image](https://user-images.githubusercontent.com/29319414/149538590-8b19d128-16cf-40b7-ac74-ace3c10663a8.png)
- Run `npm run build`

![image](https://user-images.githubusercontent.com/29319414/149538745-1fd93262-cec0-4bc6-ac2f-5e7f1a9b043a.png)

**Comment by balazsorban44** [comment]
This sounds like an edge-case in my opinion, but here is what I've found.

You have multiple options that might make more sense in this case, and would work as intended after testing with your reproduction.

1. The `TestComponent` being used in the same page file could receive the variable as a prop, so you wouldn't need to export it and import it somewhere else.

2. Use an environment variable to share information that is used both client and server-side. Even if it's not a secret, you might want to be mindful about exposing any values being used server-side, so something like `process.env.NEXT_PUBLIC_REVALIDATE` could make this more explicit

3. Define the value in a separate config file, that both the component file and the page file import. This way Next.js won't cut out the value being imported in the component file.

I checked and indeed this works with Babel, so this is SWC related indeed, but also might be the more correct solution. Let me check with the team!

**Comment by LuigiMaestrelli** [comment]
I'm having a simular issue, but I'm using a custom .babelrc to be able to use InversifyJS.
This is my .babelrc:
```
{
"presets": ["next/babel"],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}
```

Everything is working, on dev and production, but I'm getting a lot of messages like this on build.

```
./src/application/usecases/user/userUseCase.ts
Attempted import error: 'IUserApi' is not exported from '../api/auth/userApi' (imported as 'IUserApi').
```

The export and files are correct
