### ISSUE TITLE
Ability to suppress Fast Refresh warnings

### ISSUE THREAD

**Issue by danielhuang** [vercel/next.js#31893]
### Describe the feature you'd like to request

I use a [babel plugin](https://github.com/gajus/babel-plugin-transform-export-default-name) to automatically generate names for anonymous arrow functions. However, `Anonymous arrow functions cause Fast Refresh to not preserve local component state.` is constantly printed to the console. Fast Refresh works as expected using the babel plugin.

### Describe the solution you'd like

I would like a configuration option to disable this warning.

### Describe alternatives you've considered

I have considered naming my functions, but anonymous functions are cleaner in my opinion.

**Comment by YangJeffrey** [comment]
I agree
