### ISSUE TITLE
Can't use dynamic import with esm package

### ISSUE THREAD

**Issue by its-mXc** [vercel/next.js#31907]
### What version of Next.js are you using?

12

### What version of Node.js are you using?

12.22.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Tried to use esm package with dynamic import, It throws this error
```
Module not found: ESM packages (@package-name) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
  45 |   () =>
  46 |     import("@package-name"),
> 47 |   {
     |  ^
  48 |     ssr: false,
  49 |   }
  50 | );
```

### Expected Behavior

-

### To Reproduce

Try to dynamic import a esm package i.e. type module in package.json

**Comment by danieljamesross** [comment]
I have a similar problem. Trying to import and run `tonejs`. Currently using Next@12, 

`code: 'ERR_MODULE_NOT_FOUND'`

**Comment by reducio** [comment]
I have a similar problem.

**Comment by its-mXc** [comment]
@timneutkens I will add a reproduction repository this weekend

**Comment by reducio** [comment]
> I have a similar problem. System doesn't give any errors. `"next": "^12.0.5-canary.12"`

Fixed it in `12.0.8-canary.3` version.

**Comment by danieljamesross** [comment]
I confirm this fix works for my use case (above, https://github.com/vercel/next.js/issues/31907#issuecomment-981572836)

**Comment by timneutkens** [comment]
Thanks for checking and reporting back 🙏
