### ISSUE TITLE
SWC fails with exported functions generated in closures

### ISSUE THREAD

**Issue by lucasbasquerotto** [vercel/next.js#31924]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

16.5.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

next dev

### Describe the Bug

The following code does not work with SWC:

```ts
const authStorageHandler = ((storage?: AuthStorage) => {
	const defineAuthStorage = (newStorage: AuthStorage) => {
		storage = newStorage;
	};

	return {
		defineAuthStorage,
		getAuthStorage: () => {
			if (!storage) {
				console.error('no storage defined');
			}

			return storage as AuthStorage;
		},
		hasAuthStorage: () => !!storage,
	};
})();

export const { defineAuthStorage, getAuthStorage, hasAuthStorage } =
	authStorageHandler;
```

I export the functions generated by the closure so as not make the variables global in the file. 

Instead, for it to work, I have to change the code to the following:

```ts
let storage: AuthStorage | undefined = undefined;

export const defineAuthStorage = (newStorage: AuthStorage) => {
	storage = newStorage;
};

export const getAuthStorage = () => {
	if (!storage) {
		console.error('no storage defined');
	}

	return storage as AuthStorage;
};

export const hasAuthStorage = () => !!storage;
```

We use closures in several places so that would need a lot of refactoring, and not only that, but the variables would need to be placed in the scope of the file (or several files, one for each closure, should be created).

Considering that closures is a fundamental javascript feature, this error caught us by surprise, I expect that this issue is solved soon.

In the meantime, we opted out of SWC (also because we need `inline-react-svg`, and to load typescript files outside of the root context, for react web and native projects, and we don't see a replacement for `next-babel-loader`).

### Expected Behavior

It should work. closures are a fundamental feature of javascript and exporting functions generated by them should work too.

### To Reproduce

Both `next dev` and `next build` generates an error of import not found, if the import comes from an export generated by a closure, as described previously.

**Comment by lucasbasquerotto** [comment]
I just want to add that I don't see this problem with `next@12.0.8` (using both the `dev` and `build` commands). 

Was there a fix regarding this issue? I saw some SWC fixes/improvements in the RELEASES notes, but nothing specific to this issue.

In any case, it seems this issue was solved and I can now enjoy the faster builds in development.

**Comment by timneutkens** [comment]
I'll close this for the same reason as https://github.com/vercel/next.js/issues/31923#issuecomment-1013056176. If you run into issues with SWC enabled please let us know, thanks!
