### ISSUE TITLE
NEXT_ENV for natively managing different environments

### ISSUE THREAD

**Issue by LucasLemanowicz** [vercel/next.js#31947]
### Describe the feature you'd like to request

I have a local dev environment, a deployed staging environment, and a deployed production environment. It would be nice to be able to manage all those environments with .env files without having to import additional packages or use conditional logic in the source code itself.

### Describe the solution you'd like

I'd like to be able to define an environment variable that tells NextJS which env file to load. For example, a sample `package.json` file would look like:

```javascript
{
  "scripts": {
     "build": "next build", // default = production
     "build:staging": "NEXT_ENV=staging next build",
     "build:production": "NEXT_ENV=production next build",
     // ...
  },
  // ...
}
```

Another (possibly even cleaner) alternative would be to pass in the environment as a parameter:
```javascript
{
  "scripts": {
     "build": "next build", // default = production
     "build:staging": "next build staging",
     "build:production": "next build production",
     // ...
  },
  // ...
}
```

### Describe alternatives you've considered

There is no clean way to do this in NextJS currently. Alternatives include addition conditional logic in the actual code, and/or installing additional dependencies like `env-cmd`. There are enough blog posts and medium articles about this that it's worth considering how to support these workflows in a first class way. Here's just a few:

* https://medium.com/@dzungnguyen179/nextjs-multiple-environment-builds-e8b2ccb11c04
* https://stackoverflow.com/questions/59462614/how-to-use-different-env-files-with-nextjs
* https://dev.to/martiuh/cool-way-to-use-staging-and-production-environment-with-next-js-28bb

**Comment by balazsorban44** [comment]
Have you seen the official docs about this? https://nextjs.org/docs/basic-features/environment-variables

you can define different `.env.*` files for different environments.

Here is an example repo as well https://github.com/vercel/next.js/tree/canary/examples%2Fenvironment-variables
