### ISSUE TITLE
FetchError: request to https://.../api/v1/projects failed, reason: connect ETIMEDOUT 34.241.115.67:443

### ISSUE THREAD

**Issue by KennStack01** [vercel/next.js#31950]
### What version of Next.js are you using?

^12.0.4

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Google Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next export

### Describe the Bug

Getting this error,
I don't really understand why. I really want your help 🙏

My API link: https://mvp4startup-api.herokuapp.com/api/v1/projects

```
export async function getStaticProps() {
  const res = await fetch(`${server}/api/v1/projects`);
  const projects = await res.json();
  const formations = await fetch(`${server}/api/v1/formations`).then((res) =>
    res.json()
  );
  const businessplans = await fetch(`${server}/api/businessplans`).then((res) =>
    res.json()
  );
  return {
    props: {
      projects,
      formations,
      businessplans,
    },
  };
}
```

### Expected Behavior

I expect to receive data and render it to the page, through props.

### To Reproduce

Setup next app (version ^12.0.4) and make a getStaticProps call.

**Comment by MonstraG** [comment]
Same code but actually readable, use triple quotes and language name for it to work: \```ts 
```ts
export async function getStaticProps() {
	const res = await fetch(`${server}/api/v1/projects`);
	const projects = await res.json();
	const formations = await fetch(`${server}/api/v1/formations`).then((res) => res.json());
	const businessplans = await fetch(`${server}/api/businessplans`).then((res) => res.json());
	return {
		props: { projects, formations, businessplans }
	};
}
```

**Comment by KennStack01** [comment]
Actually, it's a Remote Server running at [https://mvp4startup-api.herokuapp.com/api/v1/projects](https://mvp4startup-api.herokuapp.com/api/v1/projects)

**Comment by MonstraG** [comment]
this:
```ts
export async function getStaticProps() {
	const server = "https://mvp4startup-api.herokuapp.com";
	const res = await fetch(`${server}/api/v1/projects`);
	const projects = await res.json();
	const formations = await fetch(`${server}/api/v1/formations`).then((res) => res.json());
	return {
		props: {
			projects,
			formations
		}
	};
}
```
works fr me and I can succesfully receive both projects and formations.

Including businessplans gives me `FetchError: invalid json response body at https://mvp4startup-api.herokuapp.com/api/businessplans reason: Unexpected end of JSON input`

In any case, it doesn't seem like its an issue with nextjs.

**Comment by KennStack01** [comment]
Sorry, check with this new config: 

```
export async function getStaticProps() {
	const server = "https://mvp4startup-api.herokuapp.com";
	const res = await fetch(`${server}/projects`);
	const projects = await res.json();
	const formations = await fetch(`${server}/formations`).then((res) => res.json());
	return {
		props: {
			projects,
			formations
		}
	};
}
```

```
const dev = process.env.NODE_ENV !== "production";

export const server = dev
  ? "https://mvp4startup-api.herokuapp.com/api/v1"
  : "https://mvp4startup-api.herokuapp.com/api/v1";
```

just added the `/api/v1` in the config file

**Comment by MonstraG** [comment]
Try making curl request to the api yourself to make sure that you can reach it.

**Comment by KennStack01** [comment]
just checked using postman [here](https://web.postman.co/workspace/My-Workspace~9e9ddbf7-41a6-416f-85e4-684f1c37ddf9/request/create?requestId=c3959c3a-92bd-4e8d-87d8-25f56ad484e7)

It works fine, I've got the JSON data
