### ISSUE TITLE
Error on clean install

### ISSUE THREAD

**Issue by thany** [vercel/next.js#32019]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.18.2

### What browser are you using?

Firefox 94

### What operating system are you using?

Windows 10

### How are you deploying your application?

I'm not

### Describe the Bug

Error appears after a **clean install** with typescript:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
[etc]
```

### Expected Behavior

No error, I guess.

### To Reproduce

Run the following command and give it any project name you haven't created before:

```
npx create-next-app@latest --typescript
```

Then, start it:

```
npm run dev
```

This will produce the error.

**Comment by thany** [comment]
Actually, I just tried to literally follow the quickstart, so I nuked my project directory, and recreated it using the command from the quickstart:

```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/basics-final"
```

Same error.

**Comment by thany** [comment]
Also, updating Node.js did not help. I'll update the bug report.

**Comment by thany** [comment]
Oh I just noticed I'm also getting errors like this in the CLI. I didn't see em before because the "invalid hook call" was flooding the CLI.

```
./node_modules/react/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* D:\Projecten\nextjs-blog\node_modules\react\index.js
    Used by 37 module(s), i. e.
    D:\Projecten\nextjs-blog\node_modules\@next\react-refresh-utils\loader.js!d:\Projecten\nextjs-blog\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use[1]!D:\Projecten\nextjs-blog\node_modules\next\dist\client\router.js
* d:\Projecten\nextjs-blog\node_modules\react\index.js
    Used by 13 module(s), i. e.
    D:\Projecten\nextjs-blog\node_modules\@next\react-refresh-utils\loader.js!d:\Projecten\nextjs-blog\node_modules\next\dist\build\webpack\loaders\next-swc-loader.js??ruleSet[1].rules[2].oneOf[2].use[1]!d:\Projecten\nextjs-blog\node_modules\next\dist\pages\_error.js
```

I don't see why the two are different. I'm on Windows, which is case-insensitive. If there any OS where this shouldn't happen, it'd be on Windows. The two directories mentioned there are *identical*. And yes, I can see the drive letter differs in casing. I can't help that, and I'm not going to.

But then again, I'm not sure if this has any merit to the original bug. These might be harmless warnings. No idea.
(not that they shouldn't be fixed - they absolutely should be)

**Comment by balazsorban44** [comment]
Do you maybe have `react` installed globally or have you used symlinks?
