### ISSUE TITLE
Rewrites don't seem to work when concurrentFeatures is enabled

### ISSUE THREAD

**Issue by hamlim** [vercel/next.js#32044]
### What version of Next.js are you using?

next@12.0.5-canary.13

### What version of Node.js are you using?

v14.18.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

When `experimental.concurrentFeatures` is enabled, any configured `rewrites` within `next.config.js` no longer function as they do without that feature enabled.

In development mode, the page will hang and in production the error / 404 page will be shown instead.

### Expected Behavior

Rewrites configured within `next.config.js` should work as they do when `concurrentFeatures` isn't enabled.

### To Reproduce

Clone this repo: https://github.com/hamlim/concurrent-features-rewrites-bug

Run:

- `yarn`
- `yarn build`
- `yarn start`

Visit localhost:3000/foo, see error page

**Comment by hamlim** [comment]
Possibly related issue: https://github.com/vercel/next.js/issues/31506

**Comment by jescalan** [comment]
This experimental feature has been removed, so we're gonna close this one out. Happy to talk about options for how to do rewrites with edge runtime once we get further along towards general purpose edge functions which is on the way as you have noticed! It is something we are thinking about and will provide support for. You may also be able to use middleware as a temporary workaround?
