### ISSUE TITLE
CSS Modules in React Server Components not working as intended

### ISSUE THREAD

**Issue by lfades** [vercel/next.js#32068]
### What version of Next.js are you using?

^12.0.5-canary.13

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Macos (M1)

### How are you deploying your application?

Vercel

## Behavior in Server Components

- CSS Modules don't work in server components (`.server.js`), they're currently only supported by client components (`.client.js`). This is currently mentioned in the [Next.js documentation](https://nextjs.org/docs/advanced-features/react-18#unsupported-nextjs-apis) but I'm still including as it being supported seems expected. There are no errors displayed when using them in the server either.

## Behavior in Client Components

- CSS Modules included in a `.client.js` component under a server component have a flash of content, the first render is unstyled. Happens with `next dev` and `next start`
- If the server component page switches to a dynamic route, e.g switching from `css-modules.server.js` to `[css-modules].server.js`, CSS modules won't work for client components either, the classname is applied but the styles aren't there

### Expected Behavior

To CSS Modules to work as they do without RSC.

### To Reproduce

Should be reproducible by running the `css-modules.server.js` page available in the `react-streaming-and-server-components` tests: https://github.com/vercel/next.js/blob/canary/test/integration/react-streaming-and-server-components/app/pages/css-modules.server.js

**Comment by huozhi** [comment]
Closed in #38536
