### ISSUE TITLE
Invalid URL kill the server

### ISSUE THREAD

**Issue by hopeless-programmer-online** [vercel/next.js#32075]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

14.15.5/16.13.1

### What browser are you using?

Firefox

### What operating system are you using?

Windows 7/10

### How are you deploying your application?

next start

### Describe the Bug

The server crashes on invalid HTTP requests like `*`:

```
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: *
```

This kills the server on node 16 and gives error logs on node 14.

### Expected Behavior

Errors shouldn't kill the server on node 16 or there should be a way to intercept them (like `pages/_error`).

### To Reproduce

0. Clone <https://github.com/hopeless-programmer-online/next-invalid-url-issue>.
1. Run `npm ci` to install dependencies.
2. Run `npm run build` to build the project.
3. Run `npm start` to start the server.
4. Run `npm run request` in separate terminal to send killing request.
5. Observe `UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: *`. This should kill the server on node 16.

**Comment by chentsulin** [comment]
As of Node.js 15, the default mode for unhandledRejection is changed to throw (from warn).

Protecting with a try/catch block may be needed between these lines:

https://github.com/vercel/next.js/blob/647c06b339ccabb5ee583cbdd32e12b8af6b0fd4/packages/next/server/next-server.ts#L376-L393

**Comment by Fonger** [comment]
I think this is a DoS vulnerability and there should be a hot-fix release.
