### ISSUE TITLE
getServerSideProps is executed in Edge Runtime with concurrentFeatures enabled

### ISSUE THREAD

**Issue by alex-statsig** [vercel/next.js#32108]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

With the experimental feature "concurrentFeatures" enabled, getServerSideProps can no longer import node modules like fs or perf_hooks.

### Expected Behavior

getServerSideProps should still allow node functions. It is not a "Server side rendering" function (the docs do mention SSR will be executed using the Edge Runtime, preventing fs/perf_hooks from being imported), but rather just a server function. It's unclear if this is intentional based on the wording of the docs.

### To Reproduce

Import perf_hooks from a page, only call the module from within getServerSideProps. The page will fail to build saying perf_hooks is not allowed in Edge Runtime.

**Comment by huozhi** [comment]
As the [docs of edge functions](https://vercel.com/docs/concepts/functions/edge-functions) mentioned, Native Node.js APIs are not supported in edge runtime. For example, you can't read or write to the filesystem. When you enable the `concurrentFeatures` it will be deployed to edge runtime at the moment.

We're working on the plan to let user play `concurrentFeatures` with node runtime in the near future. 🙏

**Comment by barthuijgen** [comment]
> We're working on the plan to let user play `concurrentFeatures` with node runtime in the near future. 🙏

Is there any (even very rough) timeline on this? 

I honestly don't know why you built for the Edge runtime first, I imagine way more of the community would benefit from `concurrentFeatures` on the node runtime rather then the Edge runtime. Better stop using Next.js if you're not hosting it on vercel, because clearly it's not a priority.

**Comment by huozhi** [comment]
It's definitely a priority. Concurrent feautres like streamning needs more additional contraints to ensure it's fast and does not break, edge runtime is the good place to do it then users can benefit from streaming.

**Comment by alex-statsig** [comment]
@huozhi Yeah I understood native node APIs aren't available in edge runtime, I just didn't realize that concurrentFeatures would make *everything* run in edge runtime (I thought just the UI rendering would or something). It seemed weird to me that just wanting to use <Suspense /> would require my getServersideProps to run on Edge runtime. But if it's a priority to be developed that makes sense, and clears this up I think. Thanks!

**Comment by alex-statsig** [comment]
> Is there any (even very rough) timeline on this?

@huozhi Is there any tracking for this that I can subscribe to? I'm very excited to make use of concurrent features so I can actually start using Suspense.

**Comment by balazsorban44** [comment]
I believe you can follow this one: #31506 Closing in favor.
