### ISSUE TITLE
API route catch all not working with basePath and i18n

### ISSUE THREAD

**Issue by zanatoshi** [vercel/next.js#32176]
### What version of Next.js are you using?

11.1.3

### What version of Node.js are you using?

14

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

Vercel

### Describe the Bug

We are building a NextJS with Typescript app deployed on Vercel.
In our app, we are using a catch all routes `pages/api/services/[...slug].ts`
This is working very fine with an empty basePath.
But when we start deploying our app with a {basePath: "us"}` then it is still working on local but once deployed to Vercel, it looks like the catch all route does not exist, we have directly a 404.

I created a [minimal test app](https://github.com/zanatoshi/api-routes-rest-app) to reproduce.
It was working all fine until I added the i18n configuration.
I tried with `{basePath:"/us"}` and `{basePath:"/azerty"}`, both failed.

### Expected Behavior

Expect a fetch call to `<app_url>/us/api/services/test` to be catch by our `pages/api/services/[...slug].ts`

### To Reproduce

Repository : [https://github.com/zanatoshi/api-routes-rest-app](https://github.com/zanatoshi/api-routes-rest-app)

Test link : [https://api-routes-rest-app-vert.vercel.app/azerty](https://api-routes-rest-app-vert.vercel.app/azerty)

**Comment by ijjk** [comment]
Hi, this has been updated, please re-deploy your application and give it a try! 

Example deployment of the reproduction can be seen here:
https://api-routes-rest-app-l4sag1yf9-ijjk-testing.vercel.app/azerty/api/users/first
https://api-routes-rest-app-l4sag1yf9-ijjk-testing.vercel.app/azerty/api/user/first
