### ISSUE TITLE
Hidden error with await rejected promise inside getStaticPaths

### ISSUE THREAD

**Issue by urffin** [vercel/next.js#32180]
### What version of Next.js are you using?

12.0.0

### What version of Node.js are you using?

14.16.0, 15.9.0

### What browser are you using?

any browser

### What operating system are you using?

macOS

### How are you deploying your application?

next build

### Describe the Bug

if in async function `getStaticPaths` error raised in some nested async function, called with await, like this

    export const getStaticPaths = async () => {
      await Promise.reject('Error hidden');
      // throw new Error('Raised error');
    };

then when execute `next build` in console would be output just

     Build optimization failed: found page without a React Component as default export in pages/dyn/[num]

instead normal error message. If throw error directly - then log is fine

### Expected Behavior

output concrete error message

### To Reproduce

https://stackblitz.com/edit/nextjs-pnhrbs?file=pages/dyn/[num].jsx

To reproduce run: `next build`

enough 

    export const getStaticPaths = async () => {
      await Promise.reject('Error hidden'); // any rejected promise with message
      // throw new Error('Raised error');
    };

**Comment by balazsorban44** [comment]
It is generally a good idea to reject with an `Error` if you have control over that.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject#description

**Comment by urffin** [comment]
Hmmmm. interesting...

**Comment by urffin** [comment]
@balazsorban44 is it possibly do more relevant error message? without changing nested promise

as workaround, of cource i can

    await promise.catch(e => Promise.reject(new Error(e)))

but this looks ugly

**Comment by balazsorban44** [comment]
`await promise` in that case would be enough I think. If the `promise` fails, it will just throw its error, which is caught by Next.js

**Comment by urffin** [comment]
> `await promise` in that case would be enough I think. If the `promise` fails, it will just throw its error, which is caught by Next.js

No, this work only if promise rejected with `new Error`, if reject reason any other value, for example _string_ - output just message about _Build optimization failed: found page without a React Component as default export in ..._ 

This is a problem to detect real error reason.

**Comment by ijjk** [comment]
Hi, this should be fixed in the latest version of Next.js `v12.0.10`, please update and give it a try. 

Related fix: https://github.com/vercel/next.js/pull/33753
