### ISSUE TITLE
Custom server buildId missing

### ISSUE THREAD

**Issue by tonytoth** [vercel/next.js#32292]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

chrome

### What operating system are you using?

ubuntu server

### How are you deploying your application?

custom

### Describe the Bug

Trying to use build id on a custom server (for assetPrefix) but seems like it was removed so now I'm not able to use it as it was moved under server which is private.
```ts
export declare class NextServer {
    private serverPromise?;
    private server?;
    private reqHandlerPromise?;
    private preparedAssetPrefix?;
    options: NextServerOptions;
    constructor(options: NextServerOptions);
    get hostname(): string | undefined;
    get port(): number | undefined;
    getRequestHandler(): RequestHandler;
    setAssetPrefix(assetPrefix: string): void;
    logError(...args: Parameters<Server['logError']>): void;
    render(...args: Parameters<Server['render']>): Promise<void>;
    renderToHTML(...args: Parameters<Server['renderToHTML']>): Promise<string | null>;
    renderError(...args: Parameters<Server['renderError']>): Promise<void>;
    renderErrorToHTML(...args: Parameters<Server['renderErrorToHTML']>): Promise<string | null>;
    render404(...args: Parameters<Server['render404']>): Promise<void>;
    serveStatic(...args: Parameters<Server['serveStatic']>): Promise<void>;
    prepare(): Promise<void>;
    close(): Promise<any>;
    private createServer;
    private loadConfig;
    private getServer;
    private getServerRequestHandler;
}
```

### Expected Behavior

Maybe have a public builId ?

### To Reproduce

```
const app = next({ dev });
app.prepare().then(() => {
  if (process.env.CDN_PATH) {
    app.setAssetPrefix(`${process.env.CDN_PATH}/${app.buildId}/`);
});
```

**Comment by balazsorban44** [comment]
I believe you don't need to set that?

You might also try using `next.config.js` instead, to set the `assetPrefix`.

Check out https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix

**Comment by tonytoth** [comment]
I know that I can use assetPrefix in next.config.js but I need a dynamic asset prefix.

**Comment by balazsorban44** [comment]
You can still access it from `app.server.buildId`

**Comment by tonytoth** [comment]
U kidding, right ?

**Comment by balazsorban44** [comment]
Not sure if sarcastic, or not. :sweat_smile: 

`server.js`:
```js
...
app.prepare().then(() => {
  console.log(app.server.buildId)
...
```

Terminal:
```sh
$ NODE_ENV=production node server.js
KJHCnqhsn60hGAWj9JD_2
> Ready on http://localhost:3000
```

**Comment by tonytoth** [comment]
:|
Dude ... I'm talking about about a Typescript interface and you close this topic without understanding the issue ... 
Then you show me JS code ...

**Comment by balazsorban44** [comment]
For what it's worth, that is an undocumented API, so you should only be using it at your own risk. Even the `setAssetPrefix` API is undocumented/not supported anymore.

There is probably a better way to solve your use case, I suggest you open a discussion in Help to help you upgrade.

**Comment by jpmarra** [comment]
Now that `Server` is wrapped by `NextServer` and is a private variable, we are unable to access `buildId` without ignoring the TS error. This is true for all of the previously public `Server` values, like the `router` which houses `dynamicRoutes`. 

Many of these things are necessary in order to properly build out a custom server. Why were they made private?

**Comment by balazsorban44** [comment]
Because they are APIs not intended for use by the end-user.
