### ISSUE TITLE
beforeFiles rewrites are ignored by Link component when a file system route exists

### ISSUE THREAD

**Issue by jasonbarone** [vercel/next.js#32348]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

next start, Vercel

### Describe the Bug

beforeFiles rewrites are being ignored by client side routing with Link component when a file system route exists.

### Expected Behavior

Referring to the [documentation](https://nextjs.org/docs/api-reference/next.config.js/rewrites):

> Rewrites are applied to client-side routing, a <Link href="/about"> will have the rewrite applied in the above example.

I would expect that the Link component would follow rewrites in the beforeFiles array the same way an incoming request follows, regardless of the existence of dynamic routes or a file system route.

### To Reproduce

1. Visit https://rewrites-test-two.vercel.app/
2. Click "Go to Test page"
3. You've navigated to the /test file system route. 
4. Refresh your browser. Notice you are now on Vercel.com.

The Go to Test page link is set to route to /test using the Link component. However, rewrites are set for /test to serve vercel.com. You should be routed to the rewrite destination, but instead you're routed to the file system route component (/test.js). When making a request using the browser, the correct destination appears.

Repo: https://github.com/jasonbarone/rewrites-test

**Comment by jasonbarone** [comment]
The example above uses beforeFiles: https://github.com/jasonbarone/rewrites-test/blob/main/next.config.js#L5.

**Comment by JackOddy** [comment]
also experiencing this, its blocking our ability to incrementally adopt next.js. any workarounds?

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.0.11-canary.2` of Next.js, please update and give it a try!

**Comment by JackOddy** [comment]
hi @ijjk i tried this out and rewrites from a client side request, when there is still a file system route, still do not rewrite. however the rewrite branch of the middleware is triggered as before, and if refreshing on the page that should be overwritten, the rewrite is applied correctly.

I put together a demo app here thats using `v12.0.11-canary.2` [https://github.com/JackOddy/client_side_rewrites_not_working](https://github.com/JackOddy/client_side_rewrites_not_working)

Main branch is using middleware, but there is also a beforeFiles branch that does the same thing in next.config.js - behaviour is the same

**Comment by jasonbarone** [comment]
@ijjk: awesome stuff, confirmed working! 🙏
