### ISSUE TITLE
Next.js imports browser bundle in `_middleware` file of api

### ISSUE THREAD

**Issue by JonasHiltl** [vercel/next.js#32369]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chromse

### What operating system are you using?

Windows

### How are you deploying your application?

Next start

### Describe the Bug

We are trying to connect to MongoDB inside the `_middleware` file of the api. We are using `mongoose` as the driver but when calling our connect funtion from inside the `pages/api/_middleware.ts` the browser bundle of mongoose is being imported instead of the default Node bundle. This causes our connection to fail
```
warn  - ./node_modules/mongoose/dist/browser.umd.js
`eval` not allowed in Middleware pages/api/_middleware
TypeError: mongoose__WEBPACK_IMPORTED_MODULE_0___default(...).connect is not a function
    at dbConnect (webpack-internal:///./src/utils/dbConnect.ts:13:77)
    at Object.handler (webpack-internal:///./pages/api/_middleware.ts:5:75)
    at adapter (webpack-internal:///./node_modules/next/dist/server/web/adapter.js:30:35)
    at Module.__WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?page=%2Fapi%2F_middleware&absolutePagePath=D%3A%5CIO-DOCK%5Cauth-api%5Cpages%5Capi%5C_middleware.ts!:17:87)
    at Object.run (D:\ ...\node_modules\next\dist\server\web\sandbox\sandbox.js:164:30)
    at DevServer.runMiddleware (D:\ ...\node_modules\next\dist\server\next-server.js:423:46)
    at async DevServer.runMiddleware (D:\ ...\node_modules\next\dist\server\dev\next-dev-server.js:383:28)
    at async Object.fn (D:\ ...\node_modules\next\dist\server\next-server.js:784:34)
    at async Router.execute (D:\ ...\node_modules\next\dist\server\router.js:210:32)
    at async DevServer.run (D:\ ...\node_modules\next\dist\server\next-server.js:1085:29)
```
The `eval not allowed` warning is probably caused because the browser bundle is used and it uses `eval`.

### Expected Behavior

When the `_middleware` file is positioned inside the `api` folder it should not import the bundles for the browser but rather the default Node package. It probably imports the browser bundle because `_middleware` files are primarily used on the frontend side.

### To Reproduce

This is our connection function which we want to call inside the `_middleware` file.
```typescript
import mongoose from 'mongoose';

async function dbConnect() {
  try {
    // check if we have a connection to the database or if it's currently
    // connecting or disconnecting (readyState 1, 2 and 3)
    if (mongoose.connection?.readyState >= 1) {
      return;
    }

    const mongo = await mongoose.connect(process.env.MONGO_URL!, {
      dbName: 'core-auth',
    });
    if (!mongo) console.error('No connection to the DB established');
    return mongo;
  } catch (error) {
    console.error('Mongoose failed to connect to the DB');
    console.error(error);
  }
}

export default dbConnect;
```
This is our `_middleware` file:
```typescript
import { NextFetchEvent, NextRequest } from 'next/server';
import dbConnect from '../../src/utils/dbConnect';

const handler = async (_req: NextRequest, _event: NextFetchEvent) => {
  await dbConnect();
};

export default handler;

```

**Comment by IAmJakPro** [comment]
I am facing exactly the same issue, have you found any solution for that?

**Comment by Klerith** [comment]
Same over here...

**Comment by balazsorban44** [comment]
Do note this is expected, as Middleware uses the Edge Runtime which implements Web APIs and does not support Node.js as a target:

https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis

**Comment by lrowe** [comment]
It would be great if specifying `runtime: "nodejs"` in next.config.j` made it possible to use Node modules in _middleware.[jt]s as they can be from getServerSideProps. While custom servers provide a workaround, there is a lot of functionality included when running `next dev` or `next start` that is missing from the custom server example in the docs (such as graceful exit SIGTERM and SIGINT port and hostname niceties and a number of other checks.) Most frustratingly, moving logic to a custom server means dropping transpiration of typescript or having to write your own node require hook to reuse the next swc configuration.

**Comment by javivelasco** [comment]
Note that Middleware runs with a browser based runtime where Node.js is not supported although Next.js is currently polyfilling some native modules and runtime APIs.

We are currently working on providing better errors when we detect that the user is attempting to run Node in Middleware. As part of this we will remove polyfills for the Edge Runtime to reduce confusion and focus on failing in a more meaningful fail for:
- When importing a native node module (`child_process`, `events`, ...).
- When using a global node API (`process.nextTick`, `__dirname`, ...).

That said, for the case reported in the OP the expectation is incorrect. When the compiler resolves the `mongoose` import it will choose the browser bundle, which is fine, as it makes more sense for the middleware runtime which is browser-api based. A third party package is more likely to work correctly in the Edge Runtime with a browser bundle than a server bundle as it usually server implies Node.js. The error shown there is expected as you're attempting to use a method that [does not exist](https://mongoosejs.com/docs/browser.html) in the Mongoose browser version. 

There is not a lot that we can do on the Next.js side to improve the this particular error. Picking the browser bundle over Node.js feels also fine in this case as if we were picking Node.js you'd see an error telling that Node is not supported in the Edge Runtime. There is no margin of action for this issue so I'm going to close it.

Finally I also want to point out that is not a good idea to access a centralised database from Middleware unless in production your middleware is not running at an edge network (like Vercel) and close to your data.
