### ISSUE TITLE
--skip-install option in create-next-app

### ISSUE THREAD

**Issue by Pika-Pool** [vercel/next.js#32367]
### Describe the feature you'd like to request

A `--skip-install` option in create-next-app, like in react-native, to skip installing dependencies would be really great. It allows using other package managers like `pnpm`

### Describe the solution you'd like

do not install dependencies automatically when the `--skip-install` option is set. But the dependencies should be listed in `package.json`, so user could manually install the dependencies using other package managers like `pnpm`

### Describe alternatives you've considered

An option to use `pnpm`(`--use-pnpm`). `pnpm` has gained significant popularity and would be a good option to add.

**Comment by balazsorban44** [comment]
Adding a `--skip-install` flag sounds reasonable. I'm not 100% what would go into the `--use-pnpm` flag, let's start with the first one.

Here are the appropriate files: 

(look for `await install`)
https://github.com/vercel/next.js/blob/canary/packages/create-next-app/create-app.ts

https://github.com/vercel/next.js/blob/canary/packages/create-next-app/index.ts

**Comment by anirudh1713** [comment]
Hey there, I'm trying to do this. skipping the installation is not a problem, but what about populating `package.json` with version of packages? I don't think `*` or `latest` is a good idea for version of the packages :thinking:

**Comment by Pika-Pool** [comment]
> Currently, the cli installs "`latest`" for `next` and the exact versions for `react`, `react-dom` and the dev dependencies

There are a few methods of doing this in my opinion. I'm listing them down:
1. create a template package.json file and update it whenever the versions update
    - disadvantage: have to constantly monitor the latest version of packages
2. use the `npm show` or `yarn info` commands to get the latest version of the respective packages
    - disadvantage: need internet connection
3. query the npm registry to get the latest version
    - disadvantage: need internet connection
4. We can just console.log a message with the appropriate command, like: `yarn add next react react-dom`, just like the cli does with `yarn run dev` right now, without populating package.json

@balazsorban44, what do you think should be the optimal solution?

PS: I was hoping I could work on this, as I have already started too. Am I too late?

**Comment by balazsorban44** [comment]
Feel free to work on adding the `--skip-install` flag @Pika-Pool.

I'm not sure about what @anirudh1713 is suggesting. The CLI is meant to scaffold a minimal Next.js example project. You can use the `--examlpe` flag to pull from any of the available examples in [this folder](https://github.com/vercel/next.js/tree/canary/examples).

**Comment by Pika-Pool** [comment]
When using the default templates from [this folder](https://github.com/vercel/next.js/tree/canary/packages/create-next-app/templates), the dependency list in `package.json` is populated using the install command(`npm install` or `yarn install`). 
When the `--skip-install` option is enabled, we can no longer use this method. But we still need to list the dependencies, with their versions in the `package.json` file, so the user can install them using their favorite package manager.

So what would be a good method to get the respective versions? Should we just mark it as `latest` or `*`? Or I have listed some other ways I can think of in my [previous comment](https://github.com/vercel/next.js/issues/32367#issuecomment-991588615)

**Comment by anirudh1713** [comment]
@Pika-Pool Yes, that is what I was trying to say in my [previous comment](https://github.com/vercel/next.js/issues/32367#issuecomment-991577183), `latest` or `*` doesn't seem like a good idea. I think `--use-pnpm` might be a better way. :thinking: or maybe maintaining a `package.json`?

**Comment by balazsorban44** [comment]
The CLI is expected to spin up the `latest` version of `next`, so that would be sufficient I believe. You can expect the template code to be always up-to-date for the `latest` dist tag.

**Comment by Pika-Pool** [comment]
I've added a PR(#32484) to add this feature. It adds "latest" as the version for each dependency for the default templates

**Comment by balazsorban44** [comment]
Feel free to add it in https://github.com/vercel/next.js/blob/canary/test/integration/create-next-app/index.test.js

We will update the README to avoid confusion.

**Comment by balazsorban44** [comment]
`--use-pnpm` has been added
