### ISSUE TITLE
Middleware query params functionality is broken

### ISSUE THREAD

**Issue by ardaerzin** [vercel/next.js#32480]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

We've been keeping an eye on the middleware functionality since the launch of v12. one use case we are interested in, is to authenticate users via magic links. While we can achieve this functionality, when we want to remove the token from url, we are getting errors due to infinite redirections. token is not being removed and the same thing is called over and over again until the function crashes.

others and us also saw this on examples [provided by Vercel](https://github.com/vercel/examples/issues/45)

### Expected Behavior

we expect the functionality to work as described [here](https://github.com/vercel/examples/tree/main/edge-functions/query-params-filter)

### To Reproduce

visit this [url](https://edge-functions-query-params-filter.vercel.sh/?a=b&allowed=test)

**Comment by Javimtib92** [comment]
I'm experiencing the same issue with the exact same behaviour.
Our case is that we are adding event listeners in _app file that check for auth state with a 3rd party server based on some query params we get from a magic link. This issue is causing the _app to render twice and therefore attaching the event listeners two times, then those internally are supposed to perform a redirection but they enter in a loop of redirections that crashes the app.

**Comment by ardaerzin** [comment]
is this being tracked? I mean, the official example is broken for over a month now. any information from the team will be helpful for us to plan our next tasks

**Comment by bryanrsmith** [comment]
Same here, with a slightly different use case--I'm using middleware to redirect some requests **to an external site**, and the query params that the middleware receives are being attached to the external redirect target. Seems potentially pretty dangerous 😬

**Comment by javivelasco** [comment]
This is now supported! You can remove query string parameters filtering them out with the `URLSearchParams` API.

**Comment by bryanrsmith** [comment]
@javivelasco I believe this case was specifically for **redirects**, not rewrites. I have verified that the issue has not been resolved. I can repro only when deployed to Vercel, and not when running locally. It maybe a vercel bug and not a next.js bug. Here's a repro: 

https://next-middleware-redirects.vercel.app/

Code: https://github.com/bryanrsmith/next-middleware-redirects

**Comment by bryanrsmith** [comment]
@javivelasco There is still an problem here--see repro above. Would you like me to create a separate issue?

**Comment by balazsorban44** [comment]
Yes, please open a separate issue, we appreciate it! :pray:
