### ISSUE TITLE
error - ReferenceError: Cannot access 'ComponentName' before initialization

### ISSUE THREAD

**Issue by jethrolarson** [vercel/next.js#32516]
### What version of Next.js are you using?

12.0.8-canary.6

### What version of Node.js are you using?

v16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

OSX

### How are you deploying your application?

haven't yet

### Describe the Bug

When trying to build the application I get the error:
`error - ReferenceError: Cannot access 'ProductDetailApp' before initialization` where ProductDetailApp is just the name of a component that is referenced within a page's component. This seems to be a red-herring that's masking some real error but it's preventing me from seeing the actual error so it makes it very hard to debug. I've run into this a few times with different problems

### Expected Behavior

Actual error shown

### To Reproduce

I don't have time at the moment to create an isolated test case but I may update with it when I can.

**Comment by ChristianAyala** [comment]
I'm seeing something like this as well, but more on a server-side context. Prior to v12 being released, I wrote a function that wrapped a `getServerSideProps` handler and injected things like session data onto the request. That allowed a page's `getServerSideProps` function to cleanly access things like user data. Code snippet shown below:

```ts
import { withCustomMiddleware } from 'backend/with_custom_middleware';

// pages/index.tsx
export const getServerSideProps = withCustomMiddleware(
  async (context) => ({
    props: {
      user: context.req.session?.user ?? null,
    },
  })
);
```

This worked fine with v11.1.0, but breaks when upgrading to v12.0.7.

Console error shows the following:

```sh
error - ReferenceError: Cannot access 'withCustomMiddleware' before initialization
```

Function for the handler looks something like this:

```ts
export const withCustomMiddleware = (handler: GetServerSideProps) => async (context) => {
  // Executes a set of middleware, then runs the handler as the last step in the chain
}
```
