### ISSUE TITLE
web worker broken in local development

### ISSUE THREAD

**Issue by ranjeetthorat** [vercel/next.js#32537]
### What version of Next.js are you using?

12

### What version of Node.js are you using?

16

### What browser are you using?

Chrome

### What operating system are you using?

windows 10

### How are you deploying your application?

npm run dev

### Describe the Bug

While using web worker in **development mode** (_yarn dev_)  getting this  ** __webpack_require__.u  ** is not a function"  error as soon as  I initialize web worker.
While everything works fine in production mode. 

### Expected Behavior

As expected in production (yarn build && yarn start)

### To Reproduce

// main.tsx
```ts
 const workerRef = useRef<Worker>();
   useEffect( () => { 
   
     workerRef.current = new Worker( new URL( '../../workers/determineChanges.worker', import.meta.url ) );
     workerRef.current.postMessage(['hellow']);
     return () =>  workerRef.current?.terminate();
    }, [] );
 ```
 //determineChanges.worker
 ```ts
 import pi from '../libs/fetch';
 addEventListener( 'message', async ( event ) => {
    postMessage([pi]);
});
 ```
 Here is next config js
 ```ts
/** @type {import('next').NextConfig} */
module.exports = {
  eslint: {
    dirs: ['src', 'test'],
  },
  reactStrictMode: true,
};

```

**Comment by balazsorban44** [comment]
Hi, I could not reproduce your issue. We have a working example here: https://github.com/vercel/next.js/tree/canary/examples/with-web-worker

take a look and if it did not help, could you add a full reproduction?

Would be especially interesting to see what you import from `../libs/fetch`. 

Could you explain your use case?

**Comment by ranjeetthorat** [comment]
@balazsorban44  

Its seems issue is with import statement .

I am using webpack 5 (default for next12) . the import is ```../libs/fetch```
is data fetching function  
```
export default async function fetcher<JSON = any>(
  input: RequestInfo,
): Promise<JSON> {
  const res = await fetch( input, {
    credentials: 'include',
  } );
  return res.json();
}

```

If I remove import in worker.ts  I can run  in development mode also.  Imports are working in production build perfectly but not in development.

**Comment by balazsorban44** [comment]
`import` should work as well, see the example I linked to:
https://github.com/vercel/next.js/blob/canary/examples/with-web-worker/worker.js

Please link to your repo with the full code or an isolated reproduction, so I can investigate. :pray:

**Comment by talaikis** [comment]
`with-web-worker` example does not work due to `new URL()`:

```bash
webpack/runtime/compat
The "path" argument must be of type string. Received undefined
```

**Comment by balazsorban44** [comment]
I'm not sure which version you are on, but I just did `yarn create next-app -e with-web-worker web-worker-example` and it worked with no such error.

Could you try upgrading `next` maybe?
