### ISSUE TITLE
Docs: app.renderError 

### ISSUE THREAD

**Issue by stefee** [vercel/next.js#32562]
### What is the improvement or update you wish to see?

Custom servers should use app.renderError to render error pages in an error handler. This is currently undocumented.

### Is there any context that might help us understand?

https://github.com/fastify/fastify-nextjs/issues/435

https://github.com/fastify/fastify-nextjs/pull/436

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/custom-server

**Comment by stefee** [comment]
Please let me know if you'd like me to contribute these docs myself - I'd be happy to.

**Comment by nitesh-github143** [comment]
can i work on this issue

**Comment by manovotny** [comment]
@stefee @nitesh-github143 now that the [Next.js docs are open sourced again](https://nextjs.org/docs/community/contribution-guide), please feel free to submit a PR. 😊

**Comment by leerob** [comment]
Closing as stale due to low usage of the custom (ejected) server, but we can open a new issue if needed.
