### ISSUE TITLE
When I import `next/server` in pages/api/_middleware.ts, always violate `no-server-import-in-page`

### ISSUE THREAD

**Issue by KimPinot** [vercel/next.js#32586]
### What version of Next.js are you using?

12.0.6 (latest)

### What version of Node.js are you using?

14.17.3

### What browser are you using?

chrome, safari, firefox

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

When I create a `middleware.js` file in a folder over 1 depth in pages (e.g pages/api)
and import next/server there, eslint informs me that I violated 'no-server-import-in-page' (picture 1)
But when I create `middleware` on `pages/` these error doesn't shown. (picture 2)

P.S. If I must be import `next/server` right under the `pages/`, please let me know.

## `pages/api/my/_middleware.js`
![image](https://user-images.githubusercontent.com/42037851/146440841-b098e011-45cb-4912-95e2-61fcd1344997.png)

## `pages/_middleware.js`
![image](https://user-images.githubusercontent.com/42037851/146441071-0c666be9-5019-4254-a07d-0b5e6ff577bc.png)

### Expected Behavior

Errors aren't displayed when import `next/server` regardless depth in `pages/**`

#### `.eslintrc.json`
```
{
  "extends": ["next/core-web-vitals", "plugin:prettier/recommended"],
    "rules": {
      "@next/next/no-img-element": "off",
      "import/no-anonymous-default-export": "off"
    }
}
```

#### `/pages/_middleware.js`
```
// this file doesn't shown error
import { NextResponse } from "next/server";

export function middleware(req) {
  if (!req.headers.get("
    return new Response("unauthorized", {
      status: 401,
    });
  }

  NextResponse.next();
}
```

#### `/pages/api/_middleware.js`
```
// next/server should not be imported outside of pages/_middleware.js.
// See https://nextjs.org/docs/messages/no-server-import-in-page.
import { NextResponse } from "next/server";

export function middleware(req) {
  if (!req.headers.get("
    return new Response("unauthorized", {
      status: 401,
    });
  }

  NextResponse.next();
}
```

**Comment by balazsorban44** [comment]
This has been fixed in the canary branch, please upgrade `npm i next@canary` or wait until it lands in stable.

**Comment by adityar15** [comment]
it doesn't work. Event after running npm i next@canary.

My middleware is inside pages/dashboard/_middleware.js

**Comment by balazsorban44** [comment]
Make sure to update `eslint-config-next` as well!
