### ISSUE TITLE
Middleware: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by kristojorg** [vercel/next.js#32590]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.x

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When you have middleware and a web worker, all pages crash from an error in the middleware chunk.

```
ReferenceError: document is not defined
    at /Users/kristo/d/circulation-patron-web/.next/static/chunks/webpack-middleware-0775957e405959fc.js:298:36
    at /Users/kristo/d/circulation-patron-web/.next/static/chunks/webpack-middleware-0775957e405959fc.js:386:12
    at /Users/kristo/d/circulation-patron-web/.next/static/chunks/webpack-middleware-0775957e405959fc.js:391:12
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.runInNewContext (node:vm:298:38)
    at runInContext (/Users/kristo/d/circulation-patron-web/node_modules/next/dist/server/web/sandbox/context.js:69:33)
    at Object.run (/Users/kristo/d/circulation-patron-web/node_modules/next/dist/server/web/sandbox/sandbox.js:14:9)
    at Server.runMiddleware (/Users/kristo/d/circulation-patron-web/node_modules/next/dist/server/next-server.js:448:46)
```

This appears to originate from the following code in one of my `webpack-middleware` chunks:
```
/******/ 	/* webpack/runtime/jsonp chunk loading */
/******/ 	!function() {
/******/ 		__webpack_require__.b = document.baseURI || self.location.href;
```

The middleware function I added is as simple as possible:
```ts
// _middleware.ts
import { NextRequest, NextFetchEvent, NextResponse } from "next/server";

export default async function middleware(
  _req: NextRequest,
  _ev: NextFetchEvent
) {
  return NextResponse.next();
}
```

## Reproduction

Here is a reproduction:
https://stackblitz.com/edit/nextjs-v5luqm?devtoolsheight=33&file=pages/counter.js

Note:

- If you comment out the worker-counter.js import and use the workerless-counter.js instead, it works.
- If you remove the _middleware.js page, it works.
- If you import the worker, and have the middleware, no page anywhere will work.

I'm not sure how this happens, but my guess is that when webpack detects a worker, it changes how it builds in a way that is incompatible with the edge runtime. 

In my app it doesnt happen in development, only after a full build. In the repro, it also happens in dev. I also noted that the offending code is in the middleware chunk, and doesn't appear when you don't have the worker.

### Expected Behavior

The middleware chunk should not be impacted by the web worker. 

### To Reproduce

https://stackblitz.com/edit/nextjs-v5luqm?devtoolsheight=33&file=pages/counter.js

**Comment by kristojorg** [comment]
Note: In a fresh create-next-app version, two middleware files with the exact same code generate different webpack outputs. The offending code does not appear in the working example. I'm trying to determine what causes the difference right now. I have disabled all of my custom webpack config and other next.config.js extensions.

**Comment by kristojorg** [comment]
Update on this: It has to do with using a web worker in a page (any page).

Here is a reproduction:
https://stackblitz.com/edit/nextjs-v5luqm?devtoolsheight=33&file=pages/counter.js

Note:

- If you comment out the `worker-counter.js` import and use the `workerless-counter.js` instead, it works. 
- If you remove the `_middleware.js` page, it works.
- If you import the worker, and have the middleware, no page anywhere will work.

I'm not sure how this happens. In my app it doesnt happen in development, only after a full build. In the repro, it also happens in dev. I also noted that the offending code is in the middleware chunk, and doesn't appear when you don't have the worker.

**Comment by rplotkin** [comment]
I'm experiencing the same issue.

**Comment by rplotkin** [comment]
Getting more specific:
```
/* webpack/runtime/jsonp chunk loading */
/******/ 	!function() {
/******/ 		__webpack_require__.b = typeof document !== 'undefined' && document.baseURI || typeof self.location !== 'undefined' && self.location.href;
/******/
```
That line, `__webpack_require__.b`, is NOT present when the Worker code is absent.  Also, `__webpack_require__.b` is not utilized in the closure.  It is a completely unnecessary line throwing the error.

**Comment by balazsorban44** [comment]
Using your reproduction I got a different error though:
```js
> Build error occurred
ReferenceError: Worker is not defined
    at Object.199 (.../.next/server/pages/counter.js:28:16)
    at __webpack_require__ (.../.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (.../.next/server/pages/counter.js:73:39)
    at .../.next/server/pages/counter.js:74:28
    at Object.<anonymous> (.../.next/server/pages/counter.js:77:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  type: 'ReferenceError'
}
```

So this is actually not related to Middleware. Since `Worker` does not exist in Node.js, the prerendering pass at build time will error as you showed. The correct way of registering a Worker is shown in the example below:

https://github.com/vercel/next.js/blob/canary/examples/with-web-worker/pages/index.js

This will work regardless of whether you have Middleware or not.

The reason is that `useEffect` is not evaluated in the build.

I just tested this with `latest`, and the build was successful.

Based on that, here is a working example. Clicking the button will increment the `count` state:

**pages/counter.js**
```js
import React from "react"
import { wrap } from "comlink"

export default function WorkerPage() {
  const [count, setCount] = React.useState(0)
  const ref = React.useRef(null)

  React.useEffect(() => {
    const worker = new Worker(new URL("../worker.js", import.meta.url))
    ref.current = wrap(worker)
  }, [])

  return (
    <div>
      hi from worker
      <button
        onClick={async () => {
          await ref.current.inc()
          setCount(await ref.current.counter)
        }}
      >
        {count} increment
      </button>
    </div>
  )
}
```

**worker.js**
```js
import { expose } from 'comlink';

const obj = {
  counter: 0,
  inc() {
    this.counter++;
  },
};

expose(obj);
```
