### ISSUE TITLE
PORT env var is not respected when set in .env file

### ISSUE THREAD

**Issue by mbohgard** [vercel/next.js#32603]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

### Describe the Bug

Setting `PORT=4000` for ex is not respected when set in .env, .env-development etc .env files.
Loggin out `process.env.PORT` in next.config.js is reporting the correct port (4000) but the server is still starting on port 3000 (default).
The behaviour is the same with `next dev` and `next start`. 

### Expected Behavior

The server should use PORT from .env files as when started with `PORT=4000 next dev`.

### To Reproduce

1. Have a .env file in the root of the Next project with the content `PORT=4000`.
2. Start the Next dev server with `next dev`.
3. Server is starting on port 3000.

**Comment by timneutkens** [comment]
This is actually not a bug, booting the http server asap has the highest priority in `next dev` / `next start` so it happens before loading `next.config.js` / dotenv files. Looks like the documentation is not clear on that so we'll document it 👍

**Comment by mbohgard** [comment]
Ok, yeah, especially since you have a .env file example with `PORT=8080` in it 🥴 Thanks for the quick response!

**Comment by timneutkens** [comment]
That example is constructing an external API url. But can be changed

**Comment by kachkaev** [comment]
Reading all `.env*` files should take less than few milliseconds, which should not be noticeable both in `next dev` and `next start`.

```
start server
read .env*
read next.config.js
```

↓

```
read .env*
start server
read next.config.js
```

I just ran `PORT=4242 yarn dev` to avoid clashes with another server. It worked, so I moved `PORT=4242` to `.env.local`. The server launched at `3000, so I got confused and ended up here 🙂

**Comment by timneutkens** [comment]
> Reading all .env* files should take less than few milliseconds, which should not be noticeable both in next dev and next start.

With normal file reading in Node.js we already see it taking upward of 10ms+ **per-file** depending on how much is going on in the main thread, so it'll significantly slow down bootup.

**Comment by LSafer** [comment]
Will, I don't care about 1000ms so would you please add an option for those like me who don't care 😕

Also, I don't think anybody would care about 1000ms in ((production))

For development you could cache it or something like that or make it a production thing

**Comment by LSafer** [comment]
Sorry for the tuff language but I am not a native speaker and I don't know how to deliver my thoughts better than that 😅

**Comment by SCG82** [comment]
> > Reading all .env* files should take less than few milliseconds, which should not be noticeable both in next dev and next start.
> 
> With normal file reading in Node.js we already see it taking upward of 10ms+ **per-file** depending on how much is going on in the main thread, so it'll significantly slow down bootup.

@timneutkens How about adding an option to read .env before starting? https://github.com/vercel/next.js/pull/44392 solves this issue while

**Comment by manovotny** [comment]
Good callout,@mbohgard. I've made a PR (https://github.com/vercel/next.js/pull/51063) for removing `PORT=8080` from an `.env` example to avoid any confusion. 

The [documentation regarding port customization](https://nextjs.org/docs/app/api-reference/next-cli#production) has already been updated with a note that using `.env` is not currently possible, as seen below.

![CleanShot 2023-06-09 at 14 10 18@2x](https://github.com/vercel/next.js/assets/446260/101ef853-23d7-4012-a66f-3c28b6c68dd0)
