### ISSUE TITLE
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware even if I don't use functions like eval and new Function

### ISSUE THREAD

**Issue by vadimsabadosh** [vercel/next.js#32608]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

Google Chrome 96.0.4664.93

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

Whenever I use "next start" it works fine, but whenever I use "next build" I get the error:
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/_middleware

my code:
![image](https://user-images.githubusercontent.com/72106830/146565670-8d5f0845-51c0-4ca9-acf1-58d5c53f3189.png)
![image](https://user-images.githubusercontent.com/72106830/146565700-e78d7322-a4a9-4c05-8e0f-527734f32472.png)

An error:
![image](https://user-images.githubusercontent.com/72106830/146565775-dc01cd2b-9819-42b8-a645-73d0531e9567.png)

![image](https://user-images.githubusercontent.com/72106830/146566296-48e18c27-75c8-4322-a6b3-4e9e03b1ed57.png)

### Expected Behavior

next build works fine

### To Reproduce

Just repeat code in the screenshots

**Comment by balazsorban44** [comment]
I'll look into this, thanks.

_Future advise: you can add code snippets instead of screenshots for reproduction (or any other) purposes on GitHub. It is more accessible, easier to copy, easier to read on smaller devices, etc. [Read more](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

**Comment by balazsorban44** [comment]
Given your reproduction steps, I could not reproduce this locally. You might be using a third-party library that utilizes one of the unsupported APIs by the runtime. https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis

Please provide a more accurate reproduction so we can investigate further.

**Comment by vadimsabadosh** [comment]
> Given your reproduction steps, I could not reproduce this locally. You might be using a third-party library that utilizes one of the unsupported APIs by the runtime. https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis
> 
> Please provide a more accurate reproduction so we can investigate further.

Do you mean that some of these libraries can include some unsupported API's?
![image](https://user-images.githubusercontent.com/72106830/146642179-a192efb1-6bac-429b-94df-c433ee20035a.png)

**Comment by vadimsabadosh** [comment]
> Given your reproduction steps, I could not reproduce this locally. You might be using a third-party library that utilizes one of the unsupported APIs by the runtime. https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis
> 
> Please provide a more accurate reproduction so we can investigate further.

Thank you, I will check this info. Later, I will attach the result

**Comment by vadimsabadosh** [comment]
> Given your reproduction steps, I could not reproduce this locally. You might be using a third-party library that utilizes one of the unsupported APIs by the runtime. https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis
> 
> Please provide a more accurate reproduction so we can investigate further.

I have cleaned my next.config.js from third-party libraries and config looks like that
```
const path = require('path')

const nextConfig = {
	async rewrites() {
		return [
			{
				source: '/:slug(shiny-\\S*)',
				destination: '/product/:slug'
			},
			{
				source: '/:slug(diski-\\S*)',
				destination: '/product/:slug'
			},
			{
				source: '/shiny/vsesezonnye',
				destination: '/shiny/vsesezonnaja'
			}
		]
	},
	sassOptions: {
		includePaths: [path.join(__dirname, 'src/styles')],
		cssModules: true,
		prependData: `
						@import "utils/variables";
						@import "utils/mixin";
						@import "utils/include-media";
					`
	},
	images: {
		domains: ['diski-shop-dev-media.s3.amazonaws.com']
	},
	swcMinify: true,
	compress: true,
	webpack: (config, options) => {
		config.resolve.alias['~'] = path.resolve(__dirname)
		config.resolve.alias.scss = path.resolve(`${__dirname}/src/styles`)
		if (!options.isServer) {
			config.resolve.fallback.fs = false
		}
		return config
	}
}
module.exports = nextConfig

```
but I have got the error as well
![image](https://user-images.githubusercontent.com/72106830/146690634-9d5500b1-f899-4d3e-9e8b-b814cc2a9067.png)


package.json is huge, but in my files, I haven't found any third-party libraries that I used with "require" except cypress
/pages/api/__coverage__.js
```
module.exports = require('@cypress/code-coverage/middleware/nextjs')
```
![image](https://user-images.githubusercontent.com/72106830/146690695-4069c9a6-5d3d-4f0d-b385-57eb55b06bbd.png)


/cypress/plugins/index.js
```
module.exports = (on, config) => {
	// eslint-disable-next-line import/no-extraneous-dependencies,global-require
	require('@cypress/code-coverage/task')(on, config)
	return config
}

```

![image](https://user-images.githubusercontent.com/72106830/146690707-2720a3b7-9202-48b1-9fa9-a40b2c66521c.png)

package.json
![image](https://user-images.githubusercontent.com/72106830/146690777-4d31965b-8294-46c2-923f-b3c1a5869e81.png)
![image](https://user-images.githubusercontent.com/72106830/146690792-012ee285-fcf7-4406-af5a-cf93d416fd21.png)
![image](https://user-images.githubusercontent.com/72106830/146690802-23649304-5e46-4c84-b829-ecce1df9b92e.png)

**Comment by balazsorban44** [comment]
Could you show what's in your `pages/_middleware. tsx` file?

**Comment by vadimsabadosh** [comment]
> Could you show what's in your `pages/_middleware. tsx` file? That's where I meant third-parties.

![image](https://user-images.githubusercontent.com/72106830/146692302-0d872ba3-8c48-4e14-ad92-aa4e8c7176c2.png)

```
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import redirect from 'src/middleware/middlewareRedirect'

const middleware = async (req: NextRequest) => {
	return redirect(req, NextResponse)
}
export default middleware

```

middlewareRedirect.ts
![image](https://user-images.githubusercontent.com/72106830/146692338-83bdfe3c-181a-4b35-bb32-388e9846f1d1.png)

```
import type { NextRequest } from 'next/server'
// eslint-disable-next-line
const redirect = async (req: NextRequest, NextResponse) => {
	console.log(': redirect -> req', req) // to avoid an unused vars error
	return NextResponse.next()
}
export default redirect

```

**Comment by vadimsabadosh** [comment]
> Could you show what's in your `pages/_middleware. tsx` file? That's where I meant third-parties.

Hello. I found the reason for this error.
I am using cypress with istanbul plugin. And the last update of this plugin was 5 years ago.

So, in case anyone ran into this error, my solution is to remove the istanbul plugin from the .babelrc file and find another plugin.

![image](https://user-images.githubusercontent.com/72106830/146756679-491d369d-6897-4f0e-bd9e-d28d6cc58e28.png)

**Comment by Kinbaum** [comment]
@vadimsabadosh Have you implemented a workaround for this? Running into the same issue here as well, works fine in dev, throws the two same errors when running a prod build

**Comment by jordyvandomselaar** [comment]
@Kinbaum, and @vadimsabadosh Thank you both very much for suggesting a fix to an issue I'd been bashing my head on.

I wasn't importing anything but Nextjs and it still threw this error :(

Disabling Istanbul for my middleware files did it.
