### ISSUE TITLE
Add README section: "Asset Management/Optimisation"

### ISSUE THREAD

**Issue by chrisui** [vercel/next.js#3265]
It is not clear how to effectively optimise the usage and bundling of many assets within a next.js application. Typically webpack offers great power around this as you can use various loader chains to reference, load and optimise assets in place. Since the docs say to avoid adding webpack loaders when manipulating the configuration it isn't so obvious how we should go about managing assets and optimisation of those assets in an efficient manner.

There are two main parts that I see which I would love to see solutions and documentation for:

1. How do we avoid having to maintain a large global assets folder as opposed to keeping assets close to where they are actually needed? I've seen the babel-plugin suggestion however it strikes me as counter-intuitive that a babel plugin is hitting the filesystem and especially emitting new files. This seems absolutely like the job for the bundler and/or framework (what I see next.js as). *This also has the caveat that it only works for imports from js modules whereas the power we get from webpack to have any file references (ie. css `url()`) detected and managed within the dependency graph is a huge win.*
2. How should we optimise these assets when building or developing a next.js application?

Is it on the roadmap to improve the asset management story of next.js? The more decisions about this stuff that can be moved away from user code (great example being needing to prefix CDN urls manually) the better.

**Comment by lachlanjc** [comment]
This issue is super old now…I don’t think we exactly have docs on this besides https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix but we do have the Image Optimization, & I think the landscape has shifted here with static generation & CMSs. Is there more to do here?

**Comment by molebox** [comment]
@balazsorban44 is this still relevant? If not, can we close please 🙏
