### ISSUE TITLE
`yarn create next-app` fails when directory is a workspace

### ISSUE THREAD

**Issue by karbica** [vercel/next.js#32713]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next export

### Describe the Bug

With the following project structure:

```
.
├── node_modules
├── package.json
├── sites # this is a workspace
└── yarn.lock
```

And with the following `package.json`:
```json
{
  "name": "workspace-test",
  "version": "1.0.0",
  "private": true,
  "license": "MIT",
  "workspaces": [
    "sites/*"
  ]
}
```

Running this command fails:
```bash
yarn create next-app sites/hello-world
```

With this following output:
```
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-next-app@12.0.7" with binaries:
      - create-next-app
[##] 2/2Creating a new Next.js app in /Users/karbi/dev/workspace-test/sites/hello-world.

Using yarn.

Installing dependencies:
- react
- react-dom
- next

yarn add v1.22.17
warning Missing version in workspace at "/Users/karbi/dev/workspace-test/sites/asd", ignoring.
warning Missing version in workspace at "/Users/karbi/dev/workspace-test/sites/hello-world", ignoring.
error An unexpected error occurred: "Cannot read properties of undefined (reading 'manifest')".
info If you think this is a bug, please open a bug report with the information provided in "/Users/karbi/dev/workspace-test/sites/hello-world/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Expected Behavior

I would expect that following command would produce a successful boilerplate without error:
```bash
yarn create next-app sites/hello-world
```

Additionally, running the following command works successfully when not targeting a workspace:
```bash
yarn create next-app hello-world
```

To note, using `npx` works successfully:
```bash
npx create-next-app sites/hello-world
```

### To Reproduce

Clone [this repository](https://github.com/karbica/workspace-test) and run the following command in the project root:
```bash
yarn create next-app sites/hello-world
```
<img width="1233" alt="Screen Shot 2021-12-21 at 1 20 09 PM" src="https://user-images.githubusercontent.com/8563742/147000196-d2278207-0c00-4d78-8782-f5032493bc98.png">

**Comment by SergeyMell** [comment]
Same issue for me

**Comment by MISSOURI10101** [comment]
The problem is when you install dependencies in `"hello-world"` , the package json created in this folder has not the` version` attribute 


In the next souce code : 

 ```
const packageJson = {
      name: appName,
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
      },
```
so there is two solution , either specify version in this object or try to know if there is nested folder and should add version in the package json

**Comment by karbica** [comment]
@MISSOURI10101 
Yep, removing the version number seems to be causing the issue. Also, the `version` field [was present](https://github.com/vercel/next.js/blob/v12.0.1/packages/create-next-app/create-app.ts#L206) in `v12.0.1` but was removed in `v12.0.2`.

Here is a [related issue](https://github.com/yarnpkg/yarn/issues/5936) to workspaces not having their dependencies installed if their version is omitted. It was fixed in `yarn@v2` but still broken for `yarn@v1`.

I believe `version` should be placed back into the `packageJson` object with a `0.0.0` (or `0.1.0`, as `npx` does) value for backwards compatibility. And if the developer wants to omit it, then they are free to do so.

Also to note, I now see the reason why `npx` works is because it defaults with `0.1.0` as the `version` in the `package.json` upon app creation.

**Comment by JDtheGeek** [comment]
Just ran into this exact issue.  npx version worked due to passing a version
