### ISSUE TITLE
Issue with `asPath` when using `getStaticProps` and redirects

### ISSUE THREAD

**Issue by nbouvrette** [vercel/next.js#32772]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Verel

### Describe the Bug

When using redirects in `next.config.js` and trying to output `router.asPath` in a dynamic route that is using `getStaticProps` and `getStaticPaths`, we are getting a `Warning: Text content did not match. Server: "/test-static/123" Client: "/test-statique/123"` message in the console. This is not an issue when using `getServerSideProps`.

### Expected Behavior

There should not be any discrepancy between the server and client markup. Basically, we should get the same result as with `getServerSideProps`.

## How to reproduce

Clone the example repo:
```bash
git clone https://github.com/nbouvrette/next-js-test-aspath
```

Run Next.js
```bash
npm run dev
# or
yarn dev
```

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

Inspect your page, and make sure to open the `console` tab in your browser to see logs.

### Happy path

If you click on the first link.

Both SSR and client-side `asPath` matches when using `getServerSideProps` - no error is shown in the logs.

### Issue with `asPath`

If you return back, and click on the second link you should see the following error in your console:

```console
next-dev.js?3515:32 Warning: Text content did not match. Server: "/test-static/123" Client: "/test-statique/123"
    at div
    at TestStatic (webpack-internal:///./pages/test-static/[id].tsx:16:72)
    at MyApp (webpack-internal:///./pages/_app.tsx:36:27)
    at StyleRegistry (webpack-internal:///./node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:90:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:356:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:795:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:916:27)

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

If you do a `view page source` you will see that the SSR markup is `/test-static/123` when in fact it should be using `/test-statique/123` as per the `redirects` configuration in `next.config.js`.

**Comment by balazsorban44** [comment]
You are using regular `<a>` when navigating, which won't resolve correctly. The correct way in your case would be:

```jsx
import type { NextPage } from "next"
import Link from "next/link"
const Home: NextPage = () => {
  return (
    <div>
      <Link href="/test-cote-serveur/123" locale="fr">
        Server side test, should show: /fr/test-cote-serveur/123
      </Link>
      <br></br>
      <Link href="/test-statique/123" locale="fr">
        Static test, should show: /fr/test-statique/123
      </Link>
    </div>
  )
}

export default Home
```

https://nextjs.org/docs/api-reference/next/link

**Comment by nbouvrette** [comment]
@balazsorban44 hey this was not about `<Link>` the `<a>` were in the example by design - I should have provided better reproduction steps but if you run the example repo, and hit the following URL: http://localhost:3000/fr/test-statique/123

You will see the error in the console logs... the links on the homepage were only there to facilitate the testing and `<a>` was used to avoid a client-side page change (basically hitting the URL to reproduce the error on first page load)

**Comment by balazsorban44** [comment]
That's because the `rewrites` are wrong. You should return the `test-static` part as dynamic, and make sure `getStaticPaths` return it correctly.

```js
export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [
      {
        params: {
          "test-static": "test-statique",
          id: "123", // This is the default `id` of the test page.
        },
        locale: "fr",
      },
    ],
    fallback: "blocking",
  }
}
```

And just remove the rewrite.

**Comment by balazsorban44** [comment]
Thanks for pointing out the missing documentation, I'll note the team.

On the second look, I don't think you actually need to define the paths in `getStaticPaths` though. Any request to `/fr` will indicate Next.js that you are on `router.locale === "fr"`

**Comment by nbouvrette** [comment]
@balazsorban44 yes, the example is probably not a good one for static paths since it uses an `id` but I was just trying to reproduce the behavior. 

If we imagine another example where you have possibly 2-3 valid values for the parameter and would like to statically generate these pages for speed, then from what you are saying you would need to include the path for each locale as passing the parameter only will not work.

In my scenario this would be quite fragile since the URLs are managed elsewhere - maybe I should re-open this ticket under a new feature but it looks like a potential unlikely edge-case with debatable value :)

**Comment by nbouvrette** [comment]
@balazsorban44 by the way I did further tests and

```js
params: {
  "test-static": "test-statique",
  id: "123", // This is the default `id` of the test page.
},
locale: "fr",
```

still triggers the warning in the console log, when running `npm run dev`. I've noticed that one way I could get rid of the warning, was using the original repo `getStaticPaths` values (without the path) and using `npm run build` followed by `npm run start`.

So this looks mostly like an inconsistent behavior when running in dev mode...

Of course, another way I can rid of this warning is by completely removing `getStaticPaths` and `getStaticProps` which means the static optimization will not work.

**Comment by nbouvrette** [comment]
Oh one last thing, when I replace `getStaticPaths` and `getStaticProps` by 

```
export const getServerSideProps: GetServerSideProps = async () => {
  return { props: {} }; // Empty properties, since we are only using this to get the query parameters.
};
```

The SSR for `/fr/test-statique/123` is correctly hydrated on `asPath` with `/fr/test-statique/123` and matches the client side value too.

**Comment by nbouvrette** [comment]
@balazsorban44 I think we should re-open this because this issue was not a documentation problem.

**Comment by ijjk** [comment]
@nbouvrette this behavior seems expected, you are rewriting to a static path which is prerendered so the `asPath` won't be updated until on the client. See related documentation around the `asPath` caveat added in https://github.com/vercel/next.js/pull/36876

**Comment by nbouvrette** [comment]
I just updated the [repo](https://github.com/nbouvrette/next-js-test-aspath) I created just to reproduce this issue with the latest packages and I confirm that `asPath` is still problematic when using `getStaticProps`.

Just to make sure I understand, you are basically saying that Next.js does not plan to make the server-side `asPath` match the client-side `asPath` when using `getStaticProps`? 

Is there a technical reason for this decision? It does look to me like a bug or at least something that would deserve a feature request unless this design is there intentionally?

From what I can tell, with the current solution, there is no way to get the correct SSR value for `asPath` when using `getStaticProps`.

**Comment by nbouvrette** [comment]
@ijjk not sure if you saw my last comment? I forgot to tag you

**Comment by ijjk** [comment]
The `asPath` does match as long as the requested path is what is statically generated, the problem is you are rewriting a non-matching path to a static path. The `asPath` will be the path that is statically generated. If you need the `asPath` to match uniquely to each request then `getServerSideProps` should be used. `getStaticProps` is not meant to be unique per request but instead unique per-path.
