### ISSUE TITLE
The Edge Function "map" is 1.13mb which exceeds the maximum size limit of 1mb.

### ISSUE THREAD

**Issue by jlarmstrongiv** [vercel/next.js#32907]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

v14.17.0

### What browser are you using?

CLI

### What operating system are you using?

macOS

### How are you deploying your application?

vercel cli

### Describe the Bug

> This is an experimental feature in Next.js 12, but once enabled, SSR will use the same Edge Runtime as Middleware.

The Edge Runtime breaks my code, as:
> The Edge Function "map" is 1.13mb which exceeds the maximum size limit of 1mb.

Related to https://github.com/vercel/next.js/issues/31317

### Expected Behavior

I should be able to enable `concurrentFeatures: true` and publish my project to vercel, without triggering the different runtime.

Quite frankly, the 1mb limit is just too small.  Using threejs libs, d3 libs, material-ui, and accessibility libs easily pushes me above the limit.  Using next/dynamic, adding sideEffects: false, and other techniques have no effect on the size.  

I also tried using cdns with nextjs like https://betterprogramming.pub/next-js-reducing-bundle-size-when-using-third-party-libraries-db5407252d59 suggests, but that did not work either.  

Even if you do manage to somehow reduce the file size, then you will still run into https://github.com/vercel/vercel/discussions/6931

### To Reproduce

N/A

**Comment by balazsorban44** [comment]
> Using threejs libs, d3 libs, material-ui, and accessibility libs easily pushes me above the limit

Most npm packages probably won't work immediately, since this is not run in Node.js.

Do you have an example code of what you are trying to do that exceeds this limit?

**Comment by jlarmstrongiv** [comment]
@balazsorban44 Funny you say that, I actually have to keep all the NodeJS code separated anyway, otherwise it’ll just crash.  It’s going over the limit by bundling browser libs at 1.13mb for a visualization.  

For investigation, can I give you a link to a Vercel failed build?  Is there a way to download the Vercel failed build source?  The build is actually part of a larger homegrown monorepo with tooling that will not be easy to separate and share.

**Comment by nyinyithann** [comment]
I am also getting the following error when i turn on `concurrentFeatures: true` and deploy to vercel.

`Error: The Edge Function "index" is 1.66mb which exceeds the maximum size limit of 1mb. Learn More: https://vercel.link/edge-function-size`

**Comment by Ali-Hussein-dev** [comment]
Having the same issue after upgrading to `12.0.10`


![clients – Deployment Overview](https://user-images.githubusercontent.com/42802922/152390599-a85acb8e-b0ff-49d6-8c21-a02e306fda1c.png)

**Comment by balazsorban44** [comment]
@Ali-Hussein-dev are you able to share the `api/_middleware` so we can see what dependencies are you using? Do you have any concurrent features enabled?

**Comment by Ali-Hussein-dev** [comment]
@balazsorban44 here is the link to the issue with the code https://github.com/vercel/next.js/issues/34201

**Comment by shuding** [comment]
Closing this as we shipped a lot of optimizations recently:
- #38570
- #39560
- #39548
- #39433
- #39044

Let us know if you are still running into this issue and we can reopen it, thanks!
