### ISSUE TITLE
Deploying nextjs on multiple instance result in different build files on each server

### ISSUE THREAD

**Issue by cyzanfar** [vercel/next.js#32956]
### What version of Next.js are you using?

10.1.2

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

next build && next start -p $PORT on AWS EBS

### Describe the Bug

I use AWS Elasticbeanstalk to host my application behind a load balancer. When I scale my application from 1 instance to 2 instance, the build files generated by next are not the same in both instance, resulting in 404 errors:

This file only exist on one of the instance:
https://example.com/_next/static/chunks/pages/personal-information-0cc9b5545e1107d69f10.js

the other instance has this file:
https://example.com/_next/static/chunks/pages/personal-information-f73dfe8ac657b9e7818b.js

Notice the value is different after `personal-information-`

This inconsistency in the filename results in errors in my browser such as:

```
Request URL: https://example.com/_next/static/chunks/pages/personal-information-0cc9b5545e1107d69f10.js
Request Method: GET
Status Code: 404
```

Should the file name be the same if nothing has changed? This current setup is problematic when running multiple instances for the same application.

### Expected Behavior

The file names should be the same if no code has changed

### To Reproduce

Deploy a next js app on 2 instance, here's my script in package.js:
```
 ...
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next build && next start -p $PORT"
  },
  ...
  ```

**Comment by balazsorban44** [comment]
Make sure you are using Webpack 5 by upgrading to a newer version of Next.js. 

It introduced deterministic hashes whenever the content has not changed.

https://nextjs.org/blog/next-9-5#webpack-5-support-beta

**Comment by tractorcow** [comment]
I had the same issue, and came to the same conclusion; Use an EFS filesystem for sharing artifacts and handling incremental updates (e.g. next image caches and so on).

**Comment by tractorcow** [comment]
@cyzanfar try setting up a deterministic build_id as well; Without an EFS that might still get you most of the way.

I write my release version to a TXT file and then run this 

```js
  generateBuildId: () => {
    // Use version.txt generated during release
    const releasePath = path.join(__dirname, 'public', 'version.txt');
    return fs.existsSync(releasePath) ? fs.readFileSync(releasePath, 'utf8') : null;
  }
```


EFS turns out to be a problem if you scale multiple nodes at the same time (and each try to build to a shared folder).
