### ISSUE TITLE
Incorrect symlinks when using experimental.outputFileTracingRoot

### ISSUE THREAD

**Issue by ashleypcheng** [vercel/next.js#32987]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other

### Describe the Bug

We are trying to use Next.js 12's output file tracing feature https://nextjs.org/blog/next-12#output-file-tracing to speed up building our Docker image and reduce the Docker image size when deploying our application. We are planning to leverage this feature so that we would not have to install dependencies when building our Docker image. However, after enabling `outputStandalone` and using `outputFileTracingRoot` in next.config.js like so:

```js
module.exports = {
  experimental: {
    outputStandalone: true,
    // this includes files from the monorepo base two directories up
    outputFileTracingRoot: path.join(__dirname, '../../'),
  },
}
```

The build output's symlinks seem to have the outputFileTracingRoot path removed from them. 

After digging into the code where the symlinks are created, it looks like it is using the relative path between tracing root and the actual symlink https://github.com/vercel/next.js/blob/e01ef297e757f0435f82348496e68eb6919826a8/packages/next/build/utils.ts#L1194. For example, if the tracing root is `../..` then it will remove that from the new symlinks in the standalone build output. I think it should use the existing symlink instead of getting the relative path since it is copying over the files from the tracing root.

### Expected Behavior

Symlinks should be kept as is instead of the relative path between the existing symlink and tracing root. 
So instead of 
`await fs.symlink(
              path.relative(tracingRoot, symlink),
              fileOutputPath
            )`
it should be
`await fs.symlink(
              symlink,
              fileOutputPath
            )`

### To Reproduce

1. In a mono repo where the next.js app is one of the packages, update next.config.js to include:
```js
module.exports = {
  experimental: {
    outputStandalone: true,
    // this includes files from the monorepo base two directories up
    outputFileTracingRoot: path.join(__dirname, '../../'),
  },
}
```
2. build the app using `next build`
3. in the console, navigate to the .next directory for the standalone build output and find a symlink in the app package's node_modules
4. use `ls -l <symlink>` to view the target path
5. notice that the target path is not pointing to the actual file location but is missing the relative path to the tracing root.

**Comment by remorses** [comment]
Also `outputStandalone` should not create symlinks for files outside `outputFileTracingRoot` and instead copy them in the `standalone` directory
