### ISSUE TITLE
Add Clarity About Downloading and Self-Hosting a Font File

### ISSUE THREAD

**Issue by MaedahBatool** [vercel/next.js#33054]
### What is the improvement or update you wish to see?

> They’re asking if you should download and “self host” the font file, or if you should include a link in your head to fetch it from a CDN like Google Fonts. If you self-host, our font optimization does not work

Add details on how users can download and handle self-hosted fonts. 

### Is there any context that might help us understand?

Reference [Slack Thread](https://vercel.slack.com/archives/C02F56A54LU/p1641320082221000)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/font-optimization

**Comment by molebox** [comment]
Hey @MaedahBatool whats the status of this?

**Comment by MaedahBatool** [comment]
> Hey @MaedahBatool whats the status of this?

@molebox [PR done](https://github.com/vercel/next.js/pull/33760) ✅
