### ISSUE TITLE
Cannot access runtime variables in middlewares

### ISSUE THREAD

**Issue by fdc-viktor-luft** [vercel/next.js#33068]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: 6.25.0
    Relevant packages:
      next: 12.0.8-canary.18
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8-canary.18

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

I cannot access any runtime variables inside `_middleware.ts` files.

### Expected Behavior

I want to access runtime variables in middlewares.

I couldn't find any documentation about this and hence can only hope that it is a bug and will be fixed. Currently I can only use `process.env.FOO` inside middlewares but that are build time variables, which is not ideal, because I'd prefer to use here server runtime variables.

### To Reproduce

Inside `_middleware.ts`:
```ts
import { NextFetchEvent, NextRequest, NextResponse } from 'next/server';
import getConfig from 'next/config';

// outside the middleware export
console.log(getConfig());

// inside the middleware export (doesn't matter)
export function middleware(request: NextRequest, _event: NextFetchEvent) {
    console.log(getConfig());
    return NextResponse.next();
}
...
```
Always logs `undefined` as any runtime config seems to be not accessible in middlewares.

**Comment by balazsorban44** [comment]
https://nextjs.org/docs/api-reference/next/server#how-do-i-access-environment-variables

**Comment by fdc-viktor-luft** [comment]
@balazsorban44 Didn't you read my bug report carefully enough? There is a difference between **runtime** and **build time** environment variables. Your link doesn't help at all.

**Comment by balazsorban44** [comment]
My bad for not explaining. So the docs says:

> These are evaluated at build time, so only environment variables actually used will be included.

Meaning there is way to read in environment variables at runtime.

**Comment by fdc-viktor-luft** [comment]
However, I found an ugly workaround. At least as tip for the docs: You should mention on the "Middleware" docs that "next/config" is not working and maybe also why it is not working.

**Comment by IamBlueSlime** [comment]
Hi @fdc-viktor-luft, I have the same issue for a project, what was your workaround here? Maybe you could help me out with this :)

**Comment by fdc-viktor-luft** [comment]
@IamBlueSlime I'm still struggling with it, because it seems that my workaround was not really working.

### I was doing the following:
- Generate a JSON file right before "next build" and putting it into `node_modules/my-generated/config.json`
- Importing in the middleware via `import Config from 'my-generated/config.json'`

### The problem:
I needed to create another dummy JSON to run the "next build" successfully. Since middleware code runs only on backend site and I found in the generated code some `webpack_require('my-generated/config.json')` (or something similar) I was assuming that I could update the placed JSON file on Server-Startup. But actually `webpack_require` does not use the `node_modules` directory but uses a pre-bundled version of that JSON. So I had no influence.

### Current "solution"
Now I need to take the Build-Time environment variable, which is pretty sad, because I cannot imagine that it would be hard to support the Runtime-Env for the NextJS team inside middlewares. But maybe @balazsorban44 can explain the reasons why they don't want to support it.
