### ISSUE TITLE
Rule no-unwanted-polyfillio wrongly reports error on es2019 rule

### ISSUE THREAD

**Issue by jdeniau** [vercel/next.js#33072]
### What version of Next.js are you using?

11.1.0 or 12.0.0

### What version of Node.js are you using?

14.18.0

### What browser are you using?

Chrome 67

### What operating system are you using?

Windows

### How are you deploying your application?

other platform

### Describe the Bug

The eslint rule [no-unwanted-polyfillio](https://github.com/vercel/next.js/blob/canary/errors/no-unwanted-polyfillio.md) wrongly report es2019 as duplicate.

All `esXXX` rule are marked as [Should be covered by babel-preset-env instead.](https://github.com/vercel/next.js/blob/canary/packages/eslint-plugin-next/lib/rules/no-unwanted-polyfillio.js#L52-L59).

My babel configuration is the following:

```js
module.exports = {
  presets: ['next/babel'],
  plugins: ['styled-components'], // See https://github.com/brandonchinn178/next.js/blob/master/examples/with-styled-components/.babelrc
};
```

So I think this is pretty much the default config. I did not customize anything about babel-preset-env

I tried with a boostraped nextjs 12 and swc (without babel configuration) and the issue is the same.

### Expected Behavior

Either do not report as an error, or possibly fix the babel configuration if needed ?

If we only need to fix the eslint rule, I can open a PR. If the fix is on the babel side, I will need some help there.

### To Reproduce

Reproductible repository : https://github.com/jdeniau/nextjs-object-fromentries

Open a chrome <= 71 (or any browser that [does not support `Object.fromEntries`](https://caniuse.com/mdn-javascript_builtins_object_fromentries)) and try to run a nextjs app with the following code.

```js
Object.fromEntries([]);
```

It will crash with an error:
```
Object.fromEntries is not a function
```

**Comment by balazsorban44** [comment]
Hi. We decided not to add a polyfill to not penalize most users with the increased size.

See the discussion here: https://github.com/vercel/next.js/pull/15772#discussion_r463984612

**Comment by jdeniau** [comment]
@balazsorban44 OK, so I think that we should remove it from the polyfillio rule then.

If I'm correct, all next-js polyfill are loaded in https://github.com/kripod/next.js/blob/076c0275d0133db2f8e7e8dc68f6cb2f2bd1a159/packages/next-polyfill-nomodule/src/index.js so the `NEXT_POLYFILLED_FEATURES` should contain a copy of those polyfill, no ?

If so, I can open a PR fixing this.

**Comment by balazsorban44** [comment]
I think just returning early if the polyfill is for `fromEntries` might be enough, but yeah. 

https://github.com/kripod/next.js/blob/canary/packages/next-polyfill-nomodule/src/index.js

Here is the ESlint rule:

https://github.com/kripod/next.js/blob/canary/packages/eslint-plugin-next/lib/rules/no-unwanted-polyfillio.js

And the test file should probably have a case for this as well:

https://github.com/kripod/next.js/blob/canary/test/eslint-plugin-next/no-unwanted-polyfillio.unit.test.js

**Comment by jdeniau** [comment]
I think that there might be other rule than `from Entry`, that's why I will took some time to check every rules and not just fix my use case. 👍
