### ISSUE TITLE
ReferenceError: fetchData is not defined

### ISSUE THREAD

**Issue by mjr** [vercel/next.js#33088]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 14.18.2
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.8-canary.19
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8-canary.19

### What version of Node.js are you using?

14.18.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

After upgrading `next` to version 12 i get a `ReferenceError: fetchData is not defined` when using early return without braces inside useEffect, in version 11 it works as expected.

Running the `next` command in development works as expected, but `next build` and `next start` the error happens.

```javascript
React.useEffect(() => {
  if (query === '') return

  function getFetchUrl() {
    return 'https://hn.algolia.com/api/v1/search?query=' + query
  }

  async function fetchData() {
    const res = await fetch(getFetchUrl())
    const data = await res.json()
    setData(data)
  }

  fetchData()
}, [query])
```

<img width="1280" alt="next-bug" src="https://user-images.githubusercontent.com/9324986/148583886-82e9be6b-a973-4927-ac06-c5a062901bef.png">

### Expected Behavior

Expected to work without the need to add braces.

### To Reproduce

Clone this project https://github.com/mjr/next-bug.
Run `next build` and then `PORT=3000 next start`.
Open `localhost:3000` e open the console to see the error.

**Comment by balazsorban44** [comment]
The issue seems to be related to `swcMinify: true`. I added this to our backlog. In the meantime, `swcMinify: false` should help you out.
