### ISSUE TITLE
RSC: process is not the real process object 

### ISSUE THREAD

**Issue by mohsen1** [vercel/next.js#33122]
<details>
<summary>Environment info</summary>

### Run `next info` (available from version 12.0.8 and up)

I think 12.0.8 is not published...
```ts
npm i next@12.0.8                          
npm ERR! code ETARGET
npm ERR! notarget No matching version found for next@12.0.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
```

### What version of Next.js are you using?

`^12.0.8-canary.11`
### What version of Node.js are you using?

12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

N/A

</details>

I believe I'm getting Webpack's fake `process` module when requiring process (`require("process")`) and `process` global object contains only the `env` object. 

### Expected Behavior

I'm expecting the real `process` in server components. 

### To Reproduce

In a server component try to print `process.version` for instance 

```js
// test.server.js

export default () => <p>{process.version}</p>
```

**Comment by balazsorban44** [comment]
Just curious, what's your use case @mohsen1?

**Comment by mohsen1** [comment]
Many packages examine the process object to detect if they are in the server vs. client mode. In my case Prisma Client thinks I'm running the code in browser.

**Comment by huozhi** [comment]
It's pretty related to the runtime so far. Til now (the time I commnent) it's running on the edge (a web like runtime) if you're using RSC with next.js. So it uses a browser polyfilled one. After bringing nodejs runtime into RSC, the `process` could be the nodejs runtime `process`.

Hope this answers your question.
