### ISSUE TITLE
Build fails in Ubuntu server with error "ESLint: Failed to load plugin 'react' declared in '.eslintrc.json"

### ISSUE THREAD

**Issue by azakero** [vercel/next.js#33156]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: linux
      Arch: x64
      Version: #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021
Binaries:
      Node: 14.18.2
      npm: 8.3.0
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 12.0.8-canary.19
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8-canary.19

### What version of Node.js are you using?

14.18.2

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04 VPS

### How are you deploying your application?

-

### Describe the Bug

I have posted this in So I've been trying to deploy a Next app to my Ubuntu 20.04 VPS but I'm unable to build the app in my server. Unable to run the app in development mode as well. 

I've uploaded all the files from my local machine to the server via ftp and then after installing the dependencies and running `npm run dev`, this is what I'm getting: 

```
[20:09] [server1.example.com boomboom] # npm run dev

> boomboom@0.1.0 dev
> next dev

warn  - Port 3000 is in use, trying 3001 instead.
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
info  - Loaded env from /home/user1/node-apps/boomboom/.env.local
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[4].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[4].use[2]!./styles/Footer.module.css
/home/user1/node-apps/boomboom/node_modules/source-map/lib/util.js:101
        // above the root is a no-op. Therefore we can remove all '.

SyntaxError: Unexpected end of input
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: SyntaxError: /home/user1/node-apps/boomboom/node_modules/mongodb-connection-string-url/node_modules/whatwg-url/package.json (directory description file): SyntaxError: Unexpected end of JSON input
<w> while resolving 'whatwg-url' in /home/user1/node-apps/boomboom/node_modules/mongodb-connection-string-url to a directory
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: SyntaxError: /home/user1/node-apps/boomboom/node_modules/mongodb-connection-string-url/node_modules/whatwg-url/package.json (directory description file): SyntaxError: Unexpected end of JSON input
<w> while resolving 'whatwg-url' in /home/user1/node-apps/boomboom/node_modules/mongodb-connection-string-url to a directory
```

Then after trying with `npm run build`, this is what I get:

```
[20:13] [server1.example.com boomboom] # npm run build

> boomboom@0.1.0 build
> next build

info  - Loaded env from /home/user1/node-apps/boomboom/.env.local
info  - Checking validity of types
error - ESLint: Failed to load plugin 'react' declared in '.eslintrc.json » eslint-config-next/core-web-vitals » /home/user1/node-apps/boomboom/node_modules/eslint-config-next/index.js': Cannot find module 'eslint-plugin-react' Require stack: - /home/user1/node-apps/boomboom/node_modules/eslint-config-next/index.js Referenced from: /home/user1/node-apps/boomboom/node_modules/eslint-config-next/index.js

> Build error occurred
/home/user1/node-apps/boomboom/node_modules/source-map/lib/util.js:101
        // above the root is a no-op. Therefore we can remove all '.


SyntaxError: Unexpected end of input
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/user1/node-apps/boomboom/node_modules/source-map/lib/source-map-generator.js:9:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
info  - Creating an optimized production build .[20:13] [server1.example.com boomboom] #

```

This is how my package.json file looks like:

```
{
        "name": "boomboom",
        "version": "0.1.0",
        "private": true,
        "scripts": {
                "dev": "next dev",
                "build": "next build",
                "start": "next start",
                "lint": "next lint"
        },
        "dependencies": {
                "axios": "^0.24.0",
                "fabric": "^4.6.0",
                "fuse.js": "^6.4.6",
                "material-ui-color": "^1.2.0",
                "mongoose": "^6.0.13",
                "next": "^12.0.8-canary.19",
                "rc-input-number": "^7.3.3",
                "react": "17.0.2",
                "react-dom": "17.0.2",
                "react-dropdown": "^1.9.2",
                "react-image-size": "^1.0.4",
                "react-redux": "^7.2.5",
                "redux": "^4.1.1",
                "redux-devtools-extension": "^2.13.9",
                "redux-thunk": "^2.3.0",
                "shortid": "^2.2.16"
        },
        "devDependencies": {
                "eslint": "7.32.0",
                "eslint-config-next": "11.1.2"
        }
}
```

### Expected Behavior

Run the app (in dev mode) as well as build the app in my vps .

### To Reproduce

I don't know how it can be reproduced.

**Comment by balazsorban44** [comment]
By any chance, are you copying the files from Windows?

Windows and Linux have different file endings, that could be an issue. Although I cannot confirm without a reproduction.

**Comment by azakero** [comment]
Yes. I mean I transferred the files from Windows via Filezilla. 

Previously, I had a different issue which you can see here in this post: https://github.com/vercel/next.js/discussions/33121. Then I was told by someone that it could be because of low ram. Then I stopped other apps in my vps and then successfully installed the dependencies. Now the issue is with the build.

I don't know how this can be reproduced. I am really sorry about that.

**Comment by balazsorban44** [comment]
For starters, try creating an app with our CLI tool https://nextjs.org/docs/api-reference/create-next-app (this created a minimal Next.js app) and see if transferring it the same way reproduces it. If it doesn't, the issue might be in your configuration/code somewhere.

**Comment by azakero** [comment]
I tried reproducing the issue by creating an app and installing only the dependencies which I have in my original app. It installed successfully but npm run dev and npm run build stops with 'Bus Error'. 

If you check the build error above, it has something to do with eslint. 

`error - ESLint: Failed to load plugin 'react' declared in '.eslintrc.json » eslint-config-next/core-web-vitals » /home/user1/node-apps/boomboom/node_modules/eslint-config-next/index.js': Cannot find module 'eslint-plugin-react' Require stack: - /home/user1/node-apps/boomboom/node_modules/eslint-config-next/index.js Referenced from: /home/user1/node-apps/boomboom/node_modules/eslint-config-next/index.js
`
I even updated eslint and eslint-config-next to the latest versions, but the issue is still there. 

Right now the eslint error is slightly different: 

`
error - ESLint: Failed to load plugin 'import' declared in '.eslintrc.json » eslint-config-next/core-web-vitals » /home/zakero/node-apps/boomboom/node_modules/eslint-config-next/index.js': Cannot find module 'tsconfig-paths/lib/tsconfig-loader' Require stack: - /home/user1/node-apps/boomboom/node_modules/eslint-plugin-import/lib/ExportMap.js - /home/user1/node-apps/boomboom/node_modules/eslint-plugin-import/lib/rules/named.js - /home/user1/node-apps/boomboom/node_modules/eslint-plugin-import/lib/index.js - /home/user1/node-apps/quotesverse/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
`

**Comment by balazsorban44** [comment]
This does not sound like a Next.js bug.

A quick search on "Bus error" lead me to this: https://github.com/npm/npm/issues/1035

Also, all those syntax errors seem to suggest there is some weird stuff going on with file endings. It is most likely that when you build/install on Windows, these endings won't work on Linux. 

I found this article: https://medium.com/@csmunuku/windows-and-linux-eol-sequence-configure-vs-code-and-git-37be98ef71df

I would debug around that.
