### ISSUE TITLE
Docs: How is NextRequest get populated?

### ISSUE THREAD

**Issue by zmarty** [vercel/next.js#33195]
### What is the improvement or update you wish to see?

I cannot find documentation on how geo in NextRequest is populated. Is this a Vercel hosting only feature? Or can we provide some geolocation headers from the load balancer?

<img width="473" alt="image" src="https://user-images.githubusercontent.com/330396/149007485-fa2cde49-6c76-43b5-b0a0-69c9b3b6077b.png">

### Is there any context that might help us understand?

I was reading the new middleware and next/server documentations. I also checked the code but I could not find anything other than the data type.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/server

**Comment by balazsorban44** [comment]
Thank you for pointing this out.

We will make this more clear in the docs. There are platforms (like Vercel) that will provide this information out-of-the-box, otherwise, you will have to figure out if your platform is able to provide that information.

**Comment by zmarty** [comment]
Thanks @balazsorban44

1) So... are those extracted from headers or somehow differently?
2) Would it technically be possible to have a _middleware in the root folder that somehow defines this geo information so that subsequent middleware can use them as described in the docs?

**Comment by molebox** [comment]
Fixed in https://github.com/vercel/next.js/pull/33609
