### ISSUE TITLE
Stylesheet not working in a component under Head tag 

### ISSUE THREAD

**Issue by kepes** [vercel/next.js#33196]
### Run `next info` (available from version 12.0.8 and up)

sh: 1: pnpm: not found

    Operating System:
      Platform: linux
      Arch: x64
      Version: #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
    Binaries:
      Node: 16.12.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.8-canary.20
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8-canary.20

### What version of Node.js are you using?

16.12.0

### What browser are you using?

Chrome/codesandbox

### What operating system are you using?

Ubuntu

### How are you deploying your application?

codesandbox

### Describe the Bug

When I put Stylesheet inside <HEAD> tag it works fine but If I move Stylesheet to a separate component (called HeadMeta) stylesheet not loaded and completly missing from DOM tree.

Check the Google `Roboto` font in the source!

This works:
```js
<Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content={siteDescription} />
        <meta
          property="og:image"
          content={`https://og-image.vercel.app/${encodeURI(
            siteTitle
          )}.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg`}
        />
        <meta name="og:title" content={siteTitle} />
        <meta name="twitter:card" content="summary_large_image" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
```

this isn't:

```js
<Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content={siteDescription} />
        <meta
          property="og:image"
          content={`https://og-image.vercel.app/${encodeURI(
            siteTitle
          )}.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg`}
        />
        <meta name="og:title" content={siteTitle} />
        <meta name="twitter:card" content="summary_large_image" />
        <HeadMeta />

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
```

HeadMeta.js
```js
import * as React from "react";

function HeadMeta() {
  return (
    <React.Fragment>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      />
    </React.Fragment>
  );
}

export default HeadMeta;

```

### Expected Behavior

Roboto font loads when stylesheet is in separate component.

### To Reproduce

Move stylesheet into separate component inside `<Head>` component.

```js
<Head>
        <HeadMeta />
</Head>
```

HeadMeta.js
```js
import * as React from "react";

function HeadMeta() {
  return (
    <React.Fragment>
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      />
    </React.Fragment>
  );
}

export default HeadMeta;

```

**Comment by balazsorban44** [comment]
I could not reproduce your issue using your reproduction.

This is a bad idea anyway, and you are opting-out font optimization. Please see https://nextjs.org/docs/messages/no-page-custom-font

**Comment by kepes** [comment]
Hi Balazs,

thanks for your quick answer!

I made a simplified fork of my project where you can check the bug:
[codesandbox.io](https://codesandbox.io/s/one-pager-and-blog-forked-w9q0l?file=/components/layout.js)

I don't think it's a bad idea to put large or configurable meta tags into a separate reusable component but I can accept your answer about "automatic font optimization".

**Comment by kepes** [comment]
Thanks! It works I get it.
