### ISSUE TITLE
Docs: Add section about how cache-control headers are set, depending on how your pages fetch data

### ISSUE THREAD

**Issue by molebox** [vercel/next.js#33210]
### What is the improvement or update you wish to see?

See this comment: https://github.com/vercel/next.js/issues/33204#issuecomment-1010840976

### Is there any context that might help us understand?

^

### Does the docs page already exist? Please link to it.

Maybe here: https://nextjs.org/docs/going-to-production#caching and here: https://nextjs.org/docs/api-reference/next.config.js/headers#cache-control

**Comment by Gomurmamma** [comment]
Hey, I'd like to contribute in regards to this issue! Can I be assigned?
