### ISSUE TITLE
next/link routes fails to update when using back-button in browser

### ISSUE THREAD

**Issue by KenAJoh** [vercel/next.js#33233]
### Run `next info` (available from version 12.0.8 and up)

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
Binaries:
  Node: 16.13.1
  npm: 8.1.2
  Yarn: 1.22.17
  pnpm: N/A
Relevant packages:
  next: 12.0.8
  react: 17.0.2
  react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS 12.1 Monterey

### How are you deploying your application?

next start

### Describe the Bug

While navigating trough all links in sidebar, hitting the back-button in browser "freezes" loading of previous pages when we get to a specific page.  This is only the case when using `next/link` and navigating to dynamic routes.

Hitting back again does nothing and stays "frozen" until the history reaches a page that is not dynamically routed or was not navigated to trough next/link. Meanwhile hitting forwards in browser works correctly and "unfreezes" the navigation. 

##

Notes from testing issue:
- Path that ends up "freezing" is correctly set in `getStaticPaths`.
- No data is loaded in debugger->network when clicking browser back-button to that specific link. Example in recording 👇 Event listeners or 
```jsx
useEffect(() => {
    demoRouter.beforePopState(({ url, as }) => {
      console.log(JSON.stringify({ url, as }, null, 2));
      return true;
    });
  }, []);
```
in `_app.tsx` does not run when this happens either.

https://user-images.githubusercontent.com/26967723/149218296-7092bc9e-8d28-4ec0-9efa-937167e4dbc3.mov

In recording, navigation freezes when it should have navigated to "Accordion", as seen when hitting back twice. One can see the URL and Head <title> update correctly at the 10 second mark while still rendering "Alert".

Next example is logging `beforePopState` in `_app.tsx` with this snippet 
```jsx
useEffect(() => {
    demoRouter.beforePopState(({ url, as }) => {
      console.log(JSON.stringify({ url, as }, null, 2));
      return true;
    });
  }, []);
```

https://user-images.githubusercontent.com/26967723/149219439-df3fee65-b94a-4548-bbaa-777ade4f7b7a.mov

At the 12 second mark one can see the "beforePopState" run while hitting browser forwards-button to "Accordion" after it not  logging while hitting the back-button. The URL differs from the expected output here, while `as` is as expected. 
```json
{
  "url": "/designsystem/[...slug]?slug=side&slug=alert",
  "as": "/designsystem/side/accordion"
}
```

## 

Usage of next/link 
- ScLink is here a styled-components `<a>`-tag, using native `<a>` does not fix the issue
- onClick does not preventDefault
- Using shallow or prefetch=false does not make a difference
```jsx
<NextLink href={`/${item.link.slug.current}`} passHref>
	  <ScLink
	    onClick={(e) => {
	      onClick && onClick();
	      logNavigation(e);
	    }}
	    active={
	      pageProps?.page
	        ? pageProps.page.slug === item.link.slug.current
	        : false
	    }
	  >
		    {item.title}
	  </ScLink>
</NextLink>
```

[Failing link-code in sidebar code using next/link](https://github.com/navikt/verktoykassen/blob/issue/nextjs-routing/website/components/layout/menu/DesignsystemMenu.tsx)

[_app.tsx](https://github.com/navikt/verktoykassen/blob/issue/nextjs-routing/website/pages/_app.tsx)

[Dynamic routing ([...slug].tsx)](https://github.com/navikt/verktoykassen/blob/issue/nextjs-routing/website/pages/designsystem/%5B...slug%5D.tsx)

### Expected Behavior

Hitting backwards in browser always loads the previous page when having used `next/link` to navigate to/from that specific dynamically routed page.

### To Reproduce

Bug in production can be tested [here](https://design.nav.no/designsystem/side/komponenter) 

Clone [branch in repo](https://github.com/navikt/verktoykassen/tree/issue/nextjs-routing)
```batch
// While in repo root
yarn install
yarn build:next
yarn serve:next
```
- open http://localhost:3000/designsystem/side/komponenter
- In sidebar, navigate from "Oversikt" -> "Accordion" -> "Alert"
- Hit back-button in browser

https://user-images.githubusercontent.com/26967723/149222058-8daab94d-a4e3-467d-819e-3dfc40a35a2b.mov

**Comment by KenAJoh** [comment]
Related issues, but no working solution found #7091 #9989

**Comment by snelsi** [comment]
Probably related: #29461

**Comment by KenAJoh** [comment]
### Found cause and solution!
App currently updates hash in URL while scrolling trough page. This snippet was used for handling that: 
```
useEffect(() => {
    activeId
      ? window.history.replaceState(null, null, `#${activeId}`)
      : window.history.replaceState(null, null, " ");
  }, [activeId]);
```
This broke routing when using "back"-button i browser

To fix this this snippet was used where `window.history.state` was set as first arg in `replaceState`: 
```
useEffect(() => {
    activeId
      ? window.history.replaceState(window.history.state, "", `#${activeId}`)
      : window.history.replaceState(window.history.state, "", " ");
  }, [activeId]);
```
Lesson learned is to be careful when working with window.history in Nextjs. I *think* the first solution is valid, but i might assume `next/link` uses `window.history` in the background and my first solution broke this interaction.

**Comment by the-sides** [comment]
> ```
> useEffect(() => {
>     activeId
>       ? window.history.replaceState(window.history.state, "", `#${activeId}`)
>       : window.history.replaceState(window.history.state, "", " ");
>   }, [activeId]);
> ```
This was the solution for me. THANK YOU.
