### ISSUE TITLE
Video.js crash when SWC Minify is enabled

### ISSUE THREAD

**Issue by cuyl** [vercel/next.js#33265]
### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

any

### What browser are you using?

Chrome  97.0.4692.71

### What operating system are you using?

Windows11 & MacOS 12.1

### How are you deploying your application?

next start

### Describe the Bug
Run `next build && next start`, open the demo in any browser.
Click the play button, video can not play, and console shows the error: `VIDEOJS: ERROR: TypeError: Cannot read properties of null (reading 'playlistLoader')`

### Expected Behavior

Video plays with no errors.

### To Reproduce

Repo: https://github.com/cuyl/next-bug-with-swc-minify
Link: https://next-bug-with-swc-minify.vercel.app/
Open the link and click the play button, the error shows on the console.

**Comment by rtritto** [comment]
It correctly works in dev with _yarn berry_ (repo cloned and then `yarn set version canary && yarn && yarn dev_`).
I got issue with link.
Issue related to yarn v1.

## Info
Chrome 97.0.4692.71
OS: Windows 10-11
yarn: 3.2.0-rc.10

**Comment by cuyl** [comment]
@rtritto SWC Minify only runs in production build, you should run `yarn build && yarn start` to test the bug

**Comment by rtritto** [comment]
I have same error but only with a _m3u8_ file and not with a _mp4_ file.

**Comment by cuyl** [comment]
@kdy1 Strange, I updated to `12.0.9-canary.2` play is working now, but the error still throws in Firefox and Chrome, not throw in Safari. maybe it is another bug.
Chrome 96
Firefox 96
Safari 15.2

**Comment by kdy1** [comment]
Oh... Yes, I reproduced it. It seems like a different issue, and I'm not sure about the cause.
I'll add it to my minifier tasklist.
