### ISSUE TITLE
Apple Silicon M1: cant start the default app

### ISSUE THREAD

**Issue by runmaxde** [vercel/next.js#33281]
### Run `next info` (available from version 12.0.8 and up)

/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.8-canary.22
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS (Apple Silicon M1)

### How are you deploying your application?

Locally

### Describe the Bug

It isnt possible to start the app downloaded via cli with the basic typescript example. 🤕

**thanks for all informations and help**

### Expected Behavior

Starting boilerplate app `npx create-next-app --ts ` without error 😅

### To Reproduce

1. `npx create-next-app --ts test-on-m1`
2. `cd test-on-m1`
3. `npm run dev`
4. install typescript and @types/react => wanted from cli out `npm install --save-dev typescript @types/react` 
5. `npm run dev`

https://user-images.githubusercontent.com/41482988/149400002-8abbaecc-f2bf-44db-aa50-e327f9e9eb17.mp4

**Comment by graup** [comment]
According to the [docs](https://nextjs.org/learn/basics/create-nextjs-app/setup), you might need to use `--use-npm`, did you try that?

```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
```

**Comment by runmaxde** [comment]
> According to the [docs](https://nextjs.org/learn/basics/create-nextjs-app/setup), you might need to use `--use-npm`, did you try that?
> 
> ```
> npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
> ```

Did Not change the behaviour ...

**Comment by runmaxde** [comment]
So after testing a bunch of stuff, I think the problem is based on the next version. After changing it to `"next": "12.0.5"` it seems like everything is working as expected.

**Comment by balazsorban44** [comment]
Is that the exact version you can pinpoint this to? or could find out which `canary` changed it? I cannot reproduce it, unfortunately.

**Comment by runmaxde** [comment]
`12.0.6`isn't working either, if you can tell what information you need additionally, or how to get them, I will provide them. The problem show in the video is quite strange.

**Comment by balazsorban44** [comment]
It would be useful to know which exact version introduced a bug. You can use `npx create-next-app@exact-version --ts test-on-m1` where version is any of these https://github.com/vercel/next.js/tags

Try finding the version that first produces your issue.

**Comment by runmaxde** [comment]
It seems that the error occurred only with me (no other user has reported). Unfortunately, I could not restore the scenario. 

Therefore, I would close the request
