### ISSUE TITLE
tailwind styles are not working in custome layouts

### ISSUE THREAD

**Issue by SiddheshDabholkar** [vercel/next.js#33287]
### What example does this report relate to?

with-tailwindcss

### What version of Next.js are you using?

latest

### What version of Node.js are you using?

with-tailwindcss

### What browser are you using?

chrome

### What operating system are you using?

Linux 

### How are you deploying your application?

vecrel

### Describe the Bug

Styles are not applying while using Single Shared Layout.

tried it on my machine,stackblitz and codesandbox

checkout the sandboxcode link

### Expected Behavior

Styles should be applied on navbar and footer while using custom layout.

navbar
```
import React from "react";
export default function Navbar() {
    return <div className="bg-red-900">navbar</div>;
}
```
footer
```
import React from "react";
export default function Footer() {
    return <div className="bg-red-500">footer</div>;
}
```

Layout
```
import React from "react";
import Navbar from "../layout/Navbar";
import Footer from "../layout/Footer";

export default function Layout({ children }) {
  return (
    <div>
      <Navbar />
      <>{children}</>
      <Footer />
    </div>
  );
}
```
_app.tsx
```
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Layout from '../layout/Layout'
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Layout>
      <Component {...pageProps} />
    </Layout>
  )
}

export default MyApp
```

Home
```
export default function Home() {
  return <div className="bg-green-900 p-6">hmmmmm</div>;
}
```

### To Reproduce

[sandbox](https://codesandbox.io/s/nice-pine-zk6je?file=/layout/Navbar.jsx)

**Comment by balazsorban44** [comment]
Your `tailwind.config.js` file should reference all the folders that contain Tailwind classes.

Adding `"./layout/**/*.{js,ts,jsx,tsx}",` to your `content` option solvles the issue.
