### ISSUE TITLE
next/jest is reporting incorrect line numbers for passing and failing tests

### ISSUE THREAD

**Issue by mattruby** [vercel/next.js#33412]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.4.2
      npm: 7.18.1
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.4.2

### What browser are you using?

NA

### What operating system are you using?

macOS Monterey

### How are you deploying your application?

npm run test

### Describe the Bug

When running `npm run test` on a fresh setup based on https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler I'm seeing the wrong line numbers being highlighted in the test output.  It seems as if line breaks are being ignored.

#### Wallaby:
![CleanShot 2022-01-17 at 15 36 43](https://user-images.githubusercontent.com/142194/149839458-28cda035-778b-45c1-977e-ea981218285c.png)

#### Wallaby:
![CleanShot 2022-01-17 at 15 37 16](https://user-images.githubusercontent.com/142194/149839493-a8987a84-26c7-4c35-ba67-7386d049a45a.png)

#### CLI:
![CleanShot 2022-01-17 at 15 38 51](https://user-images.githubusercontent.com/142194/149839635-48bb3dfa-eb63-4153-9c34-53ae92027c60.png)

#### Wallaby: 
![CleanShot 2022-01-17 at 15 40 57](https://user-images.githubusercontent.com/142194/149839807-a3e564a0-a0e0-4c8a-b87c-0c02336af9c3.png)

#### CLI: 
![CleanShot 2022-01-17 at 15 41 18](https://user-images.githubusercontent.com/142194/149839866-da905241-a5e6-4f6a-b9f4-e26930bbb9fa.png)

### Expected Behavior

I would expect jest's cli to output the correct line numbers with regard to error reporting and coverage. 

### To Reproduce

https://github.com/mattruby/product-model

I've checked in the test failing with and without line breaks.  Run `npm run test` and the failing lines reported should be incorrect.

**Comment by smcenlly** [comment]
Please note: this issue may be related to next.js jest compiler settings. See discussion here: https://github.com/vercel/next.js/discussions/31152#discussioncomment-1951381

> We have found two issues related to the use of `next/jest` that causes problems with programs that rely on source maps.
> 
> 1. Source maps were not included, which ideally should be when running tests to get correct stack traces, etc.
> 2. The `jsc.transform.optimizer` setting would result in incorrect line/column mappings being returned in source maps 
> 
> Updating `getJestSWCOptions` to include `sourceMaps: true` and removing `jsc.transform.optimizer` settings fixes these problems:
> 
> https://github.com/vercel/next.js/blob/950eb0f48916e36e813e7aeb3d80cc24293fa0c2/packages/next/build/swc/options.js#L72

**Comment by balazsorban44** [comment]
I believe this might be a duplicate of #33255

**Comment by JanKaifer** [comment]
Might be related to https://github.com/vercel/next.js/issues/26494 which was fixed.

**Comment by mattruby** [comment]
The issue has been fixed:
Wallaby:
<img width="307" alt="CleanShot 2023-01-12 at 11 02 55@2x" src="https://user-images.githubusercontent.com/142194/212132215-b111b511-32b4-42f2-b80f-14a225f3ffdf.png">
CLI:
<img width="810" alt="CleanShot 2023-01-12 at 11 04 39@2x" src="https://user-images.githubusercontent.com/142194/212132605-2311fa3b-5770-4c06-b041-8f87e62dd92a.png">

Thanks!
