### ISSUE TITLE
getConfig() returns undefined when experimenal concurrentFeatures flag is turned on

### ISSUE THREAD

**Issue by Jakst** [vercel/next.js#33428]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 18.0.0-rc.0
      react-dom: 18.0.0-rc.0

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying your application?

Doesn't matter

### Describe the Bug

I wanted to try out the `concurrentFeatures` flag with React 18 in our application, but am faced with the error `TypeError: Cannot read properties of undefined (reading 'publicRuntimeConfig')` on the server side. This is locally with `next dev`.

So for some reason calling `getConfig()` (from `next/config`) returns undefined when the `concurrentFeatures` flag is turned on. On the client `getConfig()` returns `{ publicRuntimeConfig: {}, serverRuntimeConfig: {} }` (always empty objects).

_**Side note:** This leaves the browser request hanging. No 500 or anything. In the server logs there are also no reference to where the code is used. No stack trace with line numbers etc. Just the bare message. This could probably be an issue on its own, but leaving it here for now._

### Expected Behavior

getConfig() should include all config set up in `next.config.js`

### To Reproduce

* Bootstrap a new application
* Set up some publicRuntimeConfig in `next.config.js`
* Upgrade to React 18 RC and turn experimental flag `concurrentFeatures` on
* Try to access publicRuntimeConfig in a page by calling `getConfig().publicRuntimeConfig`

**Comment by FourwingsY** [comment]
Is previous versions are compatible with concurrentFeatures?

**Comment by FourwingsY** [comment]
It seems [v12.0.11-canary.9](https://github.com/vercel/next.js/releases/tag/v12.0.11-canary.9) will make it works.
while concurrentFeatures are deprecated, so new config with
```
experimental: {
    reactRoot: true,
    runtime: "node",
    serverComponents: true,
  },
```

**Comment by Jakst** [comment]
Yeah thanks, seems like this is resolved

**Comment by seanislegend** [comment]
> It seems [v12.0.11-canary.9](https://github.com/vercel/next.js/releases/tag/v12.0.11-canary.9) will make it works. while concurrentFeatures are deprecated, so new config with
> 
> ```
> experimental: {
>     reactRoot: true,
>     runtime: "node",
>     serverComponents: true,
>   },
> ```

I had to add this also after updating to the 12.1 update released today. Thanks!
