### ISSUE TITLE
Cannot import .env variables inside next.config.mjs when running jest --watch script

### ISSUE THREAD

**Issue by LarsEjaas** [vercel/next.js#33446]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.10.0
      npm: 8.3.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.10.0

### What browser are you using?

Chrome

### What operating system are you using?

Version: Windows 11 Home

### How are you deploying your application?

next start

### Describe the Bug

When running `npm run test` my `next.config.mjs` file fails to run. `npm run dev` and `npm run build` without issues?

I have used the Jest setup with the Rust Compiler.

I get the following error when running `npm run test`:

```
error - Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
TypeError: Cannot read properties of undefined (reading 'split')
    at file:///C:/Users/larse.LARS-HP/headless_promo/frontend/next.config.mjs:7:59
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async Object.loadConfig [as default] (C:\Users\larse.LARS-HP\headless_promo\frontend\node_modules\next\dist\server\config.js:413:36)
    at async getConfig (C:\Users\larse.LARS-HP\headless_promo\frontend\node_modules\next\dist\build\jest\jest.js:41:18)
    at async C:\Users\larse.LARS-HP\headless_promo\frontend\node_modules\next\dist\build\jest\jest.js:73:30
    at async readConfigFileAndSetRootDir (C:\Users\larse.LARS-HP\headless_promo\frontend\node_modules\jest-config\build\readConfigFileAndSetRootDir.js:134:20)
    at async readConfig (C:\Users\larse.LARS-HP\headless_promo\frontend\node_modules\jest-config\build\index.js:233:18)
    at async readConfigs (C:\Users\larse.LARS-HP\headless_promo\frontend\node_modules\jest-config\build\index.js:420:26)
```

The failing lines the error message is referring to in next-config.mjs is:

```
import nextTranslate from "next-translate";
const imageDomains = process.env.NEXT_PUBLIC_IMAGEDOMAINS.split(",");

const nextConfig = {...
```

AND in my `.env.local` file I have:

```
NEXT_PUBLIC_IMAGEDOMAINS = "example.com, another.example.com"
```
The error imply that I cannot import .env variables in my `next.config.mjs` file when running the test environment?

I have tried adding `console.log(process.env.NEXT_PUBLIC_IMAGEDOMAINS)` to my `next.config.mjs` file and this returns the expected string when running `npm run dev` but returns undefined when running `npm run test`;
 

### Expected Behavior

Expected to be able to read .ENV variables inside my `next.config.mjs` file when running my test script. 

### To Reproduce

![ShareX_bWywIv0lAO](https://user-images.githubusercontent.com/45132430/150023585-9af26900-0026-427d-a914-33f432a0cafc.png)

**Comment by LarsEjaas** [comment]
Actually found a workaround. I can add the `.NEXT_PUBLIC_IMAGEDOMAINS` variable to an `.env` file instead and my tests will run as expected.

But isn't the tests script supposed to be running in a development environment? I am unsure if this is expected behavior?

**Comment by balazsorban44** [comment]
Please refer to the documentation: https://nextjs.org/docs/basic-features/environment-variables#test-environment-variables

**Comment by LarsEjaas** [comment]
Thanks for the explanation @balazsorban44. I will use the .env.test file instead 🙂
