### ISSUE TITLE
Modifying mongoose schemas not populating until development server is restarted

### ISSUE THREAD

**Issue by behnam-io** [vercel/next.js#33453]
### What example does this report relate to?

with-mongodb-mongoose

### What version of Next.js are you using?

12.0.8 

### What version of Node.js are you using?

16.4.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

docker-compose

### Describe the Bug

Modifying schemas (e.g adding a required field) don't populate to entire app unless you restart the development server (i.e.  npm run dev). 

### Expected Behavior

Modifying schemas should populate just like other pages/components without the need to restart development server. 

### To Reproduce

Clone the `with-mongodb-mongoose-app' example:
```bash
npx create-next-app --example with-mongodb-mongoose with-mongodb-mongoose-app
# or
yarn create next-app --example with-mongodb-mongoose with-mongodb-mongoose-app
```

Initialize the setup:
1. add your mongodb uri to `.env.local`
2. `npm i` or `yarn install`

Start the development server:
`npm run dev` or `yarn dev`

Trigger mongoose create the Pet schema by making a POST request to `localhost:3000/api/pets`

curl example:

`
curl --request POST \
  --url http://localhost:3000/api/pets \
  --header 'Content-Type: application/json' \
  --data '{
	"name": "x",
	"owner_name": "me",
	"species": "dog",
	"image_url": "any link address"
}'
`

Go to `/models/Pet.js` and modify the Pet schema; for example try these two scenarios:

1. add a required field named 'blah'
2. remove the required 'name' field

```js

// adding the 'blah' required field
const PetSchema = new mongoose.Schema({
  blah: {
    type: String,
    required: [true, 'Please provide a blah for this pet.'],
    maxlength: [20, 'Blah cannot be more than 60 characters'],
  },
  // name: {
  //   /* The name of this pet */
  //   type: String,
  //   required: [true, 'Please provide a name for this pet.'],
  //   maxlength: [20, 'Name cannot be more than 60 characters'],
  // },
// rest of the original code below
...})

```

Save the file and now try to insert a new record by making a POST request to `/api/pets/index.js`. This time ommit `name` field and add `blah` field. It's expected to receive no errors as the `name` field is not required now and we are passing the new-required `blah` field.

curl example: 
`
curl --request POST \
  --url http://localhost:3000/api/pets \
  --header 'Content-Type: application/json' \
  --data '{
	"blah": "x",
	"owner_name": "me",
	"species": "dog",
	"image_url": "any link address"
}'
`

You will get a 400 response at this stage. console.logging the error message: 

`
error Error: Pet validation failed: name: Please provide a name for this pet.
`

This indicates that our modifications to the Pet schema is not yet populated to app.

restart the development server and try again. This time you will receive a success response, indicating that our changes have populated.

**Comment by balazsorban44** [comment]
After some research, this seems to be intentional by Mongoose and not related to Next.js.

https://stackoverflow.com/a/19051909

The logic on this line:

https://github.com/vercel/next.js/blob/4d3b2ea426ee872532f987461d7fece16e67ad6a/examples/with-mongodb-mongoose/models/Pet.js#L59

prohibits recreating the model once added, which would throw the following error:

```js
OverwriteModelError: Cannot overwrite `Pet` model once compiled.
```

For reference, other ORMs (eg.: TypeORM) have options like `synchronize: true` for development, which will automatically update the models when there are changes.
