### ISSUE TITLE
Library "image-blob-reduce" works in dev mode, but crashes in prod build

### ISSUE THREAD

**Issue by fabb** [vercel/next.js#33452]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020
    Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

14.18.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

I'm trying to use the library `image-blob-reduce` with next.js, and it works fine in the dev mode (`next dev`), but it crashes on usage in the prod build (`next start`).

[`image-blob-reduce` is an ES Module](https://github.com/nodeca/image-blob-reduce/blob/master/dist/image-blob-reduce.esm.mjs), that contains the `pica` library which is built with `browserify`. `pica` also uses [`webworkify`](https://www.npmjs.com/package/webworkify) to complicate things.

Some more investigation info can be found here: https://github.com/nodeca/pica/issues/228

### Expected Behavior

This should work:

```
import ImageBlobReduce from "image-blob-reduce"

// ...
// in an event handler:
new ImageBlobReduce().toBlob(file, { max: 100 }).then((blob) => {
    console.log("converted image successfully", blob)
})
```

### To Reproduce

The error can be reproduced when deploying this codesandbox to Vercel:

https://codesandbox.io/s/image-blob-reduce-next-js-mqj7i?file=/pages/index.js

On the page, open the console and select a file with the input. This error shows up:
```
Uncaught ReferenceError: n is not defined
    at t (4f00a94f-75f9-4f8e-864e-3a077e53aef3:1:314)
    at 4f00a94f-75f9-4f8e-864e-3a077e53aef3:1:353
t @ 4f00a94f-75f9-4f8e-864e-3a077e53aef3:1
(anonymous) @ 4f00a94f-75f9-4f8e-864e-3a077e53aef3:1
```

In dev mode in Codesandbox it works correctly.

**Comment by flavianh** [comment]
Related to https://github.com/vercel/next.js/discussions/30924
