### ISSUE TITLE
Cookie maxAge handling is incorrect or undocumented in Next.js NextResponse

### ISSUE THREAD

**Issue by zmarty** [vercel/next.js#33472]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

16.8.0

### What browser are you using?

Edge (Chromium)

### What operating system are you using?

Windows 11

### How are you deploying your application?

On Azure App Service as docker container

### Describe the Bug

In the [NextResponse documentation](https://nextjs.org/docs/api-reference/next/server#public-methods) example it looks like the cookie maxAge is set in milliseconds (maxAge: 1000 * 60 * 60 * 24 * 7).

It's very easy to make a mistake here (like I did) because typically the [Max-Age in Set-Cookie is expressed in seconds](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie).

I took a look at the [code](https://github.com/vercel/next.js/blob/1d4f364515d34586b864923dafb7888bf1ff79d2/packages/next/server/web/spec-extension/response.ts#L52) and it looks like internally the value gets divided by 1000 to get back seconds. But the fact that milliseconds is expected in the first place is not documented. Please clarify.

Potentially related: 
https://github.com/vercel/next.js/discussions/27617
https://github.com/vercel/next.js/issues/31666

I also want to point out that [nookies](https://github.com/maticzav/nookies) (a Next.js cookie library) expects seconds, which makes it confusing in projects that use both NextResponse and nookies.

### Expected Behavior

If I set maxAge when defining a cookie with NextResponse I expect it to be in seconds, not milliseconds. Or at least properly document this difference.

### To Reproduce

We set cookies in a [Next.js middleware](https://nextjs.org/docs/middleware).

```typescript
  response.cookie(experimentsCookieName, JSON.stringify(newExperimentInfo), {
    path: '/',
    maxAge:  4 * 60 * 60, // I intended this cookie to have a 4 hour expiration, but it has a 14.4 seconds expiration instead!
  });
```

**Comment by kodermax** [comment]
The same.

**Comment by nkzawa** [comment]
Seems like the cookie API derived from express which uses milliseconds as the unit https://expressjs.com/ja/api.html#res.cookie
It's also true that many other libraries use seconds as the unit. I think both makes sense.

If we want to change the behavior, maybe should do it by introducing a new API in conjunction with https://github.com/vercel/next.js/issues/31719 so that easier to migrate and less confusions for existing apps.

**Comment by javivelasco** [comment]
We are going to redesign the cookies API where this will be addressed so I'm closing this one in favour of https://github.com/vercel/next.js/issues/31719
