### ISSUE TITLE
Regression in 12.0.8 for jest: TypeError: require.resolveWeak is not a function

### ISSUE THREAD

**Issue by zmarty** [vercel/next.js#33476]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.8.0
      npm: 7.21.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.8.0

### What browser are you using?

Edge (Chromium)

### What operating system are you using?

Windows 11 Enterprise (by the way, why does next info say I am using Windows 10??)

### How are you deploying your application?

On Azure App Service as docker container

### Describe the Bug

We have a Next.js website where the unit tests are using Jest. When I try to upgrade the website from Next.js 12.0.7 to 12.0.8 the unit tests which test code that uses dynamic code loading start failing.

It looks to me this is related to this previously closed bug, which would make this a regression for Next.js 12.0.8: [TypeError: require.resolveWeak is not a function (jest test) #19862](https://github.com/vercel/next.js/issues/19862)

Example output
```
  ● Test suite failed to run

    TypeError: require.resolveWeak is not a function

    > 29 | const HeaderSearchBoxMobile = dynamic(() => import('../HeaderSearchBox/HeaderSearchBoxMobile/HeaderSearchBoxMobile'));
```

### Expected Behavior

Tests should pass even if the code they test uses dynamic()

### To Reproduce

Run a Jest test where the test code tests some code that uses dynamic() to load some other code.

**Comment by balazsorban44** [comment]
Based on your reproduction, I could not reproduce this issue. Could you create one that I can have a look at?

_On `next info`: OS version is reported by the [native `os.version()` Node.js API](https://nodejs.org/api/os.html#osversion), so it's not much we can do about that. Probably related to the Node.js version you are using, maybe you have to update Node.js._

**Comment by Parnswir** [comment]
We see the same issue in our code base (closed source, sorry): with `next@12.0.8` tests fail when running `jest`; with `next@12.0.7` everything is fine. Strangely, running `jest --coverage` works fine on both versions.

**Comment by Parnswir** [comment]
https://codesandbox.io/s/next-dynamic-22ejz

if you fork it on codesandbox, you can run `npm test` in the terminal on the right (click the + icon). On `next@12.0.8` (which is installed in this sandbox), the test will fail. If you downgrade to `next@12.0.7` (select the version in the dependecies list on the left), the test will pass.

**Comment by balazsorban44** [comment]
Hmm. Thanks for the CodeSandbox, it is helpful! I recognized you did not follow the test setup from https://nextjs.org/docs/testing

Applying those seems to solve the problem. Could you try it?

@zmarty are you using a custom/Babel setup for your test environment? Could you share it?

**Comment by duc-gp** [comment]
> Hmm. Thanks for the CodeSandbox, it is helpful! I recognized you did not follow the test setup from https://nextjs.org/docs/testing
> 
> Applying those seems to solve the problem. Could you try it?
> 
> @zmarty are you using a custom/Babel setup for your test environment? Could you share it?

What exactly are you referring to or what exactly did you changed in the codesandbox to make the test run? Can you provide a link?

**Comment by zmarty** [comment]
> @zmarty are you using a custom/Babel setup for your test environment? Could you share it?

So far we have tried to repro this on an empty Next.js instance and we can't.

We stopped using a custom babel setup for the website entirely a few versions ago.

I do see we use some custom webpack config in next.config.js, so we'll be looking at that as well. Inside the unit tests folder I only see that we set up some mocks.

**Comment by duc-gp** [comment]
We also tried on an the https://github.com/vercel/next.js/tree/canary/examples/with-jest example and there it works.

Unfortunately we still need babel, otherwise we cannot use jest's automock functionality. I've forked and provided an example here:
https://github.com/vercel/next.js/compare/canary...duc-gp:example-jest-automock-not-working?expand=1

- run `npm run test example.test.js` to start the test
- when you outcomment the transform in `jest.config.js` so babel is not used, the test does not work anymore

**Comment by balazsorban44** [comment]
@duc-gp Do note we provide a babel setup as well: https://github.com/vercel/next.js/tree/canary/examples/with-jest-babel

**Comment by duc-gp** [comment]
> @duc-gp Do note we provide a babel setup as well:
> 
> * https://github.com/vercel/next.js/tree/canary/examples/with-jest-babel
> * https://nextjs.org/docs/testing#setting-up-jest-with-babel

@balazsorban44 thanks, ive just checked out the setup you mentioned and added simple basic tests:
https://github.com/vercel/next.js/compare/canary...duc-gp:example-jest-automock-not-working-with-nextjs-babel-setup?expand=1

when you run `npm run test DummyA.test.js` you can see the error `TypeError: require.resolveWeak is not a function`

**Comment by balazsorban44** [comment]
Interesting, I could not reproduce still:

![image](https://user-images.githubusercontent.com/18369201/150841206-e08aacb0-d862-4fbe-9777-c2665714610d.png)

Could you add an actual repository link so I can verify this?

**Comment by duc-gp** [comment]
> Interesting, I could not reproduce still:
> 
> ![image](https://user-images.githubusercontent.com/18369201/150841206-e08aacb0-d862-4fbe-9777-c2665714610d.png)
> 
> Could you add an actual repository link so I can verify this?

what exactly did you do to try to reproduce this? from what setup is your screenshot from?
the link to the repository is: https://github.com/duc-gp/next.js/tree/example-jest-automock-not-working-with-nextjs-babel-setup

- go into `examples/with-jest-babel`
- `npm i`
- `npm run test DummyA.test.js`

**Comment by balazsorban44** [comment]
I tried a totally clean project again with `yarn create next-app -e with-babel-jest`, added your modifications, and finally reproduced it. :+1:

**Comment by PsyGik** [comment]
Thank you for reporting this. I was upgrading a project to Next.js 12 and the CI just barfed all over with the error `TypeError: require.resolveWeak is not a function`. 

On another note, the [Upgrade Guide](https://nextjs.org/docs/upgrading) does not specify the changes that need to be done to setup [Jest with the Rust compiler ](https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler) when upgrading to Next 12. It'd be nice to have the docs updated please.

**Comment by timneutkens** [comment]
Found the problem, opening a PR with a new test that covers this case.

**Comment by timneutkens** [comment]
This is released on canary 🎉  Please try it out: `npm install next@canary`.

**Comment by ryparker** [comment]
Works for me 👍🏻

**Comment by timneutkens** [comment]
Great 👍 This is out on stable in 12.1
