### ISSUE TITLE
Redirect in next.config does not work with Chinese characters

### ISSUE THREAD

**Issue by idrisakmal** [vercel/next.js#33470]
### What version of Next.js are you using?

10.0.1

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Edge

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

I have set up some redirect rules in `next.config.js`. Issue is if the slug is in normal characters, the redirect works fine. But if I have url slug that is written in Chinese characters, it doesn't redirect. 

I have tried using the `asPath` output captured from the router and still it doesn't work. 

Sample Code `next.config.js`

```
async redirects() {
    return [
      // This works
      {
        source: "/blog/car-battery-101",
        destination: "/blog/汽車電池",
        permanent: true,
      },
      // This failed
      {
        source: "/blog/還在猶豫應否做鍍膜？為你解答三大迷思",
        destination: "/blog/汽車電池",
        permanent: true,
      },
    ];
  },
```

### Expected Behavior

When I go to the url with slug specified in the redirect rule, I expect to be redirected.

### To Reproduce

Use the same code as above. The page structure is `pages/blog/[slug]`

**Comment by balazsorban44** [comment]
I see you are using an old Next.js version. Could you please try upgrading to the `latest` version first and see if that resolves your issue? :pray:

**Comment by idrisakmal** [comment]
@balazsorban44 unfortunately that doesn't work as well 😢

**Comment by idrisakmal** [comment]
upgraded to next 12

**Comment by wwwdepot** [comment]
Try encode the source URI

```js
{
        source: encodeURI("/blog/還在猶豫應否做鍍膜？為你解答三大迷思"),
        destination: "/blog/汽車電池",
        permanent: true,
}
```

**Comment by idrisakmal** [comment]
> 

It works! Thanks alot for the suggestion
