### ISSUE TITLE
Preview mode don't correct work on AWS Amplify

### ISSUE THREAD

**Issue by skrg-kotani** [vercel/next.js#33486]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 14.17.6
      npm: 7.24.2
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start,  AWS Amplify

### Describe the Bug

I try to Implementing Next preview mode page refer to the following link.
https://nextjs.org/docs/advanced-features/preview-mode

And I try to access preview page on AWS Amplify.

But response status code is 404.

In My local environment, Preview mode is correct working !!

I'm guessing that `getStaticProps` isn't called  when request the preview page on AWS Amplify.

Please give me some advice or new information!

Please show below AWS Amplify Console Setting.

- amplify.yml
```yml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

- Build image settings
Next.js version:  11

- Rewrites and redirects

| Source address| Target address |Type | Country code|
| ------------- | ------------- |------------- |------------- |
|  /<*>  | https://${cloudfrontId}.cloudfront.net/<*>  | 200  |-  |
|  /<*>  | /index.html  | 400 | -  |

### Expected Behavior

Next Preview mode is working on AWS Amplify

### To Reproduce

1. Implement Next preview mode in Next project
refer to https://nextjs.org/docs/advanced-features/preview-mode

source code is below!

pages/api/preview.js(preview API)
```js
import { api } from "../../libs/api"

export default async (req, res) => {
  if (!req.query.id) {
    return res.status(404).end()
  }
  const { data } = await api.get(`blog/${req.query.id}?fields=id&draftKey=${req.query.draftKey}`)

  if (!data) {
    return res.status(401).json({ message: 'Invalid id' })
  }

  res.setPreviewData({
    id: data.id,
    draftKey: req.query.draftKey,
  })

  res.writeHead(307, { Location: `/blog/${data.id}` })
  res.end('Preview mode enabled')
}
```

pages/blog/page/[id].js (preview target page)
```js
import { api } from "../../libs/api"
import { useRouter } from 'next/router'

export default function BlogId({ blog }) {
  const router = useRouter()
  const backToBlogList = () => {
    router.back()
  }

  return (
    <main>
      <h1>{blog.title}</h1>
      <p>{blog.publishedAt}</p>
      <div
        dangerouslySetInnerHTML={{
          __html: `${blog.body}`,
        }}
      />
      <button onClick={backToBlogList}>
        back to List
      </button>
    </main>
  )
}

export const getStaticPaths = async () => {
  const { data } = await api.get('blog?limit=100')
  const paths = data.contents.map(content => {
      return { params: { id: content.id } }
  })
  return { paths, fallback: false }
}

export const getStaticProps = async (context) => {
  const draftKey = context.previewData?.draftKey
  const url = draftKey ? `blog/${context.params.id}?draftKey=${draftKey}` : `blog/${context.params.id}`
  const { data } = await api.get(url)
 
  return {
    props: {
      blog: data
    }
  }
}
```
2. Next Project(SSR and SSG) deploy to AWS Amplify
 refer to https://docs.aws.amazon.com/ja_jp/amplify/latest/userguide/server-side-rendering-amplify.html

3. Access to preview API endpoint on AWS Amplify
4. response statuscode is 404!!

**Comment by balazsorban44** [comment]
Hi, since you say it works locally, it sounds like an Amplify issue.

I checked their documentation at https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js and it is either outdated or hasn't been updated for a while:

> Currently, Amplify doesn't fully support Image Component and Automatic Image Optimization available in Next.js 10. 

Next.js is now on version 12.

From the above message, it can be assumed that Preview Mode might not be supported on Amplify. I suggest [asking them](https://github.com/aws-amplify/amplify-js), and if they verify it is a feature that is intended to work, please come back and we can have another look! :+1:
