### ISSUE TITLE
Example from-docker : build fail : failed to compute cache key: "/yarn.lock" not found 

### ISSUE THREAD

**Issue by JulienCorb** [vercel/next.js#33493]
### What example does this report relate to?

from-docker

### What version of Next.js are you using?

latest

### What version of Node.js are you using?

node:16-alpine

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying your application?

sudo docker build -t myappname .

### Describe the Bug

trace : 

```
[+] Building 0.8s (11/19)                                                                                                         
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 34B                                                                                             0.0s
 => [internal] load metadata for docker.io/library/node:16-alpine                                                            0.7s
 => [internal] load build context                                                                                            0.0s
 => => transferring context: 4.03kB                                                                                          0.0s
 => [deps 1/5] FROM docker.io/library/node:16-alpine@sha256:2f50f4a428f8b5280817c9d4d896dbee03f072e93f4e0c70b90cc84bd1fcfe0  0.0s
 => CACHED [builder 2/5] WORKDIR /app                                                                                        0.0s
 => CACHED [runner 3/8] RUN addgroup -g 1001 -S nodejs                                                                       0.0s
 => CACHED [runner 4/8] RUN adduser -S nextjs -u 1001                                                                        0.0s
 => CACHED [deps 2/5] RUN apk add --no-cache libc6-compat                                                                    0.0s
 => CACHED [deps 3/5] WORKDIR /app                                                                                           0.0s
 => ERROR [deps 4/5] COPY package.json yarn.lock ./                                                                          0.0s
------
 > [deps 4/5] COPY package.json yarn.lock ./:
------
failed to compute cache key: "/yarn.lock" not found: not found
```

### Expected Behavior

it should build the image with no error

### To Reproduce

have Docker installed
run `npx create-next-app --example with-docker myappname`
run `sudo docker build -t myappname .`

NB : image build works when app gets created with `yarn` instead of `npx`

**Comment by balazsorban44** [comment]
The example is optimized to work with Yarn https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

**Comment by balazsorban44** [comment]
We could add a small note about that in the docs: https://nextjs.org/docs/deployment#docker-image

Would you like to open a PR?

**Comment by JulienCorb** [comment]
thank you @balazsorban44, yes I'll open a PR !

**Comment by fahmyfarahat** [comment]
Hi 👋  @JulienCorb, I can take this one if you didn't open PR.

**Comment by JulienCorb** [comment]
Haven't done it yet, go ahead @fahmyfarahat ! thank you 😃

**Comment by balazsorban44** [comment]
Heads up, there is already a PR for this at #33695 :+1:

**Comment by oelbaganwg** [comment]
I have tested this. It still fails with the same error. yarn.lock isn't being created after you run 
`docker build -t nextjs-docker .`

The OP's original issue persists. 

Even if you create yarn.lock manually before running you run into another error:  `ERROR [deps 5/5] RUN yarn install --frozen-lockfile`

**Comment by balazsorban44** [comment]
Please check the `Dockerfile` in the example that is being cloned:

https://github.com/vercel/next.js/blob/bf8b835e2e1fd4b8364d7411d630d139478e8ea5/examples/with-docker/Dockerfile#L6-L11
