### ISSUE TITLE
Multi Zones and linking from "child" til parent

### ISSUE THREAD

**Issue by LarsBuur** [vercel/next.js#33519]
### Run `next info` (available from version 12.0.8 and up)

/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

14.18.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Using the example from 
```
https://github.com/vercel/next.js/tree/canary/examples/with-zones 
```
I ran into one problem with "next/link" 

I would like to link back to the "docs" parent using e.g. 
```
<Link href="/">Home</Link>
```

This is not possible because next.config.js
```
module.exports = {
  basePath: '/blog',
}
```
In the example 
```
<a href="/">Home</a>
```
works - but when I try the same in a larger app then this is disallowed. It might be a setting somehow.

### Expected Behavior

I would expect either 
```
<Link href="/">Home</Link>
```
works because it detects the basePath from next.config.js
or some option that allow the action.

### To Reproduce

1) clone https://github.com/vercel/next.js/tree/canary/examples/with-zones 

2) add this to blog/pages/index.js

```
<Link href="/">Home</Link>
```

**Comment by balazsorban44** [comment]
> works - but when I try the same in a larger app then this is disallowed. It might be a setting somehow.

I assume you are talking about the [ESLint rule](https://nextjs.org/docs/messages/no-html-link-for-pages), you can just disable it for this case.
