### ISSUE TITLE
API Routes 204 > Conflict between TypeScript and linter rules

### ISSUE THREAD

**Issue by johannpinson** [vercel/next.js#33536]
### Run `next info` (available from version 12.0.8 and up)

 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.2
      npm: 7.24.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Edge

### What operating system are you using?

macOS 12.0.1

### How are you deploying your application?

localhost

### Describe the Bug

In a route API, if I want to return a 204 HTTP Code (No Content), I first added an empty object `{}` as body response, but I get an error inside my terminal :

> A body was attempted to be set with a 204 statusCode for /api/hello, this is invalid and the body was ignored.
> See more info here https://nextjs.org/docs/messages/invalid-api-status-body

So in the docs, we have this code example to use:
```js
export default function handler(req, res) {
  res.status(204).send()
}
```

But by using it, it's now a TypeScript which appears in VSC

```
Expected 1 arguments, but got 0.ts(2554)
utils.d.ts(217, 25): An argument for 'body' was not provided.
```

```ts
// utils.d.ts:217
/**
 * Send body of response
 */
declare type Send<T> = (body: T) => void;
```

I try to change the `res` type with `res: NextApiResponse<any>` but it's not change.
And if I use `res: NextApiResponse<void>`, the error disappear for the `204` return, but now is on a `200` or `400` for example.

The only solution looks like to force the cast as :
```ts
;(res as NextApiResponse<void>).status(204).send()
```

Is there any solution for casting `body` type depending of the status code?

Thanks

### Expected Behavior

Allow to use an empty/void parameter in the `send()` method for a 204 API response.

### To Reproduce

```ts
// /pages/api/hello.ts

import type { NextApiRequest, NextApiResponse } from 'next'

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.status(204).send()
}
```

**Comment by balazsorban44** [comment]
Alternatively, you can just do `res.status(204).end()`, which does not expect a body.

**Comment by johannpinson** [comment]
Hello @balazsorban44 

Ok that looks good!
Thanks for the PR to update the docs, I close the issue 😉
