### ISSUE TITLE
Docs: Example of custom express server and custom express-ws websocket that supports Webpack HMR?

### ISSUE THREAD

**Issue by benallfree** [vercel/next.js#33543]
### What is the improvement or update you wish to see?

I'd like to see an example of a custom server using`express` and `express-ws` working together with webpack's HMR.

I keep seeing this console error:

```
websocket.js?a234:46 WebSocket connection to 'ws://localhost:8081/_next/webpack-hmr' failed: Invalid frame header
```

My server looks like this:

```ts
import express from 'express'
import ExpressWs from 'express-ws'

const app = express()
const expressWs = ExpressWs(app)
const handle = nextApp.getRequestHandler()

expressWs.app.ws('/', (ws, req) => {
   // Do my websocket stuff
})

// Catch all HTTP requests
app.all('*', (req, res) => {
  return handle(req, res)
})
```

It seems like I need something like:

```ts
expressWs.app.ws('/_next/webpack-hmr', (ws, req) => {
   // What goes here?
})
```

### Is there any context that might help us understand?

I see that https://github.com/vercel/next.js/blob/87c4d17726ce060519d4170d00e645ac988a03a3/docs/upgrading.md#nextjs-hmr-connection-now-uses-a-websocket says to add

```ts
app.all('/_next/webpack-hmr', (req, res) => {
  nextjsRequestHandler(req, res)
})
```

That doesn't have any effect.

**Comment by balazsorban44** [comment]
Hi, thank you for opening this. It is highly unlikely that we will add more custom server examples, as it opts out key optimization features.


The following link contains an example of how to use Next.js in a custom server mode, supporting HMR as well:
https://nextjs.org/docs/advanced-features/custom-server
