### ISSUE TITLE
`appContext.router.pathname` using old value after using `router.push` for customized app

### ISSUE THREAD

**Issue by RaenonX** [vercel/next.js#33553]
### Run `next info` (available from version 12.0.8 and up)

```
PS D:\UserData\Downloads\router-push> next info
'pnpm' is not recognized as an internal or external command,
operable program or batch file.

    Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.2
      npm: 8.3.0
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:       
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Irrelevant

### Describe the Bug

Router path name from `getInitialProps` of the customized app is using the old pathname instead of the new one. The line below will show the unexpected behavior in the browser dev console.

https://github.com/RaenonX/bug-router-push-custom-app/blob/2df1c10a3f9d6543a1f781bf7fb1524444b468d0/pages/_app.tsx#L10

### Expected Behavior

> Needs to run `next dev` to start the website first.

After clicking on the button `push A` or `push B`, the corresponding pathname should be shown as `/A` for `push A`; `/B` for `push B` in the browser console.

### To Reproduce

https://github.com/RaenonX/bug-router-push-custom-app

Simply checkout the repository above, run `next dev` and observe the behavior.

**Comment by valensto** [comment]
@RaenonX any news about this issue? I've the same problem with `appContext.ctx.query` to get slug of my page I got undefined when I change the page I have to reload it

**Comment by balazsorban44** [comment]
You should be using `appContext.ctx.pathname` instead.

There seems to be a [slight documentation issue anyway](https://nextjs.org/docs/api-reference/data-fetching/get-initial-props#context-object) (we call the object `context`, but then we list the parameters of `context.ctx`), so thanks for bringing it to our attention!
