### ISSUE TITLE
clarify possible `getServerSideProps` return values

### ISSUE THREAD

**Issue by Vthechamp22** [vercel/next.js#33576]
### What is the improvement or update you wish to see?

I would like to clarify the API documentation for the return value of `getServerSideProps`.

### Is there any context that might help us understand?

I was implementing user authentication on my website, and I was trying to restrict access to the login and signup pages if the user is logged in. To do so, I am implementing this `getServerSideProps` to redirect the user if they're logged in:
```javascript
export async function getServerSideProps(context) {
  if (context.req.cookies.user) {
    return {
      redirect: {
        destination: '/',
        permanent: true,
      },
    }
  }
  return {}
}
```
If I return an empty object (`{}`), next gives me this error:
```
Reason: Props must be returned as a plain object from getServerSideProps: `{ props: { ... } }` (received: `[object Array]`).
```
I used an empty object because in the documentation, it is mentioned that that the `props` argument is optional. I later realised that maybe the content for the `props` property is optional, but not the object itself, and I was just proposing to clarify this for other people in the future.

![Documentation](https://i.stack.imgur.com/08BRg.png)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props

**Comment by chozzz** [comment]
[The type](https://github.com/vercel/next.js/blob/canary/packages/next/types/index.d.ts#L160) basically says `either one of these properties`.

Any thoughts? Else, I will raise a PR regarding it.

**Comment by balazsorban44** [comment]
Yes, the correct way is to return either of those. It doesn't make sense to use them together, neither does it to only return `{}`.

Feel free to open a PR to address this.

**Comment by ELBEQQAL94** [comment]
Hi, Can I work on this issue? If still open?

**Comment by chozzz** [comment]
I have raised a [PR here](https://github.com/vercel/next.js/pull/33577)
