### ISSUE TITLE
3 high severity vulnerabilities after installing node-fetch

### ISSUE THREAD

**Issue by Tosinkoa** [vercel/next.js#33584]
### Run `next info` (available from version 12.0.8 and up)

`PS C:\Users\user\practice-project> npm audit
# npm audit report

node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix --force`
Will install next@10.0.1, which is a breaking change
node_modules/next/node_modules/node-fetch
  next  9.0.6-canary.0 - 9.3.4-canary.0 || 10.0.2-canary.0 - 12.0.8
  Depends on vulnerable versions of node-fetch
  node_modules/next
    eslint-config-next  >=10.2.1-canary.2
    Depends on vulnerable versions of next
    node_modules/eslint-config-next

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force`

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Firefox

### What operating system are you using?

Window 10

### How are you deploying your application?

Vercel

### Describe the Bug

After installing node-fetch with npm it showed high vulnerabilities warning, so I decided to uninstall it immediately. After uninstalling it, it still shows this error, I deleted the files in my node module and also deleted package.lock.json, after running npm i, the error still show up again, the file appear again in my node_module and package.lock.json. Please I need a solution to this. Thanks in advance

### Expected Behavior

I would like the warnings to clear

### To Reproduce

`PS C:\Users\user\practice-project> npm audit
# npm audit report

node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix --force`
Will install next@10.0.1, which is a breaking change
node_modules/next/node_modules/node-fetch
  next  9.0.6-canary.0 - 9.3.4-canary.0 || 10.0.2-canary.0 - 12.0.8
  Depends on vulnerable versions of node-fetch
  node_modules/next
    eslint-config-next  >=10.2.1-canary.2
    Depends on vulnerable versions of next
    node_modules/eslint-config-next

3 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force`

**Comment by balazsorban44** [comment]
Already addressed in #33466, soon out on `latest`.

**Comment by toytonic** [comment]
Any plans on patching v11 of nextjs as well?

**Comment by nikhilgupta16** [comment]
The issue is patched on `11.1.4` and `12.0.9`, [reference](https://github.com/vercel/next.js/issues/33462#issuecomment-1022798597)
