### ISSUE TITLE
Next.js uses cjs module loader resulting in SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by simPod** [vercel/next.js#33599]
### Run `next info` (available from version 12.0.8 and up)

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16

### What browser are you using?

n/a

### What operating system are you using?

macos

### How are you deploying your application?

n/a

### Describe the Bug

I thought next.js 12 comes with esm support. I tried to import https://github.com/simPod/react-graphql-syntax-highlighter that is not built as cjs. I'm getting `SyntaxError: Cannot use import statement outside a module` though.

 ```
> Build error occurred
/builds/projects/a/121813/client/node_modules/react-graphql-syntax-highlighter/dist/index.js:1
import { parse } from 'graphql/language/parser';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.4025 (/builds/projects/a/121813/client/.next/server/pages/graphql/schema.js:25:67)
    at __webpack_require__ (/builds/projects/a/121813/client/.next/server/webpack-runtime.js:25:42) {
  type: 'SyntaxError'
}
```

### Expected Behavior

No errors, lib should not be loaded using cjm loader

### To Reproduce

```
npx create-next-app nextjs-blog --use-yarn --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
cd nextjs-blog
yarn add react-graphql-syntax-highlighter
```

pages/index.js:

```js
import Head from 'next/head'
import { GraphqlCodeBlock } from '../src/gql';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <GraphqlCodeBlock code="" />
      </main>
    </div>
  )
}
```

src/gql.js
```js
import { GraphQLCodeBlock } from 'react-graphql-syntax-highlighter';
import 'react-graphql-syntax-highlighter/dist/style.css';
import React from 'react';

export const GraphqlCodeBlock = ({ code }) => (
  <GraphQLCodeBlock src={code} />
);
```

```
yarn run build
```

**Comment by balazsorban44** [comment]
Next 12 does [support native ES modules](https://nextjs.org/blog/next-12#es-modules-support-and-url-imports) if the package has been correctly configured.

`react-graphql-syntax-highlighter` did not configure [its `package.json`](https://unpkg.com/browse/react-graphql-syntax-highlighter@0.0.2/package.json) correctly. It does not have a `type: "module"` nor `.mjs` extensions in it's `dist` folder.

See the requirements for ES Module detection in the Node.js documentation: https://nodejs.org/api/packages.html#determining-module-system

In addition, an `exports` field should be preferred over `main` as well:

https://nodejs.org/api/packages.html#package-entry-points

Please reach out to the author of the package, or if it's you, follow the steps from the Node.js documentation.
