### ISSUE TITLE
Improve Content-Security-Policy usage explanation

### ISSUE THREAD

**Issue by grantspilsbury** [vercel/next.js#33598]
### What is the improvement or update you wish to see?

Can you add content security policy header examples?

### Is there any context that might help us understand?

At the moment the docs have
```
{
  key: 'Content-Security-Policy',
  value: // Your CSP Policy
}
```
Could you give examples of what `// Your CSP Policy` could be? 
Is it a string, an object, an array? 

In the Mozilla docs they have:
`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; child-src 'none';">`
but I'm not sure how to add that to `value: // Your CSP Policy`

For my use case I need to specify acceptable origins of our iframes.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/security-headers

**Comment by MerlinMason** [comment]
If it helps, this is how I've handled it... it expects a long string which is tricky to format so something like the following makes that slightly more manageable and easier to track changes:

```js
{
        key: "Content-Security-Policy",
        value: [
            ["base-uri", ["'self'"]],
            ["default-src", ["'self'"]],
            ["connect-src", ["'self'", "example.com", "example.co.uk"]],
            ["font-src", ["'self'"]],
            ["form-action", ["'none'"]],
            ["frame-ancestors", ["'none'"]],
            ["img-src", ["'self'"]],
            ["object-src", ["'none'"]],
            ["script-src", ["'self'", "'unsafe-eval'"]],
            ["style-src", ["'self'", "'unsafe-inline'"]],
        ]
            .map(([key, value]) => `${key} ${value.join(" ")};`)
            .join(" "),
}
```

Note that `self` and `none` are keywords so are expected to be wrapped in quotes whereas to domains are not.

**Comment by molebox** [comment]
Docs team: Let's document using a template string then replacing the new line. See Lees implementation here for reference: https://github.com/leerob/leerob.io/blob/bb3b58419bd1d9f39e1903a6c9bb1aa0a750b335/next.config.js#L40
