### ISSUE TITLE
Custom build with App getInitialProps hangs

### ISSUE THREAD

**Issue by kinetifex** [vercel/next.js#33615]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

14.18.3

### What browser are you using?

N/A

### What operating system are you using?

macOS

### How are you deploying your application?

next build

### Describe the Bug

We have found a bug when using Next 12 with [Gasket](https://gasket.dev). When the custom `_app` uses `getInitialProps`, the process hangs and never finishes. 

This is reproducable with a very simple custom build script, such as in [this repo](https://github.com/kinetifex/next-12-custom-build-bug).

When calling the Next `build` function from a script, the process hangs and never exits.

### Expected Behavior

Running a build by executing the `next/dist/build` function from a script completes and exits successfully.

### To Reproduce

Clone [this repo](https://github.com/kinetifex/next-12-custom-build-bug), and run the custom build script.

```
git clone git@github.com:kinetifex/next-12-custom-build-bug.git
cd next-12-custom-build-bug
yarn
yarn custom-build
```

**Comment by balazsorban44** [comment]
I don't think we document this being a supported use case, but the issue seems to be that you have to exit the process yourself.

```js
const path = require("path")
const builder = require("next/dist/build").default

async function main() {
  // Do some setup, then gather some config - such as from Gasket plugins
  const config = {}
  await builder(path.resolve("."), config)
  process.exit(0)
}

main()
```

should work.

**Comment by kinetifex** [comment]
This shouldn't be closed yet. We shouldn't have to exist the process manually.

My example repo has a contrived example, but with Gasket, we can perform other steps after the Next build has been completed. This has worked fine on previous version of Next (8-11). Something introduced in Next 12 is causing this issue.

**Comment by kinetifex** [comment]
And again, it only occurs with `getInitialProps` on the App, indicative of a bug in related code. I'll try to do some more digging, but a manual process exit is not the solution.

**Comment by balazsorban44** [comment]
Unless we document `const builder = require("next/dist/build").default` somewhere, it is not supposed to be used that way, and there is no guarantee for it to work.

What you could do instead is a script that only modifies the `next.config.js` file first and then runs `next build` the regular way `node my-script && next build`.
