### ISSUE TITLE
Page extensions handled inconsistently between dev server and build

### ISSUE THREAD

**Issue by tylerlwsmith** [vercel/next.js#33669]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #202111250933~1638201579~21.04~09f1aa7-Ubuntu SMP Tue Nov 30 02:
    Binaries:
      Node: 15.4.0
      npm: 7.0.15
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

15.4.0

### What browser are you using?

Chrome

### What operating system are you using?

Pop!_OS (Ubuntu-based Linux distribution)

### How are you deploying your application?

next start

### Describe the Bug

The `next build` command is able to process negative-lookbehind regular expressions in the `pageExtensions` setting correctly, while `next dev` does not.

The following page extension should match `.js` files, while ignoring files with a `.ignore.js` extension.

```js
// next.config.js

module.exports = {
  pageExtensions: ["(?<!ignore.)js"],
};

// new RegExp(`(?<!ignore.)js`).test('page.js') 
// true

// new RegExp(`(?<!ignore.)js`).test('page.ignore.js') 
// false
```

When I run `next build && next start`, `pages/page.js` is accessible at `http://localhost:3000/page`. However, when I run `next dev`,  `http://localhost:3000/page` returns a 404.

The reason I want to use a negative lookbehind regular expression in `pageExtensions` is so I can use `.ignore.js` for unfinished pages that should only be accessible during development. Here's what that would look like:

```js
const { PHASE_DEVELOPMENT_SERVER } = require("next/constants");

module.exports = (phase, { defaultConfig }) => ({
  pageExtensions: phase === PHASE_DEVELOPMENT_SERVER
    ? ["ignore.js", "(?<!ignore.)js"]
    : ["(?<!ignore.)js"]
});
```

### Expected Behavior

When I set `pageExtensions` to `["(?<!ignore.)js"]` in `next.config.js`, I would expect a page named `pages/page.js` to be accessible at `http://localhost:3000/page` when running the site using `next dev` or `next start`. 

This currently works with `next start`, but it returns a 404 error when using `next dev`.

### To Reproduce

Create a new Next.js project.

Copy the following into `next.config.js`:

```js
module.exports = {
  pageExtensions: ["(?<!ignore.)js"],
};
```

Create a page at `pages/page.js` with the following:

```js
export default function TestPage() {
  return <div>I am a test page.</div>;
}
```

Run `npm run dev` then navigate to `http://localhost:3000/page`. You'll see a 404 error instead of the page.

Now run `npm run build && npm run start` then navigate to `http://localhost:3000/page`. You'll see the page rendering correctly.

---

If you like, you can also confirm that ignored pages are not accessible. Create `pages/hidden.ignore.js` with the content below then visit `http://localhost:3000/hidden` using both `next dev` and `next start`. It will return a 404 on both methods (this is currently working correctly).

```js
export default function HiddenPage(props) {
  return <div>I am a hidden page.</div>;
}
```

**Comment by balazsorban44** [comment]
As a workaround, you could do the opposite and suffix pages that should be public. I think it's safer as well, aligns well with being explicit about what you want to expose. (this is how env variables work for example, when requiring `NEXT_PUBLIC_` for them to be inlined in client-side code.

**Comment by tylerlwsmith** [comment]
I'm currently using a workaround similar to what you suggested in my application, and I don't mind using the workaround. 

I felt like I should open an issue because the handling of regular expressions is different between the dev server and the build. I would expect if I set `pageExtensions` to `["(?<!ignore.)js"]`, the same set of pages should be accessible regardless of if I ran `next dev` or `next build && next start`. The inconsistency feels like it could be a bug.

I'm curious what your thoughts are.

**Comment by balazsorban44** [comment]
I agree that inconsistencies aren't good anyway, I just wanted to point out that this sounds like an edge-case that could be solved in an objectively safer way. 

I'm going to check later why this is happening though (is this a bug or somehow intentional, which I doubt).

**Comment by BkSouX** [comment]
hi, any updates on that ? I have similar issue with : 

` pageExtensions: process.env["CC_SITE_ID"] ? ["static.tsx"] : ["server.tsx"],`

It works with next dev but not with next build + start

**Comment by JanKaifer** [comment]
I just checked and the original reproduction shows `404` on both `dev` and `start`.
