### ISSUE TITLE
localeDetection set to false within defined locales raises an error  despite documentation says to do that

### ISSUE THREAD

**Issue by alex-piccione** [vercel/next.js#33666]
### What version of Next.js are you using?

12.0.7

### What version of Node.js are you using?

12.x

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

In this page: [Disabling Automatic Locale Detection](https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection) it says that you can disable the locale detection but it still will provide the locale info (this is more disabling routing than locale, I think).  
The example shows that you have only to set ``localeDetection: false`` in next.config.js

This is the error:
> Error: Specified i18n.locales should be an Array received undefined.
See more info here: https://nextjs.org/docs/messages/invalid-i18n-config

### Expected Behavior

Locale is detected and available by _userRouter_ and _getStaticProps_ _context_.

### To Reproduce

Createa  basic project. 
Change next.config.js to be like the example:
```javascript
module.exports = {
  i18n: {
    localeDetection: false,
  },
}
```

Just rin the application within ``yarn dev`` (it calls a script with: ``yarn install && next dev``)

**Comment by balazsorban44** [comment]
You still need to provide the possible locales your app will support as explained higher up in the docs:
https://nextjs.org/docs/advanced-features/i18n-routing#getting-started

> These are all the locales you want to support in

**Comment by alex-piccione** [comment]
> You still **need** to provide the possible locales your app will support as explained higher up in the docs:

I think it is still not clear that the _locales_ AND the _defaultLocale_ are mandatory.    
Searching online for a way to get the HTTP header "Accept-Language" many suggests that you can simply use _useRouter_ and the provided _.locale_ property from it.    
It's not immediately clear that you are forced to choose a limited list of locales you want to support.

I don't want routing,  I need to just be able to provide a locale to my DatePicker, any possible locale (more precisely I have a list of 555 locales).  
After a week without beeing able to user useRouter I think the simple way, without using intrusive 3rd party packages, is to use a _middelware_ and parse the req.headers.get("accept-language") string myself.

**Comment by balazsorban44** [comment]
Check out the `navigator.language` API if you only need the user's preferred language for your DatePicker:

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language

**Comment by alex-piccione** [comment]
> Check out the `navigator.language` API if you only need the user's preferred language for your DatePicker:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language
> 
> There is also an experimental `navigator.languages` which gives you a list so you can fall back if you don't support some of the languages in that list:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages
> 
> Ideally, all this could be part of the DatePicker component/library and you as the consumer should only need to set a single prop like `detectLanguage`.

That is was what I did initially (and what I always did when website where done just with vanilla JavaScript), 
but I cannot find a "place" (Page, getStaticProps, components) where _navigator_ or _window.navigator_ is not _undefined_.  
That's why I tried to use something _inside_ the framework.

**Comment by balazsorban44** [comment]
Coming from something like Create React App I can understand the immediate reaction. It boils down to that Next.js will try to create a pre-rendered version of your page, so you cannot access `window` inside components, you will have to find a safe place like `useEffect`, which only executes client-side. See https://nextjs.org/docs/migrating/from-create-react-app#safely-accessing-web-apis
