### ISSUE TITLE
Depends on vulnerable versions of node-fetch

### ISSUE THREAD

**Issue by guidorice** [vercel/next.js#33663]
### Run `next info` (available from version 12.0.8 and up)

n/a

### What version of Next.js are you using?

11.1.3

### What version of Node.js are you using?

node:16-alpine

### What browser are you using?

Firefox

### What operating system are you using?

MacOS

### How are you deploying your application?

kubernetes

### Describe the Bug

npm audit reports:
```
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix --force`
Will install next@10.0.1, which is a breaking change
node_modules/next/node_modules/node-fetch
  next  9.0.6-canary.0 - 9.3.4-canary.0 || 10.0.2-canary.0 - 12.0.8
  Depends on vulnerable versions of node-fetch
  node_modules/next
    eslint-config-next  >=10.2.1-canary.2
    Depends on vulnerable versions of next
    node_modules/eslint-config-next
```

### Expected Behavior

Upgrade to node-fetch 2.6.7

### To Reproduce

Run npm audit in a nextjs 11 app?

**Comment by balazsorban44** [comment]
duplicate of #33462
