### ISSUE TITLE
Latest styled-jsx fails to build with ::-webkit-slider-thumb:active selector

### ISSUE THREAD

**Issue by lachlanjc** [vercel/next.js#33672]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 14.15.4
      npm: 8.3.0
      Yarn: 1.22.10
      pnpm: 6.23.1
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

14.15.4

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

On all previous versions of next/styled-jsx, my site has built just fine. Upgrading to `12.0.8`, the upgrade of `styled-jsx` from `5.0.0-beta.3` to `5.0.0-beta.6` broke the project because of the selector `input::-webkit-slider-thumb:active`. Downgrading styled-jsx back to beta 3 with dependency overrides lets the site build once again.

<img width="645" alt="Screenshot of build logs" src="https://user-images.githubusercontent.com/5074763/151085470-1d09a2b8-b30e-4001-93d2-5e5aa23a636e.png">

### Expected Behavior

Though this CSS doesn't work for every browser, it's the only way to customize the color of an `input type-"range"` control when it's being interacted with cross-browser. (Source: https://toughengineer.github.io/demo/slider-styler/slider-styler.html) You can see it live in action on the sliders on https://watershedclimate.com/wfh-calculator

### To Reproduce

I've created a minimal reproduction project here: https://codesandbox.io/s/wild-river-vlyf2?file=/components/input_range.js

Commenting out this selector, as well as the accompanying `::-moz-range-thumb:active`, allows the site to build.

**Comment by alexander-akait** [comment]
Fix https://github.com/swc-project/swc/pull/3386

**Comment by balazsorban44** [comment]
@lachlanjc I'm guessing a few days before it appears in one of our `canary` releases.

Oh, nice @alexander-akait! Could you keep an eye on that upcoming PR and tag it with this issue for auto-closing? :pray:
