### ISSUE TITLE
Unexpected behavior when a path parameter value matches the path parameter name

### ISSUE THREAD

**Issue by klarstrup** [vercel/next.js#33703]
### What version of Next.js are you using?

12.0.8-canary.6

### What version of Node.js are you using?

whatever vercel.com is on

### What browser are you using?

Chrome 97

### What operating system are you using?

Windows

### How are you deploying your application?

Vercel

### Describe the Bug

For a URL like https://vercel.com/changelog/[item] to a page `/changelog/[item].tsx`, `useRouter().query` returns an empty object `{}`.

### Expected Behavior

For a URL like https://vercel.com/changelog/[item] to a page `/changelog/[item].tsx`, one would expect `useRouter().query` to return `{ item: "[item]" }`

### To Reproduce

Request a path parameter's name as its value: https://vercel.com/changelog/[item]

**Comment by balazsorban44** [comment]
Thanks, I could reproduce this locally with the following:


1. create page
**pages/[slug].js**
```js
import { useRouter } from "next/router"

export default function Page() {
  const router = useRouter()
  return <pre>{JSON.stringify(router.query, null, 2)}</pre>
}
```

2. Visit `http://localhost:3000/[slug]`
3. Observe error in development 
![image](https://user-images.githubusercontent.com/18369201/151233149-eefdb02c-5834-40ca-9d62-cacb796883c6.png)


Just to investigate further, do you have a valid use case for this? :thinking:

**Comment by klarstrup** [comment]
> Just to investigate further, do you have a valid use case for this? 🤔

Not in particular, but errors from this behavior popped up in my production logs for access to a similar URL (may have come from bad internal URL building)

I decided to raise this issue since it's a case of unfortunate interpolation/escaping similar to the one I addressed in https://github.com/vercel/next.js/issues/31523

**Comment by klarstrup** [comment]
The main thing here is that it feels like a breach of API contract that there is a scenario where `useRouter().query` for a page `/[param]` will not have a string `param` property


I don't want to have to check for that in all of my dynamic routes :(
