### ISSUE TITLE
node-fetch vulnerability reported by npm audit on a fresh nextjs app

### ISSUE THREAD

**Issue by senthil-sprint1** [vercel/next.js#33701]
### Run `next info` (available from version 12.0.8 and up)

'yarn' is not recognized as an internal or external command,
operable program or batch file.
'pnpm' is not recognized as an internal or external command,
operable program or batch file.

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 14.15.3
      npm: 6.14.9
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

14.15.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

S3

### Describe the Bug

This morning(1/26/2022) I created a brand new nextjs app with this command `npx create-next-app@latest`, at the end of the run I saw the following message about a vulnerability
```
found 1 high severity vulnerability
run `npm audit fix` to fix them, or `npm audit` for details
```
Here is the result from `npm audit`

```
                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  High            node-fetch is vulnerable to Exposure of Sensitive
                  Information to an Unauthorized Actor

  Package         node-fetch

  Patched in      >=2.6.7

  Dependency of   next

  Path            next > node-fetch

  More info       https://github.com/advisories/GHSA-r683-j2x4-v87g

found 1 high severity vulnerability in 256 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```

### Expected Behavior

It should not have high severity vulnerability when you create a brand new app.

### To Reproduce

- Run `npx create-next-app@latest`
- Give a name
- After app is created navigate to that folder in command line
- Run `npm audit`
- You should see the follwing message

**Comment by balazsorban44** [comment]
Duplicate of #33462
