### ISSUE TITLE
Path parameters cause repeated triggering of route monitoring

### ISSUE THREAD

**Issue by tomozheng** [vercel/next.js#33728]
### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

v14.15.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

when there are parameters on the path path: /about?id=123
Add listener routing events in _app.js
Refreshing the page will trigger the trigger listener

### Expected Behavior

When there are parameters on the path path, refreshing the page will not trigger route listening

### To Reproduce
```js
import App from 'next/app';

export default class MyApp extends App {

  componentDidMount() {
    Router.events.on('routeChangeStart', url => {
     // When the path has parameters, it will be triggered after refreshing the page
      console.log(url);
    })
  }


  render() {
    const { Component, pageProps, router } = this.props;
    return <Component {...pageProps} />
  }
}
```

**Comment by balazsorban44** [comment]
This is expected.

https://nextjs.org/docs/advanced-features/automatic-static-optimization#how-it-works

> During prerendering, the router's query object will be empty since we do not have query information to provide during this phase. After hydration, Next.js will trigger an update to your application to provide the route parameters in the query object.

So query values are delayed for static pages. We don’t provide them immediately during hydration to prevent mismatches so we trigger a second render with the updated query information.

**Comment by tomozheng** [comment]
So, how do I deal with this problem? I need to listen to the route and call some methods, which will lead to repeated triggering




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vercel/next.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月27日(星期四) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vercel/next.js] Path parameters cause repeated triggering of route monitoring (Issue #33728)





 
This is expected.
 
https://nextjs.org/docs/advanced-features/automatic-static-optimization#how-it-works
  
During prerendering, the router's query object will be empty since we do not have query information to provide during this phase. After hydration, Next.js will trigger an update to your application to provide the route parameters in the query object.
  
So query values are delayed for static pages. We don’t provide them immediately during hydration to prevent mismatches so we trigger a second render with the updated query information.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by balazsorban44** [comment]
You can use the `isReady` property for this purpose:

https://nextjs.org/docs/api-reference/next/router#router-object
