### ISSUE TITLE
jimp font not loading in api functions

### ISSUE THREAD

**Issue by Anshuman71** [vercel/next.js#33736]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020
    Binaries:
      Node: 17.0.1
      npm: 8.1.0
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

17.0.1

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

To Vercel

### Describe the Bug

I'm using jimp lib to modify images, the logic works fine on local but when I push to vercel, I get this error =>

```
INFO	[Error: ENOENT: no such file or directory, open '/var/task/node_modules/@jimp/plugin-print/fonts/open-sans/open-sans-32-black/open-sans-32-black.fnt'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/task/node_modules/@jimp/plugin-print/fonts/open-sans/open-sans-32-black/open-sans-32-black.fnt'
}
```

### Expected Behavior

Modify the image without error

### To Reproduce

For this repo https://github.com/Anshuman71/tweet-my-articles and run this action 
https://github.com/Anshuman71/tweet-my-articles/actions/workflows/update-twitter-banner.yml

**Comment by styfle** [comment]
Hi @Anshuman71 

The issue is that the following is not statically analyzable:

```js
const jimpFont = path.resolve(jimp.FONT_SANS_32_BLACK);
```

The variable `jimp.FONT_SANS_32_BLACK` could be anything that jimp decides to return at runtime.

If you change this line to a static string (cannot change at runtime), then Next.js will include the correct file at build time.

For example:

```ts
const plugin = require.resolve('@jimp/plugin-print');
const jimpFont = path.resolve(plugin, '../../fonts/open-sans/open-sans-32-black/open-sans-32-black.fnt');
```

**Comment by Anshuman71** [comment]
thanks @styfle let me try that

**Comment by Anshuman71** [comment]
I got it working by referencing those files from 'public' for now. thanks @styfle for quick response
