### ISSUE TITLE
Docs: 404 error when we click on "Data Fetching: Overview"

### ISSUE THREAD

**Issue by dudusotero** [vercel/next.js#33779]
### What is the improvement or update you wish to see?

Fix the navigation to Overview on next's docs.

### Is there any context that might help us understand?

At the final part of [Pages](https://nextjs.org/docs/basic-features/pages), when we try do to the next section of the Docs "[Overview](https://nextjs.org/docs/basic-features/data-fetching/overview)", we get a 404 error.

Some images to show exactly which element I'm clicking:
![image](https://user-images.githubusercontent.com/7073199/151626654-adafd8b6-f0bc-4bc0-9c37-19be3524c3a2.png)

I also noticed that the left side menu, has some duplicated values for the Overview links.
![image](https://user-images.githubusercontent.com/7073199/151626744-9fe256e4-d4dc-485a-98d7-116c010d2f1e.png)

The second one is the correct link, the first goes to the same link as when we click on the element of the first image.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/pages

**Comment by ijjk** [comment]
Hi, this should be corrected now thanks for reporting this!

**Comment by dudusotero** [comment]
Yeah, the side menu is working fine, now only the next needs to be fixed.

![Screenshot_20220129-021107_Chrome.jpg](https://user-images.githubusercontent.com/7073199/151648351-9cc8e876-4543-4f66-a2dd-a61f417776e1.jpg)

**Comment by leerob** [comment]
Fixed!
