### ISSUE TITLE
Image tag takes 16 seconds to load

### ISSUE THREAD

**Issue by saito-kosuke** [vercel/next.js#33800]
### What version of Next.js are you using?

12.0.9

### What version of Node.js are you using?

v14.18.1

### What browser are you using?

Chrome / Safari

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

the next.js Image tag takes 16 seconds to load as below.

### Expected Behavior

Shorten the load time of the next.js Image tag

### To Reproduce
Direct Access
https://s3.ap-northeast-1.wasabisys.com/coinfra/assets/img-staking-pc.png

Access Via next.js Image tag 
https://www.coinfra.io/_next/image?url=https%3A%2F%2Fs3.ap-northeast-1.wasabisys.com%2Fcoinfra%2Fassets%2Fimg-staking-pc.png&w=1920&q=75

**Comment by balazsorban44** [comment]
Hi. Hitting your reproduction URL results in an SSL error:

```sh
This site can’t provide a secure connectionwww.coinfra.io sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

Could you please create a reliable reproduction and share the source code as well?

**Comment by saito-kosuke** [comment]
@balazsorban44 
What do you mean?
I check the SSL of `www.coinfra.io`, but no error has occurred to me.
https://www.sslshopper.com/ssl-checker.html#hostname=https://www.coinfra.io
![image](https://user-images.githubusercontent.com/54809007/152272043-62499da5-7fa6-49b8-889b-a58c76f7707e.png)

**Comment by balazsorban44** [comment]
![image](https://user-images.githubusercontent.com/18369201/152617758-93287559-57e2-4e59-9869-97aa8a2b8cd2.png)

The http://www.coinfra.io/ site also does not seem to be loading for me, it hangs and shows a blank screen. I suspect this is not a `next/image`, but probably not a Next.js issue either.
