### ISSUE TITLE
Docs: Internationalized Routing - error with Next v12 middleware example

### ISSUE THREAD

**Issue by zanzlender** [vercel/next.js#33811]
### What is the improvement or update you wish to see?

On the page [i18n-routing](https://nextjs.org/docs/advanced-features/i18n-routing) of the docs under the section [#prefixing-the-default-locale](https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale) I found a bug and a few issues that commented on it. However, I didn't see they were resolved... 

The following example produces an infinitely looped url because **request.nextUrl.href** returns the whole url.
![image](https://user-images.githubusercontent.com/44570474/151707315-67892b21-9a85-4817-ad6f-8b05f5f1555c.png)

I believe it should be **request.nextUrl.pathname** which properly appends only the path to the new url. 

Additionally, with the message that relative urls will be deprecated, in my example I also added a env. variable containing the baseUrl like so:

![image](https://user-images.githubusercontent.com/44570474/151707428-dfd146a7-b895-4eee-8b4b-b0b861a13d81.png)

### Is there any context that might help us understand?

I think i explained everything 👍

Hope that this is correct and that it will be useful for better understanding 😊

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale

**Comment by ValentinH** [comment]
It seems that this was fixed since this issue was open: 
![image](https://user-images.githubusercontent.com/2678610/153580055-5642ae87-20aa-4714-9751-fd5e653ea8a3.png)

**Comment by balazsorban44** [comment]
Closing, as this has indeed been updated. Thanks!
