### ISSUE TITLE
Show warning during build if page is returning a large amount of data

### ISSUE THREAD

**Issue by leerob** [vercel/next.js#33829]
### Describe the feature you'd like to request

Following up from https://github.com/vercel/next.js/pull/29956, let's consider adding this for `next build`.

### Describe the solution you'd like

A warning is outputted during `next build` similar to local devl.

### Describe alternatives you've considered

See thread for context: https://twitter.com/ascorbic/status/1487024158492049408

**Comment by sshyam-gupta** [comment]
@leerob Is this ready yet? I would like to pick this up.

**Comment by balazsorban44** [comment]
Feel free to work on this!
