### ISSUE TITLE
document.referrer not updated after page transition with next/link or next/router

### ISSUE THREAD

**Issue by PhilipeGatis** [vercel/next.js#33824]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 17.0.1
      npm: 8.1.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.9
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.9

### What version of Node.js are you using?

17.0.2

### What browser are you using?

chrome

### What operating system are you using?

Macos

### How are you deploying your application?

vercel

### Describe the Bug

On every page transition using next/link or next/router document.referrer does not change with the previous url.

### Expected Behavior

document.referrer update when page transition happens using next/router or next/link.

### To Reproduce

1 - Create a Next app with 2 routes.
2 - Add this code to _app page to log document.referrer value
`useEffect(() => {
    console.log(document.referrer)
  }, [router.asPath])`
3 - on each router put a next/link or next/router to reference another page
4 - click on link
result: document.referrer no change 

1 - Create a Next app with 2 routes.
2 - Add this code to _app page to log document.referrer value
`useEffect(() => {
    console.log(document.referrer)
  }, [router.asPath])`
3 - on each router put a "\<a \\>" to reference another page
4 - click on link
result: document.referrer changed

**Comment by balazsorban44** [comment]
Referring(!) this: https://github.com/vercel/next.js/issues/7192#issuecomment-487494640 Next.js Link does client-side transitions, so `document.referrer` won't update.

**Comment by PhilipeGatis** [comment]
However, the document referrer is on client-side. I think it's  because when transition ocorrus a retrieve from new data json instead a document (html). So the browser can't update document-referrer info!
https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer @balazsorban44

**Comment by balazsorban44** [comment]
Client-side navigation won't emit this change AFAIK, they are not "true" navigations. (In a sense that they won't make a new request to the server, but they will be announced for a11y purposes, etc.)

You can test it by `window.history.pushState(null, null, "/some-page")`

and calling `document.referrer`, it won't be updated.

Besides, there are probably better ways to achieve what you want to do.

You could for example listen to a router event `routeChangeStart`:

https://nextjs.org/docs/api-reference/next/router#usage-6

Hope that helps! :pray:
