### ISSUE TITLE
React Server Components don't work with reactStrictMode

### ISSUE THREAD

**Issue by benkeil** [vercel/next.js#33847]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: 6.28.0
    Relevant packages:
      next: 12.0.9
      react: 18.0.0-rc.0
      react-dom: 18.0.0-rc.0

### What version of Next.js are you using?

12.0.9

### What version of Node.js are you using?

v16.13.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying your application?

next dev

### Describe the Bug

When you use React Server Components and want to render a client component which uses e.g. `useState` and you have `reactStrictMode` enabled, the client component don't execute any javascript.

### Expected Behavior

Should work

### To Reproduce

Checkout the `next-rsc-demo` and modify `next.config.js` to:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    reactRoot: true,
    concurrentFeatures: true,
    serverComponents: true,
  },
};

module.exports = nextConfig;

```

**Comment by balazsorban44** [comment]
Hi, this has likely been fixed by https://github.com/vercel/next.js/pull/34333

I wasn't able to reproduce the issue using the latest demo code. If you still hit this, please open a new issue, thanks! :pray:
