### ISSUE TITLE
Docs: API Routes Details - confusing text for beginning

### ISSUE THREAD

**Issue by diberry** [vercel/next.js#33842]
### What is the improvement or update you wish to see?

The [API Routes](https://nextjs.org/learn/basics/api-routes/api-routes-details) part of the beginning tutorial includes the following text which is very confusing:

```
Do Not Fetch an API Route from getStaticProps or getStaticPaths

You should not fetch an API Route from getStaticProps or getStaticPaths. Instead, write your server-side code directly in getStaticProps or getStaticPaths (or call a helper function).
```

What is the difference between fetching from and coding directly in those functions? That seems contradictory. I'm used to putting the layer of the app that makes API calls in a separate area of the app and using those functions. But I can't do that Next? I have to have the fetch method directly in getStaticXXX functions?

### Is there any context that might help us understand?

I think the tutorial should be extended with two api calls, 1 to the Next API in this app and 1 to a 3rd party API. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/api-routes/api-routes-details

**Comment by molebox** [comment]
Hey @diberry! Sorry for the confusion. We cover this here: https://nextjs.org/docs/basic-features/data-fetching/get-static-props#write-server-side-code-directly 

Essentially what this means is that you shouldn't call an API Route from inside one of the getXXXXX functions. If your API route is making a call to an external CMS to fetch data, you can bring that calling logic into the getXXX function instead. 

We'll look to update the page you linked 🙏

**Comment by MonstraG** [comment]
Example, because examples are nice:

DONT:
```js
// page
export async function getServerSideProps() {
	const data = await fetch("/api/data/");
	return { props: { data } };
}

// /api/data.js
export default async function handler(req, res) {
	await fetch(call-to-3rd-party-api);
}
```

DO:
```js
// page
export async function getServerSideProps() {
	const data = await fetchData();
	return { props: { data } };
}

// /api/data.js
export const fetchData = () => {
	return fetch(call-to-3rd-party-api);
};

export default async function handler(req, res) {
	await fetchData();
}
```

**Comment by balazsorban44** [comment]
Absolutely, but it depends on the specific use case if you have a better option or not. If you are wondering, I would leave a question in [our discussions](https://github.com/vercel/next.js/discussions) with your use case. :+1:

**Comment by Zhencha0Cai** [comment]
> Absolutely, but it depends on the specific use case if you have a better option or not. If you are wondering, I would leave a question in [our discussions](https://github.com/vercel/next.js/discussions) with your use case. 👍

Thanks for replying. Actually, I have started a post there yesterday. If you could take a look that would be great. 
https://github.com/vercel/next.js/discussions/34576
