### ISSUE TITLE
[Compiler bug]: script created using document.createElement("script") produces compile time error in NextJS 12.x

### ISSUE THREAD

**Issue by rashidul0405** [vercel/next.js#33850]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

aws

### Describe the Bug

Following code produces compile-time error

code
```js

   let script = document.createElement("script")
    script.async = async
    script.onload = resolve(key)
```

error
```sh

Error: error: Expected '=>', got '.'
  
   |
19 |     script.onload = resolve(key)
   |           ^

Caused by:
    0: failed to process js file
    1: Syntax Error
```

### Expected Behavior

Should just compile fine.
worked fine in nextjs 10.2.3

### To Reproduce

Created a repo by extracting the code https://github.com/rashidul0405/script-bug-nextjs
Exact code related to this bug: https://github.com/rashidul0405/script-bug-nextjs/commit/e0fc11f0d8bea70faec2196d5632b1e782b22c53
also available in codesandbox: https://codesandbox.io/s/cool-roentgen-726sc?file=/pages/index.js

**Comment by rashidul0405** [comment]
@ijjk @timneutkens @balazsorban44 This is simple JS, so this should compile?

**Comment by timneutkens** [comment]
Well it's not as clear-cut, you're using a reserved keyword `async` (generally used as `async function` or `async () =>`) as a variable which is breaking the SWC parser:
https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA8tJLVEoTi7KLChRsFVIyU8uzU3NK9FLLkpNLEl1zUkF8TSUIAqUNLkUgADC0UssrsxLBuoB08gS%2BXk5%2BYkpQJmi1OL8nLJUjezUSk0ALyrLc2cAAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

**Comment by rashidul0405** [comment]
I see, was very hard to understand. thank you :)

**Comment by SukkaW** [comment]
The issue still occurs in the latest version of swc. I have reported the issue to swc: https://github.com/swc-project/swc/issues/4873
