### ISSUE TITLE
RangeError: WebAssembly.instantiate(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by aboda1986** [vercel/next.js#33858]
### Run `next info` (available from version 12.0.8 and up)

 Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Tue Sep 7 14:49:57 UTC 2021
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.18.3

### What browser are you using?

Chrome

### What operating system are you using?

linux

### How are you deploying your application?

Linux server

### Describe the Bug

I tried to run "npm run dev" or  "npm run build" or "npm run start" in linux server for a fresh project, the following error occurred:

error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
    at internal/deps/cjs-module-lexer/dist/lexer.js:1:33593
    at async initCJSParse (internal/modules/esm/translators.js:72:5)
    at async Loader.commonjsStrategy (internal/modules/esm/translators.js:185:18)
    at async link (internal/modules/esm/module_job.js:67:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@ dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output abov

### Expected Behavior

next app should be running well without any error for fresh project

### To Reproduce

install a fresh project in linux server with node then try to run it in dev or production mode

1- open CPanel Terminal or connect with the server by SSH
2- Run "npx create-next-app@latest"
3- Run "npm run dev" or "npm run build" you will get the above error

**Comment by aboda1986** [comment]
To Reproduce
install a fresh project in linux server with node then try to run it in dev or production mode

1- open CPanel Terminal or connect with the server by SSH
2- Run "npx create-next-app@latest"
3- Run "npm run dev" or "npm run build" you will get the above error

**Comment by moshie** [comment]
I am getting a similar issue

**Comment by balazsorban44** [comment]
I could not reproduce with SSH. This seems to be unrelated to Next.js

Found this article, might be useful: https://blog.stackblitz.com/posts/debugging-v8-webassembly/#too-much-memory-for-my-taste

**Comment by moshie** [comment]
@aboda1986 Are you using pinojs or nextjs-sentry by any chance?

**Comment by barikhan1986** [comment]
> @aboda1986 Are you using pinojs or nextjs-sentry by any chance?

No, I don't use them

**Comment by aboda1986** [comment]
> @aboda1986 Are you using pinojs or nextjs-sentry by any chance?

No, I don't use them

**Comment by moshie** [comment]
I think your issue is that node is `14.18.3` that's pretty old try updating to v16

**Comment by amirho1** [comment]
@aboda1986 did you find any solution or the problem I have the same problem I use typescript and nodejs version 16.8.0

**Comment by aboda1986** [comment]
> @aboda1986 did you find any solution or the reason of problem ??? I have the same problem I use typescript and nodejs with version 16.8.0
Right now am using BitSSH to build and run next.js app, it's working fine but still not working if you use Cpanel Terminal
