### ISSUE TITLE
Docs: use storybook-addon-next for the with-storybook example project

### ISSUE THREAD

**Issue by RyanClementsHax** [vercel/next.js#33889]
### What is the improvement or update you wish to see?

Improve the `with-storybook` example by using the [example provided in the storybook-addon-next repo](https://github.com/RyanClementsHax/storybook-addon-next/tree/6583c2080386f72fdebc49ff93a2b8262d1219bc/examples/nextv12).

### Is there any context that might help us understand?

This was kindly requested by @leerob in [this issue](https://github.com/RyanClementsHax/storybook-addon-next/issues/3) on the `storybook-addon-next` repo.

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/tree/canary/examples/with-storybook

**Comment by leerob** [comment]
Thank you so much!
