### ISSUE TITLE
Module not found: Can't resolve `process`

### ISSUE THREAD

**Issue by TrevorThomp** [vercel/next.js#33894]
### Run `next info` (available from version 12.0.8 and up)

npx --no-install next info
```JSX
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
    Binaries:
      Node: 14.17.5
      npm: 6.14.14
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.1
      react-dom: 17.0.1
```

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

We recently attempted to upgrade to Next v12.0.8 from 11.x.x and we are no longer able to build the application and get the following error:

```JSX
Module not found: Can't resolve 'process'
> 25 | {process.env.COMPANY} Technology, Inc.
```

In our application, we access our build time environment variable in our components with `process.env.NEXT_PUBLIC_`. In 11.x.x we didn't have any issues and we are able to reference the values. 

Currently, we don't have anything set in `next.config.js` because we didn't need to have any configurations set to access these variables previously. If I install `process` as a dependency, then everything works as expected.

I noticed in v12.0.8 `process` was removed as a dependency in a PR to pre-compile more dependencies:
https://github.com/vercel/next.js/pull/32627

Is there something that needs to happen on our end for `process` to be accessible?

I've seen someone else state the same issue as well here:
https://github.com/vercel/next.js/issues/33469#issuecomment-1018547259

### Expected Behavior

No errors when resolving modules.

### To Reproduce

I'm having issues getting environments set up to provide a reproducible example but I will keep trying to get something set up.

**Comment by Praneeth-Pike** [comment]
@TrevorThomp I was running into the same issue. Doing this fixed it:
1. Add `process: require.resolve("process/browser"),` to webpack config.resolve.fallback in `next.config.js`: 
```
module.exports = {
	reactStrictMode: true,
	pageExtensions: ["js", "jsx", "ts", "tsx"],
	webpack: config => {
		// Unset client-side javascript that only works server-side
		config.resolve.fallback = {
			fs: false,
			module: false,
			process: require.resolve("process/browser"), <---- this line
		}

		return config
	},
}
```
2. `yarn add process`
