### ISSUE TITLE
Environment Variables are not passed to the server created by `outputStandalone`

### ISSUE THREAD

**Issue by JoeyEamigh** [vercel/next.js#33897]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: linux
      Arch: x64
      Version: #103-Ubuntu SMP Fri Nov 26 16:13:00 UTC 2021
    Binaries:
      Node: 16.12.0
      npm: 8.1.0
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.0.9
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.9

### What version of Node.js are you using?

16.12.0

### What browser are you using?

Chromium Edge

### What operating system are you using?

Ubuntu 20.04

### How are you deploying your application?

`outputStandalone` node server.js

### Describe the Bug

Environment variables passed using `ENV=staging node server.js` are not accessible within the Next app itself, just the server config.

### Expected Behavior

The environment variables would be defined

### To Reproduce

Create a Next server with `outputStandalone` set to true then attempt to pass an environment variable to the server by prefixing the `node server.js`

**Comment by recurrence** [comment]
I'm also not seeing the contents of .env available to api routes in the standalone build either.

**Comment by JoeyEamigh** [comment]
A workaround is to use the `env` config object in `next.config.js` and pass env vars at build time

**Comment by recurrence** [comment]
Will that expose them to the browser environment as well?

**Comment by JoeyEamigh** [comment]
I believe you still have to prefix with `NEXT_PUBLIC` for them to be exposed to the browser - [source](https://nextjs.org/docs/basic-features/environment-variables)

**Comment by recurrence** [comment]
oh that's great, I'll try this :)

**Comment by recurrence** [comment]
Actually, they do leak https://github.com/vercel/next.js/issues/11131

**Comment by recurrence** [comment]
It looks like manually copying the .env file into the build output works.

**Comment by balazsorban44** [comment]
I believe this is more of a feature request than a bug. `.env` files are not handled by the standalone server currently.

Installing `dotenv` in the `standalone` folder and then adding `require("dotenv").config()` to the `server.js` would automatically read those into `process.env` and will make them available to the rest of the app.

**Comment by balazsorban44** [comment]
I opened a PR that would copy over the env file on build, but upon re-reading this issue, I realized this is not how you tried to pass the variable.
