### ISSUE TITLE
Mozilla Scroll Issue when scroll behaviour is smooth

### ISSUE THREAD

**Issue by rishabhtatia1** [vercel/next.js#33899]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: linux
      Arch: x64
      Version: #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022
    Binaries:
      Node: 14.17.0
      npm: 6.14.13
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.1
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

11.1.3

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Mozilla

### What operating system are you using?

Linux

### How are you deploying your application?

Other platform

### Describe the Bug

Scroll behaviour when using scroll behaviour: smooth on mozilla firefox
Not able to scroll on top on page changes.

### Expected Behavior

The page should scroll to top

### To Reproduce

[Uploading screen-recorder-wed-feb-02-2022-12-02-10.zip…]()

**Comment by rishabhtatia1** [comment]
I can share the code it's a private project.

**Comment by balazsorban44** [comment]
Please do! See my e-mail on my GitHub profile. :+1:

**Comment by rishabhtatia1** [comment]
Hi,
https://finexy.com/
You can replicate the issue on this site. By following the steps in the
video.
Okay I'll make a repo which I can share. It will take some time.

**Comment by balazsorban44** [comment]
> By following the steps in the video.

Sorry, but the video did not get uploaded. Your original post https://github.com/vercel/next.js/issues/33899#issue-1121566422 contains a broken link.

I noticed that on your site you have `scroll-behavior: auto;`. Setting it to `scroll-behavior: scroll;` solves smooth scrolling, even after page navigation.

**Comment by rishabhtatia1** [comment]
Yes I'll add give me sometime.
