### ISSUE TITLE
URIError: URI malformed at decodeURIComponent

### ISSUE THREAD

**Issue by gritaliana** [vercel/next.js#33920]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying your application?

with Docker

### Describe the Bug

The project worked perfectly with Next 9.5.3

There are .sass files with provided styles for background images:

`background: url('data:image/svg+xml,%3Csvg%20xmlns%3D%22ht...`

But, after updating to Next 12.0.9 / 12.0.10, replacing packages as it is described in migration guide there are now Errors during compilation:
Where [pathToMyFile].module.sass - is the same file.

```
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[5].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[5].use[2]!./node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[5].use[3]!./node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[2].oneOf[5].use[4]!./[pathToMyFile].module.sass
frontend_1   | URIError: URI malformed
frontend_1   |     at decodeURIComponent (<anonymous>)
```

```
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> URIError
frontend_1   | (node:48) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
frontend_1   | (Use `node --trace-deprecation ...` to show where the warning was created)
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/frontend/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[5].use[1]!/frontend/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[5].use[2]!/frontend/node_modules/next/dist/build/webpack/loaders/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[5].use[3]!/frontend/node_modules/next/dist/compiled/sass-loader/cjs.js??ruleSet[1].rules[2].oneOf[5].use[4]!/frontend/[pathToMyFile].module.sass': No serializer registered for URIError
```

### Expected Behavior

Parsing css background property with data-url

### To Reproduce

I have updated to Next 12.0.10, replace @zeit/next-sass, node-sass with "sass" package. Everything as provided in migration guide. Removed url-loader package and in next.config.js I have replaced the rule:

```
config.module.rules = config.module.rules.concat([
      {
        test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 4096,
              fallback: 'file-loader'
            }
          }
        ]
      }
    ])
```

**with this configuration:** 
```
config.module.rules = config.module.rules.concat([
      {
        test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
        type: 'asset'
      }
    ])
```

Am I missing something in configuration?

Because I found out, that if I replace background property with background-image: url('data:image/svg+xml,%3Cs...') there is no error in console. But there are a lot of places where we are using background prop with data url. 

It should work and compile correctly as in Next 9.5.3 version.

**Comment by alexander-akait** [comment]
Can you show full `data` URI content?

**Comment by gritaliana** [comment]
background: url('data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20649%2087.5%22%20xmlns%3Av%3D%22https%3A%2F%2Fvecta.io%2Fnano%22%3E%3Cpath%20d%3D%22M0%200h649v87.5H0z%22%20fill%3D%22%230b3647%22%2F%3E%3Cpath%20d%3D%22M0%204.03h649v76.22H0z%22%20fill%3D%22%23104f68%22%2F%3E%3Cpath%20d%3D%22M0%200h649v8.07H0z%22%20fill%3D%22%231a6184%22%2F%3E%3C%2Fsvg%3E') 0 0 no-repeat

**Comment by alexander-akait** [comment]
Need update `css-loader` (https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack/loaders/css-loader/src/utils.js), fixed in css-loader

**Comment by gritaliana** [comment]
But I haven't install any css loader packages aside `next` itself. 
Only `"sass": "^1.49.7"`.

Should I install also css-loader? Because I thought that next provides this configuration.

**Comment by alexander-akait** [comment]
No need, bug is here, I will look at this on weekends

**Comment by gritaliana** [comment]
Oh, I see. Thank you! 
Will this issue be closed as soon as this bug will be fixed? So I can rely on it and get updates from next version.

**Comment by alexander-akait** [comment]
Yes, issue will be closed when problem was resolved
