### ISSUE TITLE
Rewrites are only configurable at build time

### ISSUE THREAD

**Issue by ffleandro** [vercel/next.js#33931]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: 6.29.1
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

`rewrites()` in `next.config.js` is only called at build time.
IMHO it should be called at run time.

*Use Case:* If I don't know beforehand the url to where I want to rewrite I can't define it at runtime from an Environment variable.

### Expected Behavior

`rewrites()` should be called at runtime so that we can have a dynamic rewrite url using an env variable.

### To Reproduce

put a log in `rewrites()` in `next.config.js` and verify that it is only called at build time and not at runtime.

**Comment by balazsorban44** [comment]
This is correct and expected. if you need a more dynamic way, you can have a look at Middleware: https://nextjs.org/docs/middleware
