### ISSUE TITLE
@media print styles are applied to regular view

### ISSUE THREAD

**Issue by aengl** [vercel/next.js#33946]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.11.1
      npm: 8.1.4
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.11.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When combining selectors and styles inside of a `@media print` (and potentially other media queries), they are applied even when the media query should not apply.

### Expected Behavior

`@media print` should not have any side-effects when not showing the print preview

### To Reproduce

The following page will always show the text in orange:
```tsx
import React, { FunctionComponent } from 'react';

const Index: FunctionComponent = () => (
  <main>
    <h1>I shouldn't have a color</h1>
    <style jsx>{`
      main {
        font-size: 2em;
        text-align: center;
      }
      @media print {
        color: teal;
        main {
          color: orange;
        }
      }
    `}</style>
  </main>
);

export default Index;
```

**Comment by ijjk** [comment]
Hi, the above `@media print {` doesn't appear to be valid CSS as the `color: teal;` should be nested inside of a selector. I'm going to close this since it doesn't appear to be a bug when the CSS is fixed, if you are still having trouble with this after updating that please respond with additional info!

**Comment by aengl** [comment]
Thank you for taking the time to respond!

I agree that it's not valid CSS. It may have been unintentional, but Next.js 11 supported this syntax as a nifty short-hand to apply the style to the component root 😁

**Comment by ijjk** [comment]
Ah yeah the swc CSS parser is stricter although we should probably be showing an error when the CSS isn't valid instead of rendering incorrect styles.

**Comment by aengl** [comment]
Yes, I agree that an error would be a good resolution 👌, that should avoid surprises after migrating to Next.js 12.

**Comment by alexander-akait** [comment]
Fix https://github.com/swc-project/swc/pull/3461

**Comment by aengl** [comment]
Wow that was quick 😮, well done! 👏💛
