### ISSUE TITLE
Middleware NextResponse.rewrite does not work for client side routing using next/link

### ISSUE THREAD

**Issue by JackOddy** [vercel/next.js#33942]
### Run `next info` (available from version 12.0.8 and up)

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.3
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.11-canary.3

### What version of Node.js are you using?

v14.18.3

### What browser are you using?

Edge

### What operating system are you using?

macOS (m1)

### How are you deploying your application?

n/a bug is reproducible locally

### Describe the Bug

When clicking on a `next/link` 
and href of the `next/link` has a corresponding page in `/pages`
and `NextResponse.rewrite()` is called within the middleware of the page (confirmed by console logging just before the call)
then the browser routes to the corresponding page in `/pages`

however if refreshing on this page or navigating to it from another means (address bar, for example) then the rewrite is successfully applied

### Expected Behavior

When clicking on a `next/link` 
and href of the `next/link` has a corresponding page in `/pages`
and `NextResponse.rewrite()` is called within the middleware of the page 
then the browser rewrites the request and the rewritten url content is displayed

### To Reproduce

[example repo here](https://github.com/JackOddy/client_side_rewrites_not_working)

spin up the next.js project by running `yarn dev`
navigate to localhost:3000 on the browser
click the text on the page (wrapped in next/link)
see that the browser has navigated to `/overwritten`
see that the content displayed is not that of the overwritten url

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.0.11-canary.6` of Next.js, please update and give it a try!

**Comment by JackOddy** [comment]
@ijjk looks like the new build is working, thank you so much for turning this around so quickly! 😁
