### ISSUE TITLE
Absolute links generated during ISR get prefixed with the i18n domain if a Host header is provided

### ISSUE THREAD

**Issue by MartijnHols** [vercel/next.js#33941]
### Run `next info` (available from version 12.0.8 and up)

/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
    Binaries:
      Node: 16.10.0
      npm: 7.24.0
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2
✨  Done in 1.05s.

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.10.0

### What browser are you using?

Chrome and curl

### What operating system are you using?

macOS and in Docker container

### How are you deploying your application?

next start and Docker container with next start

### Describe the Bug

Given the following:
1. i18n domains setup in `next.config.js` e.g. `example.nl`
2. ISR setup of a dynamic page (not sure it has to be a dynamic page); e.g. `revalidate: 1`
3. An absolute link rendered with `next/link` e.g. `<Link href="https://nextjs.org">Test</Link>`

When the page triggers a new build with ISR from a request that has a Host header for the domain configured in the i18n domains config, the href will be prefixed with that domain. To summarize the reproduction steps: `curl -H "Host: example.nl" http://localhost:3000/posts/pre-rendering` turns the `https://nextjs.org` link href into `https://example.nlhttps://nextjs.org`.

### Expected Behavior

No domain prefixing of absolute URLs (also what is the point of domain prefixing at all?)

### To Reproduce

https://github.com/MartijnHols/nextjs-absolute-links-bug

README with reproduction steps and clean commits to see the setup needed.

**Comment by MartijnHols** [comment]
Here is a patch for the issue: https://github.com/MartijnHols/nextjs-absolute-links-bug/blob/patch/patches/next%2B12.0.10.patch

**Comment by HugoBianquini** [comment]
Same issue here! Also don't understand the point of prefixing absolute URLs

I'm using a component with `next/link` in a dynamic page with `getServerSideProps`. 

```   
<Link href="https://nextjs.org" passHref>
   <a>{children}</a>
</Link>
```    
Running locally, it turns the link into `https://localhost:3000https://nextjs.org`

@MartijnHols Your patch worked here, great work!
