### ISSUE TITLE
Failed to parse src "test-file-stub" on next/image

### ISSUE THREAD

**Issue by davidgruar** [vercel/next.js#33976]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 14.16.1
      npm: 6.14.12
      Yarn: 1.19.1
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.16.1

### What browser are you using?

n/a

### What operating system are you using?

Windows

### How are you deploying your application?

n/a

### Describe the Bug

The default `next/jest` config appears to contain a bug that causes tests to break if an image file is imported and passed as the `src` of an `Image` component. If you follow the instructions at https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler, and reference an image in this way, you get an error: `Failed to parse src "test-file-stub" on next/image`.

This is because image imports are mapped to [this mock](https://github.com/vercel/next.js/blob/canary/packages/next/build/jest/__mocks__/fileMock.js), which returns the string `'test-file-stub'`. According to the advice at https://nextjs.org/docs/testing#setting-up-jest-with-babel, that string should have a leading slash, i.e. `'/test-file-stub'`. If you are using the default config, that mock is imported from `node_modules` and can't be modified.

NB this is the exact same issue as #29799, which was incorrectly closed as a duplicate of #26749. The latter is actually a separate issue, although the recommended workaround - to mock the entire `next/image` module - does also work for this one.

### Expected Behavior

It should be possible to follow the quickstart instructions and test a component that includes an imported image file without error.

### To Reproduce

1. `npx create-next-app@latest --example with-jest with-jest-app`
2. Modify `index.tsx` as follows:
```diff
  import Image from 'next/image'
+ import vercel from "../public/vercel.svg";

- <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
+ <Image src={vercel} alt="Vercel Logo" width={72} height={16} />
```
3. Run `npm test`.
4. Test run fails with ```Error: Failed to parse src "test-file-stub" on `next/image`, if using relative image it must start with a leading slash "/" or be an absolute URL (http:// or https://)```.

**Comment by balazsorban44** [comment]
Thanks for reporting! I could reproduce it and found the issue, a PR has been opened to address this.
