### ISSUE TITLE
Error when building app using next/link in _document

### ISSUE THREAD

**Issue by marek-saji** [vercel/next.js#33983]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #26-Ubuntu SMP Fri Jan 7 15:48:31 UTC 2022
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.2

### What browser are you using?

not relevant

### What operating system are you using?

linux

### How are you deploying your application?

not relevant

### Describe the Bug

Getting “React.Children.only expected to receive a single React element child.” (<https://reactjs.org/docs/error-decoder.html/?invariant=143>) when building an app using `next/link` in `pages/_document` (or it’s sub–components). Works fine with `yarn dev` and when used in `_app` (or it’s sub–components).

### Expected Behavior

`next/link` works in `pages/_document`

### To Reproduce

In an empty project (`npx create-next-app@latest`):

1. Add `pages/_document.tsx`:
    ```tsx
    import Document, { Html, Head, Main, NextScript } from 'next/document'
    import Link from 'next/link'
    
    class MyDocument extends Document {
      render() {
        return (
            <Html>
              <Head>
                <Link href="/foo" passHref>
                  <link rel="something" />
                </Link>
              </Head>
              <body>
                <Main />
                <NextScript />
              </body>
            </Html>
        )
      }
    }
    
    export default MyDocument
    ```
2. `yarn build`:
    ```terminal
    Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
    Error: Minified React error #143; visit https://reactjs.org/docs/error-decoder.html?invariant=143 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
        at Object.only (/home/saji/src/next.js-document-link-bug/node_modules/react/cjs/react.production.min.js:19:241)
        at Link (/home/saji/src/next.js-document-link-bug/.next/server/chunks/322.js:215:41)
    ```

Error is thrown here:

https://github.com/vercel/next.js/blob/06b263021ab7790f70adc6c1738dc7feb0d90065/packages/next/client/link.tsx#L230-L245

For whatever reason on `_document` we are getting an array with single element as `children` instead of the element itself.

**Comment by ijjk** [comment]
Hi, `next/link` should not be used in `_document` as it's meant for client-side transitions and as mentioned in [the docs](https://nextjs.org/docs/advanced-features/custom-document) `_document` is only server-side rendered and event-handlers do not work in this file.
