### ISSUE TITLE
Regression: bumping Next version from 11 to 12, generated js files are builded ignoring browserlist

### ISSUE THREAD

**Issue by ale-grosselle** [vercel/next.js#33985]
### Run `next info` (available from version 12.0.8 and up)
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.8
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.8

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying your application?

Other platform

### Describe the Bug

Updating our application from Next 11 to Next 12 we noticed that generated js assets are generated ignoring the browserlist.

For instance, starting from this code:
```js
const callAll = async function () {
  console.log("OK HELLO!");
}
```

**Building using Next 11 (minified version)**
```js
() => {!async function () {console.log('OK HELLO!')}(), new t})
```

**Building using Next 12  (minified version)**
```js
var n, t = (n = e().
          mark((function n () {
            return e().
              wrap((function (n) {
                for (; ;) switch (n.prev = n.next) {
                  case 0:
                    console.log('OK HELLO!')
                  case 1:
                  case'end':
                    return n.stop()
                }
              }), n)
          })), function () {
          var t = this, r = arguments
          return new Promise((function (o, e) {
            var u = n.apply(t, r)

            function c (n) {i(u, o, e, c, f, 'next', n)}

            function f (n) {i(u, o, e, c, f, 'throw', n)}

            c(void 0)
          }))
        })
```

### Expected Behavior

should respect browserslist.

We discovered that the regression is due to replacing babel in favor of  [swc](https://nextjs.org/docs/advanced-features/compiler#why-swc).

Forcing the use of babel, adding  _.babelrc_ file at the project root, the output files are converted as expected: 
```json
{
  "presets": ["next/babel"],
  "plugins": []
}

```

### To Reproduce

- Go to this repo: https://github.com/ale-grosselle/nextjs-browserlist-regression
- navigate to "next11-chrome-94" folder, then run "npm install && npm run build"
- Go to ".next/static" folder and then search "Hello"
- You will find the async function
- navigate to "next12" folder, then run "npm install && npm run build"
- Go to ".next/static" folder and then search "Hello"
- You will find the same function transpiled (for ie11 basically)

**Comment by balazsorban44** [comment]
Hi, could you test `canary`? A potentially related change has recently been made https://github.com/vercel/next.js/pull/33890

**Comment by ale-grosselle** [comment]
Hi @balazsorban44,
I tried the `12.0.11-canary.6` version, see the [example](https://github.com/ale-grosselle/nextjs-browserlist-regression/tree/main/next12-canary), but I still having the same problem. 

The output is this:

```js
var f = function () {
        var n, t = (n = e().
          mark((function n () {
            return e().
              wrap((function (n) {
                for (; ;) switch (n.prev = n.next) {
                  case 0:
                    console.log('OK HELLO!')
                  case 1:
                  case'end':
                    return n.stop()
                }
              }), n)
          })), function () {
          var t = this, r = arguments
          return new Promise((function (o, e) {
            var u = n.apply(t, r)

            function c (n) {i(u, o, e, c, f, 'next', n)}

            function f (n) {i(u, o, e, c, f, 'throw', n)}

            c(void 0)
          }))
        })
        return function () {return t.apply(this, arguments)}
      }()
```

**Comment by balazsorban44** [comment]
I did some digging, this is because we don't currently pass the Browserslist config to SWC (default compiler over Babel since Next 12).

This is planned to land when this RFC goes out: https://github.com/vercel/next.js/discussions/33227

So please follow that for further information.

Thanks for reporting! :pray:

**Comment by timneutkens** [comment]
You can now add browserslist when enabling an experimental flag: https://github.com/vercel/next.js/discussions/33227#discussioncomment-3047837
