### ISSUE TITLE
Docs: Redux Toolkit example

### ISSUE THREAD

**Issue by Elabbasy00** [vercel/next.js#33998]
### What is the improvement or update you wish to see?

redux toolkit with Next.js with a clear way

### Is there any context that might help us understand?

There are a lot of opinions about including Redux in Next
We do not know which of them are correct, nor do we have to use an external library or not

I searched a lot and found a lot of examples, all in different ways, and they all warn of losing the features of Next

I finished running Redux as follows

**store.js**

```
import { configureStore } from '@reduxjs/toolkit';
import reducers from './rootReducer';

export function makeStore() {
  return configureStore({
    reducer: reducers,
  });
}

const store = makeStore();

export default store;
```

**_app.js**

```
import React from 'react';
import { Provider } from 'react-redux';
import store from '../redux/store';

const MyApp = ({ Component, ...rest }) => {
  return (
    <Provider store={store}>
      <Component {...rest} />
    </Provider>
  );
};

export default MyApp;
```
**i'm wondering if I lost Next features like this or not

**Or do I have to use something like `next-redux-wrapper`

**Is it necessary to use useDispatch() in getStaticProps && getServerSideProps or as usually

**Is there a better way?

**Comment by balazsorban44** [comment]
We have a few examples in this repository, like:

https://github.com/vercel/next.js/tree/canary/examples/with-redux

You can check the others as well in: https://github.com/vercel/next.js/tree/canary/examples
