### ISSUE TITLE
Docs: https://tailwindcss.com/docs/guides/nextjs

### ISSUE THREAD

**Issue by RaHuLMeghani24** [vercel/next.js#34009]
### What is the improvement or update you wish to see?

Hello, I am trying to use this command as an example: npx create-next-app --example with-tailwindcss with-tailwindcss-app. However, this command only creates the next app with the Typescript project. In previous versions, it was used to create javascript projects. When I try to manually edit the extension .ts & .tsx, it throws an error. 

I am looking for an update on the docs since as of now this command only creates typescript projects. Please help.

### Is there any context that might help us understand?

Please share the command which can create next app with the javascript project along with the tailwind css.

### Does the docs page already exist? Please link to it.

https://tailwindcss.com/docs/guides/nextjs

**Comment by balazsorban44** [comment]
Hi. Going forward, we are going to prefer TypeScript as the default language for examples. It prevents a lot of issues, even for newcomers.

This is briefly hinted at here: https://github.com/vercel/next.js/blob/canary/contributing.md#adding-examples

I guess this could be made more clear here:

https://nextjs.org/docs/api-reference/create-next-app#options

**Comment by RaHuLMeghani24** [comment]
I understand. Thank you for your quick response. I appreciate it. I'll close this issue.
