### ISSUE TITLE
Caching 404 pages that should be updated with ISR

### ISSUE THREAD

**Issue by bscaspar** [vercel/next.js#34006]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 14.17.6
      npm: 6.14.15
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.17.6

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

Our app lets our users create their own static pages at `hoo.be/[username]` using ISR with `fallback: blocking` and `revalidate: 60`.

If a user navigates to a page that does not exist, for example to see if that `[username]` path is still available, they initially receive a 404, which is expected. If, after that, the user creates a page at that path, the site continues to return a 404 even when it should return a 200 with that user's recently created page. This has worked as expected for the past year+ until we recently updated next to v12.0.10.

If a user does _not_ first verify that the page does not exist, and does not see the initial 404, after creating their page, the page is built successfully, no issue with the cached 404 page.

Rebuilding the production site resolved the issue with the cached 404 and displayed the static page as expected.

We have triple checked that all API calls work as expected when generating the page. All previously existing pages work as expected, and are frequently regenerated with no issue. We see no errors in any of our logs to indicate any issue with our backend or deployments. 

Furthermore, we have validated that this new `[username]` path is returned from our `getStaticPaths` function and the data for this page is returned as expected from the `getStaticProps` call in the same page.

We have attempted to invalidate the cache using a `Cache-Control=no-cache` header, a `_vercel_no_cache=1` cookie, and a `?_vercel_no_cache=1` request parameter, all of which still return a `x-vercel-cache=HIT` response header on the 404 page (see below). 

Here are the response headers when attempting to navigate to one of these static page and instead receiving a 404: 
```
age: 2769
cache-control: public, max-age=0, must-revalidate
content-encoding: br
content-type: text/html; charset=utf-8
date: Fri, 04 Feb 2022 18:10:30 GMT
etag: W/"186b-Cr2VyfbtEM9oCOXdZn4uqF7FLXs"
server: Vercel
strict-transport-security: max-age=63072000
x-matched-path: /[username]
x-powered-by: Next.js
x-vercel-cache: HIT
x-vercel-id: cle1::iad1::cxhck-1644000999981-03d536d907c2
```

### Expected Behavior

The 404 page is not cached and the newly created site is built and served to the user as expected.

### To Reproduce

1. Navigate to a static page at a url like `hoo.be/[username]` on our site that does not exist, get the 404 page.
2. Create a page at the `[username]` site that was previously visited.
3. Revisit the `hoo.be/[username]` site and expect to see the recently built page, but get the 404 instead.

**Comment by bscaspar** [comment]
Possibly related: #22579, #10551

**Comment by bscaspar** [comment]
I was able to resolve this by adding the following to my custom 404 page: 
```js
export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {},
    revalidate: true,
  };
};
```

I am not sure whether this is a bug or not but this behavior didn't happen before I updated Next to v12. 

I really like using Next and understand the authors make tradeoffs between giving developers freedom to build how they want vs embedding opinion/best practices into the library design. In this case it seems that I shouldn't need to add a `revalidate` prop to the 404 page to make it work, but perhaps this is one of those tradeoffs.

**Comment by ijjk** [comment]
Hi, I'm not able to reproduce this with the information provided. Is `notFound: true` being used on the dynamic page, if so is `revalidate` being returned in that case as well? The default behavior when `revalidate` is not returned is to never revalidate as documented [here](https://nextjs.org/docs/api-reference/data-fetching/get-static-props#revalidate). 

https://user-images.githubusercontent.com/22380829/152613000-4536a8dd-0ddc-4676-8462-c77df9f6252e.mp4

**Comment by bscaspar** [comment]
I see - in our case when `notFound` is returned, the `revalidate` prop is not included.

In my mental model, when using `fallback: 'blocking'` a 404 page would attempt to re-render the page on subsequent requests to the same path. It sounds like I was thinking about it slightly wrong - 404 pages are treated the same way as other statically generated pages and cached for a given path. 

What was also confusing is that this seemed to work before updating to next v12. Perhaps it's just something we didn't catch.

**Comment by balazsorban44** [comment]
`notFound` should be used when your data source (like a CMS) cannot return the data for a certain path. Since the data can be updated by the CMS authors at a later time, `notFound`+`revalidate` allows your site to recover from a 404 without a redeploy.
