### ISSUE TITLE
Docs: broken example link on `next/image` API reference page

### ISSUE THREAD

**Issue by ThomasRettig** [vercel/next.js#34013]
### What is the improvement or update you wish to see?

The link https://image-component.nextjs.gallery/color under the [blurDataURL](https://nextjs.org/docs/api-reference/next/image) section of the [next/image](https://nextjs.org/docs/api-reference/next/image) docs returns a **404 error**.

### Is there any context that might help us understand?

The link should be permanently removed from the docs if it's repository no longer exists. If this is not the case, and maybe the URL was accidentally changed, the link should be updated to reflect the new URL. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/image

**Comment by balazsorban44** [comment]
Thanks!

The source code is here: https://github.com/vercel/next.js/blob/canary/examples/image-component/pages/color.js

So this might just need a redeploy. cc @styfle?

**Comment by styfle** [comment]
Thanks, I deployed the example and that page is available now! https://image-component.nextjs.gallery/color
