### ISSUE TITLE
SWC tree shaking not exposed/documented?

### ISSUE THREAD

**Issue by kfranqueiro** [vercel/next.js#34010]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.18.2
      npm: 7.19.1
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.18.2

### What browser are you using?

N/A

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I was curious to try out the SWC tree-shaking transform that was supposedly added in 12.0.8 via https://github.com/vercel/next.js/pull/32253/files; however, I'm not sure whether it's fully implemented?

Looking at the PR I expected it's an option that needs to be turned on, but there seem to be no typings for `shakeExports` within `NextConfig`, and it doesn't seem to be anywhere in `packages/next/build/swc/options`. It also doesn't seem to appear in next's documentation.

Am I misreading this and it's supposed to be on by default, or is it not actually exposed? (The setup in lib.rs looks conditional to me, though it's slightly different than the ones immediately above it for `remove_console` and `react_remove_properties`.)

### Expected Behavior

I'd expect to see some difference in build size between the same app with vs. without `nextConfig.experimental.shakeExports` or `nextConfig.shakeExports` (whichever it was intended to be added to)

### To Reproduce

- Run a build of any app, observe build size
- Run another build with `shakeExports: true` added to `next.config.js` (either top-level or under `experimental`), observe build size again

**Comment by kfranqueiro** [comment]
Thanks for the reply. The reason I opened this is because 12.0.8's changelog made it sound like this was done, and the feature request asking for it was closed when that PR was merged, which seems like that might not be the right move if the feature isn't actually available yet. So I'm a little worried that there's nothing visibly tracking whatever steps are left before it becomes available?

**Comment by balazsorban44** [comment]
The source of truth for any update towards users is the documentation. The changelog simply keeps track of the work that has been done. :+1: The PR you linked to also did not add any option like `shakeExports: true`, another good indicator that the feature isn't ready yet, or even might be solved differently in a later release.

Bigger updates also appear on our blog here: https://nextjs.org/blog

Hope that clears things up! :green_heart:
