### ISSUE TITLE
next/inline-script-id does not handle JSXSpreadAttributes correctly

### ISSUE THREAD

**Issue by no-yan** [vercel/next.js#34030]
### What version of Next.js are you using?

canary

### What version of Node.js are you using?

16.13.0 

### What browser are you using?

no

### What operating system are you using?

Ubuntu 20.04.3 LTS

### How are you deploying your application?

no

### Describe the Bug

In response to comment: https://github.com/vercel/next.js/pull/32421#issuecomment-1028927660

An error occurs because the rule `next/inline-script-id` does not handle JSXSpreadAttribute  correctly.
After #32178, It may still give an error when there is a JSXSpreadAttribute.
JSXSpreadAttribute can be any AssignmentExpression ([Spec](https://github.com/facebook/jsx#syntax)) , but inline-script-id only supports special cases.
That is based on the assumption, every JSXSpreadAttribute have property `key.name`.

Source:
https://github.com/vercel/next.js/blob/6b73acfaf5c782358258f737942d691af7b4162f/packages/eslint-plugin-next/lib/rules/inline-script-id.js#L34-L36

When a `SpreadAttribute` is passed, it will be a variable in most cases. If so, Eslint cannot find the property name.
To support other cases, we can build some complex logic, but I don't think it is worth it.
Can't we simply ignore the `JSXSpreadAttribute`?

### Expected Behavior

Rules should not report error when `JSXSpreadAttribute` is exist.

### To Reproduce

The failing case I checked is the following code.

    {
      code: `import Script from 'next/script';
      const spread = { strategy: "lazyOnload" }
      export default function TestPage() {
        return (
          <Script {...spread} id={"test-script"}>
            {\`console.log('Hello world');\`}
          </Script>
        )
      }`,
    },
You can confirm AST of this by using https://astexplorer.net/ .
@stefanprobst

**Comment by no-yan** [comment]
I would like to implement this, but I would like to hear your opinion first.

**Comment by ijjk** [comment]
Hi, thanks for looking into this, yeah if the spread attribute is not able to be checked for the values we should definitely ignore it in that case instead of showing an error, a PR updating this would be welcome!

**Comment by rohan-kulkarni-25** [comment]
Hey @ijjk  !! I will like to work on this issue can you please guide me on this !!
