### ISSUE TITLE
Not loading/fast refreshing as it should

### ISSUE THREAD

**Issue by hyoretsu** [vercel/next.js#34037]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Mon Nov 22 18:52:15 UTC 2021
    Binaries:
      Node: 16.13.1
      npm: 8.2.0
      Yarn: 1.22.17
      pnpm: 6.24.1
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Microsoft Edge v98.0.1108.43

### What operating system are you using?

Windows 11 with WSL2 (Ubuntu 21.10)

### How are you deploying your application?

next dev

### Describe the Bug

Local changes aren't reflected in dev server. The terminal says "compiling...", the site visually shows the reloading icon, but nothing happens. I also can't ever get F5 to work, only through Ctrl+R, either a single or a couple of times. After some time, the URL may also become "about:blank". Sometimes I get the full reload error.

```
Fast Refresh will perform a full reload when you edit a file that is imported by modules outside of the React rendering tree. It is also possible the parent component of the component you edited is a class component, which disables Fast Refresh. Fast Refresh requires at least one parent function component in your React tree.
You can find more information in the related error below:

TypeError: Failed to fetch
    at __webpack_require__.hmrM (http://localhost:3000/_next/static/chunks/webpack.js?ts=1644173524897:1156:20)
```

Strangely enough, it worked normally a few weeks ago. I even tried updating all my packages, but it didn't work.

### Expected Behavior

Fast Refresh should work like normal.

### To Reproduce

Make any change in [this project](https://github.com/hyoretsu/aufklarung-site). It seems to be more often triggered by changes in http://localhost:3000/admin/submissions, though I've confirmed it also happens in homepage.

**Comment by hyoretsu** [comment]
Also started happening on another project of mine, I'm starting to think that it's rather something on my PC/WSL

**Comment by balazsorban44** [comment]
Just curious. You stated that you are using `next@12.0.10`, but in your linked repository, it says `"next": "^11.1.2",`.

So which one is correct?

`webpack` should not be a dev dependency either.

I struggle to start your repository. Could you create a simplified version, removing everything that does not add to the issue at hand? You might find the problem along the way.

**Comment by hyoretsu** [comment]
I'd forgot to do a `git push`. I'm now using default Next server at @12.0.10, http, and that route exists.

I needed `webpack` as a dev dependency because I'm using PNPM, so I couldn't simply `import webpack from 'webpack';` using the copy that Next.js installed. (needed types for TS Next config I was using)

I'll try to minimize things in that repo, though if you can still fast refresh **a couple of times** even at that route it's likely something I have to fix on my machine. (Though not as simple as restarting)

**Comment by balazsorban44** [comment]
The route still did not exist, but it was probably just a typo `http://localhost:3000/admin/submission` -> `http://localhost:3000/admin/submissions` :sweat_smile: But that's alright. Having another look now :+1: Thanks for updating.

**Comment by hyoretsu** [comment]
Yeah, it's something wrong with my WSL, it also works fine on Windows here. Just gotta figure out what exactly.
