### ISSUE TITLE
Seo warning when use intrinsic layout 

### ISSUE THREAD

**Issue by Jayden-San** [vercel/next.js#34036]
### What version of Next.js are you using?

^12.0.7

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

chrome

### What operating system are you using?

linux

### How are you deploying your application?

next start

### Describe the Bug

when we use intrinsic layout of next image component, the first image that create not have a alt value and seo get a warning and the score of site comes down. and for solve that we try to use another layout but the quality of images was very low.

### Expected Behavior

To solve this problem we want to add the default alt for the next image component

### To Reproduce

![alt](https://user-images.githubusercontent.com/99136031/152692668-a7baea2b-6764-4791-8e78-cc818b54ebfc.png)

**Comment by balazsorban44** [comment]
As shown on the image above, `aria-hidden: true` is set, which means SEO tools should ignore that placeholder image.

See: https://github.com/vercel/next.js/issues/26045#issuecomment-1000001296
