### ISSUE TITLE
Missing version in workspace for a new nextjs app in turborepo.

### ISSUE THREAD

**Issue by tvarwig** [vercel/next.js#34059]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: linux
      Arch: x64
      Version: #15-Ubuntu SMP Wed Jan 12 19:18:58 UTC 2022
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

Kubernetes

### Describe the Bug

When adding a new nextjs app in a turborepo workspace the `version` is missing in the `package.json`. When you run `yarn install` or `yarn build` You get a message that says `warning Missing version in workspace at "/workspace/apps/my-app", ignoring.`. 

This will be fixed by adding a default version like `0.0.0` in the default NextJS `package.json` template. 

### Expected Behavior

`yarn install` and `yarn build` should work without having to add a `version` to the `package.json`

### To Reproduce

```
npx create-turbo@latest &&
cd apps &&
npx create-next-app@latest --ts my-app &&
yarn install
```

**Comment by balazsorban44** [comment]
This has been fixed in https://github.com/vercel/next.js/pull/33006

Please use `npx create-next-app@canary` for now or wait for the next `latest` release.
