### ISSUE TITLE
Cannot find module 'react-is'

### ISSUE THREAD

**Issue by victorenaud** [vercel/next.js#34050]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Thu Jan 20 13:58:19 UTC 2022
    Binaries:
      Node: 17.3.0
      npm: 7.24.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

```
FROM node:16.13-alpine3.15 AS builder

WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN yarn build
RUN yarn install --production --ignore-scripts --prefer-offline

FROM node:16.13-alpine3.15 AS runner
WORKDIR /app

ENV NODE_ENV production

COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

CMD ["yarn", "start"]
```

### Describe the Bug

On start, the following error is raised and prevent the app from launching.
It works in Next.js 12.0.7
The bug occured since Next.js 12.0.9

I'm not able to reproduce on my computer...
But the bug occurs consistently when deploying the docker image 

```
Error: Cannot find module 'react-is'
Require stack:
- /app/node_modules/styled-components/dist/styled-components.cjs.js
- /app/.next/server/pages/_document.js
- /app/node_modules/next/dist/server/require.js
- /app/node_modules/next/dist/server/next-server.js
- /app/node_modules/next/dist/server/next.js
- /app/node_modules/next/dist/server/lib/start-server.js
- /app/node_modules/next/dist/cli/next-start.js
- /app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/styled-components/dist/styled-components.cjs.js:1:145)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/styled-components/dist/styled-components.cjs.js',
    '/app/.next/server/pages/_document.js',
    '/app/node_modules/next/dist/server/require.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/node_modules/next/dist/server/next.js',
    '/app/node_modules/next/dist/server/lib/start-server.js',
    '/app/node_modules/next/dist/cli/next-start.js',
    '/app/node_modules/next/dist/bin/next'
  ]
  ```

### Expected Behavior

The app should start

### To Reproduce

Install the application in docker, build, and start.

**Comment by balazsorban44** [comment]
I'm not able to run your example, as the `Dockerfile` does not look complete.

We have an official recommendation for how to deploy with Docker. You might want to have a look at that:
https://nextjs.org/docs/deployment#docker-image

See our recommended `Dockerfile`:
https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

**Comment by victorenaud** [comment]
Sorry @balazsorban44 
The example was incomplete, as I put it here only for illustration.

I looked into this matter a little more today.
I pinpointed the issue to what version of `react-is` is hoisted by yarn.
You can try with the docker image of this [repo](https://github.com/victorenaud/next-bug-illustration)

While `styled-component` was the only dependency, `react-is@16.13.1` was hoisted and all was working well.
When I added some more dependencies using another version, `react-is@17.0.2` became the hoisted version of `react-is`.

And that broke the docker image.
ie if I launch the docker image and try to access the website, the error `Error: Cannot find module 'react-is'` is shown

If I go back to next.js version `12.0.8`, all is good again.
So I suppose something in `12.0.9` broke the build?

**Comment by balazsorban44** [comment]
I'll have another look, thanks.

**Comment by balazsorban44** [comment]
I found this note in `styled-components` docs: https://styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v5

https://github.com/styled-components/styled-components/issues/2874


Nonetheless, I simply swapped your `Dockerfile` with this: https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

And the server works fine!

**Comment by victorenaud** [comment]
I tried the recommended Dockerfile, and it worked, thank you!

Moreover, it reduced our containers sizes by ~50%, which is a nice side-effect. :tada:
