### ISSUE TITLE
`next build` fails with `The "path" argument must be of type string` with WebWorker within workspaces

### ISSUE THREAD

**Issue by andreypopp** [vercel/next.js#34064]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Debian 5.15.5-2~bpo11+1 (2022-01-02)
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: 6.30.0
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Chrome, Safari, ...

### What operating system are you using?

Linux

### How are you deploying your application?

next build

### Describe the Bug

With the setup described at https://github.com/andreypopp/next-repro-25484 `next build` command fails with:

```
webpack/runtime/compat
The "path" argument must be of type string. Received undefined
```

### Expected Behavior

`next build` is expected to build this correctly

### To Reproduce

This is using `pnpm` and workspaces. Note that I was able to reproduce this with `yarn` workspaces as well but in some configurations. Here I can reliably reproduce it with `pnpm`.

```
git clone git@github.com:andreypopp/next-repro-25484.git
cd ./next-repro-25484
pnpm install
(cd with-web-worker/ && pnpm run build)
```

**Comment by balazsorban44** [comment]
Just curious, is this actually related to workspaces or have you been able to reproduce in a single application as well? We should try to keep the reproduction minimal if that's the case.

**Comment by andreypopp** [comment]
@balazsorban44 this is the minimal repro I've been able to come up with, sorry.

I think this is related to workspaces, yeah (both with yarn and pnpm, though with yarn it doesn't manifest itself in this repro)

**Comment by balazsorban44** [comment]
We identified the issue and this is being addressed, thanks!
