### ISSUE TITLE
Middleware redirect has different behavior between production and development enviroment

### ISSUE THREAD

**Issue by luucas-melo** [vercel/next.js#34067]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: linux
      Arch: x64
      Version: #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.1

### What browser are you using?

Firefox

### What operating system are you using?

Linux, Ubuntu 20.04

### How are you deploying your application?

aws

### Describe the Bug

Middleware redirect has a different behavior between production mode and development mode. In production mode the redirect is permanent, so if client side is redirected from route A to B route them it's not possible to redirect to route A.

### Expected Behavior

If user is redirect from route A to B due to a conditional, them it should be possible to redirect to route A once that conditional is met.

### To Reproduce

The link below has a example application 
https://github.com/luucas-melo/client-side-redirect-middleware-not-working

Steps: 

## Run production environment

- yarn build 
- yarn start

## Flow

- click 'protected page' button
(redirected to login page)
- click 'signin' button
(should be redirected to protected page but it stays in the same page)
- try to click in the 'protected page' button or the 'link to /protected-page'

**Comment by balazsorban44** [comment]
Sidenote, NextAuth.js (I'm the maintainer 👋) has an official way of using Middleware here: https://next-auth.js.org/configuration/nextjs#middleware
