### ISSUE TITLE
create-next-app is failing with an invalid github url

### ISSUE THREAD

**Issue by spullara** [vercel/next.js#34073]
### Run `next info` (available from version 12.0.8 and up)

12.0.10 version of create-next-app

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

17.1.0

### What browser are you using?

edge

### What operating system are you using?

windows

### How are you deploying your application?

vercel

### Describe the Bug

When you try and install from a template it says the github url is invalid.

### Expected Behavior

start with the template provided

### To Reproduce

npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa my-medusa-storefront

**Comment by balazsorban44** [comment]
Hi, I could not reproduce this, here is my output:

```sh
npx create-next-app -e https://github.com/medusajs/nextjs-starter-medusa 34073
Need to install the following packages:
  create-next-app
Ok to proceed? (y)
Creating a new Next.js app in /.../34073.

Downloading files from repo https://github.com/medusajs/nextjs-starter-medusa. This might take a moment.
```

Make sure you don't have a typo or an invisible/bad character somewhere. :thinking:
