### ISSUE TITLE
When I use _middleware for redirection, all my images break

### ISSUE THREAD

**Issue by matiasdc1** [vercel/next.js#34079]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 15.11.0
      npm: 7.6.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

15.11.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

It is locally hosted.

### Describe the Bug

So, as the title says, when I use middleware for redirection, all the images on the redirect path are broken.  I redirect everything to /browse. In /browse all images are broken.

Is this a bug or am I doing something wrong?
Everything worked until I implemented the _middleware.ts file. If I remove it, everything works.

### Expected Behavior

When I add the _middleware.ts file, all  images using next/image should work without changing anything.

### To Reproduce

This is the _middleware.ts file:
```
import { NextResponse } from 'next/server'
import type { NextFetchEvent, NextRequest } from 'next/server'

export async function middleware(req: NextRequest, _ev: NextFetchEvent) {
  const url = req.nextUrl.clone()
  url.pathname = '/browse'
  const { pathname } = req.nextUrl
  if (pathname !== '/browse') {
    return NextResponse.redirect(url)
  }
  return NextResponse.next()
}
```

All images are in the public folder. I checked their names multiple times.
Just to show how I import the images, this is mainly what I display in the /browse page: 
```
import { selectedUserState } from '../atoms/selectState'
import Image from 'next/image'
import { useRecoilState } from 'recoil'

interface UserType {
  name: string
}

const User: React.FC<UserType> = ({ name }) => {
  const [user, setUser] = useRecoilState(selectedUserState)

  return (
    <div
      onClick={() => {
        setUser(name)
      }}
      className='text-center cursor-pointer hover:text-white '
    >
      <div className='h-[119px] w-30 border-white rounded-md border-0 hover:border-[1px]'>
        <Image src='/user.png' height={117} width={117} className='object-contain' />
      </div>
      <div>{name}</div>
    </div>
  )
}

const SelectUser = () => {
  return (
    <div className='bg-[rgb(20,20,20)] text-white flex flex-col h-screen'>
      <div className='px-10 py-5'>
        <Image src='/logo.svg' alt='logo' width={100} height={30} />
      </div>
      <div className='flex-grow flex flex-col justify-center items-center translate-y-[-8rem] space-y-10'>
        <div className='text-base md:text-xl lg:text-5xl'>Who is watching now?</div>
        <div className='flex text-[grey] space-x-5'>
          <User name='Matias' />
          <User name='Juan' />
          <User name='Victor' />
          <User name='Mafer' />
        </div>
        <div className='border-[1px] border-[grey] text-[grey] py-1 px-2 text-sm cursor-pointer hover:text-white hover:border-white'>
          Manage profiles
        </div>
      </div>
    </div>
  )
}

export default SelectUser

```
 Screenshots before and after: 
 
![image](https://user-images.githubusercontent.com/68567414/152909168-9a5da4a3-912e-4dd0-b880-383ada3591da.png)
![image](https://user-images.githubusercontent.com/68567414/152909219-73ec219b-6df9-4bf6-b1ec-bbea0d0b3689.png)

And yes, I am practicing my coding skills making a Netflix clone.

**Comment by icyJoseph** [comment]
Hi, I think you need to check which paths you allow to be redirected, like so:

```js
 return (
        path.startsWith('/api') || //  exclude all API routes
        path.startsWith('/static') || // exclude static files
        path.includes('.') // exclude all files in the public folder
    );
```

**Comment by matiasdc1** [comment]
Thanks!
It worked, so I added the condicional like this (There may be a better way but it works): 
```
export async function middleware(req: NextRequest, _ev: NextFetchEvent) {
  const url = req.nextUrl.clone()
  url.pathname = '/browse'
  const { pathname } = req.nextUrl

  if (
    pathname.startsWith('/api') ||
    pathname.startsWith('/static') ||
    pathname.includes('.')
  ) {
    return NextResponse.next()
  }

  if (pathname !== '/browse') {
    return NextResponse.redirect(url)
  }
  return NextResponse.next()
}

```
I was thinking the middleware only redirected the webpages. Didn't think that my implementation would redirect api and resource calls.
