### ISSUE TITLE
Docs: potential preview-mode error on production build

### ISSUE THREAD

**Issue by mingyeungs** [vercel/next.js#34129]
### What is the improvement or update you wish to see?

Under the [Clear the preview mode cookies](https://nextjs.org/docs/advanced-features/preview-mode#clear-the-preview-mode-cookies) section, It might be worth mentioning one should NOT use `<Link href="/api/to/clear/cookies/">...</Link>` to clear the preview-mode cookies.

### Is there any context that might help us understand?

`<Link />` are automatically prefetched in production built. When `<Link href="/api/to/clear/cookies/">Exit Preview</Link>` button is shown in preview mode, it gets prefetched and the preview cookies are cleared immediately.

In my case, the server is crashed whenever user enters preview mode (due to res.redirect() logic in my /preview/ api); in other setup, it might cause other unexpected behaviour.

The fix is simple though, simply use an <a /> tag and the issue is gone.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/preview-mode#clear-the-preview-mode-cookies

**Comment by balazsorban44** [comment]
Sounds good! Here is the file if anyone wanted to open a PR to fix this: https://github.com/vercel/next.js/blob/canary/docs/advanced-features/preview-mode.md

**Comment by mattyocode** [comment]
Does using a <Link /> component with  `prefetch={false}` solve the issue?

**Comment by deauna** [comment]
cheers

**Comment by mattyocode** [comment]
I'm happy to add a note about it to the docs
