### ISSUE TITLE
Unable to access request cookies in custom _app getInitialProps

### ISSUE THREAD

**Issue by fANZYo** [vercel/next.js#34138]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Sat, 29 Jan 2022 12:13:13 +0000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.9
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.9

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Google Chrome

### What operating system are you using?

Linux

### How are you deploying your application?

Vercel

### Describe the Bug

I am currently trying to set up auth persistence via a HttpOnly cookie set by a login api defined in `pages/api/login.ts`.

This api is called by the frontend when a login form is submitted. With the response is a `Set-Cookie` header that is successful

In `_app.ts` I want to access this cookie from the server via `getInitialProps`.

From everything i've been able to read so far this seem to be possible although this seems to only work for me when running `npm run dev` but when running `npm run build` followed by `npm start` the cookie is not accessible from the server and the `context.req.headers` property is an empty object. 

### Expected Behavior

I would expect the request cookies to be available to the server.

### To Reproduce

The most minimal example would be

```
// pages/_app.tsx
function CustomApp({ Component, pageProps, reqString }: CustomAppProps) {
  return (
    <>
        <pre>
          {reqString}
        </pre>
        <Component {...pageProps} />
    </>
  );
}

CustomApp.getInitialProps = async (context) => {
  return {
    cookie: JSON.stringify(context.ctx.req),
  };
};
```

The cookie is set like so
```
refreshToken=${refreshToken}; Max-Age=${expiresIn}; Secure; SameSite=Strict; Path=/; HttpOnly
```

This example will crash when running `npm run dev` as `req` won't exist but I would expect this to render the cookie when running in production. I'm also unable to log anything from the `getInitialProps` function.

**Comment by fANZYo** [comment]
Ok, further investigation this is caused by my pages having a `getStaticProps` defined. I might misunderstand how Next.js work.

My understanding is that `getStaticProps` triggers the page to be statically generated and will be rendered within `_app.tsx` on request after `getInitialProps` has done its thing. Making `_app.tsx` the perfect place to do global stuff like layout and auth.

Although this seems to be wrong. It would seem that adding a `getStaticProps` to a page forces `getInitialProps` to be run exclusively on the frontend for that specific page. 
Is that correct?

**Comment by lmoisz03** [comment]
Well, i recommend to use getServersideprops. I think there is a typo in 
```cookie: JSON.stringify(context.ctx.req),```
Context object contains req and res. Context ctx doesnt exists. Try instead context.req.

**Comment by fANZYo** [comment]
@lmoisz03 The issue with `getServerSideProps` is that if it wasn't for the auth bit, the whole website would be static. It's essentially a static website behind a subscription so I don't want to SSR it.

For your comments regarding `context.ctx` this is not a typo, despite the documentation, `getInitialProps`'s argument does not have a `req` property but does have a `ctx` property which has the `req` and `res` props.

**Comment by lmoisz03** [comment]
Hmm. You should avoid using it tho. By checking again on my website, i was able to get access to cookies.
```
Example.getInitialProps = async (ctx: NextPageContext) => {
  const cookies = ctx.req.headers.cookie
  return {
    cookies
  }
}
```
And it returned a server side response: 
`{"props":{"pageProps":{"cookies":"__Secure-ssid-...`

I don't understand what you mean with: The issue with getServerSideProps is that if it wasn't for the auth bit, the whole website would be static. It's essentially a static website behind a subscription so I don't want to SSR it.
Btw you should check this out: However, if getInitialProps is used in a custom _app.js, and the page being navigated to implements getServerSideProps, then getInitialProps will run on the server.

**Comment by lmoisz03** [comment]
Yes, I have a custom _app which contains my self-created session provider and a few other things. And the example that I showed you is the file that I just created to test your example. If you are building an SSG app you should use getServerSideProps or getStaticProps. 

And rethinking, SSG means that your site will be static and doesn't makes sence cookies in a static generated site since cookies can change or be revoked. I don't want to get in more details, but i want to know if your problem was solved or still need help.

**Comment by fANZYo** [comment]
Well so essentially I understand why it's behaving the way it is now. But here is what I'm trying to achieve
- I'm building an SSG site
- I want, before any static page is sent to the client, to check if the user has access to it
- If he does, send the page
- If he doesn't, redirect him to the landing page

I understand how this would be done the classic way (SSR) but it's like I said, if it weren't for the auth, there would be no hurdle with it being an SSG.

So maybe what I need is a middleware that handles the routing based on the auth token. Since all I need it to verify the auth on initial load. Which is why I thought the `getInitialProps` in the `_app` would do this job since it's meant to be run on the server on initial load but then on the client when following a `Link`. I would have essentially checked auth in the initial load on the server from `getInitialProps` and done nothing on the client.
