### ISSUE TITLE
`router.asPath` is different in server and in client with rewrites rules

### ISSUE THREAD

**Issue by sixclones** [vercel/next.js#34144]
### Run `next info` (available from version 12.0.8 and up)

<details>
<summary>info</summary>

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Oct 28 23:40:43 UTC 2020
    Binaries:
      Node: 16.13.0
      npm: 8.4.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

</details>

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying your application?

Vercel

### Describe the Bug

If a route has a rewrite rule (e.g. `{source: '/blog', destination: '/news'}`), the `router.asPath` property doesn't return the same result in server and in client.

This causes problem when using `router.asPath` to [check active link](https://github.com/vercel/next.js/blob/canary/examples/active-class-name/components/ActiveLink.js#L15) for example.
```jsx
<Link href={link.slug}>
  <a className={`${styles.link} ${router.asPath === link.slug ? styles.isActive : ''}`}>{link.label}</a>
</Link>
```
```
Warning: Prop `className` did not match. Server: "nav_link__PKDMm " Client: "nav_link__PKDMm nav_isActive__gTQA6"
```

I have encountered some more specific cases in the past, this one is the most obvious. But this seems to be a real issue to me or maybe I don't really understand what `rewrites` is for.

### Expected Behavior

`router.asPath` should contain the same thing in server-side and in client-side.

### To Reproduce

Clone https://github.com/sixclones/nextjs-router-issue

```
npm i
npm run dev
```

Open [localhost:3000/blog](http://localhost:3000/blog) and check the console. You should see the mentioned error.
Also inside your terminal, you should see
```
Log: -> Nav -> router.asPath /news
```
while on the browser, it displays
```
Log: -> Nav -> router.asPath /blog
```
---

I found several other issues talking about similar subjects but not really clearly, this is why I wanted to address it.
Possibly related #32772, #20488, #19574, #21040 & #21565

**Comment by xhoantran** [comment]
There is no issue with `rewrites`. You are trying to check whether a link is active by using `pathname` compare with the path that shown in the browser, which is `asPath`.

According to `Next.js` useRouter documentation:
- `asPath`: The path (including the query) shown in the browser without the configured basePath or locale.
- `pathname`: Current route. That is the path of the page in /pages, the configured basePath or locale is not included.

Without `rewrites`, there are many cases that this implementation doesn't work as expected. What I would recommend is changing the condition that compare `pathname` which is `router.pathname` and the destination route which is `link.route` in your issue demo.
