### ISSUE TITLE
Nextjs Image component stops working when configuring basePath

### ISSUE THREAD

**Issue by omerman** [vercel/next.js#34162]
### Run `next info` (available from version 12.0.8 and up)

      Operating System:
      Platform: darwin
      Arch: x64
    Binaries:
      Node: 17.3.0
      npm: 8.3.0
      Yarn: 1.22.4
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

17.3.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start / next dev

### Describe the Bug

Adding basePath to nextjs config, seems to make the public folder assets unavailable.
The basePath prefix is added, but the images are not shown.

The attached github repo is a created nextjs from docs `yarn create next-app --typescript` + added a one liner of basePath
https://github.com/omerman/nextjs-image-basePath-bug
**As you can see in this repo, the vercel icon at the bottom of the page does not show**

### Expected Behavior

The basePath should work well with Image component

### To Reproduce

As mentioned, 
1. `yarn create next-app --typescript`
2. added a one liner of basePath
3. run the app in either dev or prod mode (build & start)

See https://github.com/omerman/nextjs-image-basePath-bug
**As you can see in this repo, the vercel icon at the bottom of the page does not show**

**Comment by omerman** [comment]
![image](https://user-images.githubusercontent.com/6780529/153356683-53a9e16b-81d7-4696-b10f-03690c0d29eb.png)

**Comment by omerman** [comment]
![image](https://user-images.githubusercontent.com/6780529/153357251-d966ca4b-4c31-4646-a624-cacf8ecdf0b1.png)

**Comment by omerman** [comment]
![image](https://user-images.githubusercontent.com/6780529/153357356-ce7bc6d6-033d-419f-b8b5-2ebee1601630.png)

**Comment by balazsorban44** [comment]
When using `next/image`, you will have to apply the `basePath` as documented here:

https://nextjs.org/docs/api-reference/next.config.js/basepath#images
