### ISSUE TITLE
Dynamic route does not parse params correctly when unencoded

### ISSUE THREAD

**Issue by kudlajz** [vercel/next.js#34176]
### Run `next info` (available from version 12.0.8 and up)

```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
Binaries:
  Node: 17.1.0
  npm: 8.1.2
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.0.10
  react: 17.0.2
  react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

17.1.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS 11.5.2

### How are you deploying your application?

next start

### Describe the Bug

When using `getServerSideProps`, `context.params` is `undefined` when unencoded URL path is the same as the dynamic route's name.

Consider having a route called `[slug].tsx`.

If you access `/[slug]`, `context.params` equals `undefined` ✖️ 
If you access `/%5Bslug%5D`, `context.params` equals `{ slug: '[slug]' }` ✔️ 
If you access `/foo[slug]`, `context.params` equals `{ slug: 'foo[slug]' }` ✔️ 
If you access `/[slug]foo`, `context.params` equals `{ slug: '[slug]foo' }` ✔️ 
If you access `/[uuid]`, `context.params` equals `{ slug: '[uuid]' }` ✔️ 

Minimal working example: https://github.com/kudlajz/nextjs-dynamic-route

### Expected Behavior

For `/[slug]` URL path, `context.params` should be correctly defined as `{ slug: '[slug]' }`

### To Reproduce

1. Create a dynamic route, e.g. `pages/[slug].tsx`
2. Define `getServerSideProps` function
3. Access `/[slug]` in your application (make sure the brackets are not encoded)
4. Check value of `context.params` inside `getServerSideProps`

**Comment by balazsorban44** [comment]
Hi, this has been fixed on `canary` already (https://github.com/vercel/next.js/pull/33808), please upgrade or wait for the next `latest` release.
