### ISSUE TITLE
12.0.9-canary.11 5x'd size of edge SSR bundle

### ISSUE THREAD

**Issue by leo** [vercel/next.js#34185]
### Run `next info` (available from version 12.0.8 and up)

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101
Binaries:
  Node: 16.14.0
  npm: 8.3.1
  Yarn: 1.22.17
  pnpm: 6.30.1
Relevant packages:
  next: 12.0.9-canary.11
  react: 18.0.0-rc.0-next-fe905f152-20220107
  react-dom: 18.0.0-rc.0-next-fe905f152-20220107
```

### What version of Next.js are you using?

12.0.9-canary.11

### What version of Node.js are you using?

16.14.0

### What browser are you using?

Chrome (latest)

### What operating system are you using?

macOS (latest)

### How are you deploying your application?

Vercel

### Describe the Bug

- Version `12.0.9-canary.9` of Next.js comes with fairly small edge SSR bundles (∼ a few hundred KB in total).
- Version `12.0.9-canary.10` doesn't exist on npm (FYI, just to clarify that there's no version in between).
- Version `12.0.9-canary.11` **made their size shoot up to over 1,3 MB (∼ x5) for just a single chunk**.

Initially, I assumed this would be a problem in my own application, but after hours of investigation, I got to understand that version `12.0.9-canary.9` of Next.js didn't have this problem, and that `12.0.9-canary.11` had introduced it.

It was probably caused by https://github.com/vercel/next.js/pull/33635, is my guess.

## Analysis of version `12.0.9-canary.11`

![CleanShot 2022-02-10 at 15 12 06@2x](https://user-images.githubusercontent.com/6170607/153431957-e6ded782-3dbf-44d2-a679-1a9494c933f0.png)

## Analysis of version `12.0.9-canary.9`

![CleanShot 2022-02-10 at 15 12 50@2x](https://user-images.githubusercontent.com/6170607/153432023-ee0b5706-bf3c-4805-96f6-c1d842e3b419.png)

### Expected Behavior

It seems unintentional that the size of individual edge SSR bundles was increased by **5x**, just to support the expected functionality when rendering.

It'd be great if they'd return to a size that's closer to their original one, since a larger bundle effects the server-rendering performance (that's part of the reason why [Cloudflare Workers](https://developers.cloudflare.com/workers/platform/limits#script-size) [and probably others too] limit them to 1 MB by default, which is now being exceeded as of `12.0.9-canary.11`).

Also note that [next-rsc-demo](https://github.com/vercel/next-rsc-demo) worked just fine before `12.0.9-canary.11`. I understand that new functionality was added, but the penalty for that seems to be way too large.

### To Reproduce

1. Clone Vercel's [next-rsc-demo](https://github.com/vercel/next-rsc-demo)
2. Upgrade the `next` dependency to `12.0.9-canary.9`
3. Notice that the bundle files in `.next/server/chunks` have a "reasonable" size
4. Upgrade the `next` dependency to `12.0.9-canary.11`
5. Notice that the bundle files in `.next/server/chunks` have suddenly shot up to over 1 MB for one chunk

**Comment by icyJoseph** [comment]
Hi,

I do see that a chunk shoots up to 1.3MiB on `12.0.9-canary.11`.

```shell
    1.3 MiB [##########]  817.js
   28.0 KiB [          ]  40.js
    8.0 KiB [          ]  863.js
    4.0 KiB [          ]  976.js
    4.0 KiB [          ]  144.js
    4.0 KiB [          ]  font-manifest.json
```

Is there any limitation for you to try `12.0.11-canary.11`? I have tried with that build, and the error is gone.

```shell
   76.0 KiB [##########]  664.js
   16.0 KiB [##        ]  755.js
    4.0 KiB [          ]  320.js
    4.0 KiB [          ]  730.js
    4.0 KiB [          ]  font-manifest.json
```

**Comment by leo** [comment]
@icyJoseph Have you changed anything else when switching to `12.0.11-canary.11`?

For me, anything above `12.0.9-canary.11` (and therefore also `12.0.11-canary.11`) has this problem.

**Comment by leo** [comment]
To verify what I said above, run `npm install` and `ANALYZE="1" npm run build` in [this repo](https://github.com/leo/next-rsc-demo-test).

This is the result I got:

![CleanShot 2022-02-10 at 17 29 34@2x](https://user-images.githubusercontent.com/6170607/153452626-71b5cdf6-901d-439d-a136-81e5d6daa029.png)

**Comment by icyJoseph** [comment]
Aha, now I got it. Confirmed. Somewhere, there's a Buffer being used! I think that explains `crypto-browserify`'s present, and probably `raw-body`. 

Sorry for the initial misfire. It seems I had messed up the runtime value.

I'll keep looking around.

**Comment by shuding** [comment]
Hi all, thanks for reporting & looking into this! We are aware of the size increase, and we are work on optimizing the base server. Will keep this issue open for tracking. 🙏

**Comment by leo** [comment]
@shuding I think this issue can be closed now, correct?
