### ISSUE TITLE
Preflight request failures should not block navigation

### ISSUE THREAD

**Issue by javivelasco** [vercel/next.js#34199]
When the Next.js application shows a `Link` to a route that holds a middleware in its routing path, we run what is called a "preflight" request. This is intended to know how the client should behave when navigating to that location. This points to the bundle that should be preload, the redirection target if any, etc.

Currently, when this request fails, the client is no longer able to navigate and clicking the `Link` would just not work. In such cases, the client should control the error and instead perform a hard navigation to the link once it is clicked.

**Comment by nkzawa** [comment]
Does this just mean to ignore the error completely, or give a way to control what to do by like a flag or a callback?
