### ISSUE TITLE
All requests hang when cached image file was not found

### ISSUE THREAD

**Issue by marvinhagemeister** [vercel/next.js#34207]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Mon Nov 8 10:21:19 UTC 2021
    Binaries:
      Node: 17.0.1
      npm: 8.1.0
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

17.0.1

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

macOS, Linux

### How are you deploying your application?

Other

### Describe the Bug

Recently we've been getting some errors related to `next/image` where an image can't be found in next's cache:

```bash
error - uncaughtException: Error: ENOENT: no such file or directory, open '/app/packages/site/.next/cache/images/k047C0elIKHtnLBAtmwyI9B0nG2dKQwBTRFKitkIoQs=/0.1644532318506.DGOAZdRAgewk9fNp-mGpwXURSS4EgdYLu3eUeulx-p0=.svg'
error - uncaughtException: Error: ENOENT: no such file or directory, open '/app/packages/site/.next/cache/images/RRuKhCDW2R3bFiKaDC8qwXI7Paz066iKB9zwh8afjQI=/0.1644530873477.XABC8G+tsSfUO8fINYyc9XbXRxsjRPxMYefuKC6VM9g=.webp'
```

Once that happens the server stops responding to any requests send to it.

### Expected Behavior

A cache miss of an optimized image shouldn't make the server completely unresponsive. The server should continue to process incoming requests.

### To Reproduce

I can reliable reproduce it in my client setup, but haven't been able to narrow it down to an isolated test case so far. I'm afraid I can't share the repo publicly due to NDAs.

**Comment by ijjk** [comment]
Hi, this has been updated in the latest version of Next.js `v12.0.11-canary.12`, please update and give it a try!
