### ISSUE TITLE
Middleware Size Limit Calculation

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [vercel/next.js#34201]
### Run `next info` (available from version 12.0.8 and up)

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.1.0
      npm: 7.12.0
      Yarn: 1.22.17
      pnpm: 6.17.2
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

10.0.10

### What version of Node.js are you using?

16.1.0

### What browser are you using?

sidekick

### What operating system are you using?

windows

### How are you deploying your application?

vercel

### Describe the Bug

the size limit of the middleware (edge function) is exceeded when it shouldn't. after checking the size of the modules I used with bundle.js.org and it was only under 700kb.
![clients – Deployment Overview](https://user-images.githubusercontent.com/42802922/153481841-7288f377-f55e-4d79-8eef-aceaa74564b7.png)
 

### Expected Behavior

accept the middleware as it is without throwing an error!

### To Reproduce

Unfortunately, I couldn't reproduce it, but I can provide access to the deployment in Vercel if it might be helpful. 

Here is the link to the repo with the middleware code that causes the error. 
https://github.com/Ali-Hussein-dev/nextjs-edge-function

**Comment by balazsorban44** [comment]
I get different number when I try to build your reproduction, both locally and on Vercel.

Here is a successful build from Vercel, this does not trigger the error you show above.

```sh
Page                                       Size     First Load JS

┌ ○ /                                      2.69 kB        71.7 kB
├   └ css/92ff1f22dd9892a3.css             664 B
├   /_app                                  0 B              69 kB
├ ○ /404                                   2.84 kB        71.8 kB
├ ƒ /api/_middleware                       289 kB          358 kB
└ λ /api/hello                             0 B              69 kB
+ First Load JS shared by all              69 kB
  ├ chunks/framework-9f7c4d28dae9e00d.js   42 kB
  ├ chunks/main-96060e10e65c9c86.js        24.9 kB
  ├ chunks/pages/_app-5ff7d090283f2fbe.js  553 B
  ├ chunks/webpack-b50f92b546454389.js     1.48 kB
  └ css/27d177a30947857b.css               194 B
```

Is it possible that you have removed some dependencies compared to when you took the screenshot? That could explain why this is working now. I would need the exact same code as when the screenshot was taken to be able to verify if there is an issue. :pray:

**Comment by Ali-Hussein-dev** [comment]
@balazsorban44 the only difference is typescript. otherwise, it is the same. 
I deployed the reproduction also and got a successful build!

**Comment by balazsorban44** [comment]
Adding TypeScript shouldn't have resulted in a 270kb difference compared to your picture. :eyes: 

If even you cannot reproduce it anymore, this might have been a one-time thing then. Note, Middleware is still in beta. We will keep an eye out for this, thanks for reporting anyway!
