### ISSUE TITLE
Use of eval in code is triggering OWASP ZAP scan

### ISSUE THREAD

**Issue by eelcobosklopper** [vercel/next.js#34226]
### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.6.1

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

We have a OWASP ZAP scan in our pipeline and it found an eval in our code:
`"%eval%":eval`
It seems to be coming from either of 2 dependencies in Nextjs: assert.js or util.js. 

### Expected Behavior

No usage of eval

### To Reproduce

In the next.js project `"%eval%":eval` can be found in 2 precompiled dependencies. These were added about 2 months ago.

**Comment by balazsorban44** [comment]
Closing in favor of #35048 which has a reproduction. So far it seems that some packages that need certain things polyfilled (eg.: `assert`) are pulling in those precompiled dependencies. It would be helpful to know which package induces this in your case.

Could you narrow it down and please create a reproduction and link it under #35048 as well to further the investigation? :pray:
