### ISSUE TITLE
[Fizz] TypeError: Cannot read properties of undefined (reading 'fallback') at NextNodeServer.getStaticPaths

### ISSUE THREAD

**Issue by wongmjane** [vercel/next.js#34247]
### Run `next info` (available from version 12.0.8 and up)

yarn run v1.22.17
$ /Users/jane/Coding/node-fizz-isr-app/node_modules/.bin/next info
/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.14
      react: 18.0.0-rc.0
      react-dom: 18.0.0-rc.0
(node:23925) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/jane/Coding/node-fizz-isr-app/node_modules/react/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
✨  Done in 1.25s.

### What version of Next.js are you using?

12.0.11-canary.14

### What version of Node.js are you using?

16.13.0

### What browser are you using?

Google Chrome 98.0.4758.80 (Official Build) (arm64)

### What operating system are you using?

macOS 12.2.1 (21D62)

### How are you deploying your application?

next start

### Describe the Bug

When Fizz is enabled and the project is running in prod (both locally via `next start` or Vercel), the dynamic route crashes and shows the 500 error page, with the following error:

```
TypeError: Cannot read properties of undefined (reading 'fallback')
    at NextNodeServer.getStaticPaths (./node_modules/next/dist/server/base-server.js:696:82)
    at cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (./node_modules/next/dist/server/base-server.js:903:79)
    at ./node_modules/next/dist/server/response-cache.js:64:42
TypeError: Cannot read properties of undefined (reading 'fallback')
    at NextNodeServer.getStaticPaths (./node_modules/next/dist/server/base-server.js:696:82)
    at cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (./node_modules/next/dist/server/base-server.js:903:79)
    at ./node_modules/next/dist/server/response-cache.js:64:42
```

next.config.js:
```js
module.exports = {
  reactStrictMode: true,
  experimental: {
    reactRoot: true,
    runtime: 'nodejs' // but it also seems to crash when 'edge' is chosen
  }
}
```

### Expected Behavior

I expected the dynamic route to not crash in Fizz in prod.

### To Reproduce

1. Clone the [sample repo](https://github.com/wongmjane/nextjs-34247)
2. yarn
3. yarn build && yarn start
4. Open the `/thing/1` page

**Comment by shuding** [comment]
Hello Jane! `getStaticPaths` (and SSG/ISR) isn’t well supported at this moment, and we are treating them as SSR routes. This is something we’re actively working on and we will share updates as soon as we could. The longer term plan can be found in the switchable runtime RFC.

**Comment by Kabeer10** [comment]
Im having the same issuse when i, using getStaticPaths and getStaticProps together

**Comment by balazsorban44** [comment]
You can follow #35023

**Comment by Kabeer10** [comment]
@nagmak ,for now I'm just using getServerSideProps, or u roll back to previous version of nextJS

**Comment by shuding** [comment]
Hey all! SSG/ISR in the Node.js runtime are now supported together with the new rendering architecture, I forked @wongmjane's reproduction [here](https://github.com/shuding/nextjs-34247) and upgraded to latest versions, and it's now working fine:

```
yarn add react@latest react-dom@latest next@latest
```

Let us know if you run into other issues!
