### ISSUE TITLE
Clear muitiple cookies in _middleware page instead NextResponse.clearCookie(...).clearCookie(...) on Vercel production 🍪

### ISSUE THREAD

**Issue by igdev116** [vercel/next.js#34254]
### Describe
When deploying to production on Vercel I have an issue. I can't clear mutiple cookies at same time with built in method
```js
if (something_true) {
    return NextResponse.clearCookie('access_token').clearCookie('refresh_token');
}
```
It's ONLY clear the first cookie 'access_token' not both 'access_token' and 'refresh_token'
I also tried
```js
if (something_true) {
    const res = NextResponse.next();

    res.clearCookie('access_token');
    res.clearCookie('refresh_token');

    return res;
}
```
Two ways above not work on production. But on local dev, it's work perfectly 🤔

### Solution
I have decided to return to the old method 😄
```js
if (something_true) {
    let res= NextResponse.next();

    res.cookie('access_token', '', {
      ...cookieOptions, // Configs when you set cookies options like httpOnly: true,...
      expires: new Date(0), // Important here to let browser auto remove cookie
    });
    res.cookie('refresh_token', '', {
      ...cookieOptions, // Same above
      expires: new Date(0), // Same above
    });

    return res;
}
```
Have a nice day ✨✨

**Comment by igdev116** [comment]
I don't know why it's not working now, so weird 😅

**Comment by xhoantran** [comment]
This issue was fixed by [#30560](https://github.com/vercel/next.js/pull/30560).

I try to reproduce on [Vercel](https://nextjs-clearcookie.vercel.app/), and it doesn't work properly as this issue mentioned. 

<img width="465" alt="Vercel" src="https://user-images.githubusercontent.com/76760622/153768080-4184e642-07bf-4245-b657-50fdc3673fb7.png">

I also try to deploy on [Netlify](https://optimistic-goldstine-702bdc.netlify.app/) and it works ok.

<img width="465" alt="Vercel" src="https://user-images.githubusercontent.com/76760622/153768086-425eaa4b-1408-476e-b0cb-89600d229bc6.png">

**Comment by ardaerzin** [comment]
we had a case where we were clearing and setting a new one using `res.clearCookie` and `res.cookie(cookieName)`, and it simply didn't work when deployed to Vercel. locally It was working without any issues. I found [this discussion topic](https://github.com/vercel/next.js/discussions/33782) where I also posted a minimal repo for reproduction

**Comment by igdev116** [comment]
@xhoantran Thanks your advice, I'll try that

**Comment by MerlinMason** [comment]
The same is true for setting cookies too...
```js
const response = NextResponse.next();

response.cookie("a", "1", { sameSite: "strict", domain: response.url });
response.cookie("b", "2", { sameSite: "strict", domain: response.url });
```

Works fine locally but in Vercel production only `a` gets set.

The response has the header: `set-cookie: a=1; Path=/; SameSite=Strict, b=2; Path=/; SameSite=Strict` which as @xhoantran mentioned is incorrect.

**Comment by xhoantran** [comment]
I found out that `Vercel` has a different `middleware` build from [next-server.ts](https://github.com/vercel/next.js/blob/canary/packages/next/server/next-server.ts)` but use their own middleware (to work with another framework 🧐) which they just removed.

The root issue is from [Node HTTP](https://nodejs.org/api/http.html#responsesetheadername-value). The setHeader function just combine all the string into the array, which make the `set-cookie` not work properly.

**Comment by javivelasco** [comment]
This should already work for server mode and a fix is coming to stable for Vercel deployments in the coming days!
