### ISSUE TITLE
Docs: async config details in next.config.js seems incorrect

### ISSUE THREAD

**Issue by manspaniel** [vercel/next.js#34253]
### What is the improvement or update you wish to see?

The docs currently state: 

"_Since Next.js 12.1.0, you can use an async function:_"

```javascript
module.exports = async (phase, { defaultConfig }) => {
  /**
   * @type {import('next').NextConfig}
   */
  const nextConfig = {
    /* config options here */
  }
  return nextConfig
}
```

However:
- The latest version of Next.js is 12.0.10.
- You currently only appear to be able to export a promise, and not an async function — otherwise you receive an error stating that the async config exists.

### Is there any context that might help us understand?

Tim Neutkens tweet stating that you can export a Promise: https://twitter.com/timneutkens/status/1486075973204422665
Pull request (merged) with the new async feature: https://github.com/vercel/next.js/pull/33662

On Next v12.0.10, when exporting an async function, I receive the following error:

`Error: > Promise returned in next config. https://nextjs.org/docs/messages/promise-in-next-config`

Doesn't work:
```javascript

module.exports = async () => {
  return {/* ... */}
}
```

Does work:
```javascript

module.exports = (async () => {
  return {/* ... */}
})()
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next.config.js/introduction

**Comment by balazsorban44** [comment]
You can try this out on the `canary` channel for now, `12.1.0` is coming very soon!

**Comment by manspaniel** [comment]
Thanks @balazsorban44!
