### ISSUE TITLE
Middleware Use Breaks Locale Routing on `/` Path on Vercel if autodetected locale is not default locale

### ISSUE THREAD

**Issue by neverether** [vercel/next.js#34274]
### Run `next info` (available from version 12.0.8 and up)

```
/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
    Binaries:
      Node: 14.17.5
      npm: 6.14.14
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.17.5

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When using automatic locale detection, and the detected locale is NOT the default locale, trying to route to another locale on `/` results in a failed prefetch error and doesn't complete routing.

In my case my locales are `["ja","en"]` and my defaultLocale is `ja`. My browser language is set to english, and with the automatic locale detection, I'm taken to the `/en` route. When I try to route to the `ja` locale in `yarn dev` or `yarn build && yarn start` everything works fine. However when I deploy to Vercel I get:

```
Uncaught (in promise) Error: Failed to preflight request
```
And routing is cancelled. 

My Japanese users with a japanese langauge setting have no issue moving between the two locales. and if I disable the automatic locale detection I will be taken to `/` with a `ja` locale as expected, and I can freely route between the two locales. 

### Expected Behavior

I'm expecting to not get a preflight failure from Vercel, and routing to complete successfully.

This might be related to https://github.com/vercel/next.js/issues/34199

### To Reproduce

I've created a minimum reproducable repo here using `create-next-app` and the official example at: https://github.com/vercel/examples/tree/main/edge-functions/basic-auth-password

Repo/Commits on Github: https://github.com/sollective/next-locale-bug-repro/commits/main

I also have it hosted on Vercel here: 
https://next-locale-bug-repro.vercel.app/en (Credentials are `admin`/`password`)
(Please set your primary language to English in browser)

**Comment by maggo** [comment]
This happened to me as well, in particular the `HEAD` request to `/` is failing.
Removing the middleware file fixes the issue.

**Comment by youminkim** [comment]
Same issue here. I had to rewrite including locale. Otherwise, 404 error
```
   const localePrefix = locale === 'default' ? 'en' : locale;
   url.pathname = `/${localePrefix}/_sites/${hostname}`;
   NextResponse.rewrite(url)
```

**Comment by nkzawa** [comment]
It should already be fixed by https://github.com/vercel/next.js/pull/35911
