### ISSUE TITLE
Failing build with outputStandalone in Docker.

### ISSUE THREAD

**Issue by muqshots** [vercel/next.js#34290]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Tue Jan 18 13:02:02 PST 2022; root:xnu-8020.100.406.0.1~18/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.13.2

### What browser are you using?

Not relevant

### What operating system are you using?

macOS

### How are you deploying your application?

Docker

### Describe the Bug

Running on the node:16 base image

Getting
```
[Error: ENOENT: no such file or directory, copyfile '/app/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node' -> '/app/packages/web/.next/standalone/node_modules/sharp/build/Release/sharp-darwin-arm64v8.node']
```
When building the project

node_modules in the container has "sharp-linux-arm64v8.node"
Seems to be trying to copy the darwin version and not the linux one

### Expected Behavior

Should be using the linux sharp binary

### To Reproduce

Dockerfile

```
FROM node:16

WORKDIR /app

COPY . .

RUN yarn install
RUN yarn build


CMD ["yarn", "start"]
```

**Comment by balazsorban44** [comment]
Hi, could you check out using this guide: https://nextjs.org/docs/deployment#docker-image

A highly optimized `Dockerfile` config can be found here:

https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

**Comment by muqshots** [comment]
Thanks!

For those with a similar issue, I had `node_modules` in my .dockerignore, added `**/node_modules` and it's working now.
