### ISSUE TITLE
Server Error ReferenceError: window is not defined

### ISSUE THREAD

**Issue by kaytitulaer2008** [vercel/next.js#34330]
### Run `next info` (available from version 12.0.8 and up)

'pnpm' is not recognized as an internal or external command,
operable program or batch file.

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

v16.13.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 11

### How are you deploying your application?

npm run dev

### Describe the Bug

When using `window`, or in this case `window.sessionStorage.setItem('key', 'value')` it gives the error `Server Error
ReferenceError: window is not defined`

### Expected Behavior

I expected to add `key` with value `value` in my session storage

### To Reproduce

Create a next.js project and use `window.sessionStorage.setItem('key', 'value')` anywhere in your project. Then start the project and go to the page

**Comment by xhoantran** [comment]
Because Next.js render your page on server side. You need to put `window.sessionStorage.setItem('key', 'value')` in `useEffect` and check `typeof window != 'undefined'`.

```
useEffect(() => {
   if (typeof window !=  'undefined') 
       window.sessionStorage.setItem('key', 'value')
}, [])
```

**Comment by TylerShin** [comment]
> window.sessionStorage.setItem('key', 'value')

+ more, you don't have to wrap `typeof window !== "undefined"` when use it in `useEffect`.
useEffect only runs on a browser environment.

**Comment by xhoantran** [comment]
> > window.sessionStorage.setItem('key', 'value')
> 
> * more, you don't have to wrap `typeof window !== "undefined"` when use it in `useEffect`.
>   useEffect only runs on a browser environment.

Thank you, I updated comment

**Comment by ijjk** [comment]
Closing as this isn't a bug and the above comments are correct in that `window` usage should be kept inside of `useEffect` or `typeof window` checks.

**Comment by balazsorban44** [comment]
Here is a link to some documentation: https://nextjs.org/docs/migrating/from-create-react-app#safely-accessing-web-apis
