### ISSUE TITLE
`getInitialProps` and `getStaticProps` regarding authentication 

### ISSUE THREAD

**Issue by balazsorban44** [vercel/next.js#34334]
### What is the improvement or update you wish to see?

Given a developer is using both `getInitialProps` in a custom `_app` combined with a `getStaticProps` and `revalidate` on a page, we should inform the developer to make sure they don't accidentally cache sensitive information.

### Is there any context that might help us understand?

See a more detailed answer giving an example with NextAuth.js and how to solve the issue instead.

https://github.com/vercel/next.js/issues/34316#issuecomment-1039037314

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/authentication

**Comment by kmin-jeong** [comment]
@balazsorban44 @molebox  If there's no one assign this issue, I want to try it. can I try it on?

**Comment by molebox** [comment]
Sure @kmin-jeong its all yours!

**Comment by balazsorban44** [comment]
Closing, based on https://github.com/vercel/next.js/pull/36228#issuecomment-1107273019
