### ISSUE TITLE
Using deprecated read only property navigator.userAgent

### ISSUE THREAD

**Issue by romerodiesan** [vercel/next.js#34391]
### Run `next info` (available from version 12.0.8 and up)

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.0
      npm: 8.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2
```

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

16.0.4

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Development for know

### Describe the Bug

This is not a bug at all. But it's more currently on applications.

```
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
```

### Expected Behavior

There is information about it on https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

### To Reproduce

Just building and starting the app. This is are present on `content.bundle.js:1 `and `invisible.js:1`.

**Comment by balazsorban44** [comment]
Hi, sorry but I'm not sure what the bug report here is. `content.bundle.js` and `invisible.js` are not files coming from Next.js, make sure you do not have an extension that shows those files. In any case, you are assured that Next.js takes the correct measurements when it comes to supporting browsers https://nextjs.org/docs/basic-features/supported-browsers-features
