### ISSUE TITLE
Redirects from middleware to external domains incorrectly append query params

### ISSUE THREAD

**Issue by bryanrsmith** [vercel/next.js#34404]
### Run `next info` (available from version 12.0.8 and up)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.18.3

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying your application?

Vercel

### Describe the Bug

When a middleware function redirects to an external site the query params received by the middleware are appended to the redirect target. Middleware cannot redirect to a target with no query params if the middleware received params.

### Expected Behavior

Redirects from middleware should use the redirect target specified by the middleware without modification to the query string.

### To Reproduce

For example:
- A request is made to /foo?bar=baz
- A middleware function handles the request and redirects to `https://nextjs.org`.
- The `location` header returned to the client has a value of `https://nextjs.org?bar=baz`

This is reproducible when deployed to Vercel, but not when running locally with `next dev`.

Repro deployment: https://next-middleware-redirects.vercel.app/

Code: https://github.com/bryanrsmith/next-middleware-redirects

**Comment by ijjk** [comment]
Hi, this has been updated, please re-deploy your application and give it a try!

**Comment by bryanrsmith** [comment]
Confirmed. Thank you!
