### ISSUE TITLE
Undici, fetch not working in middleware

### ISSUE THREAD

**Issue by weyert** [vercel/next.js#34447]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.4.0
      Yarn: 1.22.17
      pnpm: 6.30.1
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

If I try to fetch data in ` middleware` function using Undici the following error occurs:

```
./node_modules/undici/lib/api/api-connect.js:4:24
Module not found: Can't resolve 'async_hooks'

Import trace for requested module:
./node_modules/undici/lib/api/index.js
./node_modules/undici/index.js
./src/pages/_middleware.ts

https://nextjs.org/docs/messages/module-not-found
```

I would expect `undici` to work as it will be the future Fetch implementation that will get bundled with Node.js: 
https://github.com/nodejs/node/pull/41749

### Expected Behavior

Calling `undici.fetch()` should work

### To Reproduce

1. Create Next.js app
2. Add `_middleware.ts` to `pages`-directory
3. Add contents to `_middleware.ts`:

```typescript
/* eslint-disable no-console */
import type { NextFetchEvent, NextRequest } from 'next/server'
import { NextResponse } from 'next/server'
import * as undici from 'undici'

export async function middleware(req: NextRequest, ev: NextFetchEvent) {
  console.log(`middleware() req:`, req)
  console.log(`middleware() ev:`, ev)
  try {
    const response = await undici.fetch('https://www.vercel.com', { method: 'GET' })
    const json = await response.text()
    console.log(`response:`, response.status, json)
    return NextResponse.rewrite(
      '/marketing/b'
    )
  } catch (err: unknown) {
    console.log(`Error occurred:`, err)
    return NextResponse.rewrite(
      '/marketing/a'
    )
  }
}
```
4. Start server `next dev`
5. Notice the error when accessing the Next.js server

```
./node_modules/undici/lib/api/api-connect.js:4:24
Module not found: Can't resolve 'async_hooks'

Import trace for requested module:
./node_modules/undici/lib/api/index.js
./node_modules/undici/index.js
./src/pages/_middleware.ts

https://nextjs.org/docs/messages/module-not-found
```

**Comment by weyert** [comment]
I tried to use a code snippet like `typeof fetch === 'function' ? fetch : require('undici').fetch` to avoid it trying to load `undici` when `fetch` is already available but that doesn't work.

**Comment by balazsorban44** [comment]
Hi, this is expected as Middleware does not support Node.js APIs like [`async_hooks`](https://nodejs.org/api/async_hooks.html).

https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis

**Comment by weyert** [comment]
@balazsorban44  but when I use code like `typeof fetch === 'function' ? fetch : require('undici').fetch` why is it still trying to load `undici`-module when fetch is defined?

So it means you can't use any typical packages?

**Comment by balazsorban44** [comment]
From the [above-linked](https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis) pages:

> why is it still trying to load undici-module

- Calling require directly is not allowed. Use ES Modules instead

> So it means you can't use any typical packages?

- Node Modules can be used, as long as they implement ES Modules and do not use any native Node.js APIs

In this case, you wouldn't need to use `undici` in the first place, because the environment the code will be run in already has `fetch`.
