### ISSUE TITLE
Usage of `styled-jsx` with `next/jest` prints a warning message

### ISSUE THREAD

**Issue by Divlo** [vercel/next.js#34492]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022
    Binaries:
      Node: 16.14.0
      npm: 8.4.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

This issue has already been discussed here: https://github.com/vercel/next.js/discussions/31152#discussioncomment-1652132 

With the arrival of `next@12.1.0`, it seems like `next/jest` is no longer experimental: https://nextjs.org/blog/next-12-1#zero-configuration-jest-plugin so now it might make sense to open individual issues instead of continuing to discuss on "next/jest feedback" discussion thread for easier tracking.

The issue is that there is a warning message when testing a component that uses `styled-jsx` with `next/jest`.
It makes tests output noisy but not dramatic as it is working.

![image](https://user-images.githubusercontent.com/25207499/154545181-0863a0cd-e5b9-462c-93c0-2c37a47b45dd.png)

### Expected Behavior

No warning message, tests run normally.

### To Reproduce

1. `npx create-next-app@12.1.0 --example with-jest with-jest-app` (using [with-jest](https://github.com/vercel/next.js/tree/canary/examples/with-jest) example)
2. Replace the content of `pages/index.tsx` file with:

```tsx
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
      </main>

      <style jsx>{`
        h1 {
          color: red;
        }
      `}</style>
    </>
  )
}

export default Home
```

3. `npm run test:ci` or `npm run test`

**Comment by GP-marco** [comment]
Same issue occurs in our code base.
The test logs are messed with hundreds of these warnings and it is impossible to see important warnings/errors.

**Comment by balazsorban44** [comment]
This should be fixed on `canary`, please upgrade and try it out!

**Comment by Divlo** [comment]
> This should be fixed on `canary`, please upgrade and try it out!

Indeed it is, thanks!
For reference and pure curiosity, do you know which commit fixed this? @balazsorban44

**Comment by balazsorban44** [comment]
It was this release: https://github.com/vercel/next.js/releases/tag/v12.1.6-canary.13

Likely this PR: https://github.com/vercel/next.js/pull/36500
