### ISSUE TITLE
[v12.1.0] Using React 18 prevents starting without `experimental` in config (TypeError: Cannot set properties of undefined (setting 'reactRoot'))

### ISSUE THREAD

**Issue by bennettdams** [vercel/next.js#34499]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 18.0.0-rc.0
      react-dom: 18.0.0-rc.0

### Describe the Bug

Starting with `v12.1.0`, you can't use React 18 when you don't use the `experimental` field in the `next.config.js`

![image](https://user-images.githubusercontent.com/29319414/154569017-38f72690-6879-47d1-a0cd-09072af2967c.png)

That's because [this recent change](https://github.com/vercel/next.js/commit/1aee93581f7154ca4c191388904c33980cd74653) sets `reactRoot` on the user's config without checking if the key already exists:

https://github.com/vercel/next.js/blob/787186a85a054ea870fc964583fe65e9f2286354/packages/next/server/config.ts#L679-L682

### Expected Behavior

- React 18 should be usable without using the `experimental` field in the `next.config.js`
or
- the [docs for React 18](https://nextjs.org/docs/advanced-features/react-18/overview) should mention that it is mandatory to set the field

### To Reproduce

1. Install via Create Next App
`npx create-next-app@latest --ts --use-npm .`
2. Install React 18
`npm install next@latest react@rc react-dom@rc`
3. Start the app
`npm run dev`

**Comment by clianor** [comment]
I fixed this by modifying next.config.js as follows:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    reactRoot: true
  }
}

module.exports = nextConfig

```

**Comment by bennettdams** [comment]
@clianor Yep, that works. [I created a PR that fixes this](https://github.com/vercel/next.js/pull/34500), which already got merged, so in the next release that shouldn't be needed anymore.
