### ISSUE TITLE
ie11  Official scaffold operation error

### ISSUE THREAD

**Issue by livelyPeng** [vercel/next.js#34509]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

无

### What browser are you using? (if relevant)

ie11

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

1. npx create-next-app@latest --typescript
# or
yarn create next-app --typescript

2
.Run npm run dev or yarn dev to start the development server on http://localhost:3000

3. 
![image](https://user-images.githubusercontent.com/32978177/154614862-60170341-47d1-4806-81b6-2460dcb53c78.png)
Invalid character
![image](https://user-images.githubusercontent.com/32978177/154614893-b9732839-6faa-4db7-869f-072cf1fa9b9c.png)

### Expected Behavior

The page cannot be displayed

### To Reproduce

1. npx create-next-app@latest --typescript
# or
yarn create next-app --typescript

2
.Run npm run dev or yarn dev to start the development server on http://localhost:3000

3. 
![image](https://user-images.githubusercontent.com/32978177/154614862-60170341-47d1-4806-81b6-2460dcb53c78.png)
Invalid character
![image](https://user-images.githubusercontent.com/32978177/154614893-b9732839-6faa-4db7-869f-072cf1fa9b9c.png)

**Comment by balazsorban44** [comment]
Hi, thanks for reporting! Although not exactly the same issue, I would like to close this in favor of https://github.com/vercel/next.js/issues/13231 which also addresses using the dev server in IE11.

I can probably tell that unfortunately, this is not a top priority, as IE11 is considered a legacy browser.

That said, we do [support it as a build target](https://nextjs.org/docs/basic-features/supported-browsers-features) and if you find issues with that please report it, but even our default target is changing (so IE11 support would become opt-in as outlined here: https://github.com/vercel/next.js/discussions/33227). As the ecosystem moves away from IE11, it makes less sense to put much effort into making the dev server work in IE11 either.

**Comment by livelyPeng** [comment]
@balazsorban44 This is not the problem [#13231](https://github.com/vercel/next.js/issues/13231)， 
I tried to install import "@ webcomponents / shadydom";
ie11： 
![image](https://user-images.githubusercontent.com/32978177/154779960-61cb8639-455a-45fb-8695-8b41cf1439e4.png)

I want to know how to solve it, because we need to be compatible with ie11

**Comment by livelyPeng** [comment]
You mean I don't need to pay attention to the next dev development environment? Automatically match IE after next build?

**Comment by balazsorban44** [comment]
Yes. Next.js adds the required polyfills as stated here https://nextjs.org/docs/basic-features/supported-browsers-features

You must still make sure that the packages you Wil be using are compatible as well, but from the Next.js side you should be good. 👍
