### ISSUE TITLE
Next 12 doesn't properly auto-prefix the `backdrop-filter` CSS property

### ISSUE THREAD

**Issue by limmidy** [vercel/next.js#34505]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
- Platform: darwin
- Arch: x64
- Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64

Binaries:
- Node: 15.5.1
- npm: 7.3.0
- Yarn: N/A
- pnpm: N/A

Relevant packages:
- next: 12.1.11-canary.21
- react: 17.0.2
- react-dom: 17.0.2

### What browser are you using? (if relevant)

Noticeable on Safari since Safari requires the `-webkit-` prefix

### Describe the Bug

I recently upgraded from Next@11.1.4 to Next@12.1.0. In Next 12, when I use the `backdrop-filter` CSS property with Styled JSX through a component, the property doesn't auto-prefix to `-webkit-backdrop-filter`.

### Expected Behavior

Previously in Next 11.1.4, `backdrop-filter` would automatically auto-prefix to `-webkit-backdrop-filter` based on the [default behavior](https://nextjs.org/docs/advanced-features/customizing-postcss-config).

### To Reproduce

I made a new CodeSandbox: https://codesandbox.io/s/vigilant-water-z3i0hi?file=/components/blurrything.js

Here you can see that `mask` gets auto-prefixed to `-webkit-mask`, but `backdrop-filter` does not.

**Comment by huozhi** [comment]
Looks like it's fixed in 12.1.4, could you give it another shot again? 🙏

**Comment by pacocoursey** [comment]
Can confirm this is fixed and should be closed :)

**Comment by ijjk** [comment]
Closing per above, thanks @pacocoursey!
