### ISSUE TITLE
Next log warning even only pass plain json to other comp

### ISSUE THREAD

**Issue by ZetraDev** [vercel/next.js#34524]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.21
      react: 18.0.0-rc.0
      react-dom: 18.0.0-rc.0

### What browser are you using? (if relevant)

brave

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

When i pass the data that fetched with mongoose from server component to client component, next will log:
```
Warning: Only plain objects can be passed to client components from server components. Objects with toJSON methods are not supported. Convert it manually to a simple value before passing it to props. Remove date from these props: {_id: {...}, date: Date, text: "xxx", __v: 0}
```
Type of the data passing to client component:
```ts
{
	_id: ObjectID,  // from mongoose
	date: Date,
	text: String,
	__v: Number  // from mongoose
}[]
```

Server Component:
```ts
export default function NoteList() {
	const notes = useData(async function () {
		const result = await Note.find();
		return result;
	});
	return (
		<div>
			<p>List:</p>
			{notes.map((n) => (
				<div key={n._id}>
					<NoteCard data={n} />
				</div>
			))}
		</div>
	);
}
```
Client Component:
```ts
export default function NoteCard({ data }: { data: Note }) {
	return (
		<div style={{ display: "flex" }}>
			<div>
				<p>ID: {data._id.toString()}</p>
				<p>Text: {data.text}</p>
			</div>
		</div>
	);
}
```
useData function:
```ts
const cache = new Map<string, unknown>();

export function useData<T>(fn: () => Promise<T>): T {
	const cacheData = cache.get(`${fn}`);
	if (!cacheData) {
		throw new Promise(async (res) => {
			const data = await fn();
			cache.set(`${fn}`, data );
			res(data);
		});
	}
	return cacheData as T;
}
```

### Expected Behavior

no warning since the data are plain object and is serializable

### To Reproduce

1. In server component, fetch data from mongodb
2. pass the data to a client component
3. render page
4. warning appear in log

**Comment by balazsorban44** [comment]
`ObjectId` and `Date` should be converted using the `toString` methods respectively, since those are objects.
