### ISSUE TITLE
Script tag errors

### ISSUE THREAD

**Issue by kakarot-dev** [vercel/next.js#34522]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Next info is not a command

### How are you deploying your application? (if relevant)

windows

### Describe the Bug

Whenever i start the website using `next dev`, This is being console logged ```Do not add <script> tags using next/head (see inline <script>). Use next/script instead. 
See more info here: https://nextjs.org/docs/messages/no-script-tags-in-head-component``` whilst i not imported any such package

### Expected Behavior

No console logs regarding the above stated warnings

### To Reproduce

Install the latest version of nextjs `v12.1.0`
Run the `next dev` command

**Comment by balazsorban44** [comment]
Hi, as the message suggests, you might have a `<script>` tag somewhere in your code. To verify, could you create a reproduction or link to your project? Thanks

**Comment by kakarot-dev** [comment]
> Hi, as the message suggests, you might have a `<script>` tag somewhere in your code. To verify, could you create a reproduction or link to your project? Thanks

Just to confirm, was thid warning only added in 12.1?

**Comment by balazsorban44** [comment]
No, it has been added a while ago. Could you provide a reproduction repository, please? :pray:

**Comment by kakarot-dev** [comment]
> No, it has been added a while ago. Could you provide a reproduction repository, please? 🙏

I have added you to the repo over at https://github.com/kakarot-dev/kakarot.pw
Please clone the beta branch and just do `npm i next@latest` and try running the dev server
( Im sorry i cant make it public )

**Comment by bogdansoare** [comment]
I have the same issue after upgrading to 12.1 and I don't have any script tags in the head

**Comment by yehezkielgunawan** [comment]
This is weird, just updated to 12.1 and I got similar issue. I didn't have any `script` tag around my project folder. I even just declare `next/head` just in my `_app.tsx`. Here's my snippet on `_app.tsx`:

```tsx
import "@/styles/globals.css";
import { DefaultSeo } from "next-seo";
import { ThemeProvider } from "next-themes";
import type { AppProps } from "next/app";
import Head from "next/head";
import "@fontsource/catamaran";

import defaultSEOConfig from "../../next-seo.config";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
      <Head>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover"
        />
      </Head>
      <DefaultSeo {...defaultSEOConfig} />
      <Component {...pageProps} />
    </ThemeProvider>
  );
}

export default MyApp;

```

This is the browser console still gives warnings like this:
```
head.js?fb5d:165 Do not add <script> tags using next/head (see inline <script>). Use next/script instead. 
See more info here: https://nextjs.org/docs/messages/no-script-tags-in-head-component
```

Here's my [full project GitHub repo](https://github.com/yehezkielgunawan/yehezgun-v3) to ensure you that I didn't have any `script` tag in my project.

**Comment by bogdansoare** [comment]
@yehezkielgunawan the warning in your case is caused by `next-themes` https://github.com/pacocoursey/next-themes/issues/84

**Comment by yehezkielgunawan** [comment]
Hm... got it, so it cause by `next-themes`, hope there will be future fixing about this

**Comment by kakarot-dev** [comment]
Oh, i use it too
well, ill close this then

**Comment by balazsorban44** [comment]
Yes, this will be fixed in https://github.com/pacocoursey/next-themes/pull/53
