### ISSUE TITLE
Deprecate `page` parameter for Middleware

### ISSUE THREAD

**Issue by javivelasco** [vercel/next.js#34521]
Currently, in Middleware, `NextRequest` holds a `page` property that can be used to _foresee_ if the incoming request will match a page or not. This feature is intended to help users detect if a certain page will be render and, in the case of dynamic routes, which ones are the parameters that they will be matching.

This information is based on simply checking if there is a static/dynamic page route that matches the request. The problem is that when the request matches a static file, it will still check if there is a page match and it is not possible to detect if there is a static file that matches at that specific stage.

This feature can be replaced by using [path-to-regexp](https://github.com/pillarjs/path-to-regexp) or any other library or regexp and it is adding logic to the middleware bundle that many users may not need, growing its size when there is no need to.

We should entirely remove the feature so that when `request.page` is accessed we can fail with an error and a link that provides a code snippet with an alternative to the feature.

**Comment by tavvy** [comment]
The rest of your comment about `path-to-regexp` makes sense, but could I ask for some clarity on how one would go about retrieving the page / route manifest from within a custom middleware?

I've noted anecdotally that `request.page` is not reliable, in that for some paths that I **know** are served by Next I am getting `{ name: undefined, params: undefined }`. For this reason I was about to rewrite my own `path-to-regexp` style logic anyway, which is how I stumbled upon this issue.

**Comment by javivelasco** [comment]
That's good to know @tavvy as it confirms that this feature is not as useful as initially expected. What I mean referring to `path-to-regexp` is that the feature simply relies on checking against all dynamic routes and usually a user would use it check wether it matches or not a _specific page_. Being that the case one can transform, i.e. `/dashboard/:slug` to a regexp and check against `request.nextUrl.pathname` to see if it is matching or not. Within that case one could also discard static file matches.

We can also add a snippet for a helper in the error link to actually make it worth with the exact Next.js page route like `pages/dashboard/[slug]`.

**Comment by jake-nz** [comment]
> although this behaviour differs between vercel dev and when actually deployed ... thats one for another day
Ah ha! That little discrepancy had me chasing my tail for far too long!

Should issues that are specific to Vercel deployment rather than Next be reported here?

My Vercel issue: https://github.com/vercel/vercel/issues/7452

**Comment by jake-nz** [comment]
I've realised that Next itself needs to know which page will be rendered in middleware.

Given folder structure like this:
* pages
  * index.tsx
  * page.tsx
  * _middleware.ts
  * [slug]
    * index.tsx
    * _middleware.ts
  
When a user requests /page `request.page.name = '/page'`
When a user requests /page2 `request.page.name = '/[slug]'`
Next needs to know this so that it can decide whether to run `[slug]/_middleware.ts` or not.

My suggestion would be to keep `request.page` because it needs to be computed and it's useful to pass on to middleware. Having some indication that there is a static file that matches would be a more useful solution.

**Comment by leerob** [comment]
Related: https://github.com/vercel/next.js/discussions/29750#discussioncomment-2122618
