### ISSUE TITLE
Next.js v12.1 on-demand-isr example has an issue when client-side navigation

### ISSUE THREAD

**Issue by Migggz** [vercel/next.js#34531]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

-

### Describe the Bug

When I was trying the demo that was introduced in Next.js 12.1 blog post. I found the issue while navigating from one route to another.

When I visited [On-Demand-ISR example](https://on-demand-isr.vercel.app/), I saw a lot of PRs each one opened from 2 or 3 minutes as expected, but when I try to visit one of these PRs and go back again I didn't see the same PRs I saw before, I saw PRs created from 14 hrs.

### Expected Behavior

When I go back I should see the updated version of this page as the first hit to this page.

### To Reproduce

- Open https://on-demand-isr.vercel.app/, and look at the last created PR
- Open any of these PRs
- Go back

**Comment by raphaelHuerzeler** [comment]
I encounted the same behaviour from what I can tell while the pages themselves are regenerated the assotiated jsons are not - so the page `/`  is updated, but `de.json` is not (we use i18n), same for individual article routes `/test` updates, but not `test.json`.

This also means that as on-demand-isr you'll usually want to omit revalidate that the jsons never get updated.

**Comment by vxna** [comment]
And this only happens if deployed to Vercel, locally works just great

**Comment by kristjanmar** [comment]
I am getting this too! Visiting a revalidated page via client-side navigation leads to the old version showing. Visiting the page directly shows the fresh version. Navigating to it and refreshing also shows the fresh version.

However, anyone who navigates to it from another page on the site will see an old version, the same version as was generated during the initial build.

I have attached a recording of the issue. On the page, the fresh version of the page shows the number 66.67%. When the build was deployed a few hours ago, it showed 33.78%. You can see how visiting the page directly and refreshing the page shows the fresh version, while navigating to it from another page shows the old version from the original deployment.

https://user-images.githubusercontent.com/22234692/154703415-ecad4472-e7dc-4896-bf38-f1755d65eb6b.mov

Unfortunately this makes the feature unusable, so I will have to go revert back to a previous build. I'm super excited about this feature, though, so hopefully this will be fixed quickly.

**Comment by ijjk** [comment]
Hi, this should be resolved now please re-deploy/trigger a new revalidation and give it a try!

**Comment by kristjanmar** [comment]
> Hi, this should be resolved now please re-deploy/trigger a new revalidation and give it a try!

It is working now, thanks!

**Comment by mpetricek** [comment]
@ijjk Hi, how and where is that fixed? Thank you!

**Comment by ijjk** [comment]
@mpetricek it was fixed on Vercel's edge, no change was needed in Next.js itself.

**Comment by Migggz** [comment]
@ijjk Yes, it is working now. Thank you!
