### ISSUE TITLE
Middleware returns code 400 when using Cypress Interceptors

### ISSUE THREAD

**Issue by alessandrojcm** [vercel/next.js#34554]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Sun Feb 6 12:21:42 UTC 2022
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 98

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When running an integration test with Cypress and trying to use `cy.intercept`, the request fails with a status code 400 and a `Invalid request format for Vercel Edge Function` error. If the middleware is removed then the test passes.

### Expected Behavior

The test should pass regardless of the middleware.

### To Reproduce

Check the README in https://github.com/alessandrojcm/cypress-repo

Additionally, you could clone the aforementioned repo an run the test against these deployments

* https://cypress-repro-e8mdzqxu0-alessandrojcm.vercel.app/ (no middleware)
* https://cypress-repro-bns371yc8-alessandrojcm.vercel.app/ (middleware)

**Comment by javivelasco** [comment]
Closing since this has been already fixed!

**Comment by balazsorban44** [comment]
You might need to redeploy for the fix to take effect :+1:
