### ISSUE TITLE
Edge Functions cause 500 Error with `Next.js@12.1`

### ISSUE THREAD

**Issue by lidqqq** [vercel/next.js#34566]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

on Vercel, the runtime is Node.js v14

### What browser are you using? (if relevant)

Chrome Chrome 98.0.4758.102 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I ran into a bug about [Edge Functions](https://vercel.com/docs/concepts/functions/edge-functions) with `Next.js@12.1`.
Edge Function causes a 500 error on Vercel, but **local development doesn't cause them**. So you can find them only when you deploy to Vercel so far.

https://ab-testing-simple-12-1.vercel.app/

<img width="1567" alt="Screen Shot 2022-02-19 at 10 43 19" src="https://user-images.githubusercontent.com/39523918/154781129-55cd0f32-10c5-4a69-83c4-caa6b029bbb3.png">

And canary version causes it too

https://ab-testing-simple-canary.vercel.app/

But it works correctly with `Next.js@12.0.x`
https://ab-testing-simple-12-0-x.vercel.app/

I got the same bug on my other production project that Edge Functions uses. Perhaps all of the Edge Functions cause 500 error regardless of how they use.

### Expected Behavior

behave as well as the before versions such as `Next.js@12.0.x`
https://ab-testing-simple-12-0-x.vercel.app/

### To Reproduce

- go [example repository of edge function](https://github.com/vercel/examples/tree/main/edge-functions/ab-testing-simple)
- deploy to vercel
- change Next.js version to v12.1
- push remote and go production url

Or you can use these repositories that I used for my research

#### cause 500 error after v12.1
https://github.com/lidqqq/ab-testing-simple-12.1
https://github.com/lidqqq/ab-testing-simple-canary

#### works correctly
https://github.com/lidqqq/ab-testing-simple-12.0.x

**Comment by balazsorban44** [comment]
Hi, thank you for reporting this!

I could identify the problem and mentioned it to the relevant team. Luckily, this is not a bug in Next.js, only that our examples should be updated to reflect #33410

I deployed a version that works here: https://balazsorban-34566-balazsorban.vercel.app/

The code changes needed are in the two `_middleware` files respectively:

```js
const destination = req.nextUrl.clone()
destination.pathname = `/home/${bucket}` // or /marketing
const res = NextResponse.rewrite(destination)
```

**Comment by lidqqq** [comment]
@balazsorban44 Thanks for replying and investigating 🙏 
I got it, and I opened [the PR](https://github.com/vercel/examples/pull/158) so please check it when you have some time 👍
