### ISSUE TITLE
If I forget to pass pageProps, Server Component still has the router

### ISSUE THREAD

**Issue by gaearon** [vercel/next.js#34595]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
Binaries:
  Node: 17.5.0
  npm: 8.4.1
  Yarn: 1.22.15
  pnpm: 6.11.0
Relevant packages:
  next: 12.1.1-canary.1
  react: 0.0.0-experimental-13036bfbc-20220121
  react-dom: 0.0.0-experimental-13036bfbc-20220121

### Describe the Bug

Suppose I forget to pass `pageProps` in my `_app.js`:

```js
function MyApp({ Component, pageProps }) {
  return <Component />
}
```

I observe my Server Component being rendered twice: once it receives `router = undefined` and once it receives the actual `router`.

### Expected Behavior

I'd expect that my Server Component either always gets, or never gets the `router` prop. (If it never is supposed to get it without `pageProps` this is worth documenting [here](https://nextjs.org/docs/advanced-features/react-18/server-components#routing) because it wasn't obvious.)

### To Reproduce

```
git clone https://github.com/gaearon/sc-bug-repro.git
cd sc-bug-repro

git checkout router

npm install
npm run dev
```

Observe error and logs from `pages/index.server.js` in the console. Observe the page actually loads nevertheless.

**Comment by balazsorban44** [comment]
Hi, since Next.js 13, React Server Components is only supported in the `app` directory. See https://beta.nextjs.org/docs/getting-started.

If you still have issues, please open a new issue with a reproduction, using `next@canary`. Thanks. :pray:
