### ISSUE TITLE
State variable passed to a server component page from Custom App not updated

### ISSUE THREAD

**Issue by ZetraDev** [vercel/next.js#34603]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.1
      react: 18.0.0-rc.0
      react-dom: 18.0.0-rc.0

### What browser are you using? (if relevant)

brave

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

When trying to update a state variable created in Custom App (`pages/_app.tsx`) that will pass to a server component page (`pages/xxx.server.tsx`), it updated in Custom App, but not updated in the page, eg:
App:
```tsx
// pages/_app.tsx
function App(props: AppProps) {
    const [token, setToken] = React.useState<string | undefined>(undefined);
    React.useEffect(() => {
        const cookies = CookieConvertor(document.cookie)
        setToken(cookies.token);
    }, [])
    return (
        <props.Component {...props} token={token} />
    );
}

export default App;
```
Server Page
```tsx
// pages/page.server.tsx
export default function Page(props: any) {
    return (
        <div>
            <p>Index</p>
            <p>{props.token}</p>
        </div>
    );
}
```
In this case, after Custom App get the cookies and update the token, `props.token` in the page still undefined

### Expected Behavior

`props.token` will updated in the page

### To Reproduce

same as the example case

**Comment by ZetraDev** [comment]
If I change the code of Custom App to this:
```tsx
function App(props: AppProps) {
    const [token, setToken] = React.useState<string | undefined>(undefined);
    const [loading, setLoading] = React.useState(true);
    const refresh = unstable_useRefreshRoot();
    React.useEffect(() => {
        const cookies = CookieConvertor(document.cookie)
        setToken(cookies.user);
        setLoading(false);
    }, [])
    return !loading && (
        <div>
            <Page {...props} token={"aaaaa"} />
        </div>
    );
}

export default App;
```
(make app only return page after collected token)
it will make page can't rendered

**Comment by balazsorban44** [comment]
React Server Components have the constraint that they cannot have interactivity, eg. state/effects/event listeners since they are only executed once-per request.

https://github.com/josephsavona/rfcs/blob/server-components/text/0000-server-components.md#capabilities--constraints-of-server-and-client-components

We are exploring ways to read data like cookies to cover your use case in the future.

**Comment by ZetraDev** [comment]
So currently there is no way to fetch logged-in user's data with server component?

**Comment by balazsorban44** [comment]
So far we didn't have those official utils in Next.js yet, cookie reader is relying on server context work which is still ongoing on React.

In the short term to get cookies and do data fetching, we recommend `getServerSideProps`.
