### ISSUE TITLE
Allow inline-scripts with `beforeInteractive` strategy

### ISSUE THREAD

**Issue by pacocoursey** [vercel/next.js#34610]
### Describe the feature you'd like to request

My library [`next-themes`](https://github.com/pacocoursey/next-themes) injects an inline script that **must** at the start of page load to avoid any color flashing. This means I must use the `beforeInteractive` strategy in `next/script`.

However, `beforeInteractive` does not support inline scripts:

![](https://user-images.githubusercontent.com/34928425/154853949-db4873cd-12c7-4f79-8306-157cb8773a50.png)

**I'd like to request that inline scripts should be supported in `next/script` with `strategy="beforeInteractive"`.**

### Describe the solution you'd like

Allow passing `dangerouslySetInnerHTML` or `children` alongside usages of the script component with `strategy="beforeInteractive"`.

Implementation strategy:
1. Pass `dangerouslySetInnerHTML` or `children` to `scripts.beforeInteractive` [on this line](https://github.com/vercel/next.js/blob/bf8b835e2e1fd4b8364d7411d630d139478e8ea5/packages/next/client/script.tsx#L157)
2. It should automatically be [passed to the rendered script tag when it's inserted via the `_document`](https://github.com/vercel/next.js/blob/bf8b835e2e1fd4b8364d7411d630d139478e8ea5/packages/next/pages/_document.tsx#L82)

### Describe alternatives you've considered

1. **Use an external script**. Not possible because the value of my inline script is constructed at runtime based on the Next.js page props.
2. **Base64 encoding the script as the `src` prop**. This is what I'm currently doing, but it means we cannot have a stable, secure way to allow the script via CSP.

**Comment by pacocoursey** [comment]
Oh, it seems `children` is already being passed, so that will work. I'll keep this open as I continue testing.

It seems the documentation is inaccurate then. External scripts are not "inlined" either - at least my understanding of inlining would be fetching the remote script text and embedding it directly in the HTML to avoid a network fetch, which I don't see happening at all.

**Comment by balazsorban44** [comment]
This use case was purposefully left out from the initial implementation.

https://github.com/vercel/next.js/issues/26343#issuecomment-900461742

As such, this sounds like a duplicate of #26343. Do you agree?

**Comment by pacocoursey** [comment]
Yep, happy to close as duplicate.

**Comment by stefanprobst** [comment]
@pacocoursey you could also just move to a regular script tag in `_document` as suggested [in the react 18 streaming](https://github.com/vercel/next.js/blob/canary/docs/advanced-features/react-18/streaming.md?plain=1#L63) docs.

**Comment by pacocoursey** [comment]
Yeah, that's what I'm planning to do 👍 (https://github.com/pacocoursey/next-themes/pull/89)
