### ISSUE TITLE
Recommended `next/jest` setup cannot load `.env.development`

### ISSUE THREAD

**Issue by matamatanot** [vercel/next.js#34662]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64
    Binaries:
      Node: 14.15.4
      npm: 7.6.3
      Yarn: 3.1.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

https://nextjs.org/docs/testing#setting-up-jest-with-the-rust-compiler
> Loading .env (and all variants) into process.env

`.env` will be loaded, but `.env.development` will not.

### Expected Behavior

`.env.development` will also be loaded.

### To Reproduce

1. Fork [official example](https://github.com/vercel/next.js/tree/canary/examples/with-jest)
2. Add .env.development
3. Add tests that depend on environment variables
4. Run tests

**Comment by matamatanot** [comment]
https://github.com/vercel/next.js/blob/7ec5d29d1f9a0d14d7e310204a70f8d07c9a7fd9/packages/next-env/index.ts#L81-L83

Can I use `.env.test.local`? It might be good if it is clearly stated in the example.

**Comment by livelyPeng** [comment]
https://github.com/vercel/next.js/issues/34624   If your problem is related to environmental variables, I suggest you do so

**Comment by livelyPeng** [comment]
You don't need to pay attention to any official environmental documents,     As follows:  env.development,    .....

**Comment by balazsorban44** [comment]
This is intentional as you would want your tests to resemble production as much as possible https://nextjs.org/docs/basic-features/environment-variables#test-environment-variables
