### ISSUE TITLE
EACCES: permission denied, mkdir '../../dist'

### ISSUE THREAD

**Issue by sincovschi** [vercel/next.js#34711]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
$  npx --no-install next info
/bin/sh: 1: yarn: not found

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Aug 25 23:20:18 UTC 2021
    Binaries:
      Node: 16.13.1
      npm: 8.5.1
      Yarn: N/A
      pnpm: 6.31.0
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

nx.dev

### Describe the Bug

when run command `npx nx run blog:serve` I get the next error:

```
> Executing task: npx nx serve blog <


> nx run blog:serve

EACCES: permission denied, mkdir '../../dist'

 ———————————————————————

 >  NX   Running target "blog:serve" failed

   Failed tasks:
   
   - blog:serve
   
   Hint: run the command with --verbose for more details.

The terminal process "/usr/bin/bash '-c', 'npx nx serve blog'" terminated with exit code: 1.
```

### Expected Behavior

when run command `npx nx run blog:serve` to not have any error as it does with next: **12.0.7**.

### To Reproduce

```
git clone https://github.com/sincovschi/sincovschi-website.git
cd sincovschi-website
npm install
npm install next@latest
npx nx run blog:serve
```

**Comment by jedrzejginter** [comment]
I am also using Next 12.1.0 with NX and can confirm this issue when running the `nx serve` command. In version 12.0.10 this does not happen.
(I am able to run `nx build` command successfully though).

**Comment by balazsorban44** [comment]
`Hint: run the command with --verbose for more details.`

What did it say?

Anyway, I think is best opened at https://github.com/nrwl/nx as it seems to be an NX bug. If they can confirm this is something with Next.js, we are happy to look more into it.

**Comment by sincovschi** [comment]
I've tried verbose, gives no more details.
Also, any kind of fixes that would elevate rights over folders and files - with no success.

@balazsorban44, why would you think that NX has a bug, when there absolutely no errors with the older versions of Next?

**Comment by balazsorban44** [comment]
> why would you think that NX has a bug,

Because NX has relied on Next.js internals before which we don't have a guarantee for not changing. It could be possible that this is the case here as well.

Although, I checked your reproduction and followed the given steps, and I am not able to reproduce the issue.

![image](https://user-images.githubusercontent.com/18369201/155453571-8ac1fe93-ed58-4100-8766-10c76e055b7a.png)

**Comment by sincovschi** [comment]
Nope, the steps are the same.

![image](https://user-images.githubusercontent.com/42443808/155568232-4c50c113-0a5f-4047-a67e-d43528018b9a.png)

Maybe on your side npm version is cached or something similar.

I've even tried another WSL container with the same result.

**Comment by balazsorban44** [comment]
I've purged my npm cache and reinstalled everything, and still could not reproduce. Regardless, I'll try to verify if there have been any related changes in Next.js after 12.0.7 regarding this. :+1:

**Comment by sincovschi** [comment]
It's working with the version up till **12.0.10**.
It's failing only with **12.1.0**.

When I try to install any canary version I get this error:
![image](https://user-images.githubusercontent.com/42443808/155607482-df0c321c-669a-441a-b577-629d91722aa7.png)

**Comment by sincovschi** [comment]
I've pinpointed the exact piece of code with the Issue, I'll open PR soon.

**Comment by sincovschi** [comment]
https://github.com/vercel/next.js/pull/34795 - the fix has been merged. Waiting for next@12.1.1

**Comment by balazsorban44** [comment]
Nice investigation! :clap: Happy to see it is fixed now :+1:
