### ISSUE TITLE
react-map-gl layer crash when using swcMinify

### ISSUE THREAD

**Issue by cungminh2710** [vercel/next.js#34715]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 14.17.6
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.1
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

Mapbox Layer is not working when using `swcMinfiy:true`. After running `next build` and `next start`, the following errors were returned when viewing in browsers:

`Given varint doesn't fit into 10 bytes`

![image](https://user-images.githubusercontent.com/8063319/155304187-b1b2822a-1684-46c4-a920-4470fb68df52.png)

### Expected Behavior

We should see mapbox layer as it's working in `yarn dev`

### To Reproduce

https://github.com/cungminh2710/nextjs-swc-mapbox

- `yarn && yarn build`
- `yarn start` then navigate to localhost:3000
- layers not showing and errors were logged in console

**Comment by balazsorban44** [comment]
Your reproduction seems to be incomplete. It's missing the `components` folder and some styles.

Removing those, I am able to build but I can see no errors. Could you complete the reproduction?

**Comment by cungminh2710** [comment]
Hi @balazsorban44, sorry. I've added the missing files

**Comment by cungminh2710** [comment]
Hi @balazsorban44 just wanted to check on the status of this. Cheers
