### ISSUE TITLE
Next how to get the backward route address？

### ISSUE THREAD

**Issue by livelyPeng** [vercel/next.js#34750]
### Describe the feature you'd like to request

Getserversideprops, for example, page B returns to page a through the browser return key. How do I get the path of page B on page a? I need to judge whether getserversideprops on page a needs to send a request

### Describe the solution you'd like

No,

### Describe alternatives you've considered

No,

**Comment by timneutkens** [comment]
Hi, please note that you've been continuously spamming the issue tracker over the last few months. Questions should be posted in Discussions: https://github.com/vercel/next.js/discussions. We've repeatedly explained that this is the case and you're unfortunately still ignoring these directions.
