### ISSUE TITLE
fetch behaviour in _middleware is inconsistent between vercel dev and vercel 

### ISSUE THREAD

**Issue by tavvy** [vercel/next.js#34769]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2
```

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

**Headers, and perhaps other `Request` configuration is not sent with `fetch(Request)` in vercel prod.**

For consistent behaviour the `fetch` `init` param must be used.

i.e

```
  const req = new NextRequest("https://some-endpoint.com/", {
    headers: {
      "some-header": "foo=bar",
    },
  });
  
  // request will not have the custom header `some-header`
  await fetch(req);
  
  // request will have the custom header
  await fetch(req.url.toString(), req)
```

According to the spec a Request should be a valid first param, and that can include headers https://fetch.spec.whatwg.org/#concept-request https://developer.mozilla.org/en-US/docs/Web/API/fetch

Indeed the behaves as expected locally with `next dev` or `vercel dev`

### Expected Behavior

Fetch behaviour should be consistent between dev and production

### To Reproduce

This works locally with `vercel dev` but not when deployed to vercel.

(For debugging purposes replace `https://some-endpoint.com/` with a locally running web service exposed via ngrok or similar)

```
import { NextRequest, NextResponse } from "next/server";

export default async function middleware(request: NextRequest) {
  const req = new NextRequest("https://some-endpoint.com/", {
    headers: {
      "some-header": "foo=bar",
    },
  });
  const resp = await fetch(req);
  console.log(resp.status);
  return NextResponse.next();
}
```
The recieving service would see  `request.headers['some-header']`.

However when deployed to Vercel this is not the case, the recieving service will not see `some-header`.

---

To work in vercel prod you must use the fetch `init` param.

Now the recieving service will see `request.headers['some-header']`
```
import { NextRequest, NextResponse } from "next/server";

export default async function middleware(request: NextRequest) {
  const req = new NextRequest("https://some-endpoint.com/", {
    headers: {
      "some-header": "foo=bar",
    },
  });
  const resp = await fetch(req.url.toString(), req);
  console.log(resp.status);
  return NextResponse.next();
}
```

**Comment by balazsorban44** [comment]
Thanks, I could reproduce with the following:

https://balazsorban-34769.vercel.app/

https://github.com/balazsorban44/issue-34769

We will look into this. :+1:

**Comment by ijjk** [comment]
Hi, this has been updated, please re-deploy your application and give it a try!
