### ISSUE TITLE
ESlint error on build (even with starter template)

### ISSUE THREAD

**Issue by SebastianSava** [vercel/next.js#34798]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

When i run npm run build

![image](https://user-images.githubusercontent.com/67977875/155681308-3bf772bb-087a-4d46-a46a-6f9095d550f9.png)

### Expected Behavior

Build

### To Reproduce

npm run build

**Comment by MoltenCoffee** [comment]
Just wanted to post the same issue! Experiencing this as well, both locally and GitHub Actions

````
Windows 11 Education
Node v16.13.0
NPM 8.2.0
```

```
Ubuntu 20.04.3 (Github CI)
Node 16.14.0
```

Turning off `reactStrictMode` in next.config.(m)js does not help.

**Comment by wlee221** [comment]
This is a regression from `eslint-plugin-react`: https://github.com/yannickcr/eslint-plugin-react/issues/3215

**Comment by timneutkens** [comment]
Handled in #34800

**Comment by SebastianSava** [comment]
I have another question. How long does it take to cover all canary updates to stable version? I ask because the default templates still breaks on build.

**Comment by SebastianSava** [comment]
How long it does it take to commit this canary to stable version? I ask because on `npx create-next-app@latest` is still broken. @timneutkens

**Comment by balazsorban44** [comment]
Already in `canary` https://github.com/vercel/next.js/releases/tag/v12.1.1-canary.3

`latest` will follow some time after.

**Comment by psudocode** [comment]
temporary fix

**Comment by jukialen** [comment]
I have v12.1.1-canary.3 but I  still have that errors. I updated eslint-config-next to latest stable and 12.1.1-canary.3.
