### ISSUE TITLE
Build hangs on "Checking validity of types" with Yarn 3 in PnP mode

### ISSUE THREAD

**Issue by srigi** [vercel/next.js#34799]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
/bin/sh: pnpm: command not found

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: root:xnu-7195.141.19~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.5.2
      Yarn: 3.2.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.2
      react: 17.0.2
      react-dom: 17.0.2
```

### How are you deploying your application? (if relevant)

not deploying, running build locally

### Describe the Bug

Creating a default app, switching to Yarn2, and then switching to PnP mode, hangs build process at

```
Checking validity of types
```

Terminal hangs on this log infinitely, CPU is not loaded.

### Expected Behavior

NPM script should finish the build.

### To Reproduce

- `yarn -v` (1.22.17)
- `yarn create next-app .`
- `yarn set version berry`
- `yarn -v` (3.2.0)
- `yarn install` (migrate `yarn.lock` to a new format)
- `yarn build`
Build at this point works as usual.

- change `nodeLinker` to `pnp` in `.yarnrc.yml`
- `yarn install` (migrate `node_modules` to PnP)
- `yarn build`
Hangs...

**Comment by zigang93** [comment]
Duplicate issue of https://github.com/vercel/next.js/issues/34794
