### ISSUE TITLE
Unable to use middleware with Next js 12 + Nx combo without a custom server

### ISSUE THREAD

**Issue by writam-roy** [vercel/next.js#34816]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 14.16.0
      npm: 6.14.11
      Yarn: 1.21.1
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Internal cloud

### Describe the Bug

I see an issue with Next js apps generated within Nx monorepo,where it is not being able to use middleware functionalities and there is an error saying **" cannot use middleware without adding port and hostname to next js server".**

Please suggest what should be the content of the custom server in this scenario to proceed,as with this code attached in the example - https://nextjs.org/docs/advanced-features/custom-server

I get futher issues from Nx saying "customServer is not a function".(Note:- I have made necessary changes to add server.js as a custom path to the Nx project)

### Expected Behavior

Next js apps created within Nx monorepo should work fine with middleware functionalities

### To Reproduce

![image](https://user-images.githubusercontent.com/84510770/155760948-694f8402-c3d9-4958-9754-cbd507b7c321.png)
![image](https://user-images.githubusercontent.com/84510770/155761008-8e512c9f-f280-49ab-8a7f-69443f17c4fc.png)
Unfortunately not able to pass the link to the repo as it is a private one.

**Comment by balazsorban44** [comment]
This should be opened on the Nx repository as it's a feature request to them.

https://github.com/nrwl/nx
