### ISSUE TITLE
Docs: clarification on production builds into docker and bundling dependencies

### ISSUE THREAD

**Issue by dcxn** [vercel/next.js#34815]
### What is the improvement or update you wish to see?

I have a next app in a monorepo context which depends on 2 other apps (or packages). All of them need to run in parallel which I currently achieve with the monorepo tool I'm using (Lerna). I currently find myself needing to the copy the full `node_modules` folder of the next app into my production docker image which I want to run on AWS, otherwise the app wont run. 

For obvious reasons I would prefer to only bundle the absolute minimum assets to run my application, so only built outputs and needed dependencies, while discarding devDependencies since they are irrelevant and increase size. I cannot find docs on this. [As mentioned in this other ticket asking the same thing](https://github.com/vercel/next.js/issues/5531):

> I ask because, when building for Docker, I would like to create the smallest image possible, and when I add a framework (such as material-ui) I am accustomed to adding it as a devDependency. However, with NextJS, it is unclear to me what the runtime needs are: does NextJS need such dependencies for SSR, etc.?

### Is there any context that might help us understand?

I have found 2 similar questions that were closed and point to a discussion that does not seem to offer a solution or information about this request:
* https://github.com/vercel/next.js/issues/5531
* https://github.com/vercel/next.js/issues/5432
* https://github.com/vercel/next.js/issues/4496#issuecomment-512413936 (main issue they point to, which seems like a different use case)

My Next version is 11.

**Comment by balazsorban44** [comment]
Our official Docker documentation would explain this already:

https://nextjs.org/docs/deployment#docker-image

It uses output file tracing, meaning it will only include the code (including node_modules) that's actually being used. 👍

This is a feature introduced in Next 12, so you'll have to upgrade.

More info about it is here: https://nextjs.org/docs/advanced-features/output-file-tracing

**Comment by dcxn** [comment]
We can't upgrade to v12 yet, because of styled components issues, but once those are fixed we will give this feature a try. Thank you for the info!

**Comment by balazsorban44** [comment]
For what it's worth, `12.1` now supports `styled-components` through the SWC compiler:

https://nextjs.org/docs/advanced-features/compiler#styled-components
https://nextjs.org/blog/next-12-1#improved-swc-support

But even then, you can still use Babel as a fallback, if there are some custom plugins that aren't ported yet.
