### ISSUE TITLE
SWC minify not working with styled-components

### ISSUE THREAD

**Issue by vip30** [vercel/next.js#34811]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

1. add styled component (layout) in _app
2. add styled component in pages
3. import createHash from crypto in _app and console.log or use it

### Expected Behavior

It should work without error and if setting swcMinify to false, it works.

### To Reproduce

https://github.com/vip30/next-reproduce

1. `yarn && yarn build && yarn start`
2. open the browser

An endless loop error in console
<img width="2240" alt="image" src="https://user-images.githubusercontent.com/4260833/155751836-356691ef-8bbf-45ab-92ff-a0bd0803766e.png">

**Comment by ngocviet** [comment]
I also have this problem. Is there any workaround, please?

**Comment by balazsorban44** [comment]
This does not seem to be related to `styled-components`. I was able to create a more minimal reproduction of this: https://github.com/balazsorban44/issue-34811

The issue seems to be with using `crypto`:

`pages/_app.js`
```js
import { createHash } from "crypto"

export default function App() {
  createHash("sha256")
  return null
}
```

**Comment by vip30** [comment]
> This does not seem to be related to `styled-components`. I was able to create a more minimal reproduction of this: https://github.com/balazsorban44/issue-34811
> 
> The issue seems to be with using `crypto`:
> 
> `pages/_app.js`
> 
> ```js
> import { createHash } from "crypto"
> 
> export default function App() {
>   createHash("sha256")
>   return null
> }
> ```

But seems it works if without styled-components?

```
page/_app.tsx
const App: FunctionComponent<AppProps> = ({ Component, pageProps }) => {
  createHash("sha256")
  return (
    <Component {...pageProps} key="a"/>
  );
};

```

```
page/index.tsx
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}
```

**Comment by balazsorban44** [comment]
It did throw an error even without `styled-components` for me. I just want to provide the most minimal reproduction to the person who will be looking at a fix. :+1:

**Comment by vip30** [comment]
> I also have this problem. Is there any workaround, please?

wrap the layout component in page level or switch off the swcMinify

**Comment by alex-sherwin** [comment]
Ran up against this as well... 

My issue manifested as React ref's never getting set (but seemingly no other errors), but the underlying cause was from trying to use a hash function from the **crypto** package (ported from a Webpack based app where I was using the **crypto-browserify polyfill** before).

When enabling the new **swcMinify** option, it breaks the production build (as described above, ref's were never getting set, presumably some other runtime exception may have been occurring that wasn't caught/displayed, though)

For now I switched to using the **crypto-js** package for a pure-JS solution for generating SHA256 hashes

**Comment by JohnLouderback** [comment]
I just experience a similar issue with `swcMinify` and styled components causing an infinite loop. Only way I could solve it was turning `swcMinify` off.
