### ISSUE TITLE
naming a variable `module` breaks opening pages when using `next dev`

### ISSUE THREAD

**Issue by MauriceVanVeen** [vercel/next.js#34859]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
    Binaries:
      Node: 16.11.0
      npm: 8.0.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

Naming a variable `module` breaks any page that uses a component which contains that variable (when running `next dev`). Doing `next build` and `next start` does give a functional page however.

### Expected Behavior

Even if a variable is named `module`, it shouldn't break the dev build. (or give a clearer error message, as the source of the error is really time consuming to track down)

### To Reproduce

```typescript
import type { NextPage } from 'next'

const module = 'module.svg'

const Home: NextPage = () => {
  return (
    <div>
      <img alt="" src={module} />
    </div>
  )
}

export default Home
```

As long as the variable at the top is called `module`, upon running `next dev` and opening the page, you will see an error stating: `Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'data')` and a warning in the console `next-dev.js?3515:32 Warning: Did not expect server HTML to contain a <div> in <div>.`

![Screenshot from 2022-02-27 00-07-18](https://user-images.githubusercontent.com/23521895/155861820-462ee846-96d5-405c-99d5-11fd1d63e651.png)

The `module.svg` can be any image. The variable name `module` is the important part. If you change it to anything else, like `moduleImg`, the page will work again.

(it should even be reproducible with `const module = ''`, so not required to add a valid image link)

**Comment by balazsorban44** [comment]
There is unfortunately no quick fix, other than picking a different name for your variable.

Creating a `module` variable hides the normal `module` variable that is used by the HMR react-refresh runtime.

- We can't rename the normal `module` since that is used for CommonJS, e.g. `module.exports = something`
- We could rename the `module` variable via SWC, but that's a bit more involved
- We could lint for `module` when used as a variable name and disallow that.

**Comment by MauriceVanVeen** [comment]
@balazsorban44 that makes sense!

Indeed, quite some work involved otherwise, linting would probably be the way to go.

**Comment by balazsorban44** [comment]
Let's create an ESLint rule for the usage of `module` as a variable name then. Feel free to pick this up in a PR, otherwise, this is open for anyone else.

**Comment by ghulamyazdani** [comment]
can I work on this? @balazsorban44

**Comment by balazsorban44** [comment]
Feel free to! Here is a list of existing rules:

https://github.com/vercel/next.js/tree/canary/packages/eslint-plugin-next/lib/rules

And here is where tests should be added:

https://github.com/vercel/next.js/tree/canary/test/integration/eslint
