### ISSUE TITLE
Link in "Foundations" return 404

### ISSUE THREAD

**Issue by ColonelBucket8** [vercel/next.js#34863]
### What is the improvement or update you wish to see?

There is an error when clicking a link on a page.

### Is there any context that might help us understand?

When a "minified" link is clicked on learn page under "How Next.js Works", it returns 404 error page.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/how-nextjs-works/development-and-production

**Comment by balazsorban44** [comment]
I could not reproduce this, if it was an issue, it likely has been fixed already. Thanks for reporting though! :+1:

**Comment by ColonelBucket8** [comment]
Sorry for not giving enough details. I still got the 404 error page. I'm referring to this link specifically.
![nextjs2](https://user-images.githubusercontent.com/59568628/155890224-e211721d-6d82-4e98-865e-6e8fe52672c7.png)
When I clicked the link, it brought me to this page.
![nextjs3](https://user-images.githubusercontent.com/59568628/155890250-0339ec33-c744-413d-8c57-d50f17932c41.png)

**Comment by balazsorban44** [comment]
Ah, I see. Thanks for the extra nudge. 👍

**Comment by balazsorban44** [comment]
Looks like it's simply

https://nextjs.org/learn/foundations/how-nextjs-works/minification -> https://nextjs.org/learn/foundations/how-nextjs-works/minifying
