### ISSUE TITLE
Docs: What is the proper way to build with NEXT_PUBLIC env vars in docker?

### ISSUE THREAD

**Issue by theogravity** [vercel/next.js#34875]
### What is the improvement or update you wish to see?

I have searched all over on how to get the `NEXT_PUBLIC` to take in my Dockerfile, but the resulting build does not have the value being used at all. 

### Is there any context that might help us understand?

In my frontend code, I am using:

```
const client = new GraphQLClient(`${process.env.NEXT_PUBLIC_FRONTEND_API_URL}`, {
  method: 'GET',
})
```

And this works locally just fine when I use a `.env.local` file with the variable.

Things I've tried:

```
FROM node:16-alpine AS builder

ARG NEXT_PUBLIC_FRONTEND_API_URL
ENV NEXT_PUBLIC_FRONTEND_API_URL=${NEXT_PUBLIC_FRONTEND_API_URL}

... 

RUN echo "NEXT_PUBLIC_FRONTEND_API_URL=${NEXT_PUBLIC_FRONTEND_API_URL}" > .env
RUN npm i && npm run build
```

docker-compose:

```
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - NEXT_PUBLIC_FRONTEND_API_URL=...
```

I've also made sure my `next.config.js` file has the following:

```
  publicRuntimeConfig: {
    NEXT_PUBLIC_FRONTEND_API_URL: process.env.NEXT_PUBLIC_FRONTEND_API_URL,
  },
```

*The built file will just have `NEXT_PUBLIC_FRONTEND_API_URL` as the value.*

```
Request URL: https://xyz.com/NEXT_PUBLIC_FRONTEND_API_URL
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

**Comment by theogravity** [comment]
I figured out my mistake.

- I didn't need to include `publicRuntimeConfig`
- The biggest blunder I did was use `docker-compose restart`, which would restart the *old* image and not use the old one

**Comment by balazsorban44** [comment]
Luckily, there is! https://nextjs.org/docs/deployment#docker-image :slightly_smiling_face: 

It should already handle if your environment variables are in a `.env`, `.env.production` files.
