### ISSUE TITLE
state reset "// @refresh reset" for fast refresh does not work as supposed

### ISSUE THREAD

**Issue by LaCocoRoco** [vercel/next.js#34880]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
 Platform: linux
 Arch: x64
 Version: 1 SMP Debian 4.19.208-1 (2021-09-29)
Binaries:
 Node: 16.13.0
 npm: 8.1.0
 Yarn: N/A
 pnpm: N/A
Relevant packages:
 next: 12.1.0
 react: 17.0.2
 react-dom: 17.0.2
```
### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

Quote from the [NextJS Documentation](https://nextjs.org/docs/basic-features/fast-refresh):
> Sometimes you might want to force the state to be reset, and a component to be remounted. For example, this can be handy if you're tweaking an animation that only happens on mount. To do this, you can add `// @refresh reset` anywhere in the file you're editing...

Fast Refresh does not reset and remount the component when `// @refresh reset` is added anywhere in the file i am editing.

### Expected Behavior

Fast Refresh should reload the component every time i edit the file.

### To Reproduce

1. Problem can be reproduced by replacing the code of index.tsx with the following code in a clean nextjs typescript project.

```typescript
// @refresh reset

import { useState } from "react";

export default function Home() {
  const [foo, setFoo] = useState(false);
  console.log(foo);

  if (!foo) setFoo(true);

  return (<div />);
}
```
2. Run the nextjs in dev environment.
3. Modify code in index.tsx and safe.
```typescript
// @refresh reset

import { useState } from "react";

export default function Home() {
  const [foo, setFoo] = useState(false);
  console.log(foo);

  if (!foo) setFoo(true);

  // new line to trigger fast refresh
  return (<div />);
}
```
4. Console Output on client side.
>false
true
[Fast Refresh] rebuilding
[Fast Refresh] done in 614ms
true
5. As suggested in the in the [NextJS Documentation](https://nextjs.org/docs/basic-features/fast-refresh) the desired output should be.
>false
true
[Fast Refresh] rebuilding
[Fast Refresh] done in 614ms
false
true

The state in the component does not reset after editing the file. This Error is derifed from a [help request](https://github.com/vercel/next.js/discussions/34775) i wrote in the nextjs discussion. I am using the braintree-web package which adds an iframe. After editing the client side throws an error.

> Uncaught (in promise) BraintreeError {name: 'BraintreeError', code: 'HOSTED_FIELDS_FIELD_DUPLICATE_IFRAME', message: 'Element already contains a Braintree iframe.', type: 'MERCHANT', details: {…}}

This problem can be fixed by reloading the page on error:
```typescript
catch (error) {
  if (error instanceof Error) {
    // is this a braintree error
    if (error.name === 'BraintreeError') {
      // force page reload because of fast refresh problem
      const braintreeError = error as unknown as BraintreeError;
      if (braintreeError.code === 'HOSTED_FIELDS_FIELD_DUPLICATE_IFRAME') {
        Router.reload();
      }
    }
  }
}
```
The component, state or better the page should be forcefully reload everytime i edit the file. This is no big problem because it only happens in a development environment, but it is kind of anoying.

Do i miss something or is this a bug?

**Comment by vcheeney** [comment]
I'm having the same issue. 

> Sometimes you might want to force the state to be reset, and a component to be remounted. **For example, this can be handy if you're tweaking an animation that only happens on mount.** To do this, you can add // @refresh reset anywhere in the file you're editing. This directive is local to the file, and instructs Fast Refresh to remount components defined in that file on every edit.

👆 That is the exactly what I'm trying to do.

**Comment by vcheeney** [comment]
@LaCocoRoco Could it be because we are using TS? Might the compiler be removing the `// @refresh reset` from our files?

**Comment by balazsorban44** [comment]
This has been confirmed as a bug in the SWC compiler and is being worked on. TS and JS should work the same way once it's fixed. :+1:

**Comment by alexjball** [comment]
@LaCocoRoco Could you reference the changes that fix this?

**Comment by LaCocoRoco** [comment]
> @LaCocoRoco Could you reference the changes that fix this?

If i remember correctly, it was something like this.
```typescript
useEffect(() => {
  (async () => {
    try {
      const dropinInstance = await create({
        authorization: clientToken,
        container: '#container',
        vaultManager: true,
        googlePay: {
          merchantId: googleMerchantId,
          transactionInfo: {
            currencyCode: currency,
            totalPrice: amount,
            totalPriceStatus: 'FINAL',
          },
        },
        paypal: {
          flow: 'checkout',
          amount: amount,
          currency: currency,
        },
        paypalCredit: {
          flow: 'checkout',
          amount: amount,
          currency: currency
        },
        venmo: true
      });
    } catch (error) {
      if (error instanceof Error) {
        // is this a braintree error
        if (error.name === 'BraintreeError') {
          // force page reload because of fast refresh problem
          const braintreeError = error as unknown as BraintreeError;
          if (braintreeError.code === 'HOSTED_FIELDS_FIELD_DUPLICATE_IFRAME') {
            Router.reload();
          }
        }
      }
    }  
  })();
});
```
