### ISSUE TITLE
next/head order changed

### ISSUE THREAD

**Issue by bobaaaaa** [vercel/next.js#34885]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

firefox, chrome

### Describe the Bug

If I add a `<Head />` component in `_app.js`, `_document.js` and a page, the order of tags changed from next 12.0.10 to 12.1.0. I created an example repo.

## head order next@canary

v12.1.1-canary.4

```html
<meta content="_app.js" />
<meta content="index.js" />
<meta content="_document.js" />
```

## head order next 12.1.0

```html
<meta content="_app.js" />
<meta content="index.js" />
<meta content="_document.js" />
```

## head order next 12.0.10

```html
<meta content="_document.js" />
<meta content="_app.js" />
<meta content="index.js" />
```

### Expected Behavior

It's either a bug or this "feature" is not mentioned anywhere (release notes). In my opinion, the next 12.0.10 version is correct and this is a bug.

### To Reproduce

https://github.com/bobaaaaa/next-bug-head

**Comment by balazsorban44** [comment]
Are you seeing any issues that are a consequence of this?

**Comment by bobaaaaa** [comment]
yes, we had some script order issues. We moved the specific code to `_app.tsx`. This worked, but now we have an increased bundlesize.

**Comment by balazsorban44** [comment]
I believe this is the relevant PR: https://github.com/vercel/next.js/pull/28119

**Comment by bobaaaaa** [comment]
Here is a simplified version for our consent management (broken version):

```html
<!-- _document.tsx -->
<script>
  window.loadOnConsent = (listOfScripts) => {}; // a script loader
</script>
```

```tsx
// _app.tsx
<Head>
  <script dangerouslySetInnerHTML={{ __html: `window.loadOnConsent(${JSON.stringify(getScriptsThatNeedConsent(config))})` }} />
</Head>
```

I know there is the `next/script` component. For us, it is important that we load the consent script as fast as possible. That's why we optimize the loading + execution timings as much as possible. We do this "outside" of react/next and communicate with a global api.

**Comment by balazsorban44** [comment]
For this exact case there is the `beforeInteractive` strategy of `next/script`. Why wouldn't that work? :thinking: 

> Scripts that load with the beforeInteractive strategy are injected into the initial HTML from the server and run before self-bundled JavaScript is executed. This strategy should be used for any critical scripts that need to be fetched and executed before the page is interactive.

https://nextjs.org/docs/basic-features/script#beforeinteractive

**Comment by bobaaaaa** [comment]
@balazsorban44 it has nothing to do with `next/script` :). I only mentioned it because it is the nextjs-standard answer for inlining javascript. But next/script did not work for us

**Comment by balazsorban44** [comment]
It is, because it gives the guarantees for your requirements. I don't understand why it would not work, as the mentioned strategy is optimized for your use case.

But to make sure if we have a different recommendation, I'll ask the rest of the team. :+1:

**Comment by bobaaaaa** [comment]
Here are some reasons why `next/script` did not work for us:

1. `next/script` did not work in `_document.tsx`
2. inlining code with `next/script` == writing code in strings. This works okay for some configs, but not for a lot of functions.
3. you can not easily test code in strings
4. inlined code will also land in the main bundle (waste of bytes)

I have a wishlist for `next/script` :)

1. works in `_document.tsx`
2. `<Script webpackEntryPoint="./path-to-my-script.ts" />`

**Comment by skmohammadi** [comment]
**Google Tag Manager** snippet code was inserted in my case at the end of other meta tags, which caused the same problem.
The problem was solved after moving GTM snippet code to the **top** of meta tags.

**Comment by JanKaifer** [comment]
This is a bug report of unexpected change, but it's not actually a bug in itself.
Since that change happened quite a long time ago, it should be safe to close this now.
