### ISSUE TITLE
Docs: Incorrect answer for quick review question

### ISSUE THREAD

**Issue by lvlshanks** [vercel/next.js#34889]
### What is the improvement or update you wish to see?

The quick review question is incorrectly marked.

### Is there any context that might help us understand?

The quick review question under the section [Adding interactivity with state](https://nextjs.org/learn/foundations/from-javascript-to-react/adding-interactivity-with-state) marks the correct answer as incorrect.
![Screenshot 2022-03-01 002758](https://user-images.githubusercontent.com/6881632/156020360-0b6f6b69-c47c-47fd-bbb5-24ec23f5da35.png)

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/from-javascript-to-react/adding-interactivity-with-state

**Comment by balazsorban44** [comment]
It seems like this has already been fixed:

![image](https://user-images.githubusercontent.com/18369201/156043987-f515f899-f0d9-41b8-8149-23404591aa6c.png)
