### ISSUE TITLE
next/image objectFit produce wrong markup

### ISSUE THREAD

**Issue by fredrik-smedberg** [vercel/next.js#34916]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 98.0.4758.109 (arm64)

### Describe the Bug

I'm trying to get Next Image tag to apply object-fit properly, but from what I can see, it falsely adds it as a non-existing attribute to the img tag:

My NextJS mark up:
```
<div style={{ borderRadius: "8px", overflow: "hidden" }}>
  <Image
    unoptimized
    src={companyLogoUrl}
    width="88"
    height="154"
    alt="company logo"
    layout="fill"
    objectFit="cover"
  />
</div>
```

Resulting HTML:
```
<div style="border-radius: 8px; overflow: hidden;">
<img src="https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg" width="88" height="154" alt="company logo" layout="fill" objectfit="cover">
</div>
```

Computed CSS (for the img tag):
```
aspect-ratio auto 88 / 154
box-sizing border-box
color rgba(0, 0, 0, 0.87)
cursor pointer
display inline
font-family Roboto, Helvetica, Arial, sans-serif
font-size 16px
font-weight 400
height 154px
letter-spacing 0.15008px
line-height 24px
text-size-adjust 100%
width 88px
-webkit-font-smoothing antialiased
```

### Expected Behavior

I was expecting the img tag to **not** get the attributes `layout` or `objectFit`, but rather get them through CSS styling.

### To Reproduce

```
<div style={{ borderRadius: "8px", overflow: "hidden" }}>
  <Image
    unoptimized
    src={companyLogoUrl}
    width="88"
    height="154"
    alt="company logo"
    layout="fill"
    objectFit="cover"
  />
</div>
```

**Comment by balazsorban44** [comment]
I cannot see this issue happening. Here is my output: 

```js
<img alt="company logo" src="https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg" decoding="async" data-nimg="fill" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover">
```

Note the warnings in development though:

> Image with src "https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg" and "layout='fill'" has unused properties assigned. Please remove "width" and "height".

> Image with src "https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg" may not render properly with a parent using position:"static". Consider changing the parent style to position:"relative" with a width and height.

You can read more about the Next.js Image component here: https://nextjs.org/docs/api-reference/next/image
