### ISSUE TITLE
Docs: Redirect the blog post about forms to the forms guide

### ISSUE THREAD

**Issue by kaycebasques** [vercel/next.js#34928]
### What is the improvement or update you wish to see?

Consider redirecting https://nextjs.org/blog/forms to https://nextjs.org/docs/guides/building-forms in order to reduce your docs maintenance overhead and ensure that users are directed to the content that is most likely to stay up-to-date.

FYI I did a lot of work like this when I worked on Chrome DevRel's team. I'd be happy to volunteer to make this change.

### Is there any context that might help us understand?

Searching for `nextjs forms` yields the blog post as the first result:

![image](https://user-images.githubusercontent.com/4713486/156218495-b2f75e74-0f0f-4069-9728-e671b7cbd73f.png)

I imagine that this blog post is less likely to be updated/maintained than the guide.

One thing that will need to be done beforehand is to review each page and make sure that all important ideas covered in the blog post are also covered in the guide. The main thing when deprecating/removing docs is to make sure no key ideas are lost.

### Does the docs page already exist? Please link to it.

https://nextjs.org/blog/forms

**Comment by MaedahBatool** [comment]
Tackled in a PR.
