### ISSUE TITLE
Docs: Buttons in learn page not showing text

### ISSUE THREAD

**Issue by davidballezaa** [vercel/next.js#34939]
### What is the improvement or update you wish to see?

Buttons in nextjs.org/learn do not show text

![image](https://user-images.githubusercontent.com/53234505/156257924-1ccb84e5-db82-4fa0-a40b-3ded53d78652.png)
![image](https://user-images.githubusercontent.com/53234505/156257822-4b9960a1-323b-4b76-bc0a-66b6fdac366d.png)

### Is there any context that might help us understand?

No.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn

**Comment by ijjk** [comment]
Hi, this should be resolved now, thanks for reporting!
