### ISSUE TITLE
next info while a new canary version is running it's workflows says you don't have the latest canary version

### ISSUE THREAD

**Issue by mandar1jn** [vercel/next.js#34930]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

warn  - Latest canary version not detected, detected: "12.1.0", 
newest: "12.1.1-canary.5".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Describe the Bug

When a new canary commit has been pushed to GitHub, but is still running its workflows and has not been published, next info warns you that you are not on the latest canary version even though it's the latest one that is available

### Expected Behavior

It should only warn you once the new canary version has been published.

### To Reproduce

I guess try it when a new canary version has been committed to github

**Comment by balazsorban44** [comment]
We don't expect you to test against a non-existent `canary` version, in this case, you could just ignore the warning. Although if you notice that there is soon a new version published, you can wait until that one is out and test your code with it, to avoid not having checked the latest canary that has a chance fixing your issue. :+1:
