### ISSUE TITLE
Canary: POST to API-routes hang when using middleware

### ISSUE THREAD

**Issue by kevineinarsson** [vercel/next.js#34966]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Aug 25 23:20:18 UTC 2021
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.5
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

cURL

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When using a middleware, POST requests to API-routes never resolve. Commenting out the code added to `next-server.ts` from vercel/next.js#34519 solves the issue. GET works as expected.

Apologies if this is a known issue, thought it would be good to bring up otherwise.

Sidenote: When setting `config.api.bodyParser: false` on API-routes, won't they still have been replaced in the middleware layer, or is it completely separate?

### Expected Behavior

POST requests to api-routes to work.

### To Reproduce

https://stackblitz.com/edit/nextjs-hhf3gk

**Comment by balazsorban44** [comment]
Confirmed, I created this super minimal reproduction as well: https://github.com/balazsorban44/nextjs-34966

`next@12.1.1-canary.1` and up causes the issue, which corresponds with your observation about #34519
