### ISSUE TITLE
Image cache is not preserved between vercel deployments for images with absolute external src URL

### ISSUE THREAD

**Issue by rumtraubenuss** [vercel/next.js#34970]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Happening at least on Next v12.1.0 and v12.1.1-canary.5 deployed to Vercel

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:45 PST 2022; root:xnu-7195.141.19~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.11.1
      npm: 8.0.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.5
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Images optimized with next Image component and default cached on Vercel are not preserved when the `src` attribute is an external URL (i.e. images from images.unsplash.com). After each deployment, for those images, for the first request, the CDN will respond with a `x-vercel-cache: MISS` header.

In contrary this is not happening when an image has a relative `src` URL (i.e. from public folder). In this case the CDN will respond with HIT or STALE even after a deployment.

The image-optimization docs also state that images should be preserved between deployments (https://vercel.com/docs/concepts/image-optimization#usage). See note:
> Even if you redeploy, images cached in /_next/image / /_vercel/image will be preserved.

In other parts of the docs it is said that caches are purged on each deploy. But this seems not to be the case for images in `/_next/image` following the docs mentioned above and actually experiencing that images with a relative URL are actually cached between deployments.

As far as I understand the setup it should not make a difference where the original image comes from. Because the images are optimized and those newly created images are cached in the app.

### Expected Behavior

Image cache for images with absolute external src URL should be cached between deployments. The same way as it happens for images with a relative src URL.

### To Reproduce

I created a test next application which renders two images. One with a local image and one with an external image: https://github.com/rumtraubenuss/vercel-image-cdn-bug

Clone the repo and deploy it to vercel.

Open network dev tools. Make sure to check `Disable cache`. Open the deployed application. Follow the link on the index page. I had to put the images on a second page, otherwise the page preview image in the vercel UI would act as a cache warmer since it requests the actual deployment to render the preview image.

On the page `/cats` you will see two images. Inspect the dev tools network and have a look at the response headers for the two images: For the very first time you open the page for both images the CDN responds with a MISS. Subsequent request (reload the page) will get HIT or STALE responds for both images.

Deploy the app again (you can use the Redeploy option in the vercel UI) wait until it is deployed. Reload the application page. You will see that the local image will have a HIT or STALE, the one with the external URL will have a MISS and therefore take much longer time to render.

Locally I checked the folder `.next/cache/images` and it seems that both kind of images are written to it. So I don't understand why the external URL images are not preserved between deployments.

I tested this with several external images (not only from unsplash) and it was everytime the same behavior.

**Comment by styfle** [comment]
@rumtraubenuss Thanks for reporting this bug!

We have fixed the bug and it will begin rolling out to every Edge region tomorrow morning, thanks!
