### ISSUE TITLE
Cannot resolve "fs/promises" error failing build

### ISSUE THREAD

**Issue by Mitsunee** [vercel/next.js#34977]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022
    Binaries:
      Node: 14.19.0
      npm: 8.5.2
      Yarn: 1.22.17
      pnpm: 6.32.2
    Relevant packages:
      next: 12.1.0 (also tested 12.1.1-canary.6)
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

not relevant

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Since upgrading to Next.js 12.1.0 running `yarn build` produces this error for any import from `"fs/promises"` including pages, their imports and npm packages:

```
yarn run v1.22.17
$ node --version && next build
v14.19.0
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

./src/utils/server/getFileList.js
Module not found: Can't resolve 'fs/promises' in '/home/mitsu/git/Projects/fgo-tools/src/utils/server'
```

This bug was particularly hard to pinpoint as these errors look exactly like the ones you would see when accidentally using Node.js 12 instead of 14 and only appear for `next build` and NOT `next dev`. 

I at first suspected Vercel to be using Node.js 12 and after asking on Twitter added `"engines": {"node":"^14"}` to my package.json (which just produced a warning about ^14 not matching 14.x, but oh well) and changed the build command to `node --version && next build` as seen above. This confirmed that the Vercel deployment was indeed using the exact same version as I was using locally, ruling out Vercel as the issue.

### Expected Behavior

The build succeeds as it did with Next.js 12.0.x and earlier versions.

### To Reproduce

- create a new Next.js project using Next.js version 12.1.0 or canary
- add `import { readFile } from "fs/promises";` to `./pages/index.js`
- run the `next build` command

You should get the following output:

```
$ next build
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

./pages/index.js
Module not found: Can't resolve 'fs/promises' in '/home/mitsu/git/Temp/reproduce-fs-import-crash/pages'


> Build failed because of webpack errors
```

--------

Edit: Wanted to clarify more clearly that this issue only appears on 12.1.0 and newer, not older versions. The main branch of my project is still on 12.0.x and deploys the same code with no issues.

**Comment by balazsorban44** [comment]
This is likely because you are either not using the import or using it in the page component. 

Next.js will try to eliminate imports from the client bundle that is used in data fetching methods like `getStaticProps` etc.

Otherwise, it will fail the build as `fs` is not an API in the browser. Make sure you use the import, and that it's only used in the data fetching methods.

You can test this on this page: https://next-code-elimination.vercel.app/

This is described on each data fetching method, example: https://nextjs.org/docs/basic-features/data-fetching/get-static-props
