### ISSUE TITLE
Incorrect SWC module?

### ISSUE THREAD

**Issue by heymartinadams** [vercel/next.js#34989]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.6
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Chrome 99.0.4844.51 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When I deploy my NextJS app to Vercel, I get the following error on Vercel:

```
error @next/swc-darwin-arm64@11.1.2: The platform "linux" is incompatible with this module.
error @next/swc-darwin-arm64@11.1.2: The CPU architecture "x64" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Command "yarn install" exited with 1
```

I tried `next@12.0.7` as well as the latest `next@12.1.1-canary.6`, both to no avail.

Since my last working deployment, I got a new MacBook Pro with an M1 chip (my previous MBP did not have an M1 chip), and I wonder if that’s the cause somehow.

### Expected Behavior

I would have hoped the deployment would work as expected.

### To Reproduce

Unfortunately I cannot post my entire app here. However, happy to grant access to the app if needed.

**Comment by balazsorban44** [comment]
could you please share the repo with me or create a small public reproduction?

**Comment by heymartinadams** [comment]
Hi @balazsorban44 — just added you to the [repo](https://github.com/ConsciousApps/LifePurposeApp), as well as to [Vercel](https://vercel.com/consciousapps/lifepurposeapp). I’m pushing commits to the repo. Thank you for your assistance!

**Comment by balazsorban44** [comment]
Could you try removing this line:

https://github.com/ConsciousApps/LifePurposeApp/blob/eefb4ff18cdb952d2f942effd905ee9ddacfb60a/package.json#L46

**Comment by heymartinadams** [comment]
Oh no! Having installed the `@next/swc-darwin-arm64": "^11.1.2"` package was the issue! 🤦🏻‍♂ (I believe I previously installed it to get `next@12` to work on my non-M1 MBP. What a rookie mistake.

Thank you so much, @balazsorban44! 🙏🏼

**Comment by balazsorban44** [comment]
Happy to help! Have a nice day.
