### ISSUE TITLE
Docs: Problem with Dockerfile on `with-docker` example - bug for npm users 

### ISSUE THREAD

**Issue by fsgreco** [vercel/next.js#35005]
### What is the improvement or update you wish to see?

A fresh project `with-docker` gives me an error when trying to build the Docker image for the first time.
The problem was due to the fact that I initialized the project via `npx` as suggested by the documentation (and at the same time do not have yarn installed on my system): the command used npm to install everything. As a result when trying to build the image it doesn't found a `yarn.lock` file and the building process return me an error.

I solved it by putting a wildcard on the COPY command:
```
COPY package*.json yarn*.lock ./
```

I can create the pull request myself if its good for you.
Already have the patch in my fork: https://github.com/fsgreco/next.js/commit/305d7eea1775c52bf33856e4e4f8dfb31dad6608

### Is there any context that might help us understand?

There are also some improvements that can be made on the documentation file about that example:
- The Dockerfile is multi-stage but the command suggested to build everything is a unique command
This means that the resulting image will be only the last one (the `production` one).
This could be solved by specifying that the build command should have a specific `--target` option.
I can try to write the fix for this if you agree. :)
In that case should I open a different pull request? 

Sorry for my caution, this is my first issue/pull request on this project :)

### Does the docs page already exist? Please link to it.

https://github.com/fsgreco/next.js/blob/canary/examples/with-docker/README.md

**Comment by ijjk** [comment]
Hi, there's already a comment in the [docker file here](https://github.com/fsgreco/next.js/blob/81c50f4a87a3dd1ef03f2d2c0bbc00447812268e/examples/with-docker/Dockerfile#L9-L11) that mentions how to leverage `npm` instead of `yarn` so I'm not sure we need to document this further.
