### ISSUE TITLE
Vercel deployment error, failed to load swc

### ISSUE THREAD

**Issue by Meriegg** [vercel/next.js#35021]
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

I am deploying an next.js app to vercel.

### How are you deploying your application? (if relevant)

I am deploying to Vercel.

### Describe the Bug

When Vercel tries to build my code i get this error: 

error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
21:51:13.924 | Error: Command "npm run build" exited with 1

When i build the project on my computer using npm run build i do not get this error.

### Expected Behavior

It should build without any errors.

### To Reproduce

Deploy an app to Vercel.

**Comment by Meriegg** [comment]
I think it was a bug in my code. I created a new project and copied all of the code from my old project to the new one and it worked.

**Comment by Meriegg** [comment]
I think it was a bug in my code. I created a new project and copied all of the code from my old project to the new one and it worked.

**Comment by saltovo** [comment]
same problem,but l use next V12.0.10,I dont know how to fix it

**Comment by balazsorban44** [comment]
Please see: https://nextjs.org/docs/messages/failed-loading-swc
