### ISSUE TITLE
Build times with swc are the same speed as babel

### ISSUE THREAD

**Issue by frozberry** [vercel/next.js#35031]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Feb 19 06:37:35 UTC 2020
    Binaries:
      Node: 16.14.0
      npm: 8.5.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I was expecting the swc compiler to greatly improve my build times compared to babel. But after testing the build times on vercel, they seem to be almost identical.

In the repoduction repo below, the speed with swc deploys in 1m 47s. The babel version deploys in 1m 55s - which seems to in margin of error.

### Expected Behavior

Building with swc should be much faster.

### To Reproduce

I originally discovered this on one of my own repos, but I can't share it publicly. However, I was able to reproduce by forking the [Supabase website](https://github.com/frozberry/supabase).

1) Deploy the project on vercel without a `.babelrc`
2) Add a `.babelrc` file with the following: 

```
{
    "presets": ["next/babel"],
    "plugins": []
}
```
3) Deploy on vercel
4) Redeploy the babel version, making sure to not use the build cache.
5) Compare build times

**Comment by balazsorban44** [comment]
The repo you link to seems to be private. Could you add a reproduction so this can be investigated? :pray:

You mention deployment, which is not the same as compilation time. Are you comparing the compilation?

**Comment by frozberry** [comment]
> The repo you link to seems to be private. Could you add a reproduction so this can be investigated? 🙏

Sorry my bad, unprivated it now.
> 
> You mention deployment, which is not the same as compilation time. Are you comparing the compilation?

You're right, I am comparing deployment. Is that a mistake? I assumed that compiling would be a significant part of it deployment. So a 5x improvement in compilation time should lead to noticeable difference in deploy time. I just figured it's easier to compare vercel deployment since it's standardised and logged.

I'm also tested by running `next build` on my local machine, but saw similar times there too.

Am I thinking about this correctly? Maybe it's working as intended, and I just have incorrect assumptions.

**Comment by balazsorban44** [comment]
Depending on project size, dependencies, plugins, etc., compiling could be the smallest or biggest part of a deployment.

I cannot confirm any "bugs" here. If you are having trouble with your project or the build speed, I suggest opening a [question in Discussions](https://github.com/vercel/next.js/discussions/new?category=Help) to get help figuring out what could cause a slow-down in your particular case. :+1:
