### ISSUE TITLE
Error Example (https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs)

### ISSUE THREAD

**Issue by EOM** [vercel/next.js#35066]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

not relevant

### Which example does this report relate to?

https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs

### Describe the Bug

Code Example in Doc

//index.js
import { useState } from 'react'
....
const [likes, setLikes] = React.useState(0)

### Expected Behavior

//index.js
import { useState } from 'react'
....
const [likes, setLikes] = useState(0)

### To Reproduce

Error run

**Comment by balazsorban44** [comment]
it's hard to tell what you are referring to. could you explain better?

**Comment by EOM** [comment]
Hello detects that there is a problem in the documentation. In the code example data error if you don't change it to "useState(0)". Attached screen print so you can see where you have to make the changes. I hope it is clear my English is bad.

Link Print Doc error: https://i.postimg.cc/7LR4BZYm/print-de-pantalla-1472.jpg

**Comment by balazsorban44** [comment]
I see, thank you! You are correct, good catch!
