### ISSUE TITLE
export const getStaticProps = null; will refresh page

### ISSUE THREAD

**Issue by gland2015** [vercel/next.js#35067]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

lasest

### Describe the Bug

export const getStaticProps = null; will refresh page, if you click Link, it will download js and refresh.

### Expected Behavior

don't refresh page

### To Reproduce

export const getStaticProps = null;

**Comment by JanKaifer** [comment]
Not able to repro in `next@canary`
https://github.com/JanKaifer/next-repro-35067
