### ISSUE TITLE
swcMinify breaks build with react-text-transition package

### ISSUE THREAD

**Issue by ch3rn1k** [vercel/next.js#35074]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.4.0: Sat Jan 29 03:25:23 PST 2022; root:xnu-8020.100.417.0.4~31/RELEASE_X86_64
Binaries:
  Node: 14.17.0
  npm: 8.5.2
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.1.0
  react: 17.0.2
  react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 98.0.4758.109

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When using `swcMinify: true` with package `react-text-transition` - it breaks application.

### Expected Behavior

Working build

### To Reproduce

```js
import { useState, useEffect } from 'react';
import TextTransition, { presets } from 'react-text-transition';

const titleTexts = ['Test', 'Test2', 'Test3', 'Test4', 'Test5'];

const Example = () => {
  const [index, setIndex] = useState(0);

  useEffect(() => {
    const intervalId = setInterval(() => setIndex((index) => index + 1), 1 * 3000);

    return () => clearTimeout(intervalId);
  }, []);

  return (
    <TextTransition
      text={titleTexts[index % titleTexts.length]}
      springConfig={presets.gentle}
      inline={true}
    />
  );
};


export default Example;
```

**Comment by balazsorban44** [comment]
Thanks, I could reproduce. Created a small reproduction repository: https://github.com/balazsorban44/nextjs-35074

**Comment by kdy1** [comment]
This is fixed by https://github.com/vercel/next.js/pull/36187

I made a mistake while reproducing this and thought it was not fixed.

I made a correct repro script (https://github.com/swc-project/swc/blob/2563c7f8ff5bb86131f642b6cca948955d795820/crates/swc_ecma_minifier/scripts/next/start.sh) and I found that this issue is fixed.
