### ISSUE TITLE
postcss @custom-media not replaced

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#35080]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: 6.30.0
    Relevant packages:
      next: 12.1.1-canary.6
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

i am using the `postcss-custom-media` plugin, and when i run `next build` the first time (i.e. when the `.next` folder does not yet exist), everything works fine. however, after subsequent builds, the `@custom-media` at rules are not correctly replaced anymore.

### Expected Behavior

`@custom-media` rules should be properly replaced on every build.

### To Reproduce

1. `git clone git@github.com:stefanprobst/next-issue-postcss-custom-media`
2. `cd next-issue-postcss-custom-media/`
3. `yarn`
4. `yarn build && yarn start`
5. Open `http://localhost:3000/` and observe the background color changing when adjusting the viewport width.
6. Also, check `cat .next/static/css/XXX.css` to see the transformed media queries (e.g. `@media (min-width:30rem)`)
7. Edit `nano components/Hero.module.css` and chage a background color, e.g. change `background: lime` to `background: yellow`
8. Run  `yarn build && yarn start` again
9. Open `http://localhost:3000/` and observe that the background color does *not* change anymore when adjusting the viewport width
10. Also check `cat .next/static/css/XXX.css` to see that now the `@custom-media` rules have *not* been replaced (they still show e.g. `@media (--screen-sm)`)

**Comment by sokra** [comment]
Each `*.module.css` file that is imported from your app is a separate CSS compilation. And so is the `global.css`. You can't expect that declarations in the global.css affect the `*.module.css` file. Even if that seem to work sometimes, that is not working as intended (probably some global variables in the postcss-custom-media plugin).

What's more likely to work is if you `@import` as shared `media.module.css` file from each `*.module.css` file where you want to use custom media queries. And place your declarations in that shared file.
This way each CSS compilation knows about the custom media declarations from the shared file.

**Comment by stefanprobst** [comment]
thanks for clarifying.

i might have misunderstood your suggestion, but when i `@import` the custom media queries in a `.module.css` file, the `@custom-media` at rules remain untransformed. see https://github.com/stefanprobst/next-issue-postcss-custom-media/commit/539ec72c42a42a8661a2eae58f844be2520a6cd6 for what i tried.

**Comment by AakashMallik** [comment]
@stefanprobst Yup. This seems to be a problem on my end too. It sometimes works, and sometimes just breaks without any warning. I am really confused as to what is going on. Did you manage to solve this?

**Comment by stefanprobst** [comment]
@AakashMallik unfortunately not, waiting for input from @sokra on how custom media should be used correctly.

**Comment by AakashMallik** [comment]
> 

Call me crazy but I hard refreshed my app and it started working again. I'll try this again if it breaks, hard to say if this is indeed what fixed it.

**Comment by sylvaindubus** [comment]
Having the same issue here... It works very randomly. Did you manage to find a workaround @stefanprobst ?

**Comment by sylvaindubus** [comment]
I think I get it working, just by removing the global import and changing my `postcss.config.json` as follow:

```
"plugins": [
    [
      "postcss-custom-media",
      {
        "importFrom": "styles/breakpoints.css"
      }
    ],
...
]
```

**Comment by VitaliyR** [comment]
Removing `.next` folder helped me, before doing it - postcss changes were never picked up by the nextjs
