### ISSUE TITLE
Image elements should have explicit width and height values

### ISSUE THREAD

**Issue by unigazer** [vercel/next.js#35091]
### Describe the feature you'd like to request

Image element, `<img />`, should have explicit `width` and `height` attributes to satisfy "PageSpeed Insights" diagnostics.

Source: https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=lr#images-without-dimensions

### Describe the solution you'd like

Add `width` and `height` attributes on the HTML image element.

Example:
```html
<img src="/path-to-image.jpg" alt="small but descriptive text" width="24" height="24" />
```

NOTE: `src`, `alt`, `width` and `height` contain example values.

### Describe alternatives you've considered

/

**Comment by balazsorban44** [comment]
We recommend using the `next/image` drop-in replacement for the `img` element. https://nextjs.org/docs/api-reference/next/image

**Comment by unigazer** [comment]
@balazsorban44 Omg, I just noticed that I didn't mention the `next/image` component itself.
I was actually referring to the `next/image` improvements. The `<Image />` component does not add the explicit `width` and `height` on the `<img />` HTML element and my feature request was referring to just that.

**Comment by balazsorban44** [comment]
It infers `width` and `height` for statically imported images already:

https://nextjs.org/docs/api-reference/next/image#width
https://nextjs.org/docs/api-reference/next/image#height

**Comment by unigazer** [comment]
This is what I meant. Take a look at the example below.

Given the example in the screenshot
![Screenshot from 2022-03-09 13-27-43](https://user-images.githubusercontent.com/12301022/157441934-cddc2596-511c-410e-a139-01eb178d19cd.png)

produces this HTML structure
![Screenshot from 2022-03-09 13-30-30](https://user-images.githubusercontent.com/12301022/157442242-76350088-abed-48db-adb0-a4418d13f6ab.png)

HTML from the DOM (from the screenshot)
```html
<img alt="logo" src="/_next/image?url=%2Flogo.png&amp;w=96&amp;q=75" decoding="async" data-nimg="intrinsic" class="rounded-full" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%" srcset="/_next/image?url=%2Flogo.png&amp;w=48&amp;q=75 1x, /_next/image?url=%2Flogo.png&amp;w=96&amp;q=75 2x">
```

and as you can see, the `width` and `height` **attributes** for the HTML image element **are not present**, but they **should be present** in the `<img />` element.

My feature request was to add the `width` and `height` attributes on the `<img />` element for the production version of the Next.js application that is using the `<Image />` component. The original source for proposing this feature comes from this article https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=lr#images-without-dimensions.

This will help developers in gaining a higher score on the "[PageSpeed Insights](https://pagespeed.web.dev/)" web tool because the browser will reduce layout shifts since it knows how much space is required for the remote image, thus providing a better UX and overall better score for page performance.

**Comment by styfle** [comment]
Thanks for reporting this issue!

This is a bug in Lighthouse that will be fixed in https://github.com/GoogleChrome/lighthouse/pull/13737
