### ISSUE TITLE
Prod server `DecodeError: failed to decode param` on special routes.

### ISSUE THREAD

**Issue by jakst** [vercel/next.js#35113]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
Binaries:
  Node: 16.14.0
  npm: 8.3.1
  Yarn: 1.22.17
  pnpm: N/A
Relevant packages:
  next: 12.1.0 (and 12.1.1-canary.6)
  react: 17.0.2
  react-dom: 17.0.2
```

### Describe the Bug

Next.js returns a 400 response on some special routes when there's a catch-all page.

### Expected Behavior

I expect a 404 on routes that don't exist.

### To Reproduce

I've prepped a repo here: https://github.com/jakst/nextjs-router-crash-reproduction

1. Run `yarn build`
1. Run `yarn start`
1. Visit [http://localhost:3000/%ff](http://localhost:3000/%ff)

You will get a `400 Bad Request` instead of `404 Page Not Found` on the document request, but there will also be an underlying server crash that gets logged if you add an `_error` page.

The stack trace for the crash looks like this:

```
DecodeError: failed to decode param
  at decode (./node_modules/next/dist/shared/lib/router/utils/route-matcher.js:18:23)
  at ./node_modules/next/dist/shared/lib/router/utils/route-matcher.js:29:21
  at Array.forEach (<anonymous>)
  at Object.match (./node_modules/next/dist/shared/lib/router/utils/route-matcher.js:23:29)
  at NextNodeServer.renderToResponse (./node_modules/next/dist/server/base-server.js:1072:49)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async NextNodeServer.pipe (./node_modules/next/dist/server/base-server.js:623:25)
  at async Object.fn (./node_modules/next/dist/server/base-server.js:496:21)
  at async Router.execute (./node_modules/next/dist/server/router.js:228:32)
  at async NextNodeServer.run (./node_modules/next/dist/server/base-server.js:600:29)
```

**Comment by balazsorban44** [comment]
@jakst you mention a crash, but I am unable to reproduce that. It only gets logged, but does not crash the server. Can you confirm the process exits for you?

**Comment by jakst** [comment]
@balazsorban44 sorry, you are right. I was too quick to write it up.

It errors, but doesn't crash.

**Comment by jakst** [comment]
@balazsorban44 okay that makes some sort of sense, but I don't expect failing to resolve a route to give 404 in one setup but 400 in the other, even though it never reaches my page handler.

My problem here is that I can't fully choose to handle this case myself. I could check the `res` object for status `400` and show a different ui, but the server will still log a 400. I want to handle these cases and return a 404. How do I do that? There does not seem to be any docs on this as far as I can tell.
