### ISSUE TITLE
PostCSS configuration error with `tailwindcss/nesting` together with `postcss-nesting`

### ISSUE THREAD

**Issue by nicolas-cusan** [vercel/next.js#35117]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```bash
  Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.3.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.6
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

Using the `postcss-nesting` nesting plugin as described in the [Tailwind documentation](https://tailwindcss.com/docs/using-with-preprocessors#nesting) (see section about `postcss-nesting`) results in an error:

```Error: A PostCSS Plugin was passed as an array but did not provide its configuration ('tailwindcss/nesting').```

The PostCSS configuration used is the following:

```js
// postcss.config.js

module.exports = {
  plugins: {
    'postcss-import': {},
    'tailwindcss/nesting': 'postcss-nesting',
    tailwindcss: {},
    'postcss-preset-env': {
      features: { 'nesting-rules': false },
    },
  },
};
```

It looks like it does not resolve `postcss-nesting` to a valid config for `tailwindcss/nesting` or there is a check in place to force plugin values to be objects instead of a strings. I also tried the following without luck:

```js
// postcss.config.js

module.exports = {
  plugins: {
    'postcss-import': {},
    'tailwindcss/nesting': {'postcss-nesting' : {}},
    tailwindcss: {},
    'postcss-preset-env': {
      features: { 'nesting-rules': false },
    },
  },
};
```

the above results in a tailwind error: `Error: tailwindcss/nesting should be loaded with a nesting plugin.`

The configuration as provided in the tailwind docs has worked for me when using other non next.js setups, so I asume the issue is with next.js and the way it handles postcss.config.js

### Expected Behavior

For the configuration to work as expected.

### To Reproduce

Go to this sandbox: https://codesandbox.io/s/white-snow-um2w00 see the error in the terminal.

To test, remove the config file and the css import in `pages/_app.js` and all works fine.

**Comment by lucasvazq** [comment]
Other workaround: use `cssnano` and forget `tailwindcss/nesting` when using `postcss-preset-env`.
https://github.com/tailwindlabs/tailwindcss/issues/4634

**Comment by nicolas-cusan** [comment]
@lucasvazq thanks for the tip, will try that.
