### ISSUE TITLE
Inline next-transpile-modules 

### ISSUE THREAD

**Issue by jaredpalmer** [vercel/next.js#35150]
### Describe the feature you'd like to request

As a monorepo user that leverages yarn, npm, pnpm workspaces, Next.js requires an external plugin that degrades build performance (`next-transpile-modules`) because of symlink quirks. 

### Describe the solution you'd like

Inline/enable a similar feature to `next-transpile-modules` directly into Next.js. 

For example, imagine there is a package called `@acme/ui` in a workspaces monorepo. 

```jsonc
// package.json
{
  "name": "my-app",
  "dependencies": {
     "next": "latest",
     "@acme/ui": "*" // or "workspace:*" in pnpm and yarn 2+
   }
}
```

```js
// next.config.js
module.exports = {
    transpileModules: ['@acme/ui'] 
}
```

### Describe alternatives you've considered

n/a

**Comment by leerob** [comment]
![image](https://user-images.githubusercontent.com/9113740/157283571-7dedadcb-db2a-4307-b1fa-e9743497af4a.png)

**Comment by remorses** [comment]
An alternative would be to always transpile paths that do not contain "node_modules"

This is always valid in yarn, npm and pnpm workspaces, the local packages real paths (the path linked by symlinks) will always be in a directory out of `node_modules`

**Comment by timneutkens** [comment]
@remorses that's already covered by `externalDir` for TypeScript files: https://github.com/timneutkens/next.js/blob/canary/packages/next/build/webpack-config.ts#L866-L869

I agree that you shouldn't have to configure what packages exist in a workspaces setup, basically expanding `externalDir` to all code. Even with that change there's still the case of people wanting to downlevel specific packages to run in older browsers.

**Comment by matamatanot** [comment]
Is there any update on this issue?

**Comment by matamatanot** [comment]
@jaredpalmer 
Is this feature already implemented?
https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages

The `next-transpile-modules` is still used in turborepo docs. Is there any plan to change it?
https://turbo.build/repo/docs/handbook/sharing-code/internal-packages#6-configuring-your-app
