### ISSUE TITLE
Image paths are incorrectly escaped

### ISSUE THREAD

**Issue by wulisensen** [vercel/next.js#35201]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

node16
next@12.1.0

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

no

### Describe the Bug

when i import a website image to my scss

```
 background: url('https://xxxxxxx/i1/O1CN01NGMXoe1zlq9Bxfwex_!!60000000aaa.png') no-repeat;
```

i get a error

external "https://xxxxxxx/i1/O1CN01NGMXoe1zlq9Bxfwex_!!./60000000aaa.png"
The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script

‘_!!66’ => '_!!./66'

### Expected Behavior

i want get zhe real img url without change

### To Reproduce

            &_font {
                line-height: 33px;
                font-family: PingFangSC-Medium;
                font-size: 13px;
                color: #FFFFFF;
                text-align: center;
                background: url('https://img.xxx.com/imgextra/i1/O1CN01NGMXoe1zlq9Bxfwex_!!6000000006755-2-tps-48-48.png') no-repeat;
                background-size: 12px;
                background-position: top 10px right 9px;
            }

**Comment by wulisensen** [comment]
When I downgrade to 11.4.0 it is ok

**Comment by JanKaifer** [comment]
This should be fixed in the new `next/image`.
