### ISSUE TITLE
with-aws-amplify-typescript uses legacy AmplifyAuthenticator

### ISSUE THREAD

**Issue by swalker326** [vercel/next.js#35222]
### Describe the feature you'd like to request

Currently uses AmplifyAuthenticator which is legacy. Also using an older verison of `@aws-amplify/ui-react` & `aws-amplify`

### Describe the solution you'd like

Should be using the new Authenticator componet

### Describe alternatives you've considered

Keep using the old one until is deprecated

**Comment by ELBEQQAL94** [comment]
This issue is still open I would like to contribute?

**Comment by sifanjoraboris** [comment]
Helping
