### ISSUE TITLE
Middleware rewrite doesn't work when directly accessing a page or doing a full refresh of a page

### ISSUE THREAD

**Issue by patricklafrance** [vercel/next.js#35227]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

When accessing a page directly or doing a full refresh of a page, a middleware rewrite doesn't work. When navigating between pages with next/link it does work though.

### Expected Behavior

Middleware rewrite is working when accessing a page directly or doing a full refresh of a page.

### To Reproduce

The bug is reproduced in the following code sandbox https://codesandbox.io/s/dawn-surf-ory5le

If you access the index page directly you'll see "Hello" instead of "Hello toto". If you navigate between the index and the about pages, you'll start seeing "Hello toto" on the index page.

**Comment by ranno-lauri** [comment]
Also having this issue, but only on preview and production deployment. On local dev server, everything is fine. Posting some logs from Logflare, that maybe are useful, as I am seeing some differences between the requests. When accessing the page with next/link, everything is working and the lambda log is:

## With Link(static page)[pre-fetched]
`{
  "deploymentId": "dpl_5tLrienkUfC76d3VeBhUjt4i35cm",
  "host": "cervera-app-4e52tnf8p-cervera.vercel.app",
  "id": "1648123080233341561032941314",
  "path": "/_next/data/iGPhGY4JS3nFPOMhlWvio/se/contacts.json",
  "projectId": "prj_E9SozIclgW9xJIksZu3xJfInp22u",
  "proxy": {
    "cacheId": "z6kn2-1648122973118-58fadb555f14",
    "clientIp": "84.50.132.226",
    "host": "cervera-app-4e52tnf8p-cervera.vercel.app",
    "method": "GET",
    "path": "/_next/data/iGPhGY4JS3nFPOMhlWvio/se/contacts.json",
    "referer": "https://cervera-app-4e52tnf8p-cervera.vercel.app/",
    "region": "arn1",
    "scheme": "https",
    "statusCode": 200,
    "timestamp": 1648123080233,
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
  },
  "requestId": "arn1::arn1::z6kn2-1648123080233-86b4d146fffb",
  "source": "static",
  "timestamp": 1648123080233
}`


### Directly accessing(static page)
`{
  "deploymentId": "dpl_5tLrienkUfC76d3VeBhUjt4i35cm",
  "host": "cervera-app-4e52tnf8p-cervera.vercel.app",
  "id": "1648123155926341561032946105",
  "path": "/kundservice",
  "projectId": "prj_E9SozIclgW9xJIksZu3xJfInp22u",
  "proxy": {
    "cacheId": "gpbxh-1648121519010-f30e2bf7db1e",
    "clientIp": "84.50.132.226",
    "host": "cervera-app-4e52tnf8p-cervera.vercel.app",
    "method": "GET",
    "path": "/kundservice",
    "region": "arn1",
    "scheme": "https",
    "statusCode": 404,
    "timestamp": 1648123155714,
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
  },
  "requestId": "arn1::arn1::z6kn2-1648123155714-ca6d8f0de72f",
  "source": "static",
  "timestamp": 1648123155926
}`

Main difference I can see, is the `path` property.


### With Link(SSR with slug)
` {
  "deploymentId": "dpl_5tLrienkUfC76d3VeBhUjt4i35cm",
  "host": "cervera-app-4e52tnf8p-cervera.vercel.app",
  "id": "1648121604058440703918928744",
  "path": "fi/product/[slug]",
  "projectId": "prj_E9SozIclgW9xJIksZu3xJfInp22u",
  "proxy": {
    "cacheId": "b766t-1648116145520-172be34ae25f",
    "clientIp": "84.50.132.226",
    "host": "cervera-app-4e52tnf8p-cervera.vercel.app",
    "method": "GET",
    "path": "/_next/data/iGPhGY4JS3nFPOMhlWvio/fi/product/gen-veitsisetti-kokkiveitsi-leikkuuveitsi.json?slug=gen-veitsisetti-kokkiveitsi-leikkuuveitsi",
    "referer": "https://cervera-app-4e52tnf8p-cervera.vercel.app/fi",
    "region": "arn1",
    "scheme": "https",
    "statusCode": 200,
    "timestamp": 1648121604054,
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
  },
  "requestId": "arn1::arn1::gpbxh-1648121604054-846a9e84d7c5",
  "source": "lambda",
  "timestamp": 1648121604058
} `    

### Directly accessing(SSR with slug)
lambda log: 
`{
  "deploymentId": "dpl_5tLrienkUfC76d3VeBhUjt4i35cm",
  "host": "cervera-app-4e52tnf8p-cervera.vercel.app",
  "id": "1648121794226550034815593842",
  "message": "START RequestId: 592079cf-9634-4ff2-9f51-1f746c58a7b9 Version: $LATEST\nEND RequestId: 592079cf-9634-4ff2-9f51-1f746c58a7b9\nREPORT RequestId: 592079cf-9634-4ff2-9f51-1f746c58a7b9\tDuration: 396.06 ms\tBilled Duration: 397 ms\tMemory Size: 1024 MB\tMax Memory Used: 205 MB\t\n",
  "parsedLambdaMessage": {
    "report": {
      "billed_duration_ms": 397,
      "duration_ms": 396,
      "max_memory_used_mb": 205,
      "memory_size_mb": 1024
    },
    "request_id": "592079cf-9634-4ff2-9f51-1f746c58a7b9"
  },
  "path": "fi/product/[slug]",
  "projectId": "prj_E9SozIclgW9xJIksZu3xJfInp22u",
  "proxy": {
    "clientIp": "84.50.132.226",
    "host": "cervera-app-4e52tnf8p-cervera.vercel.app",
    "method": "GET",
    "path": "/fi/tuote/gen-veitsisetti-kokkiveitsi-leikkuuveitsi",
    "region": "arn1",
    "scheme": "https",
    "statusCode": 404,
    "timestamp": 1648121794166,
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
  },
  "requestId": "arn1::arn1::4ppxp-1648121794166-af8765ee9ddb",
  "source": "lambda",
  "statusCode": 404,
  "timestamp": 1648121794226
}`

To me the most notable difference is in `proxy.path` and missing `proxy.referer` on the second request. In addition, I verifed that the middleware is being called in both  cases and the url passed to `NextResponse.rewrite()` is the same
