### ISSUE TITLE
standalone not works with pnpm in docker

### ISSUE THREAD

**Issue by w4-hanggi** [vercel/next.js#35235]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: 6.32.3
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

The generated standalone with pnpm are symbolink.
In step docker build, it will not contain the pnpm node_modules

### Expected Behavior

Use non symbol link in standalone output.

### To Reproduce

https://github.com/vercel/next.js/tree/canary/examples/with-docker

just execute the example with pnpm

**Comment by siva-kannan3** [comment]
I'd like to work on it, can somebody assign me?
