### ISSUE TITLE
Cannot import passport-discord

### ISSUE THREAD

**Issue by ZetraDev** [vercel/next.js#35234]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 3.2.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.9
      react: 18.0.0-rc.2
      react-dom: 18.0.0-rc.2

### What browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

When trying to import `passport-discord` in api route, it will return:
```
error - ./src/utils/DiscordStrategy.ts?__sc_server__:1:0
Module not found: Can't resolve 'passport-discord?__sc_server__'

Import trace for requested module:
./src/middleware/withPassport.ts?__sc_server__
./src/pages/api/auth/index.server.ts
```

### Expected Behavior

no error

### To Reproduce

import passport-discord in api route

**Comment by balazsorban44** [comment]
We would need a proper reproduction to investigate. Keep in mind that Middleware code (in your case `passport-discord` and all of its dependencies) should not rely on Node.js specific APIs.

https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis

**Comment by ZetraDev** [comment]
I'm use passport inside a api route instead of middleware

**Comment by ZetraDev** [comment]
like:
```ts
// src/pages/api/auth/index.ts
import DiscordStrategy from "xxx/DiscordStrategy.ts" // where the passport-discord was imported
```

**Comment by balazsorban44** [comment]
Could you still add a reproduction, please? :pray:

**Comment by ZetraDev** [comment]
I just found out that somehow passport-discord wasn't actually installed while vs code not showing error, the problem solved after i installed it, sorry for wasting your time :(
