### ISSUE TITLE
Docs: Custom Server conf object

### ISSUE THREAD

**Issue by guaiamum** [vercel/next.js#35260]
### What is the improvement or update you wish to see?

I would love to understand what is the purpose and ideal use case for the conf object when using a custom server.

### Is there any context that might help us understand?

We're using a custom express server for next and as usual we initialize the next server with:

```js
import next from 'next';
import nextConfig from '../../next.config';

const app = next({
  dev: DEVELOPMENT,
  conf: nextConfig,
});

//...
```

recently I tried commenting the `conf` line, and still, the `next.config.js` is used, and the application runs beautifully. That means next automagically loads the config in case you don't pass any override?

Another thing I checked was regarding the `assetPrefix` config, which is a client configuration, but we load it in the server initialization, which is so weird to me... Is that the way it's supposed to be?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/custom-server

**Comment by leerob** [comment]
<img width="685" alt="CleanShot 2023-09-24 at 10 13 53@2x" src="https://github.com/vercel/next.js/assets/9113740/8c16d4b8-947d-4cac-8fbe-a54ee8cfe4b8">

This is now more clear: https://nextjs.org/docs/pages/building-your-application/configuring/custom-server
