### ISSUE TITLE
unstable_revalidate fails on routes with auth

### ISSUE THREAD

**Issue by cole21771** [vercel/next.js#35272]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.10
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

The new res.unstable_validate feature cannot seem to get past my basic auth middleware throwing an error with the message `Failed to revalidate /route`.

Is there anything I can do to avoid this or is this just something that won't be supported?

### Expected Behavior

I would expect to be able to invalidate the cache of a route with an basic auth middleware. Or maybe to provide some way around it if it can't be avoided?

### To Reproduce

```typescript
// pages/admin/_middleware.ts
import { NextResponse } from 'next/server';

export const adminMiddleware = (req) => {
  const basicAuth = req.headers.get('authorization');

  if (basicAuth) {
    const auth = basicAuth.split(' ')[1];
    const [user, pass] = Buffer.from(auth, 'base64').toString().split(':');
    console.log(`Attempted login from ${user}`);

    if (user === 'user' && pass === 'pass') {
      console.log('Successful login!');
      return NextResponse.next();
    }
  }

  return new Response('Auth required', {
    status: 401,
    headers: {
      'WWW-Authenticate': 'Basic realm="Secure Area"'
    }
  });
};
```

```typescript
// pages/admin/index.ts
import { useState } from 'react';

export default function Admin({ testValue }) {

  const revalidate = async () => {
    const confirmation = confirm('Are you sure you want to revalidate cache?');

    if (confirmation) {
      const res = await fetch('/api/admin/revalidate');
      const data = await res.text();
      alert(`Revalidate Response: ${data}`);
    }
  };

  return (
    <div>
      <div>Admin page</div>
      <button onClick={revalidate} >
        Revalidate
      </button>
      {test.toString()}
    </div>
  );
}

export const getStaticProps = () => {
  return {
    props: {
      testValue: Math.random()
    }
  };
};
```

```typescript
// pages/api/admin/revalidate.ts
export default async function revalidate(req, res) {
  try {
    await res.unstable_revalidate('/admin');

    return res.status(200).json({ success: true });
  } catch (err) {
    return res.status(500).json({ success: false, msg: err.message });
  }
}
```

These three files in a basic next project should give you what you need to easily reproduce this issue. The basic auth middleware, the admin page protected by said middleware, and the revalidate endpoint that the button on the admin page calls.

**Comment by balazsorban44** [comment]
Closing in favor of the discussion at https://github.com/vercel/next.js/discussions/35659. Feel free to leave any comments there. :+1:
