### ISSUE TITLE
On-demand ISR unable to revalidate page after build using Node 17

### ISSUE THREAD

**Issue by lydiahallie** [vercel/next.js#35309]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.0.1
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

The `unstable_revalidate` function throws an error when accessing the route after running `yarn build` when using Node 17

```
Error: Failed to revalidate /
    at unstable_revalidate (/Users/lydiahallie/Desktop/ondemand-isr/node_modules/next/dist/server/api-utils/node.js:236:11)
    ...
```

The `fetch` within this function is unable to connect to the page to revalidate, and throws a `FetchError`

### Expected Behavior

The `unstable_revalidate` function should be able to revalidate the necessary pages after running `yarn build`.

### To Reproduce

1. Clone the [reprod example](https://github.com/lydiahallie/ondemand-isr-bug-reprod) `git clone https://github.com/lydiahallie/ondemand-isr-bug-reprod.git` 
2. Run `yarn build`
3. Run `yarn start`
4. Navigate to `http://localhost:3000/api/revalidate`

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.1-canary.14` of Next.js, please update and give it a try!
