### ISSUE TITLE
Slow start when lots of files on public folder

### ISSUE THREAD

**Issue by santigimeno** [vercel/next.js#35305]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: linux
      Arch: x64
      Version: #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022
    Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.10
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

Increasing the number of files in the `/public` folder makes the next.js application startup to slow down while driving CPU and memory consumption up until the startup procedure ends or it crashes due to getting OOM. These are the numbers I'm observing in my dev box:
| # files in /public folder | startup time |
| ------------------------------|-----------------|
|    1K                             |  269.062ms |
|   200K                          |  1.550s        |
|    1M                            |   7.523s       |
|   10M                         |   1m27s263ms (**until OOM crash**) | 

By running a CPU profile on the process, it looks like most of the time is spent on the [recursiveReadDirSync](https://github.com/vercel/next.js/blob/9f54b56bdea140f6aa474ebf39ed2cd98b3f7c8c/packages/next/server/lib/recursive-readdir-sync.t) function when called from [here](https://github.com/vercel/next.js/blob/canary/packages/next/server/next-server.ts#L429) which seems to make sense with the observation.

### Expected Behavior

First of all. Is this to be expected? By looking at the documentation on the `public` folder from https://nextjs.org/docs/basic-features/static-file-serving, it doesn't mention any issues with serving many static files though it makes a recommendation on using a 3rd party service for persistent file storage. Is this the actual reason?

### To Reproduce

- Create the basic acc with `npx create-next-app`
- Create/Add the desired number of files in the `/public` folder.
- Run: `npm run build`
- Run `npm run start`  and check the CPU and memory usage and the time it takes to the server to be responsive depending on the number of files.

**Comment by santigimeno** [comment]
@balazsorban44 sorry for the delay, I somehow missed the notification.
We're serving that amount of static assets (documents mainly) and yes, they're referenced by the app. To be clear, I just wanted to confirm whether this is the expected behavior and we shouldn't use Next.js for this use case (and probably state it more clearly in the documentation) or maybe it's something to improve in the framework. Thanks in advance!

**Comment by timneutkens** [comment]
You can use Next.js just fine for this use case, just not for serving 10 million files from `public`. `public` is considered an immutable directory which is read during bootup to ensure that only the files that exist during bootup can be served for the duration of the process. This was done to ensure there is no way out of the directory itself for serving given that any other path would not be served. It was added after a few directory traversal vectors were uncovered over the years.

I think the note on using external file hosts should be expanded to reflect that it's recommended to keep under a certain amount of files in `public`.

**Comment by samcx** [comment]
I think we're good to close this issue, despite that <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture> closed. Folks should still be able to find this issue.
