### ISSUE TITLE
custom express server TransformStream is not defined

### ISSUE THREAD

**Issue by CRAKZOR** [vercel/next.js#35314]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 17.7.1
      npm: 8.5.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.11
      react: 17.0.2
      react-dom: 17.0.2

### Which example does this report relate to?

https://github.com/vercel/next.js/tree/canary/examples/custom-server-express

### What browser are you using? (if relevant)

chrome 99.0.4844.51

### Describe the Bug

The error below occurs when navigating to any route. Error in render. relevant #34005. 
edit: Issue is for v12.0.11-canary.7+

```
ReferenceError: TransformStream is not defined
    at streamFromArray (/Developer/next-js/node_modules/next/dist/server/render.js:1259:38)
    at Object.renderToHTML (/Developer/next-js/node_modules/next/dist/server/render.js:967:9)
    at async doRender (/Developer/next-js/node_modules/next/dist/server/base-server.js:859:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/Developer/next-js/node_modules/next/dist/server/base-server.js:958:28)
    at async /Developer/next-js/node_modules/next/dist/server/response-cache.js:72:36
error - ReferenceError: TransformStream is not defined
```

### Expected Behavior

It should SSR and display page normally.

### To Reproduce
edit: I've determined the problem to come from using the 'mailgun.js' library. The error may be reproduced by adding mailgun.js to package.json and requiring from server.js. The issue only occurs on v12.0.11-canary.7+. 

*1. yarn add mailgun.js
*2. include ```const Mailgun = require('mailgun.js');``` in server.js
3. start server
4. navigate to any route

* new steps from edit 1/16/22

**Comment by balazsorban44** [comment]
Given the above steps, I am unable to reproduce this :thinking: `TransformStream` is polyfilled when not available:

https://github.com/vercel/next.js/blob/694407450638b037673c6d714bfe4126aeded740/packages/next/server/node-polyfill-web-streams.js#L7

Could you create a small reproduction repository that I can use to investigate further? :pray:

**Comment by CRAKZOR** [comment]
> Given the above steps, I am unable to reproduce this (in neither dev nor production) 🤔. `TransformStream` is polyfilled when not available:
> 
> https://github.com/vercel/next.js/blob/694407450638b037673c6d714bfe4126aeded740/packages/next/server/node-polyfill-web-streams.js#L7
> 
> Could you create a small reproduction repository that I can use to investigate further? 🙏


hello,

In that file, adding a check for TransformStream fixes the issue for me.

```javascript
if (!global.ReadableStream || !global.TransformStream) {
    global.ReadableStream = _readableStream.ReadableStream;
    global.TransformStream = _webStreamsPolyfill.TransformStream;
}
```

**Comment by CRAKZOR** [comment]
solved by moving all the require statements, which  include the mailgun.js library, inside the then block after prepare. ie:
```javascript
const nextApp = next({ dev })

nextApp.prepare().then(() => {

  const Mailgun = require('mailgun.js');
  const app = express();
  ...
  const server = app.listen(process.env.PORT);

})
```

**Comment by balazsorban44** [comment]
Polyfills aren't applied to the `server.js` module, so the issue is that your dependency probably relies on `TransformStream` but does not polyfill it. You might want to report it in their repo if you can verify the issue is certainly with Mailgun
