### ISSUE TITLE
axios break getServerSideProps in server component page

### ISSUE THREAD

**Issue by ZetraDev** [vercel/next.js#35322]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 3.2.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.10
      react: 18.0.0-rc.2
      react-dom: 18.0.0-rc.2

### What browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

When trying to use axios to fetch something inside a getServerSideProps of a server component page, nextjs will spam the warning below while the page successfully rendered:
```
warn  - ./.yarn/__virtual__/follow-redirects-virtual-2db68225c5/0/cache/follow-redirects-npm-1.14.9-522f191631-f5982e0eb4.zip/node_modules/follow-redirects/debug.js
Module not found: follow-redirects tried to access debug (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: debug
Required by: follow-redirects@virtual:a6641ce4e3bdcc0997f8f53d9481b67c5d38e21276de8eeee7bf92881685b3ad5600bae416c2af904ceab8132bac649e7efd0af93f18e158e0e65ee05a263d72#npm:1.14.9 (via D:\xxx\.yarn\__virtual__\follow-redirects-virtual-2db68225c5\0\cache\follow-redirects-npm-1.14.9-522f191631-f5982e0eb4.zip\node_modules\follow-redirects\)

Ancestor breaking the chain: axios@npm:0.26.1

Did you mean './debug'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

### Expected Behavior

no error

### To Reproduce

use axios to fetch something in getServerSideProps of server component page, here's my example:
```tsx
// /src/pages/xx/xx/index.server.tsx
import { GetServerSidePropsContext } from "next";
import React from "react";
import axios from "axios";

export default function Index(props: any) {
	console.log(props) // It successfully return the data fetched
	return (
		<React.Fragment>
        		<p>{JSON.stringify(props.xxx)}</p>
		</React.Fragment>
	);
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
	const {req: {cookies: {session}}} = ctx;
	if (!session) return {redirect: {destination: "/"}}
	try {
		const {data: xxx} = await axios.get("/api/xxx", {
			headers: {
				Cookie: `session=${session}`
			}
		})
		return {props: {xxx}}
	} catch (err) {
		return {redirect: {destination: "/"}}
	}
}
```

**Comment by ZetraDev** [comment]
I tried to switch it to client component page(change server.tsx to client.tsx) and theres no warning spam

**Comment by balazsorban44** [comment]
Given you are using experimental features, could you add a full reproduction, please? :pray: Using something else than Yarn seems to work fine, so I suspect the problem is related to that.

**Comment by ZetraDev** [comment]
here's the reproduction: https://github.com/ZetraDev/nextjs-reproduction

**Comment by balazsorban44** [comment]
Hmm. I am unable to reproduce any issues using Yarn `1.22.18`.

There seems to be a similar issue reported at Yarn's repo: https://github.com/yarnpkg/berry/issues/3925

In any case, I don't think this has to do with Next.js. It is likely an issue in `follow-redirects`, which is a dependency of `axios`.
