### ISSUE TITLE
Update example of with-react-native-web

### ISSUE THREAD

**Issue by sayem314** [vercel/next.js#35324]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

N/A

### Which example does this report relate to?

with-react-native-web

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

The current example seems to be for Next.js 11. It needs to be updated for v12.

### Expected Behavior

N/A

### To Reproduce

N/A

**Comment by balazsorban44** [comment]
This is incorrect, it uses whatever `latest` is at all times, which is currently 12. Make sure you don't have some random cache or similar on your local machine that for some reason prohibits you from getting Next 12 when `latest` is used as a version.

https://github.com/vercel/next.js/blob/91136d231ea992462ba11f0b564d8144fff844ec/examples/with-react-native-web/package.json#L9
