### ISSUE TITLE
Example+Doc page for "Where to store persistent/global data?"

### ISSUE THREAD

**Issue by peteristhegreat** [vercel/next.js#35346]
### Describe the feature you'd like to request

With the advent of react-hooks and all the different ways to store sessions across cookies, jwt, state management, etc, I think there should be a page in the documentation of some best practices for this, or some strong recommendations.

### Describe the solution you'd like

Something that recommends how to store global information across the app for a user.  Outside of Authentication information, the other variables that go with the user.

Maybe a page that makes it easier to find the `with-iron-session` and how it ought to be used for session globals.

### Describe alternatives you've considered

For a while I was trying to keep some session information in the url and having conditional routing based on url information in the path with wild cards like `[id]` in the path and read it with `useRouter`, but that causes a lot of these kinds of errors during the prerendering page `npm run build`  steps.
```
Error: No router instance found.
You should only use "next/router" on the client side of your app.
```
This closed/expired issue page still looks definitive because it is a top hit in google when searching for how to do it in nextjs.
https://github.com/vercel/next.js/issues/2252

I nearly jumped on `nookies` or `react-cookies`... then I found the example for `with-iron-session`.  I'm giving that a try since it matches most of my criteria.

react-hook-form recommends `Redux` or `little-state-machine` here  
https://react-hook-form.com/advanced-usage#WizardFormFunnel

**Comment by balazsorban44** [comment]
You can refer to https://nextjs.org/docs/authentication which lists many good third-party libraries that handle authentication for you, in addition to some basic guidance on how to authenticate in certain scenarios. :+1:
