### ISSUE TITLE
getStaticProps NEVER called again if it got 404 before in 12.1

### ISSUE THREAD

**Issue by futantan** [vercel/next.js#35352]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
    Binaries:
      Node: 12.22.10
      npm: 6.14.16
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

For example, we have a `pages/[site].js` file:
```js
import React from 'react'

export const getStaticPaths  = async () => {
  return {
    paths: [],
    fallback: 'blocking',
  }
}

export const getStaticProps = async (req) => {
  console.log('in getStaticProps')
  const v = Math.random()
  if (v < 0.7) {
    return { notFound: true }
  }

  return {
    props: { v },
    revalidate: 10,
  }
}

const BlogIndexPage = ({v}) => {
  return <div>hello world {v}</div>
}
export default BlogIndexPage
```
in nextjs version 12.1.0, if `getStaticProps` return `{ notFound: true }` once, the `getStaticProps` function will never be called again even if the revalidate time expired!

Version 11.1.0 works!

### Expected Behavior

`getStaticProps` should be called again if it's `{ notFound: true }`

### To Reproduce

Code above, using nextjs 12.1.0
Version 11.1.0 works.

**Comment by futantan** [comment]
Tested in local environment, using `yarn build` then `yarn start`

**Comment by futantan** [comment]
Since I'm using the feature **middleware**, it's not possible to downgrade to 11.1.0, any solution that I can take to fix this?
The website will always be 404 for my customers

**Comment by balazsorban44** [comment]
Looks like you forgot to add `revalidate` in the branch where you define `notFound: true`. Unless defined, you will stuck on the not found page for all subsequent requests.

**Comment by futantan** [comment]
ooooh! my bad! Thank you @balazsorban44 for help!
