### ISSUE TITLE
Middleware builds are using the package.json browser field

### ISSUE THREAD

**Issue by tatethurston** [vercel/next.js#35370]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

(not relevant)

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

Middleware webpack builds are using the "browser" field from package.json, which is surprising because middleware only run s in a server context.

With the following in your `package.json`:
```
  "browser": {
    "some-package": false,
  }
```  
`some-package` will not be defined in middleware handlers.
  

### Expected Behavior

The "browser" field from package.json is not used when building middleware code paths.

### To Reproduce

1. Add a package entry within the browser field in the project package.json, setting it's value to false
2. Import the package into middleware
3. Observe the package is undefined in the middleware runtime

**Comment by tatethurston** [comment]
Sandbox example: https://codesandbox.io/s/keen-cray-33iz09?file=/pages/_middleware.js

**Comment by balazsorban44** [comment]
This is expected, as Middleware uses the Edge Runtime (which builds on the same web standard APIs as browsers), not Node.js. https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis.

**Comment by balazsorban44** [comment]
Update, this behavior might change in the next `canary` release when this is published: https://github.com/vercel/next.js/pull/35335

**Comment by tatethurston** [comment]
@balazsorban44 The linked article cites middleware runtime constraints, but nothing about how dependencies are built. As a user this overloading of the browser field is surprising -- I would not expect to have the browser field applied to a build that is not executed on the client's browser. User's may want to consume a different library entry point or ensure it doesn't end up in client builds irrespective of any runtime constraints.
