### ISSUE TITLE
Custom document's head throws error with multiple children

### ISSUE THREAD

**Issue by faradaytrs** [vercel/next.js#35390]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
    Binaries:
      Node: 17.7.1
      npm: 8.5.4
      Yarn: 1.22.17
      pnpm: 6.32.3
    Relevant packages:
      next: 12.1.1-canary.13
      react: 18.0.0-rc.2-next-b9de50d2f-20220308
      react-dom: 18.0.0-rc.2-next-b9de50d2f-20220308

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

My custom document is:
````jsx
import {Html, Head, Main, NextScript} from "next/document";
import {language} from "env";

export default function Document() {
    return (
        <Html lang={language}>
            <Head>
                <link rel="icon" href="/favicon.svg" />
                <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
                <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
                <meta name="msapplication-TileColor" content="#da532c" />
                <meta name="theme-color" content="#ffffff" />
                <link rel="stylesheet" href="https://use.typekit.net/ppu5vfx.css" />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
````

When i try to build it it throws:
````bash
Failed to compile.
--
14:21:09.647 |  
14:21:09.648 | ./src/pages/_document.tsx:36:18
14:21:09.649 | Type error: This JSX tag's 'children' prop expects a single child of type '((ReactElement<any, string \| JSXElementConstructor<any>> & (boolean \| ReactChild \| ReactFragment \| ReactPortal \| null)) & (boolean \| ... 3 more ... \| null)) \| undefined', but multiple children were provided.
14:21:09.649 |  
14:21:09.649 | 34 \|         return (
14:21:09.649 | 35 \|             <Html lang={language}>
14:21:09.649 | > 36 \|                 <Head>
14:21:09.650 | \|                  ^
14:21:09.650 | 37 \|                     <link rel="icon" href="/favicon.svg" />
14:21:09.652 | 38 \|                     <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
14:21:09.652 | 39 \|                     <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
14:21:09.703 | error Command failed with exit code 1.
14:21:09.703 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
14:21:09.717 | Error: Command "yarn run build" exited with 1
````

### Expected Behavior

Compile without problems

### To Reproduce

Install latest canary (13), insert few tags inside of Head in document, see compile error.

**Comment by awareness481** [comment]
Can confirm the above error using the `_document.tsx` as written in the issue. I also tried `12.1.1-canary.10` but the issue didn't exist there

**Comment by huozhi** [comment]
Hi, which typescript version are you using?

**Comment by Coder2195Text** [comment]
Me too I have the same issue
![image](https://user-images.githubusercontent.com/63069499/158861377-a42ba955-4110-48b8-8896-3fb1aa882e3f.png)
