### ISSUE TITLE
Wildcard rewrites (/x/:path*) are causing page reloads 

### ISSUE THREAD

**Issue by kyle-ssg** [vercel/next.js#35402]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.13
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

Given the rewrite 

```
 rewrites: async ()=>{
    return {
      beforeFiles: [
          { source: '/nfl/:path*', destination: '/_sport/nfl/:path*' },
      ]
    }
  }
```

Clicking the following link triggers a refresh

```
<Link href="/nfl">Link</Link>
<Link href="/nfl/test">Link</Link>
```

However, If I add the following to the rewrites it doesn't

```
  rewrites: async ()=>{
    return {
      beforeFiles: [
          { source: '/nfl', destination: '/_sport/nfl' },
          { source: '/nfl/test', destination: '/_sport/nfl/test' },
      ]
    }
  }
```

### Expected Behavior

I'd expect next to be able to pick up the relevant paths, I'm in a situation where I can't control the hrefs and need rewriting to happen without refreshes.

### To Reproduce

https://github.com/kyle-ssg/nextjs-rewrite-issue

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.6-canary.5` of Next.js, please update and give it a try!
