### ISSUE TITLE
NextJS dev-mode server-side NOT recompiling and thus HMR not working in Docker

### ISSUE THREAD

**Issue by latchy** [vercel/next.js#35411]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro N
    Binaries:
      Node: 17.7.1
      npm: 8.5.3
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

Docker version 20.10.13, build a224086

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

Initiating a NextJS server in dev mode in a custom ExpressJS server in Docker

### Describe the Bug

The app uses TypeScript and a custom ExpressJS server from which NextJS is initiated.

When running the server locally (no Docker) the NextJS HMR works as expected, but when inside a Docker container with the volume mapped it does not pick up the file changes.

I have confirmed that my local changes are picked up by Docker (inspecting the container after file save) via the volume mounting but the NextJS framework does not recompile the pages as expected.

Interestingly when using ts-node-dev to run launch the app, I have also had to add the `--poll` flag for the server to restart when src/server files are changes. 

### Expected Behavior

Expect to see (in the server console) the page get recompiled when saving changes locally, when the app is running inside a Docker container with the src folder volume mapped accordingly.

### To Reproduce

Clone this [nextjs-docker-hmr](https://github.com/latchy/nextjs-docker-hmr) repo and check the README for more info.  

**NB. This functionality seems to work with NextJS v9.5.3**  - this can be seen on a branch of the above repo.

**Comment by yulrosy** [comment]
i met the same issue too, how to fix?

**Comment by latchy** [comment]
So I solved this issue by adding this webpack modification to the next.config.js in the pages directory.

```
const next_config = {
 webpack: function (config, context) {
        config.watchOptions = {
            poll: 1000,
            aggregateTimeout: 300,
        };
        return config;
    },
};
```
