### ISSUE TITLE
Redirect issues with i18n enabled and dashed path which include possible locale name

### ISSUE THREAD

**Issue by SZharkov** [vercel/next.js#35427]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

When adding a redirect with source `/about-us` and destination `/` (or any other) it redirects to `/undefined`.
This happens when i18n is enabled.

Note, that `/about-me` would work ok. The issue is occurred because `us` string after dash in `/about-us`.

### Expected Behavior

Redirects with dashed source and words that look like a locale need to redirect to proper target.

### To Reproduce

`next.config.js`

```
module.exports = async () => {
  return {
     i18n: {
      locales: [ 'en-ca', 'fr-ca' ],
      defaultLocale: 'en-ca',
    },
    async redirects() {
      return [{
        source: '/about-us',
        destination: '/',
        permanent: true,
        locale: false
      }]
    }
  }
}
```

Then `yarn dev` and try to open `/about-us` page. It redirects to `/undefined`

**Comment by balazsorban44** [comment]
I could not reproduce this on `canary`, you can either upgrade or wait for the fix to get to `latest`
