### ISSUE TITLE
Docs: Explain why next.lock should not be Git-ignored

### ISSUE THREAD

**Issue by TomasHubelbauer** [vercel/next.js#35454]
### What is the improvement or update you wish to see?

I would like this section of the URL Imports page to be updated:
https://nextjs.org/docs/api-reference/next.config.js/url-imports#lockfile

### Is there any context that might help us understand?

The page says next.lock should not be Git-ignored, but does not go into details on why that is. I _think_ the only downside of not versioning this file is that the cache will be rebuilt on each new clone, potentially with different versions than the ones used for the last commit?

So in effect, not versioning this lock file and directory will make it so regardless of the configured caching, Next will pull the latest version of those files at the given URLs on the next clone?

I was able to test that just deleting this repository and refreshing the development mode page rebuilt it, no problem.

I intentionally want to get the latest versions of these files on each new clone, does that mean that Git-ignoring the lock directory will achieve that for me?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next.config.js/url-imports#lockfile

<sub>[DX-1663](https://linear.app/vercel/issue/DX-1663/docs-explain-why-nextlock-should-not-be-git-ignored)</sub>

**Comment by TomasHubelbauer** [comment]
Ah okay, so not committing the lock file causes `next build` to fail. Locally and in Vercel deployment. I would like to learn whether there are ways to make `next build` run with an unfrozen lock file instead of committing the lock file. Thank you

**Comment by samcx** [comment]
@TomasHubelbauer You can do this on hosting providers such as Vercel by overriding the **Install Command** like this: `pnpm i --frozen-lockfile`.
