### ISSUE TITLE
Getting 500 on profile-ssr in with-iron-session 

### ISSUE THREAD

**Issue by akhil-gautam** [vercel/next.js#35463]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

N/A

### Which example does this report relate to?

with-iron-session

### What browser are you using? (if relevant)

Chrome 99.0.4844.51

### Describe the Bug

When accessing https://iron-session-example.vercel.app/profile-ssr after login (GitHub username), I am getting 500 error in the deployed example.

<img width="990" alt="Screenshot 2022-03-20 at 12 06 20 PM" src="https://user-images.githubusercontent.com/28865023/159151272-5b32f17c-6f00-43dd-a952-ce7e5f1503c7.png">

### Expected Behavior

It should show a page but not 500.

### To Reproduce

1. Go to https://iron-session-example.vercel.app
2. Login using your GitHub username
3. Click on `profile ssr` on the navbar.

**Comment by therealmarzouq** [comment]
Hello @akhil-gautam, This issue seems to have been resolved
