### ISSUE TITLE
Content-length header missing from NextJS optimized images

### ISSUE THREAD

**Issue by jorgev259** [vercel/next.js#35514]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.1
      npm: 8.3.0
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

98.0.1

### Describe the Bug

Image served through cdn domain has a content-length image that doesnt get passed after its optimized by next/image.

Example: https://sittingonclouds.net/cdn/album/2199.png https://www.sittingonclouds.net/_next/image?url=https%3A%2F%2Fcdn.sittingonclouds.net%2Falbum%2F2199.png&w=1920&q=75

### Expected Behavior

Content-length header on next/image images.

### To Reproduce

Included examples on bug description

**Comment by kobayashi90** [comment]
Hoping that somebody actually looks into this since the person above me isnt the only one suffering..

**Comment by kobayashi90** [comment]
@styfle i think you fixed the wrong end, see more details below:
Example Headers from an Image:

`test`

> HTTP/2 200 OK
server: ddos-guard
strict-transport-security: max-age=31536000
content-security-policy: upgrade-insecure-requests;
date: Sat, 30 Apr 2022 13:54:30 GMT
content-type: image/webp
vary: Accept
etag: KPOAagaLSb-qlZJCeVUNqa8bYcaTdwvH-17CRwiE19Q=
content-disposition: inline; filename="2521.webp"
content-security-policy: script-src 'none'; frame-src 'none'; sandbox;
x-nextjs-cache: HIT
cache-control: public, max-age=31536000
age: 0
ddg-cache-status: MISS

**Comment by kobayashi90** [comment]
> @kobayashi90 You can try out the fix on the [canary](https://github.com/vercel/next.js/releases/tag/v12.1.6-canary.16) channel using `npm install next@canary`

I did but still no content-length header on the compressed image link (first output above)

**Comment by styfle** [comment]
@kobayashi90 You'll need to update Next.js because your tests were done before canary was released.

Now that stable is released, you can run `npm install next@latest` to get the latest stable version with the fix.
