### ISSUE TITLE
Getting `window is not defined` with `hellosign-embedded` using `next build`

### ISSUE THREAD

**Issue by LuisEnMarroquin** [vercel/next.js#35559]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

$ npx next info
'pnpm' is not recognized as an internal or external command,
operable program or batch file.

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.17
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 99.0.4844.82 (64 bits) (not relevant)

### How are you deploying your application? (if relevant)

next build && next export (not relevant)

### Describe the Bug

I am trying to use `hellosign-embedded` with a TypeScript project, been trying 2 different things

1. As explained in this issue: https://github.com/vercel/next.js/issues/34653#issuecomment-1047582024

Tried with `const HelloSign = dynamic(() => import("hellosign-embedded"), { ssr: false })` but it gives me an error

![image](https://user-images.githubusercontent.com/35376824/159815850-8032f04b-f9f6-47ee-9ffd-cd5b103f9009.png)

2. Also as explained in this other issue: https://github.com/vercel/next.js/issues/34330#issuecomment-1040426608

Tried to wrap `new HelloSign` in a ternary checking for `window` to exist but I think the problem is the top level `import HelloSign from "hellosign-embedded"`

```tsx
  const client =
    typeof window !== "undefined"
      ? new HelloSign({
          allowCancel: false,
          clientId: "CLIENT ID HERE", // DEV HelloSign Client ID
          skipDomainVerification: true,
        })
      : null
```

But when building I am getting this error

```shell
$ npx next build
info  - Checking validity of types...
warn  - No ESLint configuration detected. Run next lint to begin setup
info  - Creating an optimized production build...
info  - Compiled successfully
info  - Collecting page data...

> Build error occurred
ReferenceError: window is not defined
    at C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:6234:2
    at C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:6223:46
    at ./node_modules/style-loader/lib/addStyles.js.module.exports (C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:6291:88)
    at Object../src/sass/embedded.scss (C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:9156:137)
    at __webpack_require__ (C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:30:30)
    at Object.0 (C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:9367:1)
    at __webpack_require__ (C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:30:30)
    at C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:94:18
    at C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:97:10
    at webpackUniversalModuleDefinition (C:\Users\arkus\3D Objects\pouch-instanda-hellosign\node_modules\hellosign-embedded\umd\embedded.development.js:3:20) {
  type: 'ReferenceError'
}
```

### Expected Behavior

I expect the app to build, probably I am missing dynamically importing `hellosign-embedded` but I am not sure how can I do it

### To Reproduce

```tsx
import axios from "axios"
import HelloSign from "hellosign-embedded"

export default function Home() {
  const client =
    typeof window !== "undefined"
      ? new HelloSign({
          allowCancel: false,
          clientId: "CLIENT ID HERE", // DEV HelloSign Client ID
          skipDomainVerification: true,
        })
      : null

  if (client !== null) {
    client.on("finish", () => {
      console.log("Congratulations! You have signed the document with HelloSign")
    })
  }

  const helloSignFunction = () => {
    axios
      .post(`https://example.com/helloSignDocs`)
      .then((res) => {
        if (client !== null) {
          client.open(res.data.reply.signUrl)
        }
      })
      .catch((err) => {
        console.log({ err })
      })
  }

  return (
    <button onClick={helloSignFunction }>
      Click me
    </button>
  )
}
```

**Comment by LuisEnMarroquin** [comment]
Update: Also tried setting `types` to `any` to avoid editor errors, but still doesn't work

```tsx
const HelloSign: any = dynamic(
  (): any => {
    return import("hellosign-embedded")
  },
  { ssr: false }
)

export default function Home() {

  const client =
    typeof window !== "undefined"
      ? new HelloSign({
          allowCancel: false,
          clientId: "HELLO SIGN CLIENT ID", // DEV HelloSign Client ID
          skipDomainVerification: true,
        })
      : null

  return null
}
``` 

![image](https://user-images.githubusercontent.com/35376824/159821028-86e76e82-8e3b-4609-8369-e09ed9c49732.png)

**Comment by timneutkens** [comment]
It seems that you're confusing React components with javascript libraries as you're importing the hellosign-embedded library while it's not a React component and are then trying to initialize it using `new`. Given that it's not a React component you have to load it in the onClick handler (or eagerly):

```js
export default function Home() {
  const openDocument = () => {
    import("hellosign-embedded").then(({default: HelloSign}) => {
        return new HelloSign({
            allowCancel: false,
            clientId: "HELLO SIGN CLIENT ID", // DEV HelloSign Client ID
            skipDomainVerification: true,
        })
    }).then(client => {
        client.open('URL')
    })
  }

  return <button onClick={openDocument}></button>
}
```
