### ISSUE TITLE
Next (canary) does not support the upcoming TypeScript 4.7 NodeNext/Node12 moduleResolution

### ISSUE THREAD

**Issue by jasonwilliams** [vercel/next.js#35572]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Mon Nov 8 10:21:19 UTC 2021
    Binaries:
      Node: 17.6.0
      npm: 8.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.1-canary.17
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

TypeScript have [added support](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1043271180) for package exports in the upcoming 1.4.7 release. This has included releasing a new module option called [node12](https://github.com/microsoft/TypeScript/issues/46452). However in order to use this feature (and upcoming ESM features) `moduleResolution` needs to be set to `NodeNext` or `Node12`. 

This is not possible to do in a next project, because Next changes it back to `node` at build time. Meaning users of Next are not able to use TypeScript's upcoming features.

NextJS Output:
```
We detected TypeScript in your project and reconfigured your tsconfig.json file for you. Strict-mode is set to false by default.

The following mandatory changes were made to your tsconfig.json:

        - moduleResolution was set to node (to match webpack resolution)
```

### Expected Behavior

Node12 and NodeNext to be supported in Next so I can make use of [package exports](https://nodejs.org/api/packages.html#exports) in my other dependencies. 

### To Reproduce

- Add `"typescript": "4.7.0-dev.20220322"` to your package.json assuming you're already using typescript.
- Set `moduleResolution` to `Node12` or `NodeNext`

**Comment by DovydasNavickas** [comment]
The title is a bit misleading because it's `4.7.0-dev.20220322` so it should be `TypeScript 4.7.0 NodeNext/Node12 moduleResolution`.
But it seems that even though here:
https://nextjs.org/blog/next-11-1

>We're working on extensive [ES Modules](https://nodejs.org/docs/latest/api/esm.html) support in Next.js, both as input modules *and as an output target*.

The output doesn't seem to be supported, because with TypeScript 4.7.0 `moduleResolution` should be set to `Node12` and next reverts it. Any info on that would help a lot.

**Comment by jasonwilliams** [comment]
> The title is a bit misleading because it's `4.7.0-dev.20220322` so it should be `TypeScript 4.7.0 NodeNext/Node12 moduleResolution`.

The title does mention that it’s “upcoming” so I don’t think it’s misleading. A quick search would show it’s not out yet but due to be released soon. Those builds change daily so I don’t think it’s useful to have it in the title.

**Comment by jasonwilliams** [comment]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/ has now been announced, which means it will soon come out with Next not supporting it. @timneutkens
