### ISSUE TITLE
Jest throws exception on PropTypes when using class components

### ISSUE THREAD

**Issue by rmsheppard** [vercel/next.js#35585]
### Verify canary release

- [ ] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
    Binaries:
      Node: 12.22.4
      npm: 6.14.6
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2

### Describe the Bug

Downloaded the with-jest example and added the following class:

![image](https://user-images.githubusercontent.com/23467956/160012785-dd2949fa-6577-4dfa-bef7-03846d9ef8a0.png)

Then added a jest test:

![image](https://user-images.githubusercontent.com/23467956/160012874-09293b18-64a8-4d44-92bc-4206ae6aef5e.png)

![image](https://user-images.githubusercontent.com/23467956/160012388-1ac8c886-2dad-4f6e-ad20-05f90a4c4a3d.png)

### Expected Behavior

PropTypes should be loaded when using class components.

### To Reproduce

download with-jest and include the code pasted above in "Describe the Bug"

**Comment by irvile** [comment]
Hii! can you share your jest version? In the picture you use a global jest package.

can you try one of theses commands? 

```bash
yarn test 
# or 
npm test
```
I try reproduce your issue but I cant because theses commands above works. So, I think, we need know your global jest version.

**Comment by rmsheppard** [comment]
Hi Irvile, thanks for getting back with me.  The jest version is what is included in the with-jest example project.  Those are also the commands I ran to get those exceptions.

I don't think I have jest installed globally but I'll check that out when I get back to work.  I can tell you my coworkers were having the exact same issue as we both were removing our decorators trying to clean  up our codebase so that we could make use of the rust compiler and the speed benefits thereof.

Keep in mind this only shows up when you use static propTypes or so it seems but I would think that should be handled as many projects use class components from before functional components and used the static properties.  In terms of Next everything renders and runs just fine.  Just test won't work. I then downloaded the with-jest example and replicated the issue with the above code in the image.  I haven't had the opportunity to try the new version that just came out yesterday but this was found in the 12.1.0 version.

**Comment by irvile** [comment]
Hello! It's okay =D, I think in global jest because was one possibility.  Lets try reproduce your issue! 

I created this sandbox as a Fork of [with-jest](https://github.com/vercel/next.js/tree/canary/examples/with-jest) as you mentioned in the section "To Reproduce": 
https://codesandbox.io/s/next-js-issue-35585-n0lig6?file=/pages/index.tsx 

Could you see what I miss to reproduce your issue?

![Screen Shot 2022-03-26 at 08 51 02](https://user-images.githubusercontent.com/1596614/160238808-22cf97e6-37e7-4f95-8aef-babf27f9e805.png)

**Comment by rmsheppard** [comment]
I believe the issue was actually resolved with the 12.1.1 release.  that might be the difference.  We were on version 12.0.7 and I tried 12.1.0 and it existed but the propTypes being defined this way seem to work.  We do have another issue where we have a propType saved in another file that we import and passing that to the propTypes seems to throw an exception

![image](https://user-images.githubusercontent.com/23467956/160444535-94390c45-dacb-4231-96d6-75483ead6097.png)
