### ISSUE TITLE
create-next-app not working

### ISSUE THREAD

**Issue by hateVtubers** [vercel/next.js#35599]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

node and npm version
![image](https://user-images.githubusercontent.com/83547807/160184976-f82fc108-e16d-4081-8f84-19232ebdd869.png)
 
operating system windows 10

### Describe the Bug

I try creating a next project with npx but in windows console this error:
"'yarn' is not recognized as an internal or external command, operable program or batch file."

### Expected Behavior

I'll intent build a nextjs project

### with @latest
- ![image](https://user-images.githubusercontent.com/83547807/160184126-2b8d55d4-dc61-46e7-8d23-43573e477477.png)

### without @latest
- ![image](https://user-images.githubusercontent.com/83547807/160184570-9d57e897-d366-482a-82c8-cce3fccf06ff.png)

**Comment by antonbobrov** [comment]
I've struggled the same issue.
This would help:
npx create-next-app@latest --ts --use-npm

**Comment by hateVtubers** [comment]
> I've struggled the same issue. This would help: npx create-next-app@latest --ts --use-npm 

thanks I love you

**Comment by hateVtubers** [comment]
npx create-next-app@latest --ts --use-npm

**Comment by ijjk** [comment]
Hi, this has been fixed in the latest version of Next.js `v12.1.2` please give it a try! Note: this may require running with `@latest` e.g. `npx create-next-app@latest`.
