### ISSUE TITLE
Next.js - 12.1.1 -> not allowing npx create-next-app

### ISSUE THREAD

**Issue by dhavalveera** [vercel/next.js#35607]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

'next' is not recognized as an internal or external command,
operable program or batch file.

### Describe the Bug

after updating the `create-next-app` by `npm install -g create-next-app` after that when I am running the below command to start a Nextjs App, I am getting below error.

```
C:\Users\Dhaval Vira\Desktop\Coursera Learning\Next_Prisma>npx create-next-app demotwo
Creating a new Next.js app in C:\Users\Dhaval Vira\Desktop\Coursera Learning\Next_Prisma\demotwo.

Using yarn.

Installing dependencies:
- react
- react-dom
- next

'yarn' is not recognized as an internal or external command,
operable program or batch file.
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at notFoundError (C:\Users\Dhaval Vira\AppData\Roaming\npm\node_modules\create-next-app\dist\index.js:100:3828)
    at verifyENOENT (C:\Users\Dhaval Vira\AppData\Roaming\npm\node_modules\create-next-app\dist\index.js:100:4207)
    at ChildProcess.e.emit (C:\Users\Dhaval Vira\AppData\Roaming\npm\node_modules\create-next-app\dist\index.js:100:4062)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.e.emit (C:\Users\Dhaval Vira\AppData\Roaming\npm\node_modules\create-next-app\dist\index.js:100:4103)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [
    'add',
    '--exact',
    '--cwd',
    'C:\\Users\\Dhaval Vira\\Desktop\\Coursera Learning\\Next_Prisma\\demotwo',
    'react',
    'react-dom',
    'next'
  ]
}
```

### Expected Behavior

after updating `create-next-app` to 12.1.1, `npx create-next-app appname` is not creating the Next app

### To Reproduce

I tried `npx create-next-app@latest appname` but it's throwing the same error.

even I tried to uninstall the `create-next-app` & reinstalled it but it's throwing the same error.

and I install `yarn` globally then `npx create-next-app appname` run command properly without any error

**Comment by git-no** [comment]
I have the same issue. Can not run `npx create-next-app@latest`without error/break.
Node 16.14.2, no yarn installed.

**Comment by dhavalveera** [comment]
when this update will be released @ijjk?

**Comment by nahuelDev23** [comment]
same error, ideas?

**Comment by JorneSaenen** [comment]
> same error, ideas?

"npx create-next-app@latest --use-npm"

**Comment by nyuuke** [comment]
> "npx create-next-app@latest --use-npm"

this does not help at least for my case it just stuck installing without any progress for about 20+ minutes

**Comment by ijjk** [comment]
Hi, this has been fixed in the latest version of Next.js `v12.1.2` please give it a try! Note: this may require running with `@latest` e.g. `npx create-next-app@latest`. Specific PR this was fixed in can be seen here https://github.com/vercel/next.js/pull/35608

**Comment by dhavalveera** [comment]
@ijjk -> Thank you, sir, the problem is solved!!!! and I tried with `npx create-next-app appname` it's working perfectly fine.


Thanks a lot!
