### ISSUE TITLE
Failed to load SWC binary for win32/x64

### ISSUE THREAD

**Issue by SebastianSava** [vercel/next.js#35614]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

After "Automatic Setup" installation, when i try to run npm run dev i received this message:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Attempted to load @next/swc-win32-x64-gnu, but it was not installed
info  - Attempted to load @next/swc-win32-x64-msvc, but an error occurred: The specified module could not be found.     
\\?\C:\Users\Acer\Desktop\GitHub\personal_website\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node    
error - Failed to load SWC binary for win32/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
The terminal process "C:\Windows\System32\cmd.exe /d /c npm run dev" terminated with exit code: 1.
```

### Expected Behavior

Just working

### To Reproduce

```
npx create-next-app@latest
# or
yarn create next-app
```

```
npm run dev
```

**Comment by Babailan** [comment]
make a .babelrc and put this

**Comment by SebastianSava** [comment]
> make a .babelrc and put this
> 
> ```
> {
>   "presets": ["next/babel"]
> }
> ```
> 
> [Reference](https://nextjs.org/docs/messages/failed-loading-swc)

Thanks, But i think this issue should be solved, because it’s also on the starting template.

**Comment by Brooooooklyn** [comment]
Check out here https://github.com/vercel/next.js/discussions/31073#discussioncomment-2166074

**Comment by balazsorban44** [comment]
Assuming @Brooooooklyn's suggestion helps. If not, please report back and we can re-open this issue. :+1:
