### ISSUE TITLE
`npx create-next-app@latest` not working

### ISSUE THREAD

**Issue by HarrisonHemstreet** [vercel/next.js#35623]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

*I did not check next@canary because I don't think believe that create-next-app would carry over*
Because I'm not even able to make a project with create-next-app, here's what's happening:
When I run the `npx create-next-app@latest` command in the terminal, I get this error:
```bash
~ on ☁️   
❯ npx create-next-app
Need to install the following packages:
  create-next-app
Ok to proceed? (y) y
✔ What is your project named? … test2
Creating a new Next.js app in /home/harry/test2.

Using yarn.

Installing dependencies:
- react
- react-dom
- next

node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [
    'add',
    '--exact',
    '--cwd',
    '/home/harry/test2',
    'react',
    'react-dom',
    'next'
  ]
}


```

### Describe the Bug

create-next-app is not working. The command only produces a directory and a package.json file. That's it.

### Expected Behavior

I want create-next-app to build me a next.js project

### To Reproduce

run `create-next-app@latest` in your terminal

**Comment by TaylorFlynn** [comment]
I am experiencing the same issue, 

I have never installed yarn yet it still is trying to install next template project via yarn instead of npm.

**Comment by yeskunall** [comment]
Looks like this will be fixed in #35608. It hasn’t been made part of an official release yet, only merged into `canary`. I was able to bypass the error using the `--use-npm` flag.

TIL: Next.js now uses Yarn by default: https://github.com/vercel/next.js/pull/34947#discussion_r820032044

**Comment by abLyn** [comment]
I am experiencing the same issue,
I have never installed yarn yet it still is trying to install next template project via yarn instead of npm.

Untitled Folder npx create-next-app@latest --ts fronten 
Creating a new Next.js app in /home/chaffa/Desktop/Untitled Folder/fronten.

Using yarn.

Installing dependencies:
- react
- react-dom
- next

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [
    'add',
    '--exact',
    '--cwd',
    '/home/chaffa/Desktop/Untitled Folder/fronten',
    'react',
    'react-dom',
    'next'
  ]
}

Node.js v17.8.0

**Comment by marko-knoebl** [comment]
Looks like this was introduced in the latest _patch_ version release:

this will succeed:

```bash
npx create-next-app@12.1.0
```

this will fail:

```bash
npx create-next-app@12.1.1
```

**Comment by eg-delacruz** [comment]
I tried installing the previous version, as marko-knoebl suggested, but still got the issue.

I solved it by previously installing yarn: npm install --global yarn

Afterwards, you should be able to install version 12.1.1 with all the files needed.

**Comment by tombohub** [comment]
@yeskunall why are they doing that? If we use `npx` then it's obviously npm, not yarn. I dont understand

**Comment by khudaverdiev11** [comment]
use npx create-next-app nextapp --use-npm 
it will work

**Comment by rcabre95** [comment]
> use npx create-next-app nextapp --use-npm it will work

thank you for this @khudaverdiev11 . worked like a charm. also works with the --typescript flag

**Comment by balazsorban44** [comment]
https://github.com/vercel/next.js/issues/35623#issuecomment-1079821404 is correct, indeed https://github.com/vercel/next.js/pull/35608 fixes this. You can try it out on `canary` right now, we are going to release it to `latest` :soon: Closing as this should already be fixed. :+1:

**Comment by ijjk** [comment]
Hi, this has been fixed in the latest version of Next.js `v12.1.2` please give it a try! Note: this may require running with `@latest` e.g. `npx create-next-app@latest`.
