### ISSUE TITLE
Module not found: Can't resolve '@builder.io/partytown/integration'

### ISSUE THREAD

**Issue by jlarmstrongiv** [vercel/next.js#35630]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64
    Binaries:
      Node: 14.18.1
      npm: 8.1.0
      Yarn: 1.22.10
      pnpm: 6.32.2
    Relevant packages:
      next: 12.1.2-canary.0
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

Vercel, next build

### Describe the Bug

```
warn  - Compiled with warnings

./node_modules/next/dist/pages/_document.js
Module not found: Can't resolve '@builder.io/partytown/integration' in '…'

Import trace for requested module:
./node_modules/next/document.js
./src/pages/_app.tsx
```

To [ignore](https://webpack.js.org/configuration/other-options/#ignorewarnings) the warnings, use a [custom](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) webpack config:
```js
      config.ignoreWarnings = [
        {
          module: /\.\/node_modules\/next\/dist\/pages\/_document\.js/, 
        },
      ];
```

### Expected Behavior

No warnings.  It worked in the last next version `12.1.0`.  

See recent merge of https://github.com/vercel/next.js/pull/34244

I like that PR.  I would love to see a fix, rather than a rollback.

@housseindjirdeh and @ijjk

### To Reproduce

Use a custom `_app` and `_document` and try building with webpack.

Probably not relevant, but I am using a monorepo and custom webpack config.

**Comment by jlarmstrongiv** [comment]
Related https://github.com/vercel/next.js/issues/35645

**Comment by balazsorban44** [comment]
Are you using the recently introduced Script with an experimental worker strategy?

Have you tried `canary` yet?

In any case, would you mind attaching a reproduction/your code? :pray:

**Comment by jlarmstrongiv** [comment]
@balazsorban44 

> Are you using the recently introduced Script with an experimental worker strategy?

No, I was just updating my dependencies.

> Have you tried canary yet?

Yes, I did try `12.1.2-canary.0`

> In any case, would you mind attaching a reproduction/your code? 

If Vercel has a place where I could email / upload my private repo, I would do that.

**Comment by ijjk** [comment]
@jlarmstrongiv if the repo is on GitHub and are able to invite myself `@ijjk` then that would be great, otherwise if you would prefer to share details more privately you can submit a ticket here https://vercel.com/support/request and reference this issue/message

**Comment by jlarmstrongiv** [comment]
@ijjk I invited you to the repo 👍 

1. run `npm install` in the root
2. `cd apps/nextjs/example`
3. Disable hiding the warnings in `configs/next/src/index.ts`
4. `npm run turbo:build` or `npm run turbo:dev`

**Comment by ijjk** [comment]
@jlarmstrongiv it seems that project has unrelated errors and is trying to build with a custom `bin/nextjs/build` script that doesn't exist. Also an additional repo is attempting to be cloned during `postinstall`

**Comment by jlarmstrongiv** [comment]
@ijjk my sincerest apologies!  I had gone through the steps from scratch a few days ago, but hadn’t check on the latest version of the repo.  Please pull the latest code and try again.

---

You can safely ignore the additional repo cloning during postinstall—it is for monkey patching while I contribute to an upstream repo.

The script was accidentally gitignore’d. 

I have run through and confirmed all the steps on a secondary machine 🤞

**Comment by jlarmstrongiv** [comment]
You may need to install via `npm install --force` because [`@headlessui/react`](https://www.npmjs.com/package/@headlessui/react) isn’t playing well in peerDependencies, due to the `react` v18 release yesterday.

**Comment by ijjk** [comment]
Hi, this issue appears to be that `next/document` is being imported in your `_app` file specifically the `export { App as default } from "@reactjs/next"` which is used client side and shows the missing module warning while if it's used only server-side like it's meant to be the warning won't show.

**Comment by jlarmstrongiv** [comment]
@ijjk I’m not sure I understand.  

The `export { App as default } from "@reactjs/next"` refers to:

```
// docs https://nextjs.org/docs/basic-features/typescript#custom-app
import type { AppProps } from "next/app";

export function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}
```

So I am unsure where, why, or how `next/document` would be imported in the `_app` file.

**Comment by ijjk** [comment]
Since you are using a stub file that exports both like below, it causes the `Document` import to be processed as well when importing the `App` export in `_app`

```js
export { App } from "./App";
export { Document } from "./Document";
```

**Comment by jlarmstrongiv** [comment]
Thank you @ijjk 👍 I really appreciate your help and patience

**Comment by tw1t611** [comment]
I came across the same issue on `canary` without a stub file:

![image](https://user-images.githubusercontent.com/13353525/161030656-3a57e31f-c740-4356-a47e-66644c958185.png)

The error occurs on vercel, but does not occur on local `yarn build`

**Comment by ijjk** [comment]
@tw1t611 do you have the `experimental.nextScriptWorkers` enabled in your `next.config.js`? If not you shouldn't have to install `@builder.io/partytown` and if this is the case would love an invite to investigate this!

**Comment by housseindjirdeh** [comment]
+1 to what @ijjk said. You shouldn't have to install `@builder.io/partytown` unless you need to use `experimental .nextScriptWorkers`.

Please invite both of us to your repo if that's okay :)

**Comment by ajnart** [comment]
Currently having the same issue after upgrading packages, including Next. Reverting the upgrade fixed it thankfully

**Comment by ijjk** [comment]
@ajnart were you encountering the above error on the latest canary, `v12.1.5-canary.4`?

**Comment by ajnart** [comment]
> @ajnart were you encountering the above error on the latest canary of Next.js, `v12.1.5-canary.4`?

No, the version I had was ``12.1.0``. I upgraded all my packages instead of only a few ones, and it created this error.   

<details>
<summary>My package.json dependencies when I had the issue </summary> 

 
``` json

 "dependencies": {
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@mantine/core": "^4.1.2",
    "@mantine/dates": "^4.1.2",
    "@mantine/dropzone": "^4.1.2",
    "@mantine/form": "^4.1.2",
    "@mantine/hooks": "^4.1.2",
    "@mantine/modals": "^4.1.2",
    "@mantine/next": "^4.1.2",
    "@mantine/notifications": "^4.1.2",
    "@mantine/prism": "^4.1.2",
    "@mantine/rte": "^4.1.2",
    "@mantine/spotlight": "^4.1.2",
    "axios": "^0.26.1",
    "cookies-next": "^2.0.4",
    "dayjs": "^1.11.0",
    "framer-motion": "^6",
    "next": "12.1.0",
    "prism-react-renderer": "^1.3.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-icons": "^4.3.1",
    "react-markdown": "^8.0.2",
    "swiper": "^8.1.0",
    "tabler-icons-react": "^1.44.0"
  },
  "devDependencies": {
    "@next/bundle-analyzer": "^12.1.4",
    "@next/eslint-plugin-next": "^12.1.4",
    "@types/node": "^17.0.23",
    "@types/react": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.18.0",
    "@typescript-eslint/parser": "^5.18.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.13.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-config-mantine": "^1.1.0",
    "eslint-config-next": "^12.1.4",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.4.0",
    "prettier": "^2.6.2",
    "typescript": "^4.6.3"
  }

```
</details>

**Comment by ijjk** [comment]
Can you confirm you are no longer having the issue in the latest canary? It should be fully resolved now.

**Comment by ajnart** [comment]
> Can you confirm you are no longer having the issue in the latest canary? It should be fully resolved now.

Yup! I just tested and it works now 🥳
