### ISSUE TITLE
i18n redirection through middleware causes multiple redirection during client side transitions

### ISSUE THREAD

**Issue by vinaynair39** [vercel/next.js#35648]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 16.13.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.1
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Other platform

### Describe the Bug

For advanced i18n needs, I'm currently using middleware so that only some sets of pages have i18n enabled. e.g while accessing let's say **/pt/xyz** redirects the user to **/xyz** since we don't have the Portuguese content for that particular page. 

The below piece of code works well when I directly enter the URL in the browser. But causes multiple redirections when I click a link on the page which causes a client-side transition to a different page
```
  if (!requested_page_is_i18n_enabled && locale !== 'en') {
      const url = nextUrl.clone();
      url.locale = 'en';
      return NextResponse.redirect(url);
    }
```

### Expected Behavior

Looks like the  `return NextResponse.redirect(url);` doesn't work properly when we click on a Link component

whatever changes I apply to nextUrl, it seems like it doesn't get applied but when I do a hard refresh, it works as expected

### To Reproduce

```
/* eslint-disable no-console */
import { NextResponse } from 'next/server';
import supportedLanguages from '../public/locales/supportedLanguages';

const PUBLIC_FILE = /\.(.*)$/;

const pathsWhereLocalesAreEnabled = [
  '/jobs',
  '/jobs/[id]',
  '/remote-developer-jobs',
];

export function middleware(req) {
  try {
    const { nextUrl, headers } = req;
    const { locale } = nextUrl;

    if (PUBLIC_FILE.test(nextUrl.pathname)) {
      return undefined;
    }

    if (nextUrl.pathname.includes('/api')) {
      return undefined;
    }

    const browserDefaultLocale =
      headers.get('accept-language')?.split(',')?.[0] || 'en';

    if (locale === 'en' && browserDefaultLocale === 'en') {
      return undefined;
    }

    const websiteLocale = supportedLanguages.includes(browserDefaultLocale)
      ? browserDefaultLocale
      : 'en';

    const requested_page_is_i18n_enabled = pathsWhereLocalesAreEnabled.includes(
      req.page.name,
    );

    console.log(nextUrl.toString());

    if (!requested_page_is_i18n_enabled && locale !== 'en') {
      const url = nextUrl.clone();
      url.locale = 'en';
      return NextResponse.redirect(url);
    }

    if (requested_page_is_i18n_enabled) {
      const { locale } = nextUrl;
      const url = nextUrl.clone();

      if (locale === websiteLocale && locale === 'en') return undefined;

      if (locale === 'en') {
        url.locale = websiteLocale;
        return NextResponse.redirect(url);
      }

      return undefined;
    }

    // If everything else falls through continue on with response as normal
    return undefined;
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error(e);
  }
}

```

This is the code I am using, I don't know how I can share how to reproduce this since I'm working on my company's website. Pls help :(

**Comment by erming** [comment]
Good writeup from @vinaynair39

I also got this problem. It causes the browser to get locked up in an infinite loop, sending loads of requests to the same URL over and over, effectively crashing the page.

For anyone that just need this to work _right now_, here's a solution I found:
```js
export async function middleware(req: NextRequest) {
  // ...
  // ...
  if (shouldRedirect) {
    if (req.method == "HEAD") {
      // Fixes the problem with redirects by forcing a native page load
      return NextResponse.error();
    }
    // Your redirect
    return NextResponse.redirect(urlToRedirectTo);
  }
}
```

**Comment by estephinson** [comment]
@erming I've seen that infinite navigation bug previously, suspected it was "HEAD" request related. Now chasing down a less damaging, but equally annoying issue whereby `push` is refusing to navigate with redirects in middleware, and I suspect it's the exact same reason as yours.

**Comment by vinaynair39** [comment]
> Good writeup from @vinaynair39
> 
> I also got this problem. It causes the browser to get locked up in an infinite loop, sending loads of requests to the same URL over and over, effectively crashing the page.
> 
> For anyone that just need this to work _right now_, here's a solution I found:
> 
> ```js
> export async function middleware(req: NextRequest) {
>   // ...
>   // ...
>   if (shouldRedirect) {
>     if (req.method == "HEAD") {
>       // Fixes the problem with redirects by forcing a native page load
>       return NextResponse.error();
>     }
>     // Your redirect
>     return NextResponse.redirect(urlToRedirectTo);
>   }
> }
> ```

@erming that worked for me, thank you so much!

**Comment by muhmushtaha** [comment]
> Good writeup from @vinaynair39
> 
> I also got this problem. It causes the browser to get locked up in an infinite loop, sending loads of requests to the same URL over and over, effectively crashing the page.
> 
> For anyone that just need this to work _right now_, here's a solution I found:
> 
> ```js
> export async function middleware(req: NextRequest) {
>   // ...
>   // ...
>   if (shouldRedirect) {
>     if (req.method == "HEAD") {
>       // Fixes the problem with redirects by forcing a native page load
>       return NextResponse.error();
>     }
>     // Your redirect
>     return NextResponse.redirect(urlToRedirectTo);
>   }
> }
> ```

That works fine locally on my machine but when I deployed the Next App on Vercel it gives me an error.

`Error: Failed to execute 'error' on 'Response': the method is not implemented.
    at server/pages/_middleware.js:1918:0
    at server/pages/_middleware.js:2237:0`

Is there any solution for this?

**Comment by vinaynair39** [comment]
Thanks, @javivelasco!
