### ISSUE TITLE
Can't `build next` after create-next-app in yarn workspace

### ISSUE THREAD

**Issue by gyeol1212** [vercel/next.js#35650]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.5
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.1.1
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

My nextjs app (that create using `create-next-app --template typescript` in my monorepo workspace) can't build with next error

```
./pages/_app.tsx:2:31
Type error: Cannot find module 'next/app' or its corresponding type declarations.

  1 | import '../styles/globals.css'
> 2 | import type { AppProps } from 'next/app'
    |                               ^
  3 | 
  4 | function MyApp({ Component, pageProps }: AppProps) {
  5 |   return <Component {...pageProps} />
info  - Checking validity of types .%    
```

For your information, 'next dev' works normally.
Also, if i create next app outside workspace, it works normally.

### Expected Behavior

complete build and create `dist` folder 

### To Reproduce

```
// root package.sjon
{
  ...
  "workspaces": [
    "packages/*"
  ],
  "ntl": {
    "runner": "yarn"
  },
   ...
}
```
```
// root .yarnrc.yml
packageExtensions:
  "@typescript-eslint/typescript-estree@*":
    peerDependencies:
      typescript: "*"


yarnPath: .yarn/releases/yarn-3.1.1.cjs
```

and `packages/next-app` generated by `yarn create next-app --template typescript`

**Comment by balazsorban44** [comment]
`--template typescript` is an unknown argument. You might want `--typescript` or `--ts` instead.

I am unable to reproduce otherwise.

In case you saw `--template typescript` in our docs, could you link to it so we can update it?

**Comment by gyeol1212** [comment]
@balazsorban44 Sorry, I mean `yarn create next-app --typescript`.
I was confused with `React`.

When I made it using `--typescript`, The above issues arise.
