### ISSUE TITLE
[v12.1.1] Multi-line comment at the start of return of the render function breaks app (Minified React error #152)

### ISSUE THREAD

**Issue by bennettdams** [vercel/next.js#35657]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.1.2-canary.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

When you insert a multi-line comment directly at the start of the return of the render function, the app breaks.

For example:

  ```tsx
const Home: NextPage = () => {
  return (
    /**
     * Some comment.
     */
    <div className={styles.container}>
      <Head>
    ...
  ```

This will create different errors based on your runtime and the view:

### Development (`npm run dev`)

```
error - Error: Home(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```

Browser:
![image](https://user-images.githubusercontent.com/29319414/160392111-d37059e2-85ba-4392-8df6-6c23fd36d9fd.png)

### Production (`npm run build`)
```
info  - Collecting page data  
[    ] info  - Generating static pages (0/3)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Home for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ab (/home/bennett/code/nextjs-render-comment-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:32:466)
    at d (/home/bennett/code/nextjs-render-comment-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:34:55)
    at bb (/home/bennett/code/nextjs-render-comment-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/home/bennett/code/nextjs-render-comment-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/home/bennett/code/nextjs-render-comment-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/home/bennett/code/nextjs-render-comment-bug/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/server/render.js:766:45)
    at Object.defaultGetInitialProps (/home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/server/render.js:376:51)
    at Function.getInitialProps (/home/bennett/code/nextjs-render-comment-bug/.next/server/pages/_document.js:563:20)
    at Object.loadGetInitialProps (/home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/shared/lib/utils.js:65:29)
info  - Generating static pages (3/3)

> Build error occurred
Error: Export encountered errors on following paths:
        /
    at /home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/export/index.js:396:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/build/index.js:993:17
    at async Span.traceAsyncFn (/home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/build/index.js:869:13
    at async Span.traceAsyncFn (/home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/home/bennett/code/nextjs-render-comment-bug/node_modules/next/dist/build/index.js:55:25)
➜  nextjs-render-comment-bug git:(master) 
```

---

I can confirm this happens for both variants of the multi-line comment (one or two asterisks):

- One asterisk
  ```
    /*
     * Some comment.
     */
  ```
- Two asterisks
  ```
    /**
     * Some comment.
     */
  ```

It does **NOT** happen for:
- One asterisk in one line
  ```
    /* Some comment. */
  ```
- Two asterisks in one line
  ```
    /** Some comment. */
  ```
- Normal comment over multiple lines
  ```
    // Some
    // Comment   
  ```

### To Reproduce

Reproduction repo:

https://github.com/bennettdams/nextjs-render-comment-bug

..or to manually reproduce:

1. ` npx create-next-app@12.1.2-canary.0 --ts --use-npm .`
2. Install canary `npm i next@12.1.2-canary.0`
3. Add a multi-line comment to start of the render function of `index.tsx` directly after `return`:
  ```tsx
const Home: NextPage = () => {
  return (
    /**
     * Some comment.
     */
    <div className={styles.container}>
      <Head>
    ...
  ```
4. `npm run dev` or `npm run build`

**Comment by MauriceArikoglu** [comment]
@bennettdams try wrappign your comments within the render function in curly brackets.

```
const Home: NextPage = () => {
return (

  {/**
   * Some comment.
   */}
  <div className={styles.container}>
    <Head>
  ...
```

**Comment by jakst** [comment]
> @bennettdams try wrapping your comments within the render function in curly brackets.
> 
> ```
> const Home: NextPage = () => {
> return (
> 
>   {/**
>    * Some comment.
>    */}
>   <div className={styles.container}>
>     <Head>
>   ...
> ```

You can also just move your comments above the return statement.

But a workaround is sort of uninteresting here. The important thing is to get the issue fixed. This led to production crashes for us, and there's no way to stop the issue from being reintroduced.

**Comment by MauriceArikoglu** [comment]
@jakst this has nothing to do with next or react though. It's a language feature of JSX. Embedding JS expressions just "works this way". Read more about this here: https://www.typescriptlang.org/docs/handbook/jsx.html#embedding-expressions

**Comment by bennettdams** [comment]
@MauriceArikoglu I you have a look at my original post, there are variants that don't produce an error:

> It does **NOT** happen for:
> - One asterisk in one line
>   ```
>     /* Some comment. */
>   ```
> - Two asterisks in one line
>   ```
>     /** Some comment. */
>   ```
> - Normal comment over multiple lines
>   ```
>     // Some
>     // Comment   
>   ```

I know the workarounds, but that is not the point. If you ask me, either **all** comment variants or **none** should work, but right now it's non-deterministic and will surprise some people.

**Comment by MauriceArikoglu** [comment]
@bennettdams single line comments like in your example are interpreted as text and should therefore show up in the rendered result - so not acting as comment but as a text node instead.

**Comment by bennettdams** [comment]
@MauriceArikoglu 
> single line comments like in your example are interpreted as text and should therefore show up in the rendered result

I don't think so: https://codesandbox.io/s/fancy-worker-dg23u6?file=/src/App.tsx

**Comment by balazsorban44** [comment]
This is a confirmed bug in SWC that has already been fixed (here: https://github.com/swc-project/swc/commit/552f16dba6c91876529354f3f5e155a3360a74ea) and is going to be addressed in Next.js by merging #35395. There is no need for further discussion on the topic so I'll lock it to maintainers.

Thanks for engaging! :+1:

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.4-canary.0` of Next.js, please update and give it a try!
