### ISSUE TITLE
Environment variables hidden when using dinamic retrieval

### ISSUE THREAD

**Issue by darklight9811** [vercel/next.js#35664]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022
    Binaries:
      Node: 16.6.1
      npm: 8.5.3
      Yarn: 1.22.17
      pnpm: 6.28.0
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

If you try to get a environment variable through a variable, it won't work.

### Expected Behavior

The three cases to correctly display the env variable.

### To Reproduce

``` jsx
export default function IndexPage() {
  const label = "NEXT_PUBLIC_TEST";

  return (
    <>
      <div>test: {process.env.NEXT_PUBLIC_TEST}</div>
      <div>test: {process.env["NEXT_PUBLIC_TEST"]}</div>
      <div>test: {process.env[label]}</div>
    </>
  );
}
```

**Comment by MauriceArikoglu** [comment]
@darklight9811 can you verify it's not a spelling error by mistake? What happens if you stringify your variable prior to accessing the env object value?

`      <div>test: {process.env[`${label}`]}</div>`

**Comment by darklight9811** [comment]
@MauriceArikoglu found out, actually don't know if I can do anything about this. It's because env variables are injecting in the javascript runtime, meaning the first two lines get replaced with the actual variable value. You can test out checking out the js files that your browser receive.

**Comment by MauriceArikoglu** [comment]
@darklight9811 you have to differentiate between environment variables used in server-side processes (like SSR) and client side use. In this case, I believe you'll need to make your environment variables available to the browser explicitly, to allow the CSR process to access the env var.

You do that by prefixing the env var with NEXT_PUBLIC_

https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser 

Please let me know if that fixes the problem

**Comment by darklight9811** [comment]
@MauriceArikoglu https://codesandbox.io/s/nextjs-env-bug-tsghj1

**Comment by MauriceArikoglu** [comment]
@darklight9811 nevermind, object destructuring is not supported for process env.

> Note: In order to keep server-only secrets safe, Next.js replaces process.env.* with the correct values at build time. This means that process.env is not a standard JavaScript object, so you’re not able to use [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment). Environment variables must be referenced as e.g. process.env.PUBLISHABLE_KEY, not const { PUBLISHABLE_KEY } = process.env.

https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables

What are you trying to accomplish? maybe there is alternatives

**Comment by darklight9811** [comment]
@MauriceArikoglu I'm doing an env validator/sanitizer.
