### ISSUE TITLE
Website has reloaded after new deployment

### ISSUE THREAD

**Issue by cody0203** [vercel/next.js#35677]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.1
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 99.0.4844.84 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

- Website has been reloaded after new deployment came when go to next page with `router.push()`
- I think it has been a feature of Next Js but how can i disable it? Because my website need redirect back to / page on refresh/reload (Follow the spec)
- Evident: https://user-images.githubusercontent.com/49930400/160512319-573426f3-9c22-4593-9a6a-eab7c7338d40.mov

### Expected Behavior

- My website doesn't reload after new deployment came but still have new content of it. 

### To Reproduce

- Create new source with `yarn create next-app`
- Add some pages
- Deploy it on Vercel
- Open website in / page
- Change something and deploy it again
- Go to next page with `router.push()`

**Comment by ijjk** [comment]
Hi, this is the expected behavior currently and is a feature which is described here https://nextjs.org/docs/deployment#automatic-updates we are investigating persisting as many routes/bundles as we can across deploys to prevent the number of situations this full navigation is required though.

**Comment by cody0203** [comment]
@ijjk Thank you, but one more question, how can i detect if new version is shipped, to notice users and they can manual reload the website?
