### ISSUE TITLE
Bump SWC to latest version

### ISSUE THREAD

**Issue by dlindenkreuz** [vercel/next.js#35687]
### Describe the feature you'd like to request

The current version of SWC used in `next-swc` is [`0.150.1`](https://github.com/vercel/next.js/blob/88a7e58406f866e6ed943bac9cdf38687eceb102/packages/next-swc/crates/core/Cargo.toml#L23).

Updating to the most recent version would pull in lots of [bug fixes and new features](https://github.com/swc-project/swc/blob/main/CHANGELOG.md).

### Describe the solution you'd like

Bump SWC to the most recent version (`0.161.1` [at the time of writing](https://github.com/swc-project/swc/blob/9b63369d1e10139302596ed20c14de2ef582174e/crates/swc/Cargo.toml#L12)).

### Describe alternatives you've considered

I tried to do this myself to submit a PR, but failed because of Cargo conflicts and the lack of insight how to resolve them 😿

**Comment by balazsorban44** [comment]
We are continuously upgrading SWC. :+1: The latest PR is here: https://github.com/vercel/next.js/pull/35395
