### ISSUE TITLE
NextJS Jest example throws warning during deployment

### ISSUE THREAD

**Issue by ryan-cottage** [vercel/next.js#35706]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Deploying the NextJS Jest example to Vercel results in a warning during deployment:

15:04:45.266 | Installing build runtime...
15:04:47.973 | Build runtime installed: 2.707s
15:04:48.695 | Looking up build cache...
15:04:51.255 | Build cache downloaded [46.19 MB]: 2222.878ms
15:04:51.479 | Installing dependencies...
15:04:51.744 | yarn install v1.22.17
15:04:51.815 | [1/4] Resolving packages...
15:04:52.098 | [2/4] Fetching packages...
15:05:06.307 | [3/4] Linking dependencies...
15:05:12.501 | [4/4] Building fresh packages...
15:05:12.771 | Done in 21.03s.
15:05:12.796 | Detected Next.js version: 12.1.3-canary.0
15:05:12.798 | Running "yarn run build"
15:05:13.085 | yarn run v1.22.17
15:05:13.119 | $ jest --ci && next build
15:05:15.194 | console.error
15:05:15.194 | act(...) is not supported in production builds of React, and might not behave as expected.
15:05:15.194 |  
15:05:15.195 | 4 \| describe('Home', () => {
15:05:15.195 | 5 \|   it('renders a heading', () => {
15:05:15.195 | > 6 \|     render(<Home />)
15:05:15.195 | \|           ^
15:05:15.195 | 7 \|
15:05:15.195 | 8 \|     const heading = screen.getByRole('heading', {
15:05:15.195 | 9 \|       name: /welcome to next\.js!/i,
15:05:15.195 |  
15:05:15.195 | at Object.<anonymous>.exports.act (node_modules/react-dom/cjs/react-dom-test-utils.production.min.js:37:90)
15:05:15.196 | at Object.<anonymous> (__tests__/index.test.tsx:6:11)
15:05:15.196 |  
15:05:15.311 | PASS __tests__/index.test.tsx
15:05:15.312 | Home
15:05:15.312 | ✓ renders a heading (130 ms)
15:05:15.312 |  
15:05:15.314 | Test Suites: 1 passed, 1 total
15:05:15.314 | Tests:       1 passed, 1 total
15:05:15.314 | Snapshots:   0 total
15:05:15.314 | Time:        0.929 s
15:05:15.314 | Ran all test suites.
15:05:16.055 | info  - Checking validity of types...
15:05:20.357 | info  - Creating an optimized production build...
15:05:25.490 | info  - Compiled successfully
15:05:25.491 | info  - Collecting page data...
15:05:27.513 | info  - Generating static pages (0/3)
15:05:27.561 | info  - Generating static pages (3/3)
15:05:27.568 | info  - Finalizing page optimization...
15:05:27.571 |  
15:05:27.588 | Page                                       Size     First Load JS
15:05:27.588 | ┌ ○ /                                      5.93 kB        77.5 kB
15:05:27.589 | ├   └ css/10bb29200e828224.css             495 B
15:05:27.589 | ├   /_app                                  0 B            71.5 kB
15:05:27.589 | └ ○ /404                                   192 B          71.7 kB
15:05:27.589 | + First Load JS shared by all              71.5 kB
15:05:27.589 | ├ chunks/framework-e70c6273bfe3f237.js   42 kB
15:05:27.589 | ├ chunks/main-4f7ae6aa93b0129e.js        28.2 kB
15:05:27.589 | ├ chunks/pages/_app-5508371544ba549e.js  508 B
15:05:27.589 | ├ chunks/webpack-69bfa6990bb9e155.js     769 B
15:05:27.590 | └ css/44b4f03fd3e3bcb4.css               427 B
15:05:27.590 |  
15:05:27.590 | ○  (Static)  automatically rendered as static HTML (uses no initial props)
15:05:27.590 |  
15:05:27.717 | Done in 14.64s.
15:05:27.758 | Uploading build outputs...
15:05:28.364 | Deploying build outputs...
15:05:31.597 | Build completed. Populating build cache...
15:05:40.293 | Uploading build cache [46.22 MB]...
15:05:41.938 | Build cache uploaded: 1.645s
15:05:41.967 | Done with "package.json"

### Which example does this report relate to?

with-jest

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Deploying to Vercel with Jest causes a warning that gives low confidence that tests are being run successfully.

` act(...) is not supported in production builds of React, and might not behave as expected.`

### Expected Behavior

Tests run cleanly and provide confident results (ie. no warnings)

### To Reproduce

Create a new nextjs application using the instructions `yarn create next-app --example with-jest with-jest-app`

Update the packages.json file to run jest during the build phase: `build": "jest --ci && next build`,

Deploy your newly created application to Vercel.

**Comment by ryan-cottage** [comment]
Moved to doing builds/tests in github and deploying via the cli

**Comment by Marcus-Rise** [comment]
Same issue
