### ISSUE TITLE
Add support for useDefineForClassFields typescript option

### ISSUE THREAD

**Issue by Chastrlove** [vercel/next.js#35721]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
    Binaries:
      Node: 17.6.0
      npm: 8.5.1
      Yarn: 1.22.17
      pnpm: 6.32.3
    Relevant packages:
      next: 12.1.2
      react: 16.14.0
      react-dom: 16.14.0

### What browser are you using? (if relevant)

Chrome 99.0.4844.84

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

Mobx - observable can't be applied

When I try to compile my application with next swc compiler I have this error :

> Error: [MobX] Cannot apply 'observable' to '[User@2.elo](mailto:User@2.elo)': Field not found.

And if we follow what the answer in this [stackoverflow](https://stackoverflow.com/questions/67266810/error-mobx-cannot-apply-observable-to-storeuser-field-not-found) said that I need to use useDefineForClassFields which I already use.

https://github.com/swc-project/swc/issues/3389 

https://github.com/swc-project/swc/pull/3766

 it should be fixed by swc,but next.js has't add this option

### Expected Behavior

the next-swc-loader option should add "useDefineForClassFields" property , then it can compile success

![image](https://user-images.githubusercontent.com/17813559/160807692-f5471d7f-1cd6-4c69-8c07-763a300855df.png)

### To Reproduce

https://codesandbox.io/s/young-star-6s4hmv

**Comment by timneutkens** [comment]
Related doc: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

The above doc shows how to add a test for the new behavior.
