### ISSUE TITLE
getLayout cannot assign to a server component page function

### ISSUE THREAD

**Issue by ZetraDev** [vercel/next.js#35786]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 17.7.1
      npm: 8.5.2
      Yarn: 3.2.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.4-canary.1
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

when trying to get `getLayout` inside `Component` from _app, it returns undefined

### Expected Behavior

i should be able to get the getLayout function

### To Reproduce

page:
```tsx
// ./pages/test.server.tsx
import React from "react";

export default function Test() {
	return (
		<React.Fragment>
			<p>Test</p>
		</React.Fragment>
	);
}
Test.getLayout = function getLayout(page: JSX.Element) {
	return <div className="get_layout">{page}</div>;
};
```
_app:
```tsx
// ./pages/_app.tsx
function App({ Component, pageProps }: AppProps) {
	console.log(Component.getLayout)   // <--- it returns undefined
	return (
		<div className="page">
			<Component {...pageProps } />
		</div>
	);
}

export default App;
```

**Comment by jamestrenda** [comment]
Any updates on this? I, too, am having what I think is the same issue. I feel like I've followed the documentation to a 'T' and it's not loading my custom layout defined at the page level.

**Comment by 8bitDesigner** [comment]
I can confirm I've got the same issue; the code in the documentation does not work as written. In our case, console logging out the value of `Component` returns this:

``` js
function __WEBPACK_DEFAULT_EXPORT__(props) {
    return(/*#__PURE__*/ (0,react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxDEV)(_components_en_vidcon__WEBPACK_IMPORTED_MODULE_2__["default"], _objectSpread({}, props), void 0, false, {
        fileName: "/path/to/page.js",
        lineNumber: 5,
        columnNumber: 10
    }, _this));
}
```

Meaning Webpack is returning a wrapper function which resolves to the module, instead of exporting the module itself. Since `Component` is the wrapper function, it will never have a defined `getLayout` method.

**Comment by 8bitDesigner** [comment]
Okay, strike my last comment; that was me being dumb. I found that our actual component was being wrapped by a i18n higher-order-component. I updated the component to copy the `getLayout` method from the child to the parent and everything worked after that point.
