### ISSUE TITLE
Consider updating version of "eslint-import-resolver-typescript" in "eslint-config-next"

### ISSUE THREAD

**Issue by DavideBecker** [vercel/next.js#35806]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.18.2
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

The minimist package has a security vulnerability in versions <=1.2.5.

`npm audit` reports the following dependency path: 

```eslint-config-next > eslint-import-resolver-typescript > tsconfig-paths > json5 > minimist```

All other packages and their dependencies have updated to a non-vulnerable version of minimist. However, `npm audit` still reports a vulnerability since `eslint-config-next` depends on v2.4.0 of `eslint-import-resolver-typescript`. The dependency has been updated in v2.6.0 (See: https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/98)

### Expected Behavior

Update the `eslint-import-resolver-typescript` dependency in https://github.com/vercel/next.js/blob/3069d4b77017228c86ec87238864a226efb092ae/packages/eslint-config-next/package.json#L16 from v2.4.0 to v2.6.0

### To Reproduce

Install `eslint-config-next` and run `npm audit`

**Comment by ijjk** [comment]
Closing as this should be resolved by https://github.com/vercel/next.js/pull/35781
