### ISSUE TITLE
Unable to access RuntimeConfig values when swcMinify object is added in next.config.js

### ISSUE THREAD

**Issue by binitgutka** [vercel/next.js#35815]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 14.16.0
      npm: 6.14.11
      Yarn: 1.22.4
      pnpm: 6.32.3
    Relevant packages:
      next: 12.1.4-canary.1
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome Version 100.0.4896.60 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

Using NX workspace to run next serve 

### Describe the Bug

When setting the value of 
swcMinify: to true or false 
The values of publicRuntimeConfig and serverRuntimeConfig are showing empty object
If I remove the swcMinify object I am able to access the object in _app.tsx file.

### Expected Behavior

The values of publicRuntimeConfig and serverRuntimeConfig should be available in either of the cases when swcMinify object is passed.

### To Reproduce

My _app.tsx file 
```js
import App from 'next/app';
import { useEffect } from 'react';
import getConfig from 'next/config'

// This default export is required in a new `pages/_app.js` file.

MyApp.getInitialProps = async (appContext) => {
  const appProps = await App.getInitialProps(appContext);
  return { ...appProps };
};

export default function MyApp({ Component, pageProps }) {
  useEffect(() => {
      const { publicRuntimeConfig,serverRuntimeConfig } = getConfig();
      console.log(publicRuntimeConfig,"publicRuntimeConfig",serverRuntimeConfig)
  });    
  return (
    <>
      <Component {...pageProps} />
    </>
  );
}
```

next.config.js file

```js
module.exports = composePlugins(
{
    swcMinify: false,
  },
  serverRuntimeConfig: {
 value:'data'
  },
  // Will be available on both server and client.
  publicRuntimeConfig: {
    prod: !dev,
  value:'data'
  },


);

**Comment by balazsorban44** [comment]
Given the reproduction, `publicRuntimeConfig` shows up correctly, even when using `swcMinify: true`.

Keep in mind that `serverRuntimeConfig` won't show up in `useEffect` calls, as those are only run on the client.

There might be some other issues, maybe in your `next.config.js` which is not clear from the provided code snippet.
