### ISSUE TITLE
Next dev with React 18, Always render twice

### ISSUE THREAD

**Issue by zeakd** [vercel/next.js#35822]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.5.5
      Yarn: 1.22.17
      pnpm: 6.31.0
    Relevant packages:
      next: 12.1.4
      react: 18.0.0
      react-dom: 18.0.0
```

### Describe the Bug

Hi. 
When use `next dev` with react 18, page always rendered twice.

``` jsx
// the project is just result of `create-next-app`
// pages/index.js
import { useEffect, useState } from 'react'

export default function Home() {
  console.log('render')

  const [state, setState] = useState(() => {
    console.log('state initialize');
    return 'state';
  })

  useEffect(() => {
    return () => {
      console.log('unmounted')
    }
  }, [])

  return (
    <div>
      Home
    </div>
  )
}
```
<img width="408" alt="스크린샷 2022-04-02 오전 12 36 06" src="https://user-images.githubusercontent.com/10722657/161296417-55d50aa5-a3ad-41c4-a2f3-e976a98ec7c1.png">

even lazy state intialize twice, and unmount last. So I think it is not remounted, but create twice. 
However, `next build && next start` is okay and render once.

Thanks

### Expected Behavior

Render, and Initialize Once with `next dev`

### To Reproduce

- `create-next-app`
- `npm run dev`

**Comment by GLObus303** [comment]
I assume the double render is expected due to StrictMode that `create-next-app` wraps the application with.

Although, I can reproduce the same double calling of the hooks in this simple demo -> https://codesandbox.io/s/focused-ganguly-nhsefy?file=/components/Test.js

![CleanShot 2022-04-01 at 17 46 33](https://user-images.githubusercontent.com/12488648/161297752-062b4933-fbf5-4ac9-ae4d-a79adfb13f32.png)

We have just run into a similar issue with the "useUpdateEffect" construct.

**Comment by michal-filip** [comment]
Confusing as it may be (it certainly is to me!) this seems to be the correct new behavior of [strict mode](https://reactjs.org/docs/strict-mode.html) in React 18. Effects, state initializers, renders (etc.) are called twice in dev mode when react is in strict mode.
When it comes to useEffect, what actually happens is that the effect creator is run, then the destructor is run (after which react does some assertions - forgive my ignorance here) and then state is somehow restored and effect creator is run again. In case of the custom `useUpdateEffect` hook, adding a destructor - which reverts the value of a ref - fixed the behavior. See the following sandbox: https://codesandbox.io/s/gifted-cannon-tgs7lv?file=/components/Test.js

**Comment by MonstraG** [comment]
Release blogpost talks about this behavior in section [New Strict Mode Behaviors](https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors)

**Comment by zeakd** [comment]
I think this is not correct behavior because the call order is weird. 
if it is correct strict mode behavior, it should be 

- render
- initialize state
- unmounted
- render 

but it's not. 
also lazy state is initialized twice, and it is quite critical. the heavy object is created twice in my case. it looks like created two component in parallel

in blog post, said
> whenever a component mounts for the first time, restoring the previous state on the second mount.
so unmount should be called between render, and initialize state should be called once.

**Comment by zeakd** [comment]
Okay, I found a creation twice related issue https://github.com/facebook/react/issues/20090 and it is correct to call initialize state function twice. Thank you all! 
But I still wonder, why unmount is not called between render? In CRA, unmount is not even called.

**Comment by DonovanCharpin** [comment]
Same issue on my side (dev/build) with version 12.1.4. This issue only happens when using React 18. 

From the React 18 upgrade guide, it seems that I cannot really fix it on my side as it is happening internally in next.

I'm using a custom express server and don't have much configuration. I can clearly see the first render (no interaction, only html etc) and the bundle which render just below to the first render.

It could be linked to the strict mode or an hydratation issue. I will try to change some configurations to see if I can find a fix.

**Comment by DevinEdwards** [comment]
> Same issue on my side (dev/build) with version 12.1.4. This issue only happens when using React 18.
> 
> From the React 18 upgrade guide, it seems that I cannot really fix it on my side as it is happening internally in next.
> 
> I'm using a custom express server and don't have much configuration. I can clearly see the first render (no interaction, only html etc) and the bundle which render just below to the first render.
> 
> It could be linked to the strict mode or an hydratation issue. I will try to change some configurations to see if I can find a fix.

Same issue here with version 12.1.4 & React 18. I am getting the initial HTML bundle on top of the rehydration. You can navigate through the rehydration, however, the initial HTML on top remains.

**Comment by yourfavorite** [comment]
I'm running into this issue too and it's breaking my current JWT refresh implementation by causing a race condition where two refresh requests are happening simultaneously. I've put in a workaround using localstorage for now but it's very strange that my authorization provider component is rendering (mounting?) twice in React 18 even though I'm not using strict mode.

**Comment by dung28-td** [comment]
It is intended in React 18 with Strict Mode (FYI: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode). You can find a workaround here (https://github.com/reactwg/react-18/discussions/18)

**Comment by aksdevac** [comment]
> I'm running into this issue too and it's breaking my current JWT refresh implementation by causing a race condition where two refresh requests are happening simultaneously. I've put in a workaround using localstorage for now but it's very strange that my authorization provider component is rendering (mounting?) twice in React 18 even though I'm not using strict mode.

If you are not using strict mode it should not happen, so there might be some other issue with your code, & disabling strict mode is not recommended, as it is helpful in catching errors early.

**Comment by aksdevac** [comment]
These are the logs with Strict mode ON, React 18 & latest Next.js 12.1.5, you can also see grayed out duplicate render log if you have installed React dev tools & it will confirm that its done by React strict mode
See this for more details: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#other-notable-changes

<img width="282" alt="react-18-strict-mode" src="https://user-images.githubusercontent.com/2557058/163174584-dc4127ba-2793-4bf3-84e3-7d0f1b3d4e49.png">

**Comment by mohdashraf010897** [comment]
@zeakd I did read about the new strict mode behavior and turns out we can avoid this by turning off the strict mode in next.config.js. 

![Screenshot 2022-04-16 at 12 57 20 PM](https://user-images.githubusercontent.com/57627350/163666104-5f269831-8d30-4f07-bdba-2db0820cd2e1.png)

**Comment by alexalannunes** [comment]
and when the app makes calls to an api, it will call 2 times. If I want to keep StrictMode will this always happen?
:cry:

**Comment by mohdashraf010897** [comment]
@alexalannunes Yes, but it's just a dev mode thing and doesn't affect production build 😄

**Comment by mankeheaven** [comment]
confused with 18 render twice

**Comment by sibouras** [comment]
when using react without nextjs the console output is grayed out, why is it not in nextjs?

**Comment by VahanBeck** [comment]
This change should've been highlighted more! 😪

**Comment by aksdevac** [comment]
> when using strict mode in react without nextjs the console output is grayed out, why is it not in nextjs?

Its grayed out(with react devtools) in Nextjs too, at least for me, Also getting unmount log before 2nd render. Everything is working as expected.

**Comment by sibouras** [comment]
> Its grayed out(with react devtools) in Nextjs too, at least for me, Also getting unmount log before 2nd render. Everything is working as expected.

i retested it and ur right its grayed out but not inside a useEffect(idk why!) 
```jsx
import { useState, useEffect } from 'react';

export default function App() {
  console.log('render');

  const [state, setState] = useState(() => {
    console.log('state initialized');
    return 'state';
  });

  useEffect(() => {
    console.log('run useEffect');
    return () => console.log('unmount/ cleanup Effect');
  }, []);

  return <div>hey</div>;
}

```
![render-gray](https://user-images.githubusercontent.com/64098483/165512920-3ee6bca7-99e5-47df-b8b7-750ab82e2ad7.png)

also the second render is before the unmount, i get the same order with react and next!

**Comment by balazsorban44** [comment]
This is working as intended as pointed out by many.

Please have a look at https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode for the explanation.
