### ISSUE TITLE
Next does not find .next build folder in arm64

### ISSUE THREAD

**Issue by apotdevin** [vercel/next.js#35868]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
  Platform: linux
  Arch: arm64
  Version: #1 SMP Mon Nov 8 10:21:19 UTC 2021
Binaries:
  Node: 14.15.5
  npm: 6.14.11
  Yarn: 1.22.5
  pnpm: N/A
Relevant packages:
  next: 12.1.0
  react: 17.0.2
  react-dom: 17.0.2

### How are you deploying your application? (if relevant)

Docker

### Describe the Bug

When building this [docker image](https://github.com/apotdevin/thunderhub/blob/master/arm64v8.Dockerfile) for arm64 with NextJS with a custom server (NestJS), next does not find the `.next` build folder. I have checked and the folder is there.

Next server is created [here](https://github.com/apotdevin/thunderhub/blob/master/src/server/modules/view/view.service.ts) and the next files are in [this folder](https://github.com/apotdevin/thunderhub/tree/master/src/client).

Building the docker image for [amd64](https://github.com/apotdevin/thunderhub/blob/master/Dockerfile) and for [arm32](https://github.com/apotdevin/thunderhub/blob/master/arm32v7.Dockerfile) does not show this error which makes me think this is specific to the arm64 arch.

After building the docker image for arm64 and running the container this is the error that appears:

```
Error: Could not find a production build in the '/app/src/client/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/app/node_modules/next/dist/server/next-server.js:126:23)
    at new Server (/app/node_modules/next/dist/server/base-server.js:92:29)
    at new NextNodeServer (/app/node_modules/next/dist/server/next-server.js:74:9)
    at NextServer.createServer (/app/node_modules/next/dist/server/next.js:111:16)
    at async /app/node_modules/next/dist/server/next.js:123:31
```

### Expected Behavior

Next is able to find the `.next` build folder.

### To Reproduce

1. Clone this repository: https://github.com/apotdevin/thunderhub
2. Run `npm run build:64` or `yarn build:64`. This will build [this](https://github.com/apotdevin/thunderhub/blob/master/arm64v8.Dockerfile) docker image.
3. Run the container that is built.
4. See the error posted above

**Comment by hanwenbo** [comment]
+1
