### ISSUE TITLE
title issue with react-18

### ISSUE THREAD

**Issue by SimonSiefke** [vercel/next.js#35870]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #23-Ubuntu SMP Fri Mar 11 14:54:05 UTC 2022
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.0
      react: 18.0.0
      react-dom: 18.0.0

### Describe the Bug

With React 18, there is a html comment inside the title tag: 

NextJS + React 17: 
```
<title>| abc</title>

```

NextJS + React 18: 

```
<title>| abc<!-- --></title>
```

![title-issue](https://user-images.githubusercontent.com/23744935/161531968-6868b3f4-2562-464e-9251-26978aa79115.png)

### Expected Behavior

no html comment is inside the title tag

### To Reproduce

https://github.com/SimonSiefke/nextjs-title-issue

**Comment by balazsorban44** [comment]
Probably related https://github.com/facebook/react/issues/24263

**Comment by huozhi** [comment]
Can you try to encode the whole title with jsx?

```jsx
<title>
  {(typeof location !== "undefined" ? location.pathname : "") + " | abc"}
</title>
```

**Comment by agusterodin** [comment]
I hope this isn't unnecessary noise but I can confirm this bug. I am experiencing this as well.

**Comment by balazsorban44** [comment]
_(Upvoting the original issue is usually enough unless more context/info/reproduction is provided in a comment)_

Were you able to try out the suggestion from https://github.com/vercel/next.js/issues/35870#issuecomment-1087516255?
