### ISSUE TITLE
Vercel deployment issue 404: NOT_FOUND when using middleware on dynamic routes

### ISSUE THREAD

**Issue by bryantobing12** [vercel/next.js#35893]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.1
      react: 18.0.0
      react-dom: 18.0.0
```

### What browser are you using? (if relevant)

Microsoft Edge

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I am deploying my apps to `Vercel`. but got a 404 not found page when I have `_middleware.ts` on dynamic routes and when I'm visiting the dynamic routes.

![image](https://user-images.githubusercontent.com/46083126/161675028-99a85f39-d80c-4197-b8d5-ae35939af7fe.png)

It works fine in my local

My middleware just return the `NextResponse,next()` like this
```ts
import { NextResponse } from "next/server";

const middleware = () => {
  return NextResponse.next();
};

export default middleware;
```

### Expected Behavior

- Page can be visited when deployed to Vercel without a 404 issue

### To Reproduce

I created a small repository to reproduce

https://github.com/bryantobing12/try-next-middleware

To test. when visiting `/test` it's returning 404 not found when deployed to vercel. Only happening in dynamic routes

i have this route /[customerSlug]
https://try-next-middleware.vercel.app/test

It works fine When visiting static page

https://try-next-middleware.vercel.app/dashboard

**Comment by bryantobing12** [comment]
@balazsorban44 looks like this issue only happens on `Vercel`. I tried `Netlify` and it works as expected

https://try-next-middleware.netlify.app/test

**Comment by balazsorban44** [comment]
A fix has been pushed to `canary`, please test it out (`npm i next@canary`)

**Comment by bryantobing12** [comment]
@balazsorban44  The issue with `vercel` has been fixed in the latest `canary`

but seems like this issue https://github.com/vercel/next.js/issues/35629 is back. [dynamic] route middleware will run against the parent directory. 

![image](https://user-images.githubusercontent.com/46083126/162162802-a207d5cf-30b5-464c-b0dd-f63c62fb946f.png)

**Comment by balazsorban44** [comment]
Thanks for pointing it out. The fix for this one included reverting a PR, so we are still discussing the best alternatives. :+1: Since this issue is resolved though, I'll close this one for now.

**Comment by bryantobing12** [comment]
Thank you. my temporary workaround, for now, is that
I'm checking the page name and terminating the request if the requests are not for the intended page

```ts
import { NextResponse } from "next/server";

const middleware = () => {
  const isCustomerPage = pageName?.startsWith("/[customerSlug]");

   if (!isCustomerPage) {
     return NextResponse.next();
  }
  
  // other operation

  return NextResponse.next();
};

export default middleware;
```
