### ISSUE TITLE
SWC & styled-jsx/css | Wrapped in the function scoped CSS styles not taking any effect

### ISSUE THREAD

**Issue by xtepwxly** [vercel/next.js#35945]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
   Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 14.19.1
      npm: 6.14.16
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.2
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Chrome Version 100.0.4896.60 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

`next run dev`

### Describe the Bug

Hey there,

I found out that wrapped in function _styled-jsx/css_ styles are not taking any effect. 
The issue is happening for me only if I use Rust-based compiler **SWC** for compiling Next.js project. 

`css.resolve` doesn't help with fixing this issue. 

### Expected Behavior

- if SWC is used

console.logging inline styles gives the following output:
```
String: '.c-link__cover.jsx-a70f1ef0fa37e2a2{color:#f00}'] {
  __hash: 'a70f1ef0fa37e2a2'
}
```
console.logging wrapped in function styles gives the following output:
```
[String: '.c-link__cover.jsx-c7a3b63ef91fd4e0{color:#f00}']
```
where **__hash** is missing. 

- if Babel is used

**__hash** is found in functional styles and inlined.

and the output looks the following:
```
[String: '.c-link__cover.jsx-1324596940{color:green;}\n' +
  '/*# sourceMappingURL=data:application/json;charset=utf-8;base64LONG_STRING/\n' +
  '/*@ sourceURL=/Users/home/Desktop/projects/spotify-clone/getSomeStyles.js */'] {
  __hash: '1324596940'
}
```

### To Reproduce

`index.js`
```
import { test1 } from './../styles';

const styles1 = test1(); 
    
 return (
    <>
       <div className="link">Hello</div>
       <style jsx>{styles1}</style>
    </>
);
```

`styles.js`
```
import css from 'styled-jsx/css';

function test1() {
    return css`.c-link__cover { color: #f00; }`;
}

export { test1 };
```

HTML output in browser:

SWC compiler generates the following markup: `<div class="jsx-undefined link">Hello</div>`
and CSS styles: `<style id="__jsx-undefined">.c-link__cover.jsx-c7a3b63ef91fd4e0{color:red}</style>`
Normally there shouldn't be any `undefined` in html class names.

Inlined styles working correctly for both SWC and Babel compilers.

<sub>[PACK-2987](https://linear.app/vercel/issue/PACK-2987/swc-and-styled-jsxcss-or-wrapped-in-the-function-scoped-css-styles-not)</sub>

**Comment by kdy1** [comment]
Can you provide a complete and minimal repro? I can't reproduce.
