### ISSUE TITLE
There is no type worker for strategy when using TS

### ISSUE THREAD

**Issue by daniel-bar** [vercel/next.js#35943]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.0
      npm: 6.14.11
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

warn  - Latest canary version not detected, detected: "12.1.0", newest: "12.1.5-canary.2".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

When trying to use -
`<Script strategy='worker'>`

That's the error I'm getting -
```
Type '"worker"' is not assignable to type '"afterInteractive" | "lazyOnload" | "beforeInteractive" | undefined'.ts(2322)
[script.d.ts(4, 5): ]()The expected type comes from property 'strategy' which is declared here on type 'IntrinsicAttributes & ScriptProps'
```

### Describe the Bug

When trying to use `<Script strategy='worker'>` there is no type for it.

### Expected Behavior

Should have a type for `<Script strategy='worker'>`

**Comment by balazsorban44** [comment]
This should be the case. https://github.com/vercel/next.js/blob/ad997344893403948a70edb47b0d056658458e39/packages/next/client/script.tsx#L11

You might want to update `next` as it was added in a later release. https://github.com/vercel/next.js/releases/tag/v12.1.1

_NOTE: When reporting an issue, please don't ignore the warning:_

> warn  - Latest canary version not detected, detected: "12.1.0", newest: "12.1.5-canary.2".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
