### ISSUE TITLE
Version pinning in eslint-config-next causes difficulties in supporting multiple configs

### ISSUE THREAD

**Issue by jpage-godaddy** [vercel/next.js#35977]
### Verify canary release

- [ ] ~~I verified that the issue exists in Next.js canary release~~

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Tue Jun 23 12:58:10 UTC 2020
    Binaries:
      Node: 16.13.0
      npm: 8.4.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

Our company has a standard eslint config which has a dependency on `eslint-plugin-react-hooks@^4.3.0`. The `eslint-config-next` package has a dependency on `eslint-plugin-react-hooks@4.3.0` rather than using a semver range. This is causing issues for our users where `eslint-plugin-react-hooks@4.4.0` is installed due to semver range matching in our config but then installed a _second_ time as `4.3.0`. The inability for eslint to locate a single package of this plugin then has downstream issues including actually breaking next's ability to build. We have to walk our developers through a process to get these dependencies deduped.

Could next use semver ranges for dependencies instead of pinned versions?

### Expected Behavior

If `eslint-config-next` used semver ranges, then `npm` would have resolved the existing installed `eslint-plugin-react-hooks@4.3.0` as semver-compatible and reused that dependency rather than deeming it necessary to install a separate `eslint-plugin-react-hooks` version in a nested `node_modules`.

### To Reproduce

1. Start with an empty directory.
2. Run `npm init -y`
3. Run `npm i -D eslint-config-godaddy-react`
4. Run `npm i -D eslint-config-next`
5. Run `npm ls eslint-plugin-react-hooks`
6. Observe:

```
» npm ls eslint-plugin-react-hooks                                                                                           
repro@1.0.0 /home/repro
├─┬ eslint-config-godaddy-react@8.0.0
│ └── eslint-plugin-react-hooks@4.4.0
└─┬ eslint-config-next@12.1.4
  └── eslint-plugin-react-hooks@4.3.0
```

**Comment by Niazul-Amit** [comment]
hello

**Comment by ijjk** [comment]
Closing as this should be resolved by https://github.com/vercel/next.js/pull/35781
