### ISSUE TITLE
Image Optimizer - upstream max-age regression

### ISSUE THREAD

**Issue by lluzak** [vercel/next.js#35987]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.19.0
      npm: 6.14.16
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

Changes done for upstream max-age value done in https://github.com/vercel/next.js/commit/2373320fc859af3424a8ab7e211b8292e3aafa67, are no longer there. 

Once again for upstream images we use max-age 0 which breaks CDN caching.

https://github.com/vercel/next.js/blob/5feb400aff8e7b8968174b4e339b98ce48412180/packages/next/server/image-optimizer.ts#L575

### Expected Behavior

Bring back changes from https://github.com/vercel/next.js/commit/2373320fc859af3424a8ab7e211b8292e3aafa67.

### To Reproduce

Serve image from upstream server and `Cache-Control` header will have max-age equals 0.

**Comment by anitzterritory** [comment]
+1, experiencing same issue and came to report.

**Comment by maltesa** [comment]
+1, having the same issue

**Comment by pbright** [comment]
There is some discussion of this issue on #35596.
