### ISSUE TITLE
`outputStandalone` does not work with `yarn workspaces`

### ISSUE THREAD

**Issue by jackHedaya** [vercel/next.js#36022]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
   Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.4
      react: 18.0.0
      react-dom: 18.0.0
```

### Describe the Bug

Dependencies are not found in monorepo / `yarn workspace`

```
[    ] info  - Generating static pages (0/3)
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Cannot find module '<root>/packages/website/node_modules/react/jsx-runtime.js'
```

(Dependencies are at `<root>/node_modules`)

### Expected Behavior

The build step to find the dependencies in the root folder.

### To Reproduce

Create a `yarn workspace` with a next app in `packages/`.
Configure `outputStandalone: true`. 
Run `yarn build`.

**Comment by ijjk** [comment]
Hi, the above error does not appear to be specific to `outputStandalone` as the error shown is a prerender error and not an error during the standalone folder creation. The same error should occur without `outputStandalone` enabled.
