### ISSUE TITLE
next/script component not working with Google Analytics 

### ISSUE THREAD

**Issue by MisterJimson** [vercel/next.js#36021]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

For canary
```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.4
      react: 18.0.0
      react-dom: 18.0.0
```

For stable
```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 18.0.0
      react-dom: 18.0.0
```

### What browser are you using? (if relevant)

Chrome  99.0.4844.84 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

next dev, next build && next start

### Describe the Bug

When using a Next Script component `gtag` is not attached to `window` like it is when using a regular `script` tag. 
- This has been tested with multiple `strategy` options
- This has been tested on initial page load and also as a deferred check to see if it was a timing issue.

Even when following the guidance here 1 for 1 https://nextjs.org/docs/messages/next-script-for-ga does not resolve the issue.

There is a minimal reproducible sample here: https://github.com/MisterJimson/nextjs-script-bug

### Expected Behavior

Both `gtag` and `dataLayer` should not be undefined on window when the following code is present in a NextJS app.

```
      <Script
        strategy="beforeInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GTM_CONTAINER_ID}`}
      />
      <Script
        strategy="beforeInteractive"
        id="gtag-init"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GTM_CONTAINER_ID}', {
              page_path: window.location.pathname,
            });
          `,
        }}
      />
```

### To Reproduce

A minimal reproducible sample is available here: https://github.com/MisterJimson/nextjs-script-bug

Instructions are on the readme.

**Comment by hackerxian** [comment]
set `strategy` to `afterInteractive`

https://nextjs.org/docs/messages/next-script-for-ga

**Comment by balazsorban44** [comment]
Most third-party and analytics scripts should be loaded lazily to not block the initial rendering. The above comment is the recommended way to load Google Analytics.

See the useful links section, and/or: https://nextjs.org/docs/basic-features/script#afterinteractive
