### ISSUE TITLE
URGENT: Serverless runtimes corrupted on some regions

### ISSUE THREAD

**Issue by VladimirMikulic** [vercel/next.js#36030]
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022
    Binaries:
      Node: 16.14.2
      npm: 8.0.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 18.0.0
      react-dom: 18.0.0

### Describe the Bug

`atob`/`btoa` functions are not available on Vercel serverless runtime in **some regions**.
This caused auth to break on our project because auth library relies on `globalThis.atob`.

![globalthis](https://user-images.githubusercontent.com/35997844/162558931-7abe0797-1b7b-43e8-af15-3cdabfdfd7b6.png)
![Screenshot_20220409_073935](https://user-images.githubusercontent.com/35997844/162558948-e189900e-ab6e-4ba8-8a2a-beedecc0ee64.png)
 

### Expected Behavior

I would expect `atob`/`btoa` to be available as described:
https://vercel.com/docs/concepts/functions/edge-functions#runtime-apis

### To Reproduce

It can't safely be reproduced since some regions are corrupted while others are good.
We use the same auth and same functions on 2 projects. 

The first one works, the second one doesn't because it doesn't have `atob`/`btoa`.
Keep in mind it all works locally since we run native Node.js runtime.
As a temporary solution, I [polyfilled them](https://github.com/magiclabs/magic-admin-js/issues/86).

Thanks!

**Comment by ijjk** [comment]
Hi, to confirm are you leveraging middleware? The `atob` and `btoa` methods are not provided automatically in Node.js serverless functions.

**Comment by VladimirMikulic** [comment]
Hi @ijjk! We don't use middlewares, just regular API handlers. (`api` folder)

**Comment by ijjk** [comment]
It may have been being polyfilled by a custom module being imported in your application unknowingly, hard to say without an exact reproduction.

**Comment by VladimirMikulic** [comment]
Appreciate the fast replies @ijjk.
Here is demo repo: https://github.com/VladimirMikulic/nextjs-runtime-api
API handler response: https://nextjs-runtime-api.vercel.app/api/test ("function" locally, "undefined" on Vercel)

**Comment by ijjk** [comment]
Ah I see, looks like this was added in Node.js v16 https://nodejs.org/api/globals.html#atobdata although the serverless functions only allow v14 currently.

**Comment by VladimirMikulic** [comment]
That's strange, especially since it always worked. Downgrading Magic doesn't fix the issue either.
Could you maybe give me an ETA for v16 support? Thanks a lot!

**Comment by VladimirMikulic** [comment]
I would also suggest updating documentation to exclude `atob`/`btob` since they're not available.
https://vercel.com/docs/concepts/functions/edge-functions#runtime-apis

**Comment by ijjk** [comment]
No specific ETA is available currently, adding global polyfills in the meantime should be safe until v16 support is available.
