### ISSUE TITLE
Middleware is broken with Azure CDN

### ISSUE THREAD

**Issue by ahmettahasakar** [vercel/next.js#36044]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

When I add the simplest middleware, azure CDN starts having issues displaying the web page. When I remove the middleware it works as expected. I even tested this with a an empty project.

_middleware.ts:
```
import { NextRequest, NextResponse } from 'next/server'

export function middleware(req: NextRequest) {

    try {

        console.log("--------------------------------------");
        console.log(req.url);
        console.log(req);

        const response = NextResponse.next()

        console.log(response);

        return response;
    } catch (error) {
        console.error(error);
    }

    // Return response
    return new Response('Hello, world!')
}
```

[slug].js:
```
import React from "react";
import Link from 'next/link';

const product = () => {

    return (
      <div>
       <Link href={`/${Math.random()}`}>
        <a>move</a>
       </Link>
    </div>
  );
};
export default product;

export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: "blocking",
  };
}

export const getStaticProps = async (context) => {


  return {
    props: {
     
    },
    revalidate: 340000,
  };
};
```

### Expected Behavior

Serve web pages

### To Reproduce

1) Add _middleware.ts that just returns response. No modification needed
2) Create a page that has a link to another page. So you need 2 pages.
3) Build
4) Start the server
5) Access the first page via azure cdn. No special setup needed
6) Click the link. you will see the page.
7) Reload the browser
8) You will get `Request cannot be served.` with `Http 502 error`
9) Reload the browser one more time, and you will see the content again
10) This behaviour repeats itself with each new page
11) If you remove _middleware.ts. Everything works as expected regardless of the reloads

**Comment by balazsorban44** [comment]
Hi, could you explain how you deploy your application?

Do you maybe have an example deployed that could be debugged?

Any logs on the Azure side about the 502?

**Comment by ahmettahasakar** [comment]
Hello

I tested both deployed and local. Same problem. I pointed the cdn to my local dev environment. So i did

npm run build
npm run start

Having said that deployed version has the same problem. So i dont think it is deployment

When middleware is active is nextjs returning responses in a different way that it confuses the cdn? When cdn is not in the picture it works. When middleware is not in the picture it works. 

No logging on cdn side i am afraid.

**Comment by balazsorban44** [comment]
Regardless of the issue, I actually believe that running Middleware through a CDN kind of defeats its purpose, which is to execute it on every request. :thinking:

cc @javivelasco might give a better answer here, or have an idea about what the issue can be

**Comment by ahmettahasakar** [comment]
I want to add a custom response header based on the request. Is there any other way?

**Comment by ahmettahasakar** [comment]
@javivelasco  any ideas?

**Comment by ahmettahasakar** [comment]
After hours of debugging, I understood that the, when middleware is enabled, extra preflight HEAD request during link prefetch is confusing the CDN. Is it possible to have specific cache response headers for these requests, so that I can make them bypass CDN cache?

**Comment by ahmettahasakar** [comment]
Apparently it is by design that Azure CDN, converts HEAD requests to a GET when sending to origin server. The way to mitigate this is by creating a CDN rule to disable caching when `x-middleware-preflight` header is set
