### ISSUE TITLE
with-tailwindcss is by default creating typescript

### ISSUE THREAD

**Issue by akhil-gautam** [vercel/next.js#36045]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```bash
npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: 6.32.4
    Relevant packages:
      next: 12.1.4
      react: 17.0.2
      react-dom: 17.0.2
```

### Which example does this report relate to?

https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss

### Describe the Bug

When I am running `npx create-next-app --example with-tailwindcss myapp`, by default it is generating the project with Typescript.
 

### Expected Behavior

I don't think, it should be bootstrapped with typescript by default, better make a different example for it.

### To Reproduce

Run `npx create-next-app --example with-tailwindcss myapp` to generate a tailwind app.

**Comment by balazsorban44** [comment]
This is intended. We prefer TypeScript even for examples now, as it eliminates a class of issues and we believe that ultimately it will make developers more productive.
