### ISSUE TITLE
assetPrefix is not getting respected

### ISSUE THREAD

**Issue by ajayjaggi97** [vercel/next.js#36061]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: N/A
      react-dom: N/A

### What browser are you using? (if relevant)

chrome 100.0.4896.60

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

```
const prod = process.env.NODE_ENV === 'production'
const __ID__ = process.env.BUILD_ID;

const PROD_PUBLIC_PATH = __ID__ ? `/assets/${__ID__}` : '';

const nextJSConfig = {
  assetPrefix: prod ? PROD_PUBLIC_PATH : 'http://localhost:3000',
}
```

I set the asset prefix like this. 
During build time i run `BUILD_ID=XXXX next build`
then to start the server i run `next start`

but my assetPrefix is always ''

### Expected Behavior

assetPrefix should be respected according to env variable

### To Reproduce

```
const prod = process.env.NODE_ENV === 'production'
const __ID__ = process.env.BUILD_ID;

const PROD_PUBLIC_PATH = __ID__ ? `/assets/${__ID__}` : '';

const nextJSConfig = {
  assetPrefix: prod ? PROD_PUBLIC_PATH : 'http://localhost:3000',
}
```

In production mode, when the server starts the assetPrefix is always empty

**Comment by balazsorban44** [comment]
You should either add `BUILD_ID` to a `.env*` file to be picked up automatically or pass it to production as `BUILD_ID=XXXX next start`.
