### ISSUE TITLE
Docs: no-cache: Add guide for DigitalOcean

### ISSUE THREAD

**Issue by Voyager-Two** [vercel/next.js#36107]
### What is the improvement or update you wish to see?

It would be nice if Next.js cache capability was supported on DigitalOcean's app platform.

- https://www.digitalocean.com/products/app-platform
- https://nextjs.org/docs/messages/no-cache

I'm not sure how it would exactly work, maybe would require changes on DigitalOcean's side?
They already cache `node_modules` automatically.
I'm using Docker, so that already has cache capabilities, but I assume it's not the same thing.

### Is there any context that might help us understand?

```bash
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/no-cache

**Comment by timneutkens** [comment]
Feel free to open a PR for this 👍

**Comment by Voyager-Two** [comment]
Unfortunately DO support team responded saying this is currently not supported.

I submitted an [idea request](https://ideas.digitalocean.com/app-framework-services/p/support-custom-caching-for-builds).

I can do a PR with something like this, but not sure if it would be appropriate or not.
![image](https://user-images.githubusercontent.com/3676208/164297779-400176bd-ddb2-4b84-84d3-826f37e08341.png)

Will close this for now.
