### ISSUE TITLE
create-next-app with typescript exiting with error

### ISSUE THREAD

**Issue by shellord** [vercel/next.js#36106]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

  Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.0.1
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 18.0.0
      react-dom: 18.0.0

### Describe the Bug

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

	yarn add --dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Expected Behavior

it should run a development server.

### To Reproduce

npx create-next-app --ts my-app
npm run dev

**Comment by ijjk** [comment]
Hi, this is now fixed in the latest version of Next.js `v12.1.5`, please update and give it a try!
