### ISSUE TITLE
Error: Required TypeScript package(s) not installed, yet they are

### ISSUE THREAD

**Issue by niels-k-86** [vercel/next.js#36103]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.2
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5-canary.6
      react: 18.0.0
      react-dom: 18.0.0

### Describe the Bug

Both `next dev` and `next build` throw an error about missing typescript packages, however they are in the devDependencies and are installed in `node_modules`. I've started a clean project with `yarn create next-app --typescript`. I've tried deleting my `yarn.lock`, `node_modules` and doing `yarn install --production=false`.

The error:

```
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

	yarn add --dev @types/react
```

My package.json:

```
{
  "name": "next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.1.4",
    "react": "18.0.0",
    "react-dom": "18.0.0"
  },
  "devDependencies": {
    "@types/node": "17.0.23",
    "@types/react": "18.0.3",
    "@types/react-dom": "18.0.0",
    "eslint": "8.13.0",
    "eslint-config-next": "12.1.4",
    "typescript": "4.6.3"
  }
}
```

And my tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

The missing package does seem to be installed in `node_modules/@types/react`.

### Expected Behavior

Run the NextJS app without an error.

### To Reproduce

Start a new NextJS project by running `yarn create next-app --typescript`.

**Comment by ijjk** [comment]
Hi, this is related to a change made in the recent react types and is updated in `v12.1.5-canary.7` of Next.js, please update and give it a try!

**Comment by goleary** [comment]
Just tested with `v12.1.5-canary.7` and this issue does not still exist.

**Comment by niels-k-86** [comment]
Can confirm, work with canary 7. Thanks for the quick reply!

**Comment by haf** [comment]
`➤ YN0016: │ next@npm:canary.7: Registry failed to return tag "canary.7"`
