### ISSUE TITLE
CORS error in next-with-apollo demo

### ISSUE THREAD

**Issue by verheyenkoen** [vercel/next.js#36112]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

The online demo hosted on vercel

### Which example does this report relate to?

next-with-apollo

### Describe the Bug

The demo doesn't do anything. Initially it keeps loading and a console error is logged:

> Access to fetch at 'https://nextjs-graphql-with-prisma-simple.vercel.app/api' from origin 'https://next-with-apollo.vercel.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Expected Behavior

It should work

### To Reproduce

Just go to https://next-with-apollo.vercel.app/ and see it fail.

**Comment by balazsorban44** [comment]
This example is not maintained by the Next.js team. Following the GitHub link on the page, you can report this issue here instead: https://github.com/adamsoffer/next-apollo-example

But as I can tell, it hasn't been updated in ~2 years

**Comment by verheyenkoen** [comment]
I'm referring to this example: https://github.com/vercel/next.js/tree/canary/examples/with-apollo which is linked from [this page](https://nextjs.org/examples)

**Comment by balazsorban44** [comment]
My bad, thanks!

Looks like the GitHub URL points to an outdated destination.
