### ISSUE TITLE
Nested <Suspense> blocks doesn't work: Hydration failed

### ISSUE THREAD

**Issue by IdkMan2Usertive** [vercel/next.js#36152]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.0
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Wersja 100.0.4896.75 (Official) (x86_64)

### How are you deploying your application? (if relevant)

Not relevant

### Describe the Bug

I was trying to create an application using the newest features from React 18 (just to play around), including `<Suspense>` for data fetching and `useTransition` hook.

I have followed the [React Suspense guide](https://17.reactjs.org/docs/concurrent-mode-suspense.html#what-is-suspense-exactly) and created a simple app with users & posts, exactly as described in the guide.

I have discovered that everything works well as long as I don't have nested `<Suspense>` blocks in the code but If I decide to do so I get:

```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

### Expected Behavior

There should be a possibility to define nested `<Suspense>` blocks as in the [React Suspense guide](https://17.reactjs.org/docs/concurrent-mode-suspense.html#what-is-suspense-exactly):

```jsx
function ProfilePage({ resource }) {
  return (
    <Suspense fallback={<h1>Loading profile...</h1>}>
      <ProfileDetails resource={resource} />
      <Suspense fallback={<h1>Loading posts...</h1>}>
        <ProfileTimeline resource={resource} />
      </Suspense>
    </Suspense>
  );
}
```

### To Reproduce

1. Clone the reproduction repository:

```
https://github.com/usertive/nextjs-nested-suspense-issue
```

2. yarn next dev

3. Observe what error you get:

```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```

4. Now comment out following lines:

```diff
// src/components/ProfilePage.tsx

<div className={'profile'}>
  Select user by ID:&nbsp;
  <select onChange={handleSelectChange} className={'profile-select'}>
    <option value={1}>1</option>
    <option value={2}>2</option>
    <option value={3}>3</option>
    <option value={4}>4</option>
  </select>

  <div className={'profile-metadata'}>
    <p>Displaying data for user with ID: {userId}</p>
    <p>Data is {isUserChangeTransitionPending ? 'updating...' : 'up to date'}.</p>
  </div>

  <ErrorBoundary fallback={<p>Unable to fetch profile!</p>}>
    <Suspense fallback={<p>Loading profile...</p>}>
      <ProfileDetails userResource={userResource}/>

      <ErrorBoundary fallback={<p>Unable to fetch posts for user with ID {1}!</p>}>
-        <Suspense fallback={<p>Loading posts...</p>}>
          <ProfileTimeline postsResource={postsResource}/>
-        </Suspense>
      </ErrorBoundary>
    </Suspense>
  </ErrorBoundary>
</div>
```

5. Refresh & observe that the page is loading correctly now, without any errors.

**Comment by JanKaifer** [comment]
Tried it in `next@13.1.2-canary.8` and it works now.
