### ISSUE TITLE
redirection to default locale doesn't work from getStaticProps(fallback) when we're in another locale currently

### ISSUE THREAD

**Issue by vinaynair39** [vercel/next.js#36169]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Other platform

### Describe the Bug

let's say you entered /es/xyz/[slug] on chrome and since this page wasn't statically generated before, getStaticProps runs and since there is not Spanish content for this page, I want to redirect the user to /xyz/[slug]. but the below doesn't work.

```
 return {
      redirect: {
        destination: '/xyz/abc',
        permanent: false,
      },
    };
```

I even tried doing 
```
 return {
      redirect: {
        destination: '/en/xyz/abc',
        permanent: false,
      },
    };
```

but that doesn't work either.

So my question is how to change the current locale to the default one inside of getStaticProps?

### Expected Behavior

redirects to default locale inside of getStaticProps when you're in a different locale currently should happen.

### To Reproduce

I think whatever I wrote above kinda explains it. Thanks a lot!

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.7-canary.8` of Next.js, please update and give it a try!
