### ISSUE TITLE
Docs: (next.config.js).experimental.workerThreads

### ISSUE THREAD

**Issue by DanielBailey-web** [vercel/next.js#36174]
### What is the improvement or update you wish to see?

I cannot find any documentation on workerThreads. But my intellisense says it exists. It sounds interesting and fun but I don't know how to get started.

### Is there any context that might help us understand?

```js
/** @type {import('next').NextConfig} */
const options = {
  experimental:{
    workerThreads: true
  },
};
```

**Comment by balazsorban44** [comment]
Experimental features are often not documented unless we want to reach a broader audience for feedback or we feel more confident about certain features. Undocumented APIs are always subject to change.
