### ISSUE TITLE
Broken context w/ next 12.1.5-rc.2 and above

### ISSUE THREAD

**Issue by arcanis** [vercel/next.js#36198]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #77~18.04.1-Ubuntu SMP Wed Mar 30 15:36:02 UTC 2022
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 4.0.0-rc.2
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.1
      react: 18.0.0
      react-dom: 18.0.0

### Describe the Bug

An application I have is having a strange behavior after an upgrade from 12.1.0 to current. Bisecting the releases, the problem started in 12.1.5-canary.2. I presume it's from [the React 18 upgrade](https://github.com/vercel/next.js/pull/35888), but I didn't try individual commits (is there an easy way to build them locally?).

I have some contexts defined inside layout components (using a pattern similar to the one described [here](https://nextjs.org/docs/basic-features/layouts)), and since this upgrade those contexts are missing in the SSR build, crashing the direct page load (navigating to the page client-side works fine). It's almost as if pages were built without the _app wrapper.

### Expected Behavior

Should work.

### To Reproduce

To reproduce, clone https://github.com/arcanis/next-bug-context-ssr, run `yarn && yarn next dev`, and open localhost. It will crash. If you run `yarn add next@12.1.5-canary.1` before restarting the server, it'll work.

**Comment by arcanis** [comment]
Bisecting commits, it seems the problem started with #35666 (cc @huozhi). I'm not too sure whether it's expected or not - I don't use server components, and my app file is `_app.ts` (not `_app.client.ts`), so I'd expect it to be applied on SSR rendering as well 🤔

**Comment by arcanis** [comment]
I found a repro (also editing the OP to include these informations). It seems to be related to `next-urql`, although I don't know if the actual problem comes from them doing something bad, or Next having a regression.

To reproduce, clone https://github.com/arcanis/next-bug-context-ssr, run `yarn && yarn next dev`, and open localhost. It will crash. If you run `yarn add next@12.1.5-canary.1` before restarting the server, it'll work.

**Comment by arcanis** [comment]
Can confirm using a custom build now works, thanks for the quick fix!

**Comment by huozhi** [comment]
Thanks for reporting and digging deep! 🙏

**Comment by ijjk** [comment]
Hi, the above patch is now available in `v12.1.6-canary.3` of Next.js, please update and give it a try!

**Comment by klarstrup** [comment]
My tests are now passing again as of `next@12.1.6-canary.3`!
