### ISSUE TITLE
getStaticProps revalidate not working for non-dynamic pages

### ISSUE THREAD

**Issue by BlakeBrown** [vercel/next.js#36204]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.6.0
      npm: 8.5.1
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 12.0.9
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Version 100.0.4896.88 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

We're using `getStaticProps` with a `revalidate` field to regenerate pages within our app. I've noticed it works for dynamic pages that have `getStaticPaths` defined, but it doesn't work for non-dynamic pages such as our homepage.

Our current homepage method looks like this...

```
export async function getStaticProps() {
  const { data: allCollections } = await axios.get(`collection/mostVolume`, {
    params: {
      page: 1,
      take: 20,
    },
  });

  const { data: rank } = await axios.get(`collection/rank`);
  const { data: homepageFlex } = await axios.get(`collection/homepageFlex`);

  return {
    props: {
      revalidate: 3600,
      collectionRanks: rank,
      collections: allCollections,
      homepageFlex: homepageFlex,
    },
  };
}
```

This should regenerate the data every hour, but instead it only regenerates each time we make a new Vercel deployment. Has anyone else seen this / know what the bug is?

### Expected Behavior

Would expect that the page's data gets refreshed every hour.

### To Reproduce

I haven't made a repo, but I believe you could reproduce this by making an `index.js` file with a getStaticProps method fetching data that needs to get revalidated.

**Comment by ijjk** [comment]
Hi, it looks like you are returning `revalidate` inside of your `props` which has no affect, it should be returned as a top-level field on the object returned from `getStaticProps`.

**Comment by BlakeBrown** [comment]
That was exactly the issue, thank you so much @ijjk 🙏
