### ISSUE TITLE
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.

### ISSUE THREAD

**Issue by nrakochy** [vercel/next.js#36210]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```js   
 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 3.2.0
      pnpm: 6.11.0
    Relevant packages:
      next: 12.1.6-canary.2
      react: 18.0.0
      react-dom: 18.0.0
```

### What browser are you using? (if relevant)

Chrome 99

### Describe the Bug

Thanks for the great library 👍 

After fresh install, types are not recognized. I think this is a bit different than the myriad other issues that reported bad React types. That is, everything builds as expected, but the compiler does not recognize the `jsx: preserve`  flag in the `tsconfig.json` 🤔 

<img width="776" alt="Screen Shot 2022-04-15 at 11 41 52 PM" src="https://user-images.githubusercontent.com/3740177/163661828-caff89ea-a198-4f91-bb74-96c0deca1ad6.png">

### Expected Behavior

No errors in the olde editor

### To Reproduce

```js
1. yarn create next-app --typescript
2. yarn add next@v12.1.6-canary.2      
3. Open index.tsx file
```

**Comment by timneutkens** [comment]
<img width="1290" alt="Screen Shot 2022-04-20 at 16 03 44" src="https://user-images.githubusercontent.com/6324199/164248461-3cfd6ffa-bb1f-45bf-8df9-e2ba558595e8.png">

I can't reproduce this based on the provided description 🤔  Types look fine both with 12.1.6-canary.2 and latest canary.

**Comment by nrakochy** [comment]
I suppose this probably related to some mixture of React 18 types + VSCode + tsconfig. That said, it makes the project generator quite noisy and  difficult to use for a fresh install.
