### ISSUE TITLE
TypeScript 4.6 ESLint Warning still exist

### ISSUE THREAD

**Issue by KoreSamuel** [vercel/next.js#36238]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

**os: ubuntu@18.14.5
node: v12.22.12
yarn: v1.22.18**

`npx create-next-app@canary test --ts`

```
yarn lint   
yarn run v1.22.18
$ next lint
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.6.0

YOUR TYPESCRIPT VERSION: 4.6.3

Please only submit bug reports when using the officially supported version.

=============
✔ No ESLint warnings or errors
Done in 1.44s.

```

### Describe the Bug

https://github.com/vercel/next.js/issues/35784

### Expected Behavior

work as a document except https://nextjs.org/docs/basic-features/eslint

### To Reproduce

1.
 ```
$ npx create-next-app@canary --version
npx: installed 1 in 1.327s
12.1.6-canary.3
```

2. `npx create-next-app@canary test --ts`
3.  `yarn lint`

**Comment by ytkg** [comment]
create-next-app seems to install v12.1.5

```
$ git diff package.json
diff --git a/package.json b/package.json
index a2ff7b9..ce4d1f0 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,7 @@
     "lint": "next lint"
   },
   "dependencies": {
-    "next": "12.1.5",
+    "next": "12.1.6-canary.3",
     "react": "18.0.0",
     "react-dom": "18.0.0"
   },
@@ -18,7 +18,7 @@
     "@types/react": "18.0.5",
     "@types/react-dom": "18.0.1",
     "eslint": "8.13.0",
-    "eslint-config-next": "12.1.5",
+    "eslint-config-next": "12.1.6-canary.3",
     "typescript": "4.6.3"
   }
 }
```

```
$ yarn lint
yarn run v1.22.11
$ next lint
✔ No ESLint warnings or errors
✨  Done in 2.84s.
```

It worked fine.

**Comment by KoreSamuel** [comment]
Thanks for your response.
I have tried your suggestion, and it worked the same as you shared.

But when I executed the `yarn lint` following the document's steps, it didn't match the expectation.
Maybe it should display as below, right?
```
yarn lint

# You'll see a prompt like this:
#
# ? How would you like to configure ESLint?
#
# ❯   Base configuration + Core Web Vitals rule-set (recommended)
#     Base configuration
#     None
```

**Comment by ytkg** [comment]
It's in the documentation.

> If you don't already have ESLint configured in your application, you will be guided through the installation and configuration process.

Not shown because it is already set.

Try deleting `.eslintrc.json` and then executing `yarn lint`
