### ISSUE TITLE
useEffect or componentDidMount is called twice in dev build with reactStrictMode: true

### ISSUE THREAD

**Issue by rishabhpoddar** [vercel/next.js#36233]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: 5.14.3
    Relevant packages:
      next: 12.1.6-canary.3
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

React strict mode results [in a few React hooks](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) to be called twice to detect side effects. The list on their site doesn't include:
- `useEffect`
- `componentDidMount`

However, when running NextJS in dev build with the following `next.config.js`
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
```

it calls `useEffect` and `componentDidMount` twice as well. Note that it calls `useEffect` even if the dependency array is `[]`.

### Expected Behavior

We should always expect that `useEffect` is called once per component mount if the dependency array is `[]`, and same goes for `componentDidMount`.

### To Reproduce

From the react starter template (running `yarn create next-app`)
```js
import React from "react";
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {

  React.useEffect(() => {
    console.log("Called useEffect");
  }, []);

  return <Component {...pageProps} />
}

export default MyApp
```

We modify the `_app.js` file to add a `useEffect` and then on the browser (after running `npm run dev`), you see:
<img width="325" alt="Screenshot 2022-04-18 at 00 06 13" src="https://user-images.githubusercontent.com/2976287/163727902-a55879a5-87f2-4a1f-b713-b880a6c5391e.png">

Then running the same code with `reactStrictMode: false`, you see (or running a production build):
<img width="291" alt="Screenshot 2022-04-18 at 00 07 31" src="https://user-images.githubusercontent.com/2976287/163727940-0cedc70a-7260-47c0-96de-38053bd76705.png">

**Comment by sa3dany** [comment]
Hi @rishabhpoddar, this is expected in React 18 and not a bug in Next.js. Please review the [relevant section](https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors) in the React 18 anouncement [blog post](https://reactjs.org/blog/2022/03/29/react-v18.html).

**Comment by rishabhpoddar** [comment]
Thanks for the pointer @sa3dany . I am closing this issue.
