### ISSUE TITLE
Invalid "Native Node.js APIs are not supported in the Edge Runtime" error message

### ISSUE THREAD

**Issue by nkzawa** [vercel/next.js#36237]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.3
      react: 18.0.0
      react-dom: 18.0.0

### Describe the Bug

When there is a page like the following, `next build` shows the error message `> Native Node.js APIs are not supported in the Edge Runtime. Found "child_process" imported, on index.`, even when there is no middleware used.

```js
import { spawn } from 'child_process';

export default function Page() {
  return <div>ok</div>
}
```

This is the same for the compilation error using `next dev`.

Also, a related problem, but when you use react version 17, this message is NOT shown for middleware importing `child_process`.

### Expected Behavior

The error message is shown only for edge functions certainly, even with older react version.

### To Reproduce

Import the `child_process` module on a page, without middleware, with react@18.

**Comment by riboher** [comment]
I'm experiencing a similar issue after updating my NextJS app to React v18. I have some packages installed that under the hood make use of native Node APIs such as `tls`, `http2`, or `fs`. When running either `next build` or `next dev`, the following output shows up:

```
./node_modules/@grpc/grpc-js/build/src/call-stream.js
Module not found: Can't resolve 'http2' in './node_modules/@grpc/grpc-js/build/src'

Import trace for requested module:
./node_modules/@grpc/grpc-js/build/src/channel.js
./node_modules/@grpc/grpc-js/build/src/index.js
./node_modules/@product/aker-grpc-client/es2015/index.js
./src/services/grpcServices.ts
./src/services/custom/BrazeService.ts
./src/services/workers/exportCommsEnabledDrivers.worker.ts

./node_modules/@grpc/grpc-js/build/src/channel-credentials.js
Module not found: Can't resolve 'tls' in './node_modules/@grpc/grpc-js/build/src'

Import trace for requested module:
./node_modules/@grpc/grpc-js/build/src/index.js
./node_modules/@product/aker-grpc-client/es2015/index.js
./src/services/grpcServices.ts
./src/services/custom/BrazeService.ts
./src/services/workers/exportCommsEnabledDrivers.worker.ts

./node_modules/@grpc/grpc-js/build/src/http_proxy.js
Module not found: Can't resolve 'tls' in './node_modules/@grpc/grpc-js/build/src'

Import trace for requested module:
./node_modules/@grpc/grpc-js/build/src/channel.js
./node_modules/@grpc/grpc-js/build/src/index.js
./node_modules/@product/aker-grpc-client/es2015/index.js
./src/services/grpcServices.ts
./src/services/custom/BrazeService.ts
./src/services/workers/exportCommsEnabledDrivers.worker.ts

./node_modules/@grpc/grpc-js/build/src/resolver-dns.js
Module not found: Can't resolve 'dns' in './node_modules/@grpc/grpc-js/build/src'

Import trace for requested module:
./node_modules/@grpc/grpc-js/build/src/resolver.js
./node_modules/@grpc/grpc-js/build/src/index.js
./node_modules/@product/aker-grpc-client/es2015/index.js
./src/services/grpcServices.ts
./src/services/custom/BrazeService.ts
./src/services/workers/exportCommsEnabledDrivers.worker.ts

./node_modules/@grpc/grpc-js/build/src/resolver-dns.js
Module not found: Can't resolve 'net' in './node_modules/@grpc/grpc-js/build/src'

Import trace for requested module:
./node_modules/@grpc/grpc-js/build/src/resolver.js
./node_modules/@grpc/grpc-js/build/src/index.js
./node_modules/@product/aker-grpc-client/es2015/index.js
./src/services/grpcServices.ts
./src/services/custom/BrazeService.ts
./src/services/workers/exportCommsEnabledDrivers.worker.ts


> Native Node.js APIs are not supported in the Edge Runtime. Found `http2` imported.
```

Downgrading to react v17 solves the problem

**Comment by joecarney** [comment]
@riboher I have just had the same problem and found this issue.  When I `import` a function that I don't call further down, I get `Module not found: Can't resolve 'fs'`.  If I call the function, the  error message disappears.

I can remember have had similar problems with this in the past

**Comment by aruke** [comment]
Is there any workaround other than downgrading React to v17?

**Comment by kimbaudi** [comment]
I also get this error message due to importing 'fs' (i.e., `import { accessSync, constants } from 'fs';`). But isn't that the expected behavior? https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis notes that `Native Node.js APIs are not supported. For example, you can't read or write to the filesystem`.

**Comment by G4LH4** [comment]
I get this error too while trying to use twilio video, and downgrading React to v17 didn't help.

**Comment by nkzawa** [comment]
To clarify, basically you cannot use Node.js modules on middleware (edge functions), so it's expected that `fs` or any other modules don't work. tho Some node.js modules MIGHT work if they don't use node.js specific APIs.

This issue is about displaying the error message on wrong conditions.

**Comment by marek-hanzal** [comment]
I've the same problem when switched to React 18. I'm using custom entry points for workers which worked fine before switching to R18. Now, the build is failing on node.js native stuff too (like the others here), for example because of Prisma Client.

![image](https://user-images.githubusercontent.com/13855126/166254748-3b96f0ec-2f28-4d02-90f6-22807535a1a5.png)

In general, I don't care about some "Edge Runtime" in which case I even don't know what it is or why it even exists or why it's so aggresively pushed inside the build (for Vercel or some serverless stuff, I'm ok), but I'm doing standard build for standard node.js env. so I expect the build to work as standard too, not like this:

![image](https://user-images.githubusercontent.com/13855126/166255199-20b7e1a3-58c5-4cdb-b6c5-60321cc3c94c.png)

**Comment by CGamesPlay** [comment]
Apologies for commenting here, but @marek-hanzal's issue is also my issue and I was able to solve it.

The "edge runtime" is a **third** webpack config that Next is using. This means that to add an extra entry to your webpack config, you need to use the `nextRuntime` hidden option (it should [be documented here](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) but isn't yet). The following seems to work for me:

```js
  webpack: (config, { nextRuntime }) => {
    // Undocumented property of next 12.
    if (nextRuntime !== "nodejs") return config;
    return {
      ...config,
      entry() {
        return config.entry().then((entry) => ({
          ...entry,
          cli: path.resolve(process.cwd(), "lib/cli.ts"),
        }));
      },
    };
  },
```

**Comment by riboher** [comment]
Hey @CGamesPlay, thank you for this! It fixed my issue as well! In my case, I had to actually check that the runtime was `nodejs` in order to apply the config that did use Node APIs, tried again to build and it succeeded. Thanks again!

**Comment by marek-hanzal** [comment]
Yep, I can confirm I've solved that issue same way. It was quite hidden there. But now it works.

**Comment by balazsorban44** [comment]
Docs should be updated https://github.com/vercel/next.js/pull/36685 thanks @CGamesPlay!
