### ISSUE TITLE
Jest errors with inline SVGs in Next 12.1.1+

### ISSUE THREAD

**Issue by rsanchez** [vercel/next.js#36230]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.3
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

When using SVGR (or presumably any other Webpack-based SVG importing library) and inline rendering the imported SVG, I encounter errors in Jest when running tests:

```
    Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

```

A minimal example of inline rendering an imported SVG (as opposed to utilizing next/image):

```
import Vercel from '../public/vercel.svg'

export default function Home() {
  return (
    <div>
      <h1>Welcome to Next.js!</h1>
      <Vercel />
    </div>
  )
}

```

This is because the next build tool which provides the Jest configuration includes this `moduleNameMapper` [rule](https://github.com/vercel/next.js/blob/3c1515953d808a1296dd6d1e06e2f1d6ace4d888/packages/next/build/jest/jest.ts#L89):

```
          // Handle image imports
          '^.+\\.(png|jpg|jpeg|gif|webp|avif|ico|bmp|svg)$': require.resolve(
            `./__mocks__/fileMock.js`
          ),
```

This fileMock resolver provides an object which is meant to be supplied to a Next `<Image />` component. But in my use case I want to directly render the SVG without next/image.

There is no way to override this image import rule for SVGs in my own jest.config.js.

Related issues:
https://github.com/vercel/next.js/pull/34350#issuecomment-1055463916
https://github.com/vercel/next.js/discussions/33161
https://github.com/vercel/next.js/discussions/26167

### Expected Behavior

Next should provide a configuration option to exclude SVGs from being mocked this way in Jest.

### To Reproduce

Repo with reproduction code: https://github.com/rsanchez-forks/next-with-jest-and-svgr

```
git clone git@github.com:rsanchez-forks/next-with-jest-and-svgr.git
cd next-with-jest-and-svgr
npm install
npm test
```

**Comment by timneutkens** [comment]
When you customize webpack configuration you need to make additional adjustments to other tooling as well, we can't provide an out of the box solution for customizations you're adding manually. As such this is not a bug in the Jest config but missing configuration in your application.

Here's how you could apply addition settings / override anything in the Jest config.

```js
const nextJest = require(https://github.com/vercel/next.js)

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
})

// Add any custom config to be passed to Jest
const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    // Handle module aliases (this will be automatically configured for you soon)
    '^@/components/(.*)$': '<rootDir>/components/$1',

    '^@/pages/(.*)$': '<rootDir>/pages/$1',
  },
  testEnvironment: 'jest-environment-jsdom',
}

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
const jestConfig = createJestConfig(customJestConfig)

// You can edit the jest config that comes out of createJestConfig, it's a Jest config that combines Next.js specifics with your custom config.
delete jestConfig.moduleNameMapper['^.+\\.(png|jpg|jpeg|gif|webp|avif|ico|bmp|svg)$']

// Add your custom mapper
jestConfig.moduleNameMapper['^.+\\.(png|jpg|jpeg|gif|webp|avif|ico|bmp|svg)$'] = require.resolve('something')


module.exports = jestConfig
```

**Comment by David-Rickard** [comment]
It requires a not entirely clean workaround; a straightforward application of settings for `moduleNameMapper` does not work since the earlier built-in entry takes precedence.
