### ISSUE TITLE
isn't work at Specific path 

### ISSUE THREAD

**Issue by ukhyun2402** [vercel/next.js#36259]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.13.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:        
      next: 12.1.5
      react: 18.0.0
      react-dom: 18.0.0 

### Which example does this report relate to?

next script isn't work specific path 

### Describe the Bug

I execute script to run next js.  where i nstalled specific path  (i.e  ~/Desktop/react/udemy/next-starter ) 
![image](https://user-images.githubusercontent.com/38240148/163907153-7114bcc6-2b28-4506-a2ac-bd68679421fd.png)

And i execute script to run but script was occured error. I scrutinize error message. I found some path separator isn't apply.

So, I execute script in other path to check out error
![image](https://user-images.githubusercontent.com/38240148/163907482-1eebbdff-7172-4458-8d2a-7165b87c6207.png)

It work absolutely fine!

### Expected Behavior

it work any path i want

### To Reproduce

.

**Comment by ukhyun2402** [comment]
firstly, thanks you reply

I try you suggestion. It didn't work same in 12.1.4
![image](https://user-images.githubusercontent.com/38240148/166129281-0845bf26-854c-48b0-a9ae-3ec3dcff6902.png)

when i type ``` npx next info ``` i found what version installed. please check version in picture

so I follow diection in warn message to update latest canaty version using this script ``` npm install next@canary ``` 

and it same result like below

![image](https://user-images.githubusercontent.com/38240148/166129373-82477bb2-9f7f-44c9-b890-c7129d89e26f.png)

**Comment by balazsorban44** [comment]
It looks like in your case this might have been introduced in an even earlier version. Could you try to find what is the last version that works for you?

(Could you also try to delete the `.next` folder between installs to make sure nothing is accidentally wrongly cached?)

You can install specific versions like this `npm i next@12.1.4` or in case of canary releases `npm i next@12.1.5-canary.0`.

See a list of all the available releases here: https://github.com/vercel/next.js/tags

**Comment by TylerAPfledderer** [comment]
@balazsorban44 I have a project that I have had for at least a month with `next@12.1.6` and `react/react-dom@18.2.0` that runs with no issue.

However, I build a brand new app with `next@12.2.2` and I receive the error described. Both have a project path with the word `next` in it. I revert next back to 12.1.6 in this new project, and the error still occurs. Both projects live in the same directory.

OS: Windows 11
NodeJS: 16.15.1

**Comment by JanKaifer** [comment]
@TylerAPfledderer Could you try pinpointing the exact `canary` that breaks things?
Also, don't forget to delete `.next`.

**Comment by abhijithp05** [comment]
@JanKaifer is this still open?

**Comment by simobuilds** [comment]
I had the same kind of issue when next start or next build wouldn't work, I tried npm run dev and it worked fine! Using Ubuntu Linux next@13.4.6

**Comment by samcx** [comment]
Closing this since this has become stale with no response!
