### ISSUE TITLE
how can i query by height image next/image

### ISSUE THREAD

**Issue by Musho0** [vercel/next.js#36250]
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

 Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

i need to query image by height on next/image 
our cdn works like this
example` https://example.com/image.jpg?ssl=1&h=200

### Expected Behavior
or was it possible to remove the **w** parameter,
I couldn't find anywhere how to do it, please help

**Comment by timneutkens** [comment]
Only width is supported.
