### ISSUE TITLE
Compilation performance regression (Next 12.1.1 onwards)

### ISSUE THREAD

**Issue by hanford** [vercel/next.js#36260]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Mac OS 12.3.1 / Apple M1 Max
Next.js 12.1.1+
swc/swcMinifier/relay SWC integration enabled

Next config looks like this:
```height=100
module.exports = {
  swcMinify: true,
  experimental: {
    // allowing import typescript from outside of the rootDir (dazzle-types)
    // https://github.com/vercel/next.js/issues/9474#issuecomment-810212174
    externalDir: true,
    esmExternals: 'loose',
  },
  compiler: {
    relay,
  },
  devIndicators: {
    autoPrerender: false,
  },
  eslint: {
    // We have a separate job that will handle linting dazzle & design-system / failing the build
    // https://nextjs.org/docs/api-reference/next.config.js/ignoring-eslint
    ignoreDuringBuilds: true,
  },
  typescript: {
    // 🚨 WARN 🚨
    // We allow building dazzle with TS errors because our dazzle_tsc_check & lint_ validates types
    // https://nextjs.org/docs/api-reference/next.config.js/ignoring-typescript-errors
    ignoreBuildErrors: true,
  },
};
```

### Describe the Bug

In the latest versions of Next.js I'm experiencing significantly worse dev compilation speeds, I don't have a reproduction that I can easily share at the moment (can try to create one in a few days) but can share the relevant traces / some  information below. 

I clicked through the same click paths on both Next 12.1.5 and 12.1.0 respectively and the difference are quite noticeable. As you can see in the below screenshots some routes go from ~1.5 seconds to 17+ seconds to compile.

One thing that I'm noticing, is the compiling triangle component appears to dismiss very quickly (not sure if important or relevant):

https://user-images.githubusercontent.com/2148168/163910389-daac9f17-8e51-454b-96a6-148a3c71aeb0.mov

Trace from above video:
[12.1.1-trace.zip](https://github.com/vercel/next.js/files/8509516/12.1.1-trace.zip)

Seems like in the latest build of Next.js, more modules are being compiled, but I'm not certain as to whether or not that's related. I'm also not certain whether or not this issue is happening in SWC or webpack land. Happy to share any more information / use certain specific versions of SWC/webpack if it'll help diagnose. 

On Next.js 12.1.5+:
<img width="400" alt="Screen Shot 2022-04-18 at 7 39 59 PM" src="https://user-images.githubusercontent.com/2148168/163909447-b8b7be0e-81cd-486b-a752-09ad6cfa8d73.png">

[next-12.1.6-canary.3-trace.zip](https://github.com/vercel/next.js/files/8509434/trace.zip)

On Next.js 12.1.0:
<img width="400" src="https://user-images.githubusercontent.com/2148168/163908030-38789822-9c60-43b5-a792-97befbded4e8.png">

[next-12.1.0-trace.zip](https://github.com/vercel/next.js/files/8509343/next-12.1.0-trace.zip)

We use emotion too, but I don't have any Emotion babel or SWC configurations, only the runtime pieces are used in my application.

### Expected Behavior

Ideally speeds would be the same or faster!

### To Reproduce

I don't have a reproduction that I can share at the moment, but might have some time to come up with one.

**Comment by timneutkens** [comment]
> I clicked through the same click paths on both Next 12.1.5 and 12.1.0 respectively and the difference are quite noticeable. As you can see in the below screenshots some routes go from ~1.5 seconds to 17+ seconds to compile.

The included trace are version 12.1.0 and 12.1.1 (instead of 12.1.5) and the 12.1.1 trace seems to only have compiled 2 pages compared to 12 pages in the 12.1.0 run.

Sent you a dm to get some code snippets to run traces on with swc.

**Comment by hanford** [comment]
Sorry for the confusion the more useful trace is in the middle of the above issue: [next-12.1.6-canary.3-trace.zip](https://github.com/vercel/next.js/files/8509434/trace.zip)

**Comment by samcx** [comment]
@hanford Hi there!

It looks like we never followed up on this. Can you confirm if this is still an issue?

**Comment by samcx** [comment]
Closing this since this issue has become stale!
