### ISSUE TITLE
Docs: React 18 + _document.getInitialProps double-render issue

### ISSUE THREAD

**Issue by Andarist** [vercel/next.js#36268]
### What is the improvement or update you wish to see?

Emotion maintainer here 👋 

We got an issue report about a change in behavior with React 18 and Next.js [here](https://github.com/emotion-js/emotion/issues/2725#issuecomment-1100983035). I've managed to diagnose this a little bit and it seems that the issue is, at least partially, related to:
1. hitting a React 18 code branch [here](https://github.com/vercel/next.js/blob/4a8a3d2400a54448b615fbc75cd91ca8cfea256c/packages/next/server/render.tsx#L1424-L1427) that is supposed to render the shell early to the stream
2. calling the provided `_document.getInitialProps` later on [here](https://github.com/vercel/next.js/blob/4a8a3d2400a54448b615fbc75cd91ca8cfea256c/packages/next/server/render.tsx#L1496-L1498)

This creates a "double render" of sorts and the first render is not wrapped/enhanced with the Emotion's `CacheProvider` as that is used in the `_document` ([here](https://github.com/garronej/ssr-react-18-next/blob/3b6fda6292eb46a8a23dea64d8dac4f151b1bce3/src/pages/_document.tsx#L66-L69)).

I've looked through the docs but I'm not sure how to reliably wrap the whole app with a component. Using `_document.getInitialProps` is recommended by the Material UI team to be compatible with SSG, see [here](https://github.com/mui/material-ui/blob/b3645b3fd11dc26a06ea370a41b5bac1026c6792/examples/nextjs/pages/_document.js#L31-L32)

### Is there any context that might help us understand?

No further context, everything was put in the main description of the issue.

**Comment by HaNdTriX** [comment]
https://github.com/vercel/next.js/issues/36229

**Comment by himadrinath** [comment]
looks like the problem arrived again in canary release.
can any one confirm that
