### ISSUE TITLE
Server side rendering for styled-jsx not working when using pnpm 

### ISSUE THREAD

**Issue by ivandotv** [vercel/next.js#36287]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

   Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Wed Apr 13 22:09:20 UTC 2022
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.15
      pnpm: 7.0.0-rc.6
    Relevant packages:
      next: 12.1.6-canary.4
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

`styled-jsx` is not creating server-side styles. 
This happens **only** when using `pnpm` as package manager.
Obviously, something weird is happening because of how `pnpm` is resolving the dependencies.

### Expected Behavior

Server-side styles should be created.

### To Reproduce

1. Check out the official example [with-styled-jsx](https://github.com/vercel/next.js/blob/canary/examples/with-styled-jsx/README.md)
2. Use `pnpm` to set up the project.
3. build the project.
4. start the project
5. disable javascript in the browser and visit the example.

unstyled content will be shown.

**Comment by huozhi** [comment]
We improved the support of styled-jsx in next.js for pnpm/yarnPnP in `next@12.1.6-canary.16`, could you give it a try to see if it fix your problem?
