### ISSUE TITLE
middleware: `req.headers.get('host')` is different for a page then api

### ISSUE THREAD

**Issue by maapteh** [vercel/next.js#36303]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

When im using the `req.headers.get('host')` in my middleware it gives two values, depending if it's a page or api. 

So my app runs on `http://nl.brand.test:3001` 
Then `req.headers.get('host')` for the page returns `[ 'nl.brand.test:3001' ]`. 
But for the api requests it is: `[ 'localhost:3001' ]`.

### Expected Behavior

I hoped to rely on the host to do my logic and for both would be the same. Now i have to use some logic on the revalidate part which logs the wrong hostname. Well for me wrong :)

### To Reproduce

Run the middleware example and log the host from the request. Request a page, and an api endpoint (api endpoint im working on is [revalidate](https://nextjs.org/blog/next-12-1#on-demand-incremental-static-regeneration-beta))

**Comment by ijjk** [comment]
Hi, is the API route being requested in the same way as the page? The host will be specific to the host that was requested e.g. `fetch('localhost:3001')` is expected to have a different host than `fetch('nl.brand.test:3001')`.

**Comment by javivelasco** [comment]
I believe this is exactly the same as [this one](https://github.com/vercel/next.js/issues/36625#issuecomment-1159103823). I've explained there the reasoning behind this and we can keep talking about it in [this other issue](https://github.com/vercel/next.js/issues/37536) where there is already conversation around this topic.

If this is a different issue, please feel free to reopen!
Thanks for reporting!
