### ISSUE TITLE
Example with-docker doesn't work

### ISSUE THREAD

**Issue by amatiasq** [vercel/next.js#36344]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

The module 'react' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react'
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react-dom'

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 12.1.5
      react: N/A
      react-dom: N/A

warn  - Failed to fetch latest canary version. Visit https://github.com/vercel/next.js/releases. Detected "12.1.5".
      Make sure to try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
      Read more - https://nextjs.org/docs/messages/opening-an-issue

### Which example does this report relate to?

https://github.com/vercel/next.js/tree/canary/examples/with-docker

### Describe the Bug

When I run the first command in the README it says `with-docker` is not found

```
❯ npx create-next-app --example with-docker nextjs-docker
Could not locate an example named "with-docker". It could be due to the following:
 1. Your spelling of example "with-docker" might be incorrect.
 2. You might not be connected to the internet.
```

### Expected Behavior

I will have the working example in my local environment as the README says

### To Reproduce

run
```
npx create-next-app --example with-docker nextjs-docker                                                                                                                                                                   ```

**Comment by timneutkens** [comment]
From the looks of it something in your networking layer is blocking `fetch()` to GitHub 🤔

**Comment by amatiasq** [comment]
I have other node applications connected to Github API without issue and tens of repositories cloned from Github.

Does this command work in your local?

**Comment by balazsorban44** [comment]
Yes, it works correctly. Could you test it on a different device/network to rule out network issues?

**Comment by balazsorban44** [comment]
We can show the exact network error for you (see https://github.com/vercel/next.js/pull/36567), but this is some kind of configuration on your computer, not a Next.js bug, so I'm closing this. Check if there are some proxy settings or similar blocking requests to GitHub.
