### ISSUE TITLE
Next build is trying to type check .ts dependencies 

### ISSUE THREAD

**Issue by Southclaws** [vercel/next.js#36346]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: N/A
      react-dom: N/A
```

### Describe the Bug

It seems Next.js is trying to type check dependencies, the problematic one is Nativebase:

```
Failed to compile.

../node_modules/native-base/src/hooks/useContrastText.ts:1:19
Type error: Could not find a declaration file for module 'tinycolor2'. '/Users/southclaws/Work/odin/odin/node_modules/tinycolor2/tinycolor.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/tinycolor2` if it exists or add a new declaration (.d.ts) file containing `declare module 'tinycolor2';`

> 1 | import Color from 'tinycolor2';
    |                   ^
  2 | import { useToken } from './useToken';
  3 | import { useAccessibleColors } from '../core/color-mode/hooks';
  4 | import { useNativeBaseConfig } from '../core/NativeBaseContext';
info  - Checking validity of types .task: Failed to run task "web-build": exit status 1
```

This isn't happening on our master branch and the only differences between the failing branch and master is .tsx/.ts changes, no changes to the Next.js versions or Nativebase version or tsconfig.

Very confusing this one and I don't know where to look, is it Next.js causing the problem or TypeScript or Nativebase?

### Expected Behavior

Not to throw type errors for .ts files in node_modules

### To Reproduce

Closed source so can't share the code, I can put together a repro but it'll take a while and will have to prioritise other work tasks until I get time.

**Comment by Southclaws** [comment]
Some more info we discovered:

- I tried to remove all imports of the offending file (useContrastText) and it still fails
- next dev works fine, only build fails (because I guess it doesn't do type checking for dev)
- adding `declare module "tinycolor2"` just drops to the next type error in that file

**Comment by timneutkens** [comment]
Can you try running `yarn tsc` or `npx tsc`?

**Comment by barrymichaeldoyle** [comment]
Getting the same issue, running `yarn tsc` just tells me there's a bunch of type errors inside my `node_modules`. I've got `tsconfig` setup to `skipLibCheck` and `exclude` `node_modules`.

**Comment by Southclaws** [comment]
I figured it out, there was one single import buried in _our_ codebase that was importing from `native-base/src`.

I think this happened because vscode indexes *everything* so when you type a function name and hit import, it just rolls a dice to pick which import it adds. In this case, it added the /src/ path instead of the correct path.
