### ISSUE TITLE
Docs: How to configure Next 12 linting in VSCode

### ISSUE THREAD

**Issue by morkeleb** [vercel/next.js#36343]
### What is the improvement or update you wish to see?

I'd like to see an instruction of how to get next lint results to show inside the VS code editor.
For Next 12, but still using the SWC compiler.

### Is there any context that might help us understand?

I've been trying to get the linting to work inside VSCode for about a month now since upgrading to Next 12.

I don't want to opt out of using the SWC compiler, not even in my development flow. But I can't get VSCode to lint Next in the editor as I need the .eslint.conf and a babel.conf file (or so most documentation is guiding me to)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/eslint

**Comment by jacklimwenjie** [comment]
I have the exact same question, have been fiddling in VsCode for awhile now but couldn't get it to lint on-the-fly properly in the editor.

**Comment by vadymshymko** [comment]
Hi, there! Please, take a look [eslint docs](https://eslint.org/docs/user-guide/integrations#editors) about integration. If we are talking about vscode, I recommend using [this](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) plugin
