### ISSUE TITLE
pnpm create Unknown option: 'typescript'

### ISSUE THREAD

**Issue by SimonBerens** [vercel/next.js#36360]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.5
      react: 18.0.0
      react-dom: 18.0.0

### Describe the Bug

Running `pnpm create next-app -- --typescript`
```
 ERROR   ERROR  Unknown option: 'typescript'
For help, run: pnpm help create
```

(similarly for `--ts`)

When I log into WSL and run the command, it works as expected.

`pnpm create next-app` works as expected.

### Expected Behavior

I am prompted for project configuration.

### To Reproduce

`pnpm create next-app -- --typescript`

**Comment by balazsorban44** [comment]
I could not reproduce this. :thinking: You might want to update `pnpm`, or open an issue with them.

Interestingly, your `next info` returns `pnpm: N/A`. :thinking: Did you run the command the place where you tried `pnpm create`?

**Comment by AndreaGero** [comment]
I Have the same error running `pnpm create next-app -- --typescript` on Windows 11:

```
ERROR   ERROR  Unknown option: 'typescript'
For help, run: pnpm help create
```

**Comment by balazsorban44** [comment]
It still works for me even with pnpm@7. :thinking:

I don't think it's a Next.js-specific issue. For some reason, pnpm does not recognize that the typescript flag was passed as an argument to `next-app` on Windows.

**Comment by ffaanngg** [comment]
Facing the same issue on Windows 11 with pnpm v7.0.1

**Comment by zkochan** [comment]
@ffaanngg you probably use PowerShell, in that case you need to escape `--`:

```
pnpm create next-app `-- --typescript
```

Also, it looks like there is an issue with pnpm as well because I think `pnpm create next-app --typescript` should work.

**Comment by ffaanngg** [comment]
@zkochan That appears to have fixed it. Thanks.
