### ISSUE TITLE
`x-middleware-next` header causes CORS preflight malfunction in Middleware

### ISSUE THREAD

**Issue by youminkim** [vercel/next.js#36377]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 14.17.1
      npm: 6.14.13
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.5
      react: 17.0.2
      react-dom: 17.0.2

✨  Done in 1.73s.

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

We are testing CORS preflight request with Milddleware based on [this example](https://github.com/vercel/examples/tree/main/edge-functions/cors)

We expect response `204` response from middleware because of [this OPTIONS method handing](https://github.com/vercel/examples/blob/main/edge-functions/cors/lib/cors.ts#L144). However, it responds `400` response which is the result of the actual api route. 

I found that `x-middleware-next` made the malfunction.  I removed the header in [cors.ts](https://github.com/vercel/examples/blob/main/edge-functions/cors/lib/cors.ts#L144) and it started working properly. 

```
     headers.delete('x-middleware-next')
```

### Expected Behavior

`204` response for CORS preflight request

### To Reproduce

https://github.com/vercel/examples/tree/main/edge-functions/cors

```
import type { NextRequest } from 'next/server'
import cors from '../lib/cors'

export function middleware(req: NextRequest) {
  // `cors` also takes care of handling OPTIONS requests
  return cors(
    req,
    NextResponse.next(),
  )
}
```

Add `/api/connect` route 

Example preflight request
```
OPTIONS http://localhost:3000/api/connect HTTP/1.1
Access-Control-Request-Method: POST
Access-Control-Request-Headers: origin, x-requested-with
Origin: http://localhost:3000
```

**Comment by javivelasco** [comment]
We recently refactored Middleware to get rid of the Preflight protocol so this shouldn't be an issue anymore. Now we get the effects from data requests that work with GET and your infra should be configured to support it as it is required for SSR. Therefore I'm going to close this issue, thanks for reporting 🙏 !
