### ISSUE TITLE
Styled components CSS prop is not applied when using SWC

### ISSUE THREAD

**Issue by hmps** [vercel/next.js#36380]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #29~20.04.1-Ubuntu SMP Thu Apr 14 23:15:00 UTC 2022
    Binaries:
      Node: 12.22.10
      npm: 6.14.16
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.5
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

Using SWC and styled components, styles defined with a [css prop](https://styled-components.com/docs/api#css-prop) are not applied. In this example:

```
const StyledParagraph = styled.p`
  background: rebeccapurple;
  color: white;
  padding 12px;
`;

export default function Home() {
  return (
    <>
      <StyledParagraph>Hej</StyledParagraph>
      <p
        css={`
          background: rebeccapurple;
          color: white;
		  padding 12px;
        `}
      >
        hello
      </p>
    </>
  );
}
```

`<StyledParagraph />` is correctly styled, while `<p />` is not styled at all.

🙇‍♂️

### Expected Behavior

I expected tags with a css prop to be styled with the defined style. See working example (with Babel) on https://replit.com/@hmps/Next-with-css-prop-and-babel#pages/index.jsx

### To Reproduce

https://replit.com/@hmps/NextJS-with-SWC-and-css-prop

**Comment by timneutkens** [comment]
See #30802
