### ISSUE TITLE
Should not scroll

### ISSUE THREAD

**Issue by hdJerry** [vercel/next.js#36447]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

unable to achieve this

### How are you deploying your application? (if relevant)

Application is ran on codesandbox

### Describe the Bug

When i use `scroll=false` on the Link or as part of the `router.push or router.replace options`, it still scroll. Also adding `shallow=true` will prevent the url from updating

### Expected Behavior

I expect that it shouldn't scroll
based on [disable-scrolling-to-the-top-of-the-page](https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page).

### To Reproduce

To reproduce i tried using 2 use cases
- one with the Link
- the other with router itself
recreated [code](https://codesandbox.io/s/should-not-scroll-ws61sr?file=/pages/index.js);

**Comment by kallelat** [comment]
I'm having the same issue with my code, I have a linear flow in my app and I use router.push(...) to navigate forward in the flow.

All navigations are handled by the same function, which basically only does this:
router.push(nextUrl, undefined, { scroll: false });

In most of the cases it works fine and users scroll position is kept, but in some cases it scrolls to the top.

Any updates on this one?

**Comment by christiankaindl** [comment]
Having the same issue on my Next.js 12.3 site. `scroll: false` is simply broken with hashes...

Reproduction: https://stackblitz.com/edit/nextjs-xsxkka?file=pages/index.js

As noted, `scroll: false` should prevent scrolling to the hash. From [the docs](https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page):
> To prevent scrolling to the top / hash `scroll={false}` can be added to `Link`

**Comment by lacymorrow** [comment]
Same issue in v13

**Comment by thexpand** [comment]
The issue still persists in v13. By clicking on a `Link` with `scroll={false}` for the first time, it scrolls to the top. Any consequent clicks on other `Link`s with `scroll={false}` do not scroll to the top.

**Comment by valse** [comment]
Hi, I have the same issue but in `development` it works like expected: on click don't scroll to top... published on Vercel it stopping to work.

**Comment by EthanStandel** [comment]
The current docs specifically for the app router imply that this should now work, but it doesn't seem to work in either dev or prod with @latest or @canary.
 
https://nextjs.org/docs/app/api-reference/components/link#disable-scrolling-to-the-top-of-the-page

**Comment by tquann286** [comment]
Any update on this? I have the same issue in Next App router

**Comment by EthanStandel** [comment]
> Any update on this? I have the same issue in Next App router

Weirdly, they're not in the opposite state that they were in when I commented. They fixed the docs to not have `scroll={false}` but then they added it went never added back the docs. So you should be able to add that option to your links and navigations now.

**Comment by samcx** [comment]
@hdJerry I am currently seeing the correct scrolling behavior on backward + forward navigation for `true` and `false`!

I will be closing this issue. If you are not seeing the correct behavior, please feel free to push up a new [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml)

- https://nextjs.org/docs/pages/api-reference/components/link#scroll
