### ISSUE TITLE
Cannot export page config from a function

### ISSUE THREAD

**Issue by alii** [vercel/next.js#36476]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
# ali @ trackpad in ~/code/v3 on git:master x [12:45:21]
$ yarn next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.0.0
      npm: 8.6.0
      Yarn: 3.1.1
      pnpm: 7.0.0-rc.2
    Relevant packages:
      next: 12.1.6-canary.7
      react: 18.0.0
      react-dom: 18.0.0
```

### What browser are you using? (if relevant)

100.0.4896.127 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

`yarn next dev`

### Describe the Bug

Cannot export a page config that comes from an externally defined function

### Expected Behavior

The page config works as expected

### To Reproduce

I have this function that is enabling us to write page config's more quickly with some default values and expected it to work just fine, however Next is reporting that I have "Invalid page config export found. Expected config to be an object"

<img width="708" alt="image" src="https://user-images.githubusercontent.com/25351731/165293126-b038e22c-6a92-4634-a47a-99ee3fec5e1b.png">

Calling the function as follows:
```ts
import {pageConfig} from '../server/pages';

export const config = pageConfig();

export default function Home() {
	return <>{Date.now()}</>;
}
```

**Comment by balazsorban44** [comment]
The error thrown `Invalid page config export found. Expected config to be an object` should link to this page https://nextjs.org/docs/messages/invalid-page-config which explains:

> The page's config must be an object initialized directly when being exported and not modified dynamically.
