### ISSUE TITLE
Font optimization corrupts Google Fonts link

### ISSUE THREAD

**Issue by Tadynas** [vercel/next.js#36498]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 14.17.4
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.9
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

[Font optimization](https://nextjs.org/docs/basic-features/font-optimization) function corrupts font link and does not convert `<link>` fully into `<style>` tag.  Therefore, fonts are not loaded in production and only way to load them is to disable font optimization

Before the build
```
<link
  href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
  rel="stylesheet"
/>
```

After the build
```
<link
  data-href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
  rel="stylesheet"
/>
```

### Expected Behavior

It should convert `<link>` to `<style>` tag

```
// Before
<link
  href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
  rel="stylesheet"
/>

// After
<style data-href="https://fonts.googleapis.com/css2?family=Inter&display=optional">
  @font-face{font-family:'Inter';font-style:normal...
</style>
```

### To Reproduce

1. Add _document.js file to pages folder. I'm using example from [Font Optimization page](https://nextjs.org/docs/basic-features/font-optimization)

```
// pages/_document.js

import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
            rel="stylesheet"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
```

2. run `yarn build`
3. run `yarn start`
4. open `localhost:3000` and inspect `<head>` with corrupted `<link>` tag

**Comment by fadhilx** [comment]
I confirmed this, for me it happen after I publish to server. probably because of production environment or because of build.

**Comment by garganurag89** [comment]
Facing the same issue

**Comment by SalahAdDin** [comment]
I confirm this, and it is happening in development environment(without build), actually, I opened a [discussion](https://github.com/vercel/next.js/discussions/36756) about this.

**Comment by cleberj** [comment]
Seems like https://github.com/vercel/next.js/blob/4fb0beb1ee372d56128db16ec02ff88e333d4b2a/packages/next/server/render.tsx#L1310
we always have generateStaticHTML as false.
![image](https://user-images.githubusercontent.com/69492574/167339219-04005d3b-fa56-4286-ba0b-7e1c75c7442b.png)

Hence the processors never work for ssr:

![image](https://user-images.githubusercontent.com/69492574/167339343-2d589dfe-cfea-4a9e-8f3a-3076b84609dd.png)


There were some commits 3 months ago regarding this. Not sure if that is what make SSR stop working. I change the code manually to start as TRUE, and the web optimizations started working again.

**Comment by SalahAdDin** [comment]
> Seems like
> 
> https://github.com/vercel/next.js/blob/4fb0beb1ee372d56128db16ec02ff88e333d4b2a/packages/next/server/render.tsx#L1310
> 
> 
> we always have generateStaticHTML as false.
> ![image](https://user-images.githubusercontent.com/69492574/167339219-04005d3b-fa56-4286-ba0b-7e1c75c7442b.png)
> Hence the processors never work for ssr:
> 
> ![image](https://user-images.githubusercontent.com/69492574/167339343-2d589dfe-cfea-4a9e-8f3a-3076b84609dd.png)
> 
> There were some commits 3 months ago regarding this. Not sure if that is what make SSR stop working. I change the code manually to start as TRUE, and the web optimizations started working again.

I guess it could be, cause it is not working for me with the last **NextJS** version.

**Comment by conioX** [comment]
same with me  "next": "12.1.6"

**Comment by conioX** [comment]
any news or how to fix this issue?

**Comment by SalahAdDin** [comment]
> any news or how to fix this issue?

It seems there is no solution yet.

**Comment by Zharkan** [comment]
It's been fixed, wait for 12.1.7 if you can't go canary.

**Comment by BinaryJim** [comment]
Any update on this? 

I'm also unable to get Google Fonts to load in development or production, unless I change the `display` value from `optional` to `swap`.

**Non working:**
```html
<link href="https://fonts.googleapis.com/css2?family=Inter&display=optional" rel="stylesheet"/>
```

**Working:**
```html
<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet"/>
```

**Comment by timneutkens** [comment]
Font optimization has been superseded by `next/font` which doesn't have this issue: https://nextjs.org/docs/app/building-your-application/optimizing/fonts#google-fonts
