### ISSUE TITLE
Dynamic Routing: Head scripts from nested function are missing

### ISSUE THREAD

**Issue by nitz-iron** [vercel/next.js#36508]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.9.0
      npm: 8.5.5
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.9
      react: 18.1.0
      react-dom: 18.1.0

```

### What browser are you using? (if relevant)

Google Chrome 100.0.4896.127

### How are you deploying your application? (if relevant)

i've provided an example 

### Describe the Bug

When using next/head inside dynamic route, scripts tag from nested function is not being rendered.

1. clone: https://github.com/nitz-iron/next-dynamic-route-head
2.  npm start dev
3. in path enter: /<some-id>
4. Inspect html head, only script "one" is included while "two", "three" and "four" aren't.

![image](https://user-images.githubusercontent.com/93871534/165514009-bfd53499-8dd5-44e6-be20-1ea6c8ef9875.png)

### Expected Behavior

All the script are included in the head, even those from nested function (=getLevel2Scripts)

### To Reproduce

When using next/head inside dynamic route, content from nested function is not being rendered.

1. clone: https://github.com/nitz-iron/next-dynamic-route-head
2.  npm start dev
3. in path enter: /<some-id>
4. Inspect html head, only script "one" is included while "two", "three" and "four" aren't.

**Comment by timneutkens** [comment]
This is expected as per the docs of `next/head`: https://nextjs.org/docs/api-reference/next/head

> title, meta or any other elements (e.g. script) need to be contained as direct children of the Head element, or wrapped into maximum one level of <React.Fragment> or arrays—otherwise the tags won't be correctly picked up on client-side navigations.

**Comment by nitz-iron** [comment]
Thanks for the quick response.
Can this be suggested as a feature?
also, from curiosity, why it happens?
