### ISSUE TITLE
creating a new Request from an existing object does not keep the request's method

### ISSUE THREAD

**Issue by gazs** [vercel/next.js#36522]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.7.0
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

1. when creating a Request object from an existing Request object using the polyfill, the method is not copied over

```js
const request = new Request('http://example.com', { method: 'POST', body: 'hello'})
const request2  = new Request(request)
```

throws: `TypeError: Request with GET/HEAD method cannot have body`

this is because the polyfill takes method from the optional `init` parameter of Request#constructor: https://github.com/vercel/next.js/blob/842e4ec02381234bdea82a9c95e75cc79e211a09/packages/next/server/web/spec-compliant/request.ts#L19-L26

2. when fetching a Request object in a _middleware, the method is ignored:

```js
const request = new Request('http://example.com', { method: 'POST', body: 'hello'})
const response = await fetch(request)

expect(response.req.method).toEqual('POST') // <-- return 'GET'
```

https://github.com/vercel/next.js/blob/d5e767b20d06dfd625f70267b713af52917e5897/packages/next/server/web/sandbox/context.ts#L152-L173

### Expected Behavior

the expected behaviour is the `method` and any other properties are copied over to the new request object

### To Reproduce

for example in _middleware.ts:

```js
const request = new Request('http://example.com', { method: 'POST', body: 'hello'})
const request2  = new Request(request)
request2.method === 'POST'
```

**Comment by ambrauer** [comment]
We are experiencing this as well. A simple repro we have in a `_middleware.ts`:

```javascript
import { NextResponse } from 'next/server';

export default async function () {
  const ok = await fetch('https://httpbin.org/post', {
    method: 'POST',
    body: 'test',
  });
  console.log(ok); // <-- 200 OK

  const fails = await fetch(
    new Request('https://httpbin.org/post', {
      method: 'POST',
      body: 'test',
    })
  );
  console.log(fails); // <-- 405 METHOD NOT ALLOWED (GET is sent)

  return NextResponse.next();
}
```
