### ISSUE TITLE
Docs: How to override default PostCSS behavior?

### ISSUE THREAD

**Issue by djboris88** [vercel/next.js#36544]
### What is the improvement or update you wish to see?

How to customize Next.js or turn off the default PostCSS behavior?

I am trying to turn off the post-processing of the `font-variant` property, but without any success.

### Is there any context that might help us understand?

I am trying to set styling for an element to `font-variant: initial`, and it works during the development with `next dev`. But in production, or when I do `next build && next start`, it gets overridden with `font-variant: normal`, no matter what I do.

I tried setting my `postcss.config.json` like this (and many other combinations) but without any success:

    {
        "plugins": [
            "postcss-flexbugs-fixes",
            [
                "postcss-preset-env",
                {
                    "autoprefixer": {
                        "flexbox": "no-2009"
                    },
                    "stage": 4,
                    "features": {
                        "custom-properties": false,
                        "font-variant-property": false
                    }
                }
            ]
        ]
    }

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/customizing-postcss-config

**Comment by leerob** [comment]
Hmm, this should work: https://nextjs.org/docs/pages/building-your-application/configuring/post-css#customizing-plugins

If you are still seeing issues, please open a new issue with a reproduction 🙏
