### ISSUE TITLE
Cannot run latest Next.js in Docker

### ISSUE THREAD

**Issue by iMerica** [vercel/next.js#36553]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Docker:
Docker version 20.10.14, build a224086

Next: "12.1.5"

### How are you deploying your application? (if relevant)

Docker

### Describe the Bug

Cannot run Next.js in Docker or in any Cloud Native style using containers. 

### Expected Behavior

I expect dependencies to be explicit and next.js to build in Docker

### To Reproduce

**Steps to Reproduce**

Generate a new Next.js project using Next.js

    npx create-next-app@latest

Create a Dockerfile
```
FROM node:14-buster-slim
WORKDIR /app
COPY package*.json ./
RUN yarn add -D @swc/cli @swc/core
RUN yarn install
COPY . .
CMD yarn run dev
```

Run this container locally in Docker:

```
$ docker-compose up -d
....
next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /app/.env
info  - Attempted to load @next/swc-linux-x64-gnu, but it was not installed
info  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
info  - Attempted to load @next/swc-linux-x64-musl, but it was not installed
error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timjanssen95** [comment]
Hi iMerica!

I would recommend to take a look at the new standalone feature announced in NextJS 12.1. It will reduce your Docker image drastically. 

Docs: https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files-experimental

There are also example Dockerfiles available in two flavours:
- Single env: https://github.com/vercel/next.js/tree/canary/examples/with-docker
- Multi env: https://github.com/vercel/next.js/tree/canary/examples/with-docker-multi-env

I hope this helps out!

Kind regards,
Tim Janssen
