### ISSUE TITLE
"Runtime" configuration variables are baked in at compile time when using standalone as target

### ISSUE THREAD

**Issue by SoftMemes** [vercel/next.js#36551]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 3.2.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.13
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

I'm leveraging the standalone target (outputStandalone: true) in order to create a self contained build suitable for use in Docker. While I do get an output application, this does not appear to play nice with runtime configuration.

I understand that normally in Next, access to process.env is resolved at build time, but it is possible to inject runtime configuration by accessing process.env (or through other means) in next.config.js.

When using the standalone build however, the config form next.config.js appears to be baked into the generated server.js file, meaning any environment variables set at runtime (such as through the Docker configuration) are ignored.

### Expected Behavior

Config is read by evaluating next.config.js (or the original content of it) at runtime when initializing the next standalone server.

### To Reproduce

- Populate publicRuntimeConfig or serverRuntimeConfig in next.config.js from environment variables via process.env
- Build the site with "standalone" enabled
- Set environment variables at runtime
- Observe that the runtime values are not being used

**Comment by balazsorban44** [comment]
An explanation to this has been given here: https://github.com/vercel/next.js/issues/33910#issuecomment-1028081728

You could also simply use `process.env.MY_VARIABLE` and set them in your environment or add them through a .env file. Anything that is not prepended with `NEXT_PUBLIC_` will be server-side only and won't be exposed to the client.

**Comment by SoftMemes** [comment]
Thank you for the reply, the thread that you referenced is very relevant indeed.

There's some confusion still on my side which may simply be an issue with the documentation. According to https://nextjs.org/docs/basic-features/environment-variables

```
 In order to keep server-only secrets safe, Next.js replaces process.env.* with the correct values at build time.
```

I've taken this to mean that _all_ process.env variables are baked in at build time.

Additionally, while the process.env at runtime works for the server side configuration, it does not allow for runtime modification of client side config parameters, which was the original reason for my using this pattern. This model is also suggested in the documentation on runtime configuration: https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration

**Comment by balazsorban44** [comment]
I agree, the docs could be more clear about that. :+1:

Runtime configuration on client-side comes with the penalty of not being able to statically optimize the page ([described here](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration)), so it would be good to know your use case.

Are you trying to serve content based on the user request/other dynamic parameters?

**Comment by SoftMemes** [comment]
Thank you for the reply. My use case is to be able to build a docker image once, then run it across our different environments (development, staging, production). For the clientside, the bits that differ are only some URLs such as the domain used for API calls, some environment specific details passed to Sentry for error reporting, to Google Analytics, etc.

I appreciate that the most performant way of doing this would be to build an image per environment, though I'd like to avoid it if possible as no other parts of the system works in this way, e.g. backend services are all built once, then simply fired up in an environment and tweaked via environment variables.

When I've done this with "traditional" react projects, I've injected a single dynamic config file loaded once on startup of the SPA. I suppose it would be possible to do this also with Next and wrap each client page in a component that reads (and if needed caches) the config with a regular REST call, and have a single dynamic API endpoint depend on environment variables on the server.

**Comment by balazsorban44** [comment]
This request sounds like what @leerob concluded here as well: https://github.com/vercel/next.js/pull/35820#issuecomment-1089106426

**Comment by SoftMemes** [comment]
Agreed, this looks like the same type of use case.

**Comment by merlindru** [comment]
> There's some confusion still on my side which may simply be an issue with the documentation. According to https://nextjs.org/docs/basic-features/environment-variables
> 
> ```
>  In order to keep server-only secrets safe, Next.js replaces process.env.* with the correct values at build time.
> ```
> 
> I've taken this to mean that _all_ process.env variables are baked in at build time.

Just ran into this as well! Thank you for making this clear @balazsorban44
