### ISSUE TITLE
Cannot find module '/.next/server/pages/_error.js'

### ISSUE THREAD

**Issue by mojtaba-hajishah** [vercel/next.js#36583]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

I get this issue from sentry in production. Is there a way to fix this?

```
Error: Cannot find module '/home/panel/panel/.next/server/pages/_error.js'
Require stack:
- /home/panel/panel/node_modules/next/dist/server/require.js
- /home/panel/panel/node_modules/next/dist/server/next-server.js
- /home/panel/panel/node_modules/next/dis...
  File "node:internal/modules/cjs/loader", line 933, col 15, in Module._resolveFilename
  File "/home/panel/panel/node_modules/next/dist/build/webpack/require-hook.js", line 183, col 28, in Function.mod._resolveFilename
    return resolveFilename.call(mod, request, parent, isMain, options);
  File "node:internal/modules/cjs/loader", line 778, col 27, in Module._load
  File "node:internal/modules/cjs/loader", line 1005, col 19, in Module.require
  File "node:internal/modules/cjs/helpers", line 102, col 18, in require
  File "/home/panel/panel/node_modules/next/dist/server/require.js", line 47, col 12, in Object.requirePage
    return require(pagePath);
  File "/home/panel/panel/node_modules/next/dist/server/load-components.js", line 58, col 23, in Object.loadComponents
    (0, _require).requirePage(pathname, distDir, serverless),
  File "/home/panel/panel/node_modules/next/dist/server/next-server.js", line 444, col 63, in NextNodeServer.findPageComponents
    const components = await (0, _loadComponents).loadComponents(this.distDir, pagePath, !this.renderOpts.dev && this._isLikeSer {snip}
  File "/home/panel/panel/node_modules/@sentry/nextjs/dist/utils/instrumentServer.js", line 223, col 55, in NextNodeServer.<anonymous>
    return [2 /*return*/, origMethod.call.apply(origMethod, tslib_1.__spread([this, parameterizedPath], args))];
  File "/home/panel/panel/node_modules/tslib/tslib.js", line 141, col 27, in step
    op = body.call(thisArg, _);
```

### Expected Behavior

Not getting this issue.

### To Reproduce

Nothing.

**Comment by ducdev** [comment]
I've bumped into the same issue, here are steps for reproduction:
- On your local nextjs development (next 12.1.5 and custom server express)
- npm run build
- npm start
- Keep it running, open a new tab of terminal and npm run build
- Once it starts building we will see the "Internal Server Error" on the browser tab and the console of the running one will show 
something similar to `Cannot find module '/.next/server/pages/_error.js'`

**Comment by balazsorban44** [comment]
That is kind of expected. The `.next` folder is being regenerated because of the build, so files can go missing while building the project.

**Comment by ducdev** [comment]
> That is kind of expected. The `.next` folder is being regenerated because of the build, so files can go missing while building the project.

If we need to achieve zero-downtime deployment using pm2 with cluster mode on a self-managed server, we don't expect this crash while building the new changes `npm run build` or `yarn build` before gratefully reloading it using `pm2 reload ecosystem.config.js`.

Downgraded to Next@10 and it's working well.

**Comment by timneutkens** [comment]
You can check the upgrading guide, it covers this exact case:
https://nextjs.org/docs/upgrading#cleaning-the-distdir-is-now-a-default

**Comment by mojtaba-hajishah** [comment]
@timneutkens 
Same as @ducdev I'm using pm2 on a self-managed server. So is there any other solution for this besides downgrading Next?

**Comment by timneutkens** [comment]
As said you can disable removing the distDir using the flag as per the upgrade guide 👍
