### ISSUE TITLE
SWC compiler syntax error in styled-components type definition

### ISSUE THREAD

**Issue by vaniyokk** [vercel/next.js#36589]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Thu Mar 31 12:27:24 UTC 2022
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 100.0.4896.127

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

I got a compilation error in components where i have specified custom props for components using styled-components.
**The issue appears in Next version 12.1.4+. 12.1.3 works fine.**

```
Server Error
ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js):
Error: 
  x Expected ',', got ';'
    ,----
 77 | shrink: boolean;
    :                ^
    `----


Caused by:
    0: failed to process input file
    1: Syntax Error
```

the code causing syntax error looks like

```
const Header = styled.header<{
  shrink: boolean;
  hidden: boolean;
  mobileView: boolean;
}>`
  background-color: ${({ theme }) => theme.newTheme.background.primaryInverse};
  height: ${({ shrink, hidden, mobileView }) => {
...
```

For some reason compiler thinks it's an object, not a type definition.

### Expected Behavior

We can successfully use type definitions for styled components.

### To Reproduce

It'll be reproduced on Next 12.1.4+ **with-styled-components** example if add typescript to it and specify custom type for styled component or DOM element.

**Comment by vaniyokk** [comment]
Any update on this? Related SWC issue marked as resolved.

**Comment by SukkaW** [comment]
What's the filename of your source file? It seems that the swc can't identify your code to be typescript.

**Comment by vaniyokk** [comment]
@SukkaW `AccountLayoutDiscover.tsx`. If I remove this code block the same error occurs in other file (probably next one getting compiled)

**Comment by SukkaW** [comment]
https://github.com/vercel/next.js/blob/2acac8ad8fcc6d2a192f0f56d09b997db638645a/packages/next/build/swc/options.js#L9-L10
https://github.com/vercel/next.js/blob/2acac8ad8fcc6d2a192f0f56d09b997db638645a/packages/next/build/swc/options.js#L16
https://github.com/vercel/next.js/blob/2acac8ad8fcc6d2a192f0f56d09b997db638645a/packages/next/build/swc/options.js#L19-L20

That's really weird. If your filename ends with `.ts` or `.tsx`, swc should be able to identify it.

**Comment by vaniyokk** [comment]
The problem is somewhere in the parser, because if I separate interface or type from Styled Component definition. like this, it works!

```
interface HeaderProps {
  shrink: boolean;
  hidden: boolean;
  mobileView: boolean;
}

const Header = styled.header<HeaderProps>`
  background-color: ${({ theme }) => theme.newTheme.background.primaryInverse};
  height: ${({ shrink, hidden, mobileView }) => {
```

But it's uncommon to use custom styled props like this. In my first example SWC wrongly treats type as an object. This is an issue.

**Comment by SukkaW** [comment]
Do you have any reproduction of the issue?

I just use `pnpx create-next-app --example with-styled-components with-styled-components-app` to create an example and add the following code:

```tsx
import styled from 'styled-components'

const Header = styled.header<{
  shrink?: boolean;
  hidden?: boolean;
  mobileView?: boolean;
}>`
  color: ${({ hidden }) => `#fff`}
`;

export default function Home() {
  return <Header>My page</Header>
}
```

It builds without errors.

**Comment by vaniyokk** [comment]
```
import styled from 'styled-components'

const Header = styled.header<{
  shrink?: boolean;
  hidden?: boolean;
  mobileView?: boolean;
}>`
  color: ${({ hidden }) => `#fff`}
  ${({ shrink, hidden }) =>
      shrink
        ? css`
            border-bottom: ${hidden ? 0 : 1}px solid
              ${({ theme }): string => theme.newTheme.background.senary};
          `
        : null};
`;

export default function Home() {
  return <Header>My page</Header>
}
```

I localized the problem. Please try exactly this code (replace theme usage by something else but preserve formatting) 
It's a wrapped line of `border-bottom` declaration. Without it, it compiles without errors but it also worked fine before next v12.1.4

The line is wrapped automatically by prettier so we have a lot of places like this in code.

**Comment by kdy1** [comment]
I used the exact input you provided, but I'm not sure what the problem is.

Do you mean it should be 

```js
import styled from 'styled-components';
const Header = styled.header.withConfig({
    displayName: "code__Header",
    componentId: "sc-198da6eb-0"
})([
    `color:`,
    ` `,
    `;`
], ({ hidden })=>`#fff`, ({ shrink, hidden })=>shrink ? css`border-bottom: ${hidden ? 0 : 1}px solid
              ${({ theme })=>theme.newTheme.background.senary};` : null);
export default function Home() {
    return <Header>My page </Header>;
}

```

instead of 

```js
import styled from 'styled-components';
const Header = styled.header.withConfig({
    displayName: "code__Header",
    componentId: "sc-198da6eb-0"
})([
    `color:`,
    ` `,
    `;`
], ({ hidden })=>`#fff`, ({ shrink, hidden })=>shrink ? css`
            border-bottom: ${hidden ? 0 : 1}px solid
              ${({ theme })=>theme.newTheme.background.senary};
          ` : null);
export default function Home() {
    return <Header>My page </Header>;
}

```
