### ISSUE TITLE
Docs: Clarify webpack requirement in MDX

### ISSUE THREAD

**Issue by thien-do** [vercel/next.js#36600]
### What is the improvement or update you wish to see?

I'd like to see clarification on the "webpack" peer dependency warning when installing mdx packages as instructed on [Using MDX](https://nextjs.org/docs/advanced-features/using-mdx) page.

### Is there any context that might help us understand?

In [Setup MDX](https://nextjs.org/docs/advanced-features/using-mdx#setup-nextmdx-in-nextjs) section, we will need to install:

```
npm install @next/mdx @mdx-js/loader
```

This will have a warning:

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @mdx-js/loader
  └── ✕ missing peer webpack@>=4
Peer dependencies that should be installed:
  webpack@>=4  
```

Afaik this is because mdx loader requires webpack as peer dep, but next.js already has webpack bundled in (not as a dependency)

Therefore I think there should be a small note to clarify that it's expected and ok to ignore?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/using-mdx#setup-nextmdx-in-nextjs

**Comment by kmin-jeong** [comment]
@thien-do I added some explanations about options in webpack requirement in MDX. I push it pr now.
I wish reviewers check to see if it has been modified to fit the context. Is that what you think?

**Comment by thien-do** [comment]
Hi @kmin-jeong , thanks for doing that :D let's wait to see if Next.js's maintainers are ok with the idea.

If the idea is good to go, I think the PR needs a bit more work, such as the wording (e.g. check for grammar or typo) and commit history (e.g. it may have a cleaner history - though not applicable if Next.js goes with a squash strategy)

**Comment by MaedahBatool** [comment]
Created a PR https://github.com/vercel/next.js/pull/39167
