### ISSUE TITLE
NextRequest url/nextUrl does not contain the same hostname as the Host header

### ISSUE THREAD

**Issue by bschoenmaeckers** [vercel/next.js#36625]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6-canary.16
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

Next start

### Describe the Bug

The url in the nextRequest argument of a middleware does not match the hostname defined in the Host header of the request.
This breaks absolute redirects when using the url as base.

### Expected Behavior

nextRequest.nextUrl.hostname should be have the hostname as defined in the host header of the request.

### To Reproduce

With the example middleware:

```
export async function middleware (req) {
console.log(req.headers.get("Host"), req.nextUrl.hostname, req.url)
}
```
and running a curl with Host header: `curl -H "Host: example.com" http://127.0.0.1:3000/api/somePath`

shows that the hostname is not the same as the host header, but instead always localhost.

**Comment by bschoenmaeckers** [comment]
Might be related to https://github.com/vercel/next.js/pull/31603

**Comment by javivelasco** [comment]
Hi! This is expected. In middleware we always want to receive a full url in the request so there must be always a hostname and when running as a Node.js server we can't get it reliably. The hostname will be certainly received as a `Host` header but we don't think it is a good default to rely on it as it can be forged in production.

If you want to write logic in a middleware that depends on the hostname while running Next.js as a self-hosted server you can always use the `Host` header if you're are sure you're behind a trusted proxy but we just don't think it is a reliable default for most setups.

This is what we do under the covers when a Next.js app is deployed to Vercel. We know it runs there and that we can trust that the `Host` header will be the actual request hostname so we use it to populate the middleware parameters. You can do the same for your self hosted app.

I'm closing this issue in favour of https://github.com/vercel/next.js/issues/37536 which already has a conversation around this topic. Thanks for reporting!
