### ISSUE TITLE
Missing @next/swc-freebsd-x64 package

### ISSUE THREAD

**Issue by alexdupre** [vercel/next.js#36639]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: freebsd
      Arch: x64
      Version: FreeBSD 13.0-RELEASE-p11 #0: Tue Apr  5 18:54:35 UTC 2022     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC
    Binaries:
      Node: 16.13.0
      npm: 8.5.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

Trying to run `next build` on FreeBSD produces the following error and the project is not built:
``` 
warn  - Attempted to load @next/swc-freebsd-x64, but it was not installed
error - Failed to load SWC binary for freebsd/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```
The issue is that such package doesn't exist, so it cannot be installed.

### Expected Behavior

The package is found and installed.

### To Reproduce

Simply try to build a next.js app on FreeBSD.

**Comment by Brooooooklyn** [comment]
@alexdupre I'll fix it

**Comment by alexdupre** [comment]
Thank you @Brooooooklyn 

Funny thing is that even the workarounds of setting `swcMinify: false` or creating the `.babelrc` file don't work.

**Comment by alexdupre** [comment]
Some additional info: both `loadNative` and `loadWasm` functions are failing, and that seems to break any workaround.
Installing `@next/swc-wasm-nodejs` allows to bypass the native failure, but the build still fails later. Using `swcMinify: false` doesn't help, same error, while creating the `.babelrc` file (together with installing swc-wasm-nodejs) works.
I guess the workarounds are not tested often.

**Comment by mantoze** [comment]
> Thank you @Brooooooklyn
> 
> Funny thing is that even the workarounds of setting `swcMinify: false` or creating the `.babelrc` file don't work.

The same problem. 
FreeBSD 13.0-RELEASE-p4.
I can't build project.
Setting swcMinify: false or creating the .babelrc file don't work.

**Comment by ismatim** [comment]
Me too, I open a discussion question in swc repository, thinking that the problem was over there, but I was redirected back here. https://github.com/swc-project/swc/discussions/4609. This was working for me till 12.1.4.

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.7-canary.5` of Next.js, please update and give it a try!

**Comment by alexdupre** [comment]
It works, thank you!
