### ISSUE TITLE
Custom server causes using old root API in React 18

### ISSUE THREAD

**Issue by yura3d** [vercel/next.js#36643]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Codesandbox

### Describe the Bug

The error message appears in browser console while running Next.js with React 18 and custom server:
```
Warning: ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17
```

### Expected Behavior

No error

### To Reproduce

Create empty Next.js project and add custom server according to docs.

Reproduced on codesandbox: https://codesandbox.io/s/next-12-1-6-react-18-1-custom-server-9blolp

**Comment by huozhi** [comment]
I [forked the CSB reproduction](https://codesandbox.io/s/next-12-1-6-react-18-1-custom-server-forked-f1hy7m?file=/package.json) but seems the issue is gone. I found the process.env is not correctly inlined in your reproduction which lead to render with the reacy 17 legacy hydration API.

Did you try to restart the server to see if the issue is gone?

**Comment by yura3d** [comment]
@huozhi Thanks for reply

> Did you try to restart the server to see if the issue is gone?

I tried CSB server restarting before creating the issue, and right now. Nothing changes.

But when I added `process.env.__NEXT_REACT_ROOT = "true"` string to `server.js` like it is done in your fork, the warning is gone.

> I found the process.env is not correctly inlined in your reproduction which lead to render with the reacy 17 legacy hydration API.

Can you tell what the variable(s) in environment leads to old root?

I see the same behavior on my PC with fresh Next.js installation by `create-next-app`, not only on CSB. And I've just noticed that downgrading to `next@12.1.5` makes the warning go away:

https://codesandbox.io/s/next-12-1-5-react-18-1-custom-server-qf2mnt
(forked the CSB in my first post, only `next` version is changed: 12.1.6 -> 12.1.5)

**Comment by huozhi** [comment]
🤦  I thought I removed the overriding process env var, which should be only used in next internally. I filed #36664 to fix it.
Sorry for the confusion...
