### ISSUE TITLE
`data-testid` being stripped in test/local env in latest 12.1.6

### ISSUE THREAD

**Issue by wadehammes** [vercel/next.js#36651]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Firefox 

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

In the latest 12.1.6, running Jest locally with tests that try to locate elements using the `data-testid` attr fail, this works fine in 12.1.5. 

In my next config I have:

```
compiler: {
    styledComponents: true,
    reactRemoveProperties: true,
  },
```

![image](https://user-images.githubusercontent.com/222170/166480517-fee520dd-c2b6-48ef-8457-fa5f5c95dca8.png)

### Expected Behavior

`data-testid` should only be removed in production env, not local or preview envs.

### To Reproduce

Create a projec with latest next, jest, and a test that looks for a `data-testid`.

**Comment by wadehammes** [comment]
Confirmed it fails in `12.1.6-canary.15`, all canaries before work fine.

**Comment by azeez1776** [comment]
Hey @timneutkens, can I work on the issue? should I change the `reactRemoveProperties` in the `test/integration/telemetry/next.config.swc` directory, I'm really new and would like to contrribute.

**Comment by wadehammes** [comment]
I'm also curious as to what in `12.1.6-canary.15` broke my tests, since all canaries before work fine. Nothing in that release looks like it would have effect on it? @timneutkens

**Comment by SukkaW** [comment]
The issue should be fixed by https://github.com/vercel/next.js/pull/36922

In the meantime, you can apply a temporary fix in your `next.config.js`:

```diff
// next.config.js
module.exports = {
  compiler: {
-   reactRemoveProperties: true
+   reactRemoveProperties: process.env.NODE_ENV === 'production'
  }
}
```
