### ISSUE TITLE
"ENOENT trying to open schema.prisma" when using pnpm, prisma.io in monoepo

### ISSUE THREAD

**Issue by orbiteleven** [vercel/next.js#36697]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.6.1
      npm: 7.20.3
      Yarn: 3.2.0
      pnpm: 7.0.0
    Relevant packages:
      next: 12.1.7-canary.1
      react: 18.0.0
      react-dom: 18.0.0
```

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

When building a Next.js application using the [Prisma.io](https://github.com/prisma/prisma), [pnpm](https://github.com/pnpm/pnpm) and a monorepo format, we're seeing that Next.js has not packaged the necessary files for Prisma.io to work. This has been cross-posted on Prisma.io [here](https://github.com/prisma/prisma/issues/12921).

### Expected Behavior

Prisma installed in another part of the monorepo should be packaged properly in the api route so it can initialize. This works with [a fork of the repo using Yarn](https://github.com/orbiteleven/prisma-yarn-workspace-test), so this seems to be something to do with how Next.js and PNPM work together.

### To Reproduce

* Git clone [this repo](https://github.com/SimonBerens/prisma-pnpm-workspace-test)
* run the following:
```bash
pnpm install
cd packages/prisma
pnpx prisma generate
cd ../../apps/frontend
pnpm run dev
```
* send a GET request to `localhost:3000/api/hello`

**Comment by balazsorban44** [comment]
This is likely a Prisma+monorepo compat upstream issue, so I'll close this for now. Let's see the outcome of https://github.com/prisma/prisma/issues/12921 first. :+1:

**Comment by orbiteleven** [comment]
That's fair enough. I figured I'd check here if there were other packages having problems as api routes using PNPM, as it could also be *how* Next.js bundles those routes.
