### ISSUE TITLE
Error when trying to import mongoose modal in middleware 

### ISSUE THREAD

**Issue by ViNoS-ab** [vercel/next.js#36701]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.1
      react: 18.0.0
      react-dom: 18.0.0

### Describe the Bug

trying to import a mongoose model even without using it throws the following error :
```cmd
error - (middleware)\node_modules\mongoose\dist\browser.umd.js (1242:0) @ <unknown>
ReferenceError: regeneratorRuntime is not defined
null
```
after upgrading to `next@canary` i am getting a more accurate error :
```cmd
error - ./node_modules/debug/src/node.js:5:0
Module not found: Can't resolve 'tty'

Import trace for requested module:
./node_modules/debug/src/index.js
./node_modules/mquery/lib/mquery.js
./node_modules/mongoose/lib/index.js
./node_modules/mongoose/index.js
./models/Admin.js
./pages/api/admin/_middleware.js

https://nextjs.org/docs/messages/module-not-found

You're using a Node.js module (tty) which is not supported in the Edge Runtime.
```

### Expected Behavior

the request runs through middleware and then goes to the requested route 

### To Reproduce

- create `_middleware.js`
- import  a mongoose model
- make a request that passes through that middleware

**Comment by balazsorban44** [comment]
Please see:

https://github.com/vercel/next.js/issues/32369#issuecomment-1092859859

https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis
