### ISSUE TITLE
The compiler panics when opening Dynamic routes

### ISSUE THREAD

**Issue by kekda-py** [vercel/next.js#36704]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home Single Language
Binaries:
  Node: 16.13.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.1.7-canary.1
  react: 18.0.0
  react-dom: 18.0.0
```

### What browser are you using? (if relevant)

I dont think its relevent. but `Chrome 100.0.4896.127`

### How are you deploying your application? (if relevant)

yarn dev

### Describe the Bug

Everything was working completely fine yesterday then I woke up today and ran `yarn dev`. It seemed to be fine at first but as soon as I opened a dynamic route baam! `This site can’t be reached`. I checked the console and
![](https://media.discordapp.net/attachments/918816567326806026/971610249800847390/unknown.png?width=1025&height=396)
I tried restarting it and went again on a dynamic route. same thing happened again.
I also tried `next@canary`

### Expected Behavior

It should work fine and open the page

### To Reproduce

I have no idea how to reproduce

**Comment by kekda-py** [comment]
Wait its still happening after I fixed it wtf

**Comment by kekda-py** [comment]
I am just so dumb I was running a different app and was running a different app

**Comment by balazsorban44** [comment]
Don't feel bad reaching out when you think you found a bug!

We are here to help. :slightly_smiling_face: If you think it's a project-specific issue, the [Discussions](https://github.com/vercel/next.js/discussions) is a better place, or you can check with our [Discord community](https://discord.com/invite/nextjs).

A suggestion is to create a reproduction before opening an issue.

A very educational video on the topic of contributing: https://www.youtube.com/watch?v=cuoNzXFLitc

And also: https://github.com/vercel/next.js/blob/canary/contributing.md
