### ISSUE TITLE
Custom app: unhandledRejection: TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by omerfaran** [vercel/next.js#36708]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Node: 16.15

### Describe the Bug

Hello everyone!

I'm using getInitialProps in my _app.js:

import App from "next/app";

```
function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />;
}

MyApp.getInitialProps = async ({ Component, ctx }) => {
  const appContext = App.getInitialProps(ctx);
  let pageProps = {};
  if (Component.getInitialProps)
    pageProps = await Component.getInitialProps(ctx);

  return { pageProps };
};

export default MyApp;
```
But getting the error

`unhandledRejection: TypeError: Cannot read properties of undefined (reading 'prototype')`

This error occurs on every page render, via the browser or Link. To reproduce it, you would only need to create a new nextjs app, and add the getInitialProps function like I did

I tried to follow tutorials to create this but can't understand what I'm doing wrong. Does anyone have an idea?

Thank you very much in advance

### Expected Behavior

Error won't appear

### To Reproduce

Create a new nextjs app, and add the getInitialProps function like I did

**Comment by ijjk** [comment]
Hi, where did you get the above snippet from? It seems to be incorrect so should be updated. If you are calling `App.getInitialProps(ctx)` you don't need to manually call `Component.getInitialProps` and you also don't need `getInitialProps` in `_app` unless you are doing something custom which is most often not necessary. 

Note: the `unhandledRejection` is from `App.getInitialProps` not being awaited.

**Comment by omerfaran** [comment]
Hello ijjk thank you very much for your help here

I understand now, yet when trying to do as you say, adding the await for App.getInitialProps, I'm getting the same error here:

![image](https://user-images.githubusercontent.com/42100126/167005891-552c86d9-273c-464c-902a-1e3d1b6f9571.png)


This is so strange, would you know why it can be caused? 
My node version is 16.5, and next js is 12.1.6

Thank you very much again

**Comment by ijjk** [comment]
It looks like you are still calling both `App.getInitialProps` and `Component.getInitialProps` this causes the `Component.getInitialProps` to be called twice you should only do one or the other.

**Comment by omerfaran** [comment]
Oh man I'm sorry for posting the screenshot like that, my bad, I did comment it back in here just to play around with this, it doesn't work also when not calling Component.getInitialProps.

However I found out what was causing this - it's trying to destruct the parameters of the function, when using it like in the example in the docs it's working:

`MyApp.getInitialProps = async (ctx) => {`

I'm sorry for the trouble, I should have just followed the example in the docs

Thank you very much for your help!

**Comment by ijjk** [comment]
No problem, closing as it sounds like the example in the docs is correct so nothing to change there
