### ISSUE TITLE
Build fails to compile - module not found: can't resolve "child_process" 12.1.6

### ISSUE THREAD

**Issue by wadehammes** [vercel/next.js#36776]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

In the latest 12.1.6, I can't get my site to compile on Vercel. Everything works fine in previous release. See log below. I am not sure if this is a Sentry issue or an issue with next.

![image](https://user-images.githubusercontent.com/222170/167429414-e9cb3370-e1b5-4044-8ed6-e833182b1a17.png)

### Expected Behavior

Site compiles like in 12.1.5

### To Reproduce

Have a next site set up with Sentry initiated at webpack level.

**Comment by balazsorban44** [comment]
Related: https://github.com/vercel/next.js/pull/36486, https://github.com/vercel/next.js/pull/36434

Note that you should not use Node-specific APIs in your Middleware as it uses the Edge Runtime. (See the docs: https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis). 

Sentry does not seem to be compatible at the moment.

Maybe related https://github.com/vercel/next.js/issues/36237#issuecomment-1117694528

**Comment by wadehammes** [comment]
Sentry works fine in middleware in 12.1.5 @balazsorban44 wondering what changed?

**Comment by sergeyshaykhullin** [comment]
It also break `axios` usage inside `_middleware`

```js
experimental: {
  runtime: 'nodejs'
},
```

Doesn't help ;\

```
error - ./node_modules/axios/lib/helpers/toFormData.js:26:0
Module not found: Can't resolve 'buffer'

Import trace for requested module:
./node_modules/axios/lib/axios.js
./node_modules/axios/index.js
./src/api/index.ts
./src/pages/_middleware.ts

https://nextjs.org/docs/messages/module-not-found

You're using a Node.js module (buffer) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
```

**Comment by liamross** [comment]
Seems to be breaking Prisma, Upstash, etc within Middleware files, not sure if this is a new "stricter" middleware setup or if the version is broken.

**Comment by balazsorban44** [comment]
@sergeyshaykhullin the switchable runtime does not concern Middleware, we added a note about this in the docs to make it more clear: https://github.com/vercel/next.js/pull/36862

Also in the [Middleware docs](https://nextjs.org/docs/advanced-features/middleware#deployment) there is this:

> Middleware uses a [strict runtime](https://nextjs.org/docs/api-reference/edge-runtime)

So this should explain your situation. I'm closing this as the result is expected. A final word on Sentry, they don't have official Middleware support yet: https://github.com/getsentry/sentry-javascript/issues/4206

**Comment by sergeyshaykhullin** [comment]
@balazsorban44 Does that mean i can't do http requests inside middleware?

**Comment by liamross** [comment]
@sergeyshaykhullin You can still use `fetch` (https://nextjs.org/docs/api-reference/edge-runtime#fetch)

Also as a side note: I think the issues I was facing may have been due to a custom webpack config within the next config file, will do more testing later

**Comment by balazsorban44** [comment]
Improved the documentation here: https://github.com/vercel/next.js/pull/36862

**Comment by straube** [comment]
@balazsorban44 In case I fetch CMS data (we use Sanity.io) in a middleware/Edge function and [their client](https://github.com/sanity-io/next-sanity) relies on unsupported Node modules, I have only two choices:

1. Ask the CMS client maintainer to "fix" their package to not use native Node modules (unlikely).
2. Write our own client/integration to the CMS API.

Is that right?

**Comment by balazsorban44** [comment]
You should not be using Middleware to fetch CMS data, check out our [data fetching](https://nextjs.org/docs/basic-features/data-fetching/overview) documentation for that.

**Comment by straube** [comment]
@wadehammes Here is a simplified version of the middleware I mentioned, just to illustrate how it can be done:

```
import { NextRequest, NextResponse } from "next/server";

const getRedirectUrl = (target: string, req: NextRequest) => {
  const isAbsoluteUrl = Boolean(target.match(/^https?:\/\//));
  if (isAbsoluteUrl) {
    return target;
  }

  /*
   * Relative URL.
   *
   * https://nextjs.org/docs/messages/middleware-relative-urls
   */
  const url = req.nextUrl.clone();
  url.pathname = target;
  return url;
};

export async function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;

  // This is where you'd fetch the redirect from your CMS
  const redirect = await getRedirectByPath(pathname);

  if (redirect) {
    const url = getRedirectUrl(redirect.target, req);
    return NextResponse.redirect(url, redirect.permanent ? 301 : 302);
  }
};
```

The type of the `redirect` object returned by `getRedirectByPath` looks like this:

```
type Redirect = {
  target: string;
  permanent: boolean;
};
```

But I guess you get the idea.

**Comment by wadehammes** [comment]
> @wadehammes Here is a simplified version of the middleware I mentioned, just to illustrate how it can be done:
> 
> ```
> import { NextRequest, NextResponse } from "next/server";
> 
> const getRedirectUrl = (target: string, req: NextRequest) => {
>   const isAbsoluteUrl = Boolean(target.match(/^https?:\/\//));
>   if (isAbsoluteUrl) {
>     return target;
>   }
> 
>   /*
>    * Relative URL.
>    *
>    * https://nextjs.org/docs/messages/middleware-relative-urls
>    */
>   const url = req.nextUrl.clone();
>   url.pathname = target;
>   return url;
> };
> 
> export async function middleware(req: NextRequest) {
>   const { pathname } = req.nextUrl;
> 
>   // This is where you'd fetch the redirect from your CMS
>   const redirect = await getRedirectByPath(pathname);
> 
>   if (redirect) {
>     const url = getRedirectUrl(redirect.target, req);
>     return NextResponse.redirect(url, redirect.permanent ? 301 : 302);
>   }
> };
> ```
> 
> The type of the `redirect` object returned by `getRedirectByPath` looks like this:
> 
> ```
> type Redirect = {
>   target: string;
>   permanent: boolean;
> };
> ```
> 
> But I guess you get the idea.

@straube awesome implementation, we use middleware for AB test identification and page redirects (with Launch Darkly) which works perfect (we use the fetch API to hit custom internal endpoints that handle the Launch Darkly identify and flag retrieval), wondering if you could leverage something similar (not familiar with Sanity) but the more I think about it I could probably do the same with Contentful and just hit their endpoint (and pass the pathname as a param) instead of using their SDK (which would fail due to the node module issue).

**Comment by straube** [comment]
> Perhaps, we could add polyfills for the required node modules to our own codebase?

Just answering my own question here: no. I tried that and some polyfills rely on `eval` which is also not available on the Edge environment. We'll probably have to update the code where we use client libraries (such as Sanity) to dispatch requests using `fetch`.
