### ISSUE TITLE
Multiple Set-Cookie headers will be folded when appended in _middleware

### ISSUE THREAD

**Issue by ValentinH** [vercel/next.js#36785]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.18.3
      npm: 8.8.0
      Yarn: 3.1.1
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

First of all, I'm sorry to not provide a whole issue but I would simply like to reopen #34467 which was closed and locked without a way to follow whether the fix was actually published or not.

The last answer said:
> A fix was already shipped for this and should hit stable in the coming days so I'm closing this!

But we are still observing the behaviour mentioned on this issue  **only when deploying on Vercel**. This makes it super hard to debug as we need to deploy for every single test.

PR #30560 seems to have fix it but I'm afraid it doesn't impact the Edge runtime.

Could we get the confirmation that the above mentioned fixed was actually deployed to the Edge runtime?

### Expected Behavior

I should see multiple Set-Cookie response headers.

### To Reproduce

You can reproduce it yourself easily enough. (using NextResponse.cookie just wraps the headers.append call, so using it directly for brevity)

```ts
import { NextRequest, NextResponse } from "next/server";

export default async function middleware(_request: NextRequest) {
    const resp = NextResponse.next();
    resp.headers.append("Set-Cookie", "cookie1=val1");
    resp.headers.append("Set-Cookie", "cookie2=val2");
    return resp;
}
```
Once deployed to vercel you will see in the response that the headers are concatenated.
![image](https://user-images.githubusercontent.com/2678610/167476741-18a7b688-9f34-4b47-a6c2-5ad310892cec.png)

**Comment by SukkaW** [comment]
Confirmd. Here is minimum reproduction: https://github.com/SukkaW/nextjs-issue-36785

**Comment by javivelasco** [comment]
I've just tested this in both Next.js server and a Vercel deployment and it works fine now so I think we can close this issue! Thanks for reporting! :)
