### ISSUE TITLE
next/script: beforeInteractive scripts in _document not being added to the website

### ISSUE THREAD

**Issue by kevineinarsson** [vercel/next.js#36795]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.17
      pnpm: 6.32.3
    Relevant packages:
      next: 12.1.7-canary.3
      react: 18.1.0
      react-dom: 18.1.0
```

### What browser are you using? (if relevant)

Chrome 101.0.4951.54

### Describe the Bug

In 12.1.6, a warning was added when using `strategy="beforeInteractive"` outside of _document.js ([link](https://github.com/vercel/next.js/blob/canary/errors/no-before-interactive-script-outside-document.md))

When moving a script to _document, I noticed that scripts weren't being added to the source when inspecting the website.

Some (quite poor) debugging leads me to believe that `HeadManagerContext.updateScripts` is undefined when the script is meant to be added to the scriptLoader object in `dist/server/render.js`.

### Expected Behavior

Scripts to be attached to `head` or `body` depending on where it is defined in `_document.js` as documentation implies

### To Reproduce

https://github.com/kevineinarsson/next-repro-script-issue

**Comment by balazsorban44** [comment]
Thanks for reporting, we are tracking this in https://github.com/vercel/next.js/issues/36997

Feel free to add your comments there!
