### ISSUE TITLE
TypeScript error when extending LinkProps

### ISSUE THREAD

**Issue by tnurzynski** [vercel/next.js#36800]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```   
   Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.8.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

not relevant

### How are you deploying your application? (if relevant)

not relevant

### Describe the Bug

I have a TS component, which props extend both `LinkProps` and `HTMLAttributes<HTMLAnchorElement>`. After updating next to 12.1.6, TS throws an error.

```
Interface 'NavLinkProps' cannot simultaneously extend types 'InternalLinkProps' and 'HTMLAttributes<HTMLAnchorElement>'.
  Named property 'onClick' of types 'InternalLinkProps' and 'HTMLAttributes<HTMLAnchorElement>' are not identical.

Interface 'NavLinkProps' cannot simultaneously extend types 'InternalLinkProps' and 'HTMLAttributes<HTMLAnchorElement>'.
  Named property 'onMouseEnter' of types 'InternalLinkProps' and 'HTMLAttributes<HTMLAnchorElement>' are not identical.ts(2320)
```

Related PRs:
https://github.com/vercel/next.js/pull/36436
https://github.com/vercel/next.js/pull/36474

### Expected Behavior

I know that you're changing the Link behaviour, but a minor release shouldn't break the app?

### To Reproduce

A minimal reproducible example - create a component:

```
import Link, { LinkProps } from 'next/link';
import { HTMLAttributes } from 'react';

interface NavLinkProps extends LinkProps, HTMLAttributes<HTMLAnchorElement> {}

export const NavLink: React.FC<NavLinkProps> = ({
  href,
  className = '',
  children,
  ...props
}) => {
  return (
    <Link href={href}>
      <a className={className} {...props}>
        {children}
      </a>
    </Link>
  );
};
```

(BTW I know that in this example I can easily fix it this way):

```
interface NavLinkProps extends HTMLAttributes<HTMLAnchorElement> {
  href: LinkProps['href'];
}
```

**Comment by balazsorban44** [comment]
There is a slight TS change in #36436 that prepares for the next major:

https://github.com/vercel/next.js/pull/36436/files#diff-8acbf39f6c8f78de00c1be9339c3f839cd7f9a21f3c1d825cd23c14d4f11d718R33-R40

I'm not sure if we can do better, but since `type` and `interface` resolves conflicts differently, you could write this instead:

```ts
type NavLinkProps = LinkProps & HTMLAttributes<HTMLAnchorElement>
```

Let me know if this is a sufficient solution. :+1:

**Comment by tnurzynski** [comment]
I know, I've seen these changes. I applied a different fix which works for my component. I wanted you to have a look at this issue anyway, but since it probably needs to stay like this, I'll just close :)
