### ISSUE TITLE
`asPath` mismatch when using `rewrites` feature

### ISSUE THREAD

**Issue by felixmosh** [vercel/next.js#36802]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.19.1
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.3
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

My urls looks like `/weekend-list`, which should be mapped to `/weekendList` when I print `asPath` & `pathname` I get a mismatch error .

### Expected Behavior

It should behave the same as it works on the client, `asPath` points to the actual path in the browser, `pathname` points to the underline page rendered.

### To Reproduce

```js
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async rewrites() {
    return [
      {
        source: '/weekend-list',
        destination: '/weekendList',
      },
    ]
  },
}

module.exports = nextConfig
```
```js
// pages/weekendList.js
import { useRouter } from 'next/router';

export default function WeekendList() {
  const { asPath, pathname } = useRouter();
  return (
    <ul>
      <li>asPath: {asPath}</li>
      <li>pathname: {pathname}</li>
    </ul>
  );
}
```

1. start the server (dev or prod).
2. navigate to `/weekend-list`

You will get a mismatch error.

**Comment by balazsorban44** [comment]
Duplicate, answered here: https://github.com/vercel/next.js/issues/34197#issuecomment-1035335803.

It looks like that issue was accidentally closed without clearing up the docs on this, so let's track it here.

**Comment by felixmosh** [comment]
What is the benefit of `asPath` if it is only available on the client side, think of a usage inside links.
This means that all the links of the app will generate wrong link from SSR (will hurt SEO).
