### ISSUE TITLE
next build does not lint .mjs files

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#36819]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #202204271406 SMP PREEMPT Wed Apr 27 16:11:45 UTC 2022
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: 7.0.0
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

`next/lint` by default does not lint `.mjs` files (see [here](https://github.com/vercel/next.js/blob/fdc071c5fd176f719d3eb4f2700412263cf7bff0/packages/next/cli/next-lint.ts#L21)), but it is possible to pass `--ext .mjs`.

when `next build` runs the linter, it uses the same default file extensions (see [here](https://github.com/vercel/next.js/blob/fdc071c5fd176f719d3eb4f2700412263cf7bff0/packages/next/lib/eslint/runLintCheck.ts#L133)), however there is no way to provide custom file extensions like with the `--ext` CLI option.

### Expected Behavior

see above

### To Reproduce

1. `git clone git@github.com:stefanprobst/issue-next-lint-mjs.git`
2. `yarn run lint` shows no error
3. `yarn run lint:ext` shows error because it passes `--ext .mjs`
4. `yarn run build` shows no error

**Comment by caioluis** [comment]
Changes proposed to #37389

**Comment by rubytree33** [comment]
@vitalybaev Are you still working on #37389? If not I'd like to try this issue.
