### ISSUE TITLE
"This Hook is not supported in Server Components" thrown from a client component

### ISSUE THREAD

**Issue by helloitsjoe** [vercel/next.js#36821]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64
    Binaries:
      Node: 14.18.2
      npm: 6.14.15
      Yarn: 1.22.17
      pnpm: 6.32.3
    Relevant packages:
      next: 12.1.7-canary.3
      react: 0.0.0-experimental-d20c3af9d-20220506
      react-dom: 0.0.0-experimental-d20c3af9d-20220506
```

### What browser are you using? (if relevant)

Chrome 101.0.4951.54 (Official Build) (x86_64)

### Describe the Bug

When using `useState` in a `.client.js` file, I'm getting an error as if if were a `.server.js` file:

```
Server Error
Error: This Hook is not supported in Server Components.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
components/App.client.js (4:10) @ MyApp

  2 | 
  3 | export default function MyApp({ children }) {
> 4 |   useState();
    |          ^
  5 |   return (
  6 |     <div>
  7 |       App Client
```

Possibly related to https://github.com/vercel/next.js/issues/36820

### Expected Behavior

I expect to be able to use React hooks in `.client.js` files

### To Reproduce

I've created a minimal reproduction here: https://github.com/helloitsjoe/server-components-nextjs-client/

1. `pnpm install`
2. `pnpm dev`
3. Open a browser
4. Note the server component error, coming from a client file `Foo.client.js` using `useState`

Here's what the repo consists of:

1. Create `pages/index.server.js`, `pages/_app.server.js`, `components/App.js`, and `components/App.client.js`
2. Add `React.useState` to `App.client.js`
3. Export `App.client.js` from `App.js` (this is a workaround for #36820, and might mean the two issues are related)
4. Import `App.js` into `_app.server.js`
5. Start a dev server with `pnpm dev`

**Comment by rapgodnpm** [comment]
I also have this issue, is there a plan to fix this?

**Comment by huozhi** [comment]
We have removed the support for Custom app as server components. 
And more RSC support are moving to app dir, check https://github.com/vercel/next.js/issues/38979#issuecomment-1193932355
