### ISSUE TITLE
jest v28 environment error

### ISSUE THREAD

**Issue by GabenGar** [vercel/next.js#36842]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System: 
- Platform: win32
- Arch: x64
- Version: Windows 7 Ultimate Service Pack 1

Binaries:
- Node: 12.22.1
- npm: N/A
- Yarn: N/A
- pnpm: N/A

Relevant packages:
- next: 12.1.7-canary.4
- react: 17.0.2
- react-dom: 17.0.2

### Describe the Bug

With `jest` of version 28+ `npm run test` ends in this error:
```sh
● Validation Error:

  Test environment jest-environment-jsdom cannot be found. Make sure the testEnvironment configuration option points to an existing node module.

  Configuration Documentation:
  https://jestjs.io/docs/configuration


As of Jest 28 "jest-environment-jsdom" is no longer shipped by default, make sure to install it separately.
```

I've looked at the [`jest-environment-jsdom`](https://www.npmjs.com/package/jest-environment-jsdom) page and have some reservations about installing packages without a readme. So I thought [`jsdom`](https://www.npmjs.com/package/jsdom) would suffice, but it's doesn't and crashes with the same error.

### Expected Behavior

Not crashing on test start.

### To Reproduce

```sh
git clone https://github.com/GabenGar/repros.git repros
cd repros/nextjs/jest-env-error
npm install
npm run test
```

**Comment by icyJoseph** [comment]
Ah, I recall setting this up last week, following this guide: https://jestjs.io/docs/upgrading-to-jest28#jsdom - will give it a go again.

**Comment by icyJoseph** [comment]
> I've looked at the [jest-environment-jsdom](https://www.npmjs.com/package/jest-environment-jsdom) page and have some reservations about installing packages without a readme.

Well, it's a sub-package to jest, https://github.com/facebook/jest/tree/main/packages/jest-environment-jsdom, I believe it can be trusted.

**Comment by GabenGar** [comment]
All of this is not very obvious to a person stumbling upon `jest` for the first time. I was promised the golden rivers of TDD, but instead got 200+ packages and a bunch of configs with at least 3 instructions (nextjs docs, nextjs example and jest docs) giving conflicting info. But installing `jest-environment-jsdom` does fix the issue at hand.

**Comment by icyJoseph** [comment]
> All of this is not very obvious to a person stumbling upon `jest` for the first time. I was promised the golden rivers of TDD, but instead got 200+ packages and a bunch of configs with at least 3 instructions (nextjs docs, nextjs example and jest docs) giving conflicting info. But installing `jest-environment-jsdom` does fix the issue at hand.

Yeah, that's something to take up with the Jest team I guess. They have gone through some rough times, and only yesterday, it was announced that they'll be moving into the OpenJS foundation. 

There's also a few other migration pain points, such as file transforms, which do not work like they used to, and in my opinion the upgrade guide is a bit foggy on how to update those.

**Comment by balazsorban44** [comment]
The docs should already be updated in https://github.com/vercel/next.js/pull/36632, it won't show up on the documentation before the next stable release.

I'll make sure to update our `with-jest` example to use Jest 28 as well.
