### ISSUE TITLE
NextJS - TypeError: res.unstable_revalidate is not a function

### ISSUE THREAD

**Issue by SviatLC** [vercel/next.js#36854]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

NextJS: v.12.1.6
NodeJS: v.16.14.1;
React: v.17.0.2;

### What browser are you using? (if relevant)

Chrome v.100

### How are you deploying your application? (if relevant)

using on localhost

### Describe the Bug

I try to use a brand new feature released in NextJS v.12.1 https://deepinder.me/nextjs-on-demand-isr. The API itself works fine. I can reach it. But in exchange it returns 500 error that says `res.unstable_revalidate is not a function`. It does not work either over dev (`next server && next dev`) run or production one (`next build && next start`).

This is the api endpoint:
```js
// ./api/misc/revalidate

const revalidateCache = async (_, res) => {
    console.log(res.unstable_revalidate, 'TEST REVALIDATE'); // res.unstable_revalidate is undefined here :( 

    try {
        await res.unstable_revalidate('/');

        return res.json({ revalidated: true });
    } catch (err) {
        return res.status(500).send(`Error revalidating: ${err}`);
    }
};

export default revalidateCache;

```

This is the invoke:
```js
// ./apps/client/services/server

export default function getRevalidate () {
    fetch('/api/misc/revalidate');
};
```

View layer that I call from:
```js
// .src/pages/index.js

// ...some code here

const HomePage = ({ page, legacy }) => {
    const handleClick = () => {
        getRevalidate();
    };

    return (
        <div className={styles.homeRoot}>
            <button onClick={handleClick}>REVALIDATE</button>
        </div>
    );
};

```

### Expected Behavior

`res.unstable_revalidate()` - must be reachable

### To Reproduce

I don't have deployed instance anywhere yet

**Comment by BiosBoy** [comment]
answered here: https://stackoverflow.com/questions/72213489/nextjs-typeerror-res-unstable-revalidate-is-not-a-function/72214364#72214364

**Comment by BiosBoy** [comment]
we can close it
