### ISSUE TITLE
URLs with spaces cause a 500: Internal Server Error on production only

### ISSUE THREAD

**Issue by richthornton** [vercel/next.js#36865]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #77~18.04.1-Ubuntu SMP Wed Mar 30 15:36:02 UTC 2022
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Having a space in a link url causes an internal server error on production only. For example, if I have:
`<Link href={"/details/space here"}><a>Link</a></Link>`
Then I create a page under `/details/[routeName]` with `getStaticPaths` and `getStaticProps`, there is an internal server error on Vercel.

However, when running it locally, the route is resolved fine. I believe this behaviour has only been happening for the last few days, as previously this worked fine (causing our application to break unexpectedly)

### Expected Behavior

I expected the behaviour to be retained, where urls with spaces were correctly resolved. One solution is for the user to call 'encodeURIComponent' on the part of the object that might have a space in it (I've shown where in the reproduction). However, this is a change in behaviour, and so might cause quite a few applications to have issues.

### To Reproduce

Repository with minimal reproduction: [https://github.com/richthornton/vercel-bug-recreation](https://github.com/richthornton/vercel-bug-recreation)

1. Run 'yarn dev', click on link, and verify everything works fine.
2. Deploy to Vercel, click on link, confirm seeing this issue: 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/7372040/168127550-59290923-9fb1-4123-b130-027e88227a99.png">

The deployed version can be found here: [https://vercel-bug-recreation.vercel.app/](https://vercel-bug-recreation.vercel.app/)

**Comment by balazsorban44** [comment]
Thanks for reporting. This does not seem to be a Next.js bug, but we are investigating. 👍

**Comment by balazsorban44** [comment]
This should be fixed now. 👍
