### ISSUE TITLE
[Runtime Configuration] `publicRuntimeConfig` is empty when you land on static pages

### ISSUE THREAD

**Issue by jihchi** [vercel/next.js#36863]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
Binaries:
  Node: 16.13.1
  npm: 8.1.2
  Yarn: 1.22.18
  pnpm: 6.31.0
Relevant packages:
  next: 12.1.7-canary.4
  react: 18.1.0
  react-dom: 18.1.0
```

### Which example does this report relate to?

https://github.com/jihchi/nextjs-publicruntimeconfig-client-transitions

### What browser are you using? (if relevant)

Chrome 101.0.4951.54 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

_N/A_

### Describe the Bug

> This is about [Runtime Configuration](https://nextjs.org/docs/api-reference/next.config.js/runtime-configuration).

`publicRuntimeConfig` is empty when you land on static pages (e.g. no data fetching methods or `getStaticProps`).

It only works when you land on SSR pages and/or navigate to other routes (client-side transitions) but not vice versa.

### Expected Behavior

We should see `https://picsum.photos/320/240` under `Direct from publicRuntimeConfig` section after you complete the `To Reproduce` steps.

### To Reproduce

1. Follow the [Getting Started](https://github.com/jihchi/nextjs-publicruntimeconfig-client-transitions#getting-started)
1. Open http://localhost:3000/ with your browser.
1. Click `Go to /GetInitialProps`
1. You'll see `undefined/320/240` under `Direct from publicRuntimeConfig` section

**Comment by timneutkens** [comment]
This is expected as the publicRuntimeConfig is part of the initial pageload and static pages don't hold runtimeconfig given that they're generated during `next build`. #36923 updated the docs to be clearer that you can't use static generation with runtime config.
