### ISSUE TITLE
Dynamic imports not working in WebWorker

### ISSUE THREAD

**Issue by donalffons** [vercel/next.js#36874]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Mon Mar 28 09:13:53 UTC 2022
    Binaries:
      Node: 16.14.2
      npm: 8.7.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.5
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

101.0.4951.54 (not relevant)

### How are you deploying your application? (if relevant)

(not relevant)

### Describe the Bug

I want to dynamically import React components inside a worker. These components are not meant to be rendered using ReactDOM, but using a custom renderer instead.

```js
// worker/worker.ts

import dynamic from "next/dynamic";
// import ComponentInWorker from "./ComponentInWorker"; // This works fine

const ComponentInWorker = dynamic(() => import("./ComponentInWorker"));
```

This leads to the following console error some time during an early webpack phase (i.e. "my" worker code has not yet been executed):
```
Uncaught ReferenceError: window is not defined
    at eval (loadable.js:324:5)
    at Object../node_modules/next/dist/shared/lib/loadable.js (worker_worker_ts.js:41:1)
    at Object.options.factory (worker_worker_ts.js:657:31)
    at __webpack_require__ (worker_worker_ts.js:136:33)
    at fn (worker_worker_ts.js:312:21)
    at eval (dynamic.js:43:40)
    at Object../node_modules/next/dist/shared/lib/dynamic.js (worker_worker_ts.js:19:1)
    at Object.options.factory (worker_worker_ts.js:657:31)
    at __webpack_require__ (worker_worker_ts.js:136:33)
    at fn (worker_worker_ts.js:312:21)
```

The error occurs in this line in `./node_modules/next/dist/shared/lib/loadable.js`:
```js
if (typeof window !== 'undefined') {
    window.__NEXT_PRELOADREADY = Loadable.preloadReady; // error
}
```

Disabling source maps in Chrome reveals that the following code is executed instead:
```js
if (true) {
    window.__NEXT_PRELOADREADY = Loadable.preloadReady;
}
```
And since that execution is happening in a worker, window is undefined.

### Expected Behavior

I would expect dynamic imports to work in a web worker, the same way they work on the main thread.

### To Reproduce

Here is a minimal [example on Stackblitz](https://stackblitz.com/github/donalffons/next-dynamic-import-from-worker-issue?file=worker%2Fworker.ts).

**Comment by balazsorban44** [comment]
From the docs:

> `dynamic()` can't be used inside of React rendering as it needs to be marked in the top level of the module for preloading to work, similar to React.lazy.

https://nextjs.org/docs/advanced-features/dynamic-import#basic-usage
