### ISSUE TITLE
startTransition in production build doesn't match in development

### ISSUE THREAD

**Issue by powerfulyang** [vercel/next.js#36887]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

      Platform: win32
      Arch: x64
      Version: Windows 10 Pro for Workstations
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.5
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 101.0.4951.64

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

The React@18 new api `startTransition`  in production build environment doesn't match in development environment.

### Expected Behavior

`startTransition`  has consistent performance in production and development environments 

### To Reproduce

Repository https://github.com/powerfulyang/powerfulyang.com/tree/reproduce-next-bug-about-startTransition

## clone above project

1. `git clone https://github.com/powerfulyang/powerfulyang.com.git`
2. `git checkout reproduce-next-bug-about-startTransition`
## next dev

1. `npm install`
2. `npm run prod:dev`, open http://localhost:3000/gallery, **feel fluid and responsive**

## next build

1. `npm run build`
2. `npm run start`, open http://localhost:3000/gallery, **interactions feel slow and unresponsive**

**Comment by SukkaW** [comment]
That's weird. In your repo, you don't use `startTransition` (or `useTransition`) at all.

**Comment by powerfulyang** [comment]
> That's weird. In your repo, you don't use `startTransition` (or `useTransition`) at all.

https://github.com/powerfulyang/powerfulyang.com/blob/reproduce-next-bug-about-startTransition/src/components/Masonry/index.tsx

这个文件有，不知道是 next 还是 react 的 BUG。
