### ISSUE TITLE
API function error when Nextjs app has package type=module 

### ISSUE THREAD

**Issue by jeremytenjo** [vercel/next.js#36903]
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 12.1.5
      react: 18.1.0
      react-dom: 18.1.0

### How are you deploying your application? (if relevant)

branch trigger

### Describe the Bug

Getting error when calling an api route when my package.json type=module

```js 
2022-05-14T00:47:32.805Z	undefined	ERROR	ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///var/task/___next_launcher.js:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async getListener (/var/task/___vc/__launcher.js:37:11)
RequestId: 53046e6c-3224-48d2-9428-1db2456069c2 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### Expected Behavior

Run function without error

### To Reproduce

create api function with .ts in a nextjs app with it's package.json type=module

deploy function to vercel 

trigger production function

**Comment by jeremytenjo** [comment]
Thank you for looking into this issue @Brooooooklyn . Let me know if I can provide more info

**Comment by AbuHafsa** [comment]
@jeremytenjo I assume that this issue has been fixed as per the merged PR of @ijjk?

**Comment by ijjk** [comment]
The above PR is not yet available, we will update here when it is rolled

**Comment by huozhi** [comment]
The update is rolled out to production, could you verify again to see if your issues are resolved?

**Comment by jeremytenjo** [comment]
I will test ASAP, thanks!

**Comment by jeremytenjo** [comment]
Hi @huozhi , what is the best way for me to test it?

**Comment by huozhi** [comment]
I [forked a reproduction](https://github.com/beeebox/next-esm-api-bug) and deployed to vercel [it works now](https://next-esm-api-bug-delta.vercel.app/api/hello) for me.

**Comment by ijjk** [comment]
Closing as this is resolved now per above

**Comment by jeremytenjo** [comment]
Works as of `"next": "^12.1.7-canary.10"` 

Thanks! @ijjk  @huozhi
