### ISSUE TITLE
Unstyled UI shows up on the first load. CSS is not loading properly in production build.

### ISSUE THREAD

**Issue by mplakhtiy** [vercel/next.js#36915]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Unstyled UI shows up on the first load when using material ui examples [nextjs-with-typescript](https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript) or [nextjs](https://github.com/mui/material-ui/tree/master/examples/nextjs) [stackblitz](https://stackblitz.com/github/mui/material-ui/tree/master/examples/nextjs)

This also happens within my own project with the latest packages versions.

### Describe the Bug

Unstyled UI shows up on the first load. CSS is not loading properly in production build.

### Expected Behavior

Ui is loaded with styles on the first load.

### To Reproduce

1. Go to https://stackblitz.com/github/mui/material-ui/tree/master/examples/nextjs or https://stackblitz.com/github/mui/material-ui/tree/master/examples/nextjs-with-typescript
2. Reload the ui within stackblitz (it can be seen that mui light bulb icon is large for a fraction of a second)

**Comment by balazsorban44** [comment]
This should probably be reported in https://github.com/mui/material-ui first. If they verify if they agree it's a bug with Next.js, we can have look. :+1:

**Comment by balazsorban44** [comment]
UPDATE: I found you opened this already, and there was this response: https://github.com/mui/material-ui/issues/32770#issuecomment-1127009348

I tested with our `canary` release, and it was indeed fixed already.

https://github.com/vercel/next.js/releases/tag/v12.1.7-canary.4 and up should work correctly.

**Comment by mplakhtiy** [comment]
Thanks @balazsorban44 for the quick response!

**Comment by vascojm82** [comment]
> UPDATE: I found you opened this already, and there was this response: [mui/material-ui#32770 (comment)](https://github.com/mui/material-ui/issues/32770#issuecomment-1127009348)
> 
> I tested with our `canary` release, and it was indeed fixed already.
> 
> https://github.com/vercel/next.js/releases/tag/v12.1.7-canary.4 and up should work correctly.
> 
> Related PR: #36792
> 
> And related issue already reporting this: [#36675 (comment)](https://github.com/vercel/next.js/issues/36675#issuecomment-1119264406)

Hi, I upgraded NextJS from v12.0.10 to v12.1.7-canary.39 and I'm still seeing this issue, the style from the theme won't load on the page's first render, anyone can help?

**Comment by balazsorban44** [comment]
@7iomka please refrain from mentioning the whole Next.js team.

You can create a new issue with a full reproduction, following the steps described in the [bug report template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&template=1.bug_report.yml), and see how we triage issues [here](https://github.com/vercel/next.js/blob/canary/contributing.md#triaging).
