### ISSUE TITLE
Docs: https://nextjs.org/docs/api-reference/cli

### ISSUE THREAD

**Issue by Baoing** [vercel/next.js#36963]
### What is the improvement or update you wish to see?

![image](https://user-images.githubusercontent.com/56350557/168709364-27883113-daaa-488e-8fee-6bbfa685987e.png)
anbout pass --max-old-space-size node arguments to next commands, I set "NPX --max-old-space-size=9062 next build" to invalid

And my computer 16GB running memory

### Is there any context that might help us understand?

![image](https://user-images.githubusercontent.com/56350557/168710039-f6c85ec4-fd61-4aaf-b189-e1c02d1b9344.png)
![image](https://user-images.githubusercontent.com/56350557/168710162-c25ea7c9-0367-4751-bcab-c86e4e21f095.png)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/cli

**Comment by raul-saez** [comment]
Solution given on duplicate: https://github.com/vercel/next.js/discussions/36962
