### ISSUE TITLE
"url" parameter is valid but upstream response is invalid

### ISSUE THREAD

**Issue by lack-of-gravitas** [vercel/next.js#36977]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.6
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Firefox Developer Edition 101.0b7

### How are you deploying your application? (if relevant)

Vercel (next start)

### Describe the Bug

Error 403 received with following response **"url" parameter is valid but upstream response is invalid** when using next/image <Image> component with src prop as a globally public placeholder image (https://via.placeholder.com/800).

- Codebase is vanilla https://github.com/vercel/commerce deployment to Vercel and git cloned and developed locally.
- via.placeholder.com added in images.domains in next.config
- full node_modules clean and yarn install

**Alternatives Attempted**
WORKS - add _unoptimized={false}_ prop
WORKS - use <img src= instead of <Image src=

### Expected Behavior

Publicly accessible image loads in Image component.

### To Reproduce

Use
<Image src="https://via.placeholder.com/800x600" layout="fill"  alt={'test'} />

**Comment by FLCN-16** [comment]
@lack-of-gravitas Please check this document reference if it works for you. [Documentation](https://nextjs.org/docs/messages/next-image-unconfigured-host)

**Comment by lack-of-gravitas** [comment]
> @lack-of-gravitas Please check this document reference if it works for you. [Documentation](https://nextjs.org/docs/messages/next-image-unconfigured-host)

Thanks but already have the appropriate domains in next.config
![image](https://user-images.githubusercontent.com/10094964/168920165-4dc047b0-208b-4778-899f-46255dd381db.png)

**Comment by lack-of-gravitas** [comment]
OK tried with my own Azure-based CDN and that works -- so the issue must be at via.placeholder.com
Closing issue.

**Comment by cowofevil** [comment]
@lack-of-gravitas I ran into the same problem and discovered that placeholder.com had changed their API. You might want to try "https://via.placeholder.com/800.png" to hint the API to get back a PNG image because the default is now GIF with the change in API.
