### ISSUE TITLE
No images in your Blog example

### ISSUE THREAD

**Issue by kai687** [vercel/next.js#36970]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

I didn't run anything. I only saw the issue on your website. I just assumed it's related to a code example. I just checked the 'canary' checkbox to be able to submit this issue.

### Which example does this report relate to?

It's this page: https://next-blog-wordpress.vercel.app/ 

### Describe the Bug

No images are loaded. Looks unmaintained. Link to GitHub just links to the generic Next.js repo landing page. With the `examples` folder having this many subfolders, I'm not going to go hunting for the code.

### Expected Behavior

- Example loads with images
- Link to GitHub leads to the actual code

### To Reproduce

Go to https://next-blog-wordpress.vercel.app/

**Comment by kai687** [comment]
Interesting! No, it still seems broken for me (tried Chrome, Safari, and Firefox):

<img width="813" alt="screenshot" src="https://user-images.githubusercontent.com/17420240/169018166-55226dd5-c3d0-47b1-a016-67cf8c7c89e3.png">

Interestingly, one image loads, but I get 404s like this: 

```
https://next-blog-wordpress.vercel.app/_next/image?url=https%3A%2F%2Fvercel.wpengine.com%2Fwp-content%2Fuploads%2F2020%2F05%2Fcover5.jpg&w=3840&q=75
```

for the other images. I tried hard-refreshing a couple of times, so it doesn't seem cache-related either.

**Comment by FLCN-16** [comment]
![image](https://user-images.githubusercontent.com/57741232/169679336-0525619f-ec40-4253-a49f-a8fc366535c1.png)
As you can see in above screenshot every image renders on the example. Can you please try a different browser or device?

**Comment by Stormrunn3r** [comment]
I'm having the same issue. Tried on multiple browsers: Chrome, Brave, Firefox, Edge. Also tried on my phone through wifi and 4G with Chrome and Brave.
![next-blog-wordpress vercel app_](https://user-images.githubusercontent.com/13387628/169713706-ebbf756a-726b-4a35-b677-e8b467c833f1.png)

**Comment by leerob** [comment]
I think this is an issue with our WordPress instance for the WordPress blog example - but not the `blog-starter` example 👍

**Comment by liby** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/38807139/171465915-252c5005-849a-42ff-975b-90ea6bad9491.png">

Same issue.

**Comment by leerob** [comment]
This is fixed now 🙏 Sorry about that
