### ISSUE TITLE
Docs: Document that middleware makes HEAD requests

### ISSUE THREAD

**Issue by christhegrand** [vercel/next.js#36994]
### What is the improvement or update you wish to see?

The current Next middleware documentation doesn't mention that [the middleware makes HEAD requests](https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/router/router.ts#L2050) so that the client knows how to respond after page transitions. Please update the documentation to mention this detail.

### Is there any context that might help us understand?

We had a Cloudflare firewall rule enabled that presented managed challenges to users who made requests other than GET and POST. We didn't realize that adding Next middleware would result in HEAD requests being made, which were then blocked by Cloudflare. It took a while to track down the HEAD requests to Next. No one on our team realized that the middleware did this.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/middleware

**Comment by javivelasco** [comment]
It doesn't anymore!
