### ISSUE TITLE
hydrateRoot warning in nextjs 

### ISSUE THREAD

**Issue by murrowblue22** [vercel/next.js#37003]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

next-dev.js:53 Warning: ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

next start 

### Describe the Bug

next-dev.js:53 Warning: ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

### Expected Behavior

no warning 

### To Reproduce

running react/react-dom 18.1.0 with 12.1.6

**Comment by rares-lupascu** [comment]
+1

**Comment by JamieShelley** [comment]
+1

**Comment by railaru** [comment]
+1

Didn't have any problems locally but I ran into them after deploying to vercel

<img width="1031" alt="Screenshot 2022-05-19 at 10 15 27" src="https://user-images.githubusercontent.com/38836398/169246304-c65044d4-aba6-49d7-82f7-edd674b24263.png">

This hydration issue caused react-query to warnings as well


<img width="1031" alt="Screenshot 2022-05-19 at 10 15 27" src="https://user-images.githubusercontent.com/38836398/169246949-1af915db-f731-43cc-a21f-43e9d20acf78.png">

For now I resolved these warnings by reverting react & react-dom to version 17.0.2

**Comment by shuding** [comment]
Hey! Can you share a minimal reproduction repository? Also does the same problem occur with latest canary?

**Comment by hengwangsay** [comment]
use `custom-server-express` template and update to react18, this issue will come up

**Comment by huozhi** [comment]
@hengwangsay The issue of custom server with react 18 is fixed in the 12.1.7-canary, could you bump the version and try it?

**Comment by Roossi** [comment]
> ### Verify canary release
> * [x]  I verified that the issue exists in Next.js canary release
> 
> ### Provide environment information
> next-dev.js:53 Warning: ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
> 
> ### What browser are you using? (if relevant)
> chrome
> 
> ### How are you deploying your application? (if relevant)
> next start
> 
> ### Describe the Bug
> next-dev.js:53 Warning: ReactDOM.hydrate is no longer supported in React 18. Use hydrateRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
> 
> ### Expected Behavior
> no warning
> 
> ### To Reproduce
> running react/react-dom 18.1.0 with 12.1.6

>Stop
