### ISSUE TITLE
Need an update of @babel/core to fix Type-only import specifiers issue

### ISSUE THREAD

**Issue by 7iomka** [vercel/next.js#37016]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64
    Binaries:
      Node: 16.5.0
      npm: 8.3.0
      Yarn: 1.17.3
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.6
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

Latest next.js + babel not supported [Type-only import specifiers](https://www.babeljs.cn/blog/2021/10/29/7.16.0#typescript-45-features-13802httpsgithubcombabelbabelpull13802-13838httpsgithubcombabelbabelpull13838) because version of `@babel/core` for now is 7.15.0
https://github.com/vercel/next.js/blob/b2045c7669982edbb7002c7f88f8e7665a2168f7/packages/next/package.json#L99

For my case I can't drop babel, but I need this feature, because it works without babel with typescript 4.5+.

### Expected Behavior

Type-only import specifiers are supported

### To Reproduce

Just run any project with next.js and babel and try

```
// TypeScript 4.5
import { type Foo, fooInstance } from "my-module";
```

This code will give you an error
`Unexpected token, expected ","`

Without babel, all works fine.

**Comment by timneutkens** [comment]
Feel free to open a PR!

**Comment by 7iomka** [comment]
> Feel free to open a PR!

Done. I don't know if that small change is enough :)
