### ISSUE TITLE
Next.JS + StyledComponents doesn't provide SSR html file

### ISSUE THREAD

**Issue by Clzzi** [vercel/next.js#37029]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.7.2
      npm: 8.5.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 101.0.4951.64

### How are you deploying your application? (if relevant)

next build & next start

### Describe the Bug

1. I just create next-app using cli.
2. i linstall     "babel-plugin-styled-components": "^2.0.7",    "babel-preset-next": "^1.4.0", "styled-components": "^5.3.5",
3. then make test page in index and i started next project
4. but the project doesn't rendering ssr, i get empty html file
![KakaoTalk_Photo_2022-05-19-13-45-43](https://user-images.githubusercontent.com/62810965/169208550-dc254595-d4ad-4c61-b814-0db3f4103b31.png)

### Expected Behavior

i want to get styled html file

### To Reproduce

https://github.com/Clzzi/next-styled-components-issue

i make the repository to bring up this issue.

**Comment by jtbandes** [comment]
I have this issue too, but I am **not** using a custom babelrc, just the default compiler.

I was confused because the [documentation says](https://nextjs.org/docs/advanced-features/compiler#styled-components):

> We're working to port `babel-plugin-styled-components` to the Next.js Compiler.
>
> Currently, only the `ssr` and `displayName` transforms have been implemented. These two transforms are the main requirement for using `styled-components` in Next.js.

But SSR doesn't seem to work.

**Comment by jtbandes** [comment]
cc @timneutkens who added this documentation in https://github.com/vercel/next.js/pull/31485, maybe you have some better understanding of what is supported and what is still in the works?

**Comment by Clzzi** [comment]
@jtbandes So next.js latest version(12.0.4 in #31485) support own styled-components compiler option in next.config.js and it support SSR & displayName? But i set this options instead of babelrc & _documents file.. Not Working..

**Comment by await-ovo** [comment]
> @jtbandes So next.js latest version(12.0.4 in #31485) support own styled-components compiler option in next.config.js and it support SSR & displayName? But i set styled-component in next.config.js options instead of babelrc & _documents file.. Not Working..

I tested it in the repository you provided and found that it is a problem of incorrect file names, just change `pages/_doucuments.js` to `pages/_document.js` and it should work.

**Comment by Clzzi** [comment]
@await-ovo  oh!! thank you 👍  I habitually type doucments in most projects. so i thought doucments.tsx is correct 😂
Thank you for your reply 🙏

**Comment by await-ovo** [comment]
> I have this issue too, but I am **not** using a custom babelrc nor a custom Document, just the default compiler.
> 
> I was confused because the [documentation says](https://nextjs.org/docs/advanced-features/compiler#styled-components):
> 
> > We're working to port `babel-plugin-styled-components` to the Next.js Compiler.
> > Currently, only the `ssr` and `displayName` transforms have been implemented. These two transforms are the main requirement for using `styled-components` in Next.js.
> 
> But SSR doesn't seem to work.

It looks like SSR still needs to add `_document.js` for now. #35163

I think it would be nice to be able to use `styled-components` SSR out of the box without having to add additional files :)
