### ISSUE TITLE
HEAD prefetch requests caused by middleware put locale in the url path when using domain routing

### ISSUE THREAD

**Issue by g-leon-bj** [vercel/next.js#37037]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022
Binaries:
  Node: 16.13.2
  npm: 8.1.2
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.1.7-canary.8
  react: 18.1.0
  react-dom: 18.1.0
```

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When using Domain Routing as the locale handling stretegy in `next.config.js` and some middleware then next.js fires HEAD requests for link prefetching.
These HEAD requests put locale in the url path as if using Sub-path Routing (for example: `https://example.pt/pt-PT/blog`), when is not actually needed as we are using Domain Routing and urls should be like `https://example.pt/blog`.
If we use `next/link` in a page that url is correct, but the corresponding HEAD prefecth request adds the locale, which doesn't seem to be right.

### Expected Behavior

HEAD requests fired by middleware should only put locale in the url path when `next.congif.js` has Sub-path Routing configured. But if `next.config.js` has Domain Routing configured, HEAD requests should not include locale in the url path.

### To Reproduce

Add domain routing in `next.config.js`:
```
const nextConfig = {
  i18n: {
    locales: ['en-US', 'es-ES', 'pt-PT'],
    defaultLocale: 'en-US',
    domains: [
      {
        domain: 'example.com',
        defaultLocale: 'en-US',
      },
      {
        domain: 'example.es',
        defaultLocale: 'es-ES',
      },
      {
        domain: 'example.pt',
        defaultLocale: 'pt-PT',
      },
    ],
    localeDetection: false,
  },
}
```
Then add a middleware in `pages/_middleware.ts` for example.
You'll notice HEAD requests go to `https://example.pt/pt-PT/blog` instead of `https://example.pt/blog` for example.

**Comment by Chris-fe** [comment]
I have the same issue! How to avoid the HEAD prefetch request adding the locale when using Domain Routing as the locale handling stretegy?
