### ISSUE TITLE
Title: incorrect work scripts when switching between pages

### ISSUE THREAD

**Issue by iWatson38** [vercel/next.js#37040]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:

- Platform: win32

- Arch: x64

- Version: Windows 10 Pro

Binaries:

- Node: 16.13.0

- npm: N/A

- Yarn: N/A

- pnpm: N/A

Relevant packages:

- next: 12.1.6

- react: 18.1.0

- react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 101.0.4951.67

### How are you deploying your application? (if relevant)

npm run start:dev

### Describe the Bug

The following transitions after the first one to the pages don't trigger the <Script />

### Expected Behavior

On the second, third, and so on visit to the page, the <Scripts /> I wrote should be triggered

### To Reproduce

Steps to reproduce the error behavior:
1. Go to the first page;
2. Return to the home page;
3. Go back to the first page and make sure that the <Script /> does not work on subsequent visits.

Similarly with the second page (it uses a different script strategy)

Link to the repository: https://github.com/iWatson38/issue-bug-report

**Comment by JanKaifer** [comment]
This works fine in `next@13.1.3`
