### ISSUE TITLE
Fallback: true causes meta tags not to be in source

### ISSUE THREAD

**Issue by lgrayland** [vercel/next.js#37059]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
Binaries:
      Node: 14.17.3
      npm: 6.14.6
      Yarn: 1.22.18
      pnpm: N/A
Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

Azure

### Describe the Bug

Seeing a strange behaviour when using fallback: true, have followed all the documentation regarding fetching data int he getStaticProps method and even using hardcoded value the result is the same. When using fallback: true, locally when the page loads the meta description and title appear in the elements of the console, but inspecting the source they are not present. Where as using fallback: 'blocking' the meta description and title is present in both elements and the source. On our deployed version, the behaviour is slightly different, the first time the page is generated, the meta description and title are missing from the source, however refreshing the page they then become present. Im not 100% if this is an issue or just the way it was working but our SEO team are complaining that title and meta descriptions are missing, testing this with a variety for online crawlers, some seem to pick up the title and description without any problems and others say they are missing

### Expected Behavior

to see the meta description and title in the source code when using fallback:true

### To Reproduce

forked an app and created and [example app](https://codesandbox.io/s/next-blocking-nonblocking-meta-ofu27z) where this can be clearly seen selected the fallback: true page and the title and description are missing, use the fallback: blocking route and both can be found in the source as expected

**Comment by timneutkens** [comment]
This is expected behavior. `fallback: true` serves a statically generated  If you want all requests to hold the fully generated HTML you can use `fallback: 'blocking'`. Crawlers get the `fallback: 'blocking'` behavior in all cases. Please see the documentation here: https://nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-true

**Comment by lgrayland** [comment]
thanks for the quick response, it is what i thought but wanted to confirm
