### ISSUE TITLE
Error: nested Middleware is not allowed (found pages/_middleware) 12.1.7-canary.10

### ISSUE THREAD

**Issue by wadehammes** [vercel/next.js#37051]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.10
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Says I have an error with nested middleware but I only have middleware at the root of pages. The docs page 404s.

<img width="1043" alt="Screen Shot 2022-05-19 at 8 37 54 PM" src="https://user-images.githubusercontent.com/222170/169425983-30f39919-2d88-42fe-b6e0-7fc5f9fe17ea.png">

https://nextjs.org/docs/messages/nested-middleware - this page 404s

### Expected Behavior

Build should compile as normal or the docs page should exist so I know what to change.

### To Reproduce

Have middleware in `pages`.

**Comment by wadehammes** [comment]
Found https://github.com/vercel/next.js/pull/36772 but still, the docs page 404s

**Comment by neverether** [comment]
@wadehammes I think it'll 404 till 12.1.7 is released.

The PR seems to have the new doc page as MD for the time being though: https://github.com/javivelasco/next.js/blob/a23dbe50da0e1608a30ced0d33f4b63b80058ee1/errors/nested-middleware.md
