### ISSUE TITLE
Using `shallow` routing and a `rewrite` middleware fails for dynamic segments (`/[dynamic]`)

### ISSUE THREAD

**Issue by BowlingX** [vercel/next.js#37072]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.10
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 101.0.4951.64

### Describe the Bug

Using a middleware that performs a path rewrite like the following

`middleware.ts`:

```ts
// eslint-disable-next-line @next/next/no-server-import-in-page
import { NextRequest, NextResponse } from 'next/server'

// RegExp for public files
const PUBLIC_FILE = /\.(.*)$/


export function middleware(req: NextRequest) {
  const url = req.nextUrl.clone()

  // Skip public files and API routes
  if (PUBLIC_FILE.test(url.pathname) || url.pathname.startsWith('/api')) {
    return
  }

  url.pathname = `/desktop${url.pathname}` // simplified here for the test case, the middleware will determine the right user agent here

  return NextResponse.rewrite(url)
}

```

Will cause an error (404) and reload the page on the `Link` component for `/` urls when used with `shallow`

Example

```tsx
const Example = () => (
<>
  <Link href="/" shallow>Home</Link> {/* this will fail to resolve and reload the page */}
  <Link href="/?query=myQuery" shallow>Home</Link> {/* this will fail to resolve and reload the page */}
  <Link href="/">Home</Link> {/* this is working */}
  <Link href="/another-page" shallow>Another page</Link> {/* this is also working */}
</>
)
```

The same error happens with `router.push`.

A different error happens also for `router.push`, when used like so:

```ts
  const onClick = useCallback(() => {
    push('/[device]', '/', { shallow: true })
  }, [push])
```
```
Error: The provided `as` value (/) is incompatible with the `href` value (/[device]). Read more: https://nextjs.org/docs/messages/incompatible-href-as
```

The error exists (as far as I can tell) since next `12.1.1`. It works correct in `12.1.0`.

### Expected Behavior

It should not fail with a `404` and reload the page but just route correctly.

### To Reproduce

I created a reproducible case here:
https://stackblitz.com/edit/nextjs-xljvem?file=pages/[device]/index.js

And here a fork with `12.1.0`:

https://stackblitz.com/edit/nextjs-5qakb4?file=_middleware.js

**Comment by BowlingX** [comment]
@minardimedia I would say you are running into the same changed behavior yes; Try if it works with version 12.1.0.

**Comment by minardimedia** [comment]
@BowlingX  Hi I just try with version 12.1.0  and in this version it breaks 

Original URL: `http://casablanca.nomadtest.com:3001/room/0e161feb-89ae-4373-a3f1-55ac5eed9027`

Shallow push URL: `http://casablanca.nomadtest.com:3001/_sites/casablanca/room/0e161feb-89ae-4373-a3f1-55ac5eed9027?start_date=12-12-2022`

In this version this provoke a refresh resulting in 404 

So I guess v12.1.6 somehow works it just writes the wrong URL while using NextResponse.rewrite(url) in the middleware

Here is the middleware from the multu-tenat example

```
export default function middleware(req: NextRequest) {
  const url = req.nextUrl.clone();
  const { pathname } = req.nextUrl;
  const hostname = req.headers.get("host");
  const currentHost = hostname!.replace(`.nomadtest.com:3001`, "");

  if (pathname.startsWith(`/_sites`)) {
    return new Response(null, { status: 404 });
  }

  if (!pathname.includes(".") && !pathname.startsWith("/api")) {
    if (currentHost === "host") {
      url.pathname = `/host${pathname}`;
      return NextResponse.rewrite(url);
    } else if (hostname === "nomadtest.com:3001") {
      return NextResponse.rewrite(url);
    } else {
      url.pathname = `/_sites/${currentHost}${pathname}`;
      return NextResponse.rewrite(url);
    }
  }
  return NextResponse.rewrite(url);
}
```
