### ISSUE TITLE
with-jest-app example doesn't work

### ISSUE THREAD

**Issue by rdgifford** [vercel/next.js#37082]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
➜  with-jest git:(canary) npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
    Binaries:
      Node: 18.2.0
      npm: 8.9.0
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

warn  - Latest canary version not detected, detected: "12.1.6", newest: "12.1.7-canary.9".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Describe the Bug

After setting up the with-jest example from [the documentation](https://nextjs.org/docs/testing), `yarn test` consistently fails.

### Expected Behavior

Whether using `npx` or directly cloning the repo and running `yarn test`, jest fails consistently. I've verified this on my work laptop as well.

The error is consistent: `SyntaxError: Unexpected token '.'`

![Screen Shot 2022-05-20 at 6 14 02 PM](https://user-images.githubusercontent.com/13399300/169628763-a152746a-69b2-4fe1-9dbd-b0f8e933190b.png)

### To Reproduce

Clone the repo or use `npx create-next-app@latest --example with-jest with-jest-app` following [the documentation](https://nextjs.org/docs/testing).

**Comment by rdgifford** [comment]
I've also tried this against `v12.1.7-canary.9` to the same effect.

**Comment by devrsi0n** [comment]
Same here, [this PR](https://github.com/devrsi0n/chirpy/pull/313) bumps next to 12.1.6, but it fails with jest tests, it seems due to `next/jest` changes.

**Comment by keeeparis** [comment]
Test failes due to the fact that styles for index page located in ```pages``` folder. 
In order to pass the tests you should:
1. Move index.module.css into ```src/styles``` folder;
2. In ```index.tsx``` on 4th line change imports to -> ```@/styles/index.module.css```

**Comment by ijjk** [comment]
Hi, this example is working correctly against the latest canary of Next.js please update and give it a try!
