### ISSUE TITLE
Docs: What about busting the build cache on data update? Is this possible?

### ISSUE THREAD

**Issue by tayloraucoin** [vercel/next.js#37109]
### What is the improvement or update you wish to see?

I am wondering about something that is not mentioned on the Pages documentation https://nextjs.org/docs/basic-features/pages 

Is it possible to blow up the static cache on data updates? 

As in, a shop on a marketplace updates its bio. But the page is statically rendered. The content change is not seen until the next build update. 

However, speaking from a place of not knowing the internal process, I am wondering if it is possible to **only rebuild a single page** in the overall build of the app? 

So the route for /shop/:slug is updated programmatically on the value change. 

Even if this is not possible, maybe mentioning that in the docs would help expel this question. I recall wondering this same thing when I first read them. Now I have a use case that needs it. 

### Is there any context that might help us understand?

Since most apps (mine is e-commerce) benefit from having dynamic, live updates right away. But there is the tradeoff of it not being as performant if done with full server-side every time. 

As an alternative, is there a way to rebuild the app every x number of minutes? So we could in theory have all the changes occur daily. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/pages

**Comment by ijjk** [comment]
Hi, it sounds like you are looking for on-demand ISR which is documented here https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation-beta

**Comment by tayloraucoin** [comment]
Brilliant. So happy that is available. 

I still experienced the behaviour of recent content unavailable, with revalidate being set to 1.

"next": "^12.1.6",

**Comment by ijjk** [comment]
Closing as it seems the above doc is what was desired, we will expand on this document as this feature becomes stable as well.

**Comment by tayloraucoin** [comment]
@ijjk this doesn't seem to work the way I expect it to. 

Expected behaviour:
- npm build + npm start (local)
- load /shop/shop:id page
- in a separate tab, navigate to shop dashboard
- change the shop name and submit
- refresh /shop/shop:id page one or more times to see change happen to a new name

Current behaviour:
- no change to name value on /shop/shop:id page at all
- since the dashboard is client-side fetching, the new value appears correctly 

I have both `revalidate: 1` on the shop page and I also am using the manual `Using On-Demand Revalidation` that utilizes `await res.unstable_revalidate(req.body.path);` 

Do you have an idea of what could be going wrong?

**Comment by tayloraucoin** [comment]
I have had `revalidate: 1` on for a while and never had this portion work properly. 

However, when I add a new record (like a new shop) it works and the new shop is available right away

**Comment by ijjk** [comment]
Can you share a reproduction where you are not seeing the revalidation occur correctly?

**Comment by tayloraucoin** [comment]
I don't really have the bandwidth at the moment to create a project. This would take quite a lot in order to make something similar to what I have. 

I'm in the airport on the way to an important event. Trying to get the server-side working again in order to send profiles to my sellers before then. 

Does anything here look odd? Seems like it should be extremely straight-forward

```
import queryApollo from "../../utils/graphql/query-apollo";
import QUERY_SHOP_ARTICLE_TYPES from "../../gql/queries/shop/shop-article-types";
import QUERY_SHOP_BY_SLUG from "../../gql/queries/shop/shop-by-slug";
import QUERY_SHOP_PATHS from "../../gql/queries/shop/shop-paths";
import ShopInterface from "../../components/interfaces/app/shop/Shop";

const Shop = ({ shop, shopArticleTypes, shopResponse }) => (
  <ShopInterface
    shop={shopResponse}
    shopArticleTypes={shopArticleTypes}
    shopSlug={shop}
  />
);

// This function gets called at build time
export async function getStaticPaths() {
  const shopPathsResponse = await queryApollo(QUERY_SHOP_PATHS);
  return {
    fallback: "blocking",
    paths: shopPathsResponse.data.shops.nodes
      .filter((n) => n.status === "ACTIVE" || n.status === "AWAY")
      .map((s) => {
        return {
          params: {
            shop: s.slug,
          },
        };
      }),
  };
}

// This function gets called at build time
export async function getStaticProps({ params }) {
  try {
    const shopResponse = await queryApollo(QUERY_SHOP_BY_SLUG, {
      count: 12,
      orderBy: "NAME_ASC",
      slug: params?.shop,
    });

    const shopArticleTypeResponse = await queryApollo(
      QUERY_SHOP_ARTICLE_TYPES,
      {
        shopSlug: params?.shop,
      }
    );

    if (shopResponse?.data?.shopBySlug) {
      return {
        props: {
          shop: params?.shop,
          shopArticleTypes: JSON.parse(
            shopArticleTypeResponse.data.shopArticleTypes.json
          ),
          shopResponse: shopResponse?.data?.shopBySlug,
        },
        revalidate: 1,
      };
    }

    return { notFound: true };
  } catch (error) {
    console.error("SHOP SERVER SIDE QUERY ERROR: ", error);
    return { notFound: true };
  }
}

export default Shop;

```

**Comment by tayloraucoin** [comment]
@ijjk The /shop/:id page works, since revalidate is stable and works for the :id page it is on.

However, I need to update my /browse pages too. I have this setup on the listing submit action and am getting 200 status confirmations that the revalidation was successful. But nothing changes in the browser for the browse url. 

An example route I am triggering an update for is `/browse/listings/:category`. The `path` I am passing is for sure correct. 

I am using the provided handler logic from the documentation. 

How long has this beta feature been in use? Is there anything more I can be doing?

**Comment by tayloraucoin** [comment]
@ijjk I don't know how it worked before, but now after repetitive attempts, the revalidation won't work in any circumstance. I'm using the same code in page (includes the notFound revalidate) and the `unstable_revalidate` solution. Neither makes the `/shop/:id` page value update as it should. 

Feeling pretty down about this right now. Really don't know why this isn't working as it should.

**Comment by ijjk** [comment]
Does your queryApollo handling have any caching implemented, if you log the data being returned from getStaticProps are you seeing fresh data correctly?

**Comment by tayloraucoin** [comment]
@ijjk good questions

I've added a console.log to see what, and if, the shop response is called and different. It is called, but the value is the same as before. No updates. 

`queryApollo` is just a small util for using `apollo.query`. 

That sounds like a likely possibility, I did however check the documentation, and `resultCaching: false` has been added with the same behaviour occurring https://www.apollographql.com/docs/react/caching/cache-configuration#resultcaching 

```
import apollo from "./apollo-client";

export default async function queryApollo(
  query: any,
  variables?: any,
  signal?: any
) {
  const params: {
    context: any;
    errorPolicy: "none" | "ignore" | "all";
    query: any;
    resultCaching: boolean;
    variables: any;
  } = {
    context: undefined,
    query,
    errorPolicy: "all",
    resultCaching: false,
    variables: undefined,
  };

  if (variables) params.variables = variables;

  if (signal) {
    params.context = {};
    params.context.fetchOptions = {};
    params.context.fetchOptions.signal = signal;
  }

  return await apollo.query(params);
}

```

**Comment by tayloraucoin** [comment]
I'm also getting this weird logging, from loading my fonts from the public directory.

It is logging after the shop response and slug, from their values, which is strange.

```
-------- SHOP SERVER SIDE SLUG "Inter-Regular.woff2"
-------- SHOP SERVER SIDE {"data":{"shopBySlug":null},"loading":false,"networkStatus":7,"stale":false}
```

**Comment by tayloraucoin** [comment]
@ijjk again, great idea. 

Same result though ... 

I'm less familiar with CDN. I don't believe I have any running. This here is just `npm build` `npm start` on local to test. 

Getting pretty discouraged about this. I'm at the point that I would pay a contractor from your team to take a look at it. If that could be an option. Because by all accounts this really should be working. 

Here is my apolloClient initialization file after the change:

```
import "cross-fetch/polyfill";
import ApolloClient from "apollo-boost";

import { AUTH_TOKEN } from "../../constants/keys";
import { getAPIUrl } from "../url";

const APIUrl = getAPIUrl();

const defaultOptions = {
  watchQuery: {
    fetchPolicy: "no-cache",
    errorPolicy: "ignore",
    returnPartialData: true,
  },
  query: {
    fetchPolicy: "no-cache",
    errorPolicy: "all",
  },
};

const apollo = new ApolloClient({
  uri: `${APIUrl}/graphql`,
  fetchOptions: {
    credentials: "include",
  },
  defaultOptions: defaultOptions,
  request: async (operation) => {
    if (typeof localStorage !== "undefined") {
      const token = localStorage.getItem(AUTH_TOKEN);
      if (token) {
        operation.setContext({
          headers: {
            authorization:
              token && token !== "undefined" ? `Bearer ${token}` : "",
          },
        });
      }
    }
  },
});

export default apollo;
```

**Comment by tayloraucoin** [comment]
I'll be mostly unavailable for the next 4 days. At a live event to help promote the software. But I will try and check in on this thread as often as I can since this is a priority. 

Thank you so much for all your help
