### ISSUE TITLE
bug when using jest multiproject runner with nextjs

### ISSUE THREAD

**Issue by sibelius** [vercel/next.js#37104]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.7.0
      Yarn: 1.22.19
      pnpm: 7.0.1
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

jest

### Describe the Bug

yarn jest throws the following error

Error: > Couldn't find a `pages` directory. Please create one under the project root
at Object.findPagesDir (ccsseraphini/node_modules/next/dist/lib/find-pages-dir.js:50:15)
at ccsseraphini/node_modules/next/dist/build/jest/jest.js:31:47
at readConfigFileAndSetRootDir (ccsseraphini/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:152:26)
at async readConfig (ccsseraphini/node_modules/jest-config/build/index.js:216:18)
at async Promise.all (index 1)
at async readConfigs (ccsseraphini/node_modules/jest-config/build/index.js:425:27)
at async runCLI (ccsseraphini/node_modules/@jest/core/build/cli/index.js:140:59)
at async Object.run (ccsseraphini/node_modules/jest-cli/build/cli/index.js:155:37)

### Expected Behavior

it should work 

### To Reproduce

run `yarn jest` in this repo https://github.com/sibelius/ccsseraphini

it is failing on CI as well https://github.com/sibelius/ccsseraphini/runs/6539464476?check_suite_focus=true

**Comment by ijjk** [comment]
Hi, it looks like you are leveraging the `next/jest` config and providing the `dir` option for a non-Next.js app here https://github.com/sibelius/ccsseraphini/blob/612a87b0bb0d2c57f291b60451b396ecebfc4f08/apps/cli/jest.config.js so it's failing to find a pages folder for it.

**Comment by sibelius** [comment]
the error also happens to package web

try to keep only web here https://github.com/sibelius/ccsseraphini/blob/612a87b0bb/jest.config.js#L5, and you see the same error

what is the best way to use next/jest without `pages` folder ?

I'd like to use the rust transform instead of babel one

**Comment by ijjk** [comment]
If you don't set `options.dir` it should skip trying to locate the pages directory or a `next.config.js` x-ref: https://github.com/vercel/next.js/blob/1b4e2ccd639e7f9661d1e8bbb3920048adba5bb3/packages/next/build/jest/jest.ts#L57
