### ISSUE TITLE
Requested and resolved page mismatch when using Image and src includes "../"

### ISSUE THREAD

**Issue by TheLexoPlexx** [vercel/next.js#37175]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
Binaries:
  Node: 16.14.2
  npm: 8.5.0
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.1.7-canary.15
  react: 17.0.2
  react-dom: 17.0.2

### Describe the Bug

May or may not be a follow-up to Issue #9536.

src of the Image-Component includes a "/../", which then of course causes the error stated above, however, there is no alternate way of handling images using absolute paths (or maybe I misunderstood the docs regarding image loader).

### Expected Behavior

No Error when setting an absolute path such as `/public/image.jpg`

### To Reproduce

See https://github.com/TheLexoPlexx/issue_repo

**Comment by icyJoseph** [comment]
Hi,

I believe you don't need to think of relative paths when it comes to the public directory.

```jsx
 <Image src="/logo-2_Red.jpg" width={250} height={152} />
```

Next.js will resolve that to the `public` directory.

More info in the [docs about static file serving](https://nextjs.org/docs/basic-features/static-file-serving).

**Comment by TheLexoPlexx** [comment]
I was pretty sure I tested that which got me confused in the first place, sorry for bothering you, have a nice day!
