### ISSUE TITLE
Prefetching in preview mode causes fresh data to never be re-fetched

### ISSUE THREAD

**Issue by OriginalEXE** [vercel/next.js#37190]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

In static deployment mode, when preview mode is on, link prefetching still populates the routes cache (for example, on link hover or when they come into viewport), as seen here: https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/router/router.ts#L1854. This means that if one later calls `router.replace(router.asPath)`, the fresh data will not be fetched as it will simply pull it from the cache. This causes any system that wants to trigger a re-fetch without refreshing unable to do so, as once cached, the data will always be served stale.

### Expected Behavior

Calling `router.replace(router.asPath)` should always fetch fresh data. Prefetch should therefore not happen in preview mode.

### To Reproduce

- Statically generate your site
- Add at least one Link that points to the page you are currently on
- Go into preview mode
- Call `router.replace(router.asPath)`

You should see a network request for the fresh data, but you instead see nothing as the data is loaded form a (possibly) stale cache populated by pre-fetching.

**Comment by ijjk** [comment]
Hi, thanks for opening an issue for this, it should be fixed by https://github.com/vercel/next.js/pull/37201
