### ISSUE TITLE
Next Link component has unknown-prop warning when using `legacyBehavior={false}`

### ISSUE THREAD

**Issue by brennarvo** [vercel/next.js#37248]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Binaries:
  Node: 16.13.1
  npm: 8.1.2
  Yarn: 1.22.17
  pnpm: N/A
Relevant packages:
  next: 12.1.7-canary.18
  react: 17.0.2
  react-dom: 17.0.2

### Which example does this report relate to?

hello-world

### What browser are you using? (if relevant)

Chrome 97.0.4692.71

### Describe the Bug

Passing a value of `false` to the `legacyBehavior` prop on the [Link component](https://nextjs.org/docs/api-reference/next/link) results in an [unknown-prop warning](https://reactjs.org/warnings/unknown-prop.html) from React.

### Expected Behavior

There should be no warning about an unknown-prop.

### To Reproduce

1. Visit the [StackBlitz link](https://stackblitz.com/edit/github-fjl3go?file=pages/index.js)
2. Navigate to the `index.js` file (if not there already)
3. Observe the unknown-prop warning in the terminal related to `legacyBehavior`

Screenshot:
![Screen Shot 2022-05-27 at 10 49 26 AM](https://user-images.githubusercontent.com/94568316/170734342-7ff435ad-9110-4090-a5f9-b7464ac48629.png)

**Comment by sshyam-gupta** [comment]
I can check this issue.

**Comment by dkt0591** [comment]
i got same problem
