### ISSUE TITLE
Navigation Routes BUG ????

### ISSUE THREAD

**Issue by Manuel-ZM** [vercel/next.js#37255]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
PS E:\Websites\cryptosite> npx next info

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.18
      react: 18.1.0
      react-dom: 18.1.0

warn  - Latest canary version not detected, detected: "12.1.7-canary.18", newest: "12.1.7-canary.19".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

npm run build

### Describe the Bug

nextjs + tailwind

i tried
```
const Navlinks = [
    {
        id: 1,
        path: '/login',
        label: 'Login',
        icon: faUserAstronaut
    },
```

```
default export = [
    {
        id: 1,
        path: '/login',
        label: 'Login',
        icon: faUserAstronaut
    },
```

i even added id: thought it was an issue on index...

making a navigation list and trying to map it after shows errors in the build, i think it shouldnt be the case because they are static links, seen a lot of threads about different solutions but i really dont understand why its not building it

https://github.com/Manuel-ZM/cryptotest/blob/master/pages/components/navigation.js
https://github.com/Manuel-ZM/cryptotest/blob/master/pages/components/navlinks.js
https://github.com/Manuel-ZM/cryptotest/blob/master/pages/components/layout.js

### Expected Behavior

```
PS E:\Websites\cryptosite> npm run build

> cryptosite@0.1.0 build
> next build && next export

info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully

> Build optimization failed: found page without a React Component as default export in
pages/components/navlinks

See https://nextjs.org/docs/messages/page-without-valid-component for more info.

info  - Collecting page data .
PS E:\Websites\cryptosite>
```

### To Reproduce

https://github.com/Manuel-ZM/cryptotest

**Comment by ijjk** [comment]
Hi, this is due to your components being kept in your pages folder as mentioned by that error link https://nextjs.org/docs/messages/page-without-valid-component 

You should move any non-pages outside of the pages folder.
