### ISSUE TITLE
Using Pdfjs-dist throw an error SyntaxError: Unexpected token '||='

### ISSUE THREAD

**Issue by dformteam** [vercel/next.js#37262]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.15.5
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.19
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome Version 100.0.4896.127 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

I'm having a trouble when using pdfjs-dist on Nextjs as follows:

```bash
error: node_modules\pdfjs-dist\build\pdf.js:1707
    return this._jsActionsPromise ||= this._transport.getPageJSActions(this._pageIndex);
                                  ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.pdfjs-dist (D:\work\2021\CJ1-New\cj1-new\.next\server\pages\existing-customer\register-review.js:646:18)
    at __webpack_require__ (D:\work\2021\CJ1-New\cj1-new\.next\server\webpack-runtime.js:33:42)
    at eval (webpack-internal:///./cores/utils/pdf.js:5:68) {
}
```
It seems nextjs could not transfrom to es5 [Babel](https://babeljs.io/docs/en/babel-plugin-proposal-logical-assignment-operators)

### Expected Behavior

I expect that one can work perfectly on Nextjs for pdf manipulating

### To Reproduce

1. install pdfjs-dist
```
npm i pdfjs-dist@2.13.216
```

2. Write a small function to convert any PDF file to images

```typescript
import * as PDFJS from 'pdfjs-dist';

export const toImage = async ({ blob, scale }) => {
  let pdf;
  const getPage = (num) => {
    return new Promise((resolve, reject) => {
      pdf.getPage(num).then((page) => {
        if (typeof scale !== 'number' || isNaN(scale) || scale < 0) {
          scale = 1;
        }
        const viewport = page.getViewport({ scale });
        const canvas = document.createElement('canvas');
        const canvasContext = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;
        page
          .render({
            canvasContext,
            viewport,
          })
          .promise.then(() => {
            resolve(canvas.toDataURL('image/png', 1));
          })
          .catch((error) => {
            reject(error);
          });
      });
    });
  };

  return PDFJS.getDocument(blob).promise.then((pdfx) => {
    const pages = [];
    pdf = pdfx;
    for (let i = 0; i < pdfx.numPages; i++) {
      pages.push(getPage(i + 1));
    }

    return Promise.all(pages)
      .then((imgPages) => {
        return imgPages;
      })
      .catch(console.error);
  });
};
```

3. Consume it!.
That all!

**Comment by SukkaW** [comment]
It appears that pdfjs are using Logical OR assignment, which is only supported since Node.js 15.0.0.

If you are using pdfjs on the server-side, consider updating your Node.js version to 16. If you are using pdfjs on the client-side, please use [next-transpile-modules](https://github.com/martpie/next-transpile-modules) to transpile your module (Next.js by default will not touch files in the `node_modules`).

**Comment by dformteam** [comment]
> It appears that pdfjs is using Logical OR assignment, which is only supported since Node.js 15.0.0.
> 
> If you are using pdfjs on the server-side, consider updating your Node.js version to 16. If you are using pdfjs on the client-side, please use [next-transpile-modules](https://github.com/martpie/next-transpile-modules) to transpile it (Next.js just won't touch any file in the `node_modules`).

It's solved, Thank for your support.
