### ISSUE TITLE
getting "Can't perform a React state update on an unmounted component" error on next/Image component

### ISSUE THREAD

**Issue by sabres207** [vercel/next.js#37276]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.19.1
      npm: 6.14.16
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

chrome

### Describe the Bug

I keep getting this react error in my project,
when (and only when) I remove this one call to <Image ... />, the error stops showing.

btw, I also use next/image in other places, but it only happens here.
anyone got this error before?

### Expected Behavior

using next/image without getting "Can't perform a React state update on an unmounted component" error

### To Reproduce

```
import Image from 'next/image'

export const Avatar = ({ avatarUrl }) => {

  return (
    <div className="relative rounded-full overflow-hidden w-9 h-9">
      <Image src={avatarUrl} layout="fill" />
    </div>
  )
}
```

**Comment by ijjk** [comment]
Closing per above as this should be corrected in the latest version
