### ISSUE TITLE
TypeScript Target Compiler Option is Silently Ignored

### ISSUE THREAD

**Issue by jasonboninger** [vercel/next.js#37271]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.19
      react: 18.1.0
      react-dom: 18.1.0

### How are you deploying your application? (if relevant)

next export

### Describe the Bug

Changing the `tsconfig.json` -> `compilerOptions` -> `target` setting has no effect on static export builds and no error or warning occurs to indicate this.

This is my first time filing a bug report, so please let me know if I'm doing anything wrong or unhelpful!

### Expected Behavior

Changing the TypeScript build target should be respected by the build engine like other TypeScript configuration settings, or an error or warning should indicate that the TypeScript target must always be a certain value.

### To Reproduce

- Create a new project: `npx create-next-app@canary --typescript`
- Modify the `build` script in `package.json` to be `next build && next export`
  - Remove the `Image` import and `Image` tag from `index.tsx` because it will prevent static build from succeeding
- Modify `pages/_app.tsx` with a trivial piece of functionality which uses an `ES2022` feature

```
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { useEffect, useState } from 'react';

class Test {
  #forMeOnly = true;
  
  doSomething(): void {
    console.log("FOR ME ONLY", this.#forMeOnly);
  }
}

function MyApp({ Component, pageProps }: AppProps) {
  const [test] = useState(new Test());
  useEffect(() => test.doSomething());
  return <Component {...pageProps} />
}

export default MyApp
```

- Modify `compilerOptions` -> `target` in `tsconfig.json` to be `ES2022`
- Execute `npm run build`
- Note that in the chunk exported for `_app-<cache-bust>.js` in `out/_next/static/chunks/pages` that the private field `#forMeOnly` is enforced using `WeakMap` and not using the native JavaScript feature from `ES2022`
- Expected to see `#forMeOnly` (or a minified version) and no `WeakMap`

**Comment by timneutkens** [comment]
Feel free to open a PR to add a warning. `tsc` is not used to compile the code so these options don't have an effect on output, only a few options that people were using babelrc for are respected.

**Comment by jasonboninger** [comment]
I suspected as much, but is it intent that framework users shouldn't have control over compilation in this way?

> `tsc` is not used to compile the code so these options don't have an effect on output, only a few options that people were using babelrc for are respected.

Thanks for the quick reply! Is there another way to configure what JavaScript features the compiler considers available? Perhaps the warning message could redirect people to that?

**Comment by balazsorban44** [comment]
We have an RFC to support Browserslist configuration: https://github.com/vercel/next.js/discussions/33227

An experimental support was added in: https://github.com/vercel/next.js/pull/36584

**Comment by darshkpatel** [comment]
> Feel free to open a PR to add a warning. `tsc` is not used to compile the code so these options don't have an effect on output, only a few options that people were using babelrc for are respected.

Faced this issue recently. I agree that adding a warning would be a good idea for now. 
What warning message should be added? Happy to raise a PR.

**Comment by mkayander** [comment]
Hi everyone! Please feel free to share any thoughts on the linked PR i just pushed. #43582
