### ISSUE TITLE
Image: error 400 when path contains space

### ISSUE THREAD

**Issue by Arctomachine** [vercel/next.js#37273]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 17.9.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.19
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

If page includes image whose file name contains spaces, it gives an error in console. It only happens when not importing image and instead giving it src path relative to public folder.

So `public/assets/picture name with space.jpg` and its call `<Image src='/assets/picture name with space.jpg'/>` would result in
```
The requested resource isn't a valid image for /assets/picture name with space.jpg received text/html; charset=utf-8
ImageError: The requested resource isn't a valid image.
```

If image name does not contain spaces, there is no error.
If image is imported, there is no error.
No errors in dev mode.
Sharp package does not affect it.

### Expected Behavior

Serve image without error

### To Reproduce

1. Create new project
2. Add any image `example image.jpg` into public folder
3. Add `<Image src='/example image.jpg'/>` into page
4. Build and start app
5. Scroll to added image

**Comment by Arctomachine** [comment]
Similar issue is mentioned in https://github.com/vercel/next.js/issues/27210, but it is already marked as resolved, yet my problem is present in current version.

**Comment by JanKaifer** [comment]
It works now https://github.com/JanKaifer/next-repro-37273.git
