### ISSUE TITLE
The automatically generated `tsconfig.json` file is missing `moduleResolution`

### ISSUE THREAD

**Issue by liby** [vercel/next.js#37296]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
$ next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.17
      pnpm: 7.0.0
    Relevant packages:
      next: 12.1.7-canary.23
      react: 18.1.0
      react-dom: 18.1.0
```

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

Follow the instructions to install TypeScript,  try starting the development server again.

View the generated `tsconfig.json` file:
> Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.ts
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/38807139/170955941-a9d2c9fd-8582-488b-9121-6cf145fc4740.png">

### Expected Behavior

The generated `tsconfig.json` file should contain the `moduleResolution` key.

### To Reproduce

```
# If you’re using npm
npm install --save-dev typescript @types/react @types/node

# If you’re using Yarn
yarn add --dev typescript @types/react @types/node

npm/yarn run dev
```

View the `tsconfig.json` file

**Comment by nosovandrew** [comment]
I've reached with the same issue when setup my project manually. Then I removed the result and try to use [Automatic Setup](https://nextjs.org/docs#automatic-setup). This solved my problem!

**Comment by ubervincent** [comment]
I have that issue as well.

I also added tsconfig.json manually and have Next generate the config.

Adding moduleResolution works!

**Comment by quavious** [comment]
Adding `"moduleResolution": "node"` to tsconfig.json was worked.

**Comment by hkbertoson** [comment]
If I create a next app and then add Typescript to it after. I get the error. But if I run `npx create-next-app --typescript` I don't get the error. Why is this? 

![image](https://user-images.githubusercontent.com/44106297/183144756-1969fff4-26be-4048-827d-8ffa3b7cba3f.png)

![image](https://user-images.githubusercontent.com/44106297/183144828-c3cf5f00-8ee6-4782-941c-704ebf7bf5a4.png)

**Comment by OksanaShtanhei** [comment]
I added moduleResolution manually and it works

**Comment by karishmashuklaa** [comment]
> Adding `"moduleResolution": "node"` to tsconfig.json was worked.

This works effortlessly.
