### ISSUE TITLE
Links not prefetching even if they are in viewport

### ISSUE THREAD

**Issue by nithiwatter** [vercel/next.js#37290]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

   Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 14.19.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Firefox 100.0.2 (64-bit)

### How are you deploying your application? (if relevant)

Check official website

### Describe the Bug

Simple example - check https://nextjs.org/ website - on Chrome and Edge, various pages are prefetched automatically (ex. Showcase and Blog)

![image](https://user-images.githubusercontent.com/59894785/170904693-3043c37a-ddd0-41ad-88b9-08d3e802396f.png)

On Firefox, however, even if the links are in view port, they are not prefetched. 

![image](https://user-images.githubusercontent.com/59894785/170904759-6220176b-fb0c-4799-9f3b-8e22074fc5a1.png)

These links on Firefox are only prefetched when hovering. 

### Expected Behavior

I would expect links on Firefox to be prefetched automatically (just like on Chrome or Edge). 

### To Reproduce

As outlined above.

**Comment by ijjk** [comment]
Hi, can you confirm you don't have prefetching disabled in firefix under `about:config`, specifically `network.prefetch-next`?

**Comment by nithiwatter** [comment]
Ok, I am sorry - I did not know about that setting - turning it on to `true` makes everything work as expected.

**Comment by nithiwatter** [comment]
Now that I changed the setting, something weird happened - each link is being prefetched twice on Firefox:

![image](https://user-images.githubusercontent.com/59894785/170907222-5a782581-25da-415c-bcc1-21a5191050ec.png)

Compare this with Edge:

![image](https://user-images.githubusercontent.com/59894785/170907331-37f0c601-e0a9-42b1-a00d-4e89ceeffee5.png)

Is this expected behavior?

**Comment by ijjk** [comment]
That is expected, this is how the devtools shows the requests, one is the prefetch and the second is when the script tag is added to the page which reuses the prefetched request
