### ISSUE TITLE
@next/next/no-server-import-in-page ESLint rule throws on test files

### ISSUE THREAD

**Issue by rikkit** [vercel/next.js#37309]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Tue Jun 23 12:58:10 UTC 2020
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 3.2.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0
```

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When a test file in the pages folder exists that imports `next/server`, the rule `@next/next/no-server-import-in-page` throws during `next build`.

### Expected Behavior

Test files, either those in `__tests__` or `file.test.ts` should be ignored for this rule

### To Reproduce

package.json
```
    "@typescript-eslint/parser": "^5.25.0",
    "eslint": "^8.15.0",
    "eslint-config-next": "^12.1.6",
    "eslint-plugin-react": "^7.29.4",
```

.eslint.json
```json
{
  "root": true,
  "extends": "next/core-web-vitals",
  "parser": "@typescript-eslint/parser"
}
```

Create a file at `pages/__tests__/example.test.ts`

```ts
import "jest";
import { NextRequest } from "next/server";

describe("example", () => {
  it("should pass", () => {});
});
```

Run next build or deploy to Vercel

**Comment by jaloliddinmirzayev** [comment]
#include <iostream>
#include <cstdlib>
#include <math.h>
using namespace std;
int i;
float n, x[100], xS, y[100], yS, x2[100], x2S, xy[100], xyS, a0, a1, a;
int main(int argc, char*argv[])
{
    cout<<endl<<"Approksimatsiya uchun Eng kichik kvadratlar usuli chiziqli model"<<endl;
    cout<<endl<<"n="; cin>>n;
    cout<<endl<<"x:";
    for(i=1; i<=n; i++) {cin>>x[i]; xS+=x[i];}
    cout<<endl<<"summa x:"<<xS<<endl;
    cout<<endl<<"y:";
    for(i=1; i<=n; i++) {cin>>y[i]; yS+=y[i];}
    cout<<endl<<"summa^y:"<<yS<<endl;
    cout<<endl<<"x^2:";
    for(i=1; i<=n; i++) {x2[i]=x[i]*x[i]; cout<<x2[i]<<"   "; x2S+=x2[i];}
    cout<<endl<<"summa^x:"<<x2S<<endl;
    cout<<endl<<"y*y:";
    for(i=1; i<=n; i++) {xy[i]=x[i]*y[i]; cout<<xy[i]<<"   "; xyS+=xy[i];}
    cout<<endl<<"summa x*y:"<<xyS<<endl;

a0=(-xyS/xS+yS/n)/(-x2S/xS+xS/n); cout<<endl<<"a0="<<a0<<endl;
a1=(-xyS/x2S+yS/xS)/(-xS/x2S+xS); cout<<endl<<"a1="<<a1<<endl;
cout<<endl<<"y="<<a0<<"x";
if(a1<0) cout<<a1<<endl; else cout<<"+"<<a1<<endl;
cout<<endl<<"a="; cin>>a; cout<<endl<<"y="<<a0*a+a1<<endl<<endl;
return 0;
}

**Comment by Shubhamchinda** [comment]
@rikkit I'd like to work on this.

**Comment by rikkit** [comment]
@Shubhamchinda go for it

**Comment by aboqasem** [comment]
@Shubhamchinda are you planning to work on this or do I take it over?

**Comment by Shubhamchinda** [comment]
> @Shubhamchinda are you planning to work on this or could I take it over?

@aboqasem Please take it.

**Comment by DZuz14** [comment]
@aboqasem Any progress on this?

**Comment by aboqasem** [comment]
> @aboqasem Any progress on this? 

There is already an open PR regarding the issue. I believe they would review it when they have the time to.
