### ISSUE TITLE
Internationalized Routing

### ISSUE THREAD

**Issue by sfeir-pach** [vercel/next.js#37310]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
    Binaries:
      Node: 18.0.0
      npm: 8.6.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I got locale problem, as explain in the [doc](https://nextjs.org/docs/advanced-features/i18n-routing) I would like to let any user choose then favorite language without change the URL/refresh : 

> Note that to handle switching only the locale while preserving all routing information such as [dynamic route](https://nextjs.org/docs/routing/dynamic-routes) query values or hidden href query values, you can provide the href parameter as an object:

But obviously it's not work (that's why my issue)

### Expected Behavior

I expect to change the locale and thank to i18n change the language content of my App

### To Reproduce

use the same params present in the [doc](https://nextjs.org/docs/advanced-features/i18n-routing)

**Comment by balazsorban44** [comment]
Please have a look at the documentation here: https://nextjs.org/docs/advanced-features/i18n-routing#transition-between-locales

**Comment by sfeir-pach** [comment]
Thx but as I tell you I read the documentation and it's not working but I figured out by change the middleware you gave....

/pages/_middleware
`export function middleware(request: NextRequest) {
	const shouldHandleLocale =
		!PUBLIC_FILE.test(request.nextUrl.pathname) &&
		!request.nextUrl.pathname.includes('/api/') &&
		request.nextUrl.locale === 'default';

	return shouldHandleLocale
		? NextResponse.redirect(`/en${request.nextUrl.href}`)
		: undefined;
}`

i18next.config.js
`
module.exports = {
	i18n: {
		locales: ['en', 'fr'],
		defaultLocale: 'fr',
		localeDetection: false,
	},
	trailingSlash: true,
};
`

So I gave you my config, to update the documentation or make something more explicite thank you

**Comment by balazsorban44** [comment]
I just tried:

```js
// pages/index.js
...
<Link locale="en" href="/">
  <a>To EN</a>
</Link>
...
```

And the page correctly transitions to `en`, so I think the docs should be OK. What issue are you seeing? :thinking: Could you add a full reproduction that I could look at?
