### ISSUE TITLE
Font optimization W3 Validator throws error on <meta name="next-font-preconnect" />

### ISSUE THREAD

**Issue by alveshelio** [vercel/next.js#37314]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.18
      pnpm: 7.1.7
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

Nextjs font optimization is generating a tag `<meta name="next-font-preconnect"/>`, is is throwing an error when validating the HTML in W3 validator. **Element [meta](https://html.spec.whatwg.org/multipage/#the-meta-element) is missing one or more of the following attributes: content, property.**

Looking at the code, I believe this is the issue is here:  https://cs.github.com/vercel/next.js/blob/39302141b5ea3a1e9a55af906129a44675337cf9/packages/next/pages/_document.tsx#L828

### Expected Behavior

`<meta name="next-font-preconnect"/>` should have attributes `content` and `property`

### To Reproduce

In `_document` page create a link tag to import a Google font
```ts
<link
  rel="preconnect"
  href="https://fonts.gstatic.com/s/spacegrotesk/v6/V8mDoQDjQSkFtoMM3T6r8E7mPb94C_k3HqUtEw.woff2" 
/>
```
`yarn build` and `yarn start` and validate the source here: https://validator.w3.org/nu/#textarea

**Comment by balazsorban44** [comment]
Could you attach a small reproduction?

I'm trying to validate this, but I believe we replace that tag, so it should not reach the browser.

In my reproduction the `<meta name="next-font-preconnect"/>` tag is not present in the initial HTML.

The original PR to see how this works is here: https://github.com/vercel/next.js/pull/25346
Docs: https://nextjs.org/docs/basic-features/font-optimization

**Comment by alveshelio** [comment]
I don't know why but it fixed itself
