### ISSUE TITLE
Rewrites resulting in attempt to serve wrong static files

### ISSUE THREAD

**Issue by DannyAgent** [vercel/next.js#37333]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.24
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

The application has a dynamic route set up for pages/[slug] & for pages/news/[slug].

next.config.js is set up with the following rewrite:

```js
fallback: [
        {
          source: '/:path*',
          destination: `/news/:path*`,
        },
      ],
```
This is set up to catch old wordpress blog posts that use DOMAIN/path to rewrite to DOMAIN/news/path.

The application needs a dynamic route for pages so that the client can set up new pages in the CMS (Wordpress headless).

When visiting DOMAIN/slug-of-news-post the rewrite seems to initially be successful but then an error is thrown a few seconds later -> Failed to load resource: the server responded with a status of 404 (Not Found) -> DOMAIN/_next/data/development/slug-of-news-post.

If I manually add the failed url (DOMAIN/_next/data/development/slug-of-news-post) to the browser but add in the /news path, the data is displayed in the browser (DOMAIN/_next/data/news/development/slug-of-news-post). -> Not sure if this will help shed light on the issue.
     

### Expected Behavior

When visiting DOMAIN/slug-of-news-post the application should rewrite to DOMAIN/news/slug-of-news-post as there are no pages with the [slug] "slug-of-news-post". 

### To Reproduce

**next.config.js**

```js
async rewrites() {
    return { 
      fallback: [
        {
          source: '/:path*',
          destination: `/news/:path*`,
        },
      ],
    }
```

**Folder structure**

pages
--[slug].js
--/news/[slug].js

**pages/[slug]** 

```js
export async function getStaticProps(context){
   
    const res = await fetch(`${process.env.route}/wp-json/wp/v2/pages?slug=${context.params.slug}&_embed`);
    const data = await res.json();

    return {
        props: {
            page: data[0],
        },
        revalidate:10
    }
}

export async function getStaticPaths() {
    
    const res = await fetch(`${process.env.route}/wp-json/wp/v2/pages?per_page=100`);

    const data = await res.json();

    const paths = data.map((page)=>({
        params: { slug: page.slug }
    }))
    return { paths, fallback: false }
}
```

**pages/news/[slug]**

```js
export async function getStaticProps(context){
    const res = await fetch(`${process.env.route}/wp-json/wp/v2/posts?slug=${context.params.slug}`);
    const data = await res.json();

    return {
        props: {
            post: data[0],
        },
        revalidate: 10
    }
}

export async function getStaticPaths() {
    const res = await fetch(`${process.env.route}/wp-json/wp/v2/posts?per_page=20`);

    const data = await res.json();

    const paths = data.map((post)=>({
        params: { slug: post.slug }
    }))
    return { paths, fallback: false }
}
```

**Comment by woniesong92** [comment]
I'm also affected by this. Are there any workarounds?

**Comment by JanKaifer** [comment]
You need to make sure that your redirect won't affect `_next/*` routes.
Well, you can redirect them, but you need to be aware of that.
