### ISSUE TITLE
next/router useRouter invalid typedef

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#37374]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.2.0
      npm: 8.9.0
      Yarn: 1.22.15
      pnpm: 7.1.7
    Relevant packages:
      next: 12.1.7-canary.27
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

The `useRouter`'s type definition is "kind-of" invalid, at least on the client.

After logging the `useRouter()` I saw that on client there is a `components` property that I thought I'd use for automating a Navbar that would include all the pages automatically. I don't know if this is a bug, but it would be cool if `components` was properly typedeffed.

Here is an example:
```ts
import type { NextPage } from "next";
import { useRouter } from "next/router";

const HomePage: NextPage = () => {
  const router = useRouter();
  console.log(router);
  const components = router.components;
  /**
   * `components` exist on client only,
   * on server it's are undefined.
   * however the `components`-prop of router is never defined
   **/

  return (
    <div>
      <h3>Pages</h3>
      {components &&
        Object.keys(components).map((page) => <p key={page}>{page}</p>)}
    </div>
  );
};

export default HomePage;
```

### Expected Behavior

The `components` property to be typedefined as
```ts
type NextRouter = {
  ...;
  components: ComponentType | undefined;
```

or another option to get all the available routes for my application.

### To Reproduce

Example on CodeSandbox: https://codesandbox.io/s/next-router-qc3b71

or spin up a new empty next application and paste the example code in `pages/index.tsx`

**Comment by balazsorban44** [comment]
`components` is an undocumented/private API and thus should not be relied on. 

Intended properties for use are documented here:
https://nextjs.org/docs/api-reference/next/router#router-object

And exposed in the source code here:

https://github.com/vercel/next.js/blob/ebc3408f4751a9b02b403ea523c93d87b241bf07/packages/next/shared/lib/router/router.ts#L352-L365
