### ISSUE TITLE
API routes res.status(500) not work when I use IP address visit

### ISSUE THREAD

**Issue by Capricair** [vercel/next.js#37386]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 14.17.6
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 12.1.6
  react: 17.0.2
  react-dom: 17.0.2
```

### Describe the Bug

```
// api routes
export default function (req, res) {
  res.status(500).json({ message: 'hello' })
}
```
visit http://localhost:3000, api routes status is 500
visit http://192.168.xxx.xxx:3000, api routes status is all 304, res.status(500) not work

### Expected Behavior

visit http://192.168.xxx.xxx api routes is specified by res.status

### To Reproduce

1. create a next app
2. create an api routes /api/hello, 
```
export default function (req, res) {
  res.status(500).json({ message: 'hello' })
}
```
3. request /api/hello on home page
4. open home page use IP address http://192.168.xxx.xxx, api status is all 304

**Comment by balazsorban44** [comment]
I cannot reproduce this. It is likely a network/browser configuration issue. Make sure you don't have a proxy/browser extension that can interfere.

![image](https://user-images.githubusercontent.com/18369201/171615939-8895cef0-4f4c-4ec8-86a0-066127505cb6.png)
