### ISSUE TITLE
Type GetStaticProps needs some tinker

### ISSUE THREAD

**Issue by PabloLION** [vercel/next.js#37392]
## Summary
`next.GetStaticProps` stop extends return type to `Record<string,any>`

## Detailed

Say I have a `getStaticProps` like this.

```ts
const getStaticProps = async () => {
  const typedProps = {
    str: "stringType",
    num: 123,
  }
  return {
    props: typedProps,
  };
};
```

Typescript knows the type of `typedProps`
```ts
const typedProps: {
    str: string;
    num: number;
}
```
And the `InferGetStaticPropsType<typeof getStaticProps>` in the same page works correctly.

However, after adding the type `GetStaticProps` to the `getStaticProps`. the `const SomePage: NextPage<InferGetStaticPropsType<typeof getStaticProps>>` starts to accept `{[key: string]: any}` as its argument and all type information of the props is lost (converted to `any`).

### Describe the solution you'd like

I want `GetStaticProps<P,Q,D>` stop to have default value of `P = { [key: string]: any }` from https://github.com/vercel/next.js/blob/ccd3df2f812c98874273de7b237baa9c2ad8f309/packages/next/types/index.d.ts#L118-L124 

But to me this is limited by TS engine, so I don't know how to fix it. (otherwise I'd make a PR)

### Describe alternatives you've considered

Not use GetStaticProps. Deprecate this type

## Related issues

#32434 ,  #11328

**Comment by GabenGar** [comment]
Or create an interface for props used by the page and pass it to the generic argument.

**Comment by GabenGar** [comment]
@MonstraG 
> That works, but then he needs to type page and type props separately

What do you mean? You declare page props once and then use `InferStaticProps<typeof getStaticProps>` on the page props. With added benefit of page props getting declared upfront and `getStaticProps()` having to conform to them.

@PabloLION 

>but for me TS is a QoL option
And generics make TS a QoL in the first place. In general if an interface has a generic argument it means accuracy of type hints depend on it. In case of `P` generic of `GetStaticProps` it means the `props` returned has to be an object and passing anything else is a compile error in typescript. Hard to please both camps at the same time in this case.

**Comment by PabloLION** [comment]
> With added benefit of page props getting declared upfront and `getStaticProps()` having to conform to them.

I specified this too, one design change can lead to multiple code change. This is not necessarily good.

> And generics make TS a QoL in the first place.

And we want to keep that, right?

> In case of `P` generic of `GetStaticProps` it means the `props` returned has to be an object and passing anything else is a compile error in typescript.
That is not what I saw in the code if you mean it from `GetStaticPropsResult`



> Hard to please both camps at the same time in this case.

I didn't understand this.


---
Also I haven't seen what the point you are trying to make here, could you tell me? Thanks.

**Comment by GabenGar** [comment]
> I specified this too, one design change can lead to multiple code change. This is not necessarily good.

That's way too vague and isn't related to the subject at hand.

>That is not what I saw in the code if you mean it from `GetStaticPropsResult`

That's quite literally what it does, accepts a generic for its `props` key and `GetStaticProps` narrows it down to a subtype of `Record`.

> Also I haven't seen what the point you are trying to make here, could you tell me? Thanks.

You didn't understand anything but also not seeing the point? How surprising.

**Comment by PabloLION** [comment]
> That's way too vague and isn't related to the subject at hand.

That's the exact point of this issue. If I want to add one attr to the `prop`, I would have to change both the interface and the returned value. I think we should not block TS to deduce. (also a readability improve)

> That's quite literally what it does, accepts a generic for its `props` key and `GetStaticProps` narrows it down to a subtype of `Record`.

You are correct, just not related to the question.


> You didn't understand anything but also not seeing the point? How surprising.

So what's your point here? That this Feature Request is not needed?

**Comment by MonstraG** [comment]
> That works, but then he needs to type page and type props separately

What I ment is that you do

```tsx
type Props = {
    data: Thingie
}

Page: NextPage<Props> = (props) => 

...

export const getServerSideProps: GetServerSideProps = async (ctx): Promise<GetServerSidePropsResult<Props>> => {
```

So you declare Props once, but you use it twice.

**Comment by GabenGar** [comment]
@PabloLION 
> That's the exact point of this issue. If I want to add one attr to the `prop`, I would have to change both the interface and the returned value. I think we should not block TS to deduce. (also a readability improve)

Having an interface for the page props declared upfront is way more readable than looking at the return value of the server function (which can have several return values an be pretty verbose in general) and trying to guess its type.

> You are correct, just not related to the question.

It is related directly to the question. `GetStaticProps` accepts a generic which defines its return type. And that generic has to be a subtype of `Record`, no other way around it. Making the generic completely devoid of requirements just means TS will not error out when you write something like this:
```typescript
return {
  props: []
}
```

> So what's your point here? That this Feature Request is not needed?

That you completely miss the point of generics. There might be a way to infer type from the return value, but writing the code in such way is a bad practice and will make you hate typescript, since it's pretty limited on type inference.

@MonstraG 
That's not how you type pages.
The proper way only passes the page props once:
```
interface IPageProps {}
interface IPageParams extends ParsedUrlQuery{}

export default Page({}: InferGetStaticPropsType<typeof getStaticProps>){}
```
export const getStaticProps: GetStaticProps<IPageProps, IPageParams> = async (context) => { ... }

**Comment by PabloLION** [comment]
@GabenGar please close the question then, if you think it's not needed.

**Comment by PabloLION** [comment]
> Having an interface for the page props declared upfront is way more readable than looking at the return value of the server function (which can have several return values an be pretty verbose in general) and trying to guess its type.

Agreed. In most cases yes.

> And that generic has to be a subtype of `Record`, no other way around it.

This is what I meant with TS capability.  But I believe it's improvable (although I don't know how).


> That you completely miss the point of generics. There might be a way to infer type from the return value, but writing the code in such way is a bad practice and will make you hate typescript, since it's pretty limited on type inference.

No I haven't miss that. I just don't want it to remove the original functionality of TS to infer type.  
Let's say we work with your point of generics, the best practice would be to remove the default value of `P` and force user to input a type, instead of passing a `Record<string,any>` and quietly blocking that functionality of TS to infer type.

**Comment by GabenGar** [comment]
Yeah that would be a better approach but also will not make people happy when their builds suddenly start to fail and the only solution to this is declaring props interfaces on potentially 100s of page components.

**Comment by PabloLION** [comment]
Tried to PR this on the lines mentioned at top

```ts
export type GetStaticProps<
  P = R,
  Q extends ParsedUrlQuery = ParsedUrlQuery,
  D extends PreviewData = PreviewData
> = (
  context: GetStaticPropsContext<Q, D>
) => Promise<GetStaticPropsResult<infer R>> | GetStaticPropsResult<infer R>
```

I give up because it seems not possible because I remembered React.FC needs a manual assignment of the types. Since they(react team) can't fix. I don't think varcel team can. This is limited by TS engine for me.

**Comment by GabenGar** [comment]
Infers have to be conditional so you have to provide a fallback value in case it can't be inferred:
https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types
