### ISSUE TITLE
Middleware should not be used with `target:'serverless'`

### ISSUE THREAD

**Issue by feugy** [vercel/next.js#37433]
It is not possible to build (or develop) a Middleware on a Next.js application targeting `serverless`.

### Steps to reproduce

A simple application:
```
pages/
  |__ index.js   // content: export default function Home() { return <h1>Hi there!</h1> }
middleware.js    // content: import { NextResponse } from 'next/server'; export default function middleware() { return NextResponse.next() }
next.config.js   // content: module.exports = { target: 'serverless' }
```

Run with `next dev` and you'll get this error when browsing to http://localhost:3000
```
error - Error: Cannot find module '<folder>/.next/serverless/middleware-manifest.json'
```

You'll also get a similar error when running `next build`

### 🚜 Proposal

When starting in development mode or building such an application, we should issue an error such as:
> `Global configuration as serverless is not support when middleware is present in the project. Learn more: https://nextjs.org/docs/messages/middleware-on-serverless`

Provide more details in the error page, with possible mitigations.

**Comment by feugy** [comment]
@timneutkens's plan is to deprecate this target in Next@13
I'm keeping this issue here only it happens, but we should not take any action yet.

**Comment by timneutkens** [comment]
It should be trivial to add an error for this right? Imo we should have this error in place before middleware becomes stable. The `target` option is already deprecated and in Next.js 13 it'll be removed altogether.
