### ISSUE TITLE
Docs: displaying-data-with-props is missing content

### ISSUE THREAD

**Issue by abitrolly** [vercel/next.js#37444]
### What is the improvement or update you wish to see?

At https://nextjs.org/learn/foundations/from-javascript-to-react/displaying-data-with-props it looks like there is a missing text here.

![image](https://user-images.githubusercontent.com/8781107/171999615-252a5a25-dff1-4343-a4b8-904b4648a419.png)

### Is there any context that might help us understand?

--

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/from-javascript-to-react/displaying-data-with-props

**Comment by balazsorban44** [comment]
The `For example:` refers to the upcoming ways of using a JS expression, so there is no content missing, but I agree that it might feel that way. I passed a note to the team to try to make that section a bit more clear. :+1:

Thanks!

**Comment by abitrolly** [comment]
@balazsorban44 well, indeed. :D Perhaps indenting it, or adding a header to examples list will help.

I couldn't find the source for the learn foundations tutorial. Is it on GitHub?

**Comment by balazsorban44** [comment]
The source is currently not public. We will make sure it is updated, thanks again for reporting!
