### ISSUE TITLE
_document.js does not load Script tags

### ISSUE THREAD

**Issue by francinelucca** [vercel/next.js#37491]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 102.0.5005.61 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

yarn dev

### Describe the Bug

next/Script tags do not render when in _document.js.

I am able to make changes (add divs, meta, html scripts) in the _document.js file and see them reflected in the dom, but not Script tags (tried inline scripts, urls, relative paths and also different strategies)

### Expected Behavior

DOM contains script tag in the same way that it does other tags

### To Reproduce

in _document.js: 

```jsx
import { Head, Html, Main, NextScript } from 'next/document'
import Script from 'next/script'

export default function Document() {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
        <Script id="inline" type="text/javascript">
          {
            'alert("hey")'
          }
        </Script>
          <div>Heyy</div>
      </body>
    </Html>
  )
}
```

When running application, verify div tag containing "hey" is present in the DOM but script tag is not.

**Comment by drewradcliff** [comment]
I was able to get this to work on the canary version (12.1.7-canary.31) using the `beforeInteractive` strategy
```
import { Main, NextScript, Head, Html } from 'next/document'
import Script from 'next/script'
export default function Document() {
  return (
    <Html>
      <Head>
        <Script
          id="alert"
          strategy='beforeInteractive'
        >
          {`alert('test')`}
        </Script>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
```

**Comment by balazsorban44** [comment]
Indeed, this should be fixed in `canary`, please give it a try!
