### ISSUE TITLE
NextJs Head Not Loading Script when Imported from Component

### ISSUE THREAD

**Issue by KevinDanikowski** [vercel/next.js#37495]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

NOTE: I was having trouble downloading next@canary so I couldn't verify. If that means you need to close this I understand.
Next version `12.0.8`

### Describe the Bug

Attempting to load script from a component:

```jsx
import Head from 'next/head'
    
// NOTE: next/script doens't solve the issue either
const MyScript = () => <script type='text/javascript' src='https://myscript.com' async />
    
const NotLoadingScript = () => (
      <Head>
        <MyScript />
      </Head>
)
    
const LoadsScript = () => (
      <Head>
        <script type='text/javascript' src='https://myscript.com' async />
      </Head>
)
```

I'm only loading one, not both. The `NotLoadingScript` doesn't load the script, i.e. it isn't found on the HTML page.

### Expected Behavior

I should see the script in the HTML

### To Reproduce

Use the sample components described in the bug.

**Comment by EddyVinck** [comment]
For anyone finding this page like I did, this is what worked for me:

```tsx
export const RecaptchaScript = () => (
  <Script
    async
    defer
    strategy="afterInteractive"
    src={`https://www.google.com/recaptcha/api.js?render=${recaptchaSiteKey}`}
  />
);
```

I use this in my form components.
