### ISSUE TITLE
Error: Cannot find module 'next/dist/server/denormalize-page-path.js'

### ISSUE THREAD

**Issue by adminha** [vercel/next.js#37507]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 28 05:34:34 EST 2022
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.31
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome Version 102.0.5005.63 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

next build, then uploading content of .next folder into public_html folder in cPanel

### Describe the Bug

I've created a nodejs app in cPanel, then created a server.js file using the documentation from custom server in nextjs docs as application startup file.
Then, I've uploaded the contents of .next folder (after npm run build) into the root folder of domain in cPanel.
I've also installed all the required packages via npm install command. 
But when I try to view the website, an error comes up:
```
Error: Cannot find module 'next/dist/server/denormalize-page-path.js'
Require stack:
- /home/user/domain.com/.next/server/pages/_app.js
- /home/user/nodevenv/domain.com/14/lib/node_modules/next/dist/server/require.js
- /home/user/nodevenv/domain.com/14/lib/node_modules/next/dist/server/next-server.js
- /home/user/nodevenv/domain.com/14/lib/node_modules/next/dist/server/next.js
- /home/user/domain.com/server.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.mod._resolveFilename (/home/user/nodevenv/domain.com/14/lib/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.562 (/home/user/domain.com/.next/server/pages/_app.js:114:18)
    at __webpack_require__ (/home/user/domain.com/.next/server/webpack-runtime.js:25:42)
    at Object.1003 (/home/user/domain.com/.next/server/chunks/664.js:839:28)
    at __webpack_require__ (/home/user/domain.com/.next/server/webpack-runtime.js:25:42)
    at Object.1551 (/home/user/domain.com/.next/server/chunks/664.js:15:15) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/domain.com/.next/server/pages/_app.js',
    '/home/user/nodevenv/domain.com/14/lib/node_modules/next/dist/server/require.js',
    '/home/user/nodevenv/domain.com/14/lib/node_modules/next/dist/server/next-server.js',
    '/home/user/nodevenv/domain.com/14/lib/node_modules/next/dist/server/next.js',
    '/home/user/domain.com/server.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
```

I searched and saw a similar issue here:
[https://github.com/vercel/next.js/issues/37467](url)

But didn't find any way to solve the issue.
How can I fix this?

### Expected Behavior

To run smoothly without any errors.

### To Reproduce

Package.json file :
```
{
  ...
  "main": "",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "postbuild": "next-sitemap --config project-sitemap.js",
    "start": "next start",
    "types": "tsc --noEmit",
    "export": "next export"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^6.1.1",
    "@next-auth/typeorm-legacy-adapter": "^1.0.3",
    "@reduxjs/toolkit": "^1.8.1",
    "@tinymce/tinymce-react": "^4.1.0",
    "axios": "^0.26.1",
    "bootstrap": "^5.1.3",
    "google-auth-library": "^8.0.2",
    "next": "^12.0.11-canary.4",
    "next-auth": "^4.3.4",
    "next-sitemap": "^2.5.28",
    "nodemailer": "^6.6.3",
    "react": "^17.0.2",
    "react-bootstrap": "^2.3.0",
    "react-dom": "^17.0.2",
    "react-google-one-tap-login": "^0.1.1",
    "react-redux": "^8.0.1",
    "react-select": "^5.3.2",
    "redux": "^4.2.0",
    "sass": "^1.51.0"
  },
  "devDependencies": {
    "@types/bootstrap": "^5.1.10",
    "@types/node": "^17.0.14",
    "@types/react": "^17.0.44",
    "@types/react-dom": "^18.0.0",
    "typescript": "^4.5.5"
  },
  "prettier": {
    "semi": false
  }
}

```

**Comment by balazsorban44** [comment]
Hi, could you try https://nextjs.org/docs/advanced-features/output-file-tracing?

Using a custom server setup is discouraged.

Could you please also share your code so we can investigate?

**Comment by adminha** [comment]
> Hi, could you try https://nextjs.org/docs/advanced-features/output-file-tracing?
> 
> Using a custom server setup might not be what you need.
> 
> Could you please also share your code so we can investigate?

It runs now using the method you mentioned. But SCSS files located in the public folder don't load although I've copied the public folder inside standalone folder.

P.S: Should I keep using this version (standalone) & not build the regular version? What's the risks or performance issues of using standalone version instead of regular build version?

**Comment by balazsorban44** [comment]
SCSS files should not be inside `public`, as those files need preprocessing (compiled to CSS) which is supported by Next.js [out-of-the-box](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support). That folder is intended for static files https://nextjs.org/docs/basic-features/static-file-serving

On standalone mode:

> This feature helps reduce the size of deployments drastically. Previously, when deploying with Docker you would need to have all files from your package's dependencies installed to run next start. Starting with Next.js 12, you can leverage Output File Tracing in the .next/ directory to only include the necessary files.

Read more: https://nextjs.org/docs/advanced-features/output-file-tracing

I'm closing this as this does not seem to be a Next.js issue. If you have further questions regarding your own project, you can find a lot of help in [Discussions](https://github.com/vercel/next.js/discussions) or [Discord](https://nextjs.org/discord)
