### ISSUE TITLE
Fallback rewrites with catch all route causes a JSON error 

### ISSUE THREAD

**Issue by johnnyomair** [vercel/next.js#37510]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.10.0
      npm: 7.24.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.31
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

I'm using rewrites with the `fallback` option to rewrite after dynamic routes have been checked. This works fine during server rendering, but when the app rehydrates, a fetch is made to `/produkte.json`, causing the 404 page to be rendered and sent to the client (as the route doesn't exist), which cannot be interpreted as JSON, therefore causing the app to crash.

Error in the console

<img width="803" alt="Screen Shot 2022-06-07 at 13 53 27" src="https://user-images.githubusercontent.com/48853629/172387515-c1c21d9d-9a28-4508-a6a7-201a49b06566.png">

The 404 page's HTML returned for the produkte.json request

<img width="803" alt="image" src="https://user-images.githubusercontent.com/48853629/172387679-16719851-0257-402a-86b8-466daf8f7ba4.png">

### Expected Behavior

The application "follows" rewrites when fetching the JSON content (or doesn't fetch it at all) and doesn't crash.

### To Reproduce

1. Clone the repo: https://github.com/johnnyomair/next-rewrites-fallback-bug-demo
2. Install dependencies `npm install`
3. Start application `npm run dev`
4. Click on "Produkte" link on homepage

**Comment by felixmeziere** [comment]
We have the same problem here! :/

**Comment by avaltat** [comment]
Any progress on this would be great, I have the same issue. Thank you.

**Comment by felixmeziere** [comment]
@johnnyomair did you find a workaround by any chance? This is super blocking for us 😬😬😬

**Comment by johnnyomair** [comment]
@felixmeziere no, not really. However, were able to implement our requirements by using rewrites in the default mode (without `fallback`) and narrowing down the rewrite source and destination using RegEx.

**Comment by johnnyomair** [comment]
@wyattjoh I just did. The JSON error is gone. However, the application now renders the wrong page, the home page ("/", specified in [[...path]].js). It seems like this only happens on the client. The browser first loads the correct page, then changes to the home page (see attached video).

https://user-images.githubusercontent.com/48853629/176502097-86a60842-e898-41af-8850-4ea0e3286cf5.mov

**Comment by wyattjoh** [comment]
Seems that the behaviour that you want in this case is actually to use the following for the rewrite configuration:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  rewrites: () => ({
    afterFiles: [{ source: "/produkte", destination: "/products" }],
  }),
};

module.exports = nextConfig;
```

Note that we're using `afterFiles` here instead of `fallback`. The client side routing performs the switch here because the client doesn't currently have the list of paths specified in your catch-all in its manifest in order to determine that it should instead "fallback" rather than switch to the catch all route (see https://github.com/vercel/next.js/issues/37686#issuecomment-1157942080) which is what causes the flash.

**Comment by johnnyomair** [comment]
Sorry for the late response.

The reason we're not using `afterFiles` is because our catch-all may specify paths that somewhat collide with the rewrites. For instance, it may return a path `/produkte/neue-produkte`. This page should not be rewritten to `/products/neue-produkte`. Only paths that do not match a path specified in the catch-all should be rewritten.

I can see why this might not work due to the client not having a list of all paths specified in the catch-all. As we have found a workaround (see https://github.com/vercel/next.js/issues/37510#issuecomment-1165493949), I'm fine with that. Thanks for the effort! 🙂
