### ISSUE TITLE
Support `"module": "nodenext"` in `tsconfig.json`

### ISSUE THREAD

**Issue by michaelhays** [vercel/next.js#37525]
### Describe the feature you'd like to request

With [TypeScript 4.7 providing ECMAScript Module Support](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#ecmascript-module-support-in-node-js), we can now set this in our `tsconfig.json` file for the [`module`](https://www.typescriptlang.org/tsconfig#module) option:

```json
{
  "compilerOptions": {
    "module": "nodenext",
  }
}
```

However, Next.js [rejects this value](https://github.com/vercel/next.js/blob/dc36199b2234c6586ebe05ec94078a895c707e29/packages/next/lib/typescript/writeConfigurationDefaults.ts#L43-L54), and overwrites it with `"esnext"`.

#36189 did add support for `"moduleResolution": "nodenext"`, but not `"module": "nodenext"`.

### Describe the solution you'd like

Add `"nodenext"` and `"node16"` to [`module.parsedValues`](https://github.com/vercel/next.js/blob/dc36199b2234c6586ebe05ec94078a895c707e29/packages/next/lib/typescript/writeConfigurationDefaults.ts#L46-L51):

```ts
parsedValues: [
  ts.ModuleKind.ES2020,
  ts.ModuleKind.ESNext,
  ts.ModuleKind.NodeNext,
  ts.ModuleKind.Node16,
  ts.ModuleKind.CommonJS,
  ts.ModuleKind.AMD,
]
```

I figure there may be other changes necessary to make this work, and that the [TypeScript version](https://github.com/vercel/next.js/blob/dc36199b2234c6586ebe05ec94078a895c707e29/package.json#L193) should be bumped to 4.7+ with it.

### Describe alternatives you've considered

I edited [`writeConfigurationDefaults.js`](https://github.com/vercel/next.js/blob/canary/packages/next/lib/typescript/writeConfigurationDefaults.ts) directly in my `node_modules` for a local project, and it seemed to work.

Relevant aside: I think the discussion at #32237 is a bug that needs to be resolved before this can work as expected. I still haven't been able to import files with the `.js` extension.

**Comment by jakubmazanec** [comment]
Also, `"moduleResolution": "node16"` isn't supported, only `"node", "node12" or "nodenext"`.

**Comment by terenceodonoghue** [comment]
Are there plans to support it? I'm trying to use a local ES module in my monorepo but it won't resolve without "node16". Even an option to stop Next.js forcibly overwriting the tsconfig.json would be helpful.

**Comment by ctjlewis** [comment]
@terenceodonoghue Can you post a Replit repro?

**Comment by kachkaev** [comment]
@ctjlewis you can try playing with https://github.com/kachkaev/njt/pull/186 where I try to switch a small Next.js 13 project to pure ESM. Need to use these two workarounds and it’d be great to see them implemented in Next: https://github.com/vercel/next.js/discussions/41189#discussioncomment-4026895

I’m also unable to use `"module": "NodeNext"` as mentioned in this issue.

**Comment by crutch12** [comment]
Is there some progress on this?
