### ISSUE TITLE
'Invoked an Edge Function "_middleware"' being spammed in vercel log

### ISSUE THREAD

**Issue by auto-holder** [vercel/next.js#37529]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Vercel
<img width="1423" alt="Screen Shot 2022-06-07 at 7 22 32 PM" src="https://user-images.githubusercontent.com/82126104/172518330-d7c89f83-fa81-4367-b005-2ef462bf2677.png">

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Very intrusive log statement: "Invoked an Edge Function "_middleware"" is flooding my logs ever since i started using _middleware. I can't disable it anywhere.

### Expected Behavior

Not have so much useless logs. Unless explicitly stated.

### To Reproduce

Start using _middleware

**Comment by balazsorban44** [comment]
Thanks, I passed this feedback to our team. Since this is not a Next.js bug, I'll close the issue, but feel free to add any comments if you like.
