### ISSUE TITLE
`scroll: false` does not work on hash change

### ISSUE THREAD

**Issue by alxhotel** [vercel/next.js#37552]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.31
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 101.0.4951.64

### Describe the Bug

When executing a router change, NextJS autoscrolls to the hash even if `scroll: false` was passed.

### Expected Behavior

NextJS should not scroll to the hash if the user requested that.

### To Reproduce

1. Run `router.push('#hash', undefined, { scroll: false })` where `#hash` is a valid href in your page
2. The window scrolls to that anchor (it is not supposed to do that)

**Comment by timfuhrmann** [comment]
`scroll` only controls scrolling to the top of the page after navigation. AFAIK there isn't really a solution to opt out of the browser's scroll anchoring behavior in general yet. There is `overflow-anchor: none`, but the browser support isn't perfect and all present JS solutions seem pretty hacky to me.

**Comment by alxhotel** [comment]
Yeah, I understand that. The use case I was referring to is when I want to change hash.

In that case, `scroll` is still used. In this line https://github.com/vercel/next.js/blob/23295ef34b6105291c3468697a4b21241394827f/packages/next/shared/lib/router/router.ts#L1031

So if `scroll` is `false` then the scroll to hash should never happen. If not, then what is the point of that line?
