### ISSUE TITLE
i18n support is not compatible with next export

### ISSUE THREAD

**Issue by liuliuliucome** [vercel/next.js#37575]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

i18n support is not compatible with next export 
This error problem occurs with any i18n plugin, how do I fix it? Must I use vercel to deploy SSG pages?

### How are you deploying your application? (if relevant)

next export

### Describe the Bug

i18n support is not compatible with next export 

### Expected Behavior

i18n support is not compatible with next export 

### To Reproduce

npx next export

**Comment by balazsorban44** [comment]
As per docs:

> Note that Internationalized Routing does not integrate with [`next export`](https://nextjs.org/docs/advanced-features/static-html-export) as `next export` does not leverage the Next.js routing layer. Hybrid Next.js applications that do not use `next export` are fully supported.


https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation

Also mentioned under:

https://nextjs.org/docs/advanced-features/static-html-export#unsupported-features

**Comment by vltansky** [comment]
@balazsorban44 is there any roadmap? Will it be supported in the future?

**Comment by balazsorban44** [comment]
As `next export` does not leverage Routing (which would be needed here), I don't think this is possible.
