### ISSUE TITLE
Missing incrementalCacheHandlerPath config value in base-server.ts file

### ISSUE THREAD

**Issue by AditioPangestu** [vercel/next.js#37594]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 14.17.0
      npm: 6.14.13
      Yarn: 1.22.17
      pnpm: 6.28.0
    Relevant packages:
      next: 12.1.7-canary.33
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

At this lines, no `incrementalCacheHandlerPath` config value. https://github.com/vercel/next.js/blob/15354e9b42201df8c2102f2ba2f3cfcca1e561c0/packages/next/server/base-server.ts#L353-L372

### Expected Behavior

IncrementalCache construction has `incrementalCacheHandlerPath` config value.

### To Reproduce

Assign `incrementalCacheHandlerPath` config value to `next.config.js`.

**Comment by balazsorban44** [comment]
Hi, that option is part of a feature that's still under development. You can follow our `canary` releases for updates, as our experimental features are usually not documented since they can change at any time without notice.
