### ISSUE TITLE
[edge] Error: Module not found: Can't resolve 'dns'

### ISSUE THREAD

**Issue by rtritto** [vercel/next.js#37600]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.33
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

I enable [edge runtime](https://nextjs.org/docs/api-reference/edge-runtime) using React 18 and MongoDB.
`mongodb` depends on the `dns` module, which is only available in Node.js runtime.

### Expected Behavior

No error

### To Reproduce

1. `yarn create next-app --example with-mongodb with-mongodb-app`
2. `cd with-mongodb-app`
3. delete/comment code in _/lib/mongodb.js_ file:
```diff
- if (!process.env.MONGODB_URI) {
-   throw new Error('Please add your Mongo URI to .env.local')
- }
```
4. create _next.config.js_ file:
```js
module.exports = {
  experimental: {
    runtime: 'edge'
  }
}
```
5. `yarn up mongodb next@canary react react-dom`
6. `yarn dev`

**Comment by rtritto** [comment]
Related #36237

**Comment by balazsorban44** [comment]
This is expected as per our documentation: https://nextjs.org/docs/api-reference/edge-runtime#unsupported-apis

You cannot rely on Node.js-specific APIs when using the Edge Runtime.
