### ISSUE TITLE
Middleware.js in src folder build into an unexpected "src" folder

### ISSUE THREAD

**Issue by Chastrlove** [vercel/next.js#37604]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.6.0
      npm: 7.19.1
      Yarn: 1.22.17
      pnpm: 6.32.12

    Relevant packages:
      next: 12.1.7-canary.33
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 100.0.4878.0

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

Since the https://github.com/vercel/next.js/pull/37428, i put the middleware.js in the "src" folder. After build, the middleware.js created in the "server/src" folder , not the "server" folder. Anyway, it just looks a little ugly.

![image](https://user-images.githubusercontent.com/17813559/172981525-d50e3dc2-7258-4c46-bd48-fc03759b69d0.png)

### Expected Behavior

middleware.js created in server folder.

### To Reproduce

https://codesandbox.io/s/goofy-https-zutr5n

**Comment by TszHong0411** [comment]
[https://stackblitz.com/edit/nextjs-nudqjg](https://stackblitz.com/edit/nextjs-nudqjg)

**Comment by balazsorban44** [comment]
I cannot think of a bug being raised because of this, and such "Anyway, it just looks a little ugly." is only a stylistic opinion, so I'm going to close this.

If you do discover a bug caused because of this, however, please let us know!
