### ISSUE TITLE
next/image: Empty `alt` texts are rendered as boolean attributes

### ISSUE THREAD

**Issue by gvjacob** [vercel/next.js#37616]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101
    Binaries:
      Node: 14.18.0
      npm: 8.10.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.33
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 102.0.5005.61 (Official Build) (arm64)

### Describe the Bug

The `next/image` component renders `alt` as a boolean attribute if an empty string is provided. Empty `alt` texts should be respected for accessibility reasons, mainly [decorative images](https://www.w3.org/WAI/tutorials/images/decorative/).

```jsx
<Image src="..." alt="" />

// Output should not render boolean `alt`
<img src="..." alt />
```

### Expected Behavior

Passing an empty string to the `Image` component should render an empty string for the resulting `img`'s `alt` text.

```jsx
<Image src="..." alt="" />

// Correct output
<img src="..." alt="" />
```

### To Reproduce

1. Render an `Image` component with empty string `alt` text.
```jsx
<Image src="..." alt="" />
```

2. Inspect the DOM on your browser. The resulting image's `alt` text is rendered as a boolean attribute.
![Screen Shot 2022-06-10 at 9 39 51 AM](https://user-images.githubusercontent.com/23367882/173078208-e7278d88-8409-487c-a338-8e75e647e2f3.png)

**Comment by SukkaW** [comment]
Per HTML5 spec:

> The attribute value can remain [unquoted](https://html.spec.whatwg.org/#unquoted) if it doesn't contain [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace) or any of " ' ` = < or >. Otherwise, it has to be quoted using either single or double quotes. The value, along with the "=" character, can be omitted altogether if the value is the empty string.
> ```html
> 
> <input name=address disabled>
> <input name=address disabled="">
> ```

https://html.spec.whatwg.org/#a-quick-introduction-to-html

**Comment by gvjacob** [comment]
@SukkaW Thanks for the note! First time I heard that they're equivalent.

**Comment by balazsorban44** [comment]
There are no boolean attributes (or other JS types than string) in HTML. boolean, object, JS expressions etc. are a concept in JSX: https://reactjs.org/docs/jsx-in-depth.html#props-in-jsx and are called props. :+1:
