### ISSUE TITLE
onRouteChange() event listener

### ISSUE THREAD

**Issue by pascall-de-creator** [vercel/next.js#37639]
### Describe the feature you'd like to request

It will be nice if there was a simple event listener or a hook to determine the URL of a SPA, it will help make changes to the website by the current route and thus make stuff easier

### Describe the solution you'd like

maybe a simple function like 
```js
onRouteChange(() => {
        // callback
    }
)
``` 
event listener can be introduced into Next.js

### Describe alternatives you've considered

maybe a simple hook
```js
const { currentRoute, previousRoute } = useRoute()

const Home = () => {
    return (
        <>
            { currentRoute === "vercel/next.js/issues/" ? ... : ... }
        </>

    )
}
``` 
event listener can be introduced into Next.js

**Comment by zslabs** [comment]
Does https://nextjs.org/docs/api-reference/next/router not already do all that? Hooks and event listeners within the page.
