### ISSUE TITLE
Docs: The way to create a Typescript based Next app via pnpm seems to be off

### ISSUE THREAD

**Issue by ItsRyanWu** [vercel/next.js#37645]
### What is the improvement or update you wish to see?

The documentation says we can create a Typescript project by running this command:
`pnpm create next-app -- --typescript`
The initialization process was ok but somehow it created a directory named '--typescript' on my macOS with all project code inside it.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/17338101/173237543-6c60c2d3-eacf-4e33-9614-3566187f4874.png">

### Is there any context that might help us understand?

The issue only happens when using pnpm to create a Next app.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/getting-started

**Comment by ijjk** [comment]
Hi, this documentation was updated in https://github.com/vercel/next.js/pull/37254 and will be released along with our next stable release. 

The correct command for the latest version of `pnpm` is `pnpm create next-app --typescript`
