### ISSUE TITLE
TypeError: Cannot read properties of undefined (read of undefined (reading 'config')  

### ISSUE THREAD

**Issue by tacolegs2004** [vercel/next.js#37678]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 17.3.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.38
      react: 18.1.0
      react-dom: 18.1.0

### Describe the Bug

I get an error whenever I try to visit the local host link that prevents me from seeing the expected boilerplate.

### Expected Behavior

I expecr to see the boilerplate nextjs site.

### To Reproduce

does this help?

./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./styles/globals.css
TypeError: Cannot read properties of undefined (reading 'config')

**Comment by balazsorban44** [comment]
This sounds similar to https://github.com/vercel/next.js/issues/32443 but as of then, there was no reproducible error on my side. I would be happy to investigate your case if you can provide a reproduction.

**Comment by tacolegs2004** [comment]
I'm not entirely sure how to provide a reproduction. I follow the instructions provided by the nextjs website to create a boilerplate next project.

**Comment by balazsorban44** [comment]
Does this happen on every project, even if you create one using our [CLI](https://nextjs.org/docs/api-reference/create-next-app)?

**Comment by maxwaiyaki** [comment]
Is there a walk around for this??

**Comment by FelipeBattistotti** [comment]
I have the same error!

**Comment by daverik** [comment]
I had this error but fixed it by removing a postcss.config and a tailwind.config that I had accidentally added to a parent directory.

**Comment by mickbut-ler** [comment]
Does anyone have a fix for this bug?

**Comment by vlukashov** [comment]
Accidentally I've stumbled on this (or a very similar) issue, and I have a reliable way to reproduce it.

In my case the NextJS project is in a subfolder of a larger repo. If the parent folder happens to have a `postcss.config.js` file with the `tailwindcss` and `autoprefixer` plugins, then the NextJS project fails to run or build.

### Steps to reproduce
 - create a parent folder: `mkdir monorepo && cd monorepo`
 - install the PostCSS, TailwindCSS and Autoprefixer: `npm init -y && npm install -D tailwindcss postcss autoprefixer`
 - create a `postcss.config.js` in the `monorepo` folder
    ```js
    module.exports = {
      plugins: {
        tailwindcss: {},
        autoprefixer: {},
      },
    }
    ```
 - create a basic NextJS app in a subfolder: `npx create-next-app@latest --typescript next-app`
   (the nesting level does not seem to matter: the issue appears equally when the NextJS app is directly in `monorepo/next-app` or is nested in `monorepo/packages/next-app`)
 - run the NextJS app: `cd next-app && npm run dev`
 - see the error
    ```
    error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[4].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[4].use[2]!./styles/Home.module.css
    TypeError: Cannot read properties of undefined (reading 'config')
    ```
 - remove the postcss config file and see that the error is gone

@balazsorban44, I hope a reproduction case would help you to investigate the issue and eventually get it fixed. Thanks for you support!

**Comment by inemiro** [comment]
creating tailwind.config.js file helped me in the similar monorepo case.
content can be simple as that:
```
module.exports = {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by suspence21** [comment]
The tailwind and postcss files in a parent folder were causing the issue for me. Resolved! Thank heavens!

**Comment by blastZ** [comment]
Maybe helpful, In monorepo(I used nx), you should add specific tailwind config path for postcss config

postcss.config.js
```
module.exports = {
  plugins: {
    tailwindcss: {
      config: 'apps/[app-name]/[your-path]/tailwind.config.js',
    },
    autoprefixer: {},
  },
};

```

**Comment by NikoCyber** [comment]
I started getting the same issue from yesterday when I tried to build a new nextJS project🤔 `npx create-next-app@latest` I haven't faced it before. I also tried to install NextJS with `app/` and with `pages/` folders, but getting the same error. I haven't installed anything else, only NextJS. What can be the issue? 

Params: MacOS Ventura, Next.js v13.1.4

```
error - ./src/app/page.module.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[3]!./src/app/page.module.css
TypeError: Cannot read properties of undefined (reading 'config')
    at runMicrotasks (<anonymous>)
Import trace for requested module:
./src/app/page.module.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[7].use[3]!./src/app/page.module.css
./src/app/page.module.css
```

**Comment by Jayant818** [comment]
Got the Same Error bro

**Comment by Jayant818** [comment]
Got Same Error

**Comment by Nicklaus-s** [comment]
I have the same error when trying to deploy a project with [Nextra](https://nextra.site/docs/docs-theme/start). However I believe it may be a problem with how I configured my directories.
![image](https://user-images.githubusercontent.com/100449899/215362174-677d7232-ebd0-4e74-a00f-516f8a8be189.png)

```
$ npm run dev

> syncsession@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - automatically enabled Fast Refresh for 3 custom loaders
info  - automatically enabled Fast Refresh for 3 custom loaders
error - TypeError: Cannot read properties of undefined (reading 'Compilation')
    at C:\Users\Nicklaus\node_modules\nextra\dist\index.js:344:41
    at Hook.eval (eval at create (C:\Users\Nicklaus\OneDrive\Documents\GitHub\syncSession\docs\syncsession\node_modules\next\dist\compiled\webpack\bundle5.js:13:28771), <anonymous>:45:1)
    at Hook.CALL_ASYNC_DELEGATE (C:\Users\Nicklaus\OneDrive\Documents\GitHub\syncSession\docs\syncsession\node_modules\next\dist\compiled\webpack\bundle5.js:13:25925)
    at C:\Users\Nicklaus\OneDrive\Documents\GitHub\syncSession\docs\syncsession\node_modules\next\dist\compiled\webpack\bundle5.js:28:147735
    at eval (eval at create (C:\Users\Nicklaus\OneDrive\Documents\GitHub\syncSession\docs\syncsession\node_modules\next\dist\compiled\webpack\bundle5.js:13:28771), <anonymous>:11:1)
    at NextraPlugin.<anonymous> (C:\Users\Nicklaus\node_modules\nextra\dist\index.js:325:11)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Nicklaus\node_modules\nextra\dist\index.js:41:24)
TypeError: Cannot read properties of undefined (reading 'Compilation')
    at C:\Users\Nicklaus\node_modules\nextra\dist\index.js:344:41
    at Hook.eval (eval at create (C:\Users\Nicklaus\OneDrive\Documents\GitHub\syncSession\docs\syncsession\node_modules\next\dist\compiled\webpack\bundle5.js:13:28771), <anonymous>:45:1)
    at Hook.CALL_ASYNC_DELEGATE (C:\Users\Nicklaus\OneDrive\Documents\GitHub\syncSession\docs\syncsession\node_modules\next\dist\compiled\webpack\bundle5.js:13:25925)
    at C:\Users\Nicklaus\OneDrive\Documents\GitHub\syncSession\docs\syncsession\node_modules\next\dist\compiled\webpack\bundle5.js:28:147735
    at eval (eval at create (C:\Users\Nicklaus\OneDrive\Documents\GitHub\syncSession\docs\syncsession\node_modules\next\dist\compiled\webpack\bundle5.js:13:28771), <anonymous>:11:1)
    at NextraPlugin.<anonymous> (C:\Users\Nicklaus\node_modules\nextra\dist\index.js:325:11)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Nicklaus\node_modules\nextra\dist\index.js:41:24)
```

**Comment by Steve-Reid** [comment]
> Accidentally I've stumbled on this (or a very similar) issue, and I have a reliable way to reproduce it.
> 
> In my case the NextJS project is in a subfolder of a larger repo. If the parent folder happens to have a `postcss.config.js` file with the `tailwindcss` and `autoprefixer` plugins, then the NextJS project fails to run or build.
> 
> ### Steps to reproduce
> * create a parent folder: `mkdir monorepo && cd monorepo`
> * install the PostCSS, TailwindCSS and Autoprefixer: `npm init -y && npm install -D tailwindcss postcss autoprefixer`
> * create a `postcss.config.js` in the `monorepo` folder
>   ```js
>   module.exports = {
>     plugins: {
>       tailwindcss: {},
>       autoprefixer: {},
>     },
>   }
>   ```
> * create a basic NextJS app in a subfolder: `npx create-next-app@latest --typescript next-app`
>   (the nesting level does not seem to matter: the issue appears equally when the NextJS app is directly in `monorepo/next-app` or is nested in `monorepo/packages/next-app`)
> * run the NextJS app: `cd next-app && npm run dev`
> * see the error
>   ```
>   error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[4].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[4].use[2]!./styles/Home.module.css
>   TypeError: Cannot read properties of undefined (reading 'config')
>   ```
> * remove the postcss config file and see that the error is gone
> 
> @balazsorban44, I hope a reproduction case would help you to investigate the issue and eventually get it fixed. Thanks for you support!

@vlukashov I can't than enough for posting this. I've been going nuts trying to figure out what happened. I don't think I would have ever spotted this if wasn't for your solution.
Cheers

**Comment by douglasrcjames** [comment]
For me, the issue was directly tied to if I chose to NOT install tailwindcss. My default project ran just fine when I chose to install tailwind. I tried on the @canary version as well! Current @latest version is `13.3.2`. I guess I will just learn tailwindcss until this is fixed lol! 

**Setup steps:**
```
√ What is your project named? ... test-next-error
√ Would you like to use TypeScript with this project? ...Yes
√ Would you like to use ESLint with this project? ... Yes
√ Would you like to use Tailwind CSS with this project? ... No
√ Would you like to use `src/` directory with this project? ... Yes
√ Would you like to use experimental `app/` directory with this project? ...  Yes
√ What import alias would you like configured? ... @/*
```

Then I just ran `npm run dev` after navigating to new project directory, and the error below pops up:

**Error:**
`./src/app/page.module.css
TypeError: Cannot read properties of undefined (reading 'config') at runMicrotasks (<anonymous>)`

**Comment by KarloZKvasin** [comment]
Hi, I had the same problem when I had cypress in a separate folder. I had to create the talwind configuration separately in the cypress folder as well. Hope this helps you.

```
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js):
TypeError: Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (xxx/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:85:63)
    at xxx/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:97:92
    at xxx/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
```

in folder cypress I added tailwind.config.js with 
`export * from './../tailwind.config';`

**Comment by iSuslov** [comment]
Having the same issue with firebase hosting emulator.

To reproduce simply:

```
npx create-next-app@latest
```

and try to run it in `firebase emulators`

**Comment by francosopo** [comment]
I had the same issue, but it was kind of fixed by doing in postcss config file 

`module.exports = {
  plugins: {
    tailwindcss: {
      config:'./tailwind.config.js',
    },
    autoprefixer: {},
  },
}`

but now the error is that it does not find 'blocklist'
