### ISSUE TITLE
NextJS can't resolve tsconfig.json path to module in external workspace package

### ISSUE THREAD

**Issue by Ziothh** [vercel/next.js#37679]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

- OS: macOS Monterey
- NodeJS v18.2.0

## My problem
I get a "module not found" error in my nextjs project when running dev.

I get this error when I use a path alias defined in a tsconfig inside a package. Relative imports do work. It's like the loader doesn't see my compilerOptions.path setting inside the package-scoped tsconfig.

I'm using pnpm workspaces. But I'm pretty sure the same error would occur when using yarn.

Thanks in advance.

## The error
```
error - ../database/config/models.ts:1:0
Module not found: Can't resolve '@models/business/Business.model'
> 1 | import Business from "@models/business/Business.model"
  2 | import Image from "@models/Image.model"
  3 | import Site from "@models/Site.model"
  4 | import User from "@models/user/User.model"
```

You can see the full console log in this screenshot.
![Screenshot 2022-06-13 at 16 05 16](https://user-images.githubusercontent.com/81878355/173520083-d96f598a-ae66-4a92-9945-51377ea3ac1f.png)

### Expected Behavior

I should be able to use a  tsconfig path alias inside a pnpm workspace package, defined by a tsconfig inside that package.

## What I'm doing
 I'm importing a typeorm DataSource instance in `web/pages/api/graphql.ts` from a workspace package "@workspace/backend". 
This itself imports a list of BaseEntities  from a module inside that package.
The "@models" part of that import statement is a path alias, defined inside `database/tsconfig.json`.

## My project structure
 - tsconfig.base.json
 - backend/
 - database/
 - shared/
 - web/ (this is the nextjs app)
   - next.config.js
   - tsconfig.json
   - pages/ 
   - ...
 - pnpm-workspace.yaml

Every package has a `tsconfig.base.json` that extends `tsconfig.base.json`

### `tsconfig.base.json`
```json
{
    "compilerOptions": {
        "target": "ES2017",
        "module": "ESNext",
        "lib": ["esnext", "ESNext.AsyncIterable"],
        "allowJs": false,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": false,
        "esModuleInterop": true,
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true,
        "experimentalDecorators": true,
        "strictPropertyInitialization": false,
        "emitDecoratorMetadata": true,
        "baseUrl": ".",
        "paths": {}
    },
    "include": [""],
    "exclude": ["node_modules", "_*"]
}
```

### `web/tsconfig.json`
```json
{
    "extends": "../tsconfig.base.json",
    "compilerOptions": {
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": false,
        "forceConsistentCasingInFileNames": true,
        "noEmit": false,
        "incremental": true,
        "esModuleInterop": true,
        "module": "esnext",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "baseUrl": "."
    },
    "include": ["next-env.d.ts", "./**/*.ts", "./**/*.tsx"],
    "exclude": ["node_modules"]
}
```

## `database/tsconfig.json`
```json
{
    "extends": "../tsconfig.base.json",
    "compilerOptions": {
        "baseUrl": ".",
        "rootDir": ".",
        "paths": {
            "@resolvers/*": ["./resolvers/*"],
            "@models/*": ["./models/*"],
            "@config/*": ["./config/*"]
        }
    },
    "include": ["./**/*.ts"]
}
```

## `next.config.js`
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
    experimental: {
        externalDir: true,
    },
    reactStrictMode: true,
    webpack: (config, { isServer }) => {
        config.resolve.fallback = { fs: false }

        // Fixes api routes crashing
        config.experiments = {
            topLevelAwait: true,
            // it makes a WebAssembly modules async modules
            syncWebAssembly: true,
            asyncWebAssembly: true,
            layers: true,
        }

        // generate wasm module in ".next/server" for ssr & ssg
        if (isServer) {
            config.output.webassemblyModuleFilename = "./../static/wasm/[modulehash].wasm"
        } else {
            config.output.webassemblyModuleFilename = "static/wasm/[modulehash].wasm"
        }

        return {
            ...config,
        }
    },
}

module.exports = nextConfig
```

**Comment by balazsorban44** [comment]
Since you are using the `externalDir: true` `experimental` flag, could you please provide this feedback here instead: https://github.com/vercel/next.js/discussions/26420

I recommend attaching a full reproduction (or if the repo is public, just link to it, otherwise you can also invite me to the private repo) so it is easy to investigate.

(Maybe https://github.com/vercel/next.js/discussions/26420#discussioncomment-2797562 helps, but hard to tell without a full reproduction)

**Comment by Ziothh** [comment]
Thanks for the quick response. I've granted you access to my repo if you'd want to take a look. 

I've also look at the thread you linked and found another user (1mzino: https://github.com/vercel/next.js/discussions/26420#discussioncomment-2272551) with the same issue that isn't resolved. 

Maybe this way of structuring nextjs projects wasn't considered when adding the experimental feature. 

I'm moving this question to https://github.com/vercel/next.js/discussions/26420

**Comment by balazsorban44** [comment]
:+1: I recommend creating a public _minimal_ reproduction so the next person can investigate much easier.
