### ISSUE TITLE
Docs: The example code is wrong.

### ISSUE THREAD

**Issue by D50000** [vercel/next.js#37703]
### What is the improvement or update you wish to see?

(In the middle of this document)
This feature is called [Fast Refresh](https://nextjs.org/docs/basic-features/fast-refresh). It gives you instantaneous feedback on any edits you make and comes pre-configured with Next.js.
To recap, your code went from this..
```jsx
~~~ skip ~~~
<ul>
    {name.map((name) => (
        <li key={name}>{name}</li>
    ))}
</ul>
```

### Is there any context that might help us understand?

```jsx
~~~ skip ~~~
<ul>
    {name.map((name) => (
        <li key={name}>{name}</li>
    ))}
</ul>
```

should be **_names_**

```jsx
~~~ skip ~~~
<ul>
    {names.map((name) => (
        <li key={name}>{name}</li>
    ))}
</ul>
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs

**Comment by balazsorban44** [comment]
Thanks, updated! Should be reflected :soon:
