### ISSUE TITLE
API being called twice

### ISSUE THREAD

**Issue by YasminCastro** [vercel/next.js#37715]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome 102.0.5005.63

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I'm building an application with Next Js, and I'm creating API's for it. But there's a bug that I can't solve. When I make a call to the API within the project itself or using webhooks the api is called twice. I tried to create a new project, change the version of next but it keeps making the API request twice. Here I took a print of the request being called twice ![Snipaste_2022-06-14_17-33-00](https://user-images.githubusercontent.com/62770317/173820388-2b743abb-a578-469c-b241-228b44ace48c.png)

I don't know if this is just happening with my projects, or if it's a bug outside of next...

### Expected Behavior

API running only one time when is call.

### To Reproduce

Make a simple endpoint and call it within the application itself or via webhooks.

**Comment by SukkaW** [comment]
https://github.com/vercel/next.js/issues/35822
https://github.com/vercel/next.js/issues/36920
#37274

**Comment by YasminCastro** [comment]
Thank you so much, I managed to fix it with your guys help :D
