### ISSUE TITLE
When starting the server with a syntax error in the code, and the error overlay will not disappear after fixing it.

### ISSUE THREAD

**Issue by await-ovo** [vercel/next.js#37710]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
   Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64
    Binaries:
      Node: 14.19.0
      npm: 6.14.16
      Yarn: 1.22.17
      pnpm: 7.0.0
    Relevant packages:
      next: 12.1.7-canary.39
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Version 100.0.4896.127 (Official Build) (x86_64)

### Describe the Bug

If there is a syntax problem in the code itself when running `next dev`, you can see the error overlay by accessing `localhost:3000`, but after fixing the error, the error overlay does not disappear

### Expected Behavior

After fixing the syntax error, the error overlay will disappear automatically.

### To Reproduce

1. `npx create-next-app@latest`

2. `cd my-app`

3. modify `pages/index.js` as below:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/41503212/173801789-d96dc9de-44b1-49d5-b973-b07854f2ce59.png">

4.  `yarn dev`

5. open `localhost:3000` in browser with new tab, then you can see the error overlay:

![image](https://user-images.githubusercontent.com/41503212/173802402-83609db5-d3c1-419e-ad14-1ce7c10f9cc9.png)

6.  fix the jsx syntax error in `pages/index.js` and save it: 

<img width="686" alt="image" src="https://user-images.githubusercontent.com/41503212/173802727-b2894367-f40c-41a4-aba3-46dc74f23fb3.png">

The new error overlay that appears in the browser after a successful compilation:

![image](https://user-images.githubusercontent.com/41503212/173802697-5544bf26-f6b8-4eed-ae3b-fe1035b6bda0.png)

After some research, I found that the first time I opened `localhost:3000`, `window.__NEXT_DATA__.page` is `/error`, after the syntax error was fixed , there is an error in the browser fetchting `xxxxxx.webpack.hot-update.json`:
![image](https://user-images.githubusercontent.com/41503212/173805053-b6462c09-52e9-420a-901e-b27a31298d2e.png)

I saw i[n this file](https://github.com/vercel/next.js/blob/canary/packages/next/client/dev/error-overlay/hot-dev-client.js#L362) that the whole page will be reloaded only when there is a `FULL_REFRESH_STORAGE_KEY ` in the sessionStorage:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/41503212/173806124-671d4076-ea75-4de3-bc1a-0d3e48634e40.png">

I have a little doubt here, when fallback to the error page, is it better to reload  when handle updates?

Thank you for reading this issue ~

**Comment by hanneslund** [comment]
Thanks for the issue! This works in latest canary, got fixed by #37425.
