### ISSUE TITLE
Middleware rewrite doesn't take `searchParams` when target page is a non-SSR page.

### ISSUE THREAD

**Issue by meikidd** [vercel/next.js#37720]
### Verify canary release

- [x] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

The `searchParams` is not taken when target page of `NextResponse.rewrite()` is a non-SSR page.

In this `_middleware.ts`, we want to rewrite all requests to "/login?hello=world", but in fact we can only go to "/login" without the query parameter "?hello=world".

```typescript
// _middleware.ts
import { NextRequest, NextResponse } from 'next/server';


export async function middleware(request: NextRequest) {
  console.log('_middleware:', request.nextUrl.href);

  const newUrl = request.nextUrl.clone();
  newUrl.searchParams.set('hello','world');
  newUrl.pathname = '/login';
  const response = NextResponse.rewrite(newUrl);
  
  console.log('_middleware:', newUrl.toString());
  return response;
}
```

I wanted to try it on canary version, but I found the middleware api is changed in canary and I couldn't find the corresponding document for that.

### Expected Behavior

Expect we can get "?hello=world" at rewrite target "/login" page.

### To Reproduce

I created this minimal reproducible project, please have a check:
https://github.com/meikidd/nextjs-middleware-rewrite

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.1.7-canary.40` of Next.js, please update and give it a try!

**Comment by meikidd** [comment]
Hi @ijjk , the canary version `v12.1.7-canary.40` seems not backward compatible, it prints "error - Nested Middleware is not allowed, found pages/_middleware" to me. And my middleware is not work in canary version.

**Comment by ijjk** [comment]
The breaking changes are expected as the feature is in beta so doesn't follow semver, there is a upgrade guide that is WIP progress here https://github.com/vercel/next.js/pull/37382

**Comment by meikidd** [comment]
@ijjk 
Thank you for the information. I followed the guide and upgraded to canary version, but the issue remains to me. 

I have updated my demo repo: https://github.com/meikidd/nextjs-middleware-rewrite

**Comment by ijjk** [comment]
Ah I see, on initial visit to `/detail` the query doesn't contain the `searchParam` as expected for an SSG page. We could ensure the middleware is triggered here for the SSG query hydration

**Comment by meikidd** [comment]
Thank you for the fix @ijjk May. I know when this new version will be released?

**Comment by ijjk** [comment]
The above fix is now available in `v12.1.7-canary.41` of Next.js, please update and give it a try!

**Comment by meikidd** [comment]
Hi, thank you for the quick response. I upgraded to `v12.1.7-canary.41` and have following findings, not sure if it is expected.

- When rewrite target is a SSR page("/detail" page in my demo), the rewrite target page can get query params on both nodejs side and browser hydration.
  - middleware.ts
    <img width="1022" alt="image" src="https://user-images.githubusercontent.com/376338/174485237-d80a7659-bf4a-43ed-8b6b-271d45ac9419.png">
  - nodejs
    <img width="789" alt="image" src="https://user-images.githubusercontent.com/376338/174484801-a4f7009a-281e-4976-a26c-eca04055a944.png">
  - browser hydration
    <img width="914" alt="image" src="https://user-images.githubusercontent.com/376338/174484840-63267331-31e8-4882-b565-8802f3d497cf.png">

- When rewrite target is a non-SSR page("/login" page in my demo), the rewrite target page can only get query params on browser hydration but not nodejs side.
  - middleware.ts
    <img width="1024" alt="image" src="https://user-images.githubusercontent.com/376338/174485218-c3702ce6-c320-41e6-a1d0-3bfab9d8bb28.png">
  - nodejs
    <img width="753" alt="image" src="https://user-images.githubusercontent.com/376338/174484986-88b1b755-7fba-427f-b5a8-67e7cd33bf5a.png">
  - browser hydration
    <img width="911" alt="image" src="https://user-images.githubusercontent.com/376338/174484965-cf0a1ffd-47cb-475e-9f1e-a8a689fffc1b.png">


And I noticed the `export config.matcher` doesn't work in this version, I had to change it to `if(request.nextUrl.pathname === '/detail' && request.nextUrl.pathname === '/login')` to acheive equivalent logic.

**Comment by ijjk** [comment]
> When rewrite target is a non-SSR page("/login" page in my demo), the rewrite target page can only get query params on browser hydration but not nodejs side

Yeah this is expected and is similar with other query parameters for static pages, since the page is prerendered the query information isn't available until hydration on the client since these values are provided at runtime not build time. 

The matcher now considers the locale when matching and we are investigating auto matching the locale by default and allowing manual matching with a `locale: false` field similar to rewrites/redirects.

**Comment by meikidd** [comment]
Get it. Thanks for clarifying!
