### ISSUE TITLE
Using externalDir and importing a component that imports CSS from node_modules reports a global CSS import error

### ISSUE THREAD

**Issue by PaulPopat** [vercel/next.js#37749]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.0.0
      npm: 8.6.0
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

Netlify but N/A

### Describe the Bug

When the externalDir setting is set to true and importing a component that imports a CSS file from node_modules, the global CSS error is thrown on compile.

### Expected Behavior

This above should compile without issue.

### To Reproduce

Set externalDir to true in the `next.config.js`. The next project should be in a subfolder with the package.json and node_modules at the top level. I reproduced this primarily when using NX but that is not required for reproduction.

```JSX
import React from "react";
import AComponent from "../../../out-of-project/a-component";

const Page = () => <AComponent>Some stuff</AComponent>;

export default Page;
```

Then in the `a-component.jsx` file.
```JSX
import React from "react";
import "a-node-module/styles.css";

export const AComponent = ({ children }) => <div className="class-from-styles">{children}</div>;
```

The above will throw a compiler error and, as far as I am aware, it is within the NextJS spec.

I have reproduced this with `slick-carousel`, amongst other libraries.

**Comment by balazsorban44** [comment]
Thanks for the feedback, please report it here: https://github.com/vercel/next.js/discussions/26420
