### ISSUE TITLE
Showing 405: Method Not Allowed page after redirecting from another url to the nextjs app. 

### ISSUE THREAD

**Issue by SebghatYusuf** [vercel/next.js#37785]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101
    Binaries:
      Node: 14.17.0
      npm: 6.14.13
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Brave (Version 1.39.120 Chromium: 102.0.5005.99 , Safari

### How are you deploying your application? (if relevant)

Google Cloud Run via docker

### Describe the Bug

My Nextjs app is dockerized and deployed on Google Cloud Run, when I'm redirecting from another website (domain) to the Nextjs app it's showing an empty page with this content 405: Method Not Allowed, (I 

### Expected Behavior

It should start doing the API calls in the next js app and let the user interact with the app, 

### Link to reproduction

 https://stackblitz.com/no-link-available

### To Reproduce

1- Deploy an app on Google Cloud Run and add the custom domain. 
2- Redirect from another website (domain) to the Next.js app (any page - better to have an API call inside useEffect hook). 
3- will see a page showing 405: Method Not Allowed

![Screen Shot 2022-06-17 at 12 17 01 PM](https://user-images.githubusercontent.com/48417629/174251518-d487ffaf-9b99-49bc-870f-2369abd8bbac.png)

**Comment by MonstraG** [comment]
Just a heads up, your stackblitz links is broken

**Comment by SebghatYusuf** [comment]
@MonstraG, thank you as this issue wasn't reproducible with stackblitz I have no stackblitz link.
