### ISSUE TITLE
next/link with query params are not doing client side navigation

### ISSUE THREAD

**Issue by santsys** [vercel/next.js#37789]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.40
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 102.0.5005.115

### How are you deploying your application? (if relevant)

next export

### Describe the Bug

It seems that next/links that use a dynamic route property and query do not use client side rendering and do full page reloads.

Take the example below, the top two links work as expected, client-side loading, but the bottom link seems to do a standard browser navigation (doing a full reload of the application).

```tsx
<div>
      <Link href={{ pathname: '/p2' }} passHref>
        <a>Go to Page 2</a>
      </Link>
 </div>
<div>
      <Link href={{ pathname: '/en-us/category/news' }} passHref>
        <a>Go to News (works)</a>
      </Link>
 </div>
<div>
      <Link
        href={{ pathname: '/[lang]/category/news', query: { lang: 'en-us' } }}
        passHref
      >
        <a>Go to News (doesn't work)</a>
      </Link>
 </div>
```

This used to work, and I'm not sure when it stopped working. Was there a change in requirements for using next/link?

### Expected Behavior

All link examples should use client side loading + pre-fetching.

### Link to reproduction

N/A

### To Reproduce

N/A

**Comment by timfuhrmann** [comment]
Still working as expected for me, something else might interfere with routing.

**Comment by santsys** [comment]
@timfuhrmann - Any ideas where to look? Using a standard next/link, all variations work except variations with query parameters.

Happy to do more testing, but I'm not sure what else to test at this point. Any pointers / ideas?

**Comment by timfuhrmann** [comment]
Are you using static site generation on any of your pages?

**Comment by santsys** [comment]
I think this may have something to do with the brackets in the url being encoded into `%5B`/`%5D` values and then not matching the file routes... e.g. `/_next/static/chunks/pages/%5Blang%5D/category/news.js` doesn't match `/_next/static/chunks/pages/en-us/category/news.js`

Wonder if there is an encoding mismatch somewhere?

**Comment by JanKaifer** [comment]
This behavior is here just for backward compatibility.
See the docs for more details https://nextjs.org/docs/api-reference/next/link#if-the-route-has-dynamic-segments

You should just use `href={{ pathname: '/en-us/category/news' }}` instead of `href={{ pathname: '/[lang]/category/news', query: { lang: 'en-us' } }}`.
