### ISSUE TITLE
Typescript setup error in next-env.d.ts

### ISSUE THREAD

**Issue by HummingMind** [vercel/next.js#37781]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.3.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.40
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I am using the current version of JetBrains WebStorm IDE.
It is giving me a warning for the next-env.d.ts file that is automatically generated by Next.

The warning is:
Cannot resolve file 'global'.

It is triggered by this line:
`/// <reference types="next/image-types/global" />`

If I change it to `/// <reference types="next/image-types/global.d.ts" />` then the warning goes away, but obviously Next just regenerates the file and erases the modification.

It seems like it is looking for global.ts file instead of global.d.ts.
Is this a tooling issue specific to WebStorm? I know I can suppress the warning, but I just want to make sure this is not some kind of bug with Next. If it is not, I'll open a bug report with JetBrains.

Please let me know if you need more information.

Thank you.

### Expected Behavior

No warnings. It bothers my OCD.

### Link to reproduction

None

### To Reproduce

1. Create a new Next.js application either manually or using create-next app with typescript support.
2.  Open the next-env.d.ts file in WebStorm
3.  Observe the warning in the Problems section of the IDE

Screenshot for illustration:
![image](https://user-images.githubusercontent.com/87399963/174201486-77ac81af-e3a3-4683-896c-f5b2a5f1eba5.png)

**Comment by balazsorban44** [comment]
Based on https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types- it sounds like a WebStorm bug, as the `.d.ts` extension is not required.
