### ISSUE TITLE
Middleware does not take rewrites into account. Can't A/B Test main index page. 

### ISSUE THREAD

**Issue by keslert** [vercel/next.js#37797]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Operating System:
  Platform: linux
  Arch: x64
  Version: #40-Ubuntu SMP Mon Mar 7 08:03:10 UTC 2022
Binaries:
  Node: 14.17.0
  npm: 6.14.13
  Yarn: 1.22.17
  pnpm: N/A
Relevant packages:
  next: 12.1.1-canary.17
  react: 17.0.2
  react-dom: 17.0.2

### Describe the Bug

@[javivelasco](https://github.com/javivelasco) Followup to this [issue](https://github.com/vercel/next.js/issues/35566) which was just closed. I don't think the proposed solution makes sense as you trigger different middleware based on if you are accessing the page via the rewritten path or the destination path. Also, the suggested solution doesn't allow you to run middleware just for the root page without running it for every single request. 

When using rewrites, the middleware dedicated to the destination page is not executed: the middleware dedicated to the source page is executed instead (if it exists). I want to a/b test my homepage using middleware to choose which page to show. I don't want to add middleware to /pages/_middleware because I don't want to trigger an edge function for every single page request.

```
// next.config.js
async rewrites() {
    return {
      beforeFiles: [
        { source: "/", destination: "/homepage" },
      ],
  }
}
```
```
// pages/homepage/_middleware.ts
import { NextRequest, NextResponse } from "next/server";

const COOKIE_NAME = "homepage-version";
const VERSIONS = ["og", "a"] as const;
const getVersion = () =>
  VERSIONS[Math.floor(Math.random() * VERSIONS.length)];

export function middleware(req: NextRequest) {
  const version = req.cookies[COOKIE_NAME] || getVersion();
  const res = NextResponse.rewrite(`/homepage/${version}`);

  if (!req.cookies[COOKIE_NAME]) {
    res.cookie(COOKIE_NAME, version)
  }

  return res;
}
```

### Expected Behavior

The middleware for the destination folder should be triggered when doing a rewrite.

### Link to reproduction

https://github.com/cvolant/next-middleware-rewrite-issue

### To Reproduce

Reproduction steps are described in the readme file.

**Comment by cramforce** [comment]
@ijjk Any chance your recent /index related change fixed this? Or was that only for `_next/data`?

**Comment by ijjk** [comment]
This doesn't seem related to the `/index` issue as this is still using nested middleware. 

Please see our upgrade guide for middleware here https://nextjs.org/docs/messages/middleware-upgrade-guide nested middleware is no longer supported in the latest canary of Next.js `v12.1.7-canary.48`. Also note the order priority for `next.config.js` rewrites/redirects and middleware is:

1. `next.config.js` redirects
2. middleware (redirects, rewrites, etc)
3. `next.config.js` beforeFiles rewrites
4. `next.config.js` afterFiles rewrites
5. `next.config.js` fallback rewrites

> I don't want to add middleware to /pages/_middleware because I don't want to trigger an edge function for every single page request

There is now an `export const config = { matcher: ['/', '/blog'] }` option in middleware to allow only matching specific paths. 

I'm gonna close this as these issues appear to be resolved in the latest canary.
