### ISSUE TITLE
Upgrade with-sentry example to NextJs v12 and sentry-javascript V7 

### ISSUE THREAD

**Issue by smeubank** [vercel/next.js#37870]
### Describe the feature you'd like to request

Want to be able to create NextJs v12.x application, instrumented with sentry-javascript v7.x on Vercel. With all the new features of both respectively. Including new features and fixes, listed in both release notes respectively.

### Describe the solution you'd like

The with-sentry example application should be default latest version of NextJs v12, and latest version of the sentry-javascript SDK

### Describe alternatives you've considered

The example code could just continue to have the outdated framework and SDK versions, but then users would have extra steps to use the current versions.

Today the deploy is also simply broken due to outdated dependencies

> 09:59:20.019] Cloning github.com/smeubank/nextjs-sentry-example (Branch: smeubank-v7, Commit: 7a6096a)
> [09:59:20.559] Cloning completed: 539.03ms
> [09:59:21.475] Looking up build cache...
> [09:59:21.942] Build Cache not found
> [09:59:22.236] Running "vercel build"
> [09:59:22.880] Vercel CLI 25.1.1-canary.3 build (beta) — https://vercel.com/feedback
> [09:59:23.231] Installing dependencies...
> [09:59:23.708] yarn install v1.22.17
> [09:59:23.741] info No lockfile found.
> [09:59:23.750] [1/4] Resolving packages...
> [09:59:25.415] warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> [09:59:25.438] warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> [09:59:26.230] [2/4] Fetching packages...
> [09:59:34.939] [3/4] Linking dependencies...
> [09:59:34.943] warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
> [09:59:37.216] [4/4] Building fresh packages...
> [09:59:37.985] success Saved lockfile.
> [09:59:37.991] Done in 14.29s.
> [09:59:38.030] Detected Next.js version: 11.1.4
> [09:59:38.031] Running "yarn run build"
> [09:59:38.391] yarn run v1.22.17
> [09:59:38.429] $ next build
> [09:59:39.565] info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
> [09:59:39.832] Attention: Next.js now collects completely anonymous telemetry regarding usage.
> [09:59:39.832] This information is used to shape Next.js' roadmap and prioritize features.
> [09:59:39.833] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> [09:59:39.833] https://nextjs.org/telemetry
> [09:59:39.833] 
> [09:59:39.889] info  - Checking validity of types...
> [09:59:40.052] warn  - No ESLint configuration detected. Run next lint to begin setup
> [09:59:40.055] info  - Creating an optimized production build...
> [09:59:52.805] Failed to compile.
> [09:59:52.805] 
> [09:59:52.805] Sentry CLI Plugin: Command failed: /vercel/path0/node_modules/@sentry/cli/sentry-cli releases new 7a6096ad8027f8c66dcb77c6eec2c744c537548c
> [09:59:52.806] error: An organization slug is required (provide with --org)
> [09:59:52.806] 
> [09:59:52.806] Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
> [09:59:52.806] Please attach the full debug log to all bug reports.
> [09:59:52.806] 
> [09:59:52.806] 
> [09:59:52.807] > Build error occurred
> [09:59:52.807] Error: > Build failed because of webpack errors
> [09:59:52.807]     at /vercel/path0/node_modules/next/dist/build/index.js:397:19
> [09:59:52.807]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
> [09:59:52.808]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:77:25)
> [09:59:52.837] error Command failed with exit code 1.
> [09:59:52.837] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> [09:59:52.866] Error! Command "yarn run build" exited with 1
> [09:59:52.978] Error: Command "vercel build" exited with 1

**Comment by Wyatt-SG** [comment]
I'll take this issue if no one else has already started on it.

**Comment by balazsorban44** [comment]
Feel free, thanks!

**Comment by mehdialiakbar31** [comment]
> ### Describe the feature you'd like to request
> Want to be able to create NextJs v12.x application, instrumented with sentry-javascript v7.x on Vercel. With all the new features of both respectively. Including new features and fixes, listed in both release notes respectively.
> 
> ### Describe the solution you'd like
> The with-sentry example application should be default latest version of NextJs v12, and latest version of the sentry-javascript SDK
> 
> ### Describe alternatives you've considered
> The example code could just continue to have the outdated framework and SDK versions, but then users would have extra steps to use the current versions.
> 
> Today the deploy is also simply broken due to outdated dependencies
> 
> > 09:59:20.019] Cloning github.com/smeubank/nextjs-sentry-example (Branch: smeubank-v7, Commit: 7a6096a)
> > [09:59:20.559] Cloning completed: 539.03ms
> > [09:59:21.475] Looking up build cache...
> > [09:59:21.942] Build Cache not found
> > [09:59:22.236] Running "vercel build"
> > [09:59:22.880] Vercel CLI 25.1.1-canary.3 build (beta) — https://vercel.com/feedback
> > [09:59:23.231] Installing dependencies...
> > [09:59:23.708] yarn install v1.22.17
> > [09:59:23.741] info No lockfile found.
> > [09:59:23.750] [1/4] Resolving packages...
> > [09:59:25.415] warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> > [09:59:25.438] warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> > [09:59:26.230] [2/4] Fetching packages...
> > [09:59:34.939] [3/4] Linking dependencies...
> > [09:59:34.943] warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
> > [09:59:37.216] [4/4] Building fresh packages...
> > [09:59:37.985] success Saved lockfile.
> > [09:59:37.991] Done in 14.29s.
> > [09:59:38.030] Detected Next.js version: 11.1.4
> > [09:59:38.031] Running "yarn run build"
> > [09:59:38.391] yarn run v1.22.17
> > [09:59:38.429] $ next build
> > [09:59:39.565] info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
> > [09:59:39.832] Attention: Next.js now collects completely anonymous telemetry regarding usage.
> > [09:59:39.832] This information is used to shape Next.js' roadmap and prioritize features.
> > [09:59:39.833] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> > [09:59:39.833] https://nextjs.org/telemetry
> > [09:59:39.833]
> > [09:59:39.889] info  - Checking validity of types...
> > [09:59:40.052] warn  - No ESLint configuration detected. Run next lint to begin setup
> > [09:59:40.055] info  - Creating an optimized production build...
> > [09:59:52.805] Failed to compile.
> > [09:59:52.805]
> > [09:59:52.805] Sentry CLI Plugin: Command failed: /vercel/path0/node_modules/@sentry/cli/sentry-cli releases new 7a6096ad8027f8c66dcb77c6eec2c744c537548c
> > [09:59:52.806] error: An organization slug is required (provide with --org)
> > [09:59:52.806]
> > [09:59:52.806] Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
> > [09:59:52.806] Please attach the full debug log to all bug reports.
> > [09:59:52.806]
> > [09:59:52.806]
> > [09:59:52.807] > Build error occurred
> > [09:59:52.807] Error: > Build failed because of webpack errors
> > [09:59:52.807]     at /vercel/path0/node_modules/next/dist/build/index.js:397:19
> > [09:59:52.807]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:60:20)
> > [09:59:52.808]     at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:77:25)
> > [09:59:52.837] error Command failed with exit code 1.
> > [09:59:52.837] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> > [09:59:52.866] Error! Command "yarn run build" exited with 1
> > [09:59:52.978] Error: Command "vercel build" exited with 1
