### ISSUE TITLE
Rewrites in middleware override next.config redirects

### ISSUE THREAD

**Issue by alexanderflink** [vercel/next.js#37890]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.6.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When adding a middleware (tested both with beta _middleware and canary <root>/middleware) and uploading a project to Vercel, it seems that rewrites in the middleware happen even though the page was redirected from the source. This makes the redirects in next.config not work as expected.

### Expected Behavior

I expect a page that is specified to be redirected in next.config to be redirected and not handled by the middleware at all. Otherwise, I would have to check every page that passes through the middleware if it should be redirected or not. Basically making the redirects functionality in next.config useless together with middleware.

### Link to reproduction

https://nextjs-middleware-redirects-bug.vercel.app

### To Reproduce

1. Go to https://nextjs-middleware-redirects-bug.vercel.app/source
2. Notice how the page is being rewritten, even though a redirect is specified in next.config.js from /source to /destination

### Source code
https://github.com/alexanderflink/nextjs-middleware-redirects-bug

**Comment by ijjk** [comment]
Hi, this has been updated in the latest canary of Next.js `v12.1.7-canary.41`, please update and give it a try!
