### ISSUE TITLE
Link component "href" parameter is ignored when different "as" parameter is passed

### ISSUE THREAD

**Issue by Daguima-dag** [vercel/next.js#37899]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.44
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Firefox 101.0.1 (64bits)

### Describe the Bug

Next/link , when provided with both `href` and `as`, ignores the `href` for dynamic routes (even hardcoded like `/path/id`) and only uses the value in `as`.
From what I could test, it only happens when pointing to urls that'd be resolved by a dynamic route. Static routes seem unaffected and navigate/display url properly.

### Expected Behavior

I expected the link to navigate to the url provided, while displaying the `as` value in the browser. Instead, it navigates directly to the `as` url.

### Link to reproduction

https://stackblitz.com/edit/nextjs-daee5m?file=pages%2Findex.js,pages%2Fsubpage%2Fstatic-subpage.js

### To Reproduce

Considering a file structure with:

`pages/subpage/[subpageId]`
`pages/subpage/static-subpage`

Then:
```
// Dynamic - doesn't work
<Link href="/subpage/1" as="/somethingelse">
  <a>Test dynamic route</a>
</Link>

// Static - works
<Link href="/subpage/static-subpage" as="/somethingelse">
  <a>Test static route</a>
</Link>
```

**Comment by ijjk** [comment]
Hi, when you provide different `href` and `as` values like this the automatic `href` resolving for dynamic routes is disabled and you have to manually provide the `href` value e.g. `href={{ pathname: '/subpage/[subpageId]', query: { subpageId: '1' } }}`. x-ref: [related documentation](https://nextjs.org/docs/api-reference/next/link#:~:text=the%20previous%20href/as%20behavior%20is%20used%20as%20shown%20in%20the%20previous%20docs.)
