### ISSUE TITLE
/500 responds with status 500

### ISSUE THREAD

**Issue by markwolff** [vercel/next.js#37926]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

https://nextjs.org/500

### Describe the Bug

Setting up a [server error handler](https://nextjs.org/docs/advanced-features/error-handling#handling-server-errors) at pages/500.js also creates a route at `/500`. Directly navigating to this page results in a document response of 500. Because of this, any alerts monitoring 500 rates are prone to firing. Some workarounds considered
- Setting up redirects on /500
- Ignore 500s on the /500 path

Is this expected behavior, or should one of these workarounds be considered?

### Expected Behavior

This seems like expected behavior, but makes monitoring 5xx percentages on a site prone to false positives.

### Link to reproduction

https://nextjs.org/500

### To Reproduce

https://nextjs.org/500

**Comment by ijjk** [comment]
Hi, this is done by design to allow viewing the related error pages as they will appear e.g. visiting `/404` also responds with `404` even if you have `pages/404.js`

**Comment by markwolff** [comment]
> Hi, this is done by design to allow viewing the related error pages as they will appear e.g. visiting `/404` also responds with `404` even if you have `pages/404.js`

Yeah I figured it was by design. Wondering how you handle alerting on the main nextjs site? Is it on a per-page basis, so you can ignore a random person spamming refreshes on [nextjs.org/500](https://nextjs.org/500)?

**Comment by ijjk** [comment]
We don't monitor the `/500` or `/404` paths themself correct, as a user shouldn't end up on that page naturally unless they are manually entering paths and seeing what matches.
