### ISSUE TITLE
Middleware can't detect image requests

### ISSUE THREAD

**Issue by 11koukou** [vercel/next.js#37939]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise LTSC 2019
    Binaries:
      Node: 16.7.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.45
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Firefox 101.0.1

### Describe the Bug

Hello after upgrading to latest canary release and changing from _middleware.ts to middleware.ts, every request for an image inside my public folder has the "/_next/image" pathname reported inside middleware, while it used to be e.g. "/myImage.png". So it breaks the https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale functionality as it can not correctly detect images anymore. My middleware content is exactly the same as the one in the documentation, nothing added/removed or changed. 

### Expected Behavior

Either the documentation about prefixing the default locale, or the middleware implementation need to change for correctly detecting images and not affecting their url.

### Link to reproduction

https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale

### To Reproduce

Just follow the https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale guideline

**Comment by ksocha** [comment]
I can confirm this, encountered the same issue when was trying to upgrade from `12.1.0` to `12.2.0`.

**Comment by 11koukou** [comment]
Yes that's the way for now. However the documentation will need to be changed to reflect this change. Personally I have paused using the new middleware until the even more serious issues (e.g. https://github.com/vercel/next.js/issues/38267) get fixed.
