### ISSUE TITLE
Google Analytics does not work with Next.js `Script` tag

### ISSUE THREAD

**Issue by brenopolanski** [vercel/next.js#37957]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022
Binaries:
  Node: 16.14.2
  npm: 8.5.0
  Yarn: 1.22.5
  pnpm: N/A
Relevant packages:
  next: 12.1.6
  react: 18.2.0
  react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Chrome 103.0.5060.53 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

If I use GA with `next/script` tag it won't work. But if I use normal `script` tag then it works.

### GA code snippet with `next/script` (not working)

```tsx
<Script
  strategy="afterInteractive"
  src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GA_TRACKING_ID}`}
/>
<Script
  id="ga-tracking"
  strategy="afterInteractive"
  dangerouslySetInnerHTML={{
    __html: `
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '${process.env.GA_TRACKING_ID}', {
        page_path: window.location.pathname,
      });
    `,
  }}
/>
```

### GA code snippet with regular `script` tag (working)

```tsx
<script
  src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GA_TRACKING_ID}`}
/>
<script
  dangerouslySetInnerHTML={{
    __html: `
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '${process.env.GA_TRACKING_ID}', {
        page_path: window.location.pathname,
      });
    `,
  }}
/>
```

### Expected Behavior

Render the GA script in HTML.

### Link to reproduction

https://github.com/brenopolanski/brenopolanski.com/blob/develop/src/pages/_document.tsx#L36

### To Reproduce

1. Run the [project](https://github.com/brenopolanski/brenopolanski.com);
2. Inspect the page;
3. Look for `www.googletagmanager.com/gtag/` under the `Elements` tab.

![Screenshot from 2022-06-23 13-04-40](https://user-images.githubusercontent.com/1894191/175344558-7a6cd5e2-3e60-415d-8d09-e12827e982d6.png)

**Comment by jsdeveloperr** [comment]
Hi @brenopolanski next/script not working in _document.js. I have solution. If you do this gtm is working.
<img width="689" alt="Screenshot at Jun 26 15-30-35" src="https://user-images.githubusercontent.com/94299020/175814302-ad3d8d05-3292-4496-aea1-3d2f2bbd4d1a.png">
<img width="806" alt="Screenshot at Jun 26 15-28-58" src="https://user-images.githubusercontent.com/94299020/175814374-0a167af4-f2c3-4de7-97d6-a6e009db797a.png">
<img width="637" alt="Screenshot at Jun 26 15-26-28" src="https://user-images.githubusercontent.com/94299020/175814379-8eb4344b-960b-4c80-b50c-cfae6c2468f8.png">

**Comment by jsdeveloperr** [comment]
@brenopolanski you can look this repo
https://github.com/jsdeveloperr/nextjs-script-google-analytics

**Comment by comradesharf** [comment]
Add prefix `NEXT_PUBLIC_` to fix this problem. It should become `process.env.NEXT_PUBLIC_GA_TRACKING_ID`

In your dotenv file, change from `GA_TRACKING_ID=` to `NEXT_PUBLIC_GA_TRACKING_ID=`

**Comment by timfuhrmann** [comment]
Should be fixed by https://github.com/vercel/next.js/pull/37894 on canary now.

**Comment by brenopolanski** [comment]
> As commented above, please give `next@canary` a try and let us know if it works!

Hey @balazsorban44, it works with the latest version of Next.js (`v12.2`) if I put `next/script` inside the `_document.tsx` file.

### Example:

```tsx
import { Head, Html, Main, NextScript } from 'next/document'
import Script from 'next/script'

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <NextScript />
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_TRACKING_ID}`}
        />
      </body>
    </Html>
  )
}
```

But if I create an `Analytics.tsx` component and import it into the `_document.tsx` file it doesn't work.

### Example:

- `Analytics.tsx`

```tsx
import Script from 'next/script'

export const Analytics = () => (
  <Script
    strategy="afterInteractive"
    src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_TRACKING_ID}`}
  />
)
```

- `_document.tsx`

```tsx
import { Head, Html, Main, NextScript } from 'next/document'

import { Analytics } from '@/components/Analytics'

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <NextScript />
        <Analytics />
      </body>
    </Html>
  )
}
```

**Comment by RoyBkker** [comment]
Google is advising to put all of the gTag code inside the <head> .

Why can't I find nothing about this advice in any of the docs of Next?

<img width="721" alt="image" src="https://user-images.githubusercontent.com/10207274/179224323-84e14a15-9459-4b64-b529-5ccf516e2b36.png">
