### ISSUE TITLE
Support Number Type for next/link children

### ISSUE THREAD

**Issue by flyingSquirrel-dev** [vercel/next.js#37981]
### Describe the feature you'd like to request

- Codesandbox URL: https://codesandbox.io/s/supporting-number-type-for-next-link-ketl7u?file=/pages/index.js

I think it would be better to support the `number` type for next/link children.
Can I open a PR to support it if it's okay with you? :)

### Describe the solution you'd like

- Draft PR URL: https://github.com/flyingSquirrel-dev/next.js/pull/1/files

```javascript
// packages/next/client/link.tsx
if (legacyBehavior && (typeof children === 'string' || typeof children === 'number')) {
  children = <a>{children}</a>
}
```

### Describe alternatives you've considered

Add a condition to check the type of children

**Comment by SukkaW** [comment]
IMHO it is a bug. I have opened PR #38013 to fix it.

**Comment by flyingSquirrel-dev** [comment]
@SukkaW Thanks for your PR.

I was about to create the PR to fix it, so I raised this issue to check if it is bug or not before creating PR.

I wish you would have asked first before taking this issue. I feel like my all efforts and time to find the bug have been wasted.
