### ISSUE TITLE
Image disappear Layout="responsive"

### ISSUE THREAD

**Issue by hafidzamr** [vercel/next.js#38019]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
 Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.14.2
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

Image disappear when have more then 1 Image with Layout="responsive"

### Expected Behavior

Image still showing ?

### Link to reproduction

[Repo](https://github.com/hafidzamr/my-catalogs)

### To Reproduce

https://user-images.githubusercontent.com/49369600/175788107-fddf5588-739b-4294-82dd-728e8eef1e00.mp4

**Comment by balazsorban44** [comment]
please add a reproduction. you can invite me to the private repo, or preferably create a minimal repository that focuses on the bug, thanks!

**Comment by hafidzamr** [comment]
> Please test out the `next@canary` release first, to make sure this hasn't been fixed there yet.
> 
> If you still see an issue, please add a reproduction. you can invite me to the private repo, or preferably create a minimal repository that focuses on the bug, thanks!

updated repo 

if u add props in this line `layout="reponsive" `  
[redirect to line code](https://github.com/hafidzamr/my-catalogs/blob/a1c0a9ee20e726b7c3c581d7b341c8487ba73acd/components/ui/Product/ImageSlider.tsx#L37) 

then trying runing the app -> go to product detial -> all image disappear like on video

**Comment by timfuhrmann** [comment]
The problem's most likely your image container's (`image__thumbs-wrapper`) dimensions. 

E.g. applying `width: 60px;` instead of `max-width: 60px;` **should be one of many ways** to fix it.

**Comment by hafidzamr** [comment]
> The problem is most likely one of the parents' dimensions.
> 
> E.g. applying `width: 60px;` instead of `max-width: 60px;` to `image__thumbs-wrapper` should be one of many ways to handle it.

i seee, I must declare specific width right? I'm added `width: 60px` and solved, thank you @timfuhrmann  

[codesandbox](https://codesandbox.io/s/small-paper-cxys1f?file=/styles/globals.scss:595-631)
