### ISSUE TITLE
Next.js Commerce: No Output Directory named "public" found after the Build completed - on first deploy.

### ISSUE THREAD

**Issue by motcodes** [vercel/next.js#38036]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.0.0: Thu Jun 16 20:32:32 PDT 2022; root:xnu-8792.0.92.121.3~2/RELEASE_X86_64
    Binaries:
      Node: 14.19.3
      npm: 8.12.1
      Yarn: 1.22.19
      pnpm: 7.2.1
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

warn  - Latest canary version not detected, detected: "12.1.6", newest: "12.1.7-canary.48".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

Commerce

### What browser are you using? (if relevant)

Chrome 102.0.5005.115 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

Via Clone and Deploy from the nextjs.org/commerce site

### Describe the Bug

The deployment failed after choosing Shopify as the integration and trying to build it.
**Error is a missing public folder**

<img width="1792" alt="Screenshot 2022-06-26 at 17 05 42" src="https://user-images.githubusercontent.com/20223529/175820688-384378ab-3d3c-4470-872a-2998afe2e023.png">

### Expected Behavior

The next.js commerce template should have a public folder.

### To Reproduce

1. Go to https://nextjs.org/commerce site, and hit the `Clone and Deploy` Button.
2. Select Github
3. Select Shopify
4. Let it deploy

**Comment by balazsorban44** [comment]
I tried reproducing this given the above steps, but my build succeeded. I notified the team working on commerce, but this was unlikely a Next.js bug anyway, so I'm closing this issue. If you still have problems, I recommend opening an issue at https://github.com/vercel/commerce
