### ISSUE TITLE
Invalid first char of a key in env files - comments should start with hashtags

### ISSUE THREAD

**Issue by radunemerenco** [vercel/next.js#38043]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 7.3.0
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

### Which example does this report relate to?

with-neo4g, with-apollo-neo4j-graphql

### Describe the Bug

Commented lines in env example files start with double slashes `//` instead of hashtag `#`

### Expected Behavior

The commented lines in env files should start with hashtag `#`

### To Reproduce

Rename `.env.local.example` file to `.env`, add proper env vars and start the app.

**Comment by balazsorban44** [comment]
Fixed in https://github.com/vercel/next.js/pull/38044
