### ISSUE TITLE
Anchor tag "download" does not set the suggested filename when using <Link/>

### ISSUE THREAD

**Issue by benjamintd** [vercel/next.js#38060]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.48
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Chrome Version 102.0.5005.61 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

Those two bits of code behave differently: 
```
<Link href="/api/export">
  <a download="file.xslx">Download</a>
</Link>
```

```
<a href="/api/export" download="file.xslx">Download</a>
```

The first one downloads a file called `export.xslx` (provided that the right Content-Type header is set on the response), the second one a file called `file.xslx`. 

A `download` attribute on the Anchor tag should set the suggested filename ([MDN doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download)).
Note that the generated markup is the right one (the download attribute does exist in the DOM <a> element), but the downloaded file has the wrong name. 

### Expected Behavior

That first code example should download a file called `file.xslx`. 

### Link to reproduction

https://stackblitz.com/edit/nextjs-bmfers?file=pages/index.js

### To Reproduce

Click both links in the reproduction and notice the different behavior regarding the `download` tag.

**Comment by thebergamo** [comment]
After some debugging and ponderation I would rather say this is the correct behaviour.

Why?

When using the `next/link` component, its intent is to "navigate" to other pages, which is for what this component was created in the first place. 

>Client-side transitions between routes can be enabled via the Link component exported by next/link.
[next/link docs] (https://nextjs.org/docs/api-reference/next/link)

So despite your `Link` points to some API to generate the csv file, it would always trigger the Navigation Events which causes some errors in your browser console (vide screenshot).
![image](https://user-images.githubusercontent.com/1778730/176011471-8755a7b3-3a12-4ea8-a62c-c677433ce7ae.png)

So it has the correct behaviour, not a bug.
To achieve your goal in here you should simply use the `a` tag which is not only meant to navigate between pages but also help with this download options as mentioned by you @benjamintd.

**Comment by benjamintd** [comment]
Thanks for your analysis. I used a <Link> tag to enable prefetching, as well as per the linter suggestion. However, I'll switch back to a regular anchor tag if that's the better option.

**Comment by stefanprobst** [comment]
i think this should be supported by `next/link`.
