### ISSUE TITLE
Reopen #19936

### ISSUE THREAD

**Issue by Johnrobmiller** [vercel/next.js#38068]
Reopen [#19936](https://github.com/vercel/next.js/issues/19936)

This very obviously should not have been closed -- the overwhelming majority of community has sided against the one contributor who closed this issue, yet because this single contributor is able to have the last word, they close they issue before it is ready to be closed. It's fine to push back against the community, but to close an issue like this is a slap in the face.

**Comment by timfuhrmann** [comment]
A little harsh, since this is currently being discussed. For further reference read the following RFC: https://github.com/vercel/next.js/discussions/27953

> We’re exploring if a solution to this RFC could be implemented with the Layouts RFC

**Comment by balazsorban44** [comment]
As explained above, the discussion is moved to an RFC/discussion. If you have any feedback, please tell us there.
