### ISSUE TITLE
Output File Tracing - no longer have standalone folder with latest next.js

### ISSUE THREAD

**Issue by zigang93** [vercel/next.js#38110]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 12.1.6
      react: 17.0.2
      react-dom: 17.0.2

warn  - Latest canary version not detected, detected: "12.1.6", newest: "12.1.7-canary.52".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

Reproduce step: 
1. with official example: `npx create-next-app --example with-docker nextjs-docker`
2. run `docker build -t nextjs`

Failed with this error:
```zsh
 => ERROR [runner  9/10] COPY --from=builder --chown=nextjs:nodejs /app  0.0s
------
 > [runner  9/10] COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./:
------
failed to compute cache key: "/app/.next/standalone" not found: not found
```

### Expected Behavior

should output as standalone folder

### Link to reproduction

npx create-next-app --example with-docker nextjs-docker

### To Reproduce

1. with official example: `npx create-next-app --example with-docker nextjs-docker`
2. run `docker build -t nextjs`

**Comment by zigang93** [comment]
@ijjk please have a look

**Comment by ijjk** [comment]
Hi, this is due to the rename of the config, updating to the latest stable version of Next.js `v12.2` should resolve this
