### ISSUE TITLE
CI: react@next react@experimental tests broken

### ISSUE THREAD

**Issue by yuxizhe** [vercel/next.js#38125]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

next 12

### Describe the Bug

regularly tests for react@next react@experimental broken for mouths

https://github.com/vercel/next.js/actions/workflows/test_react_experimental.yml
https://github.com/vercel/next.js/actions/workflows/test_react_next.yml
<img width="999" alt="image" src="https://user-images.githubusercontent.com/14990734/176275698-65f5f2fb-f749-4d45-bcb2-2310c8e1a563.png">

### Expected Behavior

We shoud fix those.

### Link to reproduction

https://github.com/vercel/next.js/actions/workflows/test_react_experimental.yml https://github.com/vercel/next.js/actions/workflows/test_react_next.yml

### To Reproduce

https://github.com/vercel/next.js/actions/workflows/test_react_experimental.yml
https://github.com/vercel/next.js/actions/workflows/test_react_next.yml

**Comment by AkifumiSato** [comment]
Is there any way to stop this?
I want to stop getting notifications every day.
