### ISSUE TITLE
Cannot find name 'URLPattern'

### ISSUE THREAD

**Issue by jonahallibone** [vercel/next.js#38131]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.9.0
      Yarn: 1.22.10
      pnpm: 4.14.4
    Relevant packages:
      next: 12.2.0
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

I am trying to upgrade to the GA Middlware. I previously had used logic such as 
```
const { page }  = req
...
const isActualPage = !!page.name
```
to test against the URL in my middleware so i could be sure that I was only affecting urls that corresponded to my `pages` directory. Since this was removed in next `12.2` I had begun following the guide found [here](https://nextjs.org/docs/messages/middleware-request-page) to upgrade my application to use `URLPattern` instead. I am, however, having trouble using that as VSCode and TS are telling that name doesn't exist. I am having a hard time finding any information on `URLPattern` at all in other applications, so debugging as been tough.

<img width="773" alt="Screen Shot 2022-06-28 at 6 26 47 PM" src="https://user-images.githubusercontent.com/8886318/176314807-82629799-555e-4bcf-a9fc-1a3391a23aca.png">

If there's something I need to add my global namespaces or otherwise, this just doesn't seem to work with the default Next.js TS config.

### Expected Behavior

`new URLPattern()` should be available in VSCode/TS globals

### Link to reproduction

https://codesandbox.io/s/ecstatic-marco-s3lo6n?file=/middleware.ts

### To Reproduce

1. Create a `middleware.ts` in your src or root folder
2. Try and use `new URLPattern()`

**Comment by SukkaW** [comment]
`URLPattern` is a new web standard that landed recently, check [URLPattern - MDN](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern) and [URLPattern - WICG](https://wicg.github.io/urlpattern/#urlpattern).

Although it is supported by Next.js' edge runtime, it is not implemented in Node.js and TypeScript:

- https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1199
- https://github.com/nodejs/node/issues/40844

@Kikobeats Maybe we should include the type definition for URLPattern?

- https://github.com/denoland/deno/issues/12558
- https://github.com/denoland/deno/pull/14430
- https://github.com/kenchris/urlpattern-polyfill/blob/main/src/types.d.ts

**Comment by jonahallibone** [comment]
@SukkaW It would be great if you guys could!

**Comment by balazsorban44** [comment]
Related #38103

**Comment by jonahallibone** [comment]
@balazsorban44 it seems like that PR got closed without a merge, safe to say that we'll still get this in the future? Probably won't upgrade to 12.2 until the edge global are available

**Comment by balazsorban44** [comment]
Already working on it!

**Comment by javivelasco** [comment]
Thanks for reporting this! We thought of a nice solution and we are working on it like @balazsorban44 said. Coming ASAP!

**Comment by szaveri** [comment]
Recently upgraded to NextJS 12.2.0 and as a workaround for anyone looking to upgrade (plan to change this once this issue is resolved)

```typescript
import type { URLPattern } from 'types/urlpattern';

/* eslint-disable no-undef */
// @ts-expect-error
new URLPattern({ pathname: pattern }) as URLPattern,
```

with the type definition here https://github.com/kenchris/urlpattern-polyfill#api-reference

**Comment by jonahallibone** [comment]
Any update on this? I am going to implement @szaveri's solution ASAP because not upgrading our middleware is starting to affect our billing on Vercel (since changes to middleware quota's coincided with the 12.2.0 release).

**Comment by sannajammeh** [comment]
Workaround:
`npm i urlpattern-polyfill -D`

In global.d.ts or any other d.ts file (make sure its a d.ts to avoid accidentally including this polyfill)
```ts
declare global {
  import URLPattern from "urlpattern-polyfill";
}
```

**Comment by zenyr** [comment]
> In global.d.ts or any other d.ts file (make sure its a d.ts to avoid accidentally including this polyfill's JS code)

Or you can safely add this to `next-env.d.ts` right next to `next.config.js`

```ts
/// <reference types="urlpattern-polyfill" />
```
