### ISSUE TITLE
Rewrites in middleware with locales and dynamic routes

### ISSUE THREAD

**Issue by vincentboiardt** [vercel/next.js#38146]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.12.3
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

I have setup locales and a routing with the following structure:
`pages/[country]/[[...uri]].js`

In the middleware we want to rewrite URLs like `/en-us/hello-world` to `/en/us/hello-world`: https://github.com/vincentboiardt/middleware-issue/blob/main/middleware.js

It works well unless if the URL has a locale and country which is the same, e g `/de-de/hello-world`.

Browsing to https://middleware-issue.vercel.app/sv-se/hello-world will show the following:

    {
	    "query": {
		    "country": "se",
		    "uri": [
			    "hello-world"
		    ]
	    },
	    "params": {
		    "country": "se",
		    "uri": [
			    "hello-world"
		    ]
	    },
	    "locale": "sv"
    }

Which is what I expect

Browsing to https://middleware-issue.vercel.app/de-de/hello-world will show the following:

    {
	    "query": {
		    "country": "hello-world"
	    },
	    "params": {
		    "country": "hello-world"
	    },
	    "locale": "de"
    }

This is wrong

### Expected Behavior

The rewrite should always work the same way regardless of the contents of the pathname.

Browsing to https://middleware-issue.vercel.app/de-de/hello-world should show the following:

    {
	    "query": {
		    "country": "de",
		    "uri": [
			    "hello-world"
		    ]
	    },
	    "params": {
		    "country": "de",
		    "uri": [
			    "hello-world"
		    ]
	    },
	    "locale": "de"
    }

### Link to reproduction

https://github.com/vincentboiardt/middleware-issue/blob/main/middleware.js

### To Reproduce

https://middleware-issue.vercel.app/sv-se/hello-world
https://middleware-issue.vercel.app/de-se/hello-world
https://middleware-issue.vercel.app/de-de/hello-world <-- wrong behaviour

**Comment by vincentboiardt** [comment]
It looks like `defaultLocale` is changed for each case. So it may be due to `country` being the same as `defaultLocale`.

**Comment by vincentboiardt** [comment]
Not sure if this could have something to do with the issue:
https://github.com/vercel/next.js/blob/canary/packages/next/shared/lib/i18n/normalize-locale-path.ts

**Comment by JanKaifer** [comment]
I'd recommend migrating away from `i18n` to a custom middleware.
`i18n` won't be supported in `app/` anyway.
