### ISSUE TITLE
Image is not blurred again when updating the src props

### ISSUE THREAD

**Issue by rayhk6** [vercel/next.js#38144]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

The image source is a dynamic variable and would be updated by clicking other thumbnails. I have added a blurred image to indicate the image is loading. However, It doesn't go blurred again when updating the src. The image only shows when the new image is updated. 

  ```
   <Image
                            src={imagePath}
                            alt={"alt image"}
                            layout={"fill"}
                            objectFit={"cover"}
                            priority={true}
                            placeholder="blur"
                            blurDataURL="blur data url"                            
                        />
```

### How are you deploying your application? (if relevant)

yarn dev

### Describe the Bug

N/A

### Expected Behavior

the blur image will show every time when I updated the image src.

### Link to reproduction

yarn dev

### To Reproduce

every time I update the image path.

**Comment by Kinbaum** [comment]
What about adding `key={ imagePath }` to the component to force react to rerender it

**Comment by JanKaifer** [comment]
Yup, `key` is the way to go.
