### ISSUE TITLE
Middleware basic authentication not working anymore with Next 12.2

### ISSUE THREAD

**Issue by federicocappellotto97** [vercel/next.js#38145]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 14.18.3
      npm: 6.14.15
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.0
      eslint-config-next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Locally

### Describe the Bug

Before updating my basic auth middleware was working. Then i updated to Next 12.2, migrated my middleware following the guide, but now `req.headers.get("authorization")` is returning null

### Expected Behavior

Opening the website should appear the basic auth modal, but is not working anymore

### Link to reproduction

https://codesandbox.io/s/blissful-lehmann-yujd69

### To Reproduce

Open the sandbox, and see that the basic auth modal is not appearing

**Comment by blurrah** [comment]
Looking at your reproduction, you're not asking the visitor to enter basic auth credentials so the authorization header will not be defined.

You should send a 401 with a `WWW-Authenticate` header to ask for credentials, the dialog will then show.
Example:
```js
return NextResponse.next({
    status: 401,
    headers: {
      "WWW-Authenticate": "Basic realm=realm"
    }
  });
```

I updated your sandbox with a fixed version that asks for the header: https://codesandbox.io/s/vibrant-architecture-mr5i5m

**Comment by federicocappellotto97** [comment]
Now it’s clear, thank you so much!!

Federico Cappellotto
Il 29 giu 2022, 12:24 +0200, Boris Besemer ***@***.***>, ha scritto:

**Comment by doug-skinner** [comment]
@federicocappellotto97 if the above comment resolved the problems that you were having, would you be able to close this issue out to help keep the issues list clear?
