### ISSUE TITLE
'+' removed from URL query parameters using withRouter()

### ISSUE THREAD

**Issue by mjhalwa** [vercel/next.js#38143]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.52
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.1.7-canary.52", newest: "12.2.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

Firefox 101.0.1 (64-Bit)

### How are you deploying your application? (if relevant)

npm run dev

### Describe the Bug

after starting my app with `npm run dev` I access `./pages/some.js` at `http://localhost:3000/some?search=blub&sort=-id,+val,+type&fields=id,val,type` passing several query parameters. I use next.js' built-in `withRouter` to obtain the parameters within the `this.props.router.query` object. Even though `this.props.router.asPath` still contains the `+` and `-`, the `query` Object does look like this:

``` json
{
  "fields": "id,val,type",
  "search": "blub",
  "sort": "-id, val, type"
}
```

where in `sort` the `-` is recognized correctly, but the `+` is not.

Is this on purpose? If yes why?

### Expected Behavior

I would expect a query-Object like:

``` json
{
  "fields": "id,val,type",
  "search": "blub",
  "sort": "-id, val, type"
}
```

Explanation:

I created an API to allow for explicit ascending and descending sort order of specific fields with `sort` as well es de- and selecting fields with `fields`. My intend was to support `sort=val` (asc), `sort=-val` (desc) and `sort=+val` (asc).

### Link to reproduction

https://github.com/mjhalwa/next-router-issue

### To Reproduce

1. run the project

    ``` ps1
    npm run dev
    ```

2. goto http://localhost:3000/some?search=blub&sort=-id,+val,+type&fields=id,val,type

3. Open Debug-Console in Browser to view output

**Comment by timneutkens** [comment]
This is expected behavior as the browser built-in parsing of urls outputs the same:

```js
new URL('http://localhost:3000/some?search=blub&sort=-id,+val,+type&fields=id,val,type').searchParams.forEach(console.log)
```

Googling for `plus in querystring` you end up on this page that explains why: https://stackoverflow.com/questions/6855624/plus-sign-in-query-string#:~:text=%2B%20sign%20has%20a%20semantic%20meaning,pairs%20in%20the%20query%20string.
