### ISSUE TITLE
/_next/data is permanently redirected if a middleware is present and trailingSlash is enabled

### ISSUE THREAD

**Issue by mccuna** [vercel/next.js#38189]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.10.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.1
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Irrelevant

### How are you deploying your application? (if relevant)

Irrelevant

### Describe the Bug

We have an app that uses the `next@12.2` middleware features and at the same time has `trailingSlash`  set to `true` in `next.config.js`. 

When the app is opened for the first time in a browser tab it works correctly. However, navigating to any page with `getServerSideProps` via the `Link` component results in the corresponding `/_next/data` request getting a 308 response and therefore in the server-side data not reaching the client-side. 

The issue reproduces if both, a middleware is present and `trailingSlash` is set to `true`. It doesn't matter what the `middleware` does (it can just `return NextResponse.next()`), it just needs to be present.

### Expected Behavior

The `/_next/data` request gets a 200 OK response containing the data from the server-side.

### Link to reproduction

https://codesandbox.io/s/trailing-slash-middleware-issue-rhvbbx

### To Reproduce

1. Star the app using `yarn dev`
2. Click on the "Go to dummy" link

**Comment by rudden** [comment]
Experiencing the exact same issue.

**Comment by kodkroken** [comment]
We're also experiencing the same issue when upgrading from 12.1.6 -> 12.2.

**Comment by MeanBoyCousin** [comment]
Can also confirm. Removal of `trailingSlash` from config fixes this for pages that load valid data. However, a page that returns `notFound: true` in `getServerSideProps` simply returns an empty object as a result of a 404 on the `/_next/data` path.

**Comment by icyJoseph** [comment]
Also experiencing this. Exact same as others. In our case, we rewrite `/a/b/c/` to `/z/` + `GSSP`,  with `a`, `b`, and `c`, as search params. 

It works navigating directly to `/a/b/c/` but if we do Client Side transitions, the `JSON` payload from `GSSP` comes back with 308. 

As soon as I unwind the logic to not use trailing slashes, it all works as expected.
