### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by mygoalistokillbill** [vercel/next.js#38180]
### What is the improvement or update you wish to see?

I would like to see more info of how Link component interacts with Incremental Static Regeneration.
Now if Link has prefetch=true it seems Incremental Static Regeneration doesn't work. E.g. when I click on the link it uses prefetched json files, which are not updated through ISR, and thus ISR effectively does not work. If so I would like to see the comment that prefetch={true} doesn't work with Incremental Static Regeneration.

### Is there any context that might help us understand?

No

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/link

**Comment by leerob** [comment]
Prefetching does not change whether ISR works or does not work 🙏
