### ISSUE TITLE
Build failed in CI, Module not found: Can't resolve '@swc/helpers/src/_define_property.mjs' in 

### ISSUE THREAD

**Issue by Innei** [vercel/next.js#38192]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Next version: 12.2.0
CI: Github Action
Node: 16

### Describe the Bug

Build failed in CI, but build sccuess in local.

### Expected Behavior

Build sccuess.

### Link to reproduction

https://github.com/mx-space/kami/runs/7128771175?check_suite_focus=true

### To Reproduce

Upgrade Next to 12.2.0 and build it in GitHub CI

**Comment by balazsorban44** [comment]
Likely fixed in https://github.com/vercel/next.js/pull/38174 it's not in a `canary` release yet, so please keep an eye on https://github.com/vercel/next.js/releases and report back if it was not fixed in the next release. :pray:

**Comment by rizaldirnm** [comment]
> This mine, after update to `12.2.0`
> 
> ```
> 
> Module not found: Can't resolve '@swc/helpers/src/_object_spread.mjs'
> 
> > 1 | import { AppProps } from 'next/app';
> 
>   2 | import Head from 'next/head';
> 
>   3 | import 'tailwindcss/tailwind.css';
> 
>   4 | import './styles.css';
> 
> ```
> 
> 
> 
> Using `nx.dev` environment 
> 
> > "@nrwl/next": "^14.2.4"
> 
> 
> 
> Also already check using `"next": "v12.2.1-canary.1"` result still the same.
> 
> 
> 
> 

Forget to mention that I'm using PNPM as dependecies manager

**Comment by oyed** [comment]
Latest canary fixes the issue (`12.2.1-canary.2`).

**Comment by ijjk** [comment]
Closing as noted above this should be resolved in the latest canary, please update and give it a try!
