### ISSUE TITLE
[`v12.2`] [middleware GA] Removing `page` from `NextRequest` breaks authentication use case

### ISSUE THREAD

**Issue by bennettdams** [vercel/next.js#38195]
## Use case

I would like to use middleware for authentication. I can check the authentication status based on cookies on the request.
If the user is not signed in, I can redirect him to a sign in page. But I only want/need to do this check for real pages/routes, not for everything else.

```ts
if (
  !req.page.name ||
  !!isRevalidationRequest ||
  req.page.name === ROUTES.SIGN_IN ||
  req.page.name.startsWith("/api")
) {
  // the request is not for one of our pages or it is for the sign in page or it is an API route request, go on
  return NextResponse.next();
} else {
  // check auth and redirect if necessary...
}
```

## Background

With `v12.2` the `page` field does not exist anymore on the `NextRequest` in middleware.
We used `page` to find out whether a request in the middleware was for a page route, so we can check the authentication status and redirect to a sign in page if necessary.

This was already [discssued in the middleware RFC](https://github.com/vercel/next.js/discussions/29750#discussioncomment-2122618), but without an official response.

I know that `page` was never officially documented, but now that middleware is in "general availability", I feel like there is a gap for this functionality, hence this feature request.

## Issue

Now that [**all** requests are intercepted by middleware](https://nextjs.org/docs/messages/middleware-upgrade-guide#executing-middleware-on-internal-nextjs-requests) and we **also** [don't have `page` anymore](https://nextjs.org/docs/messages/middleware-upgrade-guide#no-more-page-match-data), there's no good way to identify a request that needs to be authenticated anymore. This is because middleware now also runs for e.g.
 - `_next`/internal requests 
 - public assets (like `favicon.ico`)
 - fetches to custom URLs (e.g. an external backend like `/my-backend/some-data`) when using a proxy/rewrites

### Describe the solution you'd like

I would like to be able to identify in middleware whether a request is for a page or not.

### Describe alternatives you've considered

The only thing that comes to my mind is writing down all routes in the project and match the URL in the middleware, but this is a brittle solution, as a new route can easily be forgotten in this setup. 
Maybe the list of registered routes can be provided via Next.js' internal routing, so there's no way to forget a route.

**Comment by balazsorban44** [comment]
Hi, check out https://nextjs.org/docs/advanced-features/middleware#matcher

**Comment by bennettdams** [comment]
Hey @balazsorban44,

for the case of authentication (every page should only be accesible for authenticated users), this is a very brittle solution. If you add a new page and forget to add it to the matchers, this page is accessible without authentication.

Using a root wildcard matcher (like `'/:path*') also does not work, because now **all** requests, even non-page requests, are included again.

**Comment by tiepvuvan** [comment]
I'm also disappointed with the new matcher, we don't want to validate assets request like `.json`, `.js`. We only want to protect some pages.

New matcher doesn't include options like `/:teamId/:path*`, it that impossible to protect dynamic route paths?

Also, why did you close this issue without a solution?  @balazsorban44
