### ISSUE TITLE
next/head breaks when using @preact/compat in 12.2

### ISSUE THREAD

**Issue by vattenapa** [vercel/next.js#38204]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: 7.1.7
    Relevant packages:
      next: 12.2.1-canary.1
      eslint-config-next: N/A
      react: N/A
      react-dom: N/A
```

### Describe the Bug

When using next-plugin-preact, adding a `<Head>` tag to any page from next/head leads to the tags being rendered in the <body> tag with an <undefined></undefined> element due to the bag of head-tags are passed as a Set to the renderer. Hacking in something like following fixes the problem:

*shared/lib/head.js*:
```
function onlyReactElement(list, child) {
  [...]
  if (child instanceof Set) list.concat(...Array.from(child))
}
```

Removing `next-plugin-preact` also fixes the issue without changing the set to an array.

### Expected Behavior

Usage of Head to work when using next-plugin-preact.

Since there is an official example in the repository, I would expect aliased `@preact/compat` to work.

### Link to reproduction

https://github.com/vattenapa/next-preact-repro

### To Reproduce

start the dev server and visit the website. Console will show warnings about next-head-count missing since it's been moved to the body with an `<undefined></undefined>` tag above it.

**Comment by grefrit** [comment]
Same issue, doesn't work on 12.2.1-canary.1 too

**Comment by huozhi** [comment]
I filed a fix PR it for it although it seems better to improve the `preact.Children.toArray` support in preact to align the behavior with react

The behavior is different

```js
require('react').Children.toArray(new Set([1,2,3]))
// > [1, 2, 3]

require('preact').Children.toArray(new Set([1,2,3]))
// > [Set(3) {1,2,3}]
```
