### ISSUE TITLE
Images don't load when using next/image but loads when using img tag

### ISSUE THREAD

**Issue by KushalRaut** [vercel/next.js#38211]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I am running next js version 12 and react version 17

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

I am currently building an application with Next Js with local shopify backend and while displaying an static or images with a external URL the HTML < img / > works just fine but < Image / > from 'next/image' does not load the image.

### Expected Behavior

I want my images to load with next/image

### Link to reproduction

Don't have it my code is available at https://github.com/KushalRaut/shopify-graphql-ecommerce/blob/main/components/products/ProductCard/ProductCard.tsx

### To Reproduce

Don't really have an idea of how to reproduce. But here are the screenshots 
![image](https://user-images.githubusercontent.com/71455986/176744247-d6aa2f50-97ad-46b7-a02c-ce1dcffcd93d.png)
![image](https://user-images.githubusercontent.com/71455986/176744334-16009cca-3760-4f7b-aeee-bf791d2a08d8.png)

**Comment by salmanansari14** [comment]
I wanna work on this issue !!

**Comment by laurentDellaNegra** [comment]
Did you try importing the image with import:

replace 
`const placeHolderImage = '/img/product-image-placeholder.svg'`

by
`import placeHolderImage from 'public/img/product-image-placeholder.svg'`

https://nextjs.org/docs/basic-features/image-optimization#local-images

**Comment by KushalRaut** [comment]
Ok, I found the bug. next/image from next js version 12 doesn't seem to work with react version 17.0.2 but seems to work flawlessly with react v18 so I am closing this issue for now.

**Comment by KushalRaut** [comment]
> Did you try importing the image with import:
> 
> replace `const placeHolderImage = '/img/product-image-placeholder.svg'`
> 
> by `import placeHolderImage from 'public/img/product-image-placeholder.svg'`
> 
> https://nextjs.org/docs/basic-features/image-optimization#local-images

Yes I did try importing in both ways but didn't get any result.
