### ISSUE TITLE
Docs: Hydration failed caused by changed props

### ISSUE THREAD

**Issue by JunfXiao** [vercel/next.js#38217]
### What is the improvement or update you wish to see?

The following cause for failed hydration should be documented, as it could be an Error that is not easily detected:

Hydration will fail if some variables by reference are changed, which are passed to component's props.

### Is there any context that might help us understand?

I've made an example in the following link:
https://github.com/ForInfinity/hydration-failed-example/blob/c37a0d534ac0c3a3d38f26eaca5f435482fa96b5/pages/index.tsx#L11-L15

If an array `arr` is passed by `getStaticProps` to a component, and in the rendering, the following code is executed:
```typescript
const {arr} = props;
const headItem = arr.shift();
...
return <div>
              <h2>HeadItem: {headItem}</h2>
              {
                  arr.map((str,i)=>(
                      <p key={i}>{str}</p>
                  ))
              }
        </div>
```
A `Hydration Failed` Error will be throwen. The reason is that in SSR, `arr` is changed and becomes `arr.slice(1)`. And `arr.slice(1)` is saved in static HTML. At client side, the hydration uses the changed `arr` and will surely miss the first element of the original array, which caused `React Hydration Failed`.

A possible way to fix it:
```typescript
// const {arr} = props;
// const headItem = arr.shift()
const [headItem, ...arr] = props.arr
```

It would be rather helpful, if this cause can be mentioned in the [Possible Ways to Fix It](https://nextjs.org/docs/messages/react-hydration-error#possible-ways-to-fix-it) Section.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/react-hydration-error

**Comment by samcx** [comment]
@JunfXiao Feel free to create a <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture> for this and ping me!

Due to the age of this issue, I will be closing this in the meantime.
