### ISSUE TITLE
Double server from CLI

### ISSUE THREAD

**Issue by Arctomachine** [vercel/next.js#38232]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.1
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

CLI

### Describe the Bug

I have `app.js` file in root folder.
```js
const start = require('next/dist/cli/next-start')
start.nextStart()
```
It starts 2 servers at the same time. It starts dev server instead of production and overwrites contents of `.next` folder with files of dev server.
```
> node app.js
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```
Accessing localhost:3000 returns error 404

### Expected Behavior

Only start production server

### Link to reproduction

https://github.com/Arctomachine/reproduction-double-server

### To Reproduce

1. Run `next build`
2. Run `node app.js`

**Comment by benjaminbrgs** [comment]
Also have this issue when deploying on AWS Beanstalk

**Comment by QuiiBz** [comment]
I don't think the server is started twice:

The first log is coming from
https://github.com/vercel/next.js/blob/6b8e499c7bf13914cca92f9da1737d358133ee20/packages/next/cli/next-start.ts#L88

and the second one is from
https://github.com/vercel/next.js/blob/6b8e499c7bf13914cca92f9da1737d358133ee20/packages/next/build/output/store.ts#L56

**Comment by Arctomachine** [comment]
`require('next/dist/cli/next-start')` alone already starts server and gives one output. If you try only this line, you will get fully working dev server.
But in either case, with 2 outputs it starts malfunctioning dev server, while functioning production is expected.

**Comment by QuiiBz** [comment]
I searched a bit and the issue first appeared in version [12.1.1-canary.5](https://github.com/vercel/next.js/releases/tag/v12.1.1-canary.5).

Importing `next/dist/cli/next-start` without calling `nextStart()` before this version does not start the server.
