### ISSUE TITLE
Wrapping codes into <React.Fragment> didn't work 

### ISSUE THREAD

**Issue by vespaiach** [vercel/next.js#38242]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022
    Binaries:
      Node: 18.2.0
      npm: 8.9.0
      Yarn: N/A
      pnpm: 7.4.1
    Relevant packages:
      next: 12.2.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I had my code to check whether a certain env variables set or not before including `<Script>` tags in `<Head>` section in **_document** file, and because there were more than one Script tag, so I wrapped them with one React.Fragment tag. After that, my code didn't work, those **Script** tags weren't loaded.

```jsx
class MyDocument extends Document {
    render() {
        return (
            <Html lang="en" className="scroll-smooth">
                <Head>
                    <link rel="stylesheet" href="/main.css" />
                    {process.env.NEXT_PUBLIC_GTAG_ID && (
                        <>
                            <Script
                                strategy="beforeInteractive"
                                src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GTAG_ID}`}
                            />
                            <Script
                                strategy="beforeInteractive"
                                dangerouslySetInnerHTML={{
                                    __html: `
                                        window.dataLayer = window.dataLayer || [];
                                        function gtag(){dataLayer.push(arguments);}
                                        gtag('js', new Date());
                                        gtag('config', '${process.env.NEXT_PUBLIC_GTAG_ID}');
                                    `,
                                }}
                            />
                        </>
                    )}
                </Head>
                <body className="bg-white text-gray-500 antialiased dark:bg-gray-900 dark:text-white">
                    <Main />
                    <NextScript />
                </body>
            </Html>
        );
    }
}
```

### Expected Behavior

According to [the document](https://nextjs.org/docs/api-reference/next/head#:~:text=title%2C%20meta%20or%20any%20other%20elements%20(e.g.%20script)%20need%20to%20be%20contained%20as%20direct%20children%20of%20the%20Head%20element%2C%20or%20wrapped%20into%20maximum%20one%20level%20of%20%3CReact.Fragment%3E%20or%20arrays%E2%80%94otherwise%20the%20tags%20won%27t%20be%20correctly%20picked%20up%20on%20client%2Dside%20navigations.). Wrapping Script tags into one level of `<React.Fragment>` should work.

### Link to reproduction

https://github.com/vespaiach/personal_website/blob/2a76d9f9196901bf844623192cd238da373a489c/pages/_document.tsx

### To Reproduce

You can check out [my repository](https://github.com/vespaiach/personal_website) with commit id: `2a76d9f9196901bf844623192cd238da373a489c` for the bug reproducing

**Comment by EliseiNicolae** [comment]
Hi @vespaiach, I've added the scripts for gtm as following:

<img width="719" alt="Screenshot 2022-07-01 at 22 28 51" src="https://user-images.githubusercontent.com/43387542/176958101-ee48bd70-fd1f-475e-a287-17b96c3e6e79.png">

**Comment by seanlail** [comment]
I think this is related to https://github.com/vercel/next.js/issues/3399.

If I have meta tags in a fragment like `<>` then they are not rendering correctly.
If I inspect the page, I can see the tags... but if I open dev tools and write this I can't find them:

```
document.querySelectorAll("head meta").forEach( m => console.log(m.outerHTML))
``` 

Removing the fragment fixes it though 🙃

**Comment by timneutkens** [comment]
Nested fragments are indeed not supported in `next/head`. The new App Router has built-in support for metadata which replaces `next/head` which doesn't have this problem: https://beta.nextjs.org/docs/api-reference/metadata
