### ISSUE TITLE
12.2.0 trailingSlash:true + middleware breaks all dynamic routes!

### ISSUE THREAD

**Issue by Nexum** [vercel/next.js#38241]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.19.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When enabling trailingSlash:true AND a middleware.js all routing with dynamic parts is broken! 
This affects dev and production builds.

To verify the bug just go into next.config.js and disable trailingSlash OR remove the middleware.js, after doing either the bug will be gone and the page will work as expected.

### Expected Behavior

middleware + trailingSlash: true should NOT break all dynamic routes :(

### Link to reproduction

https://github.com/Nexum/nextjs-bug-link-12-2-0

### To Reproduce

1. Clone Repo
2. Run `yarn`
3. Run `yarn dev`
4. Open http://localhost:3000 in a browser of your choice
5. Open DevTools (Network Tab)
6. Klick any of the 3 links, the headline will vanish.
![image](https://user-images.githubusercontent.com/1257361/176931049-f99cd125-639c-4337-812e-d824cfbc45fb.png)
7. Notice the Redirect in your network tab
![image](https://user-images.githubusercontent.com/1257361/176931002-a480cc3c-78bf-46eb-bd7a-b53b1fb06c08.png)

**Comment by Nexum** [comment]
Weirdly enough this even breaks on my local machine when i next build and next start the app, but works on vercel. We verified this on a colleagues machine (linux) so it's not windows related...

**Comment by icyJoseph** [comment]
Most likely https://github.com/vercel/next.js/issues/38189, related?
