### ISSUE TITLE
Next 12.2.0 - Using Emtion with SWC still does not work fully

### ISSUE THREAD

**Issue by admapop** [vercel/next.js#38291]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.2
      eslint-config-next: 12.2.0
      react: 18.1.0
      react-dom: 18.1.0
```

### Describe the Bug

I use `emotion` in our project, before Next 12.2 emotion support in SWC was still experimental and therefore we held off and was still using babel. However, now that it's not experimental we decided to try it out.

However, we get a build error:
```Error: Component selectors can only be used in conjunction with @emotion/babel-plugin, the swc Emotion plugin, or another Emotion-aware compiler transform.```

### Expected Behavior

I expected the `swc_emotion` crate in SWC to work correctly

### Link to reproduction

https://codesandbox.io/s/swc-emotion-problem-gnp94o

### To Reproduce

All you need is emotion/react, emotion/styled and to turn it on in next config.

Then you need two styled components, one which is a parent, and the other which will be a child. Then use `Component` selector `${ComponentName}` to style said child.

**Comment by filkalny-thimble** [comment]
You can workaround this by using the classnames of the components manually. I also tagged all the places with a comment so that in the future once something equivalent to `@emotion/babel-plugin` exists, I can easily remove them.
```ts
const ChildComponent = styled.span`
    // child styles
`;

const ContainerComponent = styled.div`
    // container styles
    ${ChildComponent.toString()/* @emotion/swc-plugin */} {
        // child styles when contained in container
    }
`;
```

**Comment by Brooooooklyn** [comment]
@admapop hey, in the codesandbox link you provided, everything is working fine for me

![image](https://user-images.githubusercontent.com/3468483/177476221-4815c9e3-2051-47e1-9e68-c30db65fbfec.png)

**Comment by admapop** [comment]
Not sure what to make of it, not happening in the sandbox anymore, still happening in our codebase, I've checked and the package version on both sandbox and our project are nearly identical.

**Comment by admapop** [comment]
![image](https://user-images.githubusercontent.com/52109936/177506185-19f59783-72d2-495c-8f18-a6c6dd1dbef8.png)

**Comment by vip30** [comment]
I'm facing exactly same issue with passing option to styled function

i.e.

```ts
styled(Abc, {   shouldForwardProp: (propertyName: string) => !propertyName.startsWith("$") })
```

here is the reproduce link
https://codesandbox.io/s/swc-emotion-problem-forked-c7fbit?file=/pages/index.tsx

**Comment by vip30** [comment]
@admapop can you confirm if it's the same case on your codebase?

cc: @Brooooooklyn @kdy1

**Comment by admapop** [comment]
@vip30 In our case, we have a wrapper util which deals with transient props so we don't use `shouldForwardProp` directly in options. However, this doesn't trigger the error mentioned above, only when using component selectors in styles.

```js
const styled = ((
  component: keyof JSX.IntrinsicElements & StyledTags,
  config: any,
) => {
  config = {
    shouldForwardProp: (prop: string) => !prop.startsWith('$'),
    ...config,
  };
  return _styled(component, config);
}) as typeof _styled;
```

**Comment by vip30** [comment]
> @vip30 In our case, we have a wrapper util which deals with transient props so we don't use `shouldForwardProp` directly in options. However, this doesn't trigger the error mentioned above, only when using component selectors in styles.
> 
> ```js
> const styled = ((
>   component: keyof JSX.IntrinsicElements & StyledTags,
>   config: any,
> ) => {
>   config = {
>     shouldForwardProp: (prop: string) => !prop.startsWith('$'),
>     ...config,
>   };
>   return _styled(component, config);
> }) as typeof _styled;
> ```

Yes I think using config in styled and use that component selector will cause the errors.

You can check my sandbox link

**Comment by admapop** [comment]
@vip30 You're right actually, just tried it in my sandbox as well. The culprit seems to be `shouldForwardProp`.

FYI @Brooooooklyn

**Comment by vip30** [comment]
> @vip30 You're right actually, just tried it in my sandbox as well. The culprit seems to be `shouldForwardProp`.
> 
> It breaks even if you do plain HTML.
> 
> ```js
> styled("p", {
>   shouldForwardProp: (propertyName: string) => !propertyName.startsWith("$")
> })
> ```
> 
> FYI @Brooooooklyn

I think the problem part is the config even you set an empty object inside the config, it still throw error

```ts
styled("p", {})
```
