### ISSUE TITLE
router.pathname returns paths without a trailing slash regardless of next.config trailingSlash setting

### ISSUE THREAD

**Issue by zizzfizzix** [vercel/next.js#38304]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:

- Platform: darwin
- Arch: arm64
- Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000

Binaries:
- Node: 18.0.0
- npm: 8.6.0
- Yarn: N/A
- pnpm: N/A

Relevant packages:
- next: 12.2.1-canary.2
- eslint-config-next: N/A
- react: 18.2.0
- react-dom: 18.2.0

### Describe the Bug

`router.pathname` returns paths without the trailing slash (e.g. `/about`) despite `trailingSlash: true` in the `next.config`

### Expected Behavior

`router.pathname` should return paths with the trailing slash as configured e.g. `/about/`

### Link to reproduction

https://github.com/zizzfizzix/next-pathname-trailing-slash-bug

### To Reproduce

1. Install dependencies with `npm install`
2. Start with `npm run dev`
3. Head to the `/about/` page (note: lacks the index page as the root pathname is correct regardless)
4. Compare the output (pathname) with the URL path

**Comment by balazsorban44** [comment]
I tried tracing this back, and it seems like this has always been the case, as long as `trailingSlash` existed as a `next.config.js` option. The true path can be found on `router.asPath`. I'll double check if this is just missing some documentation.

**Comment by zizzfizzix** [comment]
Thanks for looking into it, @balazsorban44. I would argue that using `router.asPath` is not a substitute for this, as it will return the browser path as-is. There are many cases (such as the `canonical` link tag) where you might want to use the canonical path, not whatever the user requested.
