### ISSUE TITLE
next/link fetch json file multiple times when hover

### ISSUE THREAD

**Issue by aNyMoRe0505** [vercel/next.js#38360]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
    Binaries:
      Node: 18.4.0
      npm: 8.12.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.0
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

hello, when I hover the next/link and the target page using getStaticProps, it will fetch the json files multiple times in the latest version

https://user-images.githubusercontent.com/9814815/177457552-5320cd99-f6f3-42df-b528-e0784ae9f6ab.mov

but in the version 12.1.6, it behave differently

https://user-images.githubusercontent.com/9814815/177457667-99571595-ed97-4786-9b42-8ed3c0a25a51.mov

### Expected Behavior

I think fetch only one time is correct behavior, but after `12.2.0` it becomes fetch multiple times 

### Link to reproduction

https://github.com/aNyMoRe0505/next-link-test/blob/master/package.json

### To Reproduce

npm ci && npm run build && npm run start then try to hover the link and see network tab

and if you change the next version to 12.1.6, you will see the different result

**Comment by ijjk** [comment]
Hi, this is currently expected as a part of Next.js' new optimistic cache updating. Previously Next.js would only prefetch once but now with On-Demand ISR the cache could have been updated so we optimistically update the cache on hover to fetch fresh data in case it's available. If fresh data is not available the server should respond with a 304 response which doesn't use up more bandwidth.

**Comment by aNyMoRe0505** [comment]
@ijjk 
Hello, thanks for your reply.
But when I click the link to navigate to the Page A, it will still fetch the a.json again
so the only benefit is server will respond the data with 304 to save bandwidth?
is it possible that we can have an option to indicate next/link not fetch the json file again when we click the link to navigate ?
