### ISSUE TITLE
next/router Client routing + Middleware does not work as expected

### ISSUE THREAD

**Issue by thienna** [vercel/next.js#38363]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.3
      eslint-config-next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome Version 103.0.5060.53 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel, using next build

### Describe the Bug

I want to conditional rewrite using middleware based on cookie, here the cookie name is `logged_in`.
I have 2 pages `/` and `/login` (NOT using generated on demand), the flow when user on `/` page is:
- If cookie `logged_in` present and true > middleware return `NextResponse.next()`
- If cookie `logged_in` does not present > middleware return `NextResponse.rewrite(new URL(`/login`, req.url))`

After `next build` and `next start`, when I am in page`/` and do `router.replace(router.asPath)` although the middleware is still running, the UI is not updated.

`next dev` working fine.
UPDATE: this only happens on 12.2 and above

### Expected Behavior

The behavior should be consistent regardless of `next dev` and `next build`.
I don't understand why it happens, can you explain?

### Link to reproduction

https://github.com/thienna/demo-nextjs-discussion

### To Reproduce

1. Clone repo and run `next build` and `next start`
2. Go to `localhost:3000`
3. Click login
4. Click logout
5. Click login again > watch the UI

**Comment by awareness481** [comment]
Is  `response.headers.set("x-middleware-cache", "no-cache");` still an option? I don't see it in the docs.

That's what I what do for my middleware auth pre 12.2

**Comment by thienna** [comment]
@awareness481 
yeah I don't see it in the docs too, I have tried using it but it is not working

**Comment by ryanhaticus** [comment]
Can you clarify how `next build` isn't behaving the same? What's occuring?

**Comment by thienna** [comment]
@ryanhaticus do you clone the repo and follow reproduce step?

**Comment by mccuna** [comment]
Not sure, but might be the same issue as #38408

**Comment by thienna** [comment]
yeah, maybe this too https://github.com/vercel/next.js/issues/38405

**Comment by eposha** [comment]
I have the exact same problem, is there a solution to this problem?

**Comment by thienna** [comment]
fixed in [v12.2.4-canary.9](https://github.com/vercel/next.js/releases/tag/v12.2.4-canary.9)
