### ISSUE TITLE
Jest encountered an unexpected token when DynamoDB imported into file under test

### ISSUE THREAD

**Issue by herdsothom** [vercel/next.js#38368]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I cannot get Jest to work correctly with my new install of NextJS, when using a test that calls a file that imports DynamoDB (im assuming this will also happen for other packages)

I get the following error:
```
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/xxx/Development/next/with-jest-app/node_modules/uuid/dist/esm-browser/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { default as v1 } from './v1.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
```

This happens when the test calls an exported function that imports DynamoDB.

Of course if i simply remove the import, the test will pass.

### Expected Behavior

The test should pass

### Link to reproduction

See the reproduce steps

### To Reproduce

To reproduce it using a very basic setup, i ran:
`npx create-next-app --example with-jest with-jest-app`

I added to my `package.json` dependencies:
`"@aws-sdk/client-dynamodb": "^3.121.0",`

I created a new test file `example.test.js` in the `__tests__` directory.
Note that in this new test file, a simple test like `expect(1).toBe(1)` works fine.
If I make it:
```
import {getFromDynamo} from '../lib/ddb'

test('fails', async () => {
    expect(await getFromDynamo()).toBe(3)
})
```

And in `ddb.js`:
```
import {DynamoDBClient} from "@aws-sdk/client-dynamodb";

export const getFromDynamo = async () => {
    return 3
}
```

**Comment by ryanhaticus** [comment]
It looks like Jest wasn't expecting the `export` token from the `uuid` package (a dependency of DynamoDB). According to [issue 488](https://github.com/uuidjs/uuid/issues/488) from the UUID repository, this seems to be related to a "reverse dependency of this package".

Some users have reported this issue solving itself after updating their version of NodeJS.

I'd reckon you create a separate issue in https://github.com/thenativeweb/uuidv4/ as suggested by @ctavan [here](https://github.com/uuidjs/uuid/issues/488#issuecomment-664585063). This likely **isn't** an issue with NextJS.

**Comment by herdsothom** [comment]
> It looks like Jest wasn't expecting the `export` token from the `uuid` package (a dependency of DynamoDB). According to [issue 488](https://github.com/uuidjs/uuid/issues/488) from the UUID repository, this seems to be related to a "reverse dependency of this package".
> 
> Some users have reported this issue solving itself after updating their version of NodeJS.
> 
> I'd reckon you create a separate issue in https://github.com/thenativeweb/uuidv4/ as suggested by @ctavan [here](https://github.com/uuidjs/uuid/issues/488#issuecomment-664585063). This likely **isn't** an issue with NextJS.

Thanks for the reply Ryan.
Unfortunately Im already on node16 so dont think I can find a fix there.
Howcome you suggest to raise the issue in uuidv4 rather than just uuid? Isnt `uuid` the package dynamo is using here?

**Comment by ryanhaticus** [comment]
> > It looks like Jest wasn't expecting the `export` token from the `uuid` package (a dependency of DynamoDB). According to [issue 488](https://github.com/uuidjs/uuid/issues/488) from the UUID repository, this seems to be related to a "reverse dependency of this package".
> > Some users have reported this issue solving itself after updating their version of NodeJS.
> > I'd reckon you create a separate issue in https://github.com/thenativeweb/uuidv4/ as suggested by @ctavan [here](https://github.com/uuidjs/uuid/issues/488#issuecomment-664585063). This likely **isn't** an issue with NextJS.
> 
> Thanks for the reply Ryan. Unfortunately Im already on node16 so dont think I can find a fix there. Howcome you suggest to raise the issue in uuidv4 rather than just uuid? Isnt `uuid` the package dynamo is using here?

Yes, `uuid` would be the correct package.
Sorry about that.

**Comment by herdsothom** [comment]
Raising an issue in the uuidjs/uuid project now. Ps heres a codesandbox:
https://codesandbox.io/s/boring-resonance-g84z3y?file=/__tests__/example.test.js

**Comment by JanKaifer** [comment]
It seems that there has been fix in the `uuid` package.
