### ISSUE TITLE
Error overlay `<HotlinkedText>` doesn't hotlink URLs in parenthesis

### ISSUE THREAD

**Issue by AndrewRayCode** [vercel/next.js#38362]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
npx --no-install next info

node:fs:2550
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, realpath '~/test/info
```
😛 

### Describe the Bug

<img width="973" alt="Screen Shot 2022-07-05 at 8 04 39 PM" src="https://user-images.githubusercontent.com/79215/177459220-390d0c43-c965-4cb7-9f86-f2dd511108fb.png">

Nextjs error overlay doesn't link URLs properly if they're enclosed in parenthesis (and probably other cases too). See in the above screenshot that the parenthesis are part of the link.

https://github.com/vercel/next.js/blob/canary/packages/react-dev-overlay/src/internal/container/Errors.tsx#L47-L56 is not a robust linking solution.

I suggest replacing the home grown link component with https://www.npmjs.com/package/react-link-text I'm happy to open a PR if that makes sense here?

### Expected Behavior

The link to link

### Link to reproduction

https://codesandbox.io/s/next-js-link-error-overlay-iy0kek

### To Reproduce

Click on the link

**Comment by JanKaifer** [comment]
Thanks for reporting.
We try to be thoughtful about our dependencies and I think that using a package for this is not needed.

Would love to review someone's PR for fixing our code though.
You can get inspired by that package if you want, just keep it minimal.
