### ISSUE TITLE
[NEXT-694] Template literals produce ERR_TOO_MANY_REDIRECTS in middleware matcher

### ISSUE THREAD

**Issue by ryanhaticus** [vercel/next.js#38374]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**Operating System:**
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
**Binaries:**
      Node: 18.1.0
      npm: N/A
      Yarn: N/A
      pnpm: 7.0.0-rc.9
**Relevant packages:**
      next: 12.2.0
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 103.0.5060.66

### Describe the Bug

When using [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) in a [middleware matcher](https://nextjs.org/docs/advanced-features/middleware#matcher), the browser produces a `ERR_TOO_MANY_REDIRECTS` error.

This will produce an error:
```js
export const config = {
  matcher: `/fake-directory/:path*`,
};
```

This will not:
```js
export const config = {
  matcher: '/fake-directory/:path*',
};
```

Please see this [live reproduction on Vercel](https://middleware-matcher-reproduction.vercel.app/real-directory).

### Expected Behavior

A middleware matcher with a template literal should work as if it was any other string.

### Link to reproduction

https://github.com/ryanhaticus/middleware-matcher-reproduction

### To Reproduce

1. Define middleware.
2. Export a configuration with the `matcher` key.
3. The value of `matcher` should be a string created by a template literal (tildas).
4. Run `yarn dev` or deploy the application.
5. Observe the error.

<sub>[NEXT-694](https://linear.app/vercel/issue/NEXT-694/template-literals-produce-err-too-many-redirects-in-middleware-matcher)</sub>

**Comment by ryanhaticus** [comment]
Looks like [this function](https://github.com/vercel/next.js/blob/canary/packages/next/build/analysis/get-page-static-info.ts#L165) may need some changes. I'm going to look into it and possibly PR later today.

**Comment by ryanhaticus** [comment]
I've looked into this a little bit. May be related to how template literals are interpreted as functions. Going to try a few things.

**Comment by ryanhaticus** [comment]
Took down the reproduction on Vercel. Was maxing out my usage limits.

**Comment by ztanner** [comment]
Hey @ryanhaticus -- I'm no longer able to repro this and it looks like it's been working properly since ~12.3.0. Going to close this out.
