### ISSUE TITLE
Docs: How to mock useRouter from next/router in Cypress component testing?

### ISSUE THREAD

**Issue by maxpopovitch** [vercel/next.js#38397]
### What is the improvement or update you wish to see?

I'd like to have more information about the mocking of useRouter from next/router in Cypress component testing.

### Is there any context that might help us understand?

I use Cypress for components testing in my project.

Here is the code snippet from my component:
```
...
import { useRouter } from 'next/router';
...

const AccountDetails: VFC = () => {
  const router = useRouter();
  const { accountUUID } = router.query;
  ...
  return <div deta-testid="cool" />;
};

export default AccountDetails;
```
and this is how I want to test it:
```
it('should show loader if there is no data', () => {
    mount(<AccountDetails />).then(() => {
      cy.get('[data-testid="cool"]').should('be.visible');
    });
  });
```
For now, I've got this error:
```
TypeError: The following error originated from your test code, not from Cypress.

  > Cannot read properties of null (reading 'query')

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
```
How can I mock `useRouter`, or perhaps you can suggest another way to manage this test to be successfully running?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/testing

**Comment by PSoltes** [comment]
Same is happening, when mocking useRouter in jest jsdom.... nothing is exported, useRouter is null even after mocking

**Comment by joshuaolusayo** [comment]
Somebody should please offer any insight into this issue

**Comment by amaralc** [comment]
The following video can help to clarify the issue:

https://www.youtube.com/watch?v=uF2lqBluQV8&ab_channel=BrunoAntunes

**Comment by leerob** [comment]
Covered here with an example: https://nextjs.org/docs/pages/building-your-application/optimizing/testing
