### ISSUE TITLE
getServerSideProps not called on Link click if middleware is present

### ISSUE THREAD

**Issue by mccuna** [vercel/next.js#38408]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro   
    Binaries:
      Node: 16.10.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.4     
      eslint-config-next: 11.0.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Irrelevant

### How are you deploying your application? (if relevant)

Irrelevant

### Describe the Bug

`getServerSideProps` is not called when clicking on a `Link` component if a middleware is present. It doesn't matter what the middleware does, it can be just a  plain `return NextResponse.next();`.

The issue reproduces only when running a `production` build

### Expected Behavior

`getServerSideProps` is called when clicking on a `Link`, even if a middleware is present.

### Link to reproduction

https://github.com/mccuna/middleware-routing-issue

### To Reproduce

1. `npm run build`
2. `npm start`
3. Click on the "Go to login" link
4. Click on the "Set login cookie" button
5. Click on the "Go to homepage" link

The `loggedIn` cookie is present, but the homepage still displays "Is logged in: not logged in". In order to see the "Is logged in: logged in" message a refresh (F5 in the browser) is needed.

**Comment by awareness481** [comment]
I can reproduce this issue but changing the middleware code to

```js
import { NextResponse } from "next/server";

export const middleware = () => {
  const response = NextResponse.next();
  response.headers.set("x-middleware-cache", "no-cache");
  return response;
};
```
fixes this. Can you confirm that as well?

@balazsorban44 I'm not able to write good documentation around this I think, but I think this definitely needs to be in the docs, perhaps as a caveat.
I suspect the other issue linked here might be fixed by this as well

**Comment by mccuna** [comment]
Indeed, setting the `x-middleware-cache` response header to `no-cache` solves the issue. 

Is this how the middlewares are supposed to work, or setting the  `x-middleware-cache` header is just a temporary workaround? I'm asking in order to know if I need to revisit this part of my app in the future and remove it.

**Comment by awareness481** [comment]
> ```diff
> x-middleware-cache
> ```

Yep, it makes sure it doesnt use the prefetched result from next/link. It seems like it was never added to the next docs.

https://github.com/vercel/next.js/pull/32767

**Comment by mccuna** [comment]
Ok, clear, thanks for helping me out! I'll close the issue as it seems it's not an actual bug, but a misconfiguration on my side.
