### ISSUE TITLE
Middleware rewrites *all* dynamic routes as soon as it has rewritten one

### ISSUE THREAD

**Issue by klaasman** [vercel/next.js#38405]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
Binaries:
  Node: 16.14.2
  npm: 8.5.0
  Yarn: 1.22.18
  pnpm: N/A
Relevant packages:
  next: 12.2.1-canary.4
  eslint-config-next: 12.2.0
  react: 18.2.0
  react-dom: 18.2.0
```

### Describe the Bug

Under certain circumstances, middleware will rewrite routes which should _not_ be rewritten. This happens only with dynamic routes in a **production build**.

Given the following middleware:
```js
// /middleware.js
import { NextResponse } from "next/server";

export function middleware(request) {
  return request.nextUrl.pathname.includes("page-2")
    ? NextResponse.rewrite(`${request.nextUrl.origin}/insufficient-access`)
    : NextResponse.next();
}
```

And the following page:
```js
// /pages/directory/[param].js
export async function getServerSideProps(context) {
  const { page } = context.params;
  return { props: { page } };
}

export default function Page({ page }) {
  return <p>Hello {page}</p>;
}
```

Then, with client-side routing:
- visiting `/directory/page-1` will render the correct page
- visiting `/directory/page-2` will render the `insufficient-access` page

But,  as soon you've visited `/directory/page-2` all other `/directory/*` will get the `insufficient-access` page served as well.

### Expected Behavior

Do not rewrite all routes of a dynamic route, as soon as one of them is rewritten by middleware.

### Link to reproduction

https://github.com/klaasman/nextjs-middleware-rewrite-bug

### To Reproduce

1. run a build `yarn build` (issue won't happen in a development build)
2. start app `yarn start`
3. visit app [localhost:3000](http://localhost:3000)
4. click a "Page 1" link - target page is rendered
5. hit back button
6. click a "Page 2" link (of same section) - "no access" page is rendered
7. hit back button
8. click "Page 1" link - expected to see target page, instead we see the "no access" page. Refresh page to see target page.

---

Additionally there's also this deployment: https://nextjs-middleware-rewrite-bug.vercel.app/ 
But for some reason the "get static props" example won't work because the "page-1" route does a server round trip (= no client-side routing).. Possibly related with the root cause of the original issue, who knows.

The "get server-side props" example _does_ show the issue.

**Comment by Vlad-imeer** [comment]
Might be related to #38408

**Comment by klaasman** [comment]
Could be, although the suggested `x-middleware-cache`  fix header doesn't help with this issue.

**Comment by thienna** [comment]
@klaasman yeah, I have created the similar issue

**Comment by afewyards** [comment]
also running into this issue, blocking us from upgrading to 12.2

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.2.4-canary.3` of Next.js, please update and give it a try!
