### ISSUE TITLE
Prefetch request is performed on every hover when `x-middleware-cache` is set to `no-cache` 

### ISSUE THREAD

**Issue by mccuna** [vercel/next.js#38413]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro   
    Binaries:
      Node: 16.10.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.4     
      eslint-config-next: 11.0.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Irrelevant

### How are you deploying your application? (if relevant)

Irrelevant

### Describe the Bug

If the `x-middleware-cache` is set to `no-cache`, the prefetch request is performed every time the mouse hovers over a `Link`. Hovering over the same `Link` 5 times results in 5 prefetch requests.

For a single, isolated `Link` this wouldn't be an issue, but if a page has a lot of  `Link`s (like most apps do nowadays) it results in a ton of prefetch requests.

P.s.: the reason behind `x-middleware-cache` set to `no-cache` is #38408

### Expected Behavior

Don't perform the prefetch request every time the mouse hovers over a `Link`. 

There is already PR #37299 which adds a way to prevent the prefetch on hover, but it looks kind of stale.

### Link to reproduction

https://github.com/mccuna/too-many-prefetch-requests

### To Reproduce

1. `npm run build`
2. `npm start`
3. Hover back and forth over the homepage links

The network tab will quickly get filled with a bunch of prefetch requests.

![reproduction](https://user-images.githubusercontent.com/14298072/177765137-a5c24ac1-87c3-4c3c-99ee-75dab342b7d1.gif)

**Comment by jakejarvis** [comment]
FWIW I'm also encountering this, but without any middleware present.

**Comment by aprendendofelipe** [comment]
https://github.com/vercel/next.js/issues/38360#issuecomment-1178527748:

> Hi, this is currently expected as a part of Next.js' new optimistic cache updating. Previously Next.js would only prefetch once but now with On-Demand ISR the cache could have been updated so we optimistically update the cache on hover to fetch fresh data in case it's available. If fresh data is not available the server should respond with a 304 response which doesn't use up more bandwidth.

**Comment by mccuna** [comment]
Thanks for the reply! I'm closing this issue then as this is how NextJS is supposed to work.
