### ISSUE TITLE
Middleware matcher matches everything if provided a variable

### ISSUE THREAD

**Issue by controversial** [vercel/next.js#38461]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.5
      eslint-config-next: 12.2.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

Consider a project with the following middleware.js file:
```js
import { NextResponse } from 'next/server';

export function middleware(req) {
  console.log(`Evaluating middleware on ${req.nextUrl.pathname}`);
  return NextResponse.next();
}

export const config = {
  matcher: ['/test-page'],
}
```
This function only ever logs “Evaluating middleware on /test-page,” as expected.

However, if the config section is changed to the following:
```js
const testPath = '/test-page';
export const config = {
  matcher: [testPath],
}
```
now, when loading `/test-page` the function will log the following:
```
Evaluating middleware on /_next/static/chunks/webpack.js
Evaluating middleware on /_next/static/chunks/main.js
Evaluating middleware on /_next/static/chunks/react-refresh.js
Evaluating middleware on /_next/static/chunks/pages/_app.js
Evaluating middleware on /_next/static/development/_buildManifest.js
Evaluating middleware on /_next/static/development/_ssgManifest.js
Evaluating middleware on /_next/static/chunks/pages/test-page.js
Evaluating middleware on /_next/static/development/_devMiddlewareManifest.json
Evaluating middleware on /_next/static/development/_devPagesManifest.json
Evaluating middleware on /test-page
```
as if the matcher is ignored completely.

### Expected Behavior

I expect that the matcher config will still work even if it references a variable.

### Link to reproduction

https://github.com/controversial/next-middleware-matcher-repro

### To Reproduce

1. `npm install`
2. `npm run dev`
3. Navigate to localhost:3000/test-page
4. Observe console logs

**Comment by icyJoseph** [comment]
Wanna know something even more interesting, if you do:

```ts
export let config = {
  matcher: ['/test-page'],
}
```

I'll also do this. 

The reason, as far sa I was able to study, is that the middleware is not really imported or used a module, or a script, like we do regularly, instead it is transformed into an AST, and compiled like that.

When the AST is built, they look specifically, for an export config where theres is a matcher key that's a value, or array value, but  not an expression. 

Not saying there's no issue, just sharing what I learned.
