### ISSUE TITLE
`query` not updating on `shallow` push when middleware is defined 

### ISSUE THREAD

**Issue by ajmnz** [vercel/next.js#38495]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
    Platform: linux
    Arch: x64
    Version: #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022
Binaries:
    Node: 14.18.1
    npm: 6.14.15
    Yarn: 1.22.17
    pnpm: N/A
Relevant packages:
    next: 12.2.2
    eslint-config-next: N/A
    react: 17.0.2
    react-dom: 17.0.2

### Describe the Bug

In v12.2.2, when pushing a route using `shallow: true` within a catchAll route **and with a middleware defined**, `query` is not updated.

Say we've got the `/pages/[...catalog].tsx` page, we are on `/shoes` and we want to go to `/shoes/black`.

```tsx
// /middleware.ts

export function middleware() {}

// /pages/[...catalog].tsx

const CatalogPage = () => {
  const { query, push } = useRouter();
  return (
    <>
      <button
        onClick={() => {
          push("/[...catalog]", "/shoes/black", { shallow: true });
        }}
      >
        Push
      </button>
      <pre>{JSON.stringify({ query }, null, 2)}</pre>
    </>
  );
};
```

When clicking the button, `query` will not be updated regardless of the path changing.

### Expected Behavior

It is expected that `query` is updated after pushing the new route, as per [the documentation](https://nextjs.org/docs/routing/shallow-routing).

### Link to reproduction

https://codesandbox.io/s/cranky-burnell-295k32

### To Reproduce

1. After loading the Sandbox, click on the `Go to shoes` link. It should take you to `/shoes`. There you can see the actual value for `query`, which should be `query.catalog = ["shoes"]`
2. Now click the `push` button, which will set the url to `/shoes/black`. You'll see that the `query` value stays the same, when it should've been `query.catalog = ["shoes", "black"]`.
3. Reload the page from within the Sandbox browser, and you'll see the correct expected value for `query`
4. Now change the `middleware.js` filename to something else like `__middleware.js`, so it doesn't get picked up by next.
5. Go back to `/shoes`
6. Click the `push` button again, and you'll see that this time the `query` value gets correctly updated

---
### Edit 1
It seems like regular dynamic routes are also affected by this issue. See [the updated reproduction]( https://codesandbox.io/s/magical-allen-ibzr6l) including regular dynamic routes.

> In v12.2.2, when pushing a route using `shallow: true` within a ~~catchAll~~ dynamic route **and with a middleware defined**, `query` is not updated.

**Comment by mxck** [comment]
I have this bug in regular paths, not just in cathAll.

**Comment by ajmnz** [comment]
> I have this bug in regular paths, not just in cathAll.

Yep, can confirm this. Here's the extended reproduction including regular dynamic routes: https://codesandbox.io/s/magical-allen-ibzr6l

**Comment by trm217** [comment]
We have this issue on tons of pages, also with regular routes. Must have been caused by 12.2.1 or 12.2.2.

**Comment by DiaaEddinBK** [comment]
it is still here, kind of frustrating

**Comment by DiaaEddinBK** [comment]
more attention is needed here, this is a critical bug

**Comment by DiaaEddinBK** [comment]
When this will be resolved ?

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.2.4-canary.3` of Next.js, please update and give it a try!
