### ISSUE TITLE
Using assetPrefix with i18n breaks static files

### ISSUE THREAD

**Issue by federico-moretti** [vercel/next.js#38509]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.10.0
      npm: 7.24.0
      Yarn: 1.22.18
      pnpm: 7.1.5
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When using `assetPrefix`, custom rewrites and a i18n config the static files respond with 404, if I remove the i18n config everything works correctly.

### Expected Behavior

The static files should not return 404.

### Link to reproduction

https://github.com/federico-moretti/error-next-i18n-asset-prefix

### To Reproduce

To recreate the problem, start a new project with this config:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  assetPrefix: '/custom',
  async rewrites() {
    return [
      { source: '/custom/_next/:path*', destination: '/_next/:path*' },
      { source: '/custom/api/:path*', destination: '/api/:path*' },
    ];
  },
  i18n: { locales: ['en', 'it'], defaultLocale: 'en' },
};

module.exports = nextConfig;
```

**Comment by iljamulders** [comment]
Same as: https://github.com/vercel/next.js/issues/31718

**Comment by ijjk** [comment]
Closing as duplicate per above
