### ISSUE TITLE
Docs: SWC example for Why did you render

### ISSUE THREAD

**Issue by RodrigoTomeES** [vercel/next.js#38502]
### What is the improvement or update you wish to see?

Use SWC instead of babel.

### Is there any context that might help us understand?

In compiler documentation of [NextJS](https://nextjs.org/docs/advanced-features/compiler) said if there is a `babel.config.js` file the app will use babel instead of SWC so should be insteresting to update the example to use SWC config.

<img width="1021" alt="imagen" src="https://user-images.githubusercontent.com/13077343/178205651-cbf5fb0b-45c4-43d9-a443-8b807e7a65f3.png">

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/tree/canary/examples/with-why-did-you-render

**Comment by secmohammed** [comment]
@RodrigoTomeES this might help https://stackoverflow.com/questions/69807341/how-to-configure-why-did-you-render-with-nextjs-12

**Comment by RodrigoTomeES** [comment]
> @RodrigoTomeES this might help https://stackoverflow.com/questions/69807341/how-to-configure-why-did-you-render-with-nextjs-12

Hi, thanks, yes I used that way
