### ISSUE TITLE
using middleware with base path

### ISSUE THREAD

**Issue by magsout** [vercel/next.js#38528]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.2.2
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

I added in my next config a basePath. I use the middleware example here https://nextjs.org/docs/advanced-features/i18n-routing for adding the default locale. by doing this all pages with a query are empty. If I remove the middleware everything works. 

### Expected Behavior

- redirection works fine

### Link to reproduction

https://github.com/magsout/repro-middleware-nextjs

### To Reproduce

- go to https://github.com/magsout/repro-middleware-nextjs (clone, deploy and run)
- go to http://localhost:3000/admin/en
- click on [Show all environments](http://localhost:3000/admin/en/environments/2) link
- see on devtools console query is empty (no id).
- refresh, see on console query is not empty

if you comment the middleware, no issue at all.

**Comment by samuelcole** [comment]
I think this might be what I'm seeing! I walked through the code and found that 12.1.7 introduced some logic that removed the query params, and downgrading to 12.1.6 fixed it for me: https://github.com/vercel/next.js/commit/d959d283fb8912271fac54d73f910c4397bb297c#r83332647

**Comment by samuelcole** [comment]
just checked: this error still occurs in 12.3.0 (which makes sense, since it was still present in canary), but i was hoping because router changes were in the release log
