### ISSUE TITLE
next-lint: lint entire src directory

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#38533]
### Describe the feature you'd like to request

By default, the `next lint` only lints a select few directories:

https://github.com/vercel/next.js/blob/68047112d6ad9ac293161ecd3d594b05eda4d258/packages/next/lib/constants.ts#L60-L67

Which is also confirmed in the docs [here](https://nextjs.org/docs/basic-features/eslint#linting-custom-directories-and-files) so this seems like it is the intentional behavior.

I believe linting the entire `/src` directory would be a good default behavior.

### Describe the solution you'd like

By default, `next-lint` should lint the entire `/src` directory as well as the other select few directories outside `src` (pages, components, lib) for people not adopting the src structure.

### Describe alternatives you've considered

You can achieve this today by modifying the lint script like this:

`”lint”: “next lint —dir src”`

I feel like if you are adopting putting all files in src instead of having the directories in the project root (like the default examples have), there is no real point in not running the linter over all subdirectories. Outside src there might be directories you would want to treat differently (perhaps script etc) so limiting it to a select few here seems reasonable.

**Comment by TheoBr** [comment]
+1 to this, was shocked to see that `src/*` isn't linted in it's entirety. If there's a reason for that I'd love to hear, otherwise feels like an oversight

**Comment by housseindjirdeh** [comment]
Thanks for the feedback here folks. There's no particular reason why the entire `src/` isn't linted to be honest aside from my thinking that there may be some directory structures that folks would want to treat differently inside of `src/`. But I agree that's not likely the case.

I can submit an update to fix this behavior 🙏

**Comment by menushka** [comment]
I could probably disable that behaviour in my IDE, but seeing as the `.eslintrc.json` sits by default in the root directory and I believe the spec calls for linting all files in the directory, I think my IDE is actually behaving correctly in this situation.
