### ISSUE TITLE
API Route POST request without trailing slash seem to be turned into GET

### ISSUE THREAD

**Issue by harjis** [vercel/next.js#38542]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.2.0
      eslint-config-next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Hi! I noticed that POST request without trailing slash seem to be turned into GET requests. I tried to look for a configuration option that could affect this (like `trailingSlash`) but didn't find anything.
![Screenshot 2022-07-12 at 8 11 00](https://user-images.githubusercontent.com/2409276/178416282-ea02b22a-a4dc-49c1-ad98-e2e6b9b1bf70.png)

I tested this also with `^12.2.3-canary.1`

### Expected Behavior

My expectation was that both requests would be POST.

### Link to reproduction

https://github.com/harjis/nextjs-e2e-problem

### To Reproduce

I'm using cypress (10.3.0) to send requests.

```ts
// customers.e2e.ts

describe.only("cy.request()", () => {
  it("passes", () => {
    cy.request({
      method: "POST",
      url: "/api/customers/",
      failOnStatusCode: false,
      body: {
        name: "test",
      },
    }).then((res) => {
      expect(res.status).to.eq(200)
    })

    cy.request({
      method: "POST",
      url: "/api/customers",
      failOnStatusCode: false,
      body: {
        name: "test",
      },
    }).then((res) => {
      expect(res.status).to.eq(200)
    })
  })
})
```

```ts
// src/pages/api/customers/index.ts

import type { NextApiRequest, NextApiResponse } from "next";

const examples = async (req: NextApiRequest, res: NextApiResponse) => {
    console.log(req.method, req.url);
    res.status(200).json([]);
};

export default examples;
```

**Comment by JanKaifer** [comment]
Hey, could you try to reduce the reproduction?
For example, try to reproduce this without cypress. Just with basic `fetch` in the browser etc.
It will make it easier for us to find the root cause.

**Comment by harjis** [comment]
Hi! I think I was able pin point the issue on cypress side but forgot to close this issue. Sorry for the inconvenience!
