### ISSUE TITLE
`blog` example has uneven markdown tags.

### ISSUE THREAD

**Issue by Xithrius** [vercel/next.js#38567]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu, 07 Jul 2022 17:18:13 +0000
Binaries:
  Node: 18.5.0
  npm: 8.13.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 12.2.2
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Which example does this report relate to?

blog

### What browser are you using? (if relevant)

Mozilla Firefox 102.0.1

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

I am sort of a beginner at Javascript/Typescript, so I'm not completely sure where the problem is coming from in terms of templates. If you need any more information, please let me know.

Here is one of the 12 errors:

![image](https://user-images.githubusercontent.com/15021300/178576744-6708277a-d15f-4776-9ac6-f0465ff06375.png)

The example posts within the blog folder contain uneven tags, such as the following:

`[tag].mdx`:
```md
type: tag
title: Tagged Posts
```

vs

`markdown.md`:
```md
title: Markdown Examples
date: 2021/3/19
description: View examples of all possible Markdown options.
tag: web development
author: You
```

### Expected Behavior

I expected the site to start normally without errors.

### To Reproduce

1. `yarn create next-app --example blog blog-example`
2. `cd blog-example`
3. `yarn dev`

**Comment by balazsorban44** [comment]
The blog example renders correctly for me given your reproduction steps, could you link to a reproduction repository where you see the above errors?

![image](https://user-images.githubusercontent.com/18369201/178613572-57275f32-46d8-4783-be72-3c18e1e15f72.png)

**Comment by Xithrius** [comment]
Sorry for the delay, here's a repository that reproduces the problem on my end.

https://github.com/Xithrius/nextjs-blog-test

**Comment by thebergamo** [comment]
With the reproduction repo that you provided, I couldn't see any errors.
Everything loads correctly.

![image](https://user-images.githubusercontent.com/1778730/178723583-83abb25b-4cf3-46c6-bac1-85632d16d5d1.png)

**Comment by Xithrius** [comment]
I still believe it is a problem with my system, so I will close this until I'm able to reproduce on other systems.

**Comment by Xithrius** [comment]
I still believe it is a problem with my system, so I will close this until I'm able to reproduce on other systems.
