### ISSUE TITLE
optimizeCss incorrect behavior in Next.js 12 (Performance decrease)

### ISSUE THREAD

**Issue by aralroca** [vercel/next.js#38561]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
Platform: darwin
Arch: x64
Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
Binaries:
Node: 16.10.0
npm: 7.24.0
Yarn: N/A
pnpm: N/A
Relevant packages:
next: 12.1.6
react: 17.0.2
react-dom: 17.0.2
critters: 0.0.7

### Describe the Bug

Here is the official documentation about how to use a CDN with Asset Prefix:

https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix

However, in Next.js 12 the  `publicPath` of `critters` changed to use `assetPrefix`:

**[v10.2.3](https://github.com/vercel/next.js/blob/eaf74c1cb865c97e3070a8625c2c48b726ec517e/packages/next/next-server/server/render.tsx#-L1142-L1153) vs [v12.2.2](https://github.com/vercel/next.js/blob/d67baa0d1fef8a411679c9b9bdea39cb476ce2d5/packages/next/server/post-process.ts#L218-L228)**
```diff
const Critters = require('critters')
const cssOptimizer = new Critters({
  ssrMode: true,
  reduceInlineStyles: false,
 path: renderOpts.distDir,
- publicPath: '/_next/',
+ publicPath: `${renderOpts.assetPrefix}/_next/`,
  preload: 'media',
  fonts: false,
  ...renderOpts.optimizeCss,
})
```

Now every page request is downloading the CSS from the CDN before calculate the critical CSS to inline, and this has a significant impact on page latency:

```
[32mInlined 5.76 kB (38% of original 15 kB) of https://cdn.vinissimus.com/front/_next/static/css/d9c4e8c06d2c316e.css.
Time 465.162456
```

![image](https://user-images.githubusercontent.com/13313058/178468059-c2064e3f-364b-4f99-a2f7-0733cbf27c62.png)

### Expected Behavior

Even if I use a CDN in my project, to access the CSS you would have to access the `/_next` directly as before, it doesn't make sense to fetch it from a CDN.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-qqua8l?file=next.config.js

### To Reproduce

In the link to the reproduction you need to change `assetPrefix` inside `next.config.js` to a correct CDN (hard to reproduce it without it). Then `yarn build && yarn start` and check the logs and performance.

Without the link to reproduction (all the process):

1. Activate `optimizeCss` on `next.config.js` and add a CDN inside `assetPrefix`:

```js
{
  assetPrefix: cdnUrl,
  experimental: { optimizeCss: true }
}
```
2. `yarn add critters@0.0.7`
3. Add some CSS in some page
4. `yarn build && yarn start`
5.  Check the logs and performance.

**Comment by SukkaW** [comment]
@aralroca Critter is added in Next.js as a Webpack plugin and it would only be executed during the build. It is not used when serving a page.

**Comment by aralroca** [comment]
@SukkaW yes, is executed as Webpack Plugin, but also in runtime ([the Next.js code](https://github.com/vercel/next.js/blob/d67baa0d1fef8a411679c9b9bdea39cb476ce2d5/packages/next/server/post-process.ts)). If I remove the `optimizeCss` (what I have done for the moment), instead of worsening the performance, now it improves it.

![image](https://user-images.githubusercontent.com/13313058/178680986-1b54340c-5f40-489b-98f6-c08defd731b7.png)

**Comment by SukkaW** [comment]
@aralroca Would you mind providing a flamegraph to support your theory though?

```bash
npx 0x -P 'npx autocannon http://localhost:3000 -d 60'  -- node node_modules/.bin/next start
```

**Comment by aralroca** [comment]
@SukkaW I didn't know about flamegraph, although it seems that it doesn't do it very well... (all 0 in the table..)

Next 12 **with**  `experimental.optimizeCss` + CDN:

```bh
Running 60s test @ http://localhost:3000
10 connections


┌─────────┬──────┬──────┬───────┬──────┬──────┬───────┬──────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg  │ Stdev │ Max  │
├─────────┼──────┼──────┼───────┼──────┼──────┼───────┼──────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │
└─────────┴──────┴──────┴───────┴──────┴──────┴───────┴──────┘
┌───────────┬─────┬──────┬─────┬───────┬─────┬───────┬─────┐
│ Stat      │ 1%  │ 2.5% │ 50% │ 97.5% │ Avg │ Stdev │ Min │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Req/Sec   │ 0   │ 0    │ 0   │ 0     │ 0   │ 0     │ 0   │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Bytes/Sec │ 0 B │ 0 B  │ 0 B │ 0 B   │ 0 B │ 0 B   │ 0 B │
└───────────┴─────┴──────┴─────┴───────┴─────┴───────┴─────┘

Req/Bytes counts sampled once per second.
# of samples: 60

146k requests in 60.05s, 0 B read
```

Next 12 **without** `experimental.optimizeCss`:


```bh
Running 60s test @ http://localhost:3000
10 connections


┌─────────┬──────┬──────┬───────┬──────┬──────┬───────┬──────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%  │ Avg  │ Stdev │ Max  │
├─────────┼──────┼──────┼───────┼──────┼──────┼───────┼──────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │ 0 ms │ 0 ms  │ 0 ms │
└─────────┴──────┴──────┴───────┴──────┴──────┴───────┴──────┘
┌───────────┬─────┬──────┬─────┬───────┬─────┬───────┬─────┐
│ Stat      │ 1%  │ 2.5% │ 50% │ 97.5% │ Avg │ Stdev │ Min │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Req/Sec   │ 0   │ 0    │ 0   │ 0     │ 0   │ 0     │ 0   │
├───────────┼─────┼──────┼─────┼───────┼─────┼───────┼─────┤
│ Bytes/Sec │ 0 B │ 0 B  │ 0 B │ 0 B   │ 0 B │ 0 B   │ 0 B │
└───────────┴─────┴──────┴─────┴───────┴─────┴───────┴─────┘

Req/Bytes counts sampled once per second.
# of samples: 60

153k requests in 60.03s, 0 B read
```

The only thing I can see from this graph is that with `optimizeCss`, in one minute you can do fewer requests (146k vs 153k). But I guess it looks like something that didn't run correctly because of the strange results in the table.

**Comment by baraeb92** [comment]
Any updates on this? I think we might experienced the same problem here.

**Comment by fraitag** [comment]
Are you shure? 
I check code of next 12.3.1 and critters and i found place when assetPrefix is replaced. 
https://github.com/GoogleChromeLabs/critters/blob/main/packages/critters/src/index.js#L242
```javascript
    if (normalizedPath.indexOf(pathPrefix) === 0) {
      normalizedPath = normalizedPath
        .substring(pathPrefix.length)
        .replace(/^\//, '');
    }
```
on `normalizedPath` i have `https://cos/_next/static/css/5749cf13b9f9d25a.css`
on `pathPrefix` i have `https://cos/_next/`

on result in normalizedPath i have `static/css/5749cf13b9f9d25a.css`

I think i your case is not problem with using files from cdn becouse is getted from disk.

**Comment by baraeb92** [comment]
We have experienced this as well. 

There is a spike in the CPU usage when using optimizeCSS. As it keep on requesting the CSS file on every load. 

![screen_shot_2022-10-04_at_11.54.09.png](https://user-images.githubusercontent.com/23743497/201454351-e0c7c528-19f9-4c89-a9df-c21915c4d685.png)![screen_shot_2022-10-04_at_13.10.35.png](https://user-images.githubusercontent.com/23743497/201454359-04cc02ff-4bb4-40ca-8483-6f111e30b36e.png)![screen_shot_2022-10-05_at_13.53.11-1.png](https://user-images.githubusercontent.com/23743497/201454362-50cfa578-d8a9-4581-8af0-1caed7cdf145.png)

@SukkaW @janis

**Comment by galaxynova1999** [comment]
facing same issue here

**Comment by SukkaW** [comment]
The issue may be irrelevant now. The `optimizeCss` is always an experimental feature and may cause unexpected or broken application behavior. Also, it is impossible to get critical CSS from Next.js App Router + Stream SSR.

**Comment by leerob** [comment]
https://github.com/vercel/next.js/discussions/59989#discussioncomment-7962270
