### ISSUE TITLE
Rewrite in middleware causes shallow routing to break.

### ISSUE THREAD

**Issue by trm217** [vercel/next.js#38595]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 14.19.1
      npm: 6.14.16
      Yarn: 1.22.18
      pnpm: 7.5.0
    Relevant packages:
      next: 12.2.4-canary2
      eslint-config-next: N/A
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

With version v12.2 of Next.js shallow routing stopped working as expected.
We have a middleware that rewrites the route '/' to '/front' when a JWT with the desired payload is present in the request.
(See routing state directly after page load in the 1st attached screenshot)

After the page has loaded we do a shallow push to '/suche', which is not equal to '/' and therefor the current page should be unloaded and '/suche' should be loaded. However instead of the expected behaviour the asPath is set to '/suche' but the page is not unloaded. (See 3rd attached screenshot to see the router state after we pushed '/suche' to the router)

If however we reload the page, and no middleware rewriting occurs (since we are not on '/' or '/front' but on '/suche' instead) the right page is shown.

Router state after page-load:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/30313631/178735194-8cdac2a6-94d2-427e-b533-e4a5e7ec6c82.png">

Code used to push  '/suche' to the router:
```js
      router.push({ pathname: '/suche', query: newParams }, undefined, {
        shallow: true,
      })
```

Router state after routing has finished:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/30313631/178735736-640eebe2-30f0-4123-96b3-494bbfda2cbd.png">

### Expected Behavior

Expect shallow routing to work like it did pre v12.2 and as stated in the [docs](https://nextjs.org/docs/routing/shallow-routing). 
Meaning: if a shallow route is pushed for a path that is not the current path, the page should be normally routed as described in the [caveats section ](https://nextjs.org/docs/routing/shallow-routing#caveats) of the shallow routing docs.

### Link to reproduction

https://github.com/trm217/nextjs-12.2-shallow-rewrite-issue-reproduction

### To Reproduce

1. Press the toggle auth state button to make the page reload for the authenticated state.
After the reload you will see / has been rewritten to /member.
2. Enter something in the search input and submit.
You will notice that the route has changed, but the shallow route push hasn't actually loaded the '/search' page

**Comment by trm217** [comment]
I believe this issue might somehow be related to the following issues & PRs:
https://github.com/vercel/next.js/issues/38495
https://github.com/vercel/next.js/pull/37716

**Comment by controversial** [comment]
Matchers need to have constant values for static analysis, and template strings can contain non-constant expressions. See #38597

**Comment by trm217** [comment]
@controversial could you provide an example? I am unsure what you‘re referring  about.

**Comment by controversial** [comment]
so sorry—I posted on the wrong issue

**Comment by simontaisne** [comment]
Same issue on my side since version `12.2.2`.

**Comment by bdesimone98** [comment]
Images also break with rewrites that change de locale.

**Comment by DiaaEddinBK** [comment]
More attention is needed

**Comment by DiaaEddinBK** [comment]
Any estimations for this to be resolved ? it is currently a blocker, I had to downgrade to previous versions

**Comment by trm217** [comment]
@timneutkens I saw that with 12.2.2 up router changes where introduced. Any chance you could take a look at the above mentioned issues or point us in a direction on why these issues occure?

**Comment by trm217** [comment]
@DiaaEddinBK We all are blocked by these issues, but there is nothing we can do but wait for them to be resolved (or you could read in to the code and attempt to find the cause yourself). However asking when it will be resolved under every seemingly related issue most likely won't speed the process up.

**Comment by DiaaEddinBK** [comment]
@trm217 It is just very frustrating, it have been there for at least 14 days for a known and widely used framework like next with a hight reputation, this bug should be there in the first place, or at least it should be fixed long time ago, I am not saying that there should be any bug, but this particular, I mean who does not use shallow routing

**Comment by DiaaEddinBK** [comment]
@timneutkens I would like to help if possible, anybody looking for this issue? what can I do to resolve it as soon as possible? I am willing to dig into the code, I am not really sure where to start

**Comment by ijjk** [comment]
> After the page has loaded we do a shallow push to '/suche', which is not equal to '/' and therefor the current page should be unloaded and '/suche' should be loaded. 

This sounds like a bug in client code as `shallow` is being used incorrectly as you noted it should only be used when navigating to the same page. 

With middleware the caveat needs to be expanded that we aren't able to automatically fallback as middleware requires the data route be fetched to know the actual route it resolves to meanwhile `shallow` requires we don't fetch this data route. 

We can definitely update that note in the documentation though.

**Comment by trm217** [comment]
@ijjk Thank you very much for picking up on this issue 🙇🏻‍♂️
 
 > This sounds like a bug in client code as shallow is being used incorrectly as you noted it should only be used when navigating to the same page.
 
 Is see why this usage could be seen as wrong, but considering the docs which states (see below) it seems fine to me.
  
> Shallow routing only works for URL changes in the current page. For example, let's assume we have another page called pages/about.js, and you run this:
> `router.push('/?counter=10', '/about?counter=10', { shallow: true })`
> Since that's a new page, it'll unload the current page, load the new one and wait for data fetching even though we asked to do shallow routing.

The last sentence states that shallow routing to an other path than the current page is possible, but that it will cause to unload the current page and load the new one.

This behaviour also still works after Next.js v12.2.2, if you don't use the middleware.
(In my reproduction, removing the middleware and manually navigating to /members and then entering something in the search-field while cause the page to load /search. Which is the expected behaviour based on the docs)

> With middleware the caveat needs to be expanded that we aren't able to automatically fallback as middleware requires the data route be fetched to know the actual route it resolves to meanwhile shallow requires we don't fetch this data route.
Do I understand this right, that the middleware would generally break the above mentioned behaviour of shallow routing?

**Comment by ijjk** [comment]
Yeah without middleware we are able to tell if a shallow route transition doesn't actually match the current page as we have enough information in the router client side to resolve the page e.g. static rewrites and dynamic routes but with middleware rewrites are fully dynamic and we aren't able to tell if a route will be rewritten without hitting the middleware which occurs on the `_next/data` path.

Since `shallow` explicitly prevents requesting `_next/data` we aren't able to do this additional check that we are able to do without middleware.
