### ISSUE TITLE
Create-next-app error - TypeError: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by MaxMcNally** [vercel/next.js#38617]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Version 103.0.5060.53 (Official Build) (arm64)

### Describe the Bug

When using the default create-next-app, trying to load the home page gets the "Warning: Invalid hook call" and this error - >
**TypeError: Cannot read properties of null (reading 'useContext')**

no code changes after running `yarn create-next-app --typescript` 

Also tried `yarn create-next-app`

### Expected Behavior

App should show default home page

### Link to reproduction

https://github.com/vercel/next.js/tree/canary/packages/create-next-app

### To Reproduce

Run `yarn create-next-app --typescript` or `yarn create-next-app`

Follow prompts, load http://localhost:3000/ in browser

**Comment by MaxMcNally** [comment]
Figured it out. I was running `next dev`, instead of `npm run dev`, not sure why there's a difference, but it works now. Closing

**Comment by balazsorban44** [comment]
If you can run `next dev`, maybe you've installed it as a global dependency :thinking:, and there might be an issue because of a version mismatch or similar. `npm uninstall -g next` might help.
