### ISSUE TITLE
AbortSignal override is not following the spec

### ISSUE THREAD

**Issue by lfre** [vercel/next.js#38658]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Next 12.2+
Node 16+

### Describe the Bug

The edge-runtime primitives override global objects in Node. However, the `AbortSignal` override   [Reference](https://github.com/vercel/next.js/blob/53bc5b3dd326d70da5b8b3d5cd48355b649ffe75/packages/next/compiled/%40edge-runtime/primitives/index.js#L682-L694) does not follow the current spec in Node 16 LTS+ https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal 

It's missing `reason`, `throwIfAborted`, `abort` and `timeout`.

### Expected Behavior

The override matches the current spec *or* a way to disable the override is provided and documented.

### Link to reproduction

https://stackblitz.com/edit/next-js-abortsignal?file=index.js

### To Reproduce

- Start next programmatically
- Log Node's AbortSignal to confirm the `timeout` method is present.
 - The native Node version will have the matching spec (timeout, reason, throwIfAborted).
- After preparing the Next app, the globals are replaced.
 - The AbortSignal.timeout is logged and is missing.

**Comment by balazsorban44** [comment]
I can on MDN that `reason` and `throwIfAborted` are both still experimental, but `abort` and `timeout` seems to be actually missing from our Edge implementation to conform with the spec.

The `edge-runtime` in Next.js relies on the `abort-controller` polyfill:
https://github.com/vercel/edge-runtime/blob/5381871804e3d5c58a61154a82296e0a7096afb9/packages/primitives/src/index.js#L9
Which itself is missing these methods as reported in the [issues](https://github.com/mysticatea/abort-controller/issues).

FWIW, MDN says `reason` and `throwIfAborted` are implemented in Chrome for example, but I get `undefined` for both. But I agree that we should add at least support `abort` and `timeout`.
