### ISSUE TITLE
[Suspense / Navigation] - Navigation does not work when a component suspends indefinitely

### ISSUE THREAD

**Issue by gurkerl83** [vercel/next.js#38665]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
   Platform: darwin
   Arch: x64
   Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
Binaries:
   Node: 16.13.0
   npm: 8.1.0
   Yarn: 3.2.1
   pnpm: N/A
Relevant packages:
   next: 12.2.3-canary.8
   eslint-config-next: N/A
   react: 0.0.0-experimental-02206099a-20220714 (latest experimental react versions)
   react-dom: 0.0.0-experimental-02206099a-20220714 (latest experimental react versions)

### What browser are you using? (if relevant)

Chrome 103

### How are you deploying your application? (if relevant)

next dev, next start, and vercel

### Describe the Bug

Within a Suspense boundary, a Promise gets created and thrown. The Promise does not resolve. During a link-based navigation attempt, the server responds with a new page; the address bar changes, and router-based events get fired, e.g., beforeHistoryChange or routeChangeStart, but the content does not show on the client.

Not sure if the described behavior is intended or a bug. Forcing the component from outside the suspense boundary to re-render in a handler, e.g., beforeHistoryChange or routeChangeStart, does resolve the problem, but this complicates things more.

A question remains, does the render process on the client require all promises to be resolved? Maybe this is a bug because the server responds by providing new content, but the page component does not re-render on its own?

### Expected Behavior

Show a pages correspondent content even when a promise at the previous page does not resolve.

### Link to reproduction

Soon

### To Reproduce

Soon

**Comment by stevo2105** [comment]
did you figure this out? This is resulting in a ton of our pages randomly throwing a 404 :(

**Comment by thienna** [comment]
follow

**Comment by gurkerl83** [comment]
It seems when throwing a promise within a suspense boundary and never resolving it, either
- in a component within _app or 
- in a component using the next layout feature through getLayout
any navigation attempt gets blocked.

Throwing a promise within a suspense boundary within a page, in my case, a dynamic page, and never resolving it works, however.

**Comment by gurkerl83** [comment]
Closing because the issue was resolved on my end.
