### ISSUE TITLE
Google is advising to put all of the gTag code inside the <head> .

### ISSUE THREAD

**Issue by RoyBkker** [vercel/next.js#38685]
Google is advising to put all the `gtag` code inside the <head> element.

Why can't I find nothing about this advice in any of the docs of Next, when using Next/Script?

<img width="721" alt="image" src="https://user-images.githubusercontent.com/10207274/179224323-84e14a15-9459-4b64-b529-5ccf516e2b36.png">

**Comment by balazsorban44** [comment]
You can read more about how to load analytics script in our docs under `next/script`:

https://nextjs.org/docs/basic-features/script#afterinteractive

Next.js will inject the script into `head` for you, and add necessary optimizations to defer loading the analytics script after the page has become interactive to ensure performance.

**Comment by RoyBkker** [comment]
Thanks for answering @balazsorban44 , but I did this, but it's not showing up in my <head> element. 
Code I use:


```
export default function App({ Component, pageProps }: AppProps) {
  const getLayout = Component.getLayout || ((page) => page)

  return (
    <ErrorBoundary
      FallbackComponent={RootErrorFallback}
      onReset={useQueryErrorResetBoundary().reset}
    >
      <Analytics />
      {getLayout(<Component {...pageProps} />)}
    </ErrorBoundary>
  )
}
```



```
const Analytics = () => {
  return (
    <>
      {/* {isProduction && siteMetadata.analytics.plausibleDataDomain && <Plausible />} */}
      {isProduction && <SimpleAnalytics />}
      {isProduction && <GA />}
    </>
  )
}
```


```
const GAScript = () => {
  return (
    <>
      <Script
        strategy="afterInteractive"
        src="https://www.googletagmanager.com/gtag/js?id=G-******"
      />

      <Script strategy="afterInteractive" id="ga-script">
        {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-*****');
        `}
      </Script>
    </>
  )
}
```

Website, which is not showing the script inside the <head> element:
https://nutmaq.com/

**Comment by balazsorban44** [comment]
The issue was closed because it did not follow our bug report template and provided no reproduction either. Accessing your page I can see the script being applied correctly: 
![image](https://user-images.githubusercontent.com/18369201/179247415-43649f7c-8662-406d-8e3b-c9ff9c0f0274.png)

**Comment by RoyBkker** [comment]
Thanks for accessing the page, but it is now in the `<head>` element, because I did **not** use the Script element. 

To reproduce is very easy, use the Script component and see in the HTML that the script tag is not inside the head element.
