### ISSUE TITLE
Docs: i18n-routing has a huge mistake

### ISSUE THREAD

**Issue by B2o5T** [vercel/next.js#38699]
### What is the improvement or update you wish to see?

<img width="689" alt="image" src="https://user-images.githubusercontent.com/7361780/179297829-0ed3fa9b-8757-4783-b8f5-6b699d262931.png">
It's recommends use follow regex:

```js
const PUBLIC_FILE = /\.(.*)$/
``` 

BUT when we have `foo.bar.js` page

```js
/\.(.*)$/.test('/foo.bar')
// true
```

### Is there any context that might help us understand?

Pages that include dots should not be treated as public files, so example need to be changed.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/i18n-routing

**Comment by balazsorban44** [comment]
Hi that is just an example that works for most use cases. There is probably no one-size-fits-all use cases, but you can add your own logic to extend it for your needs. If you know the type of files you have, you could tweak the regex to only match those.
