### ISSUE TITLE
cms-wordpress typescript example

### ISSUE THREAD

**Issue by Josephenoch** [vercel/next.js#38752]
### Describe the feature you'd like to request

I'd like to use a typescript version of the wordpress cms example

### Describe the solution you'd like

A typescript version of the wordpress cms example should be added for ease of development.

### Describe alternatives you've considered

None.

**Comment by isaaclvf** [comment]
Hey @balazsorban44 could you assign me this issue? I would like to help.

**Comment by Josephenoch** [comment]
Hello @isaaclvf  can we work on this together, I'll find a way to reach out to you.
