### ISSUE TITLE
React 17 context value is `undefined` using `getServerSideProps()` in production with Next.js `>=12.1.6`

### ISSUE THREAD

**Issue by FabienMotte** [vercel/next.js#38765]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```sh
$ npx --no-install next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.10.0
      npm: 7.24.0
      Yarn: 1.22.19
      pnpm: 7.2.1
    Relevant packages:
      next: 12.2.3-canary.12
      eslint-config-next: N/A
      react: 17.0.2
      react-dom: 17.0.2
```

#### Description

The [Next.js example](https://github.com/algolia/react-instantsearch/tree/master/examples/next) of the React InstantSearch repository is currently using Next.js `12.1.5` and React 17 without any issues.

But upgrading to any version above (starting at Next.js `12.1.6`) results in an error 500 on the client side when serving the `production` build (it works fine in `development` env).
On the server side, the error is the following:
```js
TypeError: Cannot read property 'store' of undefined
    at Connector.getProvidedProps (.../next/node_modules/react-instantsearch-core/dist/cjs/core/createConnector.js:206:63)
    at new AlgoliaConfigure(Configure) (.../next/node_modules/react-instantsearch-core/dist/cjs/core/createConnector.js:86:32)
    at d (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
    at bb (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at execute (.../next/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js:170:32)
    at findResultsState (.../next/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js:205:10)
    at getServerSideProps (.../next/.next/server/pages/index.js:284:75)
```

#### Error details

In the example, we use the method [`getServerSideProps()`](https://github.com/algolia/react-instantsearch/blob/master/examples/next/pages/index.js#L65-L78) to find the results state and pre-render the application.

It seems to be related to a React context issue, we use a [context](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/core/createConnector.tsx#L375) to provide the InstantSearch `store` to a `Connector` but in this case, the context value is `undefined`.

You can find the [related issue on the React InstantSearch repository](https://github.com/algolia/react-instantsearch/issues/3544).

#### Potential cause

I tried to look into the Next.js codebase to see what changes could cause this issue between Next.js `12.1.5` and `12.1.6`, I found that this commit may have introduced the error, especially this `require()`: https://github.com/vercel/next.js/pull/36552/files#diff-b7046c7df36a10b027725f1b38bab0c6bb3bee63e2df718c8dd6d1233e26e85aR46

If I delete all occurrences of this `require('react-dom/server.browser')` or use `require('react-dom/server')`, everything works fine.

### Expected Behavior

The React context value should not be `undefined` as it does with Next.js `12.1.5` or earlier.

### Link to reproduction

https://codesandbox.io/s/next-ris-context-issue-zldik7?file=/pages/index.js

### To Reproduce

1. Clone this example [next example](https://github.com/algolia/react-instantsearch/tree/master/examples/next)
2. Update the Next.js version in `package.json` to `>=12.1.6`.
3. Run `yarn && yarn build`
4. Run `yarn start`
5. Open http://localhost:3000
6. See error 500 in browser and error in the console

**Comment by marcusnunes** [comment]
Following the thread because I have a similar error using `getServerSideProps`.

In my case, when I run `yarn build && yarn start` for the second time, when browsing any page, a 404 error occurs calling `/_next/data`, and instead of reloading the page like `next 12.1.6` does, it throws an error `client -side exception has occurred` for the user because it cannot read a property of undefined.

I'm skipping the 12.2 version for now.

**Comment by huozhi** [comment]
@marcusnunes is your case also related to `react-instantsearch` or sth else? do you have any reproduction for your case?
