### ISSUE TITLE
const reassignment does not throw an error in some cases

### ISSUE THREAD

**Issue by yarikpetrenko** [vercel/next.js#38767]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 103.0.5060.114 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

next start, codesandbox

### Describe the Bug

When you declare constant inside the arrow function and then reassign it, next does not throw an error. But when you create not ES6 function it's works as expected. If you do in component on top level works as expected.

When you using clear react not next it's works as expected. Also i tried it on:
 "next": "^11.0.0",
 "react": "17.0.2", 

on this version it's works as expected.

### Expected Behavior

Throw an const assignment error 

### Link to reproduction

https://codesandbox.io/s/determined-goldstine-s0ohlj?file=/pages/index.js

### To Reproduce

1. Create arrow function where you declare const and then reassign it.
2. Call function for example on button click

**Comment by JanKaifer** [comment]
I might be wrong but that is expected.

eslint is failing which is the main thing.
We are probably transpiling `const` and having a custom check in runtime would be too slow.
