### ISSUE TITLE
12.2 breaks URL hashes with a "?"

### ISSUE THREAD

**Issue by colinclerk** [vercel/next.js#38783]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.15.0
      npm: 8.12.0
      Yarn: 1.22.17
      pnpm: 6.24.4
    Relevant packages:
      next: 12.2.3-canary.14
      eslint-config-next: N/A
      react: 18.1.0
      react-dom: 18.1.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Visit [https://vercel.com/blog#asdf?](https://vercel.com/blog#asdf?)
Notice the URL changes to [https://vercel.com/blog#asdf#asdf#asdf#asdf#asdf#asdf#asdf#asdf#asdf?](https://vercel.com/blog#asdf#asdf#asdf#asdf#asdf#asdf#asdf#asdf#asdf?)
Click refresh and it does it again

### Expected Behavior

The hash part of the URL should not change on page load

### Link to reproduction

[https://vercel.com/blog#asdf?](https://vercel.com/blog#asdf?)

### To Reproduce

Unfortunately, we're not sure.

Our closed-source repo exhibits the behavior on canary, and we noticed vercel.com and nextjs.org exhibit the behavior as well.

However, we have not been able to recreate with a fresh canary repo, and we're not sure exactly what triggers the behavior on our closed-source repo.

We have reverted to 12.1.6 where the behavior is not present.

**Comment by colinclerk** [comment]
My best guess so far is this has to do with `initialCanonicalUrl` being set from the server, where there is no hash part:
https://github.com/vercel/next.js/blob/7280c3ced186bb9a7ae3d7012613ef93f20b0fa9/packages/next/server/app-render.tsx#L842-L843

Then it's this effect actually triggering the replaceState's:
https://github.com/vercel/next.js/blob/c1ce6bfe1b32ba260c250052176fb5b2cf31dab6/packages/next/client/components/app-router.client.tsx#L258

**Comment by FelixStridsbergPaf** [comment]
We also experience this, the same thing happens with `#?` inside `href` of a `next/link` and if you `router.push` such url.

Did some debugging and think the main issue is here:
https://github.com/vercel/next.js/blob/20b63e13ab2631d6043277895d373aa31a1b327c/packages/next/shared/lib/router/utils/parse-path.ts

```ts
console.log(parsePath('/test#hash?param=1'));
> {
  "pathname": "/test#hash",
  "query": "#hash",
  "hash": "#hash?param=1"
} 
```

Then those are used for example here:
https://github.com/vercel/next.js/blob/a4668f29b6d55c39eef3e4c727c748b28b697a0b/packages/next/shared/lib/router/utils/add-path-prefix.ts#L13
Resulting in:
```
/test#hash#hash#hash?param=1
```

And the `addPathPrefix` is called multiple time causing the url to grow bigger for every call since:
```ts
console.log(parsePath('/test#hash#hash#hash?param=1'));
> {
  "pathname": "/test#hash#hash#hash",
  "query": "#hash#hash#hash",
  "hash": "#hash#hash#hash?param=1"
} 
```

**Comment by colinclerk** [comment]
Yea, that looks like it. If you hit a URL with both query and hash, it works as expected:
https://vercel.com/blog?foo=bar#hash?test

Here's a proposed strategy to fix:
https://github.com/vercel/next.js/compare/canary...colinclerk:next.js:patch-1

@javivelasco any concern with this?  Another strategy is to leverage URL with a dummy domain, e.g `new URL(path, "https://example.com")`.

Unfortunately I won't be able to get a complete PR up for a few days, maybe next week. If anyone wants to run with this, please do!
