### ISSUE TITLE
Images imported in `getStaticProps` do not get bundled

### ISSUE THREAD

**Issue by Manc** [vercel/next.js#38791]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: 6.11.0
    Relevant packages:
      next: 12.2.3-canary.14
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

next dev, next start

### Describe the Bug

An image that is imported and its variable is then only used in `getStaticProps` to be passed down as property to the `NextPage` component, will not be bundled, despite the content and passed-down values looking good. A request by the client then results in an HTTP error 404.

If the same variable is (also) used in the `NextPage` component directly, the file will be bundled.

Screenshot:
<img width="556" alt="Screenshot" src="https://user-images.githubusercontent.com/811578/179740938-902176e6-fb8e-4995-90b3-e5febd1f7a2c.png">

This has already been reported #36591, but in a slightly different context, and was therefore not followed up. It turns out it doesn't matter whether the import is dynamic or not.

### Expected Behavior

Imported images should be bundled whether or not the variable itself is only being used in `getStaticProps`.

### Link to reproduction

https://codesandbox.io/s/next-import-getstaticprops-qxtm6w?file=/pages/index.tsx

### To Reproduce

- Start reproduction project in CodeSandbox.
- Open root page in browser.
- You will find:
  - Image "a" (pink) is displayed correctly.
  - Image "b" (blue) is missing, despite all image properties being available (see JSON output).

**Comment by Manc** [comment]
May I add, although it does feel like a bug, I have found a simple workaround for my case: Instead of passing the image object from the image import in `getStaticProps` to the page props directly, I now just pass the fact that I want to use that static image in the page and then use the import variable in the page component.

So at least for me this is no longer a priority and if anybody else comes across that issue, consider this approach.

**Comment by JanKaifer** [comment]
It works now.
