### ISSUE TITLE
Static page with rewrite not getting passed page props for second rerender client side

### ISSUE THREAD

**Issue by wweaver** [vercel/next.js#38794]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 14.19.1
      npm: 8.10.0
      Yarn: 1.22.19
      pnpm: 6.32.11
    Relevant packages:
      next: 12.2.3-canary.14
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 103.0.5060.114

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

When using SSG page and an `afterFiles` rewrite on vercel infrastructure only the page initially is passed the page props from getStaticProps, but a client side rerender no longer is passed the page props.

### Expected Behavior

The page props should be passed on every page re-render

### Link to reproduction

https://github.com/wweaver/next-playground

### To Reproduce

* https://next-playground-git-main-wweaver.vercel.app/river/
* https://github.com/wweaver/next-playground

1. Create an SSG page with getStaticProps that passes page props
2. Add an afterFiles rewrite that will reroute to the SSG page

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.2.4-canary.7` of Next.js, please update and give it a try!

**Comment by wweaver** [comment]
Updating the demo app I have it seems to be fixed. Thanks!

https://next-playground-qad5m435m-wweaver.vercel.app/hub/river/

I'll try with our main code base once it's released.

**Comment by wweaver** [comment]
@ijjk I added https://github.com/vercel/next.js/issues/39669 as this issue still exists for us on our main site. I added one more  piece to the puzzle in the demo app I created.
