### ISSUE TITLE
with-dynamic-import example and related docs to be updated to use Typescript

### ISSUE THREAD

**Issue by timothyhague** [vercel/next.js#38806]
### Describe the feature you'd like to request

Hello,

The `with-dynamic-import` example, as well as the example in the docs:
https://nextjs.org/docs/advanced-features/dynamic-import
they're both written in Javascript, rather than Typescript.

However, when I update to React 18, modifying to follow the example, the dynamic import Typescript checks fail.

I've stripped everything back, so I have this:

An AboutSection component, like:

```
export default function AboutSection() {
  return <div>This is the about section</div>;
}
```

and then a parent component, like:

```
const AboutSection = dynamic(() => import('./AboutSection'), {
  suspense: true,
});

export default function ParentComponent() {
  return (
    <Suspense fallback={<LoadingState />}>
        <AboutSection />
     </Suspense>
  );
}
```

Where I use `<AboutSection />` in the ParentComponent, I get this TypeScript error:

```
  'AboutSection' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<{}, any, any>' is not a valid JSX element. ts(2786)
```

When I drill down in to the types defined for the `dynamic` function, I find:

`export default function dynamic<P = {}>(dynamicOptions: DynamicOptions<P> | Loader<P>, options?: DynamicOptions<P>): React.ComponentType<P>;`

I see that a `React.ComponentType` is being returned.

Would be very useful to update the docs to show how to please Typescript in this case. 

Digging in to the React type definitions, it's really not clear:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts

### Describe the solution you'd like

Clear instructions on how to please TypeScript when dynamically importing a component with `next/dynamic`.

### Describe alternatives you've considered

Adding types to the the return value of the AboutSection. Adding types to the dynamic function call. 

No combination of types on these components have satisfied TypeScript.

The only way to satisfy Typescript is to modify the dynamic function to return a ReactNode, like:
`export default function dynamic<P = {}>(dynamicOptions: DynamicOptions<P> | Loader<P>, options?: DynamicOptions<P>): React.ReactNode;`

but, obviously, this is not the right solution.

**Comment by balazsorban44** [comment]
Make sure you also update `@types/react` in your project so it's not outdated. The following gives me no errors:

```tsx
import dynamic from "next/dynamic"
import { Suspense } from "react"

const AboutSection = dynamic(() => import("./AboutSection"), {
  suspense: true,
})

export default function ParentComponent() {
  return (
    <Suspense fallback={null}>
      <AboutSection />
    </Suspense>
  )
}
```

```tsx
export default function AboutSection() {
  return <div>Hi</div>
}
```

I opened a PR to update the example.

Otherwise we would need a reproduction to be able to help you.
