### ISSUE TITLE
Docs: legacyBehavior

### ISSUE THREAD

**Issue by mattbrannon** [vercel/next.js#38819]
### What is the improvement or update you wish to see?

I would like to see some explanation of what `legacyBehavior` means and why I'm suddenly getting warnings in my console about it. 

### Is there any context that might help us understand?

My console is filled with messages like `"onClick" was passed to <Link> with href of /blog but "legacyBehavior" was set. The legacy behavior requires onClick be set on the child of next/link`

The [documentation](https://nextjs.org/docs/api-reference/next/link) makes no mention of `legacyBehavior`. The only official mention of it is a link to a PR near the bottom of the page in this [blog post](https://nextjs.org/blog/next-12-2#other-improvements). I feel like if you're going to litter my console with warning messages, there should be some official documentation explaining what the warning message actually means. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/link

**Comment by balazsorban44** [comment]
As mentioned, this is currently an `experimental` feature, and such is not currently documented.

https://github.com/vercel/next.js/pull/36436 is the best documentation right now. It will be documented when it gets out of experimental.

**Comment by rjoonas** [comment]
@mattbrannon What is the specific `<Link>` in the create-next-app template that throws this error?

It looks like https://github.com/vercel/next.js/pull/36436 added these new warnings about `onClick` and `onMouseEnter` handlers passed directly to `<Link>`. The error message is trying to say that these props will be supported directly on `<Link>` in an upcoming release but unless you enable a feature flag your mouse event handlers are in the wrong place.

I ran into these errors when using next with chakra-ui, with a component hierarchy like:

```jsx
<chakra.Tooltip>
  <next.Link href="...">
    ...
  </next.Link>
</chakra.Tooltip>
```

Even though I hadn't passed mouse event handlers in my own code, Chakra injects them down to `<Link>` to show a tooltip on hover. I was able to fix the error by either enabling the `newNextLinkBehavior` feature flag or by adding an intermediate container for Chakra's mouse handlers:

```jsx
<chakra.Tooltip>
  <span>
    <next.Link href="...">
      ...
    </next.Link>
  </span>
</chakra.Tooltip>
```

Over on Chakra's issue tracker there's also a similar solution where you wrap next.Link with chakra.Link. https://github.com/chakra-ui/chakra-ui/issues/6105#issuecomment-1143184487

**Comment by mattbrannon** [comment]
> Even though I hadn't passed mouse event handlers in my own code, Chakra injects them down to `<Link>` to show a tooltip on hover. I was able to fix the error by either enabling the `newNextLinkBehavior` feature flag or by adding an intermediate container for Chakra's mouse handlers:

That's what I did as well. Ultimately it was easier to just enable `newNextLinkBehavior` and run the codemod `npx @next/codemod new-link` from #36436.

**Comment by JuanSystems** [comment]
amigo yo solucione el problema de esta forma:

```
<div className={`links ${clicked ? "active" : ""}`}>
            <Link href="/">
              <a onClick={handleClick}> Home</a>
            </Link>
            <Link href="/">
              <a onClick={handleClick}> Shop</a>
            </Link>
            <Link href="/">
              <a onClick={handleClick}> Blog</a>
            </Link>
          </div>
```
Espero que te ayude.
