### ISSUE TITLE
`className` prop is not reflecting in `next/future/image` when using `styled-jsx`

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [vercel/next.js#38822]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 14.16.0
      npm: 7.19.1
      Yarn: 1.22.0
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When using `Image` component from `next/future/image` and passing a `className` prop to it. The name is being added to the `image` element but the style is not reflecting. But, the same works if we are using `css-modules` or any other framework

Examples
Next + Styled-JSX https://codesandbox.io/s/next-future-image-styled-jsx-ig57fm
the `about-image2` that is passed to the `Image` component doesn't reflect 

Next + CSSModules https://codesandbox.io/s/next-future-image-css-modules-9h8qqz
Works as expected.

Is it is something to do with the build time name changes from `next` for `styled-jsx` like appending `.jsx-1834` in-front of the className. Is it under the scope to fix this, or switching to other style frameworks is the solution ?

<img width="1146" alt="Screenshot 2022-07-20 at 1 46 50 PM" src="https://user-images.githubusercontent.com/11075561/179932760-5506548c-1daf-470e-89c1-c129d1f42a84.png">
<img width="1158" alt="Screenshot 2022-07-20 at 1 46 38 PM" src="https://user-images.githubusercontent.com/11075561/179932784-756df884-e95e-47f0-b73d-1f42792f21dd.png">

### Expected Behavior

The `className` from `Image` component to behave the same in `styled-jsx` as well as other style frameworks

### Link to reproduction

https://codesandbox.io/s/next-future-image-styled-jsx-ig57fm

### To Reproduce

```jsx
import React from "react";
import Image from "next/future/image";
import Head from "next/head";

const Home = (props) => {
  return (
    <>
      <div className="about-container">
        <Head>
          <title>About - New Project3</title>
          <meta property="og:title" content="About - New Project3" />
        </Head>
        <Image
          src="/playground_assets/kitten.png"
          alt="image"
          className="about-image2"
          width={400}
          height={400}
        />
      </div>
      <style jsx>
        {`
          .about-container {
            width: 100%;
            display: flex;
            overflow: auto;
            min-height: 100vh;
            align-items: flex-start;
            flex-direction: column;
            justify-content: flex-start;
          }

          .about-image2 {
            width: 400px;
            height: 400px;
            object-fit: contain;
          }
        `}
      </style>
    </>
  );
};

export default Home;

```

**Comment by styfle** [comment]
This is expected for `styled-jsx` because the style is scoped to the current component, so you can't pass styles to a child component. Its the same for all components (not just `next/future/image`).

CSS Modules are preferable for this use case.
