### ISSUE TITLE
Middleware will result in server-side rendered pages to be prefetched.

### ISSUE THREAD

**Issue by iljamulders** [vercel/next.js#38845]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.5.0
      npm: 8.12.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.3-canary.14
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Version 103.0.5060.134 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

Adding a middleware.ts will result in server-side rendered pages to be prefetched.
```ts
import { NextRequest } from 'next/server'

export function middleware(request: NextRequest) {}
```

All `<Link>` in the viewport to an SSR page are prefetched, but according to the documentation, this should not happen.

https://nextjs.org/docs/routing/introduction#linking-between-pages

> Any <Link /> in the viewport (initially or through scroll) will be prefetched by default (including the corresponding data) for pages using [Static Generation](https://nextjs.org/docs/basic-features/data-fetching/get-static-props). The corresponding data for [server-rendered](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props) routes is not prefetched.

### Expected Behavior

SSR pages should not be prefetched when a middleware.ts is added.

### Link to reproduction

https://github.com/iljamulders/nextjs-middleware-ssp

### To Reproduce

1. Checkout https://github.com/iljamulders/nextjs-middleware-ssp
2. run `yarn install`
3. run `yarn build`
4. run `yarn start`
5. go to http://localhost:3000/
6. Check the network tab of your browsers
![Screenshot 2022-07-20 at 18 39 45](https://user-images.githubusercontent.com/6195121/180041142-a5d94fbb-5c8d-4106-bea4-5a7fc8872cde.png)

**Comment by danielbeardsley** [comment]
Deploying a very tiny middleware (added one header) ended up increasing backend requests by 5x and adding unnecessary network traffic and load to our pages.

Is there any way to deploy middleware without having it run on the edge? Though I don't know if that's the problem.

**Comment by ijjk** [comment]
Hi, this has been updated in the latest canary of Next.js, please update and give it a try!
