### ISSUE TITLE
Permitted TypeScript moduleResolution field is silently ignored during build step

### ISSUE THREAD

**Issue by nopelluhh** [vercel/next.js#38854]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: linux
  Arch: x64
  Version: Ubuntu 20.04.0 LTS Wed Jul 20 2022 15:07:23 GMT-0700 (Pacific Daylight Time)
Binaries:
  Node: 16.14.2
  npm: 7.17.0
  Yarn: 1.22.10
  pnpm: N/A
Relevant packages:
  next: 12.2.3-canary.14
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.2.3-canary.14", newest: "12.2.3-canary.15".
    Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
    Read more - https://nextjs.org/docs/messages/opening-an-issue

NOTE: I was unable to install 12.2.3-canary.15, it doesn't seem to exist on NPM at the time of creating this issue

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

Running `next build` ignores the `moduleResolution` field if it contains a value other than `nodejs`, even when using a permitted type as outlined here:

https://github.com/vercel/next.js/blob/d895a50abbc8f91726daa2d7ebc22c58f58aabbb/packages/next/lib/typescript/writeConfigurationDefaults.ts#L59-L61

This means that builds that pass direct type checking via `tsc` will fail to build if `node12` or `nodenext` are used.

I did a bit of digging and it appears this is because while [writeConfigurationDefaults](https://github.com/vercel/next.js/blob/e57e2753f12076a99173a80787e6d1a2cdb3a0fc/packages/next/lib/verifyTypeScriptSetup.ts#L71) allows  `parsedValues` options above, `getRequiredConfiguration` only returns `parsedValue` and which overrides the user's config:

https://github.com/vercel/next.js/blob/0d80b113a3d17ba86b273c8d7cef7a7a20cde95b/packages/next/lib/typescript/runTypeCheck.ts#L39-L47

If this is not the expected behavior I'm happy to attempt a PR to fix, but wanted to confirm before giving it a shot.

### Expected Behavior

Running `yarn build` should respect the `moduleResolution` field when it contains a permitted value other than `nodejs`.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-wtfonr

### To Reproduce

Run `yarn build` (and also observe that `yarn tsc` does not error)

**Comment by harrysolovay** [comment]
I'm also running into this issue.

I have my tsconfig's `moduleResolution` set to `"NodeNext"` so that I can use non-root exports.

For instance:

```ts
import * as M from "capi/frame_metadata";
// ...
```

The following error occurs upon running `next build`.

```
./components/layout/sidebar/ExtrinsicsList.tsx:1:20
Type error: Cannot find module 'capi/frame_metadata' or its corresponding type declarations.

> 1 | import * as M from "capi/frame_metadata";
    |                    ^
  2 | import classNames from "classnames";
  3 | import * as H from "hooks";
  4 | import Link from "next/link";
```

I'd also recommend that setting the tsconfig field auto-disable the `import/no-unresolved` lint, which does not account for such `NodeNext` import path specifiers.

**Comment by karl-kallavus** [comment]
Same. I'm also running into this problem. 

`package.json `
```
"exports": {
    ".": {
      "import": "./esm/index.js",
      "require": "./script/index.js",
      "types": "./types/index.d.ts"
    },
    "./test-util": {
      "import": "./esm/test-util/test.js",
      "require": "./script/test-util/test.js",
      "types": "./types/test-util/test.d.ts"
 },
 ```
 
 And same error occurs upon running next build.
 
 Seems like quite a **big problem that type resolution of `package.json` exports is unsupported**.

**Comment by nopelluhh** [comment]
hey @JanKaifer, i've verified that this is still a problem with the latest canary.

new sandbox: https://stackblitz.com/edit/vercel-next-js-cpvefa

repro steps:
1. observe that `npx tsc` succeeds
2. observe that `npm run build` fails type checking (it also seems oddly slow given the project size but that's unrelated)

**Comment by qrohlf** [comment]
I have spun up a new PR that aims to resolve this issue: https://github.com/vercel/next.js/pull/45670
