### ISSUE TITLE
`Response` in edge runtime is logged as an empty object `{}`

### ISSUE THREAD

**Issue by nm2501** [vercel/next.js#38866]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.2.3-canary.15
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When using `fetch()` from edge middleware to an API in the same next app (`/api/hello`) in my example, the target API _is_ invoked and returns a JSON response but the result in the middleware is always an empty object.
```
const fetchResult = await fetch(req.nextUrl.origin + "/api/hello", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
console.log("result: ", typeof fetchResult, Object.keys(fetchResult), fetchResult);
const payload = fetchResult.json();
console.log("payload: ", payload, Object.keys(payload));
```
always yields:
```
hello was invoked!
result:  object [] {}
payload:  {} []
```

For reference the `/api/hello` handler is:
```
export default function handler(req, res) {
  console.log('hello was invoked!');
  res.status(200).json({ name: 'John Doe' })
}
```

A minimal repo (based on `yarn create next-app`) is here: https://github.com/nm2501/next-middleware-fetch

### Expected Behavior

I would expect `fetch` to return a real `Response` from which I can obtain the `/api/hello` response data.

### Link to reproduction

https://github.com/nm2501/next-middleware-fetch

### To Reproduce

`git clone https://github.com/nm2501/next-middleware-fetch`
`cd next-middleware-fetch`
`yarn install`
`yarn dev`
Open http://localhost:3000 in a browser.
Check the terminal where you ran `yarn dev`.

**Comment by balazsorban44** [comment]
You forgot to `await` a promise here: https://github.com/nm2501/next-middleware-fetch/blob/041a6999043090879d4ff0320fda558e8fbab862/middleware.js#L21

Apart from that, the only thing that looks wrong is when you `console.log` `fetchResult`. 

We are investigating that, thanks. :+1:
