### ISSUE TITLE
Needs CSS fix for emojis on docs page

### ISSUE THREAD

**Issue by imhalid** [vercel/next.js#38901]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Describe the Bug

Emojis appear cut off and it looks like there is a problem with the frames.

![test](https://user-images.githubusercontent.com/40598819/180392874-d3d48ae5-6d0e-4490-aaf5-cf5ba03e0dd8.png)

### Expected Behavior

![Ekran Resmi 2022-07-22 10 48 54](https://user-images.githubusercontent.com/40598819/180393072-52fdce45-6717-4c53-a9d8-51c5c6b13258.png)

### Link

https://nextjs.org/docs

### To Reproduce

These properties under the `.docs img` class need to be deleted for it to appear correctly

`background: #fafafa;`
`border: 1px solid#eaeaea;`
`border-radius: 3px;`

**Comment by ijjk** [comment]
Thanks for sharing this, the styles should be corrected now!
