### ISSUE TITLE
Middleware affecting getInitialProps after 12.2.0

### ISSUE THREAD

**Issue by joaogarin** [vercel/next.js#38918]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022
    Binaries:
      Node: 14.17.5
      npm: 6.14.14
      Yarn: 1.22.17
      pnpm: 6.32.1
    Relevant packages:
      next: 12.2.3-canary.17
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

self hosted (locally) 

### Describe the Bug

hello,

I have an app that has a _app.js with a `getInitialProps`, but also some other pages that still have `getInitialProps` implemented. 

After updating to Next.js 12.2 we are noticing that the presence of the middleware file makes it so that these `getInitialProps` run both on client and server always (first the sever then the client), removing the middleware file restores the old behaviour where the `getInitialProps` runs only on the client when doing a client transition and on the server when doing a server reload 

this feels a bit at odds with the documentation on `getInitialProps` https://nextjs.org/docs/api-reference/data-fetching/get-initial-props  "For the initial page load, `getInitialProps` will run on the server only. `getInitialProps` will then run on the client when navigating to a different route via the next/link component or by using next/router" -> The page in question does not implement `getServersideProps` (but I do have a `getInitialProps` in `_app.js` as described above)

My question is : Is this intentional behaviour? that adding a middleware affects how the `getInitialProps` function behaves?  And was this meant to be introduced in 12.2? I understand that middleware was not stable before and so there are changes to it that were to be expected but since this behaviour is not documented I was wondering if this is indeed intentional or not.

Here are 2 videos of a bare bones next app demonstrating the issue : 

#### Without any middleware

Without any middleware the behaviour we can see is that `getInitialProps` works as documented, when doing a server load it runs on th server and when doing a client transition it runs on the client 

https://user-images.githubusercontent.com/2866604/180443142-d664c9eb-490a-4319-b185-02ffefff1ebe.mp4

#### With middleware

With middlware we can see that for the same app the behaviour changes, and it now runs always on server and client even when doing client transitions (where previously it would only run on the client)

https://user-images.githubusercontent.com/2866604/180443276-b6176885-0fab-43e5-95a0-35b8e413346e.mp4

Here is the repo reproducing the problem 

https://github.com/joaogarin/middleware-gip

Thank you! 

### Expected Behavior

I would expect the `getInitialProps`to run as documented : If doing a client transition it runs in the client otherwise if doing a full load it runs on the server, but not both.

### Link to reproduction

https://github.com/joaogarin/middleware-gip

### To Reproduce

`yarn install && yarn dev` - see the logs n the console. even if doing a client side transition the `getInitialProps` is being called twice both on the server and client

This also happens in a build application (with yarn build)

**Comment by danielschleindlsperger** [comment]
It seems like Next will trigger a "data request" in addition to the client side execution. It's my understanding that this should only happen for `getServerSideProps` functions, is that correct?

I have a page `/foo/[id].js` and a request to `/foo/bar` will trigger a data request to `http://localhost:3000/_next/data/development/foo/bar.json?id=bar`. Interestingly, this will actually return the rendered HTML page, which is then discarded, as code in `getInitialProps` runs in the client anyway.

If I add an artificial delay to the server version of `getInitialProps`, the transition in the client is also delayed. If I add it to both versions, I have twice the delay. It seems like the client waits for the server request to finish, and then runs `getInitialProps` in the client

**Comment by mmmulani** [comment]
I updated to 12.2.6-canary.6 and tested this out in development and still running into the same issue. @ijjk should this be re-opened?

Namely:
- have a page like `/foo/[id].tsx` with `getInitialProps`
- when navigating from `/index` to `/foo/test`, a request is made to `http://localhost:3000/_next/data/development/foo/test.json?id=test`

though my understanding is that this should not happen.

**Comment by ijjk** [comment]
On navigation this is still expected the above fix was to only change the prefetching behavior. 

When middleware is present we still need to fetch `_next/data` as we need to resolve any rewrites/redirects from middleware which could cause the page to navigate elsewhere.

**Comment by mmmulani** [comment]
agh that makes sense. Is there anyway to move the rewrite/redirect resolving logic from middleware to the client? We would really like to avoid the delay in navigating from hitting the server.

If not, is there a way from context in `getInitialProps` to determine if it is a `_next/data` client side fetch, where SSR is not critical?

**Comment by ijjk** [comment]
If you want to avoid the `_next/data` fetch you can opt the page out from matching middleware with the `matcher` config https://nextjs.org/docs/advanced-features/middleware#matcher a negative match can be used to include everything except certain patterns e.g. `/:path((?!about).*)` would exclude `/about`

**Comment by mmmulani** [comment]
Ahhh yeah, in our case we're using middleware for a multi-tenant domain solution. That is, we map custom user domains to `pages/_sites/[domain]/<path>`. So it seems like a matcher solution won't work for us?

In Next 12.0.x though, I don't believe we were running into this issue, I guess the Middleware change includes this different behaviour?

What sort of workarounds are possible for us? Is it possible to determine in `getInitialProps` if this is a middleware routing request and return early? (to navigate faster)

**Comment by ijjk** [comment]
If the multi-tenant domain solution is the only reason middleware is being leveraged and you want to avoid invoking middleware you could switch to `has` rewrites ([related documentation](https://nextjs.org/docs/api-reference/next.config.js/rewrites)) which can achieve the same thing without needing to invoke middleware on transitions.

**Comment by mmmulani** [comment]
ahh yeah looking into it, that might work for us though would require some migration.

About the json requests from `/_next/data` though, why do they need to run `getInitialProps` and actually render the page? It seems like the middleware data is just found from reading the headers? https://github.com/vercel/next.js/blob/f7df3fc1587089f25de8f9cba41ce436059e0bbe/packages/next/shared/lib/router/router.ts#L347-L352

but also, what's the point of returning this html if it will all be dropped when there's a client side navigation?

**Comment by ijjk** [comment]
It needs to actually render the page since it's meant to prevent multiple round trips to the server and client so all resolving can be done on the server and then return the result so if the middleware rewrites to a `getServerSideProps` or `getStaticProps` the data for the rewritten page can be returned in the same response.

**Comment by mmmulani** [comment]
ahhh fair enough, that all makes sense then, thanks for taking the time to answer my questions!

our solution for now will be to do something like `if (!context.req || context.asPath?.startsWith('/_next/data/')) { ... }` in `getInitialProps` to try to short-circuit this. Possibly in the future might try doing something with a shallow `router.push` and replicate our middleware logic to the client, though that also seems tough.

**Comment by TkDodo** [comment]
I did take me quite some time to investigate this behaviour today. Can we at least document that `getInitialProps` will run on the server for every request if you also have a middleware?

It's quite interesting to see a request being made from the browser to a `.json` file which then responds with the fully server-rendered html page. Is that really necessary ? What is happening with that information on the client?
