### ISSUE TITLE
Unable to use the middleware feature with React 18 & output:standalone feature

### ISSUE THREAD

**Issue by webda2l** [vercel/next.js#38934]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022
    Binaries:
      Node: 17.8.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

standalone / server.js / docker

### Describe the Bug

It's currently impossible to use the middleware feature with React18 and the output:standalone feature.
Trying to force the `experimental.runtime:nodejs` has no effect.

The simplest middleware, like a more complicated, result to the same issue.

```
import { NextResponse } from 'next/server'

export const middleware = async (request) => {
  console.log(request)
}
```

Real example:
```
/* eslint-disable @next/next/no-server-import-in-page */
import type { NextRequest } from 'next/server'
import { NextResponse } from 'next/server'

import { COOKIE_JWT_HP } from '@/services/auth'
import { routes } from '@/utils/route'

export const middleware = async (request: NextRequest) => {
  if (request.nextUrl.pathname === '/') {
    if (!request.cookies.get(COOKIE_JWT_HP)) {
      return
    }

    const url = request.nextUrl.clone()
    url.pathname = routes.dashboard
    return NextResponse.redirect(url)
  }
}

export const config = {
  matcher: ['/'],
}
```

The error:
```
Error: Cannot find module 'next/dist/compiled/@edge-runtime/primitives/console'
Require stack:
- /app/node_modules/next/dist/compiled/edge-runtime/index.js
- /app/node_modules/next/dist/server/web/sandbox/context.js
- /app/node_modules/next/dist/server/web/sandbox/sandbox.js
- /app/node_modules/next/dist/server/web/sandbox/index.js
- /app/node_modules/next/dist/server/next-server.js
- /app/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at addPrimitives (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:983)
    at Object.extend (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:388)
    at new VM (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:7886)
    at new EdgeVM (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:348)
    at new EdgeRuntime (file:///app/node_modules/next/dist/compiled/edge-runtime/index.js:1:8590)
    at createModuleContext (file:///app/node_modules/next/dist/server/web/sandbox/context.js:71:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.getModuleContext (file:///app/node_modules/next/dist/server/web/sandbox/context.js:41:25)
```

### Expected Behavior

No error.

### Link to reproduction

https://github.com/webda2l/nextjs-issue1

### To Reproduce

Build the docker, and run it http://localhost:3000/

**Comment by ajnart** [comment]
I am having the same issue @webda2l Downgrading to react `v17` and next to `v12.2.0` was a temporary fix but not i have this issue when trying to start my middleware : 
```ts
export function middleware(request: NextRequest) {
  const cookie = request.cookies.get('password');
  const isPasswordCorrect = cookie === process.env.PASSWORD;
  if (
    !isPasswordCorrect &&
    request.nextUrl.pathname !== '/login' &&
    request.nextUrl.pathname !== '/api/configs/trylogin'
  ) {
    return NextResponse.rewrite('/login');
  }
}
```

Page is white and console says this : 
```bash
The script from “http://localhost:3000/_next/static/chunks/webpack.js?ts=1658563289651” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.

The script from “http://localhost:3000/_next/static/chunks/main.js?ts=1658563289651” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
The script from “http://localhost:3000/_next/static/chunks/pages/_app.js?ts=1658563289651” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
The script from “http://localhost:3000/_next/static/development/_ssgManifest.js?ts=1658563289651” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
The script from “http://localhost:3000/_next/static/development/_buildManifest.js?ts=1658563289651” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
The script from “http://localhost:3000/_next/static/chunks/pages/login.js?ts=1658563289651” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
The script from “http://localhost:3000/_next/static/chunks/react-refresh.js?ts=1658563289651” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
Uncaught SyntaxError: expected expression, got '<'
[react-refresh.js:1](http://localhost:3000/_next/static/chunks/react-refresh.js?ts=1658563289651)
Uncaught SyntaxError: expected expression, got '<'
[webpack.js:1](http://localhost:3000/_next/static/chunks/webpack.js?ts=1658563289651)
Uncaught SyntaxError: expected expression, got '<'
[main.js:1](http://localhost:3000/_next/static/chunks/main.js?ts=1658563289651)
Uncaught SyntaxError: expected expression, got '<'
[_app.js:1](http://localhost:3000/_next/static/chunks/pages/_app.js?ts=1658563289651)
Uncaught SyntaxError: expected expression, got '<'
[login.js:1](http://localhost:3000/_next/static/chunks/pages/login.js?ts=1658563289651)
Uncaught SyntaxError: expected expression, got '<'
```

**Comment by ajnart** [comment]
Update : I have tested for every possible version since `12.2.0` with `react 17` **and** `react 18` and middlewares are NOT working for me.
The file is correclty named as the problem is not hapenning when the file is not there.
This problem occurs with or without `output: 'standalone'` in my case.
Here's the issue. 

```
The script from “http://localhost:3000/_next/static/chunks/webpack.js?ts=1658600668144” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
Uncaught SyntaxError: expected expression, got '<'
```

**Comment by webda2l** [comment]
@ajnart So seems like you're on another issue and you'll should follow the create issue procedure with a link to reproduction repository.

To complete my issue, if I use the `export const config` in the middleware file, I get only the error 500 mentioned upper on the routes include by the matcher, not every routes.

**Comment by ajnart** [comment]
> @ajnart So seems like you're on another issue and you'll should follow the create issue procedure with a link to reproduction repository.
> 
> To complete my issue, if I use the `export const config` in the middleware file, I get only the error 500 mentioned upper on the routes include by the matcher, not every routes. 

I had the same issue as you did on latest react and NextJS, it's still related to not being able to use middleware on > 12.2.0, what's why I posted my error and tests here.

**Comment by ref-thomasledoux1** [comment]
It seems like the "next/dist/compiled/@edge-runtime" dependency is not being picked up correctly by the tracing feature used by the outputstandalone..
We added the following to our catch-all route (pages/[[...slug]]): 
export const config = {
  unstable_includeFiles: [
    'node_modules/next/dist/compiled/@edge-runtime/primitives/**/*.+(js|json)',
  ],
}
This seems to have done the trick for now.

**Comment by webda2l** [comment]
> It seems like the "next/dist/compiled/@edge-runtime" dependency is not being picked up correctly by the tracing feature used by the outputstandalone.. We added the following to our catch-all route (pages/[[...slug]]):
> 
> ```js
> export const config = {
>   unstable_includeFiles: [
>     'node_modules/next/dist/compiled/@edge-runtime/primitives/**/*.+(js|json)',
>   ],
> }
> ```
> 
> This seems to have done the trick for now.

Indeed, tested as well in my `pages/index.tsx` and it fixes my real use case. Thanks.

**Comment by ref-thomasledoux1** [comment]
Good to hear! Hope this gets picked up by the team to fix it :-)

**Comment by klarstrup** [comment]
struck this as of `next@12.2.3` 🤔
