### ISSUE TITLE
Error: next/server should not be imported outside of pages/_middleware.js.

### ISSUE THREAD

**Issue by j-mendez** [vercel/next.js#38950]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.18.3
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.0.10
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Was using 12.2.2 and the `middleware.ts` file next to the pages directory and the next/server imports worked.
On 12.2.3 the error appears. I thought last update we just made it so the middleware file does not have to be inside the pages directory. 

### Expected Behavior

No error on build for `next/server` imports.

### Link to reproduction

https://github.com/a11ywatch/web

### To Reproduce

bump next to latest and try to build via `yarn build`.

**Comment by balazsorban44** [comment]
You likely refer to the ESLint rule. Make sure you update https://github.com/a11ywatch/web/blob/067768cb12c658f5ee5a9ff98682fc4333ff2036/package.json#L95 to match the `next` version.
