### ISSUE TITLE
`dangerouslyAllowSVG` config setting does not work

### ISSUE THREAD

**Issue by jciolek** [vercel/next.js#38968]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

`    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Jul 17 14:33:15 UTC 2022
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 3.1.1
      pnpm: 5.17.2
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0
`

### What browser are you using? (if relevant)

Brave 1.41.100

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Setting `dangerouslyAllowSVG` in the `images` section of `next.config.js` has no effect and the .svg images are not served through the image optimization API when the `next/image` component is used.

I have noticed, that in the PR https://github.com/vercel/next.js/pull/34431 the file `webpack-config.ts` hasn't been changed and in fact, the env variable `__NEXT_IMAGE_OPTS` [does not include](https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack-config.ts#L1566) the `dangerouslyAllowSVG` setting.

To verify that this is indeed the issue, I created the following workaround in `next.config.js`, which works:

```js
const nextConfig = {
  images: {
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    domains: ['a.storyblok.com'],
  },
  webpack(config, { isServer }) {
    if (isServer) {
      return config;
    }

    // This is a fix for botched webpack config in next.js.
    // They say you can use `dangerouslyAllowSVG` in images config,
    // but the prop is not passed down.
    config.plugins
      .filter((plugin) => plugin.constructor.name === 'DefinePlugin')
      .forEach((plugin) => {
        const key = 'process.env.__NEXT_IMAGE_OPTS';
        const value = JSON.parse(plugin.definitions[key] || '');

        if (value) {
          value.dangerouslyAllowSVG = nextConfig.images?.dangerouslyAllowSVG;
          plugin.definitions[key] = JSON.stringify(value);
        }
      });

    return config;
  },
}

module.exports = nextConfig;
```

### Expected Behavior

When `dangerouslyAllowSVG` is set to `true`, .svg images should be served through image optimization API, when using `image/next` component.

### Link to reproduction

https://codesandbox.io/s/crimson-surf-dc7loc?file=/next.config.js

### To Reproduce

1. Set the following in `next.config.js`:
```js
module.exports = {
  images: {
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    domains: ["www.svgrepo.com"]
  },
}
```
2. Add `next/image` to a page component and set `src` to point to an external .svg image:
```jsx
      <Image
        src="https://www.svgrepo.com/show/423204/coffee.svg"
        height={81}
        width={56}
      />
```
3. Observe the src in the rendered page. It should be `__next/image` but instead it points to the original location.

**Comment by ijjk** [comment]
Hi, good catch, out of curiosity what was the use case you found for wanting to enable this config? Running the SVG through the image optimizer does not apply any optimizations

**Comment by jciolek** [comment]
@ijjk Thanks! It's all about hosting the SVGs, so the traffic doesn't go directly to our CMS.
