### ISSUE TITLE
Docs: How to debug when there is not information related to our source code?

### ISSUE THREAD

**Issue by Nefcanto** [vercel/next.js#38965]
### What is the improvement or update you wish to see?

Let's see a real image of a codebase with at least 100 files and more than 100 `Link` usages:

![error](https://user-images.githubusercontent.com/12782347/180649179-9be02875-d7f4-4376-be01-ff5446438b4e.png)

Put yourself in our shoes. What should we do?

It's incredibly inefficient to use Newton's method and comment out half of the code just to find out which `Link` is causing this error.

It's the most essential thing to give developers their source code file and line number for troubleshooting.

Please tell us how we should troubleshoot these types of errors?

### Is there any context that might help us understand?

Next.js is the new hype. Yeah, I know many of us could simply not work with it. But that's not true. When something becomes the new fashion, then we are literally forced to migrate to it.

Please give more information for debugging.

Thank you.

**Comment by leerob** [comment]
Thank you for the suggestion here – we're going to continue working to make error message more clear and actionable 🙏 Feedback heard!
