### ISSUE TITLE
Server and client get different props value when passing NaN

### ISSUE THREAD

**Issue by clod9353** [vercel/next.js#38973]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.6.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.0
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When returning a NaN prop from getServerSideProps (see code below), and then using it inside the component, causes inconsisten value between server and client. 
```
export async function getServerSideProps() {
  return {
    props: {
      test: Number("test"), // NaN
    },
  };
}
```

Logging the prop from server, we can see that the value is **NaN** as expected, but on the client the value is **null**.

### Expected Behavior

The NaN value should be consistent between client and server

### Link to reproduction

https://codesandbox.io/s/next-nan-gkfo3s?file=/pages/index.tsx

### To Reproduce

- Start a new next project
- Inside index.js, put this code:
```
export async function getServerSideProps() {
  return {
    props: {
      test: NaN
    }
  };
}

export default function Home({ test }) {
  console.log("test", test);
  if (isNaN(test)) {
    return <div>NaN</div>;
  }

  return <div>Number</div>;
}
```
- Run the project
- Notice that the value logged server-side is different from the one logged client-side

**Comment by sasanpc85** [comment]
> ### Verify canary release
> 
> - [X] I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> 
>     Operating System:
>       Platform: darwin
>       Arch: arm64
>       Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
>     Binaries:
>       Node: 18.6.0
>       npm: 8.15.0
>       Yarn: 1.22.19
>       pnpm: N/A
>     Relevant packages:
>       next: 12.2.4-canary.0
>       eslint-config-next: 12.2.3
>       react: 18.2.0
>       react-dom: 18.2.0
> 
> ### What browser are you using? (if relevant)
> 
> _No response_
> 
> ### How are you deploying your application? (if relevant)
> 
> _No response_
> 
> ### Describe the Bug
> 
> When returning a NaN prop from getServerSideProps (see code below), and then using it inside the component, causes inconsisten value between server and client. 
> ```
> export async function getServerSideProps() {
>   return {
>     props: {
>       test: Number("test"), // NaN
>     },
>   };
> }
> ```
> 
> Logging the prop from server, we can see that the value is **NaN** as expected, but on the client the value is **null**.
> 
> ### Expected Behavior
> 
> The NaN value should be consistent between client and server
> 
> ### Link to reproduction
> 
> https://codesandbox.io/s/next-nan-gkfo3s?file=/pages/index.tsx
> 
> ### To Reproduce
> 
> - Start a new next project
> - Inside index.js, put this code:
> ```
> export async function getServerSideProps() {
>   return {
>     props: {
>       test: NaN
>     }
>   };
> }
> 
> export default function Home({ test }) {
>   console.log("test", test);
>   if (isNaN(test)) {
>     return <div>NaN</div>;
>   }
> 
>   return <div>Number</div>;
> }
> ```
> - Run the project
> - Notice that the value logged server-side is different from the one logged client-side

**Comment by balazsorban44** [comment]
This is currently expected. Values returned in `props` are serialized https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#props

`JSON.parse(JSON.stringify(Number('test'))` will yield `null`
