### ISSUE TITLE
Server Components not working after 12.2.0

### ISSUE THREAD

**Issue by jrwpatterson** [vercel/next.js#38979]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

Our team were experimenting with Server Components but using your demo https://github.com/vercel/next-react-server-components running with the latest versions of next we are getting the server rendered pages hanging, and never loading. 

Has something changed that we haven't see the documentation for or is there a bug in more recent versions?

### Expected Behavior

https://github.com/vercel/next-react-server-components should continue to work with recent versions of Nextjs

### Link to reproduction

https://github.com/vercel/next-react-server-components

### To Reproduce

clone https://github.com/vercel/next-react-server-components and upgrade to the latest nextjs

**Comment by balazsorban44** [comment]
Hey there, thanks for reporting this. Server Components support is still unstable. In preparation for stability, we are moving usage from `pages/` to the new `app/` folder as outlined in the [Layouts RFC](https://nextjs.org/blog/layouts-rfc). Server Components will be the default for all routes inside `app/`.

We'll be sharing more information soon on how you can test out early versions of `app/`.
