### ISSUE TITLE
Non-consistent basePath checking behaviour

### ISSUE THREAD

**Issue by eolme** [vercel/next.js#38984]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```sh
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 3.2.1
      pnpm: N/A
    Relevant packages:
      next: 12.2.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

If basePath is an empty string, a warning is displayed:

```sh
warn  - Invalid next.config.js options detected: 
[
  {
    "instancePath": "/basePath",
    "schemaPath": "#/properties/basePath/minLength",
    "keyword": "minLength",
    "params": {
      "limit": 1
    },
    "message": "must NOT have fewer than 1 characters"
  }
] 
See more info here: https://nextjs.org/docs/messages/invalid-next-config
```

But if you set the basePath to `/` an error occurs:

```sh
Error: Specified basePath /. basePath has to be either an empty string or a path prefix"
    at assignDefaults (/node_modules/next/dist/server/config.js:266:19)
    at Object.loadConfig [as default] (/node_modules/next/dist/server/config.js:97:16)
    at async NextServer.prepare (/node_modules/next/dist/server/next.js:115:24)
    at async /node_modules/next/dist/cli/next-dev.js:147:9
```

### Expected Behavior

Allow either an empty string or a slash as basePath

### Link to reproduction

-

### To Reproduce

-

**Comment by rikers** [comment]
probably related to issue #38967

**Comment by ijjk** [comment]
An empty string isn't a valid `basePath` and was previously normalized automatically since it's a falsy value so this warning is valid and the `basePath` value should be omitted for this case.

**Comment by eolme** [comment]
@ijjk but the error explicitly says that there may be an empty string 😕

**Comment by ijjk** [comment]
Hmm since we do mention the empty string is allowed and we normalize the value, it seems alright to avoid the warning here
