### ISSUE TITLE
Broken blurDataURL after ~12.2.1 patch

### ISSUE THREAD

**Issue by X7Becka** [vercel/next.js#39035]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

next start, next dev

### Describe the Bug

Hello. 
I found the bug with difference between next dev and next start in image/future (i guess result shouldn't be different to be sure i will ship app as i want to ship):
When i deploy my app or just build then start - blur images makes me scarry and flicker on millisecond because alpha channel doesn't work. Only gaussian: 
![image](https://user-images.githubusercontent.com/51074290/181088628-aa7c79a5-47ef-4493-b7cf-c1f3b53be1b1.png)
Horever, when i start the dev server, bug doesn't represents and blurred image looks as it should looks.
Finally, dev and runned ssr generates different blur images:
Dev: /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsplash.8cb7b12d.webp&w=8&q=70
Start: data:image/webp;base64,UklGRrgAAABXRUJQVlA4WAoAAAAQAAAABwAABAAAQUxQSCkAAAAAAAAJPwAxYAACABDnfI3bCAA3AHL79/8/AFW9693/wkIAAHhVSYkmMABWUDggaAAAAHACAJ0BKggABQACQDglsAJ0MEW/W79QAXECE4AA/spO0RQ0tGMgbY5zIa1mKEyF8zmfDfbxDSyWiqGvM5zXun/5/...

### Expected Behavior

I guess blur images gotta be the same.

### Link to reproduction

/

### To Reproduce

Use an image with image/future
Pass blurDataURL
See result with next dev
See result with next start

**Comment by styfle** [comment]
Can you share the full value of blurDataURL and also src?

**Comment by X7Becka** [comment]
> Can you share the full value of blurDataURL and also src?

blurDataURL: 
`data:image/webp;base64,UklGRrgAAABXRUJQVlA4WAoAAAAQAAAABwAABAAAQUxQSCkAAAAAAAAJPwAxYAACABDnfI3bCAA3AHL79/8/AFW9693/wkIAAHhVSYkmMABWUDggaAAAAHACAJ0BKggABQACQDglsAJ0MEW/W79QAXECE4AA/spO0RQ0tGMgbY5zIa1mKEyF8zmfDfbxDSyWiqGvM5zXun/5/54BzT+IDsm/5F/zRF+J3805u/azf4Y/OctSzg9jaR063+xumAAA`
src: 
`/_next/static/media/splash.8cb7b12d.webp`
src as file: 
![image](https://user-images.githubusercontent.com/51074290/182013862-07c29a75-52d2-4ac3-9ea2-56f30fd11573.png)
