### ISSUE TITLE
Being able to include deps from 'node_modules' into output

### ISSUE THREAD

**Issue by vincent-thomas** [vercel/next.js#39039]
### Describe the feature you'd like to request

To be able to include all modules into .next output instead of relieing on `node_modules`. Currently nextjs output relies on the folder node_modules. This is totally fine in a polyrepo setup, but problems starts to arise when you put it in a monorepo. With shared dependencies, locally (packages in the repo) and external libraries (from npm) are put into node_modules. Local libraries are included as symlinks, this wont cut it because when only deploying the nextjs app, the symlinks won't resolve.  

### Describe the solution you'd like

A option in the next.config.js, for example
```js
export.modules = {
  includeModules: {
    ignorePattern: ["next"],
    enable: true
  }
}
```
This would include modules sourcecode into .next. a bit like webpack. This would ease deployment in multiple ways

### Describe alternatives you've considered

I tried working around this issue with yarn workspaces and docker. I wanted the next.js's node_modules and output to be totally independent of the root node_modules. But this doesn't work because yarn is hoisting dependencies to the root worksize.e. I've tried fiddling with the yarn config file (`.yarnrc.yml`, using yarn 3+). I found one option `nmHoistingLimits`  that hoisted dependencies as far down in the workspaces as possible. But this is achieved with symlinks, which wont work when removing the local dependencies, aka optimizing docker image size

**Comment by balazsorban44** [comment]
You should be able to achieve this with the `output: "standalone"` configuration option. Please refer to the docs https://nextjs.org/docs/advanced-features/output-file-tracing
