### ISSUE TITLE
middleware causes infinite refresh loop with dynamic getStaticProps page deployed to vercel

### ISSUE THREAD

**Issue by bryanrsmith** [vercel/next.js#39049]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: 7.0.0-rc.7
    Relevant packages:
      next: 12.2.4-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Brave 1.41.100 Chromium: 103.0.5060.134 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Defining any middleware (even an empty middleware function) with a dynamic gsp page causes the page to rapidly refresh when deployed on Vercel

### Expected Behavior

The page should load without entering an infinite refresh loop.

### Link to reproduction

https://github.com/bryanrsmith/i18n-app

### To Reproduce

1. `npx create-next-app --example i18n-routing i18n-app`
2. Define an empty middleware function, `export function middleware(request) { return NextResponse.next();}`
3. Deploy the app to Vercel (I have deployed it to https://i18n-app-middleware.vercel.app/)
4. Visit `/gsp/first`

The page rapidly reloads in a loop.

**Comment by ijjk** [comment]
Hi, this has been updated in `v12.2.4-canary.3` of Next.js, please update and give it a try!

**Comment by bryanrsmith** [comment]
Thanks, @ijjk. Fix confirmed!

**Comment by mxkyb** [comment]
Oh my god. I spent a full day on this problem until I found this issue right now. thank you so much :D
