### ISSUE TITLE
VIDEOJS: WARN: The element supplied is not included in the DOM

### ISSUE THREAD

**Issue by pranshu1995** [vercel/next.js#39056]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
    Binaries:
      Node: 14.17.5
      npm: 8.3.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.0.7
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Google Chrome - Version 103.0.5060.114 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

npm run dev

### Describe the Bug

I am using [video.js](https://github.com/videojs/video.js) in my project to play streaming videos. The video player was working fine until I upgraded the React, React-DOM and Next packages for the project; and now I am getting this warning and the player is not loading properly. The player loads for a blink of an eye and then disappears. 

**Current Packages:**

    "next": "^12.2.2"
    "react": "^18.2.0"
    "react-dom": "^18.2.0"

**Previous Packages:**

     "next": "^12.1.6"
    "react": "^17.0.2"
    "react-dom": "17.0.2"

### Expected Behavior

The video player should load and run without any problem.

### Link to reproduction

https://github.com/pranshu1995/videojs-next-issue

### To Reproduce

If next, react and react-dom packages are downgraded to previous versions (mentioned before), the player loads without any problem.

**Comment by pranshu1995** [comment]
@huozhi I tried updating the next config as suggested in [this comment](https://github.com/vercel/next.js/issues/32355#issuecomment-1044192663), but didn't work out. Please guide me on how to resolve this issue.

Thanks

**Comment by balazsorban44** [comment]
This actually seems to be unrelated to Next.js, but to the React version only. React 17 worked, but React 18 did not, even with `12.1.6`.

The issue is tracked on video.js here: https://github.com/videojs/video.js/issues/7746
