### ISSUE TITLE
docker build RUN yarn build Error: Call retries were exceeded

### ISSUE THREAD

**Issue by huanlirui** [vercel/next.js#39062]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
    Binaries:
      Node: 14.16.1
      npm: 6.14.12
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

when i run   yarn build  its success
but when i run ” docker build “ Execute to yarn build ，i have this problem

i try to run yarn add --dev typescript @types/node
and try to add  this code in next.config.js  but the problem remains 。
```
 typescript: {
     ignoreBuildErrors: true
   }
```

![image](https://user-images.githubusercontent.com/40491203/181223586-abf97c52-95cd-4cdb-9483-81dc46bd7bbf.png)

### Expected Behavior

docker build success  

### Link to reproduction

no

### To Reproduce

when i run   yarn build  its success
but when i run ” docker build “ Execute to yarn build ，i have this problem

my docker file 

```
# Install dependencies only when needed
FROM node:16-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  [ -f yarn.lock ] && yarn --frozen-lockfile --prod || \

#   [ -f package-lock.json ] && npm ci || \
#   [ -f pnpm-lock.yaml ] && yarn global add pnpm && pnpm fetch --prod && pnpm i -r --offline --prod || \
  (echo "Lockfile not found." && exit 1)


# Rebuild the source code only when needed
FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build

# If using npm comment out above and use below instead
# RUN npm run build

# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# You only need to copy next.config.js if you are NOT using the default configuration
# COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

# Automatically leverage output traces to reduce image size 
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 4001

ENV PORT 4001

CMD ["node", "server.js"]

```

i try to run yarn add --dev typescript @types/node
and try to add  this code in next.config.js  but the problem remains 。
```
 typescript: {
     ignoreBuildErrors: true
   }
```

**Comment by Babbili** [comment]
@huanlirui that might happen if you added .env in `.dockerignore` file

**Comment by balazsorban44** [comment]
Try changing the package detection part to:

```Dockerfile
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile --prod; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm fetch --prod && pnpm i -r --offline --prod; \
  else echo "Lockfile not found." && exit 1; \
  fi
```

The short-circuiting with `||` did not seem to work, and I think that caused the error in installing the dependencies. I am opening a PR to fix our examples.

Also, do you have multiple lockfiles?

**Comment by huanlirui** [comment]
> @huanlirui that might happen if you added .env in `.dockerignore` file

my .dockerignore file 

```
Dockerfile
.dockerignore
node_modules
npm-debug.log
README.md
.next
.git
```

**Comment by huanlirui** [comment]
> Try changing the package detection part to:
> 
> ```dockerfile
> RUN \
>   if [ -f yarn.lock ]; then yarn --frozen-lockfile --prod; \
>   elif [ -f package-lock.json ]; then npm ci; \
>   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm fetch --prod && pnpm i -r --offline --prod; \
>   else echo "Lockfile not found." && exit 1; \
>   fi
> ```
> 
> The short-circuiting with `||` did not seem to work, and I think that caused the error in installing the dependencies. I am opening a PR to fix our examples.
> 
> Also, do you have multiple lockfiles?

i only have yarn.lock



```
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile --prod; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm fetch --prod && pnpm i -r --offline --prod; \
  else echo "Lockfile not found." && exit 1; \
  fi
```

this command  its run success  , I think this problem occurred during the yarn build  .  

I don't quite understand. I found that jest has a related issus, but I haven't used this thing. Is this the product of next?

**Comment by huanlirui** [comment]
This is all the files of this project 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/40491203/181287085-4cb900cf-4f49-40cb-b903-0bc39df1cd4c.png">

**Comment by ijjk** [comment]
@huanlirui please try pulling the latest version of [this example](https://github.com/vercel/next.js/tree/canary/examples/with-docker) as it has been updated to correct some issues!

**Comment by huanlirui** [comment]
> @huanlirui please try pulling the latest version of [this example](https://github.com/vercel/next.js/tree/canary/examples/with-docker) as it has been updated to correct some issues!

tanks ，It works for me ！
