### ISSUE TITLE
POST request from middleware fails

### ISSUE THREAD

**Issue by dferber90** [vercel/next.js#39060]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: 7.4.0
    Relevant packages:
      next: 12.2.4-canary.2
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Fetch requests made from middleware fail but only if the request is a POST request with a request body.

### Expected Behavior

The middleware should be able to make POST requests.

### Link to reproduction

https://github.com/dferber90/nextjs-fetch-bug-reproduction

### To Reproduce

1. Create a new Next.js project, eg `pnpm create next-app --ts`.

2. Add a `middleware.ts` file at the root with:

```ts
// middleware.ts
export const config = { matcher: "/" };

export async function middleware() {
  const text = await fetch("https://example.com", {
    method: "POST",
    body: "",
  }).catch((error) => {
    console.error(error);
    throw error;
  });

  console.log(text);
}
```

3. Visit http://localhost:3000

You will now see the red warning box.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/1765075/181215505-e749ee60-67e9-45ee-8475-0bdcb720ba61.png">

Additionally, the middleware will have logged the error to the terminal:

```
// from: console.error(error)
{ [TypeError: fetch failed]
  cause: [TypeError: define_process_default.nextTick is not a function] }

// from: throw error
error - Error [TypeError]: fetch failed
    at Object.processResponse (evalmachine.<anonymous>:3033:34)
    at <unknown> (evalmachine.<anonymous>:3366:42)
    at <unknown> (node:internal/process/task_queues:141:7)
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  middleware: true
}
```

**Comment by dferber90** [comment]
I debugged this a bit myself, maybe this is useful:

The `console.error(error)` output shows:

```
{ [TypeError: fetch failed]
  cause: [TypeError: define_process_default.nextTick is not a function] }
```

So `define_process_default` seems to be defined in 

https://github.com/vercel/next.js/blob/90ddd0dc83fefe0eb906f164f0ceea1549088d86/packages/next/compiled/%40edge-runtime/primitives/fetch.js#L63

Note that the provided default has no `nextTick` function:

https://github.com/vercel/next.js/blob/90ddd0dc83fefe0eb906f164f0ceea1549088d86/packages/next/compiled/%40edge-runtime/primitives/fetch.js#L68

But `nextTick` is called 4 times in that file

https://github.com/vercel/next.js/blob/90ddd0dc83fefe0eb906f164f0ceea1549088d86/packages/next/compiled/%40edge-runtime/primitives/fetch.js#L6001

https://github.com/vercel/next.js/blob/90ddd0dc83fefe0eb906f164f0ceea1549088d86/packages/next/compiled/%40edge-runtime/primitives/fetch.js#L5298

https://github.com/vercel/next.js/blob/90ddd0dc83fefe0eb906f164f0ceea1549088d86/packages/next/compiled/%40edge-runtime/primitives/fetch.js#L4222

https://github.com/vercel/next.js/blob/90ddd0dc83fefe0eb906f164f0ceea1549088d86/packages/next/compiled/%40edge-runtime/primitives/fetch.js#L571

---

I also noticed that this problem only happens during local development. The problem does not seem to exist when the application is actually deployed.

**Comment by dferber90** [comment]
Duplicate of:
- https://github.com/vercel/next.js/issues/38963
- https://github.com/vercel/edge-runtime/issues/61

**Comment by Charlie-007-star** [comment]
is there a solution yet?

**Comment by dferber90** [comment]
Since you asked the same question on another issue, here is a link to the answer given there: https://github.com/vercel/next.js/issues/38963#issuecomment-1202173861
