### ISSUE TITLE
Infinite rendering loop when using React.Suspense with dynamic imports

### ISSUE THREAD

**Issue by daniloarcidiacono** [vercel/next.js#39073]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.2
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 103.0.5060.134 (64 bit)

### How are you deploying your application? (if relevant)

next dev, but also tried Vercel

### Describe the Bug

I need to load dynamically and render a component on server side. Dynamic imports alone do not achieve what I want, because the resulting HTML contains the loading span:

```js
export default function TestComponent() {
    return <div>Hello!</div>
}
```

```js
export default function NoSuspensePage({name}) {
    const Component = dynamic(
        () => import(`../../components/TestComponent`),
        {
            loading: () => <span>Loading</span>,
            ssr: true
        }
    );

    console.log("Rendering...");
    return (
        <div>
            <h1>Dynamic import only - {name}</h1>

            <Component />
            <Link href='/no-suspense/first'>First post</Link>
            <Link href='/no-suspense/second'>Second post</Link>
        </div>
    );
}
```

`React.Suspense` is somewhat better, because it is resolved on server side, but despite that when the client rehydrates the Loading span is shown again:

```js
export default function SuspensePage({name}) {
    const Component = dynamic(
        () => import(`../../components/TestComponent`),
        {
            suspense: true,
            ssr: true
        }
    );

    console.log("Rendering...");
    return (
        <div>
            <h1>Dynamic import with React.Suspense - {name}</h1>

            <React.Suspense fallback={<span>Loading...</span>}>
                <Component />
            </React.Suspense>
            <Link href='/suspense/first'>First post</Link>
            <Link href='/suspense/second'>Second post</Link>
        </div>
    );
}
```

Furthermore, when the client clicks a link, an infinite rendering loop is triggered (check the browser console).

### Expected Behavior

No infinite loop when navigating through pages.

### Link to reproduction

https://github.com/daniloarcidiacono/nextjs-test-dynamic

### To Reproduce

1. From home page, click on  "Dynamic import With React.Suspense".
2. Open the browser console.
3. Click on "Second post" link.
4. The client gets stuck in an infinite loop
![image](https://user-images.githubusercontent.com/17272323/181269333-e3e99f21-1c62-4e92-a9d3-86e1ff278011.png)

**Comment by balazsorban44** [comment]
Dynamic imports need to be top-level:

> `dynamic()` can't be used inside of React rendering as it needs to be marked in the top level of the module for preloading to work, similar to `React.lazy`.

Please refer to the docs https://nextjs.org/docs/advanced-features/dynamic-import
