### ISSUE TITLE
Eslint formatter option

### ISSUE THREAD

**Issue by paulius-ruminas-nfq** [vercel/next.js#39123]
### Describe the feature you'd like to request

Ability to configure eslint formatter option (https://eslint.org/docs/latest/user-guide/formatters/#:~:text=ESLint%20comes%20with%20several%20built,json%20uses%20the%20json%20formatter.) for build/lint tasks. This way it would be possible to see eslint results in gitlab UI.

### Describe the solution you'd like

Ability to pass -f/--format option for build/lint tasks.

### Describe alternatives you've considered

I can't think of any other alternatives.

**Comment by SukkaW** [comment]
Isn't `next lint --fix` good enough?

**Comment by samcx** [comment]
This should be possible with `next lint --format`!
