### ISSUE TITLE
Add `isChanging` in `useRouter`

### ISSUE THREAD

**Issue by jsun969** [vercel/next.js#39128]
### Describe the feature you'd like to request

Can we have a field `isChanging` in `useRouter` to detect when router is changing then I can show a progress component

### Describe the solution you'd like

```ts
const { isChanging } = useRouter();
```

### Describe alternatives you've considered

`useIsRouterChanging.ts`

```tsx
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

export const useIsRouterChanging = () => {
  const [isChanging, setIsChanging] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const handleStart = () => {
      setIsChanging(true);
    };
    const handleStop = () => {
      setIsChanging(false);
    };

    router.events.on('routeChangeStart', handleStart);
    router.events.on('routeChangeComplete', handleStop);
    router.events.on('routeChangeError', handleStop);

    return () => {
      router.events.off('routeChangeStart', handleStart);
      router.events.off('routeChangeComplete', handleStop);
      router.events.off('routeChangeError', handleStop);
    };
  }, [router]);

  return isChanging;
};

```

`_app.tsx`

```tsx
const isRouterChanging = useIsRouterChanging();

{isRouterChanging && <LinearProgress />}
```

**Comment by balazsorban44** [comment]
You should be able to use the router events `routeChanageStart` and `routeChangeComplete` to achieve this.

Please refer to the docs https://nextjs.org/docs/api-reference/next/router#routerevents

**Comment by jsun969** [comment]
Ye. I use `router.events` as the alternative(I've shown my custom hook code in this issue). But is it more ez to make a `isChanging` field to detect this. I assume it's quite useful
