### ISSUE TITLE
Build step fails because File constructor is missing in global scope

### ISSUE THREAD

**Issue by SpadarShut** [vercel/next.js#39134]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.4
      eslint-config-next: 12.1.4
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Running `next build` results in error when a page uses a component with the following code:

```js
export const MyComponent = ({ urlOrFile }) => {

  // build command fails here:
  const isBlob = urlOrFile instanceof File

 return <div>...</div>
}
```

Checking what's there in the global scope gives this: 

```
[
  'global',                 'clearInterval',
  'clearTimeout',           'setInterval',
  'setTimeout',             'queueMicrotask',
  'performance',            'clearImmediate',
  'setImmediate',           'fetch',
  'Headers',                'Request',
  'Response',               'ReadableStream',
  'TransformStream',        '__NEXT_DATA__',
  '__NEXT_HTTP_AGENT',      '__NEXT_HTTPS_AGENT',
  '__extends',              '__assign',
  '__rest',                 '__decorate',
  '__param',                '__metadata',
  '__awaiter',              '__generator',
  '__exportStar',           '__createBinding',
  '__values',               '__read',
  '__spread',               '__spreadArrays',
  '__spreadArray',          '__await',
  '__asyncGenerator',       '__asyncDelegator',
  '__asyncValues',          '__makeTemplateObject',
  '__importStar',           '__importDefault',
  '__classPrivateFieldGet', '__classPrivateFieldSet',
  '__classPrivateFieldIn',  'regeneratorRuntime'
]

```
At the same time `next dev` compiles this without problems.

### Expected Behavior

Build should complete without errors.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-qfvuty?file=pages/index.tsx

### To Reproduce

- Reference the `File` constructor in code
- Run `next build`

**Comment by SukkaW** [comment]
`File` is only available in the browser and doesn't exist on the server. Thus when Next.js tries to render your component at the server side (Server-Side Rendering) it will throw `File is not defined`.

The only way to fix the issue is to make your code works on both client-side and server-side:


```ts
const isBlob = useMemo(() => {
  if (typeof window !== 'undefined') {
    // client-side
	return '' as any instanceof File;
  }
  // server-side
  return false; 
}, [])
```

**Comment by balazsorban44** [comment]
SukkaW is correct, you can refer to the documentation on how to access Web APIs safely https://nextjs.org/docs/migrating/from-create-react-app#safely-accessing-web-apis
