### ISSUE TITLE
Build failed because of webpack errors in latest next version

### ISSUE THREAD

**Issue by ohsnap4** [vercel/next.js#39147]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro   
    Binaries:
      Node: 16.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.2.2", newest: "12.2.4-canary.5".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

chromium 103.0.5060

### Describe the Bug

**npm run build:**
> next-data-fetching-practice-project@0.1.0 build
> next build

info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
info  - Linting and checking validity of types  
info  - Downloading WASM swc package...
info  - Using experimental wasm build of next-swc
warn  - Attempted to load @next/swc-win32-x64-gnu, but it was not installed
warn  - Attempted to load @next/swc-win32-x64-msvc, but an error occurred: The specified module could not be found.
\\?\E:\practiceProjects\Next Js\next-data-fetching-practice-project\node_modules\@next\swc-win32-x64-msvc\next-swc.win32-x64-msvc.node
panicked at 'The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Error { kind: Unsupported, message: "operation not supported on this platform" }) }', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.9.1/src/registry.rs:170:10

Stack:

Error
    at module.exports.__wbg_new_693216e109162396 (E:\practiceProjects\Next Js\next-data-fetching-practice-project\node_modules\next\wasm\@next\swc-wasm-nodejs\wasm.js:202:17)
    at wasm://wasm/059aa236:wasm-function[5445]:0xf90917
    at wasm://wasm/059aa236:wasm-function[13700]:0x11eca7b
    at wasm://wasm/059aa236:wasm-function[9995]:0x1186adc
    at wasm://wasm/059aa236:wasm-function[11009]:0x11b6862
    at wasm://wasm/059aa236:wasm-function[12785]:0x11e5cdd
    at wasm://wasm/059aa236:wasm-function[11383]:0x11c358f
    at wasm://wasm/059aa236:wasm-function[10017]:0x1187e72
    at wasm://wasm/059aa236:wasm-function[1151]:0x98decd
    at wasm://wasm/059aa236:wasm-function[654]:0x75f3f2

info  - Creating an optimized production build
Failed to compile.

static/chunks/framework-aceae1aece8045c6.js from Terser
unreachable
RuntimeError: unreachable
    at wasm://wasm/059aa236:wasm-function[9995]:0x1186aff
    at wasm://wasm/059aa236:wasm-function[11009]:0x11b6862
    at wasm://wasm/059aa236:wasm-function[12785]:0x11e5cdd
    at wasm://wasm/059aa236:wasm-function[11383]:0x11c358f
    at wasm://wasm/059aa236:wasm-function[10017]:0x1187e72
    at wasm://wasm/059aa236:wasm-function[1151]:0x98decd
    at wasm://wasm/059aa236:wasm-function[654]:0x75f3f2
    at wasm://wasm/059aa236:wasm-function[654]:0x760098
    at wasm://wasm/059aa236:wasm-function[3154]:0xd6fe73
    at wasm://wasm/059aa236:wasm-function[654]:0x75f24f

> Build failed because of webpack errors

### Expected Behavior

i want the successful build of the next app

### Link to reproduction

*

### To Reproduce

*

**Comment by balazsorban44** [comment]
This should have been fixed already on `12.2.3`, please upgrade with `npm i next@latest` and let us know. Please also verify your Next.js version and carefully read the issue template before creating an issue. :pray:

**Comment by ohsnap4** [comment]
btw after updating still getting the same issue
