### ISSUE TITLE
unhandledRejection Error when running npm run dev

### ISSUE THREAD

**Issue by dhavalveera** [vercel/next.js#39178]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.1.6
      react: 18.1.0
      react-dom: 18.1.0
```

### What browser are you using? (if relevant)

Chrome 103.0.5060.134

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

```bash
event - compiled client and server successfully in 394 ms (1715 modules)
error - unhandledRejection: Error: aborted
    at connResetException (node:internal/errors:683:14)
    at abortIncoming (node:_http_server:592:17)
    at socketOnClose (node:_http_server:586:3)
    at Socket.emit (node:events:406:35)
    at TCP.<anonymous> (node:net:661:12) {
  code: 'ECONNRESET'
}
```

### Expected Behavior

it should not throw the error

### Link to reproduction

.

### To Reproduce

I updated the nextjs version to 12.2.3 and also updated the react & react-dom package, but still the issue persist.

**Comment by ijjk** [comment]
Hi, this should be fixed in the latest canary of Next.js `v12.2.4-canary.8`, specifically [this PR](https://github.com/vercel/next.js/pull/39091).

**Comment by blackwizard111** [comment]
I am getting the same error and couldn't find the solution.. Help me

**Comment by kereh** [comment]
@ijjk wow thank you, it works for me :)

**Comment by marcelobitorical** [comment]
Thank you! Works great

**Comment by mrLuisFer** [comment]
> Hi, this should be fixed in the latest canary of Next.js `v12.2.4-canary.8`, specifically [this PR](https://github.com/vercel/next.js/pull/39091).

I had the same error, and this fixed it
Thanks 👍🏻

**Comment by Yorkshireman** [comment]
`v12.2.4` fixes this now

**Comment by xiaocai-rookie** [comment]
> Hi, this should be fixed in the latest canary of Next.js `v12.2.4-canary.8`, specifically

I has this question,I use version `12.3.1`
