### ISSUE TITLE
Property 'revalidate' does not exist on type 'NextApiResponse<any>'

### ISSUE THREAD

**Issue by luopeihai** [vercel/next.js#39182]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

nextjs: 12.0.7

### Describe the Bug

ts alter error：

Property 'revalidate' does not exist on type 'NextApiResponse<any>'.

### Expected Behavior

Property 'revalidate' does not exist on type 'NextApiResponse<any>'.ts

### Link to reproduction

sorry , This my local code

### To Reproduce

My project with typescript and This's my code :

```
// pages/api/xxx.ts

import type { NextApiRequest, NextApiResponse } from "next";
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    // Check for secret to confirm this is a valid request
    if (req.query.secret !== process.env.MY_SECRET_TOKEN) {
        return res.status(401).json({ message: 'Invalid token' })
    }

    try {
        // this should be the actual path not a rewritten path
        // e.g. for "/blog/[slug]" this should be "/blog/post-1"
        await res.revalidate('/path-to-revalidate')
        return res.json({ revalidated: true })
    } catch (err) {
        // If there was an error, Next.js will continue
        // to show the last successfully generated page
        return res.status(500).send('Error revalidating')
    }
}
```

**Comment by ijjk** [comment]
Hi, `res.revalidate()` is only available in versions `>= v12.2.0` prior versions it was called `res.unstable_revalidate()`.
