### ISSUE TITLE
Connectivity Issue with the `npx create-next-app --example` command.

### ISSUE THREAD

**Issue by chof64** [vercel/next.js#39181]
Hello, I am having the same issue, however, on mine, the `--example` points to  `https://github.com/vercel/next-learn/tree/master/basics/learn-starter` as per the tutorial (https://nextjs.org/learn/basics/create-nextjs-app/setup).
![Screenshot from 2022-07-30 15-32-31](https://user-images.githubusercontent.com/46257935/181880324-a8ee52e4-8a35-4cd8-a201-b6d7a5373342.png)

But what I noticed is that all the files from the GitHub repo seem to be downloaded. However, dependencies are not installed.

So with the assumption of all the files are fully downloaded, I just manually run `npm install to install dependencies. And proceeded to run `npm run dev` to start the dev server. And it worked!
![Screenshot from 2022-07-30 15-41-59](https://user-images.githubusercontent.com/46257935/181880396-14d1d958-4340-434b-85a1-a93021fcf27a.png)

It seems that there's some bug in the script that even though it already downloaded the repo, returns an error even though the download is complete. And with this error, the rest of the script (dependency installation) is not run.

_Originally posted by @chof64 in https://github.com/vercel/next.js/discussions/24802#discussioncomment-3285830_

**Comment by IntroJoul** [comment]
![image](https://user-images.githubusercontent.com/83115888/182027265-24f78b8e-d743-4801-8b7f-152f43d2b090.png)

[The bottom link](https://github.com/vercel/next-learn/blob/master/basics/errors/install.md) is to a readme page with the recommendation to use 
```bash
npm init next-app nextjs-blog
```
instead

**Comment by IntroJoul** [comment]
I feel this should be changed on the website

**Comment by jeferson-sb** [comment]
Related to #39321

**Comment by balazsorban44** [comment]
@chof64 could you verify which Node.js version you are on? As pointed out above, we are tracking an upstream issue in #39321 that might be the same issue that you have.

**Comment by stuartrapop** [comment]
I am having the same or similar issue

`npx create-next-app@latest --example with-jest first-test `

returns
```

? Could not download "with-jest" because of a connectivity issue between your machine and GitHub.
✔ Could not download "with-jest" because of a connectivity issue between your machine and GitHub.
Do you want to use the default template instead? … yes
The directory with-jest-app contains files that could conflict:
```

node version : v18.7.0

**Comment by balazsorban44** [comment]
Closing in favor of #39321 as this is very likely the same issue. I opened a PR #40182 to fix this.
