### ISSUE TITLE
PWA not installable in production (failed to register a ServiceWorker for scope)

### ISSUE THREAD

**Issue by AhsanSarwar45** [vercel/next.js#39224]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.8
      eslint-config-next: N/A
      react: 17.0.2
      react-dom: 17.0.2

### Which example does this report relate to?

progressive-web-app

### What browser are you using? (if relevant)

Microsoft Edge 103.0.1264.71

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

After deployment in production, there is no install button in the address bar. The following error is shown in the console:
```
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://progressive-web-app-mocha-six.vercel.app/') with script ('https://progressive-web-app-mocha-six.vercel.app/sw.js'): A bad HTTP response code (404) was received when fetching the script.
```
Very similar to https://github.com/vercel/next.js/issues/31125. The solution mentioned in that thread (https://github.com/interclip/next/commit/50785a15394345a97f1774e052cd2f32650dad1c) did not work.

### Expected Behavior

The app should be installable via a button in the address bar.

### To Reproduce

Deploy https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app.

**Comment by AhsanSarwar45** [comment]
On further research, the issue is probably related to next-pwa https://github.com/shadowwalker/next-pwa/issues/370

**Comment by timmapuramreddy** [comment]
same issue..Tried with Nextjs 12.2.3 paw 5.5.4 not generating the service worker js files

**Comment by AhsanSarwar45** [comment]
> same issue..Tried with Nextjs 12.2.3 paw 5.5.4 not generating the service worker js files

Make sure your version doesn't contain a `^`
```json
"next-pwa": "5.5.4",
! "next-pwa": "^5.5.4",
```
