### ISSUE TITLE
Rewrite not working if destination is a catch-all-route

### ISSUE THREAD

**Issue by tilman** [vercel/next.js#39256]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000
Binaries:
  Node: 14.19.3
  npm: 6.14.17
  Yarn: 1.22.19
  pnpm: 7.5.0
Relevant packages:
  next: 12.2.4-canary.9
  eslint-config-next: 12.2.3
  react: 18.2.0
  react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome with german default language

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

If the destination of an rewrite (in next.config.js) is an catch all route. The rewrite is not working and I receive an 404 on the source of the rewrite.

### Expected Behavior

Rewrites should also work if the destination is an catch-all-route ([...slugs].tsx).

### Link to reproduction

https://github.com/trieb-work/catchall-redirect-issue-

### To Reproduce

1.) Visit https://routing-issue-example-lela0i4j1-triebwork.vercel.app/
2.) You should see a 404 page even if the page from https://routing-issue-example-lela0i4j1-triebwork.vercel.app/index should be rewritten to this page

**Comment by tilman** [comment]
verified again after `12.2.6-canary.1` and the issue still exists

**Comment by ijjk** [comment]
Hi, this appears to be due to using a rewrite from `/` to `/index` which isn't supported as `/` is meant to be treated the same as `/index`. Instead an optional catch-all route should be used which achieves matching the `/` route without the rewrite workaround. 

Related documentation https://nextjs.org/docs/routing/dynamic-routes#optional-catch-all-routes
