### ISSUE TITLE
Middleware causes router to choose root server-rendered [...catchall] over more specific dynamic route only in production

### ISSUE THREAD

**Issue by Winwardo** [vercel/next.js#39266]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I am using codesandbox with `12.2.4-canary.9`, I don't know why `next info` is reporting `12.1.7-canary.46` - if that were correct, this example wouldn't run at all as I'm using top level middleware.

sandbox@sse-sandbox-kfj5rr:/sandbox$ sandbox@sse-sandbox-kfj5rr:/sandbox$ npx --no-install next infonpx --no-install next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022
    Binaries:
      Node: 14.19.3
      npm: 6.14.17
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.46
      react: 18.2.0
      react-dom: 18.2.0

    Operating System:
      Platform: linux
      Arch: x64
      Version: #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022
    Binaries:
      Node: 14.19.3
      npm: 6.14.17
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.46
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.1.7-canary.46", newest: "12.2.4-canary.9".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
warn  - Latest canary version not detected, detected: "12.1.7-canary.46", newest: "12.2.4-canary.9".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

-

### How are you deploying your application? (if relevant)

Deployed to Vercel

### Describe the Bug

Top level middleware appears to be breaking routing to routes with dynamic segments, in favour of a less specific root `[...catchall].tsx` that uses `getServerSideProps`.

1. Given the following directory structure:
![image](https://user-images.githubusercontent.com/840549/182463943-4c7da618-1d6d-4f83-b460-fb6d0f70df0f.png)

2. where all pages except `[...catchall].tsx` are simple components (no use of `getServersideProps` or `getStaticProps`) similar to this:
![image](https://user-images.githubusercontent.com/840549/182462116-458b8076-4adb-4027-a201-d141bd6bf767.png)

3. and a top level middleware that applies only to `/broken/:path*`
![image](https://user-images.githubusercontent.com/840549/182462294-7d1fc409-30e8-4240-9234-5bc5dfe29c8e.png)

4. when trying to access a route `broken/[userid]/edit` with middleware in front of it, NextJS is routing instead to the less specific `[...catchall].tsx`, which uses `getServerSideProps`
![image](https://user-images.githubusercontent.com/840549/182465055-0f16f42a-73d9-4468-bccf-68922f5df4de.png)

![image](https://user-images.githubusercontent.com/840549/182464078-710231a1-89c9-472e-88a8-f05219988cae.png)

6. notice how the URL is still pointing at the broken route `/broken/somevalue/edit`. This happens even if the `[...catchall]` redirects.

This does not happen if:
 * You are running in development.
 * You use `[catchall]` instead of `[...catchall]` (i.e. you use a dynamic route segment, but not one that is a [catch all](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes))
 * The catchall does not use `getServerSideProps`
 * There is no catchall route
 * The target path does not have middleware applied to it
 * You use previous versions of NextJS where you have a colocated `_middleware.ts`

I have not tried:
 * Moving the catchall to another location

### Expected Behavior

Adding middleware in front of a dynamic route should not affect routing.

### Link to reproduction

https://codesandbox.io/s/nextjs-12-2-middleware-catchall-issue-kfj5rr?file=/pages/index.tsx

### To Reproduce

This bug ONLY appears after building. It does not happen when running `next dev`.

// ✔️ [...catchall]
// ✔️ middleware
// ✔️ bug
// https://csb-kfj5rr-pjwuo58u8-winwardo.vercel.app/

// ✔️ [...catchall], but without getServerSideProps
// ✔️ middleware
// ❌ bug
// https://csb-kfj5rr-dl8707jrw-winwardo.vercel.app/

// ❌ [...catchall]
// ✔️ middleware
// ❌ bug
// https://csb-kfj5rr-l5obh31us-winwardo.vercel.app/

// ❌ [...catchall]
// ✔️ [query]
// ✔️ middleware
// bug
// https://csb-kfj5rr-pnre13we2-winwardo.vercel.app/

**Comment by Winwardo** [comment]
It feels like https://github.com/vercel/next.js/issues/39255 and https://github.com/vercel/next.js/issues/39256 are closely related to this issue too

**Comment by mmmulani** [comment]
also seeing this issue, ping @javivelasco on this ^

**Comment by Winwardo** [comment]
This appears to be fixed both in my CodeSandbox example, and large personal project, in `12.2.5-canary.0`, possibly from this change: https://github.com/vercel/next.js/commit/a679a1e13224407ea01dfbabe5a9ac4975f31eea

@mmmulani Does `12.2.5-canary.0` fix it for you too?

**Comment by mmmulani** [comment]
hmmm it does solve it for me though that commit makes it seem like the opposite behaviour is desired? will comment on the PR #39370 asking for clarification

**Comment by ijjk** [comment]
Closing as this should be resolved in the latest version of Next.js
