### ISSUE TITLE
Misleading info log after running `next dev`

### ISSUE THREAD

**Issue by dgrcode** [vercel/next.js#39261]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
  Operating System:
    Platform: darwin
    Arch: x64
    Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
  Binaries:
    Node: 14.17.0
    npm: 6.14.13
    Yarn: 1.22.5
    pnpm: N/A
  Relevant packages:
    next: 12.2.4-canary.9
    eslint-config-next: 12.2.0
    react: 18.2.0
    react-dom: 18.2.0
```

### Describe the Bug

npx --no-install next info

### Expected Behavior

I expected the logs to give accurate information regarding the environment variable loaded.

The logs give misleading information.

I used `dotenv-cli` to provide a `env.staging` file for env variables to the command `next dev`. The `env.staging` file was successfully loaded. The info logs are copied below:

```
daniel (main) $ yarn dev
yarn run v1.22.5
$ dotenv -e .env.staging -- next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /path_to_project/.env.local
```

### Link to reproduction

https://codesandbox.io/s/info-logs-bug-5knxtu?file=/pages/_app.tsx

*EDIT: It seems codesandbox is messing with the env variables, so there's not much to see there.

### To Reproduce

1. Create a project
2. Add `env.local` with a value, for example `MESSAGE=local`
3. Add `env.staging` with the same key but different value. For example `MESSAGE=staging`
4. Install `dotenv-cli` to be able to provide `env.staging` as env variable files
5. In package.json, replace the `dev` command with `dotenv -e .env.staging -- next dev`
6. Run `yarn dev`

Expected to

**Comment by JanKaifer** [comment]
I'm little bit confused by this report. What file gets loaded? Are you able to repro this without `dotenv-cli`?

**Comment by dgrcode** [comment]
Sorry if it wasn't clear enough.

The issue is that `.env.staging` variables are loaded while the logs tell me `.env.local` variables were loaded.

I think this issue cannot be reproduced without `dotenv-cli`, because that's necessary to load `.env.staging` variables, right? I'm not sure what's the current situation, but last time I checked Next didn't natively support staging environment variables.

**Comment by JanKaifer** [comment]
Oh, now I see the problem.
Well since `dotenv-cli` is loading of env variables than next.js doesn't know about `staging` being lodaded. And we just load `.env.local` as normal.

But since variables from `.env.staging` are in `process.env` now they will be preffered over stuff in `.env.local`.

https://nextjs.org/docs/basic-features/environment-variables#environment-variable-load-order
