### ISSUE TITLE
Standalone mode and `experimental-edge` API route shows trace warning

### ISSUE THREAD

**Issue by co6x0** [vercel/next.js#39275]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.4.0
      npm: 8.13.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.9
      eslint-config-next: 12.2.4-canary.9
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When `output: "standalone"` in next.config.js and `runtime: "experimental-edge"` in API Routes are enabled, `next build` will display the following error in the terminal.

```sh
> Build error occurred
[Error: ENOENT: no such file or directory, open '/sandbox/.next/server/pages/api/hello.js.nft.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/sandbox/.next/server/pages/api/hello.js.nft.json'
}
```

Looking in the .next directory, this path does not exist, but apparently `.next/pages/api/hello.js.nft.json` does.

### Expected Behavior

Output file paths by Edge API Routes are correctly provided in standalone.

### Link to reproduction

https://codesandbox.io/s/quizzical-breeze-ipms0m

### To Reproduce

1. add `output: "standalone"` to `next.config.json`
2. create `pages/api/*.ts` like [Edge API Routes basic example](https://nextjs.org/docs/api-routes/edge-api-routes#basic)
3. run `next build`

**Comment by zzjin** [comment]
I have same issue here

**Comment by otavioalmeidatc** [comment]
**Temporary Solution**

Run this script in parallel with your build:

```sh
#!/usr/bin/env bash

NEXT_PAGES_API=pages/api

timeout 1h sh -c 'until [ -d .next/'"$NEXT_PAGES_API"' ]; do sleep 1; done'

find .next/$NEXT_PAGES_API -type f -name '*.js.nft.json' \
	-exec echo "patching file {}" \; \
	-exec sed -i 's/\/server//g;s/\.\.\/package\.json/\.\.\/\.\.\/package\.json/g' {} \; \
	-exec mv {} .next/server/$NEXT_PAGES_API \;

```

> **Note:** Still missing wasm files contained in .next/server/edge-chunks folder that need to be moved to .next/standalone/.next/server/edge-chunks

**Comment by ferdingler** [comment]
Same issue, next build fails with following error: 

```txt
[Error: ENOENT: no such file or directory, open 'with-edge-api/.next/server/pages/api/hello.js.nft.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'with-edge-api/.next/server/pages/api/hello.js.nft.json'
}
```

My next.config.js file looks like this: 
```js
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  output: "standalone",
}

module.exports = nextConfig
```

My api route: 
```js
// pages/api/hello.js

export const config = {
  runtime: 'experimental-edge',
}

export default (req) => new Response('Hello world!')
```
