### ISSUE TITLE
The typescript project generated by create next app does not match the types version of react.

### ISSUE THREAD

**Issue by stempest0925** [vercel/next.js#39318]
### Provide environment information

node: v16.16.0
create-next-app: v12.2.3

### Which example does this report relate to?

package.json

### Describe the Bug

The typescript project generated by create next app does not match the types version of react.

react: 18.2.0
@types/react: 15.7.8
The hook cannot be used normally

### Expected Behavior

Correct the typescript version corresponding to the module.

### To Reproduce
create-next-app appName --typescript
package.json devDependencies -> @types/react

**Comment by balazsorban44** [comment]
Could you please specify what you mean by:

> The hook cannot be used normally

We automatically install the latest version of `@types/react` and `react`, which should always match. Please provide a code snippet or a reproduction repository.

**Comment by stempest0925** [comment]
> Could you please specify what you mean by:
> 
> > The hook cannot be used normally
> 
> We automatically install the latest version of `@types/react` and `react`, which should always match. Please provide a code snippet or a reproduction repository.

Sorry, I gave it a try today and found that the latest version of the@types/react installation using NPM/yarn is 15.7.8.

It seems that npm is getting https://www.npmjs. com/package/@types/react Version History, not the Current Tags Version.

The resulting types/react can not use hooks properly.

This is not a create-next-app issue. Thank you for your help.
