### ISSUE TITLE
Using monaco-editor with next throws error `(cannot read property Symbol(Symbol.iterator))`

### ISSUE THREAD

**Issue by kevinehosford** [vercel/next.js#39360]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.3.0
      npm: 7.15.1
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome Version 103.0.5060.134 (Official Build) (arm64)

### Describe the Bug

When using the `monaco-editor` with `next` an exception will be thrown when selecting an item from the suggested items:

```
Error: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

Example project: https://github.com/kevinehosford/next-react-monaco

![CleanShot 2022-08-05 at 09 47 57](https://user-images.githubusercontent.com/18267875/183091322-1ec64a12-b0df-477a-af09-82c0e1afc61e.gif)

### Expected Behavior

No exception to be thrown. A similar project not using `next` does not throw the error

Similar project: https://github.com/kevinehosford/webpack-react-monaco

![CleanShot 2022-08-05 at 10 06 06](https://user-images.githubusercontent.com/18267875/183094508-c4e510a1-8b3c-4a53-9651-8723c08a23b5.gif)

### Link to reproduction

https://github.com/kevinehosford/next-react-monaco

### To Reproduce

Select an item from code completion suggestions and the exception will be thrown.

**Comment by kdy1** [comment]
I investigated this and seems like an issue of variable renamer pass.

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/29931815/183245217-e09e4198-0bd8-44a7-9349-bfe44ff71319.png">

`dispose` should be renamed to point to the outer one, but seems like the variable renamer didn't do so.

So... `dispose` is called again with `this = undefined`

---


<img width="1463" alt="image" src="https://user-images.githubusercontent.com/29931815/183245485-1d582633-693e-4632-be61-b02623ab7721.png">

And seems like monaco-editor is transpiled to es5 using SWC using `next-transpile-modules`

Not sure why the variable renamer gave up, though.
I'll investigate further
