### ISSUE TITLE
Revalidated data by ISR is not updated when browser back / forward

### ISSUE THREAD

**Issue by ruwatana** [vercel/next.js#39394]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.4-canary.12
      eslint-config-next: 12.2.4
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.2.4-canary.12", newest: "12.2.4".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

Chrome, Safari

### How are you deploying your application? (if relevant)

next build && next start

### Describe the Bug

There is a Next.js project that `getStaticProps()` (SSG) is given a validate option to achieve ISR.
The server side behavior seems to be working correctly as far as the `x-vercel-cache` header is concerned.

However, when the project is started with `next start`, the json file (_next/data) always returns the old cache data with 200 or 304 status code and regardless of any `x-vercel-cache` header values (like hit or stale) when a browser back or forward is performed. 
Even if regeneration has been completed on the server side.

Also, when reloading the browser or visiting the site for the first time, revalidated data was retrieved.
It is the same when started with `next dev`.

### Expected Behavior

I think it should be refreshed even when go back or forward on browser if cache data revalidated by ISR.
Is this expected behavior or a bug? 
How can I achieve my expected behavior?

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-ysmyj6?file=pages%2Findex.tsx,pages%2Fsecond.tsx

### To Reproduce

0. fork to local
1. run `next build && next start`
2. go http://localhost:3000
3. tap a link in top page and go second page
4. go back on browser
5. go forward on browser
6. repeat 5 or 6

**Comment by ijjk** [comment]
Hi, this behavior is currently expected and is to ensure fast history navigations, in the latest version of Next.js we do attempt best effort cache updating on link hover. See related issue here https://github.com/vercel/next.js/issues/39186#issuecomment-1200166303

Gonna close this for now as this doesn't appear to be a bug.

**Comment by ruwatana** [comment]
@ijjk 
Thank you for your response. I understood most of it.

Is it correct that we need to use SSR or CSR to solve the problem currently? Is there anything else?

**Comment by ijjk** [comment]
If you always want to see fresh data then SSR or CSR would make sense yeah, we are investigating more optimistic data fetching on the client to update the client cache which could help here though.
