### ISSUE TITLE
Can't find @types/react all of a sudden, been there for months

### ISSUE THREAD

**Issue by lwensveen** [vercel/next.js#39415]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Doesn't work

### What browser are you using? (if relevant)

Version 104.0.5112.79 (Official Build) (x86_64)

### Describe the Bug

Didn't really change anything, out of nowhere, locally and in my pipelines, I get the following error:

```
error:   It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

    yarn add --dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).
```

It's right there in my package.json so I don't know what's up with this.

### Expected Behavior

Should work

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-7q2ayc

### To Reproduce

Hard to do, one day you're working and there's no problem, next day all of a sudden it can't find the types.

**Comment by balazsorban44** [comment]
The reproduction you are providing uses an older version of Next.js, please make sure you upgrade and test with `canary` as instructed, before opening a new bug report.

I cannot reproduce it with `next@latest`, so please upgrade.

Anyway, this seems to be related to this release from 13 days ago:

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/ad4d3aa70d943375606bc36d625dbba216cec7cb

If you cannot upgrade `next` for some reason, you can work around the issue by locking the package version by removing the `^` operator: `"@types/react": "17.0.39"`, or ideally upgrade `@types/react` and `react` to version 18.
