### ISSUE TITLE
macher middleware not work for home after add trailingSlash true

### ISSUE THREAD

**Issue by mehdiraized** [vercel/next.js#39468]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 17.1.0
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: 7.8.0
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.2.3
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 100.0.4878.0

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

after add trailingSlash true in next config middleware for pages/index.js not work 
```
export const config = {
  matcher: [
    "/",
    "/login",
  ],
};
```

### Expected Behavior

i want to check middleware in home page after add trailingSlash true

### Link to reproduction

https://codesandbox.io/s/blissful-goldwasser-1vclfg?file=/middleware.ts

### To Reproduce

i create middleware.ts and add matcher for ['/', '/login/']
and add 
```
trailingSlash: true
```
in next.config.js
but middleware not work on / home page

**Comment by ijjk** [comment]
Hi, this should working in the latest canary of Next.js `v12.2.5-canary.1`, please update and give it a try!
