### ISSUE TITLE
Page components mount twice in dev build

### ISSUE THREAD

**Issue by vasimi** [vercel/next.js#39492]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.0
      npm: 8.3.0
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 12.2.5-canary.4
      eslint-config-next: 12.2.4
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

Page components are mounted, unmounted and mounted again right after page load. This only happens in a dev build.

### Expected Behavior

Page components only mount once after page load and on navigation.

### Link to reproduction

https://github.com/vasimi/next-remount-reproduction

### To Reproduce

Run dev server a take a look at the browser console. `mount` is logged twice, `unmount` once.
![Snímek obrazovky 2022-08-11 v 12 56 23](https://user-images.githubusercontent.com/9162439/184119379-8e7bb9ba-24b0-4e97-9f9a-34e8d70c5af0.png)

**Comment by ZakariaBenali** [comment]
This is happening because of react strict mode, you can check next.config.js you'll find that reactStrictMode is enabled, this is useful to prevent some problems and only happens in dev mode. 
there is already an issue closed for the same concern: https://github.com/vercel/next.js/issues/35822

**Comment by vasimi** [comment]
I tried searching for similar issues but found nothing. Thanks for the link.
