### ISSUE TITLE
Error on dynamic Facebook CDN domains when using Next Image

### ISSUE THREAD

**Issue by rafae2k** [vercel/next.js#39512]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.6.0
      npm: 8.13.2
      Yarn: 1.22.15
      pnpm: 7.6.0
    Relevant packages:
      next: 12.2.1
      eslint-config-next: 12.2.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Microsoft Edge Version 104.0.1293.47 (Official build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I'm facing a little problem consuming an API that fetches data from Facebook, since almost every time the CDN domain change e.g:

'scontent-iad3-1.xx.fbcdn.net',
'scontent-iad3-2.xx.fbcdn.net'
....
<img width="946" alt="Screen Shot 2022-08-11 at 14 22 35" src="https://user-images.githubusercontent.com/53544360/184196106-5100663b-85d6-4e95-98f1-4cf5a530cdd6.png">

I keep getting warnings because the domain wasn't added to next.config.js BTW because it is dynamic.

how to handle that?

### Expected Behavior

Optional or loader to handle dynamic CDN url

### Link to reproduction

n/a

### To Reproduce

n/a

**Comment by balazsorban44** [comment]
You, can allow dynamic urls by the `remotePatterns` configuration option https://nextjs.org/docs/api-reference/next/image#remote-patterns
