### ISSUE TITLE
fetch api in edge runtime not support retry

### ISSUE THREAD

**Issue by chendong-xie** [vercel/next.js#39524]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

"next": "12.1.6"
"node": 16.16.0

### What browser are you using? (if relevant)

chore

### Describe the Bug

fetch api in edge runtime not support retry
all get  reason: read ECONNRESET error

### Expected Behavior

fetch can retry when  ECONNRESET error

### Link to reproduction

no need link

### To Reproduce

no need link

**Comment by chendong-xie** [comment]
![image](https://user-images.githubusercontent.com/82069123/184331100-2093fc5d-8c77-4784-aa69-44c705e1bcaf.png)

**Comment by SukkaW** [comment]
IIRC Next.js' `edge-runtime` is compliant with the whatwg fetch spec. And in the spec, there is no `retry` and you will have to manually handle the error recovery.

Have you tried https://npm.im/p-retry library to handle retry?

**Comment by chendong-xie** [comment]
https://npm.im/p-retry is work tks!

**Comment by ijjk** [comment]
Closing per above
