### ISSUE TITLE
props from getStaticProps disappear upon new deployment

### ISSUE THREAD

**Issue by javlund** [vercel/next.js#39535]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Docker on Kubernetes (GKE), using a slightly modified version of the "official" Docker script

### Describe the Bug

We are using static generation to generate practically all our pages. They fetch data from a CMS (Strapi), populate it in `getStaticProps` and pass it on to be used by the React page components. We are using ISR with a 30 sec interval, and some pages are also updated on-demand.

What we have discovered is that after a new deployment to our servers (a new pod spun up in Kubernetes), anyone who is on a page in the website **and does not reload** will, upon clicking a link to move to different page, be presented with this message: `Application error: a client-side exception has occurred (see the browser console for more information).`

Looking at the console, it appears that what happens is that the `props` expected by the React page component are not populated, so we get `undefined` or `null` or whatnot in instead. The page component expects the props to be available, and everything then breaks.

Reloading the page "fixes" the problem. Probably as this gets a fresh copy of all relevant files.

Are we the only ones experiencing this? Is it due to some faulty configuration on our end or is this a common issue? If the latter, how do people get around it? Check for commit SHAs and trigger a reload, or something?

### Expected Behavior

I would expect (or hope) that the page continued to work as expected across new deployments without needing a reload.

### Link to reproduction

Sorry, I have none

### To Reproduce

I have tried, but I haven't been able to reproduce this locally.

To reproduce, use SSG and make a new deployment of an existing app on a server while having a page open in a browser. When the deployment is done, try clicking a link to another page.

**Comment by javlund** [comment]
On closer inspection, it seems that it's trying to load a bunch of `json` files from the `_next/data` folder, but getting 404s. Likely due to the fact that the hash has changed. Why I cannot reproduce this locally eludes me, though.

**Comment by javlund** [comment]
Locally, it seems to pick up that the JSONs are failing/returning 404 and forces a reload once the link is clicked. For some reason this doesn't seem to happen on our environments, though.

**Comment by javlund** [comment]
Hi @balazsorban44, thanks for helping out.

It's a general issue that does not seem related to the actual contents of the props. I'm having a very hard time to provide a reproduction as it seems to only happen when deployed behind a load balancer and only after a redeploy.

Can you help me out by telling me exactly what conditions `next/link` requires in order to trigger the reload, possibly point me to the place in code where it happens? The crux of the issue seems to be that the reload for some reason isn't triggered on the envs even though it should be (and is when I run it locally).

**Comment by javlund** [comment]
Hi again - I thought I had done a build with Canary but apparently I hadn't done my testing rigorously enough. The issue seems to have been fixed in Canary.

I'm still flabbergasted as to why it was an issue on our envs but not locally.

My apologies for the false alarm.

**Comment by ijjk** [comment]
Thanks for confirming, sounds like we can close this as it's working in canary.
