### ISSUE TITLE
E-connection reset error on getInitialProps when requestiing from backend server 

### ISSUE THREAD

**Issue by rajneesh3923** [vercel/next.js#39545]
I'm stuck with this as well.. Any news?

I tried with NodeJs `12`, `14`, and `15` without luck.

It happens when I run my nextjs (`v10.0.7`) app in a Debian `slim-buster` docker container with env `production`.

It cannot reproduce this locally.

_Originally posted by @feluxe in https://github.com/vercel/next.js/issues/9006#issuecomment-787116437_

**Comment by balazsorban44** [comment]
Please follow the bug report template.
