### ISSUE TITLE
Docs: README doesn't coincide with what is in the example code (pages/_app.js)

### ISSUE THREAD

**Issue by thebuddysystem** [vercel/next.js#39555]
### What is the improvement or update you wish to see?

I would like to see the documentation in the README be consistent with what's in the code. 

In the [next.js/examples/with-redux-thunk](https://github.com/vercel/next.js/tree/canary/examples/with-redux-thunk/) README.md, it states: 

`... The MyApp component is wrapped in a withReduxStore function ...`

However, in the code at `pages/_app.js` there is no `MyApp` component nor is there a `withReduxStore` function, so it's really confusing.  I'm guessing that got replaced with the hook in _app.js called `useStore`??

Additionally, it states: 
```1.) pages/index.js will utilize connect from react-redux ... ```
which seems wrong, because there's no call to any `connect` function in the actual code.

Also the last sentence states: 
```... then in store.js change (line 19) store.replaceReducer(createNextReducer(initialState)) to store.replaceReducer(createNextReducer). ```
that also seems wrong because i can't find `store.replaceReducer` anywhere.

### Is there any context that might help us understand?

Just read the README and try to follow along in the code.  

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/tree/canary/examples/with-redux-thunk/README.md

**Comment by jmorel88** [comment]
@balazsorban44 I'll be happy to take this one.

**Comment by mayanhavoc** [comment]
Is this issue still open? Seems like the desired changes in the documentation have been made.

**Comment by thebuddysystem** [comment]
Oh, should i be closing it, since i opened it?  
In any case, Thanks everyone!!!
