### ISSUE TITLE
`next lint` does not match IDE (and ESLint) linting

### ISSUE THREAD

**Issue by nbouvrette** [vercel/next.js#39565]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 14.18.3
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

with-eslint

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

When using other ESLint plugins, VSCode will report linting issues in certain files (`next.config.js` for example) which will not be reported by `next lint`:

```console
> next lint

info  - Loaded env from .env.production

✔ No ESLint warnings or errors
```

While in your IDE (and if you run the normal `lint`):

```console
next.config.js
   1:28  error  Do not use "require"  unicorn/prefer-module
   5:23  error  Do not use "require"  unicorn/prefer-module
  19:1   error  Do not use "module"   unicorn/prefer-module

✖ 3 problems (3 errors, 0 warnings)
```

### Expected Behavior

I would expect the VSCode to be aligned with `next lint`

There might be some valid linting rules that someone wants to perform on `next.config.js` and `next lint` will not catch those issues which means that someone would need to manually open the file in their IDE or run the normal `lint`.

### To Reproduce

`npm i -D eslint-plugin-unicorn`

Then configure this in your `.eslintrc.json`:

```
{
  "extends": [
    "next/core-web-vitals",
    "plugin:unicorn/recommended"
  ]
}
```
Open `next.config.js` and see the errors in the IDE (you can also run `eslint --ext .js --ext .jsx --ext .ts --ext .tsx .`)

Run `npm run lint` (running `next lint`) and you will see no error in `next.config.js`

**Comment by balazsorban44** [comment]
`next.config.js` is not linted by default. See https://nextjs.org/docs/basic-features/eslint#linting-custom-directories-and-files

**Comment by nbouvrette** [comment]
It's fine but the way it's implemented prevents anyone from relying solely on `next lint`, as you might want to use linting in `next.config.js`.

Is there a specific reason some files are being excluded from `next lint` while your IDE, using `eslint` will still show linting errors?
