### ISSUE TITLE
`next/image` fails to load when using `preact`

### ISSUE THREAD

**Issue by PsyGik** [vercel/next.js#39585]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64
    Binaries:
      Node: 16.11.0
      npm: 8.0.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.0
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Chrome, Firefox Developer Edition

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

When using `preact` for production build, `next/image` fails to load with following errors in the browser console:

```
Uncaught TypeError: can't access property "transition", ReactCurrentBatchConfig$1 is undefined
    React 6
    renderReactElement index.js:411
Uncaught (in promise) Error: Cancel rendering route
    lastRenderReject index.js:628
Uncaught (in promise) TypeError: can't access property "transition", ReactCurrentBatchConfig$1 is undefined
    React 6
    renderReactElement index.js:411
```

Digging more into it, looks like it's an issue with `useTransition` hook which is available in React 18, but [unsupported in preact](https://github.com/preactjs/preact/pull/3510/files).

But I'm not sure why this affects the `next/image` component. As far as I can see, the `useTransition` hook is used in the `Link` component and not in the `next/image` component. 

Possible relevant links:
- https://github.com/vercel/next.js/search?q=startTransition&type=code
- https://stackoverflow.com/questions/71959778/error-in-production-after-upgrading-to-react-18
- https://github.com/preactjs/preact/pull/3510/files

### Expected Behavior

`next/image` must load. There should be no errors in the console.

### Link to reproduction

https://github.com/PsyGik/next-preact-issue

### To Reproduce

- Clone the repo
- Install dependencies `npm install`
- Start dev server `npm run dev`
- Observe that `Image` component does not load

Goto `next.config.js`, and remove the `preact` config. Repeat the above steps and see `Image` component loads.

**Comment by SukkaW** [comment]
@PsyGik It seems that you are not using `next-plugin-preact`: https://github.com/preactjs/next-plugin-preact.

`next-plugin-preact` is maintained by the Preact team with the help of the Next.js team.

I have tweaked your reproduction to use `next-plugin-preact` and the issue is gone.
