### ISSUE TITLE
Runtime error when components are rendered by Streaming SSR

### ISSUE THREAD

**Issue by AppleNectar** [vercel/next.js#39589]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 16.15.0
      npm: 8.13.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Microsoft Edge 104.0.1293.54

### How are you deploying your application? (if relevant)

Running locally (npm run dev)

### Describe the Bug

I apologize if this is due to my lack of understanding of Next.js and React.

A runtime error will occur when all of the following conditions are met.

1. Rendering with SSR (export getServerSideProps function)
2. Use child components that throw Promise in page components (wrap with Suspense)
3. Use the useEffect hook in the parent component (i.e., in this case, the page component) and call an asynchronous function in the callback (e.g., setTimeout, fetch and more)
4. In the asynchronous function described above, the page component sets values to the states previously declared in useState

Error message is as follows:
```
Unhandled Runtime Error
Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.
```

### Expected Behavior

Runtime error does not occur.

### Link to reproduction

https://codesandbox.io/s/next-js-hydration-issue-inbwoh?file=/pages/index.tsx

### To Reproduce

TypeScript is used.

1. Create `pages/index.tsx` with the following contents
2. Run it with `npm run dev`
3. Access `http://localhost:3000` in browser

* pages/index.tsx

```tsx
import { GetServerSideProps, NextPage } from "next";
import { Suspense } from "react";

type Props = {};

let data: string;

const SampleComponent = (): JSX.Element => {
  // This is equivalent to the behavior of the fetching library corresponding to suspense.
  if (!data) {
    throw new Promise(async (resolve) => {
      await new Promise((resolve) => setTimeout(resolve, 200));

      data = "resolved!";

      resolve(true);
    });
  }

  return <div>{data}</div>;
};

const IndexPage: NextPage<Props> = (props) => {
  const [value, setValue] = useState<number>();

  useEffect(() => {
    // When this process runs, a runtime error occurs.
    setTimeout(() => {
      setValue(1);
    }, 10);
  }, []);

  return (
    <div>
      {/* If the child is not rendered here (i.e., it is a normal SSR), no error occurs. */}
      <Suspense fallback={<div>Loading...</div>}>
        <SampleComponent />
      </Suspense>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  return {
    props: {}
  };
};

export default IndexPage;
```

**Comment by shuding** [comment]
Like the error said, it's better to wrap the state update with `startTransition`:

```
import { startTransition } from 'react'

// ...
useEffect(() => {
  setTimeout(() => {
    startTransition(() => setValue(1))
  }, 10)
}, [])
```
