### ISSUE TITLE
Cloudinary loader does not follow cloudinary convention for adding transforms params

### ISSUE THREAD

**Issue by matthewlilley** [vercel/next.js#39588]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

n/a

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

I'm having some issues with cloudinary image loader which is included with Next.js. If I want to invalidate the image via cloudinary CLI I cannot, because the ordering does not match what happens under the hood with Next.js.

e.g. I have this url:
https://res.cloudinary.com/sushi-cdn/image/fetch/f_auto,c_limit,w_64,q_auto/https://raw.githubusercontent.com/sushiswap/list/master/logos/token-logos/network/ethereum/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2.jpg

I want to invalidate so I use:
cld uploader explicit "https://raw.githubusercontent.com/sushiswap/list/master/logos/token-logos/network/ethereum/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2.jpg" type="fetch" invalidate="true" eager='[{  "fetch_format": "auto", "crop": "limit", "width": 64, "quality": "auto" }]'

but this will invalidate
http://res.cloudinary.com/sushi-cdn/image/fetch/c_limit,f_auto,q_auto,w_64/https://raw.githubusercontent.com/sushiswap/list/master/logos/token-logos/network/ethereum/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2.jpg

the params "c_limit,f_auto,q_auto,w_64" are sorted alphabetically by Cloudinary

### Expected Behavior

I think Next.js should probably be following the cloudinary convention since it's automatically adding these params to the url and there doesn't appear to be a way to deal with it right now, making invalidation very difficult.

### Link to reproduction

n/a

### To Reproduce

n/a

**Comment by SukkaW** [comment]
@matthewlilley It seems to be a Cloudinary CLI/API issue, not a Next.js issue?

It is the Cloudinary API and CLI that does the params sorting.

**Comment by matthewlilley** [comment]
Cloudinary is supported 1st class by Next.js but does not follow the convention it uses for URL building. There is also no way to configure this on either end which makes invalidation practically impossible.

**Comment by SukkaW** [comment]
@matthewlilley Cloudinary doesn't require the transformation params to be sorted. If Cloudinary doesn't support un-sorted transformation params, the image shouldn't be able to load.

As I said, it is the Cloudinary CLI that can't invalidate the cached image. What Next.js' built-in loader does is load the image from Cloudinary, and I don't see there is any bug here. You should report the issue to Cloudinary instead.

**Comment by balazsorban44** [comment]
Closing as per the above suggestion.
