### ISSUE TITLE
npm run dev is not running and terminal shows missing node file with many trails

### ISSUE THREAD

**Issue by Mo-Aziz** [vercel/next.js#39624]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

name": "twitter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^12.2.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
     "node: "18.7.0",
    "eslint": "8.21.0",
    "eslint-config-next": "12.2.5"
  },

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

every time i try to run the liver server to work on the app, the terminal throws this error.

Cannot find module 'C:\Users\MJ\Desktop\React\june 2022 projects\next\dist\bin\next'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) 
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.7.0

### Expected Behavior

The live server should start.

### Link to reproduction

N/A

### To Reproduce

Just run npm run dev

**Comment by thanhtutzaw** [comment]
rm -r .next   ( this command delete .next file)
and re build  ( npm run build ) ( npm start)

**Comment by samcx** [comment]
Closing since this issue is stale and missing a <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture>.
