### ISSUE TITLE
Found invalid GitHub URL -- Again

### ISSUE THREAD

**Issue by pdini** [vercel/next.js#39642]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.7.0
      npm: 8.15.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

The command
`npx create-next-app -e https://github.com/0xdevnet/juno-dapp-starter/ my-juno-dapp`
returns
`Found invalid GitHub URL: "https://github.com/0xdevnet/juno-dapp-starter/". Please fix the URL and try again.`
I tried also the url `https://github.com/0xkdavid/juno-dapp-starter/` suggested in the Readme with the same result.

This problem has come up before ([here](https://github.com/vercel/next.js/issues/19277) and [here](https://github.com/vercel/next.js/issues/34073)) and they were described as resolved.

### Expected Behavior

I expect the installation to proceed and the "my-juno-dapp" folder to be created.

### Link to reproduction

https://github.com/vercel/next.js/issues/34073

### To Reproduce

Type `npx create-next-app -e https://github.com/0xdevnet/juno-dapp-starter/ my-juno-dapp` in the CLI

**Comment by SukkaW** [comment]
The issue is caused by the trailing slash of the URL. Remove the trailing slash the URL will work:

```
npx create-next-app -e https://github.com/0xdevnet/juno-dapp-starter my-juno-dapp
```

**Comment by pdini** [comment]
Thanks that worked!

**Comment by SukkaW** [comment]
I have created a PR (#39665) to let create-next-app be able to handle GitHub URL with a trailing slash.
