### ISSUE TITLE
Next.js Dev Overlay bloats main chunk in production

### ISSUE THREAD

**Issue by lkenny97** [vercel/next.js#39643]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.8.0
      npm: 8.11.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

After building and starting the next application I can clearly see that next/react-dev-overlay is in the main chunk while it is unused. This lowers the performance score of the page in the lighthouse.

**See third chunk (The brown one)**
![Screen Shot 2022-08-16 at 12 34 31](https://user-images.githubusercontent.com/32220582/184848837-f593d3cb-0b1a-468e-a508-a4e8bca876dc.png)

That same chunk has high unused weight and dev overlay is a big part of it (I know this because when I separated it from the main chunk it was still called and was the main unused JS during production)
<img width="1106" alt="Screen Shot 2022-08-16 at 12 35 30" src="https://user-images.githubusercontent.com/32220582/184848882-fbcf652b-b4f3-4ec0-82dc-22422c8ea05b.png">

### Expected Behavior

As far as I know dev overlay is used only during development. If this is the case it should be excluded from the main chunk. I tried to separate it from the main chunk using

```
config.optimization.splitChunks.cacheGroups.devOverlay = {
        test: /[\\/]node_modules[\\/]next[\\/]dist[\\/]compiled[\\/]@next[\\/](react-dev-overlay)[\\/]/,
        name: "devOverlay",
        chunks: "all",
        priority: -20
      }
```

but the separated chunk was still called during page build.

### Link to reproduction

-

### To Reproduce

1. Create any nextjs project
2. Use bundle analyzer to see main chunk
3. Build and next start the application
4. See that there is a dev overlay in that chunk

**Comment by ijjk** [comment]
Hi, can you provide a reproduction where you are seeing this? This doesn't appear to be the case in the latest version of Next.js `v12.2.5`. 


<img width="1277" alt="Screen Shot 2022-08-16 at 12 26 18 PM" src="https://user-images.githubusercontent.com/22380829/184868702-36add38a-c605-472b-a822-adb3f3b68aac.png">

**Comment by lkenny97** [comment]
I have the same issue on 12.2.6-canary.0. I will try to provide a reproduction tomorrow. Please do not close the issue until that :)

**Comment by lkenny97** [comment]
> Hi, can you provide a reproduction where you are seeing this? This doesn't appear to be the case in the latest version of Next.js `v12.2.5`.

Here is the reproduction link: https://github.com/lkenny97/dev-overlay-reproduction
I also found the issue. Dev overlay stays in the main chunk when .babelrc is added to the project.

**Comment by ijjk** [comment]
It looks like this due to the `minify-simplify` babel plugin being added in your `.babelrc` so it doesn't appear to be caused by Next.js itself.
