### ISSUE TITLE
next-dev.js?3515:20 Warning: Extra attributes from the server 

### ISSUE THREAD

**Issue by sytpb** [vercel/next.js#39678]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Information:

using prism in NextJs . 

```json
"dependencies": {
"babel-plugin-prismjs": "^2.1.0",
"next": "12.2.4",
"prismjs": "^1.28.0",
"react": "18.2.0",
"react-dom": "18.2.0"
},

babelrc

"plugins": [
  [
    "prismjs",
    {
      "languages": ["javascript", "css", "markup"],
      "plugins": ["line-numbers"],
      "theme": "twilight",
      "css": true
    }
  ]
]
```

### Describe the Bug

code as the this blog to setup.

https://hackernoon.com/using-prismjs-as-a-syntax-highlighter-in-react

 i got a warning .

![image](https://user-images.githubusercontent.com/12178686/185087854-1cd31d75-bfa6-4fd6-b1b5-1627cd20e2bd.png)

```js
import React, { useEffect } from "react";
import Prism from "prismjs";


export default function Code({ code, language }) {
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  
  return (
    <div>

      <h2> Code Syntax Block {language}</h2>
      <pre>
        <code className={`language-${language}`}>{code}</code>
      </pre>

    </div>
  );
}
```

until now i just got the warning ,but adding some code to this , it turned weird ,  

```js
import React, { useEffect } from "react";
import Prism from "prismjs";


export default function Code({ code, language }) {
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  
  return (
    <div>
      {/* <div>it weird after adding this</div> */}                         
      <h2> Code Syntax Block {language}</h2>
      <pre>
        <code className={`language-${language}`}>{code}</code>
      </pre>

    </div>
  );
}
```

i got error like this . 

![image](https://user-images.githubusercontent.com/12178686/185091441-836bfe68-8ba8-4cca-84e5-39f73fee6dfc.png)

### Expected Behavior

no warning no error 

### Link to reproduction

sorry no reprodcution 

### To Reproduce

[111](https://hackernoon.com/using-prismjs-as-a-syntax-highlighter-in-react)

**Comment by balazsorban44** [comment]
Prism seems to inject those attributes client-side, which causes a hydration mismatch because the attributes are missing on the server prepass.

To fix this, you can import `Code` with `next/dynamic` and set `ssr: false` so it will be ignored server-side. See the docs: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by sytpb** [comment]
ok great ! thanks a lot .
