### ISSUE TITLE
Dynamic routes not working when app is exported to static files

### ISSUE THREAD

**Issue by AshConnolly** [vercel/next.js#39696]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.18.0
      npm: 8.5.4
      Yarn: 1.22.15
      pnpm: 7.6.0
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

next export

### Describe the Bug

I have a site that is statically exported, and has dynamic routes.

This site works fine in dev mode. However if I build & export it, and then [serve](https://www.npmjs.com/package/serve) the static files, it has an isssue.

**You can go to the site root and click on a link, which will take you to a dynamic post page like `http://localhost:3000/post/1` and will work, but if you refresh the page (or visit directly) it 404s.**

![Kapture 2022-08-17 at 16 04 39](https://user-images.githubusercontent.com/6549140/185214180-7fdf8d35-7b47-4f65-8ddc-d33f7d59a7be.gif)

**Why is this? Do dynamic routes, that need to access the router query object, not work when statically exported?**

[The dynamic route docs](https://nextjs.org/docs/routing/dynamic-routes) don't mention any caveats to dynamic routes when used with static export.

## The code:

Taking the [next.js static example](https://github.com/vercel/next.js/tree/canary/examples/with-static-export) to start with, I edited it’s `pages/post/[id].tsx` by removing the `getStaticPaths` and `getStaticProps` (as I don’t require build time static generation, and there are potentially millions of pages) and added clientside fetching on mount. I’m grabbing the [router.query.id](http://router.query.id/) value and using it to fetch data:

⚡ [Codesandbox here](https://codesandbox.io/s/hungry-wilson-t8rvlh?file=/pages/post/%5Bid%5D.tsx) (which works fine as its running in dev, not exported served files)

```tsx
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { GetPost } from '../../lib/postdata_api'
import { PostData } from '../../types/postdata'

const Post = () => {
  const [postData, setPostData] = useState<null | PostData>(null)
  const router = useRouter()
  const id = router.query.id as string
  const fetchData = async () => setPostData(await GetPost(id))

  useEffect(() => {
    if (!router.isReady) return
    fetchData()
  }, [router, router.isReady])

  if (!postData) return 'Loading...'

  return (
    <main>
      <Head>
        <title>{postData.title}</title>
      </Head>

      <h1>{postData.title}</h1>

      <p>{postData.body}</p>

      <Link href="/">
        <a>Go back to home</a>
      </Link>
    </main>
  )
}

export default Post
```

### Expected Behavior

I expected it to behave the as it does it dev. Meaning a user can:
- click a link on the root page
- view the dynamic post page eg `/post/1`
- refresh / directly visit this post (without it 404ing)

### Link to reproduction

https://codesandbox.io/s/hungry-wilson-t8rvlh?file=/pages/post/%5Bid%5D.tsx

### To Reproduce

 - Download the [code sandbox](https://codesandbox.io/s/hungry-wilson-t8rvlh?file=/pages/post/%5Bid%5D.tsx) or [github repo](https://github.com/AshConnolly/nextjs-dynamic-route-export-issue)
 - run `npm run export && serve out`
 - visit `http://localhost:3000`
 - click a link to a post
 - press refresh to see the 404

**Comment by AshConnolly** [comment]
Added a gif showing the behaviour to help explain.

**Comment by wwwdepot** [comment]
For serving SPAs, you need to pass the `-s` options to rewrite requests to `/index.html`.

```bash
serve -s out
```

**Comment by SukkaW** [comment]
@AshConnolly Dynamic routes without `getStaticPaths` can not be served directly.

Without `getStaticPaths`, Next.js doesn't know which path could be included in this dynamic routes. You should either:

- Use `next start` to serve your app
- Configure your web server to properly rewrite incoming requests to the specific HTML file.

**Comment by AshConnolly** [comment]
> For serving SPAs, you need to pass the `-s` options to rewrite requests to `/index.html`.
> 
> ```shell
> serve -s out
> ```

Thanks for the help @wwwdepot. I understand why you would need to do that but it didn't resolve it. Same issue still present :/

**Comment by AshConnolly** [comment]
Thanks for the reply @SukkaW!
> * Use `next start` to serve your app
That didn't solve it unfortunately.
> Configure your web server to properly rewrite incoming requests to the specific path (/post/[id].html)
Good suggestion, but it seems less than ideal that I would need to do that for all dynamic pages.

**Comment by SukkaW** [comment]
> > * Use `next start` to serve your app
> 
> That didn't solve it unfortunately.

Instead of `next build && next export`, do `next build && next start`. Check `http://localhost:3000` to see if everything is working.

**Comment by AshConnolly** [comment]
Thanks for replying @SukkaW!

> Instead of next build && next export -o build/ && serve build/, do next build && next start. Check http://localhost:3000 to see if everything is working.

Yeh that works fine. The same result as dev mode (can go to posts directly). 

> When you use next start, Next.js' built-in server is doing dynamic routing for you. But if you are deploying without using Next.js' built-in server, you have to handle rewrite yourself.

I see. Thanks for explaining! How would I achieve that? Do you know how to get that codesandbox example working when exported?

Also noticed [the docs say](https://nextjs.org/docs/advanced-features/static-html-export) rewrites are not supported for static export.

**Does that mean what I'm trying to do is impossible?** It's very confusing as these caveats aren't mentioned in the dynamic routes or in the static export documentation.

**Comment by SukkaW** [comment]
> presumably I cannot use dynamic routes and do client side fetching? That would seem odd if it's impossible...

As I said before, there is only a `[id].html` under your `out/posts` (or `build/posts`) folder.

Only the Next.js server knows what `[id].html` means (and can translate `[id]` to your `useRouter().id`). Other servers (Nginx, GitHub Pages, etc.) don't know `[id].html` has special meanings.

**Comment by AshConnolly** [comment]
That makes sense! Thank you so much for the help @SukkaW! Really appreciate it! 😄

**Comment by SukkaW** [comment]
> That makes sense! Thank you so much for the help @SukkaW! Really appreciate it! 😄

Don't mention it.

And, even with millions of pages, you can still use SSR (and server-side data fetching)! Check out Next.js documentation of [ISR](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration).

The static export + client-side fetching should only be a last resort when static hosting is your only option (GitHub Pages, Cloudflare Pages, etc.).
