### ISSUE TITLE
`fs` cannot be statically imported in pages

### ISSUE THREAD

**Issue by SheetJSDev** [vercel/next.js#39700]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 18.7.0
      npm: 8.15.0
      Yarn: N/A
      pnpm: 7.6.0
    Relevant packages:
      next: 12.2.6-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

npx next@canary

### Describe the Bug

A top-level import of `fs` in a page results in the error:

```
Module not found: Can't resolve 'fs'
```

The docs (https://nextjs.org/docs/api-reference/data-fetching/get-static-props#reading-files-use-processcwd) use `fs` freely.  If a webpack config override is required, it probably should be noted in the docs.

Note that the error does not show, and the module works as expected, if `fs` is dynamically imported from `getStaticProps`

### Expected Behavior

One of the following:

A) Importing `fs` from top level should not error

B) Importing `fs` from top level does error, but a webpack config override is needed.  The docs page should be updated to note the requirement

C) Importing `fs` from top level does error, but apps should use dynamic `fs` import (which does work in practice, see the warning in https://docs.sheetjs.com/docs/demos/content#nextjs).  The docs page should be updated to show the dynamic import.

### Link to reproduction

https://github.com/SheetJSDev/next-fs-issue

### To Reproduce

```bash
git clone https://github.com/SheetJSDev/next-fs-issue
cd next-fs-issue
npm i
npx next@canary
```

Then use a web browser to access http://localhost:3000/

The first time you load, the page will be completely blank and the console will show the error

```
wait  - compiling /_error (client and server)...
error - ./pages/index.js:1:0
Module not found: Can't resolve 'fs'
> 1 | import { readFile } from 'fs';
  2 | 
  3 | export default function Index({type, html}) { return ( <div>Ho</div> ); }
  4 | 
```

<img width="560" alt="next" src="https://user-images.githubusercontent.com/6070939/185220394-07dca9a9-800c-4e9b-86b0-a2fe0ead0598.png">

The same error shows if you add a `getStaticProps` method to `pages/index.js`

**Comment by SukkaW** [comment]
The reason behind  the webpack doesn't tree shake the import of `fs` import is `fs` is considered a side effect.

And the way Next.js strip server-side only import is to determine if the import is only used inside `getStaticProps`, `getStaticPaths`, or `getServerSideProps`.

So:

- This will not work:

```jsx
import { readFile } from 'fs';

export default function Index({type, html}) { return ( <div>Ho</div> ); }
```

- This will not work either:

```jsx
import { readFile } from 'fs';

export default function Index({type, html}) { return ( <div>Ho</div> ); }

export const getStaticProps = () => {
  return {
    props: {}
  }
};
```

- Only this will work:

```jsx
import { readFile } from 'fs';

export default function Index({type, html}) { return ( <div>Ho</div> ); }

export const getStaticProps = () => {
  readFile;

  return {
    props: {}
  }
};
```

**Comment by balazsorban44** [comment]
Closing as per the above explanation. You'll need to use the `fs` import inside the data fetching method for Next.js to be able to detect where the import is being used.
