### ISSUE TITLE
next/link with basepath not working when wrapping an anchor with a Link

### ISSUE THREAD

**Issue by giovanni-caiazzo** [vercel/next.js#39728]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022
    Binaries:
      Node: 16.15.1
      npm: 8.12.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.2.2
      react: 18.1.0
      react-dom: 18.1.0

warn  - Latest canary version not detected, detected: "12.2.2", newest: "12.2.6-canary.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

Firefox 103.0.2

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

In my app I have a basepath defined in `next.config.js` and I am constructing a `CustomLink` component used throughout the app like this:
```
const CustomLink = forwardRef(
  ({ to, children, className, ...props }: IProps, ref: any) => {
    return (
      <Link href={to}>
        <a href={to} ref={ref} className={className} {...props}>
          {children}
        </a>
      </Link>
    );
  }
);
```
When the anchor tag has the href defined, clicking on the link and opening it in the same tab works, while when one copies the link or tries to open it in a new tab with ctrl/cmd+click or with a middle mouse click the basepath is not applied.
Removing the href from the anchor tag fixes the problem and makes the basepath correctly apply to the link in all cases.

### Expected Behavior

I would expect that the href of the anchor tag should not change the behavior of the next Link so unpredictably

### Link to reproduction

https://codesandbox.io/s/distracted-sun-ozwptk?file=/components/CustomLink.tsx

### To Reproduce

First, navigate to the `/resources` page.
The provided link has the described problem (even hovering on it shows the link without the basepath). When `href={to}` is removed from the anchor tag of `CustomLink` the link works fine.

**Comment by jeferson-sb** [comment]
@giovanni-caiazzo The issue here is that `Link` component automatically resolves with the basepath, while anchor tag alone doesn't, so you need to remove the `href` from the anchor and use the `passHref` property to `<Link>` in order to work

**Comment by ijjk** [comment]
Closing as the above comment is correct and `next/link` automatically handles the `basePath` meanwhile you are overriding this on the `a` tag.

**Comment by giovanni-caiazzo** [comment]
Would it be possible to add a warning, or a note in the docs? From the link's behavior it was not obvious what was wrong in the implementation. It could save some time to devs in the future.
If a note exists and I missed it, apologies...

**Comment by ijjk** [comment]
It seems we don't have a warning for this, feel free to open a PR adding this for development mode! 

The related code where this could be added is here https://github.com/vercel/next.js/blob/b6bbbc813f6ce39b2c65aa0b72fbfca2ab5cbad1/packages/next/client/link.tsx#L505

Something like the below should be sufficient with a test case:
```js
if (process.env.NODE_ENV === 'development') {
 if ((child.type === 'a' && ('href' in child.props)) {
   console.warn(`next/link has anchor child with "href": ${child.props.href} which overrides next/link's handling for "href", this should be removed in favor of "passHref"`)
  }
}
```

**Comment by jeferson-sb** [comment]
@ijjk I can do that
