### ISSUE TITLE
Dynamic route case insensitive

### ISSUE THREAD

**Issue by FelHa** [vercel/next.js#39750]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.1
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Dynamic routes are case insensitive. Both `/dynamic/foo` and `dynamic/Foo` serve the same document, when the app is built and started.

### Expected Behavior

Dynamic routes are case sensitive. 

### Link to reproduction

https://github.com/FelHa/nextjs-case-insensitive

### To Reproduce

* Clone linked repository
* `npm run build`
* `npm run start`
* Go to `/About` -> 404
* Go to `/dynamic/foo` -> 200
* Go to `/dynamic/FOO` -> 200
* Reload page -> 404

**Comment by balazsorban44** [comment]
It looks like you are rendering `router.asPath`, which can cause hydration mismatches that leads to rendering issues, which is mentioned in the docs: https://nextjs.org/docs/api-reference/next/router#router-object

> Using the `asPath` field may lead to a mismatch between client and server if the page is rendered using server-side rendering or [automatic static optimization](https://nextjs.org/docs/advanced-features/automatic-static-optimization). Avoid using `asPath` until the `isReady` field is `true`.

You can also check `router.isFallback` to render a loading page when the given dynamic page has not been rendered before
