### ISSUE TITLE
Error accessing request.headers middleware

### ISSUE THREAD

**Issue by edihasrin** [vercel/next.js#39765]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

I tried to access the **request.headers** in the **Next.js Middleware** but the data is not showing up.

If I access something else, the data can appear

if i display headers it gets an error

    Server Error
    TypeError: Cannot delete property 'Symbol(set-cookie)' of #<HeadersList2>

 

1. Img 1 = Code in **Middleware**
 2. Img 2 = Fill in the data in the **request** variable
 3. Img 3 = Error when I display `request.headers`

[Img 1][1]     [Img 2][2]     [Img 3][3]

  [1]: https://i.stack.imgur.com/P158F.png
  [2]: https://i.stack.imgur.com/m90iX.png
  [3]: https://i.stack.imgur.com/9hNHJ.png

### Expected Behavior

i can access `request.headers.referer`

### Link to reproduction

-

### To Reproduce

-

**Comment by akigugale** [comment]
Getting the same error too

**Comment by eposha** [comment]
Same problem

**Comment by aliaksandr-savitski** [comment]
I had the same problem and seems like accessing directly `request.headers`  object throws that type of error, which is counter intuitive at all, and hard to debug for FE person, maybe a specific error handling for that case would be a good idea?

The solution is to ether access needed header by `request.headers.get('header-name-here')` . If you need to list them, you may use `request.headers.values(callback)`. Thank should solve the issue

**Comment by edihasrin** [comment]
> 

works, thanks
