### ISSUE TITLE
Next dev server not detecting changes when using `experimantal-edge` runtime and `getServerSideProps`

### ISSUE THREAD

**Issue by remorses** [vercel/next.js#39777]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.14.0
      Yarn: 1.22.17
      pnpm: 7.4.0
    Relevant packages:
      next: 12.2.6-canary.1
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Code changes inside `getServerSideProps` when using edge runtime won't take effect on page reload.

You will need to restart the next server to see changes

### Expected Behavior

Changing code inside `getServerSideProps` should get picked up by next

### Link to reproduction

https://github.com/remorses/try-next-getserversideprops-edge

### To Reproduce

```
pnpm i
pnpm dev
# try changing code inside `getServerSideProps` and reload the page, changes won't take effect
```

**Comment by remorses** [comment]
Another think not clear to me is what type will `context.req` have when using edge runtime, will it be a `NextResponse` like in middleware or a wrapper using the node.js req type?

**Comment by mrafei** [comment]
I have confirmed that `getServerSideProps` is not picked up by next only if it is defined as a function statement, but if you define it as a function expression it will work as expected. It is still a bug and should be fixed, for now you can use this:

`export const getServerSideProps = (context: GetServerSidePropsContext) => {
    // handle server side
}`

**Comment by remorses** [comment]
@mrafei i tried using a function expression but it has the same problem for me

**Comment by shuding** [comment]
> Another think not clear to me is what type will `context.req` have when using edge runtime, will it be a `NextResponse` like in middleware or a wrapper using the node.js req type?

It is currently a wrapper that has the similar interface as the Node.js `HTTPIncomingMessage`.

**Comment by remorses** [comment]
Fixed in latest canary
