### ISSUE TITLE
If `basePath` is set, running `next build` will cause downtime

### ISSUE THREAD

**Issue by u3u** [vercel/next.js#39795]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```sh
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
Binaries:
  Node: 16.16.0
  npm: 8.11.0
  Yarn: 1.22.19
  pnpm: 7.8.0
Relevant packages:
  next: 12.2.6-canary.1
  eslint-config-next: 12.2.5
  react: 17.0.2
  react-dom: 17.0.2
```

### Describe the Bug

If `basePath` is set, the new `buildId` will be updated after running `next build` before restarting, which will cause a 404 in `_buildManifest.js` and `_ssgManifest.js`

<img width="709" alt="image" src="https://user-images.githubusercontent.com/20062482/185783707-786f88a8-1cc1-49ee-8270-f4f556d2f388.png">

### Expected Behavior

Whether or not `basePath` is set, `buildId` should be updated after restarting the service

### To Reproduce

1. run `npx create-next-app --ts`
2. change `basePath` in `next.config.js`
3. run `next build && next start`
4. keep the service started run `next build` then refresh the page

**Comment by ijjk** [comment]
Hi, are you generating a custom `buildId` with `generateBuildId` if so this is most likely the issue as each build generates a unique id in Next.js by default and when fetching a resource fails we trigger a hard navigation.

**Comment by u3u** [comment]
@ijjk No, I just modified the `basePath`
https://github.com/u3u/nextjs-basepath-bug

**Comment by u3u** [comment]
Sorry, I just tested it again and it doesn't seem to be related to `basePath`. Running `next build` with or without `basePath` gives the same result. The reason for the difference is that I use the [`next-translate`](https://github.com/aralroca/next-translate) plugin. After using it, running `next build` `_buildManifest.js` and `_ssgManifest.js` does not bring up 404, amazing! 😮

Using `basePath` to cause downtime may be a server proxy or CDN issue 😢
