### ISSUE TITLE
Could not use `next/future/image` with imported image and fill layout

### ISSUE THREAD

**Issue by armandabric** [vercel/next.js#39807]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: linux
  Arch: x64
  Version: Ubuntu 20.04.0 LTS Mon Aug 22 2022 11:46:31 GMT+0200 (Central European Summer Time)
Binaries:
  Node: 16.14.2
  npm: 7.17.0
  Yarn: 1.22.10
  pnpm: 7.9.4-0
Relevant packages:
  next: 12.2.6-canary.1
  eslint-config-next: N/A
  react: 17.0.1
  react-dom: 17.0.1
```

### Describe the Bug

When using an imported image and the fill layout with the new image component it throw an error:

```
Error: Image with src "/_next/static/media/bar.ddd5bcf8.svg" has both "width" and "fill" properties. Only one should be used.
```

### Expected Behavior

The [doc](https://nextjs.org/docs/api-reference/next/future/image#fill) seems to allow this use case. So we should be able to use the fill layout with an imported image.

### Link to reproduction

https://stackblitz.com/edit/nextjs-future-image-fill-bug?file=pages/index.js

### To Reproduce

Open the sand box

**Comment by SukkaW** [comment]
I have identified the issue. The static imported image will always have `width` and `height` values (provided by the Webpack) that Next.js doesn't expect to have when using `fill`.

I am already working on a fix to let Next.js ignore `width` and `height` from the Webpack when using `fill`.
