### ISSUE TITLE
`runtime: 'experimental-edge'` in `next.config.js` has no effect

### ISSUE THREAD

**Issue by zhuhaow** [vercel/next.js#39800]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: N/A
      pnpm: 7.9.3
    Relevant packages:
      next: 12.2.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Setting runtime to `experimental-edge` in `next.config.js` has no effects. The build artifacts (in `.next`) look exactly the same with this config unset.

Example config,
```
/** @type {import('next').NextConfig} */
const nextConfig = {
	reactStrictMode: true,
	swcMinify: true,
	experimental: {
		runtime: 'experimental-edge',
	},
};

module.exports = nextConfig;
```

The build log does suggest Next is using experimental runtime 

```
warn  - You have enabled experimental feature (runtime) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
```

The only way to enable edge support is by setting 

```
export const config = {
	runtime: 'experimental-edge',
};
```

in the page source.

Then the generated artifacts will be compatible with edge runtime, e.g., with `edge-runtime-webpack.js` and the generated `js` files don't contain any `require` statement.

### Expected Behavior

Setting 

```
experimental: {
	runtime: 'experimental-edge',
},
```

should be enough to build all pages with edge support

### Link to reproduction

N/A

### To Reproduce

See above

**Comment by zhuhaow** [comment]
Also, if 

```
export const config = {
	runtime: 'experimental-edge',
};
```

is set, the page won't be generated statically when building. SSG is not working.

**Comment by shuding** [comment]
This is expected. The global `runtime: 'experimental-edge'` config set in `next.config.js` only affects pages that **need** a server runtime. Static pages (pages without `getStaticProps`/`getServerSideProps`) will be statically optimized as HTML at build time, there is no runtime (either edge or Node.js) involved.

However, if you force to set the runtime as `experimental-edge` for a certain page, Next.js will opt-in edge SSR for that page. Currently, the edge runtime doesn't support SSG (so it always behave like SSR) as we are working on it.

**Comment by zhuhaow** [comment]
Hi @shuding, I just tried again on the latest canary and I can confirm setting `runtime: 'experimental-edge'` has **no effect on any pages**, no matter it's API route, with dynamic (`getServerSideProps`) or not. 

At the same time, even the fully static pages are generated with the handler code for `node` runtime.
