### ISSUE TITLE
Invalid next.config.js options detected ( unexpected property api )

### ISSUE THREAD

**Issue by rajesh40** [vercel/next.js#39854]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

We are using latest version of Nextjs as below
 "next": "^**12.2**.5",
 "next-connect": "^0.13.0"
 
 It was working with Older version i.e. **12.1**

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

using amazon aws

### Describe the Bug

 - The root value has an **unexpected property, **api****, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack

Due to Removal api property we are unable to set next config like below
**api:{
    bordyParser: {
      sizeLimit: '50mb'
    }
  }**
  
  Our application stopped working  for large body size like image , csv uploads.
  But same endpoint without image or csv are working perfectly.

### Expected Behavior

It should work for large request body with image or large file (size may be more than 20 MB)

### Link to reproduction

https://dev.insta-inventory.com:3000/api/mobile/stock-checker/change-job-status

### To Reproduce

https://drive.google.com/file/d/1T6gSNS9XXW6DkO9L5xOXMTLaFAHW0Fhd/view?usp=sharing

Use this JSON payload to reproduce.

**Comment by ijjk** [comment]
Hi, as the warning says `api` is not a valid field in `next.config.js`, if you want to custom the API configuration it needs to use page-level configuration as documented here https://nextjs.org/docs/api-routes/request-helpers#custom-config

**Comment by rajesh40** [comment]
@ijjk 
We did same and it was working previous version of  NEXT.js 
But in last version i.e next": "^**12.2**.5", it stopped working as above message said.

**Comment by rajesh40** [comment]
Please reopen it.

**Comment by rajesh40** [comment]
https://nextjs.org/docs/api-routes/request-helpers#custom-config

above document is outdated for **api** key in nextjs config. 
Team must tell it's alternate if removed in last version.

**Comment by ijjk** [comment]
@rajesh40 the mentioned config must be applied in `pages/api/some-page.js` not in `next.config.js`, this hasn't changed between Next.js versions the only new change was to warn for invalid config in `next.config.js` which is correct here.

**Comment by rajesh40** [comment]
@ijjk 

We did same but it's not working after upgradation especially for large payload.
You may use payload from  **https://drive.google.com/file/d/1T6gSNS9XXW6DkO9L5xOXMTLaFAHW0Fhd/view?usp=sharing**

Please use this payload for you testing environment with latest next js version i.e. **"next": "^12.2.5".**
