### ISSUE TITLE
Rewrites don't work

### ISSUE THREAD

**Issue by JunlinPan-Crypto** [vercel/next.js#39857]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
    Binaries:
      Node: 18.7.0
      npm: 8.15.0
      Yarn: 1.22.17
      pnpm: 7.9.3
    Relevant packages:
      next: 12.2.6-canary.1
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

warn  - Failed to fetch latest canary version. (Reason: Cannot read properties of undefined (reading 'tag_name').)
      Detected "12.2.6-canary.1". Visit https://github.com/vercel/next.js/releases.
      Make sure to try the latest canary version (eg.: `npm install next@canary`) to confirm the issue still exists before creating a new issue.
      Read more - https://nextjs.org/docs/messages/opening-an-issue

### Describe the Bug

Rewrites features seems broken from a certain version, but redirects work.

Hers is `rewrites` configuration for example:

```js
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  rewrites() {
    return [
      {
        source: '/page-a',
        destination: '/page-b',
        // permanent: false,
      },
    ]
  }
}

module.exports = nextConfig

```

And the example pages:

**/pages/page-a.jsx**
```jsx
export default function pageA() {
  return <p>pageA</p>
}
```

**/pages/page-b.jsx**
```jsx
export default function pageB() {
  return <p>pageB</p>
}
```

### Expected Behavior

Accessing page `/page-a` should be rewrited with `/page-b`, but still respond page A

### Link to reproduction

https://codesandbox.io/s/new-wind-v36hub?file=/next.config.js

### To Reproduce

With **redirects** configured, run the development server and access `http://localhost:3000/page-a`

**Comment by ijjk** [comment]
Hi, if you have `pages/page-a` and you want to have the rewrite take priority you have to use `beforeFiles` rewrites as documented here https://nextjs.org/docs/api-reference/next.config.js/rewrites

**Comment by JunlinPan-Crypto** [comment]
@ijjk  Thanks, I ignored these rules. BTW, how can I rewrite api routes?

**Comment by ijjk** [comment]
Rewriting to/away API routes should work the same as the above documentation describes.
