### ISSUE TITLE
Next + SWC appear to generate incorrect sourcemaps

### ISSUE THREAD

**Issue by markerikson** [vercel/next.js#39878]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.2
      eslint-config-next: N/A
      react: 0.0.0-experimental-e7d0053e6-20220325
      react-dom: 0.0.0-experimental-e7d0053e6-20220325
```

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

Vercel, but N/A

### Describe the Bug

Next generates different sourcemaps when we switch between using Babel to transpile our code, and SWC. The SWC sourcemaps are incorrect - the mapped output differs from the original source code by a few lines, causing incorrect debugging behavior.

We build https://replay.io , a time-travel debugger for JS. The Replay client uses sourcemaps on both the backend and frontend to parse and display info about the recorded application. In turn, we frequently record replays of our own client app to debug how it's working.

I've made two replays of our codebase built with Next 12.2.6-canary.2 , switching only between using Babel and SWC to transpile:

- Babel: [https://app.replay.io/recording/replay-next-1226-canary2-babel--e55cb64a-aea9-400b-98d3-f3b5ad3525b7](https://app.replay.io/recording/replay-next-1226-canary2-babel--e55cb64a-aea9-400b-98d3-f3b5ad3525b7?point=5841333966060634269747992483333131&time=3048.1461988304095&hasFrames=true)
- SWC: [https://app.replay.io/recording/replay-next-1226-canary2-swc--8272ce14-288f-4076-93fb-45f22c562c8f](https://app.replay.io/recording/replay-next-1226-canary2-swc--8272ce14-288f-4076-93fb-45f22c562c8f?point=5192296858740256335142097310974987&time=2817.1461988304095&hasFrames=true)

If you open up `debugger/src/actions/event-listeners.ts` in both files, you can see that the Babel file correctly maps all of the lines that were hit:

![image](https://user-images.githubusercontent.com/1128784/186254202-9d6c8846-f84a-4f0b-bea6-6d5a851758c2.png)

In the SWC-built version, the line hit info is off by 3-4 lines.

![image](https://user-images.githubusercontent.com/1128784/186254255-4530a4c7-0e61-42d2-8a88-f8482fcf3445.png)

If you open up the sourcemap visualizer tool for both versions, the Babel version is correct:

- https://app.replay.io/recording/replay-next-1226-canary2-babel--e55cb64a-aea9-400b-98d3-f3b5ad3525b7/sourcemap/o999

![image](https://user-images.githubusercontent.com/1128784/186254499-7290a529-ab03-4e8b-8261-2b0840283f57.png)

and the SWC version is wrong:

- https://app.replay.io/recording/replay-next-1226-canary2-swc--8272ce14-288f-4076-93fb-45f22c562c8f/sourcemap/o995

![image](https://user-images.githubusercontent.com/1128784/186254571-f1aa8fa9-c683-4d51-9aed-f063a4310e9d.png)

### Expected Behavior

Using SWC to compile our application would generate sourcemaps that accurately map the original source.

### Link to reproduction

https://github.com/replayio/devtools/tree/bugfix/FE-434-next-sourcemaps

### To Reproduce

1. Clone https://github.com/replayio/devtools
2. Check out commit https://github.com/replayio/devtools/commit/61605c25401897a3486545111e5f9157ef5e3886 , part of the `bugfix/FE-434-next-sourcemaps` branch.
3. Run `yarn` to install
4. Use Babel to build the app: `yarn build`, and check the build output + sourcemaps
5. Check out the tip of the `bugfix/FE-434-next-sourcemaps` branch, which just disables `.babelrc` to use SWC for building
6. Use SWC to build the app: `yarnbuild`, and check the build output + sourcemaps

**Comment by kdy1** [comment]
Can you try the latest version? I think this is fixed.

**Comment by fiveable-jferg** [comment]
By "the latest version", do you mean 12.3.1, or the latest canary release?

**Comment by kdy1** [comment]
I meant the canary

**Comment by markerikson** [comment]
Whoops, somehow I missed seeing the earlier notice.  Yeah, will try tomorrow!

**Comment by markerikson** [comment]
This is still definitely broken.

Steps to reproduce:

- Clone https://github.com/replayio/devtools
- Check out branch `bugfix/FE-434-next-swc-sourcemaps-busted`
- `yarn` to install deps
- `yarn build`
- Open up https://evanw.github.io/source-map-visualization/ in a tab
- In a file explorer, browse down to `$REPLAY_REPO/.next/static/chunk/pages/recording`
- Drag `[[...id]-$HASH.js` and `[[...id]-$HASH.js.map` into the sourcemap viewer
- In the top dropdown, look around list entry 128-125 for a file named `actions/box-model.ts` and select it
- Observe that the sourcemapped original text and minified output do not align, such as the `effect: async (action, listenerApi) =>` line:

![image](https://user-images.githubusercontent.com/1128784/196774215-16f058fa-185f-4d12-bda3-60257999446f.png)

For comparison, this works correctly with Babel as the compiler:

![image](https://user-images.githubusercontent.com/1128784/196774425-33b9c35f-4203-42ac-99eb-5bf6ebcbb983.png)

I'm attaching a zip file containing the output `[[...id]].js` and `[[...id]].js.map` files for 4 different build combinations:

- 12.2, Babel compiler + Terser
- 12.2, Babel compiler + `swcminify`
- 12.3.canary-32, Babel compiler (+ `swcminify` by default?)
- 12.3-canary.32, SWC compiler

[Next Babel and SWC sourcemaps.zip](https://github.com/vercel/next.js/files/9823260/Next.Babel.and.SWC.sourcemaps.zip)

That may be useful in seeing what's different.

**Comment by kdy1** [comment]
I can't build your app because `yarn` failed.


```

❯ yarn
yarn install v1.22.19
warning Missing name in workspace at "/Users/kdy1/projects/lab/devtools/packages/markerikson-stack-client-prototype", ignoring.
[1/4] 🔍  Resolving packages...
warning Resolution field "react-is@18.2.0" is incompatible with requested version "react-is@^16.13.1"
warning Resolution field "react-is@18.2.0" is incompatible with requested version "react-is@^16.7.0"
warning Resolution field "react-is@18.2.0" is incompatible with requested version "react-is@^17.0.2"
warning @redux-devtools/app > socketcluster-client > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @redux-devtools/app > socketcluster-client > uuid@3.2.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning Resolution field "react-is@18.2.0" is incompatible with requested version "react-is@16.9.0"
warning @svgr/webpack > @svgr/plugin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
error An unexpected error occurred: "https://registry.yarnpkg.com/bvaughn-architecture-demo: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/kdy1/projects/lab/devtools/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```
 
And I found that the source map you posted has sourcemap for debug build (webpack HMR)
Can you upload a new one?

**Comment by jridgewell** [comment]
Here is the `[[...id]-$HASH.js` and `[[...id]-$HASH.js.map`: [sourcemap.zip](https://github.com/vercel/next.js/files/10038687/sourcemap.zip)

**Comment by kdy1** [comment]
Thank you!

**Comment by markerikson** [comment]
Afraid I'm busy at a conference today, but I should be back online on Monday.  Please let me know if you still need something more!

**Comment by kdy1** [comment]
@markerikson Did you post the correct input/map?

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/29931815/204707158-67488c6f-e3f0-4ca3-a8bd-e6f1a4e2af7b.png">

This is babel version, and I'm not sure if this is correct

**Comment by markerikson** [comment]
@kdy : yeah, the zip file I attached _should_ have sourcemaps from four different build setup variations, no other code changes between them.

I will say that our sourcemaps have been... seemingly flaky and inconsistent in general, and I'm not sure what other issues we might have with our setup.

In this case, I just know that switching from Babel to SWC definitely made things worse.

But yeah, that screenshot does look kinda broken too :)

**Comment by kdy1** [comment]
@markerikson Are you using browserslist or `legacyBrowsers: false`?
To fix source map issue, I have to check all transform passes but I want to focus on more widely used parts first.
The first one if typescript, but it would be nice if I know which build target is used

**Comment by markerikson** [comment]
Yeah, our current target is `chrome: 95`:

- [`next.config.js`](https://github.com/replayio/devtools/blob/ecb88e16d48d3a4343b4d32e9c576df3295a9443/next.config.js#L23-L28)
- [`.babelrc`](https://github.com/replayio/devtools/blob/ecb88e16d48d3a4343b4d32e9c576df3295a9443/.babelrc)
- [`package.json` browserslist](https://github.com/replayio/devtools/blob/main/package.json#L213-L215)

**Comment by jridgewell** [comment]
This should be resolved with https://github.com/swc-project/swc/pull/6561, though that'll need to be rolled into the `next` release.

**Comment by markerikson** [comment]
Sweet, thanks!  I'll definitely try that out as soon as you've got it available.

**Comment by kdy1** [comment]
Fixed by https://github.com/vercel/next.js/pull/43652

**Comment by markerikson** [comment]
Thank you!  We're still on Next 12 atm, but I'll try upgrading soon and see what happens.
