### ISSUE TITLE
Help people avoid trap where you have a <Link> without and immediate child <a>

### ISSUE THREAD

**Issue by mcapodici** [vercel/next.js#39881]
### Describe the feature you'd like to request

Problem:

Given this code:

```
        <Link href="/anotherpage">
          <a>
            Link 1
          </a>
        </Link>
        
        <Link href="/anotherpage">
          <div>
            Link 2
          </div>
        </Link>
```

If you create a link like Link 2 it will work when you click it, but you can't right click it to open in a new tab. Link 1 works OK.

This is because, I assume \<Link\> is more of a HOC than an actual link, which is counter to what one might expect. I assume it adds a click handler, than adds the href to the immediate child if it is an anchor, otherwise silently doesn't.

### Describe the solution you'd like

I suggest a console warning that you don't have an \<a\> as an immediate child of \<Link\>, and that it won't behave like a normal link (more like a button). To disable that warning, maybe a prop is set to show intent?

### Describe alternatives you've considered

You could change \<Link\> to inject the `a` by default, with a prop to turn that off. But I rejected that because it won't be backwards compatible.

**Comment by SukkaW** [comment]
See https://github.com/vercel/next.js/pull/36436, the `newLinkBehavior`.

It would become the new default with Next.js 13 (as planned). However, you can opt-in to it right now with `experimental.newNextLinkBehavior` in your `next.config.js`.

**Comment by mcapodici** [comment]
Perfect!
