### ISSUE TITLE
Concurrent router push requests disregard requests except the last one

### ISSUE THREAD

**Issue by yenerunver** [vercel/next.js#39909]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Issue is discovered in the sandbox environment provided below.

Version used: `12.2.6-canary.4`

### Describe the Bug

When we do two concurrent `Router.push(...)` requests, if the first route is not visited before, it is neglected.

If the first route is visited before, it works as expected.

Issue can be tested in the sandbox environment provided.

Video proof of the issue: https://user-images.githubusercontent.com/8215944/186466083-630c67a2-b1f9-4a79-ac25-71546ba87b4f.mp4

 

### Expected Behavior

It should push the routes right after each other to prevent an occacional race condition.

### Link to reproduction

https://codesandbox.io/s/next-js-router-push-forked-gqsn1k

### To Reproduce

Steps to test on the sandbox environment provided:
1. Click "Visit both".
2. Click demo browser's back button twice (if possible).
3. If it goes to First page -> Main page, reload demo browser and start from step 1.

**Comment by balazsorban44** [comment]
`router.push` is an async operation so you'll have to `await` it to let it finish the routing properly. It's also recommended to use the `const router = useRouter()` hook to call `router.push` instead of `import Router ...` and `Router.push`
