### ISSUE TITLE
Middleware executes twice (even when we use the matcher)

### ISSUE THREAD

**Issue by ornakash** [vercel/next.js#39917]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 

### How are you deploying your application? (if relevant)

Other platform

### Describe the Bug

We're using the middleware and we just found out it executes things twice, even the application itself. I know that middleware is being used in resources as well, so I put a matcher and removed the "favicon" because I heard it can cause this bug.

When we use the middleware, and console.log in "_app.tsx", we see that it renders twice. Also I put a counter in middleware.ts and every page I enter I see that it increases the counter by two.

My middleware.ts page looks like:
```
import { NextRequest, NextResponse } from "next/server";

let counter = 0;
export function middleware(request: NextRequest) {
  const response = NextResponse.next();
  counter++;

  console.log("middleware #", counter);
  return response;
}
```

### Expected Behavior

It should only render once. Wait for the request, then return the response and then render the application.

### Link to reproduction

https://github.com/ornakash/reproduction-template-nextjs

### To Reproduce

Clone the repository
use "yarn" and "yarn run dev" in order to start the server
Enter the app
Check the terminal - you should see the error

**Comment by 11koukou** [comment]
Hello, I have run your example in production mode. The middleware indeed runs twice per request, however the app does not render more than once , the "App re-renders" message appears only once in the console. This was indeed a bug about a month ago but was fixed through the pr #38422. 
So to summarize, the middleware is executed more than once but there are no unnecessary re-renders in the app

**Comment by iliketowritecode** [comment]
Also seeing this bug as well. Like @11koukou said ... the app is rendering just fine (only once). but the middleware is executed twice.

**Comment by mhauken** [comment]
I'm having the same issue here with next 13.5.4

**Comment by maiconsanson** [comment]
Same here with `14.0.3`. For me is a problem because I'm using fetch in middleware.

**Comment by goldenjayr** [comment]
same issue here `14.0.1`

**Comment by etnichols** [comment]
@11koukou could you please advise on strategies to _avoid_ double execution of middleware? As @maiconsanson pointed out, even though the double execution doesn't cause a re-render, it is indeed a problem when executing fetches or stateful logic in middleware.

We are using middleware as a way to validate and refresh authentication tokens for users. In the case where a refresh is necessary:

- first middleware execution succeeds: check token expiration, perform token refresh, attach updated tokens to cookies.
- second execution fails: check token expiration, perform token refresh -- but, the request holds a reference to the stale refresh token, which was already removed from DB in first execution -- failure!

Here's a diff of the requests coming into the middleware for the same route: https://www.diffchecker.com/qBYde2tQ/

One can see that the first request appears to be CORS-initiated, while the second is actually user-initiated: 
![Screenshot 2024-01-17 at 12 14 31 PM](https://github.com/vercel/next.js/assets/4588531/abcbd67a-67dc-459e-a224-5ddb60765410)

Would you recommend usage of the `missing` array in the [middleware matcher documentation](https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher) as a way to guard against execution of middleware for non-user-initiated calls?

Given that most useful middleware _is_ executing fetches / network calls, it would be helpful to improve the documentation around this case.

**Comment by scottsmith-1** [comment]
In my case, I'm using some session headers with Auth.js to determine the request state, and while it doesn't really break anything immediately it seems pretty aggressive for the database calls!

**Comment by GarethRader** [comment]
I am also having this problem on 14.0.4. I have tried using various matchers and still get multiple triggers. 

This is a problem for me as I am managing user sessions and conditionally redirecting based on valid user session (protecting routes). However, this causes a `too many redirects` error due to trying to use redirect() in the middleware. I would like to be able to manage all of my redirects and route protecting on server side.

**Comment by samcx** [comment]
![CleanShot 2024-02-27 at 17 43 57@2x](https://github.com/vercel/next.js/assets/28912696/d13d763b-5b50-42a1-94dd-db628e1594fa)

I am not able to replicate this issue. I will be closing this issue in the meantime!

If you are still able to replicate this on the latest, please let me know.

**Comment by gsdev01** [comment]
any update on this ?
