### ISSUE TITLE
Link prefetch [onmousedown]

### ISSUE THREAD

**Issue by mishase** [vercel/next.js#39934]
### Describe the feature you'd like to request

Requesting pages that require any API requests before render may last for about ~170ms, so user have to wait for request to finish before transition happens. This long transition requests is visible and makes your app look slow

#### Slow - ~150ms
<br />
By average we can make page transitions >2X faster by prefetching when `onmousedown` event was fired.

### You can test your click times by using this sample html:
```html
<!DOCTYPE html>
<html>
  <body>
    <button id="test" onmousedown="onDown()" onclick="onClick()">Test</button>

    <script>
      let time;

      function onDown() {
        time = Date.now();
      }

      function onClick() {
        console.log(`clicked in: ${Date.now() - time}ms`);
      }
    </script>
  </body>
</html>
```

### Describe the solution you'd like

Prefetching page when `onmousedown` event was fired

### Describe alternatives you've considered

-

**Comment by SukkaW** [comment]
@mishase 

Next.js' `next/link` component already has built-in prefetch support (built on top of React and Next.js router)!

By default, `next/link` will prefetch links when scrolling into the viewport. You can use `prefetch={false}` prop to disable viewport prefetch.
`next/link` will also prefetch the link `onMouseEnter` (and `onTouchStart` if you have opted into the `newLinkBehavior`).

In short, Next.js has already implemented the feature and it works out of the box!
