### ISSUE TITLE
comment installer une ancienne version de NEXTJS

### ISSUE THREAD

**Issue by begaaam** [vercel/next.js#39963]
### Describe the feature you'd like to request

je voudrais installer la version , NEXTJS 11.1.2 parce que j'essaie d'installer , ça installer tjrs la dernière version.(12.2.*)
merci

### Describe the solution you'd like

installer  NEXTJS 11.1.2

### Describe alternatives you've considered

parce que la version 12.2.* installe automatiquement nextauth.4

**Comment by ijjk** [comment]
Hi, you can install the older version after running `create-next-app` by manually installing with your npm client e.g. `npm i next@11.1.2`. 

Out of curiosity why do you want to leverage `v11.1.2` instead of `v12.2.5` which contains a lot of performance and bug fixes?

**Comment by begaaam** [comment]
I wanted to use next-auth v3 and it doesn't work with nextjs12.2.* but it's ok many thanks
