### ISSUE TITLE
Docs: examples/with-strict-csp doesn't support reporting

### ISSUE THREAD

**Issue by tinleym** [vercel/next.js#40068]
### What is the improvement or update you wish to see?

In [examples/with-strict-csp ](https://github.com/vercel/next.js/tree/canary/examples/with-strict-csp), it would be helpful to see Content-Security-Policy set in a response, rather than in a meta tag, which doesn't allow the report-uri parameter.

### Is there any context that might help us understand?

The report-uri parameter provides the best means troubleshoot issues, and to monitor malicious activity.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#enabling_reporting

Generally speaking, documentation around strict-csp, and how to implement a secure policy per https://web.dev/strict-csp/ is pretty lacking, especially for a topic that most web developers would do well to be aware of (and use). Even a disclaimer of what Next is capable of (or not) would be helpful: speaking from my own experience, it's hard to know what part of my issues with strict-csp in Next are platform limitations.

### Does the docs page already exist? Please link to it.

For strict-csp, no. It's been mentioned in issues, notably in this monster pull request thread: https://github.com/vercel/next.js/pull/4943. However, there isn't any definitive guidance I've found on best practices. For a core security issue like this, that seems to require domain knowledge in Next, I think there should be.

**Comment by alizaeda** [comment]
Hi, can anyone explain why the example is using (this.props) in a functional component?

**Comment by leerob** [comment]
For reporting, the provided documentation states you can do the following:

```
Content-Security-Policy: default-src 'self'; report-to http://reportcollector.example.com/collector.cgi
```

Which means you need to modify the provided example with the following:

```js
const cspHeader = `
    default-src 'self';
    report-to http://reportcollector.example.com/collector.cgi;
    script-src 'self' 'nonce-${nonce}' 'strict-dynamic';
    style-src 'self' 'nonce-${nonce}';
    img-src 'self' blob: data:;
    font-src 'self';
    object-src 'none';
    base-uri 'self';
    form-action 'self';
    frame-ancestors 'none';
    block-all-mixed-content;
    upgrade-insecure-requests;
`
```

https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy
