### ISSUE TITLE
Middleware causes redirects in next.config.js to apply to links and router pushes

### ISSUE THREAD

**Issue by codynova** [vercel/next.js#40062]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.6
      eslint-config-next: 12.2.6-canary.6
      react: 18.2.0
      react-dom: 18.2.0
```

This also occurs on Mac OS 12.5.1

### Describe the Bug

In Next 12.1.6, `redirects` in next.config.js don't apply to routing via Next/Link or next/router pushes - either in dev or prod mode. This is still true even when `/pages/_middleware.js` is defined.

In Next 12.2.5 and 12.2.6-canary.6, `redirects` in next.config.js don't apply to routing via Next/Link or next/router  pushes - either in dev or prod mode. This is still true even when `/middleware.js` is defined.

I'm not sure if this is a bug or not, but the behavior has clearly changed between versions of Next. What is the expected behavior? In the current Next Middleware docs, I see this info that seem relevant:

```
Middleware will be invoked for every route in your project. The following is the execution order:

* headers from next.config.js
* redirects from next.config.js
* Middleware (rewrites, redirects, etc.)
```

### Expected Behavior

Redirects in next.config.js would be applied identically with or without a middleware file

### Link to reproduction

https://github.com/codynova/next-middleware-redirects

### To Reproduce

Run any of the projects in dev mode and click the link or button on the homepage. See that Next 12.2.5 with middleware behaves differently.

**Comment by ijjk** [comment]
Hi, this is currently expected as middleware opts into server resolving which includes resolving rewrites and redirects in `next.config.js`. This isn't done without middleware as it would require sending a manifest to the client which we've aimed to avoid to increase ability to scale as server side routing gets more complex. 

We are investigating the ability to match this resolving client-side without middleware being present.
