### ISSUE TITLE
Serverless function crashes for custom error page

### ISSUE THREAD

**Issue by eprothro** [vercel/next.js#40065]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

n/a

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

With a local production build, a custom error page works as expected. 

On Vercel, `getInitialProps` is called for the custom error component, but the serverless function crashes, exiting with a `Runtime.ExitError` and displaying a Vercel error page to users

```
2022-08-29T21:26:28.231Z	19727b2d-6d1f-49a4-99d6-fe1c36ad4616	ERROR	Error: a test error has been manually triggered
    at getServerSideProps (/var/task/.next/server/pages/index.js:21:11)
    at Object.renderToHTML (/var/task/node_modules/next/dist/server/render.js:512:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:638:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/var/task/node_modules/next/dist/server/base-server.js:743:28)
    at async /var/task/node_modules/next/dist/server/response-cache/index.js:80:36 {
  page: '/'
}
RequestId: 19727b2d-6d1f-49a4-99d6-fe1c36ad4616 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

```
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: cle1::w2g9g-1661808388324-680c9cd47d8a

If you are a visitor, contact the website owner or try again later.
If you are the owner, [learn how to fix the error](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_FAILED) and [check the logs](https://next-500-issue-44av6jqwb-evan-bnbfinderco.vercel.app/_logs).
```

### Expected Behavior

I expect the `getInitialProps` call to succeed, and the custom error component to be rendered successfully by the serverless function.

### Link to reproduction

https://github.com/eprothro/next-500-issue/tree/error-handling-with-404-page

### To Reproduce

1. clone the reproduction repo
2. check out the `error-handling-with-404-page` branch
3. deploy to Vercel
4. visit the index
5. see the `This Serverless Function has crashed` error page

Note that with this example repo, a commit adding a `pages/404.tsx` page introduces the crash. You can check out the `error-handling-no-404-page` branch and deploy to see the custom error component as expected. However, this is likely a red herring, as the application where we're seeing this continues to experience the crash even when the `pages/404.tsx` page is removed.

**Comment by ijjk** [comment]
Hi, this is expected and is due to needing to cleanup the serverless function instance. To customize the 500 page shown when an error does occur you can leverage `pages/500` as documented here https://nextjs.org/docs/advanced-features/custom-error-page#500-page

**Comment by eprothro** [comment]
@ijjk When using `pages/500`, `pages/error` is not called. It is not clear to me whether or not that is expected behavior (see #39952), but I assume that is expected since that is true both locally and on Vercel. 

With the provided example, there is not a way (that I see) to report the error and avoid getting a `This Serverless Function has crashed` error page on Vercel. Please correct me if I'm wrong, that that is the basis for this issue, which is not solved by leveraging `pages/500` as recommended.

Also, if this serverless function crash is expected behavior, why would it not crash all the time (e.g. when no 404 page is present in the example)?

**Comment by ijjk** [comment]
If the behavior isn't consistent when `pages/404` isn't present/is then it sounds like a bug as it should always behave the same. It should also be calling `_error.getInitialProps` if present before crashing and then serving `pages/500`.

**Comment by eprothro** [comment]
Agree, that is the behavior I'd expect to see. 

* [error-handling-with-500-page](https://github.com/eprothro/next-500-issue/tree/error-handling-with-500-page) branch 
  * `GET /` to see 500 page overriding calls to `_errors` locally or on Vercel
  * `GET /foo` to see 404 page overriding calls to `_errors` locally or on Vercel
* [error-handling-with-404-page](https://github.com/eprothro/next-500-issue/tree/error-handling-with-404-page) branch
  * `GET /` on Vercel to see serverless crash
* [error-handling-no-404-page](https://github.com/eprothro/next-500-issue/tree/error-handling-no-404-page) branch
  * `GET /` on Vercel to see serverless execution of `_errors` without crash
  * Notice here an additional oddity on Vercel / serverless:
    * locally, the response is a 500 and the `NextPageContext` contains `err` information
    * on Vercel, the response is a 404 and the `NextPageContext` contains no `err` information
