### ISSUE TITLE
Error: The Next.js Babel loader does not support .mjs or .cjs config files.

### ISSUE THREAD

**Issue by khteh** [vercel/next.js#40123]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

"next": "^12.2.5",
"babel-loader": "^8.1.0",

```
../../node_modules/next/dist/pages/_error.js
Error: The Next.js Babel loader does not support .mjs or .cjs config files.
```

`.eslintrc.cjs`:
```
module.exports = {
  env: {
    browser: true,
    es2022: true,
    jest: true,
  },
  extends: [
    'airbnb',
    'plugin:import/errors',
    'eslint:recommended',
    'plugin:react/recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
    'prettier/@typescript-eslint',
  ],
<snip>
```
`babel.config.mjs`:
```
/* eslint-disable no-template-curly-in-string */

// module.exports = {
export default {
  presets: ["@babel/preset-env", '@babel/preset-typescript', "@babel/preset-react"],
  plugins: [
    [
      'babel-plugin-transform-imports',
      {
        lodash: {
          transform: 'lodash/${member}',
          preventFullImport: true,
        },
        '@mui/material': {
          transform: '@mui/material/${member}',
          preventFullImport: true,
        },
        '@mui/icons-material': {
          transform: '@mui/icons-material/${member}',
          preventFullImport: true,
        },
        '@mui/lab': {
          transform: '@mui/lab/${member}',
          preventFullImport: true,
        }
      },
    ],
  ],
}
```

### Describe the Bug

`next build` bumps into this error:
```
../../node_modules/next/dist/pages/_error.js
Error: The Next.js Babel loader does not support .mjs or .cjs config files.
```

### Expected Behavior

No build error

### Link to reproduction

Sorry, private repo

### To Reproduce

Install the packages as provided, run `yarn install`, `yarn build`

**Comment by igorsergiichuk** [comment]
We do experience the same error while trying to migrate to Next.js v12.

Provide environment information
"next": "^12.0.2",
"babel-loader": "^8.1.0",

**Comment by balazsorban44** [comment]
> Sorry, private repo

We cannot investigate this. Feel free to open a new bug report with an actual, minimal reproduction. We have template repos in the bug template to help you create one, as well as pointers on how to write a good reproduction.
