### ISSUE TITLE
`assetPrefix` already exists for handling that.

### ISSUE THREAD

**Issue by timhysniutd** [vercel/next.js#40129]
`assetPrefix` already exists for handling that.

_Originally posted by @timneutkens in https://github.com/vercel/next.js/issues/5602#issuecomment-470477015_

Asset prefix is currently not handling `/_next/data`. If we have two apps on the same domain we would need to create reverse proxy rules for specific routes just to handle `/_next/data`. Is there are good reason why this is not getting more attention? It seems like there are multiple issues discussing this.

**Comment by ijjk** [comment]
Closing as no additional context was added
