### ISSUE TITLE
`next lint` shows initial setup prompt even though package.json has `eslintConfig` key

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#40133]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.9.0
    Relevant packages:
      next: 12.2.6-canary.7
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

i have a `package.json` file with eslint configured.

when running `next lint` it shows the "How would you like to configure ESLint" prompt.

### Expected Behavior

don't prompt to setup eslint when it is already configured in `package.json`

### Link to reproduction

n/a

### To Reproduce

1. add `eslintConfig` to `package.json`
2. run `npm run lint`

issue seems to be that `hasEslintConfiguration` returns:

```json
{
  "exists": false,
  "emptyEslintrc": false,
  "emptyPkgJsonConfig": false
}
```

https://github.com/vercel/next.js/blob/canary/packages/next/lib/eslint/hasEslintConfiguration.ts#L35 will never return with `exists: true`

**Comment by balazsorban44** [comment]
This seems to have been introduced in https://github.com/vercel/next.js/pull/39872 as the first release I could verify this in was `12.2.6-canary.3`
