### ISSUE TITLE
[Middleware] - Deleting cookies does not work. 

### ISSUE THREAD

**Issue by sannajammeh** [vercel/next.js#40146]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.6.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.8
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 105.0.5195.52

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

Calling `request.cookies.delete(KEY)` according to the documentation does not delete the cookie. The cookie is set just fine, but cannot be removed through middleware. I have tested in both dev and next start.

I also tested this in an edge API route on my actual codebase and hit the same result.

### Expected Behavior

Cookie should be removed performing this operation in middleware 
```ts
const response = NextResponse.next();

response.cookies.delete(KEY);

return response;
```

### Link to reproduction

https://github.com/sannajammeh/next-middleware-cookie-delete

### To Reproduce

1. Clone the github repo
2. Build & start next server
3. Navigate to `/` which will fire useEffect to set the cookie, observe in browser devtools that its there
4. Navigate to `/remove` which will trigger middleware and attempt to remove the cookie.
5. Observe that the cookie is still there despite no calls to /api/set-cookie and console logs from middleware showing cookie is there.

**Comment by fitiskin** [comment]
As far as I know, the `response` doesn't know about the cookies from the `request` hence `response.cookies.delete(KEY);` deletes nothing because the `response` cookie _Map_ is already empty.

I found couple of workarounds that seem to help:

1. Dummy set:
    ```js
    const response = NextResponse.next();
    
    response.cookies.set(KEY, 'any value');
    response.cookies.delete(KEY);

    return response;
     ```
2. Copy cookie header from the `request` to the `response`:

    ```js
    const response = NextResponse.next({
        headers: {
            cookie: request.headers.get('cookie')
        }
    });
    
    response.cookies.delete(KEY);
    
    return response;
    ```

However, I'm not sure this is a good idea since there is [explicit condition for such behaviour](https://github.com/vercel/next.js/blob/03eb4b1d612513506a441137a4997bd137e3b014/packages/next/server/web/spec-extension/cookies.ts#L118).

**Comment by sannajammeh** [comment]
[Here is how the docs says to do it](https://nextjs.org/docs/advanced-features/middleware#using-cookies). In that case the docs should be changed if it doesn't delete the cookie at all.

**Comment by LowScarlet** [comment]
same here

**Comment by Interlude-code** [comment]
same here

**Comment by ricardo-rp** [comment]
I am having similar problems in 12.3.1

**Comment by sannajammeh** [comment]
Looking at the source code this does not look like a bug. Its looks like faulty documentation. It should be highlighted that the cookie must be set in `Response` object's cookie map before deleting. Hopefully we get this detailed in the docs.

**Comment by ricardo-rp** [comment]
I'm having success with the following workaround:
`
const deleteCookie = (response: NextResponse, key: string) => {
    response.cookies.set(key, "", { expires: new Date(Date.now()) });
};
`

**Comment by jzxhuang** [comment]
This feels like a "gotcha" with the `NextResponse` API. I expected that if I call `delete`, it would "unset" the cookie, even if it's not defined on the `NextResponse` yet! 

It would be awesome to get the docs updated, or to provide some option to the `delete` method to delete the cookie even if it isn't set yet!

**Comment by reducio** [comment]
Working fine:

```
import { cookies } from 'next/headers';

export async function POST(request, { params }) {
    try {
        const cookieStore = cookies();
        const token = cookieStore.get('access-token');

        return new Response(
            JSON.stringify({
                message: 'Logout',
                data: true,
            }),
            {
                status: 200,
                headers: {
                    'content-type': 'application/json',
                    'Set-Cookie': `access-token=${token.value}; Path=/; Max-Age=0`,
                },
            }
        );
    } catch (error) {
        return new Response(
            JSON.stringify({}),
            {
                status: 400,
                headers: {
                    'content-type': 'application/json',
                },
            }
        );
    }
}
```
