### ISSUE TITLE
error - unhandledRejection: TypeError: this._implicitHeader is not a function

### ISSUE THREAD

**Issue by khteh** [vercel/next.js#40177]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

"next": "11",
"react": "^17.0.1",

### Describe the Bug

Followed this https://github.com/vercel/next.js/blob/077097b7f8d3d826118518a90f27cebd2b1373e6/examples/with-http2/server.js
When I run the server, this is what I get:
```
info  - Using external babel configuration from /project/packages/api/babel.config.js
event - compiled successfully
Listening on HTTPS port 4433
event - build page: /
wait  - compiling...
event - compiled successfully
MUI: The LocalizationProvider component was moved from `@mui/lab` to `@mui/x-date-pickers`.
The component will no longer be exported from `@mui/lab` in the first release of July 2022.

You should use `import { LocalizationProvider } from '@mui/x-date-pickers'`
or `import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider'`

More information about this migration on our blog: https://mui.com/blog/lab-date-pickers-to-mui-x/.
error - unhandledRejection: TypeError: this._implicitHeader is not a function
    at Http2ServerResponse.end (/project/node_modules/next/dist/compiled/compression/index.js:1:141485)
    at Object.sendRenderResult (/project/node_modules/next/dist/server/send-payload.js:68:13)
    at DevServer.pipe (/project/node_modules/next/dist/server/next-server.js:882:38)

```

### Expected Behavior

No error.

### Link to reproduction

https://github.com/vercel/next.js/blob/077097b7f8d3d826118518a90f27cebd2b1373e6/examples/with-http2/server.js

### To Reproduce

`npm run start`

**Comment by balazsorban44** [comment]
This is referencing a very old version of Next.js, so closing. The error message also has indications that it's more than just the `with-http2` code, so you should attach a proper reproduction.
