### ISSUE TITLE
Middleware is causing POST/PUT requests with large payload to stuck

### ISSUE THREAD

**Issue by louisesiqifan** [vercel/next.js#40189]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.8
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

next run dev

### Describe the Bug

When `middleware.ts` is present, POST and PUT requests with large payloads to any apis in the `pages/api` folder are stuck on `pending`. 

The payload I was using has `Content-Length: 30233`, so even if in default api setting it should not be too big. 

https://user-images.githubusercontent.com/57633889/188248378-46958c68-9781-4dea-b8a9-03232eb5959a.mov

### Expected Behavior

POST and PUT requests should be working with middleware present.

### Link to reproduction

https://github.com/louisesiqifan/next-js-huge-post

### To Reproduce

1. Run `npm i`
2. Run `npm run dev`
3. In http://localhost:3000/, click the two buttons

**Comment by c0m1t** [comment]
Any update on this issue?

**Comment by mgreenw** [comment]
Also seeing this with a `middleware.ts` file and a PUT request with an image. Both 12.2 and 12.3.

**Comment by mgreenw** [comment]
I think this is a dup of https://github.com/vercel/next.js/issues/39262

**Comment by louisesiqifan** [comment]
As mentioned in #39262 , downgrading to v12.2.2 solved my issue. 
Closing this because it's a dup.
