### ISSUE TITLE
next export is not working with inner pages

### ISSUE THREAD

**Issue by firstep-official** [vercel/next.js#40210]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

mac , chrome

### Describe the Bug

https://stackblitz.com/edit/vercel-next-js-wxrotq?file=package.json

Im getting file not found + a lot of errors about the path of scripts and images

folder structure of:

pages/
a.tsx
-----folder1
-----b.tsx
----------folder2
----------c.tsx

a will navigate to b, b will not navigate to c.
im using link code

i tried play with 
basepath
  assetPrefix: "./",
  
 but with no success :(
  

### Expected Behavior

a should open b that should open c

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-wxrotq?file=package.json

### To Reproduce

https://stackblitz.com/edit/vercel-next-js-wxrotq?file=package.json

**Comment by grayaustinc** [comment]
I would recommend reading up first on [Routing](https://nextjs.org/docs/routing/introduction), as the first thing I noticed in the reproduction is that you were using `./` in the href and I believe you may not fully understand how file-system based routing works in NextJs.  

Can you modify the reproduction to be closer to the folder structure that you specified?
```
pages/
a.tsx
-----folder1
-----b.tsx
----------folder2
----------c.tsx
```

I ran `npm run export` on your reproduction and it seems to have worked fine with no errors, and I could access all pages, so I can only assume that the reproduction you provided was either the wrong one, or was not accurate enough to the issue that you are having.

The three accessible pages would be
| folder | url | href |
|--------|----|------|
| pages/index.tsx | https://vercel-next-js-wxrotq--3000.local.webcontainer.io/ | / |
| pages/page1/index.tsx | https://vercel-next-js-wxrotq--3000.local.webcontainer.io/page1/ | /page1 |
| pages/page1/page2/index.tsx | https://vercel-next-js-wxrotq--3000.local.webcontainer.io/page1/page2 | /page1/page2 |

If I understand how your routes are in the folder structure you wrote out above, pages would be
| folder | href |
|--------|------|
| pages/a.tsx | /a |
| pages/folder1/b.tsx | /folder1/b | 
| pages/folder1/folder2/c.tsx | /folder1/folder2/c |

Which would lead to 404 errors if the href is incorrect

Also, basePath and assetPrefix should not play any role in routing and should only affect import paths.

**Comment by firstep-official** [comment]
thanks
