### ISSUE TITLE
Add option to omit the '=' when setting a URL query parameter to an empty string.

### ISSUE THREAD

**Issue by elliotwaite** [vercel/next.js#40211]
### Describe the feature you'd like to request

If we call:
```
router.push({
  pathname: 'video',
  query: {
    autoplay: '',
    loop: '',
  },
})
```
the URL will be set to something like:
```
example.com/video?autoplay=&loop=
```
however, I would like to be able to omit the equals signs and set the URL to this:
```
example.com/video?autoplay&loop
```

The router can already read either of those URLs and in both cases, the values of `router.query['autoplay']` and `router.query['loop']` will be empty strings, so reading the URL when the equals signs are omitted is already possible, but I haven't figured out a way to set the URL with the equals signs omitted.

### Describe the solution you'd like

Ideally, I would want the equals signs to be omitted for query parameters that are set to empty strings.

### Describe alternatives you've considered

Alternatively, perhaps an additional option could be added the the `options` object. I'm not sure what a good name for it would be, but maybe something like `minimalQueryParams`:
```
router.push(
  {
    pathname: 'video',
    query: {
      autoplay: '',
      loop: '',
    },
  },
  undefined,
  { minimalQueryParams: true },
)
})
```

Or maybe setting the values to `null` could omit the equals signs:
```
router.push({
  pathname: 'video',
  query: {
    autoplay: null,
    loop: null,
  },
})
```
(currently, setting the values to `null` results in the same URL as setting them to empty strings, it adds the equals signs).

**Comment by adxmcollins** [comment]
Outside of something like YouTube I've never seen empty query strings not have the equals symbol, so I think generally it is more accepted to do what Next is currently doing.

However, if you need to not have them, couldn't you do this?

`router.push('/video?autoplay&loop')`

**Comment by elliotwaite** [comment]
Ah, for some reason I was thinking I had to pass in a UrlObject to set query params, but yeah, I can just create my own function for converting the query object into a URL that omits the equals signs. That seems like a good alternative solution that works for me. Thanks for pointing out that option.

I think you're right that adding the equals signs for empty strings is the more expected behavior, as that's what [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) does. For example:
```
console.log(
  new URLSearchParams([
    ['autoplay', ''],
    ['loop', ''],
  ]).toString(),
)
```
Will log `autoplay=&loop=`.

Also, it seems like some servers might not even be able to parse the URL if the equals signs are omitted, as one of the comments from the StackOverflow question of ["Is a url query parameter valid if it has no value?"](https://stackoverflow.com/questions/4557387/is-a-url-query-parameter-valid-if-it-has-no-value) mentioned:
> ASP.NET MVC (versions 4 and 5 to my knowledge) definitely choke when there is no value provided :(

So feel free to close this issue, and thanks for the helpful suggestion.
