### ISSUE TITLE
Docs: There is no description of the content generated after build in the document

### ISSUE THREAD

**Issue by szfdiwang** [vercel/next.js#40217]
### What is the improvement or update you wish to see?

After I execute NPM run build, the. Next file is output But I found that this file is very large. It contains a cache file and a webpack folder with a volume of 200 + MB I haven't seen any description about this in the document. How can I turn off this output (in fact, I deleted this file, but run start still works)

### Is there any context that might help us understand?

![image](https://user-images.githubusercontent.com/25865789/188360394-fb0b75e0-ebb6-4ca7-b5d0-12b527064852.png), I don't know how this cache is generated. I can't find the source in the document,

**Comment by balazsorban44** [comment]
The `.next/cache/webpack` folder is used to speed up builds in development (`next dev`) and, at build-time `next build` and is not actually necessary to be present in production.

We can add documentation around the purpose of that folder (or `.next` in general), so thanks for raising this issue!

FYI, if you are self-hosting and want the absolute smallest possible output, you can set the `output: "standalone"` option in `next.config.js` that will generate a `.next/standalone` folder that you can - as the name suggests - distribute as is, no `node_modules` etc. are necessary to copy. Check out the docs https://nextjs.org/docs/advanced-features/output-file-tracing#automatically-copying-traced-files

If you are hosting on Vercel, you should not be concerned with this, as Vercel is going to make sure that your app is distributed the most optimal way.
