### ISSUE TITLE
Nonce attribute doesn't work with beforeInteractive script tags inside _document 

### ISSUE THREAD

**Issue by FINDarkside** [vercel/next.js#40225]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #44~20.04.1tux3 SMP Wed Jul 20 21:18:32 UTC 2022
    Binaries:
      Node: 16.14.2
      npm: 8.19.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

When you have `Script` tags with `beforeInteractive` strategy inside your `_document`, you cannot set a nonce for them. Even if you set the prop, it's not present in the html sent to the client. Obviously this is a problem since our CSP is now blocking these scripts.

### Expected Behavior

nonce attribute being present in the script tags client receives.

### Link to reproduction

https://github.com/FINDarkside/next-repro-nonce

### To Reproduce

Have the following `_document.tsx`:

```TypeScript
import NextDocument, { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";

export default class MyDocument extends NextDocument {
  render() {
    return (
      <Html>
        <Head>
          <Script
            id={`document_datalayer_script-${new Date().getTime()}`}
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{
              __html: `
                    console.log('test');
                  `,
            }}
            nonce={"does_not_work"}
            strategy="beforeInteractive"
          />
        </Head>

        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

**Comment by leerob** [comment]
Hey folks, wanted to swing back here with an update. After digging through many different issues and discussions, I've [**made a new page in the documentation**](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy) ([PR](https://github.com/vercel/next.js/pull/54601)) specifically for Content Security Policy and nonces. This docs page: 

- Explains how to generate a `nonce` with Middleware
- Shows how to consume the `nonce` in a route with `headers()`
- Shows a complete CSP without needing to use any `unsafe`
- Shows how to ignore the `nonce` Middleware from running on prefetches / static assets

Further, we've patched some bugs and made improvements to `nonce` handling in Next.js that will be available in the latest `canary` version (for those of you time traveling from the future, upgrade to Next.js 13.5). We also updated the `with-strict-csp` example in the `examples/` folder, which is backlinked from the [new documentation page](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy).

Really hope this helps out, thank you all 🙏 I'll be closing this issue out. To continue the discussion, [please go here](https://github.com/vercel/next.js/discussions/54907).
