### ISSUE TITLE
Next Export does not generate any HTML files in /out dir

### ISSUE THREAD

**Issue by Jambre** [vercel/next.js#40240]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.2.6-canary.9
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

create-next-app

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

Static (To be uploaded to S3)

### Describe the Bug

Following the direction from the [docs](https://nextjs.org/docs/advanced-features/static-html-export), and this [article](https://dev.to/parmentierchristophe/how-to-deploy-static-next-js-to-aws-s3-1d4f)- the export function did not generate the html files for static hosting.

I've tried defining an `exportPathMap` and setting `trailingSlash` to true which neither did not change the result.

### Expected Behavior

On export the `index.html` and other defined /pages should be generated into the /out directory. However, only the _next/ directory is created in the /out dir.

Expanded folder shows all files in /out generated from the export command:
![5376089db1e6d88b79bb586a446ce1bd](https://user-images.githubusercontent.com/1571911/188509628-793257b4-2f29-4544-82de-72503a293c63.png)

### To Reproduce

1. `npx create-next-app@latest` (currently 12.2.5)
4. Change 'build' in package.json to `next build && next export`
5. Run `npm install`
6. Run `npm run build`
7. With "exportPathMap" not being defined in next.config.js the command would generate a map from "./pages"
8. Static HTML files would be available in /out but fails to appear.

**Comment by rubytree33** [comment]
I tried reproducing it and got this error after `npm run build`, and the resulting directory tree looks like yours.

```
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Configure `images.unoptimized = true` in `next.config.js` to disable the Image Optimization API.
  Read more: https://nextjs.org/docs/messages/export-image-api
```

After making the experimental fix suggested by the link, it works as expected.

**Comment by Jambre** [comment]
@rubytree33 

Thanks for helping me out. That'll do it! Perhaps I should be more considerate of the CLI output next time. Adding this to my next.config.js file made it functional for create-next-app:
```
images: {
  unoptimized: true,
},
```

Further, for my project it worked when wrapped with `experimental:`
```
experimental: {
  images: {
    unoptimized: true,
  },
},
```

This is covered in the docs [here](https://nextjs.org/docs/api-reference/next/image#unoptimized). Currently the [static export ](https://nextjs.org/docs/advanced-features/static-html-export) docs page simply _alludes_ to the setting under `Image Optimization using a custom loader`, however I would recommend that the documentation team to add a direct reference/step stating that image optimization needs to be disabled for exporting to work.
