### ISSUE TITLE
ESLint randomly started enforcing new rule which is incorrect and breaking my builds

### ISSUE THREAD

**Issue by tr1s** [vercel/next.js#40245]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Node version: `v16.15.1`
npm version: `8.19.0`
Local ESLint version: `8.23.0`
Global ESLint version: `N/A`
Operating System: `macOS Big Sur / M1 Mac`

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

ESLint is enforcing a rule which is breaking my build.

| File | Vercel Build Error |
|:-------------:|:-------------:|
|![ESLint_ERRORS](https://user-images.githubusercontent.com/19172250/188555165-af40e4a8-35fd-4515-808e-c62d60f3d978.png)|![ESLint-ERRORS-2](https://user-images.githubusercontent.com/19172250/188555424-55e9ceea-55d7-47b8-82c6-3f2be824385b.png)|

I went through my old vercel builds and found where it stopped working—I updated some packages and that was it. I just tried to revert back to all the old package versions where the builds were working fine and I still am getting the errors now.

I'm not sure why ESLint decided to enforce this rule randomly or why it's throwing an error even though it's a real property. I know I can ignore it with next.js configs but I'm instead trying to figure out what's happening here.

I also have an identical personal portfolio project with the same setup code and up-to-date packages in which I'm not having this issue. I can't understand why it's only happening on this repo.

If you have any ideas as to what's happening please let me know, thank you.

I have made an issue over at [ESLint's repo](https://github.com/eslint/eslint/issues/16278) too as I'm not sure which would be more appropriate.

### Expected Behavior

Builds should pass.

### Link to reproduction

https://github.com/tr1s/nightizm

### To Reproduce

Run `npm run lint` and see that these errors are showing up. They shouldn't be showing up at all.

**Comment by JDansercoer** [comment]
We've been getting the exact same issue
![image](https://user-images.githubusercontent.com/11869830/188556205-805ceef4-b9e0-4e09-88b5-18325b623b41.png)

A workaround on our end was updating `eslint-plugin-react`, but this shouldn't be necessary since it's a dependency of `eslint-config-next`, so this should be handled in that package.

**Comment by ljharb** [comment]
See my comments on the eslint issue; this should be closed as it's an issue with eslint-plugin-react (which has been fixed). See https://github.com/jsx-eslint/eslint-plugin-react/issues/3380.

eslint-config-next surely uses `^` so it's 100% fine for you to have to update it.

**Comment by JDansercoer** [comment]
@ljharb this shouldn't be closed, as `eslint-plugin-react` is a dependency of `eslint-config-next` and is currently not a direct dependency of our project. Next should update the version range to not include the broken dependency.

**Comment by tr1s** [comment]
yeah @JDansercoer @ljharb looks like `esling-config-next` is using the old version of `eslint-plugin-react`:

![CleanShot 2022-09-06 at 01 56 27@2x](https://user-images.githubusercontent.com/19172250/188557930-e9555ec0-f3bd-47e2-940d-c492191f7cd1.png)

I will keep the issue open until my `eslint-config-next` get's upgraded. It's currently `12.2.5` and `12.2.6` is in canary still.

**Comment by ljharb** [comment]
That’s not how transitive deps work.

The next config is using ^ to depend on the react plugin, so you *already* updated it beyond v7.29.4, just not far enough to include the fixed version. It’s on you to update it farther.

**Comment by icyJoseph** [comment]
What should be done about https://github.com/vercel/next.js/discussions/40269, which flags `styled-jsx` tags, `<style jsx>`.

**Comment by balazsorban44** [comment]
As @ljharb suggests, this is not a Next.js issue, so I'll close it. You just have to make sure that your dependencies are up-to-date.

As for `jsx` on `style` @icyJoseph, it's a special property allowed by Next.js, so a separate issue is needed, which has been opened already here #40321, and a PR fixing that issue can be found here #40331
