### ISSUE TITLE
`crypto-browserify` takes up the majority of next bundle size

### ISSUE THREAD

**Issue by mcmxcdev** [vercel/next.js#40271]
### Describe the feature you'd like to request

[crypto-browserify](https://github.com/crypto-browserify/crypto-browserify) didn't have new commits since 2018.

It takes up quite a chunk according to: https://bundlephobia.com/package/crypto-browserify@3.12.0

Also visible as part of `@next/bundle-analyzer`: 
![Screenshot from 2022-09-06 16-17-20](https://user-images.githubusercontent.com/16797721/188660228-46def460-3d39-4a4d-a178-eca754687433.png)

### Describe the solution you'd like

Switch to an alternative, maintain a fork or drop it altogether.

### Describe alternatives you've considered

/

**Comment by balazsorban44** [comment]
You are likely using a library that imports `crypto` even if it's targeted for browsers. Next.js falls back to a polyfill for historical reasons.

You can now opt out of this behavior by setting the `experimental.fallbackNodePolyfills: false` option in your `next.config.js` but you'll have to make sure the library or your code does not  unnecessarily import `crypto` then. Read more at #39248

**Comment by mcmxcdev** [comment]
Hey Balasz, thanks for the detailed explanation, I really appreciate it!

Looks like I will have to wait for v12.2.6 to drop to try it out but looks promising ;)
