### ISSUE TITLE
Middleware matcher behaves different between next start/dev and vercel

### ISSUE THREAD

**Issue by PhilippSchreiber** [vercel/next.js#40305]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.18.1
      npm: 6.14.15
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.2.5
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

vercel and next start

### Describe the Bug

During debugging a different bug I recognized that the matcher of the middleware behaves different between next start / next dev and vercel.

I setup a small example project:

- https://vercel-middleware-index-404.vercel.app/
- https://github.com/PhilippSchreiber/vercel-middleware-index-404

It is using i18n with a default locale and a dynamic page [[...slug]].jsx

On local (start or dev)the middleware is not getting called for the index page (/) but for all other pages (`/en/`, `/ueber-uns/`, `/en/about-us/`). You can see the console.log.

On vercel the middleware gets called for all pages BUT `/`.

### Expected Behavior

The behavior of the middleware should be the same between next start and vercel

### Link to reproduction

https://github.com/PhilippSchreiber/vercel-middleware-index-404

### To Reproduce

Run the project locally and deploy it to vercel. Compare the logs from middleware when loading the index page `/`.

**Comment by PhilippSchreiber** [comment]
Additional info:

Having an empty matcher like this:

```export const config = {
  matcher: [],
};
```

leads to NO middleware invocation in my main project on vercel. Locally it works fine!

**Comment by PhilippSchreiber** [comment]
Since the matcher does not work properly we need to run the middleware on all urls now. This leads to this 🙄 

![Bildschirmfoto 2022-09-09 um 18 43 56](https://user-images.githubusercontent.com/1312725/189400305-efd6ac4f-c8b0-4259-b8f8-e5237e1dc691.jpg)

**Comment by grieblius** [comment]
I can confirm I'm experiencing ~the same situation.
I'm using i18n and trying to implement multi-tenant app. Using middleware example with exclude matcher from this example:
https://github.com/vercel/platforms/blob/main/middleware.ts

On localhost root path is ignored so need to add include matcher `/`. All other paths works as expected.
On Vercel all paths with `_next` throws 404. Paths to `api` or `public` works. Tried with various combinations, but didn't succeed with exclude strategy.
Switching to include strategy (adding include paths to matcher) seems working as expected.
Not sure is i18n here involved, didn't try without it.

**Comment by miguelvictor** [comment]
Can confirm this issue. Everything is working as expected on local machine but the matcher doesn't seem to have any effect when deployed to Vercel. Now our edge middleware invocations are already too high 😢
