### ISSUE TITLE
Unknown property 'jsx' found react/no-unknown-property

### ISSUE THREAD

**Issue by Chamberlainfrancis** [vercel/next.js#40321]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Wed Sep 07 2022 17:34:02 GMT+0100 (West Africa Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.10
      pnpm: 7.9.5
    Relevant packages:
      next: 12.2.6-canary.10
      eslint-config-next: 12.2.5
      react: 17.0.1
      react-dom: 17.0.1

### What browser are you using? (if relevant)

Chrome 105 on Windows 10

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I created some components using the next-js styled-jsx <style jsx> worked fine on `v11 `of next-js, but after upgrading to `v12` I get an error when using `yarn lint` or `yarn build` with the message:

> Error: Unknown property 'jsx' found react/no-unknown-property

For clarity, I have reproduced this on - [stackblitz](https://stackblitz.com/edit/nextjs-syp4l9?file=pages/index.js) - run `yarn lint or yarn build` to see the error.

### Expected Behavior

Next-js shouldn't throw an error because on default it supports styled components. In other words, this - `<style jsx></style>` should be recognized as valid.

### Link to reproduction

https://stackblitz.com/edit/nextjs-syp4l9?file=pages/index.js

### To Reproduce

Spin up a next js app the usual way:

> npx create-next-app nextjs-blog

your package.json should look like so below, ensure you are on at least next-js `version 12` 

```
{
  "name": "next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "info": "next info"
  },
  "dependencies": {
    "next": "^12.2.5",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },
  "devDependencies": {
    "eslint": "^8.23.0",
    "eslint-config-next": "^12.2.5"
  }
}
```
Create a sample component like below in `pages/index.js`

```
export default function Home() {
  return (
    <div>
      <style jsx>{`
      .title a {
        color: #0070f3;
        text-decoration: none;
      }
      `}</style>
      <Head>
        <title>Create Next App</title>
      </Head>

      <main>
        <h1 className="title">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
       </main>
    </div>
  );
}
```
in terminal run `next build` or `next lint`  next-js should throw an error 

> Error: Unknown property 'jsx' found react/no-unknown-property

Either way, you can't build to production because the error breaks the build process.

**Comment by balazsorban44** [comment]
I could verify this and opened a PR to fix it. For now, you can force `"eslint-plugin-react": "7.31.1"` in your project as the issue only happens when `eslint-plugin-react@7.31.2` or higher is installed.
