### ISSUE TITLE
Type issues in next.js/docs/upgrading.md file 

### ISSUE THREAD

**Issue by jasham** [vercel/next.js#40341]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

There are multiple typo issues in next.js/docs/upgrading.md file

### Which example does this report relate to?

Please check next.js/docs/upgrading.md file

### Describe the Bug

There are multiple typo issues in next.js/docs/upgrading.md file please check.

### Expected Behavior

There should be no typo issues in next.js/docs/upgrading.md file

### To Reproduce

Please go to next.js/docs/upgrading.md file

**Comment by balazsorban44** [comment]
Thanks for noticing! Since this is not a Next.js bug, I'm going to close the issue, but please feel free to open a PR with your proposed changes, and we will review it! :pray:
