### ISSUE TITLE
Build warns about `experimental: { esmExternals: 'loose' }`

### ISSUE THREAD

**Issue by gthb** [vercel/next.js#40368]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 16.15.1
      npm: 8.18.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

Running `npm run build` outputs this warning:

```
warn  - Invalid next.config.js options detected: 
  - The value at .experimental.esmExternals must be a boolean but it was a string.
```

But:
* `esmExternals` has long been allowed to be `'loose'` instead of a boolean
* [that setting is still checked for](https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack-config.ts#L429)
* [an integration test still has such a configuration](https://github.com/vercel/next.js/blob/7a8da9741ddbe4a7b672b9a3e474d74f0a80aa46/test/integration/externals-esm-loose/next.config.js).

So I think the warning is erroneous. Or else some documentation of a change is missing.

### Expected Behavior

No warning.

### Link to reproduction

https://github.com/gthb/next.js-repro-erroneous-esmExternals-warning

### To Reproduce

Put this in your `next.config.js` exports:

```js
  experimental: {
    esmExternals: 'loose',
  }
```

**Comment by rubytree33** [comment]
I'm taking a look at this.

**Comment by rubytree33** [comment]
As a disclaimer I'm not a maintainer and I'm very new here.

The reproduction does have the warning. For those looking for it, [here](https://nextjs.org/docs/messages/import-esm-externals) is the relevant part of the docs for an error this option is meant to circumvent. It says the option "tries to automatically correct this error" but all I can find for its actual use (according to the comments) is to [skip certain checks](https://github.com/vercel/next.js/blob/f7eed07945375f0b4a76efcbb5cbfe87072c2261/packages/next/build/webpack-config.ts#L455-L459). This seems like behavior that doesn't align with what the docs say, but I'm still trying to figure out what this actually does in the code.

If it does need to change, I think [this](https://github.com/vercel/next.js/blob/f7eed07945375f0b4a76efcbb5cbfe87072c2261/packages/next/server/config-schema.ts#L241-L243) is the part of the schema that this type requirement comes from, and I'll just make a pull request that changes it.

(By the way, the relevant documentation isn't linked with the warning, and I couldn't find any other documentation for this option. Maybe it would be good to have documentation links to configuration warnings like this? I might open a new issue for that.)

**Comment by rubytree33** [comment]
I found `boolean | 'loose'` for its type [here](https://github.com/vercel/next.js/blob/614f0d8e19a80cbb5f707b2201c7fb3ec5f3a831/packages/next/server/config-shared.ts#L114) so it seems that this option is supposed to allow `'loose'`. The only thing in the code which conflicts with that is the [ajv schema](https://github.com/vercel/next.js/blob/f7eed07945375f0b4a76efcbb5cbfe87072c2261/packages/next/server/config-schema.ts#L241-L243) which restricts it to `boolean`.

I'll create a pull request updating the schema.
