### ISSUE TITLE
fallbackNodePolyfills: false -> Module not found: Can't resolve 'path' in `next/future/image` (micromatch)

### ISSUE THREAD

**Issue by iCrawl** [vercel/next.js#40364]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.15.1
      Yarn: 3.2.1
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Edge 105.0.1343.27 (Official build) (arm64)

### How are you deploying your application? (if relevant)

not relevant but, `next dev` / `next build` / `next start`

### Describe the Bug

12.3.0 added a new experimental config option called `fallbackNodePolyfills` to prevent polyfilling and getting feedback when you might use an internal node module inside your client.

https://nextjs.org/blog/next-12-3#other-improvements

This seems to clash with `next/future/image` using `micromatch` which uses node specific modules.

```
../../node_modules/next/dist/compiled/micromatch/index.js:22:3426
Module not found: Can't resolve 'path'

Import trace for requested module:
../../node_modules/next/dist/shared/lib/match-remote-pattern.js
../../node_modules/next/dist/client/future/image.js
../../node_modules/next/future/image.js
./src/components/SidebarLayout.tsx
./src/pages/docs/[...slug].tsx

https://nextjs.org/docs/messages/module-not-found
```

### Expected Behavior

`next/future/image` not throwing and working correctly with `fallbackNodePolyfills: false`

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-sckjm9?file=next.config.js

### To Reproduce

Just open the stackblitz, thats all to it.

```tsx
import Image from 'next/future/image';

/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  return <Image src='https://raw.githubusercontent.com/discordjs/discord.js/main/.github/powered-by-vercel.svg' width={100} height={100} />;
}
```

```js
/** @type {import("next").NextConfig} */
module.exports = {
  reactStrictMode: true,
  images: {
    domains: ['raw.githubusercontent.com'],
  },
  experimental: {
    fallbackNodePolyfills: false,
  },
};
```

**Comment by jpedroschmitz** [comment]
It also doesn't work with `next/image`

**Comment by SukkaW** [comment]
I just dig a little bit into this.

So, `micromatch` is not a client-side module. It contains lots of code that can only run on Node.js.

But also, the only used method `micromatch.makeRe` (from `shared/lib/match-remote-pattern`), is a re-export of the `picomatch`:

https://github.com/micromatch/micromatch/blob/002d0d184c95e76775528fa1dbe0c446518879b2/index.js#L387

Where `picomatch` is actually importing `path`.
