### ISSUE TITLE
Docs: Typo

### ISSUE THREAD

**Issue by TheAlmightyDada** [vercel/next.js#40374]
### What is the improvement or update you wish to see?

About half way down the page there is a note about not having to use the <a> tags anymore, there is a typo in the wording.

I think it should read "but this is not required..." rather than "but this is nor required"

Happy to fix myself and do a pull request but if someone could point me in the right direction in terms of where to find this in the code base that would be great, as I could not find it myself (I tried exact searching for "but this is nor required" but got no results")

### Is there any context that might help us understand?

-

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/navigate-between-pages/link-component

**Comment by balazsorban44** [comment]
Thanks for reporting! The source of this documentation is not public, but I created a PR to fix it, and the fix will go out once it's merged!
