### ISSUE TITLE
bug(typedef): AppType typedef changed in 12.3

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#40371]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 7.10.0
    Relevant packages:
      next: 12.3.0
      eslint-config-next: 12.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

When bumping version to Next 12.3.0 we ran into some troubles with the AppType typedefinition:

![CleanShot 2022-09-08 at 22 30 41](https://user-images.githubusercontent.com/51714798/189219996-0b95d5a5-fe32-4601-baf4-4d89cda2ff2c.png)

The AppType typedefinition and specifically the pageProps seems to have been broken in 12.3.0 and the pageProps now evaluates to {}:
![CleanShot 2022-09-08 at 22 34 22](https://user-images.githubusercontent.com/51714798/189220578-66dd692a-cf6a-49d2-b14b-21580cd238b6.png)

### Expected Behavior

I am not sure if this is a bug or if it's intended, but this change is not present in the changelog and seems to be a "breaking" one worth noting. Maybe we are required to augment some part to make it work with 3rd party dependencies?

### Link to reproduction

https://github.com/juliusmarminge/apptype-repro

### To Reproduce

Create a new next-app (using reproduction template):
```bash
npx create-next-app -e reproduction-template
```

Install NextAuth:
```bash
nom install next-auth
```

Create `pages/_app.tsx` with the following content:

```ts
import { SessionProvider } from "next-auth/react";
import type { AppType } from "next/dist/shared/lib/utils";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <SessionProvider session={pageProps.session}>
      <Component {...pageProps} />
    </SessionProvider>
  );
};
```

Hover pageProps, it evaluates to {} and the pageProps.session will error. This was not an issue in 12.2.5.

**Comment by c-ehrlich** [comment]
Appears to be related to this typedef change

12.2:
```ts
export declare type AppInitialProps = {
    pageProps: any;
};
export declare type AppPropsType<R extends NextRouter = NextRouter, P = {}> = AppInitialProps & {
    Component: NextComponentType<NextPageContext, any, P>;
    router: R;
    __N_SSG?: boolean;
    __N_SSP?: boolean;
    __N_RSC?: boolean;
};
```

12.3:
```ts
export declare type AppInitialProps<P = any> = {
    pageProps: P;
};
export declare type AppPropsType<R extends NextRouter = NextRouter, P = {}> = AppInitialProps<P> & {
    Component: NextComponentType<NextPageContext, any, any>;
    router: R;
    __N_SSG?: boolean;
    __N_SSP?: boolean;
    __N_RSC?: boolean;
};
```

**Comment by juliusmarminge** [comment]
> Appears to be related to this typedef change
> 
> 
> 
> 12.2:
> 
> ```ts
> 
> export declare type AppInitialProps = {
> 
>     pageProps: any;
> 
> };
> 
> export declare type AppPropsType<R extends NextRouter = NextRouter, P = {}> = AppInitialProps & {
> 
>     Component: NextComponentType<NextPageContext, any, P>;
> 
>     router: R;
> 
>     __N_SSG?: boolean;
> 
>     __N_SSP?: boolean;
> 
>     __N_RSC?: boolean;
> 
> };
> 
> ```
> 
> 
> 
> 12.3:
> 
> ```ts
> 
> export declare type AppInitialProps<P = any> = {
> 
>     pageProps: P;
> 
> };
> 
> export declare type AppPropsType<R extends NextRouter = NextRouter, P = {}> = AppInitialProps<P> & {
> 
>     Component: NextComponentType<NextPageContext, any, any>;
> 
>     router: R;
> 
>     __N_SSG?: boolean;
> 
>     __N_SSP?: boolean;
> 
>     __N_RSC?: boolean;
> 
> };
> 
> ```

To be clear i think this is a very good improvement and seems like it would allow for a more typesafe usage in the root app.

Maybe the AppType should be a generic like NextPage, or React.FC and letting me pass in the props like

```ts
const MyApp: AppType<{ session: Session }> = ...
```

**Comment by bennettdams** [comment]
If you already have custom app props in place and I read this recent change on the types correctly, giving your page props types to the `NextPage` as a generic fixes the issue.

Here is an example setup:

```ts
import type { NextPage } from 'next'
import type { AppProps as NextAppProps } from 'next/app'

/**
 * Custom page props returned by a Next.js page. Injected in `_app` by Next.js.
 * These are global fields that every page can provide.
 */
export type PageProps = {
  showSidebar?: boolean
}

/** Custom Next.js layout component. */
type NextPageWithLayout = NextPage<PageProps> & {
  getLayout?: (page: JSX.Element) => JSX.Element
}

/** Custom app props that return our layout component and page props. */
type AppPropsCustom = {
  Component: NextPageWithLayout
  pageProps: PageProps
} & OmitStrict<NextAppProps<PageProps>, 'pageProps'>
```

To give `Component` the right page props, you can give them to the `NextPage` via the generic:

```diff
- type NextPageWithLayout = NextPage & {
+ type NextPageWithLayout = NextPage<PageProps> & {
```

Now, `Component` receives the right prop types:

![image](https://user-images.githubusercontent.com/29319414/189327970-3603c075-5956-41ec-bfab-5c1e77184b44.png)

**Comment by balazsorban44** [comment]
Hi, `AppType` is not exposed/documented (you are importing it from `next/dist/shared/lib/utils`), so this does not count as a bug. To type the props of App, you can do:

```ts
import type { AppProps } from "next/app"
import type { Session } from "next-auth"
import { SessionProvider } from "next-auth/react"

export default function MyApp(appProps: AppProps<{ session: Session }>) {
  const {
    Component,
    pageProps: { session, ...pageProps },
  } = appProps
  return (
    <SessionProvider session={session}>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
```

**Comment by juliusmarminge** [comment]
> Hi, `AppType` is not exposed/documented (you are importing it from `next/dist/shared/lib/utils`), so this does not count as a bug. To type the props of App, you can do:
> 
> ```ts
> import type { AppProps } from "next/app"
> import type { Session } from "next-auth"
> import { SessionProvider } from "next-auth/react"
> 
> export default function MyApp(appProps: AppProps<{ session: Session }>) {
>   const {
>     Component,
>     pageProps: { session, ...pageProps },
>   } = appProps
>   return (
>     <SessionProvider session={session}>
>       <Component {...pageProps} />
>     </SessionProvider>
>   )
> }
> ```

Thanks for the response. I've always thought the import path has been weird and could probably have guessed it wasn't for official usage.

However... typing arrow function components like `const MyApp: AppType` is very nice imo in that you get typesafety over the props and the return type at the same time. 

Would you accept this as a feature request in exposing this type similar to the AppProps and allow it as a generic
```ts
import type { AppType } from "next/app";

const MyApp: AppType<{ session: Session }> = ({
  Component,
  pageProps
}) => { ... };

export default trpc.withTRPC(MyApp); // example
```

**Comment by balazsorban44** [comment]
Yes, it makes more sense as a feature request, I started working on it already. See #40391
