### ISSUE TITLE
Can't find variable _ after upgrading to Next 12.3

### ISSUE THREAD

**Issue by lionelrudaz** [vercel/next.js#40399]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 6.14.8
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: 11.1.2
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Reproduced with Firefox 104.0.1 and Safari 15.6.1

### Describe the Bug

After upgrading to Next 12.3 this morning, I've immediately had a console error saying "Can't find variable _".

I've debugged my code, because it made no sense. I've upgraded Typescript, no change.

I've finally fixed it by finding the _ variable that was created after compilation, create a new named variable and use it.

My code used to be:

```
switch (component.type) {
```

it's now:

```
let componentType: string = component.type;
switch (componentType) {
```

It is a silly thing, but I've lost plenty of time because of this, and I'm still unclear what's the root cause.

### Expected Behavior

No error after compilation.

### Link to reproduction

It's a private repo

### To Reproduce

Hard to say how to reproduce outside of the code that is provided above. Let me know if I can provide anything more helpful.

**Comment by SukkaW** [comment]
@lionelrudaz Would you mind adding a `.babelrc` file at the root of your project with content `{ "presets": ["next/babel"] }`?

I suspect if it is an issue with SWC compiler. By adding a `.babelrc` file you can opt out SWC.

**Comment by balazsorban44** [comment]
Using the reproduction from #40405 indeed, it seems to be an SWC issue.

**Comment by SukkaW** [comment]
Just disscussed the issue with some SWC contributors. It seems that issue might be related with SWC's recent generator transpiling changes.

**Comment by visnup** [comment]
An even simpler reproduction for me is adding this on any page:

```javascript
(async function () {
  console.log(await Promise.resolve("hello"));
})()
```

you can see the [output using swc playground](https://play.swc.rs/?version=1.2.249&code=H4sIAAAAAAAAA9NILK7MS1ZIK81LLsnMz1PQ0FSo5lJQSM7PK87PSdXLyU%2FXSCxPzCxRCCjKz80sTtUrSgVKlKVqKGWk5uTkK2lqWnPVampoAgC8y93WSAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D) uses a `_` variable that is never defined anywhere.

**Comment by cktsun1031** [comment]
To fix this problem

**next.config.js**
```
experimental: {
  browsersListForSwc: true,
  legacyBrowsers: false,
}
```

**package.json**
```
"browserslist": [
  "chrome 105",
  "edge 105",
  "android 105",
  "ios_saf 15.6",
  "firefox 104"
]
```
