### ISSUE TITLE
Top score in Lighthouse from the start

### ISSUE THREAD

**Issue by vicasas** [vercel/next.js#40418]
### Describe the feature you'd like to request

I would like that from the beginning when creating a new project with Next.js, using `npx create-next-app@latest` I can get the maximum score in Lighthouse.

Today it is currently giving a 97% score due to the fact that it does not explicitly have the `lang="en"` attribute on the `<html>` element or tag.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/57921784/189469152-71822b35-5d17-4098-94fb-62d9ff52550c.png">

<img width="616" alt="image" src="https://user-images.githubusercontent.com/57921784/189469142-3350e902-5a38-48aa-82d3-703223ed620c.png">

### Describe the solution you'd like

Solutions:

1. Add a `_document` file to the template by adding the `lang="en"` attribute.
2. If you don't want to add a new file, the default code since there is no `_document` should have a `lang="en"` attribute.

### Describe alternatives you've considered

N/A

**Comment by Anishpras** [comment]
@balazsorban44 I would like to work on this issue.

**Comment by marcellocurto** [comment]
Seems like this has been fixed.

I just deployed a new Next.js `14.2.3` installation on Vercel, and it scores 100 across the board.

Here is the site: [https://lighthouse-two.vercel.app](https://lighthouse-two.vercel.app)

Here are the Lighthouse results: [https://pagespeed.web.dev/analysis/https-lighthouse-two-vercel-app/h5wuy6tna5?form_factor=mobile](https://pagespeed.web.dev/analysis/https-lighthouse-two-vercel-app/h5wuy6tna5?form_factor=mobile)"

<img width="1018" alt="Screenshot 2024-05-08 at 17 15 27" src="https://github.com/vercel/next.js/assets/10226442/30f567bb-cb6d-42c9-a43c-806ba5a222f7">

**Comment by vicasas** [comment]
@marcellocurto Is it using Page or App router?

**Comment by marcellocurto** [comment]
@vicasas I used it with App router. I just checked with Page router locally and <html> has a lang attribute now.

<img width="588" alt="Screenshot 2024-05-12 at 12 59 51" src="https://github.com/vercel/next.js/assets/10226442/d00bff76-fa25-4502-9bb1-e003895e07b7">

**Comment by iamharshil** [comment]
@balazsorban44 Hey, can I fix this issue if it's still available.??

**Comment by vicasas** [comment]
@iamharshil From what I understand this has already been corrected. Now we obtain 100% of the score from the beginning using page or app router. I don't know why it's not closed, I'll close it.
