### ISSUE TITLE
window.gtag is not defined for Next.js-hydration event

### ISSUE THREAD

**Issue by Littletonconnor** [vercel/next.js#40410]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```sh
    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Sep 09 2022 11:36:36 GMT-0700 (Pacific Daylight Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.10
      pnpm: 7.9.5
    Relevant packages:
      next: 12.3.1-canary.0
      eslint-config-next: N/A
      react: 17.0.1
      react-dom: 17.0.1
```

### Which example does this report relate to?

with-google-analytics

### Describe the Bug

calling `reportWebVitals` when having google analytics setup using `with-google-analytics` results in `Next.js-hydration` event getting triggered BEFORE gtag is initialized.

This could be problematic in production if someone is just assuming `gtag` is always defined when reporting on web vitals.

### Expected Behavior

When having google analytics setup using the `with-google-analytics` example, I would expect `gtag` to be defined for all events before triggering `reportWebVitals`.
 

### To Reproduce

Here is a link to reproduce: https://stackblitz.com/edit/nextjs-rnaue8?file=pages%2F_app.js,.env.local.example,lib%2Fgtag.js,pages%2Findex.js

**Comment by grayaustinc** [comment]
Typically you would want to add a [Data Layer](https://developers.google.com/tag-platform/devguides/datalayer#installation). 
 With this, any commands will be processed after gtag is loaded.

**Comment by hayitsdavid** [comment]
Hey @Littletonconnor I can work on this one.
