### ISSUE TITLE
Next/future/image blur placeholder renders with visual artifacts

### ISSUE THREAD

**Issue by iominh** [vercel/next.js#40419]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 105.0.5195.102

### How are you deploying your application? (if relevant)

Vercel and Linode (occurs in all environments)

### Describe the Bug

When using the Image component from ```next/future/image``` with a blur placeholder and base64 blurDataURL, the placeholder renders in Chrome 105.0.5195.102 with visual artifacts, likely because the placeholder is being requested with a different request URL (i.e. we specified a ```data:image/jpeg;``` but the placeholder in the browser is being requested as ```data:image/svg+xml``` with an svg filter applied

I deployed an example to https://nextjs-next-image-issue.vercel.app/ and https://github.com/iominh/nextjs-next-image-issue.

It might be hard to see the blur placeholder but if you use the chrome devtools to apply heavy throttling (e.g. with 3g) and/or just look at the devtools you'll see the placeholder is loaded incorrectly with visual artifacts and the wrong requestURL

Here's an example based on Next 12.3.0 and React 18.2.0:

```tsx
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/future/image";
import styles from "../styles/Home.module.css";

// Sample blur
export const blurDataURL =
  "data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAIRAAAQMEAQUAAAAAAAAAAAAAAQACAwQFCBETITJEUdL/xAAVAQEBAAAAAAAAAAAAAAAAAAAFBv/EABoRAQEAAgMAAAAAAAAAAAAAAAECABIEMUH/2gAMAwEAAhEDEQA/AJLRkG+kgbELPTyxcXQOlc0k++0rKkyA3I4mxU+yT5DvhEVZrIqHeFxx4p1fM//Z";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          The below image should blur without visual artifacts
        </div>
        <Image
          src="/tuqa-nabi-uhnZZUaTIOs-unsplash.jpg"
          alt="Kitten"
          width={2848}
          height={4288}
          placeholder="blur"
          blurDataURL={blurDataURL}
        ></Image>
     
      </main>
    </div>
  );
};

export default Home;

```

In the chrome dev tools you can see the placeholder renders like the following:

![image](https://user-images.githubusercontent.com/1434477/189472595-0f4a36c7-4744-47a5-9583-e9f51ad7d264.png)

### Expected Behavior

I would've expected the placeholder to render without artifacts and with the correct type

Before next/future/image, the next/image component would return a placeholder like the following:

```
data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAIRAAAQMEAQUAAAAAAAAAAAAAAQACAwQFCBETITJEUdL/xAAVAQEBAAAAAAAAAAAAAAAAAAAFBv/EABoRAQEAAgMAAAAAAAAAAAAAAAECABIEMUH/2gAMAwEAAhEDEQA/AJLRkG+kgbELPTyxcXQOlc0k++0rKkyA3I4mxU+yT5DvhEVZrIqHeFxx4p1fM//Z
```

Instead it now returns the following:

```
data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 2400 1601'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='20'/%3E%3CfeComponentTransfer%3E%3CfeFuncA type='discrete' tableValues='1 1'/%3E%3C/feComponentTransfer%3E%%3C/filter%3E%3Cimage filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAHAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAQF/8QAIRAAAQMEAQUAAAAAAAAAAAAAAQACAwQFCBETITJEUdL/xAAVAQEBAAAAAAAAAAAAAAAAAAAFBv/EABoRAQEAAgMAAAAAAAAAAAAAAAECABIEMUH/2gAMAwEAAhEDEQA/AJLRkG+kgbELPTyxcXQOlc0k++0rKkyA3I4mxU+yT5DvhEVZrIqHeFxx4p1fM//Z'/%3E%3C/svg%3E
```

### Link to reproduction

https://nextjs-next-image-issue.vercel.app/, https://github.com/iominh/nextjs-next-image-issue

### To Reproduce

Go to https://nextjs-next-image-issue.vercel.app/ to see the placeholder load or create an image like shown in the description above

**Comment by iominh** [comment]
As a workaround, I think I may look at the next.js middleware to rewrite the placeholders

**Comment by menberg** [comment]
Same happens on Safari. The problem lies in the ComponentTransfer filter.

By the way, the new default behaviour feels quite opinionated. DX would be much better if we can opt out from this. The additional compute intense Gaussian blur filter creates a lot of overhead, which is often simply not needed:

`data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http%3A//www.w3.org/2000/svg' viewBox='0 0 undefined undefined'%3E%3Cfilter id='b' color-interpolation-filters='sRGB'%3E%3CfeGaussianBlur stdDeviation='20'/%3E%3CfeComponentTransfer%3E%3CfeFuncA type='discrete' tableValues='1 1'/%3E%3C/feComponentTransfer%3E%%3C/filter%3E%3Cimage filter='url(%23b)' x='0' y='0' height='100%25' width='100%25' href='data:image/jpeg;base64,/9j/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAFAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAbEAACAwEBAQAAAAAAAAAAAAABAgADBBEFYf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGhEAAgIDAAAAAAAAAAAAAAAAAQIAAxIxQf/aAAwDAQACEQMRAD8Aj+rq0X+NZgbRcMD5wjUBzxmUgqx+jnIiJWCnkRa66M//2Q=='/%3E%3C/svg%3E`

https://github.com/vercel/next.js/blob/c3ceeb03abb1b262032bd96457e224497d3bbcef/packages/next/shared/lib/image-blur-svg.ts

**Comment by menberg** [comment]
Temporary fix:

use `tableValues='0 1'` instead of `'1 1'`.
https://github.com/vercel/next.js/blob/c3ceeb03abb1b262032bd96457e224497d3bbcef/packages/next/shared/lib/image-blur-svg.ts#L21

**Comment by menberg** [comment]
By the way, what is `height='100%25'` and `width='100%25'` doing? Is this valid syntax?

**Comment by styfle** [comment]
This is likely because the aspect ratio of the of the provided `blurDataURL` doesn't match the aspect ratio provided by `width` and `height`.

- 10 / 7 = 1.428
- 2848 / 4288  = 0.66
