### ISSUE TITLE
[next/image] Lighthouse inconsistencies

### ISSUE THREAD

**Issue by vicasas** [vercel/next.js#40417]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: 12.3.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome Versión 105.0.5195.102 (Build oficial) (arm64)

### How are you deploying your application? (if relevant)

next build & next start

### Describe the Bug

I created a new Next.js project (using the CLI), which immediately when audited through Lighthouse seems to throw up inconsistencies in the improvement information for different points.

The audit indicates that the image does not explicitly have the `width` and `height` attributes and as additional information it tells me to use the `next/image` component for better image handling.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/57921784/189468150-998792da-2e10-47ad-9021-32fdaf2620c8.png">

* The image corresponds to the Vercel logo in the footer.

Which is strange, since both sizes of the image are explicitly included in the JSX.

```jsx
<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
```

* The test is done in an incognito window, running `npm run build` and `npm start`

### Expected Behavior

The expected behavior is that the audit can pass successfully when scanning the image, without indicating that the size attributes are missing.

### Link to reproduction

https://codesandbox.io/s/polished-butterfly-f7cybc?file=/pages/index.tsx

### To Reproduce

1. Create a new project using `npx create-next-app@latest` (using the Vercel logo in the footer as a test) or in an existing one add an image using `next/image` setting the size properties `width` and `heigth`.
2. Run `npm run build` and `npm start`.
3. Go in an incognito window to the localhost URL (http://localhost:3000/).
4. In the DevTools start a Lighthouse audit session.
5. Check the output information, an error appears indicating that you must specify the size of the image.

**Comment by balazsorban44** [comment]
This should be fixed in Lighthouse by now, check the version in your browser to make sure it's included already.

See also https://github.com/vercel/next.js/issues/39376#issuecomment-1229201173

**Comment by vicasas** [comment]
I am seeing the error with the latest version of Chrome.

![image](https://user-images.githubusercontent.com/57921784/189488085-78c2d25b-df53-4fcc-a4b3-f7cb7056b70a.png)
