### ISSUE TITLE
After setting basePath in next.config.js, dynamic route parameters won't be included inside `router.query` object (useRouter) when routing from one page to another.

### ISSUE THREAD

**Issue by ABDELMAJIDRami** [vercel/next.js#40432]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022
    Binaries:
      Node: 18.6.0
      npm: 8.13.2
      Yarn: 0.32+git
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.0
      eslint-config-next: 12.2.3
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

**This bug only happens when:**
1. adding **basePath** (exp: '/manager') to **next.config.js**, and
2. a custom **middleware.ts** is used

It is similar to ['#38495'](https://github.com/vercel/next.js/issues/38495) but with basePath used.

Routing from page _'/manager'_ to _'/manager/properties/1'_ using `<Link href={{pathname: '/properties/[id]', query: { id: property.id }}} passHref>...</Link>`, **router = useRouter()** object in the second page will have its `router.query = {}`; an empty object.
If you reload the page _'/manager/properties/1'_, `router.query` will be loaded correctly `= {id: '1'}` but then will default to `{}` when routing to another dynamic and/or nested page.

**_Noting that this issue won't arise (and router.query will load correctly) if you delete basePath from next.config.js_**

### Expected Behavior

An expected behavior is to have `router.query = {id: '1'}` after redirecting from the first page to the second page described in previous point. 

### Link to reproduction

https://github.com/ABDELMAJIDRami/basepathrouterbug

### To Reproduce

- clone project and install dependencies
- next dev
- open page `http://localhost:3000/manager`
- click the Link to redirect to 'manager/properties/1' page (Page B)
- page B shows the result of router.query object. Check console logs where i logged the router object (useRouter).
- Reload page B and check router.query again

**Comment by flyboarder** [comment]
This is also happening on NextJS version 12.2
