### ISSUE TITLE
Docs: Update needed

### ISSUE THREAD

**Issue by TheAlmightyDada** [vercel/next.js#40446]
### What is the improvement or update you wish to see?

I think the basics/assets-metadata-css/css-styling needs updating as it references folders that do not exist in the repo.

### Is there any context that might help us understand?

Hello,

In the documentation, it talks about a 'styles' folder with `globals.css` and a CSS module `Home.module.css` however that folder and those files do not exist. It looks like the project is now using styled-jsx as all of the styling is within the individual pages. But I'm not sure.

Unless I've misunderstood I think this needs updating in the documentation

Thanks

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/assets-metadata-css/css-styling

<sub>[DX-1668](https://linear.app/vercel/issue/DX-1668/docs-update-needed)</sub>

**Comment by aldairandre** [comment]
Hey man, I started studying Next.js today and I thought something was wrong with my model, but now that I see your problem, my heart starts beating again, it needs to be updated.

**Comment by samcx** [comment]
I can see both are being CSS styles used in https://github.com/vercel/next-learn/tree/main/basics/assets-metadata-css-starter so this should be fine!
