### ISSUE TITLE
create-next-app creates wrong example

### ISSUE THREAD

**Issue by aranyadan** [vercel/next.js#40453]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

NA

### Describe the Bug

running 
`yarn create next-app --example with-tailwindcss with-tailwindcss-app` 

creates a **broken package** with sections of with-tailwindcss-**emotion** also present

### Expected Behavior

Expect a with-tailwindcss project, instead get a broken project with parts of tailwindcss-emotion added as well. Works fine with 12.2.5.

### Link to reproduction

NA

### To Reproduce

yarn create next-app --example with-tailwindcss with-tailwindcss-app

**Comment by sam-kmn** [comment]
Just came across this issue. That's a pity, I was using it very often.

**Comment by ArtisJr** [comment]
I can confirm that I am seeing this issue also.

**Comment by balazsorban44** [comment]
Duplicate of #40389
