### ISSUE TITLE
app fails to load after running `npm run dev` from fresh project

### ISSUE THREAD

**Issue by crathor** [vercel/next.js#40458]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: 12.3.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

N/A but it's Chrome 105.0.5195.102

### Describe the Bug

Getting an error immediately after bootstrapping a fresh project and trying to run it.

### Expected Behavior

Application runs and starts up on the default application screen

### Link to reproduction

No tools seem to replicate this

## using NPM

`node v16.17.0 | npm v8.15.0`

`npx create-next-app@latest test-project --typescript` or `npx create-next-app@canary test-project --typescript`
`cd test-project`
`npm run dev`

```
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./styles/globals.css
Error: Cannot find module 'caniuse-lite/data/features/css-unicode-bidi'```

**Comment by klanmiko** [comment]
having the same issue on windows 10, node v18.9.0, create-next-app version 12.3.0

**Comment by bbsweb** [comment]
Because package `caniuse-lite` 1.0.30001394 delete the `css-unicode-bidi.js` file

Temporary solution: add `"caniuse-lite": "1.0.30001393",` to the `package.json`

**Comment by klanmiko** [comment]
that works, thanks!

**Comment by Rongeegee** [comment]
I fixed this issue by manually moving css-unicode-bidi.js from project of older version to node_modules/caniuse-lite/data/features

**Comment by crathor** [comment]
Thanks @bbsweb that worked for me too!
