### ISSUE TITLE
Link not working correctly on Firefox

### ISSUE THREAD

**Issue by Marius-brt** [vercel/next.js#40450]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.0
      eslint-config-next: 12.3.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Firefox

### Describe the Bug

I'm using link in my navbar. Links working great in mobile (ios) and google chrome (desktop) but on Firefox (desktop) I need to double click to open it.

### Expected Behavior

Change page with link component

### Link to reproduction

none

### To Reproduce

```jsx
<Link href="/about">
<a>About</a>
</Link>
```

**Comment by Marius-brt** [comment]
After relaunching my computer its working great on firefox. I think it was a bug of Firefox.

**Comment by Abdillah** [comment]
I experiencing this issue, even with `<button onClick={handler}></button>`.
I can't get rid of this even after restart on Firefox 105.0 (64-bit).
