### ISSUE TITLE
ESLint fails for next/core-web-vitals

### ISSUE THREAD

**Issue by Erythros** [vercel/next.js#40469]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.0
      eslint-config-next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0
===
PhpStorm 2022.2.1
Build #PS-222.3739.61, built on August 18, 2022

### What browser are you using? (if relevant)

Chrome 105.0.5195.102

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

ESLint not working with eslint-config-next.
```
Error: Failed to load config "extends: next/core-web-vitals" to extend from.
```

At first I thought it was related to #35606 but doesm't seem to work with the latest canary version either.

### Expected Behavior

For ESLint to catch and report errors in my files

### Link to reproduction

https://github.com/contentstack/contentstack-nextjs-starter-app

### To Reproduce

```
npm i

next lint
```
(`npm install next@canary ` as well to test on the latest version)

**Comment by balazsorban44** [comment]
You have a typo on this line:

https://github.com/contentstack/contentstack-nextjs-starter-app/blob/0ded87360e40cafb3858f22b528390d2b708d31a/.eslintrc.json#L9

You need to change it like so:

```diff
-       "extends: next/core-web-vitals"
+       "next/core-web-vitals"
```

Heads up, your path matcher does not any file, because you define `pages/**/*.jsx` but you only have `tsx` files.

```diff
-    "lint": "next lint pages/**/*.jsx"
+    "lint": "next lint"
```

should fix that problem too.
