### ISSUE TITLE
Acess Imagens In public page

### ISSUE THREAD

**Issue by Pedromdsn** [vercel/next.js#40500]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

https://github.com/Pedromdsn/NextJS-StartKit

### Describe the Bug

I cannot access images in the public folder.

![image](https://user-images.githubusercontent.com/57453260/189795639-b10d2946-27b7-4496-960f-0aef7d29f3c7.png)
![image](https://user-images.githubusercontent.com/57453260/189795662-60934483-301f-48b2-aeaf-58b5d834ce8d.png)

It doesn't work with absulute imports either.

### Expected Behavior

I would like to be able to import the image to be able to use `Image` without having to say what the height and width are.

### Link to reproduction

https://github.com/Pedromdsn/NextJS-StartKit

### To Reproduce

I don't know, I just downloaded the template and tried to get the images.

**Comment by balazsorban44** [comment]
You have a typo. The image shows that the file is called `backgroud-galaxy.png`.
