### ISSUE TITLE
Wrong legacy decorator compilation when using browsersListForSwc

### ISSUE THREAD

**Issue by felixmosh** [vercel/next.js#40507]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 3.2.1
      pnpm: 7.5.0
    Relevant packages:
      next: 12.2.3
      eslint-config-next: 12.3.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

chrome 105

### Describe the Bug

When compiling to **production** a class component with legacy decorators, the order of invocation is wrong.

Libs like MobX requires a specific decorator order, `observer` **after** `inject` otherwise, it throws.

### Expected Behavior

SWC compilation should remain the correct order of invocation.

### Link to reproduction

no production builds

### To Reproduce

```js
import { inject, observer } from 'mobx-react';
import {observable } from 'mobx';

@inject('myStore')
@observer
export class Component extends React.Component {
  @observable private isLoading = true;
  public render() {
    return <div>{this.isLoading? 'loading': 'done'}</div>
  }
}
```

When using in `next.config.js`
```js
// next.config.js
module.exports = {
  experimental: {
    browsersListForSwc: true,
    legacyBrowsers: false,
  },
}
```

And browser list with 
```json
// package.json
{
  "browserslist": {
    "production": [
      "> 0.5% and not dead"
    ],
    "development": [
      "last 1 version"
    ]
  },
}
```

**Comment by balazsorban44** [comment]
It could be a bug in SWC transforms, and I'm trying to reproduce, but the reproduction code provided is not runnable in its current form. Searching for this pattern I end up on the following page that says this pattern is obsolete:

https://mobx-react.js.org/recipes-inject#:~:text=The%20store%20injection%20pattern%20was,don't%20do%20drugs).

Could you please add an up-to-date reproduction repository to this issue that we can use to debug/test? :pray:

**Comment by felixmosh** [comment]
I'm not able to reproduce it from scratch :|
