### ISSUE TITLE
[NEXT-582] Unable to define multiple Set-Cookie headers via config headers

### ISSUE THREAD

**Issue by awareness481** [vercel/next.js#40518]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:42 PST 2022; root:xnu-7195.141.26~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.15.1
      npm: 8.19.1
      Yarn: N/A
      pnpm: 7.6.0
    Relevant packages:
      next: 12.3.1-canary.1
      eslint-config-next: 12.3.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

It is impossible to define multiple `Set-Cookie` headers, via [next.config.js/headers](https://nextjs.org/docs/api-reference/next.config.js/headers). Next.js seems to only account for the last defined `Set-Cookie` header for a given path

### Expected Behavior

Based on the [rfc](https://www.rfc-editor.org/rfc/rfc6265.txt#:~:text=Origin%20servers%20SHOULD%20NOT%20fold%20multiple%20Set%2DCookie%20header%20fields%20into%0A%20%20%20a%20single%20header%20field.) I would expect to be able to define multiple `Set-Cookie` headers and for the headers to not be combined into one header. (they re not combined atm, only the last header is used)

### Link to reproduction

https://github.com/awareness481/next-config-cookies

### To Reproduce

1. See that [next.config.js](https://github.com/awareness481/next-config-cookies/blob/main/next.config.js) has two` Set-Cookie` headers for each route
2. Visit `http://localhost:3000/1` and observe that only one cookie is defined
3. Visit `http://localhost:3000/2` and observe that only one cookie is defined

<sub>[NEXT-582](https://linear.app/vercel/issue/NEXT-582/unable-to-define-multiple-set-cookie-headers-via-config-headers)</sub>

**Comment by floriangosse** [comment]
This affects setting multiple `Link` headers as well. This actually a blocker for doing performance optimizations via `preconnect`, `preload`, ... `Link` headers. And, at the moment doesn't seem to be a workaround.
