### ISSUE TITLE
Async function breaks assigning to new objects in for loops

### ISSUE THREAD

**Issue by tobysmith568** [vercel/next.js#40535]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

Not relevant

### Describe the Bug

Assigning to an object in a for loop inside an async function seems to not work properly. It seems to always assign the final value to be iterated over.

![image](https://user-images.githubusercontent.com/22356255/190033121-18634bec-af20-4cda-b66e-2771751e2cb8.png)

The `works` array only has string literals pushed to it, so it works as expect and ends up with `["one", "two", "three"]`.

The `broken` array has objects assigned to it, so it is broken and gets `[{ input: "three }, { input: "three }, { input: "three }]` even though it's assigned to with the exact same variable in the exact same for loop.

Everything works as expected when it's not an async function.

This *cannot* be reproed on `next@12.2.6-canary.8`  
But can be reproed on `next@12.2.6-canary.9` and it remains present in `next@canary` as of 14/09/22.

See the README in the attached repro for more details.

### Expected Behavior

Both the `works` and `broken` arrays should get `"one"`, `"two"`, and `"three"`.

### Link to reproduction

https://github.com/tobysmith568/nextjs-repro

### To Reproduce

Push objects to an array using a for loop in an async function.

![image](https://user-images.githubusercontent.com/22356255/190033121-18634bec-af20-4cda-b66e-2771751e2cb8.png)

**Comment by rubytree33** [comment]
Could you paste the code in the screenshot?

**Comment by discretegames** [comment]
I think I have the same issue from pushing object literals in an async function, though my code isn't in a for loop. I had a line like

```ts
myarray.push({ a: await myfunc(), b: 123 });
```

in an async function and it works in `next@12.2.6-canary.8` but fails in `next@12.2.6-canary.9` saying `TypeError: Cannot convert undefined or null to object`. However, these (should-be) equivalent snippets did both work in `next@12.2.6-canary.9`:

```ts
const a = await myfunc();
myarray.push({ a, b: 123 });
```

```ts
const obj = { a: await myfunc(), b: 123 };
myarray.push(obj);
```

**Comment by magic-akari** [comment]
This is a bug in swc.

https://play.swc.rs/?version=1.3.0&code=H4sIAAAAAAAAA11QQQqDMBC8%2B4ohpwTEB1TSQ99Q6KF4aCVWUbJiFCni3xs3RqSXJMzMzsymJOtGdPRpSmi83NeWkAr6iiUBSmYb20%2Bj8%2FRTkDUihRhn4qsejBFFcihnGloWFvmBvQdqjT1AwB8VDZAnc1C1pyjODbPUmcw3k8ykWHbtyk9338IvsQS01pFXecIe3CbrJ1cHCxXyQ6GAL6cZYI2bxGTx2Cz8qmyl8n%2F6xlaeD55esPps%2Fk2p8h9C6eqlXAEAAA%3D%3D&config=H4sIAAAAAAAAAy2LQQ6AIAwE%2F9IzVz3wBx%2FRYDUYUNKWRGL4u9R4252dfeCQAP6BgizElqSdijd4oJBRAsei4IY20IZJqDtQ5J3UFJlg9HytNZGdtRX6%2BGw8yvIvypX6C9UPjkhtAAAA

**Comment by tobysmith568** [comment]
@magic-akari thanks for the quick fix in https://github.com/swc-project/swc/pull/5861.
However, I wonder if this should this have been auto-closed by the completion of https://github.com/swc-project/swc/pull/5861 ?

I would have assumed this should stay open until there's a new patch release of @swc/helpers and next.js is updated to use it. In the meantime other people might come and open more issues here while the bug is still reproducible in next@canary.

**Comment by kdy1** [comment]
Oh I missed it.
It will be fixed by https://github.com/vercel/next.js/pull/40520
