### ISSUE TITLE
Docs: Incorrect url in next/server docs

### ISSUE THREAD

**Issue by awareness481** [vercel/next.js#40539]
### What is the improvement or update you wish to see?

Clicking [Using cookies in Edge Middleware](https://nextjs.org/docs/api-reference/next/server#using-cookies-in-edge-middleware)
<details>
<summary>Screenshot of the link</summary>
<img src='https://user-images.githubusercontent.com/12380586/190064020-22440201-205d-46d8-a8f9-14e2d49daf49.png' alt='screenshot' >
</details>

doesn't do anything. Should it instead link to https://nextjs.org/docs/advanced-features/middleware#using-cookies ?

### Is there any context that might help us understand?

In the API reference of `NextRequest`, there is a link in the `cookies` description that is invalid

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/server

**Comment by balazsorban44** [comment]
Thanks, this was fixed in https://github.com/vercel/next.js/commit/3851d9065fd2cdf4b3dbef4a11667e4a224a5113

The update to the page will go out together with the next `latest` release.
