### ISSUE TITLE
custom component rendering next/script with beforeInteractive strategy

### ISSUE THREAD

**Issue by helloheesu** [vercel/next.js#40545]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.2
      eslint-config-next: 12.0.7
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome 105.0.5195.102 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

nx serve

### Describe the Bug

I am inserting a custom function component in `_document.tsx` that is rendering next/script with beforeinteractive strategy.
The component is getting executed in server-side, that I can see the console. (`console.log("prepare");` in below example)

However the script is not getting rendered in client-side. I can't find any element with id (`google-analytics` in example) and console in inline script is not shown (`console.log("HI")`).
When I insert the script directly with next/script, as I commented out in example below, it gets rendered properly that I can find the element with given id and see the console from browser. It does not work only when I insert as custom component.

![image](https://user-images.githubusercontent.com/5011544/190078443-4bff39a7-381f-454a-9350-e620e82d4449.png)
![image](https://user-images.githubusercontent.com/5011544/190079315-91a918c4-4446-40a8-ad73-9cfda5168380.png)

### Expected Behavior

The script should get rendered even when I insert it as custom component.

### Link to reproduction

https://codesandbox.io/s/vigilant-shape-djm4pu

### To Reproduce

check both server-side console and client-side console, comparing either with PrepareGAScript component / Script on _document.tsx

**Comment by SukkaW** [comment]
The only components you are allowed to put in your custom `_documents` are normal HTML tags, `next/script` and `Html`, `Head`, `Main`, and `NextScript` exported from `next/document`. Other than those are not allowed in the custom `_documents`.

**Comment by helloheesu** [comment]
> The only components you are allowed to put in your custom `_documents` are normal HTML tags, `next/script` and `Html`, `Head`, `Main`, and `NextScript` exported from `next/document`. Other than those are not allowed in the custom `_documents`.

Thanks for the comment. Is that described in the docs? I have read [custom document page](https://nextjs.org/docs/advanced-features/custom-document) and I can't find it, but it might be because of my English.

**Comment by SukkaW** [comment]
It is the implementation detail of `next/script`.

Next.js uses `React.Children` util API to scan `next/script` usage in your `_document`. If you place custom component directly in `_document`, it can not be identified by Next.js.

**Comment by ijjk** [comment]
The docs do mention that `next/script` with `beforeInteractive` does need to be placed only inside of `_document` for it to work correctly here https://nextjs.org/docs/basic-features/script#beforeinteractive so I think we can close this out.
