### ISSUE TITLE
Static HTML Export, 404 on core js files

### ISSUE THREAD

**Issue by jonrrivera** [vercel/next.js#40559]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

static html

### Describe the Bug

when statically building my application (running `next build && next export`). The  `index.html` file in the `/out` directory is getting multiple 404s, see below:

<img width="727" alt="Screen Shot 2022-09-08 at 5 01 29 PM-1" src="https://user-images.githubusercontent.com/18686388/190250463-ae3d8366-b348-419e-bdcd-faad3a134cb0.png">

I ended up figuring out this is because the `scipts` in the `index.html` file are absolute:

<img width="802" alt="Screen Shot 2022-09-14 at 12 38 01 PM" src="https://user-images.githubusercontent.com/18686388/190250616-097d23d9-b8bb-40ab-9827-4d67753535c7.png">

I order to run my app statically, and not use a run time like [serve](https://www.npmjs.com/package/serve) I have to change the paths to be relative:

<img width="824" alt="Screen Shot 2022-09-14 at 1 00 49 PM" src="https://user-images.githubusercontent.com/18686388/190250820-e05b86c9-1e1d-43e1-976d-cca087b3503e.png">

I've been looking all around on hot to automate this, is this a bug or are there better ways to go about this

### Expected Behavior

being able to control if `_next` is absolute or relative referenced during HTML static build

### Link to reproduction

https://github.com/vercel/next.js/tree/canary/examples/with-static-export

### To Reproduce

follow these instructions to Statically Deploy: https://nextjs.org/docs/advanced-features/static-html-export

go in the `/out` directory and open the index html file, you will see in the console that the core js files are 404. In order to fix, you need to change to relative paths

**Comment by SukkaW** [comment]
@jonrrivera Have you checked the `basePath` feature provided by Next.js?

https://nextjs.org/docs/api-reference/next.config.js/basepath

It enabled you to run a Next.js App in a sub-directory, which is exactly your case.

**Comment by JanKaifer** [comment]
Closing as resolved. Thanks, @SukkaW
