### ISSUE TITLE
Returning notFound from getStaticProps causes an error during next export

### ISSUE THREAD

**Issue by woedoe** [vercel/next.js#40571]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.2
      eslint-config-next: 12.3.0
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

next export

### Describe the Bug

If a page returns { notFound: true } from getStaticProps, then running next build && next export will result in an error.

It seems like `next export` expects an html file to be present, but there isn't one.

I found the exact bug here [https://github.com/vercel/next.js/issues/24422](https://github.com/vercel/next.js/issues/24422) but it's closed and a fix is implemented in 12.0.0. Nevertheless I still get the bug using 12.3.1.

### Expected Behavior

No error message, next export finishes successfully, visiting the page in production results in a 404 just like when I use next build && next start locally

### Link to reproduction

https://github.com/woedoe/nextJSExportError

### To Reproduce

1. Setup the project with` create next-app --typescript `
2. In pages/index.js add
`export async function getStaticProps() {
  return {
    notFound: true,
  };
}`
3. next build runs successfully, next export fails with the error:

> [Error: ENOENT: no such file or directory, copyfile '\next-test-app\.next\server\pages\index.html' -> '\next-test-app\out\index.html'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '\\next-test-app\\.next\\server\\pages\\index.html',
  dest: '\\next-test-app\\out\\index.html'
}

**Comment by balazsorban44** [comment]
We seem to have a test case for this that is passing :thinking:

https://github.com/vercel/next.js/blob/33a6dca74727bf4c4954b0c1e38d016dc382b74c/test/integration/export/pages/gsp-notfound.js#L1-L3

https://github.com/vercel/next.js/blob/33a6dca74727bf4c4954b0c1e38d016dc382b74c/test/integration/export/test/browser.js#L196-L214

But somehow I am able to reproduce. Will investigate.
