### ISSUE TITLE
Docs: getStaticProps & InferGetStaticPropsType | TypeScript

### ISSUE THREAD

**Issue by sicikh** [vercel/next.js#40607]
### What is the improvement or update you wish to see?

![image](https://user-images.githubusercontent.com/88524276/190628526-b115506b-31a3-4adf-9ad1-a1bffc98c296.png)

In the documentation, it is advised to type getStaticProps first, and then in the example with InferGetStaticPropsType, getStaticProps is not typed. The documentation should specify this type behavior explicitly. All examples of type behavior are listed in the examples below.

The same with the other rendering methods

### Is there any context that might help us understand?

Example 1. InferGetStaticPropsType is working as expected. Object `posts` in page Posts is type `types.Post[]`.
```
const Posts = ({ posts }: InferGetStaticPropsType<typeof getStaticProps>) => {
    ...
};

export const getStaticProps: GetStaticProps<{ posts: types.Post[] }> = async () => {
    let data: {
        allPosts: types.Post[];
    };

   // fetching data

    const posts = data.allPosts;
    return {
        props: {
            posts,
        },
    };
};
```

Example 2. The same as in the previous example, but the getStaticProps type is specified implicitly. This example is listed in the documentation.
```
const Posts = ({ posts }: InferGetStaticPropsType<typeof getStaticProps>) => {
    ...
};

export const getStaticProps = async () => {
    let data: {
        allPosts: types.Post[];
    };

   // fetching data

    const posts = data.allPosts;
    return {
        props: {
            posts,
        },
    };
};
```

Example 3. InferGetStaticPropsType is not working. Object `posts` in page Posts is type `any`.
```
const Posts = ({ posts }: InferGetStaticPropsType<typeof getStaticProps>) => {
    ...
};

export const getStaticProps: GetStaticProps = async () => {
    let data: {
        allPosts: types.Post[];
    };

   // fetching data

    const posts = data.allPosts;
    return {
        props: {
            posts,
        },
    };
};
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/data-fetching/get-static-props#getstaticprops-with-typescript

**Comment by balazsorban44** [comment]
Thanks for pointing this out, want to open a PR?

Here is the file that needs to be edited: https://github.com/vercel/next.js/blob/canary/docs/api-reference/data-fetching/get-static-props.md

**Comment by sicikh** [comment]
> Thanks for pointing this out, want to open a PR?
> 
> Here is the file that needs to be edited: https://github.com/vercel/next.js/blob/canary/docs/api-reference/data-fetching/get-static-props.md

Thank you for the answer and for specifying a documentation file, the link to the PR will be there tomorrow.

**Comment by sicikh** [comment]
> Thanks for pointing this out, want to open a PR?
> 
> Here is the file that needs to be edited: https://github.com/vercel/next.js/blob/canary/docs/api-reference/data-fetching/get-static-props.md

Here is a PR: https://github.com/vercel/next.js/pull/40639
