### ISSUE TITLE
Minified code using incorrect variable scope in 12.3.

### ISSUE THREAD

**Issue by carterm** [vercel/next.js#40621]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**next info**
```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.5.0
      npm: 7.19.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Chrome Version 105.0.5195.125 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

Loop variables that are instantiated inside a for loop are not properly going out of scope.  We have react code that displays a list of data on getServerSideProps by using a for loop, but when it renders inside a useEffect the object used to create the data list is not being properly reset.

### Expected Behavior

Objects creating inside a loop scope should be properly scoped.  The current version requires a redundant reset of object declarations in a loop scope.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-mwqgu8?file=pages/index.tsx

### To Reproduce

1) Notice In the included sample, the list will initially display items 1, 2 & 3 (from the server render).  After 1 second the dom will update using the same method and instead show the last item 3 times.

2) Fork the project and change the next version to 12.2.5 or older and the list will re-render properly.

3) Line 20 has a line of code that if you uncomment will make the code work in any version.
```
  for (let index = 0; index < myData.length; index++) {
    let result = {};
    //uncommenting this line will make the code work with this version
    //result = {};
```

**Comment by carterm** [comment]
Here is a comparison of the minified rendering.

12.2.5
```Javascript
  case 2:
      for (t = ["First", "Middle", "Last"],
      e = [],
      r = 0; r < t.length; r++)
          (u = {}).title = t[r],
          u.index = r,
          e.push(u);
      return n.abrupt("return", {
          props: {
              allResults: e
          }
      });
```

Canary
```Javascript
  case 1:
      for (u.sent(),
      n = ["First", "Middle", "Last"],
      t = [],
      i = {},
      e = 0; e < n.length; e++)
          (r = i).title = n[e],
          r.index = e,
          t.push(r);
      return [2, ((o = {}).props = {
          allResults: t
      }
```


Notice in the 12.2.5 version the object is being reset every time `(u = {})`  
vs
Canary version the loop object `(r = i)` is being re-used.

**Comment by ijjk** [comment]
Hi, this should be corrected in the latest canary of Next.js `v12.3.1-canary.3`, please update and give it a try!

**Comment by carterm** [comment]
I have confirmed that the issue is RESOLVED in Next.js `v12.3.1-canary.3`.
