### ISSUE TITLE
Unable to use library with non-fully-specified imports, even with fullySpecified false, with webpack 5

### ISSUE THREAD

**Issue by bdwain** [vercel/next.js#40632]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 14.18.1
      npm: 7.10.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.3.1-canary.3
      eslint-config-next: 11.0.1
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I am trying to use a library (a node module I don't control) that contains this import in the packaged code

```js
import _omit from 'lodash/omit';
```

and it does not work with nextjs12 and webpack5. I get this error

```
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data .Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/dev/project/node_modules/lodash/omit' imported from /Users/dev/project/node_modules/library/es/library.js
Did you mean to import lodash/omit.js?
```

I have seen that you need to add `fullySpecifed: false`, to the webpack loaders, and I have tried that a few different ways.

In my next config, i have

```
  experimental: { fullySpecified: false },
```

I also tried modifying the webpack config directly like this

```js
    config.module.rules.push({
      test: /\.m?js$/,
      type: 'javascript/auto',
      resolve: {
        fullySpecified: false,
      },
    });
```

The library has "type": "module" in it, which I think should allow this to work? 

### Expected Behavior

I should be able to import modules that don't fully specify their extensions if i set fullySpecified to false. I am able to get this working in create-react-app using `fullySpecifed: false` in my webpack config

### Link to reproduction

https://github.com/bdwain/next-module-issue

The example library for my issue is at https://github.com/bdwain/bw-test-lib

### To Reproduce

`yarn install && yarn build` in the next project

**Comment by SachinVarghese** [comment]
@bdwain Can you share any workarounds that you may have found in the meantime?

**Comment by bdwain** [comment]
we didn't come up with any @SachinVarghese

**Comment by SachinVarghese** [comment]
I have been able to work around this issue by transpiling the packages that error during the build process, by adding the following to the next config. Not ideal, not recommended, but works.
```
transpilePackages:["lodash"]
```

**Comment by timneutkens** [comment]
Looks like the package is not compatible with Node.js ESM, not much we can do about that in Next.js. Would recommend using `transpilePackages` indeed.
