### ISSUE TITLE
Gifs not loading- TypeError: unsupported file type: undefined (file: undefined)

### ISSUE THREAD

**Issue by alessiogmonti** [vercel/next.js#40689]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64
    Binaries:
      Node: 18.2.0
      npm: 8.9.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

```
import logo from '../assets/logo.gif'
import Image from 'next/image'

const Media = () => (
    <Image src={logo} 
        layout={'responsive'}
        style={{zIndex:2}}
    />
)

```

### Expected Behavior

I expect the gif to load, yet it does not. This works locally, issue occurs when building on vercel.

TypeError: unsupported file type: undefined (file: undefined)
--
19:13:35.810 | at lookup (/vercel/path0/node_modules/next/dist/compiled/image-size/index.js:1:1454)
19:13:35.810 | at Object.imageSize [as default] (/vercel/path0/node_modules/next/dist/compiled/image-size/index.js:1:2131)
19:13:35.810 | at Object.getImageSize (/vercel/path0/node_modules/next/dist/server/image-optimizer.js:658:56)
19:13:35.810 | at /vercel/path0/node_modules/next/dist/build/webpack/loaders/next-image-loader.js:38:85
19:13:35.810 | at Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:26)
19:13:35.810 | at /vercel/path0/node_modules/next/dist/build/webpack/loaders/next-image-loader.js:38:47
19:13:35.810 | at Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:26)
19:13:35.810 | at Object.nextImageLoader (/vercel/path0/node_modules/next/dist/build/webpack/loaders/next-image-loader.js:24:28)

### Link to reproduction

https://codesandbox.io/s/delicate-sky-j2nrow?file=/pages/index.tsx

### To Reproduce

I am using next-js with chakra from the examples.
Place a gif in assets and try to display it on a vercel deploy.

https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui

**Comment by alessiogmonti** [comment]
```
./src/assets/mygif.gif
Module parse failed: Unexpected character '' (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

I receive this error when in my next.config.js I specify: 
```
const nextConfig = {
images: {disableStaticImages: true}
}
module.exports = nextConfig
```

**Comment by balazsorban44** [comment]
This is the expected behavior. Setting `disableStaticImages` disables static image imports. See the docs: https://nextjs.org/docs/api-reference/next/image#disable-static-imports

**Comment by alessiogmonti** [comment]
> This is the expected behavior. Setting `disableStaticImages` disables static image imports. See the docs: https://nextjs.org/docs/api-reference/next/image#disable-static-imports

This was a solution from a 2021 stackoverflow question, I suppose their suggestion was to use webpack's standard loader by disabling the nextjs one.

 I included that as a comment because it seemed relevant, but the original bug persists- please reopen this issue.
