### ISSUE TITLE
Next 12.3.1 breaks rendering `mermaid` digrams on prod with `RangeError: Invalid array length` error but on dev works fine

### ISSUE THREAD

**Issue by B2o5T** [vercel/next.js#40750]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 6.14.4
      Yarn: 1.22.17
      pnpm: 7.12.0
    Relevant packages:
      next: 12.3.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

While updating to next 12.3.1 we figured out that our mermaid diagrams no longer work, and silently break on prod, but render totally fine dev

### Expected Behavior

On 12.3.0 mermaid diagrams renders totally fine on dev/prod

### Link to reproduction

https://github.com/the-guild-org/the-guild-components/tree/077afcb5d7078c53217cadad0c344a92e67f0397

### To Reproduce

```sh
yarn build
yarn workspace website build
yarn workspace website start
```
visit http://localhost:3000/docs/mermaid

see the console.error 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/7361780/191474107-cc946aa0-c8ad-42aa-98e8-98835219ab1b.png">

**Comment by kdy1** [comment]
I found that this is not related to swc minifier

**Comment by kdy1** [comment]
Can you try the https://github.com/vercel/next.js/releases/tag/v12.3.2-canary.43 ? I expect this to be fixed, but I can't build your repro case for unknown reason

**Comment by B2o5T** [comment]
@kdy1 I can confirm that issue with `swcMinify` no longer exist on ` 12.3.2-canary.43` for me. Thank you!

Would you love to take a look at another issue that I discovered with `experimental.optimizeCss: true` option https://github.com/vercel/next.js/issues/41359 ?

I will close this issue since the original problem was solved!
