### ISSUE TITLE
[NEXT-649] next/future/image parent position warning

### ISSUE THREAD

**Issue by filip-kis-fsc** [vercel/next.js#40762]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Microsoft Edge Version 105.0.1343.42 (Official build) (arm64)

### How are you deploying your application? (if relevant)

Not relevant.

### Describe the Bug

The issue is a false positive console warning:
```
Image with src "/_next/static/media/test-image.d677443e.jpg" has "fill" and parent element with invalid "position". Provided "" should be one of absolute,fixed,relative.
```
This can be observed in repro example where the image has the `fill` attribute and parent position is `relative`.

The culprit of this issue seems to be L284 of the following snippet:
https://github.com/vercel/next.js/blob/2b9afcfea3ce1f43833da26324b88693f2b11c8c/packages/next/client/future/image.tsx#L283-L293

[Window.getComputedStyle](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) returns an empty [CSSStyleDeclaration](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration) in case the inspected element is not in the DOM tree.

A potential fix for this would be to add an additional check for `img.parentElement` actually being in the DOM tree on L283.

### Expected Behavior

The false positive console warning should not appear.

### Link to reproduction

https://github.com/filip-kis-fsc/nextjs-future-image-parent-position-issue

### To Reproduce

1. clone repo
2. `cd` project root
3. `yarn`
4. `yarn dev`
5. open dev tools console tab
6. refresh the page
7. observe the false positive warning in the browser dev tools console

<sub>[NEXT-649](https://linear.app/vercel/issue/NEXT-649/nextfutureimage-parent-position-warning)</sub>

**Comment by SukkaW** [comment]
This sounds like a very tricky race condition.

The check performed in dev mode is executed during images' `onLoad`. The only way to trigger this issue is to unmount the component's parent right before the `onLoad` fires, which in most cases will not happen.

**Comment by filip-kis-fsc** [comment]
An example where this issue is prominent is an image rich page where images are rendered within virtualised lists.

In such pages, virtualised list rendered items length will usually differ between SSR and CSR, which can lead to unmount of images as soon as react hydration happens.

This can lead to a lot of false positive warnings which pollute the console.

**Comment by laclance** [comment]
I also get this warning. 

SplashScreen.tsx
```
function SplashScreen() {
  return (
    <div className="relative h-screen w-screen">
      <Image src="/img/bg-sign-in.jpg" alt="TallOrder" fill sizes="100vw, 100vh" />
    </div>
  );
}
```
_App.tsx
```
  if (!ready || !showChild || typeof window === 'undefined') {
    return <SplashScreen />;
  }
```

**Comment by laclance** [comment]
and this `Image with src "/img/logo-dark.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.`

```
    <NoSsr>
      <Image className='select-none' width={width || 194} height={height || 80} src="/img/logo-dark.png" alt="TallOrder" priority />
    </NoSsr>
```

**Comment by gtonussi** [comment]
I also have this issue using Chrome, when the parent div is certainly 'position: relative'

**Comment by walidbillel** [comment]
Damn I was trying to debug this for like an hour thinking I was doing something wrong where I was literally following the documentation word by word implementing all the methods.

**Comment by blackMoja** [comment]
I'm also experiencing console warning in the same way.

Is there a solution related to the above issue? 👀
The same symptoms are occurring in the following situations.
```typescript
<DownLoad>
  <Image src={link.img} alt={link.alt} loader={imageLoader} width={26} height={20} />
</DownLoad>
```

**Comment by laclance** [comment]
The warning also seemed to be happening intermittently, but after adding `style={{position: 'relative'}}` to my Image component's parent div instead of a className I have not seen the warning again.

**Comment by viclafouch** [comment]
I have the exact same issue.

AND

I have the same with this warning too : `Image with src "the-image.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.`

```jsx
<Image width={20} height={20} src={src} />
```

Very boring :(

**Comment by imtiazpy** [comment]
Having the issue: 
`Image with src "/Hero-triangle.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.`

even though I haven't used any CSS. 

Can anybody tell me, how to get rid of this warning ?

**Comment by alicercedigital** [comment]
I have the same issue:
warn-once.js?7395:11 Image with src "/icons/arrow-down.svg" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.

**Comment by damyco** [comment]
Having the same issue, started up a new project and trying to put SVG logo in my navbar, nothing fancy:

`                    <Image src="/logo.svg"
                                             alt="Logo"
                                             className="max-w-[12rem] lg:mr-10 mt-1"
                                             width={192}
                                             height={33}
                    />
`

Image with src "/logo.svg" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.

**Comment by i6mi6** [comment]
Interestingly I got the warning when passing float values to `width` and/or `height`

**Comment by nixjs** [comment]
You can try:

```css
img: {
  min-height: 100%;
  min-width: 100%;
  width: auto;
  height: auto;
  margin: 0;
  padding: 0;
}

**Comment by abdessamadelhamdany** [comment]
For me, it's happening cause I'm giving it a fixed width with a float number

So `img.height` returns `97` but `img.getAttribute("height")` returns `97.19999999999999'

I'm not sure if I should change my aspect ration to be `97` or this case should be handled like using `parseInt` on both 

```js
parseInt(img.height.toString()) !== parseInt(img.getAttribute("height"))
```

**Comment by ryarturogi** [comment]
This actually resolved the issue.

Can anyone explain why we need to set width and height to auto on the style attribute?

` <Image
      height={22.5}
      src="/logo.svg"
      style={{ width: 'auto', height: 'auto' }}
      width={82}
    />`
    
**Warning:** 

> Image with src "/logo.svg" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio.

**Comment by amritkv17** [comment]
Actually putting integer values instead of float, removes the console warning. 

From : `<Image src={logo} height={57} width={147.44} alt="Logo" />`

To : `<Image src={logo} height={57} width={147} alt="Logo" />`
