### ISSUE TITLE
JSX Parsing regression 12.2.X -> 12.3.X ("Unexpected token. Did you mean `{'>'}` or `&gt;`?")

### ISSUE THREAD

**Issue by broofa** [vercel/next.js#40773]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$ next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.13.2
      Yarn: 1.18.0
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.0
      eslint-config-next: N/A
      react: 17.0.2
      react-dom: 17.0.2
```

### Describe the Bug

The file below compiles w/out errors on `next@12.2.*`, but fails with the following errors on `next@12.3.1` (and `next@canary`:
```
error - ./data/joke.js
Error:
  x Unexpected token. Did you mean `{'>'}` or `&gt;`?
   ,----
 6 | We're stronger <code>&lt;u></code>nited than <code>&lt;div></code>ided.
   :                           ^
   `----

  x Unexpected token. Did you mean `{'>'}` or `&gt;`?
   ,----
 6 | We're stronger <code>&lt;u></code>nited than <code>&lt;div></code>ided.
   :                                                           ^
   `----

  x Unexpected token. Did you mean `{'>'}` or `&gt;`?
    ,----
 19 | Keep the <code>&lt;main></code> thing the <code>&lt;main></code> thing.
    :                        ^
    `----

  x Unexpected token. Did you mean `{'>'}` or `&gt;`?
    ,----
 19 | Keep the <code>&lt;main></code> thing the <code>&lt;main></code> thing.
    :                                                         ^
    `----
```
---
"joke.js"
```js
const jokes = [
  'Be the developer your linter thinks you are.',
  'There are 10 kinds of people, those who understand binary and those who don’t.',
  'The best caches are like the best hugs. Warm.',
  <>
    We're stronger <code>&lt;u></code>nited than <code>&lt;div></code>ided.
  </>,
  "💕 I'm the CSS to your HTML.",
  'How would you React if I said I love Vue?',
  'Keep friends close and formatters closer.',
  'What did the HTML say to the CSS? I like your style.',
  'Two CSS properties walk into a bar. A barstool in a completely different bar falls over.',
  <>
    If you want to <code>flex</code> your skills and go off the{' '}
    <code>grid</code>, try coding a layout with <code>float</code>.
  </>,
  'The Pen is mightier than the sword.',
  <>
    Keep the <code>&lt;main></code> thing the <code>&lt;main></code> thing.
  </>
];

export function useJoke() {
  return {
    data: jokes[Math.floor(Math.random() * jokes.length)],
    loading: false
  };
}
``` 

I.e. This appears to be BREAKING CHANGE of some sort in the JSX parsing logic.

**NOTE:** In case it's not obvious from the file this error is in, this isn't a critical issue for us. 😆   We have a workaround (escaping both leading and trailing angle-brackets) so this isn't a big deal.  I'm just submitting this so you're aware of the issue.  I.e. Feel free to close if this isn't worth the trouble to fix.

### Expected Behavior

See description

### Link to reproduction

See description

### To Reproduce

See description

**Comment by balazsorban44** [comment]
Thanks for reporting.

First, I thought this was a bug introduced in https://github.com/vercel/next.js/pull/40520

But in fact, it is the old behavior that is incorrect. See the JSX spec: https://facebook.github.io/jsx/#prod-JSXTextCharacter

So escaping is the solution here.

[This](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md) ESLint rule should guard against this (included [in](https://nextjs.org/docs/basic-features/eslint) `eslint-config-next`):

![image](https://user-images.githubusercontent.com/18369201/191622819-57b33748-586a-40c6-8e41-77e31035b34c.png)
