### ISSUE TITLE
Problem with starter project - can't run dev

### ISSUE THREAD

**Issue by Joehann** [vercel/next.js#40772]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.3.1", newest: "12.3.2-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Describe the Bug

I've just install a fresh next project with `yarn create next-app` command and `npm run dev`
Nothing else !
But I have this error :
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./styles/globals.css
TypeError: Cannot read properties of undefined (reading 'config')
```

### Expected Behavior

I just would like to see my project start

### Link to reproduction

nope

### To Reproduce

just `yarn create next-app`  and `npm run dev`

**Comment by balazsorban44** [comment]
I could not reproduce this, unfortunately. Please provide the repository so we can have a look. Make sure you are using the latest of the CLI by running `yarn create next-app@latest`.

**Comment by Joehann** [comment]
Thx @balazsorban44 
It's ok. The problem was NodeJS. I uninstall and re-install it. And go...
I don't understand why...! But it's run now !
