### ISSUE TITLE
appDir works incorrect with page.client.tsx

### ISSUE THREAD

**Issue by lomocc** [vercel/next.js#40792]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: 12.3.1
      react: 0.0.0-experimental-0cac4d54c-20220921
      react-dom: 0.0.0-experimental-0cac4d54c-20220921

### Describe the Bug

https://nextjs.org/blog/layouts-rfc#client-and-server-components-convention
appDir works only works with `page.js/page.tsx`, has bug with `page.client.js/page.client.tsx`

### Expected Behavior

appDir works with page.client.js/page.client.tsx

### Link to reproduction

https://github.com/lomocc/nextjs-demo

### To Reproduce

Demo: https://github.com/lomocc/nextjs-demo

**Comment by lomocc** [comment]
The latest Next.js canary release crashed:  
>`TypeError: Cannot destructure property 'CONTEXT_NAMES' of 'ComponentMod.serverHooks' as it is undefined.`

**Comment by timneutkens** [comment]
Please don't use unreleased features yet. We'll be sharing when you can start using it in #37136.
