### ISSUE TITLE
page suddenly crashes

### ISSUE THREAD

**Issue by Umamad** [vercel/next.js#40802]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

OS: windows 10
Node version: v16.14.2
package.json:
```
{
  "name": "mmm",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 5603",
    "build": "next build",
    "start": "node server.js",
    "lint": "next lint",
    "post-update": "echo \"codesandbox preview only, need an update\" && yarn upgrade --latest"
  },
  "dependencies": {
    "@emotion/cache": "latest",
    "@emotion/react": "latest",
    "@emotion/server": "latest",
    "@emotion/styled": "latest",
    "@mui/icons-material": "latest",
    "@mui/lab": "^5.0.0-alpha.79",
    "@mui/material": "latest",
    "@mui/styles": "^5.8.6",
    "@react-oauth/google": "^0.2.6",
    "@stripe/react-stripe-js": "^1.9.0",
    "@stripe/stripe-js": "^1.32.0",
    "axios": "^0.27.2",
    "cookie": "^0.5.0",
    "cookies-next": "^2.0.4",
    "cors": "^2.8.5",
    "formik": "^2.2.9",
    "formik-mui": "^4.0.0-alpha.3",
    "js-cookie": "^3.0.1",
    "jwt-decode": "^3.1.2",
    "next": "latest",
    "nextjs-progressbar": "0.0.14",
    "prop-types": "^15.8.1",
    "raw-body": "^2.5.1",
    "react": "latest",
    "react-apple-login": "^1.1.3",
    "react-dom": "latest",
    "react-elastic-carousel": "^0.11.5",
    "react-facebook-login": "^4.1.1",
    "react-google-autocomplete": "^2.7.0",
    "react-infinite-scroll-component": "^6.1.0",
    "react-scrollspy": "^3.4.3",
    "react-text-transition": "^3.0.2",
    "sharp": "^0.31.0",
    "styled-components": "^5.3.5",
    "swiper": "^8.1.4",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "eslint": "latest",
    "eslint-config-next": "latest",
    "prettier": "2.6.2"
  }
}
```

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

![New Bitmap Image](https://user-images.githubusercontent.com/83761249/191774558-6ae5fe6b-b056-4a7b-82e9-5728a96228d2.png)

at the first of loading the site looks good but after less than 1 second everything get destroyed. Same happened before, I had a build error that didn't shown in **windows** because of **uppercase and lowercase**. after i fixed that everything was fine but today it doesn't work.
> There is no build error
> There is no runtime error
> I tested all of css and js files and all of them were availible ( there is no 404 for assets )

homepage should look like this https://mealzo.weeorder.co.uk/ but it's not

### Expected Behavior

homepage should look like this https://mealzo.weeorder.co.uk/ but it's not

### Link to reproduction

https://mealzo-next-js.vercel.app/

### To Reproduce

The buggy one: https://mealzo-next-js.vercel.app/
The expected one: https://mealzo.weeorder.co.uk/

**Comment by SukkaW** [comment]
It seems that the issue is caused by [emotion](https://emotion.sh).

<img width="898" alt="image" src="https://user-images.githubusercontent.com/40715044/191880325-467da4ac-bf21-43d4-bd3b-f53c2dfb2db6.png">
<img width="727" alt="image" src="https://user-images.githubusercontent.com/40715044/191880436-fa2f5e30-0067-4fb6-863e-e0dffaac9aa3.png">

Would you like to provide the source code of your reproduction for investigation?

**Comment by Umamad** [comment]
> It seems that the issue is caused by [emotion](https://emotion.sh).
> 
> <img alt="image" width="898" src="https://user-images.githubusercontent.com/40715044/191880325-467da4ac-bf21-43d4-bd3b-f53c2dfb2db6.png">
> 
> <img alt="image" width="727" src="https://user-images.githubusercontent.com/40715044/191880436-fa2f5e30-0067-4fb6-863e-e0dffaac9aa3.png">
> 
> Would you like to provide the source code of your reproduction for investigation?

Tnx alot. You gave me a clue and I found the rest.

**Comment by Umamad** [comment]
Following of steps below fixed my problem.

## First Step
Update all of your packages such as
> @emotion/cache
> @emtion/react
> @emotion/server
> @emotion/styled
> @mui
> Next
> React & React-dom
refer to this [issue](https://github.com/mui/material-ui/tree/master/examples/nextjs)

## Second Step
I used the [MUI NextJs template](https://github.com/mui/material-ui/tree/master/examples/nextjs) but it has been changed.
the change was on createEmotionCache file so i updated the file and everythings works fine.

**Comment by SukkaW** [comment]
> he change was on createEmotionCache file so i updated the file and everythings works fine.

Since the MUI has changed its behavior, would you like to create a PR to update the Next.js example as well? So that others won't face the same issue again.
