### ISSUE TITLE
@react-pdf/renderer doesn't work with `swcMinify` set to true.

### ISSUE THREAD

**Issue by bryantobing12** [vercel/next.js#40803]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

next info

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Tested on Chrome, Firefox, and Brave

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

I'm using `@react-pdf/renderer` to create pdfs from `react app`. 

It's all working fine as expected in the development environment, but when I build the app 

and visit the page with pdf created by `@react-pdf/renderer` I got this error

![image](https://user-images.githubusercontent.com/46083126/191784879-1167a8d5-e6b2-4ced-a4ef-ae77e9ea2e35.png)

I thought this was because I'm using react 18 and there's an issue in `@react-pdf/renderer` that says to add support with react 18 https://github.com/diegomura/react-pdf/issues/2020. 

I try downgrading with this step https://stackoverflow.com/a/71972096/12720875. and it did work when I built the app with no error. But It is still at the latest using next12.1.2, and when upgrading to the latest nextjs the error appears again, and I need the feature of the latest nextjs.

and then i noticed that the error message says it's related to minification issue. 

![image](https://user-images.githubusercontent.com/46083126/191786203-23a5b46d-73b6-41dd-b219-479b19f4d8c8.png)

then I'm headed to next.config.js and remove `swcMinify: true`. and when I build the app and visit the pdf page. The error disappears.

I mean the error was already resolved by doing so. But I will not get the advantage of minification of swc. Also, I am still confused about what happened. And since the `swcMinify `is already stable as per next 12.3.0 i think this shouldn't happen.

### Expected Behavior

There's no error with the production build result 

### Link to reproduction

https://github.com/bryantobing12/next-pdf-repro

### To Reproduce

Steps to reproduce

1. git clone https://github.com/bryantobing12/next-pdf-repro
2. `yarn` to install deps
3. `yarn build`
4. `yarn start`
5. visit `localhost:3000/test`
6. The app will crash with error messages in the console

I was able to resolve that by removing `swcMinify: true` in next.config.js

steps
1. remove `swcMinify: true` in next.config.js
```diff
const nextConfig = {
  reactStrictMode: true,
-  swcMinify: true,
};
```

2. `yarn build`
3. `yarn start`
4. visit `localhost:3000/test`
5. The app will show the pdf preview with no error in the console

I'm hoping that this could be resolved without turning off `swc` minification :)

**Comment by kdy1** [comment]
Fixed by https://github.com/swc-project/swc/pull/5954

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/29931815/192422734-e7695f4d-82a9-470a-b0f1-638c847ac9bf.png">


I'll create a PR soon.

**Comment by bryantobing12** [comment]
Thanks for the fix @kdy1
