### ISSUE TITLE
all pages and layout in app folder are not found

### ISSUE THREAD

**Issue by mlnima** [vercel/next.js#40811]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I have a nextJs app with express custom server (using typescript) I've tried to move some page to the app folder also some layout but it seems does not work at all,

### What browser are you using? (if relevant)

chrome, firefox, safari ...

### How are you deploying your application? (if relevant)

custom server on ubuntu but the problem is on dev 

### Describe the Bug

 I renamed the index.tsx to page.tsx in the root of app folder also inside a folder but I get 404, 

also when there is no rewrite route in nextconfig file still I get 404

### Expected Behavior

to not getting 404

### Link to reproduction

https://github.com/mlnima/reactServerSideRenderingWithNext

### To Reproduce

https://github.com/mlnima/reactServerSideRenderingWithNext

**Comment by ijjk** [comment]
Hi, this feature is still in development and is not documented yet, please don't try to leverage it yet.
