### ISSUE TITLE
Multiple Set-Cookie headers will be folded when appended in _middleware [not resolved]

### ISSUE THREAD

**Issue by lswainemoore** [vercel/next.js#40820]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Present in Vercel Prod, but not when developing locally.

### Describe the Bug

[This issue](https://github.com/vercel/next.js/issues/34467) does not appear to be resolved. We are using 12.3.1, and still seeing *exactly* the same issue described here. I believe this issue may have been closed prematurely.

### Expected Behavior

Middleware that sets multiple set-cookie headers on a response should actually set multiple headers, instead of folding. This works correctly locally, but does not on vercel.

### Link to reproduction

see: https://github.com/vercel/next.js/issues/34467

### To Reproduce

see: https://github.com/vercel/next.js/issues/34467

**Comment by awareness481** [comment]
Can't reproduce, I see multiple set-cookie headers on the response. https://github.com/awareness481/next-cookies-append-middleware

**Comment by lswainemoore** [comment]
Thanks for looking into it! I'm a bit confused though--not seeing the middleware in that linked repo.

**Comment by awareness481** [comment]
> Thanks for looking into it! I'm a bit confused though--not seeing the middleware in that linked repo.

Whoops, you should be able to see it now. I forgot to commit the changes :P

**Comment by lswainemoore** [comment]
Gotcha! And that worked when deployed to vercel?

**Comment by awareness481** [comment]
Seems to work yes: https://next-cookies-append-middleware-ggxe.vercel.app/

**Comment by lswainemoore** [comment]
Ok, that does seem to work. However, try setting them like this: https://github.com/lswainemoore/next-cookies-append-middleware/blob/main/middleware.ts (the set-cookie header is returned from fetch rolled into one like this). This produces two different results in chrome. 

When running locally, it splits them properly: 
<img width="209" alt="image" src="https://user-images.githubusercontent.com/5581503/191904294-eac2dfaa-c859-4df9-aedb-e73ee1029c9a.png">

When running in vercel (https://next-cookies-append-middleware-s9jz.vercel.app/), it does not: 
<img width="432" alt="image" src="https://user-images.githubusercontent.com/5581503/191904355-07b88037-c63c-455d-a03b-7b37d9fbcdc8.png">

This is the same type of discrepancy that was described in the [original issue](https://github.com/vercel/next.js/issues/34467). Apologies, I could've probably saved you some time by providing this example earlier.

**Comment by lswainemoore** [comment]
in the interest of a slightly tighter reproduction: 
```
> curl -sSL -D - localhost:3000/ -o /dev/null
HTTP/1.1 200 OK
set-cookie: cookie1=val1
set-cookie: cookie2=val2
X-Powered-By: Next.js
ETag: "9pspwc0xdi39h"
Content-Type: text/html; charset=utf-8
Content-Length: 4237
Vary: Accept-Encoding
Date: Fri, 23 Sep 2022 15:08:44 GMT
Connection: keep-alive
Keep-Alive: timeout=5

> curl -sSL -D - https://next-cookies-append-middleware-s9jz.vercel.app/ -o /dev/null
HTTP/2 200
accept-ranges: bytes
access-control-allow-origin: *
age: 31016
cache-control: public, max-age=0, must-revalidate
content-disposition: inline
content-type: text/html; charset=utf-8
date: Fri, 23 Sep 2022 15:08:34 GMT
etag: "06b2fa3fd8585c57eff3cd47fdc1e99d"
server: Vercel
set-cookie: cookie1=val1, cookie2=val2
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-matched-path: /
x-vercel-cache: HIT
x-vercel-id: iad1:iad1::j8dz5-1663945714052-7bca7af3493a
content-length: 4237
```

**Comment by lswainemoore** [comment]
@awareness481 are you seeing the same behavior with that reproduction?

**Comment by steph-query** [comment]
Can confirm when you parse the cookie string yourself and call set_headers as in @awareness481's example, it does work in Vercel.

However, --in perfectly hilarious fashion-- this breaks localhost! The cookie gets mashed into a single header locally. 

We'll be able to deploy and can use the proper method in each environment, but it does feel like it's worth ironing this out so one method works in all environments.
