### ISSUE TITLE
`next/future/image` placeholder gets removed before the image has finished loading

### ISSUE THREAD

**Issue by exilvm** [vercel/next.js#40869]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Debian 5.10.136-1 (2022-08-13)
Binaries:
  Node: 16.17.0
  npm: 8.15.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 12.3.0
  eslint-config-next: 12.3.0
  react: 18.2.0
  react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Chromium: 105.0.5195.127

### How are you deploying your application? (if relevant)

Railway.app

### Describe the Bug

The blur-up placeholder does not wait until the image has finished loading, where with `next/image` it works as expected.

Also, throtteling the network speed is needed otherwise it'd happen too quickly for you to notice it. See the reproduction section below for more information.

Video demonstration:
https://user-images.githubusercontent.com/6927114/192092076-bc8982d3-b681-48eb-873a-cf45967cf4af.mp4

Live preview:
https://nextjs-future-image-production.up.railway.app

I was able to reproduce the bug with Next.js version: v12.3.2-canary.7, v12.3.1, v12.3.0, v12.2.5.

### Expected Behavior

It should wait until the image is loaded.

### Link to reproduction

https://nextjs-future-image-production.up.railway.app

### To Reproduce

1. Clone: https://github.com/EXILL-SUARL/nextjs-future-image
2. Run `npm i && npm run build && npm run start`
3. Go to: http://localhost:3000
4. Open the browser DevTools
5. Check `Disable cache` and throttle the internet speed to `Slow 3G` or lower
![20220924-104009](https://user-images.githubusercontent.com/6927114/192092036-17ea7aa9-0a4f-435a-9188-d4cc366c6dd1.png)
7. Press `CTRL+R`
8. Observe

**Comment by styfle** [comment]
With `next/future/image`, we removed the need for the browser to run JS, even when `placeholder="blur"`.

In this case, the optimized image is using WebP which can be [incrementally decoded](https://developers.google.com/speed/webp/faq#does_webp_support_progressive_or_interlaced_display) by the browser.

The quick fix here is to enable AVIF, since it doesn't have incremental decoding.

```js
module.exports  = {
  images: {
    formats: ['image/avif', 'image/webp']
  }
};
```

https://nextjs.org/docs/api-reference/next/image#acceptable-formats

**Comment by exilvm** [comment]
That fixed it. Thanks!
I think it would be nice to note that in the docs.
