### ISSUE TITLE
With-tailwindcss example is only limited to typesrcipt files. Can we make a flag that would help us choose between typescript and javascript

### ISSUE THREAD

**Issue by pranay101** [vercel/next.js#40878]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: N/A
      react: 18.1.0
      react-dom: 18.1.0

### Which example does this report relate to?

with-tailwindcss

### What browser are you using? (if relevant)

google chrome Version 105.0.5195.127 

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Whenever we use the with-tailwindcss example we are limited to just typescript files. We should make an option for users to choose between javascript and typescript files

### Expected Behavior

I want to work on this issue and make two different examples separately for javascript and typescript. though they are not very different. But having them separated would be much cleaner and more organised.

### To Reproduce

run the command : npx create-next-app -e with-tailwindcss

**Comment by balazsorban44** [comment]
Hi, we believe all of our examples should utilize TypeScript as it provides a safer and better Developer Experience.
