### ISSUE TITLE
Prefetch not working for server-side pages and static pages with rewrite. Duplicate prefetches for static pages without rewrites.

### ISSUE THREAD

**Issue by ranno-lauri** [vercel/next.js#40948]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Since version 12.3.0, prefetching on hover function on next/link started behaving differently, but remained with duplicate requests made on every hover for static pages(SSR pages were only fetched once), which adds a lot of unnecessary middleware invocations.

Things that changed from 12.2.5:
1. If the link's href is the rewrite "from" value of a static site, then it's not prefetched and **is not served the build time version**, but rather makes a new request and waits for it to finish, much like with SSR pages. 
2. Server-side rendered pages are not pre-fetched

Issue that persisted:
1. Static pages are requested again on every link hover(which includes home page) and invoke the middleware almost each request.
![image](https://user-images.githubusercontent.com/87007115/192526112-362bbd01-84ef-49c9-8d82-307577472097.png)

### Expected Behavior

Every link is prefetched once and is done for all pages.

### Link to reproduction

13.0.0 preview: https://next-duplicate-prefetch-fngm-i5fglaaev-ranno-lauri.vercel.app/
repo: https://github.com/ranno-lauri/next-duplicate-prefetch 
12.2.5 preview: https://next-duplicate-prefetch-fngm-8lnmbl59u-ranno-lauri.vercel.app/

### To Reproduce

On 13.0.0:
1. Open dev tools network tab(with cache enabled)
2. Hover over the "Kontakt' link and see no request being made
3. Hover over the "Contacs" link and see a request made on every mouse entry
4. Hover over the "Listing" link and see no request being made
5. Hover over the "Home" link and see a request made being on every mouse entry, even if already on home page.

**Comment by timfuhrmann** [comment]
Any recent insights on this?

**Comment by ranno-lauri** [comment]
Not really. Only the duplicate prefetching was said to be an expected behaviour

**Comment by ranno-lauri** [comment]
Issue persist on 13.0.0

**Comment by renanrodrigueszup** [comment]
Experiencing this as well. Found this behavior on current nextjs.org too when hovering Docs link multiple times.
![image](https://user-images.githubusercontent.com/66091812/203860871-c16f33f4-2303-46b9-b992-7bf30e9a402f.png)

**Comment by ranno-lauri** [comment]
As of "13.0.6" all prefetches are now working as expected for me. Duplicate pre-fetches 'issue' persist, but as that seems to be expected, I'm closing this issue as resolved.
