### ISSUE TITLE
Pages do not SSR in the dev environment

### ISSUE THREAD

**Issue by joebourne** [vercel/next.js#41003]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I'm using `next@12.3.2-canary.11` and `react@17.0.2`.

### Describe the Bug

Pages are not server-side rendered in the dev environment. Only after the client hydrates the React tree do I see the rendered markup. 

I'm not sure if this is my lack of understanding of the dev environment, but it's making it difficult to develop SSR pages in our application.

### Expected Behavior

During the server render, the full page should be rendered before the client is even hydrated.

### Link to reproduction

https://codesandbox.io/s/next-js-ssr-in-the-dev-environment-7vbe7c

### To Reproduce

- Go to the CodeSandbox
- Open the browser dev tools
- Click on one of the links in the mini browser
- Expect the debugger to pause execution while nothing has been rendered, implying the server didn't render anything so everything will be rendered on the client side

By contrast, if you build and start the app in production mode, the page is SSR'd. When the breakpoint is hit, the page is already visible in the background.

**Comment by balazsorban44** [comment]
For optimal debugging for your case, you can either use the VSCode debugger or use the `NODE_OPTIONS='--inspect' next dev` command. That would help you achieve what you are looking for! :pray:

Read more here: https://nextjs.org/docs/advanced-features/debugging#server-side-code
