### ISSUE TITLE
with-react-native-web React 18

### ISSUE THREAD

**Issue by AndreasBBS** [vercel/next.js#41010]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022
    Binaries:
      Node: 16.13.2
      npm: 8.19.2
      Yarn: 1.12.3
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: N/A
      react: 18.1.0
      react-dom: 18.1.0

### Which example does this report relate to?

with-react-native-web

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

There's not really a bug this is more a question for the future relating to React 18.

In your documentation for the [custom document](https://nextjs.org/docs/advanced-features/custom-document) there's a note saying 

> To prepare for [React 18](https://nextjs.org/docs/advanced-features/react-18), we recommend avoiding customizing getInitialProps and renderPage, if possible.

How would this example look in a React 18 scenario?
Is this one of the cases where it's not possible to avoid customizing through getInitialProps and renderPage?

### Expected Behavior

I would expect to be able to run this example using React 18 without leveraging getInitialProps and renderPage in_document.js

### To Reproduce

Does not apply

**Comment by balazsorban44** [comment]
Hi, the example should continue working, even if you upgrade to React 18. I upgraded the dependencies. :+1:

**Comment by AndreasBBS** [comment]
I understand that the example still works, my question was regarding how would a refactor be made as to

> avoiding customizing getInitialProps and renderPage

Right now the example takes advantage of this method but in the documentation it discourages the usage of this method with React 18. How would the same behavior be achieved without using getInitialProps and renderPage in React 18 is my question.

Thanks for the swift reply and I apologize for marking this as bug which is probably not the right way to raise this issue. Have a nice day.

**Comment by steida** [comment]
@AndreasBBS Did you figure it out?

**Comment by AndreasBBS** [comment]
> @AndreasBBS Did you figure it out?

Not really. I'm hoping this upcoming even the next team has coming in October might give me more insights.

**Comment by steida** [comment]
I already figured it out. RNfW 0.18 does not enable React 18 features yet, but it's already in https://github.com/necolas/react-native-web/commits/0.19-dev. So I believe the example is OK.
