### ISSUE TITLE
Image component has some spacing

### ISSUE THREAD

**Issue by da1z** [vercel/next.js#41103]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

If you put two nextjs images one under another there is spacing between them, not sure what it is but it is not margin or padding, maybe line height. If replace Image with img, no spacing there.

<img width="1281" alt="Screen Shot 2022-10-02 at 2 52 19 AM" src="https://user-images.githubusercontent.com/4012422/193448549-8cf5d445-1f0d-40fe-925d-4bfb7fa1efa6.png">

### Expected Behavior

no spacing

### Link to reproduction

https://github.com/da1z/next-image-bug

### To Reproduce

run project from repo or 

```
    <div>
      <Image
        alt="Next.js logo"
        src="https://assets.vercel.com/image/upload/v1538361091/repositories/next-js/next-js-bg.png"
        width={1200}
        height={400}
      />
      <Image
        alt="Next.js logo"
        src="https://assets.vercel.com/image/upload/v1538361091/repositories/next-js/next-js-bg.png"
        width={1200}
        height={400}
      />
    </div>
```

**Comment by gaston-flores** [comment]
I don't think this is an issue with `Image`, I can reproduce this with `img` tags. [Here's an example in a plain html file.](https://codesandbox.io/s/img-newline-0y4fef?file=/index.html)

I think the whitespace (newline) between the images is being rendered as extra spacing. You can fix this by setting `display: block;` on the img elements.

**Comment by balazsorban44** [comment]
@gaston-flores that was my suspicion, thanks for checking! Correct, `img`s are `inline-block` by default.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#styling_with_css
https://stackoverflow.com/questions/7641678/use-css-to-remove-the-space-between-images
