### ISSUE TITLE
middleware rewrite not working with uploaded files

### ISSUE THREAD

**Issue by cbrianball** [vercel/next.js#41157]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.13.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.18
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome version 105 (likely happens in all browsers)

### How are you deploying your application? (if relevant)

Running locally

### Describe the Bug

For requests that contain a file (either as part of FormData or if the request body itself is a file), when the middleware runs and a NextResponse.rewrite(...) is returned, no further action happens. Looking at the browser tools, the request is stuck in a `(pending)` status.

This only appears to happen if there is a file in the request. If there is only data, then everything works as expected.

In the provided repro, the middleware is simply looking for a specific URL and rewriting it to an `/api` endpoint.

### Expected Behavior

The rewrite should cause the request to be sent to the provided URL, and that endpoint should be executed. This was working in 12.1.6.

### Link to reproduction

https://github.com/cbrianball/nextjs-rewrite-bug-repro

### To Reproduce

1. Clone the repo
2. Install packages `npm i`
3. Run locally `npm run dev`
4. The "GET", "POST", and "Upload" (without selecting a file) buttons work fine and provide a value in the results
5. Selecting a file and clicking "Upload" will show no results and the console output of nextjs will show the middleware received the request, but the `/api/hello` endpoint was never reached. The browser tools will also show the request in a `(pending)` status.

**Comment by cocamm** [comment]
Hey @cbrianball 
Have you tried with a file small than 16KB? Take a look at #39262.
