### ISSUE TITLE
After updating to Next 12.3.0 or 12.3.1 (from 12.2.5) cannot access login url and console is throwing Uncaught TypeError from source.mjs 

### ISSUE THREAD

**Issue by randr44** [vercel/next.js#41167]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.1
      eslint-config-next: 12.3.1
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

106.0.5195.127

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

In local development environment application works fine.... But when creating the production build (which appears to build fine), web application pages do not load when attempting to visit site url:

there is a single error in the console: 
`Uncaught TypeError: r is not a function
    at 5507 (source.mjs:50:1)
    at r (source.mjs:50:1)
    at source.mjs:50:1
    at e (source.mjs:50:1)
    at 46785 (source.mjs:50:1)
    at i (bootstrap:22:1)
    at 29100 (source.mjs:50:1)
    at i (bootstrap:22:1)
    at 97428 (source.mjs:50:1)
    at i (bootstrap:22:1)`

when I revert to next 12.2.5 the application builds perfectly and url links 
render appropriate pages and content
![error](https://user-images.githubusercontent.com/97480113/193919955-64d6931c-9df3-4ebc-94d6-cfe13b66b029.png)

### Expected Behavior

I expect to update next packages to 12.3.0 or 12.3.1 and have the updates work with the rest of the dependencies in my next application

### Link to reproduction

https://caseoppsta-cv27pdpns-rdevs1.vercel.app/

### To Reproduce

Node 16.x environment
Next Create-React-App
Mongo DB database
Apollo GraphQL server
Next/Auth0

deploy production build and trace error to source.mjs
![error2](https://user-images.githubusercontent.com/97480113/193922800-e243bb34-b037-4481-b33a-27a1c5d05ff5.png)

**Comment by SukkaW** [comment]
The missing `r` function should be `__webpack_require`.

Are you provided a custom Webpack config through `next.config.js`? Would you like to share the source code of the repo / provide a minimum reproduction for us to investigate?

@balazsorban44 It is probably not related to SWC minify.

**Comment by randr44** [comment]
Thanks for your response. The issue was in my next.config.js file. Setting the swcMinify value to false, fixed this issue and the error is not thrown on production builds.
`const moduleExports = {
  eslint: {
    ignoreDuringBuilds: true
  },
  swcMinify: false,
  async headers () {`
