### ISSUE TITLE
Docs: API path for routes

### ISSUE THREAD

**Issue by shreedharhegde99** [vercel/next.js#41198]
### What is the improvement or update you wish to see?

Update the API routes introduction page documentation

### Is there any context that might help us understand?

In the API routes introduction page the example route `pages/api/user.js` will give an error as it is the incorrect path. It should be updated to `/api/user`  to work correctly.

![Screenshot from 2022-10-06 00-27-08](https://user-images.githubusercontent.com/90758718/194140240-c51cd15a-c802-4a76-b091-2a1f3410bb99.png)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-routes/introduction

**Comment by balazsorban44** [comment]
Please see https://github.com/vercel/next.js/pull/41199#issuecomment-1269837318
