### ISSUE TITLE
Jest warning when use placeholder="blur" on next/image or next/future/image

### ISSUE THREAD

**Issue by ArthurPedroti** [vercel/next.js#41248]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.22
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I create a fresh install from next with-jest template and create a unique test from a component with next/image and next/future/image, and show the warning bellow:

`
Image with src "/img.jpg" is smaller than 40x40. Consider removing the "placeholder='blur'" property to improve performance.
`

![image](https://user-images.githubusercontent.com/52859409/194559451-64299eba-b26f-4498-b01b-1e2dcc4b922a.png)

### Expected Behavior

Don't show this warning.

### Link to reproduction

https://codesandbox.io/p/github/ArthurPedroti/test-jest-next-image/main?file=%2Fsrc%2FNextImage%2Ftest.tsx&selection=%5B%7B%22endColumn%22%3A3%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A3%2C%22startLineNumber%22%3A11%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8yhm1bg000jltii0l8lbcve%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl8yhpftv000alqii48e5atiq%2522%252C%2522key%2522%253A%2522cl8yhpfc900rf3n6j16aet13z%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl8yhpbpq00pn3n6jhruyuw3e%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl8yhp53m00nv3n6jgb7k0pxl%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### To Reproduce

Only run "npm run test" and will show the error.

**Comment by teobler** [comment]
cannot open your link, but this warning showing because your image's width & height small than 40, not related to jest.

**Comment by balazsorban44** [comment]
Thanks, I could reproduce it and opened a PR to fix it.

@teobler, I believe the issue is with codesandbox. When clicking the link, I was prompted by "Authorize with GitHub" modal that I canceled, after which I could open the reproduction. :+1:
