### ISSUE TITLE
docker build in with-docker  is failed with the below error

### ISSUE THREAD

**Issue by narasimhamurthi** [vercel/next.js#41263]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information
[root@jenkins with-docker]# pwd
/root/next.js/examples/with-docker
[root@jenkins with-docker]#
[root@jenkins with-docker]# ls -ltr
total 20
-rw-r--r--. 1 root root 1806 Oct  7 18:25 Dockerfile
-rw-r--r--. 1 root root 3396 Oct  7 18:25 README.md
-rw-r--r--. 1 root root  189 Oct  7 18:25 package.json
-rw-r--r--. 1 root root   86 Oct  7 18:25 next.config.js
-rw-r--r--. 1 root root  154 Oct  7 18:25 app.json
drwxr-xr-x. 2 root root   48 Oct  7 18:25 styles
drwxr-xr-x. 2 root root   43 Oct  7 18:25 public
drwxr-xr-x. 3 root root   48 Oct  7 18:25 pages
[root@jenkins with-docker]# docker build -t nextjs-docker .
Sending build context to Docker daemon  37.38kB
Step 1/22 : FROM node:16-alpine AS deps
 ---> f7ef5856dc1f
Step 2/22 : RUN apk add --no-cache libc6-compat
 ---> Using cache
 ---> 80b52fe134e7
Step 3/22 : WORKDIR /app
 ---> Using cache
 ---> cd7fd162cbb4
Step 4/22 : COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 ---> Using cache
 ---> 364076824741
Step 5/22 : RUN   if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i;   else echo "Lockfile not found." && exit 1;   fi
 ---> Running in cab6ed711451
Lockfile not found.
The command '/bin/sh -c if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i;   else echo "Lockfile not found." && exit 1;   fi' returned a non-zero code: 1
[root@jenkins with-docker]# pwd
/root/next.js/examples/with-docker
[root@jenkins with-docker]#

### Describe the Bug

[root@jenkins with-docker]# ls -ltr
total 20
-rw-r--r--. 1 root root 1806 Oct  7 18:25 Dockerfile
-rw-r--r--. 1 root root 3396 Oct  7 18:25 README.md
-rw-r--r--. 1 root root  189 Oct  7 18:25 package.json
-rw-r--r--. 1 root root   86 Oct  7 18:25 next.config.js
-rw-r--r--. 1 root root  154 Oct  7 18:25 app.json
drwxr-xr-x. 2 root root   48 Oct  7 18:25 styles
drwxr-xr-x. 2 root root   43 Oct  7 18:25 public
drwxr-xr-x. 3 root root   48 Oct  7 18:25 pages
[root@jenkins with-docker]# docker build -t nextjs-docker .
Sending build context to Docker daemon  37.38kB
Step 1/22 : FROM node:16-alpine AS deps
 ---> f7ef5856dc1f
Step 2/22 : RUN apk add --no-cache libc6-compat
 ---> Using cache
 ---> 80b52fe134e7
Step 3/22 : WORKDIR /app
 ---> Using cache
 ---> cd7fd162cbb4
Step 4/22 : COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 ---> Using cache
 ---> 364076824741
Step 5/22 : RUN   if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i;   else echo "Lockfile not found." && exit 1;   fi
 ---> Running in cab6ed711451
Lockfile not found.
The command '/bin/sh -c if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i;   else echo "Lockfile not found." && exit 1;   fi' returned a non-zero code: 1
[root@jenkins with-docker]# pwd
/root/next.js/examples/with-docker
[root@jenkins with-docker]#

### Expected Behavior

failing with error while building the docker.

### Link to reproduction

in centos8

### To Reproduce

[root@jenkins with-docker]# ls -ltr
total 20
-rw-r--r--. 1 root root 1806 Oct  7 18:25 Dockerfile
-rw-r--r--. 1 root root 3396 Oct  7 18:25 README.md
-rw-r--r--. 1 root root  189 Oct  7 18:25 package.json
-rw-r--r--. 1 root root   86 Oct  7 18:25 next.config.js
-rw-r--r--. 1 root root  154 Oct  7 18:25 app.json
drwxr-xr-x. 2 root root   48 Oct  7 18:25 styles
drwxr-xr-x. 2 root root   43 Oct  7 18:25 public
drwxr-xr-x. 3 root root   48 Oct  7 18:25 pages
[root@jenkins with-docker]# docker build -t nextjs-docker .
Sending build context to Docker daemon  37.38kB
Step 1/22 : FROM node:16-alpine AS deps
 ---> f7ef5856dc1f
Step 2/22 : RUN apk add --no-cache libc6-compat
 ---> Using cache
 ---> 80b52fe134e7
Step 3/22 : WORKDIR /app
 ---> Using cache
 ---> cd7fd162cbb4
Step 4/22 : COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
 ---> Using cache
 ---> 364076824741
Step 5/22 : RUN   if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i;   else echo "Lockfile not found." && exit 1;   fi
 ---> Running in cab6ed711451
Lockfile not found.
The command '/bin/sh -c if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i;   else echo "Lockfile not found." && exit 1;   fi' returned a non-zero code: 1

**Comment by noodlemind** [comment]
@narasimhamurthi If you run or initialize your package manager. (yarn or npm etc.,) Then the lock file should get generated.
