### ISSUE TITLE
Docs: Layouts RFC blog post wording issue

### ISSUE THREAD

**Issue by Haugen** [vercel/next.js#41294]
### What is the improvement or update you wish to see?

Reading through Layouts RFC blog post I came across a sentence that I don't think makes sense. A few paragraphs down in the [Server-Centric Routing](https://nextjs.org/blog/layouts-rfc#server-centric-routing) section it says the following:

"This is in contrast to the current default of Client components, which the component JavaScript to the browser to be rendered client-side."

I don't think that second part makes sense? It sounds like it should say something like "where the component sends JavaScript..." instead of "which the component JavaScript...".

### Is there any context that might help us understand?

Just a documentation improvement on the Layouts RFC blog post.

### Does the docs page already exist? Please link to it.

https://nextjs.org/blog/layouts-rfc#server-centric-routing

**Comment by manovotny** [comment]
@Haugen good call out. I've opened a PR to address.

**Comment by manovotny** [comment]
Change has been merged. Thanks again!
