### ISSUE TITLE
og-image doesn't work with output file tracing

### ISSUE THREAD

**Issue by youssefm** [vercel/next.js#41395]
Steps to repro:

1. Create a new next js project
2. Install `@vercel/og`
3. Add an og-image API page at: `pages/api/og.tsx`
4. Add `output: "standalone",` to your `next.config.js`

Try to run `next build` to get the following output:

```
warn  - You are using an experimental edge runtime, the API might change.
info  - Creating an optimized production build .<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (176kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
info  - Creating an optimized production build  
info  - Compiled successfully

> Build error occurred
[Error: ENOENT: no such file or directory, open '/.../.next/server/pages/api/og.js.nft.json'] {
```

**Comment by marviobezerra** [comment]
Same here

**Comment by Saul-BT** [comment]
Is there any update on this?

**Comment by ijjk** [comment]
Hi, in the latest version of Next.js `v13.0.2` this is no longer a fatal error and will not block the build. We will investigate further why this file lookup is failing as well!

**Comment by balazsorban44** [comment]
Closing as duplicate of #39275
