### ISSUE TITLE
Docs: Next 12.3 `app` directory

### ISSUE THREAD

**Issue by h1sashin** [vercel/next.js#41400]
### What is the improvement or update you wish to see?

Hello, I have a question about one of the latest blog posts.

I just created a new Next app using `create-next-app` and thought I can use a new `app` directory - introduces 1 month ago in `current` NextJS version. But when I started my app locally i got an error calling
```
Error: > Couldn't find a `pages` directory. Please create one under the project root
```

I didn't create a pages directory because as I understood I don't need that anymore. Of course I made an `/app/page.tsx` and `/app/layout.tsx` files.

Just wanted to try the new concept of RFC Layouts (that's the feature I was looking for since I learned NextJS)

And there is my question - It's not yet available or my setup is bad?
If it's not available yet - when will it be?

### Is there any context that might help us understand?

create-next-app -> create `app` directory -> create example `page.js` -> remove `pages` directory -> start dev server

### Does the docs page already exist? Please link to it.

https://nextjs.org/blog/next-12-3#new-router-and-layouts-update

**Comment by leerob** [comment]
Hey there! The `app` directory isn't ready just yet – we are working hard on this. Expect an update very soon.
