### ISSUE TITLE
Docs: Indicate High memory usage if not installing sharp for image optimization

### ISSUE THREAD

**Issue by gaplo917** [vercel/next.js#41417]
### What is the improvement or update you wish to see?

# Introduction
Remote image sizes are difficult to guarantee when some users uploaded very large images on the CMS. The very large images will be retrieved by nextjs and served to the frontend.

The default library `squoosh` will cause the nextjs process a very high memory usage during image optimizations and might **crash the whole nextjs container** in a limited resource environment.

Thus, the high memory behaviour should be docuementated to increase the necessarity of installing `sharp`.

_**Note: Some of our team members can't see observable differences after installing `sharp` and then remove it immediately.**_

## Suggestion
Indicate high memory usage of `squoosh` compared with `sharp`. For example, a single 5000 x 5000 images would consume ~600MB memory while `sharp` use less than few MB memory only.

### Is there any context that might help us understand?

Demo Recording

## Without installing Sharp
Three 5000x5000 images will cause 1.8GB memory usage, and the memory jump is linear.
![next-high-mem](https://user-images.githubusercontent.com/5468398/195833901-a23e1e59-a4ec-4bfe-bc91-edf8061634cc.gif)

## Installed Sharp
The memory usage remains stable.
![next-sharp-installed-no-high-mem](https://user-images.githubusercontent.com/5468398/195833519-cd6387a9-fe45-40f1-b414-eb486cd0a751.gif)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/sharp-missing-in-production

**Comment by karlhorky** [comment]
Wonder if this issue can be replaced by a PR to switch back to `sharp`, now that [`@squoosh/cli`](https://www.npmjs.com/package/@squoosh/cli) and [`@squoosh/lib`](https://www.npmjs.com/package/@squoosh/lib) are unmaintained:

> Project no longer maintained
>
> Unfortunately, due to a few people leaving the team, and staffing issues resulting from the current economic climate (ugh), this package is no longer actively maintained. I know that sucks, but there simply isn't the time & people to work on this. If anyone from the community wants to fork it, you have my blessing. The squoosh.app will continue to be supported and improved.

<img width="1435" alt="Screenshot 2023-03-31 at 14 42 39" src="https://user-images.githubusercontent.com/1935696/229123257-1a4df96d-0596-4592-8f1c-cdb38a66cc20.png">

**Comment by karlhorky** [comment]
@styfle is there already an issue / PR about switching from `squoosh` back to `sharp` somewhere? eg. reverting @Timer's PR below and all followup PRs adding back some optional `sharp` support:

- https://github.com/vercel/next.js/pull/22253

M1 support (the original reason for switching to `squoosh`) has been in `sharp` for a long time now, and there is an initiative to also get WASM support:

- https://github.com/lovell/sharp/pull/3522

**Comment by styfle** [comment]
There's no issue tracking it in Next.js because https://github.com/lovell/sharp/pull/3522 hasn't landed yet.

Once it lands then we can look into removing `squoosh` as the wasm implementation in favor of `sharp`.

For now, the [linked docs](https://nextjs.org/docs/messages/sharp-missing-in-production) in the original post explain the current status.

**Comment by karlhorky** [comment]
Looks like [`sharp@0.33.0`](https://github.com/lovell/sharp/releases/tag/v0.33.0) now includes (experimental) WebAssembly support 🙌 

- https://github.com/lovell/sharp/pull/3522#issuecomment-1805398977
- https://github.com/lovell/sharp/issues/3336#issuecomment-1831888149
