### ISSUE TITLE
failed to compute cache key: "/.env.production.sample" not found

### ISSUE THREAD

**Issue by kushalmahajan** [vercel/next.js#41469]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/

### Which example does this report relate to?

with-docker-multi-env

### What browser are you using? (if relevant)

NA

### How are you deploying your application? (if relevant)

AWS Copilot

### Describe the Bug

Locally, this ran fine with the productions build and run. However, I ran it via AWS copilot and it broke with the errors as mentioned in the screenshot. 

![Uploading Screenshot 2022-10-16 at 7.45.11 PM.png…]()

### Expected Behavior

The docker build or run should work fine with AWS copilot

### To Reproduce

1. Clone this example repo
2. Setup AWS Copilot
3. Deploy via Copilot - https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/
4. Running `copilot init` will give this error mentioned above in screenshot

**Comment by balazsorban44** [comment]
This seems to be unrelated to/not a bug in Next.js. 

The screenshot is unavailable, but it sounds like the `.env.production.sample` file is not correctly copied over while building the image. Make sure it's not the case.
