### ISSUE TITLE
Docs: Fetching the blog data - "Now that the blog data is parsed..." can be reworded.

### ISSUE THREAD

**Issue by jiparkdev** [vercel/next.js#41468]
### What is the improvement or update you wish to see?

I would like to see different words used in the first sentence of **Fetching the blog data** section on [**Blog data** page](https://nextjs.org/learn/basics/data-fetching/blog-data).

### Is there any context that might help us understand?

**Fetching the blog data** section from [**Blog data** page](https://nextjs.org/learn/basics/data-fetching/blog-data) starts with "Now that the blog data is parsed, ...", which refers to the utility function from the previous section **Creating the utility function to read the file system**. I can understand that the utility function `getSortedPostsData()` will parse the markdown file when we use it in the page [**Implement getStaticProps**](https://nextjs.org/learn/basics/data-fetching/implement-getstaticprops), but it might be better for the context of the **Blog data** page if we say something like: "Now that we created `getSortedPostsData()`, ...".

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/data-fetching/blog-data

**Comment by balazsorban44** [comment]
Thanks, IMO, that sentence sounds correct, but I forwarded this feedback.
