### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isDynamic') is suppressing errors in getServerSideProps

### ISSUE THREAD

**Issue by amaschas** [vercel/next.js#41540]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I'm really at a loss for what causes this bug or how exactly to replicate it (which is one of the issues with the bug), but there's a bit of discussion about it here: https://github.com/vercel/next.js/discussions/40373

The summary is that in certain cases NextJS will throw an error with the message `TypeError: Cannot read properties of undefined (reading 'isDynamic')`. I believe this happens when an error is throw in `getServerSideProps`, or possible anywhere in `index.tsx`, but I'm not sure. The problem is that the `isDynamic` error obscures the error that is actually being thrown, making debugging a matter of trial and error.

> 

### Describe the Bug

1. TypeError: Cannot read properties of undefined (reading 'isDynamic') is obscuring any errors thrown in `getServerSideProps`, and possible anywhere in `index.tsx`.

### Expected Behavior

Any errors throw in `getServerSideProps` should report the actual error being throw, rather than the `isDynamic` error.

### Link to reproduction

N/A

### To Reproduce

I honestly I have no idea how to reproduce this consistently.

**Comment by balazsorban44** [comment]
Could you please attach a repository/stack trace?

**Comment by amaschas** [comment]
> Could you please attach a repository/stack trace?

Unfortunately the repository I'm encountering this in is private, but here's a stack trace. I'm still working on a way to reproduce, so if I can figure that out I'll spin up an example repo.

```
  TypeError: Cannot read properties of undefined (reading 'isDynamic')
      at Object.sendRenderResult (/node_modules/next/server/send-payload/index.ts:41:26)
      at DevServer.sendRenderResult (/node_modules/next/server/next-server.ts:485:7)
      at DevServer.pipe (/node_modules/next/server/base-server.ts:1090:19)
```

**Comment by balazsorban44** [comment]
Feel free to invite me to your repo, or try eliminating any code from the copy of your private repo that does not contribute to the issue, until you can share it publicly.

**Comment by amaschas** [comment]
> Feel free to invite me to your repo, or try eliminating any code from the copy of your private repo that does not contribute to the issue, until you can share it publicly.

Yeah, I've tried to create a stripped down version of the repo but I can't manage to trigger the error. Unfortunately simply giving you access to our repo isn't simple, as there are a variety of other private dependencies and VPN access involved to even get it running.

**Comment by amaschas** [comment]
I still haven't been able to isolate this issue in an example repo, but I did step through the request with a debugger. What I've found is that the correct error remains in context up until `this.sendRenderResult` is returned on line 656 of base-server.js. At this point execution jumps to line 70 of index.js where log is suddenly throwing the `isDynamic` error.

**Comment by amaschas** [comment]
After further investigation, I have managed to narrow this down to the `dd-trace` integration we are using with NextJS. I'm going to open a bug ticket on that repo. Should I close this one, and re-open if required?

**Comment by amaschas** [comment]
OK, I actually think we can close this entirely. Our dd-trace plugin was severely out of date. Updating it to the latest addressed the issue.
