### ISSUE TITLE
`useFileSystemPublicRoutes` disabled do not render `app` paths

### ISSUE THREAD

**Issue by sviridoff** [vercel/next.js#41568]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #42-Ubuntu SMP Thu May 19 05:03:08 UTC 2022
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 3.2.4
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.32
      eslint-config-next: N/A
      react: 0.0.0-experimental-9cdf8a99e-20221018
      react-dom: 0.0.0-experimental-9cdf8a99e-20221018

### Describe the Bug

When we set `useFileSystemPublicRoutes` as `false`, and we use the next server `render method` in production, the routes from the `app` folder are not working.
The components are compiled correctly, also the bug is not observed in depelopment mode.

Changing next-server.ts solves the wrong behaviour

```js
if (useFileSystemPublicRoutes) {
  this.appPathRoutes = this.getAppPathRoutes()
  this.dynamicRoutes = this.getDynamicRoutes()
}
```

to

```js
if (useFileSystemPublicRoutes) {
  this.dynamicRoutes = this.getDynamicRoutes()
}
this.appPathRoutes = this.getAppPathRoutes()
```

But doing so, I dont know the implications if it breaks the performance or other side effects, also I didnt run tests

Not sure if is related with [#40759](https://github.com/vercel/next.js/issues/40759)

### Expected Behavior

Display the pages from `app` folder

### Link to reproduction

https://github.com/sviridoff/next_custom_server_bug

### To Reproduce

git clone git@github.com:sviridoff/next_custom_server_bug.git
cd next_custom_server_bug
yarn
yarn run build && yarn run start
go to http://localhost:3000/home
see 404

**Comment by balazsorban44** [comment]
Thanks, but the `app` directory is not fully ready for feedback yet, as it is being actively worked on. Update is coming soon!
