### ISSUE TITLE
Docs: Four Broken Links in next/image Documentation Examples

### ISSUE THREAD

**Issue by kr1st1nagr03g3r** [vercel/next.js#41578]
### What is the improvement or update you wish to see?

Steps to reproduce issue:

Please note that I do see a recent commit [here](https://github.com/vercel/next.js/pull/41539), however it didn't fix this particular issue.

1) [Navigate to the next/image optional props doc](https://nextjs.org/docs/api-reference/next/image#optional-props)
2) Click on the following links:
[Demo the intrinsic layout (default)](https://image-component.nextjs.gallery/layout-intrinsic)
[Demo the fixed layout](https://image-component.nextjs.gallery/layout-fixed)
[Demo the responsive layout](https://image-component.nextjs.gallery/layout-responsive)
[Demo the fill layout](https://image-component.nextjs.gallery/layout-fill)
3) On each of the four links mentioned above, clicking on the Github icon at the top right results in a 404 error.
On: 
[Demo the intrinsic layout (default)](https://image-component.nextjs.gallery/layout-intrinsic) Github links to: [layout-intrinsic.jsx](https://github.com/vercel/next.js/tree/canary/examples/image-component/pages/layout-intrinsic.tsx)
[Demo the fixed layout](https://image-component.nextjs.gallery/layout-fixed) Github links to: [layout-fixed.tsx](https://github.com/vercel/next.js/tree/canary/examples/image-component/pages/layout-fixed.tsx
)
[Demo the responsive layout](https://image-component.nextjs.gallery/layout-responsive) Github links to: [layout-responsive.tsx](https://github.com/vercel/next.js/tree/canary/examples/image-component/pages/layout-responsive.tsx)
[Demo the fill layout](https://image-component.nextjs.gallery/layout-fill) Github links to: [layout-fill.tsx](https://github.com/vercel/next.js/tree/canary/examples/image-component/pages/layout-fill.tsx)

Thanks!

### Is there any context that might help us understand?

1) [Demo the intrinsic layout (default)](https://image-component.nextjs.gallery/layout-intrinsic) Github link should go to a layout-intrinsic.tsx file, however [I do not see it in this repo](https://github.com/vercel/next.js/tree/canary/examples/image-component/pages). I'm aware that intrinsic is the default, but a broken link still remains.
2) [Demo the fixed layout](https://image-component.nextjs.gallery/layout-fixed) Github link should go to a layout-fixed.jsx file, however[ I do not see it in this repo](https://github.com/vercel/next.js/tree/canary/examples/image-component/pages)
3) [Demo the responsive layout](https://image-component.nextjs.gallery/layout-responsive) Github link should go to: [responsive.tsx](https://github.com/vercel/next.js/blob/canary/examples/image-component/pages/responsive.tsx)
4) [Demo the fill layout](https://image-component.nextjs.gallery/layout-fill) Github link should go to: [fill.tsx](https://github.com/vercel/next.js/blob/canary/examples/image-component/pages/fill.tsx)

### Does the docs page already exist? Please link to it.

https://image-component.nextjs.gallery/

**Comment by balazsorban44** [comment]
Thanks, the documentation updates you mentioned have been merged, and will be reflected on the website the next time a new `latest` version of `next` is released, which is soon, so keep an eye on it. :pray:
