### ISSUE TITLE
broken @vercel/og output

### ISSUE THREAD

**Issue by maddhruv** [vercel/next.js#41641]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

nodejs 16
nextjs 12.13.1
@vercel/og 0.0.19

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

The vercel og generated images on vercel i.e. remote builds are not correct, the actual height is reduced somehow, check this out - https://www.maddhruv.dev/api/og?title=The%20Energetic%20React%20Lazy&description=Learn%20how%20React%20Lazy%20can%20be%20a%20very%20powerful%20tool%20to%20improve%20your%20site%20performance.&tags=React
![image](https://user-images.githubusercontent.com/18121502/197329102-6af4b6a0-dd67-4ec1-b2c8-a5ab96cfbe70.png)

While everything works fine on dev and local build and serve.
Source code for og API - https://github.com/maddhruv/maddhruv.github.io/blob/master/pages/api/og.tsx

I am not sure if this is the correct repo but couldn't find the actual repo for og, redirect if this repo isn't relevant

### Expected Behavior

The image rendered should of correct height, and should work same on dev and vercel build

![image](https://user-images.githubusercontent.com/18121502/197328999-39f3014a-ac92-4d35-a0b5-de214a1e072f.png)

### Link to reproduction

https://github.com/maddhruv/maddhruv.github.io/blob/master/pages/api/og.tsx

### To Reproduce

https://github.com/maddhruv/maddhruv.github.io/blob/master/pages/api/og.tsx
and OG API - https://www.maddhruv.dev/api/og?title=The%20Energetic%20React%20Lazy&description=Learn%20how%20React%20Lazy%20can%20be%20a%20very%20powerful%20tool%20to%20improve%20your%20site%20performance.&tags=React

**Comment by rahmatagungj** [comment]
Yeah, same with me.

![image](https://user-images.githubusercontent.com/30583918/197338655-a70a5136-cda5-48e4-a745-ccea556ee957.png)

**Comment by shuding** [comment]
It should be addressed already: https://twitter.com/vercel_status/status/1583956970650112001

**Comment by maddhruv** [comment]
Oh thanks @shuding works
