### ISSUE TITLE
opening nextjs website (with timer running) slows down the browser / computer

### ISSUE THREAD

**Issue by nabtron** [vercel/next.js#41670]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

The timer for countdown of the event on official website is poorly coded (or something else too) and it is causing heavy load on system. please look into it.

### Describe the Bug

The timer for countdown of the event on official website is poorly coded (or something else too) and it is causing heavy load on system. please look into it.

### Expected Behavior

should be reviewed

### Link to reproduction

https://nextjs.org/

### To Reproduce

https://nextjs.org/

**Comment by balazsorban44** [comment]
This is not a Next.js bug, so I'm closing the issue, but I forwarded this feedback to the team. Thanks. :+1:
