### ISSUE TITLE
`with-router` circular dependency detected

### ISSUE THREAD

**Issue by vorillaz** [vercel/next.js#41716]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.9.5
    Relevant packages:
      next: 12.3.2-canary.38
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Trying to spot out any memory leaks related to https://github.com/vercel/next.js/issues/32314 the `circular-dependency-plugin` reports that there is a one in the next.js package.
I am not sure if that causes the webpack memory allocation bug, but it worths a try.

### Expected Behavior

Stop producing errors on the webpack build.

### Link to reproduction

-

### To Reproduce

1. Install the `circular-dependency-plugin`
2. Use it within `next.config.js` as:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  webpack: (config, { defaultLoaders, isServer }) => {
    const CircularDependencyPlugin = require("circular-dependency-plugin");
    let numCyclesDetected = 0;
    config.plugins.push(
      new CircularDependencyPlugin({
        failOnError: true,
        cwd: process.cwd(),
        allowAsyncCycles: true,
        onStart({ compilation }) {
          numCyclesDetected = 0;
        },
        onDetected({ module: webpackModuleRecord, paths, compilation }) {
          numCyclesDetected++;
          compilation.warnings.push(new Error(paths.join(" -> ")));
        },
        onEnd({ compilation }) {
          if (numCyclesDetected > 0) {
            compilation.warnings.push(
              new Error(`Detected ${numCyclesDetected} cycles`)
            );
          }
        },
      })
    );
    return config;
  },
};

module.exports = nextConfig;
```

3. Run `next build` and spot the errors:

```
Detected 2 cycles

node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/router.js -> node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/with-router.js -> node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/router.js

node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/with-router.js -> node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/router.js -> node_modules/.pnpm/next@12.3.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/client/with-router.js
```

**Comment by SukkaW** [comment]
IMHO that circular dependency does no harm.

`next/dist/client/with-router` imports `useRouter` from `next/dist/client/router`, and `next/dist/client/with-router` is then simply re-exported by `next/dist/client/router` (so that everyone can access `withRouter` through `next/router`).

**Comment by ijjk** [comment]
Closing per above as this shouldn't be an issue in practice.
