### ISSUE TITLE
`_error` getServerSideProps pageProps are not available client-side

### ISSUE THREAD

**Issue by HugoDF** [vercel/next.js#41715]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
npx next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 29 04:31:06 PDT 2022; root:xnu-7195.141.39~2/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.12.3
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.38
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

When accessing `pageProps` for the `_error` page client-side, it's always equal to `{}`.

### Expected Behavior

When accessing `pageProps` for the `_error` page client-side, it should be equal to the value for pageProps server-side.

### Link to reproduction

https://github.com/HugoDF/nextjs-error-serverside-props

### To Reproduce

Breaking reproduction: https://github.com/HugoDF/nextjs-error-serverside-props/tree/master/error-serverside-props-next-canary

- run `yarn build && yarn start`
- load the Next.js homepage
- "Next stars: 94257" will flash but then be replaced with "Next stars: " (no number) when client-side JavaScript kicks in

**Comment by HugoDF** [comment]
I believe this is due to this Pull Request https://github.com/vercel/next.js/pull/21240/files by @ijjk 

From what I understand, that PR will replace the props (including pageProps) with the output of `Error.getInitialProps` unless the error was a "throw during render".

In the reproduction case I used the custom error page from the docs https://nextjs.org/docs/advanced-features/custom-error-page#more-advanced-error-page-customizing.

What's happening is that neither `App` nor `Error` have `getInitialProps` so the props for `Error` are being set to `{}`, see https://github.com/vercel/next.js/blob/92254d137ad87f7b48d3305ebf50751e8c68f8e6/packages/next/shared/lib/utils.ts#L367-L375

A couple of different ways to resolve this would be:

1. check that App/Error has `.getInitialProps` before running it? 
2. check that output of running getInitialProps isn't empty?
3. merge output of getInitialProps and existing/passed props? (this doesn't make so much sense since `getInitialProps` and `getServerSideProps` are mutually exclusive

**Comment by eahenke** [comment]
I'm also running into this problem, I like the idea of only running `getInitialProps` if it's present, and passing through the server-side props otherwise.

**Comment by ijjk** [comment]
Hi, `getServerSideProps` is not officially supported in `_error` only `getInitialProps`. 

See related docs here https://nextjs.org/docs/pages/building-your-application/routing/custom-error#caveats

**Comment by eahenke** [comment]
If anyone else runs into this issue, a workaround is to get the props that are returned by `getServerSideProps` from the `__NEXT_DATA__` field:

```ts
function useInitialDataProps<T>(props: T): T {
  if (typeof window === 'undefined') return props;
  const initData = window.__NEXT_DATA__;
  return initData?.props?.pageProps || props;
}
```
Probably not super stable, but seems to work.
