### ISSUE TITLE
Failed to render page when using SWC WASM for the React documentation

### ISSUE THREAD

**Issue by d3lm** [vercel/next.js#41726]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
Binaries:
  Node: 16.14.2
  npm: 8.5.0
  Yarn: 1.22.19
  pnpm: 7.13.5
Relevant packages:
  next: 12.3.2-canary.38
  eslint-config-next: 12.0.3
  react: 0.0.0-experimental-cb5084d1c-20220924
  react-dom: 0.0.0-experimental-cb5084d1c-20220924
```

### Describe the Bug

When using SWC WASM I am running into the following issue:
![CleanShot 2022-10-24 at 17 03 12](https://user-images.githubusercontent.com/12571019/197559461-ca9a81f9-0a82-4d6d-9c0f-6420f966364b.png)

### Expected Behavior

It works fine when using the native version of SWC but not the WASM. I expect it to work with the WASM as well.

### Link to reproduction

https://stackblitz.com/~/github.com/reactjs/reactjs.org

### To Reproduce

Here's how to reproduce the issue:
1. Clone the React documentation https://github.com/reactjs/reactjs.org
2. `cd beta`
3. `yarn`
4. Remove `node_modules/@next/swc-{your-platform}`, e.g. `rm -rf node_modules/@next/swc-darwin-arm64`
5. `yarn dev`
6. Open `http://localhost:3000` in your browser
7. The error dialog should pop up showing the above error

**Comment by balazsorban44** [comment]
Hi, I tested this with the latest `canary` and it seems like the issue has been fixed already.
