### ISSUE TITLE
Docs: Inline documentation for the 'legacyBehavior' property seems to specify an incorrect default value

### ISSUE THREAD

**Issue by haykam821** [vercel/next.js#41807]
### What is the improvement or update you wish to see?

These two documentation sources seem to conflict:

https://github.com/vercel/next.js/blob/ba02680b7bd0e3f0830ab371ef1d25dbaab4404f/packages/next/client/link.tsx#L79-L83

https://github.com/vercel/next.js/blob/ba02680b7bd0e3f0830ab371ef1d25dbaab4404f/docs/api-reference/next/link.md?plain=1#L53

From my testing, the latter documentation is correct.

In addition, some other inline documentation appears outdated based on the now-default experiment flag:

https://github.com/vercel/next.js/blob/ba02680b7bd0e3f0830ab371ef1d25dbaab4404f/packages/next/client/link.tsx#L85-L99

### Is there any context that might help us understand?

In Next.js 13, the new `<Link>` behavior was made default.

**Comment by balazsorban44** [comment]
Thanks, indeed the inline code documentation should reflect the new default behaviour. would you be interested in opening a PR?

**Comment by abayomi185** [comment]
I'm happy to open a PR for this.

**Comment by mkayander** [comment]
This issue can be now closed i suppose.
