### ISSUE TITLE
Docs: How to get the context object in Next 12 getStaticProps in Next 13, which have params and locale we can access from the server environment 

### ISSUE THREAD

**Issue by TrustyTechSG** [vercel/next.js#41823]
### What is the improvement or update you wish to see?

Docs: How to get the context object in Next 12 getStaticProps in Next 13, which have params and locale we can access from the server environment ?

### Is there any context that might help us understand?

We need to know the request host address during SSG/ISR.

**Comment by balazsorban44** [comment]
Hi, check out:

- https://beta.nextjs.org/docs/data-fetching/generating-static-params
- https://beta.nextjs.org/docs/guides/internationalization

Please leave a comment directly on the documentation, or open a new issue if something is unclear still
