### ISSUE TITLE
Docs:  Nextjs 13 - how to migrate custom webpack config at turbopack?

### ISSUE THREAD

**Issue by zigang93** [vercel/next.js#41820]
### What is the improvement or update you wish to see?

Turbopack look awesome for me so I decide to try nextjs 13.. but I have some webpack config need to migrate.. I wonder how to write in turbopack.. I want to get buildId for my env.. 
```js
// next.config.js file

webpack: (config, { buildId }) => {
    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env': {
          BUILD_ID: JSON.stringify(buildId),
        },
      })
    )
    return config
  },
```

### Is there any context that might help us understand?

Any example how existing webpack custom config can be migrate into turbopack?

**Comment by balazsorban44** [comment]
Hi, as a reminder Turbopack does not have it as a goal to provide a 1:1 migration guide from Webpack to Turbopack as stated:
https://turbo.build/pack/docs/migrating-from-webpack#will-it-be-compatible-with-webpacks-api


But we will make sure to bring the whole Webpack community with us, so please head over to https://github.com/vercel/turbo/discussions/2312 to give this feedback to the team. 🙏
