### ISSUE TITLE
Docs: Broken link on next-13 blog

### ISSUE THREAD

**Issue by kev2480** [vercel/next.js#41836]
### What is the improvement or update you wish to see?

The link "[deploy an example to try it out](https://vercel.com/templates/next.js/app-directory)" at the [streaming section](https://nextjs.org/blog/next-13#streaming) at the next-13 blog post  goes to a 404 page

### Is there any context that might help us understand?

Go to https://nextjs.org/blog/next-13#streaming and select the link [deploy an example to try it out](https://vercel.com/templates/next.js/app-directory)

### Does the docs page already exist? Please link to it.

https://nextjs.org/blog/next-13#streaming

**Comment by balazsorban44** [comment]
Thanks, this has been fixed.
