### ISSUE TITLE
(Beta) Docs: Broken links in /getting-started

### ISSUE THREAD

**Issue by awareness481** [vercel/next.js#41840]
### What is the improvement or update you wish to see?

In https://beta.nextjs.org/docs/getting-started , accessing "internal links" (as in links with `#`) leads to a `404`. This **does not** happen if you're routed from the app internally, only when using the link directly (as in pasting the link in the browser bar)

These should all lead to 404s

https://beta.nextjs.org/docs/getting-started#choose-your-path
https://beta.nextjs.org/docs/getting-started#automatic-installation
https://beta.nextjs.org/docs/getting-started#running-the-development-server
https://beta.nextjs.org/docs/getting-started#features-overview
https://beta.nextjs.org/docs/getting-started#next-steps

### Is there any context that might help us understand?

Didn't notice this in other pages ( but I also haven't checked each page )

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/getting-started

**Comment by ijjk** [comment]
Hi, thanks for sharing this, it should now be corrected!
