### ISSUE TITLE
App directory mobile screen value is broken

### ISSUE THREAD

**Issue by codekcv** [vercel/next.js#41842]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Mon Sep 19 19:14:52 UTC 2022
    Binaries:
      Node: 16.17.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.2-canary.43
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Tested on Firefox, Brave, Chrome

### How are you deploying your application? (if relevant)

Local or deployed, same issue.

### Describe the Bug

I was migrating from pages folder to app directory folder. Then I noticed the mobile responsiveness broke. I immediately noticed because I designed it with mobile-first approach.

When using the device toolbar to test responsiveness, the new app directory gives a different/larger value now. This breaks mobile responsiveness as using the new app doesn't trigger the mobile style counterparts as it gives a large "desktop" like value when viewed on mobile.

(✔️) When using pages routing:
![nextjs-pages](https://user-images.githubusercontent.com/51011835/197978379-644a6cb8-832f-449c-9079-dee0e87b0549.png)

(❌) When using the new app directory routing:
![nextjs-appdir](https://user-images.githubusercontent.com/51011835/197978371-524b2e7f-2293-472e-bc48-6c084549a4ce.png)

Deploying and testing it on an actual device also yields the same broken value.

Note: Use the DEVICE TOOLBAR to reproduce this.

Note 2: Using server or client component yields the same result.

### Expected Behavior

The width on component using app dir should say 390 px as well.

### Link to reproduction

https://nextjs-appdir-responsiveness-issue-146a.vercel.app/

### To Reproduce

1. Enable and use the app directory.
2. Add a CSS media query to the home page e.g max-width 600 px.
3. Apply different styling if hits media query.
4. View in mobile then check if responsiveness worked.

Try to also reproduce these steps but using the pages folder. It will behave properly.

Note: Use the DEVICE TOOLBAR and choose a dimension from the list (e.g. iPhone 12 Pro) to reproduce this.

**Comment by codekcv** [comment]
Fixed by adding this in the app dir's root layout head element.
`<meta name="viewport" content="width=device-width, initial-scale=1.0" />`

Though I didn't have to do this before with the old page folder routing system.

**Comment by joulev** [comment]
I suppose this meta tag should be added by default? All other frameworks I know (including Next.js 12) do this. In that case probably it's best to reopen this.
