### ISSUE TITLE
Allow prop className in next/link in Next.js v13

### ISSUE THREAD

**Issue by Sandstedt** [vercel/next.js#41850]
### Describe the feature you'd like to request

Please add the prop className to the next.js v13 next/link so you can style the underlaying a-tag. Now if you wanna use any styling you need to either wrap it in a unnecessary html element, or use the legacyBehavior prop and add the styled anchor link as a child.

### Describe the solution you'd like

```
<Link className="styled-a-class" href="#">Styled a link</Link>
```

or using styled-components:

```
const StyledLink = styled(Link)`
   color: green
`

<StyledLink href="#">Styled a link</Link>
```

### Describe alternatives you've considered

Using the legacyBehavior.

**Comment by Sandstedt** [comment]
Just kidding. Didn't have next 13 installed. Apparently following some old next documentation where it was not `npm i next@latest`, just `npm install next`.

**Comment by kmergen** [comment]
You can use className in next/link and many other props.
