### ISSUE TITLE
Docs: Next 13 static/dynamic without fetch() API

### ISSUE THREAD

**Issue by flexdinesh** [vercel/next.js#41851]
### What is the improvement or update you wish to see?

I would like the docs to explain a bit more about static/dynamic rendering without using the `fetch()` API. Eg. when using API clients like `@upstash/redis`.

### Is there any context that might help us understand?

I'm migrating an ISR Next 12 `pages/mypage/[id].tsx` to Next 13 `app/mypage/[id]/page.tsx` and I couldn't find how to configure static/dynamic when I'm not using the `fetch()` API. The docs seem to be written around the expectation that the user will either use the `fetch()` API or the dynamic functions. I'm using `@upstash/redis` client and want to configure the page to be server rendered only once and be statically served from the global cache for subsequent requests. I even want to be able to [use On-Demand Revalidation](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation) so I could server render the page when the id is created so users will only ever read the page from the global cache. How would I go about it in Next 13?

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering#static-data-fetching-default

<sub>[DX-1666](https://linear.app/vercel/issue/DX-1666/docs-next-13-staticdynamic-without-fetch-api)</sub>

**Comment by diegohaz** [comment]
Have you tried https://beta.nextjs.org/docs/api-reference/segment-config?

**Comment by flexdinesh** [comment]
Looks like [Segment Config](https://beta.nextjs.org/docs/api-reference/segment-config#revalidate) is what I want. Hopefully it will work the same as omitting `revalidate` in `getStaticProps` and manually revalidating the cache from an API handler. 
```js
// pages/api/revalidate.js

export default async function handler(req, res) {
  // Check for secret to confirm this is a valid request
  if (req.query.secret !== process.env.MY_SECRET_TOKEN) {
    return res.status(401).json({ message: 'Invalid token' })
  }

  try {
    // this should be the actual path not a rewritten path
    // e.g. for "/blog/[slug]" this should be "/blog/post-1"
    await res.revalidate('/path-to-revalidate')
    return res.json({ revalidated: true })
  } catch (err) {
    // If there was an error, Next.js will continue
    // to show the last successfully generated page
    return res.status(500).send('Error revalidating')
  }
}

```
ref: [On-Demand Revalidation](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation)

**Comment by icyJoseph** [comment]
I have a page which shows data from a cookie, but the data is only fresh upon hard loading of the page. SPA transitions into it do not trigger a server fetch, though I am using `export const dynamic = "force-dynamic"` I've also tried with a config object with a dynamic property, still nada. 

Anyone got any pointers?

**Comment by timneutkens** [comment]
> I have a page which shows data from a cookie, but the data is only fresh upon hard loading of the page. SPA transitions into it do not trigger a server fetch, though I am using export const dynamic = "force-dynamic" I've also tried with a config object with a dynamic property, still nada.

You're likely seeing https://beta.nextjs.org/docs/routing/linking-and-navigating#soft-navigation, in this case you might want to `router.refresh()` on the page itself if it always needs fresh data. Soft navigation is set up to integrate with the upcoming mutations implementation.

> Looks like [Segment Config](https://beta.nextjs.org/docs/api-reference/segment-config#revalidate) is what I want.

The default is to do a static render pass during `next build` for all routes, only if you opt-out of static using `headers`, `cookies`, the segment config (`force-dynamic`) or `fetch` with `cache: 'no-store'` does it end up rendering on-demand. In the case where you're not using fetch (e.g. redis, prisma, etc) you can use the segment-level config to get the same result as what `fetch()` allows.

Static rendered routes support on-demand revalidate.

**Comment by icyJoseph** [comment]
I actually observe no issues now with `13.0.1`. I am not really sure how it got fixed though. I don't even need to `force-dynamic` which is lovely.

**Comment by AlexKvazos** [comment]
I can still see a soft navigation happening when using `dynamic = 'force-dynamic'`. Here is an example where you can reproduce the issue:

https://stackblitz.com/edit/nextjs-sxijav?file=app/nested/page.tsx

Steps to reproduce:
- Click link to go to the nested page, a random number will show
- Click link to go to home page
- Click link to go to nested page

Bug: Same number shows (Expected: Different number)

**Comment by gfortaine** [comment]
@AlexKvazos It looks like that you are doing [Client-Side Navigation](https://nextjs.org/learn/basics/navigate-between-pages/client-side) with a [Server Component](https://beta.nextjs.org/docs/rendering/server-and-client-components#server-components). Simply add the directive `"use client" directive`](https://github.com/reactjs/rfcs/pull/227) at the top of the `NestedPage` component. Then, you will notice that it will trigger a re-render on client-side transition using `next/link` :

https://stackblitz.com/edit/nextjs-ckafad?file=app%2Fnested%2Fpage.tsx

**Comment by Fredkiss3** [comment]
@gfortaine 

> It looks like that you are doing [Client-Side Navigation](https://nextjs.org/learn/basics/navigate-between-pages/client-side) with a [Server Component](https://beta.nextjs.org/docs/rendering/server-and-client-components#server-components). Simply add the https://github.com/reactjs/rfcs/pull/227 at the top of the NestedPage component. Then, you will notice that it will trigger a re-render on client-side transition using next/link

There is a problem though : it causes hydration mismatches, as you can see in the screenshot below :
 
![image](https://user-images.githubusercontent.com/38298743/201671029-6a542870-a543-459d-9bcc-5d80a2659a2b.png)
 
And what about data fetching ? 
I've tweaked the example and make it fetch a random number instead on the server : 
https://stackblitz.com/edit/nextjs-zskblw?file=next.config.js,app%2Fnested%2Fpage.tsx

And wether i add a `cache: no-store` or `next: { revalidate: 0 }` it still does a soft navigation and the user needs to reload the page fully to see a different number.

**Comment by Babaktrad** [comment]
> Looks like [Segment Config](https://beta.nextjs.org/docs/api-reference/segment-config#revalidate) is what I want. Thanks for pointing out @diegohaz. Hopefully it will work the same as omitting `revalidate` in `getStaticProps` and manually revalidating the cache from an API handler.
> 
> ```js
> // pages/api/revalidate.js
> 
> export default async function handler(req, res) {
>   // Check for secret to confirm this is a valid request
>   if (req.query.secret !== process.env.MY_SECRET_TOKEN) {
>     return res.status(401).json({ message: 'Invalid token' })
>   }
> 
>   try {
>     // this should be the actual path not a rewritten path
>     // e.g. for "/blog/[slug]" this should be "/blog/post-1"
>     await res.revalidate('/path-to-revalidate')
>     return res.json({ revalidated: true })
>   } catch (err) {
>     // If there was an error, Next.js will continue
>     // to show the last successfully generated page
>     return res.status(500).send('Error revalidating')
>   }
> }
> ```
> 
> ref: [On-Demand Revalidation](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation)

You said you're migrating from `pages` Router to `app` Router. How this solution could help you?!

**Comment by samcx** [comment]
@flexdinesh Closing this since this issue is stale and our documentation has gone through many iterations since this!

- https://nextjs.org/docs/app/building-your-application/rendering/server-components
