### ISSUE TITLE
with-turbopack occasionally throws "Error during SSR rendering - timed out waiting for the Node.js process to connect" when navigating pages

### ISSUE THREAD

**Issue by muradbu** [vercel/next.js#41859]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Using Windows 10 with WSL2:
```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: N/A
      pnpm: 7.14.0
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-turbopack

### What browser are you using? (if relevant)

Firefox 107.0b4

### Describe the Bug

The new `with-turbopack` example occasionally throws during dev:
```
error - [rendering] [root of the dev server]/[CURRENT ROUTE TRYING TO RENDER]
  Error during SSR Rendering
  timed out waiting for the Node.js process to connect
```

Most of the time the page does end up rendering successfully and an `event - updated in _xxx_ms` gets logged, but on some occasions it throws the above error in the console while still rendering the page. I can still navigate to other pages, but the console stops logging events. This can happen on all pages when I navigate to them. 

Sometimes the error blocks the entire page from rendering by throwing an error in the browser, although this only occurred twice: 
![image](https://user-images.githubusercontent.com/10285764/198056563-24e7a071-2823-41d4-8b63-46b2eaed1014.png)

I cannot figure out a pattern that causes this error, the pages load fine most of the time but occasionally throw this error unexpectedly.

### Expected Behavior

On navigating, a page should render without errors, echoing an `event` to the console with the amount of time it took to update.

### To Reproduce

1. Create a new project using the example.
```
pnpm create next-app --ts --example with-turbopack
```

2. Run the dev command (`--turbo` is included in the `dev` script by default in this example.)
```
pnpm run dev
```

3. Go to http://localhost:3000 in the browser and click the links in the sidebar to navigate to different pages.
3.a. Pay attention to the console as the error might be thrown even though the page rendered.
4. After some successful navigation events this error might be thrown (multiple times if you continue navigating):
![image](https://user-images.githubusercontent.com/10285764/198060131-8d57d5c0-9194-49f2-a699-7eb0732608fa.png)
4.a On some occasions the error can be thrown in the browser as well, preventing the page from rendering.

**Comment by zacard-orc** [comment]
I have the same problem...

**Comment by 4dams** [comment]
I am also facing this issue currently – for me, it is happening on every render.

___ 

Version: `"next": "13.0.0"`
Command: `yarn dev -- --turbo` (`next dev --turbo`)

**Comment by iamanas20** [comment]
I used Node 16 and it worked!

`npm install -g n`
`n`

**Comment by muradbuyukasik** [comment]
> Switching from node14 to node16 **fixed** this for me.
> 
> using nvm
> 
> `nvm use 16`

Weird, I'm already on 16.17.1

**Comment by NotLimey** [comment]
Im having the same problem on node version: 16.15.1

**Comment by webston** [comment]
It didn't work for me on node v14, but I tried with v16.18.0, and it works well.

**Comment by o2sevruk** [comment]
The same issue. 
v14, v16, v16.18.0 - are not working.

`Turbopack failed to compile`
`error - [rendering] [root of the dev server]/  Error during SSR Rendering timed out waiting for the Node.js process to connect`

PS: SoC M1

**Comment by nrowan** [comment]
I am getting this on every load using Windows 11, WSL2, Ubuntu 22.04, node 16 and node 18. If I run this directly on Windows 11 with node 16 it seems to work fine.

**Comment by praveenkumarsaravanan** [comment]
Same issue happens in M1 Mac as well, with Node 19

**Comment by franzwilhelm** [comment]
M1 Pro, Node LTS - happening here too

**Comment by khervie-star** [comment]
Uhm , having issue, MBP 2018, 
Switched node versions to 16 as well and still the same

**Comment by ssynowiec** [comment]
I'm having the same problem on node version: v16.15.1 and v18.12.0

**Comment by littleCareless** [comment]
I also have this problem in window 10 19044.2130 ,node v16.15.0 and there are no errors in the console, only on the page

**Comment by agustrinaldokurniawan** [comment]
got same error using node 14.20.1, but running well using node 16.18.0 (windows 11)

**Comment by RajVarsani** [comment]
I am on `v16.13.0` and getting the same error.

**Comment by YunosukeYoshino** [comment]
16.18.0 worked for windows!
Does not work with M1 MAC

**Comment by nsaicharan** [comment]
Having the same issue. It does **not** work even with v16.18.0.

**Comment by b-meet** [comment]
I am also getting the same error using trubopack, webpack ain't showing any kind of errors. node version `16.17.1`

**Comment by Infinitay** [comment]
node: `16.13.1`

It was working fine at first, but then it suddenly stopped working.

**Comment by shahin-bayat** [comment]
same error for me on node `16.13.0` and `18.12.0` on M2 chip.
Nextjs version: `13.0.2`, Nextjs `13.0.0` works fine.

**Comment by Chip-Mortensen** [comment]
M1 Macbook Air same issue

**Comment by shsxnk** [comment]
yes facing same issue on chip M1.
node `v14.17.6 ` and npm `6.14.15`

**Comment by adshodgson** [comment]
Did some digging, works on Node v16 but anything above SSR Rendering issue...

**Comment by camilo-mujica** [comment]
Same issue here, with node v16.18.1 and npm 8.19.2

**Comment by cizz3007** [comment]
`    "@next/font": "13.0.7-canary.6",
    "next": "13.0.7-canary.6",`

hardware: macbook air m2

i have same issue when i try to import @next/font/google

**Comment by HuynhTuanWD** [comment]
same issue M1
node `v18.13.0` and npm 8.19.2

**Comment by nx23** [comment]
I'm having the same issue.

Windows 11
Arch Linux on WSL 2
node v19.3.0
Next.js v13.1.2

**Comment by bernardomoraes** [comment]
I'm also having the same issue and without the `--turbo`, the app runs normally.

- node v16.17.0
- Next.js v13.1.2
- Linux Ubuntu 22.04

**Comment by ygorluiz** [comment]
I'm having the same issue.

 Windows 11

* Linux Ubuntu 22.04  WSL2
* node v18.12.1
* Next.js v13.1.2

**Comment by iammati** [comment]
Same here:

- Debian 11 (bullseye) (with WSL2)
- Node.js v18.12.0 (pnpm v7.25.0)
- Next.js v13.1.2

Also using the example with TypeScript and Turbopack.

**Comment by SanchitB23** [comment]
Same here:

- Windows 10
- Node v18.12.1
- Nextjs v13.1.6

**Comment by MarekDzw** [comment]
I was receiving this timeout warning when I was running app with `next dev --turbo`. I also tried it without `--turbo` flag and I received different error in console, which was a lot more specific. 

With `--turbo`:
nothing in console just `500`
![image](https://user-images.githubusercontent.com/33802916/227646931-457b0f72-bf99-4505-97b4-3164b468cdba.png)
![image](https://user-images.githubusercontent.com/33802916/227646964-74a13ccb-3404-40db-9795-fe4d36653bf0.png)

Without `--turbo`:
![image](https://user-images.githubusercontent.com/33802916/227647146-b05c04a5-d6ba-4b9e-8b14-3e2b797fdf62.png)
![image](https://user-images.githubusercontent.com/33802916/227647200-d9aba9e5-5006-44d8-867b-b768048d87b0.png)

As you can see without using turbo the errors are descriptive and points to where the error is. 
Looks like turbo somehow is missing what caused the error and just throws error. 
If you have problem with while using turbo try also running your app without it to see if it also produces any errors.

**Comment by ken-kay** [comment]
I experienced the same error when trying to add a 'react-hook-form'. It seems to have an issue with the addition of 
<input {...register('name', {required:true})} 
...
/>

Versions:
- Node v19.7.0
- NextJS v13.2.4
- Windows 10

**Comment by sokra** [comment]
I think this should be fixed (a while ago). Do you still see this problem on the latest version?

**Comment by mjad218** [comment]
I have solved the bug!!.

I was using: 
```
export async function generateMetadata({ params }: IProps): Promise<Metadata> {
// I do a fetch request here
}
```

When I wrapped that fetch request in a try catch, the error disappeared. 

After: 
```
export async function generateMetadata({ params }: IProps): Promise<Metadata> {
  const orderId = params.order;
  const nextCookie = cookies();
  const sid = nextCookie.get("sid")?.value;
  let order = null;
  try {
    order = await getOrderByUUIDOrReturnNull(orderId, sid);
  } catch (error) {}

  const description = order?.uuid || "";
  const title = order?.uuid || "";

  const metadata: Metadata = {
    title: title,
    description: description,
  };
  return metadata;
}

```

I also did the same on the component too. 

In the function `getOrderByUUIDOrReturnNull`, I wrap a fetch request in a try catch and return null if error. 

So there should be no need to wrap it inside `generateMetadata` in a `try catch`. 

I hope this can help anyone having the same bug.

**Comment by ForsakenHarmony** [comment]
Going to close this as turbopack itself no longer does SSR rendering, that's handled by next.js now
