### ISSUE TITLE
Next 13 fetch in server component stuck forever if response is larger than ~15kb 

### ISSUE THREAD

**Issue by Escapado** [vercel/next.js#41853]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Wed Oct 26 2022 14:44:18 GMT+0200 (Central European Summer Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When fetching data [as described in the docs](https://beta.nextjs.org/docs/data-fetching/fetching), the fetch function gets stuck and never resolves, if the payload reaches a certain size.

I created a minimal stackblitz and a mock api to reproduce the problem. If I fetch 75 posts from the mock api it will never resolve, if I only fetch 50 it works fine. Since I was able to reproduce this problem with multiple mock apis and even when using something like supabase to fetch some data I think it might be a size issue? Here the difference is 14kb vs 20kb for the two requests.

_**EDIT:**_
I tried to nail the problem down further. fetch does indeed resolve but `.json()` does not. Does this have to do with the highWaterMark buffer size limit on nodejs streams?

### Expected Behavior

Fetch should not get stuck forever.

### Link to reproduction

https://stackblitz.com/edit/nextjs-vv7ryj?file=app/page.tsx

### To Reproduce

- Open the stackblitz
- Comment out line 3 and comment in in line 4 in `pages.tsx` to fetch 75 instead of 50 posts
- See that fetch never resolves

**Comment by renomureza** [comment]
@Escapado  I think line 4 i.e. this API https://apimocha.com/next13/75posts returns an invalid response body for JSON. they don't have an opening array tag "[".

![image](https://user-images.githubusercontent.com/49445216/198052615-d2863d72-d552-45b2-a331-19d260ea534d.png)

**Comment by Escapado** [comment]
Thanks @renomureza. I fixed that. However the issue still stands it's reproducible if you for example try the following mock apis:
`https://jsonplaceholder.typicode.com/posts`
`https://jsonplaceholder.typicode.com/comments`

**Comment by TheoBr** [comment]
This hurts me deeply

**Comment by balazsorban44** [comment]
Thanks for reporting, I did some digging, and the issue seems to be `node-fetch`-specific.

Currently, on the server, Next.js uses `node-fetch` to polyfill `fetch` when Node.js <18 is used. Above Node.js 18, or when the `experimental: {enableUndici: true}` option in `next.config.js` is present, we will use `undici` instead, which does not have this problem.

So current workarounds are:

1. Use Node.js 18 or above, if possible
2. Add the following to `next.config.js`:
```js
module.exports = {
  experimental: {
    enableundici: true
  }
}
```

**Comment by mechadragon01** [comment]
```
module.exports = {
  experimental: {
    enableUndici: true
  }
}
```

`enableUndici` needs to be camelCase

**Comment by srini-leanfolks** [comment]
using node-fetch solved this

**Comment by nowaythatworked** [comment]
> using node-fetch solved this

What version did you use? As @balazsorban44 mentioned, Next.js also uses node-fetch under the hood. Perhaps they are using a different version?

**Comment by srini-leanfolks** [comment]
@nowaythatworked node-fetch v3.2.10

**Comment by icyJoseph** [comment]
https://github.com/vercel/next.js/issues/41988 I see now.... the payload on this one is about 300kb

**Comment by timneutkens** [comment]
Investigated this one on my flight back from Next.js Conf, it's a known issue with cloning responses of `fetch()` in node-fetch and I could reproduce it with standalone node-fetch as well (outside of Next.js) both in the latest 2.x and 3.x release. Since we're moving to using undici anyway I've made it so that `appDir` enabled it by default. Note that this does mean that `appDir` now requires Node.js 16.8 or later.

**Comment by icyJoseph** [comment]
When deploying to Vercel, on next@13.0.1, I still see this problem.

- The enableUndici flag is still needed, even locally though
- In Vercel, when the flag is active and with `next@13.0.1`, the build process goes swell, but then at runtime I get timeouts on functions that use `fetch` within Server Components. API routes work fine.

```
[GET] /pokemon/1
11:01:15:13
Fetching pokemon: 1
Got JSON for specie
2022-11-01T10:01:26.263Z 171204fd-e67e-4df5-8281-033e63eb019f Task timed out after 10.01 seconds
```

- This is the [page](https://github.com/icyJoseph/next-js-react-gbg/blob/next-13-css-modules/demo-app/app/pokemon/%5Bid%5D/page.tsx)
- Actual [function](https://github.com/icyJoseph/next-js-react-gbg/blob/next-13-css-modules/demo-app/lib/pokemon.ts#L24)

Could the problem be that this function lives at `lib/` and not within `app/`?

**Comment by ervwalter** [comment]
FYI to @timneutkens, I can confirm that this is still broken when deploying to Vercel (same as what @icyJoseph is seeing).  Neither manually setting `enableUndici` nor using `next@13.0.2-canary.0` makes a difference.  

Server Components that fetch large payloads hang until the serverless function times out.  

I added some debug output and determined that my Vercel deployment is running Node.js v16.16.0.

**Comment by swamidass** [comment]
Same problem here. Still broken on deploy,but works fine in dev now.

**Comment by ervwalter** [comment]
FYI, I just confirmed that this Vercel deployment aspect is fixed in [v13.0.2-canary.1](https://github.com/vercel/next.js/releases/tag/v13.0.2-canary.1) via #42382

**Comment by BWBama85** [comment]
I am seeing this warning now but do not have this option configured: https://github.com/vercel/next.js/issues/42441

**Comment by ijjk** [comment]
Hi this should be updated in `v13.0.2` please update and give it a try!

**Comment by swamidass** [comment]
I can confirm it is fixed. Thanks!
