### ISSUE TITLE
Setting `use client` on a page in the app directory crashes on Vercel deployment

### ISSUE THREAD

**Issue by lesleh** [vercel/next.js#41890]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Creating a page in the new `app` directory structure and setting `"use client"` on it crashes the page on Vercel.

### Expected Behavior

Not to crash.

### Link to reproduction

https://github.com/lesleh/next-13-client-page

### To Reproduce

Broken page example code can be found here - https://github.com/lesleh/next-13-client-page/blob/main/app/broken/page.js

Deployment URL: https://next-13-client-page.vercel.app/broken

**Comment by jescalan** [comment]
Thank you for reporting - we're looking into this one 👀

**Comment by christianjuth** [comment]
Is this fixed for new Vercel deployments? I'm noticing crashes for any app page or layout that implements `"use client"`.  However, importing components that implement `"use client"` and rendering those components within app pages works.

In other words, I think `"use client"` causes crashes when it's called at the top level – top level being `layout` and `page` files.

Locally everything is working. After deploying to Vercel loading pages that call `"use client"` top level throws a 500 error in the browser. This 500 error does not appear in Vercel logs.

Repo
https://github.com/christianjuth/next13-test

Server Component App Route (working)
https://next13-test-3v0njufl1-christianjuth.vercel.app/working

Client Component App Route (not working)
https://next13-test-3v0njufl1-christianjuth.vercel.app/broken

**Comment by lesleh** [comment]
@christianjuth it's fixed in `next@canary`.
