### ISSUE TITLE
Docs: Clarify where error boundary can be used

### ISSUE THREAD

**Issue by joliss** [vercel/next.js#41898]
### What is the improvement or update you wish to see?

https://nextjs.org/docs/advanced-features/error-handling says (bold mine):

> To use Error Boundaries for your Next.js application, you **must** create a class component `ErrorBoundary` and wrap the `Component` prop in the `pages/_app.js` file.

This left me wondering if Next.js allows me to also wrap individual React components, rather than the whole app, or if that will cause problems.

If wrapping individual components isn't supported, we should perhaps emphasize that here.

If wrapping individual components *is* supported, I would suggest removing "you must", and also mentioning wrapping individual components as an alternative to wrapping the whole app.

### Is there any context that might help us understand?

none

<sub>[DX-1665](https://linear.app/vercel/issue/DX-1665/docs-clarify-where-error-boundary-can-be-used)</sub>

**Comment by leerob** [comment]
Going to close this one as stale 🙏 You can wrap individual components, yes!
