### ISSUE TITLE
Page doesn't hydrate when <html>, <head>, and <body> are not added to the root layout

### ISSUE THREAD

**Issue by PatrikTheDev** [vercel/next.js#41896]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Tue Sep 27 22:08:45 PDT 2022; root:xnu-8792.41.6~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.5.2
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Arc (chromium)

### Describe the Bug

When using the app dir (and thus using RSC), HMR doesn't work correctly. 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/25883885/198127762-eb545227-e47b-4db3-9fe4-840f1a33e6ee.png">

### Expected Behavior

HMR should be working for Server Components as well as Client Components.

### Link to reproduction

https://github.com/PatrikTheDev/hmr-reproduction

### To Reproduce

Open the project, install deps with pnpm, start the dev server

Open it in a browser and edit one of the files. The developer console will complain about an invalid HMR message.

**Comment by balazsorban44** [comment]
Thanks for reporting! So the main issue is that `layout.tsx` needs to return `html`, `body` and `head` as documented here: https://beta.nextjs.org/docs/routing/pages-and-layouts#root-layout-required

We could however provide a better warning for this type of error, so we are keeping this issue to track.

**Comment by samcx** [comment]
@PatrikTheDev I believe this has since been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> with a better error message!

![CleanShot 2024-11-12 at 16 33 42@2x](https://github.com/user-attachments/assets/495cd801-a9ea-47d2-b9c6-f2b95ac6c860)
