### ISSUE TITLE
@next/font does not have a character subset that includes left and right arrows

### ISSUE THREAD

**Issue by calebmer** [vercel/next.js#41923]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022
    Binaries:
      Node: 14.19.3
      npm: 6.14.17
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

(The canary was erroring when I tried to use the canary version so went back to v13)

### Describe the Bug

The → (U+2192) and ← (U+2190) characters have custom glyphs in fonts like [Inter](https://rsms.me/inter/glyphs/) but `@next/font` only lets you pick subsets that don’t include those characters.

I see:

<img width="28" alt="image" src="https://user-images.githubusercontent.com/8282507/198168230-2d9664bd-cbb0-47b6-9b6e-0f90e64e1f07.png">

### Expected Behavior

There is a subset (or all subsets) that include Unicode characters like → (U+2192) and ← (U+2190)

I expect to see:

<img width="28" alt="image" src="https://user-images.githubusercontent.com/8282507/198168275-efc58f06-c992-4e75-8fff-8e21af526ae2.png">

### Link to reproduction

https://codesandbox.io/s/next-font-inter-bug-repro-br3dcy?file=/pages/index.tsx

### To Reproduce

Open the [sandbox](https://codesandbox.io/s/next-font-inter-bug-repro-br3dcy?file=/pages/index.tsx)

**Comment by hanneslund** [comment]
Those glyphs aren't included when getting Inter from Google fonts. It's possible to [download Inter](https://rsms.me/inter/) and use with `@next/font/local` if you'd like to get everything included.
