### ISSUE TITLE
Next 13 - Using number constants for `revalidate` value make TS complain in VS Code

### ISSUE THREAD

**Issue by oleg-semyonov** [vercel/next.js#41951]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.12.1
      Yarn: 1.22.17
      pnpm: 7.1.3
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

For some weird reason whenever I use a constant for `revalidate` parameter of a page component, I get a TS error in VS Code stating that this is an invalid value. It looks like it's validating agains the constant name and not the value.

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/1641218/198236926-acf63c00-f1b5-4ed4-8457-e93ef88f7c7c.png">

The app still runs and builds fine, and when running TSC manually, I don't get this error message.

### Expected Behavior

`revalidate` should support both passing arbitrary values and variables as long as their type is correct.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-agx376

### To Reproduce

Unfortunately I couldn't reproduce the issue on Stackblitz (maybe some VS Code settings are different), but the error message is definitely coming from the `next` typescript plugin, see [this file](https://github.com/vercel/next.js/blob/canary/packages/next/server/next-typescript.ts#L544)

**Comment by shuding** [comment]
This is the correct behavior because these configurations should be statically analyzable (e.g. the compiler can know the information without executing the code). So things like `export const revalidate = 1 + 1` or `export const revalidate = anotherVariable` will not work.

That said, the error message isn't great and it should explain this better. We will improve that part for sure, thanks for opening this issue 👍

**Comment by oleg-semyonov** [comment]
Thanks for the clarification @shuding! I think it would make sense to also mention that in the docs to prevent confusion :)
