### ISSUE TITLE
Nextjs 13 - with-ant-design not working

### ISSUE THREAD

**Issue by jeffreys-cat** [vercel/next.js#41964]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.0", newest: "13.0.1-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Which example does this report relate to?

with-ant-design

### What browser are you using? (if relevant)

Chrome 105

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

![image](https://user-images.githubusercontent.com/11832969/198274759-6b2249fc-3c3d-414f-8c5d-e88bf8194377.png)

### Expected Behavior

npm run dev successfully

### To Reproduce

Moving the Pages folder to the app, add experimental / appdir true.

![image](https://user-images.githubusercontent.com/11832969/198275164-236f278b-8deb-46c7-b29c-1daeb3544759.png)

![image](https://user-images.githubusercontent.com/11832969/198275079-4687755b-96c5-4463-994f-73f64c34b1e4.png)

**Comment by balazsorban44** [comment]
Hi, we will gradually migrate examples to `app` over time. The example should work in its current form, so I'm closing this issue for now. :+1:

If you are interested in migrating the example yourself, you can check out the migration guide at https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app
