### ISSUE TITLE
Dark Theme ?

### ISSUE THREAD

**Issue by kneeraazon01** [vercel/next.js#41990]
### Describe the feature you'd like to request

It'd help a lot if we got to read in the dark more.

### Describe the solution you'd like

I mean, It's not a big deal can read in the light mode too. But been so used to dark mode now it feels like a good idea to add the theme.

### Describe alternatives you've considered

That's it.

**Comment by balazsorban44** [comment]
Hi, if you refer to the docs, the https://beta.nextjs.org/ version already has it! Once it's out of beta, it will be applied to https://nextjs.org :nail_care: :black_heart:
