### ISSUE TITLE
Base64 encoded images with 'fill' are always triggering 'missing sizes' warning

### ISSUE THREAD

**Issue by menberg** [vercel/next.js#42006]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.10.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

_irrelevant_

### How are you deploying your application? (if relevant)

_irrelevant_

### Describe the Bug

When using the 'fill' prop in the Next.js image component on a Base64 encoded image, the following warning in the console from this [code line](https://github.com/vercel/next.js/blob/2e9e54b64f4162db215c26105deb192b00bd6d55/packages/next/client/image.tsx#L306) will always be logged, even if there IS indeed a "sizes" prop:
```
Image with src "data:image/..." has "fill" but is missing "sizes" prop. Please add it to improve page performance. Read more: https://nextjs.org/docs/api-reference/next/image#sizes
```

According to this [code line](https://github.com/vercel/next.js/blob/2e9e54b64f4162db215c26105deb192b00bd6d55/packages/next/client/image.tsx#L564) in the Next.js image component source code, the ['unoptimized'](https://nextjs.org/docs/api-reference/next/image#unoptimized) flag will be set on all Base64 encoded images. And because of this [code line](https://github.com/vercel/next.js/blob/2e9e54b64f4162db215c26105deb192b00bd6d55/packages/next/client/image.tsx#L203), all `sizes` attributes will be removed on unoptimized images. Thus, there is no way to avoid the triggering of the quoted console warning when using a Base64 encoded image with 'fill' – even if there is a `sizes` attribute given.

### Expected Behavior

The warning should not be triggered on Base64 encoded images with 'fill' and 'sizes' attributes.

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-mjmfqs?file=pages/index.tsx

### To Reproduce

Open reproduction example and check browser console messages. The printed warning message implies that no `sizes` prop is set, which is not true.

**Comment by styfle** [comment]
Thanks for reporting this bug! It will be fixed in PR #42030
