### ISSUE TITLE
Unwanted/unnecessary html tags in Next 13

### ISSUE THREAD

**Issue by TommySorensen** [vercel/next.js#42000]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

npm install && npx next dev

### Describe the Bug

In Next 13 in the /app folder it seems like that there is no way to avoid injecting random `<div>`tags in the dom when nested routes are used.

```js
// app/layout.jsx
export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        <title>Title</title>
      </head>

      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
```

```js
// app/[[..slug]]/page.jsx
export default function Page() {
  return <>Content</>;
}
```

Output in both build and dev mode:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/4134473/198386686-9956d229-cd79-43f5-8e4d-8adde8bffcc8.png">

### Expected Behavior

I would expect the markup to only contain html tags i define myself or else i could end up with styles that will match the unwanted tags generated from NextJS.
```html
...
<body>
  <main>Content</main>
</body>
...
```

### Link to reproduction

https://stackblitz.com/edit/vercel-next-js-kbw8sm?file=next.config.js

### To Reproduce

Run dev or prod mode

**Comment by davidkhierl** [comment]
been figuring out this one the entire day, thought something wrong with all my layouts and had to test every component from top to bottom 🤦‍♂️

**Comment by MattEagle95** [comment]
Hey! This happened to me, too. I found this comment in the v13 discussion thread: https://github.com/vercel/next.js/discussions/41745#discussioncomment-3964086

seems like, if you use canary version `npm install next@canary` the divs should already be added with some identification. but not using them in `appDir` seems to be no choice atm.

**Comment by balazsorban44** [comment]
Thanks for reporting, we are aware and working on a solution: https://github.com/vercel/next.js/discussions/41745#discussioncomment-3973420
