### ISSUE TITLE
Contributing: `nextJest` is not a function

### ISSUE THREAD

**Issue by ctjlewis** [vercel/next.js#42011]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Inside Next repo.

### Describe the Bug

Running `pnpm test` throws `nextJest is not a function`. It appears that `next/jest` exports an ES Module now, and refactoring `jest.config.js` to:

```ts
const { default: nextJest } = require('next/jest')
```

Resolves.

### Expected Behavior

`pnpm test` should run without issues.

### Link to reproduction

Not going to repro here.

### To Reproduce

- Clone Next repo
- `pnpm install`
- `pnpm test`

**Comment by balazsorban44** [comment]
We added an interop for `next/jest` in https://github.com/vercel/next.js/pull/36824

I tried reproducing this using the `with-jest` example, as well as running `pnpm test` in the Next.js repo with the proposed change, but both worked correctly, so I am closing this issue.

If you have a reproduction for a specific project, please open an issue with a reproduction. :+1:
