### ISSUE TITLE
Experimental Next.js 13 app throws PageNotFound error when exported

### ISSUE THREAD

**Issue by psirenny** [vercel/next.js#42017]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
Binaries:
  Node: 16.18.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.0.1-canary.0
  eslint-config-next: 13.0.0
  react: 18.2.0
  react-dom: 18.2.0
```

### Describe the Bug

A new experimental Next.js 13 app throws a PageNotFound error when exported.

### Expected Behavior

Expected the export command to successfully output to the `/out` directory.

### Link to reproduction

https://codesandbox.io/s/vigorous-fire-sppm2c

### To Reproduce

```sh
npx create-next-app@latest --experimental-app
npx next build
npx next export
```

**Comment by balazsorban44** [comment]
`next export` is not yet supported as stated here: https://beta.nextjs.org/docs/app-directory-roadmap#planned-features
