### ISSUE TITLE
next/head elements should be present in raw html 

### ISSUE THREAD

**Issue by steffenlogen** [vercel/next.js#42026]
### Describe the feature you'd like to request

Currently, if I add elements like the title with next/head  in a component these elements are not present in the raw HTML.
It's just present in the rendered HTML. This is not optimal for web crawlers.
Especially on server-side rendered pages, there should be no reason for this behavior.
By adding these elements to the raw HTML web crawling will be easier for webcrawlers.

### Describe the solution you'd like

All next/head element are present in the raw html.

### Describe alternatives you've considered

Considered hard-coding these values in _document. But that was no suitable approach.

**Comment by balazsorban44** [comment]
I believe this should already be the case. :thinking: If you experience an issue, could you maybe open a bug report with an attached reproduction?
