### ISSUE TITLE
Occasional failures (stuck on fallback indefinitely) when using next/font

### ISSUE THREAD

**Issue by agusterodin** [vercel/next.js#42034]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Google Chrome 106.0.5249.119 (Official Build) (arm64). I can't seem to make the issue happen in any other browser (Firefox, Safari)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

The first time I attempted to load my deployment in my browser (deployed on Vercel) my fonts fail to load. It is as if it was stuck on the fallback fonts. Refreshing the page immediately fixed the issue.

In an attempt to try to deterministically recreate the issue, I tried opening the network tab in Google Chrome with the "cache disabled" option enabled. No matter how many times I refreshed this didn't cause the font loading issue to appear again. 

Next I tried opening the site in an incognito window. The font issue appeared again (Exo never flipped from fallback to actual font). As I opened Chrome DevTools, the font flipped to the actual font right away (without any refresh of the page). The actual font showed up every time on subsequent refreshes without issue. For some reason I can't get the issue to happen in an incognito window again even if I completely close out of incognito mode and reopen.

I also tried loading the site on my Xbox Series X (with Chromium-based Edge browser). The font issue appeared again (stuck on fallback until I refresh). After refreshing once, I can't get the issue to appear again.

For what it is worth I could not get this issue to appear on Safari or Firefox. Not a single time.

I am confused on whether this is a Vercel, Next, or Chromium issue. Perhaps it is because I am using CSS variables for fonts?

### Expected Behavior

Font loads correctly every time (including first time site is ever loaded) and doesn't get stuck on fallback font.

### Link to reproduction

https://github.com/agusterodin/next-font-initial-load-bug-reproduction

### To Reproduce

**This is EXTREMELY difficult to reliably reproduce!!!**

Deploy the reproduction to Vercel. Open an incognito window and type the URL of your deployment. Notice that the heading font (the thing that says "Next Font Bug") never flips over from the fallback to the actual font. Refreshing the page will fix the issue and you likely won't see the issue again unless you view your deployment on an entirely different device.

Here is an example deployment of the issue: font-bug.vercel.app

**Comment by agusterodin** [comment]
Video reproduction. Notice that at :20 the font isn't correct (stuck on fallback) when I visit dev.divtechnologies.com. Refreshing fixes it. I then open a new inconito window and the issue occurs again.

https://www.youtube.com/watch?v=D3gFrbyJeq8.

Oddly enough, notice how the font fixes itself when I resize the browser to a breakpoint where the font size changes? This almost suggests that it is a Chromium bug of some kind.

I still have yet to see this issue occur in Safari or Firefox no matter how hard I try.

**Comment by hanneslund** [comment]
The [`font-display`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) is `optional` by default, sometimes on first load the font won't be downloaded in time before its [block period](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#the_font_display_timeline) is over. So the generated fallback font is shown instead. When refreshing the page the font will be in cache which explains why the fallback isn't show again.

This behaviour is expected when using `font-display: optional`, but is the best option for reducing [CLS](https://web.dev/cls/). If you'd rather swap in the font you can use `display: 'swap'`.

**Comment by agusterodin** [comment]
Thanks for the quick response!

It may be worth adding a note about this in the docs. I can't imagine that most people would want a coin flip to essentially determine which font is shown on the screen.

Too much information about font-display modes would be excessive, especially since you provide link to MDN page. That being said, a little heads up about how "optional" behaves (and why it may not be what you desire) would likely go a long way and save a lot of people a lot of time and confusion.

**Comment by hanneslund** [comment]
Thanks for the feedback!
