### ISSUE TITLE
On demand revalidation - revalidate API call - Failed to revalidate "/post/1" Invalid response 200

### ISSUE THREAD

**Issue by AlonMiz** [vercel/next.js#42054]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

was able to reproduce both in next 12 and 13
```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: 1.22.18
      pnpm: 7.11.0
    Relevant packages:
      next: 12.3.1
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

any

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

trying to use "on-demand revalidation" but seeing an error on the revalidation part
I'm revalidating an API route that have a cache and supposed to be saved in the cdn
```
res.setHeader('Cache-Control', `public, s-maxage=${fresh}, stale-while-revalidate=${stale}`);
```

the error:
```
revalidate failed on /api/output/6336edd4b33f120a3901e702 Error: Failed to revalidate /api/output/6336edd4b33f120a3901e702: Invalid response 200
    at revalidate (/next/dist/server/api-utils/node.js:295:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(api)/./src/server/pricing.router.ts:100:17)
    at async resolveMiddleware (/node_modules/@trpc/server/dist/router-dabfef7f.mjs:190:30)
    at async callRecursive (/node_modules/@trpc/server/dist/router-dabfef7f.mjs:226:32)
    at async next (/node_modules/@trpc/server/dist/router-dabfef7f.mjs:234:32)
    at async callRecursive (/node_modules/@trpc/server/dist/router-dabfef7f.mjs:226:32)
    at async resolve (/node_modules/@trpc/server/dist/router-dabfef7f.mjs:254:24)
    at async /node_modules/@trpc/server/dist/resolveHTTPResponse-8b09a709.mjs:375:32
    at async Promise.all (index 0)
```

my guess is that it is not possible to revalidate an API call, but that seems to be a valid expectation

### Expected Behavior

revalidate an API call should be possible

### Link to reproduction

https://github.com/AlonMiz/next-js-reproduce

### To Reproduce

1. go to https://next-js-reproduce.vercel.app/
2. click revalidate
3. error returned

**Comment by balazsorban44** [comment]
On-demand Revalidation is used to revalidate pages, not API endpoints.

Please have a look at the documentation to learn more: https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#on-demand-revalidation

**Comment by AlonMiz** [comment]
Thanks for the quick answer @balazsorban44 
can we move this from Bug to a Feature request?
I think that this behavior does make sense as "on-demand revalidation".
as far as I can see, I can set cache headers to an API call as I can for pages, allowing incremental builds and on-demand revalidation.
if vercel/next allows me to cache responses in CDN, this statement does work for API calls.
`res.setHeader('Cache-Control', `public, s-maxage=60, stale-while-revalidate=600`);` 
does work for me on vercel's CDN. 
allowing to revalidate would be GREAT, allowing me to invalidate the cached response in the CDN.
