### ISSUE TITLE
Next 13 appDir: `next/config` does not behave as expected

### ISSUE THREAD

**Issue by jcoene** [vercel/next.js#42065]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When using the new appDir in Next 13, the `getConfig` method exported by `next/config` does not consistently return the expected values when being called from either Server or Client components.

### Expected Behavior

There are a group of 3 related issues here:

**Issue 1**: Expected behavior: `getConfig` called from within a layout or page server component should return both `publicRuntimeConfig` and `serverRuntimeConfig`

Observed behavior: it returns `undefined`

**Issue 2**: Expected behavior: `getConfig` called from within a client component should return `publicRuntimeConfig` (but not `serverRuntimeConfig`) in both the server (ex. Node) and client (ex. Browser) environments.

Observed behavior: it returns both `publicRuntimeConfig` and `serverRuntimeConfig` when rendered on the server, but returns `undefined` when hydrated on the client. You can see the values flicker briefly in the videos below.

**Issue 3**: Expected behavior: values in `publicRuntimeConfig` and `serverRuntimeConfig` in `next.config.js` should properly reflect the runtime value of `process.env.KEY`.

Observed behavior: the values present at build time are used, ignoring runtime environment.

Example:

```ts
const nextConfig = {
  experimental: {
    appDir: true,
  },
  publicRuntimeConfig: {
    PUBLIC_FOO: process.env.PUBLIC_FOO || "PUBLIC_BAR",
  },
  serverRuntimeConfig: {
    SERVER_FOO: process.env.SERVER_FOO || "SERVER_BAR",
  },
};
```

This seems to work fine in development:

(`PUBLIC_FOO=override1 SERVER_FOO=override2 npm run dev`)

https://user-images.githubusercontent.com/283933/198684226-b17b09b9-904b-4911-af86-efce2fae047c.mov

It no longer works after build:

(`npm run build && PUBLIC_FOO=override1 SERVER_FOO=override2 npm run start`)

https://user-images.githubusercontent.com/283933/198684454-b30b2f5a-2cda-48bb-a881-cf0ff98c3ad7.mov

### Link to reproduction

https://github.com/jcoene/next-config-example

### To Reproduce

Set config values in `next.config.js`:

```js
// next.config.js

const nextConfig = {
  experimental: {
    appDir: true,
  },
  publicRuntimeConfig: {
    PUBLIC_FOO: process.env.PUBLIC_FOO || "PUBLIC_BAR",
  },
  serverRuntimeConfig: {
    SERVER_FOO: process.env.SERVER_FOO || "SERVER_BAR",
  },
};
```

Call `getConfig` from a server component, ex:

```tsx
// page.tsx

import getConfig from "next/config";

export default async function HomePage() {
  const config = getConfig();
  return (
    <div>{JSON.stringify(config)}</div>
  )
}
```

Call `getConfig` from a client component, ex:

```tsx
// widget.tsx

'use client';

import getConfig from "next/config";

export default function ClientWidget() {
  const config = getConfig();
  return (
    <div>{JSON.stringify(config)}</div>
  )
}
```

**Comment by timneutkens** [comment]
Going to close this issue as `next/config` / runtimeConfig is not implemented yet as per https://beta.nextjs.org/docs/app-directory-roadmap#planned-features.
