### ISSUE TITLE
v13 - `app/loading.js` doesn't work properly 

### ISSUE THREAD

**Issue by yishayhaz** [vercel/next.js#42063]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

chrome 106

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

When `app/loading.js` exists
and this is the structre,
the website will show `loading.js` for 2 seconds and then show `page.js` (as expected)

And in the network tab, I can see that get `loading.js`, and it returns it after(!) the 2 seconds
but if I delete `loading.js`, I receive `page.js` after the same 2 seconds of waiting.

this doesn't make sense to me

## With `loading.js`
<img width="1440" alt="Screen Shot 2022-10-28 at 17 27 43" src="https://user-images.githubusercontent.com/50710472/198644901-1b18668c-2e0c-4b88-9a51-bd2a00ef78fd.png">

<img width="1440" alt="Screen Shot 2022-10-28 at 17 41 20" src="https://user-images.githubusercontent.com/50710472/198652984-092705ea-69b5-472b-8f0f-f43df56c74cc.png">

## Without `loading.js`
<img width="1440" alt="Screen Shot 2022-10-28 at 17 42 45" src="https://user-images.githubusercontent.com/50710472/198653787-a1aecf96-ca5a-4584-81ab-c7c3fa62b479.png">

<img width="1440" alt="Screen Shot 2022-10-28 at 17 43 08" src="https://user-images.githubusercontent.com/50710472/198654008-dfd60dbf-933d-4776-ab30-31a5975e6435.png">

### Expected Behavior

- either return `loading.js` immediately
- if you already waited 2 seconds, well now we can return `page.js`

### Link to reproduction

i-have-no-link

### To Reproduce

# `app/page.js`

```js
async function getData() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve("Superman");
    }, 2000);
  });
}

export default async function Page() {
  const name = await getData();

  return name;
}
```

# `app/loading.js`

```js
export default function Loading() {
  return "Loading...";
}
```

# `next.config.js`

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  experimental: { appDir: true },
};

module.exports = nextConfig;
```

# `package.json`

```js
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "13.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "eslint": "8.26.0",
    "eslint-config-next": "13.0.0"
  }
}
```

**Comment by timneutkens** [comment]
> I was wondering if this would be a problem with SEO, but I guess because the window itself is in loading state, the crawling bots will "wait".

Try to `curl` so that you can see the html response when the client doesn't support streaming, it'll hold the full html 👍
