### ISSUE TITLE
Forward `ref` on `Image` component

### ISSUE THREAD

**Issue by pc-erin** [vercel/next.js#42089]
### Describe the feature you'd like to request

Framer motion currently doesn't work with the nextjs image component because the component ref is not forwarded to the img element. This is a problem for any libraries or hooks that require a ref to the underlying html element.

There is a discussion of this problem, but no working solution: #37001

### Describe the solution you'd like

Forward refs on the built-in Image component to the underlying img element.

### Describe alternatives you've considered

My current workaround is to surround the image component with a `motion.div` component, but this should not be necessary and won't necessarily work for other use-cases.

**Comment by balazsorban44** [comment]
Since Next.js 13, the Image component has no wrapper element, so you can forward refs directly to the `img` element.

**Comment by download13** [comment]
How do you do that though? Refs passed to the ref prop remain null.
