### ISSUE TITLE
Docs: document Markdoc alongside MDX

### ISSUE THREAD

**Issue by mfix-stripe** [vercel/next.js#42095]
### What is the improvement or update you wish to see?

Would you all be open to me documenting [Markdoc](https://markdoc.dev/) alongside the MDX docs? I understand I am totally biased here, so please don't hesitate to push back—I only want to contribute if you think this would be valuable to include in the docs. 

If you think this is a good idea, I'm happy to create the PR.

### Is there any context that might help us understand?

We (Stripe) open-sourced [Markdoc](https://markdoc.dev/) earlier this year, which includes a [Next.js plugin](https://github.com/markdoc/next.js/) for quickly integrating the 2 together. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/using-mdx

**Comment by leerob** [comment]
We probably need more generic documentation for the general handling of Markdown.

The reason MDX Is featured here is that we have a first-party integration/plugin.
