### ISSUE TITLE
(Beta) Docs: broken link in dynamicParams section of Segment Config Options

### ISSUE THREAD

**Issue by valse** [vercel/next.js#42100]
### What is the improvement or update you wish to see?

[In this page section](https://beta.nextjs.org/docs/api-reference/segment-config#dynamicparams) the link to the `generateStaticParams` section is broken, it point to:
https://beta.nextjs.org/docs/data-fetching.

This is the correct destination:
https://beta.nextjs.org/docs/api-reference/generate-static-params

### Is there any context that might help us understand?

This is the only broken link found at the moment :P

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/segment-config#dynamicparams

**Comment by balazsorban44** [comment]
Thank you, this should soon be fixed!
