### ISSUE TITLE
Update Examples To Support Next.js 13 Experimental App

### ISSUE THREAD

**Issue by slavakurilyak** [vercel/next.js#42128]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.19.1
      Yarn: 1.22.19
      pnpm: 7.14.0
    Relevant packages:
      next: 12.2.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "12.2.5", newest: "13.0.1-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

cms-strapi

### Describe the Bug

When I run `$ pnpm create next-app@latest --experimental-app --example cms-strapi cms-strapi-app` I do not see an `app/` directory

### Expected Behavior

When I run `$ pnpm create next-app@latest --experimental-app --example cms-strapi cms-strapi-app` I am expecting an `app/` directory and `next.config.js` to have the appropriate flag:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
};
```

### To Reproduce

Run `$ pnpm create next-app@latest --experimental-app --example cms-strapi cms-strapi-app`

**Comment by balazsorban44** [comment]
Thanks, examples are going to be updated as the app directory matures. 👍 We currently provide a few examples like, `--experimental-app` and `-e with-turbopack`. More will be converted in the future.
