### ISSUE TITLE
Link with hash doesn't seem to work in next13

### ISSUE THREAD

**Issue by shanejonas** [vercel/next.js#42157]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.17.5
      npm: 6.14.14
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Brave 106.0.5249.119

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

Linking with hash doesn't seem to work in next13

```
<Link href="#footer">
 Link To Footer
</Link>
```

becomes `http://localhost:3000/undefined#footer`

### Expected Behavior

link should be to current page header but instead becomes `http://localhost:3000/undefined#footer`

### Link to reproduction

https://codesandbox.io/p/github/shanejonas/nextjs-link-undefined-bug/draft/great-lake?file=%2Fapp%2Fpage.tsx

### To Reproduce

click/hover over `Link To Footer` to see the link has `undefined` in it

### Screenshot

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/364566/198849912-21933595-afb8-4eeb-b70e-e85a14dda01f.png">

**Comment by 1377sayaba** [comment]
This is also happened for me 
So i downgraded to version 12.3

**Comment by cachho** [comment]
I don't want to hijack your thread, but I found another issues with hashes in links.

`<a href="#CCM.openWidget" title="Cookie consent configuration">` (ccm19 script) doesn't do anything in next13, when I use the same snippet in create-react-app, vue and wordpress. (I didn't want to open a thread for now, in case it might be a 3rd party issue)

**Comment by Cellor425** [comment]
I also have run into this issue, next/link is not appending the hash to the url and instead is routing to the hash address.
`<Link href='#hash'>Link</Link>`
before I upgraded to Next13: `~/currentRoute#hash`
after: `~/#hash`

**Comment by returnvoid** [comment]
Adding shallow={true} worked for me:

<Link href="#someAnchor" shallow={true}>Go there</Link>

**Comment by jayantasamaddar** [comment]
> Adding shallow={true} worked for me:
> Go there

Does not work in `Next 13.2.3`

**Comment by khan-ajamal** [comment]
Anyone figured it out yet. I am stilling facing this issue in `next@13.3.0`

**Comment by drajamal** [comment]
For the time being I am using raw HTML 'a' tag because my use case is just taking the user to the particular section on the same page.

**Comment by drajamal** [comment]
For now, I am using the raw HTML `a` tag because my use case is just taking the user to a particular section on the same page.

**Comment by jmalexan** [comment]
Having this as well, next@13.3.  Using <a> tags at the moment to workaround.

**Comment by SaveliiLukash** [comment]
Next 13.4.2, still issues with `#`

**Comment by fzsf163** [comment]
"next": "13.4.3"
I don't know if this solves the problem , but writting it like this works. May be.

`<Link href='/#sectionID'><Link/>`

Does anyone know how to get this '#id' part from the url ?
I want to show active section. This is why I need to get this. I am pretty new at this.

**Comment by stephen-spar** [comment]
Sorry if this isn't the right place, but I'm seeing the following issue using `next: 13.4.1` on the app router w/ hashes:

- be on the root route (i.e. `/`)
- click on a `<Link>` with an `href` to a specific section on that page (ex. `<Link href='#contact'>`
  - this correctly jumps down to the element with `id=contact`
- scroll somewhere else on the page & click on a `Link` with `href='/'`
- the page automatically scrolls down to the element with `id=contact`
- if you navigate to a different page and then navigate back to the root route using a `Link` with `href='/'` (i.e. _without_ the `#contact`) without refreshing in between, it will _also_ automatically scroll down to the element with `id='contact'`

guessing this is some sort of uncleared state issue? My workaround currently is to add an id to the top element of my root route and have links go to `href='/#top-element'` so the scroll position isn't disrupted.

**Comment by Afrozefathima** [comment]
Like <Link href='/link'> is not working in next js 13.4.2

**Comment by fzsf163** [comment]
> For me link with # works but general link not navigating

some code reference would help everyone to understand your problem better.
If you are meaning  this type of link- 

`<Link href="/about"></Link>` 

 which  takes you to **about** page. Then you need to put **about** folder inside **app** directory.
 
 file structure should be like this
```

├───app
│   ├───about
│   ├───blog

```

 the "/" indicates **app** route or folder then **about**  directs to your **about** folder and page.js/tsx/jsx renders **about** page. You can switch **/about** with **/blog** to go to **blog** page.
