### ISSUE TITLE
Docs: Migrate locales from v12 to v13

### ISSUE THREAD

**Issue by AlexandrosGounis** [vercel/next.js#42174]
### What is the improvement or update you wish to see?

In `v12`, localisation is supported out of the box, `locales` are handled through `useRouter()`:

```tsx
const { locale } = useRouter()
```

Now that `locale` and `defaultLocale` have been removed, how can we migrate this part?
I understand that the `app` directory can receive `/foo/[locale]/page.tsx`, and use the locale as such. If `[locale]` is missing, how can we redirect to a default locale? Should we remove the i18n config from `next.config.js`?

Internationalisation is one of the most useful features of `Next.JS`. In fact, it is the reason why we considered migrating our vanilla react projects to Next.JS. Please let us know what the best approach to deal with this part is, ideally add some docs so that other people know what to expect. Thank you. 

### Is there any context that might help us understand?

Following the current docs:
```
The locale, locales, defaultLocales, domainLocales values have been removed because built-in 
i18n Next.js features are no longer necessary in the app directory. We will document a 
comprehensive example of how to achieve i18n using nested routing and generateStaticParams
in the coming weeks.
```

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/upgrade-guide#step-4-migrating-routing-hooks

**Comment by balazsorban44** [comment]
Hi, as [described in the App Directory Roadmap#Not planned features](https://beta.nextjs.org/docs/app-directory-roadmap#not-planned-features), the i18n configuration is not being ported as-is, but we will be providing better documentation for the `app/` dir.

However, if you use any of the i18n-related configurations right now, currently you can keep using `pages/`, which we will keep maintaining.

> We will be providing more guidance on solutions for internationalized routing inside app. With the addition of [generateStaticParams](https://beta.nextjs.org/docs/api-reference/generate-static-params), which can be used inside layouts, this will provide improved flexibility for handling routing when paired with [Middleware](https://nextjs.org/docs/advanced-features/middleware) versus the existing i18n routing features in pages/.

> If you need these features, you can continue to use pages/. We will be continuing to support pages/, including bug fixes and feature additions, for multiple major versions.
