### ISSUE TITLE
turbopack example report error in initial status

### ISSUE THREAD

**Issue by sky-admin** [vercel/next.js#42202]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

with-turbopack

### Describe the Bug

exec `npx create-next-app --example with-turbopack` get a project.
`npm run dev` try run this project then got a error:
Error: React.Children.only expected to receive a single React element child.

![image](https://user-images.githubusercontent.com/6292668/198923030-33ba4ece-678a-48a4-81ed-20299af0d1c9.png)

looks like its cause by this: https://github.com/vercel/next.js/blame/29c5acd33b0754757e31cf724ed9b0ff83065234/examples/with-turbopack/app/page.tsx#L24

the Link component need only one element inside.

if i modify the code to this:
![image](https://user-images.githubusercontent.com/6292668/198923419-768c565a-1de1-4cf1-a849-f1c916896979.png)

issue resolved

### Expected Behavior

show some thing

### To Reproduce

just follow docs: https://turbo.build/pack/docs
init project with `npx create-next-app --example with-turbopack` and run dev.

**Comment by balazsorban44** [comment]
This has been fixed in https://github.com/vercel/next.js/pull/42203
