### ISSUE TITLE
.vscode folder being added

### ISSUE THREAD

**Issue by HaoboZ** [vercel/next.js#42213]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 19.0.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.2
      eslint-config-next: 13.0.1-canary.2
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

.vscode folder and files being added whenever running the server. I'm not using vscode, so this shouldn't apply, is there a reason this needs to be added?

### Expected Behavior

Don't generate a .vscode folder

### Link to reproduction

https://codesandbox.io/s/next-vscode-settings-generation-bug-c9ouvj?file=/package.json

### To Reproduce

[https://github.com/vercel/next.js/pull/42169 removed](https://github.com/vercel/next.js/issues/41966) related issue, the .gitignore was fixed but vscode was not.

**Comment by cereallarceny** [comment]
Bumping this. Super annoying to see my VS Code settings overwritten. Also, when working in a monorepo, this also makes no sense. I've found a few other issues that have been closed to inactivity, but this is absolutely still an issue @balazsorban44 .

**Problems:**
1. It's not remotely necessary.
2. It promotes favoritism in code editors (although I happen to use VSCode, I can imaging this clutters the working environments of other developers unlike myself).
3. It doesn't work in monorepos - hello Turborepo!
4. It overwrites the existing VSCode settings that a developer may have deliberately put.

**Relevant issues:**
- https://github.com/vercel/next.js/issues/41808
- https://github.com/vercel/next.js/issues/41966

**Solution(s):**
I feel like this should be something configurable, with the ability to opt-in or opt-out of this functionality. This could also easily be done as a codemod. I'm happy to attempt a PR on any of the aforementioned solutions if I can get buy-in from the Next team to change the default behavior.

**Comment by hlege** [comment]
in monorepo it is also create to subproject instead of the root folder.

**Comment by HummingMind** [comment]
+1. Using WebStrom. This folder keeps showing up after every build.
Not need for the .vscode folder.

**Comment by kriswuollett** [comment]
Just revert #41710 and similar patches until this is figured out? Assuming developers have a single project at the root of their repo can no longer be done -- especially after the Vercel acquisition of [Turborepo](https://turbo.build/).

Maybe just a `README.md` file for each IDE on how to set it up? That would be helpful especially if things like [server-side sync of settings](https://code.visualstudio.com/docs/editor/settings-sync) is used.

If it really is desired to help with these types configuration changes for us, it would be great if it was done in a `next doctor` subcommand instead that points all the things that should to be changed, with a `--fix` option to apply it for us if desired. Recommend looking at [`Flutter Doctor`](https://docs.flutter.dev/resources/bug-reports#provide-some-flutter-diagnostics) for inspiration.

**Comment by theboxer** [comment]
+1 for not automatically creating `.vscode` folder or at least have an option to disable it. Not using VS Code, so there's not reason why it should get created.

**Comment by cabaret** [comment]
Bumping this again. I'm not using `.vscode` and I don't want the folder in my projects. There's no reason to emit the VS Code config every time the server starts. At least provide the option to disable this, or provide a separate command to generate it.

**Comment by p-chan** [comment]
This is a vexing problem for monorepo users...:thinking_face:
`.vscode/settings.json` outside the root directory is not useful.
They should be able to opt-out of automatic generation.

**Comment by yordis** [comment]
We are not VS Code users, and we have a mono-repo that is not at the root and it lives next to other projects that aren't even NodeSJ

**Comment by vighnesh153** [comment]
I don't use VS code and I hate that `.vscode` is being created automatically. And no, I am not going to add it to gitignore (why should I?). It should be a opt-in feature for VS code users, instead. 

On a side note, why was the decision of creating/updating `.vscode/settings.json` made without even checking if the user is using VS Code? Is Vercel promoting the use of VS code? Is Vercel indirectly demoting other major IDE creators like Jetbrains?

**Comment by theboxer** [comment]
@vighnesh153 Couldn't agree more. This unreasonable push of vscode is just 🤮

How hard it is to create the file on your own if you need it...

**Comment by shuding** [comment]
Hey all, thanks for the feedback! The `.vscode/settings.json` is there to make VSCode use the TypeScript version in your `node_modules` folder (otherwise it will use the built-in one by default), so we can provide some TypeScript related IntelliSense features. This is required by TypeScript.

Let me see how we can improve this!

**Comment by shuding** [comment]
@will-stone That's the default behavior of Jetbrains editors which is what I expect. I wish VS Code can have that as a default too but unfortunately that's not. I've got people asking "why autocompletion isn't working" because they don't know how to set that up, or it isn't very obvious.

**Comment by will-stone** [comment]
Could this be a documented thing then? As writing config files to people's projects doesn't sound like it's winning you fans ☝️
