### ISSUE TITLE
Next 13: unable to change <title> with head.tsx when one is specified in layout.tsx

### ISSUE THREAD

**Issue by johnrackles** [vercel/next.js#42239]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.2
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Firefox 107.0b7

### Describe the Bug

When using the new app directory, I'm unable to set a <title> like it is described here [https://beta.nextjs.org/docs/routing/pages-and-layouts#modifying-head](https://beta.nextjs.org/docs/routing/pages-and-layouts#modifying-head) when there is already one defined in a layout.tsx file.

### Expected Behavior

I'd assume that a <title> tag in a head.tsx file would overwrite the layout <title>

### Link to reproduction

https://github.com/johnrackles/next13-title-tag

### To Reproduce

Remove line 5 in layout.tsx and the title change happens from within head.tsx

**Comment by alcidesbsilvaneto** [comment]
Try to define your title on a variable and then use:

`<title>{titleVariable}</title>`

Mixing variables and text inside <title> was my problem.

**Comment by johnrackles** [comment]
> Try to define your title on a variable and then use:
> 
> `<title>{titleVariable}</title>`
> 
> Mixing variables and text inside <title> was my problem.

That is a different bug I think, even when I only use a variable, it doesn't overwrite the title specified in the layout.

**Comment by chukwumaokere** [comment]
I'm having this problem too. 
I have a RootLayout with some meta tags, no title specified there
Instead I have an app/head.tsx with 
```js
export default function Head () {
    return (
        <>
            <title>Art Site</title>
        </>
    );
}
```

and app/shop/head.tsx
```js
export default function Head () {
    return (
        <>
            <title>Art Site</title>
        </>
    );
}
```
And the title never changes unless i type into the url /shop and hit enter. It loads with the right title then, but not on navigation.

**Comment by iammartincollins** [comment]
I'm having the same/a similar issue. Each of my `page.tsx` files has an accompanying `head.tsx` file. Refresh sets the header correctly but navigating doesn't change it from the original title.

Note I'm using "use client" in my pages as I don't care about SSR for them.

**Comment by nunoplima** [comment]
Updating to the atm latest next version (13.0.6) solved the issue for me.

**Comment by jaapaurelio** [comment]
This is still happening to me on next 13.1.1.
Tried with both approaches, `<title>` inside `layout.tsx` and `head.tsx`, and both have issues.
Sometimes it's shows and sometimes not.

**Comment by pixelpax** [comment]
Hey y'all, if you're using next 13 with app directory, it works differently now and uses a  'special files' approach. 

Instead of providing a <Head> tag in your page JSX, you create a separate file `head.jsx` which will _automatically_ be injected as <head> for the colocated page.tsx and those in any sub directories.

See: https://beta.nextjs.org/docs/api-reference/file-conventions/head

**Comment by karlhorky** [comment]
Looks like `head.js` / `head.tsx` is going away, in favor of new exports called `metadata` / `generateMetadata()`:

- https://github.com/vercel/next.js/discussions/41745#discussioncomment-4818481

**Comment by huozhi** [comment]
Close per above replies for moving to metadata API as the replacement of `head.js`
