### ISSUE TITLE
sass module stylings not applied on client components in nextjs13

### ISSUE THREAD

**Issue by outdoteth** [vercel/next.js#42267]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When I convert my server component to a client component, the styles fail to render.

The following example works:

```
import "MyComponent.module.scss";

export const MyComponent = () => {
   // stuff
}
```

But this example fails to render the styles:

```
"use client";

import "MyComponent.module.scss";

export const MyComponent = () => {
   // stuff
}
```

### Expected Behavior

The styles should be applied on client components 

### Link to reproduction

closed source

### To Reproduce

see above steps^

**Comment by jmikrut** [comment]
@outdoteth this is a duplicate of https://github.com/vercel/next.js/issues/41791.

Doing some testing myself, I've found that the problem is fixed in dev mode, but after building and serving (even having deployed to Vercel) a lot of my styles are still missing.

Seems like there's still some work to be done here?

**Comment by shuding** [comment]
Can you provide a more detailed reproduction, like a temporary repository?

**Comment by oelbaga** [comment]
I had this issue all day and I couldn't figure what was going on but I updated 13.0.0 to 13.0.1 canary and the issue was fixed. I believe 13.01 was released just a few hours ago.

**Comment by outdoteth** [comment]
This works after i bumped the version to 13.0.01.

From the release notes:
> Fix css modules imports in client components: https://github.com/vercel/next.js/pull/42077

**Comment by jmikrut** [comment]
Hey @shuding — thanks for the follow-up. Yes, we are building the new Payload website in public, and it's all open-source.

https://github.com/payloadcms/website

You'll see on https://stage.payloadcms.com that lots of the CSS module stylesheets are missing, but developing locally, they're all there. The site is certainly 100% in progress right now so things are unfinished everywhere but this shows the reproduction steps.

I really appreciate your help here!
