### ISSUE TITLE
Nextjs 13 @import scss file returns ModuleParseError

### ISSUE THREAD

**Issue by miladnikad** [vercel/next.js#42302]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Safari - Chrome

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

I use Next.js v13 with monorepo structure. When I try to import a scss file into another scss file, I get this error:

```
ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "~@shared/styles/variables.module.scss";
```
This is the next.config.js:

```
/** @type {import('next').NextConfig} */
const { dependencies } = require("./package.json");

const transpilePackages = Object.keys(dependencies || []).filter((dependency) =>
  dependency.startsWith("@my-monorepo/")
);

const nextConfig = {
  experimental: {
    appDir: true,
    transpilePackages,
  },
};
module.exports = nextConfig;
```

and This is my project structure:

my-monorepo-folder: 
 ```
 - packages: 
    - apps:
      - nextjs-website // (v13)
    - package-1  
    - package-2
    - shared
      - styles
        - variables.module.scss
```
How can I handle this error?

### Expected Behavior

ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import "~@shared/styles/variables.module.scss";

### Link to reproduction

local

### To Reproduce

local

**Comment by miladnikad** [comment]
> did you install sass?

According to the [docs](https://beta.nextjs.org/docs/styling/sass) I have just installed sass: 
npx lerna add -D sass  --scope=@my-monorepo/website

So I have the below line in the package.json: 
`"sass": "^1.55.0",`

**Comment by twinemarron** [comment]
@miladnikad  Are you using `next dev --turbo` ?
According to the official document below, It seems that scss is not currently support in turbopack.

https://turbo.build/pack/docs/features/css#scss-and-less

> SCSS and LESS
.scss and .less files let you utilize SCSS and LESS - languages which enhance CSS in various ways. These languages don't currently work out-of-the-box with Turbopack.
> 
> These are likely to be available via plugins in the future.
