### ISSUE TITLE
Client Side ```useSelectedLayoutSegment``` not working

### ISSUE THREAD

**Issue by simandebvu** [vercel/next.js#42300]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Distributor ID: Ubuntu On WSL2
  Description:    Ubuntu 22.04.1 LTS
  Release:        22.04
Binaries:
  Binaries:
  Node: 18.12.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant packages:
 next: 13.0.1-canary.4     
 eslint-config-next: 13.0.0
 react: 18.2.0
 react-dom: 18.2.0

### What browser are you using? (if relevant)

Google Chrome Version 106.0.5249.119 (Official Build) (64-bit)

### Describe the Bug

Unhandled Runtime Error
Error: Cannot destructure property 'tree' of '(0 , _react).useContext(...)' as it is undefined.

Call Stack
useSelectedLayoutSegments
webpack-internal:///(sc_server)/./node_modules/next/dist/client/components/navigation.js (111:13)
useSelectedLayoutSegment
webpack-internal:///(sc_server)/./node_modules/next/dist/client/components/navigation.js (115:36)
NavLink
webpack-internal:///(sc_server)/./app/nav-link.tsx (18:92)
attemptResolveElement
webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js (1167:42)
resolveModelToJSON
webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js (1620:53)
Array.toJSON
webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js (1081:40)
stringify
<anonymous>
processModelChunk
webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js (163:36)
retryTask
webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js (1823:50)
performWork
webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/server.browser.js (1856:33)

### Expected Behavior

Correct handling of the hook

### Link to reproduction

https://github.com/simandebvu/nextjs13-client-server-error-useSelectedLayoutSegment

### To Reproduce

Download and start

**Comment by hanneslund** [comment]
Could you try to change `'use-client';` to `'use client';` in `nav-link.tsx`?
