### ISSUE TITLE
Docs: getLayout is called without context

### ISSUE THREAD

**Issue by benjavicente** [vercel/next.js#42363]
### What is the improvement or update you wish to see?

[The documentation (`next@12`) shows that this is the recomended way of implementing per-page-layouts](https://nextjs.org/docs/basic-features/layouts#per-page-layouts):

```jsx
// pages/index.js
export default function Page() {
  return "In page"
}

Page.getLayout = function getLayout(page) {
  return <div style="color: red">{page}</div>
}

// pages/_app.js
export default function App({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => page)
  return getLayout(<Component {...pageProps} />)
}
```

But that example ([and a answer in SO](https://stackoverflow.com/a/69079558)) fails when a context is needed (see #36029). For example, the following code fails with the `useSomeContext must be used within a ContextProvider` error.

```jsx
// lib/contextjs
const SomeContext = createContext(undefined);

export default function ContextProvider(props) {
  return <SomeContext.Provider value={"ready"} {...props} />;
}

export function useSomeContext() {
  const context = useContext(SomeContext);
  if (!context) throw new Error("useSomeContext must be used within a ContextProvider");
  return context;
}

// pages/index.js
import { useSomeContext } from "../lib/context";

export default function Page() {
  return "In page";
}

Page.getLayout = function getLayout(page) {
  const msg = useSomeContext();
  return (
    <div style={{ color: "red" }}>
      {msg} - {page}
    </div>
  );
};

// pages/_app.js
export default function App({ Component, pageProps }) {
  const getLayout = Component.getLayout || ((page) => page);
  return <ContextProvider>{getLayout(<Component {...pageProps} />)}</ContextProvider>;
}
```

The error is caused by `getLayout(<Component {...pageProps} />)` been called before `ContextProvider` (is can be visualized as `Context( getLayout() )`, `getLayout` is evaluated completely first, without the context, and then `Context` with the layout).

### Proposal

A solution to this might be using the `getLayout` as a component and not a function. I can make a PR changing that example to:

```jsx
// pages/_app.js
export default function App({ Component, pageProps }) {
  const Layout = Component.Layout || Fragment;
  return (
    <ContextProvider>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </ContextProvider>
  );
}

// pages/index.js
Page.Layout = ({ children }) => {
  const msg = useSomeContext();
  return (
    <div style={{ color: "red" }}>
      {msg} - {children}
    </div>
  );
};
```

> This solution was also proposed as a workaround in #36029

### Is there any context that might help us understand?

See above

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/layouts#per-page-layouts

**Comment by leerob** [comment]
Layouts are now a built-in feature 😌 

https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts
