### ISSUE TITLE
[Next.js 13][Routing][Pre-fetching] Dynamic route fails to pre-fetch (404)

### ISSUE THREAD

**Issue by Smirow** [vercel/next.js#42364]
I have already made a ticket for this, but i'm giving here some details.

Pre-fetching (with `<Link>` or `router.prefetch()`) dynamic routes like `app/test/[testId]/leaf` (with one segment over the dynamic param) throws a 404 Not Found **on Vercel** (the page exists). **It works fine on `next dev` and `next start` and with other cloud providers.**

You can try it here [https://test-headers-vercel.vercel.app/test](https://test-headers-vercel.vercel.app/test)
In the inspector you can see that pre-fetching `/test/1` works as expected, pre-fetching `/test/1/leaf` throws a 404.

For `/test/1`
<img width="482" alt="Capture d’écran 2022-10-31 à 11 43 34" src="https://user-images.githubusercontent.com/16503412/198990243-dffe4838-04d1-469c-8b93-8fcdbd7e77d4.png">

For `/test/1/leaf`
<img width="482" alt="Capture d’écran 2022-10-31 à 11 43 28" src="https://user-images.githubusercontent.com/16503412/198990250-a4fb3fdb-2de2-48b8-bb9c-75b8e96f6929.png">
(The first cache hit is a MISS, Vercel then caches it)

This forces a hard navigation to `/test/1/leaf` (probably related to [this issue](https://github.com/vercel/next.js/issues/42175)).

**I haven't tried it on Next 12.**

BTW: pre-fetching seems to work in dev, contrary to what is written in the [beta doc](https://beta.nextjs.org/docs/routing/linking-and-navigating)

**Comment by Smirow** [comment]
@timneutkens thanks for the transfer, but to be clear and as mentioned, this behavior is only replicable on Vercel.

**Comment by timneutkens** [comment]
Still falls under our team's work, we'll investigate 👍

**Comment by ijjk** [comment]
Hi, this should be corrected now, please re-deploy your project and give it a try!

**Comment by Smirow** [comment]
Thanks @ijjk ! Working as expected.
