### ISSUE TITLE
Testing middleware with Jest: TypeError: this._headers.getAll is not a function

### ISSUE THREAD

**Issue by firatgh** [vercel/next.js#42374]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**Operating System:**
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
      
**Binaries:**
      Node: 18.9.0
      npm: 8.19.1
      Yarn: 1.22.19
      pnpm: N/A
      
**Relevant packages:**
      next: 13.0.2-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Hello everybody,

I am currently having issues trying to test the `middleware.ts` in my project, and to reproduce it, I've created a small project from `next.js/examples/with-jest` template, and here is the [repo](https://github.com/firatgh/nextjs-with-jest).

![Screenshot 2022-11-02 at 14 51 50](https://user-images.githubusercontent.com/96059813/199522104-3a891a52-9a0c-4b43-8273-851519e71e28.png)

**The middleware:**

```
export function middleware(req: NextRequest) {
    console.log('Hello')
    return NextResponse.next({headers: new Headers()})
}
```

**The test:**

```
describe('Middleware', () => {
  it('middleware', async () => {
    const res = await middleware(new NextRequest('http://localhost/'))

    console.log('res', res)
  })
})

```

**Other findings:**

I've also dug a little bit, and it seems that `node_modules/next/server/web/spec-extension/cookies/response-cookies.ts:36:35` is expected to fail, I just don't know in which circumstances:

![Screenshot_02_11_2022__14_55](https://user-images.githubusercontent.com/96059813/199523372-5c9d03e8-a9dd-4188-9870-c1ba6b1ce189.png)

Other things I've tried:

Changing `jestEnvironment` to `node` didn't yield the expected result. I've done it by adding the following comment in the test:

```
/**
 * @jest-environment node
 */
```

Thanks in advance

### Expected Behavior

I expect to be able to test the middleware.

### Link to reproduction

https://github.com/firatgh/nextjs-with-jest

### To Reproduce

`yarn test`

**Comment by michalstrzelecki** [comment]
Yes, I am unable to test my middleware now.

**Comment by hrasoa** [comment]
I have the same issue, it's related to https://github.com/vercel/next.js/pull/41526 in ```packages/next/server/web/spec-extension/cookies/response-cookies.ts```
```js
const headers = this._headers.getAll('set-cookie')
```
How should we now instantiate a new ```NextResponse``` ?

**Comment by firatgh** [comment]
@michalstrzelecki @hrasoa 
I ended up mocking the .getAll() method before any module I was testing imported `NextResponse`

```
Headers.prototype.getAll = () => []

// or if your are using TS

(Headers.prototype as any).getAll = () => []
```

It's not ideal, but I was kind of forced to do that.

Cheers.

**Comment by hrasoa** [comment]
@balazsorban44 as you introduced that breaking change, what is your recommendation to use ```NextResponse``` outside edge functions ?

**Comment by BolajiAyodeji** [comment]
Same issue for me with Next13 on Netlify.

<img width="367" alt="Screenshot 2022-11-11 at 7 04 33 PM" src="https://user-images.githubusercontent.com/30334776/201401658-4376f739-d246-4a42-af33-71400af4dffa.png">

**Comment by taiwabisabi** [comment]
Same issue for me with nextJS13 on Netlify with my middleware : 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/17015240/201703558-7d8c394d-b57e-48ca-b347-d59e094abe20.png">

**Comment by kristojorg** [comment]
Happening when testing middleware with jest. It was working with previous patch versions of Next 13 and then stopped.

**Comment by mdotwills** [comment]
Hey awesome team, any update on a fix for this? Thanks

**Comment by vincentdnl** [comment]
Having the same problem. Did the @firatgh and the test doesn't throw an error anymore but this is not optimal.

**Comment by jklein131** [comment]
I wrote this workaround for jest using mocks. 
```
jest.mock("next/server", () => ({
  __esModule: true,
  ...jest.requireActual("next/server"),
  NextResponse: {
    // https://github.com/node-fetch/node-fetch/issues/251
    redirect: (t: any, s: number) => {
      const headers = new Headers();
      return {
        status: s,
        ...NextResponse,
        headers: {
          // Location: t.toString(),
          get: (s: string) => {
            if (s === "Location") {
              return t.toString();
            }
          },
        },
        cookies: new ResponseCookies({
          ...headers,
          get: headers.get,
          delete: headers.delete,
          append: headers.append,
          getAll: () => [],
        } as any),
      };
    },
  },
}));
```
