### ISSUE TITLE
@next/font: Warn when `subsets` is set with template literals in next.config.js

### ISSUE THREAD

**Issue by brandongit2** [vercel/next.js#42389]
### Describe the feature you'd like to request

I had a bit of confusion where I was putting the following into my next.config.js:

```js
module.exports = {
	experimental: {
		appDir: true,
		fontLoaders: [
			{
				loader: `@next/font/google`,
				options: {subsets: [`latin`]},
			},
		],
	},
}

```

The font wasn't applying correctly. What I learned is that when you do the same thing but including the subsets in the function call, like so:

```js
const figtree = Figtree({subsets: [`latin`]})
```

The server will warn you in the console:

```
Error:
  x Font loader values must be explicitly written literals.
   ,----
 7 | const figtree = Figtree({subsets: [`latin`]})
   :                                    ^^^^^^^
   `----
```

So I replaced the template literals around `latin` with regular quotes and it worked.

### Describe the solution you'd like

Maybe the same warning should be provided for the next.config.js case.

### Describe alternatives you've considered

N/A

**Comment by hanneslund** [comment]
That error is specific to font function calls. I tried ```[`latin`]``` in `next.config.js` and it worked for me. `next.config.js` doesn't hot reload, maybe you needed to restart the dev server?
