### ISSUE TITLE
Docs: @next/font with pages directory

### ISSUE THREAD

**Issue by anton-g** [vercel/next.js#42385]
### What is the improvement or update you wish to see?

The beta docs for @next/font says (https://beta.nextjs.org/docs/optimizing/fonts):
> This feature works both in the app and pages directories. This page goes through how to use it in app. To learn how to use in pages, please refer to the [stable docs](https://nextjs.org/docs/basic-features/font-optimization).

Following the link to the stable docs should inform you how to use @next/font with the `pages` directory, but all examples are still for the new `app` directory.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/font-optimization

**Comment by delbaoliveira** [comment]
Thank you for the feedback.

Updated stable docs will land soon, in the meantime you can check this PR for reference: https://github.com/vercel/next.js/pull/42266
