### ISSUE TITLE
[Next 13] Enabling app directory breaks VSCode when using Yarn Berry

### ISSUE THREAD

**Issue by cravend** [vercel/next.js#42419]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Sun Oct 16 18:11:19 PDT 2022; root:xnu-8792.60.32.0.1~11/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.10.0
      npm: 8.19.2
      Yarn: 3.2.4
      pnpm: N/A
    Relevant packages:
      next: 13.0.2-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

After installing Next 13 + running `next dev`, the VSCode settings.json are automatically updated. However, this auto-update does not recognize Yarn Berry Zero-Installs, which removes the concept of a `node_modules` folder).

The setting is changed from `"typescript.tsdk": ".yarn/sdks/typescript/lib"` to `"typescript.tsdk": "./node_modules/typescript/lib"`.

### Expected Behavior

The setting should not be changed, or it should only selectively change if zero-installs are not enabled.

### Link to reproduction

https://github.com/cravend/yarn-berry-next-13-reproduction

### To Reproduce

- clone above repo
- run `yarn` to link dependencies
- run `yarn dev`
  - see the statement "info  - VS Code settings.json has been updated for Next.js' automatic app types, this file can be added to .gitignore if desired"
- to revert to old behavior, change the `./.vscode/settings.json` back to `"typescript.tsdk": ".yarn/sdks/typescript/lib"`

**Comment by minhoyooDEV** [comment]
Same here.

**Comment by yeliex** [comment]
it is wired why changed `.vscode` for all projects. I never use vscode and it looks uncomfortable. And the file does not in the root project dir in monorepo. Is it better to do this in boilerplates?

https://github.com/vercel/next.js/pull/41710

@ijjk

**Comment by shyuuuuni** [comment]
I also try to use zero-install, and the same issue occurs.

**Comment by cravend** [comment]
Hi, any updates on this? I'm still unable to use the app dir with my yarn berry project.
