### ISSUE TITLE
Inconsistency between SSR and CSR for resolvedUrl (not encoded vs encoded)

### ISSUE THREAD

**Issue by Will956** [vercel/next.js#42412]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: N/A
      pnpm: 7.5.2
    Relevant packages:
      next: 13.0.2-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 106

### How are you deploying your application? (if relevant)

Docker

### Describe the Bug

There is a strange behavior between Server Side Rendering and Client Side Rendering for the `resolvedUrl` value taken from our getServerSideProps.

Given that following code:
```js
// ./pages/test/[id].tsx
import Link from "next/link";

export async function getServerSideProps(context) {
  console.log("resolvedUrl", context.resolvedUrl);
  return {
    props: { url: context.resolvedUrl },
  };
}

export default function Test({ url }) {
  return (
    <div>
      <p>resolvedUrl: {url}</p>
      <p>
        <Link href="/test/this:is:a:test">Next</Link>
      </p>
    </div>
  );
}
```

If we go to `/test/test` and we click on the `Next` link, we land on `/test/this:is:a:test`, and the value for `resolvedUrl` is `/test/this%3Ais%3Aa%3Atest`.
If I reload the page, the value of `resolvedUrl` is `/test/this:is:a:test`.

Is there any reason for one to be encoded and the other not?

Thanks a lot 🙏 

### Expected Behavior

I guess the value of `resolvedUrl` should be consistent 🙌 

### Link to reproduction

https://codesandbox.io/s/gracious-proskuriakova-4bxizk

### To Reproduce

- Go to `/test/test`
- Click on `Next`
- Look at the `resolvedUrl` value within the page _(value should be encoded)_
- Reload the page 
- Look at the `resolvedUrl` value within the page _(value should not be encoded)_

**Comment by icyJoseph** [comment]
I only observe this in your sandbox, on a local project, both with stable and canary, it works consistently.

I think somehow `interpolateAs` is getting called in your example, but I can't figure out why. Also for some reason the code in your sandbox looks different than on my local machine.

**Comment by Will956** [comment]
Thanks for having a look 🙌 

Really strange, I made a minimal local reproduction here https://github.com/Will956/nextjs-issue-42412 and I'm able to reproduce the inconsistency if you want to test. 

But maybe I miss something, are you able to provide your local project in order to compare?

Thanks again 🙏

**Comment by icyJoseph** [comment]
I reckon I have `appDir` activated, let me give it a go without the `appDir`

**Comment by icyJoseph** [comment]
Ah, I had a middleware file with:

```js
export function middleware(request) {
  return NextResponse.next();
}
```

Odd...

**Comment by Will956** [comment]
Yes indeed, can see the encoded version via the SPA transition: 
![Capture d’écran 2022-11-04 à 14 49 24](https://user-images.githubusercontent.com/13664270/199990790-92c9e2ff-0454-427e-a37b-e912dd6cfd3d.png)

![Capture d’écran 2022-11-04 à 14 49 17](https://user-images.githubusercontent.com/13664270/199990787-50daa491-ead9-402b-9392-81f80a19b508.png)

I guess this should be fixed somehow to keep consistency. On our side, we're decoding it (since we compare that value with something else) now.

Thanks 🙏
