### ISSUE TITLE
Search params are removed in production unless `useSearchParams` is called

### ISSUE THREAD

**Issue by LukasMurdock** [vercel/next.js#42438]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.2-canary.2
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

next start, Vercel

### Describe the Bug

Search params seem to be removed in production _unless_ `useSearchParams` hook is called somewhere. `next dev` seems to work fine. Bug occurs with `next build` and `next start`.

### Expected Behavior

Expected search params to not be removed in production unless `useSearchParams` hook is called.

### Link to reproduction

https://github.com/LukasMurdock/next-13-test

### To Reproduce

Create a page in Next 13 `/app` that does _not_ use `useSearchParams` hook anywhere and run `next build` and `next start` and attempt to load the page with any search parameters. Search parameters should be removed.

If you add a call `useSearchParams()` then search params are not removed.

I have a reproduction here: 
- (Server component, params removed) https://next-13-test-kohl.vercel.app/server?test=
- (Client component, params removed) https://next-13-test-kohl.vercel.app/client/nowork/?test=
- (Client component calls `useSearchParams()`, params retained) https://next-13-test-kohl.vercel.app/client/work/?test=

**Comment by leerob** [comment]
Confirmed this seems like a bug - thank you!

**Comment by timneutkens** [comment]
This is fixed in #42744, thanks for the report!
