### ISSUE TITLE
SVG images imported in server components aren't included in bundle

### ISSUE THREAD

**Issue by travigd** [vercel/next.js#42443]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.2-canary.2
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

When an SVG image is statically imported in a server component, it's not included in the resulting bundle (the HTTP request 404's when loaded in the browser). Things **do work** for non-SVG images and for SVGs imported in client components.

### Expected Behavior

SVGs should work in RSCs.

### Link to reproduction

https://github.com/travigd/nextjs13-image-rsc-import-repro

### To Reproduce

See repo.

<img width="699" alt="Screen Shot 2022-11-03 at 1 39 10 PM" src="https://user-images.githubusercontent.com/773453/199829341-10dda0ed-680e-4038-a041-2229ac0a23ee.png">

**Comment by mlabrum** [comment]
I can also confirm this happening, just hit this on my own project.
