### ISSUE TITLE
[Feature Request] Enable dynamic fetch of @next/font/google based on user input.

### ISSUE THREAD

**Issue by dohomi** [vercel/next.js#42478]
### Describe the feature you'd like to request

I have a CMS where I enable user to select any google font based on the name. Now I'd love to use @next/font/google but these are not working with dynamic font names:
```
const fontName = 'Inter'
const Inter = require('@next/font/google')[fontName]
const InterCss = Inter()
```

### Describe the solution you'd like

It would be great if fonts could be chosen based on dynamic name

### Describe alternatives you've considered

Running my own network fetch via 
```
import { getFontDefinitionFromNetwork } from 'next/dist/server/font-utils'
```

**Comment by hanneslund** [comment]
Hi and thanks for the suggestion. Since `@next/font` only runs during build and has no runtime, this is not something that is planned.
