### ISSUE TITLE
generateStaticParams() missing fallback

### ISSUE THREAD

**Issue by SergeySypalo** [vercel/next.js#42503]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.18.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107

### How are you deploying your application? (if relevant)

npm run dev

### Describe the Bug

Getting the error: TypeError: result is not iterable
with this code
```
export async function generateStaticParams() {
	const paths = [1,2,3,4].map((pagenum) => ({
		page: pagenum.toString()
	}))
	return { paths, fallback: false }
}
```
As I wanted to basically allow only urls that are know to be built at build time, all others - return 404.
I didn't find this in the newest documentation: https://beta.nextjs.org/docs/api-reference/generate-static-params
But it's present in older one: https://nextjs.org/docs/api-reference/data-fetching/get-static-paths

### Expected Behavior

Once I replaced return with just:
`	return paths`
It started to work, I mean page loaded, but I can open non-existing pages with simply just a layout, instead of getting 404

### Link to reproduction

n/a

### To Reproduce

simply try to add "fallback: false" to generateStaticParams() return

**Comment by leerob** [comment]
Hey! The API has changed. See the migration guide for more details: https://beta.nextjs.org/docs/upgrade-guide#replacing-fallback

**Comment by SergeySypalo** [comment]
Thanks for pointing that out, leerob, fixed, now it works as expected.
I had read the upgrade guide, but probably due to the amount of new information missed that fallback part.
Also, I noticed that in the docs `app/posts/[id]/layout.js` is mentioned. But looking at the example code for dynamic params it looks like a typo.
Should be `app/posts/[id]/page.js` as we are retrieving a single post, while layout should be used for site top menu and a sidebar.

**Comment by leerob** [comment]
@SergeySypalo No worries, it's a lot of stuff to digest – I get it! 

And thanks for the shout, will update that typo right now.
