### ISSUE TITLE
content-type sometimes octet-stream instead of tex/html causing browser to prompt to download the site

### ISSUE THREAD

**Issue by alvarlagerlof** [vercel/next.js#42504]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.15
      pnpm: 7.9.0
    Relevant packages:
      next: 13.0.2-canary.3
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.2-canary.3", newest: "13.0.2".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```
        
        
The version is `^13.0.2-canary.3` in `package.json` but it still complains. 

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

content-type on the html files is sometimes incorrectly octet-stream instead of text/html. This causes the browser to prompt to download the site.

<div style="display: flex; flex-direction: row;">
<img width="356" alt="image" src="https://user-images.githubusercontent.com/14835120/200079807-26c0c6c7-c7d9-413b-911f-5717453a41d0.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/14835120/200080414-84549830-a26f-4092-80c3-1cf34d56a400.png">
</div>

![image](https://user-images.githubusercontent.com/14835120/200080229-28326ded-b4f2-42a6-b303-a1dd6149d909.png)

### Expected Behavior

The site loads every time.

### Link to reproduction

https://github.com/alvarlagerlof/portfolio

### To Reproduce

https://portfolio-git-test-canary-lagerlof.vercel.app (13.0.2-canary.3)

Reload a few times and it will show up either every time for a while or after a few times.

**Comment by gdborton** [comment]
I'm able to repro this w/ devtools open + cache disabled for every reload.

I also see it when following a twitter redirect:
https://t.co/T6Tz17Irbs

**Comment by ijjk** [comment]
Hi, are you still seeing this behavior with `export const revalidate = 60` removed?

**Comment by alvarlagerlof** [comment]
> Hi, are you still seeing this behavior with `export const revalidate = 60` removed?

Looks like that fixes it. https://portfolio-git-remove-revalidate-lagerlof.vercel.app/

Will it still update without it?

**Comment by ijjk** [comment]
No we'll need to investigate this further for the `revalidate` period to work properly, thanks for verifying that!

**Comment by alvarlagerlof** [comment]
> No we'll need to investigate this further for the `revalidate` period to work properly, thanks for verifying that!

So just to confirm, without it, my site is entirely static?

**Comment by ijjk** [comment]
Correct, a patch will be landed for this shortly and made available to canary and then the revalidate can be re-enabled!

**Comment by alvarlagerlof** [comment]
> Correct, a patch will be landed for this shortly and made available to canary and then the revalidate can be re-enabled!

Awesome, thank you!
