### ISSUE TITLE
Adding any script to root layout (or layout or page) causing an error in clean next 13 repo

### ISSUE THREAD

**Issue by madaher-dev** [vercel/next.js#42519]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.13.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.1
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 106.0.5249.119

### How are you deploying your application? (if relevant)

next dev -p 5000

### Describe the Bug

Tried adding google analytics tag script to root layout file as follows:
```
import { Providers } from "./providers";
import localFont from "@next/font/local";
import Script from "next/script";

const Archivo = localFont({
  src: "./fonts/Archivo-Regular.ttf",
  weight: "400",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body style={{ margin: 0, padding: 0 }}>
        <Providers>
          <section
            style={{
              backgroundColor: "red",
              height: "50px",
            }}
            className={Archivo.className}
          >
            The is the App Top Header - Will Apear in all pages
          </section>
          <section>{children}</section>
        </Providers>
      </body>
      <Script
        strategy="lazyOnload"
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
      />

      <Script strategy="lazyOnload">
        {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
        page_path: window.location.pathname,
        });
    `}
      </Script>
    </html>
  );
}
```
but gets the following error as soon as the page gets hydrated
```
Unhandled Runtime Error
ChunkLoadError: Loading chunk amp failed.
(missing: http://localhost:5000/_next/static/chunks/amp.js)
Call Stack
__webpack_require__.f.j
file:///C:/Users/sanit/Desktop/next13/.next/static/chunks/webpack.js (875:29)
<unknown>
/_next/static/chunks/webpack.js (155:40)
Array.reduce
<anonymous>
__webpack_require__.e
file:///C:/Users/sanit/Desktop/next13/.next/static/chunks/webpack.js (154:67)
fn.e
/_next/static/chunks/webpack.js (397:50)
self.__next_chunk_load__
node_modules\next\dist\client\app-index.js (31:33)
preloadModule
node_modules\next\dist\compiled\react-server-dom-webpack\client.js (83:0)
resolveModule
node_modules\next\dist\compiled\react-server-dom-webpack\client.js (650:0)
processFullRow
node_modules\next\dist\compiled\react-server-dom-webpack\client.js (735:0)
processBinaryChunk
node_modules\next\dist\compiled\react-server-dom-webpack\client.js (789:0)
```

also in the console i see
```
amp-dev.js?5ccf:7 Uncaught TypeError: Cannot read properties of null (reading 'textContent')
    at eval (amp-dev.js?5ccf:7:49)
    at ./node_modules/next/dist/client/dev/amp-dev.js (amp.js:106:1)
    at options.factory (webpack.js:722:31)
    at __webpack_require__ (webpack.js:37:33)
    at __webpack_exec__ (amp.js:703:61)
    at amp.js:704:37
    at webpackJsonpCallback (webpack.js:1410:39)
    at amp.js:9:61
```
i noticed that when i run the project with next build and then next start i only get the console warning

### Expected Behavior

The page should load normally and the script called.

### Link to reproduction

https://github.com/madaher-dev/next13.git

### To Reproduce

Follow docs to install clean next 13 project
create app directory and page and root layout
import next/script to root layout
use any script in the root template html

**Comment by balazsorban44** [comment]
I am unable to reproduce this, given the repo you linked to. Everything loads fine.  Have you been able to resolve the issue? Otherwise, this might be OS/Browser-specific. :thinking:

**Comment by madaher-dev** [comment]
> I am unable to reproduce this, given the repo you linked to. Everything loads fine. Have you been able to resolve the issue? Otherwise, this might be OS/Browser-specific. 🤔

Yes i can confirm. I just cloned the repo as is and ran npm i and npm run dev and directly get the error are soon as i open the browser.
I tried it on Edge same thing. I will try it on a different OS when am at the office tomorrow
See screenshot below

**Comment by nevsky118** [comment]
I get the same error when embedding the script in the root layout. Here is the repo https://github.com/nevsky118/my-app
Screenshot with error https://i.imgur.com/nvmUwB1.png

Chrome Version 107.0.5304.88 (Official Build) (64-bit)

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

**Comment by madaher-dev** [comment]
We tried in the office on a Mac and it works fine. seems to me a 64bit issue?
[9:24 PM] Wassim Abou Jamra
 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.9.1
      npm: 8.19.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.1
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.1", newest: "13.0.3-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

**Comment by madaher-dev** [comment]
I just updated to 13.0.3 and the issue is resolved. thank you will close it

**Comment by madaher-dev** [comment]
I tried updating and got same behavior
 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.13.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

**Comment by rafma0** [comment]
I got similar errors trying on my RootLayout

```
<Script id='consolehi'>
  {'console.log(\'hi\')'}
</Script>
```
also if add `strategy='beforeInteractive'` eslint complains about using this strategy outside pages/_document.js

console
```
Uncaught TypeError: Cannot read properties of null (reading 'textContent')
Uncaught ChunkLoadError: Loading chunk amp failed.
Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

info
```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.4.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.0.3-canary.2
  eslint-config-next: 13.0.2
  react: 18.2.0
  react-dom: 18.2.0
```

**Comment by igierard** [comment]
I'm experiencing a similar issue. It doesn't happen when I build from WSL but it does happen when I build from windows (both PowerShell and git bash). So it seems this might be a windows only issue. 

Unfortunately building in WSL from a /mnt/ directory doesn't allow for filesystem update events so no hot reloading or file updates after the next initially loads the file so it isn't really a development option.

**Comment by pogran** [comment]
do this problem is still active?
