### ISSUE TITLE
[...catchall] takes precedence when navigating from /pages to /app

### ISSUE THREAD

**Issue by Winwardo** [vercel/next.js#42532]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Running in Codesandbox, cannot run `next info`

  "dependencies": {
    "next": "13.0.3-canary.0",
    "react": "18.3.0-next-4bd245e9e-20221104",
    "react-dom": "18.3.0-next-4bd245e9e-20221104"
  },

### What browser are you using? (if relevant)

Chrome Version 107.0.5304.88 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When navigating from a page in the legacy /pages directory to the new /app directory, a [...catchall] in /pages will take be resolved instead.

### Expected Behavior

Navigating from /pages to /app should go to the correct page in /app.

### Link to reproduction

https://codesandbox.io/s/catchall-bug-k7x8pi?file=/pages/%5B...catchall%5D.tsx

### To Reproduce

Create a NextJS 13 application that uses both the legacy /pages directory and the new /app directory.
Create links that navigate between them.
Add a top level [...catchall] in the /pages directory.
Deploy to Vercel.
**This bug does not happen in dev.** I have yet to confirm if this happens on all `next build && next start` builds, or if only when deployed to Vercel.

Notice how when navigating between a page originating in /pages towards one in /app, instead the catchall page is hit.
Navigation between /pages to /pages, /app to /app or /app to /pages works as expected.

https://csb-k7x8pi-gweyxi0yg-winwardo.vercel.app/

**Comment by hanneslund** [comment]
This is the same issue as in #42513. As @timneutkens explains here https://github.com/vercel/next.js/issues/42513#issuecomment-1304835777 the expected behaviour is for it to navigate to the catchall route.

https://github.com/vercel/next.js/pull/43188 makes sure it works the same in dev and prod.
