### ISSUE TITLE
Uncaught Error: NEXT_REDIRECT

### ISSUE THREAD

**Issue by thisisclint21** [vercel/next.js#42537]
In `/app/(protected)/dashboard/page.tsx`, below code fails if it hit the direct url of `/dashboard`

```js
import { redirect } from "next/navigation";

if (!response.isSignedIn) {
    redirect('/')
  }
```

```
client.js?234c:691 
        
       Uncaught Error: NEXT_REDIRECT
    at redirect (webpack-internal:///(sc_server)/./node_modules/next/dist/client/components/redirect.js:11:19)
    at dashboard (webpack-internal:///(sc_server)/./app/(protected)/dashboard/page.tsx:44:66)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

_Originally posted by @thisisclint21 in https://github.com/vercel/next.js/discussions/41745#discussioncomment-4065660_

_Originally posted by @schemburkar in https://github.com/vercel/next.js/discussions/41745#discussioncomment-4067062_

**Comment by timneutkens** [comment]
Can you open a new issue following the issue template, I'm unable to reproduce this, it redirects correctly.

**Comment by thisisclint21** [comment]
I will not have time, but I'm not the first to have this issue!

**Comment by schemburkar** [comment]
@timneutkens Please see #42556 for all the required details and repro source code. 






> I will not have time, but I'm not the first to have this issue!

@thisisclint21 No worries, Created the above bug
