### ISSUE TITLE
Docs: illegible notes component color on beta.nextjs.org/learn

### ISSUE THREAD

**Issue by haritssr** [vercel/next.js#42552]
### What is the improvement or update you wish to see?

accessible notes component color

### Is there any context that might help us understand?

i opened the link via [https://beta.nextjs.org/docs/optimizing/images](https://beta.nextjs.org/docs/optimizing/images) which lead to [https://beta.nextjs.org/learn/seo/web-performance](https://beta.nextjs.org/learn/seo/web-performance), which lead to [https://beta.nextjs.org/learn/seo/web-performance/seo-impact](https://beta.nextjs.org/learn/seo/web-performance/seo-impact)
![Screenshot (230)](https://user-images.githubusercontent.com/66904254/200202837-2b4847aa-d078-4f58-99cf-d1679ef0cebf.png)

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/learn/seo/web-performance/seo-impact

**Comment by leerob** [comment]
Oops! You can use the normal site for this, not the beta site. 

https://nextjs.org/learn/seo/web-performance/seo-impact
