### ISSUE TITLE
`@next/font` - updatedCssResponse.replaceAll is not a function

### ISSUE THREAD

**Issue by mipyykko** [vercel/next.js#42566]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #202210211149~1666452039~22.04~1891946 SMP PREEMPT_DYNAMIC Sat O
    Binaries:
      Node: 14.18.2
      npm: 8.19.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When running `next dev`, the error `updatedCssResponse.replaceAll is not a function` is shown and the build fails. The latest canary version of `next/font` replaced a `replace` with `replaceAll`; however, this was only introduced in Node.js v15. Next.js documentation states that it requires at least Node.js v14.6.0. 

### Expected Behavior

There shouldn't be an error and the compilation should succeed.

### Link to reproduction

https://codesandbox.io/s/vigorous-ellis-z5zme6

### To Reproduce

Create a project with `next@canary` and `@next/font@canary` and import a Google font.

**Comment by hanneslund** [comment]
Already fixed in https://github.com/vercel/next.js/pull/42550.

**Comment by ijjk** [comment]
The above patch is now available in `v13.0.3-canary.1` of Next.js, please update and give it a try!
