### ISSUE TITLE
stitches css breaks on app dir (next 13)

### ISSUE THREAD

**Issue by darklight9811** [vercel/next.js#42572]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Mon Nov 07 2022 07:24:00 GMT-0300 (Horário Padrão de Brasília)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

firefox

### Describe the Bug

Using the css utility function from [stitches](https://github.com/stitchesjs/stitches) breaks the app directory (both on server components and client components). Using native styled utility from stitches work, but this is still a bug and in many cases we have to use `css` utility in our projects.

### Expected Behavior

To work as pages directory

### Link to reproduction

https://stackblitz.com/edit/nextjs-naip1g?file=package.json

### To Reproduce

create a [css className utility from stitches](https://stitches.dev/docs/framework-agnostic#use-it), and use it in a component.

**Comment by darklight9811** [comment]
Its because of the .toString function, maybe add a check that transforms the prop into string (if it has the toString function) before actually parsing?

**Comment by balazsorban44** [comment]
As the error says "Error: Functions cannot be passed directly to Client Components because they're not serializable.". You can mark the pages that rely on this with `"use client"`.

**Comment by darklight9811** [comment]
@balazsorban44 did you read my second comment? It's something could be fixed to make this work on server components.

I have to insist because this can end up breaking other packages too and makes sense to add this verification before the data parsing.

**Comment by gabriel-mend** [comment]
@darklight9811 bro, i use you base the exemple and work with me this, but only on the client side. 
https://stackblitz.com/edit/nextjs-ftij4p?file=app/ServerStylesSheet.tsx

But all pages and components you need to use with stitches, you put this flag on top the code ` 'use client'`.  This specify the component or page is run on client side.

**Comment by darklight9811** [comment]
@gabriel-mend but the function its complaining is a conversion to string, actually it's an issue with react server dom. But it doesn't make sense force it into a client component.
