### ISSUE TITLE
NextJS13/AppLayout - While using Next/Link with href, I noticed that the title in the Header did not change when I navigated between the routes.

### ISSUE THREAD

**Issue by violetbee** [vercel/next.js#42573]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.0
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

While using Next/Link with href, I noticed that the title in the Header did not change when I navigated between the routes.

### Expected Behavior

When I switch from the main route to the sub route, the title of the header should also be updated.

### Link to reproduction

https://github.com/violetbee/express-p-ts-rest-frontend

### To Reproduce

![image](https://user-images.githubusercontent.com/61601796/200288497-3d578411-aec4-427c-8a44-3ca5332cd19d.png)
![image](https://user-images.githubusercontent.com/61601796/200288542-2c8044c1-02fc-46a5-ba0f-ed6c8dd5a604.png)
![image](https://user-images.githubusercontent.com/61601796/200288778-a5f8cc23-6102-46fe-91f2-bf87380e6974.png)
![image](https://user-images.githubusercontent.com/61601796/200288712-8cd1032c-fe5e-4d22-badd-e3f9ca1610a6.png)

**Comment by timneutkens** [comment]
This is currently expected as it still has to be implemented. 

> Warning: Currently, the Head export does not re-render on client-side transitions, only on initial render. To work around this for <title>, you can use a client component with useEffect that updates document.title. This will be fixed soon in a future release.

https://beta.nextjs.org/docs/api-reference/file-conventions/head
