### ISSUE TITLE
Migrating next/link to v13 using new-link codemod breaks when <a> had imported component as child

### ISSUE THREAD

**Issue by tony3918** [vercel/next.js#42577]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
Platform: darwin
Arch: x64
Version: Darwin Kernel Version 22.1.0: Sun Oct 9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Binaries:
Node: 16.13.2
npm: 8.1.2
Yarn: 1.22.19
pnpm: N/A
Relevant packages:
next: 13.0.3-canary.0
eslint-config-next: N/A
react: 18.2.0
react-dom: 18.2.0

### Describe the Bug

Assume we had the following code in Next.js v12

```
// Test.js
const Test = () => <div>Test</div>;
export default Test;
```

```
// Page.js
import Test from "./Test.js"
(...)
<Link href="/xyz">
  <a>
    <Test>Hello</Test>
  </a>
</Link>
(...)
```

If we [upgrade to Next.js v13](https://nextjs.org/docs/upgrading#upgrading-from-12-to-13) and upgrade next/link through `npx @next/codemod new-link ./pages`, Page.js becomes as follows:
```
// Page.js
import Test from "./Test.js"
(...)
<Link href="/xyz" legacyBehavior>
  <Test>Hello</Test>
</Link>
(...)
```

The issue is that our link is no longer clickable. The new-link codemod puts "legacyBehavior" in our <Link> but when the child component is not <a>, it seems to break.

### Expected Behavior

After migrating to next@13 and executing the new-link codemod, every <Link> should still work as normal.

### Link to reproduction

https://codesandbox.io/s/beautiful-bush-2hsisr?file=/pages/index.tsx

### To Reproduce

Go to above link and try to click the "Test" link.

**Comment by balazsorban44** [comment]
Hi, I could not reproduce this anymore based on the reproduction. There was no `legacyBehavior` added, so make sure you run the `latest` of `@next/codemod`
