### ISSUE TITLE
Next Link with prefetch={false} disables client side navigation

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#42575]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Mon Nov 07 2022 11:47:42 GMT+0100 (heure normale d’Europe centrale)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 106.0.5249.119 (arm64)

### Describe the Bug

When using `<Link prefetch={false}>` it disables client-side navigation. Even on hovering, there is no preloading, although the documentation says so :
<img width="742" alt="image" src="https://user-images.githubusercontent.com/38298743/200294137-c1d88ab0-d64e-4dd6-9ff9-04f053b672e7.png">

### Expected Behavior

It should not disable client side navigation ?

### Link to reproduction

https://stackblitz.com/edit/nextjs-ef22cg?file=app%2Fnested%2Floading.tsx,app%2Fnested%2Fpage.tsx,app%2Fpage.tsx

### To Reproduce

Go the reproduction link, open the page in a new tab to see it, then go to the home page, click on the link to nested route, you'll see the browser reload.

**Comment by balazsorban44** [comment]
Thanks, created a more minimal reproduction, we will look into this.

https://github.com/balazsorban44/nextjs-42575

**Comment by aprendendofelipe** [comment]
Duplicate of #42175

**Comment by Fredkiss3** [comment]
Go to  https://github.com/vercel/next.js/issues/42175 to follow the issue resolution
