### ISSUE TITLE
Error: NEXT_REDIRECT crashing server in prod

### ISSUE THREAD

**Issue by OMikkel** [vercel/next.js#42587]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 13.0.3-canary.0
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome Version 107.0.5304.88

### How are you deploying your application? (if relevant)

Vercel and localhost in prod environment

### Describe the Bug

Looks similar to #42556, but this issue is based on the server crashing

Whenever I run `yarn build && yarn start` and visit `http://localhost:3000/dashboard` i receive this error:
![](https://i.imgur.com/9fJk8nk.png)

The route `/dashboard` is set to route a user back to `/` if not logged in. This is done in a SC via the `redirect()` function.
This error crashes the server and I have to restart it, on a vercel deployment I just get a 500 error.

### Expected Behavior

I expect the page to redirect the user to the desired URL without the server crashing. 

### Link to reproduction

https://github.com/OMikkel/next_redirect_repro

### To Reproduce

1. Clone git repo above
2. Run yarn install
3. Run yarn build
4. Run yarn start
5. Go to /dashboard
6. Restart the app
7. Try again

**Comment by timneutkens** [comment]
@adrian-goe can you create a separate issue with a reproduction, thanks!

**Comment by manuthecoder** [comment]
I am experiencing the same issue as well!

**Comment by jomarl** [comment]
We are also experiencing issues with redirects (getServersideProps) after upgradring. In 13.0.0 the client performed a request to a unknown chunk after loading a page with a redirect in getServerSideProps - and in 13.0.3 this request disapeared but we are still getting an error logged that the route was not found when the redirect target is loaded. Everthing works as expected but it's annoying to constantly get an error from route loader. Will try and recreate the issue in a barebones project as we have some additional stuff around the router and a custom server to support prettified and localized urls in our application. Might be out setup.
