### ISSUE TITLE
@next/font/google not correctly rendering on initial load with static generation

### ISSUE THREAD

**Issue by e3b0c442** [vercel/next.js#42581]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Dev environment:

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

Build environment:

    Operating System:
      Platform: linux
      Arch: x64
      Version: #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Seen in Brave Version 1.45.113 Chromium: 107.0.5304.62 (Official Build) (arm64), Chrome Version 107.0.5304.87 (Official Build) (arm64), and Safari  16.1 (18614.2.9.1.12)

### How are you deploying your application? (if relevant)

next export

### Describe the Bug

When adding a Google font globally as described in the documentation, where that font is referenced in global stylesheets, the font is not rendered on the first page load unless already locally cached, and is not correctly rendered until another re-render is forced (e.g. by resizing the window and hitting a breakpoint.

If I switch back to adding a <link> tag to the header to load the font from Google, the page renders correctly from first load.

This is reliably reproducible in the Chromium-based browser; it only occurs intermittently in Safari. I was not able to reproduce in Firefox. It also occurs using the dev server.

Note: the above `next info` does not describe the build environment, which is a Linux GitHub actions runner.

### Expected Behavior

The correct fonts are rendered from initial page load across all browsers

### Link to reproduction

https://github.com/omahasymphonicchorus/website-next/blob/main/pages/_app.js

### To Reproduce

* Load the page at https://next.omahasymphonicchorus.org in an affected browser 
* Note that the initial loaded font is the default sans-serif font
* Resize the page and note the correct font is rendered when a breakpoint is hit
* Hard reload the page to bypass the cache and note the default sans-serif font is again rendered on initial load

Source: https://github.com/omahasymphonicchorus/website-next/blob/main/pages/_app.js
GitHub workflow including build/export step: https://github.com/omahasymphonicchorus/website-next/blob/main/.github/workflows/nextjs.yml

I will try to create a minimal reproduction if I have time, but the above is reliably reproducible.

**Comment by hanneslund** [comment]
I think this solves your issue https://github.com/vercel/next.js/issues/41916#issuecomment-1292786022.
```tsx
const montserrat = Montserrat({ subsets: ["latin"] });
```
If you want do swap in Montserrat, you can use [`font-display: swap`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display)
```tsx
const montserrat = Montserrat({ subsets: ["latin"], display: "swap" });
```
