### ISSUE TITLE
@next/next/google-font-display ESLint: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by adjsky** [vercel/next.js#42604]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sat Oct 29 14:21:50 UTC 2022
Binaries:
      Node: 19.0.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.14.1
Relevant packages:
      next: 13.0.3-canary.0
      eslint-config-next: 13.0.3-canary.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When running `next build` the following error is logged: 

`info  - Linting and checking validity of types ...error - ESLint: Cannot read properties of undefined (reading 'value') Occurred while linting /home/adjsky/Programming/stuff/evil-cards/apps/client/src/pages/_document.tsx:8 Rule: "@next/next/google-font-display"`

the line that fails check:

```jsx
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
```

when specifying crossOrigin="anonymous" check doesn't fail

### Expected Behavior

check doesn't fail

### Link to reproduction

https://github.com/adjsky/next-eslint-google-font-display

### To Reproduce

1. clone reproduction repo
2. install deps
3. run `next build`

**Comment by mrkldshv** [comment]
I'd like to take this one!
