### ISSUE TITLE
Hooks not working in client component

### ISSUE THREAD

**Issue by danybeltran** [vercel/next.js#42610]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 19.0.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.88

### Describe the Bug

I am using the experimental `appDir` in my Next app (not using the `pages` directory), and I have this page inside `app/page.tsx`

```tsx
'use client'
import { useState } from 'react'

export default function Page() {
  const [num, setNum] = useState(0)

  return (
    <div>
      <h2>State: {num}</h2>
      <button onClick={() => setNum((c) => c + 1)}>++</button>
    </div>
  )
}
```

And in `app/layout.tsx`:

```tsx
'use client'
import 'styles/globals.css'

export default function RootLayout({ children }) {
  return <div className='p-16'>{children}</div>
}
```

However, i am getting these errors in the browser console:

![image](https://user-images.githubusercontent.com/30043027/200462650-22030e5a-1dd3-458b-a24c-59d4cccf5d8d.png)

The page renders but doesn't become interactive after hydration, so hooks are not working client side, but code that is not inside a `useEffect` still runs server-side

### Expected Behavior

A page that becomes interactive after load

### Link to reproduction

https://github.com/danybeltran/next13-etc-1

### To Reproduce

Create a client page that uses hooks like `useState` or `useEffect`

**Comment by balazsorban44** [comment]
Hi, as per the docs, you are missing `html` and `body` in your root layout:

https://beta.nextjs.org/docs/routing/pages-and-layouts#root-layout-required
