### ISSUE TITLE
Docs: Where does react cache come from?

### ISSUE THREAD

**Issue by marcospassos** [vercel/next.js#42684]
### What is the improvement or update you wish to see?

The docs mention using a `cache` function from the `react` package:
![image](https://user-images.githubusercontent.com/943036/200842215-0ba9c885-5170-41fe-a29d-1b2020af3da5.png)

In which version was it introduced? I can't find any resource about this function.

### Is there any context that might help us understand?

Next 13

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/data-fetching/caching#preload-pattern-with-cache

**Comment by marcospassos** [comment]
Ok, it's like it's not currently supported by react, but added through module augmentation by next.

**Comment by joaopaulomoraes** [comment]
Anyway this is not clear in the doc 🤔

**Comment by leerob** [comment]
It's an experimental feature still: https://github.com/facebook/react/pull/25506

**Comment by joaopaulomoraes** [comment]
Thanks for the reference! ⚛️
