### ISSUE TITLE
[appDir] middleware is not executed or packed when used with appDir

### ISSUE THREAD

**Issue by promer94** [vercel/next.js#42686]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.23.0-20220130.1630
      pnpm: 7.14.0
    Relevant packages:
      next: 13.0.3-canary.2
      eslint-config-next: 12.2.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

middleware is not executed or packed when used with app dir

### Expected Behavior

After enable appDIr, middleware should still work.
```js
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    appDir: true,
  },
}
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/promer94/next-middleware-app

### To Reproduce

* start app
```
pnpm dev
```
<img width="1657" alt="Screenshot 2022-11-09 at 22 11 55" src="https://user-images.githubusercontent.com/15878786/200852686-29ee9144-3945-4ca1-a726-4394662153d9.png">

The `Set-Cookie` header is missing from reponse header and the `console.log` did not execute

**Comment by AdhamMoussa** [comment]
I have the same issue

**Comment by deviantpixel** [comment]
I can confirm this issue as well. It is a bit difficult with new vs legacy documentation. I have tried the following based on various documentation sources:

* Added `allowMiddlewareResponseBody: true` to the `experimental` next.config.js config file
* Tried moving the `middleware.ts` file outside the `app` directory
* Tried renaming the file to `middleware.js` just to ensure it's not a TS issue

All of these still result in the middleware function not being utilized. I plan to switch to not use the `appDir` option for now. Let me know if I can help provide additional information.

**Comment by matthewbean** [comment]
Same here, there is a workaround that I found to work though. Create a pages directory with an empty “.gitkeep” file in it. Middleware started working after that.
