### ISSUE TITLE
Query params getting stripped from index route (Next 13 - App dir)

### ISSUE THREAD

**Issue by ben-greenwood** [vercel/next.js#42697]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.4.0
  npm: 8.12.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.0.2
  eslint-config-next: 13.0.2
  react: 18.2.0
  react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When navigating to my website (example -> https://boilerplate-sandy.vercel.app/?utm_source=test) the url params are stripped from the url. This only happens on the root page and not on any nested routes.

I need the `utm_source` for campaign tracking, so would really appreciate some help!

### Expected Behavior

I'd expect the url params to stay in the url when visiting the page. Note that this is the behaviour on Next 12 apps.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

npx create-next-app@latest --experimental-app

### To Reproduce

This behaviour can be replicated by building a new Next 13 app with `npx create-next-app@latest --experimental-app`

**Comment by ceIia** [comment]
currently facing the exact same issue.

**Comment by timneutkens** [comment]
Thanks for the report! Opened a PR here: https://github.com/vercel/next.js/pull/42744

**Comment by ceIia** [comment]
thanks @timneutkens!

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.0.3`, please update and give it a try!
