### ISSUE TITLE
Too many open files when creating from a template

### ISSUE THREAD

**Issue by nagayev** [vercel/next.js#42703]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

npx --no-install next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Debian 5.10.120-1 (2022-06-09)
    Binaries:
      Node: 18.10.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Disable eslint with create-next-app doesn't work: user can't run the server.

### Expected Behavior

Working app.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

None

### To Reproduce

```npx create-next-app project --js```
Select No (question about using eslint).
```
cd project
npm run dev
```
See many errors like
Watchpack Error (watcher): Error: EMFILE: too many open files, watch '/home/marat/Documents/Code/sandbox/project/node_modules/next/dist/build/webpack/loaders/next-style-loader/runtime'

**Comment by balazsorban44** [comment]
Hi, we recently fixed a likely related issue via https://github.com/vercel/next.js/pull/45760

Could you try `npx create-next-app@canary --typescript` to see if it is fixed? :pray:

**Comment by ijjk** [comment]
Closing as this is fixed on canary per-above
