### ISSUE TITLE
Head from next/head not working in NextJS 13 /app dir

### ISSUE THREAD

**Issue by milanbgd011** [vercel/next.js#42708]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

~/Desktop/next13headbug on  main! ⌚ 0:12:10
$ npm run info

> next13headbug@0.1.0 info
> next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.2", newest: "13.0.3-canary.2".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

npm run dev, npm start

### Describe the Bug

Can't use `<Head>..</Head>` or just `<head>...</head>` in /app dir, all tags within it does not show in source HTML at all OR creates build and dev errors.

### Expected Behavior

Just import from next/head, put <Head>...some meta tags</Head> and it should work.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

no link

#### 4. add <Head /> with couple of title,meta,link tags
```javascript
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>....</main>
    </div>
  )
}    
```
#### 5. run `npm run dev` and none of these set title/meta/link tags appear in HTML source of the page and it reports error in browser console + tags defined in `<Head>...</Head>` DO NOT UPDATE headers at all
<img width="1025" alt="Screenshot 2022-11-10 at 00 08 13" src="https://user-images.githubusercontent.com/20988958/200963227-f986af05-15db-45e9-8a47-84b9ca76ce41.png">

#### 6. run `npm run build` and then `npm start` and this error from point 5. will appear again but in minified form
<img width="1027" alt="Screenshot 2022-11-10 at 00 08 45" src="https://user-images.githubusercontent.com/20988958/200963245-bf0a1094-8602-4217-a0a9-d261368744ab.png">

```javascript
export default function Home() {
  return (
    <div className={styles.container}>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main className={styles.main}>....</main>
    </div>
  )
}    
```

#### 7. replace `<Head>` and `</Head>` with `<head>` and `</head>` and now title/meta/link and it will update head tags on page, but it reports a lot of errors in browser console in dev mode
![Screenshot 2022-11-10 at 00 09 32](https://user-images.githubusercontent.com/20988958/200962866-39d5d0fe-7094-4f1f-9e82-58cda9c24957.png)

#### 8. same error in production mode
![Screenshot 2022-11-10 at 00 10 00](https://user-images.githubusercontent.com/20988958/200962935-30a27747-26d7-41b3-ba2c-27186c1765a9.png)

**Comment by HaNdTriX** [comment]
> In the pages directory, the next/head React component is used to manage <head> HTML elements such as title and meta . In the app directory, next/head is replaced with a new [head.js special file](https://beta.nextjs.org/docs/api-reference/file-conventions/head). Learn more about [head.js](https://beta.nextjs.org/docs/api-reference/file-conventions/head)

[more info](https://beta.nextjs.org/docs/upgrade-guide#step-3-migrating-nexthead)

**Comment by milanbgd011** [comment]
Missed that info. 

Thank you very much for clarification.

If nothing else, maybe someone will find this issue and know this is not allowed, because RTFM was not executed. :)

**Comment by MincePie** [comment]
Did you figure out what is required in order to fix this? I have the same problem. I cant find a tutorial showing how to fix this.
