### ISSUE TITLE
SyntaxError at runtime using 'Context in Client Components' example from beta docs

### ISSUE THREAD

**Issue by cmdcjones** [vercel/next.js#42722]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 18.10.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Brave 1.45.118

### Describe the Bug

Running into a SyntaxError at runtime following the 'theme-provider' example of using Context Providers in the docs (https://beta.nextjs.org/docs/rendering/server-and-client-components#using-context-in-client-components). 

The example uses `export default function ThemeProvider({...})`.
The error being thrown is as follows:
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseModel (/home/.../app/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:40:15)
    at resolveModule (/home/.../app/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:645:24)
    at processFullRow (/home/.../app/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:735:9)
    at processBinaryChunk (/home/.../app/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:789:5)
    at progress (/home/.../app/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:842:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**NOTE**: Removing `default` as per the example 'Rendering third-party context providers in Server Components' allows the code to run error free at runtime.

### Expected Behavior

No SyntaxError at runtime and the Context Provider successfully wrapping the children components in `layout.*sx`

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://beta.nextjs.org/docs/rendering/server-and-client-components#using-context-in-client-components

### To Reproduce

![Screenshot_20221109_103059](https://user-images.githubusercontent.com/43971640/200994373-9d3081c3-b0e5-4bd8-956f-cf7b7e9102f8.png)
![Screenshot_20221109_103115](https://user-images.githubusercontent.com/43971640/200994380-4641cf32-5c8d-44e1-8370-05c8bd6138a2.png)

**Comment by balazsorban44** [comment]
Thanks, it has already been reported here: https://beta.nextjs.org/docs/rendering/server-and-client-components#thread-id=94m-K

You can report beta documentation issues directly on the page by adding a comment. :+1:

**Comment by balazsorban44** [comment]
Although, on a second thought we should probably show a more clear error message, so thanks for reporting.

**Comment by cmdcjones** [comment]
Apologies for the repost. Thank you for the quick reply.

**Comment by iSplasher** [comment]
I keep getting this error and I can't figure out why.
Looking at the provided example in OP, what exactly constitutes a syntax error here? `export default function` is valid syntax.

**Comment by sscaff1** [comment]
`import { ThemeProvider } from './theme-provider';`

should be

`import ThemeProvider from './theme-provider';`

You're trying to get a named exported (i.e. `ThemeProvider`) from the theme-provider file, but you're only providing a default export from that file.

**Comment by iSplasher** [comment]
You're right, I missed that, however, like @balazsorban44 said, this needs a clearer error message. I don't think this should be closed yet.

**Comment by samcx** [comment]
This error message has since been made clearer, so closing this stale issue!

![CleanShot 2024-11-13 at 14 25 25@2x](https://github.com/user-attachments/assets/a5cc6de9-513e-4c47-9f4f-9c0fd05c2819)
