### ISSUE TITLE
Can't add configuration for images domain and fonts when using Turbopack

### ISSUE THREAD

**Issue by ningo-agilityio** [vercel/next.js#42737]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.6.0
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.2", newest: "13.0.3-canary.3".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Which example does this report relate to?

That is the sample with Turbopack: npx create-next-app@latest --example with-turbopack

### What browser are you using? (if relevant)

Version 107.0.5304.87

### Describe the Bug

When I added these configuration in `next.config.js` and run `next dev --turbo`

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true, // Recommended for the `pages` directory, default in `app`.
  swcMinify: true,
  experimental: {
    // Required:
    appDir: true,
  },
};

module.exports = nextConfig;
```
Unfortunately, I got the error:
```
Error: You are using configuration and/or tools that are not yet
supported by Next.js v13 with Turbopack:


- Unsupported Next.js configuration option(s) (next.config.js)
  The only configurations options supported are:
    - experimental.serverComponentsExternalPackages
    - experimental.transpilePackages
  To use Turbopack, remove other configuration options.
```

So how can I configure the domain image and font with Turbopack?

### Expected Behavior

We can use the current configuration of Next.js with Turbopack

### To Reproduce

...

**Comment by balazsorban44** [comment]
Thanks, as the error says, these features are currently under development.
