### ISSUE TITLE
If the Link tag is used in layout.tsx when the app directory is enabled, an error occurs if an event occurs during page loading.

### ISSUE THREAD

**Issue by awukomaki** [vercel/next.js#42749]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: arm64
      Version: #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021
    Binaries:
      Node: 19.0.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.3
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.110

### How are you deploying your application? (if relevant)

local(Docker), codesandbox

### Describe the Bug

If the app directory is enabled, writing a Link tag in layout.tsx causes an error when loading the page.
Normal loading does not generate an error, but if there is an event such as click or keyup during page loading, an 'Unhandled Runtime Error' is generated.

### Expected Behavior

No error occurs and the page loads as normal.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://codesandbox.io/p/sandbox/thirsty-andras-6w7y6w?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A6%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8skx9az000nlpgeaw1kc72o%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fnext.config.js%2522%252C%2522%252Fapp%252Flayout.tsx%2522%252C%2522%252Fapp%252Fpage.tsx%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Ftsconfig.json%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clab3roq001gd3b6i1m9xan5t%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### To Reproduce

**1. Install Next.js.**

**2. Create an app directory and rewrite the configuration as follows.**
```
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
    reactStrictMode: true,
    swcMinify: true,
    experimental: {
      appDir: true,
    },
}
module.exports = nextConfig
```
**3. Create the files required to deliver the page.**
**app/layout.tsx**
```
import Link from "next/link";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html>
        <body>
          <Link href="/">sample</Link>
          {children}
        </body>
      </html>
    </>
  );
}
```
**app/page.tsx**
```
export default function Home() {
  return <>
  <h1>Hello, World.</h1>
  </>;
}
```
**4. Start the Next.js**
```
$ npm run dev
```
**5. Request the page in your browser.**
**6. Click and keyup events are triggered during loading.**
**7. An error occurs and the following message is displayed.**
```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
```
*To ensure an error, keep clicking continuously during loading.

**Comment by AdamMikacich** [comment]
Can confirm the behavior also occurs with next Image components. The bug is present in a freshly generated project (`yarn create next-app --experimental-app`) which has next images but no links.

**Comment by firatoezcan** [comment]
Is there any update on this? This is the one thing preventing us from wanting to move to app directory

**Comment by firatoezcan** [comment]
Hey, I just checked this with version 13.2.4 and it doesn't seem to happen anymore. @gnoff  if you would check it again and verify that this doesn't happen anymore this could be closed.

https://codesandbox.io/p/sandbox/thirsty-andras-6w7y6w?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A31%2C%22endLineNumber%22%3A17%2C%22startColumn%22%3A31%2C%22startLineNumber%22%3A17%7D%5D

**Comment by pewallin** [comment]
Looks like it is still happening in 13.2.4 with production builds for us.

**Comment by firatoezcan** [comment]
Hmm, weird. I just tested it on our production page with disabled cache and throttled network and I can't get the error to show up. And we do have `Link`-tags rendered in our `RootLayout`. Are you able to provide a repro?

**Comment by awukomaki** [comment]
An easy way to reproduce this error screen is to click on the screen several times during the reload and continue clicking after the reload is complete.

**Comment by pewallin** [comment]
Just reproduced it with `yarn create next-app --experimental-app` and created a pages page with a Link back to the start page. The hydration error occurs not 100% of the times but it is there (on the "app" start page)

**Comment by timneutkens** [comment]
Theres's been a few fixes to React that affect hydration. Can you check again using 13.3?

**Comment by awukomaki** [comment]
Thanks for telling us.
However, the above problem does not seem to have been resolved in the latest version. (v13.3)

https://codesandbox.io/p/sandbox/thirsty-andras-6w7y6w?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A6%7D%5D

**Comment by timneutkens** [comment]
<img width="747" alt="CleanShot 2023-04-10 at 14 32 05@2x" src="https://user-images.githubusercontent.com/6324199/230902062-46e99799-663a-486f-8a1e-4c9a234e8f6e.png">

Seems you've installed 13.0.3-canary.3 in that sandbox. I've updated it to next@latest (13.3.0 currently). 

Here's a new sandbox on 13.3.0: https://codesandbox.io/p/sandbox/brave-heisenberg-kmh281?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A32%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A32%2C%22startLineNumber%22%3A13%7D%5D

Application url: https://kmh281-37001.csb.app/
