### ISSUE TITLE
*maybe fixed...?* App Directory localhost index exposed in dev, not on Vercel build

### ISSUE THREAD

**Issue by KjellConnelly** [vercel/next.js#42759]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.3
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 106.0.5249.103

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When I run `npm run dev`, and visit `localhost:3000`, my website loads properly.

When I `git push`, and **Vercel** builds my app, and I visit my url: `https://dev-evergreendbt.vercel.app`, I get a _**404** | This page can not be found._

I have to visit `https://dev-evergreendbt.vercel.app/index` to make load my page. Conversely, when I visit `localhost:3000/index`, I get a 404.

### Expected Behavior

I would expect consistent behavior between what runs on *localhost*, and Vercel's deployment.

I suspect this is due to the way I structured my `app` directory. 
- `app/`
    - `layout.tsx` *used to wrap everything with context, auth, etc*
    -  `(index)/` *I want a specific layout for the public side of the page... index, about, contact, etc*
        - `layout.tsx`
        - `page.tsx` *this is the index page that has problems loading*
        - `about/`
            - `page.tsx`
        - `contact/`
            - `page.tsx`
    - `(FullScreen)/`
       - `layout.tsx` *I want a full screen layout for login and register*
       - `login/` *shares layout with whole app, but not index*
            - `page.tsx`
       - `register/` *shares layout with whole app, but not index*
           - `page.tsx`
   - `home/`
       - `layout.tsx` *shares app layout, but has layout for all logged in users`
       - etc...

As you can see, url endpoints should be, which works on localhost:
- `/`
- `/about`
- `/contact`
- `/login`
- `/register`
- `/home`

But on Vercel, my endpoints are instead:
- `/index`
- `/about`
- `/contact`
- `/login`
- `/register`
- `/home`

*note that I have to explicitly visit `/index` on Vercel endpoint, and then the browser clears `/index`, so if I refresh, I hit the 404*

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://codesandbox.io/s/pensive-villani-uznoum?file=/app/layout.tsx

### To Reproduce

Please note that `app` directory requires node 16.8.0, but `codesandbox.io` only goes up to 16.12.0 by setting the node version in `sandbox.config.json` to 16. So you won't be able to run the example from the link, but you can look at how everything is setup and run using your own machine.

1. To reproduce, create a new Next app using experimental app directory: either follow instructions [using the beta.nextjs.org](https://beta.nextjs.org/docs/installation), but just run `npx create-next-app@latest --experimental-app` from terminal.
2. Once in your editor, setup folder structure as shown in [codesandbox example](https://codesandbox.io/s/pensive-villani-uznoum?file=/app/layout.tsx)
3. `npm run dev` to see all works.
4. deploy to vercel and you need to add `/index` to the url to get the index page

## Update 3 hours later

For some reason, it's working on the vercel site the same as it was for the localhost site. I've been coding, so it may have something to do with me updating my `next-auth` code... but it's possible that Vercel changed something. Not quite sure, but I'll leave this post up here for now.

**Comment by matheusbort** [comment]
I'm facing this problem but on my own k8s environment, or even when i run `node server.js` in my standalone build.

The routes in `/app` is returning 404.

When i run `npm run start` is normal, but with `node server.js` the routes in `app dir` returns 404.

**Comment by KjellConnelly** [comment]
Idk... It seems like it's still working a day later. I'm going to close this for now. Seems like Vercel did something on their servers to account for this.
