### ISSUE TITLE
CSS modules not loading after navigation when with experimental appDir

### ISSUE THREAD

**Issue by darthmaim** [vercel/next.js#42764]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Mon Sep 19 19:14:52 UTC 2022
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.3
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.89

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

- Running `next dev`. Opening a page renders everything correctly and includes the css modules of all components.
- **Navigating to another pages doesn't load the css of newly included components.**
- Styles used on the initial page work correctly.

- This only occurs after enabling `experimental.appDir` and creating the `app` directory.
- The pages are still in the `pages` directory and the components in a `components` directory.

This prevents incremental adoption of the app directory for existing applications.

### Expected Behavior

- Styles should load correctly after navigation with enabled `experimental.appDir`.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/darthmaim/next-13-app-styles-repro

### To Reproduce

- Clone the repro repository
- Run `npm run dev`
- Open the page in a browser
- Observe the styles being loaded correctly (green text)
- Click the link to navigate to the second page
- Observe the styles being NOT loaded correctly (no red text)
- Hard Refreshing this page loads the styles (red text appears)

- Disable `experimental.appDir` in `next.config.js` and repeat the reproduction above to see the working example.

**Comment by araujobarret** [comment]
I'm experiencing the same issue but with styled components. Using the 13.0.3-canary6

**Comment by araujobarret** [comment]
Just tested with next@13.0.6-canary.1 and still has the same error, when you navigate between pages, the next page styles are not loaded.
If we access the page directly it loads all styles but with any new interaction that changes the style it won't load, in the example below we see the loading state not being applied and the button losing its current style.

https://user-images.githubusercontent.com/15792853/204207048-63e169aa-0523-4ec7-979e-a8fe1ec0ba4d.mov

**Comment by darthmaim** [comment]
Verified that this still happens with 13.1.1-canary.1

**Comment by fredrikbergqvist** [comment]
Verified that this still happens with 13.1.1
It only seem to happen in dev-mode though

**Comment by darthmaim** [comment]
✅ This seems to have been fixed sometime between 13.1.1 and 13.2.2-canary.0
