### ISSUE TITLE
Next 13 beta RCC fetch with use not working with public directory

### ISSUE THREAD

**Issue by TomasHubelbauer** [vercel/next.js#42761]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Binaries:
  Node: 19.0.0
  npm: 8.19.2
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.0.3-canary.3
  eslint-config-next: 13.0.2
  react: 18.2.0
  react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

next export

### Describe the Bug

I am using Next 13 beta with the app API (no pages routes) and I am hoping to build a component which pulls text from a TXT file in the public directory into its children. Here's the code:

```javascript
'use client';

import Link from 'next/link';
import { use } from 'react';

export default function RCCUseTest() {
  const text = use(fetch('/about.txt').then(response => response.text()));

  return (
    <>
      <header>
        <Link href="">« Home</Link>
      </header>
      {text}
    </>
  );
}
```

Unfortunately I am getting this error:

> Error: Failed to parse URL from /rcc-use-test.txt

![rcc-use-error](https://user-images.githubusercontent.com/6831144/201206249-dc5dedb4-842a-4c92-be03-181763ce01cd.png)

Note that when I switch to the canary build, this route works when clicking on the `Link` on the landing page but not when accessing the route URL directly.

### Expected Behavior

I expect the text to be loaded using the fetch, additionally, I expect `next export` to produce a SSR route which calls the `fetch` on the client to pull in the additional data.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/TomasHubelbauer/next-13-ssg

### To Reproduce

```
npm install
npm run dev
```

After, access http://localhost:300/ and right-click the second route link (the one with RCC and `use` in the name) and open in a new tab. A simple click will work in canary! But direct route access will still throw the issue.

**Comment by shuding** [comment]
Should be same as 42760, explained here:

https://github.com/vercel/next.js/issues/42760#issuecomment-1311312973
