### ISSUE TITLE
Image blur placeholder not taking full width with fill image

### ISSUE THREAD

**Issue by Kerumen** [vercel/next.js#42765]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.12.1
      Yarn: 1.22.19
      pnpm: 7.14.2
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.87

### Describe the Bug

When using the `Image` component (Next.js v13) with `fill` and a `blurDataURL`, the blurred placeholder is not taking the full width of the viewport as the loaded image does.

<table>
<tr>
	<th> Blurred placeholder
	<th> Loaded image
<tr>
	<td> <img width="915" alt="Screenshot 2022-11-10 at 16 11 51" src="https://user-images.githubusercontent.com/5436545/201217445-4b90f92d-e84a-4262-bf60-8ee144f534f3.png">
	<td> <img width="913" alt="Screenshot 2022-11-10 at 16 11 58" src="https://user-images.githubusercontent.com/5436545/201217453-96b24130-6223-459d-821a-73e59dd8993b.png">
</table>

I stumbled across [this PR](https://github.com/vercel/next.js/pull/41573) which fixed some bugs related to the blur placeholder. It seems that adding `preserveAspectRatio="none"` to the generated SVG without width / height would fix the issue but I don't know the implications.
Also, why is it an SVG and not just the `base64` image as it was on Next.js v12?

### Expected Behavior

The blurred SVG should take the full width of the viewport and not display empty spaces around the image. It was working correctly on Next.js v12.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://codesandbox.io/s/goofy-orla-v8kciw

### To Reproduce

Use an `Image` component with `fill` and a `blurDataURL`.

**Comment by styfle** [comment]
> It seems that adding preserveAspectRatio="none" to the generated SVG without width / height would fix the issue

If the `viewBox` attribute isn't set, the `preserveAspectRatio` attribute has no effect [see mdn](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/preserveAspectRatio)

Although its worth trying it out and seeing if it works without causing artifacts like https://github.com/vercel/next.js/issues/40419

> why is it an SVG and not just the base64 image as it was on Next.js v12

SVG blur performs better compared to CSS blur. It also means we don't need JS to remove any CSS once the image loads.

> Link to reproduction

Thanks I was able to reproduce! This is entering the deopt mode here where the width/height of the blurDataURL are not known so it falls back to CSS blur.

https://github.com/vercel/next.js/blob/fe762d329fdf9d6d6e6bf084198ad49f696d42b7/packages/next/shared/lib/image-blur-svg.ts#L26

Another thing we could try is adding new props for `blurWidth` and `blurHeight` to `next/image` that complement the `blurDataURL` prop.

**Comment by jeff-overhaul** [comment]
Adding `preserveAspectRatio='xMidYMid slice'` to the <image> tag in the SVG would fix it

**Comment by styfle** [comment]
Thanks, I created #44317 with a fix! Its difficult to test all the cases here without manually looking at the result so I'll need to make sure it doesn't break anything else.

**Comment by vimtor** [comment]
I upgraded to the new Next.js image and I found this same issue.

https://user-images.githubusercontent.com/36263538/216265397-c852eb09-8d6f-4192-a013-08ca96599e58.mp4
