### ISSUE TITLE
Significant bundle size increase after switching to v13.0.3

### ISSUE THREAD

**Issue by piotr-czerwik** [vercel/next.js#42782]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.14.2
    Relevant packages:
      next: 13.0.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Starting with `13.0.3-canary.0` (and newer releases) the resulting bundles have a significant increase in size. 

For the starter app created using `npx create-next-app@latest nextjs-starter --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"` the build results are as the following:

**v13.0.2**:
```
Route (pages)                              Size     First Load JS
┌ ○ /                                      5.05 kB        77.7 kB
└ ○ /404                                   181 B          72.9 kB
+ First Load JS shared by all              72.7 kB
  ├ chunks/framework-8c5acb0054140387.js   45.4 kB
  ├ chunks/main-85616fa12b5fff02.js        26.3 kB
  ├ chunks/pages/_app-df511a3677d160f6.js  194 B
  └ chunks/webpack-ee7e63bc15b31913.js     815 B

○  (Static)  automatically rendered as static HTML (uses no initial props)
```

**v13.0.3**:
```
Route (pages)                              Size     First Load JS
┌ ○ /                                      5.75 kB        84.6 kB
└ ○ /404                                   212 B            79 kB
+ First Load JS shared by all              78.8 kB
  ├ chunks/framework-0f397528c01bc177.js   45.7 kB
  ├ chunks/main-e71c796c4d7cc2e4.js        31.8 kB
  ├ chunks/pages/_app-ef9da0a6572b3989.js  243 B
  └ chunks/webpack-7a6cea4e6a92562f.js     1.08 kB
```

This gives 8-9% increase in the First Load JS, just for the starter app.
For the apps I am working on, upgrade to v13.0.3 gave even larger numbers (20-25%). 

### Expected Behavior

No increase in bundles size or the reasoning behind it.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/vercel/next-learn/tree/master/basics/learn-starter

### To Reproduce

Checkout the code and run build using `v13.0.2` and `v13.0.3`.

**Comment by will-stone** [comment]
In our testing, we've found it's stopped tree-shaking our (ESM) component library from the client-side bundle.
