### ISSUE TITLE
Dynamically added images result in 404

### ISSUE THREAD

**Issue by hosseinitabar** [vercel/next.js#42781]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Nov 11 2022 14:15:39 GMT+0330 (Iran Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.3-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.3-canary.4", newest: "13.0.3".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

You deploy a next.js website. And there are images in `/public/images` directory.

After deployment, if you manually add a `temp.png` to `/public/images/` directory, and go to `example.com/images/temp.png` you get 404.

### Expected Behavior

Images inside public directory should be served, even if added dynamically.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-goevwq?file=package.json

### To Reproduce

There is not much to reproduce. You should add an image manually and request it.

**Comment by balazsorban44** [comment]
Hi, this is currently expected.

Refer to the [docs](https://nextjs.org/docs/basic-features/static-file-serving):

> Files added at runtime won't be available. We recommend using a third party service like [AWS S3](https://aws.amazon.com/s3/) for persistent file storage.
