### ISSUE TITLE
Fast Refresh with 'use client' causes full-page reload when using generateStaticParams

### ISSUE THREAD

**Issue by schickling** [vercel/next.js#42789]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: 7.14.2
    Relevant packages:
      next: 13.0.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When using Next.js 13 with `use client`, HMR causes full-page reload when data from `import` changes with the following log messages:

![image](https://user-images.githubusercontent.com/1567498/201347875-1723a165-3b2d-4d54-ab9f-91540413ac1e.png)

### Expected Behavior

Should do an incremental HMR execution without full page reload.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/contentlayerdev/next-contentlayer-example/blob/376c129b64a6e23b0163532b656cdbc66c3e47f7

### To Reproduce

- Clone this repo: `https://github.com/contentlayerdev/next-contentlayer-example/blob/376c129b64a6e23b0163532b656cdbc66c3e47f7`
- Run `yarn install; yarn dev`
- Navigate to `/posts-use-client/change-me` and change the content in `posts/change-me.md`

**Comment by samcx** [comment]
@schickling Hi there!

Since this issue is stale and there a quite a few moving parts, I will be closing this issue.

I have not recently seen any Fast Refresh issues with `use client` and `generateStaticParams`, but if this is still occurring, please let us know!
