### ISSUE TITLE
Title does not change while changing routes - Next js 13 appDir

### ISSUE THREAD

**Issue by mjad218** [vercel/next.js#42784]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

``` 

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

Title does not change while navigating between routes. 

Also, Next js 13 moves meta tags inside the body to the head. 

### Expected Behavior

Title should change when the route changes. 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/mjad218/next-js-13-head-bug

### To Reproduce

Clone the repo and run the dev server.

**Comment by balazsorban44** [comment]
Thanks for the report, although this is a known issue currently and a workaround is documented here: https://beta.nextjs.org/docs/routing/pages-and-layouts#modifying-head

> Warning: Currently, the <Head> export does not re-render on client-side transition using `next/link`, only on initial render and reloads. To work around this for <title>, you can use a client component with useEffect that updates `document.title`. We plan to fix this in a future release.

**Comment by mjad218** [comment]
Thank you,
