### ISSUE TITLE
yarn dev in Next 13 generates 0 byte pages using appDir

### ISSUE THREAD

**Issue by volnei** [vercel/next.js#42792]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.0.1
      npm: 8.19.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When running yarn build, using appDir pages are generated with zero bytes

```
Route (app)                                Size     First Load JS
┌ ○ /                                      0 B                0 B
├ λ /[user]                                0 B                0 B
├ λ /[user]/[course]                       0 B                0 B
├ ○ /about                                 0 B                0 B
├ ○ /business                              0 B                0 B
```

### Expected Behavior

Generate correct pages

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

none

### To Reproduce

Create a project using appDir and run  'yarn build'

**Comment by balazsorban44** [comment]
Closing in favor of #42874

**Comment by tzii** [comment]
still getting this error when using route group (13.0.5)
![image](https://user-images.githubusercontent.com/61374202/204098070-461daa54-a9e2-419c-ba39-182d25c14d24.png)
