### ISSUE TITLE
appDir not supported when building with output standalone mode. All routes fail with 404 errors.

### ISSUE THREAD

**Issue by ferdingler** [vercel/next.js#42812]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

Docker

### Describe the Bug

The appDir feature does not work when building the app with `output: "standalone"` mode. The produced `.next/standalone/server` directory is missing the `app` content as well as the corresponding traces, dependencies and chunks. This causes the standalone application to throw 404 errors on all page routes. 

### Expected Behavior

The `.next/standalone` folder should contain all the necessary files for the `app` directory along with required node_modules dependencies and related chunk files. The app should not throw 404 errors when running the `node .next/standalone/server.js` file. 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://codesandbox.io/s/unruffled-bose-7eykvd?file=/next.config.js

### To Reproduce

- Enable `experimental.appDir = true` in `next.config.js` file. 
- Enable `output = "standalone"` in `next.config.js` file. 
- Run  a build: `npm run build`. 
- Run the produced output `node .next/standalone/server.js` file. 

Application crashes with 404 errors.

**Comment by fahadlabs** [comment]
Exact same error. Need a solution asap.

**Comment by balazsorban44** [comment]
Hi, `output: "standalone"` is not yet supported by the app directory. If you rely on this feature, you can keep using `pages` as before. We are going to update the [roadmap docs](https://beta.nextjs.org/docs/app-directory-roadmap) to include this. Thanks!

**Comment by DenisBessa** [comment]
I noticed that this planned feature is not in [roadmap docs](https://beta.nextjs.org/docs/app-directory-roadmap) anymore.

It is still planned?

**Comment by balazsorban44** [comment]
Yes, it is still planned, will try to make sure it is better presented in the roadmap, it should go under `next.config.js` options. Thanks for pointing out.

**Comment by barayuda** [comment]
Thanks alot for fix this @DuCanhGH in canary release 🎉

**Comment by DuCanhGH** [comment]
@vesters I've just reproduced the error. It seems that it only happens if you don't have a pages/ dir, so maybe you can try creating one. I don't think that issue is related to this issue though, you should open a new issue :) I can investigate it tomorrow if I'm not busy.

**Comment by vesters** [comment]
Awesome work, thank you!

And I can confirm that adding a 'pages'-folder fixed the error I was getting.

**Comment by DuCanhGH** [comment]
@vesters the change has been approved. Wait for the next release and you should probably be able to delete pages/ :)

**Comment by vesters** [comment]
Thank you very much. I have already tried and it works without the 'pages' folder👌
Great work!
