### ISSUE TITLE
Significant bundle size increase in Nextjs 13.3.3

### ISSUE THREAD

**Issue by belgattitude** [vercel/next.js#42813]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022
    Binaries:
      Node: 16.17.0
      npm: 8.19.3
      Yarn: 4.0.0-rc.28
      pnpm: 7.15.0
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

There's a significant size increase when upgrading from 13.3.2 to 13.3.2.

"Shared by all" went from **150kb to 180kb** (swc complier and `swcMinify: true`)

![image](https://user-images.githubusercontent.com/259798/201437317-83f9a33e-4488-4aa8-9a0d-6a1471d27d14.png)

"Pages" sees a size increase

![image](https://user-images.githubusercontent.com/259798/201437542-b90db9df-597f-48a1-89c3-5d933f96a358.png)

"Bundle analyzer" report a size increase in "parsed size"

![image](https://user-images.githubusercontent.com/259798/201436932-6ab66177-ec8b-46dd-bb81-ca4f44d617f5.png)

### Expected Behavior

A size increase can happen but as this one is quite big, I guess it should be taken into consideration.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/belgattitude/nextjs-monorepo-example/pull/2896

### To Reproduce

Follow the instructions in the PR: https://github.com/belgattitude/nextjs-monorepo-example/pull/2896.

You'll find how to install both version to easily compare locally.

**Comment by belgattitude** [comment]
Disabling swcMinify helped. Gentle ping to @kdy1 

See also https://github.com/vercel/next.js/discussions/30237#discussioncomment-4120838

**Comment by kdy1** [comment]
Fixed by https://github.com/vercel/next.js/pull/42790

**Comment by belgattitude** [comment]
Great, thanks a lot.
