### ISSUE TITLE
can you delete https://github.com/vercel/next.js/issues/41280 

### ISSUE THREAD

**Issue by narasimhamurthi** [vercel/next.js#42822]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

plz delete https://github.com/vercel/next.js/issues/41280 as it is raised by mistake.

### Which example does this report relate to?

delete

### Describe the Bug

plz delete https://github.com/vercel/next.js/issues/41280 as it is raised by mistake.

### Expected Behavior

plz delete https://github.com/vercel/next.js/issues/41280 as it is raised by mistake.

### To Reproduce

plz delete https://github.com/vercel/next.js/issues/41280 as it is raised by mistake.

**Comment by joulev** [comment]
It has been closed, there is no need to do anything about it. It's not necessary to delete closed issue whether it's opened by mistake or not IMO. Probably you should close this issue too.

**Comment by narasimhamurthi** [comment]
> It has been closed, there is no need to do anything about it. It's not necessary to delete closed issue whether it's opened by mistake or not IMO. Probably you should close this issue too.
@joulev 
 the has my company org details  which is vulnerable. that is the reason i need https://github.com/vercel/next.js/issues/41280 to be deleted ASAP.

**Comment by joulev** [comment]
Oh I didn't notice that, sorry. Yes then it should be deleted. That said you should have raised this issue much earlier.

Unfortunately I'm just another Next.js user like you, I don't have such privileges.

**Comment by balazsorban44** [comment]
I deleted the issue, but to be fair, I did not see anything sensitive in the description. For security reasons though, if you think anything has been leaked, it is imperative that you change secrets, etc. at your company. Once something has been published online, you cannot assume it's ever safe again.

**Comment by narasimhamurthi** [comment]
Thanks @balazsorban44
