### ISSUE TITLE
Docs: Update Next tutorial on the official website

### ISSUE THREAD

**Issue by Shubham-Rasal** [vercel/next.js#42830]
### What is the improvement or update you wish to see?

After the release of v13 of next, the tutorial present on the website has become outdated.

### Is there any context that might help us understand?

[This page](https://nextjs.org/learn/basics)

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics

**Comment by balazsorban44** [comment]
Thanks, we will look into this!
