### ISSUE TITLE
No client-only APIs or next/headers in client component

### ISSUE THREAD

**Issue by tinleym** [vercel/next.js#42838]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.3-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.110

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

Client components can render in an environment where neither client-only APIs (like the document object) nor next/headers are available. 

This creates issues when, for example, cookies are needed for a fetch. If a client environment is assumed, the document object isn't available and credentials are not available to be attached to a request. If a server environment is assumed, cookies aren't available from next/headers and so also can't be attached to the request.

### Expected Behavior

If client-only APIs are not always available to client components, then the next/headers API should be available.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/tinleym/next13-oddity

### To Reproduce

Run next dev and check the server-side console. You'll see a case where neither the document object nor the next/headers cookie function is available.

**Comment by balazsorban44** [comment]
There is no way to read headers in a browser. For cookies, you can read them from `document.cookie`, although keep in mind, only non `HttpOnly` cookies can be read.

Cookies are automatically attached to a client-side request to the backend, so you don't need to do anything about that.

To initiate a `fetch` call from a client component, usually you would use a library (`swr` or `react-query`), or `useEffect`, which only executes client-side, and will have `document` available.
