### ISSUE TITLE
[appDir] ModuleParseError for import that works in /pages

### ISSUE THREAD

**Issue by oBusk** [vercel/next.js#42839]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
Binaries:
  Node: 16.18.1
  npm: 9.1.1
Relevant packages:
  next: 13.0.3
  eslint-config-next: 13.0.3
  react: 18.2.0
  react-dom: 18.2.0

### Describe the Bug

Importing packages depending on, what I assume is causing it, (the bane of every npm install ever) `node-gyp` fails with the following error 

```
ModuleParseError: Module parse failed: Unexpected token (9:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // This script needs to be compatible with PowerShell v2 to run on Windows 2008R2 and Windows 7.
| 
> using System;
| using System.Text;
| using System.Runtime.InteropServices;
```

Using the same import in a page in `/pages` works as intended. I assumed this was because `/app` uses Edge runtime, but what the [documentation says](https://beta.nextjs.org/docs/rendering/edge-and-nodejs-runtimes) is that the app directory also uses the node runtime by default. I assume there is some change in the webpack configuration between `/app` and `/pages` files which causes this.

### Expected Behavior

Either that the webpack configuration for `/app` handles the terrible things happening in `node-gyp`, _or_ clarified somewhere in the documentation what the limitation of packages used in `/app` files is.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/oBusk/module-parser-error

### To Reproduce

In any Next 13 project 
1. Import a package which depends on node-gyp upstream in a `/pages` page and ensure it works.
1. Now clone this page as a `/app` page 
1. Run `npm run dev`
1. Try to load the page that is in `/app`. 
1. See the error.

In the linked reproduction I've built two identical pages using `/pages` and `/app` dir, and if you load the `/pages` page initially, it works, but trying to load the `/app` version will break the build. Trying to build will always break the build.

**Comment by balazsorban44** [comment]
This is due to the fact that dependencies will by bundled by default in the `app/` directory. You can opt out of this behaviour by adding this to your `next.config.js` file:

```js
experimental: {
  serverComponentsExternalPackages: ['pacote'],
  appDir: true,
},
```

You can check out the docs here: https://beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages

**Comment by oBusk** [comment]
@balazsorban44 Thanks for the response!
