### ISSUE TITLE
[NEXT-683] `writeConfigurationDefaults` throw error when using `extends` in `tsconfig.json`

### ISSUE THREAD

**Issue by GoodbyeNJN** [vercel/next.js#42831]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Mon Sep 19 19:14:52 UTC 2022
    Binaries:
      Node: 16.17.0
      npm: 8.8.0
      Yarn: 1.23.0-20220130.1630
      pnpm: 7.15.0
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

There is a base tsconfig in the project root directory, and a tsconfig in the next directory extends it.

As you can see, there is no `include` property in next-tsconfig, but there is in base-tsconfig. And `tsc -p apps/next/tsconfig.json --showConfig` shows there is `include` property in which finally applied to the next directory.

When runs `npm run dev`, it throws `TypeError: Cannot read properties of undefined (reading 'push')`.

I found the source of the error:
https://github.com/vercel/next.js/blob/canary/packages/next/lib/typescript/writeConfigurationDefaults.ts#L182

In my demo, the value of `rawConfig` would be:

```js
{
  extends: '../../tsconfig.json',
  compilerOptions: { target: 'ES5' },
  compileOnSave: false,
  include: [ '../../**/*.ts', '../../**/*.tsx' ],
  exclude: [ '../../node_modules' ]
}
```

And the value of `userTsConfig` would be:

```js
{
  extends: '../../tsconfig.json',
  compilerOptions: { target: 'ES5' }
}
```

### Expected Behavior

It shouldn't throw error.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/GoodbyeNJN/write-ts-config-error

### To Reproduce

1. Run `npm install` to install deps
2. Run `npm run dev`, it will throw error

<sub>[NEXT-683](https://linear.app/vercel/issue/NEXT-683/writeconfigurationdefaults-throw-error-when-using-extends-in)</sub>

**Comment by JPBM135** [comment]
# Can reproduce (yarn):
![image](https://user-images.githubusercontent.com/67063134/214959233-ccbe15ce-1f21-4b1e-8b0b-f430c366d5c8.png)

### Ts in the next js folder
```json
{
	"extends": "../../tsconfig.json",
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"@app/*": [
				"./*"
			]
		},
		"plugins": [
			{
				"name": "next"
			}
		]
	}
}
```

### Ts in the Root
```json
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"compilerOptions": {
		"target": "es5",
		"lib": [
			"dom",
			"dom.iterable",
			"esnext"
		],
		"allowJs": true,
		"skipLibCheck": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"noEmit": true,
		"esModuleInterop": true,
		"module": "esnext",
		"moduleResolution": "node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "preserve",
		"incremental": true,
		"plugins": [
			{
				"name": "next"
			}
		]
	},
	"include": [
		"next-env.d.ts",
		"**/*.ts",
		"**/*.tsx",
		".next/types/**/*.ts"
	],
	"exclude": [
		"node_modules"
	]
}
```

**Comment by controversial** [comment]
has anyone found a solution for this issue?

**Comment by simPod** [comment]
Aslo on next.js 13.1.6

**Comment by shuding** [comment]
Fixed in https://github.com/vercel/next.js/pull/48668.
