### ISSUE TITLE
[appDir][Dynamic Rendering] Dynamic Data Fetching doesn't seem to be fully working (various bugs in Data Fetching & Route Segment Config Options)

### ISSUE THREAD

**Issue by gfortaine** [vercel/next.js#42856]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: N/A
      react: 18.3.0-next-fecc288b7-20221025
      react-dom: 18.3.0-next-fecc288b7-20221025

### Describe the Bug

It seems that we have had a hard time setting up Dynamic Rendering. Indeed, it looks like that many of the various options are still KO at the time of writing :

- [Route Segment Config Options](https://beta.nextjs.org/docs/api-reference/segment-config)
  -  `dynamic` with `'force-dynamic'` & `fetchCache` with `'default-no-store'` didn't work
 
- [Dynamic Data Fetches](https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering#using-dynamic-data-fetches)
  - `{ cache:  'no-store' }` & `{ next: { revalidate: 0 } }` didn't work neither

At the end of the day, only `revalidate` with a value of `0` did the trick

### Expected Behavior

Options to enable Dynamic Rendering described in the documentation should work :

https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering#dynamic-rendering

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/vercel/next-react-server-components

### To Reproduce

Clone the repo and use the various options (except  `revalidate` with a value of `0` that is working) in the `ItemPage` Server Component (`/app/item/page.js`). Then, you will see the bug when trying to go on the `/item` page with the following error message :

`An item with an ID must be provided as a query parameter.`

**Comment by gfortaine** [comment]
@huozhi @shuding @timneutkens @leerob It seems that the current tests are KO (`test/e2e/app-dir/app-static-test.ts`, https://github.com/vercel/next.js/pull/41505). Indeed, it looks like that we shouldn't use `Date.now()` to ensure that we have the expected behaviour. Another possibility could be to check if searchParam is correctly handled by the Server Component (like what is done in the repository aforementioned).

**Comment by balazsorban44** [comment]
@gfortaine we will look into this. For future reference, please refrain from mass tagging core maintainers. :pray: :green_heart:

**Comment by gfortaine** [comment]
@balazsorban44 As a side note, it seems that the bug appears only in production mode (`run build`) not in development

**Comment by jmcruzmanalo** [comment]
Encountering the same thing, the `dynamic` option is completely ignored it seems.
![image](https://user-images.githubusercontent.com/41225365/202062723-d37a08f3-d79b-4915-a416-83d893fbef33.png)

I've tested as well that `revalidate: 0` in `fetch` calls is one option to force SSR as @gfortaine stated. An alternative I found was to use call `import { previewData } from 'next/headers'` to force SSR again.

![image](https://user-images.githubusercontent.com/41225365/202063034-618ddd69-06d4-4130-99b8-dec2e667b706.png)

**Comment by sumiren** [comment]
Same for me.

For me, `export const dynamic='force-dynamic'`does not work totally now.
Only `export const revalidate=0` works.

**Comment by zenflow** [comment]
@gfortaine fyi
> Upgraded to next@13.1.0 and the issue seem to have been fixed.
https://github.com/vercel/next.js/issues/43191#issuecomment-1363403154

**Comment by dumbravaandrei22** [comment]
Hello!
I can still reproduce this in 13.1.1 and 13.1.2-canary.4 dev and build mode.
@gfortaine Can we reopen this? 
If we cannot, I will file a new issue.

Did you manage to solve this using 13.1.1?
