### ISSUE TITLE
Next 13: ISR not working for eperimental-edge runtime

### ISSUE THREAD

**Issue by thomkrupa** [vercel/next.js#42859]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.6.0
      Yarn: 1.22.19
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.3-canary.4
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

ISR doesn't seem to work for `eperimental-edge` runtime. x-vercel-cache is MISS for all requests.

### Expected Behavior

Vercel should cache the page in both runtimes.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://next13-subpages-1ih8md05t-thomkrupa.vercel.app/

### To Reproduce

1. Go to the https://next13-subpages-1ih8md05t-thomkrupa.vercel.app/isr/1/node
2. Open Network tab
3. Refresh, cache is HIT
4. If you go to https://next13-subpages-1ih8md05t-thomkrupa.vercel.app/isr/1/edge
5. Open Network tab
6. Refresh, cache is always MISS

Repository: https://github.com/thomkrupa/next13-subpages-bug/tree/isr-edge

**Comment by balazsorban44** [comment]
Hi, ISR for the Edge Runtime is currently not supported, so currently, this is expected.

**Comment by neoromantic** [comment]
@balazsorban44 that would be alright, if we could built static sites without edge runtime on next13. 

If I understand it correctly, there's no way currently to have ISR page, that works with edge cache & on next13. Am I wrong?
