### ISSUE TITLE
AppDir: component styles get overridden every time new component instances load

### ISSUE THREAD

**Issue by ErAz7** [vercel/next.js#42862]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Whenever a new component loads, it overrides any custom styling on that component.
For example lets say I have a Link component that has `color: gray` and I've used it in header but because header is gray itself, I've added a custom styling for that link as `color: white`. 
Now imagine I have another page that uses same Link component but with default styles this time (`color: gray`)
Open the app's home page (which does not have any link inside, only in header), everything fine, navigate to the other page that is using Link component, header color breaks because the default style of the Link component loads again and replaces custom color set for header Link

### Expected Behavior

Think it's obvious but just to fill in:
The ideal behavior is not to refetch Link component's styles when it's already loaded
Another bad but still better behavior would be to load it but not override custom styles of Link in header

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

[Reproduction Live (stackblitz) Link](https://stackblitz.com/edit/vercel-next-js-gjdhpw?file=app/head.tsx)

![2022-11-14_1-53-18](https://user-images.githubusercontent.com/46329768/201547567-59aa3dec-67dd-4278-9103-1024bc783bc7.gif)

### To Reproduce

Explained enough in **Describe the Bug** section, together with the reproduction link it should be enough to reproduce

**Comment by timneutkens** [comment]
Just had a look at this and it seems to me that the behavior is correct, the reason it ends up overriding styles is that you're putting two different css module classes on the `<Link>` whereas the CSS set on a component using CSS modules has to be unique/non-conflicting otherwise you'll end up with loading-order issues. Will double check with the team though.

**Comment by ErAz7** [comment]
Thank you for checking @timneutkens 
if I understood correctly, you mean I should not add custom style to Link component on header? but if so, then how can we handle customization of component styles when I have a component with some default styles but in a specific use case I need to override some of those

**Comment by ErAz7** [comment]
with the current approach, when I use a component as a `server-component`, the component is not downloaded by client but its styles are injected (which is inevitible) but when later for example user navigates to another paget that exact same component is used, the styles are loaded again

I think the reason we dont have this issue in lets say an SPA, is because it loads components that it needs whenever they are used so there's no repeated-style-loading but with `server-components` aproach, styles are loaded again when the component is reused

**Comment by ErAz7** [comment]
any update @timneutkens?

**Comment by balazsorban44** [comment]
Please refrain from tagging core maintainers to gain visibility. 💚

**Comment by ErAz7** [comment]
sure, my bad!

**Comment by ErAz7** [comment]
> I think the issue is the href has a ...
does that mean this problem only happens with Link component?

**Comment by ErAz7** [comment]
Thanks @shuding
is this supposed to fix this issue? because I tested on the stackblitz shared above and there was no improvement regarding this bug
tested on [13.0.5-canary.3](https://www.npmjs.com/package/next/v/13.0.5-canary.3)

**Comment by shuding** [comment]
@ErAz7 It's not released yet (`canary.3` was before that commit: https://github.com/vercel/next.js/commits/canary), I think a new one will be out today.

**Comment by ErAz7** [comment]
got it, thanks

**Comment by ErAz7** [comment]
Confirm the fix by @shuding resolves the problem

**Comment by ErAz7** [comment]
The problem still persists in some cases @shuding 
Here in this screenshot, I have a general Modal component and a PriceModal component
Modal sets grid to `1fr 1fr` but since PriceModal needs 3 columns, it sets grid to `1fr 1fr 1fr`. Basically everything should work just fine but again the class/style of Modal loads 2 times and the second one orverrides the styles from PriceModal
![2022-12-10_15-27-47](https://user-images.githubusercontent.com/46329768/206854071-4332026c-1e62-4a4e-8381-2a052f85fe35.jpg)

OS: Linux
Browser: Chrome
Next: 13.0.7-canary.4

**Comment by ErAz7** [comment]
Also happens for header link:

![2022-12-10_18-44-05](https://user-images.githubusercontent.com/46329768/206862141-c6c4769f-b7ff-4e8d-8a1e-975b82654a92.jpg)

you see the exact same classname and styles are repeated 4 times

**Comment by ErAz7** [comment]
this whole issue may be related to https://github.com/vercel/next.js/issues/20203

**Comment by shuding** [comment]
The bug should be fixed with #44938
