### ISSUE TITLE
Next.js 13.0.3 adds 48kb javascript to first load

### ISSUE THREAD

**Issue by iljamulders** [vercel/next.js#42889]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Upgrading to `next@canary` results in 48kb of extra javascript being loaded on first load

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.4
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0
```

### 13.0.2
![Screenshot 2022-11-14 at 10 30 39](https://user-images.githubusercontent.com/6195121/201633202-7f5ac064-0c33-4110-a39e-766f83a38b2e.png)

### 13.0.3
![Screenshot 2022-11-14 at 10 31 16](https://user-images.githubusercontent.com/6195121/201633242-3eaf33a9-3ecb-432f-bb16-c5d04e34e61d.png)

### Expected Behavior

Next 13.0.3 should not add so much extra javascript

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

yarn create next-app --typescript

### To Reproduce

Create a new next.js project with `yarn create next-app --typescript`

Switch between next.js 13.0.2 and canary, and see the difference in js file size
```
yarn add next@13.0.2
yarn build
yarn start
```

```
yarn add next@canary
yarn build
yarn start
```

**Comment by balazsorban44** [comment]
Thanks, this has been addressed already in https://github.com/vercel/next.js/pull/42790, but it's not yet released. It will be fixed in the next `canary` release.
