### ISSUE TITLE
NextRouter was not mounted

### ISSUE THREAD

**Issue by davidizac** [vercel/next.js#42907]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

Getting "NextRouter was not mounted" when using the useRouter hooks from next/router
<img width="458" alt="Screen Shot 2022-11-14 at 6 08 46 PM" src="https://user-images.githubusercontent.com/34278628/201710193-c6d8fb44-23c8-4458-b361-ed57a60ba7a5.png">
<img width="529" alt="Screen Shot 2022-11-14 at 6 08 52 PM" src="https://user-images.githubusercontent.com/34278628/201710207-d32db2e7-07ee-4660-9f2f-76d54c91b01f.png">

### Expected Behavior

Should not get the error

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-nlrwaa?file=app/layout.tsx

### To Reproduce

Error will happens instantly

**Comment by davidizac** [comment]
Found why.
Should use next/navigation

**Comment by justEstif** [comment]
If you are looking for the path name in a client component, 
import { usePathname } from "next/navigation";
