### ISSUE TITLE
Middleware does not function in Next.js 13 while using Turbopack

### ISSUE THREAD

**Issue by scissorhands26** [vercel/next.js#42921]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 19.0.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.4
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Using `next dev --turbo` causes middleware not to execute. 

### Expected Behavior

Using `next dev --turbo` should not affect middleware execution.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/scissorhands26/nextjs-13-middleware-turbopack-bug

### To Reproduce

Use middleware in conjunction with the pages or app directory, and add the `--turbo` flag to `"dev": "next dev --turbo"`.

**Comment by renanrodrigueszup** [comment]
having the same issue in a turborepo environment

**Comment by racsogrok** [comment]
I'm experiencing this issue as well. I was looking to build a library that integrates well with Turbopack, but this is the last blocker I'm facing at the moment.

**Comment by shakibhasan09** [comment]
Same issue here

**Comment by rokob** [comment]
Any update here? I am still seeing this.

**Comment by ARKHN3B** [comment]
Any update? I have this issue when using `next-intl` with Turbopack

**Comment by Warmachine13** [comment]
Waiting for this update

**Comment by psidofuturodev** [comment]
Same issue here

**Comment by yazhouio** [comment]
I encountered the same issue when using `next dev --turbo`.
If my code is located in the `src` directory, the middleware does not run. 

My solution was to move the `app` directory and `middleware.js` to the root directory. This way, the middleware can run.

**Comment by daniel-koudouna** [comment]
Has there been any progress on this? We are also facing this issue inside a turborepo project on 14.0.0 . Removing the `src` folder does make the middleware run, but it is not an ideal solution. Is there a flag we should use like `--root` in this case?

**Comment by gangeshwark** [comment]
Any update on this yet? We are still facing this issue too. We'd like to maintain the existing folder structure.

**Comment by digitaltopo** [comment]
+1 seeing the same issue, `middleware.ts` in `/src` folder with `/app` directory and it doesn't get picked up while using `--turbo`

**Comment by Fraank98** [comment]
A year has passed and you still can't use turbo with a middleware...omg

**Comment by ForsakenHarmony** [comment]
Sorry for the long wait, a fix is in #58218
