### ISSUE TITLE
The css class are duplicated after save file.

### ISSUE THREAD

**Issue by Hardel-DW** [vercel/next.js#42926]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.3-canary.4
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Version 107.0.5304.107 (64 bits)

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

The bug occurs with NextJS 13.  

After starting the development environment with "next dev", an HotRelaoding, just save a file.  
This action will duplicate all of the CSS classes.  
These extremely annoying !

![image](https://user-images.githubusercontent.com/42413417/201814388-21ae0a5a-e3ab-4014-a27e-b8fcf2fb9fa4.png)

### Expected Behavior

The styles are duplicated after save files.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/Hardel-Labs/next13-template

### To Reproduce

1. Create a new project 
`yarn create next-app --experimental-app .`

2. Start
`next dev` or `yarn dev` or 'npm dev`

3. Edit .tsx, or styles files (css, scss, module...).

4. Opened the browser's developer tools.

5. See that the classes are all duplicate.

**Comment by JarrodMFlesch** [comment]
Duplicate https://github.com/vercel/next.js/issues/42702

**Comment by shuding** [comment]
This issue was fixed in newer versions, let us know if it's still happening.
