### ISSUE TITLE
[Bug] Using webpack require.context in Next.js v12/v13 will return a promise

### ISSUE THREAD

**Issue by yy523697597** [vercel/next.js#42931]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

node v16.17
next.js v12.2 / v13
yarn v1.22

### What browser are you using? (if relevant)

chrome 107

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When using webpack's require.context to import components in next v12/v13, the returned value is a promise. After setting experimental: { esmExternals: false } in next.config.js, the returned value is normal.

![image](https://user-images.githubusercontent.com/22169084/201860708-3cdddfce-65fd-4c61-9c94-ff5bf9255c30.png)

![image](https://user-images.githubusercontent.com/22169084/201862587-0f61dcc0-6614-44fc-886f-fb733527dcc3.png)

![image](https://user-images.githubusercontent.com/22169084/201862265-eefecc3b-577e-443a-89b9-775cafe23850.png)

### Expected Behavior

Promise is not returned when using webpack's require.context to import components in next v12/v13

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/tailwindlabs/headlessui/discussions/1203

### To Reproduce

use reqiure.context in next.js

**Comment by balazsorban44** [comment]
In Next.js 12, [we enabled](https://nextjs.org/blog/next-12#es-modules-support-and-url-imports) `esmExternals: true` by default, meaning that we will look for ESM by default, which resolves asynchronously, so this is expected.

To import components more efficiently, have a look at `next/dynamic`, which will lazy load components https://nextjs.org/docs/advanced-features/dynamic-import
