### ISSUE TITLE
Sub route cannot inherit any tags in head tag which not present but in root `head.tsx`

### ISSUE THREAD

**Issue by Ryan2128** [vercel/next.js#43020]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: 7.14.2
    Relevant packages:
      next: 13.0.4-canary.3
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.110

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

@timneutkens

Thanks for your work in #42904 , bug in `13.0.4-canary.3` version, `/about-me` route's head tag cannot inherit any tags which not present in head tag but in root `head.tsx`

`/` route's `Head.tsx`

<img width="1527" alt="image" src="https://user-images.githubusercontent.com/33176053/202360322-184e2d98-afed-42c5-aa75-525591b61bbb.png">

`/about-me` route's `Head.tsx`

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/33176053/202360343-778355cb-9890-4da0-90a8-0ccf216d428a.png">

`/` route's head tag

![image](https://user-images.githubusercontent.com/33176053/202360709-0a3cdf1e-6697-44e1-94f6-933e574fdbbb.png)

`/about-me` route's head tag

![image](https://user-images.githubusercontent.com/33176053/202360737-ba8424cd-a576-43f1-95b1-ecee48b15bc5.png)

### Expected Behavior

Expected Behavior same as `next/head` component in v12.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

The code needed to reproduce is above.

### To Reproduce

1. `yarn dev`
2. switch route
3. check the head tag

**Comment by balazsorban44** [comment]
Hi, this is expected behavior. You can check out the documentation here: https://beta.nextjs.org/docs/api-reference/file-conventions/head#sharing-tags-across-multiple-routes
