### ISSUE TITLE
dropzone.js can't be loaded if I use swc

### ISSUE THREAD

**Issue by 0ldm0s** [vercel/next.js#43027]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.0.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.16.0
    Relevant packages:
      next: 13.0.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I use dropzone.js for my nextjs project. I can use it in dev mode, but can't use it for ssg mode.

If I export for ssg, I get the error: `extend is not defined`. 

Then I try to use `dynamic import` with `ssr: false`, nothing has changed, it's returns same error.

But, If I disable `swcMinify`, it can be used. 

P.S. I disable it, but output file size is smaller. why?

### Expected Behavior

dropzone.js can be use for ssg with swcMinify.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/0ldm0s/dropzone-demo

### To Reproduce

set `swcMinify: true` in `next.config.js`

**Comment by balazsorban44** [comment]
The output size difference was a regression, it has been fixed in #42790. But there is still an issue with the minifer regarding the good in the reproduction, so we will look into it. Thanks for reporting.
