### ISSUE TITLE
Next13 How does the client component use the data from the server component

### ISSUE THREAD

**Issue by coderlfm** [vercel/next.js#43039]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

nextjs

### Which example does this report relate to?

-

### Describe the Bug

This is how it was used in next12
```js
export async function getStaticProps() {
  const posts = await getPosts()
  return { props: { posts } }
}

function Posts(props) {
  const { data } = useQuery({
    queryKey: ['posts'],
    queryFn: getPosts,
    initialData: props.posts,
  })

  // ...
}
```
I have similar needs in next13

I want the server to have the data ready when the page first opens. For example, the first page of a blog is rendered by the server, and when the second page is clicked, the client resends the request

As far as I know, in next13 the server component couldn't transfer data to the client.

How is this requirement handled in next13?

### Expected Behavior

I wish there was a way for the client to get the server component's data as initialization data

### To Reproduce

-

**Comment by balazsorban44** [comment]
You can pass props to client components with the one requirement that they need to be serializable (eg.: for example you cannot pass functions).

Please refer to the docs: https://beta.nextjs.org/docs/rendering/server-and-client-components#passing-props-from-server-to-client-components-serialization
