### ISSUE TITLE
502 TOO_MANY_FORKS on Vercel with simple redirect

### ISSUE THREAD

**Issue by cipriancaba** [vercel/next.js#43032]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.13.1
    Relevant packages:
      next: 13.0.4-canary.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Vercel is erroring on root path with a 502. No middleware is involved but there is some strangeness happening with some nested dynamic routes

We are using middleware to do rewrites for statically generated AB experiments and this has served us well with the pages dir

Created a repro repo here https://github.com/cipriancaba/nextjsmiddlewareabtesting
Deployed version is here https://nextjsmiddlewareabtesting-web-i2ex.vercel.app/

What goes wrong:
- the middleware `rewrite` is redirecting instead of rewriting, see: `https://nextjsmiddlewareabtesting-web-i2ex.vercel.app/about-us`
- root path `/` is erroring with 502 even though this is not part of the dynamicSlug route. Removing the dynamicSlug route fixes the problem
- Everything works as expected locally with `next dev` and `next start`

### Expected Behavior

Root path is acessible
Rewrites don't redirect
Would get more info on to what's wrong in order to debug this

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/cipriancaba/nextjsmiddlewareabtesting

### To Reproduce

Deploy to vercel

**Comment by balazsorban44** [comment]
Hi, thanks for reporting, this should be fixed now! Let us know!
