### ISSUE TITLE
next/link breaks the client on prefetch if fetch request failed.

### ISSUE THREAD

**Issue by artmsv** [vercel/next.js#43048]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 9.1.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.4-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Client breaks when prefetch on next/link fails.

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/46975989/202522592-00851081-4d21-499e-b75b-14e0d7fca677.png">

### Expected Behavior

This error doesn't appear in `next: 12.1.0`. 
Page would follow the link without showing an application error if prefetch fails.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/artmsv/next-link-issue

### To Reproduce

1. You need to have adblocker/ublock.
2. Run `npm start` (this will build production and run it), go to index page and click on `/advertise-something` in next12 and next13.
3. next12 will not break client.
4. next13 will break client.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.0.4-canary.4` of Next.js, please update and give it a try!

**Comment by artmsv** [comment]
> Hi, this has been updated in `v13.0.4-canary.4` of Next.js, please update and give it a try!

Can confirm, thank you
