### ISSUE TITLE
`next build` breaks @microsoft/signalr [v13.0.3, canary]

### ISSUE THREAD

**Issue by acoiro** [vercel/next.js#43042]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.7.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.4-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

The built app doesn't behave as the dev app, see screenshot

<img width="602" alt="Screenshot 2022-11-17 at 16 53 42" src="https://user-images.githubusercontent.com/1120395/202498460-c3428b17-242e-4181-8319-97874226aed4.png">

I was able to identify the function in https://www.npmjs.com/package/@microsoft/signalr that doesn't compile correctly
(the reproduction code contains only this function)

```js
function resolveNegotiateUrl(url) {
  const index = url.indexOf("?");
  let negotiateUrl = url.substring(0, index === -1 ? url.length : index);
  if (negotiateUrl[negotiateUrl.length - 1] !== "/") {
    negotiateUrl += "/";
  }
  negotiateUrl += "negotiate";
  negotiateUrl += index === -1 ? "" : url.substring(index);
  if (negotiateUrl.indexOf("negotiateVersion") === -1) {
    negotiateUrl += index === -1 ? "?" : "&";
    negotiateUrl += "negotiateVersion=1";
  }
  return negotiateUrl;
}
```

I pasted the function into the [SWC playground](https://play.swc.rs/?version=1.3.18&code=H4sIAAAAAAAAA32QTQ6CMBCF9z3F2IWpUVS2koYb6Eo3xoXigE2akrTFmBjubik%2FAhF37bx5b76ZtFCJFbkCjSaXT9xjlltxtXjUkhVaLuBNAJJcGQtC3fEFHFx57d%2BHlNGYLiLXIdGC6nmbNlPcjNVCZWy7av2cQxBC7HWJKrMP2NWaTxIpsH7Suf9pDQGEF5i5JLqhNSIMxy%2B9VOWV5IfUFXzLWB6BUuoAh9tM434v01VPqI07sQOtI6eAx2Pjai6de8R%2FOzT5POz21WgLrQaWiJTkAxl4R9XtAQAA&config=H4sIAAAAAAAAA0WNSw6DMAxE7%2BI123bBHXqIKDUoVX7yGKkoyt3rABU7ez5vGn3gaW5UnYBlXNizui%2FNpHtleAlVaSKFSYuL4G6Pk5XVIoyHebEU8OVOlEIOyz5IvqQqDNyWy2v8J7uBUnlvQ2jH2AF8Ur8ZKpvVAl5X7iz%2BAPJfOO21AAAA) but I couldn't reproduce the issue.

### Expected Behavior

The application behaves the same in dev and build mode.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/acoiro/next-13.0.3-build-bug

### To Reproduce

Run the reproduction code

```sh
git clone git@github.com:acoiro/next-13.0.3-build-bug.git
cd next-13.0.3-build-bug
npm install
npm run dev
```

Navigate to http://localhost:3000/ and see the correct output.

Now build and run the app

```sh
npm run build && npm start
```

Navigate to http://localhost:3000/ and see a different output.

**Comment by niranjan94** [comment]
Seeing a similar weird behaviour when using https://github.com/novnc/noVNC 

- `13.0.2 & before` - Works perfectly on both `npm run dev` & `npm run build && npm start`
- `13.0.3` - Works perfectly on `npm run dev`. Does not work on `npm run build && npm start`
-  `canary` - Works perfectly on `npm run dev`. Does not work on `npm run build && npm start`

Haven't still been able to narrow down the exact issue with compilation. But something is going wrong in 13.0.3
