### ISSUE TITLE
using @w3ui/react-uploader UploaderProvider in a Next.js app with SWC minification enabled breaks in production builds

### ISSUE THREAD

**Issue by travis** [vercel/next.js#43052]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: 7.13.4
    Relevant packages:
      next: 13.0.4-canary.3
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Brave Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

If I use the `UploaderProvider` from `w3ui/react-uploader` in my app it works fine in dev mode (`npm run dev`) but the app throws errors (https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]= and https://reactjs.org/docs/error-decoder.html/?invariant=423) when run in a production build with SWC minification enabled (`npm run build && npm start`). 

Disabling SWC minification in Next 12, 13 or canary fixes the issue.

### Expected Behavior

Apps using `UploaderProvider` should work the same in development and production mode, with SWC minification enabled or disabled.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/web3-storage/w3ui-swc-minify-bug

### To Reproduce

Clone https://github.com/web3-storage/w3ui-swc-minify-bug and run `npm install && npm run build && npm start` and then visit http://localhost:3000

Disable SWC minification (as demonstrated on this branch https://github.com/web3-storage/w3ui-swc-minify-bug/tree/fixed) to fix this issue. The issue also does not occur when running with `npm run dev`.

**Comment by kdy1** [comment]
I checked if https://github.com/vercel/next.js/pull/43449 is a fix, but seems like this was a different issue.
I'll work on this next week (as a task with the highest priority)
