### ISSUE TITLE
When multiple layout files exist, page transitions using the Link or Browser Back button do not work with the layout files.

### ISSUE THREAD

**Issue by GrowUp-Haruno** [vercel/next.js#43065]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Nov 18 2022 15:32:45 GMT+0900 (日本標準時)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.4-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Google Chrome 107.0.5304.110

### How are you deploying your application? (if relevant)

next dev or next start

### Describe the Bug

For example, if layout files exist for the root segment and the segment, if you transition from the root segment to the segment and then use the browser's back button to return to the root segment, the layout for the root segment will no longer be applied.
This effect extends to nested segments that do not contain layout files.

### Expected Behavior

The root segment layout file should be applied.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-3hug2o?file=app/page.tsxtfile-in-blog/layout.tsx

### To Reproduce

1. Click on "Open in New Tab" in the stackblitz IDE.

2. Open route
At this time, the first line will show the "root layout" set in (/app/layout.tsx).

3. Click on the "Go to Blog" link (/app/blog).
Since there is no layout file in (/app/blog), the first line will show "root layout" set in (/app/layout.tsx).

4. Use the browser back button to return to the root.
Since the anomaly has not yet occurred, "root layout" is displayed on the first line of the page.

5. Click on the "Go to layoutfile-in-blog" link (/app/layoutfile-in-blog).
Since the layout file (/app/layoutfile-in-blog/layout.tsx) exists, the first line will show "layoutfile-in-blog layout".

6. Use the browser back button to return to the root.
An anomaly occurs at this time and the first line "root layout" is not displayed.

7. Click on the "Go to Blog" link (/app/blog).
The first line "root layout" is not displayed.

8. Click the browser back button to return to the root.
The first line "root layout" is not displayed.

9. Click the "Go to layoutfile-in-blog" link (/app/layoutfile-in-blog).
The layout file (/app/layoutfile-in-blog/layout.tsx) will be applied and the first line will show "layoutfile-in-blog layout".

* In stackblitz, it is run with next dev, but it is also reproduced when run with next build and next start.

**Comment by hanneslund** [comment]
Hi! The reason is that `layoutfile-in-blog/layout.tsx` contains `<html>`, `<head>` and `<body>` which causes a hydration error, only the [root layot](https://beta.nextjs.org/docs/routing/pages-and-layouts#root-layout-required) should have those tags.

It works by updating `layoutfile-in-blog/layout.tsx` to:
```tsx
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <p>layoutfile-in-blog layout</p>
      {children}
    </>
  );
}

```

You can read more about pages and layouts [here](https://beta.nextjs.org/docs/routing/pages-and-layouts).

**Comment by GrowUp-Haruno** [comment]
Thank you so much.
I thought the error was on the server side, so I was missing the error check on the client side.
