### ISSUE TITLE
Problem with dependency on Windows

### ISSUE THREAD

**Issue by TheBrainOne** [vercel/next.js#43066]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**Operating System:**
- Platform: win32
- Arch: x64
- Version: Windows 10 Pro

**Binaries:**
- Node: 18.12.1
- npm: N/A
- Yarn: N/A
- pnpm: N/A

**Relevant packages:**
- next: 13.0.4
- eslint-config-next: 13.0.4
- react: 18.2.0
- react-dom: 18.2.0

### Describe the Bug

I create Next.js app on Windows used `npx create-next-app@latest` and `npx create-next-app@canary` and get some weird problem in package.json with dependency. I don't get this problem on MacOS.

So all dependencies are in production:
```json
{
  "name": "dev",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "eslint": "8.27.0",
    "eslint-config-next": "13.0.4",
    "next": "13.0.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.3"
  }
}
```

### Expected Behavior

There should be correct grouping of dependencies so that dev dependencies don't be used in production.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

-

### To Reproduce

Just create Next.js app on Windows using `npx create-next-app@latest` or `npx create-next-app@canary`.

**Comment by balazsorban44** [comment]
Hi, this is expected (and should not be OS-specific, you likely have a different version in the cache). Next.js is not relying on `dependencies` vs. `devDependencies` either if you host on platforms like Vercel or use `output: "standalone"`.
