### ISSUE TITLE
Compilation result does not conform to expectation

### ISSUE THREAD

**Issue by sbfkcel** [vercel/next.js#43060]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 12.1.5
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

-

### What browser are you using? (if relevant)

Chrome 107.0.5304.110

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

The development mode is normal, but the compiled results run abnormally.
Question 1
---
```javascript
let str1 = "Hello";
let str2 = " world"
let result = false ? 'wss' : 'https';
result += `://${str1}`;
result += str2;

// ://Hello world
console.log(result);
```

Question 2
---
Some styles will be ignored in the build result.

![image](https://user-images.githubusercontent.com/5469785/202620547-00a918e7-9f52-41f0-8063-f4ad522f4381.png)

### Expected Behavior

Question 1
---

```javascript
// https://Hello world
console.log(result);
```

Question 2
---
![image](https://user-images.githubusercontent.com/5469785/202619927-ed792967-ec49-4ad2-a0d9-8b9d689ff426.png)

### To Reproduce

```javascript
let str1 = "Hello";
let str2 = " world"
let result = false ? 'wss' : 'https';
result += `://${str1}`;
result += str2;

console.log(result);
```

**Comment by balazsorban44** [comment]
Sounds similar to #43042

**Comment by sbfkcel** [comment]
Yes, in ` next.config Js' After adding 'swcMinify fy: false', it is normal to compile again.

It is uncertain whether the ignored CSS is normal (border and shadow attributes) or whether the class name does not match.

In short, it is the 'swcMini fy' problem.

**Comment by balazsorban44** [comment]
I only verified the computation issue, if you have a CSS bug, please add a reproduction for that (a minimal repo)
