### ISSUE TITLE
Custom async hook does not work inside the middleware

### ISSUE THREAD

**Issue by hosseinitabar** [vercel/next.js#43071]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Nov 18 2022 14:46:18 GMT+0330 (Iran Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I want to import custom async hooks and use them inside my middleware. This is because I need to connect to API to get the redirection data, and I also work in a modular system. Thus the `SEO` modules is not in my code. I need to import stuff from it.

### Expected Behavior

`middleware.js` should work with custom async hooks.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/nextjs-odl1kp?file=UseRedirect.js,middleware.js

### To Reproduce

Create a next app

Create a custom async hook

Import it inside the `middleware.js`

Run

**Comment by balazsorban44** [comment]
There are some issues in the provided reproduction. This should work:

```diff
import { NextResponse } from 'next/server';
- import { useRedirect } from './UseRedirect';
+ import useRedirect from './UseRedirect';

export async function middleware(request) {
  if (request.nextUrl.pathname.startsWith('/_next')) {
    return;
  }

-  const checkRedirection = await useRedirect();
+  const { checkRedirection } = await useRedirect();

  const { isRedirected, newUrl } = checkRedirection(request.nextUrl);

  if (isRedirected) {
    return newUrl;
  }
}
```

**Comment by hosseinitabar** [comment]
@balazsorban44 My bad. I changed the code. But it does not [work](https://stackblitz.com/edit/nextjs-odl1kp?file=UseRedirect.js,middleware.js).

**Comment by hosseinitabar** [comment]
@balazsorban44 please follow the steps I have provided above. Create an empty next application, create a custom async hook, and use that hook inside your middleware. You should make the middleware function async too.

**Comment by balazsorban44** [comment]
My bad, but there are still issues:

```js
import { NextResponse } from 'next/server'
import useRedirects from './UseRedirect'

export async function middleware(request) {
  if (
    request.nextUrl.pathname.startsWith('/_next') ||
    request.nextUrl.pathname.startsWith('/foo') // Make sure to opt out of redirects to the same page to avoid infinite loops
  ) {
    return
  }

  const { checkRedirection } = await useRedirects()

  const { isRedirected, newUrl } = checkRedirection(request.nextUrl)

  console.log(isRedirected, newUrl)
  if (isRedirected) {
    return NextResponse.redirect(new URL(newUrl, request.nextUrl))
  }
}
```

```js
const useRedirects = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/users') // any process that takes time
  const redirects = await response.json()

  const checkRedirection = url => {
    return {
      isRedirected: true, // logic to check redirection
      newUrl: '/foo', // logic to form the new URL
    }
  }

  return {
    checkRedirection,
  }
}

export default useRedirects
```


If you have further problems, I recommend you to check out [Discussions](https://github.com/vercel/next.js/discussions).

**Comment by hosseinitabar** [comment]
@balazsorban44 than you for your notes. The point is, it still does not work.

Let me explain it better. It seems that the middleware wants to work at the client-side and we need it to be dynamic so we need it to work on the server-side (because of SEO).

And that's what makes the problem.

I have created a more complete example [here](https://stackblitz.com/edit/nextjs-rtpqzb?file=UseRedirect.js,middleware.js,ApiResponse.json,CheckRedirection.js,Cache.js,pages%2Findex.js)

Please think about it. These are our requirements:

1- We need to be able to get the redirection data, from API. Because our websites are dynamic (in fact, we are a website design agency)
2- We need to be able to cache that data. Because we can't contact our API for each request in the middleware for the sake of performance
3- We need to be able to run it on the server, because of SEO

It seems that Next.js does not support this combination. Or if it does, we can't find a good example to follow.

Thank you so much.

**Comment by balazsorban44** [comment]
> seems that the middleware wants to work at the client-side

this is incorrect, Middleware always runs on the server.

For further support, I recommend opening this in discussions https://github.com/vercel/next.js/discussions
