### ISSUE TITLE
What is the type signature of middleware.ts?

### ISSUE THREAD

**Issue by jameshfisher** [vercel/next.js#43072]
### What is the improvement or update you wish to see?

[The Middleware docs](https://nextjs.org/docs/advanced-features/middleware) show a TypeScript example, but the types are imprecise.

It seems that `middleware.ts` is expected to export two things, `middleware` and `config`. Here's my guess at typing them:

```ts
// middleware.ts
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

type NextMiddlewareReturnValue = 
  | NextResponse // e.g. a rewrite or redirect
  | void // Not an error - but not sure what it means
  ;

type NextMiddlewareFn = (
  request: NextRequest,
) => NextMiddlewareReturnValue | Promise<NextMiddlewareReturnValue>;

type NextMiddlewareConfig = { matcher: string | [string] };

// This function can be marked `async` if using `await` inside
export const middleware: NextMiddlewareFn = (request: NextRequest) => {
  return NextResponse.redirect(new URL('/about-2', request.url));
};

// See "Matching Paths" below to learn more
export const config: NextMiddlewareConfig = {
  matcher: '/about/:path*',
};
```

But I don't know if these are correct.

### Is there any context that might help us understand?

I'm looking for equivalents of `import { GetServerSideProps, NextPage } from 'next'`, etc.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/middleware

**Comment by balazsorban44** [comment]
The type in the example seems correct, your example assumptions should be adjusted. `Response` is a more correct return value, but you can just use `NextMiddlewareResult` instead.

Or if you are using function expressions, you can use `NextMiddleware` too:
https://github.com/vercel/next.js/blob/ce5b59d2ed71261bd5fbafb1abdf849c6d9d8926/packages/next/server/web/types.ts#L51

```ts
import { type NextMiddleware } from "next/server"

export const middleware: NextMiddleware = (req) => {
  // req is already typed
  return true // This will fail type checking too
}
```

`void` will call `NextResposne.next()` internally, for convenience: https://github.com/vercel/next.js/blob/ce5b59d2ed71261bd5fbafb1abdf849c6d9d8926/packages/next/server/web/adapter.ts#L194

**Comment by jameshfisher** [comment]
@balazsorban44 Thanks! `NextMiddleware` is exactly what I wanted.

The other part - do you know if there's a type for `config`?

**Comment by balazsorban44** [comment]
I don't think we have a type for that currently, want to open a PR? :+1: :pray:
