### ISSUE TITLE
req.nextUrl.host claims to be "localhost" when visiting a different domain

### ISSUE THREAD

**Issue by jameshfisher** [vercel/next.js#43090]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
$ npx --no-install next info

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.12.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.4-canary.5
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Chrome latest, Firefox latest - browser seems irrelevant

### Describe the Bug

In middleware, the `req.nextUrl.host` equals `"localhost"` even when the `Host` header is a different hostname that happens to resolve to `127.0.0.1`. For example, if visiting with host `foobar.local.gd` (a service that always resolves to `127.0.0.1`), Next still claims the host is `"localhost"`. But Next should not even know about the string `"localhost"` except if it's present in the HTTP request that it receives.

### Expected Behavior

The logging in `middleware.ts` should never happen, because the `req.nextUrl.host` should match the `Host` header in the HTTP request.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/jameshfisher/next-bug-middleware-host

### To Reproduce

Run `npx create-next-app@latest`. Run `npm i next@canary`.

Add this `middleware.ts` to log requests:

```ts
import { NextMiddleware } from "next/server";

export const middleware: NextMiddleware = (req) => {
  const hostHeader = req.headers.get("host");
  const claimedHost = req.nextUrl.host;
  if (claimedHost !== hostHeader) {
    console.log(
      `Weird: request has Host:${hostHeader} but req.nextUrl.hostname is ${claimedHost} in request to`,
      req.url
    );
  }
};
```

Run `npm run dev`.

Visit `http://next-bug.local.gd:3000/` in your browser. This `local.gd` service is a DNS server that always resolves to 127.0.0.1.

**Comment by balazsorban44** [comment]
This is currently expected, see the previous issue https://github.com/vercel/next.js/issues/37536

**Comment by jameshfisher** [comment]
Ah ok, thanks @balazsorban44. I'll just make sure to use `req.headers.get("host")` instead, then, since I don't think I need `req.nextUrl.host`.

(I do find this weird, though. It makes sense that `next dev` is given a port, because it has to listen on that port. But it's weird that `next dev` is given a hostname, since there's no such thing as "listening on a hostname". And I can't see what the security issue is that it's solving - is there a concrete example of a vuln that would happen if `req.nextUrl.host came from the Host header?)
