### ISSUE TITLE
NextJS 13 build dropping addition assignment operator (+=)

### ISSUE THREAD

**Issue by clayrisser** [vercel/next.js#43104]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Debian 6.0.8-1 (2022-11-11)
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 3.1.0
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 13.0.3
      react: 18.1.0
      react-dom: 18.1.0

### What browser are you using? (if relevant)

Chrome and Firefox

### Describe the Bug

NextJS application is fine during `next dev`. However, when I build the app and run it `next build && next start`, the transpiled code is dropping the addition assignment (`+=`) operator on code in `node_modules`.

Here you can see the original code . . .

![2022-11-18-143050_screenshot](https://user-images.githubusercontent.com/6234038/202810425-46231b2f-db1c-4574-a768-1fed4dfa222d.png)

. . . and here you can see what it gets transpiled to. Notice it dropped `+=`.

![2022-11-18-143157_screenshot](https://user-images.githubusercontent.com/6234038/202810493-d56fb192-86ae-4a45-ae1e-0a461b41faa9.png)

I have tried this using a `babel.config.js` and without babel. The result is the same. I am using the latest nextjs.

### Expected Behavior

Should not drop `+=`

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://example.com

### To Reproduce

Setup nextjs and install a node module that uses `+=` in the code

**Comment by clayrisser** [comment]
Just confirmed this bug does NOT happen in nextjs `12`. This is a serious regression.

**Comment by clayrisser** [comment]
I'm wondering if the bug is located somewhere in the optimization/minifying. Does nextjs use the same minifier with SWC and babel, because the bug happens in both modes.

**Comment by Janpot** [comment]
Just ran into this as well https://github.com/vercel/next.js/issues/43128.

**Comment by bysxx** [comment]
The same issue occurs in component type related to next

**Comment by kdy1** [comment]
@Janpot I think it's already fixed on upstream. Did you try canary?

**Comment by kdy1** [comment]
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/29931815/203027593-adb39a2d-a53f-4538-888d-56547faef4e8.png">

**Comment by kdy1** [comment]
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/29931815/203028290-b97394d8-f1e4-4785-9815-f3899b84cb5d.png">

**Comment by Janpot** [comment]
Confirmed, thank you. Apologies, I only tested on latest stable.

**Comment by balazsorban44** [comment]
Indeed, this is an SWC Minify bug @clayrisser which you can turn on or off by `swcMinify: true | false` in your `next.config.js`.

The issue has been fixed in `canary` already though, please give it a try!
