### ISSUE TITLE
Next.js 13 appDir regression page compression not enabled

### ISSUE THREAD

**Issue by transitive-bullshit** [vercel/next.js#43106]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.15.0
    Relevant packages:
      next: 13.0.5-canary.0
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.110

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Production pages and page data served from Next.js 13 `appDir` are not served with compression.

This is highlighted in Lighthouse scores, and is compounded by `next/link` prefetches. 

Example Lighthouse feedback:
<img width="804" alt="CleanShot 2022-11-18 at 16 34 49@2x" src="https://user-images.githubusercontent.com/552829/202814348-81aefec5-8eb9-426e-a456-92e8701640ba.png">

Example page GET `response` from chrome devtools:
<img width="1003" alt="CleanShot 2022-11-18 at 16 36 23@2x" src="https://user-images.githubusercontent.com/552829/202814543-57f1840d-6e15-4236-9f12-db1c0d55a830.png">

Note the absence of `content-encoding`.

### Expected Behavior

`content-encoding` should include `br` or `gzip` and the pages and prefetch data should be significantly smaller.

Example page response headers when using Next.js with `pages` instead of `appDir`:

<img width="559" alt="CleanShot 2022-11-18 at 16 37 12@2x" src="https://user-images.githubusercontent.com/552829/202814635-46080d83-7070-4847-b04b-3211a84c0020.png">

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://next-13-compression-bug.vercel.app/

### To Reproduce

1. Deploy any Next.js 13 `appDir` app to prod on Vercel (example: https://github.com/transitive-bullshit/next-13-compression-bug using the `reproduction-template` without any changes aside from updating to latest `next@canary`)
2. GET a page
3. Check the response headers

Additionally, check the response headers for `next/link` prefetches, which are also not compressed.

Also related: https://github.com/vercel/next.js/discussions/41745#discussioncomment-4175030 and there was another comment in the discussion thread related to Lighthouse "Enable text compression", but it's hard to find specific discussion posts once it passes a threshold.

**Comment by transitive-bullshit** [comment]
Note: there is a related bug here in that `content-type`, `etag`, and several Vercel-related headers are never returned for HTML and prefetch resources when using `appDir`. See the devtools screenshots and repro example above for examples.

**Comment by smallshen** [comment]
Any update?

**Comment by adamfortuna** [comment]
Great description of this issue! This is the largest issue on my site according to PageSpeed Insights too. I'm really enjoying working with Next.js 13, and have a feeling this will be fixed in time.

<img width="859" alt="Screen Shot 2023-01-12 at 8 34 38 PM" src="https://user-images.githubusercontent.com/7741/212231209-13540375-c9ad-4d2b-ae53-0995d0cf1d3f.png">

**Comment by baraeb92** [comment]
Yes, we experienced the same problem when upgrading to the Nextjs 13, even when we are not using appDir features.

**Comment by tomaszzmudzinski** [comment]
The same is happening for our page: https://shopetry.com

**Comment by teatr-wybrzeze-portal** [comment]
Looking forward to fixing this, it's quite a big hit on performance on my page too:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/104894435/219486387-99537aba-a294-42c5-bde4-6e8144636bcc.png">

**Comment by sroussey** [comment]
Looks like it is an issue with the type being octet-stream. The codebase has some references to a content type being set, but never consumed!

https://github.com/search?q=repo%3Avercel%2Fnext.js%20contentTypeHeader&type=code

**Comment by sroussey** [comment]
And since the content type is not getting passed through something like this is doing it, incorrectly:

https://github.com/vercel/next.js/blob/f3b231ccf1fb632640858de47a568892204bcb5c/packages/next/src/server/api-utils/node.ts#L227

**Comment by shuding** [comment]
This is now fixed in the latest canary, check out #45808. Here is it working after deployed too: https://streaming-zeta.vercel.app.
