### ISSUE TITLE
run error : error Command failed with signal "SIGBUS".

### ISSUE THREAD

**Issue by huadee1108** [vercel/next.js#43112]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

{
  "name": "soquest",
  "author": "pipi@SoQuest",
  "version": "0.1.0",
  "private": true,
  "license": "",
  "scripts": {
    "dev": "next",
    "turbo": "next dev --turbo",
    "build": "next build",
    "start": "next start",
    "prepare": "husky install",
    "lint": "eslint ./src/**/*.{ts,tsx}"
  },
  "lint-staged": {
    "./src/**/*.{ts,js,jsx,tsx}": [
      "eslint --ignore-path .gitignore --fix",
      "prettier --ignore-path .gitignore --write"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn lint"
    }
  },
  "dependencies": {
    "@emotion/react": "^11.10.4",
    "@emotion/server": "^11.10.0",
    "@emotion/styled": "^11.10.4",
    "@mui/icons-material": "^5.10.9",
    "@mui/material": "^5.10.8",
    "@reduxjs/toolkit": "^1.9.0",
    "@types/react-copy-to-clipboard": "^5.0.2",
    "ahooks": "^3.7.2",
    "axios": "^1.1.3",
    "bignumber.js": "^9.0.2",
    "ethers": "^5.6.4",
    "formik": "^2.2.9",
    "moment": "^2.29.3",
    "next": "latest",
    "nextjs-progressbar": "^0.0.14",
    "react": "^18.2.0",
    "react-copy-to-clipboard": "^5.1.0",
    "react-device-detect": "^2.2.2",
    "react-dom": "^18.2.0",
    "react-player": "^2.11.0",
    "react-redux": "^8.0.5",
    "react-toastify": "^9.1.1",
    "secure-random": "^1.1.2",
    "wagmi": "^0.6.7",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.1.2",
    "@commitlint/config-conventional": "^17.1.0",
    "@next/eslint-plugin-next": "^12.3.1",
    "@types/node": "^14.6.0",
    "@types/react": "^18.0.8",
    "@types/react-dom": "^18.0.3",
    "@typescript-eslint/eslint-plugin": "^5.38.1",
    "@typescript-eslint/parser": "^5.38.1",
    "babel-plugin-import": "^1.13.5",
    "babel-plugin-inline-react-svg": "^2.0.1",
    "eslint": "^8.14.0",
    "eslint-config-next": "latest",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^3.5.2",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.4.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "husky": "^8.0.1",
    "lint-staged": "^12.4.2",
    "npm-force-resolutions": "^0.0.10",
    "prettier": "^2.6.2",
    "typescript": "^4.8.4"
  }
}

### Describe the Bug

![image](https://user-images.githubusercontent.com/33452487/202832670-20a3551f-1742-4871-966f-a19d3415119c.png)

### Expected Behavior

run success

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

no link yet

### To Reproduce

no link yet

**Comment by balazsorban44** [comment]
Please only open an issue when you have a minimal reproduction.

> no link yet

is not something we can investigate.
