### ISSUE TITLE
When I try to use jsonwebtoken in middleware I get an error

### ISSUE THREAD

**Issue by maLikiz** [vercel/next.js#43115]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:           
      Platform: win32           
      Arch: x64                 
      Version: Windows 10 Pro   
    Binaries:                   
      Node: 19.0.1              
      npm: N/A                  
      Yarn: N/A                 
      pnpm: N/A                 
    Relevant packages:          
      next: 13.0.4-canary.5     
      eslint-config-next: 13.0.3
      react: 18.2.0             
      react-dom: 18.2.0   

### Describe the Bug

When I try to use jsonwebtoken in middleware I get an error: 
```bash
error - Error: The edge runtime does not support Node.js 'buffer' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at <unknown> (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:206)
    at Object.get (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:206:19)
    at eval (webpack-internal:///(middleware)/./node_modules/safe-buffer/index.js:12:12)
    at (middleware)/./node_modules/safe-buffer/index.js (evalmachine.<anonymous>:926:1)
    at __webpack_require__ (evalmachine.<anonymous>:37:33)
    at fn (evalmachine.<anonymous>:269:21)
    at eval (webpack-internal:///(middleware)/./node_modules/jws/lib/sign-stream.js:2:15)
    at (middleware)/./node_modules/jws/lib/sign-stream.js (evalmachine.<anonymous>:224:1)
    at __webpack_require__ (evalmachine.<anonymous>:37:33)
    at fn (evalmachine.<anonymous>:269:21)
    at eval (webpack-internal:///(middleware)/./node_modules/jws/index.js:2:18) {
  middleware: true
}
```

Code example:
```ts
// middleware.ts
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import jwt from 'jsonwebtoken';
import _config from './core/config';


// This function can be marked `async` if using `await` inside
export function middleware(request: NextRequest) {
  console.log('middleware');
  // const token = request.body.token || request.query.token || request.headers['x-access-token'];
  const token = 'testToken';
  console.log({ token });

  // decode token
  if (token) {
    // verifies secret and checks exp
    jwt.verify(token, _config.secret, function (err, decoded) {
      if (err) {
        return new NextResponse(
          JSON.stringify({ success: false, message: 'authentication failed' }),
          { status: 401, headers: { 'content-type': 'application/json' } }
        );
      }

      // request.decoded = decoded;
      NextResponse.next();
    });
  } else {
    // if there is no token
    // return an error
    return new NextResponse(
      JSON.stringify({ success: false, message: 'authentication failed' }),
      { status: 401, headers: { 'content-type': 'application/json' } }
    );
  }
}

//
export const config = {
  matcher: '/api/:path*',
};
```

This happens even if I just place `jwt` in the code without any methods

### Expected Behavior

I expect jsonwebtoken to work successfully in middleware

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/maLikiz/vercel-next-js-dnp5ov

### To Reproduce

Install node v19.0.1
Run the app
Click to "Test request" button
Look at server console:
![image](https://user-images.githubusercontent.com/4878139/202833895-18a546db-9a77-4d80-825c-fd1c32b1f94a.png)

**Comment by icyJoseph** [comment]
Hi,

The edge runtime doesn't implement a bunch of Node.js APIs, because they aim to be a minimal portable runtime. You can use `jose` instead, which is written to work in such portable runtimes, https://www.npmjs.com/package/jose:

For example, this snippets can get you going quickly.

```ts
import {SignJWT, jwtVerify, type JWTPayload} from 'jose';

export async function sign(payload: Token, secret: string): Promise<string> {
    const iat = Math.floor(Date.now() / 1000);
    const exp = iat + 60* 60; // one hour

    return new SignJWT({...payload})
        .setProtectedHeader({alg: 'HS256', typ: 'JWT'})
        .setExpirationTime(exp)
        .setIssuedAt(iat)
        .setNotBefore(iat)
        .sign(new TextEncoder().encode(secret));
}

export async function verify(token: string, secret: string): Promise<Token> {
    const {payload} = await jwtVerify(token, new TextEncoder().encode(secret));
    // run some checks on the returned payload, perhaps you expect some specific values

    // if its all good, return it, or perhaps just return a boolean
    return payload;
}
```

For more in-depth info, refer to: https://github.com/vercel/next.js/discussions/38227

**Comment by balazsorban44** [comment]
This is currently expected, and the error should explain the reason. `buffer` is a Node.js-specific module that the Edge runtime currently does not support. Consider using an alternative like [`jose`](https://www.npmjs.com/package/jose), which should work in the Edge runtime already.
