### ISSUE TITLE
[AppDir]: Link with prefetch={false} refresh page

### ISSUE THREAD

**Issue by domosedov** [vercel/next.js#43118]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: N/A
      pnpm: 7.16.1
    Relevant packages:
      next: 13.0.5-canary.2
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.110

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

See in reproduce

### Expected Behavior

No page refresh when Link clicked

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-9hjxty?file=app%2Flayout.tsx

### To Reproduce

Set prefetch={false} on Link component

**Comment by domosedov** [comment]
In stackblitz click "open in new tab"
<img width="227" alt="Снимок экрана 2022-11-19 в 11 48 39" src="https://user-images.githubusercontent.com/42298502/202842974-3f1321d3-a311-4e50-a0b3-1e1df6bb532e.png">
Click on links
<img width="131" alt="Снимок экрана 2022-11-19 в 11 48 47" src="https://user-images.githubusercontent.com/42298502/202842975-cf02ea46-c757-48c3-8d99-b95699aa93fc.png">

**Comment by Mistwell** [comment]
also has this trouble on next 13.0.5-canary.4

**Comment by switz** [comment]
Also seeing this on latest canary.

**Comment by actraiser** [comment]
This is still an issue on 13.1.6-canary.1 - it would be great if this problem would be adressed soon.

Greets
-act

**Comment by amannn** [comment]
The reproduction now works in Next.js 13.4, but it doesn't if you have the whole app nested in a folder like `app/[locale]` ([repro](https://stackblitz.com/edit/vercel-next-js-xum9jh?file=app%2F[locale]%2Fpage.tsx)).

The workaround is adding a root layout, even if it just passes `children` through:

```tsx
// app/layout.tsx
import {ReactNode} from 'react';

type Props = {
  children: ReactNode;
};

// Even though this component is just passing its children through, the presence
// of this file fixes an issue in Next.js 13.4 where link clicks that switch
// the locale would otherwise cause a full reload.
export default function RootLayout({children}: Props) {
  return children;
}
```

**Comment by p00000001** [comment]
> The reproduction now works in Next.js 13.4, but it doesn't if you have the whole app is nested in a folder like `app/[locale]` ([repro](https://stackblitz.com/edit/vercel-next-js-xum9jh?file=app%2F%5Blocale%5D%2Fpage.tsx), [standalone demo](https://vercelnextjsxum9jh-e5qj--3000--9c984a48.local-credentialless.webcontainer.io/en)).
> 
> The workaround is adding a root layout, even if it just passes `children` through:
> 
> ```tsx
> // app/layout.tsx
> import {ReactNode} from 'react';
> 
> // Even though this component is just passing its children through, the presence
> // of this file fixes an issue in Next.js 13.4 where links with `prefetch={false}`
> // would otherwise cause a full reload.
> export default function RootLayout({children}) {
>   return children;
> }
> ```

I have this exact issue in Next.js 13.4 using:

-  _app/[locale]/layout.js_.
-  _app/[locale]/.../page.js_.

However, unfortunately the above solution didn't solve it for me. Initial server load works as expected with both being called. Thereafter:

When clicking a link with `prefetch={true}`, only _app/[locale]/.../page.js_ is called/prefetched and then loads from the local cache as expected.

When clicking a link with `prefetch={false}`, both _app/[locale]/layout.js_ and _app/[locale]/.../page.js_ are called. On subsequent visits, they're loaded from the cache without being called.

**Comment by samcx** [comment]
@domosedov Just tested this locally with the latest stable v15 and I am not seeing this issue!
