### ISSUE TITLE
[TypeError: adapter is not a function] - fetching content in Contenful on a Server Component

### ISSUE THREAD

**Issue by addsac** [vercel/next.js#43120]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.5-canary.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.110∑

### How are you deploying your application? (if relevant)

still in local

### Describe the Bug

When I try to fetch content in Contentful on a fresh Next.js 13 application, i get this error: 
[TypeError: adapter is not a function]

The files I use to describe the error are: 
- app/components/BlogPreview.jsx
- util/contentfulBlogPosts.js

### Expected Behavior

I should be able to get the results of the api call

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/addsac/PegasoDigitalStudio

### To Reproduce

Clone the rep, run on terminal: "npm run dev", open localhost:3000.

**Comment by balazsorban44** [comment]
I cannot run the reproduction as it requires an access token, as well as there are unrelated module import issues:
![image](https://user-images.githubusercontent.com/18369201/203058661-1bb69fa4-0989-4fc0-8690-ec9cc3037fbe.png)


Please fix the reproduction by removing unnecessary code that does not contribute to the issue and removing requirements for auth, so we can investigate.
