### ISSUE TITLE
revalidate() fails on static /app pages in development mode

### ISSUE THREAD

**Issue by dardanbujupaj** [vercel/next.js#43132]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.16.0
    Relevant packages:
      next: 13.0.5-canary.2
      eslint-config-next: 13.0.5-canary.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Safari Version 16.1 (18614.2.9.1.12)

### Describe the Bug

When manually revalidating a static `/app` page using `NextApiResponse.revalidate()` in development mode (`next dev`) an error `Failed to revalidate /: Invalid response 200` gets thrown.

`revalidate()` works correctly on:
* if next is run with `next build && next start`
* if a dynamic page (e.g. `/[name]`) is revalidated

This is a bit confusing when running in development.

### Expected Behavior

`NextApiResponse.revalidate()` should always work on static pages.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/dardanbujupaj/next-revalidate-reproduction

### To Reproduce

1. Run app with `npm run dev`
  * goto http://localhost:3000 and press revalidate -> fails (unexpected)
  * goto http://localhost:3000/dynamic and press revalidate -> succeds (expected)

2. Run app with `npm run build && npm run start`
  * goto http://localhost:3000 and press revalidate -> succeds (expected)
  * goto http://localhost:3000/dynamic and press revalidate -> succeds (expected)

**Comment by dardanbujupaj** [comment]
I did some digging and found the difference between running with `dev` and `build/start`.

At this line the in prod `isSSG` gets set for static sites, as they're in the prerender manifest, which isn't available in dev.
https://github.com/vercel/next.js/blob/ecfd2f4cd6a1c3f6bc3cd1cca6b62a3cb705a4e2/packages/next/server/base-server.ts#L1041

**Comment by dineshyadav3169** [comment]
any update on this?

**Comment by daszkowski** [comment]
Same problem? 🤔  https://github.com/vercel/next.js/issues/48771
