### ISSUE TITLE
blog-starter doesn't work with `--turbo`, process.cwd doesn't return root dir

### ISSUE THREAD

**Issue by TommasoAmici** [vercel/next.js#43135]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 9.1.2
      Yarn: 1.22.19
      pnpm: 7.16.0
    Relevant packages:
      next: 13.0.5-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

blog-starter

### Describe the Bug

`process.cwd()` doesn't return the root of the project, but a path within `.next/server`

```

Error rendering page
Message

Error: ENOENT: no such file or directory, scandir '/Users/tommi/dev/misc/blog-starter/.next/server/pages/_posts'
  at Object.readdirSync (node:fs:1451:3)
  at getPostSlugs (/lib/api.ts:8:12)
  at Module.getAllPosts (/lib/api.ts:41:16)
  at getStaticProps (/pages/index.tsx:44:31)
  at Object.renderToHTML (node_modules/.pnpm/next@13.0.5-canary.2_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/render.js:384:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async runOperation (/pages/index.tsx/server-renderer.tsx:148:4)
  at async (/pages/index.tsx/server-renderer.tsx:49:17)

Exit status

exit status: 1
```

### Expected Behavior

I suppose `process.cwd` should be the same as usual even when using `--turbo`

### To Reproduce

Run `blog-starter` example with `--turbo`

**Comment by ForsakenHarmony** [comment]
Sorry for the late response, but is this still happening?

I think I fixed this a while ago

**Comment by ForsakenHarmony** [comment]
works for me now, so I'm gonna close this

**Comment by Chrysippus** [comment]
> Sorry for the late response, but is this still happening?
> 
> I think I fixed this a while ago

Yes, I think this issue is fixed, as far as I can tell.
