### ISSUE TITLE
[NEXT-811] [appDir] `next/image` with `priority` doesn't generate `<link rel="preload" ...>` tag.

### ISSUE THREAD

**Issue by kvnang** [vercel/next.js#43134]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 18.10.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.13.0
    Relevant packages:
      next: 13.0.5-canary.2
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When using `pages` directory, the `<Image />` component from `next/image` with `priority` prop will generate a `<link rel="preload" as="image" ... />` on the `<head />`. But this is not the case when using `app` directory.

I believe this is because, currently, the `<link>` tag is injected using `next/head` on a client component ([reference](https://github.com/vercel/next.js/blob/ecfd2f4cd6a1c3f6bc3cd1cca6b62a3cb705a4e2/packages/next/client/image.tsx#L899-L912)). This doesn't work given the server component setup.

### Expected Behavior

`<link rel="preload" as="image" ... />` will also be generated for priority `<Image />` when using `app` directory.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/kvnang/next-image-preload

### To Reproduce

```bash
git clone https://github.com/kvnang/next-image-preload
cd next-image-preload
npm run build && npm run start
```

Under `/app/page.tsx`, the `<Image />` component with src `vercel.svg` has a `priority` prop set to `true`, and thus should produce `<link rel="preload" />` tag. But it doesn't in this case.

<sub>[NEXT-811](https://linear.app/vercel/issue/NEXT-811/[appdir]-nextimage-with-priority-doesnt-generate-link-rel=preload-tag)</sub>

**Comment by kvnang** [comment]
Possible solutions:
- Using ReactDOM's float `preload()` (like in `<Script />` component), but it doesn't support certain attributes like `imgsrcset`, for example.
- Making a server component version of `<Image />` component, and just inlining `<link>` tag, which will be picked up by the `<head>`. But this seems quite destructive ...

**Comment by transitive-bullshit** [comment]
I'm seeing this as well, though I'm also seeing this with the new `next/image` when reverting to use `pages/`.

**Comment by sckimynwa** [comment]
Same Issue Here.
I'm using vercels official [next 13 demo](https://vercel.com/solutions/nextjs) which uses next 13.0.7-canary.4 as a dependency

in this demo, I created new page and add Client Component to Use `next/image`

<img width="251" alt="image" src="https://user-images.githubusercontent.com/30401400/209531882-382838c0-8ce4-4a72-8af1-c6fcad93ddd1.png">

``` typescript
import Test from './child.client';

export default async function Page() {
  return (
    <div className="space-y-8">
      <div className="space-y-4">
        <h1 className="text-xl font-medium text-gray-400/80">
          Next Image Test
        </h1>
        <Test />
      </div>
    </div>
  );
}

``` typescript
import Image from 'next/image';

const Test = () => {
  return (
    <div className="space-y-2">
      <div className="flex space-x-2">
        <Image
          src="/prince-akachi-LWkFHEGpleE-unsplash.jpg"
          className="rounded-full"
          width={300}
          height={300}
          alt="User"
        />
        <Image
          priority
          src="https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?cs=srgb&dl=pexels-pixabay-45201.jpg&fm=jpg"
          className="rounded-full"
          width={300}
          height={300}
          alt="User"
        />
      </div>
    </div>
  );
};

export default Test;

```

in the second image, with `priority` props, next should generate link tag with preload as image, but nothing happend in the document's head tag. I think injecting the preload tag is not working in thie version 🤔 

<img width="757" alt="image" src="https://user-images.githubusercontent.com/30401400/209532118-e6a296bd-869f-444b-9b51-a317b9b55bae.png">

**Comment by michaelyang** [comment]
Same issue here, not seeing the preload being generated. The priority prop seems to be only be removing the lazy loading portion.

**Comment by steve-marmalade** [comment]
@balazsorban44 , regarding:
> Thanks, this is currently expected, as head handling is still a work in progress: https://beta.nextjs.org/docs/app-directory-roadmap#supported-and-planned-features, which next/image relies on to push a preload tag to the DOM.

Has anything changed in this regard with all of the effort around `head.js` / `metadata` that went into `13.2` ?

**Comment by steve-marmalade** [comment]
The latest Beta docs now include a section on [Resource hints](https://beta.nextjs.org/docs/api-reference/metadata#resource-hints), and it looks like support for `next/image` should be added automatically for client components:

> These methods are currently only supported in Client components.
> Next.js in-built features such as next/font, next/image and next/script automatically handle relevant resource hints.

However, when I updated to 13.3 I am not seeing these tags in the `<head>` of the document.

Should I create a separate repro for this? Or should we be setting these manually as shown in e.g. [this comment](https://github.com/vercel/next.js/issues/47399#issuecomment-1490175982)?

**Comment by styfle** [comment]
This issue is that browsers like [Safari](https://bugs.webkit.org/show_bug.cgi?id=231150) that don't support `imagesrcset` will fallback to `href`. 

https://github.com/vercel/next.js/blob/af49d5098b050698661fb1f1787870fb554e44f8/packages/next/src/client/image.tsx#L959-L963

The new `ReactDOM.preload()` requires a `href` and that could cause Safari to be _slower_ by preloading the wrong image, so we need a better solution.

**Comment by mrgnou** [comment]
App dir is now Stable but this issues remains on next 13.4.1. It drastically cripples LCP performances :(

**Comment by ddegooijer** [comment]
Also an issue here, lcp image has fetchpriority but no preload tag is generated.

**Comment by Jarpiino** [comment]
still apparent in 13.4.5 :(

**Comment by gauravsaini964** [comment]
Any ETA on when this fix is landing in canary? I see huge drop in LCP performance ~1 second.

**Comment by Jarpiino** [comment]
Have you tried to statically import your images?
import sample_image from "public/images/sample_image.jpg"
And then applying the priority=true?

<Image
Src=sample_image
Priority=true
/>

**Comment by jep-a** [comment]
Looks like if you need it now, you can update to 13.4.9 and use getImgProps from https://github.com/vercel/next.js/pull/51205 and use that to get the generated srcset and sizes from your image and feed it into ReactDOM.preload

Just wrote this without testing, but this is a simplified version of what I did in real code
```jsx
import Image, { unstable_getImgProps as getImgProps } from 'next/image';
import { preload } from 'react-dom';

const ImagePreload = ({imgProps}) => {
  const preloadImgProps = getImgProps(imgProps)
  
  preload(preloadImgProps.props.src, {
    as: 'image'
    imageSrcSet: preloadImgProps.props.srcSet,
    imageSizes: imgProps.sizes
  })
  
  return (
    <Image {...imgProps} />
  )
}
```

But looks like its almost fixed anyways with this PR https://github.com/vercel/next.js/pull/52425

**Comment by gauravsaini964** [comment]
Please check #52995 .
