### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by rdyar** [vercel/next.js#43143]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.5-canary.2
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I just updated an existing Next app to the latest next 13 and in the console when I run yarn dev I see an error:

```
TypeError: Cannot read properties of null (reading 'length')
    at eval (webpack-internal:///./node_modules/next/dist/client/dev/error-overlay/hot-dev-client.js:262:55)
```

I don't think this is coming from my code as I only use length in one place and it should be ok.

I googled it and came up with a few people on SO that have the issue (in the last week or so) but I don't see any thing in here about it: https://stackoverflow.com/questions/74415937/nextjs-typeerror-cannot-read-properties-of-null-reading-length

Nothing seems broken, I just see it in the console.

### Expected Behavior

no error message in console

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

n/a

### To Reproduce

for me it is simply doing yarn dev,

**Comment by icyJoseph** [comment]
I somehow think this is a minification issue, because when I looked at the code there was a guard for the length check closest to the offending line, on the source code, but not in the minified code... it's a bit hard to trigger, usually you need to make a syntax error on a page, save, and fix the error to trigger it, but it doesn't always happen to me.

**Comment by jarradxz** [comment]
Thanks for fixing. I also just noticed this locally too. 

https://github.com/vercel/next.js/commit/ed2aa9fd75fa2b82de30261d6d3abaa3f7aad55f?diff=unified#diff-e676ab1125f4857b4e42850e2f067267f5fb2fbbf7464b88e70a7399d9a1940bR179 looks like the line that is most critical in this fix to me.
