### ISSUE TITLE
13.0.4, regression when SC uses cookies - 

### ISSUE THREAD

**Issue by icyJoseph** [vercel/next.js#43148]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
next.js/demo-app on  next-13-css-modules [!⇡] via  v16.14.0 at  took 28s
❯ npx next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.11.0
    Relevant packages:
      next: 13.0.5-canary.3
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

In versions 13.0.1, 2 and 3, using `import { cookies } from "next/headers";` made the page behave dynamically. Starting with `13.0.4` the page becomes static. This has been observed at build time. 

### Expected Behavior

Pages that use `import { cookies } from "next/headers";` should run on demand. Or perhaps that's not the expected behavior?

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/icyJoseph/next-js-react-gbg/tree/next-13-css-modules/demo-app

### To Reproduce

Build the app, go to `capture` click on the pokeball, then navigate to `collection`, the pokemon you interacted with should show, but it won't.

Reload the page, now the pokemon shows.

**Comment by samcx** [comment]
@icyJoseph Just checking in on this, and can confirm this is not an issue with the latest stable v15!
