### ISSUE TITLE
Docs: The sample code for "(beta)api-reference/notfound" does not work correctly.

### ISSUE THREAD

**Issue by GrowUp-Haruno** [vercel/next.js#43175]
### What is the improvement or update you wish to see?

Because fetchUsers(id) in the description code returns an empty object even if communication fails, "if (!user)" cannot execute "notFound()".

### Is there any context that might help us understand?

If use res.ok to return undefined, etc., you can execute "notFound()".
```tsx
async function fetchUsers(id) {
  const res = await fetch('https://...');
  if (!res.ok) return undefined;
  return res.json();
}
```

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/notfound

**Comment by balazsorban44** [comment]
Thanks for reporting, we will evaluate your feedback! You can leave feedback on the beta docs directly on the page, I've now done so with this issue. :+1: https://beta.nextjs.org/docs/api-reference/notfound#thread-id=JpFp1 In the future, you can just mark any text on the page and leave a comment. :+1:
