### ISSUE TITLE
next/image swaping cached images

### ISSUE THREAD

**Issue by Sooraj-Baburaj** [vercel/next.js#43189]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
    Relevant packages:
      next: 12.2.2
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome, Firefox, Safari

### Describe the Bug

While in production, cached images are loaded incorrecly by next's Image component. The right src attribute is being assigned but the image shown in the browser is incorrect. While opening the image link it shows the expected image. 
For Example, There are two images, A & B in the webpage, two different links are being appended to the img element but both images being printed are the same.  

Similar issue [here](https://github.com/vercel/next.js/issues/23518), but the latest canary version and sharp didn't help.

### Expected Behavior

Images should be loading correctly.

We all know Next Js is an amazing framework. I've developed multiple websites using Next Js and this is the first time I'm facing such an issue. 

Take a look at the screenshot below: 

![Screenshot from 2022-11-21 18-39-00](https://user-images.githubusercontent.com/91947818/203065160-fa71eaa6-2a40-47fe-acf7-690d5553f220.png)

The images from above the image are supposed to be two different images. 

![imageOne](https://user-images.githubusercontent.com/91947818/203065434-238d5549-0e98-4ea7-a9db-68311e19d64f.jpg)
![imageTwo](https://user-images.githubusercontent.com/91947818/203065442-adb0e3c8-9b02-4b81-8dd8-542f0d36948c.jpg)

But these images with two different urls are shown as one. 

![imagefullview](https://user-images.githubusercontent.com/91947818/203065567-628ca998-feb6-4ac3-9666-6846482a285d.jpg)

While opening the second image in a new tab, it shows the correct image.

**Comment by balazsorban44** [comment]
Hi, I noticed that the reproduction is using [`next@10`](https://nextjs.org/blog/next-10) (2 years old release), and we would like to ask you to verify if the issue is still present `next@canary`, since any issues might have already been fixed since then.

**Comment by Sooraj-Baburaj** [comment]
Thank you for your help! Using `next@12.3.2-canary.30` fixed the issue.
