### ISSUE TITLE
Type error: 'PageComponent' is declared but never used

### ISSUE THREAD

**Issue by kaname-png** [vercel/next.js#43195]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information
```
 ⚡nekodex ❯❯ pnpm exec next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 2 19:50:29 UTC 2022
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: 3.2.4
      pnpm: 7.13.5
    Relevant packages:
      next: 13.0.5-canary.3
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

### What browser are you using? (if relevant)

Microsoft Edge 107.0.1418.52

### How are you deploying your application? (if relevant)

next build

### Describe the Bug

When I try to compile my application with "next build", eslint complains about "PageComponent" being declared but never used.

I looked where that declaration was because I didn't have any variable with that name, then I see that in the "types" folder inside the "next" folder that is autogenerated by next.

![image](https://user-images.githubusercontent.com/56084970/203118400-778b4f2b-0827-41f9-8f12-41583a4635f7.png)

![image](https://user-images.githubusercontent.com/56084970/203120954-63c5cec1-0026-4ff5-886f-7ae637716612.png)

![image](https://user-images.githubusercontent.com/56084970/203120861-b2b32b13-f2ff-437f-9696-5579b3fb861c.png)

### Expected Behavior

A successful compilation with no slint errors.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

None.

### To Reproduce

1. Create a nextjs project
2. Run `next build`

**Comment by balazsorban44** [comment]
Could you attach a reproduction? I cannot reproduce with a simple `pnpm create next-app --experimental-app`. The `.next` directory should not be checked by the linter by default. :thinking:

**Comment by kaname-png** [comment]
@balazsorban44 here is the reproduction: https://codesandbox.io/s/practical-thunder-zywnfb?file=/README.md

**Comment by ryohlan** [comment]
It occurs by adding '"noUnusedLocals": true' in tsconfig.json.
