### ISSUE TITLE
Layout type incorrect for layouts with dynamic parallel routes

### ISSUE THREAD

**Issue by bigs** [vercel/next.js#43199]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.14.2
    Relevant packages:
      next: 13.0.4-canary.3
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Version 107.0.5304.110 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When taking advantage of [dynamic parallel routes](https://nextjs.org/blog/layouts-rfc#dynamic-parallel-routes), wherein Next injects a prop into a layout for each leaf segment, running `next build` triggers a TypeScript error:

```
Type error: Layout "app/redacted/[slug]/layout.tsx" does not match the required types of a Next.js Layout.
  Invalid configuration:
    The exported layout component isn't correctly typed.
```

### Expected Behavior

Next should account for properties it injects into a layout's props when type checking layouts using dynamic parallel routes. In my scenario, `next build` should not error. 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-osqgfu?file=app/@test/page.tsx

### To Reproduce

In the linked stackblitz environment, you can run the development server and see that the layout renders as expected, injecting the page from the dynamic parallel route `@test` into the layout.

When you stop the dev server and attempt a `next build` you will see the build error pertaining to the restrictive TypeScript typings.

**Comment by axelvaindal** [comment]
I've the exact same issue, but only for one of my third parallel route group.

Each route group has exactly the same structure, I've created it 3 times as I need different layouts.
The first two works fine, but the last one is not working and on build it provided the same error you mention here.

When I `npm run build` locally, no error though.
As it was blocking deployment, I've force the build to pass by ignoring typescript errors in build time, but it's a real annoyance.

@bigs @balazsorban44 Do you have some insight on why the `typescript` build is failing only for this route group (cf image) ?

The `publish` route group is the only one to fail at build time, the two others work like a charm in production.
When deployed in production, the compiled code work as expected so I assume it's a typescript configuration problem, but is there any way we can help to get rid of it ? 🙏

<img width="510" alt="image" src="https://github.com/vercel/next.js/assets/11026659/de4707f5-cb84-4c3c-88be-a815bfac7db8">

<img width="909" alt="image" src="https://github.com/vercel/next.js/assets/11026659/e8782d8e-f71e-40a7-97b5-ed11cd11914d">

**Comment by bigs** [comment]
Best as I could ascertain at the time, Next's compiler was generating bad TypeScript definition files (not taking into account the components injected as props) which lead to it not compiling. Would require a change in Next, I believe.

**Comment by ariannargesi** [comment]
Same issue here

**Comment by samcx** [comment]
@bigs I am not able to replicate this stale issue with the latest stable v15, so will be moving forward with closing it!

**Comment by bigs** [comment]
Great to hear, thanks.
