### ISSUE TITLE
NextJs export dynamic='force-dynamic' option builds a static page

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#43191]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Mon Nov 21 2022 12:09:02 GMT+0100 (heure normale d’Europe centrale)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

The option to export a page as dynamic do not work on the latest release of nextjs, even when a page is configured with `dynamic='force-dynamic'`, at build time it stills consider it as a static page.

### Expected Behavior

As per the documentation, the page should be considered as dynamic and searchParams should work

> 'force-dynamic': Force dynamic rendering and dynamic data fetching of a layout or page by disabling all caching of fetch requests and always revalidating. This option is equivalent to:

getServerSideProps() in the pages directory.
Setting the option of every fetch() request in a layout or page to { cache: 'no-store', next: { revalidate: 0 } }.
Setting the segment config to export const fetchCache = 'force-no-store'

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/nextjs-czq25n?file=app%2Fpage.tsx,app%2Fproducts%2Fpage.tsx

### To Reproduce

Go to the reproduction link and try to run `npm run build`, first you will have this output : where `/` and `/products` page are marked as dynamic but nextjs consider them as static pages. 

```
Route (app)                                Size     First Load JS
┌ ○ /                                      0 B                0 B
├ ○ /products                              148 B          65.9 kB
└ λ /products/[id]                         148 B          65.9 kB
+ First Load JS shared by all              65.8 kB
  ├ chunks/17-11f964cd932290b4.js          64 kB
  ├ chunks/main-app-f7991bdf5a7d528d.js    200 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB
```

To try further, you could go to `/` or `/products` and pass queryParams, it isn't picked up by nextjs.

**Comment by mrob11** [comment]
👍🏻 came to report this same issue and found this at the top. Bit of a different scenario for me as my project does not use `fetch` at all server-side but am using Prisma ORM. I'll work on a reproduction that I can post and update my comment.

**Comment by gfortaine** [comment]
https://github.com/vercel/next.js/issues/42856

**Comment by Fredkiss3** [comment]
Upgraded to `next@13.1.0` and the issue seem to have been fixed.
