### ISSUE TITLE
[turbo] complied code not correct

### ISSUE THREAD

**Issue by liaoyinglong** [vercel/next.js#43210]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.17
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.5-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

**the source code:**
https://github.com/d3/d3-selection/blob/main/src/select.js#L6
<img width="864" alt="image" src="https://user-images.githubusercontent.com/23382699/203200688-e3d7e85b-9abf-48aa-b7eb-edb3c8f94139.png">

**in normal mode is corre:**
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/23382699/203200339-79c8f572-b7f8-4c9a-9b7e-16bb687f2ad7.png">
after run code:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/23382699/203205814-cd1da59c-404a-4a99-a6d6-491f7efaf94c.png">

**in turbo complier is not correct:**
<img width="1745" alt="image" src="https://user-images.githubusercontent.com/23382699/203200636-e38f5937-563d-4069-823d-639775757f0a.png">
after run code:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/23382699/203205243-28637e0f-26f7-4c09-a3f9-693a27696c4a.png">

### Expected Behavior

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/23382699/203200339-79c8f572-b7f8-4c9a-9b7e-16bb687f2ad7.png">

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/liaoyinglong/next-turbo-bug

## correct

1. `npm run dev`
2. see devtools output

## error

1. `npm run dev:turbo`
2. see devtools output

**Comment by padmaia** [comment]
Seems fixed testing on most recent canary
