### ISSUE TITLE
[swc] imports are stripped when used only in a satisfies expression

### ISSUE THREAD

**Issue by andparsons** [vercel/next.js#43220]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.5-canary.4
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

It seems that the values of imports used solely inside a satisfies expression fail to get included, throwing an error like 
```
ReferenceError: *importName* is not defined
```

Using the import elsewhere than inside the satisfies expression will resolve the import.

Removing the satisfies keyword and type also allows for the import to resolve.

Looks like this issue was introduced in v13.0.3-canary.4 with an update to swc. 
v13.0.3, v13.0.4 and the latest canary still persist this issue.

### Expected Behavior

Much like removing the satisfies keyword and type, or using the import elsewhere than this expression, the use of the import inside the satifies expression should still be included.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/nextjs-xhfh9z?file=pages%2Findex.tsx%3AL28

### To Reproduce

Swapping between using an import inside the satifies expression

```tsx
import { revalidate } from '../lib/next';

export const getStaticProps = function () {
  return {
    revalidate,
    props: {
      page: {a:1},
    },
  };
} satisfies GetStaticProps;
```

and the same code without the keyword and type and restarting the dev server will show the error only occurring as mentioned

```tsx
import { revalidate } from '../lib/next';

export const getStaticProps = function () {
  return {
    revalidate,
    props: {
      page: {a:1},
    },
  };
};
```

**Comment by andparsons** [comment]
Still an issue with v13.0.6-canary.0

**Comment by kdy1** [comment]
Closing as fixed on canary
![image](https://github.com/vercel/next.js/assets/29931815/85bc447e-bc26-480f-95f2-08e4b4117836)
