### ISSUE TITLE
Client component pages are not cached.

### ISSUE THREAD

**Issue by pawanbana** [vercel/next.js#43233]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.4
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I am using nextjs 13.0.4 and for pages which are client component they are not cached instead we make fetch call to server even though they are simple functional component without API calls.

request call is made every time user navigate to any page any number of times. 

I tried `dynamic` and everything but still it is not working

Note: 
- No dyamic routes are there.
- No data fetching
- Just client components.

### Expected Behavior

It should be cached and no request should be made if user revisits the page.
did run same code in v12 it is working as expect no extra call is made to server if user navigates to any page.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

Na

### To Reproduce

Build an app
 - make an next app with next-create-app
 - Make multiple pages inside app dir
 - Link them to each other and navigate using useRouter.
 
  e.g: 
  landing page component: 
  ```
  'use client';
 
import React from 'react';
import styles from './page.module.css'
import { useRouter} from 'next/navigation';

export default function Home() {
  let router = useRouter();
  return (
    <div className={styles.container}>
      <main className={styles.main}>
        <h1 className={styles.title} onClick={() => {
          router.push('/test')
        }}>
          Welcome to 
        </h1>
      </main>
    </div>
  )
}
```

another page component
  ```
  'use client';
 
import React from 'react';
import styles from '../page.module.css'
import { useRouter} from 'next/navigation';

export default function Home() {
  let router = useRouter();
  return (
    <div className={styles.container}>
      <main className={styles.main}>
        <h1 className={styles.title} onClick={() => {
          router.push('/')
        }}>
          Welcome to 
        </h1>
      </main>
    </div>
  )
}
```

**Comment by balazsorban44** [comment]
Hi, it's unclear if you are even using `app/` directory since you mention v12 which does not support client components. Could you add a reproduction so we can investigate?

**Comment by pawanbana** [comment]
I am using `app`  directory, what I meant with v12 is that in v12 we had this caching on client side but on v13 We make fetch call for each component while it should be cached if user revisits the same page.

**Comment by sawik-code** [comment]
if you need cliend side cashing use fetch library like swr or react query

**Comment by pawanbana** [comment]
<img width="553" alt="Screenshot 2022-11-22 at 6 30 27 PM" src="https://user-images.githubusercontent.com/31897605/203320163-898cf44b-3a69-4fac-8059-03dd63a09d0a.png">

When I switch to two pages simultaneouly these calls are made to fetch the page data but  I didn't add any API call or anything in the react component. it is not caching the pages component.

**Comment by pawanbana** [comment]
@balazsorban44 Added reproduce steps 🙇

**Comment by sawik-code** [comment]
Use next/link insted and put navigation in your layout component

**Comment by balazsorban44** [comment]
As suggested above, you should definitely use `next/link` and not `h1` for links for accessibility reasons whenever possible, but indeed, there seems to be a mismatch between `router.push` and `Link#href` behavior, let me look into this.

**Comment by balazsorban44** [comment]
So I checked, and this is expected. `router.push` does not do prefetching (thus caching) by default, so you need to apply it with `router.prefetch`. Ie:

```js
onClick={() => {
  router.prefetch("/")
  router.push("/")
}}
```

This will cache the response for subsequent navigations. `Link` navigations do this already and again, is the recommended prior way for navigations.

Docs: https://beta.nextjs.org/docs/routing/linking-and-navigating#conditions-for-soft-navigation

**Comment by pawanbana** [comment]
@balazsorban44  I did this implementation and it solved the prefetching issue but now if I am using the Link component, and If I want to do some business logic based on the current route I need to use `usePathName` which is doesn't get updated in realtime with Link component is there another API I can use or is it not ideal to use `Link` component with `usePathname` hook? and instead use the `useRouter` ?
