### ISSUE TITLE
[appDir] Catching and wrapping, or not rethrowing, errors from fetch(), cookies(), or headers() causes dynamic page to be rendered statically.

### ISSUE THREAD

**Issue by M0lion** [vercel/next.js#43245]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.5-canary.4
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

Several of my pages are doing dynamic fetches inside try blocks. When I catch the errors I check if it's a specific error that should be handled in some way, otherwise i wrap it in a new Error with an informative error message and the cause set to the original error and throw that.

This works fine when running `next dev`, but when building with `next build` it fails while trying to statically render these pages. The pages should not be statically rendered as they're using dynamic fetches. This seems to be happening because I am wrapping the original error so that next doesn't see it and thus doesn't know that the page should be dynamically rendered.

### Expected Behavior

I expect that my app builds successfully with my pages with dynamic fetches rendering dynamically.

Otherwise I would expect this behavior to be documented, probably [here](https://beta.nextjs.org/docs/rendering/static-and-dynamic-rendering), along with some other way to solve this. Maybe some way to check for DynamicServerErrors, or some way to force dynamic rendering.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/M0lion/next-repro

### To Reproduce

Run `npm ci` and `npm run build`.

**Comment by samcx** [comment]
@M0lion Since this issue is stale and the <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> does not show App Router being used, I will move forward with closing this!
