### ISSUE TITLE
Server component rendered twice with getStaticParams

### ISSUE THREAD

**Issue by lsvargas** [vercel/next.js#43254]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.0.2
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

The Server Component renders twice in production environment when defining `generateStaticParams`, it is also called twice in the build process.
This is basically the code I used to showcase the behaviour:
```javascript
export async function generateStaticParams() {
  return [{ id: "1" }, { id: "2" }]
}

export const revalidate = 5

async function Day({ params }) {
  const { id } = params

  console.log("id: ", id)

  return (
    <div>
      <h1>Component</h1>
    </div>
  );
}

export default Day
```

Another thing to notice is that each time the component seems to receive different `params` for the same `id`

### Expected Behavior

Server Component rendering only once

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/lsvargas/nextjs13-bug

### To Reproduce

1) Clone the [repo](https://github.com/lsvargas/nextjs13-bug)
2) Run `yarn build && yarn start`
2) Click the button to navigate to the url and see the console

**Comment by javmurillo** [comment]
Since you have two params, I think it is normal the server will render twice, one for each path (id 1 and id 2).

**Comment by varzy** [comment]
Same issue.
