### ISSUE TITLE
head.js doesn't get searchParams

### ISSUE THREAD

**Issue by itrelease** [vercel/next.js#43269]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: 7.9.5
    Relevant packages:
      next: 13.0.4
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

It seems `head.js` files doesn't get `searchParams` in props

### Expected Behavior

I would expect to get `searchParams` in props for `head.js` files the same way we have it in `page.js` files

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-zykntz?file=app/head.tsx

### To Reproduce

Check terminal panel

**Comment by leerob** [comment]
`generateMetadata` replaces this: https://beta.nextjs.org/docs/api-reference/metadata#generatemetadata-function
