### ISSUE TITLE
useSelectedLayoutSegment(s) hooks both return no data

### ISSUE THREAD

**Issue by NuroDev** [vercel/next.js#43279]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 13.0.4
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Microsoft Edge Version 107.0.1418.56 (Official build) (arm64)

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

Currently when trying to use either [useSelectedLayoutSegment](https://beta.nextjs.org/docs/api-reference/use-selected-layout-segment) or [useSelectedLayoutSegments](https://beta.nextjs.org/docs/api-reference/use-selected-layout-segments) hooks they both return no data.

 - `useSelectedLayoutSegment` returns `null` at all times
 - `useSelectedLayoutSegment` returns an empty array

### Expected Behavior

According to [the docs](https://beta.nextjs.org/docs/api-reference/use-selected-layout-segment) they should be returning both either `string | null` & `Array<string>` respectively

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/nextjs-zbazdc?file=app/(app)/[slug]/layout.tsx

### To Reproduce

Follow (beta) Next.js documentation on how to use the hooks, primarily via creating a segment of any kind, & attempt to use the hooks in a client component or layout respectively.

**Comment by NuroDev** [comment]
Could be related to #42300

**Comment by Fredkiss3** [comment]
This is definitely a regression since in precedent versions it worked, as a workaround for now you can use `usePathname` as a replacement.

**Comment by balazsorban44** [comment]
This is expected, as of https://github.com/vercel/next.js/pull/42299

**Comment by abhilashlr7** [comment]
> This is expected, as of #42299
> 
> From the documentation:
> 
> > useSelectedLayoutSegment is a hook that can only be used inside a [Client Component](https://beta.nextjs.org/docs/rendering/server-and-client-components). You can use it in a client component that is imported into a layout. It returns a string of the active segment or null if one doesn't exist.
> 
> See: https://beta.nextjs.org/docs/api-reference/use-selected-layout-segment

I think in the repro link, the component is marked as client component and yet the values aren't displayed. The same happens in my project where a client component doesn't log the output of ` useSelectedLayoutSegment();` as expected but it displays `null`

**Comment by Fredkiss3** [comment]
@abhilashlr7 , what is said in the docs is that this hook has these constraints : 

- You can't access the selected segment from within a server component
- You can't access the selected segment from a page, or directly from a layout
-  You can only access the segment if `useSelectedLayoutSegment` or `useSelectedLayoutSegments` is called from a **client component** that is imported by a **layout**. 
- `useSelectedLayoutSegment` and `useSelectedLayoutSegments` will return `null` and `[]` respectively when called from a segment that is at the same segment level that the layout from within it's imported 

You can see more in the docs : https://beta.nextjs.org/docs/api-reference/use-selected-layout-segment#examples

**Comment by Fredkiss3** [comment]
Im my opinion, this information is very important as it can easily lead to confusion, it should be highlighted in the docs or at least made in a different section.

Kind of like the new react beta docs do : 

<img width="907" alt="image" src="https://user-images.githubusercontent.com/38298743/203561648-f563292f-8bd4-4ceb-84b2-833ac4036aa2.png">

**Comment by NuroDev** [comment]
> Im my opinion, this information is very important as it can easily lead to confusion, it should be highlighted in the docs or at least made in a different section.

Agreed. This issue was less of a bug & more about (my) confusion in understanding layout segments when reading the docs & struggling to see / understand the constraints in which you can actually access layout segments
