### ISSUE TITLE
Next js 13 appDir config not working locally

### ISSUE THREAD

**Issue by vitalijalbu** [vercel/next.js#43286]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Hi guys, I downloaded this repo:
https://codesandbox.io/s/rsuite-nextjs-hgpbkh

Locally it doesn't work but online it works! 
Maybe due to node -v? Locally i have v18 but on codesandbox it uses v14

### What browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

npm run dev

### Describe the Bug

Locally it doesn't work but online it works! 
Maybe due to node -v? Locally i have v18 but on codesandbox it uses v14

### Expected Behavior

It must work :D

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://codesandbox.io/s/rsuite-nextjs-hgpbkh

### To Reproduce

clone locally and npm i then npm run dev

**Comment by balazsorban44** [comment]
There are two issues:

- `RootLayout` does not need to be imported and wrap the tree in your `page.js` (If you got this impression from our documentation, could you please link to it, so we can fix it?)
- `Button` is an interactive element and such should only be used in client components.
   - You can either: mark `page.js` with `"use client"`
   - move `Button` into a different file and add `"use client"`, then import in `page.js`

See: https://beta.nextjs.org/docs/rendering/server-and-client-components#when-to-use-server-vs-client-components and https://beta.nextjs.org/docs/routing/pages-and-layouts

**Comment by vitalijalbu** [comment]
> * "use client"

sorry, how to move button in a different file if I need button in that file?
About root layout, i found it here: https://beta.nextjs.org/docs/routing/pages-and-layouts

**Comment by vitalijalbu** [comment]
Where  I can find a working boilerplate with appDir made on next 13?

**Comment by balazsorban44** [comment]
> sorry, I'm using a ui library so that's why I'm importing the button like that. Is it a ui library's issue or next? Why on sandbox it works but locally doesn't?
https://beta.nextjs.org/docs/rendering/server-and-client-components#third-party-packages
> About root layout, i found it here: [beta.nextjs.org/docs/routing/pages-and-layouts](https://beta.nextjs.org/docs/routing/pages-and-layouts)
This page does not show you to import `RootLayout` in `page.js`
> Where I can find a working boilerplate with appDir made on next 13?
`npx create-next-app --experimental-app` will give you an app directory boilerplate.

**Comment by vitalijalbu** [comment]
> ?

thanks
