### ISSUE TITLE
Middleware not applied in standalone server mode

### ISSUE THREAD

**Issue by revmischa** [vercel/next.js#43319]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 13.0.5-canary.7
      eslint-config-next: 12.2.5
      react: 18.2.0
      react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

AWS CDK-nextjs-standalone https://github.com/jetbridge/cdk-nextjs

### Describe the Bug

I am trying to deploy a Lambda function that packages up the standalone output server. The handler source: https://github.com/jetbridge/cdk-nextjs/blob/main/assets/lambda/NextJsHandler.ts

When I try adding middleware, for example next-auth `withAuth()`, the middleware is run as expected on the matching routes when I run `next dev` locally but when I build and deploy the standalone output with that handler, the middleware is not run on the matching routes.

I see that a middleware-manifest.json file is generated and included in required-server-files.json. There are two webpack chunks mentioned in the manifest. I am unclear on if these are loaded and handled by the standalone server, or if I need to do something with them (I understand it can theoretically be an edge function), but I'm completely at a loss as to how to get middleware to be applied when using the standalone output with `NextNodeServer()`

### Expected Behavior

Ideally the middleware would Just Work with the standalone server. The matched routes would apply the middleware to the relevant requests.

Failing that, I can create a Lambda@Edge function or perhaps middy middleware or somesuch to wrap requests and responses based on the middleware-manifest.json. I would require some documentation for this though.

I assume there are some relevant concepts in `getMiddlewareBundle` (https://github.com/vercel/vercel/blob/c2d0887b94476cd540fb9d94e6e8b353cd343c38/packages/next/src/utils.ts#L2284) but this function is not exported and looks highly vercel-specific.

My middleware.js:
```ts
import { withAuth } from 'next-auth/middleware';

// require authentication for certain routes
console.log('MIDDLEWARE LOAD');

export default withAuth({});

export const config = {
  // apply to these routes
  matcher: ['/profile/:path*'],
};
```

On /profile/* routes I see `MIDDLEWARE LOAD` printed if I am running `next dev` but not in the lambda function. Routes are not protected in lambda.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/jetbridge/next-middleware-repro

### To Reproduce

Build nextjs app with standalone output
Deploy AWS lambda function with this wrapper https://github.com/jetbridge/cdk-nextjs/blob/main/assets/lambda/NextJsHandler.ts around the standalone output
Middleware is not applied to routes

See readme of https://github.com/jetbridge/next-middleware-repro

**Comment by DuCanhGH** [comment]
First of all, I must say that your reproduction repo is... really bloated. It's as if you just copied your actual app and called it a day. You should only include things that matter in the reproduction repo.
I don't think the issue is related to middlewares or `output: "standalone"` though. I just tested an app with `middleware.ts` and `output: "standalone'` turned on and the middleware still runs just fine. With next-auth/middleware it still runs normally. Maybe you should investigate further into your app to see what else may have gone wrong? Maybe it is AWS Lambda? I've yet to use AWS Lambda though so I don't really know.

**Comment by balazsorban44** [comment]
Hi, given the premise of the issue and the reproduction steps, it does seem that the problem is somewhere else. I tried reproducing the issue in a more minimal way here: https://github.com/balazsorban44/nextjs-43319

Starting the standalone server with `node .next/standalone/server.js`, you will see that Middleware indeed is run as expected.

Could you create a more minimal reproduction and do some troubleshooting to make sure it is an actual bug in Next.js first? :pray:

**Comment by khuezy** [comment]
@balazsorban44 I have the same issue when deploying to AWS: https://github.com/khuezy/middleware

I see that this works locally when I run `node .next/standalone/server.js`
Can you check if there's anything missing from the server setup in https://github.com/sladg/nextjs-lambda/blob/master/lib/standalone/server-handler.ts.

If this isn't a nextjs issue, then perhaps there's some misconfiguration at AWS lambda/apigateway layer: https://github.com/sladg/nextjs-lambda/blob/master/lib/cdk/stack.ts

Thanks in advance!

**Comment by khuezy** [comment]
Nvm, I got it working, it turns out there's some crucial settings required in the server file. Thanks for taking your time w/ this Balázs. Much appreciated!
I'll post an update of the required config in a moment once I figure out what the exact fields are.

**Comment by khuezy** [comment]
@balazsorban44 @revmischa
```
NextServer({ minimalMode: true }) // this flag breaks middleware
```

**Comment by revmischa** [comment]
Are the NextServer params explained somewhere by chance?

**Comment by khuezy** [comment]
I found this: https://github.com/vercel/next.js/discussions/29801 it says not to use it.

**Comment by revmischa** [comment]
Thanks everyone

**Comment by revmischa** [comment]
Hopefully fixed by https://github.com/jetbridge/cdk-nextjs/pull/33/files
