### ISSUE TITLE
Build fails for pages with props

### ISSUE THREAD

**Issue by mastoj** [vercel/next.js#43312]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #202207312230~1663791054~22.04~28340d4 SMP PREEMPT_DYNAMIC Wed S
    Binaries:
      Node: 16.8.0
      npm: 7.21.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.5-canary.6
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

When having a page with props using `yarn run dev` works just fine but `yarn run build` fails. 

Sample repo: https://github.com/mastoj/nextjs-page-error

Sample output when building:

```
➜  nextjs-page-error git:(main) yarn run build
yarn run v1.22.19
$ next build
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Linting and checking validity of types ...Failed to compile.

Type error: Page "app/search/page.tsx" does not match the required types of a Next.js Page.
  Invalid configuration:
    The exported page component isn't correctly typed.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

The page build complains on looks like this (it's in /app/search/page.tsx):

```
import React from "react";

type PageProps = {
  searchParams: { q: string };
};

const Page = ({ searchParams }: PageProps) => {
  return <div>Search</div>;
};

export default Page;
```

### Expected Behavior

I expect the build to pass. 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/mastoj/nextjs-page-error

### To Reproduce

run `yarn run build`

**Comment by mastoj** [comment]
If I have the props for `/app/search/page.tsx` be of type `any` it works, but I don't want that, I like my types :)

**Comment by mastoj** [comment]
Also, not sure if this is related. When I do use `any` everything works as expected when I use `run dev` and `run builds` works fine, but when I do `run start` the behavior is different compared to `run dev`. My `searchParams` will be blank for some reason, does it have to do with the page being a client side component?

Sample of the last issue here: https://github.com/mastoj/nextjs-page-error/tree/weird-diff

**Comment by balazsorban44** [comment]
This is because the types you provide are actually incorrect. You can see a hint in `.next/types` for what it's supposed to look like.

In short, `searchParams` is supposed to be optional:

```tsx
interface PageProps {
  searchParams?: { q: string }
}

export default function Page({ searchParams }: PageProps) {
  return <div>Search</div>
}
```

This should work.

Regarding https://github.com/vercel/next.js/issues/43312#issuecomment-1325712185, please report it as a different issue, and make sure there is a clear reproduction attached. :+1:

**Comment by felixkoch** [comment]
Solution. If you use a client component you need to use the useSearchParams hook: https://beta.nextjs.org/docs/api-reference/use-search-params

Also be aware of the getter-API, you can't access searchParams directly.

**Comment by mastoj** [comment]
Thanks, will have a look. What is the getter api?
