### ISSUE TITLE
create-next-app installs all dependencies as "dependencies"

### ISSUE THREAD

**Issue by mehrdad-shokri** [vercel/next.js#43331]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 3.3.0
      pnpm: 7.17.0
    Relevant packages:
      next: 13.0.4
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.4", newest: "13.0.6-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### What browser are you using? (if relevant)

chrome

### Describe the Bug

I've checked [create-next-app](https://www.npmjs.com/package/create-next-app) version on my system, It's the latest version. Trying to create a new Next.js app with ``create-next-app`` with Typescript, creates the following ``package.json``:  

```
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "eslint": "8.28.0",
    "eslint-config-next": "13.0.4",
    "next": "13.0.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.3"
  }
}

```

### Expected Behavior

I believe some of these dependencies should live in ``devDependencies`` like this:  
```
{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "13.0.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
  },
  "devDependencies": {
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "eslint": "8.28.0",
    "eslint-config-next": "13.0.4",
    "typescript": "4.9.3"
  }
}
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

 yarn create next-app my-app --ts --eslint --experimental-app

### To Reproduce

`` yarn create next-app my-app --ts --eslint --experimental-app``

**Comment by balazsorban44** [comment]
This should not be a problem, please see https://github.com/vercel/next.js/issues/43066#issuecomment-1319969015

**Comment by mehrdad-shokri** [comment]
But there are many devDependencies which makes the time of deployment longer.
