### ISSUE TITLE
Tailwindcss not working in appDir after add plugin

### ISSUE THREAD

**Issue by emdile** [vercel/next.js#43333]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.18.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.5
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

After  add plugin :

module.exports = withPlugins([withTM, withExpo], nextConfig)

I get error

![Screenshot_20221124_111007](https://user-images.githubusercontent.com/100505981/203806483-93820802-cdec-4e61-a6fd-42de09d91d67.png)

### Expected Behavior

apply tailwindcss style

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/emdile/next13-tailw

### To Reproduce

-add any plugin to project
-export it in next.config
-import global.css with tailwindcss imports in app/layout.tsx
-run dev

**Comment by balazsorban44** [comment]
TailwindCSS should be working, as per documentation: https://beta.nextjs.org/docs/styling/tailwind-css can you add a reproduction?

**Comment by emdile** [comment]
> Tailwind CSS should be working, as per documentation: https://beta.nextjs.org/docs/styling/tailwind-css can you add a reproduction?

Reproduction add

**Comment by balazsorban44** [comment]
Next.js now has built-in support for transpiling libraries in `node_modules`. You change your `next.config.js` to this:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    transpilePackages: ['moti'],
    appDir: true,
  },
}

module.exports = nextConfig
```

See the docs here: https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages

**Comment by emdile** [comment]
> Next.js now has built-in support for transpiling libraries in `node_modules`. You change your `next.config.js` to this:
> 
> ```js
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   reactStrictMode: true,
>   experimental: {
>     transpilePackages: ['moti'],
>     appDir: true,
>   },
> }
> 
> module.exports = nextConfig
> ```
> 
> See the docs here: https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages

It's work but how i can config if i want to use @expo/next-adapter
