### ISSUE TITLE
Allow to import from external folder

### ISSUE THREAD

**Issue by finom** [vercel/next.js#43351]
### Describe the feature you'd like to request

I have a monorepo and I require ts files from a common package.
```
/packages
  /next-website
  /common
```

But I get the following error:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/1082083/203859425-db04757f-3185-4c7d-94bb-20001eea1d10.png">

### Describe the solution you'd like

The solution is to include files from external repository at webpack config. Unfortunately I don't know how.

### Describe alternatives you've considered

An alternative is to give me an advice how to do that with next config. Thank you!

**Comment by balazsorban44** [comment]
External packages aren't transpiled by default, but Next.js 13 can now transpile your packages via the `transpilePackages` option:
https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages
