### ISSUE TITLE
Next 13 appDir: failed to deploy with `dynamicParams: false`

### ISSUE THREAD

**Issue by otoyo** [vercel/next.js#43357]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.5.0
      npm: 6.14.8
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.0
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

A page component under [Dynamic Segments](https://beta.nextjs.org/docs/routing/defining-routes#dynamic-segments), such like `app/blog/[slug]/page.tsx`, with `dynamicParams = false` failed to deploy on Vercel.
It is not happened in local.
```ts
export const dynamicParams = false

export async function generateStaticParams() {
  return [{ slug: 'hello-world' }]
}

export default async function BlogSlugPage({ params }: {
  params: { slug: string },
}) {
  return (
    <>
      <p>{params.slug}</p>
    </>
  )
}
```

Error messages(Vercel)
```
info  - Finalizing page optimization...
--
16:00:02.056 |  
16:00:02.076 | Route (app)                                Size     First Load JS
16:00:02.076 | ┌ ○ /                                      0 B                0 B
16:00:02.076 | └ ● /blog/[slug]                           136 B          66.5 kB
16:00:02.076 | └ /blog/hello-world
16:00:02.076 | + First Load JS shared by all              66.4 kB
16:00:02.076 | ├ chunks/17-efbfc64aa8219284.js          64.1 kB
16:00:02.076 | ├ chunks/main-app-f7991bdf5a7d528d.js    200 B
16:00:02.076 | └ chunks/webpack-d2d5d8dda7543a35.js     2.06 kB
16:00:02.077 |  
16:00:02.077 | Route (pages)                              Size     First Load JS
16:00:02.077 | ┌ ○ /404                                   179 B          81.1 kB
16:00:02.077 | └ λ /api/hello                             0 B            80.9 kB
16:00:02.077 | + First Load JS shared by all              80.9 kB
16:00:02.077 | ├ chunks/main-dd5d86fd91989c9a.js        78.7 kB
16:00:02.077 | ├ chunks/pages/_app-9f5490aa3d56632f.js  192 B
16:00:02.077 | └ chunks/webpack-d2d5d8dda7543a35.js     2.06 kB
16:00:02.077 |  
16:00:02.077 | λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
16:00:02.078 | ○  (Static)  automatically rendered as static HTML (uses no initial props)
16:00:02.078 | ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
16:00:02.078 |  
16:00:03.371 | Traced Next.js server files in: 1.131s
16:00:04.007 | Created all serverless functions in: 635.756ms
16:00:04.017 | Collected static files (public/, static/, .next/static): 6.696ms
16:00:04.544 | Error: ENOENT: no such file or directory, open '/vercel/path0/.next/server/app/404.html'
```

### Expected Behavior

`Error: ENOENT: no such file or directory, open '/vercel/path0/.next/server/app/404.html'` error is not occurred.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/otoyo/next13-sample

### To Reproduce

1. `npx create-next-app@latest --experimental-app` with TypeScript
2. Place `app/blog/[slug]/page.tsx` and define `generateStaticParams()` and `export const dynamicParams = false`
3. Push and run a deploy process on Vercel

**Comment by Kyoss79** [comment]
Cheers, you are my saviour.

I had the exact same issue and was banging my head my this happens in the first place.

Thank you sooo much.
Hope a fix comes soon.

**Comment by ijjk** [comment]
Hi, this should now be resolved, please re-deploy your project and give it a try!
