### ISSUE TITLE
Next 13 app folder: Error boundary breaks navigation to pages inside same route group

### ISSUE THREAD

**Issue by Arctomachine** [vercel/next.js#43355]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

If error boundary is triggered for page inside route group, navigation via links stops working for all pages in this route group. Url is changed, but contents of error file are still on the page.

_Additional breaks (could be related - I encounter them in my main project, but cannot reproduce here): full reloading page (browser reload) and navigating to link outside current route group also breaks certain styles. They are all (did not notice anything else) related to font weights in different places on page. Fixed by another full reload._
_What I use in the project where I encountered it:_

_- Next fonts. One variable font connected to `html` tag._
_- Css modules. All font weights are defined in different modules, none in global styles._
_- Scss. All style files are .scss_

### Expected Behavior

Navigating to pages inside same route group works. Page contents are changed along with url.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/Arctomachine/next-13-error-bug-repro.git

### To Reproduce

1. `next dev` or `next build` + `next start`, happens in both
2. Go to http://localhost:3000
3. Click corresponding link on home page or directly move to `/anotherPage`
4. When error screen is given, click corresponding link to go to `/yetAnotherPage`. Url is changed, but page contents are not.
5. Click corresponding links to go to `/` or `/sidePage`. Navigation works because they are outside of current route group.

**Comment by samcx** [comment]
@Arctomachine Just tested this stale issue on the latest stable v15 and I was not able to replicate it!
