### ISSUE TITLE
NextJS 13 and Docker

### ISSUE THREAD

**Issue by ghiblin** [vercel/next.js#43367]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

with-docker

### Describe the Bug

If you try to enable and use the app directory experimental feature, once you run the container you get a 404 - Not found message  

### Expected Behavior

To see the content of the page

### To Reproduce

1. enable the experimental feature in the `next.config.js` file:
```js
/** @type {import('next').NextConfig} */
module.exports = {
  experimental: {
    appDir: true
  },
  output: 'standalone',
}
```

2. rename `pages` folder into `app` folder
3. rename `index.js` into `page.js`
4. build the image with `docker build -t nextjs-docker .`
5. run the image with `docker run -p 3000:3000 nextjs-docker`
6. open the browser and go to `http://localhost:3000`

**Comment by ghiblin** [comment]
to solve this issue, you need to add the following line into `.Dockerfile` file:
```
COPY --from=builder --chown=nextjs:nodejs /app/.next/server ./.next/server
```

**Comment by balazsorban44** [comment]
Standalone mode is not yet supported with the app directory, so this is expected. See: https://github.com/vercel/next.js/issues/42812#issuecomment-1313287665

**Comment by DuCanhGH** [comment]
@balazsorban44 I've already added the support for it :)

**Comment by simplequality** [comment]
Standlone works for app dir now, however it does not work with any path under router group. The generated build will have an empty path dir. For instance, if there is an /example under /(sample), the standalone build comes with the /(sample)/example dir and an empty /example dir which will result 500 error when visit /example

**Comment by DuCanhGH** [comment]
@simplequality this happens because of an issue with .nft.json handling that causes Next.js to not copy those pages' required chunks. Thanks for noticing. I will try to find a fix :)

**Comment by DuCanhGH** [comment]
@simplequality the change has been approved, should be there by the next canary build :)
