### ISSUE TITLE
Page turns white while navigating the pages in nextjs 

### ISSUE THREAD

**Issue by gimtwi** [vercel/next.js#43369]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

package.json:
```
{
  "name": "text-nav",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "18.11.9",
    "@types/react": "18.0.25",
    "@types/react-dom": "18.0.9",
    "eslint": "8.28.0",
    "eslint-config-next": "13.0.5",
    "next": "13.0.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.3"
  }
}
```
 npm: '8.15.0',
  node: '16.17.0',

### Describe the Bug

Hello, i'm using npx create-next-app@latest --ts command and a little bit of code to navigate several pages, and every time page turns white before loading the page and navigating through pages. 
Here is my index.tsx:
```
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App test</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <nav>
          <ul>
            <li>
              <a href="/">
                <span>Home</span>
              </a>
            </li>
            <li>
              <a href="/products">
                <span>Products</span>
              </a>
            </li>
            <li>
              <a href="/about">
                <span>About</span>
              </a>
            </li>
          </ul>
        </nav>
        <h1>home page</h1>
      </main>
    </div>
  );
}
```
Nothing fancy here on css side as well.:
```

html,
body {
  padding: 0;
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
}

a {
  color: inherit;
  text-decoration: none;
}

* {
  box-sizing: border-box;
}

@media (prefers-color-scheme: dark) {
  html {
    color-scheme: dark;
  }
  body {
    color: white;
    background: black;
  }
}

```
I’m running it on local host, I don't understand why such a simple application takes so much time to load. Is it a bug, or is it a problem on my side? Thanks. 

### Expected Behavior

Transition should be smooth. 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

npx create-next-app@latest --ts + code i provided above 

### To Reproduce

npx create-next-app@latest --ts + code i provided above

**Comment by balazsorban44** [comment]
Could you add a link to a reproduction repository? We need to see the pages you link to. Is this happening in dev or production?

**Comment by gimtwi** [comment]
I found out that this issue accruing only with <a/> property, but replacing <a/> with <Link /> from "next/link" solved the problem.
