### ISSUE TITLE
[NEXT-697] React Dev Tools in chrome causes Error "Uncaught TypeError: wakeable.then is not a function" when a context provider wraps a suspense (next dev)

### ISSUE THREAD

**Issue by max-ch9i** [vercel/next.js#43389]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

❯ npx next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Nov 25 2022 15:45:12 GMT+0000 (Greenwich Mean Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome + React Dev tools extension

### How are you deploying your application? (if relevant)

npx next dev (or yarn dev)

### Describe the Bug

Error `Uncaught TypeError: wakeable.then is not a function` is thrown.

### Expected Behavior

No error should be thrown.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/nextjs-sys3ek?file=package.json

### To Reproduce

https://user-images.githubusercontent.com/1893149/204023103-db90dd68-1185-4311-9345-2133e1589077.mov

1. Load stackblitz (tab A): https://stackblitz.com/edit/nextjs-sys3ek?file=package.json
2. Make sure dev build is running (npx next dev)
3. Open a new tab (tab B) and open dev console
4. Copy the preview url from stackblitz from tab A
5. Paste into the address bar tab B, load the page.
6. Refresh the page.
7. Observe `Uncaught TypeError: wakeable.then is not a function`

If the react dev extension is disabled, the error is not thrown.
If the context provider is removed, the error is not thrown.
If suspense is removed, the error is not thrown.

<sub>[NEXT-697](https://linear.app/vercel/issue/NEXT-697/react-dev-tools-in-chrome-causes-error-uncaught-typeerror-wakeablethen)</sub>

**Comment by vlausargs** [comment]
i had same issue when calling dispatch or setState in useEffect in react context
![image](https://user-images.githubusercontent.com/39726092/206882441-047cdcf3-bd48-4028-bcc9-7de8e0a692a3.png)

**Comment by jaular** [comment]
Same error when using Sanity (preview) with next@13.1.1

**Comment by priyanshuraj24** [comment]
I am also getting this error _**"TypeError wakeable.then is not a function**_" when the page is **refreshed**. Initially, everything appears to load properly, but when I refresh the page, the website breaks and prevents me from performing any actions, such as navigation, and some libraries do not load (Swiper and GSAP).

Next Version: next@13.1.1
Features I am using are: appDir, Provider & context, and also dispatching inside useEffect

**Comment by amkatyshev** [comment]
+1

**Comment by JuanseChavero** [comment]
Getting the same error when using Next-themes when in 'light' mode and refreshing the page. (for some reason when in 'dark' mode it doesn't happen)

**Comment by songhobby** [comment]
Is there a timeline for a fix?

**Comment by timneutkens** [comment]
<img width="1190" alt="CleanShot 2023-02-28 at 14 42 13@2x" src="https://user-images.githubusercontent.com/6324199/221871524-c7815f6f-cf6a-4d45-8db1-2e7c051ce19c.png">
<img width="550" alt="CleanShot 2023-02-28 at 14 41 59@2x" src="https://user-images.githubusercontent.com/6324199/221871529-19094a98-8772-4bb5-be3c-3f31002cf663.png">

Seems that it happens during selective hydration with React devtools loaded on the page, this is not related to how Next.js is implemented so it'd be good to report this on the React repository. I'll let the React team know separately as well 👍

**Comment by timneutkens** [comment]
Just verified this is fixed by https://github.com/facebook/react/pull/26275!
