### ISSUE TITLE
@next/font/local: Cannot read properties of undefined (reading 'fs')

### ISSUE THREAD

**Issue by fscgustavo** [vercel/next.js#43394]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: linux
      Arch: x64
      Version: #20 SMP Tue Aug 30 18:45:03 CEST 2022
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 12.0.9
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Version 1.45.131 Chromium: 107.0.5304.110 (Official Build) (arm64)

### Describe the Bug

The @next/font/local can not be used inside the app or pages directory. The following error is displayed when the default function is used. It occurs before the app start:

```
Font loader error:
Cannot read properties of undefined (reading 'fs')
```

### Expected Behavior

Render the app normally with a div that contains the className created by the localFont function

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

[Codesanbox](https://codesandbox.io/p/sandbox/compassionate-keldysh-6xn08v?file=%2Fapp%2Fpage.tsx&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A5%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clawu2ygy00cp3b6goihwg2in%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpackage.json%2522%252C%2522%252Ffont%252FrobotoMedium.ttf%2522%252C%2522%252Fapp%252Fpage.tsx%2522%252C%2522%252Fnext.config.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clawt999o000n3b6fofw6j8wa%2522%253A%257B%2522key%2522%253A%2522clawt999o000n3b6fofw6j8wa%2522%252C%2522name%2522%253A%2522Default%2520Space%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clawuwx1q026s3b6fwcjkvgsh%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clawt999o000n3b6fofw6j8wa%2522%257D)

### To Reproduce

Run `next dev` or `next build`, the error will be displayed in the terminal.

**Comment by hanneslund** [comment]
Hi! This can be fixed by updating your next version, try 13.0.5.
