### ISSUE TITLE
Page keeps refreshing: "Fast Refresh had to perform a full reload."

### ISSUE THREAD

**Issue by BenjaminLindberg** [vercel/next.js#43398]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Sat Oct 29 14:22:16 UTC 2022
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 7.14.1
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Firefox 106.0.4 (64bit)

### How are you deploying your application? (if relevant)

yarn run dev (next dev)

### Describe the Bug

When i start my app and open it up in Firefox it keeps reloading. 
It's almost like a loop, that just continues and continues and never stops.
This is getting printed out in the console: `warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/basic-features/fast-refresh#how-it-works`. 

### Expected Behavior

I expect the app to not reload on such high interval in dev mode that i cant even see the page. 
**NOTE: when i open up 2 instances of the app (which makes one app get hosted on port 3001) everything works fine, it also works fine when i close the app on port 3000 and keep the other one running. **

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

No idea how to reproduce 

### To Reproduce

I dont know exactly how to reproduce, but try using the versions i use and start the app with `yarn run dev`.

**Comment by B3nnjoe** [comment]
Just tried opening the page up on `Chrome Version 107.0.5304.68 (Official Build) (64-bit)` and seems to be no errors.
But when i open it up on firefox the error seems to be there.

**Comment by tonypizzicato** [comment]
I see the same in `13.0.6-canary.2` in Chrome. Works fine in Safari

**Comment by BenjaminLindberg** [comment]
The issue got solved when i cleared all the cache and all the other data stored by the site.
So i guess that clearing the cache & other site data solves the problem 👍🏻

**Comment by BenjaminLindberg** [comment]
The issue keeped appearing when i closed the browser, which made me need to delete cache and such.
But i solved it!
Apparently i had some old service worker still running on that address from another project. But i have never experienced this since i deleted the SW.
