### ISSUE TITLE
Docs: bad example for classnames packages

### ISSUE THREAD

**Issue by xgqfrms** [vercel/next.js#43393]
### What is the improvement or update you wish to see?

# `classnames` !== `clsx`

```diff
import styles from './alert.module.css';
- import cn from 'clsx';
+ import classNames from 'classnames';

export default function Alert({ children, type }) {
  return (
    <div
-      className={cn({
+      className={classNames({
        [styles.success]: type === 'success',
        [styles.error]: type === 'error',
      })}
    >
      {children}
    </div>
  );
}
```

https://www.npmjs.com/package/classnames

https://www.npmjs.com/package/clsx

### Is there any context that might help us understand?

![image](https://user-images.githubusercontent.com/7291672/204035289-6d21c20c-3666-46d2-ace0-1dc32252306c.png)

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/assets-metadata-css/styling-tips

**Comment by pratik-codes** [comment]
Is anyone working on this? I can take this up if it is open

**Comment by xgqfrms** [comment]
# I can not find where is the `docs` repo, therefore cannot make a PR for it!


## ✅ `Edit this page` link wanted

like React Docs did, which is very easy to find the doc file.

<img width="933" alt="image" src="https://user-images.githubusercontent.com/7291672/204874278-51b62bb8-473f-4cb8-aa71-6351f49f691a.png">


https://reactjs.org/docs/react-dom-server.html

## 👎 not just simply goto`discussions`

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/7291672/204874814-6c519de6-593a-4cd5-89d4-ba563dd8eb39.png">


https://nextjs.org/learn/basics/assets-metadata-css/styling-tips

**Comment by xgqfrms** [comment]
# has been fixed ✅

![image](https://user-images.githubusercontent.com/7291672/218810431-a85295da-af7f-4a8f-b017-cf576837a6be.png)


https://nextjs.org/learn/basics/assets-metadata-css/styling-tips

**Comment by xgqfrms** [comment]
# has been fixed ✅

![image](https://user-images.githubusercontent.com/7291672/218810431-a85295da-af7f-4a8f-b017-cf576837a6be.png)


https://nextjs.org/learn/basics/assets-metadata-css/styling-tips
