### ISSUE TITLE
App Directory in NextJs breaks PrimeReact client code

### ISSUE THREAD

**Issue by chrishj59** [vercel/next.js#43401]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.19.1
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

FireFox 106.0.5 

### How are you deploying your application? (if relevant)

Running on local MacBook

### Describe the Bug

I am using the UI tool package PrimeReact to have a MengaMenu as default menu using the new new layout model
On the layout page in the app directory, there is no client-side styling with all the text displayed as plain text in a vertical list.
Using the pages directory the styling is shown correctly.
The PrimeReact team have confirmed that this appears to be a NextJs issue.

### Expected Behavior

When layout.tsx and navbar.tsx are annotated with 'use client' I expect the styling  from PrimeFaces to use used to render the megamenu correctly

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/chrishj59/next13LayoutDemo

### To Reproduce

Using the example code run the application with `npm run dev` and view the page displayed

**Comment by balazsorban44** [comment]
It looks like you forgot to import the required styles as shown in this example:
https://github.com/primefaces/primereact-examples/blob/main/nextjs-basic/pages/_app.js

Adding these in the root layout will render correctly.

![image](https://user-images.githubusercontent.com/18369201/204598312-f28424a7-3c77-49bb-92ee-124da894a2c6.png)

Please refer to the docs: https://beta.nextjs.org/docs/upgrade-guide#migrating-_documentjs-and-_appjs

**Comment by chrishj59** [comment]
This still happens where is primeReact css file are included in _app.tsx .
Please see https://github.com/chrishj59/next13LayoutDemo
