### ISSUE TITLE
AppDir - Unable to call API route from Server Component

### ISSUE THREAD

**Issue by SamRoehrich** [vercel/next.js#43415]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

locally

### Describe the Bug

Calling an API route from a server component throws an error. 
`Error: Failed to parse URL from /api/hello`

Following the pattern in the beta docs - https://beta.nextjs.org/docs/data-fetching/fetching#asyncawait-in-server-components - this pattern throw the above error.

`app/Dashboard/DashboardHeader/index.tsx`
```
export default async function DashboardHeader() {
	const { name } = await getData()
	return (
		<header className="flex items-center justify-between px-4 py-4 bg-white border-b border-gray-200">
			<div className="flex items-center">
				<h1 className="text-2xl font-semibold">Dashboard</h1>
			</div>
			<div className="flex items-center">
				<h1>Hi - {name}</h1>
			</div>
		</header>
	)
}

async function getData(): Promise<{ name: string }> {
	const data = await fetch('/api/hello', { method: 'GET' })
	return data.json()
}
```

`pages/api/hello.ts`
```
import { NextApiRequest, NextApiResponse } from 'next'

export default function handler(_req: NextApiRequest, res: NextApiResponse) {
	res.status(200).json({
		name: 'John Maverick'
	})
}
```

### Expected Behavior

API routes should be available to a server component.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/SamRoehrich/coachqlv2

### To Reproduce

Clone repo
Navigate to /dashboard
Notice issue

Files in question
`app/dashboard/DashboardHeader/index.tsx`

**Comment by balazsorban44** [comment]
Server-side `fetch` calls need to use an absolute URL to include the host. This should work:

```js
await fetch('http://localhost:3000/api/hello', { method: 'GET' })
```

**Comment by adrianosmond** [comment]
@balazsorban44 This solves the issue for `next dev`, but `next build` is still broken.

In case anyone is interested I hacked my way around it by installing `wait-on` and `concurrently` and changing the build script in my package.json to be
```
"build": "concurrently \"wait-on http://localhost:3000/api/hello && next build\" \"next dev\" --kill-others --success first",
```
(or replace `/api/hello` with some API Route from your application)
