### ISSUE TITLE
Next 13 Hook: useSelectedLayoutSegment() returns segment value as `null` for the `/` i.e. home route

### ISSUE THREAD

**Issue by Palanikannan1437** [vercel/next.js#43413]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:5
7 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Version 107.0.5304.110 (Official Build) (x86_64)

### Describe the Bug

While navigating to any route (say /movies) and using useSelectedLayoutSegment to read the active route segment, the segment value being returned is expected i.e. I'm getting 'movies`.

But incase of navigating to the home route (/), while using useSelectedLayoutSegment, I'm getting null as the segment value...is this an intended behaviour? 

How do you think `''` an empty string would be a replacement to `null` being returned, would love to hear everyone's thoughts on this! Thank you😄

PS: I've attached a gitpod instance for everyone to quickly test and see in action what I'm exactly talking about!

### Expected Behavior

```js
const segment = useSelectedLayoutSegment();
```

Incase of navigating to the home route i.e. `/`, the expected segment could be an empty string `''` instead of null.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://gitpod.io/#https://github.com/Palanikannan1437/next-13-test

### To Reproduce

1. Create a app/nav-link.js component

```javascript
"use client";

import Link from "next/link";
import { useSelectedLayoutSegment } from "next/navigation";

export default function NavLink({ href, children }) {
  let segment = useSelectedLayoutSegment();

  let active = href === `/${segment}`;
  console.log({ href, active }, `/${segment}`);

  return <Link href={href}>{children}</Link>;
}
```

2. Create a app/layout.js file 

```javascript
import "./globals.css";
import NavLink from "./nav-link";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-900 text-gray-100 antialiased">
      <head>
        <title>Nested Layouts by example</title>
      </head>
      <body>
        <header className="border-b p-4">
          <nav className="space-x-4">
            <NavLink href={"/"}>Home</NavLink>
            <NavLink href={"/movies"}>Movies</NavLink>
          </nav>
        </header>
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
```

3. Now while navigating to the Home page i.e. the / , the segment is `null`, instead of `''` an empty string

**Comment by Palanikannan1437** [comment]
If this issue really does persist and the current behaviour of returning `null` for the home route for `useSelectedLayoutSegment` is not the intended behaviour, **I'd love to work on this issue and come up with a PR!** Thank you😄

**Comment by Fredkiss3** [comment]
I think this is the intended behavior, as said in the docs : 

https://beta.nextjs.org/docs/api-reference/use-selected-layout-segment#examples

<img width="749" alt="image" src="https://user-images.githubusercontent.com/38298743/204103758-57d0f19f-34c9-4c49-9187-63396cbc6017.png">

**Comment by Palanikannan1437** [comment]
> I think this is the intended behavior, as said in the docs : 
> 
> https://beta.nextjs.org/docs/api-reference/use-selected-layout-segment#examples
> 
> <img width="749" alt="image" src="https://user-images.githubusercontent.com/38298743/204103758-57d0f19f-34c9-4c49-9187-63396cbc6017.png">
> 

Ohhh thank you so much for letting me know so quickly @Fredkiss3 !!

But why are we using null instead of `''` an empty string though?

**Comment by Fredkiss3** [comment]
good question

**Comment by balazsorban44** [comment]
This is intended as found in the documentation. There is no such segment as `""`, hence `null`, which expresses an intentionally non-existent value.

**Comment by Fredkiss3** [comment]
that's fair

**Comment by Palanikannan1437** [comment]
> This is intended as found in the documentation. There is no such segment as `""`, hence `null`, which expresses an intentionally non-existent value.

Ohhh! Is the root `/` considered as a "non-existent" value? Could you please help me understand why so? 

Thank you 😄

**Comment by balazsorban44** [comment]
So from [the documentation](https://beta.nextjs.org/docs/api-reference/use-selected-layout-segment):

> The useSelectedLayoutSegment hook allows you to read the active route segment *one level down from a layout*.

> It returns a string of the active segment or null if one doesn't exist.

In this case, since there is no segment below the root layout, there is nothing to match. Hope this helps. :pray:

**Comment by Palanikannan1437** [comment]
> The useSelectedLayoutSegment hook allows you to read the active route segment one level down from a layout.

Ohhh!! I misinterpreted that it meant...

- We can read all the active route segments by using `useSelectedLayoutSegment`  in a component that is present **one level down** w.r.t the layout, i.e. `NavLink` component in this case!

But now I understand that it meant....

- We can read all the active route segments that are **one level down** from the respective layout!

I'm not sure if it's just me, but do you suggest if we'd need to change the docs up a bit to be more clear?😅

Thank you so much for all the support and quick responses @balazsorban44!! 🎉

**Comment by balazsorban44** [comment]
No problem! You can leave direct feedback on the documentation (by selecting the text you find confusing) :pray:, and the docs team will have a look.
