### ISSUE TITLE
Next 13 ISR does not work with dynamic route

### ISSUE THREAD

**Issue by thien-do** [vercel/next.js#43427]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

NA: This happens in all browsers

### How are you deploying your application? (if relevant)

Vercel - https://vercel.com/thien-do/next-13-isr - prj_7zxCSPoiumpGycUiKN5CySBlnoJl

### Describe the Bug

There is no option in [Segment Config](https://beta.nextjs.org/docs/api-reference/segment-config#configrevalidate) to achieve pre-13 Incremental Static Regeneration (ISR). Or there is, but they do not work yet.

Please see the "to reproduction" for details on various cases I have tested.

### Expected Behavior

Setting something like:

```
revalidate: 60
dynamic: 'error' (or 'force-static')
```

should trigger a cache HIT for subsequent visit (of the same path) like in Next 12's ISR.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/thien-do/next-13-isr

### To Reproduce

**To reproduce:**

1. Visit https://next-13-isr.vercel.app/two/foo -> this is always MISS even in subsequent visit. Config of this route is:
    ```
    # /two/[param]
    revalidate = 60
    dynamic = "error"
    ```
2. Visit https://next-13-isr.vercel.app/three/foo -> this is always MISS even in subsequent visit. Config of this route is:
    ```
    # /three/[param]
    revalidate = 60
    dynamic = "force-static"
    ```

**More details:**

The linked reproducible repo consists of only 3 commits:
1. The initial commit created by Next
3. The commit that configs various routes to have ISR (https://github.com/thien-do/next-13-isr/commit/dc5bd6ec4199cc52e31d3e6f479aa1163bfea3b9)
4. A commit to upgrade next to canary (13.0.6-canary1 at the time of writing) (https://github.com/thien-do/next-13-isr/commit/fb9d413ab471225499976b4863e01d36fa3b8502)

Specifically, the app is configured to have 5 routes:

|               | x-vercel-cache | revalidate | dynamic      | fetchCache |
|---------------|----------------|------------|--------------|------------|
| static        | HIT            |            |              |            |
| one/[param]   | MISS           |            | auto         |            |
| two/[param]   | MISS           | 60         | error        |            |
| three/[param] | MISS           | 60         | force-static |            |
| four/[param]  | MISS           | 60         | force-static | only-cache |

The problem is all 4 dynamic routes are MISS on subsequent visits, thus there is no way to have ISR behaviour (HIT on subsequent visits)

**Comment by thien-do** [comment]
Oh so the bug is because I did not have `generateStaticParams`. Adding one that returns `[]` fixes it!

**Comment by brvnonascimento** [comment]
> At the moment, `generateStaticParams` is broken if used with `previewData`. #43392

This is only for development. I was able to workaround that with this:

```tsx
// TODO: Remove this condition once the following PR is merged: https://github.com/vercel/next.js/pull/43395
export const generateStaticParams =
  process.env.NODE_ENV !== 'development'
    ? async () => {
 
        return [
          { slug: [] },
          { slug: ['/test']
        ]
      }
    : undefined
```
