### ISSUE TITLE
[v13 app folder] Two issues for Link prefetch options.

### ISSUE THREAD

**Issue by GomaGoma676** [vercel/next.js#43423]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
    Relevant packages:
      next: 13.0.6-canary.1
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Two issue with Link for prefetch options.

Issue 1, With prefetch={false} in Link, by navigations global state such as useContext, Zustand lost.
Issue 2, With prefetch={true} in Link, Even although prefetched rsc payload exist, another new rsc payload fetch called when firstly navigate to page, especially on static route.

### Expected Behavior

Issue 1, useContext global state shall be preserved when navigate by Link with prefetch false option. 
Issue 2, prefetched rsc payload shall be reused. (redundant rsc payload fetch when firstly navigating to shall be removed, especially on static route.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/GomaGoma676/v13-link-prefetch.git

### To Reproduce

Issue 1. With prefetch={false} in Link, set value by useContext lost by Link navigation, with useRouter.push state preserved.
Issue 2. With prefetch={true}, with first load of home page, rsc payload of home and demo subtree segment are returned in network tag (expected behavior of prefetch), but we firstly navigate to demo page by Link, another payload fetch called, with further revisit to demo page no fetch called due to client in-memory cache.

**Comment by lfraudeau** [comment]
I experience the same issue with the app directory and it's really annoying because :
- it makes browsing really slow on slow networks. - it makes the prefetch almost useless.

Hope it will be fix soon !

**Comment by boatilus** [comment]
I went ahead and deployed the example @GomaGoma676 provided (thank you!) to Vercel if anyone wants to check out the issue at hand a bit more easily: https://v13-link-prefetch.vercel.app

Viewing the network inspector, the runtime's correctly prefetching `/demo`, as the link appears above the fold, but the request isn't cached, and navigating to `/demo` through the link initiates a second request. Subsequent navigations to `/demo` are executed without an additional fetch.

I'm seeing this same behavior when preloading dynamic components (along with associated CSS modules), so there may some relation to the mechanisms there, but I'll file a separate issue for that.

**Comment by Arctomachine** [comment]
Issue 2 seems to have been fixed in recent versions. There is no duplicate fetch after visiting prefetched link.

**Comment by samcx** [comment]
@GomaGoma676 Hi there!

Since this issue has become stale and <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> is no longer available, I'm going to safely assume that issue has since been resolved.

If there is still an issue with Link prefetch, please let us know!
