### ISSUE TITLE
[NEXT-947] The experimental-runtime fails with ReferenceError: self is not defined when used inside a route group

### ISSUE THREAD

**Issue by shadcn** [vercel/next.js#43458]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
Binaries:
  Node: 16.18.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.13.5
Relevant packages:
  next: 13.0.5
  eslint-config-next: 13.0.5
  react: 18.2.0
  react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Using the `experimental-edge` runtime fails with the following error when used inside a route group.

```
ReferenceError: self is not defined
    at Object.<anonymous> (/var/task/.next/server/app/(marketing)/stats/page.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (/var/task/node_modules/.pnpm/next@13.0.6-canary.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/require.js:88:12)
    at /var/task/node_modules/.pnpm/next@13.0.6-canary.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/load-components.js:37:73
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/stats'
}
RequestId: Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Given the following file structure:

```
app
├── page.tsx ✅
├── nested
│   └── page.tsx ✅
├── (group)
│   └── group
│       └── page.tsx ❌
└── (another-group)
    └── another-group
        └── page.tsx ❌  
```

With `export const runtime = "experimental-edge"`, the following is observed:

- `/` - Works
- `/nested` - Works
- `/group` - Fails
- `/another-group` - Fails

I checked if having a `layout.tsx` has any effect on grouping. It does not.

### Expected Behavior

Expects the `experimental-edge` runtime to work inside route groups.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/shadcn/next-debug-edge-runtime

### To Reproduce

See the links below:

1. ✅ `experimental-edge` runtime works for **root page**: https://next-debug-edge-runtime.vercel.app
2. ✅ `experimental-edge` runtime works for a **nested page**: https://next-debug-edge-runtime.vercel.app/nested-with-layout
3. ❌ `experimental-edge` runtime does not work for a **grouped page with layout**: https://next-debug-edge-runtime.vercel.app/group-no-layout
4. ❌ `experimental-edge` runtime does not work for a **grouped page without layout**: https://next-debug-edge-runtime.vercel.app/group-with-layout

<sub>[NEXT-947](https://linear.app/vercel/issue/NEXT-947/the-experimental-runtime-fails-with-referenceerror-self-is-not-defined)</sub>

**Comment by pksorensen** [comment]
#43662  - my example was the /pages/index.tsx , and i dont see that is covered in the senarie mentioned here so why is it a dublicate?

**Comment by shadcn** [comment]
@shuding Thanks for the fix in https://github.com/vercel/next.js/pull/43549.

I tested with the latest canary `13.0.7-canary.1` but still seeing the same error.

**Comment by pksorensen** [comment]
people are reporting issues on https://github.com/vercel/next.js/issues/43662 that is not related to route groups. As i see it , fetch do not work in edge runtime.

**Comment by alvarlagerlof** [comment]
I just got the error on 13.1.1, not in a route group. Just /test/[name].

**Comment by marketsystems** [comment]
fails with the same message "ReferenceError: self is not defined" on windows for **nested pages** even now, yet build works fine if you do it on linux (ubuntu) even though all packages and binaries are the same version as windows

**Comment by kaceycleveland** [comment]
Getting this on deploying to vercel on 13.2.4

**Comment by ijjk** [comment]
Hi, this should now be available in production, please re-deploy your project and give it a try!

**Comment by barthicus** [comment]
I also rebuild my projects that previously failed with 500 error. Now they are working fine. Thanks!
