### ISSUE TITLE
Avoid modifying .next directory on build

### ISSUE THREAD

**Issue by Uni2K** [vercel/next.js#43462]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 17.4.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.4
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

A very similar issue was mentioned here: https://github.com/vercel/next.js/issues/1135 and here: https://github.com/vercel/next.js/pull/1139#event-962264425

The issue is concerning the downtime of the application during rebuild.
The new build replaces important files inside the .next directory, so the currently running server will produce errors.

### Expected Behavior

I would expect that the new build will be applied once it has finished. Until that everything should run error free. The issue mentioned above addresses the same problem.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

/

### To Reproduce

1. next build + next start (go to localhost:3000 to check if it is really running)
2. Trigger another build in a separate console (next build)
3. Check localhost:3000 to see that it is not online anymore, you will just get a 500 error

**Comment by balazsorban44** [comment]
Dist directory is cleaned up by default between builds, but you can turn this off via `cleanDistDir: false` in `next.config.js` as mentioned here: https://nextjs.org/docs/upgrading#cleaning-the-distdir-is-now-a-default
