### ISSUE TITLE
Can't use next/navigation 'redirect' method inside the layout file

### ISSUE THREAD

**Issue by Pamboli** [vercel/next.js#43464]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 13.0.6-canary.1
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 107.0.5304.107

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

I'm using the "next/navigation" redirect function to redirect the page to the login page if the session is not found. I'm using that function inside a server component which is inside the "layout.tsx" file. 

The page doesn't redirects and the screen shows an unhandled runtime error (Error: NEXT_REDIRECT) that makes me think that the redirect method is not being executed on the server side, because the error shows in the client. If I use this same method inside  a component on the "page.tsx" file it works perfectly.

![image](https://user-images.githubusercontent.com/80546925/204338934-fb9386cc-107f-4935-80ef-0f5ce81afcd3.png)

### Expected Behavior

Using the redirect function in a server component should redirect the page.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/Pamboli/tool-it

### To Reproduce

- pnpm run dev
- Go to localhost:3000
The app should detect that the user is not logged and should redirect automatically to the login page but the error will show.

**Comment by ijjk** [comment]
Closing as this should be updated in the latest version of Next.js, please update and give it a try!
