### ISSUE TITLE
Headers.entries() empty return

### ISSUE THREAD

**Issue by willin** [vercel/next.js#43466]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 3.3.0
      pnpm: 7.17.1
    Relevant packages:
      next: 13.0.5
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.5", newest: "13.0.6-canary.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Describe the Bug

<img width="834" alt="image" src="https://user-images.githubusercontent.com/1890238/204343881-282c509a-9088-468d-972d-b05fdbbc5a8b.png">

<img width="934" alt="image" src="https://user-images.githubusercontent.com/1890238/204343842-4f5bc0a0-8d00-4729-b24e-592837d52848.png">

### Expected Behavior

get all headers

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/willin/beta.willin.wang/commit/f9492ec9e3ec1a53e83e9c0106bb8a45252f17e2

### To Reproduce

```ts
import { headers } from 'next/headers';

export default async function PostPage1() {
  const headersList = headers();
  const referer = headersList.get('referer');
  const ua = headersList.get('user-agent');
  const country = headersList.get('x-vercel-ip-country');
  const region = headersList.get('x-vercel-ip-country-region');

  return (
    <div>
      <h1>Hello</h1>
      <div>Referer: {referer}</div>
      <div>UA: {ua}</div>
      <div>Country: {country}</div>
      <div>Region: {region}</div>
      <pre>{JSON.stringify(headersList.entries(), null, 2)}</pre>
    </div>
  );
}
```

**Comment by wwwdepot** [comment]
Convert iterators to array by `Array.from(iterator)` or spread syntax `[... iterator]`

```jsx
import { headers } from "next/headers";

export default async function page() {
  const headersList = headers();

  return (
    <div>
      <h1>Hello</h1>
      <pre>{JSON.stringify(Array.from(headersList.entries()), null, 2)}</pre>
    </div>
  );
}
```
