### ISSUE TITLE
Memory leak using fetch() without consuming body

### ISSUE THREAD

**Issue by longzheng** [vercel/next.js#43493]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 13.0.6-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When using `fetch()` on the server-side (e.g. in a `getServerSideProps`) without reading the response body, memory usage climbs linearly to the number of requests being made.

For example a request like this

```typescript
    fetch("http://127.0.0.1:3000/api/test")
      .then(async (res) => {
        return res.headers;
      })
```

I graphed the memory usage while making 100 fetch requests to an API endpoint returning 1MB data in my repro demo app (linked below)

![image](https://user-images.githubusercontent.com/484912/204485201-223d03f0-49d2-4b6c-8351-d5b15df80b6b.png)

The memory usage will continue to grow until the Node.js app crashes due to heap out of memory.

But when requesting `fetch()` with consuming the body, the memory stays consistent

```typescript
    fetch("http://127.0.0.1:3000/api/test")
      .then(async (res) => {
        for await (const chunk of res.body as any) {
          // force consumption of body
        }

        return res.headers;
      })
```

![image](https://user-images.githubusercontent.com/484912/204485220-fd8c4fa4-deb6-45b2-bfc2-682de27f4a29.png)

### Expected Behavior

Memory stays consistent when using `fetch()` without reading the response body

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/longzheng/nextjs-memory-leak-demo

### To Reproduce

1. Clone repro demo app https://github.com/longzheng/nextjs-memory-leak-demo
2. `npm install`
3. `npm run build`
4. `npm run start`
5. Navigate to http://localhost:3000/
6. Click "Return response headers only" and see memory usage graph climb
7. Go back to homepage and click on "Force consumption of response body" and see memory usage graph stay steady

**Comment by michael-kleemann** [comment]
We also faced this issue in the last days.
In our usecase we wanted to follow the redirected URL and read that out.
We were not interested in the body content. Therefore, we did not consume it.
This is a mistake that can easily occur and might have fatal consequences. 

There has been the same issue in node-fetch around 2016: https://github.com/node-fetch/node-fetch/issues/83

**Comment by Fredkiss3** [comment]
In next you can use `undici` instead of `node-fetch` which is the default with a config flag : 

```js
// next.config.js
module.exports = {
   experimental: {
        enableUndici: true
       // other flags
    },
}
```

Does using `undici` solve the problem ? 🤔

**Comment by longzheng** [comment]
> In next you can use `undici` instead of `node-fetch` which is the default with a config flag :
> 
> ```js
> // next.config.js
> module.exports = {
>    experimental: {
>         enableUndici: true
>        // other flags
>     },
> }
> ```
> 
> Does using `undici` solve the problem ? 🤔

I believe under Node 18, Next.js 13 [will not polyfill](https://github.com/vercel/next.js/blob/canary/packages/next/server/node-polyfill-fetch.js#L3) and use the global `fetch()` (because `global.fetch` is defined) which is [undici under the hood](https://nodejs.org/de/blog/announcements/v18-release-announce/#fetch-experimental:~:text=implementation%20comes%20from%20undici)?

**Comment by nico-abram** [comment]
This seems to be [documented](https://undici.nodejs.org/#/?id=garbage-collection) undici behaviour
