### ISSUE TITLE
with-mobx example install command

### ISSUE THREAD

**Issue by Haschikeks** [vercel/next.js#43512]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Not needed

### Which example does this report relate to?

with-mobx

### Describe the Bug

The `How to use` section of the `with-mobx` example is using an outdated example name.

Current command:
`${packageManager} create-next-app --example with-mobx-react-lite with-mobx-react-lite-app`

### Expected Behavior

The expected command should only use `with-mobx` to correspond to the example name.

`${packageManager} create-next-app --example with-mobx with-mobx-app`

### To Reproduce

No steps to be taken.

**Comment by Haschikeks** [comment]
I would be willing to fix the issue.

**Comment by balazsorban44** [comment]
Assuming you talk about this section:
https://github.com/vercel/next.js/blob/fdff88bb62fabb825f0cb68cba3101bb572a8888/examples/with-mobx/README.md?plain=1#L30-L38

Please go ahead, and open a PR! :green_heart:

**Comment by Haschikeks** [comment]
I just noted that the same problem is present on other parts of the readme aswell.
Once for the Stackblitz link and for the `Deploy with Vercel`.

Should those be updatet aswell?

https://github.com/vercel/next.js/blob/fdff88bb62fabb825f0cb68cba3101bb572a8888/examples/with-mobx/README.md?plain=1#L19-L24

**Comment by balazsorban44** [comment]
Yes, go ahead

**Comment by Haschikeks** [comment]
The same pattern of problem/typo seem to be present on the [with-mobx-state-tree](https://github.com/vercel/next.js/tree/canary/examples/with-mobx-state-tree) example

Should this be a separate PR or can this be added to mine current one?

**Comment by balazsorban44** [comment]
Same PR is fine
