### ISSUE TITLE
Allow setting transpilation target version

### ISSUE THREAD

**Issue by bouk** [vercel/next.js#43560]
### Describe the feature you'd like to request

Currently Next.JS [always targets](https://github.com/vercel/next.js/blob/55e35c5144bdbeeccf1d0fcfb92284b578a31d6a/packages/next/build/swc/options.js#L277-L278) `es5` for transpilation, which can lead to quite suboptimal code if you use newer functionality like the spread operator. Currently there isn't a way to override this default.

### Describe the solution you'd like

It would be nice if it defaulted to whatever's in `tsconfig.json` and if there was also an option in `next.config.js` to override the version.

### Describe alternatives you've considered

I've added the following to my `next.config.js`:

```js
const swcOptions = require('next/dist/build/swc/options')
const { getLoaderSWCOptions } = swcOptions
swcOptions.getLoaderSWCOptions = function (...args) {
  const result = getLoaderSWCOptions(...args)
  result.jsc.target = 'es2022'
  return result
}
```

This reaches into the Next internals to override the swc config

**Comment by balazsorban44** [comment]
Hi, since Next.js 13, we are now targeting browsers that support ESM by default. Read more: https://github.com/vercel/next.js/discussions/33227

You can configure this by using a Browserslist config: https://nextjs.org/docs/basic-features/supported-browsers-features#browserslist
