### ISSUE TITLE
Docs: Inconsistency regarding where to put <Script> components that have the `beforeInteractive` strategy.

### ISSUE THREAD

**Issue by cmbritten** [vercel/next.js#43566]
### What is the improvement or update you wish to see?

There appears to be an inconsistency in the recommended location of a <Script> component using the `beforeInteractive` strategy.

One [page in the docs](https://nextjs.org/docs/api-reference/next/script#beforeinteractive) recommends `_app.js` as the location:

> `beforeInteractive` scripts must be placed inside `pages/_app.js` and are designed to load scripts that are needed by the entire site (i.e. the script will load when any page in the application has been loaded server-side).

In contrast, a linter error and [the corresponding explanation](https://nextjs.org/docs/messages/no-before-interactive-script-outside-document) of the message recommends putting the same <Script> inside the `_document.js` page (see below for the relevant warning).

Would it be possible for the docs to clarify the best placement of such a <Script>?

### Is there any context that might help us understand?

If you add the above-described script in `_app.js`, you receive the following warning:

> `next/script`'s `beforeInteractive` strategy should not be used outside of `pages/_document.js`. See: https://nextjs.org/docs/messages/no-before-interactive-script-outside-documenteslint[@next/next/no-before-interactive-script-outside-document](https://nextjs.org/docs/messages/no-before-interactive-script-outside-document)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/script#beforeinteractive

**Comment by michael-bouwer** [comment]
Anyone manage to get past this one? I have this issue too. My app builds fine and runs in dev, but I receive the same errors above in the console.
