### ISSUE TITLE
Konva / konva-react not working with app directory setup

### ISSUE THREAD

**Issue by stx-chris** [vercel/next.js#43567]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Tue Nov  8 21:14:19 PST 2022; root:xnu-8792.60.55.131.1~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.9.0
    Relevant packages:
      next: 13.0.6-canary.2
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area of Next.js is affected? (leave empty if unsure)

App directory (appDir: true)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

[https://codesandbox.io/s/angry-sun-6iu9e4?file=/app/page.tsx](https://codesandbox.io/s/angry-sun-6iu9e4?file=/app/page.tsx)

### To Reproduce

Minimum working example

```
"use client";

import Konva from "konva";
import { Stage, Layer, Rect } from "react-konva";

export default function MinExample() {
  return (
    <>
      <Stage width={200} height={100}>
        <Layer>
          <Rect x={1} y={2} width={3} height={4} />
        </Layer>
      </Stage>
    </>
  );
}
```

### Describe the Bug

The following error message is returned:

```
error - ./node_modules/konva/cmj/index-node.js
Module not found: Can't resolve 'canvas' in '.../node_modules/konva/cmj'
Did you mean './canvas'?
```

Seems to have to do with ESM handling.

Things I tried, without luck:
- changing to `dynamic` import
- `next.config.js` setting: `experimental: { esmExternals: 'loose' }`
- `webpack.IgnorePlugin` targeting `canvas` and `konva`

### Expected Behavior

Working the same as if used in the `/pages` directory. There, no issues occur.

### How are you deploying your application? (if relevant)

yarn dev

**Comment by Fredkiss3** [comment]
This has been an issue since nextjs 12 (you can see here: https://github.com/konvajs/react-konva/issues/588).

And the issue persists even on the page directory, the solution is to import your konva component with `next/dynamic`. 
See [here](https://github.com/konvajs/react-konva/issues/588#issuecomment-1329923458) for the solution.

**Comment by stx-chris** [comment]
Thanks @Fredkiss3 for your feedback, we are using this workaround successfully in our Next 12 projects. But as I wrote above, the `dynamic` woraround doesn't work anymore for our current Next 13 `appDir` project. 

The `{ssr: false}` seems to be ignored, resulting in the very same error message. Also working in conjunction with the `"use client"` directive has no effect.

**Comment by balazsorban44** [comment]
This seems to be a library issue, `canvas` is given as a dev dependency, even if it gets used at runtime: https://github.com/konvajs/konva/blob/763a7be0f908697bd6fb4eaec00822e6783df259/package.json#L94

Thus it never gets installed by the package manager, causing the above issue.

It also seems like there is some ESM <> Common JS issues with `konva`/`react-konva` which should be fixed upstream.

**Comment by stx-chris** [comment]
Right, one quick fix seems to be to exclude `canvas` from the webpack config:

```
const nextConfig = {
  ...
  webpack: (config) => {
    config.externals = {
      canvas: "canvas",
    };
    return config;
  },
};
```

Now, the app compiles but still generates a warning when the affected component is used:

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
```
 
Still hoping for a better solution, though.
