### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by alsonick** [vercel/next.js#43573]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.3.4
      eslint-config-next: 13.0.0
      react: 17.0.2
      react-dom: 17.0.2

### Which area of Next.js is affected? (leave empty if unsure)

Other

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/splashsaver/splashsaver.com

### To Reproduce

1. Clone the GitHub repository ([https://github.com/splashsaver/splashsaver.com](https://github.com/splashsaver/splashsaver.com)).
2. Install the missing dependencies with `yarn install`.
3.  Build the monorepo with `yarn build`.

### Describe the Bug

Whenever I try to build my Turborepo project I get the following error.

`TypeError: Cannot read properties of null (reading 'useContext')`

More info:

```
landing:build: > Build error occurred
landing:build: Error: Export encountered errors on following paths:
landing:build:  /
landing:build:  /_error: /404
landing:build:  /_error: /500
landing:build:  /blog
landing:build:  /privacy
landing:build:  /team
landing:build:  /terms
```

I get the same error in my `web` app but with the respective paths, the `docs` app builds successfully.

When I run the Turborepo project locally the page returns an `Internal Server Error` message and I get the following error.

`TypeError: Cannot read properties of null (reading 'useReducer')`

<img width="800" alt="image" src="https://user-images.githubusercontent.com/101022772/204872947-fe4e4887-c397-4c45-99dd-f54420419126.png">

### Expected Behavior

Successful builds.

**Comment by balazsorban44** [comment]
`next` is incorrectly marked as a dependency here: https://github.com/splashsaver/splashsaver.com/blob/94f71848a4e2df8c9d68f06af9b53ccd59504868/packages/ui/package.json#L22, it should be a `peerDependency`. Likewise, `react` should be added as a peerDependency.

Furthermore, you can likely drop `next-transpile-modules`, as Next.js 13 now supports transpiling modules built in. See: https://beta.nextjs.org/docs/api-reference/next.config.js#transpilepackages
