### ISSUE TITLE
Router.query contains _next when using middleware with dynamic routes

### ISSUE THREAD

**Issue by mv-nborrett** [vercel/next.js#43598]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.5
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area of Next.js is affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/mv-nborrett/middleware-dynamic-routes

### To Reproduce

- Run the project usng `npm run dev`.
- Navigate to http://localhost:3000/base/default.
- See that the text "The path is: default" is correctly displayed.
- Select the link labelled "Link to another page".  This navigates the user to http://localhost:3000/base/another-page.
- See that the text "The path is: another-page" is correctly displayed.
- Go back using the back button.  This navigates the user back to http://localhost:3000/base/default.
- See that the text "The path is: _next" is displayed.

### Describe the Bug

My understanding is that router.query.path should match the path segment matched in the dynamic route.  However, when middleware is used, even if that middleware just passes the request through without taking any action, router.query.path displays _next in certain situations.  If the middleware is removed (ie, middleware.ts is deleted), router.query.path always displays the correct value.

### Expected Behavior

I would expect router.query.path to contain the path segment displayed in the URL.  The reason that this is an issue is that we have buttons which use router.query.path as a prefix when linking to pages deeper in the tree.  This means that the button sends the user to http://localhost:3000/base/_next/child-page instead of http://localhost:3000/base/default/child-page.

### Which browser are you using? (if relevant)

Chrome 107.0.5304.122 (Official Build) (32-bit)

### How are you deploying your application? (if relevant)

npm run dev

**Comment by balazsorban44** [comment]
Tracked down to this release: https://github.com/vercel/next.js/releases/tag/v12.2.6-canary.8, likely related PR: https://github.com/vercel/next.js/pull/39257

**Comment by phunanon** [comment]
I confirm the issue persists, taking the reproduction repo and upgrading to both `13.2.4` and `13.2.5-canary.20` (up from `13.0.5`).

**Comment by darshkpatel** [comment]
This occurs to any dynamic routing page not mentioned in `getStaticPaths`, matching the matcher in the middleware 
still happens in `v13.3.1`

<img width="686" alt="Screenshot 2023-04-23 at 9 32 55 PM" src="https://user-images.githubusercontent.com/11258286/233850900-3377de9f-594e-4267-b31a-af3c7019d441.png">
