### ISSUE TITLE
[NEXT-325] NextJS13 - AppDir - Server redirect happens as fetch not browser redirection

### ISSUE THREAD

**Issue by schemburkar** [vercel/next.js#43605]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 18.5.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.3
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/vercel/next.js/files/10133225/next-redirect-demo.zip

### To Reproduce

Build & run the sample

[next-redirect-demo.zip](https://github.com/vercel/next.js/files/10133225/next-redirect-demo.zip)

```
yarn install
yarn dev
```

Navigate to `/test/A` this should do below:
- Renders page `test/[slug]/page`, which redirects to `/external`
-  `/external` is a pages route and server redirects (302) to external site `google.com`

The server redirect is done via fetch and not browser redirection.

![image](https://user-images.githubusercontent.com/3159347/205078087-3e7fe6e1-534c-48aa-83d3-f6113cde9b4c.png)

### Describe the Bug

The app has below pages
- `/test/[slug]/page.tsx` - using app dir route and server redirect from next/navigation
- `/external` - pages route that redirects to external site.

If user enters `/external` in url, the page correctly does a 302 redirect to external site. This is expected behaviour.

If user enters `/test/A` in the url, the page also returns a 302, but the redirection happens via fetch. This is not expected behaviour.

**Expected Behaviour**:
The redirection should be browser redirection and not done via fetch.

To reproduce the bug

Navigate to `/test/A` this should do below:
- Renders page `test/[slug]/page`, which redirects to `/external`
-  `/external` is a pages route and server redirects to external site `google.com`

### Expected Behavior

The route `/test/A` should be browser redirection and not done via fetch.

<sub>[NEXT-325](https://linear.app/vercel/issue/NEXT-325/nextjs13-appdir-server-redirect-happens-as-fetch-not-browser)</sub>

**Comment by Fredkiss3** [comment]
I think if you want to redirect to an external domain, you could use `middleware.ts`, as next redirect function is more for redirecting between your routes and server components.

**Comment by schemburkar** [comment]
@Fredkiss3 I have a different opinion. If a redirect is being sent from a page with a 302 status code, it should always be a browser redirect. Not handled via xhr/fetch. It should not matter if its a external domain.

Also there is conflicting behaviour if the `/external` page is hit via url vs being called by another redirect from app dir. That means this is a bug in either case.

**Comment by boehlerlukas** [comment]
@schemburkar I was expecting a server side 302 redirect as well.

**Comment by 31i0t** [comment]
Same issue here. The problem manifests similarly with a CORS error. I believe this is unexpected behavior, no? The [redirect() docs](https://beta.nextjs.org/docs/api-reference/redirect) say the URL can be relative or absolute. Why use an absolute URL for anything that isn't external?

**Comment by 31i0t** [comment]
Workaround:
`app/settings/page.tsx`
```diff
import Redirect from "./Redirect"

export default function SettingsPage() {
...
-  redirect('https://google.com')
+ return <Redirect />
...
}

```

`app/settings/Redirect.tsx`
```tsx
'use client'

import { useEffect } from 'react'

export default function Redirect() {
  useEffect(() => {
    window.location.replace('https://google.com')
  })
  return null
}
```

**Comment by lucchev** [comment]
Same problem here with `middleware` sending an external redirection :
````js
NextResponse.redirect('https:\\[domain][pathname]')
````
It's interpreted by the Next Client as a fetch, not a browser redirection.
So same CORS error...

**Comment by LGmatrix13** [comment]
Been experiencing this issue still in 13.1. @boehlerlukas’s recommendation for a 302 server side redirect seems like a good idea…

**Comment by DaleLJefferson** [comment]
Yes this is really annoying, since the redirect is in a server component I was expecting to see a server side redirect.

This workaround https://github.com/vercel/next.js/issues/43605#issuecomment-1342410758 worked but it's not very satisfying.

**Comment by morgangallant** [comment]
Can confirm that the above-mentioned workaround did work, was having an issue where redirecting to another route (i.e. from /dashboard -> /login) wouldn't render the contents of /login properly, would just show the layout and blank otherwise. Not sure if this is immediately related to this issue or not, but certainly a similar fix — seems very reasonable that redirect() should be implemented as a 302 or something similar to it.

**Comment by ChristianIvicevic** [comment]
I am experiencing another minor issue with this behavior myself. In my root page I just have the following:
```tsx
import { unstable_getServerSession } from 'next-auth';
import { redirect } from 'next/navigation';
import { authOptions } from 'pages/api/auth/[...nextauth]';

const Page = async () => {
  const session = await unstable_getServerSession(authOptions);
  redirect(session !== null ? '/lobby' : '/login');
};

export default Page;
```
The Vercel dashboard of my application shows a white screen and no preview which may be due to a lack of a browser-based redirect. Ironically the redirect works as expected with a classic index file at `pages/index.tsx` that contains the following code:
```tsx
import type { GetServerSideProps } from 'next';
import { unstable_getServerSession } from 'next-auth';
import { authOptions } from 'pages/api/auth/[...nextauth]';

const Page = () => null;

export default Page;

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const session = await unstable_getServerSession(req, res, authOptions);
  return { redirect: { destination: session !== null ? '/lobby' : '/login', permanent: false } };
};
```
Unlike the use of `redirect()` the old approach via `gSSP` takes the environment into consideration.

**Comment by timneutkens** [comment]
Had a look into this one, it happens because there is a redirect() call to a url that ends up redirecting, fetch() doesn't give us much to deal with this case because you can't get the `location` header when setting `redirect: 'manual'` on fetch otherwise this case would have an easy solution.
What we'll have to do instead is always forcing a browser navigation when the fetch for the RSC payload fails.

**Comment by CTOverton** [comment]
I tried installing `"next": "13.2.4-canary.4"` which I think has @timneutkens pr merged in it but I'm not entirely sure. Unforcunately I'm still hitting a redirect issue.

My code looks something like this for anyone interested

client `src/components/AuthComponent.tsx`
```tsx
'use client'

import React from 'react'
import Button from '@/components/Button'
import useAuth from '@/lib/useAuth'

export default function AuthComponent({
  children,
}: {
  children: React.ReactNode
}) {
  const { user, loading, signIn, signOut } = useAuth()
    
    
    return (
        <Button onClick={signIn}>Login with Spotify</Button>
    )
```

client `src/lib/useAuth.ts`
```tsx
import { useState } from 'react'

export default function useAuth() {
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(false)

  async function signIn() {
    console.log('sign in')

    await fetch('/api/auth/login')
  }

  async function signOut() {
    console.log('sign out')
  }

  return { user, loading, signIn, signOut }
}
```

server `src/app/auth/login/route.ts`
```tsx
import { redirect } from 'next/navigation'
import { config } from '@/config/config'

export async function GET(request: Request) {
  const state = generateRandomString(16)
  const scope = 'user-read-private user-read-email'

  redirect(
    'https://accounts.spotify.com/authorize?' +
      querystring.stringify({
        response_type: 'code',
        client_id: config.SPOTIFY_CLIENT_ID,
        scope: scope,
        redirect_uri: config.SPOTIFY_REDIRECT_URI,
        state: state,
      })
  )
}
```

Still getting the CORS redirect for the external Spotify url
> Access to fetch at 'https://accounts.spotify.com/authorize?response_type=code&client_id=<CLIENT_ID>&scope=user-read-private%20user-read-email&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback&state=CQS7Yc5oPom73Szt' (redirected from 'http://localhost:3000/api/auth/login') from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
