### ISSUE TITLE
Middleware req.cookies.get and getAll return wrong value

### ISSUE THREAD

**Issue by voronianski** [vercel/next.js#43610]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 29 04:31:06 PDT 2022; root:xnu-7195.141.39~2/RELEASE_X86_64
    Binaries:
      Node: 14.19.2
      npm: 6.14.17
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.0.6-canary.3
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/voronianski/nextjs-middleware-cookie-bug/blob/main/middleware.ts#L15-L17

### To Reproduce

1. `yarn dev`
2. open http://localhost:3000
3. create cookie `test` with value `consentId=aaa7fe7f-e59d-47c3-a53d-cd844fb9ad6b&datestamp=Thu+Dec+01+2022+16%3A57%3A23+GMT%2B0100+(Central+European+Standard+Time)&version=6.32.0&interactionCount=1&isGpcEnabled=0&isIABGlobal=false&hosts=&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1%2CC0005%3A1`

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/974035/205122338-ffaa8e9a-cc51-496e-9390-903c21016a49.png">

4. reload the page
5. check middleware console logs

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/974035/205122530-7cd8c559-5ff3-4923-afc3-0262e2ef49fc.png">

### Describe the Bug

when given complex string in a cookie (regardless encoded or not) `req.cookies.get` and `req.cookies.getAll` methods in middleware return wrong `value` for that cookie (just first part of a string).

Example string that breaks -

```
consentId=aaa7fe7f-e59d-47c3-a53d-cd844fb9ad6b&datestamp=Thu+Dec+01+2022+16%3A57%3A23+GMT%2B0100+(Central+European+Standard+Time)&version=6.32.0&interactionCount=1&isGpcEnabled=0&isIABGlobal=false&hosts=&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0003%3A1%2CC0004%3A1%2CC0005%3A1
```

Example of `req.cookies.get()?.value` -

```
consentId
```

### Expected Behavior

it should return correctly parsed `value` in both `req.cookies.get` and `req.cookies.getAll` methods.

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
Hi, this has been fixed in #44218 please upgrade to `next@latest`!
