### ISSUE TITLE
Add Server Startup Hooks

### ISSUE THREAD

**Issue by anthonyalayo** [vercel/next.js#43611]
### Describe the feature you'd like to request

This feature has been requested for over 2 years now in this discussion thread with no response from Vercel: https://github.com/vercel/next.js/discussions/15341

I belive @mschipperheyn [described it very simply:](https://github.com/vercel/next.js/discussions/15341#discussioncomment-3128585)

> Nextjs should have subscribeable events for this that accept promises:
> 
> ```
> preStartup
> postStartup
> preShutdown
> postShutdown
> ```
> The basic task of initialization is such a pain. You should not have to optin to a custom server to be able to do this.

This feature is **necessary** since standalone mode **does not work** with custom servers. Being able to initialize a prism connection pool or telemetry at the start of an application is standard for use with API routes.

### Describe the solution you'd like

Provide any sort of hook/function/subscribe-able event that developers can use to have code run once at server startup.

### Describe alternatives you've considered

I have considered using a custom server to do this, but it does not work with standalone mode. Standalone ignores your custom server and generates its own.

**Comment by anthonyalayo** [comment]
Please do not bucket this under discussion -- this is a feature request.

**Comment by anthonyalayo** [comment]
Please do not bucket this under discussion -- this is a feature request. The associated discussion is here: https://github.com/vercel/next.js/discussions/15341

**Comment by balazsorban44** [comment]
Hi, feature requests are converted to discussions as outlined in the contribution docs, as well as the issue template you filled out.
