### ISSUE TITLE
Multi Zones deployed without Cloudflare throws ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by trevans24** [vercel/next.js#43614]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

What version of Next.js are you using?

13.0.1

What version of Node.js are you using?

16.X

What operating system are you using?

Mac

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://stackblitz.com/edit/vercel-next-js-9aqgfv

### To Reproduce

Following the github example [with zones](https://github.com/vercel/next.js/tree/canary/examples/with-zones) may not provide all information...

1. Follow monorepo set up
2. Add next config to both home and public folders following example
3. Create env with redirect url
4. Deploy 2 Vercel apps following the monorepo example from the with zones
5. Add Checkly integration to Vercel
6. `home` hosted Vercel app builds
7. `public` hosted Vercel app doesn't build, Checkly issue due to basePath being `/public`

### Describe the Bug

`home > next.config.js`
```
const { PUBLIC_URL } = process.env

/** @type {import('next').NextConfig} */
module.exports = {
  async rewrites() {
    return [
      {
        destination: `${PUBLIC_URL}/public`,
        source: '/public',
      },
      {
        destination: `${PUBLIC_URL}/public/:path*`,
        source: '/public/:path*',
      }
    ]
  },
}
```

`"public" > next.config.js`
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  basePath: '/public',
}

module.exports = nextConfig
```

Home hosted at this [URL](https://you-ofd.vercel.app/) > go to `/public` see the ERR_TOO_MANY_REDIRECTS. Inside the dev tools network tab note a bunch of 308s
Public hosted at this [URL](https://ofd-grit-digital.vercel.app/) > go to `/public` route and see it working

There are no redirects noted at all in the `public` repo. Not sure if Vercel doing SSL is causing this issue or what might be causing this.

### Expected Behavior

Following the Vercel example the deployed apps should work going to the main domain then following the other next app route should render the application without throwing 308

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by mknichel** [comment]
Hi @trevans24 , 

I think the problem should go away if you change your rewrites to use `/:path+`. Try:

```
  async rewrites() {
    return [
      {
        source: '/public',
        destination: `${PUBLIC_URL}/public`,
      },
      {
        source: '/public/:path+',
        destination: `${PUBLIC_URL}/public/:path+`,
      }
    ]
  },
```

Let me know if that doesn't fix it.
