### ISSUE TITLE
Some exact strings catch the "Hydration failed" error

### ISSUE THREAD

**Issue by arnaudjnn** [vercel/next.js#43638]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.11.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.0.5
  eslint-config-next: 13.0.5
  react: 18.2.0
  react-dom: 18.2.0
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/arnaudjnn/react-hook-form

### To Reproduce

- Go to homepage
- See error
- If you use another input name than specifically `lastName` it works

### Describe the Bug

Error: Hydration failed because the initial UI does not match what was rendered on the server

### Expected Behavior

No hydration error

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
I cannot reproduce this either in dev, prod, or deployed to Vercel. Can you check if it's not a browser extension that somehow interferes?

**Comment by arnaudjnn** [comment]
Correct, It's due to LastPass extension on inputs. Do you think we can improve this for the dev experience only?
