### ISSUE TITLE
Extremely slow development load times (90-200s) [turborepo]

### ISSUE THREAD

**Issue by alsonick** [vercel/next.js#43649]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 13.0.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/splashsaver/splashsaver.com

### To Reproduce

1.  Clone the GitHub repository (https://github.com/splashsaver/splashsaver.com.git).
2. Install the missing dependencies with `yarn install`.
3. Run the project `yarn dev`.
4. Navigate to a random `tsx` file in the `web` application (`cd apps/web/`).
5. Make a minor change or just save the file.

### Describe the Bug

Extremely long load times in development mode, typically around 90-200s.

Screenshots of load times:
<img width="595" alt="Screenshot 2022-12-02 at 17 43 57" src="https://user-images.githubusercontent.com/101022772/205353352-ece53876-db51-4030-abb3-59c61673c46b.png">
<img width="570" alt="Screenshot 2022-12-02 at 17 44 18" src="https://user-images.githubusercontent.com/101022772/205353411-3c7a5cbd-ecb2-41f1-9cd0-5503bd23198a.png">
<img width="570" alt="Screenshot 2022-12-02 at 17 45 49" src="https://user-images.githubusercontent.com/101022772/205353720-8f9392e6-950a-45d1-8627-06f41dc54968.png">
<img width="590" alt="Screenshot 2022-12-02 at 17 46 02" src="https://user-images.githubusercontent.com/101022772/205353756-d7fbf30c-36f1-4599-84bc-cb31f1e56de2.png">

### Expected Behavior

Fast reload times.

### Which browser are you using? (if relevant)

108.0.5359.71

**Comment by VictorHaine** [comment]
[alsonick](https://github.com/alsonick) I got some weird results as well, but it was my tailwind "content" configuration that was too broad, analyzing my compiled storybook files in the shake-tree.

**Comment by alsonick** [comment]
> [alsonick](https://github.com/alsonick) I got some weird results as well, but it was my tailwind "content" configuration that was too broad, analyzing my compiled storybook files in the shake-tree.
> 
> Changing from `"../../packages/ui/**/*.{ts,tsx}"` to `"../../packages/ui/components/**/*.{ts,tsx}"` fixed the issue.
> 
> ```js
> module.exports = {
>   content: [
>     "../../packages/ui/components/**/*.{ts,tsx}",
>     "./pages/**/*.{ts,tsx}",
>     "./layouts/**/*.{ts,tsx}",
>     "./components/**/*.{ts,tsx}"
>   ],
>   theme: {
>     extend: {}
>   },
>   plugins: [require("@tailwindcss/typography"), require("@tailwindcss/forms")]
> };
> ```

Tried this but the issue still remains. 🥲

**Comment by alsonick** [comment]
Not sure if this is relevant or helpful but I also get this in the console whenever it's loading.

![image](https://user-images.githubusercontent.com/101022772/205377044-8d8ee446-3efe-466f-9fc3-4183f9699de9.png)

**Comment by alsonick** [comment]
UPDATE: Turns about my Turborepo project was really misconfigured, I was using two different versions of `next` inside my `landing` & `web` applications.
