### ISSUE TITLE
remark-frontmatter does not work with `mdxRs` enabled for `@next/mdx`

### ISSUE THREAD

**Issue by jbean96** [vercel/next.js#43656]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.0.1
      npm: 8.1.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/jbean96/next-mdx-rs-issue

### To Reproduce

Run `yarn next dev` from the root of the repo. Navigate to `localhost:3000`, observe that the front matter present in `app/blog.mdx` is rendered into HTML.

In `next.config.mjs` comment out the `mdxRs: true` line, restart the server, navigate to `localhost:3000` observe that the front matter is omitted from the rendered HTML.

### Describe the Bug

Frontmatter is not omitted from the rendered HTML when `mdxRs` is enabled.

### Expected Behavior

Frontmatter should be omitted from the rendered HTML.

**Comment by vdesdoigts** [comment]
Hello, did you find a solution?

**Comment by yangshun** [comment]
Not just `remark-frontmatter`, all plugins provided in `remarkPlugins`, and likely `rehypePlugins` as well. `mdx-rs-loader` is probably not passing them in properly.

**Comment by ahupp** [comment]
rehypePlugins appears to work, at least with @mapbox/rehype-prism.

**Comment by timneutkens** [comment]
As per the project readme it doesn't support plugins yet:

https://github.com/wooorm/mdxjs-rs#when-should-i-use-this

> This project does not yet support plugins. To benefit from the unified (remark and rehype) ecosystem, use [@mdx-js/mdx](https://mdxjs.com/packages/mdx/).
