### ISSUE TITLE
Major Issue Being Ignored

### ISSUE THREAD

**Issue by machineghost** [vercel/next.js#43670]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Next.js Issues Tracker

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/vercel/next.js/discussions/10935

### To Reproduce

1. Go to https://github.com/vercel/next.js/discussions/10935
2. See that (literally) hundreds of devs are begging for the feature
3. Also see that no one from the Next team has deigned to respond

### Describe the Bug

Look, I understand that in OSS development, everyone doesn't always get their pet issue fixed.  But when hundreds of devs all request the same thing, and the issue has been ongoing for *over a year* ... couldn't you at least *answer* them ... even if the answer is "no we won't fix this"?

### Expected Behavior

When an issue is major enough to get hundreds of people responding to it, the Next team addresses it in some way (again, even if it's a one sentence "We don't think a fix for this belongs in Next.js" response).

**Comment by cheesycod** [comment]
I agree

**Comment by balazsorban44** [comment]
Thanks for the feedback, but the best action is to upvote feature requests, as those are handled via Discussions.

I forwarded this to the team for review.
