### ISSUE TITLE
A gray background will appear after the next/image component is loaded using placeholder='blur'

### ISSUE THREAD

**Issue by 0x3Anthony** [vercel/next.js#43689]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

"next": "^13.0.6"

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

create-next-app

### To Reproduce

<Image alt="" src={require('@images/home/space/cover_01.png')} placeholder="blur" />

### Describe the Bug

A gray background will appear after the next/image component is loaded using placeholder='blur'
The previous nextjs version did not encounter this problem
Below is a schematic diagram of the code and rendering
![image](https://user-images.githubusercontent.com/100060836/205486442-8a2f2cc3-3a53-4918-a85c-6f1bc60698be.png)
![image](https://user-images.githubusercontent.com/100060836/205486500-8e411b67-05ea-4aad-a7e0-c2e847b74b8d.png)

### Expected Behavior

When the placeholder='blur' attribute is used, these introverted styles should not exist after the image is loaded, and can be removed. Now it is an obvious bug

**Comment by ruben-martin-lozano** [comment]
It's probably related to this PR https://github.com/vercel/next.js/pull/43587 where the useState from next/image was removed.
