### ISSUE TITLE
[Next13 App dir] Bug with server-only being used in an API route handler

### ISSUE THREAD

**Issue by KolbySisk** [vercel/next.js#43700]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.0.0: Mon Aug  1 06:32:20 PDT 2022; root:xnu-8792.0.207.0.6~26/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/KolbySisk/next-server-only-bug

### To Reproduce

1. Create a client component that makes a request to an api route (A form that posts data to an api route, for example)
2.`npm i server-only`
3. Add `import "server-only";` to the api route.
4. Run and make the request to the api route.

See error:

`You're importing a component that needs server-only. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component.`

### Describe the Bug

API routes are handled only on the server, so I would expect `import "server-only";` to work fine.

More realistically, I have a function which includes sensitive information that I want to ensure only runs on the server. It can be used in both a server component, and an API route, given the context.

I'm also curious how Next even knows about the relationship between a client component and an API route handler. 

### Expected Behavior

Code is executed as expected without the error.

<sub>[NEXT-1385](https://linear.app/vercel/issue/NEXT-1385/[next13-app-dir]-bug-with-server-only-being-used-in-an-api-route)</sub>

**Comment by Fredkiss3** [comment]
I think you don’t need to import server only in an api route. Since when used in a api route it is sure to only run on the server.

I think the problem is that `server-only` can only work and give you the correct errors if it used in a context of a component, and maybe NextJs confuse the api handler for a component when `import server-only` is used, I may be wrong though.

**Comment by HStromfelt** [comment]
I think there is still an issue with API routes wrongly being confused with client components. I have a library function that uses:
```
import { cookies } from "next/headers";
```
and is used in an API route. The function should only be run by server-side code so this is ok, but NextJS thinks that the calling functions (API routes) are client-side:
```
./lib/getUser.js

You're importing a component that needs next/headers. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component.

   ,----
 7 | import { cookies } from "next/headers";
   : ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   `----

One of these is marked as a client entry with "use client":
  lib/getUser.js
  pages/api/stripe/create-account.js
```
I can fix by adding import "server-only" to the api files but then I get the same error as @KolbySisk.

**Comment by Fredkiss3** [comment]
I think it is rightfully a bug, with NextJs confusing the api route as a client component, but I also think that these directives should fail, as you imported `cookies` which is a function you can only use in server components but not anywhere else, you’d have to use the request object in your api handler. same thing for `server-only` which is supposed to be a guardrail when you import them from a react component (wether it is client or server one). 
When you try to use them in a different context out of react (i.e api handlers) NextJs is lost and produces and generic incorrect error

**Comment by Fredkiss3** [comment]
@ayhanap  You can only `import { cookies } from 'next/headers';` inside of server components not anywhere else.
In middleware or api handlers, you should use the request object.

**Comment by larsniet** [comment]
Same thing here. 

When I run fetch within a "use client" (signup in this instance) page and use this server-side only import on the API's side:
 ```
// pages/api/auth/signup.ts
import { createServerClient } from "@utils/supabase-server";
```

It returns:

```
You're importing a component that needs next/headers. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component.
   ,----
 1 | import { headers, cookies } from "next/headers";
   : ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   `----

One of these is marked as a client entry with "use client":
  src/utils/supabase-server.ts
  src/pages/api/auth/signup.ts
```

Even though I did not nest my API route within the "use client" page, it still thinks I did. My guess is that NextJS has some issues with combining API routes and the new App directory.

**Comment by boatilus** [comment]
A similar issue also manifests when importing anything into a server component from a module that also imports a module which imports certain client-only features, such as `useReducer`, including simple functions which, say, just return a string. That's a fairly long-winded and convoluted way of saying that this error message is the result of a false positive.

A simple repro is [here](https://github.com/boatilus/v13-false-client-error). Attempting to build it results in the following error despite that the imported *function* does not require `useReducer`, even if a parent import *does*:

```
You're importing a component that needs useReducer. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
```

I encountered this error when upgrading from `13.0.2` to `13.0.3` in a project that uses Jotai. If one defines Jotai atoms in the same module as (as an example) related, but orthogonal, helper functions, then imports those helper functions into a server-only component, this error is raised.

**Comment by Fredkiss3** [comment]
@boatilus I think nextjs or more so react evaluate the components from top to bottom with imports firsts. But the logical reason i think is that when importing a package from a file, the bundler would have to include the package when compiling your file even if it is only used by different functions inside the file. 
And when you import a function from that file within a server-component, you will end up with an undefined import (`useReducer` in your example), since the client only packages and functions are not included within server-components. 

At scale i don't know why it would be problem, and if the helper functions could be used outside of the file which import them, it is not a bad idea to put them in a different file.

**Comment by boatilus** [comment]
That'd be the case if the import was *not* tree-shaken, yes. Please reference the [repro](https://github.com/boatilus/v13-false-client-error).

In this case: the exported function does not rely on a client-only construct, as tree-shaking would omit the imported module with the `useReducer` import, and the error is therefore non-constructive in this particular case.

**Comment by logemann** [comment]
I also have this bug. Just creating a simple API route like this one:

```
import type { NextApiRequest, NextApiResponse } from 'next'
import { headers, cookies } from 'next/headers';

type Data = {
  name: string
}

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  console.log(headers);
  res.status(200).json({ name: 'John Doe' })
}
```

Error is this:
```
One of these is marked as a client entry with "use client":
  pages/api/hello.ts
```

So NextJS treats this api route component as a client component?! In the beta docs there is no hint that API routes are not working with latest release so that i am still a bit unsure if this is really a bug.

**Comment by logemann** [comment]
@Fredkiss3 what exactly means thumbs down in this context?

**Comment by Fredkiss3** [comment]
@logemann 

You can only import { cookies } from 'next/headers'; inside of server components and **not anywhere else**.
In api handlers, you should use the `req` object with `req.headers` (I think) and `req.cookies`.

**Comment by jpreynat** [comment]
Same thing on my end.
I am using server-side logic code in a Server component with `server-only`, and it is working properly.
However, now I need to use the same logic in my API and my build is failing.

**Comment by m-foskett** [comment]
I am getting the same error as OP in a more complicated context but same issue of a call to API route handler from Client Component.  I am using Next.js 13.2.4

Context:
I am using `useSWR(key, fetcher)` with some data as an argument in a Client Component.
The fetcher/helper function is marked `server only` as it is using `getServerSession` (from next-auth) to get current user which is then used to get an active API key from a database using PrismaClient. API key is then used to do an authorised fetch with the data to a local API endpoint.

If I don't mark this fetcher/helper `server only`, then my db lookup throws an error as PrismaClient can not run in the browser.

What is the suggested method to make a call with user-inputted data from a Client component to an API route handler in Next.JS 13?

**Comment by Fredkiss3** [comment]
@m-foskett the fetcher could just be a `fetch("/api/your-data")` and  you cann getServerSession in your route handler. 

If this is not possible I would like to know more about why 🤔

**Comment by ovy9086** [comment]
😑 yep. valid bug.

**Comment by reza-ebrahimi** [comment]
This is also happening if your server component and client component exported at same level/place:

**Structure:**
```
\mixed_component
    \server_component_contains_next_headers
    \client_component_marked_use_client
    index.ts
```

**index.ts:**

```typescript
export * from "./server_component"; // contains import { cookies } from 'next/headers'; 
export * from "./client_component_marked_use_client";
```

If you import `mixed_component` somewhere, you will get the error:

```
You're importing a component that needs next/headers. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component.

One of these is marked as a client entry with "use client":
./mixed_component/index.ts
```

**Comment by purboindra** [comment]
hi, is there any solutions for this problem? i got this problem by adding headers from next/headers, and importing that file somewhere which is marked 'use client'.
_You're importing a component that needs next/headers. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component._

**Comment by OliverRC** [comment]
Upgraded from `13.4.4` -> `13.4.9` and now getting this error on `sitemap.ts`.
So definitely a bug :)

Reverted and will have to wait on a fix.

**Comment by timneutkens** [comment]
@OliverRC that sitemap issue has been fixed in 13.4.10 👍

**Comment by benminor** [comment]
@timneutkens I'm still getting `You're importing a component that needs next/headers. That only works in a Server Component which is not supported in the pages/ directory. Read more: https://nextjs.org/docs/getting-started/react-essentials#server-components` in next version 13.4.10

**Comment by timneutkens** [comment]
To clarify are you referring to `pages/api` or to sitemap.ts? Because the sitemap case was fixed.

**Comment by OliverRC** [comment]
I have upgraded to next `13.4.10`

Using the AppRouter I can confirm the issue with the `sitemap.ts` has been resolved.
I am able to use `import { headers } from 'next/headers';` without it throwing an error now.

**Comment by Phoenixmatrix** [comment]
Just throwing my name here for a 👍 for this issue, as I just hit it.

I use import "server-only" in my backend authentication code to make sure no one imports it in a client component tree. But I need to use the same code in server components as I do in APIs. Unfortunately, server-only fails in API routes, so I can't. I have to move it up to a wrapper or something made just for server components, but then my auth code is vulnerable to someone making an honest mistake.

It would be great if I could use server-only to poison my code against client side usage but still have it work with route handlers.

**Comment by timneutkens** [comment]
> It would be great if I could use server-only to poison my code against client side usage but still have it work with route handlers.

Route handlers should be fine. This issue in particular is about `pages/api`, not route handlers.

**Comment by matzkoh** [comment]
I'm using `pages/api` because tRPC doesn't support App Router yet. However, having `server-only` in the import chain from `pages/api/trpc/[trpc].ts` causes issues, and there seems to be no way to avoid it even with file splitting.

Currently, I have to comment out `import 'server-only'` to get around this problem.

**Comment by ksdaylight** [comment]
Hello every one,
I found a solution provided by someone else:
[this](https://github.com/vercel/next.js/discussions/44270#discussioncomment-6064242).

This bug is very inexplicable. I have been developing the project for a while, but today it suddenly fails to compile! sad...

**Comment by MincePie** [comment]
What is the proposed approach to adding a server component to a navbar?

My navbar has:

"use client"
import { useState } from 'react'
import { Dialog } from '@headlessui/react'
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline'
import LogoLnm from '../../components/LogoLnm'
import Authed from './Header'


export default function Example() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  return (
    <header className="bg-white">
      <nav className="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
        <div className="flex lg:flex-1">
         
        </div>
        <div className="flex lg:hidden">
          <button
            type="button"
            className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
            onClick={() => setMobileMenuOpen(true)}
          >
            <span className="sr-only">Open main menu</span>
            <Bars3Icon className="h-6 w-6" aria-hidden="true" />
          </button>
        </div>
        
        <div className="hidden lg:flex lg:flex-1 lg:justify-end">
          <a href="#" className="text-sm font-semibold leading-6 text-gray-900">
            Log in <span aria-hidden="true">&rarr;</span>
          </a>
        </div>
      </nav>
      <Dialog as="div" className="lg:hidden" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
        <div className="fixed inset-0 z-10" />
        <Dialog.Panel className="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
          <div className="flex items-center justify-between">
            <a href="#" className="-m-1.5 p-1.5">
              <span className="sr-only">Your Company</span>
              <img
                className="h-8 w-auto"
                src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                alt=""
              />
            </a>
            <button
              type="button"
              className="-m-2.5 rounded-md p-2.5 text-gray-700"
              onClick={() => setMobileMenuOpen(false)}
            >
              <span className="sr-only">Close menu</span>
              <XMarkIcon className="h-6 w-6" aria-hidden="true" />
            </button>
          </div>
          <div className="mt-6 flow-root">
            <div className="-my-6 divide-y divide-gray-500/10">
              
              <div className="py-6">
                <Authed />
              </div>
            </div>
          </div>
        </Dialog.Panel>
      </Dialog>
    </header>
  )
}

The Authed Component has:

```
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import Link from 'next/link'
import LogoutButton from '@/components/LogoutButton'
import { redirect } from 'next/navigation'
import Icon from '@/components/Logo'
const headers = import('next/headers')


export default async function Authed() {
    const supabase = createServerComponentClient<Database>({ cookies})
    const {
      data: { user },
    } = await supabase.auth.getUser()
  
    const { data: session } = await supabase.auth.getSession()
  
    if (!session) {
      redirect('/login')
    }

    return (
        <div>
            <Icon />

            {user ? (
              <div>
                <div className="flex items-center gap-4">
                  Hey, {user.email}!
                  <LogoutButton />
                </div>
                 
              </div>
            ) : (
              
                <Link
                  href="/login"
                  className="py-2 px-4 rounded-md no-underline bg-btn-background hover:bg-btn-background-hover"
                >
                  Login
                </Link>


                
             
            )}
        </div>
    )
}
```

I can't use cookies in the Authed if I want to use Authed in NavBar. How can I get the user if I can't store the cookie?

What is the the method to use a server component inside a page that also has state?
