### ISSUE TITLE
`font-weight` rendered  differently on Chrome with `@next/font`

### ISSUE THREAD

**Issue by Rawnly** [vercel/next.js#43761]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 7.12.0
    Relevant packages:
      next: 13.0.7-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/Rawnly/next-font-bug

### To Reproduce

- If you try to change the font weight on chrome based browsers (tested on Chrome and Arc) the font isn't bold as it should be (screenshot below). With firefox, this doesn't happen. On the https://github.com/mona-sans website this doesn't happen.

### Describe the Bug

Font weight is displayed differently on Chrome-based browsers.

**FIREFOX**
![CleanShot 2022-12-06 at 13 17 35@2x](https://user-images.githubusercontent.com/16429579/205910547-55627abb-d849-49c1-bc31-7853631268b1.png)

https://user-images.githubusercontent.com/16429579/205910890-768f2739-4b77-4cc0-944c-a2aaa56203a0.mp4

**CHROME**
![CleanShot 2022-12-06 at 13 18 05@2x](https://user-images.githubusercontent.com/16429579/205910579-009fe4b9-f77c-47a6-a1a3-ae75a5a86426.png)

https://user-images.githubusercontent.com/16429579/205910718-d30ccc7b-b8d8-422b-bc4a-17c130287e5c.mp4

### Other weird behaviors

- Comment `className` inside `src/pages/_document.tsx`, as you can see the <p> element loses his given font (mona-sans) even if there's a main tag inside _app that has the variable and is set as sans font in tailwind.config.js
- Remove fonts from the main tag. You can see that the app is unable to display all the fonts and the classNames to the HTML tag aren't applied.

### Expected Behavior

I would like to be able to change font weight on chrome. 

### Which browser are you using? (if relevant)

Chrome / Arc / Firefox

**Comment by hanneslund** [comment]
Try defining the available font weights of your variable font when loading the file.
```js
export const mona = localFont({
  src: "./Mona-Sans.woff2",
  variable: "--font-mona",
  weight: "200 900",
});
```

**Comment by maxeth** [comment]
I have the same issue, already spent hours trying to fix it but no luck so far. 

I noticed that if I deploy my site (to Vercel) and change the screen size of my browser, open the dev console or reload the page (without resetting the cache), the correct font is applied.

Also, in development, I can get it to work manually in the dev-console when I additionally add a font-family rule inside ```<style jsx>``` as shown below, simply by toggling the css-variable* ```--font-nunito``` . The moment I disable it in the dev-console, all fonts appear in their correct weight (which is weird because ```--font-nunito``` has the exact same value as ```font-family``` inside ```<style jsx>``` which is successfully applied to the ```html``` tag). 

```jsx
// pages/_app.js
import { Nunito } from '@next/font/google'

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin-ext"],
});
export default function MyApp({ Component, pageProps }) {
  return (
    <>
          <style jsx global>{`
            html {
              font-family: ${nunito.style.fontFamily};
            }
          `}</style>

         <div className={nunito.variable + " font-sans"}>
          <Component {...pageProps}  />
        </div>
    </>
  )
}
```

and

```jsx
// tailwind.config.js
const { fontFamily } = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} \*/
module.exports = {
 // [...]
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-nunito)', ...fontFamily.sans],
      },
    },
  },
  plugins: [],
}
```

**Comment by hanneslund** [comment]
@maxeth Have you tried ` subsets: ["latin"],` instead of `subsets: ["latin-ext"],`? Sounds like it doesn't preload correctly and the font doesn't show up because of `font-display: optional`.

**Comment by maxeth** [comment]
> @maxeth Have you tried ` subsets: ["latin"],` instead of `subsets: ["latin-ext"],`? Sounds like it doesn't preload correctly and the font doesn't show up because of `font-display: optional`.

I also tried "latin", and in both cases the network tab shows the fonts a (pre-?)loading on all browsers. Also, when I change the font-weight from 100 to 800, I see that the weight is changing slightly (barely noticeable, looks more like a blur), whereas on Firefox it changes correctly just as it's supposed to.

The same issue occurs if I import fixed weights and/or non-variable fonts with ```@next/fonts```: They only have the correct weight on Firefox. I've tweaked the configs and imports in every possible way but nothing helped.

**Comment by maxeth** [comment]
I have "fixed" the issue by adding ```display: "block"```, ```"swap"```  or ```"fallback"``` 

``` jsx
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  display: "block",
});
```

but I assume there could be some performance/UX drawbacks like layout shifting in specific cases, otherwise, this would already be the default, right?

 I've just tested it in production and the font loaded within 60ms without any issues, but I'm still wondering why it doesn't work properly with ```display: "optional"``` as in the docs.

**Comment by Rawnly** [comment]
> I have "fixed" the issue by adding display: "block", "swap" or "fallback"

Unfortunately, this didn't work for me 🫠. I tried all possible combinations and nothing changed so far...

**Comment by hanneslund** [comment]
> Try defining the available font weights of your variable font when loading the file.
> 
> ```js
> export const mona = localFont({
>   src: "./Mona-Sans.woff2",
>   variable: "--font-mona",
>   weight: "200 900",
> });
> ```

@Rawnly did you try this?

**Comment by Rawnly** [comment]
@hanneslund yes!

**Comment by Rawnly** [comment]
> @Rawnly did you try this?
@hanneslund it must have been some caching, now it works on chrome!

**Comment by hanneslund** [comment]
@maxeth could you provide a minimal reproduction of the problem you're having in a separate issue? 🙏

**Comment by maxeth** [comment]
@hanneslund I'd say I resolved my issue by adding ```display: "fallback"```, I was just wondering what Rawnly's solution was since he probably got it working with the default ```display: "optional"``` value.

**Comment by hanneslund** [comment]
@maxeth if you create a small reproduction I'll try to figure out why it didn't work with `"optional"` for you 👍

**Comment by maxeth** [comment]
@hanneslund  I just tried to identify the issue because the new repo I created worked perfectly fine, and I found out that the issue was caused by a very deeply nested component directly importing css files from library, which had some ```font-family``` styles. I'll replace it with modular css, which will fix the issue completely. 🙂

I should've tried creating a minimal reproduction from the very beginning, this seems to be the best way to debug things like these quickly.

**Comment by Rashair** [comment]
I'm still having this issue :| Both on Chrome and Firefox, but little differently.

**Comment by mooijtech** [comment]
I'm having this issue with `Inter` font loaded via `@next/font`.
WebKit doesn't seem to like the `variable` (`Inter var`) font type.
I ended up manually putting the `Inter` font files in `public` and using the non-variable version (just `Inter` not `Inter var`).

**Comment by mooijtech** [comment]
For Tailwind CSS I solved it via: https://levelup.gitconnected.com/how-to-make-next-js-13s-optimized-fonts-work-with-tailwind-css-c3c5e57d38aa
