### ISSUE TITLE
App directory RSC payloads are uncompressed (no gzip)

### ISSUE THREAD

**Issue by juanferreras** [vercel/next.js#43792]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.5
      pnpm: 7.1.9
    Relevant packages:
      next: 13.0.7-canary.1
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/juanferreras/app-directory

### To Reproduce

1. Clone the repository (it's an exact copy as of today of https://github.com/vercel/app-playground) OR deploy your own using https://vercel.com/templates/next.js/app-directory
2. Run `yarn && yarn build && yarn start`
3. Open a page such as `/ssg` and look into Network

### Describe the Bug

App directory uses RSC payloads to navigate from one route to another (where pages directory used JSON payloads), and they are currently served minified but not compressed (with gzip, like all other static assets Next.js does)

<img alt="RSC payloads do not have Content-Encoding=gzip header" src="https://user-images.githubusercontent.com/8507996/206033560-ee01009b-c3e1-4ccb-9658-85e2e1dd698c.png" width="500" />

### Expected Behavior

Unless there's any (undocumented) technical reason that yields it impossible, **RSC payloads should ideally be compressed** so they don't end up weighing significantly more than their previous JSON counterparts (not that their weights are necessarily comparable, but should ideally be in the same order of magnitude)

### Which browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

Vercel but N/A (e.g. Vercel isn't compressing these resources either, but Next.js should be consistent with compressing all resources)

**Comment by Fredkiss3** [comment]
Did NextJs in previous version compress the other payloads and static files with gzip ?

And is technically possible to compress responses with gzip by using a web server like nginx ?

**Comment by juanferreras** [comment]
> Did NextJs in previous version compress the other payloads and static files with gzip ?

@Fredkiss3 Correct, see https://nextjs.org/docs/api-reference/next.config.js/compression. Next.js by default compresses JS chunks, JSON payloads, etc with gzip. When deployed to Vercel, these files are compressed with brotli (if `Accept-Encoding` supports it).

When using the app directory, all these files are still compressed, but RSC payloads are not.

> And is technically possible to compress responses with gzip by using a web server like nginx ?

I'd assume this is possible, but should be an edge case instead of the default behavior.

**Comment by Fredkiss3** [comment]
You are totally right, on vercel it should be compressed by default. But on a custom server they recommend to offload the process to a web server : 

> Next.js provides [gzip](https://tools.ietf.org/html/rfc6713#section-3) compression to compress rendered content and static files. In general you will want to enable compression on a HTTP proxy like [nginx](https://www.nginx.com/), to offload load from the Node.js process.
