### ISSUE TITLE
Docs: Breaking change cookies with version 13.0.1

### ISSUE THREAD

**Issue by joan-saum** [vercel/next.js#43815]
### What is the improvement or update you wish to see?

In the release 13.0.1, there is a breaking change regarding the usage of cookies, from this commit: https://github.com/vercel/next.js/pull/41526

But this breaking change is not mentioned in the release page: https://github.com/vercel/next.js/releases/tag/v13.0.1

### Is there any context that might help us understand?

I'm a developer, I want to upgrade my nextjs version to the latest. I see there is no breaking changes in the version 13.0.1. I update and I face some errors regarding the cookies

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/releases/tag/v13.0.1

**Comment by leerob** [comment]
Hey there, apologies our communication wasn't great here. The documentation should be up-to-date here now.
