### ISSUE TITLE
NextJS after updating from 13.0.4 to 13.0.6 next/image blur placeholder not working properly

### ISSUE THREAD

**Issue by cantutar** [vercel/next.js#43829]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.18.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

npm i next@latest

### To Reproduce

After updating nextjs from 13.0.4 to 13.0.6

### Describe the Bug

it broke all the blurdataurl shimmer effect, it is not shimmering at all its just sticking to image

its even in my production for example https://www.playerse.net/valorant/agents

### Expected Behavior

Expected behaviour was shimmer image while loading and load image properly

### Which browser are you using? (if relevant)

Chrome 108.0.5359.99, Firefox dev edition 108.0b9 (64-bit

### How are you deploying your application? (if relevant)

Vercel

**Comment by snelsi** [comment]
Related:
https://github.com/vercel/next.js/issues/43689
https://github.com/vercel/next.js/pull/43587

**Comment by tomer-tgp** [comment]
Same here: https://dev.goodparty.org/
