### ISSUE TITLE
Next13 appDir: Styled components that get rendered at a later time have no styles

### ISSUE THREAD

**Issue by Fluxium2006** [vercel/next.js#43858]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: >8.0.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.1
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Fluxium2006/Next13-SC-Test

### To Reproduce

1. Clone the above repo
2. npm i
3. Go to http://localhost:3000/

To implement styled-components in the appDir, I was following this guide: [https://beta.nextjs.org/docs/styling/css-in-js#styled-components](https://beta.nextjs.org/docs/styling/css-in-js#styled-components)

### Describe the Bug

In a `page.tsx` marked as a client component (`"use client"`) in the appDir, any styled component that is not rendered on the initial page render, but instead after a certain condition has been met, has no styles applied to it. The styles it should have are not in the `style` tag in the `head` element.

The bug was tested in 13.0.6 and 13.0.7-canary.1 and occurs there. Using the above repo and Next version 13.0.7-canary.3 I get the following error and could not fully test it:

```
Unhandled Runtime Error
TypeError: originalFactory is undefined
```

### Expected Behavior

The element should render correctly with it's styles appearing / or already being in the `styles` tag.

### Which browser are you using? (if relevant)

Firefox 107.0.1

### How are you deploying your application? (if relevant)

next dev, next start

**Comment by huozhi** [comment]
Duplicate with #42526. Please checkout the comment https://github.com/vercel/next.js/issues/42526#issuecomment-1343263346
