### ISSUE TITLE
Dev mode error: "originalFactory is undefined" when importing client component ("use client") from other package

### ISSUE THREAD

**Issue by reiv** [vercel/next.js#43902]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 19.0.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.4
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

Repro here: https://github.com/reiv/next-canary-test

### To Reproduce

- clone the repro
- install deps
- run `next dev` in the `apps/web`
- observe error immediately after page loads

### Describe the Bug

(The repro is based on the turborepo starter, modified to use `appDir: true` as well as the latest canary.)

Importing a React client component from a module outside of the Next app causes `TypeError: originalFactory is undefined`. This only occurs in dev mode, and seems to be limited to client components ("use client") - non-client components can be imported without error.

The bug exists as of `13.0.7-canary.3` (`13.0.7-canary.1` works fine).

### Expected Behavior

No error in dev mode.

**Comment by Fluxium2006** [comment]
I have the same error running this repo in dev https://github.com/vercel/app-playground

**Comment by reiv** [comment]
Possibly a Windows-only bug, just tested on a different machine with no issues.

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021
    Binaries:
      Node: 19.2.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.18.2
    Relevant packages:
      next: 13.0.7-canary.4
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0
```

What about you @Fluxium2006 ?

**Comment by rafma0** [comment]
Looks the same as https://github.com/vercel/next.js/issues/43854 , the bug is still present in canary.6 on Windows
