### ISSUE TITLE
CSS doesn't load correctly in client-side navigation

### ISSUE THREAD

**Issue by mjr** [vercel/next.js#43926]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64
Binaries:
  Node: 16.17.1
  npm: 8.15.0
  Yarn: 1.22.19
  pnpm: 7.18.1
Relevant packages:
  next: 13.0.7-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/mjr/nextjs-css-repo/

### To Reproduce

Go to https://codesandbox.io/p/github/mjr/nextjs-css-repo/draft/crimson-monad/
Click on the link to go to the Dashboard.
Click on the link to go back to home.
See that now the color of the home page is green, after having loaded the CSS of the dashboard.

### Describe the Bug

The dashboard style is not being removed when returning to home page, the opposite also happens, if I start on the dashboard page (SSR), go to home page and return to the dashboard, the dashboard layout turns red.

Starting at: `http://localhost:3000`

![Kapture 2022-12-10 at 14 50 31](https://user-images.githubusercontent.com/9324986/206868781-7f0126b5-ca50-404f-ad37-a0665ac0733a.gif)

Starting at: `http://localhost:3000/dashboard`

![Kapture 2022-12-10 at 14 52 58](https://user-images.githubusercontent.com/9324986/206868785-94cd5868-ac5c-4715-ae0c-8d488e235a74.gif)

### Expected Behavior

What is expected is the layouts do not conflict with each other.

### Which browser are you using? (if relevant)

Chrome 108.0.5359.98

**Comment by rainwashed** [comment]
I am also facing the same issue.

**Comment by diogovdias** [comment]
Is there any solution for this bug? It completely messes up the styling when navigation between routes.

**Comment by nandorojo** [comment]
Same exact thing happening for me. Any progress for you guys? When I refresh the page it works fine, but when routing client-side, it isn't loading `import './some-file.scss'`.

**Comment by mjr** [comment]
cc: @shuding @timneutkens

**Comment by nandorojo** [comment]
no need to ping maintainers. they have a lot on their plates and will get to this when they can.

**Comment by timneutkens** [comment]
When using global CSS it's up to you to ensure there is proper scoping. Without scoping it can indeed happen that if you use multiple global imports they override each-other. There is no guarantee on when styles will unload, this is managed by React.

Previously you could only import global styles from `_app.js`, we introduced this limitation to ensure you wouldn't have to ensure scoping is correct, however a lot of feedback was that it is too strict and they know what they're doing. We lifted the limitation, this still means it's up to you to handle scoping conflicts.

**Comment by mjr** [comment]
@timneutkens, just to confirm, so it's not possible in next.js to have this same behavior as the remix? (https://codesandbox.io/p/github/mjr/remix-css-test/)

I created an example in next.js of how I thought it worked, importing the css in `page.js` it shouldn't appear in other pages, or did I get it wrong? I thought that only `layout.js` would be shared. (https://codesandbox.io/p/github/mjr/next-css-test/)

**Comment by timneutkens** [comment]
CSS is not unloaded because it needs to be there when you e.g. have animations running when loading the page. Unloading would mean you can see a FOUC when navigating back, or you lose scroll restoration because of it not being fast enough to load. CSS loading is handled by React now, unlike in `pages`, we just provides the stylesheets to React.

**Comment by mjr** [comment]
Don't you think it might make sense to have an option to do this, where the developer knows these points you mentioned, but also knows it's safe to do for your use case? Since this comes from React, does it not have an option to say it's safe to remove the CSS?
