### ISSUE TITLE
Module parse failed: Octal literal in strict mode (61:65)

### ISSUE THREAD

**Issue by alexmf91** [vercel/next.js#43930]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/alexmf91/eth-solidity-web3/tree/master/crowd-coin

### To Reproduce

Server component that throws the error: 
```
import factory from '@crowd-coin/ethereum/factory'
import CampaignsList from './components/CampaignList'

const getCampaigns = async () => {
  const campaigns = await factory.methods.getDeployedCampaigns().call()
  return campaigns
}

export default async function Campaigns() {
  const campaigns = await getCampaigns()

  return (
    <div>
      <p>Home Page app campaigns {JSON.stringify(campaigns)}</p>
      <CampaignsList items={campaigns} />
    </div>
  )
}
```

Client component that works as spected:
```
'use client'

import { useEffect } from 'react'
import factory from '@crowd-coin/ethereum/factory'

export default function CampaignsList({ items }: any) {
  const campaigns = 'await getCampaigns()'
  useEffect(() => {
    async function getCampaigns() {
      const campaigns = await factory.methods.getDeployedCampaigns().call()
      console.log('Campaings', campaigns)
    }
    getCampaigns()
  }, [])

  return <p>CampaignsList component {JSON.stringify(items)}</p>
}
```
Web3 lib config:
```
import Web3 from 'web3'

let web3

if (typeof window !== 'undefined' && typeof window.ethereum !== 'undefined') {
  console.log('Web3 browser instance')
  // We are in the browser and metamask is running.
  window.ethereum.request({ method: 'eth_requestAccounts' })
  web3 = new Web3(window.ethereum)
} else {
  console.log('Web3 server instance')
  // We are on the server *OR* the user is not running metamask
  const provider = new Web3.providers.HttpProvider(
    'https://goerli.infura.io/v3/APIKEY'
  )
  web3 = new Web3(provider)
}

export default web3
```
### Describe the Bug

When I run the dev server with a call to web3 in the server it throws me the following error:
```
error - ./node_modules/tar/lib/header.js
Module parse failed: Octal literal in strict mode (61:65)
File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-flight-loader/index.js
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
|         if (this[TYPE] === "5") this.size = 0;
|         this.linkpath = decString(buf, off + 157, 100);
>         if (buf.slice(off + 257, off + 265).toString() === "ustar\000") {
|             this.uname = decString(buf, off + 265, 32);
|             this.gname = decString(buf, off + 297, 32);
```
### Expected Behavior

I expect to be able to build properly the dev server, and run the function in server side as runs in client side.

**Comment by alexmf91** [comment]
Some help would be nice. Thx

**Comment by JonCognioDigital** [comment]
I am getting a similar error (Module parse failed: Octal literal in strict mode) with the most basic app/layout.tsx and app/page.tsx

**Comment by devdreamsolution** [comment]
I am getting a same error after upgrading the version 13.3.0 in app directory beta version.

**Comment by Alldrich** [comment]
I am getting same error after upgrading to 13.3.0.

**Comment by RETOVSKEJ** [comment]
same in 13.3.1

**Comment by ccweerasinghe1994** [comment]
I am getting same error after in 13.3.0.

**Comment by namln2k** [comment]
I am getting the same error with Next.js 13.3.0
I found an answer on Stackoverflow, which seems weird but works.
That guy just changes from
`export default function RootLayout() { /** ... */ }`
to
`function RootLayout() { /** ... */ }
export default RootLayout`

**Comment by kdy1** [comment]
This should be fixed on the latest canary.

**Comment by kdy1** [comment]
Closing as fixed
