### ISSUE TITLE
Dynamic data and server-side code does not work in middleware.js

### ISSUE THREAD

**Issue by MohammadMiras** [vercel/next.js#43940]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
Platform: linux
Arch: x64
Version: #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
Binaries:
Node: 18.12.1
npm: 9.1.2
Yarn: 1.22.19
pnpm: N/A
Relevant packages:
next: 13.0.7-canary.4
eslint-config-next: 13.0.6
react: 18.2.0
react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/MohammadMiras/NextRedirectionDynamicDataProblem

### To Reproduce

- Clone the repo
- `npm install`
- `npm dev run`
- It throws an error

### Describe the Bug

I want to use `middleware.js` to apply redirections. The redirection data comes from an API because it's dynamic.

And because it does not change that much and because of the reason of performance, we can't call the API for each request. 

Also because our SEO data is very dynamic, we can't restrict requests to some specific requests. This means that we need to:

- Get dynamic data from API
- Store/retrieve it on/from hard as a cache mechanism

But it does not work.

### Expected Behavior

We should be able to run node.js code in `middleware.js`. And we should be able to call APIs there.

**Comment by renatoandre1175** [comment]
Estou com problema aqui está dando erro 451 , por favor me ajuda
