### ISSUE TITLE
Serverless Function has timed out if adding any icon from @mui/icons-material at _app.tsx page

### ISSUE THREAD

**Issue by dev-ahmedhany** [vercel/next.js#43957]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

The bug at Vercel's server (or netlify) not at localhost

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.18.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/dev-ahmedhany/nextjs-mui-bug

### To Reproduce

any icon from @mui/icons-material at _app.tsx page

### Describe the Bug

getting error Serverless Function has timed out at any serverless function if added any icon from @mui/icons-material at _app.tsx page

### Expected Behavior

running the serverless function

### How are you deploying your application? (if relevant)

vercel, netlify

**Comment by smaeda-ks** [comment]
@dev-ahmedhany 
Have you checked https://github.com/vercel/next.js/issues/23187#issuecomment-1021574886 ?
See also: https://mui.com/material-ui/guides/minimizing-bundle-size/#development-environment

**Comment by balazsorban44** [comment]
See the above, and also: https://nextjs.org/docs/advanced-features/compiler#modularize-imports

**Comment by dev-ahmedhany** [comment]
@balazsorban44 

[modularize-imports](https://nextjs.org/docs/advanced-features/compiler#modularize-imports)  worked the best

this general version didn't work
```
// next.config.js
module.exports = {
  experimental: {
    modularizeImports: {
      'my-library/?(((\\w*)?/?)*)': {
        transform: 'my-library/{{ matches.[1] }}/{{member}}',
      },
    },
  },
}
```

i had to write this

```
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    modularizeImports: {
      "@mui/material": {
        transform: "@mui/material/{{member}}",
      },
      "@mui/icons-material": {
        transform: "@mui/icons-material/{{member}}",
      },
    },
  },
};
```

[minimizing-bundle-size](https://mui.com/material-ui/guides/minimizing-bundle-size/#development-environment) falling back to babel it fixes the bug but slow at build at Vercel servers


Is there any relation between **serverless function** and **_app** file that I can make benefit from?
