### ISSUE TITLE
Regression of middlewares performance in next dev (v13)

### ISSUE THREAD

**Issue by ValentinH** [vercel/next.js#43999]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Binaries:
  Node: 16.18.1
  npm: 8.19.2
  Yarn: 1.22.17
  pnpm: N/A
Relevant packages:
  next: 13.0.7-canary.5
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/ValentinH/next-13-midlewares-regression

### To Reproduce

- create a simple API route (the one from the `create-next-app` example does the job)
- add a middleware simply returning `NextResponse.next()`
- run with `next dev`
- load test the API route

I shared a script in the reproduction repository for the load test.

### Describe the Bug

While trying to upgrade our applications to Next.js 13, we noticed that some of our E2E tests were failing due to timeouts. After digging into it, we noticed that our API routes were much slower than on v12.

It turns out that this is related to the fact that we are using middlewares to protect our API.
Removing them fixes the slowner.

### Expected Behavior

Middlewares should be, at least, as fast as on v12.

**Comment by NOtherDev** [comment]
I think it might be the same issue I'm facing: https://github.com/vercel/next.js/discussions/44053
From my perspective, though, `next build` prod configuration isn't affected, is it?

**Comment by ValentinH** [comment]
Indeed, I can confirm that this issue is only happening when running `next dev`.

**Comment by FreeWall** [comment]
I can confirm this as well using middleware, prod build is roughly the same speed as v12, dev is much slower.

**Comment by ValentinH** [comment]
I just tried with the latest 13.1.6 version (I updated the linked repository) and the issue is still present.

**Comment by ValentinH** [comment]
Still present in 13.2.3.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.2.5-canary.28` of Next.js, please update and give it a try!

**Comment by ValentinH** [comment]
I confirm that this is fixed, thanks for this!

Just a side note: v13 is still slower than v12 for the test I made but nothing comparable to the original issue.

**next 12**
![image](https://user-images.githubusercontent.com/2678610/229445113-d9eef604-b05a-4fd6-be22-acbc5513cd9b.png)


**next 13**
![image](https://user-images.githubusercontent.com/2678610/229445167-1548d90c-9398-416f-8985-0bbade43edf3.png)
