### ISSUE TITLE
I have migrated from babel to swc. But started getting error regarding JSX support only with production environment.

### ISSUE THREAD

**Issue by gvete** [vercel/next.js#43994]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 "next": "^13.0.6",

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue

https://github.com/vercel/next.js

### To Reproduce

Run next js with production env. 

### Describe the Bug

The app was working properly with preset-react classic babel cofiguration. I tried it setting that with swc. But still no success.

> Server Error
> TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxDEV) is not a function
> 
> This error happened while generating the page. Any console logs will be displayed in the terminal window.
> Source
> src/pages/_document.tsx (103:5) @ style
> 
>   101 | const emotionStyles = extractCriticalToChunks(initialProps.html);
>   102 | const emotionStyleTags = emotionStyles.styles.map((style) => (
> > 103 |   <style
>       |   ^
>   104 |     data-emotion={`${style.key} ${style.ids.join(' ')}`}
>   105 |     key={style.key}
>   106 |     // eslint-disable-next-line react/no-danger
> Call Stack
> map
> src/pages/_document.tsx (102:48)
> Show collapsed frames

### Expected Behavior

No issue with production.

**Comment by CamPCatDev** [comment]
do u need help

**Comment by dhruvkelawala** [comment]
Do you still face this issue? Have you managed to solve it?

**Comment by gvete** [comment]
I have migrated to new appdir. That helps to solve my problem.

**Comment by kdy1** [comment]
Closing as there's no valid repro
