### ISSUE TITLE
Support removing trailing slash on void HTML elements

### ISSUE THREAD

**Issue by wscourge** [vercel/next.js#43995]
### Describe the feature you'd like to request

I'd like Next.js to support removing trailing slash from void HTML elements. Due to [validator.w3.org](https://validator.w3.org):

> Info: Trailing slash on void elements [has no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interacts badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values).

### Describe the solution you'd like

Ideally, it'd just work out of the box - I don't see any downsides.

### Describe alternatives you've considered

I didn't consider any alternatives.

**Comment by lachlanjc** [comment]
This behavior is far upstream of Next.js in the design of JSX, Babel, and swc. Personally, I would rather not see Next adopt this, as it’d make React code in Next apps incompatible with React code elsewhere, while not providing a tangible benefit beyond accommodating an aesthetic preference to the ecosystem, and making JSX code less clear to read (I think void elements having a syntactic indication makes them clearer than traditional HTML), so I think it’d be a net loss.

**Comment by wscourge** [comment]
What about incorporating only into the built HTML? This is what I meant in the first place, and I don't see how it affects **React** code.

**Comment by SukkaW** [comment]
@wscourge 

I understand the feature you are requesting. However, implementing this would introduce extra performance overhead and it could break React DOM Stream SSR.
IMHO you can request the feature to `facebook/react` directly since it is related to how `ReactDOMServer` produces HTML.

**Comment by wscourge** [comment]
OK, thank you for pointing me in the right direction. Keep up the good work, cheers.

**Comment by h-harsh** [comment]
Is there any alternate solution to this? @wscourge ?

**Comment by wscourge** [comment]
No, I haven't.
