### ISSUE TITLE
NPM EXPORT : Cannot find module for page: /

### ISSUE THREAD

**Issue by vitali-duckma** [vercel/next.js#44002]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Npm build works ok, but when tried to export, I get this error:
Cannot find module for page: /
![Screenshot 2022-12-13 alle 14 38 03](https://user-images.githubusercontent.com/118166188/207339013-49182209-38b5-4059-b0a5-b1f6d86ffbac.png)

It exports 404.html but the index.html is empty (see photo)

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app), Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue

no link

### To Reproduce

Try to export an app using appDir

### Describe the Bug

Npm build works ok, but when tried to export, I get this error:
Cannot find module for page: /

### Expected Behavior

It must work well

### Which browser are you using? (if relevant)

chrome

<sub>[NEXT-1388](https://linear.app/vercel/issue/NEXT-1388/npm-export-cannot-find-module-for-page)</sub>

**Comment by CamPCatDev** [comment]
do u need help?

**Comment by JoshPav** [comment]
Also facing this issue myself. I get a different page each time I run the command too, which to me indicates there could be some kind of race condition going on. 

```
Build attempt | Output
#1            | PageNotFoundError: Cannot find module for page: /
#2            | PageNotFoundError: Cannot find module for page: /error-handling
#3            | PageNotFoundError: Cannot find module for page: /context
#4            | PageNotFoundError: Cannot find module for page: /error-handling
```

For anyone looking to reproduce it seems if you modify the `build` script of the [Next13 App Playground](https://github.com/vercel/app-playground) so it runs `next export`:

```
...
 "scripts": {
    "build": "next build && next export",
    ...
```
 the issue will manifest itself.

In the [App Directory Roadmap](https://beta.nextjs.org/docs/app-directory-roadmap)  they do mention that `next export` is still a WIP.
```
Section       | Feature     | Supported
...
Configuration | next export | 🏗️
```

However, the way the docs explain the process of SSG I would infer that Next13 should support `next export`. 

Is anyone able to confirm is this is something we will need to wait for? Or perhaps a piece of configuration that is missing to enable this?

**Comment by vitali-duckma** [comment]
I separated the build & export commands, builds ok, but when try to export gives that error.

**Comment by vitali-duckma** [comment]
> WIP

How much it will take to fix it?? Can we see any progress percentage?? Or at leat how we can "temporarily" fix it.

**Comment by CamPCatDev** [comment]
do you have discord? @vitali-duckma

**Comment by vitali-duckma** [comment]
> 

vity31#7223 my username

**Comment by CamPCatDev** [comment]
accept it @vitali-duckma

**Comment by simonpkerr** [comment]
I'm seeing the same issue, a different error each time. in the log i see, `No "exportPathMap" found in "XXXX/next.config.js". Generating map from "./pages"` even though there isn't a 'pages' dir

**Comment by Erlesand** [comment]
@simonpkerr When using the new /app directory, there currently is no support for using next export, it is listed as work in progress on the [roadmap](https://beta.nextjs.org/docs/app-directory-roadmap#supported-and-planned-features).

I do not think there currently is any more information about when this will be added, but maybe someone else has got some information about that? :)

**Comment by shinebayar-g** [comment]
Oh this is unfortunate, @Erlesand thanks for the hint.

**Comment by CHNsPart** [comment]
same issue, 
`PageNotFoundError: Cannot find module for page: /
    at Object.getPagePath (D:\Work\Clients\JFTL - AZMA\.code\JFTL-Project\node_modules\next\dist\server\require.js:77:15)`

**Comment by santi020k** [comment]
`Note: Support for static exports is currently only available on next@canary. This will be included in Next.js 13.3 shortly.
` 
You can use:
npm i next@canary react@latest react-dom@latest eslint-config-next@latest

**Comment by CamPCatDev** [comment]
do npm i next@canary react@latest react-dom@latest eslint-config-next@latest

**Comment by davetapley** [comment]
⚠️  Be sure to set `output: 'export'` in `next.config.js` per [here](https://beta.nextjs.org/docs/configuring/static-export#configuration).

Also note you don't need to `next export` any more, `yarn build` will produce `out/`.

**Comment by allestaire** [comment]
> ⚠️ Be sure to set `output: 'export'` in `next.config.js` per [here](https://beta.nextjs.org/docs/configuring/static-export#configuration).
> 
> Also note you don't need to `next export` any more, `yarn build` will produce `out/`.

Nope, tried this, it work create an `out` directory

**Comment by johnfruit** [comment]
problem on version next.js 13.2
my issue was fix with the following

1)  run npm i next@latest react@latest react-dom@latest eslint-config-next@latest
2) on your next.config.js inside nextConfig const add output: 'export'
3)  I also dont add next export to my package.json

please follow this link
https://nextjs.org/blog/next-13-3

and see the section of Static Export for App Router
