### ISSUE TITLE
Error: Image import ... is not a valid image file. The image may be corrupted or an unsupported format.

### ISSUE THREAD

**Issue by Gregliest** [vercel/next.js#44012]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: linux
      Arch: x64
      Version: #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022
    Binaries:
      Node: 18.10.0
      npm: 8.19.2
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

https://github.com/Gregliest/Blog/blob/photo1/pages/index.tsx

### To Reproduce

Run `yarn dev` and go to localhost:3000. You should see the error message.

### Describe the Bug

Note: I did not verify the canary build because this issue does not exist on a clean project. I simply can't find the configuration difference that leads to this issue.

# Issue
I'm trying to use a static image import, and it fails with the message, `Error: Image import "../public/static/lake.jpg" is not a valid image file. The image may be corrupted or an unsupported format.` The image is valid, so at the very least the error message is incorrect. The failing import is [here](https://github.com/Gregliest/Blog/blob/photo1/pages/index.tsx#L13). 

# Things I tried
- New project -> I tried the same code in a new project, and it worked as expected. So, the issue is not with the jsx code or the image itself. 
- `yarn install`
- Updating next to 13.0.6

Thanks in advance for your help.

### Expected Behavior

I expect the image to be imported and show up on my page. 

### Which browser are you using? (if relevant)

Firefox 107.0.1

### How are you deploying your application? (if relevant)

Vercel

**Comment by RomainSF** [comment]
I can't find where this error is coming from, but here is how I fixed it:

added:
images: {
    formats: ['image/webp'],
},

to next.config.js

**Comment by Gregliest** [comment]
Thanks for the clue, I found the [issue](https://github.com/Gregliest/Blog/blob/photo1/next.config.js#L73-L84) in next.config.js.

**Comment by Razorshnegax018** [comment]
> Thanks for the clue, I found the [issue](https://github.com/Gregliest/Blog/blob/photo1/next.config.js#L73-L84) in next.config.js.

Can you explain your fix? I'm having a [very similar problem](https://github.com/expo/expo-cli/issues/4613) with the same exact error but in a different next environment.
