### ISSUE TITLE
Doesn't build on OpenBSD

### ISSUE THREAD

**Issue by dante-robinson** [vercel/next.js#44058]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: openbsd
      Arch: x64
      Version: GENERIC.MP#890
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.0.7-canary.7
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Static HTML Export (next export)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/tree/canary/examples/reproduction-template

### To Reproduce

`yarn build`

 or 

`yarn run dev`

### Describe the Bug

Crashes during build time.

```
yarn run v1.22.18
$ next build
/home/user/reproduction-app/node_modules/next/dist/build/swc/index.js:70
const triples = _triples.platformArchTriples[PlatformName][ArchName] || [];
                                                          ^

TypeError: Cannot read properties of undefined (reading 'x64')
    at Object.<anonymous> (/home/user/reproduction-app/node_modules/next/dist/build/swc/index.js:70:59)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/user/reproduction-app/node_modules/next/dist/build/analysis/parse-module.js:9:12)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

No crash.

**Comment by gjskha** [comment]
I'm seeing this same behavior on OpenBSD 7.2 with Node.js v18.12.1 running the example code at https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs .

**Comment by gjskha** [comment]
The trouble is caused by the OS sniffing done here:
/next/dist/lib/download-wasm-swc.js
and the uglified code at:
next/dist/compiled/@napi-rs/triples/index.js

Problem is that it doesn't know about OpenBSD and NetBSD at all. I got it to work by copying the FreeBSD section appropriately. In theory OpenBSD and NetBSD have a few more platforms though.

**Comment by dante-robinson** [comment]
> The trouble is caused by the OS sniffing done here: /next/dist/lib/download-wasm-swc.js and the uglified code at: next/dist/compiled/@napi-rs/triples/index.js
> 
> Problem is that it doesn't know about OpenBSD and NetBSD at all. I got it to work by copying the FreeBSD section appropriately. In theory OpenBSD and NetBSD have a few more platforms though.

Did you get it working at all? We had found an issue on FreeBSD where auto refresh isn't working but assumed this is on the React side was just curious if the same on OpenBSD.

https://forums.freebsd.org/threads/reactjs-project-no-autorefresh-on-freebsd.84108/

**Comment by gjskha** [comment]
I got it to compile and run but auto-refresh doesn't work. Maybe this piece of output is relevant or helpful.

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using wasm build of next-swc
warn  - Attempted to load @next/swc-openbsd-x64, but it was not installed
event - compiled client and server successfully in 473 ms (159 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 514 ms (169 modules)
```

I am happy to file a PR for the changes I did make. I couldn't figure out where on my own.

**Comment by dante-robinson** [comment]
> I got it to compile and run but auto-refresh doesn't work. Maybe this piece of output is relevant or helpful.

Same issue as mentioned above on FreeBSD then. I assume this is a React issue though since others in that post had issues with it on React as well.

> I am happy to file a PR for the changes I did make. I couldn't figure out where on my own.
You will need to clone the repo and push the change to your cloned repo and then it should let you open a PR to submit it.
