### ISSUE TITLE
Can't read headers set in middleware using the headers function on server components

### ISSUE THREAD

**Issue by focux** [vercel/next.js#44051]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: 7.18.1
    Relevant packages:
      next: 13.0.7-canary.7
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/s/jovial-pine-ntpftb

### To Reproduce

1. Create a middleware and set a header using the NextResponse helper.
2. Create a server component and log the headers using the `next/headers` function.

### Describe the Bug

When you set a header in a middleware, you can't read it using the `next/headers` function. However, when I inspect the network request of the page, I see that the header that I set it's there, it's just that you can't read it using the `next/headers` function.

### Expected Behavior

To be able to read the headers set in a middleware using the `next/headers` function.

### Which browser are you using? (if relevant)

Chrome

**Comment by Angusross111** [comment]
You need to set the Headers on the Request rather than the Response.
https://github.com/Angusross111/reproduction-app-middleware-cookies/blob/header-fix/middleware.ts
