### ISSUE TITLE
Images imported by dynamically imported component (even transitively) are not built in DEV

### ISSUE THREAD

**Issue by nicknotfun** [vercel/next.js#44068]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
    Binaries:
      Node: 18.1.0
      npm: 8.8.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.0.8-canary.0
      eslint-config-next: 13.0.7
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue

https://github.com/nicknotfun/dynimp

### To Reproduce

README in repository is up to date, but I believe any dynamic import component that then imports a static image transitively would have the issue.

1. Run `yarn dev`

### Describe the Bug

Observe that the dynamically loaded component is present, however the image it refers to (itself a regular import) is not processed by the dev server and is a broken image.

### Expected Behavior

The image works consistently.

Potential basis for workaround: This is fixed by directly visiting the dynamically loaded page.

**Comment by nicknotfun** [comment]
FYI, in the 'real world' example - we happen to also be using a custom server, wrapped in a custom start script (as the example repository shows however, this isn't relevant to the bug). So have implemented a work-around of pre-warming the dynamic components - and this works.

**Comment by itsajay1029** [comment]
Are you working on this @huozhi ?

**Comment by mkhotib20** [comment]
same problem here

**Comment by milo-** [comment]
@huozhi there are now multiple issues tracking this #44143 and #44658
