### ISSUE TITLE
next-sanity is using older version of sanity

### ISSUE THREAD

**Issue by Guneetsinghtuli** [vercel/next.js#44076]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I have a problem running this command. It's showing many errors but I don't think that the problem might be because of the environment.

### Which example does this report relate to?

cms-sanity

### How are you deploying your application? (if relevant)

next

### Describe the Bug

Please have a look at this [File](https://github.com/vercel/next.js/blob/canary/examples/cms-sanity/package.json). the current latest version of next-sanity is 3.1 and in the example, we are using 0.3.

It would be really helpful if we could upgrade the version as many things have updated and fails to run on upgrading.

### Expected Behavior

The project should be expected to work with the latest next-sanity integration, And I would love to work on this project as well to upgrade it.  

### To Reproduce

After cloning the repo, you can try to upgrade the next-sanity package by `**npm i next-sanity@latest**` After running it if you try to start the project, many things might break in the application.

**Comment by ciruz** [comment]
@leerob the outdated Sanity version got updated 3 months ago with this PR https://github.com/vercel/next.js/pull/45662 

https://github.com/vercel/next.js/blob/canary/examples/cms-sanity/package.json

**Comment by leerob** [comment]
Awesome, thank you!
