### ISSUE TITLE
Edge API routes exclude src directory

### ISSUE THREAD

**Issue by nickbabcock** [vercel/next.js#44077]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.17.1
    Relevant packages:
      next: 13.0.7
      eslint-config-next: 13.0.7
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/nickbabcock/rl-web

### To Reproduce

Switch config of `src/pages/api/replay` to:

```ts
export const config = {
  runtime: "edge",
};
```

And execute `npm run dev`.

(apologies, the repo isn't technically a minimal reproduction (as 13.0.7, seems to break in other ways), but the issue / solution should be clear. If not I'll create one a minimal reproduction).

### Describe the Bug

[Next.js supports](https://nextjs.org/docs/advanced-features/src-directory) putting pages in the `src` directory.

So when I tried testing GA version of edge functions (#44045 cc @feugy), I received the following error:

> Page /src/pages/api/replay provided runtime 'edge', the edge runtime for rendering is currently experimental. Use runtime 'experimental-edge' instead.

[I see that #44045 looks if the route starts with `/pages`](https://github.com/vercel/next.js/pull/44045/files#diff-cb7ac6392c3dd707c5edab159c3144ec114eafea92dad5d98f4eedfc612174d2R346) so a `/src/pages` route throws it off. The solution seems like it should look in the `src` directory too.

A temporary workaround is to move the pages outside of the `src` directory.

### Expected Behavior

If `src` directory is supported then edge API routes hosted in `src/pages/api` shouldn't error.

**Comment by controversial** [comment]
Here’s a minimal reproduction: https://github.com/controversial/nextjs-edge-functions-ga-error-repro

In the commit history, you can see that the penultimate commit (`git checkout HEAD~1`) works, while the most recent commit (which just moves `pages` → `src/pages`; `git checkout main`) fails.

Note that this error still exists in the 13.1 release, as well as in the `13.1.1-canary.0`.

The 13.1 release notes advertise that 

> "experimental-" prefix is no longer needed

but this isn’t true if a project uses a `src` folder.

**Comment by controversial** [comment]
This screenshot shows the issue clearly:

<img width="910" alt="Screenshot 2022-12-23 at 5 03 03 PM" src="https://user-images.githubusercontent.com/10377391/209409861-95df0714-5034-4d77-8fec-6177fd5c0336.png">

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.4-canary.1` of Next.js, please update and give it a try!

**Comment by feugy** [comment]
Thanks for the but report @controversial, and apologies for the lag. Let us know if you have other related blockers!

**Comment by controversial** [comment]
Thanks for getting on this @feugy! The main other related (as far as edge API routes) blocker for me is #38302
