### ISSUE TITLE
Docs: A note that env variables used in getStaticProps should be prefixed with NEXT_PUBLIC_  when using on-demand ISR

### ISSUE THREAD

**Issue by kapantzak** [vercel/next.js#44082]
### What is the improvement or update you wish to see?

I wish to see a note that any env variable used inside the `getStaticProps` function should be prefixed with `NEXT_PUBLIC_` in order to be available when triggering on-demand revalidation.

### Is there any context that might help us understand?

I was trying to use on-demand ISR on a set of blog pages. In the `getStaticProps` function I was calling the CMS api to get the respective article and I was using the respective url that was stored as an env variable. This was working at build time and all pages were statically generated, but when the CMS webhook called the revalidate endpoint in order to rebuild the specific page, the env variable was undefined. Only after I prefixed the specific env variable with `NEXT_PUBLIC_` that worked.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#using-on-demand-revalidation

**Comment by balazsorban44** [comment]
This should not be the case though, as `getStaticProps` is run server-side only and such does not require the `NEXT_PUBLIC_` prefix.

Check out https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

If you are having issues, I suggest opening a bug report with a minimal reproduction so we can investigate.
