### ISSUE TITLE
"Feedback" on Nextjs.org Not Submitting - blocked by CORS policy

### ISSUE THREAD

**Issue by schizek** [vercel/next.js#44103]
### What is the improvement or update you wish to see?

There is a bug that should be fixed on the nextjs.org site causing the "Feedback" feature to not work and just returns the error "Failed to fetch" with the console revealing the following error...

> Access to fetch at 'https://api.nextjs.org/api/feedback' from origin 'https://nextjs.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Is there any context that might help us understand?

Tested on several pages including https://nextjs.org/docs/advanced-features/custom-server using the Feedback form at the bottom of the article as well as the one in the header.

<img width="1436" alt="Screenshot 2022-12-17 at 2 18 34 AM" src="https://user-images.githubusercontent.com/5023509/208233130-a48e7edc-8e0a-4743-9e75-382f5d68f338.png">

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/custom-server

**Comment by wadehammes** [comment]
I've seen this before when running ad blockers like uOrigin or similar, not saying that is the case here but something to check.

**Comment by balazsorban44** [comment]
I also recommend checking extensions, I cannot reproduce this.
