### ISSUE TITLE
Compiler error with styled-components and console.log

### ISSUE THREAD

**Issue by TrevorBurnham** [vercel/next.js#44113]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.12.0
  npm: 8.19.2
  Yarn: 1.22.17
  pnpm: N/A
Relevant packages:
  next: 13.0.8-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue

https://github.com/TrevorBurnham/styled-components-swc-error-repro

### To Reproduce

1. Create a Next.js project with styled-components (`npx create-next-app --example with-styled-components` will do the trick)
2. Create a module with multiple `styled` component declarations and `console.log('Hello world!')`;
3. `npm run dev` and load the page in the browser

### Describe the Bug

Compilation fails with the error

```
Module parse failed: Identifier '_templateObject' has already been declared (11:9)
File was processed with these loaders:
 * ./node_modules/next/dist/compiled/@next/react-refresh-utils/dist/loader.js
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
|     return data;
| }
> function _templateObject() {
|     const data = _tagged_template_literal([
|         ""
Hello world!
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
```

### Expected Behavior

No problems should occur during compilation.

**Additional note:** The only relevant issue I could find is #30053. In that case, the issue could be worked around by setting `swcMinify: false`. However, that configuration flag doesn't affect the behavior I'm seeing.

**Comment by TrevorBurnham** [comment]
I realized right after I posted this report that the bug is actually caused by the [Console Ninja extension](https://marketplace.visualstudio.com/items?itemName=WallabyJs.console-ninja) for VS Code, which hooks in to the local compilation process. 😖

**Comment by TrevorBurnham** [comment]
One of the Console Ninja folks replied on the [issue](https://github.com/wallabyjs/console-ninja/issues/59) I filed with them:

> While the issue in this case was caused by Console Ninja, it's not specific to it. If you add simple `eval("");` anywhere in your component code, you'll get the same error with Console Ninja paused or even uninstalled. Console Ninja adds some code that contains `eval`, and that's why it was breaking.

I can confirm: If you open my repro and replace `console.log('Hello world!')` with `eval('')`, I see the same error (without the Console Ninja extension).

**Comment by blopez2010** [comment]
Any news on this issue?

**Comment by xuxucode** [comment]
See sample repo: https://github.com/xuxucode/console-ninja-issue-249/blob/master/app/page.tsx#L12-L14

The critical part is a class with private methods:
```ts
// A class with two private methods which have same names. The only difference
// is one of them begins with a underscore.
class Client {
  #privateMethod() { }

  #_privateMethod() { }
}
```

**Comment by kdy1** [comment]
Closing as fixed 
<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/bc3e8967-3d6a-4f20-b7b7-419bd5fe7716">
