### ISSUE TITLE
Nextjs13 - TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by Alii-isk** [vercel/next.js#44129]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Which example does this report relate to?

none

### What browser are you using? (if relevant)

Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

### Describe the Bug

I am trying out the new **nextJS 13** app directory but i keep getting `TypeError: Cannot read properties of undefined (reading 'call')` on the client side when i use a component with `'use client'`

**i use  `"next": "13.0.7"`**
**AppInfo.tsx**
```
'use client'

export default function AppInfo() {
   return (
      <>
         <h1>client</h1>
      </>
   )
} 
```

**page.tsx**

```
import AppInfo from './appinfo';

export default async function Dashboard() {

  return (
    <>
      <div className="flex flex-col gap-5 max-w-[1028px] mx-auto px-4">
        <h1 className="mt-5 text-3xl font-light">
          👋 Hi, <span className="font-bold text-gray-400 ">Admin</span>
        </h1>
        <AppInfo/>
      </div>
    </>
  )
}
```

### Expected Behavior

no error

### To Reproduce

**AppInfo.tsx**
```
'use client'

export default function AppInfo() {
   return (
      <>
         <h1>client</h1>
      </>
   )
} 
```

**page.tsx**

```
import AppInfo from './appinfo';

export default async function Dashboard() {

  return (
    <>
      <div className="flex flex-col gap-5 max-w-[1028px] mx-auto px-4">
        <h1 className="mt-5 text-3xl font-light">
          👋 Hi, <span className="font-bold text-gray-400 ">Admin</span>
        </h1>
        <AppInfo/>
      </div>
    </>
  )
}
```

**Comment by ChristopherTrimboli** [comment]
can confirm, I have same issue, happened after upgrade to `13.0.7`

**Comment by kaceycleveland** [comment]
The canary build they have solved it for me. There are some issues I am running into with navigation and the back button though.

**Comment by Emyboy** [comment]
> The canary build they have solved it for me. There are some issues I am running into with navigation and the back button though.

I've been having the same issue with navigation as well. I even noticed it on the NextJs website 😄

**Comment by mehmetkursataydin** [comment]
Seems to be OK in MacOS environment but got the same error on Windows.

**Comment by drakata** [comment]
> on windows I get the same error in version "next": "13.0.7". "next": "13.0.6", version ok

I got the same issue, using windows, `next@13.0.6` works for me too.

**Comment by dafengzhen** [comment]
try using next@canary

**Comment by roberto-duran** [comment]
I get the same error on version 13.0.7
downgrade to version 13.0.6 and "evrething" work

**Comment by roberto-duran** [comment]
> try using next@canary

in the canray version its fixed.
TY

**Comment by pogran** [comment]
> I get the same error on version 13.0.7 downgrade to version 13.0.6 and "evrething" work

need to wait next release after 13.0.7 ? I think use canary on prod its not a good idea

**Comment by Alii-isk** [comment]
This issue got fixed in `next@canary`,
so you either gonna use `next@canary` or wait for the upcoming new version
