### ISSUE TITLE
[AppDir] Link component prefetch={false} does not prefetch on hover, as the beta documentation states.

### ISSUE THREAD

**Issue by HummingMind** [vercel/next.js#44131]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 19.3.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.7
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

private repo

### To Reproduce

You can see it deployed here.
[Deployed to Vercel](https://test-next-eta-navy.vercel.app/)

### Describe the Bug

Using the AppDir in Next.JS 13, the Link component prefetch={false} does not prefetch on hover, as the beta documentation states. I just have two pages linking to each other, each Link is set to prefetch={false}

You can see it deployed here.
[Deployed to Vercel](https://test-next-eta-navy.vercel.app/)

Tested with caching disabled in dev tools. Is this a bug or is the documentation wrong?

Thank you!

### Expected Behavior

Hovering over the link on either page should prefetch the other page.

### Which browser are you using? (if relevant)

latest stable Edge

### How are you deploying your application? (if relevant)

Vercel via Github

**Comment by timneutkens** [comment]
This is intentional and indeed different from `pages` as there were many requests for `prefetch={false}` to completely disable prefetching. Relevant code: https://github.com/vercel/next.js/blob/canary/packages/next/client/link.tsx#L618
The docs are not up to date with that I'll make that change right away.

**Comment by timneutkens** [comment]
Pushed up the change to the docs! Deployment is currently running so you'll see the docs change 🔜
