### ISSUE TITLE
Unintended full page refresh after shallow navigation with middleware rewrite

### ISSUE THREAD

**Issue by ha1fstack** [vercel/next.js#44187]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Education
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.4~13.0.8 canary1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/s/clever-voice-5hz5og

### To Reproduce

Go to '/foo' path and click 'go to bar' link.

### Describe the Bug

When you click the 'go to bar' link,

**For normal situation without middleware rewrite,**
It navigates to '/foo' then immediately navigates right back to '/bar' and shows 'go to bar' again. (it happends in short time so you won't see contents of '/bar' page at all)

**When using middleware rewrite (different page for different user agent in example)**
For context... before 13.0.7, when you click the link the path changes to '/bar' then changes to '/foo', but unlike previous situation it still shows contents of '/bar'.
After 13.0.7, it behaves similar to normal situation without middleware.
So the previous issue was solved, but strangely full page refresh is triggered after it navigates back to '/foo'.
This only happends in development mode not in production.

### Expected Behavior

When using middeware rewrite, the page should not refresh in development mode after shallow navigation.

**Comment by raRaRa** [comment]
Same issue here. I am URL re-writing subdomains to a specific page with a middleware.

The URL rewrite is changing {customerId}.domain.com/customer to domain.com/customer/{customerId}.

If the Link has the href set to /customer/[customerId] then the shallow route works without refreshing, but I don't want to show [customerId] in the path. So I tried to use `as` with `/customer/` then it shows an error that the as is not compatible with the href.

Error: The provided `as` value (/customer) is incompatible with the `href` value (/customer/[customerId]). Read more: https://nextjs.org/docs/messages/incompatible-href-as

**Comment by raRaRa** [comment]
I can confim that the shallow routing is working as expected on production, but not in development.

**Comment by DB-Alex** [comment]
@raRaRa are you sure? I have the exact same problem in production when using the router.push method.

**Comment by nabildroid** [comment]
working on production but not in vercel

**Comment by nabildroid** [comment]
this entire appdir next is scam, not working and a lot of problems, i wish i have stared my protect in Remix
