### ISSUE TITLE
Bug on beta docs 

### ISSUE THREAD

**Issue by AntonioObra** [vercel/next.js#44221]
### What is the improvement or update you wish to see?

On the beta docs, when you login to see the comments, and can see other people comments, z-index is off and when scrolling past it, the comments appear above the navigation menu. This is a problem I found occurs on all sizes, from mobile to desktop. With inspector element I've found that the one of the components contained in the comments component has this class:

```
.bubbles_glowContainer__cDhs0 {
    position: absolute;
    top: 1px;
    left: 1px;
    width: 26px;
    height: 26px;
    /* z-index: 100000; */
    pointer-events: none;
}
```
As you can see it has a z-index of 100000, although removing it simply does nothing as far as I tested.

### Is there any context that might help us understand?

I've found it on these pages: [https://beta.nextjs.org/docs/routing/fundamentals](url), [https://beta.nextjs.org/docs/rendering/server-and-client-components](url)

![image](https://user-images.githubusercontent.com/55183634/208878476-04dc09a7-9cc5-4e20-af16-aca397dc1f7b.png)

![image](https://user-images.githubusercontent.com/55183634/208878630-01a3e801-e6dd-4d53-83cd-d2547f99e863.png)

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/routing/fundamentals

**Comment by balazsorban44** [comment]
Thanks, it's unrelated to Next.js or its documentation. To give feedback on the preview comments feature, check out the popup on the page: 
![image](https://user-images.githubusercontent.com/18369201/210963493-e6ffc941-ec8d-4782-903c-5be821c57305.png)
