### ISSUE TITLE
Bug on Next.js 13.0.7

### ISSUE THREAD

**Issue by AbdelrhmanX7** [vercel/next.js#44228]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.7
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

yarn create next-app --experimental-app --typescript

### To Reproduce

![image](https://user-images.githubusercontent.com/74682593/208910525-a061a5cb-de24-4b4e-b93c-dc357114a791.png)

### Describe the Bug

Next.js starts to show the error "TypeError: Cannot read properties of undefined" (reading "call")  on deploy, and the only way to fix this issue is by deleting all Image components.

### Expected Behavior

It should display a standard image. 

### Which browser are you using? (if relevant)

Chrome 108.0.5359.125 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

yarn run dev

**Comment by timneutkens** [comment]
> I verified that the issue exists in the latest Next.js canary release

Did you verify on canary: `npm install next@canary`? Because this is already fixed on canary.
