### ISSUE TITLE
[appDir] Next.js appDir can't compile `@web3-react/core` and `@ethersproject/providers` dependencies

### ISSUE THREAD

**Issue by dengoloborodko** [vercel/next.js#44273]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.2.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/summer-dawn-wqu0cu

### To Reproduce

1. Open a sandbox and check errors in the console.
2. Rename `app` directory -> `app_commented`
3. Rename `pages_commented` directory -> `pages`
4. Check the console - no compilation errors present

### Describe the Bug

When importing dependencies from `@web3-react/core` and `@ethersproject/providers` packages in appDir - compilation errors occur:

```
warn  - ./node_modules/ws/lib/buffer-util.js
Module not found: Can't resolve 'bufferutil' in '/project/sandbox/node_modules/ws/lib'

./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in '/project/sandbox/node_modules/ws/lib'
```

This issue is not reproducible from the `pages` directory

### Expected Behavior

It should compile without any issues, as in the pages directory.
Or please provide instructions on how to fix this, via `next.config.js` options for example

**Comment by Lite5h4dow** [comment]
im having this issue too.

**Comment by SuttonJack** [comment]
Try using the following in your `next.config.js` -

```js
module.exports = {
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.externals.push({
      'utf-8-validate': 'commonjs utf-8-validate',
      'bufferutil': 'commonjs bufferutil',
    })
    return config
  },
}
```

**Comment by denysgoloborodko** [comment]
> Try using the following in your `next.config.js` -
> 
> ```js
> module.exports = {
>   webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
>     config.externals.push({
>       'utf-8-validate': 'commonjs utf-8-validate',
>       'bufferutil': 'commonjs bufferutil',
>     })
>     return config
>   },
> }
> ```

Thank you, that's helped!

**Comment by dengoloborodko** [comment]
> Try using the following in your `next.config.js` -
> 
> ```js
> module.exports = {
>   webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
>     config.externals.push({
>       'utf-8-validate': 'commonjs utf-8-validate',
>       'bufferutil': 'commonjs bufferutil',
>     })
>     return config
>   },
> }
> ```

Thank you, that's helped!
