### ISSUE TITLE
No style tags in <head> using appDir

### ISSUE THREAD

**Issue by Fluxium2006** [vercel/next.js#44272]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/Fluxium2006/next13styles

### To Reproduce

Clone the above repo
`npm install`
`npm run dev`
visit [http://localhost:3000](http://localhost:3000)

Alternatively:
Create a new project using `npx create-next-app@latest`
Install sass: `npm i sass`
Create e.g. a scss module with some styles and apply those to an element

### Describe the Bug

Styles are not injected into `<head>`

### Expected Behavior

Style tags are present in the `<head>`

### Which browser are you using? (if relevant)

Firefox 108

### How are you deploying your application? (if relevant)

locally (npm run dev)

**Comment by lewisjr** [comment]
I am having the same issue with `appDir: true`, except I am using css modules as opposed to sass. Not working for client or server components. Oddly enough, something styled with `styled-components: 5.3.6` is showing the styles though. When I change it to use turbopack some of the styles are being applied but not all

**Comment by Fluxium2006** [comment]
[This release](https://github.com/vercel/next.js/releases/tag/v13.1.1) fixes this bug.
