### ISSUE TITLE
Swiping to the left on the first image causes a client side exception

### ISSUE THREAD

**Issue by ItsValerius** [vercel/next.js#44271]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 19.0.1
      npm: 8.19.2
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.1.0
      eslint-config-next: 13.1.0
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

with-cloudinary nextjs-image-gallery

### What browser are you using? (if relevant)

Chrome 108.0.5359.125

### How are you deploying your application? (if relevant)

Official demo

### Describe the Bug

A Client side exception inside the image carousel.

### Expected Behavior

Either nothing should happen when swiping to the left or make it wrap around to the end.

### To Reproduce

Click on the first image, then Swipe left.

**Comment by EmilianoGarciaLopez** [comment]
Have the same issue here. We're you able to find a fix?
