### ISSUE TITLE
`Dynamic Code Evaluation` error in a react hook

### ISSUE THREAD

**Issue by jahirfiquitiva** [vercel/next.js#44290]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.13.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.0
      eslint-config-next: 13.1.0
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/jahirfiquitiva/jahir.dev/pull/41

### To Reproduce

run `yarn build` in the repository

### Describe the Bug

I have a custom react hook where I'm calling the library `node-vibrant` to get an image colors.
Upon compilation or build, the build fails with this error in the output:
```
./node_modules/lodash/_root.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation

Import trace for requested module:
./node_modules/lodash/_root.js
./node_modules/lodash/_cloneBuffer.js
./node_modules/lodash/_baseClone.js
./node_modules/lodash/clone.js
./node_modules/node-vibrant/lib/builder.js
./node_modules/node-vibrant/lib/vibrant.js
./node_modules/node-vibrant/lib/browser.js
./src/hooks/usePalette.ts
./src/hooks/index.tsx
```

It seems like this is an error with Middlewares or Edge API Routes which I think is not really related to React hooks, although I may be wrong.

### Expected Behavior

The project should build normally as the `node-vibrant` library is not being used in Middlewares or Edge API Routes

### How are you deploying your application? (if relevant)

next build and Vercel

**Comment by jahirfiquitiva** [comment]
PS: `next dev` runs perfectly fine and the hook is executed normally

**Comment by SukkaW** [comment]
@jahirfiquitiva No, it is caused by `lodash`:

https://unpkg.com/browse/lodash@4.17.21/_root.js

```js
var root = freeGlobal || freeSelf || Function('return this')();
```

Lodash uses `Function('return this')` to get `globalThis` which triggers the error.

**Comment by jahirfiquitiva** [comment]
@SukkaW but then the documentation is misleading because of it says it's for Middlewares or Edge API Routes. I think should say the issue can happen anywhere in the project then.

By the way, is there any workaround on this? How could I solve it without removing this library? Because it was working perfectly fine with previous versions on Next.

Thanks!

**Comment by jahirfiquitiva** [comment]
turns out the issue was caused because I was importing a field from a hook file in an api route, and for some reason it imported the other hooks too including one with the conflicting code.
sorry for the inconveniences
