### ISSUE TITLE
Layout component gets duplicated in other component

### ISSUE THREAD

**Issue by sgandolfo** [vercel/next.js#44301]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.7.0
      npm: 9.2.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.0
      eslint-config-next: 13.1.0
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/sgandolfo/nextjs-blog

### To Reproduce

1. Create a layout component within a folder in the App directory, i.e. posts.
2. Inside the page.js file in the posts directory, wrap the page content in the Layout component as shown in the example:
4. Run npm dev
5. Watch layout being duplicated

### Describe the Bug

When navigation to localhost:3000/posts I see that the entire Layout component has been duplicated inside the {children} of the main tag inside the Layout component

Below some screenshots of the behaviour I noticed:
Duplication of the content inside the localhost:3000/posts screen:

![image](https://user-images.githubusercontent.com/49209915/209349645-848273e9-23f3-41ef-8f4d-287bba5f1872.png)

View from the Inspect window:
![image](https://user-images.githubusercontent.com/49209915/209349816-25966c0d-5188-4cb4-8020-1d1f8d46dc55.png)

If the code is migrated to the old 'Pages' directory, the code works as expected and the layout is not being duplicated.

### Expected Behavior

Layout component should not be duplicated within the main tag

### Which browser are you using? (if relevant)

Chrome Version 108.0.5359.124 (Official Build) (arm64)

**Comment by AlainD-** [comment]
It's an error on your side. In your Post page componant you wrap again your posts with the about's layout compoment:

```
import Layout from "../../pages/about/layout";

export default function FirstPost() {
    return (
        <Layout>
            <h1>First Post</h1>
        </Layout>
    )
}
```

**Comment by sgandolfo** [comment]
Hi Alain,

Thanks for the feedback! My apologies for making such a mistake in the first place. I wasn't aware that you do need to specifically wrap the h1 inside the Layout component to make it work.

Thanks again for your help!

Kind regards,
Stefano
