### ISSUE TITLE
(AppDir) 🙏🏻 Don't show a warning when when attributes are dynamically added to the <html> tag before hydration

### ISSUE THREAD

**Issue by garronej** [vercel/next.js#44343]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 6.28.0
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 11.0.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/garronej/mui-next-appdir-demo/tree/darkmode

### To Reproduce

```bash
git clone https://github.com/garronej/mui-next-appdir-demo
cd mui-next-appdir-demo
git checkout darkmode
yarn
yarn dev
```

### Describe the Bug

When [I dynamically add the attribute `<html data-fr-theme="dark" >` on client side](https://github.com/garronej/mui-next-appdir-demo/blob/3f8b9dac4946960167efd90803f51c2306b0e637/app/layout.tsx#L10) I get the following warning:  

`Warning: Extra attributes from the server: data-fr-theme` (more like: 'extra argument added by the client before hydratation')

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/6702424/209474682-dff6002e-64c8-4ff8-81d7-894594de0bda.png">  

(the warning is only shown in dev mode)  

### Expected Behavior

Not having a warning.  
This html attribute decides [what CSS `--var` colors are used](https://github.com/garronej/mui-next-appdir-demo/blob/3f8b9dac4946960167efd90803f51c2306b0e637/app/styles.css#L1-L14).  

Waiting for the hydration to add the attribute result in white flashes:  

https://user-images.githubusercontent.com/6702424/209474952-bab2a037-efe6-461c-9995-35357e41a908.mov

In PagesDir there was no warning.  

<details>
    <summary>Same setup in Next 13 PagesDir giving no warning</summary>  

```bash
git clone https://github.com/garronej/mui-next-appdir-demo
cd mui-next-appdir-demo
git checkout pagesdir-darkmode
yarn
yarn dev
```

</details>

**Comment by Fredkiss3** [comment]
React will always give a hydration error when the initial html does not match that of the server. In production It will result in a full client side render which is not ideal. It is a mechanism is react to not mess up hydration.

**Comment by Fredkiss3** [comment]
One of the solutions could be to first check for dark mode media query with css `@media (prefers-color-scheme: dark)`, that way you don’t have to run a Js script first to manage the dark mode.
As for manual toggle of dark-mode it is hard since next 13 with appDir hydrate your page from the root as opposed to next 12 where it hydrated from a `#__next` div.

I don’t have a solution yet

**Comment by garronej** [comment]
UPDATE: What's reassuring me is that [the beta React docs](https://beta.reactjs.org/) website implement the same approach for their dark mode (adding an attribute to the `<html>` element).  
They are using Next in PageDir still but it means when they'll want to migrate to AppDir they'll hit the same roadblock.  

https://user-images.githubusercontent.com/6702424/209488395-5fc1114f-4c98-4d33-90da-3766c05215ad.mov  

@Fredkiss3  

> since next 13 with appDir hydrate your page from the root as opposed to next 12 where it hydrated from a #__next div  

Thank you, that's the key for understanding what's going on 👍🏻   

> In production It will result in a full client side render which is not ideal. It is a mechanism is react to not mess up hydration.  

I'd like to put that claim to the test. I don't know how yet though 🤔

**Comment by RemVN** [comment]
How about change theme like this? it works fine in my app (next app dir)

![image](https://user-images.githubusercontent.com/34063162/209491380-ea2549ec-21f8-4e96-ab5c-049d39da4a55.png)

**Comment by garronej** [comment]
Hi @RemVN :)  
Sure it works but it induces [white flashes](https://user-images.githubusercontent.com/6702424/209474682-dff6002e-64c8-4ff8-81d7-894594de0bda.png) for users dark mode users.  The effects are invoqued to late. For an optimal user experience, we want the html attribute to be set  before the DOM content gets loaded.

**Comment by RemVN** [comment]
> Hi @RemVN :) Sure it works but it induces [white flashes](https://user-images.githubusercontent.com/6702424/209474682-dff6002e-64c8-4ff8-81d7-894594de0bda.png) for users dark mode users. The effects are invoqued to late. For an optimal user experience, we want the html attribute to be set before the DOM content gets loaded.

maybe you can use this approach. seems fine and no hydration error
![image](https://user-images.githubusercontent.com/34063162/209492244-71ddafea-9246-46c8-b17d-09b0dfc778ed.png)

**Comment by garronej** [comment]
Sure, but on the server, we don't know what color theme the person making the request want.  
On the client I can query `window.matchMedia("(prefers-color-scheme: dark)").matches` or read for the `localStorage`.  
We could use cookies, but it wouldn't work on the first visit and it would opt us out from [automatic static optimization](https://nextjs.org/docs/messages/opt-out-auto-static-optimization).

**Comment by garronej** [comment]
@Fredkiss3,  

Using this test repo:  

```bash
git clone https://github.com/garronej/mui-next-appdir-demo
cd mui-next-appdir-demo
git checkout darkmode
yarn
yarn build
yarn start
```  
How would you test the following claim ?  

> In production It will result in a full client side render which is not ideal. It is a mechanism is react to not mess up hydration.  

I would like to be able to understand the effect that commenting out [this line](https://github.com/garronej/mui-next-appdir-demo/blob/3f8b9dac4946960167efd90803f51c2306b0e637/app/layout.tsx#L10) have on the rendering process...

**Comment by RemVN** [comment]
I found another solution 

1. create a middleware file 
```
import { NextRequest, NextResponse } from 'next/server';

export function middleware(request: NextRequest) {
    // only apply for html files
    if (request.headers.get('content-type')?.includes('text/html')) {
        const response = NextResponse.next();
        response.headers.set(
            'Accept-CH',
            `Sec-CH-Prefers-Color-Scheme, Sec-CH-Prefers-Contrast`,
        );
        response.headers.set('Vary', 'Sec-CH-Prefers-Color-Scheme');
        response.headers.set('Critical-CH', 'Sec-CH-Prefers-Color-Scheme');
        return response;
    }
    return NextResponse.next();
}
```

2. Get 'sec-ch-prefers-color-scheme' header from client
```
import { headers } from 'next/headers';

export default async function RootLayout({ children }: DivProps) {
    const headersList = headers();
    let preferTheme = headersList.get('sec-ch-prefers-color-scheme');

    return (
        <html
            lang='en'
            data-theme={preferTheme}
        >
            <head></head>
            <body>
                {children}
            </body>
        </html>
    );
}
```

Result:

https://user-images.githubusercontent.com/34063162/209498135-c078ffa3-c455-4d21-9b08-1b7bf7ffd550.mp4

**Comment by RemVN** [comment]
my bad, `request.headers.get('Content-Type')?.includes('text/html')` 
should be `request.headers.get('Accept')?.includes('text/html')`

**Comment by garronej** [comment]
@RemVN this is lit 🤩!  
Much smarter than the cookie approach! I didn't know about `Accept-CH`.  

Unfortunately, I can't go with this solution because  
1) It implies a re-render on the backend for every request. I don't want to give up static optimization.  
2) It doesn’t work on Firefox and Safari.  

Thanks for sharing, though !!

**Comment by RemVN** [comment]
@garronej I'm also thinking about static optimization.  Maybe can be solved with something like [theme] route segment (eg: /[theme]/home/). However it's not good for SEO and a little bit overkill
The best solution right now is media query in css file or having a new function like generateStaticHeaders... ?

**Comment by garronej** [comment]
> The best solution right now is media query in css file  

Meh. As mentioned by @Fredkiss3 this implies giving up on the theme switcher. ☹️  

What I'll be doing is, in dev mode, add the attribute will be set in a `useEffect` and in production I'll do it ASAP (there is no warning in production). @Fredkiss3 says it results in a full-client side render but I failed to gather evidence that confirms this is the case.  

Anyway, I hope we'll get an answer from the Next team...

**Comment by Fredkiss3** [comment]
Normally in production it does not give a warning instead it gives an encoded console error (error 418 which is hydration mismatch), and after that it says that it will do a client side render. 
At least that’s the error message I got. 
I don’t know how it play with Server components in appDir but it should give the same error… right ?

**Comment by Fredkiss3** [comment]
@garronej if the script you gave does not give any warning (or error) maybe it is because it runs after hydration ? (Or is deferred automatically by NextJs).
In my research for this problem, I’ve seen that NextJs automatically adds defer attributes to scripts. 
```jsx 
<script dangerouslySetInnerHTML={{
          "__html": ` 
          document.documentElement.setAttribute("data-fr-theme", "dark") 
          `
        }}></script>
```

**Comment by Fredkiss3** [comment]
Ok I’ve read of an attribute you can use to suppress hydration warning.

from the docs :
https://beta.reactjs.org/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors

> If a single element’s attribute or text content is unavoidably different between the server and the client (for example, a timestamp), you may silence the hydration mismatch warning.
> 
> To silence hydration warnings on an element, add suppressHydrationWarning={true}

So to suppress it you would do : 
```jsx
<html suppressHydrationWarning={true}> 
   <head>
   <script dangerouslySetInnerHTML={{
          "__html": ` 
          document.documentElement.setAttribute("data-fr-theme", "dark") 
          `
        }}></script>
   </head>
<body>
   {/*rest of your code*/}
</body>
</html>
```

**Comment by garronej** [comment]
@Fredkiss3 You are the real MVP <3!  

It only work with `<script />` though. `<Script />` is evaluated too late, we get a white flash, even with the `beforeInteractive` strategy enabled.  

Closing now.  
Thank you very much!
