### ISSUE TITLE
Docs: layout.js

### ISSUE THREAD

**Issue by vaibhav-OP** [vercel/next.js#44342]
### What is the improvement or update you wish to see?

it seems like the layout.js file should have "use client" on top if we want to render a client component inside it.

### Is there any context that might help us understand?

i was getting `Hydration failed because the initial UI does not match what was rendered on the server.` for some time i searched the internet and the next discord server but i could'nt solve the the issue.
adding "use client" on the top of layout.js solved the issue also helped with using packages like react-toastify

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/file-conventions/layout

**Comment by apriltaoyvr** [comment]
Are you certain this is coming from just client components and not provider components?

https://beta.nextjs.org/docs/rendering/server-and-client-components#rendering-third-party-context-providers-in-server-components

**Comment by vaibhav-OP** [comment]
> Are you certain this is coming from just client components and not provider components?
> 
> https://beta.nextjs.org/docs/rendering/server-and-client-components#rendering-third-party-context-providers-in-server-components

Yes im sure about it as i was rendering a navbar inside the layout.jsx the navbar component had "use client" which i think makes it a client component. That navbar was giving me the hydration error untill i added "use client" on top of layout.jsx

**Comment by vaibhav-OP** [comment]
here is an ![example](https://lgdx7w-3000.preview.csb.app), while recreating the error i found it only gives that error if we import anything `ex useState from react` inside the client component that is rendered inside layout.jsx.
![Screenshot 2022-12-26 191127](https://user-images.githubusercontent.com/46072323/209555389-55c6e7bf-afc0-46f8-bfe9-d48d4f858b60.jpg)

not sure if its a documentation problem or bug 😓

**Comment by balazsorban44** [comment]
I could not reproduce an issue given the reproduction. If you still have this problem, please open a new bug report. :pray:
