### ISSUE TITLE
Pages inside parenthesis folder show zero bytes in build overview 

### ISSUE THREAD

**Issue by RemVN** [vercel/next.js#44340]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/RemVN/next-13-bug-zero-page-size

### To Reproduce

1. `git clone https://github.com/RemVN/next-13-bug-zero-page-size`
2. `npm install`
3. `npm run build`

### Describe the Bug

Pages inside the parenthesis folder show incorrect size (0 bytes), but outside the parenthesis folder they work fine. This is just a visual bug, not too annoying but useful to know when your application gets big.

![image](https://user-images.githubusercontent.com/34063162/209472677-9e180396-4566-4945-91e8-714025318505.png)

![image](https://user-images.githubusercontent.com/34063162/209472703-cabb0b60-dfeb-48a7-8041-e413b3393450.png)

### Expected Behavior

Pages inside parenthesis should larger than 0 bytes

**Comment by yuto-hasegawa** [comment]
I have the exact same issue.
next@13.4.2

**Comment by fabio-nettis** [comment]
Confirmed. Still an issue in version v13.4.5.

**Comment by ijjk** [comment]
Hi, this has been updated in the latest version of Next.js, please update and give it a try!

**Comment by fabio-nettis** [comment]
Pages seem to work , all tough it seems as if all API routes contained in the API directory, inside the api folder are still marked with 0kb

**Comment by ijjk** [comment]
@fabio-nettis that is expected for API routes as they don't have client-side JS so it isn't shown to conflate server-size with client-size

**Comment by fabio-nettis** [comment]
> @fabio-nettis that is expected for API routes as they don't have client-side JS so it isn't shown to conflate server-size with client-size

How exactly would I make sure then, that my API routes are not too JS-Heavy?

**Comment by ijjk** [comment]
We're investigating updated build summary to express this better!
