### ISSUE TITLE
`next dev` logs experimental edge runtime error on API routes when project is using src/ directory

### ISSUE THREAD

**Issue by bryanrsmith** [vercel/next.js#44382]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.17
      pnpm: 7.17.1
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/bryanrsmith/api-route-error-src/blob/main/src/pages/api/foo.ts

### To Reproduce

Configure an API route to use the (now stable) edge runtime in a project that uses the `src/` directory.

```
export const config = {
	runtime: 'edge',
};
```

### Describe the Bug

`next dev` prints the following error:

error - Page /src/pages/api/foo provided runtime 'edge', the edge runtime for rendering is currently experimental. Use runtime 'experimental-edge' instead.

`next build` does not print this error.

### Expected Behavior

The dev environment should handle the src/ directory consistently with production builds.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.4-canary.1` of Next.js, please update and give it a try!
