### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '')

### ISSUE THREAD

**Issue by ib-ahmed** [vercel/next.js#44386]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 17.5.0
      npm: N/A
      Yarn: N/A
      pnpm: 7.14.2
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/supastore/next-13-edge-reading-error

### To Reproduce

Created a new next app using npx create-next-app@latest --experimental-app next-13-edge-reading-error
Changed the runtime in next.config.js to "experimental-edge"

### Describe the Bug

[TypeError: Cannot read properties of undefined (reading '')] appears in the terminal when accessing a page and only when the specified runtime is the experimental-edge. Without changing the runtime, this error does not appear.

### Expected Behavior

No errors would be logged when using the experimental-edge runtime

**Comment by otoyo** [comment]
I might have got same error on the Edge Runtime.
This is not appeared in the local. eg: `next dev` `vercel dev`
```
TypeError: Cannot read properties of undefined (reading 'length')
    at worker.js:31:30559
    at worker.js:21:14472
    at worker.js:31:58743
    at worker.js:55:12955
```

**Comment by ib-ahmed** [comment]
Closing as it seems fixed now

**Comment by timneutkens** [comment]
Thanks for checking, indeed this should be fixed already 👍
