### ISSUE TITLE
Docs: Does next/link scroll prop false disable scrolling to element?

### ISSUE THREAD

**Issue by IDrumsey** [vercel/next.js#44407]
### What is the improvement or update you wish to see?

I'm using the scroll prop as `scroll={false}` on some links and it doesn't stop from scrolling to the element. Just checking to see if the docs seen [here](https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page:~:text=To%20prevent%20scrolling%20to%20the%20top%20/%20hash%20scroll%3D%7Bfalse%7D%20can%20be%20added%20to%20Link) are accurate about this.

### Is there any context that might help us understand?

Something like this

```
<Link scroll={false} href="/some-page#some-section"/>
```

still scrolls to the section.

**Comment by MirciaGeorge** [comment]
I have the same problem, do you solve it?

**Comment by bm64** [comment]
+1, I got the same problem on 13.0.7

**Comment by IonelLupu** [comment]
@IDrumsey  I am just curious, why would you have a Link with a href that goes to a section and you don't want it to scroll to that section? 🤔

**Comment by IDrumsey** [comment]
> @IDrumsey I am just curious, why would you have a Link with a href that goes to a section and you don't want it to scroll to that section? 🤔

I'm sorry for not getting back to you, it's been a while and I can't really remember.

**Comment by leerob** [comment]
This is now documented!
