### ISSUE TITLE
Docs: next/image sets CSP headers for SVG by default

### ISSUE THREAD

**Issue by Taarek** [vercel/next.js#44419]
### What is the improvement or update you wish to see?

Sorry in advance if this is not the proper issues category, but felt more suitable than a bug report.

I noticed this in my `Issues` tab on Edge: 
It's pointing to an image URL made by NextJS (it's a JPG converted to WebP)
![image](https://user-images.githubusercontent.com/13603398/209917758-ea99503f-40cb-4d99-9eb7-102fc9d05092.png)

After a little bit of digging, I found; https://github.com/vercel/next.js/blob/87a419f821f518ca614b320411c06872c7cb425c/packages/next/shared/lib/image-config.ts#L111

And: https://nextjs.org/docs/api-reference/next/image#dangerously-allow-svg

So it seems like these CSP rules are for SVG, but then my question is, is it intentional that it says this in the docs: 
`"If you need to serve SVG images with the default Image Optimization API, you can set dangerouslyAllowSVG and contentSecurityPolicy inside your next.config.js"` 

Even though NextJS already sets these values by default in the config?

Probably is very nitpicky, sorry about that.

### Is there any context that might help us understand?

The docs ask the user to configure `dangerouslyAllowSVG` and `contentSecurityPolicy` in `next.config.js` to use SVG with the Image Optimization API, even though the config sets these CSP headers by default, seen in: https://github.com/vercel/next.js/blob/87a419f821f518ca614b320411c06872c7cb425c/packages/next/shared/lib/image-config.ts#L111

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/image#dangerously-allow-svg

**Comment by leerob** [comment]
https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy
