### ISSUE TITLE
`next lint` omits `app` dir by default.

### ISSUE THREAD

**Issue by wojtekolek** [vercel/next.js#44424]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
Binaries:
  Node: 18.4.0
  npm: 8.12.1
  Yarn: 1.22.19
  pnpm: 7.20.0
Relevant packages:
  next: 13.1.1
  eslint-config-next: 13.1.1
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), ESLint (eslint-config-next)

### Link to the code that reproduces this issue

-

### To Reproduce

Just run the `next lint` command when you have some issues inside `app` directory. They will be skipped by default as `app` dir is not listed inside `ESLINT_DEFAULT_DIRS` 

### Describe the Bug

By default, the `next lint` omits the `app` directory.

### Expected Behavior

Linter should also go through the `app` directory by default.

**Comment by avgupta456** [comment]
Also running into this issue.
