### ISSUE TITLE
Dynamic routes react router returns undefined

### ISSUE THREAD

**Issue by SergeySypalo** [vercel/next.js#44425]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/blob/canary/examples/dynamic-routing/pages/post/%5Bid%5D/%5Bcomment%5D.tsx

### To Reproduce

I tried to use this example from the official docs: https://nextjs.org/docs/routing/dynamic-routes
using the path as follows: **pages/post/[slug].js** and want to access the slug value on the page
```
import { useRouter } from 'next/router'

export default function Page() {
  const router = useRouter()
  console.log(router.query.slug)
  return (
    <>
     ... omitted for brevity
    </>
  )
}
```

### Describe the Bug

and got 'undefined' instead of slug value

### Expected Behavior

should get the slug value as described in the documentaion

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by GabenGar** [comment]
The [reference for `useRouter()`](https://nextjs.org/docs/api-reference/next/router#router-object):
>`query`: `Object` - The query string parsed to an object, including [dynamic route](https://nextjs.org/docs/routing/dynamic-routes) parameters. It will be an empty object during prerendering if the page doesn't use [Server-side Rendering](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props). Defaults to `{}`

**Comment by SergeySypalo** [comment]
Just looks at the docs once again and the example code for dynamic routing, it looks like there is no way to get **slug** value, when my page is **pages/post/[slug].js** (without using server rendering)?
So only the is to use pages/post/[slug]/index.js, is that correct?

**Comment by GabenGar** [comment]
No, you have to check `isReady` for truthiness before doing any manipulations with `query` parameter.

**Comment by SergeySypalo** [comment]
Tried solutions from this https://stackoverflow.com/questions/61040790/userouter-withrouter-receive-undefined-on-query-in-first-render with no luck, the query is empty as is ready is still false even when using useEffect.
Checked this example too: https://github.com/vercel/next.js/tree/canary/examples/active-class-name
It turned out to be that the page URL is displayed correctly in return, so in the HTML code displayed on the screen, but before the return, I can't get the slug value.
Would you mind sharing the working code?

**Comment by GabenGar** [comment]
```typescript
import { useRouter } from 'next/router'

export default function Page() {
  const router = useRouter();
  const { isReady, query } = router;
  
  useEffect(() => {
    // do not run effect until query is ready
    if (!isReady) {
      return
    }
    ...
  }, [...])
  
  return (
    !isReady ? <>Loading....</> : (...)}
  )
}
```

**Comment by SergeySypalo** [comment]
```
import { useEffect } from 'react'
import { useRouter } from 'next/router'

export default function Post() {	
	const router = useRouter()
	const { isReady, query } = router

	useEffect(() => {
	  if (!isReady) return	  
	}, [isReady, query])
	console.log(query)
	
	return <>
               Post text...
       </>
}
```
as a result in console I see `{}` istead of actual slug

**Comment by GabenGar** [comment]
Of course you see an empty object, because you console call runs on the first render. try calling it within `useEffect()` callback after `isReady` check.

**Comment by SergeySypalo** [comment]
Like this?
```
useEffect(() => {
	if (!isReady) return	  
	    console.log(query)
	}, [isReady, query])

```
If yes, nothing returned at all

**Comment by GabenGar** [comment]
Do you have an `/app` directory?

**Comment by SergeySypalo** [comment]
not yet, tried it, but it still contains a very crucial bug (https://github.com/vercel/next.js/issues/42648 and https://github.com/vercel/next.js/issues/42268), moving all meta tags from page body to head, messing all schema org metadata, so I'm waiting for it to be fixed, and then will be able to use it.

**Comment by GabenGar** [comment]
Does removing `query` from dependency array make it appear?

**Comment by SergeySypalo** [comment]
Nope, and eslint starts complaining:
React Hook useEffect has a missing dependency: 'query'. Either include it or remove the dependency array.eslint[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)

**Comment by techstaunch-solutions** [comment]
Faced same issue, currently there's a work around using serverSideProps,

**Comment by techstaunch-solutions** [comment]
Faced same issue, currently I have tried a work around, using `getServerSideProps`,
```ts
export const getServerSideProps = async ({ query }: any) => {
  return {
    props: {
      handle: query.handle
    }
  };
};

```

**Comment by SergeySypalo** [comment]
Looking at this issue now I guess I used a strange way to access the slug value. Now, in NextJS 14 and app directory, I do it like this:
```
export async function generateStaticParams() {	
	return ["1","2"].map(i => ({ page: i }))
}

export default function Posts({ params }) {	
	return <p>My blog - page {params.page}</p>
}
```

**Comment by GabenGar** [comment]
There was nothing strange, the question in the OP doesn't mention static generation and the repro doesn't use it either. So the router was operating client-side and therefore could only operate after hydration (hence the `isReady` check within `useEffect()`).

**Comment by SergeySypalo** [comment]
I guess you are right, but anyway, I'm trying to make the code as server-side as possible now, i.e. use server components. If I need a dynamic route param value I'd just pass it as a parameter to a client component instead of dealing with the router itself in the client component.
