### ISSUE TITLE
Allow to use react hooks inside getServerSideProps function

### ISSUE THREAD

**Issue by necimye** [vercel/next.js#44422]
### Describe the feature you'd like to request

I am using Nextjs for building a small project where I store access token inside react context and want to make api request from getServerSideProps function. But I am not allowed to call a hook that provides the access token stored in the context. It would be better to provide that feature

### Describe the solution you'd like

We should be allowed to call react hooks inside getServerSideProps function

### Describe alternatives you've considered

I thought wrapping that jsx element which uses the data inside another jsx element but it showed type issues in typescript.

**Comment by GabenGar** [comment]
There is no react render tree in the `getServerSideProps()` therefore it's literally impossible.
