### ISSUE TITLE
Array.prototype.at is not transpiled and causes TypeError in browsers

### ISSUE THREAD

**Issue by paulgreg** [vercel/next.js#44423]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue

https://codesandbox.io/s/awesome-dewdney-yp0x9d?file=/pages/index.tsx

### To Reproduce

Create a new app via `npx create-next-app@canary` with default options

Add `console.log([1,2,3].at(0))` in `pages/index.tsx`.

`npm run build && npm run start`

### Describe the Bug

Open http://localhost:3000 in Chrome 91, Firefox 89 or Safari 13 ([any browser not supporting array.at](https://caniuse.com/mdn-javascript_builtins_array_at))

An error will occurs : TypeError: "[...].at is not a function"

The code isn’t transpiled to older browsers.

### Expected Behavior

Code is transpiled and works on older browsers as described in [next browser support documentation](https://nextjs.org/docs/basic-features/supported-browsers-features).

### Which browser are you using? (if relevant)

Safari 13.1

**Comment by bertho-zero** [comment]
Same error, I have to temporarily replace my `Array.at`

**Comment by klaasman** [comment]
This seems to be fixed ~2 weeks ago: https://github.com/vercel/next.js/pull/44436
