### ISSUE TITLE
useRouter does not work with app directory + edge runtime

### ISSUE THREAD

**Issue by advaith1** [vercel/next.js#44438]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/advaith1/next-router-bug

### To Reproduce

1. Enable app directory and [edge runtime](https://beta.nextjs.org/docs/rendering/edge-and-nodejs-runtimes) in the config file:
```js
/** @type {import("next").NextConfig} */
module.exports = {
  reactStrictMode: true,
  experimental: {
    runtime: 'experimental-edge',
    appDir: true
  }
}
```

2. Make a client component that is displayed (can just be app/page.tsx)

4. Import useRouter from next/navigation and use it

Example app/page.tsx file:
```js
"use client";

import { useRouter } from "next/navigation";

export default function Client() {
  const router = useRouter();
  return <div>hello world</div>;
}
```

5. Run `next dev`

### Describe the Bug

An "invariant expected app router to be mounted" error occurs:

![image](https://user-images.githubusercontent.com/11778454/210024974-baf315a1-f989-4375-bd24-8f7471726089.png)

### Expected Behavior

There is no error and the router can be used for methods such as `router.push`.

### Which browser are you using? (if relevant)

Chrome 111.0.5485.0

### How are you deploying your application? (if relevant)

next dev

**Comment by hubertlepicki** [comment]
I think you're using it wrong. `app/page.jsx` should be a React Server Component, i.e. without "use client;", and *from within that page* you can render your <Client/> component. Put it in a separate file, I put my client components in `components` folder at project root, and import it from `app/page.jsx` like this instead:

```
import Client from '../components/client';

export default function Page({}) {
  return(<>
    This is my component:

    <Component />
  <>
);
}
```

**Comment by advaith1** [comment]
@hubertlepicki I just made `page` the client component to make the reproduction example simple; in my actual app `page` is a server component and this error happens when rendering the client component

**Comment by vtassios** [comment]
From the example you provide, seems that you have a wrong import.

It should be `import { useRouter } from 'next/router'`

**Comment by advaith1** [comment]
no

https://beta.nextjs.org/docs/api-reference/use-router

> The new useRouter hook should be imported from next/navigation and not next/router

**Comment by logemann** [comment]
Cant recreate the error with the exact same config and code.

**Comment by advaith1** [comment]
I am still getting this error in my provided repo on next 13.1.3-canary.0.

I am on Node v16.14.0, might that be relevant?

**Comment by WilsonPhoo** [comment]
I am getting this too. Any updates?

**Comment by balazsorban44** [comment]
I was no longer able to reproduce this, so it was likely fixed already. Please upgrade, and if you think you still have this problem, please open a new bug report.
