### ISSUE TITLE
Size/First Load JS: 0 when organizing routes without affecting the URL path

### ISSUE THREAD

**Issue by pimmee** [vercel/next.js#44449]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Dec 30 2022 16:44:59 GMT+0100 (Central European Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.1.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-1z86s6?file=package.json&view=editor

### To Reproduce

`npm run build` in terminal and see build output

### Describe the Bug

The build output display "Size / First load JS: 0" for pages that are in parenthesis folders (e.g. (marketing) or (shop)).

https://beta.nextjs.org/docs/routing/defining-routes#example-organize-routes-without-affecting-the-url-path

<img width="268" alt="image" src="https://user-images.githubusercontent.com/33460567/210088711-e6595587-3bb7-41ff-812a-c5d912e9dee6.png">

<img width="511" alt="image" src="https://user-images.githubusercontent.com/33460567/210088674-67bc016f-ad01-44d2-a263-12103082b974.png">

### Expected Behavior

To see the Size / First load JS for these pages.

**Comment by RemVN** [comment]
I have a same issue #44340. hope they will fix it soon

**Comment by pimmee** [comment]
@RemVN Oh, I missed that one. I'll close this issue in favour of yours.
