### ISSUE TITLE
TailwindCSS prefix not working

### ISSUE THREAD

**Issue by thienna** [vercel/next.js#44444]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      "autoprefixer": "^10.4.12",
      "postcss": "^8.4.18",
      "tailwindcss": "^3.2.4",

### Which example does this report relate to?

with-tailwindcss

### What browser are you using? (if relevant)

Chrome Version 108.0.5359.124 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

next build && next start

### Describe the Bug

Some Chrome extension CSS interferes with my website, so I decided to use the tailwind prefix to add a prefix class to prevent conflict CSS between my website and the chrome extension. I followed the docs then this happen, no CSS classes add to HTML:
<img width="1176" alt="Screen Shot 2022-12-30 at 14 09 31" src="https://user-images.githubusercontent.com/16835989/210044031-01bf24d7-6b8e-4714-a6d3-07d60f3bc1c1.png">
<img width="1440" alt="Screen Shot 2022-12-30 at 14 15 43" src="https://user-images.githubusercontent.com/16835989/210044463-a31c1389-07aa-489e-b712-6053e781dd06.png">

This issue happens to many of my websites on Vercel, I need some help!

### Expected Behavior

CSS classes added to HTML and working.

### To Reproduce

https://tailwindcss.com/docs/configuration#prefix
Just add 1 line config `prefix` in `tailwind.config.js`:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: 'test-prefix', // here
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by ajarouih** [comment]
ake sure that you have correctly configured the tailwindcss plugin in your postcss.config.js file. The configuration should look something like this:
```
module.exports = {
  plugins: [
    require('tailwindcss')({
      prefix: 'test-prefix',
    }),
    require('autoprefixer'),
  ],
};
```

**Comment by HaNdTriX** [comment]
From my point of view Next.js works as expected here.

Adding the prefix option to tailwind changes the output of the **generated class names**.
This means you have to use these classnames accordingly:

## Example

First add a prefix option to `tailwind.config.js`:

```diff
/** @type {import('tailwindcss').Config} */
module.exports = {
+  prefix: "tw-",
  // ...
};
```

then you need to change the use of these classnames as well!

```diff
-        <h1 className="text-6xl font-bold">
+        <h1 className="tw-text-6xl tw-font-bold">
          Welcome to{' '}
-          <a className="text-blue-600" href="https://nextjs.org">
+          <a className="tw-text-blue-600" href="https://nextjs.org">
            Next.js!
          </a>
        </h1>


For more info please read the [tailwind docs](https://tailwindcss.com/docs/configuration#prefix).

**Comment by ijjk** [comment]
Closing per above, thanks @HaNdTriX
