### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat '/app/.next/server/app'

### ISSUE THREAD

**Issue by khteh** [vercel/next.js#44442]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
"next": "13.1.1",
```

### Link to the code that reproduces this issue

private repo

### To Reproduce

```
$ yarn install
$ yarn build
```

### Describe the Bug

```
> Build error occurred
[Error: ENOENT: no such file or directory, lstat '/root/workspace/apps/api/.next/server/app'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/root/workspace/apps/api/.next/server/app'
}
```

### Expected Behavior

No build error

**Comment by lienista** [comment]
I'm hitting similar issue after upgrading to Node v18. File path works locally but on Vercel, it's unable to find the file.

**Comment by phunanon** [comment]
I'm having the same issue on `13.4.2`. A workaround is to, after the .next directory has been emptied, create an empty `server/app` directory by the time that it is required in the build process.
