### ISSUE TITLE
@next/font font doesn't load in initial page load on first visit

### ISSUE THREAD

**Issue by tvarwig** [vercel/next.js#44456]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.9.0
      npm: 8.19.1
      Yarn: 1.22.19
      pnpm: 7.12.2
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (@next/font)

### Link to the code that reproduces this issue

na

### To Reproduce

Create a next 13 application. In `_app.tsx`
```
import { Bebas_Neue, Roboto } from '@next/font/google'

const bebas = Bebas_Neue({ subsets: ['latin'], weight: ['400'], variable: '--font-bebas' })
const roboto = Roboto({ subsets: ['latin'], weight: ['300', '400', '500', '700'], variable: '--font-roboto' })

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <main className={`h-full ${bebas.variable} ${roboto.variable} font-sans`}>
```

```
// tailwind.config.js
...
 fontFamily: {
        sans: ['var(--font-roboto)', ...defaultTheme.fontFamily.sans],
        header: ['var(--font-bebas)', ...defaultTheme.fontFamily.sans],
},
...
```

### Describe the Bug

When a production website is loaded first time in a browser that has not been to the site before the font is not loaded. After a refresh the site is loaded with the font. Below is example screenshots.

![initial-visit](https://user-images.githubusercontent.com/8144988/210110689-0ad8bf8b-add8-43dc-a52e-1232c14463dd.png)

![after-refresh](https://user-images.githubusercontent.com/8144988/210110687-7ba59606-adb6-455b-97d6-2250a3b20f70.png)

### Expected Behavior

Font to load on first site visit. 

### How are you deploying your application? (if relevant)

Vercel

**Comment by flowtsohg** [comment]
Use display `swap` https://nextjs.org/docs/api-reference/next/font#display

e.g.
```ts
const bebas = Bebas_Neue({ subsets: ['latin'], weight: ['400'], variable: '--font-bebas', display: 'swap' })
```

**Comment by tvarwig** [comment]
@flowtsohg  Adding ` display: 'swap'` to the font worked.  

Vercel could this be updated in docs possibly? I tested this on two different sites I have and it looks like this workaround is needed in both

**Comment by nora-soderlund** [comment]
@flowtsohg, thank you.

For me, my fallback font was overriding the preferred font, even though it was successfully loaded and visible in the source.

```js
const roboto = Roboto({
    style: [ "normal", "italic" ],
    weight: [ "400", "500" ],
    subsets: [ "latin" ],
    fallback: [ "Times New Roman" ]
});
```

E.g. here the fallback font was Arial and the displayed font was Arial:
```css
.__className_12590b {
    font-family: '__Roboto_12590b', '__Roboto_Fallback_12590b', Times New Roman;
}
```
And if I removed the fallback font, the preferred font was displayed:
```css
.__className_12590b {
    font-family: '__Roboto_12590b', Times New Roman;
}
```

What could've caused this and **why does `display: "swap"` fix it?

**Comment by flowtsohg** [comment]
> @flowtsohg, thank you.
> 
> For me, my fallback font was overriding the preferred font, even though it was successfully loaded and visible in the source.
> 
> ```js
> const roboto = Roboto({
>     style: [ "normal", "italic" ],
>     weight: [ "400", "500" ],
>     subsets: [ "latin" ],
>     fallback: [ "Times New Roman" ]
> });
> ```
> 
> E.g. here the fallback font was `local("Arial")` and the displayed font was Arial:
> 
> ```css
> .__className_12590b {
>     font-family: '__Roboto_12590b', '__Roboto_Fallback_12590b', Times New Roman;
> }
> ```
> 
> And if I removed the fallback font from the class, the preferred font was displayed:
> 
> ```css
> .__className_12590b {
>     font-family: '__Roboto_12590b', Times New Roman;
> }
> ```
> 
> What could've caused this and **why does `display: "swap"` fix it**?

The display property isn't a Next thing, but rather a browser thing. Here's the page on MDN that says what each value means to the font-face loading https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display#values

In case of `swap` MDN says `Gives the font face an extremely small block period and an infinite swap period.`, which is a weird way to say that it will first get the fallback font as quickly as it can, and then swap when it finishes loading the proper font.

The Next default value is `optional` which MDN defines as `Gives the font face an extremely small block period and no swap period.`, which is yet again a weird way to say that it will first get the fallback font as quickly as it can, then it will get the proper font and cache it but never actually use it, and only upon a refresh/page switch where the font is needed again will it be used since it's already cached.

**Comment by TomSmedley** [comment]
> @flowtsohg Adding ` display: 'swap'` to the font worked.
> 
> Vercel could this be updated in docs possibly? I tested this on two different sites I have and it looks like this workaround is needed in both

I think it would be sensible to move the default to "swap", I had this issue and I've seen plenty of people have it on the NextJS Discord too. You can safely make the assumption that people want to see their custom font. With `@next/font` automatically optimizes your fonts, it should feel very much like a `plug-and-play` feature like `@next/image` does. 

Though that's just my opinion, I think it will avoid the many people who are having this issue and needing to search Github to get answers.

**Comment by behrangsa** [comment]
Looks like I am facing a similar issue.

* Code example: https://github.com/behrangsa/issues-nextjs-font-weights
* Deployed to: https://issues-nextjs-font-weights.vercel.app

If you keep pressing `Ctrl + R` and `Ctrl + Shift + R`, every now and then some weights don't load:

[Font Weights](https://user-images.githubusercontent.com/18451/215317137-c78638de-b1a2-4370-8cda-8bea8201990d.webm)

**Comment by chesterhow** [comment]
> Vercel could this be updated in docs possibly? I tested this on two different sites I have and it looks like this workaround is needed in both

I was facing this issue too, and after poking around the docs a little more I realised it is actually mentioned in the docs. It's under the "Font Optimization" page and not under the "@next/font" page itself, which is probably why many of us missed it.

https://nextjs.org/docs/basic-features/font-optimization#choosing-font-display

**Comment by hanneslund** [comment]
In the latest version of `@next/font`, `swap` is the default.

**Comment by philiplindberg** [comment]
As of `@next/font` v13.1.6, `optional` still seems to be the default `display` value used. I just deployed a new site this morning and had to explicitly set the `display` property to `swap` to show my custom fonts reliably.
