### ISSUE TITLE
Error: An error occurred in the Server Components render. he specific message is omitted in production builds to avoid leaking sensitive details.

### ISSUE THREAD

**Issue by yanalshoubaki** [vercel/next.js#44463]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/yanalshoubaki/website

### To Reproduce

I give the repository link.

### Describe the Bug

When i build next app, after start creating an optimized production build, it shows an error, " Failed to fetch data ", and show me this error after that  :
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.]

my code :
```js
async function getData(): Promise<Repo[]> {
  const res = await fetch(process.env.APP_URL + "/api/repos", {
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
  });
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

await getData();
```

api route :

```js

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  try {
    const response = await fetch(
      `https://api.github.com/users/yanalshoubaki/repos`,
      {
        headers: {
          Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
        },
      }
    );
    const data = await response.json();
    res.status(200).json(data);
  } catch (error) {
    if (error instanceof Error) {
      res.status(500).json({ error: error.message });
    }
  }
}
```

### Expected Behavior

The build work and deploy it to vercel

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

Vercel, npm run build

**Comment by jasonappah** [comment]
My best guess is that the fetch in the component is failing because you are trying to fetch from the API route and those routes aren't served during the build process. Since you're using a server component, my understanding is that you can safely fetch the data from GitHub directly in the component without leaking any tokens since that fetch should run on the server

**Comment by Ka0shi** [comment]
> My best guess is that the fetch in the component is failing because you are trying to fetch from the API route and those routes aren't served during the build process. Since you're using a server component, my understanding is that you can safely fetch the data from GitHub directly in the component without leaking any tokens since that fetch should run on the server

Thank you so much!! you can't imagine how painful these 3 days of figuring out the problem were for me. If it wasn't for you, I would have kept digging in the wrong place.

**Comment by yanalshoubaki** [comment]
> My best guess is that the fetch in the component is failing because you are trying to fetch from the API route and those routes aren't served during the build process. Since you're using a server component, my understanding is that you can safely fetch the data from GitHub directly in the component without leaking any tokens since that fetch should run on the server

Thank you so much, it's works now.
