### ISSUE TITLE
On-demand revalidation working on my machine but not on Vercel

### ISSUE THREAD

**Issue by nfts2me** [vercel/next.js#44460]
### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112
    Binaries:
      Node: 16.17.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.21.0
    Relevant packages:
      next: 13.1.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I'm using getStaticProps with "revalidate: false".
And using on-demand revalidation with an API to manually revalidate changes when source information is changed. Something like this:
https://vercel.com/docs/concepts/incremental-static-regeneration/quickstart#on-demand-revalidation

On my server when running "npm run build" && "npm run start" it works perfectly.
However, on Vercel, it doesn't work at all. It never revalidates, despite the logs show that it is revalidating.

I've tried with and without middleware rewriting, with the same problem.

The middleware rewrite is like this:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/109629895/210129204-a109b237-1305-41a6-92f0-a19ee6995b47.png">

And the revalidation code is quite straightforward:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/109629895/210129243-3e647834-2a03-40d7-abd2-3cdd753a2fe1.png">

On my machine, as said, it works without any problem. If I don't revalidate but change the data, it keeps the same cached version. If I call the API to revalidate, it changes it.

However, on Vercel, it just doesn't do anything, despite the logs seems to be working fine.
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/109629895/210129451-e82f2e00-4b90-4f17-90ac-d4a5a6b96fe4.png">

But calling again that URL gets the old cached version.

Same thing for both URL, for the not rewritten URL and for the rewritten URL using middleware.

And, as said, on-demands revalidation works perfectly on my machine with "npm run start", only revalidating the expected URL.

**Comment by dogukan6durukan** [comment]
If you make an internal API call from your client-side on your machine that will work but on production it will fail because you can only make API call to external resources like _FIREBASE_URL_ but if you want to fetch your internal API, you can write server-side code directly in getStaticProps. 

Checkout : [Next JS Docs](https://nextjs.org/docs/basic-features/data-fetching/get-static-props#write-server-side-code-directly)

**Comment by nfts2me** [comment]
> If you make an internal API call from your client-side on your machine that will work but on production it will fail because you can only make API call to external resources like _FIREBASE_URL_ but if you want to fetch your internal API, you can write server-side code directly in getStaticProps.
> 
> Checkout : [Next JS Docs](https://nextjs.org/docs/basic-features/data-fetching/get-static-props#write-server-side-code-directly)

Maybe I didn't explained properly, but the API is NOT called in the same call. The revalidation code is an API that is called externally to revalidate the URL Path. But is not called from within the code.

**Comment by smaeda-ks** [comment]
@nfts2me I believe we resolved this issue in your support ticket. It was confirmed that there was no bug, and your code needed some adjustment. Could you close this issue? Thanks

**Comment by nfts2me** [comment]
Not really.

On version 13.1.4 you resolved one of the issues I was having.

**Comment by smaeda-ks** [comment]
@nfts2me As mentioned in the ticket, that's expected behavior. See #45269

**Comment by nfts2me** [comment]
> @nfts2me
> 
> I've come across something quite similar, are you calling your api using a different subdomain? This seems to be the problem with vercel caches not being cleared (more details in the issue)
> 
> #45269

After talking with @Vercel they told us that (as said by @smaeda-ks) that's the expected behaviour. 
We are working with Middleware, and expected that everything went into the same "bucket"/"subdomain" when revalidating. But that wasn't the case. 

Even though Middleware rewrites the subdomains into a path, in terms of cache is uses per-subdomain cache.
So caches are not shared within rewritten subdomains.

We think once rewritten it should be the behaviour, but it isn't.
