### ISSUE TITLE
next build failed due to Collecting page data .Error: @next/font/google failed to run or is incorrectly configured

### ISSUE THREAD

**Issue by JianWang2016** [vercel/next.js#44462]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

next build

### What browser are you using? (if relevant)

Chrome Version 108.0.5359.124 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

failed to build

### Describe the Bug

/ ♥ npx create-next-app@latest test
✔ Would you like to use TypeScript with this project? … No / Yes
✔ Would you like to use ESLint with this project? … No / Yes
Creating a new Next.js app in /Users/adena/test.

Using npm.

Installing dependencies:
- react
- react-dom
- next
- @next/font

added 18 packages, and audited 19 packages in 9s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Initializing project with template: default 

Initialized a git repository.

Success! Created test at /Users/adena/test

[03:38:02] ~
// ♥ cd test
[03:38:07] (main) test
// ♥ next build
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data .Error: @next/font/google failed to run or is incorrectly configured.

Read more: https://nextjs.org/docs/basic-features/font-optimization
    at Object.<anonymous> (/Users/adena/test/node_modules/@next/font/google/index.js:15:7)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at 353 (/Users/adena/test/.next/server/pages/index.js:49:32)
    at __webpack_require__ (/Users/adena/test/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/Users/adena/test/.next/server/pages/index.js:329:39)

> Build error occurred
Error: Failed to collect page data for /
    at /usr/local/lib/node_modules/next/dist/build/utils.js:960:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
info  - Collecting page data .[03:38:18] (main) test

### Expected Behavior

I simply created a next.js project without adding any codes.

npm run dev  - success to display at localhost
next build - should produce no error
Instead, next build failed. I tried a few versions including create-next-app@13.1.0, but none could be built due to the same errors shown above.

Any help is greatly appreciated.

### To Reproduce

>npx create-next-app@latest test
>cd test
>next build

**Comment by hanneslund** [comment]
Does it work if you run `npm run build` instead of `next build`?

**Comment by JianWang2016** [comment]
Yes, it works using npm run build. Thanks so much!

**Comment by hanneslund** [comment]
Great! When running `next build`, I guess you were using a [globally installed](https://docs.npmjs.com/downloading-and-installing-packages-globally) version of `next` instead of the one in the project.

**Comment by WCByrne** [comment]
Maybe this should be opened as a new issue but I thought I'd try here first. I am able to create a standalone test app using `create next-app` and everything works fine using yarn 3. However when I try to setup the same app in a monorepo setup using yarn workspaces I get this error about the font package failing.

I initially thought maybe it was just a yarn issue but the fact that it appears to work fine as a single project leads me to believe that it is a workspace issue. 

I will work on setting up a demo of the issue but any thoughts in the meantime?

**Comment by WCByrne** [comment]
Here is a demo of the issue. This project worked fine until adding the blog app to a yarn workspace.
https://github.com/WCByrne/next-test
