### ISSUE TITLE
(AppDir) Unpredictable hydration errors in production

### ISSUE THREAD

**Issue by garronej** [vercel/next.js#44494]
Hello,

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 6.28.0
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 11.0.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/garronej/react-dsfr-next-appdir-demo

### To Reproduce

👉 Find a Replay.io recording of the error [here](https://app.replay.io/recording/production-hydration-error-appdir--22cef0f4-d572-4b6a-9cfe-23d3fd7317c1)

```bash
git clone https://github.com/garronej/react-dsfr-next-appdir-demo
cd react-dsfr-next-appdir-demo
git checkout repaly
rm -rf .next && yarn build && yarn start
```

Open [Replay](https://www.replay.io/) (or another browser but the bug is easier to be reproduced with replay.io).  

Navigate to `http://localhost:3000`.  

With the developer tools closed, hit `ctrl + r` until the toggle fails to tick.  

Example:  

https://user-images.githubusercontent.com/6702424/210230202-1c63d039-3130-44bb-8d9c-60ff24cf9d49.mov  

(On the video I only need to refresh two times but it can as well take 50 tries... )

### Describe the Bug

There is a random React hydration error that seems to be caused by the insertion of:  

```html
	<script charset="utf-8" data-webpack="_N_E:chunk-185" src="/_next/static/chunks/app/layout-fd4c780b92aa3f6f.js"></script>
	<script charset="utf-8" data-webpack="_N_E:chunk-390" src="/_next/static/chunks/390-3afbf3099c58beed.js"></script>
	<script charset="utf-8" data-webpack="_N_E:chunk-931" src="/_next/static/chunks/app/page-63bb863f91c0bf6b.js"></script>
```

in the `<head />`.  

![image](https://user-images.githubusercontent.com/6702424/210230737-3ce9dd15-d99e-47d0-b5f1-ee96d5ede66d.png)  

Find [here](https://github.com/garronej/react-dsfr-next-appdir-demo/blob/repaly/logs/html_sent_by_the_server.html) the HTML as sent by the server and [here](https://github.com/garronej/react-dsfr-next-appdir-demo/blob/repaly/logs/when_hydration_error_is_thrown_reorderd.html) the HTML when the hydration error is thrown.  

 

### Expected Behavior

No error

### Which browser are you using? (if relevant)

It's easyer to reproduce on Replay.io but it hapens with any browser

Thanks for your work,  

<sub>[NEXT-1382](https://linear.app/vercel/issue/NEXT-1382/appdir-unpredictable-hydration-errors-in-production)</sub>

**Comment by ItayElgazar** [comment]
@garronej  I'm experiencing the same. I realized it happens only with MUI without everything working as expected.

**Comment by garronej** [comment]
Hi @ItayElgazar,  
I don't think we should mislead Versel team into thinking this it a bug related to MUI.  
There is nothing that MUI can do that would justify Next behaving like this.  
It's a very tricky to reproduce bug, the fact that we can't reproduce anymore if we remove MUI doesn't tell us much.  
It could reappear any time given a certain planet alignment...

**Comment by nrezvoi** [comment]
I also have random hydration errors with app folder. Tried disabling/enabling different parts of my application, wasn't very helpful since error is random, but I noticed that making some of my client components lazy loaded solves it, further more, on particular page (server component) where I don't have much stuff but still have error I had links using `next/link` - I removed all of them - hydration errors disappeared (at least it looked like it, again - it's random), then I added just 1 link with only text and href - hydration errors started randomly again

```
"next": "^13.2.4",
"react": "^18.2.0",
"react-dom": "^18.2.0"
```

**Comment by timneutkens** [comment]
Hey @garronej, it's been a couple of months and we've fixed a very similar issue that also manifested as a hydration error, this was a bug in React. Can you check if it's fixed for you on the latest stable version of Next.js `npm install next@latest`? Thanks!

**Comment by garronej** [comment]
@timneutkens, sure thing! Thanks

**Comment by garronej** [comment]
@timneutkens Sorry it took me so long.  
I confirm the issue is fixed. 
Thank for your work! Closing
