### ISSUE TITLE
[NEXT-664] Late css modules styles loading in Next 13

### ISSUE THREAD

**Issue by Wojtazzzz** [vercel/next.js#44529]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

- Next 13.1.1 (app dir)
- React 18.2.0

### Link to the code that reproduces this issue

https://github.com/typeofweb/polskifrontend/pull/191

### To Reproduce

Copy pull request from link above.

### Describe the Bug

CSS Modules styles are fetched and loaded after page rendered. Error appears only on first subpage visit, on every subpage.

Open https://polskifrontend-cmx8dv3pq-typeofweb.vercel.app/ and click "O SERWISIE" in the top navigation. As you can see main container has 100% width, then styles are loaded and container has correct width.

### Expected Behavior

Styles should be loaded earlier.

<sub>[NEXT-664](https://linear.app/vercel/issue/NEXT-664/late-css-modules-styles-loading-in-next-13)</sub>

**Comment by mmiszy** [comment]
It's clearly visible in the Network tab that the CSS file is only fetched after navigating to the other page and it takes some time. This is the reason for the FOUC.

**Comment by visualies** [comment]
same issue here

**Comment by shuding** [comment]
This issue should be resolved in latest canary. Ref: #47708.
