### ISSUE TITLE
Docs: CSS bug in https://nextjs.org/telemetry

### ISSUE THREAD

**Issue by CrazyDiablo** [vercel/next.js#44551]
### What is the improvement or update you wish to see?

**here is what looklike now**
![16727955586241](https://user-images.githubusercontent.com/32573416/210467802-e6f889c0-3cff-4550-aa76-524d9c4ed28a.png)

**i wish to see it normal**

### Is there any context that might help us understand?

just css bug

### Does the docs page already exist? Please link to it.

https://nextjs.org/telemetry

**Comment by ijjk** [comment]
Good catch, this should now be patched!
