### ISSUE TITLE
`next` TypeScript Plugin Breaks Intellisense Autocomplete with Workspace TypeScript

### ISSUE THREAD

**Issue by karlhorky** [vercel/next.js#44574]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.12.1
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 3.8.1
    Relevant packages:
      next: 13.1.2-canary.0
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), TypeScript

### Link to the code that reproduces this issue

https://codesandbox.io/s/epic-maria-g3n3ym?file=/tsconfig.json

### To Reproduce

1. Use Next.js TypeScript plugin via `compilerOptions.plugins = [{ "name": "next" }]` in `tsconfig.json`
2. Use Workspace TypeScript version in VS Code via <kdb>ctrl/cmd</kbd>-<kbd>shift</kbd>-<kbd>P</kbd> and `TypeScript: Select TypeScript Version...` -> `Use Workspace Version`
3. Attempt autocomplete eg. with the text "styl" and then <kdb>ctrl</kbd>-<kbd>spacebar</kbd> -> 💥 "No suggestions."

Screenshot (broken):

<img width="928" alt="Screenshot 2023-01-04 at 20 43 27" src="https://user-images.githubusercontent.com/1935696/210637297-9541a655-f596-436b-bd66-34fdbc8c81d3.png">

Screenshot (working, without `next` TS Plugin configured, but with @mrmckeb's [`typescript-plugin-css-modules`](https://github.com/mrmckeb/typescript-plugin-css-modules) configured):

<img width="1354" alt="Screenshot 2023-01-04 at 20 36 16" src="https://user-images.githubusercontent.com/1935696/210637420-9f8b927a-ef56-4997-b3d6-d1cfd4c5aa1b.png">

Screenshot (Workspace Version of TS selected)

<img width="600" alt="Screenshot 2023-01-04 at 20 34 58" src="https://user-images.githubusercontent.com/1935696/210637561-b0fa8255-2c08-427d-8102-6ae410cf4c89.png">

### Describe the Bug

If the Workspace Version of TypeScript is used in VS Code (which some users have configured) along with the Next.js `"next"` TypeScript plugin in `tsconfig.json`, then IntelliSense autocompletion fails

### Expected Behavior

IntelliSense autocompletion should still work

**Comment by viktor-ku** [comment]
I've spent 3 hours trying to figure out why my neovim config is broken, turns out it's the `next` plugin. Oh well. Should I replace it with `typescript-plugin-css-modules` instead?

**Comment by karlhorky** [comment]
Oh, `typescript-plugin-css-modules` is not an alternative, it's just another plugin that we use, but one that is working.

**Comment by irg1008** [comment]
What happens if we disable the plugin? Does the app run and works as It should? This is, I think a breaking issue. Not being able to have intellisense is a big problem

**Comment by felixmokross** [comment]
Judging from this tweet, the plugin seems to be for docs and suggestions: https://twitter.com/delba_oliveira/status/1592209522281439232

So the app should still run fine when the plugin is disabled. In dev mode it runs for me. However, I can't find a way to disable it permanently. If I comment out the plugin in tsconfig, it gets added again as soon as I start dev mode again:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/11920943/216839846-05cec152-5f51-4a7b-bc0d-7a51466c01e5.png">

This makes this issue quite annoying. I have to start dev mode, then comment out the plugin, and then restart the language server to be able to work with a functioning Intelli Sense.

**Comment by karlhorky** [comment]
As of `next@13.1.6` I can no longer reproduce this problem (maybe even fixed in earlier versions):

https://user-images.githubusercontent.com/1935696/217299820-6d92ec5a-6fdf-4373-bdda-d14bbee13190.mp4

Closing this issue.
