### ISSUE TITLE
disable prerender in appdir

### ISSUE THREAD

**Issue by stephen-dahl** [vercel/next.js#44582]
inside of a /app/page.tsx I have 
```
export const dynamic = "force-dynamic";

const SearchPage = async () => {
  const fileName = "../data/repoInfo.json";
  const fileText = await readFile(fileName, { encoding: "utf-8" });
  const components = JSON.parse(fileText) as Component[];
  return <ComponentSearch components={components} />;
};
```
How can I disable prerender on this file since the data file does not exist at build time?

_Originally posted by @stephen-dahl in https://github.com/vercel/next.js/discussions/41745#discussioncomment-4585806_

**Comment by lluzak** [comment]
@stephen-dahl did you try ?
```js
export const dynamic = "force-dynamic";
export const revalidate = 0;
```

**Comment by stephen-dahl** [comment]
thought I did but it is working now, must have tried them separately

**Comment by logemann** [comment]
> thought I did but it is working now, must have tried them separately

makes sense to close this one right?
