### ISSUE TITLE
[NEXT-602] NextJS 13: Scroll to #HashID not working in appDir

### ISSUE THREAD

**Issue by ExactlyRahul** [vercel/next.js#44625]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
Platform: linux
Arch: x64
Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
Binaries:
Node: 18.12.1
npm: 9.2.0
Yarn: N/A
pnpm: N/A
Relevant packages:
next: 13.1.1
eslint-config-next: 13.1.1
react: 18.2.0
react-dom: 18.2.0

I have tested on latest: 13.1.2-canary.1 too, its same.

### Which area(s) of Next.js are affected? (leave empty if unsure)

*No response*

### Link to the code that reproduces this issue

[https://github.com/OptimBro/next13-scroll-to-hashid-bug](https://github.com/OptimBro/next13-scroll-to-hashid-bug)

### To Reproduce

Click on the button link where it is linking to a HTML hash ID.
Once you click on it, it will do nothing.

When we are on different page, and click on the button, it will still do nothing.

When we open browser dev tools, and click on the hashID from source code, it will work. Check below:

![](https://uploads.linear.app/099ed59a-06c6-472f-9977-4798721bda90/18a30072-a0d7-44b3-a156-bf9e48bbc14a/2a1a16b1-b274-427d-afe2-7869416b6da0)

The issue is with only `appdir`, things are working fine with `pages `directory.

### Describe the Bug

Scroll to hash id is not working.

When I click on below items which are <Link> components, they don't scroll to hash id

![](https://uploads.linear.app/099ed59a-06c6-472f-9977-4798721bda90/be709642-845f-4965-98ac-f71f69425da5/5b7c461b-4c89-4e9c-b787-fd6b98c25190)

It should scroll to bottom of the page (below section)

![](https://uploads.linear.app/099ed59a-06c6-472f-9977-4798721bda90/a52688ad-0673-46a2-abe0-be7bf76ed01c/89ce5fad-7896-430b-845a-ee538e81c87a)

It doesn't work on  refresh, from another page anywhere.

### Expected Behavior

`<Link href="/#hashid">Hash ID Section</Link>`

When clicking on above element it should scroll to the section where `HashID` is used, eg. below:

`<div id="hashid"> `

### Which browser are you using? (if relevant)

*No response*

### How are you deploying your application? (if relevant)

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-602](https://linear.app/vercel/issue/NEXT-602/nextjs-13-scroll-to-hashid-not-working-in-appdir)</sub>

**Comment by selenecodes** [comment]
Running into the same issue. Wrapping next/link in your own custom component and using an `<a>` tag when the URL contains a `#` seems to work best atm

**Comment by selenecodes** [comment]
Here's an example of a component you could use:
```
import type { ComponentProps, ReactElement } from 'react'
import React, { forwardRef } from 'react'
import NextLink from 'next/link'

type AnchorProps = Omit<ComponentProps<'a'>, 'ref'> & {
  newWindow?: boolean
  prefetch?: boolean
}

export const Anchor = forwardRef<HTMLAnchorElement, AnchorProps>(function (
  { href = '', children, newWindow, prefetch = true, ...props },
  // ref is used in <NavbarMenu />
  forwardedRef,
): ReactElement {
  if (newWindow) {
    return (
      <a
        href={href}
        ref={forwardedRef}
        rel="noreferrer"
        target="_blank"
        {...props}
      >
        {children}
      </a>
    )
  }

  if (!href) {
    return (
      <a ref={forwardedRef} {...props}>
        {children}
      </a>
    )
  }

  if (href.includes('#')) {
    return (
      <a href={href} ref={forwardedRef} {...props}>
        {children}
      </a>
    )
  }

  return (
    <NextLink href={href} prefetch={prefetch} ref={forwardedRef} {...props}>
      {children}
    </NextLink>
  )
})
```

**Comment by OptimBro** [comment]
Won't fix?

**Comment by Falven** [comment]
Having this issue still. Update on a fix?

**Comment by therealsuji** [comment]
Same here still having this issue in 13.2
