### ISSUE TITLE
Incorrect layout rendered after navigating back

### ISSUE THREAD

**Issue by rijk** [vercel/next.js#44649]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
npx next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.22.0
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/github/rijk/next-app-playground/repro/layout-issue

### To Reproduce

1. Navigate to /www
2. Navigate to /www/learning
3. Navigate back to /www

### Describe the Bug

Note that instead of the correct tree:

```
www layout
www page (should show www layout above)
```

After following the navigation steps, this is rendered:

```
[org] layout
www page (should show www layout above)
```

So the `www layout` is **not rendered**, and the `[org] layout` is **not unmounted**. When you reload you see the correct tree rendered again.

### Expected Behavior

The correct layout should always be rendered, regardless off soft or hard navigation.

**Comment by hampak** [comment]
Hello, @rijk.

Any updates on this problem?

**Comment by rijk** [comment]
idk, can't seem to reproduce it anymore. I'll close this issue
