### ISSUE TITLE
font with tailwind

### ISSUE THREAD

**Issue by pogran** [vercel/next.js#44652]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

-

### Link to the code that reproduces this issue

font error

### To Reproduce

install next last version , tailwind, add font exo_2

### Describe the Bug

this doc https://beta.nextjs.org/docs/optimizing/fonts#with-tailwind-css doesn't work

I install tailwind and add this font  https://fonts.google.com/?query=exo+2 by this doc, but this font not load if open new tab, but font load when you refresh the page.

### Expected Behavior

-

**Comment by Archiyopp** [comment]
I think you need to put display: swap [nextjs.org/docs/api-reference/next/font#display](https://nextjs.org/docs/api-reference/next/font#display) or check this issue https://github.com/vercel/next.js/issues/44456

**Comment by pogran** [comment]
@Archiyopp thx, i helped me with this problem!
