### ISSUE TITLE
Static media not being included when using next/dynamic with ssr: false

### ISSUE THREAD

**Issue by deini** [vercel/next.js#44658]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.19.3
      npm: 6.14.17
      Yarn: 1.22.15
      pnpm: 7.5.2
    Relevant packages:
      next: 13.1.2-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue

https://github.com/deini/no-static-media-on-dynamic-import

### To Reproduce

1. Clone the reproduction repo
2. `pnpm install`
3. `pnpm run dev`
4. A next.js logo should be rendered but it isn't

### Describe the Bug

When importing static media assets such as .svg in a component which is imported using `next/dynamic` with `ssr: false` the media file is not copied to `.next/static/media/`. 

```js
// Logo component imports an svg file
const Logo = dynamic(() => import('../Logo'), {
  ssr: false,
});
```

This used to work in Next `13.0.6` and broke in `13.0.7`

### Expected Behavior

The media files should be copied to the Next's static media directory.

The reproduction repo has a `next-13.0.6` branch that shows it working.

**Comment by Trallp** [comment]
The same problem https://github.com/vercel/next.js/issues/44143
