### ISSUE TITLE
Route Grouping with Edge runtime leads to 500 error on Vercel deployment

### ISSUE THREAD

**Issue by fdecampredon** [vercel/next.js#44657]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.2-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/fdecampredon/app-dir-grouping-edge-bug

### To Reproduce

Deploy a repository to vercel with a  route group, and `runtime: 'experimental-edge'` runtime in `next.config.js`. The routes under the Route Group will render a 500 error (see: https://app-dir-grouping-edge-fyaqtwyus-fdecampredon.vercel.app/home).

### Describe the Bug

Routes under a Route Groups with edge runtime returns a 500 error *on Vercel deployments*, works on local with production build.

### Expected Behavior

Routes under routes group should render properly.

### Which browser are you using? (if relevant)

Chrome 108.0.5359.124

### How are you deploying your application? (if relevant)

Vercel

**Comment by smaeda-ks** [comment]
@fdecampredon I believe this can be merged into https://github.com/vercel/next.js/issues/43458

**Comment by fdecampredon** [comment]
Yes it's clearly a duplicate, I don't know why I didn't see this previous issue.
