### ISSUE TITLE
dynamic import with ssr:false causes The server could not finish this Suspense boundary 

### ISSUE THREAD

**Issue by shriq011** [vercel/next.js#44650]
Update: you could try the latest canary (>= 13.0.7-canary.5) now, we have migrated `next/dynamic` to Suspense and React.lazy based API in #42589, should work properly now
next version =. 13.0.7 , using dynamic import with ssr=false gives this error still 
_Originally posted by @huozhi in https://github.com/vercel/next.js/issues/36636#issuecomment-1351265185_

**Comment by shriq011** [comment]
@huozhi looks like the issue is not fixed yet

**Comment by wadehammes** [comment]
Duplicate of #44083 which was caused by PR #42589 @balazsorban44

**Comment by huozhi** [comment]
> Duplicate of #44083 which was caused by PR #42589 @balazsorban44

Close per above
