### ISSUE TITLE
In nextjs 13, could not initialize firebase-admin in app directory artchitecture

### ISSUE THREAD

**Issue by thanhdatvo** [vercel/next.js#44691]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000
    Binaries:
      Node: 19.2.0
      npm: 9.2.0
      Yarn: N/A
      pnpm: 7.18.1
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.1.1", newest: "13.1.2-canary.2".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue

npx create-next-app@latest --example with-turbopack   

### To Reproduce

after running above command to initialize the project:
Step 1: install firebase admin
pnpm i firebase-admin
Step 2: add these code to the top of app/page.tsx to initialize firebase app to fetch firestore database in server side to render react in server  
....
import * as firebaseAdmin from 'firebase-admin';

async function getFirestoredata(pageId: string) {
    firebaseAdmin.initializeApp();
}
....
Step 3: go to localhost:3000 ->  3 errors below appear

### Describe the Bug

 
Turbopack failed to compile
1 of 21 
Error resolving commonjs request

error - [resolve] [project-with-next]/node_modules/.pnpm/retry-request@5.0.2/node_modules/retry-request/index.js  Error resolving commonjs request
  unable to resolve module "request"
  
  | It was not possible to find the requested file.
  | Parsed request as written in source code: module "request"
  | Path where resolving has started: [project-with-next]/node_modules/.pnpm/retry-request@5.0.2/node_modules/retry-request/index.js
  | Type of request: commonjs request
  | Import map: No import map entry
  | 

 
Turbopack failed to compile
2 of 21 
Error resolving commonjs request

error - [resolve] [project-with-next]/node_modules/.pnpm/google-auth-library@8.7.0/node_modules/google-auth-library/build/src/auth/pluggable-auth-handler.js  Error resolving commonjs request
  unable to resolve dynamic
  
  | It was not possible to find the requested file.
  | Parsed request as written in source code: dynamic
  | Path where resolving has started: [project-with-next]/node_modules/.pnpm/google-auth-library@8.7.0/node_modules/google-auth-library/build/src/auth/pluggable-auth-handler.js
  | Type of request: commonjs request
  | Import map: No import map entry

Turbopack failed to compile
3 of 21 
Error resolving commonjs request

error - [resolve] [project-with-next]/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.mjs  Error resolving commonjs request
  unable to resolve module "encoding"
  
  | It was not possible to find the requested file.
  | Parsed request as written in source code: module "encoding"
  | Path where resolving has started: [project-with-next]/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.mjs
  | Type of request: commonjs request
  | Import map: No import map entry
  | 

### Expected Behavior

Should not have bug

**Comment by mehmetkose** [comment]
can you call firebase-admin on the client side? I'm not sure tho

**Comment by kossnocorp** [comment]
@thanhdatvo you gotta install `request` to make it work: `npm i --save request`.

@mehmetkose no you can't but it will work in a server component.

**Comment by ignacioportigliatti** [comment]
But the library is deprecated :/

> @thanhdatvo you gotta install `request` to make it work: `npm i --save request`.
> 
> @mehmetkose no you can't but it will work in a server component.

**Comment by thanhdatvo** [comment]
Hi all,
Currently I'm not working for that project, so I will close this issue.
Feel free to reopen this issue if you have them same problem.
