### ISSUE TITLE
Defining a function that uses Sharp results in a build error

### ISSUE THREAD

**Issue by gregorias** [vercel/next.js#44697]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.3.0
      npm: 9.2.0
      Yarn: 1.22.19
      pnpm: 7.18.0
    Relevant packages:
      next: 13.1.2-canary.2
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/gregorias/sharp-nextjs-bug

### To Reproduce

1. Clone the reproduction repo.

```shell
git clone https://github.com/gregorias/sharp-nextjs-bug
```

2. Install deps.

```shell
cd sharp-nextjs-bug
npm i
```

3. Build the site.

```shell
npm run build
```

### Describe the Bug

The build fails with the following message:

```
./node_modules/detect-libc/lib/detect-libc.js
Module not found: Can't resolve 'child_process' in '/Users/grzesiek/Code/yolo/sharp-nextjs-bug/node_modules/detect-libc/lib'

Import trace for requested module:
./node_modules/detect-libc/lib/detect-libc.js
./node_modules/sharp/lib/utility.js
./node_modules/sharp/lib/index.js

./node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/sharp/build/Release/sharp-darwin-arm64v8.node
./node_modules/sharp/build/Release/ sync ^\.\/sharp\-.*\.node$
./node_modules/sharp/lib/sharp.js
./node_modules/sharp/lib/input.js
./node_modules/sharp/lib/index.js

./node_modules/sharp/lib/libvips.js
Module not found: Can't resolve 'fs' in '/Users/grzesiek/Code/yolo/sharp-nextjs-bug/node_modules/sharp/lib'

Import trace for requested module:
./node_modules/sharp/lib/libvips.js
./node_modules/sharp/lib/constructor.js
./node_modules/sharp/lib/index.js

./node_modules/sharp/lib/libvips.js
Module not found: Can't resolve 'child_process' in '/Users/grzesiek/Code/yolo/sharp-nextjs-bug/node_modules/sharp/lib'

Import trace for requested module:
./node_modules/sharp/lib/libvips.js
./node_modules/sharp/lib/constructor.js
./node_modules/sharp/lib/index.js

./node_modules/sharp/lib/utility.js
Module not found: Can't resolve 'fs' in '/Users/grzesiek/Code/yolo/sharp-nextjs-bug/node_modules/sharp/lib'

Import trace for requested module:
./node_modules/sharp/lib/utility.js
./node_modules/sharp/lib/index.js
```

### Expected Behavior

The build succeeds. Just importing sharp (see `pages/index.tsx`) should not result in an obscure build error.

I suspect that it has something to do with Sharp not working in client code (https://github.com/lovell/sharp/issues/2350#issuecomment-685167291), but I couldn't figure out what the appropriate resolution for this should be. I don't intend to use Sharp client-side, but how do I import Sharp into modules that are used build time only and not have it crash the build process?

**Comment by mertcanaltin** [comment]
hi @gregorias :heart: 

To solve this problem, you need to find a way to use the sharp module only in the build process and not in client-side code. One way to do this is to compile the client side code with Webpack and parse the code using the sharp module from the code served to the client, I was wondering? Would a build like this solve this problem?

**Comment by gregorias** [comment]
Hi @mertcanaltin, thank you for a quick answer.

1. I'd like to propose to update the build-time code elimination process to include unused code. In the reproduction repo, if you change `pages/index.tsx` to have `getStaticProps` like so:

```typescript
import sharp from 'sharp';

function foo(src: string) {
  sharp(src);
}

export default function Home() {
  return (<main></main>);
}

export async function getStaticProps() {
  foo;
  return { props: {}};
}
```

Then the build works. I think it's reasonable to expect that an unused function like foo would be eliminated without using it in `getStaticProps`.

2. I'm not expecting a perfect code-elimination that would work for more advanced cases, e.g., using `sharp` in a standalone module that mixes client-side and build-time code, so then creating a separate build-time only module makes sense.

**Comment by mertcanaltin** [comment]
@gregorias I agree with what they said yes adding it as a module as needed will only have been used during the build process and will not be included in the client side package 🤔
