### ISSUE TITLE
edge+appdir: `useSelectedLayoutSegment` - Cannot destructure property 'tree' of '(0 , _react).useContext(...)' as it is null.

### ISSUE THREAD

**Issue by james-elicx** [vercel/next.js#44725]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: 7.14.2
    Relevant packages:
      next: 13.1.2-canary.3
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/james-elicx/nextjs13-error-reproduction/tree/edge-useselectedlayoutsegment

### To Reproduce

Clone repository and switch to the `edge-useselectedlayoutsegment` branch, install dependencies with `npm install`, and run it with `npm run dev`

### Describe the Bug

Using useSelectedLayoutSegment in a client component inside the app directory on the edge runtime throws the following error in the browser.
```
Unhandled Runtime Error
TypeError: Cannot destructure property 'tree' of '(0 , _react).useContext(...)' as it is null.
```
It works fine if the runtime is changed to `nodejs`, but when using the `edge` or `experimental-edge` runtimes, it results in an error.

I did find another issue with this error (#42300), however, their solution was to make it a client component. In my reproduction, it already is a client component.

I would speculate that this might be related to a larger issue with using `next/navigation` on the edge runtime due to the `useRouter` error in #44438.

### Expected Behavior

There should be no errors and it should work fine.

**Comment by james-elicx** [comment]
Just checked with the latest canary version of nextjs and this issue still appears to be happening. Would be nice if the relevant labels were added to this issue...

**Comment by joneslloyd** [comment]
For what it's worth:

I encountered this issue* when I tried to use it in a `/pages/` directory instead of an `/app/` directory.

My project was partially migrated. When I moved this hook call to the `/app/` directory, it _automagically_ worked.






* User error because I didn't read the documentation properly

**Comment by balazsorban44** [comment]
I was no longer able to reproduce this, so it was likely fixed already. Please upgrade, and if you think you still have this problem, please open a new bug report.
