### ISSUE TITLE
Issue with NextJS >= 13.0.7 with react-ssr-prepass and dynamic components

### ISSUE THREAD

**Issue by LiamMartens** [vercel/next.js#44727]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: linux
      Arch: x64
      Version: #202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.5.2
    Relevant packages:
      next: 13.0.7
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue

https://github.com/LiamMartens/nextjs-13-prepass-dynamic-import-reproduction

### To Reproduce

- Create a new NextJS project (>=13.0.5)
- Add `react-ssr-prepass` and set it up with `getStaticProps` (very simply add `await ssrPrepass(<Home />)` to the `getStaticProps` function in the homepage)
- Add a dynamic component on the homepage

### Describe the Bug

From Next 13.0.7 onwards it looks like the updated `dynamic` breaks `react-ssr-prepass`. I understand prepass should probably be removed in favor of native suspense and fetching methods, however we have projects that extensively use `prepass` at the this time.

If the official guidance is to deprecate this way of data fetching, it would be great to have guidance as to how to upgrade from a prepass fetching strategy to something like server components. Although, as far as I'm aware this is not ready for production yet anyways so it would be better to keep support for prepass.

### Expected Behavior

This works up until NextJS 13.0.6; the dynamic components should just work.

**Comment by Blitss** [comment]
Doesn't work for me either, didn't realize this was a Next issue

**Comment by Blitss** [comment]
Doesn't work for me too, downgrading to 13.0.6 works fine

**Comment by JanKaifer** [comment]
Looking at the `react-ssr-prepas` docs:
> react-ssr-prepass on the other hand is a custom implementation of a React renderer. It attempts to stay true and correct to the React implementation by:
>
> Mirroring some of the implementation of ReactPartialRenderer
Leaning on React elements' symbols from react-is
Providing only the simplest support for suspense

Maybe guys at `react-ssr-prepass` might know a bit more, about what is the issue.
Could someone open an issue there?

**Comment by huozhi** [comment]
`next/dynamic` starts to use native react primitives like `Suspense` and `React.lazy` since next 13.0.7, and react server dom could already handle the it during SSR, you don't really need the `react-ssr-prepass` for this case. Removing it is the way to go. The library is still saying `Note: Suspense is unstable and experimental` but it's actually ready to use in production now with react 18.

**Comment by LiamMartens** [comment]
@huozhi I did think this, however; from what I understand full Suspense support is only supported in the currently still experimental `appDir` - which we didn't want to switch to yet until stable.

**Comment by Blitss** [comment]
> you don't really need the `react-ssr-prepass`

You need it for cases like react Apollo SSR (`getDataFromTree`) when using along with dynamic imports. If you don't use a prepass then imports won't get resolved and Apollo won't fetch the queries inside the dynamic components.

**Comment by huozhi** [comment]
I've addressed the issue in #45565, which revertes the loadable change that we had before. Ideally it will solve your issue in next canary or patch, please let us know if that solves your problem

**Comment by huozhi** [comment]
Can you try `next@13.1.7-canary.5`? It works for me with the reproduction, thanks!
