### ISSUE TITLE
Next.js SSR performance degradation with React 18 (React 17 -> React 18)

### ISSUE THREAD

**Issue by joel1st** [vercel/next.js#44766]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64
    Binaries:
      Node: 16.2.0
      npm: 7.13.0
      Yarn: 1.22.19
      pnpm: 7.5.2
    Relevant packages:
      next: 12.3.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/joel1st/nextjs-ssr-perf-test

### To Reproduce

https://github.com/joel1st/nextjs-ssr-perf-test#reproduction

### Describe the Bug

React 18 + Next.js performs worse than React 17 + Next.js. This is across Next.js 12 and 13. This is not the case with raw React renderToString(), React 18 has better performance in comparison to React 17 when Next.js is omitted - Separate React specific benchmarks here: https://github.com/SuperOleg39/react-ssr-perf-test

| Stat                                            | Next.js 12 / React 17 | Next.js 12 / React 18 | Next.js 13 / React 18 |
|-------------------------------------------------|-----------------------|-----------------------|-----------------------|
| Average Requests Per Second (higher is better)  | 22.8                  | 18.3 (-19.7%)         | 17 (-25.4%)           |
| Average Latency (lower is better)               | 2436.85 ms            | 3303.44 ms (-35.5%)   | 3171.23 ms (-27.3%)   |

### Expected Behavior

I expectReact 18 to perform on par or better than React 17, as raw React benchmarks show a performance improvement between these versions.

**Comment by feedthejim** [comment]
hey @joel1st, thanks for opening the issue! Thanks for the thorough repro case, this is fairly interesting. Taking a look.

**Comment by feedthejim** [comment]
what I found after a quick investigation:
- in Next.js, going from 17 to 18 changes the rendering code path to stop using `renderToString` for its streamable equivalent. The reason for this is that as indicated in the doc, [renderToString does not support well Suspense and streaming](https://reactjs.org/docs/react-dom-server.html#rendertostring), and we want Next.js to be able to use the full power of concurrent React, so we can't go back to `renderToString`
- the streaming version of React is slower and that is corroborated by the React benchmark you linked, thus we can expect Next to also be slightly slower as well.

There's not much that is actionable here so I'm gonna go ahead and close the issue!

**Comment by joel1st** [comment]
@feedthejim Interesting, thanks for investigating. Unfortunate that there isn't a way to control the rendering behaviour. Although I didn't include it in the benchmark, we are seeing 2-3x the amount of CPU usage in our prod environment from this update. As we have quite a heavy SSR site (with a lot of traffic), we require quite a bit more infrastructure to support the same load.

**Comment by feedthejim** [comment]
A few tips:

- a heavy part of the CPU usage is due to the font optimisation on pages routes. You can disable that if you don't use it and you can go for next/font instead, which is better.
- maybe try the app folder routes? It's somewhat lighter CPU wise

**Comment by joel1st** [comment]
Thanks @feedthejim 
Are there any docs for disabling these font optimisations? We are using a regular css import which references static font files. Will this hit the CPU usage issue you are referring to?

![Screen Shot 2023-01-13 at 10 57 06 am](https://user-images.githubusercontent.com/4032164/212205998-14e9ce48-9015-4b76-aadc-7caae9148a06.png)
