### ISSUE TITLE
resolvedUrl in getServerSideProps is not a URL

### ISSUE THREAD

**Issue by akselinurmio** [vercel/next.js#44818]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.2-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/akselinurmio/resolvedurl

### To Reproduce

1. Start development server by running `npm run dev`.
2. Open web browser and navigate to http://localhost:3000/
3. Examine the following results:
   1. _See following error in the browser:_
      <img width="732" alt="Screenshot 2023-01-12 at 15 10 40" src="https://user-images.githubusercontent.com/3000387/212074896-8df088dd-523c-4763-a646-1e2b9dcdb390.png">
   2. _And following log line in the server console:_
      ```
      This resolvedUrl should be URL, but is a path instead: /
      ```

### Describe the Bug

`resolvedUrl` property of the `context` parameter of the `getServerSideProps` is defined in [the documentation](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#context-parameter) as a URL of the current document, but instead it is just a path part of a URL.

[Documentation of `getServerSideProps`](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#context-parameter):

> `resolvedUrl`: A normalized version of the request URL that strips the `_next/data` prefix for client transitions and includes original query values.

It can't be parsed with `new URL(resolvedUrl)` as is, but has to be combined with some absolute URL first.

### Expected Behavior

URL was officially defined in 1994 by Sir Tim Berners-Lee, and back then, HTTP URLs were defined as always including the hostname. This same interpretation has, as to my personal experience, followed more or less to this day.

I’m aware of [”the new URL spec”](https://url.spec.whatwg.org/) worked by WHATWG, but I see that, for the most of us, just the abbreviation "URL" still means an absolute URL as defined by Berners-Lee. Not a ”relative URL” of the new URL specification.

Therefore I think that it should be made clear in the naming of the `resolvedUrl` property and in its documentation, that it’s not an absolute URL, but a relative URL, or **path** to be super clear.

**Comment by balazsorban44** [comment]
`url` in this case is based on the `IncomingMessage` interface of Node.js, which is documented here:
- https://nodejs.org/api/http.html#messageurl

The [documentation you linked](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#context-parameter) to also mentions that `req` is based on the above, so this is expected.


The documentation does not mention that it's an absolute URL. This unfortunately cannot be changed without being a breaking change.

**Comment by balazsorban44** [comment]
`url` in this case is based on the `IncomingMessage` interface of Node.js, which is documented here:
- https://nodejs.org/api/http.html#messageurl

The [documentation you linked](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#context-parameter) to also mentions that `req` is based on the above, so this is expected.


The documentation does not mention that it's an absolute URL. This unfortunately cannot be changed without being a breaking change.

**Comment by akselinurmio** [comment]
I’d disagree, as the documentation of the `resolvedUrl` doesn't mention the `req` object in any way. What I’d like to see the documentation explicitly declare is that it's indeed a ”relative URL”. This way there wouldn’t be any ambiguity on the supposed format.
