### ISSUE TITLE
Ability to add custom headers to the on demand revalidation request

### ISSUE THREAD

**Issue by blurrah** [vercel/next.js#44811]
### Describe the feature you'd like to request

When calling `res.revalidate()` from an API route I'd like to see the ability to add custom headers to the actual revalidate request.

A use case of this is bypassing protection. Vercel has a bypass protection header which we use to access our testing/staging environments. While this works for accessing the API route, it will not get passed on and the revalidate call will fail on a 401.

### Describe the solution you'd like

An additional option where we can define custom headers:
```ts
await res.revalidate(`/my-path`, {
      unstable_customHeaders: {
        'x-vercel-protection-bypass': req.headers['x-vercel-protection-bypass']
      }
    })
```

The `revalidate` function can then merge those headers and use them in the fetch request.

### Describe alternatives you've considered

Not a lot of alternatives to consider, you could allow custom cookies or allow for only one custom header to be set if you don't want to give developers the ability to override a required header that might break the experience.

While this issue pops up on Vercel for me, I don't think we should fix it just for Vercel but allow developers to bypass other platforms security as well.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.3-canary.3` of Next.js, please update and give it a try!

**Comment by blurrah** [comment]
Can confirm that `v13.1.3-canary.4` works with the Vercel bypass out of the box. The `allowedRevalidateHeaderKeys` should work with any other header you'd need to pass. Thanks for picking it up!
