### ISSUE TITLE
[NEXT-493] Docs: next.js after 13.0.7 dev server cluster worker restarter causes NODE_OPTIONS='--inspect' to use port 9230 instead of 9229 and so on

### ISSUE THREAD

**Issue by michaellopez** [vercel/next.js#44817]
### What is the improvement or update you wish to see?

This affects the following versions of nextjs:
- 13.0.7
- 13.1.0
- 13.1.1
- and probably some future versions too

TLDR: Set environment variable `__NEXT_DISABLE_MEMORY_WATCHER=1` if you don't have Out Of Memory issues. Otherwise read on to understand the problem but unfortunately no solution.

I would like better documentation or information regarding PR https://github.com/vercel/next.js/pull/43958. Or at least better exposure for such a big change in execution model without having to dig through releaselogs/changelogs for something unknown. Hopefully this issue might help exposure and future googlers.

The linked PR introduces the cluster module to start the next dev server in a forked process so that it can monitor the memory usage of the dev server and restart it if it gets too high.

This model causes the port used by inspection to get increased by 1 for the first start and every restart after that. So all official documentation and third party/user contributed educational material regarding debugging like tutorials, video, courses, etc will stop working **by default** as the changes in the linked PR are opt-out, rather than inform the user in a proper way and then be opt-in.

Basically providing `NODE_OPTIONS=--inspect` will assign the default port of 9229 to the main node process that handles nextjs. Before the linked PR was merged this process was the same process that started and ran the next dev server, meaning attaching a debugger to this process worked as expected; we could debug our nextjs code.

After the merge though, the next dev server is run in a forked child process to the main process, meaning we now have to attach to port 9230 (node increases the port number by 1 automatically) because port 9229 is assigned to the main process that does the actual forking. If you happen to run into the OOM issues that the PR was meant to work around, your next dev server will hit the memory limit and will get stopped and then started again by the main node process. This is a new forked child process and also a new inspect port number, 9231 (increased by 1 again) and so on.

I appreciate the workaround in the PR, it is quite clever. Hopefully this issue can help some people understand why they can't debug their Next.js code anymore or why the debug agent suddenly stops from out of nowhere due to the main process restarting the dev server.

### Is there any context that might help us understand?

The PR https://github.com/vercel/next.js/pull/43958 is meant to be helpful, and it is. I just would've appreciated a bit more light on the change of execution model for the next dev server. Some big bold text on the github release page or at least some keyword filled discussion/issue that we can find by google (as I hope this issue might be able to help with)

<sub>[NEXT-493](https://linear.app/vercel/issue/NEXT-493/docs-nextjs-after-1307-dev-server-cluster-worker-restarter-causes-node)</sub>

**Comment by feedthejim** [comment]
Didn't mean to close this sorry!

**Comment by feedthejim** [comment]
I will fix this!

**Comment by michaellopez** [comment]
Much appreciated 👍  @feedthejim
