### ISSUE TITLE
Cannot use 2 font families 

### ISSUE THREAD

**Issue by yousefelgoharyx** [vercel/next.js#44825]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
Binaries:
      Node: 16.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-fonts

### To Reproduce

link to code does not work. it seems stackbiltz does not support next 13 idk.
steps to reproduce:
1) look at the Arabic letters. They should have a different font family

### Describe the Bug

I'm building a bilingual website, Arabic and English so I'm using 2 fonts, one for Arabic letters and the other for English letters but that is not the case. Only one font gets applied and the other gets ignored. I suspect the reason is that Next automatically adds fallback font that always gets applied no matter what.

### Expected Behavior

The correct font should be applied to the Arabic letters

**Comment by valentinpolitov** [comment]
> I suspect the reason is that Next automatically adds fallback font that always gets applied no matter what.

Did you try to turn off automatic fallback? https://nextjs.org/docs/api-reference/next/font#adjustfontfallback

```ts
const poppins = Poppins({
  adjustFontFallback: false,
  variable: "--font-poppins",
  weight: ["400", "700"],
  subsets: ["latin"],
});
```

**Comment by yousefelgoharyx** [comment]
I think that will fix it but this property reduces CLS so I'll be giving up on CLS just for the sake of using two fonts?
Or should I turn it off for the first font and on for the second?
Thanks for your answer tho
