### ISSUE TITLE
Header tags missing when using useSearchParams in layout component in production

### ISSUE THREAD

**Issue by hamza512b** [vercel/next.js#44868]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
    Platform: win32
    Arch: x64
    Version: Windows 10 Pro
  Binaries:
    Node: 18.12.1
    npm: N/A
    Yarn: N/A
    pnpm: N/A
  Relevant packages:
    next: 13.1.2-canary.8
    eslint-config-next: N/A
    react: 18.2.0
    react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/hamza512b/next-13-layout-issue

### To Reproduce

Run `build` command and start the server:
```
npm run build
npm run start
```
open the website on localhost and view the source code html file. It all messed and the header tags are missing.

### Describe the Bug

When adding useSearchParams hook in layout file the html file get messed up. It looks like this. The header tags are missing and nothing is static is appended to the html file.

```html
<!DOCTYPE html>
<html id="__next_error__">
  <head>
    <script
      src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"
      nomodule=""
    ></script>
  </head>
  <body>
    <script
      src="/_next/static/chunks/webpack-8735b88e08106ef9.js"
      async=""
    ></script>
    <script src="/_next/static/chunks/17-863c1e401a8d9d7d.js" async=""></script>
    <script
      src="/_next/static/chunks/main-app-f5f82bea125ee053.js"
      async=""
    ></script>
  </body>
</html>
<script>
  (self.__next_f = self.__next_f || []).push([0]);
</script>
<script>
  self.__next_f.push([1, 'J0:"@1"\n']);
</script>
<!-- More script tags -->
```

### Expected Behavior

When adding useSearchParams hook in layout file, this should not happen instead header tags should be in the page source.

**Comment by GabenGar** [comment]
Yeah, because you are using a [client-side hook](https://beta.nextjs.org/docs/api-reference/use-search-params):
> - During [static rendering](https://beta.nextjs.org/docs/rendering/fundamentals#static-rendering), any component using the `useSearchParams` hook will skip the prerendering step and instead be rendered on the client at runtime.
> - To access search params in [Pages](https://beta.nextjs.org/docs/api-reference/file-conventions/page) (Server Components), use the [`searchParams`](https://beta.nextjs.org/docs/api-reference/file-conventions/page#searchparams-optional) prop.

Not to mention you marked root layout as client-side component, which means the entire app renders client-side only.

**Comment by brandonscript** [comment]
Ahh, super frustrating, been looking for this all day. Thanks for the help. Whipped up this hook to use in place:

``` jsx | tsx

import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import isEqual from "react-fast-compare";

interface UrlEvents {
  routeChanged?: ({
    pathname,
    location,
  }: {
    pathname: string | null;
    location: Location | null;
  }) => void;
}

export const useNavigation = ({ on }: { on?: UrlEvents }) => {
  const pathname = usePathname();
  const [location, setLocation] = useState<Location>();

  const { routeChanged } = on || {};

  useEffect(() => {
    if (pathname && typeof window !== "undefined") {
      window.addEventListener("popstate", () => {
        if (!isEqual(window.location, location)) {
          setLocation(window.location);
          routeChanged?.({
            pathname,
            location: window.location,
          });
        }
      });

      return () => {
        window.removeEventListener("popstate", () => {});
      };
    }
  }, [location, pathname, routeChanged]);

  return location;
};
```

**Comment by nahtnam** [comment]
I would like to add that I'm experiencing the same issue BUT i have `use client` at the top of my component. It looks something like this:

```tsx
'use client'

export function AnalyticsWatcher() {
  const pathname = usePathname()
  const query = useSearchParams()

  useEffect(() => {
    // ...
  }, [pathname, query])

  return (
    <Script id="segment" strategy="worker">
       ...
    </Script>
  )
}
```

but my build outputs a similar `__next_error__` html for the SSG. I would assume the `use client` would stop this from ever rendering on the server

**Comment by timneutkens** [comment]
Posted a reply here: https://github.com/vercel/next.js/issues/45032#issuecomment-1436623497

Here's an example: https://github.com/derrickreimer/fathom-client/issues/44#issuecomment-1436626914

Taking @nahtnam's example:

```jsx
'use client'

function Watcher() {
  const pathname = usePathname()
  const query = useSearchParams()

  useEffect(() => {
    // ...
  }, [pathname, query])
}

export function AnalyticsWatcher() {
  return (
    <>
    <Suspense fallback={null}>
       <Watcher />
    </Suspense>
    <Script id="segment" strategy="worker">
       ...
    </Script>
    </>
  )
}
```

> Not to mention you marked root layout as client-side component, which means the entire app renders client-side only.

Adding `'use client'` to a layout doesn't mean it's client-side rendering. It means the component will be hydrated client-side.
There's a multi-phase process:
- Rendering server components
- Using the rendered server components to render to HTML (this includes rendering the client components)
- Hydrating client-side, only the JS for client components is loaded.

**Comment by GabenGar** [comment]
> Adding 'use client' to a layout doesn't mean it's client-side rendering. It means the component will be hydrated client-side.

This is technically true, but the major reason to make any given component client-only is to derive its state from some browser API with `useEffect()`, so it means it will be server-rendering a stub at best.

**Comment by brandonscript** [comment]
I'm having a hard time connecting the dots between the proposed solution ("warn if using `useSearchParams`) and how that fixes this bug, which affects anything in the document whether client, server, or hybrid. No matter how many chunks you split your code into, if any of them are consuming `useSearchParams`, <head> will be empty. 

Tim, maybe you can help clarify?

**Comment by timneutkens** [comment]
@brandonscript did you see the updated docs here? https://beta.nextjs.org/docs/api-reference/use-search-params#static-rendering. When you don't add a Suspense boundary around the component that calls `useSearchParams` it ends up bubbling up till the root of the application and opt-in to client-rendering there instead of at the Suspense boundary level.
