### ISSUE TITLE
Dynamic routing fails in production v.13.1.2 (Error: invariant: invalid Cache-Control duration provided: 0 < 1)

### ISSUE THREAD

**Issue by lassegit** [vercel/next.js#44860]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 13.1.2
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

///

### To Reproduce

- Install v. 13.1.2
- Add dynamic route (e.g. [slug] folder)
- Build and run it in production mode

Returns the following error: 

```
Error: invariant: invalid Cache-Control duration provided: 0 < 1
    at Object.setRevalidateHeaders (/Users/lasse/Repos/aihelperbot.com/node_modules/next/dist/server/send-payload/revalidate-headers.js:13:19)
    at Object.sendRenderResult (/Users/lasse/Repos/aihelperbot.com/node_modules/next/dist/server/send-payload/index.js:62:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: invariant: invalid Cache-Control duration provided: 0 < 1
    at Object.setRevalidateHeaders (/Users/lasse/Repos/aihelperbot.com/node_modules/next/dist/server/send-payload/revalidate-headers.js:13:19)
    at Object.sendRenderResult (/Users/lasse/Repos/aihelperbot.com/node_modules/next/dist/server/send-payload/index.js:62:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: invariant: invalid Cache-Control duration provided: 0 < 1
    at Object.setRevalidateHeaders (/Users/lasse/Repos/aihelperbot.com/node_modules/next/dist/server/send-payload/revalidate-headers.js:13:19)
    at Object.sendRenderResult (/Users/lasse/Repos/aihelperbot.com/node_modules/next/dist/server/send-payload/index.js:62:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: invariant: invalid Cache-Control duration provided: 0 < 1
    at Object.setRevalidateHeaders (/Users/lasse/Repos/aihelperbot.com/node_modules/next/dist/server/send-payload/revalidate-headers.js:13:19)
    at Object.sendRenderResult (/Users/lasse/Repos/aihelperbot.com/node_modules/next/dist/server/send-payload/index.js:62:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

### Describe the Bug

Returns white screen of death for dynamic routes with the error message: "Internal Server Error".

> I verified that the issue exists in the latest Next.js canary release *

It exist in "stabile" release.

### Expected Behavior

Render dynamic routes without issue.

**Comment by badcc** [comment]
I also began experiencing this with 13.1.2 and came here to find this report

**Comment by DavidTParks** [comment]
Experiencing the same. Can view my repo where it's happening at https://github.com/DavidTParks/vamp

**Comment by homanp** [comment]
> Experiencing the same. Can view my repo where it's happening at https://github.com/DavidTParks/vamp

@DavidTParks did you find a solution to this?

**Comment by dafengzhen** [comment]
> > Experiencing the same. Can view my repo where it's happening at https://github.com/DavidTParks/vamp
> 
> @DavidTParks did you find a solution to this?

you can try to set the revalidate, refer to the document https://beta.nextjs.org/docs/api-reference/segment-config#revalidate

**Comment by homanp** [comment]
> > > Experiencing the same. Can view my repo where it's happening at https://github.com/DavidTParks/vamp
> > 
> > 
> > @DavidTParks did you find a solution to this?
> 
> you can try to set the revalidate, refer to the document https://beta.nextjs.org/docs/api-reference/segment-config#revalidate

That did not help unfortunately.

**Comment by davidthomasparks** [comment]
> > Experiencing the same. Can view my repo where it's happening at https://github.com/DavidTParks/vamp
> 
> 
> 
> @DavidTParks did you find a solution to this?

Had to downgrade to 13.1.1 while a fix is sorted.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.3-canary.5` of Next.js to show a proper error explaining what is occurring better. 

The problem here is that the dynamic path is being statically generated during the build and then dynamic server methods are being used during runtime e.g. `cookies()` or `headers()` from `next/headers`. 

If these are being used in a shared library and the page is meant to be statically generated then `export const dynamic = 'force-static'` can be used to prevent this error or alternatively if the page isn't meant to be statically generated and these methods are needed `export const dynamic = 'force-dynamic'` can be leveraged.

**Comment by switz** [comment]
I see, in my case my root layout was accessing cookies, whereas some individual pages were not themselves, so next detected them as static. I'm going to force dynamic on all pages to solve this for now and may revisit this in the future to balance out static/dynamic pages.

**Comment by lassegit** [comment]
@switz Same issue here. `RootLayout` is utilizing the user `token` and dynamic `headers`, but thought you could still pre-render pages below as `export const dynamic = 'force-static'`?

Anyhow @ijjk thanks for the clarification, means I can update to newer version (lots of improvements and general bug fixes) and fix my errors.

**Comment by xriter** [comment]
I tried adding `export const dynamic = "force-dynamic";` to every layout and page I have, but I am still getting the error `Page changed from static to dynamic at runtime`.
Also during build, some paths are still marked as `○  (Static)`. Is this to be expected?
Any other solutions I can try to fix this?

**Comment by switz** [comment]
> I tried adding `export const dynamic = "force-dynamic";` to every layout and page I have, but I am still getting the error `Page changed from static to dynamic at runtime`. Also during build, some paths are still marked as `○ (Static)`. Is this to be expected? Any other solutions I can try to fix this?

I ran into this. Had to install next stable (13.1.2) and then reinstall next@canary. It was some sort of caching/versioning issue.

**Comment by xriter** [comment]
@switz  I just tried this, but unfortunately the issue persists. :-(

**Comment by ijjk** [comment]
@xriter can you share a repo where you are seeing this after updating to the latest canary?

**Comment by xriter** [comment]
Since this particular Issue has been marked as 'closed' already, a new issue has been posted to request more verbose error logging: https://github.com/vercel/next.js/issues/45068#issuecomment-1399253832

**Comment by xriter** [comment]
@ijjk Reproduce with this project:
https://codesandbox.io/p/sandbox/little-wood-lwwtt7?file=%2Fapp%2Flayout.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A20%7D%5D

Build and then start this project.
Navigate to localhost:3000/projects/123
The error Error: Page changed from static to dynamic at runtime get thrown.
