### ISSUE TITLE
[v13] unknown path after generateStaticParams still calls page component

### ISSUE THREAD

**Issue by y-nk** [vercel/next.js#44957]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.24.3
    Relevant packages:
      next: 13.1.2
      eslint-config-next: 13.1.2
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-lmkayl?file=next.config.js,app/layout.tsx,app/page.tsx,app/%5Bslug%5D/page.tsx

### To Reproduce

1. Create a next project with `appDir` enabled
2. Create a `/app/[slug]/page.tsx` containing:

```tsx
export async function getStaticParams() {
  return [{ slug: 'hello' }]
}

export default function Page({ params }) {
  return <main>
    {JSON.stringify(params)}
  </main>;
}
```

3. Navigate to `http://localhost:3000/not-hello

### Describe the Bug

When creating a page with a route such as "/[slug]/page.tsx", we can leverage `generateStaticParams` to create the list of authorized values of `slug` such as:

```
export async function generateStaticParams(context) {
  return [{ slug: 'hello' }]
}
```

### Expected Behavior

It should use the error.tsx or throw a 404 (if no error.tsx found)

**Comment by Fredkiss3** [comment]
If you want to not allow other pages that the generated ones, you can do : `export dynamicParams = false` at the top of your file.

You can see in the docs : https://beta.nextjs.org/docs/api-reference/segment-config#dynamicparams

**Comment by y-nk** [comment]
@Fredkiss3 thank you. the api is a bit confusing, maybe having a wrapper object rather than 2 separate exports would make more sense. but it solves my issue 🙏

**Comment by y-nk** [comment]
@Fredkiss3 in case you'd be interested, i've checked on the types and it seems there's some mismatch.

https://github.com/vercel/next.js/discussions/41745#discussioncomment-4708038

**Comment by Fredkiss3** [comment]
@y-nk if you use NextJs in VSCode, when you will run the dev server for the first time ( `npm run dev` ) it will ask you to install a typescript plugin, with that you’ll have type hints and docs for the segment config. 

It’s something that the NextJs team worked on and is very nice.

**Comment by y-nk** [comment]
@Fredkiss3 thanks for your answer. i do, i'll try the plugin !

...although to be honest it feels like more code to fix the issue of this api design could have been avoided if the api was just simpler / less fragmented - i could be wrong, this is a small scope of view from a casual consumer :) i can sense this choice will increase complexity of the codebase over time since you'll have vim and intellij people complaining about the lack of plugin too 😓

**Comment by Fredkiss3** [comment]
I suppose if next provided a `PageConfig` type with it and exported an object like they did in api routes, it would be nice. But as far as i know, i think the plugin is a typesript plugin not a vscode one, so i suppose you could install it in command line and run it from intellij and neovim ?

**Comment by y-nk** [comment]
:ah: interesting :) thank you again
