### ISSUE TITLE
Production build call data fetching function twice (server components, app directory)

### ISSUE THREAD

**Issue by havran** [vercel/next.js#44966]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```shell
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 16.19.0
      npm: 9.3.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.3-canary.2
      eslint-config-next: 13.1.2
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/havran/nextjs-13.1.2-called-twice

### To Reproduce

Steps: 

- build
```shell
npm run build
npm run start
```
- click to link and observe console

### Describe the Bug

When I run production build, my data fetching method is called twice (based by observation of console.time method). 
When I run app as dev, this behave as expected, data fetching method is called once.

### Expected Behavior

Data fetching method should be called once with production build.

### How are you deploying your application? (if relevant)

next start

**Comment by Rishab49** [comment]
Do you tried turning off react strict mode in config file 
`js
const nextConfig = {
  reactStrictMode: false
}
`

**Comment by havran** [comment]
> Do you tried turning off react strict mode in config file `const nextConfig = { reactStrictMode: false }`
> 
> refer to the solution of this issue [#35822 (comment)](https://github.com/vercel/next.js/issues/35822#issuecomment-1112067884)

It is not related - we talking about SSR here.

**Comment by havran** [comment]
Tested with canary [v13.1.3-canary.4](https://github.com/vercel/next.js/releases/tag/v13.1.3-canary.4) - same behaviour.

**Comment by javmurillo** [comment]
Same problem here, testing with a simple API which counts the requests. When building, my server receives two API calls instead of one. I tested with and without *cache* hook.
```
// Express API
let counter = 0;
app.get("/hello", (req, res) => {
  counter += 1;
  console.log(counter);
  res.status(200).send({ counter });
});

// Next App
import { cache } from 'react'
const test = cache(async () => fetch(...))

export default async function Page({ params }) {
  const response = test();
  console.log(response);
  return <>Testing</>;
}

// Server output
~/gitProjects/express-hello > node index.js
Example app listening on port 6000
1
2
```

```
Node: 18.13.0
next: 13.1.2
react: 18.2.0
react-dom: 18.2.0
```

I found #36229, maybe HaNdTriX response can be related, but i doubt it, since the request should be cached by default.
Thank you.

**Comment by havran** [comment]
Tested with release v13.1.3 - same behaviour.

**Comment by havran** [comment]
Same issue here https://github.com/vercel/next.js/issues/44655

**Comment by havran** [comment]
Seems like NextJS v13.2.1 solve issue. I still wonder where was problem?

**Comment by lhz516** [comment]
@havran In v13.2.3, the fetching still happens twice when using the page level revalidate.

You can add `export const revalidate = 5;` to your [page.tsx](https://github.com/havran/nextjs-13.1.2-called-twice/blob/main/src/app/%5B%5B...slug%5D%5D/page.tsx), and you can find the fetching happens twice every 5 seconds while you keep refreshing the page.

**Comment by zsrobinson** [comment]
I seem to be having the same issue with v13.3.0 and revalidating using the `next.revalidate` option in the fetch API.

**Comment by joncoronel** [comment]
Yep this is still an issue in the 13.3. When I call on demand revalidation for a route, it runs twice.
