### ISSUE TITLE
After updating Next js from 11 to 13 version, images from assets folder stopped working

### ISSUE THREAD

**Issue by Rozhkow** [vercel/next.js#44963]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.16.0
    Relevant packages:
      next: 13.1.2
      eslint-config-next: 11.0.1
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

private repository

### To Reproduce

-

### Describe the Bug

I've updated NextJs in my application and huge part of images stopped working. I keep my images in asstes folder and after running a project usually all of them are transferred to .next folder, but now only a small part.

My flow:
`
...
import RightLogo from '@/images/about/right_logo.png';

export default function AccountSettingLayout({ children }) { 
    return (
...
                    < Image src={RightLogo} alt='Right logo' />
...
`

The path to the image is correct, but but on the site we just have an alt text.

![image](https://user-images.githubusercontent.com/70947620/212923499-1146ec13-a632-4485-8b41-bf7095f0b36d.png)
![image](https://user-images.githubusercontent.com/70947620/212923568-84d2804a-ebc2-4eed-9428-c01fd9ab3597.png)
![image](https://user-images.githubusercontent.com/70947620/212923590-4334cd32-0d12-4cb6-b19b-b37097fbd21b.png)

I've found a solution, but it's a bit dummy. If I'll keep all the images in public folder, and will indicate the path to the image as here:

`<Image 
  src="/about/right_logo.png" 
  alt='Right logo'
  width={200}
  height={500} 
/>`

### Expected Behavior

Return expected behaviour of images

### Which browser are you using? (if relevant)

Chrome 

### How are you deploying your application? (if relevant)

yarn next dev

**Comment by Rishab49** [comment]
can you show your file structure in root directory.

**Comment by ijjk** [comment]
Hi, it looks like you aren't leveraging `next/image` and have a custom `Image` component instead as the imported image returns an object with additional context that `next/image` consumes but a normal image tag does not. 

If you would like to not leverage the built-in image import handling it can be disabled via:

```js
// next.config.js

module.exports = {
  images: {
    disableStaticImages: true
  }
}
```

**Comment by Rozhkow** [comment]
Sorry, probably I've explained my issue not such correct. 

Earlier (on version 11 next) when starting the project, all images in the assets/images folder were transferred to the .next/static/media folder, now (when updating to version 13) only fonts and a few images are saved in this folder

My question is: what could be the reason for this and how to return the old behavior, in which, at running project, all images are statically stored in next//static/media

**Comment by Rozhkow** [comment]
> Hi, it looks like you aren't leveraging `next/image` and have a custom `Image` component instead as the imported image returns an object with additional context that `next/image` consumes but a normal image tag does not.
> 
> If you would like to not leverage the built-in image import handling it can be disabled via:
> 
> ```js
> // next.config.js
> 
> module.exports = {
>   images: {
>     disableStaticImages: true
>   }
> }
> ```

Sorry, probably I've explained my issue not such correct.

Earlier (on version 11 next) when starting the project, all images in the assets/images folder were transferred to the .next/static/media folder, now (when updating to version 13) only fonts and a few images are saved in this folder

My question is: what could be the reason for this and how to return the old behavior, in which, at running project, all images are statically stored in next//static/media
