### ISSUE TITLE
`next dev` does not compile page as of Next 13.0.3-canary.4

### ISSUE THREAD

**Issue by markerikson** [vercel/next.js#44976]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Windows:

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.11.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.3-canary.2
      eslint-config-next: N/A
      react: 0.0.0-experimental-e7d0053e6-20220325
      react-dom: 0.0.0-experimental-e7d0053e6-20220325

Linux:

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 3.2.1
      pnpm: N/A
    Relevant packages:
      next: 13.1.3-canary.2
      eslint-config-next: N/A
      react: 0.0.0-experimental-e7d0053e6-20220325
      react-dom: 0.0.0-experimental-e7d0053e6-20220325

### Link to the code that reproduces this issue

https://github.com/replayio/devtools/tree/feature/FE-1124-next-13-upgrade

### To Reproduce

1. Clone the Replay.io DevTools repo at https://github.com/replayio/devtools
2. Check out branch `feature/FE-1124-next-13-upgrade`
3. Run `yarn` to install all deps
4. Run `yarn dev` to start the dev server
5. Browse to http://localhost:8080/recording/reduxts-csb-2--be1a4568-6c84-474c-a9eb-3a0491a792d8 , which will attempt to compile page `/recording/[[...id]]`
6. Observe that it does not finish compiling. There are no further progress updates.

Confirmed that this happens on both Windows and WSL Linux.

### Describe the Bug

The Replay.io DevTools repo is currently on Next 12.1, and still uses Babel to do our JS compilation, as we had seen issues with Next+SWC sourcemaps (previously filed as #39878 ).

I attempted to upgrade our repo to Next 13.1.2 to see if the sourcemap issues were resolved.  After installing 13.1.2, `yarn build` succeeded with Next configured to use either Babel or SWC for JS compilation.  (Repo uses Babel by default because we have a `.babelrc` file.  Renaming that to `.babelrc.bak` switches to SWC.)

However, when I tried to run `yarn dev` and load a page, Next started compiling our `/recording/[[...id]]` page, and never progressed further.

I bisected Next releases and confirmed that this behavior started with Next 13.0.3-canary.4.  `yarn dev` runs okay with 13.0.3-canary.3, but the same freezing happens with 13.0.3-canary.4.

Looking at https://github.com/vercel/next.js/releases/tag/v13.0.3-canary.4 , the potentially relevant PRs could likely be:

- #42741
- #42767
- #42733

### Expected Behavior

`yarn dev` would successfully compile the page as usual

### Which browser are you using? (if relevant)

Chrome 108, but not relevant

### How are you deploying your application? (if relevant)

Local dev

**Comment by ijjk** [comment]
Hi, thanks for the detailed reproduction! Opened a patch for this here https://github.com/vercel/next.js/pull/44986 will update this thread when it's available on canary.

**Comment by markerikson** [comment]
Hah, if it was telemetry, guess it must have been this PR that was the issue instead :)

- #42766

**Comment by ijjk** [comment]
Yeah that change surfaced it in initial compilation with yarn `v3`. The above patch is now available in `v13.1.3-canary.4` of Next.js, please update and give it a try!

**Comment by markerikson** [comment]
Awesome! I'm done for the day, but I'll give it another shot tomorrow.

**Comment by markerikson** [comment]
Okay, confirmed that 13.1.3-canary.4 fixes the issue - thanks!

**Comment by ijjk** [comment]
Great, thanks for confirming! 🚀
