### ISSUE TITLE
Next.js 12.0.2 causes memory leak after upgrading from Next 12.0.1

### ISSUE THREAD

**Issue by dev-cutshort** [vercel/next.js#44973]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information
We are running a docker container inside AWS ECS.

### Link to the code that reproduces this issue

N/A

### To Reproduce

Unable to reproduce with fresh Next.js setup, likely because we are using an enterprise app and there are a lot of third party packages involved.

I can only assume that the server is crashing due to memory size. 
In our enterprise app, we are able to see the crashes periodically after 2-3 hours. 

### Describe the Bug

We switched to Next.js v12.2.0 to use the keepAliveTimeout feature. But we started seeing 502 bad gateway errors and when examined the logs we found that the app crashes with SIGABRT.
Following are the logs from AWS Cloudwatch 
` FATAL ERROR: v8::FromJust Maybe value is Nothing.`
`error Command failed with signal "SIGABRT".`

### Expected Behavior

App is expected to NOT crash

### How are you deploying your application? (if relevant)

next start

**Comment by ijjk** [comment]
Hi, please update to the latest version of Next.js v13 as v12 is missing a lot of updates! If you are still seeing issues with this in latest version we would be happy to investigate further!
