### ISSUE TITLE
When closing `yarn dev` in VS Code, new console windows pop up

### ISSUE THREAD

**Issue by marktoman** [vercel/next.js#44992]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

The module 'react' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react'
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react-dom'

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.2
      eslint-config-next: N/A
      react: N/A
      react-dom: N/A

warn  - Latest canary version not detected, detected: "13.1.2", newest: "13.1.3-canary.4".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Link to the code that reproduces this issue

See below

### To Reproduce

1. `npx create-next-app -e reproduction-template bug`
2. `code bug`
3. In the VSCode terminal, `yarn dev`
4. Wait for the server to start
5. Press ctrl + c

### What happens
One (or more if 13.1.3-canary.4) console windows pop up and immediately close. The window contained [messages](https://user-images.githubusercontent.com/47689923/213086905-bddd5b8b-4fcc-489a-bd42-18e068c3e722.png).

### Why it matters
The console immediately closes, so the messages cannot be read. But mainly, the console popping up and immediately closing is indescribably disturbing for such a regular task.

### Expected Behavior

The process closes with all messages printed in the VS Code terminal with no external console window showing.

**Comment by xsmithdev** [comment]
Same here, very annoying as I have to refocus on vscode before I can continue using the terminal

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.3-canary.5` of Next.js, please update and give it a try!
