### ISSUE TITLE
[appdir] [next 13.1.2] build crashes because routes are prerendered with fake data in dynamic segments

### ISSUE THREAD

**Issue by raphaelbadia** [vercel/next.js#45006]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

$ /private/tmp/reproduction-app/node_modules/.bin/next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 9.1.2
      Yarn: 1.22.19
      pnpm: 7.23.0
    Relevant packages:
      next: 13.1.3-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

✨  Done in 2.42s.

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/tree/canary/examples/reproduction-template

### To Reproduce

Hello, 

I upgraded from next 13.0.6 to next@13.1.2 yesterday and since then I cannot build anymore my project. Digging into the issue   showed my that the pages with dynamic segments are now prerendered at build time with the dynamic segment name as a string.

To reproduce, simply clone and install my reproduction link, then run `yarn build`.

The build will fail.

### Describe the Bug

When building, next will try to render the page with the param as an argument. For instance, it will prerender `app/[todoId]/page.tsx` with the params `{todoId: "[todoId]"}`.

I tried using `export const dynamic = 'force-dynamic';` but it doesn't change anything.

### Expected Behavior

Like in 13.1.1, it shouldn't fail the build.

**Comment by RemVN** [comment]
The repository you provided is a default template. There may be a mistake here. Can you please edit the correct repository link?

**Comment by bogh** [comment]
I am also experiencing this. I have a page with a dynamic path in app dir `app/[locale]/page.tsx`
Doing `yarn build` would crash with a prerendering error.

**Comment by ijjk** [comment]
Hi, `export const dynamic = 'force-dynamic'` not being honored has been corrected in the latest canary of Next.js `v13.1.3-canary.5`. Note, it is expected that the page attempts being prerendered if this isn't present and `generateStaticParams` isn't present as otherwise we aren't able to analyze whether the path is static or dynamic during build.
