### ISSUE TITLE
[NEXT-685] Page navigation & caching with search params is broken in 13.1.2 production (work in dev)

### ISSUE THREAD

**Issue by njarraud** [vercel/next.js#45026]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:36:28 PST 2022; root:xnu-8019.80.24~21/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.0.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.3-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-phyu1x

### To Reproduce

in the terminal: `npm install && npx next build` then `npx next start`

In the browser:
1. Go to url `/1?page=1`
2. Click `next page` multiple times

### Describe the Bug

The first time the page `/1?page=1` is open, the server log will read `server page: 1` twice. Then if you click the link `next page`, the correct url `/1?page=2` is displayed in the address bar but the html page content remains on page 1. If you click again on `next page` nothing happens anymore. Besides even hard reloading the page (even with a different page param) will still serve the content of page 1 (the first ever called).

### Expected Behavior

When page `/1?page=1` is open, the server log shall read `server page: 1`.
Then on subsequent clicks `server page: 2`, `server page: 3`, etc. and the html content shall reflect that.
It is the case in 13.1.1 but not from 13.1.2 in production mode.

### How are you deploying your application? (if relevant)

next start

<sub>[NEXT-685](https://linear.app/vercel/issue/NEXT-685/page-navigation-and-caching-with-search-params-is-broken-in-1312)</sub>

**Comment by njarraud** [comment]
Adding `export const dynamic = 'force-dynamic'` to pages using `searchParams` seems to be the solution with latest versions of Next.

**Comment by bpossolo** [comment]
I've noticed similar behavior on 13.1.1 when navigating using the browser's back/forward button on a page with search/query params.

the pagination buttons (which trigger a route change using next/navigation `router.push()` function correctly.
but when attempting to move backwards/forwards in the history using the browser's back/forward buttons, the url changes but the dom content does not.

it's almost like the query params are not being taken into consideration when computing the in-browser cache key for the route.

**Comment by jrazmi** [comment]
Has anyone found newer releases of Next to have addressed this?  I've tried 13.1.4 and just updated to 13.1.6 and am still seeing this behavior.  Even using `export const dynamic = 'force-dynamic'` doesn't seem to resolve the issue.

**Comment by mikkelwf** [comment]
Any update on this?

**Comment by bpossolo** [comment]
omg im so excited to see if this working now!
this was one of the biggest roadblocks to releasing my new nextjs app dir based app to the world 🎉
