### ISSUE TITLE
Loading.js not working on nested segment with dynamic params

### ISSUE THREAD

**Issue by focux** [vercel/next.js#45021]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.2
      npm: 9.3.0
      Yarn: 1.22.19
      pnpm: 7.24.3
    Relevant packages:
      next: 13.1.3-canary.4
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-wb2thv?file=app/(main)/page.tsx

### To Reproduce

1. Click on the "Users" menu
2. Click on a user
3. The `loading.js` component of the parent segment is not shown.

### Describe the Bug

When you navigate to a nested dynamic segment, for instance, `/users/[userId]` and you have a `Loading.js` component on a parent segment (the loading component is on `/` segment), it doesn't show it when the page is loading.

### Expected Behavior

I expect the parent loading component to be shown when the page is loading.

**Comment by austinyearlykim** [comment]
I am seeing this issue as well.  My project setup looks like:

App/[profile]/[post]/loading.js
App/[profile]/[post]/page.js

The loading.js file in my root folder works properly when the root of my project is requested, but loading.js does not work for any subdirectories if they're dynamic.

**Comment by JanKaifer** [comment]
That is expected. You should add `loading.tsx` into a `/users/` if you want loading state there.

**Comment by focux** [comment]
@JanKaifer That is so unintuitive, I would expect the loading to fallback to the closest suspense boundary, in this case that is the loading on the parent segment.
