### ISSUE TITLE
[NEXT-690] `@next/font` does not respect `https_proxy` environment variable

### ISSUE THREAD

**Issue by tom-h10** [vercel/next.js#45034]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.12.1
  npm: 9.2.0
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.1.2
  eslint-config-next: 13.1.2
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (@next/font)

### Link to the code that reproduces this issue

N/A

### To Reproduce

1. `npx create-next-app`
2. An app including `@next/font` will be created
3. `npm run dev` behind a corporate proxy (with `https_proxy` environment variable)
4. Access to http://localhost:3000/

### Describe the Bug

Failed to fetch the font.

Dev server output:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 6.6s (165 modules)
wait  - compiling / (client and server)...
Error [NextFontError]: Failed to fetch `Inter` from Google Fonts.
    at nextFontError (...\node_modules\@next\font\dist\utils.js:55:17)
    at downloadGoogleFonts (...\node_modules\@next\font\dist\google\loader.js:87:39)   
    at ...\node_modules\next\dist\build\webpack\loaders\next-font-loader\index.js:52:99
    at async Span.traceAsyncFn (...\node_modules\next\dist\trace\trace.js:79:20)       
error - Failed to download `Inter` from Google Fonts. Using fallback font instead.
event - compiled client and server successfully in 1023 ms (194 modules)
```

### Expected Behavior

Respect the `https_proxy` environment variable, and the font should be successfully retrieved.

<sub>[NEXT-690](https://linear.app/vercel/issue/NEXT-690/nextfont-does-not-respect-https-proxy-environment-variable)</sub>

**Comment by xgqfrms** [comment]
This is a very unfriendly developer experience for beginners of Next.js.
