### ISSUE TITLE
Prerendering of pages with generateStaticParams is skipped when useSearchParams is used in children 

### ISSUE THREAD

**Issue by njarraud** [vercel/next.js#45032]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:36:28 PST 2022; root:xnu-8019.80.24~21/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.0.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 12.3.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/wispy-frost-i878rg

### To Reproduce

Check the html source code of the home page when `<SearchParamComponent />` is a child component or not.
You can also comment/uncomment the `generateStaticParams` function.

### Describe the Bug

The documentation states that 

**During [static rendering](https://beta.nextjs.org/docs/rendering/fundamentals#static-rendering), any component using the useSearchParams hook will skip the prerendering step and instead be rendered on the client at runtime.**

From my observations:
- if the page does not use `generateStaticParams`, the component is prerendered and `searchParams.get` returns undefined in the html source code. (better than what the documentation states).
- if the page uses `generateStaticParams` and has a component using `useSearchParams` anywhere in the tree, prerendering is skipped for the page all together! (worse than the documentation ).

useSearchParams becomes pretty much useless as things like SEO falls apart with an empty html tag even if a tiny component somewhere down the tree uses this hook.

I also noticed that the html tag attribute becomes `<html id="__next_error__">` instead of `<html lang="en">` as defined in the root layout file.

### Expected Behavior

The use of `useSearchParams` somewhere shall not make the whole page skip prerendering.

### How are you deploying your application? (if relevant)

next start

**Comment by Hooman-studio** [comment]
I am having this problem as well, I only notice it when disabling javascript in my browser. It doesn't render anything except the `<html id="__next_error__">` and script tags.

**Comment by njarraud** [comment]
Yes, unfortunately it looks like that with the latest versions of Next, I have this issue with all pre-rendered pages. Only pages marked with `export const dynamic = 'force-dynamic'` have the proper html content as they are not cached on the server.

**Comment by hamza512b** [comment]
#44868

**Comment by desire** [comment]
@timneutkens i am also having this issue! seems like if you use the `useSearchParams` hook anywhere it prevents static generation for that page. 

https://github.com/derrickreimer/fathom-client/issues/44

this explains the issue very well

**Comment by timneutkens** [comment]
I've updated the documentation to explain why `useSearchParams` enables client-side rendering below the Suspense boundary: https://beta.nextjs.org/docs/api-reference/use-search-params#static-rendering

When there's no Suspense boundary the whole page ends up deopting, which will cause a warning soon: #46141.

Wrote a bit more on how this compares to `router.isReady` here: https://twitter.com/timneutkens/status/1627593203074445313
