### ISSUE TITLE
Next.js 13 app directory with enabled trailing slash client side routing does not work

### ISSUE THREAD

**Issue by lnikell** [vercel/next.js#45062]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.1.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

n/a

### To Reproduce

1. Create new Next.js 13 app
2. Enable trailingSlash: true option in config
3. Create few pages and use next/link from a home page to them
4. Deploy to Vercel
5. You will see 404 responses on prefetch requests

### Describe the Bug

Client-side routing does not work with enabled trailingSlash: true config due to 404 prefetch requests.
https://neon-next-jo772cn40-neondatabase.vercel.app/
<img width="520" alt="screenshot-2023-01-19-21-34-52@2x" src="https://user-images.githubusercontent.com/2697570/213553961-9355547f-26e0-44b0-aaff-060667c07edd.png">

### Expected Behavior

When you set trailingSlash: false everything works perfectly.
https://neon-next-6ftgjmj7r-neondatabase.vercel.app/

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by lnikell** [comment]
The same happens on another project with Next.js 13 but with "pages" directory.

**Comment by ijjk** [comment]
@lnikell can you share a reproduction with the project using pages directory that is 404ing with `trailingSlash: true`? `pages` doesn't make requests to those paths and instead uses the `_next/data` variant which shouldn't be affected, we also have existing test coverage for `pages` with `trailingSlash: true`.

**Comment by lnikell** [comment]
@ijjk It feels like on another site, it's a little bit story, so I will update you after the investigation if it appears to be the same problem at the end. Thanks a lot for a very quick fix! 🔥 That was super fast!

**Comment by ijjk** [comment]
The above patch has now been released, please re-deploy your project for the fix to be applied!
