### ISSUE TITLE
Page changed from static to dynamic at runtime, but totally unclear where or why

### ISSUE THREAD

**Issue by xriter** [vercel/next.js#45068]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.3-canary.5
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue
https://codesandbox.io/p/sandbox/little-wood-lwwtt7?file=%2Fapp%2Flayout.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A20%7D%5D

### To Reproduce
Build and then start this project.
Navigate to localhost:3000/projects/123
The error Error: Page changed from static to dynamic at runtime get thrown.

### Describe the Bug

Even after making every component `use client` and adding `export const dynamic = "force-dynamic";` to every layout and page, still `Error: Page changed from static to dynamic at runtime` shows up, failing to render the page.

However, it is totally unclear what code or file is causing this problem. In big projects it will be search for a needle in a haystack to find the issue...

### Expected Behavior

It would be nice if the error log would contain more information about where or why this problem shows up. What line or file causes this error message to show up.

**Comment by switz** [comment]
I saw this happen to me because I was using `generateStaticParams` on a page but my root layout was forcing every page to be dynamic. I disabled `generateStaticParams` for the time being, as I access `cookies` in my root layout so every page must be dynamic.

**Comment by alexis78i** [comment]
[To Reproduce](https://github.com/alexis78i/nextjs-issue-45068) try to build the project, the dynamic page dynamic/[slug]/page.js becomes static.

<img width="1189" alt="Screenshot 2023-01-21 at 13 40 10" src="https://user-images.githubusercontent.com/15069001/213869470-7bf4a880-6a76-489b-96b2-43e0802813b6.png">

**Comment by xriter** [comment]
Reproduce with this project:
https://codesandbox.io/p/sandbox/little-wood-lwwtt7?file=%2Fapp%2Flayout.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A20%7D%5D

Build and then start this project.
Navigate to localhost:3000/projects/123
The error `Error: Page changed from static to dynamic at runtime` get thrown.

**Comment by xriter** [comment]
Seems to be related to this issue: https://github.com/vercel/next.js/issues/45134

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.6-canary.0` of Next.js, please update and give it a try!

**Comment by xriter** [comment]
@ijjk This update seems to have solved the problem :-)
