### ISSUE TITLE
Docs: The mdx-as-server-component is not supported on webpack4

### ISSUE THREAD

**Issue by ktanoooo** [vercel/next.js#45086]
### What is the improvement or update you wish to see?

The following new feature adds alias when using mdx.
https://github.com/vercel/next.js/pull/44651

It is supported for arrays in alias on webpack5, but webpack4 is not.
I think this is confusing. So I think should be added on the documentation about it required webpack5, what do you think about?

### Is there any context that might help us understand?

The added alias
https://github.com/vercel/next.js/pull/44651/files#diff-bdcc8e0f4068c2d8bc8f1225c9776f3ec581e79a457abe748a053148925610d1R24-R27

webpack
https://github.com/webpack/enhanced-resolve/releases/tag/v5.0.0-beta.0
> add support for arrays in alias

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/advanced-features/using-mdx

**Comment by balazsorban44** [comment]
Webpack 4 has been removed since Next.js 12, see https://nextjs.org/blog/next-12#breaking-changes

The new app directory (RSC) requires Next.js 13
