### ISSUE TITLE
next 13.1.3 no longer displays localhost but a random host as url when ran with docker

### ISSUE THREAD

**Issue by thdk** [vercel/next.js#45097]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023
    Binaries:
      Node: 18.9.0
      npm: 8.19.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.4-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

with-docker

### Describe the Bug

When launching nextjs 13.1.3 seems to use a random host when started from docker.

```sh
docker run --rm --publish 3000:3000 next          
Listening on port 3000 url: http://05c54daa24ce:3000
```
Note that opening http://localhost:3000 in the browser works and show the next app.

### Expected Behavior

Running the with-docker example should print `url:http:localhost:3000` on the terminal
```sh
Listening on port 3000 url: http://localhost:3000
```

### To Reproduce

- Go to examples/with-docker
- run `yarn install` (otherwise you are missing a lock file and docker build will throw)
- (verify if installed next version is >= 13.1.3 in node_modules folder)
- run `docker build -t next .`
- run `docker run --rm -p 3000:3000 next`

**Comment by ijjk** [comment]
This is picking up the `HOSTNAME` env docker is setting, it can be overridden to `localhost` by setting `HOSTNAME=localhost` instead if desired. I don't think we should special case and override in Next.js itself though as we can't tell if it was intentional or not.
