### ISSUE TITLE
[NEXT-447] [13.0.7+] Issues caused by "temporary" clusterization on development environment

### ISSUE THREAD

**Issue by developerdavi** [vercel/next.js#45122]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

**Operating System:**
Platform: darwin
Arch: arm64
Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000

**Binaries:**
Node: 16.17.0
npm: 8.15.0
Yarn: 1.22.19
pnpm: 7.25.1

**Relevant packages:**
next: 13.1.4-canary.1
eslint-config-next: 13.1.2
react: 18.2.0
react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

https://codesandbox.io/s/bold-waterfall-xg2qog?file=/pages/api/bug.ts

### To Reproduce

Run the app and access `/api/bug.ts` in 2 different ways.

1. Just let it run by default (`yarn dev`)
2. Run with the env variable `__NEXT_DISABLE_MEMORY_WATCHER` set to something truthy (or `yarn dev:nocluster`)

### Describe the Bug

Since v13.0.7 (or more specifically, since #43958) if the app is started using the `next dev` command, the server by default will do some kind of process orchestrating to stop and resurrect the process if it exceeds an amount of used memory.

The issue is that the use of `cluster.fork()` is a breaking change for some projects as they may depend on the value of `cluster` properties such as `cluster.isMaster` (or `cluster.isPrimary`).

I noticed that issue because `log4js` wasn't logging in development environment and was working fine on production builds. Initially I thought that it was actually some kind of problem with `stdout` routing between the child processes and the main one, but actually I noticed that `log4js` depends on `cluster` properties to listen to log events and work fine even if you are clustering your app (e.g using PM2). But actually `log4js` wasn't actually performing `process.stdout.write` because the "main" process (in the case, an API route) wasn't actually the master process.

Turns out that disabling that behavior either from log4js using the `disableClustering` parameter or using the `__NEXT_DISABLE_MEMORY_WATCHER` env variable the problem disappears (in the first case because it will assume you aren't using clusters and consider that it should always write into `stdout`, and in the second case due to disabling the next-dev clusterization).

It was hard to find the cause of issue, but luckily I have other project using next + log4js and I tested some versions and found it. Shouldn't it be better documented or even this "temporary solution" removed?

### Expected Behavior

The app should work as a main process (master/primary).

<sub>[NEXT-447](https://linear.app/vercel/issue/NEXT-447/[1307]-issues-caused-by-temporary-clusterization-on-development)</sub>

**Comment by feedthejim** [comment]
@developerdavi thank you for opening the issue! That's a big problem indeed. I think I might be able to change the implementation to just use workers instead cluster and that should be sufficient enough.

Interesting though that using cluster in one library basically stops users from using it in one another.
