### ISSUE TITLE
Next >=3.1.2 routes with [dynamicProperty] are seen as static instead of dynamic

### ISSUE THREAD

**Issue by xriter** [vercel/next.js#45134]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.4
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/little-wood-lwwtt7?file=%2Fapp%2Flayout.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A20%7D%5D

### To Reproduce

Build and then start this project.
Navigate to localhost:3000/projects/123
The error `Error: Page changed from static to dynamic at runtime` get thrown.

### Describe the Bug

In next version <= 3.1.1 when building a project, routes that contain a dynamic property, where seen as 'dynamic'.

```
Route (app)  
├ λ /project/[projectId]

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```
However, in version 3.1.2 and above, some of them started being seen as static, despite containing `export const dynamic = "force-dynamic";`
```
Route (app)  
├ ○ /project/[projectId]

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

Then when running the site, this error starts popping up: `Error: Page changed from static to dynamic at runtime`

Is seems like this happens because a parent layout contains `'use client' ` (because it has some interactive buttons).

### Expected Behavior

Routes with a dynamic property should be seen as 'dynamic' during build, instead of 'static'.

```
Route (app) 

should be:
λ /project/[projectId]

but is:
○ /project/[projectId]

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
```

**Comment by panthony** [comment]
Same here, all pages with dynamic segment ended as "static" and I had the following errors:

https://github.com/vercel/next.js/issues/44860

Reverting back to 3.1.1 fixed the issue.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.1.6-canary.0` of Next.js, please update and give it a try!

**Comment by xriter** [comment]
@ijjk This update seems to have solved the problem :-)
