### ISSUE TITLE
NextResponse.redirect crash page

### ISSUE THREAD

**Issue by ilchenkoArtem** [vercel/next.js#45138]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

   Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 13.1.4
      eslint-config-next: 13.1.4
      react: 18.2.0
      react-dom: 18.2.0

### Which example does this report relate to?

https://nextjs.org/docs/advanced-features/middleware#conditional-statements

### What browser are you using? (if relevant)

Google Chrome

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

I created middleware for redirects:

```ts
import {NextResponse} from 'next/server'
import type {NextRequest} from 'next/server'

export function middleware(request: NextRequest) {
  const isNextFile = request.nextUrl.pathname.startsWith('_next');
  if (isNextFile) return NextResponse.next()

  const isPublic = request.nextUrl.pathname.startsWith('/sign-in');
  const isAuthorized = request.cookies.get('auth');

  if (isPublic && isAuthorized) {
    return NextResponse.redirect(new URL('/my-profile', request.url));
  }

  if (!isPublic && !isAuthorized) {
    return NextResponse.redirect(new URL('/sign-in', request.url));
  }

  return NextResponse.next()
}
```

When I go to not public page (/sign-in) and my app doesn't have auth cookie my page crash with error
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/33321841/213894699-d6fcba4e-ea16-4b68-84f1-62f06817b30b.png">

### Expected Behavior

Page should show correct without error

### To Reproduce

1. Create middlwear
```ts
import {NextResponse} from 'next/server'
import type {NextRequest} from 'next/server'

export function middleware(request: NextRequest) {
  const isNextFile = request.nextUrl.pathname.startsWith('_next');
  if (isNextFile) return NextResponse.next()

  const isPublic = request.nextUrl.pathname.startsWith('/sign-in');
  const isAuthorized = request.cookies.get('auth');

  if (isPublic && isAuthorized) {
    return NextResponse.redirect(new URL('/my-profile', request.url));
  }

  if (!isPublic && !isAuthorized) {
    return NextResponse.redirect(new URL('/sign-in', request.url));
  }

  return NextResponse.next()
}
```

2. Add page sign-in
3. Add page my-profile
3. Got to the /sign-in route
4. See error in console

**Comment by ilchenkoArtem** [comment]
It fixed my problem: 

```ts
export const config = {
  matcher: [
    '/((?!_next).*)(.+)'
  ],
}
```

But it is not clear

**Comment by FauricioValencia** [comment]
same error here

**Comment by fabianrod** [comment]
Same error here

**Comment by balazsorban44** [comment]
Middleware is run in front of all requests, and redirecting `_next` requests will actually break the import of those .js files shown in the console.

You can avoid this by telling Middleware to not run the redirect on the `_next` directory by adding the matcher, which is documented here: https://nextjs.org/docs/advanced-features/middleware#matcher
