### ISSUE TITLE
Unable to run `npm run build` due to `Error: ENOENT: no such file or directory`

### ISSUE THREAD

**Issue by sgrobert** [vercel/next.js#45159]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

`next info`

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.17.1
      npm: 9.2.0
      Yarn: 1.22.19
      pnpm: 7.22.0
    Relevant packages:
      next: 13.1.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

---

`package.json`
- "@next/font": "^13.1.4",
- **"next": "^13.1.5-canary.2"**,

---

`next.config.js`
```
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  experimental: {
    appDir: true,
  },
  staticPageGenerationTimeout: 1000,
}

module.exports = nextConfig

```

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-ubvjrc?file=app%2Flayout.jsx,next.config.js

### To Reproduce

1. Run `npm install`
2. Run `npm run build`

---

`Sample Execution In StackBlitz`:

![Screenshot 2023-01-23 at 7 49 24 AM](https://user-images.githubusercontent.com/759805/213947157-0d4eb338-61b9-4a62-b433-7450f666b77d.png)

### Describe the Bug

While attempting to run the command `npm run build`, the following error message pops up:
```
...

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Linting and checking validity of types  
info  - Collecting page data  
info  - Generating static pages (24/24)

> Build error occurred
[Error: ENOENT: no such file or directory, rename '/Users/.../.next/export/404.html' -> '/Users/.../.next/server/pages/404.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/Users/.../.next/export/404.html',
  dest: '/Users/.../.next/server/pages/404.html'
}
info  - Finalizing page optimization .%      

END OF `npm run build`.

```

---

I tried the following multiple solutions in an attempt to resolve the issue, but the error still occurs:
**[1] Moved Affected Files Out To Temp Folder `/app-backup` Instead of Keeping Under `/app`**
- (a) Moved `/app/(error-pages)/404/page.jsx` to `/app-backup/404/page.jsx`
- (b) Error is thrown for the next file instead for `/app/(error-pages)/500/page.jsx`
- (c) The same thing happened when I attempted to move the same file for `/app/(error-pages)/500/page.jsx`
- (d) The same issue repeats for other files when [1c] was moved.

**[2] Reinstalled Node Packages**
- Based on Stackoverflow: https://stackoverflow.com/questions/69295639/next-build-issue-with-file-names
- (a) Deleted `package-lock.json`
- (b) Reinstalled `node_modules` via `npm install`
- (c) Same problem arises when running `npm run build`
- (d) Followed up with secondary instructions via: https://stackoverflow.com/questions/49651221/npm-enoent-no-such-file-or-directory-rename
- (e) Verified npm cache via `npm cache verify`
- (f) Ran thru [2a] -> [2c]. Same results
- (g) Tried cleaning the cache via `npm cache clean`
- (h) Ran thru [2a] -> [2c]. Same results

**[3] Added staticPageGenerationTimeout To `next.config.js`**
- Based on nextjs.org documentation: _Static page generation timed out after multiple attempts_: https://nextjs.org/docs/messages/static-page-generation-timeout
- Injected `staticPageGenerationTimeout: 1000,` within `next.config.js`
- Ran thru [2a] -> [2c]. Same results

**[4] Attempted Alternative Solutions via NextJS's Issues Docs**
- Based on NextJS's GitHub Issues: (i) https://github.com/vercel/next.js/issues/44442
- Based on NextJS's GitHub Issues: (ii) https://github.com/vercel/next.js/issues/44120
- (a) Tried temporary fix suggestion from https://github.com/vercel/next.js/issues/44120#issuecomment-1364732323
- (b) Ran thru [2a] -> [2c]. Same results

**[5] Updated NextJs to the Latest Canary Version**
- (a) Updated from `"next": "^13.1.4"` to `"next": "^13.1.5-canary.2"`
- (b) Ran thru [2a] -> [2c]. Same results

### Expected Behavior

The `npm run build` process should complete as per normal, especially when all relevant bugs are fixed, which will signal to me that the build will run safely on a server-execution. 

### Which browser are you using? (if relevant)

Brave Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Localhost Only, running `npm run build`, which executes `next build`.

**Comment by balazsorban44** [comment]
Your repro gives a 404, could you fix? Are you trying to use `next export` by chance? It is not yet supported with the app directory as per https://beta.nextjs.org/docs/app-directory-roadmap#supported-and-planned-features

**Comment by sgrobert** [comment]
Hi @balazsorban44 ,

My apologies... I've just rechecked the link and here is the working link in incognito:

https://stackblitz.com/edit/vercel-next-js-pchf6t?file=next.config.js


![Screenshot 2023-01-23 at 10 09 05 PM](https://user-images.githubusercontent.com/759805/214060153-7d43ecdc-e8ea-4b70-9465-680e244ff978.png)

**Comment by kfirfitousi** [comment]
It seems like you can't have routes like `/404` and `/500` in the app directory. Changing them to `/e404` and `/e500` solved the problem.  
You should be using a `not-found.tsx` file for dealing with 404 errors: https://beta.nextjs.org/docs/api-reference/notfound

**Comment by sgrobert** [comment]
Hi @kfirfitousi ,

Thanks for the clarification. Just pulled the folders out of `/app` and it does seem to work. 

May I check with you let's say if `/404` is handled by `not-found.tsx` in NextJS 13, and for other `5XX` errors I can just rename the files, would you happen to know what about those other `4XX` custom client-side files such as `/401` or `/403`, should I just rename to a `/403-error` page or are there other default files that will be used by NextJS 13 to replace such files like `not-found.tsx`?

Thank you!

**Comment by kfirfitousi** [comment]
You can use the `error.tsx` file for error handling.
Here is a basic example:

```tsx
// app/error.tsx
'use client';

export default function Error({
  error,
  reset,
}: {
  error: Error;
  reset: () => void;
}) {
  return (
    <html>
      <head></head>
      <body>
        <h2>Something went wrong!</h2>
        <h3>{error.message}</h3>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  );
}
```

And then in a page/component any error thrown will be caught:

```tsx
// app/page.tsx
export default async function Home() {
  await fetch('some-non-existent-url'); 
  // ^ will throw Error with message: "Failed to parse URL from some-non-existent-url"
  return <h1>Home</h1>;
}
```

Which will render the Error component like so:
![image](https://user-images.githubusercontent.com/37262772/214248654-f480c1f4-6bfc-4240-ab9d-17ce941805e1.png)

You can also wrap the error-producing code with a try-catch block to throw a custom error:

```tsx
// app/page.tsx
export default async function Home() {
  try {
    await fetch('some-non-existent-url');
  } catch (e) {
    throw new Error('Custom error message');
  }
  return <h1>Home</h1>;
}
```

**Comment by sgrobert** [comment]
Hi @kfirfitousi ... Thank you for the additional help and examples! Really appreciate it!
