### ISSUE TITLE
[NEXT-455] Trying to start a project with create-next-app and an import alias causes "EMFILE: too many open files..."

### ISSUE THREAD

**Issue by wbolduc** [vercel/next.js#45161]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Windows 10
git bash terminal

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

no link because the problem is with CNA

### To Reproduce

try and create a project with an alias

for example `npx create-next-app@latest my-project3 --typescript --eslint`
select yes for src and no for app dir and input an alias

### Describe the Bug

![image](https://user-images.githubusercontent.com/16736623/213947786-4d2289c8-d0f7-4e6e-948a-db8841a47809.png)

Causes an error on install
`Aborting installation.
Unexpected error. Please report it as a bug:
 [Error: EMFILE: too many open files, open 'C:\Users\Will\Programming\my-project3\node_modules\next\dist\compiled\raw-body\index.js'] {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\Users\\Will\\Programming\\my-project3\\node_modules\\next\\dist\\compiled\\raw-body\\index.js'
}`

No alias works
![image](https://user-images.githubusercontent.com/16736623/213947902-822bba65-95bc-4da9-8766-732e72b92c52.png)

### Expected Behavior

should be able to give an alias

### Which browser are you using? (if relevant)

none

### How are you deploying your application? (if relevant)

local host

<sub>[NEXT-455](https://linear.app/vercel/issue/NEXT-455/trying-to-start-a-project-with-create-next-app-and-an-import-alias)</sub>

**Comment by IshfaqAhmedProg** [comment]
having the same issue when trying to create a new next-app! but the error report path is postcss-value-parser\LICENSE

### Environment 
Windows 10
git bash terminal

![image](https://user-images.githubusercontent.com/38818105/214483288-69e963ef-5798-4c0a-9e07-1d45d850d158.png)


`Aborting installation.
Unexpected error. Please report it as a bug:
 [Error: EMFILE: too many open files, open 'C:\WorkHolder\ScraperFox\CRM\scrapefox-crm\node_modules\next\dist\compiled\postcss-value-parser\LICENSE'] {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\WorkHolder\\ScraperFox\\CRM\\scrapefox-crm\\node_modules\\next\\dist\\compiled\\postcss-value-parser\\LICENSE'
}`

**Comment by realjoshuau** [comment]
Also having this issue when running `npx create-next-app@latest . --typescript --eslint`

```
Aborting installation.
Unexpected error. Please report it as a bug:
 [Error: EMFILE: too many open files, open '~/Documents/GitHub/front/node_modules/next/dist/shared/lib/router/utils/is-bot.js'] {
```

**Comment by mekavehamichlolay** [comment]
have now the same issue with npx create-next-app
![image](https://user-images.githubusercontent.com/93684773/216258705-e4171665-8453-416e-9f30-8658717010c1.png)

**Comment by HaiderSultanArc** [comment]
It happens with selecting No for src as well. The issue is only recreated by defining aliases while creating the project. Have the same problem here.

**Comment by louisgv** [comment]
This doesn't happen for me locally (npm dev and npm build/start worked). But it throw when deployed to vercel:

```
2023-02-05T23:21:36.825Z	d7fb0c90-4232-4896-8c8a-0e1598ad436e	ERROR	[Error: EMFILE: too many open files, open '/var/task/node_modules/.pnpm/iconoir-react@6.2.0_react@18.2.0/node_modules/iconoir-react/dist/esm/ShareIos.mjs'] {
  errno: -24,
  code: 'EMFILE',
  syscall: 'open',
  path: '/var/task/node_modules/.pnpm/iconoir-react@6.2.0_react@18.2.0/node_modules/iconoir-react/dist/esm/ShareIos.mjs',
  page: '/'
}
RequestId: d7fb0c90-4232-4896-8c8a-0e1598ad436e Error: Runtime exited without providing a reason
Runtime.ExitError

```

**Comment by AionQRy** [comment]
how to fix this error ?

**Comment by necm1** [comment]
I'm facing the same issue. Any updates?
