### ISSUE TITLE
Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir '/root/InfinityBotList/Infinity-Next/node_modules/next/dist/pages/_document.js'

### ISSUE THREAD

**Issue by cheesycod** [vercel/next.js#45189]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir '/root/InfinityBotList/Infinity-Next/node_modules/next/dist/pages/_document.js' in edge routes with a custom document

export const config = {
    runtime: 'experimental-edge',
}
  

custom document:

import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
    render() {
        return (
            <Html>
                <Head>
                </Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </Html>
        )
    }
}

export default MyDocument

### Which area(s) of Next.js are affected? (leave empty if unsure)

Head component/file (next/head / head.js), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

.

### To Reproduce

1. Make a route with experimental-edge and a custom _document.tsx, the error will then appear and the custom document will not be rendered

### Describe the Bug

1. Make a route with experimental-edge and a custom _document.tsx, the error will then appear and the custom document will not be rendered

### Expected Behavior

The server runs properly with custom document

### How are you deploying your application? (if relevant)

next dev and next start

<sub>[NEXT-1396](https://linear.app/vercel/issue/NEXT-1396/watchpack-error-initial-scan-error-enotdir-not-a-directory-scandir)</sub>

**Comment by bobsingor** [comment]
Same issue. custom _document.tsx is not being rendered when using runtime: 'experimental-edge',

Same error:
Watchpack Error (initial scan): Error: ENOTDIR: not a directory, scandir '/Users/.../GitHub/.../node_modules/next/dist/pages/_document.js'

**Comment by kramer99** [comment]
Similar issue here after upgrading from Next 12 to 13. It doesn't stop the app from running, but would be nice to resolve it:

```
/Volumes/code/project % npm run dev

> dev
> next dev

Watchpack Error (watcher): Error: EACCES: permission denied, watch '/Volumes/code/.DocumentRevisions-V100'
Watchpack Error (watcher): Error: EACCES: permission denied, watch '/Volumes/code/.fseventsd'
Watchpack Error (initial scan): Error: EACCES: permission denied, scandir '/Volumes/code/.DocumentRevisions-V100'
Watchpack Error (initial scan): Error: EACCES: permission denied, scandir '/Volumes/code/.fseventsd'
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
...etc...
```

**Comment by kylemclean** [comment]
I am getting the same error, but changes to _document.tsx are being rendered.

Using the `experimental-edge` runtime.

**Comment by cndlhvn** [comment]
Me too

**Comment by syonfox** [comment]
Hello, I am getting the same issue, does anyone know the solutions? 

```
Server Error

ReferenceError: document is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
node_modules/decode-named-character-reference/index.dom.js (5:0)
eval
node_modules/decode-named-character-reference/index.dom.js (5:0)
./node_modules/decode-named-character-reference/index.dom.js
evalmachine.<anonymous> (6545:1)
__webpack_require__
evalmachine.<anonymous> (37:33)
fn
evalmachine.<anonymous> (281:21)
eval
webpack-internal:///./node_modules/micromark-core-commonmark/dev/lib/character-reference.js (6:90)
./node_modules/micromark-core-commonmark/dev/lib/character-reference.js
evalmachine.<anonymous> (7073:1)
__webpack_require__
evalmachine.<anonymous> (37:33)
fn
evalmachine.<anonymous> (281:21)
eval
webpack-internal:///./node_modules/micromark-core-commonmark/dev/index.js (31:85)
./node_modules/micromark-core-commonmark/dev/index.js
evalmachine.<anonymous> (7007:1)
```

**Comment by huozhi** [comment]
Couldn't repro with latest nextjs anymore, add a test case for this. Please verify with latest nextjs version
