### ISSUE TITLE
AppDir [slug] not working with Prisma+Postgres

### ISSUE THREAD

**Issue by jensamunch** [vercel/next.js#45219]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.13.2
      npm: 9.2.0
      Yarn: N/A
      pnpm: 7.25.1
    Relevant packages:
      next: 13.1.3
      eslint-config-next: 13.1.3
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.1.3", newest: "13.1.6-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue

### Link to the code that reproduces this issue

https://github.com/jensamunch/nextjs-app-directory

### To Reproduce

Nextjs + Prisma + Postgres + Railway

This page works using `pnpm dev`. But breaks when trying to build.
Somehow it is getting null from the DB call? But how come it works with dev?
In both cases it's a railway.app DB is called.

```
import { findPost } from 'lib/posts';

interface Props {
  params: {
    slug: string;
  };
}

export default async function Page({ params }: Props) {
  const id = params.slug;
  const post = await findPost;
  };
  if (post) {
    return (
      <>
       {post.title}
      </>
    );
  }
}
```

### Describe the Bug

info  - Compiled successfully
info  - Skipping validation of types
info  - Linting  
info  - Collecting page data  
[    ] info  - Generating static pages (0/4)TypeError: Cannot read properties of null (reading 'title')
    at Content (/Users/jensmunch/Documents/nextjs-app-directory/.next/server/app/post/[slug]/page.js:366:29)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3496175693'
}

Error occurred prerendering page "/post/[slug]". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'title')
    at Content (/Users/jensmunch/Documents/nextjs-app-directory/.next/server/app/post/[slug]/page.js:366:29)
info  - Generating static pages (4/4)

> Build error occurred
Error: Export encountered errors on following paths:
        /post/[slug]/page: /post/[slug]
    at /Users/jensmunch/Documents/nextjs-app-directory/node_modules/.pnpm/next@13.1.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/export/index.js:409:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/jensmunch/Documents/nextjs-app-directory/node_modules/.pnpm/next@13.1.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/jensmunch/Documents/nextjs-app-directory/node_modules/.pnpm/next@13.1.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:1398:21
    at async Span.traceAsyncFn (/Users/jensmunch/Documents/nextjs-app-directory/node_modules/.pnpm/next@13.1.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async /Users/jensmunch/Documents/nextjs-app-directory/node_modules/.pnpm/next@13.1.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:1258:17
    at async Span.traceAsyncFn (/Users/jensmunch/Documents/nextjs-app-directory/node_modules/.pnpm/next@13.1.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/Users/jensmunch/Documents/nextjs-app-directory/node_modules/.pnpm/next@13.1.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/build/index.js:66:29)
 ELIFECYCLE  Command failed with exit code 1.

### Expected Behavior

Everything works when I d
It's working with prisma when I use sqlite and file db.
When I deploy with railway.app the dynamic path fails.

All other parts of the app are fine incl server components so its not a db issue.

**Comment by GabenGar** [comment]
SQLite and file db? How do you fetch data from those? There is no file system in prod.

**Comment by jensamunch** [comment]
@GabenGar thanks you're right.

i've made it more clear now:
https://github.com/jensamunch/nextjs-app-directory
https://nextjs-app-directory-mxwjpp81z-jens.vercel.app/

you can see that everything is fetching from DB but slug page is returning NULL
https://nextjs-app-directory-mxwjpp81z-jens.vercel.app/post/clda40xjm0000ml08hizonynn

**Comment by jensamunch** [comment]
hmm..

no it seems i was wrong...thank you for your help @GabenGar i dont know what happened but it works now:

https://nextjs-app-directory-9iq38x19c-jens.vercel.app/
