### ISSUE TITLE
Nested `next/dynamic` is not preloaded during SSR

### ISSUE THREAD

**Issue by fikrikarim** [vercel/next.js#45213]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.6-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/fikrikarim/nested-next-dynamic-bug

### To Reproduce

Create a nested `next/dynamic` component: import a component with `next/dynamic`, and inside that component, import another component with `next/dynamic`.

 Run `next build` and `next start`. Check the generated HTML.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/13066728/214244603-aa40299f-1c6b-4a6d-b2fb-fe642ca0509c.png">

https://nested-next-dynamic-bug.vercel.app/

### Describe the Bug

The recent PR #45160 fix React.lazy preloading during SSR. It's working, but it doesn't preload a nested `next/dynamic`.

### Expected Behavior

The generated HTML should contain the correct content by preloading all `next/dynamic`, even the nested ones.

`Next.js v13.0.6` has the expected behavior:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/13066728/214245565-6fea4c90-b742-47a0-b132-6826873f5f83.png">

https://nested-next-dynamic-dbn5z8i2d-fikrikarim.vercel.app/

**Comment by hsheikhali1** [comment]
Can confirm this is still a bug. We're still experiencing issues where static builds dont contain the compiled CSS rather a inline JS script that targets elements.. which then get blocked by CSP rules.

**Comment by sebpettersson** [comment]
I think this is a fairly major issue still, since @huozhi's  #45160 only partially fixed #45151. 

It essentially keeps us from upgrading past 13.0.6, at least without doing changes to our code splitting strategy.

I think this bug might also have SEO implications, and even worse, it might break sites that have CSP that doesn't allow `unsafe-inline` for `script-src`.

**Comment by hsheikhali1P** [comment]
> I think this is a fairly major issue still, since @huozhi's #45160 only partially fixed #45151.
> 
> It essentially keeps us from upgrading past 13.0.6, at least without doing changes to our code splitting strategy.
> 
> I think this bug might also have SEO implications, and even worse, it might break sites that have CSP that doesn't allow `unsafe-inline` for `script-src`.


This does break our site since we have very strict CSP rules. We already had to work around the fact that NextJS injects a inline style to image tags.. `<img style="color: transparent" ... />` all thought that one isn't as bad.

As a result of this bug we opted not to go past v13.0.0

**Comment by hsheikhali1** [comment]
> I think this is a fairly major issue still, since @huozhi's #45160 only partially fixed #45151.
> 
> It essentially keeps us from upgrading past 13.0.6, at least without doing changes to our code splitting strategy.
> 
> I think this bug might also have SEO implications, and even worse, it might break sites that have CSP that doesn't allow `unsafe-inline` for `script-src`.

This does break our site since we have very strict CSP rules. We already had to work around the fact that NextJS injects a inline style to image tags.. <img style="color: transparent" ... /> all thought that one isn't as bad.

As a result of this bug we opted not to go past v13.0.0
