### ISSUE TITLE
absolute import error while trying to import from index file

### ISSUE THREAD

**Issue by dalalRohit** [vercel/next.js#45212]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Tue Jan 24 2023 12:13:14 GMT+0530 (India Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.1.4
      eslint-config-next: 11.1.4
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://stackblitz.com/edit/github-xpctje

### To Reproduce

1. Navigate to the [StackBlitz demo](https://stackblitz.com/edit/github-xpctje)
2. Project will fail to compile

### Describe the Bug

I'm trying to set up absolute imports using this [official guide](https://nextjs.org/docs/advanced-features/module-path-aliases). While setting up, I noticed one issue/bug. I have got an `index.tsx` file in `hooks, components, types` folders which exports all the other files inside the corresponding folders.

This is not working
```
import { useTest } from '@/hooks';
```

This is working
```
import { useTest } from '@/hooks/index';
```

I don't think specifying "index" for every directory is the way to go here. Is there anything I'm missing?

Any help is highly appreciated, thank you ;)

![image](https://user-images.githubusercontent.com/32014253/214230222-cee40f22-200b-490b-bc00-c505958877b0.png)

### Expected Behavior

This issue is happening only with the folders where I have an `index` file to export everything from. 
We should be able to use the absolute import feature with this pattern as well.

The following snippet should work, is my expectation.
```
import { useTest } from '@/hooks';
```

**Comment by kfirfitousi** [comment]
In `tsconfig.ts`, using
```json
"paths": {
  "@/hooks/*": ["hooks/*"]
}
```
will only match paths like `@/hooks/<something>`.
You can use this:
```json
"paths": {
  "@/hooks": ["hooks"]
}
```

or a catch-all alias:

```json
"paths": {
  "@/*": ["./*"]
}
```

**Comment by dalalRohit** [comment]
thank you so much, this worked 👍🏻
