### ISSUE TITLE
Fully dynamic page being prerendered with broken parameters

### ISSUE THREAD

**Issue by vattenapa** [vercel/next.js#45220]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #2 SMP Mon Sep 19 16:26:59 CEST 2022
    Binaries:
      Node: 18.9.0
      npm: 8.19.1
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 13.1.6-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-nblcsw?file=app/test/[id]/page.tsx

### To Reproduce

Run _npm build_

An error will be thrown during static generation due to `/test/[id]` not being statically generatable.

### Describe the Bug

During the static generation phase, Next.js will attempt to generate the page statically with the id `[id]` (url encoded to `%5Bid%5D`).

This happens whether `generateStaticParams` is defined or not.

Seems to have been introduced in 13.1.2, as before I updated my packages, this worked as expected.

### Expected Behavior

No static generation when there are no defined static params.

**Comment by sroussey** [comment]
I created a test to show this as well at https://github.com/sroussey/test-build/tree/generateStaticParams

The count during build is correct, but the calls are not. Instead of getting called multiple times (either example here or mine), it gets called once with `{ id: '%5Bid%5D' }` which is `[id]`. So nothing is prerendered except a bad parameter. This also likely explains part of the reason my next-sitemap finds nothing in the app folder. I can't even do a PR to fix that one since nothing is in the private `.next/*manifest.json` files.

```
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Linting and checking validity of types  
info  - Collecting page data  
[    ] info  - Generating static pages (0/4){ id: '%5Bid%5D' }
{ id: '%5Bid%5D' }
info  - Generating static pages (4/4)
info  - Finalizing page optimization  

Route (app)                                Size     First Load JS
┌ ○ /                                      0 B                0 B
└ ○ /[id]                                  136 B          66.3 kB
+ First Load JS shared by all              66.2 kB
  ├ chunks/17-117920d106f3fedc.js          64.3 kB
  ├ chunks/main-app-98e085eb764b6ba1.js    205 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   179 B          80.7 kB
+ First Load JS shared by all              80.5 kB
  ├ chunks/main-f65e8b61c2b0787e.js        78.7 kB
  ├ chunks/pages/_app-5841ab2cb3aa228d.js  192 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)
```

In my example, I have every page console.error the id, and I have three ids, so you would expect to see those emitted during the build, but instead you see { id: '%5Bid%5D' } and the pages not listed as built.

**Comment by sroussey** [comment]
Also, there does not seem to be a test to verify that pages are actually rendered. There is a test to see if the build output says how many pages were rendered though, but that is not the same. ;)

**Comment by sroussey** [comment]
I changed the code to output the entire args each time:

```
info  - Collecting page data  
[    ] info  - Generating static pages (0/4){ params: { id: '%5Bid%5D' }, searchParams: { id: '[id]' } }
{ params: { id: '%5Bid%5D' }, searchParams: { id: '[id]' } }
info  - Generating static pages (4/4)
```

**Comment by ijjk** [comment]
Hi, unless you specify `export const dynamic = 'dynamic'` we don't know the page is dynamic unless we attempt rendering it which provides the default params similar to how the fallback is generated in `pages`.

**Comment by sroussey** [comment]
This bug was introduced in v 13.1.1

What you are saying is conceptually true, but the code does not work as you say it does.

**Comment by sroussey** [comment]
As for this issue, between 13.1.1 and 13.1.2, the build process puts the `[id]` as the parameter. Sorry if I messed up your issue @vattenapa.

**Comment by vattenapa** [comment]
@ijjk Sorry, I think the issue title is a bit misleading -- I'm not looking to create a per-request dynamic route, but a route that is not pre-rendered but during runtime fetches data from a CMS to determine if the route exists or not without having to turn off all caching (`force-dynamic`).

Is the pre-13.1.2 an implicit `force-dynamic` for the pages like in my example? (imagine replacing the dummy with a fetch)
