### ISSUE TITLE
NextJS 13 (latest) package not working in monorepos

### ISSUE THREAD

**Issue by JoeCollinsBJSS** [vercel/next.js#45258]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 8.1.2
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 13.1.3-canary.4
      eslint-config-next: 12.0.0
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue

https://github.com/JoeCollinsBJSS/next-monorepo-bug-reproduction/tree/main

### To Reproduce

Place Next 13 package into a monorepo with other next packages and apps (for example I've used the `api-routes-app` example, but this seems to occur with all next examples and basic apps - see repo attached for a simple recreation)
Run `pnpm install` and then (`./scripts/recreate.sh`) or the below:
```
#!/bin/bash

cd ./source/apps/app-collection/api-routes-app
pnpm run build
cp -r .next/static .next/standalone/.next/static
node .next/standalone/server.js
```
This will now error. The identical package and commands works if moved into it's own dir outside of a monorepo (eg, `cp -r . ~/api-routes-app` then running the above commands will have it successfully run). 

### Describe the Bug

After following the above recreation, the below error occurs:

```
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (4/4)
info  - Finalizing page optimization  

Route (pages)                              Size     First Load JS
┌ ○ /                                      2.35 kB        79.6 kB
├ ○ /404                                   182 B          73.1 kB
├ λ /api/people                            0 B              73 kB
├ λ /api/people/[id]                       0 B              73 kB
└ ○ /person/[id]                           632 B          77.9 kB
+ First Load JS shared by all              73 kB
  ├ chunks/framework-6690b5f441f4815a.js   45.2 kB
  ├ chunks/main-0b3de3c2ea1d89dc.js        26.8 kB
  ├ chunks/pages/_app-f428db71773d82f0.js  195 B
  └ chunks/webpack-8fa1640cc84ba8fe.js     750 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './initialize-require-hook'
Require stack:
- /Users/[redacted]/next-monorepo-test/source/apps/node_modules/.pnpm/next@13.1.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js
- /Users/[redacted]/next-monorepo-test/source/apps/app-collection/api-routes-app/.next/standalone/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/[redacted]/next-monorepo-test/source/apps/node_modules/.pnpm/next@13.1.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/[redacted]/next-monorepo-test/source/apps/node_modules/.pnpm/next@13.1.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js',
    '/Users/[redacted]/next-monorepo-test/source/apps/app-collection/api-routes-app/.next/standalone/server.js'
  ]
```

### Expected Behavior

The app should run locally when running `node .next/standalone/server.js` in the package, as it does when the project is in it's own root dir

### How are you deploying your application? (if relevant)

pnpm run build && node server.js

**Comment by diroussel** [comment]
Yes, I've seen this too.  A simple example Nextjs project that builds in standalong mode works on it's own.  But when run from inside an pnpm mono repo, the build app doesn't work.

It's not only that the standalone mode misses some dependency modules, it seems to just copy a few files from withing those modules.

Could it be that it's getting confused by pnpm's use of symlinks.  Or could it be something else?

**Comment by janpio** [comment]
We have a similar error in a project we are currently working on to figure out a different problem. Here is the full stacktrace and info:

```
gitpod /project/packages/service (main) $ node .next/standalone/server.js
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module './initialize-require-hook'
Require stack:
- /project/packages/service/node_modules/.pnpm/next@13.1.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js
- /project/packages/service/.next/standalone/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/project/packages/service/node_modules/.pnpm/next@13.1.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project/packages/service/node_modules/.pnpm/next@13.1.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js',
    '/project/packages/service/.next/standalone/server.js'
  ]
}
```

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.22.0
    Relevant packages:
      next: 13.1.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

My colleague @millsp previously connected this to another issue https://github.com/vercel/next.js/issues/42651, where he posted a bit of an analysis as well: https://github.com/vercel/next.js/issues/42651#issuecomment-1399053794 

Based on that he also came up with a workaround: `rm -fr .next/standalone/node_modules/next`. After running this command, I can successfully start and use the app.

**Comment by diroussel** [comment]
@janpio that just removes the broken copy of 'next' from the standalone folder. So when you run the app, it will find 'next' in the node_modules of the parent folder.  If you were to copy the 'standalone' folder out to somewhere else on the filessystem or another machine. Then it wouldn't work.  Right?

**Comment by millsp** [comment]
Yes, that's right. I was deleting this folder just for the sake of doing a local reproduction with `next` + `prisma`. I don't think it would deploy correctly, indeed. Hopefully this will highlight the problem. From what I have seen, only the server file is copied but not the rest of the files that are needed. I could reproduce with `pnpm` and `npm` workspaces.

**Comment by DuCanhGH** [comment]
I did some changes to your repo:
- `scripts/recreate.sh`
```sh
#!/bin/bash

cd ./source/apps/app-collection/api-routes-app
pnpm run build
cp -r .next/static .next/standalone/.next/static
node .next/standalone/server.js
```
- Root `pnpm-lock.yaml`:
```yaml
packages:
  # all packages in subdirs of apps/
  - 'source/apps/**'
  # all packages in direct subdirs of packages/
  - 'packages/**'
```
- Your `next.config.js`:
```js
const { join } = require('path');

/** @type {import('next').NextConfig} */
module.exports = {
  output: 'standalone',
  experimental: {
    outputFileTracingRoot: join(__dirname, "../../../..")
  }
}
```
And deleted `pnpm-lock.yaml` in other folders, since those aren't needed. Then I tried to build and it worked just fine. Please see the [caveats](https://nextjs.org/docs/advanced-features/output-file-tracing#caveats) section here, it says that you need to use `experimental.outputFileTracingRoot` in monorepos. Hope this helps :)

**Comment by JoeCollinsBJSS** [comment]
I've tried the above resolution, although this works if we run in situ, if we try to move the standalone folder to be standalone as in the below script (now in the repo if you `git fetch`) it breaks with missing `styled-jsx` modules. I've attempted to install that within my app and then re-build and that didn't resolve the issue at all so it seems like something else must be going on? We don't use styled-jsx directly at all and it seems to be used by nextjs

````
#!/bin/bash

cd ./source/apps/app-collection/api-routes-app
pnpm run build
mkdir .next/standalone/source/apps/app-collection/api-routes-app/.next/static
cp -r .next/static .next/standalone/source/apps/app-collection/api-routes-app/.next
# node .next/standalone/source/apps/app-collection/api-routes-app/server.js

mkdir ~/standalone-dir
cp -r .next ~/standalone-dir
cd ~/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/
node server.js

**Comment by DuCanhGH** [comment]
@JoeCollinsBJSS that's kinda weird, I'm having no trouble running that script at all:
![image of a successful run](https://user-images.githubusercontent.com/75556609/217313424-1b736c6e-7fac-42c2-9ff1-4297bd451801.png)
The script runs just fine, and all I did after cloning your repo were changing your pnpm-workspace.yaml, deleting unnecessary pnpm-lock files and then running the script.

**Comment by sunaurus** [comment]
I'm debugging this issue right now for my project, I've found that the issue does not occur consistently on all machines.

One one machine, after I run `next build`, my `.next/standalone/node_modules/next/dist/server` only contains these files:

```
drwxrwxr-x 2 runner runner  4096 Feb 16 07:43 .
drwxrwxr-x 8 runner runner  4096 Feb 16 07:43 ..
-rw-rw-r-- 1 runner runner   708 Feb 16 07:43 get-page-files.js
-rw-rw-r-- 1 runner runner   698 Feb 16 07:43 htmlescape.js
-rw-rw-r-- 1 runner runner 71950 Feb 16 07:43 next-server.js
-rw-rw-r-- 1 runner runner   681 Feb 16 07:43 utils.js
```
So it's clearly missing `initialize-require-hook` for example and thus next fails to start.

However, on a second machine, with the exact same repo and following the exact same build steps, the `.next/standalone/node_modules/next/dist/server` contains much more files (including `initialize-require-hook.js`), and the next starts without issues.

Both machines are ARM based, both are running the exact same version of node (v18.13.0), so I'm still trying to figure out what the actual difference is and why one machine is producing different results.

**Comment by dnyn92** [comment]
> I've tried the above resolution, although this works if we run in situ, if we try to move the standalone folder to be standalone as in the below script (now in the repo if you `git fetch`) it breaks with missing `styled-jsx` modules. I've attempted to install that within my app and then re-build and that didn't resolve the issue at all so it seems like something else must be going on? We don't use styled-jsx directly at all and it seems to be used by nextjs
> 
> ```
> #!/bin/bash
> 
> cd ./source/apps/app-collection/api-routes-app
> pnpm run build
> mkdir .next/standalone/source/apps/app-collection/api-routes-app/.next/static
> cp -r .next/static .next/standalone/source/apps/app-collection/api-routes-app/.next
> # node .next/standalone/source/apps/app-collection/api-routes-app/server.js
> 
> mkdir ~/standalone-dir
> cp -r .next ~/standalone-dir
> cd ~/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/
> node server.js
> ```
> 
> & The error:
> 
> ```
> node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module 'styled-jsx'
> Require stack:
> - /Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/node_modules/next/dist/build/webpack/require-hook.js
> - /Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/node_modules/next/dist/server/initialize-require-hook.js
> - /Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/node_modules/next/dist/server/next-server.js
> - /Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/server.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
>     at Object.loadRequireHook (/Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/node_modules/next/dist/build/webpack/require-hook.js:38:21)
>     at Object.<anonymous> (/Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/node_modules/next/dist/server/initialize-require-hook.js:3:19)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/node_modules/next/dist/build/webpack/require-hook.js',
>     '/Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/node_modules/next/dist/server/initialize-require-hook.js',
>     '/Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/node_modules/next/dist/server/next-server.js',
>     '/Users/Joe.Collins/standalone-dir/.next/standalone/source/apps/app-collection/api-routes-app/server.js'
>   ]
> }
> ```

I've got the same issue with a Nx monorepo using pnpm for my Nextjs app. If I compile it locally on my Mac (Intel) it works perfectly but as soon as I try to deploy it to Azure with Github Actions the deployment fails. If I download the build artifact and run it locally it through the above mentioned error. I have also tried to install styled-jsx as dependency but same result. So far, it was an awful experience to deploy a Nextjs app in a monorepo with Nx, running from one workaround to the other (bundle size, nested directories in the bundle, etc.).

```
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'styled-jsx'
```
The relevant version that I am using are:
```
"nx": "15.6.2",
"next": "13.1.1",
"pnpm": "^7.26.1",
```

**Comment by dogyun-wildseed** [comment]
I have simillar issue
```
Node.js v18.16.0
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module './initialize-require-hook'
Require stack:
- /base/node_modules/next/dist/server/next-server.js
- /base/front/codo-front/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/base/node_modules/next/dist/server/next-server.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/base/node_modules/next/dist/server/next-server.js',
    '/base/front/codo-front/server.js'
  ]
} 
```

I  have tried  with adding `experimental.outputFileTracingRoot`, it doesn't work neiter

**Comment by idleberg** [comment]
I ran into the same problem and could _workaround_ the issue by adding a `.npmrc` to my monorepo-root.

```
shared-workspace-lockfile=false
```

That alone won't be enough if you have specified `outputFileTracingRoot` in your Next config.
