### ISSUE TITLE
res.revalidate does not clear Vercel cache under certain condition when using wildcard subdomains

### ISSUE THREAD

**Issue by horizon0708** [vercel/next.js#45269]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/horizon0708/revalidate-repro

### To Reproduce

1. Clone the repo and host the project in Vercel. Add `SECRET_KEY` env var.
2. Add a wildcard certificate (for my repro repo it is *.revalidate.sidenotes.xyz) 
3. After the app is deployed, go to any wildcard domain (e.g. abc.revalidate.sidenotes.xyz)
4. you should see a random number and refreshing a page should not change the number as the page has been SSG'd
6. Trigger revalidate for that path (`/site/abc`) by triggering a GET request, using a different subdomain e.g. `https://other.revalidate.sidenotes.xyz/api/revalidate?apiKey={SECRET_KEY}&path=%2Fsite%2Fabc`
7. confirm revalidate isn't giving any error responses and that `getStaticProps` is getting called in the logs.
8. Refresh the page. The number isn't refreshed. HTML payload still has the same number.

Expected behaviour: the page is re-genereated and the number changes when I refresh the page.
Actual behaviour: the number stays the same 

The cache purge works IF you call the `/api/revalidate` endpoint with the same subdomain. i.e.
Given that you want to revalidate `a.test.com`
- calling `a.test.com/api/revalidate` 🟢
- calling `test.com/api/revalidate` ❌
- calling `b.test.com/api/revalidate` ❌

Note that the cache purge from different subdomain works if you run next locally with `next start`,  which leads me to think that this is not the intended behaviour

### Describe the Bug

When a path is revalidated, the subdomain of the `api` endpoint that is calling the `res.revalidate` is wrongly taken into account in clearing the cache.

### Expected Behavior

When a path is revalidated, the Vercel cache for that path should be cleared regardless of the caller's subdomain.

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by horizon0708** [comment]
Double checking, I can't repro with the reproduction repo, so I'll close this for now.

**Comment by horizon0708** [comment]
Reopeing with updated repro steps

**Comment by ijjk** [comment]
Hi, this behavior is currently expected as the CDN cache is specific to the hostname so to revalidate content on a hostname it needs to be called via that hostname.

**Comment by horizon0708** [comment]
@ijjk It would be nice if it is documented somewhere though :p
