### ISSUE TITLE
Edge runtime region not working when Sentry plugin installed

### ISSUE THREAD

**Issue by MatWetz** [vercel/next.js#45271]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.0.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.16.0
    Relevant packages:
      next: 13.1.6-canary.1
      eslint-config-next: 13.1.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/MatWetz/sentry-next-bug

### To Reproduce

Follow these steps 👇

pnpm create next-app
cd into the new app
npx @sentry/wizard -i nextjs
add pages/api/regional.ts with export const config = { runtime: 'edge', regions: ['dub1'] }
pnpm run build
cat .next/server/middleware-manifest.json

Region does not appear when checking in `cat .next/server/middleware-manifest.json`

```
{
  "sortedMiddleware": [],
  "middleware": {},
  "functions": {
    "/api/regional": {
      "env": [
        "SENTRY_DSN",
        "NEXT_PUBLIC_SENTRY_DSN",
        "SENTRY_TRACES_SAMPLE_RATE",
        "SENTRY_ENVIRONMENT",
        "SENTRY_RELEASE",
        "GITHUB_SHA",
        "COMMIT_REF",
        "VERCEL_GIT_COMMIT_SHA",
        "VERCEL_GITHUB_COMMIT_SHA",
        "VERCEL_GITLAB_COMMIT_SHA",
        "VERCEL_BITBUCKET_COMMIT_SHA",
        "ZEIT_GITHUB_COMMIT_SHA",
        "ZEIT_GITLAB_COMMIT_SHA",
        "ZEIT_BITBUCKET_COMMIT_SHA",
        "SENTRY_NAME"
      ],
      "files": [
        "server/edge-runtime-webpack.js",
        "server/pages/api/regional.js"
      ],
      "name": "pages/api/regional",
      "page": "/api/regional",
      "matchers": [
        {
          "regexp": "^/api/regional$"
        }
      ],
      "wasm": [],
      "assets": []
    }
  },
  "version": 2
}% 
```   

### Describe the Bug

When adding a specific region to the edge runtime, it does not get applied when Sentry is also in the Next.js project.

### Expected Behavior

The "dub1" region should appear in middleware-manifest.json, thus taking into account by the Next.js builder

### Which browser are you using? (if relevant)

-

### How are you deploying your application? (if relevant)

-

**Comment by balazsorban44** [comment]
Tracked internally. https://vercel.slack.com/archives/C03S8ED1DKM/p1675174547343459?thread_ts=1674552621.716099&cid=C03S8ED1DKM
