### ISSUE TITLE
Docs: Rewrites (Unreachable `404 page` or `error page`)

### ISSUE THREAD

**Issue by cha2hyun** [vercel/next.js#45285]
### Issue
Unreachable '404 page' or 'error page' when invalid 'rewrites' in 'config'.
Docs can warn people to check for `rewrites` when a browser can't reach that 

### For more information
Discussion: https://github.com/vercel/next.js/discussions/45071

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next.config.js/rewrites

**Comment by balazsorban44** [comment]
Hi, could you possibly open a bug report with a _minimal_ reproduction focusing on your issue? Preferably a public GitHub repository. 

It's not entirely clear to me from the linked thread what the issue might be. It mentions `_404` (which is not recognized by Next.js, the correct file name is `404`), and also Middleware, but then it shows an `_app` file. All in all, it would be great to see the whole code. Thanks!

**Comment by cha2hyun** [comment]
> Hi, could you possibly open a bug report with a _minimal_ reproduction focusing on your issue? Preferably a public GitHub repository.
> 
> It's not entirely clear to me from the linked thread what the issue might be. It mentions `_404` (which is not recognized by Next.js, the correct file name is `404`), and also Middleware, but then it shows an `_app` file. All in all, it would be great to see the whole code. Thanks!

Hello @balazsorban44 

There is an example repo
https://github.com/3underdog/nangmanski_web_v2

published on 
https://nangmanski-web-v2.vercel.app/

> API server has been closed. So index pages will go error page


### Unreachable 404 pages

When i go invalid path like `https://nangmanski-web-v2.vercel.app/abcdefghi` it says bad gateway
![image](https://user-images.githubusercontent.com/56015532/215955109-4207be54-e97d-4fb1-9be0-1052b138eabd.png)

The reason why it goes `502 Bad Gateway` which made by vercel not a custom `404 pages` is there are wrong destination path on `next.config.js`
