### ISSUE TITLE
Commerce: Menu flickering on mouse over

### ISSUE THREAD

**Issue by yazoo321** [vercel/next.js#45327]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Uploading vercel_bug_report.mov…

The bug can be reproduced in the hosted demo
https://spree.vercel.store/

and I reproduced locally with: https://github.com/vercel/commerce
also with updating to latest next.js

### Which example does this report relate to?

commerce (https://github.com/vercel/commerce)

### What browser are you using? (if relevant)

tested multiple

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

When you sign in, you can open the user menu by clicking the icon
The menu appears, however if the mouse overlays the menu, the menu location flickers to a different side

### Expected Behavior

The menu should remain in the instantiated position

### To Reproduce

Sign in, open the user menu and hover the mouse over the menu.
See the video uploaded

**Comment by yazoo321** [comment]
https://user-images.githubusercontent.com/19325521/215058098-a974e021-b6ac-400c-88d5-0ec174fcf28b.mov

Re-attaching bug video

**Comment by balazsorban44** [comment]
Thanks, please report this on https://github.com/vercel/commerce

Note, might be fixed by https://github.com/vercel/commerce/pull/918
