### ISSUE TITLE
"Max serverless function size" when using readFile from public/*

### ISSUE THREAD

**Issue by Eyas** [vercel/next.js#45320]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6-canary.1
      eslint-config-next: 13.1.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Eyas/nextjs-repro-1

### To Reproduce

1. Clone the Repo
2. Try to deploy to vercel

### Describe the Bug

A static set of pages with `generateStaticParams` to render MDX pages.

Within the (supposedly static) RSC, we have an image optimizer with these lines (commenting them out causes the issue to go away):

```
  const imagePath = path.join(process.cwd(), "public", src);
  const imageBuffer = await readFile(imagePath);
```

This code should be run locally on build during page generation (and it seems to when running `next build`). But when attempting to deploy,

Deployment fails with

```
Error: The Serverless Function "blog/[slug]" is 155.98mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
```

I see a few issues:
- The list of dependencies includes everything in `/public`, even unreferenced files
- These dependencies shouldn't be included in a Serverless function, they should run once on build
- These dependencies are included even if the code isn't called (e.g. by returning early using `if(true) { return;}`)

### Expected Behavior

Deployment succeeds, as these are not runtime dependencies.

### How are you deploying your application? (if relevant)

Vercel

**Comment by ijjk** [comment]
This is due to how the static tracing works, since `@vercel/nft` can't be sure what the `src` value could be it includes all paths in `public` as that's a static reference. To reduce the amount of files included you need to make the path more specific e.g. `public/runtime`
