### ISSUE TITLE
[NEXT-594] Deploying to Vercel breaks client-side navigation with app

### ISSUE THREAD

**Issue by razvan-soare** [vercel/next.js#45331]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

next info:
Operating System:
Platform: darwin
Arch: arm64
Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41\~1/RELEASE_ARM64_T6000
Binaries:
Node: 16.18.0
npm: 8.19.2
Yarn: 1.22.19
pnpm: N/A
Relevant packages:
next: 13.1.6-canary.1
eslint-config-next: 13.1.6-canary.1
react: 18.2.0
react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

Narrowed down version by @timneutkens: [https://github.com/timneutkens/test1234-nextjs](https://github.com/timneutkens/test1234-nextjs)

<details>
<summary>Original reproduction</summary>

[https://github.com/razvan-soare/test1234-nextjs](https://github.com/razvan-soare/test1234-nextjs)
</details>

### To Reproduce

Live url: [https://test1234-nextjs.vercel.app/product](https://test1234-nextjs.vercel.app/product)
Code: [https://github.com/razvan-soare/test1234-nextjs](https://github.com/razvan-soare/test1234-nextjs)

### Describe the Bug

Main Problem:

On page transition the page fully reloads.
Seems the prefetching is not working after deploying to vercel.
If i run the build command and run the server locally everything works -> page transition does not fully reload the page state is being kept
Im using the new APP folder structure. This example is just a simple example that emulates one project im working on. Inside the layout im rendering the UIHeader, containing all the links and a button that sets a state. Locally the state is kept between page transition but not working once is deployed to vercel. (always getting reset)

Tried a bunch of setups but it seems prefetching breaks once it gets deployed. I am on the latest version: 13.1.5

### Expected Behavior

On route change the page wont fully reload and only load the necessary resources and take advantage of prefetch

### Which browser are you using? (if relevant)

all

### How are you deploying your application? (if relevant)

vercel

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-594](https://linear.app/vercel/issue/NEXT-594/deploying-to-vercel-breaks-client-side-navigation-with-app)</sub>

**Comment by ardauzan** [comment]
Same. Its extremely frustrating.

**Comment by ddegooijer** [comment]
Also have this issue with nextjs 13.1 and app dir. 

Any update on this?

**Comment by timneutkens** [comment]
Thanks for the report! We'll have a look!

**Comment by timneutkens** [comment]
Thanks for the reproduction, I was able to verify the issue, we'll investigate and fix it.

I've created a narrowed down version of the reproduction: https://github.com/timneutkens/test1234-nextjs

**Comment by ijjk** [comment]
Hi, thanks for the reproduction, we've opened a patch for this here https://github.com/vercel/vercel/pull/9493 and will update when it's available to leverage!

**Comment by ddegooijer** [comment]
I still have 404 with prefetch on:
https://demo-1.caresites.vercel.app/

This is a project that uses the platform kit repo as an example, with dynamic sites and slugs, all generated with generateStaticParams. 

I could create a github repo if you like, right now its private.

**Comment by timneutkens** [comment]
As JJ mentioned this isn't deployed to production yet.

**Comment by ijjk** [comment]
Hi, the mentioned patch has now been release, please re-deploy your project and give it a try!

**Comment by ddegooijer** [comment]
Redeployed and the 404 issue is gone! Thanks very much.

Still have the new 'hard' page rendering on every request, instead of the 'soft' load. When loading the project locally with build and start it works fine. 

Maybe an issue with middleware? I could create a small repo so you can check the code :-)

Thanks in advance.

**Comment by timneutkens** [comment]
Verified the issue for which a reproduction was provided is fixed so I'm going to close this issue. Please open a new issue with a reproduction for what you're running into @ddegooijer!
