### ISSUE TITLE
AppDir Next/Link  stops scroll to #ID

### ISSUE THREAD

**Issue by st1ng7ay** [vercel/next.js#45342]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.26.0
    Relevant packages:
      next: 13.1.6-canary.1
      eslint-config-next: 13.1.5
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-qya3vg?file=app%2Fpage.tsx

### To Reproduce

migrate from pages to app

### Describe the Bug

Link to # ID stops working - no scroll to ID

### Expected Behavior

after clicking page scrolls to ID

### Which browser are you using? (if relevant)

Safari, Chrome

**Comment by nalenb** [comment]
I'm having the same issue in next 13.1.5

**Comment by matulkum** [comment]
I think it Is same as (or at least related to) #44625
