### ISSUE TITLE
'legacyBehavior' default value is next/link is true, which is different from the documentation

### ISSUE THREAD

**Issue by Rongeegee** [vercel/next.js#45378]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: #154~18.04.1-Ubuntu SMP Tue Jan 10 16:58:20 UTC 2023
    Binaries:
      Node: 16.13.1
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: 7.11.0
    Relevant packages:
      next: 12.3.0
      eslint-config-next: 12.3.0
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

None.

### To Reproduce

Use a Link component imported from 'next/link', and pass any attributes, such as 'className' to it. The attributes will all be ignored. 

### Describe the Bug

I use the Link component imported from 'next/link'. Apprarently, if I pass any attribute or props to this component, it will be ignored unless I manually pass 'legacyBehavior={false}' to the Link component. According to this documentation: https://nextjs.org/docs/api-reference/next/link, legacyBehavior is default to be false. There should not be the need to manually pass 'legacyBehavior={false}'. So either the documentation is wrong or this is a bug.

### Expected Behavior

The attributes of the link should not be ignored and should be in the developer console without passing 'legacyBehavior={false}' to it

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Linux VPS

**Comment by DuCanhGH** [comment]
Because `legacyBehavior`'s default value was changed to `false` in `v13.0.0` 💀

**Comment by Rongeegee** [comment]
@DuCanhGH That's incorrect. I updated my project to the newest, and the default value is still true

**Comment by DuCanhGH** [comment]
@Rongeegee I'm not sure about that, your environment information specifies that you are using `v12.3.0`. Please make sure `experimental.newNextLinkBehavior` in your `next.config.js` isn't set to `false`. I don't see how `next/link` isn't using the new behavior by default in Next 13 as I'm using it with `className` just fine in my project.
