### ISSUE TITLE
Page params not passed properly when using Next/Link in very specific circumstance

### ISSUE THREAD

**Issue by kshehadeh** [vercel/next.js#45393]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/kshehadeh/next-link-bug-example

### To Reproduce

Run the sample app above and navigate to the http://localhost:3000.  There are two links - "Works" and "Does not work".  When you click on the "Does not work" you will be taken to a page where the page params are not being passed to the component properly.  

### Describe the Bug

This is a demonstration of a bug with NextJS 13:

**When**

1. middleware is used
2. trailingSlash config is set to `true`
3. Using next/link to link to a [...params] file that uses getServerSideProps and ends with `.html`

**Result**

Page params are not passed to component properly.

**IMPORTANT**

This only happen with local non-prod development

### Expected Behavior

I would expect that params get sent to the component properly in a local dev environment with trailingSlash set to true, middleware enabled and a path that ends in `.html`

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by Escapado** [comment]
Might be related to https://github.com/vercel/next.js/issues/45340
