### ISSUE TITLE
Typesafe router query

### ISSUE THREAD

**Issue by judicaelandria** [vercel/next.js#45427]
### Describe the feature you'd like to request

It would be great if the router query is automatically typed so we don't need to type it manually

### Describe the solution you'd like

Let's say we have a dynamic page
- [id]
   - index.tsx

It should automatically pick the id and type the router query based on that(infer); we should have something like this 
```ts
const router = useRouter()
const id = router.query.id 
// the id is type string (depends on the dynamic page)
```

### Describe alternatives you've considered

Right now we need to always type it like this
```ts
const router = useRouter()
const id = (router.query as Record<"id",string>).id
```

**Comment by balazsorban44** [comment]
Hi, this would actually be kind of unsafe, since any property in `query` can be of type `string[]` if the param appears multiple times. This needs to be a runtime check to be on the safe side.

In the `app/` directory, router segments and search params are separate and should already be types
