### ISSUE TITLE
[NEXT-443] Can't use FullCalendar with Nextjs 13 from the app directory 

### ISSUE THREAD

**Issue by flyingfish04** [vercel/next.js#45435]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

-

### To Reproduce

1. run `npx create-next-app@latest --typescript`
2. run `npm install @fullcalendar/daygrid @fullcalendar/react`
3. try calling the calender from this path: `app/page.tsx`

### Describe the Bug

I want to use this package '@fullcalendar/react' in my nextjs app. 
I had the issue with the Global CSS before that was mentioned here #19936, so it was suggested to use Nextjs 13 with the /app directory.

So i installed Nextjs 13 app and when i tried to import it, it shows this error:

> TypeError: Class extends value undefined is not a constructor or null
> 
> This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components.

I don't see how the app directory should solve this when it won't let me call it from it and wants me to call it from a different directory. And it is not just this package, there are many that have this issue.

**Here is my project directory:**
![image](https://user-images.githubusercontent.com/117914797/215731465-58eeb2de-4099-4b64-ad45-3a56bd85f81d.png)

**Here is a simple page:**
> import FullCalendar from "@fullcalendar/react";
>
> export default function Home() {
>       return ( <main\> <FullCalendar/\> </main\> )
>}

**and here is my package:**
{
  "name": "test-nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@fullcalendar/daygrid": "^6.1.1",
    "@fullcalendar/react": "^6.1.2",
    "@next/font": "13.1.6",
    "@types/node": "18.11.18",
    "@types/react": "18.0.27",
    "@types/react-dom": "18.0.10",
    "eslint": "8.33.0",
    "eslint-config-next": "13.1.6",
    "next": "13.1.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.5"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.2.4"
  }
}

### Expected Behavior

Nextjs needs to sort this issue with the Global CSS imports from packages.

### Which browser are you using? (if relevant)

-

### How are you deploying your application? (if relevant)

-

<sub>[NEXT-443](https://linear.app/vercel/issue/NEXT-443/cant-use-fullcalendar-with-nextjs-13-from-the-app-directory)</sub>

**Comment by balazsorban44** [comment]
Hi, first as the error suggests, the library uses a class component that is only allowed in Client Components. You can add the `"use client"` directive at the top of the file or ask the author to add it in https://github.com/fullcalendar/fullcalendar-react/blob/main/src/index.tsx. 

Check out the docs to learn more: https://beta.nextjs.org/docs/rendering/server-and-client-components#when-to-use-server-vs-client-components
