### ISSUE TITLE
Cannot load plain markdown files using `@next/mdx` for server components

### ISSUE THREAD

**Issue by jajaperson** [vercel/next.js#45431]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 18.9.1
      npm: 8.19.3
      Yarn: 3.1.1
      pnpm: 6.22.2
    Relevant packages:
      next: 13.1.7-canary.0
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/tree/canary/examples/app-dir-mdx

### To Reproduce

1. Rename `app/message.mdx` to `app/message.md`
2. Update import in `app/page.tsx` accordingly.
3. `npm run dev`

### Describe the Bug

```
error - ./app/message.md
Module parse failed: Unexpected character ' ' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> # MDX as a Server Component
|
| This is a demo for rendering MDX as a server component.

Import trace for requested module:
./app/message.md
./app/page.tsx
```

### Expected Behavior

The [beta docs](https://beta.nextjs.org/docs/guides/mdx) seem to suggest that `@next/mdx` can be used with plain `.md` files as well, so you'd expect these alterations on the example project to make no visible changes to the page.

**Comment by balazsorban44** [comment]
By default `@next/mdx` only checks for the`.mdx` extensions

![image](https://user-images.githubusercontent.com/18369201/215773972-0afff67f-c138-460f-b3f5-7756f750d71a.png)

You can add support by the following change in your `next.config.js`:

```diff
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
    mdxRs: true,
  },
};

- const withMDX = require("@next/mdx")();
+ const withMDX = require("@next/mdx")({ extension: /\.mdx?$/ });
module.exports = withMDX(nextConfig);

```
