### ISSUE TITLE
Next build dynamic component ReferenceError

### ISSUE THREAD

**Issue by markjhvonk** [vercel/next.js#45447]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.19.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.7-canary.0
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue

https://github.com/markjhvonk/daypilot-next-bug

### To Reproduce

1. Run 'npm i'
2. Run 'npm run dev' to see the app working with the third-party component
3. Run 'npm run build' to see the successful build
4. Run 'npm uninstall next'
5. Run 'npm install next@canary' (13.1.7 is the latest version of next when writing this report)
6. Run 'npm run dev' to see the app working with the third-party component, but throwing the same error as the build.
7. Run 'npm run build' to see the build failing

### Describe the Bug

After upgrading Nextjs from 12.2.0 to the latest version (13.1.7 canary) the build stopped working and throws the following error during the 'Generating static pages' step: `ReferenceError: navigator is not defined`.
This error originates from a third party calendar module/component (DayPilot) which does not work with SSR. This is why I added the dynamic() import before exporting the component wrapper, which seemed to worked fine in v12.x.

I tried a couple of things already;
- Placing the dynamic() import in various different locations, also directly on the third party component itself.
- Migrating to the /app directory (on v13.x) and using the 'use client'; flag. This seemed to resolve the build error itself, but gave the same errors when running the build.
- Move from Babel to the SWC builder, this requires a bit more overhead on our side to sort out the rest of the libraries we use and TypeScript compatibility. Will test this a bit further in the test repo. 
  Update: For now switching to SWC (by removing babel.config.js) seems to fix the build, but it then also breaks in runtime (npm run start)

Thanks!

### Expected Behavior

I expect the build to pass and not fail because the behavior should not have changed for the dynamic() imports between v12 and v13.

### How are you deploying your application? (if relevant)

next start

**Comment by huozhi** [comment]
We had some fixes in 13.2, I can't repro this with next latest (13.2.x) anymore, can you upgrade to latest next to give it a try? Thanks

**Comment by markjhvonk** [comment]
@huozhi Thanks for the response. I can confirm that the build now works on version 13.2.4.
However when I run `npm run start` afterwards, the application still crashes when I go to a page where the third party component is used. It gives the error `TypeError: o.DayPilot.Date is not a constructor`. I encountered this error before and was able to avoid this by using the dynamic import (like I mentioned in the issue).
I again tried to apply the `'use client';` line as suggested in the [nextjs documentation](https://beta.nextjs.org/docs/rendering/server-and-client-components#rendering-third-party-context-providers-in-server-components), but this also makes no difference.
Running the app with `npm run dev` still works fine...
Thanks again!

**Comment by huozhi** [comment]
@markjhvonk Appreciate if you can file a new issue with the new reproduction, thanks
