### ISSUE TITLE
next/font wrong font on the initial request, doesn't swap to the right one

### ISSUE THREAD

**Issue by borispoehland** [vercel/next.js#45475]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  Operating System:
    Platform: darwin
    Arch: arm64
    Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
  Binaries:
    Node: 16.17.0
    npm: 8.15.0
    Yarn: 1.22.19
    pnpm: 7.25.1
  Relevant packages:
    next: 13.1.7-canary.1
    eslint-config-next: 13.1.1
    react: 18.2.0
    react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (@next/font)

### Link to the code that reproduces this issue

https://github.com/borispoehland/font-repro

### To Reproduce

Deploy the repository on Vercel (or any other hosting provider) and open the link

### Describe the Bug

Sometimes when opening the link, the font is wrong (e.g. sans-serif) instead of the font specified by next/font. It does never swap to the correct font. The only way to solve the problem is by reloading the page, then the correct font is shown right away.

It happens very unregularly and across all browsers. Most of the time, it happens when you first open the link using your browser or device. The loading time is longer as well then

I was able to catch a error message from my Firefox console:
```
downloadable font: font-display timeout, webfont not used (font-family: "__Poppins_f49817" style:normal weight:400 stretch:100 src index:0) source: https://font-repro.vercel.app/_next/static/media/916d3686010a8de2.p.woff2
```

It seems like it happens in conjunction with a blocking script in `_document.js`. Sometimes though, blocking scripts are needed, e.g. for a proper dark mode or in `react-wrap-balancer`.

Note also how I injected the font using `<style jsx global>` on the `html` because otherwise it wouldn't stick to elements outside of the Layout, e.g. Portals.

Attached is an instance where I catched the font error when I opened the page on my iPhone:
![IMAGE 2023-02-01 11:10:18](https://user-images.githubusercontent.com/60541010/216013892-01989f93-b77b-45ea-b64c-7d794851ac19.jpg)

Live demo (maybe you catch the error there): https://font-repro.vercel.app/

### Expected Behavior

No matter how long the page blocks or the server responds, the selected webfont should always display after it's loaded and never "stuck" until you need to reload the page manually

### How are you deploying your application? (if relevant)

Vercel

**Comment by hanneslund** [comment]
Try changing the [display](https://nextjs.org/docs/api-reference/next/font#display) to `swap` to always swap to the downloaded font when ready, even if it loads slow.

**Comment by borispoehland** [comment]
> Try changing the [display](https://nextjs.org/docs/api-reference/next/font#display) to `swap` to always swap to the downloaded font when ready, even if it loads slow.

That is already the default, isn’t it?

**Comment by thexpand** [comment]
@borispoehland Sadly, it isn't. The documentation seems to be wrong. I tested this myself yesterday and it seems that the default is `optional`. Try removing the `display` option from the font configuration and then check the `style` tag in the `head` to see the `display: optional;` added to the loaded fonts.

**Comment by shhmon** [comment]
I'm experiencing the same issue, and setting `display: 'swap'` explicitly seems to resolve the issue.

Upon reading the next/font api reference, I'm having a hard time understanding the relevance of the [adjustFontFallback](https://nextjs.org/docs/api-reference/next/font#adjustfontfallback) option (I'm using google fonts). What's the difference between setting `display: 'block'` and `adjustFontFallback: false` in this context? Seems to me that the end result would be the same. Could someone clarify?

**Comment by charkour** [comment]
In Next v13.2, `display: 'swap'` is the [default](https://nextjs.org/blog/next-13-2#other-improvements).

**Comment by mwawrusch** [comment]
I am experiencing an issue (twice so far) that might be related:
When during build time in dev the font can't be loaded from google (maybe internet request failed) then it falls back to times roman and the only way to fix it is to delete the .next/static/media folder.

This happens at least up until 13.2.4
