### ISSUE TITLE
appDir: Module resolution error when using a RSC

### ISSUE THREAD

**Issue by kasvith** [vercel/next.js#45485]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.26.0
    Relevant packages:
      next: 13.1.7-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/kasvith/next13-remirror-react-renderer-error.git

### To Reproduce

- Run the project
- Visit [http://localhost:3000](http://localhost:3000)

### Describe the Bug

I want to render React Nodes with React Remirror Renderer(it doesn't load the Editor and produces React Nodes from a given JSON, similar to how MDX works)

So i wanted to use it as a Server Component,
This gives me a weird error like 

```
error - ./node_modules/@remirror/core-utils/dist/remirror-core-utils.js
Attempted import error: 'includes' is not exported from '@remirror/core-helpers' (imported as 'includes').

Import trace for requested module:
./node_modules/@remirror/core-utils/dist/remirror-core-utils.js
./node_modules/@remirror/core/dist/remirror-core.js
./node_modules/@remirror/preset-react/dist/remirror-preset-react.js
./node_modules/@remirror/react/dist/remirror-react.js
./src/app/page.tsx
```

But the `includes` from  `@remirror/core-helpers` is already an exported member.
If i switch to `use client`, it works fine and renders content

### Expected Behavior

To provide a better error or solve this if can

**Comment by shuding** [comment]
After some investigation it seems to be from `node_modules/get-dom-document/lib/get-dom-document.node.mjs` which imports `module`:

```js
import { createRequire } from "module";
```

...and it can't be bundled. Quick workaround is to have `experimental.serverComponentsExternalPackages: ['@remirror/react']` in your `next.config.js` but we will still try to address it inside Next.js.

**Comment by kasvith** [comment]
Thanks for insight @shuding

**Comment by kasvith** [comment]
@shuding can you point me a file which uses it
I thought current imports doesn't use any state

**Comment by shuding** [comment]
@kasvith `render.tsx` imports `@remirror/react`, which imports `@remirror/extension-react-component` and it has `useState` inside `extension-react-component/src/portals/react-portals.tsx`.

**Comment by kasvith** [comment]
aha, thanks
