### ISSUE TITLE
Next.js doesn't support Node 18 if browserslist is set, because node-releases are being compiled into the dist folder with outdated data

### ISSUE THREAD

**Issue by rdsedmundo** [vercel/next.js#45492]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.18
      pnpm: 7.26.2
    Relevant packages:
      next: 12.3.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Package manager (npm, pnpm, Yarn)

### Link to the code that reproduces this issue

N/A

### To Reproduce

- Add browserslist: node 18 to package.json, while using Next.js 12.3.4.

### Describe the Bug

https://unpkg.com/next@12.3.4/dist/compiled/cssnano-simple/index.js

If you search on this file for 17.4.0 you can see that this is the latest Node.js version included there. Why is this even bundled on the package directly? It took my ages to figure it out that the issue was there, previously I was forcing my package manager resolution to install the latest version of node-releases/browserslist that for sure had Node.js 18 included, but because you're inlining the versions during pre-publish it didn't have any effect.

### Expected Behavior

The versions should not be inlined during pre-publish. Upgrading to Next.js 13 / canary should not be a solution here, because a simple thing like this shouldn't require a major upgrade, besides your website says "minimum Node version", which suggests that anything upward should work assuming no major deprecations (which is the case with Node 18).

**Comment by rdsedmundo** [comment]
Apparently it's also a problem even on Next.js 13 latest: https://unpkg.com/next@13.1.6/dist/compiled/cssnano-simple/index.js

This list shouldn't really be compiled.

**Comment by SukkaW** [comment]
@rdsedmundo Would you like to share a reproduction with us? Even though I totally understand your issue, I still want to have a re-production so that I can test if my fix works.

**Comment by rdsedmundo** [comment]
Literally just setting package.json#browserslist to `node 18` will do it, in any Next project. This is unusual because in a next app you'd want to target browsers, of course. But this was not intentional, as I had this config in the monorepo and the next app was inheriting it from the root, but in any case the failure here shouldn't have been "node 18" is not supported but either something else should be thrown or no error should appear at all.

**Comment by SukkaW** [comment]
@rdsedmundo Would you like to verify if your issue has been fixed **after a new canary release that includes my PR is released**?
