### ISSUE TITLE
Async page does not work alonside 'use client'

### ISSUE THREAD

**Issue by Nefcanto** [vercel/next.js#45544]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
    Binaries:
      Node: 18.13.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.7-canary.4
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/Nefcanto/Next13AsyncPageUseClient

### To Reproduce

- Create a default next 13 app, and enable the app directory
- Remove the entire `page.js` (home page) code, and replace it with:
```
'use client'

const Home = async () => {
	return <h1>hi</h1>
}

export default Home
```
- You should see this error:
> Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

- Now remove the `async` or `'use client'`. It should work now.

### Describe the Bug

We should change the page function to async if we want to load data on a page.

```
const Home = async () => {
    const data = await fetch('some_api')
    const json = await data.json()
    return <h1>hi</h1>
}
```

We should also use state management or effects on this page. Then we should decorate it with `'use client'`.

But if we do that, we get this error:

> Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

### Expected Behavior

We should be able to:

1. Load data inside a page (use `async` keyword)
2. Manage state inside that page (use `useState`)

**Comment by balazsorban44** [comment]
Hi, this is expected as only Server Components can be `async`.

For client components, you can use the `use` hook to unwrap promises.

Check out https://beta.nextjs.org/docs/rendering/server-and-client-components and 
https://github.com/acdlite/rfcs/blob/first-class-promises/text/0000-first-class-support-for-promises.md#example-use-in-client-components-and-hooks

**Comment by Nefcanto** [comment]
Can we have a complete example of how to do this? An example that contains `import` from the top. A fully functional `page.js` example that we can copy/paste into our code to test.
