### ISSUE TITLE
[NEXT-454] CSS modules in pages not reloaded properly when appDir enabled

### ISSUE THREAD

**Issue by JanKaifer** [vercel/next.js#45553]
repro: https://github.com/JanKaifer/next-repro-[next-454](https://linear.app/vercel/issue/NEXT-454/css-modules-in-pages-not-reloaded-properly-when-appdir-enabled)-2.git

When running in `dev` mode, styles will break when navigating between pages.

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-454](https://linear.app/vercel/issue/NEXT-454/css-modules-in-pages-not-reloaded-properly-when-appdir-enabled)</sub>

**Comment by karlhorky** [comment]
Maybe this was fixed by https://github.com/vercel/next.js/pull/45619 ?
