### ISSUE TITLE
[NEXT-457] Remove non-determinism from order of font includes

### ISSUE THREAD

**Issue by JanKaifer** [vercel/next.js#45559]
I dug into this and found one source of nondeterminism caused by `Set`.
The rest may be caused by different node versions (I was not able to get 16.19 working locally).

I'll create a new ticket to investigate this further, but let's not hold this PR with it.

_Originally posted by @JanKaifer in https://github.com/vercel/next.js/issues/45487#issuecomment-1416121891_
            

<sub>[NEXT-457](https://linear.app/vercel/issue/NEXT-457/remove-non-determinism-from-order-of-font-includes)</sub>

**Comment by feedthejim** [comment]
@JanKaifer is this being fixed in the PR now?

**Comment by JanKaifer** [comment]
Nope
