### ISSUE TITLE
next-swc: SVG `<path>` identified as usage of `node:path` import

### ISSUE THREAD

**Issue by karlhorky** [vercel/next.js#45561]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Feb 03 2023 18:38:16 GMT+0100 (Central European Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.1.7-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-npuob3?file=package.json

### To Reproduce

1. Open the StackBlitz above (start the dev server with `yarn dev` if it doesn't start on its own)
2. See the `UnhandledSchemeError` error message about usage of `node:path` in the client, although it is not used there
3. Remove the `<path>` from the JSX and observe the error message disappear

![Screenshot 2023-02-03 at 18 34 30](https://user-images.githubusercontent.com/1935696/216671177-6c104739-be8e-464b-9d9d-8c80ea1c87b0.png)

### Describe the Bug

The SVG `<path>` in the React component is incorrectly identified as a usage of `node:path` (which is actually an unused identifier), causing the `UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme)` error message (which normally occurs when the `path` import is used in a client-side component).

cc @kdy1 from https://github.com/vercel/next.js/pull/45149#issuecomment-1401771364

### Expected Behavior

Any HTML or SVG tags which have the same name as unused identifiers should not be identified as usages of an identifier

**Comment by kdy1** [comment]
Oh I think this can be an issue of swc core modules. I'll check it tomorrow.

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/pull/6911 will fix this

**Comment by karlhorky** [comment]
Ok great, thanks! I think this is still unreleased, but if the versioning will use semver I guess it seems like it will probably be version `1.3.33` or `1.4.0`.

We can leave this open until the Next.js version also includes this swc version.

**Comment by kdy1** [comment]
Fixed by https://github.com/vercel/next.js/pull/45776

**Comment by karlhorky** [comment]
Thanks! Confirmed that this was fixed in one of the latest canary versions!

https://stackblitz.com/edit/nextjs-kzstkn?file=pages%2Findex.tsx&file=yarn.lock

<img width="1318" alt="Screenshot 2023-02-14 at 10 43 42" src="https://user-images.githubusercontent.com/1935696/218698407-d053e6d7-5040-40bb-99a2-4d814c572fa2.png">
