### ISSUE TITLE
Make Component Folder in App Directory for General Component ex. Button

### ISSUE THREAD

**Issue by novalmurtado** [vercel/next.js#45598]
### Describe the feature you'd like to request

I want there to be a folder called `components` in the `app` directory which contains a collection of client component files that are widely used in various pages such as Button Component.
e.g.
```
./app/components/Button.jsx
./app/components/Sidebar.jsx
```

### Describe the solution you'd like

because like the Button Component which is widely used on various web pages, I want to easily import it such as

```
import Button from "@/app/components/Button"
import Sidebar from "@/app/components/Sidebar"
```

I also hope that the folder named components can reduce the bundle size created because the button component is part of the client component which is used on various pages such as the login page and register page.

the components folder contains a collection of client component files that are commonly used in various web pages. in the hope of reducing the bundle size on production

### Describe alternatives you've considered

N/A

**Comment by RemVN** [comment]
you can use parenthesis folder name, eg: (components) and place components inside of them.

**Comment by Willem-Jaap** [comment]
You can also just add a folder to your project root, or `src/` with these components. I'm not sure if you would want everything inside your `app` directory. I've been experimenting with different ways to structure globally reusable components/hooks/functions. You can take a look: [next-foundation](https://github.com/Willem-Jaap/next-foundation)

If anyone has other suggestions or ways to do this, please let me know!

**Comment by novalmurtado** [comment]
okay thanks for the advice from all of you. I think sometimes it does need a foundation that can be a standard so that it makes it easier when going to start
