### ISSUE TITLE
[NEXT-640] force-dynamic broken for catch-all routes

### ISSUE THREAD

**Issue by cipriancaba** [vercel/next.js#45603]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.13.1
    Relevant packages:
      next: 13.1.7-canary.5
      eslint-config-next: 13.1.7-canary.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-7xai7h?file=app%2F[variant]%2F(shop)%2Fp%2F[[...id]]%2Fpage.tsx

### To Reproduce

The page is explicitly set as dynamic so it can fetch data on server side

When running the app, the following error is thrown
```
Error: Page changed from static to dynamic at runtime /test/p
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
```
This page shouldn't be marked as static since 
```
export const dynamic = 'force-dynamic';
```
Dynamic params is also not respected, giving 404 on random routes /test/p/random
```
export const dynamicParams = true;
```
The problem happens even without the `[variant]` segment in the repro, but kept it there to make sure it matches our current working environment

### Describe the Bug

Nextjs incorrectly marks a `force-dynamic` page as `static` causing runtime error
This seems to have been introduced in `13.1.3`

### Expected Behavior

The page should be dynamic, fetch should work

Probably related to #45068 #44860

<sub>[NEXT-640](https://linear.app/vercel/issue/NEXT-640/force-dynamic-broken-for-catch-all-routes)</sub>

**Comment by andrew840513** [comment]
was working with v13.1.6-canary.0 broke again at v13.1.6-canary.1 to v13.1.6-canary.6

**Comment by AdisonCavani** [comment]
Same.
`13.1.7-canary.28` - Error: Page changed from static to dynamic at runtime
`13.1.7-canary.27` - working fine

**Comment by hiddenest** [comment]
same at `13.1.2` too (upgraded from `13.1.6`)

**Comment by cmngan** [comment]
Same issue happens in `13.2.1`

**Comment by AlexisWalravens** [comment]
> Same. 
> `13.1.7-canary.28` - Error: Page changed from static to dynamic at runtime 
>`13.1.7-canary.27` - working fine

I have the same issue but I don't use `export const dynamic = 'force-dynamic'`

I just have `export const revalidate = 60` in a catch-all routes page.

Edit:
However if I remove the **`generateStaticParation`** it works again.

**Comment by coopernewby** [comment]
> However if I remove the **`generateStaticParation`** it works again.

Same issue on 13.2.1

**Comment by AlexisWalravens** [comment]
Seems to be fixed on `13.2.3` didn't tested on `13.2.2`.

**Comment by hk86** [comment]
Same error on 13.2.2, but fixed on 13.2.3. Thanks!

**Comment by TheCodby** [comment]
I have the same problem but when i put `cache: "no-cache"` with fetch(), and `export const dynamic = "force-static";`

**Comment by shuding** [comment]
Just tested it and it works fine with `13.2.5-canary.12`. Will add a test case to ensure.
