### ISSUE TITLE
next/dynamic doesn't render its imported component immediately after import

### ISSUE THREAD

**Issue by phuctm97** [vercel/next.js#45688]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.18.0
      npm: 9.2.0
      Yarn: 1.22.19
      pnpm: 7.24.2
    Relevant packages:
      next: 13.1.7-canary.7
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue

https://github.com/phuctm97/repro-next-dynamic-issue

### To Reproduce

Clone the repro repository, there is explanation inside where/what/why issue is happening. Search for "[BUG]" when you open the repo to start with.

### Describe the Bug

I created a wrapper around `next/dynamic` below to wait for a Context value to be ready & found 2 bugs.

```tsx
import type { Loader } from "next/dynamic";
import type { FC } from "react";
import nextDynamic from "next/dynamic";
import { useContext } from "react";
import { Context } from "@/components/provider";

export function dynamic<P extends JSX.IntrinsicAttributes>(
  loader: Loader<P>
): React.ComponentType<P> {
  const NextDynamicComponent = nextDynamic(loader, { suspense: true });
  const CustomDynamicComponent: FC<P> = (props) => {
    if (typeof window === "undefined") throw new Error(); // Suspend the component during SSR
    const context = useContext(Context);
    if (!context)
      // Suspense the component until Context is ready
      throw new Promise((resolve) => window.setTimeout(resolve, 200));
    return <NextDynamicComponent {...props} />;
  };
  return CustomDynamicComponent;
}
```

There are 2 bugs happened:

1. Throw Error during SSR should NOT be considered an error, it's how to suspend a component during SSR. However, Next.js is showing error both in console & in Next.js error overlay. This issue has been reported before https://github.com/vercel/next.js/issues/35564 but it happens again now.

3. The `next/dynamic` returned component doesn't seem to be rendered immediately instead something is being rendered first which cause any wrapping <Suspense /> to fail to maintain its fallback state & cause flashing effects. Run the repro repo you'll see the flashing effect, it should NOT happen. This issue doesn't happen in next@13.0.6.

### Expected Behavior

1. Throw Error during SSR should NOT be considered an error, it's how to suspend a component during SSR.

3. The `next/dynamic` returned component should render its component immediately & if its component suspends immediately, any wrapping <Suspense /> to should maintain its fallback state (no flashing effect).

### Potential Cause

I have looked into changes since 13.0.7 and it seems like `LazyImpl` was completely replaced by `LoadableImpl` which is causing both issues.

**Comment by phuctm97** [comment]
@huozhi This is related to this issue: https://github.com/vercel/next.js/issues/44083#issuecomment-1419024241.

**Comment by huozhi** [comment]
Was also mentioned in the previous fixing PR that since We're deprecating `suspense` option now, so you can directly use  `React.lazy` and `Suspense` for your case, since you also asked for the dynamic `fallback` component. So you can just replace `next/dynamic` with these React primitives for this case.

**Comment by phuctm97** [comment]
@huozhi I'm actually using lazy & Suspense to workaround the issue now, think it is a great feature for next/dynamic to fully support Suspense out of the box.

The 1st bug is still there even if I use `lazy`. Throwing error to suspend during SSR still causes console error logs in both on browser console & server-side console despite everything is working fine . I'm not sure if this is a React bug or Next.js bug.

**Comment by huozhi** [comment]
Throwing the custom error could break hydration. Unless you have a error boundary wrapping it.

You've wrapped the extra Suspense boundaries for it when using `next/dynamic` [here](https://github.com/phuctm97/repro-next-dynamic-issue/blob/157e62106dd249b4e43f10be35cfae3c1cf8d613/components/provider/index.tsx#L11-L13). `next/dynamic` will stay like before without mixing with react primitive Suspense. If you need to introduce extra suspense boundaries, use `React.lazy`.

**Comment by phuctm97** [comment]
> Throwing the custom error could break hydration. Unless you have a error boundary wrapping it.
> 
> You've wrapped the extra Suspense boundaries for it when using `next/dynamic` [here](https://github.com/phuctm97/repro-next-dynamic-issue/blob/157e62106dd249b4e43f10be35cfae3c1cf8d613/components/provider/index.tsx#L11-L13). `next/dynamic` will stay like before without mixing with react primitive Suspense. If you need to introduce extra suspense boundaries, use `React.lazy`.

I understand if you/Next.js team want `next/dynamic` to stay as is and don't fully support Suspense because custom solution can always be implemented. However, throw error during SSR should be a bug because in React docs it is how to suspend SSR. If a component is suspended during SSR, it should be suspended during hydration too (by throwing promise) and it will resolve only after mount, hence there won't be hydration issue.

The only bug right now is that suspending during SSR is still annoyingly console error everywhere, which it shouldn't.

**Comment by phuctm97** [comment]
@huozhi Would appreciate your help in regards to suspending during SSR 🙏.

**Comment by huozhi** [comment]
app dir supports the streaming and suspense with correct implementation. `pages/` will remain static rendering after 13.2.
`next/dynamic` also supports suspense in app dir with a different implementation.

The issue for your use case is it can't throw a custom error for suspense as it will cause error in hydration since it's not **allowed errors**, otherwise all kinds of errors might be swallowed on client. As `pages/` become static rendering now so I think this can't be done.

The only way to have suspense now is in app dir, and you have a `<ErrorBoundary>` for your suspense boundary to catch the error, the layout for that page should remain as dynamic rendering as well, so error won't throw during static optimization.
