### ISSUE TITLE
[NEXT-517] Breakpoint not getting hit in VSCode with Next.js debugger config

### ISSUE THREAD

**Issue by InfiniteLearner** [vercel/next.js#45697]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.7-canary.7
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/InfiniteLearner/debug_error_next_reproduction

### To Reproduce

!!!!!!!!!!!!!!!!!!!!! You should be using node v 16.14.2 !!!!!!!!!!!!!!!!!!!!

(Because of other constraints I can not update my node version so this is not an option)

Create a new next.js app 
```npx create-next-app@latest```
Use every default options

Add a new config for debugging in vsCode (.vscode/launch.json):
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Next.js: debug server-side",
        "type": "node-terminal",
        "request": "launch",
        "command": "npm run dev"
      },
      {
        "name": "Next.js: debug client-side",
        "type": "chrome",
        "request": "launch",
        "url": "http://localhost:3000"
      },
      {
        "name": "Next.js: debug full stack",
        "type": "node-terminal",
        "request": "launch",
        "command": "npm run dev",
        "serverReadyAction": {
          "pattern": "started server on .+, url: (https?://.+)",
          "uriFormat": "%s",
          "action": "debugWithChrome"
        }
      }
    ]
  }
```

Create a new async function in index.tsx and call it (with an onClick for example):
```
async function greeting(){
    console.log("Hello");
    console.log("Goodbye");
  }

...

<p onClick={greeting}></p>
...
```

Add a new breakpoint in the function.
![2023-02-08_11h49_26](https://user-images.githubusercontent.com/29714758/217508897-9d54afc1-9378-4fd9-828c-e84f03fce5c3.png)

Run in debug mode (either server-side, client-side or fullstack).

### Describe the Bug

On click of the element, the logs will be displayed without being stop.
The breakpoints are not getting hit.

![2023-02-08_11h50_08](https://user-images.githubusercontent.com/29714758/217509064-40b3aacc-d36d-494f-9c9a-15b0f2826cb0.png)

It should be noted that breakpoints on the returned component are working fine but none in functions.
So if you had a breakpoint on your div (or any other component) it will stop.

### Expected Behavior

The breakpoints should get hit and the logs not be displayed.

<sub>[NEXT-517](https://linear.app/vercel/issue/NEXT-517/breakpoint-not-getting-hit-in-vscode-with-nextjs-debugger-config)</sub>

**Comment by naut305** [comment]
Up+. I got the same issue. Can not hit breakpoints

**Comment by jonleung** [comment]
I'm having the same problem.

My debugger attaches, it just doesn't stop at a breakpoint

Operating System:
      Platform: OSX
      Arch: x64
      Version: Ventura
    Binaries:
      Node: v18.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

**Comment by balazsorban44** [comment]
Hmm. I cannot reproduce the OP's issue, we will need to look more into this. @InfiniteLearner attaching a reproduction would be very helpful. :pray:

**Comment by jonleung** [comment]
Here is me reproducing the issue with Next.js v13.2.3 but I also tested 13.2.2, 13.2.1 13.1.6, 12.3.4 and I could not get anything to trigger a breakpoint:

Here is me starting with `npx create-next-app@latest` today: https://capture.dropbox.com/sSSjb6nxQGN4Yl43

**Comment by HelmerBarcos** [comment]
Im also having this problem with all Next.js versions mentioned above. 
VScode version  `1.76`

**Comment by HelmerBarcos** [comment]
For the next.js version `13.1.6` it will start 2 debuggers. 1 on port `9229` and another one on port `9230`

Inside the package.json 

```
    "dev": "NODE_OPTIONS='--inspect' next dev",

```

Inside the `launch.json`

```
    {
      "name": "Attach",
      "address": "127.0.0.1",
      "port": 9230,
      "request": "attach",
      // "localRoot": "${workspaceFolder}/frontend", # just if next app is not inside your root dir
      "skipFiles": ["<node_internals>/**"],
      "type": "node"
    }
```

If you now attach the vscode debugger, it will recognize breakpoints

**Comment by gregmartyn** [comment]
`--inspect=0.0.0.0:9229` doesn't work anymore because https://github.com/vercel/next.js/blob/canary/packages/next/src/cli/next-dev.ts#L524 assumes it can do `debugPort + 1` with `debugPort = "0.0.0.0:9229"`

**Comment by gregmartyn** [comment]
Opened a separate issue for that: https://github.com/vercel/next.js/issues/47083

**Comment by ukabu** [comment]
> For the next.js version `13.1.6` it will start 2 debuggers after running `npm run dev`. 1 on port `9229` and another one on port `9230`
> 
> ### 1️⃣ without dockerized nextjs app
> Inside the package.json
> 
> ```
>     "dev": "NODE_OPTIONS='--inspect' next dev",
> ```
> 
> Inside the `launch.json`
> 
> ```
>     {
>       "name": "Attach",
>       "address": "127.0.0.1",
>       "port": 9230,
>       "request": "attach",
>       // "localRoot": "${workspaceFolder}/frontend", # just if next app is not inside your root dir
>       "skipFiles": ["<node_internals>/**"],
>       "type": "node"
>     }
> ```
> 
> If you now attach the vscode debugger, it will recognize breakpoints

Node v19.7.0
Next.js v13.2.4

Tried this, yet breakpoints are still no go.

In a `.ts` file:

![image](https://user-images.githubusercontent.com/95629/227722821-82af4b9f-906c-48ea-ad8f-a726fbe7446f.png)

```
> bio-trousse@0.1.0 dev
> NODE_OPTIONS='--inspect' next dev

Debugger listening on ws://127.0.0.1:9229/c488c6b0-d0ad-462a-960b-0d46b92016e0
For help, see: https://nodejs.org/en/docs/inspector
warn  - the --inspect option was detected, the Next.js server should be inspected at port 9230.
Debugger listening on ws://127.0.0.1:9230/520830bc-1763-4201-a714-a034dcb30c1d
For help, see: https://nodejs.org/en/docs/inspector
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /workspaces/bio-trousse/.env.local
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
Starting inspector on 127.0.0.1:9229 failed: address already in use
event - compiled client and server successfully in 1778 ms (262 modules)
wait  - compiling...
event - compiled client and server successfully in 504 ms (262 modules)
```

**Comment by ukabu** [comment]
I even tried the vscode auto attach feature which attach to all processes (3) when running `npm run dev` and breakpoints are not good either.

![image](https://user-images.githubusercontent.com/95629/227723091-30087e00-aeff-493d-b910-777955c383e8.png)

```
Debugger listening on ws://127.0.0.1:53266/376fb431-e929-47d4-9164-15e2b60c00e6
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> bio-trousse@0.1.0 dev
> next dev

Debugger listening on ws://127.0.0.1:53307/a2c5dd46-85ea-44b7-9dcb-503d480fb1bf
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:53096/0ade082a-860f-4fe7-820f-decf43d8f1db
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /workspaces/bio-trousse/.env.local
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

Debugger listening on ws://127.0.0.1:53243/86f557ca-e973-46cd-ba81-11724d58615d
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
event - compiled client and server successfully in 1882 ms (262 modules)
wait  - compiling...
event - compiled client and server successfully in 585 ms (262 modules)
```

**Comment by ukabu** [comment]
Ok, scratch that, with auto attach, it did manage to hit a break point after reloading the app in the broswer.

**Comment by asafpelegcodes** [comment]
Just wondering how is this not a huge problem for tons of people or why isn't it getting much attention from authors?

**Comment by juhahe** [comment]
Not sure about the OP, but I think later commenters are experiencing this [issue](https://github.com/vercel/next.js/issues/48767) with the current version of next.js. The issue is that `next` starts several `node` processes and the debug server is started on the wrong `node` process. That process does not execute the code where the breakpoint is set, so the debugger never pauses the execution. That's why @ukabu had success with "auto attach feature which attach to all processes". I'm not familiar with this feature myself but attaching the debugger to the process that actually executes the code with the breakpoint would seem to work.

**Comment by NullReferenceEric** [comment]
Good point.  @ukabu can you detail your attach to all processes workflow?

**Comment by ukabu** [comment]
Just set the `Javascript: Auto attach filter` to `Always` in your workspace or user settings.

![image](https://github.com/vercel/next.js/assets/95629/af386adf-d13f-4be0-84ff-ca303cdee2cf)

**Comment by LieAlbertTriAdrian** [comment]
Facing the same issue here

**Comment by Cow258** [comment]
It is worth noting that
We can't hit the breakpoint on the first execution
because the file does not exist there yet or was not compiled
In most cases, the breakpoint can only be triggered normally during the second execution

**Comment by lu-zen** [comment]
Manually attaching works here:
```
- info the --inspect option was detected, the Next.js server for app should be inspected at port 32957.
- info the --inspect option was detected, the Next.js server for pages should be inspected at port 35423.
```
Using `CMD+SHIFT+P` then `Debug: Attach to Node process` and selecting the corresponding process.
Didn't have any luck launching via debugger, it attaches to the wrong proccess.

**Comment by cesarvarela** [comment]
> Just wondering how is this not a huge problem for tons of people or why isn't it getting much attention from authors?

This is really baffling, but the reason is that most devs don't know how to use debuggers and rely mostly on logs which is soo inefficient. It is a lost battle at this point.

**Comment by nicu-chiciuc** [comment]
A thing that doesn't seem to be mentioned is that I'm able to stop the execution in a server function by adding a `debugger` statement.
Waiting for the first execution to pass then waiting for the 2nd one to attach doesn't seem to work for me.

The issue with the `debugger` (and I assume breakpoints) is that it stops in a file that has the same contents and name as the actual function file, but it's not the same file (?!).

Note that the file with the debugger doesn't show Git diffs nor breadcrumbs.

<img width="805" alt="Screenshot 2023-07-06 at 11 33 07" src="https://github.com/vercel/next.js/assets/4076804/c3148afc-87ad-4562-b5fa-47260f18dd23">

<img width="859" alt="Screenshot 2023-07-06 at 11 33 01" src="https://github.com/vercel/next.js/assets/4076804/df9b78c3-bbcf-4c28-8738-044b29458e39">


I'm using Turborepo so that might add other issues into the mix. I think it would be worth having a sample Next.js repo with clear instructions on how to debug the code.
