### ISSUE TITLE
Docs: Create a Next.js App

### ISSUE THREAD

**Issue by marcos-jesus** [vercel/next.js#45790]
### What is the improvement or update you wish to see?

Page 2, in Next <=12 have a screen writing Welcome to NextJS.

Have a ask quick review is don't updated.
What text do you see on the page?

have two answer: 

A: Welcome to Next.js! 
B: Hello Next.js!

there really is no right answer.

### Is there any context that might help us understand?

documentation is don't update

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/create-nextjs-app/setup

**Comment by Rishab49** [comment]
I installed the latest version(without turbopack) right now and I see "Welcome to nextjs".
