### ISSUE TITLE
nextAuth POST request to internal API returns 400 status code. 

### ISSUE THREAD

**Issue by Alfredoeb9** [vercel/next.js#45798]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

      next: 12.2.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://next-auth-app-test.vercel.app/register

### To Reproduce

  "dependencies": {
    "bcryptjs": "^2.4.3",
    "formik": "^2.2.9",
    "next": "12.2.2",
    "next-auth": "^4.10.0",
    "nodemailer": "^6.9.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icons": "^4.7.1"
  },

### Describe the Bug

I'm trying to do a fetch POST request to my internal api/signup.js but once i uploaded application to vercel I am receiving a 400 status code but everything works perfect locally. Any Idea why this happens? I've tried the most recent packages for next and next-auth and I even downgraded to above dep.

It fails on my fetch call

`fetch("/api/auth/signup", {
                                    method: "POST",
                                    headers: {
                                        "Content-Type": "application/json, text/plain, */*",
                                        "User-Agent": "*"
                                    },
                                    body: JSON.stringify(r)
                                });`

### Expected Behavior

User inputs email and password and once presses register, sends a POST request to my /api/signup page which calls mongo. 

### How are you deploying your application? (if relevant)

vercel

**Comment by yutakobayashidev** [comment]
Is this related to this issue?

https://github.com/orgs/vercel/discussions/1493

**Comment by Alfredoeb9** [comment]
> Is this related to this issue?
> 
> https://github.com/orgs/vercel/discussions/1493

It possibly could be related

**Comment by pdparchitect** [comment]
This should have been a P0 incident but no. I imagine lots of people had their apps completely broken due to whatever change caused this issue and rollback is no aways the option (in particular when secrets need to be rotated).

**Comment by balazsorban44** [comment]
Hi, could you reopen this on https://github.com/nextauthjs/next-auth instead, if the issue is still happening? :pray: This is unlikely a Next.js issue.
