### ISSUE TITLE
createStore is deprecated in store.js when using with NextJS and TypeScript

### ISSUE THREAD

**Issue by jeet-khondker** [vercel/next.js#45838]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.4
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript

### Link to the code that reproduces this issue

This is a private repository.

### To Reproduce

[
<img width="1032" alt="Screen Shot 2023-02-13 at 11 36 40" src="https://user-images.githubusercontent.com/48243450/218358009-661847d0-2dc1-4149-a5c2-a64a9efff225.png">
](url)

### Describe the Bug

When I tried to use `createStore` of Redux in NextJS and TypeScript, the following error is displayed.
`createStore` is deprecated currently.
VS Code is recommending to use `configureStore` from Redux Toolkit instead of `createStore`

```
@deprecated
We recommend using the configureStore method of the @reduxjs/toolkit package, which replaces createStore.

Redux Toolkit is our recommended approach for writing Redux logic today, including store setup, reducers, data fetching, and more.

For more details, please read this Redux docs page: https://redux.js.org/introduction/why-rtk-is-redux-today

configureStore from Redux Toolkit is an improved version of createStore that simplifies setup and helps avoid common bugs.
```

### Expected Behavior

I expected createStore not to be deprecated.

### Which browser are you using? (if relevant)

Google Chrome

**Comment by sairajchouhan** [comment]
Hey, @jeet-khondker the deprecation message is because the method `createStore` has been marked as deprecated inside of `redux`. So no matter whether you use `Next.js`, ' create-react-app`, or anything else, you will see that deprecation message.

**Comment by jeet-khondker** [comment]
Hi @sairajchouhan 
What will be the alternative issue to use `createStore` in `store.js`? Because the Github code is using that `createStore` which is deprecated. So this issue need to be solved with correct code in `store.js`

**Comment by sairajchouhan** [comment]
Ya, if you want more guidance on that, you can open a discussion in the redux repository here https://github.com/reduxjs/redux/discussions/new?category=help

if this helps, kindly close the issue here :)

**Comment by jeet-khondker** [comment]
Until the correct code in `store.js` has been provided, how can I close this issue?
Is the code in `store.js` has been provided? If that is so, I will close this issue then.

**Comment by balazsorban44** [comment]
I'm assuming you refer to these: https://github.com/search?q=repo%3Avercel%2Fnext.js+createStore+path%3A%2F%5Eexamples%5C%2F%2F&type=code?

**Comment by jeet-khondker** [comment]
@balazsorban44 
It does not refer to the correct resource.

**Comment by alexrabin** [comment]
I don't think this is Next.js related. createStore is deprecated and the new function is [configureStore](https://redux-toolkit.js.org/api/configureStore).

**Comment by Kahono0** [comment]
@jeet-khondker
Redux have replaced `createStore`  with `configureStore` so am guessing that is what should be used in store.js. Ref: https://github.com/reduxjs/redux/issues/4325

**Comment by jeet-khondker** [comment]
@Kahono0 
Yes, I can understand it. 
But don’t you think it is also important to change the codebase of `store.js` of this repository using `configureStore`?

**Comment by mkayander** [comment]
@jeet-khondker Can you share a link to the `createStore` you are mentioning? In this repo

**Comment by jeet-khondker** [comment]
@mkayander 
https://github.com/reduxjs/redux/blob/master/src/createStore.ts

**Comment by mkayander** [comment]
> @mkayander https://github.com/reduxjs/redux/blob/master/src/createStore.ts

This is another repository. You mentioned "the codebase of store.js of this repository", so is it in the next.js (current) repository?

**Comment by jeet-khondker** [comment]
@mkayander 
I cannot find that file now. Maybe it has been removed now. 
If the issue is solved, we can close this issue.

**Comment by mkayander** [comment]
I am not sure about the updates but yeah you are free to close this issue if there's no such thing anymore
