### ISSUE TITLE
Creating a custom 404 page with Next 13

### ISSUE THREAD

**Issue by sebpowell** [vercel/next.js#45834]
### What is the improvement or update you wish to see?

I've just finished upgrading to Next 13 – feels like a big improvement, well done for all your hard work. 

Just one problem I seem to be having – creating a custom 404 page. According to the upgrade guide, the new `app` directory doesn't support this yet. I assumed that it might work by using the `pages` directory instead, but it doesn't seem to get picked up by that either. Is this expected? Or am I perhaps missing something?

Just to be clear, this is what I've tried:

```
/app
  404.tsx
```

and

```
/pages
  404.tsx
```

Neither of these seem to work. 

### Is there any context that might help us understand?

See above.

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app

**Comment by daredevil3435** [comment]
I want to try if I can contribute to this issue. I'm complete newbie here. Can you guide me ?

**Comment by Gawdfrey** [comment]
Hey.

FYI, you should always link to a reproduction of your issue. It is almost always really difficult to help without.

Back to the question, 404 pages are only handled in the app directory when explicitly calling the notFound() function. Next will then show the closest NotFound page in the tree. To show 404 pages implicitly you need to locate them in the pages folder.

I have it working this way in [this reproduction](https://codesandbox.io/p/sandbox/vibrant-bohr-h1gcce?file=%2Fnext.config.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A9%7D%5D). Take and look and see if you are missing something from this setup :)

**Comment by isaachinman** [comment]
I've also just upgrading an existing NextJs app from v12 to v13. Our `pages/404.tsx` page now enters into a continuous reload loop.

From what I can tell, this regression occurred in 13.0.7. I cannot repro the issue in 13.0.6.

**Comment by sebpowell** [comment]
@Gawdfrey Thanks for the quick response! And apologies yes, I should have included this. 

I checked your link, and mine is setup the same way, and for whatever reason just started working this morning 🤷. Maybe it was serving up a cached version or something. 

Going to close this now, thank you for your help!

**Comment by LawEyez** [comment]
Just a quick question, is there a way to add the layout in `app` to the 404 page in `pages`?

**Comment by Gawdfrey** [comment]
> Just a quick question, is there a way to add the layout in `app` to the 404 page in `pages`?

Not as I am aware of. The way I have done it previously is using _app if I wanted a common layout for both the 500 and 404 pages.

We have to wait until the implicit not found functionality arrives before we share the same layout unfortunately.

**Comment by JamDev0** [comment]
Hey, mine it's kind of working, but when the 404 page is loaded it triggers the following erro:

![image](https://user-images.githubusercontent.com/61752887/223453809-65f80a24-6c2f-4518-b84c-0c1f33487d45.png)

I'm using the next middleware, could it be it?

(if i did something wrong in this comment i'm sory, i'm new in here)

**Comment by Gawdfrey** [comment]
> Hey, mine it's kind of working, but when the 404 page is loaded it triggers the following erro:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/61752887/223453809-65f80a24-6c2f-4518-b84c-0c1f33487d45.png)
> 
> 
> 
> I'm using the next middleware, could it be it?
> 
> 
> 
> (if i did something wrong in this comment i'm sory, i'm new in here)

Usually good to include a replication of your code. Hard to help without. As you say it might be middleware if it does any routing, but as said, hard to say without looking at any code.

**Comment by Gawdfrey** [comment]
> Alright, sory.
> 
> 
> 
> My middleware is like this:
> 
> 
> 
> ````typescript
> 
> import { validSubdomains } from '@utils/validSubdomainsList';
> 
> import type { NextRequest } from 'next/server';
> 
> import { NextResponse } from 'next/server';
> 
> 
> 
> export function middleware(request: NextRequest) {
> 
>   const reqHost = request.headers.get('host');
> 
> 
> 
>   const reqURL = new URL(request.url);
> 
> 
> 
>   const currentSubdomain = reqHost?.slice(0, reqHost.indexOf('.'));
> 
> 
> 
>   const isValidSubdomain = validSubdomains.find(
> 
>     (subdomain) => subdomain === currentSubdomain
> 
>   );
> 
> 
> 
>   const token = request.cookies.get('aplication.token')?.value;
> 
> 
> 
>   console.log("token", {token})
> 
> 
> 
>   // Verify with the api if the token is valid  
> 
> 
> 
>   const isIndexPage = reqURL.pathname === '/';
> 
> 
> 
>   if (isIndexPage) {
> 
>     if (!token) {
> 
>       return NextResponse.redirect(new URL(`/login`, request.url));
> 
>     }
> 
> 
> 
>     return NextResponse.redirect(new URL(`/dashboard`, request.url));
> 
>   }
> 
> 
> 
>   if (isValidSubdomain) {
> 
>     const isNotAuthenticatedRoute = [
> 
>       '/login',
> 
>       '/register',
> 
>       '/forgot',
> 
>     ].includes(reqURL.pathname);
> 
> 
> 
>     if (isNotAuthenticatedRoute && token) {
> 
>       return NextResponse.redirect(new URL(reqURL.pathname, request.url));
> 
>     }
> 
> 
> 
>     if (!isNotAuthenticatedRoute && !token) {
> 
>       return NextResponse.redirect(new URL(`/login`, request.url));
> 
>     }
> 
> 
> 
>     return NextResponse.rewrite(new URL(`${reqURL.pathname}`, request.url));
> 
>   } else {
> 
>     return NextResponse.rewrite(new URL("/subdomain-not-valid", request.url));
> 
>   }
> 
> 
> 
> }
> 
> 
> 
> export const config = {
> 
>   matcher: ['/((?!api|_next/static|favicon.ico).*)'],
> 
> };
> 
> ```

Cant see any apparent issues on a quick look. But the error says you are trying to route to "/dashboar" but in the middleware only "/dashboard" is mentioned. Might be worth checking out if that url is being botched somehow

**Comment by JamDev0** [comment]
So, the lack of mention of '/dashboard' doesn't seem to have anything to do with the error. To test it, I removed the part that checks whether the user needs to be logged in for the route, and placed it somewhere else. However, it still throws the same error.

Currently, the middleware looks like this:

```typescript
import { validSubdomains } from '@utils/validSubdomainsList';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

export function middleware(request: NextRequest) {
  const reqHost = request.headers.get('host');

  const reqURL = new URL(request.url);

  const currentSubdomain = reqHost?.slice(0, reqHost.indexOf('.'));

  const isValidSubdomain = validSubdomains.find(
    (subdomain) => subdomain === currentSubdomain
  );

  const token = request.cookies.get('medical-registration.token')?.value;

  console.log("token", {token})

  // Verify with the api if the token is valid  

  const isIndexPage = reqURL.pathname === '/';

  if (isIndexPage) {
    if (!token) {
      return NextResponse.redirect(new URL(`/login`, request.url));
    }

    return NextResponse.redirect(new URL(`/dashboard`, request.url));
  }

  if (!isValidSubdomain) {
    return NextResponse.rewrite(new URL("/subdomain-not-valid", request.url));
  }
}

export const config = {
  matcher: ['/((?!api|_next/static|favicon.ico).*)'],
};
```

**Comment by iosifache** [comment]
Hi @LawEyez,

An approach to put the `404` page in the `app` directory is to create an `app/[others]/page.tsx` file with the following content:

```js
import { redirect } from "next/navigation";

export default async function NotFound() {
    redirect("/404");
}
```

In this way, any non-existent route will be served by the generic `[others]` route, which will redirect to `/404`. The latter will render the content of `app/404/page.tsx`, whose content you can freely change.

**Comment by chaepling** [comment]
@iosifache Hi! I think your solution is the most fastest way to custom 404 pages.

But I have a question, won't doing that affect SEO? From my opinion that solution seems to not have a status code of 404, but 301. 

Does it work like next 12 version's 404 page? Asking out of curiosity. Thanks!

**Comment by ssoima** [comment]
Hi Guys, for me it worked to just create a 404.tsx page under /src/pages and import the style from '@/app/globals.css'

**Comment by JamDev0** [comment]
@ssoima when you do in that way a error isen't triggered? Something about hard navigations

**Comment by elliotgaramendi** [comment]
Just create /app/not-found.jsx

**Comment by ssoima** [comment]
@JamDev0, no error is triggered. Try it with a blank project.

**Comment by ElliotHYLee** [comment]
The current issue with the not-found is that it seems somehow throws an error at least on my side and <Link> doesn't work from my navbar. From the doc, the not-found component doesn't accept any props like reset() or so. Therefore, if I use not-found, the user need to force refresh the page after clikcing <Link href="/">Home</Llink>

So far, dyanmic catch all route seems the best option. and src/pages/404.tsx did work for me. Please enlightne me how you are all working around or any.

**Comment by dstarosta** [comment]
I have the same issue with the not-found.tsx page breaking Link elements.

**Comment by joshuajeschek** [comment]
> Just create /app/not-found.jsx
> 
> https://beta.nextjs.org/docs/api-reference/file-conventions/not-found
> https://beta.nextjs.org/docs/api-reference/notfound

thanks for the links! another thing that caused me to trip, was that this is not triggered when using `dynamicParams = false`. Or am I missing something?
Anyways, I am using `dynamicParams` again, and then use an explicit `notFound()` in my `Page` function :)

**Comment by clevermiraz** [comment]
I am facing a Similar Problem When Adding `404.tsx` or `404.jsx` to the app directory. Even on My Actual Route Not Working Properly.

**Comment by ElliotHYLee** [comment]
> 
seems not-found.ts working with the latest version for <Link>

**Comment by UmerGillani36** [comment]
Thanks its working with not-found.jsx or not-found.tsx

**Comment by offwork** [comment]
app/not-found runs in the root directory, which means you can't go back to app/page.tsx. so when you wrote a path that is not in your app directory, you will be redirected to not-found, but you cannot return to the index/home page. Is it possible to make this change in RootLayout?

**Comment by rtatarinov** [comment]
We still need to get a custom layout page for 404
