### ISSUE TITLE
[NEXT-610] NextJS pre-renders dynamic segment route even if `generateStaticParams` is not provided

### ISSUE THREAD

**Issue by dream-ellie** [vercel/next.js#45850]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.14.0
      npm: 8.5.0
      Yarn: 1.22.19
      pnpm: 6.11.0
    Relevant packages:
      next: 13.1.7-canary.10
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-3twfnt?file=app/posts/[slug]/page.tsx

### To Reproduce

1. Open the code to reproduce: https://stackblitz.com/edit/vercel-next-js-3twfnt?file=app/posts/[slug]/page.tsx
2. Run `yarn build`
3. The build will when trying to pre-render the `app/posts/[slug]/page.tsx` page.

The idea is to have a dynamic segment route like /posts/[slug] without the `generateStaticParams` function. 

### Describe the Bug
When nextJS builds the project, it tries to pre-render the `posts/[slug]/page.tsx` with the invalid value for the `[slug]`  parameter that is `"[slug]"` string.

### Expected Behavior

If there is no `generateStaticParams` provided, the pre-rendering should not happen.
Missing `generateStaticParams` is a clear indication that SSR is expected.

Documentation also does not say anything about this behaviour.

Just like with Nextjs.12 providing the `getStaticPaths()` was only required if we wanted to pre-render any of the dynamic routes, the `generateStaticParams()` in NextJs.13 should be optional and if we don't provide it, there should be no pre-rendering and the rendering should default to dynamic. 

### Which browser are you using? (if relevant)

irrelevant

### How are you deploying your application? (if relevant)

irrelevant

<sub>[NEXT-610](https://linear.app/vercel/issue/NEXT-610/nextjs-pre-renders-dynamic-segment-route-even-if-generatestaticparams)</sub>

**Comment by kfirfitousi** [comment]
The problem comes from this function: 

```tsx
function getPost(slug: string) {
  const body = Posts[slug];

  if (!body) {
    throw new Error(`Unsupported slug ${slug}`);
  }
  return body;
}
```

Instead of throwing an Error, you should use `notFound`:

```tsx
import { notFound } from 'next/navigation';

function getPost(slug: string) {
  const body = Posts[slug];

  if (!body) {
    notFound();
  }
  return body;
}
```

This will also throw an Error, but Next.js can handle it gracefully.   
You can then add a `not-found.tsx` file to the `[slug]` directory. The component you export there will render when the `notFound` function is called:

```tsx
// app/posts/[slug]/not-found.tsx

export default function NotFound() {
  return <h2>Page not found</h2>;
}
```

**Comment by dream-ellie** [comment]
@kfirfitousi Thanks. Adding notFound will work around the issue that I have highlighted in this ticket by letting nextJS pre-render the "Not Found" page.

But this ticket is not about working around the problem in the example code. My example was a very simplified code to demonstrate the point.

My understanding (based on the documentation) that the notation `[<anything>]` tells NextJS that this is dynamic route segment and `<anything>` will be replaced with the actual value from the actual url at runtime.
Or, **if I choose to**, can be pre-rendered by NextJS if I supply the `generateStaticParams()` function.

The problem is that I do not want to pre-render any single dynamic segment. I want them to be rendered dynamically at request time, hence no `generateStaticParams()` is given.
And the fact that NextJS still tries to do it with obviously invalid value "[<anything>]" is incorrect or undocumented behaviour.

NextJS should not be even trying to pre-render the dynamic page with the "[slug]" string as `slug` parameter.
