### ISSUE TITLE
Aborting Installation when alias is given as a parameter for the create-next-app

### ISSUE THREAD

**Issue by sjosuerojas** [vercel/next.js#45858]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

3verbose stack Error: canceled
erbose stack     at exec (C:\Users\Josue\AppData\Roaming\nvm\v18.12.0\node_modules\npm\node_modules\libnpmexec\lib\index.js:242:17)
verbose stack at async module.exports (C:\Users\Josue\AppData\Roaming\nvm\v18.12.0\node_modules\npm\lib\cli.js:134:5)
verbose cwd C:\Users\Josue\Desktop\Code
verbose Windows_NT 10.0.19045
verbose node v18.12.0
verbose npm  v9.4.2

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

npx create-next-app@latest --typescript

### To Reproduce

After choosing the typescript template and then selecting these options: 
![image](https://user-images.githubusercontent.com/52830706/218507407-fc0cb914-65e8-449a-a597-cc3fe173773a.png)

It always fails after adding an alias. Otherwise everything goes as accordingly.  

### Describe the Bug

Aborting installation.
Unexpected error. Please report it as a bug:
 [Error: EMFILE: too many open files, open 'C:\Users\sylvester.rojas\Desktop\JOSH\Code\rick-morty-app\node_modules\next\dist\compiled\image-size\index.js'] {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: 'C:\\Users\\sylvester.rojas\\Desktop\\JOSH\\Code\\rick-morty-app\\node_modules\\next\\dist\\compiled\\image-size\\index.js'
}

--
After choosing the option *alias* for adding one or a couple of it.

### Expected Behavior

Adding some alias after installing the next-create-app package

**Comment by CypherCrow** [comment]
I was about to report this, until I got a feeling that this was possibly reported by someone else. Hopefully, this gets resolved.

**Comment by balazsorban44** [comment]
Hi, we recently fixed a likely related issue via https://github.com/vercel/next.js/pull/45760

Could you try `npx create-next-app@canary --typescript` to see if it is fixed? :pray:

**Comment by ijjk** [comment]
Closing as this is fixed on canary per-above
