### ISSUE TITLE
Docs: Broken link in getting started page

### ISSUE THREAD

**Issue by atultiwaree** [vercel/next.js#45855]
### What is the improvement or update you wish to see?

![NExtJS](https://user-images.githubusercontent.com/93477615/218488569-cc19a91b-f164-46a4-ae68-6b2a5b6543b5.PNG)

### Is there any context that might help us understand?

The Highlighted **link is broken** please fix that.

### Does the docs page already exist? Please link to it.

 https://nextjs.org/learn/foundations/from-javascript-to-react/getting-started-with-react

**Comment by amirfakhrullah** [comment]
I'd like to fix this

**Comment by balazsorban44** [comment]
Thanks, this is fixed already and is currently being published. Should be fixed soon :tm:
