### ISSUE TITLE
calling useRouter inside component that used in next mdx return error

### ISSUE THREAD

**Issue by normanaranez** [vercel/next.js#45892]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 18.14.0
      npm: N/A
      Yarn: N/A
      pnpm: 7.27.0
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/normanaranez/portfolio

### To Reproduce

Step 1: clone this repo https://github.com/normanaranez/portfolio
Step 2: npm install
Step 3: npm run dev (this is working)
step  4: npm run build (error trigger on this command)

Error:

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
    at useRouter (C:\Development\nextjs\portfolio\node_modules\next\dist\client\router.js:122:15)
    at ArticleLayout (C:\Development\nextjs\portfolio\.next\server\chunks\830.js:63:39)
    at Fb (C:\Development\nextjs\portfolio\node_modules\react-dom\cjs\react-dom-server-legacy.node.production.min.js:65:44)

### Describe the Bug

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: NextRouter was not mounted. https://nextjs.org/docs/messages/next-router-not-mounted
    at useRouter (C:\Development\nextjs\portfolio\node_modules\next\dist\client\router.js:122:15)
    at ArticleLayout (C:\Development\nextjs\portfolio\.next\server\chunks\830.js:63:39)
    at Fb (C:\Development\nextjs\portfolio\node_modules\react-dom\cjs\react-dom-server-legacy.node.production.min.js:65:44)
    at Ib (C:\Development\nextjs\portfolio\node_modules\react-dom\cjs\react-dom-server-legacy.node.production.min.js:67:254)
    at W (C:\Development\nextjs\portfolio\node_modules\react-dom\cjs\react-dom-server-legacy.node.production.min.js:73:89)

### Expected Behavior

it will work the same as running npm run dev

### How are you deploying your application? (if relevant)

github pages using built-in nextjs action

**Comment by balazsorban44** [comment]
Hi, I tried to reproduce given the steps described, but I was not able to. Could you test `canary` or add a more minimalistic reproduction?

**Comment by normanaranez** [comment]
@balazsorban44 sorry for late response. the error is temporarily gone because i disabled the useRouter inside the ArticleLayout.tsx

please refer to this commit https://github.com/normanaranez/portfolio/commit/76ada359ffdb952ac7b9a3fa69f4b3af84aa8df9

**Comment by balazsorban44** [comment]
Thanks for clarifying.

So the issue is that you are rendering `useRouter` inside `generateRssFeed` at build via `React.renderToStaticMarkup`.


https://github.com/normanaranez/portfolio/blob/76ada359ffdb952ac7b9a3fa69f4b3af84aa8df9/src/lib/generateRssFeed.ts#L33-L35

This then shows the error that links to: https://nextjs.org/docs/messages/next-router-not-mounted, which explains that this is the expected behavior, as `useRouter` should be rendered within the Next.js context.


The easiest way to fix this is to mock out `useRouter` when generating the RSS feed, for example:

```js
let router = (isRssFeed ? () => ({ back() {} }) : useRouter)()
```

_Small note, next time make sure the reproduction corresponds to the reproduction steps. :pray:_

**Comment by normanaranez** [comment]
Thanks a lot, it is working now.
