### ISSUE TITLE
Production build API route connection refused error when pointing from getServerSideProps

### ISSUE THREAD

**Issue by Ankish76** [vercel/next.js#45901]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 18.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/Ankish76/next-production-api-bug

### To Reproduce

Create a production build 
Start production build

### Describe the Bug

Unable to test production build on development machine.
For production build when getServerSideProps make a call to api route using 

`export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("http://localhost:3000/api/hello") 
  const data: { name: string } = await res.json()
  return {
    props: {
      name: data.name
    },
  }
}`

throws connection refused error
![image](https://user-images.githubusercontent.com/16212112/218739291-95cc34bd-ed90-477e-9a20-03728e890159.png)

But for development build it works fine.

### Expected Behavior

It should not throw error
API call should succeed

**Comment by balazsorban44** [comment]
`getServerSideProps` should not attempt fetching data from an API route, but rather import the logic directly. See: https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props#getserversideprops-or-api-routes
