### ISSUE TITLE
[NEXT-555] Docs: Missing example for importing a Google Font with a space in the font title

### ISSUE THREAD

**Issue by christiangenco** [vercel/next.js#45916]
### What is the improvement or update you wish to see?

[The Next.js documentation on importing Google Fonts](https://nextjs.org/docs/basic-features/font-optimization#google-fonts) shows this recommended method of importing Google fonts:

```js
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })

export default function MyComponent() {
  return (
    <main className={inter.className}>
      Lorem ipsum dolar set amut
    </main>
  )
}
```

This method works for the `Inter` font and other fonts with single word titles. I'm trying to import a font called [Redacted Script](https://fonts.google.com/specimen/Redacted+Script) which has a space in the title.

I tried just TitleCasing it:

```js
import { RedactedScript } from '@next/font/google'
const redactedScript = RedactedScript({ subsets: ['latin'] })

export default function MyComponent() {
  return (
    <main className={redactedScript.className}>
      Lorem ipsum dolar set amut
    </main>
  )
}
```

However this code gives me the error:

```
`@next/font` error:
Unknown font `RedactedScript`
```

This font is defined in [font-data.json](https://github.com/vercel/next.js/blob/canary/packages/font/src/google/font-data.json#L9983) with a key that includes a space (`Redacted Script`) as are several other multi-word fonts, I just can't figure out how to import a module with a space in the title.

I also tried:

```js
import fonts from "@next/font/google";
const RedactedScript = fonts["RedactedScript"];
```

but that code throws the error `Font loaders must be called and assigned to a const in the module scope`.

I need to see an example in the documentation of how to import Google Fonts with a space in their title.

### Is there any context that might help us understand?

I don't think any additional context is needed.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/font-optimization#google-fonts

<sub>[NEXT-555](https://linear.app/vercel/issue/NEXT-555/docs-missing-example-for-importing-a-google-font-with-a-space-in-the)</sub>

**Comment by christiangenco** [comment]
Using Javascript I still get `Font loaders must be called and assigned to a const in the module scope` with @dbredvick's underscored code. That code might work differently in Typescript?

**Comment by dbredvick** [comment]
@christiangenco does it still blow up if you use the notation the docs suggests?

```ts
import { Redacted_Script } from '@next/font/google'
const redactedScript = Redacted_Script({  subsets: ['latin'], weight: "300"  })
```

**Comment by christiangenco** [comment]
Oh hey that worked! Thank you :D
