### ISSUE TITLE
[NEXT-557] Dark mode for Next.js website 

### ISSUE THREAD

**Issue by Jsbbvk** [vercel/next.js#45920]
### Describe the feature you'd like to request

Is there any development for a dark theme for the nextjs.org website? My eyes get flashed when I look at documentation at 3am. 

### Describe the solution you'd like

Option for dark theme

### Describe alternatives you've considered

Extensions that automatically changes theme to dark 

<sub>[NEXT-557](https://linear.app/vercel/issue/NEXT-557/dark-mode-for-nextjs-website)</sub>

**Comment by balazsorban44** [comment]
Hi, the [beta docs](https://beta.nextjs.org) is already using dark mode, so... 🤫🌑

**Comment by CavidM** [comment]
Hi. Is there any way to turn off dark mode on new website?
