### ISSUE TITLE
[NEXT-565] can't get not-found.js in dynamic router

### ISSUE THREAD

**Issue by denisso** [vercel/next.js#45939]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

windows 10
node v18.13.0
    "@next/font": "13.1.5",
    "@types/node": "18.11.18",
    "@types/react": "18.0.27",
    "@types/react-dom": "18.0.10",
    "classnames": "^2.3.2",
    "eslint": "8.32.0",
    "eslint-config-next": "13.1.5",
    "moment": "^2.29.4",
    "next": "^13.1.7-canary.14",
    "react": "^18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.4"

### Link to the code that reproduces this issue

https://github.com/denisso/next13-app-exp/tree/router-dynamic

### To Reproduce

To reproduce the problem, go to the "Dynamic Params false" section and select one of the gray links.

### Describe the Bug

When 404 is triggered, the page is completely reloaded, and I get a 404 page which is the default.

### Expected Behavior

get content not-found.js Instead of 404 page which is the default.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

https://6951jo-3000.preview.csb.app/

<sub>[NEXT-565](https://linear.app/vercel/issue/NEXT-565/cant-get-not-foundjs-in-dynamic-router)</sub>

**Comment by JanKaifer** [comment]
`not-found.tsx` needs to be manually triggered with `notFound()`. It doesn't get triggered when you navigate to non-existing path.

We are working on that.
