### ISSUE TITLE
Duplicate API pages

### ISSUE THREAD

**Issue by micmc422** [vercel/next.js#45942]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release
Only happen in 13.1.7-canary.14 to 13.1.7-canary.19.

With 13.1.7-canary.20 warning still in console, but dev seems to work fine.

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 19.6.0
      npm: N/A
      Yarn: N/A
      pnpm: 7.27.0
    Relevant packages:
      next: 13.1.7-canary.15
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/micmc422/duplicate-api-page-issue.git

### To Reproduce

Create a new API page 
run next dev

### Describe the Bug

Console report alert for duplicate page :

warn  - Duplicate page detected. pages\api\hello-copy.ts and pages\api\hello-copy.ts resolve to /api/hello-copy
warn  - Duplicate page detected. pages\api\hello.ts and pages\api\hello.ts resolve to /api/hello

All pages (non api) return 404 error

### Expected Behavior

Should not break app

### Which browser are you using? (if relevant)

chrome

**Comment by Brettkgamble** [comment]
Also experiencing this issue when moving from "13.1.7-canary.13" to ""13.1.7-canary.14". Also tried 13.1.7-canary.15 with the same result.

**Comment by evowizz** [comment]
Also facing this issue. I also tried with @leerob's [website](github.com/leerob/leerob.io) and the same issue happened. However, it seems that building for production works fine (`next build` + `next start`).

**Comment by giuseppe-g-gelardi** [comment]
i am having the same issue as well, however, only on windows. on mac everything works fine.

**Comment by imranbarbhuiya** [comment]
Same issue here

**Comment by rdylina** [comment]
Same issue here. 
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:        
      next: 13.1.7-canary.21  
      eslint-config-next: N/A 
      react: 18.2.0
      react-dom: 18.2.0

**Comment by davidlbowman** [comment]
Same issue, only happens with `npm run build` and not `npm run build --turbo`

**Comment by idango10** [comment]
Based on the documentation, it appears that [Route Handlers](https://beta.nextjs.org/docs/data-fetching/api-routes), which are available on `next@canary`, replace [API Routes](https://beta.nextjs.org/docs/data-fetching/api-routes) from the `pages/` directory.

In my opinion, if the project is using the experimental `app/` directory, the `pages/` directory should not be utilized and a warning should be issued if it exists, indicating that it will be ignored.

**Comment by DuCanhGH** [comment]
They just merged PR 46238, which seems to have fixed this issue :D

**Comment by micmc422** [comment]
Fixed,

no more warning in 13.1.7-canary.26

**Comment by plasmadice** [comment]
> Fixed,
> 
> no more warning in 13.1.7-canary.26

Nearly lost my mind. Thank you. Got rid of the `warn  - Duplicate page detected.` error by upgrading to next@13.2.4 and dropping all canary versions in package.json. 

Operating System:
Platform: win32
Arch: x64
Version: Windows 10 Pro
Node: 18.3.0
npm: N/A
Yarn: Failed using this
pnpm: Filed using this
Relevant packages:
next: 13.1.7-canary.14
@next/font: 13.1.7-canary.5
react: 18.2.0
react-dom: 18.2.0
