### ISSUE TITLE
Removing redirects() from next.config.js does not work

### ISSUE THREAD

**Issue by Brew-Brew** [vercel/next.js#45984]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.3
      eslint-config-next: 12.3.3
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

x

### To Reproduce

I removed redirects() function what looks like below, but if i enter the url http://localhost:3000, It redirect to localhost:3000/dashboard :(

```
    async redirects() {
      return [
        {
          source: "/",
          destination: "/dashboard",
          permanent: true,
        },
      ];
    },
```

### Describe the Bug

I wonder It only occurs on localhost? because It should be solved on below situations 

as is `https://{our url}`  =>`https://{our url}/dashboard`

to be `https://{our url}`=> our new page

### Expected Behavior

as is `https://{our url}`  =>`https://{our url}/dashboard`

to be `https://{our url}`=> our new page

**Comment by ijjk** [comment]
Hi, since you specified `permanent: true` the `308` status code is leveraged which browsers cache indefinitely so to reset this cache you need to do a hard refresh.

**Comment by stefanone91** [comment]
Upgrading to next@13.2.4 have made the game, for me!
Thank you!
