### ISSUE TITLE
Docs: Add examples about unit testing the new app directory

### ISSUE THREAD

**Issue by jmaestree** [vercel/next.js#45987]
### What is the improvement or update you wish to see?

Currently there's no examples about how to test the new folder structure of the `app` directory. For example the `layout, page, head, ...` files.

I'm having issues trying to test a layout page when using the `next/cookies` package, but there's no examples about testing, it will be grateful to have a clear guidelines about what we can test or not depending if the file is being rendered on client/server.

### Is there any context that might help us understand?

-

**Comment by gutisalex** [comment]
having the same issue with next/cookies but also with next/headers... no docs nor examples how to write proper tests using app router. Hopefully we can get something soon!

**Comment by DawidWraga** [comment]
Any examples of writing testings using app router would be much appreciated, cannot set up any basic tests due to "    Cannot find module '@testing-library/jest-dom/extend-expect' from 'jest.setup.ts" error

**Comment by leerob** [comment]
We're working on adding documentation around testing with the App Router, stay tuned 🙏
