### ISSUE TITLE
Docs: Choose a specific font weight or font style in NextJs 13

### ISSUE THREAD

**Issue by ChinonsoIg** [vercel/next.js#45994]
### What is the improvement or update you wish to see?

I am using **@next google fonts**.
From the docs, you can specify an array of values for the font weight and font style like so:
```
import { Montserrat } from '@next/font/google'

const montserrat = Montserrat({ 
  weight: ['300', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'] 
})
```
When I want to reference this font in my app, I call it like so:
`<h1 className={montserrat.className}>Dashboard</h1>`

I would like us to specify how to reference a specific font weight from the weight array, and a specific font style from the style array.

### Is there any context that might help us understand?

The problem currently is that, when you write the weight array like the one above `['300', '900']`, it ends up selecting none of the two. It selects something in between. But, when I write only one, say `['300']`, it returns the correct font weight for 300. In the same vein, if I write only `['900']` as the font weight, it returns the correct weight for 900.

In addition, where the font style is written like so  `['normal', 'italics']`, it returns the normal font style. If I interchange it so italics comes first `['italics', 'normal']`, it also returns normal font style. The italics is only selected when I have only it in the array, like so `['italics']`.

Link to the docs below.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/font-optimization

**Comment by leerob** [comment]
When you're adding multiple weights, you're making them available for you to reference and use in your CSS files. You would need to be more specific when adding your weight to your rule, making sure to explicitly use `300` versus just `normal`. 

You also might be able to override the weight keywords like `bold`, but not sure if this is the best move.

```css
/* Override for all bold elements */
b, strong {
    font-weight: 700;
}

/* Override for any element set to bold through font-weight */
*:where([style*="font-weight: bold"]) {
    font-weight: 700 !important;
}
```
