### ISSUE TITLE
[NEXT-623] `next/image` does not load lazily when dynamically generated in Safari.

### ISSUE THREAD

**Issue by meotimdihia** [vercel/next.js#46019]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.27.0
    Relevant packages:
      next: 13.1.7-canary.16
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

https://github.com/meotimdihia/nextjs-bugs

### To Reproduce

Open https://nextjs-safari-caching-bug.vercel.app/lazyload in Safari 16.2 on Mac or iOS.

### Describe the Bug
I can't explain this issue well. But please take a look at this problem.  

Safari loaded every image in the world.
https://nextjs-safari-caching-bug.vercel.app/lazyload
<img width="1809" alt="image" src="https://user-images.githubusercontent.com/300961/219489385-53ebade3-3c05-4750-aad7-93c86afcc455.png">

But in this link, it works fine in this link:
https://nextjs-safari-caching-bug.vercel.app/static/test.html

Though `next/legacy/image` is fine.

### Expected Behavior

....

<sub>[NEXT-623](https://linear.app/vercel/issue/NEXT-623/nextimage-does-not-load-lazily-when-dynamically-generated-in-safari)</sub>

**Comment by meotimdihia** [comment]
@glepretre it looks like we can't set `loading`: `lazy` before `src` in Next/image.

**Comment by meotimdihia** [comment]
@timneutkens  Sorry for the ping but I think this bug is important. But no one knows it, it takes months for me because I never used Safari.

**Comment by glepretre** [comment]
Thanks a lot! :pray: Updated in 13.2.1 and tested: it's perfectly lazy now :sweat_smile:

**Comment by timneutkens** [comment]
@glepretre thanks for investigating this, it helped create a quick PR that we were able to land right before the stable release.
