### ISSUE TITLE
TypeError: this._headers.getAll is not a function on production

### ISSUE THREAD

**Issue by madsbuch** [vercel/next.js#46034]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

This morning we started getting this error in production:

```
TypeError: this._headers.getAll is not a function
    at (node_modules/next/dist/server/web/spec-extension/cookies/response-cookies.js:30:0)
    at (node_modules/next/dist/server/web/spec-extension/response.js:34:0)
    at (node_modules/next/dist/server/web/spec-extension/response.js:91:0)
    at (src/middleware.ts:9:14)
    at (node_modules/@sentry/nextjs/esm/edge/utils/edgeWrapperUtils.js:54:0)
    at (node_modules/@sentry/nextjs/esm/edge/wrapMiddlewareWithSentry.js:18:7)
    at (node_modules/next/dist/esm/server/web/adapter.js:97:0)
```

The code regards a line where we make a next response:

```
const res = NextResponse.next();
```

There is a thread about this in _tests_ previously: https://github.com/vercel/next.js/issues/42374

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

no

### To Reproduce

Create a middleware that invokes `NextResponse.next();`

### Describe the Bug

Either this is on Vercel or on Next.js

Middlewhere started to throw an error this morning with the result that no routes using the middleware can be accessed directly.

### Expected Behavior

For it to work.

**Comment by funwithtriangles** [comment]
We're also getting this error

**Comment by madsbuch** [comment]
We had to deactivate middleware while this issue is corrected. It looks like it is the Vercel build process that introduced the error, as it is only for new builds (According to @funwithtriangles ; existing deployments are not affected).

**Comment by funwithtriangles** [comment]
From Vercel support:

> The issue has been passed on to our engineering team who are working on a fix currently as priority. As you've mentioned, an instant rollback seems to work for the moment to keep the site up but we will let you know as soon as we have any updates on this!

**Comment by balazsorban44** [comment]
Thanks, I'm closing this as the issue should be the same as #42374.

The PR fixing it is under review: https://github.com/vercel/next.js/pull/42736

**Comment by balazsorban44** [comment]
Until the PR is merged, a redeploy should fix the issue now!
