### ISSUE TITLE
Docs: Command+K support for navigation and search in the docs

### ISSUE THREAD

**Issue by nklswbr** [vercel/next.js#46041]
### What is the improvement or update you wish to see?

I would like to see Next support the ability to navigate and search the docs with ⌘ + K on Mac or CTRL + K on Windows.

### Is there any context that might help us understand?

Since many frameworks and libraries support this feature, I think it makes sense for Next to do so as well. The [Tailwind docs ](https://tailwindcss.com/docs/installation) provide this feature, for example.

**Comment by balazsorban44** [comment]
Thanks for the feedback, this is on our list of features  we want on the documentation page and is already tracked internally. 🙏
