### ISSUE TITLE
Nextjs13 - AppDir - not able to export default project created via npm create-next-app

### ISSUE THREAD

**Issue by dsvgit** [vercel/next.js#46067]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 18.14.0
      npm: 8.19.3
      Yarn: 3.3.1
      pnpm: 7.26.3
    Relevant packages:
      next: 13.1.7-canary.18
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Static HTML Export (next export)

### Link to the code that reproduces this issue

https://github.com/dsvgit/reproduction-app-next-export

### To Reproduce

- create an app:
```
npx create-next-app@latest my-app
```
- run build and export
```
next build
next export
```

### Describe the Bug

I tried to export nextjs app via `next build && next export` command.
The app is created with experimental `appDir`. And I run these commands without any code modifications.
I have the `out` directory, but I don't see `index.html` file. This is the result from reproduction template:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/9424830/219794759-278e4e3d-93d6-42ad-92bc-d58edd666532.png">

And I see the following error:
```
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - using build directory: /Users/dsvuser/work/projects/tales/reproduction-app-next-export/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "/Users/dsvuser/work/projects/tales/reproduction-app-next-export/next.config.js". Generating map from "./pages"
info  - Launching 11 workers
info  - Copying "public" directory
info  - Exporting (2/2)
PageNotFoundError: Cannot find module for page: /
    at Object.getPagePath (/Users/dsvuser/work/projects/tales/reproduction-app-next-export/node_modules/next/dist/server/require.js:77:15)
    at /Users/dsvuser/work/projects/tales/reproduction-app-next-export/node_modules/next/dist/export/index.js:384:48
    at Array.map (<anonymous>)
    at /Users/dsvuser/work/projects/tales/reproduction-app-next-export/node_modules/next/dist/export/index.js:375:69
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Users/dsvuser/work/projects/tales/reproduction-app-next-export/node_modules/next/dist/trace/trace.js:79:20) {
  code: 'ENOENT'
}

```

### Expected Behavior

No errors, `out/index.html` created after running `next build && next export`

**Comment by joaquinwojcik** [comment]
It's not supported yet. 
You can find the roadmap here: https://beta.nextjs.org/docs/app-directory-roadmap

---
Duplicates #46111
