### ISSUE TITLE
Component' refers to a value, but is being used as a type here. Did you mean 'typeof Component'?

### ISSUE THREAD

**Issue by 1111Eugene** [vercel/next.js#46064]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

[{
	"resource": "/e:/Coding/next/pages/_app,js",
	"owner": "typescript",
	"code": "2749",
	"severity": 8,
	"message": "'Component' refers to a value, but is being used as a type here. Did you mean 'typeof Component'?",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 10,
	"endLineNumber": 3,
	"endColumn": 19
},{
	"resource": "/e:/Coding/next/pages/_app,js",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'>' expected.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 20,
	"endLineNumber": 3,
	"endColumn": 21
},{
	"resource": "/e:/Coding/next/pages/_app,js",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 36,
	"endLineNumber": 3,
	"endColumn": 37
},{
	"resource": "/e:/Coding/next/pages/_app,js",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 3,
	"startColumn": 37,
	"endLineNumber": 3,
	"endColumn": 38
}]

### Which example does this report relate to?

https://github.com/vercel/next.js/blob/canary/examples/next-css/pages/_app.tsx

### Describe the Bug

type Component = /*unresolved*/ any
'Component' refers to a value, but is being used as a type here. Did you mean 'typeof Component'?ts(2749)

### Expected Behavior

good

### To Reproduce

just copy and paste the code from the example file into your file

**Comment by balazsorban44** [comment]
I could not reproduce this, if you still experience a problem, please open a new issue, and attach your minimal public reproduction.
