### ISSUE TITLE
NextJS Layout suddenly stopped working and being rendered and sometimes it renders correctly again

### ISSUE THREAD

**Issue by RamboGj** [vercel/next.js#46061]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

NextJS 13.1.1

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript

### Link to the code that reproduces this issue

Not available

### To Reproduce

Run nextproject and create a layout

### Describe the Bug

I am using next 13.1.1, this is the second project that I've been working that I got the same issue with layout. I am using /pages dir, not /app. I basically create a Layout and wrap some component inside it. Sometimes it renders correctly, but, suddenly, the Layout stops rendering and apllying any kind of styles, it just breaks.

Layout ==>
```js
import React from 'react'
import { Header } from '../components/Header'
import { Sidebar } from '../components/Sidebar'

interface DashboardLayoutProps {
  children: React.ReactNode | React.ReactNode[]
}

export function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <div className="max-w-screen w-full bg-black overflow-x-hidden">
      <div className="w-screen mx-auto">
        <Header />

        <div className="w-screen flex">
          <Sidebar />

          <main className="px-4 lg:px-12 mr-8 text-white min-h-screen flex-1 flex flex-col bg-blue900 pb-12">
            {children}
          </main>
        </div>
      </div>
    </div>
  )
}
```

App.tsx ==>
```js
import '../styles/globals.css'

import type { AppProps } from 'next/app'
import { DashboardLayout } from '../layouts/DashboardLayout'
import { usePathname } from 'next/navigation'

export default function App({ Component, pageProps }: AppProps) {
  const pathname = usePathname()

  return (
    <>
      {pathname !== '/' ? (
        <DashboardLayout>
          <Component {...pageProps} />
        </DashboardLayout>
      ) : (
        <Component {...pageProps} />
      )}
    </>
  )
}
```

Obs: the screenshoot url is /dashboard/overview

Expected UI (Ignore graphs please)
![Screenshot_7](https://user-images.githubusercontent.com/64593022/219750648-229b8250-f651-4cbd-90ff-2e3442f9f5a2.png)

The UI I got
![Screenshot_17](https://user-images.githubusercontent.com/64593022/219750855-d748b733-71c7-4beb-888b-65bc67f7c774.png)

### Expected Behavior

The Layout to render correctly

### Which browser are you using? (if relevant)

Firefox and Google

### How are you deploying your application? (if relevant)

It is in Localhost

**Comment by donley828** [comment]
remove `usePathname` maybe reslove your question
