### ISSUE TITLE
appDir: css module not loaded in production in latest canary version

### ISSUE THREAD

**Issue by Pnlvfx** [vercel/next.js#46091]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2
    Binaries:
      Node: 19.5.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.7-canary.16
      eslint-config-next: 13.1.6
      react: 18.3.0-next-3d615fc14-20220919
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Pnlvfx/bbabystyle/tree/5accfc9c6f5ec8f4bd49eb3e2896e93e4166ad57

### To Reproduce

I've not a reproduction actually, but I hope some developer will take a look at this issue!

### Describe the Bug

When using next build and next start with the latest canary version (13.1.7-canary.20) but starting from 13.1.7-canary.18 there seems to be a problem when loading a CSS module like import style from '../abcde.module.css', I verified that is still present in the latest version, but if I step back top next@13.1.7-canary.16 it works fine!

### Expected Behavior

I expect to see the css loaded but it happens only when using next dev!

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

vercel

**Comment by rmorey** [comment]
I believe I'm seeing the same issue

[Here](https://github.com/rmorey/canary-css-bug) is a demo running next@latest. It imports PicoCSS and you can see [on the vercel deployment](https://canary-css-bug.vercel.app/) that the styling is applied.

[Here](https://github.com/rmorey/canary-css-bug/pull/1/files) is the same demo, but with next bumped to canary. The only difference is the next version. But when we look at the [vercel preview deployment ](https://canary-css-bug-git-canary-rtm.vercel.app/) the styling isn't there

**Comment by leerob** [comment]
Thanks for letting us know! It *might* be due to the change from head.js -> metadata API, but that's just a guess.

Maybe worth trying with that? https://beta.nextjs.org/docs/guides/seo

**Comment by Pnlvfx** [comment]
I was using the new metadata before and I'm still using the metadata with this version 13.1.7-canary.16, and everything work fine  so I don't think that the issue is related to this.
