### ISSUE TITLE
dynamic routes under the appDir do not work only at build time

### ISSUE THREAD

**Issue by Hyuga-Tsukui** [vercel/next.js#46098]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 4.0.0-rc.38
      pnpm: 7.27.1
    Relevant packages:
      next: 13.1.7-canary.20
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/Hyuga-Tsukui/bug-report

### To Reproduce

Just run `npx build`

### Describe the Bug

Note that this does not occur in `next dev`

The conditions under which this occurs are two Steps.

1. When the parent server component creates a dynamic link to a child, it obtains and uses something like an ID from an external resource.
2. The child component then does something with the ID it received from the parent. At this point, since the ID is an unexpected value(Like %5Bid%5D.), in the reproduced example, it is accessed with a key that does not exist in the array and undefined is returned. 

![image](https://user-images.githubusercontent.com/30320033/219922835-1960f93d-26c4-4858-9e1d-34c1866b1d75.png)

**Shouldn't this be built until the parent's Promise is resolved?**

Also, I think this is the same thing that's happening in this [discussion](https://github.com/vercel/next.js/discussions/45851)

### Expected Behavior

Hopefully the build will go through correctly.

Need something like this that can build correctly when there are dependencies on Promise in a nested relationship, or an evacuation hatch.

**Comment by Hyuga-Tsukui** [comment]
Reproduction repositories were re-created with the minimum configuration with the specified template.

**Comment by jaunruh** [comment]
1 up.

I am having the same issue. The following page shows a dynamic page with `/[project]/...` as the slug.

```javascript
export default function Page({
                               params: {project},
                             }: {
  params: { project: string };
}) {
  let md = new MarkdownIt();
  console.log(`${project}`)
  let projectData: Project = require(`/content/projects/${project}/content.yaml`)
//...
}
```

The require reads a local yaml file that describes the page content. This setup was working at some point in the past (I think on `next 13.1.1`.
But on build it prints:
```bash
%5Bproject%5D
Error: Cannot find module './%5Bproject%5D/content.yaml'
    at webpackContextResolve (/Users/johannes/Programming/Private/JS/next-image-test/.next/server/chunks/291.js:36:11)
    at webpackContext (/Users/johannes/Programming/Private/JS/next-image-test/.next/server/chunks/291.js:31:11)
    at Page (/Users/johannes/Programming/Private/JS/next-image-test/.next/server/app/projects/[project]/page.js:355:48)
    at T (/Users/johannes/Programming/Private/JS/next-image-test/.next/server/chunks/593.js:1078:25)
    at Ma (/Users/johannes/Programming/Private/JS/next-image-test/.next/server/chunks/593.js:1241:33)
    at Array.toJSON (/Users/johannes/Programming/Private/JS/next-image-test/.next/server/chunks/593.js:1034:32)
    at stringify (<anonymous>)
    at V (/Users/johannes/Programming/Private/JS/next-image-test/.next/server/chunks/593.js:1333:53)
    at ping (/Users/johannes/Programming/Private/JS/next-image-test/.next/server/chunks/593.js:1133:43) {
  code: 'MODULE_NOT_FOUND'
```
Where the first line is my `console.log`


Refer to [this](https://github.com/jaunruh/next-image-test) repo for an example.

**Comment by axis00** [comment]
+1

I'm having the same issues with `13.1.6`
this is a fresh project

<img width="345" alt="image" src="https://user-images.githubusercontent.com/31441739/220412527-ab010445-e676-43b1-b6b7-86a7a4fc99b2.png">


```javascript
/** page.tsx **/
const getData = () => Promise.reject('this is an error')

export default async function Page({ params }: any) {
  console.log('\nparams', params)
  const data = await getData()

  return <p>{data}</p>
}
```

```
# terminal output
info  - Collecting page data  
[    ] info  - Generating static pages (0/4)
params { id: '%5Bid%5D' }
this is an error

Error occurred prerendering page "/[id]". Read more: https://nextjs.org/docs/messages/prerender-error
this is an error
info  - Generating static pages (4/4)

> Build error occurred
Error: Export encountered errors on following paths:
        /[id]/page: /[id]
```

**Comment by Zyzle** [comment]
I'm seeing the same issue here, last good version for me was `13.1.7-canary.27` (the error occurs in .28). I'll try and create a minimal example

**Comment by Hyuga-Tsukui** [comment]
> I got the same issue. Upgrading to 13.2.1 fixed this issue

I can confirm that it no longer occurs in the repository that I gave in the bug report, in version 13.2.1 

![image](https://user-images.githubusercontent.com/30320033/221311862-5d387db2-9679-45cb-b2cd-df231e99f10d.png)
