### ISSUE TITLE
Duplicate page warning when running Next.js with authentication

### ISSUE THREAD

**Issue by wiscaksono** [vercel/next.js#46096]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

  **System:**
>    OS: Windows 10 10.0.22621
>     CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
>     Memory: 7.06 GB / 15.93 GB

  **Binaries:** 
>  Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD

  **Browsers:**
>    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.46)
>     Internet Explorer: 11.0.22621.1

**package.json**
```json
  "dependencies": {
    "@emailjs/browser": "^3.10.0",
    "@headlessui/react": "^1.7.11",
    "@react-icons/all-files": "^4.1.0",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@types/react": "18.0.28",
    "@vercel/analytics": "^0.1.10",
    "eslint": "8.34.0",
    "eslint-config-next": "13.1.6",
    "framer-motion": "^9.0.4",
    "next": "^13.1.7-canary.8",
    "next-auth": "^4.19.2",
    "react": "18.2.0",
    "react-code-blocks": "^0.0.9-0",
    "react-dom": "18.2.0",
    "tailwind-scrollbar": "^2.1.0",
    "typescript": "4.9.5",
    "typewriter-effect": "^2.19.0"
  },
  "devDependencies": {
    "@types/node": "18.14.0",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "prettier": "^2.8.4",
    "prettier-plugin-tailwindcss": "^0.2.3",
    "tailwindcss": "^3.2.7"
  }
  ```

### Link to the code that reproduces this issue

https://github.com/wiscaksono/wiscaksono-next

### To Reproduce

1. Clone the project from this repository
2. Run `yarn install`
3. Run `yarn dev`
4. Observe the duplicate page warnings in the console

### Describe the Bug

I am encountering a problem with Next.js where I am receiving a "Duplicate page detected" warning when running `yarn dev`. Specifically, the following warnings are appearing in my console:

```
warn - Duplicate page detected. src\pages\api\api.ts and src\pages\api\api.ts resolve to /api/api
warn - Duplicate page detected. src\pages\api\auth\[...nextauth].ts and src\pages\api\auth\[...nextauth].ts resolve to /api/auth/[...nextauth]
warn - Duplicate page detected. src\pages\api\auth\[...nextauth].ts and src\pages\api\auth\[...nextauth].ts resolve to /api/auth/[...nextauth]
warn - Duplicate page detected. src\pages\api\auth\[...nextauth].ts and src\pages\api\auth\[...nextauth].ts resolve to /api/auth/[...nextauth]
```

**Here is my folder structure**
![image](https://user-images.githubusercontent.com/63142229/219868825-575ad30d-6dff-4816-b620-40901734cf4d.png)

I have checked my code and I am confident that there are no duplicate pages in my project. I believe that this issue is related to the Next.js authentication configuration that I have set up using `next-auth`.

**Additional information:**
I have tried the following steps to resolve the issue:

- Upgrading all the packages
- Checking my code for any duplicate pages
- Restarting my development server
- None of these steps have resolved the issue.

### Expected Behavior

I expect that when running yarn dev with next-auth authentication enabled, I should not receive any "Duplicate page detected" warnings.

### Which browser are you using? (if relevant)

Chrome 109.0.5414.120

### How are you deploying your application? (if relevant)

next start

**Comment by Brettkgamble** [comment]
Related to #45942 - Duplicate API Pages
