### ISSUE TITLE
@vercel/og not working with route handlers

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#46097]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Sat Feb 18 2023 16:34:02 GMT+0100 (heure normale d’Europe centrale)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.1.7-canary.20
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://stackblitz.com/edit/github-phyjhy?file=app%2Fapi%2Fog%2Froute.tsx

### To Reproduce

1. click the reproduction link
2. run `npm run dev`

### Describe the Bug

When adding vercel/og to route handlers, it gives this error :  

<details>
<summary>./node_modules/@vercel/og/vendor/resvg.simd.wasm?module
Module parse failed: Unexpected character '' (1:0)</summary>
<p>./node_modules/@vercel/og/vendor/resvg.simd.wasm?module
Module parse failed: Unexpected character '' (1:0)
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.
You need to enable one of the WebAssembly experiments via 'experiments.asyncWebAssembly: true' (based on async modules) or 'experiments.syncWebAssembly: true' (like webpack 4, deprecated).
For files that transpile to WebAssembly, make sure to set the module type in the 'module.rules' section of the config (e. g. 'type: "webassembly/async"').
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@vercel/og/vendor/resvg.simd.wasm?module

./node_modules/@vercel/og/dist/index.js

./app/api/og/route.tsx

This error occurred during the build process and can only be dismissed by fixing the error.</p>
</details>

### Expected Behavior

vercel/og should work just fine.

**Comment by DuCanhGH** [comment]
Perhaps you forgot to add `export const runtime = "edge"`? But yeah, seems that vercel/og isn't working with Route Handlers...

**Comment by Fredkiss3** [comment]
Added `runtime = "edge"` and updated the example, but it still gives this error : 
```
Error [TypeError]: runtime.context.addEventListener is not a function
    at createModuleContext (file:///home/projects/github-phyjhy/node_modules/next/dist/server/web/sandbox/context.js:233:21)
```

**Comment by DuCanhGH** [comment]
@Fredkiss3 yeah, it kind of doesn't work right now it seems, that was just a reminder :D
I get a different error though, which is that `yoga-wasm-web` doesn't have a default export (which may be related to the fact that it doesn't have a `main` field in `package.json`)
I hope they fix it soon though.

**Comment by mwskwong** [comment]
> This should be fixed with the next canary build :)

And it seems to be the case

**Comment by joulev** [comment]
Yes it works now.

**Comment by Fredkiss3** [comment]
Thanks, it have been fixed. The only thing to pay attention to is not to forget to set the runtime to `edge` or `experimental-edge`.

```ts
export const runtime = `edge`
```
