### ISSUE TITLE
[NEXT-703] 404 on vercel deployed index pages with i18n next config

### ISSUE THREAD

**Issue by JohnGemstone** [vercel/next.js#46118]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
    Binaries:
      Node: 17.7.1
      npm: 8.5.2
      Yarn: 1.22.19
      pnpm: 6.11.0
    Relevant packages:
      next: 13.1.7-canary.21
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Internationalization (i18n), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/JohnGemstone/next13-appdir_i18n-config-bug
https://next13-appdir-i18n-config-bug.vercel.app/

### To Reproduce

1. Make a new project with Create Next App `npx create-next-app@latest`
2. Update next.config to include i18n options:

```js
const nextConfig = {
  experimental: {
    appDir: true,
  },
  i18n: {
    locales: ["en"],
    defaultLocale: "en",
  },
}
```

3. Commit and deploy to vercel
4. Observe 404 when visiting deployed index.

### Describe the Bug

Context: I'm migrating a `pages` api site to `appdir` for performance improvements. One of the lighthouse recommendations is to add a lang attribute to your html. Reading around it's recommended to use the i18n options in next.config to add the lang attribute.

Bug: When I add i18n options to `next.config`, on deployed instances it returns a 404 for my index (sub pages are ok). There are no deploy errors and my local environment works as expected.

### Expected Behavior

The deployed index page should load as normal, without a 404 rewrite.

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-703](https://linear.app/vercel/issue/NEXT-703/404-on-vercel-deployed-index-pages-with-i18n-next-config)</sub>

**Comment by BurgerBurglar** [comment]
is this fixed?

**Comment by KeisukeNagakawa** [comment]
same here.

**Comment by bastienrobert** [comment]
@KeisukeNagakawa could you please give some context?
