### ISSUE TITLE
[Docs?] Edge API function breaks on local with res.status is not a function

### ISSUE THREAD

**Issue by Izhaki** [vercel/next.js#46128]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.1
      npm: 9.3.1
      Yarn: N/A
      pnpm: 7.25.0
    Relevant packages:
      next: 13.1.7-canary.21
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### To Reproduce

- `npx create-next-app@latest`
- Add the following to `src/pages/api/hello.ts`:

```js
export const config = {
  runtime: "edge",
  regions: ["dub1"],
};
```

- `pnpm dev`
- Go to http://localhost:3000/api/hello

### Describe the Bug

```
error - res.status is not a function
  15 |   res: NextApiResponse<Data>
  16 | ) {
> 17 |   res.status(200).json({ name: "John Doe" });
     |      ^
  18 | }
  19 | 
```

**Comment by Izhaki** [comment]
I've started seeing this after upgrading to Node 18, but now having downgraded to 16 - same issue.

Closing as currently this seems to be machine specific. Will re-open if I figure out the cause.

**Comment by Izhaki** [comment]
Going to reopen the issue, although I now believe this not a bug, but rather a documentation issue.

All the example in https://nextjs.org/docs/api-routes/edge-api-routes do not involve the `res` parameter, rather then all return `new Response(...)`.

There is a note at the bottom saying:

> Note: Using [Edge Runtime](https://nextjs.org/docs/api-reference/edge-runtime) with getServerSideProps does not give you access to the response object. If you need access to res, you should use the [Node.js runtime](https://nextjs.org/docs/advanced-features/react-18/switchable-runtime) by setting runtime: 'nodejs'.

But it's hard to understand what this means... we are just calling http://localhost:3000/api/hello.

**Comment by balazsorban44** [comment]
The function signature is different in the Edge runtime, than in the default  (Node.js).

You don't have a `res` object, as the message says, but you rather return a [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) instance, or optionally [`NextResponse`](https://nextjs.org/docs/api-reference/next/server#nextresponse).

This means that there is a migration to be done if you use the other runtime:

```ts
export default function handler(req, res) {
  res.status(200).json({ name: 'John Doe' })
}
```

becomes

```ts
export default function handler() {
  return Response.json({ name: 'John Doe' })
}
```
