### ISSUE TITLE
Docs: Need Template / Description how to create a Server Components / next v13 compatible library

### ISSUE THREAD

**Issue by mwawrusch** [vercel/next.js#46129]
### What is the improvement or update you wish to see?

We would like to see a working template for a component library that supports Server Components or documentation with details about how to create such a library. 

### Is there any context that might help us understand?

We use our own libraries to encapsulate component designs and functionality. When importing them into our main next.js application web pack erroneously forces use client on those imported functions and components. Even something as simple as this triggers the error:

export function classNames(...classes: any[]) {
  return classes.filter(Boolean).join(' ')
}

Importing and using this function through the default module entry point forces the component to 'use client'. However, when targeting the component directly (e.g. not bundled) the it works

Does not work:
```
import { ThemedMainContainer } from '@rojiio/roji-web-team-library';
```

Does work:
```
import { ThemedMainContainer } from '@rojiio/roji-web-team-library/src/primitives/ThemedMainContainer';
```
So the question is how should we set up react libraries correctly to not mess up with the primary's next.js bundler.

**Comment by balazsorban44** [comment]
You can check out the documentation:

- https://beta.nextjs.org/docs/rendering/server-and-client-components#third-party-packages
- https://beta.nextjs.org/docs/rendering/server-and-client-components#rendering-third-party-context-providers-in-server-components
- https://beta.nextjs.org/docs/rendering/server-and-client-components#when-to-use-server-vs-client-components

If you have any feedback about this documentation, you can leave it directly on the page, thanks to preview comments!

However, if you think you found a bug, could you please create a separate issue with an attached minimal public reproduction, so we can look into it?
