### ISSUE TITLE
Cannot read properties of null (reading 'disconnect')

### ISSUE THREAD

**Issue by zx-zx22** [vercel/next.js#46134]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

next version  13.0.5

### Link to the code that reproduces this issue

1

### To Reproduce

use Sentry.js caught errors

### Describe the Bug

Cannot read properties of null (reading 'disconnect')

### Expected Behavior

not error

### Which browser are you using? (if relevant)

chrome

**Comment by timneutkens** [comment]
Going to close this, as you can imagine this issue is not actionable.
