### ISSUE TITLE
[NEXT-589] Add warning when whole page is de-opted into client-side rendering

### ISSUE THREAD

**Issue by feedthejim** [vercel/next.js#46141]
Example: when using useSearchParams

ctx: [https://vercel.slack.com/archives/C03KAR5DCKC/p1676879683515529?thread_ts=1676878373.528499&cid=C03KAR5DCKC](https://vercel.slack.com/archives/C03KAR5DCKC/p1676879683515529?thread_ts=1676878373.528499&cid=C03KAR5DCKC)

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-589](https://linear.app/vercel/issue/NEXT-589/add-warning-when-whole-page-is-de-opted-into-client-side-rendering)</sub>

**Comment by timneutkens** [comment]
@samstr we've added docs on `useSearchParams` when using static or dynamic rendering and how to only deopt a small part of the page to client-rendering: https://beta.nextjs.org/docs/api-reference/use-search-params#static-rendering

**Comment by samstr** [comment]
> @samstr we've added docs on `useSearchParams` when using static or dynamic rendering and how to only deopt a small part of the page to client-rendering: https://beta.nextjs.org/docs/api-reference/use-search-params#static-rendering

Thanks @timneutkens - this is great!
