### ISSUE TITLE
Client rendering ignored in dev mode

### ISSUE THREAD

**Issue by grod220** [vercel/next.js#46151]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 9.1.2
      Yarn: 1.22.19
      pnpm: 7.26.2
    Relevant packages:
      next: 13.1.7-canary.21
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/vercel/app-playground

### To Reproduce

Add a `console.log` to any component that uses the `use client` directive and note where it logs (browser console vs terminal) during `next dev` versus `next build` + `next start`.

### Describe the Bug

With client components, one would expect them to never render on the server. However, they are executed in two environments:
- At build time (attempting to statically render)
- At runtime when using `next start`

This causes confusion given it is a departure to what happens with you run the production version of the app (`next build` + `next start`) and it does what you expect (always runs on the client).

This causes a problem especially for libraries that cannot run on the server. Errors are thrown on the server even though the developer marks them with `use client`.

### Expected Behavior

In dev mode, all client components are rendered exclusively in the client.

**Comment by timneutkens** [comment]
Hey, this is a misunderstand of `'use client'`, it marks a component as needing client-side JS, it's the equivalent of any components in "pages" today. It'll still be rendered to HTML.
