### ISSUE TITLE
Meta elements are not deduped in case they are not direct children of <Head />

### ISSUE THREAD

**Issue by Katona** [vercel/next.js#46160]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.0.8-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/spring-bird-f9ymow

### To Reproduce

Add a `<meta name="viewport" ...>` element as indirect child (extracted into a React component) to the `Head` tag in `pages/_app.js`.

### Describe the Bug

There will be two `<meta name="viewport" ...>` elements in the page: one added by NextJS and one by the app, apparently the deduplication is not working this way.  

### Expected Behavior

Only the `meta` element added by the app should be in the page.

### Which browser are you using? (if relevant)

Chrome

**Comment by teobler** [comment]
### need further clarification

I can just see only one meta tag from your link, mismatch with your description:
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/26424691/220241319-d5fb134a-d8f2-4523-99e5-aa7f00fb10c0.png">

**Comment by Katona** [comment]
It's strange, there is only one in the Inspector, but there are two in the frame source. Also, the one visible there is added by NextJS. I added another meta (`charset`) which you can observe in the Inspector, too.

**Comment by Katona** [comment]
So, we extracted the `meta` tags into a React component for code organization purposes, but this causes the problem above, and now I can see that some (all?) `meta` tags are not even rendered.

**Comment by timneutkens** [comment]
Rendering components as part of `next/head` is not supported.

> title, meta or any other elements (e.g. script) need to be contained as direct children of the Head element, or wrapped into maximum one level of <React.Fragment> or arrays—otherwise the tags won't be correctly picked up on client-side navigations.

https://nextjs.org/docs/api-reference/next/head
