### ISSUE TITLE
`npm run dev` after a fresh `npx create-next-app` creates a localhost:3000 with a 404 error

### ISSUE THREAD

**Issue by zhiyi-zhang-duke** [vercel/next.js#46177]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Windows 10
vscode 1.75.1
npm 9.4.0
node 19.6.1

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js

### To Reproduce

The bug is pretty self explanatory. If you run:
`npx create-next-app --example github-pages nextjs-github-pages`
Then
`npm run dev`
You get the following result:
![image](https://user-images.githubusercontent.com/68999131/220245555-837d8f35-441a-4226-8f96-330b11519a5b.png)

### Describe the Bug

Console errors:
GET http://localhost:3000/ 404 (Not Found)
websocket.js?a9be:60 WebSocket connection to 'ws://localhost:3000/gh-pages-test/_next/webpack-hmr' failed: 

### Expected Behavior

The expected behavior is that index.tsx is rendered. In this case "Hello World. About."

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next run deploy

**Comment by Ding-Fan** [comment]
For me I wait a long time and this error shows up

```sh
Error [NextFontError]: Failed to fetch `Inter` from Google Fonts.
    at nextFontError (/home/linux/Github/my-app/node_modules/@next/font/dist/utils.js:55:17)
    at /home/linux/Github/my-app/node_modules/@next/font/dist/google/loader.js:124:43
    at Array.map (<anonymous>)
    at downloadGoogleFonts (/home/linux/Github/my-app/node_modules/@next/font/dist/google/loader.js:112:61)
    at /home/linux/Github/my-app/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:52:99
    at async Span.traceAsyncFn (/home/linux/Github/my-app/node_modules/next/dist/trace/trace.js:79:20)
error - Failed to download `Inter` from Google Fonts. Using fallback font instead.
event - compiled client and server successfully in 263.4s (194 modules)
Error [NextFontError]: Failed to fetch `Inter` from Google Fonts.
    at nextFontError (/home/linux/Github/my-app/node_modules/@next/font/dist/utils.js:55:17)
    at /home/linux/Github/my-app/node_modules/@next/font/dist/google/loader.js:124:43
    at Array.map (<anonymous>)
    at downloadGoogleFonts (/home/linux/Github/my-app/node_modules/@next/font/dist/google/loader.js:112:61)
    at /home/linux/Github/my-app/node_modules/next/dist/build/webpack/loaders/next-font-loader/index.js:52:99
    at async Span.traceAsyncFn (/home/linux/Github/my-app/node_modules/next/dist/trace/trace.js:79:20)
error - Failed to download `Inter` from Google Fonts. Using fallback font instead.
```

Then I can see the `localhost:3000` page.

**Comment by Ding-Fan** [comment]
remove everything about "import Inter" in the file `pages/index.tsx` makes it working.

**Comment by balazsorban44** [comment]
This is because the example has a basePath defined: https://github.com/vercel/next.js/blob/c765fadfbec886cdf1885ae3145e82a52b4fec16/examples/github-pages/next.config.js#L7

You can visit http://localhost:3000/gh-pages-test
