### ISSUE TITLE
bug on body :root global css

### ISSUE THREAD

**Issue by dwissaaj** [vercel/next.js#46176]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I am testing the next feature "appDir", in `global.css`. I found a bug in css and create this issues at this conversation at [this beta next js docs  ](https://beta.nextjs.org/docs/styling/global-styles#thread-id=nHE_V) . So as default next js css render multiple div inside  `:root` class, I don't use any css framework and it happen after we generate a project. Problem is it work as global, so even we add another component using css class it happen, global css is create as a home directory for all css.

![a](https://user-images.githubusercontent.com/71976179/220236049-01212929-a805-414d-becd-bb05fe87498e.jpeg)
![Screenshot-2023-02-09-110705](https://user-images.githubusercontent.com/71976179/220236059-98d12c11-db1b-4764-b858-f8a4c272e273.jpeg)

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

npx create-next-app 

### To Reproduce

I using Webstorm 2022.3.1 default project CLI 

### Describe the Bug

`:root` class in global.css render multiple div. The only solution to stop this behavior is delete it in global css

### Expected Behavior

Clearn white backgorund, see 
![picture](https://user-images.githubusercontent.com/71976179/220236832-9b4fa067-6032-416c-b4f8-24c013bb62c9.png)

**Comment by shuding** [comment]
Can you show the code? I'm not following this:

> :root class in global.css render multiple div.

Happy to take a look if you get a reproduction!
