### ISSUE TITLE
Watch router events in appdir

### ISSUE THREAD

**Issue by taoqf** [vercel/next.js#46173]
### Describe the feature you'd like to request

I would like to watch the events router emit.

### Describe the solution you'd like

The way Just like 'next/router' does.

### Describe alternatives you've considered

I have not get any.

**Comment by balazsorban44** [comment]
`router.events` is not supported in the app directory as it doesn’t match up with concurrent rendering, e.g. multiple navigations could be started where most are discarded. Hence, there’s an inconsistency in events.

You could try something similar to this:

```jsx
'use client'

import { usePathname, useSearchParams } from 'next/navigation'

function ListeningForRouteChange() {
   const pathname = usePathname()
   const searchParams = useSearchParams()
   useEffect(() => {
      // do something because url changed.
   }, [pathname, searchParams])
}
```

**Comment by taoqf** [comment]
@balazsorban44 Thanks.

**Comment by verekia** [comment]
This should be updated then: https://beta.nextjs.org/docs/upgrade-guide/version-11#update-usage-of-routerevents

Using the code above with `usePathname` and `useSearchParams`, the effect is triggered only after the URL has changed, though. Is there any way to detect that a page change has started loading before the URL is updated (similarly to `routeChangeStart`)? This would be helpful to show a progress bar before the URL changes.
