### ISSUE TITLE
useEffect calling 2 times

### ISSUE THREAD

**Issue by Wellers0n** [vercel/next.js#46175]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@next/font": "13.1.6",
    "@types/node": "18.14.0",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "eslint": "8.34.0",
    "eslint-config-next": "13.1.6",
    "next": "13.1.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.5"
  }
}

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/elated-khorana-7lkhty?file=%2F.eslintrc.json&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A4%7D%5D

### To Reproduce

simple useEffect inside component, this effect is calling 2 times

### Describe the Bug

effect is calling 2 times

![Screenshot 2023-02-20 at 23 33 57](https://user-images.githubusercontent.com/39449389/220235114-d49e92d3-c91e-481a-bed1-56656a1dfdae.png)

![Screenshot 2023-02-20 at 23 50 19](https://user-images.githubusercontent.com/39449389/220235212-08956560-c675-48b6-bcdc-48bec932a38e.png)

### Expected Behavior

I expected useEffect calling 1 time

### Which browser are you using? (if relevant)

Brave

**Comment by sairajchouhan** [comment]
in react 18 useEffect calls twice in strict mode and this is only in development.

https://beta.reactjs.org/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development

**Comment by joeshajan** [comment]
> in react 18 useEffect calls twice in strict mode and this is only in development.
> 
> https://beta.reactjs.org/reference/react/StrictMode#fixing-bugs-found-by-re-running-effects-in-development

Correct

**Comment by balazsorban44** [comment]
This is the expected behavior as pointed out above.

**Comment by Wellers0n** [comment]
ok guys, thanks
