### ISSUE TITLE
Docs(beta): useSearchParams

### ISSUE THREAD

**Issue by arieloO** [vercel/next.js#46195]
### What is the improvement or update you wish to see?

We would like to have more details/recommendations for search params manipulation and `useSearchParams` usage

### Is there any context that might help us understand?

Context : `useSearchParam` and this comment : [components/navigation.ts#L38](https://github.com/vercel/next.js/blob/9e86fd1d586e00204eb933bd969d5799585ac42a/packages/next/src/client/components/navigation.ts#L38)

https://github.com/vercel/next.js/blob/9e86fd1d586e00204eb933bd969d5799585ac42a/packages/next/src/client/components/navigation.ts#L38

#### Questions : 
- Why are `append`, `set` `delete` & `sort` still exposed in the `useSearchParam` hook ?
- Will these methods be exposed elsewhere by next in the future? Or implemented in a specific utility hook for query manipulation?

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/use-search-params

**Comment by GMaiolo** [comment]
I scratched my head for a long while when attempting to set the search params using the exposed `set()` function

**Comment by jeanmayorga** [comment]
i create a custom hook to handle the query string params with typescript.

useQueryParams.tsx
```js
"use client"

import { usePathname, useRouter, useSearchParams } from "next/navigation";

export default function useQueryParams<T = {}>() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const queryParams = searchParams as unknown as Partial<T>;
  const urlSearchParams = new URLSearchParams(searchParams);

  function setQueryParams(params: Partial<T>) {
    Object.entries(params).forEach(([key, value]) => {
      urlSearchParams.set(key, String(value));
    });

    const search = urlSearchParams.toString();
    const query = search ? `?${search}` : "";

    router.push(`${pathname}${query}`);
  }

  return { queryParams, setQueryParams };
}
```

App.tsx
```js
interface QueryParams {
  query: string;
}
export function App() {
  const { queryParams, setQueryParams } = useQueryParams<QueryParams>();

  // to update
  // setQueryParams({ query: value })
  
  // to get the queryParams typed.
  // queryParams
  }
```

**Comment by leerob** [comment]
Sorry this is a bit stale, but we've made improvements here: https://nextjs.org/docs/app/api-reference/functions/use-search-params
