### ISSUE TITLE
Tailwind styles disappear for couple of seconds on HMR in `app` dir

### ISSUE THREAD

**Issue by unbelivr** [vercel/next.js#46197]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 13.1.7-canary.21
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/github/unbelivr/next-tailwind-bug-with-app/tests

### To Reproduce

1. Fork the sandbox or [repo](https://github.com/unbelivr/next-tailwind-bug-with-app)
2. Run `dev` and open localhost:3000. It should show fullscreen gray box and text inside it
3. Open `src/app/page.tsx` and make any changes, save. You may need to repeat this few times to reproduce.
4. Styles will disappear for a second on HMR, you won't see the gray box at this moment

### Describe the Bug

It looks like there's an issue with injection or deduplication of styles. In the video below you can notice strange behavior inside `<head>`

https://user-images.githubusercontent.com/12210765/220398634-03120090-49e2-4368-a921-1c1bdff0aae8.mov

### Expected Behavior

Styles should not flash

### Browser

Chrome 110.0.5481.100

**Comment by diegohaz** [comment]
I noticed that this also happens in production sometimes when clicking on links for the first time, but it's really hard to reproduce.

**Comment by cqh963852** [comment]
> I noticed that this also happens in production sometimes when clicking on links for the first time, but it's really hard to reproduce.

Have you open `dev tool element tab` during reproduce?

I found that if `dev tool element tab` being opened, It will be eaiser reproduce

**Comment by diegohaz** [comment]
@shuding I'm still seeing the issue in production when I try to navigate to a page for the first time using the keyboard (tabbing to the link and pressing Enter).

I still can't create a minimal reproduction, but here's a video of what's happening:

https://github.com/vercel/next.js/assets/3068563/00e7b884-6208-4506-aae5-cf816ddc0c74
