### ISSUE TITLE
API Routes timeout in production

### ISSUE THREAD

**Issue by kouji-dev** [vercel/next.js#46203]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 13.1.7-canary.21
      eslint-config-next: 13.1.7-canary.21
      react: 18.2.0
      react-dom: 18.2.0
```
Same thing for next@13.1.6

### Link to the code that reproduces this issue

https://github.com/kouji-dev/boostgg

### To Reproduce

Having deployed only the typescript template, the call to **_productionUrl.vercel.app/api/hello** works_, but when i added my front-end libraries and prisma to the project, all my api routes are not working anymore, and I get 

```
An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT
```

### Describe the Bug

the logs are clean and there are no errors, also everything works fine in my local. I even connected to the production database from my local and the api responds in 127ms. but also testing just a dummy api route doesnt work.

```
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'

type Data = {
  name: string
}

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  res.status(200).json({ name: 'John Doe' })
}

```

I also have deployed my code in 2 diffrent regions: Paris (which is near me), San francisco which is soo far but both gives the same result.

### Expected Behavior

That my api routes work in production, if it works in local. If the api is consuming a lot, vercel platform should warn me and dont interupt the call at least for the first call so that i can mesure the total resources and time needed for the api.

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

next build

**Comment by icyJoseph** [comment]
Could it be possible that your server bundle is so large that it cannot be parsed on a sensible time? Could you run `@next/bundle-analyzer` and see what's up with the server bundles?

**Comment by kouji-dev** [comment]
@icyJoseph thanks for your reply, i think i've found the root cause. Surprisingly it is due to @mui/icons-material, it impacts the bundle size. I will close this ticket it is related to this [mui icon issue](https://github.com/mui/material-ui/issues/35450)
