### ISSUE TITLE
with-zones - blog page - error 404

### ISSUE THREAD

**Issue by mahima98** [vercel/next.js#46229]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

$ npx --no-install next info
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ramh\AppData\Local\npm-cache\_logs\2023-02-22T07_12_08_821Z-debug-0.log

### Which example does this report relate to?

with-zones

### What browser are you using? (if relevant)

Version 110.0.5481.104 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

As I created a new NextJS project with the template 'with-zones' example.
The "home" project runs well after `npm install && npm run dev`
However, As I go to the root project of "Blog" after `npm install && npm run dev`
Am getting an error 404 on localhost:4000 :(

### Expected Behavior

The "Blog" page should open properly localhost:4000 after `npm install && npm run dev`

### To Reproduce

As I created a new NextJS project with the template 'with-zones' example.
The "home" project runs well after `npm install && npm run dev`
However, As I go to the root project of "Blog" after `npm install && npm run dev`
Am getting an error 404 on localhost:4000 :(

**Comment by balazsorban44** [comment]
The blog project has a `baseBath` configured:

https://github.com/vercel/next.js/blob/844776ef95aa3b5cdf88448284101139a678189f/examples/with-zones/blog/next.config.js#L3

This means that you need to visit the pages under `http://localhost:4000/blog`
