### ISSUE TITLE
[NEXT-611] Improve hydration error messages in `pages`

### ISSUE THREAD

**Issue by chavda-bhavik** [vercel/next.js#46226]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.9.4
    Relevant packages:
      next: 13.1.7-canary.21
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/chavda-bhavik/nextjs-error-reproduction

### To Reproduce

1. Write this invalid jsx in the `index.tsx` file,
```
export default function Home() {
  return (
    <button>
      <button>Click Me</button>
    </button>
  );
}
```
2. See the error `Hydration failed because the initial UI does not match what was rendered on the server.`
![image](https://user-images.githubusercontent.com/50201755/220343429-1df6ce6b-c906-4fc8-b306-8e9930bd5c1e.png)

### Describe the Bug

I am receiving the `Hydration failed because the initial UI does not match what was rendered on the server` error when attempting to troubleshoot an HTML issue in jsx. It would be helpful to have a more specific error message that indicates which HTML element the issue is in, as this would make it easier to identify what the problem is.

### Expected Behavior

When there is an issue in jsx regarding HTML, a message stating `issue in HTML` would be helpful to debug rather than the `Hydration failed because the initial UI does not match what was rendered on the server` error. In addition to where the HTML issue is.

<sub>[NEXT-611](https://linear.app/vercel/issue/NEXT-611/improve-hydration-error-messages-in-pages)</sub>

**Comment by icyJoseph** [comment]
Typically the console contains the exact node where things went wrong. Do remember that this is first and foremost a React error.

![Screenshot 2023-02-22 at 09 29 35](https://user-images.githubusercontent.com/21013447/220564776-e514e61e-06fe-47c5-911f-f9887c5b4d13.png)

There's however, some thing, I used to agree too, now I don't know, but should this break onto a hydration error? https://github.com/vercel/next.js/issues/36765

The error did exist when React 17 was used under the hood, but now with the concurrent root, this kind of things breaks the hydration process. https://github.com/facebook/react/issues/24519

**Comment by chavda-bhavik** [comment]
Thanks for the clarification, Joseph. I think we are talking about the same thing, does it really a `hydration error` or not?

**Comment by timneutkens** [comment]
We've changed the error overlay in a bunch of ways recently: https://github.com/facebook/react/issues/24519#issuecomment-1439915463
