### ISSUE TITLE
Deployment Regression app dir / nested layouts - fails to render on vercel

### ISSUE THREAD

**Issue by mwawrusch** [vercel/next.js#46266]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.1.0
      npm: 8.1.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.7-canary.26
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

can create it if necessary

### To Reproduce

Create an app that includes nested layouts, like so:

app/ -> layout.tsx
app/[walletId]/dashboard -> layout.tsx

### Describe the Bug

This works in development, however when deployed on vercel, the page is not rendered but this error is returned (from canary .11 to .26, .10 works fine on vercel):

```
2023-02-22T20:24:53.541Z	68a7b9b6-dc69-4a61-ad8d-38f62c7b5ab8	ERROR	TypeError: Cannot read properties of undefined (reading '')
    at Va (/var/task/.next/server/chunks/832.js:40298:56)
    at Ma (/var/task/.next/server/chunks/832.js:40428:50)
    at Object.toJSON (/var/task/.next/server/chunks/832.js:40159:32)
    at stringify (<anonymous>)
    at Ua (/var/task/.next/server/chunks/832.js:40486:53)
    at Qa (/var/task/.next/server/chunks/832.js:40278:35)
    at ping (/var/task/.next/server/chunks/832.js:40287:32)
2023-02-22T20:24:53.545Z	68a7b9b6-dc69-4a61-ad8d-38f62c7b5ab8	ERROR	[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3462549672'
  ```
  
  
  

### Expected Behavior

It should render the page

### Which browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

vercel

**Comment by mwawrusch** [comment]
FYI, the regression happens from 13.1.7-canary.10 to 13.1.7-canary.11

**Comment by xvvvyz** [comment]
@mwawrusch are you still having this issue on the latest release?

**Comment by mwawrusch** [comment]
Last I checked was 13.2.0 and same issue there

**Comment by xvvvyz** [comment]
I was facing a similar error but it turns out I just needed to remove these from my `experimental` next config:

```
serverComponentsExternalPackages: [
  '@supabase/supabase-js',
  '@supabase/auth-helpers-nextjs',
]
```

Probably no help to you—nested layouts are working fine for me on the latest version.

**Comment by mwawrusch** [comment]
> I was facing a similar error but it turns out I just needed to remove these from my `experimental` next config:
> 
> ```
> serverComponentsExternalPackages: [
>   '@supabase/supabase-js',
>   '@supabase/auth-helpers-nextjs',
> ]
> ```
> 
> Probably no help to you—nested layouts are working fine for me on the latest version.

Thx, but my experimental only contains the appDir flag. Do you per any chance know how I can get vercel to not remove the detailed log output in production? That would help.

**Comment by mwawrusch** [comment]
Good news, the bug seems to be gone with next version 13.2.1

**Comment by xvvvyz** [comment]
> Do you per any chance know how I can get vercel to not remove the detailed log output in production?

I do not. Ended up debugging through trial and error.. Would like to know how to do this as well.

**Comment by balazsorban44** [comment]
Closing based on https://github.com/vercel/next.js/issues/46266#issuecomment-1445168503. If you see this resurfacing or have a similar issue, please open a new bug report. :pray:
