### ISSUE TITLE
New NextJS project with Typescript does not lint typescript upon `npm run lint`

### ISSUE THREAD

**Issue by cat-michael-gwynne** [vercel/next.js#46294]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.1.7-canary.28
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

ESLint (eslint-config-next), TypeScript

### Link to the code that reproduces this issue

-

### To Reproduce

- `npx create-next-app`
- Name project
- Select Yes for Typescript
- Select Yes for ESLint
- Use defaults for other options
- cd into your directory
- `npm install next@canary`
- Open src/pages/_app.tsx and change App to return `boolean` instead of `AppProps`
- `npm run lint`
- Notice no errors

### Describe the Bug

When setting up a new NextJS project with Typescript and ESLint, I would expect `npm run lint` to error if there is a Typescript error in the code.
But it does not.

### Expected Behavior

When setting up a new NextJS project with Typescript and ESLint, I would expect `npm run lint` to error if there is a Typescript error in the code.

**Comment by balazsorban44** [comment]
Linting and type-checking are two different operations.

You can add a script `"type-check": "tsc"` (note, we already default to `noEmit: true` in the `tsconfig.json` file.).

Alternatively, `next build` will run both linting and type-checking already.
