### ISSUE TITLE
[NEXT-622] Reexporting client components causes them to be undefined

### ISSUE THREAD

**Issue by jankaifer** [vercel/next.js#46293]
**Client components import**

When importing client components via an exporting index, the imported components are undefined.
While importing them via the direct path, it's imported correctly.

```js
// components/index.ts
export * from './CompA';
export * from './CompB';

// app/page.tsx
// Both are undefined
import { CompA, CompB } from '../components';

// This works
import { CompA } from '../components/CompA';
import { CompB } from '../components/CompB';
```

_Originally posted by @alexismch in https://github.com/vercel/next.js/discussions/41745#discussioncomment-4946305_
      

<sub>[NEXT-622](https://linear.app/vercel/issue/NEXT-622/reexporting-client-components-causes-them-to-be-undefined)</sub>

**Comment by icyJoseph** [comment]
- https://github.com/vercel/next.js/issues/46293
- https://github.com/vercel/next.js/discussions/46227#discussioncomment-5080421

A couple more reports of this issue.

**Comment by DuCanhGH** [comment]
@icyJoseph I also want to add #41940, which might be helpful to the maintainers :D 
It seems that this issue only happens in dev mode, and exporting client components through barrel files works just fine in production (both static and dynamic).

**Comment by shuding** [comment]
Using `export *` inside a client boundary (a file with “use client”) is not currently supported, and an error should be displayed on the CLI. So this is a planned thing to work on rather than a bug.

**Comment by DuCanhGH** [comment]
@shuding in this case `./components/index.ts` is not inside a client boundary, it just exports client components from 2 other files that are marked with "use client". I'd say this is a bug tbh, as it behaves differently between dev and prod. At least it should throw an error in both, right?
