### ISSUE TITLE
[NEXT-627] Type imports from next package break with `typedRoutes: true`

### ISSUE THREAD

**Issue by pf1gura** [vercel/next.js#46320]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      next: 13.2.0
      eslint-config-next: 13.2.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-rlge1y?file=app/page.tsx

### To Reproduce

Create new project with app directory, add `typedRoutes: true` to `next.config.js`, import a type from `next` package (e.g. new `Metadata`) and then try to build the app with `next build`

### Describe the Bug

Above error produces `Type error: Module '"next"' has no exported member 'Metadata'` error

![image](https://user-images.githubusercontent.com/41795518/221026513-566ba316-a25b-470c-8e30-deea1a86d2fb.png)

### Expected Behavior

`import type { Metadata } from 'next';` should not break the app

<sub>[NEXT-627](https://linear.app/vercel/issue/NEXT-627/type-imports-from-next-package-break-with-typedroutes-true)</sub>

**Comment by bhbs** [comment]
The module declarations for `next/link` and `next` are described in link.d.ts. They are ambient module declarations, but `next` needs to be a module augmentation.
https://github.com/microsoft/TypeScript/blob/ccf3d3c5f9b4bc2883d700870ed2dac454050f1f/src/compiler/utilities.ts#L794-L805

Can I create a PR today? Or, If it is urgent, I leave it to the maintainers.
