### ISSUE TITLE
[NEXT-647] Throws `Illegal invocation` when I called the edge route handler from the client

### ISSUE THREAD

**Issue by taishikato** [vercel/next.js#46337]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.10
      pnpm: 7.27.1
    Relevant packages:
      next: 13.2.1-canary.0
      eslint-config-next: 13.2.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/taishikato/repurpose-tweet/tree/route-handler

### To Reproduce

1. Run the app with `pnpm run dev`
2. Logged in with Google account
3. Click `Elon Musk`
4. Click `Stoner` button

An error shows up in the fourth one.

https://user-images.githubusercontent.com/980588/221077035-1ae55b51-fab5-4c67-8234-fe70c3a173fc.mp4

### Describe the Bug

When I called the API from the front-end, this error occurred.
It works fine on my local (Node `v18.14.2`), but it doesn't on Vercel.

I have 2 APIs and the `Node` runtime one works fine, but the `Edge` runtime one causes the error.

<img width="1285" alt="CleanShot 2023-02-23 at 18 17 30@2x" src="https://user-images.githubusercontent.com/980588/221075761-a2ebb4c5-6b5c-4528-bfd6-08c87f379c70.png">

### Expected Behavior

Succeed to call the API.

<sub>[NEXT-647](https://linear.app/vercel/issue/NEXT-647/throws-illegal-invocation-when-i-called-the-edge-route-handler-from)</sub>

**Comment by davidknezic** [comment]
Same here, we get `TypeError: Illegal invocation` when reading the `POST` body in our edge-based route handler:

```ts
import { type NextRequest } from 'next/server';

export const config = {
  runtime: 'edge',
};

export async function POST(request: NextRequest) {
  // the line below fails
  const body = await request.json();

  // ...
}
```

There's no issue when reading the `POST` body in non-edge route handlers.

**Comment by greidinger-reis** [comment]
Getting the same error here when reading the `PUT` body in a edge route handler in the new `/app` route handler.

Only when deployed at Vercel, on dev environment there's no errors.

```ts
export async function PUT(req: NextRequest) {
    const body = await req.json();
    // ...
}
```

The error is logged as below:

```bash
TypeError: Illegal invocation
    at (src/app/api/contact/route.ts:7:27)
    at (node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/future/route-handlers/app-route-route-handler.js:264:0)
    at (node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/async-storage/static-generation-async-storage-wrapper.js:28:0)
    at (node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/async-storage/static-generation-async-storage-wrapper.js:3:50)
    at (node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/future/route-handlers/app-route-route-handler.js:173:9)
    at (node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/async-storage/request-async-storage-wrapper.js:61:0)
    at (node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/async-storage/request-async-storage-wrapper.js:26:41)
    at (node_modules/.pnpm/next@13.2.3_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/esm/server/future/route-handlers/app-route-route-handler.js:170:0)
```

**Comment by paulsp94** [comment]
Getting the same error when trying to resolve `res.json()` in prod. Working in local environment.

**Comment by igorxmath** [comment]
Same problem here using POST method on vercel edge functions. Local env works fine

**Comment by HeisenCode007** [comment]
Have the same issue, it would be nice to be able to run POST handlers on edge

**Comment by LukasBacevicius** [comment]
Have the same issue, any possible workaround for this?

**Comment by steven-tey** [comment]
This seems to be an issue with [Route Handlers](https://beta.nextjs.org/docs/routing/route-handlers) – an edge function inside the `pages/api` folder works as expected.

I've notified the Next.js team about this issue and we're actively looking into it 🙏

**Comment by taishikato** [comment]
Thanks @steven-tey 🥳

**Comment by steven-tey** [comment]
Good news: this has been fixed in latest canary <picture data-single-emoji=":cele-cry:" title=":cele-cry:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..3BV-zxkjSFZtHVxr.zeyoVzfjv0PEfOh5AFs5KNd2SVACKljgk1vRbyIuL7dzBvZB9rk6mfIq-iCPH6S3OcEBY9Veb7Py9U-QRFBKR0F1_3cMKDqD99cspgyaEVMwsa8Yd9gERPHJ.dmX8YYMtJjgmDhd4vQ2v3w" alt=":cele-cry:" align="absmiddle"></picture> 

Just update Next.js to latest canary (yarn upgrade next@canary`) and it should work! <picture data-single-emoji=":yayawesome:" title=":yayawesome:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..m5pyi3ilX_rrE1G3.ia34xpZuQtj8nO7Y8l-O0yXIELX3JWvjf3AJy5r-mxziX115gvV5ir1Dg8M9TcnYLmdRyUZFmJ1VsO8dZmVovJny2NTF5uURnU0Ve27r7rjonXTHDWZIVQCel-Q.L9QJP6_3LjntJjIkZ4wIfQ" alt=":yayawesome:" align="absmiddle"></picture>

**Comment by taishikato** [comment]
Thank you @steven-tey and Vercel team!

**Comment by mushan0x0** [comment]
Can I ask what screen recording software you are using? 🤣

**Comment by taishikato** [comment]
@mushan0x0 https://www.screen.studio/ 👍
