### ISSUE TITLE
cookies serialize decodeURIComponent  %* URI malformed error not catch result 500 server error

### ISSUE THREAD

**Issue by okbeng03** [vercel/next.js#46336]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.17
      pnpm: 7.18.1
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.0.4
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

the code https://github.com/vercel/next.js/blob/canary/packages/next/src/compiled/%40edge-runtime/cookies/index.js#L49

### To Reproduce

1. use middleware
2. request cookie has string %，like 'NowClick=nav3@%u8BA2%u5355%u67E5%u8BE2; ' 

### Describe the Bug

cookies serialize decodeURIComponent  %* URI malformed error not catch result 500 server error

### Expected Behavior

try catch the error, don't result 500 server error

### How are you deploying your application? (if relevant)

next start

**Comment by okbeng03** [comment]
I has saw the code in next@canary, has the same problem

**Comment by balazsorban44** [comment]
Could you attach a reproduction? 🙏

**Comment by okbeng03** [comment]
sorry, i just try next@canary, is ok
