### ISSUE TITLE
"Fetch" is also cached for "POST" requests

### ISSUE THREAD

**Issue by semy** [vercel/next.js#46349]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-hg91jc

### To Reproduce

1. Start the project and open the home page.
2. Click on the post link first: "TikTok Geld verdienen".
3. On the next page you will see the exact post title.
4. Click "Back to Index".
5. Now click on the category: "Online Business Anleitungen".
6. On the next page, the post title will be displayed again. However, the category name should be displayed.

Two notes:
1. I could reproduce the error only on my Mac (Apple M1 Max). I think it works on Linux for example. On the stackblitz link it works correctly for example.
2. According to the documentation, "POST" fetch requests should not be cached, however I always get a cached result from the second request on, which causes the error (I have already investigated deeper). For example, when I execute the query to retrieve the category, I get the result of the post query.

### Describe the Bug

1. The fetch function apparently also caches POST requests.
2. The result of the first GraphQL request is cached and then returned for all further GraphQL requests.

### Expected Behavior

1. POST requests should not be cached, unless I use "cache" from React (as described in the documentation).
2. If POST requests are cached lately, then only "same requests" should be cached.

### Which browser are you using? (if relevant)

Chrome 110.0.5481.77

### How are you deploying your application? (if relevant)

npm run dev

**Comment by micmc422** [comment]
Same issues on Windows 11.

GraphQL return last query and switch cache to "no-store" break static pages.

fetch cache use target url as index. on POST it should include body data, maybe an hash ?

**Comment by dotellie** [comment]
I have a feeling I'm also running into this but with the app directory though I assume they use the same mechanism.

**Comment by Zyzle** [comment]
I'm seeing an error relating to this too,  I'm using fetch to retrieve graphql endpoints and build my pages. Everything works fine in dev mode but as soon as I try and create a build of my site all the pages fail.

It started with `13.1.7-canary.28` (27 was fine)

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.2.2-canary.1` of Next.js, please update and give it a try!
