### ISSUE TITLE
[NEXT-644] cookies broke on 13.2.1 Invariant: Method expects to have requestAsyncStorage, none available

### ISSUE THREAD

**Issue by cipriancaba** [vercel/next.js#46356]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Fri Feb 24 2023 12:23:18 GMT+0200 (Eastern European Standard Time)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.2.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-gqeapg?file=package.json,app%2F[variant]%2F(shop)%2Fp%2F[[...id]]%2Fpage.tsx,next.config.js

### To Reproduce

Try to import cookies from `next/headers`
Try to access a dynamic page, eg `/test/p`

### Describe the Bug

Error: Invariant: Method expects to have requestAsyncStorage, none available

This happens if I do an import of cookies

```
import { cookies } from 'next/headers';

const DynamicPage = async () => {
  const nextCookies = cookies();
  console.log(nextCookies.get('random'));
  const data = await loadRandomData();

  return <div>{data.title}</div>;
};
```

![Screenshot 2023-02-24 at 12 26 31](https://user-images.githubusercontent.com/695515/221155519-8a149462-8b68-4db5-9a0e-75004f75a8b9.png)

### Expected Behavior

I can access the cookies object on a dynamic page

<sub>[NEXT-644](https://linear.app/vercel/issue/NEXT-644/cookies-broke-on-1321-invariant-method-expects-to-have)</sub>

**Comment by destino92** [comment]
I'am also facing this issue we are setting cookies for internationalization

**Comment by ayhanap** [comment]
Not sure if its related but happens when I access cookies() outside of an async function.

```
import { cookies } from 'next/headers';

//gives same error when used here
const hello = cookies().get('access_token')?.value;

export default async function FeedbackPage(props: FeedbackPageProps) {

//works ok inside here
....
...
}
```

**Comment by frankimhof** [comment]
I also get this error.

I am using experimental App directory (appDir: true).

I get the error when calling `getServerSession` (imported from [next-auth](https://next-auth.js.org/))
inside of an [API Route](https://nextjs.org/docs/api-routes/introduction) handler function.

**Comment by talbertherndon** [comment]
> I also got this error, but was able to fix it.
> 
> I am using experimental App directory (appDir: true).
> 
> I got the error when calling `getServerSession(authOptions)` (imported from [next-auth](https://next-auth.js.org/)) inside of an [API Route](https://nextjs.org/docs/api-routes/introduction) handler function.
> 
> Fixed it by also providing `req` and `res` (from the API Route handler) as arguments to `getServerSession`: `getServerSession(req, res, authOptions)`

Where exactly is this file and how are you calling user session?

**Comment by jgb-solutions** [comment]
@talbertherndon `import { ServerResponse } from "http"`

**Comment by VyMajoris** [comment]
> I also got this error, but was able to fix it.
> 
> I am using experimental App directory (appDir: true).
> 
> I got the error when calling `getServerSession(authOptions)` (imported from [next-auth](https://next-auth.js.org/)) inside of an [API Route](https://nextjs.org/docs/api-routes/introduction) handler function.
> 
> Fixed it by also providing `req` and `res` (from the API Route handler) as arguments to `getServerSession`: `getServerSession(req, res, authOptions)`

This would not work for me because I'm using `getServerSession` inside a multer `fileFilter` function, I don't have access to the response there. At least not that I'm aware.

**Comment by jgb-solutions** [comment]
You get the request out of the context passed to getServersideProps' context.

**Comment by VyMajoris** [comment]
> You get the request out of the context passed to getServersideProps' context.

I know, but this is on an API: https://github.com/Global-Conflicts-ArmA/global-conflicts-website/blob/main/pages/api/missions/%5BuniqueName%5D/update.ts#L89

I'm trying some hacks to see if I can get the session there.

**Comment by dlamprey** [comment]
is this still an issue in @latest? 

├─┬ @next-auth/mongodb-adapter@1.1.1
│ └─┬ next-auth@4.22.0
│   └── next@13.3.4 deduped
├─┬ eslint-config-next@12.0.7
│ └── next@13.3.4 deduped
└── next@13.3.4

I am getting the error with this (in pages/api):

import { cookies } from 'next/headers';

export default async function handler(req, res) {
const cookieKey = 'some-cookie-key';
console.log('cookieValue', cookies().get(cookieKey))

Error:

error - node_modules\next\dist\client\components\headers.js (56:14) @ cookies
error - Error: Invariant: Method expects to have requestAsyncStorage, none available
    at cookies (webpack-internal:///(api)/./node_modules/next/dist/client/components/headers.js:52:15)
    at handler (webpack-internal:///(api)/./pages/api/setGetReaction.js:27:91)

**Comment by reesmanp** [comment]
I am getting this error on latest and with canary.

**Comment by joaodobread** [comment]
I'm getting this error too. Using version "13.3.4" and following the code in the example on the docs page:
```
import { cookies } from "next/headers";

export default function Page() {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  return "...";
}
```

**Comment by dlamprey** [comment]
> I am getting this error on latest and with canary.

@reesmanp nice to know it is not just me. is this broken for everyone? are other just getting the cookie on the front end? i am wondering why others aren't speaking up. i would hate to downgrade to 12.x.

**Comment by verdrangen** [comment]
> > I am getting this error on latest and with canary.
> 
> @reesmanp nice to know it is not just me. is this broken for everyone? are other just getting the cookie on the front end? i am wondering why others aren't speaking up. i would hate to downgrade to 12.x.

Same here. Trying to access headers but having this issue too.

**Comment by RobinNagpal** [comment]
I get it in my Root Layout in nextjs 13

```
interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions);
```

Here is the error
```
warn  - Fast Refresh had to perform a full reload due to a runtime error.
error - node_modules/next/dist/client/components/headers.js (39:14) @ headers
error - Error: Invariant: Method expects to have requestAsyncStorage, none available
    at RootLayout (./src/app/layout.tsx:34:86)
n
```

**Comment by reesmanp** [comment]
>  i would hate to downgrade to 12.x.

I don't think you need to downgrade. Since this is the app directory and in 13 you don't need to use the app directory and the pages directory is stable, you can maintain using 13. We're using v13 on pages but are looking to migrate to app.

**Comment by reesmanp** [comment]
@wyattjoh it looks like the code path for retrieving cookies and headers calls `new globalThis.AsyncLocalStorage()` then immediately calls `getStore` without a `run` or `enterWith` function call... Where exactly is the context supposed to be coming from?

**Comment by reesmanp** [comment]
Downgrading to 13.2.0 (from 13.4.0), it works.

**Comment by dlamprey** [comment]
thanks @reesmanp for sharing your insight about this issue. i was pretty sure I tried 13.2.0 before but just did so again and am getting the same error:

error - node_modules\next\dist\client\components\headers.js (34:14) @ cookies
error - Error: Invariant: Method expects to have requestAsyncStorage, none available
    at cookies (webpack-internal:///(api)/./node_modules/next/dist/client/components/headers.js:34:15)

├─┬ @next-auth/mongodb-adapter@1.1.1
│ └─┬ next-auth@4.22.0
│   └── next@13.2.0 deduped
├─┬ eslint-config-next@12.0.7
│ └── next@13.2.0 deduped
└── next@13.2.0

**Comment by lk9100** [comment]
on the latest 13.4.1 release, having the same issue.

**Comment by salvinoto** [comment]
Having this issue as well, using server actions on 13.4.1 release

**Comment by SvemirskiHod** [comment]
Having the same issue with server actions on 13.4.1

**Comment by vitalyliber** [comment]
@lk9100 @salvinoto @SvemirskiHod just upgrade NextJS to the v13.4.2-canary.3 version.

**Comment by lk9100** [comment]
> @lk9100 @salvinoto @SvemirskiHod just upgrade NextJS to the v13.4.2-canary.3 version.

have just installed v13.4.2-canary.3 
same error

<img width="306" alt="Screenshot 2023-05-09 at 20 54 26" src="https://github.com/vercel/next.js/assets/1432536/cd957c25-86d8-4ff0-8763-bcad2b517dbc">

<img width="742" alt="Screenshot 2023-05-09 at 20 50 55" src="https://github.com/vercel/next.js/assets/1432536/8683db88-47c5-484c-b50d-bc1665111671">

**Comment by tmns** [comment]
^^ Also on 13.4.2-canary.3 and getting the same error when invoking `getServerSession` from a server action.

**Comment by hgogoi2012** [comment]
I am also getting the same error.

**Comment by timneutkens** [comment]
Hey, could you open a new issue with a reproduction so that we can have a look?

**Comment by lwensveen** [comment]
Don't have this error anymore either, but session always returns null when calling `const session = await getServerSession(authOptions);` in the RootLayout

**Comment by lukevers** [comment]
Hey @timneutkens, let me see if I can get a reproduction for you, but I just got this same error while testing transitioning a server action passed down from the page to a client component to having the client component have direct access to it. I just upgraded my dependencies and see this exact issue.

**Comment by lukevers** [comment]
@timneutkens https://github.com/lukevers/next-644

I have two pages that define two situations:

* `/issue1` - "individual server components" - The main issue here is that when we access cookies through a server component imported from a client component, it does not work. It works if we import it in a server component (page layout here) and pass it to the client component as a prop.
* `/issue2` - "shared server component" - The issue here is that when we access cookies through a server component imported from a client component, it does not work. It also does not work even if it was passed through to the client component if the server component is the same component

**Comment by lukevers** [comment]
@timneutkens I came to the conclusion this is related to next-auth after my related closed issue ([here](https://github.com/nextauthjs/next-auth/issues/7523)), but I wanted to debug it more so I copied the code locally and when I use the same code (but not imported from the library), grabbing my session information works.

```ts
import { getServerSession } from 'next-auth/next';
import { __internal__unstable__getSession } from './_internal_session';

// uses from next-auth
export async function getSession() {
  return await getServerSession({});
}

// uses a copied version locally
export async function __unstable__getSession() {
  return await __internal__unstable__getSession({});
}```

Is there anyway this could somehow be related to the bundler?

**Comment by AmmarR0118** [comment]
i only get this error when any of the server actions is imported inside client component

**Comment by Hiieu** [comment]
Can we re-open the issue? This error is still happening in `v13.4.4-canary.0`.

**Comment by Hiieu** [comment]
What I did to solve the problem is to replace the entire cookies implementation from NextJS with the [cookies-next](https://www.npmjs.com/package/cookies-next) library.

**Comment by timneutkens** [comment]
Please see my earlier comment, we can investigate if you provide a reproduction in a new issue, instead you're posting additional comments here without a reproduction 😢 https://github.com/vercel/next.js/issues/46356#issuecomment-1543653146
