### ISSUE TITLE
[NEXT-671] Next.js 13.2.1 - Module '"next/navigation"' has no exported member 'usePathname'.

### ISSUE THREAD

**Issue by TadejPolajnar** [vercel/next.js#46360]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release1

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
Binaries:
  Node: 16.15.1
  npm: 8.11.0
  Yarn: 1.22.19
  pnpm: 7.18.2
Relevant packages:
  next: 13.2.1
  eslint-config-next: 13.2.1
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

[https://stackblitz.com/edit/nextjs-q4nrme?file=package.json,tsconfig.json,pages%2Findex.tsx](https://stackblitz.com/edit/nextjs-q4nrme?file=package.json,tsconfig.json,pages%2Findex.tsx)

### To Reproduce

```
import { usePathname } from 'next/navigation';

export default function Home() {
  const pathname = usePathname();

  return <div>Pathname: {pathname}</div>;
}
```

### Describe the Bug

Hook usePathname works as expected, it returns current path name however **typescript throws an error** which doesn't allow you to build the page.
Typescript error:  `Module '"next/navigation"' has no exported member 'usePathname'.`

As a temporary solution I used `// @ts-ignore` to suppress the error for now.

### Expected Behavior

Typescript type of `usePathname` needs be exported correctly and typescript error should disappear.

### Which browser are you using? (if relevant)

*No response*

### How are you deploying your application? (if relevant)

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-671](https://linear.app/vercel/issue/NEXT-671/nextjs-1321-module-nextnavigation-has-no-exported-member-usepathname)</sub>

**Comment by lionelrudaz** [comment]
Same issue with useSearchParam.

Here's my code: 

```
"use client";

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { CaretLeft } from 'phosphor-react';

type Props = {
  defaultUrl?: string
  style?: "flat" | "shadow"
}

const BackButton = ({
  defaultUrl,
  style
}: Props) => {
  const searchParams = useSearchParams();
  const returnUrl = searchParams.get('returnUrl') ?? defaultUrl;
  
  return (
    <Link
      href={`${returnUrl ? returnUrl : "/"}`}
      className={`mr-auto rounded-full p-2 flex items-center justify-center ${style === "shadow" ?  "bg-white shadow-md" : "bg-gray-200"}`}
      passHref
    >
      <CaretLeft size={24} color="black" weight="regular" />
    </Link>
  )
};

export default BackButton;
```

Was working with NextJS 13.1, not working anymore after the update to Next 13.2.

I hope this helps.

**Comment by TadejPolajnar** [comment]
@lionelrudaz you need to insert it right before the problematic row, here is an example:

```tsx
import Image from 'next/image'
import {useMemo} from "react";
// @ts-ignore
import { usePathname } from 'next/navigation';
```

**Comment by lionelrudaz** [comment]
@TadejPolajnar it works as a temporary fix :)

**Comment by ooyay** [comment]
make sure navigation types is exist in next-env.d.ts

```
/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/navigation" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.

```

**Comment by TadejPolajnar** [comment]
@ooyay `next-env.d.ts` changes every time you build the app or run development.

**Comment by TadejPolajnar** [comment]
Based on a review I received on proposed PR, this is expected behavior `usePathname` can only be used inside app directory.

**Comment by ooyay** [comment]
> @ooyay `next-env.d.ts` changes every time you build the app or run development.

I don't know, but the error was coming up until this line comes

**Comment by kevin-courbet** [comment]
I'm still getting this error in my App directory project... don't think this is fixed. 13.2.1

**Comment by AlanMorel** [comment]
I can also confirm that I'm also getting this issue when upgrading to 13.2.

My project is an app directory project as well. I don't think this issue should be closed.

**Comment by sabbircste** [comment]
Module parse failed: Unexpected token (6:5) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

**Comment by kieranm** [comment]
Also seeing this issue in the app directory in 13.2. @TadejPolajnar I would suggest reopening.

**Comment by balazsorban44** [comment]
So it looks like the OP's issue is that they are trying to use `next/navigation`, while `appDir: true` is not enabled in the `next.config.js` file, as well as there is no `app` directory present. These conditions are the current requirement for us to correctly update the `next-env.d.ts` file for those types to be included.

**Comment by kieranm** [comment]
We are using the `app` folder and have `appDir: true` and ran into this issue. I think (I could be wrong) we needed to run `next dev` in order to have the types be updated. `next dev` isn't run in CI environments which is which is why our builds started failing after Dependabot tried to bump the version. Does this sound right?

**Comment by kieranm** [comment]
It seems like `next build` also adds the correct types so I can't really explain this. In any case it seems to have added the correct types now.

**Comment by Willem-Jaap** [comment]
Also having this issue, indeed the issue seems to be that the next-env.d.ts is not updated in the linting proces.

```bash
42:11  Error: Unsafe assignment of an `any` value.  @typescript-eslint/no-unsafe-assignment
42:22  Error: Unsafe call of an `any` typed value.  @typescript-eslint/no-unsafe-call
```

**Comment by wyattjoh** [comment]
In order to get the update to the types, you have to run `next dev` to generate updated `next-env.d.ds` file. Due to how TS type augmentation works, this was a neccesary evil. Once you run that, it should update it to include one of the following:

```ts
/// <reference types="next/navigation-types/navigation" />
/// <reference types="next/navigation-types/compat/navigation" />
```

This was changed in https://github.com/vercel/next.js/pull/45919 to ensure that users who are using both `/pages` and `/app` will have types representative of the hybrid use case.

**Comment by Willem-Jaap** [comment]
I know this is the `next dev` is the fix for **development**, But `next dev` is (and should not be) used in a **pipeline** or **github actions**. 
I have a pipeline which lints all code using 'next lint'. This validates all used types. If these types are not set correctly, It can't validate them, therefore the pipeline failes.

A possible solution is to also generate the file as a `postinstall` step, which would solve the problem.

**Comment by giovanedann** [comment]
Hey! im on 13.2.1 and even after running next dev my declaration file does not set these type declarations lines by default

after running next dev this is the file generated:

`/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
`

**Comment by balazsorban44** [comment]
@kieranm

> We are using the app folder and have appDir: true and ran into this issue. I think (I could be wrong) we needed to run next dev in order to have the types be updated. next dev isn't run in CI environments which is which is why our builds started failing after Dependabot tried to bump the version. Does this sound right?

> It seems like next build also adds the correct types so I can't really explain this. In any case it seems to have added the correct types now.

Since both `next dev` and `next build` update types, this should not be an issue in CI or locally. :thinking:

@Willem-Jaap

> I know this is the fix for development and actually works, but next dev is (and should obviously not be) used in a pipeline or github actions.
I have a pipeline which lints all code using 'next lint'. This validates all used types. If these types are not set correctly, It can't validate them, therefore the pipeline failes.

Fixing this during linting is already tracked here https://github.com/vercel/next.js/issues/46104. (There is also a PR #46249)

@giovanedann 

> Im not using the app directory, im using the pages directory, maybe is something related?

Exactly. This type is generated only when `appDir: true` is set and you have an `app` directory. See my comment https://github.com/vercel/next.js/issues/46360#issuecomment-1446273525

**Comment by giovanedann** [comment]
Oh! i missed this comment, my bad!

So, the solution for that is to refactor the project to use the app directory or lock next in 13.1.6?

**Comment by wyattjoh** [comment]
If you're not using app directory @giovanedann, then you should continue to use `next/router`, `next/navigation` is for use with projects utilizing app directory.

**Comment by giovanedann** [comment]
@wyattjoh sure, appreciate your time! Thank you very much! @balazsorban44

**Comment by jdouglass** [comment]
This might be a long shot here, but I get this exact same error message when I tried using turborepo in their monorepo configuration. I had ui components in a separate package folder, however, those ui components needed useSearchParams and usePathname. Is my only option as of right now is to use `// @ts-ignore` as a temporary fix or is there a better solution for my case?

**Comment by tgroutars** [comment]
Just want to add: This doesn't occur for me with `next lint` (afaik that command doesn't run type checks, just eslint?). But it does happen when I run type checks (`tsc --noEmit`) on github actions.

https://github.com/vercel/next.js/pull/46249 generates `next-env.d.ts` on `next lint` so it won't fix the issue unless `next lint` runs before typechecks. 

Best way would be to have an explicit way to generate `next-env.d.ts`, either in `postinstall` or before running typechecks

**Comment by timinho111** [comment]
Also running into this issue when upgrading from next 13.1.6 to 13.2.1 without changing anything else.

`/// <reference types="next/navigation-types/navigation" />`

is set correctly after running `next dev` but it does not find useSearchParams() and usePathname().

Should next/navigation always been used when using the app directory or should next/router be used when using the router outside of the app directory?

**Comment by ijjk** [comment]
Hi, this has been updated in the latest canary of Next.js, please update and give it a try!
