### ISSUE TITLE
Docs: Beta Docs JSON-LD recommendation is insecure by default

### ISSUE THREAD

**Issue by Eyas** [vercel/next.js#46377]
### What is the improvement or update you wish to see?

The beta SEO docs suggest `dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}`.

Turns out this is vulnerable to XSS and not actually compliant with JSON-LD. e.g. a `name: "abc</script><MOREHTML>"` is valid JSON that stringifies without an escaped `</script>`. The JSON-LD spec gets away with this by adding extra escaping rules for any JSON-LD included inline in an HTML document.

I saw this in google/react-schemaorg#9 and solved this in google/react-schemaorg#10

Either recommend a package that does this already (e.g. my own google/react-schemaorg) or by including a sample of what the escaping looks like (you're free to copy the linked PR, it's licensed under Apache 2.0).

### Is there any context that might help us understand?

google/react-schemaorg#10 has a proper fix. The repro in google/react-schemaorg#9 can be triggered from the beta.nextjs.org docs too.

(I can't find where the beta docs live, otherwise I would have contributed a fix myself)

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/guides/seo#json-ld

**Comment by Fonger** [comment]
Same escape function is used in next.js hydration `__NEXT_DATA__` script

https://github.com/vercel/next.js/blob/b98469c86b74b06b55fc4c59bcf87d034e1919f1/packages/next/src/server/htmlescape.ts#L14-L16

Or consider expose this function so that we can use this function to escape these tags for json.

**Comment by Eyas** [comment]
Note that JSON-LD escape semantics are defined in a separate spec, btw!

**Comment by nitinTJ** [comment]
I am unable to see it, when I am checking the page source

**Comment by leerob** [comment]
It's a fairly naive implementation – I'm open to PRs to back link back to that package, but want to keep the package-less example for quick copy pasting (could have a disclaimer).
