### ISSUE TITLE
[NEXT-660] Fetching from app/api/<route> produces a 405 method not allowed. 

### ISSUE THREAD

**Issue by ericschmar** [vercel/next.js#46375]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Dec 19 20:43:09 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 3.2.4
      pnpm: N/A
    Relevant packages:
      next: 13.2.1-canary.0
      eslint-config-next: 13.2.0
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

n/a

### To Reproduce

Upgraded from 13.0.0 to 13.2.1 (i.e. latest). Migrated `pages/api/route1` to the new `appDir` methodology. Moved it to `app/api/route1/route.ts`. 

`app/api/route1/route.ts`: 
```
export default async function GET(req: Request) {
    const { searchParams } = new URL(req.url);
    const { data, error } = await fetch(process.env.BASE_URL + '/route1' + searchParams)
    return new Response(JSON.stringify({
        data: data ? data : [],
        error: error ?? ""
    }), { status: 200 })
}
```

From within a client component, calling:
```
fetch('/api/route1?query=Query', {method: 'GET'})
```
Returns an error:
```
body: ReadableStream {locked: true}
bodyUsed: true
headers: Headers {append: function, delete: function, get: function, has: function, set: function, %E2%80%A6}
ok: false
redirected: false
status: 405
statusText: "Method Not Allowed"
type: "basic"
url: "http://localhost:3000/api/route1?query=Query"
```

### Describe the Bug

The bug is returning a 405 Method not allowed when the route is defined for a `GET` and explicitly set the method to `GET`. 

### Expected Behavior

The route should be called from within the originating fetch call.

<sub>[NEXT-660](https://linear.app/vercel/issue/NEXT-660/fetching-from-appapiroute-produces-a-405-method-not-allowed)</sub>

**Comment by WoLfulus** [comment]
You should be exporting it as a named handler (`export async function GET`), but you're exporting it as a default instead (`export default async function GET`). 

If there are no plants to default exports besides configuration, I believe next could warn if it detects `route.ts` is exporting default. Any other scenario (like assuming default is always a GET operation would cause a lot of confusion and counter intuitive).

**Comment by timneutkens** [comment]
Yeah we're going to add a warning when using the default export 👍

**Comment by ericschmar** [comment]
@WoLfulus thank you for the easy catch. I knew it had to be something stupid. Looks like I copied and pasted my code from the `pages/api` and changed the function name to `GET`. Should have spent more time reading. Really appreciate it.
