### ISSUE TITLE
Metadata API doesn't work if component is marked with "use client"

### ISSUE THREAD

**Issue by FilipLusnia** [vercel/next.js#46372]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Metadata API doesn't work if component is marked with "use client" - instead, component gets it's metadata from layout.tsx. 
If I remove the "use client" directive, everything works fine.

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-ub2hpm?file=pages%2Findex.tsx

### To Reproduce

Create basic component and export basic metadata object with a title from it. Check if title got paplied to the tab in the browser. Then add "use client" to the top of component and check if title is still displayed.

### Describe the Bug

Metadata API doesn't work if component is marked with "use client" - instead, component gets it's metadata from layout.tsx. 
If I remove the "use client" directive, everything works fine.

### Expected Behavior

Metadata API should work regardless of component being rendered server-side and client-side

**Comment by erwanvivien** [comment]
The new Metadata API allows you to define metadata (e.g. meta and link tags inside your HTML head element) with an explicit metadata configuration in **any layout** or page that is a **Server Component**.<sup>[1]</sup>

[1]: https://nextjs.org/blog/next-13-2#built-in-seo-support-with-new-metadata-api

**Comment by huozhi** [comment]
Hi it's by designed it only works in server components for now

**Comment by verekia** [comment]
For people who use libraries that only work with client-side components (like Chakra UI), we have to split every single `page.js` into server + client files just to set titles. I hope metadata becomes supported in client components because at the moment I have to stick to `head.js`.
