### ISSUE TITLE
[NEXT-651] generateMetadata breaks loading.tsx

### ISSUE THREAD

**Issue by Ayterx** [vercel/next.js#46384]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

https://github.com/ayterx/next-bug

### To Reproduce

adding generateMetadata function to a page and `loading.tsx` file

### Describe the Bug

adding the `generateMetadata` function to a page will ignore `loading.tsx` file

- if there's `loading.tsx` in root it will run instead of `/blog/loading.tsx`

- if there isn't a `loading.tsx` in the root `/blog/loading.tsx` won't run

Also sometime `/blog/loading.tsx` runs after root loading `/app/loading.tsx` 🤷‍♂️

example when navigating `/blog`

/app
--/blog
----page.tsx (with generateMetadata)
----loading.tsx (ignored)
-layout.tsx
-loading.tsx (this will run instead of /blog/loading.tsx)
 
 

### Expected Behavior

.

<sub>[NEXT-651](https://linear.app/vercel/issue/NEXT-651/generatemetadata-breaks-loadingtsx)</sub>

**Comment by dante-sparras** [comment]
Im experiencing this aswell, any updates on this?

**Comment by ayhanap** [comment]
I experience the same, also related to https://github.com/vercel/next.js/issues/45418

**Comment by Ontegor** [comment]
I have the same error

**Comment by huozhi** [comment]
Can you try again with [v13.2.5-canary.33](https://github.com/vercel/next.js/releases/tag/v13.2.5-canary.33) the `blog/loading` is showing up for me @Ayterx

**Comment by Ayterx** [comment]
@huozhi Yes, This has been fixed in [v13.2.5-canary.22](https://github.com/vercel/next.js/releases/tag/v13.2.5-canary.22) with removing `"use client"` in `loading.tsx`

[v13.2.5-canary.20](https://github.com/vercel/next.js/releases/tag/v13.2.5-canary.20) introduce "use client" bug #47796 #47748 #47704

**Comment by huozhi** [comment]
Will close this and follow up the use client issue in those issues mentioned above
