### ISSUE TITLE
Auto-generated `Route` type by `typedRoute` includes route groups

### ISSUE THREAD

**Issue by darthrommy** [vercel/next.js#46401]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 18.14.1
  npm: 9.2.0
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.2.2-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/darthrommy/typedroute-catches-routegroups

### To Reproduce

1. Run `npm run dev`
2. Wait for `.next/types/link.d.ts` to be generated

### Describe the Bug

Route groups are hidden from the actual route hierarchy, but are included in the auto-generated `Route` type.

In my example, routes are defined like this:

1. `/page.tsx` -> `/`
1. `/foo/page.tsx` -> `/foo`
1. `/(group)/bar/page.tsx` -> `/bar`

But I got type error when using `next/link`:

```tsx
// works fine
<Link href="/foo">To Foo</Link>

// throws error
<Link href="/bar">To Bar</Link>

// does not throw
<Link href="/(group)/bar">To Bar</Link>
```

You can also confirm that the `/(group)/bar` type is generated by looking at `.next/types/link.d.ts`.

```ts
type Route<T extends string = string> = 
  | `/${Suffix}`
  | `/(group)/bar${Suffix}`
  | `/foo${Suffix}`  | `/${Suffix}`
  | `/(group)/bar${Suffix}`
  | `/foo${Suffix}`
```

### Temporary Workaround
```tsx
<Link href={"/bar" as Route}></Link>
```

### Expected Behavior

I think route groups should be ignored by route type generations.

**Comment by DuCanhGH** [comment]
They forgot to replace `\` with `/`, again...
