### ISSUE TITLE
[NEXT-692] Metadata Blog / Docs

### ISSUE THREAD

**Issue by erwanvivien** [vercel/next.js#46405]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

https://beta.nextjs.org/docs/api-reference/metadata

I found some errors:
- `referrer: 'origin-when-crossorigin'` should be `referrer: 'origin-when-cross-origin',`
- `import type { Metadata } from "next";` should be `import type { Metadata } from "next/types";`

### Which example does this report relate to?

metadata

### Describe the Bug

Breaks

### Expected Behavior

Not breaks

### To Reproduce

Nothing

<sub>[NEXT-692](https://linear.app/vercel/issue/NEXT-692/metadata-blog-docs)</sub>

**Comment by huozhi** [comment]
> import type { Metadata } from "next"; should be import type { Metadata } from "next/types";

`import type { Metadata } from "next"` should be available as well, do you encounter some problems with it?

**Comment by erwanvivien** [comment]
I'm having `Module '"next"' has no exported member 'Metadata'.ts(2305)`

**Comment by erwanvivien** [comment]
```
./app/layout.tsx:9:15
Type error: Module '"next"' has no exported member 'Metadata'.

   7 |
   8 | import styles from "./Home.module.css";
>  9 | import type { Metadata } from "next";
     |               ^
```

**Comment by damozhang** [comment]
Same issue!

> ./app/layout.tsx:9:15
> Type error: Module '"next"' has no exported member 'Metadata'.
> 
>    7 |
>    8 | import styles from "./Home.module.css";
> >  9 | import type { Metadata } from "next";
>      |               ^

**Comment by dragos199993** [comment]
hey. had the same issue when I updated to 13.2.1, I just only had to restart the Typescript service and it started to work. Not sure if this is a really a fix in all cases, but the type is surely there, most probably TS is only confused.

**Comment by erwanvivien** [comment]
Very wierd, considerind it happens in build too? Shouldn't typescript be restarted on build ?

**Comment by DuCanhGH** [comment]
Do you, by any chance, have `experimental.typedRoutes` enabled? If so, please either upgrade to the latest canary version or temporarily turn it off :)

**Comment by erwanvivien** [comment]
Yes I have it

**Comment by DuCanhGH** [comment]
@erwanvivien then you can try one of those two temporary solutions :) Just needed until `13.2.2` is released, though.

**Comment by huozhi** [comment]
We've fixed the typo in the docs. Closed the issue as imports from `'next'` is expected.

**Comment by erwanvivien** [comment]
Thanks
