### ISSUE TITLE
Standalone output has a response time of >200ms when using app dir

### ISSUE THREAD

**Issue by mschaul** [vercel/next.js#46419]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Standalone mode (output: "standalone")

### Link to the code that reproduces this issue

-

### To Reproduce

- Create a project with the `reproduction-template-app-dir` template
- Add `output: 'standalone'` to `next.config.js`
- Run `npm run build`
- Run `node .next/standalone/server.js`
- Check the page load time in a browser

### Describe the Bug

Every request to a page has a response time of about 200ms. This does not happen with app dir disabled, or if not using standalone output.

With some debugging, I found out that problem is that `.next/server/server-reference-manifest.json` seems to be missing from the generated standalone output. The `loadManifest` function tries to load the file 3 times, with a 100ms timeout between retries, which is where the observed 200ms comes from.

### Expected Behavior

Using standalone output mode should not have a negative effect on page load times.

**Comment by khuezy** [comment]
Thanks for putting this up, I'm experiencing the same issue.

**Comment by shuding** [comment]
@khuezy Thanks for reporting, I'll have that fixed!
