### ISSUE TITLE
[NEXT-663] Link from pages to app folder adds default locale to path

### ISSUE THREAD

**Issue by pirobtumen** [vercel/next.js#46426]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.0
      eslint-config-next: 13.0.5
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Internationalization (i18n), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-xjiqkw?file=next.config.js

### To Reproduce

First, enable `appDir` and `i18n` in your `next.config.js`:

``` js
/** @type {import("next").NextConfig} */
module.exports = {
  reactStrictMode: true,
  experimental: {
    appDir: true,
  },
  i18n: {
    locales: ['es', 'en'],
    defaultLocale: 'es',
  },
};
```

Then create a page in your `pages` directory and a add a different page in the `app` folder. Add a `<Link>` inside the pages folder that points to the page in the app folder. In the example, when you navigate from the home (default locale) to the test page ( / , Link href=/test ) the URL is set to /es/test, but it should be /test. 

### Describe the Bug

Using `next/link` component in the pages directory and pointing it to a path that is rendered using the app folder, if i18n is configured, the default locale is added is to the path.

Pages folder: index.tsx => Link href=/test
App folder: test/page.tsx

Clicking the link from "/" to "/test" results in "/es/test" but it should be just "/test".

### Expected Behavior

Links from pages folder with the default locale, should not add the locale to the path when navigating to a page inside the app folder.

<sub>[NEXT-663](https://linear.app/vercel/issue/NEXT-663/link-from-pages-to-app-folder-adds-default-locale-to-path)</sub>

**Comment by teobler** [comment]
if nobody is working on this, I can try to pick it up

**Comment by ijjk** [comment]
Hi, this appears related to https://github.com/vercel/next.js/pull/47180 please update to the latest and give it a try!
