### ISSUE TITLE
[NEXT-670] Faulty `app/` Static to Dynamic Error When POST fetches are used from layout.tsx

### ISSUE THREAD

**Issue by kulgg** [vercel/next.js#46436]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/kulgg/app-static-to-dynamic-reproduction

### To Reproduce

Start the development server and navigate to /one.
The `app/` Static to Dynamic Error will be shown.

### Describe the Bug

POST request fetches from a layout component inside a dynamic segment route that uses generateStaticParams will lead to a faulty [`app/ Static to Dynamic Error`](https://nextjs.org/docs/messages/app-static-to-dynamic-error).
GET requests work without problems.

On build the should-be SSG routes turn into server-side rendered routes.

### Expected Behavior

As with GET requests, the statically generated dynamic segment routes should be generated for POST requests without problems

### Which browser are you using? (if relevant)

Brave Version 1.48.171 Chromium: 110.0.5481.177 

<sub>[NEXT-670](https://linear.app/vercel/issue/NEXT-670/faulty-app-static-to-dynamic-error-when-post-fetches-are-used-from)</sub>

**Comment by itsuki0927** [comment]
+1

**Comment by semy** [comment]
+1

**Comment by rakoort** [comment]
Similar issue happening here, both on layout and individual page files. GraphQL fetch requests using POST are returning undefined.

I have one header/footer fetch in the root layout and a page fetch under a page slug folder. Interestingly it fetches either one or the other, but never both at the same time. All my fetches have a revalidate setting, but I can load one page fine if I swap out the header/footer fetch revalidate setting with force cache. At this point a route change will trigger the same static to dynamic error as mentioned in the OP.

**Comment by hiddenest** [comment]
How about adding `next: { revalidate: 10 }` to fetch requests?
I had a similar issue with this, and solved by adding `revalidate` option to each requests.
(but don't know why exactly it occurs error)

**Comment by semy** [comment]
For me `next: { revalidate: 10 }` works for POST GraphQL requests locally, but as soon as I roll it out in Production it doesn't work anymore and I get weird results. I have to test it with the last canary.

**Comment by kulgg** [comment]
Interesting `next: { revalidate: 10 } `seems to fix it for me both for the dev and prod server. However it shouldnt be necessary.

**Comment by hiddenest** [comment]
Agree. I'm guessing that the new cache policy in 13.2 is that requests with `revalidate: 0` or no revalidate setting are automatically assumed to be dynamic content. 🤔

**Comment by sairion** [comment]
https://github.com/vercel/next.js/commit/c5336132c3f014441e6991193aa1ad48a39a8937#diff-4c54e369ddb9a2db1eed95fe1d678f94c8e82c540204475d42c78e49bf4f223aR64-R66 not sure, but this diff seems to be triggering it?

**Comment by grimko** [comment]
Similar problem here with `13.2.1`.

My ugly workaround to have both `dev` and `build` work:
```
      next:
        process.env.NODE_ENV === 'development'
          ? { revalidate: 10 }
          : undefined,
```

**Comment by r-martins** [comment]
Similar issue here, already reported here.
If I downgrade from 13.2 (#45134) to 13.1.6-canary.0 it works.

**Comment by semy** [comment]
But when you downgrade you have other problems with fetch. So this is no Solution.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.2.3-canary.1` of Next.js, please update and give it a try!

**Comment by r-martins** [comment]
Thanks a lot @ijjk .
Couldn't be faster! thanks 💯
