### ISSUE TITLE
[next/codemod]: Type-only imports not preserved when using `next-image-to-legacy-image`

### ISSUE THREAD

**Issue by JohnDaly** [vercel/next.js#46459]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.19
      pnpm: 7.1.7
    Relevant packages:
      next: 13.2.2-canary.1
      eslint-config-next: 13.2.2-canary.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-cw9gs5?file=pages/index.tsx

### To Reproduce

Add a type-only import from the `next/image` package (e.g. `import type { ImageProps } from 'next/image';`)

Run `npx @next/codemod next-image-to-legacy-image . --force`

### Describe the Bug

Type-only imports are not preserved when running the `next-image-to-legacy-image` codemod

### Expected Behavior

I expect that the `type` keyword will be preserved when running the codemod:

## Expected
```ts
import type { ImageProps } from 'next/image';

// Becomes:

import type { ImageProps } from 'next/legacy/image';
```

## Actual
```ts
import type { ImageProps } from 'next/image';

// Becomes:

import { ImageProps } from 'next/legacy/image';
```

**Comment by timneutkens** [comment]
Fixed in #46460, thanks for the PR!
