### ISSUE TITLE
[NEXT-680] Help! Can't run the development server

### ISSUE THREAD

**Issue by ricomuh** [vercel/next.js#46497]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I can not run the development server either using npm run dev or yarn dev. I install new nex.js projects multiple times but it has the same result.

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), SWC minifier (swcMinify: true), SWC transpilation

### Link to the code that reproduces this issue

https://github.com/ricomuh/my-app

### To Reproduce

When I run dev with the project that using app/ dir it's end in `info  - Using wasm build of next-swc`
![image](https://user-images.githubusercontent.com/76117803/221595666-784f2938-a74c-45d2-b2e8-54c970051d43.png)

But when I run the project that using `pages/` dir it's end in `ready - started server on 0.0.0.0:3000, url: http://localhost:3000` 
![image](https://user-images.githubusercontent.com/76117803/221595819-6b37687e-752d-467a-a23f-111c4471d0fe.png)

### Describe the Bug

 the terminal is ended when I run the dev server, I use git bash, tabby, and vscode terminal.

### Expected Behavior

it supposed to run normally.

### Which browser are you using? (if relevant)

Chrom 110.0.5481.177

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-680](https://linear.app/vercel/issue/NEXT-680/help-cant-run-the-development-server)</sub>

**Comment by balazsorban44** [comment]
Seems to be an OS-specific issue, I cannot reproduce it under Linux. :thinking:

The terminal output does not show any useful information though, so we might be swallowing some errors, will have to look more into this.

**Comment by ricomuh** [comment]
> Seems to be an OS-specific issue, I cannot reproduce it under Linux. :thinking:
> 
> The terminal output does not show any useful information though, so we might be swallowing some errors, will have to look more into this.

Well, I can run next projects that already installed before but not the projects that I installed since yesterday

**Comment by timneutkens** [comment]
Just ran the reproduction on codesandbox and couldn't reproduce either, you can view it here: https://codesandbox.io/p/github/ricomuh/my-app/main?file=%2FREADME.md

There's no much we can do to investigate this further without additional information like the output of `next info`.

**Comment by balazsorban44** [comment]
I tried and could not reproduce it on Windows either. 

An option is to try `next@canary` to see if it has been fixed, but for now, I'll move this to discussions.

If you still think it's a Next.js bug, please open a new issue with a proper reproduction, and system details (`next info`). :pray:
