### ISSUE TITLE
[NEXT-693] next/script with loading strategy inside rootLayout, causes error when it's not TypeScript

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#46549]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.3
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

ESLint (eslint-config-next), Script optimization (next/script)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-6bcyqf

### To Reproduce

Create a ``rootLayout`` with JavaScript: 

```javascript
// app/layout.js
import Script from "next/script";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script src="http://1.1.1.1/test.js" strategy="beforeInteractive" />
    </html>
  );
}
```
You will get an error that you should not use ``next/script`` with a loading strategy outside of `pages/_document.js`, now create the same layout, but with TypeScript, you will get no error on the frontend.

```tsx
// app/layout.tsx
import Script from "next/script";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Script src="http://1.1.1.1/test.js" strategy="beforeInteractive" />
    </html>
  );
}
```

`yarn lint` will fail on both cases.

### Describe the Bug

If you use ``next/script`` with a loading strategy inside a TypeScript ``rootLayout``, everything works fine, as described in the beta docs: https://beta.nextjs.org/docs/api-reference/components/script#beforeinteractive

When you try the same inside a ``rootLayout`` which is not TypeScript, you get following error:
> `next/script`'s `beforeInteractive` strategy should not be used outside of `pages/_document.js`. See: https://nextjs.org/docs/messages/no-before-interactive-script-outside-documenteslint[@next/next/no-before-interactive-script-outside-document](https://nextjs.org/docs/messages/no-before-interactive-script-outside-document)

When you run ``yarn lint`` you will get the error for both cases (`layout.js` and `layout.tsx`).

### Expected Behavior

Get no error at all, since the beta docs say it's okay, to use next/script with a straategy inside `rootLayout`.

<sub>[NEXT-693](https://linear.app/vercel/issue/NEXT-693/nextscript-with-loading-strategy-inside-rootlayout-causes-error-when)</sub>

**Comment by timneutkens** [comment]
Keep in mind that regardless of the eslint errors the provided code needs to render `<Script>` in `<body>` not in `<html>`

```tsx
import Script from "next/script";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
		{children}
         <Script src="http://1.1.1.1/test.js" strategy="beforeInteractive" />
	</body>
    </html>
  );
}
```

**Comment by ciruz** [comment]
@timneutkens yes, but its a 1:1 copy from the next.js beta docs example:

![image](https://user-images.githubusercontent.com/987947/221852832-d02fdab5-e2a5-483e-b102-0a6f123673dc.png)

**Comment by timneutkens** [comment]
Will get that fixed!

**Comment by JanKaifer** [comment]
IN the reproduction, I get the eslint warning for `.tsx` too:
```
./app/layout.no.js
7:7  Warning: `next/script`'s `beforeInteractive` strategy should not be used outside of `pages/_document.js`. See: https://nextjs.org/docs/messages/no-before-interactive-script-outside-document  @next/next/no-before-interactive-script-outside-document

./app/layout.tsx
11:7  Warning: `next/script`'s `beforeInteractive` strategy should not be used outside of `pages/_document.js`. See: https://nextjs.org/docs/messages/no-before-interactive-script-outside-document  @next/next/no-before-interactive-script-outside-document
```

**Comment by ciruz** [comment]
Local on Windows I only get it on JS, on stackblitz for both.
