### ISSUE TITLE
Docs: next/script documentation for stable and beta is not consistent

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#46551]
### What is the improvement or update you wish to see?

The documentation for `beforeInteractive` on [beta](https://beta.nextjs.org/docs/api-reference/components/script#beforeinteractive) and on [stable](https://nextjs.org/docs/api-reference/next/script#beforeinteractive) is not consistent.

On stable `<Script>` renders inside `<body>`, but on beta it renders inside `<html>`.

### Is there any context that might help us understand?

@timneutkens just pointed out https://github.com/vercel/next.js/issues/46549#issuecomment-1448087832 that  `<Script>` needs to render inside `<body>` and not `<html>`

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/components/script#beforeinteractive

**Comment by leerob** [comment]
Should be fixed now!
