### ISSUE TITLE
[NEXT-731] usePathname not working with basePath setting

### ISSUE THREAD

**Issue by stephanvane** [vercel/next.js#46562]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64
    Binaries:
      Node: 18.12.0
      npm: 9.2.0
      Yarn: 1.22.17
      pnpm: 7.28.0
    Relevant packages:
      next: 13.2.2-canary.3
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/stephanvane/next-basepath-pathname-bug

### To Reproduce

1. Create a new project 
2. enable the `app` directory
3. enable `basePath` in `next.config.js` (e.g. `basePath: "/foo",`)
4. create a 'client' page in the app directory (that uses `'use client'`)
5. use the `usePathname()` hook
6. display the value on the page

### Describe the Bug

- When rendered on the server, the value of pathname will be `/`. this seems alright.
- In the browser, the pathname is replaced by `/foo`.

This leads to a 'React Hydration Error'

<img width="987" alt="Screenshot 2023-02-28 at 16 51 20" src="https://user-images.githubusercontent.com/411353/221906180-21ee5ff7-57e6-41c1-81ae-bcd8d063d719.png">

### Expected Behavior

I would expect to see a pathname of `/`

<sub>[NEXT-731](https://linear.app/vercel/issue/NEXT-731/usepathname-not-working-with-basepath-setting)</sub>

**Comment by luanmm** [comment]
I can confirm this behavior in my scenario. I wasn't expecting usePathname to return URL with basepath in it (this is not consistent with the old `/pages` behavior, neither do with basepath general concepts), and my authentication redirect is getting wrong.

Thanks in advance for attention!

**Comment by Inoir** [comment]
this also a pain, if you want to get active item. i.e: https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#checking-active-links is not working as in the example, since the usePathname returns the path with basepath, but the configs dont. so you need to add basepath to every compare.

**Comment by ammmze** [comment]
My workaround for now is setting a `NEXT_PUBLIC_BASE_PATH` environment variable and then using a wrapper hook like this:

```ts
import { usePathname as useNextPathname } from 'next/navigation';

/**
 * Retrieves the current url pathname, **from the base path**.
 * Note: This is used as a workaround because the current implementation of `usePathname` from NextJS is inconsistent
 * in scenarios where the application is running with a "basePath" that is not the root. In this scenario, on the
 * server side `usePathname` would return the path after the base path but on the client side, it would result in the
 * path including the base path. This in turn could cause the application to rehydrate improperly and trigger errors
 * when the page hydrates in the browser. See: https://github.com/vercel/next.js/issues/46562
 */
export function usePathname(): string | null {
    let pathname = useNextPathname();
    if (pathname && process?.env?.NEXT_PUBLIC_BASE_PATH && pathname.startsWith(process.env.NEXT_PUBLIC_BASE_PATH)) {
        pathname = pathname.substring(process.env.NEXT_PUBLIC_BASE_PATH.length);
        return pathname === '' ? '/' : pathname;
    }
    return pathname;
}
```
