### ISSUE TITLE
[NEXT-732] The "error.tsx" code that I copy/pasted from the docs causes a linting error.

### ISSUE THREAD

**Issue by jazzypants1989** [vercel/next.js#46573]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

npx next info

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.3
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/jazzypants1989/nextjs-test

### To Reproduce

Copy and paste the error.tsx provided by the docs into the app directory.

### Describe the Bug

![image](https://user-images.githubusercontent.com/102560332/221947484-46f7acaf-3880-47f3-9575-0d4bb9b9b909.png)

Why?

### Expected Behavior

I expect to be able to copy and paste examples from the docs without causing a linting error.

### Which browser are you using? (if relevant)

Doesn't matter

### How are you deploying your application? (if relevant)

Doesn't matter.

<sub>[NEXT-732](https://linear.app/vercel/issue/NEXT-732/the-errortsx-code-that-i-copypasted-from-the-docs-causes-a-linting)</sub>

**Comment by timneutkens** [comment]
This is a bug, thanks for the report!
