### ISSUE TITLE
[NEXT-735] Using headers.append twice with the Set-Cookie header only adds a single header

### ISSUE THREAD

**Issue by controversial** [vercel/next.js#46579]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Fri Feb 10 08:08:36 PST 2023; root:xnu-8796.100.721.505.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 3.3.1
      pnpm: N/A
    Relevant packages:
      next: 13.2.2-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/mystifying-babbage-ruhtyx?file=%2Fpages%2Fapi%2Ftest.ts

### To Reproduce

Visit `/api/test` with devtools open to observe the cookies sent with the request.

### Describe the Bug

Only a single Set-Cookie header is sent and only a single cookie is set:
<img width="208" alt="Screenshot 2023-02-28 at 3 50 42 PM" src="https://user-images.githubusercontent.com/10377391/221976757-66e520c2-cf98-4a4b-86ba-bcba4ec8a137.png">

### Expected Behavior

Two Set-Cookie headers should be added, as the [fetch standard](https://fetch.spec.whatwg.org/#concept-header-list-sort-and-combine) specifies.

This issue is very similar to #38302; @balazsorban44 [asked](https://github.com/vercel/next.js/issues/38302#issuecomment-1445312910) that I open this issue to track this separate reproduction!

<sub>[NEXT-735](https://linear.app/vercel/issue/NEXT-735/using-headersappend-twice-with-the-set-cookie-header-only-adds-a)</sub>

**Comment by xriter** [comment]
Even when doing it manually, it only sets one header:
```
return new Response(null, {
	headers: [
		[
			"Set-Cookie",
			cookie.serialize("cookie1", "myval1", {
				maxAge: 3600,
				path: "/",
			}),
		],
		[
			"Set-Cookie",
			cookie.serialize("cookie2", "myval2", {
				maxAge: 3600,
				path: "/",
			}),
		],
	],
});
```

gives
```
< HTTP/1.1 200 OK
< vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch
< set-cookie: cookie1=myval1; Max-Age=3600; Path=/, cookie2=myval2; Max-Age=3600; Path=/
< Date: Wed, 01 Mar 2023 16:32:00 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
```

They are being serialised with a comma, instead of adding two separate headers.

It might be a bug in the Fetch api (see https://www.ryadel.com/en/fetch-api-bug-get-set-multiple-set-cookie-headers/)
I have not been able to find a fix yet...

**Comment by qq99** [comment]
Just ran into this too, following

**Comment by raphaelbadia** [comment]
Related to https://github.com/vercel/edge-runtime/issues/283

**Comment by dillonraphael** [comment]
Apparently there's been a fix for this that's merged into canary, but still getting the same issue. Even on localhost.

**Comment by xriter** [comment]
@dillonraphael Could you share the link of the pull request that's supposed to fix this you are referring to?

**Comment by artemavrin** [comment]
In middleware setting 2 cookies works as it should, but in app/route, it sets only the first value

**Comment by abuinitski** [comment]
IMO Fetch API not to be blamed here, this must be very specific to Next API Routes implementation (or whatever underlying http rendering mechanism that it's using). 

It all seems like API Routes do not handle an easy-to-miss edge case that is specific to `Set-Cookie`. This is a special header, the only one that has this funny behavior when multiple values are to be rendered into repeating header (vs. one header instance with values joined by comma).

Writing all this to ping that issue still exists in today's canary, and it hurts.
