### ISSUE TITLE
Custom dev server get Error: TypeError: Cannot read properties of undefined (reading 'ProvidePlugin') 

### ISSUE THREAD

**Issue by frankda** [vercel/next.js#46588]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
Platform: MacOS
Arch: M1
Binaries:
Node: 16.4.2
npm: 7.17.0
Yarn: N/A
pnpm: N/A
Relevant packages:
next: 13.2.1
eslint-config-next: N/A
react: 18.2.0
react-dom: 18.2.0

### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-n5mjba?file=package.json,server.js

### To Reproduce

1. Create a create-next-app
2. create a new `server.js` in root directory
3. Install package `webpack` and `express`
4. Use the code in stackbliz link in `server.js`, can pass any config into `next()`
5. `node server.js` start the server

### Describe the Bug

If I pass any next.config into `next({conf=${ANY_NEXT_CONFIG}})`, will get error:

```bash
TypeError: Cannot read properties of undefined (reading 'ProvidePlugin')
    at Object.getBaseWebpackConfig [as default] (file:///home/projects/nextjs-n5mjba/node_modules/next/dist/build/webpack-config.js:1087:64)
    at async Promise.all (index 0)
    at async Span.traceAsyncFn (file:///home/projects/nextjs-n5mjba/node_modules/next/dist/trace/trace.js:79:20)
    at async Span.traceAsyncFn (file:///home/projects/nextjs-n5mjba/node_modules/next/dist/trace/trace.js:79:20)
    at async HotReloader.start (file:///home/projects/nextjs-n5mjba/node_modules/next/dist/server/dev/hot-reloader.js:387:30)
    at async DevServer.prepare (file:///home/projects/nextjs-n5mjba/node_modules/next/dist/server/dev/next-dev-server.js:596:9)
```

### Expected Behavior

Dev server to spin up in localhost:3000.

**Comment by tridattran** [comment]
This looks related to https://github.com/vercel/next.js/issues/45413. It looks like next version `13.0.1` may not have this issue.

**Comment by frankda** [comment]
Any updates for this one?

**Comment by karlhorky** [comment]
> It looks like next version `13.0.1` may not have this issue.

`next@13.0.1` indeed works with the `server.js` from @frankda's original StackBlitz.

Actually all versions I tested up until `next@13.1.1` seem to be fine:

StackBlitz (working) `next@13.1.1`: https://stackblitz.com/edit/nextjs-lcybqb?file=package.json

<img width="1080" alt="Screenshot 2023-03-21 at 17 47 30" src="https://user-images.githubusercontent.com/1935696/226682162-6443246b-9adb-4c87-aa67-af52e925df6d.png">

---

And then versions starting with `next@13.1.2` are broken:

StackBlitz (broken) `next@13.1.2`: https://stackblitz.com/edit/nextjs-mimpqu?file=package.json

<img width="999" alt="Screenshot 2023-03-21 at 17 54 07" src="https://user-images.githubusercontent.com/1935696/226684096-ac0101aa-4e52-4d95-ba6f-8908ab292fc5.png">

[This comment](https://github.com/vercel/next.js/issues/45413#issuecomment-1475234869) in #45413 by @farhan2077 leads me to think that  aa0664cc2c0415fbe851a0e2aa9dd932bc9327e9 may be the cause.

@ijjk it seems that aa0664cc2c0415fbe851a0e2aa9dd932bc9327e9 (your PR #43198 with the experimental precompiled `next-server`) could be causing problems here with `ProvidePlugin` not being defined - what do you think?

**Comment by karlhorky** [comment]
My StackBlitzes above and [this comment](https://github.com/vercel/next.js/issues/45413#issuecomment-1475234869) in #45413 by @farhan2077 leads me to think that [aa0664c](https://github.com/vercel/next.js/commit/aa0664cc2c0415fbe851a0e2aa9dd932bc9327e9) may be the cause.

@ijjk it seems that [aa0664c](https://github.com/vercel/next.js/commit/aa0664cc2c0415fbe851a0e2aa9dd932bc9327e9) (your PR #43198 with the experimental precompiled `next-server`) could be causing problems here with `ProvidePlugin` not being defined - what do you think?

**Comment by rdimascio** [comment]
Any news on this? I'm seeing the exact same issue on `13.2.4`

```
next({
    dev: IS_DEV,
    hostname: HOSTNAME,
    port: SERVER_PORT,
    conf: {
      env: {
        API_URL: 'http://localhost:3000/api',
      }
    }
});
```
Throws a webpack error —

```
Cannot read properties of undefined (reading 'DefinePlugin') TypeError: Cannot read properties of undefined (reading 'DefinePlugin')
```

**Comment by karlhorky** [comment]
The way we have worked around it for now is to set `dir` to our Next.js directory (you could also use `__dirname` instead if you're not on ESM yet):

```js
// util/next.ts
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import next from 'next';

const app = next({
  dev: !('NODE_ENV' in process.env) || process.env.NODE_ENV === 'development',
  hostname: 'localhost',
  port: 3000,
  // Path to next.config.js
  dir: resolve(
    dirname(fileURLToPath(import.meta.url)),
    '..',
  ),
});
```

**Comment by rdimascio** [comment]
Thanks @karlhorky, I left that out because I didn't think it was relevant to the issue. We are setting `dir`, and have the app running. But the issue seems to arise when we use `conf`. We have a config object that we need to pass into Next at runtime.

**Comment by karlhorky** [comment]
What I meant is that you can use `next.config.js` instead of setting the `conf` key. If you need logic, maybe you can write it in `next.config.js`

**Comment by rdimascio** [comment]
The issue is we need to pass dynamic runtime secrets from the Express server, and we cannot import them into `next.config.js` because the server application is written in TypeScript.
