### ISSUE TITLE
Can not open app after upgrading to 13.2.2

### ISSUE THREAD

**Issue by yannxaver** [vercel/next.js#46595]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.12.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: 7.26.2
    Relevant packages:
      next: 13.2.2
      eslint-config-next: 13.2.2
      react: 18.2.0
      react-dom: 18.2.0

### Link to the code that reproduces this issue

/

### To Reproduce

I cannot reproduce it for now. 

### Describe the Bug

- dev server starts normally
- try to open the app
- browser gets stuck in an endless loop  
- no errors on the server
- no errors in the browser
- downgrading to 13.2.1 reverses the problem

I am using:
- app dir
- typed routes
- root level dynamic route for i18n

### Expected Behavior

- the app should open

### Which browser are you using? (if relevant)

Problem exists in all browsers

**Comment by Talent30** [comment]
I can reproduce it

**Comment by DuCanhGH** [comment]
If you have `experimental.typedRoutes` enabled, please temporarily add `async redirects() { return [] }` and `async rewrites() { return [] }` to your Next config if you don't have them defined. Should be fixed soon enough, though.

**Comment by Talent30** [comment]
> If you have `experimental.typedRoutes` enabled, please temporarily add `async redirects() { return []; }` and `async rewrites() { return []; }` to your Next config if you don't have them defined. Should be fixed soon enough, though.

Thank you!

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.3.3-canary.0` of Next.js, please update and give it a try! Thanks @DuCanhGH for the quick fix!

**Comment by DuCanhGH** [comment]
@mwskwong I'm already on it, thanks for reporting :)

**Comment by mdrayer** [comment]
@DuCanhGH is there another issue or PR for that `DynamicRoutes` type error? I see it is fixed in the latest `canary`, but I see another issue related to it. If not, I can take out another issue.

**Comment by DuCanhGH** [comment]
@mdrayer what type error? I'm not seeing anything weird, ngl.

**Comment by mdrayer** [comment]
@DuCanhGH FWIW, I created a separate issue: https://github.com/vercel/next.js/issues/46974

**Comment by DuCanhGH** [comment]
@mdrayer yes, I've noticed that issue. It should be an easy fix :)
