### ISSUE TITLE
Docs: add information that you can add unsupported meta tags as well

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#46607]
### What is the improvement or update you wish to see?

In the docs there is no information that you can add unsupported / other meta tags as well.

### Is there any context that might help us understand?

It's possible to add not direct supported / other meta tags as well:

https://github.com/vercel/next.js/blob/5792533781e6d6fdf10d5b400d8e97d25bd5edc3/packages/next/src/lib/metadata/types/metadata-interface.ts#L503

https://github.com/vercel/next.js/discussions/46603

```tsx
export const metadata = {
  title: "Home",
  description: "Welcome to Next.js",
  other: {
    ["twitter:label1"]: "written by",
    ["twitter:data1"]: "foobar",
  },
};
```

![image](https://user-images.githubusercontent.com/987947/222100998-c6890851-82b7-4611-841c-9a4005266135.png)

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/guides/seo

**Comment by leerob** [comment]
This has been added!
