### ISSUE TITLE
Minified React error #321 for clean initialised nextjs project

### ISSUE THREAD

**Issue by fl-y** [vercel/next.js#46601]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

next info
```
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 14.19.0
      npm: 8.5.0
      Yarn: 1.22.19
      pnpm: 7.27.0
    Relevant packages:
      next: 13.2.3-canary.0
      eslint-config-next: 13.2.2
      react: 18.2.0
      react-dom: 18.2.0
```
The below error occurs to a clean nextjs app

<img width="590" alt="Screenshot 2023-03-01 at 4 39 49 PM" src="https://user-images.githubusercontent.com/31615341/222074777-ccaf1ddf-2df1-4e8b-9933-9700dad39b7c.png">

confirmed the same with yarn

### Link to the code that reproduces this issue

Not really necessary

### To Reproduce

- pnpm create next-app --typescript
- enter 5 times
- cd my-app
- pnpm i next@canary
- pnpm dev

### Describe the Bug

The screenshot says all

### Expected Behavior

No errors

**Comment by mettini** [comment]
Checkout your extensions. In my case Loom was causing the error.

To identify it, hover on `blur.js` to see the extension id and search for it at chrome://extensions.

**Comment by mitchell-robinson** [comment]
@mettini great catch, we just had the same error caused by the Loom extension.

**Comment by XenonSingh** [comment]
@mettini this worked thanks buddy . f**** loom

**Comment by fl-y** [comment]
yes it was loom - thanks @mettini 🙏

**Comment by terance-edmonds** [comment]
In my case, i had to change _swcMinify: true_ to _swcMinify: false_ in **next.config.js**
