### ISSUE TITLE
Fetch status code is always 200 except if performing a full page refresh without cache

### ISSUE THREAD

**Issue by TCM-dev** [vercel/next.js#46621]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
Platform: darwin
Arch: arm64
Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112
Binaries:
Node: 18.12.1
npm: 8.19.2
Yarn: N/A
pnpm: N/A
Relevant packages:
next: 13.2.2-canary.1
eslint-config-next: 13.2.1
react: 18.2.0
react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/TCM-dev/nextjs-error-handling-bug

### To Reproduce

- Starts the project with npm run dev
- Go to the page `http://localhost:3000/`
- Server console logs `true`and `200`
- Refresh the page without cache
- Server console logs `false`and `404`

### Describe the Bug

Using fetch to retrieve data inside a page on server side, the response status code is incorrect when simply loading/reloading the page. It looks like nextjs is caching the response without taking into account the status code.

### Expected Behavior

The status code should be corresponding to the status code of the response and not return a 200 by default.

**Comment by gernathlub** [comment]
I am experiencing the same bug. The first request performs as expected, but when the response is loaded from cache, the response status code is always 200.

**Comment by andrewbateman** [comment]
I can confirm that this is an issue for me also. My application (and probably everyone else's) relies on the status codes being returned as per the original request.

**Comment by zek** [comment]
The problem is here. When we set the cache we don't store the status.

https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/patch-fetch.ts#L189-L206
