### ISSUE TITLE
Error running a new project

### ISSUE THREAD

**Issue by fariss** [vercel/next.js#46632]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

npx create-next-app@latest

### To Reproduce

npx create-next-app@latest nextjs-blog
cd nextjs-blog
npm run dev

### Describe the Bug

When i run the new created project the first time, i got this error:

**unhandledRejection: TypeError: trace.getSpan is not a function**

i tried creating the project using npx create-next-app@latest & npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"

i got the same error

### Expected Behavior

I just expected to see the default home page of a new created Nextjs project

**Comment by balazsorban44** [comment]
Could you please link to a repository? I cannot reproduce based on the description.

**Comment by fariss** [comment]
He

> Could you please link to a repository? I cannot reproduce based on the description.

Hi,

I just created a repo: https://github.com/fariss/nextjs-new-project

Screenshot: https://ibb.co/PrYqTK1

**Comment by ciruz** [comment]
@fariss works for me, also your repo works for me:

![image](https://user-images.githubusercontent.com/987947/222359138-c0f9eba3-ed9f-496f-a6f5-920c22ac1f1b.png)

![image](https://user-images.githubusercontent.com/987947/222359244-acdf76bc-bf48-40ea-a5ea-f8c781f3bb4c.png)

**Comment by fariss** [comment]
Very strange, I solved it by installing @opentelemetry, as suggested here: https://stackoverflow.com/questions/75571462/nextjs-13-2-1-unhandledrejection-error-in-next-js-project-typeerror-trace-g
`npm install @opentelemetry/api @opentelemetry/resources @opentelemetry/semantic-conventions @opentelemetry/sdk-trace-node @opentelemetry/instrumentation`
