### ISSUE TITLE
NextJS 13.2 overwrites favicon with it's own 

### ISSUE THREAD

**Issue by DominicTobias** [vercel/next.js#46682]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.2
      npm: 9.6.0
      Yarn: 1.22.19
      pnpm: 7.28.0
    Relevant packages:
      next: 13.2.3
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### To Reproduce

```ts
// src/app/layout.tsx
export const metadata = {
  icons: {
    icon: { url: '/favicon.svg', type: 'image/svg' },
    shortcut: { url: '/favicon.svg', type: 'image/svg' },
  },
}
```

### Describe the Bug

What I want to achieve is:
```html
<link rel="shortcut icon" type="image/svg" href="/favicon.svg" />
```

However NextJS overwrites this with it's own icon. It also produces an extra "icon" meta which I didn't need I think.

<img width="512" alt="Screenshot 2023-03-02 at 13 01 59" src="https://user-images.githubusercontent.com/760314/222436267-ff431ea3-e9f6-4b44-b18c-f1afe2978aa8.png">

### Expected Behavior

NextJS should not overwrite with it's own favicon.

**Comment by piccinnigius** [comment]
for me metadata works, but not icons are shipped to output page (title working, but no link icon)

**Comment by DominicTobias** [comment]
All I had to do was remove `favicon.ico` from `src/app`, it seems to automatically pick it up and write a meta tag for it

**Comment by chuckcg** [comment]
I have the same issue. I have no favicon.ico so can't use the same fix than @DominicTobias :/

**Comment by KokosTech** [comment]
> I have the same issue. I have no favicon.ico so can't use the same fix than @DominicTobias :/

Do you use Next 13.2 with `/app` directory. If yes, and you don't have a `favicon.ico` in the `/app`, I'd suggest putting your own there. It should probably fix it.

**Comment by ugochukwudev** [comment]
didnt work

**Comment by raselldev** [comment]
i have some issue, but in here i using nextjs 13.3

my metadata in layout.tsx
`export const metadata: Metadata = {
  title: {
    default: "Raka Rasell",
    template: "%s | Raka Rasell",
  },
  description: "Software Developer",
  openGraph: {
    title: "Raka Rasell",
    description: "Software Developer",
    url: "https://rakarasell.dev",
    siteName: "Raka Rasell",
    images: [
      {
        url: "https://rakarasell.dev/og.jpeg",
      },
    ],
    locale: "en-US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: { url: "/favicon.svg", type: "image/svg" },
    shortcut: { url: "/favicon.svg", type: "image/svg" },
  },`

**Comment by amine-baya** [comment]
in nextjs 13.3, the favicon.ico should be under the app directory. so you just need to change it with your new image

**Comment by aleksgribko** [comment]
> All I had to do was remove `favicon.ico` from `src/app`, it seems to automatically pick it up and write a meta tag for it

Oh my, it was so easy. It must be mentioned in the docs somewhere. And why would next js place default favicon in  `src/app` and not in `public`, not clear for me..

**Comment by DominicTobias** [comment]
> in nextjs 13.3, the favicon.ico should be under the app directory. so you just need to change it with your new image

.ico is quite an unpleasant and poorly supported format in image editors, a lot of people prefer a PNG, or better yet nowadays SVG has wide support and you can do cool stuff like change the colors depending if the user is on dark or light theme

**Comment by blinovvvvvv** [comment]
I just put `favicon.ico`to a `public` directory and it is gonna work! I tried to switch `favicon.ico` at `app` directory and configure `metadata` object at `app/layout.tsx` but it had no effect
