### ISSUE TITLE
Cannot find module sass fibers

### ISSUE THREAD

**Issue by colbyfayock** [vercel/next.js#46690]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 14.19.0
      npm: 6.14.16
      Yarn: 1.22.18
      pnpm: 7.26.0
    Relevant packages:
      next: 13.2.4-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Package manager (npm, pnpm, Yarn)

### Link to the code that reproduces this issue

https://github.com/colbyfayock/next-sass-fiber-repro

### To Reproduce

Try to load any page and it spins.

I've been watching this https://github.com/vercel/next.js/issues/37825#issuecomment-1451512044 and the latest comment helped debug the issue with 

```
process.on('unhandledRejection', error => {
  console.log('unhandledRejection', error);
});
```

Inside my next config

### Describe the Bug

Seems a modules not able to be resolved in the Sass pipeline

Not sure if it's related to something i'm doing or a regression, but everything was previously working before I tried to upgrade to latest

```
    "next": "13.0.6",
    "sass": "^1.56.2",
```

https://github.com/colbyfayock/spacejelly.dev/

### Expected Behavior

Page loads with sass capabilities

**Comment by shuding** [comment]
Duplicate with #45052, which should be fixed in latest versions.
