### ISSUE TITLE
outputFileTracingIncludes using wrong root path in Next13.2.3

### ISSUE THREAD

**Issue by Mitsunee** [vercel/next.js#46697]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed Feb 22 18:13:06 UTC 2023
    Binaries:
      Node: 16.19.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 7.27.1
    Relevant packages:
      next: 13.2.3 (also tested on 13.2.4-canary.0)
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/Mitsunee/fgo-timers/tree/debug-nft-issues

### To Reproduce

add files in next.config.mjs under `experimental.outputFileTracingIncludes`, for example:

```js
    outputFileTracingIncludes: {
      "/": [
        "./assets/static/backgrounds.json",
        "./assets/static/events.json",
        "./assets/static/loginTickets.json",
        "./assets/static/prismShops.json",
        "./.next/cache/atlasacademy/info.json",
        "./.next/cache/atlasacademy/NA/nice_master_mission.json"
      ]
    }
  },
```

### Describe the Bug

I was previously using the config.unstable_includeFiles export to explicitly set some files (which are generated by a prebuild script) as required for the ISR serverless function. This option has been removed in Next.js 13.2.x in favour of this new config file option.

The [docs](https://nextjs.org/docs/advanced-features/output-file-tracing#caveats) state that the paths should be "relative to the project's root" and show some example of relative paths. I adjusted my paths to match this after noticing that the old paths failed to work.

Furthermore my builds on vercel now fail with the following error:  
```
"Error: ENOENT: no such file or directory, lstat '/vercel/path0/.next/assets/static/data/servants.json'"
```

Note how the path contains ".next", but continues with a "assets" segment. The relative path from my config is "./assets/static/data/servants.json". This part is the bug I would like to report. It seems to me that the default outputFileTracingRoot is "projectRoot/.next" instead of actually being the projectRoot (read: cwd when running `yarn next build`). The documentation also states to use `__dirname` to set a different root in monorepos, despite this global no longer being available in ESM contexts.

### Expected Behavior

The files should be included in the .nft.json file and be present for serverless function execution so that ISR can access them again. This behaviour should match the removed behaviour of exporting an object called "config" with a key "unstable_includeFiles".

I'd also like to mention that I have an API route with tRPC which does successfully include my assets/static directory in its .nft.json file.

### Attempted Solutions

I also attempted to reproduce the issue locally and the "index.js.nft.json" does indeed fail to include *any* of the files I have set in my [config](https://github.com/Mitsunee/fgo-timers/blob/d35b7c5be502acadd58ef057c51e638c7a6caf53/next.config.mjs). The build does not fail locally.

#### process.cwd

While `__dirname` may no longer be available I did try `outputFileTracingRoot: process.cwd()` in my config, reran the build locally but sadly got the same result.

#### Adjusting the path to assumed incorrect behaviour

Since the root seems to be ".next" the logical conclusion is that my paths should become "../assets/*". I again attempted this locally but still got the same result, my files were not included in the .nft.json

### Further Notes

I will be reverting my main branch back to Next13.1 for now. Should any suggestions arise I can try them in a separate branch which I will link here.

Update: I have created the branch: https://github.com/Mitsunee/fgo-timers/tree/debug-nft-issues (deployment: https://vercel.com/mitsunee/fgo-timers/7dJRYzLFKkesgU6fwQT8hXuiKQ5P)

### How are you deploying your application? (if relevant)

vercel

**Comment by ijjk** [comment]
Hi, the linked repo doesn't appear to be leveraging the mentioned config https://github.com/Mitsunee/fgo-timers/blob/586f9b4abaf0bd823b2bd98e415a33d8644aae1a/next.config.mjs#L8

The `outputFileTracingIncludes` config is relative to the project dir related code can be seen here https://github.com/vercel/next.js/blob/111ef3951cf13e9eb758ace222265fdd3f883d6e/packages/next/src/build/index.ts#L1799

and we have tests for this config which are working as expected here https://github.com/vercel/next.js/blob/111ef3951cf13e9eb758ace222265fdd3f883d6e/test/integration/build-trace-extra-entries/app/next.config.js#L23

**Comment by Mitsunee** [comment]
> Hi, the linked repo doesn't appear to be leveraging the mentioned config https://github.com/Mitsunee/fgo-timers/blob/586f9b4abaf0bd823b2bd98e415a33d8644aae1a/next.config.mjs#L8

See the Further notes section in my initial post. I have reverted the changes so I could ship a new feature that had not been in a build yet.

> The `outputFileTracingIncludes` config is relative to the project dir related code can be seen here

See my bug description. The path incorrectly includes ".next", which is neither the project dir, nor included in my path.

**Comment by Mitsunee** [comment]
closing as I'm no longer developing the website that had the problem and found other ways to cheese nft's tracing into finding my filepaths. 

Also this issue has been stale since March in a classic example of why I don't like even reporting niche bugs like this anymore. Nobody cares - unstable features just get removed without warning or working alternatives and Next.js is basically one giant unstable framework.

**Comment by fabiopk** [comment]
But is there an alternative to this? I am still facing the same issue.

**Comment by Mitsunee** [comment]
please stop posting here, this issue is closed
