### ISSUE TITLE
Docs: improve the clarity of stable features

### ISSUE THREAD

**Issue by devmanbr** [vercel/next.js#46714]
### What is the improvement or update you wish to see?

across the next.js site, it is not possible to clearly determine which of the new features in version 13 are already considered stable (although some things suggest this, such as a blog post).

in use, however, the use of the "experimental" setting makes us understand the opposite.

so be clearer in the documentation.

### Is there any context that might help us understand?

we look forward to the stability of the new features, it's nice to be able to keep track of what's actually going on more reliably

**Comment by leerob** [comment]
Fixed now that it's stable 😄
