### ISSUE TITLE
[NEXT-888] MetaData title and description will add to body instead head tag

### ISSUE THREAD

**Issue by roshaninet** [vercel/next.js#46738]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.0.0
    Relevant packages:
      next: 13.2.4-canary.1
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-erobcb?file=app%2Fpage.tsx,next.config.js,app%2Flayout.tsx

### To Reproduce

default meta data in layout.jsx 

```
export const metadata = {
    title: {
        default: 'خرید و اجاره ویلا در شمال',
        template: '%s | املاک دلاوران',
    },
}
```

page.js metadata:

```
export const metadata = {
    description: "گروه مشاورین املاک دلاوران، خریدو فروش ویلا در شمال مازندران",
    alternates: {
        canonical: canonicalLink("")
    }
};
```

### Describe the Bug

meta data export will append tag to body tag instead head tag

![Screenshot 2023-03-03 at 6 54 28 PM](https://user-images.githubusercontent.com/8685071/222759145-febbc19a-4989-4fd9-9e88-a7711fcdbfdb.png)

### Expected Behavior

the meta data must be add to head tag.

<sub>[NEXT-888](https://linear.app/vercel/issue/NEXT-888/metadata-title-and-description-will-add-to-body-instead-head-tag)</sub>

**Comment by axten** [comment]
same here, meta tags end up in body

**Comment by Adrianjs42** [comment]
I could reproduce the issue after using React.Suspense in the layout.tsx.
@roshaninet do you use React.Suspense in the layout.tsx file, too?

**Link to the code that reproduces this issue**
https://stackblitz.com/edit/vercel-next-js-erobcb?file=app%2Fpage.tsx,next.config.js,app%2Flayout.tsx

**To Reproduce**

```
import type { Metadata } from 'next/types';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: {
    default: 'Next.js App Router',
    template: '%s | Next.js App Router',
  },
  description:
    'A playground to explore new Next.js App Router features such as nested layouts, instant loading states, streaming, and component level data fetching.',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head />
      <body>
        <Suspense fallback={<>loading</>}>{children}</Suspense>
      </body>
    </html>
  );
}
```

**Expected Behavior**
The metadata should be placed inside of the head tag.

By the way, when you build the app, the metadata is placed correctly in the head tag.

**Comment by priyanshuraj24** [comment]
+1

**Comment by hicodersofficial** [comment]
+1

**Comment by roshaninet** [comment]
@Adrianjs42 No i dont,
i think this problem exists in dynamic metadata (generateMetadata)

**Comment by icyJoseph** [comment]
Hi,

This happens when you have a loading file, and in general, it seems like the presence of suspense boundaries (`<!-- $ -->`, `<!-- /$ -->`) triggers the issue.


https://user-images.githubusercontent.com/21013447/227182580-d28a43eb-eed5-4c58-9774-34ef227f704a.mov

**Comment by roshaninet** [comment]
@icyJoseph yes man, the problem is in loading file. i confirm that problem is in loading file.
