### ISSUE TITLE
[NEXT-764] GET Route Handlers not valid destinations with experimental.typedRoutes

### ISSUE THREAD

**Issue by karlhorky** [vercel/next.js#46742]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.2.4-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link), TypeScript

### Link to the code that reproduces this issue

[https://codesandbox.io/p/sandbox/trusting-rosalind-1mwkuc](https://codesandbox.io/p/sandbox/trusting-rosalind-1mwkuc)

### To Reproduce

1. Clone CodeSandbox and enable local TypeScript version + Next.js TypeScript plugin
2. Observe the TypeScript error in `app/page.tsx` about the `href` location pointing at a `GET` Route Handler

```
Type '"/set-cookie"' is not assignable to type 'UrlObject | RouteImpl<"/set-cookie">'.ts(2322)

link.d.ts(76, 5): The expected type comes from property 'href' which is declared here on type 'IntrinsicAttributes & LinkRestProps & HrefProp<"/set-cookie">'
```

![](https://uploads.linear.app/099ed59a-06c6-472f-9977-4798721bda90/e9307400-586b-42d5-ba66-fc482c864195/21b70c2d-f2e4-4389-9cb4-478fae0e5b88)

Associated Route Handler:

`app/set-cookie/route.ts`

```ts
import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  const maxAge = 60 * 60 * 24; // 24 hours in seconds
  return new NextResponse(null, {
    // Temporary redirect
    status: 307,
    headers: {
      location: "/",
      "Set-Cookie": `cookie_name=a3fWa; Max-Age=${maxAge}; Expires: ${
        Date.now() + maxAge * 1000
      }; Path=/`,
    },
  });
}
```

### Describe the Bug

The `experimental.typedRoutes` configuration doesn't handle an `href` prop on `next/link` pointing at a location of a `GET` Route Handler

cc @DuCanhGH @shuding

### Expected Behavior

An `href` location pointing at a `GET` Route Handler works

### Which browser are you using? (if relevant)

*No response*

### How are you deploying your application? (if relevant)

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-764](https://linear.app/vercel/issue/NEXT-764/get-route-handlers-not-valid-destinations-with-experimentaltypedroutes)</sub>

**Comment by DuCanhGH** [comment]
![image](https://user-images.githubusercontent.com/75556609/222775495-4ff16e92-e491-4543-bfcf-81c7d93ba272.png)
We currently filter out non-page files from type `Route`. I will include this with my current PR.

**Comment by karlhorky** [comment]
> I think I will also add support for `route.ts` in my current PR.

This PR, I imagine?

- https://github.com/vercel/next.js/pull/46679

Maybe a line should be added to the top of the PR description with `Fixes #46742` ?

**Comment by DuCanhGH** [comment]
@karlhorky I'm asking for the members' reviews first, since I don't know whether Route Handlers are supposed to be used with `next/link` or not.

**Comment by shuding** [comment]
@DuCanhGH Let's open a separate PR for this feature request as this one requires more complicated logic to implement and needs some discussion (typed routes doesn't support API routes and public files at all as of today, not a bug).

**Comment by shuding** [comment]
I shared some of my thoughts here: https://github.com/vercel/next.js/pull/47185#issuecomment-1470965313, but this does look like a valid use case... although `as Route` is a work around here, do you feel that we should add GET routes to the types cc @sebmarkbage?

**Comment by sebmarkbage** [comment]
Yea, ideally you should be able to use a custom route with a rewrite just as if it was a Next.js built-in page. So we should include those.
