### ISSUE TITLE
Can’t access headers from `edge` route handlers

### ISSUE THREAD

**Issue by controversial** [vercel/next.js#46755]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Fri Feb 10 08:08:36 PST 2023; root:xnu-8796.100.721.505.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 3.3.1
      pnpm: N/A
    Relevant packages:
      next: 13.2.4-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/optimistic-field-h3ll94?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A14%2C%22startLineNumber%22%3A9%7D%5D

### To Reproduce

1. Load the `/test-node` route, and observe that the request’s headers are returned back as a JSON response.
2. Open `/test-edge`route`, and observe that an error is thrown.
3. Observe that the only difference between the `/test-node` and `/test-edge` route handlers is the `runtime` config option (`nodejs` vs `edge`)

### Describe the Bug

Accessing `headers()` (or `req.headers`) under the `edge` or `experimental-edge` runtime in a route handler throws an error

### Expected Behavior

the `headers()` API works under either route handler runtime

**Comment by balazsorban44** [comment]
Thanks, this has been fixed in https://github.com/vercel/next.js/pull/46741

Please upgrade to `next@canary`!
