### ISSUE TITLE
Give some more spacing 

### ISSUE THREAD

**Issue by rohan9024** [vercel/next.js#46767]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
N/A
```

### Link to the code that reproduces this issue

https://vercel.com/templates?utm_source=next-site&utm_medium=navbar&utm_campaign=nextjs-templates

### To Reproduce

click on inspect and select iPad mini

### Describe the Bug

Need more spacing between filter and search bar.
It appears to be congested.

Please assign me 
![image](https://user-images.githubusercontent.com/64919642/222914138-1a4b1e41-e29e-4956-95ec-7997f6c9af2b.png)

### Expected Behavior

Needs more spacing

**Comment by balazsorban44** [comment]
Thanks, I pinged the team about it! Since it's not a Next.js bug, I'm closing this issue.
