### ISSUE TITLE
Docs: Next documentation claims to support Safari 12+, but actually supports 12.1+ due to lack of globalThis polyfill

### ISSUE THREAD

**Issue by simonhrogers** [vercel/next.js#46792]
### What is the improvement or update you wish to see?

The Next documentation claims to support Safari 12, however it does not, as `globalThis` is not supported by Safari until 12.1. 

### Is there any context that might help us understand?

I’m running 12.0 on an old Macbook as clients frequently still have it (...) and my Next.js app shows a blank screen. 

For Next.js to truly support Safari 12+ a polyfill for globalThis would be needed. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/basic-features/supported-browsers-features

**Comment by balazsorban44** [comment]
Interesting. :thinking: Our default target lists safari 12: https://github.com/vercel/next.js/blob/canary/packages/next/src/shared/lib/constants.ts/#L61

Could you add a reproduction with some code to verify which version of Next.js you are using so we can investigate?

**Comment by simonhrogers** [comment]
Hey @balazsorban44! Thanks so much for getting back to me. 

After opening this issue I discovered that as of `13.2.4-canary.3` another member had clocked the same issue and released a fix for it within `next/polyfill` – so on the canary branch this is no longer an issue :-) Prior to that it had been an issue with all version I’d installed from Next 13.0 – 13.2

S
