### ISSUE TITLE
try-catch for `import` not working in Route Handlers

### ISSUE THREAD

**Issue by damnmicrowave** [vercel/next.js#46791]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000
Binaries:
  Node: 19.6.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.2.4-canary.3
  eslint-config-next: 13.2.3
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/damnmicrowave/nextjs-try-catch-import-error-example

### To Reproduce

1. Run the development server:
`yarn dev`

2. Try to open [/hello](http://localhost:3000/hello) route

3. Get an import error:
![image](https://user-images.githubusercontent.com/34608186/222966416-09468004-c670-41d2-b8af-a0d660a70f54.png)

### Describe the Bug

When using new Route Handlers, `Module not found` error is thrown, ignoring the try-catch block.

### Expected Behavior

Error should be caught, executing second block of code (in my example, using the WebCrypto API instead of Node.js 'crypto' package)

### Which browser are you using? (if relevant)

Firefox Developer Edition v111.0b1

**Comment by balazsorban44** [comment]
It's unclear what the goal is, when `export const runtime = 'edge'` is set, node-specific modules are not loadable, and the handler is going to use the Edge Runtime, so there is no need to target the Node.js runtime anyway.

**Comment by damnmicrowave** [comment]
@balazsorban44 I am trying to write a universal function that can be used in both runtimes. Is there a better way to check which runtime is used?
