### ISSUE TITLE
[NEXT-777] Wrong route handler for app + pages hybrid with i18n config

### ISSUE THREAD

**Issue by pveyes** [vercel/next.js#46814]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.27.0
    Relevant packages:
      next: 13.2.4-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Internationalization (i18n)

### Link to the code that reproduces this issue

https://github.com/pveyes/next.js-i18n-app-pages-hybrid

### To Reproduce

- Clone reproduction repo
- Run dev server: `next dev`
- Open http://localhost:3000/blog/random
- Page will return 404 even though it should've been handled by app/blog/[slug]/page.tsx
- Disable i18n config, restart dev server and reopen the page
- It works fine

### Describe the Bug

When i18n config (with `locales` & `defaultLocale` option) is enabled in `next.config.js`, `app` routes with dynamic segment  (e.g: `/blog/[slug]`) will always be 404. This happens because when matching the [app dir routes in default-route-matcher-manager](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/future/route-matcher-managers/default-route-matcher-manager.ts#L231), the pathname passed has a locale prefix because `defaultLocale` option (e.g: `/en/blog/random`).

The solution I've tried locally that fixes the issue is by using "naked route" for app dir route matcher. We can get this by using `options.i18n?.pathname` and fallback to `pathname` if there's no i18n config

```diff
diff --git a/packages/next/src/server/future/route-matcher-managers/default-route-matcher-manager.ts b/packages/next/src/server/future/route-matcher-managers/default-route-matcher-manager.ts
index b8d88976..5eb43333 100644
--- a/packages/next/src/server/future/route-matcher-managers/default-route-matcher-manager.ts
+++ b/packages/next/src/server/future/route-matcher-managers/default-route-matcher-manager.ts
@@ -228,7 +228,7 @@ export class DefaultRouteMatcherManager implements RouteMatcherManager {
       return matcher.match(pathname, options)
     }
 
-    return matcher.match(pathname)
+    return matcher.match(options.i18n?.pathname ?? pathname)
   }
 
   public async *matchAll(
```

This is also something that we do in https://github.com/vercel/next.js/blob/canary/packages/next/src/server/base-server.ts#L678, I think it's a valid change. I've made a PR-ready branch in https://github.com/pveyes/next.js/tree/locale-routing.

### Expected Behavior

Page in app dir render normally

### Which browser are you using? (if relevant)

any browser

### How are you deploying your application? (if relevant)

Tested locally

<sub>[NEXT-777](https://linear.app/vercel/issue/NEXT-777/wrong-route-handler-for-app-pages-hybrid-with-i18n-config)</sub>

**Comment by rexwangcc** [comment]
We are facing the exact same issue.

**Comment by rexwangcc** [comment]
> Just want to ditto that we are facing the exact same issue.

For whoever needs to work around it, we had a docker (k8s indeed) nextjs deployment with `node server.js` as the entrypoint before running into this issue (with `next-i18next`, `appDir: true` and `pages/[slug].tsx` together), and switching to `next start` helped us workaround this for now, wildly guess there's some inconsistency between the custom server generated by next build and the next runtime.
