### ISSUE TITLE
Docs: using example code from `app` router 'error handling' page seems to trigger `NEXT_TS_ERRORS.INVALID_CLIENT_ENTRY_PROP` warning

### ISSUE THREAD

**Issue by philwolstenholme** [vercel/next.js#46843]
### What is the improvement or update you wish to see?

Copying this example from https://beta.nextjs.org/docs/routing/error-handling into a file called `src/app/(main)/product/[id]/error.tsx`:

```typescript
'use client'; // Error components must be Client components

import { useEffect } from 'react';

export default function Error({
  error,
  reset,
}: {
  error: Error;
  reset: () => void;
}) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error);
  }, [error]);

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  );
}
```

Results in a `Props must be serializable for components in the "use client" entry file, "reset" is invalid.ts` TypeScript warning from the [`packages/next/src/server/typescript/rules/client-boundary.ts` rule](https://github.com/vercel/next.js/blob/a0c4354be82415cd8c3013fbabaeb050f57dba1d/packages/next/src/server/typescript/rules/client-boundary.ts#L59).

### Is there any context that might help us understand?

I copied the code as-is from the docs and got the warning

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/routing/error-handling

**Comment by MahirPatel3130** [comment]
maybe the problem is that reset function is not get serialized when it gets passed as props, so maybe you can useCallback() hook by which same function instance on subsequent renders as long as its dependencies have not changed.

**Comment by MahirPatel3130** [comment]
<img width="495" alt="Screenshot 2023-03-06 at 2 21 48 PM" src="https://user-images.githubusercontent.com/117554519/223258248-88fe3422-59e2-484d-8937-f0aeda19594b.png">

**Comment by MahirPatel3130** [comment]
You can try this out maybe this can work.

**Comment by bramarcade** [comment]
I'm having the same problem. (I tried using a callback and that didn't work either.)

Is there a way to declare a client component such that it can only accept props from other client components? That would obviate the serializability concern and probably stop the warning.

**Comment by philwolstenholme** [comment]
I wonder if this is related to this other issue that I am having? https://github.com/vercel/next.js/discussions/46637#discussioncomment-5222661

**Comment by MahirPatel3130** [comment]
> I'm having the same problem. (I tried using a callback and that didn't work either.)
> 
> Is there a way to declare a client component such that it can only accept props from other client components? That would obviate the serializability concern and probably stop the warning.

RIght now, maybe there is not any way to declare other client component since as we know that the problem is in reset function which is not get serialzied either way.

**Comment by MahirPatel3130** [comment]
So, maybe right now it's better to wait for the version 13 get production ready first because still the docs is unclear and not completely correct.

**Comment by philwolstenholme** [comment]
Ah, this issue is a duplicate of https://github.com/vercel/next.js/issues/46573, which is now fixed (I guess the fix will be in the next release)
