### ISSUE TITLE
Strict CSP does not work with styles

### ISSUE THREAD

**Issue by lasley** [vercel/next.js#46857]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-strict-csp

### What browser are you using? (if relevant)

FireFox 111.0b8 (64-bit), Chrome Version 110.0.5481.177

### How are you deploying your application? (if relevant)

```next build && next start```

or

```next build && next export```

### Describe the Bug

Strict CSP in the example only applies for `script-src` - use of styles will generate a CSP error on `style-src` when navigating to a page using `next/link`. This is not present for actual page loads, only ones through router.

### Expected Behavior

Browsing to another page using next/link does not generate a CSP error if the page has styles

On FireFox: `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).`

On Chrome: `Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

### To Reproduce

In `with-strict-csp`:

Edit file `pages/index.js`

```javascript
import Link from "next/link";

export default function Home() {
  return <Link href={'/another'}>Hello World</Link>
}
```

New file `pages/another.module.css`

```
.style {
    background-color: red;
    color: blue;
}
```

New file `pages/another.js`

```javascript
import {style} from './another.module.css'

export default function Another() {
  return <div class={style}>Another</div>
}
```

Then in console:
1. `npm install`
2. `npm build`
3. `npm start`

In browser:
1. `http://localhost:3000`
2. Click the link - observe that the text is black and there is a CSP error
4. Refresh page - observe that the text is blue with a red background & there is no CSP error

**Comment by har1sh** [comment]
I am seeing the same issue with one of the projects am working on. NextJS router is adding inline styles, probably for performance optimization during loads. Hopefully we can get this resolved, for us to start enforcing stricter style-src.

**Comment by csi-lk** [comment]
Yep looks like the app-renderer doesn't inject the nonce if available

https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/app-render.tsx#L471-L492

**Comment by leerob** [comment]
Hey folks, wanted to swing back here with an update. After digging through many different issues and discussions, I've [**made a new page in the documentation**](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy) ([PR](https://github.com/vercel/next.js/pull/54601)) specifically for Content Security Policy and nonces. This docs page: 

- Explains how to generate a `nonce` with Middleware
- Shows how to consume the `nonce` in a route with `headers()`
- Shows a complete CSP without needing to use any `unsafe`
- Shows how to ignore the `nonce` Middleware from running on prefetches / static assets

Further, we've patched some bugs and made improvements to `nonce` handling in Next.js that will be available in the latest `canary` version (for those of you time traveling from the future, upgrade to Next.js 13.5). We also updated the `with-strict-csp` example in the `examples/` folder, which is backlinked from the [new documentation page](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy).

Really hope this helps out, thank you all 🙏 I'll be closing this issue out. To continue the discussion, [please go here](https://github.com/vercel/next.js/discussions/54907).
