### ISSUE TITLE
Docs: Response With a Buffer From API

### ISSUE THREAD

**Issue by shangcode** [vercel/next.js#46879]
### What is the improvement or update you wish to see?

It may helpful to add some explain on how to response with various objects on https://nextjs.org/docs/api-routes/response-helpers.

After some search, I found `Buffer.from()` could make it on the right way:
```
const pdfBytes = await pdfDoc.save()
res.status(200).send(Buffer.from(pdfBytes.buffer))
```

### Is there any context that might help us understand?

Tody, I am trying to make an API end point that use PDF-LIB to generate pdf and response it.
At first, I have tried to response with a blob object, but it becomse null on client.

After a whole day struggling, I found it could be fixed with`Buffer.from(pdfBuffer)`.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-routes/response-helpers

**Comment by balazsorban44** [comment]
The Next.js API Response API is an extension of the Node.js API (also linked in the Next.js documentation)

See `res.end() here: `https://nodejs.org/api/http.html#outgoingmessageendchunk-encoding-callback

`res.send` is also documented to be able to return `Buffer`:

> `res.send(body)` - Sends the HTTP response. body can be a string, an object or a Buffer
