### ISSUE TITLE
Nextjs-13 Cookie

### ISSUE THREAD

**Issue by KSrahul** [vercel/next.js#46878]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Development/Production
```

### Link to the code that reproduces this issue

Development 

### To Reproduce

Cookie, in nextjs-13 server components 

### Describe the Bug

in nextjs-12 we can check and delete cookie using "getServersideProps" using "next/cookie" package. 

But in nextjs-13, there no option to delete cookie from server components. Pls add that feature also

### Expected Behavior

Delete cookie nextjs -13 server components 

### Which browser are you using? (if relevant)

Chrome

**Comment by balazsorban44** [comment]
Setting cookies is being worked on, see https://beta.nextjs.org/docs/api-reference/cookies#good-to-know

**Comment by KSrahul** [comment]
> Setting cookies is being worked on, see https://beta.nextjs.org/docs/api-reference/cookies#good-to-know

Yes, but no option to delete cookie
