### ISSUE TITLE
Setting `swcMinify: true` in production causes a client-side exception

### ISSUE THREAD

**Issue by daanboer** [vercel/next.js#46887]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1-NixOS SMP Wed Feb 22 11:57:12 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: N/A
      pnpm: 7.26.3
    Relevant packages:
      next: 13.2.4-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC minifier (swcMinify: true)

### Link to the code that reproduces this issue

https://github.com/daanboer/next-citationjs-repro

### To Reproduce

Setup and run the example code using:

```shell
pnpm install
pnpm build
pnpm start
```
Then visit `localhost:3000`. This will issue a client-side exception, and the formatted citation is not shown.

### Describe the Bug

Using the [`@citation-js/core`](https://github.com/citation-js/citation-js/tree/main/packages/core), and [`@citation-js/plugin-csl`](https://github.com/citation-js/citation-js/tree/main/packages/plugin-csl) packages to format a CSL-json document results in a client-side exception when combined with `swcMinify: true`. Disabling `swcMinify` results in the desired behavior and the formatted citation is shown without any errors. This bug only occurs in production, enabling `swcMinify` in the dev environment works just fine.

### Expected Behavior

The generated page should not issue any errors and show a formatted citation.

**Comment by eugeniudedin** [comment]
I have same issue only on production with `swcMinify: true`.
Error: `Application error: a client-side exception has occurred (see the browser console for more information).`

**Comment by LunaTK** [comment]
Having a same issue.

**Comment by noah-rss** [comment]
We are currently experiencing this as well.

**Comment by avitorio** [comment]
Hey @daanboer and @LunaTK , I'm currently experiencing this. Did you all find a solution? My package breaks on next.js if swcMinify isn't set to false...

**Comment by daanboer** [comment]
> Hey @daanboer and @LunaTK , I'm currently experiencing this. Did you all find a solution? My package breaks on next.js if swcMinify isn't set to false...

Nope, sadly I haven't found a solution, and the issue still persists.

**Comment by LunaTK** [comment]
Me neither. Still using next.js with `swcMinify` disabled :(

**Comment by kcrwfrd** [comment]
We started experiencing a TypeError from another package after upgrading to `14.2.3` ... if we set `swcMinify: false` or downgrade to `14.1.4`, it works fine.

**Comment by daanboer** [comment]
Yes, this problem seems to have returned in `14.2.~`. I have updated the reproduction example to the `14.3.0` canary. The error has now moved to the build step (on `14.2.~` it still throws a runtime exception). This issue starts to become more pressing, as `swcMinify` is being deprecated in the near future.

**Comment by huozhi** [comment]
@kcrwfrd @daanboer could you share a reproduction repo about your issue?

**Comment by daanboer** [comment]
@huozhi sure, a reproduction example can be found here: https://github.com/daanboer/next-citationjs-repro.

**Comment by huozhi** [comment]
Sorry for duplicated tagging, forgot to mention we're already investigating that one. Asking @\kcrwfrd 's case to see if it's a different case 🙏 thanks!

**Comment by kcrwfrd** [comment]
> Sorry for duplicated tagging, forgot to mention we're already investigating that one. Asking @\kcrwfrd 's case to see if it's a different case 🙏 thanks!

My encounter with the bug involved another package so I don't have it isolated very well, but I can put something together @huozhi

**Comment by kcrwfrd** [comment]
@huozhi okay I just successfully put together a reproduction: https://github.com/kcrwfrd/next-swc-minify-bug-reproduction

Thanks for looking into it 🙏🏼

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/pull/8956 will fix this issue, and the issue reported by @kcrwfrd will be fixed by https://github.com/swc-project/swc/pull/8957.
I'll close this with `swc_core` update PRs.

Thank you for reporting and creating a repro! Fixing a minifier bug is nearly impossible without a good repro.

**Comment by daanboer** [comment]
@kdy1 Thank you for treating this issue. I have updated the reproduction example to use the latest canary release (`14.3.0-canary.70`), but the problem still persists. Is this to be expected?
