### ISSUE TITLE
[NEXT-1139] [BUG] Very long dev builds 50 times slower

### ISSUE THREAD

**Issue by OlegLustenko** [vercel/next.js#46884]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 9.4.1
      Yarn: 1.22.19
      pnpm: 7.25.0
    Relevant packages:
      next: 13.2.4-canary.5
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

can I add this later?

### To Reproduce

Our application heavily using **rewrites**, it might be the case 

- Update to latest next.js
- `npm run dev`, track compilation time

### Describe the Bug

Compilation takes too much time

13.1.6
![image](https://user-images.githubusercontent.com/11524061/223474279-b692f1c0-f610-4806-9364-26a93ca5c0f0.png)

13.2.2+, also tested on canary builds
![image](https://user-images.githubusercontent.com/11524061/223474430-a83288df-d4d2-42fd-97e0-5347b5b5aeea.png)

### Expected Behavior

It takes less or the same amount of time

<sub>[NEXT-1139](https://linear.app/vercel/issue/NEXT-1139/[bug]-very-long-dev-builds-50-times-slower)</sub>

**Comment by red1** [comment]
I had a similar issue on a Mac Book Pro M2, I had to deactivate SWC in next.config.js

**Comment by zdraffko** [comment]
I am experiencing the same issue with Next.js 13 on Windows 11.

**Comment by ijjk** [comment]
Hi, could you try removing any previous changes to `next.config.js` and only set `experimental: { swcFileReading: false }` to confirm whether it's related to that or not?

**Comment by OlegLustenko** [comment]
@ijjk oh wow! Thanks for the quick response, and even more, it helped!

![image](https://user-images.githubusercontent.com/11524061/224051029-0707f5e9-dea4-4faf-b8fc-3138f7f6bf52.png)

Can I treat it as a recommendation as-of-now?

**Comment by ijjk** [comment]
For now yes, we will investigate further!

**Comment by OlegLustenko** [comment]
More info after fresh `npm install` it still reproduced even with a flag

![image](https://user-images.githubusercontent.com/11524061/224538062-eec625ff-7241-4000-a5b5-6cc9301aec0f.png)

**Comment by OlegLustenko** [comment]
It still fantomly reproduced even with `swcFileReading` :(

It's a hard blocker for us and we have to revert back `13.1.6`

**Comment by OlegLustenko** [comment]
@ijjk, do we need to add some bug tags so it's not lost visibility?

The thing is in 13.2.x versions rewrites fixed for `appDir`

**Comment by SilentDepth** [comment]
Facing the same issue here. I did some little experiments in my Next.js + Tailwind CSS project and found that if I use brace expansion in the middle part of paths in Tailwind CSS `content` option, like `./{components,pages}/**/*.jsx`, then `next dev` will take a very long time to compile. Splitting it into several patterns (e.g. `['./components/**/*.jsx', './pages/**/*.jsx']`) solves my problem.

**Comment by wh5938316** [comment]
Is there any update on this? I am experiencing a similar issue where my dev builds are very slow on my **Mac Pro M1**. This issue occurs when using versions of Next.js above **13.2.4**, so I have had to lock my version to **13.2.4**.

**Comment by wadehammes** [comment]
Not sure if related, but I am getting this now like every build (happens very randomly) and my builds are 3x longer than they use to be to Vercel:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/222170/236580632-0173586e-e18c-4204-870a-cec9eb2e4ed9.png">

Avg build for our 1700 pages use to be 9-11min, now its taking 24min. I even went in and optimized over 100 images our marketing team had uploaded to our Contentful that were huge, shaving off roughly 200MB (yikes, I know).

**Comment by timneutkens** [comment]
Hey, can you share the `.next/trace` file when running on the previous version and then upgrade and share the trace file for that too. Then we can at least get some insight into what's different as there is no reproduction provided.

**Comment by timneutkens** [comment]
Closing this issue to consolidate the same reports here: https://github.com/vercel/next.js/issues/48748#issuecomment-1578374105.
Please follow the steps provided in order for us to investigate further.
