### ISSUE TITLE
Bug in pathname matching in remotePatterns

### ISSUE THREAD

**Issue by ns1000** [vercel/next.js#46903]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.14.1
      npm: 9.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.3
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-vxvpyx?file=pages/index.tsx

### To Reproduce

A url like: https://s.yimg.com/ny/api/res/1.2/.tN3tiOdZqngt0Dro4127w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/total_film_411/be25e8f1a01fff35142f9c4e3d8d215f

fails to match in the otherwise valid remotePatterns

    remotePatterns: [
      {
        protocol: "https",
        hostname: "*.yimg.com",
      },
    ],

### Describe the Bug

When using remotePatterns without a pathname next will default to the following code in match-remote-pattern.ts

```javascript
if (!makeRe(pattern.pathname ?? '**').test(url.pathname)) {
    return false
}
```

This however will fail to match a path in a url like:
https://s.yimg.com/ny/api/res/1.2/.tN3tiOdZqngt0Dro4127w--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzU-/https://media.zenfs.com/en/total_film_411/be25e8f1a01fff35142f9c4e3d8d215f

Foe now i solved it myself by changing the code to use a different regex
```javascript
let regex = /^(\/[^\s/?#]*)*$/
```

### Expected Behavior

The remote pattern should match

**Comment by itsmedmd** [comment]
Might be related recent stackoverflow issue:
https://stackoverflow.com/questions/75860419/why-doesnt-the-remotepatterns-wildcard-work-for-specific-images-in-next-js
