### ISSUE TITLE
app-dir-i18n - TypeError: dictionaries[locale] is not a function

### ISSUE THREAD

**Issue by Rover420** [vercel/next.js#46918]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 19.7.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

It was also previously tested with Node version 18.12.0
```

### Which example does this report relate to?

app-dir-i18n-routing

### What browser are you using? (if relevant)

not relevant - server bug - any browser

### How are you deploying your application? (if relevant)

occurs both - dev and start

### Describe the Bug

Hi. 

I've just cloned a fresh "app-dir-i18n-routing" example and since beginning when I open that app, it gives me a server-side error in console as below. Any ideas?

https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing

error - get-dictionary.ts (11:75) @ getDictionary
error - TypeError: dictionaries[locale] is not a function

https://discord.com/channels/752553802359505017/1082950382495473704/1082950382495473704

(I've provided also other bugs in this Discord topic)

Anyway, the app works, but it's annoying 🙁

![3](https://user-images.githubusercontent.com/100524342/223701243-f408f948-1698-461d-b66f-ff255f230fe9.jpg)

![4](https://user-images.githubusercontent.com/100524342/223701274-7b74f704-4772-477c-b66a-ee8f47ff09ad.jpg)

### Expected Behavior

I guess to not spam errors all the time someone opens the app.

### To Reproduce

idk, I've just cloned fresh example repo and it was already there. Tested it/cloned twice.

**Comment by Rover420** [comment]
Also if someone might be interested, I've improved the i18n middleware code to redirect user to preferred locale if it's provided in a cookie if it's valid, otherwise as it was - detect locale and finally defaultLocale. It might not be perfect, especially my Typescript knowledge, but it works just fine

![image](https://user-images.githubusercontent.com/100524342/223701602-501620ad-7b15-41d9-ab61-1ea383e7dc6a.png)

![image](https://user-images.githubusercontent.com/100524342/223701645-16ea7b9a-0b4e-4590-a4b0-dc5faa3f6849.png)

**Comment by Rover420** [comment]
Ok ChatGPT gave me a fix:

get-dictionary.ts file:

```
import 'server-only'
import type { Locale } from './i18n-config'

// We enumerate all dictionaries here for better linting and typescript support
// We also get the defalt import for cleaner types
const dictionaries: {[key: string]: () => Promise<{ [key: string]: { [key: string]: string } }> } = {
  en: () => import('./dictionaries/en.json').then((module) => module.default),
  pl: () => import('./dictionaries/pl.json').then((module) => module.default),
};

export const getDictionary = async (locale: Locale) => dictionaries[locale]()
```

**Comment by Rover420** [comment]
But I think there is a problem with this i18n routing example, because basically you can't access public folder (images), because it automatically redirects you to [lang]/example.png

**Comment by SuvorovAndrey** [comment]
Indeed, I guess it's also related to the middleware feature. I have exactly the same problem. In my project I have an image public folder, which is on the "matcher", once the page with images is loading, the console shows as many errors as images loaded. If you have only favicon.ico you can remove it from matcher, it will not show the error anymore.

**Comment by moneebalalfi** [comment]
Hello, did anyone solve the issue ?

**Comment by moneebalalfi** [comment]
This works for me 🤝

```
import 'server-only';
import { Locale } from './i18-config';

const dictionaries = {
  en: () => import('./dictionaries/en.json').then((module) => module.default),
  ar: () => import('./dictionaries/ar.json').then((module) => module.default),
};


export const getDictionary = async (locale: Locale) => {
  return locale == 'ar' ? dictionaries.ar() : dictionaries.en();
};
```

**Comment by SuvorovAndrey** [comment]
> This works for me 🤝
> 
> ```
> import 'server-only';
> import { Locale } from './i18-config';
> 
> const dictionaries = {
>   en: () => import('./dictionaries/en.json').then((module) => module.default),
>   ar: () => import('./dictionaries/ar.json').then((module) => module.default),
> };
> 
> 
> export const getDictionary = async (locale: Locale) => {
>   return locale == 'ar' ? dictionaries.ar() : dictionaries.en();
> };
> ```

Indeed, a good solution, we can also use i18n-config data to set defaultLocale in case if there is no locale available. Here is vanilla js solution :
`import 'server-only'
import { i18n } from './i18n-config'

const dictionaries = {
  fr: () => import('./dictionaries/fr.json').then((module) => module. Default),
  en: () => import('./dictionaries/en.json').then((module) => module.default),
}

export const getDictionary = async (locale) => i18n.locales.includes(locale) ? await dictionaries[locale]() : await dictionaries[i18n.defaultLocale]()`

**Comment by dongwonnn** [comment]
Based on the comments [here](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/base-server.ts#L2423), if the user doesn't have a favicon.ico file, the browser will provide a default favicon.ico. This favicon.ico is being caught by [lang] and causing the issue.

In reality, if you add any favicon.ico file under the public folder, this issue won't occur. But I want to investigate the root cause. (In my project, I use favicon.png)

**Comment by Viktror-INC** [comment]
I wrote easiest way

dictionary.ts

````
import en from "shared/dictionaries/en.json";
import ru from "shared/dictionaries/ru.json";

export type DictionariesLangs = keyof typeof dictionaries;


export const dictionaries = {
  en,
  ru,
};
````
Page or component
page.tsx

```
import {
  dictionaries,
} from "shared/dictionaries/dictionary";


export const Home = ({ params }) => {
  const lang = dictionaries[params.lang];
  console.log("en", lang);
  return <div>home</div>;
};

export default Home;
```

**Comment by eblanchette** [comment]
```

export const getDictionary = async (locale: string) => {
  const dictionary = dictionaries[locale];
  // Check to see if it's a function
  if (typeof dictionary === "function") {
    return dictionary();
  }
  return null;
};
```

**Comment by exelimpichment** [comment]
> ```
> export const getDictionary = async (locale) => dictionaries[i18n.locales.includes(locale) ? locale : i18n.defaultLocale]()
> ```

thank you mate

**Comment by armachino** [comment]
> Based on the comments [here](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/base-server.ts#L2423), if the user doesn't have a favicon.ico file, the browser will provide a default favicon.ico. This favicon.ico is being caught by [lang] and causing the issue.
> 
> In reality, if you add any favicon.ico file under the public folder, this issue won't occur. But I want to investigate the root cause. (In my project, I use favicon.png)

It's awkward but it works for me, thank you
