### ISSUE TITLE
Catch-all routes are never cached on Vercel

### ISSUE THREAD

**Issue by mritzerfeld** [vercel/next.js#46939]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
Binaries:
      Node: 19.6.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 13.2.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/mritzerfeld/next13-vercel-caching

### To Reproduce

Create a catch-all route in app directory and publish on Vercel.

### Describe the Bug

I already contacted Vercel support which recommended opening an issue here since app directory is still in beta.

Whenever using a catch-all route, Vercel is unable to cache the page. The x-vercel-cache response header will always be "MISS". Static routes however are cached and x-vercel-cache will return "HIT" starting with the second visit of the page.

This problems exists on catch-all routes without any fetch() calls (see linked example) or with fetch() calls regardless of their revalidation configuration (I tried long-during intervals or set revalidate to false).

I've deployed my linked example on https://next13-vercel-caching.vercel.app/.

- https://next13-vercel-caching.vercel.app/static will be returned from cached starting with second visit
- https://next13-vercel-caching.vercel.app/foo/bar with never be cached

On real-life deployments this results in a very bad TTFB when backend-calls are executed on every visit and fetch() is never cached.

### Expected Behavior

Catch-all routes should be returned from cache once executed for the first time.

### How are you deploying your application? (if relevant)

Vercel

**Comment by ijjk** [comment]
Hi, you need to either define `export const dynamic = 'force-static'` or `export function generateStaticParams() { return [] }` for the page to be considered dynamic. 

Example deployment with `export const dynamic = 'force-static'` https://next13-vercel-caching-gamma.vercel.app/
