### ISSUE TITLE
Docs: Make clear that custom API route config is exported from the API route itself

### ISSUE THREAD

**Issue by elenalape** [vercel/next.js#46932]
### What is the improvement or update you wish to see?

There should be an explicit warning that the [API Route Request Helper](https://nextjs.org/docs/api-routes/request-helpers#custom-config) config is not supplied in `next.config.js` but on each API endpoint.

The documentation states that

> Every API Route can export a config object to change the default configuration (...)

but given most of the route config, including headers and rewrites, usually lives in the global config, it's not clear _where_ the developer should be adding in that logic.

And if there is a way to do it from global config, an example would be appreciated!

### Is there any context that might help us understand?

Like many, we're used to managing most of our Next configuration, via `next.config.js`, so that's where I had been trying to add some extras to allow responses larger than Vercel's default 1MB limit.

[This Stackoverflow comment](https://stackoverflow.com/questions/70503440/how-to-override-the-4mb-api-routes-body-size-limit#comment133357296_74896701) finally helped.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-routes/request-helpers#custom-config

**Comment by leerob** [comment]
All options for the API routes config are added here: https://nextjs.org/docs/pages/building-your-application/routing/api-routes#custom-config
