### ISSUE TITLE
Why nextjs request not having geo or location available on azure services?

### ISSUE THREAD

**Issue by rishabh0504** [vercel/next.js#46942]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Please use the default configuration, nothing much done
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

use default template.

### To Reproduce

Just create a default template and deploy to azure instance.

### Describe the Bug

On azure, request object  geo is not providing request origin.

### Expected Behavior

It should provide the location for the request origin as normal application server  does.

### Which browser are you using? (if relevant)

Chrome/Safari

### How are you deploying your application? (if relevant)

Azure

**Comment by JesseKoldewijn** [comment]
How are you deploying to Azure if I may ask? Using sst by chance?

**Comment by JesseKoldewijn** [comment]
I'm asking because as far as I know the NextJS runtime doesn't natively support being ran on anything else than vercel. So in case you're using sst you might want to create an issue on their repo instead:
https://github.com/serverless-stack/open-next

**Comment by JesseKoldewijn** [comment]
@karlhorky Am I correct to assume that NextJS doesn't natively support Azure and AWS deployments by itself without open-next? Because if so, I think this issue could be closed.

**Comment by leerob** [comment]
> I'm asking because as far as I know the NextJS runtime doesn't natively support being ran on anything else than vercel
> Am I correct to assume that NextJS doesn't natively support Azure and AWS deployments

This is not accurate. Next.js works and runs everywhere, including self-hosting on Azure (either as a Node.js server or through a Docker container). More here: https://nextjs.org/docs/deployment#self-hosting

> Why nextjs request not having geo or location available on azure services?

Geolocation headers are not populated when running locally with `next dev` or for production with `next start` by default. This is an _optional_ addition that platforms supporting Next.js can add if they want. Having extremely accurate geolocation requires paying for a service, usually.

For example, a popular service is [MaxMind](https://www.maxmind.com/en/home). We can probably make this more clear in the documentation - it currently says "This information is provided by your hosting platform.".

**Comment by JesseKoldewijn** [comment]
Ah gotcha, I was under the understanding that there were curtain things within the nextjs runtime that only works hosted on vercel or though open-next.

**Comment by armannaj** [comment]
This is empty and undefined on vercel platform as well. As I mentioned it on [here](https://github.com/vercel/examples/issues/34)

**Comment by leerob** [comment]
Made this more clear in the docs: https://github.com/vercel/next.js/pull/59719
