### ISSUE TITLE
Next 13 + appDir: FOUC during HMR when `middleware.ts` present

### ISSUE THREAD

**Issue by timfee** [vercel/next.js#46947]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.4-canary.8
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```
### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/timfee/next-fouc

### To Reproduce

1. Create a trivial `layout.tsx` and `page.tsx`. In my repro, I wrapped things in a `<Provider>` and made a `fetch` call, as I was trying to rule out root causes.
2. Make changes to the file while running `next dev` and observe occasional FOUCs, but generally works OK.
3. Add a trivial `middleware.ts` file
4. Observe that any change causes a full-on flash of content.

![Screen Shot 2023-03-08 at 19 02 49](https://user-images.githubusercontent.com/3246342/223906388-7eff4d5e-521b-4a66-bd53-a3aec2bac024.gif)

### Describe the Bug

Styles seem to be removed and re-added when `middleware.ts` is present.

### Expected Behavior

Adding `middleware.ts` doesn’t affect my files (or if I need to manually specify a matching pattern that excludes css files, etc., that it would be clearly documented)

### Which browser are you using? (if relevant)

Chrome latest

### How are you deploying your application? (if relevant)

`next dev`

### Similar issues
https://github.com/vercel/next.js/issues/46868

**Comment by shuding** [comment]
This issue is fixed in newer versions with a test add in https://github.com/vercel/next.js/pull/47708. Let us know if you're still running into it, thanks!
