### ISSUE TITLE
SWC: async generator bug

### ISSUE THREAD

**Issue by pindjur** [vercel/next.js#47021]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue

https://github.com/pindjur/swc_bug

### To Reproduce

1. Clone above repo
2. npm i && npm run dev
3. Visit http://localhost://3000
4. open browser devtools console

### Describe the Bug

There is a bug when polifying async generators and iterators for some browsers. Code execution order is wrong in certain situations when while loop  is used inside try block followed by finally block. I can confirm this work as expected with babel(see with_babel branch).

Console output is:
```  
yield
iteration
finally
yield
iteration
finally
yield
iteration
finally
yield
iteration
finally
finally
```

### Expected Behavior

But should be:

```
yield
iteration
yield
iteration
yield
iteration
yield
iteration
finally
```

### Which browser are you using? (if relevant)

Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)

**Comment by MartinPavlik** [comment]
Hi @pindjur, I've also hit this issue and it looks like it was fixed in [SWC v1.3.47](https://github.com/swc-project/swc/pull/7215) so using newer version of next.js should fix it, for example [v13.4.9](https://github.com/vercel/next.js/blob/v13.4.9/package.json)
