### ISSUE TITLE
[NEXT-978] `./app/[[...params]]/page.tsx` gives `SyntaxError: "undefined" is not valid JSON at JSON.parse (<anonymous>)`

### ISSUE THREAD

**Issue by timfee** [vercel/next.js#47024]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.5-canary.0
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

trivial example below

### To Reproduce

Create a trivial page
```tsx
// ./app/[[..params]]/page.tsx

export default function Page(params) {
  return <>hello</>
}
```

### Describe the Bug

Doing so returns:
```
error - SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
```

Note that if I remove the double bracket notation, the error goes away.

### Expected Behavior

The opposite :)

### How are you deploying your application? (if relevant)

next dev

<sub>[NEXT-978](https://linear.app/vercel/issue/NEXT-978/app[[params]]pagetsx-gives-syntaxerror-undefined-is-not-valid-json-at)</sub>

**Comment by timfee** [comment]
My workaround for now:
```tsx
// ./app/page.tsx
import { redirect } from "next/navigation"

export default function Page() {
  redirect("/default")
}
```
```tsx
// ../app/[...params]/page.tsx
// ^^ removed the [[]] notation

export default function Page(params) {
  return <>hello</>
}

```

**Comment by MathysHenry** [comment]
Hey,

I use next v13.2.4, I've got the same problem but on my two dynamic routes for the moment `app/[slug]` & `app/[slug]/[product_slug]`. I guess it happens on routes with multiple dynamic args.

Other information, i always get this error in production but rarely in development, and it happens after a manual reload of the current page.

**Comment by MathysHenry** [comment]
@timfee I found out that the issue comes from something around my `global-error.tsx` file. If I try rebuild the application and start the server after deleting the `global-error.tsx` file, the dynamic routes of my application do not trigger this error again.

Are you using this file in your project ?

**Comment by DeveloperHIT** [comment]
I am getting this same error, as well.

` 
1 of 1 unhandled error
Next.js is up to date

Unhandled Runtime Error
SyntaxError: "undefined" is not valid JSON

Call Stack
JSON.parse
<anonymous>
React`

**Comment by DeveloperHIT** [comment]
I was able to fix this issue by changing my <></> to <div></div>

No idea why this works, but it fixed the issue for me. I had empty div's on each of my page.tsx. I am assuming that whatever is in <></> is the first item in JSON while the contents of child layouts represent the rest of the JSON. So, the <></> was throwing an error saying the first element in the JSON was not valid.

**Comment by mmpneo** [comment]
I'm seeing this error on a freshly scaffolded 13.2.5-canary.30 app with providers wrapper even without fragments
last working version for me is v13.2.5-canary.19 after that everything broke

removing "use client" fixes it

providers.ts
```ts
"use client";
export function Providers({ children }: any) {
  return <>{children}</>;
}
```
layout.tsx
```tsx
import { Providers } from "./components/providers";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
```
```
error - SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
```

**Comment by tlgsn** [comment]
I getting error after 13.3 update

**Comment by Evan1115** [comment]
same issue when specifying "use client".

**Comment by alexdwvar** [comment]
same for me, but when I first declare the function and after I export it works

**Comment by a-ramakrishnan** [comment]
For some reason, doing 
function <func name> () { } and
export default <func name> it works fine

Does not work, when I do
const <func name> = () => {}
 or
put the export along with the function declaration.

This happens on all pages, not just on dynamic ones.

**Comment by chris-pikul** [comment]
Just ran into this as well, using `global-error.tsx` just does not work. 

```
"dependencies": {
  "next": "^13.3.0",
  "react": "^18.2.0",
  "react-dom": "^18.2.0"
}
```

**Comment by beckblakestrom** [comment]
Ran into this as well in next 13.3.0 - triggered when using "use client" on any page or component. Was non issue in last project, next 13.2.4

No fixes or workarounds yet

**Comment by nickali2** [comment]
> Ran into this as well in next 13.3.0 - triggered when using "use client" on any page or component. Was non issue in last project, next 13.2.4
> 
> No fixes or workarounds yet

I have the same issue

**Comment by braswelljr** [comment]
```bash
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
```

having this issue even degrading to back to 13.2.4 which was working is giving me this error.

**Comment by edgarrps** [comment]
This problem happened to me on windows but not on mac, with the same project

**Comment by beckblakestrom** [comment]
> ```shell
> SyntaxError: "undefined" is not valid JSON
>     at JSON.parse (<anonymous>)
> ```
> 
> having this issue even degrading to back to 13.2.4 which was working is giving me this error.
> 
> * they are happening in client components.

Did you use "npm install next@13.2.4" ? Simply changing your package.json next version and then just using npm install will not fix issue. Using "npm install next@(version)" did work for me however, at least in development, have not used in production yet.

**Comment by Niclassg** [comment]
I have this problem after upgrading to 13.3.0, reverting back to 13.2.4 fixes it. Will wait for a hotfix.

**Comment by xiwoo** [comment]
Unfortunately for me, I'm using the 13.2.4 version, but it doesn't fix the issue.
In general, it seems that undefiend is invoked in the order of importing error-boundry.js.

**Comment by oliver-oloughlin** [comment]
Upgraded to Next.js 13.3 and immediately encountered this issue. Reverted back to 13.2.4 and everything was fine again. The presence of error.tsx or global-error.tsx made no difference. To me it seemed like the error occured as soon as a client component tried to run. As in it wouldn't even run a console.log at the very start of the functional component.

**Comment by naveen-polasa** [comment]
i was using latest version 13.3 faced the same issue multiple times but after changing the version to 13.2.4 everything is fine now

**Comment by damien-schneider** [comment]
Same for me, using back the 13.2.4 solved the problem

**Comment by nosovandriy** [comment]
The same trouble, while rolled back to the previous version...

**Comment by mohammadrz003** [comment]
use your function like this and then the error disappear:

```
const Home = () => {
    return (
       <div></div>
    )
}

export default Home
```

**Comment by ilhamgepe** [comment]
> if you're using `"use client"` and face this error, use your function like this and then the error disappear:
> 
> ```
> const Home = () => {
>     return (
>        <div></div>
>     )
> }
> 
> export default Home
> ```

this solution work for me.

**Comment by shuding** [comment]
Hi all! There seem to be multiple different reports in this thread, and I believe some of them have been fixed already. With the latest canary, I can no longer reproduce these problems on my machine:

1:

```jsx
// ./app/[[..params]]/page.tsx

export default function Page(params) {
  return <>hello</>
}
```

2:

```jsx
"use client";
export function Providers({ children }: any) {
  return <>{children}</>;
}
```

### If you are still getting an issue with latest canary (>= 13.3.1-canary.4), please share a reproduction with your Next.js version and operating system name. This will help me debugging the problem, thanks!

**Comment by ackDeckard** [comment]
Upgrading to the lastest canary fixed my issue.

**Comment by shuding** [comment]
Closing it then 👍

**Comment by manuelMarkDenver** [comment]
> if you're using `"use client"` and face this error, use your function like this and then the error disappear:
> 
> ```
> const Home = () => {
>     return (
>        <div></div>
>     )
> }
> 
> export default Home
> ```

This one resolved it! I spent hours and hours of installing and reverting next versions. Thank a lot dude!

**Comment by mabdullahadeel** [comment]
I faced this issue with `next@13.3.0`. In my case 

> https://github.com/vercel/next.js/issues/47024#issuecomment-1502874376

This solved the issue but I started having other errors regarding hydration (content mismatch). Only happened on hard reload on the page. (app/q/[qid]/page.tsx)

I used
```
pnpm create next-app
```
to bootstrap the application.

### This solved the issue for me 👇

Installing latest canary release manually solved the issue for me

```
pnpm i next@canary
```

**Comment by ZakariaRekhla2004** [comment]
the solution of error .
Change package.json in dev : "next dev --turbo "

**Comment by ivanhouttaylor** [comment]
I had the same issue, was tearing my hair out trying to figure out what was causing it.

package.json dependencies:
```
    "next": "^13.3.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router": "^6.3.0",
```

Like others have suggested, when using `'use client'` you have to change the way that functions are exported to fix the problem.

```
'use client';

export default function SignIn () { ... }
```

to instead

```
'use client';

function SignIn() { ... }

export default SignIn;
```

And for me, the issue was fixed.

**Comment by ZakariaRekhla2004** [comment]
Thank you so much brother

Le ven. 21 avr. 2023 à 19:26, ivanhouttaylor ***@***.***> a
écrit :

**Comment by graceyudhaaa** [comment]
> to instead
> 
> ```
> 'use client';
> 
> function SignIn() { ... }
> 
> export default SignIn;
> ```

this fixed things for me, wow thankyou it's been hours

**Comment by ethanneff** [comment]
this is still broken on `next 13.4.2`. works on macs, fails on window machines

**Comment by timneutkens** [comment]
Please open a new issue following the template with a reproduction.
