### ISSUE TITLE
Next 13+ AppDir - Dynamic Route Segment Config not working

### ISSUE THREAD

**Issue by lukasedw** [vercel/next.js#47033]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #41-Ubuntu SMP Fri Feb 10 19:59:45 UTC 2023
    Binaries:
      Node: 18.9.0
      npm: 9.5.0
      Yarn: 3.2.1
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.5-canary.1
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/patrick91/next-time.git

### To Reproduce

The code fetches with Graphql the current time. If you refresh the page it will cache, `export const dynamic = "force-dynamic";` [here](https://github.com/patrick91/next-time/blob/main/app/force-dynamic/page.tsx) doesn't work.

### Describe the Bug

[Segment config](https://beta.nextjs.org/docs/api-reference/segment-config#configrevalidate) dynamic is not working as intended.

### Expected Behavior

To not cache the fetch of apollo

### How are you deploying your application? (if relevant)

npm run dev

**Comment by jmaestree** [comment]
> It's happening since 13.2.4 for me. I reverted back to 13.2.3 for now, everything started working again.

Same for me, reverting and using `13.2.3` the issue disappears.

**Comment by twalker1998** [comment]
I'm still experiencing this on `13.5.6`. I'm not quite ready to upgrade to NextJS 14- perhaps it is fixed there? Either way, this bug still exists and I'd really like to not have to revert to an older version.
