### ISSUE TITLE
Gayperez

### ISSUE THREAD

**Issue by ASQGVRVZYQRSJ7JE** [vercel/next.js#47042]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Https://onlyfans.com armandogutierrezperez26@gmail.com armandogutierrezperez29@gmail.com.mx_/FILE @gmail.com @mx.xxxgay_y
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

Xxxgay@gmail.com 

### To Reproduce

if (!GoogleSignIn.hasPermissions(
        GoogleSignIn.getLastSignedInAccount(getActivity()),
        Drive.SCOPE_APPFOLDER)) {
    GoogleSignIn.requestPermissions(
            MyExampleActivity.this,
            RC_REQUEST_PERMISSION_SUCCESS_CONTINUE_FILE_CREATION,
            GoogleSignIn.getLastSignedInAccount(getActivity()),
            Drive.SCOPE_APPFOLDER);
} else {
    saveToDriveAppFolder();
} @xxxgay 

- [ ] canary[PayPal.me](url)`<a href="#"  #canary://armando xnxxperez sexogayperez `_canary

### Describe the Bug

#perezgay

### Expected Behavior

K@AcanarySQGVRVZYQRSJ7JE/canary xxxgay_ywww.paypal.com.paypal.com 

### Which browser are you using? (if relevant)

Https://github.com/xnxxperez sexogayperez://xxxgay_ywww.paypal.com 

### How are you deploying your application? (if relevant)

*Twitter.com

**Comment by Xxxgay** [comment]
***@***.***

xnxxperez
