### ISSUE TITLE
Safari IOS <=13 support broken

### ISSUE THREAD

**Issue by rusted-love** [vercel/next.js#47045]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/blob/287ad83399fa6e90deae4ab75a5f9f762adc45e7/packages/next/src/shared/lib/fnv1a.ts#L5-L33

### To Reproduce

Use `next/image` component on any page. Run `next build` and open it in Safari IOS 13 and earlier.

### Describe the Bug

After recent update https://github.com/vercel/next.js/pull/46283 NextJs throws and error `ReferenceError: Can't find variable: BigInt` for Safari version 13 and earlier.
As described here https://nextjs.org/docs/basic-features/supported-browsers-features minimum support version is 12.
I don't use bloom filter for my images. But in that file BigInt used outside of function. 

https://github.com/vercel/next.js/blob/287ad83399fa6e90deae4ab75a5f9f762adc45e7/packages/next/src/shared/lib/fnv1a.ts#L5-L33

Its imported here
https://github.com/vercel/next.js/blob/287ad83399fa6e90deae4ab75a5f9f762adc45e7/packages/next/src/shared/lib/bloom-filter/hashing.ts#L1

### Expected Behavior

Do not use BigInt in NextJs codebase. Or maybe move BigInt initialisation to function call. That would prevent broken Safari 13 for those who don't use bloom image filter.

### Which browser are you using? (if relevant)

Safari IOS 13

### How are you deploying your application? (if relevant)

next serve

**Comment by ijjk** [comment]
Hi, can you share a reproduction? This is only loaded if you are using `appDir: true` or enable an experimental config. 

x-ref: https://github.com/vercel/next.js/blob/d08caa88ba4332bf30de4774c886404115afc366/packages/next/src/shared/lib/router/router.ts#L779

**Comment by rusted-love** [comment]
@ijjk yes, I approve that issue exists only `appDir: true` enabled. 
I migrated few url back to pages and disabled `appDir: true`. So now it works.

**Comment by rusted-love** [comment]
I close issue. Just do not use `app` dir ass suggested by @ijjk. Wait for release.

**Comment by semy** [comment]
We are already live with app dir (even if you should not), so it is not so easy to no longer use the app dir. Would therefore be good if a short note comes by @ijjk as soon as the problem is fixed :)
