### ISSUE TITLE
Client side async page throw an error

### ISSUE THREAD

**Issue by Axiol** [vercel/next.js#47044]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 19.3.0
      npm: 9.2.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.1
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Axiol/baro-cyclo-next/blob/planetscale-prisma-swtich/app/avis/%5Bslug%5D/page.tsx

### To Reproduce

I'm trying to build a page with client interactions that will lead to async call to save data. So, the page needs to be declared as client and async like so : 

```javascript
'use client'

import { useState } from 'react'

const getPlace = async (name: string) => {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_LOCAL_URL}/api/places/${name}`,
    {
      cache: 'no-store',
    }
  )

  if (!res.ok) {
    throw new Error('Failed to fetch data')
  }

  const data = await res.json()

  return data.place
}

const Review = async ({ params }: { params: { slug: string } }) => {
  const place = await getPlace(params.slug)

  //...
}
```

But, as soon as I add the `async` to my page declaration, it throws an error

### Describe the Bug

The app returns this error : 

> Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.

### Expected Behavior

I should be able to have an async page on the client

**Comment by pindjur** [comment]
Async server components are only supported. https://github.com/acdlite/rfcs/blob/first-class-promises/text/0000-first-class-support-for-promises.md
