### ISSUE TITLE
[Next.js 13](https://nextjs.org/13) introduces the [`app` directory](https://beta.nextjs.org/docs/routing/fundamentals) (beta) with new features and conventions. However, upgrading to Next.js 13 does **not** require using the app directory.

### ISSUE THREAD

**Issue by hunain3199** [vercel/next.js#47052]
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature (appDir) in next.config.js.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - VS Code settings.json has been created for Next.js' automatic app types, this file can be added to .gitignore if desired
(node:15812) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
info  - Using wasm build of next-swc

whats this issue server is not opening means local host 3000 is not opening

**Comment by codeDaiQin** [comment]
I had the same problem

**Comment by pavlosantoniou13** [comment]
Did you fix it? i have the same thing

**Comment by pavlosantoniou13** [comment]
Guys i fixed it. you have to uninstall node and install the latest version. maybe you have installed the wrong bit version.

**Comment by pavlosantoniou13** [comment]
> ready - started server on 0.0.0.0:3000, url: http://localhost:3000 warn - You have enabled experimental feature (appDir) in next.config.js. info - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback warn - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> 
> info - VS Code settings.json has been created for Next.js' automatic app types, this file can be added to .gitignore if desired (node:15812) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time (Use `node --trace-warnings ...` to show where the warning was created) info - Using wasm build of next-swc
> 
> whats this issue server is not opening means local host 3000 is not opening
Guys i fixed it. you have to uninstall node and install the latest version. maybe you have installed the wrong bit version.

**Comment by pavlosantoniou13** [comment]
> I had the same problem

Guys i fixed it. you have to uninstall node and install the latest version. maybe you have installed the wrong bit version.

**Comment by timneutkens** [comment]
Going to close this issue as somehow the issue template was bypassed and a reproduction was not provided.
