### ISSUE TITLE
Docs: How to conditionally stop navigation

### ISSUE THREAD

**Issue by srowe0091** [vercel/next.js#47071]
### What is the improvement or update you wish to see?

In the new "app" directory, I would like to see how to conditionally stop the user from navigating away when a Link is clicked or navigation occurs to alert the user they are leaving unsaved changes.

### Is there any context that might help us understand?

Router events was removed in version 13 with the "app" directory, and there has not been a replacement, nor seems like theres a plan for one. This is a fundamental feature through out many applications.

**Comment by sinclairnick** [comment]
Same. Router events seem to have been removed. While you can identify route changes via `const pathname = usePathname()` changes, you cannot actually modify navigation behaviour, it seems, just yet.

**Comment by geoffoliver** [comment]
The lack of this feature definitely breaks my use case of preventing people from accidentally leaving an edited form.

**Comment by srowe0091** [comment]
Same, The lack of attention this is getting makes it seem like its not a problem for others. I opened this back in March and no so far nothing has happened

**Comment by izumin5210** [comment]
Same. The current App Router cannot prevent form content from being lost due to unintended browser backs.
Will have to go back to a page router.
we may have to revert to Pages Router.

**Comment by BillyLevin** [comment]
This still appears to be difficult to achieve and quite buggy with Pages router. Does anyone have a good example of this being implemented? Throwing inside one of the route events does stop navigation, but sometimes the address in the URL bar still changes

This is a common pattern on pretty much any web page that has a form, so I'm surprised that it's so complicated to achieve in Next

**Comment by mrksph** [comment]
> The lack of this feature definitely breaks my use case of preventing people from accidentally leaving an edited form.

Same here, just came up with this issue and while it looks like a common pattern in other frameworks I can't find any easy way to implement it

**Comment by nadeem-golflan** [comment]
any update on this guys? Has anyone found a way to work around this problem or any other approach that might help in achieving the desired output.

**Comment by timneutkens** [comment]
We've recently posted a thorough reply on some alternatives for cases router events were previously used for, you can find that here: https://github.com/vercel/next.js/discussions/41934#discussioncomment-8996669

Going to close this issue to consolidate these discussions as the case asked for is covered in that reply.
