### ISSUE TITLE
[NEXT-1176] Debugging with non-localhost address stopped working

### ISSUE THREAD

**Issue by gregmartyn** [vercel/next.js#47083]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Fri Mar  3 17:29:44 UTC 2023
    Binaries:
      Node: 17.9.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/blame/8d83d85e5359146bbbd0f96ea2f8490e7d6bc9cd/packages/next/src/cli/next-dev.ts#L488

### To Reproduce

NODE_OPTIONS=--inspect=0.0.0.0:9229 next dev

### Describe the Bug

NodeJS's `--inspect` switch takes an optional address as a parameter that isn't being honored by Next. Next crashes when that is present.
spec: `--inspect[=[host:]port]`
https://nodejs.org/api/cli.html#--inspecthostport

In order to be able to expose a debugger from inside a Docker container, it has to listen on `0.0.0.0` instead of the default `127.0.0.1`. To do that, we have to specify `--inspect=0.0.0.0:9229`.

https://github.com/vercel/next.js/blame/8d83d85e5359146bbbd0f96ea2f8490e7d6bc9cd/packages/next/src/cli/next-dev.ts#L488

assumes the parameter is an integer: `parseInt(debugPortStr, 10)`, but `debugPortStr` could be e.g. `0.0.0.0:9229`

https://github.com/vercel/next.js/blob/canary/packages/next/src/cli/next-dev.ts#L524
then does
`--inspect${isDebuggingWithBrk ? '-brk' : ''}=${debugPort + 1}`

which crashes:
```
warn  - the --inspect option was detected, the Next.js server should be inspected at port 1.
/usr/bin/node:  must be 0 or in range 1024 to 65535.
```

### Expected Behavior

Next should parse out and honor the address part of the --inspect switch.

### How are you deploying your application? (if relevant)

Docker for local dev, Vercel for hosting

<sub>[NEXT-1176](https://linear.app/vercel/issue/NEXT-1176/debugging-with-non-localhost-address-stopped-working)</sub>

**Comment by JackWatson06** [comment]
Thank you for posting this! You beat me to it. Was having this EXACT same issue yesterday.

**Comment by itsravenous** [comment]
I have this issue too (using e.g. `--inspect=:9230`). Curious, why does Next try to increment the port number?

**Comment by JackWatson06** [comment]
> I have this issue too (using e.g. `--inspect=:9230`). Curious, why does Next try to increment the port number?

The dev server spawns a new child node.js process (which has been occurring since recent updates to Next.js) - as such, it increments the inspect debug port as it's different from the primary process which started next.js. This comment somewhat discusses this concept: https://github.com/vercel/next.js/pull/45745/files#r1101862213

**Comment by edorgeville** [comment]
@JackWatson06 points in the right direction.
This line more specifically:
https://github.com/vercel/next.js/blob/8b44085b703e973487c843d93bc1662aaecd7912/packages/next/src/cli/next-dev.ts#L518
It expects `debugPortStr` to be shaped like an integer. But if you use `--inspect:0.0.0.0:12345`, `debugPortStr` is now `0.0.0.0:12345`, thus the parse fails and returns 0.
Then not long after, it tries using this 0 port and does +1 on it. https://github.com/vercel/next.js/blob/8b44085b703e973487c843d93bc1662aaecd7912/packages/next/src/cli/next-dev.ts#L541
Causing the `/usr/bin/node:  must be 0 or in range 1024 to 65535.` error.

**Comment by pirtlj** [comment]
I'm seeing this as well,  using docker running 

    "dev": "NODE_OPTIONS=\"--inspect=0.0.0.0:9229\" next dev -p 3001",

and no longer hitting break points

**Comment by Cow258** [comment]
Hi @huozhi,

If you have some spare time, would you be able to help me further with this issue? 

Debugger is something I often use to quickly find problems, 
but the latest release is not working for me and it's causing me some trouble. 

Thank you.

**Comment by pirtlj** [comment]
I'm having this issue still 13.3.1 i'm using 

`NODE_OPTIONS=\"--inspect=0.0.0.0:9229\" next dev -p 3001`

I'm also running in docker with 

    ports:
      - "3001:3001"
      - "9229:9229"
      - "9230:9230"

**Comment by gregmartyn** [comment]
@ijjk I don't see the fix addressing an inspect arg with an IP address like `--inspect=0.0.0.0:9229`
