### ISSUE TITLE
Docs: Note that need to turn off mdxRs when using MDX plugins

### ISSUE THREAD

**Issue by paulwongx** [vercel/next.js#47098]
### What is the improvement or update you wish to see?

As per this issue, it's not stated in the docs that you need to turn off mdxRs in order to use remark/rehype/recma plguins.
https://stackoverflow.com/questions/75571651/using-remark-and-rehype-plugins-with-nextjs-13

The relevant part of the docs is here:
https://beta.nextjs.org/docs/guides/mdx#remark-and-rehype-plugins

### Is there any context that might help us understand?

State that mdxRs needs to be turned off for `import nextMDX from "@next/mdx"` to work. 

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/guides/mdx#remark-and-rehype-plugins

**Comment by mattrossman** [comment]
This was really frustrating for me because the docs specifically tell you to enable mdxRs at the start, then proceeds to show how to add plugins, then at the *very* end of the page it's mentioned **not** to use the option because it's experimental. Took me a while to connect the dots as to why plugins were silently failing.

If the option isn't recommended, it probably shouldn't be in the "Getting Started" section that newcomers will be following.

**Comment by nareshbhatia** [comment]
[Reposting my response to the above stackoverlow thread]

I am also trying to follow [Next.js MDX docs](https://nextjs.org/docs/app/building-your-application/configuring/mdx), but running into fundamental problems (already tried `mdxRs: false`). For me even a hello world page is not rendering. This is the error I get:

```
 ⨯ node_modules/@mdx-js/react/lib/index.js (34:26) @ React
 ⨯ createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at __webpack_require__ (/Users/naresh.bhatia/projects/blog-template/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/articles/hello-world/page.mdx:6:71)
    at (rsc)/./src/app/articles/hello-world/page.mdx (/Users/naresh.bhatia/projects/blog-template/.next/server/app/articles/hello-world/page.js:325:1)
    at Function.__webpack_require__ (/Users/naresh.bhatia/projects/blog-template/.next/server/webpack-runtime.js:33:42)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
null
```

Don't understand where in the code it is trying to use `createContext` and is suggesting to add `use client`. All I am trying to do is to create a static site, with all content in the repository - not even using `<MDXRemote>`. Would appreciate any thoughts to get me unstuck!

My repo is here: https://github.com/nareshbhatia/blog-template

**Comment by lu-zen** [comment]
This still is a problem.

**Comment by leerob** [comment]
Fixed!
