### ISSUE TITLE
Docs: Is there a way i can access the pathname in the page.tsx file in next13 with the new app folder?

### ISSUE THREAD

**Issue by danielgroen** [vercel/next.js#47108]
### What is the improvement or update you wish to see?

why do i want this?

for example, i have a sidebar. The sidebar i only need to render as ssr since the sidebar won't change.
Only the links inside the sidebar need a active class when the current path is the same as the href in the link component in the sidebar.

### Is there any context that might help us understand?

So you have the sidebar here.
It would be helpfull if i have access to pathname, or just simply to the req object.

page.tsx

```
export default function layout() {
 return (
 <div className="sidebar">
  <Link href="/about">about</Link>
 </div>
 )
}
```

**Comment by JesseKoldewijn** [comment]
Do you want to have access to the pathname on the client or the server side? Cuz on the client side you can just use the following:
```
window.location.pathname
```

**Comment by zek** [comment]
@danielgroen You can check out https://beta.nextjs.org/docs/api-reference/use-selected-layout-segment

However I'm also looking a way to access NextRequest object globally. I don't see any way to do it.

**Comment by kossnocorp** [comment]
@JesseKoldewijn @zek but these methods don't work in the service components, don't they? From the context, I assume that's what the question was about, as I would render navigation on the server.

Either way, can you please point to the method that will work on the server?

**Comment by JesseKoldewijn** [comment]
Serverside solution to this could be using middleware. Example below:

```tsx
import { NextResponse } from 'next/server'; 
export function middleware(request: Request) { // Store current request url in a custom header, which you can read later const requestHeaders = new Headers(request.headers); requestHeaders.set('x-url', request.url); return NextResponse.next({ request: { // Apply new request headers headers: requestHeaders, } }); }
```

**Comment by kossnocorp** [comment]
@JesseKoldewijn thank you, Jesse! The middleware approach worked out for me. I found similar code in another issue, but TypeScript complained about it. Here's what I ended up writing (I hope it's helpful for others):

```ts
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { nanoid } from "nanoid";

export function middleware(request: NextRequest) {
  // Pass the pathname to the server components
  const headers = new Headers(request.headers);
  headers.set("x-pathname", request.nextUrl.pathname);

  const response = NextResponse.next({
    request: { headers },
  });

  // Assign a CSRF token to the response cookies
  const existingToken = request.cookies.get("csrfToken")?.value;
  if (!existingToken) response.cookies.set("csrfToken", nanoid());

  return response;
}
```

**Comment by JesseKoldewijn** [comment]
Other alternative is getting just the title from the meta and base you path logic on that, but I think the middleware flow is way better and not all that complicated👌

**Comment by jeengbe** [comment]
Would be even better if Next.js could support this automatically. Something like a more detailed `useSelectedLayoutSegment()` for server components.

**Comment by jeengbe** [comment]
See this discussion for a proposal for adding more methods like `headers()`:  #47976

**Comment by studentIvan** [comment]
> Serverside solution to this could be using middleware. Example below:
> 
> ```tsx
> import { NextResponse } from 'next/server'; 
> export function middleware(request: Request) { // Store current request url in a custom header, which you can read later const requestHeaders = new Headers(request.headers); requestHeaders.set('x-url', request.url); return NextResponse.next({ request: { // Apply new request headers headers: requestHeaders, } }); }
> ```
> 
> Ps sorry for the formatting of the example. Currently on mobile.

Hi. It makes the static params broken (SSG), so is not the solution

**Comment by timneutkens** [comment]
It's intentional that layouts don't have access to request-specific data besides `headers()` / `cookies()` as they do not get rerendered when the navigation has shared layouts. You can read more about that here: https://nextjs.org/docs/app/building-your-application/routing#partial-rendering. If you do what @kossnocorp suggested subsequent navigations will have the layouts in a state where they still show the previous path, instead of the current path.

I'll bring up providing `pathname` as part of `page.js` (similar to `searchParams`) to the team 👍

**Comment by timneutkens** [comment]
Duplicate of #43704
