### ISSUE TITLE
Docs: Clarification regarding the behaviour of legacyBehavior prop in NextLink

### ISSUE THREAD

**Issue by nik32** [vercel/next.js#47114]
### What is the improvement or update you wish to see?

In the nextJS docs (link - https://nextjs.org/docs/api-reference/next/link)… there is a note which goes as follows - “Note, when legacyBehavior is not set to true, all anchor tag properties can be passed to next/link as well such as, className, onClick, etc.” Firstly, typescript is forbidding me to pass the ‘legacyBehavior’ prop itself. Even if I ignore TS and pass the legacyBehavior={false} as stated in the note… still the className I passed to <Link> is not getting applied to the child <a> of <Link> element. Can you rectify this mistake on docs? Or else can you guys guide to me what is it that I am doing wrong? And also why your type definitions of <Link> is not specifying this prop. Due to it TS is throwing error if I try to pass the prop

### Is there any context that might help us understand?

https://nextjs.org/docs/api-reference/next/link (refer to the above issue expl)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-reference/next/link

**Comment by JesseKoldewijn** [comment]
Sounds like you're either missing the nextjs types or have an incorrect tsconfig maybe. 
Can't reproduce this in both canary and the last version of nextjs 12.

ref to commit where this boolean was added:
https://github.com/vercel/next.js/commit/489e65ed98544e69b0afd7e0cfc3f9f6c2b803b7

**Comment by nik32** [comment]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/51018572/225018403-b67c5814-4894-4f5e-ba26-dfd70c7072d4.png">

This is the link.d.ts and there is no legacyBehaviour in it. What can be done?? I using v12.1.5

**Comment by DuCanhGH** [comment]
@nik32 you are using an old version of Next. Next's docs usually only applies to the latest version of it. Perhaps that feature wasn't available back then, please try upgrading first. Also, in Next 12, the new next/link behavior isn't enabled by default - just a reminder :)

**Comment by JesseKoldewijn** [comment]
> @nik32 you are using an old version of Next. Next's docs usually only applies to the latest version of it. Perhaps that feature wasn't available back then, please try upgrading first. Also, in Next 12, the new next/link behavior isn't enabled by default - just a reminder :)

Was about to send the same ;)

**Comment by JesseKoldewijn** [comment]
@nik32 And if you need to stay on the older version of Next you could try and see if the following config option was available already back in 12.1.5 

```
next.config.js

experimental: {
    newNextLinkBehavior: true,
  },
```

**Comment by JesseKoldewijn** [comment]
It could maybe be an improvement to add a reference to the NextJS version targeted in the code shown in the docs so things like these couldn't happen.

**Comment by nik32** [comment]
@JesseKoldewijn @DuCanhGH  thanks for your prompt reply. I agree that adding the version for which the note is targeted would really help.

> @nik32 For what purpose do you need the legacyBehavior for?

@JesseKoldewijn I just wanted to pass a className for styling the child of Link. I was trying to pass it through the link tag itself as stated in the docs but was confused when the styles did not apply (coz its mentioned in docs). That's why thought of posting this issue... to know whether there is a gap in my understanding or if I am doing something wrong
