### ISSUE TITLE
[NEXT-820] OTEL: add `http.route` to `SERVER` spans

### ISSUE THREAD

**Issue by jankaifer** [vercel/next.js#47113]
[Is there any way we could set ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions)`http.route` here?

Without this it's impossible to do aggregate analysis on paramaterized routes, since they would all have different URLs, which is something APM providers (like Sentry for example) would need!

*Originally posted by @AbhiPrasad in* [*https://github.com/vercel/next.js/pull/47066#discussion_r1135323331*](https://github.com/vercel/next.js/pull/47066#discussion_r1135323331)

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-820](https://linear.app/vercel/issue/NEXT-820/otel-add-httproute-to-server-spans)</sub>

**Comment by jankaifer** [comment]
@AbhiPrasad forgot to ask you if the changes implemented in #47392 are sufficient for using it in the Sentry SDK.

**Comment by AbhiPrasad** [comment]
Yup! This looks great! Are we adding this to edge routes any time soon?

**Comment by jankaifer** [comment]
It's on the roadmap, but we want to iron out any quirks with `nodejs` first.
