### ISSUE TITLE
Cookies are missing and are not updated if a request to Route Handler is sent from the server side

### ISSUE THREAD

**Issue by ndt080** [vercel/next.js#47126]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
"next": "13.2.4"
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/magical-chihiro-zgtbmr?file=%2Fnext.config.js&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A3%7D%5D

### To Reproduce

Send a request to Route Handler from the server side

Route Handler always has empty tokens, and tokens are never passed to the main response to receiving the page.
```
export async function POST(request: NextRequest) {
    const accessToken = cookies().get(StorageKey.AccessToken)?.value;
    console.log(accessToken) // null
    
    const accessToken2 = request.cookies.get(StorageKey.AccessToken)?.value;
    console.log(accessToken) // null
    
    // ... fetching new tokens ...

    const response = NextResponse.json(data);
    response.cookies.set(StorageKey.AccessToken, 'asdadasd');
    // Tokens will not be transferred to the main response to 
    // receiving the page and therefore are not stored in the browser
    return response;
}
```

### Describe the Bug

Cookies are missing and are not updated if a request to RouteHandler is sent from the server side

### Expected Behavior

Cookies can be accessed in the Router Handle, and data sent via the Set-Cookie response header is placed in the Set-Cookie response header to receive the page

**Comment by Fredkiss3** [comment]
It is normal, you can't store cookies serverside, only a client (browser) can store cookies, because the response that the server sends (a `set-cookie` header) is an instruction for the browser to store the cookie and this instruction is ignored on the server.

Taken from MDN (https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#creating_cookies) : 

> An HTTP cookie (web cookie, browser cookie) is a small piece of data that a server sends to a user's web browser. The browser may store the cookie and send it back to the same server with later requests.

**Comment by ndt080** [comment]
@Fredkiss3 But then it turns out that AppDir killed all the possibilities to transfer cookies to the client side when executing logic in server components.

I understand that the Set-Cookie header will be ignored on the client side, but why is the data from it not copied to the NextResponse of the given page?
Middleware can intercept responses from the Route Handler?

**Comment by Fredkiss3** [comment]
Right now, there is no direct possibility to set cookies from a server-component, you have to set the cookie either from the client by calling the `fetch(`/api/refresh-session`)` function in a client component or you could use a middleware by copying the response headers from the fetch function since cookie is just a `set-cookie` header.

```ts
// middleware.ts
import { NextRequest, NextResponse } from 'next/server';

export function middleware(request: NextRequest) {
  const response = await fetch("https://zgtbmr-3000.csb.app/api/refresh-session", {
    method: "post",
  });
  const cookiesHeaders = new Headers(response.headers);
  return NextResponse.next({
    request: {
      headers: {
         'set-cookie': cookiesHeaders.get('set-cookie')
      },
    },
  });
}
```
That's not ideal though, but i've seen in the docs that there could be a way to set the cookies on the server, from the docs at https://beta.nextjs.org/docs/api-reference/cookies#good-to-know : 

> The Next.js team at Vercel is working on adding the ability to set cookies in addition to the cookies function.

**Comment by ndt080** [comment]
@Fredkiss3 You misunderstood. I'm talking about whether it is possible in middleware to intercept the response from the Route Handler when a request is sent from the server side.

**Comment by Fredkiss3** [comment]
@ndt080 i don't think it is possible ? 🤔
Why would you want to intercept the request from the route handler specifically ?

**Comment by ndt080** [comment]
The huge problem is that I need to UPDATE the cookies so that I have a valid access token at the next request

**Comment by ndt080** [comment]
If you can't use your own authorization system with Next, it turns out that Next has turned into a framework for blog development.

**Comment by Fredkiss3** [comment]
You could try to see the approach up that I gave up there with a middleware. 
The middleware will run before your server side page code, and the middleware can set headers and cookies, after that you can do the rest of your logic (like fetching data to render) on your `page.tsx` file.
