### ISSUE TITLE
[NEXT-832] Dev Server NPM error code ENOWORKSPACES

### ISSUE THREAD

**Issue by joepetrillo** [vercel/next.js#47121]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.6.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.3
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dev server and NPM

### Link to the code that reproduces this issue

https://github.com/joepetrillo/workspace-issue

### To Reproduce

Clone the repo then `npm install` then `cd reproduction-app` then `npm run dev`

<img width="701" alt="image" src="https://user-images.githubusercontent.com/32227357/225073547-009f5219-3aa0-478c-afaf-0ae1bef23e77.png">

### Describe the Bug

**I have determined that this error happens when a nextjs (versions after 13.1.6) dev server runs in an npm workspace.**

`npm config get registry` is getting called sometime during the dev server startup and is throwing an error since it is not supported in workspaces. 

`error code ENOWORKSPACES`
`error This command does not support workspaces.`

I initially thought this could be a turborepo issue, but it is not. More details are in the issue I initially opened (linked below).

https://github.com/vercel/turbo/issues/4183

And here is a sample error log:

```
0 verbose cli /Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/bin/node /Users/jpetrillo/Library/Caches/fnm_multishells/18620_1678811038524/bin/npm
1 info using npm@9.6.1
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 0ms
9 info found workspace root at /Users/jpetrillo/Documents/Projects/workspace-bug
10 timing config:load:file:/Users/jpetrillo/Documents/Projects/workspace-bug/.npmrc Completed in 0ms
11 timing config:load:project Completed in 3ms
12 timing config:load:file:/Users/jpetrillo/.npmrc Completed in 0ms
13 timing config:load:user Completed in 0ms
14 timing config:load:file:/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/etc/npmrc Completed in 0ms
15 timing config:load:global Completed in 0ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 5ms
18 timing npm:load:configload Completed in 5ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm config get registry
22 verbose argv "config" "get" "registry"
23 timing npm:load:setTitle Completed in 5ms
24 timing config:load:flatten Completed in 1ms
25 timing npm:load:display Completed in 1ms
26 verbose logfile logs-max:10 dir:/Users/jpetrillo/.npm/_logs/2023-03-14T16_37_32_128Z-
27 verbose logfile /Users/jpetrillo/.npm/_logs/2023-03-14T16_37_32_128Z-debug-0.log
28 timing npm:load:logFile Completed in 2ms
29 timing npm:load:timers Completed in 0ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 15ms
32 timing command:config Completed in 0ms
33 verbose stack Error: This command does not support workspaces.
33 verbose stack     at Config.cmdExec (/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/npm/lib/base-command.js:123:29)
33 verbose stack     at Npm.exec (/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/npm/lib/npm.js:154:20)
33 verbose stack     at async module.exports (/Users/jpetrillo/Library/Application Support/fnm/node-versions/v18.15.0/installation/lib/node_modules/npm/lib/cli.js:134:5)
34 verbose cwd /Users/jpetrillo/Documents/Projects/workspace-bug/reproduction-app
35 verbose Darwin 22.2.0
36 verbose node v18.15.0
37 verbose npm  v9.6.1
38 error code ENOWORKSPACES
39 error This command does not support workspaces.
40 verbose exit 1
41 timing npm Completed in 21ms
42 verbose code 1
43 error A complete log of this run can be found in:
43 error     /Users/jpetrillo/.npm/_logs/2023-03-14T16_37_32_128Z-debug-0.log
```

### Expected Behavior

No error

<sub>[NEXT-832](https://linear.app/vercel/issue/NEXT-832/dev-server-npm-error-code-enoworkspaces)</sub>

**Comment by joepetrillo** [comment]
Ok so I just tested each version and it starts at exactly `13.1.7-canary.18` like you thought!

**Comment by joepetrillo** [comment]
If anyone else is able to reproduce this, it could be helpful to know if you are using any sort of node package manager or if you have any sort of `.npmrc` config. I will try to find a few others who have already reproduced this to give me their info.

**Comment by ifeltsweet** [comment]
We run into the exact same issue and we are using [n](https://github.com/tj/n).

**Comment by sunaurus** [comment]
I'm seeing the same error on next `13.2.4`.
I'm using nvm version `0.39.3` with node `v18.15.0`.

Running `npm config get registry` in my nextjs workspace does indeed produce the exact same error. It works without issues when running in the root directory that contains all the workspaces.

**Comment by tonypine** [comment]
Also happening here running next `13.2.4`, with turbo `1.4.3`, node 18 and npm `9.5.0`

**Comment by davecarlson** [comment]
Still seeing this on 
```
next 13.2.4
turbo 1.8.5
npm  9.5.0
```

**Comment by goesta** [comment]
Getting the Same error while following the Turborepo tutorial:
Not using a Version manager, installed node with homebrew.

```
31 timing npm:load Completed in 14ms
32 timing command:config Completed in 1ms
33 verbose stack Error: This command does not support workspaces.
33 verbose stack     at Config.cmdExec (/opt/homebrew/lib/node_modules/npm/lib/base-command.js:123:29)
33 verbose stack     at Npm.exec (/opt/homebrew/lib/node_modules/npm/lib/npm.js:154:20)
33 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli.js:134:5)
34 verbose cwd /Users/x/Projects/test/apps/web
35 verbose Darwin 22.3.0
36 verbose node v19.8.1
37 verbose npm  v9.6.2
38 error code ENOWORKSPACES
39 error This command does not support workspaces.
40 verbose exit 1
```

**Comment by jiby-aurum** [comment]
I get the error with 3.1.6 also on first dev server start, seemingly it tries to patch lock file

```
ready - started server on 0.0.0.0:3030, url: http://localhost:3030
info  - Loaded env from /Users/jibyjose/Projects/aurum-one/web/dashboard/.env
warn  - The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config
warn  - The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config
info  - automatically enabled Fast Refresh for 1 custom loader
warn  - Found lockfile missing swc dependencies, patching...
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jibyjose/.npm/_logs/2023-03-28T13_55_04_964Z-debug-0.log
event - compiled client and server successfully in 2s (4135 modules)
warn  - Lockfile was successfully patched, please run "npm install" to ensure @next/swc dependencies are downloaded
```

**Comment by tgaeta** [comment]
I also receive the same error when I spin up a dev server on a turborepo/next/npm project. Everything still builds and runs like @joepetrillo stated.

Error:
```shell
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in: ...
```

Package versions:
```json
"next": "13.2.4",
"react": "18.2.0",
"react-dom": "18.2.0",
"turbo": "1.8.3",
```

node/npm versions:
```shell
node --version
v18.15.0

npm --version
9.5.0
```

**Comment by tgaeta** [comment]
> npx next telemetry disable

Yep - fixed it for me!!! 🎉

**Comment by joepetrillo** [comment]
Disabling telemetry also fixes this for me!

Until they are able to fix this, I guess I’m not sharing any data 😆

**Comment by nyfever007** [comment]
this did the trick. thanks

**Comment by thany** [comment]
Ran into the same issue, disabling telemetry worked around the issue... On my pc.

Other people in my team are still experiencing this issue. So, despite positive comments, it's not _actually_ fixed yet.

**Comment by seanmc9** [comment]
> jacobpgn

Thank you so much for this - super helpful!

**Comment by lmaero** [comment]
> Hey folks! I've just seen this same error with another developer I'm working with.
> 
> We both have very similar developer environment setups, but they were seeing `ENOWORKSPACES` when running `next dev` for an npm workspace via `npm run dev -w=client`, and I was not seeing any error. This is a brand new project we weren't expecting any issues with, so we've investigated why our systems were behaving differently.
> 
> Following the comments above pointing at `npm config get registry` and recent changes to [`getRegistry`](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-registry.ts), I added some debugging to my local Next package so we could step through the code. `getRegistry` first [tries to find out which package manager](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-registry.ts#L12) is being used, so we step through [`getPkgManager`](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-pkg-manager.ts):
> 
> 1. [Check for lockfiles](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-pkg-manager.ts#L9-L17) falls through, as npm workspaces don't have their own lockfiles.
> 2. [Check for user agent](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-pkg-manager.ts#L18-L25) falls through with no matches (mine looks like `npm/9.5.0 node/v18.15.0 darwin arm64 workspaces/true`)
> 3. ⚠️ [Check to see if yarn is installed](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-pkg-manager.ts#L26-L29) passes. I have yarn installed, though I'm not using it for this project, so `getPkgManager` returns `yarn` for an npm workspace. My friend does not have yarn installed, so it falls to [`return 'npm'`](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-pkg-manager.ts#L34) by default.
> 
> Finally, in [`getRegistry`](https://github.com/vercel/next.js/blob/e35710f71f8e0f2844add1a97513a65a54a6f2a3/packages/next/src/lib/helpers/get-registry.ts#L13) my machine runs `yarn config get registry` and the other machine runs `npm config get registry`.
> 
> `yarn config get registry` does not raise this workspace error, but `npm config get registry` does 😅
> 
> My guess is that the other folks here unable to reproduce the error have either yarn or pnpm installed, whereas people seeing the error do not.
> 
> Perhaps `getRegistry` should be updated to silently swallow this error? I'd also propose a fix for `getPkgManager` to identify npm in this case, but in practice that might just mean that more people see an unhelpful error!
> 
> ## potential quick fix for users
> Run `npx next telemetry disable` to disable [Next telemetry](https://nextjs.org/telemetry). That skips this whole check so you'll see no error, and I've also found it's made `next dev` start up faster for me 🙂

Thank you!

As an alternative, if you don't want to use `npx next telemetry disable` you can set this environment variable inside your `.env` file `NEXT_TELEMETRY_DISABLED=1`

**Comment by DeepakR63** [comment]
Thank you so much...! I have faced the same issue, that can resolved with npx next telemetry disable

**Comment by uonr** [comment]
Now, even if I turn off telemetry I still get this error.

**Comment by jiteshrajoriyaa** [comment]
But this fix only run the docs not the web.
![Screenshot 2024-06-06 163537](https://github.com/vercel/next.js/assets/149613929/1fcf9752-adf1-4735-8c9b-8516ba0c0443)

**Comment by nazarepiedady** [comment]
@joepetrillo, if your problem was already solved, you can close this issue to help to clean up the issues tab,
