### ISSUE TITLE
Docs: How to handle, for instance, a search bar with server-side components

### ISSUE THREAD

**Issue by jeengbe** [vercel/next.js#47123]
### What is the improvement or update you wish to see?

Hi!

With the new app directory and server-side components, it is not clear to me how I would implement a search bar. An example in the docs would be great. Otherwise (see below), a clarification that this pattern is not possible is currently missing.

### Is there any context that might help us understand?

A search bar is merely a simple example of the general idea that I currently not sure of how to implement. Other examples are tables with sort/filter options, or more generally, any client component that fetches data depending on a state variable.

All examples in docs and blog posts require items that can uniquely be identified by the current URL only, for instance, a blog post.\
With table filtering, this is no information one would want in the URL. This becomes especially problematic when two dynamic components are shown on a page, in which case the URL need to encode both components' state.

Natively, the easiest approach is to use a server-side component as a child in a client-side component:
```tsx
"use client";

const SearchBar = () => {
	// ...
	return <>
		<input ref={queryRef} ... />
		<SearchResults query={searchQuery} />
	</>
}
```
this renders the server component `SearchResults` depending on the dynamic state variable `query`.

This pattern is sadly not possible, and the docs advise wrapping and passing the server component as a child. This would then require the server component to hold the state in order to pass it to the server-side `SearchResults`, which is also not possible.

---

Am I misunderstanding the idea of server-side components, and they are only for initially loaded data?

Would, in the above examples, dynamic fetching and rendering *need* to take place on the client?

**Comment by jeengbe** [comment]
Hi @Fredkiss3, thanks for the link to the thread! It shows precisely what I had in mind for simpler components. 

The problem with this though is that with increasing complexity of the state, the URL grows, since you essentially need to serialize it as a URL. Imagine an input component with several fields.

But with this, I assume there is no good way of doing this; passing data from client component to server component.

**Comment by Fredkiss3** [comment]
I had to do more complex form for a recent project using next-13 with appDir and here is what i had to do to simplify serializing and managing the state in the URL : 

- First to make it easier (and also working without JS), i used a `<form />` tag with a `GET` method so that i don't have to set the params for each input, it will manage itself (with onSubmit for example)
- I also used serialized the state with `URLsearchParams`, and pass it to the URL with `searchParams.toString()`, it will constructs the querystring itself.

At the end the code looked something like this : 

```tsx
'use client';
import { useSearchParams } from 'next/navigation';

function SearchForm() {
       const searchParams = useSearchParams();
       const [query, setQuery] = React.useState(searchParams.get('q'));
       const [selectedCategory, setSelectedCategory] = React.useState(searchParams.get('category'));

      return ( 
        <form
            action="/search"
            method="GET"
            onSubmit={e => {
                e.preventDefault();
                const searchParams = new URLSearchParams(
                    new FormData(e.currentTarget) as any
                );
                router.push(`/search?${searchParams.toString()}`);
            }}>
            <input
                type="text"
                name="q"
                value={query}
                onChange={e => setQuery(e.target.value)}
            />
           
            <select
                name="category"
                value={selectedCategory}
                 onChange={e => setSelectedCategory(e.target.value)}
            >
             <option value="1">Category One</option>
             <option value="2">Category Two</option>
             <option value="3">Category Three</option>
           </select>

           <button type="submit">submit</button>
       </form>
   );
}
```

The use-case in question : 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/38298743/225247551-08955631-32cc-4c76-9587-db6eb5afc6b2.png">


However this is my approach, in this one i don't search on input but rather on submit, so that i can easily convert the `formData` to searchParams.

**Comment by zacBkh** [comment]
Very interesting discussions. 
Is there any way with next 13 to : 
- Render a full list of items on the server
- Filter them client side

I don't picture how to "pass" the action from server to client and through what (useState is not available in SC...)

**Comment by szabolcsveer** [comment]
this is some fucked up shit...

**Comment by nina-alin** [comment]
Is there any way to do this without using the router ? I mean, it seems very obvious to me that using an URL to handle a simple client / server interaction is not sustainable and is not adapted to every use-case...

**Comment by leerob** [comment]
A few examples:

- https://next-admin-dash.vercel.app/
- https://demo.vercel.store/
