### ISSUE TITLE
`fetch` with `cache: no-store` or `revalidate: 0` for static page still builds a dynamic page

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#47148]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.2.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/pensive-brattain-glgb0x?file=%2Fapp%2Fpage.tsx&selection=%5B%7B%22endColumn%22%3A34%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A34%2C%22startLineNumber%22%3A10%7D%5D

### To Reproduce

- Go on codesandbox 
- Stop the dev server if it starts
- Open a new terminal a run `npm run build`

You will see the output of the build that show that the page is dynamic : 
```bash

Route (app)                                Size     First Load JS
─ λ /                                      137 B          68.4 kB
+ First Load JS shared by all              68.2 kB
  ├ chunks/455-80713d5f0013dce9.js         66.4 kB
  ├ chunks/main-app-e54152ae43526aa8.js    203 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   179 B          84.1 kB
+ First Load JS shared by all              83.9 kB
  ├ chunks/main-65424a8306558f01.js        82.1 kB
  ├ chunks/pages/_app-907dedfd0e4177db.js  192 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB
```

### Describe the Bug

In a page, next force a page to be dynamic if it find a fetch with `cache: 'no-store'` or `revalidate: false`  even when i force the page to be static with `export const dynamic = 'force-static'`.

### Expected Behavior

The page should still be generated statically and the fetch not be cached.

**Comment by rvanlaarhoven** [comment]
I guess I'm running into the same or a similar issue. I'm trying out [Prisma's Planetscale serverless driver](https://www.prisma.io/blog/serverless-database-drivers-KML1ehXORxZV#use-planetscale-with-planetscaledatabase), which uses `fetch` with a `cache: 'no-store'` [under the hood](https://github.com/planetscale/database-js/blob/7fc6089480eef285cbd143c18929fba51d4ef49a/src/index.ts#L286).

I have a static app router page, that fetches some data from the database. The initial build works fine, but recompiling a page after a revalidation results in the following error:

```
Page changed from static to dynamic at runtime /, reason: no-store fetch https://aws.connect.psdb.cloud/psdb.v1alpha1.Database/Execute /
see more here https://nextjs.org/docs/messages/app-static-to-dynamic-error
```

The mentioned docs link also does not contain any reference to a `fetch` as a possibility to cause this problem.

**Comment by MangoMarcus** [comment]
This is over a year old, can any maintainers shed any light here?

It seems to be the intended behaviour but struggling to understand how I can statically render a page using uncached data - ie. data that is fresh at build time - is this an anti-pattern or something in NextJS?

**Comment by akhrarovsaid** [comment]
I'm also experiencing this issue on Next v13.5.6

**Comment by leerob** [comment]
This sounds expected. I believe in this instance you were looking for `error`. This would prevent you from building a dynamic page:

- `'force-static'`: Force static rendering and cache the data of a layout or page by forcing [cookies()](https://nextjs.org/docs/app/api-reference/functions/cookies), [headers()](https://nextjs.org/docs/app/api-reference/functions/headers) and [useSearchParams()](https://nextjs.org/docs/app/api-reference/functions/use-search-params) to return empty values.
- `error`: Force static rendering and cache the data of a layout or page by causing an error if any components use [dynamic functions](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-functions) or uncached data.

https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
