### ISSUE TITLE
with appDir & typedRoutes enabled: next includes ANY directory starting with "app" in its name

### ISSUE THREAD

**Issue by akomm** [vercel/next.js#47151]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: Ubuntu 20.04.0 LTS Wed Mar 15 2023 13:00:14 GMT+0100
Binaries:
  Node: 16.14.2
  npm: 7.17.0
  Yarn: 1.22.19
  pnpm: 7.13.6
Relevant packages:
  next: 13.2.5-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link), TypeScript

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-y5j7qv

### To Reproduce

1. open the stackblitz URL and go to app/page.tsx (https://stackblitz.com/edit/vercel-next-js-y5j7qv)
2. type in different urls in the `Link` components and check the completion provided

### Describe the Bug

next will include all ts file pathes from any other project directory that starts with `app`, in the given stackblitz example its the folder `appx`.

### Expected Behavior

next should not include the appx folder into the typed routes

**Comment by DuCanhGH** [comment]
I'm on it :)
