### ISSUE TITLE
[NEXT-909] Image custom loader does not work with with Edge SSR.

### ISSUE THREAD

**Issue by timclark97** [vercel/next.js#47168]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.9.0
      npm: 8.19.1
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://codesandbox.io/p/github/timclark97/next-image-bug/main

### To Reproduce

1. In `next.config.js`, add the following

```js
  images: {
    loader: "custom",
    loaderFile: "./lib/imageLoader.js",
  },
  experimental: {
    runtime: "experimental-edge",
  }
```

2. Create the file `imageLoader.js` (I have placed it in a `lib` directory) with the following

```js
export default function imageLoader({ src, width, quality }) {
  return `https://via.placeholder.com/${width}`;
}
```

3. Paste the following into `pages/index.tsx`

```tsx
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Image src="photo.jpg" width={200} height={200} alt="Image" />
    </div>
  );
}
```

4. Run `npm run dev` and go to `http://localhost:3000`

### Describe the Bug

- [Use of the edge runtime for SSR has been experimentally available since version 12.2](https://nextjs.org/blog/next-12-2#edge-server-rendering-experimental).

- When using a cloud provider for image optimization instead of the built in Next.js optimization, [the docs suggest using a custom image loader](https://nextjs.org/docs/api-reference/next/image#loader-configuration).

However, combining these two features (Edge SSR and custom image loader), results in the error `Image with src "..." is missing "loader" prop` when using the `Image` component.

### Expected Behavior

When 
1. using edge SSR
2. a custom image loader defined in `next.config.js`:

The `Image` component should use the custom loader as the image loader. No `loader` prop should need to be passed to the `Image` component.

<sub>[NEXT-909](https://linear.app/vercel/issue/NEXT-909/image-custom-loader-does-not-work-with-with-edge-ssr)</sub>

**Comment by styfle** [comment]
Thanks for reporting! This will be fixed in #47659
