### ISSUE TITLE
[NEXT-847] ChunkLoadError only on deployement if using `next/dynamic` since Next `13.2.4`

### ISSUE THREAD

**Issue by Timothee-P** [vercel/next.js#47173]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.29.0
    Relevant packages:
      next: 13.2.5-canary.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Dynamic imports (next/dynamic)

### To Reproduce

I'm working on trying to reproduce this bug with the reproduction-template, but haven't been able till now.
Maybe creating a exemple with multiple chunks will make it work?

### Describe the Bug

Since upgrading next from `13.2.3` to `13.2.4`, I have a chunkLoadError on my `/app` pages, which cause hydratation error. 
This only occurs on Vercel deployment or after running `next build && next start`.
No errors/warning if using `next dev` or during the build.

Here is a screenshot of the errors: 
<img width="990" alt="Capture d’écran 2023-03-15 à 19 03 01" src="https://user-images.githubusercontent.com/33151156/225402106-821ca75a-3413-4e6e-8fe7-0b73bf48df04.png">

After investigation, the issue seam to appear if using dynamic imports via next/dynamic(or React.lazy). 
Dynamic import seem to break hydration when importing component with sub-components also used outside the import. 
No issue with a simple 'Hello world' dynamic import, or if bypassing next/dynamic on these more complexe components.

Also, in the exemple showed via the screenshot, the file `3845-003ea1aae1221d6c.js` doesn't exist in the `/.next` folder.  But `.next/static/chunks/3845.a2edb05c0b138330.js` does. 

Apparently the same error occurred for jinojacob15 ([Comment-#46989](https://github.com/vercel/next.js/issues/46989#issuecomment-1463780608)) and SuttonJack ([Comment-#46989](https://github.com/vercel/next.js/issues/46989#issuecomment-1465077047)), which seems unrelated to the initial issue. 

### Expected Behavior

No error on deployement, or at least printing an error on `next dev` or `next build`

<sub>[NEXT-847](https://linear.app/vercel/issue/NEXT-847/chunkloaderror-only-on-deployement-if-using-nextdynamic-since-next)</sub>

**Comment by jinojacob15** [comment]
Faced the same issue

**Comment by miriyas** [comment]
Same here, client-reference-manifest is pointing wrong file.

830-004c10da4a4c61af.js exist, but manifest sees like 830-s0meth1ngwr0ng.js.

When I removed all dynamic imports, problem gone.

**Comment by Nickman87** [comment]
Also have the same issue, even in the latest canary `13.3.1-canary.8`.
It is not so easy to reproduce it seems as I tried to make a codesandbox, but it just works, so there will be more at play that just a single next/dynamic import.
https://codesandbox.io/p/sandbox/jovial-bogdan-dv2vkl

I currently bypassed it by doing this (just so it does not render serverside):

```typescript
// import dynamic from "next/dynamic";
// const App = dynamic(() => import("@/admin/App"), { ssr: false });

const Admin: NextPage = () => {
  if (window) {
    const App = require("@/admin/App").default;
    return <App />;
  }

  return null;
};
```

**Comment by miriyas** [comment]
next@13.3.1-canary.14

Same

**Comment by Nickman87** [comment]
Yes, everything works as expected now, thanks!
