### ISSUE TITLE
Turbopack cannot be enabled with `experimental.fontLoaders` options in next.config.js

### ISSUE THREAD

**Issue by PassTheMayo** [vercel/next.js#47181]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/suspicious-khorana-s0e9lq?file=%2FREADME.md

### To Reproduce

1. Create a new Next.js project
2. Update Next.js to the latest version (`13.2.5-canary.4` at time of testing)
3. Enable `experimental.appDir` in `next.config.js`
4. Add default config for `experimental.fontLoaders` in `next.config.js`
5. Attempt to start dev server with Turbopack (`next dev --turbo`)

### Describe the Bug

When starting the development server, it will exit with an error saying that `experimental.fontLoaders` is not supported with Turbopack. I do not believe that this is the case, as you can still use the new `next/font` with Turbopack, you just cannot specify default settings in the `next.config.js` file. This is the complete error message that is returned from starting the development server:
```
Error: You are using configuration and/or tools that are not yet
supported by Next.js v13 with Turbopack:


- Unsupported Next.js configuration option(s) (next.config.js)
  To use Turbopack, remove the following configuration options:
    - experimental.fontLoaders
  The only supported configurations options are:
    - configFileName
    - env
    - experimental.appDir
    - experimental.serverComponentsExternalPackages
    - experimental.turbo
    - images
    - pageExtensions
    - onDemandEntries
    - rewrites
    - redirects
    - headers
    - reactStrictMode
    - swcMinify
    - transpilePackages
```

### Expected Behavior

I expected the development server to start without any errors, and for the font loader settings to be applied without intervention from Turbopack, as this has nothing to do with Turbopack itself.

### How are you deploying your application? (if relevant)

`next dev --turbo`

**Comment by balazsorban44** [comment]
`experimental.fontLoaders` has been dropped in https://github.com/vercel/next.js/pull/46886 so you can remove it from your `next.config.js`
