### ISSUE TITLE
[NEXT-833] Inconsistent behavior of @edge-runtime randomUID and native randomUID

### ISSUE THREAD

**Issue by motopods** [vercel/next.js#47189]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 19.8.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

-

### To Reproduce

crypto.randomUUID() in middleware

### Describe the Bug

The crypto.randomUUID generation should contain 4 hyphens, like, 2ec3dd93-b1e2-42ff-87b3-fe41e52bce76.

But the randomUUID function in @edge-runtime only contains 3 hyphends, like 87f3fbce-ca3d-45a0-85fde91d7ffb954d
It's format is difference with native crypto.randomUUID.

https://github.com/vercel/next.js/blob/a3dff7c8da9a49e89f63f67785a75eb7cff90169/packages/next/src/compiled/%40edge-runtime/primitives/crypto.js#L6491, 

### Expected Behavior

The randomUUID function in @edge-runtime should have same ouput format with native crypto.randomUUID

<sub>[NEXT-833](https://linear.app/vercel/issue/NEXT-833/inconsistent-behavior-of-edge-runtime-randomuid-and-native-randomuid)</sub>

**Comment by motopods** [comment]
It's upstream package bug, and be fixed. https://github.com/PeculiarVentures/webcrypto-core/commit/049cd7c9434c6171d8d8f4c83c9aa912fd510d3f.

We should update upstream packge version.

**Comment by motopods** [comment]
https://github.com/vercel/edge-runtime/issues/287

**Comment by balazsorban44** [comment]
Thanks, https://github.com/vercel/next.js/pull/46818 should address this when merged.

**Comment by keyz** [comment]
Would love to see this fixed! I was testing the edge runtime and found out that all generated UUIDs are invalid in dev. It looks like the latest version of `@edge-runtime/vm` (2.1.2) still has this bug: https://github.com/vercel/edge-runtime/issues/310

**Comment by motopods** [comment]
https://github.com/vercel/next.js/blob/173381a57239e25291116f12b522ccdc64e42624/packages/next/src/compiled/%40edge-runtime/primitives/crypto.js#L6491

The compiled file not updated, this bug is still exsiting.

**Comment by motopods** [comment]
https://github.com/vercel/next.js/blob/7e02f11e3ab24c4beef8552515d963a03cd1559f/packages/next/src/compiled/%40edge-runtime/primitives/package.json#LL1C1-L1C1

I think primitives version should be update

**Comment by motopods** [comment]
minimal version required to fix bug

webcrypto-core ^1.7.6
@peculiar/webcrypto ^1.4.2

so @edge-runtime/primitives at least 2.2.0
