### ISSUE TITLE
AppDir Robots.txt/Sitemap.xml Route Handlers Return 404 Not Found

### ISSUE THREAD

**Issue by jpgilchrist** [vercel/next.js#47198]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/upbeat-flower-gb2jhm

### To Reproduce

I created three links on the home page
1. a regular page at `app/regular/page.tsx`
2. a robots.txt with a route handler defined at `app/robots.txt/route.ts`
3. a not extension named route handler defined at `app/api/route.ts`

Notice that the regular page and the non robots.txt route handler work as expected. The regular route returns the appropriate page with html. The `/api/route.ts` handler returns the text body of "api", but the `robots.txt/route.ts` returns a 404. I've also tried this with a `sitemap.xml/route.ts` with the same result as robots. 

### Describe the Bug

It would appear there's a bug in finding / locating folders with an extension in the name. However, according to the docs, this should be possible. 

https://beta.nextjs.org/docs/routing/route-handlers#robotstxt-rssxml-and-sitemapxml

### Expected Behavior

Route Handlers with a folder that has an extension in it's name should work.

### Which browser are you using? (if relevant)

Version 111.0.5563.65 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

next dev

**Comment by Arctomachine** [comment]
I use route handler for sitemap, it works. Try adding status and content type header to response.
