### ISSUE TITLE
Inline Webpack `imports-loader` different behavior for next (dev) and preview deploy on Next v13.2.4

### ISSUE THREAD

**Issue by cdbattags** [vercel/next.js#47221]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.14.0
  npm: 9.3.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.2.5-canary.5
  eslint-config-next: 12.2.2
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue

https://github.com/triple-axle/next-imports-loader

### To Reproduce

1. Run `yarn dev` and see map
2. Deploy to Vercel and see that map tiles do not load with error global is not defined

### Describe the Bug

Using `imports-loader` with `additionalCode` seems to have broken in Next 13.

### Expected Behavior

Running the app locally should not be any different than when the app is deployed.

### Which browser are you using? (if relevant)

Chrome 111.0.5563.64

### How are you deploying your application? (if relevant)

Vercel

**Comment by cdbattags** [comment]
It looks like `imports-loader` will break anyways in the transition to turbo so we'd like to find a solution that can polyfill this global var for a specific import using SWC.

It's a bit tricky here as well because the @here/maps-api-for-javascript library is configuring a web worker.

**Comment by cdbattags** [comment]
This works correctly in production for us using Next 12.3.1.

**Comment by cdbattags** [comment]
It looks like this does not work either:

```ts
/**
 * @type {import('next').NextConfig}
 * */
const nextConfig = {
  webpack(config) {
    config.module.rules.push({
      test: require.resolve(`@here/maps-api-for-javascript`),
      use: [
        {
          loader: `imports-loader`,
          options: {
            additionalCode: `const global = undefined;`,
          },
        },
      ],
    })

    return config
  },
}
```

**Comment by balazsorban44** [comment]
Hi, I tried looking into this, but assumingly `@here/maps-api-for-javascript` is a private package/not on npm? https://npm.im/@here/maps-api-for-javascript

Can you add a reproduction that is not private?

Remember:

> Note: changes to webpack config are not covered by semver so proceed at your own risk

https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config

To me, this sounds more like a distribution issue, rather than a Next.js bug. `global` should not be used in a browser context. If you are the package author, simply use [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis), which is the web standard.

> It's a bit tricky here as well because the @here/maps-api-for-javascript library is configuring a web worker.

This is fine, Web Workers are supported

**Comment by cdbattags** [comment]
Package can be added with:

`npm config set @here:registry https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/`

Sorry!

**Comment by cdbattags** [comment]
I agree this is a distribution issue but this was working fine on Next 12. Something happened with 13 which broke being able to use this. For now, I've just implemented a package patch to work around it.

**Comment by balazsorban44** [comment]
https://github.com/vercel/next.js/issues/47221#issuecomment-1487063632

We cannot guarantee unchanged internals, so when using a custom webpack configuration, this might be an unwanted side effect.

FWIW, I tracked it down to one of the changes here: https://github.com/vercel/next.js/compare/v12.3.2-canary.29...v12.3.2-canary.30 but I don't think we can consider this as a bug.
