### ISSUE TITLE
[NEXT-883] Using compiler relay on graphql returns module (typescript)

### ISSUE THREAD

**Issue by EloB** [vercel/next.js#47239]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
Binaries:
  Node: 16.17.0
  npm: 8.15.0
  Yarn: 1.22.19
  pnpm: 7.1.0
Relevant packages:
  next: 13.2.5-canary.7
  eslint-config-next: 12.1.5
  react: 18.2.0
  react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/misty-surf-1vh56k?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A3%7D%5D

### To Reproduce

https://codesandbox.io/p/sandbox/misty-surf-1vh56k?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A16%2C%22endLineNumber%22%3A58%2C%22startColumn%22%3A16%2C%22startLineNumber%22%3A58%7D%5D

### Describe the Bug

Old issue was closed but the problem still exist: https://github.com/vercel/next.js/issues/36366#issuecomment-1472917683

Updated the codesandbox with latest versions and canary.

Problem described in short:
```ts
const pagesIndexQuery = graphql`
  query pagesIndexQuery @preloadable {
    TweetsMeta {
      count
    }
  }
`;

console.log(pagesIndexQuery);
```

Should not output `Object [Module] { default: [Getter] }`.

### Expected Behavior

Should output:
```ts
{
  fragment: {
    argumentDefinitions: [],
    kind: 'Fragment',
    metadata: null,
    name: 'pagesIndexQuery',
    selections: [ [Object] ],
    type: 'Query',
    abstractKey: null
  },
  kind: 'Request',
  operation: {
    argumentDefinitions: [],
    kind: 'Operation',
    name: 'pagesIndexQuery',
    selections: [ [Object] ]
  },
  params: {
    cacheID: 'b78830457717f1f17ab62ff54204c588',
    id: null,
    metadata: {},
    name: 'pagesIndexQuery',
    operationKind: 'query',
    text: 'query pagesIndexQuery {\n  TweetsMeta {\n    count\n  }\n}\n'
  },
  hash: '9f6c9650cdd8f7d476d27d232b8308fe'
}
```

Might be a problem with SWC but I'm not sure. According to this it should be solved but the problem remains.
https://github.com/swc-project/plugins/issues/107#event-8738527380

<sub>[NEXT-883](https://linear.app/vercel/issue/NEXT-883/using-compiler-relay-on-graphql-returns-module-typescript)</sub>

**Comment by balazsorban44** [comment]
Thanks for reporting, I had a look, and the reason that https://github.com/swc-project/plugins/issues/107#event-8738527380 did not fix this is that Next.js currently is not using that `@swc/relay-plugin` directly but has its own implementation here: https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/core/src/relay.rs

We ideally want to sync the one from the SWC project, so we will have a look at this.

You'll likely also want to set `eagerEsModules: true` for it to take effect.
