### ISSUE TITLE
[NEXT-838] create-next-app with tailwind + src directory breaks

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#47236]
```
Initializing project with template: app-tw


Aborting installation.
Unexpected error. Please report it as a bug:
 [Error: ENOENT: no such file or directory, open 'src/pages/index.tsx'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'src/pages/index.tsx'
}
```

`pnpm create next-app@canary demo` breaks with this set of options:

![cleanshot_2023-03-17_at_09.50.50_2x.png](https://uploads.linear.app/099ed59a-06c6-472f-9977-4798721bda90/24ffdb77-76c1-42e8-9946-539c9f16b559/f5717ba8-fa90-4fed-98fd-ac62a1f3344f)

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-838](https://linear.app/vercel/issue/NEXT-838/create-next-app-with-tailwind-src-directory-breaks)</sub>

**Comment by rohanA6** [comment]
is it working without src?

**Comment by JesseKoldewijn** [comment]
> is it working without src?

yes

**Comment by JesseKoldewijn** [comment]
I'm mainly kind of curious why it is looking for a index.ts file in the pages dir while the appDir option is enabled in this example. For me it seems to work just file with the same setup config as @timneutkens shows here excluding the src dir option.

**Comment by edgarasben** [comment]
Having the same issue:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/725324/225936596-caae00a7-62a6-4ace-b95b-1032108a6bd4.png">

**Comment by JesseKoldewijn** [comment]
Luckily there's a fix on its way as we can see a little earlier in this thread (open-PR above). 👍

**Comment by JesseKoldewijn** [comment]
Awesome stuff man! Keep it up! 😄 👍

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.2.5-canary.10` of Next.js please give it a try with `npx create-next-app@canary`
