### ISSUE TITLE
[NEXT-879] I can't build next.js app on android using termux

### ISSUE THREAD

**Issue by yhyadev** [vercel/next.js#47271]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: android
      Arch: arm64
      Version: #1 SMP PREEMPT Wed Feb 8 20:17:58 CST 2023
    Binaries:
      Node: 19.6.1
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: 7.29.3
    Relevant packages:
      next: 13.2.5-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.2.5-canary.5", newest: "13.2.5-canary.8".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app), Package manager (npm, pnpm, Yarn), SWC transpilation

### Link to the code that reproduces this issue

https://github.com/developers-cup/web

### To Reproduce

Open termux and type
`pnpm create next-app`

Select typescript
no app directory
no src directory

Then type
`pnpm build`

### Describe the Bug

When i typed `pnpm build`

It says

info  - Linting and checking validity of types
info  - Creating an optimized production build ..[1]    14351 segmentation fault  pnpm build

And when i type `pnpm dev`
It says

ready - started server on 0.0.0.0:3000, url: http://localhost:3000

And stop.

### Expected Behavior

I expected the build is runs normally
And the server is created like the one i built on vercel https://devcup.vercel.app/

<sub>[NEXT-879](https://linear.app/vercel/issue/NEXT-879/i-cant-build-nextjs-app-on-android-using-termux)</sub>

**Comment by pindjur** [comment]
Can you try UserLAnd android app with Ubuntu or manually install [https://wiki.termux.com/wiki/PRoot](PRoot)
