### ISSUE TITLE
[NEXT CANARY] Tailwind config file is wrong

### ISSUE THREAD

**Issue by Dun-sin** [vercel/next.js#47276]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.8
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

terminal

### To Reproduce

create a new next project using the canary cli, pick no to using the `app directory` type, after installation run `npm run dev`

This happened tailwind content was:
```
content: [
		'./pages/**/*.{js,ts,jsx,tsx}',
		'./components/**/*.{js,ts,jsx,tsx}',
		'./app/**/*.{js,ts,jsx,tsx}',
	],
```

instead of:
```
content: [
		'./pages/**/*.{js,ts,jsx,tsx}',
		'./components/**/*.{js,ts,jsx,tsx}',
		'./src/**/*.{js,ts,jsx,tsx}',
	],
```

### Describe the Bug

The tailwind styles don't work, but the global styles do

### Expected Behavior

Tailwind styling should work

**Comment by alexshyba** [comment]
Not sure if it's the same issue, but I had a similar issue if I select "yes" to "src" directory:

```
 Would you like to use `src/` directory with this project? ...  Yes
```

The page is broken:
![image](https://user-images.githubusercontent.com/900910/226126499-0d46e660-c048-4454-89ab-989de583ea90.png)

Workaround - manually add `src/` prefix to content paths in `tailwind.config.js`:

```
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/app/**/*.{js,ts,jsx,tsx}',
  ],
```

**Comment by Dun-sin** [comment]
Yes it's there same issue👍🏽

**Comment by balazsorban44** [comment]
Thanks, this is tracked in #47236. #47238 will fix this issue.

**Comment by Dun-sin** [comment]
Awesome @balazsorban44, does it also run the latest next-canary? Because when I tried to get the next info using `npx --no-install next info`, I got the error that next-canary wasn't the latest, even when I just created a new next project using the latest CLI for next using canary
