### ISSUE TITLE
Fast Reload not Working.

### ISSUE THREAD

**Issue by Akhilbisht798** [vercel/next.js#47277]
I am following Next.js documentation of `create a Next.js App`.
https://nextjs.org/learn/basics/create-nextjs-app

Completely following the tutorial there.
But when they ask you to change something and it will change automatically as soon changes are made in page 4 of the documentation i referred to I am not able to see any changes.
Maybe that is because of documentation is outdated or the npx command that we used to download the project for the tutorial is outdated.
Or there is some other problem. Can anyone Confirm this problem?

To see the changes i have stop the `npx run dev` command and re run it again.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/create-nextjs-app

**Comment by heyitsuzair** [comment]
Check whether your file name is First letter is capital or not

**Comment by 7777chaitanya** [comment]
> Check whether your file name First letter is capital or not

Hey @heyitsuzair , could you please share the link to the documentation page that says this?

**Comment by heyitsuzair** [comment]
My bad it was function* name, not file name. Check whether your "function*" name First letter is capital or not

Refer to this issue https://stackoverflow.com/questions/61033562/hot-module-reload-is-not-working-on-my-nextjs-app. 

https://nextjs.org/docs/basic-features/pages. See there, there function name's first letter is also capital lettered as I have also noticed while working with next that hot reload doesn't work if the function name's first letter of page is not capital.

**Comment by Akhilbisht798** [comment]
I think that is the reason it might be not working. I think there is not much left in this issue so, i will close this one thanku for your time.

**Comment by 7777chaitanya** [comment]
@Akhilbisht798 This might give you more clarity -> https://nextjs.org/docs/basic-features/fast-refresh
