### ISSUE TITLE
writeHead(301) in getInitialProps doesn't work with Link components

### ISSUE THREAD

**Issue by marshallku** [vercel/next.js#47307]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.12.1
  npm: 9.6.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 12.2.2
  eslint-config-next: 12.2.2
  react: 17.0.2
  react-dom: 17.0.2
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/pedantic-cartwright-9uoxiq?file=%2Fpages%2F_document.tsx&selection=%5B%7B%22endColumn%22%3A9%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A9%2C%22startLineNumber%22%3A4%7D%5D

### To Reproduce

1. Add `res.writeHead(302, URL_TO_REDIRECT)` in `getInitialProps` of page component
2. Access that link with `Link` component

### Describe the Bug

Redirect never works unless you access that page directly.

### Expected Behavior

Redirected to `URL_TO_REDIRECT`

**Comment by balazsorban44** [comment]
You forgot to end the response with `res.end()`, `writeHead` does not do that. It will just hang indefinitely.

You might want to check [Middleware](https://nextjs.org/docs/advanced-features/middleware) as a better alternative to `getInitialProps` maybe.
