### ISSUE TITLE
[NEXT-861] Link to "/" redirects to "/index.txt" when using `output: "export"`

### ISSUE THREAD

**Issue by dqn** [vercel/next.js#47334]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 18.3.0
      npm: 8.11.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.10
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/dqn/next-issue-reproduction-20230321

### To Reproduce

1. Run `yarn build`
2. Run `yarn start`
3. Open http://localhost:3000
4. Click link
5. Redirects /index.txt

### Describe the Bug

When using `output: "export"` on next.config.js, link to "/" redirects to "/index.txt".

Demo: https://next-issue-reproduction-20230321.vercel.app/

### Expected Behavior

Navigate to "/".

<sub>[NEXT-861](https://linear.app/vercel/issue/NEXT-861/link-to-redirects-to-indextxt-when-using-output-export)</sub>

**Comment by wangzishun** [comment]
I have the same problem. next@13.2.5-canary.28

**Comment by styfle** [comment]
`next start` is running a Node.js server but the purpose of `output: 'export'` is to run [without a Node.js server](https://nextjs.org/docs/advanced-features/static-html-export).

Is there a reason why you are trying to use both?

**Comment by wangzishun** [comment]
My idea is to start a service with next start that generates HTML, while the required JavaScript/CSS files for the SPA can be stored on a CDN.

![1680846645616](https://user-images.githubusercontent.com/36786594/230549744-c9097509-ac86-49d9-87ca-99fdd0a3dd6e.jpg)

**Comment by abduraufsherkulov** [comment]
Even tho it's fixed issue with static routes, the same issue for dynamic routes.

**Comment by styfle** [comment]
That sounds like you want assetPrefix, not output export. 

See https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix

**Comment by abduraufsherkulov** [comment]
@styfle but I am having no issue with assets, when I go "post/1" route, it is showing "post/1.txt" which doesn't exist. Previously I had exact same issue with static routes (e.g. /home.txt etc) but it is fixed in latest canary.

**Comment by agavrilov76** [comment]
I have the same problem

**Comment by GooseOb** [comment]
Same problem, I used nextjs github action for deploying to my gooseob.github.io

**Comment by GooseOb** [comment]
Same problem
