### ISSUE TITLE
[CLI] --tailwind flag does not create a Tailwind + Next app

### ISSUE THREAD

**Issue by albbus-stack** [vercel/next.js#47341]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:        
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

npx create-next-app@latest --ts --tailwind

### To Reproduce

1. Run `npx create-next-app@latest --ts --tailwind` or `pnpm create next-app --ts --tailwind`
2. Type project name and select desired configuration (in my case no src and no app directory)
3. The newly bootstrapped project is not containing any Tailwind, instead is the default Next app example

### Describe the Bug

I can't bootstrap a new Next app with Tailwind since the new official way (not involving --e with-tailwindcss) is cloning me the default Next example.

### Expected Behavior

The command cited above should clone a new Next app with Tailwind already set up.

**Comment by balazsorban44** [comment]
It's currently only available on `create-next-app@canary`

**Comment by albbus-stack** [comment]
Oh thank you haven't figured out there was a canary for create-next-app
