### ISSUE TITLE
Problem with new "export const metadata" + heavy F.O.U.C in production

### ISSUE THREAD

**Issue by NitrousBGC** [vercel/next.js#47350]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.10
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/NitrousBGC/nitrousdigital

### **Issue: Missing Meta Tags & F.O.U.C (Flash of Unstyled Content)**
**To Reproduce Missing Meta Tags:**

1. Create a new Next.js app.
2. In the root of the pages directory, create layout.js and page.js files.
3. Ensure both pages use Server Side Rendering (SSR).
4. Add the export const metadata object as shown in the Next.js documentation to either page.js or layout.js.
5. Deploy the app to production and test using online SEO Checkers, such as [[www.nitrousdigital.net](https://www.seobility.net/en/seocheck/)](https://www.seobility.net/en/seocheck/). The tools report missing title, description, and other meta tags.

**To Reproduce F.O.U.C:**

Visit [www.nitrousdigital.net](http://www.nitrousdigital.net/) in a web browser.
Observe the Flash of Unstyled Content (F.O.U.C) on the first page load with the preloader, and when navigating between pages such as "Terms of Service", "Cookies", "Privacy Policy", and "Join Forces".

**Additional Information:**

The issue appeared suddenly and without an obvious cause.
SCSS Modules are being used for styling.
Meta tags seem to only appear once the F.O.U.C is resolved, as they are the last elements to load inside the <head> in the browser's developer tools.

### Describe the Bug

**The issue consists of two related problems:**

**Missing Meta Tags:** Despite following the Next.js documentation and adding the export const metadata object, essential meta tags such as title, description, and keywords are not being properly rendered in a timely manner. When running the website through the online SEO checker, Seobility (https://www.seobility.net/en/seocheck/), the analysis reports that these meta tags are missing. However, the tags are actually rendered, but very late in the loading process. The delayed rendering of these meta tags can negatively impact the site's search engine performance and overall SEO score. Additionally, this delay causes Twitter cards to not display correctly when sharing the website on the platform.

**Flash of Unstyled Content (F.O.U.C):** The website experiences a noticeable F.O.U.C during the initial page load and when navigating between different pages. This results in a poor user experience as the content appears unstyled momentarily before the final styles are applied. The exact cause of the F.O.U.C is currently unknown, but it may be related to the use of SCSS Modules for styling.

### Expected Behavior

**Expected Behavior:**

**Properly Rendered Meta Tags:** Meta tags should be rendered correctly and promptly, allowing for better SEO performance and accurate display of Twitter cards when sharing the website.

**No Flash of Unstyled Content (F.O.U.C):** The website should load without any F.O.U.C, ensuring a smooth user experience with properly styled content from the start.

### Which browser are you using? (if relevant)

Version 111.0.5563.65 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

Vercel

**Comment by 7777chaitanya** [comment]
@NitrousBGC , Your link to reproduction of the issue points to a private repository.

Could you please attach a minimial public reproduction?

Please make sure to remove any unnecessary code that does not contribute to the observed issue so we can track the potential problem down more easily.

**Comment by NitrousBGC** [comment]
> @NitrousBGC , Your link to reproduction of the issue points to a private repository.
> 
> Could you please attach a _minimial public_ reproduction?
> 
> Please make sure to remove any unnecessary code that does not contribute to the observed issue so we can track the potential problem down more easily.

Hi @7777chaitanya, I've looked into this issue and discovered that on the initial load, the HTML tag contains the id __next_error__. After about one second, this id is removed and the loading continues as expected (see attached image). To isolate the problem, I removed all components inside layout.js and pushed it to production. The issue disappeared, so I added the components back one by one to determine the culprit. It turned out that an unused import, const searchParams = useSearchParams(), in the nav component was causing the issue. Upon removing this single line, everything worked as expected again (imported from next/navigation).

I am unsure how this line could break the entire website, and I believe it warrants further investigation. The problematic code is in the navigation.js component (as it was when the issue occurred). I've included the full code below for reference:

```
"use client";
import styles from "./navigation.module.scss";
import React from "react";
import Link from "next/link";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {usePathname, useSearchParams} from 'next/navigation'
const NavItem = ({ active, href, handleClick, children }) => (
  <li className={`${active === href ? styles.active : ""}`}>
    <Link href={href} onClick={() => handleClick(href)}>
      {children}
    </Link>
  </li>
);
export default function Navigation() {
  const pathname = usePathname()
  const searchParams = useSearchParams()
  const [active, setActive] =  useState(pathname);
  const [isMobile, setIsMobile] = useState(false);
  const [menuIsOpen, setMenuIsOpen] = useState(false);
  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= 1050);
    };
    if (typeof window !== "undefined") {
      window.addEventListener("resize", handleResize);
      handleResize();
      return () => window.removeEventListener("resize", handleResize);
    }
  }, []);
  useEffect(() => {
    setActive(pathname);
  }, [pathname]);
  const handleClick = (pathname) => {
    setActive(pathname);
    setMenuIsOpen(false);
    if (pathname === "/contact" && typeof document !== "undefined") {
      const contactElement = document.getElementById("contact");
      const position = contactElement.getBoundingClientRect();
      window.scrollTo({
        top: position.top + window.pageYOffset,
        behavior: "smooth",
      });
    }
  };
  const navFadeIn = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { duration: 0.3 } },
  };
  const handleCloseMenu = () => {
    setMenuIsOpen(false);
  };
  const menuItems = [
    { href: "/", label: "Home" },
    { href: "/about-us", label: "about us" },
    { href: "/projects", label: "projects" },
    { href: "/join-forces", label: "join forces" },
  ];
  return (
    <motion.div className={styles.navWrapper}>
      <motion.nav className={styles.navContainer}>
        <div className={styles.blur}></div>
        <div className={styles.mobileContact}>
          <a onClick={() => handleClick("/contact")}>
            <svg
              width="30"
              height="30"
              viewBox="0 0 30 30"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <circle cx="15" cy="15" r="15" />
              <path d="M23.4859 7.01195C23.399 6.648 22.9991 6.40036 22.6365 6.52908C22.6365 6.52908 6.92789 12.0733 6.92528 12.0752C6.68417 12.1647 6.5071 12.3947 6.49403 12.6581C6.48227 12.9109 6.63843 13.1742 6.86909 13.2814L12.9536 16.1218C12.9536 16.1218 15.9181 13.1573 15.9234 13.152C16.5114 12.564 17.4504 13.4735 16.8473 14.076L13.8776 17.0457C13.8776 17.0457 16.714 23.1237 16.7192 23.1335C16.8349 23.3557 17.061 23.4968 17.3093 23.5079C17.5791 23.5203 17.8287 23.3139 17.9254 23.0721C17.9254 23.0721 23.4663 7.37263 23.4696 7.36283C23.5108 7.24979 23.5134 7.1276 23.4859 7.01195Z" />
            </svg>
            <span>contact</span>
          </a>
        </div>
        <div className={styles.menuHamburger}>
          <span>MENU</span>
          <div
            onClick={() => {
              setMenuIsOpen(!menuIsOpen);
            }}
            className={`${styles.hamburger} ${
              menuIsOpen ? styles.hamburgerClose : ""
            }`}
          >
            <div className={styles.hamburgerLine}></div>
            <div className={styles.hamburgerLine}></div>
            <div className={styles.hamburgerLine}></div>
          </div>
        </div>
        <AnimatePresence>
          {!menuIsOpen && !isMobile && (
            <motion.ul
              variants={navFadeIn}
              initial={isMobile ? "hidden" : "visible"}
              animate="visible"
              exit="hidden"
            >
              {menuItems.map((item) => (
                <NavItem
                  key={item.href}
                  active={active}
                  href={item.href}
                  handleClick={handleClick}
                >
                  {item.label}
                </NavItem>
              ))}
              <li>
                <a onClick={() => handleClick("/contact")}>contact</a>
              </li>
            </motion.ul>
          )}
        </AnimatePresence>
        <AnimatePresence>
          {menuIsOpen && isMobile && (
            <motion.ul
              initial={{
                transform: "translate(-50%, -150%)",
                transition: {
                  duration: 0.5,
                },
              }}
              animate={{
                transform: "translate(-50%, -50%)",
                transition: {
                  duration: 0.5,
                },
              }}
              exit={{
                transform: "translate(-50%, -150%)",
                transition: {
                  duration: 0.5,
                },
              }}
            >
              {menuItems.map((item) => (
                <NavItem
                  key={item.href}
                  active={active}
                  href={item.href}
                  handleClick={handleClick}
                >
                  {item.label}
                </NavItem>
              ))}
              <li>
                <a onClick={() => handleClick("/contact")}>contact</a>
              </li>
            </motion.ul>
          )}
        </AnimatePresence>
      </motion.nav>
    </motion.div>
  );
}
```
![Screenshot 2023-03-21 174142](https://user-images.githubusercontent.com/108579761/226684512-5c0e80e0-dddd-4b0f-a03c-2d020ec12163.png)
![Screenshot 2023-03-21 174128](https://user-images.githubusercontent.com/108579761/226684519-3c351baf-5cc8-41d3-95b5-4c42afb366fc.png)
![normal behaviour after removing the line](https://user-images.githubusercontent.com/108579761/226684521-00263061-6957-4017-925d-29fbac610621.png)
![main issue](https://user-images.githubusercontent.com/108579761/226684523-a3d4030a-8e30-4322-b6d5-512229995f82.png)

Thanks a lot for offering help! I hope it gets fixed easily.

**Comment by DuCanhGH** [comment]
@NitrousBGC you are using useSearchParams, which causes the tree up to the closest Suspense to be client-rendered. Wrap the component that uses the hook with a Suspense.
For example, with a component like this:
```jsx
// app/Foo.jsx
"use client";
import { useSearchParams } from "next/navigation";

export function Foo() {
    const searchParams = useSearchParams();
    return <p>{searchParams.get("foo")</p>;
}
```
you should use it like this:
```jsx
// app/page.jsx
import { Suspense } from "react";

import { Foo } from "./foo";

export default function Page() {
    return (
        <Suspense fallback={<></>}>
            <Foo />
        </Suspense>
    );
}
```

**Comment by NitrousBGC** [comment]
> @NitrousBGC you are using useSearchParams, which causes the tree up to the closest Suspense to be client-rendered. Wrap the component that uses the hook with a Suspense.
> For example, with a component like this:
> ```jsx
> // app/Foo.jsx
> "use client";
> import { useSearchParams } from "next/navigation";
> 
> export function Foo() {
>     const searchParams = useSearchParams();
>     return <p>{searchParams.get("foo")}</p>;
> }
> ```
> you should use it like this:
> ```jsx
> // app/page.jsx
> import { Suspense } from "react";
> 
> import { Foo } from "./foo";
> 
> export default function Page() {
>     return (
>         <Suspense fallback={<>Some loading UI</>}>
>             <Foo />
>         </Suspense>
>     );
> }
> ```
> 

Hey @DuCanhGH, didn't know that unused useSearchParams could break the app. Thanks for the Suspense tip! Is this a common issue? Appreciate your help!

**Comment by DuCanhGH** [comment]
@NitrousBGC it isn't an issue, it is an intended behaviour, see [useSearchParams's docs](https://beta.nextjs.org/docs/api-reference/use-search-params) and [its source code](https://github.com/vercel/next.js/blob/3b1aaa2686ab50fa4945595d1b46122e34cbc5e7/packages/next/src/client/components/navigation.ts#L93). Glad to be of help :)
