### ISSUE TITLE
Docs: running `npm run dev` in the From React to Next.js section of the tutorial throws an error

### ISSUE THREAD

**Issue by Andreyrvs** [vercel/next.js#47361]
### What is the improvement or update you wish to see?

following the tutorial when reaching the end of the section From React to Next.js it asks to run `npm run dev` but it generates the error below

```bash

npm run dev            

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (/home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/lib/find-pages-dir.js:33:11)
    at new DevServer (/home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/server/dev/next-dev-server.js:101:44)
    at NextServer.createServer (/home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/server/next.js:104:20)
    at /home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/server/next.js:119:42
    at async NextServer.prepare (/home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/server/next.js:94:24)
    at async /home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/cli/next-dev.js:121:9

```

### Is there any context that might help us understand?

this is my `package.json` file

```json
{
  "scripts": {
      "dev": "next dev"
  },
   "dependencies": {
     "next": "^11.1.0",
     "react": "^17.0.2",
     "react-dom": "^17.0.2"
   }
 }
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs

**Comment by thejus-r** [comment]
wait aren't these old version of Next and React tho?

**Comment by Andreyrvs** [comment]
> wait aren't these old version of Next and React tho?

This part of the tutorial recommends react^17 and next^11.

**Comment by Andreyrvs** [comment]
> it looks like you are not using the pages directory, NextJs uses "pages" directory for routing, try placing your index.js file inside a folder "pages".
> 
> Your directory structure should look like
> 
> ![image](https://user-images.githubusercontent.com/63202440/226698362-ce38a520-3217-4c80-b7f8-eaad4e00c616.png)

Even putting it in the `pages` directory doesn't work.
This makes the tutorial difficult to understand.

**Comment by maxymapp** [comment]
> > it looks like you are not using the pages directory, NextJs uses "pages" directory for routing, try placing your index.js file inside a folder "pages".
> > Your directory structure should look like
> 
> Even putting it in the `pages` directory doesn't work. This makes the tutorial difficult to understand.

You seem to have missed this step from the tutorial:
`Move the index.js file to a new folder called pages (more on this later).` Search for this text again in https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs

**Comment by Andreyrvs** [comment]
> > > it looks like you are not using the pages directory, NextJs uses "pages" directory for routing, try placing your index.js file inside a folder "pages".
> > > Your directory structure should look like
> > 
> > 
> > Even putting it in the `pages` directory doesn't work. This makes the tutorial difficult to understand.
> 
> Yeah, you seem to have missed this step from the tutorial: `Move the index.js file to a new folder called pages (more on this later).` Search for this text again in https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs What's the current error after you have `index.js` in `/pages`?

Really missed that step. Even after moving to the pages directory it still generated an error. I was using node^18.15.0. When I switched to node^16.18.1 it worked. 
Thanks for the help.

**Comment by Andreyrvs** [comment]
> > > it looks like you are not using the pages directory, NextJs uses "pages" directory for routing, try placing your index.js file inside a folder "pages".
> > > Your directory structure should look like
> > 
> > 
> > Even putting it in the `pages` directory doesn't work. This makes the tutorial difficult to understand.
> 
> Yeah, you seem to have missed this step from the tutorial: `Move the index.js file to a new folder called pages (more on this later).` Search for this text again in https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs What's the current error after you have `index.js` in `/pages`?

o erro :
```bash
npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at /home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
    at /home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/compiled/webpack/bundle5.js:29861:16
    at /home/andrey/github-projects/side-projects/Nex.js/learn/node_modules/next/dist/compiled/@vercel/nft/index.js:1:307088
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0

```

**Comment by Andreyrvs** [comment]
> > > it looks like you are not using the pages directory, NextJs uses "pages" directory for routing, try placing your index.js file inside a folder "pages".
> > > Your directory structure should look like
> > 
> > 
> > Even putting it in the `pages` directory doesn't work. This makes the tutorial difficult to understand.
> 
> Yeah, you seem to have missed this step from the tutorial: `Move the index.js file to a new folder called pages (more on this later).` Search for this text again in https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs What's the current error after you have `index.js` in `/pages`?

Really missed that step. Even after moving to the pages directory it still generated an error.
I was using node^18.15.0. When I switched to node^16.18.1 it worked.
Thanks for the help.
