### ISSUE TITLE
Stripe checkout  return generates an error - destroy is not a function

### ISSUE THREAD

**Issue by chrishj59** [vercel/next.js#47393]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 16.13.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-stripe-typescript

### What browser are you using? (if relevant)

FireFox 111.0

### How are you deploying your application? (if relevant)

Running on local MacBook

### Describe the Bug

On completing the stripe test payment using the checkout form, the page returns the error .
Unhandled Runtime Error

TypeError: destroy is not a function

The browser log has:
`Uncaught TypeError: destroy is not a function
    React 15
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    EventHandlerNonNull* scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:14
    NextJS 4
    <anonymous> next-dev.js:3
    NextJS 7
[react-dom.development.js:22932](webpack://_N_E/node_modules/react-dom/cjs/react-dom.development.js?ac89)
The above error occurred in the <ClearCart> component:`

### Expected Behavior

I would expect the page to  confirm payments and clear any cart

### To Reproduce

Download  the example and setup as per the ReadMe document and  then run with `npm run dev`.
Select the checkout example with the default payment of $1000 and complete the card information.
On press the pay button, the error is returned

**Comment by heyitsuzair** [comment]
Please provide a link to the code file where you have integrated stripe

**Comment by heyitsuzair** [comment]
The problem might be having useEffect as an Async Function

Please Refer For Details.. https://medium.com/geekculture/react-uncaught-typeerror-destroy-is-not-a-function-192738a6e79b

**Comment by chrishj59** [comment]
Hi here is the gitHub code. I am using the example as  with the exception of using my stripe account ids
[code](https://github.com/chrishj59/stripe_checkout_47393).
Could suggest that the example code is corrected if it is un the useEffect code

**Comment by heyitsuzair** [comment]
Try upgrading every package to the latest version. This might help

**Comment by heyitsuzair** [comment]
Ok. I found this as bug and will create new pull request

**Comment by chrishj59** [comment]
I have updated all packages to the latest version.  The issue still persists.
The updated code has been uploaded to [GitHub repo](https://github.com/chrishj59/stripe_checkout_47393)
