### ISSUE TITLE
App dir internationalization in parallel with pages

### ISSUE THREAD

**Issue by joaogarin** [vercel/next.js#47430]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.5
      pnpm: 7.27.0
    Relevant packages:
      next: 13.2.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/joaogarin/nextjs-i18n-repro

### To Reproduce

1 ) Run git clone on the reproduction repostitory
2 ) run npm install
3 ) run npm run dev and go to https://localhost/test

### Describe the Bug

There is some redirect happening when using a [lang] directory together with existing internationalized app (using the i18n config in next.config.js)

The page gets redirected to a URL without http://localhost:3000 resulting in a broken page. In vercel the deployment also fails (I think maybe its possible to see as its linked in the repo)

### Expected Behavior

Expect to be able to use the app dir (with i18n) together with an existing pages directory already working and using i18n

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
Looks like there were some issues with the middleware logic, here is a simplified version which seems to work right for both pages and app:

```ts
// middleware.ts
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

import { i18n } from "./i18n-config";

import { match as matchLocale } from "@formatjs/intl-localematcher";
import Negotiator from "negotiator";

function getLocale(headers: Negotiator.Headers) {
  const languages = new Negotiator({ headers }).languages();
  return matchLocale(languages, [...i18n.locales], i18n.defaultLocale);
}

export function middleware(req: NextRequest) {
  // using req.url instead of `req.nextUrl`, which strips away the locale from pathname 
  const { pathname } = new URL(req.url);
  const localeInPathname = pathname.slice(1, 3) as any
  if (!i18n.locales.includes(localeInPathname)) {
    const locale = getLocale(Object.fromEntries(req.headers));
    req.nextUrl.pathname = `/${locale}${pathname}`;
    return NextResponse.redirect(req.nextUrl);
  }
}

export const config = {
  // Matcher ignoring `/_next/` and `/api/`
  matcher: ["/((?!api|_next/static|_next/image|favicon.ico).*)"],
};
```

```ts
// next.config.js
//...
  i18n: {
    locales: ["default", "en", "de", "cs"],
    defaultLocale: "default",
    localeDetection: false,
  },
```

```ts
// get-dictionary.ts
//...
export const getDictionary = async (locale: Locale) =>
  // To handle when the locale is "default", we fall back to English.
  dictionaries[locale]?.() ?? dictionaries.en();
```


This is partially based on the documentation from https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale
