### ISSUE TITLE
[NEXT-889] Unable to Test Server Components in Next.js 13 App Dir

### ISSUE THREAD

**Issue by defrex** [vercel/next.js#47448]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 19.7.0
  npm: 9.5.0
  Yarn: N/A
  pnpm: N/A
Relevant packages:
  next: 13.2.5-canary.14
  eslint-config-next: 13.2.4
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Jest (next/jest)

### Link to the code that reproduces this issue

https://github.com/defrex/next13-jest-server-bug

### To Reproduce

In the linked repo, `npm i && npx jest`

The repo is just a very basic `create-next-app` project with Jest installed, using the `next/jest` config.

### Describe the Bug

Any test of a server-only component (or anything with a server-only component in it's import path) fails to load.

Like so,

```
 FAIL  src/app/layout.test.ts
  ● Test suite failed to run


      × NEXT_RSC_ERR_CLIENT_IMPORT: server-only
       ╭─[/Users/defrex/code/broken-jest-example/src/app/layout.tsx:1:1]
     1 │ import "./globals.css";
     2 │ import "server-only";
       · ─────────────────────
     3 │
     4 │ export async function getLayoutData() {
     5 │   return {
       ╰────

      3 | describe("Layout getData", () => {
      4 |   it("should return data", async () => {
    > 5 |     const data = await getLayoutData();
        |                 ^
      6 |     expect(data.isData).toBeTruthy();
      7 |   });
      8 | });

      at Object.transformSync (node_modules/next/src/build/swc/index.ts:376:25)
      at Object.<anonymous> (src/app/layout.test.ts:5:17)
```

### Expected Behavior

I would expect these files/components to be testable. Or at very least, to be able to import non-component code from related files for the sake of testing.

<sub>[NEXT-889](https://linear.app/vercel/issue/NEXT-889/unable-to-test-server-components-in-nextjs-13-app-dir)</sub>

**Comment by balazsorban44** [comment]
Related to #47299

**Comment by jordanmcdougall** [comment]
I am also experiencing the same issue as @defrex  but instead of importing `server-only` I am importing `next/headers` in a page.tsx file that is in the app dir.

Testing is raising the same `NEXT_RSC_ERR_CLIENT_IMPORT` error as above.

Any guidance on how to fix would be much appreciated!!

**Comment by red2678** [comment]
Same issue. Would love to start testing :) Or would I......

**Comment by roelandmoors** [comment]
> Related to #47299

In that issue the explanation is that `@testing-library/react` simulates a browser, but I get that error also without that library. I was trying to test some logic that doesn't uses React and should always run on the server.

**Comment by philwolstenholme** [comment]
It's more that `jsdom` simulates a browser (a client), I think. That must trigger some Next.js or React code that checks to see if a React Sever Component is being used outside of a Server context.

The NEXT-889 issue tag in the issue title means that the Next team are tracking this internally, so that's a good sign.

I think one solution will be to have two Jest profiles, one for client-side code and one for server-side code. With two profiles you can have two different environments, `jsdom` for the client and then Node for the server.

**Comment by roelandmoors** [comment]
A seperate profile is a good idea. Do you have an example that works with Nextjs 13 maybe?

**Comment by philwolstenholme** [comment]
> A seperate profile is a good idea. Do you have an example that works with Nextjs 13 maybe?

No, sorry, not yet.

My team was about to start looking into it but then I saw that Vercel had updated this ticket with a Linear/Jira ticket reference, so we put the idea to the side and will wait for an official docs update.

If you'd like an example of using two Jest profiles then I think the 'Next Right Now' repo has an example of it. I'm on my phone at the moment but will post this comment then go and find and share a URL on my laptop…

**Comment by philwolstenholme** [comment]
Ah, I was wrong, it was Blitz, not 'Next Right Now': https://github.com/blitz-js/blitz/blob/canary/packages/blitz/jest-preset.js#L50-L82

Someone has also shared an example of using ~~profiles~~ projects (I got the name wrong in my earlier comment) https://github.com/vercel/next.js/discussions/12411#discussioncomment-5472457

**Comment by roelandmoors** [comment]
That github comment is really nice, but even in a Node environment I get the same error. 
Below is the config I used. Without `import "server-only";` the tests are passing.

```javascript
// jest.config.mjs
import nextJest from 'next/jest.js'

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: './',
})

const clientTestConfig = {
  displayName: "client",
  testMatch: ["/**/*.clienttest.[jt]s?(x)"],
  testEnvironment: "jest-environment-jsdom",
};

const serverTestConfig = {
  displayName: "server",
  testMatch: ["/**/*.servertest.[jt]s?(x)"],
  testEnvironment: "node",
};

// Add any custom config to be passed to Jest
/** @type {import('jest').Config} */
const config = {
  // Add more setup options before each test is run
  projects: [await createJestConfig(clientTestConfig)(), await createJestConfig(serverTestConfig)()],
};

export default config;
```

**Comment by philwolstenholme** [comment]
Ah yeah, `server-only` does some stuff that won't be affected by just the `jsdom` vs `node` environment switch.

https://github.com/facebook/jest/issues/13967 has some info on this. There are two things we can try (I've not tried these yet, so not sure if they actually work):

Mocking `server-only`, potentially?: https://github.com/facebook/jest/issues/13967#issuecomment-1468987614

Someone else pointed out how `server-only` works (`package.json` exports, with the error being thrown only if the `react-server` export is _not_ used), and suggested how to override what export is used in Jest: https://github.com/facebook/jest/issues/13967#issuecomment-1493284963

**Comment by bramarcade** [comment]
Confirming this also affects me. The 'Testing' section of the app beta docs is still greyed out / unpublished, so hopefully a solution is in the pipes.

**Comment by jviall** [comment]
@feugy This problem still seems to be occurring when using vitest--what is the vitest equivalent of configuring server-only code for testing using `/** @jest-environment node */`?

**Comment by nickmccurdy** [comment]
That should also work with Vitest (along with `@vitest-environment`).

**Comment by leerob** [comment]
Hey everyone, we have a [fix](https://github.com/vercel/next.js/pull/54891) landed on the latest [canary](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.16) (`v13.4.20-canary.16`). Please let us know if it's working for y'all 🙏 Appreciate your patience.
