### ISSUE TITLE
next/image not showing the whole image on IOS

### ISSUE THREAD

**Issue by westernal** [vercel/next.js#47459]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 17.6.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.15
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

GitHub: https://github.com/westernal/Portfolio 
Website: https://alinavidi.dev/

### To Reproduce

Click on burger menu and go to projects.

**The code**
` <Image
          src={project.image.website}
          width={300}
          height={150}
          id="project-image"
          alt={"Westernal's website"}
        />`

**Test on Windows**
![mobile](https://user-images.githubusercontent.com/79543272/227376019-88eabad4-0fc9-4d14-a668-f31629e10783.png)

**Actual result on IOS**
![unnamed](https://user-images.githubusercontent.com/79543272/227375999-bd4fd57d-4e96-4180-b4f7-64adbd8eacc2.png)

**The image**
![westernal-web](https://user-images.githubusercontent.com/79543272/227376403-6f7207e6-350e-4efc-bf6a-955f3e2850d7.svg)

### Describe the Bug

I'm using Next.js to build my portfolio but there is a problem, when I tested it on chrome with my laptop everything is perfect but when I deployed it the image was broken. I tried fill option and object-fit but nothing worked.

I've never had this issue before with next/images. I'll be happy if you help me understand what happened.

### Expected Behavior

Showing the whole image as the docs says: 

> The default image fit behavior will stretch the image to fit the container.

but its not stretching.

### Which browser are you using? (if relevant)

Safari and Chrome on IOS 16.3.1

### How are you deploying your application? (if relevant)

Vercel

**Comment by heyitsuzair** [comment]
Try using css property "object-fit:cover"

**Comment by westernal** [comment]
> Try using css property "object-fit:cover"

I did and it didn't work.

**Comment by westernal** [comment]
I just saw this issue's text on IOS and saw this:
![D3034A52-4717-4B80-A094-B87A7BB24503](https://user-images.githubusercontent.com/79543272/227448143-6e9f49a1-37ae-4048-bb67-e5eb4b1f3a6f.png)

I think the problem is with the image itself.
