### ISSUE TITLE
Docs: code out of sync

### ISSUE THREAD

**Issue by SumitBando** [vercel/next.js#47479]
### What is the improvement or update you wish to see?

The page at https://nextjs.org/learn/basics/navigate-between-pages/link-component refers to
\<h1 className="title">
However, checked out code now is:
\<h1 className={styles.title}>

### Is there any context that might help us understand?

Doc older than code?

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/navigate-between-pages/link-component

**Comment by manovotny** [comment]
@SumitBando thanks for reporting this. We just deployed a fix for it now. 😊
