### ISSUE TITLE
Next-link scrolling layout.tsx "children" into view no matter what

### ISSUE THREAD

**Issue by this-Cunningham** [vercel/next.js#47475]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: 1.22.10
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.15
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/this-Cunningham/Next-link-scroll-bug-repro

### To Reproduce

- Anytime using next-link to navigate to a page within a `layout.tsx`... if the layout's rendered `{ children }` HTML container is below the viewport, the children are scrolled into view, all the way up to scroll position zero if there is enough content to scroll that far... 

- if even a tiny, tiny sliver of the layout's rendered `{children}` container are above the viewport on initial navigation (even by 1px), there is no scrolling (desired behavior).... 

in the provided repro repo -- you can play around with the viewport height and if you shrink the viewport height enough and start using the buttons to navigate you will notice this scrolling behavior

if you increase the viewport height enough so the content at the bottom is above the fold/in the initial view upon navigating... there is zero scrolling

### Describe the Bug

When using next-link to navigate to a page where a layout.tsx's `{children}` container is below the viewport/below the fold, the application scrolls until the "children" html container is at scroll position zero if possible, otherwise it is scrolled as high up as possible

### Expected Behavior

Expected behavior is for there to be zero scrolling when initially navigating to any page unless there is a `#` in the url.

### Which browser are you using? (if relevant)

Chrome - Version 111.0.5563.64 (Official Build) (x86_64) ... Safari - Version 16.3 (18614.4.6.1.6) and latest firefox

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1393](https://linear.app/vercel/issue/NEXT-1393/next-link-scrolling-layouttsx-children-into-view-no-matter-what)</sub>

**Comment by DaviLhlapak** [comment]
I have the same problem reported but without using the layout on the subpage.

When I use `{ children }` within the layout and on the page the first element has the "fixed" position, the behavior of the scroll on the page is to scroll to bottom, if the first element is something other than "fixed" like "static" the scroll works as it should be. However, this only happens when the link to the page with the "fixed" element is located far down on the source page.

Try with this code:
```js
/* ...src/app/page.tsx */
export default function Home() {
  return (
    <main className={styles.main}>
      <Link href='/blog' style={{ height: '100px', width: '100px', backgroundColor: 'green', marginTop: '5000px'}}>
        Click to go To Blog
      </Link>
    </main>
  )
}
```
``Delete Layout.tsx in Blog Folder``
![image](https://user-images.githubusercontent.com/50346240/227551560-ffa3290b-8004-4695-b82c-06a4ad211c40.png)
```js
/* ...src/app/blog/page.tsx */
export default function Page() {
  return (
    <>
      <div style={{ position: 'fixed', top: 0, left: 0 }}>
        Menu Fixed
      </div>
      <div style={{ marginTop: '100px', height: '100vh', color: 'yellow' }}>
        Contet
      </div>
      <div style={{ marginTop: '500px' }}>
        Footer
      </div>
    </>
  )
}
```
The result:
![chrome_YVfDGFKxYd](https://user-images.githubusercontent.com/50346240/227552813-241ae931-176c-4b13-9399-6443b9b979f7.gif)

I expected that when clicking on a link located in a footer, for example, the user would be taken to the top of the content and not to the footer of the page again. This causes the user to have to scroll again to the top.

(If I change the first element to something static, the bug doesn't occur. However, in my use case, the first element is a fixed menu.)

**Comment by schimi-dev** [comment]
Same here

**Comment by AlexSapoznikov** [comment]
Can confirm from my side as well.

**Comment by bdlowery** [comment]
This is NOT fixed. Just make it like how the web has worked for the past 20 years... click on a link, get taken to the top of the page. I don't need my 50 year old client telling me that the 'site is broken' because the website 'doesn't work when you click a link'.

**Comment by sin-ko** [comment]
I am seeing the same problem as well

**Comment by singleseeker** [comment]
I hope this can be fixed ASAP. I've got the same issue.

**Comment by swa-legste** [comment]
Same problem here. Should we open a new bug or rename the issue with respect to `sticky` to emphasis on the condition?

**Comment by h2toan** [comment]
I am expecting an update from the team to fix this issue. I have also encountered this issue.

**Comment by leandronorcio** [comment]
Same here.
1) Pushing a page does not reset the scroll of the layout.
2) Going back to the previous page resets the scroll of the layout.

Both these are obviously unexpected behavior.  A user navigating to another page expects to see the top part of the page.

https://github.com/vercel/next.js/assets/32889996/b45af659-d0cc-42ac-babc-e10d8e50d8bc

**Comment by holahoon** [comment]
I seems like if I wrap `page.tsx` with `layout.tsx` in `app` directory causes this issue.
And it also randomly starts from top

**Comment by holahoon** [comment]
Same. Tried **not** using layout component but the problem still persists. Weird... 🙁
