### ISSUE TITLE
fetch API caching when searchParams is used

### ISSUE THREAD

**Issue by smitbarmase** [vercel/next.js#47515]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.5-canary.16
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/smitbarmase/dumb

### To Reproduce

4 days ago @timneutkens made few fixes #47312. This issue seems to related to that.

I have social page which fetches all posts using `searchParams` that is, if url is `/social?page=1` it make fetch request to `/posts/1` and if url is `/social?page=2` it make fetch request to `/posts/2` to get all posts for that paginated page.

### Describe the Bug

Now, if we use `next: { revalidate: 30 }` on this fetch request, things starts to break. It works for `/social?page=1` but, on requesting `/social?page=2` for some reason this fetch request gives different output. Looks like output is from cache of different request.

```
https://my-api-here.com/posts/2
{
  id: 2,
  title: 'Second Post',
  content: 'This is the content of the second post.'
}
TypeError: posts.map is not a function
    at PageWidget (/var/task/.next/server/app/social/page.js:280:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

One thing to note in above output is, `/posts/2` API returns array of posts which should be posts with ids `4, 5, 6` but in this case, it is giving output which is of manually fetching post `2` in my `slug` route. I think cache is getting wrongly mapped.

### Expected Behavior

It should show content on page 2, which are three posts with ids `4, 5, 6`. Instead, this error comes up `Application error: a client-side exception has occurred (see the browser console for more information).
Digest: 1144457952`

### Which browser are you using? (if relevant)

Arc 0.95.0 Chromium Engine Version 111.0.5563.110

### How are you deploying your application? (if relevant)

Vercel on production

**Comment by timneutkens** [comment]
Can you provide a reproduction as the provided repository is not available.

**Comment by smitbarmase** [comment]
I made it public now. You can take a look.

I also noticed something strange. This is my server code. Notice `post` ids here. I guess this is failing due to some problem with caching. It is considering `/posts/2` which to get all posts on page 2, and `/post/2` which is post with id 2, the same.

```
const express = require('express');
const app = express();

// Dummy data for the posts
const posts = [
  { id: 1, title: 'First Post', content: 'is the content of the first post.' },
  { id: 2, title: 'Second diff Post', content: 'is the content of the second post.' },
  { id: 3, title: 'Third Post', content: 'is the content of the third post.' },
  { id: 4, title: 'Fourth Post', content: 'This is the content of the first post.' },
  { id: 5, title: 'Five Post', content: 'This is the content of the second post.' },
  { id: 6, title: 'Six Post', content: 'This is the content of the third post.' },
];

// API to get a list of all posts
app.get('/posts/:page', (req, res) => {
  const page = req.params.page ?? 1;
  console.log(page);
  console.log("posts fetched\n");
  
  let postList = posts.map((post) => {
    return { id: post.id, title: post.title };
  });
  if (page == 1) {
    postList = postList.slice(0, 3);
  } else if (page == 2) {
    postList = postList.slice(3);
  } else {
    postList = undefined;
  }

  if (postList) {
    res.json(postList);
  } else {
    res.status(404).json({error: 'Page not found'});
  }
});

// API to get a specific post by ID
app.get('/post/:id', (req, res) => {
  console.log(req.params.id);
  console.log("post incoming\n");
  const postId = parseInt(req.params.id);
  const post = posts.find((p) => p.id === postId);
  if (post) {
    res.json(post);
  } else {
    res.status(404).json({ error: 'Post not found' });
  }
});

// Start the server
app.listen(4000, () => {
  console.log('Server is running on port 4000');
});

```

Below server code works. Because I changed `post` ids to some gibberish now.

After
```js
const express = require('express');
const app = express();

// Dummy data for the posts
const posts = [
  { id: 'abc', title: 'First Post', content: 'is the content of the first post.' },
  { id: 'def', title: 'Second diff Post', content: 'is the content of the second post.' },
  { id: 'ghi', title: 'Third Post', content: 'is the content of the third post.' },
  { id: 'jkl', title: 'Fourth Post', content: 'This is the content of the first post.' },
  { id: 'mno', title: 'Five Post', content: 'This is the content of the second post.' },
  { id: 'pqr', title: 'Six Post', content: 'This is the content of the third post.' },
];

// API to get a list of all posts
app.get('/posts/:page', (req, res) => {
  const page = req.params.page ?? 1;
  console.log(page);
  console.log("posts fetched\n");
  
  let postList = posts.map((post) => {
    return { id: post.id, title: post.title };
  });
  if (page == 1) {
    postList = postList.slice(0, 3);
  } else if (page == 2) {
    postList = postList.slice(3);
  } else {
    postList = undefined;
  }

  if (postList) {
    res.json(postList);
  } else {
    res.status(404).json({error: 'Page not found'});
  }
});

// API to get a specific post by ID
app.get('/post/:id', (req, res) => {
  console.log(req.params.id);
  console.log("post incoming\n");
  const postId = req.params.id;
  const post = posts.find((p) => p.id === postId);
  if (post) {
    res.json(post);
  } else {
    res.status(404).json({ error: 'Post not found' });
  }
});

// Start the server
app.listen(4000, () => {
  console.log('Server is running on port 4000');
});

```

If I can help you more to debug this let me know.

**Comment by smitbarmase** [comment]
@timneutkens I'm not able to reproduce it again. Looks like problem in vercel caching. Let's close this for now.
