### ISSUE TITLE
npm run dev suddenly stops at the beginning with no error logs

### ISSUE THREAD

**Issue by bejenaru-victor** [vercel/next.js#47510]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: ia32
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.16
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

npm run dev

### To Reproduce

![Screenshot_10](https://user-images.githubusercontent.com/20127910/227639175-12fdf451-6204-41b2-9dd4-944fcecf8e0f.jpg)

### Describe the Bug

After following the instructions for the installation of nextjs with the command `npx create-next-app@latest` and entering in the folder created, I'm running npm run dev to run the local server. After it builds and is rendering as 'ready', it suddenly closes with no additional information. I've tried to debug and search what would be the problem, but after hours, couldn't find any helpful information

### Expected Behavior

run properly as the docs are advising

### Which browser are you using? (if relevant)

firefox

### How are you deploying your application? (if relevant)

Windows terminal

**Comment by JesseKoldewijn** [comment]
Hey man, could you provide me with a reproduction repo by chance so I can test your issue with the exact project you got there? Tried to reproduce it by following the same steps as you did but no dice on this behavior.

**Comment by razier** [comment]
Been having this issue for awhile now, weirdly I noticed that it is working on my other pc.

Further digging via node -p "process.arch" made me realized I am somehow running 32 bit of node, uninstalling the 32bit node and reinstall with the 64bit msi (node-v18.15.0-x64.msi) and it runs successfully.

Possible that the compiler (next-swc is on 64bit only and does not support running it via 32bit node).

**Comment by bejenaru-victor** [comment]
@razier Thank you very much. It worked after uninstalling node and reinstalling the 64 bit version. You restored my hope in the framework :)

**Comment by JesseKoldewijn** [comment]
Tip in the future, use nvm or volta for managing node imstalls. This makes sure you get the valid version. 

You can install volta from volta.sh or via winget by the following command:
```
winget install Volta.Volta
```
