### ISSUE TITLE
Metadata elements appearing in the body after refreshing in Next.js if loading.tsx is present

### ISSUE THREAD

**Issue by eyenalxai** [vercel/next.js#47522]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103
Binaries:
  Node: 19.3.0
  npm: 9.2.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.2.5-canary.16
  eslint-config-next: 13.2.4
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/eyenalxai/metadata/tree/yes-loading-no-meta

### To Reproduce

1. Clone https://github.com/eyenalxai/metadata/tree/yes-loading-no-meta
2. Run the Next.js application and navigate to http://0.0.0.0:3000/
3. Click on the link to http://0.0.0.0:3000/person/1. Observe that the metadata appears in the `<head>` section.
4. Refresh the page and inspect the HTML source. Notice that the metadata elements are now in the `<body>`

Demo: https://metadata-git-yes-loading-no-meta-wobtelhid.vercel.app/

### Describe the Bug

When navigating to a page from the index page, the metadata is correctly placed in the `<head>` section. However, after refreshing the page, the metadata elements appear in the `<body>` instead.

The issue seems to be related to the presence of the loading.tsx file in the /app directory. A repository without the loading.tsx file does not exhibit the same issue:

Demo without the bug: https://metadata-git-no-loading-yes-meta-wobtelhid.vercel.app/
Source code without the bug: https://github.com/eyenalxai/metadata/tree/no-loading-yes-meta

### Expected Behavior

The metadata elements should always be placed in the `<head>` section.

### Which browser are you using? (if relevant)

Safari 16.2 (18614.3.7.1.5), Chrome 111.0.5563.64

### How are you deploying your application? (if relevant)

next start, Vercel

**Comment by JesseKoldewijn** [comment]
Weirdly enough I don't run into this issue on my following repo:
https://github.com/ShiftCodeEU/shiftcode.eu
Which run on the following domain:
https://shiftcode.eu

**Comment by eyenalxai** [comment]
> Weirdly enough I don't run into this issue on my following repo:
> https://github.com/ShiftCodeEU/shiftcode.eu
> Which run on the following domain:
> https://shiftcode.eu

I was able to reproduce by adding src/app/loading.tsx file to your code.
<img width="491" alt="Screenshot 2023-03-25 at 21 23 11" src="https://user-images.githubusercontent.com/40147710/227732205-c0d5dabc-f0eb-4f99-a56a-5aeb1d5e448b.png">

**Comment by JesseKoldewijn** [comment]
Odd, indeed a weird issue with the loading.tsx file flow.

**Comment by icyJoseph** [comment]
https://github.com/vercel/next.js/issues/46738
