### ISSUE TITLE
Docs: Some sections are hard to read in new nextjs beta docs.

### ISSUE THREAD

**Issue by officialrajdeepsingh** [vercel/next.js#47521]
### What is the improvement or update you wish to see?

Nextjs team change the highlight color so people read it. 

### Is there any context that might help us understand?

The background color is so dense when many comments on the same section in nextjs beta docs. It is not read clearly. To understand better, you checkout attach images. 

![hardtoread](https://user-images.githubusercontent.com/32416397/227714934-bdc76c2f-5577-4c89-b264-c57783b1083c.png)

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/use-router

**Comment by balazsorban44** [comment]
Thanks, I forwarded this feedback to the team working on the Preview comments feature.

This is however neither related to the Next.js package nor the Next.js documentation directly, so I'm closing the issue.

**Comment by Willem-Jaap** [comment]
You can use `ctrl + .` to toggle the comments

**Comment by leerob** [comment]
We've made this better 🙏
