### ISSUE TITLE
Tailwind config file is wrong

### ISSUE THREAD

**Issue by iprotoni** [vercel/next.js#47551]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: Ubuntu
      Arch: x64
      Version: 22.04
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.8
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

terminal

### To Reproduce

create a new next project using the canary cli, pick no to using the app directory type, after installation run npm run dev

This happened tailwind content was:

content: [
		'./pages/**/*.{js,ts,jsx,tsx}',
		'./components/**/*.{js,ts,jsx,tsx}',
		'./app/**/*.{js,ts,jsx,tsx}',
	],
	
	instead of:

content: [
		'./pages/**/*.{js,ts,jsx,tsx}',
		'./components/**/*.{js,ts,jsx,tsx}',
		'./src/**/*.{js,ts,jsx,tsx}',
	],

### Describe the Bug

The tailwind custom styles don't work, but the global styles do.

### Expected Behavior

The tailwind styling should working as expected.

**Comment by ijjk** [comment]
Hi, this appears to be working properly in the latest version of `create-next-app`, note to use the latest version you must run the command as `npx create-next-app@canary` or `pnpm create next-app@canary`.
