### ISSUE TITLE
App with middleware is slow

### ISSUE THREAD

**Issue by markcalendario** [vercel/next.js#47566]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.18.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/markcalendario/next-js-reproduction-template-middleware-issue

### To Reproduce

Create a `middleware.js` file and run an app to dev mode. Open a browser and try to reload a page. Expect a heavy reload latency issue.

### Describe the Bug

When I reload the localhost:3000 it takes 3-5 seconds to load if the `middleware.js` is present (only in `npm run dev`).

### Expected Behavior

The app should load instantly even the `middleware.js` is present.

**Comment by JesseKoldewijn** [comment]
Sounds like a node16 issue, just ran your repo on my end and it only took between 1.5 and 2.8 sec to reload (still a touch long tbh, but its the pages dir and not the appDir).

```
 Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro <- Win 11 Pro (not sure why it detects windows 10)
    Binaries:
      Node: 16.18.0
      pnpm: 8.1.0
    Relevant packages:
      next: 13.2.5-canary.21
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by markcalendario** [comment]
Thanks. I upgraded the Node to 18.15.0, it improves. 2.90s - 3.50 in my case.
