### ISSUE TITLE
[NEXT-903] sitemap.xml not generated

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#47574]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Vercel

next12.2.5@canary-19
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/juliusmarminge/jumr.dev

### To Reproduce

Follows @leerob’s tweet https://twitter.com/leeerob/status/1639639575843729409?s=46&t=Uy_Hg1WWwsYDe1YleBLsaA to setup sitemap & robot. (Source: https://github.com/leerob/leerob.io/blob/main/app/sitemap.ts).

### Describe the Bug

unfortunatly, no sitemap seems to be om generated: https://jumr.dev/sitemap.xml

### Expected Behavior

Route above not to 404, see https://leerob.io/sitemap.xml

### How are you deploying your application? (if relevant)

Vercel

**Comment by leerob** [comment]
Could you try without using the `src/` directory? That's my first guess looking at this. Thanks for opening!

**Comment by juliusmarminge** [comment]
> Could you try without using the `src/` directory? That's my first guess looking at this. Thanks for opening!

Still 404-ing after refactoring not to use `src/`: https://github.com/juliusmarminge/jumr.dev/blob/main/app/sitemap.ts

**Comment by huozhi** [comment]
You're ignoring `ts` in `pageExension` in your next config but using ts as file extension for robots and sitemap routes. Changing the file extension to tsx or add ts into `pageExtension` can fix it

**Comment by juliusmarminge** [comment]
> You're ignoring `ts` in `pageExension` in your next config but using ts as file extension for robots and sitemap routes. Changing the file extension to tsx or add ts into `pageExtension` can fix it

Aaaahh, silly me. Sorry for the confusion...
