### ISSUE TITLE
[NEXT-983] `app` router CSS handling seems incompatible with CSS Cascade Layers - no way to guarantee that CSS that defines layers can be loaded before any usage of the CSS layers

### ISSUE THREAD

**Issue by philwolstenholme** [vercel/next.js#47585]
(I'm not 100% sure if this is a Next issue or a RSC/React core issue) 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
See https://codesandbox.io/p/sandbox/next-js-css-cascade-layers-hkqesn
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/next-js-css-cascade-layers-hkqesn

### To Reproduce

1. Open the Codesandbox https://codesandbox.io/p/sandbox/next-js-css-cascade-layers-hkqesn
2. Note that the disabled buttons are not all grey, the 'theme' colour is being applied instead of the 'state' colour
3. Use devtools to re-order the CSS files in the `<head>` and note that the button background colours change. Now the 'state' styling has taken over the background colour – this is what we want!

![image](https://user-images.githubusercontent.com/6339853/228085458-c4d9abca-dca0-480a-ac3d-1ce5ab8383bc.png)

![image](https://user-images.githubusercontent.com/6339853/228085526-1da9e10f-b0c1-43e0-884d-7393a2d06b5b.png)

### Describe the Bug

[CSS Cascade Layers](https://css-tricks.com/css-cascade-layers/) are an exciting feature in CSS with [strong browser support](https://caniuse.com/css-cascade-layers). An example use case would be to make sure that utility classes could always override component styles, or that local styles could override imported shared company-wide styles to allow modifications on a per-app basis.

The [order that the browser discovers layers is very important](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers#determining_the_precedence_based_on_the_order_of_layers). Users of CSS cascade layers and Next.js need a way to define their layers before any other CSS is encountered by the browser, or else the order of the layers that the browser picks may not be what the developer wanted. 

This seems difficult at the moment as layout CSS appears in the DOM after per-page or per-component styles:

![image](https://user-images.githubusercontent.com/6339853/228086070-e1e1485d-1733-4b83-acbd-a5cc7768b8e3.png)

## Workarounds

To make sure it comes first I’ve had to add a new CSS file containing the layer definitions (e.g. `@layer default, theme, state;`) to my public directory, and import it with a `precedence` prop that isn’t in the types :( This is a shame as it's a non-standard way of doing things and the file now isn't processed in the same way as my other CSS files:

![image](https://user-images.githubusercontent.com/6339853/228086394-4e05d934-8798-445e-b208-0564c9443070.png)

I am also considering undoing the above, but using https://github.com/ramonvictor/postcss-prepend-imports to import a CSS file that defines the layers into every CSS file, so it doesn't matter which one the browser encounters first. I'd rather not do this because of the unnecessary bytes.

### Expected Behavior

I'd love any of these:
* a way to control the 'weight' of a CSS import so that I could give my CSS layer defining import a weight of -100 and have it always come first
* an officially supported way to include a `<link>` element with a `precedence` prop value that will make it appear in the DOM order before any other `link type="stylesheet"` elements
* an officially supported way to include some inline CSS (`<style>@layer default, theme, state;</style>` ) that will appear in the DOM order before any `link type="stylesheet"` elements

### Which browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

<sub>[NEXT-983](https://linear.app/vercel/issue/NEXT-983/app-router-css-handling-seems-incompatible-with-css-cascade-layers-no)</sub>

**Comment by philwolstenholme** [comment]
cc @gnoff (https://twitter.com/dan_abramov/status/1639667448369618948)

**Comment by bencehusi** [comment]
Having the same issue.

How can I control/ensure that an imported css file always stays on the top?

I use tailwind with some component library.

When hot reload happens, the imported css will be always the last before the closing </head> tag - wrecking havoc on my styles.

**Comment by gnoff** [comment]
@philwolstenholme sorry for the delay, was travelling when we first engaged. back now and going to look at this

**Comment by philwolstenholme** [comment]
No need to apologise @gnoff :) Thanks for looking into it.

**Comment by gnoff** [comment]
cc @shuding source issue

**Comment by gnoff** [comment]
@philwolstenholme the page css is supposed to be higher precedence than the layout css. we're looking into why it is out of order. The idea is that you would just define your layers in the root layouts css imports. the first import in that file should go first when we render the page and therefore you should have a stable order for your layers. For some reason the page css is being ordered first which is not expected. Once we fix the ordering I believe you should have all the tools necessary to stage the layers yourself without any special purpose APIs

Thanks for bringing to our attention

**Comment by philwolstenholme** [comment]
> The idea is that you would just define your layers in the root layouts css imports. the first import in that file should go first when we render the page and therefore you should have a stable order for your layers.

Perfect, that sounds like the behaviour I had expected/hoped for when I tried this out for the first time. Thanks for picking this up 🙂

**Comment by philwolstenholme** [comment]
Looks like this might have a follow-up: #48807
