### ISSUE TITLE
next dev overwrite global fetch

### ISSUE THREAD

**Issue by edvinerikson** [vercel/next.js#47596]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Wed Nov 23 01:01:46 UTC 2022
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 4.0.0-rc.39
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.20
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/edvinerikson/next-dev-server-bug-repro

### To Reproduce

run the dev server with `npm run dev`,  and navigate to `http://localhost:3000`. After the first load, inspect the next dev server terminal output.

You should see this:
```
executing fetch
[Function: patchedFetch]
````

refresh the page again and you should see this additional line:
```
[AsyncFunction: fetch]
```

### Describe the Bug

The first request to the dev server always work. The first request after a change (HMR kicks in) works. What doesn't work is any subsequent requests. Those subsequent requests flips back to the original fetch implementation (`[AsyncFunction: fetch]`) which make my fetch patch (`[Function: patchedFetch]`) not run anymore.

### Expected Behavior

I expect that the terminal always print `[Function: patchedFetch]`, this is how it works if you run using next build/next start

**Comment by edvinerikson** [comment]
cc @feedthejim do you know if this could be fixed in next? It seems that the memory leak fix applied in the dev server is what causes this to happen.

**Comment by kettanaito** [comment]
I'm encountering a similar issue when using MSW server-side (in `getServerSideProps`). Next is restoring the `fetch` global, throwing any the patch that MSW applies to provision interception. 

## How to resolve this

Next shouldn't prematurely assume they are the only ones patching globals. Instead, if they do provision patches, mark them with a unique Symbol, then check the presence of that symbol before applying the patch _That_ is a much more reliable global module patching strategy to prevent patch duplicates and respect whichever other third-party libraries may meddle with globals. 

Can I please ask the Next team to consider this approach?

**Comment by kettanaito** [comment]
https://github.com/vercel/next.js/pull/60796 seems to achieve the purpose! Excited to give it a try to share my findings. Thank you for working on this.
