### ISSUE TITLE
[WEB-854] Cannot find module './dictionaries_cs.json_cd1970._.js' when i was trying app dir, using turbopack it appeared

### ISSUE THREAD

**Issue by vadxq** [vercel/next.js#47595]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.14.0
    Relevant packages:
      next: 13.2.5-canary.20
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

app-dir-i18n-routing

### What browser are you using? (if relevant)

chrome

### Describe the Bug

<img width="726" alt="image" src="https://user-images.githubusercontent.com/18227775/228223067-3754eab1-bf4d-43a8-bbd9-f99e428c36ba.png">

When I run the program with turbopack, the json file of dictionaries cannot be found. 

When i was trying app dir, using turbopack it appeared.

this script is `"dev": "next --turbo"`

But it’s okay to use the default webpack.

### Expected Behavior

I hope to be compatible with turbopack and be able to use turbopack to develop.
Is it because turbopack lacks something? 
How do I need to modify the program to meet this?

### To Reproduce

It is almost reproducible using the official warehouse.

clone code and `pnpm i` install package

change `package.json` `script ` to this:

```
"scripts": {
    "dev": "next --turbo"
}
```
run  `pnpm dev` , reproduce.

<sub>[WEB-854](https://linear.app/vercel/issue/NEXT-910/cannot-find-module-dictionaries-csjson-cd1970-js-when-i-was-trying-app)</sub>

**Comment by vadxq** [comment]
If you need to use app-dir-i18n-routing, I now use the static import method instead of the dynamic import method, which can run through turbopack and is provided for the convenience of app dir i18n friends. 

But dynamic import still needs an official solution.

like this:
```typescript
import 'server-only';
import type { Locale } from './config';

// static import instead of dynamic import
import enJson from './dictionaries/en.json' assert { type: 'json' };
import zhCNJson from './dictionaries/zh-CN.json' assert { type: 'json' };

// We enumerate all dictionaries here for better linting and typescript support
// We also get the default import for cleaner types
const dictionaries = {
  en: () => enJson,
  'zh-CN': () => zhCNJson
  // https://github.com/vercel/next.js/issues/47595
  // en: () =>
  // import('./dictionaries/en.json', { assert: { type: 'json' } }).then(
  //   (module) => module.default
  // ),
  // 'zh-CN': () =>
  //   import('./dictionaries/zh-CN.json', { assert: { type: 'json' } }).then(
  //     (module) => module.default
  //   )
};

export const getDictionary = async (locale: Locale) => dictionaries[locale]();
```

**Comment by padmaia** [comment]
I'm not seeing this when testing with the latest version. Closing this one out.
