### ISSUE TITLE
Error with 'with-tailwind' example

### ISSUE THREAD

**Issue by reveurguy** [vercel/next.js#47593]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.4.0
      npm: 9.6.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-tailwindcss

### What browser are you using? (if relevant)

Arc

### Describe the Bug

I am running the `npx create-next-app --tailwind with-tailwindcss-app` command and the project that is created doesn't have tailwind configured.

### Expected Behavior

The project created should have tailwind configured.

### To Reproduce

run `npx create-next-app --tailwind with-tailwindcss-app`

**Comment by balazsorban44** [comment]
The Tailwind example has been moved to the CLI, using the `--tailwind` flag.

See:

https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss#how-to-use

**Comment by reveurguy** [comment]
Ok I'll try with create-next-app@canary.
Is create-next-app considered as latest? Because earlier it was working fine, but recently only it stopped working and now it creates a next project but tailwind is not configured for that.

**Comment by reveurguy** [comment]
I tried using the earlier method as well which was `npx create-next-app --example with-tailwindcss myname`. This also gave error

**Comment by jswent** [comment]
If the new `--tailwind` flag only works on canary maybe they shouldn't have pushed the changes to with-tailwind example yet, as now there is no way to generate a tailwind project on latest.
