### ISSUE TITLE
Docs: Assets, Metadata, and CSS > Global Styles

### ISSUE THREAD

**Issue by aaalfo2** [vercel/next.js#47601]
### What is the improvement or update you wish to see?

There is a spelling error in a code. On this line,
" Finally, import the CSS file inside the pages/_app.js file you've created earlier on: "

the provided code is
```
// pages/_app.js
import '../styles/global.css';

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
```

Which results in an error that says cannot find the global.css file. Because there is not a global.css file, it's global**s**.css.

I know the documentation says create a new file before this, but let's say a user sees an existing global CSS file and don't do it.

### Is there any context that might help us understand?

No. It's simple enough.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/assets-metadata-css/global-styles

**Comment by balazsorban44** [comment]
I could not find a reference to `globals.css` on the page you linked to. This has likely been fixed already then.

**Comment by aaalfo2** [comment]
> I could not find a reference to `globals.css` on the page you linked to. This has likely been fixed already then.

No, global`s`.css it's not on the page; it's in the starter repo files.

I'm saying, while the page says create a new global css file, wouldn't it be better to reference to and use the existing file? Because, for example, imagine someone sees the existing file and skip making "global.css" file. They would edit the existing global`s`.css file, only to face the error page of not finding that file because of the provided code in the guides.
