### ISSUE TITLE
All pages inside app dir I'm using new fetch api to repalce getStaticProps throw me an error: 'TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component' but I'm not using contexts on it'

### ISSUE THREAD

**Issue by RamboGj** [vercel/next.js#47603]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

Not sure

### To Reproduce

Not sure

### Describe the Bug

I am moving a NextJS 12 application to a NextJS 13 with app dir. I moved all pages successfully following NextJS upgrade guide here:[( https://beta.nextjs.org/docs/upgrade-guide)] But now that I'm trying to use Next's new fetch api, I 'm getting a trouble. ALL PAGES I was using getStaticProps are throwing me an error 'TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it.' when I use the new fetch api, but I'm not using a context in it.

This is my component inside app dir =>

```
import { BlogAdCard } from '@components/Blog/BlogAdCard'

import { motion } from 'framer-motion'
import Footer from '@components/Footer'

interface AdProps {
  id: number
  attributes: {
    thumbnail: {
      data: {
        attributes: {
          formats: {
            thumbnail: {
              url: string
            }
          }
        }
      }
    }
    title: string
    excerpt: string
    createdAt: Date
    updatedAt: Date
    publishedAt: Date
    slug: string
    callToAction: string
  }
}
async function getBlogAds() {
  const res = await fetch(
    'apiUrlPlaceholder',
    { next: { revalidate: 60 * 60 * 6 } },
  )
  const blogAds = await res.json()

  return blogAds
}

export default async function Blog() {
  const blogAds: AdProps[] = await getBlogAds()

  return (
    <div className="max-w-screen min-h-screen w-full bg-blueBurBg bg-left-bottom bg-no-repeat">
      <div className="max-w-[1120px] w-full mx-auto pt-14">
        <header className="w-full flex flex-col items-center">
          <h1 className="font-aldrich text-[1.5rem] lg:text-[3.5rem] uppercase">
            BLOG
          </h1>
          <p className="text-center text-white text-2xl mt-6">
            Curated articles by our experts
          </p>
        </header>
        <motion.ul
          initial="hidden"
          animate="visible"
          className="w-full mt-14 flex flex-wrap gap-8"
        >
          {blogAds?.map(({ attributes, id }) => {
            return <BlogAdCard key={id} id={id} attributes={attributes} />
          })}
        </motion.ul>
      </div>
      <Footer />
    </div>
  )
}
```

Addition: I am using 2 contexts in my /app/layout.tsx and both has 'use client' on its top, but removing them didn't make the app works well.

### Expected Behavior

I expect the app to load the pages correctly and fetch the data without throwing me a context error once I'm not using contexts on its page

**Comment by RamboGj** [comment]
Framer Motion was causing this. It's probably using many client side hooks once animations only happens on client side. Not sure how to animate components with framer motion inside server components.

**Comment by JesseKoldewijn** [comment]
@RamboGj you can use the layout.tsx file for providers and also for framermotion if we're talking page transitions. See: https://beta.nextjs.org/docs/rendering/server-and-client-components#rendering-third-party-context-providers-in-server-components

If you want to do any other animations I would recommend wrapping the animation in a dynamic imported component.
