### ISSUE TITLE
`initialProps.html` incorrectly encodes the class attribute value in HTML

### ISSUE THREAD

**Issue by 1aron** [vercel/next.js#47617]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 7.17.0
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-3otnhg?file=pages%2Findex.js,pages%2F_document.js%3AL23,pages%2F_app.js

### To Reproduce

1. Add a [Master CSS](https://beta.css.master.co/docs/guides) syntax `ml:0>h1` in `className="..."`
```tsx
// pages/index.js

export default function Home() {
  return (
    <div class="ml:0>h1">
      <h1>Hello World</h1>
    </div>
  );
}
```

2. Create a `pages/_docment.tsx` with the following code:
```tsx
// pages/_docment.tsx

import Document, { Html, Head, Main, NextScript, DocumentContext } from 'next/document';

export default function Doc() {
    return (
        <Html>
            <Head />
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}

Doc.getInitialProps = async (ctx) => {
    const initialProps = await Document.getInitialProps(ctx);
    console.log(initialProps.html);
    return initialProps;
};
```

See the `console.log(initialProps.html)` output

### Describe the Bug

`initialProps.html` incorrectly encodes `>` in `class="..."` as `&gt;`:
```html
<div id="__next"><div class="ml:0&gt;h1"><h1>Hello World</h1></div></div>
```

### Expected Behavior

```html
<div id="__next"><div class="ml:0>h1"><h1>Hello World</h1></div></div>
```
The CSS rules generated by Master CSS based on the class name `ml:0>h1` are as follows:
```css
.ml\:0\>h1>h1 {
    margin-left: 0rem
}
```
The `\>` in the middle is a valid CSS selector; I have tried it in pure React or other frameworks, and they all encode HTML correctly except Next.js.

I'm proposing a brand new architecture: **CSS Progressive Rendering** - it's used to encapsulate and generate CSS rules on-demand for technologies like SSR and SSG and has overall better rendering and CSS painting performance.

Check out the guide [Master CSS Progressive Rendering in Next.js](https://beta.css.master.co/docs/guides/nextjs)

**Comment by balazsorban44** [comment]
This is unrelated to Next.js.

The escaping happens in React. Here is a reproduction without Next.js: https://codesandbox.io/s/busy-resonance-owc77s?file=/src/index.js

**Comment by 1aron** [comment]
> This is unrelated to Next.js.
> 
> The escaping happens in React. Here is a reproduction without Next.js: https://codesandbox.io/s/busy-resonance-owc77s?file=/src/index.js

Sorry we realized this earlier, we should have decoded the source first.
