### ISSUE TITLE
Image srcset size widths not generated at all

### ISSUE THREAD

**Issue by apfelbox** [vercel/next.js#47613]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 8.0.0
    Relevant packages:
      next: 13.2.5-canary.20
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

—

### To Reproduce

We are using the image component with a custom loader. However for regular images, there are no image sizes generated anymore.

Only the `1x` and `2x` sizes are generated, however no screen width based ones.

### Describe the Bug

We use the image like this:

```tsx
const image = {
    src: "...",
    width: ...,
    height: ...,
};

<Image src={image} alt={alt} />
```

But now it just generates an image with srcset `1x` and `2x` and doesn't use the image sizes at all. This way we use the image with 4000px width even on mobile devices.

### Expected Behavior

It should always generate the different width-sizes as well, to avoid loading huge sizes on mobile.

**Comment by styfle** [comment]
You need to set the [`sizes`](https://nextjs.org/docs/pages/api-reference/components/image#sizes) prop

**Comment by styfle** [comment]
Closing since responsive images was documented in PR #51457.

See the rendered documentation here: https://nextjs.org/docs/app/building-your-application/optimizing/images#responsive

**Comment by apfelbox** [comment]
Perfect, thank you (esp for the direct docs link) 👍
