### ISSUE TITLE
Latest canary release adds unused import to compiled types

### ISSUE THREAD

**Issue by StampixSMO** [vercel/next.js#47646]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: 7.29.1
    Relevant packages:
      next: 13.2.5-canary.20
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), TypeScript

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-go5rfn?file=README.md

### To Reproduce

1. Create a [new StackBlitz](https://stackblitz.com/edit/vercel-next-js-go5rfn?file=README.md) with the new app repo
2. Build the example without changing anything (new terminal & `npm run build`)
3. Read out `cat .next/types/app/page.ts`
4. There's `NextRequest` imported there, unused  in the file.

### Describe the Bug

Our TS configuration errors out on unused types/variables/... and since it's the default to also type-check the `.next/types` folder, this errors out during build.

This first appeared in `13.2.5-canary.19`, `13.2.5-canary.18` works fine.

### Expected Behavior

The `types` folder in the `.next` folder to not contain unused types.

**Comment by DuCanhGH** [comment]
Ah, sorry for this, should be a quick fix. Definitely introduced by my PR that added Route Handlers support to Next's Typescript plugin...
