### ISSUE TITLE
Module not found: Can't resolve './_next/static/media/b1db3e28af9ef94a-s.woff2'  After set   assetPrefix to '.',

### ISSUE THREAD

**Issue by coderup2021** [vercel/next.js#47641]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
❯ pnpm next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.17.1
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.2.4", newest: "13.2.5-canary.20".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Link to the code that reproduces this issue

no

### To Reproduce

pnpm create next-app  (with default options) 

modify next.config.js as following

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  assetPrefix: '.',    // or './'
}

module.exports = nextConfig
```

pnpm build

then will get following error
```shell
pnpm build

> next-test@0.1.0 build /Users/lj/Study/web3.0/next-test
> next build

info  - Linting and checking validity of types  
Failed to compile.

src/pages/index.tsx
Module not found: Can't resolve './_next/static/media/d1d9458b69004127-s.woff2'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/font/google/target.css?{"path":"src/pages/index.tsx","import":"Inter","arguments":[{"subsets":["latin"]}],"variableName":"inter"}
./src/pages/index.tsx

src/pages/index.tsx
Module not found: Can't resolve './_next/static/media/b967158bc7d7a9fb-s.woff2'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/font/google/target.css?{"path":"src/pages/index.tsx","import":"Inter","arguments":[{"subsets":["latin"]}],"variableName":"inter"}
./src/pages/index.tsx

src/pages/index.tsx
Module not found: Can't resolve './_next/static/media/ae9ae6716d4f8bf8-s.woff2'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/font/google/target.css?{"path":"src/pages/index.tsx","import":"Inter","arguments":[{"subsets":["latin"]}],"variableName":"inter"}
./src/pages/index.tsx

src/pages/index.tsx
Module not found: Can't resolve './_next/static/media/c0f5ec5bbf5913b7-s.woff2'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/font/google/target.css?{"path":"src/pages/index.tsx","import":"Inter","arguments":[{"subsets":["latin"]}],"variableName":"inter"}
./src/pages/index.tsx

src/pages/index.tsx
Module not found: Can't resolve './_next/static/media/b1db3e28af9ef94a-s.woff2'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.2.4_biqbaboplfbrettd7655fr4n2y/node_modules/next/font/google/target.css?{"path":"src/pages/index.tsx","import":"Inter","arguments":[{"subsets":["latin"]}],"variableName":"inter"}
./src/pages/index.tsx


> Build failed because of webpack errors
info  - Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.
```

### Describe the Bug

I am not sure what happend, please help

### Expected Behavior

expected `pnpm build` can work ok with assetPrefix config

**Comment by balazsorban44** [comment]
Hmm. It looks like the repro steps given are enough to reproduce. (The default template uses `next/font`)

**Comment by JesseKoldewijn** [comment]
> After some digging, I believe this is intentionally not working. The `assetPrefix` is expected to be a full URL or an absolute path, and not start with a `.`. This is how it is documented as well: https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix 
> 
> So I think we just need a better error message and clarify the docs.
> 
> This will be invalid for other use cases like `next/image as well, but that component will already surface this via the following error message:
> 
> ![image](https://user-images.githubusercontent.com/18369201/229825629-9cabfbdc-0989-4200-b7d8-527d440efdf4.png)
> 

Well in my case I programatically import the image file and throw it into a Image component. It works on deployments to vercel and in dev but it breaks on static.

**Comment by balazsorban44** [comment]
> Well in my case I programatically import the image file and throw it into a Image component. It works on deployments to vercel and in dev but it breaks on static.

Can you clarify this part? What do you mean by "programmatically importing"? Maybe you can attach a reproduction?

The above error is shown when you import the image in the module scope and pass it to the `src` prop, this is what triggers the image loader to emit the files in the static folder.

https://github.com/vercel/next.js/blob/a3acbf4f552bd6b8780d739dfae418e775d1b4de/packages/next/src/build/webpack/loaders/next-image-loader/index.ts#L20-L25

`next/font` has the same path generation:

https://github.com/vercel/next.js/blob/a3acbf4f552bd6b8780d739dfae418e775d1b4de/packages/next/src/build/webpack/loaders/next-font-loader/index.ts#L69-L76

It just does not verify invalid URLs later on, as `next/image` does:

https://github.com/vercel/next.js/blob/a3acbf4f552bd6b8780d739dfae418e775d1b4de/packages/next/src/shared/lib/image-loader.ts#L26-L41

**Comment by JesseKoldewijn** [comment]
> > Well in my case I programatically import the image file and throw it into a Image component. It works on deployments to vercel and in dev but it breaks on static.
> 
> Can you clarify this part? What do you mean by "programmatically importing"? Maybe you can attach a reproduction?
> 
> The above error is shown when you import the image in the module scope and pass it to the `src` prop, this is what triggers the image loader to emit the files in the static folder.
> 
> https://github.com/vercel/next.js/blob/a3acbf4f552bd6b8780d739dfae418e775d1b4de/packages/next/src/build/webpack/loaders/next-image-loader/index.ts#L20-L25
> 
> `next/font` has the same path generation:
> 
> https://github.com/vercel/next.js/blob/a3acbf4f552bd6b8780d739dfae418e775d1b4de/packages/next/src/build/webpack/loaders/next-font-loader/index.ts#L69-L76
> 
> It just does not verify invalid URLs later on, as `next/image` does:
> 
> https://github.com/vercel/next.js/blob/a3acbf4f552bd6b8780d739dfae418e775d1b4de/packages/next/src/shared/lib/image-loader.ts#L26-L41

I got my images in a images folder in the src dir. I import them from that dir in my code and then dump the image into a Image component. My repo is located in https://github.com/ShiftCodeEU/shiftcode.eu

**Comment by balazsorban44** [comment]
This seems to be unrelated to the original issue though since I cannot see an `assetPrefix` config. (I also see `output: "export"` commented out/third-party tool generating the output, maybe it should be reported as a separate issue.)

**Comment by JesseKoldewijn** [comment]
> This seems to be unrelated to the original issue though since I cannot see an `assetPrefix` config. (I also see `output: "export"` commented out/third-party tool generating the output, maybe it should be reported as a separate issue.)

You're right that I'm not using the asset prefix. I did have the output export enabled while testing which is why it's commented out. As far as I know and from my experience with the pages dir I was under the impression it would still work the same as it does with importing images ending up in the _next/static dir.

**Comment by koba04** [comment]
@balazsorban44 I've created a PR to improve the error message #49403
