### ISSUE TITLE
Docs: beta docs for Internationalization (i18n) - server-only

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#47656]
### What is the improvement or update you wish to see?

In the beta [Localization](https://beta.nextjs.org/docs/guides/internationalization#localization) docs, is an code example:

```javascript
import 'server-only';

const dictionaries = {
  en: () => import('./dictionaries/en.json').then((module) => module.default),
  nl: () => import('./dictionaries/nl.json').then((module) => module.default),
};

export const getDictionary = async (locale) => dictionaries[locale]();
```

But there is no information that [`server-only`](https://www.npmjs.com/package/server-only) is a third party package, you need to install first.

### Is there any context that might help us understand?

In this example [Keeping Server-Only Code out of Client Components (Poisoning)](https://beta.nextjs.org/docs/rendering/server-and-client-components#keeping-server-only-code-out-of-client-components-poisoning) there is a information that you have to install `server-only` first:

![image](https://user-images.githubusercontent.com/987947/228523301-a593953d-f024-42d4-8563-6b34126fb479.png)

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/guides/internationalization#localization

**Comment by leerob** [comment]
Thanks, we'll make this change 🙏
