### ISSUE TITLE
Inline next/script doesn't run when placed in _document

### ISSUE THREAD

**Issue by christiankaindl** [vercel/next.js#47666]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.2.5-canary.20
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Script optimization (next/script)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/modest-fog-d7t1mg?file=%2FREADME.md

### To Reproduce

1. Open Codesandbox reproduction
2. Open browser console
3. Reload preview in Codesandbox
4. Notice that only the Script

### Describe the Bug

Inline scripts with strategy='afterInteractive' in `_document.js` aren't executed and also don't fire any of onLoad/onReady/onError.

### Expected Behavior

To see both 
- "Running inline script 1" and
- "Running inline script 2"
in the console. But only the second one (and the beforeInteractive one) is logged.

**Comment by JesseKoldewijn** [comment]
Try those scripts in the _app.js file 👍

**Comment by christiankaindl** [comment]
> Try those scripts in the _app.js file +1

Yes, that is what I did to work around the issue, but I did not find anything in the docs that would suggest that it doesn't work in _document.js?

**Comment by JesseKoldewijn** [comment]
The _docuement file is used on serverside only which is also why you get an error in your IDE when you try to use the next/document components in any other file. one of the things that might work in some cases but is still not recommended is importing css files in your _document file instead of your _app file

**Comment by JesseKoldewijn** [comment]
This falls under the 2nd caveat in the docs. See: https://nextjs.org/docs/advanced-features/custom-document

**Comment by JesseKoldewijn** [comment]
> Thanks for the link @JesseKoldewijn, that makes sense! Then it seems to me Next.js could show a warning at least in that case, though the issue is probably obsolete with the new app router anyways

Even in the appDir you do have places where your code only runs on buildtime or strictly in server. One thing you for instance need to think about is to import any styling, providers and such inside of your template.tsx and not inside of your pages or layouts themselves.

**Comment by balazsorban44** [comment]
https://nextjs.org/docs/api-reference/next/script#afterinteractive

It mentions that you can place it in pages and layouts.

The page also mentions that `beforeInteractive` scripts can be placed in `_document` as a hint.


For the App Router, here is the documentation https://beta.nextjs.org/docs/api-reference/components/script (not it is a work in progress, feel free to leave feedback on it directly, via Preview Comments.)
