### ISSUE TITLE
FOUC with CSS Modules and Next.js 13

### ISSUE THREAD

**Issue by harshhhdev** [vercel/next.js#47683]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000
    Binaries:
      Node: 19.7.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.17.1
    Relevant packages:
      next: 13.2.3
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/harshhhdev/www/tree/next-rewrite/src/app

### To Reproduce

You can already see the FOUC on the deployed website at: [33fa1ur95-38kle3q7i-harshhhdev.vercel.app](https://33fa1ur95-38kle3q7i-harshhhdev.vercel.app/)

1) Clone the repository
2) Click on a link _specifically_ from the navbar
3) See FOUC

### Describe the Bug

Whenever I click on a new link using the navbar, I get FOUC because the CSS modules load slow.

The global styles load just fine, it's just the CSS modules that are loading slow. I have a feeling that the modules are fetched only when the page loads, and here the HTML loads first. I'm positive that this is an issue with next/link, because when I substitute it with regular anchor tags the glitch goes away.

I've also tried turning off prefetch, but I haven't had any luck with it.

### Expected Behavior

I expect all the styles to load properly, and not get the flash of unstyled content.

### Which browser are you using? (if relevant)

Brave Browser 104.1.42.97

### How are you deploying your application? (if relevant)

Vercel

**Comment by NitrousBGC** [comment]
I face the same problem since the release of Next 13. There is definitely a problem with css and scss modules.

**Comment by harshhhdev** [comment]
This was fixed on Next.js 13.3.0 :partying_face:

**Comment by NitrousBGC** [comment]
> This was fixed on Next.js 13.3.0 :partying_face:

Wow! That's really exciting news. 
I'll test it ASAP!
