### ISSUE TITLE
[NEXT-940] Unexpected token u in JSON because of  "use client"

### ISSUE THREAD

**Issue by thewbuk** [vercel/next.js#47704]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win64
      Arch: x64
      Version: Windows 11 Home
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.21
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Static HTML Export (next export)

### Link to the code that reproduces this issue

https://github.com/thewbuk/nextjs13_error

### To Reproduce

`npm run build`

### Describe the Bug

When trying to build project, `SyntaxError: Unexpected token u in JSON at position 0` is thrown for every page that uses `"use client"` even though the latest release of the canary is supposed to fix this issue. 

Using `App` directory

### Expected Behavior

Create static export

<sub>[NEXT-940](https://linear.app/vercel/issue/NEXT-940/unexpected-token-u-in-json-because-of-use-client)</sub>

**Comment by mattiasw** [comment]
Same problem in our project using 13.2.5-canary.21. It works fine on Linux but not on Windows. We're seeing the problem with `next dev` too.

**Comment by ZiBuDo** [comment]
On 13.2.4 with a page that uses a client component.

When I migrate the page to a route group with a multiple root layouts I also get this error. Tested on canary as well.

On Windows.

**Comment by BeezBeez** [comment]
Same problem here on 13.2.5-canary.21

**Comment by mattiasw** [comment]
Tried it on Node 18 and still the same error.

**Comment by frg** [comment]
@JesseKoldewijn This solution didn't work for me. Did it work for anyone with this issue?

Windows, node 18.12.1, next 13.2.4

**Comment by Brettkgamble** [comment]
I am experiencing the same issue here for Versions 13.2.5-canary.20 through to 13.2.5-canary.25

13.2.5-canary.19 works fine.

**Comment by darklight9811** [comment]
This is just too huge of a bug to be left unoticed by the next team. So I believe we must fall under certain conditions to let this error happen.

From every person that commented here, I would like to know your operating system, node version and any other detail considered relevant.

**Comment by Kiborgik** [comment]
The same on any canary> 20. Win 11, Node v18.15.0

**Comment by Winwardo** [comment]
Happening here on use of `"use client"`.
Canary 20+, Windows 10, Node 18.14.2.

Looking through commits between https://github.com/vercel/next.js/commit/53bcdea01c963ecfb0746bd70ab73ba114aa32e8 and https://github.com/vercel/next.js/commit/18131c7dab79365c7025e59f6052cd81b61a9215, the following few look possibly related:

* [Add initial tree shaking refactorings](https://github.com/vercel/next.js/commit/4c2ad81ea7d5ff51a8d91aa31e4dca3514067555)
* [Improve client boundary source type detection](https://github.com/vercel/next.js/commit/b28cd21ee57bfd9c2f7e775310e42b1ec9dd1eab)

**Comment by epndavis** [comment]
> "use client";
> 
> const About = () => {
> 	return <div></div>;
> };
> export default About;

For me not using the arrow function broke it.
```
"use client";

export default function About() {
	return <div></div>;
};
```
Swapped my client component to an arrow function and it worked.

**Comment by JesseKoldewijn** [comment]
> > "use client";
> > 
> > const About = () => {
> > 	return <div></div>;
> > };
> > export default About;
> 
> For me not using the arrow function broke it.
> ```
> "use client";
> 
> export default function About() {
> 	return <div></div>;
> };
> ```
> Swapped my client component to an arrow function and it worked.
> Version: `13.2.5-canary.28` , Windows 11, Node: 16.14.2

Yeah for me it sort of stopped breaking on build when I used arrow functions and actually having a element in the return other than a empty fragment. It did still break on a dynamic route tho cuz on the static build it only exported images used in one of the static routes and nothing else. 

So it only exports the following structure:
```
/_next/** <- ofcourse
/showcase/
--/slug-1 <- only images no html 
/404.html <- might work fine, didnt test
/index.html <- broken asset hrefs
```

The disfunctional dynamic route might have to do with my setup because I didn't dive deep into the ssg usecase of it yet, so I'm not sure if you still have to generate the static paths for it.

The disfunctional image src hrefs on the index page are kinda weird to me because I'm not using anything in the homepage that scream "I'm gonna break!" to me honestly.

Might need to have a deeper look into it bur hey, atleast it partially works ish.

Repo: https://github.com/ShiftCodeEU/shiftcode.eu 

^ Incase anybody knows what the deal is with the broken images or something, would appreciate it👌

**Comment by Nickman87** [comment]
> > "use client";
> > const About = () => {
> > return ;
> > };
> > export default About;
> 
> For me not using the arrow function broke it.
> 
> ```
> "use client";
> 
> export default function About() {
> 	return <div></div>;
> };
> ```
> 
> Swapped my client component to an arrow function and it worked. Version: `13.2.5-canary.28` , Windows 11, Node: 16.14.2

Same here, switching my client component to an arrow function instead of a regular function fixed the build error, didn't change anything else:
Windows 11 fresh install + node V18.15.0 (latest LTS)

**Comment by Brettkgamble** [comment]
I edited all of my client components and changed to Arrow functions which partially solved the issue.  I am using Vercel's Analytics wrapper which has the format: 

`'use client';
import { Analytics } from '@vercel/analytics/react';

export function AnalyticsWrapper() {
  return <Analytics />;
}`

When I change this to an arrow function everything breaks.  The same for the preview Suspense that I am using for my Sanity CMS integration. 

`"use client"

// Once rollup supports 'use client' module directives then 'next-sanity'
// will include them and this re export will no longer be necessary

export { PreviewSuspense as default } from 'next-sanity/preview';`

I try to keep up with the Canary releases.....for exactly this reason, when things break I like to stay ahead a little, rather than trying to upgrade higher versions of releases which has been problematic in the past.

**Comment by darklight9811** [comment]
Error still happening in `13.2.5-canary.32`

**Comment by SuttonJack** [comment]
If anyone is in a position where others on your team have Windows and you only have a mac, I used [this](https://www.parallels.com/) app, downloaded Node, and was able to debug our codebase / try the suggestions above.

**Comment by darklight9811** [comment]
Wish vercel/next team would look into this, because Im unable to test fixes and later improvements because of this error.

**Comment by DerianAndre** [comment]
I had all my functions as arrow functions and with export default. One page had `export const metadata = { ... }`  and it affected, removing it solve the issue... also I tried `export { metadata }` didn't work had to remove it completly.

**Comment by Systemcluster** [comment]
This is not just related to pages, every component with `"use client"` causes this error in `13.3.0`.

Reproduction:

- Create an example app with `npx create-next-app@latest --experimental-app`
- Create a simple client component:
```tsx
"use client"
export const ClientComponent = () => {
    return (<div>Hello World</div>)
}
```
- Add it to `app/layout.tsx`:
```tsx
<body>
    {children}
    <ClientComponent/>
</body>
```

**Comment by reginpv** [comment]
I can confirm this is still not working.

Windows 11
Next 13.3

I have test on my Mac and there's no issue, it looks looks like a Windows specific issue.

This will not work:
`"use client"

export default function Home() {
  return (
    <main>
      test
    </main>
  )
}
`

This will work
`"use client"

const Home = () => {
  return (
    <main>
      test
    </main>
  )
}

export default Home`

**Comment by motopods** [comment]
This issue seems to have been introduced in version 13.2.5-canary.19, and Windows specific issue.

**Comment by chris-pikul** [comment]
Confirmed here that Windows is broken.

# Arrow Function Fixes It

Broken code:

```js
"use client";

export default function MyComponent() {
  return <h1>Hello World</h1>;
}
```

The fix is to just convert to arrow function:

```js
"use client";

const MyComponent = () => {
  return <h1>Hello World</h1>;
}
export default MyComponent;
```

---
Platform: Windows 11
Next Version: 13.3.0
React Version: 18.2.0

**Comment by Abdulaleemu** [comment]
> 13.2.5-canary.19 works fine.

using arrow function worked for me too.. thanks a million

**Comment by igorroncevic** [comment]
> Confirmed here that Windows is broken.
> 
> # Arrow Function Fixes It
> Broken code:
> 
> ```js
> "use client";
> 
> export default function MyComponent() {
>   return <h1>Hello World</h1>;
> }
> ```
> 
> The fix is to just convert to arrow function:
> 
> ```js
> "use client";
> 
> const MyComponent = () => {
>   return <h1>Hello World</h1>;
> }
> export default MyComponent;
> ```
> 
> Platform: Windows 11 Next Version: 13.3.0 React Version: 18.2.0

Confirmed, just tried and it solved it the issue. Cheers!

**Comment by wouter-deen** [comment]
Same problem here. I'll just wait for the next stable release, as I do not think that replacing all the regular functions in my project with arrow functions is a viable option. Running Windows 11 Pro here.

**Comment by darklight9811** [comment]
@leerob sorry for pinging you here, but its been almost two weeks, one stable launch. And this is still blocking all windows users from continuing using next on app dirs.

**Comment by motopods** [comment]
It's related to two files, changed in 13.2.5-canary.20.

dist\build\analysis\get-page-static-info.js
next-swc.win32-x64-msvc.node

**Comment by motopods** [comment]
[(cjs|auto)](https://github.com/vercel/next.js/blob/18131c7dab79365c7025e59f6052cd81b61a9215/packages/next/src/build/analysis/get-page-static-info.ts#L45)

This line `(cjs|auto)` was added, and some changes in swc.

**Comment by motopods** [comment]
This error occurs when the clientEntryType is `auto`
https://github.com/vercel/next.js/blob/18131c7dab79365c7025e59f6052cd81b61a9215/packages/next/src/build/analysis/get-page-static-info.ts#L65

**Comment by Kiborgik** [comment]
Is the team aware about this?

**Comment by arshad-repliq** [comment]
Confirmation -
Using arrow functions to all of your components where "use client" is being used fixes it.
We should be using arrow functions for now until this bug gets fixed. 
Thanks everyone who recommended to use arrow function that actually does fix it

**Comment by motopods** [comment]
It's path slash bug in Windows at next-flight-loader, https://github.com/vercel/next.js/blob/9c0e52089628c25c13a5bce6fb57b18f65dbbae1/packages/next/src/build/webpack/loaders/next-flight-loader/index.ts#L67


Possible solutions， change
```
- const proxy = createProxy("${this.resourcePath}")
+ const proxy = createProxy(String.raw\`${this.resourcePath}\`)
```

**Comment by ddcrobert** [comment]
Works for me, huge thanks!

**Comment by ventsislavnikolov** [comment]
@motopods Thank you! It's working like a charm because for me, using the Arrow function cannot fix the problem because external libraries like NextAuth Session Provider are invoked and the problem still exists.

**Comment by thewbuk** [comment]
Amazing find @motopods! Works great on the newest versions. Having said that, I am not sure how the arrow function trick seems to solve it in some cases (it didn't fully solve it in mine), so worth investigating further and hopefully, an official patch will come soon now

**Comment by Keroxen** [comment]
converting to arrow function fixed the issue for me in 13.3.0.

**Comment by iliaamiri** [comment]
> It's path backslash and string escape bug at [next-flight-loader](https://linear.app/vercel/issue/NEXT-flight-loader), in Windows
> 
> https://github.com/vercel/next.js/blob/9c0e52089628c25c13a5bce6fb57b18f65dbbae1/packages/next/src/build/webpack/loaders/next-flight-loader/index.ts#L67
> 
> Possible solutions
> 
> ```
> - const proxy = createProxy("${this.resourcePath}")
> + const proxy = createProxy(String.raw\`${this.resourcePath}\`)
> ```
> 
> I am not sure arrow function's workaround is the same problem as this.
> 
> Is there anyone patch node_modules\next\dist\build\webpack\loaders\[next-flight-loade](https://linear.app/vercel/issue/NEXT-flight-loade)r\index.js, this file. then delete .next directory, restart dev. And give me some feedback?

Thank you! This is working for me as well ❣️
Tested on Vercel and everything works fine now 🤗

**Comment by SageJustus** [comment]
> 
This is working for me as well. 
I'm on Windows 10 and Next.js 13.3.0.

**Comment by basstimam** [comment]
> 

Thanks, It worked for me as well!

**Comment by basstimam** [comment]
> It's path backslash and string escape bug at [next-flight-loader](https://linear.app/vercel/issue/NEXT-flight-loader), in Windows
> 
> https://github.com/vercel/next.js/blob/9c0e52089628c25c13a5bce6fb57b18f65dbbae1/packages/next/src/build/webpack/loaders/next-flight-loader/index.ts#L67
> 
> Possible solutions
> 
> ```
> - const proxy = createProxy("${this.resourcePath}")
> + const proxy = createProxy(String.raw\`${this.resourcePath}\`)
> ```
> 
> I am not sure arrow function's workaround is the same problem as this.
> 
> Is there anyone patch node_modules\next\dist\build\webpack\loaders\[next-flight-loade](https://linear.app/vercel/issue/NEXT-flight-loade)r\index.js, this file. then delete .next directory, restart dev. And give me some feedback?



Thanks it worked for me!

**Comment by darklight9811** [comment]
Thanks @shuding, really grateful for this

**Comment by AlexKaridas** [comment]
same problem....

**Comment by iliaamiri** [comment]
@AlexKaridas Does this solution work for you?
![image](https://user-images.githubusercontent.com/37903573/233705209-95b072cf-87cc-432f-bd92-d2d8442d0a6e.png)
