### ISSUE TITLE
mdx math plugins does not work with the new Rust compiler 

### ISSUE THREAD

**Issue by qiushiyan** [vercel/next.js#47723]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 8.0.0
    Relevant packages:
      next: 13.2.5-canary.21
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), MDX (@next/mdx)

### Link to the code that reproduces this issue

https://github.com/qiushiyan/next13-mdx

### To Reproduce

`pnpm dev`

### Describe the Bug

I am trying to display katex formulas in mdx with two plugins `remark-math` and `rehypeKatex`. This is my `next.config.mjs` (with `app` dir and `mdxRs` enabled)

```
import addMdx from "@next/mdx";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";

/** @type {import('next').NextConfig} */
const nextConfig = {
	pageExtensions: ["ts", "tsx", "js", "jsx", "mdx"],
	experimental: {
		appDir: true,
		mdxRs: true,
	},
};

const widthMDX = addMdx(nextConfig, {
	options: {
		remarkPlugins: [remarkMath],
		rehypePlugins: [rehypeKatex],
		// If you use `MDXProvider`, uncomment the following line.
		// providerImportSource: "@mdx-js/react",
	},
});

export default widthMDX(nextConfig);
```

I also include the katex css link in my root layout.

Testing with mdx content 

```
# Hello mdx

This is a formula

$$
a^2 + b^2 = c^2
$$
```

This does not take any effect to transform the tags. 

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/48123899/228989197-b19991c6-3f62-4023-822a-15577697034f.png">

### Expected Behavior

Plugins transform formula into `<span class="math math-inline"><span class="katex">…</span></span>`

**Comment by balazsorban44** [comment]
Thanks, plugins are currently not supported by the Rust version, see also: https://github.com/vercel/next.js/discussions/41745#discussioncomment-5232465
