### ISSUE TITLE
When layout.tsx gets a child its type is [Function (anonymous)] and I can't filter them

### ISSUE THREAD

**Issue by GeisonJr** [vercel/next.js#47750]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Nothing specific, but i running in my machine the next 13.2.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/pedantic-joana-otyt70?file=%2Fapp%2Flayout.tsx&selection=%5B%7B%22endColumn%22%3A25%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A5%7D%5D

### To Reproduce

layout.tsx
```tsx
export default function ({ children }) {
  const filteredChildren = Children.toArray(children)
    .filter(child => {
    return child.type === 'button'; // works for Components Too
  });

  return (
    <div>
      {/* Renderize seus componentes de layout aqui */}
      {filteredChildren}
    </div>
  );
};
```

page.tsx
```tsx
export default function Main({ children }) {
  return <button>{children}</button>;
}
```

### Describe the Bug

I try to filter the children to use in a specific area of the page, but I can get their type, because they all come as [Function (anonymous)]

### Expected Behavior

It should be possible to perform this filtering by type

```tsx
  const filteredChildren = Children.toArray(children)
    .filter(child => {
    return child.type === 'button'; // works for Components Too
  });
```

**Comment by balazsorban44** [comment]
I could not see the issue in the reproduction. :thinking:

Also, note that `Children` might not be what you want: https://react.dev/reference/react/Children#alternatives
