### ISSUE TITLE
[WEB-831] [turbopack] Environment variables arent accessible in next13 middleware

### ISSUE THREAD

**Issue by sklymoshenko** [vercel/next.js#47766]
### What version of Turbopack are you using?

1.8.8

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When accessing a `process.env` only `NEXT_RUNTIME` is accessable from middleware. So there is no more env variables there. 

This scenario is working fine, without using `next dev --turbo`. 
I can access all my env variables when running `next dev` or after build with `next build` and `next start`.

### Expected Behavior

When accessing `process.env.CUSTOM_KEY` which is declared inside .env or .env.local or .env.* or inside `next.config.ts` in `env: { customKey: 'customKey' }` should be accessable in middleware handler or any other edge runtime.

### To Reproduce

Complete the steps from official website.
```
Create a Next.js v13 project with Turbopack:
npx create-next-app --example with-turbopack

Start the Next.js development server (with Turbopack):
yarn dev
```

package.json
```
{
  "private": true,
  "scripts": {
    "dev": "next dev --turbo",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "format": "prettier --write \"**/*.{js,ts,tsx,md}\""
  },
  "prettier": {
    "arrowParens": "always",
    "semi": true,
    "trailingComma": "all",
    "singleQuote": true
  },
  "dependencies": {
    "clsx": "1.2.1",
    "next": "latest",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "styled-components": "6.0.0-beta.2",
    "styled-jsx": "5.1.0",
    "use-count-up": "3.0.1"
  },
  "devDependencies": {
    "@types/node": "18.0.3",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
    "autoprefixer": "^10.4.7",
    "eslint": "8.19.0",
    "eslint-config-next": "latest",
    "postcss": "^8.4.14",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.12",
    "tailwindcss": "^3.1.6",
    "typescript": "4.7.4"
  }
}
```

middleware.ts
```
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export async function middleware(req: NextRequest, res: NextResponse) {
    console.log(process.env.CUSTOM_KEY) //undefined
    return NextResponse.next()
}
export const config = {
  matcher: ['/'],
}
```

next.config.ts
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true, // Recommended for the `pages` directory, default in `app`.
  experimental: {
    // Required:
    appDir: true,
  },
  env: {
    customKey: 'my-value',
  }
};

module.exports = nextConfig;
```

.env
```
CUSTOM_KEY = custom-key
```

<sub>[WEB-831](https://linear.app/vercel/issue/WEB-831/[turbopack]-environment-variables-arent-accessible-in-next13)</sub>

**Comment by jridgewell** [comment]
Traced through this, Turbopack is creating the `router` process with all expected ENV values. But, the edge function definition doesn't list any [ENV keys](https://github.com/vercel/next.js/blob/2adc1f6c54db2fdf2b8e0b02b6f7c023d8564b9b/packages/next/src/server/lib/route-resolver.ts#L162), so it's not invoked with any values (besides `NEXT_RUNTIME`).

@ijjk Is is ok to just `Object.keys(process.env)` here to pass everything? We don't currently have a way to determine what ENV keys are actually used in the dev's code.

**Comment by anthonytison** [comment]
Hi,
Currently, i'm using the Next 13.2.5-canary.32 and it works well for getting the env variables in the middleware however i can't get any of them inside the route handlers. 
So far, i only have the `NEXT_RUNTIME`.
