### ISSUE TITLE
Urgent, canary breaking on use client

### ISSUE THREAD

**Issue by darklight9811** [vercel/next.js#47796]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro Education
    Binaries:
      Node: 16.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.25
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

reproduction shown below

### To Reproduce

I really don't know how to reproduce because everything I do works when deploying to codesandbox and stackblitz. I think it may be related to windows (windows 10). But steps to reproduce:

- create app dir
- create client component (with use client directive)
- import it in the app

### Describe the Bug

Since `13.2.5-canary.20` (last working version is canary.19), my app is breaking when I try to import a "use client" component, it displays the following on the terminal:

``` bash
error - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
```

### Expected Behavior

To work as expected, as from before `13.2.5-canary.20`

**Comment by darklight9811** [comment]
I noticed when canary.21 launched, but decided to wait if this was fixed. Since I didn't notice anyone reporting this, decided to report it before it gets to next minor.

**Comment by thewbuk** [comment]
This error was reported at https://github.com/vercel/next.js/issues/47704 and https://github.com/vercel/next.js/issues/47748 with different circumstances as well

**Comment by darklight9811** [comment]
Closing in favor of #47704
