### ISSUE TITLE
Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.

### ISSUE THREAD

**Issue by llorenspujol** [vercel/next.js#47805]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.19.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

I cannot reproduce it locally.

### To Reproduce

I don't know exactly how to reproduce it locally, it seems to happen only when deployed on Vercel.

### Describe the Bug

When executing a serverless function, I am getting the error `Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.` approximately 50% of the times. This error seems to happen only when deployed on vercel. I see the error just by checking the logs.
It seems a bug in the cachedData, since this code is what is giving this error: https://github.com/vercel/next.js/pull/46204/files

Here is the Serverless execution success and fail chart by day, almost 50% fails due to this error.
![image](https://user-images.githubusercontent.com/18361241/229316007-cafa554f-213b-417b-9869-ea6714643dca.png)

Here is a full error example found in the "Logs":
```
2023-04-01T22:34:02.255Z	undefined	INFO	info  - Loaded env from /var/task/.env.production
Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.
    at NextNodeServer.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/server/base-server.js:1013:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async NextNodeServer.renderPageComponent (/var/task/node_modules/next/dist/server/base-server.js:1072:24)
    at async NextNodeServer.renderToResponseImpl (/var/task/node_modules/next/dist/server/base-server.js:1098:32) {
  page: '/front-end-jobs-in-antwerp'
}
RequestId: 3193f9ce-3d2b-493d-b5f4-6d8c4c407b22 Error: Runtime exited with error: exit status 1
Runtime.ExitError

```

### Expected Behavior

I expect the cache to work as expected and to have no errors in the serveless function executions. My external backend service , where the serverless function gets the data, does not fail, so the expected behaviour is that the serveless function gets the data and cache it as expected.

<sub>[NEXT-1391](https://linear.app/vercel/issue/NEXT-1391/error-invariant-expected-pagedata-to-be-a-string-for-app-data-request)</sub>

**Comment by certmates** [comment]
Seeing the same issue on, specifically for Google web crawling.

**TYPE: Serverless Function**

```
Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.
    at NextNodeServer.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/server/base-server.js:1013:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.renderPageComponent (/var/task/node_modules/next/dist/server/base-server.js:1072:24)
    at async NextNodeServer.renderToResponseImpl (/var/task/node_modules/next/dist/server/base-server.js:1098:32) {
  page: 'X'
}
RequestId: X Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by hk86** [comment]
I'm seeing this as well. Someone found the issue?

**Comment by ijjk** [comment]
Hi, can you please confirm this is still an issue in the latest version of Next.js `v13.4.3-canary.2`?

**Comment by certmates** [comment]
Hi @ijjk,

Sorry for the delay. New version broke some unrelated functions for me.

I previously had a ~90% fail rate on requesting Google indexing. I have tried 10 times since updating and it failed just once. I will monitor over the next days.

Thank you.

**Comment by rusted-love** [comment]
NextJs 13.4.13 
Still getting this error sometimes.
Deployment to Vercel.

Error occurs only for User Agent
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google-PageRenderer Google (+https://developers.google.com/+/web/snippet/)`

**Comment by llorenspujol** [comment]
@ijjk still happening with Next.js `v13.4.4`

**Comment by jmikrut** [comment]
For everyone else's visibility, we opened a Vercel help discussion here:

https://github.com/orgs/vercel/discussions/2677

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.4.5` of Next.js please update and give it a try!

**Comment by austintreneff** [comment]
Just a heads up here.. I was still experiencing the issue on `v13.4.5` but `v13.4.6` seems to have fixed it.

**Comment by francofantini** [comment]
Hi there, I'm still seeing these error logs in production using `v13.4.6`

>Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.
    at NextNodeServer.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/server/base-server.js:1274:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.renderPageComponent (/var/task/node_modules/next/dist/server/base-server.js:1333:24)
    at async NextNodeServer.renderToResponseImpl (/var/task/node_modules/next/dist/server/base-server.js:1365:32)
    at async NextNodeServer.pipeImpl (/var/task/node_modules/next/dist/server/base-server.js:641:25)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:1139:21)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:315:32)
    at async NextNodeServer.runImpl (/var/task/node_modules/next/dist/server/base-server.js:615:29)
    at async NextNodeServer.handleRequestImpl (/var/task/node_modules/next/dist/server/base-server.js:546:20) {
  page: '/categorias/lamparas'
}
RequestId: 065834d7-2433-4378-8637-e8b243f845c2 Error: Runtime exited with error: exit status 1
Runtime.ExitError

Anyone else?

**Comment by llorenspujol** [comment]
Same, still happening with v13.4.6.

I think we should re-open the issue.

**Comment by logansparlin** [comment]
This is happening for me on v13.4.7

**Comment by ijjk** [comment]
Can anyone reporting this is still occurring provide a deployment or repo with reproduction where they are seeing it?

The confirmed cases of this have all been resolved and are working properly in the latest version of Next.js

**Comment by steve-marmalade** [comment]
@ijjk , here is a deployment running `13.4.9-canary.2` where I am continuing to see this issue: https://web-rcvmm3c6s-marmalade.vercel.app/. The requested URL was https://www.marmalade.co/shop-small?exp=directS2

```
START RequestId: 6596f190-b28a-45a0-9805-72839a735556 Version: $LATEST
2023-07-06T20:08:18.518Z	6596f190-b28a-45a0-9805-72839a735556	ERROR	Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.
    at NextNodeServer.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/server/base-server.js:1289:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.renderPageComponent (/var/task/node_modules/next/dist/server/base-server.js:1348:24)
    at async NextNodeServer.renderToResponseImpl (/var/task/node_modules/next/dist/server/base-server.js:1380:32)
    at async NextNodeServer.pipeImpl (/var/task/node_modules/next/dist/server/base-server.js:641:25)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:1158:21)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:315:32)
    at async NextNodeServer.runImpl (/var/task/node_modules/next/dist/server/base-server.js:615:29)
    at async NextNodeServer.handleRequestImpl (/var/task/node_modules/next/dist/server/base-server.js:546:20) {
  page: '/%7B%22emailVerified%22%3Afalse%2C%22experiment%22%3A%22directS2%22%2C%22isLoggedIn%22%3Afalse%2C%22isWebview%22%3Afalse%7D/shop-small'
}
RequestId: 6596f190-b28a-45a0-9805-72839a735556 Error: Runtime exited without providing a reason
Runtime.ExitError
END RequestId: 6596f190-b28a-45a0-9805-72839a735556
REPORT RequestId: 6596f190-b28a-45a0-9805-72839a735556	Duration: 191.80 ms	Billed Duration: 192 ms	Memory Size: 1024 MB	Max Memory Used: 146 MB
```

The UserAgent making the request was Googlebot

```
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.179 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
```

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.4.10-canary.3` of Next.js, please update and give it a try!

**Comment by Galanthus** [comment]
> Hi, this has been updated in `v13.4.10-canary.3` of Next.js, please update and give it a try!

Still not working and returning the same error in production on Vercel. Tested on latest 3 versions.

**Comment by Galanthus** [comment]
> ### Verify canary release
> * [x]  I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> ```shell
> Operating System:
>       Platform: win32
>       Arch: x64
>       Version: Windows 10 Pro
>     Binaries:
>       Node: 16.19.0
>       npm: N/A
>       Yarn: N/A
>       pnpm: N/A
>     Relevant packages:
>       next: 13.2.4
>       eslint-config-next: 13.0.0
>       react: 18.2.0
>       react-dom: 18.2.0
> ```
> 
> ### Which area(s) of Next.js are affected? (leave empty if unsure)
> App directory (appDir: true), Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)
> 
> ### Link to the code that reproduces this issue
> I cannot reproduce it locally.
> 
> ### To Reproduce
> I don't know exactly how to reproduce it locally, it seems to happen only when deployed on Vercel.
> 
> ### Describe the Bug
> When executing a serverless function, I am getting the error `Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.` approximately 50% of the times. This error seems to happen only when deployed on vercel. I see the error just by checking the logs. It seems a bug in the cachedData, since this code is what is giving this error: https://github.com/vercel/next.js/pull/46204/files
> 
> Here is the Serverless execution success and fail chart by day, almost 50% fails due to this error. ![image](https://user-images.githubusercontent.com/18361241/229316007-cafa554f-213b-417b-9869-ea6714643dca.png)
> 
> Here is a full error example found in the "Logs":
> 
> ```
> 2023-04-01T22:34:02.255Z	undefined	INFO	info  - Loaded env from /var/task/.env.production
> Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.
>     at NextNodeServer.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/server/base-server.js:1013:27)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async NextNodeServer.renderPageComponent (/var/task/node_modules/next/dist/server/base-server.js:1072:24)
>     at async NextNodeServer.renderToResponseImpl (/var/task/node_modules/next/dist/server/base-server.js:1098:32) {
>   page: '/front-end-jobs-in-antwerp'
> }
> RequestId: 3193f9ce-3d2b-493d-b5f4-6d8c4c407b22 Error: Runtime exited with error: exit status 1
> Runtime.ExitError
> ```
> 
> ### Expected Behavior
> I expect the cache to work as expected and to have no errors in the serveless function executions. My external backend service , where the serverless function gets the data, does not fail, so the expected behaviour is that the serveless function gets the data and cache it as expected.
> 
> ### Which browser are you using? (if relevant)
> _No response_
> 
> ### How are you deploying your application? (if relevant)
> _No response_
> 
> [NEXT-1391](https://linear.app/vercel/issue/NEXT-1391/error-invariant-expected-pagedata-to-be-a-string-for-app-data-request)

Have you ever managed to solve this?

**Comment by BorisBarzotto** [comment]
Error occurs in 13.4.10 too

**Comment by TrustyTechSG** [comment]
Error occurs in 13.4.13.

**Comment by TrustyTechSG** [comment]
> Error occurs in 13.4.13. randomly see error below from vercel log.
> 
> `Error: invariant: Expected pageData to be a string for app data request but received undefined. This is a bug in Next.js.`

Just found out in my case, this error only happen when opening the site in puppeteer.
