### ISSUE TITLE
[WEB-968] [turbopack] next/font not working in a dockerized environment 

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#47802]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

next/font utility is causing issues in docker environments:

```bash
warning -
  [fetch]
    [next]/internal/font/google/plus_jakarta_sans_3fefeabb.module.css
      Error while requesting resource
      There was an issue establishing a connection while requesting https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200..800&display=swap.
```

and in reality this is been stored in .next folder under .next/server/pages/fallback_not_found folder

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Turbopack (--turbo)

### Link to the code that reproduces this issue

no response

### To Reproduce

no response

### Describe the Bug

no response

### Expected Behavior

no response

<sub>[WEB-968](https://linear.app/vercel/issue/NEXT-1066/[turbopack]-nextfont-not-working-in-a-dockerized-environment)</sub>

**Comment by joacub** [comment]
update in the error:

```js
warning - [fetch] [next]/internal/font/google/plus_jakarta_sans_3fefeabb.module.css  Error while requesting resource
  There was an issue establishing a connection while requesting https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200..800&display=swap.
  
  | error sending request for url (https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@200..800&display=swap): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

**Comment by sspenst** [comment]
Having a similar issue but I'm only seeing it locally. I don't have a fetch error but I was able to fix my issue by changing

`export const rubik = Rubik({ display: 'swap', subsets: ['latin'] });`

to

`export const rubik = Rubik({ display: 'swap', subsets: ['latin'], fallback: [] });`

**Comment by joacub** [comment]
> Having a similar issue but I'm only seeing it locally. I don't have a fetch error but I was able to fix my issue by changing
> 
> `export const rubik = Rubik({ display: 'swap', subsets: ['latin'] });`
> 
> to
> 
> `export const rubik = Rubik({ display: 'swap', subsets: ['latin'], fallback: [] });`

you may see only locally as this is a turbo pack related issue, webpack works correctly, and the production builds are been get done by webpack yet.
btw your solution didn't work for me, did you see any other workaround ?

**Comment by sspenst** [comment]
> you may see only locally as this is a turbo pack related issue, webpack works correctly, and the production builds are been get done by webpack yet. btw your solution didn't work for me, did you see any other workaround ?

I realized I was running an outdated docker build which was causing some strange issue with the font, so deleting all the containers and rebuilding fixed my issue. Sorry I can't be of more help!

**Comment by joacub** [comment]
So you are able to use the fonts ?

**Comment by ForsakenHarmony** [comment]
@joacub @sspenst is this happening to you with next.js 14 / the latest canary?

**Comment by ForsakenHarmony** [comment]
going to close this for now, if you're still running into this, please open a new issue with a reproduction case
