### ISSUE TITLE
Next 13 STATIC EXPORT Not Working | No OUT Folder

### ISSUE THREAD

**Issue by TilP** [vercel/next.js#47808]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64
    Binaries:
      Node: 19.8.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://beta.nextjs.org/docs/configuring/static-export

### To Reproduce

Update next.config.js with `output: 'export'` .  Run `next build `.  experimental.appDir is set to true.

### Describe the Bug

Unable to product export out folder as described in https://beta.nextjs.org/docs/configuring/static-export

### Expected Behavior

.next/build should contain an out folder.  .next/build does not exist as well after implementing above.

**Comment by SukkaW** [comment]
Here I quote from the documentation page you have mentioned:

> Note: Support for static exports is currently only available on `next@canary`. This will be included in Next.js 13.3 shortly.

**Comment by TilP** [comment]
Sorry, missed that.  But, thanks.
