### ISSUE TITLE
Docs: Does `router.refresh()` refresh invalidate all cached pages or just the currently opened

### ISSUE THREAD

**Issue by jeengbe** [vercel/next.js#47812]
### What is the improvement or update you wish to see?

On https://beta.nextjs.org/docs/api-reference/use-router#userouter, its description is _Refresh the current route and fetch new data from the server._ On https://beta.nextjs.org/docs/routing/linking-and-navigating#invalidating-the-cache, however, we see _The cache can be invalidated using `router.refresh()`_, which sounds a lot more like invalidating _all_ cached pages.

### Is there any context that might help us understand?

I was searching for a way to invalidate all cached soft navigation after a user logs in. The docs don't make clear whether this is the method I require.

**Comment by RotaruAndrei1998** [comment]
@jeengbe  I have the same issue, on soft navigation, the cache is still preserved after router.refresh().  The server component it's not rendered on the server, and it has stale data. I am curious about how to fix this.

**Comment by IGassmann** [comment]
As far as I know, it only refreshes the data for the currently rendered route. If you need to invalidate the whole client-side cache after a user signs out, you can use this workaround made by @clerkinc : https://github.com/clerkinc/javascript/blob/712c8ea792693a335d9bf39c28e550216cb71bcb/packages/nextjs/src/client/invalidateNextRouterCache.ts

**Comment by multiwebinc** [comment]
It doesn't seem to be invalidating the cache on the current page for me when I call `router.refresh()` (Next 13.4.1). Even if I push F5, it still pulls the cached data. Only if I do `Ctrl-F5` does it fetch the new data. So I need to do `cache: "no-store"` on the original request, which is also not what I want.

**Comment by FengeRVictor** [comment]
That would be great to have a function that invalidate all the router cache ! :D

**Comment by adarsh-drishya** [comment]
did you find and workaround? i am trying to refetch the data on the server component by click on client component button. also i want fetch to work

**Comment by leerob** [comment]
We've improved the docs here: https://nextjs.org/docs/app/building-your-application/caching
