### ISSUE TITLE
Dev compiling is stuck

### ISSUE THREAD

**Issue by sanjarbek-ismatov** [vercel/next.js#47821]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.2.4", newest: "13.2.5-canary.26".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.  
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

.

### To Reproduce

![Снимок экрана (28)](https://user-images.githubusercontent.com/65501439/229361868-654d2984-1d91-414f-aa9d-b7b328aba761.png)

### Describe the Bug

in enabled app directory next js app, if i start development mode, compiler is stuck (npm run dev). Showing message: wait  - compiling /page (client and server)... . Sometime works, sometimes doesn't work.

### Expected Behavior

Only it's work

### Which browser are you using? (if relevant)

Chrome latest

### How are you deploying your application? (if relevant)

next start

**Comment by tavurth** [comment]
For me it was `"next": "canary"` that was causing a new similar bug just now.

Reverting to `"next": "13.2.4"` fixed it for me.

**Comment by joacub** [comment]
> For me it was `"next": "canary"` that was causing a new similar bug just now.
> 
> Reverting to `"next": "13.2.4"` fixed it for me.

Hi is using that version already, try installing latest canary version …27 will probably resolve.

**Comment by superssingh** [comment]
To solve this issue, just install latest version 13.2.5-canary.27. Type like this in terminal -  npm install next@13.2.5-canary.27
that's it.

**Comment by yachtcareerhub** [comment]
> npm install next@13.2.5-canary.27

Have been having the same issue for the last few days. Installing the latest version doesn't fix it for me.

**Comment by rahulps1000** [comment]
Hi, I am also having the same issue with canary.31 as well. If you have any solution please let me know.

**Comment by sanjarbek-ismatov** [comment]
If this bug show, try next@latest (in me, it's fixing for a short time)

**Comment by rahulps1000** [comment]
> If this bug show, try next@latest (in me, it's fixing for a short time)

Hi @sanjarbek-ismatov , 

I have tried this step and it not working for me.
If you have any other suggestion that might fix the issue please let me know.

Thanks,
Rahul

**Comment by sanjarbek-ismatov** [comment]
> 

No. I know. But when I open localhost:3000 it shows error

**Comment by sanjarbek-ismatov** [comment]
> I found that we need to open http://localhost:3000/ it in any of the browser for the rest of the compilation to work.
> 
> please try ot out and close this issue if it got resolved.
No. I know. But when I open localhost:3000 it shows error

**Comment by yachtcareerhub** [comment]
So this is what's working for me now. I've added `--turbo` flag to `scripts.dev` in `package.json`.

```
{
  "scripts": {
    "dev": "next dev --turbo",
    ...
  },
  ...
}
```

So far `npm run build` is still not compiling on my computer but at least it's working in the Bitbucket pipelines. Would be perfect if I would be able to build it locally as well.

**Comment by CreatorLZ** [comment]
i'm having this error too!. seems almost everyone is having this same error. is there a sure fix?

**Comment by bsheratlumi** [comment]
In my experience, starting `http://localhost:3000/`, or your port, is necessary for Next.js to finish compiling

**Comment by KimCCode** [comment]
Yep opening http://localhost:3000 worked for me as well

**Comment by BongBongBang** [comment]
Same situation...
Next version: 14.0.4-canary.17
I found this only occurs for windows, not for Mac , for me at least.
Solution: use 'next dev' not 'next dev  --turbo'. close the turbopack.

**Comment by kallezz** [comment]
Had this problem on 14.1.0, what [yachtcareerhub](https://github.com/yachtcareerhub) posted, using the turbo flag fixes it.

**Comment by ty-codes** [comment]
> Had this problem on 14.1.0, what [yachtcareerhub](https://github.com/yachtcareerhub) posted, using the turbo flag fixes it.

Currently have this issue on 14.1.0

**Comment by bernii** [comment]
same problems with 14.1.0/14.1.1 and latest canary
compilation hangs when I try to access any app-router based page (typescript 5.3.3)

**Comment by metacop** [comment]
> i'm having this error too!. seems almost everyone is having this same error. is there a sure fix?
Did you find a solution?

**Comment by metacop** [comment]
> i'm having this error too!. seems almost everyone is having this same error. is there a sure fix?

Did you find a solution?

**Comment by kristiegiles** [comment]
> > having the same issue - `"next": "^14.1.4"` with `next@canary` installed
> 
> my problem was tailwind config.

how did you fix it?

**Comment by metacop** [comment]
> > > having the same issue - `"next": "^14.1.4"` with `next@canary` installed
> > 
> > 
> > my problem was tailwind config.
> 
> how did you fix it?

Yes, it is related to CSS.

1.   first check the globalss.css
2.   tailwind.config.ts

`/** @type {import('tailwindcss').Config} */
import withMT from '@material-tailwind/react/utils/withMT';
const config = withMT({
	content: [
		'./src/auth/components/FormLogin.tsx',
		// './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/components/**/*.{js,ts,jsx,tsx,mdx}',
		// './src/app/**/**/*.{js,ts,jsx,tsx,mdx}',
		// './src/app/**/*.{js,ts,jsx,tsx,mdx}',
		// './src/app/**/**/*.{js,ts,jsx,tsx,mdx}',

		'./src/**/**/*.{js,ts,jsx,tsx,mdx}',
		'./**/**/**/**/*.{js,ts,jsx,tsx,mdx}',
		// './src/app/login/*.{js,ts,jsx,tsx,mdx}',
	],

	theme: {
		extend: {},
	},
	plugins: [],
});

export default config;`

**Comment by navanshu** [comment]
Same issue here using next 14.2.3 and tailwind 3.4.3, even turbo doesn't fixes it

**Comment by timneutkens** [comment]
In order to help me investigate this I'll ideally need an application that can be run, if you can't provide that (I understand if you can't) please provide the `.next/trace` file.

If possible follow these steps which would give me the best picture to investigate:

* `npm install next@canary` (use the package manager you're using) -- We want to make sure you're using the very latest version of Next.js which includes the fixes mentioned earlier.
* `rm -rf .next`
* start development using the `NEXT_CPU_PROF=1` and `NEXT_TURBOPACK_TRACING=1` (regardless of if you're using Turbopack, it only affects when you do use Turbopack) environment variable.  E.g.:
  * npm:  `NEXT_TURBOPACK_TRACING=1 NEXT_CPU_PROF=1 npm run dev`
  * yarn:  `NEXT_TURBOPACK_TRACING=1 NEXT_CPU_PROF=1 yarn dev`
  * pnpm: `NEXT_TURBOPACK_TRACING=1 NEXT_CPU_PROF=1 pnpm dev`
* Wait a few seconds
* Open a page that you're working on
* Wait till it's fully loaded
* Wait a few seconds
* Make an edit to a file that holds a component that is on the page
* Wait for the edit to apply
* Wait a few seconds
* Make another edit to the same file
* Wait a few seconds
* Exit the dev command (`ctrl+c`)
* Upload the CPU traces put in the root of the application directory to [https://gist.github.com](https://gist.github.com)
* Upload the `.next/trace` file to [https://gist.github.com](https://gist.github.com) -- Please **don't** run trace-to-tree yourself, as I use some other tools (e.g. Jaeger) that require the actual trace file.
* If you're using Turbopack upload the `.next/trace.log` as well, if it's too large for GitHub gists you can upload it to Google Drive or Dropbox and share it through that.
* Upload `next.config.js` (if you have one) to  [https://gist.github.com](https://gist.github.com)
* Share it here

**Comment by ADTC** [comment]
Having issue with Next.js `14.2.3` as well. I don't have Tailwind or Turbo. A restart of the server _sometimes_ fixes it, but there's no guarantee. I am on macOS Sonoma, in Apple Silicon, if that matters.

**Comment by tseijp** [comment]
> Having issue with Next.js `14.2.3` as well. I don't have Tailwind or Turbo. A restart of the server _sometimes_ fixes it, but there's no guarantee. I am on macOS Sonoma, in Apple Silicon, if that matters.

same (; _ ;)

**Comment by auspy** [comment]
had issue in tailwind config. i had change path from entire dir to some specific dir. old - not working path: `"./node_modules/lib_name/**/*.{js,ts,jsx,tsx}",`
working path:  `"./node_modules/lib_name/**/*.{js,ts,jsx,tsx}",`

**Comment by auspy** [comment]
had issue in tailwind config. i had change path from entire dir to some specific dir. old - not working path: `"./node_modules/lib_name/**/*.{js,ts,jsx,tsx}",`
working path:  `"./node_modules/lib_name/dist/**/*.{js,ts,jsx,tsx}",`

**Comment by MohamedBechirMejri** [comment]
my issue was tailwind config. I was migrating from pages router to app router and I think the old config  was scanning node_modules which resulted in compilation seeming stuck. 

if you're not using tailwind make sure another lib isn't doing the same thing 
![image](https://github.com/user-attachments/assets/5d1b52cc-f100-45a7-979b-36c27a50d0a8)

**Comment by KinanGH98** [comment]
In my case, disabling the VPN did the trick.

**Comment by timneutkens** [comment]
I'm going to close this issue as there hasn't been new reports with actionable traces and some people figured out it was other tools in use causing slowdowns.
