### ISSUE TITLE
Docs: useRouter() forceOptimisticNavigation is missing

### ISSUE THREAD

**Issue by rainyEra** [vercel/next.js#47894]
### What is the improvement or update you wish to see?

Add forceOptimisticNavigation to the docs in a useRouter section.

### Is there any context that might help us understand?

No.

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/use-router

**Comment by balazsorban44** [comment]
It's an internal API, hence it's undocumented. It's not meant to be used by the end user.
