### ISSUE TITLE
static assets conflict with public/static

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#47919]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fassets%2Fa10e35c88c373249.png&w=3840&q=75
```
return a 404 seems like have conflict with existing folder in public/static/

this does not happen with Webpack is turbo pack related issue or maybe app/dir

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

no response

### To Reproduce

no response

### Describe the Bug

no response

### Expected Behavior

no response

### Which browser are you using? (if relevant)

no response

### How are you deploying your application? (if relevant)

no response

**Comment by joacub** [comment]
Any plan on this, next/image is not working in turbopack

**Comment by panieldark** [comment]
Cmon guys, any progress? This is a pretty important feature advertised in Next13
