### ISSUE TITLE
Disapointed

### ISSUE THREAD

**Issue by allestaire** [vercel/next.js#47943]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Create suggest to use Next.js, for developer who likes SSG,
And then here I come, having problem with document when building.
Creating static build instead of SSR.
Documentation also not clear, having no specific or straight to the point information on how should it works.

We still love the react library, it should not be inside a framework.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

We still love the react library, it should not be inside a framework.

### To Reproduce

We still love the react library, it should not be inside a framework.

### Describe the Bug

We still love the react library, it should not be inside a framework.

### Expected Behavior

We still love the react library, it should not be inside a framework.

**Comment by allestaire** [comment]
Too many complication when building little app. tsk tsk

**Comment by allestaire** [comment]
Note, if you have a required package using document on browser, well goodluck with that.
Can build my project

**Comment by ijjk** [comment]
Hi, if you can provide more specifics with the issues you are running into we can investigate more, if you are needing general help please open a discussion!

**Comment by allestaire** [comment]
Sorry just ranting, I am so stressed because on the new environment.
Already fixed the issue regarding on build, it seems like I have to change version from 'next@13.2.5` to `next@13.2.4@canary.30`

**Comment by allestaire** [comment]
Currently my issue is to change `_next` folder to remove underscore, but it seems like there are no options in doing that, currently searching for any solution as of now

- Thanks by the way
