### ISSUE TITLE
Docs: CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Cedar-81** [vercel/next.js#47950]
### What is the improvement or update you wish to see?

![image](https://user-images.githubusercontent.com/64336732/230016006-5958bd74-8af9-4386-8764-1fb3155536fb.png)

I think modifying the first line under the enforcement section to "Instances of abuse, harassment, or otherwise unacceptable behaviour may be..." would make it even more readable and easily understandable.

### Is there any context that might help us understand?

It makes it clear and readable as I found it a little hard to understand initially. Also, I would like to make that change as a go as an initial contribution to the Nextjs framework, it it's fine by y'all.

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/blob/canary/CODE_OF_CONDUCT.md

**Comment by timneutkens** [comment]
This document is based on the official contributors covenant code of conduct, it's intended to be included in the repository as-is: https://www.contributor-covenant.org/version/2/1/code_of_conduct/, you could contribute to that document and it would naturally flow back into many open source projects that use this code of conduct.
