### ISSUE TITLE
when I access the parent segment that returns notFound and then access a child segment that changes the URL (segment), it does not render the UI of the child segment and keeps the UI of the parent segment.

### ISSUE THREAD

**Issue by brunorguerra** [vercel/next.js#47964]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.30
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/github/brunorguerra/nextjs-report-bug-navigation/main?workspace=%257B%2522activeFilepath%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clg3qyyqt000x356h7tgl526w%2522%253A%257B%2522key%2522%253A%2522clg3qyyqt000x356h7tgl526w%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A46371%252C%2522key%2522%253A%2522clg3razxn006s356hxc23jf7m%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252FpostList%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clg3ray0d002o356hzbrb11wz%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clg3qyyqt000x356h7tgl526w%2522%252C%2522spacesOrder%2522%253A%255B%2522clg3qyyqt000x356h7tgl526w%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### To Reproduce

This is the home page, access the PostList link, to access the postList page interface.
![image](https://user-images.githubusercontent.com/79162247/230109090-c16f7319-cad1-4f87-9809-a37aded7f73d.png)

I configured it to return notFound when accessing this specific segment (/postList). however, the postList directory does not have a special not-found.tsx file, so it will return the not-found.tsx file that is in the root of the /app project.
![image](https://user-images.githubusercontent.com/79162247/230109807-d7f86aa8-603a-4e65-8690-f3ed3ab5f162.png)

Access the Link PostList of the layout which will return notFound then access the Link Post of the layout.
![image](https://user-images.githubusercontent.com/79162247/230112051-b9a65e15-3069-4856-8c99-5e3aa5143928.png)
Note: It must occur in this order: access Link PostList then Link Post for the problem to occur

### Describe the Bug

I have two Link Components in a RootLayout in the app directory, one that directs my path to the /postList segment and the other to /postList/post

However, when I first access the postList which returns notFound and then access the post it remains in the notFound interface of the parent segment (/postList) and does not return the interface of the child segment (/postList/post). This occurs when I don't have a special not-found.tsx file for the parent segment and it fetches not-found.tsx from the root directory.

I tested this same step by step but containing a special file for not-found.tsx in the parent segment and it worked normally.

Note: when I access /postList then /postList/post it maintains the content of the parent segment (/postList), however, if I access the homepage (/) and directly access the Link Post (/postList/post) without accessing the Link PostList before, it normally returns the content of the child segment.

### Expected Behavior

I expected the same behavior to happen as I have when I have a not-found.tsx for the parent thread, it renders its children.

### Which browser are you using? (if relevant)

Brave 1.49.132

### How are you deploying your application? (if relevant)

localhost

**Comment by karlhorky** [comment]
Is this still happening? When making a branch on your CodeSandbox demo above, I don't see the behavior you described 

However, I'm not sure I understand your instructions above - maybe you could edit your description to make them clearer

Here's the branch:

https://codesandbox.io/p/github/brunorguerra/nextjs-report-bug-navigation/csb-j8oiv5/draft/vigorous-wave

**Comment by brunorguerra** [comment]
Apparently the problem has already been solved.
