### ISSUE TITLE
Custom webpack config is not called in next/jest

### ISSUE THREAD

**Issue by luixo** [vercel/next.js#47974]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 9.6.0
      Yarn: 1.22.19
      pnpm: 7.12.2
    Relevant packages:
      next: 13.2.5-canary.30
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue

https://github.com/luixo/svg-build-case

### To Reproduce

1. `npx create-next-app --ts --example with-jest <name>`
2. `npm -D @svgr/webpack`
3. Add SVG icon on the page that is included in tests
4. `npx jest`

Additionaly, I investigated that custom `webpack` function is not called in jest environment (though `next/jest` package is used).
To verify that I added loggin to file `log.txt`: 
- `header` on `next.config.js` evaluation
- `timestamp` on webpack custom config evaluation.
While building app with `npm run build` one can see header and 3 timestamps are added.
While running `npx jest` one can see only header added.

### Describe the Bug

```
 FAIL  __tests__/index.test.tsx
  ● Console

    console.error
      Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

      Check the render method of `Home`.
          at Home

      17 |           Welcome to <a href="https://nextjs.org">Next.js!</a>
      18 |         </h1>
    > 19 |         <Icon />
         |         ^
      20 |
      21 |         <p className={styles.description}>
      22 |           Get started by editing <code>pages/index.js</code>
```

### Expected Behavior

No errors

**Comment by ClementDreptin** [comment]
Hey, I'm still experiencing this issue with next@14.2.0-canary.63 and I don't know how to fix. Any chance this could be investigated? Or provide a workaround maybe?

**Comment by ClementDreptin** [comment]
I just found a fix for anyone who would come across this issue. Jest not being able to resolve the import paths for SVGs when using SVGR can be fixed my mocking the SVG imports and using a `moduleNameMapper`. This is explained in the [Jest documentation](https://jestjs.io/docs/webpack#handling-static-assets).

If you configured SVGR to work alongside next-image-loader, you most likely have a way to specify what loader you want to use depending on the import path. In my case, I configured webpack to use SVGR when the import path ends with ".svg?svgr". If you did the same, all you have to do is modify `jest.config.ts` like so
```TS
const config = {
  // ... rest of you config
  moduleNameMapper: {
    // ... your potential other mappers
    "^.+\\.svg\\?svgr$": "somewhere/svgFileMock.ts",
  },
};
```
and create an `svgFileMock.ts` that exports an empty function like so
```TS
export default function svgFileMock() {}
```

Hope it helps anyone!

**Comment by timneutkens** [comment]
`next/jest` does not run webpack, it only adds some transforms for the files using SWC.
