### ISSUE TITLE
Docs: Space or line break doesn't work in feedback window

### ISSUE THREAD

**Issue by ATK3Shape** [vercel/next.js#48008]
### What is the improvement or update you wish to see?

Update would be to fix the bug in feedback window to allow using space and line break.

![image](https://user-images.githubusercontent.com/24272528/230305010-056701d6-9458-4696-80f4-51238e508cc7.png)

### Is there any context that might help us understand?

No

**Comment by sumitshinde-84** [comment]
i am working on that issue

**Comment by sumitshinde-84** [comment]
i am unable to find code or component of that form can anyone help

**Comment by jhylacey** [comment]
Having the same isssue

**Comment by leerob** [comment]
Fixed!
