### ISSUE TITLE
Nextjs webpack build  hot reload error - hot-reloader-client.tsx 

### ISSUE THREAD

**Issue by Yard-Daniel** [vercel/next.js#48030]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Tested versions:
next@13.1.0
next@13.1.6
next@13.2.4
next@13.2.5-canary.32
```

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-chqhja?file=app%2Fpage.tsx

### To Reproduce

Setup turbo monorepo with a nextjs13 project.

`pnpm dev`

The error mostly occurs and seldom disappears, because of the hot.module (not sure what triggers).

It fails in the nextjs13 webpack bundle.

### Describe the Bug

```bash
error - uncaughtException: TypeError: Cannot read properties of undefined (reading 'length')
cfolio:dev:     at WasmHash._updateWithBuffer (/Users/bob/dev/nextjs13/node_modules/.pnpm/next@13.2.4_z72xxk7vwlamvgqemvc4ptm4du/node_modules/next/dist/compiled/webpack/bundle5.js:28:1352524)
```

file: packages/next/src/client/components/react-dev-overlay/hot-reloader-client.tsx
line: 153

// current
const hasUpdates = Boolean(updatedModules.leng
<img width="1792" alt="Screenshot 2023-04-06 at 17 40 34" src="https://user-images.githubusercontent.com/73103852/230429405-e5cc2b2e-8b21-44db-87e9-18ea4ca1b217.png">
th)

// should be
 const hasUpdates = Boolean(updatedModules && updatedModules.length)

// because error
Boolean(null.length) // TypeError: Cannot read properties of null (reading 'length') obviously.

### Expected Behavior

To run `pnpm dev` without issues from the nextjs13 build.

**Comment by shuding** [comment]
I think this should have been fixed in the latest codebase, as we check `!updatedModules` here so it can't be `null` or `undefined` in the place you pointed out:

https://github.com/vercel/next.js/blob/eba1626b459504c8ef87a78b7dc8afaa7c6c591b/packages/next/src/client/components/react-dev-overlay/hot-reloader-client.tsx#L134-L151

Let us know if you still see it in the latest canary, thanks.
