### ISSUE TITLE
Static Export (with-static-export) example doesn't output files

### ISSUE THREAD

**Issue by ivoiv** [vercel/next.js#48034]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-static-export

### Describe the Bug

https://nextjs.org/docs/advanced-features/static-html-export
npm run build doesn't output anything in the example

### Expected Behavior

An /out folder with exported files in it

### To Reproduce

Clone repo
Install
Run build

**Comment by wwwdepot** [comment]
install `next:canary` to try out the new export configuration

**Comment by ivoiv** [comment]
13.3 was released where this actually works.
