### ISSUE TITLE
Docs: API Routes Request Helpers

### ISSUE THREAD

**Issue by ghost** [vercel/next.js#48037]
### What is the improvement or update you wish to see?

```
req.body - An object containing the body parsed by content-type, or null if no body was sent
```
Please, add more details on what exactly this means. Also, the typescript type for `body` being `any` doesn't help. No offence, but I'm really disappointed that a 100K stars framework makes it so hard to handle requests.

### Is there any context that might help us understand?

```ts
import {NextApiRequest, NextApiResponse} from "next";

export default async function handler(request: NextApiRequest, response: NextApiResponse) {
    const body = request.body;

    // what to do???
}
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/api-routes/request-helpers

**Comment by leerob** [comment]
We're open to community contributions here if you'd like to make this more clear 🙏 Thank you for the suggestion.
