### ISSUE TITLE
Docs: Fix spelling error in example problem 

### ISSUE THREAD

**Issue by seriouscatsoserious** [vercel/next.js#48053]
### What is the improvement or update you wish to see?

![image](https://user-images.githubusercontent.com/121734574/230522788-a3f96cbd-2301-4595-aa30-878f04cf6ee1.png)

As depicted in the image, the answer listed as choice A has a spelling error. It says knit the dough, where it should say knead the dough. 

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/from-javascript-to-react/updating-ui-with-javascript

**Comment by shaikahmadnawaz** [comment]
Shall I start working on this issue? Please assign me

**Comment by shaikahmadnawaz** [comment]
I'm ready to work on the issue, please assign this issue to me
