### ISSUE TITLE
Docs: Fix confusing grammar

### ISSUE THREAD

**Issue by superdevjr** [vercel/next.js#48054]
### What is the improvement or update you wish to see?

There's an instance of strange grammar in the linked article. I'll put it here and also put my suggested edit, denoted by bold text.

"This modularity allows your code to be more maintainable as it grows because you can easily add, update, and delete components without touching the rest of our application."

"This modularity allows your code to be more maintainable as it grows because you can easily add, update, and delete components without touching the rest of **your** application."

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/from-javascript-to-react/building-ui-with-components

**Comment by leerob** [comment]
Thanks for the suggestion, but I'm okay with keeping it is as 🙏
