### ISSUE TITLE
v13.3.0 getStaticPaths Fails with error - Error: Call retries were exceeded

### ISSUE THREAD

**Issue by rnantes** [vercel/next.js#48061]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.8.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.0
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/

### To Reproduce
```Typescript
export const getStaticPaths: GetStaticPaths = async () => {
    const mySlugs = await getMySlugs(); // returns a array of ~2500 strings 

    var paths = mySlugs.map(s => {
      return {
        params: { slug: s }
      };
    })

    var res = { paths: paths, fallback: false };
    return res;
}
```

### Describe the Bug

The get request `await getMySlugs();` to get my slugs works fine, but I Get this error:

```
error - Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/Users/re/abc/my-proj/node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (/Users/re/abc/my-proj/node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:512:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  digest: undefined
}
```

### Expected Behavior

getStaticPaths should not throw an error because `await getMySlugs();` returns fine. I should see the page available. It works in 12.5.4

**Comment by verekia** [comment]
I didn't get those errors on `13.2.5-canary.22`, but now I have them on `13.3.0`.

**Comment by cengo** [comment]
I upgraded my next version from `12.1.0` to `13.3.0` and started to get this error.

**Comment by DrMint** [comment]
Same problem here after upgrading from `13.2.4` to `13.2.5`

**Comment by hajjarjoseph** [comment]
The same is happening on my side on `13.3.0`.

```
export const getStaticPaths: GetStaticPaths = async () =>
  getStaticPathForService();
```

`getStaticPathForService` returns a Promise

**Comment by AndreiAyar** [comment]
It seems to be an issue on 13.3.0, as I also get this error.

**Comment by AbdullahDiaa** [comment]
Same issue here with 13.3.0
```
error - Error: Call retries were exceeded
    at ChildProcessWorker.initialize (node_modules/next/dist/compiled/jest-worker/index.js:1:11661)
    at ChildProcessWorker._onExit (node_modules/next/dist/compiled/jest-worker/index.js:1:12599)
    at ChildProcess.emit (node:events:512:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  digest: undefined
```

**Comment by wadehammes** [comment]
Same issue on my end

**Comment by 7iomka** [comment]
Any news?

**Comment by DrMint** [comment]
If anyone needs a patch, here one I've made using `patch-package`.
1. Extract the archive at the root of your project (should create a `patches` folder)
2. Install patch-package: `npm i patch-package`
3. In package.json add the postinstall script:
    ```diff
     "scripts": {
    +  "postinstall": "patch-package"
     }
    ```
4. Rerun `npm i` to trigger the postinstall script. You should see the patch being applied in the console:
    ```
    Applying patches...
    next@13.3.0 ✔
    ```
If you're curious what the patch is all about, it's just reverting the changing made to `packages/next/src/server/dev/static-paths-worker.ts` (see my [previous message](https://github.com/vercel/next.js/issues/48061#issuecomment-1501074956) above). You can create the patch yourself by:
1. installing Next v13.2.4 
2. copying `packages/next/src/server/dev/static-paths-worker.ts`
3. installing Next v13.3.0 and replacing `packages/next/src/server/dev/static-paths-worker.ts` with the copied version.
4. Install patch-package: `npm i patch-package`
5. In package.json add the postinstall script:
    ```diff
     "scripts": {
    +  "postinstall": "patch-package"
     }
    ```
6. Create a patch using: `npx patch-package next`
7. The patch is now created in the `patches` folder at the root of your project.
[patches.zip](https://github.com/vercel/next.js/files/11218357/patches.zip)

**Comment by rnantes** [comment]
Seems to be fixed for me in in release [13.3.1-canary.7](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.7) thank you ijjk!

**Comment by nfts2me** [comment]
Also having this same error since 13.3.0

**Comment by j4p3** [comment]
:point_up: Seeing this error output on a freshly created next `13.3.1` project - on the dev server, not in production - with the full error:

```
error - Error: [object Response]
    at getProperError (my_project/node_modules/next/dist/lib/is-error.js:37:12)
    at DevServer.renderToResponseImpl (my_project/node_modules/next/dist/server/base-server.js:1338:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.pipeImpl (my_project/node_modules/next/dist/server/base-server.js:625:25)
    at async Object.fn (my_project/node_modules/next/dist/server/next-server.js:1130:21)
    at async Router.execute (my_project/node_modules/next/dist/server/router.js:311:32)
    at async DevServer.runImpl (my_project/node_modules/next/dist/server/base-server.js:599:29)
    at async DevServer.run (my_project/node_modules/next/dist/server/dev/next-dev-server.js:922:20)
    at async DevServer.handleRequestImpl (my_project/node_modules/next/dist/server/base-server.js:528:20) {
  digest: undefined
  }
  ```

This does not occur on a route which renders a static string, but does occur on a route which uses `getServerSideProps`.

**Comment by jagilley** [comment]
I'm getting the same error as @j4p3. Tested on next==13.2.3 and next==13.4.4. I didn't change anything, the dev server seems to have spontaneously decided to stop working

**Comment by petya0927** [comment]
I'm on `13.4.5`, same issue for me. Any updates with this?
