### ISSUE TITLE
Image not working on production

### ISSUE THREAD

**Issue by muhammedogz** [vercel/next.js#48077]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 16.15.0
      npm: 8.18.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image), Jest (next/jest)

### Link to the code that reproduces this issue

https://github.com/muhammedogz/next-image-error

### To Reproduce

`npx create-next-app@latest`
after created
update next-config
```ts
/**
 * @type {import('next').NextConfig}
 **/

const config = {
  images: {
    domains: ["avatars.githubusercontent.com"],
  },
  output: "standalone",
  reactStrictMode: false,
};

module.exports = config;
```
use this docker file
```
# Install dependencies only when needed
FROM node:16-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json ./ 

RUN npm i --legacy-peer-deps

# Rebuild the source code only when needed
FROM node:16-alpine AS builder

ENV NEXT_TELEMETRY_DISABLED 1

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

# Production image, copy all the files and run next
FROM node:16-alpine AS runner

ENV NEXT_TELEMETRY_DISABLED 1
ENV PORT 3000

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENTRYPOINT ["node", "server.js"]
```
modify index.ts
```ts
import Image from "next/image";

export default function Home() {
  return (
    <div>
      test
      <Image
        alt="test"
        src={"https://avatars.githubusercontent.com/u/14985020?s=200&v=4"}
        width={100}
        height={100}
      />
    </div>
  );
}
```

After that, run docker commands in the root of the project
```
docker build .
docker run -dp 3000:3000 <image-id>
```
Locate to the http://localhost:3000/
image is not shown.

Helpfull info
Docker Logs output
```
Error: Cannot find module 'next/dist/compiled/jest-worker'
Require stack:
- /app/node_modules/next/dist/server/lib/squoosh/main.js
- /app/node_modules/next/dist/server/image-optimizer.js
- /app/node_modules/next/dist/server/next-server.js
- /app/server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/app/node_modules/next/dist/server/lib/squoosh/main.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/lib/squoosh/main.js',
    '/app/node_modules/next/dist/server/image-optimizer.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/server.js'
  ]
}
```

### Describe the Bug

Images are not shown. Server sending 500 for images.
Exact same docker file and exact same project working yesterday. I tried it with different nextjs versions.

### Expected Behavior

Show the images without error

### How are you deploying your application? (if relevant)

Dockarized and deploy to the AWS

**Comment by huseyinsarsilmaz** [comment]
Oh thanks bro, I've been looking forward for this for sooo many time, you're great !

**Comment by muhammedogz** [comment]
I tested it with those versions and it is working. Above versions seems broken unfortunatelly
```
"next": "13.2.4",
"eslint-config-next": "13.2.4"
```

**Comment by reducio** [comment]
I have a same problem. ```standalone``` mode working nice only ```"next": "13.2.4"```. In other cases the Image component doesn't get correct image url.

**Comment by stackrus** [comment]
same

**Comment by Gosev** [comment]
The same issue shows up using 13.3.0 on AWS Amplify (which deploys using docker)

**Comment by timruiterkamp** [comment]
I have encountered the same issue as stated above. There is a **very bad** workaround, which is to turn the optimization off for next/image in the next.config.js until the problem is fixed. The images will show up again, but you have lost the srcset generation and other benefits, so downgrading to 13.2.4 is the better solution.

**Comment by luisjorge129** [comment]
I can confirm I am having this issue after upgrading to next 13.3.0 using amplify (it does not happens locally only when is up on amplify), it does gets resolve if I disable image optimization (which then you lose the sweet optimization for images) and it also gets fixed downgrading back to next 13.2.4.

**Comment by 7iomka** [comment]
I haven't seen as many breaking changes as in 13.3 in a long time :(

**Comment by shahram0102** [comment]
> Temporary workaround
> 
> ```
> COPY --from=builder /app/next.config.js ./
> COPY --from=builder /app/public ./public
> COPY --from=builder /app/package.json ./package.json
> COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
> COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
> + COPY --from=builder /app/node_modules/next/dist/compiled/jest-worker ./node_modules/next/dist/compiled/jest-worker
> ```

this solution only work for internal images

**Comment by joaotextor** [comment]
I can confirm that downgrading from 13.3 to 13.2.4 fixes the issue.

**Comment by didemkkaslan** [comment]
> I can confirm that downgrading from 13.3 to 13.2.4 fixes the issue.

Nothing works for me

**Comment by marketsystems** [comment]
> I can confirm that downgrading from 13.3 to 13.2.4 fixes the issue.

having to downgrade is not exactly a "fix" though is it..! Hopefully they working on this

**Comment by luisjorge129** [comment]
> > I can confirm that downgrading from 13.3 to 13.2.4 fixes the issue.
> 
> having to downgrade is not exactly a "fix" though is it..! Hopefully they working on this

Is technically a fix if it works how is supposed to after downgrading, even if it sounds odd we don't have much choice on this if we want to use 13.3.0 with amplify, is either this or image optimization false at the moment (both make it work how it supposed, but none are ideal).  But we know the developers of next will gets this sort out, we are just here to report the issue or help them, is all about waiting for a fix.

**Comment by marketsystems** [comment]
> > > I can confirm that downgrading from 13.3 to 13.2.4 fixes the issue.
> > 
> > 
> > having to downgrade is not exactly a "fix" though is it..! Hopefully they working on this
> 
> Is technically a fix if it works how is supposed to after downgrading, even if it sounds odd we don't have much choice on this if we want to use 13.3.0 with amplify, is either this or image optimization false at the moment (both make it work how it supposed to, but none are ideal). But we know the developers of next will gets this sort out, we are just here to report the issue or help them, is all about waiting for a fix now.

quite a lot of fixes needed for 13.3, was eager to use it for my project but sticking with 13.2.4 for now

**Comment by exilvm** [comment]
I'm sticking with `v13.2.4` as well until the developers address the issue.

**Comment by marketsystems** [comment]
tag a few active contributors and hope it gets sorted or they at least know who to prop :D @timneutkens @feedthejim @delbaoliveira @leerob @wyattjoh

**Comment by baltagih2** [comment]
This issue is back on 13.4.1

Images break or we get an "internal server error" (was working fine on 13.3.1 and 13.3.4)

**Comment by jethrolarson** [comment]
Standalone seems to be working for me on [v13.4.2-canary.3](https://github.com/vercel/next.js/releases/tag/v13.4.2-canary.3). I'm not sure if there was a regression on 13.4.1 as I did not test that version.

**Comment by marketsystems** [comment]
ridiculous when stuff gets fixed then broken again!

**Comment by ckqbao** [comment]
I have same issue when deployed to vercel, the error is OPTIMIZED_EXTERNAL_IMAGE_REQUEST_FAILED. My next.config.ts is configured with image remotePatterns.

**Comment by fuyu77** [comment]
It seems to work fine for me on v13.4.2.

**Comment by jethrolarson** [comment]
Yeah, I'm seeing no problem on 13.4.2 so this can stay closed, from my
perspective

**Comment by AliSinaYOusofi** [comment]
I have the same issue with Nextjs 13.4.3 . I had to use <img /> instead of <Image  /> component.

**Comment by alekslario** [comment]
The issue persists in 13.4.3. The development server only accepts the `/../public/image.png` path as `src` but for production, I had to use simple `image.png`.  Switching the path depending on the environment was my temporal fix.

**Comment by BossBele** [comment]
I have the same error on v12.3.4. Running `next start` I get the error:

> Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production

This is because I had `output: "standalone"` in my `next.config.js`
To fix this, simply install "sharp" from npm. `npm i sharp` or `yarn add sharp`

> It's worth noting that this error does not occur in Vercel deployments, since sharp is installed automatically for you

**Comment by Oliveira-86** [comment]
@damgel where should i  put this codes:

`COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+ COPY --from=builder /app/node_modules/next/dist/compiled/jest-worker ./node_modules/next/dist/compiled/jest-worker`

**Comment by damgel** [comment]
> @damgel where should I put these codes?
> 
> `COPY --from=builder /app/next.config.js ./
> COPY --from=builder /app/public ./public
> COPY --from=builder /app/package.json ./package.json
> COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
> COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
> + COPY --from=builder /app/node_modules/next/dist/compiled/jest-worker ./node_modules/next/dist/compiled/jest-worker` 

You need to put this lines in your Dockerfile. Just locate the COPY command inside the file and replace with this lines.

**Comment by damgel** [comment]
> > @damgel where should I put these codes?
> > 
> > `COPY --from=builder /app/next.config.js ./
> > COPY --from=builder /app/public ./public
> > COPY --from=builder /app/package.json ./package.json
> > COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
> > COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
> > + COPY --from=builder /app/node_modules/next/dist/compiled/jest-worker ./node_modules/next/dist/compiled/jest-worker` 
> 
> You need to put this lines in your Dockerfile. Just locate the COPY command inside the file and replace with this lines.

![IMG_20230627_135732.jpg](https://github.com/vercel/next.js/assets/1912831/525c7191-54e1-4a67-bcd3-02e1e6893dd0)
