### ISSUE TITLE
Upgrading to 13.3.0 cause SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by XEngine** [vercel/next.js#48070]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

can't provide, big project, anyways it only occurs on some environments maybe, couldn't reproduce on stackblitz

### To Reproduce

:>

### Describe the Bug

When I put "use client" at the top of a file next begins to cry about " SyntaxError: Unexpected token u in JSON at position 0". 

13.2.4 didn't have this issue.

### Expected Behavior

nextjs should not cri about "u" in "use  client".

### Which browser are you using? (if relevant)

Chrome

**Comment by Kamalito75** [comment]
I have the same problem even without using "use client".

**Comment by micmc422** [comment]
Same here on win11, seem to be every folders/files starting with “u”.
I got a folder "ui”, files in trigger error if I change to “fix-ui” error is from a file starting with “**u**se client”.

Error from folder : “Module parse failed: Bad character escape sequence”

**Comment by guttir14** [comment]
Similar issue: https://github.com/vercel/next.js/issues/47704

**Comment by pier7529** [comment]
After upgrading to 13.3.0 : same error - SyntaxError: Unexpected token u in JSON at position 0  at JSON.parse (<anonymous>)

**Comment by NitrousBGC** [comment]
Same problem here on all pages

**Comment by VaniaPopovic** [comment]
This error only appears on a Windows machine for me only on NextJS > (13.2.4). Tried Node 18.15, and the latest current 19.8.1. Also tried installing dependancies with NPM (latest) and PNPM (latest). My project runs fine on my mac machine, without 

`error - SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse ()
`

**Comment by AmeenJalali** [comment]
I have the same problem after upgrading to 13.3.0.

**Comment by getfit-us** [comment]
I have the same issue, but working great on 13.2.4. Big Project Can not really share either. I am back at 13.2.4 everything working fine.

**Comment by leonlarsson** [comment]
+1
Happens on 13.3.0 with https://github.com/leonlarsson/bfstats-web

**Comment by lenryk** [comment]
Only happens when I use `use client` for pages. 

Rolled back next to `v13.2.4` and seems to work now. Hopefully, they will fix it soon for the latest release.

**Comment by schimi-dev** [comment]
Same problem here. It worked fine until v13.2.5-canary.19. Starting from v13.2.5-canary.20 I get this problem on my Windows machine.

**Comment by Xetoxyc** [comment]
already discussed here, also there was a revert from @feedthejim. Seems like they could not reproduce it at review.

https://github.com/vercel/next.js/discussions/47736

**Comment by GetPsyched** [comment]
I do not have this issue (Linux, Next v13.3) however my friend who has the exact same repo as me (Windows 11, Next v13.3.0) does have this issue.

I've seen others in this thread mention Windows; perhaps it's a Windows + v13.3.0 problem?

**Comment by GetPsyched** [comment]
@XEngine I believe the `u` is from `undefined` being passed into `JSON.parse` here:
```js
function parseModel(response, json) {
  return JSON.parse(json, response._fromJSON);
}
```
This is what causes the syntax error since `undefined` isn't valid JSON.

**Comment by jacobkapitein** [comment]
The issue seems to only happen on Windows. A temporary workaround would be to use WSL. That seems to work for me.

**Comment by XEngine** [comment]
> @XEngine I believe the `u` is from `undefined` being passed into `JSON.parse` here:
> 
> ```js
> // node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js
> 
> function parseModel(response, json) {
>   return JSON.parse(json, response._fromJSON);
> }
> ```
> 
> This is what causes the syntax error since `undefined` isn't valid JSON.

yes I also found this block, there is one function that called this function while its argument called "model" or someting was null. I am just not familier with next's source which is all rust or something otherwise I would try to create a PR :D

**Comment by alfredlw** [comment]
Same issue. 13.3.0 does not support 'use client'

**Comment by microdotmatrix** [comment]
> I do not have this issue (Linux, Next v13.3) however my friend who has the exact same repo as me (Windows 11, Next v13.3.0) does have this issue.
> 
> I've seen others in this thread mention Windows; perhaps it's a Windows + v13.3.0 problem?

I was running into this problem when I updated to 13.3 in a project I was working on in Windows 10 on my laptop, and after reading through this issue thread I booted my desktop running Linux (Ubuntu 22.04), run a fresh create-next-app package with 13.3 and unfortunately I'm still having this issue... so no, its a problem on Linux as well. At least it is for me.

**Comment by TheMagoo73** [comment]
I'm seeing the same issue with my toy project - https://github.com/TheMagoo73/pokematic. `main` branch using 13.2.4 is working just fine, but locally I get this issue after upgrading to 13.3.0. This is on Win10.

Deploying the 13.3.0 branch out to Vercel as a preview (ie. the version that fails locally) works just fine.

**Comment by ArianHamdi** [comment]
Resolved by enabling turbopack. 
seems a webpack issue.
Windows 11, node 16.19.0.

**Comment by moolcoov** [comment]
+ The same issue

**Comment by arshad-repliq** [comment]
We're having this same error for last 2 days on windows only, working fine on linux and mac, as everyone else mentioned JSON is recieving undefined in here - 
![image](https://user-images.githubusercontent.com/128469992/230753065-2c27d62a-e1d6-4eb5-9fd2-13980ec39798.png)

**Comment by arshad-repliq** [comment]
We're having this same error for last 2 days on windows only, working fine on linux and mac, as everyone else mentioned JSON is recieving undefined in here - 
![image](https://user-images.githubusercontent.com/128469992/230753065-2c27d62a-e1d6-4eb5-9fd2-13980ec39798.png)

**Comment by arshad-repliq** [comment]
It can be fixed by simply turning your normal function () {} components into arrow function components whereever you've used "use client" you must use arrow function, it's still a bug but it can be fixed by using arrow functions.
I've fixed it myself and several others from a different issue fixed their projects this way. Until the bug is fixed this should work.

**Comment by TheMagoo73** [comment]
Changing my client components to use arrow function seems to have worked around this. I haven't been able to migrate to TurboPack yet as it seems to break the optional catch-all route at the root of my app, but it seems (at least for me) using arrow functions for client components is the key.

**Comment by XEngine** [comment]
changing them to arrow components not a fix for me.

**Comment by moolcoov** [comment]
it didn't help me as well

вс, 9 апр. 2023 г., 20:05 Cem Yılmaz ***@***.***>:

**Comment by XEngine** [comment]
https://github.com/vercel/next.js/issues/47704#issuecomment-1501058527

this appears to be a greak workaround for now. Closing this since this solution is a PR now and it will probably on the next canary release

**Comment by beratbayram** [comment]
Arrow function fix did not work for me. I had to rollback to 13.2.4.

I can confirm that the issue occurs when "use client" is used and I also using a win 10 machine with default configurations

**Comment by moolcoov** [comment]
> Arrow function fix did not work for me. I had to rollback to 13.2.4.
> 
> I can confirm that the issue occurs when "use client" is used and I am also using a win 10 machine with default configurations.

this issue was done in [v13.3.1-canary.4](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.4)

**Comment by 2akb** [comment]
I confirm the words of my predecessor - after installing the nextjs package and before the first run, install: **npm install --save next@13.3.1-canary.4 react react-dom**

**Comment by sawa-ko** [comment]
Fixed with latest canary version `(13.3.1-canary.4)`. :D

**Comment by maddsua** [comment]
> Resolved by enabling turbopack. seems a webpack issue. Windows 11, node 16.19.0.

yep, turbopack works fine

**Comment by AbdElra7man9** [comment]
I have the same problem, everything is working fine with 'use client' except using it in providers component for app layout
does anyone know how to temporary fix it until next js developers fix the problem

**Comment by rafaelbvc** [comment]
After i use "use client" i got type n parse errors... 
Mine V13.3.0, arrow function worked!

**Comment by nathanelcorpuz** [comment]
> It can be fixed by simply turning your normal function () {} components into arrow function components whereever you've used "use client" you must use arrow function, it's still a bug but it can be fixed by using arrow functions. I've fixed it myself and several others from a different issue fixed their projects this way. Until the bug is fixed this should work.

Turning it into an arrow function and exporting that as default worked for me. Thank you.

**Comment by Venipa** [comment]
> > Arrow function fix did not work for me. I had to rollback to 13.2.4.
> > I can confirm that the issue occurs when "use client" is used and I am also using a win 10 machine with default configurations.
> 
> this issue was resolved in [v13.3.1-canary.4](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.4)
fyi
still an issue in v13.3.1-canary.6

**Comment by anargiris** [comment]
I have the same issue when I try to wrap my app with the SupabaseProvider from this example:
https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components

Don't know if my problem is related to Supabase or NextJS but I guess it could be useful to share this here. Tested both with 13.3 and 13.2.4 and still got the same problem.

**Comment by asheikho99** [comment]
> It can be fixed by simply turning your normal function () {} components into arrow function components whereever you've used "use client" you must use arrow function, it's still a bug but it can be fixed by using arrow functions. I've fixed it myself and several others from a different issue fixed their projects this way. Until the bug is fixed this should work.

It will stop working if you have an named export along side default export in your file. also it appears that the issue occurs with named exports

Working
```ts
'use client';

import { signIn } from 'next-auth/react';

const LoginButton = () => {
    return (
        <button
            onClick={() => {
                signIn('github');
            }}>
            Sign In
        </button>
    );
};
```

Not Working
```ts
'use client';

import { signIn, signOut } from 'next-auth/react';

const LoginButton = () => {
    return (
        <button
            onClick={() => {
                signIn('github');
            }}>
            Sign In
        </button>
    );
};

const LogoutButton = () => {
    return (
        <button
            onClick={() => {
                signOut();
            }}>
            Sign Out
        </button>
    );
};

export default LoginButton;
export { LogoutButton };

```

**Comment by rohansen856** [comment]
> It can be fixed by simply turning your normal function () {} components into arrow function components whereever you've used "use client" you must use arrow function, it's still a bug but it can be fixed by using arrow functions.
> I've fixed it myself and several others from a different issue fixed their projects this way. Until the bug is fixed this should work.

Thanks. It worked.

**Comment by burakyesilyurt** [comment]
I've fixed it this way.
```javascript
"use client";
import { useEffect, useState } from "react";

const TestComponent = () => {    //---------------> make an arrow function

const [counter, setCounter] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCounter((prevCounter) => prevCounter + 1);
    }, 1000);
    return () => clearInterval(interval);
  }, []);

 return (
    <div className="App">
      <h1>Counter: {counter}</h1>
    </div>
  );
}
export default TestComponent    //---------------> export from here
```

**Comment by beratbayram** [comment]
I confirm that it is fixed for me at v13.3.1-canary.4

> > Arrow function fix did not work for me. I had to rollback to 13.2.4.
> > I can confirm that the issue occurs when "use client" is used and I am also using a win 10 machine with default configurations.
> 
> this issue was resolved in [v13.3.1-canary.4](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.4)

**Comment by Satindar31** [comment]
This only happens in the 13.3 update. It is related to an issue in parsing `'use client`. A simple work around is using the `--turbo` flag when starting

**Comment by itava0** [comment]
I'm using Windows 11 and nextJS 13.3.0
Arrow functions fixed the issue for me.

**Comment by itava0** [comment]
Spend two days debugging these issues 😭

**Comment by MirSowasVonEgal** [comment]
> I've fixed it this way.
> 
> ```js
> "use client";
> import { useEffect, useState } from "react";
> 
> const TestComponent = () => {    //---------------> make an arrow function
> 
> const [counter, setCounter] = useState(0);
> 
>   useEffect(() => {
>     const interval = setInterval(() => {
>       setCounter((prevCounter) => prevCounter + 1);
>     }, 1000);
>     return () => clearInterval(interval);
>   }, []);
> 
>  return (
>     <div className="App">
>       <h1>Counter: {counter}</h1>
>     </div>
>   );
> }
> export default TestComponent    //---------------> export from here
> ```

I tried it with one client side component and it didnt worked for me.
Downgrading to 13.2.4 worked for me.

**Comment by MirSowasVonEgal** [comment]
Found out it didnt worked for me, because I use a wrapper.

![image](https://user-images.githubusercontent.com/67387740/233847890-2a2de91f-a4f4-4f5d-81e5-0cf31095067a.png)
![image](https://user-images.githubusercontent.com/67387740/233847896-1429d28c-50ed-4693-bc1f-11505d27e881.png)

**Comment by MirSowasVonEgal** [comment]
Doesn't worked:

![image](https://user-images.githubusercontent.com/67387740/233848040-7341357a-70de-4fcc-8d77-8e7f89fbbdcd.png)
In different file:
![image](https://user-images.githubusercontent.com/67387740/233848044-86b49173-c650-421a-8fe2-44a86e10f553.png)

Worked in same file:
![image](https://user-images.githubusercontent.com/67387740/233848083-03b1222f-cf63-42a1-886c-0d672f1fcebe.png)

**Comment by JaviVA93** [comment]
I updated to version "13.3.1-canary.4" and now it's fixed (no need to do the arrow function workaround, which didn't work always)
