### ISSUE TITLE
[NEXT-1089] Custom fonts in `ImageResponse` not working in App Dir

### ISSUE THREAD

**Issue by surjithctly** [vercel/next.js#48081]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.18
      pnpm: 7.25.1
    Relevant packages:
      next: 13.3.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/github-f6jt4y?file=app%2Fopengraph-image.js

### To Reproduce

1. Run the Server
2. Check the error in console
3. Alternatively open the generated path in new URL to get the error. 

### Describe the Bug

While importing custom fonts, it throws the following error. 

```
error - unhandledRejection: Error [TypeError]: Failed to parse URL from /_next/static/media/Inter-Regular.f356e84a.woff
    at new Request (node:internal/deps/undici/undici:9474:19)
    at fetch1 (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.3.1-canary.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react/cjs/react.shared-subset.development.js:193:39)
    at doOriginalFetch (/Users/.../opengraph/node_modules/.pnpm/next@13.3.1-canary.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/lib/patch-fetch.js:159:24)
    at /Users/.../opengraph/node_modules/.pnpm/next@13.3.1-canary.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/lib/patch-fetch.js:253:20 {
  digest: undefined
}
```

### Expected Behavior

It should not throw error. Instead it should load properly. 

### Which browser are you using? (if relevant)

Any

<sub>[NEXT-1089](https://linear.app/vercel/issue/NEXT-1089/custom-fonts-in-imageresponse-not-working-in-app-dir)</sub>

**Comment by ekqt** [comment]
Also had this same issue

**Comment by khuezy** [comment]
I'm having the same issue; as a workaround, you can do this:
Put your font in `/public/fonts/here.tff`
```typescript
async function getFont(): Promise<Buffer> {
  const url = process.env.APP_URL
  return new Promise((resolve, reject) => {
    http.get(`${url}/fonts/Font.ttf`, (res) => {
      const chunks: any[] = []
      res.on('data', c => chunks.push(c))
      res.on('end', () =>
        resolve(Buffer.concat(chunks))
      )
    }).on('error', (err) => {
      reject(err)
    })
  })
}
```

**Comment by huozhi** [comment]
Hi, you’re using the default nodejs runtime, you can use fs read to access the font data in nodejs runtime.

Check out the nodejs example list here
https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation/og-image-examples#load-files-in-node.js-runtime

Or you can just add `export const runtime = “edge”` to your opengraph-image

**Comment by huozhi** [comment]
Can you try to move the font load inside the route handler it resolves the problem for me @surjithctly 

```tsx
const font = fetch(new URL('Inter-Regular.woff', import.meta.url)).then((res) =>
  res.arrayBuffer()
);
```

**Comment by huozhi** [comment]
@lukadev-0 can you check [the nodejs usage of og section](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation/og-image-examples#load-files-in-node.js-runtime) if you want to use nodejs runtime, it's just using fs operations instead of `fetch` to load font or extra assets.

**Comment by lukadev-0** [comment]
> @lukadev-0 can you check [the nodejs usage of og section](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation/og-image-examples#load-files-in-node.js-runtime) if you want to use nodejs runtime, it's just using fs operations instead of `fetch` to load font or extra assets. The bundle size is bit larger because it contains more necessary dependencies for edge runtime, but the speed is ideal.
> 

I tried that however the files didn't get included in the deployment

**Comment by huozhi** [comment]
@lukadev-0 could you provide a reproduction? Can take a look on that to see what's going wrong

**Comment by lukadev-0** [comment]
> @lukadev-0 could you provide a reproduction? Can take a look on that to see what's going wrong

Here you go: https://github.com/lukadev-0/next-og-image-font-repro

Whenever fetching the open graph image the following error is thrown:
```
error - [Error: ENOENT: no such file or directory, open '/vercel/path0/src/app/Inter-Medium.ttf'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/vercel/path0/src/app/Inter-Medium.ttf'
}
```

**Comment by huozhi** [comment]
@lukadev-0 Can you try the latest canary it resolves the deployment issue for me

**Comment by huozhi** [comment]
@ekqt would you mind filing another issue with a reproduction for that as it's not related to the original problem of this issue

**Comment by lukadev-0** [comment]
> @lukadev-0 Can you try the latest canary it resolves the deployment issue for me

I've tried with 13.4 (its newer than canary) and it worked. Thanks!

**Comment by lukadev-0** [comment]
@huozhi Turns out it doesn't work when there's a dynamic data fetch. (I've updated my reproduction)
```tsx
export default async function og() {
   const res = await fetch("https://jsonplaceholder.typicode.com/todos/1", {
     cache: "no-store",
   });
```

**Comment by huozhi** [comment]
Yeah can repro that, we take a look.

**Comment by surjithctly** [comment]
I changed my font and started to get this strange error. If I remove the fonts[], it works. 

```
- error Error [TypeError]: Cannot read properties of undefined (reading '256')
    at parseFvarAxis (webpack-internal:///(sc_server)/./node_modules/.pnpm/next@13.4.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@vercel/og/index.edge.js:10980:22)
```

**Comment by mwskwong** [comment]
Yeah, using the exact example in the doc in the latest version will still fail.
https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image#generate-images-using-code-js-ts-tsx

**Comment by ecto** [comment]
I was getting the `Failed to parse URL` error, and loading the font in a function as described in the comment above worked for me - thanks @mwskwong!

**Comment by riccardolardi** [comment]
Yep, loading the font in a function as described by @mwskwong does the trick

**Comment by florianjuengermann** [comment]
Confirmed, got it working with:
- edge function
- function in global scope `const getFont = async () => {
  const res = await fetch(
    new URL('@/fonts/Inter/static/Inter-SemiBold.ttf', import.meta.url)
  );
  return await res.arrayBuffer();
};`
- not in public directory

**Comment by prokopsimek** [comment]
The weird thing is, that function getFont does not work with a argument `font`. Do you know why?

```ts
const getFont = async (font: string) => {
  const res = await fetch(new URL(`./${font}.ttf`, import.meta.url));
  return await res.arrayBuffer();
};
```

```
Server Error
TypeError: fetch failed

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

**Comment by langovoi** [comment]
> Hi, you’re using the default nodejs runtime, you can use fs read to access the font data in nodejs runtime.
> 
> Check out the nodejs example list here https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation/og-image-examples#load-files-in-node.js-runtime

Link doesn't work. Looks like this example was silently removed. Proof: [web.archive.org](https://web.archive.org/web/20230516204820/https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation/og-image-examples#using-a-custom-font). There is same last updated date, but different content.

Example from old doc, it works for node runtime:
```js
const font = fs.promises.readFile(
  path.join(fileURLToPath(import.meta.url), '../../assets/TYPEWR__.ttf'),
);
const image = fs.promises.readFile(
  path.join(fileURLToPath(import.meta.url), '../../assets/image.png'),
);
```

**Comment by iamhectorsosa** [comment]
Moved around the things based on the suggestions here source: https://github.com/iamhectorsosa/iamhectorsosa/blob/1-add-basic-og-images-using-dynamic-files/src/app/opengraph-image.tsx

```tsx
export const runtime = "edge";

export const contentType = "image/png";

export default async function Image() {
  const groteskRegular = await fetch(
    new URL("./SchibstedGrotesk-Regular.ttf", import.meta.url)
  ).then((res) => res.arrayBuffer());
  const groteskSemibold = await fetch(
    new URL("./SchibstedGrotesk-Semibold.ttf", import.meta.url)
  ).then((res) => res.arrayBuffer());
```

The build succeeds locally but fails at deployment. I'm running into this issue:

```
./src/app/opengraph-image.tsx:23:4
13:31:43.419 | Module not found: Can't resolve './SchibstedGrotesk-Semibold.ttf'
13:31:43.419 | 21 \|   ).then((res) => res.arrayBuffer());
13:31:43.419 | 22 \|   const groteskSemibold = await fetch(
13:31:43.419 | > 23 \|     new URL("./SchibstedGrotesk-Semibold.ttf", import.meta.url)
13:31:43.419 | \|    ^
13:31:43.420 | 24 \|   ).then((res) => res.arrayBuffer());
13:31:43.420 | 25 \|
13:31:43.420 | 26 \|   return new ImageResponse(
13:31:43.420
```

**Comment by mrasadatik** [comment]
Guys, I don't know why!!! But using `woff` font format instead of `ttf` solve my problem!

**Comment by altano** [comment]
I created this helper:

```ts
import type { Font } from "satori";

export default async function getFonts(): Promise<Font[]> {
  // This is unfortunate but I can't figure out how to load local font files
  // when deployed to vercel.
  const [interRegular, interMedium, interSemiBold, interBold] =
    await Promise.all([
      fetch(`https://rsms.me/inter/font-files/Inter-Regular.woff`).then((res) =>
        res.arrayBuffer()
      ),
      fetch(`https://rsms.me/inter/font-files/Inter-Medium.woff`).then((res) =>
        res.arrayBuffer()
      ),
      fetch(`https://rsms.me/inter/font-files/Inter-SemiBold.woff`).then(
        (res) => res.arrayBuffer()
      ),
      fetch(`https://rsms.me/inter/font-files/Inter-Bold.woff`).then((res) =>
        res.arrayBuffer()
      ),
    ]);

  return [
    {
      name: "Inter",
      data: interRegular,
      style: "normal",
      weight: 400,
    },
    {
      name: "Inter",
      data: interMedium,
      style: "normal",
      weight: 500,
    },
    {
      name: "Inter",
      data: interSemiBold,
      style: "normal",
      weight: 600,
    },
    {
      name: "Inter",
      data: interBold,
      style: "normal",
      weight: 700,
    },
  ];
}
```

And then used it whenever I needed fonts in an opengraph-image.tsx file:

```ts
return new ImageResponse(..., {
  fonts: await getFonts(),
});
```

I feel bad fetching from a CDN but I couldn't get anything else to work. Here's what I was seeing:

1. runtime=edge would not work for me. no matter what I did I was over the 1MB limit, whatever that means.
2. Once deployed to vercel with runtime=nodejs: the OG image of static routes pre-render fine and the font file is there. but, dynamic routes lazily render the OG image when requested (even with `getStaticPaths`) and the font files are NOT IN THE DEPLOYMENT at all in Vercel during this lazy render. I scanned the entire filesystem with globby: the ttf files are gone. I tried putting them in multiple places (including `public`) and they are definitely just not there.

So fetching from a CDN and using runtime=node is the only solution that works for dynamic routes deployed to vercel.
