### ISSUE TITLE
Docs: Potential typo when referring to React 18 and Next 13

### ISSUE THREAD

**Issue by ranegray** [vercel/next.js#48084]
### What is the improvement or update you wish to see?

Potential error when referring to new versions. 

### Is there any context that might help us understand?

<img width="698" alt="Screen Shot 2023-04-07 at 16 26 02 PM" src="https://user-images.githubusercontent.com/75066470/230626193-0f85f7b5-c5a4-4e81-9d95-e7274c6f47ad.png">

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/how-nextjs-works/rendering

**Comment by wwwdepot** [comment]
they did introduce the **alpha** version of RSC in v12.  Don't see anything wrong with paragraph.

**Comment by ranegray** [comment]
Okay, cool. Wasn't sure and couldn't find anything about it. Ill close this issue.

**Comment by wwwdepot** [comment]
Read blog post https://nextjs.org/blog/next-12
