### ISSUE TITLE
How To Access Req/Headers/Cookie In Server Components

### ISSUE THREAD

**Issue by Antor666777** [vercel/next.js#48092]
### Access Req/Headers/Cookie In Server Components
Hey,
in Next.JS 13 app directory
i think we can'taccess the **req** like we accessed in getServerSideProps
```javascript
export async function getServerSideProps(context) {
  // We Can Access Req By
  const {req} = context
  return {
    props: {}, // will be passed to the page component as props
  }
}
```
Accesing req is very important because it is required to authenticate a user and getting users base url and this can help us to fetch data for ex:
### BaseUrl
The baseUrl is important because if we deploy our project in vercel not in production we can get different urls and if we run our next app in different ports the url will be different si we **don't have to hardcode** an url.
```javascript
const protocol = context.req.headers['x-forwarded-proto'] || 'http';
const baseUrl = `${protocol}://${context.req.headers.host}`;
const response = await fetch(baseUrl+'/api/hello')
const data = await response.json()
```
### Auth Validation
By getting the req object we can get cookies etc.. this can help us to validate user credentials manually

Please Fix It

### Is there any context that might help us understand?

Sorry If You Are Seeing This Again
How Can We Access The req object

**Comment by Ryan2018-js** [comment]
+1

**Comment by ma13gagan** [comment]
+1

**Comment by Antor666777** [comment]
Guys I have found the solution i have readed a next js documentation here it is telling how can we access the headers and cookie in Next.JS 13 Server Component
### Access Headers
Here is how can you access the [headers](https://beta.nextjs.org/docs/api-reference/headers)
```javascript
```

**Comment by Antor666777** [comment]
# Here is the issue that i made for writable cookies #48325
