### ISSUE TITLE
Docs: parallel routes must provide a `default.js` file or else it will throw a 404 error

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#48090]
### What is the improvement or update you wish to see?

When using parallel routes, if someone provide a child under the parent route, when navigating to the child route, next will show a 404 page instead of the page, i have noticed that adding a `default.js` fixes this. 

```
dashboard
├── @user
│   ├── page.js
│   └── default.js <-- should add this, if not specified the user will have a 404 when navigating to dashboard/child-route
├── child-route
│       └──  page.js
├── layout.js
└── page.js
```

I think this should be added to the docs. 

It must also be noted that it parent `layout.js` does not render the `{user}` prop inside the JSX, navigating to `dashboard/child-route` will work normally, but the `@user` parallel page will not be shown when navigating to `/dashboard`.

This should be highlighted in the docs as users could easily stumble on this error.

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/routing/parallel-routes#defaultjs

**Comment by defrex** [comment]
I ran into this problem as well. It also seems like, to get the page to load on hard refresh, I needed to add a `default.tsx` parallel to the `layout.tsx` file.

I literally just added this to make it work.

```tsx
import Page, { PageProps } from './page'

export default async function Default(props: PageProps) {
  return (
    // @ts-expect-error Async Component
    <Page {...props} />
  )
}
```

Seems like that should be the generic default when unspecified, IMO.

**Comment by Nickman87** [comment]
Wow, nice catch, it is also very unintuitive for me why we need all these `default` pages... I mean, if you don't know which parallel part to render, by default it should just render nothing, as we are doing now, OR fallback to the page that is already defined there.

**Comment by y0zong** [comment]
it's not work in complex case like more than one level or [Catch-all Segments](https://beta.nextjs.org/docs/routing/defining-routes#catch-all-segments), it seems `parallel route` implementation is a bit confusing :(

**Comment by jvanmaaren** [comment]
FYI this does not seem to work when you use [the route group hack ](https://github.com/vercel/next.js/issues/49243#issuecomment-1548111858) and refresh the page

**Comment by ztanner** [comment]
Looks like some docs were added on this [here](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#unmatched-routes)!

**Comment by Fredkiss3** [comment]
thank you @ztanner  i am closing this issue
