### ISSUE TITLE
Link tag for file-based manifest not added to head element

### ISSUE THREAD

**Issue by glennreyes** [vercel/next.js#48105]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.8.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.1.1
    Relevant packages:
      next: 13.3.1-canary.2
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/glennreyes/my-next-manifest-app

### To Reproduce

1. Go to https://my-next-manifest-app.vercel.app/
2. Check element tree
3. `<link rel="manifest" href="/manifest.webmanifest">` non-existent although it's configured in `app/manifest.ts` and accessible via https://my-next-manifest-app.vercel.app/manifest.webmanifest

### Describe the Bug

The link tag for manifest is not automatically added to the head element, when a file-based manifest is configured.

### Expected Behavior

The link tag for manifest is automatically added to the head element, when a file-based manifest is configured.

### Which browser are you using? (if relevant)

Brave Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

**Comment by huozhi** [comment]
Thanks for reporting! This is already fixed by https://github.com/vercel/next.js/pull/48310, and please upgrade to the latest version 🙏
