### ISSUE TITLE
navigating to and from global `not-found.js` do not work in next v13.3

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#48111]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Sat Apr 08 2023 00:07:37 GMT+0200 (heure d’été d’Europe centrale)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 7.13.6
    Relevant packages:
      next: 13.3.1-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/github-qh3hsn?file=app%2Flayout.tsx,app%2Fpage.tsx

### To Reproduce

To test navigating to a 404 page :

1. Run `next dev`
2. Click on the link "Go to a 404 page"

To test navigating from a 404 page :

1. Run `next dev`
2. Go to a page that does not exist
3. Click on the link "Go home"

### Describe the Bug

There are 2 bugs occurring with 404 navigation : 

- When navigating a page that does not exist with the `<Link>` component if you have a global `not-found` page it will show the current page only and not even navigate, if i manually go to the nonexisting page (from the URL bar for ex) it will show me the correct page. 
- If you go to a page that does not exist and try to navigate using the `<Link>` component anywhere, it will update the URL in the URL bar but not show that page, it will only show the 404 page

### Expected Behavior

Navigation from and to a page that does not exists when using a global not-found page should work normally.

**Comment by TheEdoRan** [comment]
A few days ago I opened an issue for the same problem you described (broken navigation from 404 page links): #47862. I think the two bugs are related, and it seems that the Next team is already working to fix them!

**Comment by Fredkiss3** [comment]
Ah ok then
