### ISSUE TITLE
On Demand Revalidation Bug with Dynamic Segments - Invalid Response 200

### ISSUE THREAD

**Issue by theonlydaleking** [vercel/next.js#48119]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.17.0
    Relevant packages:
      next: 13.3.1-canary.2
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/theonlydaleking/nextjs-revalidation-error

### To Reproduce

- Clone the repo
- install deps `yarn` 
- `yarn build`
- `yarn start`
- open a browser and navigate to localhost:3000/api/revalidate 
- it will fail to revalidate the dynamic segment. 
- revalidating a static route like `/` works fine 

### Describe the Bug

Revalidation fails for dynamic segments, gives an error `Invalid Response: 200` 
Works well for normal routes eg `/` 

when testing the api-utils/node.ts, it's failing at this line: 
https://github.com/vercel/next.js/blob/4e3f135fd66258c12e65d97e6ca859a4309a5f77/packages/next/src/server/api-utils/node.ts#L414-L418

If you log those 3 if conditions you'll get: `undefined, 200, undefined` respectively 
if you log those 3 conditions for a static path you get `REVALIDATED, 200, undefined` 

### Expected Behavior

response: revalidation success 

### How are you deploying your application? (if relevant)

Vercel

**Comment by theonlydaleking** [comment]
After more digging, I've realised this is a misunderstanding of how revalidation works (Dynamic segments are dynamically rendered) 
What led me to believe they weren't is perhaps another bug where my dynamic segments are not pulling new data. This is perhaps to do with graphQL

**Comment by lShinal** [comment]
@theonlydaleking why you closed the issues. I was already hoping I'd found what I was looking for

**Comment by nicosh** [comment]
@theonlydaleking, i think Dynamic segments can be cached and revalidated, i have the same problem and it fails to revalidate segments only on-demand, while it works using ISR.
Perhaps you should consider to re-open this issue.

**Comment by daszkowski** [comment]
@theonlydaleking I have same problem with "Invalid Response 200" for on-demand revalidation for dynamic routes (on next v13.3.1) - interestingly enough the revalidation is actually performed (i.e. the data is updated) while an error is returned from the API - does anyone have any information if this is a problem with the current version and if so, will it be patched in the future? 🤔
