### ISSUE TITLE
[NEXT-1100] unhandledRejection: Error [TypeError]: trace.getSpan is not a function

### ISSUE THREAD

**Issue by dossy** [vercel/next.js#48118]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Sun Nov  6 23:17:00 PST 2022; root:xnu-7195.141.46~1/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.2
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue

[https://github.com/dossy/nextjs-trace-getSpan-is-not-a-function](https://github.com/dossy/nextjs-trace-getSpan-is-not-a-function)

### To Reproduce

Provided by [https://github.com/vercel/next.js/issues/48118#issuecomment-1556428577:](https://github.com/vercel/next.js/issues/48118#issuecomment-1556428577:)

reproduce with a yarn workspaces monorepo.

Check this one out here: [jamesopti/next-tracespan-error-reproduction](https://github.com/jamesopti/next-tracespan-error-reproduction)

The packages/server has "@opentelemetry/api":  "^0.18.1"

The packages/client is a brand new create next app.

### Describe the Bug

Trying to access the app results in an `unhandledRejection: Error [TypeError]: trace.getSpan is not a function` error:

```
$ yarn dev
yarn run v1.22.19
$ next dev
warn  - Port 3000 is in use, trying 3001 instead.
ready - started server on 0.0.0.0:3001, url: http://localhost:3001
(node:53803) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
event - compiled client and server successfully in 1821 ms (170 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 467 ms (217 modules)
error - unhandledRejection: Error [TypeError]: trace.getSpan is not a function
    at NextTracerImpl.getActiveScopeSpan ([REDACTED]/create-next-app-sample/node_modules/next/dist/server/lib/trace/tracer.js:50:22)
    at NextTracerImpl.trace ([REDACTED]/create-next-app-sample/node_modules/next/dist/server/lib/trace/tracer.js:69:103)
    at DevServer.handleRequest ([REDACTED]/create-next-app-sample/node_modules/next/dist/server/base-server.js:166:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.handleRequest ([REDACTED]/create-next-app-sample/node_modules/next/dist/server/dev/next-dev-server.js:839:16) {
  digest: undefined
}
```

### Expected Behavior

The home page should render in the browser.

### Which browser are you using? (if relevant)

Chrome Version 111.0.5563.146 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

locally

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-1100](https://linear.app/vercel/issue/NEXT-1100/unhandledrejection-error-[typeerror]-tracegetspan-is-not-a-function)</sub>

**Comment by dossy** [comment]
#46632

**Comment by ndpa** [comment]
This also worked for me to resolve this issue as per #46632 / yarn add @opentelemetry/api @opentelemetry/resources @opentelemetry/semantic-conventions @opentelemetry/sdk-trace-node @opentelemetry/instrumentation

But, it seems very odd to me that I would need to do this. Please let me know if a better solution appears.

**Comment by jamesopti** [comment]
Trying to upgrade to the latest 13.4 and getting this error.

Any response from the next team? Seems odd that consumers would need to install opentelemetry themselves 🤔

**Comment by jamesopti** [comment]
It appears that `@opentelemetry/api` is a peerDependency now, but the docs dont indicate as much: https://github.com/vercel/next.js/blob/v13.4.1/packages/next/package.json#L95

**Comment by huozhi** [comment]
@jamesopti There's a built-in version of opentelementry by default, it should work even you didn't install it.

I can't repro the error with latest version 13.4.1 with origin reproduction post in the issue description. Could you post another reproduction for this if you're still seeing the error?

**Comment by jamesopti** [comment]
We're using a monorepo where the client package is nextjs. Our server package requires @opentelemetry/api. Is it possible this is causing a conflict?

Additionally, why is `@opentelemetry/api` listed as a peer dependency? That sure seems like what is causing the problem here.

```
➜  client git:(main) yarn why @opentelemetry/api
├─ @opentelemetry/instrumentation-express@npm:0.16.0
│  └─ @opentelemetry/api@npm:1.0.0-rc.3 (via npm:^1.0.0-rc.0)
│
└─ server@workspace:packages/server
   └─ @opentelemetry/api@npm:0.18.1 (via npm:^0.18.1)
```

**Comment by jamesopti** [comment]
FWIW, this issue was introduced in 13.4.0

13.3.4 does not have this problem.

**Comment by huozhi** [comment]
The different version could be possible reason, could you try add `resolution` in package.json to lock its version to one, we'll investigate the issue at the same time

**Comment by huozhi** [comment]
@jamesopti yes ideally only `@opentelemetry/api` will be fine so that it's always the same version. Can you try this?

```json
"resolutions": {
  "**/@opentelemetry/api": "0.18.1",
}
```

**Comment by huozhi** [comment]
@jamesopti  We really need a minimal reproduction here as the original reproduction in the issue is not able to repro the issue. Please provide a reproduction repo

**Comment by dossy** [comment]
I can no longer reproduce the issue, so if someone else can, please provide a minimal reproduction.  Thanks!

**Comment by jamesopti** [comment]
@dossy @huozhi This is very easy to reproduce with a super simple yarn workspaces monorepo.

Check this one out here: https://github.com/jamesopti/next-tracespan-error-reproduction


The `packages/server` has `"@opentelemetry/api":  "^0.18.1"`

The `packages/client` is a brand new create next app.

**Comment by shuding** [comment]
Hey! I took a look and it appears that you're on `@opentelemetry/api@0.18.1`, which doesn't have the methods Next.js need (https://unpkg.com/browse/@opentelemetry/api@0.18.1/build/src/api/trace.js there's no `getSpan` method exposed). It's available in the latest version: https://unpkg.com/browse/@opentelemetry/api@1.4.1/build/src/api/trace.js.

Confirmed that your repo works fine if upgrading the `@opentelemetry/api` package. In the meantime I'll add a check in Next.js regarding the minimal required version of that lib.

**Comment by jamesopti** [comment]
So now I'm really confused. Is `@opentelemetry/api@^1.0.0` a required peer dependency for NextJS?

The solution to run my client can't just be to upgrade the entire telemetry package for my server.


> @jamesopti There's a built-in version of opentelementry by default, it should work even you didn't install it.


According to this comment, I was under the impression that consumers were not required to install opentelementry themselves

**Comment by shuding** [comment]
@jamesopti I did a quick look and `0.19.0` already have that `getSpan` API (https://unpkg.com/browse/@opentelemetry/api@0.19.0/build/src/api/trace.js), you don't need to bump to 1.0.

The logic in Next.js is that if you have opentelementry installed, Next.js will use your version. Otherwise Next.js uses its built-in one. But here the problem is that the user provided version doesn't meet the need.

**Comment by jamesopti** [comment]
> The logic in Next.js is that if you have opentelementry installed, Next.js will use your version. Otherwise Next.js uses its built-in one. But here the problem is that the user provided version doesn't meet the need.

So it sounds like I need a way to tell Yarn workspaces that the `0.18.1` version is for `packages/server` and that `packages/client` cannot use it.

In classic yarn you could use the noHoist option but with Yarn 3 I'm not sure how to do that anymore.

I'll also explore the 0.19.0 approach, which is much more doable than a major version upgrade.

Thanks for the detail

**Comment by jamesopti** [comment]
Unfortunately `0.19.0` has a bunch of breaking changes and is not an option for me to fix with this.

I'm going to capitulate and just install the latest @opentelemetry packages in my nextjs workspace.

**Comment by weyert** [comment]
> @dossy @huozhi This is very easy to reproduce with a super simple yarn workspaces monorepo.
> 
> Check this one out here: https://github.com/jamesopti/next-tracespan-error-reproduction
> 
> The `packages/server` has `"@opentelemetry/api": "^0.18.1"`
> 
> The `packages/client` is a brand new create next app.

Why do you use a two year old experimental version of `@opentelemetry/api`? v1 got released two years ago.
