### ISSUE TITLE
Parallel Route - Navigation fails to clear slot 

### ISSUE THREAD

**Issue by dalalmj** [vercel/next.js#48124]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 16.17.0
      npm: 9.1.3
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/dalalmj/prtest2

### To Reproduce

Using parallel route to display list detail view. List = base route. Detail = @detail, parallel route. This allows user to see list while getting details either in modal or below or to right of list. After detail is display in slot, when navigating back to list, the slot is not cleared.

Run, click List link.
Click on 1
Click on Close
Still show details of 1

### Describe the Bug

When showing slot (parallel route), slot does not get cleared if URL does not match.

### Expected Behavior

When showing slot (parallel route), slot should get cleared if URL does not match.

**Comment by feedthejim** [comment]
this is on purpose, we don't clear parallel routes if they don't match on the server. What you want to do is use a [...catchAll] route in your parallel route when you want to "hide" a route. Will make sure this is explained in the docs.

**Comment by Yukioru** [comment]
Here's a similar issue with a parallel route that should only show up on one page but not the others.

In my case, it will not be possible to use the [...catchAll] route, because it will never be called.

Repo: https://github.com/Yukioru/next-parallel-routes-bug
Demo without ...catchAll: https://next-parallel-routes-bug.vercel.app/
demo with ...catchAll: https://next-parallel-routes-44umlwyls-yukioru.vercel.app/

**Comment by feedthejim** [comment]
@Yukioru good news this is fixed by #48424 I think

**Comment by dalalmj** [comment]
Just tested with latest canary (8), it is now works as is, not need for [...catchAll] route

**Comment by dalalmj** [comment]
BTW, can someone have a look at related issue [#48122](https://github.com/vercel/next.js/issues/48122), Parallel route navigation fails when prefetch is set to false.

**Comment by Yukioru** [comment]
> Just tested with latest canary (8), it is now works as is, not need for [...catchAll] route

For my case - I will wait for a fix. In canary.8 the behavior is the same (which makes sense).
