### ISSUE TITLE
`Module parse failed: Unexpected character '�'` when using canvas in new App Directory @13.3

### ISSUE THREAD

**Issue by titouv** [vercel/next.js#48135]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Fri Mar 17 14:38:40 PDT 2023; root:xnu-8796.120.16~15/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: 8.1.1
    Relevant packages:
      next: 13.3.1-canary.3
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/titouv/nextjs-appdir-pdf-reproduce 

### To Reproduce

To reproduce use the following repo : https://github.com/titouv/nextjs-appdir-pdf-reproduce. A small example setup with create-next-app

In the pages directory, the route /pages/pdf maps to http://localhost:3000/pdf.
The pdf component using pdfjs-dist works 

In the new app directory, the route /app/pages.tsx maps to http://localhost:3000/
The pdf component using pdfjs-dist doesn't work and give the following error.
`Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)`

The bug appears in last version next@13.3 and on the latest canary version used in the repo next@13.3.1-canary.3

### Describe the Bug

The issue we're encountering is that the `pdfjs-dist` library fails to load in the new app directory, resulting in the error `Module parse failed: Unexpected character '�'`. I'm uncertain why the bundling configuration for the app directory prevents this module from loading, while it works fine in the pages directory.
It seems the error is due to the `canvas` depedency of the `pdfjs-dist` package. I know `canvas` is a big module that is not recommended to run on lambda but it seems even in local configuration or pure static export this doesn't work.

### Expected Behavior

The expected behavior is to have the pdjs-dist package behave the same as in the pages directory and not produce the error.

### Which browser are you using? (if relevant)

Arc 112.0.5615.49 (chromium browser)

**Comment by JasperAlexander** [comment]
Take a look at [this issue](https://github.com/mozilla/pdf.js/issues/16214) and [my package](https://github.com/JasperAlexander/ai-utils/tree/main/packages/file-to-text) which uses pdfjs-dist and can be used in a Next.js project.

**Comment by marcrmueller** [comment]
This solved it for me - https://github.com/konvajs/konva/issues/1458#issuecomment-1356122802

**Comment by timneutkens** [comment]
https://github.com/konvajs/konva/issues/1458#issuecomment-1543977999
