### ISSUE TITLE
CSS modules not working in `/app/not-found.tsx`

### ISSUE THREAD

**Issue by nghiepdev** [vercel/next.js#48133]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/dark-microservice-lxq1q8?file=%2Fapp%2Fnot-found.tsx

### To Reproduce

Click to `Go to 404` page.

### Describe the Bug

CSS modules do not apply in `not-found.tsx`

### Expected Behavior

CSS modules just work

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next dev

**Comment by jinojacob15** [comment]
Me also had the same experience , the new 'not-found.js' file is full of bugs , link is broken , css modules being not loaded

**Comment by saurabhchardereal** [comment]
Can confirm this as well. Importing the `*.module.scss` in `not-found.tsx` itself works but the styles aren't being compiled.
