### ISSUE TITLE
[NEXT-1013] (...)[dynamic] does not work

### ISSUE THREAD

**Issue by sandervspl** [vercel/next.js#48143]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$ next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.1.1
    Relevant packages:
      next: 13.3.1-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/sandervspl/intercept-route-test/

### To Reproduce

1. Go to https://intercept-route-test.vercel.app/en/foo/bar/baz
2. Click on `Show user`
3. It will show the regular page which says `I am a REGULAR user page`

### Describe the Bug

You can not use a dynamic parameter with parallel routes, e.g. `(...)[locale]`

### Expected Behavior

It should show a page with the text `User INTERCEPT page`

<sub>[NEXT-1013](https://linear.app/vercel/issue/NEXT-1013/[dynamic]-does-not-work)</sub>

**Comment by shawshankkumar** [comment]
It would help if you could deploy this!

**Comment by sandervspl** [comment]
@shawshankkumar Good idea. I just did!

https://intercept-route-test.vercel.app/en/foo/bar/baz

**Comment by kristian240** [comment]
@feedthejim Can you take a look at this one as well? I also have an issue with this one.

**Comment by feedthejim** [comment]
on the latest canary?

**Comment by sandervspl** [comment]
@feedthejim I have just updated the deployed reproduction to canary.6 https://intercept-route-test.vercel.app/en/foo/bar/baz

**Comment by feedthejim** [comment]
thanks for the repro @sandervspl, will investigate

**Comment by Manduro** [comment]
When looking into this with routes as below, I found that the interception route is never used. Instead it always uses the normal `/language/[id]` route and resolves the id param to `(.)74a84042-7f87-43cf-8189-11da75c7afb3` (so including the `(.)` indicator).

```json
{
	"/[language]/[id]/page": "/[language]/[id]",
	"/[language]/@modal/(.)[id]/page": "/[language]/(.)[id]"
}
```

So the problem likely lies in the route matching area. An interception segment should get priority over a normal dynamic segment.

Hope this helps @feedthejim

**Comment by Manduro** [comment]
Attached is a patch with a workaround for this issue. It's for `(.)[dynamic]` specifically, but can be updated to work with `(...)[dynamic]`. The param value will contain the `(.)`, so you should replace this in your code that is using the param.

[next+13.4.1.patch](https://github.com/vercel/next.js/files/11456441/next%2B13.4.1.patch)

**Comment by Morishiri** [comment]
I also observed that having just dynamic `[locale]` in the root of my tree and trying to achieve [NextGram](https://github.com/vercel-labs/nextgram) behavior sometimes loads photo in modal, sometimes in regular page (didn't found a rule for it, looks like some race). May be related to this issue.
