### ISSUE TITLE
Intercepting Routes not working for multiple routes

### ISSUE THREAD

**Issue by borispoehland** [vercel/next.js#48157]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.25.1
    Relevant packages:
      next: 13.3.1-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Intercepting Routes, Parallel Routes

### Link to the code that reproduces this issue

https://github.com/borispoehland/nextgram-demo.git

### To Reproduce

- Open https://nextgram-demo.vercel.app/test
- Click a picture and see it **not** opening in the modal, but as page

### Describe the Bug

Route interception only works for single routes at a time. In the demo, this is https://nextgram-demo.vercel.app, but not https://nextgram-demo.vercel.app/test.

I think a very common use case will be to use the interception for each route but the intercepted route itself. For example, on all pages but `/cart,` I want the cart to render as a modal. Only when opening `https://domain.com/cart`directly, I want to render it as page. This is all the more common when you consider that a cart is often part of the nav bar, which is shown on all pages.

This behaviour currently requires to **duplicate** the intercepted segment `(..)photos/[id]/page.js` across all our routes where we want the interception to happen.

### Expected Behavior

Instead, when we declare an intercepting route as parallel route (as in the example: `@modal/(..)photos/[id]/page.js`), every layout that includes the `@modal` slot and all its children should render the modal. 

In our example, when opening the photo from within the `/test` page, it should render it as modal and not call the page, because the parent layout of the `/test` page includes the `@modal` slot

**Comment by borispoehland** [comment]
Perhaps, if this would break existing behaviour or doesn't work irt to other things that I'm not aware about, maybe an idea could be to opt-in to the "make interception work on all routes", e.g. in form of a route group? https://github.com/vercel/next.js/issues/48104#issuecomment-1501105469

**Comment by feedthejim** [comment]
hey @borispoehland, turns out we already have markers beyond (..):
- (.) for matching siblings
- (...) for matching from the root

Both should allow you to do matching from the route!

I'm sorry these haven't been documented yet but it should be updated soon

**Comment by borispoehland** [comment]
Hey @feedthejim, none of these work. When you go to the example and adapt the path to any of the combinations (., .., ...), none of it works to trigger the modal from the `/test` page. This issue should still be open... Thanks for checking

**Comment by feedthejim** [comment]
ah indeed! Found the bug, will fix in #48276

**Comment by borispoehland** [comment]
@feedthejim Thank you!

**Comment by borispoehland** [comment]
@feedthejim I have another question that I first want to ask you before I open a issue because it is a understanding problem from my side.

I looked at the example of the [„Mutating data“ docs](https://beta.nextjs.org/docs/data-fetching/mutating) and I found out that the behaviour of `router.refresh` is not refreshing. That is because the default option of fetch is `{cache: "force-cache"}` and that doesn't trigger the re-fetch or the data. If I use `{cache: "no-store"}` it works.

**Comment by feedthejim** [comment]
@borispoehland that would be expected I guess? router.refresh only refreshes the client state. If your server code always caches then you won't get an updated version. You want to use ISR in this case and revalidate that path .see https://beta.nextjs.org/docs/data-fetching/revalidating

**Comment by borispoehland** [comment]
Hold on @feedthejim - router.refresh is supposed to refresh the server component data fetches without using client state, no?

In the example from [Mutating data](https://beta.nextjs.org/docs/data-fetching/mutating), calling it will fetch the new To-Dos from the server, so that they are updated when you submit a new To-Do earlier.

Now, is it not possible to refresh the server fetch ON-DEMAND in the moment where we do router.refresh, regardless of the caching used?
Let's say we use ISR and the data from the server component `https://api.example.com/todos` is not yet stale, only in 20 seconds it will become stale. But we just added a To-Do and called router.refresh, the function still returns the old data though because no new fetch is triggered. Doesn't that destroy the whole point of router.refresh then? You initiate a refresh but the To-Dos are not re-fetched? Am I missing something?

**Comment by feedthejim** [comment]
I think that example is wrong and should use `cache: 'no-store'`, I've surfaced that to the team.

> router.refresh is supposed to refresh the server component data fetches without using client state, no?

No, what it does is reset the client cache and fetch again from the server. If the server was caching it, then it will still return the same result. I've let the team know to make that more clear in the doc.

> Now, is it not possible to refresh the server fetch ON-DEMAND in the moment where we do router.refresh, regardless of the caching used?

Yes, it is not possible at the moment, hence why we're working on mutations. Basically in the near future, you'll be able to do something like adding a todo, refreshing the todos page and return that in one pass.

> Doesn't that destroy the whole point of router.refresh then? You initiate a refresh but the To-Dos are not re-fetched? Am I missing something?

not really because not all pages are static
