### ISSUE TITLE
Intercepting routes to a modal does not work in a subdir

### ISSUE THREAD

**Issue by kasperaamodt** [vercel/next.js#48163]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
    Binaries:
      Node: 19.3.0
      npm: 9.2.0
      Yarn: 1.22.18
      pnpm: 7.21.0
    Relevant packages:
      next: 13.3.1-canary.3
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/devhuset/next-text-app

### To Reproduce

Run app.
Try the modal in the front page, and then the sub page.

### Describe the Bug

Intercepting routes to a modal in a subdir does not seem to work like it does in the app dir root.

### Expected Behavior

To work in the same way in a subdir, as the root dir.

**Comment by alvarlagerlof** [comment]
Perhaps similar to https://github.com/vercel/next.js/issues/48104 ?

**Comment by feedthejim** [comment]
can you repro on the latest canary @kasperaamodt ?

**Comment by Kinbaum** [comment]
I have the same issue. My file structure looks like this:

```
app
└── [lang]
    ├── layout.tsx
    └── public
        ├── @modal
        │   ├── (.)request-form
        │   │   └── page.tsx
        │   └── default.tsx
        ├── layout.tsx
        ├── page.tsx
        └── request-form
            └── page.tsx
```

Inside of my modal, I am logging a message to the console. When I create a link to `/en/public/request-form` and mouse over it, I can see my message getting logged. When I click the link however, the modal never renders and I'm always taken directly to the page.

**Comment by Kinbaum** [comment]
@timneutkens In addition to my comment above, I also haven't seen an example of this that is accessible. Looking at the nextgram example, closing the modal does not return focus to the trigger. Is there an example of the interception with a11y?

**Comment by moseslucas** [comment]
When dealing with a basic modal. You can do a stateless and`searchParam` based modal. See this how it's done https://medium.com/@lukeses09/how-to-do-a-basic-modal-in-next-js-13-7cf3b72ce919
