### ISSUE TITLE
"Use client" read as undefined JSON 

### ISSUE THREAD

**Issue by Benevos** [vercel/next.js#48171]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/Benevos/nextjs-error

### To Reproduce

1. Create a project in latest version.
2. Copy the next code in Home.
```javascript
import ServerComponent from './ServerComponent';

export default function Home() {
  return (<ServerComponent/>)
}
```
3. Make this two components.

**ClientComponent.js**
```javascript
"use client";

export default function ClientComponent() {
  return (
    <div>
        <h1>This is a client component!</h1>
    </div>
  )
}
```
**ServerComponent.js**
```javascript
import ClientComponent from "./ClientComponent"

export default function ServerComponent() 
{

    return (<ClientComponent/>)
        
}
 
```
4. Do `npm run dev` in project enviroment.

### Describe the Bug

Page will be giving returning an exception and not running at all. 

This is the given error:

![image](https://user-images.githubusercontent.com/74975454/230795665-35d7c08d-0cf3-46c7-a09a-8eeeee41078a.png)

### Expected Behavior

Page loads and show the message _"This is a client component!"_.

As I read in beta docs, this should run but I don't understand what is happening, I deduce this is may due to a bad interpretation of `"use client"` as an undefined JSON, but can't be sure about it.

### Which browser are you using? (if relevant)

Chrome 111.0.5563.148

**Comment by XEngine** [comment]
https://github.com/vercel/next.js/pull/48152

this is a fix
