### ISSUE TITLE
[Next 13.3.0] - Dev server crashing

### ISSUE THREAD

**Issue by adamjdavies** [vercel/next.js#48186]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.7.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

...

### To Reproduce

Upgrade to Next 13.3.0 and try running the dev server

### Describe the Bug

Upgraded to Next 13.3.0 to test out some new features on my project. Previously was using Next 13.2.4. 

When attempting to run the dev server, the following error was thrown:

./node_modules/next/dist/compiled/@vercel/og/index.node.js:17950:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/next/server.js
./node_modules/@supabase/auth-helpers-nextjs/dist/index.js
./utils/supbaseClientCreate/supabase-browser.tsx
./components/modules/admin/auth/supabase-context-provider.tsx

### Expected Behavior

The dev server should run as normal.

### Which browser are you using? (if relevant)

Version 111.0.5563.146 (Official Build) (arm64)

**Comment by adamjdavies** [comment]
Updating to the latest version of the supabase auth helpers package fixed this.

**Comment by notdotscott** [comment]
@adamjdavies can you explain how to do that please? I'm experiencing this exact issue but not sure what you mean by "supabase auth helpers". Thanks

**Comment by adamjdavies** [comment]
@notdotscott I am using[ Supabase](https://supabase.com/) for handling auth and my backend. They offer [a helper library](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components) to simplify the auth implementation in Next.js (either using the pages or app directory). It seems that the issue I was having was related to the helper library. Supabase released a fix for this, so updating to use the latest version resolved my issue. 

If you're not using Supabase, then I'm not sure I will be able to help.
