### ISSUE TITLE
[NEXT-980] `next export -o <dir>` output directory ignored if next.config has `output: "export"`

### ISSUE THREAD

**Issue by jldec** [vercel/next.js#48207]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.15.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.3.1-canary.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Static HTML Export (output: "export")

### Link to the code that reproduces this issue

https://github.com/jldec/next-reproduction-app

### To Reproduce

- clone [repro](https://github.com/jldec/next-reproduction-app) and install deps (I use pnpm)

```
pnpm build
```

- terminal output says

```
warn  - "next export" is no longer needed when "output: export" is configured in next.config.js https://nextjs.org/docs/advanced-features/static-html-export
Export successful. Files written to /Users/jldec/next/reproduction-app/dist
```

```
$ ls dist
ls: dist: No such file or directory

$ ls out
404.html    _next       favicon.ico index.html
```

### Describe the Bug

Since v13.3.0 `next build` also does export (see https://github.com/vercel/next.js/pull/47376)

Any existing builds which use `next export -o <output-dir>` will be broken because `next build` will put the files in the default `out` directory and the subsequent `next export -o <output-dir>` will not re-build or move the files into `<output-dir>`.

### Expected Behavior

Prior-version `next export -o` behavior should not be impacted by the new `next build` all-in-one behavior, even if it means re-copying the files to the specified output directory.

<sub>[NEXT-980](https://linear.app/vercel/issue/NEXT-980/next-export-o-dir-output-directory-ignored-if-nextconfig-has-output)</sub>

**Comment by styfle** [comment]
Thanks for reporting this issue!

If you want to submit a PR with a fix, please do. Otherwise we'll get around to it by the next stable release 👍
