### ISSUE TITLE
Docs: Fix incorrect instructions in docs

### ISSUE THREAD

**Issue by seriouscatsoserious** [vercel/next.js#48203]
### What is the improvement or update you wish to see?

Update the example depicted below, as well as the starter code listed here (https://nextjs.org/learn/basics/navigate-between-pages/setup) to reflect what the source code of the starter file should contain at that step. Potentially, this should be corrected at every instance of the starter file being shared in the docs. 

### Is there any context that might help us understand?

The example here(https://nextjs.org/learn/basics/navigate-between-pages/link-component) instructs user to "Then find the h1 tag that looks like this:", except that if the user was following the tutorial to that point, the text would no longer say "Welcome" as pictured, but would say "Learn" according to the steps in the tutorial before, linked here and depicted in the second image (https://nextjs.org/learn/basics/create-nextjs-app/editing-the-page)

![image](https://user-images.githubusercontent.com/121734574/230948205-3d0b649f-db6f-41e5-b701-f36a58bcfe03.png)

Second image (this page comes first in sequence):
![image](https://user-images.githubusercontent.com/121734574/230949148-c6f7f757-2333-4f16-bf4a-d11c09ec78e3.png)

**Comment by leerob** [comment]
We have a new course 😄  https://nextjs.org/learn
