### ISSUE TITLE
Docs: Update example images to include current Next.js logo

### ISSUE THREAD

**Issue by superdevjr** [vercel/next.js#48211]
### What is the improvement or update you wish to see?

Please update the graphics in the linked Doc to contain the most current version of the Next.js logo. 

### Is there any context that might help us understand?

![image](https://user-images.githubusercontent.com/121734574/230981662-891afde9-f0c6-425c-92dd-22e1185b3e14.png)

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/data-fetching/two-forms

**Comment by jhylacey** [comment]
Updated versions here at same resolution:

![image](https://user-images.githubusercontent.com/121734574/230982332-075697c4-a81f-4fde-b1b4-3d341687c78a.png)

![image](https://user-images.githubusercontent.com/121734574/230982659-fb4b6cf4-eb4c-4647-93b2-4b4971560313.png)

**Comment by khareyash05** [comment]
On it!!

**Comment by khareyash05** [comment]
hi @jhylacey I am not able to locate the image in the repo could you please help me with that?

**Comment by jhylacey** [comment]
> hi @jhylacey I am not able to locate the image in the repo could you please help me with that?

That page isn't included in the repo, which is why I'm posting this as an issue rather than a PR.

**Comment by leerob** [comment]
We'll be updating this as we refresh the course 🙏
