### ISSUE TITLE
Docs: Examples with more detailed steps 

### ISSUE THREAD

**Issue by DMF194** [vercel/next.js#48234]
### What is the improvement or update you wish to see?

Hi all,

I have recently started with full stack development with next.js with neo4j.

Using the example below.

https://github.com/vercel/next.js/tree/canary/examples/with-apollo-neo4j-graphql

Up until the https://localhost:3000/api/graphql, I was able to understand, but when I try to go to the movies page, the following error is shown.

> Error! number format error: interior "-" character: 1995-11-22 number format error: interior "-" character: 1995-12-15 number format error: interior "-" character: 1995-12-22 number format error: interior "-" character: 1995-12-22 number format error: interior "-" character: 1995-12-08 number format error: interior "-" character: 1995-12-15

When I checked back the query the data in the AuraDB instance, I found the dates saved were in string but 

`npm run dev`

It automatically turned the string into integer.

I feel like the instructions could describe the error handling of data formats for improvement

### Is there any context that might help us understand?

Would like to see some basic error handling or unit test to check if the data formats is consistent with the backend as shown in the AuraDB or other Neo4j instances.

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/tree/canary/examples/with-apollo-neo4j-graphql

**Comment by luchillo17** [comment]
Do you have a public repo to reproduce? Are you using the movies playground `:play movie-graph` data neo4j offers you as part of the tutorial? the example has in the `typeDefs` the year as an `Int` type, the same for the data of the playground, so that might be where the issue lies.

**Comment by leerob** [comment]
Closing as stale 🙏 Open to contributions to make that example better!
