### ISSUE TITLE
[NEXT-994] Links with parallel intercepted modals are not working

### ISSUE THREAD

**Issue by kristian240** [vercel/next.js#48232]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 7.27.0
    Relevant packages:
      next: 13.3.1-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/kristian240/parallel-interception-link-not-working

### To Reproduce

1. Go to `/feed`
2. Press random photo link -> random image will appear below & URL will be changed to `/photo`
3. Press back link will change the URL but the UI state won't
4. Pressing back browser's back button twice (/feed -- 1st click --> /photo -- 2nd click --> /feed) will show the correct UI state

### Describe the Bug

The UI is not changing when from intercepted route there is a link to the previous page. This is happening only in the development environment. 

### Expected Behavior

The UI should change when from intercepted route there is a link to the previous page. When production env is used it works - https://parallel-interception-link-not-working.vercel.app/

### Which browser are you using? (if relevant)

not relevant

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-994](https://linear.app/vercel/issue/NEXT-994/links-with-parallel-intercepted-modals-are-not-working)</sub>

**Comment by feedthejim** [comment]
seems fixed in the latest canary!
