### ISSUE TITLE
Supabase auth import server component

### ISSUE THREAD

**Issue by victorbillaud** [vercel/next.js#48251]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 7.30.0
    Relevant packages:
      next: 13.3.1-canary.4
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/mryechkin/nextjs-supabase-auth/tree/main

### To Reproduce

clone repo
run `pnpm i next@latest react@latest react-dom@latest eslint-config-next@latest supabase@latest` to get the latest version 
run `pnpm install` and `pnpm run dev` 

### Describe the Bug

```
./node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@vercel/og/index.node.js:17950:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/server.js
./node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.5.9_azjgpjpfyzbcykafu5t4hngxtm/node_modules/@supabase/auth-helpers-nextjs/dist/index.js
./src/lib/supabase-browser.js
./src/components/AuthProvider.js

``` 

The supabase module import a server component inside the client component and it makes crash the application :/

### Expected Behavior

No really excepted behavior but jsut working well. Maybe some explanations

**Comment by emilianoyaryura** [comment]
any updates on this?

**Comment by KajSzy** [comment]
This seems to be resolved by supabase team
https://github.com/supabase/auth-helpers/issues/493
