### ISSUE TITLE
Dynamic params in edge API routes 

### ISSUE THREAD

**Issue by vitalikda** [vercel/next.js#48263]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.1.1
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.3.0", newest: "13.3.1-canary.4".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Link to the code that reproduces this issue

https://github.com/vitalikda/edge-api-route-dynamic-params

### To Reproduce

Create edge api route with dynamic param and try to access it in production 

### Describe the Bug

When you try to access dynamic params from url, it’s prepend with nextParam string in production, so you can’t access the param

### Example
Edge Api route: https://github.com/vitalikda/edge-api-route-dynamic-params/blob/main/src/pages/api/%5Bid%5D/index.ts
- in dev mode req.nextUrl.searchParams.get('id') returns ID
- in prod: req.nextUrl.searchParams.get('id') returns null

Looking at the next url, there is prefix nextParam - `?nextParamid=hello-world`

Here is repo: https://github.com/vitalikda/edge-api-route-dynamic-params
Here is preview: https://edge-api-route-dynamic-params.vercel.app/

### Expected Behavior

Url search param should be accessible as in nodejs runtime 

### How are you deploying your application? (if relevant)

Vercel

**Comment by vitalikda** [comment]
I have updated next to the latest canary version - same result 

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.1.1
    Relevant packages:
      next: 13.3.1-canary.4
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by greidinger-reis** [comment]
I am having this same issue on edge runtime with dynamic segments, accessing params props on the page, throws type error. 
```
TypeError: Cannot read properties of undefined (reading 'orderId')
    at (node_modules/.pnpm/next@13.3.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/esm/server/app-render/app-render.js:175:0)
```

**Comment by pdparchitect** [comment]
Folks you have introduced a breaking change in 13.3 with zero documentation. It breaks assumptions and there is hardly anything in your CI to prevent breaking the build.

**Comment by garciajg** [comment]
Any news on this issue?

**Comment by timneutkens** [comment]
This was fixed on next@canary. New stable going out today/tomorrow 👍

**Comment by vitalikda** [comment]
Fixed! Updated example repo 👌
