### ISSUE TITLE
Docs: Head in client components

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#48266]
### What is the improvement or update you wish to see?

There is a explanation how to use metadata for server components but there is not way to do this though client components.

example use case when you want to update title with current total number of product in the cart or similar just for tab navigation purposes not for seo purposes.

### Is there any context that might help us understand?

no response

**Comment by joacub** [comment]
> I might be wrong but I believe the flow for client components is fairly similar. I do agree tho that this should be explained in more detail in the docs tho.

Well I don’t know but you can’t use `export metadata` in client components, idk if is a bug or is like that by design , I think is by design as the response is clear that you can not use that in client components so there is no way to put head metatags in client components.

**Comment by ALWISHARIFF** [comment]
How can you add then SEO meta tags to the head of client components since head.js file approach using the appdir does not export the  head meta tags in the head.js file into the out directory html files when exported using next export.

**Comment by joacub** [comment]
> What you can do is using the layout component with generateMetadata 👍

That’s pretty limited approach, imagine a web socket connection that updates the price of the bitcoin constantly or a number is charleta without see. The head component should not be removed for this kind of scenarios si the component can handle in client the title.

yeah we can get the document.title and update but the idea is to have this inside the whole structure for no colisions

**Comment by ALWISHARIFF** [comment]
```You are attempting to export "metadata" from a component marked with "use client",-```
I believe the Head.js file approach should be brought back since the approach in exporting components that use "use client" into the page.js route may lead to alot of file creations with components that use "use client"  and a lot of import statements and more files will have to be created.

**Comment by arnasofc** [comment]
Hello, guys I have this issue, the title is not changing even if I export the dynamic or static metadata, it changes only after page refresh but while navigating different pages it's staying the same. What to do?

**Comment by leerob** [comment]
You cannot use the Metadata API from Client Components 🙏 

https://nextjs.org/docs/app/building-your-application/optimizing/metadata
