### ISSUE TITLE
Middleware rewrite to edge router handler - Invariant: no match found for request

### ISSUE THREAD

**Issue by DaleLJefferson** [vercel/next.js#48295]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.18
      pnpm: 7.29.3
    Relevant packages:
      next: 13.3.1-canary.5
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/friendly-paper-t3xyol

### To Reproduce

Using the codesandbox or code below

Visit: /one/example

## middleware.ts
```ts
import { type NextRequest, NextResponse } from "next/server";

export function middleware(request: NextRequest) {
  const url = request.nextUrl;

  url.pathname = "/two/example";

  return NextResponse.rewrite(url);
}

export const config = {
  matcher: "/one/:path*",
};

```

## /app/two/example/route.ts
```ts
export const runtime = "edge";
export const dynamic = "force-dynamic";

export function GET() {
  return new Response("Example");
}
```

### Describe the Bug

A middleware rewrite to an edge route handler causes an error in the dev server.

`Error: Invariant: no match found for request. Pathname '/one/example' should have matched '/two/example'`

<img width="443" alt="image" src="https://user-images.githubusercontent.com/375005/231497198-bdf096a4-6ad1-43b4-abbc-83b4aed51f5e.png">

### Expected Behavior

Expect: Middleware to rewrite to /two/example successfully.

Same code works when runtime is set to `nodejs`

**Comment by eblanchette** [comment]
I think I'm experiencing something similar but with turbopack.  When I include prisma it breaks. I don't think it's considering the runtime flag.

/src/app/api/order/route.ts
```
export const runtime = "nodejs";
export const revalidate = 0;

import { PrismaClient } from "@prisma/client/mrp";
import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  const prisma = new PrismaClient();
  return NextResponse.json({
    foo: "bar",
  });
}
```

Error:
```
error rendering: Error: PrismaClient is unable to be run in the browser.

Debug info:
- error rendering: Error: PrismaClient is unable to be run in the browser.
  In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issuesstatus: signal: 9 (SIGKILL)
```

Error (if I move prisma up):
```
error rendering: TypeError: Cannot read properties of undefined (reading 'middleware_edge')

Debug info:
- error rendering: TypeError: Cannot read properties of undefined (reading 'middleware_edge')
```

**Comment by kaylynn234** [comment]
I believe I'm experiencing the same issue using Turbopack with `next-auth`; all requests to paths under `/api/auth` fail because of the same `TypeError: Cannot read properties of undefined (reading 'middleware_edge')`. To my knowledge `next-auth` uses middleware rewrites from a dynamic route, which is probably why.

That being said, I'm not sure why I'm encountering this issue in the first place; I'm not trying to use the edge runtime at all, and this should be running on the Node runtime. I have a feeling that @eblanchette's guess is correct, and the runtime flag is being ignored somehow.

I'm not sure if Turbopack lives in a separate repository - or where the next.js integration lives - but I'd be eager to contribute if possible.

**Comment by avmentzer** [comment]
same problem here

**Comment by godfrednanaowusu** [comment]
> I believe I'm experiencing the same issue using Turbopack with `next-auth`; all requests to paths under `/api/auth` fail because of the same `TypeError: Cannot read properties of undefined (reading 'middleware_edge')`. To my knowledge `next-auth` uses middleware rewrites from a dynamic route, which is probably why.
> 
> That being said, I'm not sure why I'm encountering this issue in the first place; I'm not trying to use the edge runtime at all, and this should be running on the Node runtime. I have a feeling that @eblanchette's guess is correct, and the runtime flag is being ignored somehow.
> 
> I'm not sure if Turbopack lives in a separate repository - or where the next.js integration lives - but I'd be eager to contribute if possible.

i believe this specifically happens in the next 13.3.0 version

the next 13.3.1 version has a different error

error rendering: Error: Cannot find module 'http'

**Comment by Royal-lobster** [comment]
This issue currently breaks usage of nextjs with next intl. hope it gets fixed or if we can get a work around to this issue

**Comment by kevinwolfcr** [comment]
Same issue for me. Switching back to `nodejs` runtime solved the issue.

**Comment by lukasburns** [comment]
Same issue here, using `export const runtime = 'nodejs'` solves this issue. would very much like to make it work with edge

**Comment by sam3d** [comment]
Also just bumped into this, forcing it off the edge runtime worked.

Looks like the fix for this isn't very complex, would be amazing to get some maintainer eyes on this

**Comment by bram209** [comment]
same issue, I would like to stay on the edge runtime, did anyone find a workaround (other than switching to nodejs)?

**Comment by AlexIsMaking** [comment]
> Error: Invariant: no match found for request. Pathname '/one/example' should have matched '/two/example'

I ran into this issue as described here - https://github.com/vercel/ai/issues/740.

But I wasn't using middleware and next 14.0.1 works fine, whereas 14.0.2 (re)introduces the issue.
