### ISSUE TITLE
Infinit loop when using useState

### ISSUE THREAD

**Issue by parweb** [vercel/next.js#48326]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.1.1
    Relevant packages:
      next: 13.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/github/parweb/demo-bug-next13/draft/async-smoke?file=%2Fsrc%2Flayouts%2FToggle.js&selection=%5B%7B%22endColumn%22%3A67%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A67%2C%22startLineNumber%22%3A12%7D%5D&workspace=%257B%2522activeFilepath%2522%253A%2522%252Fsrc%252Flayouts%252FToggle.js%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252Fapp%252Fpage.js%2522%252C%2522%252Fsrc%252Flayouts%252FToggle.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clgessp2200153b6zampbx9pp%2522%253A%257B%2522key%2522%253A%2522clgessp2200153b6zampbx9pp%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clgest23w008r3b6zi7movbx7%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clgest1cq00663b6zar2o2o3v%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clgessp2200153b6zampbx9pp%2522%252C%2522spacesOrder%2522%253A%255B%2522clgessp2200153b6zampbx9pp%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### To Reproduce

go to the homepage
click on the button show me (component src/layouts/Toggle.js)
see console log in dev tools

### Describe the Bug

when clicking on the "show me" button an infinit rerender is produce 
visible by viewing in dev tools all the console.log

### Expected Behavior

when clicking on the "show me" button
see one console.log with toggle variable value

### Which browser are you using? (if relevant)

chrome 112.0.5615.49

**Comment by washingtonsoares** [comment]
Hi @parweb, well as you have a client component, I think there is no need to `async` export the `src/layouts/Toggle.js` component file. So it should work fine once you remove the `async` keyword.
Exporting it using `async` and using it exclusively in the client could cause some weird behaviors, but I don't know exactly how to explain it. 
This is what I found out from the docs:

> Components in the Client Component module graph are primarily rendered on the client, but with Next.js, they can also be prerendered on the server and hydrated on the client.

https://beta.nextjs.org/docs/rendering/server-and-client-components

**Comment by parweb** [comment]
you are right removed the async and it work fine
