### ISSUE TITLE
Turbopack with Next config option "compiler - emotion or styledComponents" do not work

### ISSUE THREAD

**Issue by gurkerl83** [vercel/next.js#48341]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.6
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue

No reproduction

### To Reproduce

Create a new project, turbopack instruction

```
npx create-next-app --example with-turbopack
```

Replace next with latest canary in my case 13.3.1-canary.6. Set config option "compiler - emotion or styledComponents", this landed just a few hours before the canary version mentioned was build.

```
compiler: {
   styledComponents: true,
   emotion: true
}
```

### Describe the Bug

Still receiving that compiler is not supported at all. Guess there is a problem how configuration object "compiler" gets evaluated in https://github.com/vercel/next.js/blob/e97100c5eaff9351ab8b6c83c5341994f22f60e9/packages/next/src/lib/turbopack-warning.ts

Unsupported Next.js configuration option(s) (next.config.js)
  To use Turbopack, remove the following configuration options:
    - compiler
  The only supported configurations options are:
    - configFileName
    - env
    - experimental.appDir
    - compiler.emotion
    - compiler.styledComponents
    - experimental.serverComponentsExternalPackages
    - experimental.turbo
    - images
    - pageExtensions
    - onDemandEntries
    - rewrites
    - redirects
    - headers
    - reactStrictMode
    - swcMinify
    - transpilePackages

### Expected Behavior

When the compiler options are white-listed they should work similar to the experimental object. In https://github.com/vercel/next.js/blob/e97100c5eaff9351ab8b6c83c5341994f22f60e9/packages/next/src/lib/turbopack-warning.ts extra steps are required to eval the experimental option, for the compiler option I can not see any of those steps in warning.ts

### How are you deploying your application? (if relevant)

Executing the dev script in package.json generates the bug

```
"dev": "next dev --turbo",
```

yarn dev

**Comment by MonstraG** [comment]
It seems that since then, the check has been updated and it lets you run it with 
```
compiler: {
    emotion: true
}
```

Did not work on 13.3.4, works on 13.4.12.

**Comment by ForsakenHarmony** [comment]
Should be working
