### ISSUE TITLE
Beta Docs: Metadata page incorrectly uses ReactDOM.preload() for <link rel="preconnect" /> example

### ISSUE THREAD

**Issue by GeorgeIpsum** [vercel/next.js#48356]
### What is the improvement or update you wish to see?

On https://beta.nextjs.org/docs/api-reference/metadata#link-relpreconnect:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/2670350/231854433-72d0fbb8-ac37-4a57-bb95-c05a56f5d320.png">

The example listed here used `ReactDOM.preload` instead of `ReactDOM.preconnect` here. As far as I know, this is incorrect, but the appropriate function can just be swapped in. Super easy fix! (Didn't see where if possible to create a PR for beta docs changes)

### Is there any context that might help us understand?

This should be it

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/metadata#link-relpreconnect

**Comment by Maroben** [comment]
The function `ReactDOM.preload` also does not seem to exist. See: https://react.dev/reference/react-dom

I think the documentation example file should probably look like this.

```
'use client'

import ReactDOM from 'react-dom/client'

export function PreloadResources() {
  ReactDOM.createRoot(document.head).render(<link rel='preconnect' href='https://fonts.googleapis.com' />)

  return null
}
```

**Comment by gtomitsuka** [comment]
I'm trying to use this, but PreloadResources seems unused. Do I need to import `app/preload-resources.tsx` or add it to a config somewhere? `PreloadResources` or `preload-resources.tsx` are nowhere to be found in the source code either.

**Comment by atakanatamert** [comment]
I've had the same issue as @gtomitsuka. What I did to solve is, import `app/preload-resorces.tsx` on `app/layout.tsx`, then use it like so;  

```
import { PreloadResources } from "./preload-resources";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <PreloadResources />
      <body>{children}</body>
    </html>
  );
}
```
After that change it worked as expected. That said, I'm not sure it is correct way to do it.

**Comment by HamAndRock** [comment]
I see app router is still using <Head>tags for Next/Image prefetches. I assume it should be replace with ReactDOM.preload().

Here: https://github.com/vercel/next.js/blob/18d112fb5ca62bdb7b1361a65c7e33615d16bdd1/packages/next/src/client/image.tsx#LL959C12-L959C12

https://github.com/vercel/next.js/issues/50694
