### ISSUE TITLE
[NEXT-1200] Misplaced script tags in HTML when using appDir

### ISSUE THREAD

**Issue by rayokamoto** [vercel/next.js#48372]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 13.3.1-canary.6
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-gq2mmt

### To Reproduce

Create any Next.js application using the appDir feature. The reproduction template for the appDir feature will be used for this example.
```shell
npx create-next-app -e reproduction-template-app-dir
```
Run the development server or run in production mode, the issue persists regardless.
```shell
npm run dev
# or
npm start
```
Go to the network tab and select the root file. Go to the response tab and view the raw HTML. On Firefox, it looks something like this:
![image](https://user-images.githubusercontent.com/22254748/231933946-95ef994c-d905-457f-8285-ad4459662074.png)

Chrome:
![image](https://user-images.githubusercontent.com/22254748/231934040-447ff8db-5b39-4863-a767-664093ea5ab5.png)

To see if the issue exists, the website using the appDir feature can also be put through the W3 validator, which will identify whether there are misplaced script tags or not. As an example, use Vercel's App Router website: https://app-dir.vercel.app

**Results**
https://validator.w3.org/nu/?doc=https%3A%2F%2Fapp-dir.vercel.app

![image](https://user-images.githubusercontent.com/22254748/231937210-0ef9f166-e875-475a-8db7-beee60e9640b.png)

### Describe the Bug

When using the appDir feature, misplaced/stray script tags are present, meaning that there are script tags that are placed outside of the closing `</html>` element. An example of this is shown below:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="/_next/static/css/app/page.css"
      data-precedence="next.js"
    />
    <link
      rel="stylesheet"
      href="/_next/static/css/app/layout.css"
      data-precedence="next.js"
    />
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="\favicon.ico" type="image/x-icon" sizes="any" />
    <script src="/_next/static/chunks/polyfills.js" nomodule=""></script>
  </head>
  <body>
    <!-- Body content -->
  </body>
</html>
<script>
  (self.__next_f = self.__next_f || []).push([0]);
</script>
<script>
  self.__next_f.push([1, '0:"$L1"\n']);
</script>
<script>
  self.__next_f.push([
    1,
    '2:I{"id":"(app-client)/./node_modules/next/dist/client/components/app-router.js","name":"","chunks":["app-client-internals:app-client-internals"],"async":false}\n4:I{"id":"(app-client)/./node_modules/next/dist/client/components/error-boundary.js","name":"","chunks":["app-client-internals:app-client-internals"],"async":false}\n6:I{"id":"(app-client)/./node_modules/next/dist/client/components/layout-router.js","name":"","chunks":["app-client-internals:app-client-internals"],"async":false}\n7:I{"id":"(app-client)',
  ]);
</script>
<script>
  self.__next_f.push([
    1,
    '/./node_modules/next/dist/client/components/render-from-template-context.js","name":"","chunks":["app-client-internals:app-client-internals"],"async":false}\n8:I{"id":"(app-client)/./node_modules/next/dist/client/image.js","name":"","chunks":["app/page:app/page"],"async":false}\n',
  ]);
</script>
<!-- Script tags continue -->
```

These script tags are automatically generated by Next.js and do not appear to be scripts that are inserted via the `<Script />` component.

I have also confirmed that this issue is not present when using the `pages/` directory, tested on the latest canary release.

### Expected Behavior

The HTML should not contain any misplaced script tags (stray start tag `script`). All script tags should be placed inside the `<body>` tag instead.

<sub>[NEXT-1200](https://linear.app/vercel/issue/NEXT-1200/misplaced-script-tags-in-html-when-using-appdir)</sub>

**Comment by mauricekleine** [comment]
I can verify that even now that the App dir is stable in Next.js 13.4.0, this still happens: https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.mauricekleine.com%2F
