### ISSUE TITLE
Docs: Sitemap for Google Search console based on Nextjs maunal sitemap docs 

### ISSUE THREAD

**Issue by niemiaszek** [vercel/next.js#48405]
### What is the improvement or update you wish to see?

I would like to see more examples for sitemap.xml and robots.txt generation with metadata (for example how to generate sitemap with multiple Allow/Disallow rules or many agents). I've got a bit confused, looking at _learn_ article vs _beta docs_. More context below.

### Is there any context that might help us understand?

I'm currently developing my first webpage using Nextjs. I wanted to setup my web to be searchable. I find it really troubling to do with current docs.

I've seen [this article in learn section](https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps) and I've setup sitemap just like it in [my code](https://github.com/niemiaszek/exchange-office-webpage/blob/10e7fd0a1aa3a2511356848ebf8d232dedfffd5f/public/sitemap.xml). However, I got hit with "unsupported file format" just like in [this Stack Oveflow issue](https://stackoverflow.com/questions/73745828/xml-sitemap-unsupported-file-format-next-js). I've changed my sitemap from `<xml version="1.0" encoding="UTF-8">...</xml>` to `<?xml version="1.0" encoding="UTF-8"?>`. This got my sitemap working for Google Search Console.

I wanted to check out if there's anything on this topic in _beta_ docs and I've found sitemaps and robots.txt mentioned in [metadata api reference](https://beta.nextjs.org/docs/api-reference/metadata#sitemap). Can I switch to approach shown here for robots and sitemap, using `import { MetadataRoute } from 'next';`? How do I list here multiple allow/disallow rules for robots?

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/metadata#robots-file

**Comment by leerob** [comment]
https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
