### ISSUE TITLE
[NEXT-1021] parallel-route-default not resolved if .js is not in the page extensions

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#48431]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 3.5.0
      pnpm: 8.1.0
    Relevant packages:
      next: 13.3.1-canary.8
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/juliusmarminge/intercepting-routes-repro

### To Reproduce

1. Clone repo
2. Start dev - you'll get this error:

<details>
<summary>Error log</summary>

```
error - uncaughtException: Error: . is neither a posix nor a windows path, and there is no 'join' method defined in the file system
    at join (/Users/julius/Dev/sandbox/next-intercept/node_modules/.pnpm/next@13.3.1-canary.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:1346037)
    at /Users/julius/Dev/sandbox/next-intercept/node_modules/.pnpm/next@13.3.1-canary.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:289998
    at arrayEachIndex (/Users/julius/Dev/sandbox/next-intercept/node_modules/.pnpm/next@13.3.1-canary.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:7165)
    at Object.map (/Users/julius/Dev/sandbox/next-intercept/node_modules/.pnpm/next@13.3.1-canary.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/neo-async/async.js:1:9971)
    at Array.<anonymous> (/Users/julius/Dev/sandbox/next-intercept/node_modules/.pnpm/next@13.3.1-canary.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:28:289973)
    at runCallbacks (/Users/julius/Dev/sandbox/next-intercept/node_modules/.pnpm/next@13.3.1-canary.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:1:152096)
    at /Users/julius/Dev/sandbox/next-intercept/node_modules/.pnpm/next@13.3.1-canary.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:1:154008
    at /Users/julius/Dev/sandbox/next-intercept/node_modules/.pnpm/next@13.3.1-canary.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/webpack/bundle5.js:1:253738
    at FSReqCallback.oncomplete (node:fs:192:23)
```

</details>

3. Add a `default.tsx` with a default null export: `export default () => null;
` in root and the parallel modal route:

![CleanShot 2023-04-15 at 22 55 40](https://user-images.githubusercontent.com/51714798/232252783-8dfbee20-6ac6-4aa4-b69f-4e8f294c51f8.png)

4. Restart dev - error gone.

### Describe the Bug

Intercepting + Parallel route modals require a `default.tsx` file or else the app crashes (or atleast freezes), see demo below.

https://user-images.githubusercontent.com/51714798/232252868-fefe124e-144a-4402-b5b5-fa00edd8ba5a.mp4

### Expected Behavior

App should work without the `default.tsx`.

As stated in docs, it should only be required as a fallback after hard-refreshes: https://beta.nextjs.org/docs/routing/parallel-routes#defaultjs

And @timneutkens mentioned there should be a default provided by next: https://twitter.com/timneutkens/status/1647282559573794817?s=20

So the app should run fine without these "null-barrel-exports".

Weirdly enough, [vercel-labs/nextgram](https://github.com/vercel-labs/nextgram) runs fine even after deleting these 2 default files...

<sub>[NEXT-1021](https://linear.app/vercel/issue/NEXT-1021/bugnext-intercepting-routes-not-working-without-defaulttsx)</sub>

**Comment by feedthejim** [comment]
So I took a look @juliusmarminge, this was a pretty funny one :) so the reason why it specifically caused an error on your project was that your next.config only allows for tsx or mdx files with the pageExtensions config, so it would not resolve the default.js file provided by Next.js.

Fix incoming.

Note: in your example, you'd still need a default for the @modal slot.

**Comment by juliusmarminge** [comment]
Interesting... Allowing `mdx` pages has now shot me in the foot twice 😇 

> Note: in your example, you'd still need a default for the @modal slot.

Why is that? Shouldn't the default provided by you take care of that?

**Comment by feedthejim** [comment]
@juliusmarminge the default.js provided returns a 404 by design.

 The reason is because of things like this:
```/app/[slug]/layout.js
/app/[slug]/@user/profile/page.js
/app/[slug]/@team/members/page.js
function Layout({ params: { slug }, user, team }) {
  return isTeam(slug) ? team : user;
}```
If I visit /feedthejim/members that should be a 404 because there's no "members" page of a user.

The doc should be updated soon to include all of those complicated nuances.
