### ISSUE TITLE
The project won't even build and I can't figure out what's wrong. It just says JSON undefined.

### ISSUE THREAD

**Issue by clearly-outsane** [vercel/next.js#48436]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/clearly-outsane/To-be-deleted

### To Reproduce

Not sure at all. 

### Describe the Bug

![image](https://user-images.githubusercontent.com/44093134/232255825-9de02570-9235-4442-824a-931df565e79b.png)
![image](https://user-images.githubusercontent.com/44093134/232256030-868f4a09-7ed3-4b2e-ad39-42aa5c5eb963.png)

`SyntaxError: Unexpected token u in JSON at position 0 at JSON.parse (<anonymous>)`

This is all I see in the console. I genuinely have no idea what this error means. The project won't even build

### Expected Behavior

Not sure what the expected behaviour should be.

**Comment by HamAndRock** [comment]
Fixed in canary, Windows only issue from what I could understand. Had the same issue as you did.

**Comment by avmentzer** [comment]
Same here. The project builds but throws an error:

`SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)`

When using turbopack the error vanished, but then the api routes aren't working anymore(500 internal server error), because of the "middleware edge" bug.

Specs:
Win 11 latest updates
Node 18.15
Nextjs canary@latest

Also all other version of nextjs 13.2 are not working anymore. Hope this get fixed soon.

**Comment by shuding** [comment]
Fixed together with https://github.com/vercel/next.js/issues/47704, please upgrade to the latest version.
