### ISSUE TITLE
Problem occurs when returning to main page via navbar from not-found page

### ISSUE THREAD

**Issue by bysxx** [vercel/next.js#48444]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 3.3.1
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.8
      eslint-config-next: 12.1.6
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/bysxx/next-ts-template-tailwind

### To Reproduce

Example: https://next-ts-template-tailwind.vercel.app/

1. access the link (https://next-ts-template-tailwind.vercel.app/any-path)
2. return to Home via navbar
3. Home Page not rendered <- **Problem**

### Describe the Bug

Not rendered problem occurs when returning to main page via navbar from not-found page

### Expected Behavior

The way the page.tsx in the app compares to the current route seems to be twisted

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

vercel

**Comment by avionanx** [comment]
Happens on Windows 10, Next 13.3.0, node 19.0.0 aswell.

**Comment by dudusotero** [comment]
Happens on MacOS 13.3.1, Next 13.3.0, Node 16.20.0.

```tsx
// not-found.tsx
import Link from "next/link";

export default function NotFound() {
  return (
    <main className="flex flex-col gap-4">
      <h1>404 Page</h1>
      <Link href="/">Go to Home</Link>
      <Link href="/about">Go to About</Link>
    </main>
  );
}
```
All other routes are working as expected, same code structure.

**Comment by Marshall-Hao** [comment]
same here!!
Happens on MacOS Ventura 13.0, Next 13.3.0 node 14.18.3
```
"use client";
import { Link } from "@chakra-ui/next-js";
import {
  Box,
  Heading,
  Container,
  Divider,
  Button,
  Text,
} from "@chakra-ui/react";

const NotFound = () => {
  return (
    <Container>
      <Heading as="h1">Not found</Heading>
      <Text>
        The page you&apos;re looking for was not found.
      </Text>
      <Divider my={6} />
      <Box my={6} textAlign="center">
        <Button as={Link} href="/" colorScheme="teal">
          Return to home
        </Button>
      </Box>
    </Container>
  );
};

export default NotFound;
```
if i navigate to an non-exsit page from the home page, the not-found wont be trigger!
But if i go directly to an non-exsit page, it will show, but if i navigate to the home page with the Link(next/link), the page componet does not updated!

**Comment by T99** [comment]
It appears that this is the main issue for this bug: #47862.

**Comment by jahirfiquitiva** [comment]
Is this the same issue I reported at https://github.com/vercel/next.js/issues/48367 ? 🤔
