### ISSUE TITLE
Version 13.3.0 breaks images on AS Amplify

### ISSUE THREAD

**Issue by baltagih2** [vercel/next.js#48453]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.2.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

N/A

### To Reproduce

- Have a working website (using app directory) on 13.2.4
- Upgrade to 13.3.0
- If the website is hosted on AWS Amplify, all images break

Important note: This bug only appears in production (after deploying to AWS Amplify)

Reverting to 13.2.4 fixes the issue

Confirmed that the issue exists in 13.3.1-canary.8
Confirmed that it is not a caching issue

### Describe the Bug

Images break (the image broken icon shows up with the `alt` message) in production when hosting on AWS Amplify.

### Expected Behavior

The images should display as normal

### Which browser are you using? (if relevant)

Chrome 112.0.5615.49, but also happens on Safari and Firefox

### How are you deploying your application? (if relevant)

AWS Amplify

**Comment by n3ih7** [comment]
Duplicate and here's the similar one. 
https://github.com/vercel/next.js/issues/48077#issuecomment-1504501461
