### ISSUE TITLE
[NEXT-1156] Using an external package that imports `next/server` incorrectly bundles `@vercel/og`

### ISSUE THREAD

**Issue by solaldunckel** [vercel/next.js#48469]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.6.3
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.3.1-canary.8
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/solaldunckel/next-13-bundle-size-issue

### To Reproduce

1. Create a route handler on the edge
2. Import an external package that uses `NextResponse` or `NextRequest` (e.g `@clerk/nextjs`)
3. Notice that `@vercel/og` gets bundled in the route handler

### Describe the Bug

After updating to Next.js version 13.3, I noticed a significant increase in the size of my edge functions on Vercel. Upon investigation, I found that a new `ImageResponse` export in `next/server` is now included by default.

One of the packages I use, `@clerk/nextjs`, imports `NextResponse` which causes the `@vercel/og` package to be bundled into the function.
You can see in those screenshots the bundle size increase when importing the external package `@clerk/nextjs`

<img width="1214" alt="Screenshot 2023-04-17 at 10 30 13" src="https://user-images.githubusercontent.com/37122137/232429646-ff8668df-fc94-45e7-8132-64abf3fed3ed.png">
<img width="1209" alt="Screenshot 2023-04-17 at 10 30 20" src="https://user-images.githubusercontent.com/37122137/232429671-4a51b312-1040-4761-bdcf-a90c344d3fe5.png">

An error message also appears when running `next build`, which correspond to the size of `@vercel/og/index.edge.js`

```
[webpack.cache.PackFileCacheStrategy] Serializing big strings (659kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
```

The only way I found to fix the issue was to patch the external package to import`NextResponse` and `NextRequest` directly from `next/dist/server/web/exports/`

### Expected Behavior

Importing from `next/server` in an external package shouldn't cause `@vercel/og` to be bundled.

<sub>[NEXT-1156](https://linear.app/vercel/issue/NEXT-1156/using-an-external-package-that-imports-nextserver-incorrectly-bundles)</sub>

**Comment by av-erencelik** [comment]
Hey, I am experiencing the same problem too. I can't deploy to vercel because edge function size is bigger than 1mb and getting the same errors like you. Did you find any workarounds or solutions for this?

**Comment by solaldunckel** [comment]
The only workaround I found is patching `@clerk/nextjs` to modify all imports from `next/server` to the corresponding export. It's actually what Next.js is doing during compilation (sadly not on external packages).

https://github.com/vercel/next.js/blob/8050a6c8e056efb336f15f6fa5be789cd040574d/packages/next-swc/crates/core/src/lib.rs#L162-L169

One example of the patch for the `withClerkMiddleware.js` file : 

```diff
--- a/dist/server/withClerkMiddleware.js
+++ b/dist/server/withClerkMiddleware.js
@@ -2,7 +2,7 @@
 Object.defineProperty(exports, "__esModule", { value: true });
 exports.handleMiddlewareResult = exports.withClerkMiddleware = exports.decorateResponseWithObservabilityHeaders = void 0;
 const backend_1 = require("@clerk/backend");
-const server_1 = require("next/server");
+const NextResponse = require("next/dist/server/web/exports/next-response").default;
 const constants_1 = require("../constants");
 const clerk_1 = require("./clerk");
 const errors_1 = require("./errors");
@@ -93,7 +93,7 @@ exports.withClerkMiddleware = withClerkMiddleware;
 function handleMiddlewareResult({ req, res, authStatus, authMessage, authReason, }) {
     // pass-through case, convert to next()
     if (!res) {
-        res = server_1.NextResponse.next();
+        res = NextResponse.next();
     }
     // redirect() case, return early
     if (res.headers.get(constants_1.constants.Headers.NextRedirect)) {
```

It made my edge functions less than 1mb so it should also fix your deploys on Vercel :)

**Comment by av-erencelik** [comment]
@solaldunckel thanks for very detailed answer. I tried your solution and it works. I posted this issue on Clerk's discord and they suggested to downgrading to earlier version of Next.js until Vercel fix it. They said they were in contact with the next team and reported the problem.

**Comment by amannn** [comment]
The `next-intl` middleware is also affected by this: https://github.com/amannn/next-intl/discussions/297

**Comment by shuding** [comment]
This problem should be fixed with the next canary release, thanks for bringing it up!
