### ISSUE TITLE
NEXT_PUBLIC_VERCEL_URL is undefined

### ISSUE THREAD

**Issue by paqstd-dev** [vercel/next.js#48477]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.0.1
      npm: 9.1.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.2.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/cranky-water-bbvl11

### To Reproduce

Deploy to vercel:
```
vercel build
vercel deploy --prebuilt
```

Open url (for example [my deploy build](https://vercel-public-url-implementation.vercel.app)) and watch:
<img width="557" alt="Снимок экрана 2023-04-17 в 14 27 19" src="https://user-images.githubusercontent.com/26341266/232471143-1076cce1-6d2f-4493-a033-50ccd2826ae4.png">

### Describe the Bug

I don't understand how can I use `NEXT_PUBLIC_VERCEL_URL` in my application? The [documentation](https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables#framework-environment-variables) states that this variable is automatically available. However, I am getting undefined in the browser.

I also tried specifying `next.config.js` as `env`, but that doesn't work either:
```js
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
  output: 'standalone',
  swcMinify: true,
  env: {
    NEXT_PUBLIC_VERCEL_URL: process.env.VERCEL_URL,
  },
}

module.exports = nextConfig
```

In my code it works only for server rendering, but "undefined" type for client:
```js
// configs/index.ts
export const VERCEL_URL = process.env.VERCEL_URL ?? process.env.NEXT_PUBLIC_VERCEL_URL
```

I also tried to specify in .env.production. In such a case, I get an empty string "" instead of the expected VERCEL_URL:
```env
# .env.production
NEXT_PUBLIC_VERCEL_URL=${VERCEL_URL}
```

I would be grateful for any ideas and tips. 

### Expected Behavior

I would like to automatically receive the current url both on the server and on the client, without manually specifying this information somewhere.

Now for deployment, I manually execute the commands `vercel build` and `vercel deploy --prebuilt`. But I also have a config for github actions to trigger the deployment automatically. In this case, I can not manually change VERCEL_URL somewhere. I need link for every deploy (not only production and preview links).

### Which browser are you using? (if relevant)

Safari 16.4 (18615.1.26.11.23) and Google Crome 112.0.5615.49

### How are you deploying your application? (if relevant)

Vercel

**Comment by paqstd-dev** [comment]
Also I created discussion [NEXT_PUBLIC_VERCEL_URL for auto deploy on Vercel](https://github.com/vercel/next.js/discussions/48391), but it seems this issue can help me faster.

**Comment by Garett-MacGowan** [comment]
I'm also seeing undefined values in my envrionment. I'm pretty sure I had this working before.

**Comment by paqstd-dev** [comment]
Now it works. I didn't change anything in my code. Perhaps this is a server error of Vercel itself.
