### ISSUE TITLE
Next.js does not recognize `use client`...

### ISSUE THREAD

**Issue by alsrb0504** [vercel/next.js#48486]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/alsrb0504/Next.js-Blog-Clone-Coding---Dream-Coding/commit/dacdfcdc4624b7d4f8f8caf0c89efb35e622f1b1

### To Reproduce

Declaring the use client at the top of a client component using the ` `` ` symbol causes Next.js to fail to recognize the use client, resulting in an error.

### Describe the Bug

In Next.js, if you enter 'use client' at the top of a component to use 'useState', Next.js interprets it as a string and displays an error such as `You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.`

### Expected Behavior

Honestly I'm not sure if this feature was intended by Next.js team.

But I wasted a lot of time because of this problem.. Personally, I would like the Next.js team to have a feature that specifies use client to use double quotes when the above issue is the case.

### Which browser are you using? (if relevant)

chrome

**Comment by ivoiv** [comment]
Isn't the issue that `` are interpolated at runtime due to placeholder expressions?

I don't see how nextjs can recognize \`use client\` without it compiling your project once to resolve template literals and then compiling it a second time.

**Comment by alsrb0504** [comment]
Wow... I used to think that template literals were treated the same as string in JavaScript. I'm learning something new. Thank you.
