### ISSUE TITLE
404 on parallel route, even though a `default.tsx` has been provided

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#48509]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Sun Apr  2 19:24:16 PDT 2023; root:xnu-8796.120.31~10/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.18
      pnpm: 7.1.0
    Relevant packages:
      next: 13.3.0
      eslint-config-next: N/A
      react: N/A
      react-dom: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/Fredkiss3/parallel-routes-modal-next

### To Reproduce

1. clone the repo, 
2. Install & run the next server
3. click on the first board (the URL is : http://localhost:3001/boards/oWNLDSH2nQTVrDcWS3zg7o)
4. click on one card, the card will show
5. without changing the route, reload the browser, you will have a 404

### Describe the Bug

I wanted to use parallel routes to show 2 pages at the same page in the same route, something like this : 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/38298743/232614480-b5384481-9c9f-4deb-890e-016ae1dbd76d.png">

The first problem i encountered was that i needed to add a `default.tsx` at every level, or else i would have a 404 : 

```
.
├── boards/
├── page.tsx
└── [bid]
    ├── page.tsx
    ├── layout.tsx
    └── @card_modal/
        ├── default.tsx <-- here
        └── cards/
            ├── default.tsx <-- here
            └── [cid]/
                ├── page.tsx
                └── default.tsx <-- here
```

Then while being on the same route, if i reload the page i get a 404 even though a default.tsx is defined for every page. 
To fix the error i tried to add a `default.tsx` at the same level as the `layout.tsx` but it gives me a hydration error and on reload it shows the content of `default.tsx` with the modal instead of  the content of `page.tsx`. 

I should also note that the modal is rendered without a condition : 

```tsx
import * as React from "react";

export default function BoardDetailsLayout({
  children,
  card_modal,
}: {
  children: React.ReactNode;
  card_modal: React.ReactNode;
}) {
  return (
    <>
      {children}
      {card_modal}
    </>
  );
}
```

### Expected Behavior

the modal should be shown without the need to add a `default.tsx` everywhere, and it should not throw a 404 on page reload. 

### Which browser are you using? (if relevant)

firefox

### How are you deploying your application? (if relevant)

vercel

**Comment by feedthejim** [comment]
Yeah so like I mentioned in DMs, you need a default for children slot in your layout where you are rendering the modal, so you want to add one at that level. This will be mentioned in the docs.
