### ISSUE TITLE
Next.js doesn't respect { cache: "no-store" } setting in ky 

### ISSUE THREAD

**Issue by Talent30** [vercel/next.js#48519]
What is ky? Tiny & elegant JavaScript HTTP client based on the browser Fetch API
https://github.com/sindresorhus/ky

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.3.1-canary.11
      eslint-config-next: 13.3.1-canary.11
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/ecstatic-dawn-p2skov

### To Reproduce

npm run build

### Describe the Bug

When you set { cache: "no-store" } in ky Next.js still trying to generate static page during build time 

### Expected Behavior

Skip fetching during build time

**Comment by rafaelalmeidatk** [comment]
I am pretty sure this happens because `ky` does not use the native `fetch` implementation which is what `next` modifies:

https://github.com/sindresorhus/ky-universal/blob/349bbe429dd9a9bed7d1cf18d1a2c4ff4b656fe0/index.js#L1

**Comment by Talent30** [comment]
Hi, @rafaelalmeidatk. I am using ky, not ky-universal. 

Ref: https://github.com/sindresorhus/ky/issues/501

**Comment by rafaelalmeidatk** [comment]
> Hi, @rafaelalmeidatk. I am using ky, not ky-universal.

Did you try my suggestion of passing `fetch` as an option to `ky`?

**Comment by rafaelalmeidatk** [comment]
@Talent30 I was able to use `ky` with `{ cache: "no-store" }` just fine, I created a repro here: https://github.com/rafaelalmeidatk/nextjs-13-ky

I chose an API that you could see the data changing (the time) but it is kinda flaky so expect some errors when reloading the page, but the data is changing as expected

**Comment by Talent30** [comment]
> @Talent30 I was able to use `ky` with `{ cache: "no-store" }` just fine, I created a repro here: https://github.com/rafaelalmeidatk/nextjs-13-ky/blob/9810419345647a396bf75ee40a68d32b164e42e3/app/page.tsx#L7
> 
> I chose an API that you could see the data changing (the time) but it is kinda flaky so expect some errors when reloading the page, but the data is changing as expected
> 
> Let me know if I missed something from your setup

Yes in this example at `runtime`, `{ cache: "no-store" }` is working as expect. 

However, my example is trying to proof that with `{ cache: "no-store" }` next.js is still trying to fetch data at `build time`(when you are building the app next.js is trying to statically generate the page) which it shouldn't with `{ cache: "no-store" }`.

**Comment by rafaelalmeidatk** [comment]
> However, my example is trying to proof that with { cache: "no-store" } in ky next.js is still trying to fetch data at build time(when you are building the app next.js is trying to statically generate the page) which it shouldn't with { cache: "no-store" }.

@Talent30 I am not sure `ky` has anything to do with this? `fetch` has the exact same behavior in my repro. This is because every segment is static by default, so they are built at build time since the pages need to be pre-rendered. You can change this behavior by using a diferent [Segment Config Option](https://beta.nextjs.org/docs/api-reference/segment-config#dynamic), in this case it looks like you are looking for `force-dynamic`? This will avoid the request at build-time
```js
export const dynamic = 'force-dynamic'
```

**Comment by Talent30** [comment]
@rafaelalmeidatk First of all I would like to thank you for being so patient with me in discussing this issue.

1. I found that in your repo, the setting is `{ cache: 'no-cache' }` instead of `{ cache: 'no-store' }`. Here is a [working example](https://codesandbox.io/p/github/Talent30/nextjs-13-ky/draft/sweet-edison?file=%2FREADME.md&workspace=%257B%2522activeFilepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fapp%252Fpage.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clgoolwd500sj3b6ivu98q7o6%2522%253A%257B%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clgoolwjr000tg4g0bndx8glm%2522%252C%2522key%2522%253A%2522clgoolwd400si3b6i93j089e3%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%252C%2522key%2522%253A%2522clgoolwd500sj3b6ivu98q7o6%2522%252C%2522name%2522%253A%2522Terminal%2522%257D%257D%252C%2522currentSpace%2522%253A%2522clgoolwd500sj3b6ivu98q7o6%2522%252C%2522spacesOrder%2522%253A%255B%2522clgoolwd500sj3b6ivu98q7o6%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D) with fetch which next.js respects the `{ cache: "no-store" }` setting(no fetch during build time). However I cannot reproduce the same result with ky.




2. According to the documentation, `{ cache: 'no-store' }` within each fetch should be respected.
`export const dynamic = 'force-dynamic'` is a way to change cache option of every fetch under the segment. I would like to use it as the last resort.
```
'force-dynamic': Force dynamic rendering and dynamic data fetching of a layout or page by disabling all caching of fetch requests and always revalidating. This option is equivalent to:

getServerSideProps() in the pages directory.
Setting the option of every fetch() request in a layout or page to { cache: 'no-store', next: { revalidate: 0 } }.
Setting the segment config to export const fetchCache = 'force-no-store'
```

**Comment by vasco3** [comment]
ah, GitHub copilot tricked me into typing `'no-cache'`. Thanks for pointing that out


> @rafaelalmeidatk First of all I would like to thank you for being so patient with me in discussing this issue.
> 
> 1. I found that in your repo, the setting is `{ cache: 'no-cache' }` instead of `{ cache: 'no-store' }`. Here is a [working example](https://codesandbox.io/p/github/Talent30/nextjs-13-ky/draft/sweet-edison?file=%2FREADME.md&workspace=%257B%2522activeFilepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fapp%252Fpage.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clgoolwd500sj3b6ivu98q7o6%2522%253A%257B%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clgoolwjr000tg4g0bndx8glm%2522%252C%2522key%2522%253A%2522clgoolwd400si3b6i93j089e3%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%252C%2522key%2522%253A%2522clgoolwd500sj3b6ivu98q7o6%2522%252C%2522name%2522%253A%2522Terminal%2522%257D%257D%252C%2522currentSpace%2522%253A%2522clgoolwd500sj3b6ivu98q7o6%2522%252C%2522spacesOrder%2522%253A%255B%2522clgoolwd500sj3b6ivu98q7o6%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D) with fetch which next.js respects the `{ cache: "no-store" }` setting(no fetch during build time). However I cannot reproduce the same result with ky.
> 2. According to the documentation, `{ cache: 'no-store' }` within each fetch should be respected.
>    `export const dynamic = 'force-dynamic'` is a way to change cache option of every fetch under the segment. I would like to use it as the last resort.
> 
> ```
> 'force-dynamic': Force dynamic rendering and dynamic data fetching of a layout or page by disabling all caching of fetch requests and always revalidating. This option is equivalent to:
> 
> getServerSideProps() in the pages directory.
> Setting the option of every fetch() request in a layout or page to { cache: 'no-store', next: { revalidate: 0 } }.
> Setting the segment config to export const fetchCache = 'force-no-store'
> ```

**Comment by doiali** [comment]
> Revalidate work with fetch but not with ky

Same here.  
There is an issue with ky. it does not pass next options to the underlying fetch

**Comment by thexpand** [comment]
I can confirm this as well. While most of the time I need to disable the cache for the `fetch` function, I can do that by passing `'cache': `no-store'`, but once I need to set a custom `next.revalidate` option, then ky doesn't pass down the `next` key to the underlying `fetch`.

**Comment by Talent30** [comment]
close https://github.com/sindresorhus/ky/pull/536
