### ISSUE TITLE
[WEB-969] since 13.3.1-canary.13 routing error in NextResponse not existing

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#48542]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
no response
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Turbopack (--turbo)

### Link to the code that reproduces this issue

no response

### To Reproduce

no response

### Describe the Bug

when exporting like this export type { NextResponse } then in that file next response is not working, it was working before

error during Next.js routing for /

Caused by:
- ReferenceError: NextResponse is not defined

Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NextRouterContentSource::get failed
- error during Next.js routing for /
- ReferenceError: NextResponse is not defined
      [at Object.middleware [as handler] (file:///app/apps/web/.next/build/edge/chunks/[project]_packages_next-intl_src_server_index.tsx_ab3591._.js:84:13)]
      [at Object.adapter (file:///app/apps/web/.next/build/edge/chunks/08b5e_.pnpm_204d7e._.js:1664:33)]
      [at default (file:///app/apps/web/.next/build/edge/chunks/src_middleware.ts_next-edge-bootstrap.ts_bb7e12._.js:20:335)]
      [at file:///app/node_modules/.pnpm/next@13.3.1-canary.13_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0_sass@1.62.0/node_modules/next/dist/server/web/sandbox/sandbox.js:88:30]
      [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
      [at async TurbopackDevServerProxy.runMiddleware (file:///app/node_modules/.pnpm/next@13.3.1-canary.13_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0_sass@1.62.0/node_modules/next/dist/server/next-server.js:1494:24)]
      [at async TurbopackDevServerProxy.runMiddleware (file:///app/node_modules/.pnpm/next@13.3.1-canary.13_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0_sass@1.62.0/node_modules/next/dist/server/dev/next-dev-server.js:827:28)]
      [at async Object.fn (file:///app/node_modules/.pnpm/next@13.3.1-canary.13_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0_sass@1.62.0/node_modules/next/dist/server/next-server.js:1639:42)]
      [at async Router.execute (file:///app/node_modules/.pnpm/next@13.3.1-canary.13_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0_sass@1.62.0/node_modules/next/dist/server/router.js:311:32)]
      [at async resolveRoute (file:///app/node_modules/.pnpm/next@13.3.1-canary.13_@babel+core@7.21.3_react-dom@18.2.0_react@18.2.0_sass@1.62.0/node_modules/next/dist/server/lib/route-resolver.js:176:9)]

### Expected Behavior

it was working before

### Which browser are you using? (if relevant)

no response

### How are you deploying your application? (if relevant)

no response

<sub>[WEB-969](https://linear.app/vercel/issue/NEXT-1067/since-1331-canary13-routing-error-in-nextresponse-not-existing)</sub>

**Comment by ForsakenHarmony** [comment]
Going to close this as routing is now completely different
