### ISSUE TITLE
Turbopack build duplicate div constantly (webpack works perfectly)

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#48547]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
no response
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Turbopack (--turbo)

### Link to the code that reproduces this issue

no response

### To Reproduce

import ReactTextTransition, { presets } from 'react-text-transition';
import GetStartedButtons from './GetStartedButtons';

const texts: string[] = ['World', 'City', 'State'];

const TitleAnimated = React.memo(
  () => {
    const [textIndex, setTextIndex] = React.useState(0);
    const intl = useIntl();
    React.useEffect(() => {
      const interval = setInterval(() => {
        setTextIndex((prev) => prev + 1);
      }, 2000);
      return () => {
        clearInterval(interval);
      };
    }, []);

    const text = texts[textIndex % texts.length];

    return (
      <ReactTextTransition springConfig={presets.gentle} delay={300} inline>
        <GradientText>
          {text === 'World'
            && intl.formatMessage({
              id: 'world',
              defaultMessage: 'World',
            })}
          {text === 'City'
            && intl.formatMessage({
              id: 'city',
              defaultMessage: 'City',
            })}
          {text === 'State'
            && intl.formatMessage({
              id: 'state',
              defaultMessage: 'State',
            })}
        </GradientText>
      </ReactTextTransition>
    );
  },
  () => true,
);

TitleAnimated.displayName = 'TitleAnimated';

### Describe the Bug

div animated (@react-spring/web) gets duplicated always

### Expected Behavior

div should keep mounted and just updated the props

### Which browser are you using? (if relevant)

no response

### How are you deploying your application? (if relevant)

no response

**Comment by joacub** [comment]
seems like this is what cause the problem in turbo pack only:

```js
return react_1.default.createElement(
    web_1.animated.div,
    {
      className: 'text-transition '.concat(className),
      style: __assign(
        __assign(__assign({}, inline && !initialRun.current ? widthTransition : undefined), style),
        {
          whiteSpace: inline ? 'nowrap' : 'normal',
          display: inline ? 'inline-flex' : 'flex',
          height: heightRef.current,
        },
      ),
    },
    transitions(function (styles, item) {
      return react_1.default.createElement(web_1.animated.div, {
        style: __assign({}, styles),
        ref: item === children ? currentRef : undefined,
        children: item,
      });
    }),
  );
```

the function inside of transition is detected as a Component and it is not this also happened in other issue I've already posted:  https://github.com/vercel/next.js/issues/48542

**Comment by padmaia** [comment]
@joacub could you create repo with your minimal reproduction to help us look into this? 🙏

**Comment by joacub** [comment]
> @joacub could you create repo with your minimal reproduction to help us look into this? 🙏

hi @padmaia seems that this issue was fixed already in the latest canary versions, I forgot to close this.

thanks
