### ISSUE TITLE
`<Link prefetch={false}>` show the content of default.tsx file for the first navigation when using parallel route in a dynamic segment

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#48551]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Tue Apr 18 2023 19:07:28 GMT+0200 (heure d’été d’Europe centrale)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.3.1-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-4rcwhm?file=app%2F[dynamic]%2Fpage.tsx,app%2F[dynamic]%2F%40modal%2Fmodal%2F[path]%2Fpage.tsx,app%2F[dynamic]%2Fdefault.tsx

### To Reproduce

1. Open the project on stackblitz & start the project
2. Click on the link to `@modal`, you will see the content of default.tsx located in the same level as the `layout.tsx` that wraps the modal
3. click on go back
4. And click on the link to `@modal` again, now you will both the content of the page + the content of the parallel route

### Describe the Bug

When using a link with `prefetch={false}` that points to a parallel route when in a dynamic segment, the content of  the `default.tsx` located in the same level as the layout that wraps the parallel route will show on first navigation, on subsequent navigations both content will show normally.

This bug happens only if the layout is located in a dynamic segment (i.e `[dynamic]`), if you are not in a dynamic segment everything will works fine. 

### Expected Behavior

When using a link with `prefetch={false}` both the content of the page and the parallel route should be shown on the first navigation instead of the content of `default.tsx` file.

**Comment by samcx** [comment]
@Fredkiss3 Thank you for submitting an issue!

I was not able to replicate this issue with the latest canary—can you confirm that you are experiencing the same as well with the latest canary? We've been shipping a lot of Parallel Route fixes recently!

**Comment by Fredkiss3** [comment]
Yes, this is fixed, thanks.
