### ISSUE TITLE
`<Link prefetch={false}>` stops navigation when using it inside a parallel route

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#48550]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Tue Apr 18 2023 18:41:42 GMT+0200 (heure d’été d’Europe centrale)
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.3.1-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-9bhsuu?file=app%2Fpage.tsx,app%2Fother%2Fpage.tsx

### To Reproduce

1. Open the project on stackblitz & start the project
2. open the preview in a new tab (otherwise you won't see it)
3. From the home page click on one of the modals, you will be able to navigate without a problem
4. Now from the parallel route, click on the link to `/other`, nothing will happen, if you try clicking on any other link, nothing will happen

### Describe the Bug

When using a Link with `prefetch={false}`, in conjunction with a parallel route, if the link points to a path outside of the parallel route, when you go to the parallel route, and try to click on the link it will break navigation and no navigation will be possible. 

### Expected Behavior

link with prefetch should not stop navigation even when in a parallel route

**Comment by samcx** [comment]
@Fredkiss3 Thank you for submitting an issue!

I was able to replicate this issue on the latest canary—can you verify the same as well?

**Comment by Fredkiss3** [comment]
I can confirm this bug doesn't exist anymore, thank you 🙏🏾
