### ISSUE TITLE
images broken in alpine standalone

### ISSUE THREAD

**Issue by mlarcher** [vercel/next.js#48600]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
bash-5.1# npx --no-install next info
sh: next: not found

env is node:18.10.0-alpine3.15 docker image
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue

http://toomuch.com

### To Reproduce

build and deploy a nextjs app with Image component from 'next/image';

### Describe the Bug

Images appear as broken link

### Expected Behavior

images are displayed

### How are you deploying your application? (if relevant)

docker

**Comment by DuCanhGH** [comment]
Should be fixed in latest canary :)
