### ISSUE TITLE
UseParams Intercepting Routes not sending the current params

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#48613]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Last canary
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

No response 

### To Reproduce

Parallel interception route 

### Describe the Bug

Using interception routes does not send the current params . Is sending old page params 

### Expected Behavior

Get the params that the page is 

### Which browser are you using? (if relevant)

No response 

### How are you deploying your application? (if relevant)

No response

**Comment by feedthejim** [comment]
fixed in #49595
