### ISSUE TITLE
Docs: Need Help for Next.js 13 Cypress and Next-Auth Testing

### ISSUE THREAD

**Issue by ImBIOS** [vercel/next.js#48611]
### What is the improvement or update you wish to see?

I found frustrating to test next-auth using cypress in nextjs

### Is there any context that might help us understand?

Next-Auth, Cypress, Next.js 13

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/testing

**Comment by leerob** [comment]
https://nextjs.org/docs/app/building-your-application/testing/cypress
