### ISSUE TITLE
next-types-plugin does not work on Turborepo monorepos

### ISSUE THREAD

**Issue by t3dotgg** [vercel/next.js#48653]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information
I have also tested latest canary and worked with Anthony Shew to confirm the issue exists on all of Turbo's templates

```bash
 Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: 8.1.1
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue

npx create-turbo@latest

### To Reproduce

1. `npx create-turbo@latest`
2. Use `pnpm`
3. Try to use the workspace version of TS
4. Plugin doesn't work

### Describe the Bug

The plugin doesn't work

### Expected Behavior

The plugin works

**Comment by juliusmarminge** [comment]
Pretty sure this is cause next creates a vscode folder in the root app directory even if there is already one in the monorepo root.

Removing the inner vscode folder fixes the plugin until you restart the dev server and the folder is recreated

**Comment by JesseKoldewijn** [comment]
Noticed this as well but kept thinking I did something stupid since it didnt happen on every monorepo I have with a next.js app router project
