### ISSUE TITLE
loading.js not working in Safari (macOS and iOS)

### ISSUE THREAD

**Issue by jeremiasjutz** [vercel/next.js#48663]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.17
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/loving-hugle-qk4j4g

### To Reproduce

Open the csb [page](https://qk4j4g-3000.csb.app/) in a separate tab and see, that the browser waits, until all data is loaded instead of showing loading.js.

### Describe the Bug

Safari doesn't show the loading UI defined in loading.tsx

### Expected Behavior

It should show the loading.tsx UI as it does in Chrome and Firefox

### Which browser are you using? (if relevant)

Safari 16.3 on macOS and 16.4.1 on iOS

### How are you deploying your application? (if relevant)

next dev

**Comment by JesseKoldewijn** [comment]
Fix: Don't use safari...

Just kidding ;)

Aight so, from what I've experienced the loading.tsx component works kinda of iffy atm. Like the loading.tsx is (last time I checked) kind of borked on dynamic routes.

I would assume that everybody is working hard to make the whole app router experience even better and can't wait for what's to come. But as of now, good callout on this behavior. Noticed the weird loading.tsx behavior on our mac and my macOS vm.

**Comment by shuding** [comment]
I guess that this is because the minimal bytes for Safari to display any HTML content is slightly larger than this demo's loading.js, while it's still streaming the actual page content. Maybe you can try making that loading file a bit more complex with more content and see if it works.

**Comment by jeremiasjutz** [comment]
Thanks for all your answers! 
Added more content to my loading.tsx and now everything works as expected.
