### ISSUE TITLE
Metadata didn't show in head tag

### ISSUE THREAD

**Issue by MR-Addict** [vercel/next.js#48673]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 18.15.0
  pnpm: N/A
Relevant packages:
  next: 13.2.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/MR-Addict/github-users

### To Reproduce

I export metadata in root **layout.tsx** like below, and metadata didn't shw in **head** tag, instead it showed in **body** tag:

```tsx
import "./globals.css";

import { PopupContextProvider } from "@/contexts";
import { Footer, ScrollToTop } from "@/components";

export const metadata = {
  title: "Github Users",
  description: "Github Users",
  icons: { icon: "/favicon.ico" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <PopupContextProvider>
          {children}
          <ScrollToTop />
          <Footer />
        </PopupContextProvider>
      </body>
    </html>
  );
}
```

### Describe the Bug

Metadata didn't shw in **head** tag, instead showing in **body** tag.

![image](https://user-images.githubusercontent.com/75357598/233679116-40159889-4275-4a20-9c58-041d53f1fd55.png)

### Expected Behavior

Metadata show in head tag.

### Which browser are you using? (if relevant)

Chrom and Edge

### How are you deploying your application? (if relevant)

Vercel

**Comment by khuezy** [comment]
Try the latest version

**Comment by MR-Addict** [comment]
Yeadh, I think the problem has been solved in next.js 13.3.1
