### ISSUE TITLE
Parallel routes do not clear slot with [...catchAll]

### ISSUE THREAD

**Issue by Yukioru** [vercel/next.js#48719]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 19.7.0
  npm: 9.5.0
  Yarn: N/A
  pnpm: 8.8.0
Relevant Packages:
  next: 13.5.4-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/Yukioru/next-parallel-routes-bug
https://codesandbox.io/p/github/Yukioru/next-parallel-routes-bug/main
https://next-parallel-routes-bug.vercel.app

### To Reproduce

You have to use soft navigation

1. Click "To /overview" page
2. Slot displays correctly with contents of the "Overview Extension"
3. Click "To /demo" page
4. The slot has not cleared

![image](https://user-images.githubusercontent.com/8497115/233791410-cd5a10cd-e3f9-4f3d-b1ce-f8a48713574d.png)

### Describe the Bug

Once the slot is shown, it is not cleared if the URL does not match.
A similar bug has already been described in Issue: https://github.com/vercel/next.js/issues/48124, but the solution with `[...catchAll]` route did not help. The route is not called.

If you do a hard navigation, you will see that the `/demo` slot segment corresponds to the default.js route, but it does not show up.

### Expected Behavior

Using soft navigation (next/link) the slot should be cleared by the `[...catchAll]` route (or the `default.js` route if possible).

### Which browser are you using? (if relevant)

Chrome 112.0.5615.138

### How are you deploying your application? (if relevant)

Vercel, CodeSandbox

<sub>[NEXT-1394](https://linear.app/vercel/issue/NEXT-1394/parallel-routes-do-not-clear-slot-with-[catchall])</sub>

**Comment by y0zong** [comment]
like I mentioned here[#48090](https://github.com/vercel/next.js/issues/48090#issuecomment-1527394102), it seems dynamic route or catch-all route still not compatible with parallel route, I think it may have some work to do.

**Comment by Yukioru** [comment]
Did a little research on the code - the essence of the problem is that all `/[...catchAll]` match only with `[...catchAll]` pages. When the situation arises that `[...catchAll]` the route is only in the parallel segment, but not on the page - the router will wait for the transition to the `[...catchAll]` page (if in my Issue go to a non-existent page, the segment will be called).

It seems that appPaths should contain any of the `[...catchAll]` being in a segment (but not necessarily having a page) considering nesting.

https://github.com/vercel/next.js/blob/cad6d3aa2208e82c26eee7ff81a0a47aeec39968/packages/next/src/server/dev/next-dev-server.ts#L557-L581
Perhaps there is a similar code in other packages for generating pages (I could not find it correctly)..

**Comment by lmatteis** [comment]
I fixed this here. You need the right combination of right page.js inside the slot https://github.com/lmatteis/nextgram

**Comment by adidoes** [comment]
I just ran into this issue on `13.4.7`. Has anyone found a workaround?

**Comment by oswaldoacauan** [comment]
Any updates on this? Right now feels impossible to use Parallel routes with Dynamic routes.

**Comment by tangye1234** [comment]
Any progress?

**Comment by Yukioru** [comment]
Updated the issue to the latest canary version `13.5.4-canary.1`
🗿waiting..

**Comment by tangye1234** [comment]
> Updated the issue to the latest canary version `13.5.4-canary.1`
> 🗿waiting..

Could you see this issue? The whole app is unmounted in the case described there without any error.

**Comment by gragland** [comment]
Here's a workaround:

```
app
├─ @photoModal
│  ├─ (.)photo
│  │  └─ page.tsx <----- a modal with links to home, /profile, and /login
│  └─ [...catchAll]
│  │  └─ page.tsx <----- returning null here is supposed to cause modal to hide when
│  │  │                  navigating away, as this should match all other routes, doesn't work though.
│  │  │                  So we create dummy pages to match the specific routes below.
│  └─ profile             
│  │  └─ page.tsx <----- page that returns null, causing modal to hide when navigating to /profile
│  └─ login
│  │  └─ page.tsx <----- page that returns null, causing modal to hide when navigating to /login
|  └─ page.tsx <----- page that returns null, causing modal to hide when navigating to /
|  └─ default.tsx
├─ photo
|  └─ page.tsx 
├─ profile
│  └─ page.tsx
|  login
|  └─ page.tsx
└─ page.tsx
```

Dummy page looks like this:
```tsx
export default function Page() {
  return null
}
```

**Comment by stefanofa** [comment]
Since I ran into the same problem, I also created a simple [codesandbox](https://codesandbox.io/p/sandbox/interesting-glade-fykc54).

The desired result is that the subheader that is displayed following a soft navigation to `/c` is "I'm the catchall subheader!"

**Comment by stefanofa** [comment]
I have created a [draft PR with failed tests and further context](https://github.com/vercel/next.js/pull/58054), if anyone would like to add feedback please feel free to do so.

**Comment by feedthejim** [comment]
thanks @stefanofa for adding a repro. I was looking into this and you're right that it should work. I'll try to fix this in the next one-two weeks. It's not super straightforward to fix unfortunately.

**Comment by stefanofa** [comment]
Thanks @feedthejim for taking care of it. Since this is part of the topic, I have a question to ask, namely why do the [slots during soft navigation behave as described in the docs](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#navigation
)?

![image](https://github.com/vercel/next.js/assets/9802152/e7698b90-4c36-4de6-a1ea-b6feec399345)

Thinking about it I can't think of any concrete use cases, although I'm most likely missing something.
