### ISSUE TITLE
Docs: Potential security issue. Fallback 'blocking' or `true`

### ISSUE THREAD

**Issue by sumanchapai** [vercel/next.js#48718]
### What is the improvement or update you wish to see?

Ability to specify an optional secret when building a page that didn't previously exist.

### Is there any context that might help us understand?

1. Assume building a movie page `/movie/[slug]` makes call to the backend.
2. You set fallback to blocking or true because new movies might be added after build.
3. If someone visits `/movie/random1/` then it will trigger call to backend.
4. If someone visits (though browser or a script) `/movie/random2/` `/movie/random3` and so on and so forth, you backend will potentially get clogged.

**Comment by leerob** [comment]
We could try to make this more clear in the documentation, thanks. In the meantime, if you do see anything you'd classify as a security issue, you can email `security@vercel.com` with a reproduction. Thank you.
