### ISSUE TITLE
serverComponentsExternalPackages not working with monorepo packages

### ISSUE THREAD

**Issue by souporserious** [vercel/next.js#48739]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 17.4.0
      npm: 8.3.1
      Yarn: 1.22.17
      pnpm: 8.2.0
    Relevant packages:
      next: 13.3.1-canary.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/souporserious/server-components-external-packages-bug

### To Reproduce

- Install the packages
- Run the dev server
- You should see an error about needing an appropriate loader

### Describe the Bug

When a third-party library's dependency is marked in `serverComponentsExternalPackages` it is not respected. For example, the following error occurs when trying to load SWC in a Server Component located in a separate package even though `@swc/core` is added to the config:

```
../node_modules/.pnpm/@swc+core-darwin-arm64@1.3.52/node_modules/@swc/core-darwin-arm64/swc.darwin-arm64.node
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

I've verified that this works in the case of being local to the relevant Next.js project. However, when it is in a third-party like another package in a monorepo it does not seem to resolve correctly.

### Expected Behavior

The package resolves correctly and does not cause an error in Server Components.

**Comment by alvis** [comment]
I've the same issue and it seems to be linked to #43433

**Comment by raftario** [comment]
Yes, this is the same issue.

**Comment by souporserious** [comment]
Still getting this same error, but closing this issue since it's a duplicate of https://github.com/vercel/next.js/issues/43433.
