### ISSUE TITLE
next build produces incorrect JavaScript code

### ISSUE THREAD

**Issue by larsgw** [vercel/next.js#48731]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19)
    Binaries:
      Node: 16.19.0
      npm: 9.6.5
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.19
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.3.1-canary.19", newest: "13.3.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Script optimization (next/script)

### Link to the code that reproduces this issue

https://github.com/larsgw/next-js-compile-issue-mcve

### To Reproduce

  - Run `npm run build`
  - Run `npm run start`
  - Go to http://localhost:3000
  - Open the Developer Tools/JavaScript Console
  - Click the button labeled <kbd>Click to test</kbd>

### Describe the Bug

This will (currently) produce an error like this one:

```
framework-e2bd64861297ca18.js:9
Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at onClick (index-572eab17bd5f8a7d.js:1:349)
    at Object.eU (framework-e2bd64861297ca18.js:9:14912)
    at eH (framework-e2bd64861297ca18.js:9:15066)
    at framework-e2bd64861297ca18.js:9:33374
    at re (framework-e2bd64861297ca18.js:9:33473)
    at rn (framework-e2bd64861297ca18.js:9:33887)
    at framework-e2bd64861297ca18.js:9:39345
    at oP (framework-e2bd64861297ca18.js:9:96345)
    at eF (framework-e2bd64861297ca18.js:9:14046)
    at ro (framework-e2bd64861297ca18.js:9:35178)
```

That is because the code is transformed to the following:

```js
function(n, t, u) {
    "use strict";
    u.r(t),
    u.d(t, {
        default: function() {
            return e
        }
    });
    var c = u(5893);
    function e() {
        return (0,
        c.jsx)(c.Fragment, {
            children: (0,
            c.jsx)("button", {
                onClick: ()=>{
                    var n;
                    n = n.slice()
                }
                ,
                children: "Click to test"
            })
        })
    }
}
```

Note specifically how the function `foo` in the original code:

```js
function foo (arg) {
  var arg = arg.slice()
}
```

is incorrectly optimised:

```js
()=>{
  var n;
  n = n.slice()
}
```

### Expected Behavior

I would expect that `next build` does not introduce such errors in the code.

### Which browser are you using? (if relevant)

Google Chrome 111.0.5563.146 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

next start

**Comment by larsgw** [comment]
To be fair, I would not have guessed that the following function does "work", but it seems to.

```js
(n)=>{
  var n;
  n = n.slice()
}
```

**Comment by icyJoseph** [comment]
Most likely an SWC issue.

Check [this playground](https://play.swc.rs/?version=1.3.53&code=H4sIAAAAAAAAA0WMMQ7DIBAEe16xJW7iDwBNmvwhSkEcsKw4XIQPK5LF333YRZqVbm53wu9LmfEK0ZeZEUsaeKKEG32C7rAp%2FFkkgvZ5PDGw%2Bgw5YVtelnkaZCKfqiRy4JITjDuq5lmYRUHpKrW33cRtXTPq%2B6Or7qBgAoeFTX%2B229T0TtUdhcLyPaUAAAA%3D&config=H4sIAAAAAAAAA42VS47bMAyG93OKwOtZtIsCgx6gu55BUCzKUSqJhkhlEgxy99KKnUkntNFNEPPjw6R%2Byh8vu113pL77ufuQv%2FIw2kJQ7s9ioUtmexZLB32y1Jcwcve60CNNiEuFZrneQMe2DMAtiH7M3l1EJJi9Z1MKOfjLY7ke01iA6MEmVklXE2SezN5GgtdHVvCd%2Fsnb7HvECDZvEGPJhMwwQNES9xijHQnMyRYly%2FSmtgRCrcQEK4MzY8FR5dkFDpil5jN1YJ3p0YGCQoGewwm0MKklYZmkPaWfhh3s6zC0I%2F4SDScbq2WlJpzbkcjbKlkPGIiNr1kb4Q2uzOAG5%2BF%2BjQzeFOBa8nPcEUNeOZM%2FADKBaImyTaDlbR5e9LQW7TcjQ%2FYiWb4oXOStdZlhkKGaELwy2WkyUDhop1nA1R6myfba68x4ZXwUHBjwXrSipKb3wP1BK8qXEdArQM7Xek1VN2DuW7jCp4XYwL%2BkS9YFNnsky4d1Spe0x7hRIAEf0G04yFEwruMit8R5XOc1OxBpgFNdKjXwfAnIAjCa2O7KJ23IekhGM0Tcf14Ts8P1fgUnm4e27w%2F3JeMY4QRxTcb%2FsSKbVN7tNKl62eyn7YU3TZRWFi98%2F7agpZWX5bc11SV09aGhpsnpUyISSpiP1H16Lp%2BPe6Uu0O8lvE3r%2Bhc8%2FyKF5AYAAA%3D%3D), it works fine there, but if [we switch the target to ES2015, or later](https://play.swc.rs/?version=1.3.53&code=H4sIAAAAAAAAA0WMMQ7DIBAEe16xJW7iDwBNmvwhSkEcsKw4XIQPK5LF333YRZqVbm53wu9LmfEK0ZeZEUsaeKKEG32C7rAp%2FFkkgvZ5PDGw%2Bgw5YVtelnkaZCKfqiRy4JITjDuq5lmYRUHpKrW33cRtXTPq%2B6Or7qBgAoeFTX%2B229T0TtUdhcLyPaUAAAA%3D&config=H4sIAAAAAAAAA42VwW7bMAyG732Kwuce2gEDhj3AbnsGQbEoR5kkGiKVJijy7qMVO80a2tjFsPmJpEj9lD%2Benp%2B7A%2FXdz%2BcPeZWP0RaCcvsWC50z25NYOuiTpb6EkbuXhR5oQlwqNMvlCjq2ZQBuTvTt9e377NBFRILZYTalkIM%2F32fsMY0FiO5sYpWINUHmyextJHi5ZwXf6Z%2B4zb5DjGDzBjGWTMgMAxQtcI8x2pHAHG1Rokw7tSUQaikmWBmcGQuOKs8ucMAsOR%2BpA%2BtMjw4UFAr0HI6guUkuccsk5Sn1NOxgV4ehnfIXbzjaWC0rOeHUjkR2q0TdYyA2vmathVe40oMrnJv71TN4U4BryY9%2BBwx55Uz%2BAEgHoiXKNoEWt63woqc1b7%2FpGbIXyfJZ4SJvrcoMgzTVhOCVzk6dgcJBO80CrvYwdbbXtjPjlfZRcGDAe9GKEpreA%2Fd7LSmfR0CvADlf6zVVXYG5TeEKnwZiA%2F%2BSKlkX2LwiWd6vUzqnHcaNBAl4j25jgRwF4zouckucxnVeswORBjh1SaUGHi8BGQBGE9t1%2BaANGQ%2BJaIaIu89rYl5wud3Cyeahzfvdfck4RjhCXJPxf4zIJpW9HSdVL5P9ML3wQxOllcELb68LWkp5Wp6tqC6hq3cFNU1OfxORUMJ8oO5z5fL7uGXqAv1e3Fu3Ln8BijqMrecGAAA%3D), then it does it as you describe. We should take this issue to the SWC repository.

**Comment by larsgw** [comment]
Maybe related to https://github.com/swc-project/swc/issues/6419 then

**Comment by icyJoseph** [comment]
Nice! Hopefully this example can be fixed. Typically the SWC maintainer can do a lot more with such concise snippets, make a test and fix the compression. Let's be patient.

**Comment by larsgw** [comment]
It looks like a fix was released in SWC.
