### ISSUE TITLE
Docs: API OPTIONS 

### ISSUE THREAD

**Issue by miriyas** [vercel/next.js#48770]
### What is the improvement or update you wish to see?

In `app/api/route.ts`,

// If `OPTIONS` is not defined, Next.js will automatically implement `OPTIONS` and  set the appropriate Response `Allow` header depending on the other methods defined in the route handler.

=> depending on the other methods defined in the route handler.

This needs to be explained more.

### Is there any context that might help us understand?

When I have an api route with POST only,

OPTIONS are not implemented automatically.

So I should define OPTIONS manually

```
export const OPTIONS = async (request: NextRequest) => {
  return new Response();
};
``` 

or add meaningless GET. (Then OPTIONS are implemented automatically)

```
export const GET = async (request: NextRequest) => {
  return new Response();
};
```

I found this with struggling 2 hours for implementing session cookie.

Everytime I POST with idToken, it shows CORS error.

Other APIs with POST are fine. (They had GET, PATCH, DELETE)

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/file-conventions/route#http-methods

**Comment by BrandonNoad** [comment]
I'm running into this as well when my route.ts only has `export async function POST(request: Request) { ... }`.

Receiving a `405 Method Not Allowed` as the response to the OPTIONS request.

**Comment by snowthen-o7** [comment]
Also ran into the same problem, but thankfully found this issue. I don't like the idea of having to leave in a "load-bearing" GET/OPTIONS handler, but I can confirm that @miriyas's suggestion of defining OPTIONS manually works well as a workaround.

**Comment by miriyas** [comment]
Guys, this one looks similar.

https://github.com/vercel/next.js/issues/48798

**Comment by aacoimbra** [comment]
"I'm experiencing the same issue. The OPTIONS method isn't automatically handled for POST requests.

**Comment by aacoimbra** [comment]
I'm experiencing the same issue. The OPTIONS method isn't automatically handled for POST requests.

**Comment by leerob** [comment]
OPTIONS is now documented 🙏 

https://nextjs.org/docs/app/api-reference/file-conventions/route#http-methods

**Comment by BrandonNoad** [comment]
@leerob Did the docs even change? It seems like the issue raised by the OP still hasn't been addressed.
