### ISSUE TITLE
Revalidating cached server side rendered pages not working

### ISSUE THREAD

**Issue by mrhiccup** [vercel/next.js#48771]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1-canary.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/mrhiccup/revalidation_get_server_side_props

### To Reproduce

Run the provided example with 
``` npm run build && npm run start```
and then call the api:
```curl  http://localhost:3000/api/revalidate-server-page-normal-rendering```
or
```curl  http://localhost:3000/api/revalidate-server-page-get-server-side-props-rendering```

### Describe the Bug

Error thrown by `res.revalidate`

```text
Error revalidating: Error: Failed to revalidate /server-page-normal-rendering: Invalid response 200
```
or 
```text
Error revalidating: Error: Failed to revalidate /server-page-get-server-side-props-rendering: Invalid response 200
```

### Expected Behavior

The revalidation should be successful.

### How are you deploying your application? (if relevant)

Vercel

**Comment by itzfeltrin** [comment]
Facing the same issue

**Comment by daszkowski** [comment]
@mrhiccup  Have sam problem "Invalid response 200" (next.js version 13.3.1) - interestingly enough the revalidation is actually performed (i.e. the data is updated) while an error is returned from the API - does anyone have any information if this is a problem with the current version and if it will be patched in the future? 🤔

**Comment by irfancoder** [comment]
Encountered this error once, but realised it was my own dumb mistake. The page I tried to revalidate is a `getServerSideProps` page :laughing:

**Comment by ijjk** [comment]
Hi, `res.revalidate` is only compatible with On-Demand ISR which requires `getStaticProps`. If you are looking for more granular control over your caching you can look at trying `app` which allows revalidating tags/paths without page level ISR.
