### ISSUE TITLE
[NEXT-1197] (AppDir) `<input type="radio" defaultChecked />` is unchecked immediately.

### ISSUE THREAD

**Issue by wonu** [vercel/next.js#48778]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Mon Apr 24 2023 23:03:08 GMT+0900
    Binaries:
      Node: 16.14.2
      npm: 7.17.0
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.3.2-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://stackblitz.com/edit/vercel-next-js-cnys4q (app directory, the issue happens)

https://stackblitz.com/edit/vercel-next-js-m8f8gg (pages directory, the issue doesn't happen)

### To Reproduce

https://user-images.githubusercontent.com/9602236/234021910-e09a6102-18a3-40d0-91c8-6dc28ec85b05.mp4

### Describe the Bug

There are 4 `<input type="radio">`s
- `<input type="radio" name="a" defaultChecked={true} />`
- `<input type="radio" name="a" defaultChecked={false} />`
- `<input type="radio" name="b" defaultChecked={true} />`
- `<input type="radio" defaultChecked={true} />`

On page refresh, the first, third and fourth one have been checked initially, but the first one is unchecked right after.
This issue seems that was introduced since `next@13.3.1-canary.17`.

### Expected Behavior

Default checked radio input that has same name should remains checked.

<sub>[NEXT-1197](https://linear.app/vercel/issue/NEXT-1197/appdir-input-type=radio-defaultchecked-is-unchecked-immediately)</sub>

**Comment by anmoti** [comment]
I request a fix as it is still happening today.

**Comment by sophiebits** [comment]
Should be fixed in [v13.5.6-canary.1](https://github.com/vercel/next.js/commit/24a146680f6e4cb53737ddee170958b700977ee0) via 0a80017d038e7de7ac16894d4ebc8d64cf7988eb

**Comment by cphoover** [comment]
Why do I always run into the weirdest bugs

**Comment by tialki** [comment]
Still exists in version 13.5.6 under dev mode.

**Comment by timneutkens** [comment]
Going to close this as no new reproduction was provided. If you're running into something like this please open a new issue with a reproduction. Thanks!
