### ISSUE TITLE
bug report reproductions projects don't work - Stackblitz, CodeSandbox

### ISSUE THREAD

**Issue by studentIvan** [vercel/next.js#48788]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

Stackblitz reproduction-template
https://stackblitz.com/fork/github/vercel/next.js/tree/canary/examples/reproduction-template

CodeSandbox reproduction-template
https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template

### Which example does this report relate to?

reproduction-template

### Describe the Bug

Stackblitz

shows:

```
error - Failed to patch lockfile, please try uninstalling and reinstalling next in this workspace
TypeError: Cannot read properties of undefined (reading 'os')
    at fetchPkgInfo (file:///home/projects/vercel-next-js-rm3xmn/node_modules/next/dist/lib/patch-incorrect-lockfile.js:72:25)
    at async Promise.all (index 2)
    at async patchIncorrectLockfile (file:///home/projects/vercel-next-js-rm3xmn/node_modules/next/dist/lib/patch-incorrect-lockfile.js:161:26)
error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```

CodeSandbox simple falls when you trying to edit something.

If I do something wrong - maybe better to add it to the bug report markdown, to make it clear.

### Expected Behavior

Expected working out of the box

### To Reproduce

Just go to the reproduction link and see how it builds

**Comment by styfle** [comment]
This "Failed to load SWC binary" should be fixed by https://github.com/vercel/next.js/pull/48803

Its currently publishing and should be done once this job completes: https://github.com/vercel/next.js/actions/runs/4791615248

**Comment by styfle** [comment]
@studentIvan Can you confirm its working now?

**Comment by studentIvan** [comment]
@styfle yep, it's working now. Though, it had some weird logs in the start:

```
success Install finished in 12.164s
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Downloading WASM swc package...
ERR!: Unknown command `config`
```

but the project is working and I can make the bugs to reproduce, thanks!

**Comment by studentIvan** [comment]
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/1205208/234172959-ba2e5c21-d3e5-4b1b-af79-11c8226e2fe1.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1205208/234172990-a297ec4c-06e1-4d93-ba0b-34b65a3a8cbd.png">

**Comment by balazsorban44** [comment]
Hi, we dropped StackBlitz from the bug report templates for now, so closing this. If codesanbox fails again, feel free to report in a new issue.
