### ISSUE TITLE
Recently fixed CSS ordering issue is re-corrupted on hot reload

### ISSUE THREAD

**Issue by meebix** [vercel/next.js#48807]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
    Platform: darwin
    Arch: x64
    Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
Binaries:
    Node: 18.12.1
    npm: 8.19.2
    Yarn: 3.5.0
    pnpm: 8.1.1
Relevant packages:
    next: 13.3.2-canary.5
    eslint-config-next: 13.3.0
    react: 18.2.0
    react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/meebix/repro-nextjs-css-order

### To Reproduce

1. Load the app at http://localhost:3000
2. Notice the styled button when the page loads
3. Using your editor (VSCode), save the `page.tsx` file which will trigger a hot-reload of the dev server
4. Notice the button has disappeared

### Describe the Bug

When the Next dev server performs a hot reload, the CSS ordering is corrupted. The original CSS ordering issue in Next.js was recently fixed via [this PR](https://github.com/vercel/next.js/pull/48244). However, it appears there is more to the issue, which I am raising. (CC @shuding who fixed the original issue 🙏🏻 )

You can see from my screenshots that on initial load of the page, the CSS ordering is correct:
<img width="666" alt="correct-css-order" src="https://user-images.githubusercontent.com/8016033/234162387-6d36ae48-5280-4c64-997e-e5624dd23f9c.png">

However, after a hot-reload, the ordering is corrupted:
<img width="676" alt="hot-reload-corrupt-css-order" src="https://user-images.githubusercontent.com/8016033/234162426-8914a756-f6f1-45eb-aa4b-647c8b8516b1.png">

In my repro, the Button disappears because in the `layout` CSS there is button reset CSS and thus it must come first before any `page` CSS.

### Expected Behavior

When the Next dev server performs a hot-reload, the CSS order should be maintained and thus not corrupted.

### Which browser are you using? (if relevant)

Chrome

**Comment by philwolstenholme** [comment]
#47585 was the original ticket
