### ISSUE TITLE
Massive Hydration errors on fast click

### ISSUE THREAD

**Issue by milanbgd011** [vercel/next.js#48817]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

I switched to NextJS in january 100%, version 13.0, 13.1, 13.2... All seems to be working ok.

Except I am getting a lot of hydration errors which I first did not where they come from:
<img width="1405" alt="sentry" src="https://user-images.githubusercontent.com/20988958/234244537-f255c129-783e-43c9-95ab-bce6c1d0d628.png">

So I tried one thing, to refresh page and then click on NON-CLICKABLE element by force multiple times and then I got the Hydration error.

It creates the same error in /app and in /pages defined web pages.

I am using non-clickable text to demonstrate, it creates the same error on clickable too.

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### To Reproduce

1. goto https://vercel.com/docs
2. open the console of the browser
3. position cursor above the non clickable text (it is in purple in the screenshot above)
4. hit CMD+R on keyboard while non-stop fast clicking the non clickable text while it loads
5. observe minified error that points to hydration error link

### Describe the Bug

Simple hydration errors when clicking on clickable or non-clickable elements before hydration finishes.

Since this is unhandled error, it breaks entire page 100%. 😞

It appears that users on mobile phones with slower bandwidth and/or cpu suffer a lot of these errors.

### Expected Behavior

Do not throw hydration errors.
Do not break entire app because of the hydration errors.

### Which browser are you using? (if relevant)

chrome,edge any version

**Comment by milanbgd011** [comment]
Safari too, all browsers no exception:

![Screenshot 2023-04-25 at 12 26 01](https://user-images.githubusercontent.com/20988958/234249591-92b11f93-4ddd-4dc1-8af3-17b6dd5354dd.png)

**Comment by JesseKoldewijn** [comment]
It doesn't seem related to the cursor position relative to any form of text. I get these minified errors just on pageload without my cursor being even in the window.

**Comment by milanbgd011** [comment]
Seems like this is false, closing. When I get proper reproduction scenario I will report again.
