### ISSUE TITLE
useState Render Infinite Loop

### ISSUE THREAD

**Issue by SamKomesarook** [vercel/next.js#48822]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.1.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.6
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Kiwi-Biosciences/render-test

### To Reproduce

1. Clone the repo, build, and start the server.
2. Navigate to the homepage and open the debug tools console.
3. Click the image in the centre of the screen to trigger the update.
4. View how the component is re-rendered in an infinite loop.

### Describe the Bug

The useState hook update causes an infinite loop of refreshes when used in async client components.

### Expected Behavior

The useState hook update should cause a single re-render.

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

AWS Amplify

**Comment by satyavamsi** [comment]
Having a similar issue

**Comment by icyJoseph** [comment]
Components labeled as 'use client'; cannot be `async`, only Server Components can be async: 

https://github.com/Kiwi-Biosciences/render-test/blob/main/src/app/page.tsx#L1-L6


```jsx
"use client";
import Image from "next/image";
import styles from "./page.module.css";
import { useState } from "react";
//                         v this is not possible within use client
export default async function Home() {
```

So you are creating an incompatible situation.

**Comment by SamKomesarook** [comment]
@icyJoseph Ah I see, thanks for that! And noting for future reference to use [the use hook](https://beta.nextjs.org/docs/data-fetching/fetching#use-in-client-components).
