### ISSUE TITLE
Response is not cached between `generateMetadata()` and `Page()`

### ISSUE THREAD

**Issue by Expensiveee** [vercel/next.js#48833]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Debian 5.10.162-1 (2023-01-21)
    Binaries:
      Node: 18.16.0
      npm: 9.6.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/Expensiveee/no-cache

### To Reproduce

Have a function that fetches data from any api, call it in `generateMetadata()` and in `Page()`.

### Describe the Bug

2 api calls are made. This is not optimal if you need data for the `Page()` and `generateMetadata()`.

### Expected Behavior

It should only make 1 API call since it's supposed to cache the data on the first api call.

**Comment by onurcagan** [comment]
This is an issue we're facing as well. And nothing we tried (revalidate, no-cache, no-store so on with fetch) seems to help.

Another interesting thing that may require its own issue is that those 2 API calls are being made from 2 different IP addresses although even on local build the fetch is duplicated so it may be irrelevant.

![image](https://user-images.githubusercontent.com/55636840/234713235-60bf5a25-e3cf-491f-8680-c46eec9d8bcc.png)
![image](https://user-images.githubusercontent.com/55636840/234713246-8cb07954-cbf8-4c2f-8075-869833d33d1c.png)

**Comment by huozhi** [comment]
Can you try the latest version 13.4.1 of next.js? Seems the 2nd fetch is cached now

I'm testing with 13.4.1-canary.2
<img width="520" alt="image" src="https://user-images.githubusercontent.com/4800338/236587494-99a8c169-4b23-4d93-a117-bcdf7b77896a.png">

Will mark this as close
