### ISSUE TITLE
Navigation with `next/link` on global `not-found` page does not work in App Router

### ISSUE THREAD

**Issue by octet-stream** [vercel/next.js#48836]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.9.0
      npm: 9.6.3
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.3.2-canary.6
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/nostalgic-brook-0pfp6s

### To Reproduce

To see the navigation issues:
1. Click on the `Navigate to not-found page` link;
2. Nothing should happen: The page's pathname is changed `/404`, but you'll still see the home page;
3. Then you can refresh page and see 404 page. You will also notice that page have no `title`, even thought `src/app/not-found.tsx` module has `export const metadata = {title: "..."}`;
4. On the 404 page, click `Navigate to home page`, and again you'll see that nothing is changed again, aside from the page's `pathname` in browser;
5. Refresh page again to see Home page;
6. Click on the `About page` link - navigation works as expected for this page, but not for 404.

### Describe the Bug

Navigation for global `not-found` page in App Router does not seem to work: When navigating to such page, or from it using `next/link`, the address is changed in browser, but browser keeps showing the same page. Tested with Chrome and Safari, on both latest stable Next.js version and latest canary (`13.3.2-canary.6` at that moment).

### Expected Behavior

Navigation with `next/link` works the same as with the other pages in App Router.

### Which browser are you using? (if relevant)

Safari (Version 16.4 (18615.1.26.11.23)) and Chrome (Version 112.0.5615.137)

**Comment by timneutkens** [comment]
Duplicate of #47862
