### ISSUE TITLE
Docs: Suspense External Link Error

### ISSUE THREAD

**Issue by yasincandev** [vercel/next.js#48856]
### What is the improvement or update you wish to see?

In [this](https://beta.nextjs.org/docs/data-fetching/streaming-and-suspense#example-using-suspense-boundaries) section of the docs, the link given in the

> For more Suspense examples and use cases, please see the [React Documentation](https://react.dev/apis/react/Suspense)

section leads to React's new documentation but the link gives an error. 

### Is there any context that might help us understand?

Those who want to learn more about `Suspense` should go to this [link](https://react.dev/reference/react/Suspense).

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/data-fetching/streaming-and-suspense#example-using-suspense-boundaries

**Comment by TinaSay** [comment]
Pls assign me

**Comment by yasincandev** [comment]
This issue solved in last 13.4 release.
