### ISSUE TITLE
[NEXT-1053] Scrolling doesn't work in production build with `app`

### ISSUE THREAD

**Issue by goenning** [vercel/next.js#48852]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 9.4.1
      Yarn: 1.22.19
      pnpm: 7.6.0
    Relevant packages:
      next: 13.3.2-canary.6
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/aptabase/buildwith.app

### To Reproduce

Clone https://github.com/aptabase/buildwith.app and run locally. It'll scroll to top on every page navigation because scrollRestoration is false.

Visit https://buildwith.app/ (hosted on Vercel). Navigation between pages does not scroll to top

### Describe the Bug

Navigation between pages does not scroll to top when scrollRestoration is false and hosted on Vercel.

### Expected Behavior

Navigation between pages should scroll to top when scrollRestoration is false and hosted on Vercel.

### Which browser are you using? (if relevant)

Brave 112.0.5615.138 and Safari 16.4

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1053](https://linear.app/vercel/issue/NEXT-1053/scrollrestoration-doesnt-work-when-deployed-to-vercel)</sub>

**Comment by timneutkens** [comment]
The `experimental.scrollRestoration` has no effect on `app` which you're using.

What I've found is that it only happens on production builds, it's unrelated to if that's on Vercel or not.
Here's two sandboxes, it happens only on the production sandbox.
- [Development](https://codesandbox.io/p/github/aptabase/buildwith.app/main?file=%2Fnext.config.js)
- [Production](https://codesandbox.io/p/github/aptabase/buildwith.app/csb-h7nec2/draft/admiring-lovelace?file=%2Fnext.config.js&selection=%5B%7B%22endColumn%22%3A30%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A30%2C%22startLineNumber%22%3A4%7D%5D)

Will investigate further why that is the case.
