### ISSUE TITLE
useRouter's replace is not working as expected in version 13.3.1

### ISSUE THREAD

**Issue by VugarAhmadov** [vercel/next.js#48860]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/great-solomon-f815px?file=%2Fapp%2Fpage.tsx

### To Reproduce

1. use this codesandbox link. 
2. write a letter to the input
3. you will see a refresh and the query string will be removed

### Describe the Bug

useRouter's replace method  is not working as expected. in Nextjs 13.2.4 it was working correctly. when you type something in the search it starts the transition using useTransition hook. and replaces the url with the provided search value. but in Nextjs version 13.3.1 it is not working. it is also not working in latest canary relase ([13.3.2-canary.7](https://github.com/vercel/next.js/releases/tag/v13.3.2-canary.7))

### Expected Behavior

Not remove the search params and replace the url.

### Which browser are you using? (if relevant)

Google Chrome Version 112.0.5615.137 (Official Build) (x86_64)

**Comment by barbarah** [comment]
I'm also experiencing this error. After updating search params with `router.replace()`, all client state is lost. I made a code sandbox with both a `useState` and `useRef`. In the 13.2.4 version, the state remains after the ` router.replace`. In the 13.3.1 version, the state is reset, AND I lose focus in the input field.

Working version with 13.2.4: https://codesandbox.io/p/sandbox/bug-next-13-2-4-z9qu9g?file=%2Fapp%2Fpage.tsx

Not working version with 13.3.1: https://codesandbox.io/p/sandbox/bug-next-13-3-1-txdmph?file=%2Fapp%2Fpage.tsx

**Comment by benjaminwaterlot** [comment]
Same here ; updating any "search param" with `router.replace` will trigger **unmounting and remounting of every client components**, even if their props don't change.

**Comment by tienpd** [comment]
Still not working on 13.3.2 version.

**Comment by VugarAhmadov** [comment]
in version 13.4.0 the issue is fixed. thanks

**Comment by VugarAhmadov** [comment]
in version 13.4.0 the issue is fixed. thanks
