### ISSUE TITLE
TypeError: req.on is not a function

### ISSUE THREAD

**Issue by sunaryohadi** [vercel/next.js#48875]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.7
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

none

### To Reproduce

        export const api = { bodyParser: false }
        
        export async function POST(req) {
          const token = await getToken({ req })
        
          if (token) {
            const data = await new Promise((resolve, reject) => {
              const form = new IncomingForm({ multiples: true })
              form.parse(req, (err, fields, files) => {
                if (err) return reject(err)
                resolve({ fields, files })
              })
            })
        
            const { fields } = data
        
            console.log(fields)
        
            if (fields.approved_flag === 'true') {
              NextResponse.json({ message: 'Ok' })
            } else {
              NextResponse.json({ message: 'You have to confirm first' }, { status: 400 })
            }
          } else {
            return NextResponse.json({ message: 'Token not valid or expired' }, { status: 400 })
          }
        }

### Describe the Bug

    error - TypeError: req.on is not a function
        at IncomingForm.parse (webpack-internal:///(sc_server)/./node_modules/formidable/src/Formidable.js:182:13)
        at POST.data (webpack-internal:///(sc_server)/./app/api/shipping/update/route.js:28:18)
        at new Promise (<anonymous>)
        at POST (webpack-internal:///(sc_server)/./app/api/shipping/update/route.js:24:28)
        at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:233:33)

Working fine with /pages, but not /app

### Expected Behavior

I think the request missing function

**Comment by kanejoe** [comment]
same for me.  Also 

`import formidable from 'formidable'

const form = formidable()
new Promise((resolve, reject) => {
    form.parse(request, (err, fields, files) => {
      if (err) reject(err)
      resolve({ fields, files })
    })
  })
`
formidable@v.2.5

**Comment by balazsorban44** [comment]
[Route Handler](https://beta.nextjs.org/docs/routing/route-handlers) gives you a [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request) instance, not a Node.js-like `NextApiRequest` which is based on [`IncomingMessage`](https://nodejs.org/api/http.html#class-httpincomingmessage), what Formidable seem to expect, so this is not a Next.js bug.

**Comment by leesontungggg** [comment]
I'm having the same issue. Is there any way to get req as NextApiRequest in Next 13?

**Comment by yzubkov** [comment]
Would be good to know the official recommendation for how to listen to various events that are typically available on the NodeJS instance of the "req" instance.

One use-case is to listen to closed connection when a streaming socket is closed. Funny enough, documentation does provide an example of [streaming data from a Route](https://nextjs.org/docs/app/building-your-application/routing/router-handlers#streaming), however fails to address a situation if a stream is interrupted, or if you are streaming to multiple users, and one of the users disconnects.

**Comment by rabitarochan** [comment]
I also encountered the same event.

This is not a good solution, but it seems to be handled by API Route by creating a file in `/pages/api/*` even for App Router enabled applications.

I have confirmed this workaround with Next 13.4.2 .

```
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.2
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

**Comment by Advaita1** [comment]
same issue here, using next: 13.4.2, and formidable

**Comment by locnguyen** [comment]
I have the same problem but my handler interacts with http-proxy. I'm currently using the workaround with putting it in the `pages/api` directory.

**Comment by Yanger-Rai** [comment]
Tested in next 13.4.4, the pages/api/* do not work
Any work around this?

**Comment by sdb1228** [comment]
So after spending some time on this it seems like Nextjs 13 API handlers handle form data for you.  I found [this example ](https://github.com/directus/directus/discussions/18018) using [directus](https://github.com/directus/directus).  I know this isn't a direct answer to using formidable but maybe it helps someone in the future?

The tl;dr is that you can now access formdata through the request.formdata 


```
export async function POST(request: Request) {
  const formData = await request.formData();
  const file = formData.get('file');
  console.log("form data", formData, file);
}
```

Hope this helps someone

**Comment by ReactjsGod** [comment]
Hey guys I've been stuck on the error now for almost a day now Do we have a solution to the error "-error TypeError: req.on is not a function"

export const POST = async (req:NextRequest, res:NextRequest) => {
    await mongooseConnect();
    const form = new multiparty.Form();
  const {fields,files} = await new Promise((resolve,reject) => {
    form.parse(req, (err, fields, files) => {
      if (err) reject(err);
      resolve({fields,files});
    });
  });
  console.log('length:', files?.file?.length);
  console.log('THIS IS THE REQUEST FOR', form);
}

**Comment by entest-hai** [comment]
me too, I am experiencing the same issue

**Comment by Faizan-26** [comment]
I am experiencing the same issue, is there any way to solve this?

**Comment by gmotzespina** [comment]
Same issue here.

**Comment by Abdullah-SoftDev** [comment]
Guys i am also getting same issue here. 

const buffer = (req: NextApiRequest) => {
    return new Promise<Buffer>((resolve, reject) => {
        const chunks: Buffer[] = [];

        req.on('data', (chunk: Buffer) => {
            chunks.push(chunk);
        });

        req.on('end', () => {
            resolve(Buffer.concat(chunks));
        });

        req.on('error', reject);
    });
}; 

❌ Error message: req.on is not a function

**Comment by vela91** [comment]
me too, :face_exhaling:

**Comment by altaf53** [comment]
> So after spending some time on this it seems like Nextjs 13 API handlers handle form data for you. I found [this example ](https://github.com/directus/directus/discussions/18018) using [directus](https://github.com/directus/directus). I know this isn't a direct answer to using formidable but maybe it helps someone in the future?
> 
> The tl;dr is that you can now access formdata through the request.formdata
> 
> ```
> export async function POST(request: Request) {
>   const formData = await request.formData();
>   const file = formData.get('file');
>   console.log("form data", formData, file);
> }
> ```
> 
> Hope this helps someone

This solved my issue. It seems we don't require formidable now as nextjs is handling it out of box. Thanks mate..!!

**Comment by EvansRobbie** [comment]
> So after spending some time on this it seems like Nextjs 13 API handlers handle form data for you. I found [this example ](https://github.com/directus/directus/discussions/18018) using [directus](https://github.com/directus/directus). I know this isn't a direct answer to using formidable but maybe it helps someone in the future?
> 
> The tl;dr is that you can now access formdata through the request.formdata
> 
> ```
> export async function POST(request: Request) {
>   const formData = await request.formData();
>   const file = formData.get('file');
>   console.log("form data", formData, file);
> }
> ```
> 
> Hope this helps someone
This solved my issue too. You're a lifesaver bro.

**Comment by rharkor** [comment]
any up ?

**Comment by maslennikov** [comment]
I am also stuck with this. This prevents me from implementing a proper SSE api handler with next because I can't handle client 'close' event properly

**Comment by maslennikov** [comment]
I was looking a way to replace a `request.on('close', ...)` functionality with Next.js 13 route handler request and stumbled upon this thread. What worked for me is using the [`Request.signal` method](https://developer.mozilla.org/en-US/docs/Web/API/Request/signal):
```js
export async function GET(req: NextRequest) {
  req.signal.addEventListener('abort', function () {
    console.log('ABORT')
  })
  // rest of the code
}
```
