### ISSUE TITLE
TypeError in 13.3.2-canary.7: Cannot read properties of undefined (reading 'current') error. 

### ISSUE THREAD

**Issue by dincerpece** [vercel/next.js#48872]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.2-canary.7
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

sorry i can't upload because my project contains localhost database connections

### To Reproduce

While there is no problem in the pages that do not contain a subpage such as contact-us in the src/app directory, I get the error "error - TypeError: Cannot read properties of undefined (reading 'current')" in the pages under the news-media/[slug] folder. This error also happens on my page in news-media/[slug]. When I do next build and then next start, I don't get such errors in localhost:3000, but I get these errors in my own configuration "next build && node server/server.js production".

My server.js file looks like this: "const { createServer } = require('https')
const { parse } = require('url')
const next = require('next')
const fs = require('fs')
const dev = process.argv[2] !== 'production'
const serverProduct = process.argv[3] === 'server' || undefined

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0'
const hostname = 'localhost'
const port = 443
// when using middleware hostname and port must be provided below
const app = next({ dev, hostname, port })
const handle = app.getRequestHandler()
const httpsOptions = {
key: fs.readFileSync(./server/certificates/${serverProduct ? 'cloudflare.key' : 'server.key'}),
cert: fs.readFileSync(./server/certificates/${serverProduct ? 'cloudflare.pem' : 'server.crt'}),
}
app.prepare().then(() => {
createServer(httpsOptions, async (req, res) => {
try {
const parsedUrl = parse(req.url, true)
await handle(req, res, parsedUrl).then(null)
} catch (err) {
console.error('Error occurred handling', req.url, err)
res.statusCode = 500
res.end('internal server error')
}
})
.once('error', (err) => {
console.error(err)
process.exit(1)
})
.listen(port, () => {
console.log(> Ready on https://${hostname})
})
})

### Describe the Bug

What is missing in my server.js file or what do I need to do last 13.3.2-canary.7 I got this error. Normally, the pages under news-media/[slug] open, but when I refresh the page, I get the error "TypeError: Cannot read properties of undefined (reading 'current') 500 Internal Server Error.
"
![Screenshot_17](https://user-images.githubusercontent.com/57527680/234593239-755ea990-0abe-4112-a6d6-d180cdcd63be.png)

### Expected Behavior

What is missing in my server.js file or what do I need to do last 13.3.2-canary.7 I got this error. Normally, the pages under news-media/[slug] open, but when I refresh the page, I get the error "TypeError: Cannot read properties of undefined (reading 'current') 500 Internal Server Error.
"

### Which browser are you using? (if relevant)

Chrome 112.0.5615.138

### How are you deploying your application? (if relevant)

on my localhost with the command "next build && node server/server.js production".

**Comment by dincerpece** [comment]
Here is the screenshot of  my server.js file: 
![Screenshot_20](https://user-images.githubusercontent.com/57527680/234595521-42981391-bc09-401b-bc2e-3e6e2f96d897.png)

**Comment by dincerpece** [comment]
My problem persists in version 13.3.2-canary.8!

**Comment by dincerpece** [comment]
The error persists on the homepage and all other pages in version 13.3.2-canary.9
![Screenshot_21](https://user-images.githubusercontent.com/57527680/234823374-1864c8d7-3b4b-46ad-b272-0da2f8ca7378.png)

**Comment by barbarah** [comment]
I'm also experiencing this error. Only in the Vercel builds and not locally. After a downgrade of Next, the error still remained. 

I got rid of the error after a redeploy in Vercel. I believe this empties the cache: https://github.com/orgs/vercel/discussions/457#discussioncomment-19810
