### ISSUE TITLE
[NEXT-1064] Unable to select regions for edge using App Router

### ISSUE THREAD

**Issue by t3dotgg** [vercel/next.js#48905]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### To Reproduce

1. Start app router repo
2. `export const runtime = "edge";` ✅
3. `export const preferredRegion = "sfo1";` ❌

@leerob thinks this is unintended behavior

### Describe the Bug

Unable to deploy regional edge functions in app router

### Expected Behavior

Able to deploy regional edge functions in app router

<sub>[NEXT-1064](https://linear.app/vercel/issue/NEXT-1064/unable-to-select-regions-for-edge-using-app-router)</sub>

**Comment by t3dotgg** [comment]
Confirmation of deployment failing on Vercel

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/6751787/234759036-7370d418-a576-4f25-99a5-d50bc37a36e5.png">

**Comment by t3dotgg** [comment]
When I ignore the ts errors it still deploys globally 😅

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/6751787/234759367-8f4cf23f-b383-4965-b7a9-681a6e2d4067.png">

**Comment by kasperaamodt** [comment]
I was just about to open the same issue. I'm trying to deploy a regional edge function, and can't get it to work in the app dir.

I tried with `export const regions = ['fra1'];` as well, does not work either.

**Comment by timneutkens** [comment]
Just to clarify as there was some miscommunication. `preferredRegion` is not implemented yet. We're working on it soon, stay tuned!
