### ISSUE TITLE
Next.js crashes with exit 137 (Out of memory?)

### ISSUE THREAD

**Issue by OZZlE** [vercel/next.js#48961]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

asdf

### To Reproduce

next.config.js

	const { i18n } = require('./next-i18next.config')

	/** @type {import('next').NextConfig} */
	const nextConfig = {
	  output: 'standalone', // https://developers.redhat.com/articles/2022/11/23/how-deploy-nextjs-applications-red-hat-openshift#building_a_container_to_run_your_next_js_application
	  reactStrictMode: true,
	  productionBrowserSourceMaps: true,
	  i18n,
	  async redirects() {
		return [
		  {
			source: '/da-en/:slug*',
			destination: '/en/:slug*',
			permanent: true,
		  },
		  {
			source: '/fi-en/:slug*',
			destination: '/en/:slug*',
			permanent: true,
		  },
		  {
			source: '/fi-sv/:slug*',
			destination: '/sv/:slug*',
			permanent: true,
		  },
		  {
			source: '/no-en/:slug*',
			destination: '/en/:slug*',
			permanent: true,
		  },
		  {
			source: '/sv-en/:slug*',
			destination: '/en/:slug*',
			permanent: true,
		  },
		]
	  },
	}

	module.exports = nextConfig

Github Action

	name: build-tst-artifact

	on:
	  workflow_dispatch:
		branches: [ acc ]

	jobs:
	  build:
		name: Build Image and push | BaseImage
		env:
		  runner_image: quay.io/redhat-github-actions/buildah-runner
		  runner_memoryrequest: 8000Mi
		  runner_memorylimit: 8000Mi
		  # runner_cpurequest: 800m
		  # runner_cpulimit: 1600m
		runs-on: linux

		strategy:
		  matrix:
			node-version: [18.12.1]

		steps:
		- uses: actions/checkout@v3
		- name: Docker using Buildah
		  uses: redhat-actions/buildah-build@v2
		  with:
			image: my-image
			dockerfiles: |
			  ./Dockerfile
			context: .
			load: true

Dockerfile

	FROM node:18 AS deps
	WORKDIR /app

	COPY package.json package-lock.json ./
	RUN  npm install --omit=dev

	FROM node:18 AS builder
	WORKDIR /app
	COPY --from=deps /app/node_modules ./node_modules
	COPY . .

	ENV NEXT_TELEMETRY_DISABLED 1

	RUN npm run build --debug

	FROM node:18 AS runner
	WORKDIR /app

	ENV NODE_ENV production
	ENV NEXT_TELEMETRY_DISABLED 1

	COPY --from=builder /app/.next ./.next
	COPY --from=builder /app/node_modules ./node_modules
	COPY --from=builder /app/package.json ./package.json

	USER nextjs

	EXPOSE 3000

	ENV PORT 3000

	CMD ["npm", "start"]

### Describe the Bug

npm run build fails with exit code 137:

	[2/3] STEP 6/6: RUN npm run build --debug

	> forms@0.1.0 build
	> next build

	info  - Loaded env from /app/.env
	info  - Linting and checking validity of types...
	info  - Creating an optimized production build...
	info  - Compiled successfully
	info  - Collecting page data...
	Killed
	npm notice 
	npm notice New minor version of npm available! 9.5.1 -> 9.6.5
	npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.5>
	npm notice Run `npm install -g npm@9.6.5` to update!
	npm notice 
	subprocess exited with status 137
	subprocess exited with status 137
	[3/3] STEP 1/11: FROM node:18 AS runner
	error building at STEP "RUN npm run build --debug": exit status 137
	time="2023-04-28T14:32:28Z" level=error msg="exit status 137"
	Error: Error: buildah exited with code 137

### Expected Behavior

Not run out of plenty memory

**Comment by JacobMGEvans** [comment]
Seems like potentially a memory issue with the Docker setup. 

1. Could increase the memory of the docket setup from the 8000Mi to 12k 

2. If the directories don't need to be in both locations from build you can move them rather than copying 

3. A smaller Node image `node:18-slim` which should be around 188MB 

Hope any of these help or you figured it out 🤙

**Comment by OZZlE** [comment]
Worked with 12k!
