### ISSUE TITLE
Docs: Provide examples of how to organise code by feature

### ISSUE THREAD

**Issue by AntonyM71** [vercel/next.js#48978]
### What is the improvement or update you wish to see?

Presently the documentation seems to assume that we have all our pages together, all our components together, and all our tests together. Whilst this is a common pattern it is increasingly common in large applications to group code by feature, rather than the file being a component or a test.

The primary advantage is that this more closely maps to how software development work is done, typically we work on a vertical slice of functionality, say updating a component, it's test and it's redux store in a story, much more often than we update all the components or all the tests.

At the moment, the setup seems to assume that pages and tests must be in the root directory, and provides little detail on how to change this to meet the folder structure you want for your project, and what information there is seems to be drowned out on the internet by confusion around how the `pages` folder works.

A few topics that I might suggest:
- A pattern (with examples) for feature grouping of files in next.js
- Using the documentation on the pages directory  to consider using it simply as a router, to other components in a components directory (as this topic seems to cause a lot of confusion, and reduces the googlability of the test setup)
- What settings nextjs passes to testing suites by default, and how they differ from other frameworks (e.g. create-react-app) that you might migrate from

### Is there any context that might help us understand?

Whilst I've been able to pick up the idea that the pages (`src/pages`) directory can be used simply as a router, with components in a different (`src/components/<feature_name>`) directory . How to include the Jest tests as `.spec.ts` files within the component directory without having `test` and `pages` in the route of the folder seems tricky

**Comment by leerob** [comment]
https://nextjs.org/docs/app/building-your-application/routing/colocation
