### ISSUE TITLE
ESM project with appDir+typescript does not compile without typedRoutes

### ISSUE THREAD

**Issue by oxc** [vercel/next.js#49004]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.7.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.5.2
    Relevant packages:
      next: 13.3.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue

https://github.com/oxc/next.js-issue-appdir-esm

### To Reproduce

Run `npm run build`

You will get an error:

```
> build
> next build

warn  - You have enabled experimental feature (appDir) in next.config.mjs.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - Creating an optimized production build
info  - Compiled successfully
info  - Linting and checking validity of types ...Failed to compile.

info  - Linting and checking validity of types .app/layout.tsx
Type error: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("../../../app/layout.js")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.
```

![image](https://user-images.githubusercontent.com/1388972/235353408-e088c4f8-50dd-479e-ab88-db632732ade0.png)

### Workaround

Enabling the `typedRoutes` feature fixes type checking (see the `fix` branch in the reproduction repository).

### Describe the Bug

When a next.js project uses experimental appDir, typescript, and ESM modules for project files, type checking is broken unless also typedRoutes is enabled.

The files in .next/types get interpreted by tsc as CommonJS, and fail to import the ESM modules in appDir.

The next-types-plugin already provides the code to generate a package.json that marks those types files as module, but it is only generated when the typedRoutes feature is enabled:
https://github.com/vercel/next.js/blob/285e77541f55a8ec720a4b92154668eccce4dee1/packages/next/src/build/webpack/plugins/next-types-plugin.ts#L676-L690

This file also needs to be generated when the root project has type:module (and typedRoutes is not enabled).

### Expected Behavior

`npm run build` should build the application correctly, regardless of whether typedRoutes is enabled.

**Comment by oxc** [comment]
This started happening in 13.2.0, and did not occur in 13.1.6

**Comment by DuCanhGH** [comment]
This works probably due to the fact that we add a `package.json` with `{"type": "module"}` to `.next/types`, but only when `typedRoutes` is enabled. Should be an easy fix :)
