### ISSUE TITLE
[AppDir] "use server"; opts page into dynamic, supresses `dynamic = 'error'`

### ISSUE THREAD

**Issue by oBusk** [vercel/next.js#49007]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: 9.6.5
      Yarn: 1.22.19
      pnpm: 6.34.0
    Relevant packages:
      next: 13.3.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/oBusk/next-dynamic-bug

### To Reproduce

- In any app dir page, import a commponent which has `"use server";` at the top.
- The page will now always render dynamically instead of statically
- The page will not give an error if you try to access dynamic functions or searchParams even if you have `dynamic = 'error'`
- If you add `generateStaticParams()`, the `dynamic = 'error'`will start working as expected, and give an error, as you would expect.

### Describe the Bug

I was struggling to figure out why my page was rendering dynamically eventhough I had [`export const dynamic = 'error'`](https://beta.nextjs.org/docs/api-reference/segment-config#dynamic). I realised that it was because I was importing a component which I had tried to ensure was rendering on the server by using the `"use server";` directive at the top. 

### Expected Behavior

Page respects rendering choices of `dynamic = 'error'` or `dynamic = 'force-static'` even if you happen to import a component that has ´"use server";`.
If the case is that `"use server";` should never be used in appDir, it should probably throw an error and inform the developer about how to appropiately ensure a component is always executed on the server.

**Comment by shuding** [comment]
This is a bug that we'll fix soon.

**Comment by jasonsilberman** [comment]
hey @shuding, I am running into this too. I have a page with:

```js
export const dynamic = "force-static";
```

but it is somehow still being dynamic rendered even though I have `generateStaticParams`. I think I am running into this same bug, are there any updates here?

**Comment by shuding** [comment]
Hey, I just confirmed that this issue is gone in the latest `next@canary`. Using the same reproduction, the route is now static:

![CleanShot-2024-01-18-TY2mRiNu@2x](https://github.com/vercel/next.js/assets/3676859/4b06a566-9c27-4d95-89b9-ec4610dfa6c5)

Closing the issue now - feel free to re-open if you have a new reproduction. Cheers!
