### ISSUE TITLE
Next.Js Bigcommerce Integration

### ISSUE THREAD

**Issue by zilmehta-ets** [vercel/next.js#49026]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
I'm following the below documentation for integration between Next js and Bigcommerce. 
https://developer.bigcommerce.com/api-docs/storefronts/nextjs-commerce.

Even though I selected Bigcommerce in the "Add Integrations", the code that is getting cloned if Next.Js + Shopify and not Bigcommerce.

I contacted Bigcommerce team however they have mentioned the issue is from Vercel end.
```

### Link to the code that reproduces this issue

-

### To Reproduce

![image](https://user-images.githubusercontent.com/24618095/235417271-6366ec53-b979-4fd8-be20-a1e0cb22dfae.png)
![image](https://user-images.githubusercontent.com/24618095/235417311-8e6667f1-6bab-467b-ab82-5551c5335db5.png)
![image](https://user-images.githubusercontent.com/24618095/235417337-8d185e9f-d5da-44e5-950a-58514f1b67a6.png)

### Describe the Bug

As you can see in the screenshots attached, the code that is getting cloned if of Shopify and not Bigcommerce.

### Expected Behavior

The cloned code should be Next.Js + Bigcommerce.

### How are you deploying your application? (if relevant)

Vercel

**Comment by leerob** [comment]
Hey there! This is because v2 of Commerce is using Shopify. Please see the README for instructions on using BigCommerce with v1.

https://github.com/vercel/commerce/releases/tag/v1
