### ISSUE TITLE
Docs: Route Segment Config Options

### ISSUE THREAD

**Issue by 623059008** [vercel/next.js#49025]
### What is the improvement or update you wish to see?

I'm trying to export config in `route.ts` to set bodyParser close.
In old version, it is declared by
```
export const config = {
api:{
bodyParser: false
}
}
```
But in next13, I got this error:
Error: `export const config` in /vercel/path0/app/api/xxx/route.ts is deprecated. Please change `runtime` property to segment export config. See https://beta.nextjs.org/docs/api-reference/segment-config
I need more docs and explaination about how to set bodyParser close in new version.

### Is there any context that might help us understand?

The reason I want to set the bodyParser close is because I need to get the raw body to validate the webhooks from other platform like Shopify.

### Does the docs page already exist? Please link to it.

https://beta.nextjs.org/docs/api-reference/segment-config

**Comment by timneutkens** [comment]
The body is not parsed by default in `route.ts`. It uses the web `Request` that you can use to read the body. If you don't read the body it's not read, so the option is not relevant for `route.ts`.

```
export default function GET(request: Request) {
   // get body as text
   // const text = request.text()

   // get body as json (parses the body as JSON)
   // const json = request.json()
}
```

**Comment by ikebastuz** [comment]
@623059008 Have you managed to get raw body for webhooks?

Setting up stripe, but whatever I try from `NextRequest` - is not working
```
Webhook payload must be provided as a string or a Buffer
```
Tried passing 

- request
- request.body
- request.json()
- await buffer(request.body)

**Comment by MyManAy** [comment]
> @623059008 Have you managed to get raw body for webhooks?
> 
> Setting up stripe, but whatever I try from `NextRequest` - is not working
> 
> ```
> Webhook payload must be provided as a string or a Buffer
> ```
> 
> Tried passing
> 
> * request
> * request.body
> * request.json()
> * await buffer(request.body)

So apperently if you are using the App router in Nextjs the bodyParser is actually **disabled** by default. For Stripe, it requires the "raw body" from the request, and you can obtain it by using `req.text()` 

```typescript
export async function POST(req: Request, res: any) {
  const text = await req.text();
  const headersList = headers();
  const stripeSignature = headersList.get("Stripe-Signature");
  console.log(stripeSignature);

  let event;
  try {
    event = stripe.webhooks.constructEvent(
      text,
      stripeSignature!,
      webhookSecret!
    );
```
