### ISSUE TITLE
Parallel route with interception results in 404 error

### ISSUE THREAD

**Issue by glecetre** [vercel/next.js#49032]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.3.3-canary.2
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/fervent-hawking-7z1jjx

### To Reproduce

1. Go to the main page (`/`) -> error 404
2. Go to `/posts/1` -> error 404
3. In the root layout, remove the modal from the render -> everything works (but no interception)

### Describe the Bug

When using a parallel route that includes an route interception, any route gives a 404 error.

Note: I've seen #48232 already created but the author mentions a bit of a different bug that is a bit different so I opted to create a new issue.

### Expected Behavior

The routes should render correctly and the @modal should intercept navigation.

**Comment by timneutkens** [comment]
You need to create a `default.ts` (or `.js`) as the default in Next.js is to call `notFound()` as parallel routes cover more than just modals. https://beta.nextjs.org/docs/routing/parallel-routes#defaultjs. You can also refer to the demo for modals: https://github.com/vercel-labs/nextgram
