### ISSUE TITLE
Navigating to root route not working only adds .txt on the end

### ISSUE THREAD

**Issue by allestaire** [vercel/next.js#49042]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.1
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app)

### Link to the code that reproduces this issue

none

### To Reproduce

Try navigating to `router.push('/')` the result url with generate `mywebsite.txt` instead of `mywebsite/`
This only happens on **export** or build version of the app, but works fine on development server

### Describe the Bug

Routing bug

### Expected Behavior

Should navigate to root route

### Which browser are you using? (if relevant)

Chrome

**Comment by eliasdefrancisco** [comment]
Me too, every static page generated in the /out directory with  output: "export", generates an extra file .txt with same name as page, and page source code includes this .txt lines inside <script> tags

**Comment by eliasdefrancisco** [comment]
Here you have a Github repo documenting the bug
[https://github.com/eliasdefrancisco/next13_txt_bug](https://github.com/eliasdefrancisco/next13_txt_bug)
Hope this help :-)

**Comment by timneutkens** [comment]
@eliasdefrancisco what's shown in the readme is not a bug, it's how RSC works. Similar to getStaticProps/getServerSideProps, React needs to have the rendered tree in order to hydrate. In the future the React team is planning on reusing the rendered html, but until then the scripts holding the information for hydration are expected. The `.txt` file is used for navigation, it's the RSC payload.

**Comment by eliasdefrancisco** [comment]
@timneutkens thank's for your reply. Needs react that hydration tree for rendering STATIC pages? I'm almost sure NextJs 12 and 13 without appDir works very well without that bunch of redundant information. If thats the new way of working, I think it's very SEO unfriendly :-(

**Comment by eliasdefrancisco** [comment]
Thank's again for quickly reply @timneutkens, I doubt that bunch of <script> tags at the end of STATIC pages improves SEO at all, may be better than pages flavor. I think another migration is incoming with the pain of my soul (︶︹︶)

**Comment by allestaire** [comment]
Sorry for the late response,
I didnt fix the issue but this might help:
* You can use .httaccess to redirect .txt to its original
* Also instead of using SSG, I transition to SSR instead, cause it won't have any issues regarding on routing.
