### ISSUE TITLE
'ReferenceError: document is not defined' in Client Component

### ISSUE THREAD

**Issue by SamKomesarook** [vercel/next.js#49139]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.1.0
      npm: 8.19.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.5-canary.5
      eslint-config-next: 13.3.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Kiwi-Biosciences/render-test

### To Reproduce

Clone the repo, and attempt to build.

### Describe the Bug

The build fails due to a reference issue.

### Expected Behavior

The build should succeed, as it references the document var inside a client component.

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

AWS Amplify

**Comment by timneutkens** [comment]
```tsx
export default function Wrapper({ children }: { children: React.ReactNode }) {
  useEffect(() => {
	  var w = document.documentElement.clientWidth || window.innerWidth;
	  console.log(w);
  })
  return <div>{children}</div>;
}
```

Client components render on both the server and client, it's basically the same as all React components in `pages` today.

Please have a look at the documentation here: https://beta.nextjs.org/docs/rendering/server-and-client-components#client-components
