### ISSUE TITLE
redirect from 'next/navigation' doesn't accept a status code or permanent value

### ISSUE THREAD

**Issue by LotharVM** [vercel/next.js#49148]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.5-canary.3
      eslint-config-next: 13.0.2
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/inspiring-dijkstra-yu6r2t

### To Reproduce

When opening the CodeSandbox, a redirect happens to `/permanent-redirect`. This automatically gets a `302` status code.

### Describe the Bug

In Next.js prior to v13, you could set the status code of a redirect, in for example `getStaticProps`, via the `permanent` value like so:

```javascript
redirect: { 
   permanent: true, 
   destination: <url>
}
```

In Next.js v13 (app folder) there's no way to set the status, it automatically sets it to 302.

### Expected Behavior

Allow a second parameter to be passed to the `redirect` function. Either `permanent` or a status code, as long as it's possible to change it to whatever works for your specific use case.

Something like this:
```javascript
redirect('/permanent-redirect', true)
redirect('/permanent-redirect', 308)
```

**Comment by timneutkens** [comment]
This is intentional, as anytime you call `redirect()` it will be at the point where the stream has already started, so you can't edit the statusCode anymore. If you want to have permanent redirects the recommendation is to use Middleware as it will run in front of any request, before streaming starts.

**Comment by remorses** [comment]
@timneutkens does `cache()` work between `middleware.js` and server components?

**Comment by timneutkens** [comment]
The `React.cache()` only works in the context of the same React rendering.

Next.js Cache: https://nextjs.org/blog/next-13-2#nextjs-cache does work in middleware, as it's a more generic caching layer backed by a datastore.
