### ISSUE TITLE
Bug reproduce templates don't work again

### ISSUE THREAD

**Issue by studentIvan** [vercel/next.js#49143]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
any
```

### Which example does this report relate to?

reproduction-template

### Describe the Bug

success Install finished in 5.406s
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Downloading WASM swc package...
ERR!: Unknown command `config`

Try this: turbo --help
warn  - Attempted to load @next/swc-linux-x64-gnu, but an error occurred: Cannot load native addon because loading addons is disabled: /home/projects/vercel-next-js-8kkbdm/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node
warn  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
warn  - Attempted to load @next/swc-linux-x64-musl, but an error occurred: Cannot load native addon because loading addons is disabled: /home/projects/vercel-next-js-8kkbdm/node_modules/@next/swc-linux-x64-musl/next-swc.linux-x64-musl.node
error - Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc

### Expected Behavior

expected working

### To Reproduce

1. run stackblitz or other example platform with template
2. get error

**Comment by diegohaz** [comment]
Link to reproduction: https://stackblitz.com/edit/nextjs-pwaxql

**Comment by timneutkens** [comment]
The template only mentions codesandbox now.
