### ISSUE TITLE
Crazy random full page reloads when combining app dir and pages dir

### ISSUE THREAD

**Issue by klarstrup** [vercel/next.js#49154]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```swift
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/klarstrup/next.js-repro-repo/tree/random-hard-navigation

### To Reproduce

Enable appDir and have a static page in /app as well as a route in /pages with a dynamic and a catchall segment.

The repro includes an example for iterating through combinations of catch all segment values at http://localhost:3000/dynamic-part/7/1

### Describe the Bug

What should be client-side soft navigations become hard page loads at seemingly randomly URLs like `Router.replace("/dynamic-part/7/2")` and `Router.replace("/dynamic-part/7/3")`, but not adjacent URLs on the same route such as `Router.replace("/dynamic-part/7/1")` and `Router.replace("/dynamic-part/7/4")`

### Expected Behavior

`Router.replace("/dynamic-part/7/2")` and `Router.replace("/dynamic-part/7/3")` should behave just as `Router.replace("/dynamic-part/7/1")` and `Router.replace("/dynamic-part/7/4")` do, with a fully client-side navigation without a page reload.

**Comment by klarstrup** [comment]
No, this bug does not happen without the static and unused `/app/ping/page.js` page. 

Yes it only happens for specific combinations of catch all segment values.

**Comment by klarstrup** [comment]
Probably related to the 2% warned here https://github.com/vercel/next.js/pull/46283

But should this come into play at all for a navigation within the exact same route?

**Comment by klarstrup** [comment]
Remains relevant as of 13.4.1

**Comment by klarstrup** [comment]
Remains relevant as of 13.4.2 and 13.4.3-canary.0

**Comment by klarstrup** [comment]
This reproduction seems to have been fixed as of 13.4.3-canary.1, owing to https://github.com/vercel/next.js/pull/49741 I suppose

**Comment by klarstrup** [comment]
Will reopen this if I happen upon it in the real world again, but this repro seems to have gone the way of the dodo.

**Comment by ijjk** [comment]
Closing per https://github.com/vercel/next.js/issues/49154#issuecomment-1551522112 as sounds like this is corrected now, let us know if you are still seeing issues with this after that patch!
