### ISSUE TITLE
Intercepted & Parallel Routes Don't Always Render

### ISSUE THREAD

**Issue by keegandonley** [vercel/next.js#49176]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.1
      npm: 8.18.0
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant packages:
      next: 13.3.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/keegandonley/keegan.codes

### To Reproduce

This can be reproduced by visiting the `/blog` page, and clicking around for a while. After some time has passed, certain pages fail to load and the route doesn't transition on click. The page is live at `https://keegan.codes/blog` and the repo is open-source

### Describe the Bug

My blog uses parallel routes and intercepted routes to display blog posts in a "modal" when they are clicked. After some time is passed and some clicks have occurred successfully, the modal will suddenly fail to appear to some posts, and the route doesn't transition. The network request for the post still occurs.

This video highlights that some clicks work and some don't, but the network request for the new page can still be seen:

https://user-images.githubusercontent.com/12700819/236058856-4177af5b-a821-4428-85e3-e64707dc9e11.mov

### Expected Behavior

Clicking on a link should produce the same behavior no matter how many times the action has previously been executed.

### Which browser are you using? (if relevant)

Brave Version 1.50.121 Chromium: 112.0.5615.138 

### How are you deploying your application? (if relevant)

Vercel

**Comment by keegandonley** [comment]
I should add that after a refresh links again work for a while, even ones that were previously not working

**Comment by aurbina83** [comment]
I’m experiencing this same issue. I don’t have anything fancy (parallel or intercepted routes). Just a next/previous pagination buttons. Every once in a while the next page fails to load. I’m logging my db query durations and they’re sub 20ms so it’s not the data fetching.

If I wait long enough, some times the page will load and it can be > 5s. 

If I refresh the page loads immediately.

**Comment by keegandonley** [comment]
Closing this stale issue as it is no longer affecting me
