### ISSUE TITLE
Missing `next dev --turbo` features

### ISSUE THREAD

**Issue by padmaia** [vercel/next.js#49174]
The Turbopack dev server is nearly feature complete, but here is a list of some outstanding issues:

* https://github.com/vercel/turbo/issues/4796
* https://github.com/vercel/turbo/issues/4802
* https://github.com/vercel/turbo/issues/4805
* https://github.com/vercel/turbo/issues/4806
* https://github.com/vercel/turbo/issues/4803
* https://github.com/vercel/turbo/issues/4807
* https://github.com/vercel/turbo/issues/4808
* https://github.com/vercel/next.js/issues/55592

Released in 13.5

* https://github.com/vercel/turbo/issues/4794
* https://github.com/vercel/turbo/issues/4795
* https://github.com/vercel/turbo/issues/4797
* https://github.com/vercel/turbo/issues/4798
* https://github.com/vercel/turbo/issues/4799
* https://github.com/vercel/turbo/issues/4801
* https://github.com/vercel/turbo/issues/4804
* https://github.com/vercel/turbo/issues/4809
* https://github.com/vercel/turbo/issues/4810

**Comment by sanny-io** [comment]
It also does not support exporting.

**Comment by padmaia** [comment]
> It also does not support exporting.
> 
> https://nextjs.org/docs/app/building-your-application/deploying/static-exports#configuration

This issue is specifically for dev server features. Production builds are not supported at all yet. At one point `next dev --turbo` would fail if you had this option configured, but now it will ignore it since it isn't relevant.

**Comment by crusoexia** [comment]
How about "Module federation" for micro-frontend architecture?

**Comment by adamrneary** [comment]
We are really excited to get this a try over at Watershed. For now, turbopack is failing because we are employing the `experimental.externalDir` flag, which we seem to believe that we need for our monorepo use case with pnpm. (See https://github.com/vercel/next.js/discussions/26420).

But this seems like a possible miscommunication, because Turbopack, Turborepo, Next.js…are all the same team. :)

Is there a working example of a monorepo that uses Turborepo and Turbopack with Next 13, where an app in one project is relying on, for example, UI components in another project? This seems like a bread and butter example, but we must have it wrong somewhere!

**Comment by lutfi-haslab** [comment]
I have error hydration using turbo,
```
Error: Text content does not match server-rendered HTML.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
```
and warning
```
Error: There was an error while hydrating this Suspense boundary. Switched to client rendering.
```
it works normally without `--turbo` i am using it because much faster than dev only

**Comment by TzviPM** [comment]
Not sure if this should be included in this list: https://github.com/vercel/turbo/issues/5347

**Comment by OttlikG** [comment]
I'm getting error when importing sass file from external lib from node_modules
```
@import '~flexboxgrid/css/flexboxgrid.css';

unable to resolve module "~flexboxgrid" with subpath "/css/flexboxgrid.css"
```

**Comment by lachlanjc** [comment]
Good news, webp image support landed in today's release! #52285

**Comment by TzviPM** [comment]
I went to test the new webp support, and I'm now experiencing an issues with route groups:

```
Non matching path () provided for /(main)
```

I have a main site and a microsite that don't share much layout, so my site (minus icons and metadata) is separated into a `(main)` route group and a `(microsite)` group, each with their own top-level layout.

When I try to load the home page in `(main)` with `next dev --turbo`, I get the following error information:

```
Non matching path () provided for /(main)

Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NodeRenderContentSource::get failed
- Non matching path () provided for /(main)
```

I don't have time to create a minimal repro right now, but if anyone has a similar issue, please feel free to tag me on any speculative work and I can try to pitch in when I have time.

**Comment by dungnk-admixion** [comment]
I'm definitely running into the same problem as @TzviPM. Normal `next dev` works fine though. For the time being I'll just stick to normal webpack while NextJS team sorts this out.

**Comment by osdiab** [comment]
It also fails if you have `typedRoutes` FYI

**Comment by Hollayemi** [comment]
I'm running into the same problem as @TzviPM. it works fine without the parenthesis though.

**Comment by tosave04** [comment]
I get the same problem on Route Groups with turbo as @TzviPM, after testing on a minimal app, the problem occurs only in --turbo and from next version **13.4.10-canary.5**
Error message
```jsx
Non matching path () provided for /(site)/(pages)

Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NodeRenderContentSource::get failed
- Non matching path () provided for /(site)/(pages)
```

**Comment by Hollayemi** [comment]
I am using webpack for now, I don't know what to do



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by brianbit9** [comment]
Same issue 

`Non matching path (login) provided for /(pages)/login`

**Comment by winverse** [comment]
same issue

next @13.4.6
`Runing`

next @13.4.7
`Runing`

next @13.4.8
`Runing`

next @13.4.9
`Runing`

next @ 13.4.10
```
Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NodeRenderContentSource::get failed
- Non matching path () provided for /(list)
```

next @ 13.4.11
```
Debug info:
- Execution of <NodeRenderContentSource as GetContentSourceContent>::get failed
- Non matching path () provided for /(list)
```

next @13.4.12
```
Debug info:
- Execution of <NodeRenderContentSource as GetContentSourceContent>::get failed
- Non matching path () provided for /(list)
```

See: [https://github.com/velog-io/velog/tree/main/packages/velog-web](https://github.com/velog-io/velog/tree/main/packages/velog-web)

**Comment by jaycedotbin** [comment]
7c67b1216cecdd75f054a859766615880e1d50ed Fixes the route groups issue, it landed at [13.4.13-canary.5](https://github.com/vercel/next.js/releases/tag/v13.4.13-canary.5)

**Comment by mattcoker** [comment]
> [7c67b12](https://github.com/vercel/next.js/commit/7c67b1216cecdd75f054a859766615880e1d50ed) Fixes the route groups issue, it landed at [13.4.13-canary.5](https://github.com/vercel/next.js/releases/tag/v13.4.13-canary.5)

Can confirm, [13.4.13-canary.5](https://github.com/vercel/next.js/releases/tag/v13.4.13-canary.5) fixed the route groups bug for me.

**Comment by cutsoy** [comment]
I'm running into some issues getting Intercepting Routes to work. Has anyone else managed to get it working with Turbo (or with SSG)?

**Comment by 2Senn** [comment]
having the same issue as @lutfi-haslab  hydration error when importing a client component into a server component. It works fine on normal dev. Anyone found a workaround for this?

**Comment by timneutkens** [comment]
Going to close this specific issue as we no longer need a larger tracking issue, please report bugs / changes you'd like in a new issue.

In case of @wojtekmaj we already chatted on X but `.js` resolving as `.ts` is planned, that is not supported with Next.js out of the box today with webpack either so there's no tests for it. In this case you edited webpack configuration to change the resolving.

**Comment by pawelblaszczyk5** [comment]
> Going to close this specific issue as we no longer need a larger tracking issue, please report bugs / changes you'd like in a new issue.
> 
> In case of @wojtekmaj we already chatted on X but `.js` resolving as `.ts` is planned, that is not supported with Next.js out of the box today with webpack either so there's no tests for it. In this case you edited webpack configuration to change the resolving.

Any plans for experimental.typedRoutes in turbo?

**Comment by timneutkens** [comment]
Eventually, yes, but right now we're focusing on stable features and bugfixes first as there's only so much time in day 🙂

**Comment by pawelblaszczyk5** [comment]
Understandable 😃 Just wanted to know whether it’s planned at all, thank you very much for the answer, awesome job!
