### ISSUE TITLE
Links stop working at some point for next.js 13.x (was fine with next.js 12.x)

### ISSUE THREAD

**Issue by MartinXPN** [vercel/next.js#49215]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Next.js versions I've tried: 13.3.3 and 13.3.4
Worked fine with Next.js 12.x
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/MartinXPN/profound.academy

### To Reproduce

When opening any of the courses here: https://profound.academy then going back to the homepage, then opening another course, then going back to the homepage, and repeating this process 4-5 times freezes the `Link` component.
I can see that the data is retrieved in the server logs, but the front-end does not navigate to the clicked link.
The only way to make it work is by refreshing the page.
There are no error messages or warning anywhere in the logs.

### Describe the Bug

After several navigations where the (probably prefetching of the link) link causes the UI to freeze and not navigate to any clicked element.
The previously cached links work fine at that point. The new links don't work at all. Other elements like buttons, text, etc work fine but new links do not navigate anywhere. The user gets stuck.

### Expected Behavior

The user should be able to navigate to any link they click (that worked fine with next.js version 12.x).

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
Following the steps, I cannot seem to be reproducing this behavior. Does this happen only when deployed, or locally as well? Could you in any case try out the latest version of Next.js to make sure it's not something already fixed? I see you are using the App Router, which we've iterated on a lot recently.

The reproduction is a bit verbose, could you see if you can cut it down to a more minimal version where can still experience the issue so we can investigate further? Thanks!

**Comment by switz** [comment]
I have seen this happening on my self-hosted nextjs app using the app dir. Seems like it only started recently. I've been trying to reproduce it.

**Comment by MartinXPN** [comment]
I just redeployed the app with the latest 13.4 version and seems like the issue is gone. 
Besides, the website feels a LOT FASTER! I didn't expect such a speedup from the update.
Big thanks to the Next.js team for the improvements on the app router!
