### ISSUE TITLE
appDir experimantal is always present in the config file

### ISSUE THREAD

**Issue by Natchii59** [vercel/next.js#49239]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: N/A
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.0
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app)

### Link to the code that reproduces this issue

no link

### To Reproduce

Just create a new Next.js application with the latest version (13.4.0), and check the configuration file (next.config.js)

### Describe the Bug

The object that allows to define that we use the appDir functionality in experimental version is always present when creating a new application while it is now in stable version.
```typescript
experimental: {
  appDir: true,
}
```

### Expected Behavior

Remove this configuration when creating new applications.

### Which browser are you using? (if relevant)

Version 112.0.5615.137 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

No deploy

**Comment by tony1658** [comment]
See #49241

**Comment by ajaxbo360** [comment]
Oh , ok i see , i was trying to fix this issue before i saw your comment  @tony1658
