### ISSUE TITLE
turbopack error during Next.js routing for /

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#49233]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next v13.3.5-canary.12
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Turbopack (--turbo)

### Link to the code that reproduces this issue

no response

### To Reproduce

next dev --turbo

### Describe the Bug

error during Next.js routing for /admin/cost-conditions

Caused by:
- router evaluation failed: received error from javascript stream
- could not find app asset

Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NextRouterContentSource::get failed
- error during Next.js routing for /admin/cost-conditions
- router evaluation failed: received error from javascript stream
- Execution of get_evaluate_pool failed
- Execution of emit failed
- Execution of internal_assets failed
- Execution of separate_assets failed
- Execution of primary_referenced_assets failed
- Execution of NodeJsBootstrapAsset::references failed
- Execution of DevChunkingContext::evaluated_chunk_group failed
- Execution of EcmascriptChunk::parallel_chunks failed
- Execution of ecmascript_chunk_content_single_entry failed
- Execution of DevChunkingContext::can_be_in_same_chunk failed
- Execution of turbopack_core::ident::AssetIdentVc::path failed
- Execution of turbopack_core::ident::AssetIdentVc::with_modifier failed
- Execution of route_bootstrap failed
- could not find app asset

### Expected Behavior

no response

### Which browser are you using? (if relevant)

no response

### How are you deploying your application? (if relevant)

no response

**Comment by joacub** [comment]
Flag —root fix the problem

**Comment by jb-thery** [comment]
@joacub can you provide more information please ? I have the same issue on my turbo repo and vercel project

**Comment by joacub** [comment]
> @joacub can you provide more information please ? I have the same issue on my turbo repo and vercel project

You have two ways one is telling turbo the root of the project with the flag or in the next config  put the root in the outputFileTracingRoot and output standalone. It will work both ways

**Comment by jb-thery** [comment]
@joacub thanks ! but if I try this :  "dev": "next dev --turbo --root ../../",

I have an infinite loading and this error : 
```
web-app:dev: error - [resolve] ... [1 paths] are hidden, run with --show-all to show them

```

**Comment by joacub** [comment]
> @joacub thanks ! but if I try this : "dev": "next dev --turbo --root ../../",
> 
> I have an infinite loading and this error :
> 
> ```
> web-app:dev: error - [resolve] ... [1 paths] are hidden, run with --show-all to show them
> ```

humm, weird, I don't know what is you specific case, but it should something similar try doing this in your next config let me show you my setup:


```js
const nextConfig = {
  /**
   * Same as typechecking
   */
  eslint: {
    ignoreDuringBuilds: true,
  },
  /**
   * Ignore for now type checking errors no time for that
   */
  typescript: {
    ignoreBuildErrors: true,
  },
  /**
   * Compiler options for emotion development and source maps
   */
  // compiler: {
  //   // emotion: true,
  // },
  reactStrictMode: true,
  transpilePackages: [
    '@wsy/browser-utils',
    '@wsy/config',
    '@wsy/hooks',
    '@wsy/logger',
    '@wsy/next-intl',
    '@wsy/shared',
    '@wsy/socket.io-msgpack',
    '@wsy/store',
    '@wsy/ui',
  ],
  output: 'standalone',
  // swcMinify: true,
  experimental: {
    // typedRoutes: true,
    // workerThreads: 8,
    // swcMinify: true,
    swcFileReading: false,
    appDir: true,
    outputFileTracingRoot: path.join(__dirname, '../../'),
.........
```
