### ISSUE TITLE
[NEXT-1120] `draftMode().enable()` does not set cookie if followed by `redirect()`

### ISSUE THREAD

**Issue by jornki** [vercel/next.js#49237]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.19.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.0
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/jornki/next-draft-bug

### To Reproduce

1. Create the following Route Handler (/api/demo)

```typescript
// app/api/demo/route.ts
import { draftMode } from "next/headers";
import { redirect } from "next/navigation";

export async function GET(req: Request) {
	draftMode().enable();
	return redirect("/");
}
```

2. Call the the route.

### Describe the Bug

When using redirect in combination with `draftMode().enable();`, the `__prerender_bypass` cookie is not set. However, if you return a Response instead of using a redirect the cookie is set.

### Expected Behavior

The `__prerender_bypass` cookie should be set.

### Which browser are you using? (if relevant)

Tested with latest Firefox and Edge

### How are you deploying your application? (if relevant)

Tested locally (dev and start)

<sub>[NEXT-1120](https://linear.app/vercel/issue/NEXT-1120/setting-«draftmodeenable»-does-not-set-a-cookie-if-followed-by-a)</sub>

**Comment by andrew-mcmaster** [comment]
This was happening for me too, was able to fix with this for now.
```
return new Response(null, {
    status: 307,
    headers: {
        Location: path,
    },
})
```

**Comment by jornki** [comment]
> 

Thank you for the alternative solution @andrew-mcmaster.

**Comment by jamesMAwalker** [comment]
Also having this issue,  @andrew-mcmaster's solution worked for me as well.

**Comment by hrithikroboto** [comment]
I was pulling my hair until I saw this.

**Comment by mrgnou** [comment]
andrew-mcmaster solves __prerender_bypass cookie writing, but despite being correctly set, `draftMode().isEnabled` stays always `false` in any of my server components.

**Comment by maximilianschmitt** [comment]
It seems that `draftMode().disable()` also doesn't work when followed by a `redirect()`. @andrew-mcmaster's workaround works here too! :)
