### ISSUE TITLE
[NEXT-1146] Hashes are different between multiple servers with generateBuildId

### ISSUE THREAD

**Issue by mcAnastasiou** [vercel/next.js#49230]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 13.4.0
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/mcAnastasiou/nextjs-build-id

### To Reproduce

Try to build multiple times using a unique generateBuildId

### Describe the Bug

The webpack chunk hash and/or main chunk hash are different between different builds with the same generateBuildId

![Screenshot 2023-05-04 at 20 44 57](https://user-images.githubusercontent.com/45881723/236286848-12b0c86c-09f0-4c81-894b-e225abe5dabd.png)

### Expected Behavior

The webpack chunk hash should be the same when a build is using the same generateBuildId

<sub>[NEXT-1146](https://linear.app/vercel/issue/NEXT-1146/hashes-are-different-between-multiple-servers-with-generatebuildid)</sub>

**Comment by leonardofaria** [comment]
Having the same issue. The hashes from `main-app` and `webpack` are created by Webpack, it doesn't look like they are using the buildId (not sure if this was possible in the past).

One thing that I tried is to tweak the webpack config in the `next.config.js`:

```js
const config = {
  webpack: (config, options) => {
    const { dev } = options;
    if (!dev) {
      const hash = process.env.GIT_COMMIT_SHA || 'static-id';
      config.output = {
        ...config.output,
        filename: `[name].${hash}.js`,
      };
    }
    return config;
  },
};
```

The config above doesn't work:

```
unhandledRejection Error: Cannot find module '/my-project/apps/dazzle/.next/server/es/_document.56aa6e80b2604da2.js'
Require stack:
- /my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/server/require.js
- /my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/server/load-components.js
- /my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/build/utils.js
- /my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/build/worker.js
- /my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at /my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/server/require-hook.js:189:36
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at requirePage (/my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/server/require.js:156:12)
    at /my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/server/load-components.js:67:65
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async loadComponentsImpl (/my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/server/load-components.js:66:33) {
  type: 'Error',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/server/require.js',
    '/my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/server/load-components.js',
    '/my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/build/utils.js',
    '/my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/build/worker.js',
    '/my-project/node_modules/.pnpm/next@13.4.8_react-dom@18.2.0+react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
```

**Comment by Allan-Nava** [comment]
Any news to solve Issue with chunk hashes?

**Comment by dungmidside** [comment]
Is there any update ? It seem build id not work as expected when using for keep same output file name

**Comment by chk7964** [comment]
Also affect cache:yourdomain.com

**Comment by ishantgupta777** [comment]
Any updates here?

**Comment by neomad1337** [comment]
I created [PR](https://github.com/vercel/next.js/pull/62698) related to this issue.

Temporarily I installed a new package mini-css-extract-plugin@2.4.4 on the project and patched the import in the module located in ```/node_modules/next/dist/build/webpack/plugins/mini-css-extract-plugin.js```
You can patch it with ```yarn patch```.

After that, the problem stopped reproducing.

**Comment by rnacken** [comment]
It seems that this problem still exists (using Next 14.1.1). 

It is happening with both css-chunks AND the js-chunks (specifically `main-app-CHUNK` and `webpack-CHUNK`, all other js-chunk seem to be named correctly)

Since the issue happens on js-chunks as well (this was in the original post), I think closing this issue is premature at the moment @samcx 

Having said that; does anybody have any progress on a fix?
