### ISSUE TITLE
Docs: incorrect demonstration on React Essentials page

### ISSUE THREAD

**Issue by grefrit** [vercel/next.js#49240]
### What is the improvement or update you wish to see?

The demonstration in Thinking in server components is incorrect
![image](https://user-images.githubusercontent.com/45934058/236317931-b3ff6ee0-349d-40fb-9905-b71129f43782.png)

At right bottom corner it says that Client component is blue, a Server component is purple, but is it not true, it should be flipped

### Is there any context that might help us understand?

-

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/getting-started/react-essentials#thinking-in-server-components

**Comment by hzhu** [comment]
[Fixed in production:](https://nextjs.org/docs/getting-started/react-essentials#server-components)

<img width="1385" alt="Screenshot 2023-06-04 at 3 16 39 PM" src="https://github.com/vercel/next.js/assets/1811365/9619c2ce-d737-487d-a8ac-80bb33b0d0d6">

**Comment by leerob** [comment]
Fixed!
