### ISSUE TITLE
Docs: ability to enlarge image

### ISSUE THREAD

**Issue by grefrit** [vercel/next.js#49244]
### What is the improvement or update you wish to see?

It is impossible to see what is going on the image, so I think, we need an ability to enlarge image on  left mouse click
![image](https://user-images.githubusercontent.com/45934058/236319105-6738ec13-b379-4f42-b3a9-2140f027ed96.png)

It's an example, I cannot read code on this illustration, it is too small

### Is there any context that might help us understand?

An ability to enlarge image on left click

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/getting-started/react-essentials#client-components

**Comment by leerob** [comment]
Done!
