### ISSUE TITLE
[NEXT-1090] Property 'set' does not exist on type 'ReadonlyRequestCookies'.

### ISSUE THREAD

**Issue by pedro757** [vercel/next.js#49259]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Thu Apr  6 19:47:04 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.1-canary.1
      eslint-config-next: 13.4.1-canary.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/divine-firefly-4si8qm?file=%2Fpackage.json

### To Reproduce

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#using-headers

### Describe the Bug

The docs state that we can set cookies within a server action. but it's readonly

![image](https://user-images.githubusercontent.com/30637426/236352894-e830cbfd-d6de-4315-bad5-18d90e17fbd0.png)

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#using-headers

### Expected Behavior

I want to be able to do what the docs says:
https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#using-headers

<sub>[NEXT-1090](https://linear.app/vercel/issue/NEXT-1090/property-set-does-not-exist-on-type-readonlyrequestcookies)</sub>

**Comment by BoraALAP** [comment]
is there any update on this ??

**Comment by kristian240** [comment]
Seems to be working on `v13.4.1`

**Comment by borispoehland** [comment]
> Seems to be working on `v13.4.1`

I'm using 13.4.1 and for me it's not working

**Comment by ZeroThe2nd** [comment]
Just like @borispoehland, for me I'm also getting the error that `.set()` does not exist in `cookies()` imported as the example referred to in the original post linked.

I have the `serverActions: true` flag on, running `yarn next --version` reports `Next.js v13.4.1`. I've also tried removing node_modules and doing a `yarn upgrade` just to be sure.

Whenever I invoke `cookies().set(...)` from a server action, the following error appears in my terminal:

<img width="682" alt="image" src="https://user-images.githubusercontent.com/20568682/236704874-79ca9460-7434-4301-8205-7add5e6b0543.png">

Maybe this gives more of a lead?

**Comment by slacerda85** [comment]
I'm still having the same problem, but I noticed in the .pnpm file for the definitions, that the set value was omitted in the Typescript utility:

`/// <reference types="node" />
import type { RequestCookies } from '../cookies';
import type { BaseNextResponse } from '../../../base-http';
import type { ServerResponse } from 'http';
import { ResponseCookies } from '../cookies';
export declare type ReadonlyRequestCookies = Omit<RequestCookies, 'clear' | 'delete' | 'set'>;
export declare class RequestCookiesAdapter {
    static seal(cookies: RequestCookies): ReadonlyRequestCookies;
}
export declare const SYMBOL_MODIFY_COOKIE_VALUES: unique symbol;
export declare class MutableRequestCookiesAdapter {
    static seal(cookies: RequestCookies, res: ServerResponse | BaseNextResponse | undefined): ResponseCookies;
}`

maybe is something with those definitions, I dont know...

**Comment by DanieleSidoti** [comment]
I have the same problem

**Comment by mrob11** [comment]
`cookies().set` is working for me in a server action using the `next@13.4.2-canary.2`

**Comment by suhascv** [comment]
`cookies().set` using `Next.js v13.4.2-canary.2`  in server action doesn't work for me

```
Error: ReadonlyRequestCookies cannot be modified.
```

**Comment by johnson-jesse** [comment]
> `cookies().set` is working for me in a server action using the `next@13.4.2-canary.2`

✅ Confirmed. This is working in `13.4.2-canary.2` and `13.4.2-canary.3`. The typescript error still shows, but the app should still work. I no longer see the runtime error as show above.

```bash
Error: Invariant: Method expects to have requestAsyncStorage, none available at persistCookieState
```

I see the cookie set in the browser as expected via server action. Now if we can just get that TS error and the rest of those console warnings cleaned up, we'll be a happy crew.

**Comment by ma13gagan** [comment]
> Edit: This instance of `cookies().set()` is being called in a server action which is housed in an external file, that has `'use server'` as it's first line. The component it's being imported into is by itself not a client component, but one of its parent components is. This might actually be related to the issue at hand _in my case_.

Looks like we cannot use cookies in the Server Action if that Server Action is directly imported into the Client Component. I made it work by importing that Server Action in the Server Component first and then passing it as a prop in the Client Component. I don't know if it is the right way to achieve this.

**Comment by shuding** [comment]
This should be a TypeScript error as the `.set` method is missing. If you add `// @ts-ignore` it should pass build with latest canary version.

Will find a way to fix it properly.

**Comment by mrob11** [comment]
> This should be a TypeScript error as the `.set` method is missing. If you add `// @ts-ignore` it should pass build with latest canary version.
> 
> Will find a way to fix it properly.

Adding the `@ts-ignore` directive is allowing my build to pass now. Great! Looking forward to proper support.

**Comment by itsgoofer** [comment]
I'm on 13.4.1 and can confirm that, even though vscode is complaining, `.set` works just fine. However, building your project with `yarn build` throws the same error. Using `// @ts-ignore` gets you through building tho.

**Comment by maninderpreetsingh** [comment]
I tried on 13.4.1 by // @ts-ignore but after the build and starting project it's thorwing error! 
`ReadonlyRequestCookiesError: ReadonlyRequestCookies cannot be modified.`

**Comment by itsgoofer** [comment]
> I tried on 13.4.1 by // @ts-ignore but after the build and starting project it's thorwing error! `ReadonlyRequestCookiesError: ReadonlyRequestCookies cannot be modified.`

Make sure you are using `use server` wherever you're using `cookies().set`. That can be in an `action` or an `api route`.

**Comment by maninderpreetsingh** [comment]
I tried but still the cookie is not set and getting error "error unhandledRejection: Error: ReadonlyRequestCookies cannot be modified." on SSR. Also tried on canary build as well!

**Comment by anneau** [comment]
Same problem.

https://github.com/vercel/next.js/blob/062fbf6d2d1629ffa240b87af35955c51f5eaeaa/packages/next/src/client/components/headers.ts#L40-L47

It seems like it's being done intentionally...

**Comment by john-griffin** [comment]
Trying to set a cookie in a server action (dedicated server action file) triggered via a server component form action I get

`error Error: Invariant: Method expects to have requestAsyncStorage, none available`

in next `13.4.2`

**Comment by johnson-jesse** [comment]
Yes. See thread above

**Comment by john-griffin** [comment]
Ok I believe the confusion is between imported server action files vs in component server actions.

This currently works fine for inline server actions where `use server` directive is at the top of the function body.

It throws the `requestAsyncStorage` error for actions defined with top-level `use server` directive on top of a file.

**Comment by johnson-jesse** [comment]
@john-griffin Does this example repo I just set up help? https://github.com/johnson-jesse/next-server-action-cookies-demo

**Comment by josias-r** [comment]
Also experiencing this error in a simple server action file smth like:

```ts
"use server";

export async function myAction() {
   cookies().set(...); // TS Error
}
```

**Comment by john-griffin** [comment]
@johnson-jesse thanks, so it seems like you are triggering the file based server action from a client component using an onClick. This is not the exact case I have. It errors with `requestAsyncStorage` when it's a server component triggering via `<form action=`.

**Comment by johnson-jesse** [comment]
@john-griffin Sure, I've updated  https://github.com/johnson-jesse/next-server-action-cookies-demo to also show it working with server component and formAction. Let me know how that works please.

**Comment by john-griffin** [comment]
@johnson-jesse thats working great! I paired my example down to match and it seems ok now. It seems like something was being cached somewhere. Cheers!

**Comment by john-griffin** [comment]
@johnson-jesse actually I found the issue now.

I have another separate client component referencing the same actions file but a different action in that file.

Removing this form stops the `requestAsyncStorage` error from the first component.

It seems like if you have some client components and some server components calling into different server actions in the same file this issue will happen.

**Comment by johnson-jesse** [comment]
@john-griffin Not sure I follow. But you're working so we're good. 😎 I updated my [repo](https://github.com/johnson-jesse/next-server-action-cookies-demo) with more examples of some cross usage.

**Comment by sujang958** [comment]
What about setting Http-only cookies? How do I set Http-only cookies?

**Comment by josias-r** [comment]
> What about setting Http-only cookies? How do I set Http-only cookies?
Noticed the same, some types exist, but they are not fully correct. httpOnly, expiry date for example are missing :D

I think this issue shold be reopened

**Comment by deeq14** [comment]
I'm getting "Error: Invariant: Method expects to have requestAsyncStorage, none available" 

This happens when client component is calling an action from separate file with the "use server" directive at the top of the file like @john-griffin said

It works with no issue IF the page is server rendered and not using "use client"
