### ISSUE TITLE
useMemo problem in Next js when using contentlayer

### ISSUE THREAD

**Issue by RajinCoding2007** [vercel/next.js#49267]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
Relevant packages:
      next: 13.4.0
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

[https://github.com/RajinCoding2007/Next-ContentLayer-Bug](https://github.com/RajinCoding2007/Next-ContentLayer-Bug)

### To Reproduce

I followed contentlayer documentation and used `useMDXComponent(post.body.code)` to render markdown file and it causes error.

### Describe the Bug

I was following contentlayer documentation, I got this error:

```
- error node_modules\next\dist\compiled\react\cjs\react.shared-subset.development.js (1760:20) @ useMemo
- error TypeError: Cannot read properties of null (reading 'useMemo')
    at Page (./app/posts/[slug]/page.jsx:27:96)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
null
- error node_modules\next\dist\compiled\react\cjs\react.shared-subset.development.js (1760:20) @ useMemo
- error TypeError: Cannot read properties of null (reading 'useMemo')
    at Page (./app/posts/[slug]/page.jsx:27:96)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
digest: "2047166120"
null
```

### Expected Behavior

I expected that MDX page will be rendered successfully. I also made an issue in contentlayer repo:

[https://github.com/contentlayerdev/contentlayer/issues/449](https://github.com/contentlayerdev/contentlayer/issues/449)

### Which browser are you using? (if relevant)

Chrome

**Comment by Toshimichi0915** [comment]
Wrong
```jsx:app/posts/[slug]/page.jsx
export async default function Page({ params }) {
```

Correct:
```jsx:app/posts/[slug]/page.jsx
export default function Page({ params }) {
```

I checked the code works fine without async

**Comment by wadehammes** [comment]
For me, a similar error happens only when deployed to Vercel, for useEffect:

https://github.com/TanStack/query/issues/5371

**Comment by wadehammes** [comment]
I think this is related to https://github.com/vercel/next.js/issues/49261

**Comment by RajinCoding2007** [comment]
> Wrong
> 
> ```js
> export async default function Page({ params }) {
> ```
> 
> Correct:
> 
> ```js
> export default function Page({ params }) {
> ```
> 
> I checked the code works fine without async keyword. Please check Page function yourself. Thanks. ![image](https://user-images.githubusercontent.com/26406334/236394922-b39cf7a2-7f9b-493f-8c69-0652e7d0e766.png)

Yes, it works, but what if I really need `await` inside the Page? I don't need `await` right now, but I may need this in future.

**Comment by Toshimichi0915** [comment]
useMemo is pointless in server components because it does not re-render at all anyway.

`useMDXComponent` is defined as follows. So you can simply call `getMDXComponent` instead of `useMDXComponent`
```
export const useMDXComponent = (code: string, globals: Record<string, unknown> = {}) => {
  return React.useMemo(() => getMDXComponent(code, globals), [code, globals])
}
```

```jsx
import { allPosts } from 'contentlayer/generated'
import { getMDXComponent } from 'next-contentlayer/hooks'
import { notFound } from 'next/navigation'

export function generateStaticParams() {
  return allPosts.map((post) => ({
    slug: post._raw.flattenedPath,
  }))
}

export default async function Page({ params }) {
  // Find the post for the current page.
  const post = allPosts.find((post) => post._raw.flattenedPath === params.slug)

  // 404 if the post does not exist.
  if (!post) notFound()

  // Parse the MDX file via the useMDXComponent hook.
  const MDXContent = getMDXComponent(post.body.code)

  return (
    <div>
      {/* Some code ... */}
      <MDXContent />
    </div>
  )
}
```

**Comment by RajinCoding2007** [comment]
> useMemo is pointless in server components because it does not re-render at all anyway.
> 
> `useMDXComponent` is defined as follows. So you can simply call `getMDXComponent` instead of `useMDXComponent`
> 
> ```tsx
> export const useMDXComponent = (code: string, globals: Record<string, unknown> = {}) => {
>   return React.useMemo(() => getMDXComponent(code, globals), [code, globals])
> }
> ```
> 
> ```js
> import { allPosts } from 'contentlayer/generated'
> import { getMDXComponent } from 'next-contentlayer/hooks'
> import { notFound } from 'next/navigation'
> 
> export function generateStaticParams() {
>   return allPosts.map((post) => ({
>     slug: post._raw.flattenedPath,
>   }))
> }
> 
> export default async function Page({ params }) {
>   // Find the post for the current page.
>   const post = allPosts.find((post) => post._raw.flattenedPath === params.slug)
> 
>   // 404 if the post does not exist.
>   if (!post) notFound()
> 
>   // Parse the MDX file via the getMDXComponent.
>   const MDXContent = getMDXComponent(post.body.code)
> 
>   return (
>     <div>
>       {/* Some code ... */}
>       <MDXContent />
>     </div>
>   )
> }
> ```

Oh, thanks! It works.
