### ISSUE TITLE
Docs: wrong link in route handlers docs (app dir)

### ISSUE THREAD

**Issue by AviAvinav** [vercel/next.js#49271]
### What is the improvement or update you wish to see?

In the docs for route handlers(app dir), under the [behavior section](https://nextjs.org/docs/app/building-your-application/routing/router-handlers#behavior), the link in the last line is wrong, it redirects to https://nextjs.org/docs/app/building-your-application/routing/router-handlers#robotstxt-rssxml-and-sitemapxml when it should instead go to https://nextjs.org/docs/app/building-your-application/routing/router-handlers#non-ui-responses

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/router-handlers#behavior

**Comment by SamarthBagga** [comment]
Hi, could this issue be assigned to me? I would like to work on it.

**Comment by AviAvinav** [comment]
@SamarthBagga I don't think you need to be assigned, just look at the [contributing](https://github.com/vercel/next.js/tree/canary/contributing) readmes, and make a pr to fix this and wait for approval from the maintainers.

**Comment by SamarthBagga** [comment]
Sure! Thanks for the heads up.

**Comment by leerob** [comment]
Fixed
