### ISSUE TITLE
revalidatePath and revalidateTag missing types

### ISSUE THREAD

**Issue by HaoboZ** [vercel/next.js#49273]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 19.9.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.1-canary.1
      eslint-config-next: 13.3.2
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

a

### To Reproduce

`import { revalidatePath } from 'next/server';`

### Describe the Bug

It throws the error `Module '"next/server"' has no exported member 'revalidatePath'.`

### Expected Behavior

Should have no error

**Comment by eistruhe** [comment]
Had the same issue yesterday and found this [test](https://github.com/vercel/next.js/blob/fd319d3922178ec31ef5a7a70fc9a46397f160fb/test/e2e/app-dir/app-static/app/api/revalidate-path-edge/route.ts#L2). Looks like it got moved to `next/cache`? Documentation says it should be in `next/server` though.

**Comment by ijjk** [comment]
Hi, thanks for raising this, the above comment is correct and these should be imported from `next/cache` not `next/server` we will get docs updated accordingly!
