### ISSUE TITLE
New `app` directory 404 page issue

### ISSUE THREAD

**Issue by TheoKondak** [vercel/next.js#49281]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.0
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/TheoKondak/portolio-minimal-reproduction

### To Reproduce

When visiting a nonexisting route, a reoccurring error happens. It triggers every ~ 3sec.

![image](https://user-images.githubusercontent.com/25774466/236417302-a3fb393b-1c5a-4e42-928c-e2db955f35b8.png)

When visiting a non existing route that is under `experiences` route, where I use the `notFound()`, it does throw this error. 

If you spin the server in the minimal reproduction repo, you will see some buttons I have created and some instructions about the error.

### Describe the Bug

When browsing to a non-existing route, the `not-found.tsx` file is triggered, but along with it, a 404 GET error occurs.

### Expected Behavior

As happens with the routes that are under the `experience`, I would like to find a way to stop the error from occurring.

### Which browser are you using? (if relevant)

Chrome 112.0.5615.138

### How are you deploying your application? (if relevant)

Not relevant

**Comment by OatsProgramming** [comment]
@TheoKondak I had this issue before: I believe that there is no global Not-Found page yet. However, I found that you can circumvent the issue by doing a catch-all slug instead as shown below with [...not-found]:

<img width="201" alt="Screenshot 2023-05-06 at 12 32 40 AM" src="https://user-images.githubusercontent.com/107077453/236602290-1f1fdaea-4ed4-493e-9227-470f8111a25f.png">

Hope this helps!

**Comment by levipadre** [comment]
Will try @OatsProgramming, thanks for the idea. So would that be a page.tsx file inside or a 404.tsx and 500.tsx or else?

**Comment by OatsProgramming** [comment]
@levipadre I should've gotten to more detail earlier; sorry about that. 

What I've done is used a page.tsx and called notFound() from next/navigation to explicitly create a 404 error. I had a not-found.tsx file still at the root.

Best to show with pictures: 

The repo:
<img width="199" alt="Screenshot 2023-05-06 at 1 42 23 AM" src="https://user-images.githubusercontent.com/107077453/236607954-15e9aaae-cb37-4948-86b5-b491c9151047.png">

_Please take note of how there's a catch-all slug [...not-found] **and** a not-found.tsx file_

The code within [...not-found]/page.tsx:
![notfound](https://user-images.githubusercontent.com/107077453/236608073-5852c78f-3ffc-4619-a02b-392c726e0800.png)

**Comment by levipadre** [comment]
Thank you so much @OatsProgramming for the details. I'm gonna try it 🤞🏻

**Comment by TheoKondak** [comment]
> Same issue here, the "not-found" page doesn't trigger when I visit a not-existing page. I also use internationalization, so my structure is /app/[lang]/not-found.tsx

For me, the `not-found` page is triggered, and displayed, but it keeps trying to fetch the page in 3-second intervals (as seen in the screenshot).

Have you tried putting your not found in the root `app/` directory? I think that this is the way it is supposed to work. Not sure how you can apply internationalization though.

**Comment by TheoKondak** [comment]
> @levipadre I should've gotten to more detail earlier; sorry about that.
> 
> What I've done is used a page.tsx and called notFound() from next/navigation to explicitly create a 404 error. I had a not-found.tsx file still at the root.
> 
> Best to show with pictures:
> 
> The repo: <img alt="Screenshot 2023-05-06 at 1 42 23 AM" width="199" src="https://user-images.githubusercontent.com/107077453/236607954-15e9aaae-cb37-4948-86b5-b491c9151047.png">
> 
> _Please take note of how there's a catch-all slug [...not-found] **and** a not-found.tsx file_
> 
> The code within [...not-found]/page.tsx: ![notfound](https://user-images.githubusercontent.com/107077453/236608073-5852c78f-3ffc-4619-a02b-392c726e0800.png)

Thanks @OatsProgramming. Indeed this approach seems to work for me as well!

To make it easier for anyone else in the same situation, I will summarize what I did following your approach and solve the issue:

- In the root of `app/` create a new folder and give it a name of `[...not-found]`. The name of the folder is not important, but it's better to call it `not-found` for consistency.
- Create a new `page.tsx` file. The content of the file:
  ```js
  import { notFound } from 'next/navigation';
export default function NotFound() {
  notFound();
}
```

This means that whenever a route does not match with an existing route in your project, it will call the newly created page, and then call the `notFound()` which will redirect to the `not-found.tsx` page.

**Comment by OatsProgramming** [comment]
@TheoKondak glad it helped! Should prolly close this issue to lower the tasks for the vercel team if you think that the approach will do.

**Comment by levipadre** [comment]
I know the ticket is already closed. Maybe I've done something wrong or different but using this method when I visit a non-existing page, I got a NEXT_NOT_FOUND error message, but with the layout around the page. So instead of:
```
import { notFound } from 'next/navigation';

export default function NotFound() {
    notFound();
}
```

I added:
```
import { getDictionary } from '../dictionaries';

export default async function NotFound({
    params
}: {
    params: {
        lang: string
    }
}) {
    const dict = await getDictionary(params.lang);

    return (
        <main>
            <h1>404 page</h1>
            <h2>{dict.titles.home}</h2>
        </main>
    )
}
```
in `/src/app/[lang]/[...not-found]/page.tsx` page, which seems to work for me. I have a custom 404 page now when I visit a non-existing page.

But what about the custom 500 page? It was handled before App Router, right?

**Comment by OatsProgramming** [comment]
@levipadre That is something that probably should be placed in the question section. It does seem to get a little too specific and that it'd require to see the repo to understand the situation. But to try and answer: if you are using NextJS 13, then a custom 500 page is an error.tsx file. 

Here's the docs for handling errors: 
[https://nextjs.org/docs/app/building-your-application/routing/error-handling](https://nextjs.org/docs/app/building-your-application/routing/error-handling)

You can also checkout the component heirarchy for layout, errors, not-found, etc. here:
[https://nextjs.org/docs/app/building-your-application/routing#component-hierarchy](https://nextjs.org/docs/app/building-your-application/routing#component-hierarchy)

But from the sound of it, it seems that the version you're running with, or the syntax, is below NextJS 13. If that is the case, I can't really help any further. I apologize: my knowledge is filled more with NextJS 13 rather than any other version.

**Comment by TheoKondak** [comment]
@levipadre , which version of NextJs are you using? The way it worked for me is the one mentioned above for the `[...not-found]`, and I also have `not-found.tsx` in the root of the `app/`.

The minimal reproduction of the directory is this:

```
app/
  [...not-found]/
      page.tsx
  not-found.tsx
  page.tsx
```

Also, I am running NextJS 13.4 at the moment.

As @OatsProgramming  said, it's better to open a [discussion](https://github.com/orgs/vercel/discussions/categories/help).

**Comment by menadeth** [comment]
the solution above is not working on my side, its working on my local but in deployment its not working
