### ISSUE TITLE
[NEXT-1142] app increase bundle size of pages

### ISSUE THREAD

**Issue by QzCurious** [vercel/next.js#49286]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
Binaries:
  Node: 16.19.0
  npm: 8.19.3
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.4.1-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/QzCurious/nextjs-app-increase-bundle-size-of-pages

## Check the bundle size of pages of a clean next-app

1. `git clone git@github.com:QzCurious/nextjs-app-increase-bundle-size-of-pages.git`
2. `cd nextjs-app-increase-bundle-size-of-pages.git`
3. `git checkout e73f9f4`
4. `yarn`
5. `yarn build`
6. check output
![image](https://user-images.githubusercontent.com/38932402/236432508-d101b2aa-a9d5-46b7-b095-3ab0e5df4459.png)

## Check the bundle size of pages of a next-app with a `app/home/page.tsx`

1. `git checkout 93a54da`
2. `yarn`
3. `yarn build`
4. check output

![image](https://user-images.githubusercontent.com/38932402/236433338-c65ac68e-60e4-4901-a7b7-72b8e44a7bb2.png)

### Describe the Bug

By just adding a minimal page in app directory, it increase the bundle size of pages.

### Expected Behavior

The bundle size of pages should not affected by app directory.

<sub>[NEXT-1142](https://linear.app/vercel/issue/NEXT-1142/app-increase-bundle-size-of-pages)</sub>

**Comment by QzCurious** [comment]
Upgrade to 13.4.5-canary.0 solve the issue.

![image](https://github.com/vercel/next.js/assets/38932402/a7181718-b945-46e0-800b-8598630d1053)

**Comment by huozhi** [comment]
Thanks for confirming!
