### ISSUE TITLE
Docs: Misleading

### ISSUE THREAD

**Issue by allestaire** [vercel/next.js#49299]
### What is the improvement or update you wish to see?

The documentation for `_app.js` is no where to found, or the team just hide it somewhere that is not visible on the page?

### Is there any context that might help us understand?

Information on how to utilize `_app.js` that it seems missing on the site documentation

**Comment by allestaire** [comment]
Damn, dont know if the documentation is working fine.
This is the link if what I am looking for, but its not working, tsk tsk
https://nextjs.org/docs/pages/building-your-application/routing/custom-app

**Comment by allestaire** [comment]
Dont know what to do after creating the _app.js, should I import it to the page component or is it automatically overide?

**Comment by rafaelalmeidatk** [comment]
There is a toggle at the top of the navigation menu, you need to change it to "Using Pages Directory" since `_app` is not a thing with the App Router:

**Comment by allestaire** [comment]
I appreciate the upgrade because it much easier to put it on the layout other than create `_app.js`
