### ISSUE TITLE
Docs: thinking in server components diagram is wrong

### ISSUE THREAD

**Issue by amendezm** [vercel/next.js#49305]
### What is the improvement or update you wish to see?

I think the areas marked as blue are the server components

![image](https://user-images.githubusercontent.com/26444448/236472077-c2529e40-aaa9-4e7d-9254-5465a05f3ae4.png)

### Is there any context that might help us understand?

![image](https://user-images.githubusercontent.com/26444448/236471484-c7fbe175-931b-4a75-80e8-9e383fd61171.png)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/getting-started/react-essentials#thinking-in-server-components

**Comment by leerob** [comment]
Fixed!
