### ISSUE TITLE
[NEXT-1114] `content-length` is gone from requests since 13.4.0

### ISSUE THREAD

**Issue by VictorGlindasPaf** [vercel/next.js#49310]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 3.5.1
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/magical-euler-zto6yv

### To Reproduce

Try to access `req.headers['content-length']`

### Describe the Bug

`req.headers['content-length']` is undefined.

### Expected Behavior

`req.headers['content-length']` should be defined, and be the byte length of the body.

<sub>[NEXT-1114](https://linear.app/vercel/issue/NEXT-1114/content-length-is-gone-from-requests-since-1340)</sub>

**Comment by Glinkis** [comment]
@msheakoski
That's a bit weird. Things worked fine for me with `apollo-server-micro` in Next 13.3.x, but broke in 13.4.

**Comment by VictorGlindasPaf** [comment]
@huozhi This happens in the pages dir for us. We don't use the app dir. So not sure that tag is right for this issue?

**Comment by huozhi** [comment]
@VictorGlindasPaf no worries it's just tag that the root cause is related to app dir, will def check pages as well

**Comment by zhelezkov** [comment]
Hey, faced same issue. `Content-Length` header is gone, and I can't set it on my own, which causes different issues, for example it breaks video player on iOS if video served/proxied with next.

Do you think it's possible to override it somehow for APIs?

**Comment by programmarchy** [comment]
This worked for me up 13.2.4, then 13.3.0 broke my use case.

FWIW, my API route takes in a multipart form request from a regular HTML form, and forwards that request to a remote endpoint by setting `content-type` and `content-length` then streaming the body.

```
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const testId = getStringParam("testId", req.query);
  const variantId = getStringParam("variantId", req.query);
  const api = new API();

  const upload = await fetch(`api/tests/${testId}/variants/${variantId}/upload_pdf/`, {
    method: 'POST',
    body: req, // ReadableStream
    headers: {
      "content-type": req.headers["content-type"],
      "content-length": req.headers["content-length"]
    },
    duplex: "half",
  });

  if (!upload.ok) {
    throw new Error("Upload failed.");
  }

  res.redirect(303, `/tests/${testId}/variants/${variantId}/edit`);
}
```

This technique doesn't seem to work without `content-length`. The remote request is being handled by a Django 4.1.2 server.

**Comment by tomitrescak** [comment]
Is it possible that this change affects my API routes? I am getting empty `req.body` in every API. Basically all POST requests are broken.

**Comment by khalilsarwari** [comment]
@zhelezkov

You can try the following between install and build steps based on huozhi's pending changes:

```
sed -i '/"content-length",/d' 'node_modules/next/dist/esm/server/lib/server-ipc/utils.js' 
sed -i '/"content-length",/d' 'node_modules/next/dist/esm/server/web/sandbox/sandbox.js' 
sed -i '/"content-length",/d' 'node_modules/next/dist/server/web/sandbox/sandbox.js' 
sed -i '/"content-length",/d' 'node_modules/next/dist/server/lib/server-ipc/utils.js'
```
This fixes iOS playback for me :)

 @tomitrescak 
 
 Yes, it does affect API routes, though I found `compress: false` to be the real issue in my case:
 
 https://github.com/vercel/next.js/issues/50320
 
 Hope this helps!

**Comment by shawnlknight** [comment]
> #50320

@tomitrescak is this still happening for you? I believe we are experiencing a similar issue with empty req.body in our API routes.
