### ISSUE TITLE
App router will encounter abnormal 404 error in the latest version of 13.4.x.

### ISSUE THREAD

**Issue by isbasex** [vercel/next.js#49313]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.2.3
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/nextjs-13-4-1-bug-report-sy17wt?file=%2Fapp%2F%28public%29%2F_%2Flogin%2Fpage.tsx&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A18%7D%5D

### To Reproduce

1. open[codesandbox](https://codesandbox.io/p/sandbox/nextjs-13-4-1-bug-report-sy17wt?file=%2Fapp%2F%28public%29%2F_%2Flogin%2Fpage.tsx&selection=%5B%7B%22endColumn%22%3A23%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A23%2C%22startLineNumber%22%3A18%7D%5D)
2. visit: `/_/login`    You will see a 404 error page.
![404](https://user-images.githubusercontent.com/9151309/236500262-4ef0d12b-87ff-498a-8013-50fa347c5ae1.jpg)

3. But the same code works properly in version 13.2.3
see:  https://codesandbox.io/p/sandbox/nextjs-13-4-1-bug-report-forked-ih3xdo?selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A2%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A2%7D%5D&file=%2Fapp%2F%28public%29%2F_%2Flogin%2Fpage.tsx

### Describe the Bug
When you have the following directory structure, an abnormal 404 error will occur in the latest version 13.4.x.
![dir struct](https://user-images.githubusercontent.com/9151309/236503497-ba07b5ba-0add-4b23-8d08-bb8c42fd0ba8.jpg)

## Version 13.2.3 works properly
![working](https://user-images.githubusercontent.com/9151309/236498924-7fa8b3c6-da16-40a8-bc8e-15a7efa58ac0.jpg)

## The same code appears as 404 in the latest version
![404](https://user-images.githubusercontent.com/9151309/236500262-4ef0d12b-87ff-498a-8013-50fa347c5ae1.jpg)

### Expected Behavior

The latest version should behave consistently with the routing matching behavior of version 13.2.3, without any occurrence of 404 errors.

**Comment by eloekset** [comment]
How do you get from the default project structure from create-next-app to a structure with pages inside a pages folder? Isn't that the whole point of file based routing as they say in the tutorials? 
https://www.youtube.com/watch?v=f-6GAntaum4&list=PLC3y8-rFHvwgC9mj0qv972IO5DmD-H0ZH&index=6

![image](https://user-images.githubusercontent.com/791721/236561867-4f69598a-759c-4a81-9fd9-bfc622645a8c.png)

No matter where I put the layout.tsx and index.tsx/page.tsx relative to the pages directory, the result is always http 404 not found:
![image](https://user-images.githubusercontent.com/791721/236562160-198f6aaa-60e3-4d29-8069-8d8340a89236.png)

Just another web app framework with breaking changes between minor versions just to make sure it's impossible to learn how to get started.

**Comment by sayusufa** [comment]
Just encounter same issue after upgrading to the 13.4.1. Any piece of advice, please? 🙄

**Comment by timneutkens** [comment]
Folders starting with `_` are not routed by default, so that's why you're seeing that particular file not being routed. What you can do is use `%5F` instead of the `_` for the folder name (it's the escape character for `_`).

@eloekset sounds like you're using a tutorial that uses the `pages` directory. Last week we've introduced the App Router in the newest version of Next.js: https://nextjs.org/blog/next-13-4. You can choose `no` at the App Router question to get the `pages` directory instead.
