### ISSUE TITLE
Docs: overflowing text in docs 

### ISSUE THREAD

**Issue by mnik01** [vercel/next.js#49362]
### Bug: overflowing text in docs

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/39025497/236615530-fd66e36c-662e-4af4-840c-11f5d2b39ba2.png">

See `serverComponentsExternalPackages` block.
https://nextjs.org/docs/app/api-reference/next-config-js

### Is there any context that might help us understand?

https://nextjs.org/docs/app/api-reference/next-config-js
`serverComponentsExternalPackages` block

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/next-config-js

**Comment by Yana-Gupta** [comment]
@mnik01 
I want to fix this bug.

**Comment by Yana-Gupta** [comment]
Can you assign me to this issue.

**Comment by mnik01** [comment]
@Yana-Gupta I can't assign. But you can fork the project and fix the bug. Then open the Pull Request and mention there this issue

**Comment by sdkdeepa** [comment]
I am seeing the overflowing of text. It is truncated with three dots. Is this happening on a specific browser / screen size? 
<img width="662" alt="Screenshot 2023-09-25 at 12 16 19 AM" src="https://github.com/vercel/next.js/assets/19764585/797b3ad3-0d98-46c6-a697-156ada349e31">

**Comment by mnik01** [comment]
@sdkdeepa 
![image](https://github.com/vercel/next.js/assets/39025497/c83cacf8-2525-45d4-913f-902769385e7d)

Now I'm able to see it truncated. So I guess the issue is already fixed. Because of it, I will close this ticket
