### ISSUE TITLE
[NEXT-1185] revalidateTag is not working consistently

### ISSUE THREAD

**Issue by railaru** [vercel/next.js#49368]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.2
      npm: 9.3.0
      Yarn: N/A
      pnpm: 7.12.2
    Relevant packages:
      next: 13.4.1-canary.2
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://github.com/railaru/nextjs-postgres-starter-prisma

### To Reproduce

Background

This is a basic Next.js 13 Prisma template with server actions.

I've added the creation of new users and the editing and deleting of existing users.

Steps to reproduce:
1. Run the project locally with Postgress ENV variables 
2. All the CRUD operations work when adding/removing/updating users in the same page
3. When I go to users/:id and update a name or email there, it updates once
4. When editing the same user twice, the old cache is still in place even though revalidateTag('users') is run and the username only changes after I refresh the page

### Describe the Bug

Cache invalidation with revalidateTag and server actions is not working as expected. When doing CRUD actions on a different page, they don't work on other pages.

### Expected Behavior

I would like to see the same behaviour as doing CRUD actions in the route or refreshing the page. In other words, the UI should be updated even if I updated the form on a different route, since I removed the cache.

### Which browser are you using? (if relevant)

Chrome, Mac

### How are you deploying your application? (if relevant)

Locally, Vercel

<sub>[NEXT-1185](https://linear.app/vercel/issue/NEXT-1185/revalidatetag-is-not-working-consistently)</sub>

**Comment by shuding** [comment]
Looks like this was fixed by #50848, could you verify with latest canary? Thanks!
