### ISSUE TITLE
"next/link" from not-found.js does not work

### ISSUE THREAD

**Issue by DestroyerXyz** [vercel/next.js#49372]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.8.1
      npm: 9.5.1
      Yarn: 3.3.1
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/intelligent-jones-l7ifb9

### To Reproduce

1. Open any invalid page or one that doesn't exist.
2. Click the "Return Home" link.
3. Navigation doesn't take effect.

### Describe the Bug

Linking to the home page or any other page with "next/link" in the not-found.js file doesn't work.
It only changes the browser URL.

### Expected Behavior

It navigates to the specified page.

**Comment by marianobenitezz** [comment]
It is not working in the `app/not-found.tsx` file, but inside a route segment it works. E.g. `app/(shop)/not-found.tsx`

**Comment by DestroyerXyz** [comment]
@marianobenitezz It doesn't even load for me if I put it in a route segment.

**Comment by jinojacob15** [comment]
already raised in 13.3 version . when it will be fixed ?? link component and css are broken

**Comment by DestroyerXyz** [comment]
I'm using <a> for the time being but it forces a full reload on the client.

**Comment by TheEdoRan** [comment]
#47862
