### ISSUE TITLE
[NEXT-1136] Puppeteer error with Next13 app dir : TypeError: oe is not a function

### ISSUE THREAD

**Issue by jocarrd** [vercel/next.js#49383]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2
    Binaries:
      Node: 16.15.1
      npm: 8.11.0
      Yarn: 1.22.15
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.1-canary.2
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/friendly-violet-44ognx?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A20%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A20%7D%5D

### To Reproduce

Try to navigate to the path /api/scraper

### Describe the Bug

Server Error
TypeError: oe is not a function
![image](https://user-images.githubusercontent.com/55456507/236649524-40c0844b-2095-47bb-8753-cbf6935d527c.png)

### Expected Behavior

When using the pages directory, it correctly returns the h1 of the page, on the other hand, when migrating it to the api directory, it returns that error.

<sub>[NEXT-1136](https://linear.app/vercel/issue/NEXT-1136/puppeteer-error-with-next13-app-dir-typeerror-oe-is-not-a-function)</sub>

**Comment by timneutkens** [comment]
I've opened a PR to add puppeteer to the packages that are considered external. Until that is landed and out you can manually specify it in `next.config.js`:

```js
/** @type {import("next").NextConfig} */
module.exports = {
  experimental: {
    serverComponentsExternalPackages: ["puppeteer"],
  },
};
```

**Comment by jocarrd** [comment]
thank you @timneutkens
