### ISSUE TITLE
Docs: MDX using plugin code example fix

### ISSUE THREAD

**Issue by zenpk** [vercel/next.js#49391]
### What is the improvement or update you wish to see?

The current example of using Remark and Rehype Plugins in MDX is not working. I would like to see it fixed (the fixed code is shown below).

### Is there any context that might help us understand?

Original example Code:

```javascript
import addMdx from '@next/mdx';
 
const nextConfig = {
  pageExtensions: ['ts', 'tsx', 'js', 'jsx', 'mdx'],
  experimental: {
    appDir: true,
  },
};
 
addMdx(nextConfig, {
  options: {
    remarkPlugins: [],
    rehypePlugins: [],
    // If you use `MDXProvider`, uncomment the following line.
    // providerImportSource: "@mdx-js/react",
  },
});
 
export default nextConfig;
```

Fixed example code:

```javascript
import withMdx from "@next/mdx";

const nextConfig = {
  pageExtensions: ["ts", "tsx", "js", "jsx", "mdx"],
};

const mdxConfig = {
  options: {
    remarkPlugins: [],
    rehypePlugins: []
    // If you use `MDXProvider`, uncomment the following line.
    // providerImportSource: "@mdx-js/react",
  }
};

export default withMdx(mdxConfig)(nextConfig);
```

I changed the name `addMdx` to `withMdx` because in the previous example code you used `withMdx` and I think it would be better to use the same import name. Also, the `appDir` option seems no longer needed.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/configuring/mdx#remark-and-rehype-plugins

**Comment by MatthewCaseres** [comment]
The code you cite as being the original example code appears to no longer be there.

The code I see is this - 

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
};
 
const withMDX = require('@next/mdx')({
  options: {
    remarkPlugins: [],
    rehypePlugins: [],
    // If you use `MDXProvider`, uncomment the following line.
    // providerImportSource: "@mdx-js/react",
  },
});
module.exports = withMDX(nextConfig);
```

**Comment by zenpk** [comment]
@MatthewCaseres Thanks for the reply. It seems that they have updated it, now it should work fine :)

**Comment by MatthewCaseres** [comment]
Hey I'm having an error if you could check out my reproduction and maybe correct it I can close my ticket as well - https://github.com/vercel/next.js/issues/50110

**Comment by zenpk** [comment]
@MatthewCaseres Hi, I took a look, and according to the official doc 
 
> Create mdx-components.tsx in the root of your application (the parent folder of app):

Your mdx-components.tsx is not in the correct location. Since you're using the src folder, it should be put in the parent folder of src. After doing that everything seems working fine. I hope this helps.
