### ISSUE TITLE
Duplicate css-classes from page.css and layout.css when sharing component

### ISSUE THREAD

**Issue by ssandoy** [vercel/next.js#49395]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

I have noticed that when I use a component in both my layout.tsx and page.tsx files, the CSS-classes for that component is loaded into both stylesheets. 
This can result in conflicting CSS-ordering, which causes unexpected layout and styling issues.

For example, if you define a custom style for a component in layout.css, but also use the same component in page.tsx, the custom style may be ignored, since the CSS class is duplicated in both stylesheets, and the page.css class takes precedence due to the order of loading. 

Is this as intended?

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/sharp-poincare-8j3e6g?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A11%7D%5D&file=%2Fapp%2Fpage.tsx

### To Reproduce

1. Create a component and define some CSS rules for it.
2. Use that component in your layout.tsx file.
3. Use the same component in one of your page.tsx files.
4. Add a custom classname to the component inside layout.tsx
5. The styles from page.tsx gives precedence, ignoring the custom styles in layout.tsx

### Describe the Bug

When using a React component in both layout.tsx and page.tsx, conflicting CSS ordering can cause the custom style defined in layout.css to be ignored.

### Expected Behavior

Custom styles for a React component should work correctly, even when the component is used in multiple files or contexts.

**Comment by shuding** [comment]
Hi! I can reproduce the same issue in pages/ directory as well. The main issue was that the Footer component has these order of imports:

```js
import styles from "./footer.module.css";
import { ButtonBase } from "../button/Button";
```

So `footer.module.css` will end up being the first in the generated stylesheet, and then followed by Button's styles. If you swap these two imports, it should be good.
