### ISSUE TITLE
[NEXT-1167] Server Actions 405 "Method Not Allowed" when using generateStaticParams

### ISSUE THREAD

**Issue by arduano** [vercel/next.js#49408]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed, 26 Apr 2023 20:50:14 +0000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.0.6-canary.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

~~_No response_~~
Server actions. It seems like server actions wasn't part of the issue form dropdown earlier

### Link to the code that reproduces this issue

https://github.com/arduano/server-actions-repro

### To Reproduce

- `npm install`
- `npm run dev`
- Open `/asdf` in the browser
- Click the button, observe the network requests in the browser's dev tools

### Describe the Bug

Including `generateStaticParams` in a page breaks server actions, making it return 405 on each request

### Expected Behavior

The server actions behave as expected

<sub>[NEXT-1167](https://linear.app/vercel/issue/NEXT-1167/server-actions-405-method-not-allowed-when-using-generatestaticparams)</sub>

**Comment by AlexisWalravens** [comment]
Hi, can confirm just had the same bug.
The moment I remove generateStaticParams from the page the action works.

**Comment by TNury** [comment]
Same thing here

**Comment by NaderTate** [comment]
any updates on this issue?

**Comment by emondpph** [comment]
Also had the same issue with 405 http errors and errors in the console... Commenting the generateStaticParams function fixes. When are you expecting to publish the fix ?

**Comment by simpel** [comment]
Same for me! Trying to use server actions gave me 405 all the time. Removing generateStaticParams made the server actions work...but...yea.. I need generateStaticParams too! :)

**Comment by Tommoore96** [comment]
I'm not using `generateStaticParams` but I am getting the same error (405) when trying to use server actions.

My server action takes files as form data and uploads those files to google cloud.

**Comment by arduano** [comment]
@Tommoore96 Would you be able to get a minimal reproduction? Your situation might need to be a separate github issue.

**Comment by AslanArt** [comment]
Same here I'm not using generateStaticParams  but still get 405 errors, I am not able to use my api files somehow! Work perfectly in local

**Comment by hack89** [comment]
Same here. When I removed generateStaticParams, it worked.

**Comment by walid-mos** [comment]
Trying to do internationalization, and in my end the same problem.

I am using generateStaticParams in the root layout, then server actions in all my routes get 405 method not allowed. 

Removing generateStaticParams make it works, but it is not a fix as i need this for locales.

**Comment by tarunsharma18** [comment]
Facing the same issue when using server actions along with getStaticParams. 
When can I expect the fix for the same?

**Comment by amlcodes** [comment]
Bump

Is there anybody from Next on this issue? Happy to look into into it.

**Comment by ctrenks** [comment]
Do we know if this is a bug or can we not use server actions with generateStaticParams pages?

**Comment by NaderTate** [comment]
This error occurs in development only. Try building the app then running it in production, it will work just fine.

**Comment by ctrenks** [comment]
405 error in production on [POST] from Vercel logs

**Comment by plevik** [comment]
Behaviour is still present on `"next": "13.4.13-canary.10"`.

**Comment by Arctomachine** [comment]
> This error occurs in development only. Try building the app then running it in production, it will work just fine.

Error happens in production too, just not printing anything in server console (browser console and network tab still show 405)

**Comment by kfirfitousi** [comment]
Did anyone manage to find a workaround for this?

**Comment by AndrewRPorter** [comment]
I was adding i18n support to my website following [this guide](https://nextjs.org/docs/app/building-your-application/routing/internationalization) and ran into this issue as well. In my case, I was getting failures with server actions when my layout file was in my `app/[lang]` directory.

Splitting out the layout files into two, one at the app route (`app/layout.tsx`) and one in the `app/[lang]` dir (`app/[lang]/layout.tsx`) folder did it for me.

**Comment by roeean** [comment]
Also had the same issue. Removing the generateStaticParams function fixes. Why we can't use both generateStaticParams and server actions?

**Comment by Bartek532** [comment]
Same here.

**Comment by cmoscosoz** [comment]
Same issue here. with generateStaticParams

> I was adding i18n support to my website following [this guide](https://nextjs.org/docs/app/building-your-application/routing/internationalization) and ran into this issue as well. In my case, I was getting failures with server actions when my layout file was in my `app/[lang]` directory.
> 
> Splitting out the layout files into two, one at the app route (`app/layout.tsx`) and one in the `app/[lang]` dir (`app/[lang]/layout.tsx`) folder did it for me.

@AndrewRPorter were you using generateStaticParams? I'm using i18n too. could you please provide an example of how you split your layouts?

**Comment by mohamedzhioua** [comment]
> I was adding i18n support to my website following [this guide](https://nextjs.org/docs/app/building-your-application/routing/internationalization) and ran into this issue as well. In my case, I was getting failures with server actions when my layout file was in my `app/[lang]` directory.
> 
> Splitting out the layout files into two, one at the app route (`app/layout.tsx`) and one in the `app/[lang]` dir (`app/[lang]/layout.tsx`) folder did it for me.

any other way to solve it ???  i have the same issue after adding app/[lang]

**Comment by mohamedzhioua** [comment]
> generateStaticParams

same here i just tried it and it works for me too

**Comment by qnten** [comment]
Didn't find this issue at first because it doesn't include the error message I am getting. In case anyone else gets the same error message, here it is:

```
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at PathnameContextProviderAdapter (/reproduction-app/node_modules/.pnpm/next@13.4.20-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/shared/lib/router/adapters.shared-runtime.js:84:11)
    at Be (/reproduction-app/node_modules/.pnpm/next@13.4.20-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:1:47861)
    at Ze (/reproduction-app/node_modules/.pnpm/next@13.4.20-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:1:48550)
    at div
    at Ye (/reproduction-app/node_modules/.pnpm/next@13.4.20-canary.23_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages.runtime.dev.js:1:55624)
```

**Comment by irg1008** [comment]
We are talking about it in the next-intl repo as well: https://github.com/vercel/next.js/issues/49408#issuecomment-1703337599

I think next.js should look into this if the plan to release server actions as beta or stable soon

**Comment by irg1008** [comment]
OMG 😱 Thank you! Amazing work

**Comment by borispoehland** [comment]
I found 2 workarounds

Either set `export const dynamic = "force-dynamic"` on the page using the server action.

Or, if that clashes with other options (e.g. you set `export const dynamic = "error"` in a previous segment), you can currently bypass the error by turning your page from `mypath/page.tsx` to `mypath/[[...slug]].tsx`. This [optional catch-all segment](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#optional-catch-all-segments) makes "/mypath" still accessible and magically works, by telling Next.js: This page must be dynamic. Inside of the route's `page.tsx,` you can then make sure that only "/mypath" is matched by using notFound:
```
// mypath/[[...slug]].tsx
export default function Page({ params: { slug } }) {
  if (slug?.[0]) { notFound() }
  
  return <form action={myServerAction}> <button type="submit">Works like a charm</button> </form>

}
```
