### ISSUE TITLE
Docs: Unable to access "Building your Application" page from the sidebar

### ISSUE THREAD

**Issue by FrozenHearth** [vercel/next.js#49413]
### What is the improvement or update you wish to see?

As the title says, the "Building your Application" page is inaccessible from the sidebar.

### Is there any context that might help us understand?

This page however, is accessible from the "Installation" page. Please refer to the below video:

https://user-images.githubusercontent.com/27160715/236695547-8c5615b9-e85e-4a7c-bf8e-aa16592be2d1.mov

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application

**Comment by leerob** [comment]
This is fixed, thanks
