### ISSUE TITLE
[NEXT-1131] Cannot navigates between pages when server actions are running

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#49425]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Tue Apr 25 04:07:22 PDT 2023; root:xnu-8796.121.2~8/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.18
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/Fredkiss3/bug-next-server-actions-blocking-navigation

### To Reproduce

Go to the app, try clicking on the button multiple times in succession, then after that try clicking on the link, you won't be able to navigate until all of the requests to the action have finished.

### Describe the Bug

You can see in the video below by yourself, the request has intentionnaly been slowed down to simulate a slow network  :

https://user-images.githubusercontent.com/38298743/236712918-42c53c80-7c33-40af-85bf-f1eeeaddddf5.mov

### Expected Behavior

server actions running should not be blocking the UI.

<sub>[NEXT-1131](https://linear.app/vercel/issue/NEXT-1131/cannot-navigates-between-pages-when-server-actions-are-running)</sub>

**Comment by masterkain** [comment]
are you sue that `other-page` wasn't compiling while you were trying to request it?

**Comment by PegeDev** [comment]
is there any solution for this problem?

**Comment by yasseralsaidi** [comment]
same here!

**Comment by karlhorky** [comment]
Thanks for the fix in #54307 @ztanner and @shuding 🙌 

@Fredkiss3 Seems like it was released in `next@13.4.20-canary.1` - can you confirm and provide proof that this version is working in your app?

**Comment by Fredkiss3** [comment]
I can confirm that the bug is fixed, see the updated example here : https://github.com/Fredkiss3/bug-next-server-actions-blocking-navigation

https://github.com/vercel/next.js/assets/38298743/f246d37b-65d0-4794-b15a-ec7d07388a0b

**Comment by eifo** [comment]
upgrading to v13.4.20-canary.1 has introduced the following bug - when there is a long server action, the first server action re-loops, reruns again and again. Specifically I'm running googleapis library from my server action, calling multiple server actions which altogether might take almost a minute, had to stay in 13.4.20-canary.0.

**Comment by ztanner** [comment]
@eifo are you able to open a separate issue with a minimal reproduction? That'll make it easier for us to triage/follow-up with a fix 🙏
