### ISSUE TITLE
Docs: Environment Variables on this page shows extra headings

### ISSUE THREAD

**Issue by mskri** [vercel/next.js#49434]
### What is the improvement or update you wish to see?

Environment Variables docs page shows extra headings in the "on this page" -section. The section is picking up those extra headings from the code examples in the page.

### Is there any context that might help us understand?

![Screenshot 2023-05-08 at 10 03 48](https://user-images.githubusercontent.com/2499987/236757763-69511966-4eee-41ce-ab64-bcf6a94b5730.png)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/configuring/environment-variables

**Comment by leerob** [comment]
Fixed
