### ISSUE TITLE
[appdir] route handler incorrectly rendered as static when NextRequest

### ISSUE THREAD

**Issue by masterkain** [vercel/next.js#49441]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Tue Sep 13 07:51:46 UTC 2022
    Binaries:
      Node: 20.1.0
      npm: 9.6.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime), SWC transpilation

### To Reproduce

```ts
import { prisma } from '@/lib/db';
import { NextRequest, NextResponse } from 'next/server';

// GET /api/hc
// health check
export async function GET(request: NextRequest) {
  // just do something to check if the db is working
  await prisma.projects.findFirst();

  return new NextResponse('OK');
}
```

### Describe the Bug

route handler is getting statically evaluated

<img width="746" alt="Screen Shot 2023-05-08 at 10 55 29" src="https://user-images.githubusercontent.com/12844/236782229-20db12be-b82c-41ad-bf70-e874b3877226.png">

### Expected Behavior

https://nextjs.org/docs/app/building-your-application/routing/router-handlers#static-route-handlers

the route handler above will try to be statically evaluated, but it has to be dynamic.

using `export const dynamic = 'force-dynamic'` works

```
export const dynamic = 'force-dynamic'

export async function GET(request: Request) {
```

### How are you deploying your application? (if relevant)

docker build in standalone mode

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  output: 'standalone',
  experimental: {
    // logging: 'verbose',
  },
};

module.exports = nextConfig;
```

**Comment by masterkain** [comment]
I'm seeing something else, will open another one

**Comment by sophiebits** [comment]
My understanding is that this is the intended behavior. Components run at build time if possible. For example you could want to fetch blog posts from your database and statically generate the response for each one. As you noted, you can specify force-dynamic or revalidate = 0 to run dynamically.

**Comment by masterkain** [comment]
correct, but my understand was that if request is being specified `GET(request)`, as opposed to not being non-specified `GET()` is should force dynamic, but it isn't.

maybe request is not enough and it should also be used somehow?

**Comment by sophiebits** [comment]
Ah yes, it is only if you access properties that may vary dynamically. For example if you access req.nextUrl.pathname then that will not bail out because it can be known statically. The logic as currently implemented is in this file if you are curious:
https://github.com/vercel/next.js/blob/c93747eb33582bf8988dc7a53d4cf9d643b4a753/packages/next/src/server/future/route-modules/app-route/helpers/proxy-request.ts

**Comment by masterkain** [comment]
gotcha, thanks! (maybe a little hint in the doc for newbies like me, mine is a health check endpoint that up until I started adding the database call I did not realize it was being compiled as static 🥇  )
