### ISSUE TITLE
Metadata and Link component is not working in not-found page

### ISSUE THREAD

**Issue by MasterProvider** [vercel/next.js#49452]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.2-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/distracted-shockley-f0uqen

### To Reproduce

not-found.tsx
```
import NotFound from "../component/NotFound";

export const metadata = {
  title: "NotFound",
};

export default function NotFoundPage() {
  return <NotFound />;
}
```

component/NotFound.tsx

```
"use client";
import Link from "next/link";

export default function NotFound() {
  return (
    <div>
      <div>This page is not found</div>
      <Link href="/">Back to Home</Link>
    </div>
  );
}
```

### Describe the Bug

The Metadata is not working inside in not-found page also the Link component is not firing to the page destination.

### Expected Behavior

I want the Metadata and Link component to work inside in not-found page.

### Which browser are you using? (if relevant)

Chrome 112.0.5615.139

### How are you deploying your application? (if relevant)

next start, Vercel

**Comment by 18888628835** [comment]
I used `<Link href="/"/>` in not-found.tsx, and when I click it, the page jumps to "/", but why UI still be not-found instead of home UI ？

**Comment by MasterProvider** [comment]
I think not-found page is still unstable

**Comment by TheEdoRan** [comment]
Link bug in root not-found is being tracked here: #47862

**Comment by menadeth** [comment]
this works for me
![image](https://user-images.githubusercontent.com/106055637/237010311-615255d6-03ec-48af-a9f5-d004fbf7bb3e.png)
