### ISSUE TITLE
NEXTJS redirects to homepage when accessed with Hyperlink

### ISSUE THREAD

**Issue by lawrenceuchenye** [vercel/next.js#49478]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Issue is that when you try to access a page other than the home page using a hyperlink such http://localhost:3000/about-us it redirect's back to the homepage(http://localhost:3000) when you access the about-us page from the homepage it doesn't redirect only through a hyperlink those this bug occur
```

### Link to the code that reproduces this issue

sorry NDA(NON-DISCLOSURE AGREEMENT)

### To Reproduce

Issue is that when you try to access a page other than the home page using a hyperlink such http://localhost:3000/about-us it redirect's back to the homepage(http://localhost:3000) when you access the about-us page from the homepage it doesn't redirect only through a hyperlink those this bug occur

### Describe the Bug

the page load auto refreshes then redirect to the home page when access through a hyperlink

### Expected Behavior

not to redirect to the home to main the page requested/loaded through the link

**Comment by lawrenceuchenye** [comment]
P.S:not sure about canary had to thick it to publish issue

**Comment by lawrenceuchenye** [comment]
P.S:not sure about canary had to thick it to publish issue

**Comment by timneutkens** [comment]
Unfortunately this issue is not actionable without a reproduction. As per the issue template I'm going to close it. Feel free to open a new issue when you have a reproduction.
