### ISSUE TITLE
[NEXT-1214] TS Plugin Error: "false" is not a valid value for the "dynamicParams" option. ts(71003)

### ISSUE THREAD

**Issue by junaydb** [vercel/next.js#49489]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.4.0
      npm: 8.12.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.2-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue

https://github.com/junaydb/nextjs-ts-bug-repro

### To Reproduce

Export the `dynamicParams` variable from a route. 

### Describe the Bug

TS error: `"false" is not a valid value for the "dynamicParams" option. ts(71003)` when exporting `dynamicParams` from a route. 

Only occurred since I updated to `13.4.1` from `13.2`.

The application builds with no errors, only appears in the text editor (vscode).

### Expected Behavior

No error.

<sub>[NEXT-1214](https://linear.app/vercel/issue/NEXT-1214/ts-plugin-error-false-is-not-a-valid-value-for-the-dynamicparams)</sub>

**Comment by abedshaaban** [comment]
same problem here

**Comment by palakvc** [comment]
Same issue.

**Comment by ChandanJal** [comment]
**Hey there** ! I've a trick for you. Just write this code and It will work fine.
```
const dynamicParams = false;
export { dynamicParams };
```
Past this code inside your **page.ts** | **layout.ts** file 

@palakvc
