### ISSUE TITLE
"Error: Failed to load external module react-apexcharts: ReferenceError: window is not defined" when using `ssr: false`

### ISSUE THREAD

**Issue by drj17** [vercel/next.js#49484]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.4.2-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic), Turbopack (--turbo)

### Link to the code that reproduces this issue

https://github.com/drj17/nextjs-issue-reproduction

### To Reproduce

Run `yarn dev --turbo` and navigate to the application

### Describe the Bug

Application crashes with: `Error: Failed to load external module react-apexcharts: ReferenceError: window is not defined`

### Expected Behavior

Using `{ ssr: false }` should prevent issues with libraries trying to access the window when it is not defined.

<sub>[WEB-1033](https://linear.app/vercel/issue/WEB-1033/error-failed-to-load-external-module-react-apexcharts-referenceerror)</sub>

**Comment by padmaia** [comment]
Should be fixed with this PR: https://github.com/vercel/turbo/pull/4901

**Comment by padmaia** [comment]
You can try out Next.js [13.4.3-canary.1](https://www.npmjs.com/package/next/v/13.4.3-canary.1) or wait until the next stable patch release (usually on Thursdays).
