### ISSUE TITLE
Revalidate anything other than `fetch()`

### ISSUE THREAD

**Issue by pedro757** [vercel/next.js#49496]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.2-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/gifted-microservice-fphtss?file=%2Fpackage.json%3A26%2C25

### To Reproduce

In the codesanbox create a post and try to edit it two times you'll get staled data

### Describe the Bug

Is it possible to revalidate anything other than `fetch()` calls, like a complete path, or prisma queries.

### Expected Behavior

I expect the revalidatePath to do what the name suggests. or being able to revalidate anything other than `fetch()` calls.

For now, I have to use `router.refresh()` to get the correct data in the RSC.

**Comment by K1NXZ** [comment]
I am having the same issue. Prisma queries are not getting updated.

**Comment by timneutkens** [comment]
We're working on it! https://twitter.com/timneutkens/status/1654843969069625345
