### ISSUE TITLE
[NEXT-1199] only the last call to revalidateTag works in DEV mode

### ISSUE THREAD

**Issue by Torsten85** [vercel/next.js#49509]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: N/A
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.2-canary.3
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/divine-lake-8pfqub

### To Reproduce

* Load the homepage at "/". 
* See two fetched timestamps
* Goto "/flush"
* Go back to "/"
* Only the last timestamp gets refetched

### Describe the Bug

the two requests have to separate tags "a", and "b".
"/flush" will revalidate both tags 
only the last call to `revalidateTag` works
This only happens in DEV mode, in production it works as expected.
If you introduce a delay between calls, it works even in DEV mode.

### Expected Behavior

multiple calls to `revalidateTag` should work in DEV mode

<sub>[NEXT-1199](https://linear.app/vercel/issue/NEXT-1199/only-the-last-call-to-revalidatetag-works-in-dev-mode)</sub>

**Comment by martin-coded** [comment]
I have the same issue, that only the last tag is getting revalidated. As workaround I tested to loop over all the tags and make for every single one a new request. This works as expected.

Is it correct, that I could set the same tag for different queries and with the revalidateTag() method, all queries with the same tags are getting revalidated?

```js
// /api/revalidate

export async function POST(req: NextRequest) {
  const data = await req.json();
  for (tag of data.tags) {
    await fetch(`https://dev.app.ch:3001/api/revalidate?tag=${tag}`);
  }

  return NextResponse.json({revalidated: true, now: Date.now()});
}

export async function GET(req: NextRequest) {
  const tag = req.nextUrl.searchParams.get('tag');
  revalidateTag(tag);
  return NextResponse.json({revalidated: true, now: Date.now()});
}

```

**Comment by ztanner** [comment]
Hey @Torsten85! I wanted to check and see if you're still seeing this behavior on the latest version of Next.js? Looks like this might have been fixed recently
