### ISSUE TITLE
NEXT_PUBLIC_* env vars defined in next.config.js no longer showing up in app with v13.4.1-v13.4.3 (was working in v13.4.0)

### ISSUE THREAD

**Issue by ndrakett** [vercel/next.js#49541]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.0
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue

https://github.com/ndrakett/next-env-test

### To Reproduce

* Clone https://github.com/ndrakett/next-env-test
* `npm install`
* `npm run dev`
* Open http://localhost:3000 in browser
* Notice that you only see the value of the `NEXT_PUBLIC_VAR_FROM_ENV` environment variable. The value of env var defined in next.config.js, `NEXT_PUBLIC_VAR_FROM_NEXT_CONFIG`, doesn't show up in the page

* Kill the server
* Edit package.json and set next to version `13.4.0`
* Run `npm install`
* Run `npm run dev`
* Open http://localhost:3000 in browser
* Notice that you see values for both env vars in the page.

See pages/index.js for references to both env vars

### Describe the Bug

It seems environment variable handling changed between NextJS 13.4.0 and 13.4.1.  Our application defines NEXT_PUBLIC_ environment variables in both .env and in next.config.js.  This is working for is in versions of NextJS from 13.0.6 through 13.4.0.  Values for environment variables defined in next.config.js no longer show up in the app when its run when using NextJS 13.4.1.

I didn't see any mention of a change like this in the release notes for 13.4.1.  Is this a regression?

### Expected Behavior

The values of environment variables defined in both .env and ones set in next.config.js (process.env.NEXT_PUBLIC_VAR_NAME="val") should show up in the application when run.

### How are you deploying your application? (if relevant)

npm run dev

**Comment by damusnet** [comment]
Seeing the same thing, but as far as I can tell, this only affects `dev` mode, and env variable are defined again in `prod` build.

**Comment by beinoriusju** [comment]
I'm using `13.4.1` and experienced similar problem yesterday. My application depends on framework respecting loading sequence:  all env files loaded (1), `next.config.js` file loaded(2). This loading sequence allows me to overwrite some of envs inside `next.config.js`. This worked until I've updated to  `13.4.1`. As shown in code snippet below I'm using `dotenv` to load custom envs expecting them to be available for all application. But instead my `process.env.DATABASE_URL` points to production database instead of database defined for testing.

```js
//next.config.js
const dotenv = require('dotenv');

if (process.env.APP_ENV === 'testing') {
  //expecting to overwrite DATABASE_URL and other params
  dotenv.config({ path: '.env.testing', override: true });
}

const nextConfig = {
 //...
}

module.exports = nextConfig;  
```

**Comment by ndrakett** [comment]
Still broken with v13.4.2.

**Comment by semy** [comment]
Same problem.

**Comment by ndrakett** [comment]
Still broken with v13.4.3

**Comment by vltansky** [comment]
same problem

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.4.4-canary.2`, please update and give it a try!

**Comment by Fyvel** [comment]
Hi guys, I'm using v13.4.1 and here's what worked for me

```
// next.config.js

const { SOME_URL } = process.env // for some reason it has no issue reading the variables from here

const nextConfig = {
  env: {
    SOME_URL,
  },
}

module.exports = nextConfig
``` 

hope it helps
