### ISSUE TITLE
[NEXT-1173] use node module inside instrumentation hook cause module not found error

### ISSUE THREAD

**Issue by galaxynova1999** [vercel/next.js#49565]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.2-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/awesome-roman-jkuyps?file=%2Fpages%2Findex.tsx%3A3%2C10-3%2C14

### To Reproduce

run yarn dev in codesandbox

### Describe the Bug

use node module like path (except process, because it has been defined in webpack.resolve.fallback) inside instrumentation.ts file will cause module not found error

also, it can be temporarily solved by adding browser field in package.json
```json

"browser": {
    "path": false
  }
```

![image](https://github.com/vercel/next.js/assets/45778220/689c2940-cfca-4816-9f8d-a300f030aafe)

### Expected Behavior

no error since it's a server startup config, it's highly likely to use nodejs module(s)

### Which browser are you using? (if relevant)

Chrome 100.0.4878.0

### How are you deploying your application? (if relevant)

next start

<sub>[NEXT-1173](https://linear.app/vercel/issue/NEXT-1173/use-node-module-inside-instrumentation-hook-cause-module-not-found)</sub>

**Comment by mickeld23** [comment]
Hi, was trying this feature out and faced the same problem at first. Then read again the documentation and realized that I needed to use import inside the function. The other issue is that you need to check that your are running your code in the correct runtime.
Seen your codesandbox and this should fix it:

instrumentation.ts:
```
export async function register() {
  if (process.env.NEXT_RUNTIME === "nodejs") {
    const { join } = await import("path");
    const { cwd, exit, platform } = await import("process");
    console.log(join("a", "b"));
    console.log(cwd());
  }
}
```

Hope this helps

**Comment by galaxynova1999** [comment]
> Hi, was trying this feature out and faced the same problem at first. Then read again the documentation and realized that I needed to use import inside the function. The other issue is that you need to check that your are running your code in the correct runtime. Seen your codesandbox and this should fix it:
> 
> instrumentation.ts:
> 
> ```
> export async function register() {
>   if (process.env.NEXT_RUNTIME === "nodejs") {
>     const { join } = await import("path");
>     const { cwd, exit, platform } = await import("process");
>     console.log(join("a", "b"));
>     console.log(cwd());
>   }
> }
> ```
> 
> Hope this helps

it works，thanks！
maybe the document should describe it more clear

**Comment by pthieu** [comment]
I'm also hitting a similar issue:

```
Error: Module not found: Can't resolve 'net'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/postgres@3.3.5/node_modules/postgres/src/index.js
./src/app/api/db/index.ts
./src/instrumentation.ts
```

For my case, I'm running my DB migrations on server start, and I import the migration function from my DB lib.

**Comment by 1148177968** [comment]
> 

I have the same problem, This looks like a bug.

**Comment by 1148177968** [comment]
> My problem with this feature is I wanted something to run on server start and not when the first browser window opens. It seems that its not the case even though they are marketing it as start with the server: `If you export a function named register from this file, we will call that function whenever a new Next.js server instance is bootstrapped.`

I have the same problem, This looks like a bug.

**Comment by lmgeorge** [comment]
Also running into this issue when attempting to bootstrap the https://github.com/microsoft/ApplicationInsights-node.js package.

Inlining the logic into the `register` function doesn't work as the Node runtime dependencies are only used by the `applicationinsights` package. Using the workaround with the `browser` config is a non-starter as that would require explicitly declaring `[node package name]: false` for over a dozen packages, when those packages should be resolvable in the `nodejs` runtime without issue.

**Comment by LiorDueto** [comment]
> Also running into this issue when attempting to bootstrap the https://github.com/microsoft/ApplicationInsights-node.js package.
> 
> Inlining the logic into the `register` function doesn't work as the Node runtime dependencies are only used by the `applicationinsights` package. Using the workaround with the `browser` config is a non-starter as that would require explicitly declaring `[node package name]: false` for over a dozen packages, when those packages should be resolvable in the `nodejs` runtime without issue.

We also ran into this with application insights. We worked around it by adding a few checks that at worse case emit a warning.
not perfect, but works well enough for our small application.

it involves 4 files:
- `next.config.mjs` - to save the startup phase and tickle the `/api/boot` endpoint
- `instrumentation.ts` - (optional) configure application insights or telemetry
- `/api/boot/route.ts` - workaround to run startup code on server-side only
- `serverStartup.ts` - the actual server startup code that runs only once

something along these lines:

**next.config.mjs:**

```

function startup() {
	return phase => {
		console.log('Starting: ', phase);

		/** @type {import('next').NextConfig} */
		const nextConfig = {
			experimental: { instrumentationHook: true },
			serverRuntimeConfig: { nextPhase: phase },
		};
		if (['phase-production-server', 'phase-development-server'].includes(phase)) {
			// this is always localhost (we call locally). 
			const localhost = 'http://127.0.0.1:3000';
			// workaround for issue in NextJS - use /api to ensure startup code is server-only, see https://github.com/vercel/next.js/discussions/15341
			const bootRoute = `${localhost}/api/boot`;
			console.info(`- setting up delayed server initialization (5 seconds) at ${bootRoute}...`);
			setTimeout(() => {
				try {
					// Tickle a boot api so we can do one-time initialization on server launch.
					fetch(bootRoute, { cache: 'no-store' });
				} catch (error) {
					// TODO: consider killing the process if startup code fails
					console.error(`server startup failed: ${error}`);
				}
			}, 5000);
		}
		return nextConfig;
	};
}

export default startup();
```

**instrumentation.ts:** (optional)

```
import * as appInsights from 'applicationinsights';
import getConfig from 'next/config';

export async function register() {
	const runtime = process.env.NEXT_RUNTIME;
	const config = getConfig()?.serverRuntimeConfig;

	if (config && ['phase-production-server', 'phase-development-server'].includes(config.nextPhase)) {
		console.info(`registering instrumentation hook. NEXT_RUNTIME: ${runtime}. Startup-phase: ${config.nextPhase}`);
		initApplicationInsights();
	}
}

function initApplicationInsights() {
	// only set up application insights in production mode
	if (process.env.NODE_ENV !== 'production') return;

	try {
		console.log('initializing Application Insights');
		if (!appInsights.setup) {
			console.warn('appInsights is undefined or already initialized.');
			return;
		}
		appInsights.setup('Application Insights Connection String here..');
		// ... extra configuration here
		appInsights.start();
	} catch (err) {
		console.error(`Error initializing Application Insights: ${err}`);
	}
}
```

**/api/boot/route.ts:**
```
import { onServerStartup } from '@/lib/utils/serverStartup';

// disable static caching/pre-rendering during build time
export const dynamic = 'force-dynamic';

export async function GET() {
	try {
		await onServerStartup();
		return new Response('Ok');
	} catch (error) {
		console.error(`Boot Error: ${error}`);
		return new Response(`Boot Error: ${error}`, { status: 500 });
	}
}
```

**serverStartup.ts:**
```
// workaround for NextJS issue - ensure this is called only one time. see https://github.com/vercel/next.js/discussions/15341
let isInitialized = false;

/**
 * Place code here that should be run once at server startup
 */
export async function onServerStartup() {
	// NextJs issue - this may be called multiple times
	if (isInitialized) {
		console.warn('server already initialized');
		return;
	}
	console.info('initializing server...');
        // ...
        // TODO: place your server startup code here..
        // ...
	console.info('server initialization complete.');
	isInitialized = true;
}
```

**Comment by kubop** [comment]
> Also running into this issue when attempting to bootstrap the https://github.com/microsoft/ApplicationInsights-node.js package.
> 
> Inlining the logic into the `register` function doesn't work as the Node runtime dependencies are only used by the `applicationinsights` package. Using the workaround with the `browser` config is a non-starter as that would require explicitly declaring `[node package name]: false` for over a dozen packages, when those packages should be resolvable in the `nodejs` runtime without issue.

Have you managed to fix or implement some workaround for this issue? I'm also trying to include the `applicationinsights` with instrumentation, but without any luck.

**Comment by lmgeorge** [comment]
@kubop I have not. I started to explore the workaround mentioned in the description of the bug, but after adding the tenth Node standard library package, I gave up due to time constraints.

**Comment by jjhuff** [comment]
> Hi, was trying this feature out and faced the same problem at first. Then read again the documentation and realized that I needed to use import inside the function. The other issue is that you need to check that your are running your code in the correct runtime. Seen your codesandbox and this should fix it:
> 
> instrumentation.ts:
> 
> ```
> export async function register() {
>   if (process.env.NEXT_RUNTIME === "nodejs") {
>     const { join } = await import("path");
>     const { cwd, exit, platform } = await import("process");
>     console.log(join("a", "b"));
>     console.log(cwd());
>   }
> }
> ```
> 
> Hope this helps

FWIW, this doesn't seem to work in my 13.4.19, at least with webpack config:
```
./src/instrumentation.ts:16:16
Module not found: Can't resolve 'path'
```

**Comment by ItzDerock** [comment]
Running into this issue with 13.5.4. Originally, I had 
```ts
if (process.env.NEXT_RUNTIME !== "nodejs") return;
// imports and do something
```
but this does not work, instead it must be 
```ts
if (process.env.NEXT_RUNTIME === "nodejs") {
  // imports and do something
}
```

**Comment by igabor94** [comment]
> Ran into this issue with 13.5.4, originally, I had
> 
> ```ts
> if (process.env.NEXT_RUNTIME !== "nodejs") return;
> // imports and do something
> ```
> 
> but apparently this does not work, instead it must be
> 
> ```ts
> if (process.env.NEXT_RUNTIME === "nodejs") {
>   // imports and do something
> }
> ```

It worked for me on 13.4.19. Thank you!

**Comment by justLuiz** [comment]
Another usefull sample with this problem

[nextjs instrumentation with prometheus sample](https://codesandbox.io/p/sandbox/hopeful-tharp-vnz5v2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clofnxuip000a2v6givwhxwya%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clofnxuio00032v6gorj3dcgh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clofnxuio00072v6gmw43p2wo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clofnxuio00092v6g2bjlfcl3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clofnxuio00032v6gorj3dcgh%2522%253A%257B%2522id%2522%253A%2522clofnxuio00032v6gorj3dcgh%2522%252C%2522activeTabId%2522%253A%2522clofq8ccm01912x6gjrgvdek3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Finstrumentation.ts%2522%252C%2522id%2522%253A%2522clofq7zq4014r2x6gkys6gomi%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fconfig%252Fprometheus.ts%2522%252C%2522id%2522%253A%2522clofq8bl4016w2x6gpcf09c3p%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fapi%252Fmetrics%252Froute.ts%2522%252C%2522id%2522%253A%2522clofq8ccm01912x6gjrgvdek3%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clofnxuio00092v6g2bjlfcl3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clofnxuio00082v6gj7fz88zy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fapi%252Fmetrics%2522%257D%255D%252C%2522id%2522%253A%2522clofnxuio00092v6g2bjlfcl3%2522%252C%2522activeTabId%2522%253A%2522clofnxuio00082v6gj7fz88zy%2522%257D%252C%2522clofnxuio00072v6gmw43p2wo%2522%253A%257B%2522id%2522%253A%2522clofnxuio00072v6gmw43p2wo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clofnxuio00042v6gmw9hsn54%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clofnxuio00052v6gzmef3tie%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clofnxuio00062v6gqvfcta12%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%257D%252C%257B%2522id%2522%253A%2522clofo0wt800ue2v6gf5wgvrue%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clofo0x0800o6d9gg5sko3uyn%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clofnxuio00042v6gmw9hsn54%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by landisdesign** [comment]
I'm running into this in dependencies.

If I attempt to `await import('winston')`, it errors on `os` being required by the `@colors/colors` dependency in `winston`.

Not sure if there's a good way to get `os` imported in such a way that it's available to the `winston` import.

**Comment by axpchina** [comment]
for some reason...found out that you must put those imports in:
```
export async function register() {
    if (process.env.NEXT_RUNTIME === "nodejs") {
        console.log("instrumentation register");
        //await import packages...
    }
}
```
not only using await, the trick seems to be "if (process.env.NEXT_RUNTIME === "nodejs") {...}", you have to do things inside this "IF", I don't know why, but it worked well, otherwise didn't.

**Comment by robsoncloud** [comment]
> for some reason...found out that you must put those imports in:
> 
> ```
> export async function register() {
>     if (process.env.NEXT_RUNTIME === "nodejs") {
>         console.log("instrumentation register");
>         //await import packages...
>     }
> }
> ```
> 
> not only using await, the trick seems to be "if (process.env.NEXT_RUNTIME === "nodejs") {...}", you have to do things inside this "IF", I don't know why, but it worked well, otherwise didn't.

I had the same issue and this tip did the trick to solve the issue. Thanks

**Comment by developerasun** [comment]
> for some reason...found out that you must put those imports in:
> 
> ```
> export async function register() {
>     if (process.env.NEXT_RUNTIME === "nodejs") {
>         console.log("instrumentation register");
>         //await import packages...
>     }
> }
> ```
> 
> not only using await, the trick seems to be "if (process.env.NEXT_RUNTIME === "nodejs") {...}", you have to do things inside this "IF", I don't know why, but it worked well, otherwise didn't.

this is true, I tried both with/without full env path like below

```ts
// does not work
const runtime = process.env.NEXT_RUNTIME

if (runtime === "nodejs") {
  const { myModule} = await import("some-module")
}
```

and only below works

```ts
// works
if (process.env.NEXT_RUNTIME=== "nodejs") {
  const { myModule } = await import("some-module")
}
```

seems like nextjs under the hook make a detection pattern only working with fully annotated process.env.

felt like kind of unneeded complicates tho

**Comment by Andrii-Antoniuk** [comment]
Can also confirm that an early return won't work
```
if (process.env.NEXT_RUNTIME !== "nodejs") {
  return;
  }
```

**Comment by ZeeshanAhmadKhalil** [comment]
for me `register()` inside `instrumentation.ts` is not working at all. I am using it like this:

```
import { awsAccessKey, secretAccessKey } from "~config/base-url"
import { getSecret } from "~helper/index"

//! not working
export async function register() {
    console.log("register===>")
}
```

But I am unable to see any consoles. Do consoles don't work here? Or should i do some extra steps to make `register()` working?

**Comment by mxvsh** [comment]
any update on this?

**Comment by mxvsh** [comment]
here is what i did -

i wanted to execute functions in my next.js application on every startup - i tried using `instrumentation.ts` but it was always throwing error about `fs` and other node modules, so what i did is make a GET api route (Next 14) and use `fetch` from `instrumentation.ts`. It worked like charm 🎉 


```js
export function register() {
  fetch('http://localhost:3000/api/init')
}
```

i have hard coded the URL, but you can use `process.env.VERCEL_URL`

**Comment by talonx** [comment]
This is too cumbersome to use for initialization. I ended up moving all the init code into another node service altogether, based on Express, where it's much easier.

**Comment by CyberT33N** [comment]
In my case I used process.cwd() to define the path where I used import(). Make sure that you not do anything like that :)

**Comment by Arctomachine** [comment]
I encountered this error with several libraries.
Contrary to https://github.com/vercel/next.js/issues/49565#issue-1703070720 everything worked normally in dev mode, but builds failed.
So I tried several variations of what is described in https://github.com/vercel/next.js/issues/49565#issuecomment-1902082982 and the best workflow in this file is like this:
1. Avoid writing any logic in instrumentation file
2. Write function with all logic in separate file and export it
3. In register function use `(if process.env.NEXT_RUNTIME === 'nodejs') { }`
4. Inside this condition use `const { someFunction } = await import('fileWithFunction')`
5. And call `someFunction()`

Any other workflow will potentially give error, so avoid writing literally anything else in instrumentation file.

**Comment by CyberT33N** [comment]
I ended up using magic comments to disable webpack for my import:
- `/* webpackIgnore: true */`
`- https://webpack.js.org/api/module-methods/#magic-comments

My problem was, that my imported path was always a dynamic variable and did not find a valid solution to import it. However, I guess there isa way but I did not spend much more time with it and just added webpackIgnore comment. I do not think that there will be crazy negative aspects when you use it for dynamic imports. But of course it is not the cleanest solution. Maybe somebody with more webpack expierence has a more clean solution.

instrumentation.ts
```
export async function register() {
    console.log('[INSTRUMENATION] - process.env.NEXT_RUNTIME: ', process.env.NEXT_RUNTIME)

    if (process.env.NEXT_RUNTIME === 'nodejs') {
        const { bootstrap } = await import('@/src/bootstrap')
        await bootstrap()
    }
}
```

bootstrap.ts
```
async function bootstrap () {
    const modelDetails = await import(/* webpackIgnore: true */ path)
    return modelDetails
}
```
- Also another workaround in other cases is to make this:
  - import(`${path}`)

**Comment by huozhi** [comment]
This is caused by the runtime since when the `instrumentation.js` will be the entry for both Node.js and Edge runtime. Separate the entry based on the runtime would be the proper solution for now. In the future we might introduce the different entry file convention of `instrumentation.js` for different runtime.

One small improvement we patched on latest *canary* release is that we won't generate the edge runtime entry of instrumentation.js when you only have Node.js routes, so you can safely write Node.js code inside of the `instrumentation.js` file there.
