### ISSUE TITLE
Docs: a broken link in Getting Started/React Essentials

### ISSUE THREAD

**Issue by cdtkrk** [vercel/next.js#49567]
## AS-IS:

```markdown
[pre-rendered on the server as HTML](https://nextjs.org/docs/getting-started/(/docs/app/building-your-application/rendering#static-and-dynamic-rendering-on-the-server)) to produce a faster initial page load.
```

## TO-BE:

```markdown
[pre-rendered on the server as HTML](https://nextjs.org/docs/app/building-your-application/rendering#static-and-dynamic-rendering-on-the-server) to produce a faster initial page load.
```

### Is there any context that might help us understand?

There is a broken link in "Good to know" in the "Composing Client and Server Components" section.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/getting-started/react-essentials#composing-client-and-server-components

**Comment by leerob** [comment]
Thank you! Will fix this right now.
