### ISSUE TITLE
API routes cannot execute a function to generate a config export

### ISSUE THREAD

**Issue by NuroDev** [vercel/next.js#49561]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 9.6.0
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/crazy-monad-63bn3i

### To Reproduce

Create a new api directory using the pages directory structure & create a basic function that returns an object of the same structure expected by the `config` object. Then export a new constant called `config` that calls that function.

## Example

```ts
import { NextResponse } from 'next/server';

const buildConfig = () => ({
	runtime: 'edge',
});

// This breaks it & throws a "Please use `runtime: "edge"` instead" error.
export const config = buildConfig();

export default function handler() {
	return NextResponse.json({
		success: true,
	});
}
```

### Describe the Bug

It seems that, for whatever reason, Next.js is not running this top-level function call to retrieve config object & instead requires you export a fixed / static object.

This is of course a very much edge case bug & for context the only reason I discovered this & it is needed is I have been working on my `next-define` package to make building pages, routes, etc in Next.js easier & better typed without need for the TypeScript plugin.
Currently this issue means that the `config` object returned by using the `defineApi` function is not valid / doesn't work.

### Expected Behavior

The object return by calling a function should perform / be handled the exact same way as by defining a static object.

**Comment by DuCanhGH** [comment]
You just can't export a `config` object from pages, routes and layouts anymore, see #48774.

**Comment by NuroDev** [comment]
Ah okay, didn't know that was deprecated / removed.

However, doing some testing this also applies to the new app directory as well it seems.

```ts
// src/app/api/hello/route.ts
import { NextResponse } from 'next/server';

export function GET(): NextResponse {
	return NextResponse.json({
		success: true,
	});
}

const buildRuntime = () => 'edge';

export const runtime = buildRuntime();
```

This will work in run fine, at least locally from my testing, but when you go to build:

```bash
src/app/api/hello/route.ts
Type error: Route "src/app/api/hello/route.ts" does not match the required types of a Next.js Route.
  Invalid configuration "runtime":
    Expected ""edge" | "nodejs" | "experimental-edge" | undefined", got "string".
```

**Comment by DuCanhGH** [comment]
@NuroDev yeah that's the new Typescript plugin complaining. You have to make `buildRuntime()` return a constant string (`"edge"`, `"nodejs"`, `"experimental-edge"`, `undefined`), rather than type `string`.

**Comment by NuroDev** [comment]
Ah yeah that makes sense. That does seem to fix it.

Though oddly Next.js refuses to even acknowledge that `runtime` exists when using `next-define`'s `defineRoute` helper 🤔 , but I guess this is a bit out of scope of this current issue.

Closing for now.

**Comment by timneutkens** [comment]
Keep in mind that these config values need to be statically analyzed, so using functions is not supported.
