### ISSUE TITLE
Fetch does not revalidate as expected

### ISSUE THREAD

**Issue by ecam900** [vercel/next.js#49571]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: 7.30.0
    Relevant packages:
      next: 13.4.2-canary.4
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/ecam900/minimal_demo

### To Reproduce

1. Go to [the demo website.](https://minimal-demo.vercel.app/)
2. Navigate between pages by clicking the links.

### Describe the Bug

The [fetch ](https://github.com/ecam900/minimal_demo/blob/main/src/fetchers/getCatFact.ts) does revalidate the result of the fetch every 1 second with the stale-while-revalidate pattern. Even if you wait 5 seconds between clicks, and click ten times in a row it does not revalidate the result.

### Expected Behavior

I expected the fetch to be refreshed with new data without having to hard refresh the page.

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

vercel

**Comment by CarlosBalladares** [comment]
I have the same issue on `13.4.1`

**Comment by ecam900** [comment]
> Potentially related to #49638. Can you verify it still happens on `next@canary`?

I will verify today and get back to you.

**Comment by gavinbaradic** [comment]
Also getting a similar error. Getting errors with `export const revalidate = 60` on `next@canary`

```
- event compiled client and server successfully in 2.2s (1213 modules)
DOMException [AbortError]: The operation was aborted.
    at Object.fetch (/Users/gavin/portfolio/node_modules/next/dist/compiled/undici/index.js:1:26669) {
  [Symbol(kName)]: 'AbortError'
}
```

**Comment by ijjk** [comment]
This appears to be behaving as expected currently as the client router is caching the requests client-side and the fetch revalidations are working correctly when refreshing the page. 

Currently if you always want fresh data on navigation you have to do:
`import {useRouter} from 'next/navigation`
`useRouter().refresh()`
