### ISSUE TITLE
Getting the current page being rendered in layout.tsx isn't possible

### ISSUE THREAD

**Issue by evowizz** [vercel/next.js#49585]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 19.8.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.2-canary.4
      eslint-config-next: 13.4.2-canary.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/misty-sea-5n0u9s?file=%2Fapp%2Flayout.tsx%3A23%2C21

### To Reproduce

This is reproducible in any project using the App Router.

### Describe the Bug

Using the Pages router, it was possible to get the current path thanks to `getInitialProps` from the `_document.tsx` file. However, this feature was not ported to the App Router, making it impossible to know which page is being "generated" from within the root `layout.tsx` file. which in the end can prevent page-based themes applied at build-time (for example) when using App Router versus the Page router.

### Expected Behavior

Ability to get data about pages being "generated" from the root `layout.tsx`.

**Comment by timneutkens** [comment]
This is working as intended. Below the common layout it does not rerender so reading the pathname would not update when navigating. You can read more about that here: https://nextjs.org/docs/app/building-your-application/routing#partial-rendering

You can `usePathname()` in a client component to read the full pathname.

**Comment by evowizz** [comment]
Thanks @timneutkens for your reply! As you mentioned, "below the common layout, it does not rerender, so reading the pathname would not update when navigating." 

With the Page Router, getting the path from `getInitialProps` would also cause the pathname to not be updated when navigating. I created a demo to demonstrate this behavior [on codesandbox.io](https://codesandbox.io/p/sandbox/romantic-sanne-j2shez?file=%2Fpages%2F_document.tsx%3A9%2C1-10%2C1).

If you open the URL to the home page, you will see the following in logs:
```
{
  err: undefined,
  req: undefined,
  res: undefined,
  pathname: '/',
  query: {},
  asPath: '/',
  locale: undefined,
  locales: undefined,
  defaultLocale: undefined,
  AppTree: [Function: AppTree],
  defaultGetInitialProps: [AsyncFunction: defaultGetInitialProps],
  renderPage: [AsyncFunction: renderPage]
}
```
However, after clicking on "Go to Blog", the details about the /blog path won't be logged. 

The current behavior with the Page Router seems to match the behavior you described if it ever was implemented with the App router. 

Could this be reconsidered, please?
