### ISSUE TITLE
Docs: Web Accessibility : Emphasize the good-to-know notes

### ISSUE THREAD

**Issue by MenaiAla** [vercel/next.js#49586]
### What is the improvement or update you wish to see?

I have a low vision and I struggle to notice the good-to-know content.

### Is there any context that might help us understand?

I would recommend changing the background color of the layout.

I would recommend changing the color of the left border of the layout.

**Comment by leerob** [comment]
Thank you for this feedback, we are planning to update the colors on the diagrams to have them be more accessible. Stay tuned for that change! 🙏
