### ISSUE TITLE
Docs: Version history for redirects

### ISSUE THREAD

**Issue by Nanosync** [vercel/next.js#49583]
### What is the improvement or update you wish to see?

In https://nextjs.org/docs/pages/api-reference/next-config-js/redirects, there is no version history for when the key `missing` was added.

### Is there any context that might help us understand?

For rewrites, `missing` was added in `v13.3.0`. Was this already available for redirects?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/next-config-js/redirects

**Comment by leerob** [comment]
Thank you! I will add this.
