### ISSUE TITLE
Next/Link in global not-found page not working

### ISSUE THREAD

**Issue by HamAndRock** [vercel/next.js#49599]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.2-canary.4
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/festive-haze-sxcwdh

### To Reproduce

Create a global not-found page in app directory and add Next/Link there to navigate from it to non 404 page. When clicking on the Next/Link component url does get updated but the content stays the same, so you still see 404 page even though the url is showing you should be on the new page.

### Describe the Bug

Not able to use Next/Link in global not-found page

### Expected Behavior

I would be able to navigate to different pages without an issue from global not found page.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Self, Codebox

**Comment by kubop** [comment]
I came across the same issue in 13.4.2. I'd like to add, that clicking on the 
```JSX
<Link href="/some-path-that-doesnt-exist">Click</Link>
```
doesn't render the not-found page, although it updates the URL in the browser.

### Link to the code that reproduces this issue
https://codesandbox.io/p/github/kubop/nextjs-13.4.1-notfound/

**Comment by TheEdoRan** [comment]
Duplicate of #47862

**Comment by HamAndRock** [comment]
Sorry, missed this tried looking it though :/ Closing as a dulicate https://github.com/vercel/next.js/issues/47862
