### ISSUE TITLE
Docs: output standalone and next start

### ISSUE THREAD

**Issue by petertflem** [vercel/next.js#49594]
### What is the improvement or update you wish to see?

Hello! 👋 

I have had some problems figuring this out using the docs.

After upgrading Next.js from version 12 to version 13, I get a new warning when running the app.
```
"next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
```
The warning itself is clear on what to do, but I find no info on what changed here between version 12 and 13. The warning comes after first building, then starting the app:
```
next build
next start -p 3001
```

This used to print no warnings. The `next.config.js` file has `output: 'standalone'` configured, because in staging and production we run the app in a docker container. The setup for that is based on the [with docker](https://nextjs.org/docs/app/building-your-application/deploying#docker-image) example, which sets `output` to `standalone`.

To debug a built version of the app locally, I run `next build` + `next start -p 3001`, which I no longer can do without getting the warning. I don't know what is going on in Next under the hood here, and I have these questions, which may be useful to add to the docs, if they're not there. They do overlap a bit, though. Might be only me though, or maybe it is in there somewhere.

1 - What changed here between version 12 and 13?

2 - Is this a correct summary?
The `next build` command with the `output: 'standalone'` config will automatically only include the needed files, except `public` and `.next/static`. Without using the standalone option, I would have to manually copy all the files needed by the app.

3 - The [docs state](https://nextjs.org/docs/pages/api-reference/next-config-js/output#automatically-copying-traced-files):
>Additionally, a minimal server.js file is also output which can be used instead of next start.

And [they also state](https://nextjs.org/docs/app/api-reference/next-cli#production):
> Note: next start cannot be used with output: 'standalone' or output: 'export'.

The first quote make it seems like I could use `next start` with the `output: "standalone"` config, but the second quote makes it clear that doesn't work.

I'm curious as to why it doesn't work? The app only logs a warning when I try, and runs fine. Does it fall back on some other way to run?

### Is there any context that might help us understand?

I kind of added everything to the first text area :)

**Comment by DuCanhGH** [comment]
> 1 - What changed here between version 12 and 13?
Nothing changed but a warning was added so that users are aware.

> 2 - Is this a correct summary?
The next build command with the output: 'standalone' config will automatically only include the needed files, except public and .next/static.

Yes. I don't understand what the last sentence means, however.

> 3 - ...

This note (`Note: next start cannot be used with output: 'standalone' or output: 'export'.`) probably means that `next start` isn't meant to start the server for `output: 'standalone' | 'export'` as it doesn't make use of these output modes' files. You can still use it as it will just use what a normal `next build` would output. One thing you can do is using an environment variable:

Your `Dockerfile` (or a similar thing that you use):
```Dockerfile
ENV BUILD_STANDALONE true

RUN npm run build
```

Your `next.config.js`:
```js
modules.export = {
    output: process.env.BUILD_STANDALONE === "true" ? "standalone" : undefined,
    // ...rest of your config
}
```

Hope this helps!

**Comment by petertflem** [comment]
I see, thanks! 😀

2 - The sentence just meant that I would have to parse the `.nft.json` files myself, to copy the needed files.
3 - "probably means that next start isn't meant to" -> My apologies, still a little confused by the wording, do you guess a little, or do you know for sure? 🙏 Thanks for the helpful code examples!

**Comment by DuCanhGH** [comment]
@petertflem 
No, you don't need to go through the `.nft.json` files, they are for tracing dependencies and stuff.
> 3 - "probably means that next start isn't meant to" -> My apologies, still a little confu...

Let's just say that `output: "standalone"` and `output: "export"` have their own ways to serve, but `next start` still works. It just doesn't take advantage of those modes. This warning just makes sure that you do take advantage of them.

**Comment by DuCanhGH** [comment]
@petertflem wait, isn't it about the website? 

Locally you should just use `next start` unless you are specifically debugging `output: "standalone" | "output"`. 

For deploying you should use `output: "standalone"` if you want to deploy with docker and similar stuff (Vercel, Netlify and some others don't need this though), or `output: "export"` if you want to statically export the whole app (not just some pages). Just know that these output modes' benefits really do matter.

Note that I mean by "have their own ways to serve" is that they serve the website differently to `next start`...

**Comment by petertflem** [comment]
@DuCanhGH Sorry, that was unclear of me 🙏 Any functionality on the website itself would not be affected, like what happens when button X is clicked. That is what I meant, just a bit paranoid about breaking production. I understand that it will affect how the files for the website is served.

We use output: "standalone" for docker, and run it with `node server.js`. Locally, if I wanted to test an app that is build (e.g. for testing if getStaticProps works), I'd use `next start`. For dev it is just `next dev`.

**Comment by DuCanhGH** [comment]
@petertflem have a great day :)
