### ISSUE TITLE
Docs: 404 link in official docs

### ISSUE THREAD

**Issue by romainbriand** [vercel/next.js#49590]
### What is the improvement or update you wish to see?

On the dynamic routes introduction paragraph, the "prerendered" word links to https://nextjs.org/docs/pages/building-your-application/routing/pages/building-your-application/data-fetching/get-static-paths instead of https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-paths

### Is there any context that might help us understand?

Wrong link

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes

**Comment by romainbriand** [comment]
I've thought about submitting a PR but don't know/haven't found if official docs are open to community editions 🤷

**Comment by leerob** [comment]
Thank you! Fixing this now.
