### ISSUE TITLE
[NEXT-1171] Link to anchor doesn't respect scroll-padding properties in App Router

### ISSUE THREAD

**Issue by rosszurowski** [vercel/next.js#49612]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.2-canary.4
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/crimson-breeze-8r3ccl

### To Reproduce

1. Open the [minimal reproduction app](https://codesandbox.io/p/sandbox/crimson-breeze-8r3ccl)
2. Press the link to **Section A** or **Section B**
3. Notice that the header is touching the top of the viewport, despite `scroll-padding-top` being set in `globals.css`
4. Refresh the page, and notice how the scroll position correctly updates to account for the `scroll-padding-top` when the navigation is done outside of Next.js

### Describe the Bug

When linking to an anchor on a page using the `Link` component, any `scroll-padding` CSS property values aren't respected.

If I have a global scroll-padding value of `2rem` set, when navigating via a native browser link to eg. `/about#contact`, the page will navigate to the element with an ID of `contact` with `2rem` of space above it. However, when using Next.js's `Link` component, the element touches the top of the viewport.

### Expected Behavior

I'd expect `Link` to behave like a native `a` tag and respect any `scroll-padding` values set in CSS.

### Which browser are you using? (if relevant)

Firefox 112.0.2

<sub>[NEXT-1171](https://linear.app/vercel/issue/NEXT-1171/link-to-anchor-doesnt-respect-scroll-padding-properties-in-app-router)</sub>

**Comment by SamBallantyne** [comment]
Has anyone figured out a good workaround for this?

**Comment by OhYello** [comment]
Having the same issue with this too. Adding scroll margin doesn't affect the anchor link jumps. Any updates?
