### ISSUE TITLE
[NEXT-1169] useOptimistic revert is happening after serverAction but before revalidatePath render 

### ISSUE THREAD

**Issue by infiniteluke** [vercel/next.js#49619]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 17.3.1
      npm: 8.3.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.4.2-canary.4
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

[https://github.com/infiniteluke/checkboxes/blob/main/src/app/\_components/Checkbox.tsx#L27](https://github.com/infiniteluke/checkboxes/blob/main/src/app/\_components/Checkbox.tsx#L27)

### To Reproduce

1. Visit [https://checkboxes-chi.vercel.app/](https://checkboxes-chi.vercel.app/)
2. Check or uncheck a checkbox

### Describe the Bug

* Optimistic value is showed during server action 👍
* The passthrough value (?) is rendered before the revalidated data is rendered causing a flash of the previous value 👎

I believe the useOptimistic revert is happening after the [serverAction](https://github.com/infiniteluke/checkboxes/blob/main/src/app/\_actions/index.ts#L30-L32) is finished but before the revalidated data is rendered

### Expected Behavior

Optimistic value is rendered until `revalidatePath` is finished so there is no flash of the old passthrough state

### Which browser are you using? (if relevant)

*No response*

### How are you deploying your application? (if relevant)

Vercel

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-1169](https://linear.app/vercel/issue/NEXT-1169/useoptimistic-revert-is-happening-after-serveraction-but-before)</sub>

**Comment by r-ohan** [comment]
Experiencing the same problem - let me know if you figure out a workaround.

**Comment by switz** [comment]
Also seeing the same issue here, getting a flash of stale content because the optimistic data is removed before the fresh data has come in.

**Comment by vimtor** [comment]
Same issue here

**Comment by plrs9816** [comment]
Still not resolved.
Not really a workaroud, but when React strictmode is not enabled (also in prod), it works fine.

**Comment by magoz** [comment]
I'm having the same issue.
 
In my case, I'm using `useOptimistic` in combination with `startTransition`, but having the same problem.

<img width="611" alt="Screenshot 2023-08-13 at 09 39 50" src="https://github.com/vercel/next.js/assets/9190753/68e23e6d-c62d-4a25-bbd0-9c3a582c944b">

**Comment by abduraufsherkulov** [comment]
Anybody figure out the solution?

**Comment by vimtor** [comment]
> Anybody figured out the solution?

@abduraufsherkulov I have been using a custom hook to achieve the same:

```tsx
function useOptimistic<T>(passthrough: T) {
  const [value, setValue] = useState<T>(passthrough);

  useEffect(() => {
    setValue(passthrough);
  }, [passthrough]);

  return [value, setValue] as const;
}
```

I'm not sure if this covers all use cases, but it has been working great for me.

**Comment by JovanJevtic** [comment]
Any updates?

**Comment by jide** [comment]
I have the same issue, and it is very hard to find info on that subject.

I adapted @vimtor code to take an additional reducer arg :
```js
function useOptimistic(passthrough, reducer) {
  const [value, setValue] = useState(passthrough);

  useEffect(() => {
    setValue(passthrough);
  }, [passthrough]);

  return [value, (payload) => setValue(reducer(passthrough, payload))];
}
```

**Comment by kpotter-m2** [comment]
> I have the same issue, and it is very hard to find info on that subject.
> 
> I adapted @vimtor code to take an additional reducer arg :
> 
> ```js
> function useOptimistic(passthrough, reducer) {
>   const [value, setValue] = useState(passthrough);
> 
>   useEffect(() => {
>     setValue(passthrough);
>   }, [passthrough]);
> 
>   return [value, (payload) => setValue(reducer(passthrough, payload))];
> }
> ```

to add to this, here's a type safe version:
```ts
function useOptimistic<T, P>(passthrough: T, reducer: (state: T, payload: P) => T): [T, (payload: P) => void] {
    const [value, setValue] = useState(passthrough);

    useEffect(() => {
        setValue(passthrough);
    }, [passthrough]);

    return [value, (payload) => setValue(reducer(passthrough, payload))];
}
```

**Comment by vimtor** [comment]
At the risk of being a bit pedantic, if you want to add the version with the reducer, you should pass the reducer function through `useCallback`. If you do that, you would also want to [store the reducer callback in a ref](https://epicreact.dev/the-latest-ref-pattern-in-react/).

```ts
import { useCallback, useEffect, useRef, useState, useLayoutEffect } from "react";

function useOptimistic<T, P>(passthrough: T, reducer: (state: T, payload: P) => T) {
  const [value, setValue] = useState(passthrough);

  useEffect(() => {
    setValue(passthrough);
  }, [passthrough]);

  const reducerRef = useRef(reducer);
  useLayoutEffect(() => {
    reducerRef.current = reducer;
  }, []);

  const dispatch = useCallback((payload: P) => {
    setValue(reducerRef.current(passthrough, payload));
  }, [passthrough]);

  return [value, dispatch] as const;
}
```

**Comment by nizioleque** [comment]
I am having the same issue and I also cannot find any information on this subject. I am using `useOptimistic` in a switch's `onChange` handler to show the updated value:
```{tsx}
"use client";

import { togglePositionActive } from "@/api/position";
import { Switch } from "@mui/material";
import { useOptimistic } from "react";

function ActiveSwitch({ isActive }: ActiveSwitchProps) {
  const [optimisticIsActive, setOptimisticIsActive] = useOptimistic(
    isActive,
    (_, newValue: boolean) => newValue,
  );

  const updateIsActive = async (newValue: boolean) => {
    setOptimisticIsActive(newValue);
    await togglePositionActive(); // this is a server action which calls `revalidateTag`
  };

  return (
    <Switch
      checked={optimisticIsActive}
      onChange={(_, checked) => updateIsActive(checked)}
    />
  );
}
```

I am also getting this warning which I couldn't find mentioned absolutely anywhere: 
```
Warning: An optimistic state update occurred outside a transition or action. To fix, move the update to an action, or wrap with startTransition.
```

Is anyone else also seeing this issue? Did you find a solution? I also tried using it together with `useTransition` but with no luck.

**Comment by layerzzzio** [comment]
@nizioleque 

If this is your optimistic update function:

```
  const handleLike = async (
    likeType: LikeType,
    optimisticState: boolean | null,
  ) => {
    if (user == null) {
      router.push("/login");
    } else if (
      optimisticState == null ||
      (optimisticState == true && likeType != LikeType.Like) ||
      (optimisticState == false && likeType != LikeType.Dislike)
    ) {
      const isLike = likeType == LikeType.Like;
      setOptimisticLike(isLike);
      await optimisticLikeReaction(aiPictureName, isLike, fullPath);
    }
  };
```

Then wrap that in a startTransition, coming from  const [_, startTransition] = useTransition() defined in your component, as such:

```
const ActionButton: React.FC<ActionButtonProps> = ({
  isSelected,
  handleLike,
  text,
  icon,
}) => {
  return (
    // <form action={handleLike} className="w-full">
    <Button
      variant={text == "Dislike" ? "destructive" : "positive"}
      size="lg"
      className={`w-full border-2 ${isSelected && text == "Dislike" ? "border-red-400" : isSelected && text == "Like" ? "border-green-400" : !isSelected && text == "Dislike" ? "border-destructive/90 bg-destructive/90" : !isSelected && text == "Like" ? "border-green-900/90 bg-green-900/90" : ""}`}
      onClick={(_) => startTransition(() => handleLike())}
    >
      {icon} {text}
    </Button>
    // </form>
  );
};
```

**Comment by agomesd** [comment]
I think  this is the one, you need to wrap the call to the update optimisitic state with startTransition. 

```
"use client";

import { togglePositionActive } from "@/api/position";
import { Switch } from "@mui/material";
import { useOptimistic,  startTransition } from "react";

function ActiveSwitch({ isActive }: ActiveSwitchProps) {
  const [optimisticIsActive, setOptimisticIsActive] = useOptimistic(
    isActive,
    (_, newValue: boolean) => newValue,
  );

  const updateIsActive = async (newValue: boolean) => {
    startTransition(() => {
        setOptimisticIsActive(newValue);
     }
     
    await togglePositionActive(); // this is a server action which calls `revalidateTag`
  };

  return (
    <Switch
      checked={optimisticIsActive}
      onChange={(_, checked) => updateIsActive(checked)}
    />
  );
}
```

**Comment by schimi-dev** [comment]
This could be related: https://github.com/facebook/react/issues/28574

**Comment by infiniteluke** [comment]
I'm going to close this as it's specific to react, not next.js. Track https://github.com/facebook/react/issues/28574 if you're interested.
