### ISSUE TITLE
getStaticProps in page component builds in local but not on vercel

### ISSUE THREAD

**Issue by HoracioGutierrez** [vercel/next.js#49635]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 20.0.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.2-canary.4
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/HoracioGutierrez/test-next-new/commit/31677056133504201e044071d7750125885e973a

### To Reproduce

I only tried to deploy it localy with the appropiate env variables : 

DATABASE_URL
UPLOADTHING_SECRET
UPLOADTHING_APP_ID

### Describe the Bug

So it's pretty straight forward like the title says, I tried to deploy an app with the new nextjs and it works just fine , it even gives this output : 

![image](https://github.com/vercel/next.js/assets/11802413/e0da274c-1df5-4d34-befd-7223478a1c9b)

but the i tried to deploy it on vercel and this happens : 

![image](https://github.com/vercel/next.js/assets/11802413/b4a87939-b092-4e6e-a48b-d973d36cdcc6)

### Expected Behavior

The deploy on vercel as far as I'm concerned should be the exact same as it's been going so far up to the point I tried to implement getStaticProps

### Which browser are you using? (if relevant)

Versión 112.0.5615.140 (Build oficial) (64 bits)

### How are you deploying your application? (if relevant)

git push, auto conected to vercel

**Comment by timneutkens** [comment]
`getStaticProps`, `getServerSideProps` and `getStaticPaths` are not supported in App Router as per the upgrade guide. I'm not sure why you don't see it during `next build`, when I run the build in codesandbox I'm seeing exactly the same errors: https://codesandbox.io/p/github/HoracioGutierrez/test-next-new/csb-ddodzi/draft/busy-turing 

<img width="1049" alt="CleanShot 2023-05-11 at 15 28 59@2x" src="https://github.com/vercel/next.js/assets/6324199/c0c25307-dfbe-43f8-94e2-3e14657d47b0">
