### ISSUE TITLE
Metadata behaves unexpectedly when the serverActions option is true.

### ISSUE THREAD

**Issue by woo3145** [vercel/next.js#49650]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.6.0
      npm: 8.15.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/woo3145/bug-next-server-actions-metadata-not-working

### To Reproduce

Metadata behaves unexpectedly when the serverActions option is true.

### Describe the Bug

https://github.com/vercel/next.js/assets/100907484/9a623361-a3b4-4745-bba0-aa2b367ba892

### Expected Behavior

Metadata should work properly.

### Which browser are you using? (if relevant)

chrome 113.0.5672.92(arm64)

**Comment by JesseKoldewijn** [comment]
Hey man!
To start of, you're not testing against the latest canary release. It seems like the issue you're describing & showing here was either already fixed on canary or something related to it. 

See my repo down below for a known working example with serverActions toggled on + metaData correctly working.

**Comment by shuding** [comment]
Closing as it should be fixed in the latest canary.

**Comment by JesseKoldewijn** [comment]
> > Hey man! To start of, you're not testing against the latest canary release. It seems like the issue you're describing & showing here was either already fixed on canary or something related to it.
> > 
> > See my repo down below for a known working example with serverActions toggled on + metaData correctly working.
> 
> Thank you for your comments! But after canary update the same problem occurs. The same problem occurs when I create multiple routers in your starter. (It seems to me that it stops after the first correct operation)

It seems like there's something going on on your end locally in that case because I've tested my repo which runs canary on both served from both linux+windows dev server and deployed on vercel without issues.

**Comment by woo3145** [comment]
> > > Hey man! To start of, you're not testing against the latest canary release. It seems like the issue you're describing & showing here was either already fixed on canary or something related to it.
> > > See my repo down below for a known working example with serverActions toggled on + metaData correctly working.
> > 
> > 
> > Thank you for your comments! But after canary update the same problem occurs. The same problem occurs when I create multiple routers in your starter. (It seems to me that it stops after the first correct operation)
> 
> It seems like there's something going on on your end locally in that case because I've tested my repo which runs canary on both served from both linux+windows dev server and deployed on vercel without issues.

thank you I tried the same issue by running it on Windows, but the result was the same.
Metadata is applied only the first time the router is run and is not applied.
So I created a new problem.
https://github.com/vercel/next.js/issues/49679#issue-1706442173
