### ISSUE TITLE
Metadata does not work after one page move when the serverActions option is true. 

### ISSUE THREAD

**Issue by woo3145** [vercel/next.js#49679]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.6.0
      npm: 8.15.0
      Yarn: N/A
      pnpm: 8.5.0
    Relevant packages:
      next: 13.4.2-canary.5
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/woo3145/bug-next-server-actions-metadata-not-working

### To Reproduce

https://github.com/vercel/next.js/assets/100907484/8b9bb7a6-7b25-4af7-a32c-e96dfc28759f

### Describe the Bug

same as title

### Expected Behavior

Metadata should work properly.

### Which browser are you using? (if relevant)

chrome 113.0.5672.92(arm64)

**Comment by JesseKoldewijn** [comment]
I ended up being able to reproduce this issue on the latest canary release funny enough. Not sure which release was the last where this worked as expected but it seems like sort of a related issue to the next-i18n issue where softroutes break curtain flows like the metadata and the i18n instance.

**Comment by woo3145** [comment]
> I ended up being able to reproduce this issue on the latest canary release funny enough. Not sure which release was the last where this worked as expected but it seems like sort of a related issue to the [next-i18n](https://linear.app/vercel/issue/NEXT-i18n) issue where softroutes break curtain flows like the metadata and the i18n instance.
> 
> i18n issue: #49655 Current behavior: i18n instance gets killed on softroutes.
> 
> Metadata issue: data isn't consistently read on softroutes but do get updated on hard routes and refreshes.

Thanks I tested the hard router based on your comments. Hard routers seem to have the same problem. Updated my github and vercel distros.
