### ISSUE TITLE
i18n breaks dynamic pages/routes in Vercel

### ISSUE THREAD

**Issue by Ayterx** [vercel/next.js#49686]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Internationalization (i18n), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/Ayterx/api-route-vercel-bug
https://api-route-vercel-bug.vercel.app/api2

### To Reproduce

1- add i18n in next.config.js
```
  i18n: {
    defaultLocale: "en",
    locales: ["en", "ar"],
  },
```
2- create route handler inside app dir (make sure its not inside api folder)
3- deploy to vercel

### Describe the Bug

**- This won't happen in localhost**
**- Creating a route handler inside api folder will work fine**
**- Any route handler not inside api folder will result 404 page**

removing i18n from next.config.js will fix this

### Expected Behavior

.

### How are you deploying your application? (if relevant)

Vercel

**Comment by Ayterx** [comment]
not sure if this issue should be in vercel/vercel repo or here

**Comment by izoukhai** [comment]
Same thing has been posted in Vercel's repo: https://github.com/vercel/vercel/issues/9827

But as usual, we have 0 answers... 
**Note that deploying the project by yourself on a server works.**

**Comment by izoukhai** [comment]
@Ayterx did you find a workaround ?

**Comment by Ayterx** [comment]
@izoukhai I believe there isn't, I found this happens only in Vercel.

**Comment by Ayterx** [comment]
Update: The problem happens with dynamic pages/routes, Static pages work fine, I've updated the example with static and dynamic pages

also found this: https://github.com/vercel/next.js/pull/46362
cc @shuding

**Comment by leerob** [comment]
Good news, this is now fixed on the Vercel side! It will be included in `vercel@31.1.0`.

https://github.com/vercel/vercel/pull/10243

**Comment by aralroca** [comment]
Very good news! thanks  @leerob

**Comment by Ayterx** [comment]
Thanks!!!
