### ISSUE TITLE
Parsing error: Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by vsakaria-mgnl** [vercel/next.js#49706]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.0
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

ESLint (eslint-config-next)

### Link to the code that reproduces this issue

https://github.com/vsakaria-mgnl/insurance-demo-saas

### To Reproduce

1. Run npx create-next-app And then look into the project folders structure. Any files that are created have the following error message in vscode

Parsing error: Cannot find module 'next/babel'
Require stack:
- /Users/vishal/Documents/code/insurance-demo-saas/insurance-demo-nextjs/node_modules/next/dist/compiled/babel/bundle.js
- /Users/vishal/Documents/code/insurance-demo-saas/insurance-demo-nextjs/node_modules/next/dist/compiled/babel/eslint-parser.js
- /Users/vishal/Documents/code/insurance-demo-saas/insurance-demo-nextjs/node_modules/eslint-config-next/parser.js
- /Users/vishal/Documents/code/insurance-demo-saas/insurance-demo-nextjs/node_modules/@eslint/eslintrc/dist/eslintrc.cjseslint

2. The next problem when I try to create a react component I get this in the terminal

Module parse failed: Unexpected token (2:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

### Describe the Bug

There seems to be some error in the configuration of the transpiling and ES lint.

The first error above Can be tolerated. But now when I create a react component it's giving me an error point 2 above

### Expected Behavior

All code complies and doesn't give unnecessary errors 

### Which browser are you using? (if relevant)

Chrome is up to date Version 113.0.5672.92

**Comment by ThinkerDreamer** [comment]
I have exactly this issue now. How was this resolved? @vsakaria-mgnl ?

**Comment by haamedshadow** [comment]
i have same issue when i add rules into my .eslintrc.json show same error and i have 2 folders one for frontend and one for backend and when i open just frontend folder in vscode dosn't show any error but when open both folders in vscode show error , did anybody knows how to open both folders without any error? thnks

**Comment by dzcpy** [comment]
@ThinkerDreamer What about using Next in a monorepo, how to solve this problem?

**Comment by ThinkerDreamer** [comment]
> @ThinkerDreamer What about using Next in a monorepo, how to solve this problem?

Hey, I have no idea! Luckily I'm not working with a monorepo now. If you figure it out, please post here!
