### ISSUE TITLE
Module not found: ESM packages (supports-color) need to be imported

### ISSUE THREAD

**Issue by 0xrasla** [vercel/next.js#49718]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:       
      next: 13.4.3-canary.0  
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0      
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/0xrasla/blog-next

### To Reproduce

Create a new Next.js project.
Install Mongoose using npm install mongoose.
Create a dbConnect.js file and add the following code:

`import { supportsColor } from "supports-color";
import mongoose from "mongoose";

const MONGO_URI = process.env.MONGO_URI;

console.log(`Connecting to ${MONGO_URI}`);

const database_connection = async () => {
  if (global.connection?.isConnected) {
    console.log("reusing database connection");
    return;
  }

  const database = await mongoose.connect(MONGO_URI, {
    useNewUrlParser: true,
  });

  global.connection = { isConnected: database.connections[0].readyState };
  console.log("new database connection created");
};

export default database_connection;
`

Import dbConnect in your app/api/route.js file and call it:

`import { NextResponse } from "next/server";
import dbConnect from "@/lib/dbConnect";

export async function GET(request) {
  return NextResponse.json({
    msg: "hell",
  });
}
`

Start your Next.js app using npm run dev.

### Describe the Bug

Actual behavior:

The app fails to start and throws the following error message:

`Module not found: ESM packages (supports-color) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals
`

Bug message for GitHub issues:

**Issue Description:**

When attempting to connect to a MongoDB database using Mongoose in a Next.js app, the following error is thrown:

`Module not found: ESM packages (supports-color) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals`

### Expected Behavior

Expected behavior:

The app starts without any errors and connects to the MongoDB database successfully.

### Which browser are you using? (if relevant)

OperaGX 4.29.0

### How are you deploying your application? (if relevant)

yarn dev

**Comment by FendiMohamed** [comment]
i m facing the same problem for days can you help me to fix it

**Comment by ashish293** [comment]
For me using -
`npm i supports-color@8.1.1`

It is working

**Comment by Yogeshthangm** [comment]
Its working for me too thanks

**Comment by francoisjacques** [comment]
OK it's a little too magical for me. Is the root cause known?

**Comment by Yogeshthangm** [comment]
No, maybe its a  NextJS 13.4 bug i guess.

**Comment by francoisjacques** [comment]
Ah, it appears that supports-color is in ESM now. debug is still CJS. Fun times.
