### ISSUE TITLE
NextJs Stripe Webhooks

### ISSUE THREAD

**Issue by oliverkidd** [vercel/next.js#49739]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://www.codedaily.io/tutorials/Stripe-Webhook-Verification-with-NextJS

### To Reproduce

Keeping things simple. Here's the function im using

import Stripe from "stripe";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY as string, {
  apiVersion: "2022-11-15",
});

export async function POST(req, res) {
const rawBody = await req.text(); // Have also tried using await buffer(req) from 'micro' but no luck
const stripeHeader = req.headers["stripe-signature"]; // This returns undefined always....
stripe.webhooks.constructEvent(rawBody,stripeHeader, process.env.STRIPE_WEBHOOK_SECRET_KEY as string );
}

export const config = {
  api: {
    bodyParser: false,
  },
};

### Describe the Bug

I have tried setting up stripe web hooks but it doesn't seem to work. Im not able to retrieve the header value using req.headers["stripe-signature"] from within my function.

Ive tried every possible solution on the docs already, im stumped.

### Expected Behavior

undefined value when using req.headers["stripe-signature"] on the req received from stripe webhook event

**Comment by alyssapiresfernandescefet** [comment]
headers now have a get() function, so you should use it like this: `req.headers.get('stripe-signature')`.

Route Handlers now don't have a `res` object in their parameters, so I think you should look into it a little bit more before implementing something with it.

Here's a link for further help: https://nextjs.org/docs/app/building-your-application/routing/router-handlers

**Comment by oliverkidd** [comment]
THANK YOU! You won't believe how much pain you've saved there. Couldn't seem to find clear documentation on that anywhere.

**Comment by rvermootenct** [comment]
@oliverkidd where you able to get it working without using res? Would you be able to shed some light?

**Comment by oliverkidd** [comment]
Certainly. I ended up removing the exported config to not parse the body as this doesn't seem to be necessary any more. The final code was as follows:

`
import { NextResponse } from "next/server";
import { buffer } from "node:stream/consumers";

export async function POST(req: any) {
  const rawBody = await buffer(req.body);
  let event;
  try {
    event = stripe.webhooks.constructEvent(
      rawBody,
      req.headers.get("stripe-signature") as string,
      process.env.STRIPE_WEBHOOK_SECRET_KEY as string
    );
  } catch (err) {
    console.log(err);
    return NextResponse.json(
      {
        message: "Webhook signature verification failed",
      },
      {
        status: 400,
      }
    );
  }
 // have to return response promptly, ie without waiting for back-end process or stripe will potentially flag your account
  handleWebhook(event);
  return NextResponse.json(
    { message: "successfully received" },
    { status: 200 }
  );
}`

**Comment by haris-aqeel** [comment]
`import { collection, doc, getDocs, limit, query, updateDoc, where } from 'firebase/firestore';
import { buffer } from 'micro';
import { NextApiRequest, NextApiResponse } from 'next';
import Stripe from 'stripe';
import { db } from '../../FirebaseConfig';


const stripe = new Stripe(process.env.STRIPE_API_KEY || "", {
  apiVersion: '2022-11-15',
});


interface InvoicePaidEvent extends Stripe.Event {
  data: Stripe.Invoice;
}


export const config = {
  api: {
    bodyParser: false,
  },
};





export default async function handleWebhook(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  const buf = await buffer(req);
  const sig = req.headers['stripe-signature']!;


  let event
  try {
    // const payload = buf.toString();

    event = stripe.webhooks.constructEvent(
      buf.toString(),
      sig as string,
      process.env.STRIPE_WEBHOOK_SECRET || ""

    ) as InvoicePaidEvent;

    console.log("event============>", event)
  } catch (err: any) {
    console.log(`Webhook Error: ${err.message}`);
    return res.status(400).send({ message: `Webhook Error: ${err.message}`, buf: buf, bugString: buf.toString() });
  }

  switch (event.type) {

    case 'invoice.paid':
      const email = (event.data.object as any).customer_email
      const userDocs = await getDocs(query(collection(db, 'users'), where('email', '==', email)));
      if (!userDocs.empty) {
        const userDoc = userDocs.docs[0];
        const userRef = doc(db, 'users', userDoc.id);
        await updateDoc(userRef, { plan: 'paid' });
        console.log(`Updated plan for user with email ${email} to 'paid'`);
      } else {
        console.log(`No user found with email ${email}`);
      }
      break;

    case 'invoice.payment_failed':

      const emailll = (event.data.object as any).customer_email
      const userDocsss = await getDocs(query(collection(db, 'users'), where('email', '==', emailll)));

      if (!userDocsss.empty) {
        const userDoc = userDocsss.docs[0];
        const userRef = doc(db, 'users', userDoc.id);
        await updateDoc(userRef, { plan: 'free' });
        console.log(`Updated plan for user with email ${emailll} to 'free'`);
      } else {
        console.log(`No user found with email ${emailll}`);
      }

      break;

    case 'customer.subscription.deleted':

      try {

        const customerId = (event.data.object as any).customer
        const cus = await stripe.customers.retrieve(customerId)
        const emaill = (cus as any).email
        const querySnapshot = await getDocs(query(collection(db, 'users'), where('email', '==', emaill), limit(1)));
        if (!querySnapshot.empty) {
          const document = querySnapshot.docs[0];
          if (document.exists()) {
            const userRef = doc(db, 'users', document.id);
            await updateDoc(userRef, { plan: 'free', credits: 5 });
            console.log(`Updated plan for user with email ${emaill} to 'free'`);
          } else {
            console.log(`No user found with email ${emaill}`);
          }
        } else {
          console.log(`No user found with email ${emaill}`);
        }
      } catch (error) {
        console.log(error)

      }

      break;

    default:
      console.log(`Unhandled event type ${event.type}`);
  }

  return res.status(200).json({ received: true });
}`

I am facing error like that

```
{
  "message": "Webhook Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe?"
}
```

My  buf in error looks like that

`"buf": "{\n  \"id\": \"evt_1NDgCrBlZB4s39emwJJWcS2c\",\n  \"object\": \"event\",\n  \"api_version\": \"2022-11-15\",\n  \"created\": 1685505616,\n  \"data\": {\n   .............}"
`

Bugstring looks like that 

`
 "bugString": "{\n  \"id\": \"evt_1NDgCrBlZB4s39emwJJWcS2c\",\n  \"object\": \"event\",\n  \"api_version\": \"2022-11-15\",\n... 
`

This exact piece of code works fine, when deployed on aws amplify or when run locally. Only problem occurs after vercel deployment

**Comment by moreno1123** [comment]
@haris-aqeel Did you manage to resolve the issue? I have the same problem and tried numerous answers from different sources but no luck :/

**Comment by abhishekjakhar** [comment]
I am having the same issue. The code works fine locally but when I deploy to Vercel it does it not work. I get the following error.

`Webhook Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
`

I have double checked that my production webhook secret is also correct. I am stuck on this error for 2 days now.

**Comment by haris-aqeel** [comment]
@abhishekjakhar  @moreno1123 I can help you resolve this error

**Comment by moreno1123** [comment]
@haris-aqeel Hey thanks for reaching out. I've eventually got it to work. 

My problem was that I was trying to resend the event through stripe dashboard and not matter what changes I've made I had no success.
![session2](https://github.com/vercel/next.js/assets/83433432/3f86d2d3-6dce-4fd8-b794-b7bafff6f82b)

After some time I tried with real payment event so after giving the card and paying it worked. The code was same as from @haris-aqeel.

I guess Stripe has a problem with resending events and webhooks. 
I would suggest to try and test the webhook with real payment.

**Comment by btahir** [comment]
I'm getting a 401 error. How are you all handling CORS?

I feel like the answer is similar to what people are doing here: https://github.com/vercel/next.js/discussions/47933

But I am not sure the best way to implement it for webhooks.

**Comment by nikshepsvn** [comment]
> I'm getting a 401 error. How are you all handling CORS?
> 
> I feel like the answer is similar to what people are doing here: #47933
> 
> But I am not sure the best way to implement it for webhooks.

Same here

**Comment by btahir** [comment]
Bizarre but if you simply add an empty Middleware function all of a sudden your route works??

```
export async function middleware(request: NextRequest) {}
```

**Comment by nikshepsvn** [comment]
Figured it out, for those it of you getting 401s make sure your auth isn't blocking requests to the endpoint since it's coming externally from stripe. That's why making the middleware helped above

**Comment by btahir** [comment]
> Figured it out, for those it of you getting 401s make sure your auth isn't blocking requests to the endpoint since it's coming externally from stripe. That's why making the middleware helped above

Thanks! That did it...I was using Clerk and had to add the api route to the publicRoutes array in middleware :)
