### ISSUE TITLE
When using intercepted routes and redirecting from within the modal, the modal does not unmount

### ISSUE THREAD

**Issue by ali-idrizi** [vercel/next.js#49731]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Wed Aug 25 23:20:18 UTC 2021
Binaries:
  Node: 18.12.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.4.3-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/github/ali-idrizi/nextgram/draft/cocky-turing

### To Reproduce

I have modified the nextgram example to have another page, and added a link to it in the /photo modal. To reproduce:

- Click on a photo to open the modal
- Click the "About Us" link just below the modal

### Describe the Bug

Notice the modal doesn't close after clicking the "About Us" link, even though we got redirect to `/about` page.

The About page still opens under the modal. Also, once redirected, clicking the backdrop doesn't close the modal, but instead goes back to the previous page. The backdrop has to be clicked twice to close the modal

### Expected Behavior

The modal should only stay open if the URL matches the intercepted route `photos/[id]`. In the above case, since we are redirected to `/about`, the modal should be unmounted

**Comment by mkarajohn** [comment]
Related to https://github.com/vercel/next.js/issues/49662

**Comment by ViliamKopecky** [comment]
I also have this problem. I created another example:

- repo: https://github.com/ViliamKopecky/next13-intercepting-routes
- running: https://next13-intercepting-routes.vercel.app/intercepting/yellow

https://github.com/vercel/next.js/assets/316435/da911bfb-31a9-4f41-b167-20cfa656c7d2

**Comment by ali-idrizi** [comment]
Closing this in favor of #49662
