### ISSUE TITLE
Docs: A bug with search box 

### ISSUE THREAD

**Issue by KaKashi1210** [vercel/next.js#49738]
### What is the improvement or update you wish to see?

if visit this url - https://nextjs.org/docs and i want to search for specific thing in docs i will go to this search bar 
![Screenshot from 2023-05-13 12-21-56](https://github.com/vercel/next.js/assets/97914006/104be049-63ba-44f9-b460-8faeb2e84fb0)
but if i click its not letting me type and i even tried pressing ctrl + k, it redirects me to search bar of the browser 

### Is there any context that might help us understand?

i inspected and found there is no text area or input tag to look out for input maybe i am wrong or issue is from my end, if that is the case i apologise to maintainers for raising unwanted issue 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs

**Comment by SonMooSans** [comment]
The text input is the trigger of search dialog, it should open the dialog when you clicked on it unless you are using unsupported browser

If the dialog doesn't open, try to reduce the width of your window, you should see there's a search icon on the navbar. Just click on it and the dialog should be opened

**Comment by KaKashi1210** [comment]
it was browser issue thanks :)
