### ISSUE TITLE
Docs: explain how to populate `alternates` metadata fields with current route's pathname

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#49743]
### What is the improvement or update you wish to see?

when `metadataBase` is set, it is possible to automatically populate the `alternates#canonical` metadata field with the current route's pathname by using `./`. this will also propagate correctly when set in a layout component. this is pretty neat but currently not documented.

```ts
export const metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_BASE_URL),
  alternates: {
    canonical: "./"
  }
}
```

(also see [this layout](https://github.com/vercel/next.js/blob/canary/test/e2e/app-dir/metadata/app/alternates/layout.tsx) in [this test](https://github.com/vercel/next.js/blob/canary/test/e2e/app-dir/metadata/metadata.test.ts#L326-L344))

the current docs examples [here](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#alternates) and [here](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase) don't document this option.

note: what is less clear is how this can be used with `alternates#languages`, i.e. how to add a locale prefix to the pathname `./` resolves to.

### Is there any context that might help us understand?

-

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/generate-metadata

**Comment by ddaoxuan** [comment]
@stefanprobst  I think this is documented here:
- https://nextjs.org/docs/app/api-reference/functions/generate-metadata#url-composition

**Comment by stefanprobst** [comment]
ah, thanks! i guess what's still unclear is how to add a locale prefix but that is probably a separate feature request.

**Comment by mrxsal** [comment]
Is there a way we can automatically add a trailing slash to the url? All my routes have `/` appended, but the generated canonical urls are always without a trailing slash. This is bad for SEO.
