### ISSUE TITLE
Docs: useSearchParams link goes to useParams on useRouter page

### ISSUE THREAD

**Issue by yousoumar** [vercel/next.js#49756]
### What is the improvement or update you wish to see?

On [`useRouter`](https://nextjs.org/docs/app/api-reference/functions/use-router#userouter) for the `app` directory's page, when you click on `useSearchParams` in "Migrating from the `pages` directory" section, it goes to `useParams`. 

### Is there any context that might help us understand?

See the below video: 

https://github.com/vercel/next.js/assets/63708012/1709ab26-9f8b-4114-b832-efbadb533394

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/use-router#userouter

**Comment by leerob** [comment]
Thanks for reporting! I will fix this. We're in the process of moving all of these new docs back to open source and the `docs/` folder. Stay tuned 😄

**Comment by yousoumar** [comment]
I forked the code to fix it but didn't find it. Felt kinda bad about my confidence, but now I know it's not on the repo :) Thank @leerob and @arjenbloemsma!

**Comment by arjenbloemsma** [comment]
You're welcome @yousoumar. I had a similar 'quest' recently where I could not find a certain doc in the repo, that is when I learned some docs are closed source. So don't let that influence your confidence, it was just a little bump on the awesome learning path you're on. Keep it up!
