### ISSUE TITLE
bcrypt issue

### ISSUE THREAD

**Issue by avmentzer** [vercel/next.js#49759]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
------------------------------------------

- error ./node_modules/@mapbox/node-pre-gyp/lib/clean.js:8:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$
./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
./node_modules/bcrypt/bcrypt.js
./components/helpers/registerUser.tsx
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

no link

### To Reproduce

use bcrypt

### Describe the Bug

loading bcrypt results in this error

### Expected Behavior

no error

**Comment by JesseKoldewijn** [comment]
Are you trying to use bcrypt on a client component by chance?

**Comment by avmentzer** [comment]
it's a server component. It currently works with bcrypt-ts.

**Comment by JesseKoldewijn** [comment]
I would guess that there might be a misconfig in your tsconfig setup since server components should have access to node modules.

**Comment by JesseKoldewijn** [comment]
Hmm weird, have you tried installing fs into the project itself? (I know, you shouldn't have to but worth to try right)

**Comment by 634750802** [comment]
same problem in next 13.4.3

**Comment by aimehai** [comment]
Same problem in next 13.4.3

**Comment by haythamfouda** [comment]
Any news? I have the same issue with Next 13.4.3

**Comment by sebadiaz-arg** [comment]
Same issue here with "next": "13.2.4" and using "bcrypt": "^5.1.1".

**Comment by sebadiaz-arg** [comment]
May be it is related with this situation:
https://stackoverflow.com/a/73929977/7191548

**Comment by haythamfouda** [comment]
I ended up using "bcryptjs" instead. It's working fine with no errors.

**Comment by JesseKoldewijn** [comment]
And you're sure you're not trying to use bcrypt on the browser side? @avmentzer 
Because that would be my last guess on this issue

**Comment by SudeepGowda55** [comment]
Yes "bcryptjs" works fine in client-side of next js

**Comment by elgatoflaco** [comment]
I solved it by adding "use server" at the top line of the file that used bcrypt.

What's curious is that if I use TypeScript, I don't have to set that flag.

Using Next.js 14 with app router.

**Comment by CzechCoder** [comment]
I'm using Next.js 14 with app router and bcrypt didn't have any problems with webpack but suddenly the errors showed up somewhere down the line without me changing any configs. Weird.
It just keeps saying "Critical dependency: the request of a dependency is an expression"
