### ISSUE TITLE
Docs: How do create a server and client component in one

### ISSUE THREAD

**Issue by jeengbe** [vercel/next.js#49752]
### What is the improvement or update you wish to see?

I would like an entry in the docs that explains how to create a component that works both on the server and the client. Depending on the rendering environment, it would behave slightly differently.

---

Example:
A translatable component `T` that takes a translation key and renders the translated text.

If `T` is used within no client component (i.e. used as a server component), it should translate the text on the server. Assume translation is a performance-heavy task and to be performed on the server, if possible.\
If the component, however, is used as child of some `"use client"` component, it should fall back to a React context from which it retrieves all translations and translate the string on the client's end. 

---

My idea thus far is something like the following:
```tsx
// use-t.ts
import { useClientT } from "./use-client-t";

export const useT = () => {
  if (typeof window === "undefined") {
    return require("./use-server-t").useServerT();
  }

  return useClientT();
};

// T.tsx
const T = ({ key, data }) => {
  const t = useT();

  return <>{t(key, data)}</>;
};

// client-component.tsx
"use client";

export const Counter = () => {
  const [count, setCount] = useState(0);

  return (
    <>
      <button onClick={() => setCount(count + 1)}>Increment</button>
      <T key="count" data={{ count }} />
    </>
  );
};

// server-component.tsx
export const Dashboard = () => {
  return <>
    { /* A lot of expensive T stuff */ }
  </>;
}
```

This illustrates how `useT()` would fall back to either a client-side hook, or a server-side function, depending on the environment.

Unfortunately, this doesn't work.

---

I assume this is a pattern that is, or if not, should be, possible. Something in the documentation that hints as to how to do this would be nice.

### Is there any context that might help us understand?

See above

**Comment by jeengbe** [comment]
It looks like this concept already works, just not with modules that import `server-only` or `next/headers`.

**Comment by jeengbe** [comment]
For anyone with a similar problem: Due to how these imports are collected (https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/core/src/react_server_components.rs#L64C1-L65, https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/core/src/react_server_components.rs#L182-L206), converting `import { cookies } from "next/headers"` to  `const { cookies } = require("next/headers");` bypasses this limitation for now.

**Comment by razorman8669** [comment]
@jeengbe "solution" works for us, but i'm curious if there are implications to pulling `cookies` in this way, especially in Typescript code where static imports are preferred.

**Comment by leerob** [comment]
You can't mix server and client components in the same file. This is a React restriction, not Next.js. 

- https://react.dev/reference/react/use-client

**Comment by jeengbe** [comment]
Hi @leerob! 

This issue isn't specifically about putting client and server components in the _same_ file, but rather a single component/hook that, depending on the environment, renders a client or server component/runs a different hook. It's strongly related to !49757, which is the only issue that prevents this pattern. 

A use-case for this is an expensive component/hook that, wherever possible, should run on the server without two different ways of calling it.
