### ISSUE TITLE
ReadonlyURLSearchParams is incompatible with URLSearchParams

### ISSUE THREAD

**Issue by laozhu** [vercel/next.js#49774]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.8.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.5.0
    Relevant packages:
      next: 13.4.2
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4

warn  - Latest canary version not detected, detected: "13.4.2", newest: "13.4.3-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

no

### To Reproduce

```ts
import { usePathname, useRouter, useSearchParams } from "next/navigation";

const router = useRouter();
const pathname = usePathname();
const searchParams = useSearchParams();

const clonedSearchParams = new URLSearchParams(searchParams);
clonedSearchParams.sort();

router.replace(["/login", clonedSearchParams.toString()].filter(Boolean).join("?"));
```

### Describe the Bug

Got type error

> Argument of type 'ReadonlyURLSearchParams' is not assignable to parameter of type 'string | URLSearchParams | string[][] | Record<string, string> | undefined'.
  Property 'size' is missing in type 'ReadonlyURLSearchParams' but required in type 'URLSearchParams'.ts(2345)
url.d.ts(840, 18): 'size' is declared here.

### Expected Behavior

No type error

**Comment by Naddiseo** [comment]
According to `@types/node` the `size` parameter was added to `URLSearchParams` in v18.16

**Comment by erikschul** [comment]
Related docs: https://nextjs.org/docs/app/api-reference/functions/use-search-params#updating-searchparams
