### ISSUE TITLE
emotion compiler leaves inline comments in output

### ISSUE THREAD

**Issue by Pikachews** [vercel/next.js#49779]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Mar  9 20:12:21 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.17
      pnpm: 7.30.5
    Relevant packages:
      next: 13.4.3-canary.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC minifier (swcMinify: true), SWC transpilation

### Link to the code that reproduces this issue

https://stackblitz.com/edit/github-j1khil?file=shared%2Fstyles.js%3AL21

### To Reproduce

Add any comment to a emotion styled component and build.
e.g.
```
export const basicStyles = css`
  // I shouldn't be present
  background-color: white;
  ...
`;
```
Search for the added text in the Search function of Chrome/browser.

![image](https://github.com/vercel/next.js/assets/5668416/6e7f966f-93c6-4a53-aa54-bfbd80ff24df)

### Describe the Bug

Inline comments written into emotion css/styled components are present in the compiled output.

### Expected Behavior

Inline comments should be stripped from the compiled output.

**Comment by kdy1** [comment]
<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/f4f4c570-4e98-42d6-86b1-a9a217c40917">
Closing as fixed
