### ISSUE TITLE
revalidate, revalidateTag and revalidatePath not working as  intended

### ISSUE THREAD

**Issue by epndavis** [vercel/next.js#49778]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.0
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://github.com/epndavis/nextjs-revalidate-issue

### To Reproduce

1. Load the homepage (revalidate)
- Wait 30 seconds for GraphQl fetch to revalidate, refresh the page a couple of times to get the new data

2. Load the homepage (revalidateTag)
- Go to http://localhost:3000/api/revalidate?tag=graphql

- Back to homepage, refresh the page a couple of times to get the new data
3. Load the homepage (revalidatePath)
- Go to http://localhost:3000/api/revalidate?path=/
- Back to homepage, refresh the page a couple of times to get the new data

4. Load http://localhost:3000/dynamicGraphQl/2 (revalidatePath)
- Go to http://localhost:3000/api/revalidate?path=/dynamicGraphQl/2
- Go back to dynamic page and refresh

### Describe the Bug

Steps 1 and 2 refresh all data on the page. There are two fetch requests on the homepage, one with revalidation (GRAPHQL) the other cached indefinitely (API). When revalidated through any of these methods the GRAPHQL is revalidated but the API fetch request is also revalidated.

Step 4. If revalidatePath is used on a dynamic route nothing happens unless revalidateTag is used.

### Expected Behavior

We would expect that only the revalidated request is re-run, the cached fetch request should remain static. If revalidating a page it shouldn't revalidate everything unless it is requested to be revalidated as in step 3 via the path. This is as described in this [youtube video](https://www.youtube.com/watch?t=677) and recently this [tweet](https://twitter.com/amosbastian/status/1656990717464526848?t=NhoM2U2GoKdq31k0jj80kw&s=19)

We would also expect dynamic routes to be revalidated via `revalidatePath` .

**Comment by ijjk** [comment]
Hi, everything appears to be working properly in the provided reproduction with the latest canary of Next.js as can be seen in the below recording. Something to note from above is that revalidatePath should be called with the page's pathname not the URL e.g. `/dynamicGraphQl/[id]` and not `/dynamicGraphQl/2`

https://github.com/vercel/next.js/assets/22380829/0e67d685-2134-4789-bff4-7d7653cae7b4

**Comment by joncoronel** [comment]
> 

Wouldn't that mean that revalidating a dynamic path would revalidate every dynamic page generated in the cache for that dynamic route?
So if I have a hundred pages generated for a dynamic path, it would revalidate all of them? Personally, I would like to be able to revalidate a specific dynamic page instead of having to revalidate all of them.

**Comment by joncoronel** [comment]
> 

Temporary workaround is to add a [slug] tag to the fetch functions in the dynamic path and then call revalidateTag.

**Comment by ijjk** [comment]
@joncoronel if you want to revalidate a specific pathname e.g. `/blog/first` you can continue to leverage On-Demand ISR although do note that `revalidatePath` does not revalidate all affected paths under a dynamic path immediately only when next visited so if you visit one pathname under dynamic path and then the rest are visited and the cache is already updated they will not re-fetch.

**Comment by joncoronel** [comment]
@ijjk I found that after the 13.4 update, the old method of On-Demand ISR through res.revalidate no longer works with pages in app dir. I get an error message. 

Okay got it that makes more sense. So when I visit a dynamic path that was already in cache that has been revalidated through revalidatePath,  would it still first show the cached version of the dynamic path and revalidate in the background similar to time-based ISR or would it wait to load the page until it is revalidated like how it would if that dynamic path has not been generated yet/not in cache?

**Comment by lseemann** [comment]
```Something to note from above is that revalidatePath should be called with the page's pathname not the URL e.g. /dynamicGraphQl/[id] and not /dynamicGraphQl/2```

Is this the intended behavior for `revalidatePath`? As @joncoronel notes, if one invokes `revalidatePath`, one probably intends to revalidate _a single path_, not all the paths that match a dynamic route.

**Comment by tutorialcode** [comment]
> 

Hi, can you elaborate this more? e.g. After using validatePath('/blog/[slug]'), if i visit /blog/my-post-1, that will get regenerated, then I visit /blog/my-post-2, but that will not get regenerated because my-post-1 has been regenerated?

**Comment by tutorialcode** [comment]
> `revalidatePath` does not revalidate all affected paths under a dynamic path immediately only when next visited so if you visit one pathname under dynamic path and then the rest are visited and the cache is already updated they will not re-fetch.

Hi, can you elaborate this more? e.g. After using validatePath('/blog/[slug]'), if i visit /blog/my-post-1, that will get regenerated, then I visit /blog/my-post-2, but that will not get regenerated because my-post-1 has been regenerated?

**Comment by mediabeastnz** [comment]
Should this be re-opened? It's still an issue as @tutorialcode pointed out

**Comment by Tommoore96** [comment]
I still have this problem.  

I'm trying to create something on one page and revalidate another, but when I click "back" in the browser to get to `/view-posts` I'm only shown the old data.  If I click a `Link` element then the `/view-posts` page is revalidated, although that happens regardless of whether I use `revalidatePath` or not.

I've tried putting some console.logs in my code and it looks like the component is rendered *before* the server action (`getPosts`) is called. 🤔 

Am I using server actions wrong???

```ts
// app/create-post/actions.ts

export async function createPost(content: string) {
  const { userId, orgId } = auth();

  await db.insert(posts).values({ content });

  revalidatePath("/view-posts");
}
```

```tsx
// app/view-posts/page.tsx

async function getPosts() {
  "use server";

  const posts = await db
    .select()
    .from(postsTable)

  return posts;
}

export default async function Posts({
  params,
}...
```
