### ISSUE TITLE
Safari 12-13 broken due to "Can't find variable: BigInt"

### ISSUE THREAD

**Issue by Andrew67** [vercel/next.js#49789]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: 7.29.3
    Relevant packages:
      next: 13.4.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Link to the code that reproduces this issue

https://github.com/vercel/next.js/tree/canary/examples/reproduction-template

### To Reproduce

- Clone the `reproduction-template` with no changes
- `yarn build && yarn start` (or equivalent `npm`/`next`)
- Try to open the empty site on an iOS 12 device

User agent of my reproduction device: `"Mozilla/5.0 (iPad; CPU OS 12_5_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1"`

My workaround in `pages/_document.tsx`:
```jsx
<Script id="ios12-compat" strategy="beforeInteractive">
  {`if (!('BigInt' in window)) {
      window.BigInt = (x) => Number(x);
      BigInt.asUintN = (_, x) => x;
    }`}
</Script>
```

### Describe the Bug

`ReferenceError: Can't find variable: BigInt` which prevents any client-side code from running.
This is a follow-up to the now-closed #47045, it's the same error.
Seems to be relevant again now that `appDir` is enabled OOTB, I ended up hitting this when upgrading one of my projects to 13.4.2.

### Expected Behavior

Pages should load normally with no error.

### Which browser are you using? (if relevant)

iOS Safari 12.5.6

**Comment by JesseKoldewijn** [comment]
According to mozilla the bigInt primitive is supported on safari from version 14 (came out in 2020)
To prevent this error you'll have to transpile the build output to an older ecma script standard. 

bigInt primitive: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility 

To support older browsers, you can reference the docs: https://nextjs.org/docs/architecture/supported-browsers

**Comment by Andrew67** [comment]
Is there a plan to change which browsers are officially supported?
As mentioned in #47045 the `BigInt` usage came from new `appDir`-related router code.
The Supported Browsers doc still states this as of today:
> Next.js supports modern browsers with zero configuration.
> - Chrome 64+
> - Edge 79+
> - Firefox 67+
> - Opera 51+
> - Safari 12+

But the use of `BigInt` out of the box invalidates a big portion of this list.

**Comment by JesseKoldewijn** [comment]
> Is there a plan to change which browsers are officially supported?
> As mentioned in #47045 the `BigInt` usage came from new `appDir`-related router code.
> The Supported Browsers doc still states this as of today:
> > Next.js supports modern browsers with zero configuration.
> > - Chrome 64+
> > - Edge 79+
> > - Firefox 67+
> > - Opera 51+
> > - Safari 12+
> 
> But the use of `BigInt` out of the box invalidates a big portion of this list.

The docs state that Next.js supports these more modern browsers without any configuration. The docs also state that you can support older ones using the browserslist config. I don't think it will be a high prio to support older version in the default setup to be honest but well, could change in the future ofcourse.

**Comment by Andrew67** [comment]
Yes, the issue is occurring on Safari 12 which is on that list in the docs as a "modern" browser supported without any configuration.

**Comment by JesseKoldewijn** [comment]
ah gotcha, in that case I do agree that they should clarify that the app router with the default config only support Safari 14+ and not below that point without any form of polyfills or transpile flow.

**Comment by Andrew67** [comment]
Actually, I see that in this commit: https://github.com/vercel/next.js/commit/3323702018b67e447560b07d4a9625d2ce1b4800#diff-a740b6030c209e42a78459a1e0b566f38110738bffba171f5795a77a577a71ed

The code is refactored that used to depend on `fnv1a` which is where `BigInt` came in. It's possible this won't be an issue in the next canary, but the latest canary is from a day before this commit.

**Comment by Andrew67** [comment]
Update, the issue is solved in `13.4.3-canary.1` with no configuration changes thanks to that commit as expected.
CC @ijjk 

From what I can tell no other piece of code uses `fnv1a` after that commit.

**Comment by JesseKoldewijn** [comment]
Awesome, glad to hear it got resolved!

**Comment by ijjk** [comment]
Closing as https://github.com/vercel/next.js/issues/49789#issuecomment-1548958832 mentioned this should be fixed in the latest canary!
