### ISSUE TITLE
[NEXT-1257] SSR errors still reported even when fixed, until the dev server is rebooted

### ISSUE THREAD

**Issue by joshwcomeau** [vercel/next.js#49788]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/joshwcomeau/ssr-repro

(relevant code + instructions in `/src/app/page.js`)

### To Reproduce

1. Introduce an error in a Client Component by trying to access `window` in render:

```jsx
'use client';

function Home() {
  window.localStorage.getItem('hello');
  return <p>Hi</p>;
}

export default Home;
```

2. Start a dev server (`npm run dev`). The error will be logged:
<img width="436" alt="CleanShot 2023-05-14 at 17 22 07@2x" src="https://github.com/vercel/next.js/assets/6692932/ef8d8263-a21d-4960-87a4-3a506e763459">

3. Fix the error by removing the `window` reference.
4. Refresh the page.

In the terminal, the error continues to be reported, even though the issue is fixed:

<img width="381" alt="CleanShot 2023-05-14 at 17 23 23@2x" src="https://github.com/vercel/next.js/assets/6692932/06a3c0ba-f225-4109-8b0f-87e2d1166af4">

### Describe the Bug

The `window is not defined` error persists even after it's been fixed. This continues until the dev server is restarted.

The "ghost error" stops SSR from working. It's also potentially super confusing, and might make developers think that they haven't actually fixed the problem.

### Expected Behavior

No error should be logged once the error has been fixed.

### Which browser are you using? (if relevant)

Chrome 113.0.5672.92 (Official Build) (arm64)

<sub>[NEXT-1257](https://linear.app/vercel/issue/NEXT-1257/ssr-errors-still-reported-even-when-fixed-until-the-dev-server-is)</sub>

**Comment by huozhi** [comment]
Hi can you try the latest canary (`>= 13.4.5-canary.6`)? It seems resolved for me. Thanks

**Comment by joshwcomeau** [comment]
Just tried it, and can confirm that it appears to be fixed! Thanks @huozhi :)
