### ISSUE TITLE
SearchParams in page.tsx are empty after build

### ISSUE THREAD

**Issue by pstachula-dev** [vercel/next.js#49781]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT Wed Apr 26 19:16:58 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.5.0
    Relevant packages:
      next: 13.4.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### To Reproduce

SearchParams in page.tsx are empty after build
I have Url: `http://localhost:3000/?carType[]=combi&fuel[]=diesel`

When I run root page in SSR in dev mode:
```
const Home = async (pageProps) => {
  console.log(new URLSearchParams(pageProps.searchParams).toString();)
```
Output: // { 'carType[]': 'combi', 'fuel[]': 'diesel' }

After build and start:
Output: // {} 

It is expected behavior?

**Comment by JesseKoldewijn** [comment]
Check if it still persists when you follow the tips on here > https://github.com/vercel/next.js/issues/43077#issuecomment-1543638105-permalink and the docs > https://nextjs.org/docs/app/api-reference/functions/use-search-params#behavior
