### ISSUE TITLE
Docs: please include example with app dir and context with useState

### ISSUE THREAD

**Issue by pguardiario** [vercel/next.js#49839]
### What is the improvement or update you wish to see?

It's not clear how to maintain client state with new app dir. None of the example apps demonstrate this

### Is there any context that might help us understand?

An example app with new app dir and a context that maintains client state

**Comment by camezcua12** [comment]
This has more to do with React itself, and how it separates Client and Server Components, than it has to do with the App Router itself, at least in my opinion.

If you go to [this link](https://nextjs.org/docs/getting-started/react-essentials) you'll see the whole gist of Server Components, and the `use client` directive to instruct React which are Server and Client components.

There is also a pretty good summary table to know when to use either types of components in [this section](https://nextjs.org/docs/getting-started/react-essentials#when-to-use-server-and-client-components) of the same page. In there it is explained that if you need to use State and/or Lifecycle Effects (such as `useState`), then you should use the `use client` directive at the start of your component to tell React if will be a Client Component.

**Comment by pguardiario** [comment]
Thanks @camezcua12, there's some confusion because new app router no longer allows passing props from layout / app to pages, and also maintaining state with context seems to be broken (at least in my experience). So I'm hoping someone can provide an example of this very common situation in the examples folder.

**Comment by timneutkens** [comment]
Have a look at this example: https://github.com/vercel/app-playground/tree/main/app/context

Deployed example: https://app-router.vercel.app/context

**Comment by leerob** [comment]
Hey there! We do have some documentation here. Hopefully this and the example above help out.

https://nextjs.org/docs/getting-started/react-essentials#context

**Comment by pguardiario** [comment]
@leerob - yes but these docs don't address state at all.
@timneutkens - thank you! this is what I'm looking for I think.
