### ISSUE TITLE
Build logs show wrong page type (Lambda) when using cookies() and Suspense

### ISSUE THREAD

**Issue by borispoehland** [vercel/next.js#49847]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.25.1
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/borispoehland/cookies-suspense-repro

### To Reproduce

- Build the project
- Notice how `/` and `/mixed` produce a lambda build output, even though they are static
<img width="472" alt="Bildschirm­foto 2023-05-16 um 11 13 00" src="https://github.com/vercel/next.js/assets/60541010/5f646a0a-5039-4038-bbcb-dd281b4309bc">

### Describe the Bug

In the `/`, `/working` and `/mixed` routes I fetch the timestamp and it is static. Meaning the page is static and behaves like getStaticProps, right?

The problem comes as soon as you drop in a server component using `cookies()`, however I prevent the CSR from bubbling up using a Suspense boundary:
```
import { Suspense } from 'react'
import CookiesServerComponent from './components/CookiesServerComponent'
import { fetchTimestamp } from './fetchers/fetchTimestamp'

export default async function Page() {
  const timestamp = await fetchTimestamp() // I only run once, on build
  return (
    <>
      <h1>{timestamp}</h1>
      <Suspense>
        <CookiesServerComponent />
      </Suspense>
    </>
  )
}
```

Nevertheless, the build output shows the route as dynamic route (lambda symbol), even though the route seems to be static (just like `/working`, where it displays correctly because `cookies()` isn't used). To verify, visit https://cookies-suspense-repro.vercel.app/ and you can see that the timestamp doesn't change.

### Expected Behavior

In the build output, it should show the circle icon instead of the lambda icon

### How are you deploying your application? (if relevant)

Vercel

**Comment by ijjk** [comment]
Hi, this is correct as is as the pages are dynamically rendered for each request the static part is the fetch calls being cached!

**Comment by borispoehland** [comment]
> Hi, this is correct as is as the pages are dynamically rendered for each request the static part is the fetch calls being cached!

So you can have static fetches inside a dynamic route with Lambda symbol? Can you please answer these questions for me?

- Does it make a difference if I have this markup:
```
export default function Page({
  searchParams,
}: {
  searchParams: Record<string, string>
}) {
    // Imagine this div was a huge component, with own fetches and state
  return <div>{JSON.stringify(searchParams)}</div>
}
```
or this:
```
import { Suspense } from 'react'
import ClientComponent from './client'

export default function Page() {
  return (
    // Imagine this div was a huge component, with own fetches and state
    <div>
      <Suspense>
        <ClientComponent />
      </Suspense>
    </div>
  )
}
```
```
'use client'

import { useSearchParams } from 'next/navigation'

export default function ClientComponent() {
  const searchParams = useSearchParams()
  return <>{JSON.stringify(searchParams)}</>
}
```

Because if yes, I think that should reflect in the build logs:

- When a page is completely opted out of SSR due to `searchParams` cookies() or headers() and NO suspense boundary, show the lambda
- When a page is partially or not opted out of SSR (for example by catching with a suspense boundary that protects the wrapping components from being opted out of CSR, show the circle symbol

You know what I mean?
