### ISSUE TITLE
[NEXT-1287] Docs: Problem of calling a page twice when navigating a page using nextLink

### ISSUE THREAD

**Issue by holicreact** [vercel/next.js#49844]
### What is the improvement or update you wish to see?

Problem of calling a page twice when navigating a page using nextLink

### Is there any context that might help us understand?

If you apply the prefetch={false} option to nextLink, the page is called twice when navigating the page of a sub-dynamic segment of the dynamic segment path.

I am sending additional unnecessary API requests because I make API requests inside the page.

For example, when you have a \[categorySlug\]\[subCategorySlug\] path, if you browse the categorySlug page, you request the page only once, but when you browse the subCategorySlug path, you request the page twice

If this is a bug, please fix it If it's not a bug, please let me know how to prevent page duplicate calls Thank you.

![](https://uploads.linear.app/099ed59a-06c6-472f-9977-4798721bda90/de3f51bd-f6de-4068-9142-f88c38901aed/67ede91e-8dd8-4c5c-92ab-de5c0fa147c9)

### Does the docs page already exist? Please link to it.

\*\*[https://app-directory-v2.vercel.app/context](https://app-directory-v2.vercel.app/context)

[https://github.com/holicreact/app-directory-v2.git\*\*](https://github.com/holicreact/app-directory-v2.git\*\*)

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-1287](https://linear.app/vercel/issue/NEXT-1287/docs-problem-of-calling-a-page-twice-when-navigating-a-page-using)</sub>

**Comment by thexpand** [comment]
@holicreact Could it be only in development because of the strict mode?

**Comment by holicreact** [comment]
thank this is link 
**https://github.com/vercel/next.js/issues/49844#issuecomment-1549876192**

**Comment by holicreact** [comment]
> HI, to better understand the issue you are facing, could you please share the code that you are currently running? The more details you can provide, the easier it will be to find the problem.

@SamarthBagga 
thank this is link
https://github.com/holicreact/app-directory-v2

> @holicreact엄격한 모드 때문에 개발 중일 수 있습니까? React가 엄격 모드에 있을 때 컴포넌트가 마운트되었다가 마운트 해제되었다가 다시 마운트된다는 점에 유의하십시오. 이것은 개발에서만 발생합니다.

@thexpand It's sad but It's working regardless of that.

**Comment by chaepling** [comment]
Having the same issue here. Can somebody please explain why this is happening? My loggin plan exceeded due to this cause.

**Comment by holicreact** [comment]
> Having the same issue here. Can somebody please explain why this is happening? My logging plan exceeded due to this cause.

@chaepling  you too? I hope this problem is resolved soon

**Comment by smo043** [comment]
We are also seeing similar issues; I have apis on all of my pages, and the apis are going into an infinite cycle due to link prefetch.

**Comment by jakepeyser** [comment]
This is preventing us from upgrading to v13.4. We have several navigation elements with many links that we can't afford to prefetch them all, so we'd need to set `prefetch` to false, but this issue would have us duplicating the requests on each link click, neither of which is desired.

**Comment by jakepeyser** [comment]
@smo043 We're on 13.3.4 in prod

**Comment by jakepeyser** [comment]
@smo043 I do not see the issue at our current version, Next.js only seems to prefetch metadata on hover and the new page is rendered and injected on click

**Comment by smo043** [comment]
> @smo043 I do not see the issue at our current version, Next.js only seems to prefetch metadata on hover and the new page is rendered and injected on click

Oh okay, In my case all routes are being prefetched on every page load

**Comment by smo043** [comment]
@holicreact - could we change the title of this issue, since many of us have a similar issue?

**Comment by holicreact** [comment]
> This issue is preventing us from upgrading to v13.4. We have several navigation elements with many links that we can't afford to prefetch them all, so we'd need to set `prefetch` to false, but this issue would have us duplicating the requests on each link click, neither of which is desired.

@jakepeyser That's right, depending on the specific conditions, both sides have problems.


> @smo043 I do not see the issue at our current version, Next.js only seems to prefetch metadata on hover and the new page is rendered and injected on click

@jakepeyser
@smo043  

prefetch={true} 일때 개발 환경에서는 마우스 호버시 데이터를 가져옵니다.
하지만 프로덕션 환경에서는 뷰포트에 보일때 데이터를 패칭합니다.

prefetch={false} 일때는 프로덕션에서 마우스를 호버해도 데이터를 패칭 하지 않고 
링크 클릭시 페이지를 두번 호출합니다.

이것은 하드 탐색 또는 소프트 탐색과 관련이 있다고 생각합니다.



> @holicreact - could we change the title of this issue, since many of us have a similar issue?

@smo043 What are you going to change the title to?
If it's a good title, I agree I think maybe you can choose a better title than me Please

**Comment by smo043** [comment]
@holicreact - Sorry for not being clear, can we change [docs] to [bug]?

**Comment by holicreact** [comment]
> @holicreact - Sorry for not being clear, can we change [docs] to [bug]?

That's a good idea. I'll organize it and post the bug report again
