### ISSUE TITLE
Docs: Equivalent for the `_app.tsx` entrypoint in App Router

### ISSUE THREAD

**Issue by camezcua12** [vercel/next.js#49850]
### What is the improvement or update you wish to see?

Being able to create Custom Apps in the Pages Router added a lot of adaptability and customization to projects, but at the moment it doesn't seem there is any equivalent to it in App Router (maybe `layout.tsx`, but doesn't do quite the same).

### Is there any context that might help us understand?

Back with Pages Router, you could import the `reflect-metadata` polyfill for DI libraries into `_app.tsx`. Currently, importing the polyfill the same way into `layout.tsx` doesn't really work.

**Comment by ala-garbaa-pro** [comment]
## Equivalent for the `_app.tsx` entrypoint in App Router in Next.js 13

The equivalent for the `_app.tsx` entrypoint in App Router in Next.js 13 is the `app/layout.tsx` file. This file is used to render the initial layout of your application, and it can be used to add global functionality to your application.

The `app/layout.tsx` file is a React component that receives two props: `Component` and `pageProps`. The `Component` prop is the name of the page that should be rendered, and the `pageProps` prop is an object that contains the initial props for the page.

The `app/layout.tsx` file can be used to add global functionality to your application. For example, you can use it to add a header or footer to all of your pages, or to inject additional data into pages.

Here is an example of an `app/layout.tsx` file that uses the `App` component to add a header to all of your pages:

```tsx
import React from 'react';
import { App } from 'next/app';

const AppWithHeader = () => (
  <App>
    <header>
      <h1>My App</h1>
    </header>
    <main>
      <h2>This is my main content</h2>
    </main>
  </App>
);

export default AppWithHeader;
```

This code will add a header to all of your pages. The header will contain the text "My App".

The `app/layout.tsx` file can also be used to inject additional data into pages. For example, you can use it to inject the current user's data into pages.

Here is an example of an `app/layout.tsx` file that uses the `App` component to inject the current user's data into pages:

```tsx
import React from 'react';
import { App } from 'next/app';

const AppWithUser = ({ user }) => (
  <App>
    <main>
      <h2>This is my main content</h2>
      <p>Hello, {user.name}</p>
    </main>
  </App>
);

export default AppWithUser;
```

This code will inject the current user's data into all of your pages. The user's name will be displayed in the header of each page.

The `app/layout.tsx` file is a powerful tool that can be used to control the initial rendering of pages and to add global functionality to your application.

**Comment by camezcua12** [comment]
Thanks for that @ala-garbaa-pro! It's a great elaboration, but unfortunately doesn't cover the point I was trying to make with my initial comment. So previously, with `_app.tsx`, you could import whichever packages you might need to work for the whole of the NextJS application, such as `reflect-metadata` for using decorators and/or DI libraries.

At the moment surely you can replicate whatever component tree you had with `_app.tsx` with `app/layout.tsx`, but what about those global imports I explained above? How would you ideally import something like `reflect-metadata` in `app/layout.tsx`? As far as I've tested it, it doesn't work, my only workaround for the time being replace the `package.json` scripts by being prefaced by `node -r reflect-metadata`, but that doesn't seem ideal.

**Comment by programateus** [comment]
Thanks for reporting this @camezcua12! I'm running into this same issue, currently importing `reflect-metadata` into `app/layout.tsx` has no effect. I have tried your workaround using `node -r reflect-metadata ./node_modules/.bin/next dev` but I got no success so far.
What is working for me right now is marking my files with `'use client'` and importing it, but it's obviously not the right approach...

**Comment by leerob** [comment]
Thanks for the comment @ala-garbaa-pro! This is correct, see the adoption guide as well: https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#migrating-_documentjs-and-_appjs

If you need to use some library that requires client-side React, it is okay to `"use client"`: https://www.youtube.com/watch?v=6jM_0wDOw4g

**Comment by elmarsto** [comment]
> Thanks for the comment @ala-garbaa-pro! This is correct, see the adoption guide as well: https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#migrating-_documentjs-and-_appjs
> 
> If you need to use some library that requires client-side React, it is okay to `"use client"`: https://www.youtube.com/watch?v=6jM_0wDOw4g

This answer does not actually address the point raised by OP, and this is the second time on this thread someone has fired off a non-explanation without reading and appreciating the problem. 

As it happens, I have the same problem, and also, as it happens, with `reflect-metadata`. Has anyone got a *working*, verified solution to doing global, project-wide imports, a matter *not* resolvable by just slapping "use client" on everything, *or* modifying layout.tsx?

**Comment by elmarsto** [comment]
Update: my workaround is incredibly boneheaded, but does indeed work. just add `import 'reflect-metadata'`to the top of literally every `**/*.ts{,x}`.  No `use 'client'`or changes to `package.json` required. 

Hopefully a proper mechanism will come out for global imports in Next 14 or whatever, and I can just `sed` away this boilerplate.

**Comment by pabloimrik17** [comment]
Any update on this issue? I have the same problem with a new project in my company and i was really excited to do it with Nextjs

**Comment by programateus** [comment]
@pabloimrik17 since I am using Inversify and have to import all dependencies to one file, what worked for me was importing reflect-metadata into that file.

A snipped of my current code:

```typescript
import "reflect-metadata";
import { Container } from "inversify";

import { infraDependencies } from "@/infra/dependencies";
import { applicationDependencies } from "@/application/dependencies";

const container = new Container();
const dependencies: DependencyDictionary[] = [
  ...applicationDependencies,
  ...infraDependencies,
];
for (const dependency of dependencies) {
  if (dependency.token && dependency.implementation) {
    const whenOn = container
      .bind(dependency.token)
      .to(dependency.implementation);
    if (dependency.name) whenOn.whenTargetNamed(dependency.name);
    continue;
  }
  if (dependency.token && dependency.value) {
    const whenOn = container
      .bind(dependency.token)
      .toConstantValue(dependency.value);
    if (dependency.name) whenOn.whenTargetNamed(dependency.name);
    continue;
  }
  throw new Error(
    `Could not bind dependency: ${
      dependency.value || dependency.implementation
    }`
  );
}

export default container;
```
