### ISSUE TITLE
something wierd is going on with prismas findMany in nextjs

### ISSUE THREAD

**Issue by nitlott** [vercel/next.js#49854]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
OS:
    archlinux (same results on vercel production tho)

    Database:
    postgres (same results on vercel production tho)

    Node.js version:
    v19.9.0 (same results on vercel production tho)
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue

https://have.none.com

### To Reproduce

Use nextjs 13 with appfolder and no src folder, create 2 different routes that uses findmany as below, and setup prisma to supabase postgres. load the feed to fetch all prompsts,. and make a profile page that can list its own prompts with params that contain id to filter in findmany

### Describe the Bug

after more investigation it seams it is prismas findmany in combination with nextjs, it does not mather if its on vercel or not.
if i npm run build and npm run start locally i get same results.
but if i run npm run dev it works.

this findmany caches forever after first run (even if you try other devices it still shows the data from first run and deleted posts are still there also new prompts is not there)
here is my /api/prompt route
const prompts = await prisma.prompt.findMany({ include: { creator: true }, });

and this one works without a problem everytime :
here is my /api/users/[id]/prompt route
const prompts = await prisma.prompt.findMany({ where: { creatorId: params.id, }, include: { creator: true }, });

i have tried many different aproaches solving this but nothing seams to work. this problem started when i implemented prisma instead of using mongoose/mongodb.

i now use postgres database (atm supabase if that mathers for investigation)

### Expected Behavior

expected behavior is that the feed page should update with current prompts in database, not showing deleted prompts and showing new prompts. which it does not.

in profile page it works flawlesly

only difference is this part in findMany:

where: { creatorId: params.id, }

### Which browser are you using? (if relevant)

not relevant, its the same on every browser/device i tried always loads the data from whomever loaded it first

### How are you deploying your application? (if relevant)

i tried multiple ways, only way that works is in dev, it occurs when you build the app

**Comment by timneutkens** [comment]
Unfortunately you haven't provided a reproduction so this is entirely guessing. It seems you're just not expecting static generation? See these docs: https://nextjs.org/docs/app/building-your-application/routing/router-handlers#static-route-handlers
