### ISSUE TITLE
File-based Metadata - opengraph-image wrong URL

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#49859]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue

https://github.com/ciruz/next-og

### To Reproduce

On our latest next.js project we have an `opengraph-image` via File-based metadata, so basically we created an `opengraph-image.jpg` in the `/app` directory.

Everything works fine in development mode, as soon as we deploy the project on our production system, the `og:image` has a wrong url (`https://localhost:3000`):
![image](https://github.com/vercel/next.js/assets/987947/9789870a-09ca-4105-9352-b0fa1b6fcbc1)
`<meta property="og:image" content="http://localhost:3000/opengraph-image.jpg?dd6067b0d6892c99"/>`

All other regular assets, have a realtive path.

If I deploy a blank project [`https://github.com/ciruz/next-og`](https://github.com/ciruz/next-og) with an `og:image` to **Vercel**, the URL + Path for the `og:image` is somehow set and not `localhost`, so I assume Vercel sets like a base domain / path somewhere in the background / config of next.js, but it's a different subdomain (more in the end of text).

If I set an [assetPrefix](https://nextjs.org/docs/app/api-reference/next-config-js/assetPrefix) in the `next.config.js` the prefix is applied everywhere, but not for the `og:image` or Favicon set via `Metadata`.

```js
//next.config.js
const isProd = process.env.NODE_ENV === 'production';
 
module.exports = {
  // Use the CDN in production and localhost for development.
  assetPrefix: isProd ? 'https://cdn.mydomain.com' : 'http://foobar.com',
};
```

Result:
```
<meta property="og:image" content="http://localhost:3000/opengraph-image.jpg?3672c8818f51ad56"/>
<link rel="icon" href="images/test.svg"/>
<script src="http://foobar.com/_next/static/chunks/polyfills.js" noModule=""></script>
```
![image](https://github.com/vercel/next.js/assets/987947/9d5add69-00d4-4460-a3ad-c9d60cf7582d)

When I check the source of my example repo on Vercel, it's also weird that the `og:image` has a different domain/subdomain there:

- URL: https://next-og-lyart.vercel.app/
- `og:image` url: `<meta property="og:image" content="https://next-bof7pedda-ciruz.vercel.app/opengraph-image.jpg?3672c8818f51ad56"/>`

![image](https://github.com/vercel/next.js/assets/987947/b769db2b-0407-4bad-9548-4907679bb885)

Even if I start my local next.js instance, with just a different port (`:3001`) and view the source, the `og:image` has the default (now wrong) port:

![image](https://github.com/vercel/next.js/assets/987947/ec84c615-ebf8-4b4b-8617-a8d49a839fb5)

### Describe the Bug

Metadata `og:image` has the wrong URL.

### Expected Behavior

- Have a relative path **OR**
- Use the assetPrefix for Metadata too **OR**
- Have another way to set a Base Domain for Metadata Informations

### Which browser are you using? (if relevant)

Latest Chrome

### How are you deploying your application? (if relevant)

Vercel, Other

**Comment by huozhi** [comment]
`assetPrefix` doesn't apply for metadata as it could by any string, to assign a proper domain for it you need to use `metadataBase` in the layout, please checkout the [docs](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase).

I found the 2nd issue that port doesn't match is a compilation related issue, drafting a fix now

**Comment by ciruz** [comment]
@huozhi thank you for the new informations. You are right, if i'm in development mode, the metadataBase is ignored for the file based `og:image`, if I build the site and then start it, the url is set correctly.
