### ISSUE TITLE
CSS module not loading inside dynamic routes when importing into both loading and page

### ISSUE THREAD

**Issue by abepuentes** [vercel/next.js#49871]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 4.0.0-rc.42
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Link to the code that reproduces this issue

https://github.com/abepuentes/loading-css-module-bug

### To Reproduce

1. npx create-next-app@latest
2. Add a file structure for dynamic routes
3. Add a loading.tsx page
4. import the same css module to both page.tsx and loading.tsx
5. Deploy or build the project

Error was introduce with next@13.3.0, working as expected on next@13.2.4.

Live demo: https://loading-css-module-bug.vercel.app

### Describe the Bug

NextJS let you add a loading.tsx page to render while fetching, if we import the same css module to this loading.tsx file and into page.tsx file, the style is not apply until refresh.

The reason to import from the same css module into this two files is to have the same styling while the data is fetching.

Works fine on dev, this bug its visible once deployed to Vercel/Amplify-Hosting or after building while using yarn start/npm run start.

### Expected Behavior

Style should be applied to the page file after loading without need to refresh the page. Working as expected while development. Workaround so far its pretty easy, just import style from different css modules.

### How are you deploying your application? (if relevant)

next start, Vercel, Amplify Hosting

**Comment by rusted-love** [comment]
We experience a similar problem in our production build.
Our NextJs version is 13.4.4
With direct link page works fine.
While navigating with `next/link` from another page, css just not included in DOM.

**Comment by Yukioru** [comment]
+1
Same problem. Reproducible only in the production build on the latest canary version.

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 19.7.0
  npm: 9.5.0
  Yarn: N/A
  pnpm: 8.6.0
Relevant packages:
  next: 13.4.5-canary.4
  eslint-config-next: 13.4.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
```

**Comment by rusted-love** [comment]
This issue is still present in Next.js 13.4.8.

**Comment by studentIvan** [comment]
13.4.9 issue still exists. Only after the build though

**Comment by mrwithersea** [comment]
Experiencing the same behaviour, styles are missing from the page until the page is refreshed; working as expected in dev, not in build. We have used a pattern of defining a loading variant of our components that utilise the same styles and so share a CSS module file, the loading.tsx imports the loading variant of the component, page.tsx imports the default variant. Where we `prefetch` on a `Link` to a page so that the loading.tsx is not required styles are applied as expected.

**Comment by nitinTJ** [comment]
This issue is still present in next 13.4.16.

**Comment by Xuandong95** [comment]
Prefetch can be disabled by passing `prefetch={false}`. you might try it. This configuration solves my problem
.https://nextjs.org/docs/app/api-reference/components/link#prefetch

**Comment by BalajiSriraman** [comment]
This issue exists in next v14.0.1 too!
tailwind css doesnt load in dynamic routes [app router]
@ztanner could you pls look into this issue!
