### ISSUE TITLE
Modal intercept/parallel routes clash when intercepting from different routes

### ISSUE THREAD

**Issue by resthedev** [vercel/next.js#49878]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/nextjs-clashing-intercept-routes-7fb9i9?file=/app/page.tsx:1,1

### To Reproduce

Do the following within the root URL of the sandbox (aka `/` route). This is also accessible by the **Home** link.
1. Click **foo** link.
2. Click **Post 1** link (within the Foo Page). Note that it says `[Intercepted on Foo Page]`. 
3. Click outside the modal to go back and close it.
4. Click **home** link.
5. Click **bar** link.
6. Click **Post** link (within the Bar page). Note that it **incorrectly** says `[Intercepted on Foo Page]`.

### Describe the Bug

When intercepting the _same_ route from within _different_ routes, the intercepting clashes and the wrong pages/slots are rendered. 

The behavior seems to change depending on the order of the intercepting. 

### Expected Behavior

Being able to intercept the same route from within different routes and rendering the correct content.

<sub>[NEXT-1818](https://linear.app/vercel/issue/NEXT-1818/modal-interceptparallel-routes-clash-when-intercepting-from-different)</sub>

**Comment by prodbygoss** [comment]
Bump — still having this issue.

**Comment by resthedev** [comment]
> I have just reported a somewhat similar case: https://github.com/vercel/next.js/issues/53170. It uses route groups, but the root cause of the bug might be the same.

Thanks for letting me know! I checked the other Issues you referenced as well, and I'm sort of relieved that I'm not the only one having this issue. Hopefully it's brought to the attention of the team.

**Comment by kachkaev** [comment]
Yeah I also hope that this issue will be addressed soon. When I was trying to configure an intercepting route next to a normal route for something like `/photos/[id]`, I was beating against the wall for a few hours. I was confident that a bug like that just could not exist and it was me not understanding the docs or being stupid in some other way.

Only after creating a clear reproduction for https://github.com/vercel/next.js/issues/53170, it became apparent to me that it was an issue in Next.js, not in my head 😅 It was tough but I am relieved too now!

**Comment by resthedev** [comment]
Bump — still facing this issue and it is a pretty critical bug.

**Comment by resthedev** [comment]
Bump

**Comment by resthedev** [comment]
Bump

**Comment by resthedev** [comment]
> Yeah I also hope that this issue will be addressed soon. When I was trying to configure an intercepting route next to a normal route for something like `/photo/[id]`, I ended up beating against the wall for a few hours. I was confident that a bug like that just could not exist and it was me not understanding the docs or being stupid in some other way.
> 
> Only after creating a clear reproduction for #53170, it became apparent that it was an issue in Next.js, not in my head 😅 Tough times but I am relieved now too!

Wondering if you've been able to work around the issue on your end. I have unfortunately not heard back from the team about this issue, so I'm quite tempted to just scrap the whole modal intercept/parallel routing and just implement this all in traditional state (which would be a bummer since this feature was a big reason I migrated to NextJS `app` directory).
