### ISSUE TITLE
Docs: The 'Using app/pages router' selector sometimes does not work

### ISSUE THREAD

**Issue by arjenbloemsma** [vercel/next.js#49870]
### What is the improvement or update you wish to see?

Sometimes the selector button for choosing between the pages and app router, which is present in the left menu just below the search box (so on all pages), seems to get crazy. The dropdown disappears as soon as it pops up, making it impossible to select. See attached clip.

Since it occurs in the docs, but is a UI issue I'll also add my system info here.

    Browser: Safari Version 16.4 (18615.1.26.110.1)
    OS: macOS Ventura 13.3.1 (a) (22E772610a)

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4

It is hard to reproduce, but happend a couple of times in the last week. 

### Is there any context that might help us understand?

https://github.com/vercel/next.js/assets/8061052/57600c82-339f-4efa-b0f0-d5a289a2d2f5

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs

**Comment by leerob** [comment]
I can't reproduce, but please let me know if you are still seeing this.
