### ISSUE TITLE
Docs: Edge functions link is broken

### ISSUE THREAD

**Issue by adamalston** [vercel/next.js#49886]
### What is the improvement or update you wish to see?

In a section of the Next.js docs that goes over how Next.js works on the edge, there is the following paragraph:

> By moving some work that was traditionally done client-side or server-side to the Edge, you can make your application more performant because it reduces the amount of code sent to the client, and part of the user's request does not have to go all the way back to the origin server - thus reducing latency. [See Edge examples with Next.js here](https://vercel.com/features/edge-functions#:~:text=or%20steps%20required.-,CODE%20EXAMPLES,-Unlock%20the%20potential).

An error is shown on the linked page.

### Is there any context that might help us understand?

![edge-functions](https://github.com/vercel/next.js/assets/18297826/4bec6996-f2cd-4b42-ae43-ebc953fb6dc1)

**Comment by arjenbloemsma** [comment]
Hi @adamalston, can you please post the url of the page where this link appears on?

**Comment by adamalston** [comment]
Hi @arjenbloemsma, the URL is https://nextjs.org/learn/foundations/how-nextjs-works/cdns-and-edge.

**Comment by delbaoliveira** [comment]
Thank you for reporting this @adamalston, it'll be fixed shortly. The link should go to [the examples on this page](https://vercel.com/features/edge-functions#:~:text=Unlock%20the%20potential%20of%20edge%20computing).
