### ISSUE TITLE
"You have a Server Component that imports next/router. Use next/navigation instead." error doesnt respect async imports

### ISSUE THREAD

**Issue by mPaella** [vercel/next.js#49887]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.3-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Dynamic imports (next/dynamic), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/dry-haze-40tool?file=%2Futils%2FoldRouter.tsx%3A8%2C1

### To Reproduce

Use an async import in a server component, which itself imports something from `next/router`

You will see the "ReactServerComponentsError" "You have a Server Component that imports next/router. Use next/navigation instead." error.

### Describe the Bug

This ReactServerComponentsError throws during compilation instead of runtime, not respecting dynamic imports

This could be considered a positive.... as it guarantees you wont import from "next/router", but its a bit of a pain point migrating from pages router.

### Expected Behavior

**For async imports**, the error should be thrown at runtime. As a dev, im 100% certain the code containing the import from "next/router" will not be imported/ran. So, having this throw at import/runtime would fix this problem.

**For non async imports**, a compilation time error is fine.

**Comment by shuding** [comment]
The compile-time check is a quick way to avoid obvious mistakes and help people migrating their code, but it's not designed to be a guard to check the runtime code. Similarly you can't do `import { useState } from 'react'` in RSC, but Next.js allows you to run `const isRSC = !!require('react').useState` as a way to "opt-out compilation check" and it's almost a valid use case.
