### ISSUE TITLE
Docs: App Router Link Section is outdated

### ISSUE THREAD

**Issue by Makisuo** [vercel/next.js#49921]
### What is the improvement or update you wish to see?

<img width="648" alt="image" src="https://github.com/vercel/next.js/assets/31933546/8f1a2ad0-a3ae-4ded-bca1-091be3c10c0e">

This doesn't work anymore in the app router with <Link> and should be removed

### Is there any context that might help us understand?

When using the new nextjs app router it's not possible anymore to use dynamic href for <Link>. Would be possible to replace this section with a generic example of how to just use href and replace to achieve the same.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/components/link#with-url-object

**Comment by delbaoliveira** [comment]
Thank you for reporting this @Makisuo, this will be updated shortly 🙏🏼
