### ISSUE TITLE
res.revalidate fails through middleware, revalidatePath for dynamic routes

### ISSUE THREAD

**Issue by jwalcher** [vercel/next.js#49955]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/jwalcher/revalidation

### To Reproduce

- execute `yarn run build`, `yarn run start`, navigate to `localhost:3000/?lang=[lang]` where `[lang]` is one of `en,de,fr`
- navigate to `localhost:3000/handler/revalidate?lang=[lang]` and back to `localhost:3000/?lang=[lang]`, refresh multiple times and check whether content updates
- navigate to `localhost:3000/api/revalidate?lang=[lang]` and back to `localhost:3000/?lang=[lang]`, check whether content updates, and console for errors
- note that the code includes a `middleware.ts` which rewrites the `/?lang=[lang]` queries with the `/[lang]` route
- also note that `/fr` is a static route, while `/en` and `/de` are dynamically generated at build time using `generateStaticParams()`

### Describe the Bug

- `localhost:3000/handler/revalidate?lang=[lang]` is a route handler in the App directory that calls `revalidatePath(/[lang])`. Revalidation is successful when `[lang]` is `fr` which is a static route, but does nothing when `[lang]` is one of `en,de` which are dynamically generated at build time using `generateStaticParams()` 
- In fact, even on the static route, the page shows updated content only at the second refresh. It appears that the first refresh only revalidates the fetch-cache, but does not rebuild the page itself. This is unlikely intentional.
- `localhost:3000/api/revalidate?lang=[lang]` is an api route in the Pages directory that calls `res.revalidate(/[lang])`, throwing an `Error: Invalid response 500 at NextNodeServer.revalidate`. This error does not appear, and revalidation is successful, when middleware is deactivated for all the routes.

### Expected Behavior

- `revalidatePath` should work on both static and dynamically generated routes and should immediately rebuild the page on first refresh.
- `res.revalidate` should not be passed through middleware. (I think this was indeed so until v13.3.0, when my revalidation strategy in the pages directory worked fine.)

**Comment by daszkowski** [comment]
Have same error (at next@13.4.2) - Package subpath './server.edge' is not defined by "exports" - for On-demand Revalidation using res.revalidate([url])

**Comment by nabildroid** [comment]
same this, ISR is useless without on-demand revalidation

**Comment by jwalcher** [comment]
Not sure what y'all think, but my description of the issue might be too opaque. I'm going to close it and reopen something more specific.

**Comment by jwalcher** [comment]
My description of the issue might be too opaque. I'm closing and reopening something more specific.

**Comment by daszkowski** [comment]
@jwalcher - thx for info - leave a link to new issue - I will follow up topic

**Comment by jwalcher** [comment]
@daszkowski the new issue is at https://github.com/vercel/next.js/issues/50464 Perhaps some upvotes will catch attention
