### ISSUE TITLE
[NEXT-1210] 'Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".   [function]' when no client components in entire application. 

### ISSUE THREAD

**Issue by jmarks-joshua** [vercel/next.js#49983]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 20.1.0
      npm: N/A
      Yarn: N/A
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.3-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue

https://github.com/jmarks-joshua/next-bad-error

### To Reproduce

1. Download repo
2. run `npm install`
3. run `npm run dev`
4. go to localhost:3000
5. See error on console
6. press only button on screen
7. see error on screen

### Describe the Bug

The bug is just that the error message resulting from a component with a server action that uses non-serializable closure or arguments. The error message produced says "Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server"." When I didn't have a single Client Component in the entire application.

### Expected Behavior

I think it should say something more like "Functions cannot be passed directly to Server Actions. All arguments and used closure  must be serializable."

So firstly I think the error message is wrong, but also that the documentation around Server Actions needs to talk about how closures work with server actions. From a different error message I was able to figure out that variables from the Component closure that are used in a server function, are secretly passed down as function parameters. So for me this error was happening when as far as I knew I wasn't passing any non-serializable arguments, but in reality I was because of behind the scenes magic.

<sub>[NEXT-1210](https://linear.app/vercel/issue/NEXT-1210/error-functions-cannot-be-passed-directly-to-client-components-unless)</sub>

**Comment by shuding** [comment]
Hi! The problem here is that you're referencing a function, `getData`, inside the Action that isn't serializable:

```js
  const getData = () => 'Test'

  const formAction = async () => {
    'use server'
    const name = getData()
  }
```

There're two ways to fix it. You can put it inside the Action:

```js
  const formAction = async () => {
    'use server'
    const getData = () => 'Test'
    const name = getData()
  }
```

Or make it another Action:


```js
  const getData = async () => {
    'use server'
    return 'Test'
  }

  const formAction = async () => {
    'use server'
    const name = getData()
  }
```

I reported to the React team so we can make this error cleaner, thanks!

**Comment by jmarks-joshua** [comment]
Isn't that exactly what I said in the description and the expected behaviour? Once I figured out what was happening it was obvious why and how to fix it, but the error message had me going down the wrong path for a long time because it has absolutely nothing to do with the actual cause of the problem. 

And also that there's nothing in the documentation about closures used having to be serialisable as well, which I think would make all of this a lot clearer.
