### ISSUE TITLE
Docs:  Nextjs  showing broken image or not showing properly

### ISSUE THREAD

**Issue by Junaid300** [vercel/next.js#49989]
### What is the improvement or update you wish to see?

Nextjs Images should show properly, as expected. It is not related to size or width.

### Is there any context that might help us understand?
I think it is not related to doc, but From couple of days i have slow internet and some times Nextjs show. I have attached two screenshot one is from Nextjs documentation and is from kent c dodds site. I have seen this behavior couple times. 

![Screenshot from 2023-05-18 16-40-24](https://github.com/vercel/next.js/assets/66414908/4edd0e73-8119-4fcf-a92c-19e36d530e3d)
 broken image.

![Screenshot from 2023-05-18 16-41-37](https://github.com/vercel/next.js/assets/66414908/06bf45c6-7515-405f-ae0a-3c447821bb49)

**Comment by leerob** [comment]
Hey there, I can't reproduce this. Unfortunately I'm not sure the issue you're seeing, but I don't believe it's from the site 🙏
