### ISSUE TITLE
Throwing ApiError in API routes always return status code 500.

### ISSUE THREAD

**Issue by cgps-admin** [vercel/next.js#49999]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.3-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/modest-pine-2g3w3d

### To Reproduce

* add an API route
* import `ApiError` from `next/dist/server/api-utils`
* throw as error using `throw new ApiError(400, 'error')`
* call the API route

### Describe the Bug

The code for an API route is being inlined.
In this example (https://codesandbox.io/p/sandbox/modest-pine-2g3w3d) the file `.next/server/pages/api/hello.js` includes an inline copy of `node_modules/next/dist/server/api-utils/index.js` which redefines the class `ApiError`.
This means that the error is no longer an instanceof `ApiError` (because it is an instance of the redefined class) causing this line to always be false:  https://github.com/vercel/next.js/blob/c7e5d767177b862506648fa87d96e80b7c358719/packages/next/src/server/api-utils/node.ts#L640

### Expected Behavior

I expect the thrown error to be catched by this line 
 https://github.com/vercel/next.js/blob/c7e5d767177b862506648fa87d96e80b7c358719/packages/next/src/server/api-utils/node.ts#L640 and a 400 status code is returned, however status code 500 is being returned by this line https://github.com/vercel/next.js/blob/c7e5d767177b862506648fa87d96e80b7c358719/packages/next/src/server/api-utils/node.ts#LL654C1-L654C1

**Comment by balazsorban44** [comment]
> import ApiError from next/dist/server/api-utils

This API is private/undocumented and not intended for the user to import it.
