### ISSUE TITLE
[GITHUB ACTIONS] All PR's are failing if package.json contains a change

### ISSUE THREAD

**Issue by dvakatsiienko** [vercel/next.js#49997]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.0
      npm: 9.6.6
      Yarn: 1.22.19
      pnpm: 7.24.3
    Relevant packages:
      next: 13.4.3-canary.2
      eslint-config-next: 13.4.3-canary.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.2
```

### Which example does this report relate to?

Multiple: with-redux, with-algolia-react-instantsearch, with-storybook, app-dir-progressive-web-app and others

### Describe the Bug

**A Socket Security: Pull Request Alerts** step fails for multiple PR's that include **examples** changes.

**PR's with broken CI**:
- [upgrade with-redux to app router](https://github.com/vercel/next.js/pull/49994) | [ACTUAL ISSUE](https://github.com/vercel/next.js/pull/49994/checks?check_run_id=13581495697)
- [upgrade with-alogila example](https://github.com/vercel/next.js/pull/49939) | [ACTUAL ISSUE](https://github.com/vercel/next.js/pull/49939/checks?check_run_id=13554510679)
- [upgrade with-storybook example](https://github.com/vercel/next.js/pull/49863) | [ACTUAL ISSUE](https://github.com/vercel/next.js/pull/49863/checks?check_run_id=13521618709)
- [upgrade with-storybook example](https://github.com/vercel/next.js/pull/49065) | [ACTUAL ISSUE](https://github.com/vercel/next.js/pull/49065/checks?check_run_id=13160839904)

There are multiple different reasons of fail:
- **This pull request alert report failed to run. This can sometimes be due to an error with GitHub's API, Socket's API or a bug in the bot. You can try to re-run the report at any time.**
- **This pull request alert report was aborted or timed out while running. You can try to re-run the report at any time.**

Step re-runs does not work — the same issue is observed again and again.
I've tried to re-create PR but still same issue with **Socket Security** step.

My assumption is that the fail is initiated by presence of package updates in **package.json**. Because, for instance, in [with-facebook-pixel](https://github.com/vercel/next.js/pull/49880) example PR update the ***Socket Security: Pull Request Alerts** check passes, but there are no changes in **package.json**.

### Expected Behavior

Step should pass without failing due to internal issues.

### To Reproduce

Open a pull request with example update for **examples** directory.

**Comment by balazsorban44** [comment]
I'm closing it as per the comment put out by the github action: "This pull request alert report failed to run. This can sometimes be due to an error with GitHub's API, Socket's API or a bug in the bot. You can try to re-run the report at any time."

It's been a while and this did not show up as an issue. Will keep an eye for it.
