### ISSUE TITLE
No Script Tags In Head Component Error

### ISSUE THREAD

**Issue by ashby-dev** [vercel/next.js#50015]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.2
      eslint-config-next: 13.1.2
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

with-google-analytics

### Describe the Bug

Example is using a <script> tag within the next/head <Head> tag; flags an error to instead use a next/script <Script> tag instead.

### Expected Behavior

Clear directions on how to implement the google analytics script tag within the _app.js document.

### To Reproduce

Open browser console.

**Comment by leerob** [comment]
This example was recently updated, thank you!
