### ISSUE TITLE
Rewrites from next.config.js are double proxied in Next >=13.3.0

### ISSUE THREAD

**Issue by caleblloyd** [vercel/next.js#50017]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next info


    Operating System:
      Platform: linux
      Arch: x64
      Version: #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.15
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/caleblloyd/nextjs-double-proxy-bug

### To Reproduce

[Clone this repo](https://github.com/caleblloyd/nextjs-double-proxy-bug) or do it in your own next app with:

`next.config.js`:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async rewrites() {
    return [
      {
        source: '/api/:path*',
        destination: `http://localhost:3001/api/:path*`,
      }
    ]
  },
}

module.exports = nextConfig
```

`express.js`:

```
const express = require('express')
const app = express()

// respond with "hello world" when a GET request is made to the homepage
app.get('**', (req, res) => {
  res.send(`
x-forwarded-for:   ${req.headers["x-forwarded-for"]}
x-forwarded-port:  ${req.headers["x-forwarded-port"]}
x-forwarded-proto: ${req.headers["x-forwarded-proto"]}
`.trimStart())
})

app.listen(3001, undefined, () => {
    console.log("listening on :3001")
})
```

NextJS versions >=13.3.0 double-proxy rewrites in `next.config.js`

1. run `node express.js` to start a server on Port 3001
2. run `npm run dev` to start NextJS on Port 3000
3. Run `curl http://localhost:3000/api/test`

### Describe the Bug

Rewrites in the `next.config.js` file are being proxied twice in Next >=13.3.0 resulting in comma-delimited `X-Forwarded-` headers

Next >= 13.3.0

```
x-forwarded-for:   ::ffff:127.0.0.1,::ffff:127.0.0.1
x-forwarded-port:  3000,3000
x-forwarded-proto: http,http
```

### Expected Behavior

Only proxy once, producing a single `X-Forwarded-` header

Next < 13.3.0

```
x-forwarded-for:   ::ffff:127.0.0.1
x-forwarded-port:  3000
x-forwarded-proto: http
```

**Comment by ahmed-adly-khalil** [comment]
follow

**Comment by caleblloyd** [comment]
@nctay I don't think it is fixed.  I upgraded my recreate repo to `13.4.4` then to `13.4.5-canary.0` and the issue is still present

**Comment by MattElcock** [comment]
This is still an issue on `13.4.4`:

```
x-forwarded-for: ::1,::ffff:127.0.0.1
x-forwarded-port: 3000,3000
x-forwarded-proto: http,http
x-forwarded-host: localhost:3000
```

**Comment by ivanhueso** [comment]
I see the same issue

**Comment by caleblloyd** [comment]
So it seems that this may be by-design.

In the `server-start.ts` file, there is a setting called `useWorkers` now which is the default when running `next dev`.  It adds another proxy to a local server here:

https://github.com/vercel/next.js/blob/b714ac55c113bbb387b2501ec968028a2637acb4/packages/next/src/server/lib/start-server.ts#L251-L262

This would probably be fine, except there are some non-standard headers that result from this 2nd layer of proxying that can break downstream parses.

The `http-proxy` library, which does the proxying, [includes comma-delimited values](https://github.com/http-party/node-http-proxy/blob/335aeeba2f0c286dc89c402eeb76af47834c89a3/lib/http-proxy/passes/web-incoming.js#L78-L83) for `X-Forwarded-Proto` and `X-Forwarded-Port`.

Although they are non-standard headers, [MDN specifies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) that `X-Forwarded-Proto` is:

> The forwarded protocol (http or https)

Some Downstream parsers will read `X-Forwarded-Proto`  will look for `http` or `https` here, but NextJS is now passing `http,http`

It is unlikely that `http-proxy` will update this behavior - it has been 3 years since the ast release, and the header is non-standard anyways so there is no RFC to point to for compliance.

This header is superseded by [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) anyways, which has a clear RFC.

Maybe NextJS can eventually switch to another proxy implementation that supports `Forwarded`

**Comment by caleblloyd** [comment]
I will close this now, as it is clear the double-proxy behavior is a result of the Workers implementation.  Therefore the double `X-Forwarded-For` header is needed to be able to see the original Client IP

**Comment by sailor** [comment]
Hey @caleblloyd, i do agree that `X-Forwarded-For` should include all the IP addresses from every proxies and the user IP at the very end. But it seems that the `X-Forwarded-Proto` should only contain one value and not `https,http` when using SSL. Is there something i'm missing?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

**Comment by caleblloyd** [comment]
That's my expectation too, but `X-Forwarded-Proto` is a non-standard header so there is no definitive answer. [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) is a standard header, maybe one day years from now all proxies and middlewares will support it :smile:

**Comment by sailor** [comment]
Hey @MattElcock another issue has been opened there: https://github.com/vercel/next.js/issues/52266
(as this one is closed)
