### ISSUE TITLE
useSearchParams with JavaScript disabled results in pages being rendered empty

### ISSUE THREAD

**Issue by codinginflow** [vercel/next.js#50029]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/silly-northcutt-v9pvrn?file=%2Fapp%2Flayout.tsx%3A10%2C27

### To Reproduce

1. Create a client component that makes use of `useSearchParams`.
2. Put this client component into your root `layout`
3. Build the project and run it with `npm start`
4. Disable JavaScript in the browser and open a page. The page will be empty.

Not only the page that uses the search params doesn't render, but also its **siblings**.

Check the codesandbox I provided for a simple example. Make sure to **build** and **run** the project (not dev mode). You can disable JavaScript in your Chrome dev tools and use the on-page links to navigate between pages.

To disable JavaScript, open the Chrome dev tools with F12. Then hit Ctrl + Shift + P and search for "Disable JavaScript".

The problem goes away when you wrap the component that uses `useSearchParams` into a `Suspense` boundary.

### Describe the Bug

Using `useSearchParams` in a client component and disabling JavaScript in the browser causes sibling components to not be rendered (after building the project) unless you wrap the component that uses `useSearchParams` into a `Suspense` boundary.

### Expected Behavior

Pages should render without JavaScript enabled. This is important for SEO.

### Which browser are you using? (if relevant)

Google Chrome

### How are you deploying your application? (if relevant)

locally and Vercel

**Comment by shuding** [comment]
This should be the expected behavior. When `useSearchParams()` is used, the entire part will be fully client-side rendered. Related docs: https://nextjs.org/docs/app/api-reference/functions/use-search-params#static-rendering

**Comment by codinginflow** [comment]
I saw that in the docs but I thought the page was still prepopulated on the server (like client components).

This seems like an immense foot gun. Wherever you use search params client-side, you have to remember to wrap that section into a Suspense boundary, otherwise your page becomes invisible to crawlers.

**Comment by codinginflow** [comment]
Also, this behavior seems inconsistent. I have another page that uses `useSearchParams` and it renders just fine without JavaScript.

**Comment by codinginflow** [comment]
> The main reason is that we can't predict search params during SSR. There're two choices, one is to make that page always server-rendered on every request which isn't ideal. Another choice is to have `useSearchParams()` supported during SSR, but always return an empty object (the previous `pages/` behavior), but that causes hydration every time.

But I don't understand why a component using `useSearchParams` would cause a static **sibling** page to not be rendered. The static page doesn't need to know about the params at compile-time. I only use them at runtime in that other component.
