### ISSUE TITLE
Docs: Dynamic Routes section uses an outdated way to import remark-html 

### ISSUE THREAD

**Issue by JHunnicutt** [vercel/next.js#50037]
### What is the improvement or update you wish to see?

The page on rendering markdown gives instructions on using remark and remark-html. The example import for remark-html is outdated and incorrect. 

It lists:
```
import html from 'remark-html';
```

It should be:
```
import remarkHtml from 'remark-html'
```

Further more, the function that uses remark-html should be rewritten as well.
```
const processedContent = await remark()
  // the line below has been updated
  .use(remark-html)
  .process(matterResult.content);
const contentHtml = processedContent.toString();
```

[Source](https://github.com/remarkjs/remark-html)

### Is there any context that might help us understand?

People new to Nextjs may run into issue at this point when their code fails to work, and will be unsure why. However, they may be encouraged to check the remark docs when following along, as the auto-complete doesn't show the same code as the example.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/dynamic-routes/render-markdown

**Comment by balazsorban44** [comment]
Hi, this seems to be stylistic changes, and different variable names, and should not affect how the code works. Note that default imports can be named anything.
