### ISSUE TITLE
Docs: Broken link when navigating to `intercepting-routes ` from `parallel routes` in the next.js docs

### ISSUE THREAD

**Issue by nzaih1999** [vercel/next.js#50038]
### What is the improvement or update you wish to see?

The url from the docs should be changed from `https://nextjs.org/docs/app/routing/intercepting-routes` to `https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes` 

### Is there any context that might help us understand?

not working(`url from parallel routes page in docs`) : [https://nextjs.org/docs/app/routing/intercepting-routes](https://nextjs.org/docs/app/routing/intercepting-routes`)

working : [https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes)](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes) 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/routing/intercepting-routes

**Comment by kachkaev** [comment]
Hmm, seeing 500 here: https://nextjs.org/docs/app/routing/intercepting-routes

<img width="793" alt="Screenshot 2023-07-25 at 19 19 53" src="https://github.com/vercel/next.js/assets/608862/8f100154-e4ca-4a64-84c7-85f1784abde3">

https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes works
