### ISSUE TITLE
`providers.tsx` not working as expected.

### ISSUE THREAD

**Issue by noneloop** [vercel/next.js#50030]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3-canary.3
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4

I have tried different environments and none of the following environments and versions work properly.
OS: Windows, WSL, Github Codespace
Node versions: 18, 20
React and ReactDOM: 18.2.0
Next versions: 13.x (with App Router)
Compiler: Webpack, Turbopack
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/noneloop/my-app

### To Reproduce

1. Create Next App
    ```
    ~$ npx create-next-app
    ✔ What is your project named? … (my-app)
    ✔ Would you like to use TypeScript with this project? … No / (Yes)
    ✔ Would you like to use ESLint with this project? … No / (Yes)
    ✔ Would you like to use Tailwind CSS with this project? … No / (Yes)
    ✔ Would you like to use `src/` directory with this project? … (No) / Yes
    ✔ Use App Router (recommended)? … No / (Yes)
    ✔ Would you like to customize the default import alias? … (No) / Yes
    ```
2. Install NextUI
    ```
    ~/my-app$ npm install @nextui-org/react
    ```
3. Delete all the files in `app/`
4. Add `app/providers.tsx` with code:
    ```tsx
    "use client";

    import {NextUIProvider} from "@nextui-org/react";

    export function Providers({children}: {children: React.ReactNode}) {
      return <NextUIProvider>{children}</NextUIProvider>;
    }
    ```
5. Add `app/layout.tsx` with code:
    ```tsx
    import {Providers} from "./providers";

    export default function RootLayout({
      children,
    }: {
      children: React.ReactNode
    }) {
      return (
        <html lang="en">
          <body><Providers>{children}</Providers></body>
        </html>
      )
    }
    ```
6. Add `app/page.tsx` with code:
    ```tsx
    import {Button} from "@nextui-org/react";

    export default function RootPage() {
      return (
        <>
          <Button>Hello</Button>
        </>
      );
    }
    ```
Now run dev server with `npm run dev`, you will get an error message in browser:
   > You're importing a component that needs useState. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.

This page works fine when `use client` is added to the `page.tsx`.

### Describe the Bug

Use [client components <providers.tsx>](https://nextjs.org/docs/getting-started/react-essentials#rendering-third-party-context-providers-in-server-components)
for third party context providers in server components.  
It is not working as expected.

### Expected Behavior

Import any Client Components directly in Server Components without adding `use client` to `page.tsx`.

**Comment by VaniaPopovic** [comment]
To me it seems that NextUI's button https://github.com/nextui-org/nextui/blob/main/packages/react/src/button/button.tsx is using use-hooks undearneath. Namely there are imports to React's useMemo. That means that the component hosting this <Button /> component will need to be a client component, and will need to include the "use client" directive at the top.
