### ISSUE TITLE
[NEXT-1217] Auto deduping doesn't work with revalidate = 0

### ISSUE THREAD

**Issue by codinginflow** [vercel/next.js#50031]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/epic-darwin-t78er9?file=%2Fapp%2Fpage.tsx%3A6%2C1

### To Reproduce

1. Create a server component that fetches the same data both in the Page and in `generateMetadata`
2. Make the page dynamic by exporting `const revalidate = 0`
3. Run the project, the data is fetched twice

### Describe the Bug

The app router docs say that fetch is automatically deduped in server components and no use of React's `cache` function is necessary whatsoever. This is not true for dynamic pages that use `revalidate = 0`.

### Expected Behavior

The request should be deduped and only one request to the data source should be made.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

locally, Vercel

<sub>[NEXT-1217](https://linear.app/vercel/issue/NEXT-1217/auto-deduping-doesnt-work-with-revalidate-=-0)</sub>

**Comment by ijjk** [comment]
There's seems to be an issue with the react fetch wrapping being reset unexpectedly so when Next.js fetch caching is skipped the fetch de-duping isn't being applied

x-ref: [thread](https://vercel.slack.com/archives/C042LHPJ1NX/p1684518670927189?thread_ts=1682974724.765039&cid=C042LHPJ1NX)

**Comment by ijjk** [comment]
Hi, this has been updated in `13.4.4-canary.2` of Next.js, please update and give it a try!

**Comment by codinginflow** [comment]
Thank you for the clarification and fix!
