### ISSUE TITLE
Typescript error in the with-mongodb example

### ISSUE THREAD

**Issue by jakekugel** [vercel/next.js#50084]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.6.3
```

### Which example does this report relate to?

with-mongodb

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

n/a

### Describe the Bug

When I try to build the with-mongodb example using `npm run build`, the build fails with this typescript error:

```
./pages/index.tsx:5:42
Type error: Parameter 'context' implicitly has an 'any' type.

  3 | import { InferGetServerSidePropsType } from 'next'
  4 |
> 5 | export async function getServerSideProps(context) {
    |                                          ^
  6 |   try {
  7 |     await clientPromise
  8 |     // `await clientPromise` will use the default database passed in the MONGODB_URI
```

### Expected Behavior

The example should build successfully.

### To Reproduce

The issue can be reproduced with these three commands:

```
npx create-next-app --example with-mongodb myapp
cd myapp
npm run build
```

**Comment by ibrahemid** [comment]
Hello @jakekugel, can i create a pull for this issue ?

**Comment by jakekugel** [comment]
Thank you @ibrahemid that would be much appreciated if you created a pull.
