### ISSUE TITLE
Web APIs Cache not working in Vercel Edge Middleware – typeof `caches` is `undefined`

### ISSUE THREAD

**Issue by awinogrodzki** [vercel/next.js#50102]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://app.replay.io/recording/untitled--a18f4a73-07a1-49a7-94ec-6400bf8094ae

### To Reproduce

Issue is not reproducible locally or in Node.js environments, where `caches` is always present

Issue happens only inside Vercel Edge Middleware

Can be reproduced by deploying app with following `middleware.ts`:

```typescript
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export async function middleware(request: NextRequest) {
  console.log({
    typeofCaches: typeof caches, // "undefined"
    globalTypeofCaches: typeof global.caches, // "undefined"
  });
  return NextResponse.next();
}

export const config = {
  matcher: ["/", "/((?!_next/static|favicon.ico).*)"],
};
```

### Describe the Bug

Global `caches` property is `undefined` when trying to access it from `middleware.ts/js` inside Vercel Edge Middleware runtime.

Here are logs from Edge Middleware. `typeof caches` and `typeof global.caches` yields `undefined`

<img width="560" alt="Screenshot 2023-05-20 at 20 18 17" src="https://github.com/vercel/next.js/assets/12574743/f3f4eb1e-5f8d-4c03-87b3-5087a41d75af">

When running locally or inside remote Node.js environment, `caches` is present and middleware works fine

And here are logs from Next.js Serverless Function, where `caches` are present:

<img width="550" alt="Screenshot 2023-05-20 at 20 19 32" src="https://github.com/vercel/next.js/assets/12574743/0bbfe7e2-20e7-415f-a7e8-d5db5065da57">

### Expected Behavior

`caches` and `global.caches` inside Vercel Edge Middleware runtime is present and exposes [Web APIs CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/Cache)

### Which browser are you using? (if relevant)

Version 113.0.5672.126 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

**Comment by awinogrodzki** [comment]
I see that `caches` has been removed from `@edge-runtime/primitives@2.1.3`

> Edge Functions doesn't support it these days, so better to drop to keep 1:1 with production scenario

https://github.com/vercel/edge-runtime/pull/281 

I understand that middleware runs inside Edge Function that does not have access to `CacheStorage`.

Is there a way to cache fetch requests made from middleware? Probably better description of my use case would be helpful:

I work on Edge Runtime compatible Firebase Authentication library https://github.com/awinogrodzki/next-firebase-auth-edge


In middleware, before I validate user using `RequestCookies`, I have to fetch Google x509 certificates from `https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com`. I need those certificates to act as public key, which I then verify token against.

Those certificates have expiry date, which means I cannot load them during build time.

I would like to cache either response or certificates between multiple middleware requests, otherwise I have to call googleapis each time a request is made.

The only solution I can come up with is by setting up proxy API route to fetch Google certificates and return them with correct Cache-Control headers. This does not suit my use-case well. At the moment, single point of configuration for my library is `middleware.ts` file and forcing users to add separate files would introduce another layer of complexity to maintain.

Please let me know if you have any suggestions or follow up questions

**Comment by JannikZed** [comment]
I think a lot of people just did not notice this problem yet. We also just came across it when validating JWTs using JWKS.. this adds a lot of delay to the TTFB and is very unexpected. Shouldn't be a problem to have the vercel internal cache available in the middleware ...

**Comment by awinogrodzki** [comment]
After some recent experiments, I noticed that you can now create a global `Map` object shared between multiple requests in `Edge runtime`. 

This basically solves the caching problem in middleware.

**Comment by emmgfx** [comment]
> After some recent experiments, I noticed that you can now create a global `Map` object shared between multiple requests in `Edge runtime`.
> 
> This basically solves the caching problem in middleware.

Could you explain this more on detail? Thanks!

**Comment by awinogrodzki** [comment]
@emmgfx, sure!

Let's consider following Middleware example:

```tsx
let cachedResult = null;

async function fetchSomething() {
  if (cachedResult) {
     return cachedResult;
  }

  const response = await fetch('some-api-url', { headers: { Accept: 'application/json' } });

  if (!response.ok) {
     throw new Error('Oops!');
  }

  cachedResult = await response.json();

  return cachedResult ;
}

export async function middleware(request) {
  const result = await fetchSomething();
}
```

When I reported the issue, each middleware execution was called in separate `global` context, which means that `cachedResult` was always `null` for subsequent requests

I assumed this was due to Vercel's Edge Function architecture, and since we're in an Edge Runtime, it would make sense to use (Web APIs Cache)[https://developer.mozilla.org/en-US/docs/Web/API/Cache] for this scenario. But Web APIs Cache was not supported by Edge Runtime and I was left with no options to cache the result of `fetch` call.

After some recent testing, it seems that now, subsequent requests share the same global context. Which means that `cachedResult` variable is shared between multiple requests and we can use this to cache repeated `fetch` requests result.

**Comment by emmgfx** [comment]
> @emmgfx, sure!
> 
> Let's consider following Middleware example:
> 
> ```tsx
> let cachedResult = null;
> 
> async function fetchSomething() {
>   if (cachedResult) {
>      return cachedResult;
>   }
> 
>   const response = await fetch('some-api-url', { headers: { Accept: 'application/json' } });
> 
>   if (!response.ok) {
>      throw new Error('Oops!');
>   }
> 
>   cachedResult = await response.json();
> 
>   return cachedResult ;
> }
> 
> export async function middleware(request) {
>   const result = await fetchSomething();
> }
> ```
> 
> When I reported the issue, each middleware execution was called in separate `global` context, which means that `cachedResult` was always `null` for subsequent requests
> 
> I assumed this was due to Vercel's Edge Function architecture, and since we're in an Edge Runtime, it would make sense to use [Web APIs Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache) for this scenario. But Web APIs Cache was not supported in Edge Runtime and I was left with no options to cache the result of `fetch` call.
> 
> After some recent testing, it seems that now, subsequent requests share the same global context. Which means that `cachedResult` variable is shared between multiple requests and we can use this to cache repeated `fetch` requests result.

I think that I understand. But then you are not exactly "caching", you are storing the result in a variable and the variable isn't cleaned between executions, right? Then, you can have some troubles revalidating?

**Comment by awinogrodzki** [comment]
> I think that I understand. But then you are not exactly "caching", you are storing the result in a variable and the variable isn't cleaned between executions, right? Then, you can have some troubles revalidating?

The example I provided is a simplification.

Here is implementation in `next-firebase-auth-edge` library: https://github.com/awinogrodzki/next-firebase-auth-edge/blob/main/src/auth/signature-verifier.ts#L119

```tsx
const keyResponseCache: Map<string, PublicKeysResponse> = new Map();
```

```tsx
  private async fetchAndCachePublicKeys(url: URL): Promise<PublicKeys> {
    const response = await this.fetchPublicKeysResponse(url);
    keyResponseCache.set(url.toString(), response);

    return response.keys;
  }

  public async fetchPublicKeys(): Promise<PublicKeys> {
    const url = new URL(this.clientCertUrl);
    const cachedResponse = keyResponseCache.get(url.toString());

    if (!cachedResponse) {
      return this.fetchAndCachePublicKeys(url);
    }

    const {keys, expiresAt} = cachedResponse;
    const now = Date.now();

    if (expiresAt <= now) {
      return this.fetchAndCachePublicKeys(url);
    }

    return keys;
  }
}
```

Here I store response data + `expiresAt` derived from `Cache-Control` header to invalidate/update the cache

The idea is that having shared global context, you can build more sophisticated caching mechanism

**Comment by emmgfx** [comment]
Oh now I understand. Nice @awinogrodzki , thank you!
