### ISSUE TITLE
Error: No router instance found.

### ISSUE THREAD

**Issue by yamijuan** [vercel/next.js#50100]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 16.18.1
      npm: 9.6.5
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/confident-tristan-qvxue1

### To Reproduce

Just run the example and render home

### Describe the Bug

page.tsx in home is a client component, and I'm calling a hook that user `Router` from `next/router` inside an `useEffect` and get the error:

Error: No router instance found.
You should only use "next/router" on the client side of your app.

![image](https://github.com/vercel/next.js/assets/25460766/cd93ae55-f12b-48fc-89f2-5bbf6cf0704a)

### Expected Behavior

Shouldn't render this in the server since it's a client component

### Which browser are you using? (if relevant)

Chrome 113.0.5672.127

### How are you deploying your application? (if relevant)

next dev, next start

**Comment by HamAndRock** [comment]
You need to use import from 'next/navigation' in app directory that one is solely just for pages directory

**Comment by shuding** [comment]
In App Router you'll have to use `next/navigation` to get the `router` instance, see https://nextjs.org/docs/app/api-reference/functions/use-router for more details.
