### ISSUE TITLE
Next 13 , App Dir , <Link scroll={false} href={...} >click</Link> , Clicking the link still goes top of the page 

### ISSUE THREAD

**Issue by jinojacob15** [vercel/next.js#50105]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Env Details 

Next js  Version 13.4.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

does not have a public url but this can can be reproduced on local machine

### To Reproduce

Next 13 , App Dir , <Link scroll={false} href={...} >page link</Link> , Clicking the link still goes top of the page  , scroll false prop is not respected . Even router.push(pathname,,{scroll:false}) does not work . 

### Describe the Bug

Next 13 , App Dir , <Link scroll={false} href={...} >page link</Link> , Clicking the link still goes top of the page  , scroll false prop is not respected . Even router.push(pathname,,{scroll:false}) does not work . 

### Expected Behavior

If Link scroll false prop is set then, page should retain scroll position

### Which browser are you using? (if relevant)

chromium

### How are you deploying your application? (if relevant)

local machine 

<sub>[NEXT-1377](https://linear.app/vercel/issue/NEXT-1377/next-13-app-dir-link-scroll=false-href=-clicklink-clicking-the-link)</sub>

**Comment by EthanStandel** [comment]
I just want to add to the noise around this problem. I have a very hard time considering the appDir as "stable" without this. The fact that I can't use links which update even queryParams without a scroll reset is supremely problematic.

**Comment by danf97** [comment]
Same issue here. Any workaround?

**Comment by FranLagorio** [comment]
I have the same problem! I can't have smooth scrolling either. The only solution for me was add a <div> with the height necessary and transform to 'use client' to make the smooth effect.

**Comment by srikargunnam** [comment]
Similar issue, I have page which has some links at mid part of the page, when user clicks on any link, I am able to update searchParams, and I want the user to stay at the same position of window, but the page scrolls to top, I tried using scroll={false} prop of Link component, it's not working, any workaround till the issue gets fixed?

**Comment by EthanStandel** [comment]
The only workaround I've found is to completely circumvent Next's routing. In the cases where I need to maintain scroll state, I have converted those pages to fetch the data client side and then used my own custom wrapper around `<a />` tags that has click handlers that `event.preventDefault()` and then manually update the history API and then run whatever state update logic I need.

It's not scalable but it works for individual scenarios.

**Comment by okanji** [comment]
I am having a similar issue with` useRouter`. Where `router.replace` or `router.push` defaults to scrolling to the top. There used to be an option object that you could pass to those where you could specify scroll as false `{scroll: false}` but that does not exist any more. 

When I look at the interface:  `replace(href: string, options?: NavigateOptions): void;` and then inspect the `NavigateOptions` interface:

```
export interface NavigateOptions {
}
```

It's empty! Was this forgotten?

**Comment by okanji** [comment]
Looking at the docs, there is not option to disable scroll in the `app dir` version of `useRouter`.  And no mention of it in the migration from pages to app dir. How can we get someone to look into this?

**Comment by lethanksbinh** [comment]
I found a workaround for myself, and that's adding a hash value to the href and an id to the element I wanted to go to:
```javascript
<Link href={{ pathname: "page", hash: 'head' }} replace>
  Go to page
</Link>

<div id="head"></div>
```

**Comment by timneutkens** [comment]
Landed support for `scroll={false}` and `scroll: false` on `router.push` / `router.replace` in #51869 and triggered a new canary release. Thanks for the feedback!

**Comment by okanji** [comment]
Awesome looking forward to using it!

**Comment by adamchipperfield** [comment]
> Landed support for `scroll={false}` and `scroll: false` on `router.push` / `router.replace` in #51869 and triggered a new canary release. Thanks for the feedback!

Is there a way to set the opposite as default?

**Comment by kachkaev** [comment]
> Is there a way to set the opposite as default?

You can create a custom Link component that wraps Next.js Link and adds `scroll={scroll ?? false}` to it. Not sure if changing the default on the framework level is a good idea – this does not compose.

**Comment by adamchipperfield** [comment]
I think I've confused myself here. The default behaviour I'm getting is **not** scrolling to the top of the page. Is this expected?

I want to tell it to always scroll to the top, unless stated otherwise.
