### ISSUE TITLE
 Bug: Incompatibility with React-RxJS when TurboPack is enabled (ReferenceError: Subscriber is not defined)

### ISSUE THREAD

**Issue by lojithv** [vercel/next.js#50106]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/lojithv/react-rxjs-nextjs-turbo-issue.git

### To Reproduce

Use react-rxjs with turbopack.

1. Enable turbopack
2. Add react-rxjs
3. Create a hook from an observable
4. run app using `next dev --turbo`

![Screenshot_3](https://github.com/vercel/next.js/assets/74459314/2683343c-85f9-4e32-abc4-271ec79f443d)
![Screenshot_2](https://github.com/vercel/next.js/assets/74459314/8fd208a2-efd9-40ea-8864-14616f2e7b91)

### Describe the Bug

Cannot use React-Rxjs with turbopack. 

### Expected Behavior

Should be able to use React-Rxjs with turbopack.

### Which browser are you using? (if relevant)

Chrome 113.0.5672.127

<sub>[WEB-1089](https://linear.app/vercel/issue/WEB-1089/bug-incompatibility-with-react-rxjs-when-turbopack-is-enabled)</sub>

**Comment by ForsakenHarmony** [comment]
Should be fixed with https://github.com/vercel/turbo/pull/5392
