### ISSUE TITLE
Global error handler (global-error.tsx) fails to catch errors in nested layouts

### ISSUE THREAD

**Issue by SiarheiLazakovich** [vercel/next.js#50119]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/runtime-water-ylwcg0

### To Reproduce

1. open: https://codesandbox.io/p/sandbox/runtime-water-ylwcg0
2. execute: yarn start (or yarn && yarn build && yarn start)
3. see:
<img width="1728" alt="Screenshot 2023-05-21 at 13 34 39" src="https://github.com/vercel/next.js/assets/10497370/5274872a-f9f0-4965-9ef5-4ef248919136">

### Describe the Bug

After upgrading to version v13.1.7-canary.11 and newer, the global error handler (global-error.tsx) fails to catch errors that occur within nested layouts. When an error occurs in a layout, the global error handler is not triggered, and the error is not handled.

### Expected Behavior

When any error occurs in the application, the global error handler (global-error.tsx) should be triggered regardless of the level of nesting in the layouts. The global handler should catch and handle errors at any level of layout nesting.
Same as was in 13.1.7-canary.10.

codesandbox with 13.1.7-canary.10: https://codesandbox.io/p/sandbox/crazy-lake-nw0qy7
<img width="1728" alt="Screenshot 2023-05-21 at 13 34 26" src="https://github.com/vercel/next.js/assets/10497370/890c28b1-0e0a-4e4d-8ebf-16eaa0b4a265">

**Comment by RafalChojnowskiPagepro** [comment]
For me it doesn't catch error from root layout either

**Comment by llee1990** [comment]
Still seeing this issue after upgrading to v13.4.10. Unable to catch errors from root layout. Only from root ~~error.tsx~~

**Comment by KristineTrona** [comment]
Same here, updated to 13.4.10 and throwing an error in root layout does not display `global-error.tsx`

**Comment by subalee** [comment]
Same here @13.4.11 
![image](https://github.com/vercel/next.js/assets/4430384/e66ddc86-c65f-4068-aae6-085fe8832add)

**Comment by PencilCoder0E** [comment]
@vercel Please take a look at this

**Comment by PencilCoder0E** [comment]
> 

Update:

This also seem to happen with not-found, 404, and 500 pages that are located in the root of /app directory.
