### ISSUE TITLE
Font weight in opengraph-image doesnt seem to work

### ISSUE THREAD

**Issue by harish-sethuraman** [vercel/next.js#50127]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.15.0
      npm: 8.5.5
      Yarn: 1.22.18
      pnpm: 7.1.9
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/harish-sethuraman/og-next-repro

### To Reproduce

check the `og-playground` output and try running the repo in local and verify the og image generated the fontweight is not working fine.

### Describe the Bug

I tried to create `opengraph-image` in the app directory through the opengraph-image file and font-weight doesnt seem to work. I pasted the same code in `og-playground` and it seems to work fine there and here is a [link](https://og-playground.vercel.app/?share=jVTBTsMwDP2VyIhbpZWBEKqACwyBuDEkLruki9tmpEmVpowx7d9xCtuabrD1FPtZ9vPzU5cwNQIhgYlm7Xct5Mf6zVjtFgpvlstthrECZV64hE3gLI5PJxB1wbkUrvgDE7KuFF94NFP42UN96l5anDpptK-ZGtWUulfFlcz1k8OybktQO7S9kllTO5kt7gxhuuW5tyzl0_fcmkYLX5IqCvuMqMNYfmHCzoc7wNuvCpdxHGAVF0Lq3Pc8r8IdV6v1-3abDPXer_gh6WgZYwXaFy5k0wpz1Rt9vMBHSXy0yMfIfMBR_3uKsZLbXLb7nMU7W28lD0Qn2Yth2Ga_7oyRSMb67idZlu0M7_bvTaAZ6e0jt7Iu2HNDLNmYja8HaUhjUAzDRLVh0vHfMI46RIQQRCRw4QRqLGVqFCFEqkfkwbZnEmykSSqkKwUUqq4dB-THTbyNIAJTeePUkCyhvQgkV-R9-DkeJBc-EJg2OSQZVzVGgKWZyddF5f8vbt5G1MfzHpUpCkicbXAVgeMpVRSolJkbqwSsvgE)

I have also created a repro in case it is needed https://github.com/harish-sethuraman/og-next-repro the same code is present in the playground as well. Also I installed the `@vercel/og` package and imported `ImageResponse` from it instead of `next/server` and the issue seems to persist.

### Expected Behavior

Font weight should work just like the one in [og-playground.vercel.app](https://og-playground.vercel.app)

**Comment by shuding** [comment]
`@vercel/og` has only one font with one weight builtin as the fallback. You'll have to provide your own fonts with different weights to make it work: https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation/og-image-examples#using-a-custom-font
