### ISSUE TITLE
chunks loading on appDir

### ISSUE THREAD

**Issue by Marsony** [vercel/next.js#50134]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 3.5.4
      pnpm: 7.24.3
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Script optimization (next/script)

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app@latest

### To Reproduce

yarn build

### Describe the Bug

On the `pages` 
`<script defer="" src="/_next/static/chunks/7564.d445a9d48197f5cd.js"></script>`

On the `appDir`
```
<script>self.__next_f.push([1,"9:I{\"id\":\"6110\",\"chunks\":[\"533:static/chunks/533-c38c26f55daf3423.js\",\"4475:static/chunks/4475-c736b9c3c2aba648.js\",\"9874:static/chunks/9874-498ca8fb50bb6f93.js\",\"9111:static/chunks/9111-cb17561439e8aba9.js\",\"6204:static/chunks/6204-8a85174892ba7775.js\",\"1233:static/chunks/1233-8211853719e36553.js\",\"6924:static/chunks/app/[lang]/publication/[...slugs]/page-47047b4fa1328a6c.js\"],\"name\":\"EffectorNext\",\"async\":false}\na:I{\"id\":\"6593\",\"chunks\":[\"9874:static/chunks/9874-498ca8fb50bb6f93.js\",\"5066:static/chunks/50"])</script>
```

This leads to a significant increase in the required time before the script starts loading in the browser, and hence the execution itself. Why? Is It bug or side effects of early stage of appDir? Waterfall increases by an average of two or three times

### Expected Behavior

Should chunks be loaded like it was on the  `pages` ?

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

localhost

**Comment by proweb** [comment]
+1
