### ISSUE TITLE
Docs: Accessing metadata in MDX files

### ISSUE THREAD

**Issue by traversng** [vercel/next.js#50138]
### What is the improvement or update you wish to see?

I would like to see an example of how to access the metadata from an MDX file as shown in one of the examples: https://nextjs.org/docs/app/building-your-application/configuring/mdx#frontmatter

### Is there any context that might help us understand?

I just think the example is incomplete

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/configuring/mdx#frontmatter

<sub>[DX-1708](https://linear.app/vercel/issue/DX-1708/docs)</sub>

**Comment by leerob** [comment]
I believe the documentation is clear about this at the moment. Open to example contributions if you would like to see something further!

<img width="682" alt="CleanShot 2023-11-09 at 08 59 52@2x" src="https://github.com/vercel/next.js/assets/9113740/0bbd8a74-5f0b-4121-9e30-bfff6c3a28d5">
