### ISSUE TITLE
Hot Module Replacement (HMR) not working when Turbopack enabled

### ISSUE THREAD

**Issue by kaumac** [vercel/next.js#50153]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64
    Binaries:
      Node: 18.13.0
      npm: 9.6.3
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.2.4", newest: "13.4.4-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/kaumac/rank-tt

### To Reproduce

- Make any UI (JSX/TSX) changes running NextJS with Turbopack (--turbo)
- Watch as either the entire page reloads

### Describe the Bug

When running NextJS with Turbopack (--turbo) the hot module replacement (HMR) doesn't work properly and instead reloads the entire page, making development quite a bit slower.

If run `next dev` without turbopack and make the exact same changes, it does HMR correctly instead of reloading the entire page.

I know Turbopack doesn't have full feature parity with Webpack just yet, but HMR is a pretty essential feature nowadays.

### Expected Behavior

Hot module replacement of only the changed component

<sub>[WEB-1159](https://linear.app/vercel/issue/WEB-1159/hot-module-replacement-hmr-not-working-when-turbopack-enabled)</sub>

**Comment by padmaia** [comment]
I'm not seeing full-page reloads when using create-next-app for both pages and the new app router. I also don't have access to https://github.com/kaumac/rank-tt. Would you mind open-sourcing it or providing a simpler reproduction we can access? It would also help to know what particular files you are updating, as it is probably only certain cases that fully reload.

**Comment by kaumac** [comment]
@padmaia Sorry I thought it was already public. It is now...

I tested it a bit more, still don't know what causes this, but it doesn't happen on very simple pages without layouts.

For example, I have a temporary simple landing page at `app/page.tsx` and if I make changes there hmr happens as expected. But if I make changes to any component, page or layout file under `/painel` (that's where the real application begins) then I get a full page reload...

The weird part is that it works with webpack, so I'm just using that for now, but I'd love to migrate to Turbopack...

**Comment by OhadBaehr** [comment]
I actually have the opposite problem, for some reason hot reloading was not working for me, tried running `npm run dev --turbo` and now it's working

**Comment by nnecec** [comment]
same problem. when I enable `--turbo`, HMR is work, but page state will be reset.

**Comment by jaukia** [comment]
Having the same problem, too. When doing any changes to the page tsx, the state gets reset.

**Comment by azvyae** [comment]
I it any updates on this problem? Even navigating links will trigger full page reload

**Comment by ForsakenHarmony** [comment]
Are you still seeing this with next 14?

Would appreciate a simpler reproduction case.

**Comment by padmaia** [comment]
We need a better reproduction case and a confirmation that this is still happening in the latest canary to look into this. Closing for now.
