### ISSUE TITLE
CORS documentation insufficient

### ISSUE THREAD

**Issue by shaun-scale** [vercel/next.js#50171]
Lee Robinson had added CORs documentation here which was an awesome start.

https://nextjs.org/docs/app/building-your-application/routing/router-handlers#cors

One of the gaps called out in the discussion is that you need to explicitly support the OPTIONS method on your routes to respond to the CORS request correctly. 

This was documented later on in the initial discussion
https://github.com/vercel/next.js/discussions/47933

**Comment by shaun-scale** [comment]
cc @leerob, also hi @leerob ! 👋

**Comment by delbaoliveira** [comment]
Hey @shaun-scale 👋🏼  This issue was recently address here: https://github.com/vercel/next.js/pull/62439

Let us know if you have any further feedback!
