### ISSUE TITLE
Docs: next.config.js variants in odd location

### ISSUE THREAD

**Issue by mrienstra** [vercel/next.js#50192]
### What is the improvement or update you wish to see?

`docs/api-reference/next.config.js/introduction.md` should be shown at https://nextjs.org/docs/app/api-reference/next-config-js, rather than at https://nextjs.org/docs/app/api-reference/next-config-js/pageExtensions

### Is there any context that might help us understand?

https://nextjs.org/docs/app/api-reference/next-config-js only shows one form that `next.config.js` can take (object in Node.js module file).

For some reason, the other variants (`mjs`, `function`, `async function`) are outlined here: https://nextjs.org/docs/app/api-reference/next-config-js/pageExtensions

... which doesn't make much sense to me, guessing this is a mistake / side effect. Content is coming from [docs/api-reference/next.config.js/introduction.md](https://github.com/vercel/next.js/blob/canary/docs/api-reference/next.config.js/introduction.md) ([permalink](https://github.com/vercel/next.js/blob/6f2e140/docs/api-reference/next.config.js/introduction.md))

---

Aside (I can open another issue for this if desired): documentation of `defaultConfig` is difficult to locate, not on either of these pages, and not found via search. Just a simple example would be nice, as is done for `phase`.

**Comment by balazsorban44** [comment]
Thanks for the report, the docs has undergone a series of refactoring, and files have been moved around. This should be correct now, if you have further feedback, please open a new issue, thanks! :pray:
