### ISSUE TITLE
`revalidatePath` is not busting client segment cache

### ISSUE THREAD

**Issue by abuinitski** [vercel/next.js#50203]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
 Platform: linux
 Arch: x64
 Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
Binaries:
 Node: 16.17.0
 npm: 8.15.0
 Yarn: 1.22.19
 pnpm: 7.1.0
Relevant packages:
 next: 13.4.4-canary.2
 eslint-config-next: N/A
 react: 18.2.0
 react-dom: 18.2.0
 typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/cranky-lovelace-mkjcpq

### To Reproduce

1. Run provided example, start off at initial route "/", observe list of items
2. Click "Item 1", observe details page with an input
3. Click "Back", observe you're back at list page (this is important, somehow initial route does not end up in client cache)
4. Click "Item 1" again
5. Enter something different (e.g. "Item 1 updated") into the input field, click "Save", observe view is properly updated
6. Cllick "Back", observe old name is still displayed in the list page, consult logs to make sure this page was not rendered on the server, and was indeed served from client cache
7. Refresh preview page, observe new name is displayed

### Describe the Bug

When Server Action triggers server mutation, and properly(?) invalidates obsolete paths, while these paths are (assumedly) removed from server cache, may still remain in client segment cache, and therefore serve incorrect data afterwards.

### Expected Behavior

Since Server Action invalidated path, displaying cached version is not expected afterwards.

**Comment by mediabeastnz** [comment]
Also seeing this behaviour which basically makes `revalidatePath()` unusable

**Comment by karlhorky** [comment]
Here's a video from the sandbox - interestingly it also sometimes succeeds 🤔 (I had it succeed multiple times before I took the video, so I thought that was actually not a problem anymore)

https://github.com/vercel/next.js/assets/1935696/3df54eca-7a59-45f2-8525-de9b3f5bf98e

This is where the `revalidatePath()` is used in the code, since it wasn't mentioned in the issue description above:

`app/[itemId]/actions.ts`

```ts
"use server";

import { revalidatePath } from 'next/cache'

import { getItemsRepository } from "../_item/ItemsRepository";

export async function saveItemName(itemId: string, newName: string) {
  console.log(`SAVE: ${itemId}/${JSON.stringify(newName)}`);
  await getItemsRepository().updateItemName(itemId, newName);
  revalidatePath(`/${itemId}`);
  revalidatePath("/");
}
```

**Comment by shuding** [comment]
Thanks @karlhorky I believe that this is fixed with https://github.com/vercel/next.js/pull/50848.

**Comment by abuinitski** [comment]
yep, it works, thanks!
