### ISSUE TITLE
Problem with the metadata when attempting to deploy it on Vercel

### ISSUE THREAD

**Issue by aditya305** [vercel/next.js#50217]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4

warn  - Latest canary version not detected, detected: "13.4.3", newest: "13.4.4-canary.3".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
```

### Which example does this report relate to?

page.js, metadata

### What browser are you using? (if relevant)

Chrome 113.0.5672.127

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I recently created a new Next.js project and developed a website. During this process, I discovered that the head tags are now being written using the `_export const metadata = {}_` method, including a title like this:

```javascript
_export const metadata = {
  title: "Flutter Roadshow"
};
```

After pushing the code and attempting to deploy it on Vercel, I encountered an issue where Vercel was unable to successfully deploy the code onto the website.

![Screenshot 2023-05-23 180838](https://github.com/vercel/next.js/assets/41361167/44d6174c-5260-442a-9046-2d07ff96c320)

![Screenshot 2023-05-23 181005](https://github.com/vercel/next.js/assets/41361167/aea71c5c-1b32-48b0-8572-6484f9c6b517)

### Expected Behavior

Ideally, the website should execute and deploy seamlessly, devoid of any errors. However, instead of the expected smooth deployment, I encountered some errors. To provide a better understanding of the situation, I have included screenshots of the relevant code and the error message displayed by Vercel:

![Screenshot 2023-05-23 180838](https://github.com/vercel/next.js/assets/41361167/e135c17d-248c-4b71-b0d1-9a68ba36034a)

![Screenshot 2023-05-23 181005](https://github.com/vercel/next.js/assets/41361167/6599d932-6220-4e5d-9099-a77c13603bbc)

These errors are hindering the successful deployment of the website on Vercel.

### To Reproduce

![Screenshot 2023-05-23 180838](https://github.com/vercel/next.js/assets/41361167/71a7a994-d645-4a83-adf7-846a44db5627)

**Comment by joulev** [comment]
The `export const metadata` and `export function generateMetadata` syntaxes only work in server components (at least for now), see #48266. So you need to do something like this

* Make a client component, say, `page.client.tsx` with all your logic

```tsx
"use client";

export default function PageClient() {
  return <div>Hello, world!</div>;
}
```

* then use it in the server component `page.tsx`

```tsx
// page.tsx
import PageClient from "./page.client";

export default function Page() {
  return <PageClient />;
}

export const metadata = {
  title: "Hello, world!",
};
```

**Comment by aditya305** [comment]
sounds good!
However, is there a simpler method to define the remaining SEO tags?

**Comment by joulev** [comment]
[See the documentation](https://nextjs.org/docs/app/building-your-application/optimizing/metadata).
