### ISSUE TITLE
Can't see full url for cache information in Next.js logs

### ISSUE THREAD

**Issue by franzwarning** [vercel/next.js#50237]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 3.5.1
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.5
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

-

### To Reproduce

-

### Describe the Bug

I only see the least important part of my API request urls:

<img width="741" alt="CleanShot 2023-05-23 at 14 11 00@2x" src="https://github.com/vercel/next.js/assets/1596816/0a61af90-9f94-46ef-b599-0f19da11c40e">

### Expected Behavior

It would be nice to see the end of the urls, rather than the beginning. Or have a verbose output of sorts.

### Which browser are you using? (if relevant)

Safari

**Comment by samcx** [comment]
@franzwarning I don't think this is an issue anymore with the `logging` config!

- https://nextjs.org/docs/app/api-reference/next-config-js/logging

![CleanShot 2024-11-13 at 22 55 22@2x](https://github.com/user-attachments/assets/5538499a-c4df-409f-bae3-83d8232b075a)
