### ISSUE TITLE
[NEXT-1260] /app/not-found broken in standalone mode

### ISSUE THREAD

**Issue by klarstrup** [vercel/next.js#50232]
### Verify canary release

* [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.5-canary.7
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

[https://github.com/klarstrup/next.js-repro-repo/tree/ERR_PACKAGE_PATH_NOT_EXPORTED](https://github.com/klarstrup/next.js-repro-repo/tree/ERR_PACKAGE_PATH_NOT_EXPORTED)

### To Reproduce

Build and run the app: `npm i && npm run build && node ./.next/standalone/server.js`

Request any path on the server, [http://localhost:3000/](http://localhost:3000/) is a good choice.

### Describe the Bug

any 404 page results in a bunch of failing script requests which result in ERR_PACKAGE_PATH_NOT_EXPORTED spam in server output:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.edge' is not defined by "exports" in /next.js-repro-repo/.next/standalone/node_modules/react-dom/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at /Users/io/code/my-app/.next/standalone/node_modules/next/dist/server/require-hook.js:196:36
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Expected Behavior

no failing script requests and ERR_PACKAGE_PATH_NOT_EXPORTED spam in server output

### Which browser are you using? (if relevant)

*No response*

### How are you deploying your application? (if relevant)

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-1260](https://linear.app/vercel/issue/NEXT-1260/appnot-found-broken-in-standalone-mode)</sub>

**Comment by christianvuerings** [comment]
We noticed that it's the existence of a `not-found.jsx` file in our app directory that's causing this issue. If we remove the `not-found.jsx` file and we add a root `page.jsx`, we don't see the exception.

Example fix at https://github.com/klarstrup/next.js-repro-repo/pull/1
Also might be related to https://github.com/vercel/next.js/issues/49796

**Comment by ChandanJal** [comment]
**Hey There** ✋  ! It is working absolutely fine in my device.

**Operating System:**
-   Platform: darwin
-   Arch: arm64
-   Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000

**Binaries:**
-   Node: v18.16.0
-   npm: 9.5.1

**Relevant packages:**
-   next: 13.4.4-canary.4
-   eslint-config-next: N/A
-   react: 18.2.0
-   react-dom: 18.2.0
-   typescript: N/A

**Comment by klarstrup** [comment]
still applies as of next@13.4.4-canary.11

**Comment by klarstrup** [comment]
still applies as of next@13.4.4

**Comment by Rajaotix** [comment]
Try to do `clear npm cache` then npm install. It works for me

**Comment by klarstrup** [comment]
Still applies as of next@13.4.5-canary.2 - in spite of both `npm cache clear --force` and `rm -rf node_modules .next` and so on.

**Comment by Inoir** [comment]
our is gone after setting absolute paths for everything on the server. so prefix with NEXT_PUBLIC_URL. Dunno if this is only one of the cause of this error. without we had the same issue

**Comment by klarstrup** [comment]
Sorry, add that prefix where, @Inoir? https://github.com/klarstrup/next.js-repro-repo/tree/ERR_PACKAGE_PATH_NOT_EXPORTED

**Comment by marcospassos** [comment]
Same here

**Comment by klarstrup** [comment]
Can confirm this still applies as of `next@13.4.5-canary.5`

**Comment by klarstrup** [comment]
Can confirm this still applies as of `next@13.4.5-canary.7`

**Comment by huozhi** [comment]
Hi, we hear you loud. As this bug is not fixed yet as the issue is still opening. We'll post update once it's closed with a PR or certain solution. No need to keep bumping it with comments, we'll working on it, thanks 😄

**Comment by klarstrup** [comment]
Sorry, it wasn't really my impression that this had been triaged at all and I wanted to make sure the relevancy was apparent when you eventually got to it.

**Comment by jamiter** [comment]
@klarstrup, just curious if this is now fixed for you.

**Comment by klarstrup** [comment]
> @klarstrup, just curious if this is now fixed for you.

Yes and no, it is broken in a new way in `13.4.7-canary.1`.

**Comment by klarstrup** [comment]
This is not fixed as of #51611/`next@13.4.8-canary.1`

But as of #51506/`next@13.4.7-canary.4` the 500 errors look like this on the backend 🤔

```elixir
Error: connect ECONNREFUSED ::1:59104
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 59104
}
```

**Comment by huozhi** [comment]
@klarstrup how did you bump to this network error? I tried your original reproduction from this issue with canary version it works for me

**Comment by klarstrup** [comment]
No idea, this is with the repro repo above on the system described above:

```zsh
io@Ios-MacBook-Pro my-app % git status   
On branch ERR_PACKAGE_PATH_NOT_EXPORTED
Your branch is up to date with 'origin/ERR_PACKAGE_PATH_NOT_EXPORTED'.

nothing to commit, working tree clean
io@Ios-MacBook-Pro my-app % rm -rf .next node_modules && npm i next@canary && npm run build && node ./.next/standalone/server.js

added 40 packages, and audited 42 packages in 2s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> build
> next build

- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types  
- info Collecting page data  
- info Generating static pages (3/3)
- info Finalizing page optimization  

Route (app)                                Size     First Load JS
─ ○ /_not-found                            0 B                0 B
+ First Load JS shared by all              77.6 kB
  ├ chunks/769-f51582f2b9b00a6b.js         25.2 kB
  ├ chunks/bce60fc1-49ee79ad31766ac6.js    50.5 kB
  ├ chunks/main-app-5537570c1c769cc0.js    217 B
  └ chunks/webpack-bf1a64d1eafd2816.js     1.61 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   182 B          75.4 kB
+ First Load JS shared by all              75.2 kB
  ├ chunks/framework-8883d1e9be70c3da.js   45 kB
  ├ chunks/main-f21a854e626768e2.js        28.4 kB
  ├ chunks/pages/_app-998b8fceeadee23e.js  195 B
  └ chunks/webpack-bf1a64d1eafd2816.js     1.61 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)

Listening on port 3000 url: http://localhost:3000
Error: connect ECONNREFUSED ::1:49756
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 49756
}
Error: connect ECONNREFUSED ::1:49756
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 49756
}
^C%                                                                                                                                                                       
io@Ios-MacBook-Pro my-app % npx next info                                                                                       

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.8-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A

io@Ios-MacBook-Pro my-app % 
```

**Comment by DuCanhGH** [comment]
@klarstrup #51887 should hopefully resolves this issue :)

**Comment by bsh-github-techuser** [comment]
We have the same issue, using Next.js 13.4.7 and Node.js 18.16.0. With Node.js 16, it seems to work correctly, so it seems like it's the other way round and it's broken in newer versions of Node.js.

**Comment by ghost91-** [comment]
We have the same issue, using Next.js 13.4.7 and Node.js 18.16.0. With Node.js 16, it seems to work correctly, so it seems like it's the other way round and it's broken in newer versions of Node.js.

**Comment by klarstrup** [comment]
Inexplicably fixed for me as of `next@13.4.9-canary.3` 🤷‍♀️ Can't figure out which change in that version actually did the trick

**Comment by DuCanhGH** [comment]
@klarstrup the default host was changed to 127.0.0.1, which, uh, was quite crazy a change...

**Comment by klarstrup** [comment]
Oh I found the PR now https://github.com/vercel/next.js/pull/52283

It was not mentioned in the release notes :/ @shuding

**Comment by shuding** [comment]
That was included in the canary release, although it should be part of the release note.

**Comment by klarstrup** [comment]
Not as anything resembling "Use 127.0.0.1 as the default host for the standalone server" at least, I think something might've gone awry generating the release note.

**Comment by huozhi** [comment]
@klarstrup Thanks for checking it's missing in release log, manually added them back for now. I'll follow up why it's lost 🙏
