### ISSUE TITLE
CSS code splitting in App Router isn't working with Next.js version beyond 13.2.4

### ISSUE THREAD

**Issue by lrozewicz** [vercel/next.js#50239]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.3
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/lrozewicz/nextjs-app-router-bug

### To Reproduce

Clone the repo https://github.com/lrozewicz/nextjs-app-router-bug

Go to folder /not-working/my-app
`npm install`
`npm build`
`npm start`

run in browser http://localhost:3000/

You will see one CSS file, containing the styling for the Header and Content components.
![not-working](https://github.com/vercel/next.js/assets/37874987/35568964-9a9a-4d57-b2b9-c6d5132dc910)

If we repeat the above steps for the application in the /working/my-app/ folder, we will see the proper operation, that is, two separate CSS files, one with styling for the Header component and the other for the Content component.
![working](https://github.com/vercel/next.js/assets/37874987/71287193-8a83-4211-815a-f3723ab341c4)

### Describe the Bug

In Next.js versions 13.2.4 and lower css splitting of code into various bundles it works with no problems. 
In higher versions of Next.js, unfortunately, it stopped working. 

The application is built of 2 components, which are loaded using <Suspence>. 
![code-page](https://github.com/vercel/next.js/assets/37874987/9f96168d-1234-471c-b71c-b0b08803bbcb)

### Expected Behavior

There should be separate CSS result files for component one (Header) and component two (Content). And this is what happens in an application using Next.js version 13.2.4. In contrast, an application using version 13.4.3 produces one common CSS file with code for both components. 

### Which browser are you using? (if relevant)

Chrome 113.0.5672.127 

### How are you deploying your application? (if relevant)

localhost

**Comment by shuding** [comment]
Hey! In a production build, CSS files will be bundled if possible to minimize the number of network requests and maximize compression. Without this an application with hundreds of CSS modules will result in hundreds of CSS request when loading. This is the expected behavior in the pages directory too. The difference between 13.2.4 and 13.4.3 is actually a bugfix.

Also I'm not seeing `next/dynamic` used in your code, is that related?

**Comment by lrozewicz** [comment]
> Hey! In a production build, CSS files will be bundled if possible to minimize the number of network requests and maximize compression. Without this an application with hundreds of CSS modules will result in hundreds of CSS request when loading. This is the expected behavior in the pages directory too. The difference between 13.2.4 and 13.4.3 is actually a bugfix.
> 
> Also I'm not seeing `next/dynamic` used in your code, is that related?


The attached code is just a simplification of the problem we have. Our application has many pages, there are components on these pages, on some pages some components occur, on others they do not. 

The problem is that whether we use Suspence, or dynamic import, or React.lazy then the styling of all the components eventually go into one big CSS file, even if the component is not present on the page. This causes redundancy in the CSS code.

How can we force Next.js not to load styles on the page for components that do not currently appear on a given subpage? Currently, all subpages load the styling for all components the application has, regardless of whether the component occurs on a given subpage or not :( 

Previously this worked fine, it loaded small CSS files of only those components that were present on a given page.

**Comment by lrozewicz** [comment]
As far as I can see, the problem occurs when using capture all requests, i.e. [...slug]. Then the styling goes into one file, even if the component is not used on the page. When I find some time I will prepare a simple application and upload it on github to better show what I mean.

**Comment by shuding** [comment]
Got it! Happy to reopen this once we know what the problem is so we can track and fix. For dynamically loaded components it might be an issue indeed.
