### ISSUE TITLE
Bug Report with Codesandbox does not work anymore with latest canary

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#50299]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Not possible
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/s/serene-elbakyan-nck1q7

### To Reproduce

Open a Bug Report and click the link for CodeSandbox reproduction:

![image](https://github.com/vercel/next.js/assets/987947/c88cd94b-516c-4721-bfda-7d0a4d4efbc4)

https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template

### Describe the Bug

If you open CodeSandbox, change any file so that CodeSandbox starts everything, you will get this error in their Terminal:

```
> Sandbox Container: Starting sandbox nck1q7...
> Sandbox Container: Sandbox nck1q7 started
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error next@13.4.4-canary.8: The engine "node" is incompatible with this module. Expected version ">=16.8.0". Got "14.19.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Expected Behavior

Just work.

**Comment by balazsorban44** [comment]
I could not reproduce this issue. :thinking: The Node.js version I get is 16.17. It might have been updated.

Node 14 is EOL as of very recently, so Next.js has also bumped the minimum version. CodeSandbox likely followed.

**Comment by balazsorban44** [comment]
I notified the CodeSandbox team. 🙏
