### ISSUE TITLE
Middleware `export const config` is deprecated.

### ISSUE THREAD

**Issue by cristianbuta** [vercel/next.js#50297]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
 Platform: darwin
 Arch: arm64
 Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu 8796.101.5~3/RELEASE_ARM64_T6000
Binaries:
 Node: 18.14.0
 npm: 9.3.1
 Yarn: 1.22.19
 pnpm: N/A
Relevant packages:
 next: 13.4.3
 eslint-config-next: 13.4.3
 react: 18.2.0
 react-dom: 18.2.0
 typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/cristianbuta/next-middleware-bug-report

### To Reproduce

`npm run dev`

### Describe the Bug

The CLI states:

warn `export const config` in nextbugreport/app/middleware.ts is deprecated. Please change `runtime` property to segment export config. See https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config

And the matcher does not work at all, therefore the middleware does not get called.

### Expected Behavior

matcher allows you to filter Middleware to run on specific paths.

See https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config

### Which browser are you using? (if relevant)

Chrome 113.0.5672.126 (arm64)

**Comment by ksorv** [comment]
@cristianbuta I'm also having the same issue, Would be able to tell what is to be used for path matching in middleware if this is deprecated?

**Comment by cristianbuta** [comment]
> @cristianbuta I'm also having the same issue, Would be able to tell what is to be used for path matching in middleware if this is deprecated?

middleware.ts has to sit at src level
