### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:62507

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#50298]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.8
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/s/serene-elbakyan-nck1q7

### To Reproduce

I setup a codesandbox but it looks like it is not compatible with the latest canary => https://codesandbox.io/s/serene-elbakyan-nck1q7

![image](https://github.com/vercel/next.js/assets/987947/39d9c307-5412-4eaa-9d7a-382e13b5cf98)

### Describe the Bug

Just updated to the latest canary and now I get this error on Windows

```
- error Error: connect ECONNREFUSED 127.0.0.1:62746
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 62746
}
- error Error: connect ECONNREFUSED 127.0.0.1:62746
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 62746
}
- error Error: connect ECONNREFUSED 127.0.0.1:62746
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 62746
}
- wait compiling /favicon.ico/route (client and server)...
- event compiled successfully in 417 ms (433 modules)
- error Error: connect ECONNREFUSED 127.0.0.1:62746
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 62746
}
```

### Expected Behavior

Don't throw an error.

**Comment by paulvanbrenk** [comment]
Looks like this is the same issue

https://github.com/vercel/next.js/issues/50290

seeing this too, and it's blocking me

**Comment by ciruz** [comment]
> Looks like this is the same issue
> 
> #50290
> 
> seeing this too, and it's blocking me

Hey thank you for the Issue.

Also if relevant, I use `yarn` and no `Turbopack`.

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.4.4-canary.9` of Next.js, please update and give it a try!

**Comment by ciruz** [comment]
Hey @ijjk I'm on `next@13.4.4-canary.10` now and it works again, as expected. Thank you.
