### ISSUE TITLE
Docs: add section on App Router testing

### ISSUE THREAD

**Issue by DonikaV** [vercel/next.js#50334]
### What is the improvement or update you wish to see?

All official examples are outdated 
https://github.com/vercel/next.js/tree/canary/examples/with-jest 
I am trying to find any example of next 13 app folder and tests setup.

### Is there any context that might help us understand?

When i try run tests from this example repo
https://github.com/vercel/next.js/tree/canary/examples/with-jest 
I am getting many errors about metadata, or about Context Providers and etc.

**Comment by balazsorban44** [comment]
Thanks for the feedback! We are working on a recommendation in this regard.

Related issues are https://github.com/vercel/next.js/issues/47448 and https://github.com/vercel/next.js/issues/47299

We will get back when we have more information! :pray:

**Comment by leerob** [comment]
https://github.com/vercel/next.js/issues/47448#issuecomment-1705573492

**Comment by leerob** [comment]
https://nextjs.org/docs/app/building-your-application/testing
