### ISSUE TITLE
Pages inside route groups have size 0

### ISSUE THREAD

**Issue by bi-zi** [vercel/next.js#50330]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 19.7.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.10
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/bi-zi/bundle-size

### To Reproduce

To reproduce the problem, you need to add the page to (route groups) and run build.

You can see in the screenshot (User) and inside it are two pages of News and Post. There is also just a Price page outside the route groups and its size is not equal to 0

![bundle size](https://github.com/vercel/next.js/assets/76881636/78f79cc2-ecd0-46cd-8658-eaf548699478)

### Describe the Bug

Pages inside (route groups) have size 0

### Expected Behavior

Pages inside (route groups) should not be size 0

### Which browser are you using? (if relevant)

Chrome 113.0.5672.127

### How are you deploying your application? (if relevant)

-

**Comment by Herklos** [comment]
I am also experiencing the same issue... 

> How are you deploying your application? (if relevant)

Using Cloudflare

**Comment by Wepa121** [comment]
same issue

**Comment by ijjk** [comment]
Hi, this has been fixed in the latest version of Next.js, please update and give it a try!
