### ISSUE TITLE
revalidatePath in server action is not revalidating the path(s)

### ISSUE THREAD

**Issue by Abyrd9** [vercel/next.js#50356]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.13
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

app dir
server actions
revalidatePath

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Abyrd9/nextjs-revalidate-path-bug

### To Reproduce

Sorry that there's db setups involved but I wasn't sure how else to get the reproduction I wanted.

1. Create new [supabase](https://supabase.com/dashboard/projects) project
2. Create new table called "posts" and a new columns called "name" with type "text"
3. In project settings copy the "Project URL" and the "Project API keys" (anon public)
4. create a local.env file and add the url and the api key:
```
SUPABASE_URL=https://{supabase-db-url}.supabase.co
SUPABASE_KEY={supabase-key}
```

`npm run dev` and navigate to `http://localhost:3000/`

Click the "Add New" button and then type in any sort of text and submit it.

### Describe the Bug

When calling a server action that is running revalidatePath on a specific path, I would expect that path to re-run it's queries and return with fresh data. Instead if stays cached.

When submitting the form (located in `/src/components/dialog.tsx`) we call a server action (located in `/src/components/dialog.actions.ts`) in which we run the revalidatePath function on the paths `/` (base path) and `/?create=true` (dialog form path), but the neither the base path nor the dialog path revalidate, they both keep the stale data unless the default cache time runs out or you hard refresh.

### Expected Behavior

When Submitting the form on the `/?create=true` url, the base url `/` and the dialog url `/?create=true` should revalidate and run their queries again to get the newly created post.

**Comment by Comi9** [comment]
To benefit from the path revalidation, I believe you have to use a regular function and not an arrow function for your server actions.

```
export async function submit(data: FormData) {
  await supabase.from("posts").insert([{ name: data?.get("note") }])

  revalidatePath('/')
}
```

**Comment by Abyrd9** [comment]
> To benefit from the path revalidation, I believe you have to use a regular function and not an arrow function for your server actions.
> 
> ```
> export async function submit(data: FormData) {
>   await supabase.from("posts").insert([{ name: data?.get("note") }])
> 
>   revalidatePath('/')
> }
> ```

Even after changing to a regular function, the page(s) still will not revalidate.

**Comment by TranscendentalRide** [comment]
`loading.tsx` will not display on path passed to `revalidatePath` in 13.4.4, 13.4.3, or 13.4.2. But it did work in 13.4.1 and 13.4.0

**Comment by latinrev** [comment]
I just figured out my issue with revalidate path using MongoDB, it was rather silly but perhaps it may help you
I had
Action
```
  async function saveNewAnime(data: FormData) {
    "use server";
    let newAnime = Object.fromEntries(data.entries()) as anime;
    createAnime(newAnime);
    revalidatePath("/");
  }
```
Database action
```
export const createAnime = async (animeData: anime) => {
    const newAnime = deleteActionField(animeData) as anime
    await client.anime.create({ data: { ...newAnime } })
}
```

my mistake was that I forgot to await my 
` createAnime(newAnime);`
changing it to
` await createAnime(newAnime);`
made it work

So, I'm guessing perhaps revalidatePath("/") is being triggered before awaiting for 
` await supabase.from("posts").insert([{ name: data?.get("note") }])`

**Comment by Abyrd9** [comment]
@latinrev In the repo I shared above I'm awaiting on [line 10](https://github.com/Abyrd9/nextjs-revalidate-path-bug/blob/main/src/components/dialog.actions.ts#L10)

I think the problem is different because it seems like revalidatePath is revalidating the path it's currently on rather than the path that I'm passing it.

So when I run the server action on the `/?create=true` path, I want to revalidate the `/` path, but only the `/?create=true` path is being invalidated even when I'm passing in a different path.

**Comment by shuding** [comment]
Should be included in `next@13.4.5-canary.8`, let me know if it's fixed!

**Comment by Abyrd9** [comment]
@shuding Sorry for not getting back, I didn't see the "let me know if it's fixed".
So it was working perfectly in that canary version you sent me! However, after seeing that 13.4.5 released with those fixes, I upgraded but now I'm back to not getting the expected revalidation 😢

**Comment by havgry** [comment]
Just confirming it now works with `revalidateTag` as well.
