### ISSUE TITLE
Abort Signal Not Working with Next.js Edge Functions

### ISSUE THREAD

**Issue by Fawwaz-2009** [vercel/next.js#50364]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: 7.18.2
    Relevant packages:
      next: 13.4.4-canary.13
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4

warn  - Latest canary version not detected, detected: "13.4.4-canary.13", newest: "13.4.4".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Fawwaz-2009/demo-abort-signal-not-working-in-edge-function

### To Reproduce

1. Clone and run the application.
2. Visit the main page, navigate to the fetch or EventSource demo.
3. Press the "Stop Stream" button, which triggers an abort on the request.
4. Observe the console logs on the server to sea the streaming not stoping.

### Describe the Bug

when we use EventSource and fetch with AbortController. Simply put, the 'abort' event that's part of the request.signal in the edge function isn't firing like it should.

### Expected Behavior

Normally, if a request gets cancelled from the client side, the 'abort' signal in the edge function should light up. This helps stop any work related to the request on the server-side, which is good for keeping things running smoothly.

**Comment by masterkain** [comment]
maybe relevant (no solution yet) https://github.com/vercel/next.js/discussions/48682

**Comment by flosrn** [comment]
did you find a solution?

**Comment by wsxiaoys** [comment]
based on https://github.com/vercel/next.js/issues/50804

downgrading version to `v13.0.7` works for me (req.socket 'close' event emit correctly when aborting)

**Comment by wsxiaoys** [comment]
> based on #50804
> 
> downgrading version to `v13.0.7` works for me (req.socket 'close' event emit correctly when aborting)

turns out this only works for a local setup, vercel's production LB seems not propagate abort information to the api endpoint

**Comment by iuadastra** [comment]
I am facing the similar problem also with nodejs runtime - abort listener on request.signal is not triggered.
