### ISSUE TITLE
revalidation is not triggered by `<Link />` with app router

### ISSUE THREAD

**Issue by QzCurious** [vercel/next.js#50362]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Apr 2 22:23:49 UTC 2021
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/QzCurious/next-isr-not-triggered-by-link

### To Reproduce

This recording might easier to understand the steps below

https://github.com/vercel/next.js/assets/38932402/fff77f1c-363d-4ca9-9bdf-b10bfbc0a0f3

1. Clone the repo and `yarn && yarn build && yarn start`
2. Go to http://localhost:3000/app-route/a
3. There are two component on the page, a client component and a server component, showing the time they were executed
4. Click the `<Link />` To page b
5. There are also two component showing their time on page b and a `<Link />` To page a
6. The two pages are configured with `export const revalidate = 1`. Please click **To page a** and **To page b** periodically.
7. The bug is that Server Time on each pages only shows exact one value. For example page a always be `11:02:07 AM`

### Describe the Bug

There are four ways to [revalidate](https://nextjs.org/docs/app/building-your-application/data-fetching/revalidating#error-handling-and-revalidation) with app router. For this issue, I'm reporting bug on _revalidation with `export const revalidate`_. But bug also exists in reset of the ways.

_Sorry if I use the term `revalidate` or `revalidation` incorrectly. When I meanions it I mean react on client side should trigger a event, or a request specifically, to validate whether the cache is slated and update the cache if it's staled._

## The Bug

I have two pages configured with `export const revalidate = 1` in app directory. When I navigate between these pages with `<Link />`, the revalidation is not working. Stale data is show, that is, server component is not re-executed.
Beside that, refresh the page do trigger the revalidation. So I thought it's a bug on `<Link />`

## Four ways to revalidate

I had browse though issues. But seem non of they were reporting bug with `export const revalidate`. As the [comment](https://github.com/vercel/next.js/discussions/42290#discussioncomment-5832298) from nextjs team member is asking for a dedicate issue with reproduction so I made one. Although the issue I found are not exactly the same case as mine, I think they all relevant so I list it out.

- revalidation with `fetch` ([#](https://nextjs.org/docs/app/building-your-application/data-fetching/revalidating#background-revalidation))
- revalidation with `export const revalidate` ([#](https://nextjs.org/docs/app/building-your-application/data-fetching/revalidating#background-revalidation))
- revalidatePath ([`#`](https://nextjs.org/docs/app/api-reference/functions/revalidatePath))
- revalidateTag ([`#`](https://nextjs.org/docs/app/api-reference/functions/revalidateTag))

### Expected Behavior

Compare to revalidation behavior of pages router (I also include example code in the repo with http://localhost:3000/pages-route/a) and according to [this](https://github.com/vercel/next.js/issues/43289#issuecomment-1543320829). The revalidation should be triggered from client side with `<Link />`:

- navigate to pages with a `<Link />` revalidate
- hover over a `<Link />` should revalidate
- refresh a page should revalidate

**Comment by mavic111** [comment]
That is because the <Link/> do soft navigation, so it does not refetch the data, but use cache instead.

https://github.com/vercel/next.js/issues/42991

**Comment by QzCurious** [comment]
@mavic111 Thank you for pointing me out the issue.

Seems like currently soft navigation would always use **client side cache**. I don't agree with the behavior and I think the migration guide for [Incremental Static Regeneration](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#incremental-static-regeneration-getstaticprops-with-revalidate) is kind of misleading (with pages router the page indeed updated by `<Link />`, no the case for app router).

**Comment by QzCurious** [comment]
Finally finish reading though the #42991. But the topic seems to focus on dynamic routes and mine is not. @mavic111 Do you think I should close this issue and follow how #42991 gose? 

---

Especially agree that server side cache and client side cache should somehow aligned.

> **In my opinion, client side cache should be aligned with server side cache** to ensure predictable behavior when navigating, no matter if it's soft or hard navigation.
> 
> ## Case: `revalidate` time provided
> The living time of this prefetch in the background should be the same as the one provided by the developer in the revalidation time of the page or `fetch` request, then retrigger a fetch if link hasn't been clicked yet.
> 
> ## Case: `no-cache`
> If `no-cache` is provided then prefetch should never occur (or happen only on hover/focus) as the developer expects the page or component to be rendered at request time.
> 
> ## Case: `force-cache` (default):
> Then current behavior is fine unless invalidated by the developer.
> 
> **This would also be on a per fetch call basis to ensure the granularity intended by the RSC.**
>
> https://github.com/vercel/next.js/issues/42991#issuecomment-1549681448 by @luisorbaiceta

**Comment by mavic111** [comment]
Yes, but the root cause is the same.

When I have a dynamic route, let say /posts/my-post. Then I update the content through the CMS and then trigger res.revalidate("/posts/my-post"). The data in the server will update. But in the client, cause we are using soft navigation, navigating between /posts to /posts/my-post will not refetch the data from the server, until you reload the page. 

Same as your case, export const revalidate = 1 means it should revalidate the page every 1 second, right? In the server, it does. But in the client, we use soft navigation again. So it will not refetch the data from the server.

**Comment by QzCurious** [comment]
I've almost no experience with ISR with pages router and don't know that `res.revalidate("/posts/my-post")` didn't inform client side to refetch data again (I was thinking that returning `res.revalidate()` would do the **inform**).

Yes, after read https://github.com/vercel/next.js/issues/42991 and docs again and agin. I'm now knowing that the revalidation is all about **server side cache**. It's another case for client side. So people are proposing pageTTL or cache aligning I quote above. 

Close this so nextjs team won't be overwhelming.

**Comment by QzCurious** [comment]
I think it's worth to mention. According to doc [`export const dynamic = "force-dynamic"`](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic) should behave the same as `getServerSideProps()` but it doesn't. 

![image](https://github.com/vercel/next.js/assets/38932402/0ab8f0bf-831a-4653-83ec-375749e693f0)
