### ISSUE TITLE
Images are lazy loaded based on bandwidth

### ISSUE THREAD

**Issue by stfn00** [vercel/next.js#50373]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/youthful-leftpad-edrrez

### To Reproduce

I made this sandbox:
[https://edrrez-3000.csb.app/](https://edrrez-3000.csb.app/)

You can check opening Developer tools on Network tab, setting "Slow 3G" and you can see how many images are loaded on first load.

### Describe the Bug

Test loading the site with the normal connection and the images are loaded one at a time and the lazy loading works fine.

<img width="807" alt="bug-lazy-1" src="https://github.com/vercel/next.js/assets/36002130/e0faf24c-41b2-4142-8007-301d13d3b9be">

While if we do a test in "Slow 3G" we can see that on the first loading the images are all loaded and therefore the lazy loading is not working.

<img width="804" alt="bug-lazy-2" src="https://github.com/vercel/next.js/assets/36002130/9a918cde-4fda-4c09-a648-d0208177a9b1">

### Expected Behavior

What I expect is that the images are loaded respecting the lazy loading principle. More in case the connection is lower, Instead in this case the opposite happens and when the connection is lower more images are loaded.

**Comment by JesseKoldewijn** [comment]
... duplicate of #49651
Please don't create duplicates of your own issue 👍

**Comment by stfn00** [comment]
@JesseKoldewijn I'm sorry, I know I created a duplicate, but I haven't received any kind of feedback regarding the last issue.
If some contributor would have given me a simple explanation of what the expected behavior of the component is, I would not have created another issue. 👍

**Comment by JesseKoldewijn** [comment]
> @JesseKoldewijn I'm sorry, I know I created a duplicate, but I haven't received any kind of feedback regarding the last issue. If some contributor would have given me a simple explanation of what the expected behavior of the component is, I would not have created another issue. 👍

That's not how it work. It's on you to not create duplicates of your own issue not on the contributors to throw everything aside to respond to every issue in the repo. I'd recommend to remove this duplicate and discuss your issue further in the original issue.

**Comment by stfn00** [comment]
> > @JesseKoldewijn I'm sorry, I know I created a duplicate, but I haven't received any kind of feedback regarding the last issue. If some contributor would have given me a simple explanation of what the expected behavior of the component is, I would not have created another issue. 👍
> 
> That's not how it work. It's on you to not create duplicates of your own issue not on the contributors to throw everything aside to respond to every issue in the repo. I'd recommend to remove this duplicate and discuss your issue further in the original issue.
> 
> Also keep in mind what would happen to the issue tracking if everybody would handle their issue like that. It would basically make keeping track of all the issues impossible since we would end up with 2, 3, 3 or more duplicates of the same issue which basically make resolving the actual issue harder.

OK no problem. Let's continue on the previous thread 👍 
[https://github.com/vercel/next.js/issues/49651](https://github.com/vercel/next.js/issues/49651)
