### ISSUE TITLE
[NEXT-1242] Server Action will freeze the Client app

### ISSUE THREAD

**Issue by ruohki** [vercel/next.js#50380]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
> servicedesk@0.1.0 info
> next info
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/vibrant-scooby-t51sd3

### To Reproduce

`wait.tsx`
```typescript
"use server";
export const async wait_some(ms: number) => new Promise((res) => useTimeout(() => res(), ms));
```

`button.tsx`
```typescript
"use client";

export default async Button = () => {
  const [loading, setLoading] = React.useState<boolean>(false);
  const wait_a_bit = async () => {
    setLoading(true);    
    await wait_some(2000);
    setLoading(false);
  }
  return <button onClick={wait_a_bit}>Freeze me</button>
}
```

This will freeze the frontent app in the current next release

### Describe the Bug

When doing any state updates on the frontend while a server action is invoked the whole ui freezes and stays frozen. This example uses useState Hook, but this also happens with useTransition etc.

### Expected Behavior

Not Freeze :)

### Which browser are you using? (if relevant)

chrome latest

<sub>[NEXT-1242](https://linear.app/vercel/issue/NEXT-1242/server-action-will-freeze-the-client-app)</sub>

**Comment by ruohki** [comment]
Slight addition. The delay obviously stands for some async server stuff happening.

**Comment by shuding** [comment]
Closing as it's duplicated with #49425.
