### ISSUE TITLE
generateStaticParams always triggers SSG instead of Static build

### ISSUE THREAD

**Issue by markomitranic** [vercel/next.js#50397]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
    Binaries:
      Node: 20.0.0
      npm: 9.6.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/markomitranic/generate-static-params

### To Reproduce

`npm run build` or `yarn build`

### Describe the Bug

When `generateStaticParams` is used within a page, the page won't be built as Static (as the [documentation](https://nextjs.org/docs/app/api-reference/functions/generate-static-params) claims). Instead it will be built as SSG, even when there is no obvious need for it.

```
Route (app)                                Size     First Load JS
┌ ○ /                                      144 B          77.2 kB
└ ● /[slug]                                144 B          77.2 kB
    ├ /hello
    └ /world
+ First Load JS shared by all              77.1 kB
  ├ chunks/488-1f03962ddd268029.js         24.8 kB
  ├ chunks/bce60fc1-85b580128752ff2e.js    50.5 kB
  ├ chunks/main-app-367ed85073b17288.js    216 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

Route (pages)                              Size     First Load JS
─ ○ /404                                   181 B          74.7 kB
+ First Load JS shared by all              74.5 kB
  ├ chunks/framework-8883d1e9be70c3da.js   45.1 kB
  ├ chunks/main-a40de27d8a3fc69f.js        27.6 kB
  ├ chunks/pages/_app-b555d5e1eab47959.js  195 B
  └ chunks/webpack-8074fabf81ca3fbd.js     1.61 kB

○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
```

### Expected Behavior

With Pages Router that made perfect sense, since it always had to be used in pair with `getStaticProps`, but with the App Router (and according to the [docs](https://nextjs.org/docs/app/api-reference/functions/generate-static-params)) it should simply decide to statically generate those pages.

### Which browser are you using? (if relevant)

Arc 0.105.3 (39135)

### How are you deploying your application? (if relevant)

Vercel

**Comment by sannajammeh** [comment]
`●  (SSG)     automatically generated as **static** HTML + JSON (uses getStaticProps)`

In both examples they are static.  Either intended functionality or faulty build output, but the actual HTML is valid.

**Comment by markomitranic** [comment]
@sannajammeh mhm, so as far as I understand your message, even tho it for some reason classifies them as SSG and thus not static, it also in the same time says `as static` which means that they in fact are statically generated during compilation, and not SSG?

To clarify, how I read this is that "the HTML+JSON is statically generated, but still requires a server side action to serve", but you are saying that is wrong and it doesn't in fact use SSG?

**Comment by markomitranic** [comment]
> > @sannajammeh mhm, so as far as I understand your message, even tho it for some reason classifies them as SSG and thus not static, it also in the same time says `as static` which means that they in fact are statically generated during compilation, and not SSG?
> > To clarify, how I read this is that "the HTML+JSON is statically generated, but still requires a server side action to serve", but you are saying that is wrong and it doesn't in fact use SSG?
> 
> SSG is completely static. SSR is dynamic - requires server side action to serve.

Oh, I did not know that SSG is the same as Static, thank you very much for the explanation and I'm sorry for the confusion :) I wonder tho, why do we have both Static & SSG as output, isn't it all the same thing - just a html static chunk.

**Comment by sannajammeh** [comment]
> > > @sannajammeh mhm, so as far as I understand your message, even tho it for some reason classifies them as SSG and thus not static, it also in the same time says `as static` which means that they in fact are statically generated during compilation, and not SSG?
> > > To clarify, how I read this is that "the HTML+JSON is statically generated, but still requires a server side action to serve", but you are saying that is wrong and it doesn't in fact use SSG?
> > 
> > 
> > SSG is completely static. SSR is dynamic - requires server side action to serve.
> 
> Oh, I did not know that SSG is the same as Static, thank you very much for the explanation and I'm sorry for the confusion :) I wonder tho, why do we have both Static & SSG as output, isn't it all the same thing - just a html static chunk.

It's different to signal the developer that this page was generated at build time using external data and not just plain React code.

SSG stands for Static Site Generation, so the result is static but it's generated using some data. There are also different ways the next.js router is loading the data based on how you request it. HTML + JSON will result in a few different outputs, html file, json file, JS file. When already on a hydrated client (ie you have visited the index page and you try to load `/new` or something, next will not request the HTML file, it will grab the json + the JS file and render the page in your browser.

Under the umbrella of SSG we also have ISR and on demand ISR. Here are the differences:

- Static - No generation is performed (doesn't get data from some external source)
- SSG - Generation is performed, result is same as 
- ISR: SSG on the entire page and any dynamic params generated, content is then revalidated automatically based on the timeout you've set
- On demand ISR: Same as above + programmatic invalidation use `res.revalidate(<path>)`, `revalidateTag(<cache key>)` or `revalidatePath(<path>)` from API routes.
