### ISSUE TITLE
`rewrites` cause page refresh if source matches a route in app router

### ISSUE THREAD

**Issue by QzCurious** [vercel/next.js#50390]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: 1.22.17
  pnpm: 7.17.0
Relevant packages:
  next: 13.4.5-canary.0
  eslint-config-next: 13.4.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/QzCurious/nextjs-rewrites-cause-page-refresh

### To Reproduce

https://github.com/vercel/next.js/assets/38932402/0c8f47d2-3f52-4943-b6cd-b922aacc611e

1. Make following files
    - /app/page-a/page.tsx
    - /app/page-b/page.tsx
    - /pages/pages-router/page-a/index.tsx
    - /pages/pages-router/page-b/index.tsx
2. Set `rewrites` with `beforeFiles` in next.config.js so route to /page-a and /page-b will use page files under /pages
	```js
	const nextConfig = {
	  async rewrites() {
	    return {
	      beforeFiles: [
	        { source: "/page-a", destination: "/pages-router/page-a" },
	        { source: "/page-b", destination: "/pages-router/page-b" },
	      ],
	    };
	  },
	};
	```
2. Add `<Link href="/page-b">Go to /page-b</Link>` in /pages/pages-router/page-a/index.tsx
3. Add `<Link href="/page-a">Go to /page-a</Link>` in /pages/pages-router/page-b/index.tsx
4. `next dev` or `next build && next start`
5. Go to http://localhost:3000/page-a
6. Click the `<Link />`
7. **Page is refreshed** instead of being client side routed

### Describe the Bug

Click on `<Link />` the page is refreshed.

Notice that if the source of rewrite is not matching a route in app directory. This bug won't happen.

https://github.com/vercel/next.js/assets/38932402/59f41d91-421a-46a5-9aae-6fe6898ecb1b

### Expected Behavior

Click on `<Link />` should not cause page refresh, even if the `href` is set to a url that is `rewrites`-ed.

**Comment by blackpanther1881** [comment]
facing same issue

**Comment by QzCurious** [comment]
@blackpanther1881 I'm currently use file base routes as fallback and rewrite urls to that.

- /app/app-router/page-a/page.tsx
- /app/app-router/page-b/page.tsx
- /pages/pages-router/page-a/index.tsx
- /pages/pages-router/page-b/index.tsx

```ts
const nextConfig = {
  async rewrites() {
    return {
      beforeFiles: [
        { source: "/page-a", destination: "/pages-router/page-a" },
        { source: "/page-b", destination: "/pages-router/page-b" },
      ],
    };
  },
};
```

This way, there is no overlapped url so solve the problem. 

_Note that navigate between pages routes and app routes still get page refreshed. (It might work as expected, similar to [multiple root layout](https://nextjs.org/docs/app/building-your-application/routing/route-groups#creating-multiple-root-layouts))_
