### ISSUE TITLE
Multi-line environment variable not working

### ISSUE THREAD

**Issue by reza-ebrahimi** [vercel/next.js#50409]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #79~20.04.1-Ubuntu SMP Thu Apr 20 22:12:07 UTC 2023
Binaries:
  Node: 20.2.0
  npm: 9.6.6
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.4.4
  eslint-config-next: 13.4.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.5
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/adoring-fog-4nkuzo

### To Reproduce

-   [Open sandbox](https://codesandbox.io/p/sandbox/adoring-fog-4nkuzo)
- Navigate to `/env` route.
- Check the logs

### Describe the Bug

The output of `console.log(process.env.GITHUB_PRIVATE_KEY)` is `"-----BEGIN PRIVATE KEY-----`.
If you look at the `.env` file, only the first line of environment variable is printed into console.

```js
console.log(process.env.GITHUB_PRIVATE_KEY);
// output: "-----BEGIN PRIVATE KEY-----
```

Note: The private key is invalidated.

### Expected Behavior

Printing all lines as it is.

**Comment by joshtinhan** [comment]
This issue will be fixed if PR #38481 got merged.

**Comment by balazsorban44** [comment]
Correct. We cannot merge it currently, as it would be a breaking change. But you can follow the above-mentioned PR for a resolution.

**Comment by reza-ebrahimi** [comment]
@balazsorban44 As you said that PR is still not merged, so why this issue is marked `as completed` then `closed`?
