### ISSUE TITLE
Docs: Typo within an <a> tag resulting in a 404 Error within the App Router Docs

### ISSUE THREAD

**Issue by brianschnee** [vercel/next.js#50411]
### What is the improvement or update you wish to see?

# Sumary
A broken link in the new App Router documentation resulted in a `404 error`.

## Location

`App Router > Building Your Application > Routing > Pages and Layouts`

Specifically, in the Layouts section: https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts, there is a bullet point within the "Good to know" subsection that reads:

> Layouts do not have access to the current route segment(s). To access route segments, you can use [useSelectedLayoutSegment](https://nextjs.org/docs/app/building-your-application/routing/docs/app/api-reference/functions/use-selected-layout-segment) or [useSelectedLayoutSegments](https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segments) in a Client Component

## Issue

The first link for `useSelectedLayoutSegment` does not route properly.
The `<a>` tag has the following code:

`<a href="docs/app/api-reference/functions/use-selected-layout-segment"><code>useSelectedLayoutSegment</code></a>`

which results in the URL: "https://nextjs.org/docs/app/building-your-application/routing/docs/app/api-reference/functions/use-selected-layout-segment"

## Solution

There is a missing `/` (slash) before the word `docs`. 

Change "docs/app/api-reference..." to "/docs/app/api-reference..."

### Is there any context that might help us understand?

The information (summary, location, issue, and solution) has been provided within the "What is the improvement or update you wish to see?" question.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts

**Comment by HelpMe-Pls** [comment]
I think they embedded the wrong URL.
[This](https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segment) is the one.

**Comment by manovotny** [comment]
Thanks for reporting it! This was fixed somewhere along the way. 😊
