### ISSUE TITLE
`Link` is not prefetching on hover if `prefetch=false` is given - as per documentation

### ISSUE THREAD

**Issue by adiathasan** [vercel/next.js#50412]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/adiathasan/mui-react-hook-form-plus/tree/master/next-server-components-demo

### To Reproduce

- First add a link to another page and set `<Link prefetch={false} href="/your-route" />` - by default `prefetch=true`

```tsx
import Link from 'next/link';

export default function Home() {
	return (
		<div>
			<Link prefetch={false} href='/mui'>
				MUI
			</Link>
		</div>
	);
}

```

- create `/your-route` directories as per suggested in the `app` dir 

<img width="301" alt="image" src="https://github.com/vercel/next.js/assets/61478071/9b863fb0-28f5-46ed-8aae-ccb5757f9a33">

- terminal 👉 `yarn build`

- open port `http://localhost:3000`

- inspect dev tools

- go to network tab

- see `hovering` on the `link` that points to `/your-route`

### Describe the Bug

It is being said that in the `Link` component if we set `prefetch=false` it will prefetch the route on hover. Below is the ss of what's coming from the description of the prop. See image v

[<img width="1235" alt="Screenshot 2023-05-27 at 5 41 42 AM" src="https://github.com/vercel/next.js/assets/61478071/5e4c868c-6c66-42d4-a645-e638733eb962">](url)

But it's not fetching the `route` on `hover` in the background

### Expected Behavior

Should fetch the page on `hover` if `prefetch=false` is set on `hover` in `Link` / `next/link`

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Local build, next start

**Comment by joacub** [comment]
That’s is disabled for app router

if (!prefetchEnabled && isAppRouter) {
          return
        }

**Comment by adiathasan** [comment]
> That’s is disabled for app router
> 
> if (!prefetchEnabled && isAppRouter) { return }

Why is that, can anyone explain?

**Comment by deepakrh185** [comment]
To be clear that prefetching will not work in dev mode will only works in production mode @adiathasan

**Comment by adiathasan** [comment]
```

> To be clear that prefetching will not work in dev mode will only works in production mode @adiathasan

Yeah, I have built the app and tried it to be clear if you see above.

**Comment by ts213** [comment]
> > That’s is disabled for app router
> > if (!prefetchEnabled && isAppRouter) { return }
> 
> Why is that, can anyone explain?

I'm also interested.

**Comment by TomJD** [comment]
Any news on this? 

It is a bug, or the documentation needs updating that `prefetch={false}` does not actually prefetch on hover.

I am running the app in production, all other links in the viewport prefetch as expected and written in docs.

**Comment by oliviertassinari** [comment]
I would expect that prefetch on hover continue to work. It seems another regression like #61816.

**Comment by heath-freenome** [comment]
Honestly, I'm curious WHY it would prefetch on hover if the link is being told never to prefetch?!

**Comment by ztanner** [comment]
Hi folks, to close the loop on this:

In App Router, `prefetch={false}` will completely disable prefetching, even on hover. This is documented [here](https://nextjs.org/docs/app/api-reference/components/link#prefetch) as well as in the JSDOC comment [here](https://github.com/vercel/next.js/blob/21ffe10ebdc27cabe319099db19daf23d9daaacc/packages/next/src/client/link.tsx#L77-L85).

In Pages Router, `prefetch={false}` will still prefetch when hovering. 

For any discussions or feature requests about this behavior, it's better suited for the [Discussions](https://github.com/vercel/next.js/discussions) board rather than a bug report.
