### ISSUE TITLE
useRouter events: are not working on next js 13  

### ISSUE THREAD

**Issue by nahidhasan141400** [vercel/next.js#50427]
### What is the improvement or update you wish to see?

it's to important future in  the framework  for make a batter user experience 
so pleases add the router change event   

### Is there any context that might help us understand?

`Router.events.on `

not working properly

**Comment by altechzilla** [comment]
You can use the `const pathname = usePathname()` hook from `next/navigation` and then a useEffect that listens to that.

**Comment by ChandanJal** [comment]
**Hey there** ✋  ! I don't think there is any options for listening to the router events. But you can provide more details what you want to do ?

**Comment by balazsorban44** [comment]
Please refer to the documentation: https://nextjs.org/docs/app/api-reference/functions/use-router#router-events

**Comment by nahidhasan141400** [comment]
> **Hey there** ✋ ! I don't think there is any options for listening to the router events. But you can provide more details what you want to do ?

i want make a progress bar loader top of the site

**Comment by ChandanJal** [comment]
> > **Hey there** ✋ ! I don't think there is any options for listening to the router events. But you can provide more details what you want to do ?
> 
> i want make a progress bar loader top of the site

You can use `loading.js` file inside the directory or routes that you want to show progress bar.
