### ISSUE TITLE
Compiler Error using TypeScript: "getServerSideProps" is not supported 

### ISSUE THREAD

**Issue by opendeluxe** [vercel/next.js#50424]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/opendeluxe/nextjs-typescript-issue

### To Reproduce

```
git clone https://github.com/opendeluxe/nextjs-typescript-issue
cd nextjs-typescript-issue
yarn install
yarn dev

open localhost:3000
```

The repository is taken from the reproduction-template: https://github.com/vercel/next.js/tree/canary/examples/reproduction-template-app-dir.

We can also easily reproduce with:

1. create a new nextjs application, using TypeScript
2. head to the docs for Data Fetching: https://nextjs.org/docs/app/building-your-application/data-fetching
3. copy example code from that side into an existing page:

```
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next';

export const getStaticProps: GetStaticProps = async (context) => {
    return [];
};

export const getStaticPaths: GetStaticPaths = async () => {
    // ...
    return [];
};

export const getServerSideProps: GetServerSideProps = async (context) => {
    // ...
    return [];
};

/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  // ...
}
```

### Describe the Bug

Any use of functions like `getServerSideProps` will not compile when TypeScript will be used.

Function `getServerSideProps` can't get compiled using TypeScript. It works only when building NextJS as pure JavaScript application like the official Wordpress_Example.

But using this with a new setup NextJS configured with TypeScript, it gives the following error:

```
- error ./app/page.tsx
ReactServerComponentsError:

"getStaticProps" is not supported in app/. Read more: https://nextjs.org/docs/app/building-your-application/data-fetching
```

### Expected Behavior

It compiles. 

### Which browser are you using? (if relevant)

Chrome and Safari, latest

**Comment by shuding** [comment]
Hi! As mentioned in the docs, 

> Previous Next.js data fetching methods such as [getServerSideProps](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props), [getStaticProps](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props), and [getInitialProps](https://nextjs.org/docs/pages/api-reference/functions/get-initial-props) are not supported in the new App Router

**Comment by opendeluxe** [comment]
> Hi! As mentioned in the docs,
> 
> > Previous Next.js data fetching methods such as [getServerSideProps](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props), [getStaticProps](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props), and [getInitialProps](https://nextjs.org/docs/pages/api-reference/functions/get-initial-props) are not supported in the new App Router

I see, thank you. Unfortunately, the old examples still use the old approach. Is there something available showing the new methods?

**Comment by thi-days** [comment]
I'm facing the same issue here, and the docs are showing the old way of doing it. I need to generate a page statically for my project and now don't how to do it using the new App Router.

**Comment by AarNtyon** [comment]
> 
hi bro, how's it going now? have you solved it yet?

**Comment by nick4fake** [comment]
@shuding So.. What is the recommended approach? All docs, all references use it and we are a bit lost.

**Comment by thi-days** [comment]
@AarNtyon Man, I haven't solved the issue using the new App Router yet. I'm currently using the legacy router and still waiting for a response on this thread. IMO, the docs should give us the new approach. =/

**Comment by opendeluxe** [comment]
This issue should not get closed so quickly as the issues still persists, but produces different errors now. 

Since the documentation on the Data-Fetching page still shows Code that is absolutely not working with latest nextJS version, I filed another issue:

https://github.com/vercel/next.js/issues/52914

Please provide us some more documentation or better example apps that work with latest versions. The current status is not really helpful and can't be used at all.

**Comment by itinance** [comment]
@opendeluxe see my comment https://github.com/vercel/next.js/issues/52914#issuecomment-1642855212

**Comment by odaytelbany** [comment]
@opendeluxe did you find the solution ?

**Comment by odaytelbany** [comment]
[Here](https://github.com/odaytelbany/instagram-clone/issues/1) is the solution, closed issue✔
