### ISSUE TITLE
Cannot read properties of null (reading 'useState') with Context Wrapper

### ISSUE THREAD

**Issue by jeffrafter** [vercel/next.js#50438]
Re-opening #48518 (it is still happening)

@huozhi 👋 

Sorry for reopening this one but it is definitely still happening. I had time to bisect through the versions today (though I haven't found the cause yet). This broke for non-vercel deploys between `13.3.1-canary.8` (works) and `13.3.1-canary.9` (broken). I'd like to still look into this one if possible. I don't have a standalone re-production but was able to reproduce this with the CodeSandbox from @dprothero (I opened the code sandbox  and started it using his command, and then opened the page he suggested and saw the error). 

I don't think you can reproduce this as standalone. My hunch is this is something in the response prep.

**Comment by jeffrafter** [comment]
Also wanted to say I would be happy to 🍐 with or give access to any of the team (you are all obviously my favorite people ❤️) as I have a production example that reproduces the problem.

**Comment by jeffrafter** [comment]
I'm secretly suspicious of https://github.com/vercel/next.js/pull/48478 as I have a hunch this is related to a problem with the bundled react versus non-bundled react (18.2.0 versus 18.3.0) and something around generating the response that will be hydrated.

**Comment by thimmey** [comment]
Do you have a workaround for this? I wanted ro give next.js a try this weekend but nothing is working (tried several versions of 13.2.x and 13.4.x, including canary for the next installation and the next .... Posted my issue here https://github.com/vercel/next.js/issues/50434

**Comment by huozhi** [comment]
Close per https://github.com/vercel/next.js/issues/48518#issuecomment-1566069264
