### ISSUE TITLE
Dev request logs don't work on edge runtime

### ISSUE THREAD

**Issue by psikoi** [vercel/next.js#50439]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/psikoi/nextjs-edge-fetch-logs-reproduction

### To Reproduce

Using the example repository I've provided, just run it locally with `next dev`, and then navigate between `/node` and `/edge` to see the difference in logs.

### Describe the Bug

When running locally, fetching timing logs will not be logged if `runtime` is set to `edge`

### Expected Behavior

I'd expect these logs to still be logged in development despite the chosen runtime environment.

### Which browser are you using? (if relevant)

Google Chrome Version 112.0.5615.137

**Comment by SaveliiLukash** [comment]
Experiencing the same issue.

Getting useful fetch logs, but only when using **node** runtime:
<img width="867" alt="image" src="https://github.com/vercel/next.js/assets/78015938/9eeb5476-c229-4a2a-96a9-3c8ac7f75a96">

Getting **no logs** when runtime is set to **edge**.

As of today it's `"next": "13.4.6"`

**Comment by ImmutablePerson** [comment]
I also facing this problem. 

Detailed fetch logs do not work when the runtime is set to edge.
<img width="480" alt="Screenshot 2023-08-17 at 14 17 06" src="https://github.com/vercel/next.js/assets/76953627/3dbca9df-6f40-46df-a96e-8f1f7dc27482">

Next version: `"next": "13.4.13"`
