### ISSUE TITLE
Relative URI Fragments in Next Link Component not working

### ISSUE THREAD

**Issue by DerPlayer2001** [vercel/next.js#50452]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/DerPlayer2001/next-relative-link-issue

### To Reproduce

Visit `/issue` and left klick on the "To Bottom" button you now land on `/#bottom` instad of `/issue#bottom`.

### Describe the Bug

If you load the reproduction code and visit `/issue` you have two buttons(created with next/link) with relative Fragment links( `#bottom` & `#top` ). The Html Anchor Elements display the correct link and when clicked with middle mouse button also Redirects to `/issue#bottom`. But when using left click it redirects to `/#bottom`. This Bug first appeared when switching to the new app directory.

### Expected Behavior

A `<Link/>`Element with `href="#bottom"` on the page `/issue` should redirect to `/issue#bottom` as it's Anchor counterpart does. And with `href="/#bottom"` land on `/#bottom`. There shouldn't be a discrepancy in the resulting URL when using middle or left mouse button click.

**Comment by BaffinLee** [comment]
There is an onClick handler in the Link component, called `router.push('#bottom')`, not sure if it's expected.

Maybe you should just use a tag.

![image](https://github.com/vercel/next.js/assets/17738556/30f98163-f8d2-4183-8a38-43d2548e3330)

**Comment by DerPlayer2001** [comment]
> There is an onClick handler in the Link component, called `router.push('#bottom')`, not sure if it's expected.

Yes I'm aware that next/link uses an `onClick` handler to redirect. In my Opinion the resulting Path should match up with respective Anchor Tag Path.

**Comment by saikatmitra91** [comment]
faced a similar issue in relative paths while using mdx and nextjs

in case of paths starting with `./foo`, the path gets updated to `/{basePath}/foo` instead of the path being relative to current router path.
