### ISSUE TITLE
classes of html element

### ISSUE THREAD

**Issue by dkirchhof** [vercel/next.js#50455]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed May 17 14:00:55 UTC 2023
    Binaries:
      Node: 19.9.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-app-dir

### To Reproduce

use "create-next-app" start the dev server and open any page (http://localhost:3000/).

### Describe the Bug

For some reason, nextjs injects some hashed class names to the html element. This produces the following warning:

"Warning: Extra attributes from the server: class"

### Expected Behavior

The html element should just have the classes which I add in the root layout or it shouldn't throw the hydration(?) error / warning.

**Comment by shuding** [comment]
It seems like you don't have any props in the `<html>` element, could you update the reproduction?

**Comment by dkirchhof** [comment]
Well, it is the default `layout` file in the app directory.

```tsx
import './styles.css';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface IProps {
    children: React.ReactNode;
}


export default (props: IProps) => (
    <html lang="en">
        <body>{props.children}</body>
    </html>
);
```

If I pass any custom class, the hashed classes will be appended.

**Comment by shuding** [comment]
@dkirchhof I still don't get what you mean, here's what I'm seeing (which is correct):

<img width="1559" alt="CleanShot-2023-06-08-NxTngd8e@2x" src="https://github.com/vercel/next.js/assets/3676859/56e5d985-efcc-4bd6-8f0c-a1f123a00e96">

Please make sure to create a reproduction does proof "nextjs injects some hashed class names to the html element", and we will fix.

**Comment by dkirchhof** [comment]
Okay, here is some more information:

Here is the bootstrap step:
![image](https://github.com/vercel/next.js/assets/2778643/12551e15-3aab-4efd-85e9-011ebc63d418)

When I run the app via `npm run dev` I will get this error:
![image](https://github.com/vercel/next.js/assets/2778643/fec3f54d-72a0-4afa-8b5d-0d1e29792f37)

As you can see, there are some classes attached to the html element.

Here is the code of my root layout (default code):
```js
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
```

And here is a repo to reproduce the bug: https://github.com/dkirchhof/nextjs-html-class-bug

**Comment by dkirchhof** [comment]
Just realized that issue is on all websites I open with my browser. So I found out, that it is a browser extension which injects these classes :man_facepalming:
