### ISSUE TITLE
Prefetch block the thread for 1-2 seconds 

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#50457]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Last canary
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

No response 

### To Reproduce

Prefetching links block the thread for seconds, try offloading in a worker or do this in batches more slowly to not block the thread.

When you scroll you also see that some parts take longer to load because of this. 

### Describe the Bug

No response 

### Expected Behavior

Thread not blocked

**Comment by michaelhays** [comment]
I'm legitimately nervous about hovering over links when building in development. Sometimes I'll move my mouse over the side nav of our app, which prefetches several pages, and locks up my application for 10+ seconds.

The app directory clearly has some performance issues that need to be addressed, but in the meantime, is there a way to disable prefetching entirely in development?

**Comment by ivanhueso** [comment]
I have set  set `prefetch={false}` in my development environment and when i click on `<Link ` it skip the `loading.js` and it show a complete blank page for ~ 2 to 5 seconds and then it loads the next page following by the loading.js and the page.js content.  
This happen to different links  at different moments which makes me hard to find a pattern. I think it comes from Next.js directly.

**Comment by joacub** [comment]
we disabled it, prefetch works really bad and there is no performance noticiable gains
