### ISSUE TITLE
middleware breaks res.revalidate

### ISSUE THREAD

**Issue by jwalcher** [vercel/next.js#50464]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/jwalcher/middle-reval

### To Reproduce

1. create `/app/time/page.jsx`
```
 export default async function Page() {
    const data = await (await fetch("https://www.timeapi.io/api/Time/current/zone?timeZone=Europe/Amsterdam")).json();
    return (<h1>Time in Amsterdam is {data.hour + ":" + data.minute + ":" + data.seconds}</h1>);
  }
```
2. let `/api/revalidate.js` be
```
export default async function handler(req, res) {
  await res.revalidate("/time");
  return res.json({ revalidated: true });
}
```
3. refresh `/time` and check timestamp shows data fetched at last call to `/api/revalidate`
4. insert `middleware.js`
```
import { NextResponse } from "next/server";
export const config = { matcher: ["/((?!api).*)"], };
export default function middleware(request) {
  const rewritePath = "/time"
  const rewriteUrl = new URL(rewritePath, request.nextUrl);
  return NextResponse.rewrite(rewriteUrl);
} 
```
and return to step 3
5. exclude `/time` from middleware by replacing negative lookahead with `(?!api|time)` in matcher, and return to step 3

### Describe the Bug

1. active middleware breaks `res.revalidate()`, throws `Error: Invalid response 500 at NextNodeServer.revalidate`
2. note that I am **not** trying to revalidate a path **via** middleware rewrite, but indeed calling `res.revalidate()` on the _exact path_, exactly as described in the [docs](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#on-demand-revalidation)
3. excluding revalidation path from middleware restores functionality

### Expected Behavior

1. revalidation should succeed independent of any middleware active on revalidation path
2. the docs claim that `middleware won't be executed for On-Demand ISR requests`. Somehow this does not seem to be the case.

**Comment by ChandanJal** [comment]
Hey @jwalcher I see you are using app directory. 

Please refer the following doc
1. https://nextjs.org/docs/app/api-reference/file-conventions/route
2. https://nextjs.org/docs/app/building-your-application/routing/router-handlers

And create an `api` folder inside your app directory. Inside the `api` directory create another folder called `time` or `revalidate` whatever you want to call it. After that create file called `route.js`

`app > api > (time | revalidate) > route.js`

```
import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";

export async function GET(request) {
  revalidatePath("/time");
  return NextResponse.json({ revalidated: true });
}
```

Past this code inside the file that you just created & execute this to get the suitable result.

Lots have change from `next -v12` so read it properly.

**Comment by jwalcher** [comment]
Hey @ChandanJal Thanks for advice! I tried many things, including migrating the revalidation to `app` directory, and described the various failure modes in a previous bug report https://github.com/vercel/next.js/issues/49955 

Fact is, `revaldiatePath` does not work on dynamics routes at the moment (and I have lot of dynamic routes in my production). This is known and already under active investigation, see for example https://github.com/vercel/next.js/issues/49387#issuecomment-1568280336

So I made a separate issue trying to salvage revalidation of `app` router with `res.revalidate` in `pages`. I know this is a bit hybrid, but it was working up until [v13.3.2-canary.7](https://github.com/vercel/next.js/releases/tag/v13.3.2-canary.6)

I can probably wait until `revalidatePath` works properly, but I suspect the issue I describe also affects revalidation in `pages` router.

**Comment by duongductrong** [comment]
Do you guys can use route segments config like dynamic, revalidate? It still not working on latest ver, the data not fetching if I set revalidate=false

**Comment by jwalcher** [comment]
For on-demand revalidation, I don't think any such config is necessary according to the docs. 
Last time I tested background revalidation, it was working fine however.

**Comment by jwalcher** [comment]
**Update** @ChandanJal I tested `res.revalidate` on the old pages router and it indeed still works even in the presence of middleware. So it's only my hybrid revalidation scheme that's broken (while `revalidatePath` is not yet working). So the title of the issue is correct, but perhaps it'll never be fixed.

**Comment by ChandanJal** [comment]
@jwalcher read this, maybe this could help you
https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#custom-invocation-using-starttransition

![1212121](https://github.com/vercel/next.js/assets/97095857/93991034-af73-465c-bbd1-7a0148067529)

**Comment by jwalcher** [comment]
?

**Comment by jwalcher** [comment]
issue gone in 14.0.0
