### ISSUE TITLE
React Minify error , hydration error in next.js SSR firebase , firestore ,firebase admin token and nookies

### ISSUE THREAD

**Issue by thanhtutzaw** [vercel/next.js#50468]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release ( Currently Next.js 13.0.6 )

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      eslint-config-next: 13.0.6
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.0.6", newest: "13.4.5-canary.0".
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/thanhtutzaw/facebook-ui

### To Reproduce

To run this project, install it locally using npm:
### You will need to setup firebase , firestore ,firebase admin 
$ git clone https://github.com/thanhtutzaw/facebook-ui.git
$ cd facebook-ui
$ cp .env.local.example .env.local
$ npm install
$ npm run dev

### Describe the Bug

Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Ucaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
 
### Which browser are you using? (if relevant)

Brave ( Windows )

### How are you deploying your application? (if relevant)

Vercel

**Comment by thanhtutzaw** [comment]
### Looks like my date from SSR making this error . Now the error is gone .
#
![Screenshot (178)](https://github.com/vercel/next.js/assets/71011043/167613ea-04d9-443a-ac1a-761931ee2b0d)

**Comment by jovinlidan** [comment]
> ### Looks like my date from SSR making this error . Now the error is gone .
> ![Screenshot (178)](https://user-images.githubusercontent.com/71011043/241641502-167613ea-04d9-443a-ac1a-761931ee2b0d.png)

toLocaleDateString fixes your error?
