### ISSUE TITLE
Docs: Deploy NextJs Application with Server and API Route code to Windows IIS

### ISSUE THREAD

**Issue by ravenet** [vercel/next.js#50469]
### What is the improvement or update you wish to see?

Hello Team,

As next js is leading in many ways to build a website, but I fee there is no a concreate example it is can deploy with API Route and Server side code to a windows server it still a major platform most of the people use it..

- 1 Static wesbite is deployment no issues
- When we add api route or server side code, deployment does not work at all in many cases.
- Please create a useful doc to how it is combined and deployed to a windows server.

### Is there any context that might help us understand?

API Route and Server Side code

**Comment by BaffinLee** [comment]
This guide on stackoverflow might help you. https://stackoverflow.com/questions/46266609/host-node-js-on-windows-server-iis

Your are going to need [iisnode](https://github.com/Azure/iisnode)

**Comment by ravenet** [comment]
@BaffinLee 

Thank you and  in fact, I have visited this link earlier. But, I am looking a working guide from next team as they are mkaing very very good progress in the SSR rendering with app router.

Thanks
