### ISSUE TITLE
create-next-app --no-app option not being respected or documented

### ISSUE THREAD

**Issue by mattlgroff** [vercel/next.js#50478]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Windows WSL2 Ubuntu 22.04

`next info` not applicable, cli issue.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

N/A, CLI issue.

### To Reproduce

create-next-app my-app --ts --eslint --no-app --use-npm --src-dir --import-alias "@deps/*" --tailwind

### Describe the Bug

There is no documentation on what to pass if you do not want the app directory when trying to run `create-next-app` 

The  `--app` is documented:
```markdown
  --app

    Initialize as an App Router project.
```

However looking at the code, there is an option for `--no-app`, however it's not documented and it's not being respected either.

```bash
create-next-app my-app --ts --eslint --no-app --use-npm --src-dir --import-alias "@deps/*" --tailwind
? Would you like to use experimental `app/` directory with this project? › No / Yes
```

In the next.js codebase:
```typescript
    if (!process.argv.includes('--app') && !process.argv.includes('--no-app')) {
      if (ciInfo.isCI) {
        program.app = true
      } else {
        const styledAppDir = chalk.hex('#007acc')('App Router')
        const { appRouter } = await prompts({
          onState: onPromptState,
          type: 'toggle',
          name: 'appRouter',
          message: `Use ${styledAppDir} (recommended)?`,
          initial: true,
          active: 'Yes',
          inactive: 'No',
        })
        program.app = Boolean(appRouter)
      }
    }
```

### Expected Behavior

`--no-app` should be documented & it should not prompt me about the app directory. It should respect the flag and go with the pages directory.

**Comment by timicienio** [comment]
The same case for --no-app and --no-src-dir. 

Been looking for these options for weeks before actually discovering it, this is indeed a problem needed to be solved.

**Comment by balazsorban44** [comment]
This has been mentioned here https://nextjs.org/docs/app/api-reference/create-next-app#non-interactive:~:text=Further%2C%20you%20can,).
