### ISSUE TITLE
Docs: Wrong link on nextjs.org landing page.

### ISSUE THREAD

**Issue by TobiObeck** [vercel/next.js#50483]
### What is the improvement or update you wish to see?

"Client and Server Rendering" card links to ["Data fetching"](https://nextjs.org/docs/basic-features/data-fetching/overview) on the https://nextjs.org/ landing page.

I assume, instead it should link to:
- https://nextjs.org/docs/app/building-your-application/rendering
- or https://nextjs.org/docs/pages/building-your-application/rendering
- the redirect seems broken: https://nextjs.org/docs/building-your-application/rendering

### Is there any context that might help us understand?

![image](https://github.com/vercel/next.js/assets/13554426/90ac22ec-e54e-4e5f-85f6-8cf9040c9156)

### Does the docs page already exist? Please link to it.

https://nextjs.org/

**Comment by skmohammadi** [comment]
❤️
