### ISSUE TITLE
Upgrade next from 13.4.3 to 13.4.4 startup crash, because of websocket error in dev mode due to NODE_OPTIONS='--inspect'

### ISSUE THREAD

**Issue by julianklumpers** [vercel/next.js#50489]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/julianklumpers/reproduction-app

### To Reproduce

- yarn dev
- npm run dev
- pnpm dev

### Describe the Bug

In the release log of 13.4.4 is a commit that says `NODE_OPTIONS='--inspect'` is fixed, see: 
- fix: NODE_OPTIONS='--inspect' in next dev for debugging: https://github.com/vercel/next.js/pull/48019

Passing `NODE_OPTIONS='--inspect'` causes a websocket error and the app cannot start.

### Expected Behavior

Running dev with NODE_OPTIONS='--inspect' starts the app without websocket error and inspect mode works correctly.

### Which browser are you using? (if relevant)

Google Chrome Version 113.0.5672.92

### How are you deploying your application? (if relevant)

Digital Ocean

**Comment by gusfune** [comment]
I can confirm I could replicate, was just a matter of passing `NODE_OPTIONS='--inspect'` to my startup script.

**Comment by stevejcox** [comment]
Seeing this WasmHash error too. Has come and gone in previous versions, but is back again.

**Comment by monowai** [comment]
I'm starting with `NODE_OPTIONS='--inspect' next dev` and still see the error as at 13.4.4  when I navigate to `http://localhost:3000` - `WebSockets request was expected`

```
Debugger listening on ws://127.0.0.1:9229/fedf6935-9af5-42cf-bfc4-3914287169bf
...
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
Debugger listening on ws://127.0.0.1:62395/f269290f-eb18-45bc-93cf-f528594a995d
```

Connecting my node debugger to `9229`, logs this message:
`- ready started server on 0.0.0.0:3000, url: http://localhost:3000`

Looks like maybe websockets are expected for both ports - 9229 and 62395?

**Comment by VanTanev** [comment]
Can confirm, we're seeing the same error on MacOS when running `NODE_OPTIONS='--inspect' next dev -p 3000`
```
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: N/A
      pnpm: 7.32.4
    Relevant packages:
      next: 13.4.5-canary.6
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

**Comment by manuelbarzi** [comment]
same error in my mac. i cannot inspect server-side code. the command `NODE_OPTIONS='--inspect' next dev` does not seem to work in the current version of next 13. any suggestions from the development team?

**Comment by hassanqureshi2** [comment]
Its working without `NODE_OPTIONS`

**Comment by Geminii** [comment]
Same problem in our company since we upgrade to `13.4.4` version 😭

**Comment by andresgutgon** [comment]
@Cow258 could be this related? https://github.com/vercel/next.js/pull/48019 I saw it was added on `13.4.4`

**Comment by semy** [comment]
Just upgrade to 13.4.5

**Comment by andresgutgon** [comment]
I was on `13.4.5` and was getting that error. Can you link to the commit or PR where this was fixed. For me was not working
<img width="542" alt="image" src="https://github.com/vercel/next.js/assets/49499/57104db9-fa00-44f8-837c-164002e8e5ae">

**Comment by Cow258** [comment]
@andresgutgon
I don't think it related to #48019.
I installed and tested on [v13.4.4-canary.5](https://github.com/vercel/next.js/releases/tag/v13.4.4-canary.5) and it is working well.
So the issue should be after than 24 May.
```
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: 1.22.19
      pnpm: 8.5.0
    Relevant packages:
      next: 13.4.4-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

**Comment by Cow258** [comment]
I can confirm this issue is 100% related to #50248 
Tested vserions:
v13.4.4-canary.5 -> GOOD
v13.4.4-canary.6 -> GOOD
v13.4.4-canary.7 -> WebSockets request was expected
![image](https://github.com/vercel/next.js/assets/14261588/821e7603-a5c4-4957-8056-9b515d3f7f38)

**Comment by Cow258** [comment]
I think the conflict happens on debug port or HTTP port or IPC port

**Comment by Cow258** [comment]
I'm attempting to fix this issue
![image](https://github.com/vercel/next.js/assets/14261588/75a20ad5-70d8-4393-baf0-3033455bde02)

**Comment by cray2015** [comment]
despite this issue being fixed in 13.4.4. I still see this issue many times. The current workaround for me is to remove the `NODE_OPTIONS='--inspect'` flag
run the dev or start scripts without it after that it should run successfully. Once it runs you can stop the process re add the above flag and try to run it back the websocket error should be solved. I have tried this procedure 3-4 times and it has helped me to run the solution with the flag

**Comment by Cow258** [comment]
@cray2015 This issue should be fixed in the next release or above version v13.4.8-canary.3

**Comment by Geminii** [comment]
@Cow258 Thanks for the fix and information, really appreciate 🙏

**Comment by rodrigocastromartinez** [comment]
I've tested with next 13.4.10 and with 13.4.8-canary.3, and the inspector doesn't work yet. any updates on this?
