### ISSUE TITLE
Upgrading from 13.3.1 to ^13.4.4 causes react error "Warning: Invalid hook call."

### ISSUE THREAD

**Issue by Cherikon** [vercel/next.js#50486]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
To see a list of supported npm commands, run:
  npm help
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.3.1
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue or a replay of the bug

n\a

### To Reproduce

Upgrading from next 13.3.1 to ^13.4.4.
Start dev app.
Open page with react components

### Describe the Bug

In my nextjs app i use a React components. which is located in another lib (with node_modules).
I import react app in next dynamically, after that i start next app (next dev) and open page with this react component and i get error
![image](https://github.com/vercel/next.js/assets/71213965/b0319a58-c5c0-4f31-873b-9b3e5bfaaf9e)
I can't use canary relis because i use @storybook/nextjs@7.0.18

### Expected Behavior

The app starts normally

**Comment by deepakrh185** [comment]
checkout the initial hook call it breaks the rule and so kindly share the repo it will be good to short out :)

**Comment by Cherikon** [comment]
React component that causes the error works correctly in another react app

**Comment by deepakrh185** [comment]
It is hard to tell without the code

**Comment by Cherikon** [comment]
According to the company's rules, I can not provide the code base

**Comment by deepakrh185** [comment]
okay just check the parent components hook call

**Comment by altechzilla** [comment]
Do you have any transpiled modules or modularized imports?

**Comment by Cherikon** [comment]
I can give you my config files.
Webpack and babel config in react app:
webpack.config.js
`const nodeExternals = require('webpack-node-externals');

const config = {
  entry: './src/index.tsx',
  externals: [nodeExternals()],
  output: {
    filename: 'index.js',
    libraryTarget: 'commonjs'
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader'
        ]
      },
      {
        test: /\.ts(x)?$/,
        loader: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.svg|png$/,
        loader: 'url-loader'
      }
    ]
  },
  resolve: {
    extensions: [
      '.tsx',
      '.ts',
      '.js',
      '.jsx'
    ]
  }
};

module.exports = config;`
.babelrc
`{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": false
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    ["babel-plugin-styled-components", {
      "namespace": "credit-page"
    }]
  ]
}`

In next app:
next.config.js
`require('dotenv').config();

module.exports = {
  env: {
    IS_LOCAL: process.env.IS_LOCAL,
    API_WEB_URL: process.env.API_WEB_URL,
    API_DATA_URL: process.env.API_DATA_URL,
    API_SALES_URL: process.env.API_SALES_URL,
  },
  transpilePackages: ['ubrr-widgets/constantApi'],
  // https://nextjs.org/docs/api-reference/next/image
  // https://nextjs.org/docs/basic-features/image-optimization
  images: {
    formats: ['image/avif', 'image/webp'],
    domains: ['my_domains'],
  },
};
`
.babelrc
`{
  "presets": ["next/babel"],
  "plugins": [
    [
      "inline-react-svg",
      {
        "svgo": {
          "plugins": [
            {
              "name": "preset-default",
              "params": {
                "overrides": {
                  "cleanupIDs": false
                }
              }
            }
          ]
        }
      }
    ]
  ]
}
`

**Comment by altechzilla** [comment]
I would check if it's something related to `ubrr-widgets/constantApi`. I've been having similar issues with versions later than  13.3.1 when using the pages directory. Could only ever get it working with the appDir. 

Alternatively, I know this is counter-intuitive, but just for the sake of debugging it you can try the next-transpile-modules deprecated package by @martpie which seems to transpile modules correctly (see the resolveSymlinks option). 

I started an issue here: https://github.com/vercel/next.js/issues/50391

Perhaps you can draw some attention to it.

**Comment by Cherikon** [comment]
Thank you, i will try

**Comment by Cherikon** [comment]
It didn't help :(

**Comment by luckyraul** [comment]
I have the same issue, and found that if I use code transpiled as esm library from node_modules -  it doesn't work. So if I copy component sources to project - works well

**Comment by karam94** [comment]
We are experiencing this same problem at work (so I can't share code), but the above summarises the issue perfectly. A good starting point might be if we are able to narrow down what Next update version or library update version caused the breakage?

**Comment by sanbornhilland** [comment]
We're also experiencing this issue in our project. I agree with @karam94 that the above discussion seems to capture the issue well. I just want to add that 13.3.2 is the first bad release for us. I have not narrowed down the specific bad commit but I will try to do a bisect when I have a chance.

**Comment by petedavisdev** [comment]
We have the same problem with components imported from a component library using the `transpilePackages` option in **next.config.js**, anytime the library component imports hooks from react.
We're stuck on *13.3.1* until this is fixed.

**Comment by smitbarmase** [comment]
Deleting a project. And cloning again worked for me.
