### ISSUE TITLE
Using a `babel.config.js` file gives error when having a middleware containing `NextResponse.redirect()`

### ISSUE THREAD

**Issue by IonelLupu** [vercel/next.js#50492]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/athoteldev/vercel-function-test/tree/middleware-issue

### To Reproduce

1. create a new Next.js project.
2. add a `babel.config.js` file:
```js
const plugins = []

module.exports = {
    presets: ['next/babel'],
    plugins,
}

```
3. add a middleware.ts in the root of the project:
```ts
import { NextRequest, NextResponse } from 'next/server'

export async function middleware(request: NextRequest) {
	if (false) { // just for demo purposes
		return NextResponse.redirect(new URL('/some-page', request.url))
	}
}

```
4. push the changes and the Vercel build and deploy.
5. notice the error message:
```


Error: The Edge Function "middleware" is referencing unsupported modules:
--
16:01:31.675 | - index.js: ./resvg.wasm?module, ./yoga.wasm?module
16:01:33.773 | NOW_SANDBOX_WORKER_EDGE_FUNCTION_UNSUPPORTED_MODULES: The Edge Function "middleware" is referencing unsupported modules:	- index.js: ./resvg.wasm?module, ./yoga.wasm?module


```

![image](https://github.com/vercel/next.js/assets/4083652/0512e4a9-ee6c-4d06-8196-9243e4434798)

### Describe the Bug

I am getting an error when Vercel is trying to build the project.

To notice that removing any of these two files: `babel.config.js` or `middleware.ts`, will make the project build successfully. 

The project also build successfully if I remove the ".redirect()" from the `middleware.ts` file.

But I can't do that with my real project because I have specific configuration.

### Expected Behavior

To not get any errors in Vercel when it's building the project

### Which browser are you using? (if relevant)

-

### How are you deploying your application? (if relevant)

Vercel

**Comment by jamesopti** [comment]
Googling this error got me here as well. Trying to upgrade to Next `13.4.4`

**Comment by jamesopti** [comment]
FWIW This appears to have been introduced in `13.4.4` as `13.4.3` works fine.

**Comment by davecarlson** [comment]
Confirm happening for me also, upgrading from 4.3 to 4.4.

This is all that is in my middleware.
Vercel peeps - related build id is `8XeB7ndqxJDfHdWnHKXVxAuVLKzi`


```import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

const allowedOrigins = [
  "http://mysite.dev:3000",
  "https://www.mysite.com"
];

export function middleware(request: NextRequest) {
  const requestHeaders = new Headers(request.headers);
  const response = NextResponse.next();

  const origin = requestHeaders.get("origin");
  if (origin && allowedOrigins.includes(origin)) {
    response.headers.set("Access-Control-Allow-Origin", origin);
    response.headers.set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    response.headers.set(
      "Access-Control-Allow-Headers",
      "Origin, X-Api-Key, X-Requested-With, Content-Type, Accept, Authorization"
    );
  }

  return response;
}
```

**Comment by TrustyTechSG** [comment]
Also having this deployment error after upgraded to 13.4.4, downgrade to 13.4.3 for now.

```
Error: The Edge Function "src/middleware" is referencing unsupported modules:
--
14:32:31.918 | - index.js: ./resvg.wasm?module, ./yoga.wasm?module
14:32:34.039 | NOW_SANDBOX_WORKER_EDGE_FUNCTION_UNSUPPORTED_MODULES: The Edge Function "src/middleware" is referencing unsupported modules:	- index.js: ./resvg.wasm?module, ./yoga.wasm?module
```

**Comment by andreioprisan** [comment]
Confirming that this is still an issue on net 13.4.4:
`

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
--
14:36:03.114 | ○  (Static)  automatically rendered as static HTML (uses no initial props)
14:36:03.114 |  
14:36:03.736 | Done in 78.51s.
14:36:08.237 | Traced Next.js server files in: 4.441s
14:36:11.047 | Created all serverless functions in: 2.808s
14:36:11.207 | Collected static files (public/, static/, .next/static): 9.941ms
14:36:14.829 | Build Completed in /vercel/output [3m]
14:36:16.137 | Deploying outputs...
14:36:26.867 | Error: The Edge Function "middleware" is referencing unsupported modules:
14:36:26.867 | - index.js: ./resvg.wasm?module, ./yoga.wasm?module
14:36:29.027 | NOW_SANDBOX_WORKER_EDGE_FUNCTION_UNSUPPORTED_MODULES: The Edge Function "middleware" is referencing unsupported modules:	- index.js: ./resvg.wasm?module, ./yoga.wasm?module

`

**Comment by nicholasio** [comment]
this is also happening for me.

**Comment by JakubKontra** [comment]
this is also happening for me with vercel/og

**Comment by codinsonn** [comment]
Hmm, same thing here, anyone have any luck with editing their babel or webpack config?

**Comment by davecarlson** [comment]
Give [v13.4.5-canary.10](https://github.com/vercel/next.js/releases/tag/v13.4.5-canary.10) a try, see if it fixes it

**Comment by seongsoo96** [comment]
> Give [v13.4.5-canary.10](https://github.com/vercel/next.js/releases/tag/v13.4.5-canary.10) a try, see if it fixes it
> 
> [EDIT] - 13.4.5 is now released

I tried at version 13.4.5. But still has error.

**Comment by JannikWempe** [comment]
@huozhi  This error still exists in `13.4.10-canary.3` when using `@vercel/og` in an edge function:

During deployment:
> 16:51:52.539 | Error: The Edge Function "api/og/post" is referencing unsupported modules:
> 16:51:52.539 | - index.js: ./resvg.wasm?module, ./yoga.wasm?module, url

During development:
> [next] - error Error [ReferenceError]: exports is not defined
> [next]     at eval (webpack-internal:///(middleware)/./node_modules/next/dist/compiled/@vercel/og/index.edge.js:3:23)

I am using the [example](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation) for `@vercel/og` – nothing fancy custom.

Downgrading to `13.4.3` resolves the issue.
