### ISSUE TITLE
Issue with POST request handling in Next.js API route next 13.4.4

### ISSUE THREAD

**Issue by georgeziozas** [vercel/next.js#50491]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

i provide all the code on my reproduce steps.

### To Reproduce

To reproduce the Internal Server Error in the Next.js API route when submitting data, please follow these steps:

Set up a Next.js project with Prisma integration.
Create an API route file named route.ts located at src/app/api/projects/route.ts.
Copy the following code into route.ts:
typescript
Copy code

```
import { NextRequest, NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function GET(request: Request) {
  return new Response("yo");
}

export async function POST(request: Request) {
  try {
    const { logo, title, standard, twitter, discord, telegram, userId } =
      await request.json();

    // In a production setting you'd want to validate the incoming data here

    const result = await prisma.project.create({
      data: {
        logo: logo,
        title: title,
        standard: standard,
        twitter: twitter,
        discord: discord,
        telegram: telegram,
        userId: userId,
      },
    });
    return NextResponse.json({ data: result }, { status: 200 });
  } catch (error) {
    NextResponse.json({ error: "Internal Server Error" });
  }
}
```
Start your Next.js development server using npm run dev or yarn dev.
Open a web browser and navigate to http://localhost:3000.
Use a tool such as Postman or cURL to send a POST request to http://localhost:3000/api/projects with the required payload.
Observe the response and check if an Internal Server Error occurs.

Form code:

```
"use client";

import { FC, useState } from "react";
import { useSession } from "next-auth/react";
import { error } from "console";

export default function SubmitForm() {
  const { data: session } = useSession();
  const [formData, setFormData] = useState({
    logo: "",
    title: "",
    standard: "",
    twitter: "",
    discord: "",
    telegram: "",
  });

  const handleInputChange = (e: { target: { name: any; value: any } }) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    try {
      const response = await fetch("/api/projects", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          logo: formData.logo,
          title: formData.title,
          standard: formData.standard,
          twitter: formData.twitter,
          discord: formData.discord,
          telegram: formData.telegram,
          userId: session?.user?.email, // We're assuming you are storing user in your component's state
        }),
      });

      if (response.ok) {
        console.log("form successfully submitted");
        // Handle success - maybe show a notification or redirect the user
      } else {
        console.log("submission failed");
        // Handle error - show a notification or handle error
      }
    } catch (error) {
      return error;
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-gray-100 p-4 sm:p-6 lg:p-8">
      <div className="max-w-md w-full space-y-8">
        <form
          className="mt-8 space-y-6 bg-white rounded-lg shadow-xl p-4 sm:p-6 lg:p-8"
          onSubmit={handleSubmit}
        >
          <h2 className="text-2xl sm:text-3xl font-bold text-center">
            Submit Project
          </h2>

          <div>
            <label className="text-gray-600 mb-2 block" htmlFor="logo">
              Upload Project Logo
            </label>
            <input
              type="file"
              id="logo"
              name="logo"
              accept="text"
              className="w-full py-2 border-gray-300 rounded-md"
              onChange={handleInputChange}
            />
          </div>

          <div>
            <label className="text-gray-600 mb-2 block" htmlFor="title">
              Project Title
            </label>
            <input
              type="text"
              id="title"
              name="title"
              onChange={handleInputChange}
              className="w-full py-2 border-gray-300 rounded-md"
            />
          </div>

          <div className="space-y-2">
            <span className="text-gray-600 mb-2 block">
              Choose a token standard
            </span>
            <label className="inline-flex items-center">
              <input
                type="radio"
                className="form-radio"
                name="standard"
                value="BRC-20"
                onChange={handleInputChange}
              />
              <span className="ml-2">BRC-20</span>
            </label>
            <label className="inline-flex items-center">
              <input
                type="radio"
                className="form-radio"
                name="standard"
                value="SRC-20"
                onChange={handleInputChange}
              />
              <span className="ml-2">SRC-20</span>
            </label>
            <label className="inline-flex items-center">
              <input
                type="radio"
                className="form-radio"
                name="standard"
                value="ORC-20"
                onChange={handleInputChange}
              />
              <span className="ml-2">ORC-20</span>
            </label>
          </div>

          <div>
            <label className="text-gray-600 mb-2 block" htmlFor="twitter">
              Twitter Link
            </label>
            <input
              type="url"
              id="twitter"
              name="twitter"
              onChange={handleInputChange}
              className="w-full py-2 border-gray-300 rounded-md"
            />
          </div>

          <div>
            <label className="text-gray-600 mb-2 block" htmlFor="discord">
              Discord Link
            </label>
            <input
              type="url"
              id="discord"
              name="discord"
              onChange={handleInputChange}
              className="w-full py-2 border-gray-300 rounded-md"
            />
          </div>

          <div>
            <label className="text-gray-600 mb-2 block" htmlFor="telegram">
              Telegram Link
            </label>
            <input
              type="url"
              id="telegram"
              name="telegram"
              onChange={handleInputChange}
              className="w-full py-2 border-gray-300 rounded-md"
            />
          </div>

          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full"
            type="submit"
          >
            Submit Project
          </button>
        </form>
      </div>
    </div>
  );
}
```

### Describe the Bug

The bug is an Internal Server Error that occurs when submitting the form in the provided Next.js application. The error is encountered when making a POST request to the /api/projects endpoint. Despite following the recommended code structure and implementing the required functionality, the server responds with a 500 Internal Server Error. The issue seems to be related to the handling of the POST request and the interaction with the Prisma database client.

The prisma properly configured and set. I believe the problem consists from the next package updates...

### Expected Behavior

I expected the form submission to be successful, resulting in a POST request to the /api/projects endpoint. The server should handle the request correctly and save the form data to the Prisma database using the Prisma client. I anticipated receiving a response with a 200 status code and the newly created project data in the response body.

### Which browser are you using? (if relevant)

chrome 113.0.5672.127

### How are you deploying your application? (if relevant)

im on dev mode atm.

**Comment by georgeziozas** [comment]
FYI,
I tried the canary and still the same exact problem.

**Comment by icyJoseph** [comment]
Hi,

In:

```js
 catch (error) {
    NextResponse.json({ error: "Internal Server Error" });
  }
```

Could you please log the error? Those usually contain quite a lot of information, and it'll help us narrow down the issue.

**Comment by georgeziozas** [comment]
> Hi,
> 
> In:
> 
> ```js
>  catch (error) {
>     NextResponse.json({ error: "Internal Server Error" });
>   }
> ```
> 
> Could you please log the error? Those usually contain quite a lot of information, and it'll help us narrow down the issue.



As requested i fixed my error handling: 

**Form**

```
...
const result = await response.json();
      console.log("response on form:" + result);
      if (response.ok) {
        console.log("Form successfully submitted");
        // Handle success - maybe show a notification or redirect the user
      } else {
        console.log("Form submission failed");
        // Handle error - show a notification or handle error
      }
    } catch (error) {
      return "SubmitForm:" + error;
    }
  };
```

**Route.ts**
```
...
  console.log("prisma create result:" + result);
    return NextResponse.json({ data: result }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error: error }, { status: 500 });
  }
}
```
**Errors Results:**
![image](https://github.com/vercel/next.js/assets/12986112/f5c21cac-2c98-4f43-92e5-582947564532)
![image](https://github.com/vercel/next.js/assets/12986112/fd7d9597-3918-4a38-a237-19dad953ab79)
![image](https://github.com/vercel/next.js/assets/12986112/16f37dbd-cbb8-425d-87e9-49011b534638)
![image](https://github.com/vercel/next.js/assets/12986112/4bfb10cb-56ac-432e-87ff-93757d73fc33)

Thanks in advance.

**Comment by icyJoseph** [comment]
I see, but that's not really, what I wanted to see. The Error object is not serializable like that, so it usually ends up `"{}"` - 

I want to see what `console.log(error)` is outputing in your console. Do this:

```js
 } catch (error) {
    console.log(error) // ---> I want to see what this prints server side, in your terminal
    const message = error instanceof Error ? error.message : "Unexpected Error";
    return NextResponse.json({ message }, { status: 500 });
  }
```

Notice the `console.log(error)` - I want to see that one. It could be various thing, so we need to narrow it down by looking at it.

**Comment by georgeziozas** [comment]
> ```js
> message 
> ```

Yes you are totally correct, my bad. 

Here is updated: 

**route**

```
console.log("prisma create result:" + result);
    return NextResponse.json({ data: result }, { status: 200 });
  } catch (error) {
    console.log(error);
    const message = error instanceof Error ? error.message : "Unexpected Error";
    return NextResponse.json({ message }, { status: 500 });
  }
}
```

**Error:**

![image](https://github.com/vercel/next.js/assets/12986112/eba6c15a-bd53-4284-9e11-4d9727caed98)

**Comment by georgeziozas** [comment]
It seems the error be occurring at line 14 in the route.ts file of my API handler.

I believe its a problem regarding the parsing of the json? 

The thing is that i dont see any problems on it to be frank.

**Comment by icyJoseph** [comment]
Yeah I think the issue is that you have Node 16. Try upgrading to Node 18 😄 Node 18 introduced the Fetch API, and friends, whereas, Node 16 doesn't have it, so Next.js uses a poly-fill, which I think is breaking some invariant (assumption) when parsing the body.

**Comment by georgeziozas** [comment]
> Yeah I think the issue is that you have Node 16. Try upgrading to Node 18 😄 Node 18 introduced the Fetch API, and friends, whereas, Node 16 doesn't have it, so Next.js uses a poly-fill, which I think is breaking some invariant (assumption) when parsing the body.

hey mate, i followed your reccomendation. I updated to Node 20 instead of 18. 
![image](https://github.com/vercel/next.js/assets/12986112/51448ff5-2fb2-4202-817b-dddc614ba64d)

Tried it again, still same exact error? :(

**Comment by icyJoseph** [comment]
Mmm could you try to just echo? I'll setup a project soon.

I mean:

```ts
export async function POST(request: Request) {
  try {
    const { logo, title, standard, twitter, discord, telegram, userId } =
      await request.json();

    // In a production setting you'd want to validate the incoming data here

    const result = {
      logo: logo,
      title: title,
      standard: standard,
      twitter: twitter,
      discord: discord,
      telegram: telegram,
      userId: userId,
    };

    return NextResponse.json({ data: result }, { status: 200 });
  } catch (error) {
    NextResponse.json({ error: "Internal Server Error" });
  }
}
```

Let's discard Prisma for now, and just make sure we can echo back.

**Comment by icyJoseph** [comment]
Alright, I set this up:

```ts
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  return new Response("yo");
}

export async function POST(request: Request) {
  try {
    const { logo, title, standard, twitter, discord, telegram, userId } =
      await request.json();

    // In a production setting you'd want to validate the incoming data here

    const result = {
      logo: logo,
      title: title,
      standard: standard,
      twitter: twitter,
      discord: discord,
      telegram: telegram,
      userId: userId,
    };

    return NextResponse.json({ data: result }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error: "Internal Server Error" });
  }
}
```

And sent this request from an HTTP client:

```http
POST http://localhost:3000/api/echo
Content-Type: application/json

{
    "logo": "logo",
    "title": "title",
    "standard": "standard",
    "twitter": "twitter",
    "discord": "discord",
    "telegram": "telegram",
    "userId": "userId"
}
```

And it works flawlessly.  Tested with Node 20 and Node 18.

**Comment by georgeziozas** [comment]
can you tell me which versions of packages you used? next etc 
I will make a new project from scratch and try again

**Comment by georgeziozas** [comment]
> Alright, I set this up:
> 
> ```ts
> import { NextResponse } from "next/server";
> 
> export async function GET(request: Request) {
>   return new Response("yo");
> }
> 
> export async function POST(request: Request) {
>   try {
>     const { logo, title, standard, twitter, discord, telegram, userId } =
>       await request.json();
> 
>     const result = {
>       logo: logo,
>       title: title,
>       standard: standard,
>       twitter: twitter,
>       discord: discord,
>       telegram: telegram,
>       userId: userId,
>     };
> 
>     return NextResponse.json({ data: result }, { status: 200 });
>   } catch (error) {
>     return NextResponse.json({ error: "Internal Server Error" });
>   }
> }
> ```
> 
> And sent this request from an HTTP client:
> 
> ```httpspec
> POST http://localhost:3000/api/echo
> Content-Type: application/json
> 
> {
>     "logo": "logo",
>     "title": "title",
>     "standard": "standard",
>     "twitter": "twitter",
>     "discord": "discord",
>     "telegram": "telegram",
>     "userId": "userId"
> }
> ```
> 
> And it works flawlessly. Tested with Node 20 and Node 18.

Thats absurb.... I made a brand new project, copied the files. Same problems. I dont get it really. 

Here is my file structure.. 
![image](https://github.com/vercel/next.js/assets/12986112/0a072bf2-771d-4eec-a101-303f49ddab67)

**Comment by balazsorban44** [comment]
@georgeziozas Could you add a link to a _minimal_ (remove dependencies/code that does not contribute) reproduction instead of screenshots/code snippets? :pray: It could make the investigation a bit faster.

> so Next.js uses a poly-fill

Node.js 16 should be fine to use, as we are using `undici` for polyfilling, the same lib that Node.js 18+ uses internally.

**Comment by georgeziozas** [comment]
> @georgeziozas Could you add a link to a _minimal_ (remove dependencies/code that does not contribute) reproduction instead of screenshots/code snippets? 🙏 It could make the investigation a bit faster.
> 
> > so Next.js uses a poly-fill
> 
> Node.js 16 should be fine to use, as we are using `undici` for polyfilling, the same lib that Node.js 18+ uses internally.

I uploaded the project here. 
https://github.com/georgeziozas/btc-socials/tree/main/btc-socials

**Comment by icyJoseph** [comment]
Is the problem here?

```js
   const { logo, title, standard, twitter, discord, telegram, userId } =
      await request.json();
    console.log("Request Body:", await request.json());

```

I don't think you can consume the request twice.

**Comment by georgeziozas** [comment]
I cant believe this was the problem...

Respect brother. SOLVED.

**Comment by DonikaV** [comment]
How i can redirect user to error.js / global-error.js if i return 500 status from route.ts? I am throwing error in my component but nothing. 
I have

route.ts
```
ContextProvider
     Component
```
     in Component i am doing **ContextProvider.function** which doing fetch to route.ts, in route.ts i return status 500
     return NextResponse.json(data, {
      status: 500,
    });
    
    And nothing happens, the app stay on the same route and i just see log in dev tools.
