### ISSUE TITLE
Setting dynamicParams to false also does not return a 404 page for entry points not returned by generateStaticParams.

### ISSUE THREAD

**Issue by pressogh** [vercel/next.js#50504]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.23.0-20220130.1630
      pnpm: 7.8.0
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/red-violet-0d26j5

### To Reproduce

Access to the /test entry point
Access to the /a entry point

### Describe the Bug

Leaving dynamicParams=false and accessing an entry point that does not exist in generateStaticParams does not return a 404 page.

/test : The parameters for test are returned by generateStaticParams, so you can access them normally.
/a : generateStaticParams doesn't return any parameters for a, so leaving dynamicParams=false should return a 404 page.

However, when i actually access /a, it doesn't return a 404 page, but instead receives the params from Page, just as it would if i left dynamicParams=true

### Expected Behavior

/test : The parameters for test are returned by generateStaticParams, so you can access them normally.
/a : generateStaticParams doesn't return any parameters for a, so leaving dynamicParams=false should return a 404 page.

**Comment by HamAndRock** [comment]
You are missing export in front of generateStaticParams.

**Comment by pressogh** [comment]
> You are missing `export` in front of generateStaticParams.

My Bad. I'll close the issue
