### ISSUE TITLE
Cached page rendered on UI

### ISSUE THREAD

**Issue by Adityak4201** [vercel/next.js#50505]
### Provide environment information

```bash
next 13.3.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

NA

### To Reproduce

I have a multi page application. I recently added a new page and routed it from a next js page. Let's say pages are page1 and page2. page1 is the initial page. When I routed from page1 to page2, page2 rendered correctly, however on redirecting back from page2 to page1, below data is returned everytime.

### Describe the Bug

0:[[["",{"children":["core",{"children":["home",{"children":["__PAGE__",{}]}]}]},"$undefined","$undefined",true],"$L1","$L2"]]
3:I{"id":"41371","name":"","chunks":["8350:d24c7ea9-765a6432e38c0542","7916:7916-fe7590151e5d94b4","209:209-8263a4e0f55d689f","9110:9110-3c363f495353651e","3178:3178-9e1b1c620e9cd79f","2311:2311-ed299d02c3ab48d3","3185:app/layout-6b0effcd902f9021"],"async":false}
4:I{"id":"8230","name":"","chunks":["8350:d24c7ea9-765a6432e38c0542","7916:7916-fe7590151e5d94b4","209:209-8263a4e0f55d689f","9110:9110-3c363f495353651e","3178:3178-9e1b1c620e9cd79f","2311:2311-ed299d02c3ab48d3","3185:app/layout-6b0effcd902f9021"],"async":false}
5:I{"id":"51300","name":"","chunks":["2272:webpack-4cfbaca87a09b172","2667:2443530c-a04c5514d6966e5c","4961:4961-f39ace97c5812a59"],"async":false}
6:I{"id":"16022","name":"","chunks":["2272:webpack-4cfbaca87a09b172","2667:2443530c-a04c5514d6966e5c","4961:4961-f39ace97c5812a59"],"async":false}
7:I{"id":"46773","name":"","chunks":["8350:d24c7ea9-765a6432e38c0542","7916:7916-fe7590151e5d94b4","6394:6394-f26cb6822e3ab1b5","5846:5846-c44219c5c77f7962","1505:app/core/profile/page-0213c8d14910f615"],"async":false}
8:I{"id":"99031","name":"","chunks":["8350:d24c7ea9-765a6432e38c0542","7916:7916-fe7590151e5d94b4","1411:1411-35333ab0676ac119","6394:6394-f26cb6822e3ab1b5","5846:5846-c44219c5c77f7962","209:209-8263a4e0f55d689f","2192:2192-ce71917bc54d041d","4326:4326-da00c963f838ed9c","706:706-7d98ef73d17bf3d9","8089:8089-5c71b2a25210e9d7","9110:9110-3c363f495353651e","353:353-72d215e93124704b","8862:8862-11ac4e29db01ad71","7901:7901-2c1e809d5dfefeb0","9987:9987-7437f636735b0026","2311:2311-ed299d02c3ab48d3","2860:app/core/home/page-94df22aa4b5faf88"],"async":false}
2:[[["$","meta",null,{"charSet":"utf-8"}],["$","title",null,{"children":"POS Homepage"}],["$","meta",null,9:[null,null,[["$","link","0",{"rel":"stylesheet","href":"/_next/static/css/20f18295d6fb7de4.css","precedence":"next.js"}],["$","link","1",{"rel":"stylesheet","href":"/_next/static/css/0b81f70dccaa65a1.css","precedence":"next.js"}],["$","link","2",{"rel":"stylesheet","href":"/_next/static/css/a0637e0d0acd9061.css","precedence":"next.js"}]]]
a:[null,null,[["$","link","0",{"rel":"stylesheet","href":"/_next/static/css/c85e3756eb74cc21.css","precedence":"next.js"}]]]

### Expected Behavior

Render proper HTML on UI.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next start, Akamai cache

**Comment by HamAndRock** [comment]
Might be related to CDNs:

https://github.com/vercel/next.js/pull/49140#issuecomment-1549405009

**Comment by balazsorban44** [comment]
@HamAndRock is correct. You can follow the mentioned PR for updates.
