### ISSUE TITLE
no way to permanent redirect with 308 status code from server component with redirect() function

### ISSUE THREAD

**Issue by MahmoudBakr22** [vercel/next.js#50526]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/MahmoudBakr22/next_permanent_redirect_bug

### To Reproduce

open the network tab and click reload you will always notice the the status code is 307 
 
![Screenshot_112](https://github.com/vercel/next.js/assets/111358769/5a7d54a9-76ba-4209-93e9-1343faa2a477)

### Describe the Bug

redirect function from next/navigation always temporary redirect with status code 307 with no option to permanent redirect with 308 status code 

### Expected Behavior

expect redirect function from next/navigation to accept another parameter that specify if redirect is permanent or temporary
the same as redirection in pages directory 

`
  return {
          redirect: {
            destination: "/redirect",
            permanent :true
          },
`  
and I understand  that you can not change the status code after streaming starts as mentioned in this comment
https://github.com/vercel/next.js/issues/49148#issuecomment-1542260937

but I am talking about redirection that happens before streaming starts
and after some digging I fond out that Next Js  always set the statusCode for the redirection that happens before streaming to 307 as fixed 
as shown below
![Screenshot_111](https://github.com/vercel/next.js/assets/111358769/9e3b1388-b9c7-4180-9cd1-767a1be3bdb0)

so we only need a way to choose if we want the statusCode to be 307 or 308

**Comment by balazsorban44** [comment]
You might get more help specific to your projectin [Discussions](https://github.com/vercel/next.js/discussions) or in our [Discord](http://nextjs.org/discord).

**Comment by poorscousertommy8** [comment]
I have the same problem. The redirects are maintained in a CMS. In Page.js I fetch data, based on this data I know whether I have to forward the current URL or not. In principle, this would also be possible in the middleware, but the fetches are apparently not cached in the middleware, which is why this is not an option (all fetches would then be executed several times).

How can I solve the problem?

**Comment by overtune** [comment]
We also have this problem. All page data comes from a CMS, where all redirects are handled.
When we have loaded the data for a page we know if we need to redirect and if it needs to be permanent or not.

If we use the `redirect` function we can create the redirect and it works (but as said it always sets 307 as the status code).
If it can set 307 as the status code, it must be possible to set 308...

This is currently a show stopper for us to go live on App router.

(In middleware I don't think you can read and act on a requests response data right? I have not found anything about that in the documentation any way).

Thanks for all the work!

**Comment by jagadishg** [comment]
I was facing the same issue. I have worked around this issue with route handlers and returning native response object

```js
return new Response(undefined, {
    status: pageRedirect.permanent ? 308 : 307,
    headers: { location: pageRedirect.destination },
})
```

**Comment by JurajKavka** [comment]
Why is this issue closed? This is huge and we can't continue to develop our CMS application with app router. We need to switch back to `pages` router!

**Comment by JurajKavka** [comment]
I think this issue should not be closed. It is showstopper for us and nowhere is properly explained how to solve that.

**Comment by david-keefe** [comment]
To serve a 301 redirect,I have to move my data-fetching logic to the middleware? That is a poor solution that defeats the purpose of React server components.
