### ISSUE TITLE
Docs: appDir not-found file clarification

### ISSUE THREAD

**Issue by astateful** [vercel/next.js#50521]
### What is the improvement or update you wish to see?

I would like to see the documentation for the not-found.js contain information such as whether this file can export a server or client component. Basically, the documentation here should be similar to what is documented for the error page in the app dir.

### Is there any context that might help us understand?

The error page documentation at https://nextjs.org/docs/app/api-reference/file-conventions/error is far more descriptive.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/not-found

<sub>[DX-1650](https://linear.app/vercel/issue/DX-1650/docs-appdir-not-found-file-clarification)</sub>

**Comment by leerob** [comment]
This page now mentions that it's a server component by default and has an example of data fetching.
