### ISSUE TITLE
`previewData` function not exported anymore

### ISSUE THREAD

**Issue by Tobi-mmt** [vercel/next.js#50523]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 7.26.3
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/busy-framework-jdlbqz?file=%2Fapp%2Fpage.tsx%3A1%2C1

### To Reproduce

1. Use the current nextjs version 13.4.4 or canary version
2. use the appDir 
3. create a `page.tsx` and place the following line to the import `import { previewData } from 'next/headers'`
4. see build or dev server failing

### Describe the Bug

Upgrading from 13.3.0 to 13.4.4 is not possible when I use the `previewData` function of the headers component since this function is not exported anymore.
As long as I use the previewData instead of the `draftMode` I need this function to get the preview informations inside the `appDir`.

In the following commit the `previewData` was removed from the header component. In my opinion this is a breaking change and should not be inside a bug fix release.
https://github.com/vercel/next.js/commit/58e5c780f33d22bc8300b1d5d8ed4065c62645e2#diff-d24b60b60f9aa56d44645e3521f3ebf3063ae5dc44616629a4eccb9d082b3d6c

### Expected Behavior

Upgrading from 13.3.0 to 13.4.4 did not remove the `previewData` function from the `headers` component.

**Comment by balazsorban44** [comment]
Hi, thanks for opening the issue! The reason `previewData` was removed between the mentioned versions is because before `13.4.0` the App Router was considered experimental, meaning the APIs could still have changed.

Going forward, we recommend using `draftMode` as [documented](https://nextjs.org/docs/app/building-your-application/configuring/draft-mode).
