### ISSUE TITLE
[NEXT-1253] Can't dynamically import components that have CSS Modules

### ISSUE THREAD

**Issue by maxsteenbergen** [vercel/next.js#50527]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.5-canary.0
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Dynamic imports (next/dynamic), Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/maxsteenbergen/dynamic-css-module-repro

### To Reproduce

- Clone the repo
- Run the Turborepo monorepo from the root → `turbo run dev`
- Navigate to `/components/controls/button`
- Error trigger

### Describe the Bug

I'm trying to dynamically load a component based on the route. In essence, the route app/components/controls/button in workspace docs) loads the component located at components/controls/button in the UI workspace.

This works beautifully. The component is resolved and rendered just fine until you try to style it with CSS Modules. When you do, NextJS throws the following error: `Cannot read properties of null (reading 'parentNode')`

Note that importing the same component statically does not trigger the error. Also, you don't actually need to apply the module: just logging the styles import triggers the bug.

I did some more debugging in my spare time, and tracked the issue down to line 26-27 of `/node_modules/next/dist/build/webpack/config/blocks/css/loaders/client.js` which reads

```
var anchorElement = document.querySelector("#__next_css__DO_NOT_USE__");
var parentNode = anchorElement.parentNode// Normally <head>
```

As this code only runs in dev environments, I went ahead and checked a build and indeed, the error doesn't occur. As a dirty hack, I added id="__next_css__DO_NOT_USE__" to my main <html> tag, and the error did go away in one environment but not the other.
It's interesting to note that the same error occurs when trying to use a statically imported component in an .mdx file.

This error does _NOT_ occur with the `--turbo` flag, but that triggers a entirely different bug.

> EDIT: Upon closer debugging, it seems related to the combination of using [slug] urls and dynamic imports?

### Expected Behavior

- Dynamically importing a component styled with CSS Modules renders equally to a statically imported one.
- Importing components that have CSS modules in a .mdx file renders appropriately.

### Which browser are you using? (if relevant)

all

### How are you deploying your application? (if relevant)

next start

<sub>[NEXT-1253](https://linear.app/vercel/issue/NEXT-1253/cant-dynamically-import-components-that-have-css-modules)</sub>

**Comment by maxsteenbergen** [comment]
@BaffinLee  Thanks! Tried that suggestion but didn't work; probably because I'm not using `/pages` at all here.
I did find that it's got something to do with [slugs]. The same component imported dynamically works when hardcoding some paths, but not when building the import URI dependent on the slug params

**Comment by maxsteenbergen** [comment]
Though that does open up a new can o' worms: with that fix, components with internal useState hooks embedded in mdx files bug out because of it, something about invalid hook calls and `TypeError: Cannot read properties of null (reading 'useState')`

**Comment by ealexhaywood** [comment]
This is very similar to what I'm doing in https://github.com/vercel/next.js/issues/51324 where I'm trying to dynamically load a component based on the route.

Client components fail, but server components (without any client component children) work.

**Comment by padmaia** [comment]
I tested this out with the latest version and this seems to work now.
