### ISSUE TITLE
Modifying root layout causes "Expected server HTML to contain a matching" error

### ISSUE THREAD

**Issue by vmaark** [vercel/next.js#50533]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.1
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vmaark/layout-mismatch

### To Reproduce

1. `git@github.com:vmaark/layout-mismatch.git`
2. `cd layout-mismatch`
3. `yarn install`
4. `yarn dev`
open `localhost:3000` - see the error.

### Describe the Bug

If there are any jsx elements added to the `RootLayout` inside the `html` node, it causes an `Expected server HTML to contain a matching` error. If this is the intended behaviour, I haven't found it in the documentation. The linked reproduction adds a `<div />` to the application generated by `npx create-next-app`.

Most likely this is a duplicate issue of https://github.com/vercel/next.js/issues/41864

### Expected Behavior

No error, or clearer documentation on how to edit the `RootLayout`.

**Comment by balazsorban44** [comment]
`div` is an invalid child of `html`, which also should also produce this warning:

![image](https://github.com/vercel/next.js/assets/18369201/6e766ca7-1b20-4560-8ae7-f6f49677c4d8)

You likely wanted to place the `div` inside `body`, solving your mismatching HTML issue.

#41864 did not have a reproduction, so it's impossible to tell if these are related.

**Comment by vmaark** [comment]
> `div` is an invalid child of `html`, which also should also produce this warning:
> 
> ![image](https://user-images.githubusercontent.com/18369201/241972427-6e766ca7-1b20-4560-8ae7-f6f49677c4d8.png)
> 
> You likely wanted to place the `div` inside `body`, solving your mismatching HTML issue.
> 
> #41864 did not have a reproduction, so it's impossible to tell if these are related.

okay, then `header`.

**Comment by vmaark** [comment]
@balazsorban44 should I open a new ticket for this?
