### ISSUE TITLE
SWC unable to find node_modules path when using openapi-codegen tool

### ISSUE THREAD

**Issue by owonwo** [vercel/next.js#50547]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 9.1.2
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/owonwo/-openapi-swc-bug-example

### To Reproduce

Remove the `experimental` property and value from the `.swcrc` and then run `npm run generate:api`. It should work as expected.

It doesn't work with the `@swc/plugin-styled-components` plug present

### Describe the Bug

![image](https://github.com/vercel/next.js/assets/29642861/8db67b1a-f9c6-403e-9166-790c67f9307c)

### Expected Behavior

![image](https://github.com/vercel/next.js/assets/29642861/84889a8d-78cb-464b-a9dd-69772eaafd01)

It should generate a couple files in the `<rootDir>/core/api` folder

**Comment by kdy1** [comment]
`.swcrc` should have no effect

**Comment by kdy1** [comment]
It works.
https://github.com/kdy1/next-50547


You have to install `@swc/plugin-styled-components`

**Comment by owonwo** [comment]
Thanks @kdy1
