### ISSUE TITLE
Error: webp format is not supported in Image Component when using Turpopack. 

### ISSUE THREAD

**Issue by MAhmedSid** [vercel/next.js#50540]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/MAhmedSid/Turbo-Check

### To Reproduce

1. Run this command in terminal "pnpm i"
2. Then after installing all packages just run "pnpm run dev" 

### Describe the Bug

The bug is when I am running development server with --turbo . Its not supporting **webp** format in "Image component" provided by next js  and not even in HTML **img** tag.

### Expected Behavior

I was added two images in page.tsx with only one difference which format of those two. The png format file is working but webp is not working. I hope my information would help to make Next JS (The best framework). Because I am enthusiast of Next js. 

### Which browser are you using? (if relevant)

Microsoft Edge Version 113.0.1774.57 (Official build) (64-bit)

### How are you deploying your application? (if relevant)

pnpm run dev

<sub>[WEB-1157](https://linear.app/vercel/issue/WEB-1157/error-webp-format-is-not-supported-in-image-component-when-using)</sub>

**Comment by padmaia** [comment]
This appears to be working in v13.5+
