### ISSUE TITLE
[BUG] Static Rendering build times increase 300+% in 13.2.5-canary.26

### ISSUE THREAD

**Issue by ElGrecode** [vercel/next.js#50555]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), SWC transpilation, Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/compare/v13.2.5-canary.25...v13.2.5-canary.26

### To Reproduce

The test to reproduce is to create ~400 statically generated pages with resources pulled dynamically from a CMS api to generate the `slug` parameter props. To isolate the problem for this test I am only:
- statically generating one specific app directory page (`CompanyPage`)
- fetching the resource, but
- not rendering anything more than a single `<div>`

```
export default async function CompanyPage(context: PageContext) {
    const {
        params: { slug },
    } = context
    const company = await getCompany(slug)

    return <div>STATIC</div>
}
```

My next config has also been stripped to its most basic form:
```
const nextConfig = {
    experimental: {
        appDir: true,
    },
}
```

`npm run build`

### Describe the Bug

`13.2.5-canary.25` 400 pages build times: 35-40 seconds,  (5 times reproduced)
`13.2.5-canary.26` 400 pages build times: 140-160 seconds, (5 times reproduced)

The increase in build time is 3-4x. For our production workloads, this makes production builds and deploys untenable when leading into hours of time at thousands of statically generated pages.

Please note: in the latest canary, `13.4.5-canary.2` the build times have decreased slightly, but still hovering around 2x-3x the build time of `13.2.5-canary.25`

Possibly Related: https://github.com/vercel/next.js/issues/46884

### Expected Behavior

The bug expectation is to maintain consistent build times with no configuration changes.

### Which browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

Vercel

**Comment by sannajammeh** [comment]
SWC fixes just got merged so should improve in the next canary

**Comment by wadehammes** [comment]
I have been trying to figure this one out for awhile! I am still on 13.2.4 because everything after that adds roughly 5 min to my build time. Glad fixes are coming!

**Comment by ElGrecode** [comment]
Unfortunately the updates in [v13.4.5-canary.3](https://github.com/vercel/next.js/releases/tag/v13.4.5-canary.3) have not noticeably changed the build times. They still hover around the same times

**Comment by ijjk** [comment]
Hi, this has been updated in `v13.4.6-canary.3` of Next.js, please update and give it a try!
