### ISSUE TITLE
not-found.js doesn't read metadata

### ISSUE THREAD

**Issue by lewisking** [vercel/next.js#50566]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Mon May  8 23:12:01 PDT 2023; root:xnu-8796.140.12.505.1~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.13.0
      npm: 8.1.0
      Yarn: 1.22.11
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/lewisking/next-js-not-found-issue

### To Reproduce

Visit localhost:3000/example-404, note that the browser title isn't set.

### Describe the Bug

The browser title isn't set, which makes me believe the metadata export is ignored on not-found.js

### Expected Behavior

I would expect the metadata export to be respected.

**Comment by JesseKoldewijn** [comment]
I don't know for sure why it both doesn't read the metadata and just keeps refreshing every 4 seconds (in dev) but my workaround for the title not changing bit on the not-found page is by just returning something like this:

```
<html>
    <head>
        <title>404 - acme</title>
    </head>
    <body>
    <main>404 | not found</main>
    </body>
</html>

```

**Comment by MRezaSafari** [comment]
using @JesseKoldewijn solution can mess up the layout. ( if you have a RootLayout )

and then if you just have a head with a title in it. you will receive this error after routing

<img width="957" alt="image" src="https://github.com/vercel/next.js/assets/1060150/dab3a055-7cc7-4921-ae5d-0cc5117d664a">

**Comment by JesseKoldewijn** [comment]
I can the before mentioned work-around both just now on the latest canary and have been using this for a couple of months already as well. I'll create a reproduction for ya 👍

**Comment by JesseKoldewijn** [comment]
I've created a fork with the work-around for ya and thrown in in a PR on your reproduction repo so you can easily see the differences. 👍

**Comment by lewisking** [comment]
Thanks @JesseKoldewijn, but I get errors in console when I set the HTML element within the not-found file. I'm also of the mindset I should be setting that only once in this project to be 
<img width="441" alt="Screenshot 2023-06-01 at 09 28 16" src="https://github.com/vercel/next.js/assets/519069/7def473d-eea4-4d31-a2a0-f30442d7ad8f">
honest.

**Comment by JesseKoldewijn** [comment]
> Thanks @JesseKoldewijn, but I get errors in console when I set the HTML element within the not-found file. I'm also of the mindset I should be setting that only once in this project to be honest! <img alt="Screenshot 2023-06-01 at 09 28 16" width="441" src="https://user-images.githubusercontent.com/519069/242460473-7def473d-eea4-4d31-a2a0-f30442d7ad8f.png">

The html and head element need to match the elements in your layout tho.
See example of how I've been working around this matter in this repo: https://github.com/JesseKoldewijn/next-js-not-found-issue

**Comment by lewisking** [comment]
> > Thanks @JesseKoldewijn, but I get errors in console when I set the HTML element within the not-found file. I'm also of the mindset I should be setting that only once in this project to be honest! <img alt="Screenshot 2023-06-01 at 09 28 16" width="441" src="https://user-images.githubusercontent.com/519069/242460473-7def473d-eea4-4d31-a2a0-f30442d7ad8f.png">
> 
> The html and head element need to match the elements in your layout tho. See example of how I've been working around this matter in this repo: https://github.com/JesseKoldewijn/next-js-not-found-issue

Gotcha. Still, would expect it to take from the metadata export and not need this workaround, so I'll leave this open

**Comment by JesseKoldewijn** [comment]
Yeah man I agree it is supposed to work as expected. Just wanted to share my work-around as more of a short-term fix :wink:

**Comment by shuding** [comment]
Related discussions in #45620.

**Comment by huozhi** [comment]
Close this as duplicate, let's track in #45620
