### ISSUE TITLE
Error: A Node.js API is used (process.cwd) which is not supported in the Edge Runtime.

### ISSUE THREAD

**Issue by xkungfu** [vercel/next.js#50565]
Apologies for commenting here, but @marek-hanzal's issue is also my issue and I was able to solve it.

When building the below Error occurred:
`Error: A Node.js API is used (process.cwd) which is not supported in the Edge Runtime.
`

and I find the solution, it is very closed to my problem.

-----------------------------------------------
`The "edge runtime" is a **third** webpack config that Next is using. This means that to add an extra entry to your webpack config, you need to use the `nextRuntime` hidden option (it should [be documented here](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) but isn't yet). The following seems to work for me:`

```js
  webpack: (config, { nextRuntime }) => {
    // Undocumented property of next 12.
    if (nextRuntime !== "nodejs") return config;
    return {
      ...config,
      entry() {
        return config.entry().then((entry) => ({
          ...entry,
          cli: path.resolve(process.cwd(), "lib/cli.ts"),
        }));
      },
    };
  },
```
_Originally posted by @CGamesPlay in https://github.com/vercel/next.js/issues/36237#issuecomment-1117694528_

--------------------------------------------------
            
but when I try to build again, I found the "lib/cli.ts " is a wrong path.

where to find file cli.ts and copy to lib/cli.ts?
or what is the right path of cli.ts?

I have tried copy cli.ts file from the bin path of next.js source  to "lib/cli.ts".  but many denpendicies lost :

```
- info Loaded env from /home/datad/chat/gpt2/.env
[Next] apiUrl:  undefined
Failed to compile.

./lib/cli.ts
Module not found: Can't resolve 'inquirer'
./lib/cli.ts
Module not found: Can't resolve 'meow'
./lib/cli.ts
Module not found: Can't resolve 'is-git-clean'
./lib/cli.ts
Module not found: Can't resolve '../lib/uninstall-package'
./lib/cli.ts
Module not found: Can't resolve '.bin/jscodeshift'

> Build failed because of webpack errors



```

please help me .

thanks@

**Comment by balazsorban44** [comment]
I'm closing this, as this is not following our bug template. Please open an issue with a mininal reproduction. 

_Note that modifying the webpack config is not covered by sever._
