### ISSUE TITLE
NextResponse doesn't work inside callback function !

### ISSUE THREAD

**Issue by zwelhtetyan** [vercel/next.js#50572]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
--
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

--

### To Reproduce

--

### **Although the process of uploading image to space is done, response doesn't send to client**

```ts
// app/api/upload/route.ts

export async function POST(request: Request) {
  const formData = await request.formData();
  const file = formData.get("file");

  const validFile = file instanceof File;

  if (!validFile) return NextResponse.json({ message: "not a valid file!" });

  const buffer = await file.arrayBuffer();

  S3client.upload({
    Bucket: "my_bucket_name",
    ACL: "public-read",
    Key: `test/zwel/${uuidv4()}${file.name}`,
    Body: Buffer.from(buffer),
  }).send((err, data) => {
    if (err) return NextResponse.json({ message: "uploading fail!" });

    const url = data.Location;

    console.log("url: ", url);
    return NextResponse.json({ url });
  });
}

```

```tsx
// imageUpload.ts

  const handleImageUpload = async (file: File) => {
    const formData = new FormData();
    formData.append("file", file);

    try {
      const res = await fetch(`${envConfig.BASE_URL}/api/upload`, {
        method: "POST",
        body: formData,
      });

      const data = await res.json();

      console.log(data.url);
    } catch (err) {
      console.log(err);
    }
  };

```

`SyntaxError: Unexpected end of JSON input
    at handleImageUpload (webpack-internal:///(app-client)/./components/admin/ImageUpload.tsx:42:36)`

<img width="709" alt="Screenshot 2023-05-31 at 2 24 49 PM" src="https://github.com/vercel/next.js/assets/89287841/bc0ccbd2-53c9-48e7-9ef5-cf9aef7b882a">

### Expected Behavior

`{url: "example.png"}`

### Which browser are you using? (if relevant)

--

### How are you deploying your application? (if relevant)

no deployment

**Comment by hesalx** [comment]
Return from a callback does not return from the outer function. In case you're coming from a language where `return` in a lambda returns from the outer function, this is not how it works in JavaScript.

The fact you are talking about a callback strongly also suggests that `.send()` is asynchronous in which case `return` in a callback is almost entirely irrelevant. There is nothing in the function `POST()` that would be able to capture the result of the callback passed to `.send()`. The function `POST()` reaches the end and returns `undefined` immediately after `.send()` is called and does not wait for the callback.
Consider the following example:

```js
async function POST() {
    setTimeout(() => { console.log("callback") }, 100);
    console.log("end of POST")
}
```
```
=> await POST()
  end of POST()
< undefined
  callback
```

If the lib you are using does not natively support promises (such that you could `await` the function) you can always wrap arbitrary callback-based code in a promise:

```tsx
return new Promise(resolve => {
  s3Client.upload({ ... }).send((err, data) => {
    if (err) {
      resolve(NextResponse.json({ message: "uploading fail!" }));
    } else {
      const url = data.Location;
      resolve(NextResponse.json({ url }));
    }
  });
})
```

**Comment by icyJoseph** [comment]
As the above says, you have to somehow await the async work. Promisifying the callback is one thing. 

However, I think the s3Client.upload, has a `.promise()` method, which you can await? If not, the above is the right way to go. 

- https://javascript.info/promisify

**Comment by zwelhtetyan** [comment]
Both solution are working perfectly. Thanks @hesalx @icyJoseph for your help ❤️!

**Comment by sannajammeh** [comment]
> Both solutions are working perfectly. Thanks @hesalx @icyJoseph for your help ❤️ .

If you wouldn't mind, close the issue if it's resolved :)
