### ISSUE TITLE
NextJS is always using worker threads when using the app router

### ISSUE THREAD

**Issue by lazarv** [vercel/next.js#50586]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.7.0
      npm: 8.19.4
      Yarn: 1.22.11
      pnpm: 8.6.0
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

Runtime issue, not related to app code, use `create-next-app`

### To Reproduce

- create a new next.js app, choose everything as default.
- install `next@canary`
- build app
- start app
- HTTP load test using `oha`

```
npx create-next-app@latest
cd my-app
npm i next@canary
npm run build
npm start

oha http://localhost:3000 -z 30s
```

### Describe the Bug

Connections to workers started by the main next.js server is starting to fail after 7-10s, server becomes unresponsive and receiving `ETIMEDOUT` errors from the next.js server:

```
Error: connect ETIMEDOUT ::1:55442
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '::1',
  port: 55442
}
``` 

If `useWorkers` is turned off, regardless of `appDir` is enabled or not, everything seems to work as expected.
`useWorkers` is using `config.experimental.appDir` here https://github.com/vercel/next.js/blob/canary/packages/next/src/cli/next-start.ts#L91

### Expected Behavior

`useWorkers` should be a configuration property, not based on `appDir` usage. Developer should be able to disable workers if not needed.

### How are you deploying your application? (if relevant)

next start

**Comment by mcavaliere** [comment]
I bet this is also related to https://github.com/vercel/next.js/issues/48748 .

**Comment by rochaalexandre** [comment]
This is also a problem when debugging a nextjs serve with intellij Idea, I took a long time to found that the command `NODE_OPTIONS='--inspect' next dev` that start the dev mode has the **useworkers**  hard coded as true. With this config intellij is not able to connect in the right node process to debug the apps.

The workaround for me was to edit the filenext/dist/server/lib/start-server.js line 152 and set the useWorkers as false.

**Comment by lazarv** [comment]
Next.js 13.4.20-canary.28 no longer uses child processes with `jest-worker` to run separate app and pages router.
