### ISSUE TITLE
No way to skip root layout

### ISSUE THREAD

**Issue by finom** [vercel/next.js#50591]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
NextJS 13 with app router
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

None

### To Reproduce

1. Create /app/layout.tsx
2. Create /app/something/layout.tsx
3. Create /app/something/page.tsx

Page /something inherits parent layout.

### Describe the Bug

This is not a feature request, this is a bug report. There is no way to use a custom layout for a nested route.

1. /app/something/layout.tsx is wrapped by  /app/layout.tsx
2. `useRouter` doesn't give a way to get current path at layout.tsx so I can't determine layout I need
3. `window.location` is unavailable.

To achieve what I want I need to use the following workaround:

1. Create a component called `AppLayout`
2. Use it to wrap /app/page.tsx (not layout.tsx)
4. Keep /app/something/layout.tsx as is
5. Create `layout.tsx` for all nested routes except of one (/app/foo/layout.ts, /app/bar/layout.ts but not for /app/something/layout.tsx) and wrap them by `AppLayout` or re-export default layout component at these files.

Another way is to ignore layout.tsx completely and use `AppLayout` wrapper in every app.tsx where it's needed. I would not do this if I had _app.tsx in the app router.

### Expected Behavior

I expect some way to disable parent layout so I don't need to find tricky workarounds to make app router work. I'm thinking to switch back to pages router because it less problematic.

### Which browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

Not relevant

**Comment by hesalx** [comment]
[Route Groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups)

```sh
/app/ # no layout
/app/(root)/layout.tsx      # your most common global layout
/app/(root)/about/page.tsx  # pages with the common layout
/app/(something)/layout.tsx # some unique layout 
/app/(something)/something/page.tsx # a page with a unique layout
```

The act of "skipping root layout" is simply moving the route to new group. You get a clean slate for each.

**Comment by finom** [comment]
@hesalx Looks like this is a workaround. Thank you.
