### ISSUE TITLE
appDir + async server component + scss-modules + fetch with cache: 'no-cache' = large precomputed chunk

### ISSUE THREAD

**Issue by aXenDeveloper** [vercel/next.js#50602]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Education
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: 13.4.5-canary.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/github/aXenDeveloper/fetch-ssr/

### To Reproduce

Repo: https://github.com/aXenDeveloper/fetch-ssr
1. Clone the repo, and run `npm run dev`,
2. Go to `http://localhost:3000/workspaces` page,
3. Refresh few time page

![image](https://github.com/vercel/next.js/assets/58148176/0e8ec019-c617-465f-ba6d-3dd218667afa)
![image](https://github.com/vercel/next.js/assets/58148176/af978881-ca50-4e38-9d34-c7036e9dd91d)

In codesandbox I have:
`Warning: A large precomputed chunk was passed to writeChunk without being copied. Large chunks get enqueued directly and are not copied. This is incompatible with precomputed chunks because you cannot enqueue the same precomputed chunk twice. Use "cloneChunk" to make a copy of this large precomputed chunk before writing it. This is a bug in React.`

### Describe the Bug

The problem is in cache in `fetch` when I use `scss-modules`. When I implement fetch with `cache: 'no-cache` I got an error in subpage `workspaces`:
File: `app/(layout)/(main)/workspaces/page.tsx`.
```
  const res = await fetch('https://apisocial.axendev.net/graphql', {
    method: 'POST',
    credentials: 'include',
    mode: 'cors',
    cache: 'no-cache',
    headers: {
      'Content-Type': 'application/json'
    }
```

But if I remove `cache: 'no-cache',` forks fine.
I checked also in home page with `cache: 'no-cache',` and it works fine.

It happens only when is `scss-modules`.
Similar bug: https://github.com/vercel/next.js/issues/42466

### Expected Behavior

Page should render the loading state immediately.

### Which browser are you using? (if relevant)

Chrome 113.0.5672.127

**Comment by WoLfulus** [comment]
Did you solve this issue?

**Comment by nitinTJ** [comment]
Any solution?

**Comment by aXenDeveloper** [comment]
Yes, check all your `layout.tsx` and remove unnecessary `async` in your function.
