### ISSUE TITLE
Favicons using image files don't work with Safari (iOS/Mac)

### ISSUE THREAD

**Issue by som-R91** [vercel/next.js#50623]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 20.2.0
      npm: 9.6.6
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.2
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/som-R91/nextjs-appDir-favicon-safari-bug

### To Reproduce

All I did was create a new project on Next Js using app directory, deleted the favicon.ico (Vercel logo), and added a different favicon.ico in the app directory as instructed on https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons.

### Describe the Bug

The new favicon shows up on the Google Chrome and Firefox browsers, but on Safari (both Mac/iOS) the Vercel logo still shows.

### Expected Behavior

All browsers should show the new favicon.

### Which browser are you using? (if relevant)

Safari 16.5, Chrome 113.0.5672.126, Firefox 112.0.1

### How are you deploying your application? (if relevant)

Vercel

**Comment by icyJoseph** [comment]
Hi,

Did you try to empty the Safari cache? 

![Screenshot 2023-06-02 at 10 54 28](https://github.com/vercel/next.js/assets/21013447/3510d042-5806-43ef-90c1-ea9a6c09aaa8)


Before I did that localhost:3000 was stuck at another favicon I used earlier.

**Comment by som-R91** [comment]
Thank you, icyJoseph. I tried that but it didn't work ☹️.
