### ISSUE TITLE
There's no way to access or use the generated type for `typedRoutes: true`

### ISSUE THREAD

**Issue by Svish** [vercel/next.js#50644]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 20.1.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/prod-mountain-hv2c45?file=%2Fapp%2Fpage.tsx%3A19%2C16

### To Reproduce

Create a component wrapping the strongly typed `Link` component from `next/link`:

```ts
import type { ReactNode } from 'react'
import clsx from 'clsx'
import NextLink from 'next/link'

interface Props {
  href: string
  className?: string
  children: ReactNode
}

export default function Link({ href, className, children }: Props) {
  return (
    <NextLink
      href={href}
      className={clsx('my common link classes all links should have', className)}>
      {children}
    </NextLink>
  )
}
```

### Describe the Bug

With `typedRoutes: true`, the `href` prop of `Link` is strongly typed, only allowing valid route-strings. So my example component, which is meant to wrap the `Link` component to add some general defaults like app-specific styling, cannot have a properly strongly typed `href` prop to pass through. I can fall back to `string` of course, but that removes the whole point of using `typedRoutes: true` in the first place. I want strong types, and I want my component wrapping `Link` to be equally strongly typed.

![image](https://github.com/vercel/next.js/assets/142162/55f13c85-e0f6-44e1-9c65-875f9c9b080c)

> Type 'string' is not assignable to type 'UrlObject | RouteImpl<string>'.ts(2322)  
> link.d.ts(77, 5): The expected type comes from property 'href' which is declared here on type 'IntrinsicAttributes & LinkRestProps & { href: UrlObject | RouteImpl<string>; }'  
> (property) href: UrlObject | __next_route_internal_types__.RouteImpl<string>  
> The path or URL to navigate to. This is the only required prop. It can also be an object.
> 
> @see — [https://nextjs.org/docs/api-reference/next/link](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

### Expected Behavior

There should be a straight-forward way to access and use the type of the helpful strongly typed `href` prop.

**Comment by HamAndRock** [comment]
Isn't Route what you are looking for ?

![image](https://github.com/vercel/next.js/assets/24235083/7d36ba33-f348-480b-9cad-56811248d6db)
