### ISSUE TITLE
[NEXT-1290] getServerSession in ServerAction

### ISSUE THREAD

**Issue by bfourgeaud** [vercel/next.js#50658]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.3
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/bfourgeaud/server-actions-session-repro

### To Reproduce

1 - Login (with any credentials)
2 - Click "Server Action" button
3 - See error on server side (terminal)

### Describe the Bug

Whenever I try to use `getServerSession `from `next-auth` in a server action, the server throws an error :
**`Error: Invariant: Method expects to have requestAsyncStorage, none available`**

On the other hand, on any other server component (home page of reproduction for example), there is no problem retrieving the current session.

### Expected Behavior

It should be possible to retrieve session information in server-actions the same way we retrieve them in any server-component.

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

next dev

<sub>[NEXT-1290](https://linear.app/vercel/issue/NEXT-1290/getserversession-in-serveraction)</sub>

**Comment by andrewmcoupe** [comment]
@bfourgeaud Have you tried passing the action as a prop to the client component?

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#props

**Comment by chungweileong94** [comment]
> @bfourgeaud Have you tried passing the action as a prop to the client component?
> 
> https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#props

Yes, this will fix the issue. I'm not sure if this is a bug or by design.

**Comment by bfourgeaud** [comment]
:heavy_check_mark: Ok it works when passing down props instead of making the call inside the server action.  

But it would simplify props handling if it were possible. For now I have to pass down session 3 levels down (`page -> button -> serverAction`), when I simply could make a call inside server action.
  
Before closing, maybe wait if that is intended behaviour or bug ?

**Comment by mirshko** [comment]
Im having the same issue, but it seems to be from the next/headers cookies package, not next-auth, or in my case auth-helpers from Supabase
