### ISSUE TITLE
Next App Router fails to return NextResponse inside of bcrypt hash callback

### ISSUE THREAD

**Issue by shrapnelnet** [vercel/next.js#50667]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home Single Language
    Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://pastebin.com/H4CkxH1A

### To Reproduce

Create a POST endpoint in the app directory. use bcrypt.hash and return a NextResponse in the callback.

### Describe the Bug

A HTTP 500 is always returned without the response body regardless of what is specified.

### Expected Behavior

The specified response body and status would be returned.

**Comment by icyJoseph** [comment]
Hi,

You gotta promisify the callback https://javascript.info/promisify

In the old days before promises, you'd schedule some work and pass a callback. It'd then be called when done.

Now in async/await and promises day, to couple with those old APIs' we must turn the process into a promise.

```ts
import bcrypt from "bcrypt";
import { Request } from "node-fetch";
import { NextResponse } from "next/server";
 
export async function POST(req: Request) {
    // get data from req body (irrelevant)
    const password: string = body.password;
    return new Promise((resolve, reject) => {

      bcrypt.hash(password, saltRounds, (_err, hash) => {
        // maybe you wanna do something with reject?
         resolve(NextResponse.json({ success: true }, { status: 200 }));
         // or maybe use if-else to resolve with NextResponse.json({error: true})
      });
    })
}
 
```

More precisely what is happening is that the synchronous portion of your code, finishes, and the runtime sees no event loop work leftover so it ends. If you return a promise rather, it'll await for it to settle, that is to reject or resolve.

**Comment by shrapnelnet** [comment]
@icyJoseph so sorry for adding what comes down to a trivial problem to the tracker. thank you for the prompt response ☺️

**Comment by icyJoseph** [comment]
No worries! This is how we learn. You can also start a discussion, and from there we can see if its a bug or something else going on. Have a good day!
