### ISSUE TITLE
next/link prefetch=false broken for dynamic routes

### ISSUE THREAD

**Issue by cjonesdoordash** [vercel/next.js#50670]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.5
      pnpm: 6.23.6
    Relevant packages:
      next: 13.5.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/cjonesdoordash/nextjs-prefetch-issue

### To Reproduce

Run the example and click the link to navigate between pages. You'll notice that the async data fetched within the layout.tsx file that shouldn't be re-fetched between navigations is refetched every time (it will hit cache eventually, but this behavior is incorrect as layouts shouldn't be re-rendered)

Another interesting side effect of this is if you hard reload a page after you've hit the fetch cache is that you'll get new data, but clicking a link to navigate will actually give you a cache hit on the old cache entry, which definitely shouldn't happen.

### Describe the Bug

To start off I've only been able to reproduce this issue when utilizing a dynamic segment (pages without a dynamic segment above them don't run into this issue).

If you use one and have pages below it that share a common layout and link to each other with prefetch set to false you can validate via console logs or fetch calls that the layout is re-ran on every navigation.

According to the docs layouts are meant to not re-render when you're just navigating within their segment.

### Expected Behavior

Setting prefetch to false on links doesn't break the documented layout behavior for dynamic routes

### Which browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

**Comment by cjonesdoordash** [comment]
Validated this issue is still happening with the latest version `13.4.10` - any chance someone is able to take a peek at this? It breaks support with how i18n is recommended to be built.

**Comment by eposha** [comment]
I have same issue

**Comment by cjonesdoordash** [comment]
Verified this is still happening with the latest release (13.5.4). Also simplified the example a bit. All you need to do is hit `localhost:3000/en/testing` and then click the link on the page and you'll notice the layout content changes.

**Comment by cjonesdoordash** [comment]
@timneutkens any chance you've been able to get someone to look into this issue?

**Comment by cjonesdoordash** [comment]
Confirmed this issue is resolved with the latest canary. Thanks!
