### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined when using Nextjs 13.4.4 api routes

### ISSUE THREAD

**Issue by faraasat** [vercel/next.js#50679]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
   Platform: win32
   Arch: x64
   Version: Windows 10 Enterprise
Binaries:
   Node: 18.14.1
   npm: N/A
   Yarn: N/A
   pnpm: N/A
Relevant packages:
   next: 13.4.5-canary.3
   eslint-config-next: 13.4.4
   react: 18.2.0
   react-dom: 18.2.0
   typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

For this issue you can find the repo here: https://github.com/faraasat/app-api-route-error . You can also access deployed version here: https://app-api-route-error.vercel.app/api/ and it is giving 500 Server Error.

### To Reproduce

The steps to reproduce are:

Create /api/route.ts in /app.

Now Paste the following code:

```typescipt
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  NextResponse.json({ message: "This Worked", success: true });
}

export async function POST(request: Request) {
  try {
    NextResponse.json({ message: "This Worked", success: true });
  } catch (err) {
    console.log(err);
    NextResponse.json({ message: err, success: false });
  }
}
```

### Describe the Bug

When accessing this API route using Postman or a browser, I am getting the error: "TypeError: Cannot read property 'headers' of undefined when using"

Screenshot of error when using Webpack:

![image](https://github.com/vercel/next.js/assets/63093876/da386547-b25e-4456-9a87-ca8f807d15e9)

Screenshot of error when using Turbopack:

![image](https://github.com/vercel/next.js/assets/63093876/c4f12350-939f-49a3-98fb-a3c07435dd93)

I encountered this bug when I was using next@13.4.4. I also tried it in next@13.5.3-canary.3 but I got the same error.

It worked fine when I used next@13.4.2.

As for the package manager, I am using pnpm.

Furthermore, this error occurs in both development and production.

### Expected Behavior

Successfully returns the JSON data when we put a GET or POST request on the API route.

### Which browser are you using? (if relevant)

Chrome 113.0.5672.129

### How are you deploying your application? (if relevant)

Vercel

**Comment by icyJoseph** [comment]
Add a `return` statement to the functions:

```ts
import { NextResponse } from "next/server";

export async function GET(request: Request) {
  return NextResponse.json({ message: "This Worked", success: true });
}

export async function POST(request: Request) {
  try {
    return NextResponse.json({ message: "This Worked", success: true });
  } catch (err) {
    console.log(err);
    return NextResponse.json({ message: err, success: false });
  }
}
```

**Comment by faraasat** [comment]
Thanks, that solved the issue in my case!
