### ISSUE TITLE
[NEXT-1249] When use `next/dynamic` in page router, the page mount twice

### ISSUE THREAD

**Issue by AkaraChen** [vercel/next.js#50682]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 11 Home
    Binaries:
      Node: 20.2.0
      npm: N/A
      Yarn: N/A
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.5-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic)

### Link to the code that reproduces this issue or a replay of the bug

Repo: https://github.com/AkaraChen/nextjs-reproduction-page-dir
Deploy: https://nextjs-reproduction-page-dir.vercel.app

### To Reproduce

1. clone my reproduction repo
2. `pnpm dev`

### Describe the Bug

1. `#__next` element have two children, all of the children have the same DOM sturcture `<div><button/></div>`
2. Both children is Rendered in client side, but only the second child can interact

### Expected Behavior

Only mount once.

### Which browser are you using? (if relevant)

Chrome 113.0.5672.127

### How are you deploying your application? (if relevant)

next dev

<sub>[NEXT-1249](https://linear.app/vercel/issue/NEXT-1249/when-use-nextdynamic-in-page-router-the-page-mount-twice)</sub>

**Comment by huozhi** [comment]
It's cannot be detected as the same module when it's not dynamic imported (`using import(..)`) from other module, it doesn't have a unique module id that can be matched.

The propery way to do it is move your loaded component to another file and use dynamic import.

You can only use inline function when `ssr` option is `false`, as it only render once on client so there's no module id matching problem.
