### ISSUE TITLE
Clicking back button after navigating with next/link causes page to download

### ISSUE THREAD

**Issue by timrae** [vercel/next.js#50686]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 19.8.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/timrae/nextjs-app-dir-reproduction

### To Reproduce

1. Start the web app (in prod)
1. Click the 'Page 1' tab
1. Click the 'Page 2' tab
1. Click the browser back button

### Describe the Bug

When running the reproduction case in production, the browser tries to download a file called 'page1' when you click the browser back button instead of going back to the page called page1. This doesn't happen in dev.

I'm using `next/link` with the Mui Tabs component, I'm not sure if this is relevant or not.
I'm also using a hidden nested route so that I can use a client-side root template.

Also not sure if this is related to #45595 or not.

### Expected Behavior

Browser goes back to the previous page without trying to download anything

### Which browser are you using? (if relevant)

Chrome 113.0.5672.127

### How are you deploying your application? (if relevant)

Netlify

**Comment by timrae** [comment]
Here's a quick link to the problematic code: https://github.com/timrae/nextjs-app-dir-reproduction/blob/main/app/AppBar.tsx
It's running in production here if you just want to quickly see the behaviour: https://rad-bavarois-7ffe08.netlify.app/

**Comment by icyJoseph** [comment]
@timrae For some reason, in your app, navigating between tabs, reloads the entire page:

https://github.com/vercel/next.js/assets/21013447/97447baa-8b4c-421e-a760-619f28543461

As you can see at the end of the video, it is only when I disable the cache, that the page downloads. Obviously, a common user, with dev tools closed, has enabled cache so that happens to them.

The question is, why is your app not doing SPA navigation, rather it unloads, and I think that makes the browser save the `.rsc` format as the "the page", so that when you go back to it, it downloads the file.

Hopefully this is not a false lead into the issue 🤞

**Comment by timrae** [comment]
Yes I noticed that it's not doing the SPA navigation as well. It works
correctly in dev though, so I'm not really sure how to proceed with this...
Please let me know if you have any suggestions.

**Comment by icyJoseph** [comment]
Could this be related? https://github.com/vercel/next.js/pull/49140 somehow the CDN is not serving the rsc file but the HTML one, and that breaks?

**Comment by timrae** [comment]
Thanks for your comments, I don't have enough understanding of next.js to say either way, but I tried deploying to Vercel instead of Netlify and it's working there so I'll close this issue for now :)
