### ISSUE TITLE
Memory leak on v12

### ISSUE THREAD

**Issue by FlorisdeG** [vercel/next.js#50690]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 12.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue or a replay of the bug

Not relevant

### To Reproduce

Unable to reproduce with a clean build. The problem probably exists mostly with larger projects & extra packages. We don't have a lot of images on the website and disabled image optimisation, so next/image is not the problem in this case.

### Describe the Bug

We are experiencing excessive memory usage that grows indefinitely, we see this problem from multiple sources. The only reason it goes down again is because we temporarily restart the server automatically when it hits a certain threshold.

![image-2023-05-30-09-12-29-092](https://github.com/vercel/next.js/assets/93332997/cc56fe77-d58d-402a-b18a-4d7f9a618eae)

### Expected Behavior

The memory usage should be a steady line.

### How are you deploying your application? (if relevant)

next start

**Comment by altechzilla** [comment]
Not sure if related to these issues linked here:
https://github.com/vercel/next.js/issues/50332

**Comment by ijjk** [comment]
Hi, please update to the latest version of Next.js v13 as v12 is missing a lot of updates! If you are still seeing issues with this in latest version we would be happy to investigate further!
