### ISSUE TITLE
File-based Metadata - opengraph-image and twitter-image has unexpected behaviour

### ISSUE THREAD

**Issue by agilxpgeoffrey** [vercel/next.js#50698]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$ next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.1.1
    Relevant packages:
      next: 13.4.5-canary.3
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3

✨  Done in 1.98s.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue or a replay of the bug

N/A

### To Reproduce

Add an opengraph-image.png or twitter-image.png in the `/app` directory and meta tags are working as expected - og:image/twitter:image and derivative are added.

Create a page in a sub-directory and export metadata containing `openGraph` and/or `twitter` then you get only what was defined in the metadata export.

Following would result in no `og` or `twitter` meta tags:
```
export const metadata: Metadata = {
    // ...
    openGraph: {},
    twitter:{}
}
```

However, if you add the png in the same folder, it works as expected again.

### Describe the Bug

I didn't expect the `twitter:image` and `og:image` (with size, etc) to disappear because I added some metadata in a sub directory.

### Expected Behavior

I expected the metadata to be merged.

### How are you deploying your application? (if relevant)

same on Vercel and locally with next dev

**Comment by huozhi** [comment]
Do you mean the metadata only merges the same level of routes? That's expected behavior, you can check the merging behavior in [next.js metadata docs](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#merging)

As it could be pretty complex senarios to merge the metadata we let users themselves to merge it with parent. You can use `generateMetadata({ params }, resolvingParentMetadata)` API and merge the current export ones with `resolvingParentMetadata`

**Comment by agilxpgeoffrey** [comment]
Nice. Thanks @huozhi. 
Suggestion: It might be nice to get a line about this or a reference to this in https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image.
