### ISSUE TITLE
Latest version locking up!

### ISSUE THREAD

**Issue by billnbell** [vercel/next.js#50707]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
See https://github.com/vercel/next.js/issues/45508#issuecomment-1574010754
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/issues/45508#issuecomment-1574010754

### To Reproduce

See https://github.com/vercel/next.js/issues/45508#issuecomment-1574010754

### Describe the Bug

https://github.com/vercel/next.js/issues/45508#issuecomment-1574010754

### Expected Behavior

https://github.com/vercel/next.js/issues/45508#issuecomment-1574010754

**Comment by BuddhiAbeyratne** [comment]
Suggest adding this at the end of build scripts for now 

https://github.com/vercel/next.js/issues/45508#issuecomment-1560568292

**Comment by shuding** [comment]
Let's keep the conversation in that existing issue instead of having a new one, this doesn't help solving the problem but makes it harder for the team to track. Thanks!
