### ISSUE TITLE
@next/mdx - metadata is ignored

### ISSUE THREAD

**Issue by AdisonCavani** [vercel/next.js#50734]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), MDX (@next/mdx), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/AdisonCavani/next-mdx-metadata-issue-reproduction

### To Reproduce

```bash
cd src
pnpm i
pnpm dev
```

Go to `/mdx` page

See `<head>` - no changes to metadata (author missing)

### Describe the Bug

When I add `metadata` to my `page.mdx`:

```mdx
export const meta = {
  author: 'Rich Haines',
};

# Sample MDX page
```

The metadata is ignored and the `<head>` does not contain `author` (and other) metadata.

Also, the [docs for MDX in `app dir`](https://nextjs.org/docs/app/building-your-application/configuring/mdx) (section getting started) should have information about adding `mdx` to [`pageExtensions`](https://nextjs.org/docs/pages/api-reference/next-config-js/pageExtensions):

```js
// next.config.js
module.exports = {
  pageExtensions: ['mdx', 'md', 'jsx', 'js', 'tsx', 'ts'],
  // Other settings...
};
```

### Expected Behavior

The `<head>` should be updated with provided metadata in `.mdx` page

**Comment by pokey** [comment]
I'm not sure I'd expect the `head` to pick this metadata up automatically, but the docs are very unclear on how to use metadata.  They just say how to add it to the `.mdx` file, but give no instructions about what to do next.  [Here's](https://nextjs.org/docs/app/building-your-application/configuring/mdx#frontmatter) the section I'm referring to

**Comment by aksxaay** [comment]
Adding on to what pokey since, this is something I looked into as well, rather than defining the exports for every markdown file you end up creating, you can generalize by declaring a new module with `.mdx` extension

`app/mdx.d.ts`
```ts
declare module '*.mdx' {
  export const meta: { title: string, date: string?, description: string?};
}
```
you can carry on editing `page.tsx`
```tsx
"use client";
import HelloWorld, { meta } from "./hello.mdx";

export default function Page() {
  return (
    <>
      <article className="prose py-6 dark:prose-invert">
        <p>{meta.title}</p>
        {/* {HelloWorld.toString()} */}
        <HelloWorld />
      </article>
    </>
  );
}

```

**Comment by thomaszdxsn** [comment]
you need `export const metadata`, it's your expectation
