### ISSUE TITLE
Docs: eslint and eslint-config-next are not installed as development dependencies in Next.js 13

### ISSUE THREAD

**Issue by tjhoo** [vercel/next.js#50731]
### What is the improvement or update you wish to see?

In the [ESLint configuration](https://nextjs.org/docs/app/building-your-application/configuring/eslint#additional-configurations)
```
...
if either of the two configuration options are selected, Next.js will automatically install eslint and eslint-config-next as development dependencies in your application
...
```
Please note that `create-next-app` is not installing `eslint` and `eslint-config-next` as a development dependencies anymore.

### Is there any context that might help us understand?

I'm trying to figure out if we should ever need to install packages like eslint, prettier, prisma as development dependencies.

Also in the [Prettier configuration](https://nextjs.org/docs/app/building-your-application/configuring/eslint#prettier) section, it describes the installation of development dependencies
```
npm install --save-dev eslint-config-prettier
```

This is rather confusing becuase `create-next-app` is not installing development dependencies but many of the Versal examples in Git and documents are still promote the development dependencies.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/configuring/eslint#additional-configurations

<sub>[DX-1652](https://linear.app/vercel/issue/DX-1652/docs-eslint-and-eslint-config-next-are-not-installed-as-development)</sub>

**Comment by alcpereira** [comment]
I was also a bit surprised by seeing everything in `dependencies` (`@types`, `eslint`, etc) but it seems it comes from this [feature](https://nextjs.org/docs/pages/api-reference/next-config-js/output) and this [PR](https://github.com/vercel/next.js/pull/42218).

**Comment by tjhoo** [comment]
If that is the case then it would be very helpful that the installation of development dependencies should be replaced in all the documents and examples, to avoid the confusion.

**Comment by balazsorban44** [comment]
Hi, since this is not affecting builds and is more like a stylistic change/simplification, I'm closing the issue. We welcome PRs to do this change on examples/documentation gradually though! :pray:
