### ISSUE TITLE
NEXT_REDIRECT in ServerActions

### ISSUE THREAD

**Issue by bfourgeaud** [vercel/next.js#50757]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/bfourgeaud/server-actions-redirect-repro

### To Reproduce

1 - Run the minimal reproduction - go to `localhost:3000`
2 - Click button _Redirect Action -- This throws an error_
3 - See error `NEXT_REDIRECT `on server terminal

### Describe the Bug

When using `redirect('/.../...')` inside of server action, it throws an error whenever the redirect is inside a try..catch.

```ts
// WORKS
export async function redirectAction() {
  const newPost = await new Promise<{ id: string }>((res, rej) => setTimeout(() => res({ id: "1" }), 2000))
  redirect(`/posts/${newPost.id}`)
}
```

```ts
//THROWS ERROR
export async function redirectErrorAction() {
  try {
    const newPost = await new Promise<{ id: string }>((res, rej) => setTimeout(() => res({ id: "1" }), 2000))
    redirect(`/posts/${newPost.id}`)
  } catch(err) {
    console.log(err)
    return { error: "An error occured" }
  }
}
```

### Expected Behavior

It should be possible to use try...catch in serverActions and redirect only on succeeded.

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

next dev

**Comment by joulev** [comment]
What happened here is that `redirect` actually throws an error of its own, `NEXT_REDIRECT`

> Invoking the `redirect()` function throws a `NEXT_REDIRECT` error &mdash; [source](https://nextjs.org/docs/app/api-reference/functions/redirect#redirect)

This error is then caught by your `try`-`catch`, then is logged to the server terminal by that `console.log(err)`. I wouldn't say this is a bug.

**Comment by shuding** [comment]
This is by design as documented here: https://nextjs.org/docs/app/api-reference/functions/redirect#redirect. `redirect()` will throw as a signal to indicate Next.js to stop continuing executing the route below it as it's already redirected.
