### ISSUE TITLE
Docs: `DOMException` with `insertBefore` during frequent page transitions with language translation in Next.js-based documentation sites

### ISSUE THREAD

**Issue by taichi221228** [vercel/next.js#50751]
### What is the improvement or update you wish to see?

I have encountered an `insertBefore` `DOMException` issue during frequent page transitions combined with the use of the language translation function. This issue has been experienced on several Next.js-based documentation sites:

#### Definitively observed on:
- [Next.js Documentation](https://nextjs.org/docs)

#### Potentially observed on, but requires further verification:
- [SWR Documentation](https://swr.vercel.app/docs/getting-started)
- [Nextra Documentation](https://nextra.site/docs)
- [CVA Documentation](https://cva.style/docs)

This error poses significant hindrances to non-English speaking users who rely on translation tools. Thus, an investigation and resolution of this issue would greatly enhance the user experience and accessibility of these resources for users worldwide.

#### Steps to Reproduce the Bug

Note: Although this uses a special procedure to reproduce the bug, the bug has been confirmed to occur even under normal usage. Also, certain browsers, such as Safari, may crash the site just by translating the page.

1. Navigate through various pages within the site to accumulate history.
2. Translate the page into a language other than English.
3. Rapidly trigger the "back" and "forward" browser functions to induce high-speed rendering.
4. Observe that the bug occurs.

A video demonstrating this bug can be found at the following link: [Reproduction of Bug](https://gyazo.com/c66683062f90fde7c59acc450ae2e52f)

It appears that the DOM operations by the translation tool and the DOM management by the application may be in conflict. However, I lack the necessary expertise to fully investigate the cause and provide a solution.

I kindly request the assistance of the Next.js team to investigate this issue and to provide a solution. This issue significantly affects the accessibility and usability of Next.js-based documentation sites for non-English speaking users.
<img width="1592" alt="image" src="https://github.com/vercel/next.js/assets/58300794/f41fd5c5-0369-4431-a6b5-ff3ae8187419">

**Comment by balazsorban44** [comment]
This is tracked in https://github.com/vercel/next.js/issues/51101 so I'm closing in favor. thanks for reporting!
