### ISSUE TITLE
`next.config` `basePath` causes full page reload

### ISSUE THREAD

**Issue by HappyTribe** [vercel/next.js#50784]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: N/A
      pnpm: 8.6.0
    Relevant packages:
      next: 13.4.5-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/HappyTribe/nextjs-render-test
https://nextjs-render-test-git-main-happytribe.vercel.app/app

https://github.com/HappyTribe/nextjs-render-test-without-basepath
https://nextjs-render-test-without-basepath-git-main-happytribe.vercel.app/

### To Reproduce

1. Open provided [link](https://nextjs-render-test-git-main-happytribe.vercel.app/app).
2. Navigate to any sub route
3. Navigate back to the home page

To emphasise/better see the rerendering of the page you can use the "paint flashing" option available under Developer Tool -> More Tools -> Rerendering -> Paint flashing.

### Describe the Bug

When navigating from any sub page to the home page the browser does a full reload/rerender.

Project deployed WITH `basePath` set does a full reload when navigating.
https://nextjs-render-test-git-main-happytribe.vercel.app/app

Same project deployed but WITHOUT `basePath` set doesn't do a full reload:
https://nextjs-render-test-without-basepath-git-main-happytribe.vercel.app/

### Expected Behavior

When navigating to and from different pages that use a common layout the whole page should not rerender but only the "sub-section" of the page that changes.

### Which browser are you using? (if relevant)

Chrome 114.0.5735.90 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

**Comment by tom-sherman** [comment]
We also have this problem when deploying to Vercel. The problem cannot be replicated with `next start`.

**Comment by tom-sherman** [comment]
This looks to be fixed on the latest canary.

See https://nextjs-basepath-render-test-hmu9ahmkn-tomsherman.vercel.app/app

https://github.com/tom-sherman/nextjs-render-test/commit/da1fcdecc4ec4769d550c38208d9123269191663

**Comment by tom-sherman** [comment]
Also see #48305

**Comment by HappyTribe** [comment]
Closing issue in favour of older issue #48305.

**Comment by HappyTribe** [comment]
Thanks for the help! @tom-sherman
