### ISSUE TITLE
generateMetadata - Title Template - TS error

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#50789]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.5
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js), TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/modest-voice-h0q6qv?file=%2Fapp%2Flayout.tsx%3A18%2C1-19%2C1

### To Reproduce

Open the example repo, you can see the TS error there, or run a build command in the terminal, to get the error:

![image](https://github.com/vercel/next.js/assets/987947/4a31afb1-a57e-417b-9ab4-1a652ec7af80)

### Describe the Bug

I followed this guide here, how to work with the metadata template object and how to set a prefix/suffix:

https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template

![image](https://github.com/vercel/next.js/assets/987947/30cd0189-6dc2-4aad-8dee-bc32de2326ff)

If you do so, you will get an typescript build error:

```tsx
Type error: Type '{ template: string; }' is not assignable to type 'string | TemplateString'.
  Property 'absolute' is missing in type '{ template: string; }' but required in type 'AbsoluteTemplateString'.
```

### Expected Behavior

Just work.

**Comment by icyJoseph** [comment]
Interesting, I think the docs are not up to date. Moreover,  the types have gone through a lot of changes 👀 

- https://github.com/vercel/next.js/commit/2e251cb85fd4104aa473bb2538276bb671c63d65

I guess, they ought to update the docs

**Comment by huozhi** [comment]
@ciruz the reproduction on codesandbox is using a very old version 

```
next@canary:
  version "13.1.7-canary.10"
```

Can you upgrade to the latest stable or canary?

**Comment by ciruz** [comment]
@huozhi with the latest stable, you get the error too, so maybe the docs are wrong as @icyJoseph said.

**Comment by ciruz** [comment]
@huozhi  I just updated the codesandbox to `next@^13.4.5-canary.5`:

![image](https://github.com/vercel/next.js/assets/987947/301a4aa1-728c-4c5a-973a-b0c57af358c7)

The error still exists:
![image](https://github.com/vercel/next.js/assets/987947/5ba33862-c113-4c40-8ae4-af32c0191ac8)

**Comment by huozhi** [comment]
`default` property is required when you use with template, thanks for pointing out, looks the docs need to update. will update later.

The reproduction template also needs to update as the version was incorrectly locked in it. Will follow up on that

**Comment by huozhi** [comment]
The [document](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template) is updated now, thank you both for reporting and checking the docs 🙏

**Comment by huozhi** [comment]
Good news: codesandbox will fix the cache issue for the yarn.lock soon!

**Comment by ciruz** [comment]
Awesome thank you @huozhi so there was really something wrong.

In the meantime I found another issue regarding title templates: https://github.com/vercel/next.js/issues/50827
