### ISSUE TITLE
Script Tag not working as expected in APP DIR

### ISSUE THREAD

**Issue by ALWISHARIFF** [vercel/next.js#50812]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
    Binaries:
      Node: 16.19.0
      npm: 8.19.4
      Yarn: 3.5.0
      pnpm: 8.6.0
    Relevant packages:
      next: 13.4.5-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which example does this report relate to?

NEXT JS Script TAG

### What browser are you using? (if relevant)

Mozilla 113.0.2 

### Describe the Bug

I am trying to load some Javascript from the layout.js using the Script tag but the execution is not in order as in the layout.js
```
import './globals.css'
import { Inter } from 'next/font/google'

import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/css/icons.css" />
        {/* <!--  animate css plugins --> */}
        <link rel="stylesheet" href="/css/animate.css" />
        {/* magnific-popup css plugins -->*/}
        <link rel="stylesheet" href="/css/magnific-popup.css" />
        {/* <!--  owl carosuel css plugins --> */}
        <link rel="stylesheet" href="/css/owl.carousel.min.css" />
        {/* <!-- metis menu css file --> */}
        <link rel="stylesheet" href="/css/metismenu.css" />
        {/* <!--  owl theme css plugins --> */}
        <link rel="stylesheet" href="/css/owl.theme.css" />
        {/* <!--  Bootstrap css plugins --> */}
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        {/* <!--  aos css plugins --> */}
        <link rel="stylesheet" href="/css/aos.min.css" />
        {/* <!--  main style css file --> */}
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body className={inter.className}>{children}</body>
      <Script src="/js/jquery.min.js" defer />
      <Script src="/js/modernizr.min.js" defer />
      <Script src="/js/jquery.easing.js" defer />
      <Script src="/js/popper.min.js" defer />
      <Script src="/js/bootstrap.min.js" defer />
      <Script src="/js/isotope.pkgd.min.js" defer />
      <Script src="/js/imageload.min.js" defer />
      <Script src="/js/scrollUp.min.js" defer />
      <Script src="/js/owl.carousel.min.js" defer />
      <Script src="/js/magnific-popup.min.js" defer />
      <Script src="/js/easypiechart.min.js" defer />
      <Script src="/js/counterup.min.js" defer />
      <Script src="/js/wow.min.js" defer />
      <Script src="/js/metismenu.js" defer />
      <Script src="/js/timeline.min.js" defer />
      <Script src="/js/ajax-mail.js" defer />
      <Script src="/js/aos.min.js" defer />
      <Script src="/js/active.js" defer />
    </html>
  )
}
```
I am getting the error message
```Warning: validateDOMNesting(...): <script> cannot appear as a child of <html>```
When i added the defer attribute it doesnt execute in order.
```Warning: Cannot render a sync or defer <script> outside the main document without knowing its order. Try adding async="" or moving it into the root <head> tag```

The Script tag with defer should execute the scripts in different orders it doesn't follow the order as stated in the code

### Expected Behavior

The Script tag with defer should execute the scripts in the order in code

### To Reproduce

A next js project running latest next js canary and stable that uses the nextjs Script tag to load external script use multiple Script tags in the APP DIR on the layout.js or page.js files with the defer attribute to view the Execution  bug.

**Comment by ciruz** [comment]
You mixing things up, `<head>` and importing css like this is not the right way in App Router.
Remove the `<head>`, this does not exist in the App Router (anymore).

I also just tested it, I can use `next/script` and css files inside the `layout.tsx` without any problems, but as soon as I add the invalid `<head>` element, will get the `validateDOMNesting` error.

PS: you can import css files like so:

```tsx
import "leaflet/dist/leaflet.css";
```

So this is not an issue at all.

**Comment by ALWISHARIFF** [comment]
I imported all the css files using the import statement removed the head tags from the layout file added the script with defer attributes the scripts are not executed in order even after adding defer to the script tags

**Comment by ALWISHARIFF** [comment]
This means the error still exists The Script tag is not working as expected I will close the Duplicate and leave this

**Comment by leerob** [comment]
As mentioned above, you should [import the script](https://github.com/vercel/next.js/issues/50812#issuecomment-1578225325). Learn more about metadata here: https://nextjs.org/docs/app/building-your-application/optimizing/metadata

**Comment by ALWISHARIFF** [comment]
The issue still exist are you dropping support for the script tag in next 13 
next/script has the errors above as for now

**Comment by leerob** [comment]
Is this the script issue you are seeing? https://github.com/vercel/next.js/issues/51242

Here's the list of unsupported metadata and their alternatives: https://nextjs.org/docs/app/api-reference/functions/generate-metadata#unsupported-metadata
