### ISSUE TITLE
Page defined in the same folder as layout ignores layout Metadata template

### ISSUE THREAD

**Issue by ciruz** [vercel/next.js#50827]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.6
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/ciruz/next.js-title-template

### To Reproduce

Checkout the repository and the deployed example on vercel:

https://github.com/ciruz/next.js-title-template/blob/master/app/folder/layout.tsx#L5
https://github.com/ciruz/next.js-title-template/blob/master/app/folder/page.tsx#L5
https://github.com/ciruz/next.js-title-template/blob/master/app/folder/foobar/page.tsx#L4

- https://next-js-title-template.vercel.app/folder
expected title: `folder/page | layout.tsx` 
result: `folder/page`

- https://next-js-title-template.vercel.app/folder/foobar
expected title: `folder/foobar/page | layout.tsx`
result: `folder/foobar/page | layout.tsx`

### Describe the Bug

It looks like if you have a `layout.tsx` with a [template title](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template), the first `page.tsx` which is inside the same directory as the `layout.tsx` file, uses the layout, as described [here](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts), but ignores the Metadata title template.

Look at following code:

```tsx
//app/folder/layout.tsx
export const metadata: Metadata = {
  title: {
    template: "%s | layout.tsx",
    default: "Default Title",
  },
};


//app/folder/page.tsx
export const metadata: Metadata = {
  title: "folder/page",
};

// expected title => folder/page | layout.tsx
// result         => folder/page


//app/folder/anotherfolder/page.tsx
export const metadata: Metadata = {
  title: "folder/anotherfolder/page",
};

// expected title => folder/anotherfolder/page | layout.tsx
// result         => folder/anotherfolder/page | layout.tsx
```

If you don't define a title inside the `page.tsx` file then it will uses the the correct default template title, like this:

```tsx
//app/folder/layout.tsx
export const metadata: Metadata = {
  title: {
    template: "%s | layout.tsx",
    default: "Default Title",
  },
};


//app/folder/page.tsx
export const metadata: Metadata = {
  description: "no title defined, only a description",
};

// expected title => Default Title
// result         => Default Title
```

### Expected Behavior

Show the correct page title

**Comment by freund17** [comment]
Have had a look at #46859?

I think you're describing the same issue.

**Comment by huozhi** [comment]
Per above. Close as duplicated of #46859
