### ISSUE TITLE
App directry cannot get app directory custom global variable

### ISSUE THREAD

**Issue by xingyibiao** [vercel/next.js#50826]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/dazzling-kilby-owv2wd?file=%2Fapp.js%3A6%2C1

### To Reproduce

custom server set global.foo = 'bar'
in page.tsx get global.foo

### Describe the Bug

custom server set global.foo = 'bar'
but in page.tsx console.log(gloabl.foo) will be undefined

### Expected Behavior

expect in page.tsx console.log(global.foo) should be 'bar'

### Which browser are you using? (if relevant)

Chrome 100.0.4878.0

### How are you deploying your application? (if relevant)

custom server (express)

**Comment by shuding** [comment]
The Next.js rendering server isn't running in the main process as the custom server, to pass information you'll have to use environment variables.

**Comment by xingyibiao** [comment]
> The Next.js rendering server isn't running in the main process as the custom server, to pass information you'll have to use environment variables.

How to  use global method?
