### ISSUE TITLE
[NEXT-1305] Errors in generateMetadata are not caught by global-error.tsx boundary in dev mode

### ISSUE THREAD

**Issue by tom-sherman** [vercel/next.js#50863]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.13.2
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.4.5-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App router, error boundary, metadata

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tom-sherman/nextjs-generate-metadata-bug

### To Reproduce

1. `pnpm dev`
2. Visit `/`

### Describe the Bug

It shows the default Next.js error page when in dev mode. When in production mode (`next start`) it works though.

### Expected Behavior

It should show my custom error boundary.

### How are you deploying your application? (if relevant)

Not relevant

See also See also https://github.com/vercel/next.js/discussions/49925

<sub>[NEXT-1305](https://linear.app/vercel/issue/NEXT-1305/errors-in-generatemetadata-are-not-caught-by-global-errortsx-boundary)</sub>

**Comment by arjenbloemsma** [comment]
Hi @tom-sherman, 

To catch errors coming from the 'generateMetadata' function you need to add a 'global-error.tsx' to your app directory.

I've created a PR for your reproduction repo that implements this.

You can find more details in the nextjs docs [here](https://nextjs.org/docs/app/building-your-application/routing/error-handling#handling-errors-in-root-layouts).

Kind regards,

Arjen

**Comment by tom-sherman** [comment]
I was sure that I tried that approach 🤔 

Thanks!

**Comment by tom-sherman** [comment]
I've realised this bug only relates to dev mode, that's why I was sure I tried global-error before: I had, but not in production mode.

I've updated the issue to reflect this as a bug with global-error, metadata, and dev-mode.

**Comment by tom-sherman** [comment]
@huozhi I also have an issue with this in prod mode where errors thrown in generateMetadata in a page with a nested layout fails.

See https://github.com/tom-sherman/nextjs-generate-metadata-bug/commit/4ff00f9157509089122bff36266b6b50cd307ce5

This doesn't show the global error with `next start`.

Is this included in your internal issue or should I create a separate issue for this?

**Comment by huozhi** [comment]
@tom-sherman thanks for reporting and mentioning the behaviors in various case, could cover that as well. Internal issue tracking includes all context from github issue, it's covered.

**Comment by PaulWild** [comment]
just to +1 @tom-sherman , we experienced this issue in production with a nested route in production.
