### ISSUE TITLE
[NEXT-1334] Next/Font jitters and causes a slight layout shift when using revalidatePath() or revalidateTag()

### ISSUE THREAD

**Issue by elliotgonzalez123** [vercel/next.js#50879]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 16.16.0
      npm: 9.6.7
      Yarn: 1.22.4
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.6
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Font optimization (next/font)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/elliotgonzalez123/next-font-jitter

### To Reproduce

Refresh page, or click one of the "delete" buttons

### Describe the Bug

The font on the page when using next/font will jitter and cause a layout shift when calling `revalidateTag()` or `revalidatePath()` inside a server action.  You can also trigger the jitter by simply refreshing the page.  If you remove the next/font package the jitter goes away.

Related discussion here: https://github.com/vercel/next.js/discussions/50782

https://github.com/vercel/next.js/assets/49325153/c69056b9-6a29-4a3c-9858-a0bc3492d28f

### Expected Behavior

The font does not jitter or cause a layout shift when calling `revalidateTag()` or `revalidatePath()` inside a server action.

### Which browser are you using? (if relevant)

Chrome Version 112.0.5615.137 (Official Build) (x86_64)

<sub>[NEXT-1334](https://linear.app/vercel/issue/NEXT-1334/nextfont-jitters-and-causes-a-slight-layout-shift-when-using)</sub>

**Comment by santiagoesteva** [comment]
+1 If I disable next/font/google the jitter  from layout, the jitter goes away
