### ISSUE TITLE
Property 'handler' is incompatible with index signature.     Type 'AuthOptions' is not assignable to type 'never'.

### ISSUE THREAD

**Issue by sundaram2021** [vercel/next.js#50870]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
when i running build command , i get this error

.next/types/app/api/auth/[...nextauth]/route.ts:8:13
Type error: Type 'OmitWithTag<typeof import("C:/Desktop/blog/src/app/api/auth/[...nextauth]/route"), "POST" | "GET" | "PUT" | "config" | "generateStaticParams" | "revalidate" | "dynamic" | "dynamicParams" | ... 6 more ... | "PATCH", "">' does not satisfy the constraint '{ [x: string]: never; }'.
  Property 'handler' is incompatible with index signature.
    Type 'AuthOptions' is not assignable to type 'never'.

   6 |
   7 | // Check that the entry is a valid entry
>  8 | checkFields<Diff<{
     |             ^
   9 |   GET?: Function
  10 |   HEAD?: Function
  11 |   OPTIONS?: Function
- info Linting and checking validity of types ...
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/sundaram2021/blog-typescript-fullstack.git

### To Reproduce

npm run build

### Describe the Bug

not able to build the app for production

### Expected Behavior

should build the app without any issue

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by userari** [comment]
The problem persists in stable Next Js version 13.4.5 (the exact same issue )

`
    "next": "13.4.5",
    "next-auth": "^4.22.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"
`

**Comment by zpydee** [comment]
and with `next@13.4.6`

**Comment by zpydee** [comment]
I got mine to build with:

(in `/app/api/auth/[...nextauth]/route.ts):

```ts
//  Type cast is a workaround for https://github.com/vercel/next.js/issues/50870
const authOptions = {
  // ....
} as never;
```

but then on Vercel, it fails after build with

```bash


Build Completed in /vercel/output [2m]
--
17:26:13.061 | Deploying outputs...
17:26:21.078 | Failed to process build result for "api/auth/[...nextauth]". Data: {"type":"Lambda"}.
17:26:21.080 | Error: The Serverless Function "api/auth/[...nextauth]" is 52.69mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
17:26:23.128 | NOW_SANDBOX_WORKER_MAX_LAMBDA_SIZE: The Serverless Function "api/auth/[...nextauth]" is 52.69mb which exceeds the maximum size limit of 50mb.


```

I'm guessing this could be related to using nextauth with new app router...

**Comment by danghieuliem** [comment]
You can add `ignoreBuildErrors: true` to `nextConfig`
next.config.js
```javascript
const nextConfig = {
  typescript: {
     ignoreBuildErrors: true,
  },
};

module.exports = nextConfig;
```

**Comment by sundaram2021** [comment]
`<html>
<body>


Type error: Route "src/app/api/auth/[...nextauth]/route.ts" does not match the required types of a Next.js Route.
--
15:46:57.406 | "authOptions" is not a valid Route export field.
15:46:57.406 |  
15:46:57.557 | Error: Command "npm run build" exited with 1
15:46:57.835 | BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1


</body>
</html>
`

getting this error after few changes in the code .

whole app is completed as per my aspirations and works as I want  but in production it causes error

**Comment by balazsorban44** [comment]
Hi, you can move `authOptions` into a different file, (eg.: `auth.ts`) and import it from there, to make this go away.

I'm working on a new version of NextAuth.js which won't have this issue. In any case, Next.js behaves as expected here, so I'm closing this issue.
