### ISSUE TITLE
`dev server` warning of a memory leak

### ISSUE THREAD

**Issue by Josehower** [vercel/next.js#50909]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 20.2.0
      npm: 9.6.6
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.4-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/next-memory-leak-reproduction-dev-mode-nvfvrl

### To Reproduce

to reproduce:

1. Visit the reproduction sandbox
2. Open a log tab
3. click in the fire button in the browser tab (to trigger multiple request to different pages simulating high traffic)
4. verify that you receive the following error in the log tab:
```
(node:1491) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 29 unpipe listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Describe the Bug

This error may validate [other issues with similar problems that have been documented](https://github.com/vercel/next.js/issues/49929) with a posible leak in Next.js. If the leak exists is really problematic form small apps running in some servers with low amount of ram. Its important to say that this error only shows in `dev server` mode.

If its a false alarm also it would need to be removed.

### Expected Behavior

requesting multiple pages in an app should't cause any memory leak 

<sub>[NEXT-1431](https://linear.app/vercel/issue/NEXT-1431/dev-server-warning-of-a-memory-leak)</sub>

**Comment by holicreact** [comment]
me too same see

**Comment by shuding** [comment]
Should be better with #52360. There's still an event emitter that gets registered too many times but it's not a leak I believe. Will look into fixing that too.

**Comment by timneutkens** [comment]
Going to close this issue as https://github.com/vercel/next.js/pull/52360 was landed.
