### ISSUE TITLE
Unable to get pg module to work

### ISSUE THREAD

**Issue by lucgagan** [vercel/next.js#50921]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.9.0
      npm: 9.6.3
      Yarn: N/A
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.5-canary.6
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

N/A

### To Reproduce

N/A

### Describe the Bug

```
./node_modules/.pnpm/pg@8.11.0/node_modules/pg/lib/crypto/utils.js
Error: 
  x Return statement is not allowed here
    ,-[/Users/blog/node_modules/.pnpm/pg@8.11.0/node_modules/pg/lib/crypto/utils.js:4:1]
  4 | if (useLegacyCrypto) {
  5 |   // We are on an old version of Node.js that requires legacy crypto utilities.
  6 |   module.exports = require('./utils-legacy')
  7 |   return
    :   ^^^^^^
  8 | }
  9 | 
 10 | const nodeCrypto = require('crypto')
    `----
```

### Expected Behavior

Expect https://www.npmjs.com/package/pg to work

**Comment by shuding** [comment]
This is an issue of that package, not related to Next.js: https://github.com/brianc/node-postgres/issues/2980

**Comment by lucgagan** [comment]
This is hardly true.. It works just fine outside of Next.js.

I also tried using pg-promise and slonik and none of those worked.

**Comment by charmander** [comment]
> This is an issue of that package, not related to Next.js: [brianc/node-postgres#2980](https://github.com/brianc/node-postgres/issues/2980)

As I noted in the linked issue, pg uses CommonJS modules, and top-level return is correct. pg will remove it, but this same bug will affect any other package that makes use of top-level return.

**Comment by gronka** [comment]
> This is an issue of that package, not related to Next.js: [brianc/node-postgres#2980](https://github.com/brianc/node-postgres/issues/2980)

I can't use pg-promise. Can you at least recommend a work-around?
