### ISSUE TITLE
Client component importing server function make the page non-static

### ISSUE THREAD

**Issue by viniciusbitt** [vercel/next.js#50932]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 11 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.7
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/cranky-raman-1xkzns

### To Reproduce

import `ClientComponent` that has `Server Action` inside a page

page.tsx
```
async function getData() {
    console.log("getData called");
}

export default async function Home() {
  await getData()
  return <ClientComponent />
}
```
ClientComponent.tsx
```
"use client";

export default function ClientComponent() {
    return <button onClick={() => {serverAction()}}>Add To Cart</button>;
}
```

serverAction.ts
```
"use server";

export async function action() {
  console.log("server action");
}
```

### Describe the Bug

The `getData` function on the page is called every time the page is reloaded even in `next start`

### Expected Behavior

The `getData` function called once and revalidated only in demand

**Comment by Fredkiss3** [comment]
that's expected as server actions submit to the current route, so it needs to be dynamic and not static.

**Comment by viniciusbitt** [comment]
> that's expected as server actions submit to the current route, so it needs to be dynamic and not static.

so if i go to use `revalidatePath` on the same route, it won't do anything? Because I thought it worked like this: `page getData build time (static)` > `server action and revalidatePath` > `page getData revalidated in background`

and I don't know if what you said is something very obvious, but shouldn't that be in the documentation?

**Comment by Fredkiss3** [comment]
`revalidatePath` do not revalidate in background but "On demand", when you call it the next time you will access the revalidated path, it will refetch your data (or rebuild your page).

From the docs : 

> `revalidatePath` only invalidates the cache when the path is next visited. This means calling revalidatePath with a dynamic route segment will not immediately trigger many revalidations at once. The invalidation only happens when the path is next visited.

link: https://nextjs.org/docs/app/api-reference/functions/revalidatePath

The reason why server actions mark the current page as dynamic is because server actions are compiled as `POST` fetch calls to the same route (you could try to inspect the network to see), if your page is static it can't do that. I was surprised at first, but after giving it little bit of thought it clicked for me and i think it makes sense, maybe they can mention it in the docs but i don't think this is a bug.

However if you want to use On demand revalidation on static pages (in the background), i would advise to not use server actions, but route handlers, you can call `revalidatePath` in them. so instead of calling your function, you make a fetch to your route handler.

**Comment by shuding** [comment]
We are currently working on this fix. Using Server Actions shouldn't convert your page from static to dynamic. The Server Actions handler worker will be built separately if that page is statically optimized.

**Comment by Adevien** [comment]
> We are currently working on this fix. Using Server Actions shouldn't convert your page from static to dynamic. The Server Actions handler worker will be built separately if that page is statically optimized.

Thank god its a bug, i was worried for a second

**Comment by jamesbeck** [comment]
Second this issue 👍, thought I was going mad, would seriously limit the use for the otherwise excellent server actions.

**Comment by Adevien** [comment]
> We are currently working on this fix. Using Server Actions shouldn't convert your page from static to dynamic. The Server Actions handler worker will be built separately if that page is statically optimized.

any updates on this?

**Comment by jamesbeck** [comment]
@nukkerone Thanks for the suggestion but this work around doesn't appear to work. As soon as you pass the server action through to the client component the whole route is forced into becoming dynamically rendered.

@Shuding any progress?

**Comment by Fredkiss3** [comment]
there is the same issue openned here which is prioritised, you may follow it for updates #52840

**Comment by jamesbeck** [comment]
@Fredkiss3 Thank you for drawing my attention to that 👍
