### ISSUE TITLE
After build standalone output, app not working as expected (no css files loaded neither JS functionalities)  

### ISSUE THREAD

**Issue by mustafaskyer** [vercel/next.js#50931]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.4.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.1
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3

warn  - Latest canary version not detected, detected: "13.4.4", newest: "13.4.5-canary.7".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/mustafaskyer/nextjs-standalone

### To Reproduce

create new next app

```shell
npx create-next-app@latest
```

start the app in dev mode
```shell
yarn dev
```

update `next.config.js` with output
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "standalone",
};

module.exports = nextConfig;

```

build the app
```shell
yarn build
```

run the build app from `.next/standalone/server.js`

```shell
NODE_ENV=production node .next/standalone/server.js
```

# Result in DEV

<img width="100%" height="450" src="https://i.ibb.co/p4ZYYFr/dev.png" />

## Result After build
<img width="100%" height="450" src="https://i.ibb.co/DDcTDZW/build.png" />

### Describe the Bug

After build the using standalone output, the build isn't as we expect, no css files loaded and js functionality not working such as routing

### Expected Behavior

expect build dir to be like the dev

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

NODE_ENV=production node .next/standalone/server.js

**Comment by Fredkiss3** [comment]
You need to copy the files from `.next/static` to `standalone/.next/static` and to copy the `public` folder to `standalone/public`. 

From the docs : 

>  This minimal server does not copy the public or .next/static folders by default as these should ideally be handled by a CDN instead, although these folders can be copied to the standalone/public and standalone/.next/static folders manually, after which server.js file will serve these automatically.

link: https://nextjs.org/docs/app/api-reference/next-config-js/output#automatically-copying-traced-files
