### ISSUE TITLE
Docs: Middle Hero section in the Home Page.

### ISSUE THREAD

**Issue by AbhayaShankar** [vercel/next.js#50977]
### What is the improvement or update you wish to see?

The Stack-gap is more and it would be better with smaller stack-gap...

| Prev. Hero Section | New Hero Section (Suggested) |
| -----------        | ----------- |
| ![image](https://github.com/vercel/next.js/assets/113185442/5505d5f3-f99d-4cf0-9f7e-9af76db82ea4)|  
![next js](https://github.com/vercel/next.js/assets/113185442/c28b5b86-49c2-48c3-ac8c-3d1935c4d1d1) |
     

### Is there any context that might help us understand?

Just changed the Stack gap from 32px to 20px.
think it looks a bit better.

**Comment by delbaoliveira** [comment]
Thank you for the suggestion @AbhayaShankar, it comes down to personal preference. I think we're happy with the design right now.
