### ISSUE TITLE
Docs: Move Theme changer to top

### ISSUE THREAD

**Issue by AbhayaShankar** [vercel/next.js#50988]
### What is the improvement or update you wish to see?

Moving the theme changer to the Navbar -->  where it is more accessible. I have been referring to the docs for more than 3 Months now but never did I saw that theme changer component. If it's on the Navbar where it is more accessible, It would be much more feasible for user to use.

## Moving this which is at the bottom to the Top
![image](https://github.com/vercel/next.js/assets/113185442/712d6c91-82e5-4698-a7b7-86a07ed9fda9)

## To here... to the right of Learn button
![image](https://github.com/vercel/next.js/assets/113185442/3f5da24d-b45f-4cae-aefb-494d84b6aa93)

### Is there any context that might help us understand?

More Accessible for users.

**Comment by leerob** [comment]
Thanks for the suggestion, but we are currently planning to keep the switcher in the footer 🙏
