### ISSUE TITLE
[next: 13.4.4] Error: when running build: couldn't be rendered statically because it used searchParams

### ISSUE THREAD

**Issue by kleutons** [vercel/next.js#50999]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Version: ubuntu-latest
    Binaries:
      Node: 18.16.0
      npm: 9.6.6
    Relevant packages:
      next: 13.4.3
      eslint-config-next: 13.4.4
      react: 18.2.9
      react-dom: 18.2.4
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Dynamic imports (next/dynamic), Static HTML Export (output: "export")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/kleutons/next-test

### To Reproduce

This is a simplified code that I made to reproduce the error, it's available on github:
https://github.com/kleutons/next-test

to reproduce, clone the repository, and build.
At the time of: Build with Next.js, the message with the errors appears.

### Describe the Bug

The code works perfectly in the dev environment, but when I run the build on github Pages Aciton, it fails with the following error message...

- Build with Next.js:
Error occurred prerendering page "/user". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Page with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.id`.

### Expected Behavior

Run the compilation without errors,

On the user page, I put the following code:

```
export const dynamic = 'dynamic force';
// 'automatic' | 'dynamic force' | 'error' | 'static force'
```

but it did not work

### How are you deploying your application? (if relevant)

Github Pages Action - nextjs.yml

**Comment by garciawell** [comment]
I'm having the same error.  My ideia is to receive searchParams from url via server and pass along the information to client.
When I build the project and run local, eveything works fine, but in local environment (dev mode) , I've received the error`Dynamic server usage: searchParams.toJSON` after change de URL page

**Comment by shabailiu** [comment]
Getting this also, happens with importing a page that has `'use client'`.

**Comment by rdp-studio** [comment]
same issue @garciawell
is there anyway to fix?

**Comment by jyc5120** [comment]
I have same error in same scenario of using searchParams, are there any solution

**Comment by anuoua** [comment]
Use `useSearchParams` instead, it works.

**Comment by monolithed** [comment]
I have the same problem when I'm building a static assembly. Your error can be fixed by specifying the correct value:

```
export const dynamic = 'force-static' // 'auto' | 'force-dynamic' | 'error' | 'force-static';
```

However, this prevents the ability to access the API - this directory simply isn't created. I have a completely static website that makes a single request to the server (a contact form), and I can't build a static assembly. By default, Next.js builds all pages as SSR, and when I add the magic 'dynamic' variable, it doesn't copy the 'api' directory.

**Output:**

<img width="285" alt="Screenshot 2023-09-12 at 02 15 56" src="https://github.com/vercel/next.js/assets/803674/97e09477-31df-43f0-b4a5-9a320583dd1f">


**Input**

<img width="295" alt="Screenshot 2023-09-12 at 02 16 26" src="https://github.com/vercel/next.js/assets/803674/78d98cc9-9ab1-4747-bb56-c839759030de">

**Comment by monolithed** [comment]
> Use `useSearchParams` instead, it works.

@anuoua, what do you mean? 

<img width="637" alt="Screenshot 2023-09-12 at 02 24 36" src="https://github.com/vercel/next.js/assets/803674/69a16fbe-c236-436a-a719-29a9269c17c7">

**Comment by sethburtonhall** [comment]
I am getting a similar error when adding `output: "export` to my `next.config.js`. `npm run build` is successful but `output: "export"` causes an error when running `npm run dev`.

**Comment by phpepe** [comment]
I have similar issues and only on certain endpoints. 

When adding the `export const dynamic = 'force-static'` it solves the build error but Im receiving nulls.

After hours of debugging, and wondering why other endpoints where able to access searchParams, I realized that only couple of routes are generated statically under out/api/*: The only ones that are being exportied statically only implemented GET handers.
As I want a static export only client pages, I dont need api/* to be exported at all. My final workaround was adding an empty dummy POST handler:

`export async function POST(req: NextRequest) {}`

**Comment by Myks92** [comment]
I also get the same problem when using searchParams on `app/admin/user/users/page.tsx`:

```
'use server'
import React from 'react'
import all, { type Params } from '@/user/query/users/all'
import Filter from '@/user/ui/user/form/filter'
import List from '@/user/ui/user/list'
interface Props {
  searchParams: Params
}
export default async function Page({ searchParams }: Props): Promise<React.JSX.Element> {
  const pagination = await all({ size: 50, ...searchParams })
  return (
    <>
      <Filter/>
      <List items={pagination.items} pagination={pagination.pagination}/>
    </>
  )
}
```

Error message:
```
#23 84.60 Error: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
#23 84.60     at /app/.next/server/chunks/3543.js:1:1639
#23 84.60     at /app/.next/server/chunks/3543.js:1:1656
#23 84.60     at async i (/app/.next/server/app/admin/user/users/page.js:1:6256)
#23 84.60     at async f (/app/.next/server/app/admin/user/users/page.js:1:7440)

```

**Comment by kleutons** [comment]
Hello everyone, I ended up giving up using github pages, I used Vercel and it works perfectly.

**Comment by kleutons** [comment]
Hello everyone, I ended up giving up using github pages, I used Vercel and it works perfectly.

**Comment by Myks92** [comment]
@kleutons I have this problem not only on github, but also on localhost.

**Comment by CharlesStover** [comment]
I got this error for routes when my `page.ts` app router file exported a `Page` that required `'use client';`. I was able to fix it by using:

```
import ComponentWithUseClient from '../../somewhere-else';

export default function Page() {
  return <ComponentWithUseClient />;
}
```
