### ISSUE TITLE
Footer in root layout.tsx displaying even when you override with another layout in particular folder

### ISSUE THREAD

**Issue by urbanobaz** [vercel/next.js#50993]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.15
      pnpm: 8.6.0
    Relevant packages:
      next: 13.1.1
      eslint-config-next: N/A
      react: N/A
      react-dom: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/urbanobaz/portfolioV3

### To Reproduce

/links route displaying a footer when it shouldn't be.

### Describe the Bug

![Screenshot 2023-06-08 at 3 22 22 PM](https://github.com/vercel/next.js/assets/41762856/15045ebc-f7bd-4e62-bb7a-c999558acee4)

**Footer added to the root layout.tsx is not being overwritten by the layout.tsx in the links folder**

![Screenshot 2023-06-08 at 3 23 35 PM](https://github.com/vercel/next.js/assets/41762856/be830afb-ae5f-4006-993d-23e1b6e75ce1)

**footer showing up in /links route even though there's a layout.tsx file in that folder to override the root layout.tsx**

![Screenshot 2023-06-08 at 3 24 47 PM](https://github.com/vercel/next.js/assets/41762856/9cfc6bd0-21a7-4721-9744-632239a4b98e)

### Expected Behavior

expected to not have a footer on the /links route because layout inside of that folder does not have a footer.

**Comment by selven** [comment]
The sub layout.tsx doesn't overwrite the parent one it's nested inside it. See here:
https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts

**Comment by urbanobaz** [comment]
thanks @selven I was able to find a workaround for my issue.
