### ISSUE TITLE
Unexpected error 500 at the `/500` route when deployed to Vercel

### ISSUE THREAD

**Issue by tom-sherman** [vercel/next.js#51037]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.13.2
      Yarn: 1.22.19
      pnpm: 8.2.0
    Relevant packages:
      next: 13.4.5-canary.9
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tom-sherman/next-vercel-500-error-bug

### To Reproduce

Visit the `/500` route on any next.js app router project deployed on Vercel. eg. https://github.com/tom-sherman/next-vercel-500-error-bug

This is also an issue when using basePath. If your basePath is set to `/foo` then `/foo/500` has the same behaviour.

### Describe the Bug

When visiting the `/500` route of my Next.js app deployed on Vercel I get a 500 server error.

### Expected Behavior

It should return 404, or the page if it exists.

### How are you deploying your application? (if relevant)

Vercel

**Comment by ijjk** [comment]
Hi, this is expected see related response/issue here https://github.com/vercel/next.js/issues/37926#issuecomment-1163470678
