### ISSUE TITLE
`not-found.js` does not work within a route group

### ISSUE THREAD

**Issue by viniciusbitt** [vercel/next.js#51075]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.4.5-canary.9
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/youthful-zhukovsky-qpjl36

### To Reproduce

1. Create a route group and create `not-found.js` inside the group.
2. Navigate to any not found page

### Describe the Bug

`not-found.js` file isn't working within a route group.

### Expected Behavior

Reading the documentation I saw that it has no limitation for route group.

**Comment by viniciusbitt** [comment]
Related: [#50034](https://github.com/vercel/next.js/discussions/50034#discussion-5211681)

**Comment by surjithctly** [comment]
I confirm this does not work and created a [Stackblitz Reproduction](https://stackblitz.com/edit/stackblitz-starters-nan4gk?file=app%2F(website)%2Fnot-found.tsx) and found this issue.

**Comment by dbrxnds** [comment]
Running into this same issue now. I think that's on purpose though, the docs state that only the root `not-found` page will render for unmatched routes. Not necessarily the nearest one. Although I think it would make sense for it do so.

**Comment by hughlv** [comment]
I'm running into this issue too. The problem is related to the use of next-intl, to get all pages (including app/page.tsx) localized properly, we have to put everything under app/(locales) route group. And then not-found.tsx itself became NOT FOUND.

Any workround or fixing suggestions are welcome.

**Comment by hughlv** [comment]
> I'm running into this issue too. The problem is related to the use of [next-intl](https://linear.app/vercel/issue/NEXT-intl), to get all pages (including app/page.tsx) localized properly, we have to put everything under app/(locales) route group. And then not-found.tsx itself became NOT FOUND.
> 
> Any workround or fixing suggestions are welcome.

The solution mentioned in #50034 (i.e. adding a [...not-found] route) worked. Saved my day.
