### ISSUE TITLE
Docs: Document crash

### ISSUE THREAD

**Issue by SGDS666** [vercel/next.js#51101]
### What is the improvement or update you wish to see?

Please fix the issue of clicking on the left menu sub item after document translation and crashing

### Is there any context that might help us understand?

When I use Chrome's built-in translation function to view documents, clicking on the menu sub item on the left will cause the page to crash

<img width="1587" alt="image" src="https://github.com/vercel/next.js/assets/86196091/7842c3b9-5f35-4fed-af9b-0dfa84218801">

<img width="2079" alt="image" src="https://github.com/vercel/next.js/assets/86196091/4ce3580e-4b3c-4e00-bf1e-5d1677d8a819">

<sub>[DX-1674](https://linear.app/vercel/issue/DX-1674/docs-document-crash)</sub>

**Comment by delbaoliveira** [comment]
Thank you @SGDS666, I was able to recreate this issue. We'll look into it 👍🏼

**Comment by SGDS666** [comment]
https://github.com/facebook/react/issues/11538

**Comment by leerob** [comment]
This should be fixed 🙏
