### ISSUE TITLE
Redirects stay on `localhost`

### ISSUE THREAD

**Issue by max-programming** [vercel/next.js#51102]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/max-programming/codedamn-profile

### To Reproduce

In the `next.config.js`, add redirects and set `/` to `/profile` or anything else.

### Describe the Bug

I set redirects in a different nextjs app as described above. And now the same thing happens on every other nextjs project **on localhost**. So if I go to `localhost:3000`, it redirects me to `localhost:3000/profile`

### Expected Behavior

The redirects applied to one nextjs app should not affect the other projects.

### Which browser are you using? (if relevant)

Microsoft Edge 115.0.1880.3

**Comment by poteboy** [comment]
I have reproduced this issue on my Mac as well.

**Comment by kasperwelbers** [comment]
I run into the same problem on Chrome in Ubuntu

**Comment by amm834** [comment]
I have got this issue in my macos and chrome when I set the `/` route to the `/en` it's keep redirecting to the /en route even I have been killed server

**Comment by max-programming** [comment]
@kasperwelbers @poteboy @amm834 
Try opening that in an Ingonito/private tab and also try clearing the cache and site data.

That's how I solved it thanks to @delbaoliveira 

https://twitter.com/delba_oliveira/status/1667827537014030336?t=W34_ixeFS-9udFuGLzMO8w&s=19

**Comment by kasperwelbers** [comment]
Thanks for sharing your solution.

But my main concern was not fixing the redirect in my own browser. Rather, I was concerned it might also happen in production. Do we know for sure this only happens on localhost?

**Comment by amm834** [comment]
Thank for your solution.
I have been tried to solve this issue like above before you submit, but it's hitting to the /en route. If we use incognito tab it's working. I know that, but it's not that I excepted to be happen. I am super concern about production env.
