### ISSUE TITLE
Framer Motion Reorder has unexpected behaviour with Next.js

### ISSUE THREAD

**Issue by jai-x** [vercel/next.js#51129]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000
    Binaries:
      Node: 18.6.0
      npm: 8.13.2
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5
      eslint-config-next: 13.4.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/jai-x/framer-reorder-bug

### To Reproduce

1. Clone linked repo
1. `npm install`
1. `npm run dev`
1. Open `localhost:3000` in browser
1. Click link to "Framer Reorder bug"
1. Move card elements around and observe weird behaviour

### Describe the Bug

* [`framer-motion`](https://github.com/framer/motion) is a popular animation and motion library for React
* The [`Reorder`](https://www.framer.com/motion/reorder/) allows for smooth reordering of React elements along a given axis
* Attempting to use `framer-motion` `Reorder` with next.js caused the reordering not to work as expected. 
* The elements often get stuck or unrelated element will move
* This does NOT happen when using a vanilla React project
* This is specific to using `framer-motion` + next.js

https://github.com/vercel/next.js/assets/8362491/0f10b675-adef-4edd-b09b-1c1cf9093dd9

### Expected Behavior

* The card elements should be able to re-ordered smoothly and not get stuck

### Which browser are you using? (if relevant)

Firefox 113.0.1 (64 bit) & Chromium 113.0.5672.126 (Tested broken in both browsers)

### How are you deploying your application? (if relevant)

n/a - dev server

**Comment by jai-x** [comment]
Relevant bug opened library side; https://github.com/framer/motion/issues/2183

**Comment by shuding** [comment]
According to [this](https://github.com/framer/motion/issues/2183#issuecomment-1594238954), it's not related to Next.js as they reproduced with React + Vite and confirmed an older version of Framer Motion works.
