### ISSUE TITLE
Server action doesn't respect cache

### ISSUE THREAD

**Issue by darklight9811** [vercel/next.js#51138]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
npx --no-install next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Sun Jun 11 2023 15:58:21 GMT-0300 (Horário Padrão de Brasília)
    Binaries:
      Node: 16.14.2
      npm: 9.4.2
      Yarn: 1.22.19
      pnpm: 8.3.1
    Relevant packages:
      next: 13.4.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://stackblitz.com/edit/stackblitz-starters-xcinly

### To Reproduce

Create a server action that is consumed on a form and uses a cached function and call it multiple times using a primitive.

### Describe the Bug

The cached function is called everytime.

### Expected Behavior

The cached function to only be called once.

**Comment by shuding** [comment]
Hi! Server Actions are not executed under the React rendering context, you can think of it as a normal async function or an API endpoint. React APIs like cache and hooks won’t work inside.

Instead you can use any server cache mechanism like Map or LRU.
