### ISSUE TITLE
`next build --profile` does not use `react-dom/profiling` 

### ISSUE THREAD

**Issue by promer94** [vercel/next.js#51131]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.5-canary.3
      eslint-config-next: 13.4.5-canary.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/promer94/nextjs-profile.git

### To Reproduce

1. bootstrap the project
```bash
pnpm install
pnpm build
```
2. Navigate to https://localhost:3000
3. Open react-dev-tool, you will find the profile feature is disabled.

### Describe the Bug

`next build --profile` does not use `react-dom/profiling` for production build

### Expected Behavior

`next build --profile` should use `react-dom/profiling` for production build

**Comment by shuding** [comment]
cc @gnoff This could probably be simplified with your PR I think?
