### ISSUE TITLE
404 refresh proble

### ISSUE THREAD

**Issue by mohammad-taheri1** [vercel/next.js#51132]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.14.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5
      eslint-config-next: 13.4.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/mohammad-taheri1/nextjs-tailwind-sandbox

### To Reproduce

you can check it on any Next.js project

### Describe the Bug

Hi.
I'm seeing a bug that exixts on version 13.4.5. Default 404 page is refreshing infinitively and it can be seen on console. also, if you create a custom not-found.js, the problem still exists. 
Only creating a file for catch all with this syntax can solve this problem:

```
[...not-found]
```

### Expected Behavior

not refreshing

### Which browser are you using? (if relevant)

Google chrome

### How are you deploying your application? (if relevant)

npm run dev

**Comment by aiherrera** [comment]
Can confirm this is happening to me as well. Catching 

> ### Verify canary release
> * [x]  I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> ```shell
> Operating System:        
>       Platform: win32        
>       Arch: x64
>       Version: Windows 10 Pro
>     Binaries:
>       Node: 16.14.0
>       npm: N/A
>       Yarn: N/A
>       pnpm: N/A
>     Relevant packages:
>       next: 13.4.5
>       eslint-config-next: 13.4.5
>       react: 18.2.0
>       react-dom: 18.2.0
>       typescript: 5.1.3
> ```
> 
> ### Which area(s) of Next.js are affected? (leave empty if unsure)
> App directory (appDir: true)
> 
> ### Link to the code that reproduces this issue or a replay of the bug
> https://github.com/mohammad-taheri1/nextjs-tailwind-sandbox
> 
> ### To Reproduce
> you can check it on any Next.js project
> 
> ### Describe the Bug
> Hi. I'm seeing a bug that exixts on version 13.4.5. Default 404 page is refreshing infinitively and it can be seen on console. also, if you create a custom not-found.js, the problem still exists. Only creating a file for catch all with this syntax can solve this problem:
> 
> ```
> [...not-found]
> ```
> 
> ### Expected Behavior
> not refreshing
> 
> ### Which browser are you using? (if relevant)
> Google chrome
> 
> ### How are you deploying your application? (if relevant)
> npm run dev

@mohammad-taheri1 I can confirm this is happening to me as well. I also did the same workaround of [...not-found] for the time being.

**Comment by mohammad-taheri1** [comment]
It seems that, when we throw `notFound()`, it works fine. But, when we use other ways like `router.push()` or `Link` component, This error happens.

**Comment by xiwoo** [comment]
The same problem happens to me. If there is no address suitable for directory-based route processing currently supported by next.js, it is moving to not-found.js, and it continues to refresh after moving.
This is becoming an unnecessary and continuous request to the server.

**Comment by dawi** [comment]
Maybe the same issue as #10024.

**Comment by nicolaslima321** [comment]
I'm having this same issue on Next 13.4.6

**Comment by Khoiwall** [comment]
Can you try [...404]

**Comment by Besuf** [comment]
Why hasn't someone been assigned to this issue yet? I can confirm that it is happening to me as well. I'm using the most recent version (13.4.7).

**Comment by Jordaneisenburger** [comment]
I'm probably having the same issue.

```typescript
export const getUserData = cache(async (slug: string) => {
    const data = await prismaFunction(slug)

    if (!data) {
        notFound();
    }

    return data;
});
```
For me the 404 page (root not-found.tsx) just ends up infinitely refreshing itself.

**Comment by lramos33** [comment]
same problem, it reloads the page infinitely

**Comment by nenorrell** [comment]
https://github.com/vercel/next.js/discussions/40000#discussioncomment-6291368

^ A workaround that worked for me
