### ISSUE TITLE
next/link scroll to top not working with external components, scss, passHref and legacyBehavior

### ISSUE THREAD

**Issue by Yaren-IT** [vercel/next.js#51153]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.5-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/goofy-germain-rypqwh

### To Reproduce

1. Browse to the end of the page.
2. Navigate to the other page by header or side navigation.
3. Observe the missing scrolling behavior.

### Describe the Bug

After changing to App Dir, scroll (to top) behavior does not work anymore.
Maybe related to:
- #49255
- #49263
- #49427

### Expected Behavior

With Pages Router the Navigation works and one gets to the top of the page.
After implementing the Navigatoin on the App Router, scrolling behavior isn't working as expected.

**Comment by Yaren-IT** [comment]
I've added an alternative way, with passing the next/link Component into the HeaderMenuItem and SideNavMenuItem, to avoid passHref and legacyBehavior. 
Still same outcome.

**Comment by glundgren93** [comment]
I've been having the same issue.
