### ISSUE TITLE
After replacing app/pages.tsx with pages/index.tsx, the tailwindcss style will become invalid

### ISSUE THREAD

**Issue by imyuanli** [vercel/next.js#51154]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home China
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/priceless-ptolemy-m5pcy8?file=%2Fapp%2Flayout.tsx%3A1%2C1-22%2C1

### To Reproduce

Replace page.tsx under the app and create a new page/index.tsx

### Describe the Bug

TailwindCSS style is invalid

### Expected Behavior

After replacing app/pages. tsx, the rendering style should be normal

**Comment by Fredkiss3** [comment]
You did not import `globals.css` in your index page.

typically you import the CSS either in all the files in your `pages/` directory or you create a file `_app.tsx` where you import the CSS only once. 

more on the docs for `_app.tsx` : https://nextjs.org/docs/pages/building-your-application/routing/custom-app

**Comment by imyuanli** [comment]
> You did not import `globals.css` in your index page.
> 
> typically you import the CSS either in all the files in your `pages/` directory or you create a file `_app.tsx` where you import the CSS only once.
> 
> more on the docs for `_app.tsx` : https://nextjs.org/docs/pages/building-your-application/routing/custom-app

oh, thank you
