### ISSUE TITLE
While importing "@aws-amplify/auth", I get this error in the browser: "Uncaught (in promise) Error: Cannot find module 'fs'"

### ISSUE THREAD

**Issue by GarryOne** [vercel/next.js#51157]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.10.0
      npm: 7.24.0
      Yarn: 1.22.10
      pnpm: 5.18.8
    Relevant packages:
      next: 13.4.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/inspiring-night-yzm4j6

### To Reproduce

Have a Next.js project started with `--turbo`.

1. Import this

```
import { Auth } from "@aws-amplify/auth";
```

2. Call any function from this package. For example:
```
Auth.configure();
```

3. Check browser console:

### Describe the Bug

Having that import of `@aws-amplify/auth`, triggers this error in the browser:

<img width="809" alt="image" src="https://github.com/vercel/next.js/assets/6481499/2b02f876-3c73-48c3-9683-a56efcacca83">

### Expected Behavior

To not get any error.

<sub>[WEB-1613](https://linear.app/vercel/issue/WEB-1613/while-importing-aws-amplifyauth-i-get-this-error-in-the-browser)</sub>

**Comment by joacub** [comment]
how is this going, we have third party modules that sometimes use fs modules and they are not necessary been called but turbopack call them nad dont allow the build

**Comment by GarryOne** [comment]
I think this issue is linked with:
https://github.com/vercel/turbo/issues/2372

**Comment by GarryOne** [comment]
Still occurs with `Node` `v20` and `canary` of `Next.js`

https://codesandbox.io/p/sandbox/nice-tree-qjsm77

**Comment by GarryOne** [comment]
I think this issue also is linked with:

https://github.com/vercel/next.js/issues/56844

**Comment by GarryOne** [comment]
I've updated to latest version of `next` and @aws-amplify/auth` and the error slightly changed:

```
TypeError: Cannot read properties of undefined (reading 'configure')
```

<img width="1512" alt="image" src="https://github.com/vercel/next.js/assets/6481499/699807fd-0087-4f46-83c2-b38b33d8c13d">

**Comment by ForsakenHarmony** [comment]
@GarryOne that error is expected though?
neither the `aws-amplify` nor `@aws-amplify/auth` have an export named `Auth` or `configure`

I think the issue you reported is fixed, can you confirm?

**Comment by GarryOne** [comment]
Yeah. I can confirm it's fixed.

You're right. the import should be like this:

```
import { Amplify } from "aws-amplify";

export default function Home() {
  Amplify.configure({});
  return <>Home</>;
}
```
They've changed that recently.
