### ISSUE TITLE
create-next-app adds tailwindcss in the 'dependencies' array instead of 'devDependencies'

### ISSUE THREAD

**Issue by kamal-choudhary** [vercel/next.js#51161]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.3.0
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.3.0", newest: "13.4.5".
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://www.npmjs.com/package/create-next-app

### To Reproduce

1. run npx create-next-app@latest
2. When it prompts **Would you like to use Tailwind CSS with this project? No / Yes** - Press **Y**
3. After installation, open `package.json` file
4. You'll find `tailwindcss`, `postcss`, `autoprefixer` packages in the **dependencies** array.

### Describe the Bug

Tailwind related packages are added in the **dependencies** array. While Tailwind docs state that it is better if we add those packages in the **devDependencies** array. 

Link to Tailwind docs: [https://tailwindcss.com/docs/installation/using-postcss](https://tailwindcss.com/docs/installation/using-postcss)

### Expected Behavior

Actually, these 3 packages should be in the **devDependencies** in `package.json` file as Tailwind docs explain [here](https://tailwindcss.com/docs/installation/using-postcss).

The terminal command Tailwind docs suggest is:

`npm install -D tailwindcss postcss autoprefixer`

**Comment by icyJoseph** [comment]
I think the problem is that in deploy environments, NODE_ENV is set to `production`, as per npm docs: 

> With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies

https://docs.npmjs.com/cli/v9/commands/npm-install#description and the same applies to yarn, https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production-true-false, so we are in a pickle here.

Because Tailwind and company, wouldn't be installed, and then we wouldn't be able to have styles at all.

**Comment by kamal-choudhary** [comment]
@icyJoseph thank you for the input. 

Can I manually remove those packages from "dependencies" and install them as dev dependencies?

Will it have some consequences?

**Comment by icyJoseph** [comment]
Yes, you can. 

The consequence, would be that if you ever deploy to an environment where `NODE_ENV` is set to `"production"`, it won't install tailwind and company, and AFAIK it won't compile at all.

**Comment by ijjk** [comment]
Hi, this is expected as Next.js now has a `standalone` [output mode](https://nextjs.org/docs/app/api-reference/next-config-js/output) which is more accurate/specific than attempting to install production/dev specific dependencies.

**Comment by regunakyle** [comment]
> Hi, this is expected as Next.js now has a `standalone` [output mode](https://nextjs.org/docs/app/api-reference/next-config-js/output) which is more accurate/specific than attempting to install production/dev specific dependencies. 

Sorry to necro, Next.js newbie here. I have some questions:

1. Do I have to set `output: 'standalone'` manually in `next.config.js` to use this new feature? By default the this is not set.
2. With `output: 'standalone'`, can I put every libraries in _dependencies_ (even for libraries like Jest and Cypress)?
3. Does this work for static sites (i.e. static export)?
