### ISSUE TITLE
getConfig() always return undefined in Next 13

### ISSUE THREAD

**Issue by sergeyzwezdin** [vercel/next.js#51173]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.4
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/sergeyzwezdin/nextjs13-config-issue

### To Reproduce

1. Create new project using CLI
2. Add `publicRuntimeConfig` in `next.config.js`
3. Import `import getConfig from "next/config";`
4. Run `getConfig()`

### Describe the Bug

`getConfig` function returns undefined.

### Expected Behavior

`getConfig` function should return actual config from `next.config.js`.

### Which browser are you using? (if relevant)

Chrome 113.0.5672.126

### How are you deploying your application? (if relevant)

Vercel

**Comment by icyJoseph** [comment]
- https://nextjs.org/docs/app/api-reference/next-config-js/runtime-configuration

> Good to know: This feature is considered legacy and does not work with [Automatic Static Optimization](https://nextjs.org/docs/pages/building-your-application/rendering/automatic-static-optimization), [Output File Tracing](https://nextjs.org/docs/pages/api-reference/next-config-js/output#automatically-copying-traced-files), or [React Server Components](https://nextjs.org/docs/getting-started/react-essentials#server-components). Please use [environment variables](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables) instead to avoid initialization overhead.

**Comment by sergeyzwezdin** [comment]
Interesting. Thank you!

P.S. Would be great to have this notification in runtime so avoid such questions during migration :-)

**Comment by icyJoseph** [comment]
Yes, sorry I had to run, so I just copied it. I agree, an error would be nice.
