### ISSUE TITLE
Why useRouter encode arrays in query?

### ISSUE THREAD

**Issue by MenaiAla** [vercel/next.js#51200]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.2.4", newest: "13.4.6-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

/

## Task
 I want to pass an array as a parameter to the query and display it in this format `roofs=[1,2]` I'm my URL.

## Code

```javascript
router.replace({
					pathname: '/panel_placement',
					query: {
						address_id: '11842008',
						roofs:`[${selectedRoofs.join(',')}]`, //here
						lang,
					},
				});
```

## Current

However, when I pass the array I get an encoded result : 

 `/path?address_id=1235&roofs=%5B1%2C2%5D&lang=en`

## Expected

The format should be like this :

 `/path?address_id=1235&roofs=[1,2]&lang=en`

**Comment by harry-atk** [comment]
You're passing a string here instead of an array so it is encoded as one with encodeURIComponent. You can pass an array but it won't be the url format you want, but router.query will read it as an array

**Comment by icyJoseph** [comment]
Isn't this done by the URLSearchParams API?

You can run this on your browser console:

```js
const q = {tags: '[0,1,2]'}
const search = new URLSearchParams(q)
search.get("tags") // '[0,1,2]'
search.set("foo", "[9,7,8]")
search.get("foo") // '[9,7,8]'
search.toString() // 'tags=%5B0%2C1%2C2%5D&foo=%5B9%2C7%2C8%5D'
```

**Comment by shuding** [comment]
You shouldn't put `[`, `]`, `,` in the query as they're reserved characters: https://www.rfc-editor.org/rfc/rfc3986#section-2.2, the encoded format is correct and expected. This isn't a Next.js behavior but the `URLSearchParams` standard.
