### ISSUE TITLE
Iamge unable to load after static export

### ISSUE THREAD

**Issue by Athrun-Judah** [vercel/next.js#51210]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.3.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Image optimization (next/image, next/legacy/image), Static HTML Export (output: "export")

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/crazy-gwen-rg9cf9?file=%2Fpackage.json%3A13%2C23

### To Reproduce

1. pnpm build.
2. pnpx serve@latest out.

### Describe the Bug

Iamge unable to load after static export, and run `pnpx serve@latest out` or deploy on docker with nginx. When I don't use static export, only use pnpm start, Image load as expected.
![test](https://github.com/vercel/next.js/assets/66123941/5a61fe86-f9af-4e75-82a4-aa5cd7da8748)

### Expected Behavior

Image able to load.

**Comment by electrolyte-orb** [comment]
is that a typo in the Title?

**Comment by electrolyte-orb** [comment]
Please refer to this: [https://nextjs.org/docs/app/building-your-application/deploying/static-exports#image-optimization](https://nextjs.org/docs/app/building-your-application/deploying/static-exports#image-optimization)

Check if this solves your problem?

**Comment by Athrun-Judah** [comment]
> is that a typo in the Title?

yeah, it's a typo. And the problem is solved, thanks. I must add a cutom loaderFile to solve it.
