### ISSUE TITLE
dynamic router jump to txt after static export

### ISSUE THREAD

**Issue by Athrun-Judah** [vercel/next.js#51216]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 3.9.10
```

### Link to the code that reproduces this issue or a replay of the bug

https://nextjs.org/docs/app/building-your-application/deploying/static-exports#deploying

### To Reproduce

1.pnpm build
2.pnpx serve@latest out

### Describe the Bug

After running ```pnpm build```,the dynamically routed files do not generate html files. If the route jumps to a dynamically routed page, it automatically jumps to the txt file.

### Expected Behavior

Normally jump to HTML.

**Comment by babytutu** [comment]
#48022

**Comment by guofei0723** [comment]
same issue.
and When you set basePath in next.config.js, for example "mypath", `<Link href='/'>Home</Link>` will jump to /mypath.txt

**Comment by Afellman** [comment]
same issue

**Comment by femmyte** [comment]
I having this same issue, and I have searched online but couldn't find any solution

**Comment by caleb-barber-medic** [comment]
same issue
