### ISSUE TITLE
app dir setAssetPrefix not work

### ISSUE THREAD

**Issue by xingyibiao** [vercel/next.js#51223]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: 8.5.1
    Relevant packages:
      next: 13.4.6-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/frosty-yalow-phg76g?file=%2Fnext.config.js%3A3%2C27

### To Reproduce

custom server app dir setAssetPrefix not work in my local server. I don't know how to fix it

### Describe the Bug

custom server app dir setAssetPrefix not work
<img width="1032" alt="image" src="https://github.com/vercel/next.js/assets/24382926/c3c3ae47-1d59-474a-b4b1-10da9a2d9237">

### Expected Behavior

all static asset should with custom prefix like: 'https://www.baidu.com/_next/static/chunk/xxx.js'

### Which browser are you using? (if relevant)

Chrome 100.0.4878.0

### How are you deploying your application? (if relevant)

custom server (http)

**Comment by xingyibiao** [comment]
Is anyone following up this issue?

**Comment by xingyibiao** [comment]
Does app router won`t support custom server to setAssetPrefix？

**Comment by nicolaturcato** [comment]
Bringing up this issue. Same happens to me starting from v13.5, it was working perfectly fine on v13.4.7.
SetAssetPrefix stopped working on my custom server.
Can please someone figure out why?

**Comment by xingyibiao** [comment]
I fix it by set dynamic = 'force-dynamic'
```typescript react
// layout.tsx
export const dynamic = 'force-dynamic'
```
the reason is  use file cache by default, so always is next.config.js assetPrefix

**Comment by xingyibiao** [comment]
It just work on v13.4.x
below v13.5

> I fix it by set dynamic = 'force-dynamic'
> 
> ```ts
> // layout.tsx
> export const dynamic = 'force-dynamic'
> ```
> 
> the reason is use file cache by default, so always is next.config.js assetPrefix

It just work on 13.4.1(my version), 13.5.x not work

**Comment by shaunwarman** [comment]
Would a workaround be conditionally setting `assetPrefix` in next.config.js?

```javascript
const assetPrefix = process.env.NODE_ENV === 'production' ? https://mycdn.com : undefined;

/** @type {import('next').NextConfig} */
const nextConfig = {
  assetPrefix,
  ...
};

module.exports = nextConfig;
```
