### ISSUE TITLE
[Edge runtime] - broken behavior for req.clone() on Vercel

### ISSUE THREAD

**Issue by ValentinH** [vercel/next.js#51227]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.26.1
    Relevant packages:
      next: 13.4.6-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/ValentinH/vercel-edge-req-clone-issue

### To Reproduce

```
curl -i --location --request POST 'https://vercel-edge-req-clone-issue.vercel.app/api/test-edge' \
--header 'Content-Type: application/json' \
--data-raw '{
    "test": "yes!"
}'
```

which executes the following code:
```ts
import { NextRequest, NextResponse } from "next/server";

export const config = {
  runtime: 'edge',
  regions: ['fra1'],
};

export default async function handler(req: NextRequest) {
  const payload = await req.clone().json();
  const payload2 = await req.json();

  return NextResponse.json({ payload, payload2 });
}

```

This should return a 200 with:
```
{
  "payload": {
    "test": "yes!"
  },
  "payload2": {
    "test": "yes!"
  }
}
```

### Describe the Bug

The issue is due to the second `req.json()` that crashes on Vercel with:
```
SyntaxError: Unexpected end of JSON input
    at (src/pages/api/test-edge.ts:10:19)
    at (node_modules/next/dist/esm/server/web/adapter.js:144:19)
```

It seems that the `req.clone()` function doesn't work as intended. See https://developer.mozilla.org/en-US/docs/Web/API/Request/clone.
Especially:
> In fact, the main reason clone() exists is to allow multiple uses of body objects (when they are one-use only.)

### Expected Behavior

Cloning the request should allow reading the body again, even on Vercel.

### How are you deploying your application? (if relevant)

Vercel

**Comment by angelhodar** [comment]
I can confirm this happens

**Comment by KingBirdBotw** [comment]
Same problem here, it seems you can not read request twice even using request.clone() on Vercel.

I have chaining middlewares so it is necessary for me to handle request.json() more than once

**Comment by smaeda-ks** [comment]
@ValentinH Thanks for the bug report. We've found the issue on the Vercel side and are currently working on a fix. I will keep you updated. Thanks for your patience!

**Comment by smaeda-ks** [comment]
@ValentinH The fix is now live. Could you please redeploy and test it again? Thanks!

**Comment by ValentinH** [comment]
I confirm that the fix works for me. Thanks guys!
