### ISSUE TITLE
Build Crash on Windows (`TypeError`) for `_isAppDir`

### ISSUE THREAD

**Issue by ovflowd** [vercel/next.js#51225]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Binaries:
  Node: 18.13.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 8.6.0
Relevant packages:
  next: 13.4.5
  eslint-config-next: 13.4.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Operating System (Windows, MacOS, Linux)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/nodejs/nodejs.org/pull/5426

### To Reproduce

The Issue actually happens within GitHub Actions on a Windows Runner. And seems to be fine on Linux and macOS builds. It seems to be related to "app directory" even thought we do not use the "app directory feature"

### Describe the Bug

```
build: TypeError: Cannot read properties of undefined (reading '_isAppDir')
build:     at D:\a\nodejs.org\nodejs.org\node_modules\next\dist\export\index.js:420:39
build:     at Array.filter (<anonymous>)
build:     at D:\a\nodejs.org\nodejs.org\node_modules\next\dist\export\index.js:419:43
build:     at async Span.traceAsyncFn (D:\a\nodejs.org\nodejs.org\node_modules\next\dist\trace\trace.js:103:20)
build:     at async D:\a\nodejs.org\nodejs.org\node_modules\next\dist\build\index.js:1489:21
build:     at async Span.traceAsyncFn (D:\a\nodejs.org\nodejs.org\node_modules\next\dist\trace\trace.js:103:20)
build:     at async D:\a\nodejs.org\nodejs.org\node_modules\next\dist\build\index.js:1345:17
build:     at async Span.traceAsyncFn (D:\a\nodejs.org\nodejs.org\node_modules\next\dist\trace\trace.js:103:20)
build:     at async build (D:\a\nodejs.org\nodejs.org\node_modules\next\dist\build\index.js:145:[29](https://github.com/nodejs/nodejs.org/actions/runs/5253121230/jobs/9490043267?pr=5426#step:7:30))
build: ERROR: command finished with error: command (D:\a\nodejs.org\nodejs.org) npm run build exited (1)
command (D:\a\nodejs.org\nodejs.org) npm run build exited (1)
```

GitHub Action: https://github.com/nodejs/nodejs.org/actions/runs/5253121230/jobs/9490043267?pr=5426

### Expected Behavior

The build should succeed as in the other systems (Linux, macOS).

<sub>[NEXT-1504](https://linear.app/vercel/issue/NEXT-1504/build-crash-on-windows-typeerror-for-isappdir)</sub>

**Comment by ovflowd** [comment]
Hey @styfle sorry for the ping! We're still seeing this in our CI!

I.e.: https://github.com/nodejs/nodejs.org/actions/runs/5806595272/job/15739809537?pr=5617

**Comment by styfle** [comment]
@ovflowd I tried building that repo using Windows 11 and it works fine.

I created PR https://github.com/vercel/next.js/pull/53818 with a potential fix but it would be good to get the steps to reproduce. 

I suspect it might have something to do with this experimental feature so you could try disabling that: https://github.com/nodejs/nodejs.org/blob/25717d37e28243cbfbc5910d80c7c8459026220b/next.config.mjs#L51-L53

**Comment by ovflowd** [comment]
> I suspect it might have something to do with this experimental feature so you could try disabling that: [nodejs/nodejs.org@25717d3/next.config.mjs#L51-L53](https://github.com/nodejs/nodejs.org/blob/25717d37e28243cbfbc5910d80c7c8459026220b/next.config.mjs#L51-L53)

I remember I had to add that due to a momentary bug on Next.js that it was including SWC binaries within the Edge Runtimes, which was causing the runtimes to exceed the max 50mb size... Is that fixed?

**Comment by ovflowd** [comment]
> I created PR https://github.com/vercel/next.js/pull/53818 with a potential fix but it would be good to get the steps to reproduce.

Super appreciate that. @bmuenzenmeyer was also facing this on his Windows 11 machine.

**Comment by bmuenzenmeyer** [comment]
I get this error on the [nodejs](https://github.com/nodejs/nodejs.org) repo, at the tip of current development.

For example, from https://github.com/nodejs/nodejs.org/commit/9a45ee1f21a789f5c238bb32416338b0a883ea05

```
git clone git@github.com:nodejs/nodejs.org.git node-site
cd node-site
nvm use
npm ci
npx turbo deploy
```

**Comment by ovflowd** [comment]
@bmuenzenmeyer can you format your error output on a "markdown code block"?

**Comment by ovflowd** [comment]
FYI @styfle I removed that `experimental` flag, but sadly (https://github.com/nodejs/nodejs.org/pull/5617) is still failing. I assume your PR on Next.js might fix this issue.

**Comment by styfle** [comment]
@ovflowd I tried to reproduce locally but it builds fine for me. Are you table to reproduce the issue locally?

Here's what I tried:

```
git clone https://github.com/nodejs/nodejs.org
cd nodejs.org
git checkout chore/add-static-builds-to-ci
npm ci
npm run build
```

This was commit [d83cfeb](https://github.com/nodejs/nodejs.org/pull/5617/commits/d83cfebc87f76a5a07e14fd3b03b5f22a9657d8d) and I'm seeing a successful build using Windows 11 64bit ARM running in a VM.

**Comment by ovflowd** [comment]
I can try on my Windows machine, but @bmuenzenmeyer is a Windows user and he was able to reproduce. Let me try this now.

**Comment by ovflowd** [comment]
- `npm run build` creates a minimal version of the application to be deployed on Vercel
- `npm run deploy` creates a build with static export (target: `export`)

**Comment by ovflowd** [comment]
I was able to reproduce with:

```
> nodejs.org@1.0.0 scripts:generate-next-data
> cross-env NODE_NO_WARNINGS=1 node scripts/generate-next-data/index.mjs


> nodejs.org@1.0.0 build
> cross-env NODE_NO_WARNINGS=1 next build

- warn You have enabled experimental features (largePageDataBytes, outputFileTracingExcludes) in next.config.mjs.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

- info Creating an optimized production build
- info Compiled successfully
- info Skipping validation of types
- info Skipping linting
- info Collecting page data

> Build error occurred
TypeError: Cannot read properties of undefined (reading '_isAppDir')
    at C:\Users\Claudio Wunder\GitHub\nodejs.org\node_modules\next\dist\export\index.js:422:39
    at Array.filter (<anonymous>)
    at C:\Users\Claudio Wunder\GitHub\nodejs.org\node_modules\next\dist\export\index.js:421:43
    at async Span.traceAsyncFn (C:\Users\Claudio Wunder\GitHub\nodejs.org\node_modules\next\dist\trace\trace.js:103:20)
    at async C:\Users\Claudio Wunder\GitHub\nodejs.org\node_modules\next\dist\build\index.js:1579:21
    at async Span.traceAsyncFn (C:\Users\Claudio Wunder\GitHub\nodejs.org\node_modules\next\dist\trace\trace.js:103:20)
    at async C:\Users\Claudio Wunder\GitHub\nodejs.org\node_modules\next\dist\build\index.js:1435:17
    at async Span.traceAsyncFn (C:\Users\Claudio Wunder\GitHub\nodejs.org\node_modules\next\dist\trace\trace.js:103:20)
    at async build (C:\Users\Claudio Wunder\GitHub\nodejs.org\node_modules\next\dist\build\index.js:146:29)

C:\Users\Claudio Wunder\GitHub\nodejs.org>
```

**Comment by styfle** [comment]
@ovflowd Thanks I can reproduce the issue now.

Looks like the root cause is that `getStaticPaths()` in your app is passing file paths instead of url paths.

https://github.com/nodejs/nodejs.org/blob/8225312fe8d26129e40e222ffed93f92fcfd3c41/pages/%5B...path%5D.tsx#L85

I can see backslashes here but they should be forward slashes.

**Comment by ovflowd** [comment]
> I can see backslashes here but they should be forward slashes.

Hmm, afaik they should be forwarded slashes. Is this happening due to Windows FS using backslashes? Let me play around here and build an URL instead of file path.

**Comment by ovflowd** [comment]
I can ack that using platform-specific separators fixes the issue. https://github.com/nodejs/nodejs.org/pull/5617

Not sure if the bug-fix on Next.js is still needed, but def worth investigating imo.
