### ISSUE TITLE
Docs: Learn page is outdated

### ISSUE THREAD

**Issue by Shubhdeep12** [vercel/next.js#51244]
### What is the improvement or update you wish to see?

Seems like the Learn page is outdated.

![image](https://github.com/vercel/next.js/assets/43654389/92bf33d8-7618-4d36-b6c5-04fe926922bc)

### Is there any context that might help us understand?

Do we need this page?

If yes, then the Search bar and theme are not working here.

![image](https://github.com/vercel/next.js/assets/43654389/0e3c58e1-4bf9-4389-946e-2577c86706ec)
![image](https://github.com/vercel/next.js/assets/43654389/d208ae01-0abc-4cee-92c9-9f1891f5b629)

<sub>[DX-1695](https://linear.app/vercel/issue/DX-1695/docs-learn-page-is-outdated)</sub>

**Comment by balazsorban44** [comment]
Thanks for offering help! The `/learn` page is maintained internally, but your feedback helps us improve it!

I noticed too that the search bar is disabled, so we will track this internally to provide a fix/update.

**Comment by leerob** [comment]
We'll be working on revamping the learn pages in the coming months! Thank you for the suggestion.
