### ISSUE TITLE
Nextjs random ports

### ISSUE THREAD

**Issue by Orygaw** [vercel/next.js#51263]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next info

    Operating System:
      Platform: freebsd
      Arch: x64
      Version: FreeBSD 13.0-RELEASE-p12 #4 9f398ead8: Tue Aug  9 21:57:22 UTC 2022     
    Binaries:
      Node: 18.12.1
      npm: 6.14.8
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 13.4.5
      eslint-config-next: N/A
      react: 18.0.0
      react-dom: 18.0.0
      typescript: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://nextjs.org/docs/pages/building-your-application/configuring/custom-server

### To Reproduce

npx create-next-app@latest
create app.js

const { createServer } = require('http')
const { parse } = require('url')
const next = require('next')
 
const dev = process.env.NODE_ENV !== 'production'
const hostname = 'localhost'
const port = 3000
// when using middleware `hostname` and `port` must be provided below
const app = next({ dev, hostname, port })
const handle = app.getRequestHandler()
 
app.prepare().then(() => {
  createServer(async (req, res) => {
    try {
      // Be sure to pass `true` as the second argument to `url.parse`.
      // This tells it to parse the query portion of the URL.
      const parsedUrl = parse(req.url, true)
      const { pathname, query } = parsedUrl
 
      if (pathname === '/a') {
        await app.render(req, res, '/a', query)
      } else if (pathname === '/b') {
        await app.render(req, res, '/b', query)
      } else {
        await handle(req, res, parsedUrl)
      }
    } catch (err) {
      console.error('Error occurred handling', req.url, err)
      res.statusCode = 500
      res.end('internal server error')
    }
  })
    .once('error', (err) => {
      console.error(err)
      process.exit(1)
    })
    .listen(port, () => {
      console.log(`> Ready on http://${hostname}:${port}`)
    })
})

### Describe the Bug

The hosting service allows me to host Node.js applications but requires me to reserve a port before starting the application. Recently, I have been experiencing problems with new versions of Next.js. It seems that Next.js needs two ports, one of which I can specify for the application (in the example below, it's port 1420), while the other port is randomly assigned (in the example, it's 12035). This prevents me from using Next.js, and I don't see an option to reserve the second port used by Next.js, so I'm reporting it as a bug.

~/domains/mypage.com/public_nodejs>$ node app.js
> Ready on http://localhost:1420/
Invariant: failed to start render worker Error: listen EPERM: operation not permitted 127.0.0.1:12035
    at Server.setupListenHandle [as _listen2] (node:net:1468:21)
    at listenInCluster (node:net:1533:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1682:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
  code: 'EPERM',
  errno: -1,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 12035
}

### Expected Behavior

running nextjs on port 1420

**Comment by PLKplkPLK** [comment]
Same here, log:
```
Ready on http://localhost:10101/
Invariant: failed to start render worker Error: listen EPERM: operation not permitted 0.0.0.0:27089
    at Server.setupListenHandle [as _listen2] (node:net:1446:21)
    at listenInCluster (node:net:1511:12)
    at doListen (node:net:1660:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'EPERM',
  errno: -1,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 27089
}
```
I'm trying to run it on port 10101, but the app tries to use 27089 additionally which I don't have permission to use.

**Comment by avkarenow** [comment]
There are two random ports used by the node process:
1. IPC Server: https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/server-ipc/index.ts#L67
2. Render Server: https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/render-server.ts#L146

I guess the best solution will be to give the possibility of choosing those ports via environment variables (PORT_IPC and PORT_RENDER?)

Now I just hardcoded steady ports in server.listen() to make it work.

**Comment by PLKplkPLK** [comment]
Do you happen to know what might've changed since the day you've replied? Your answear was great, it did work, but today the same thing is happening. Have there been any new random ports added?

**Comment by davidbarratt** [comment]
This seems like the same problem described in https://github.com/vercel/next.js/issues/52702 ?

**Comment by PLKplkPLK** [comment]
@avkarenow I assume those were:
https://github.com/vercel/next.js/blob/26a57af38938625110ea5ca49428cfb871db2508/packages/next/src/server/lib/server-ipc/index.ts#L71C1-L71C1
changed 'addr.port' to some integer port e.g. 4000 and
https://github.com/vercel/next.js/blob/26a57af38938625110ea5ca49428cfb871db2508/packages/next/src/server/lib/render-server.ts#L118C3-L118C3
changed 'addr.port' to some integer port e.g. 4001?
Or did you change something different?

**Comment by fab1an** [comment]
Another problem here is that the processes are listening on all interfaces by default instead of just on localhost.

**Comment by avkarenow** [comment]
@davidbarratt looks the same.
@fab1an or it should use unix sockets instead.

**Comment by PLKplkPLK** [comment]
After many tries I've came to conclusion that the problem might the app-router. When you don't install it (the recommended app router option during install) the problem doesn't occur.

**Comment by fab1an** [comment]
Yes, that is correct, but I have converted my app already to use the router. Too bad the recommended new way of going forward breaks things in such a way.

**Comment by tika** [comment]
Strange issue... it happens in several of my projects. NextJS why!

**Comment by gorskidev** [comment]
@avkarenow how did you hardcoded steady ports? Could you share a bit of code?

**Comment by colonder** [comment]
I'm facing the same issue @avkarenow could you share your code behind fixing those ports?

**Comment by colonder** [comment]
For anyone reading this: this has been resolved with the next Next.js versions, if you upgrade to the newest one, it works with specifying just one port

**Comment by avkarenow** [comment]
A bit of update/testing from my side:
- the last release Next.js v13.4.19 still binding additional ports, but seems to do it another way and I don't need to patch it with static ports but stop working with my Passenger server
- the latest canary version: Next.js 13.4.20-canary.26 seems to not bind additional ports anymore (I guess fixed by #54813) and works without problems with Passenger server and CLI next start.

**Comment by colonder** [comment]
This is again reverted to where it was before with the newest canary https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.35

**Comment by avkarenow** [comment]
Next.js 13.4.20-canary.39 doesn't bind any additional ports and works with Passenger.

**Comment by ijjk** [comment]
Hi, as mentioned above Next.js is running in a single process again in the latest version `v13.4.20-canary.40` so no longer requires IPC ports like previously needed, please update and give it a try!
