### ISSUE TITLE
Docs: mention ESM (ES Modules)

### ISSUE THREAD

**Issue by kasparkallas** [vercel/next.js#51284]
### What is the improvement or update you wish to see?

Searching for "ESM" returns nothing. There used to be more details on how to initialize a new Next.js project with ESM from get-go (the Next.js config). Is this purposely being hidden and driven towards CJS in the new docs?

### Is there any context that might help us understand?

`create-next-app` should also allow to specify that the new project should use ESM.

<sub>[DX-1694](https://linear.app/vercel/issue/DX-1694/docs-mention-esm-es-modules)</sub>

**Comment by balazsorban44** [comment]
Thanks for the feedback! Actually, there's not much you need to do. Next.js supports both ESM and CJS out of the box.

If you put `type: "module"` in your `packages.json`, you can also define files like `next.config.js` as ESM, no special configuration is needed. Third-party modules distributed as CJS, ESM, or both already work, without configuration. If both are present, ESM will be preferred.

If you don't want the whole project to be defined as ESM, you can do so on a per-file basis, via the Node.js convention of using `.mjs` file extensions (eg.: `next.config.mjs`).

For further information, refer to the Node.js documentation: https://nodejs.org/api/packages.html#determining-module-system
