### ISSUE TITLE
Vercel: app reloads when navigating to ‘/‘ 

### ISSUE THREAD

**Issue by esponges** [vercel/next.js#51306]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.6-canary.4
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://fer-toasted.vercel.app/

### To Reproduce

Just navigate to the page and navigate using the navigation links. You'll notice the bug when navigating to `/` only. 

The original repo [is here](https://github.com/esponges/fer-personal-site)

If you want to test locally just copy the `env.example` to `.env` and then `npm i && npm run dev`. Enough to check the navigation. Other fetch request might not work though.

### Describe the Bug

I have this NextJS [app][1] deployed on vercel

I'm using the new `app` directory and make use of the RSC components.

The error presenting in this app is that navigation towards the home route `/` causes the app to reload. 

This doesn't happen when navigating from `/` to the other routes or from any other route to any non `/` route. Eg.

- `/` to -> `/posts` or `/projects` NO RELOAD

- `/projects` to `/posts` NO RELOAD

- any navigation hapenning to `/` CAUSES RELOAD

> This issue is present _only_ in my Vercel deployment, not locally.

I use the `Link` component from `next/link`. 

```

export const NavbarLink = ({
  href,
  // rest of props
  onClick,
}: {
  href: string;
  // rest of types
  onClick?: () => void;
}) => {
  return (
    <Link
      href={href}
      onClick={onClick}
      className={!isMobile && shouldDisplay ? 'ml-6' : 'block'}
    >
      <span
        className={`rounded font-bold md:p-3 font-color-dark--primary ${textColor} ${textSize} ${className} ${!shouldDisplay ? 'hidden' : null}`}
      >
        {children}
      </span>
    </Link>
  );
};
```

and this is `NavbarLink` is used by all of the links in the navbar: `/`, `/posts`, `/projects`.

```
<div className={isMobile ? 'align-center flex justify-center text-center' : ''}>
  <NavbarLink
    href={Routes.home}
    textSize="md:text-4xl text-3xl"
    className={NAV_LINK_HOVER_CLASS}
    shouldDisplay
    isMobile={isMobile}
  >
    FerTostado
  </NavbarLink>
  <NavbarLink
    href={Routes.posts}
    textSize="md:text-xl lg:text-2xl text-lg"
    className={NAV_LINK_HOVER_CLASS}
    shouldDisplay={!isMobile}
  >
    Posts
  </NavbarLink>
  <NavbarLink
    href={Routes.projects}
    textSize="md:text-xl lg:text-2xl text-lg"
    className={NAV_LINK_HOVER_CLASS}
    shouldDisplay={!isMobile}
  >
    Projects
  </NavbarLink>
</div>
```

*things I've tried*

- Using `useRouter.push` instead of `Next` component from `next/link`
- Moving the app directory from `src/app` to `app` (root path)
- Using `Link` component elsewhere than footer and navbar 
- Playing with latest next 13 versions. I'm on `13.3.x`
- Played with the `next.config`.

I noticed a `404` in the base route `/` in the network tab, which might something to do?

[![network tab][2]][2]

If I follow the trace for that `404` in the console I see this

[![stack trace][3]][3]

`next.config.mjs`

```
const config = {
  experimental: {
    appDir: true,
  },
  reactStrictMode: true,
  swcMinify: true,
  i18n: {
    locales: ['en'],
    defaultLocale: 'en',
  },
  webpack(config) {
    config.experiments = {
      ...config.experiments,
      topLevelAwait: true,
    };
    return config;
  },
  // images
};
export default config;
```

This is the [repo url][4] in a case you want to see it all.

  [1]: https://fer-personal-site-test-reload-bug.vercel.app/
  [2]: https://i.stack.imgur.com/PxeRQ.png
  [3]: https://i.stack.imgur.com/l8jIE.png
  [4]: https://github.com/esponges/fer-personal-site

### Expected Behavior

Navigating to `/` without any reload.

### Which browser are you using? (if relevant)

Tried Chrome 114.0.5735.106 and Safari  16.4

### How are you deploying your application? (if relevant)

Vercel

**Comment by JunlinPan-Crypto** [comment]
https://github.com/vercel/next.js/issues/47486

**Comment by esponges** [comment]
> #47486

Thanks, sadly neither downgrading to a version before [v13.2.4-canary.2](https://github.com/vercel/next.js/releases/tag/v13.2.4-canary.2) nor setting the `clientRouterFilter: false` did the work.
