### ISSUE TITLE
Fresh create-next-app: npm run dev: Unexpected token ??=

### ISSUE THREAD

**Issue by Swivelgames** [vercel/next.js#51326]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$ npx --no-install next info
Unexpected token '??='
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Swivelgames/next-js-issue-51326

### To Reproduce

npm run dev

### Describe the Bug

Can't run anything.

### Expected Behavior

Should be able to run things.

### Which browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

**Comment by thanhnt2192** [comment]
I have the same error when I use node version 14
Just update to node version 18.16.0 and it work now

**Comment by ijjk** [comment]
Hi, as noted above it seems you are using an EOL Node.js version which is not supported!

**Comment by Swivelgames** [comment]
Oh yikes! Forgot to switch back to 18. Good call out. Thank you.
