### ISSUE TITLE
RequestExtension in middleware.ts can not pass down

### ISSUE THREAD

**Issue by kin-for-test** [vercel/next.js#51333]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 19.5.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

middleware

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

middleware.ts
```
export function middleware(request) {
  request.language = "en_US";
  return NextResponse.next();
}

```

app/api/route.ts
```
export async function POST(request) {
console.log(request.language)  // undefined
}

```

### Expected Behavior

expected  request.language in app/api/route.ts should be "en_US"

### To Reproduce

middleware.ts
```
export function middleware(request) {
  request.language = "en_US";
  return NextResponse.next();
}

```

app/api/route.ts
```
export async function POST(request) {
console.log(request.language)  // undefined
}

```

**Comment by balazsorban44** [comment]
This is not expected to work. You can set cookies or any other headers, which will be available then.
