### ISSUE TITLE
Docs: Broken links to docs in Learn section

### ISSUE THREAD

**Issue by sm-kc** [vercel/next.js#51363]
### What is the improvement or update you wish to see?

There are broken links to the main docs from the learner docs.

Some pages under `/learn/`, for example https://nextjs.org/learn/basics/data-fetching/two-forms have links to

> `/docs/basic-features/pages#some-anchor`

But that URL now redirects you to

> `/docs/pages/building-your-application/routing/pages-and-layouts#some-anchor`

which doesn't have the anchored section in question. It seems like the structure of the main docs has been changed since the learner docs were put together. In the case of the page above it means that almost all the links in it (which are repeated over and over again) are broken.

### Is there any context that might help us understand?

I'm learning Next and broken links in the tutorial are frustrating.

<sub>[DX-1693](https://linear.app/vercel/issue/DX-1693/docs-broken-links-to-docs-in-learn-section)</sub>

**Comment by balazsorban44** [comment]
That seems correct, thanks, we will look into this!

**Comment by leerob** [comment]
Hey! We are in the process of updating this course entirely. We'll get this patched up.
