### ISSUE TITLE
App Router: next build fails to prerender by trying to fetch data

### ISSUE THREAD

**Issue by jens-ox** [vercel/next.js#51395]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant packages:
      next: 13.4.7-canary.0
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/adoring-bartik-66swjf

### To Reproduce

Run `pnpm build`.

### Describe the Bug

When trying to fetch data in the root layout (or a component imported by it), `next build` will fail due to the build step trying to fetch the data.

Adding a root `loading.tsx` or `global-error.tsx` does not help.

### Expected Behavior

`next build` manages to build.

**Comment by joulev** [comment]
The build error is due to http://localhost:8000 not being available during build. This is not a bug &ndash; you have to configure the backend to be online when you build the app.

**Comment by jens-ox** [comment]
> The build error is due to http://localhost:8000/ not being available during build. This is not a bug – you have to configure the backend to be online when you build the app.

I don't really understand why this is obligatory. There are certainly plenty of valid use-cases where this is not possible - having to have to set up an entire backend in CI for statically prerendering a page that will receive different data at runtime doesn't really make sense imo.

**Comment by joulev** [comment]
> I don't really understand why this is obligatory.

It is *not* obligatory, I literally told you the ways to configure it to only fetch during runtime.

**Comment by jens-ox** [comment]
> It is not obligatory, I literally told you the ways to configure it to only fetch during runtime.

No need to be mean, I wrote my reply before you edited yours - sorry!

> If you want to disable static rendering, opt in to [dynamic rendering](https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering#dynamic-rendering) by [export const dynamic = 'force-dynamic'](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic) or use [no-store](https://nextjs.org/docs/app/api-reference/functions/fetch#optionscache) for the fetch.

Thanks, that works! ☺️
