### ISSUE TITLE
TypeError: router.forward is not a function

### ISSUE THREAD

**Issue by RamazaniMwemedi** [vercel/next.js#51407]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.5
      eslint-config-next: 13.4.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

```jsx           <IconButton               size="medium"               sx={{                 bgcolor: (theme) => theme.palette.action.selected,               }}               onClick={() => router.forward()}             >               <ArrowForwardIosRoundedIcon fontSize="small" />             </IconButton> ```

### To Reproduce

```jsx 
         <IconButton
              size="medium"
              sx={{
                bgcolor: (theme) => theme.palette.action.selected,
              }}
              onClick={() => router.forward()}
            >
              <ArrowForwardIosRoundedIcon fontSize="small" />
            </IconButton>
```

### Describe the Bug

Navigating to a forward page.

### Expected Behavior

Navigate to the forward page

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
It should be there: https://nextjs.org/docs/app/api-reference/functions/use-router#userouter

Make sure you are importing `useRouter` from `"next/navigation"` and not `next/router`

**Comment by RamazaniMwemedi** [comment]
Yes I figured that out but forgot to close the issue
Thanks anyway.
