### ISSUE TITLE
JavaScript Loading issue

### ISSUE THREAD

**Issue by SidhuCodes69** [vercel/next.js#51446]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Hey, I am in stuck in one thing that when i Add these scripts

    <Script strategy="lazyOnload" src="/assets/js/bootstrap.bundle.min.js" />
            <Script strategy="lazyOnload" type="text/javascript" src="/assets/rs-plugin/js/jquery.themepunch.tools.min.js" />
            <Script strategy="lazyOnload" type="text/javascript" src="/assets/rs-plugin/js/jquery.themepunch.revolution.min.js" />
            <Script strategy="lazyOnload" src="/assets/js/jquery.fancybox.min.js" />
            <Script strategy="lazyOnload" src="/assets/js/owl.carousel.js" />
            <Script strategy="lazyOnload" src="/assets/js/script.js" />




In Next.js 13.3.0 it sometimes give me an error that something is not a function or bla bla... even when the page is intially rendred it works fine but when i navigate to other page it don't works i mean thtat the script lost it's state i even tried every single thing like on route change it refresh the scripts but did not work, useEffect but also did not work can someone please help me i  have tried every single thing but nothing worked :( i even check the whole network but did not found i was looking for
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Script optimization (next/script)

### Link to the code that reproduces this issue or a replay of the bug

There is no link for that

### To Reproduce

Hey, I am in stuck in one thing that when i Add these scripts```

    <Script strategy="lazyOnload" src="/assets/js/bootstrap.bundle.min.js" />
            <Script strategy="lazyOnload" type="text/javascript" src="/assets/rs-plugin/js/jquery.themepunch.tools.min.js" />
            <Script strategy="lazyOnload" type="text/javascript" src="/assets/rs-plugin/js/jquery.themepunch.revolution.min.js" />
            <Script strategy="lazyOnload" src="/assets/js/jquery.fancybox.min.js" />
            <Script strategy="lazyOnload" src="/assets/js/owl.carousel.js" />
            <Script strategy="lazyOnload" src="/assets/js/script.js" />

```


In Next.js 13.3.0 it sometimes give me an error that something is not a function or bla bla... even when the page is intially rendred it works fine but when i navigate to other page it don't works i mean thtat the script lost it's state i even tried every single thing like on route change it refresh the scripts but did not work, useEffect but also did not work can someone please help me i  have tried every single thing but nothing worked :( i even check the whole network but did not found i was looking for

### Describe the Bug

Hey, I am in stuck in one thing that when i Add these scripts```


    <Script strategy="lazyOnload" src="/assets/js/bootstrap.bundle.min.js" />
            <Script strategy="lazyOnload" type="text/javascript" src="/assets/rs-plugin/js/jquery.themepunch.tools.min.js" />
            <Script strategy="lazyOnload" type="text/javascript" src="/assets/rs-plugin/js/jquery.themepunch.revolution.min.js" />
            <Script strategy="lazyOnload" src="/assets/js/jquery.fancybox.min.js" />
            <Script strategy="lazyOnload" src="/assets/js/owl.carousel.js" />
            <Script strategy="lazyOnload" src="/assets/js/script.js" />


```

In Next.js 13.3.0 it sometimes give me an error that something is not a function or bla bla... even when the page is intially rendred it works fine but when i navigate to other page it don't works i mean thtat the script lost it's state i even tried every single thing like on route change it refresh the scripts but did not work, useEffect but also did not work can someone please help me i  have tried every single thing but nothing worked :( i even check the whole network but did not found i was looking for

### Expected Behavior

Hey, I am in stuck in one thing that when i Add these scripts```

    <Script strategy="lazyOnload" src="/assets/js/bootstrap.bundle.min.js" />
            <Script strategy="lazyOnload" type="text/javascript" src="/assets/rs-plugin/js/jquery.themepunch.tools.min.js" />
            <Script strategy="lazyOnload" type="text/javascript" src="/assets/rs-plugin/js/jquery.themepunch.revolution.min.js" />
            <Script strategy="lazyOnload" src="/assets/js/jquery.fancybox.min.js" />
            <Script strategy="lazyOnload" src="/assets/js/owl.carousel.js" />
            <Script strategy="lazyOnload" src="/assets/js/script.js" />

```


In Next.js 13.3.0 it sometimes give me an error that something is not a function or bla bla... even when the page is intially rendred it works fine but when i navigate to other page it don't works i mean thtat the script lost it's state i even tried every single thing like on route change it refresh the scripts but did not work, useEffect but also did not work can someone please help me i  have tried every single thing but nothing worked :( i even check the whole network but did not found i was looking for

### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

**Comment by jees47** [comment]
can you re-produce the same issue in codesandbox and send the link?, or any repo link?

**Comment by shuding** [comment]
Closing as there's no reproduction provided for this issue and it's inactive for two months.
