### ISSUE TITLE
13.4.6 useState Initial Value and Initializer function

### ISSUE THREAD

**Issue by SnekCode** [vercel/next.js#51459]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.1
      eslint-config-next: 13.4.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/gallant-lumiere-zj9yx6?file=/pages/index.tsx:12,1

### To Reproduce

I've create a CodeSandbox to document the possible bug, but this is easily reproducible by using `npx create-next-app@canary <name>` then replacing page.tsx with:
```tsx
"use client"
import { useState } from 'react'

export default function Home() {
  "use client"
  const [darkmode] = useState(window.matchMedia('(prefers-color-scheme: dark)').matches)

  return (<h1 className=''> Hello </h1>
  )
}
```

Then run `npm run dev`

### Describe the Bug

code is ran on server side even with "use client" directive resulting in an error being thrown for accessing the window object.

```
- error src/app/page.tsx (7:30) @ window
- error ReferenceError: window is not defined
    at Home (./src/app/page.tsx:13:72)
   5 | export default function Home() {
   6 |   "use client"
>  7 |   const [darkmode] = useState(window.matchMedia('(prefers-color-scheme: dark)').matches)
     |                              ^
   8 | 
   9 |   return (<h1 className=''> Hello </h1>
  10 |   )
```

### Expected Behavior

Expect useState to not be initialized on the server side.

**Comment by shuding** [comment]
First of all, `"use client"` is file-level. This means that it does nothing when you put it inside the function body:

```jsx
export default function Home() {
  "use client" // <- ❌
  ...
```

And secondly, `"use client"` marks the file as a client boundary, but it's will still be server-side rendered and `window` will be undefined. If you have used `pages` directory before, that's the behavior of everything.

The correct way to do it, is to update the state inside a `useEffect` so it will run after hydration on the client.
