### ISSUE TITLE
Docs: The sidebar seems to misinterpret YAML comments within code blocks as Markdown headings

### ISSUE THREAD

**Issue by PinkChampagne17** [vercel/next.js#51468]
### What is the improvement or update you wish to see?

The sidebar should accurately reflect the structure and hierarchy of the documentation, but actually, it misinterprets YAML comments as Markdown headings and show them in the sidebar.

### Is there any context that might help us understand?

![screenshot](https://github.com/vercel/next.js/assets/45930107/590a6676-d5de-4c49-a7a3-a025354f7a83)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions

<sub>[DX-1681](https://linear.app/vercel/issue/DX-1681/docs-the-sidebar-seems-to-misinterpret-yaml-comments-within-code)</sub>

**Comment by delbaoliveira** [comment]
Thank you @PinkChampagne17, a fix for this will be landing shortly.
