### ISSUE TITLE
Font Awesome Fix for Next, Stops Loading Custom SCSS

### ISSUE THREAD

**Issue by jared-leddy** [vercel/next.js#51464]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64
Binaries:
  Node: 16.14.0
  npm: 8.10.0
  Yarn: 1.22.19
  pnpm: 6.11.0
Relevant packages:
  next: 13.4.7-canary.1
  eslint-config-next: 13.3.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.0.4
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/carbondigitalus/min-repro

### To Reproduce

Excluding the ENV variables (that you don't have), run the following:
```
npm install
npm build
npm run start:prod
```

### Bug description

[Solution: Large Font Awesome Icon Issues on Next.js](https://fontawesome.com/docs/web/use-with/react/use-with)

From the problem above, we had large icons and many icons were missing. We added the code below, and our icon problem went away. 
```ts
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
```

Once the icon problem went away, we discovered that our custom SCSS files were not loading. For Next.js, the issue does not happen in dev on localhost. Only when using prod, or the app is deployed on Vercel, does this problem show up. 

### NPM Versions of Font Awesome
```json
{
    "@fortawesome/free-brands-svg-icons": "^6.4.0",
    "@fortawesome/free-solid-svg-icons": "^6.4.0",
    "@fortawesome/react-fontawesome": "^0.2.0",
}
```

### Browser and Operating System

- Google Chrome
Version 114.0.5735.133
- iMac computer
OS Ventura 13.4

### Expected Behavior

Run the following. Icons are present and CSS loads correctly. 
```
npm install
npm run start:dev
```

### Which browser are you using? (if relevant)

Google Chrome Version 114.0.5735.133

### How are you deploying your application? (if relevant)

Vercel

**Comment by shehi** [comment]
Are you using FA as SVG or fonts?

**Comment by jared-leddy** [comment]
I'm using this method from the FA website.
<img width="505" alt="image" src="https://github.com/vercel/next.js/assets/57743183/f4b128e4-1a6d-47dd-930c-d6c0afb01a98">

**Comment by shehi** [comment]
> I'm using this method from the FA website. <img alt="image" width="505" src="https://user-images.githubusercontent.com/57743183/246910090-f4b128e4-1a6d-47dd-930c-d6c0afb01a98.png">

Yea, that's SVG. 
Add this to your package.json as well: 
```
"@fortawesome/fontawesome-svg-core": "^6.4.0",
```

Include this in your main styles pipeline, from `@fontawesome/fontawesome-svg-core`:
```
@import '~@fortawesome/fontawesome-svg-core/styles.css';
```

It should work. Don't have to do that `config.autoAddCss()` part. At least I don't have it.

**Comment by jared-leddy** [comment]
> Yea, that's SVG...

Installed the NPM package. Removed the config. Ran build and start prod scripts. Problem still present.

**Comment by jared-leddy** [comment]
Still trying to resolve this issue.

**Comment by webilum** [comment]
I'm having the same issue. Icons are fine on dev, but on vercel they're much bigger and the `size` parameter is not applied

**Comment by Rajeshchalasani9** [comment]
Any solution?  Still having the same issue in recent installation.

**Comment by jared-leddy** [comment]
To be honest, I don't exactly remember. Reviewing the min repro repo, this is what is different that I can tell. I believe this is what fixed the icons, but the rest of our styles have issues. My best guess is that it's a breakdown between class and functional components. 

Remove the code here:
https://github.com/carbondigitalus/min-repro/blob/main/src/pages/_app.tsx#L2
https://github.com/carbondigitalus/min-repro/blob/main/src/pages/_app.tsx#L12-L13

**Comment by Rajeshchalasani9** [comment]
> To be honest, I don't exactly remember. Reviewing the min repro repo, this is what is different that I can tell. I believe this is what fixed the icons, but the rest of our styles have issues. My best guess is that it's a breakdown between class and functional components.
> 
> Remove the code here: https://github.com/carbondigitalus/min-repro/blob/main/src/pages/_app.tsx#L2 https://github.com/carbondigitalus/min-repro/blob/main/src/pages/_app.tsx#L12-L13

I have moved `import "@fortawesome/fontawesome-svg-core/styles.css";` 
from _app.js  to globals.scss like below 

```
@import "../scss/thin.scss";
@import "../scss/light.scss";

@import "@fortawesome/fontawesome-svg-core/styles.css";
```
in your case it might be style.scss.
