### ISSUE TITLE
Docs: Translate to other language

### ISSUE THREAD

**Issue by ChanghyeonYoon** [vercel/next.js#51536]
### What is the improvement or update you wish to see?

Hi there. I am a front-end developer using Next.js in Korea. I would like to work on translating Next.js Korean documentation for Koreans. React documentation is translated into multiple languages, but Next.js is still only available in English, which is inconvenient.

If possible, I would like to take the lead in translating the Korean documentation. As an open source, I plan to work with various Koreans on the translation.

Please confirm.

### Is there any context that might help us understand?

I also participated in the Korean translation of the React docs, and I think it would be great to do it the way they did it: 

https://github.com/reactjs/ko.react.dev

**Comment by ChanghyeonYoon** [comment]
@ijjk

**Comment by juniorforlife** [comment]
if approved I can help with translating to Vietnamese as well

**Comment by balazsorban44** [comment]
Thanks, I've passed this feedback to our docs team!

@ChanghyeonYoon please refrain from tagging core maintainers for reach in the future, thank you! 🙏
