### ISSUE TITLE
SVG Path Jsx working on Server, but not in "use client" - showing Error - Module parse failed, need  loader to handle

### ISSUE THREAD

**Issue by Belivup** [vercel/next.js#51568]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64
    Binaries:
      Node: 20.0.0
      npm: 9.6.4
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Belivup/svg-error

### To Reproduce

Icon.js
```
import { getData } from './iconFetch'

export default async function Icon({ name, className, color }) {

    const types = ['brand', 'reg', 'solid', 'light', 'thin'];
    const lastPart = name.split('_').pop();

    const iconData = types.find(type => type === lastPart) ? await getData(name, lastPart) : null

    if (!iconData) {
        const empty = require(`./svg/svgError`).Empty
        return empty(className)
    }

    const [width, height, empty, unicode, path] = iconData

    return (
        <svg className={`svg-icon ${className}`} xmlns="http://www.w3.org/2000/svg"
            viewBox={`0 0 ${width} ${height}`}
            fill={color}
            role="img">
            <path d={path} />
        </svg>
    )
}

```

Page.js

```
'use client' -- // Without 'use client' , working Perfectly.

import Icon from "iconview"

export default function Home() {
  return (
    <main>
   
      <Icon name="facebook_brand" />

    </main>
  )
}
```

### Describe the Bug

SVG Icon Path JSX Working as Server Components</h3>
      <h3>If i "use client", then Showing <code> <br/> <br/>
          Module parse failed: Unexpected token (18:8) <br/>
          You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
      </code> </h3>

### Expected Behavior

./node_modules/iconview/Icon.js

```
Module parse failed: Unexpected token (18:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|     return (
>         <svg className={`svg-icon ${className}`} xmlns="http://www.w3.org/2000/svg"
|             viewBox={`0 0 ${width} ${height}`}
|             fill={color}
```
This error occurred during the build process and can only be dismissed by fixing the error.

### Which browser are you using? (if relevant)

Any

### How are you deploying your application? (if relevant)

LocalHost

**Comment by igordanchenko** [comment]
> Unsupported Pattern: Importing Server Components into Client Components

https://nextjs.org/docs/getting-started/react-essentials#unsupported-pattern-importing-server-components-into-client-components

**Comment by Belivup** [comment]
> > Unsupported Pattern: Importing Server Components into Client Components
> 
> https://nextjs.org/docs/getting-started/react-essentials#unsupported-pattern-importing-server-components-into-client-components

But how can i implement this here? can can i pass jsx with data?

**Comment by igordanchenko** [comment]
The recommended pattern is described right there in the documentation.

For example, you can refactor your code as follows.

```js
// page.js

import Icon from "iconview"
import MainComponent from "MainComponent"

export default function Home() {
  return (
    <MainComponent icon={<Icon name="facebook_brand" />} />
  )
}
```

```js
// MainComponent.js

"use client"

export default function MainComponent({ icon }) {
  return <main>{icon}</main>
}

```

**Comment by Belivup** [comment]
i'd like to use icon like this,   `<Icon name="facebook_brand" />`
can you please give me full code?
i'm sorry for asking but i really do not understanding how to implement it.
i really apprecaite your help, and looking forward.

here is my all file.

Icon.js
```
import { getData } from './iconFetch'

export default async function Icon({ name, className, color }) {

    const types = ['brand', 'reg', 'solid', 'light', 'thin'];
    const lastPart = name.split('_').pop();

    const iconData = types.find(type => type === lastPart) ? await getData(name, lastPart) : null

    if (!iconData) {
        const empty = require(`./svg/svgError`).Empty
        return empty(className)
    }

    const [width, height, empty, unicode, path] = iconData

    return (
        <svg className={`svg-icon ${className}`} xmlns="http://www.w3.org/2000/svg"
            viewBox={`0 0 ${width} ${height}`}
            fill={color}
            role="img">
            <path d={path} />
        </svg>
    )
}

```

iconFetch.js
```
export async function getData(name, type) {

    const license = process.env.ICONVIEW || '509000'
    const url = `https://api.iconview.org/icons?name=${name}&type=${type}`

    try {
        const res = await fetch(url, {
            next: { revalidate: true },
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': license
            }
        });

        if (!res.ok) {
            return null
        }

        return await res.json()

    } catch (error) {
        return null
    }
```

**Comment by Belivup** [comment]
Even This One Also Error - Module parse failed: Unexpected token (2:11)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

```
export function Facebook_Fab ({className, color, size, onClick}) {
    return <svg 
        className={`svg-icon ${className}`} 
        onClick={onClick}
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 512 512"
        fill={color}
        fontSize={size}
        role="img">
        <path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z"/>
    </svg>
}
```
    
    
```
'use client'

import {Facebook_Fab} from "iconview/svg/fab/Facebook";

export default function Nav(){

    return(
        <>
            <h1>Nav</h1>
            <Facebook_Fab />

        </>
    )
}
```

**Comment by igordanchenko** [comment]
> Even This One Also Error - Module parse failed: Unexpected token (2:11)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

This is absolutely unrelated to Next.js. The `iconview` package that you published on npm isn't valid. You published your package as CommonJS, but all your js files are in ESM format.

**Comment by Belivup** [comment]
> > Even This One Also Error - Module parse failed: Unexpected token (2:11)
> > You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> 
> This is absolutely unrelated to Next.js. The `iconview` package that you published on npm isn't valid. You published your package as CommonJS, but all your js files are in ESM format.

This is Fixed by adding The Webpack Config.

```
const nextConfig = {

    // Your Others Config

    webpack: (config, { defaultLoaders }) => {
        config.module.rules.push({
            test: /\.+(js|jsx)$/,
            include: /node_modules[\\/]iconview/,
            use: defaultLoaders.babel,
        });
        return config;
    },
};

module.exports = nextConfig;

```

**Comment by shuding** [comment]
It looks like your component is from node_modules: `./node_modules/iconview/Icon.js`, and it has JSX. By default, all packages inside node_modules should be valid code for Node.js to run (JSX isn't). You can use the [transpilePackages](https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages) option to make sure it's transpiled.
