### ISSUE TITLE
Next 13.4: Error: connect ETIMEDOUT ::1:50720     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) 

### ISSUE THREAD

**Issue by broksonic21** [vercel/next.js#51560]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.7.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.1
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app -e reproduction-template --- no change needed

### To Reproduce

We can reproduce this in our environment, but also directly against  [npx create-next-app -e reproduction-template](https://github.com/vercel/next.js/tree/canary/examples/reproduction-template) --- no change needed to see this. Happens after 5000 or 6000 every time.

```
npm run build
npm start
```

Then in a new window:

```
ab -n 10000 -c 100 http://127.0.0.1:3000/
```

### Describe the Bug

In Next 13.3 - we can run 

```
ab -n 10000 -c 100 http://127.0.0.1:3000/
```

to completion without error

But on 13.4 (including in canary), we get :

```
~ ab -n 10000 -c 100 http://127.0.0.1:3000/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
apr_socket_recv: Operation timed out (60)
Total of 6455 requests completed
```

As well as this from the server - it never recovers once in this state.

```
> next start

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
Error: connect ETIMEDOUT 127.0.0.1:57665
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 57665
}
Error: connect ETIMEDOUT 127.0.0.1:57665
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 57665
}
```

The error then repeats forever until you kill the server.

### Expected Behavior

Next 13.4 (or canary) runs same as 13.3 - you can run multiple calls vs it without crash

### Which browser are you using? (if relevant)

ab

### How are you deploying your application? (if relevant)

next start (seen in production docker as well as local setup)

**Comment by broksonic21** [comment]
This does _not repro_ when using:

```
  experimental: {
    appDir: false 
    // https://nextjs.org/docs/messages/experimental-app-dir-config
    // this also controls running workers https://github.com/vercel/next.js/issues/45508#issuecomment-1597087133, which is causing
    // memory issues in 13.4.4 so until that's fixed, we don't want this.
  },
```

I can run forever in this mode.

**Comment by mauron85** [comment]
for me it happens even for very first request in 13.4

**Comment by mircostraessle** [comment]
We were able to fix this issue on our system thanks to this comment https://github.com/vercel/next.js/issues/49929#issuecomment-1631206457 which mentioned, that the new Next.js Setup now uses multiple processes to work.
That got us thinking and we found out, that on our company infrastructure there was a global http proxy configured and because there was no exception in the proxy configuration for localhost the communication between these Next.js processes was routed through the proxy which obviously didn't work and caused the timeout errors.

**Comment by broksonic21** [comment]
It seems better recently, but still crashes on:

```
ab -n 100000 -c 100 http://127.0.0.1:3000/
```

And the memory grows but is _never_ relinquished. I still have:

<img width="788" alt="image" src="https://github.com/vercel/next.js/assets/24306571/7fe0def0-7f0c-4677-a150-72dcb483e4c7">

After a crash:
<img width="586" alt="image" src="https://github.com/vercel/next.js/assets/24306571/967fa66a-7833-4ad8-81b3-c9f352b52a53">
