### ISSUE TITLE
Docs: Environment Variables Not Working Client-Side in Docker

### ISSUE THREAD

**Issue by DaakyeHeneEmma** [vercel/next.js#51575]
### What is the improvement or update you wish to see?

The containerizing environment with NextJS_12 pages and trying to get an environment variable recognized client-side but gets undefined even when prefixed with the NEXT_PUBLIC, it works on other environments like development as stated in the docks but not in docker containerization. I can't see or find any docs for this if the team can work on that.

### Is there any context that might help us understand?

showing and demonstrating working code examples will help

**Comment by dorukerenaktas** [comment]
As documentation states env variables that stars with `NEXT_PUBLIC_` are bundled at build time. You can not change value after build. Checkout documentation for more information [Bundling Environment Variables for the Browser](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser).

> Note: After being built, your app will no longer respond to changes to these environment variables. For instance, if you use a Heroku pipeline to promote slugs built in one environment to another environment, or if you build and deploy a single Docker image to multiple environments, all NEXT_PUBLIC_ variables will be frozen with the value evaluated at build time, so these values need to be set appropriately when the project is built. If you need access to runtime environment values, you'll have to setup your own API to provide them to the client (either on demand or during initialization).

**Comment by AlmazHecker** [comment]
> As documentation states env variables that stars with `NEXT_PUBLIC_` are bundled at build time. You can not change value after build. Checkout documentation for more information [Bundling Environment Variables for the Browser](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser).
> 
> > Note: After being built, your app will no longer respond to changes to these environment variables. For instance, if you use a Heroku pipeline to promote slugs built in one environment to another environment, or if you build and deploy a single Docker image to multiple environments, all NEXT_PUBLIC_ variables will be frozen with the value evaluated at build time, so these values need to be set appropriately when the project is built. If you need access to runtime environment values, you'll have to setup your own API to provide them to the client (either on demand or during initialization).

how can I set env variables at runtime ?

**Comment by brycehanscomb** [comment]
> how can I set env variables at runtime ?

You have a few options, some of which are listed here:

https://www.saltycrane.com/blog/2021/04/buildtime-vs-runtime-environment-variables-nextjs-docker/

**Comment by balazsorban44** [comment]
Hi, using environment variables from Docker is not different from other deployment methods. Check out https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

You can also check out https://github.com/vercel/next.js/tree/canary/examples/with-docker on how to set up Docker.

If you think there is a bug, please open a bug report with an attached reproduction, thanks! :pray:
