### ISSUE TITLE
[NEXT-1300] Docs: 

### ISSUE THREAD

**Issue by yuanyuanzi718** [vercel/next.js#51596]
### What is the improvement or update you wish to see?

I am a Chinese developer. After translating into Chinese, I click on the next chapter to report an error. Then, I need to refresh and click on the next chapter, and then click on the Chinese translation

### Is there any context that might help us understand?

![](https://uploads.linear.app/099ed59a-06c6-472f-9977-4798721bda90/69ca0f3c-21ea-4dd2-9fee-dee739b996f7/9ca3096d-cd19-4415-bc4d-725ca71e5760)

### Does the docs page already exist? Please link to it.

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [NEXT-1300](https://linear.app/vercel/issue/NEXT-1300/docs)</sub>

**Comment by balazsorban44** [comment]
Hi, are you using something like Google Translate? Could you explain the reproduction steps in detail, and which page exactly you saw this error on?

**Comment by delbaoliveira** [comment]
Thanks for reporting this @yuanyuanzi718! 

I was able to reproduce it - it's the same issue as: https://github.com/vercel/next.js/issues/51101

We believe it may have to do with: https://github.com/facebook/react/issues/11538
But I'm not sure yet, it could also be something in our code.
