### ISSUE TITLE
Docs: If possible, could you please make the diagram public?

### ISSUE THREAD

**Issue by r-kozu** [vercel/next.js#51601]
### What is the improvement or update you wish to see?

Thank you for the wonderful react full-stack framework and documentation.

If possible, could you please make the diagram public?
I can give the community a document that I have translated into Japanese.

### Is there any context that might help us understand?

I am Japanese and work for a Japanese software company and trying to get everyone to use Nextjs in our company.
So I'm trying to translate yours wonderful App router ver documentation into Japanese, but I found that I [can't use the diagrams](https://nextjs.org/docs/community/contribution-guide#diagrams).

**Comment by balazsorban44** [comment]
Thanks for the feedback, forwarded it to the docs team.

**Comment by delbaoliveira** [comment]
Hey @r-kozu, please DM me on https://twitter.com/delba_oliveira :pray:

**Comment by r-kozu** [comment]
> Hey @r-kozu, please DM me on https://twitter.com/delba_oliveira 🙏

Thank you for your response.
I menshoned you because I can't DM you due to twitter's specs.

**Comment by delbaoliveira** [comment]
@r-kozu, I need your email address to share the figma file. Either add it here and delete the comment after I share it, or find another way to message me privately.

**Comment by r-kozu** [comment]
> @r-kozu, I need your email address to share the figma file. Either add it here and delete the comment after I share it, or find another way to message me privately.

I see. 
This is my email address.
ejn.guppy@gmail.com

**Comment by delbaoliveira** [comment]
Sent an invite 👍🏼

**Comment by r-kozu** [comment]
> @r-kozu Sent an invite 👍🏼

Thank you very much. I confirmed that I could reference it and deleted the email address👍
