### ISSUE TITLE
Next Dev is full reloading frequently  

### ISSUE THREAD

**Issue by mirsahebali** [vercel/next.js#51609]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Using WSL2 with Debian.
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jun 2 00:45:15 UTC 2023
    Binaries:
      Node: 20.3.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.2
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```
https://github.com/vercel/next.js/assets/104109868/15f177b8-bb86-4edc-8534-976f623d97f9

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps), Routing (next/router, next/navigation, next/link), Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app project_name --src-dir --app 

### To Reproduce

Install a with `npx create-next-app project_name --src-dir --app `
 
cd `project_name`

`npx next dev ` or `npm run dev`

Edit the app directory with some components and layouts

### Describe the Bug

It starts it automatically. 
The next dev starts making like a 69 requests in 1700ms smth and again and then I get a full reload every second without doing anything. Using `--turbo` didn't help as it the process got terminated every 1-2 minutes.

I checked the  docs and github issues section and couldn't find any helpful solutions.

It also persists even after rolling back the updates to stable versions.

### Expected Behavior

Simple `next dev` environment with instant change to reflected when changes were made to small elements such as a div or Link etc.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by padmaia** [comment]
Are you still seeing this issue with v13.5+?

**Comment by mirsahebali** [comment]
No, it has been resolved. Thank you guys.
