### ISSUE TITLE
Page router components cannot import SWR that imported from other packages when App Router components exist

### ISSUE THREAD

**Issue by kaorun343** [vercel/next.js#51638]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
% yarn next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 3.6.0
      pnpm: 7.25.0
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/kaorun343/next-app-swr-monorepo

### To Reproduce

1. Run `yarn dev`
2. Open http://localhost:3000/ , then it works well (SWR is imported as expected).
3. Open http://localhost:3000/about , then Next.js throws `TypeError: swr__WEBPACK_IMPORTED_MODULE_0__ is not a function` .
4. Stop `yarn dev` command and remove `app` directory, and run `yarn dev` again.
5. Open http://localhost:3000/about , then it works well (SWR is imported as expected).

### Describe the Bug

I prepared two pages, the one is`/` page, which is app router, and the other one is `/about` page, which is page router.

I mentioned this bug when I tried to use app router that page router pages exists. Until adding app router pages, the Next.js application was able to import SWR without any errors. However, after I made app router page, the existing page router causes such errors.

The most important point of this bug is that this issue is only happens when the package that Next.js imports from page router imports SWR.

```
// Correct
Next.js (page router) -> SWR

// Incorrect
Next.js (page router) -> shared package -> SWR
```

### Expected Behavior

Whether app router pages exists or not, SWR should be imported from page router pages without any errors.

**Comment by sannajammeh** [comment]
Which version of SWR are you using? They've just shipped some RSC bundle fixes.

**Comment by kaorun343** [comment]
The version of SWR is 2.1.5. 

Thanks.

**Comment by kaorun343** [comment]
I tried v2.2.0 but this issue still exists.

**Comment by kaorun343** [comment]
I stopped using SWR with App Router and Pages Router simultaneously.
