### ISSUE TITLE
No "out" folder generated when doing static export

### ISSUE THREAD

**Issue by ishaanjain** [vercel/next.js#51664]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Static HTML Export (output: "export")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/ishaanjain/reproduction-app

### To Reproduce

Clone the repo and run `npm run build`

### Describe the Bug

The docs state that given `const nextConfig = { output: 'export', }` inside `next.config.js`:

After running `next build`, Next.js will produce an `out` folder which contains the HTML/CSS/JS assets for your application.

But no `out` folder is created, and there is no `index.html` to be found.

### Expected Behavior

I expect `npm run build` to generate the static assets of the application in an `out` folder. Like an `index.html` at least, something that can be served statically.

**Comment by christianMiguez** [comment]
Isn't npm run export?

**Comment by wwwdepot** [comment]
You create the config variable but didn't export it.

**Comment by ishaanjain** [comment]
Ah, that was it. Thanks!
