### ISSUE TITLE
Docs: nextjs.org site has hamburger menu bug

### ISSUE THREAD

**Issue by juniorforlife** [vercel/next.js#51683]
### What is the improvement or update you wish to see?

The side menu gets hidden once it passes 890px in screen width. However the hamburger menu icon is still shown

### Is there any context that might help us understand?

![bug](https://github.com/vercel/next.js/assets/68360917/a60b0e13-18c2-42ec-ba14-e05ee1853525)

**Comment by quaintrelle7** [comment]
Hi!
I would like to take up this issue.

**Comment by delbaoliveira** [comment]
Thank you for reporting this @juniorforlife! I've forwarded it to our engineering team to take a look at. 

@quaintrelle7, the code for Next.js site is private, so I'm sorry we're unable to assign it. Thank you for the offer though ❤️
