### ISSUE TITLE
Parallel Routes with catchAll routes NOT work as expected

### ISSUE THREAD

**Issue by youweol-master** [vercel/next.js#51705]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Sat Aug 27 02:44:20 EDT 2022
    Binaries:
      Node: 16.19.1
      npm: 8.9.0
      Yarn: 1.22.19
      pnpm: 7.26.3
    Relevant packages:
      next: 13.4.8-canary.1
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/github/youweol-master/next-catchAllExample/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj8k76to000b2e6hzzopdfuh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj8k76to000d2e6hx1t43fj2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clj8k76to000b2e6hzzopdfuh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clj8k76to000a2e6hoks1qtyu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clj8k76to000b2e6hzzopdfuh%2522%252C%2522activeTabId%2522%253A%2522clj8k76to000a2e6hoks1qtyu%2522%257D%252C%2522clj8k76to000d2e6hx1t43fj2%2522%253A%257B%2522id%2522%253A%2522clj8k76to000d2e6hx1t43fj2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clj8k7lub009o2e6h1xiwphe0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clj8k7r7200ep2e6hh2r5ac8j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fhello%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clj8k7r7200ep2e6hh2r5ac8j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### To Reproduce

always Reproduce.

hint: the codesandbox URL is very long, here is  [the example repo](https://github.com/youweol-master/next-catchAllExample)

### Describe the Bug

when visit url /hello or /hello/sd, the @slot always render content in default.tsx, NOT [...catchAll]/page.tsx

### Expected Behavior

render content in [...catchAll]/page.tsx

**Comment by avkvak** [comment]
Experiencing the same issue

**Comment by doiali** [comment]
same here.  
always `@slot/page.tsx` or `@slot/default.tsx` is rendered in the slot, But never `@slot/[...catchAll]/page.tsx`

**Comment by youweol-master** [comment]
see #49531
