### ISSUE TITLE
turbopack-with-nextauth-middleware

### ISSUE THREAD

**Issue by roysabenecio** [vercel/next.js#51704]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000
Binaries:
      Node: 18.15.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: 8.6.2
Relevant packages:
      next: 13.4.8-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/io-sono-roy/turbopack-with-nextauth-middleware

### To Reproduce

1.  Login if not logged in, just sign in without credentials
2. Go to dashboard if not redirected
3. Go to sample page or dashboard

### Describe the Bug

It does not navigate to other pages when in an export default with nextauth/middleware is declared in middleware.ts. This works fine with normal run dev. Also, GET /sample is continuously fetching in the terminal (or other, depends on page). It also displays this when stopped:
Caused by:
- router evaluation failed: received error from javascript stream
- failed to receive message
- reading packet length
- unexpected end of file

Debug info:
- Execution of get_from_source failed
- Execution of resolve_source_request failed
- Execution of NextRouterContentSource::get failed
- error during Next.js routing for /dashboard?_rsc=111bfb2
- router evaluation failed: received error from javascript stream
- failed to receive message
- reading packet length
- unexpected end of file
 

### Expected Behavior

I expected to switch from dashboard to sample page or vice versa when logged in using next auth middleware

### Which browser are you using? (if relevant)

Version 114.0.5735.133 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### How are you deploying your application? (if relevant)

run dev --turbo

<sub>[WEB-1611](https://linear.app/vercel/issue/WEB-1611/turbopack-with-nextauth-middleware)</sub>

**Comment by io-sono-roy** [comment]
This is my first ever issue. I also read the guideline, but I still don't know if I did it correctly, so please correct me if there is something wrong with my report. 
I also don't know if this is really turbopack, next auth or middleware.

**Comment by ridays2001** [comment]
I am getting this issue too. Latest stable Next.js version. I have set up `getServerSideProps` and the session value is null when using turbopack. If I use the default compiler, I get the proper session value. Using turbopack here causes the page to reload infinitely.

**Comment by io-sono-roy** [comment]
> I am getting this issue too. Latest stable Next.js version. I have set up `getServerSideProps` and the session value is null when using turbopack. If I use the default compiler, I get the proper session value. Using turbopack here causes the page to reload infinitely.

This is in Pages right? I'm using App router, but I think it's the same case

**Comment by ridays2001** [comment]
> This is in Pages right? I'm using App router, but I think it's the same case

Oh yea, forgot to mention the pages directory.
