### ISSUE TITLE
router.push("/") broken when intercepting routes as modal with parallel routes

### ISSUE THREAD

**Issue by pedro757** [vercel/next.js#51711]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: 8.6.1
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3


```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/fast-bush-qlpdwm?file=%2Fapp%2Fhome%2Fpage.tsx

### To Reproduce

use push("/") in a modal

### Describe the Bug

This is what I get
![image](https://github.com/vercel/next.js/assets/30637426/336f9356-79ca-40c6-949c-ab3c64466573)

### Expected Behavior

I expect it to actually redirect me to the path I telling it to redirect

**Comment by m10rten** [comment]
Relatable issue here:
When having a modal in `@modal` folder that is a intercepted version of another page eg: signin modal, intercepted from `/signin`.
Whenever I press a `<Link href="terms" />` it does not remove the modal, even though I set this in my Dialog from @shadcn ui:
```tsx
"use client";

import { useRouter } from "next/navigation";
import SinginContent from "@/app/(auth)/signin/content";
import { Dialog, DialogContent } from "@/components/ui/dialog";

export default function SigninModalContent() {
  const router = useRouter();
  const handleOnOpenChange = (open: boolean) => {
    if (!open) {
      router.back();
    }
  };
  return (
    <Dialog open={true} onOpenChange={handleOnOpenChange}>
      <DialogContent>
        <SinginContent />
      </DialogContent>
    </Dialog>
  );
}
 ```

**Comment by m10rten** [comment]
> Relatable issue here: When having a modal in `@modal` folder that is a intercepted version of another page eg: signin modal, intercepted from `/signin`. Whenever I press a `<Link href="terms" />` it does not remove the modal, even though I set this in my Dialog from @shadcn ui:
> 
> ```tsx
> "use client";
> 
> import { useRouter } from "next/navigation";
> import SigninContent from "@/app/(auth)/signin/content";
> import { Dialog, DialogContent } from "@/components/ui/dialog";
> 
> export default function SigninModalContent() {
>   const router = useRouter();
>   const handleOnOpenChange = (open: boolean) => {
>     if (!open) {
>       router.back();
>     }
>   };
>   return (
>     <Dialog open={true} onOpenChange={handleOnOpenChange}>
>       <DialogContent>
>         <SigninContent />
>       </DialogContent>
>     </Dialog>
>   );
> }
> ```

I think I did something

```tsx
  useEffect(() => {
    if (path !== "/signin") {
      setOpen(false);
    } else {
      setOpen(true);
    }
  }, [path]);
  ```

**Comment by BrunoFerreira95** [comment]
Check the import 
import { useRouter } from 'next/router'
or
import { useRouter } from 'next/navigation'

maybe be valide.
A new update in the docs about the defalut.tsx was release.

**Comment by TheLexoPlexx** [comment]
Probably the same issue here: I fixed it through push to the parent directory first. I don't know why that works: https://github.com/TheLexoPlexx/senator/tree/back-to-server/app/einsatzplanung/%5Bid%5D/%40user/add

**Comment by pedro757** [comment]
This issue still persist in v13.5.2

**Comment by david0178418** [comment]
Seems related to https://github.com/vercel/next.js/issues/49662

As noted by others in the ticket, routing back is working. But pushing new state does not.  Even using the native `(navigation || history).back()` will unmount the modal. But `history.pushState(...)` does not, which I'd imagine `Link` is using under the hood with simple linking fallback when js is not enabled.

**Comment by jchamale** [comment]
Happening to me as well, I'm intercepting a route like `/member/menu/card` and in this dialog I want to move to `/member/menu/information`. The intercept route never closes the dialog.

**Comment by pedro757** [comment]
Hey @samcx ! Thanks for addressing this issue, I just updated the code sandbox to the latest canary v14.0.5-canary.45 and I see  the background component (not the modal) disappears when refreshing, idk if that's the expected behavior. Other than that I believe `router.back()`  and`router.refresh()` are working good considering this sandbox. I haven't used this functionality in a real project though.

You can check out the code sandbox to make sure that's the expected behavior. 

I guess you can close this issue in next release.

**Comment by samcx** [comment]
@pedro757 I can confirm this is a separate 🐛 with `router.refresh()`—it should not disappear. I have shared this with the team to take a look!
