### ISSUE TITLE
Refreshing an intercepted parallel route `(modal)` breaks router

### ISSUE THREAD

**Issue by pedro757** [vercel/next.js#51714]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: 8.6.1
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/goofy-williamson-myrykt

### To Reproduce

Steps to reproduce: 
1. Click `Go to Login Page` Button
2. Click `Refresh` Button
3. Click `Go Back` Button

### Describe the Bug

When refreshing an intercepted parallel route the router stops working and then you can't go to any other route because the intercepted route doesn't disappear.

### Expected Behavior

I expect the intercepted parallel route to disappear and take me to the correct route

<sub>[NEXT-2030](https://linear.app/vercel/issue/NEXT-2030/refreshing-an-intercepted-parallel-route-modal-breaks-router)</sub>

**Comment by jmarbutt** [comment]
I am having a very similar issue.

**Comment by joeleonard212** [comment]
Hi guys, I'm struggling with Intercepted/Parallel/Modal routes as well, exactly as described from @pedro757 

I open a modal containing some account settings. When I send a PUT request within the modal, I then run a router.refresh() to fetch the updated data from the underlying server component. 

When I run this from the actual segment page.tsx this works as expected.

Insted, within the @modal/(.)account/page.tsx the router.resfresh() doesn't update the visualization of changes and also the router breaks: if I click on router.back() the url changed but the component is still renderized and can't be removed without  a refresh.

I'll look for some workaround but I would like to understand if this is a bug or I'm doing something wrong

**Comment by joeleonard212** [comment]
I'm having the same issue as described from @pedro757 

When calling router.refresh() from within a  @modal/intercept/page.tsx rendered component,  the underlying server component doesn't fetch new data.

Also, if I call router.back() right after, the component persist rendered on the back path and can only be remove refreshing the browser.

When the component is called on its own normal route, the component is working fine.

**Comment by joeleonard212** [comment]
Hey guys, it seems they've released new docs and an extensive explanation of how the cache works. Everything is here!
https://github.com/vercel/next.js/discussions/54075

**Comment by Fredkiss3** [comment]
@joeleonard212 This is a total different discussion from this issue.

**Comment by joeleonard212** [comment]
> @joeleonard212 This is a total different discussion from this issue.

You sure ? 

The Component Cache keeps track of each rendered segment separately, in doing so it unlocks a bunch of features:

- Navigating between pages reusing segments (Partial Navigation).
- Instant back/forward navigation that preserves the browser scroll position
- <span style="color:red">**Parallel Routes / Interception, as you can keep the segment cache nodes of multiple pages at the same time. The Router Tree is the other piece in making Parallel Routes work as that decides what is being shown on screen.**</span>
- Purging individual segments of the router cache (i.e. router.refresh() purges the entire cache, but revalidatePath('/dashboard') will only purge the client-side router cache below the specified dashboard path in the near future).

I found it usefull since personally I fixed changing caching strategy. If a component require interaction with the user, I just don't rely on router.refresh() but I manage the cache using tags and server actions. Also, to correctly use intercepted routes, you should check if you are taking care of router tree

**Comment by Fredkiss3** [comment]
@joeleonard212 
Can you share the fix then ?

**Comment by joeleonard212** [comment]
> @joeleonard212 Can you share the fix then ?

Sure, hope this can be helpfull   https://github.com/joeleonard212/Intercept_and_Revalidate/tree/main 

this is just an example of how I'm using the following to let things work:

server_actions
unstable_cache
revalidate_tag

**Comment by joeleonard212** [comment]
https://github.com/vercel/next.js/assets/35630044/c5d70462-af1f-497a-855e-c82a1d38fc1c

**Comment by joeleonard212** [comment]
Now I'm gonna adopt useOptimistic() hook to let the update be instantaneous

**Comment by gragland** [comment]
Also having this issue on 13.4.20-canary.4. The problem persists even after navigating away from the intercepted route with <Link> or `router.push`.

**Comment by akomm** [comment]
I think it has nothing to do with specifically intercepting routes. It just happens with parallel routes:

https://github.com/vercel/next.js/issues/54723

**Comment by Enkratia** [comment]
Good to know that it's not just bugged `router.refresh()`. Server side routing via server actions with redirect() makes the same thing, absolutely.
