### ISSUE TITLE
App Router: Next/Link does not respect smooth scroll

### ISSUE THREAD

**Issue by chris-gil-martins** [vercel/next.js#51721]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
codesandbox on next@13.4.8-canary.1
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/boring-carson-rhrf23?file=%2Fapp%2Flayout.tsx%3A9%2C1

### To Reproduce

Use the two different navbars to see smooth scroll difference between Next/Link and normal anchor tag.

### Describe the Bug

Next/Link does not scroll smoothly

### Expected Behavior

Next/Link should scroll smoothly

<sub>[NEXT-1406](https://linear.app/vercel/issue/NEXT-1406/app-router-nextlink-does-not-respect-smooth-scroll)</sub>

**Comment by azvyae** [comment]
Possible related to #44295, only current workaround is by define the style inside `global.css` file with using !important directive

```css
html {
 scroll-behavior: smooth !important;
}
```

**Comment by agrattan0820** [comment]
Having the same issue as well, got a test deployment up in case that helps:
Vercel deployment: https://nextjs-scroll-to.vercel.app/
Code: https://github.com/agrattan0820/nextjs-scroll-to

**Comment by Manduro** [comment]
> Possible related to #44295, only current workaround is by define the style inside `global.css` file with using !important directive
> 
> ```css
> html {
>  scroll-behavior: smooth !important;
> }
> ```

Note that this has a possible unwanted side effect: navigating to a different page will not set the scroll position instantly but will also scroll to top smoothly.

**Comment by timneutkens** [comment]
To clarify this further, you're expecting `<Link href="#somewhere-on-the-same-page">` to be a smooth scroll and `<Link href="/blog#somewhere-else">` to not do a smooth scroll right?

As @Manduro said we saw many cases where people added `scroll-behavior: smooth` and then navigations become a case of rendering the page, then smooth scrolling to the top, which is a very jarring UX. Hence why we override the smooth scrolling before navigating. However, I'm thinking of not overriding scroll-behavior when it's same-page applying a hash.

**Comment by chris-gil-martins** [comment]
Perhaps a new prop to override the smooth behavior on a per case basis would be ideal to get a wider range of possibility.

`<Link href="#somewhere-on-the-same-page">` would move instantly
`<Link href="#somewhere-on-the-same-page" smooth>` would scroll smoothly if scroll behavior smooth is enabled

and same for different pages:

`<Link href="/blog#somewhere-else">`
`<Link href="/blog#somewhere-else" smooth>`

**Comment by timneutkens** [comment]
I'd prefer not introducing different behavior / props, just mirroring what `<a>` does.

**Comment by chris-gil-martins** [comment]
It would be great if different page hash link could also scroll smoothly, but if this would prove problematic with non-hash links scrolling to top then at least same-page hash smooth scroll as per your original suggestion would be fine. Worst case it should still be possible to achieve different page smooth scroll using normal `<a>`  tags.
