### ISSUE TITLE
Docs: description of Client Components is confusing

### ISSUE THREAD

**Issue by ishaanjain** [vercel/next.js#51734]
### What is the improvement or update you wish to see?

There's an improvement I'd like to see on the page on rendering (linked below)
https://nextjs.org/docs/app/building-your-application/rendering#component-level-client-and-server-rendering

Under the subheading Component-level Client and Server Rendering, there is written the following:

> Now, with Server and Client Components, React can render on the client and the server meaning you can choose the rendering environment at the component level.
> 
> By default, the app router uses Server Components, allowing you to easily render components on the server and reducing the amount of JavaScript sent to the client.

This seems to imply that Server Components render on the server, while Client components render on the client. However, to my understanding both Server and Client components render on the server by default.

If there's anything wrong with my understanding I'd love to correct it. If not, I'd like to see this documentation updated to clarify that Client components do **not** mean the component is rendered on the client.

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/rendering#component-level-client-and-server-rendering

<sub>[DX-1706](https://linear.app/vercel/issue/DX-1706/docs-description-of-client-components-is-confusing)</sub>

**Comment by balazsorban44** [comment]
I think, this is a good suggestion, thanks!

To clarify, client components are run on the server too, during build, doing a prerender pass, to generate the initial HTML. You can think of  client components as the default in the pages directory.

We should definitely note this to avoid the confusion of client != browser. 👍

**Comment by leerob** [comment]
Thanks for the suggestion! We've recently revamped our client and server component docs entirely. 

https://nextjs.org/docs/app/building-your-application/rendering/client-components
