### ISSUE TITLE
router.push('/') directs to a wrong url

### ISSUE THREAD

**Issue by jim-king-2000** [vercel/next.js#51748]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
github pages
```

### Link to the code that reproduces this issue or a replay of the bug

And here is the code: https://github.com/Cache-Hit-Shanghai/jujiuipcappui

### To Reproduce

1. Open https://cache-hit-shanghai.github.io/jujiuipcappui/.
1. Click the left-bottom button and see the url.

### Describe the Bug

We use a `Card` element:
```tsx
import { useRouter } from 'next/navigation';

export function IconLInk({icon, label, url}) {
  const router = useRouter();
  return (
    <Card pad='small' gap='small' onClick={() => router.push(url)}>
      <CardBody align='center'>
        {icon}
      </CardBody>
      <CardFooter align='center'>
        <Text size='xsmall'>{label}</Text>
      </CardFooter>
    </Card>
  );
}
```

And `router.push(url)` is the key point here.

Then we create two links:
```tsx
<IconLInk icon={<Webcam />} label='device' url='/' />
<IconLInk icon={<Radial />} label='my' url='/my' />
```

At last, we set the `basepath` in `next.config.js`:
```js
// @ts-check

/**
 * @type {import('next').NextConfig}
 **/
const nextConfig = {
  /**
   * Enable static exports for the App Router.
   *
   * @see https://nextjs.org/docs/pages/building-your-application/deploying/static-exports
   */
  output: "export",

  /**
   * Set base path. This is usually the slug of your repository.
   *
   * @see https://nextjs.org/docs/app/api-reference/next-config-js/basePath
   */
  basePath: "/jujiuipcappui",

  /**
   * Disable server-based image optimization. Next.js does not support
   * dynamic features with static exports.
   *
   * @see https://nextjs.org/docs/pages/api-reference/components/image#unoptimized
   */
  images: {
    unoptimized: true,
  },
};

module.exports = nextConfig;
```
### Expected Behavior

After being deployed to github pages, `router.push('/')` should direct to https://cache-hit-shanghai.github.io/jujiuipcappui/.
### Actual Behavior

`router.push('/')` directs to https://cache-hit-shanghai.github.io/jujiuipca.

Notice that it woks well on my local environment. `router.push('/')` directs to http://localhost:3000/jujiuipcappui. And on github pages, `router.push('/my')` works well and directs to https://[cache-hit-shanghai.github.io/jujiuipcappui/my](https://cache-hit-shanghai.github.io/jujiuipcappui/my).

### Steps to Reproduce

1. Open https://cache-hit-shanghai.github.io/jujiuipcappui/.
1. Click the left-bottom button and see the url.

And here is the code: <https://github.com/Cache-Hit-Shanghai/jujiuipcappui>
### Your Environment

- Grommet version: 2.32.2
- Browser Name and version: Chrome v114
- Operating System and version (desktop or mobile): Win11

### Expected Behavior

After being deployed to github pages, router.push('/') should direct to https://cache-hit-shanghai.github.io/jujiuipcappui/.

### Which browser are you using? (if relevant)

Chrome v104

### How are you deploying your application? (if relevant)

github pages

**Comment by jim-king-2000** [comment]
The original link: grommet/grommet#6851

**Comment by babytutu** [comment]
#51549

**Comment by jim-king-2000** [comment]
Close as duplicate to #51549.
