### ISSUE TITLE
Installing devDependencies as dependencies

### ISSUE THREAD

**Issue by AnilSeervi** [vercel/next.js#51741]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/blob/96d540c768330e3a53f14e954ef9f2a70e68b163/packages/create-next-app/templates/index.ts#L239

### To Reproduce

Just run `npx create-next-app` and select some devDeps like `typescript` or `eslint` and these will be installed as dependencies.

### Describe the Bug

Installing devDependencies as dependencies for `create-next-app` templates

### Expected Behavior

Install devDependencies as `devDependencies`

**Comment by GaneshJampa** [comment]
I think they were never been installed as devDependencies. They've been just dependencies. I see no problem.

**Comment by ijjk** [comment]
Closing as duplicate of https://github.com/vercel/next.js/issues/51161
