### ISSUE TITLE
@next/next/no-html-link-for-pages doesn't work with app router

### ISSUE THREAD

**Issue by osdiab** [vercel/next.js#51742]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.6.2
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/osdiab/next-eslint-repro-links/blob/main/src/app/page.js#L13

### To Reproduce

- set up next app
- make an `about` page
- add a link to the `index` page to the `/about` page with an `<a />` tag
- run `next lint`
- no error shows up

### Describe the Bug

I expect from [the description of the lint rule](https://nextjs.org/docs/messages/no-html-link-for-pages) that if i use an `<a />` tag where I should be using a `<Link />` tag for an internal link, it would tell me that i should use `<Link />` instead.

### Expected Behavior

It should show a lint error

**Comment by DerTimonius** [comment]
I'd like to take a look into this!

**Comment by Nick-surferboy** [comment]
Can you assign it to me please ?

**Comment by maanil17** [comment]
can you assign it to me?

**Comment by Aperrix** [comment]
hi everyone, any news ?

**Comment by abhiyadav05** [comment]
Hello sir can you assign it to me
