### ISSUE TITLE
post issue

### ISSUE THREAD

**Issue by aryanahmed15** [vercel/next.js#51743]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
vercel link add but post nothing show just show 500 error or 505 error and not show the link pic please solve my problem
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

a

### To Reproduce

vercel link add but post nothing show just show 500 error or 505 error and not show the link pic please solve my problem

### Describe the Bug

vercel link add but post nothing show just show 500 error or 505 error and not show the link pic please solve my problem

### Expected Behavior

nothing good

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

yes

**Comment by shuding** [comment]
Hi! Please be specific and provide a minimal reproduction of the problem here.
