### ISSUE TITLE
Trying to compile deleted loading.tsx

### ISSUE THREAD

**Issue by soKKett** [vercel/next.js#51763]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 20.1.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8-canary.2
      eslint-config-next: 13.4.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

works on a fresh build of nextJS canary

### To Reproduce

1. Init NextJS in the folder
2. Create any nested route (e.g. /app/dashboard)
3. Create loading.tsx
4. Load page in your browser
5. Delete loading .tsx

### Describe the Bug

The bug is that when i am deleting 'loading.tsx' it still tries to load it and show that error, even if i am reopening the server:

> ./src/app/dashboard/loading.tsx
> Error: Failed to read source code from C:\Users\ **** \repos\nextjs-app\src\app\dashboard\loading.tsx
> Caused by:
>     The system cannot find the file specified. (os error 2)

**The error disappears when i am reinstalling nextjs**

### Expected Behavior

I want Nextjs not to show error when i am deleting 'loading.tsx'

### Which browser are you using? (if relevant)

Chrome 114.0.5735.134 

### How are you deploying your application? (if relevant)

yarn dev on my PC

**Comment by babytutu** [comment]
delete .next folder
