### ISSUE TITLE
Docs: missing information in i18n docs

### ISSUE THREAD

**Issue by a0m0rajab** [vercel/next.js#51766]
### What is the improvement or update you wish to see?

In this documentation, I got an issue with the i18n. The middleware did not work, tried to find a solution online but without a luck. 

https://github.com/vercel/next.js/blob/5e36c349925ddf71ab48ef44e3d713ddc5afc883/docs/02-app/01-building-your-application/01-routing/13-internationalization.mdx#L21-L30

I think adding the `["*"]` case would be helpful.

### Is there any context that might help us understand?

Here is my stackoverflow question and solution: 

> 
> I have been trying to use the NextJs [i18n routing on a website](https://nextjs.org/docs/app/building-your-application/routing/internationalization) [Archive](https://web.archive.org/web/20230610190155/https://nextjs.org/docs/app/building-your-application/routing/internationalization), but when I followed the exact steps provided in the documentation, I got this error: Incorrect locale information provided
> 
> I tried to debug it by checking the headers of the requests but it's all correct.
> 
> I tried to solve this by checking the error on console, reading related questions on [stackoverflow](https://stackoverflow.com/questions/21589401/javascript-users-incorrect-locale-with-date-formatting) [Archive](https://web.archive.org/web/20230610190202/https://stackoverflow.com/questions/21589401/javascript-users-incorrect-locale-with-date-formatting) and [GitHub ](https://github.com/formatjs/formatjs/discussions/2440)[Archive](https://web.archive.org/web/20230610190208/https://github.com/formatjs/formatjs/discussions/2440) but without success.
> 
> 
> The issue is happening due to getting the language array as: [ "*" ] 
> Which is not defined in the language that we have,  I added an if condition to solve this issue: 
> 
> ```js
>     if (languages.length === 1 && languages[0] === '*') {
>         languages = ['ar']
>     }
> ```
> 
> Then followed the same steps in the documentation and it worked well. 
> 

https://stackoverflow.com/questions/76447732/nextjs-13-i18n-incorrect-locale-information-provided/76548248#76548248

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/internationalization

**Comment by leerob** [comment]
Hey, I just double checked the example linked for i18n, and it seems to working as expected for me.

**Comment by a0m0rajab** [comment]
@leerob thank you for that, I solved the issue on my side. Yet if I go again with the docs I got the same issue! 

When you check the demo you can find that they have the accept language set: 

https://github.com/vercel/next.js/blob/a4094e28a19b14153fab087aa8602e97d32d0aed/examples/app-dir-i18n-routing/middleware.ts#L9-L25

Do you suggest me to have a video recording of the issue or just keep it as it's?
