### ISSUE TITLE
The word "the" is repeated in the last blog post.

### ISSUE THREAD

**Issue by danmondra** [vercel/next.js#51770]
### What is the improvement or update you wish to see?

The word "the" is repeated in:
https://nextjs.org/blog/june-2023-update#road-to-stability
-> Stable API line...

![image](https://github.com/vercel/next.js/assets/110652280/8bbec174-7e99-48c6-9e36-151fdaf8cf7b)

### Is there any context that might help us understand?

I think the blog is not open source, that's why I couldn't make the correction.

### Does the docs page already exist? Please link to it.

https://nextjs.org/blog/june-2023-update#road-to-stability

**Comment by balazsorban44** [comment]
Thanks, I applied a fix, this should be gone soon.
