### ISSUE TITLE
Intercepting Routes Modal gives 404

### ISSUE THREAD

**Issue by cinnamonbreakfast** [vercel/next.js#51796]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.13.0
      npm: 8.19.3
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/pensive-snowflake-cdwnv9?file=%2Fapp%2F%40modal%2F%28.%29about%2Fpage.tsx%3A5%2C2

### To Reproduce

try to navigate to anything. Locally i fet 404, on codesandbox doesn't even build

### Describe the Bug

The link above doesn't even work, but locally i get a 404 for everything... 

### Expected Behavior

a very low effort modal example for intercepting routes

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

yarn dev

**Comment by louisthomaspro** [comment]
Hello,
You are missing the `default.tsx` inside your `@modal` folder. This returns null for your `{modal}` in `layout.tsx` while the route is not intercepted.
Additionally, you need to upgrade NextJS version (> 13.3)

Please find the CodeSandbox link with the fixes: https://codesandbox.io/p/sandbox/modest-saha-hxr5zl

**Comment by cinnamonbreakfast** [comment]
Wow, never thought it could be that. Fixed, i will close it.
Thank you!
