### ISSUE TITLE
Docs: Scrolling to an id

### ISSUE THREAD

**Issue by nagman** [vercel/next.js#51827]
### What is the improvement or update you wish to see?

> When there is an `id` defined in `href`, it will scroll to the specific `id`, similarly to a normal `<a>` tag.
> To prevent scrolling to the top of the route segment, set `scroll={false}` and add a hashed `id` to `href`

So... do I need to set `scroll={false}` or not?

If it already scrolls to the `id` without `scroll={false}`, why would I add it?

### Is there any context that might help us understand?

I've tried with and without it, and in every case it scrolls to the hashed `id`.

I think the second sentence can be removed.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#scrolling-to-an-id

**Comment by davidjmurphyjr** [comment]
FWIW, scroll=false was removed from the docs

https://github.com/vercel/next.js/pull/51964/files
