### ISSUE TITLE
create-react-app: reactStrictMode in next.config.js is inconsistently set

### ISSUE THREAD

**Issue by dan-mcdonald** [vercel/next.js#51838]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
N/A this isn't a part of the normal NextJS framework, but instead is part of the create-next-app package. I reviewed the source code for tag v13.4.8-canary.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

N/A

### To Reproduce

1.  `$ npx create-next-app@v13.4.8-canary.5 example-no-app --no-src-dir --no-eslint --no-tailwind --no-app --javascript --import-alias="@/*"`
2. `$ npx create-next-app@v13.4.8-canary.5 example-is-app --no-src-dir --no-eslint --no-tailwind --app --javascript --import-alias="@/*"`
3. `$ diff -u example-{no,is}-app/next.config.js`

### Describe the Bug

When creating a new next app with the app router, the reactStrictMode flag is not enabled by default.

### Expected Behavior

I expected that an app style project would enable reactStrictMode by default. But it does not.

```$ diff -u example-{no,is}-app/next.config.js
--- example-no-app/next.config.js       2023-06-26 16:33:31.250000000 +0000
+++ example-is-app/next.config.js       2023-06-26 16:33:31.250000000 +0000
@@ -1,6 +1,4 @@
 /** @type {import('next').NextConfig} */
-const nextConfig = {
-  reactStrictMode: true,
-}
+const nextConfig = {}
 
 module.exports = nextConfig
```

**Comment by balazsorban44** [comment]
Hi, this is because using the app router automatically opts into React strict mode.

See https://github.com/vercel/next.js/blob/57ab2818b93627e91c937a130fb56a36c41629c3/packages/next/src/build/webpack-config.ts#L322
