### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by merzainc** [vercel/next.js#51855]
### What is the improvement or update you wish to see?

![IMG_20230627_001637](https://github.com/vercel/next.js/assets/114744793/63893e7e-6939-4649-8530-4806fa9f1b6c)
I would like to have this section reviewed, is this statement entirely correct?. Wasn't the statement supposed to have said "redirecting" instead of "rewriting".

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/components/link

**Comment by JesseKoldewijn** [comment]
Please update the issue title to reflect the topic you want to talk about.
Plus, you can both do rewriting and/or redirecting from the middleware. Depends on the usecase.

**Comment by balazsorban44** [comment]
The sentence reflects the code snippet right below it, so it is as expected.

![image](https://github.com/vercel/next.js/assets/18369201/578d9c32-bbd9-4327-991b-341c16bfecc1)


But as said above, you can also do redirects if you wish.

**Comment by merzainc** [comment]
Thank you all for clearing that up
