### ISSUE TITLE
Docs: getStaticProps equivalent in app router

### ISSUE THREAD

**Issue by c-desmarais** [vercel/next.js#51860]
## Description

I am looking at the [getStaticProps docs](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props) and I don't see an equivalent in the app router. I have gone through [the migration guide](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#static-site-generation-getstaticprops) as well to see if I haven't missed out on anything. 

The migration guide seems to mention that `getStaticProps` is no longer necessary, especially because some optimizations have been done within the `fetch` API. 

However, I'm unsure how to achieve the same results since I am not using the fetch API. 

### Is there any context that might help us understand?

I would like to generate my static page at build time and pass it given set of properties. I don't want to have to call a function that fetches the data every time the page is rendered. I want to pre-render it at build time. 

For now, all I need to do to build the page is read from my file system. 

I used to follow this guide : https://nextjs.org/learn/basics/dynamic-routes/render-markdown

But unfortunately I don't see the equivalent example with the app router. 

Having a similar example with the app router or more details about how to correctly replace `getStaticProps` without using fetch would be really nice.

**Comment by DuCanhGH** [comment]
This is how you do it in App Router:
```jsx
// lib/posts.js
import { remark } from 'remark';
import html from 'remark-html';

export async function getPostData(id) {
  const fullPath = path.join(postsDirectory, `${id}.md`);
  const fileContents = fs.readFileSync(fullPath, 'utf8');

  // Use gray-matter to parse the post metadata section
  const matterResult = matter(fileContents);

  // Use remark to convert markdown into HTML string
  const processedContent = await remark()
    .use(html)
    .process(matterResult.content);
  const contentHtml = processedContent.toString();

  // Combine the data with the id and contentHtml
  return {
    id,
    contentHtml,
    ...matterResult.data,
  };
}

// app/posts/[id]/page.jsx
import { getPostData } from "@/lib/posts.js";

export default async function Page({ params: { id } }) {
  const postData = await getPostData(params.id);
  return (
    <Layout>
      {postData.title}
      <br />
      {postData.id}
      <br />
      {postData.date}
      <br />
      <div dangerouslySetInnerHTML={{ __html: postData.contentHtml }} />
    </Layout>
  );
}
```
Hope this helps!

**Comment by codegino** [comment]
I'm having the same problem. I want to fetch some data from different sources using their SDKs. As a **dirty** workaround, I moved my `getStaticProps` logic to a new API and use `fetch` to reach that API.

```js
// app/api/page-prop/route.ts
export const GET = async () => {
  // Copy-paste code from old getStatisProps

  return NextResponse.json({
    // return value of old staticProps
  });
};
```

The data are pre-rendered properly and I don't see a flicker from `loading.tsx` to `page.ts`, but I don't want to expose those APIs to the public. I hope we have something like a [Remix loader](https://remix.run/docs/en/main/route/loader) so it would be easier.

**Comment by balazsorban44** [comment]
https://github.com/vercel/next.js/issues/51860#issuecomment-1609019374 is the correct answer here. The App Router will try to render static content at build-time unless opted out via a [Dynamic Function](https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering#dynamic-functions)

Read more at https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering

**Comment by c-desmarais** [comment]
> This is how you do it in App Router:
> 
> ```js
> // lib/posts.js
> import fs from 'fs';
> import matter from 'gray-matter';
> import path from 'path';
> import { remark } from 'remark';
> import html from 'remark-html';
> 
> // Your markdown folder for posts.
> const postsDirectory = path.join(__dirname, '../posts');
> 
> export async function getPostData(id) {
>   const fullPath = path.join(postsDirectory, `${id}.md`);
>   const fileContents = fs.readFileSync(fullPath, 'utf8');
> 
>   // Use gray-matter to parse the post metadata section
>   const matterResult = matter(fileContents);
> 
>   // Use remark to convert markdown into HTML string
>   const processedContent = await remark()
>     .use(html)
>     .process(matterResult.content);
>   const contentHtml = processedContent.toString();
> 
>   // Combine the data with the id and contentHtml
>   return {
>     id,
>     contentHtml,
>     ...matterResult.data,
>   };
> }
> 
> // app/posts/[id]/page.jsx
> import { Layout } from "@/components/Layout";
> import { getPostData } from "@/lib/posts";
> 
> export default async function Page({ params }) {
>   const postData = await getPostData(params.id);
>   return (
>     <Layout>
>       {postData.title}
>       <br />
>       {postData.id}
>       <br />
>       {postData.date}
>       <br />
>       <div dangerouslySetInnerHTML={{ __html: postData.contentHtml }} />
>     </Layout>
>   );
> }
> ```
> 
> Hope this helps!
> 
> In the App Router, Next.js would try to prerender everything just like in Pages Router. But, by default (no `export const fetchCache` stuff), to bail out of prerendering you have to use dynamic params (such as `[id]`, `[...id]`, `[[...id]]`) without `generateStaticParams` (equivalent of `getStaticPaths` in Pages Router), use `export const dynamic = 'force-dynamic'` or `export const revalidate = 0`, use `fetch` with `{ cache: 'no-store' }`/`{ next: { revalidate: 0 } }`, or use dynamic functions like `cookies()` and `headers()`.
> 
> You can now do data fetching (or server-related stuffs such as using Node.js's APIs) directly in Server Components (they can be marked with `async` like in the example above), so `getStaticProps` and its friends are no longer needed.

Sounds good. Much thanks for your detailed reply. 

So are we saying that in this example, `getPostData` will only be fully executed at build time ? 

When I notice `getPostData` still gets called at runtime, should I just assume there is some caching behind the scenes that keeps the result of the previous execution (at build time) ? 

Just trying to understand a bit how this works under the hood. :)

**Comment by DuCanhGH** [comment]
@c-desmarais if it is exactly like in the example then no, `getPostData` is executed on page request as it is a dynamic route without `generateStaticParams`. What you need to do is [export `generateStaticParams` from your page](https://nextjs.org/docs/app/api-reference/functions/generate-static-params), just like [how you use `getStaticPaths` with `getStaticProps`](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-paths) in Pages Router (`getStaticProps` won't work without `getStaticPaths` in dynamic routes).
