### ISSUE TITLE
fetch() on dev server: logs collapses requests to the same url

### ISSUE THREAD

**Issue by tomconroy** [vercel/next.js#51900]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Thu Mar  9 20:12:21 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8-canary.6
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/tender-water-pmswst?file=%2Fapp%2Fpage.tsx%3A23%2C1

### To Reproduce

Open the code sandbox logs to see this output:

```
-  ┌ GET / 200 in 90ms
   │
   ├──── POST https://www.generaltypestudio.com/graphql 200 in 0ms (cache: HIT)
   │
   ├── 1 level ── POST https://www.generaltypestudio.com/graphql?p=foo 200 in 0ms (cache: HIT)
   │
   ├── 1 level ── POST https://www.generaltypestudio.com/graphql?p=bar 200 in 0ms (cache: HIT)
   │
   └── 1 level ── POST https://www.generaltypestudio.com/graphql?p=baz 200 in 1ms (cache: HIT)
   ```

### Describe the Bug

Multiple `fetch()` requests to the same resource (with different POST body) are shown as a single request in the dev server logs. This makes it impossible to know if requests are being cached appropriately.

### Expected Behavior

I would expect the 3 different requests to show 3 times here. Even though the URL the same, the requests are not the same. It's possible to get around this by supplying a query param... for GraphQL requests it's usually easy enough to include the query name as a query param.

e.g. expected output:

```
-  ┌ GET / 200 in 90ms
   │
   ├──── POST https://www.generaltypestudio.com/graphql 200 in 0ms (cache: HIT)
   │
   ├──── POST https://www.generaltypestudio.com/graphql 200 in 0ms (cache: HIT)
   │
   ├──── POST https://www.generaltypestudio.com/graphql 200 in 0ms (cache: HIT)
   │
   ├── 1 level ── POST https://www.generaltypestudio.com/graphql?p=foo 200 in 0ms (cache: HIT)
   │
   ├── 1 level ── POST https://www.generaltypestudio.com/graphql?p=bar 200 in 0ms (cache: HIT)
   │
   └── 1 level ── POST https://www.generaltypestudio.com/graphql?p=baz 200 in 1ms (cache: HIT)
   ```

**Comment by nickjackson** [comment]
This is a duplicate of #51699

**Comment by tomconroy** [comment]
Beat me to it!
