### ISSUE TITLE
[NEXT-1326] eslint: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by codewithhong** [vercel/next.js#51917]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.16.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.6.1
Relevant Packages:
  next: 13.4.8-canary.7
  eslint-config-next: 13.4.8-canary.7
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.0.4
Next.js Config:
  output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

ESLint (eslint-config-next)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/codewithhong/eslint-plugin-next-bug

### To Reproduce

1. Add a client component
2. Use arrow function

### Describe the Bug

These [five lines](https://github.com/vercel/next.js/blob/5b883bb5d1de5a2d47d419dd0019e158b5f6896e/packages/eslint-plugin-next/src/rules/no-async-client-component.ts#L55-L59) can't find anything, actually.

And it caused:
```txt
Cannot read properties of undefined (reading 'type')
Occurred while linting X:\eslint-plugin-next-bug\src\app\page.tsx:1
Rule: "@next/next/no-async-client-component"
```

### Expected Behavior

No error.

<sub>[NEXT-1326](https://linear.app/vercel/issue/NEXT-1326/eslint-cannot-read-properties-of-undefined-reading-type)</sub>

**Comment by balazsorban44** [comment]
Thanks, this rule was introduced in https://github.com/vercel/next.js/pull/51547, and looks like this case was missing.

We should probably make sure the rule handles arrow functions but at the very least not error.

The source code is at https://github.com/vercel/next.js/blob/canary/packages/eslint-plugin-next/src/rules/no-async-client-component.ts

Feel free to open a PR!

Regarding the 404 in the docs, this change happened 2 days ago, some parts of the documentation are only updated on patch releases, and not for `canary`. It should be there the next time we release a new version
