### ISSUE TITLE
Docs: redirect() is missing an explanation not RedirectType

### ISSUE THREAD

**Issue by alvarlagerlof** [vercel/next.js#51975]
### What is the improvement or update you wish to see?

I'd love to see an explanation for the second param for redirect(). Looking at the types, it seems like it's an enum of `"push"` or `"replace"`. I can guess what it does, but I'd love to see what it corresponds to server-side. Is it a header of perhaps?

### Is there any context that might help us understand?

Server side

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/redirect#redirect

<sub>[DX-1713](https://linear.app/vercel/issue/DX-1713/docs-redirect-is-missing-an-explanation-not-redirecttype)</sub>

**Comment by delbaoliveira** [comment]
Thank you @alvarlagerlof, here's the PR: https://github.com/vercel/next.js/pull/51987

Feel free to leave any further feedback there.
