### ISSUE TITLE
CSS loader issue when migrating from pages to app

### ISSUE THREAD

**Issue by JamesGriz** [vercel/next.js#52021]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 7.26.0
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 12.3.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/JamesGriz/CSS-loader-issue

### To Reproduce

Clone repo and install dependencies.

`cd apps/web-ui`
`yarn dev`

Load http://localhost:3000/ which should display a page with "Hey! Welcome to the new app router"

In `web-ui/src/app/page.tsx` uncomment the `import '../global.css'` line and check http://localhost:3000/ again.

### Describe the Bug

This is a turbo repo using a ui library in `packages/ui` and a nextjs web app in `apps/web-ui`

I have started migrating the web-ui to use the new app router following the steps accordingly. https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#upgrading-new-features

As soon as I tried to import the gobal.css file I get the following error message:
```
./src/global.css
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @tailwind base;
| @tailwind components;
| @tailwind utilities;
```

Which has been working with no problem when using the pages router, can see in `web-ui/src/pages/_app.tsx` for how thats setup.

### Expected Behavior

When I start my next web app, it should start with no errors and I can see my tailwind styled applied to the app router index page (page.tsx).

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
Hi, so your repo contains private packages, so I was unable to run everything. I attempted to create a more minimal version of the reproduction: https://github.com/balazsorban44/nextjs-52021

This seems to work fine.

![image](https://github.com/vercel/next.js/assets/18369201/81738129-d731-4797-bd27-8a7c7b102f77)


Could you make sure your reproduction is as minimal as possible and is easy to install/run/debug so we can investigate more easily?

Small note: `next-transpile-modules` is not necessary anymore, see: https://nextjs.org/blog/next-13-1#built-in-module-transpilation-stable

**Comment by JamesGriz** [comment]
Hi @balazsorban44 thanks for looking into it, apologies about the dependency issues. Based on your feedback I want to do a bit of digging to try and pinpoint where the issue is coming from. Might be something to do with turbo repo. Will reopen if I find its relevant to nextjs with a better example to debug. Cheers

**Comment by JamesGriz** [comment]
The issue was next-transpile-modules as it turns out. After updating my next.config file the issue was resolved.
