### ISSUE TITLE
bug: revalidating many tags only revalidates the last one

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#52020]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.8-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.8-canary.12", newest: "13.4.8-canary.9".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/juliusmarminge/nextjs-revalidate-many-bug

### To Reproduce

1. Clone Repo
2. Click around the revalidate buttons.
3. Notice that each of the buttons that revalidates 1 tag works as expected, but when revalidting both, only 1 is revalidated.
4. Change order of the revalidation happens, notice that now the other fetch is revalidated.

Demo: 

https://github.com/vercel/next.js/assets/51714798/f15009e9-c92f-4e85-814e-f943a865ef9c

### Describe the Bug

When revalidating many tags, only the last one is revalidated. For example:

1. I send the two fetches `foo` and `bar`, each with a separate tag set:

```ts
export async function fetchFoo() {
  // this will hit the `api/foo` endpoint and tag the request with `foo`
  return myFetch({ key: "foo", path: "foo", input: {} });
}

export async function fetchBar() {
  // this will hit the `api/bar` endpoint and tag the request with `bar`
  return myFetch({ key: "bar", path: "bar", input: {} });
}

// Helper function to fetch with a cache tag
export async function myFetch<T = any>(opts: FetchOptions) {
  const { method = "GET" } = opts;

  let url = `${getBaseUrl()}/api/${opts.path}`;
  if (method === "GET") {
    url += `?input=${JSON.stringify(opts.input)}`;
  }

  const res = await fetch(url, {
    method,
    ...(method === "POST" && {
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(opts.input),
    }),
    next: { tags: [opts.key] },
  });

  if (!res.ok) {
    throw new Error(res.statusText);
  }
  return (await res.json()) as T;
}
```

2. Now i want to revalidate these, for the sake of bug reproduction I included 2 ways of doing this, 1 with server actions and 1 with a client-side fetch to a revalidate endpoint (to show that the bug is not dependent on the experimental serveractions feature)

2a. I revalidate the foo tag - now i get back a new timestamp for foo. Great.
2b. I revalidate the bar tag - now i get back a new timestamp for bar. Great.

3. Now I want to revalidate both at the same time. But only the last one is revalidated:

This will revalidate foo but not bar.

```tsx
      <form
        action={async () => {
          "use server";
          revalidateTag("bar");
          revalidateTag("foo");
        }}
      >
```

Changing the order of the 2 revalidations will cause bar to be revalidated but not foo.

### Expected Behavior

All tags to be revalidated

**Comment by juliusmarminge** [comment]
Side bug here is the layout shifting going on when revalidating. I've mostly seen this related to next/font (see https://github.com/vercel/next.js/issues/50879) but this repro is not using any fancy css or font loading at all.

it seems like the entire css stylesheet is being reloaded everytime a tag is revalidated (in dev only). seems a bit odd that that should happen.

**Comment by ijjk** [comment]
Hi, this appears to be fixed already in the latest canary of Next.js. Please update and give it a try!


https://github.com/vercel/next.js/assets/22380829/39eba705-556d-40c9-88d5-58c776f495d9
