### ISSUE TITLE
Interception does not work with (..)(..)

### ISSUE THREAD

**Issue by khuezy** [vercel/next.js#52059]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: 8.6.5
    Relevant Packages:
      next: 13.4.8-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

appDir, modal, route interception

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/khuezy/next-double-intercept

### To Reproduce

1. npm install
2. npm run dev
3. Go to [localhost:3000](http://localhost:3000)
4. Click on "/feed/nested"
5. Click on "Go to /photo", this should intercept the root /photo
6. Note the app loads /photo instead of intercepting
7. Look at terminal, see error:

```
error TypeError: Expected "1" to be a string
    at /Users/user/Projects/double/node_modules/next/dist/compiled/path-to-regexp/index.js:239:19
```

Console the tokens were from that library:

```
~~tokens:  [
  '/feed/nested',
  { name: 0, prefix: '/', suffix: '', pattern: '..', modifier: '' },
  { name: 1, prefix: '', suffix: '', pattern: '..', modifier: '' },
  'photo'
] { validate: false }
~~tokens:  [] { validate: false }
~~data:  { '0': '(..)(..)' }
```

### Describe the Bug

When using (..)(..) modal interception, it does not intercept path, console throws error

### Expected Behavior

Using (..)(..) correctly intercepts path 2 levels up

**Comment by rsolomon** [comment]
@khuezy Did you end up finding a solution to this? I'm running into what looks to be the same problem on v13.4.13, and it's also reproducible on your branch when upgrading `next` there too.

**Comment by khuezy** [comment]
@rsolomon That boy ain't right. You might want to open a new ticket w/ a repo step. I'm pretty sure the Nextjs is sick and tired of me opening the same ticket over and over.
