### ISSUE TITLE
Can Import Knex in Pages Folder, but Not in App Folder

### ISSUE THREAD

**Issue by machineghost** [vercel/next.js#52091]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023
    Binaries:
      Node: 20.3.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8-canary.14
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/machineghost/nextbug

### To Reproduce

I have a basic API route, but the code of the API is irrelevant because the problem is with an `import` line.  My sample repo just has a dummy API at /api/resource

1. Clone repo
2. `npm i`
3. `npm run  dev`
4.  Use Postman or a similar tool to make a GET request to http://localhost:3000/api/resource
5. See the error (both in response and at the terminal) ... even though the code never invokes anything from `knex` (it just imports it)

### Backstory/Explanation

The library Knex needs to be configured for different database libraries, so it has this code:

    const dbNameToDialectLoader = Object.freeze({
        'better-sqlite3': () => require('./better-sqlite3'),
        cockroachdb: () => require('./cockroachdb'),
        mssql: () => require('./mssql'),
        mysql: () => require('./mysql'),
        mysql2: () => require('./mysql2'),
        oracle: () => require('./oracle'),
        oracledb: () => require('./oracledb'),
        pgnative: () => require('./pgnative'),
        postgres: () => require('./postgres'),
        redshift: () => require('./redshift'),
        sqlite3: () => require('./sqlite3'),
    });
    
    // ...
    function getDialectByNameOrAlias(clientName) {
        const resolvedClientName = resolveClientNameWithAliases(clientName);
        const dialectLoader = dbNameToDialectLoader[resolvedClientName];

As you can see, when the file is required none of the database libraries are actually required along with it.  Instead, it exports `getDialectByNameOrAlias`, which is called later when Knex is configured.

Normally knex is configured like so:

    const realKnex = knex(config); // config details which database to use

### What does this have to do with Next?

I have a file that configures knex and exports the configured version.  When I import that file in an API route in the `pages` directory, it works great.

However, when I try to do the same exact thing (import the file) in an `app` route handler, I get the following error:

    - error ./node_modules/knex/lib/dialects/better-sqlite3/index.js:7:11
    Module not found: Can't resolve 'better-sqlite3'

    https://nextjs.org/docs/messages/module-not-found

    Import trace for requested module:
    ./node_modules/knex/lib/dialects/index.js
    ./node_modules/knex/lib/knex-builder/internal/config-resolver.js
    ./node_modules/knex/lib/knex-builder/Knex.js
    ./node_modules/knex/lib/index.js
    ./node_modules/knex/knex.js
    ./src/database/knex.js
    ./app/api/resource/route.js

In other words, it fails because it tries to require a SQL Lite library ... during the import, before I've even had a chance to configure Knex (and I can see as much through `console.log` statements).

If I comment out the code to require SQL Lite:

        const dbNameToDialectLoader = Object.freeze({
            //'better-sqlite3': () => require('./better-sqlite3'),

I get other errors, but I'm able to get past this one at least.  However, if I add a `console.log` (or trace) before the `require`:

        const dbNameToDialectLoader = Object.freeze({
            'better-sqlite3': () => console.log('wtf') || require('./better-sqlite3'),

I don't see the log (but do get the error).

As far as I can tell, Next (or Webpack?) is somehow seeing the `require` statements, and requiring them, *before* those `require` statements are actually run.  It then fails, because I don't have SQL Lite libraries installed ... but again, *only* when I do this in the `app` directory.

Oh, and all of this is happening in the dev environment (I haven't deployed a version that uses `app` yet because of this issue).

Does the `app` directory have any sort of `require` pre-loading that could explain this behavior?  

### Describe the Bug

I can't import knex, because some of its `require` statements (which are hidden behind a function call) get required before that function is called, causing an error because I don't have the corresponding library installed ... but all this only happens in the `app` folder (in `pages` everything imports just fine).

### Expected Behavior

If I can import a file in `pages`, I should be able to import it in `app`, even if it does weird `require` trickery (as Knex does).

### Which browser are you using? (if relevant)

A recent Chrome (not relevant)

### How are you deploying your application? (if relevant)

Other platform (not relevant)

**Comment by balazsorban44** [comment]
Hi, this is because dependencies used inside [Server Components](https://nextjs.org/docs/getting-started/react-essentials#server-components) and [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/router-handlers) will automatically be bundled by Next.js.

If a dependency is using Node.js specific features, you can choose to opt-out specific dependencies from the Server Components bundling and use native Node.js require.

See the docs: https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages

So the solution is:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['knex'],
  },
}
 
module.exports = nextConfig
```

**Comment by machineghost** [comment]
Thanks for the explanation, but shouldn't there be some mention of this in the documentation somewhere?  Knex is a pretty popular server-side library, and Next.js is becoming more and more of a server-side framework every day: more and more people are going to run into this problem.

Plus, I can't imagine Knex is the only library with conditional `require` statements in it.

**Comment by machineghost** [comment]
Or better yet, why not add Knex to the "[short list of popular packages](https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/server-external-packages.json) that currently are working on compatibility and automatically opt-ed out"?

**Comment by balazsorban44** [comment]
I linked to the relevant documentation. :pray: We have a baseline of "popular" packages that are included by default already, but I agree that this can be improved, so I flagged this to the team. It's hard to decide what should go to the list, as most people would consider their packages "priority"  to be included.

**Comment by machineghost** [comment]
I hear you on the difficulty of deciding on the list.  For what it's worth [Knex](https://github.com/knex/knex) has 17.7k Github stars.  That's only a fraction of Next's 100k+, but still more than some of the other existing excluded packages.

At its core, though, that list really seems like ... if not a problem, at least the smell of one ... so why not solve it by addressing the root issue instead?

> dependencies used inside [Server Components](https://nextjs.org/docs/getting-started/react-essentials#server-components) and [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/router-handlers) will automatically be bundled by Next.js.

Wouldn't it just make more sense to give Next some mechanism for saying "if a library exists in `node_modules`, bundle it up now; if not, get it later"?

**Comment by balazsorban44** [comment]
We are discussing exactly that. :+1: There is no 100% solution, but we are trying to come up with good heuristics to detect the most common cases. Thanks for the feedback!
