### ISSUE TITLE
Removed API route is seem to keep working

### ISSUE THREAD

**Issue by bookuha** [vercel/next.js#52099]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 16.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8-canary.14
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug
https://github.com/bookuha/kwp

### To Reproduce

Launch the project, navigate to the default page ("/").
Notice, that getPlayers() in OnlinePlayersList logs different players object than the one that http://localhost:3000/api/players returns. Try accessing http://localhost:3000/api/players with browser and with the component's fetch() - you may notice that they return different results.

### Describe the Bug

I had to transform object that comes from backend (extract only values). I did this in my players/route.ts, but when I access the route with the fetch in a component, I get unmodified result. When I access the route with browser directly, I get the expected result (only object's values). I have left console.log() in my route.ts, but when I access it with fetch(), it never procs, only with browser directly.
KEEP IN MIND, that at some point of time I had recreated an endpoint, and it feels like the previous version of it has been cached and fetch() accesses it. (restarts don't help)

### Expected Behavior

The route I access with fetch() API is the same I access with browser.

### Which browser are you using? (if relevant)

114.0.5735.199 - 64

### How are you deploying your application? (if relevant)

npm run dev

**Comment by EvandrooViegas** [comment]
could you provide the repo link?

**Comment by bookuha** [comment]
> could you provide the repo link?

yes, updated: https://github.com/bookuha/kwp

**Comment by balazsorban44** [comment]
I did a diff on calling the endpoint directly vs what's logged in the component and could not see a difference:

![image](https://github.com/vercel/next.js/assets/18369201/b940deb0-62e6-4647-a677-1597d8a4ad57)

The issue title also seems to be unrelated to the reported bug, I recommend opening a new issue, clarifying what the problem is, with a bit more clear reproduction steps, if it's still relevant in your opinion. Thanks!
