### ISSUE TITLE
Unavailable in app directory when used with vanilla extract

### ISSUE THREAD

**Issue by seohyeon1578** [vercel/next.js#52094]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.5
    Relevant Packages:
      next: 13.4.8-canary.14
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

with-vanilla-extract

### What browser are you using? (if relevant)

Chrome 114.0.5735.199

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

This is the problem I faced trying to set the globalStyle of `vanilla extract`.
I used it by `import  './globalStyle.css';` in layout.tsx, but failed to apply it.
If 'use client' is not specified, it is not applied.

### Expected Behavior

When starting next start the globalStyle should be applied and you will see the style applied in `app/page.tsx`.

### To Reproduce

Clone repo
`npx create-next-app --example with-vanilla-extract with-vanilla-extract-app
`npm run dev`

Load http://localhost:3000/ which should display a page with logo and button

in app/layout.tsx comment the 'use client' line and check http://localhost:3000/ again

**Comment by balazsorban44** [comment]
The error in the terminal originates from here:

https://github.com/vanilla-extract-css/vanilla-extract/blob/84ba370e770799dcb248ce3bb45e701dd7af9a77/packages/integration/src/packageInfo.ts#L47

Our templates don't have `name` defined as per our [example guidelines](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md)

You can simply add a `name` field to your project.
