### ISSUE TITLE
Docs: Search is not working under the page https://nextjs.org/learn/foundations/about-nextjs

### ISSUE THREAD

**Issue by promer94** [vercel/next.js#52121]
### What is the improvement or update you wish to see?

I should be able to search by clicking the search bar or use cmd + K

### Is there any context that might help us understand?

I can't do search when i was looking at https://nextjs.org/learn/foundations/about-nextjs

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/about-nextjs

**Comment by darshanjain-entrepreneur** [comment]
Can someone tell where i can find the doc in repo where the  search functionality is written

**Comment by leerob** [comment]
Thanks for the heads up, we'll fix this. This code for `/learn` is not open source 👍

**Comment by leerob** [comment]
Actually, I take that back. Seems we fixed it already. Can you confirm?

**Comment by promer94** [comment]
@leerob It works now. Thanks for your quick response ❤️
