### ISSUE TITLE
Error generating sitemap.xml with the latest 13.4.8 version

### ISSUE THREAD

**Issue by MartinXPN** [vercel/next.js#52146]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Jun  8 23:57:12 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

`yarn build && yarn start`

### To Reproduce

Create a `sitemap.ts` file in the `app` directory and export a function that generates routes dynamically.

### Describe the Bug

```shell
Error occurred prerendering page "/sitemap.xml". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError [ERR_INVALID_ARG_TYPE]: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
 ```

Crashes locally. Works fine when deployed to Vercel.

### Expected Behavior

The build shouldn't result in an error

**Comment by pogasanov** [comment]
Example from [docs](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#generate-a-sitemap) works fine. Please provide repo link.
