### ISSUE TITLE
Unsupported metadata not be rendered in the root layout

### ISSUE THREAD

**Issue by ngolin** [vercel/next.js#52175]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.1.7-canary.10
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

warn  - Latest canary version not detected, detected: "13.1.7-canary.10", newest: "13.4.9-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
npm notice 
npm notice New major version of npm available! 8.15.0 -> 9.7.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.7.2
npm notice Run npm install -g npm@9.7.2 to update!
npm notice
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/agitated-farrell-ldcnqz?file=%2Fapp%2Flayout.tsx%3A15%2C1

### To Reproduce

```js
export const metadata = {
  // this title rendered as expected.
  title: "My Title",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <head>
        {/* this meta won't be rendered, and on v13.4.7 double rendered. */}
        <meta http-equiv="Accept-CH" content="Width, Downlink, Sec-CH-UA" />
      </head>
      <body>{children}</body>
    </html>
  );
}
```

### Describe the Bug

Unsupported metadata not be rendered in the root layout on version canary, on v13.4.7 rendered twice.

### Expected Behavior

Render the unsupported metadata in the as described in `<head />`.

**Comment by balazsorban44** [comment]
This looks like coming from React itself. 

The console tells you:

```
Warning: Invalid DOM property `http-equiv`. Did you mean `httpEquiv`?
    at meta
    at head
    at HTML
```

And updating the attribute resolves the issue. Refer to https://react.dev/learn/writing-markup-with-jsx#3-camelcase-salls-most-of-the-things
