### ISSUE TITLE
Docs: CSS on the message docs was applied incorrectly

### ISSUE THREAD

**Issue by jaegeon-tatum** [vercel/next.js#52183]
### What is the improvement or update you wish to see?

The width of all hyperlink elements in the md document is 0.

example page : https://nextjs.org/docs/messages/invalid-getstaticpaths-value

**This bug occurs on all error message pages.**

<img width="1033" alt="image" src="https://github.com/vercel/next.js/assets/77370217/14aaa167-4416-4297-9fa6-b311ca2475af">

it caused by the presence of the `position: absolute` property in the hyperlink elements.

<img width="1430" alt="image" src="https://github.com/vercel/next.js/assets/77370217/87dad1a8-0e56-477d-9735-8e8ec7b2d504">

without `position: absolute`
<img width="1144" alt="image" src="https://github.com/vercel/next.js/assets/77370217/820b8c3d-7f3f-4618-bd75-3c7a8532a1bb">

### Is there any context that might help us understand?

Chrome Version 114.0.5735.133

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/invalid-getstaticpaths-value

<sub>[DX-1725](https://linear.app/vercel/issue/DX-1725/docs-css-on-the-message-docs-was-applied-incorrectly)</sub>

**Comment by nicksan222** [comment]
May i get assigned to this?

**Comment by roottool** [comment]
"[Install `sharp` to Use Built-In Image Optimization](https://nextjs.org/docs/messages/install-sharp)" page is a good example too.
There is a difference in the display of hyperlinks depending on whether the `absolute` class or the `relative` class.

The `relative` class doesn't occur this issue.
![image](https://github.com/vercel/next.js/assets/11808736/9cee1451-be19-4bc6-b158-925f870b9e8e)

**Comment by balazsorban44** [comment]
Thanks, this is already fixed and is going to be released soon, so I'm closing.
