### ISSUE TITLE
Instant Crash On 13.4.8

### ISSUE THREAD

**Issue by altechzilla** [vercel/next.js#52191]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Instant crash as soon as opening a route since the latest Next version (13.4.8), any idea where this is coming from and how to get around it? Didn't happen before the latest release.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue or a replay of the bug

N/A

### To Reproduce

Using the app directory with a variety of routes & dynamic metadata.

### Describe the Bug

**Unhandled Runtime Error**

Error: Cannot read properties of undefined (reading 'absolute')

**postProcessMetadata**

/.../Monorepo/Web/node_modules/.pnpm/next@13.4.8_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/lib/metadata/resolve-metadata.js (276:69)

**accumulateMetadata**

/.../Monorepo/Web/node_modules/.pnpm/next@13.4.8_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/lib/metadata/resolve-metadata.js (362:12)

MetadataTree

/.../Monorepo/Web/node_modules/.pnpm/next@13.4.8_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0_sass@1.63.6/node_modules/next/dist/lib/metadata/metadata.js (34:68)

### Expected Behavior

No crash, like on 13.4.7

### Which browser are you using? (if relevant)

Any

### How are you deploying your application? (if relevant)

Localhost

<sub>[NEXT-1397](https://linear.app/vercel/issue/NEXT-1397/instant-crash-on-1348)</sub>

**Comment by altechzilla** [comment]
@timneutkens - posted that crash issue here (re. this message https://github.com/vercel/next.js/issues/48748#issuecomment-1619117483)

<img width="738" alt="250650619-2342582c-43e4-4613-9af2-67919b4721b5" src="https://github.com/vercel/next.js/assets/8274669/9c6cfe25-bd0a-4319-b479-51349496b757">

**Comment by Rudi-Batubara** [comment]
This issue occurs when you accidentally add a statistics file twitter-image.tsx or opengraph-image.tsx in a route segment but the page.tsx does not contain the opengraph/twitter title field metadata

Next Info:
----------
    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.3.0
      npm: 9.8.0
      Yarn: 1.22.18
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.9-canary.2
      eslint-config-next: 13.4.9-canary.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A


This issue appears since NextJs v13.4.8 to 3.4.9-canary.2

Reproduce:
https://codesandbox.io/p/sandbox/bold-yalow-kmxc7p?file=%2Fapp%2Fpage.tsx%3A10%2C19

Temporary solution:
Added a twitter/opengraph title column to the static/dynamic metadata in the page.tsx file, or remove unused opengraph-image.tsx/twitter-image.tsx files
