### ISSUE TITLE
Router.push() doesn't remove Cookie on second execute

### ISSUE THREAD

**Issue by d-rubin** [vercel/next.js#52199]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.9-canary.1
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), CLI (create-next-app), Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/d-rubin/Router-issue

### To Reproduce

In my repo you can go to logout -> home -> logout -> home, and you will see that the authToken is not removed every time.

### Describe the Bug

I encountered this problem when I logged my user out and the authToken was not properly removed. This caused a bug where I saw the data from the previous user.

### Expected Behavior

 To solve this problem, an option for routing like "no-cache" would be nice, where the routing is executed every time.

### Which browser are you using? (if relevant)

Google Chrome Version 114.0.5735.199

### How are you deploying your application? (if relevant)

next dev

**Comment by nicksan222** [comment]
I think this is related to universal-cookies package...
