### ISSUE TITLE
Routing issue with basepath when deployed

### ISSUE THREAD

**Issue by vinceve** [vercel/next.js#52201]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

I did not install the latest canary version as we're using next and it's not compatible with our generators, so excuse me for that.

### Provide environment information

We're running in a Kubernetes environment and have created an ingress on domain.com/my-path. The NextJS app root is served on /my-path.

```bash
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

illprovidelater

### To Reproduce

1. deploy an ingress in a kubernetes cluster on domain.com/my-app
2. Configure the NextJS app to work on a subpath. (I tried lots of variations, the one that is posted here, works somewhat for the root page)

```javascript
const nextConfig = {
  nx: {
    // Set this to true if you would like to use SVGR
    // See: https://github.com/gregberge/svgr
    svgr: false,
  },

  /**
   * Being set in the helm charts.
   */
  trailingSlash: true,
  assetPrefix: '/my-app',
  async rewrites() {
    return [
      {
        source: '/my-app/:path*',
        destination: '/:path*', // The :path parameter is used here so will not be automatically passed in the query object.
      },
    ]
  },
};
```

### Describe the Bug

1. When surfing to /my-app on the domain. The root page is loaded and the assets are correctly served from /my-app/_next...
2. When surfing to a subpage /my-app/test/foo for example (a page that exists). A redirect is triggered to /test/foo on the browser.
3. When surfing to a subpage /my-app/my-app/test/foo for example. A redirect is triggered to /my-app/test/foo on the browser.

-------------

I'm aware of the base path property and tried to configure that as well in conjunction with a rewrite, but that doesn't work either.

### Expected Behavior

I would expect that the rewrite handles the /my-app correctly. 

Expected behavior:

1. Request on /my-app ---> internally maps on /
2. Request on /my-app/test/foo ----> internally maps on /test/foo (no redirect occurs!)
3. Request on /my-app/my-app/test/foo ----> Gives a 404 because it internally maps on /my-app/test/foo and that is not configured.

If I disable my javascript, the redirect is not occurring. I also see the following in my response: (note that the /railroad is my testing subpath)

 
<img width="1660" alt="Screenshot 2023-07-04 at 16 03 01" src="https://github.com/vercel/next.js/assets/875642/77c7e536-34dc-4fe1-9fbd-1b8894eb93b4">

If I understand correctly, the client side router code is forcing a redirect to the canonical url (that I see in the screenshot) which is outside of the subpath.

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

Kubernetes

**Comment by vinceve** [comment]
When I dive into the code itself I find that the client app router is using following parameter:

```
    'process.env.__NEXT_ROUTER_BASEPATH': JSON.stringify(config.basePath),
```

https://github.com/vercel/next.js/blob/8aa9a52c36f338320d55bd2ec292ffb0b8c7cb35/packages/next/src/build/webpack-config.ts#L357

As the basepath is not set in my config (because otherwise it would link to /my-app/my-app) this doesn't work. But I haven't got the full context of the codebase to make an informed decision on how to solve this.

**Comment by evanhameed99** [comment]
+1
