### ISSUE TITLE
No way in v13 (w `app/`) to generate a `<link rel="sitemap" ... />` in header

### ISSUE THREAD

**Issue by elmarsto** [vercel/next.js#52228]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
The documentation does not describe any method for producing a sitemap link, which is an HTML feature which passes validation: https://stackoverflow.com/questions/13327527/how-to-make-a-sitemap-link-in-the-page-head-pass-the-w3c-validator
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/elmarsto/sbstr8

### To Reproduce

Read the documentation

### Describe the Bug

No documented way in `metadata` to point to a sitemap

### Expected Behavior

If I can do it in `<Head>...</Head>` with v12, I should be able to do it in v13. A regression

**Comment by joulev** [comment]
You can always add it to your root layout

```tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="sitemap"
          type="application/xml"
          title="Sitemap"
          href="/sitemap.xml"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
```

**Comment by shuding** [comment]
It's documented here: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

**Comment by elmarsto** [comment]
With all due respect, it does not appear that you read and understood my comment. 

I'm well aware that you can generate a sitemap with sitemap.js/ts. 

I'm speaking specifically about the *link* to the sitemap that it is possible to create in <head>. 

Please refer to the original comment. I encourage careful reading.

**Comment by elmarsto** [comment]
Expected: 

As for links to an rss feed, there is some subfield of `metadata` I can create to generate such a <link> element. 

Actual:

No such mechanism exists. And when I create a link directly in <head>, it is not actually there in the output. Also, my tooling tells me to use `next/head`. And when I do *that*, there is, again, no `<link>` to the sitemap in the output.
