### ISSUE TITLE
Tab title not updating upon changing page

### ISSUE THREAD

**Issue by sinclairnick** [vercel/next.js#52223]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
   Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.5.0
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.0.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Metadata (metadata, generateMetadata, next/head, head.js)

### Link to the code that reproduces this issue or a replay of the bug

NA

### To Reproduce

Update project to 13.4.8. Visit page A, browser tab title ("Page A"). Visit page B, browser tab remains "Page A"

### Describe the Bug

Since upgrading to 13.4.8 the metadata title (at least, probably all meta) does not update upon changing route.

### Expected Behavior

Metadata should update when changing pages.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by sinclairnick** [comment]
Update: It actually seems that this might be a Vercel problem. Downgrading to 13.4.7 did not fix this issue. Moreover, the next docs website seems to be suffering the same issue mentioned.

**Comment by JesseKoldewijn** [comment]
I got a project that still runs 13.4.3.canary-0 that doesn't experience this issue oddly enough. Also deployed on vercel mind you, https://github.com/ShiftCodeEU/shiftcode.eu

**Comment by sinclairnick** [comment]
Thank you for mentioning that @TheEdoRan! I'm not even sure I'm using server actions at the moment, so I might be able to just scrap that config. Cheers!

**Comment by sinclairnick** [comment]
Closed in favour of https://github.com/vercel/next.js/issues/49409,
