### ISSUE TITLE
[Next 13.4.8] Code with Ternary Operator now broken

### ISSUE THREAD

**Issue by kenbankspeng** [vercel/next.js#52231]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: N/A
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.9-canary.1
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue or a replay of the bug

WIP

### To Reproduce

Build my code

### Describe the Bug

Issue only after upgrade from Next 13.4.7 to 13.4.8. My code and 3rd party lib code with Ternary Operator now hits transpilation error.

```
const entries = Object.entries(obj);
const firstValue = entries.shift()?.[1]; // [0] is key, [1] is value
```
transpiles to:
```
const entries = Object.entries(obj);
const firstValue = this?.;
```

Module parse failed: Unexpected token (23:33)
File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-flight-loader/index.js
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
|     const convert = (obj)=>{
|         const entries = Object.entries(obj);
>         const firstValue = this?.;
|         return {
|             ...firstValue,

I can avoid the error by refactoring. But I can't refactor all my 3rd party libraries.

This code is fine.
```
const entries = Object.entries(obj);
const maybeNull = entries.shift();
const firstValue = maybeNull && maybeNull[1];
```

### Expected Behavior

No error.

**Comment by kenbankspeng** [comment]
Issue is being caused by 3rd party swr plugin (next-superjson-plugin) which now breaks on Next 13.4.8.

**Comment by p-j** [comment]
Getting the same issue without the plugin mentioned (though we use another SWC plugin: [lingui/swc-plugin](https://github.com/lingui/swc-plugin))

Not sure this issue should be closed @kenbankspeng
