### ISSUE TITLE
Requests logs shows incomplete, unhelpful URLs

### ISSUE THREAD

**Issue by raphaelbadia** [vercel/next.js#52239]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
yarn run v1.22.19
$ /Users/raphael/code/billiv/billiv-frontend/node_modules/.bin/next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 7.25.1
    Relevant packages:
      next: 13.4.2
      eslint-config-next: 13.3.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4

warn  - Latest canary version not detected, detected: "13.4.2", newest: "13.4.9-canary.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
✨  Done in 2.57s.
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/raphaelbadia/nextjs-appdir-truncates-logs

### To Reproduce

Use fetchs with long URLS, such as 

```

export default async function Home() {
  await fetch(
    "https://jsonplaceholder.typicode.com/posts/1/comments?url=too_long&truncated=unfortunately_yes"
  );
  await fetch(
    "https://jsonplaceholder.typicode.com/posts/1/comments?url=too_long&hello=false&truncated=unfortunately_yes"
  );
  return null;
}
```

### Describe the Bug

When I use fetch, the requests are logged in the terminal. 

This is a great idea, but they are truncated and I can't differentiate them:

![CleanShot 2023-07-05 at 11 32 04](https://github.com/vercel/next.js/assets/1901628/9327a678-b507-4bc0-b12f-c627f1fa8e1a)

Here I don't understand why my edge config gets called twice, is it the same call? I can't know.

Same for my 6s slow request, In my code I have two different queries but I don't know which one is which.

### Expected Behavior

I'd like to be able to see the full URL in the terminal.

<sub>[NEXT-1604](https://linear.app/vercel/issue/NEXT-1604/requests-logs-shows-incomplete-unhelpful-urls)</sub>

**Comment by raphaelbadia** [comment]
This is where I'm at today. 

![CleanShot 2023-08-22 at 10 53 36](https://github.com/vercel/next.js/assets/1901628/f07bea35-c4a0-44db-89d8-058d9a9d8f46)

**Comment by matbee-eth** [comment]
I would also love this to be reviewed- atleast truncate the common URL components

**Comment by matbee-eth** [comment]
![image](https://github.com/vercel/next.js/assets/381356/7406596c-93ef-4171-b5aa-c6419f43d34a)
