### ISSUE TITLE
Loading UI Interferes with Puppeteer navigation

### ISSUE THREAD

**Issue by ProchaLu** [vercel/next.js#52265]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.0
    Relevant Packages:
      next: 13.4.9-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/ProchaLu/next-route-puppeteer

### To Reproduce

1. Clone the Puppeteer test repository from GitHub
```
git clone https://github.com/ProchaLu/next-route-puppeteer-test
```
2. Navigate to the project's root directory
```
cd next-route-puppeteer-test
```
3. Install the project dependencies
4. Start the Puppeteer test script by running the following command in the terminal:
```
node index.js
```

### Describe the Bug

I have encountered an issue where the Next.js Loading component interferes with Puppeteer and the actual page loading process. Currently, Puppeteer considers the page as "done" when the Loading component is visible, causing a problem because Puppeteer waits for the network to become idle before proceeding.

To illustrate the problem, I have created a small Next.js app directory project with a Next.js Loading component that is visible for a short amount of time. The small project [repository](https://github.com/ProchaLu/next-route-puppeteer) is [deployed](https://next-route-puppeteer.vercel.app/) with vercel. Additionally, here is the Puppeteer test [repository](https://github.com/ProchaLu/next-route-puppeteer-test).

The problem seems to be that Next.js uses same-document navigation, causing the browser navigation to be resolved much earlier than the app-level navigation. Consequently, Puppeteer waits for the network to become idle, assuming the page has finished loading, while the actual app-level navigation and content loading are still in progress. This discrepancy causes issues between Puppeteer and the Next.js Loading component.

This issue is related to the problem described in the Puppeteer issue: 
- https://github.com/puppeteer/puppeteer/issues/10447

### Expected Behavior

The expected behavior is for Puppeteer to accurately determine the readiness of the page, ensuring that it waits until the actual content is fully loaded before proceeding with the test. Ideally, there should be a seamless synchronization between Puppeteer's network idle state and the completion of the app-level navigation in Next.js. This improvement would prevent Puppeteer from misinterpreting the page readiness when the Next.js Loading component is displayed, resulting in consistent and reliable test execution.

### How are you deploying your application? (if relevant)

Vercel

**Comment by ProchaLu** [comment]
A solution for this with Puppeteer and Next.js would be to use the `page.waitForSelector()` method, like in the example below:
```js
  await Promise.all([
    page.waitForNavigation({ waitUntil: 'networkidle0' }),
    page.click('a[href="/page"]'),
  ]);

await page.waitForSelector('text/PAGE');
```

**Comment by Summaw** [comment]
Adding onto what was said above from @ProchaLu you could set a timeout and maybe do a try catch so if selector is there do x if not then do y.

`
await page.waitForSelector('selectorhere', {timeout: 10 * 1000});
`

**Comment by ProchaLu** [comment]
After investigating the loading states in Next.js, I was able to see some differences that can cause issues with Puppeteer and Next.js in the previous versions. I think since [Next.js `v13.4.20-canary.24`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.24), the loading state behavior has changed.

The [reproduction project](https://github.com/ProchaLu/next-loading-state) contains:

- Landing page featuring the `cookies().get` functionality
- Page for the `cookies().set` operation
- Test page to check the `cookies().get` function
- Content-rich page with both text and image elements
- Page with a client-side timeout of 2 seconds
- Page with a server-side timeout of 2 seconds
- Page equipped with a fetch function for interacting with an external API

The Puppeteer test goes to every page and checks the loading state, and waits for the network to be idle, to see if this can cause an issue when the test runner thinks the page is already loaded. 

The biggest difference is that the Next.js Loading component is not showing in the previous versions when the network is pending.

## Loading state with the `cookies().get` and `cookies().set` pages

- ### Loading component is not rendered when making network requests in Next.js `v13.4.9`, [Reproduction](https://github.com/ProchaLu/next-loading-state-old-version):

https://github.com/upleveled/courses/assets/80746311/85ea500b-74a8-4e0b-8e22-627d5084763b

<img width="1262" alt="old-network-pending-no-loading" src="https://github.com/upleveled/courses/assets/80746311/d5acb021-339f-472c-bbcd-910d011b7249">
<img width="1262" alt="old-network-pending-test-no-loading" src="https://github.com/upleveled/courses/assets/80746311/4667d9a3-880e-49b1-89c0-5d28d6a97a56">

- ### Loading component is rendered when making network requests in Next.js `v13.4.20-canary.24`, [Reproduction](https://github.com/ProchaLu/next-loading-state):

https://github.com/upleveled/courses/assets/80746311/38eb7340-2bdc-4a58-808d-a1b95487301d

<img width="1262" alt="new-network-pending-test-loading" src="https://github.com/upleveled/courses/assets/80746311/794773bb-4ade-4833-9ae9-301b306243df">

## Loading state when changing to a page with a server-side timeout

- ### Loading state not rendered with Next.js `v13.4.9`, [Reproduction](https://github.com/ProchaLu/next-loading-state-old-version):

<img width="1262" alt="old-network-pending-timeout-no-loading" src="https://github.com/upleveled/courses/assets/80746311/24243d6c-3e29-43e9-9eb7-bb54ffe814a9">

- ### Loading state rendered with Next.js `v13.4.20-canary.24`, [Reproduction](https://github.com/ProchaLu/next-loading-state):

<img width="1262" alt="new-network-pending-timeout-loading" src="https://github.com/upleveled/courses/assets/80746311/8cd43528-8eb3-4653-8851-c97045951156">

## Loading state when the network is idle after a `fetch`

- ### Loading state rendered and network idle with Next.js `v13.4.9`, [Reproduction](https://github.com/ProchaLu/next-loading-state-old-version):

<img width="1262" alt="old-network-idle-loading-state" src="https://github.com/upleveled/courses/assets/80746311/5d49726b-10c9-4145-bd4f-ba19f4a390cb">

- ### Loading state not rendered and network idle with Next.js `v13.4.20-canary.24`, [Reproduction](https://github.com/ProchaLu/next-loading-state):

<img width="1262" alt="new-fetch-finished-no-loading" src="https://github.com/upleveled/courses/assets/80746311/ef852e09-6e83-4a89-83ae-00d9aa26daab">

## Test results with Next.js `v13.4.9`:

```
goto page and set cookie
❌ not found
goto landing page
❌ not found
goto get cookie page
❌ not found
goto page with images and text
❌ not found
goto page with timeout
❌ not found
goto page with server timeout
✅ found
fetch from Pokemon API
✅ found
lading page second load
❌ not found
```

## Test results with Next.js `v13.4.20-canary.24`:

```
goto page and set cookie
✅ found
goto landing page
✅ found
goto get cookie page
✅ found
goto page with images and text
❌ not found
goto page with timeout
❌ not found
goto page with server timeout
✅ found
fetch from Pokemon API
✅ found
lading page second load
✅ found
```

## Page displaying before network is idle

<img width="1072" alt="network-not-idle-no-loading" src="https://github.com/upleveled/courses/assets/80746311/8fd29d62-dc32-48dd-8fd2-e5ac5b00e8de">

It is unclear for me whether this is an issue, as the page may render before it has fully loaded. Some images may still be pending in the network tab. In cases where these are no network requests, Puppeteer may interpret the network as idle beore the full page is loaded.

## [Reproduction](https://github.com/ProchaLu/next-loading-state-without-loading) without Next.js loading state:

https://github.com/upleveled/courses/assets/80746311/1e650b45-95c1-4ca7-b0dc-9eb4e3b77152

In this test repository, I noticed that network requests always finish before the page changes. This means that the network is idle before the new page is visible. As the screenshots show, before the page changes, the network is idle, and then the page changes.

- ### Network active on the previous page after click

<img width="1261" alt="no-loading-fetch-request" src="https://github.com/upleveled/courses/assets/80746311/f82788c2-fdcf-4ccd-8268-7578ae6ee093">

- ### Network is idle and page changes

<img width="1261" alt="no-loading-fetch-idle" src="https://github.com/upleveled/courses/assets/80746311/b38de5db-ce4f-4194-9e76-52378a0187d7">

## Other differences observed during testing

- Next.js changed the network requests. After recording videos with an older and newer Next.js version, I observed a difference in network requests when deploying the same page.

Next.js v`13.4.9`, 10 requests
<img width="323" alt="Screenshot 2023-09-22 at 12 24 13" src="https://github.com/upleveled/courses/assets/80746311/4566e58d-86ab-4575-89af-6280633e9836">

Next.js v`13.4.20`, 16 requests
<img width="323" alt="Screenshot 2023-09-22 at 12 26 06" src="https://github.com/upleveled/courses/assets/80746311/21ffbe9e-ecdb-4cef-a65b-df02df001faa">

## Conclusion:

The loading state issue with Next.js and Puppeteer that I encountered seems to be fixed in Next.js. I recommend upgrading always to the latest stable release version.

The loading state now works as expected on all pages except pages with client-side timeout are displaying the Next.js loading state. The loading component becomes visible when the network is active and disappears when the network becomes idle.
