### ISSUE TITLE
Docs: prevent re-rendering the dom after changing url search params using next router.push

### ISSUE THREAD

**Issue by mkhavari01** [vercel/next.js#52330]
### What is the improvement or update you wish to see?

i havent found any doc for it

### Is there any context that might help us understand?

.

**Comment by balazsorban44** [comment]
`router.push` is meant to reflect the current state of the URL, meaning it will also send an update to any reference to it. You can read the current URL that is not bound to `useRouter()` via `window.location.searchParams` for example.
