### ISSUE TITLE
Nextjs 13.4.9 - ESLint couldn't determine the plugin "react-hooks" uniquely.

### ISSUE THREAD

**Issue by belgattitude** [vercel/next.js#52365]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

ESLint (eslint-config-next)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/belgattitude/artist/pull/7

### To Reproduce

See https://github.com/belgattitude/artist/pull/7 and https://github.com/belgattitude/artist/actions/runs/5480794201/jobs/9984365681?pr=7

```bash
git clone -b nextjs-reprod-eslint-react-hooks --single-branch https://github.com/belgattitude/artist.git
cd artist
corepack enable && pnpm install
cd apps/web
pnpm lint
```

![image](https://github.com/vercel/next.js/assets/259798/9ee52a8c-48d9-42f3-9f99-46b8269b39ef)

```bash
pnpm why -r eslint-plugin-react-hooks
```

```
artist-monorepo /home/sebastien/github/artist

devDependencies:
@belgattitude/eslint-config-bases 1.35.1
└── eslint-plugin-react-hooks 4.6.0

web@0.1.0 /home/sebastien/github/artist/apps/web

devDependencies:
@belgattitude/eslint-config-bases 1.35.1
└── eslint-plugin-react-hooks 4.6.0
eslint-config-next 13.4.9
└── eslint-plugin-react-hooks 5.0.0-canary-7118f5dd7-20230705

artist-strapi-api@0.1.0 /home/sebastien/github/artist/packages/strapi-api

devDependencies:
@belgattitude/eslint-config-bases 1.35.1
└── eslint-plugin-react-hooks 4.6.0

```

### Describe the Bug

Since https://github.com/vercel/next.js/pull/52275, projects using a custom eslint configuration might run into `Nextjs 13.4.9 - ESLint couldn't determine the plugin "react-hooks" uniquely.`

Based on the reproduction PR above, see an example

- https://github.com/belgattitude/artist/blob/main/apps/web/.eslintrc.js
- it uses https://github.com/belgattitude/shared-dx/tree/main/packages/eslint-config-bases

In that case there will be 2 versions installed (with pnpm at least)

devDependencies:
@belgattitude/eslint-config-bases 1.35.1
└── eslint-plugin-react-hooks 4.6.0
eslint-config-next 13.4.9
└── eslint-plugin-react-hooks 5.0.0-canary-7118f5dd7-20230705

Which leads to `ESLint couldn't determine the plugin "react-hooks" uniquely.`

As a workaround:

```json
  "resolutions": {
    "eslint-plugin-react-hooks": "4.6.0"
  },
```

### Expected Behavior

Imho, eslint-plugin-next should allow usage of customized/shared eslint-config. Using a canary: eslint-plugin-react-hooks 5.0.0-canary-7118f5dd7-20230705 makes the setup slightly more difficult for some advanced usages.

PS: Tested with pnpm 8.6.6 and yarn 4.0.0-rc.48 but I guess other variant will fail to as it's different major version.

<sub>[NEXT-1476](https://linear.app/vercel/issue/NEXT-1476/nextjs-1349-eslint-couldnt-determine-the-plugin-react-hooks-uniquely)</sub>

**Comment by nareshbhatia** [comment]
I am running into the same issue with npm:

```
Plugin "react-hooks" was conflicted between
".eslintrc.js » eslint-config-next/core-web-vitals » my-app/node_modules/eslint-config-next/index.js » plugin:react-hooks/recommended"
and ".eslintrc.js » @my-lint-config/strict#overrides[1] » plugin:react-hooks/recommended"
```

My lint config is using `eslint-plugin-react-hooks@4.6.0` (which is the `latest` tag), whereas `eslint-config-next/core-web-vitals` is using `eslint-plugin-react-hooks@5.0.0-canary-7118f5dd7-20230705`:

```shell
npm list eslint-plugin-react-hooks
my-repo
├─┬ my-app
│ └─┬ eslint-config-next@13.4.9
│   └── eslint-plugin-react-hooks@5.0.0-canary-7118f5dd7-20230705
└─┬ my-lint-config
  └── eslint-plugin-react-hooks@4.6.0
```

**Comment by yusuf-saydullayev** [comment]
same issue in eslint-config-next@13.4.8

**Comment by emondpph** [comment]
Also running into this issue, reverting to eslint-config-next@13.4.8 seems to fix the problem for now

**Comment by gvillenave** [comment]
Any update here? We're still blocked in 13.4.12.

**Comment by terrymun** [comment]
Just an update: we are still experiencing this issue with the latest release 13.4.13.

**Comment by gvillenave** [comment]
Can anyone look at this? We are still stuck on version 13.4.7 because of this issue.

**Comment by emondpph** [comment]
I could remove this error by removing the direct dependency of eslint-plugin-react-hooks, and instead use the one that is bundled by NextJs

**Comment by M1chaelChen** [comment]
still experiencing this issue in 13.4.18. got it working with manual resolution
```
"resolutions": {
  ...,
  "eslint-plugin-react-hooks": "4.6.0"
}
```
