### ISSUE TITLE
Intercepting routes within grouped routes requires a `default.ts` in the group with the interception

### ISSUE THREAD

**Issue by luizeboli** [vercel/next.js#52386]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:38 PDT 2021; root:xnu-7195.141.8~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.3
    Relevant Packages:
      next: 13.4.10-canary.0
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/luizeboli/nextjs-group-interception

### To Reproduce

1. Install the dependencies
2. Start the web server
3. Open the home page at http://localhost:3000
4. A 404 not found error will be rendered

### Describe the Bug

This bug may be related to https://github.com/vercel/next.js/issues/48104

I have a route group called `(home)` and inside this group there's a parallel route called `@modal` with an interception to the `item/[slug]` page.

When starting the application it renders a 404 not found. The only way to fix that is by creating a `default.tsx` page inside the `@modal` route group as described in https://github.com/vercel/next.js/issues/48104#issuecomment-1500589264

If the interception is not inside a route group then it works without that `default.ts` page.

### Expected Behavior

I expect the application to render the home page without the necessity of creating a `default.tsx` page in the `@modal` route group.

### Which browser are you using? (if relevant)

Edge 114

**Comment by luizeboli** [comment]
Although the [docs](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes#examples) does not mention the necessity of this `default.tsx` page, looking the [example](https://github.com/vercel-labs/nextgram/blob/main/src/app/%40modal/default.tsx) it also creates this file inside the group.

I'm wondering if this is an expected behavior as a route group that just have an intercepted route can't be rendered in the layout as there's nothing to be rendered

**Comment by renovatt** [comment]
"next": "13.4.19",

I'm facing a slightly strange problem, I don't know if I'm missing something.

I have a project that is already working normally, the dynamic routes together with route interception, everything is ok. The folder structure is as follows:
![Captura de tela 2023-11-03 112111](https://github.com/vercel/next.js/assets/94547135/57677bf9-4cbc-4e47-964c-39331ae13114)

link: https://portfolio-renovatt.vercel.app/views/projects
Note: the route is being intercepted, the background remains the same.

But I'm trying to use hidden routes, ``(views)``, putting them in parentheses, and following the same structure, following the same pattern, route interception doesn't work correctly.

**An error occurs where the original route and the intercepted route are called together.**

I changed the structures a few times and found these two repositories, which I found in other issues:
https://github.com/vercel/next.js/issues/49614
https://github.com/vetledv/repro-intercept/blob/main/src/app/(some-group)/%40modal/(.)photos/%5Bid%5D/page.tsx
https://github.com/Apestein/nextflix/blob/main/src/app/(main)/%40modal/(.)show/%5Bid%5D/page.tsx

They are doing it like this, placing ``@modal`` inside ``(main)``, but when I do this, the route appears in the URL , however the screen is not changed, in this case my component does not appear, but if I update the page the original route happens, but just by placing ``(views)`` as the parent folder, the intercepted route happens, but with the same error as before , where the original route and the intercepted route are called together.

![Captura de tela 2023-11-03 111949](https://github.com/vercel/next.js/assets/94547135/cca21e1a-76cd-430b-8da2-baba1670412b)
![Captura de tela 2023-11-03 111653](https://github.com/vercel/next.js/assets/94547135/08145884-c945-4c51-b55c-d5b6024b9045)

I don't understand why this happens, can anyone help me?

**Comment by samcx** [comment]
@luizeboli Thank you for submitting an issue!

A few things to unpack here:

- It is expected to have a `default.tsx` inside your `(home)` Route Group → https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#reload. This was designed this way so you don't accidentally render a route that shouldn't be parallel rendered. A good visualization of this is also laid out in our <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> App Router playground → https://app-router.vercel.app/parallel-routes/impressions.

![CleanShot 2024-01-09 at 16 21 48@2x](https://github.com/vercel/next.js/assets/28912696/af9396df-5bb8-4aae-bb4f-01cb773b6466)

- You're missing a `export default` here → https://github.com/luizeboli/nextjs-group-interception/blob/main/src/app/(home)/%40modal/(...)item/%5Bslug%5D/page.tsx, which is resulting in the intercepted route to not show (e.g., if you were to add a link to `<Link href="/item/123"`)

(shows how intercepting routes work, and what happens after a hard refresh. I added the `export default` here)
![CleanShot 2024-01-09 at 16 57 07](https://github.com/vercel/next.js/assets/28912696/ed742ef4-0f43-4fbf-9e2c-e1b4238f17fb)

Let me know if that helps! As far as I can see, there is no 🐛 here with all the App Router things (Route Group, Intercepting Routes, & Parallel Routes) at play here.

**Comment by samcx** [comment]
@renovatt If you can submit a separate [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml), I can take a look!

**Comment by luizeboli** [comment]
Thanks for sharing that explanation @samcx
