### ISSUE TITLE
Link is truncated in the middle

### ISSUE THREAD

**Issue by devevignesh** [vercel/next.js#52381]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.17
      pnpm: 8.6.5
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: export
```

### Which example does this report relate to?

with-static-export

### What browser are you using? (if relevant)

Brave: 1.52.122 Chromium: 114.0.5735.110

### Describe the Bug

I have encountered an issue with the `Link` component where the link path is getting cut in the middle. For example, when using the following link: `<Link href="/client/uuid/coaching-guide" />`, it redirects to `/client/uuid/coaching-`, resulting in a 404 error. Similar to this: https://github.com/vercel/next.js/issues/48996#issuecomment-1612270534

### Expected Behavior

Expect it to go to "/client/uuid/coaching-guide"

### To Reproduce

`next.config.js`

```
/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
	output: 'export',
};

module.exports = nextConfig;
```

1. Execute [create-next-app](https://github.com/vercel/next.js/tree/canary/packages/create-next-app) with [npm](https://docs.npmjs.com/cli/init), [Yarn](https://yarnpkg.com/lang/en/docs/cli/create/), or [pnpm](https://pnpm.io/) to bootstrap the example:

```shell
npx create-next-app --example with-static-export with-static-export-app
```

2. Serve site via npx serve@latest out

<sub>[NEXT-1415](https://linear.app/vercel/issue/NEXT-1415/link-is-truncated-in-the-middle)</sub>

**Comment by devDoubleH** [comment]
Please checkout this: https://nextjs.org/docs/pages/api-reference/next-config-js/redirects

**Comment by leedyche** [comment]
Im experiencing the exact same issue. Im not using any redirects, i do have output:'export' set to true and any links I use get truncated and 404. I previously had the .txt issue (im using the latest nextjs) so ive set prefect={false} in order to avoid that. Currently I cant get any links to work at all when published as a static website does anyone have any work arounds? thanks

**Comment by devDoubleH** [comment]
Did you checkout link above

**Comment by devDoubleH** [comment]
Sorry for misunderstanding could give some examples of truncated urls please ?

**Comment by leedyche** [comment]
no problem, so an example link in my code is 
`<Link href="/weddings" > weddings </Link>`

Locall this works in debug, when i publish as a static site this will redirect to 

https://baseurl/ours

likewise this link

`<Link href="/ourstory" > Ourstory</Link>`

navigates to

https://baseurl/ours

however, if i navigate to the correct url by typing in the address ie go to 

https://baseurl/ourstory

I see the page, and all the links now work - untill i go to the home page, then all the links break again

thanks

**Comment by devDoubleH** [comment]
Is there any page called ourstory in your app ?

**Comment by leedyche** [comment]
yes, as i said if i navigate to the url directly it works without issue

**Comment by devDoubleH** [comment]
I am on nextjs 13.4.8 and everything okey

**Comment by leedyche** [comment]
It works for me in debug running locally, the issue only occurs when i publish using 

`/** @type {import('next').NextConfig} */
const nextConfig = {
    output:'export',
    distDir: 'dist'
  }

module.exports = nextConfig`

**Comment by zhangxinyong12** [comment]
When I use nginx as a proxy, refreshing the page prompts 403. If I set nginx to try_files $uri $uri/ /index.html;

Refresh and jump to the home page. How do you solve it? I don't understand.

**Comment by zhangxinyong12** [comment]
location / {
	   if ($uri ~* \.(html)$) {
               add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
            }
           try_files $uri $uri/ /index.html;
        }
