### ISSUE TITLE
`sitemap.ts` marked as as `"use client"` in version 13.4.9

### ISSUE THREAD

**Issue by Svish** [vercel/next.js#52390]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 20.1.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Svish/geekality.net/tree/e1a6cda84d9c3bd1879f405f96c616102fdeee8a

### To Reproduce

1. Run `npm i next@13.4.9` (or `.10-canary.0`)
2. Use `import 'server-only'` in a file that's imported by `./src/app/sitemap.ts`.
3. Run `npm run build`

### Describe the Bug

I have a file that uses `import 'server-only'` to make sure it doesn't leak into client components. In version `13.4.8` this was working fine, but once I tried to update `next` to the current `13.4.9`, I'm suddenly getting an error because of this. And the weirder part is that the error seem to be coming from my `./src/app/sitemap.ts`, which is definitely not using any client components, it's actually not using any components at all. It's the metadata route for sitemaps from Next. 🤔

Here's the output from running `npm run build` on version `13.4.9`. The latest canary produces the same error:

```
- warn You have enabled experimental feature (typedRoutes) in next.config.js.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. 
Use at your own risk.

Warning: Contentlayer might not work as expected on Windows
Generated 269 documents in .contentlayer
Failed to compile.

./src\content\index.ts
ReactServerComponentsError:

You're importing a component that needs server-only. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

   ╭─[D:\projects\geekality.net\src\content\index.ts:1:1]
 1 │ import 'server-only'
   · ────────────────────
 2 │
 3 │ import { byString, byStringValue } from '@/util/sort'
 4 │ import { onlyPublished } from './filters'
   ╰────

One of these is marked as a client entry with "use client":
  ./src\content\index.ts
  ./src\app\sitemap.ts
  ./src\app\sitemap.ts


> Build failed because of webpack errors
- info Creating an optimized production build .
```

### Expected Behavior

The `import 'server-only'` in my `./src/content/index.ts` shouldn't cause any issues in `sitemap.ts`, or any other files for that matter, just because I update `next` to version `13.4.9`.

<sub>[NEXT-1417](https://linear.app/vercel/issue/NEXT-1417/sitemapts-marked-as-as-use-client-in-version-1349)</sub>

**Comment by Arctomachine** [comment]
It started happening at canary 2, so one of commits between 1 and 2 causes this

**Comment by timneutkens** [comment]
Looking at the diff it's caused by this change: https://github.com/vercel/next.js/pull/51950

**Comment by franzwarning** [comment]
Seeing this same error with my icon.tsx file which is exporting a default async function which is getting headers from next/headers. I get the error:
```
You're importing a component that needs next/headers. That only works in a Server Component but one of its parents is marked with "use client", so it's a Client Component.
```

None of the parents are client components. It looks like the fix you pushed is only for those marked w/ server-only?
