### ISSUE TITLE
SWR stopped working on Nextjs

### ISSUE THREAD

**Issue by paulvanbrenk** [vercel/next.js#52410]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 3.4.1
      pnpm: 8.5.1
    Relevant Packages:
      next: 13.4.10-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC transpilation

### Link to the code that reproduces this issue or a replay of the bug

n/a

### To Reproduce

Add swr to a new project

`npm add swr`

Add following to `page.tsx` before exported function.

```
import useSWR from "swr";

const fetcher = (url: string) => fetch(url).then((res) => res.json());
```
Add following to exported function, doesn't matter the url doesn't exist.

```
  const { data } = useSWR("/hello", fetcher);
```

start app, and navigate to localhost.

Notice webpack error.

Since both NextJs, and SWR are build by Vercel, you're probably in a better position to figure out who broke what.

### Describe the Bug

- error app/page.tsx (9:26) @ Home
- error TypeError: (0 , swr__WEBPACK_IMPORTED_MODULE_2__.default) is not a function
    at Home (./app/page.tsx:19:69)
    at stringify (<anonymous>)
digest: "4017139691"
   7 | 
   8 | export default function Home() {
>  9 |   const { data } = useSWR("/hello", fetcher);
     |                          ^
  10 | 
  11 |   return (
  12 |     <main className={styles.main}>

### Expected Behavior

No webpack error

**Comment by paulvanbrenk** [comment]
I'm not sure when this broke, but I encountered it when migrating from pages > appdir. So between 12 and 13.4.9

**Comment by eashish93** [comment]
You can't use hooks in `page.tsx` file. If you want to use that, you can either add `use client` to `page.tsx` to make it render client side only or better way is to create a new file with `use client` and export that in `page.tsx`

**Comment by paulvanbrenk** [comment]
Adding 'use client` doesn't work, the separate component does. Arguably that is still a bug, the error message should be much better.

**Comment by devDoubleH** [comment]
Hello Paul I think you having a problem with a url. Next.js pages directory uses a folder called 'api' which indicates we need to use /api/url in every our requests.

const { data } = useSWR("/api/hello", fetcher);
 
So you please try this.

**Comment by balazsorban44** [comment]
@devDoubleH that is incorrect for App Router (which the OP seems to be referring to), it does not have any convention around the path for APIs as `pages/`

**Comment by balazsorban44** [comment]
The original issue seems to be what is explained here: https://github.com/vercel/next.js/issues/52410#issuecomment-1625958656

Adding `"use client"` at the top of the page fixes the issue. If it's not the case for you, please open a new issue, with an attached _minimal_ reproduction, thanks!
