### ISSUE TITLE
Error from Jest tests on a NextJS 13 Server Action

### ISSUE THREAD

**Issue by craigmcc** [vercel/next.js#52424]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Output from "next info":

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
```

Dependencies and dev dependencies from package.json:

```
  "dependencies": {
    "@craigmcc/shared-utils": "^1.0.3",
    "@prisma/client": "^4.16.2",
    "@tanstack/react-table": "^8.9.3",
    "@types/node": "20.3.3",
    "@types/react": "18.2.14",
    "@types/react-dom": "18.2.6",
    "autoprefixer": "10.4.14",
    "bcrypt": "^5.1.0",
    "class-variance-authority": "^0.6.1",
    "clsx": "^1.2.1",
    "eslint": "8.44.0",
    "eslint-config-next": "13.4.7",
    "lucide-react": "^0.258.0",
    "next": "13.4.7",
    "pino": "^8.14.1",
    "postcss": "8.4.24",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "rotating-file-stream": "^3.1.0",
    "tailwind-merge": "^1.13.2",
    "tailwindcss": "3.3.2",
    "tailwindcss-animate": "^1.0.6",
    "typescript": "5.1.6"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^14.0.0",
    "@types/chai": "^4.3.5",
    "chai": "^4.3.7",
    "jest": "^29.6.1",
    "jest-environment-jsdom": "^29.6.1",
    "prisma": "^4.16.2",
    "ts-node": "^10.9.1"
  }
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/craigmcc/bookcase

### To Reproduce

* Download and install this repository, along with it's depedencies.
* Attempt to run "npm run test:ci".
* See the error that is displayed in the output about LibraryActions.test.ts.

### Describe the Bug

Tests fail to run, with the following error message and trace:

```

 FAIL  src/actions/LibraryActions.test.ts
  ● Test suite failed to run

    Cannot find module 'private-next-rsc-action-proxy' from 'src/actions/LibraryActions.ts'

    Require stack:
      src/actions/LibraryActions.ts
      src/actions/LibraryActions.test.ts

      53 |  * The type for options that select which child or parent models should be
      54 |  * included in a response.
    > 55 |  */
         |              ^
      56 | type IncludeOptions = {
      57 |     // Include child Authors?
      58 |     withAuthors?: boolean;

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (src/actions/LibraryActions.ts:55:75)
      at Object.<anonymous> (src/actions/LibraryActions.test.ts:26:65)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.498 s
Ran all test suites.
```

### Expected Behavior

The tests should succeed.  (They do in a non-NextJS13 app that I am trying to convert from).

Additionally, the actual server action being tested works correctly in dev mode -- just cannot set up tests for them.

Also, see a [related docs issue](https://github.com/vercel/next.js/issues/52347) that might be related.  In the absence of a docs page about test setup for the Apps Router, I just followed the instructions for the Pages Router.

### Which browser are you using? (if relevant)

Not relevant to this issue.  Running from shell command line.

### How are you deploying your application? (if relevant)

Not relevant to this issue.  Running from shell command line.

**Comment by craigmcc** [comment]
For some reason I cannot edit the "repro" instructions.  After downloading and installing, you'll also need to:
* Set up an empty database.
* Configure an appropriate DATABASE_URL entry in a ".env" file.  (I use Postgres but it probably does not matter.)
* Run shell command "prisma db push" to configure the database schema.

**Comment by balazsorban44** [comment]
Duplicate/related to #47448, so closing in favor. Thanks for reporting!
