### ISSUE TITLE
Parallel routes within catchall routes are not rendered unless there is another catchall children routes

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#52441]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.10-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Fredkiss3/next-parallel-catchall-bug

### To Reproduce

1. clone and start the server
2. Click on the link to `/a`, you will see the text under `Parellel` says `HOME - PARALLEL` 
3. Click on the link to `/b` you will see the text under `Parellel` says `GOTTA CATCH EM ALL ! (PARALLEL)`

### Describe the Bug

It is said in the documentation that you can use catchall routes with parallel routes : 

> If you want to navigate elsewhere and dismiss a modal, you can also use a catch-all route.

https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#dismissing-a-modal 

However when using it, they don't appear unless there is another catchall route as children routes. You can even experiment by deleting the folder at `/app/[...catchAll]` and now the catchall routes under parallel routes will never show anymore.

I also tried using optional catchall routes within the parallel routes (`[[..catchall]]`) but it gave me this error : 
```
Error: You cannot define a route with the same specificity as a optional catch-all route ("/" and "/[[...catchall]]").
``` 

### Expected Behavior

I would have expected catchall routes to work without any hack.

**Comment by Terro216** [comment]
ran into the same bug

**Comment by Fredkiss3** [comment]
i'm closing this in favor of #49531
