### ISSUE TITLE
`generateMetadata` / `metadata` causes warnings in browser devtools

### ISSUE THREAD

**Issue by grzegorzpokorski** [vercel/next.js#52454]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.11.0
      npm: 8.19.2
      Yarn: N/A
      pnpm: 8.6.0
    Relevant Packages:
      next: 13.4.10-canary.0
      eslint-config-next: 13.4.10-canary.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/grzegorzpokorski/nextjs-meta-tags-issue

### To Reproduce

1. Build and run project (`pnpm build && pnpm start`) OR run development server (`pnpm dev`).
2. Go to `/` route.
3. Click "Link to /nested" or "Link to /nested/route" link.
4. Click "Link to /" link.
5. Click "Link to /nested" or "Link to /nested/route" link.
6. Now open console from devtools in browser.
7. You should receive in console a warnings like on screenshot below:

![image](https://github.com/vercel/next.js/assets/27455716/79a1e87d-dbc2-4ca3-be25-76176a8a6bce)

### Describe the Bug

I define some of meta data using `generateMetadata` function which are different on pages of the website. When I go through pages like in steps which I provided in "To reproduce" section I recieve browsers warnings about each attribute passed to `metadata.robots.googleBot` object like so: "The key "`metadata.robots.googleBot.*`" is not recognized and ignored."
This behaviour apears in spacyfic cases, but mostly when in nested routes `generateMetadata` function returns more attributes than `/` route.

Worthy mention is that this bug occurs only when I go from `/` route to any nested route as in example: `/nested` or `/nested/route` using links from `next/link`. When I go from `/nested` page to `/nested/route` and vice versa warnings in console does not appear.

No matter if I use `genetateMetadata` or `metadata` - in both cases I recieve the same warnings in browser console.

### Expected Behavior

No browser errors / warnings in the console.

### Which browser are you using? (if relevant)

Chrome 114.0.5735.199

<sub>[NEXT-1420](https://linear.app/vercel/issue/NEXT-1420/generatemetadata-metadata-causes-warnings-in-browser-devtools)</sub>

**Comment by madfcat** [comment]
I was getting the same error. I think I have found a solution for my case.

In my case, I was fetching metadata from the server dynamically in the generateMetadata function. For some pages "description" was empty. In this case, `<meta name="description">` tag was not present.

So when I came to this page from the page which had meta description, I was getting the same error as in the authors post "The key "some key" is not recognized and ignored.". I have added " " string to the cases when the meta desciption was getting "" (empty string) and the warning gone.
Now, for the pages, which had previously no `<meta name="description">` tag at all, I have `<meta name="description" content=" ">`.

And it silences the error.

From my understanding, travelling from one page to another, the framework tries to compare the DOM, it can not find corresponding tag and just argues about this.

**Comment by huozhi** [comment]
This issue needs some updates from react side to avoid DOM throwing the warnings.

**Comment by Zerebokep** [comment]
I receive the same warning when generating dynamic titles and descriptions using generateMetadata.

**Comment by grzegorzpokorski** [comment]
I checked if there's any change by testing on `next@14.0.4`, and it appears that this issue has been resolved

**Comment by huozhi** [comment]
Thanks for checking! 🙏
