### ISSUE TITLE
Docs: unsupported features for listed deployment providers

### ISSUE THREAD

**Issue by angelovdev** [vercel/next.js#52470]
### What is the improvement or update you wish to see?

I would like to see what is and isn't supported (mainly ISR/On-Demand Regeneration/Image caching) in the deployment providers listed at https://nextjs.org/docs/app/building-your-application/deploying#other-services

In particular, I am looking for Google Cloud Run but would be nice to have info about the rest as well.

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/deploying#other-services

<sub>[DX-1757](https://linear.app/vercel/issue/DX-1757/docs-unsupported-features-for-listed-deployment-providers)</sub>

**Comment by leerob** [comment]
All features are supported on Google Cloud Run, because it's using `next start`. Above, it says:

> You can self-host Next.js with support for all features using Node.js or Docker.

Then below, we also say:

> Good to know: Not all serverless providers implement the [Next.js Build API](https://nextjs.org/docs/app/building-your-application/deploying#nextjs-build-api) from next start. Please check with the provider to see what features are supported.

I'm happy with this currently 🙏
