### ISSUE TITLE
Docs: Mobile navigation is not displayed when the viewport width falls within a specific range.

### ISSUE THREAD

**Issue by grzegorzpokorski** [vercel/next.js#52476]
### What is the improvement or update you wish to see?

I would like to be able to access the mobile menu of the nextjs.org website when I switch my smartphone to horizontal mode. Currently, this is not possible because the "desktop" version of the navigation hides at viewport widths below 1021px, while the "mobile" version of the navigation does not appear when I toggle the navigation trigger button within the viewport width range of 890px to 1020px.

### Is there any context that might help us understand?

All above is about main menu of the website not navigation of the docs.

<sub>[DX-1756](https://linear.app/vercel/issue/DX-1756/docs-mobile-navigation-is-not-displayed-when-the-viewport-width-falls)</sub>

**Comment by balazsorban44** [comment]
Thanks for reporting, this is fixed now, and will be out "soon".
