### ISSUE TITLE
Can't load async server component in dev mode

### ISSUE THREAD

**Issue by alexeygorbachevskiy** [vercel/next.js#52502]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next version: 13.4.9

"dev": "next dev -p 9001 | local-ssl-proxy --key .cert/key.pem --cert .cert/cert.pem --source 9000 --target 9001"

The issue is being reproduced only in dev mode. Everything is working if i'm  starting my vercel build.
```

### Link to the code that reproduces this issue or a replay of the bug

See "To Reproduce" section

### To Reproduce

```
const ServerComponent = async () => {
  let data: Data[] = [];

  try {
    data = await fetchData();
  } catch (err) {
    //
  }

  return <ClientComponent data={data} />;
};
-----------------------------------------------------------------------

"use client";
................imports.............................
const ClientComponent: FC<Props> = ({data}) => {
.......................... code...............................
};
```

### Describe the Bug

When i route to server component described above the page gets infinite loading in dev mode.

### Expected Behavior

The page should correctly been appeared without endless loading in dev mode.

**Comment by alexeygorbachevskiy** [comment]
@balazsorban44

**Comment by alexeygorbachevskiy** [comment]
@balazsorban44  Are u sure u read the environment info with attention? The issue appears exactly only with  `local-ssl-proxy`

**Comment by balazsorban44** [comment]
If that's part of the reproduction, it's fine, but still provide the whole code base, not just snippets. Thanks!
