### ISSUE TITLE
[App Router] Layout children is not a valid React element when using custom `not-found` file

### ISSUE THREAD

**Issue by arobert93** [vercel/next.js#52513]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.10-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/epic-thunder-46rv35

### To Reproduce

* Create a client (`'use client'`) component (`ThemeProvider`) that accepts `children` prop. Before returning the children, check if the prop is a valid React element. If invalid, return an error message as text node, otherwise return it in a `React.Fragment`.
* In `app/layout.tsx` wrap the `children` with `ThemeProvider`.
* Create a `app/not-found.tsx` page that returns a simple dom node.
* Navigate to a page that does not exist and you should now see that the ThemeProvider renders the error text node.

### Describe the Bug

When using a custom `not-found` file, the children passed to the layout is not a valid React element.

### Expected Behavior

I expect a React element to be able to pass it to my ThemeProvider.

I need it to be valid because I'm passing it to a 3rd-party library that handles it and it checks it internally.

**Comment by balazsorban44** [comment]
Hi, so this is expected as per the React documentation: https://react.dev/reference/react/isValidElement#checking-if-something-is-a-react-element

> Any other values, such as strings, numbers, or arbitrary objects and arrays, are not React elements.

`children` can possibly be an array, so the check will return `false` accordingly.
