### ISSUE TITLE
Docs: "Dynamic Routes" title are not appropriate

### ISSUE THREAD

**Issue by takefumi-yoshii** [vercel/next.js#52512]
### What is the improvement or update you wish to see?

As below page shows, `dynamic route` is now used to point to a route that returns a dynamic rendering.
https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering

In App Router docs, we should provide page "Dynamic Segments" instead of "Dynamic Routes".

### Is there any context that might help us understand?

https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes

**Comment by balazsorban44** [comment]
The naming corresponds to other Routing related topics in the docs, eg. "Parallel Routes", "Intercepting Routes", "Nested Routes", etc. https://nextjs.org/docs/app/building-your-application/routing#next-steps

So I think this is correct, but thanks!
