### ISSUE TITLE
Docs: A wrong hyperlink

### ISSUE THREAD

**Issue by whi-sper** [vercel/next.js#52528]
### What is the improvement or update you wish to see?

In [this page](https://nextjs.org/learn/basics/data-fetching/with-data) there is a hyperlink for Static Generation, I think it points to the wrong url.

### Is there any context that might help us understand?

https://nextjs.org/docs/pages/building-your-application/rendering/static-site-generation

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/data-fetching/with-data

**Comment by balazsorban44** [comment]
Thanks for reporting, this is fixed now, and will be out "soon".
