### ISSUE TITLE
Docs: Notation of "dynamic route" is confusing

### ISSUE THREAD

**Issue by takefumi-yoshii** [vercel/next.js#52545]
### What is the improvement or update you wish to see?

In this page, `"Dynamic Routes"` notation used for URL including `"Dynamic Segments"`.
https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes

And in this page same notation is used for dynamically rendered route.
https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering

What about fixing it like this:

```diff
- - In a static route, components are rendered on ...
- - In a dynamic route, components are rendered on ...
+ - In a statically rendered route, components are rendered on ...
+ - In a dynamically rendered route, components are rendered on ...
```

Best regurds.

### Is there any context that might help us understand?

https://github.com/vercel/next.js/issues/52512

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic-rendering

**Comment by leerob** [comment]
^ was covered in the referenced PR.
