### ISSUE TITLE
Server Component is not suspended in dynamically rendered page when fetch revalidate > 0

### ISSUE THREAD

**Issue by rinald-ta** [vercel/next.js#52572]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.10-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/blissful-volhard-8c6c9d?file=%2Fapp%2Fpage.tsx%3A15%2C26

### To Reproduce

To reproduce, paste this code to a `page.tsx` or `page.js` file

```tsx
import { Suspense } from "react";

import { headers } from "next/headers";

const Component = async () => {
  const data = await fetch(
    "https://official-joke-api.appspot.com/random_joke",
    {
      next: { revalidate: 1 }, // replace with 0 to make Suspense work
    }
  ).then((res) => res.json());

  return (
    <div>
      <p>{data.setup}</p>
      <p>{data.punchline}</p>
    </div>
  );
};

const Page = () => {
  // force dynamic rendering
  headers();

  return (
    <Suspense fallback={<div>Loading...</div>}>
      {/* @ts-ignore */}
      <Component />
    </Suspense>
  );
};

export default Page;
```

Here, `Component` is an async server component that fetches some data and caches it for 1 second. The page component uses the `headers()` dynamic function to force dynamic rendering. A suspense boundary is added to show instant loading UI. 

### Describe the Bug

The issue is that `Component` isn't suspended when `fetch` is configured with a revalidation other than 0. Because of this, the suspense boundary never shows the fallback component, and the page is always blocked until the fetch request is resolved.

### Expected Behavior

The component should be suspended on dynamically rendered pages and any loading UI should render as expected, even when cached fetch requests are used (suspend only when there is a cache MISS, i.e. after the revalidation period).

### Which browser are you using? (if relevant)

Microsoft Edge
Version 114.0.1823.79 (Official build) (arm64)

### How are you deploying your application? (if relevant)

`next start`

**Comment by darshanjain-entrepreneur** [comment]
Hey  ,the  component is not suspended because In Next.js, the Suspense component is not natively supported for data fetching with revalidate: 1

**Comment by darshanjain-entrepreneur** [comment]
you can use swr if you want to dynamically update your data.
import useSWR from "swr";

const Component = () => {
  const { data, error } = useSWR(
    "https://official-joke-api.appspot.com/random_joke",
    { revalidateOnMount: true, refreshInterval: 1000 }
  );

  if (error) {
    return <div>Error occurred while fetching data.</div>;
  }

  if (!data) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <p>{data.setup}</p>
      <p>{data.punchline}</p>
    </div>
  );
};

const Page = () => {
  return (
    <div>
      <Component />
    </div>
  );
};

export default Page;

**Comment by darshanjain-entrepreneur** [comment]
you can also use react component to do the same thing .
`import { useState, useEffect } from "react";

const Component = () => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        "https://official-joke-api.appspot.com/random_joke"
      );
      const jsonData = await response.json();
      setData(jsonData);
      setLoading(false);
    };

    fetchData();
  }, []);

  if (loading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>Error occurred while fetching data.</div>;
  }

  return (
    <div>
      <p>{data.setup}</p>
      <p>{data.punchline}</p>
    </div>
  );
};

const Page = () => {
  return (
    <div>
      <Component />
    </div>
  );
};

export default Page;`

**Comment by rinald-ta** [comment]
> Hey ,the component is not suspended because In Next.js, the Suspense component is not natively supported for data fetching with revalidate: 1

Any reasons as to why this is? This isn't documented anywhere. Next.js docs on Streaming and loading UI don't really go into much details: [https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming](url)

**Comment by rinald-ta** [comment]
I would assume that the issue happens because the requests are always marked as `cache: HIT`, although the actual page response times say otherwise.

<img width="600" alt="Screenshot 2023-07-13 at 23 21 00" src="https://github.com/vercel/next.js/assets/92527147/17bb7786-ac3f-4617-a1ef-e8d5c52eff3f">
