### ISSUE TITLE
Next 13.4.10-canary.3 Standalone mode breaks app

### ISSUE THREAD

**Issue by khuezy** [vercel/next.js#52615]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

[Reproduction Repo](https://github.com/khuezy/sst-next-10)

### To Reproduce

This setup deploys Nextjs as a standalone app running on AWS. So you need to have your ~/.aws/credentials set up in order to deploy the app

1) `pnpm install`
2) `npx sst deploy --stage dev`
3) wait for deployment
4) go to the outputted CloudFront URL
5) Notice `Internal Server Error`
6) Check CloudWatch logs, it should be something like the logs below
7) to clean up, run `npx sst remove --stage dev`

Question: Why is it trying to load `react/jsx-runtime`?

@logStream    
2023/07/13/[$LATEST]aaa75d180aaf...
@message    
2023-07-13T00:37:28.806Z    undefined    ERROR    Failed to override Next.js require hooks. Error: Cannot find module '/var/task/node_modules/react/jsx-runtime.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)
    at resolveExports (node:internal/modules/cjs/loader:565:14)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at /var/task/node_modules/next/dist/server/require-hook.js:1:3469
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at hse (file:///var/task/packages/app/index.mjs:31:7405)
    at gj (file:///var/task/packages/app/index.mjs:31:7019)
    at file:///var/task/packages/app/index.mjs:31:10451 {
  code: 'MODULE_NOT_FOUND',
  path: '/var/task/node_modules/react/package.json'
}

### Describe the Bug

Most likely introduced in this PR: https://github.com/vercel/next.js/pull/52206

### Expected Behavior

Standalone deployments should work. `13.4.10-canary.2` works but not 3 and above.

### How are you deploying your application? (if relevant)

Deploying Standalone Mode to AWS via SST and OpenNext

**Comment by khuezy** [comment]
If the removal of the jsx-runtime is intentional, then I'll close this issue.

**Comment by feedthejim** [comment]
@khuezy can you provide a repro that does not involve SST to help us triage if it's a SST bug or not?

**Comment by wssjq198913** [comment]
@khuezy  i have exactly the same issue, don't know what to do.

**Comment by khuezy** [comment]
@feedthejim thanks for replying. I'll close this as it's not a nextjs issue.

@wssjq198913 if you're using SST, this PR should fix it: https://github.com/serverless-stack/open-next/pull/159
