### ISSUE TITLE
Dynamic app routing working fine on dev mode, but in production It returns 404 not found. 

### ISSUE THREAD

**Issue by anasbinsabiet** [vercel/next.js#52617]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.18.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: export
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/anasbinsabiet/demo

### To Reproduce

https://demo9999.netlify.app/service

when click the Service 1 or Service 2 or Service 3 from menu, it returns 404 not found.
but it works fine on development mode in locally.

### Describe the Bug

https://demo9999.netlify.app/service

when click the Service 1 or Service 2 or Service 3 from menu, it returns 404 not found.
but it works fine on development mode in locally.

### Expected Behavior

It should show the details page as it shows in locally.

**Comment by rexfordessilfie** [comment]
Related https://github.com/vercel/next.js/issues/52381
