### ISSUE TITLE
Using fetch with formData inside a Route Handler never returns

### ISSUE THREAD

**Issue by rafma0** [vercel/next.js#52616]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 11 Pro
    Binaries:
      Node: 20.4.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/rafma0/nextjs-route-fetch

### To Reproduce

1. run the repro code
2. try to post a file to /api/local-image

![image](https://github.com/vercel/next.js/assets/28578847/f839571b-2a9c-4feb-9169-eec67445f531)

### Describe the Bug

What I'm trying to do is "redirect" an image upload from the next **Route Handler** to an external API. The same code was working correctly before **Node.js** got updated to **20.4.0**.

When I try to post a file larger than 100kb (or maybe even 64kb?) the route never returns, and after 5 min I get something like this in the console

```sh
-  ┌ POST /api/local-image 408 in 317428ms
   │
   └──── POST http://localhost:3000/api/external-image 408 in 317402ms (cache: MISS)

- error Error: aborted
    at connResetException (node:internal/errors:720:14)
    at abortIncoming (node:_http_server:782:17)
    at socketOnClose (node:_http_server:776:3)
    at Socket.emit (node:events:524:35)
    at TCP.<anonymous> (node:net:334:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
```

(Tested on Windows 11 Pro and Debian)

local-image/route.tsx
```ts
export async function POST (request: Request) {
  const body = await request.formData()

  const res = await fetch('http:/localhost:3000/api/external-image', {
    method: 'POST',
    body
  })

  return new Response(res.body, { status: res.status })
}
```

To simulate the external API I created a simple route external-image/route.tsx in the repro with
```ts
export async function POST (request: Request) {
  const body = await request.formData()

  console.log(body.get('image'))

  return new Response()
}
```

If you try to post a file larger than 100kb and your next server is using node 20.4.0, you will never see the console.log. Post a really small file or run the server in node 20.3.1 and everything should work as expected.

### Expected Behavior

Described in the bug

<sub>[NEXT-1438](https://linear.app/vercel/issue/NEXT-1438/using-fetch-with-formdata-inside-a-route-handler-never-returns)</sub>

**Comment by rafma0** [comment]
| Next.js | Node.js | Status |
|--------|--------|--------|
| 13+ | 20.3.1 | ✔️ |
| 13.4.10-canary.5 | 20.4.0 | ❌ |
| 13.4.12-canary.0 | 20.5.0 | ❌ |

**Comment by mchawande** [comment]
`Redirect` is not working for `POST` route handler.

**Comment by rafma0** [comment]
Hi @leerob, I just tried the code from my repro (updating next to 13.4.20-canary.9) and nodejs 20.5.1 and the behaviour is exact the same. Latest canary with nodejs 20.3.1 still works fine.

**Comment by Jyrno42** [comment]
I have encountered similar behaviour with using `request.json()` and not supplying a content-type header (browser automatically set it to `text/plain`). The request just hangs until the timeout and then responds with a 408 timeout error.

This may be related to this issue but I am unsure. Once I am done with the feature I am working on I shall file that as a separate issue after I have reproed it on canary.

**Comment by rafma0** [comment]
Okay, it looks like the issue was fixed in Node.js 20.6.0. I tried the latest Next.js with Node.js 20.5.1, and the request still never returned. However, when I tried it with 20.6.0 and later (including the latest 20.8.0), everything seemed to work fine. I'm closing this issue.
