### ISSUE TITLE
The new Link component automatically appends an <a> tag to the child elements, resulting in a change in the style visible to the user. Using legacyBehavior poses no issues

### ISSUE THREAD

**Issue by fzxbl** [vercel/next.js#52618]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
    Binaries:
      Node: 20.3.1
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A


warn  - Failed to fetch latest canary version. (Reason: Cannot read properties of undefined (reading 'tag_name').)
      Detected "13.4.9". Visit https://github.com/vercel/next.js/releases.
      Make sure to try the latest canary version (eg.: `npm install next@canary`) to confirm the issue still exists before creating a new issue.
      Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/fzxbl/issue_about_link_in_nextjs

### To Reproduce

**When I use the new <Link>，I got a page like this:**
![image](https://github.com/vercel/next.js/assets/31810871/97d9a50d-1f23-4f64-8ad1-d3b4741b9f80)

**When I use the legacyBehavior atrribute, I got a page like this, which means theres is an obvious diffrence between the last version of <Link> and the now version of  <Link>**
![image](https://github.com/vercel/next.js/assets/31810871/37572911-1ba2-473e-94cb-089dc70f0143)

**This is a related commit, which maybe will help it**
[https://github.com/vercel/next.js/commit/489e65ed98544e69b0afd7e0cfc3f9f6c2b803b7](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

### Describe the Bug

The new version of the <Link> component wraps child elements with `<a>`, but this causes a change in the styles of the child elements.

### Expected Behavior

The new version of the <Link> component will not change in the styles of the child elements.

### Which browser are you using? (if relevant)

Edge 114.0.1823.67 (arm64)

### How are you deploying your application? (if relevant)

next start

**Comment by balazsorban44** [comment]
From the code provided, this seems to be expected. The current implementation is that `Link` is going to be created as an `a` element, 
https://github.com/vercel/next.js/blob/c56915842a41ce5cd1328b36dff44004352c9f15/packages/next/src/client/link.tsx#L746-L752 which is the correct way of creating links. The old link markup does not have `a` elements for links, which is semantically incorrect anyway.

Read more: https://nextjs.org/blog/next-13#breaking-changes
