### ISSUE TITLE
fast refresh performs full slow compile for every change in local dev - pages router - as of 13.4.8

### ISSUE THREAD

**Issue by samcarton** [vercel/next.js#52623]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

none

### To Reproduce

- on pages router, with middleware
- on a page with a dynamic page route
- edit a react component and make a minor change that would normally be handled by a simple fast refresh (1-2seconds)
- notice that it recompiles all 13k modules and takes 60+ seconds 

### Describe the Bug

What used to be a quick dev experience has degraded since 13.4.8. Minor changes to react components no longer perform an actual _fast_ refresh - instead of taking 2s, the compile takes as much as a fresh build (60-120s). Yes I have confirmed all [these fast refresh criteria](https://nextjs.org/docs/messages/fast-refresh-reload) are met. This was behaving as expected prior to 13.4.8 - I rolled back version by version to confirm, where only the nextjs version was changing and our code was staying exactly the same.  

The below is an example of the compile that used to take 1-2s, now taking 2 minutes.

```
- wait compiling /my/route/[someId] (client and server)...
- event compiled client and server successfully in 117.8s (13785 modules)
```

### Expected Behavior

Fast refresh should be fast.
```
- wait compiling /my/route/[someId] (client and server)...
- event compiled client and server successfully in 1s (13785 modules)
```

### How are you deploying your application? (if relevant)

local dev

**Comment by balazsorban44** [comment]
Actually, let me close this in favor of https://github.com/vercel/next.js/issues/48748#issuecomment-1578374105. Please visit that issue and follow the instructions to help us investigate. Post your results there.

**Comment by samcarton** [comment]
@balazsorban44 as I understand it, that issue is regarding the slow compile times in general - on initial load and page navigation. The issue I'm seeing is specifically around fast refresh behaviour that was (until recently) working fine. I will try to make a repro. If the compile times were 90% faster it'd still be too slow for a fast refresh.
