### ISSUE TITLE
Intercepting route modal does not work with basepath 

### ISSUE THREAD

**Issue by Uy575** [vercel/next.js#52624]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.7
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

Nextgram

### To Reproduce

should make intercepting route keep working with basepath

### Describe the Bug

i created a modal using intercepting route and parallel route but when we set basepath intercepting route stop working

### Expected Behavior

modal should act as a intercepting route after a basepath added

### Which browser are you using? (if relevant)

google chrome

### How are you deploying your application? (if relevant)

production

<sub>[NEXT-1439](https://linear.app/vercel/issue/NEXT-1439/intercepting-route-modal-does-not-work-with-basepath)</sub>

**Comment by BStoller** [comment]
Any updates on this? I really would like to use this routing for one of my apps.

**Comment by Uy575** [comment]
> Any updates on this? I really would like to use this routing for one of my apps.

No, still not fixed. its working fine without basepath, but with basepath still broken.

**Comment by BStoller** [comment]
@balazsorban44 any suggestions on possible solutions?

**Comment by uyeong** [comment]
I'm having the same problem and it hasn't been fixed yet. 

I'm hoping there's a workaround, even if it's a bit tricky. 

I've created a repository that reproduces the issue. It's https://github.com/uyeong/nextgram.

**Comment by hsuanyi-chou** [comment]
really need this feature.
When will nextjs fix this issue?

**Comment by treepo1** [comment]
any updates on this?

**Comment by leerob** [comment]
Could we get a minimal reproduction? I see nextgram is linked, but there's also additional stuff added there. A minimal version would be very helpful to pinpoint the issue.

**Comment by klarstrup** [comment]
Here you go @leerob: https://github.com/klarstrup/Intercepting-route-modal-does-not-work-with-basepath

Comment or uncomment `baseDir` in next.config.js and visit http://localhost:3000/ or http://localhost:3000/sub-directory respectively. The prior will have the expected behavior of the links on the demonstration images will be intercepted and result shown in modal - whereas in the latter a typical navigation will happen without interception.

**Comment by samcx** [comment]
@klarstrup Thank you for the <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture>! I was able to replicate the issue. I will be sharing this with the team so we can take a look!

**Comment by Uy575** [comment]
@leerob  @samcx  hey here is your own repo nextgram https://github.com/Uy575/Next_intercepting_and_parallel_route_issue.git 
i just add a next config file with basepath named "/testing".
you can comment and uncomment  basepath in nextconfig file to point the issue, it has different behaviour with basepath commenting and uncommenting.

**Comment by Uy575** [comment]
@leerob @samcx  hey here is your own repo nextgram https://github.com/Uy575/Next_intercepting_and_parallel_route_issue.git 
i just added a next config file with basepath named "/testing".
you can comment or uncomment  basepath in nextconfig file to point the issue, it has different behaviour with basepath commenting or uncommenting.
