### ISSUE TITLE
node-cache data is automatically lost aftersome time 

### ISSUE THREAD

**Issue by prakashn91** [vercel/next.js#52638]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Hi Guys, I just migrate my one-service digital ocean to Vercel, but unfortunately, my cache data is lost after some time automatically
and on digital ocean the cache works fine

Please help me if anyone face the same kind of issue
```

### Link to the code that reproduces this issue or a replay of the bug

node-cache npm 

### To Reproduce

data automatically lost after sometime

### Describe the Bug

I just migrate my one-service digital ocean to Vercel, but unfortunately, my cache data is lost after some time automatically

### Expected Behavior

data will be persist unit the server restart or anyone reset the data

**Comment by balazsorban44** [comment]
Hi, unlike Digital Ocean, Vercel is a serverless platform, meaning it will scale down to zero when not in use, losing any in-memory cache. You can use something like https://vercel.com/docs/storage/vercel-kv to persist cache across serverless restarts.

This is not related to Next.js, so closing the issue.
