### ISSUE TITLE
Metadata not working for not found page

### ISSUE THREAD

**Issue by mehmetext** [vercel/next.js#52636]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112
    Binaries:
      Node: 19.4.0
      npm: 9.4.2
      Yarn: 1.22.19
      pnpm: 8.6.5
    Relevant Packages:
      next: 13.4.10-canary.6
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Metadata (metadata, generateMetadata, next/head)

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app -e reproduction-template

### To Reproduce

.

### Describe the Bug

I want to add metada to not-found page but it doesn't work. 
<img width="215" alt="Ekran Resmi 2023-07-13 14 23 05" src="https://github.com/vercel/next.js/assets/44941107/82a74541-4698-4b5b-b137-2ebed704af19">

<img width="408" alt="Ekran Resmi 2023-07-13 14 23 18" src="https://github.com/vercel/next.js/assets/44941107/77dad2b1-1119-43ec-b053-8431410b0e3b">

<img width="307" alt="Ekran Resmi 2023-07-13 14 23 28" src="https://github.com/vercel/next.js/assets/44941107/004ea028-b6b3-4f3d-92d7-fce67a3060c8">

So, how can I add metadata to not-found.tsx?

### Expected Behavior

.

### Which browser are you using? (if relevant)

Google Chrome

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1446](https://linear.app/vercel/issue/NEXT-1446/metadata-not-working-for-not-found-page)</sub>

**Comment by nicksan222** [comment]
Why would you want to do that?

**Comment by darshanjain-entrepreneur** [comment]
here only page.tsx works

**Comment by emondpph** [comment]
Yeah I had the same issue, we should be able to add a title tag even if it's a 404 page

**Comment by mehmetext** [comment]
> Why would you want to do that?

Because I want to show a title for the user :) I think that it's a user experience. Also, there is a title in default 404 not found page. I want to customize it.
