### ISSUE TITLE
The swcPlugins are causing "tree shaking" to be ineffective, which seems like a bug.

### ISSUE THREAD

**Issue by coder-xiaotian** [vercel/next.js#52679]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.15
      pnpm: 6.11.0
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.4.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/coder-xiaotian/layzy-cut

### To Reproduce

I used my custom swc plugin [use-client](https://github.com/coder-xiaotian/swc-useclient) in the lazy-cut project, When executing "pnpm analyze," it was found that all components of @mui/material are being bundled, but removing the "use-client" plugin resolves this issue.

### Describe the Bug

With "use-client" enabled:
<img width="879" alt="image" src="https://github.com/vercel/next.js/assets/22257014/6218cb42-e2b1-4725-b31d-f52ff849a248">

Without "use-client":
<img width="884" alt="image" src="https://github.com/vercel/next.js/assets/22257014/ce4b69eb-77f6-4951-9aa8-9ffd4bd23170">

### Expected Behavior

I sought help from the SWC community, and they mentioned that this appears to be a bug in Next.js.
<img width="650" alt="image" src="https://github.com/vercel/next.js/assets/22257014/f022c759-aef4-4d0e-bce9-c99b6dd5466d">

### Which browser are you using? (if relevant)

Chrome 114.0.5735.198

**Comment by shuding** [comment]
This is expected at the moment. Exports crossed the first client boundary can't be free-shaken. We will look into improving it in the future.
