### ISSUE TITLE
Typescript types for `NextApiRequest` are missing properties

### ISSUE THREAD

**Issue by ryami333** [vercel/next.js#52682]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10-canary.8
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/crimson-frost-kltdh3?file=%2Fapp%2Fapi%2Ffoo%2Froute.ts%3A5%2C1

### To Reproduce

```ts
import { NextApiHandler } from "next";

export const GET: NextApiHandler = (request, response) {
    console.log(request.nextUrl); // error TS2339: Property 'nextUrl' does not exist on type 'NextApiRequest'.

    return response.json({ hello: "world"})
}
```

### Describe the Bug

When trying to access the property `nextUrl` on an object of type `NextApiRequest`, I receive the Typescript error `error TS2339: Property 'nextUrl' does not exist on type 'NextApiRequest'.`. However, when I log this to the console, it becomes apparent that the property _does_ exist as described in https://nextjs.org/docs/pages/api-reference/functions/next-server.

### Expected Behavior

I should not get an error when correctly accessing properties which do exist on NextApiRequest.

**Comment by balazsorban44** [comment]
Route Handlers (App Router) have a different syntax then API routes (pages directory), read more about it in the docs: https://nextjs.org/docs/app/building-your-application/routing/router-handlers
