### ISSUE TITLE
Next.js 13.4.10 breaks `Intl.DateTimeFormat` formats in production builds

### ISSUE THREAD

**Issue by suneettipirneni** [vercel/next.js#52698]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 3.5.1
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/suneettipirneni/site

### To Reproduce

When running the website in dev mode the homepage shows my localized time formatted as HH:MM AM/PM.
This is expected as per the code for this is defined here: https://github.com/suneettipirneni/site/blob/78b55a7c50cc990cba864e69bc84da551f798c5a/components/Profile.tsx

However, when building and running a production build via `yarn build`, the time displayed on the homepage is shown in the format of DD/MM/YY, which was not the format specified in the code.

### Describe the Bug

In the previous next.js version 13.4.9, both the local dev and production build properly showed the correct format using the `Intl.DateTimeFormat` API. In the latest version the production build gives the incorrect format.

### Expected Behavior

The production build of the next app should give the proper format for the date using the `Intl.DateTimeFormat` API.

### Which browser are you using? (if relevant)

Version 114.0.5735.198 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

Vercel

**Comment by scottbert** [comment]
This also affects `Intl.NumberFormat`. Under `13.4.10` and above:

```typescript
const options = {
  style: 'currency',
  currency: 'GBP'
};

new Intel.NumberFormat('en-US', options).format(1.99); //returns 1.9

Intel.NumberFormat('en-US', options).format(1.99); //returns £1.90
```
Interesting that the `new` keyword seems to break it.

**Comment by scottbert** [comment]
Also to verify the issue still exists in `next@13.4.13-canary.11`

**Comment by scottbert** [comment]
Also, and this is super annoying, I cannot reproduce this in a vanilla typescript create next-app application. I did notice that if I turn off swcMinify in next.config then everything works again

**Comment by scottbert** [comment]
More notes. Deployed the site to production this morning with Nextjs `13.4.12` and `swcMinify: false` and unexpectedly found that the prices were broken again, even though this worked when doing production builds locally, so am at a loss. Downgraded to `.9`

**Comment by suneettipirneni** [comment]
I've tested this once again in next.js `13.4.19`, the issue seems to no longer be present.
