### ISSUE TITLE
Module not found: Can't resolve 'antd/lib/qr-code'

### ISSUE THREAD

**Issue by zombieJ** [vercel/next.js#52703]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.10-canary.8
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.10-canary.8", newest: "13.4.10".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/github/alyosha-30emeciel/antd-qrcode-bug/csb-6xksxs/draft/happy-burnell?file=/package.json:18,20

### To Reproduce

just run `npm start`

### Describe the Bug

<img width="554" alt="截屏2023-07-15 10 08 05" src="https://github.com/vercel/next.js/assets/5378891/2a4c6c06-eab3-4f3b-920a-2d7dac96e611">

### Expected Behavior

QRCode path should be `qrcode`, not `qr-code`. NextJS convert to the wrong path.

**Comment by naveen8801** [comment]
Hi @zombieJ, I'd like to check it, is this issue open?

**Comment by zombieJ** [comment]
@naveen8801  Please feel free to help on this : )

**Comment by naveen8801** [comment]
@zombieJ, I think I have found the exact reason behind this behavior. Please check config.ts [here](https://github.com/vercel/next.js/blob/7ce663ed52a881ffb3fa38e50ff5d6e135293fbf/packages/next/src/server/config.ts#L693) and example for this config is [here](https://github.com/vercel/next.js/blob/7ce663ed52a881ffb3fa38e50ff5d6e135293fbf/docs/04-architecture/nextjs-compiler.mdx#L304)

```kebabCase``` related change was introduced 2 weeks ago [PR link](https://github.com/vercel/next.js/pull/52148)

**Comment by alyosha-30emeciel** [comment]
May I try to add an exception in my project's 'next.config.js' file as a workaround ?
I'm not sure about how it works. Maybe this?
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
    modularizeImports: {
        'antd/lib/QRCode': {
            transform: 'antd/lib/qrcode',
        },
    },
}

module.exports = nextConfig
```

**Comment by zombieJ** [comment]
In most case, naming can be `kebabCase`. But `QRCode` is not kebabCase as `qr-code` in antd path.

**Comment by balazsorban44** [comment]
Related/duplicate issue: #52307 I'm going to close this in favor, feel free to comment further there!
