### ISSUE TITLE
Server start (next start) uses HTTP to communicate between threads

### ISSUE THREAD

**Issue by davidbarratt** [vercel/next.js#52702]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
Binaries:
  Node: 18.16.1
  npm: 9.5.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.4.7
  eslint-config-next: 13.4.7
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, CLI (create-next-app), Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

next start

### To Reproduce

Run `next-start` and with something to instrument outbound HTTP requests (i.e. New Relic) and you should see something like this:
![Screenshot 2023-07-14 at 9 35 22 PM](https://github.com/vercel/next.js/assets/868364/933cda39-4e4a-4f2a-a9af-f59b1b185245)

### Describe the Bug

In https://github.com/vercel/next.js/commit/fdacca8abc424288e95c65fe31d1d28d479adc36 `next start` started using workers in order to seperate out the rendering and routing logic into seperate threads for the purposes of isolation. This seems sensible, however, the the mechanism chosen to message between the threads is.... HTTP. While that is a wonderful protocol to message between applications/processes, it incures a significant amount of overhead that is completely unnecessary to communicate between threads of the same process.

### Expected Behavior

I expected Next.js to listen to HTTP requests on the single, specified port and use [worker.postMessage()](https://nodejs.org/api/worker_threads.html#workerpostmessagevalue-transferlist) to forward a request to a specific worker and then listen for a response with the [`message` event](https://nodejs.org/api/worker_threads.html#event-message_1). The main thread will need to keep track of it's sent requests so it can match them up with respones (which may come back in any order). Alternatively, it's probably accaptable to create a new thread for each incoming request, which might be better anyways for handling the high CPU usage of SSR.

If the goal of this code is _isolation_ rather than _multithreading_, it might be better to use a [Node.js VM](https://nodejs.org/api/vm.html#vm-executing-javascript) in which you could pass an event emitter or even the promise `resolve` callback. This is [how Cloudflare isolates Workers](https://developers.cloudflare.com/workers/learning/how-workers-works/#isolates) from each other.

**Comment by davidbarratt** [comment]
Ping @ijjk

**Comment by colonder** [comment]
@ijjk any solution to this? This really is a big deal for hosting where ports need to be reserved in advance.

**Comment by colonder** [comment]
This has been resolved with next Next.js versions, if you upgrade to the newest one, it works with specifying just one port

**Comment by davidbarratt** [comment]
@colonder which change fixed it?

**Comment by colonder** [comment]
@davidbarratt When I said "upgrade to the newest one" I meant that previously I used 13.4.6 and now I upgraded to 13.4.19 so I can't really tell which change precisely fixed it. I can check which version is the first one that started working as expected.

**Comment by colonder** [comment]
@davidbarratt I found that 13.4.13 is the first version that works as expected, anything before that has this issue with an additional random port. That doesn't mean that everything is cool though - some hostings (like cPanel with Phusion Passenger) still report that there have been multiple calls to `server.listen()` and some kind of proxy is still required. That is still an improvement though since it's much easier to work around having to proxy just one port instead of an additional random one.
