### ISSUE TITLE
Docs: Should add a guide on how to achieve SPA behavior without caching

### ISSUE THREAD

**Issue by masterbater** [vercel/next.js#52704]
### What is the improvement or update you wish to see?

Provide documentation how to achieve SPA behavior, do we need to use revalidate 0 for the directive force-dynamic
Its very hard to know how to achieve properly and we want proper guidance from nextjs team. 

### Is there any context that might help us understand?

Lots of people encounter the caching behavior of nextjs which people are not aware or doesnt know how to opt out properly. Some doesnt work because of soft navigation even with using headers() or cookies()

**Comment by leerob** [comment]
https://github.com/vercel/next.js/discussions/54075
