### ISSUE TITLE
In the React Client Manifest. This is probably a bug in the React Server Components bundler

### ISSUE THREAD

**Issue by JawadFadel** [vercel/next.js#52713]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
\src\widget\layout\AppLayout.tsx
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/assets/59622265/56d4f024-24e3-4c41-85c7-87cfba9016d5

### To Reproduce

![image](https://github.com/vercel/next.js/assets/59622265/56d4f024-24e3-4c41-85c7-87cfba9016d5)

### Describe the Bug

Error: Could not find the module "C:\Users\jawad\Desktop\projects\Rm\rms\src\widget\layout\AppLayout.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

### Expected Behavior

update nextjs to 10

**Comment by mlmetzner** [comment]
I have the same issue when importing a client component in an intercepted/parallel route. In 13.4.10, it wasn't breaking in 13.4.9. But it wasn't working as intended there either, it went directly to the other parallel route.

**Comment by JawadFadel** [comment]
Fixed:  
![image](https://github.com/vercel/next.js/assets/59622265/09edee55-f358-4aa8-8087-72999190813f)
replace folder name from () -> (admin)  new update not support () folder name

**Comment by ambrosebeavers** [comment]
@JawadFadel . I am having the same issue but I am not seeing where your recommendation resolves it. Now both the intercepted route and the regular route is showing up

**Comment by JawadFadel** [comment]
> Fixed: ![image](https://user-images.githubusercontent.com/59622265/253739899-09edee55-f358-4aa8-8087-72999190813f.png) replace folder name from () -> (admin) new update not support () folder name

**https://github.com/vercel/next.js/issues/52713#issuecomment-1636754097**
