### ISSUE TITLE
not-found loses layout

### ISSUE THREAD

**Issue by karlhorky** [vercel/next.js#52718]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.10-canary.8
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/sleepy-leavitt-q76g5v?file=%2Fapp%2Fnot-found.tsx

### To Reproduce

1. Visit the CodeSandbox above
2. Navigate to a not-found page using the link or altering the URL
3. Layout is missing on the not-found page 💥

https://github.com/vercel/next.js/assets/1935696/e6bf4bb1-913d-4f36-9f14-552f1345c68b

### Describe the Bug

The not-found page no longer receives a layout

### Expected Behavior

The not-found page receives a layout

### Related issues / PRs

Possibly related to this issue and the PR addressing it:

1. Issue: https://github.com/vercel/next.js/issues/49115 by @joshwcomeau
2. PR: https://github.com/vercel/next.js/pull/52589 by @huozhi, reviewed by @shuding 

<sub>[NEXT-1449](https://linear.app/vercel/issue/NEXT-1449/not-found-loses-layout)</sub>

**Comment by karlhorky** [comment]
To contrast this with the previous behavior, I forked the sandbox above to downgrade to `next@13.4.9` (no other changes other than the version number), and header from the layout is working again:

CodeSandbox: https://codesandbox.io/p/sandbox/immutable-thunder-ym59x5?file=%2Fapp%2Fnot-found.tsx%3A1%2C1

https://github.com/vercel/next.js/assets/1935696/5e680d2b-2777-4e84-a7d2-a32138042464

**Comment by karlhorky** [comment]
Thanks for #52790 @huozhi and @ijjk 🙌

However, I noticed that PR was reverted in https://github.com/vercel/next.js/pull/52977 before the release of [`next@13.4.11`](https://github.com/vercel/next.js/releases/tag/v13.4.11).

Should we reopen this issue until it's landed permanently?

**Comment by LagSlug** [comment]
I'm not sure if this is related, but the not-found.js file is being resolved to a parent route when set under a dynamic route.

E.g.

In the following tree, under the route /bovines/[id], the `not-found.tsx` under the [id] directory will be called, but the returned node is not rendered - instead the nearest parent directory with a `not-found.tsx` is rendered.

```
.
└── app
    ├── bovines
    │   ├── [id]
    │   │   ├── not-found.tsx  (not rendered when throwing the NotFound error at this route)
    │   │   └── page.tsx
    │   ├── not-found.tsx (this is rendered instead)
    │   └── page.tsx
    ├── favicon.ico
    ├── globals.css
    ├── layout.tsx
    └── page.tsx
 ```

**Comment by karlhorky** [comment]
Thanks for the re-land in #52985 @huozhi @ijjk 🙌

The layout is back for `not-found` now:

CodeSandbox: https://codesandbox.io/p/sandbox/determined-bash-hp979v?file=%2Fpackage.json%3A10%2C24


https://github.com/vercel/next.js/assets/1935696/a73f673b-1c71-455e-9ba6-767080eba328
