### ISSUE TITLE
Refresh page while access to private directory

### ISSUE THREAD

**Issue by saeedhemmati** [vercel/next.js#52717]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/saeedhemmati/nextjs13

### To Reproduce

Open `http://localhost:3000/hidden` url and then you will see page reloads.

### Describe the Bug

While define a private route like `/app/_hidden/page.tsx` app multiple reload in same time and not stop at all. this behaviour happen when turbopack is enable

### Expected Behavior

Render `not-found` page.

**Comment by padmaia** [comment]
This appears to be fixed with v13.5+
