### ISSUE TITLE
not-found page shows wrong layout and styles

### ISSUE THREAD

**Issue by mirkonasato** [vercel/next.js#52739]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.3
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/mirkonasato/not-found-demo

### To Reproduce

* Clone the above repo
* Start with `npm run dev`. (It's the same with `npm build; npm start`)
* Open `/` and `/posts/one` to see the full layout and styles on regular pages
* Open `/wtf` and `/posts/wtf` to see not found pages

### Describe the Bug

The repo includes a very simple custom `app/not-found.js`. Here are screenshots for four paths: `/` and `/posts/one` exist, while `/wtf` and `/posts/wtf` do not.

![not-found](https://github.com/vercel/next.js/assets/133967/a4a81a6c-f35d-4c85-9fb7-9223ea1ce43a)

The Not Found page for `/wtf` shows the styles from `globals.css`, but not the `<header>` from `layout.js`.
The Not Found page for `/posts/wtf` shows the `<header>` from `layout.js`, but not the styles from `globals.css`. 

### Expected Behavior

The custom Not Found page should use the same layout and styles as regular pages.

**Comment by mtr1990** [comment]
same issue

**Comment by EiDemir** [comment]
For me, it only works as expected on the routes where a loading page is also added. When no loading page is added, it breaks since the styles and the root layout aren't applied.

**Comment by mirkonasato** [comment]
Indeed, the repro repo works fine with `next@13.4.9`, so this looks like a regression.

**Comment by codinginflow** [comment]
This used to work as expected but a recent update of Next.js broke it. The question is, was this intentional or is this a bug?

**Comment by mirkonasato** [comment]
@karlhorky it certainly looks the same as the `/wtf` part of my example, however my repo also shows a different behaviour for the `/posts/wtf` dynamic route. It might well be that both share the same cause, but until we know for sure I'll leave this open.

**Comment by glenncai** [comment]
Same issue, and the theme toggle is also not working on the `not-found.tsx` when I use the `Context` method.

```typescript
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Theme>
          <AppProvider>{children}</AppProvider>
        </Theme>
      </body>
    </html>
  );
}
```
