### ISSUE TITLE
Docs: generateMetadata function bug

### ISSUE THREAD

**Issue by DanielZ1337** [vercel/next.js#52759]
### What is the improvement or update you wish to see?
```
```jsx filename="app/products/[id]/page.jsx" switcher
import { Metadata } from 'next'

export async function generateMetadata(
  { params, searchParams },
  parent
) {
  // read route params
  const id = params.id

  // fetch data
  const product = await fetch(`https://.../${id}`).then((res) => res.json())

  // optionally access and extend (rather than replace) parent metadata
  const previousImages = (await parent).openGraph?.images || []

  return {
    title: product.title,
    openGraph: {
      images: ['/some-specific-page-image.jpg', ...previousImages],
    },
  }
}

export default function Page({ params, searchParams }) {}
```

### Is there any context that might help us understand?

The switcher causes problems in the docs, since it is possible to switch to the javascript version, when there isn't any. If code example switched to javascript, the code example preview will completely disappear and a refresh is required. Either remove the switcher I guess or add the javascript version

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/generate-metadata#generatemetadata-function

**Comment by harshalone** [comment]
is there a way to use the same details fetched inside the generateMetadata inside our page component. Because if not then we will be fetching same details twice at server side
