### ISSUE TITLE
Docs: Improved how to get information about the current locale

### ISSUE THREAD

**Issue by Eunkyung-Son** [vercel/next.js#52769]
### What is the improvement or update you wish to see?

https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing

I have implemented multilingual(i18n) support based on the example above. If you want to use information about the current locale in a component, you need to pass the 'lang' as a prop from the layout or page and drill it down to the sub-components using props drilling. It would be helpful to have a hook that can receive the locale without using props drilling. In the previous version, with the page router, you could retrieve information about the locale using 'useRouter' from 'next/router'. However, in the current version, since it has been migrated to 'next/navigation', you can no longer access the locale.

### Is there any context that might help us understand?

https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing

![스크린샷 2023-07-17 오후 5 00 29](https://github.com/vercel/next.js/assets/68625841/88877322-dc46-466c-9a1c-d784fee76102)

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing

**Comment by leerob** [comment]
Hey! If you want some other options for making it easier to deal with locales / translations, we have included some community resources here: https://nextjs.org/docs/app/building-your-application/routing/internationalization#resources

Also open to community contributions if you feel that example could be better.
