### ISSUE TITLE
error     at stringify (<anonymous>)

### ISSUE THREAD

**Issue by susahin80** [vercel/next.js#52817]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
PS D:\udemy\nextjsprojects\imdb> npx --no-install next info

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

...

### To Reproduce

PS D:\udemy\nextjsprojects> npx create-next-app@latest
√ What is your project named? ... imdb
√ Would you like to use TypeScript? ... No / Yes
√ Would you like to use ESLint? ... No / Yes
√ Would you like to use Tailwind CSS? ... No / Yes
√ Would you like to use `src/` directory? ... No / Yes
√ Would you like to use App Router? (recommended) ... No / Yes
√ Would you like to customize the default import alias? ... No / Yes
Creating a new Next.js app in D:\udemy\nextjsprojects\imdb.

Using npm.

Initializing project with template: app-tw

Installing dependencies:
- react
- react-dom
- next
- tailwindcss
- postcss
- autoprefixer
- eslint
- eslint-config-next

added 343 packages, and audited 344 packages in 45s

131 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Initialized a git repository.

Success! Created imdb at D:\udemy\nextjsprojects\imdb

### Describe the Bug

After installing with default options, when I run "npm run dev" it gives the following error.

```
PS D:\udemy\nextjsprojects> cd imdb
PS D:\udemy\nextjsprojects\imdb> npm run dev

> imdb@0.1.0 dev
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 1573 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 129 ms (20 modules)
- wait compiling /page (client and server)...
- event compiled client and server successfully in 6s (474 modules)
- wait compiling...
- event compiled successfully in 125 ms (226 modules)
- error node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-server.edge.development.js (389:12) @ resolveClientReferenceMetadata
- error     at stringify (<anonymous>)
null
- error node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-server.edge.development.js (389:12) @ resolveClientReferenceMetadata
- error     at stringify (<anonymous>)
null
- error node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-server.edge.development.js (389:12) @ resolveClientReferenceMetadata
- error     at stringify (<anonymous>)
null
- error node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-server.edge.development.js (389:12) @ resolveClientReferenceMetadata
- error     at stringify (<anonymous>)
null
- error node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-server.edge.development.js (389:12) @ resolveClientReferenceMetadata
- error     at stringify (<anonymous>)
null
- error node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-server.edge.development.js (389:12) @ resolveClientReferenceMetadata
- error     at stringify (<anonymous>)
null
- error node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-server.edge.development.js (389:12) @ resolveClientReferenceMetadata
- error     at stringify (<anonymous>)
digest: "4023818524"
null
```

### Expected Behavior

it should run without error

**Comment by SomethingReasonable** [comment]
Did you find a solution to this issue? I have experienced the same thing, despite trying several next versions (13.4.2, 13.1.1, 13.4.10)
