### ISSUE TITLE
Favicon.ico not recognized within the app directory - BUT, icon.ico, is. 

### ISSUE THREAD

**Issue by jonathonchilds** [vercel/next.js#52813]
All I had to do was remove `favicon.ico` from `src/app`, it seems to automatically pick it up and write a meta tag for it

_Originally posted by @DominicTobias in https://github.com/vercel/next.js/issues/46682#issuecomment-1455173138_
            

For me, the Nextjs logo was persisting, despite it not being declared any place, and despite me having added a favicon.ico file to my app directory. In the midst of me writing this, I realized that I had not tried re-naming the favicon.ico file to icon.ico. I intended to follow the metadata files docs and implement the following:
<link
  rel="icon"
  href="/icon?<generated>"
  type="image/<generated>"
  sizes="<generated>"
/>

... but, I happened to have my development server running, and to my great surprise and relief, the favicon shows! So in the midst of me writing this, I've changed my issue: favicon.ico does not automatically render, but icon.ico does. (Previously, I had also attempted to insert a <head> tag with <link rel="icon" href="/favicon.ico" sizes="any" /> pasted in, but that didn't show my favicon, either. 

I know this is verbose. I hope it's helpful?!

**Comment by timneutkens** [comment]
Please use the issue template.

**Comment by donaminos** [comment]
@jonathonchilds thanks a lot for this title 🙏 I was struggling with my favicon not showing up even if it's present in the dom. Changin the name to `icon.ico` fixed the issue so thank again
