### ISSUE TITLE
Page crashes and "Error: Connection closed." appears

### ISSUE THREAD

**Issue by patrick91** [vercel/next.js#52824]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: N/A
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/europython/website/

### To Reproduce

Open this page a few times: https://ep2023.europython.eu/wasm

### Describe the Bug

Same as #49205

### Expected Behavior

No crash

**Comment by patrick91** [comment]
This seems to be have been reintroduced in 13.4.9 :( I've reverted next to 13.4.8 in my codebase. 

The error is still visible here: https://ep2023-n689xgnp1-europython-society.vercel.app/wasm

**Comment by doinghun** [comment]
Did reverting to 13.4.8 work? @patrick91 Having the same issue

**Comment by xosaad** [comment]
Having the same issue on Next 13.4.10. It does not happen when my app is run locally. Only when it is deployed.

**Comment by xosaad** [comment]
> Did reverting to 13.4.8 work? @patrick91 Having the same issue

I just reverted and noticed that its happening less than before but its definitely not 100% fixed

**Comment by Gbuomprisco** [comment]
I am hitting the exact same issue. I would love to pout together a reproduction, but it only happens in production so it'll take me a bit.

**Comment by arclogos132** [comment]
I get this too 🥲

**Comment by arclogos132** [comment]
Serverless logs look clean. 
Console only says...
`Error: Connection closed.`

**Comment by Gbuomprisco** [comment]
> did u check your vercel logs that whats error you guys getting

This is not a server issue. The RSC payload during the navigation is correct - it's a client-side exception.

![image](https://github.com/vercel/next.js/assets/3512197/bf4382ca-1bf8-46ab-b11b-783d6dfdbaea)

**Comment by Legend-official** [comment]
> > did u check your vercel logs that whats error you guys getting
> 
> This is not a server issue. The RSC payload during the navigation is correct - it's a client-side exception.
> 
> ![image](https://user-images.githubusercontent.com/3512197/254267439-bf4382ca-1bf8-46ab-b11b-783d6dfdbaea.png)

its not check serverside logs and do console logs in ur server then only u get output error without console logs u don't get any error on server side

**Comment by doinghun** [comment]
Are you guys all using [`next-intl`](https://github.com/amannn/next-intl)? I am using it and it seems this issue https://github.com/vercel/next.js/issues/49205 was related as well

**Comment by Gbuomprisco** [comment]
> Are you guys all using [`next-intl`](https://github.com/amannn/next-intl)? I am using it and it seems this issue #49205 was related as well

I am not using it - I don't think it's related.

**Comment by youminkim** [comment]
In our case, it happened when we `router.push`. We temporarily changed it to `window.locaiton.href` instead.

**Comment by arclogos132** [comment]
I use generateMetadata

**Comment by arclogos132** [comment]
I use a tags instead of Link component for external links and sometimes window.open() could this be the reason?

**Comment by LouisLec** [comment]
I just got the issue, right now, after a fresh install on the project I am working on for a couple weeks now, and I see this issue has been posted just today. When did you first experienced all this ?

**Comment by arclogos132** [comment]
I have server actions true on my config

**Comment by Gbuomprisco** [comment]
> I just got the issue, right now, after a fresh install on the project I am working on for a couple weeks now, and I see this issue has been posted just today. When did you first experienced all this ?
> 
> Downgrading to 13.4.5 doesnt solve the issue

I only noticed it today after deploying to Vercel.

I have server actions enabled in case it matters (but I'd be surprised).

**Comment by arclogos132** [comment]
@Gbuomprisco same here

**Comment by arclogos132** [comment]
Could be a bug on the Vercel side? since local works perfectly

**Comment by arclogos132** [comment]
> I just got the issue, right now, after a fresh install on the project I am working on for a couple weeks now, and I see this issue has been posted just today. When did you first experienced all this ?
> 
> Downgrading to 13.4.5 doesnt solve the issue

I got this issue today too.

**Comment by NinonMaraval** [comment]
+1

**Comment by xosaad** [comment]
> Could be a bug on the Vercel side? since local works perfectly

Yup most likely a bug. Local works perfectly for me as well

**Comment by LouisLec** [comment]
this problem occurs randomly in my application, but more systematically as my page size grow. for example, when i want to increase the number of rows displayed in a table, i can go up to a certain number (with random crashes), but after a certain point nothing works. 

I also think this has something to do with Vercel.

**Comment by LouisLec** [comment]
one of my previous next 13 project is also facing the same issue. I haven't touched it for a couple weeks and it worked perfectly

**Comment by abusada** [comment]
If this is a Vercel deployment issue with no action required from us, how can we escalate and prioritize the resolution? We've noticed the impact in production, and it has the potential to cause financial losses.

**Comment by Gbuomprisco** [comment]
> 
If this is a Vercel deployment issue with no action required from us, how can we escalate and prioritize the resolution? We've noticed the impact in production, and it has the potential to cause financial losses.

If you're on a paid plan, you can create a case from the dashboard. I'll also be doing that if it's not fixed at some point tomorrow as well

**Comment by kohort-aymeric** [comment]
We have got the same error today

**Comment by jordan-mcrae** [comment]
+1, just started today for us on Vercel. We've tried downgrading our Next versions but with no luck. Older deploys seem to be okay, but all of our new builds have the issue.

**Comment by patrick91** [comment]
Yes, the reverting didn't actually work :( I checked an old deploy and that still works

**Comment by collinversluis** [comment]
I am having the same issue, reverting is not seeming to work, serverActions are enabled and I'm using the app router. All new builds are having this issue.

I am getting data with a server function with await and it's larger data in both cases. When it's smaller data it does not work. My API is also getting truncated after around 64kbs and that never happened before.

Maybe it's some issue with nextjs serverless function response limits? it's a larger response that gets the "Error: Connection closed." every time

**Comment by patrick91** [comment]
this seems to be ok now, is anyone else still experiencing this issue?

**Comment by chrisjh** [comment]
We're still seeing this issue – no code changes or package updates to the page that's crashing – was working fine previously, but a new deployment has been running into this error consistently.

**Comment by razvan-soare** [comment]
Build seems to be working fine again. Was breaking today the whole day. Tried a new deploy now and looks fine will keep an eye open tho..

**Comment by collinversluis** [comment]
All of my broken versions randomly resolved a few hours ago with a redeploy... My API stopped truncating too.

Glad I spent 10 hours troubleshooting a Vercel issue

**Comment by chrisjh** [comment]
To follow up – our most recent deployment is also now ok, but it's the first one to work today. Any sort of update from Vercel would be appreciated, especially since the status page never reflected this platform issue.

**Comment by razvan-soare** [comment]
Everything seemed ok last night. 
In the morning i was browsing the website and i got the error again. Randomly.

Is better for sure. Where yesterday was a 100% rate to reproduce the error today only happened once randomly.

IS there any way of catching this error or having it crash in a nicer way ?

**Comment by timneutkens** [comment]
Hey folks, sorry to hear you ran into issues. I reached out internally and apparently there was an issue yesterday: https://www.vercel-status.com/incidents/5c0cpdhr3n4p.

In the future if you're running into issues that require immediate attention please reach out to Vercel support, I understand that you ended up here in this case but GitHub issues on the Next.js repository are not monitored 24/7 (i.e. most of our team working on Next.js is in Europe).

Guidance on the vercel-status link is to redeploy the application, can you try that if you're still running into issues?

**Comment by chrisjh** [comment]
Thanks for following up @timneutkens! Will reach out to support next time. Admittedly, it was helpful to see that others were encountering the same thing via this GitHub issue.

**Comment by cipriancaba** [comment]
Vercel support is more than useless. Our PRO plan response time is more than 1 month. We still have unresolved issues that are pending from beginning of June. Really worried about the level of ****s given by vercel since releasing app dir.

This issue is NOT resolved we can still randomly see it, and it's not the first time that our production deployment pipeline is blocked. There isn't even a way to catch the runtime error and report this, so we can't really be sure of the magnitude of the problem

Here is a support case that we just created 00146982
