### ISSUE TITLE
import "server-only" and "use server" throws when used in middleware

### ISSUE THREAD

**Issue by akomm** [vercel/next.js#52833]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.1.7-canary.10
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/beautiful-montalcini-vdnznm?file=%2Fmiddleware.ts%3A2%2C1

### To Reproduce

Just open the reproduction example.

### Describe the Bug

1. Can't import "server-only" files into middleware.

2. Importing "use server" files into middleware handles it as client file. So for example environment isn't available and code that relies on it breaks.

### Expected Behavior

The explained problems not happening.

<sub>[NEXT-1616](https://linear.app/vercel/issue/NEXT-1616/import-server-only-and-use-server-throws-when-used-in-middleware)</sub>

**Comment by akomm** [comment]
I think the middleware (maybe for static analysis?) is simply processed earlier than those server-only imports are removed?

**Comment by barryengineerapart** [comment]
I can't believe that nobody has answered this issue... It seems extremely important.
