### ISSUE TITLE
Server actions forcing dynamic routes

### ISSUE THREAD

**Issue by ehwarren** [vercel/next.js#52840]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/bluegrv/next-js-server-actions-force-dynamic-route

### To Reproduce

Building the app shows any route using a server action is forced to be dynamic
<img width="406" alt="image" src="https://github.com/vercel/next.js/assets/3991658/050bc225-08cc-4908-9e95-5007eb72e045">

### Describe the Bug

Whenever a server action is used in a component (server or client component) the corresponding route is forced to be dynamic. 

There is an unanswered question in discord in regards to this: https://nextjs-forum.com/post/1118778071873486948

### Expected Behavior

I would expect that the route should still be able to be static or SSG

<sub>[NEXT-1453](https://linear.app/vercel/issue/NEXT-1453/server-actions-forcing-dynamic-routes)</sub>

**Comment by shuding** [comment]
This is on our roadmap, Server Actions should not affect the route itself.

**Comment by son1ss** [comment]
Any updates?
