### ISSUE TITLE
Error in static exports - error API Routes cannot be used with "output: export"

### ISSUE THREAD

**Issue by sumedhe** [vercel/next.js#52855]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: export
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Static HTML Export (output: "export")

### Link to the code that reproduces this issue or a replay of the bug

npm run dev

### To Reproduce

Steps to reproduce:
1. Initiate a nextjs project with `create-next-app`. Set `No` to the following option.
    `Would you like to use App Router? (recommended) … No / Yes`
2. Add `output: 'export',` to the `next.config.js` file. ([Ref](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports))
3. Run `npm run dev`
4. It will show the above error.

### Describe the Bug

When we enable static exports, it shows the following error even we have disabled the API routes in `create-next-app`.
```
- error API Routes cannot be used with "output: export"
```

### Expected Behavior

If we haven't enabled API routes that error should not be shown.

### Which browser are you using? (if relevant)

Brave

**Comment by icyJoseph** [comment]
Hi,

That's because the `create-next-app` starter kit, for Pages Router, contains an `api/hello.ts` (or js) route, which is an API route.

```console
src/pages
├── _app.tsx
├── _document.tsx
├── api
│   └── hello.ts
└── index.tsx
```

I think you might be misreading, `App Router` for `API Routes`, those are different things.

**Comment by sumedhe** [comment]
Closing as it is resolved with the above comment.
