### ISSUE TITLE
Lacking 'color' attribute in IconDescription Metadata

### ISSUE THREAD

**Issue by rkt2spc** [vercel/next.js#52853]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.11-canary.0
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/blob/v13.4.11-canary.0/packages/next/src/lib/metadata/types/metadata-types.ts#L99

### Describe the Bug

The color attribute is needed to generate Safari Pinned Tab Icon
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

```
<link rel="mask-icon" href="website_icon.svg" color="red">
```

It's also commonly generated with favicon generators

### Expected Behavior

There should be a way to provide the color attribute to Icons

**Comment by darshanjain-entrepreneur** [comment]
Can you explain in brief what is the issue
