### ISSUE TITLE
please add app directory for with-zustand example

### ISSUE THREAD

**Issue by sinafath** [vercel/next.js#52858]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
**
```

### Which example does this report relate to?

with-zustand

### Describe the Bug

there is no example of Zustand with new next app directory. Can I use Zustand with the new app directory model?

### Expected Behavior

Using zustand with app directory

### To Reproduce

**

**Comment by balazsorban44** [comment]
Hi, the preferred way would be to convert the current example at https://github.com/vercel/next.js/tree/canary/examples/with-zustand instead of adding a new one. The examples directory is community-maintained so feel free to open a PR, and we can help review it! :pray:

**Comment by nicksan222** [comment]
Please assign me, i will publish the PR in 12 hours at most

**Comment by shyampathade** [comment]
Can you assign it to me please ?

**Comment by monstajoe2002** [comment]
Can you assign me this issue please?

**Comment by mhpjay422** [comment]
HI, I'm new here and gave this issue a try. No success. Details below.

When trying to convert to the app router:

- The current initialization of the "store" uses a `useRef`
- With the conversion to the app router, the initialization of the store errors saying the `useRef` can only be used in a client component
![CleanShot 2023-10-25 at 19 36 32](https://github.com/vercel/next.js/assets/12041898/ca8b4a5e-97c0-4364-9106-13d8ad218b72)
- I know adding 'use client' wouldnt be the way to go but gave it a try and get this error
![CleanShot 2023-10-25 at 19 38 12](https://github.com/vercel/next.js/assets/12041898/a6251f8c-e0a7-4d70-8872-e9c1dfce9672)



I tried to figure a way not to use the `useRef` with no luck. I am not sure how to proceed from here. Any pointers?
