### ISSUE TITLE
Could not find the module in the React Client Manifest. This is probably a bug in the React Server Components bundler.

### ISSUE THREAD

**Issue by gauravsaini964** [vercel/next.js#52862]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: 8.6.0
    Relevant Packages:
      next: 13.4.11-canary.0
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/assets/16620277/58d05257-6176-47bb-bca5-b84afb6c5843

### To Reproduce

https://stackblitz.com/github/easydevgit/next-13-course/tree/master/advanced-routing-intercepting-routes?file=app/layout.tsx

### Describe the Bug
<img width="723" alt="Screenshot 2023-07-19 at 3 46 47 PM" src="https://github.com/vercel/next.js/assets/16620277/ba8e7736-054d-4583-a3c6-6046de465b39">

<img width="1829" alt="Screenshot 2023-07-19 at 3 54 29 PM" src="https://github.com/vercel/next.js/assets/16620277/79958618-10d3-44a5-9567-3c54f11f3859">

I am getting this error after updating to 13.4.10 and also on latest canary. It is working fine on 13.4.9.
I am using parallel and intercepting routes.

### Expected Behavior

Normal parallel and intercepting route behaviour.

### How are you deploying your application? (if relevant)

Vercel

**Comment by gauravsaini964** [comment]
@timneutkens @khuezy  Opened new issue as earlier one was locked #50243

**Comment by timneutkens** [comment]
I'm amazed by how my comments and the issue template are ignored 😢 This issue does not have a reproduction, only a link to a directory tree screenshot.

**Comment by gauravsaini964** [comment]
> I'm amazed by how my comments and the issue template are ignored multiple times 😢 This issue does not have a reproduction, only a link to a directory tree screenshot.

I must have missed it.

Its not mine but having the exact same issue.

https://stackblitz.com/github/easydevgit/next-13-course/tree/master/advanced-routing-intercepting-routes?file=app/layout.tsx

**Comment by khuezy** [comment]
@timneutkens please forgive our incompetence ;)
But in the stackblitz above, the model interception of `(.)login` causes the app to crash when it tries to intercept the route.

**Comment by collection27** [comment]
Here is a simple way to reproduce this issue:
1. Clone https://github.com/vercel-labs/nextgram/tree/main
2. Update to next@latest (13.4.10)
3. Run

Anytime you click a photo the error will popup. 

`Error: Could not find the module "X:\gits\testerror\nextgram\src\components\modal\Modal.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.`

**Comment by isaackoz** [comment]
I believe #52664 is causing the issue. The issue appears to be due to the naming convention of intercepting routes. 

Line 352 in `packages/next/src/build/webpack/plugins/flight-manifest-plugin.ts`
```
const groupName = entryName
        .slice(0, entryName.lastIndexOf('/'))
        .replace(/\/@[^/]+/g, '')
        .replace(/\/\([^/]+\)/g, '')
```
If we do a normal group, 
```
const route1 = "app/(group)/@named/foo/page.tsx"

const groupName = route1
        .slice(0, route1.lastIndexOf('/'))
        .replace(/\/@[^/]+/g, '')
        .replace(/\/\([^/]+\)/g, '')

console.log(groupName)
// output: 'app/foo' (correct syntax)
```
However if we do an intercepting route,
```
const route2 = "app/(group)/@named/(.)foo/page.tsx"

const groupName = route2
        .slice(0, route2.lastIndexOf('/'))
        .replace(/\/@[^/]+/g, '')
        .replace(/\/\([^/]+\)/g, '')

console.log(groupName)
// output: 'appfoo' <----- Missing '/'
```

I'm not sure if it handles intercepting routes above or elsewhere, but this just caught my eye at first glance. It would make sense why intercepting routes don't work.

**Comment by khuezy** [comment]
So did the PR above forget to account for the `(.)` and `(..) characters`? And with the `(..)` paths, it would need to resolve the paths.

**Comment by devrudraa** [comment]
I am facing the same problem I made a modal using parallel routing and intercepting route it works fine but when I added a back button using useRouter from "next/navigation" it is giving me error:


Unhandled Runtime Error
Error: Could not find the module "[absolute path]\app\@modal\(.)password\new\page.jsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

Please help me I need to add this back function 🥹

**Comment by shuding** [comment]
Hi all, this issue should be fixed in `13.4.11`. Please upgrade and let us know, thanks!

**Comment by khuezy** [comment]
Thanks @shuding, it's fixed!

**Comment by khuezy** [comment]
uh oh, .13 broke this again, cc @shuding

**Comment by timneutkens** [comment]
Please open a new issue with a reproduction so that we can have a look.

**Comment by EranNL** [comment]
I get this error when nested components both have `use client` defined. I don't know whether that is related, but it is perhaps worth noting.
