### ISSUE TITLE
next-translate Hydration failed

### ISSUE THREAD

**Issue by atwoodcai1991** [vercel/next.js#52861]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
v18.16.1
Apple M1 Pro 12.3
16 GB
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Internationalization (i18n)

### Link to the code that reproduces this issue or a replay of the bug

none

### To Reproduce

```
const nextConfig = {
  ...devProxy,
  pageExtensions: ['page.tsx', 'page.ts', 'page.jsx', 'page.js'],
  i18n,
  transpilePackages: ['ahooks'],
  webpack: (config, options) => {
    const location = options.isServer ? 'ssr' : 'chunks'
    config.plugins.push(
      new NextFederationPlugin({
        name: 'main',
        filename: 'static/chunks/remoteFooterEntry.js',
        exposes: {
        },
        remotes: {
          remoteHeader: `remoteHeader@http://localhost:9000/_next/static/${location}/remoteHeaderEntry.js`
        },
        shared: {},
        extraOptions: {
          automaticAsyncBoundary: true
        }
      })
    )
    return config
  }
}
module.exports = nextTranslate(nextConfig)
```

### Describe the Bug

when i use @module-federation/nextjs-mf and next-translate-plugin in next.config.js

,
here is the data of __NEXT_DATA__:   looks like ok!
{"props":{"pageProps":{"__lang":"uk-UA","__namespaces":{"common":{"mc_common_footer_about_us":"Про нас","mc_common_footer_about":"Про біржу MEXC",............."mc_common_sidebar_customer_hotline_working_hours":"Working Hours: {{workingHours}}"}}},"__N_SSG":true},"page":"/","query":{},"buildId":"development","isFallback":false,"gsp":true,"locale":"uk-UA","locales":["en-US","ru-RU","tr-TR","vi-VN","id-ID","ja-JP","ko-KR","pt-PT","es-ES","it-IT","zh-TW","zh-CN","fa-IR","de-DE","fil-PH","fr-FR","th-TH","ar-AE","uk-UA"],"defaultLocale":"en-US","scriptLoader":[]}

BUT page shows the key words:   mc_common_footer_about

### Expected Behavior

show translations

**Comment by timneutkens** [comment]
> when i use @module-federation/nextjs-mf and [next-translate-plugin](https://linear.app/vercel/issue/NEXT-translate-plugin) in next.config.js

This doesn't sound like a Next.js issue. Please raise an issue in the particular package you're using that causes the issue.

**Comment by atwoodcai1991** [comment]
thanks your comment,  i found that next-translate-plugin's template code didn't insert bundle
```
import ${INTERNAL_CONFIG_KEY} from '@next-translate-root/i18n'
    import __appWithI18n from 'next-translate/appWithI18n'
    ${pagePkg.getCode()}
    export default __appWithI18n(${pageVariableName}, {
      ...${INTERNAL_CONFIG_KEY},
      isLoader: true,
      skipInitialProps: ${skipInitialProps},
      ${addLoadLocalesFrom(existLocalesFolder)}
    });
```

**Comment by atwoodcai1991** [comment]
latest progress click here [https://github.com/aralroca/next-translate-plugin/issues/63](https://github.com/aralroca/next-translate-plugin/issues/63)
