### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by s-iliyas** [vercel/next.js#52876]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2
    Binaries:
      Node: 19.9.0
      npm: 9.6.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.10", newest: "13.4.11-canary.0".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/s-iliyas/portfolio

## Install dependencies
`yarn`

## Run server
`yarn dev
`
## To see warnings
Click on `logout` button present in navbar and check server logs

### Describe the Bug

I don't know why I'm getting this warnings, which are annoying.

```
Import trace for requested module:
./node_modules/@nlpjs/core-loader/src/container-bootstrap.js
./node_modules/@nlpjs/core-loader/src/index.js
./node_modules/node-nlp/src/nlp/nlp-util.js
./node_modules/node-nlp/src/nlp/index.js
./node_modules/node-nlp/src/index.js
./app/api/bot/route.js

./node_modules/@nlpjs/core-loader/src/container-bootstrap.js
Critical dependency: the request of a dependency is an expression
```

### Expected Behavior

Maybe just compiling server logs should be present.

### Which browser are you using? (if relevant)

Google Chrome

### How are you deploying your application? (if relevant)

Only in local, yarn dev.

**Comment by balazsorban44** [comment]
Hi, the reason for this issue is that the `node-nlp` package has a too complex `require` statement which cannot be analyzed for bundling, which is the default case for even third-party packages in the App Router.

This can be opted out via the  `serverComponentsExternalPackages` option. Read more here: https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages

So adding the following to `next.config.js`

```js
module.exports = {
  experimental: {
    serverComponentsExternalPackages: ["node-nlp"],
  },
};
```

will solve the issue. (Note, we are currently exploring if we can detect these cases automatically)
