### ISSUE TITLE
generateStaticParams breaks intercepting routes

### ISSUE THREAD

**Issue by Netail** [vercel/next.js#52880]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.6.1
    Relevant Packages:
      next: 13.4.11-canary.0
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Netail/app-dir-intercept

### To Reproduce

1. Create a project which uses parallel route and intercepting, something like;

```
.
└── [locale]/
    ├── (program)/
    │   ├── programma/
    │   │   └── [slug]/
    │   │       └── [id]/
    │   │           └── page.jsx
    │   └── program/
    │       └── [slug]/
    │           └── [id]/
    │               └── page.jsx
    ├── @modal/
    │   ├── (.)programma/
    │   │   └── [slug]/
    │   │       └── [id]/
    │   │           └── page.jsx
    │   └── (.)program/
    │       └── [slug]/
    │           └── [id]/
    │               └── page.jsx
    └── layout.jsx
```

2. Add a generateStaticParams in the root layout

### Describe the Bug

`generateStaticParams` in the root layout prevents route intercepting, causing to render the actual page instead of the intercepted component

### Expected Behavior

Display intercept component instead of the actual page

**Comment by Dev-CasperTheGhost** [comment]
I'm also able to reproduce this bug in production (Vercel). Repository details:

```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.7
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

**Comment by Netail** [comment]
Mhmm, I feel like intercepting routes is a complete mess atm.

**Comment by yuuhn** [comment]
I'm experiencing the same issue but without using `generateStaticParams` in my project. My folder structure is as follows:
```
app
  [user]
    page.tsx
  @profile
    (.)[user]
      page.tsx
  layout.tsx
  page.tsx
```

**Comment by Neo-Ciber94** [comment]
`generateStaticParams` works for me but when I use `output: "export"` the app breaks and render the normal route ignoring the interception

**Comment by SamHendry** [comment]
@Neo-Ciber94 I am experiencing a similar issue. I have a modal with an intercepting route in it - `/@modal/(..)[slug]/page.tsx` - which works perfectly fine normally but when I set `output: "export"` the normal route is rendered and it throws the error
```
Error: Page "/search/(..)[club]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.
```
even though I do in fact export this function in the `page.tsx` and it works without static exports.

**Comment by EdVonTech** [comment]
Any update?

**Comment by prananta** [comment]
Happened to me too. But then I fixed it by exporting generateStaticParams from the page.tsx instead of layout.tsx. Seems like exporting generateStaticParams from layout breaks the intercepting route.

**Comment by Abdalla-Mon** [comment]
Did you solve this?
I was working on that for like 5 hours and didn't make any progress.
When I build the project, it generates the page normally, but there is no interception routing in production

**Comment by Netail** [comment]
Muchas gracias 🏄‍♂️
