### ISSUE TITLE
Error with official example from Docs for Data-Fetching: "getServerSideProps" is not supported in app/

### ISSUE THREAD

**Issue by opendeluxe** [vercel/next.js#52914]
### What is the improvement or update you wish to see?

I'd like to see a working example for server side data-fetching. The example code on the corresponding pages are not working, instead only producing an error.

I tried to copy/paste the official examples from the Data feching page for `getServerSideProps` and it throws errors:

    import type { InferGetServerSidePropsType, GetServerSideProps } from 'next'
     
    type Repo = {
      name: string
      stargazers_count: number
    }
     
    export const getServerSideProps: GetServerSideProps<{
      repo: Repo
    }> = async () => {
      const res = await fetch('https://api.github.com/repos/vercel/next.js')
      const repo = await res.json()
      return { props: { repo } }
    }
     
    export default function Page({
      repo,
    }: InferGetServerSidePropsType<typeof getServerSideProps>) {
      return repo.stargazers_count
    }

Error:

    ./app/page.tsx
    ReactServerComponentsError:
    
    "getServerSideProps" is not supported in app/. Read more: https://nextjs.org/docs/app/building-your-application/data-fetching

Unfortunately, it refers to data-fetching documentation, which contains the example that led me to this error.

How to deal with that and how to use getServerSideProps with AppRouter?

### Is there any context that might help us understand?

# Steps to reproduce:

1. Create the app:

   ` npx create-next-app@latest`

    (TypeScript: yes, AppRouter: yes, src-directory: no)

2. Change the pages.tsx into the variant above from the Docs.

package.json:

      "scripts": {
        "dev": "next dev -p 8002",
        "build": "next build",
        "start": "next start -p 8002",
        "lint": "next lint"
      },
      "dependencies": {
        "@types/node": "20.4.2",
        "@types/react": "18.2.15",
        "@types/react-dom": "18.2.7",
        "autoprefixer": "10.4.14",
        "eslint": "8.45.0",
        "eslint-config-next": "13.4.10",
        "eslint-config-prettier": "^8.8.0",
        "eslint-plugin-prettier": "^5.0.0",
        "next": "13.4.10",
        "postcss": "8.4.26",
        "prettier": "^3.0.0",
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "tailwindcss": "3.3.3",
        "typescript": "5.1.6"
      },
      "devDependencies": {
        "@typescript-eslint/eslint-plugin": "^6.1.0"
      }

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching

**Comment by itinance** [comment]
I stumbled upon the same issue recently. There are many pages describing old and new approaches. 

The most recent version you should follow is this one: https://nextjs.org/docs/app/building-your-application/data-fetching/fetching

The truth is, you don't need `getServerSideProps` anymore. This is written in one of the data-fetching pages, but there are still links to the old page, especially when people are coming from Google or SO or tutorials, and many devs often fell into this trap. (see https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props)


Here is a working example: (it simply fetches data inside the render function and that's it)

```
export default async function Page() {
  const data = await getData()
 
  return <main></main>
}
```

I would suggest adding a corresponding note "deprecated" on this [page](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props):
(https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props)

 with a link to the new [page](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching) 
(https://nextjs.org/docs/app/building-your-application/data-fetching/fetching)

**Comment by zainabdeen486** [comment]
These old methods are not supported in app router instead you can use the fetch api check docs for more clarification

**Comment by icyJoseph** [comment]
The docs you linked to, https://nextjs.org/docs/app/building-your-application/data-fetching, describe "Old Methods" and show a link to `getServerSideProps`:

<img width="1428" alt="Screenshot 2023-07-20 at 11 20 20" src="https://github.com/vercel/next.js/assets/21013447/b455cac6-0168-4498-8a0c-b1ef8a3d5b14">

Which has some indicators that you are now in the Pages router domain. Perhaps they should put a gigantic banner across the top of the page saying, <<These Docs Apply to Pages Router>> ?

**Comment by balazsorban44** [comment]
Hi, the error message contains a link to data fetching within the App Router, further specifying server-side data fetching in the following section: https://nextjs.org/docs/app/building-your-application/data-fetching#fetching-data-on-the-server

If after reading this page you are still confused, you can use the "Feedback" button (top right) on the page to explain to us how we can do better, thanks!

**Comment by opendeluxe** [comment]
Hey guys. I appreciate all your feedback. There seems to be a significant level of confusion for those new to NextJS at the present time. There's a learning curve involved in transitioning from the traditional Router model to the App Router model. In addition, the methods of 'data fetching' have undergone significant changes. As @itinance mentioned earlier, the multitude of tutorials, Stackoverflow responses, and blog posts often refer to varying documentation, including some older techniques. This makes it challenging, but critical, to grasp the broader concept.
Some guys above mentioned to put big banners or at least a specific note to the relevant pages, when they are outdated. This would help a lot with these deep-linked pages.

**Comment by icyJoseph** [comment]
I think there's also a misconception with the state of Pages Route. It is not deprecated, nor outdated. AFAIK it is still a valid, worth exploring solution. 

I remember Next 8 days, and Next 9.x with GSSP and company was such a game changer, that solidified over several years. Even the official communication is clear about this:

> ### [Is the Pages Router going away?](https://nextjs.org/blog/next-13-4#is-the-pages-router-going-away)
> No. We are committed to supporting pages/ development, including bug fixes, improvements, and security patches, for multiple major versions moving forward. We want to ensure developers have enough time to incrementally adopt the App Router as they're ready.
> 
> Using both pages/ and app/ in production together is supported and encouraged. The App Router can be adopted on a [per-route basis](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration).
> 


To be honest, at least from my point of view, App Router is Pages Router tech as a React primitive. Of course, there's new syntax, new features, more details of implementation that ought to be learned, and pitfalls to be recognised, but in the bigger picture some concepts are still the same.
