### ISSUE TITLE
next/script always loads scripts with async set to true

### ISSUE THREAD

**Issue by domdomegg** [vercel/next.js#52935]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
    Binaries:
      Node: 20.4.0
      npm: 9.7.2
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.11-canary.0
      eslint-config-next: 13.1.5
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/domdomegg/next-async-script-reproduction

### To Reproduce

Use `next/script` to load scripts that must be run in order, making sure to disable `async` loading.

### Describe the Bug

Scripts are loaded with `async` loading enabled, despite them being disabled. They may execute out of order.

### Expected Behavior

Scripts are loaded with `async` loading disabled. They execute in the order they were requested.

### Which browser are you using? (if relevant)

Google Chrome 114.0.5735.198 (Official Build) (arm64) 

### How are you deploying your application? (if relevant)

Vercel

**Comment by domdomegg** [comment]
Unfortunately `beforeInteractive` is not appropriate for this use case as they are limited to scripts running in the root layout that are applied across the entire site. I'm looking to load scripts dynamically, e.g. only if the user visits certain pages or loads certain components.

**Comment by ozzyonfire** [comment]
> Have you tried using `beforeInteractive`, https://nextjs.org/docs/app/api-reference/components/script#strategy

Have this same issue even when using beforeInteractive. I have a third-party script that is very strict about async and defer not being used on the script.

And I'm getting errors when it's loading.
![image](https://github.com/vercel/next.js/assets/779491/825561c8-7bbc-47c5-8798-7e115ad8e11a)
