### ISSUE TITLE
notFound() from a dynamic route renders not-found.js without css

### ISSUE THREAD

**Issue by tomer-tgp** [vercel/next.js#52974]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Next version:13.4.10 (latest)
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/thegoodparty/gp-webapp/blob/develop/app/candidate/%5Bslug%5D/page.js#L61

### To Reproduce

visit https://qa.goodparty.org/candidate/not-here
compare to https://qa.goodparty.org/not-here

### Describe the Bug

not-found is being rendered with no CSS (tailwind)

this is the (global) not-found code:
https://github.com/thegoodparty/gp-webapp/blob/develop/app/not-found.jsNot

### Expected Behavior

the not found page should be rendered with CSS like https://qa.goodparty.org/not-here

### Which browser are you using? (if relevant)

chrome 114.0.5735.198, firefox 115.0.2

### How are you deploying your application? (if relevant)

Vercel

**Comment by razvan-soare** [comment]
Hey had a similar issue in 13.4.10 

A few hours ago there was a new canary release: v13.4.11-canary.1 Seems to be fixed here.

https://github.com/vercel/next.js/commit/cb24c555a639189740bd1c6f981fcc075152020a

**Comment by suyalcinkaya** [comment]
@razvan-soare Looks like they had to revert it due to a turbopack issue: https://github.com/vercel/next.js/releases/tag/v13.4.11-canary.2

**Comment by FredTreg** [comment]
I had the issue too, but it seems to be fixed in 13.4.12

**Comment by JasonLamv-t** [comment]
same issue

**Comment by rreo** [comment]
> I had the issue too, but it seems to be fixed in 13.4.12

Concur, I did `npm install next@latest` and it solved my issue.

**Comment by benmneb** [comment]
The latest stable release v13.4.13 does not render with tailwind styles. CSS modules and inline styles work...

**Comment by huozhi** [comment]
Close this as seem the issue is resolved with the reproduction in the description. Please file a new issue with a minimal reproduction if you still have problems with it
