### ISSUE TITLE
Hydration errors introduced begining with `13.4.11-canary.1` 

### ISSUE THREAD

**Issue by Kinbaum** [vercel/next.js#53006]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
Binaries:
  Node: 18.15.0
  npm: 9.5.0
  Yarn: 1.22.10
  pnpm: 8.2.0
Relevant Packages:
  next: 13.4.11
  eslint-config-next: 13.4.11
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Kinbaum/hydration-error/tree/main

### To Reproduce

1. Clone the repository and run `yarn`
2. Run `yarn dev`
3. Navigation to http://localhost:3000
4. Open up the dev tools and see the error in the console

<img width="1278" alt="Screenshot 2023-07-21 at 9 52 14 AM" src="https://github.com/vercel/next.js/assets/6590356/ffebcbc6-4230-4cbb-884d-d332eba836f7">

### Describe the Bug

This appears to be a hydration issue

### Expected Behavior

I would not expect to see this error. Within this repo, I've also included a working version example where the only change is that I am running next `13.4.10` rather than `13.4.11`

1. Run a `git switch working-verion`
2. Then run `yarn`
3. Navigation to http://localhost:3000
4. Open up the dev tools and see that there is no hydration error with the previous release

<img width="1279" alt="Screenshot 2023-07-21 at 9 50 50 AM" src="https://github.com/vercel/next.js/assets/6590356/a4a86c01-b539-448c-9e35-0237a6b490a7">

**Comment by tangye1234** [comment]
Same to me

**Comment by tangye1234** [comment]
@shuding please have a look.

**Comment by tangye1234** [comment]
@timneutkens could you please take a look at this issues, cause many people suffers from this. `useId` hook in client component will definitely lead to this issue.

The issue was introduced in v13.4.11 and the latest canary [v13.4.13-canary.0](https://github.com/vercel/next.js/releases/tag/v13.4.13-canary.0) dose not fix it yet.
