### ISSUE TITLE
Regression: DynamicServerError when using headers() in generateMetadata

### ISSUE THREAD

**Issue by raphaelbadia** [vercel/next.js#53011]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$ /private/tmp/generatemetadata/node_modules/.bin/next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.8
    Relevant Packages:
      next: 13.4.11-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Metadata (metadata, generateMetadata, next/head)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/raphaelbadia/generate-metadata-headers

### To Reproduce

1. Clone the reproduction repository
2. run `yarn install && yarn build`
3. see the error message: ```- info Collecting page data  
[    ] - info Generating static pages (0/3)DynamicServerError: Dynamic server usage: headers
    at staticGenerationBailout (/private/tmp/generatemetadata/.next/server/chunks/511.js:5052:21)
    at headers (/private/tmp/generatemetadata/.next/server/chunks/511.js:4877:62)
    at Module.generateMetadata (/private/tmp/generatemetadata/.next/server/app/page.js:239:37)
    at /private/tmp/generatemetadata/node_modules/next/dist/lib/metadata/resolve-metadata.js:195:24
    at /private/tmp/generatemetadata/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/private/tmp/generatemetadata/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/private/tmp/generatemetadata/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/private/tmp/generatemetadata/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/private/tmp/generatemetadata/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /private/tmp/generatemetadata/node_modules/next/dist/server/lib/trace/tracer.js:106:107 {
  digest: 'DYNAMIC_SERVER_USAGE'
}```

### Describe the Bug

I was using `headers().get('host')` in my generateMetadata() in the layout, but when upgrading to the latest version it started spitting the error mentioned above.

Using `export const dynamic = "force-dynamic";` fixes the problem. 

### Expected Behavior

I expected nextjs to automatically detect the header like it used to !

**Comment by sn3h** [comment]
it seems to me that headers() does not return anything lately (and it did).. 
No matter where used, it returns

`HeadersList {
  [Symbol(headers map)]: Map(0) {},
  [Symbol(headers map sorted)]: null
}`

**Comment by fuyu77** [comment]
We also faced the same issue with version 13.4.11, but we have built successfully with version 13.4.16.

**Comment by huozhi** [comment]
Tested the reproduction against latest 13.4.16, it's fixed now
