### ISSUE TITLE
Docs: improve text selection accessibility

### ISSUE THREAD

**Issue by pnicolli** [vercel/next.js#53055]
### What is the improvement or update you wish to see?

The selection color #f81ce5 does not have good contrast with white text.
For reference: https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=F81CE5

### Is there any context that might help us understand?

This is how I currently see the docs:

![image](https://github.com/vercel/next.js/assets/14176608/b92d61a6-aae7-4b33-bf70-de82d944cc35)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs

<sub>[DX-1809](https://linear.app/vercel/issue/DX-1809/docs-improve-text-selection-accessibility)</sub>

**Comment by darshanjain-entrepreneur** [comment]
![image](https://github.com/vercel/next.js/assets/108680813/f977fba4-7911-4355-aeef-50425569dee5)

**Comment by darshanjain-entrepreneur** [comment]
![Screenshot (60)](https://github.com/vercel/next.js/assets/108680813/1387231d-b4b8-4ad0-b01e-84d29cfa59f2)

**Comment by darshanjain-entrepreneur** [comment]
Is this looks good

**Comment by leerob** [comment]
Hey! Thanks for the suggestion. We'll revisit our selection color site wide as part of our design system. 

https://vercel.com/design/color
