### ISSUE TITLE
Routes named "children" are not accessible in dev mode

### ISSUE THREAD

**Issue by stage-two** [vercel/next.js#53072]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.12-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/spring-rgb-6f7kql

### To Reproduce

1. Create a file named "children.tsx" under the /pages dir
2. Run next.js dev server
3. Try to navigate to `/children` page in the browser

### Describe the Bug

Routes having `/children` substring are not accessible in the dev mode.
In the provided codesandbox example routes `/children` and `/profile/children` do not work while deliberately misspelled `/chiltren` works just fine.

Looks like this behaviour was introduced by https://github.com/vercel/next.js/pull/52362

### Expected Behavior

Pages are accessible in dev/prod mode disregarding their name.

<sub>[NEXT-1514](https://linear.app/vercel/issue/NEXT-1514/routes-named-children-are-not-accessible-in-dev-mode)</sub>

**Comment by darshanjain-entrepreneur** [comment]
Is this a problem or it is specifically done by next js team

**Comment by schlegz** [comment]
Can confirm this in my project as well.
