### ISSUE TITLE
Sorry if this isn't the right place, but I'm seeing the following issue using `next: 13.4.1` on the app router w/ hashes:

### ISSUE THREAD

**Issue by 57u** [vercel/next.js#53075]
I have a similar issue as to the described below.  

My NextJS has has just 2 pages: index.js and stats.js.

Index has multiple sections with IDs, that i link to via hashes in the URL. Stats is just a standalone page.

My navigation looks like so: (simplified for here)
href=/#section1
href=/#section2
href=/stats
 
 When i am on index, and click the nav to go to /stats, the router flashes /stats in the url, but then it goes back to its current url. If i am on /stats and click a hash link, the same happens, it flashes in the url and then stays on /stats page.
 
 I have no extra routing or code that interferes with it.
 
 Is this a new bug or issue?

 
              Sorry if this isn't the right place, but I'm seeing the following issue using `next: 13.4.1` on the app router w/ hashes:

- be on the root route (i.e. `/`)
- click on a `<Link>` with an `href` to a specific section on that page (ex. `<Link href='#contact'>`
  - this correctly jumps down to the element with `id=contact`
- scroll somewhere else on the page & click on a `Link` with `href='/'`
- the page automatically scrolls down to the element with `id=contact`
- if you navigate to a different page and then navigate back to the root route using a `Link` with `href='/'` (i.e. _without_ the `#contact`) without refreshing in between, it will _also_ automatically scroll down to the element with `id='contact'`

guessing this is some sort of uncleared state issue? My workaround currently is to add an id to the top element of my root route and have links go to `href='/#top-element'` so the scroll position isn't disrupted.

_Originally posted by @stephen-spar in https://github.com/vercel/next.js/issues/42157#issuecomment-1560142555_

**Comment by balazsorban44** [comment]
Hi, please follow the [issue template](https://github.com/vercel/next.js/blob/canary/.github/ISSUE_TEMPLATE/1.bug_report.yml) for reporting bugs.
