### ISSUE TITLE
413 Body exceeded 1mb limit

### ISSUE THREAD

**Issue by IgorRSGraziano** [vercel/next.js#53087]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Tue, 11 Jul 2023 05:13:39 +0000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/IgorRSGraziano/nextjs-api-size-issue

### To Reproduce

Try create a new API route on NextJS, and send JSON payload with more than 1MB.

### Describe the Bug

I'm trying to send a request to an API, where the payload is a JSON, and I also send some images, transforming them into base64, and the server immediately returns me a 413, I tried debugging to see if I was stopping in some internal process, but it doesn't even execute the actions of the middleware, nor of my API route.
I'm using NextJS 13, but still with "pages" instead of the App,
I looked in the documentation and found some settings for the next.config file, like this: (https://nextjs.org/docs/pages/building-your-application/routing/api-routes)
api: {
bodyParser: {
sizeLimit: "10mb",
},
},
And this one too: (https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions)
experimental: {
serverActions: true,
serverActionsBodySizeLimit: "10mb",
},

None of the two had any effect, even in Next's start logs it is also reported that these properties do not exist.

### Expected Behavior

be able to send larger size files

### Which browser are you using? (if relevant)

Firefox

**Comment by shuding** [comment]
I can't reproduce it locally. If you are deploying your application to Vercel (which has a 4.5 MB body limitation), please take a look at https://vercel.com/guides/how-to-bypass-vercel-body-size-limit-serverless-functions.

**Comment by IgorRSGraziano** [comment]
@shuding Thanks for the feedback!

Have you tried to play in the added git and check the server's return (DevTools Network)?
I now added a Dokerfile to better isolate the test, and even so the error persists.

I'm not using Vercel servers, the problem occurred locally in a CMS project, I released it to test on the production server (VPS) and the same error persists when trying to send large files (3~10MB).

**Comment by shuding** [comment]
Sorry I just took a look at your code again, it turns out that you added the config to `next.config.js` which is not correct. As per the docs, you need to export the `config` object in your API route (https://nextjs.org/docs/pages/building-your-application/routing/api-routes#custom-config), which is this file: https://github.com/IgorRSGraziano/nextjs-api-size-issue/blob/main/src/pages/api/upload.ts

And it will look like:

```ts
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

type Data = {
	name: string;
};

export default function handler(req: NextApiRequest, res: NextApiResponse<Data>) {
  console.log(req.body);
	res.status(200);
}

export const config = {
  api: {
    bodyParser: {
      sizeLimit: '10mb',
    },
  },
}
```

Let me know if you have other questions.

**Comment by IgorRSGraziano** [comment]
> Sorry I just took a look at your code again, it turns out that you added the config to `next.config.js` which is not correct. As per the docs, you need to export the `config` object in your API route (https://nextjs.org/docs/pages/building-your-application/routing/api-routes#custom-config), which is this file: https://github.com/IgorRSGraziano/nextjs-api-size-issue/blob/main/src/pages/api/upload.ts
> 
> And it will look like:
> 
> ```ts
> // Next.js API route support: https://nextjs.org/docs/api-routes/introduction
> import type { NextApiRequest, NextApiResponse } from "next";
> 
> type Data = {
> 	name: string;
> };
> 
> export default function handler(req: NextApiRequest, res: NextApiResponse<Data>) {
>   console.log(req.body);
> 	res.status(200);
> }
> 
> export const config = {
>   api: {
>     bodyParser: {
>       sizeLimit: '10mb',
>     },
>   },
> }
> ```
> 
> Let me know if you have other questions.

It worked! I had reread that part a few times, but I missed that it exported the configuration in the file itself. Thank you!
