### ISSUE TITLE
dangerouslySetInnerHTML change inserted HTML

### ISSUE THREAD

**Issue by HansLjy** [vercel/next.js#53092]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2
    Binaries:
      Node: 18.12.1
      npm: 9.8.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.12-canary.0
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/floral-sun-j8c8pl?file=%2Fpages%2Findex.tsx%3A1%2C1

### To Reproduce

Just check the output of the relevant code

### Describe the Bug

The html code fed into `dangerouslySetInnerHTML` is `<p>abcde <div>fghi</div> jklmn</p>`, but somehow the rendered result change the inserted HTML into
```html
<div><p>abcde </p><div>fghi</div> jklmn<p></p></div>
```
which has 2 extra p tags

### Expected Behavior

The rendered HTML should be the same as the HTML inside `dangerouslySetInnerHTML`

### Which browser are you using? (if relevant)

Firefox

**Comment by icyJoseph** [comment]
`div` inside `p` is invalid HTML. When received by the browser, the browser changes it! 

However, when you do a "programmatically" HTML injection, or for example let a UI framework such as React, mutate the DOM for you, the browser allows it. 

How can you test this quickly? Well, open your dev tools, go to the Elements section, and Right click on the body tag to `Edit as HTML` then paste `<p>abcde <div>fghi</div> jklmn</p>` in, press Esc, and voíla, the browser forbids the invalid HTML.

- https://caninclude.glitch.me/caninclude?child=div&parent=p

Here's a codesandbox: https://codesandbox.io/s/zen-kepler-x8tshf?file=/public/index.html where the index.html has the invalid HTML you want to render, and hence the browser "edits/fixes" it, and then the React App, "programmatically" creates the DOM nodes and the browser allows it.

**Comment by balazsorban44** [comment]
As pointed out above, this is not a Next.js bug, so closing. Thanks!
