### ISSUE TITLE
Constant being removed in production build.

### ISSUE THREAD

**Issue by ikapta** [vercel/next.js#53096]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.2.0
      npm: 9.6.6
      Yarn: 1.22.19
      pnpm: 7.13.4
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/mantinedev/mantine/issues/4548#issuecomment-1645085370

### To Reproduce

Below code in production build, the `positions` and `rtlPositions` will be removed, but ok in dev mode.

```ts

interface IProps {
  isRtl: boolean | string;
  position: keyof typeof positions;
}

const positions = {
  top: 1,
  left: 2,
  right: 3,
  bottom: 4,
}

const rtlPositions = {
  top: 1,
  right: 2,
  left: 3,
  bottom: 4,
}

export function PositionRender({ isRtl, position }: IProps) {

  const display = (isRtl === 'fe-fe-fe' ? rtlPositions : positions)[position];

  return <h1>
    PositionRender: {display}
  </h1>
}
```
![fa72be97-9928-4b57-8fa6-773bc43fec37](https://github.com/vercel/next.js/assets/1364025/4a2ba1d3-b792-4433-92ab-d3355a19098b)

### Describe the Bug

```
const display = (isRtl === 'fe-fe-fe' ? rtlPositions : positions)[position];
```
`rtlPositions` and `positions` will be transform to an empty object in production build. That code works fine in **@next@13.3.1**, but error occurred in **next@13.4.12**.

### Expected Behavior

the `rtlPositions` and `positions` constant shouldn't be removed.

**Comment by icyJoseph** [comment]
Hi,

This is an SWC issue, which I've reproduced [here](https://play.swc.rs/?version=1.3.70&code=H4sIAAAAAAAAA3WQQW%2FCMAyF7%2FkV7wZInSbYTikdZ26I67RDKS5Ey5IoMdKqrv99bqFUmzYpUp7t%2BPNzlHFMsS4rwnYXfUhoFWDSnq3GwXtLpcMXEkfjTrmUgk%2BGjXca79T4GtwEkmtMp1x1SlUieMqhGKjsg8YyE2WpZo1VL6M5nUU%2F9frgmf2HxnM2QSLb3b%2BcW%2FNqYv7Boc%2FgI6O%2BuKqnYMTtyR0pztvrttndLjp9%2B4uFjBPc1cjRpGDLRjzMhwYURYFZTQ%2FDmWHz06qe1l%2B8jvIt73mR%2BBId1ufli0T4ZUijvc%2FqpL5%2B7N%2FJHuobQRqFVKwBAAA%3D&config=H4sIAAAAAAAAA32VwXLjIAyG73mKjM%2B99rIPsLc%2BA0OMcMhi5EEijaeTd19BnNRt5Fw89v8hCSQhf%2B32%2B%2B5Effdn%2FyWv8jHZTJAf36LQnNheROl4noD6HCbu3u6UqSLOBZpyvYGOs03kMY9rTxlsz3dhEa8%2FzWweoC7pgN6XIF1EJFiCLNIYUvDz2neP45SBaKWJKu7KCImr7G0keFuzjJ%2F0w2%2FTD4gRZPfbxFgyITEMkDXHPcZoJwJztlnxUndqcyDUQlRYGJyZMk4qTy5wwCQxn6kD60yPDhQUMvQczqCZSSwxSyTHU87TsINDGYbWGb%2Bs4WxjsazEhEsriexW8XrEQGx8SVoKb3AjBze4JPe3ZfAmA5ecnu1OGNJGTf4BSAaiJUp2BM1vW%2BGln7as%2FUvLkLy0LM8Kl%2FbWTplgkKSaELyS2ZoZyBy0amZwpYea2V7bzoI30kfBgQHvpVcU1%2FQZuD9qQetoQK8Aqa%2F1WlfdgHncwg1eL8QL%2FFdOyXqDLStGy8dtSvN4wPgiwAh8RPdigZSCcRtnmRKXaZuX5EBaA5y6pFADz0NALgCjiW1WPvWGXA%2FxaIaIh%2B8x8Txv26ML9IGuxHWTdeNdWX4Ktbp1KEsxRkwn6h7Wj0Hc9r677v4DNkYPd1IGAAA%3D)

Please do take it to the SWC repository, https://github.com/swc-project/swc/issues, and provide that reproduction playground. Notice that lowering the SWC version on the playground, fixes the issue.

**Comment by ikapta** [comment]
> Hi,
> 
> This is an SWC issue, which I've reproduced [here](https://play.swc.rs/?version=1.3.70&code=H4sIAAAAAAAAA3WQQW%2FCMAyF7%2FkV7wZInSbYTikdZ26I67RDKS5Ey5IoMdKqrv99bqFUmzYpUp7t%2BPNzlHFMsS4rwnYXfUhoFWDSnq3GwXtLpcMXEkfjTrmUgk%2BGjXca79T4GtwEkmtMp1x1SlUieMqhGKjsg8YyE2WpZo1VL6M5nUU%2F9frgmf2HxnM2QSLb3b%2BcW%2FNqYv7Boc%2FgI6O%2BuKqnYMTtyR0pztvrttndLjp9%2B4uFjBPc1cjRpGDLRjzMhwYURYFZTQ%2FDmWHz06qe1l%2B8jvIt73mR%2BBId1ufli0T4ZUijvc%2FqpL5%2B7N%2FJHuobQRqFVKwBAAA%3D&config=H4sIAAAAAAAAA32VwXLjIAyG73mKjM%2B99rIPsLc%2BA0OMcMhi5EEijaeTd19BnNRt5Fw89v8hCSQhf%2B32%2B%2B5Effdn%2FyWv8jHZTJAf36LQnNheROl4noD6HCbu3u6UqSLOBZpyvYGOs03kMY9rTxlsz3dhEa8%2FzWweoC7pgN6XIF1EJFiCLNIYUvDz2neP45SBaKWJKu7KCImr7G0keFuzjJ%2F0w2%2FTD4gRZPfbxFgyITEMkDXHPcZoJwJztlnxUndqcyDUQlRYGJyZMk4qTy5wwCQxn6kD60yPDhQUMvQczqCZSSwxSyTHU87TsINDGYbWGb%2Bs4WxjsazEhEsriexW8XrEQGx8SVoKb3AjBze4JPe3ZfAmA5ecnu1OGNJGTf4BSAaiJUp2BM1vW%2BGln7as%2FUvLkLy0LM8Kl%2FbWTplgkKSaELyS2ZoZyBy0amZwpYea2V7bzoI30kfBgQHvpVcU1%2FQZuD9qQetoQK8Aqa%2F1WlfdgHncwg1eL8QL%2FFdOyXqDLStGy8dtSvN4wPgiwAh8RPdigZSCcRtnmRKXaZuX5EBaA5y6pFADz0NALgCjiW1WPvWGXA%2FxaIaIh%2B8x8Txv26ML9IGuxHWTdeNdWX4Ktbp1KEsxRkwn6h7Wj0Hc9r677v4DNkYPd1IGAAA%3D)
> 
> Please do take it to the SWC repository, https://github.com/swc-project/swc/issues, and provide that reproduction playground. Notice that lowering the SWC version on the playground, fixes the issue.

Thanks!

**Comment by balazsorban44** [comment]
Closing as it's tracked in SWC, thanks!
