### ISSUE TITLE
Hydration mismatch when using the `useId` hook, when using the `app/` router

### ISSUE THREAD

**Issue by RobinMalfait** [vercel/next.js#53110]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.1
    Relevant Packages:
      next: 13.4.12-canary.0
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/RobinMalfait/server-client-mismatch-example

### To Reproduce

This only happens when using the `app/` router, not when using the `pages` directory. When you run the reproduction repo (`next dev`) and open your browser, then the warning is available in your console.

### Describe the Bug

When using the `useId` hook result in on of the attributes or as the contents of an element, then a mismatch is shown.

```
Warning: Prop `data-id` did not match. Server: ":R1mcq:" Client: ":R6pj9:"
```

The following code should be enough to reproduce this:
```js
"use client";

import {useId} from "react"

export function Example() {
  let id = useId()
  return <div data-id={id}>My Example</div>
}
```

### Expected Behavior

I expect that no mismatch issue is happening.

<sub>[NEXT-1470](https://linear.app/vercel/issue/NEXT-1470/hydration-mismatch-when-using-the-useid-hook-when-using-the-app-router)</sub>

**Comment by hrasoa** [comment]
I also have this issue. Here a sandbox to reproduce: https://codesandbox.io/p/sandbox/next-js-fxis37

**Comment by icyJoseph** [comment]
It'd seem that is only happening on dev mode, correct?

**Comment by icyJoseph** [comment]
Alright, it looks like something has gone wrong in https://github.com/vercel/next.js/compare/v13.4.11-canary.0...v13.4.11-canary.1

**Comment by icyJoseph** [comment]
It has to be that somehow in the server there's a React tree structure, and on the client there's another one. Perhaps some wrapping code that changes, but I've not been able to pinpoint where exactly. I thought it had to do with the dev server hot reloading, but nope.

**Comment by icyJoseph** [comment]
I think the issue has been introduced at https://github.com/vercel/next.js/pull/52843, doing local dev with 3e821ef1893a42e4f247364000785eb806bf2211 works fine, but using 4994a428ae5beeeb5e0ece1d791458a5ab1c41b2 fails.

**Comment by icyJoseph** [comment]
More updates. Skipping this branch, https://github.com/vercel/next.js/blob/canary/packages/next/src/client/app-index.tsx#L249 fixes the issue.

**Comment by icyJoseph** [comment]
I'd seem that there's two ReactDevOverlay wrappers, one of which happens only client side. 4994a42 PR introduced another overlay. My guess is that this generates different React trees, which leads to useId divergence.

**Comment by emirefek** [comment]
"next": "13.4.12"

I'm using this version. When hotfix will be available? If it won't be live soon how can I install canary version of next? Is there a guide/docs?

**Comment by icyJoseph** [comment]
> "next": "13.4.12"
> 
> I'm using this version. When hotfix will be available? If it won't be live soon how can I install canary version of next? Is there a guide/docs?

To install Canary you do `npm install next@canary`. The same goes for yarn or pnpm.


I guess they'll release it soon enough :)
