### ISSUE TITLE
Debugging with NODE_OPTIONS='--inspect=0.0.0.0' next dev causes errors

### ISSUE THREAD

**Issue by mkoreo** [vercel/next.js#53127]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:22 +0000
    Binaries:
      Node: 20.3.1
      npm: 8.19.2
      Yarn: N/A
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/blame/8d83d85e5359146bbbd0f96ea2f8490e7d6bc9cd/packages/next/src/cli/next-dev.ts#L488

### To Reproduce

NODE_OPTIONS='--inspect=0.0.0.0' next dev

### Describe the Bug

NodeJS's --inspect switch takes an optional address as a parameter that isn't being honored by Next. Next crashes when that is present.
spec: --inspect[=[host:]port]
https://nodejs.org/api/cli.html#--inspecthostport

In order to be able to expose a debugger from inside a Docker container, it has to listen on 0.0.0.0 instead of the default 127.0.0.1. To do that, we have to specify --inspect=0.0.0.0:9229.

The result of doing this is:
```
- info the --inspect option was detected, the Next.js proxy server should be inspected at port 0.
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info the --inspect option was detected, the Next.js routing server should be inspected at port 1.
/usr/local/bin/node:  must be 0 or in range 1024 to 65535.
```

This **and the root cause** has been clearly described earlier in: https://github.com/vercel/next.js/issues/47083 but not fixed, as mentioned by gregmartyn in https://github.com/vercel/next.js/issues/47083#issuecomment-1572453046

This has also been described in (and presumably fixed but not accepted) in https://github.com/vercel/next.js/pull/47671

### Expected Behavior

Start node debugger on 0.0.0.0 and default ports 9232 & 9233 instead of parsing "0.0.0.0" as a port only integer.
Honor the node --inspect switch parameters.

**Comment by khuezy** [comment]
I think it's broken in the latest version, even `--inspect` w/o any arguments fails. It looks like it opens 2 inspector 9229 and 9230 but none of the break points works when you attach on either port.

**Comment by HelmerBarcos** [comment]
Its is a duplication of https://github.com/vercel/next.js/issues/47083. I will create a PR in order to fix this. This should help people debugging an nextjs application that runs in a docker container

**Comment by simonstaton** [comment]
For anyone facing the same issue, there is a temporary workaround to define the inspect argument twice initially with only the port --inspect=9229 --inspect=0.0.0.0

**Comment by x-yuri** [comment]
I also ran into it while trying to debug `nextjs` in a `docker` container. `node_module/.bin/next dev` starts the dev server [here][a]. And before that it [amends the node options][b] (to make the child bind to the next port, to be able to debug both processes). The thing is, [`getDebugPort`][c] and the "change the options" code (the previous link) handle only the `--${nodeDebugType}=PORT` case. But there's also [`--${nodeDebugType}=HOST:PORT` and `--${nodeDebugType}=HOST`][d].

[a]: https://github.com/vercel/next.js/blob/v14.0.4-canary.32/packages/next/src/cli/next-dev.ts#L246-L257
[b]: https://github.com/vercel/next.js/blob/v14.0.4-canary.32/packages/next/src/cli/next-dev.ts#L241-L243
[c]: https://github.com/vercel/next.js/blob/v14.0.4-canary.32/packages/next/src/server/lib/utils.ts#L14-L22
[d]: https://nodejs.org/api/cli.html#--inspecthostport

**Comment by StefanMeindlDatenKraft** [comment]
I tried the fix from [x-yuri](https://github.com/x-yuri) but its still not working for me (using the node alpine 3.18 img with  `yarn run dev` as start command and `NODE_OPTIONS='--inspect=0.0.0.0' next dev` for the dev script in the package.json)

Is there any fix comming? Or did I miss something?

**Comment by x-yuri** [comment]
@StefanMeindlDatenKraft I just confirmed that the workaround [works][a]. If it still doesn't for you, I expect a long explanation, as I did.

[a]: https://gist.github.com/x-yuri/26b2630700656caf902ec101401f9d6e

**Comment by StefanMeindlDatenKraft** [comment]
@x-yuri what was your output from next js? Did it also start two debugger for you on 9229 and 9230?

**Comment by StefanMeindlDatenKraft** [comment]
Yeah that is what I meant, it does not show up in `chrome://inspect`. 

I do have a docker-compose.yml where I expose the app port, `9229` and `9230` and start it with `docker-compose up`. With my nextjs app I get 2 messages. When i create a fresh one I get just 1 but still with `Starting inspector on 0.0.0.0:9230 failed: address already in use`. And I followed the steps 1:1. 

Btw thanks for the tip with `sleep infinity`

**Comment by x-yuri** [comment]
When I do `-p 9229:9229` in place of `-p 127.0.0.1:9229:9229` the node processes don't show up in `chrome://inspect` for some reason.

"address already in use" is expected. My patch makes all children try to use `9230`. Only the first one succeeds. Usually that's not a problem. Particularly most likely in your case and in the case in the gist.

For `9230` to work it should be added to the list:

![](https://i.imgur.com/Dfn6uGO.png)
![](https://i.imgur.com/e8iUnsQ.png)

**Comment by StefanMeindlDatenKraft** [comment]
So the problem was with the docker configuration, I am still trying to figure out what the difference between my config and the docker run config of yours is, but when I use the docker run ... alpine:3.18 it works and I can inspect.

I will post again when I find the issue. Thanks for your help and quick replies @x-yuri

**Comment by alessandrojcm** [comment]
Is there any progress or workaround for this issue? I need to debug an issue that only happens inside a container and I cannot seem to attach the debugger. Passing `--inspect=0.0.0.0:9229` makes the container exit with `must be 0 or in range 1024 to 65535`. Passing only the inspect flag works but it binds to `127.0.0.1`

**Comment by StefanMeindlDatenKraft** [comment]
As mentioned in @x-yuri s guide you have to change the sourcecode of next with this command: `sed -Ei '/NODE_OPTIONS.*nodeDebugType.*/s//NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=0.0.0.0:9230`;/' node_modules/next/dist/cli/next-dev.js
/my-app # diff -u node_modules/next/dist/cli/next-dev.js.bak node_modules/next/dist/cli/next-dev.js`

**Comment by alessandrojcm** [comment]
> As mentioned in @x-yuri s guide you have to change the sourcecode of next with this command: `` sed -Ei '/NODE_OPTIONS.*nodeDebugType.*/s//NODE_OPTIONS = `${NODE_OPTIONS} --${nodeDebugType}=0.0.0.0:9230`;/' node_modules/next/dist/cli/next-dev.js /my-app # diff -u node_modules/next/dist/cli/next-dev.js.bak node_modules/next/dist/cli/next-dev.js ``

That did it, thanks very much.

**Comment by jeroenbegyn** [comment]
Workaround also works for me!

**Comment by timmywil** [comment]
Worth pointing out that the workaround shows how easy this would be to fix. Let's get the fix in a release.

**Comment by sitole** [comment]
Currently still relevant issue.
It's not possible to propagate debugger from Docker container because by default it listens only on internal IP.
