### ISSUE TITLE
Production server returns 500 when URL contains relative path segment

### ISSUE THREAD

**Issue by mikesurowiec** [vercel/next.js#53126]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 20.4.0
      npm: 9.7.2
      Yarn: 1.22.17
      pnpm: 7.5.0
    Relevant Packages:
      next: 13.4.12-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/mikesurowiec/next-relative-path-bug

### To Reproduce

1. Build and run a production version of the app. 
2. `curl` a non-existent url that includes `..`. Make sure to use the `--path-as-is` flag.

```sh
$ npm run build
$ npm run start
$ curl -i --path-as-is localhost:3000/my/../path
```

Response
```
HTTP/1.1 500 Internal Server Error
Internal Server Error
```

### Describe the Bug

The development version of the server correctly returns a `404 Not Found` response when attempting to access non-existent routes with a relative path segment. 

The production version of the server returns a 500 error given the same request.

A brief investigation seems to indicate it's related to how the `NormalizeError` is caught and handled versus re-thrown.

### Expected Behavior

The production server should return a `404 Not Found`, same as the development server.

### Which browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

n/a

<sub>[NEXT-1554](https://linear.app/vercel/issue/NEXT-1554/production-server-returns-500-when-url-contains-relative-path-segment)</sub>

**Comment by timredband** [comment]
What's the status of this? This is a major issue in production still and doesn't look like it's getting much traction.

**Comment by jessepostwapo** [comment]
We're also looking for this to be released! We'd appreciate an update on this issue.

**Comment by ztanner** [comment]
Hi! I’m no longer able to reproduce this behavior after testing with the latest version of next (13.5.2 at time of writing this). Going to close this issue but don’t hesitate to reply with a repro in case you’re still having troubles. Thank you!
