### ISSUE TITLE
Docs: Deploying > Self-Hosting > Node.js Server > server.js file?

### ISSUE THREAD

**Issue by MicaelPiresX** [vercel/next.js#53159]
### What is the improvement or update you wish to see?

I think it would be very helpful to have a 'server.js' file template in the 'Deploying > Self-Hosting > Node.js Server' section of the documentation.

### Is there any context that might help us understand?

I was trying to deploy a test Next.js app (using the app router) to a Shared Hosting (using cPanel).
When I was creating the Node.js app on the cPanel, I needed the startup file, which there is no suggestions on how it or how it should be, on the Next.js docs.

**Comment by balazsorban44** [comment]
The file is generated for you with all the necessary assets when you set the `output: "standalone"` option in `next.config.js`.

Check out https://nextjs.org/docs/app/api-reference/next-config-js/output for more info.

**Comment by MicaelPiresX** [comment]
@balazsorban44, thank you very much for the information, I hadn't noticed that part of the documentation yet.
Still, following the logic described in this docs, I wasn't able to deloy the app, and from what I see on [Stackoverflow](https://stackoverflow.com/questions/76519757/how-to-deploy-a-nextjs-13-app-using-app-router-in-cpanel) there are more people with the same problem.
I think the docs should be clearer on this type of deloyment.
