### ISSUE TITLE
Next 13 app dir localization bug

### ISSUE THREAD

**Issue by 2hmad** [vercel/next.js#53167]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2
    Binaries:
      Node: 18.16.0
      npm: 9.6.6
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Internationalization (i18n)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/github/2hmad/next13-app-dir-localization/main

### To Reproduce

1. Create parent locale param inside the app directory to contain all routes
2. Define supported locales in exported cost called `i18n`
3. Implement Dictionaries to get translated words from locale JSON file based on locale param
4. Handle get current locale from headers in middleware
5. Add locale to pathname if not found
6. Navigate to the blog page after changing to other locales except for the default locale

### Describe the Bug

I created a localization using nextjs 13 app dir and set the supported locales to ar and en, with en being the default. However, when I navigate to the ar locale, it automatically switches back to en. I'm seeking assistance to resolve this issue.

### Expected Behavior

The new locale should be fixed in the URL while navigating not revert to the default locale

**Comment by Ayterx** [comment]
Related to https://github.com/vercel/next.js/issues/49686
This should be fixed today https://github.com/vercel/vercel/pull/10243#issuecomment-1649835410

**Comment by cloetensbrecht** [comment]
It seems that the url of the Blog button is wrong.
You're navigating to /blog, but it should be /ar/blog or /en/blog as you need to have the locale as a first path part:

``` javascript
<Link href={`/${locale}/blog`}>Blog</Link>
```

**Comment by 2hmad** [comment]
> It seems that the url of the Blog button is wrong. You're navigating to /blog, but it should be /ar/blog or /en/blog as you need to have the locale as a first path part:
> 
> ```js
> <Link href={`/${locale}/blog`}>Blog</Link>
> ```

There are no other methods except this one? :/

**Comment by cloetensbrecht** [comment]
> There are no other methods except this one? :/

It depends of what you exactly wants. But for now your `middleware.js` is checking for a locale within the pathname. (Lines 18-20).
When no locale was set within the pathname, it will redirect you to the browser language or the default language followed by the pathname (Line 25 - 27).

So if you want to use the current implementation, you just need to be sure to add the locale in every link:
`/en`
`/en/blog`
`/ar`
`/ar/blog`
And not use `/blog` without a locale because it will be redirected to `/en/blog` (Line 25 - 27 inside `middleware.js`).

I would also recommand to use TypeScript to prevent writing errors.

**Comment by 2hmad** [comment]
> > There are no other methods except this one? :/
> 
> It depends of what you exactly wants. But for now your `middleware.js` is checking for a locale within the pathname. (Lines 18-20).
> When no locale was set within the pathname, it will redirect you to the browser language or the default language followed by the pathname (Line 25 - 27).
> 
> So if you want to use the current implementation, you just need to be sure to add the locale in every link:
> `/en`
> `/en/blog`
> `/ar`
> `/ar/blog`
> And not use `/blog` without a locale because it will be redirected to `/en/blog` (Line 25 - 27 inside `middleware.js`).
> 
> I would also recommand to use TypeScript to prevent writing errors.


I completed the task. However, the documentation for "next" does not provide clear instructions on how to handle navigation with localization. I have been considering alternative methods for achieving this.

By the way, I use TypeScript in my project. The code provided is just for testing purposes.

Thanks 🙏🏻
