### ISSUE TITLE
Intercepting routes don’t work with route groups

### ISSUE THREAD

**Issue by kachkaev** [vercel/next.js#53170]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.10
    Relevant Packages:
      next: 13.4.13-canary.1
      eslint-config-next: 13.4.13-canary.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/kachkaev/next-js-intercepting-routes-in-groups-mwe

Here is the ‘product spec’:

> The app is a photo browser, similar to [nextgram](https://github.com/vercel-labs/nextgram).
> There are three navigation pages:
> 1. Home page (recent photos)
> 2. top photos
> 3. best photo
>
> When users navigate to a photo on the first two pages, it should open in a modal.
> When users navigate to a photo on the third page, it should open in a new page, not in a modal.
> Each photo page has previous / next links. Neighbouring photos open in the same way: in a modal or in a new page*.
> 
> ---
> \* When I add previous / next links in the [nextgram](https://github.com/vercel-labs/nextgram) app, neighbouring photos always open in a modal. This creates modals on the standalone photo page, which is what I am trying to avoid:
>
> https://github.com/vercel/next.js/assets/608862/9fc693d4-3579-4e09-b9d7-a69a0fe313ce

### To Reproduce

1.  Clone the repo:

    ```sh
    git clone https://github.com/kachkaev/next-js-intercepting-routes-in-groups-mwe.git
    cd next-js-intercepting-routes-in-groups-mwe
    pnpm install
    pnpm dev
    ```

1.  Inspect the folder structure:

    ```txt
    app/
    ├── (no-modal)
    │   ├── best-photo
    │   │   └── page.tsx
    │   ├── layout.tsx
    │   └── photo
    │       └── page.tsx
    ├── (with-modal)
    │   ├── @modal
    │   │   ├── (...)photo
    │   │   │   └── page.tsx
    │   │   ├── page.tsx
    │   │   └── top-photos
    │   │       └── page.tsx
    │   ├── layout.tsx
    │   ├── page.tsx
    │   └── top-photos
    │       └── page.tsx
    └── layout.tsx
    ```
    
    Here is the technical solution I have come up with based on the docs:

    - There is a root layout for global navigation, CSS reset, custom fonts, etc.
    - There are two route groups called `(no-modal)` and `(with-modal)`.
    - Home page and ‘top photos’ page are in the `(with-modal)` group.
    - The layout file in this group contains a slot called `@modal` which renders a photo page using an intercepting route.
    - The ‘best photo’ page is in the `(no-modal)` group, together with the photo page itself.
    - In addition to the intercepting route for a photo, `app/(with-modal)/@modal` also contains dummy routes for the home page and the ‘top photos’ page to avoid 404s. I know it is possible to add `default` or `catch-all` routes to this folder too, but doing so would blur the distinction between the two route groups and thus make the reproduction a bit less vivid.
    
    The reproduction example does not use dynamic routes for simplicity. Photo ids are encoded in a GET param. Going for `photo/[id]` produces the same results (see below).

1.  Open http://localhost:3000 and navigate between the home page and the ‘top photos’ page. Click on individual photo links within these pages and observe them opened in the modal, as expected. We are in the same route group called `(with-modal)`, all works fine so far.
    
    https://github.com/vercel/next.js/assets/608862/e6c4bc14-cbea-416e-b960-c92f3502aa85

1.  **Broken scenario 1:** While on a photo page, press refresh in the browser. Observe that the photo page is opened in a new page, not in a modal. This is expected. Now try navigating to a previous or a next photo and observe an error:

    ```
    Unhandled Runtime Error
    Error: notFound() is not allowed to use in root layout
    ```

    https://github.com/vercel/next.js/assets/608862/c7f8fce5-7fca-499f-b858-2ebdb7f83dca

1.  **Broken scenario 2:** Navigate to the ‘best photo’ page and observe that it uses `(no-modal)` layout, as expected. Navigate to a photo page and observe the same error as above.

    https://github.com/vercel/next.js/assets/608862/5bfbb122-4564-482a-8c3f-c4d222d97b0d

1.  **Broken scenario 3:** Open the photo page and observe that it uses `(no-modal)` layout, as expected. Make a small tweak in `/app/(no-modal)/photo/page.tsx` to trigger hot reloading. Observe `notFound()` error again:

    <img width="724" alt="broken-scenario-3" src="https://github.com/vercel/next.js/assets/608862/680be215-7447-46ff-b429-65d0ed012822">

### Describe the Bug

Seems like Next.js is unable to deal with intercepting routes and route groups at the same time. Presence of `app/(with-modal)/@modal/(...)photo/page.tsx` breaks navigation to `/photo` from pages where this route is not intercepting.

The same happens for dynamic routes (i.e. when `/photo?id=123` is replaced with `/photo/123`). See the [PR #1](https://github.com/kachkaev/next-js-intercepting-routes-in-groups-mwe/pull/1) in the reproduction repo.

<img width=350 src="https://github.com/vercel/next.js/assets/608862/c2bf80ce-6d72-415c-9c5a-814d2d2f03a2"> &nbsp; → &nbsp; &nbsp; <img width=350 src="https://github.com/vercel/next.js/assets/608862/195c9e63-cd79-47f1-95e9-23f9fcb49e08">

### Expected Behavior

I would expect that the app would work according to product spec described earlier. The folder structure I have come up with seems to match Next.js docs for the listed requirements. Avoiding modals at least on the photo page is crucial and I am not sure how to do this without using route groups and intercepting routes.

Perhaps, this is just a matter of docs and I am just missing something. I have been trying various workarounds for quite a few hours last weekend but have not solved the problem no matter what I have tried. Hope that the reproduction example is helpful.

### How are you deploying your application? (if relevant)

I have not tried deploying this app yet, but if I try `pnpm build && pnpm start`, navigation remains broken in the same scenarios as during `pnpm dev`. There are two key differences:

1.  Error message says:
    ```
    Application error: a server-side exception has occurred (see the server logs for more information).
    Digest: NEXT_NOT_FOUND
    ```
2.  Unlike in `pnpm dev`, browser URL does not update when a broken link is followed.

https://github.com/vercel/next.js/assets/608862/871cf1ed-bf8c-4415-bebf-0ce9f72c3073

---

**PS**: Despite this situation and some level of frustration caused by it, I find the new router pretty awesome. So let me use this bug report as an opportunity to thank the Next.js community for working on it! I know that some developers  struggle with the new model because of the things they’ve got used to, but I do see a lot of value in the change! Epic stuff! 👏

**Comment by unoscar** [comment]
Having the same issue, heavily relying on group routes and want to add intercepting to my site

**Comment by thongbn** [comment]
mine same problem , work fine in dev mode but 404 in production build
Here is my project folder
![image](https://github.com/vercel/next.js/assets/14286010/56720538-78a3-4329-8c0f-27772aa01f3b)

**Comment by bilalesi** [comment]
the same issue with routes groups

**Comment by jmarbutt** [comment]
I am also having this issue.

**Comment by jma1020** [comment]
Having the same issue.

**Comment by wawle** [comment]
Having the same issue.

**Comment by iandesignmilano** [comment]
> il mio stesso problema, funziona bene in modalità sviluppatore ma 404 nella build di produzione Ecco la cartella del mio progetto ![Immagine](https://private-user-images.githubusercontent.com/14286010/261785824-56720538-78a3-4329-8c0f-27772aa01f3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODM2ODYsIm5iZiI6MTcwNDk4MzM4NiwicGF0aCI6Ii8xNDI4NjAxMC8yNjE3ODU4MjQtNTY3MjA1MzgtNzhhMy00MzI5LThjMGYtMjc3NzJhYTAxZjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE0Mjk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiZDFjYjZjMWVhNDgxMTY0ZmRmYWYzMGZjZjE2MTgzMTJkOTAyOWNkMzI1OTAxMjA2YzVlMDUyZmYyY2FiNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OU8sM1_Mf5Uh3M3lAYNx4iBdC3ANdgFCT_8m5Z9nSWw)
> 
> Esegui ancora il rendering e funziona in modalità sviluppatore ![Immagine](https://private-user-images.githubusercontent.com/14286010/261785924-0ef4e281-42dd-4c98-9721-9a2d0f603c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODM2ODYsIm5iZiI6MTcwNDk4MzM4NiwicGF0aCI6Ii8xNDI4NjAxMC8yNjE3ODU5MjQtMGVmNGUyODEtNDJkZC00Yzk4LTk3MjEtOWEyZDBmNjAzYzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE0Mjk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YjFlNjcwNWJhMjQ1Y2I2N2ZmMjMwMzJmNWUzYTlmZjlmMzc4NTExNjVmYzE3MmRkOTAyM2I5NDAzYjNjZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EKwc4KOd-GNXzlAznxv9gywH6fN0c0sWZFoeYgreAX8)

I have the same problem

**Comment by decanTyme** [comment]
Here's my setup after following the [docs](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#modals):

![image](https://github.com/vercel/next.js/assets/74456102/a79df6bc-9e33-4233-bc88-fa6c939b5633)

I basically wanted to group all settings stuff so it doesn't clutter when I'm not working on it. It should intercept and overlay whatever's in `/[user]`, but I only get a 404. The odd thing is that the `(.)settings` **_does_** get imported by the fact that:

![image](https://github.com/vercel/next.js/assets/74456102/2d600ac0-657e-4354-93b4-1d76e40fb1dd)

```tsx
// app/(settings)/@settings/(.)settings/page.tsx
export default function SettingsIntercept() {
  console.log("SettingsIntercept!")

  return (
    <Modal>
      <SettingsSidebar />
    </Modal>
  )
}
```
 
Only works when I yank both `@settings` and `settings` out of `(settings)` and put them into `app` directly.

**Comment by Vladimir21500** [comment]
> mine same problem , work fine in dev mode but 404 in production build Here is my project folder ![image](https://private-user-images.githubusercontent.com/14286010/261785824-56720538-78a3-4329-8c0f-27772aa01f3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjUyMjAsIm5iZiI6MTcxMzg2NDkyMCwicGF0aCI6Ii8xNDI4NjAxMC8yNjE3ODU4MjQtNTY3MjA1MzgtNzhhMy00MzI5LThjMGYtMjc3NzJhYTAxZjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZTgxOTgwYjczZTZiMDU2NWY4ZmQwMjIzYWFiM2VhOTViYzFiMzg1ZjU4YjEwMDRmZTNmMWMxMjUzZjQzYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YzCttRwsf9P7_XxJeZWRlQ-Rhn3pbcrlgOocwsgE9PU)
> 
> Still render and working in dev mode ![image](https://private-user-images.githubusercontent.com/14286010/261785924-0ef4e281-42dd-4c98-9721-9a2d0f603c55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjUyMjAsIm5iZiI6MTcxMzg2NDkyMCwicGF0aCI6Ii8xNDI4NjAxMC8yNjE3ODU5MjQtMGVmNGUyODEtNDJkZC00Yzk4LTk3MjEtOWEyZDBmNjAzYzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMDIwNTY5NTQ3ZjdmYmY1M2ZkNWEyNjQwMWI3OTczMzdjMjE3ZmZkOTMzYjZlZGYyZTIxNjQ3NWI5ZTdlYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-eHCM34mYq1SssLzxAdMnTyRR5CiIhW1DRMDd6HugeM)

JUst curious: are yours (.)cart/page.tsx and cart/page.tsx the same?

**Comment by ztanner** [comment]
Hi @kachkaev (and others)! Apologies for the delay in responding. Recently I've been working through the various parallel routes & interception routes issues. I took a look at the provided reproduction and I was able to get all scenarios working as expected, so I think we were able to address the problems you were running into!

### Scenario 1

https://github.com/vercel/next.js/assets/1939140/3a910a1a-b5ff-46e1-9f4a-3f01c20ff1f6

### Scenario 2

https://github.com/vercel/next.js/assets/1939140/caa6cd78-adf1-4a20-9301-2c56484f2dee

### Scenario 3

https://github.com/vercel/next.js/assets/1939140/97b368f3-1b5f-486e-b452-57f084146636

The only thing I noticed that was missing was a `app/(with-modal)/default.tsx` file to handle the case where the `children` slot in `app/(with-modal)/layout.tsx` isn't matched with a page route (as is the case currently when it triggers route interception).

I'm going to close this issue, but happy to answer any additional questions, or look at other bug reproductions. Thank you!

**Comment by chochoZusebmt** [comment]
> Hi @kachkaev (and others)! Apologies for the delay in responding. Recently I've been working through the various parallel routes & interception routes issues. I took a look at the provided reproduction and I was able to get all scenarios working as expected, so I think we were able to address the problems you were running into!
> 
> ### Scenario 1
>  CleanShot.2024-04-23.at.17.33.11.mp4 
> ### Scenario 2
>  CleanShot.2024-04-23.at.17.34.17.mp4 
> ### Scenario 3
>  CleanShot.2024-04-23.at.17.37.17.mp4 
> The only thing I noticed that was missing was a `app/(with-modal)/default.tsx` file to handle the case where the `children` slot in `app/(with-modal)/layout.tsx` isn't matched with a page route (as is the case currently when it triggers route interception).
> 
> I'm going to close this issue, but happy to answer any additional questions, or look at other bug reproductions. Thank you!

Hi @ztanner 

Thanks for your solution.

Please post application file structure and maybe source code for corresponding file. I'm facing this issue and nextjs documentation doesn't give enough information.

**Comment by olehakon** [comment]
> The only thing I noticed that was missing was a `app/(with-modal)/default.tsx` file to handle the case where the `children` slot in `app/(with-modal)/layout.tsx` isn't matched with a page route (as is the case currently when it triggers route interception).

Can you elaborate on why this is the case? Aren't the children defined when navigating to an intercepted route? Am I missing something here?

**Comment by ztanner** [comment]
> > The only thing I noticed that was missing was a `app/(with-modal)/default.tsx` file to handle the case where the `children` slot in `app/(with-modal)/layout.tsx` isn't matched with a page route (as is the case currently when it triggers route interception).
> 
> Can you elaborate on why this is the case? Aren't the children defined when navigating to an intercepted route? Am I missing something here?

In the provided repro, the app transitions to a new layout (from `app/(no-modal)/layout.tsx` to `app/(with-modal)/layout.tsx`. The route that's transitioned to matches the interception route (which fills the `@modal` slot), but nothing matches to the `children` slot. When a slot is encountered for the first time and it can't find a match, it uses `default.tsx`. The default `default.tsx` behavior is to throw a `notFound()` error.
