### ISSUE TITLE
Multiline environment variables dont work as expected

### ISSUE THREAD

**Issue by nuntax** [vercel/next.js#53183]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.2
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/nuntax/next-js-bugreport

### To Reproduce

Have a multiline environment variable like a ecdsa key for JWT usage.
.env.local:
```
PUBLIC_KEY='-----BEGIN PUBLIC KEY-----
multi-line
-----END PUBLIC KEY-----'
```
When now logging the environment variable:
`console.log(process.env.PUBLIC_KEY)`
The console output looks like the following:
`'-----BEGIN PUBLIC KEY-----`

 
 

### Describe the Bug

Only the first line of the environment variable is getting loaded.
Weirdly enough adding the experimental --turbo flag to next dev resolves the issue.

### Expected Behavior

The expected behaviour is that the entire variable is loaded and that
`console.log(process.env.PUBLIC_KEY)`
prints
```
PUBLIC_KEY='-----BEGIN PUBLIC KEY-----
multi-line
-----END PUBLIC KEY-----'
```

**Comment by balazsorban44** [comment]
This is currently not possible, as it would be a breaking change to update `dotenv`.

You can follow this PR: https://github.com/vercel/next.js/pull/38481#issuecomment-1608424103

**Comment by nuntax** [comment]
For anyone looking for a workaround, just replace the line breaks with \n.
