### ISSUE TITLE
with-stripe-typescript example fails to read router.query.session_id in results.tsx

### ISSUE THREAD

**Issue by CaesuraMediaNet** [vercel/next.js#53208]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.3
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.4
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

with-stripe-typescript 

### What browser are you using? (if relevant)

Chrome Version 114.0.5735.198 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

Locally

### Describe the Bug

**Install Example Stripe :** 
```
npx create-next-app --example with-stripe-typescript with-stripe-typescript
cd with-stripe-typescript
Add Stripe secrets to .env.local
npm install
npm run dev
```

**Browser**
http://localhost:3000/use-shopping-cart
Add to Cart
Checkout 
Stripe Test Mode
Proceed with test credit card, Stripe redirects to :
http://localhost:3000/result?session_id=cs_test_...

**Browser console - continuous warnings :** 
`_client.js:1 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render._`

**Results Page :** 
Status: loading...
CheckoutSession response:
"loading..."
Cart cleared.

**Next dev console :** 
```
A non-serializable value was detected in an action, in the path: `register`. Value: [Function: register]
Take a look at the logic that dispatched this action:  {
  type: 'persist/PERSIST',
  register: [Function: register],
  rehydrate: [Function: rehydrate]
}
(See https://redux.js.org/faq/actions#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants)
(To allow non-serializable values see: https://redux-toolkit.js.org/usage/usage-guide#working-with-non-serializable-data)
```

Looking at `pages/result.tsx` :` router.query.session_id is null`, there are no query parameters from `useRouter(),` when I manually paste the one in from Stripe, it works fine and gives me the transaction data.

Why don't I get` router.query.session_id `from `useRouter() `then?

Thanks for any responses!

### Expected Behavior

Should get ` router.query.session_id `from `useRouter() ` and the page should show the transaction data.

### To Reproduce

As above

**Comment by darshanjain-entrepreneur** [comment]
lient.js:1 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render._

this is happening because you are updating the state inside useeffect which lead to continous calling for useEffect
You should either insert empty array with useEffect so that it runs once or stop updating the state inside useEffect.

**Comment by CaesuraMediaNet** [comment]
Hi darshanjain-entrepreneur - this is not my code, it's the example code from Next.js.

**Comment by CaesuraMediaNet** [comment]
Research so far : in ```./components/ClearCart.tsx``` : 
```
import { useEffect } from 'react'
import { useShoppingCart } from 'use-shopping-cart'

export default function ClearCart() {
  const { clearCart } = useShoppingCart()

  useEffect(() => {
    clearCart()
  }, [clearCart]) // remove this?

  return <p>Cart cleared.</p>
}
```
If I remove the ```clearCart``` from the ```useEffect``` braces I get no errors and I get the transaction details all ok.  Except that the cart is not cleared. I'll keep looking for solutions to this, but I don't understand why Vercel's live demo works and the code doesn't...

**Comment by leerob** [comment]
We recently completely overhauled this example https://github.com/vercel/next.js/tree/canary/examples/with-stripe-typescript

Check it out and let us know what you think!
