### ISSUE TITLE
CodeSandbox Reproduction Template doesn’t work

### ISSUE THREAD

**Issue by simonhrogers** [vercel/next.js#53205]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
CodeSandbox
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/s/github/vercel/next.js/tree/canary/examples/reproduction-template

### To Reproduce

Visit: https://codesandbox.io/s/github/vercel/next.js/tree/canary/examples/reproduction-template

### Describe the Bug

I wanted to put together a minimal reproduction but the codesandbox template doesn’t load, says GitHub auth may have expired. 

https://codesandbox.io/s/github/vercel/next.js/tree/canary/examples/reproduction-template

### Expected Behavior

The CodeSandbox linked to by this issue creator to be useable. 

### Which browser are you using? (if relevant)

Chrome 114

**Comment by balazsorban44** [comment]
Hi, I could not reproduce this, so will close for now, but please open a new issue if you are still seeing this. In that case, I'll try to reach out to the CodeSandbox team.

![image](https://github.com/vercel/next.js/assets/18369201/d9e1df1a-0c79-49dd-9650-60884d6d2431)

**Comment by simonhrogers** [comment]
<img width="1865" alt="Screenshot 2023-07-28 at 14 54 54" src="https://github.com/vercel/next.js/assets/12583581/df2a5020-a84d-45c8-a4be-bf2153c7419a">

@balazsorban44 This is what I am seeing, still broken
