### ISSUE TITLE
Docs: The wrong file extension is in the Custom Errors page's example

### ISSUE THREAD

**Issue by hshqwq** [vercel/next.js#53218]
### What is the improvement or update you wish to see?

The example file is js, but the content of the file is jsx. Fix it, please.

### Is there any context that might help us understand?

look at each examples in <https://nextjs.org/docs/pages/building-your-application/routing/custom-error>

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/routing/custom-error

**Comment by darshanjain-entrepreneur** [comment]
It does'nt matter because you can write jsx in .js file

**Comment by hshqwq** [comment]
Oh, sorry I don't know that.

But for new typescript users, maybe they will use the `.ts` file, it will make error. Of course, it's up to your choose. And thanks for your answer
