### ISSUE TITLE
Not found page, component loses styles

### ISSUE THREAD

**Issue by andelkocvjetkovic** [vercel/next.js#53210]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 20.2.0
      npm: 9.8.0
      Yarn: 3.2.3
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.13-canary.3
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

code: https://github.com/andelkocvjetkovic/nextjs-bug
link: https://nextjs-bug-tau.vercel.app/

### To Reproduce

run 
```
npm run build
npm  run start
```

1. Click on button 'Not Found' which leads to not-found page.
2. Click on button 'Home' which leads back to home page

https://github.com/vercel/next.js/assets/56834937/0d6786bf-21ab-4a4a-9085-b701b3feb71e

### Describe the Bug

When navigate back to Home page styles for the button are lost.

### Expected Behavior

When navigate back to Home page styles for the button are not lost.

### Which browser are you using? (if relevant)

Version 114.0.5735.248 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

next start and Varcel

<sub>[NEXT-1507](https://linear.app/vercel/issue/NEXT-1507/not-found-page-component-loses-styles)</sub>

**Comment by pedroeckel** [comment]
Same problem here

**Comment by andelkocvjetkovic** [comment]
<img width="1409" alt="Screenshot 2023-07-31 at 12 04 00" src="https://github.com/vercel/next.js/assets/56834937/c758a969-d6c7-4c0e-91a9-b488ed7aba22">
I think issues is with <link />, in the not-found page next.js load styles <link /> within <body />, then in home page, <body /> content is replaced with content of home page and <link /> get deleted. 
Solution is to always load <link /> styles within <head /> element.

**Comment by andelkocvjetkovic** [comment]
bug is still present.

@huozhi would you reopen this issues ?

**Comment by ezdar2743** [comment]
@andelkocvjetkovic 
I solved this by using dynamic routing.
`app/[...not_found]/page.tsx`
Try this!😄

**Comment by huozhi** [comment]
@andelkocvjetkovic It's fixed in canary `13.4.14-canary.3`, can you verify and we should be able to close this issue. And I added some tests in #53906 to ensure it won't be regression again

**Comment by huozhi** [comment]
@andelkocvjetkovic Can you try the latest canary?

**Comment by andelkocvjetkovic** [comment]
I tried with ```13.4.14-canary.5```. The issues is still there.

**Comment by huozhi** [comment]
Gonna take a deeper look on it 👁️

**Comment by MKraust** [comment]
We have similar issue. Navigating from 404, we lose some styles (exactly 1 css chunk is missing). But for us it happens only on hard navigation to 404 then soft navigation to other pages.

`13.4.12` works fine, but newer versions are broken. I've traced this bug to `13.4.14-canary.4` (the first version with this bug).

Unfortunately, I've been trying to reproduce it in a fresh project with no success (with the same versions it bugs in our project).

**Comment by andelkocvjetkovic** [comment]
@huozhi I tried with [13.4.20-canary.2](https://www.npmjs.com/package/next/v/13.4.20-canary.2) and the issue is fixed.
https://nextjs-bug-tau.vercel.app
