### ISSUE TITLE
Docs: Add Authentication section

### ISSUE THREAD

**Issue by gmoniava** [vercel/next.js#53222]
### What is the improvement or update you wish to see?

There is docs about authentication for the pages router:
https://nextjs.org/docs/pages/building-your-application/routing/authenticating

Is it planned to write such for app router too?

### Is there any context that might help us understand?

N/a

### Does the docs page already exist? Please link to it.

N/a

<sub>[DX-1814](https://linear.app/vercel/issue/DX-1814/docs-add-authentication-section)</sub>

**Comment by balazsorban44** [comment]
Thank you, closing this issue in favor of #48988 feel free to comment there with any specific question/feedback! :pray:

**Comment by gmoniava** [comment]
@balazsorban44 That issue has narrower scope AFAIK (mine was about authentication in general), but I made that comment there too as you suggested.
