### ISSUE TITLE
Link tag loading problem

### ISSUE THREAD

**Issue by Omkar-khallar** [vercel/next.js#53244]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
I am using Nextjs for 1month but I maked a project in Nextjs in that project the Link tag is very very very slow it take upto 2 minutes to go to next page or on click back button the url changes but the page don't change I have to reload the page it is very slow to load new page iam using the latest version why is this happening is there any solution?
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

.

### To Reproduce

.

### Describe the Bug

 I am using Nextjs for 1month but I maked a project in Nextjs in that project the Link tag is very very very slow it take upto 2 minutes to go to next page or on click back button the url changes but the page don't change I have to reload the page it is very slow to load new page iam using the latest version why is this happening is there any solution? 

### Expected Behavior

.

### Which browser are you using? (if relevant)

Chrome and edge

### How are you deploying your application? (if relevant)

In development environment

**Comment by darshanjain-entrepreneur** [comment]
hey can you send your code .

**Comment by ibadsiddiqui** [comment]
I am having the same issue on my end. Can you please tell me what information I need to provide for additional context?

**Comment by Omkar-khallar** [comment]
Wait I am sending

**Comment by darshanjain-entrepreneur** [comment]
upload your code to codesandbox and share it

**Comment by Omkar-khallar** [comment]
Would I send it on your mail

**Comment by Omkar-khallar** [comment]
This project is personal I can't public that project

**Comment by timneutkens** [comment]
Please follow the issue template and provide a reproduction. Also please don't post duplicates #53242. Closing this issue as it intentionally does not provided requested information.
