### ISSUE TITLE
not-found.js always called on initial/first request

### ISSUE THREAD

**Issue by p00000001** [vercel/next.js#53252]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 11 Home
    Binaries:
      Node: 20.5.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/p00000001/next-initial-404-load-issue

### To Reproduce

Simply load the default homepage of the app and you will see a console message "not-found.js called" to show the `not-found.js` has been rendered.

### Describe the Bug

`not-found.js` represents a 404 page when the user has tried to access a resource that doesn't exist. However, Next.js is rendering this page every time a user makes their first request to the app, even if the URL is valid.

Because 404 pages often require API calls, this is creating unnecessary work and additional API calls for every user that accesses the website.

### Expected Behavior

It would seem reasonable to assume that a 404 error should be the exception, not the norm, and so `not-found.js` should only be rendered when a 404 error first occurs to avoid unnecessary extra processing and API calls.

### Which browser are you using? (if relevant)

Chrome latest

### How are you deploying your application? (if relevant)

Next Start

**Comment by cbratschi** [comment]
Confirmed, had this strange issue as well and thought something is wrong with our  middleware implementation but the issue persisted.

Seeing the middleware is invoked first, then not-found.tsx is always invoked and finally the routed page gets built.

**Comment by huozhi** [comment]
The noy found will be used as the error boundary which will be rendered as server components and serialized in RSC payload, it's expected behavior. If you want it not to be rendered as server components during RSC rendering, you can mark it as client component with `"use client"`
