### ISSUE TITLE
cookies().set() doesn't invalidate client cache

### ISSUE THREAD

**Issue by ProchaLu** [vercel/next.js#53261]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.13-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/tender-banzai-sn635z

### To Reproduce

1. Go to [CodeSandBox](https://codesandbox.io/p/sandbox/tender-banzai-sn635z)
2. Go to the `set` section
3. Enter a new session cookie value and press `Update Session`
4. Go to the home section and check if the new session cookie value is visible
5. Refresh the page
6. The session value should now display the actual value

https://github.com/vercel/next.js/assets/80746311/2a0af398-1b3a-4c7f-86ba-d53bf2f477ce

### Describe the Bug

After setting new cookies, the page doesn't invalidate client cache. As a result, the new cookie value is not immediately visible, and the old cookie value is still visible on the page. Clicking on `refresh` makes the new cookie value appear correctly. This issue seems to have surfaced after upgrading to Next.js `13.4.11-canary.1`. This behavior worked fine in Next.js `13.4.10`.

### Expected Behavior

After setting cookies, it should invalidate the client cache. The new cookie value should be immediately visible without requiring a page refresh.  

@shuding, maybe it is related to this PR? 
- https://github.com/vercel/next.js/pull/51290

<sub>[NEXT-1478](https://linear.app/vercel/issue/NEXT-1478/cookiesset-doesnt-invalidate-client-cache)</sub>

**Comment by shuding** [comment]
Need to test again when #53373 is landed.
