### ISSUE TITLE
"Error: Uncaught [TypeError: (0 , _reactdom.preload) is not a function]" when running jest

### ISSUE THREAD

**Issue by roryhen** [vercel/next.js#53272]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.4
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/lively-monad-rr5hgl

### To Reproduce

Run `npm run test` in a new terminal in the codesandbox repro provided

### Describe the Bug

In jest tests where `<Image />` from `next/image` is being used with `priority={true}` set, when I attempt to run `jest` it throws this error `Error: Uncaught [TypeError: (0 , _reactdom.preload) is not a function]`.

It seems to be introduced in next@13.4.11, when I install next@13.4.10 the error goes away. It also prints `The above error occurred in the <ImagePreload> component` in the terminal so I tracked it down to this PR (https://github.com/vercel/next.js/pull/52425) where `preload` from `react-dom` is imported and used in that component which I suspect could be part of the issue.

Not sure of how to workaround the issue, but I'm open to suggestions.

### Expected Behavior

I expect to be able to run jest tests using Image components without errors from the framework.

<sub>[NEXT-1482](https://linear.app/vercel/issue/NEXT-1482/error-uncaught-[typeerror-0-reactdompreload-is-not-a-function]-when)</sub>

**Comment by roryhen** [comment]
As a temporary workaround, I ended up adding a mock in our `jest.setup.js`:

```js
import React from 'react'

function MockImage(props) {
  return React.createElement('img', props)
}
jest.mock('next/image', () => MockImage)
```

Not perfect, but works for us for now.

**Comment by fuyu77** [comment]
```tsx
import type * as ReactDom from 'react-dom';

jest.mock('react-dom', () => ({
  ...jest.requireActual<typeof ReactDom>('react-dom'),
  preload: jest.fn(),
}));
```

It also works for us by mocking `react-dom`.

**Comment by C4rl0s** [comment]
> ```tsx
> jest.mock('react-dom', () => ({
>   ...jest.requireActual<typeof ReactDom>('react-dom'),
>   preload: jest.fn(),
> }));
> ```

This worked for me too :)

**Comment by xyzarivera** [comment]
Bumped my nextjs to 13.4.13, the error still exists. Solutions above still work also.
