### ISSUE TITLE
next > 13.4.10 too aggressive tree shaking

### ISSUE THREAD

**Issue by Torsten85** [vercel/next.js#53286]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 19.6.0
      npm: 9.4.0
      Yarn: N/A
      pnpm: 8.5.0
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

webpack optimization I guess

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Torsten85/next-13-4-10-tree-shaking-bug

### To Reproduce

run `pnpm i && pnpm test`, see the error (13.4.13-canary.5)
run `git checkout downgrade && pnpm i && pnpm test`, see no error (13.4.9)

### Describe the Bug

SWC minify removes a used chunk of code from a dependency, resulting in a production error

### Expected Behavior

the bundling process should correctly determine that the code block is referenced and in use

**Comment by icyJoseph** [comment]
This is an SWC issue. AFAIK, it has already been reported upstream to the SWC repository.

- https://github.com/vercel/next.js/issues/53096
- https://github.com/swc-project/swc/issues/7710
- https://github.com/swc-project/swc/issues/7700

**Comment by Torsten85** [comment]
Seems like it, but I get the same result with `swcMinify: false`

**Comment by icyJoseph** [comment]
Really? There was a repository on one of those issues, and it worked with minify turned off. Mmm 🤔 yours uses app router, wonder if that changes things. Could you try with pages router?

**Comment by Torsten85** [comment]
Sorry, I was wrong, `swcMinify: false` did prevent the error.

**Comment by kdy1** [comment]
This will be fixed by https://github.com/swc-project/swc/pull/7702
