### ISSUE TITLE
Next canary 13.4.13-canary.5 will crash in only Safari when server actions is enabled

### ISSUE THREAD

**Issue by tangye1234** [vercel/next.js#53281]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.10
    Relevant Packages:
      next: 13.4.13-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Server Actions / Browser Compatibility / Mac OS

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tangye1234/nextjs-bug-test

### To Reproduce

install latest 2 versions of next@canary

```
pnpm dev
```

1. In latest Safari, open localhost:3000, the error overlay will 100% come out when server actions is enabled.
2. If I disable server actions, then I long press command+R to keep refresh homepage, the console will also prints error info sometimes.

### Describe the Bug

In Safari 16.5.2

Unhandled Runtime Error
TypeError: undefined is not an object (evaluating 'originalFactory.call')

### Expected Behavior

works well in safari

### Which browser are you using? (if relevant)

Safari 16.5.2

<sub>[NEXT-1481](https://linear.app/vercel/issue/NEXT-1481/next-canary-13413-canary5-will-crash-in-only-safari-when-server)</sub>

**Comment by tangye1234** [comment]
![image](https://github.com/vercel/next.js/assets/447084/8cc92f17-56e9-43b3-bc2b-e3d670bf7a14)

**Comment by tangye1234** [comment]
Moreover, If I disable server actions, it seems OK when I refresh the homepage at a slow frequency.
But if I refresh the homepage at a very high frequency(long press command + R), the console would prints error.

![image](https://github.com/vercel/next.js/assets/447084/8fe251c0-9668-42d6-bd48-ea4f94e3c495)

**Comment by tangye1234** [comment]
Bugs will be only reproduced in Safari, chromium based browsers seems OK.

**Comment by joulev** [comment]
Same here, running Next.js v13.4.12 with Safari 17.0. It doesn't consistently appear though, I could get the error in one dev run, terminate the dev server, then immediately run the dev server again and it could work.

**Comment by shuding** [comment]
Strangely, this is very difficult to reproduce. After clearing Safari's cache I'm no longer able to see the error again...
