### ISSUE TITLE
Importing experimental_useOptimistic in a server component throws wrong error

### ISSUE THREAD

**Issue by adrianbw** [vercel/next.js#53312]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.20.1
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: 8.6.10
    Relevant Packages:
      next: 13.4.13-canary.6
      eslint-config-next: 13.4.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/adrianbw/use-optimistic-broken

### To Reproduce

Call `useOptimistic` in a server component. Get this error instead of the correct error telling you not to use it server side:
<img width="1069" alt="Screenshot 2023-07-28 at 3 23 22 PM" src="https://github.com/vercel/next.js/assets/12662580/e75d8d9f-50b4-41bb-a816-e291a8719c11">

### Describe the Bug

When you call `useOptimistic` from a server component, you get this error: 
<img width="1069" alt="Screenshot 2023-07-28 at 3 23 22 PM" src="https://github.com/vercel/next.js/assets/12662580/e75d8d9f-50b4-41bb-a816-e291a8719c11">

It should be an error telling you not to import `useOptimistic` in a server component.

### Expected Behavior

I would expect to see an error like this:
```
You're importing a component that needs experimental_useOptimistic. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials
```

**Comment by Balance8** [comment]
can confirm this happened to me as well

**Comment by adrianbw** [comment]
It shows above, but I did write a PR to fix this: https://github.com/vercel/next.js/pull/53313.
