### ISSUE TITLE
'use client' directive weird behavior when combined with material-ui and react-three-fiber

### ISSUE THREAD

**Issue by fransjesky** [vercel/next.js#53355]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.6
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/fransjesky/nextjs-bug-issue

### To Reproduce

1. Clone this repository from material-ui/examples
https://github.com/mui/material-ui/tree/master/examples/material-next-app-router-ts

or manually setup the custom design system of material-ui in the next.js version 13.4.12 created using create-next-app. (documentation on how to setup it: https://mui.com/material-ui/guides/next-js-app-router/)

2. Add the react-three-fiber dependency and create a react-three-fiber component which later will be imported to page.tsx

```ts
// components/BoxMesh.tsx
import { useRef } from 'react';
import { Box } from '@mui/material';
import { Mesh } from 'three';
import { Canvas } from '@react-three/fiber';

export default function Box() {
  const meshRef = useRef<Mesh>(null!);
  console.log(meshRef);

  return (
    <Box component='div' sx={{ width: '100%', height: '20vh' }}>
      <Canvas>
        <mesh ref={meshRef}>
          <boxGeometry />
          <meshBasicMaterial />
        </mesh>
      </Canvas>
    </Box>
  );
}```

// app/page.tsx
import * as React from 'react';
import Box from '@mui/material/Box';
import BoxMesh from '@/component/BoxMesh';

export default function HomePage() {
  return (
    <Box component='div'>
      <BoxMesh />
    </Box>
  );
}
```

### Describe the Bug

After imported the react-three-fiber component, when running the `npm run dev`, it would throw an error

> You're importing a component that needs useRef. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.
Learn more: https://nextjs.org/docs/getting-started/react-essentials

However, if i remove or disable the react-three-fiber component, the app would be working fine, that is really weird as on the page.tsx, there is a client-side component which is Box component from Material-UI.

I forgot to mention, if the 'use client' directive were put in the page.tsx, it would work as well.

If you use the repository from material-ui, look at the ThemeRegistry and EmotionCache.tsx, the 'use client' directive are being use there and the ThemeRegistry is imported to layout.tsx, which means the 'use client' is on the parent level of page.tsx, which is why the material-ui are working fine. However when using the react-three-fiber component, the app crashed as it is not using 'use client' directive. 

### Expected Behavior

When using the react-three-fiber component, it should be working as well

### Which browser are you using? (if relevant)

Chrome 113.0.5672.126

### How are you deploying your application? (if relevant)

next dev (npm run dev)

**Comment by fransjesky** [comment]
edited the code part

**Comment by NadhifRadityo** [comment]
This is correct behaviour. `"use client"` directive is file scoped (or import scoped, however you want to call it), not react children scoped. Even if the `<Box>` component from material UI is marked `"use client"`, you still need to add `"use client"` directive either in your `page.tsx` or `components/BoxMesh.tsx`.

You probably want to put the directive in the `components/BoxMesh.tsx`, so that the page doesn't need to be hydrated on the client.

**Comment by shuding** [comment]
As @NadhifRadityo said, the `"use client"` marks the **file** and its imports (and imports' imports, ...) as Client Components, not the component tree below.

Dan has a great talk on this: https://www.youtube.com/watch?v=zMf_xeGPn6s.
