### ISSUE TITLE
Redirect bugged when run in route

### ISSUE THREAD

**Issue by jnatmorris** [vercel/next.js#53351]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 20.5.0
      npm: 9.8.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.6
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/jnatmorris/routing-bug-report

### To Reproduce

1. Clone repo
2. Start the dev server
3. Try to click on the button on page1 
4. Inspect dev server logs to see route handler was fired, and js/ts of second page in server component fired.

### Describe the Bug

`redirect("/page2")` as well as `return NextResponse.redirect(new URL("/page2", request.url))` do not work in route handlers. It is stated [here](https://nextjs.org/docs/app/api-reference/functions/redirect) and [given an example here](https://nextjs.org/docs/app/building-your-application/routing/router-handlers#redirects) it should be possible, but when run the redirect does not fire.

Interestingly, while the redirect does not change the UI, it does cause the js/ts code in the server component of page2 to run (this can be seen in the console). It should also be noted that if console logging the result of the fetch to the route handler, you indeed get back a valid redirect, but no redirect occurs. 

### Expected Behavior

When redirect is called in the route handler, the UI changes to the redirected page as well as runs any server component js/ts logic. 

### Which browser are you using? (if relevant)

Tested in Chrome 108.0.5359.124 and Safari 16.5.2 (18615.2.9.11.10).

**Comment by balazsorban44** [comment]
The problem is how you are executing the redirection. The `fetch` API does not execute the redirect, but it will follow it.

The following code snippet follows the redirect:
https://github.com/jnatmorris/routing-bug-report/blob/af2ba61bb00272c20b3894d93c98ac451e4db873/src/app/page1/page.tsx#L6-L9

which you can verify by for example running `await res.text()` and looking at the result. It will be the rendered result of `page2/page.tsx`.

This is not a Next.js bug, just how `fetch` works.
