### ISSUE TITLE
Docs: fix colour in image about automatic fetch() request deduping

### ISSUE THREAD

**Issue by geryogam** [vercel/next.js#53360]
### What is the improvement or update you wish to see?

The colour in the image is incorrect (blue instead of red) for the request C in component B.

### Is there any context that might help us understand?

No.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching#automatic-fetch-request-deduping

<sub>[DX-1835](https://linear.app/vercel/issue/DX-1835/docs-fix-colour-in-image-about-automatic-fetch-request-deduping)</sub>

**Comment by balazsorban44** [comment]
Good eye, thank you! We will look into it.

**Comment by balazsorban44** [comment]
Closing this as it's fixed now. The documentation got a major upgrade in #52514, the image can be found here: https://nextjs.org/docs/app/building-your-application/caching#request-memoization
