### ISSUE TITLE
Envs that are not NEXT_PUBLIC are undefined in middleware.ts on vercel

### ISSUE THREAD

**Issue by mbret** [vercel/next.js#53382]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.2
      npm: 9.6.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.6
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

vercel

### To Reproduce

Define env without NEXT_PUBLIC, try to log it in middleware.ts

I cannot reproduce the bug locally, the env variables are correctly defined when using `npm run dev`

### Describe the Bug

Any env that is not using NEXT_PUBLIC is undefined in the middleware.

### Expected Behavior

any server env should be available in middleware since it's server code.

**Comment by balazsorban44** [comment]
I tried this, and could not reproduce. Environment variables work as expected.

Remember, you have to redeploy on Vercel if you add a new environment variable. Also, make sure they are exposed to the right environment you are deploying to.

**Comment by mbret** [comment]
It's not because it works for you that it is necessarily fixed. Not sure why you would close the issue without asking more information maybe.

Regarding the issue, we are not using vercel env variable, we are using .env.development and .env.local.

This is our file example

![image](https://github.com/vercel/next.js/assets/1911240/f7588a00-052c-4782-91be-662aac48ddaf)

Logging `process.env` in middleware.ts will output

```
{
  VERCEL_REGION: 'cdg1',
  VERCEL_ENV: 'preview',
  NX_DAEMON: 'false',
  TURBO_REMOTE_ONLY: 'true',
  TURBO_RUN_SUMMARY: 'true',
  VERCEL: '1',
  VERCEL_GIT_COMMIT_AUTHOR_LOGIN: '',
  VERCEL_GIT_COMMIT_AUTHOR_NAME: 'xxxxxx',
  VERCEL_GIT_COMMIT_MESSAGE: 'xxxxxxxx',
  VERCEL_GIT_COMMIT_REF: 'xxxx',
  VERCEL_GIT_COMMIT_SHA: 'xxxxxx',
  VERCEL_GIT_PREVIOUS_SHA: '',
  VERCEL_GIT_PROVIDER: 'gitlab',
  VERCEL_GIT_PULL_REQUEST_ID: '',
  VERCEL_GIT_REPO_ID: '',
  VERCEL_GIT_REPO_OWNER: 'xxxxxx',
  VERCEL_GIT_REPO_SLUG: 'xxxxx',
  VERCEL_URL: 'xxxxxx'
}
```

It does not contains our custom variable. Also as mentionned, any NEXT_PUBLIC_ env var in the file will be however logged in the middleware. It's actually statically replaced during the build.
