### ISSUE TITLE
Hydration error when render style element

### ISSUE THREAD

**Issue by guijiangheng** [vercel/next.js#53418]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 16.19.1
      npm: 9.6.5
      Yarn: 1.22.19
      pnpm: 7.30.0
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/guijiangheng/hydration-error

### To Reproduce

This bug can be easy reproduce, just render 

```tsx
export default function Page() {
  return (
    <div>
      <div data-test="test">test</div>
      <style>{`[data-test="test"] { background: red; }`}</style>
    </div>
  );
}

```

Then refresh page, the error will popup.

<img width="1008" alt="截屏2023-08-01 11 45 01" src="https://github.com/vercel/next.js/assets/24951305/cc8235e1-d6ab-4d0f-944f-3b709e1d511f">

<img width="1792" alt="截屏2023-08-01 11 45 32" src="https://github.com/vercel/next.js/assets/24951305/111a1fda-21d5-4caa-a3db-c3d360358288">

### Describe the Bug

Looks like not handling escape character well.

### Expected Behavior

Should not throw error, since it's a very simple and correct use case.

**Comment by icyJoseph** [comment]
Hi,

You need to do:

```tsx
/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  return (
    <div>
      <div data-test="test">test</div>
      <style
        dangerouslySetInnerHTML={{
          __html: `[data-test="test"] { background: red; }`,
        }}
      />
    </div>
  );
}

```

**Comment by guijiangheng** [comment]
Thanks, it works
