### ISSUE TITLE
Docs: Github Actions CI example does not share a build between jobs of the same workflow

### ISSUE THREAD

**Issue by tctc91** [vercel/next.js#53437]
### What is the improvement or update you wish to see?

In the Github Actions build cache example, change `.next/cache` to `.next`

Only caching the `.next/cache` folder prevents you from sharing a build between jobs in the same workflow. If you perform a `npm run build` in one job and later try to perform an `npm run start` it will present the following error:

```
Error: Could not find a production build in the '/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
```

### Is there any context that might help us understand?

In our workflow we build, unit test and lint in one job but later on run our Cypress integration tests in a separate job. For this we need to spin up the app with `npm run start`.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions

**Comment by balazsorban44** [comment]
There is no one size fits all, but to align with the other services, I think it's reasonable to keep the current documentation. However, you are free to pick your own CI environment!
