### ISSUE TITLE
Docs: correct way to use server action to update form data

### ISSUE THREAD

**Issue by pguardiario** [vercel/next.js#53435]
### What is the improvement or update you wish to see?

I'm looking for the correct way to use server actions to update form data (server component form without reloading page)
I can't find anything that looks like this in the server action documentation

### Is there any context that might help us understand?

For example:

```
async function search(data) {
    'use server'
    // ?? do something like redirect or router.push here ???
}

return <form action={search}>...
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/data-fetching/building-forms

**Comment by shuding** [comment]
The docs you're looking at is for the "pages/" directory. You need to click this switch to view docs for the App Router:

![CleanShot-2023-08-02-le4HFJK0@2x](https://github.com/vercel/next.js/assets/3676859/18e81958-a073-4c49-8c7a-3ebfbe2ed24f)

Or click here when searching the docs:

![CleanShot-2023-08-02-eSrSc3ek@2x](https://github.com/vercel/next.js/assets/3676859/e83fd07c-a38c-4f50-8821-a4dd831c38cd)

**Comment by pguardiario** [comment]
@shuding - You're right, that was the wrong link it should be:
https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions

Do I need to post the issue again or can we reopen this?
