### ISSUE TITLE
Next.js Link tag throws a client-side exception with GitHub Pages and .nojekyll.

### ISSUE THREAD

**Issue by Mona04** [vercel/next.js#53458]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.9
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: export
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Mona04/nextjs-link-bug

### To Reproduce

I built my project with the ssg option and __added .nojekyll to my repository.__
1. ```next build```
2.  manually add ```.nojekyll``` in the ```out``` directory .
3. ```gh-pages -d out -b gh-pages -t true```
 
There are dynamic route pages. 

When I click on the ```<Link>``` tag linked to a dynamic routed page, it throws an error. And it works fine without JavaScript (ctrl + click).

### Describe the Bug

When I click on the <Link> tag linked to a dynamic routed page, it throws an error. And it works fine without JavaScript (ctrl + click).

Here is the built site hosted by gh-page. [site](https://mona04.github.io/nextjs-link-bug/)

### Expected Behavior

It should route without error.

### How are you deploying your application? (if relevant)

next build and gh-pages

**Comment by balazsorban44** [comment]
Could you please add the complete source code so we can have a look? :pray:

**Comment by Mona04** [comment]
> Could you please add the complete source code so we can have a look? 🙏

I forgot to change default branch. Now you could see source code. Im sorry.

**Comment by Mona04** [comment]
It works well if I specify the file extension (/aaa/aaa => /aaa/aaa.html).
I think it is because github page doesn't check if there is a folder or a file with the same name.
