### ISSUE TITLE
ignoreDuringBuilds not being used

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vercel/next.js#53459]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 16 13:30:11 UTC 2023
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: N/A
      pnpm: 8.6.0
    Relevant packages:
      next: 13.3.2-canary.13
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/shadcn-ui/taxonomy

### To Reproduce

Just use this config

```

const config = {
  reactStrictMode: true,
  images: {
    domains: ["avatars.githubusercontent.com"],
  },
  experimental: {
    appDir: true,
    serverComponentsExternalPackages: ["@prisma/client"],
  },
  eslint: {
    // Warning: This allows production builds to successfully complete even if
    // your project has ESLint errors.
    ignoreDuringBuilds: true,
  },

}

export default config

```

and run the build command

### Describe the Bug

ignoreDuringBuilds doesn't work

### Expected Behavior

ignoreDuringBuilds should work, so I shouldn't get crappy eslint errors and block the build. I don't care about them, js is bad anyway :)

Thanks a lot

Cheers,

Fra

**Comment by balazsorban44** [comment]
This option should work as intended. Keep in mind that by default only the following directories will be handled:

https://github.com/vercel/next.js/blob/12e77cae30f61bd94182931b836ec46a1d79a888/packages/next/src/lib/constants.ts#L60-L61

You can add your own `dirs` option to override the defaults.

In any case, if you are seeing ESLint errors with the linked project's ESLint configuration, you might want to take it up as an issue there instead first.

If you are still having trouble, please open a new issue with your own minimal reproduction, thanks! :pray:

**Comment by FrancescoSaverioZuppichini** [comment]
> This option should work as intended. Keep in mind that by default only the following directories will be handled:
> 
> https://github.com/vercel/next.js/blob/12e77cae30f61bd94182931b836ec46a1d79a888/packages/next/src/lib/constants.ts#L60-L61
> 
> You can add your own `dirs` option to override the defaults.
> 
> In any case, if you are seeing ESLint errors with the linked project's ESLint configuration, you might want to take it up as an issue there instead first.
> 
> If you are still having trouble, please open a new issue with your own minimal reproduction, thanks! 🙏

I agree but I am using Prisma and the types there are so crazy and poorly managed that it is like impossible to get them right and I am wasting time fighting typescript and prisma auto generated types when everything is actually fine so I was looking for a way to disable the eslint errors, at least for now - thanks a lot, will try and report back 🤗

**Comment by isaacdarcilla** [comment]
Same issue
