### ISSUE TITLE
Docs: Multiple Sitemaps

### ISSUE THREAD

**Issue by TonsiTT** [vercel/next.js#53480]
### What is the improvement or update you wish to see?

As far as I can see,  in PR #48867, the ability to add multiple sitemaps was added. I would like to see an example in the docs of generating more than 1 sitemap.

### Is there any context that might help us understand?

.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

<sub>[DX-1843](https://linear.app/vercel/issue/DX-1843/docs-multiple-sitemaps)</sub>

**Comment by lukedanielson** [comment]
I've tried the test file [sitemap.ts](https://github.com/vercel/next.js/blob/v13.4.13/test/e2e/app-dir/metadata-dynamic-routes/app/gsp/sitemap.ts) from `v13.4.13` in various locations: 

- ./src/app/sitemap.ts
- ./src/app/sitemap/[id]/1.ts
- ./src/app/sitemap.xml/[id]/1.ts

I receive a `404 Not Found` with just the text "Not Found" when the file is located at `./src/app/sitemap.ts` and visiting `http://localhost:3000/sitemap.xml`. The sitemap content from the `sitemap()` export returns successfully if I remove the `generateSitemaps()` export from the file.

When using the latter two paths above (`./src/app/sitemap/[id]/1.ts` and `./src/app/sitemap.xml/[id]/1.ts`) it returns the `/[...not_found]/page`.

Any ideas on how to implement multiple sitemaps correctly without documentation yet?

[sitemap.ts](https://github.com/vercel/next.js/blob/v13.4.13/test/e2e/app-dir/metadata-dynamic-routes/app/gsp/sitemap.ts) file for reference:
```ts
import { MetadataRoute } from 'next'

export async function generateSitemaps() {
  return [{ id: 0 }, { id: 1 }, { id: 2 }, { id: 3 }]
}

export default function sitemap({ id }): MetadataRoute.Sitemap {
  return [
    {
      url: `https://example.com/dynamic/${id}`,
      lastModified: '2021-01-01',
    },
    {
      url: `https://example.com/dynamic/${id}/about`,
      lastModified: '2021-01-01',
    },
  ]
}
```

**Comment by SivaGanesh56** [comment]
any updates on this ?

**Comment by denny999222** [comment]
> > I've tried the test file [sitemap.ts](https://github.com/vercel/next.js/blob/v13.4.13/test/e2e/app-dir/metadata-dynamic-routes/app/gsp/sitemap.ts) from `v13.4.13` in various locations:
> > ```
> > * ./src/app/sitemap.ts
> > 
> > * ./src/app/sitemap/[id]/1.ts
> > 
> > * ./src/app/sitemap.xml/[id]/1.ts
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I receive a `404 Not Found` with just the text "Not Found" when the file is located at `./src/app/sitemap.ts` and visiting `http://localhost:3000/sitemap.xml`. The sitemap content from the `sitemap()` export returns successfully if I remove the `generateSitemaps()` export from the file.
> > When using the latter two paths above (`./src/app/sitemap/[id]/1.ts` and `./src/app/sitemap.xml/[id]/1.ts`) it returns the `/[...not_found]/page`.
> > Any ideas on how to implement multiple sitemaps correctly without documentation yet?
> > [sitemap.ts](https://github.com/vercel/next.js/blob/v13.4.13/test/e2e/app-dir/metadata-dynamic-routes/app/gsp/sitemap.ts) file for reference:
> > ```ts
> > import { MetadataRoute } from 'next'
> > 
> > export async function generateSitemaps() {
> >   return [{ id: 0 }, { id: 1 }, { id: 2 }, { id: 3 }]
> > }
> > 
> > export default function sitemap({ id }): MetadataRoute.Sitemap {
> >   return [
> >     {
> >       url: `https://example.com/dynamic/${id}`,
> >       lastModified: '2021-01-01',
> >     },
> >     {
> >       url: `https://example.com/dynamic/${id}/about`,
> >       lastModified: '2021-01-01',
> >     },
> >   ]
> > }
> > ```
> 
> I was also facing the same issue, and so, in my case, I just created an API Route/Route Handler for my other sitemap.
> 
> * ./src/app/sitemap-es.xml/route.js (sitemap-es.xml is a folder. Can be whatever you want to name the sitemap route)
> 
> Inside the route, I made it as such:
> 
> ```
> export async function GET() {
>   let sitemapXml = `
>     <?xml version="1.0" encoding="UTF-8"?>
>     <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
>     <url>
>         <loc>https://www.acme.com</loc>
>         <lastmod>2021-01-01</lastmod>
>     </url>
>     <url>
>         <loc>https://www.acme.com/about</loc>
>         <lastmod>2021-01-01</lastmod>
>     </url>
>     </urlset>
>     `
> 
>   return new Response(sitemapXml, {
>     headers: {
>       "content-type": "application/xml;charset=UTF-8",
>     },
>   })
> }
> ```

Sort of stuck on the same issue, can you elaborate on what your sitemap.ts file looks like? And your file structure where your xml routes are?

**Comment by lukedanielson** [comment]
@denny999222 Sure thing, here is my `./src/app/sitemap.xml/route.ts` file:

```ts
import config from "@/lib/config";
import { xmlUrl } from "@/lib/types/Xml";
import getXmlUrlSet from "@/lib/utils/getXmlUrlSet";

export async function GET() {
  const sitemaps: xmlUrl[] = [
    { url: "/sitemaps/latest" },
    { url: "/sitemaps/categories" },
    { url: "/sitemaps/all/1" },
    { url: "/sitemaps/all/2" },
    { url: "/sitemaps/all/3" },
    { url: "/sitemaps/all/4" },
  ];

  const postUrls: xmlUrl[] = sitemaps.map((cat: { url: string }) => ({
    url: `${config.local.baseUrl}${cat.url}`,
    lastModified: new Date(post.date).toISOString(),
  }));

  const xmlStr = `<?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      ${postUrls
        .map((postUrl: xmlUrl) => `<sitemap><loc>${postUrl.url}</loc></sitemap>`)
        .join("")}
    </urlset>`;

  return new Response(xmlStr, {
    headers: {
      "content-type": "application/xml;charset=UTF-8",
    },
  });
}
```

Is this helpful, or do you need to see the other sitemaps referenced in this file?

**Comment by SivaGanesh56** [comment]
we need generate sitemaps for our SSG site. there will be no standalone server in my case

**Comment by denny999222** [comment]
Appreciate the super quick response, examples of the other sitemaps would be super helpful Luke. Thanks!

**Comment by lukedanielson** [comment]
@denny999222 No problem. Here is a few of them to help get the idea:

`./src/app/sitemaps/categories/route.ts`:
```ts
import config from "@/lib/config";
import { xmlUrl } from "@/lib/types/Xml";
import getXmlUrlSet from "@/lib/utils/getXmlUrlSet";

export async function GET() {
  const categories = [
    { url: "/category/your-life" },
    { url: "/category/entertainment" },
    { url: "/category/style" },
  ];

  const postUrls: xmlUrl[] = categories.map((cat: { url: string }) => ({
    url: `${config.local.baseUrl}${cat.url}`,
    lastModified: new Date(post.date).toISOString(),
  }));

  const xmlStr = getXmlUrlSet(postUrls);

  return new Response(xmlStr, {
    headers: {
      "content-type": "application/xml;charset=UTF-8",
    },
  });
}
```

`/src/app/sitemaps/all/[page]/route.ts`:
```ts
import config from "@/lib/config";
import { TArticleArchive } from "@/lib/types/Article";
import { xmlUrl } from "@/lib/types/Xml";
import fetchJson from "@/lib/utils/fetchJson";
import getXmlUrlSet from "@/lib/utils/getXmlUrlSet";

type PropsContext = {
  params: { page?: number | undefined };
};

export async function GET(
  request: Request,
  context: { params: PropsContext["params"] }
) {
  const page = context?.params?.page; // '1'
  const url = `${config.wpApi.baseUrl}/sh-api/sitemap/${page}`;
  const fetchTag = `sitemap-all--${page}`;
  const fetchCfg = { next: { revalidate: 1800, tags: [fetchTag] } };
  const posts = await fetchJson(url, fetchCfg);

  const postUrls: xmlUrl[] =
    posts &&
    posts.map((post: TArticleArchive) => {
      let dateParts = post.date.split(" ");
      let date = dateParts[0] + "T" + dateParts[1] + ".000Z";
      return {
        url: `${config.local.baseUrl}/read/${post.slug}`,
        lastModified: new Date(date).toISOString(),
      };
    });

  const xmlStr = getXmlUrlSet(postUrls);

  return new Response(xmlStr, {
    headers: {
      "content-type": "application/xml;charset=UTF-8",
    },
  });
}
```

`./src/lib/utils/getXmlUrlSet.ts`:
```ts
import { xmlUrl } from "../types/Xml";
import getXmlUrlsStr from "./getXmlUrlsStr";

export default function getXmlUrlSet(postUrls: xmlUrl[] | undefined): string {
  if (!postUrls || ![postUrls.length]) {
    return "";
  }

  const postUrlsXmlStr = postUrls
    .map(
      (postUrl: xmlUrl) =>
        `<url><loc>${postUrl.url}</loc>` +
        (postUrl.lastModified ? `<lastmod>${postUrl.lastModified}</lastmod>` : ``) +
        `</url>`
    )
    .join("");

  return `<?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      ${postUrlsXmlStr}
    </urlset>`;
}
```

**Comment by denny999222** [comment]
Incredibly helpful answer, thanks a lot Luke! Best answer I've found thus far on this issue

**Comment by sagarchoudhary96** [comment]
@huozhi can you help here with an example for how this #48867 functionality can be used ?

**Comment by delbaoliveira** [comment]
Hello, we've documented `generate sitemaps` and included an example of using it for sitemap splitting. 

Hope it's helpful! Closing this issue, but feel free to leave any further feedback on the PR. 🙏🏼 

https://github.com/vercel/next.js/pull/59626

**Comment by sagarchoudhary96** [comment]
Thanks @delbaoliveira 🙌
