### ISSUE TITLE
Docs: [BUG] Table component overflows on mobile

### ISSUE THREAD

**Issue by alvarlagerlof** [vercel/next.js#53488]
### What is the improvement or update you wish to see?

The table component used in [the new caching page](https://nextjs.org/docs/app/building-your-application/caching) (for example) is too wide on mobile, causing the whole page to overflow. I suggest that an `overflow-x` should be added to added to it. so that it can scroll horizontally independently.

<img width="320" alt="image" src="https://github.com/vercel/next.js/assets/14835120/81cd1d04-c06f-495d-8bcf-e30bf61fedf4">

### Is there any context that might help us understand?

n/a

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/caching

<sub>[DX-1844](https://linear.app/vercel/issue/DX-1844/docs-[bug]-table-component-overflows-on-mobile)</sub>

**Comment by alvarlagerlof** [comment]
cc @delbaoliveira Probably an easy fix. I was looking to make a PR but it looks like the code is not published.

**Comment by darshanjain-entrepreneur** [comment]
Yes the code is not publically available.

**Comment by balazsorban44** [comment]
This is tracked now, we will provide a fix soon. Indeed, the source code for this is not currently public, but thanks for the heads up!

_(Note @alvarlagerlof, usually there is no need to directly mention maintainers, as it can create noise for them. Thanks for understanding! :pray:)_

**Comment by leerob** [comment]
Just pushed a fix, thank you.
