### ISSUE TITLE
Google fonts are outdated

### ISSUE THREAD

**Issue by charleywolf** [vercel/next.js#53506]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (next/font)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/charleywolf/nextjs-issue-reproduction

### To Reproduce

To reproduce, you can import the font `DM_Sans` and try to set it up without specifying the weight. 
Your linter will say it is a required field yet it should not be. You should be allowed not to set up the weight because it is a variable font.

Attempt this code:
`const dmSans = DM_Sans({ subsets: ['latin']});`

### Describe the Bug

The font data in `next/font/google` is outdated. Some fonts, including `DM_Sans` aren't correct anymore because the fonts file in `next/font/google` hasn't been updated in 2 months.

### Expected Behavior

I expected to be able to do `const dmSans = DM_Sans({ subsets: ['latin']});` to setup my font, but that threw an error.

**Comment by vinaykulk621** [comment]
The Error says that you need to specify the subset.
you have to add subsets which can take either `latin` or `latin-ext` as value

![image](https://github.com/vercel/next.js/assets/94120295/88b8f51f-b3b5-467a-af96-651ae5210bdc)


</br>


`layout.tsx`
```tsx
const dmSans = DM_Sans({ subsets: ['latin'], weight: ['400', '500', '700'] });
```

**Comment by charleywolf** [comment]
Sorry about that, but the main issue still persists: DM Sans is a variable font but it makes you specify the weight because the google fonts are outdated.
