### ISSUE TITLE
globals.css should be loaded before any script with a <Head> tag in a component

### ISSUE THREAD

**Issue by chriship** [vercel/next.js#53515]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

My project is using Tailwind which is imported into `_app.js` (`import '@/styles/globals.css'`). I have other components which override some of the styles set in `globals.css` using the `<Head>` component however, it seems that `globals.css` is injected into the markup after the component styles.

Note this is similar to issue #3575 but not the same because the components are rendering the contents of their `<Head>` components in the correct order, it's just `globals.css` is rendered last but I believe it should be first?

A basic example is as follows:

styles/globals.css:
```
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  background-color: green;
}
```

_app.js:
```
import Head from 'next/head'

function TestComponent({ }) {
  return (
      <>
          <Head>
              <style>{`
                  body {
                      background-color: blue;
                  }
              `}</style>
          </Head>
          <div></div>
      </>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <style>{`
          body {
            background-color: red;
          }
        `}</style>
      </Head>
      <div>
        <TestComponent />
        <div>I would expect 'TestComponent' to override the background color but the one from globals.css is prioritized but it rendering green from globals.css</div>
      </div>
    </>
  )
}
```

### Link to the code that reproduces this issue or a replay of the bug

https://gist.github.com/chriship/d564edffd73d4b091ed8a59beff923d0

### To Reproduce

1. Create a new project with TailwindCSS. 
2. Add a background color style within `globals.css`. 
3. Within a page add a `<Head>` tag and add some styles to override the background color.
4. The background color set within `globals.css` will take priority.

### Describe the Bug

The style tag from imports defined within _app.js are rendered in the markup after style tags from <Head> components defined elsewhere. 

### Expected Behavior

I believe the style tag from imports defined within _app.js should be rendered in the markup before any style tags from <Head> components defined elsewhere.

**Comment by igordanchenko** [comment]
You should remove `<Head>` component and use `<style jsx global>` instead. That should resolve your issue.

```jsx
<style jsx global>{`
    body {
        background-color: blue;
    }
`}</style>
```

See for reference - https://nextjs.org/docs/pages/building-your-application/styling/css-in-js

**Comment by chriship** [comment]
> You should remove `<Head>` component and use `<style jsx global>` instead. That should resolve your issue.
> 
> ```js
> <style jsx global>{`
>     body {
>         background-color: blue;
>     }
> `}</style>
> ```
> 
> See for reference - https://nextjs.org/docs/pages/building-your-application/styling/css-in-js

Yeah thanks, this does work for me. Will close this one.
