### ISSUE TITLE
Unable to run the application due to .next folder permissions

### ISSUE THREAD

**Issue by HristovCodes** [vercel/next.js#53516]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Debian 4.19.269-1 (2022-12-20)
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.6.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Operating System (Windows, MacOS, Linux)

### Link to the code that reproduces this issue or a replay of the bug

none

### To Reproduce

Run `npm run dev` as one user. Log out and log in as another user on the machine and run `npm run dev` again. The project won't build and you will get a permission error on the **.next** folder. 

### Describe the Bug

I described it as best as I can in the "To Reproduce" section. The problem can easily be solved by recursively changing the permissions of the .next folder and running `npm run dev` again, but then after running the command the problem arises again for the other users on the server, because after running the `npm run dev` command the permission of all the files in .next folder change to be owned of the user running the command.

I was able to fix the problem by changing the dev script to `"dev": "sudo chown -R :smbshare .next/ && sudo chmod -R g+rwx .next/ && next dev",`, but the problem is this feels like a cheap fix, like fixing a broken window with duct tape.

### Expected Behavior

To be able to build the project as any user on the server that has access to the project directory.

**Comment by HristovCodes** [comment]
Forgot to mention that using `sudo npm run dev` also doesn't fix the problem but just throws an error `syntaxerror unexpected token ' =??'`

**Comment by balazsorban44** [comment]
> syntaxerror unexpected token ' =??'

This means you are on an older Node.js version than what is expected. Make sure you are on at least 16.8: https://github.com/vercel/next.js/blob/0ecde6bd32dac474ec5342fc9e70c54363636717/packages/next/package.json#L315

> because after running the npm run dev command the permission of all the files in .next folder change to be owned of the user running the command.

The dev server is meant for a single developer working on it, so I feel like this is expected. Your solution seems correct for your use case.

**Comment by HristovCodes** [comment]
Node js is update to the latest version for everyone. The rest makes sense, thanks for clarifying that this is how it should be.
