### ISSUE TITLE
`next/image` with `priority` in App Router causes double fetch on mobile

### ISSUE THREAD

**Issue by gauravsaini964** [vercel/next.js#53574]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: 8.6.0
    Relevant Packages:
      next: 13.4.13-canary.14
      eslint-config-next: 13.4.11
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

Link to the code that reproduces this issue or a replay of the bug
https://github.com/gauravsaini964/image-preload-next13

### To Reproduce

- Build the repo.
- Navigate to index page (which is using app-dir) and inspect network tab.
- Preload image is loaded twice of different resolution.
- Navigate to /page-dir (which is using page dir).
- Correct image is preloaded only once.

Generated preload tag
```html
<link rel="preload" as="image" fetchpriority="high" imagesrcset="https://staging.nathabit.in/_nat/images/face_malai_mobile_4c3ebeef79.jpg?format=auto&amp;width=640&amp;quality=75 640w, https://staging.nathabit.in/_nat/images/face_malai_mobile_4c3ebeef79.jpg?format=auto&amp;width=750&amp;quality=75 750w, https://staging.nathabit.in/_nat/images/face_malai_mobile_4c3ebeef79.jpg?format=auto&amp;width=828&amp;quality=75 828w, https://staging.nathabit.in/_nat/images/face_malai_mobile_4c3ebeef79.jpg?format=auto&amp;width=1080&amp;quality=75 1080w, https://staging.nathabit.in/_nat/images/face_malai_mobile_4c3ebeef79.jpg?format=auto&amp;width=1200&amp;quality=75 1200w, https://staging.nathabit.in/_nat/images/face_malai_mobile_4c3ebeef79.jpg?format=auto&amp;width=1920&amp;quality=75 1920w, https://staging.nathabit.in/_nat/images/face_malai_mobile_4c3ebeef79.jpg?format=auto&amp;width=2048&amp;quality=75 2048w, https://staging.nathabit.in/_nat/images/face_malai_mobile_4c3ebeef79.jpg?format=auto&amp;width=3840&amp;quality=75 3840w" imagesizes="80vw">
``` 

<img width="1680" alt="Screenshot 2023-08-04 at 5 11 20 PM" src="https://github.com/vercel/next.js/assets/16620277/3364a6ae-ecb6-4dc4-b475-a93555870755">
<img width="1680" alt="Screenshot 2023-08-04 at 5 11 43 PM" src="https://github.com/vercel/next.js/assets/16620277/01836c2d-1062-49f3-89dc-08ba84a52b79">
<img width="1322" alt="Screenshot 2023-08-04 at 5 10 45 PM" src="https://github.com/vercel/next.js/assets/16620277/f39b8a39-4d1c-4615-a980-41e174cd5689">

### Describe the Bug

I have 10 banners on a page. 

Only 1st banner is LCP image hence I set priority=true on that banner.
Preload tag is generated and image is fetched of ~600-800px width which is correct size. But the image is fetched again of higher resolution immediately and this higher resolution image is rendered. Effectively negating the presence of preload tag.

This only happens in first banner.

On the remaining 9 banners, priority=false,  lower and correct resolution image is used. Resolution is equal to the one fetched in preload tag.

### Expected Behavior

Only one LCP image should be fetched and rendered.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1497](https://linear.app/vercel/issue/NEXT-1497/nextimages-when-using-priority=true-fetching-same-images-twice-of-two)</sub>

**Comment by gauravsaini964** [comment]
I think I have found the issue.
```html
    <meta name="viewport" content="width=device-width, initial-scale=1" />
```

This should be top statement (atleast before image preload) to report correct device width. Source [https://stackoverflow.com/questions/51290584/responsive-img-gets-wrong-images-from-srcset](url)

> A couple potential gotchas to double check. Make sure you have <meta name="viewport" content="width=device-width"> in the head so the devices you test on are forced to adopt their real width when loading the page.

I can confirm, if I manually move this tag to top of the html, only the correct image loads :)

You can see this behaviour working correctly in page directory. Added steps to reproduce now.

**Comment by gauravsaini964** [comment]
@styfle Please check this. Thank you

**Comment by styfle** [comment]
@gauravsaini964 I am not able to reproduce locally with `next dev`, or `next build && next start` or with `vc deploy`.

### Local
<img width="922" alt="image" src="https://github.com/vercel/next.js/assets/229881/a92b91d2-25b1-4dae-b026-b8e2fa2c09b1">

### Deployment
<img width="995" alt="image" src="https://github.com/vercel/next.js/assets/229881/188ca885-44b6-48b5-bb53-97a0e4630650">

**Comment by styfle** [comment]
I see now - I can reproduce when emulating mobile.

This looks like a bug with `ReactDOM.preload()` so I'll create an upstream issue, thanks!
