### ISSUE TITLE
Environment variable behavior changed on 13.4.13-canary

### ISSUE THREAD

**Issue by asmockler** [vercel/next.js#53579]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.14
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: standalone
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/asmockler/next-bug-runtime-env-vars

### To Reproduce

Create a standalone app and try to access an environment variable set not-at-build-time.

`console.log(process.env.TEST)` will evaluate to `undefined` for both of the following commands:

```
node .next/standalone/server.js
TEST=present node .next/standalone/server.js
```

I would expect the first to be `undefined` and the second to be `present`

### Describe the Bug

Environment variables are not accessible when set after build-time.

### Expected Behavior

Environment variables should be accessible and able to be overridden at runtime.

### Which browser are you using? (if relevant)

Server-side

### How are you deploying your application? (if relevant)

Standalone w/ Docker on Google Cloud Run

**Comment by joacub** [comment]
Yes i also reported that in another issue

**Comment by markspolakovs** [comment]
Bisected the regression to 1398de9977b89c9c4717d26e213b52bc63ccbe7e (cc @timneutkens @ijjk) - to verify, clone https://github.com/markspolakovs/nextjs-53579-repro, edit `test.sh` to set the path to your local Next.js build, then run `./test.sh`.

**Comment by balazsorban44** [comment]
Thanks for reporting! I'll close this in favor of #53367, you can subscribe to that issue for updates! @markspolakovs thanks for tracking this down! :pray:
