### ISSUE TITLE
data fetching in server components

### ISSUE THREAD

**Issue by Nicki-Di** [vercel/next.js#53627]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.0.0: Tue Jul 18 20:35:35 PDT 2023; root:xnu-10002.0.199.505.1~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.0.0
      npm: 9.7.2
      Yarn: 1.22.19
      pnpm: 7.18.2
    Relevant Packages:
      next: 13.4.13-canary.16
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Data fetching (gS(S)P, getInitialProps), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Nicki-Di/test-ssr

### To Reproduce

1. Open the homepage on http://localhost:3000/
2. Click on "Click Me" button. This will take you to the page that dies the data fetchings
3. You see the date? Good, Now hit the "return" button and get back to homepage
4. If you again click the "Click Me" button, you won't see any new request being made. Thus, if you change the data on the Node.js server on 5004 port, it won't be fetched. The only way to get the fresh data is by NOT using Link component and doing the navigation with a simple anchor (<a></a>) tag.
5. To test this properly, you may need a mock Node.js backend, here is the code for it:
```js 
import express from "express"
import cors from "cors"
const app = express()
app.use(cors())

const port = 5004

app.get('/data', (req, res) => {
  const data = [{
    name: "nick",
    score: 17
  }]
  res.json(data)
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

### Describe the Bug

When I do data fetching on server component with async await, and navigate between different pages of my application with Link component, for the second time, this data fetch function doesn't get called and the data is not fresh. I've done all cache disabling, etc.

### Expected Behavior

Just like the Next.js 12, when we had getServerSideProps, any time we'd visit a page with this function, this function would get called and the data on page would be fresh.
Now, the only way to get fresh data is hard reload on browser or by not using Link component.

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Local, but tested on Vercel and got the same result.

**Comment by balazsorban44** [comment]
Hi, this is because client-side navigations are cached for 30 seconds, see: https://nextjs.org/docs/app/building-your-application/caching#duration-3

**Comment by Nicki-Di** [comment]
Is there any universal setting to turn it off in all routes? I've already tried ```export const dynamic = 'force-dynamic'``` and ```revalidate = 0``` .They didn't work.
