### ISSUE TITLE
[Turbo Flag] Can't use webpack loaders on layout files

### ISSUE THREAD

**Issue by willwill96** [vercel/next.js#53621]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.16
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Turbopack (--turbo)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/willwill96/next-turbo-webpack-loader-repro

### To Reproduce

Run `npm run dev -- --turbo` 

You will see the following error:
![image](https://github.com/vercel/next.js/assets/10997562/17f7fa42-7038-4201-bd88-e59759d4afaa)

If you update the `turbo.rules` glob to `page.tsx`, it parses the file fine (and still has the added import). It also seems to work fine if I target the `layout.tsx` file without using turbopack (see the webpack config)

### Describe the Bug

It seems like there is some special behavior for the layout file specifically, that is causing parsing errors when combined with webpack. 

I wrote a webpack loader that was solely an identity function (does not modify any code) to verify this was not an issue with the specific loader (`imports-loader`) I'm using and had the same behavior. The webpack loader I was using is below:
```
module.exports = function identityLoader (code) {
    return code
}
```

### Expected Behavior

I can use webpack loaders for any file in nextjs in conjunction with the `--turbo` flag.

### Which browser are you using? (if relevant)

Not relevant, but latest Chrome

### How are you deploying your application? (if relevant)

next dev/start

<sub>[WEB-1348](https://linear.app/vercel/issue/WEB-1348/[turbo-flag]-cant-use-webpack-loaders-on-layout-files)</sub>

**Comment by padmaia** [comment]
@willwill96 I'm not seeing this issue with v13.5.1, can you confirm?

**Comment by ForsakenHarmony** [comment]
You can add `as: '*.tsx'` to tell turbopack it's still a typescript file after it has been processed with the loader:

```js
turbo: {
    rules: {
        'layout.tsx': {
            loaders: [{
                loader: 'imports-loader',
                options: {
                    imports:  ....
                }
            }],
            as: "*.tsx"
        }
    }
}
```

We need to add that to our docs.
