### ISSUE TITLE
use client: ReferenceError: EventSource is not defined 

### ISSUE THREAD

**Issue by nukisman** [vercel/next.js#53629]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
On my local machine:

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 9.2.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.16
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A



On sandbox:

    Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13-canary.16
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/strange-jepsen-jjgctx

### To Reproduce

Just make empty client component with `use client` and `new EventSource(url)`

### Describe the Bug

Despite the `use client` in `Stream.tsx` it prints error in server console for `new EventSource(...)` on every new page load.

PS: SSE streaming via `EventSource` actually works and shown in UI on my local machine (with additional code).

```
- error components/Stream.tsx (5:12) @ eval
- error ReferenceError: EventSource is not defined
    at eval (./components/Stream.tsx:8:13)
    at (ssr)/./components/Stream.tsx (/workspace/.next/server/app/page.js:304:1)
    at __webpack_require__ (/workspace/.next/server/webpack-runtime.js:33:42)
  3 | import { useEffect, useMemo, useState } from 'react';
  4 | 
> 5 | const sse = new EventSource('/api/stream');
    |            ^
  6 | 
  7 | export const Stream = () => {
  8 |   return (
```

### Expected Behavior

No error printed when apply directory `use client` and use browser only API (like `EventSource`)

### Which browser are you using? (if relevant)

Chrome 115.0.5790.114 (x86_64)

### How are you deploying your application? (if relevant)

npm run dev

**Comment by balazsorban44** [comment]
Node.js does not have `EventSource` defined yet. Remember, `"use client"` does not mean that something is only running in the browser. Next.js will have a sevrer-side prepass to generate a static version of the page. To safely access browser-only APIs, check out: https://nextjs.org/docs/app/building-your-application/deploying/static-exports#browser-apis
