### ISSUE TITLE
Can't install latest canary release v13.4.13-canary.16

### ISSUE THREAD

**Issue by jcohenho** [vercel/next.js#53636]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.18
      pnpm: 8.5.1
    Relevant Packages:
      next: 13.4.13-canary.15
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/compare/v13.4.13-canary.15...v13.4.13-canary.16#diff-a0fdacd2ade87c5238dde44378f574f7e123e669acdf8b740878b14b33b20275R19

### To Reproduce

run `npm install next@canary` 
or 
`yarn add next@canary` 

### Describe the Bug

When trying to run `yarn add next@canary`, I get the following error: 

`error Package "client-only-vendored" refers to a non-existing file '"/Users/me/projects/my_projects/vendored/node_modules/client-only-vendored"'.` 

I can install `v13.4.13-canary.15` perfectly fine, it looks like some new directories were added in this latest release. 

### Expected Behavior

I should be able to install the latest version of Next canary.

**Comment by balazsorban44** [comment]
Hi, this was reverted in #53640 so you should be able to upgrade.
