### ISSUE TITLE
"use" hook in client component not work 

### ISSUE THREAD

**Issue by zy0228** [vercel/next.js#53660]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: N/A
      pnpm: 7.12.0
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

"use" hook in client component not work 

### app/layout.tsx
```
// Nav client component
// Slide client component

export default function Home({ params }: { params: Props }) {
  const lang = use(import(`./lang/${params.lang}.json`))

  return (
    <section className="w-full relative">
      <Nav />
      <Slide />
    </section>
  )
}
```
### Nav component
```
'use client'

export default function Nav() {
 useEffect(() => {
   console.log(window)
 }, [])
  return <h1>nav</h1>
}
```

### Slide component (will throw error
```
'use client'

export default function Slide() {
   const { imgList } = use(import('./xxxx.json'))
 
  // above line code will throw error , but when I remove brother component Nav will work 
  // Throw Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server. 

  return <>{imgList.map(url => (<img  src={url}/>)}<>

}
```

### Describe the Bug

Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.

### Expected Behavior

when i use 'use(import('xxx'))' in client component, can work

**Comment by balazsorban44** [comment]
Hi, as the error message says, this is currently expected as the feature is not supported yet.

**Comment by zy0228** [comment]
> Hi, as the error message says, this is currently expected as the feature is not supported yet.

but, if I remove Nav Component from app/layout.tsx, it's will work

**Comment by lshearer** [comment]
I also encountered this. The error says `async/await is not yet supported in Client Components, only Server Components`. But we're not trying to use `async/await` in a Client Component, we're just trying to use the `use` hook. It's my understanding that the whole purpose of the `use` hook is for in components that _don't_ support async/await, i.e., Client Components. 

The [Next.js docs](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-client) even mention the `use` hook as an API for Client Components. I realize that it also says

> Wrapping fetch in use is currently not recommended in Client Components and may trigger multiple re-renders

though I've interpreted that as "you can use it in Client Components, but it may trigger multiple re-renders" or maybe also "you shouldn't directly wrap `fetch` in `use` and should first wrap `fetch` with `cache` or something similar". Not "you can't use the `use` hook in Client Components yet".

So it feels like something isn't clear in the docs or there is a Next.js or React bug. But given that @zy0228 said it works when a sibling component is removed, it feels like there's at least something wrong with how Next.js is handling it.

**Comment by zy0228** [comment]
Yeah, I'm pretty sure it's a bug. Strangely, if I make`Nav Component` to `SFC` ,  it's will work!
