### ISSUE TITLE
Navigating back from 404 page renders 404, not expected page

### ISSUE THREAD

**Issue by CarlosBalladares** [vercel/next.js#53689]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.0
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/CarlosBalladares/next-404-back-button

### To Reproduce

1. clone
2. install dependencies with yarn
3. run yarn dev
4. go to root page `/` observe the contents
5. click the link
6. go back
7. 404 remains on the screen, but the root page `/` contents should show

### Describe the Bug

Whenever navigating back from a 404 page the previous page doesn't show and the 404 page remains visible.

### Expected Behavior

after going back from the 404 page the current page contents should be visible.

### Which browser are you using? (if relevant)

Microsoft Edge Version 115.0.1901.188 (Official build) (64-bit)

### How are you deploying your application? (if relevant)

next start

**Comment by CarlosBalladares** [comment]
https://github.com/vercel/next.js/assets/14811752/a002b049-674e-494e-8c1a-6168cb160b92

video of repro

**Comment by CarlosBalladares** [comment]
a  workaround is to use `a` an regular anchor tag instead of `Link` from `next/link`.

**Comment by CarlosBalladares** [comment]
it also works as expected when you disable javascript

**Comment by huozhi** [comment]
Thanks for reporting, will close this as duplicated of #52264 and track the issue there
