### ISSUE TITLE
`not-found.tsx` not using `layout.tsx` in "Route Groups"

### ISSUE THREAD

**Issue by Yovach** [vercel/next.js#53694]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Tue Jul 18 21:28:32 UTC 2023
Binaries:
  Node: 20.4.0
  npm: 9.7.2
  Yarn: 1.22.19
  pnpm: 8.6.11
Relevant Packages:
  next: 13.4.14-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Yovach/nextjs-no-layout-on-not-found

### To Reproduce

1 - Clone
2 - npm install
3 - npm run dev
4 - Go to [http://localhost:3000/blog](http://localhost:3000/blog)

### Describe the Bug

The `./src/app/(public)/not-found.tsx` isn't using the [Root Layout](https://nextjs.org/docs/app/building-your-application/routing/route-groups#creating-multiple-root-layouts) of `(public)` folder.

```
app
  (admin)
    - layout.tsx
    - page.tsx
  (public)
    /blog
      - page.tsx
    - layout.tsx
    - not-found.tsx
    - page.tsx
```

### Expected Behavior

The `./src/app/(public)/not-found.tsx` file should use the [Root Layout](https://nextjs.org/docs/app/building-your-application/routing/route-groups#creating-multiple-root-layouts) of `(public)` folder, as it's in the same route group and should consider `./src/app/(public)` to be the root of its tree.

So when we visit [http://localhost:3000/blog](http://localhost:3000/blog), we should get "Welcome to public page !" followed by "Not found!"

It was working on [v13.4.9](https://github.com/vercel/next.js/releases/tag/v13.4.9) but according to a Next.js user, a v13.4.10 canary version broke this feature :(

<sub>[NEXT-1499](https://linear.app/vercel/issue/NEXT-1499/not-foundtsx-not-using-layouttsx-in-route-groups)</sub>

**Comment by mburumaxwell** [comment]
Could this be what is requested for at https://github.com/vercel/next.js/discussions/50034 ?

**Comment by Yovach** [comment]
> Could this be what is requested for at #50034 ?

Yes, probably, it worked with v13.4.9 but seems to be broken now.
