### ISSUE TITLE
MiddlewareConfig type is no longer available as of version 13.4.13

### ISSUE THREAD

**Issue by iamfj** [vercel/next.js#53696]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 20.2.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/blissful-swanson-3lp48k

### To Reproduce

- Install next@13.4.13
- Create a middleware with config
- Try to import the MiddlewareConfig type

### Describe the Bug

It is strange not to be able to access the MiddlewareConfig type. In version 13.4.12 this was still possible. It was cumbersome (because the type was obtained from the path `next/dist/server/lib/route-resolver`) but it was possible.

It feels wrong to have to define this type now.

### Expected Behavior

I would expect this MiddlewareConfig type to be obtainable from the `next/server` package / path.

**Comment by balazsorban44** [comment]
`next/dist/server/lib/route-resolver` This kind of import was never officially supported. You should not import anything from under `dist` as it is considered internals and can change at any point. That said, New versions of Next.js now properly expose `MiddlewareConfig` since #61576
