### ISSUE TITLE
bug: modularizeImports breaks lucite-react

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#53702]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.14-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/juliusmarminge/lucide-modularize

### To Reproduce

Import any Lucide icon and run `pnpm build`. See this error:

<img width="606" alt="CleanShot 2023-08-07 at 23 52 49@2x" src="https://github.com/vercel/next.js/assets/51714798/998bd223-53b4-4e21-bc70-d712239caea9">

Upon further inspection, we can see that the `cjs` directory doesn't have an `icon` folder, but all the icons seem to be inlined (!???) in the root file...

<img width="1023" alt="CleanShot 2023-08-07 at 23 53 24@2x" src="https://github.com/vercel/next.js/assets/51714798/9abfe92f-5ac4-4c69-ae42-5805c648a9fe">

### Describe the Bug

Can't use lucide-react in next@13.4.13

### Expected Behavior

Can use lucide-react in next@13.4.13

**Comment by juliusmarminge** [comment]
Related to https://github.com/vercel/next.js/issues/53668, but since that was labelled Jest I thought I'd create this one too to cover an even simpler repro

**Comment by gtonussi** [comment]
Hi, had the same issue updating my project to next@13.4.13 using lucide-react@0.265.0.

**Comment by chungweileong94** [comment]
I personally use `import { createLucideIcon } from 'lucid-react'` in my codebase, which throws the same error. 
Unlike other icon imports, `createLucideIcon` is slightly different, and rarely used by most people directly in the application codebase, which I don't think Next team considers about it before.

The only work about I can do now is to remove the modularizeImports support for lucide-react in NextJS via patch-package.

**Comment by balazsorban44** [comment]
Correct, #53697 fixed this, so closing. You can upgrade to `next@canary` to test it out, and it will be available shortly on `next@latest` too.
