### ISSUE TITLE
[>= 13.4.13] .env File not read into node server

### ISSUE THREAD

**Issue by fmacherey** [vercel/next.js#53716]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
I updated to next 13.4.13 and when I start my node server, it says "Listening to port undefined", so `process.env.ENV` is undefined. ENV ist defined in my .env.development file. 

Observations:
- this also happens at 13.4.14-canary.0
- 13.4.12 still works
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

not relevant

### To Reproduce

- update to current 13.4.13 or higher
- run yarn dev 
- server will not be able to listen on port defined in env-File

### Describe the Bug

see above

### Expected Behavior

.env Files are available in server.js

### Which browser are you using? (if relevant)

not relevant

### How are you deploying your application? (if relevant)

node server/index.js

**Comment by schimi-dev** [comment]
Probably related to/same as : https://github.com/vercel/next.js/issues/53579 and https://github.com/vercel/next.js/issues/53367

**Comment by timmywil** [comment]
Is there a workaround for getting the .env.local to load in a custom server? `app.prepare()` is no longer doing it.

**Comment by balazsorban44** [comment]
Thanks for reporting, I'll close this in favor of #53367, you can subscribe to that issue for updates.
