### ISSUE TITLE
Minifier too agressive deletes used code

### ISSUE THREAD

**Issue by santialbo** [vercel/next.js#53723]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC minifier (swcMinify: true), SWC transpilation

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/santialbo/next-swc-issue

### To Reproduce

Create a basic next app
```
npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
```

Create a `/pages` component like the following
```ts
export default function Home() {
  return (
    <div>{foo.a}</div>
  )
}

const foo = {
  get a() {
    return `a ${this.b}`;
  },
  get b() {
    return `b`;
  }
}
```

Run `yarn build` and inspect `.next/chunks/pages/{chunk of the used page}`, the following will be generated:
```
(self.webpackChunk_N_E=self.webpackChunk_N_E||[]).push([[405],{5557:function(n,t,u){(window.__NEXT_P=window.__NEXT_P||[]).push(["/",function(){return u(6616)}])},6616:function(n,t,u){"use strict";u.r(t),u.d(t,{default:function(){return r}});var e=u(5893);function r(){return(0,e.jsx)("div",{children:c.a})}let c={get a(){return"a ".concat(this.b)}}}},function(n){n.O(0,[774,888,179],function(){return n(n.s=5557)}),_N_E=n.O()}]);
```

The previous `foo` object gets compiled into

```
let c={get a(){return"a ".concat(this.b)}}
```
Notice property `get b` is missing! The resulting string is `a undefined` instead of `a b`;

### Describe the Bug

The minifier is too agressive eliminating dead code which is not actually dead.

I noticed this error in my codebase when I upgraded from `13.4.9` to `13.4.13`

### Expected Behavior

Don't delete actually used property.

<sub>[NEXT-1502](https://linear.app/vercel/issue/NEXT-1502/minifier-too-agressive-deletes-used-code)</sub>

**Comment by balazsorban44** [comment]
Looks like it's a regression that slipped in via https://github.com/vercel/next.js/pull/52371, we are looking into it, thanks for reporting!
