### ISSUE TITLE
Cant Open Next.js on macOS

### ISSUE THREAD

**Issue by ShivankK26** [vercel/next.js#53726]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
it is showing this error

Application error: a client-side exception has occurred (see the browser console for more information).
```

### Which example does this report relate to?

nextjs 13

### What browser are you using? (if relevant)

mozilla firefox, chrome, safari

### How are you deploying your application? (if relevant)

none

### Describe the Bug

no idea

### Expected Behavior

it should work

### To Reproduce

![Screenshot 2023-08-08 at 5 48 42 PM](https://github.com/vercel/next.js/assets/115289871/27002c3c-7fed-4d92-9773-b9dc05663b35)

**Comment by fabio-nettis** [comment]
Just tried to open [the page](https://nextjs.org) on my Mac running MacOS 13.5 (22G74). The page opens just fine, try clearing your cache and try again. I do not think that this is related directly to Next.js nor to the operating System of your machine.

**Comment by ShivankK26** [comment]
ok
