### ISSUE TITLE
External API response is cut off when proxying with `rewrites`

### ISSUE THREAD

**Issue by yamashhh** [vercel/next.js#53737]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.13-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/competent-tess-gdqf3w

### To Reproduce

1. Create a proxy for an external API endpoint by setting `rewrites` in `next.config.js`
2. Consume the API in an arbitrary component
3. Check the response from the API

### Describe the Bug

The response JSON is cut off.

![Screenshot 2023-08-09 at 0 33 32](https://github.com/vercel/next.js/assets/51022322/a338d966-236c-42e2-a80c-0c607255d9fa)

### Expected Behavior

The entire API response is available.

Confirmed working when downgraded to v13.2.4.
repro: https://codesandbox.io/p/sandbox/vibrant-http-j6wnzr

```sh
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.2.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

These issues/discussions might be related:

- https://github.com/vercel/next.js/discussions/48265
- https://github.com/vercel/next.js/issues/37783

**Comment by icyJoseph** [comment]
Do you have to downgrade all the way to 13.2.4 for it to break? I can try to do a bit of searching on which commit broke it, but I'd just like some confirmation that 13.2.5 for example is already broken.

**Comment by yamashhh** [comment]
@icyJoseph 

Hi, I've found out that this specific problem might be fixed in the latest canary version,
here is the breakdown:

| Next.js version   | Reproduces |
| ----------------- | ---------- |
| v13.4.12          | NO         |
| v13.4.13          | YES        |
| v13.4.14-canary.1 | NO         |

Confirmed on local machine:

```sh
    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      ppm: 8.6.9
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

[This](https://github.com/yamashhh/nextjs-issues-53737) is the code I used, sorry I had to move from Codesandbox because it was laggy.

**Comment by icyJoseph** [comment]
Awesome, no worries. You can also use Stackblitz from GitHub, like this: 

`https://stackblitz.com/github/yamashhh/nextjs-issues-53737`

**Comment by ian-hutchinson** [comment]
@yamashhh Did you ever verify this in a stable release?

I'm seeing very similar issues in dev when proxying requests on version 13.4.19. 

It feels like something has fundamentally changed with the chunking. I do not see the issue in 13.4.12.

**Comment by tkmcmaster** [comment]
My use case seems intermittent. I thought it was fixed by the canary release (and it worked locally) but is truncated still when deployed in AWS. So I'm still rolled back to `13.3.4`

**Comment by ra-lfaro** [comment]
> @yamashhh Did you ever verify this in a stable release?
> 
> I'm seeing very similar issues in dev when proxying requests on version 13.4.19.
> 
> It feels like something has fundamentally changed with the chunking. I do not see the issue in 13.4.12.

exact same here

**Comment by ra-lfaro** [comment]
after lots of digging i was able to resolve my issue by removing the content-length on the proxy response. This wasnt an issue until upgrading from 13.4.12 to 13.4.19
