### ISSUE TITLE
Docs: Contradiction description in doc about useSelectedLayoutSegment

### ISSUE THREAD

**Issue by leyunn** [vercel/next.js#53731]
### What is the improvement or update you wish to see?

Edit one of the page to make the information consistent

### Is there any context that might help us understand?

In the page of [parallel-routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#useselectedlayoutsegments),
it states that "Both useSelectedLayoutSegment and useSelectedLayoutSegments accept a parallelRoutesKey, which allows you read the active route segment within that slot."

However, if you go to [useSelectedLayoutSegment](https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segment#parameters)
it states that "useSelectedLayoutSegment does not take any parameters."

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#useselectedlayoutsegments

**Comment by leerob** [comment]
Fixed!
