### ISSUE TITLE
typedRoutes: type overrides generated in .next, gitignored, tsc unreliable in CI

### ISSUE THREAD

**Issue by osdiab** [vercel/next.js#53732]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: 8.6.2
    Relevant packages:
      next: 13.4.7-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link), TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue or a replay of the bug

any nextjs app will be this way

### To Reproduce

- make a nextjs app
- add `typedRoutes`
- add code that uses the types generated by `typedRoutes` directly
- make a CI job that runs `tsc` without first running a dev server
- typechecking fails since e.g. `LinkProps` doesn't have a generic (it doesn't if you aren't using `typedRoutes`, but if you are then it does

### Describe the Bug

Types are missingtypedRoutes generated a `.next/types/link.d.ts` file that overrides the builtin `next/link` types. But `.next` is in `.gitignore` by default, and if you typecheck your code in CI using `tsc` directly, then it is likely to not be there at that time. So then the types are missing and then typechecking fails.

### Expected Behavior

one of two things:

- a way to generate the types by a `next` command outside of the dev server
- not gitignoring the types by default

**Comment by shuding** [comment]
Since Next.js edits the tsconfig as well with required things like `next-env.d.ts`, it's not recommended to do the type checking directly via `tsc`. If you run `next build`, Next.js calls the TypeScript compiler directly to do type checking before building your app.

I'll still fix this by adding stub generics to `Route` and `LinkProps` to cover more cases.

**Comment by GabenGar** [comment]
@shuding 
One of the more annoying parts of running type checks with `next build` is it runs linter beforehand (which isn't very fast to begin with and I know its output after the first run) and bails out on the first type error and then, on success, runs an entire build chain. Especially annoying when I only care about broken module references after a refactor, as I know for a fact it won't build until I fix them. IMO if `next` is abstracting typescript away it should provide a command to run it separately, or at least in `next lint` after linting.

**Comment by osdiab** [comment]
Yeah I’m just not going to use NextJS’s implementation of typed routes then. I specifically run my build of the actual application in parallel with the typechecking and linting in GitHub actions so using NextJS’s typechecking during builds slows down our CI by a lot. Coupled with the fact that i actually think the DX of having a separate function to invoke for building links is just better than the 100% typescript string literals union approach, third party library seems like the clear move.
