### ISSUE TITLE
Docs: Add guidance for handling errors in server actions

### ISSUE THREAD

**Issue by Wyatt-SG** [vercel/next.js#53743]
### What is the improvement or update you wish to see?

I would like to see more guidance or examples of handling errors in a server actions and passing those back to the client.

### Is there any context that might help us understand?

Currently my team is altering the URL upon server action errors to include an error search param. This suggestion might help other developers wanting to pass back errors from a server action.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#examples

**Comment by Fredkiss3** [comment]
For handling, a primitive from react needs to be implemented to support getting the action returned value, something like `useActionState(action)` and it would work even without JS enabled.

> From Dan Abramov :  https://twitter.com/dan_abramov/status/1655763129106587648?s=20

**Comment by leerob** [comment]
https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#error-handling

We'll amend this further as more upstream changes land in React 👍
