### ISSUE TITLE
Debugging with non-localhost address doesn't work

### ISSUE THREAD

**Issue by iverks** [vercel/next.js#53757]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-pages

### To Reproduce

set dev script to

"NODE_OPTIONS='--inspect=0.0.0.0:9229' next dev"

### Describe the Bug

https://github.com/vercel/next.js/issues/47083 is not fixed

When debugging in docker i need to set --inspect host to be 0.0.0.0 to reach it from the outside. When i do this next crashes because it interprets 0.0.0.0:9229 as only the port. See better explaination in linked issue. The issue is wrongly marked as fixed.

### Expected Behavior

Debugger starts but uses 0.0.0.0 instead of 127.0.0.1

### How are you deploying your application? (if relevant)

Docker (developing)

**Comment by simonstaton** [comment]
For anyone facing the same issue, there is a temporary workaround to define the inspect argument twice initially with only the port --inspect=9229 --inspect=0.0.0.0

**Comment by simonstaton** [comment]
Any update on this? Currently it's impossible to debug a NextJS application running in a docker container.
