### ISSUE TITLE
Revalidate not working with Pages Router on dynamic routes

### ISSUE THREAD

**Issue by IlirEdis** [vercel/next.js#53750]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.16.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/IlirEdis/revalidate-test

### To Reproduce

- Create a new blog post in Strapi. 
- Run `npm run build`
- Run `npm run start`
- Refresh the page

In home page the new blog post appears because its a static route but if you click on the post it sends to a 404 because the dynamic route (the single post) was not revalidated.

### Describe the Bug

After creating a new blog in my Strapi instance, the same post appears in the first page because it is a static page (`index.tsx`) however if you click on that post it leads to a 404 which means that the dynamic route did not revalidate.

I have months that i'm forced to redeploy on vercel every time me or someone from the team created a new blog post.

_*btw we have a pro plan on vercel and still didn't get a reply on my support ticket!_

### Expected Behavior

Display my newly created posts from CMS without building the app or redeploy on vercel (my case)

### How are you deploying your application? (if relevant)

Vercel

**Comment by wwwdepot** [comment]
Use fallback = blocking instead of false 

https://github.com/IlirEdis/revalidate-test/blob/main/pages/%5BpostSlug%5D.tsx#L124

```diff
-fallback: false,
+fallback: 'blocking',
```

> If fallback is false, then any paths not returned by getStaticPaths will result in a 404 page.

https://nextjs.org/docs/pages/api-reference/functions/get-static-paths#fallback-false
