### ISSUE TITLE
Docs: More Rewrite Config Examples

### ISSUE THREAD

**Issue by jamesmcintyre** [vercel/next.js#53774]
### What is the improvement or update you wish to see?

More examples for regex path-matching in next config rewrites. Not everyone is a regex expert but also the way the rewrites work in-addition to normal regex behaviors is even confusing.

- Specifically try to add more common path-matching examples that'd help save many devs time.
- Such as nested routes, catch-all after a single route, etc.

Even better would be linking to a simple vercel-hosted web app that'd help you build the path-match string!

### Is there any context that might help us understand?

The request may sound needy but I think these are the types of things that really improve DX if they can be improved.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/next-config-js/rewrites#regex-path-matching

**Comment by leerob** [comment]
Hey! Thank you for the suggestion. 

I like using https://regexr.com/ or ChatGPT to help with regexes. Since this isn't anything specific to Next.js, and it's hard to tell specifically what regexes folks might want, I am okay with leaving it as is 🙏
