### ISSUE TITLE
Docs: Description in intercepting routes is misleading.

### ISSUE THREAD

**Issue by iamrahulrnair** [vercel/next.js#53787]
### What is the improvement or update you wish to see?

![image](https://github.com/vercel/next.js/assets/55950758/0ef2ea41-f73f-415c-ba90-5e49e67055ed)
This part is kind of misleading, If i click on a feed item the intercepting route is /photos segment not the /feed. If i am wrong why the /feed is intercepted to show /photos/:id, it should intercept from the current context isn't it? I think the documentation needs an update around this and simplify the use of word 'intercept'.

### Is there any context that might help us understand?

Documentation regarding intercepting routes

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes

<sub>[DX-1891](https://linear.app/vercel/issue/DX-1891/docs-description-in-intercepting-routes-is-misleading)</sub>

**Comment by delbaoliveira** [comment]
Thank you, agree, it is kind of confusing. How's this fix? https://github.com/vercel/next.js/pull/53854

**Comment by iamrahulrnair** [comment]
looks good now, now the intercepting part make sense.
