### ISSUE TITLE
turborepo not working in pages

### ISSUE THREAD

**Issue by ThyeeZz** [vercel/next.js#53781]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Jun  8 23:57:12 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_X86_64
    Binaries:
      Node: 19.9.0
      npm: 9.6.3
      Yarn: 1.22.10
      pnpm: 8.6.11
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/ThyeeZz/zilliz-website/tree/add-i18n

### To Reproduce

I created a project according to [truborepo doc]( https://turbo.build/repo/docs/getting-started/create-new);

change directory to ./apps/web-app and run `pnpm dev`,  the error like following will arise:
![image](https://github.com/vercel/next.js/assets/41352919/26eb09c0-f5c3-4fd8-89e1-082c54188ebf)

### Describe the Bug

can't load a .jsx or .tsx file

### Expected Behavior

no error arises

**Comment by anthonyshew** [comment]
Hi! You'll need to make sure you use [transpilePackages](https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages) when you're importing `.tsx` files directly.

**Comment by ThyeeZz** [comment]
> Hi! You'll need to make sure you use [transpilePackages](https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages) when you're importing `.tsx` files directly.

It works now, thanks a lot!
