### ISSUE TITLE
Fetch requests no longer logging in 13.4.13 they show in 13.4.12

### ISSUE THREAD

**Issue by MrHus** [vercel/next.js#53795]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/condescending-noyce-qmd4d9

### To Reproduce

Make a call using fetch in a server component see that nothing is logged.

### Describe the Bug

Logs are disabled 

### Expected Behavior

In the logs you'd expect to see these types of logs:

`┌ GET /users/1 200 in 60ms`

**Comment by gtonussi** [comment]
I'm having the same issue with server side calls. Not only them are not logging, but there is no loggin at all.

Usually, when server is started, I get:

"wait compiling...
event compiled..."

Those would show up right after npm run dev, and also after each new save. Now there is nothing on console.

Next@13.4.13

**Comment by davecarlson** [comment]
fetch seems to be completely broken server side in my route.ts handlers , all are now failing with the following:
```
Aug  9 17:16:58 ip-172-31-12-152 web: TypeError: fetch failed
Aug  9 17:16:58 ip-172-31-12-152 web: at Object.fetch (node:internal/deps/undici/undici:11413:11)
Aug  9 17:16:58 ip-172-31-12-152 web: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Aug  9 17:16:58 ip-172-31-12-152 web: at async invokeRequest (/var/app/current/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
Aug  9 17:16:58 ip-172-31-12-152 web: at async requestHandler (/var/app/current/node_modules/next/dist/server/lib/start-server.js:336:33)
Aug  9 17:16:58 ip-172-31-12-152 web: at async Server.<anonymous> (/var/app/current/node_modules/next/dist/server/lib/start-server.js:152:13) {
Aug  9 17:16:58 ip-172-31-12-152 web: cause: RequestContentLengthMismatchError: Request body length does not match content-length header
Aug  9 17:16:58 ip-172-31-12-152 web: at write (node:internal/deps/undici/undici:9907:41)
Aug  9 17:16:58 ip-172-31-12-152 web: at _resume (node:internal/deps/undici/undici:9885:33)
Aug  9 17:16:58 ip-172-31-12-152 web: at resume (node:internal/deps/undici/undici:9787:7)
Aug  9 17:16:58 ip-172-31-12-152 web: at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
Aug  9 17:16:58 ip-172-31-12-152 web: code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
```

**Comment by davecarlson** [comment]
Further update on here - it only happens if you include an additional header (ie, x-user-token). Remove the header, and the fetch works...

**Comment by davecarlson** [comment]
I've tracked it down to this PR: https://github.com/vercel/next.js/pull/53368

Manually undoing this change fixes it for safari locally.

**Comment by cjboco** [comment]
Was trying to deploy a docker image and getting the same fetch errors. (p.s. I had fetches with no headers and it was still giving me fetch errors).

reverted back to 13.4.12 and it's all working now.

**Comment by huozhi** [comment]
@MrHus You need to enable `logging` this in `next.config.js` now with new version
```
module.exports = {
  experimental: {
     logging: "verbose"
  }
}
```

**Comment by MrHus** [comment]
@huozhi I've enabled `logging: 'verbose'`:

`You have enabled experimental feature (logging) in next.config.js.`

But it still is not showing any request logs.

I'm sending custom headers like @davecarlson, when I stop sending headers it shows the logs again.

Please re-open this issue.

**Comment by davecarlson** [comment]
The issue is that the fetch will send 
"Content-Length": "0". 

This will break, as it is not correctly being filtered out anymore like it used to (the PR changed the bevahiour).

This hotfix fixes it: 

Before: 
```
const filterReqHeaders = (headers, forbiddenHeaders)=>{
    
    for (const [key, value] of Object.entries(headers)){
        if (forbiddenHeaders.includes(key) || !(Array.isArray(value) || typeof value === "string")) {
            delete headers[key];
        }
    }
    return headers;
};
```

After:
```
const filterReqHeaders = (headers, forbiddenHeaders)=>{

    if (headers['content-length'] && headers['content-length'] === '0') {
        delete headers['content-length']
    }
    
    for (const [key, value] of Object.entries(headers)){
        if (forbiddenHeaders.includes(key) || !(Array.isArray(value) || typeof value === "string")) {
            delete headers[key];
        }
    }
    return headers;
};
```
