### ISSUE TITLE
Serverless functions cant find the statically bundled libraries like ffmpeg-static and ffprobe-static

### ISSUE THREAD

**Issue by Rameshv** [vercel/next.js#53791]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.6.5
      Yarn: 1.22.19
      pnpm: 6.8.0
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Rameshv/next-ffprobe

### To Reproduce

clone the repo https://github.com/Rameshv/next-ffprobe and run `npm run dev` and upload a file 

### Describe the Bug

I am trying to use `ffprobe-static` https://www.npmjs.com/package/ffprobe-static to get the meta data about the uploaded file in next js 13 API routes. 

here is a sample code

```
var ffprobe = require('ffprobe-static')
var ffmpeg = require('ffmpeg-static')
var fs = require('fs')
import util from 'util'
const exec = util.promisify(require('child_process').exec)
import path  from 'path'

export async function POST(req: NextRequest) {
    console.log(ffmpeg)
	const data = await req.formData()
    const uploads = []
    const keys = data.keys()

    const file = data.get(keys.next().value) as File

    const outpath = `/tmp/${file.name}`
    if (!fs.existsSync(path.dirname(outpath))){
        fs.mkdirSync(path.dirname(outpath))
    }
    const buffer  = await file.arrayBuffer()
    fs.writeFileSync(outpath, Buffer.from(buffer))

    const ffprobeCommand = `${ffprobe.path} -i ${outpath} -show_entries format=duration -v quiet -of csv="p=0"`
    const { stdout: durationOutput } = await exec(ffprobeCommand)
    const durationInSeconds = parseFloat(durationOutput.trim())
    const durationInMins = Math.round(durationInSeconds / 60)


    return NextResponse.json(durationInMins)
}
```

when calling `ffprobe.path`, this is expected to return the statically bundled path from node_modules path like this
`/Users/rameshvel/work/ffprobe-issue/node_modules/ffprobe-static/bin/darwin/x64/ffprobe'`

but instead it was returning the path from `/Users/rameshvel/work/ffprobe-issue/.next/server/app/api/upload/ffmpeg`. And thats a wrong path.

### Expected Behavior

looking at the code `ffprobe-static` code, I see 

```
var ffprobePath = path.join(
  __dirname,
  'bin',
  platform,
  arch,
  platform === 'win32' ? 'ffprobe.exe' : 'ffprobe'
);
```

` __dirname,` seems to be the problem. any ideas how to reslolve this for next??

**Comment by Rameshv** [comment]
I managed to get this working with copy webpack plugin
```

/** @type {import("next").NextConfig} */
const CopyPlugin = require("copy-webpack-plugin");
const PermissionsOutputPlugin = require('webpack-permissions-plugin');
module.exports = {
  reactStrictMode: true,
  webpack: (config, options) => {
    config.plugins.push(new CopyPlugin({
      patterns: [
        { from: "./node_modules/ffprobe-static/bin", to: "./app/api/upload/bin/" },
      ],
    }))
    config.plugins.push(new PermissionsOutputPlugin({
      buildFiles: [
        "./.next/server/app/api/upload/bin/darwin/x64/ffprobe",
        "./.next/server/app/api/upload/bin/darwin/arm64/ffprobe",
        "./.next/server/app/api/upload/bin/linux/x64/ffprobe",
        "./.next/server/app/api/upload/bin/linux/ia32/ffprobe",
        "./.next/server/app/api/upload/bin/win32/x64/ffprobe",
        "./.next/server/app/api/upload/bin/win32/ia32/ffprobe",
      ],
    }))
    console.log(config.plugins)
    return config
  },
}

```

not sure if this is the way to do it in next.js. but works so far. lets see if it can be deployed in vercel without the same issue

**Comment by Rameshv** [comment]
NOPE. This only works in dev mode. does not work in deployed vercel app. Back to square one. 

I really need to have `ffmpeg & ffprobe` installed on my vercel instance to go ahead with the deployments.  

I also tried installing it via `installCommand` using 'yum`. that also not working.
This is kind of a basic thing to do and was hoping there should be an easy way to add external dependencies with next.js. But I am not finding one.

any help is much appreciated.

**Comment by njarraud** [comment]
I have the same issue with all packages that are trying to load files with fs e.g. pngquant-bin, tinify, etc.
They use __dirname inside their code but unfortunately in appDir, __dirname seems to default to the path of the api script importing the modules.

**Comment by njarraud** [comment]
````
config.externals = [...config.externals, 'pngquant-bin']```
does the trick for me in the webpack config

**Comment by Rameshv** [comment]
Hi @njarraud , thanks for the suggestion
unfortunately, I still got the same error. is there 

`stderr: '/bin/sh: /Users/rameshvel/work/ffprobe-issue/.next/server/app/api/media/upload/bin/darwin/x64/ffprobe: No such file or directory\n'`

any ideas? should I have to make any other changes besides webpack externals ??

**Comment by balazsorban44** [comment]
By default, dependencies are bundled in App Router, likely causing the problem.


You can opt out of this with the following config option https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages
