### ISSUE TITLE
Expect header not supported on API route POST requests after switch to undici

### ISSUE THREAD

**Issue by ambrauer** [vercel/next.js#53822]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/suspicious-fermat-dg7pkp

### To Reproduce

Send a POST request to https://dg7pkp-3000.csb.app/api/foo which includes the [Expect](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect) header (`Expect: 100-continue`).

### Describe the Bug

Starting from next@13.4.13 POST requests to (Pages-based) API routes with an Expect header fail with an error:
![image](https://github.com/vercel/next.js/assets/400763/84b9bac5-daa0-4c61-84bf-0baf340b026f)

Using next@13.4.12 the issue is not reproducible.

The Expect header is apparently [automatically sent by .NET](https://learn.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.expect100continue?view=net-7.0). We are simultaneously looking into disabling this in the .NET client making these particular requests.

**Here are notes from a colleague's investigation into this...**
You have an internal invoke-request file that executes internal server side fetch call when API route is triggered by POST request

Before  <13.4.13 you used node fetch: https://github.com/vercel/next.js/blob/v13.4.12/packages/next/src/server/lib/server-ipc/invoke-request.ts#L4

In scope of 13.4.13 you removed node fetch and started to use [undici](https://github.com/nodejs/undici): https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/server-ipc/invoke-request.ts#L27

undici doesn't support this header, so it's a breaking change for us, see: https://github.com/nodejs/undici/blob/main/lib/core/request.js#L354

Here is a PR where you made these changes: [https://github.com/vercel/next.js/commit/1398de9977b89c9c4717d26e213b52bc63ccbe7e#diff-52cd95be25b76891bc705a2b49[…]530283792dd37f6bbd332feb4255ab1f](https://github.com/vercel/next.js/commit/1398de9977b89c9c4717d26e213b52bc63ccbe7e#diff-52cd95be25b76891bc705a2b498cbd25530283792dd37f6bbd332feb4255ab1f)

Here is a PR where you mentioned migration to undici: https://github.com/vercel/next.js/pull/53548

### Expected Behavior

Expect header is supported.

**Comment by davecarlson** [comment]
These changes also break GET requests to a route handler if the request came from safari:

‘’’
Aug  9 17:16:58 ip-172-31-12-152 web: TypeError: fetch failed
Aug  9 17:16:58 ip-172-31-12-152 web: at Object.fetch (node:internal/deps/undici/undici:11413:11)
Aug  9 17:16:58 ip-172-31-12-152 web: at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Aug  9 17:16:58 ip-172-31-12-152 web: at async invokeRequest (/var/app/current/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
Aug  9 17:16:58 ip-172-31-12-152 web: at async requestHandler (/var/app/current/node_modules/next/dist/server/lib/start-server.js:336:33)
Aug  9 17:16:58 ip-172-31-12-152 web: at async Server.<anonymous> (/var/app/current/node_modules/next/dist/server/lib/start-server.js:152:13) {
Aug  9 17:16:58 ip-172-31-12-152 web: cause: RequestContentLengthMismatchError: Request body length does not match content-length header
Aug  9 17:16:58 ip-172-31-12-152 web: at write (node:internal/deps/undici/undici:9907:41)
Aug  9 17:16:58 ip-172-31-12-152 web: at _resume (node:internal/deps/undici/undici:9885:33)
Aug  9 17:16:58 ip-172-31-12-152 web: at resume (node:internal/deps/undici/undici:9787:7)
Aug  9 17:16:58 ip-172-31-12-152 web: at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
Aug  9 17:16:58 ip-172-31-12-152 web: code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
‘’’
