### ISSUE TITLE
Catch all params (`[...slug]`) are an array of 1 url encoded string when using `edge` runtime

### ISSUE THREAD

**Issue by remorses** [vercel/next.js#53849]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/remorses/next.js-bug-encoded-dynamic-param/tree/main

### To Reproduce

-   Deploy to Vercel with `edge` runtime
-   click the link `navigate to another/random`
-   Notice that the param `slug` is not an array of paths, but it's url encoded (something like `["another%2Frandom"]`)

### Describe the Bug

The catch all param `slug` is not an array of paths, but it's an array of a string url encoded (something like `["another%2Frandom"]`)

### Expected Behavior

`slug` should be `["another", "random"]

Related to 
https://github.com/vercel/next.js/issues/50856
https://github.com/vercel/next.js/issues/47651 (that was when using `experimental-edge`, the slash was not url encoded)
https://github.com/vercel/vercel/issues/9723

### Which browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1506](https://linear.app/vercel/issue/NEXT-1506/catch-all-params-[slug]-are-an-array-of-1-url-encoded-string-when)</sub>

**Comment by simonecervini** [comment]
I reported the same issue a few days ago here with a similar repro if that helps: https://github.com/vercel/next.js/issues/53682

I might as well close the issue at this point

**Comment by remorses** [comment]
Does the issue reproduce locally for you?

**Comment by remorses** [comment]
I will close this issue then
