### ISSUE TITLE
Middleware does not match when use :path

### ISSUE THREAD

**Issue by burakkgunduzz** [vercel/next.js#53840]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 3.4.1
      pnpm: 8.5.1
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/burakkgunduzz/middleware-match-bug

### To Reproduce

Go to homepage and click to link to go to a detail page.
Expect that middleware runs but it does not.

### Describe the Bug

I have a dynamic route in pages dir which is product/[slug].tsx
I have a middleware which includes code below
```js
export default function middleware (){
    console.log("hello from middleware")
}
// below line should match but it does not
export const config = {matcher: ["/product/:path"]}
```
When I go to this dynamic route either via Link or from url my middleware does not run. But If I put * to the end of the :path as "/listing/:path*" it runs.

However, asterix should only be helpful for paths like /product/anyRoute/anyRoute/anyRoute

I would like to match with only my dynamic route not nested routes.

### Expected Behavior

Middleware should match and run when provide a path as /anyRoute/:path

**Comment by burakkgunduzz** [comment]
Any updates here?

**Comment by burakkgunduzz** [comment]
any updates here?

**Comment by m-sanders** [comment]
This is still an issue. The workaround I am using is to use regex pattern matching:

```
export const config = {matcher: ["/product/:path([\\w-_]+)"]}
```

But this is a little unwieldy and can introduce new venues for bugs.
