### ISSUE TITLE
while deploying my nextjs project with sentry on aws amplify build getting failed

### ISSUE THREAD

**Issue by gauravsapkal1** [vercel/next.js#53867]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
I am using nextjs 11.1.3 when I added sentry error tracking to my next js project when i build and run it locally it works fine but when i deploy my sentry nextjs project on aws amplyfy my build getting failed with following error,
'> Build error occurred\n' +
                                  'Error: spawn ENOMEM\n' +
                                  '    at ChildProcess.spawn (node:internal/child_process:420:11)\n' +
                                  '    at spawn (node:child_process:733:9)\n' +
                                  '    at fork (node:child_process:169:10)\n' +
                                  '    at ChildProcessWorker.initialize (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:141:45)\n' +
                                  '    at new ChildProcessWorker (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:132:10)\n' +
                                  '    at WorkerPool.createWorker (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/WorkerPool.js:44:12)\n' +
                                  '    at new BaseWorkerPool (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/base/BaseWorkerPool.js:135:27)\n' +
                                  '    at new WorkerPool (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/WorkerPool.js:30:1)\n' +
                                  '    at new Worker (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/index.js:167:26)\n' +
                                  '    at createWorker (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/lib/worker.js:15:28)\n' +
                                  '    at new Worker1 (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/lib/worker.js:21:9)\n' +
                                  '    at /codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/build/index.js:432:31\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/telemetry/trace/trace.js:60:20)\n' +
                                  '    at async Object.build [as default] (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/build/index.js:77:25) {\n' +
                                  '  errno: -12,\n' +
                                  "  code: 'ENOMEM',\n" +
                                  "  syscall: 'spawn'\n" +
                                  '}',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
                                  [G
2023-08-10T16:47:33.927Z [ERROR]: [?25h[G[J
                                  300s › darxjey0xrl5c › Error: Command failed with exit code 1: node_modules/.bin/next build
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/tree/canary/examples/reproduction-template-pages

### To Reproduce

**Below is my aws amplify build logs**
'> Build error occurred\n' +
                                  'Error: spawn ENOMEM\n' +
                                  '    at ChildProcess.spawn (node:internal/child_process:420:11)\n' +
                                  '    at spawn (node:child_process:733:9)\n' +
                                  '    at fork (node:child_process:169:10)\n' +
                                  '    at ChildProcessWorker.initialize (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:141:45)\n' +
                                  '    at new ChildProcessWorker (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/workers/ChildProcessWorker.js:132:10)\n' +
                                  '    at WorkerPool.createWorker (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/WorkerPool.js:44:12)\n' +
                                  '    at new BaseWorkerPool (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/base/BaseWorkerPool.js:135:27)\n' +
                                  '    at new WorkerPool (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/WorkerPool.js:30:1)\n' +
                                  '    at new Worker (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/node_modules/jest-worker/build/index.js:167:26)\n' +
                                  '    at createWorker (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/lib/worker.js:15:28)\n' +
                                  '    at new Worker1 (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/lib/worker.js:21:9)\n' +
                                  '    at /codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/build/index.js:432:31\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/telemetry/trace/trace.js:60:20)\n' +
                                  '    at async Object.build [as default] (/codebuild/output/src489982623/src/Expertia-nextjs/node_modules/next/dist/build/index.js:77:25) {\n' +
                                  '  errno: -12,\n' +
                                  "  code: 'ENOMEM',\n" +
                                  "  syscall: 'spawn'\n" +
                                  '}',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
                                  [G
2023-08-10T16:47:33.927Z [ERROR]: [?25h[G[J
                                  300s › darxjey0xrl5c › Error: Command failed with exit code 1: node_modules/.bin/next build

### Describe the Bug

When I add sentry error trcking to my nextjs after deploymemnt on aws amplify my build getting filed with   'Error: spawn ENOMEM\n' +

### Expected Behavior

build should not failed on aws amplify

**Comment by k1995** [comment]
Encountered the same problem, resolved by upgrading to the latest nextjs version(v13.4.13)

**Comment by balazsorban44** [comment]
Closing as per the above comment, thanks! Feel free to open a new issue with an up-to-date reproduction if you still have problems!

**Comment by gauravsapkal1** [comment]
@k1995  is there any other way to do without upgrading to next 13 ?

**Comment by gauravsapkal1** [comment]
is there any way so that we can generate source-maps for nextjs other than build process, my problem is I cannot build source-map on amplify due to memory issue, So I need to build source-maps separately and upload them to sentry error tracking to get proper error tracking, but after build in .next folder all files name are not consistent for every build. So is there any way to maintain consistent file names every time we build nextjs application?
