### ISSUE TITLE
optimizeCss doesn't include any inline style

### ISSUE THREAD

**Issue by GeorgeHulpoi** [vercel/next.js#53863]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Static HTML Export (output: "export")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/GeorgeHulpoi/next-critical-css-issue

### To Reproduce

1. Create the Application (TypeScript / ESLint / SASS / using src folder)
2. Add the following option in `next.config.js`:
```js
experimental: { optimizeCss: true },
```
3. Install `critters`, latest version or `0.0.6`, seems like both doesn't work for me.
4. `npm run build`
5. `npm run start`

### Describe the Bug

The rendered HTML doesn't contain any `style` tag for critical CSS.

### Expected Behavior

It should include the critical CSS as a `inline style` like in the integration test for Critical CSS: https://github.com/vercel/next.js/tree/canary/test/integration/critical-css

### How are you deploying your application? (if relevant)

next start

**Comment by SukkaW** [comment]
`optimizeCss` only works with the Page Router and doesn't work with the new App Router.

**Comment by GeorgeHulpoi** [comment]
> `optimizeCss` only works with the Page Router and doesn't work with the new App Router.

Still it should include the critical inline styles. Isn't the layout the part of the same page?!

**Comment by galaxynova1999** [comment]
you can try something like this: `https://gist.github.com/lebreRafael/1546623f730d0e93f163afadb32cb594`

simply rewriting Head.getCssLinks method, and load all css file line during request

**Comment by juanferreras** [comment]
> you can try something like this: `https://gist.github.com/lebreRafael/1546623f730d0e93f163afadb32cb594`
> 
> simply rewriting Head.getCssLinks method, and load all css file line during request

This wouldn't be possible on the app directory though, `_document` does not exist.

---

I understand that `optimizeCss` hasn't ever graduated from experimental, but nonetheless the idea of iterating through CSS chunks and inlining the styles that are directly needed in the HTML seems like it'd still beneficial in many scenarios (explicitly, in terms of FCP and LCP) for sites with at least 1 blocking stylesheet. Unless I'm mistaken, that'd apply for all the "recommended" styling approaches on appDir such as CSS modules, Tailwind or anything else that uses the same CSS chunking.

I don't know whether...
A. React's Float has any specific treatment upcoming for these OR
B. If using `useServerInsertedHTML` as described in https://nextjs.org/docs/app/building-your-application/styling/css-in-js#configuring-css-in-js-in-app could let someone achieve a similar effect in userland (e.g. append to `<head/>` critical styles from the SSR'd HTML). There still wouldn't be any way of making those built-in external link tags load without blocking paint though

**Comment by lucgagan** [comment]
> you can try something like this: https://gist.github.com/lebreRafael/1546623f730d0e93f163afadb32cb594
> simply rewriting Head.getCssLinks method, and load all css file line during request

Is there an equivalent for app dir?

**Comment by benjamindell** [comment]
I was also hoping to see a solution for the App Router architecture.

**Comment by thaophamvan** [comment]
When this feature available on app router?

**Comment by erdalugur** [comment]
same! please add that feature

**Comment by leerob** [comment]
https://github.com/vercel/next.js/discussions/59989#discussioncomment-7962270
