### ISSUE TITLE
next/image broken in AWS Amplify for 13.4.13+

### ISSUE THREAD

**Issue by blathersbugs** [vercel/next.js#53872]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.17.0
      npm: 9.8.1
      Yarn: 4.0.0-rc.48
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A

note that this is probably not helpful, as it runs locally under this environment

I don't have a way to get details on the amplify hosting environment
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/blathersbugs/nextjs-13.4.13-amplify-images-issue-repro

### To Reproduce

deploy repository to aws amplify
view in browser

you can see it here:
https://main.d2qhtpew952tt6.amplifyapp.com/

repository uses dynamically build links (created as static strings) with next/image
uses middleware to append locale to url and locale to build url

### Describe the Bug

images load as broken links,
this worked in 13.4.12
there have been a few bug reports about this breaking in the past.

### Expected Behavior

Images load and are optimized

tests should be implemented so this doesn't keep breaking.

### Which browser are you using? (if relevant)

pretty sure this doesn't matter, but Chrome Version 115.0.5790.171 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

AWS Amplify

**Comment by blathersbugs** [comment]
if you get a 404, try the url with a locale at the end like:
https://main.d2qhtpew952tt6.amplifyapp.com/en-US
it should automatically redirect, but it might not be working, might be a problem with the url rewrite rules in amplify,
I don't think it is a problem with nextjs

**Comment by espenbye** [comment]
Same issue here

**Comment by frattaro** [comment]
Doesn't only affect images, I've seen it affecting SSR pages like:

`Failed to load static props`
and you can see in the network request
`https://pr-521.<my_app_id>.amplifyapp.com/_next/data/4kgGdNIlqLokQFmCPI1rw/en/<my_slug>.json?slug=<my_slug_part_1>&slug=<my_slug_part_1>`

**Comment by ferdingler** [comment]
Downgrading to `13.4.12` indeed fixes the problem on Amplify Hosting. Here is the same app working with that version: https://main.d2lnvvwfrjw6ix.amplifyapp.com. Repo: https://github.com/ferdingler/nextjs-13.4.13-amplify-images-issue-repro/commit/4eacd0220a10153aa4ba4c06e28da114353912f1

**Comment by admmasters** [comment]
Whatever happened in 13.4.13 was a really problematic change for a lot of next/image users (had a similar issue in eks). Even the current version hasn't fixed a lot of the errors. I thought Vercel were looking to try and get a bit of stability back into next.js but it looks to me like the testing on non Vercel platforms is not at all a priority 😔

**Comment by frattaro** [comment]
semantic versioning should be better respected

**Comment by ArianHamdi** [comment]
Same here
Middleware seems to be ignored

**Comment by pachoclo** [comment]
Also affected by this problem (hosting on Amplify).

- Works fine on 13.4.12
- Breaks from 13.4.13 (up to 13.4.16)

**Comment by ferdingler** [comment]
This seems to be the change that broke v13.4.13: https://github.com/vercel/next.js/pull/52492

**Comment by ethyaan** [comment]
This is AWS Amplify side problem, because of recent changes the middleware is getting ignored, they are working on it but when I'm nor sure, due to this I have to move from Amplify to docker images on a EC2 instance which is time consuming operation.

**Comment by blathersbugs** [comment]
> This seems to be the change that broke v13.4.13: #52492

This should have been at least a minor version update.
I don't see how this is a bugfix.

**Comment by terrymun** [comment]
On v13.4.19 and the bug is still reproducible.

**Comment by nosovandriy** [comment]
Also, have this problem - The image component is broken, and sometimes Error 500 on Amplify). 
Everything works on 13.4.12, but not works from 13.4.13 to the latest version 13.4.19

**Comment by sciarrilli** [comment]
+1

**Comment by pachoclo** [comment]
> This is AWS Amplify side problem, because of recent changes the middleware is getting ignored, they are working on it but when I'm nor sure, due to this I have to move from Amplify to docker images on a EC2 instance which is time consuming operation.

@ethyaan Do you have a link to a GH issue (on the Amplify side)?

**Comment by leerob** [comment]
Hey folks – this appears to be an issue with AWS Amplify. `next/image` appears to be working correct both in `next dev` and with `next start` (using the default image optimization, with the `next/image` component).

Let's continue this conversation on the Amplify side https://github.com/aws-amplify/amplify-hosting/issues/3641 🙏
