### ISSUE TITLE
Regression in ctx.req parameters availability in Document getInitialProps in version 13.4.13 (works in 13.4.12)

### ISSUE THREAD

**Issue by carystanley** [vercel/next.js#53883]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.19.0
      npm: 9.2.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/carystanley/nextjs-req-context-regression

### To Reproduce

Clone the repo at https://github.com/carystanley/nextjs-req-context-regression, install and use `npm run dev`

go to: `http://localhost:3000/`
see page with:

```
Fail: Missing Header Data
Hello World
```

run `npm i next@13.4.12`

use `npm run dev`

go to: `http://localhost:3000/`
see page with:

```
Has Header Data
Hello World
```

### Describe the Bug

Not sure if this bug is specific in our setup. But we have express running and we have middleware that adds "context" to the req object. We then use that information in our Document getInitialProps(ctx) to make a data call for the header which is customized based on `req.context` and other `req.*` metadata.

This worked fine in version  13.4.12, but some regression occurred in 13.4.13 that has cause the additional `req.*` metadata to no longer be available.

This was a breaking change that broke our application

### Expected Behavior

We would expect it to operate like it did in version 13.4.12 where `req.*` information on the `req` object in Document getInitialProps(ctx) was still available.

### How are you deploying your application? (if relevant)

express

**Comment by ehwarren** [comment]
Possibly the same issue,

attempting any of the login/logout methods through Next-Auth is broken on localhost in version 13.4.13, it always redirects to https:// which doesn't work for localhost.

in 13.4.12, the proto from the original request is retained, in the case of localhost, this is http:.

I know they are using server context as well, so i'm assuming this is the issue but I haven't dove in.

**Comment by sshah98** [comment]
> Possibly the same issue,
> 
> attempting any of the login/logout methods through [Next-Auth](https://linear.app/vercel/issue/NEXT-Auth) is broken on localhost in version 13.4.13, it always redirects to https:// which doesn't work for localhost.
> 
> in 13.4.12, the proto from the original request is retained, in the case of localhost, this is http:.
> 
> I know they are using server context as well, so i'm assuming this is the issue but I haven't dove in.

did you ever figure out if this is the issue?

**Comment by balazsorban44** [comment]
Closing in favor of #54440

**Comment by carystanley** [comment]
Consolidation is fine, as long as this regression is ultimately fixed
