### ISSUE TITLE
Catch-all route takes precedence over dynamic routes when navigating with next/link

### ISSUE THREAD

**Issue by clueleaf** [vercel/next.js#53887]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/clueleaf/next-catch-all-route-reproduction

### To Reproduce

1. Start the Next app with dev mode

> yarn dev

2. Open the root page

> http://localhost:3000/

3. Click the `Post 1` link (http://localhost:3000/posts/1)
4. The page returns 404 even though `/posts/[id]/index.tsx` file exists under `/pages` folder
5. If you reload, `Post 1` page loads successfully

### Describe the Bug

This happens when a catch-all route (`[...rest].tsx`) is defined and `getServerSideProps` is used in both the catch-all route and the destination dynamic route (`/posts/[id]/index.tsx`).

I'm using catch-all route in order to redirect any routes to the sign in page if the user doesn't have a session. If the user has the session, catch-all route returns 404 because the user should know that the page doesn't exist.
(In the reproduction repo, the sign in page is not included and catch-all route always returns 404, assuming the user is already signed in).

```ts
// /pages/[...rest].tsx

export const getServerSideProps: GetServerSideProps = async (context) => {
  //   const session = ...
  //   if (!session) {
  //     return { redirect: { destination: `/signin?callback=${context.resolvedUrl}`, permanent: false } };
  //   }
  return { notFound: true };
};
```

When navigating to a dynamic routes using Next `Link` component, somehow this catch-all route is triggered and 404 is returned even though the route exists.

Here is the `getServerSideProps` func in the dynamic route. 

```ts
// /pages/posts/[id]/index.tsx

export const getServerSideProps: GetServerSideProps = async (context) => {
  //   const session = ...
  //   if (!session) {
  //     return { redirect: { destination: `/signin?callback=${context.resolvedUrl}`, permanent: false } };
  //   }
  //   return { props: { session } };

  return { props: {} };
};
```

One of the following actions fixes this bug, but makes it difficult to redirect anonymous users to the login page.
* Remove `/pages/[...rest].tsx` completely
* Remove `getServerSideProps` in `/pages/[...rest].tsx`
* Remove `getServerSideProps` in `/pages/posts/[id]/index.tsx`

It seems like this bug happens from v13.4.13, and only in dev mode.

### Expected Behavior

404 is not returned when navigating to a dynamic route with `Link` component.

<sub>[NEXT-1535](https://linear.app/vercel/issue/NEXT-1535/catch-all-route-takes-precedence-over-dynamic-routes-when-navigating)</sub>

**Comment by alexcibotari** [comment]
I have exactly the same situation with a little bit different setup 

````
- app
  - [...slug]
    - layout.tsx
    - page.tsx
  - api
    - draft
      - rout.ts
````

When I try to access **/api/draft** it is handled by **[...slug]**

**Comment by esotericbug** [comment]
`- pages
  - [...slugs]
    - index.tsx
  - blog
    - [slug]
     - index.tsx
    - index.tsx
  `
  
I have the same issue but in pages router. Which was fixed by downgrading back from v13.4.19 to v13.4.12.

**Comment by joerambo** [comment]
Same issue here. Can confirm downgrade to 13.4.12 temp fix is working.

**Comment by alexcibotari** [comment]
I the app base even after downgrade to 13.3.0 it doesn't work

**Comment by samipshah100** [comment]
Same issue with pages router. but downgrade to 13.4.12 did not work.
