### ISSUE TITLE
env empty when using zod validation

### ISSUE THREAD

**Issue by JipSterk** [vercel/next.js#53896]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.6.11
    Relevant Packages:
      next: 13.4.14-canary.1
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: standalone
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/JipSterk/next-app-dir-no-env

### To Reproduce

- clone the repo
- install dependencies with pnpm i
- cp .env.example .env
- update .env with GITHUB_ID & GITHUB_SECRET from https://github.com/settings/apps
  - the homepage should be http://localhost:3000
  - the callback url should be http://localhost:3000/api/auth/callback/github
- run docker compose up
- go to localhost:3000 an error should occur stating that zod couldn't validate any of the variables as they are undefined?

### Describe the Bug

the env variables should be validated as being defined. 
a `console.log(process.env)` confirms that the variables are there but still the zod schema cannot validate them.
i've tried importing `require('dotenv/config')` in `next.config.js` but this doesn't help.
it might have something to do with rcs and handling variables prefixed with: NEXT_PUBLIC_ but that's just a guess

### Expected Behavior

no zod validation error and all the env variables being defined in both rsc and client components

### Which browser are you using? (if relevant)

Chromium Engine Version 115.0.5790.170

**Comment by schimi-dev** [comment]
Related to : https://github.com/vercel/next.js/issues/53579 and https://github.com/vercel/next.js/issues/53367
