### ISSUE TITLE
Can't initialize the project ( npx create-next-app@latest not working )

### ISSUE THREAD

**Issue by LukePenkava** [vercel/next.js#53900]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Same things I always do to start a new project:

npx create-next-app@latest .
( using Typescript )
npm run dev

Getting this error:

Error: Could not find the module "C:\Users\Workstation\Desktop\test\node_modules\next\dist\client\components\app-router.js#default" in the React Client Manifest. This is probably a bug in the React Server Components bundler.

Can't figure out what's the issue. Never had it before.
( Also happens with "next": "^13.4.14-canary.1" )
```

### Link to the code that reproduces this issue or a replay of the bug

agaga

### To Reproduce

npx create-next-app@latest .
npm run dev

### Describe the Bug

Basic standard initialization of a new project is not working

### Expected Behavior

Initialize a project

**Comment by balazsorban44** [comment]
Could you add a link to the code repo? :pray:
