### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by xiaoqufengdi** [vercel/next.js#53934]
### What is the improvement or update you wish to see?

'https://github.com/vercel/next-learn/tree/master/learn-starter', the page not found
![image](https://github.com/vercel/next.js/assets/31072438/3e25b309-6544-43d3-b1f2-5eeff1926266)

### Is there any context that might help us understand?

update the link

### Does the docs page already exist? Please link to it.

https://www.nextjs.cn/learn/basics/create-nextjs-app/setup

**Comment by balazsorban44** [comment]
nextjs.cn is not an official website, so you need to find the author and report the issue there. The correct link is https://github.com/vercel/next-learn/blob/master/basics/errors/install.md
