### ISSUE TITLE
Docs: XSS Issue in Metadata learn example

### ISSUE THREAD

**Issue by phiresky** [vercel/next.js#53961]
### What is the improvement or update you wish to see?

The JSON-LD metadata examples https://nextjs.org/learn/seo/rendering-and-ranking/metadata use dangerouslySetInnerHTML. That's required because within script tags browsers don't do normal html entity processing. But it also leads to an XSS issue if some of the data is user-generated.

Here's an example of the issue when a user would adapt that example:

```js
import Head from "next/head";

function ProductPage(props) {
  function addProductJsonLd() {
    return {
      __html: JSON.stringify({
        "@context": "https://schema.org/",
        "@type": "Product",
        name: props.title,
      }),
    };
  }
  return (
    <div>
      <Head>
        <title>{props.title}</title>
        <meta
          name="description"
          content="Super product with free shipping."
          key="desc"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={addProductJsonLd()}
          key="product-jsonld"
        />
      </Head>
      <h1>{props.title}</h1>
      <p>Super product for sale.</p>
    </div>
  );
}

export default ProductPage;
```

Seems innocuous. But if you now render
```jsx
<ProductPage title="hello </script><script>alert('hi');</script>" />
```

You'll get a injected script. Nextjs itself uses a copy-paste of the htmlescape library to prevent this issue for __NEXT_DATA__: https://github.com/vercel/next.js/blob/261db496f7cf04b70f078a6eae0c8baf6fe5c238/packages/next/src/server/htmlescape.ts

### Is there any context that might help us understand?

The example itself uses a literal string so it's not an issue, but it suggests this to be a good strategy in general. User generated data in the metadata can be very common.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/seo/rendering-and-ranking/metadata

**Comment by balazsorban44** [comment]
Thanks for pointing this out. Assumingly, this kind of metadata comes from a trusted CMS source, where any user input has been sanitized before storing, but will make this note to the team! We are actually rewriting the Learn section, so this is good feedback.

**Comment by phiresky** [comment]
Thanks.

> Assumingly, this kind of metadata comes from a trusted CMS source

In my case and I think many other cases, the sanitization happens due to the fact that during normal SSR or client-side-rendering, content is automatically and forcibly sanitized in JSX / during rendering. So this is kind of an escape hatch out of that.

This kind of metadata can very easily be a user-generated post title or comment or username or similar.
