### ISSUE TITLE
style register response duplicate styles with ant.design

### ISSUE THREAD

**Issue by yaxiaoliu** [vercel/next.js#53984]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.7
    Relevant Packages:
      next: 13.4.14-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

with-ant-design

### What browser are you using? (if relevant)

Chrome 115.0.0.0

### Describe the Bug

When I use `useServerInsertedHTML` in the project to extract the `css-in-js` content from `ant-design`, and access `localhost:3000`, I found that there are duplicate CSS content returned in the response. This leads to an increase in the size of the response content for HTTP requests.

duplicate in `<head>`
<img width="1183" alt="image" src="https://github.com/vercel/next.js/assets/37991688/b680220f-2539-4618-be56-f55ccce8f0d9">

duplicate after `</html>`
<img width="1176" alt="image" src="https://github.com/vercel/next.js/assets/37991688/c2bab229-8778-4e2c-ab58-535383f5b96c">

### Expected Behavior

It should not return duplicated content.

### To Reproduce

```bash
npx create-next-app@latest reproduction-app -e with-ant-design
cd reproduction-app
npm i
npm run dev
open http://localhost:3000/
```

**Comment by pkuphy** [comment]
See this: https://github.com/vercel/next.js/discussions/49354#discussioncomment-6279917

**Comment by yaxiaoliu** [comment]
It's now working, thank you
