### ISSUE TITLE
Debugging with non-localhost address stopped working

### ISSUE THREAD

**Issue by sydtv** [vercel/next.js#54010]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: arm64
      Version: #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.15
      eslint-config-next: 13.4.15
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

run "NODE_OPTIONS='--inspect=0.0.0.0:9229' next dev"

### To Reproduce

Create new nextjs project with 'npx create-next-app' and add the `NODE_OPTIONS='--inspect=0.0.0.0:9229'` option to the npm run dev command.

The process will abort and the following error message is displayed: `bin/node:  must be 0 or in range 1024 to 65535.`

### Describe the Bug

NextJS command `next dev` doesn't allow host and port option for `--inspect`. This behavior causes problems when debugging a project inside a docker container. It does work with `--inspect-brk`.

### Expected Behavior

NextJS command `next dev` considers host and port for `--inspect`.

### How are you deploying your application? (if relevant)

next dev

**Comment by sydtv** [comment]
I guess that the ip is not considered in this file:
https://github.com/Cow258/next.js/blob/canary/packages/next/src/server/lib/worker-utils.ts

**Comment by x-yuri** [comment]
Already opened in #53127.

> I guess that the ip is not considered in this file:

Nope, see the mentioned issue.
