### ISSUE TITLE
Dark/Light Mode Toggle Not Functioning @ `next.js.org/learn`

### ISSUE THREAD

**Issue by mogulcoder26** [vercel/next.js#54018]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x86_64
      Version: Ubuntu 22.04.2 LTS 
    Binaries:
      Node: 20.3.0
      npm: 9.6.7
      yarn:N/A
      pnpm: N/A
    Relevant Packages:
      N/A
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://nextjs.org/learn/foundations/about-nextjs?utm_source=next-site&utm_medium=homepage-cta&utm_campaign=home

### To Reproduce

[Link](https://nextjs.org/learn/foundations/about-nextjs?utm_source=next-site&utm_medium=homepage-cta&utm_campaign=home) to the part where the issue exists.

### Describe the Bug

I'm writing to report an issue I've encountered with the dark/light mode toggle on nextjs.org/learn.

While The toggle button to switch between dark and light modes is present on the Learn platform, but clicking it doesn't result in any change in the interface's appearance.

### Expected Behavior

Clicking the toggle button should switch the platform's mode between dark and light, providing a comfortable learning experience based on user preferences.

### Which browser are you using? (if relevant)

chrome

**Comment by balazsorban44** [comment]
Thank you! The learn section is not part of the same app as the docs, but is currently being rewritten with the App Router in mind, and will get a fresh coat of paint 💅
