### ISSUE TITLE
Supertest with jest gives error: "ReferenceError: Headers is not defined"

### ISSUE THREAD

**Issue by devLeopar** [vercel/next.js#54019]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Jest (next/jest)

### Link to the code that reproduces this issue or a replay of the bug

www.google.com

### To Reproduce

It happened when I upgraded next 12 to next 13.4.13. The API endpoints were being tested with the setup configuration below:

`tests/setup.ts`
```
import http from "http"

import supertest from "supertest"
import { apiResolver } from "next/dist/server/api-utils/node"

export const client = (handler) => {
  const requestHandle = (request, response) =>
    apiResolver(request, response, undefined, handler, {} as any, undefined)

  const server = http.createServer(requestHandle)
  return supertest(server)
}
```

`tests/userAuth.ts`

```
  it("should get access denied on reaching page", async (done) => {
    client(handlePageReach)
      .post("/api/reachPage")
      .set("Authorization", `Bearer ${token}`)
      .expect(403, done)
  })
```
Note: This `handlePageReach` uses middleware of `"next-connect": "^0.10.1"`

when I run `yarn test` as I did normally, it started showing error like below:
```
    ReferenceError: Headers is not defined

      at Object.<anonymous> (node_modules/next/src/server/web/spec-extension/adapters/headers.ts:28:37)
      at Object.<anonymous> (node_modules/next/dist/server/api-utils/index.js:67:18)
```

### Describe the Bug

Running jest tests for the purpose of testing API endpoints with `supertest` and `apiResolver`, nextjs 13.4 started giving unexpected error while previous version did not give any error

### Expected Behavior

This code should have ran and done the API testing as it did before

**Comment by balazsorban44** [comment]
> import { apiResolver } from "next/dist/server/api-utils/node"

This is importing Next.js internals which aren't guaranteed to be stable between releases.

Next.js ensures that `Headers` is correctly available in all supported Node.js versions, as you can see here https://github.com/vercel/next.js/blob/canary/packages/next/src/server/node-polyfill-fetch.ts


Closing as the provided code is not covered by sever and such should not be used. If you are still having issues, please open a new bug report with a reproduction. Thanks!
