### ISSUE TITLE
Parallel routing not working

### ISSUE THREAD

**Issue by ViNoS-ab** [vercel/next.js#54023]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:       
      next: 13.4.15
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

couldn't provide, but well described

### To Reproduce

file structure:
![image](https://github.com/vercel/next.js/assets/61888585/95e11d58-e28e-4832-b4cc-a835624f864f)

```tsx
// /cart/layout.tsx
"use client";

import { useSelectedLayoutSegment } from "next/navigation";

export default function Layout(props: {
  payement: React.ReactNode;
  children: React.ReactNode;
}) {
  const seg = useSelectedLayoutSegment();
  console.log(seg);

  return <div>{props.children}</div>;
}
```
```tsx
// cart/@payment/payment/page.tsx
export default function Page() {
  console.log("hellooo");

  return <div>hellooo</div>;
}
```

### Describe the Bug

when I navigate to `http://localhost:3000/cart/payment`
the  root layout is applied however it also shows a 404 error inside, and it keeps refreshing 
in the component layout when i console.log the segment it shows "__DEFAULT__" 
also the console.log in the `cart/@payment/payment/page.tsx` is logging `hellooo` 

### Expected Behavior

parallel routing where a route shows normally when i navigate to `http://localhost:3000/store/cart/payment`

### Which browser are you using? (if relevant)

Microsoft Edge Version 115.0.1901.203 (Official build) (64-bit)

### How are you deploying your application? (if relevant)

locally

**Comment by ragnaroks** [comment]
still 100% reproduces at Next.js 14.0.4

**Comment by Leafgard** [comment]
Hello !

I think I encountered the same issue, and I took the opportunity to [write the reproduction](https://github.com/Leafgard/54023-parallel-routing) myself.

Please correct me @ViNoS-ab or @ragnaroks if I am mistaken.

To give some further context, when running the reproduction, I would expect the following to happen:
- ✅  Path **/** => Shows "**Parallel / Home**"
- ❌  Path **/dashboard** => Shows "**Parallel / Dashboard**", which in our case, returns a **404**.

Looking forward to find out whether this is expected behavior or not.

Thanks for your work.

**Comment by ztanner** [comment]
> Hello !
> 
> I think I encountered the same issue, and I took the opportunity to [write the reproduction](https://github.com/Leafgard/54023-parallel-routing) myself.
> 
> Please correct me @ViNoS-ab or @ragnaroks if I am mistaken.
> 
> To give some further context, when running the reproduction, I would expect the following to happen:
> 
> * ✅  Path **/** => Shows "**Parallel / Home**"
> * ❌  Path **/dashboard** => Shows "**Parallel / Dashboard**", which in our case, returns a **404**.
> 
> Looking forward to find out whether this is expected behavior or not.
> 
> Thanks for your work.

`/dashboard` 404s because your `@parallel` slot does not `@parallel/dashboard/page.tsx` nor does it have a fallback `@parallel/default.tsx`. You can read more about this behavior here: https://nextjs.org/docs/app/api-reference/file-conventions/default
