### ISSUE TITLE
Usestate not getting updated on rerender

### ISSUE THREAD

**Issue by AugustinSorel** [vercel/next.js#54049]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC Mon J
    Binaries:
      Node: 16.20.2
      npm: 8.19.4
      Yarn: N/A
      pnpm: 8.3.1
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.4.9
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://youtu.be/Lg2nXkfloGE

code sandbox: https://codesandbox.io/p/sandbox/agitated-driscoll-x54jc7?file=%2Fapp%2FClient.tsx%3A1%2C1-3%2C14

### To Reproduce

here is my `src/app/dashboard/@allExercisesGrid/page.tsx`
```ts
const AllExercisesGrid = async () => {
  const exercises = await db.select().from(exercise);

  return <Client x={exercises} />;
};

export default AllExercisesGrid;
```

here is my `src/app/dashboard/@allExercisesGrid/Client.tsx`
```ts
"use client";

import { useState } from "react";

export const Client = ({ x }: { x: unknown[] }) => {
  const [gridItems] = useState(x);

  return (
    <p>
      GridItem: {gridItems.length} x: {x.length}
    </p>
  );
};
```

### Describe the Bug

After insterting elements one by one, the useState is not getting updated
Here is the output:

```txt
GridItem: 59 x: 59
GridItem: 59 x: 60
GridItem: 59 x: 61
GridItem: 59 x: 62
```

### Expected Behavior

```txt
GridItem: 59 x: 59
GridItem: 60 x: 60
GridItem: 61 x: 61
GridItem: 62 x: 62
```

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

vercel

**Comment by AugustinSorel** [comment]
here is a code sandbox: https://codesandbox.io/p/sandbox/agitated-driscoll-x54jc7?file=%2Fapp%2FClient.tsx%3A1%2C1-3%2C14

**Comment by balazsorban44** [comment]
This is expected and not related to Next.js. The initial state passed to a `useState` is not expected to change after the initial render. Read more in the React docs: https://react.dev/reference/react/useState#parameters

> This argument is ignored after the initial render.
