### ISSUE TITLE
Error resolving EcmaScript Modules request (icons from the library stopped working after the update)

### ISSUE THREAD

**Issue by MrOxMasTer** [vercel/next.js#54063]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.15
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.15", newest: "13.4.16".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Link to the code that reproduces this issue or a replay of the bug

/sdssdsdd

### To Reproduce

/ssssdssdsdsd

### Describe the Bug

I use the shadcn ui library. It in turn uses radix/ui and lucide-react. When connecting icons from lucide, I get an error after upgrading to version 13.4.15-13.4.16. Before that, there was version 13.4.11 and everything was fine and I wanted to update and I started getting an error when connecting icons from the lucide-react library
![image](https://github.com/vercel/next.js/assets/59291123/50585c5f-f5e2-4129-9aa8-b3c877470f85)
![image](https://github.com/vercel/next.js/assets/59291123/c1c92032-1a87-4b08-a091-463a0ae0383d)
![image](https://github.com/vercel/next.js/assets/59291123/cd9aff6f-3ab9-4f47-a69d-e49846888b23)
![image](https://github.com/vercel/next.js/assets/59291123/ad19fa35-0293-4280-9db0-9e4eeb0c2e45)
![image](https://github.com/vercel/next.js/assets/59291123/9afc65a6-5f09-4e88-93b4-71c0a60b0709)

### Expected Behavior

work

### Which browser are you using? (if relevant)

chrome

**Comment by MrOxMasTer** [comment]
13.4.13 also does not work on this version. Only on 13.4.12 and earlier

**Comment by MrOxMasTer** [comment]
https://github.com/lucide-icons/lucide/issues/1482

**Comment by rossanmol** [comment]
Still broken :/
