### ISSUE TITLE
nextjs-template template defines metadata object in layout.js instead of page.js

### ISSUE THREAD

**Issue by rnarkk** [vercel/next.js#54064]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
NA
```

### Which example does this report relate to?

nextjs-template.vercel.app

### Describe the Bug

This is quite a time-wasting starter experience.

### Expected Behavior

Put it in page.js.

### To Reproduce

NA

**Comment by balazsorban44** [comment]
Hi, we don't have an example called `nextjs-template` in https://github.com/vercel/next.js/blob/canary/examples, so closing this issue.

Note, as per the documentation, you can put metadata in a layout.js file too: https://nextjs.org/docs/app/building-your-application/optimizing/metadata
