### ISSUE TITLE
revalidatePath redirects to intercepting route

### ISSUE THREAD

**Issue by maxhannan** [vercel/next.js#54085]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 20.4.0
      npm: 9.7.2
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.12
      eslint-config-next: 13.4.12
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://app.replay.io/recording/create-next-app--71effefe-43de-463e-b54e-4c2e3d2fa540

### To Reproduce

Create a dynamic route which uses a server action to mutate data. Create a parallel, intercepting route which displays the same page in a modal and has the same ability to mutate data. When using a server action that revalidates path on the actual route, when the route is revalidated you will be redirected to intercepting route.   

### Describe the Bug

I have a route '/post/[id]' which also uses and intercepting parallel route to display the same page in a modal above the home page. On this page there is a like button which uses server actions to mutate the database which then calls revalidate route after the mutation is completed. On the intercepted route, this works without issue, however if I click the like button on the full route (not intercepted) when revalidatePath is called, the page redirects and the intercepting route modal is rendered over the full route (see recording). I am also using 'useOptimistic) but this bug occurs with or without the use of that hook. 

### Expected Behavior

revalidatePath does not redirect and show the intercepting route on top of the full route page. 

### Which browser are you using? (if relevant)

Chrome Version 115.0.5790.170 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

**Comment by eharvey328** [comment]
I'm having the same issue. This can also be observed during a hot reload of the [nextgram](https://github.com/vercel-labs/nextgram/tree/main) example app. 

@maxhannan have you found any workaround since opening this?

**Comment by crowmw** [comment]
Same problem for me. This is unfortunate because this is a common scenario where we have a form in a modal after which we close the modal, for example.

**Comment by chris-trait** [comment]
This is affecting me too in `14.0.1`.

Calling `revalidateTag` from inside a server action triggered by an intercepted route (either the original route, or the intercepted version), causes a page reload... the action never returns and the rest of my client function never runs.

**Comment by rperrote** [comment]
next.js 14.0.3 not fixed yet

**Comment by balazsorban44** [comment]
Hi, the provided reproduction is missing the source code, and nextgram does not use `revalidatePath` either. To investigate, we need the source code. Please open a new issue with a minimal reproduction, thanks! "same issue", "not fixed" comments are unfortunately unhelpful in the investigation. :pray:

**Comment by kahnclusions** [comment]
Hi @balazsorban44 I've opened a new issue with a reproduction using NextGram here: https://github.com/vercel/next.js/issues/59796
