### ISSUE TITLE
instrumentation.ts build fail when using "import type"

### ISSUE THREAD

**Issue by kin-for-test** [vercel/next.js#54089]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 20.5.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

TypeScript (plugin, built-in types)

### Link to the code that reproduces this issue or a replay of the bug

null

### To Reproduce

next dev

### Describe the Bug

instrumentation.ts
```
import { LogDB } from "LogDB";
export async function register() {
	await new LogDB().insert("startup");
}
```

LogDB.ts
```
import type Log from "./Log";
import { prisma } from "./PrismaClient";
export class LogDB implements Log{
	public async insert(log :string) {
		let result = await prisma.log.create({ data: log });
	}
}
```

Log.ts
`export type log={insert:(log:string)=>Promise<any>}`

when run next build , fail on the error 

- error ./LogDB.ts
Module parse failed: Unexpected token (1:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import type Log from "./Log";

### Expected Behavior

it should be run find

**Comment by balazsorban44** [comment]
Looks like your import is wrong.
Probably it should be:

```diff
// Log.ts
- export type log={insert:(log:string)=>Promise<any>}
+ export type Log={insert:(log:string)=>Promise<any>}

// LogDB.ts
- import type Log from "./Log";
+ import type { Log } from "./Log";
```

With these changes, I could not reproduce the issue. If you still have them, please open a new issue, and add a reproduction.
