### ISSUE TITLE
Change dynamic route decode from "%20" to hypen "-"

### ISSUE THREAD

**Issue by dwissaaj** [vercel/next.js#54096]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Webstorm 2023.1.3
Windows 10
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/dwissaaj/kisetsu.tech/blob/development/src/app/blog/%5Btitle%5D/page.tsx

### To Reproduce

Next starter project with prisma in route handler. So every time we handling the dynamic route like `/app/blog/[title]/page.tsx` it return url with `/blog/first20%blog20%write` means the decode url every space change to `20%` . The problem is it's also affecting `generateMetadata()` function. See image for detailed bug

![Metadata and Url weird result](https://github.com/vercel/next.js/assets/71976179/93d8e9d5-f5cc-48f5-8499-05cb8ee57d55)

### Describe the Bug

The dynamic route render url as default from
`/app/blog/[title]/page.tsx`
return 
`/blog/first20%blog20%write`

### Expected Behavior

Can we decode it to become
`/blog/first-blog-write`

**Comment by icyJoseph** [comment]
As said in the discussion:

```tsx
export async function generateMetadata({
  params: { title },
}: {
  params: { title: string };
}) {
  return {
    title: decodeURIComponent(title),
  };
}
```

And also decode it while rendering.

White spaces are reserved characters. When I go to `https://example.com/this is an example`, the browser encodes the spaces as `%20`, `https://example.com/this%20is%20an%20example`, which is out the framework immediate control.

One way would be to redirect from `%20` to `-` separated paths, but that's pretty much a user land implementation detail, not something the framework should do. At least, IMHO.

**Comment by dwissaaj** [comment]
Copy that solve the issue.
