### ISSUE TITLE
NextJS  v13.4.16 does not work in docker container

### ISSUE THREAD

**Issue by JurajKavka** [vercel/next.js#54093]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
 Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Fri, 11 Aug 2023 11:03:36 +0000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.16
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: standalone
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/blob/canary/examples/with-docker/README.md

### To Reproduce

- Follow the instructions here: https://github.com/vercel/next.js/blob/canary/examples/with-docker/README.md
- be sure you have Next v13.4.16

### Describe the Bug

Docker container with Next app starts but do not serve any content

### Expected Behavior

Docker container should start and serve application

### How are you deploying your application? (if relevant)

Google Clound

**Comment by DuCanhGH** [comment]
Can you try this instruction `ENV HOSTNAME 0.0.0.0`?

**Comment by MegaOleh2** [comment]
add [area: examples](https://github.com/vercel/next.js/labels/area%3A%20examples)

**Comment by MegaOleh2** [comment]
> Can you try changing `ENV HOSTNAME localhost` to `ENV HOSTNAME 0.0.0.0`, or `ENV HOSTNAME ::`? Next now listens on `localhost`, rather than `0.0.0.0`, when `HOSTNAME` is set to `localhost` :) Perhaps the Dockerfile should be updated.

This is work thanks

**Comment by michalvadak** [comment]
This is broken from 13.4.13

**Comment by michalvadak** [comment]
@timneutkens Wouldn't your fix fallback to Docker's default HOSTNAME env which is the ID of the container?

**Comment by DuCanhGH** [comment]
@timneutkens you may want to update other docker examples as well https://github.com/vercel/next.js/commit/0084166caaba402c1f8218da48e32855bc7ee48b :)

**Comment by nguaman** [comment]
Hello,
Just FYI.

If I remove 'ENV HOSTNAME 0.0.0.0', it doesn't work on Google Cloud Run.

**Comment by DuCanhGH** [comment]
@nguaman sounds like Google Cloud Run doesn't provide HOSTNAME, perhaps a note with a commented out `ENV HOSTNAME 0.0.0.0` should be added :)

**Comment by mhm13dev** [comment]
When I try to deploy my code in a docker container with standalone mode using `13.3.4`, the code is built and runs successfully.

But now I upgraded to `13.4.19` and the code is built successfully but I get this error when the container is started.

![image](https://github.com/vercel/next.js/assets/28213822/2bbce8f5-72c4-44c3-b338-11d01fd7ea35)

**Comment by mhm13dev** [comment]
@DuCanhGH 
When I try to deploy my code in a docker container with standalone mode using `13.3.4`, the code is built and runs successfully.

But now I upgraded to `13.4.19` and the code is built successfully but I get this error when the container is started.

I am deploying it on AWS ECS

![image](https://github.com/vercel/next.js/assets/28213822/2bbce8f5-72c4-44c3-b338-11d01fd7ea35)

**Comment by DuCanhGH** [comment]
@mhm13dev that doesn't even look like a proper hostname 💀 Can you try `ENV HOSTNAME 0.0.0.0`?

**Comment by mhm13dev** [comment]
I tried these 3 values: 0.0.0.0, localhost, :: 

None of them worked.

**Comment by mhm13dev** [comment]
I think this hostname is given by AWS ECS

**Comment by DuCanhGH** [comment]
@mhm13dev if 0.0.0.0 doesn't work then I don't really know either :( I have no experience with AWS ECS as well, so I can't tell why the hostname looks like that. Doesn't look like my PR is related as it just fixes issues with IPv6, whereas this hostname most likely isn't one.

**Comment by mhm13dev** [comment]
@DuCanhGH sure thank you.
