### ISSUE TITLE
Since Next.js 13.4.13, custom headers no longer can be set in middleware (works fine with 13.4.12)

### ISSUE THREAD

**Issue by bfovez** [vercel/next.js#54094]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.15.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:       
      next: 13.4.14-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/with-next-13-4-13-7zh3kl

### To Reproduce

Juste compare the two barebone examples (identical except for the Next.js version).

With Next.js 13.4.12: [https://codesandbox.io/p/sandbox/with-next-13-4-12-lm62df](https://codesandbox.io/p/sandbox/with-next-13-4-12-lm62df)
It works perfectly fine. The custom header is properly set in `middleware.ts`. The server console confirms and the page shows the correct header.

With Next.js 13.4.13:  [https://codesandbox.io/p/sandbox/with-next-13-4-13-7zh3kl](https://codesandbox.io/p/sandbox/with-next-13-4-13-7zh3kl)
The exact same code does not work anymore. The header is not set, as the server console and the page show.

### Describe the Bug

The code `middleware.ts` is straightforward:

```
export function middleware(request: NextRequest) {
  const newHeaders = new Headers(request.headers);
  newHeaders.set("x-header", "Some random header");
  const newRequest = new NextRequest(request, { headers: newHeaders });
  console.log(
    "Retrieved x-header:",
    newRequest.headers.get("x-header")
  );
  return NextResponse.next(newRequest);
}
```

With Next.js **13.4.12**, the console shows `Retrieved x-header: Some random header`, as expected.
With Next.js **13.4.13**, the console shows `Retrieved x-header: null`.

### Expected Behavior

With Next.js **13.4.13**, the console should show `Retrieved x-header: Some random header`, as it shows with Next.js **13.4.12**.

### Which browser are you using? (if relevant)

115.0.5790.171

### How are you deploying your application? (if relevant)

Vercel

<sub>[NEXT-1521](https://linear.app/vercel/issue/NEXT-1521/since-nextjs-13413-custom-headers-no-longer-can-be-set-in-middleware)</sub>

**Comment by mattiaz9** [comment]
for me it works if done like this:
```ts
const headers = new Headers(request.headers)
headers.set("x-authed", isSignedIn.toString())

return NextResponse.next({
  request: {
    headers,
  },
})
```

**Comment by bfovez** [comment]
Thank you Mattia.
But as I use a chain of middlewares, I do need to construct a new request.
(I use NextMiddleware as a 'next' function).
So, still a regression to me, as your workaround is not applicable to my
use case.

**Comment by bfovez** [comment]
Thank you [balazsorban44](https://github.com/balazsorban44).
