### ISSUE TITLE
Fast Refresh indicator is not rendered on 

### ISSUE THREAD

**Issue by olafur164** [vercel/next.js#54100]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.14.2
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.16-canary.1
      eslint-config-next: 13.4.16
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/tree/canary/examples/reproduction-template

### To Reproduce

I expect that any template should suffice so I just linked to the reproduction template. What I did was I created a project from scratch and tried saving a file in pages router and a file in app router. Then I checked the inspect elements to see if there was a mismatch. The div with id __next-build-watcher is rendered on pages router but not in app router and that div is was renders the hot reload / fast refresh indicator.

Inspect Page in Pages router
<img width="1268" alt="image" src="https://github.com/vercel/next.js/assets/8494320/7c620c7b-a1c9-49b0-93f6-9929b064a434">

Inspect Page in App router
<img width="742" alt="image" src="https://github.com/vercel/next.js/assets/8494320/d1129c52-f733-420e-bc12-4020414aa2c1">

### Describe the Bug

The hot reload / fast refresh indicator that happens when you save a file in dev is not rendered in App router but is rendered in Pages.

### Expected Behavior

I would expect that this indicator should also be rendered in App router.

**Comment by balazsorban44** [comment]
Thanks, this is currently expected as the indicator is not yet implemented for the App Router: https://github.com/vercel/next.js/blob/canary/packages/next/src/client/app-next-dev.ts/#L11
