### ISSUE TITLE
`eslint` is not installed as a dev dependency

### ISSUE THREAD

**Issue by imageck** [vercel/next.js#54105]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023
    Binaries:
      Node: 18.17.1
      npm: 
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.16
      eslint-config-next: 13.4.16
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/vercel/tree/main/examples/nextjs

### To Reproduce

1. `npx create-next-app@latest my-app --ts --no-tailwind --eslint --app --no-src-dir --import-alias "@/*" --use-npm`
2. `cd my-app && node -e 'console.log(JSON.parse(fs.readFileSync("package.json")).devDependencies)'`

### Describe the Bug

The [documentation](https://nextjs.org/docs/pages/building-your-application/configuring/eslint) states:

> If either of the two configuration options are selected, Next.js will automatically install `eslint` and `eslint-config-next` as development dependencies in your application and create an `.eslintrc.json` file in the root of your project that includes your selected configuration.

however both packages are installed as direct dependencies. The ESLint documentation also instructs installing it as a dev dependency.

Either the documentation is wrong or both package should really be installed as development dependencies.

### Expected Behavior

During installation of ESLint, it is saved as a dev dependency.

<sub>[NEXT-1520](https://linear.app/vercel/issue/NEXT-1520/eslint-is-not-installed-as-a-dev-dependency)</sub>

**Comment by ijjk** [comment]
Hi, this is expected per https://github.com/vercel/next.js/pull/48076#pullrequestreview-1376312311 it does seem we should update those docs though!
