### ISSUE TITLE
Extra fields attached to request no longer readable in API handler

### ISSUE THREAD

**Issue by alex-statsig** [vercel/next.js#54129]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.17.1
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.32.4
    Relevant Packages:
      next: 13.4.16
      eslint-config-next: N/A
      react: 18.1.0
      react-dom: 18.1.0
      typescript: 4.8.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

n/a

### To Reproduce

1. Create a custom server which wraps all route handling.
2. Before calling `app.getRequestHandler()(req,res,url)`, attach some data to req (for example, some authentication result). i.e. `req.myTestField = 1`
3. Inside the API route handler, log `req.myTestField`, and observe its not present

### Describe the Bug

Data set on the request object with a custom server is no longer preserved when API routes receive the request.

### Expected Behavior

As was the case in previous versions of next.js (last confirmed 13.4.8), any extra fields set on request should be carried over into API routes.

**Comment by itrelease** [comment]
@balazsorban44 https://github.com/vercel/next.js/issues/53883 https://github.com/vercel/next.js/issues/54288

**Comment by balazsorban44** [comment]
Closing in favor of #54440. Feel free to comment there!
