### ISSUE TITLE
Chunks files not found after upgraded to 13.4.1x

### ISSUE THREAD

**Issue by hungcrush** [vercel/next.js#54120]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.16
      eslint-config-next: 13.4.16
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

None

### To Reproduce

git pull
yarn build

pm2 stop vf
pm2 delete vf

![image](https://github.com/vercel/next.js/assets/8098916/70e4ebeb-e12b-492b-a9f2-0ecd5b0d34e6)

### Describe the Bug

My chunks files in static/chunks/app/[locale]/.... not found ( I checked the file on server and they're exist. other files normal

ex: 
/_next/static/chunks/app/%5Blocale%5D/layout-38b8ac0a0766c23e.js

![image](https://github.com/vercel/next.js/assets/8098916/22ebb6c6-7d76-4fce-b784-766d04fac16c)

### Expected Behavior

None

**Comment by controversial** [comment]
You didn’t provide any code for a reproduction, but try stopping your server, removing the `.next` folder, and then running `next build && next start` (or `next dev`) from there.

**Comment by hykelvinlee42** [comment]
I've been experiencing the same issue when deploying the project in a Nginx server (docker container).

**Comment by aXenDeveloper** [comment]
Yes, the same for me in docker container.

**Comment by hungcrush** [comment]
> You didn’t provide any code for a reproduction, but try stopping your server, removing the `.next` folder, and then running `next build && next start` (or `next dev`) from there.

I tried it. But it same :( 
It only happens on [locale] folder: app/[locale]/....

Do you have any ideas for it?

**Comment by hykelvinlee42** [comment]
Issue #54008 described the same and provided a reproducible example.

**Comment by Baukaalm** [comment]
I have the same issue, described it here https://github.com/vercel/next.js/issues/54133#issuecomment-1683366199.

**Comment by Baukaalm** [comment]
Can you show links or router.push configs with that paths?

**Comment by hungcrush** [comment]
> Can you show links or router.push configs with that paths? Maybe you send asPath incorrect

No this is static files. they're in .next folder

**Comment by bryceAebi** [comment]
I'm experiencing a similar issue, though it only manifests when I test my site via Google Search Console.

Do folks know which version I can downgrade to to solve this error? Is it 13.4.9?

**Comment by hungcrush** [comment]
> I'm experiencing a similar issue, though it only manifests when I test my site via Google Search Console.
> 
> Do folks know which version I can downgrade to to solve this error? Is it 13.4.9?

Yes. After I downgrade to 13.4.9 it works well...

**Comment by bryceAebi** [comment]
Hm, for what it's worth I still get the missing chunk issue on Google Search Console at 13.4.9

**Comment by bryceAebi** [comment]
Perhaps my issue is not the same. My only affected routes are the dynamic routes and the error looks the same, but the chunks that are sometimes missing are not those from the `[slug]` directory

**Comment by MarceloBD** [comment]
Same problem here with next 13.4.19, chunks are created but they are not found

**Comment by Refrezsh** [comment]
Same problem, all works fine on Next 13.4.12.

**Comment by shehi** [comment]
This is the same as #54008 .

**Comment by picspirit** [comment]
I've been experiencing the same issue. Debian, Nginx, PM2. 
If visite the app by http://ip:3000, there would be no problem. 
But if I visit the domain, got the same issure.

**Comment by hungcrush** [comment]
It's fixed by remove slash '/' end of link on nginx config. 
Thank you.

**Comment by MarceloBD** [comment]
But this is still a bug in nextjs as I am having this on Windows and not running nginx

**Comment by shehi** [comment]
Being on IIS doesn't mean it doesn't have similar rewrite mechanism like
Nginx does when URLs are terminated with a slash. I think this behaviour
actually to be a standard behaviour, because several frameworks also behave
this way. Have you checked your IIS vhost configuration?

**Comment by MarceloBD** [comment]
You mean on my machine? I am running on localhost

**Comment by alexrabin** [comment]
This should still be open. 13.5.1 still has this issue
