### ISSUE TITLE
Docs: Server actions enhancement with progressive enhancements 

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#54135]
### What is the improvement or update you wish to see?

Some recommended patterns do not work well with progressive enhancement, and they make it seems like using client features disable the usage of forms without JS enabled, while it does not and there is a simple trick to achieve that.
 
Especially these 2 examples : 

1. https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#enhancements
2. https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#progressive-enhancement

### 1st example : with useOptimistic 
```tsx
'use client'
 
import { experimental_useOptimistic as useOptimistic, useRef } from 'react'
import { send } from './actions.js'
 
export function Thread({ messages }) {
  const [optimisticMessages, addOptimisticMessage] = useOptimistic(
    messages,
    (state, newMessage) => [...state, { message: newMessage, sending: true }]
  )
  const formRef = useRef()
 
  return (
    <div>
      {optimisticMessages.map((m) => (
        <div>
          {m.message}
          {m.sending ? 'Sending...' : ''}
        </div>
      ))}
      <form
        action={async (formData) => {
          const message = formData.get('message')
          formRef.current.reset()
          addOptimisticMessage(message)
          await send(message)
        }}
        ref={formRef}
      >
        <input type="text" name="message" />
      </form>
    </div>
  )
}
```

In this example, using action directly makes the action a client action, which do not work without JS enabled, instead, we could use the `onSubmit` prop to do our logic and still pass the action to the form.  The advantage here is that `onSubmit` runs before the action and stopping the event propagation there means stopping the action from automatically running. And Since onSubmit requires JS, when it is not enabled, the form will back to the default behavior with `action`.

The better code would be : 

```tsx
'use client'
 
import { experimental_useOptimistic as useOptimistic } from 'react'
import { send } from './actions.js'
 
export function Thread({ messages }) {
  const [optimisticMessages, addOptimisticMessage] = useOptimistic(
    messages,
    (state, newMessage) => [...state, { message: newMessage, sending: true }]
  )
 
  return (
    <div>
      {optimisticMessages.map((m) => (
        <div>
          {m.message}
          {m.sending ? 'Sending...' : ''}
        </div>
      ))}
      <form
        action={send}
        onSubmit={async (e) => { 
          // prevent the execution of the `send` action
          e.preventDefault();
          
          // automatically typed as a HTMLFormElement
          const form = e.currentTarget; 
          const formData = new FormData(form);
          
          form.current.reset()
          addOptimisticMessage(message)
          await send(formData)
        }}
      >
        <input type="text" name="message" />
      </form>
    </div>
  )
}
```

This would mean that we would have to change our `send` action to take a `FormData` instead of a string, but that doesn't change much. 

```ts
"use server"
import { db } from '~/lib/db';
import { revalidatePath } from 'next/cache';

// Instead of this
export async function send(message: string) {
   await db.insertInto(`messages`).values({ message });
  revalidatePath(`/chat-screen`);
}


// Do this
export async function send(formData: FormData) {
   const message = formData.get(`message`)!.toString();
   await db.insertInto(`messages`).values({ message });
   revalidatePath(`/chat-screen`);
}

``` 

<hr />

```tsx
'use client'
 
import { useState } from 'react'
import { handleSubmit } from './actions.js'
 
export default function ExampleClientComponent({ myAction }) {
  const [input, setInput] = useState()
 
  return (
    <form action={handleSubmit} onChange={(e) => setInput(e.target.value)}>
      {/* ... */}
    </form>
  )
}
```

This example is just plain wrong, adding an `onChange` prop to the form will listen for when every input of the form changes, but not when the form is submitted, and `myAction` is not even used... overall i don't understand the purpose of this example.

### Is there any context that might help us understand?

I don't know what to say here, so no

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#progressive-enhancement

**Comment by leerob** [comment]
https://github.com/vercel/next.js/pull/54139#issuecomment-1686582834
