### ISSUE TITLE
Docs: router events for app dir

### ISSUE THREAD

**Issue by MateoKappa** [vercel/next.js#54145]
### What is the improvement or update you wish to see?

Im creating a "you have unsaved changes are you sure you want to leave" event in my app , but i find it really difficult to detect if the route is changing before changing routes and also stop it , with app dir layout .

### Is there any context that might help us understand?

So im trying to create a "you have unsaved changes are you sure you want to leave" event in my app , im using next js 13 app dir layout and since react events are not available at this , i cannot find an alternative does someone has a suggestion ? Also beforeunload event doesnt work , it only works when im about to close the page complitely but not when im changing routes in my web app 

<sub>[DX-1927](https://linear.app/vercel/issue/DX-1927/docs-router-events-for-app-dir)</sub>

**Comment by ethyaan** [comment]
Hey, 
hope you are doing great.
So it becomes a blocker here in my case as well,
I want to run few animation at the moment route change start.
I'm using the App directory and `router` from `next/router` is not available for us to listen to the events.
so any Suggestion?
do we even have such thing in app directory to control and capture event before the route change happens?
I don't wan't to listen to pathname or params because they will change when everything is lost.
Any Idea?

**Comment by ethyaan** [comment]
@ijjk , can you please help in this?

**Comment by luckyship** [comment]
i also have the same issue, is there any method to solve this?

**Comment by leerob** [comment]
Hey there, currently this is the route eventsr we have documented for the App Router: https://nextjs.org/docs/app/api-reference/functions/use-router#router-events

Rather than a docs change, this is a feature request for the App Router itself, so I'll note that down 👍

**Comment by ethyaan** [comment]
@leerob  Thank you for replying,
So how we can help in this feature request and how we can track it?
I appreciate if give some more information on this.

**Comment by Israeltheminer** [comment]
@MateoKappa The closest thing I found to make this work was to add this ` return (e.returnValue = '');`, but this method is tagged as deprecated [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue), also having your issue on my current project btw.
