### ISSUE TITLE
`redirect()` function doesn't consider basePath

### ISSUE THREAD

**Issue by XDean** [vercel/next.js#54163]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 16.15.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.17-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/XDean/next-bug/tree/redirect-function-basepath

### To Reproduce

- Goto `/dev/redirect`
- It redirect to `/target`. The correct path should be `/dev/target`

### Describe the Bug

The `redirect` function should consider `basePath` config. But it not.

Another strange behavior is, If you access `/dev/link` , click the link redirect to `/direct`, it works.

### Expected Behavior

`redirect('/target)` can goto `/dev/target`

<sub>[NEXT-1529](https://linear.app/vercel/issue/NEXT-1529/redirect-function-doesnt-consider-basepath)</sub>

**Comment by kmvan** [comment]
I don't think this is a bug.

**Comment by XDean** [comment]
> I don't think this is a bug.

Please give some reason.

Someone may say 'this is by design', I prepared another testcase.

- goto `/dev/link`
- clik the `link redirect to /direct`, it works
- right click the `link redirect to /direct`, open in new tab, it fails.

The behavior is not consistent.

**Comment by timneutkens** [comment]
This is definitely a bug 👍

**Comment by kmvan** [comment]
@XDean You are right.
