### ISSUE TITLE
App Router crashes when navigating back into the application using browser buttons

### ISSUE THREAD

**Issue by icyJoseph** [vercel/next.js#54184]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
npx next info

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.7.1
      Yarn: 1.22.19
      pnpm: 7.22.0
    Relevant Packages:
      next: 13.4.17
      eslint-config-next: 13.4.17
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.6.2
    Next.js Config:
      output: N/A

```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app example-app

### To Reproduce

In **any** App router app (just run `npx create-next-app example-app`), do:

1. run npm run build && npm run start,
2. when it runs open a new tab in your browser,
3. type localhost:3000
4. App loads normally
5. Browse back with the back button
6. Browse forward with the forward button
7. App crashes

### Describe the Bug

Thanks to https://github.com/vercel/next.js/discussions/54180, which outlines that the crash is originating on accessing `tree[1]` without checking for undefined.

 The error first appears on the major release: **13.4.17** and it is still present in canary.

I do believe, even the next.js docs page are suffering this issue.

https://github.com/vercel/next.js/assets/21013447/84112bd0-ba1b-4889-a08c-1a76df2f84d2

The video shows that navigating back to next.js docs crashes, and forward to the toy app, crashes too.

### Expected Behavior

The page should not crash when navigating back into it, using browser controls.

<sub>[NEXT-1528](https://linear.app/vercel/issue/NEXT-1528/app-router-crashes-when-navigating-back-into-the-application-using)</sub>

**Comment by icyJoseph** [comment]
It seems that the issue has been introduced between: 13.4.16 to 13.4.17-canary.0 https://github.com/vercel/next.js/compare/v13.4.16...v13.4.17-canary.0 - because installing 13.4.16 works fine, but the next canary breaks.

**Comment by MKraust** [comment]
Might be related to https://github.com/vercel/next.js/pull/54081

**Comment by icyJoseph** [comment]
Yeah, 0b3e366f3212dcf7d35ed86da60a8422e1a4836a seems to have introduced the issue.

- I made a `npx create-next-app example-app`,
- checked out 86d2ead1fe612432f7aee73f295a3753bd421ebe and `pnpm install && pnpm dev` on the next.js repo
-  `pnpm add ./path/to/next.js/{packages/next,node_modules/{react,react-dom}}` 
- build and start example app, no problem
- checkout 0b3e366f3212dcf7d35ed86da60a8422e1a4836a and `pnpm install && pnpm dev`
- build and start example app, issue appears

Could someone double check this?
