### ISSUE TITLE
Docs: Darkmode theme changer not working on tutorials section

### ISSUE THREAD

**Issue by thefonso** [vercel/next.js#54181]
### What is the improvement or update you wish to see?

On this page...https://nextjs.org/learn/basics/navigate-between-pages

Theme (darkmode) changer buttons at bottom of page do not function.

### Is there any context that might help us understand?

On this page...https://nextjs.org/learn/basics/navigate-between-pages

Theme (darkmode) changer buttons at bottom of page do not function.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/navigate-between-pages

**Comment by leerob** [comment]
Hey! We're working on this, it will be fixed in the coming months when we release an updated version of the course 🙏
