### ISSUE TITLE
Next.js 13.4.9 - SWC minification breaks production builds

### ISSUE THREAD

**Issue by jantimon** [vercel/next.js#54192]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.11
    Relevant Packages:
      next: 13.4.17
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

SWC minifier (swcMinify: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/jantimon/next-swc-minification-reproduction/

### To Reproduce

1. clone the reproduction example
```bash
git clone https://github.com/jantimon/next-swc-minification-reproduction.git
npm i
```
2.  As the SWC minifier runs only during build you have to create a build:
```bash
npm run build
npm run start
```
3. Open http://localhost:3000/
4. enter anything into the input field
5. click the button to cause a rerender
6. react will unmount the input field and mount it again
7. the input is empty

![shot-BDOkhzCn](https://github.com/vercel/next.js/assets/4113649/d0936d73-cca9-4633-b3d0-56c48f9a294f)

### Describe the Bug

The bug was introduced in `next@13.4.9-canary.2` - all early versions (e.g. `next@13.4.9-canary.1`) work fine.

The issue seems to be part of this change: https://github.com/vercel/next.js/compare/v13.4.9-canary.1...v13.4.9-canary.2

ContextExample.tsx

```tsx
import { ReactNode, createContext } from "react";

const Context = createContext({});

export const ContextProvider = ({ children }: { children: ReactNode}) => {
    return <Context.Provider value={{}}>{children}</Context.Provider>;
}

export const ContextDemo = {
    Provider: ContextProvider
}
```

Client Component.tsx

```tsx
"use client";
import { useState } from "react";
import { ContextDemo } from "./ContextExample";

export const ClientCompoenent = () => {
  const [count, setCount] = useState(0);

  return (
    <>

      <ContextDemo.Provider>
        <input />
      </ContextDemo.Provider>

      <button
        onClick={() => {
          console.log("click");
          setCount(count + 1);
        }}
      >
        +1 (rerender)
      </button>
    </>
  );
};
```

During minifcation SWC will inline the `ContextProvider` component right into the render function:

```js
"use strict";
      n.r(r),
        n.d(r, {
          ClientCompoenent: function () {
            return u;
          },
        });
      var t = n(7437),
        o = n(2265);
      let s = (0, o.createContext)({}),
        u = () => {
          let [e, r] = (0, o.useState)(0);
          return (0, t.jsxs)(t.Fragment, {
            children: [
              (0, t.jsx)(
                // 🐞 here is the inlined function (scoped to `u`)
                //  therefore the function will recreated for each render: 
                (e) => {    
                  let { children: r } = e;
                  return (0, t.jsx)(s.Provider, { value: {}, children: r });
                },
                { children: (0, t.jsx)("input", {}) }
              ),
              (0, t.jsx)("button", {
                onClick: () => {
                  console.log("click"), r(e + 1);
                },
                children: "+1 (rerender)",
              }),
            ],
          });
        };
```

It looks like SWC does this minification only if a dot is in the component name.
changing `ContextDemo.Provider` to `ContextDemoProvider` fixes the issue.

### Expected Behavior

Running `npm dev` will not trigger the swc minifcation and runs properly.

A rerender will not unmount components and the input will keep its value:

![shot-VoV9ZKkO](https://github.com/vercel/next.js/assets/4113649/96daad44-780e-407d-9362-689f1fff8aca)

<sub>[NEXT-1530](https://linear.app/vercel/issue/NEXT-1530/nextjs-1349-swc-minification-breaks-production-builds)</sub>

**Comment by jantimon** [comment]
Update:

@kdy1 - it looks like the problem is **not** with SWC.

This is the generated code with `next@13.4.9-canary.1`:

```js
    7228: function (e, r, n) {
      "use strict";
      n.r(r),
        n.d(r, {
          ClientCompoenent: function () {
            return u;
          },
        });
      var t = n(9268),
        o = n(6006);
      let s = (0, o.createContext)({}),
        u = () => {
          let [e, r] = (0, o.useState)(0);
          return (0, t.jsxs)(t.Fragment, {
            children: [
              (0, t.jsx)(
                (e) => {
                  let { children: r } = e;
                  return (0, t.jsx)(s.Provider, { value: {}, children: r });
                },
                { children: (0, t.jsx)("input", {}) }
              ),
              (0, t.jsx)("button", {
                onClick: () => {
                  console.log("click"), r(e + 1);
                },
                children: "+1 (rerender)",
              }),
            ],
          });
        };
    },
```

and this is the broken code with `next@13.4.9-canary.2`:

```js
    7365: function (e, r, n) {
      "use strict";
      n.r(r),
        n.d(r, {
          ClientCompoenent: function () {
            return u;
          },
        });
      var t = n(9268),
        o = n(6006);
      let s = (0, o.createContext)({}),
        u = () => {
          let [e, r] = (0, o.useState)(0);
          return (0, t.jsxs)(t.Fragment, {
            children: [
              (0, t.jsx)(
                (e) => {
                  let { children: r } = e;
                  return (0, t.jsx)(s.Provider, { value: {}, children: r });
                },
                { children: (0, t.jsx)("input", {}) }
              ),
              (0, t.jsx)("button", {
                onClick: () => {
                  console.log("click"), r(e + 1);
                },
                children: "+1 (rerender)",
              }),
            ],
          });
        };
    },
```

as you can see (beside the module id) the code is exactly the same as before..

I can only guess but it might be because of the react upgrade from `"react-builtin": "npm:react@18.3.0-canary-1cea38448-20230530"` to `"react-builtin": "npm:react@18.3.0-canary-1fdacbefd-20230630"`.

**Comment by jantimon** [comment]
@jaggli has just created a new react issue: https://github.com/facebook/react/issues/27248

**Comment by jaggli** [comment]
I boiled down the problem to the following two statements, which are the equivalent of the code being generated through SWC, under certain conditions like shown above.

1. Create a dynamically created component with createElement like so:
   ```javascript
   const DynamicComponent = createElement(() => createElement(Demo));
   ```
2. Use `<DynamicComponent />` as children
   ```javascript
   return createElement("button", null, DynamicComponent);
   ``` 
 
 I'm not sure what de documentation is referring to, when they say
 
 > "You must treat React elements and their props as [immutable](https://en.wikipedia.org/wiki/Immutable_object) and never change their contents after creation."

https://react.dev/reference/react/createElement

So in case this sentence says: "You can't dynamically nest `createElement()`" then it is a SWC bug. If it does not mean that, then it's probably a React bug..
