### ISSUE TITLE
Stale fetch responses are never served

### ISSUE THREAD

**Issue by siffogh** [vercel/next.js#54193]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 8.6.10
    Relevant Packages:
      next: 13.4.17
      eslint-config-next: 13.4.17
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/siffogh/next-caching-issue/blob/main/src/app/page.tsx

### To Reproduce

In `app/page.tsx`, try the following code. This code calls a mock API that serves a response after 5 seconds.

```tsx
export const runtime = 'edge';

export default async function Home() {
  const data = await fetch('https://hub.dummyapis.com/delay?seconds=5', {
    cache: 'force-cache',
    next: { revalidate: 1 },
  });

  return (
    <code>
      <pre>{JSON.stringify(await data.text(), null, 2)}</pre>
    </code>
  );
}
```

### Describe the Bug

Every single request takes at least 5 seconds.

### Expected Behavior
It's expected for the data to be considered stale after 1 second, but then the stale version should be served while the fresh data is fetched in the background.
Requests after the first should be immediate since the response should be cached.
Is this expected? If so, is there anything we can do to be able to cache such requests? The cookie value is not even used.
I tried `export const fetchCache = "force-cache";` but it leads to the same result.

### How are you deploying your application? (if relevant)

Vercel

**Comment by davecarlson** [comment]
You have set revalidate to 1. So after 1 second, the cache is now classed as stale.

**Comment by siffogh** [comment]
> You have set revalidate to 1. So after 1 second, the cache is now classed as stale.

@davecarlson That I understand, but it should serve the stale version and fetch the fresh one in the background to update the cache, no?

**Comment by focux** [comment]
I'm experiencing this same issue, did you find anything related to this? I expect the old cached results to be served while it revalidates in the background.
