### ISSUE TITLE
Docs: Pages router features in App router docs for Deployment

### ISSUE THREAD

**Issue by jessicarush** [vercel/next.js#54200]
### What is the improvement or update you wish to see?

I would like to see App Router information (instead of Pages Router) in the [Next.js Build API](https://nextjs.org/docs/app/building-your-application/deploying#nextjs-build-api) section of [Deploying](https://nextjs.org/docs/app/building-your-application/deploying) in the [App Router docs](https://nextjs.org/docs/app/building-your-application). 

### Is there any context that might help us understand?

Some of the information in the [Next.js Build API](https://nextjs.org/docs/app/building-your-application/deploying#nextjs-build-api) section is specific to Pages Router not App Router. This is confusing to those of us learning Next.js App Router for the first time. For example:

> - HTML files for pages using getStaticProps or [Automatic Static Optimization](https://nextjs.org/docs/pages/building-your-application/rendering/automatic-static-optimization)

And where "This output is generated inside the .next folder:", there is no mention of `.next/server/app`.

As I am still learning, I'm not sure if there is any other information on this page that is specific to Pages Router and not App Router.

EDIT: In the section [Manual Graceful Shutdowns](https://nextjs.org/docs/app/building-your-application/deploying#manual-graceful-shutdowns) it describes how to register a handler for a signal in `pages/_document.js`. Need clarification on where to do this in App Router. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/deploying

**Comment by leerob** [comment]
The deployment documentation has been updated since this was posted, we've made some larger changes here!
