### ISSUE TITLE
Hot-reload doesn't work with versions above 13.4.7

### ISSUE THREAD

**Issue by TotomInc** [vercel/next.js#54208]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.5.1 & 18.17.1 & 18.14.0
      npm: 9.8.1
      Yarn: 1.22.19
    Relevant Packages:
      next: 13.4.19-canary.0
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/TotomInc/nextjs-recompilation-issue

The repo is a fresh `npx create-next-app@latest`, nothing more.

### To Reproduce

I've created a fresh app by following the documentation: `npx create-next-app@latest`

- Added TypeScript + TailwindCSS + ESLint
- Added custom paths alias @/*

If I downgrade the version of Next.js to `13.4.7`, recompilation now works as intended.

If someone has an idea or a direction, I'll take it to help debug this issue. I don't remember doing custom configuration on my environment, as I try to avoid custom configs.

I tried to add a `.babelrc` just in case, but it doesn't work:

```json
{
  "presets": ["next/babel"],
  "plugins": []
}
```

However, I noticed that using `next dev --turbo` makes the Hot Reload work.

### Describe the Bug

Re-compilation doesn't trigger after the initial compilation of a page (pages router, app dir) or an API route.

To re-compile, I need to restart the development server.

https://github.com/vercel/next.js/assets/9285210/c0f052dd-ccb5-4ac4-ad57-ea4b795a3d79

### Expected Behavior

Re-compilation should work as expected, without restarting the Next.js dev-server.

**Comment by TotomInc** [comment]
Thanks @leerob, I've updated the issue. It looks like this is reproducible on my environment with a fresh `npx create-next-app@latest`, so it doesn't appear to be related to my project.

I've noticed that downgrading the freshly created next-app to Next.js `13.4.7` does resolve the issue. However, I don't want to stay stuck on an old version of Next.js

If you have any pointers on what could be related to my local environment, I'll try it.

**Comment by TotomInc** [comment]
I've had a lot of stuff inside my `/etc/hosts`, when I removed the following lines:
```
# Custom localhost resolver.
127.0.0.1 localhost localhost.me
::1 localhost localhost.me

127.0.0.1 localhost app.localhost.me
::1 localhost app.localhost.me
# End of section
```
It looks like HMR is now working on Next.js 13.4.19.

**Comment by TotomInc** [comment]
Something really strange is that when I'm running these commands while testing installs (`npm i && rm -rf .next && npm run dev`), I get the `[Fast Refresh] rebuilding` in the browser on the initial render in the console.

Then, if I try to edit a file, HMR recompilation isn't triggered. I refresh the tab, I don't have the [Fast Refresh] rebuilding` message anymore in the browser console.

I can get the [Fast Refresh] rebuilding` message again if I'm `rm -rf .next` before starting the dev-server again.

**Comment by city17** [comment]
I'm experiencing the exact same problem. Happens both with `npx create-next-app@latest` and `yarn create next-app`. I've tried most combinations of settings (with & without TS, Tailwind, etc.) and Hot Refresh is always broken. Only downgrading to 13.4.7 as suggested by @TotomInc solves it.

**Comment by TotomInc** [comment]
@city17 could you also share your environment details like in the issue please? You can do it with `npx --no-install next info`

**Comment by TotomInc** [comment]
Thanks @city17, I just tried 18.13.0 with next.js 13.4.19 and the HMR still doesn't work. 😔

**Comment by TotomInc** [comment]
Well, I've just found out that I can run turbopack without any issue, since they have implemented almost all major compatibility features.
I can now use a "stable" next.js version (13.4.19) with `next dev --turbo` on my project.

**Comment by TotomInc** [comment]
Is there a way to enable debug logs for the webpack development server?

Something I would like to see, is if the server properly detects file changes which should then trigger a file recompilation.

**Comment by TotomInc** [comment]
I've finally managed to make it work.

[Thanks to this Webpack issue on StackOverflow](https://stackoverflow.com/a/28610124/3669565), it looks like some folders on macOS can get corrupted which causes `fsevents` to not send properly.

The easiest fix was to rename the parent folder (which contains all my project) to another name, than back to the original name:

```bash
$ mv ~/.github ~/.github-temp
$ mv ~/.github-temp ~/.github
```

**Comment by switz** [comment]
> The easiest fix was to rename the parent folder (which contains all my project) to another name, than back to the original name:

wow, this fixed it for me, thank you! word of caution: it's easier to change your directory name via finder (or gui) vs. the CLI – I accidentally broke my project with some bad `mv` commands. be careful.

make sure you're `git pushed` first too. speaking from experience.
