### ISSUE TITLE
Docs: providerImportSource in MDX is misleading

### ISSUE THREAD

**Issue by joshuaavalon** [vercel/next.js#54212]
### What is the improvement or update you wish to see?

Currently, `@next/mdx` uses `@mdx-js/react` by default but the example tell you to set `providerImportSource` to `"@mdx-js/react"`.

https://github.com/vercel/next.js/blob/87b66f64e53b9e5867cc88a7d648f4ab0af816ac/packages/next-mdx/index.js#L24-L28

If you set `providerImportSource` to `"@mdx-js/react"`, `mdx-components.tsx` from "Getting Started" will no longer work.

### Is there any context that might help us understand?

Next.js example
```js
import remarkGfm from 'remark-gfm'
import createMDX from '@next/mdx'
 
/** @type {import('next').NextConfig} */
const nextConfig = {}
 
const withMDX = createMDX({
  options: {
    extension: /\.mdx?$/,
    remarkPlugins: [remarkGfm],
    rehypePlugins: [],
    // If you use `MDXProvider`, uncomment the following line.
    // providerImportSource: "@mdx-js/react",
  },
})
export default withMDX(nextConfig)
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/configuring/mdx

**Comment by mnengwa** [comment]
Can confirm this issue. It haunted me the whole night. 

After defining your components in `mdx-components.tsx` at the root of your project e.g
```
import { Typography } from "antd";
import type { MDXComponents } from "mdx/types";

export const useMDXComponents = (components: MDXComponents): MDXComponents => {
    return {
        h1: ({ children }) => <Typography.Title>{children}</Typography.Title>,
        ...components,
    };
};
```

Having `providerImportSource` set to "@mdx-js/react" like below would not render your custom components but use the default components.

**DOES NOT WORK**
```
/** @type {import('next').NextConfig} */

const nextConfig = {
    experimental: {
        mdxRs: true,
    },
};

const withMDX = require("@next/mdx")({
    options: {
        extension: /\.mdx?$/,
        providerImportSource: "@mdx-js/react",
    },
});

module.exports = withMDX(nextConfig);
```
