### ISSUE TITLE
Module not found: Cant resolve fs

### ISSUE THREAD

**Issue by zinzombe-kin** [vercel/next.js#54220]
I'm trying to convert one of my components into a client component but I keep running into the "Module not found : Can't resolve 'fs'" error. I've found this to be useful but this component uses useState, therefore it has to be a client component, here is the relevant part of my code:

"use client";

const Nav  = () => {
const [navOpen, toggle a Open] = useState(false);

return () 
} 

Hi,

You are putting a `"use client"` directive inside a server component. When the compiler tries to bundle that up for the client it touches `fs`.

Remove that `"use client"` directive and you'll be fine.

---

To format code it is better to use triple `:

> like this: ```js
 
and then put your code

And then close with triple ` once again:

> like this: ```

So that it can look like:

```js
let world = "world"
const hello = `${world}`
```

_Originally posted by @icyJoseph in https://github.com/vercel/next.js/discussions/45784#discussioncomment-4938892_

**Comment by icyJoseph** [comment]
Can you show me the more of the code? In general you have to refactor so that the parts that use interactivity, "use client", are contained within their own module, and the `fs` bits are in the server component.

Post some pseudo-code and I can help you out.

**Comment by zinzombe-kin** [comment]
Thanks for helping out Joseph!

Here is the code for the entire component:
'use client'

import Link from "next/link";
import {RegisterLink, LoginLink} from "@kinde-oss/kinde-auth-nextjs/server";
import Image from "next/image";
import { FunctionComponent, useState } from "react";

const Nav: FunctionComponent = () => {
    const [navOpen,setNavOpen] = useState(false);
    const user = undefined;

    return (
        <nav className="flex justify-between py-4 sm:py-2 bg-gray-300 shadow-xl px-2 relative">
            <Link href="/">
                <h1 className="font-title text-4xl sm:text-3xl font-bold">Gamer<span className="text-red-500 text-xl">pulse</span></h1>
            </Link>

            <div className="sm:flex hidden">
                {/* Desktop nav */}

                {
                    user ?
                    <div className="flex">
                        <Image 
                        src="/assets/user/user.jpg"
                        alt="Profile image"
                        />

                        <div>
                            <h2 className="text-xl font-heading font-bold">Kin Leon Zinzombe</h2>
                            <p className="font-heading">kinzinzombe07@gmail.com</p>
                        </div>
                    </div> :
                    <div className="flex gap-4">
                    <RegisterLink className="bg-purple-900 text-white px-8 py-1 rounded-full hover:bg-purple-700">Register</RegisterLink>
                    <LoginLink className="bg-transprarent border border-gray-700 text-black px-8 py-1 rounded-full hover:bg-white">Login</LoginLink>
                    </div>
                }

                <div className="grid shadow-xl absolute h-[100vh] w-[100vw] sm:hidden ">
                    {/* Mobile nav */}

                    {
                        navOpen ? 
                        <div className="">
                            <h2>Mobile nav</h2>
                        </div> :
                        <Image
                        alt="bars"
                        src="/images/bars.svg" 
                        width={30}
                        height={30}
                        />
                    }
                </div>
            </div>
        </nav>
    )
}

export default Nav;

**Comment by icyJoseph** [comment]
@zinzombe-kin but where's `fs` used here? I searched quickly on `@kinde-oss/kinde-auth-nextjs/server`, and found nothing on their Github Repository, maybe it is through a dependency? Could you post the error stack you are getting? Screenshot or whatever, so I can identify where the `fs` is being used?

**Comment by zinzombe-kin** [comment]
That's exactly the point, I'm not using fs ANYWHERE in my code, There isn't a single file that uses fs

But the error message suggests its being used by a NextJS  inside node_modules

**Comment by icyJoseph** [comment]
But could you take a screenshot of the errors? Terminal messages, or browser error overlay.

**Comment by icyJoseph** [comment]
I have an idea but I just want to see the error message before giving you a way out. Otherwise we might end up creating more confusion.

**Comment by zinzombe-kin** [comment]
Understood, here is the error:

![image](https://github.com/vercel/next.js/assets/125105023/215f8987-4d5e-4fe2-8a4d-ca61610f8081)

**Comment by icyJoseph** [comment]
Right so the way I interpret that is that `@kinde-oss` in importing `NextResponse` from `next/server` and when you in turn import the RegisterLink, and LoginLink components, you, indirectly, import NextResponse too.

That means that you also import indirectly, those things that `NexResponse` imports, which unfortunately ends up touching `fs` at some point.

- https://github.com/kinde-oss/kinde-auth-nextjs/blob/51721bd6a4bf36ebe62f3bb19c9743f4bdaef56d/src/authMiddleware/authMiddleware.js#L4
- https://github.com/kinde-oss/kinde-auth-nextjs/blob/51721bd6a4bf36ebe62f3bb19c9743f4bdaef56d/server/index.d.ts#L4

In the second case it is only type definitions, but in the first it is actually used. 

To be fair, the import is `import {RegisterLink, LoginLink} from "@kinde-oss/kinde-auth-nextjs/server";` which indicates that this ought to be used only on server side code.

For completeness sake, the code issue originates at:

```js
// node_modules/@kinde-oss/kinde-auth-nextjs/dist/server/index.js
// other imports
import { SHA256 as t, enc as r } from "crypto-js";
import n from "jwt-decode";
import { NextResponse as s } from "next/server";

// mode stuff 

function k(e) {
  let t = !1;
  const r = y(e.nextUrl.href),
    o = y(u.postLogoutRedirectURL),
    a = e.cookies.get("kinde_token"),
    c = r === o;
  return (
    a && (n(JSON.parse(a.value).access_token), (t = !0)),
    t || c
      ? t && c
        ? s.redirect(new URL(u.postLoginURL))
        : s.next()
      : s.redirect(new URL(u.postLogoutRedirectURL, e.url))
  );
}

// and more stuff
```

The one thing to understand here is that this is kind of bad already. You'll end up also bundling `crypto-browserify` into your client, and a bunch of other stuff that's expected to be only server side supported.

## A (potential) work around

1. Refactor Nav to:

```tsx
"use client";

import Link from "next/link";
import Image from "next/image";
import { useState, ReactNode } from "react";

const Nav = ({ kindeControls }: { kindeControls: ReactNode }) => {
  const [navOpen, setNavOpen] = useState(false);
  const user = undefined;

  return (
    <nav className="flex justify-between py-4 sm:py-2 bg-gray-300 shadow-xl px-2 relative">
      <Link href="/">
        <h1 className="font-title text-4xl sm:text-3xl font-bold">
          Gamer<span className="text-red-500 text-xl">pulse</span>
        </h1>
      </Link>

      <div className="sm:flex hidden">
        {/* Desktop nav */}

        {user ? (
          <div className="flex">
            <Image src="/assets/user/user.jpg" alt="Profile image" />

            <div>
              <h2 className="text-xl font-heading font-bold">
                Kin Leon Zinzombe
              </h2>
              <p className="font-heading">kinzinzombe07@gmail.com</p>
            </div>
          </div>
        ) : (
          <div className="flex gap-4">{kindeControls}</div>
        )}

        <div className="grid shadow-xl absolute h-[100vh] w-[100vw] sm:hidden ">
          {/* Mobile nav */}

          {navOpen ? (
            <div className="">
              <h2>Mobile nav</h2>
            </div>
          ) : (
            <Image alt="bars" src="/images/bars.svg" width={30} height={30} />
          )}
        </div>
      </div>
    </nav>
  );
};

export default Nav;
```

2. Use Nav by passing in the Server Components (RegisterLink, and LoginLink), from a Server Component:

```tsx
// this ought to be a server component
import Nav from "./Nav";
import { RegisterLink, LoginLink } from "@kinde-oss/kinde-auth-nextjs/server";

export default function Home() {
  return (
    <Nav
      kindeControls={
        <>
          <RegisterLink className="bg-purple-900 text-white px-8 py-1 rounded-full hover:bg-purple-700">
            Register
          </RegisterLink>
          <LoginLink className="bg-transprarent border border-gray-700 text-black px-8 py-1 rounded-full hover:bg-white">
            Login
          </LoginLink>
        </>
      }
    />
  );
}
```

## A better fix

I think `@kinde-oss/kinde-auth-nextjs` should expose RegisterLink, and LoginLink from a different module, so that `next/server` is not indirectly used by consumers of these components.

- https://github.com/kinde-oss/kinde-auth-nextjs/blob/51721bd6a4bf36ebe62f3bb19c9743f4bdaef56d/src/components/LoginLink.js
- https://github.com/kinde-oss/kinde-auth-nextjs/blob/51721bd6a4bf36ebe62f3bb19c9743f4bdaef56d/src/components/RegisterLink.js#L4

As we can see, they are just React components, they shouldn't be bundled up in `/node_modules/@kinde-oss/kinde-auth-nextjs/dist/server/index.js`.

To be fair, maybe they already do? I haven't used this API ever, and I just skimmed through their Github page ReadMe, you'll have to ask them.

**Comment by zinzombe-kin** [comment]
Thanks a lot! This has fixed my issue and it's working fine now!

**Comment by icyJoseph** [comment]
> Thanks a lot! This has fixed my issue and it's working fine now!

@zinzombe-kin if that's the case then either turn this into a discussion and mark it as answered by my comment or just close the issue (simplest). Have a great day and don't hesitate to ask further, preferably first as a discussion.

**Comment by z-Zihan** [comment]
I've also encountered this issue. Could you help me take a look at what the problem might be?
![image](https://github.com/vercel/next.js/assets/46581968/0efb4e83-bde1-4975-bbbf-b5901e9812dd)

text：
./node_modules/next/dist/compiled/@vercel/og/index.node.js:18677:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/next/server.js
./node_modules/@supabase/auth-helpers-nextjs/dist/index.js
./pages/_app.tsx

**Comment by icyJoseph** [comment]
@z-Zihan It looks like you are importing from `@supabase/auth-helpers-nextjs` inside `_app`.

Are you making sure to not include it on the client bundle? Are you perhaps using `getInitialProps`? Could you show us how `_app` is structured?

**Comment by z-Zihan** [comment]
Thanks a lot! This has fixed my issue and it's working fine now!

**Comment by AhmedNaoumvdev** [comment]
> @z-Zihan It looks like you are importing from `@supabase/auth-helpers-nextjs` inside `_app`.
> 
> Are you making sure to not include it on the client bundle? Are you perhaps using `getInitialProps`? Could you show us how `_app` is structured?

Hello @icyJoseph I get the same error of module not found 'fs'
```
- error ./node_modules/next/dist/compiled/@vercel/og/index.node.js:18677:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/next/server.js
./node_modules/@kinde-oss/kinde-auth-nextjs/dist/server/index.js
./app/dashboard/page.tsx
./app/dashboard/class/page.tsx
```
and this is my class/page.tsx code 

```
"use client"
import * as XLSX from "xlsx";
import { user } from "../page";
const Class = () => {
  const [modalClassIsOpen, setClassIsOpen] = React.useState<boolean>(false);
  const [modalGroupIsOpen, setGroupIsOpen] = React.useState<boolean>(false);
  const [className, setClassName] = React.useState<String>("");
  const [classList, setClassList] = React.useState<String[]>([]);
  const [activeClass, setActiveClass] = React.useState<String | null>("");
  const [GroupName, setGroupName] = React.useState<String>("");
  const [groupList, setGroupList] = React.useState<String[]>([]);
  const [studentData, setStudentData] = React.useState<Student[]>([]);

  const db = getFirestore();
  const handleActiveClass = async (
    e: React.MouseEvent<HTMLParagraphElement>
  ) => {
    e.stopPropagation();
    document.querySelectorAll(".oneClass").forEach((className) => {
      className.classList.remove("activeClass");
    });
    (e.target as Element).classList.add("activeClass");
    console.log((e.target as Element).textContent);
    setActiveClass((e.target as Element).textContent);
    await getDocs(
      collection(
        db,
        "users",
        `${user?.id}`,
        "classes",
        `${(e.target as Element).textContent}`,
        "groups"
      )
    )
```

As you can see I import user from ../page because class/page is a client component so I getKindeServerSession in a server component and call it a client component 

```
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const { getUser } = getKindeServerSession();
export const user = getUser();
const Main = async () => {
  return <div>Mainooooooooo</div>;
};
export default Main;
```
why this error is occurred? and to be more precise I get the user data from Kinde I use it in my dashboard Pages
my dashboard has a layout with a fixed sidebar and the other page are sub folder inside dashboard folder in the app router 
this is my case in details hope you can help me or anyone I will be very very thankful.

**Comment by DaveOrDead** [comment]
Thanks @icyJoseph, one of the maintainers of Kinde here.  Great point on SSC for the link components, we'll look into exposing `RegisterLink` and `LoginLink` as client components.

@AhmedNaoumvdev if you raise your issue on the https://github.com/kinde-oss/kinde-auth-nextjs repo we'll take a look into it for you there
