### ISSUE TITLE
Docs: It should be highlighted whether we can use traditional CSS files or no in App router

### ISSUE THREAD

**Issue by gmoniava** [vercel/next.js#54248]
### What is the improvement or update you wish to see?

It is a little bit unclear if we can use traditional CSS files in Nextjs app router like we did with react SPA apps; for example when we could have `Button.jsx` and `Button.css` in react apps.

So is this possible? If no, docs should mention it.

There is talk about some global styles, but I was not sure how that applied to my above question.
https://nextjs.org/docs/app/building-your-application/styling/css-modules#global-styles

### Is there any context that might help us understand?

N/a

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/styling/css-modules#global-styles

**Comment by gmoniava** [comment]
@balazsorban44 fyi

**Comment by leerob** [comment]
Yes, you can 👍 The docs are recommending CSS modules still, though. The most common use case for this would be using a published CSS from from an external dependency, which that works okay. 

https://nextjs.org/docs/app/building-your-application/styling/css-modules#external-stylesheets

**Comment by gmoniava** [comment]
Yeah now I remember it was mentioned in the "External Stylesheets" but I still think it would be better for docs to explicitly say that this approach (e.g. having `Button.jsx` and `Button.css`) is possible but not recommended. Someone might think that it is only ok for external stylesheets and global.css for example.
