### ISSUE TITLE
Docs: learning page theme switcher not working

### ISSUE THREAD

**Issue by Grazinascito** [vercel/next.js#54255]
### What is the improvement or update you wish to see?

I tried changing light mode to dark mode but it didn't work
![Captura de Tela 2023-08-18 às 19 17 02](https://github.com/vercel/next.js/assets/65836646/01f86133-8f9b-46aa-b02f-c3c2fbdb63d9)

### Is there any context that might help us understand?

I shared the webpage to more 2 friends and they relate the same issue

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/about-nextjs

**Comment by balazsorban44** [comment]
Thanks, this is related to https://github.com/vercel/next.js/issues/51244 so closing. We are working on revamping the Learn pages.
