### ISSUE TITLE
onClick not working in fresh project in next 13.4.17

### ISSUE THREAD

**Issue by shulinnn** [vercel/next.js#54269]
### Verify canary release

- [] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.16
      eslint-config-next: 13.4.16
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/shulinnn/next-reprod

### To Reproduce

Use npx create npx create-next-app@latest with app router add onClick handler to whatever element.

### Describe the Bug

onClick handler on any element simply doesnt work.

### Expected Behavior

Should log "XD" into the console.

**Comment by icyJoseph** [comment]
As discussed in https://github.com/vercel/next.js/discussions/54196 this is still not really reproduce-able. https://stackblitz.com/github/shulinnn/next-reprod shows (when Stackblitz works) that the click handler works. 

I've also shared a video in the discussion showing how things work fine. We need more data regarding how you experience this issue.

Do you also experience it when you `build` the app?

**Comment by shulinnn** [comment]
Did nothing else that create a fresh next.js app and edited the page.js file. Havent tried building it. Could it be brave browser? Cant really try the stackblitz in Brave but in Chrome i can.

**Comment by icyJoseph** [comment]
Could you build the app? and see the same error happens?  I'll give it a got in Brave (had not used it for some months now)

**Comment by icyJoseph** [comment]
@shulinnn do you, maybe have JavaScript disabled?

**Comment by shulinnn** [comment]
Why would it work for me in 13.4.16 then ?

**Comment by icyJoseph** [comment]
Alright then, did you try building the app?

**Comment by icyJoseph** [comment]
Does it work to switch to `console.count`? maybe somehow your console.log function is monkey patched?

**Comment by shulinnn** [comment]
Still no output with `console.count()` Will try the build later.

**Comment by icyJoseph** [comment]
Uff this is not looking good. I am worried it is OS specific. 

When you try building, do something like `console.log("FOO1337")`, and then search for that in the `.next` folder. I want to see if its bundled into the client code.

I did not understand, but, did you try with other browsers, same issue?

**Comment by shulinnn** [comment]
Yes, i tried Chrome and Brave.Dont have anything else to try it on.
> When you try building, do something like console.log("FOO1337"), and then search for that in the .next folder. I want to see if its bundled into the client code.
It does not get bundled.

**Comment by icyJoseph** [comment]
Let's try to discard SWC. 

Create a `.babelrc` file, and put this on it:

```json
{
  "presets": ["next/babel"],
  "plugins": []
}
```

That'll opt-out from SWC compiling during dev mode. Does it still not work?

**Comment by ca-lee-b** [comment]
I've been having this exact same problem (in 13.4.18 aswell), eventually I caved in and downgraded to 13.4.16.

**Comment by icyJoseph** [comment]
> I've been having this exact same problem (in 13.4.18 aswell), eventually I caved in and downgraded to 13.4.16.

Windows too?

**Comment by ReezanVisram** [comment]
Same issue in 13.4.19, Chrome, Windows - `onClick` events were not firing. Downgraded to 13.4.16 and `onClick` events are working.

**Comment by icyJoseph** [comment]
@ReezanVisram could you try to verify if the handlers are included in the client bundle? And also try to use babel as described above?

**Comment by ReezanVisram** [comment]
It is there in 13.4.16:
![image](https://github.com/vercel/next.js/assets/59345266/e6d8aa0b-f9ff-4f38-bdf8-a2fb7853892b)
But not in 13.4.19:
![image](https://github.com/vercel/next.js/assets/59345266/8640954d-4381-4d79-a609-ce8587156861)

**Comment by icyJoseph** [comment]
Uff, this is not looking good. I've tried once again, once with TS on, one with only JS, and it works fine. I am using a Macbook.

It also worked on Stackblitz, which would mean it is not a Linux issue. 

I don't have access to my Windows and Linux machines until Monday. And my Windows machine doesn't even have a dev env setup 🤔 

@ReezanVisram, sorry for asking stuff from you once again, but between `13.4.16` and `13.4.17`, there was:

- `13.4.17-canary.0`
- `13.4.17-canary.1`
- `13.4.17-canary.2`

Could you install those, `npm install next@13.4.17-canary.0` for example, and try to figure out which one introduced the breakage?

**Comment by ReezanVisram** [comment]
@icyJoseph 
- `13.4.17-canary.0` - `onClick` works, `FOO1337` is in the `/.next` directory
- `13.4.17-canary.1` - `onClick` DOES NOT work, but `FOO1337` is in `server/app` and `/static/chunks/app`  but NOT in `layout.<numbers>.hot-update.js` in the `/.next` directory 
- `13.4.17-canary.2` - `onClick` DOES NOT work, but `FOO1337` is in `server/app` and `/static/chunks/app`  but NOT in `layout.<numbers>.hot-update.js` in the `/.next` directory

**Comment by ReezanVisram** [comment]
I also noticed in the Chrome console on `13.4.16`, I get the message `[Fast Refresh]: Reloading` but I don't see that on `13.4.17-canary.1` and `13.4.17-canary.2`. Idk if that helps

**Comment by icyJoseph** [comment]
What Node version do you have? There's so few commits after canary 0... One did a change that assumes a Node.js version greater than 16.5 🤔 The plot thickens!

**Comment by ReezanVisram** [comment]
I'm using Node v16.13.1

**Comment by icyJoseph** [comment]
EUREKA! I've got it. It is the Next.js version! I tried with 16.13.0, and it broke for me too! 16.14.0 fixes it!!! 🎉

**Comment by icyJoseph** [comment]
Alright y'all, upgrade your Node.js version to 16.14.0, the docs are out of date, with regards to that, and the using anything lower than 16.13.0, and least in my case, won't let me install at all, because:

```console
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error ts-api-utils@1.0.2: The engine "node" is incompatible with this module. Expected version ">=16.13.0". Got "16.8.0"
error Found incompatible module.
```

Please do upgrade to 16.14.0 - I'd recommend taking 18.16.0 or later, if possible.

**Comment by ReezanVisram** [comment]
Awesome, thank you!

**Comment by huozhi** [comment]
Thanks @icyJoseph , nice catch
