### ISSUE TITLE
PrismaClient is unable to be run under the Vercel Edge Runtime

### ISSUE THREAD

**Issue by JawadFadel** [vercel/next.js#54271]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.17
      eslint-config-next: 13.4.17
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.17", newest: "13.4.19".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js/assets/59622265/56d4f024-24e3-4c41-85c7-87cfba9016d5

### To Reproduce

When im using prsima in middleware  gets error PrismaClient is unable to be run under the Vercel Edge Runtime

### Describe the Bug

Error: PrismaClient is unable to be run under the Vercel Edge Runtime.

### Expected Behavior

gets data from db

**Comment by benjaminwaterlot** [comment]
That's expected @JawadFadel 🙂

Prisma is telling you it's unable to run in the Vercel Edge Runtime because it is, indeed, not compatible with that runtime.

You therefore cannot run Prisma queries in middleware (because Next.js middleware is meant to run on the "edge runtime", not on Node.js), and should put them elsewhere in your back-end code.

**Comment by balazsorban44** [comment]
As said above, this is expected.
