### ISSUE TITLE
Extending request object stopped working

### ISSUE THREAD

**Issue by itrelease** [vercel/next.js#54288]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.4.0
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/sad-jepsen-q3792z

### To Reproduce

Update nextjs to version > 13.4.12

### Describe the Bug

In my project I'm using custom expressjs server which sets few middleware functions and some of them extending request object with new fields and these fields was accessible in `getServerSideProps` function via `context.request[here_new_my_new_field]`. This approach worked up to the version 13.4.12. 

### Expected Behavior

Custom fields should be accessible in request object and I should see `GUID is wow-test-guid`

**Comment by MarcusNotheis** [comment]
Looks like this issue is also affecting API Routes (https://github.com/vercel/next.js/issues/54129)

**Comment by balazsorban44** [comment]
Closing in favor of #54440. Feel free to comment there!
