### ISSUE TITLE
Docs: missing docs for dynamic manifest.ts metadata route

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#54296]
### What is the improvement or update you wish to see?

unless i missed something, the dynamic `manifest.ts`/`manifest.tsx` metadata route is currently not documented. at least it is not mentioned [here](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#manifest)

### Is there any context that might help us understand?

nope

**Comment by delbaoliveira** [comment]
Hey @stefanprobst, thank you for raising this. Here's the PR to document the `manifest` file: https://github.com/vercel/next.js/pull/54380
