### ISSUE TITLE
Docs: Serializable values that can be passed from the Server to Client Components

### ISSUE THREAD

**Issue by koichik** [vercel/next.js#54291]
### What is the improvement or update you wish to see?

[Passing props from Server to Client Components (Serialization)](https://nextjs.org/docs/getting-started/react-essentials#passing-props-from-server-to-client-components-serialization) says:
> Props passed from the Server to Client Components need to be [serializable](https://developer.mozilla.org/en-US/docs/Glossary/Serialization). This means that values such as functions, Dates, etc, cannot be passed directly to Client Components.

In fact, `Date`, `Set`, `Map`, especially `Promise` are seriarizable. They can be passed directly from the Server to Client Components.

### Is there any context that might help us understand?

Here is the serializable values defined by React:
https://github.com/facebook/react/blob/98f3f14d2e06fb785103296318204cd154d5d0ed/packages/react-server/src/ReactFlightServer.js#L128-L154

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/getting-started/react-essentials#passing-props-from-server-to-client-components-serialization

**Comment by delbaoliveira** [comment]
This is very interesting, thank you @koichik 🙏🏼  Will update it as part of this PR: https://github.com/vercel/next.js/pull/51579
