### ISSUE TITLE
Data inside the res.locals object from express in custom server is not available in pages/ after version 13.4.13+

### ISSUE THREAD

**Issue by skogie** [vercel/next.js#54381]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.17
      pnpm: 8.0.0
    Relevant Packages:
      next: 13.4.20-canary.2
      eslint-config-next: 13.4.20-canary.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/skogie/test-custom-express-server-next

### To Reproduce

run `yarn && yarn dev` navigate to http://localhost:3000, you should see it says `Data: My bad data` because res.locals is undefined in next `13.4.13+` in `pages/_app`

### Describe the Bug

After upgrading to 13.4.13 and above we are no longer able to use data set on res.locals inside the express custom server in `pages/_app.tsx`

### Expected Behavior

Whats expected to happen is that http://localhost:3000 renders with the page saying `Data: My nice data`, this works when using next version `13.4.12`

**Comment by nicholasgriffintn** [comment]
FYI: looks like another issue was made for this: https://github.com/vercel/next.js/issues/54440

**Comment by balazsorban44** [comment]
Closing in favor of #54440. Feel free to comment there!
