### ISSUE TITLE
Docs: Colors in api fn logs are force-enabled unless `FORCE_COLOR` is set to 0

### ISSUE THREAD

**Issue by willscripted** [vercel/next.js#54391]
### What is the improvement or update you wish to see?

Add documentation on turning off colors.
Possibly in the [Deploying](https://nextjs.org/docs/app/building-your-application/deploying#nodejs-server) section?
Or maybe mention something about the `FORCE_COLOR` env variable on the [Environment Variables](https://nextjs.org/docs/app/building-your-application/configuring/environment-variables) page.

### Is there any context that might help us understand?

Colors are printed out on `next start` in API function logs. This is usually not a desirable behavior when running in a production environment.
Many frameworks detect whether on not colors are supported or adhere to the [no-color standard](https://no-color.org/).

Digging in a little deeper, I see `FORCE_COLOR` is set to 1 in the [server's worker processes](https://github.com/vercel/next.js/blob/705b2ef2d4eb504aca5d7b9e015479fcaad1b624/packages/next/src/server/lib/server-ipc/index.ts#L103C1-L105).

My read here is that this is by design and just an expedient solution to [this issue](https://github.com/vercel/next.js/issues/11836) or some similar issue. 

Any docs would be appreciated. (Thank you! :partying_face: )
A better long-term solution might be checking for `NO_COLOR` before setting `FORCE_COLOR`.

**Comment by leerob** [comment]
It doesn't appear that this env var works anymore. Open to a community contribution to allow disabling colors + docs in the `next dev` part of the CLI!
