### ISSUE TITLE
Docs: Docs should say that for example static rendering doesn't work with dev server

### ISSUE THREAD

**Issue by gmoniava** [vercel/next.js#54396]
### What is the improvement or update you wish to see?

AFAIK if you do `npm run dev` you can't statically render a page:
https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic

Am I right? If yes, the docs should say it. Otherwise it can confuse people.

If you do instead this:` npm run build && npm run start`, then static rendering works. But docs should mention it.

### Is there any context that might help us understand?

n/a

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic

**Comment by gmoniava** [comment]
@balazsorban44 fyi

**Comment by gmoniava** [comment]
@leerob fyi

**Comment by leerob** [comment]
It's expected that the local development environment `next dev` ([docs](https://nextjs.org/docs/app/api-reference/next-cli#development)) is intentionally different than building your application for production.

For example, to generate a static page, you need to run `next build` and "prerender" it.

**Comment by gmoniava** [comment]
Yes but it would be better if **docs said this explicitly**. I had lost quite some time trying to figure out why static rendering didn't work with npm run dev. Then I got help on discord.

**Comment by leerob** [comment]
We'll consider this while updating the Next.js course, I think this should be one of the first things taught on the differences between local and prod. Good feedback!
