### ISSUE TITLE
style: formatting in new Next.js apps deviate from `prettier` defaults

### ISSUE THREAD

**Issue by hamirmahal** [vercel/next.js#54402]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
$  npx --no-install next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.16.1
      npm: 9.7.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.2
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/hamirmahal/nextjs-reproduce-style-inconsistency

### To Reproduce

1. Run `npx create-next-app@latest` from your terminal.
2. Go to `src/app/page.tsx`.
3. Save the file.
4. Notice that regardless of whether you set `prettier` to prefer single quotes or double quotes, there will be changes in the file.

https://github.com/vercel/next.js/assets/43425812/78f29485-421f-488a-b55a-0ae32281cd2f

### Describe the Bug

There's inconsistent styling in a brand new Next.js application. Either single quotation marks or double quotation marks should be preferred, as opposed to mixing both.

### Expected Behavior

Either single quotation marks or double quotation marks should be preferred.

**Comment by hamirmahal** [comment]
I'm happy to look into this myself if someone wants to point me toward the relevant code and source files.

**Comment by balazsorban44** [comment]
It's the formatting of `app/page*` and `pages/index*` files here: https://github.com/vercel/next.js/tree/canary/packages/create-next-app/templates that seems to be incosistent. Feel free to send a PR!

**Comment by hamirmahal** [comment]
Thanks! I created one. Feel free to comment on the PR to let me know what changes I should make.

**Comment by viktorronnback** [comment]
I might be missing something, but I have not found any inconsistencies with single/double quotes in the templates. Using single quote for JavaScript and JSX are two different formatting choices, and two different Prettier options. Maybe you just got this mixed up? It seems that single quote for JS and double quote for JSX are used by default in the template files.

The video attached to this issue shows Prettier formatting line 18 in a correct way: single-quote setting is set to false, line 18 contains JavaScript code (inside brackets) and is therefore changing it to double-quote.

I tested it myself by setting up a new project using `npx create-next-app@latest` with TS and Tailwind as this seems to be the project settings used in the reproduction. I formatted all files in the directory using Prettier with single quote set to true resulting in no changed files. Meaning that all files use consistent single/double quotes. I also tried formatting all files in https://github.com/vercel/next.js/tree/canary/packages/create-next-app/templates and found no changes in single/double quotes, meaning that there does not seem to be any inconsistencies there either.

**Comment by hamirmahal** [comment]
I updated the pull request because the TypeScript Tailwind template has formatting that deviates from some of `prettier`'s defaults, and I think those deviations are worth documenting in the form of a `packages/create-next-app/templates/app-tw/ts/.prettierrc` file.

**Comment by kachkaev** [comment]
I also think thank using Prettier defaults would be better. Left a comment in https://github.com/vercel/next.js/pull/54409#issuecomment-1817980252.

**Comment by kachkaev** [comment]
@styfle thanks for merging this! If Next.js team wants to improve `git blame` in templates, it’s possible to add `.git-blame-ignore-revs` to the repo and mention 4466ba436b996263307171d344cca199e8087744 in it.

DefinitelyTyped maintainers did recently: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.git-blame-ignore-revs. They switched to [`dprint`](https://www.npmjs.com/package/dprint) which also enabled semicolons and double quotes  everywhere. If a commit is mentioned in `.git-blame-ignore-revs`, it becomes ‘transparent’ to `git blame`.

**Comment by styfle** [comment]
@kachkaev I was going to add that after merging and forgot. Thanks for the reminder! 

PR here: https://github.com/vercel/next.js/pull/60582
