### ISSUE TITLE
Docs: Incorrect example shown when trying to opt out of cache for "Fetching data on the Server with third-party libraries"

### ISSUE THREAD

**Issue by juskek** [vercel/next.js#54434]
### What is the improvement or update you wish to see?

The following [example](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#example) does not work when trying to opt out of cache for "Fetching data on the Server with third-party libraries"

I have the following folder structure:
- src/
  - app/
    - page.tsx
  - utils/
    - get-item.ts 

And page.tsx looks like this:
```typescript
import { getItem } from '@/utils/get-item'
 
export default async function Page({
  params: { id },
}: {
  params: { id: string }
}) {
  const item = await getItem(id)
  // ...
}
```

If I put `export const revalidate = 0` in get-item.ts, e.g.
```typescript
import { cache } from 'react'
 
export const revalidate = 0 // ! DOES NOT WORK
 
export const getItem = cache(async (id: string) => {
  const item = await db.item.findUnique({ id })
  return item
})
```
 caching still occurs and whenever I refresh the page, I do not get the latest data from my third party library

However, if I move `revalidate` to page.tsx instead, e.g.

```typescript
import { getItem } from '@/utils/get-item'

export const revalidate = 0 // ! THIS WORKS
 
export default async function Page({
  params: { id },
}: {
  params: { id: string }
}) {
  const item = await getItem(id)
  // ...
}
```

Then no caching occurs and when I refresh the page I get the latest data as intended.

### Is there any context that might help us understand?

See GIFs at the following [PR](https://github.com/Theodo-UK/OmniLog/pull/35)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#example

**Comment by Shubhamrawat5** [comment]
Same issue

**Comment by leerob** [comment]
This was fixed!
