### ISSUE TITLE
Setting cookie and retrieving cookie in route handlers

### ISSUE THREAD

**Issue by Revaycolizer** [vercel/next.js#54432]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 16.17.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.2
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Revaycolizer/minimal-repo/tree/main

### To Reproduce

Failed to fetch token
Failed to fetch token
- error node_modules\axios\lib\core\settle.js (19:11) @ settle
- error AxiosError: Request failed with status code 500
    at Unzip.emit (node:events:525:35)
null
- error node_modules\axios\lib\core\settle.js (19:11) @ settle
- error AxiosError: Request failed with status code 500
    at Unzip.emit (node:events:525:35)
null
- error node_modules\axios\lib\core\settle.js (19:11) @ settle
- error AxiosError: Request failed with status code 500
    at Unzip.emit (node:events:525:35)
digest: "3042517773"
null

### Describe the Bug

 the browser is sending the cookie and the route can't see it when consuming it.

### Expected Behavior

the route should retrieve the cookie in the frontend instead of null value

### Which browser are you using? (if relevant)

Version 112.0.5615.138 (Official Build) (64-bit)

**Comment by balazsorban44** [comment]
The instructions aren't very clear, but I'll assume you are talking about: https://github.com/Revaycolizer/minimal-repo/blob/108b0fcf3681e6728f4298b06daab72fa98e1297/app/actions/getAdminToken.ts#L7-L11

Which in this case would work as expected, since you are not actually passing any cookies with the headers.

You can use `cookies()` to forward it to the request, or better yet, instead of making a network call, import the logic of `api/cookie/route.ts`, which is going to be more performant, avoiding an unnecessary network call.

See: https://nextjs.org/docs/app/api-reference/functions/cookies

**Comment by kutay-vesti** [comment]
I have same issue, I do not change anything. I got the same error on the template!

**Comment by Revaycolizer** [comment]
> The instructions aren't very clear, but I'll assume you are talking about: https://github.com/Revaycolizer/minimal-repo/blob/108b0fcf3681e6728f4298b06daab72fa98e1297/app/actions/getAdminToken.ts#L7-L11
> 
> Which in this case would work as expected, since you are not actually passing any cookies with the headers.
> 
> You can use `cookies()` to forward it to the request, or better yet, instead of making a network call, import the logic of `api/cookie/route.ts`, which is going to be more performant, avoiding an unnecessary network call.
> 
> See: https://nextjs.org/docs/app/api-reference/functions/cookies

i tried but neither of it works , i tried even getting some folks to look upon the codes and found out that the cookie is sent by browser but route hanlder fails to see it i think you should fix this problem
![cookie](https://github.com/vercel/next.js/assets/109684996/422fc872-9e2a-4fc1-bf15-112ab0a8d8df)

**Comment by Revaycolizer** [comment]
> I have same issue, I do not change anything. I got the same error on the template!

they need to fix it as the browser sends the cookie but route handler fails to see it
