### ISSUE TITLE
Extending request while using a custom server/standalone mode

### ISSUE THREAD

**Issue by balazsorban44** [vercel/next.js#54440]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Versions of Next.js 13.4.13 and above are affected.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps), Routing (next/router, next/navigation, next/link), Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

Reproductions are available in the linked issues below

### To Reproduce

Reproductions are available in the linked issues below

### Describe the Bug

When using a custom server/standalone mode, there might be an incentive to extend the request that is then passed on to other parts of the application to access the extra property.

Since 13.4.13, this is not straightforward/possible.

Link to related issues to consolidate them in a single location for tracking:

- https://github.com/vercel/next.js/issues/53883
- https://github.com/vercel/next.js/issues/54288
- https://github.com/vercel/next.js/issues/54129
- https://github.com/vercel/next.js/issues/54435
- https://github.com/vercel/next.js/issues/54381

### Expected Behavior

This is a bit tricky to solve because of the render workers, but we would like to track this until we have an answer/solution.

**NOTE**

If you are affected, please leave a comment below with your use case and a reproduction of the issue (make it as minimal as possible, so it's easy to investigate to anyone without prior knowledge of your codebase). Please do not comment without meaningful additional information (if you want to comment "same", etc., react :+1: to the original description instead)! Thank you.

Unhelpful/unrelated comments will be marked as off-topic/spam to keep the readability of the thread.

<sub>[NEXT-1553](https://linear.app/vercel/issue/NEXT-1553/extending-request-while-using-a-custom-serverstandalone-mode)</sub>

**Comment by itrelease** [comment]
Why creating another issue instead of picking one already existed and link similar issues?

**Comment by t-net** [comment]
**On AWS Fargate:**
Since version 13.4.13 the `request.nextUrl.origin` in the middleware is returning the internal IP address of the AWS Fargate container. We use this value as the base URL to make an API call to check some user values. This causes a `UND_ERR_CONNECT_TIMEOUT` error in fetch. On version 13.4.12 it returned the http://xxx.eu-west-1.compute.internal:8080 internal address. We're not sure if the hostname changes in the commit https://github.com/vercel/next.js/commit/a4b430e6f18e280ff1f97e8147dc807799f9c314 is causing the issue, or if it's a trying to change the hostname to https. 

**Locally**
On docker locally where localhost is equal to 0.0.0.0 it works fine, if we set the HOSTNAME variable to 0.0.0.0. It breaks if we set the hostname to localhost, since it then tries to access 127.0.0.1.

**Comment by coltonehrman** [comment]
We are seeing the same thing. Strangely I am also finding that my `console.log` are not showing when ran inside `getServerSideProps`.

**Comment by coltonehrman** [comment]
> We are seeing the same thing. Strangely I am also finding that my `console.log` are not showing when ran inside `getServerSideProps`.

It almost seems as if there is a different process running all together.

**Comment by coltonehrman** [comment]
I found some interesting stuff regarding the issues in 13.4.13

Initial PR
https://github.com/vercel/next.js/pull/52492

Reverted before 13.4.12 release
https://github.com/vercel/next.js/pull/53016

<img width="734" alt="Screenshot 2023-08-25 at 9 17 21 AM" src="https://github.com/vercel/next.js/assets/12456288/1a4553a3-1ac7-4fa3-92fc-c803865c933f">

Reverted Revert
https://github.com/vercel/next.js/pull/53029

No trace of when or where the reverted revert got released
It's as if this change got snuck in to 13.4.13

My hunch is this is what "broke the world", separating the router & render processes basically broke all things being passed between custom server (runs before routing) and render (runs in Next.js)

**Comment by coltonehrman** [comment]
> I found some interesting stuff regarding the issues in 13.4.13
> 
> Initial PR #52492
> 
> Reverted before 13.4.12 release #53016
> 
> <img alt="Screenshot 2023-08-25 at 9 17 21 AM" width="734" src="https://user-images.githubusercontent.com/12456288/263296290-1a4553a3-1ac7-4fa3-92fc-c803865c933f.png">
> Reverted Revert #53029
> 
> No trace of when or where the reverted revert got released It's as if this change got snuck in to 13.4.13
> 
> My hunch is this is what "broke the world", separating the router & render processes basically broke all things being passed between custom server (runs before routing) and render (runs in Next.js)

Tracing logic:

`invokeRequest` get's called:
https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/router-server.ts#L378-L386

`fetch` get's called:
https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/server-ipc/invoke-request.ts#L22-L41

Not sure how this worked before, but based on this logic, the `res` object will **NEVER** get sent to the "render" as it is making a new `http` request internally. This design of "separation" inherently **will not** support passing data between the custom server and Next.js router/renderer.

**Comment by nicholasgriffintn** [comment]
> No trace of when or where the reverted revert got released
> 
> It's as if this change got snuck in to 13.4.13

The reverted revert was the first commit in v13.4.13-canary.0.

**Comment by coltonehrman** [comment]
> > No trace of when or where the reverted revert got released
> > It's as if this change got snuck in to 13.4.13
> 
> The reverted revert was the first commit in v13.4.13-canary.0.

Yeah, it appears so. They should update the release notes here https://github.com/vercel/next.js/releases/tag/v13.4.13-canary.0 and here https://github.com/vercel/next.js/releases/tag/v13.4.13

**Comment by grawk** [comment]
Hey maintainers. This is a radical departure in terms of functionality for teams using Next.js with an express custom server, and relying upon decorated req/res objects. Can you all please provide a statement soon about whether this loss of functionality was purposeful and will not be maintained going forward? It is critical to helping with my team's decision of whether to continue using Next.js for our use case.

**Comment by coltonehrman** [comment]
> This is a bug. We're figuring out how to bring this back as it's non-trivial to support the request object being modified, it's accidental that it broke, there was no test for that, the tests for using the custom server API test the documented behavior which is passing Node.js request / response into the handler.

Will the bug fix only fix the `req`/`res` extension use case?

Based on the new code & design, this is just one case that is broken, other cases would include any bootstrapping of global objects at the custom server level & singleton modules that get required and depended on in the custom server in within Next.js contexts.

**Comment by cosieLq** [comment]
Another change that's happened in #53029 
is that the internal routing for static assets (/_next/static).

As mentioned in #54159 , custom response headers in next config are not applied to static assets when i18n is configured.
Since v13.4.13, NextJs also shows this inconsistency in applying custom headers for static assets between with and without i18n.

I hope this issue will be fixed soon as well. It has become a blocker for us.

**Comment by shaunwarman** [comment]
> This is a bug. We're figuring out how to bring this back as it's non-trivial to support the request object being modified, it's accidental that it broke, there was no test for that, the tests for using the custom server API test the documented behavior which is passing Node.js request / response into the handler.

@timneutkens would you mind sharing what specific change was made here to get eyes / brainstorming?

**Comment by nicholasgriffintn** [comment]
Just tried it out real quick, getting an error `NextRouter was not mounted` on our app using pages with `13.4.20-canary.24`, not getting it with `13.4.20-canary.23`.

**Comment by nicholasgriffintn** [comment]
^ Update: Changing useRouter imports in the packages that were erroring to use `next/compat/router` seems to have sorted the issue, it seems the change made means that `next/router` imports no longer work from packages for some reason.
