### ISSUE TITLE
Docs: Revalidating at build-time

### ISSUE THREAD

**Issue by dcporter44** [vercel/next.js#54452]
### What is the improvement or update you wish to see?

In the [revalidation docs](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating) it says: 

"By default, Next.js automatically caches the returned values of fetch in the [Data Cache](https://nextjs.org/docs/app/building-your-application/caching#data-cache) on the server. This means that the data can be fetched at build time or request time, cached, and reused on each data request."

The part that caused me a lot of confusion is "data can be fetched at build time". It makes it sound like if we use `fetch` in a server component with `revalidate: false` that it will still be revalidated on each build. This is not the case. The store is persistent across builds. This should be clarified.

### Is there any context that might help us understand?

Perhaps I'll create a feature request for this, but personally I want to have a way to revalidate data on `npm run build` and `npm run dev`. Currently I have to delete the `.next` folder before building. I want the data to be refreshed every time I restart the server.

The above documentation made me think this is how it worked by default. Caching forever even after restarting the server seems like an unusual default. Yes you may want to cache forever and manually revalidate using tags, but when not using tags, this behavior is something that will very rarely be needed. You might as well just download the data to a file in your project. But maybe that's just me. Regardless, I think there should be emphasis in the documentation that revalidation only occurs at build-time on the very first build.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating

**Comment by Fredkiss3** [comment]
I had the same issue, the trick i found was just to set a really low `revalidate` on fetch requests, `1` second is a good value, as each build will at least take more than one second. If you set your page to `force-static` the page will be built statically, it won't fetch at runtime, but next time you run a build it will refetch again.

**Comment by leerob** [comment]
The documentation seems correct here. The way to revalidate data would be to use the provided programmatic revalidation options, or as suggested above, use a low value for time-based revalidation.
