### ISSUE TITLE
Multi-zone not working on version 13.4.19. 13.4.3 works fine

### ISSUE THREAD

**Issue by Zonalds** [vercel/next.js#54454]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.0
      npm: 8.3.1
      Yarn: 1.22.19
      pnpm: 7.32.2
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A


warn  - Latest canary version not detected, detected: "13.4.19", newest: "13.4.20-canary.3".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
✨  Done in 5.96s.
```

### Link to the code that reproduces this issue or a replay of the bug

yarn dev

### To Reproduce

on `next.config.js` add 

```
const { APP_URL } = process.env

/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      {
        source: '/:path*',
        destination: `/:path*`,
      },
      {
        source: '/app',
        destination: `${APP_URL}/app`,
      },
      {
        source: '/app/:path*',
        destination: `${APP_URL}/app/:path*`,
      },
    ]
  },
}

module.exports = nextConfig
```
on `.env.local` add
APP_URL=http://localhost:3001

http://localhost:3001 references another nextjs app on port 3001

### Describe the Bug

When using Multi-zone to video a second app. The app refreshes indefinitely. The terminal prints https://nextjs.org/docs/messages/fast-refresh-reload 

### Expected Behavior

Downgrading to version 13.4.3 works fine. The app doesn't refresh indefinitely when using multi-zone

### Which browser are you using? (if relevant)

Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

not deployed yet

**Comment by bryanbarrios** [comment]
This behavior has been occurring since version `13.4.13`. Versions `<=13.4.12` work normally.

**Comment by agustints** [comment]
I am also experiencing the same issue after upgrading to `13.4.13` and later versions.
The source app works well, when navigating to apps that it's under the rewrite rules, the app refreshes indefinitely, and displays `⚠ Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload`.

**Comment by exneval** [comment]
Just faced the issues in my side as well, 13.4.13-canary-0 break multi zones in dev server, even with 13.5.2

please take a look @ijjk @huozhi

**Comment by wjaykim** [comment]
It occurs in 13.5.4 as well, which prevents us upgrading from 13.4.4 to 13.5.x. Please take a look this issue.

**Comment by liorheber** [comment]
I created this repository with the issue
https://github.com/liorheber/multizone-issue

**Comment by exneval** [comment]
It's so easy to reproduce:

Zone 1: https://codesandbox.io/p/sandbox/multi-zones-1-m79cw8

Zone 2: https://codesandbox.io/p/sandbox/multi-zones-2-xfk4d9

**Comment by francofantini** [comment]
Hi @samcx, have you been able to review the reproduction repos yet? Thank you.

**Comment by milo-** [comment]
Any updates on this? It's blocking us from upgrading 😢

**Comment by bryanbarrios** [comment]
In Next.js 14 with App Router this issue doesn't occur, but Fast Refresh doesn't work; if I edit a component, the change is not applied. I have to access the URL of the zone I'm modifying to see the change instantly, otherwise, I have to reload.

**Comment by 9vfQbg7z4ajrGQxR** [comment]
Please @ijjk @huozhi its blocking us for upgrading since 13.4.4 :pray:

**Comment by aladinflux** [comment]
It's even on NextJS 14

**Comment by SeegeneChoSeongMin** [comment]
What's happening to me is similar but a little different, I'm getting infinite reloads in dev mode, prod mode is fine, same as everyone else, but I'm getting the same error even with version 13.4.19(default is 14.0.2). Also, it happens with "Error : Hydration failed because the initial UI does not match what was rendered on the server".

My environment : 
pnpm : 8.8.0
turborepo : 1.10.16
next : 13.4.19(14.0.2)
OS : windows10
node : 18.17.0
typescript : 5.2.2
react: 18.2.0

**Comment by bookinlife** [comment]
i met same problem with with-zone example and next 14.

https://github.com/vercel/next.js/tree/canary/examples/with-zones

**Comment by wjaykim** [comment]
It's still not fixed in 14.0.4. It should be opened again.

**Comment by bryanbarrios** [comment]
> It's still not fixed in 14.0.4. It should be opened again.

Yes, it doesn't work on both routers as with Turbopack.

**Comment by exneval** [comment]
> It's so easy to reproduce:
> 
> Zone 1: https://codesandbox.io/p/sandbox/multi-zones-1-m79cw8
> 
> Zone 2: https://codesandbox.io/p/sandbox/multi-zones-2-xfk4d9

I updated to 14.0.4 and also still experience the same issue as before

please kindly check again @ztanner

**Comment by agustints** [comment]
Hi @jamaybyrone, thank you for the review, I replied to your comment in the [PR thread](https://github.com/vercel/next.js/pull/59471#discussion_r1426133328). 
Feel free to reach out if there's anything I can assist you with — I will be happy to help!
