### ISSUE TITLE
Docs: Data Fetching, Caching, and Revalidating 

### ISSUE THREAD

**Issue by Fishamble** [vercel/next.js#54459]
### What is the improvement or update you wish to see?

In the Data Fetching, Caching, and Revalidating page clicking the link
'Good to know: Revalidation only works with the [Node.js runtime]
results in a 500 error.

### Is there any context that might help us understand?

In the Data Fetching, Caching, and Revalidating page clicking the link
'Good to know: Revalidation only works with the [Node.js runtime]
results in a 500 error.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#caching-data

**Comment by delbaoliveira** [comment]
Thank you @Fishamble, we're clarifying this information in this PR: https://github.com/vercel/next.js/pull/54499
