### ISSUE TITLE
Docs: Add example for With-Docker using src directory 

### ISSUE THREAD

**Issue by YodaheaD** [vercel/next.js#54465]
### What is the improvement or update you wish to see?

In the 'with-docker' example the dockerfile is configured for next js projects using the app directory, what if we use the 'src' instead?

### Is there any context that might help us understand?

Add a small description on what changes the dockerfile if using the 'src' directory. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/deploying#docker-image

**Comment by leerob** [comment]
Hey! Open to a community contribution here 😄 

https://nextjs.org/docs/community/contribution-guide

**Comment by benjaminreid** [comment]
I used this exact Dockerfile with the src directory and it worked just fine a few days ago.

I actually assumed it wouldn’t at first. But it only really interacts with the .next folder which stays in the root of your project anyway.

**Comment by leerob** [comment]
Oh true, very good point! I guess we don't need to update the example then 😄
