### ISSUE TITLE
"jfif" files fail to render with "Image" component

### ISSUE THREAD

**Issue by jaandrews** [vercel/next.js#54464]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next info throws an error when I attempt to run it in my environment, even with the "--no-install" flag.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Image optimization (next/image, next/legacy/image)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/stupefied-fermi-8nfs9c

### To Reproduce

1. Get a jfif file.
2. Render it with the Image component from "next/image"

### Describe the Bug

Image request throws a 403 error.

### Expected Behavior

Image renders.

### Which browser are you using? (if relevant)

Chrome 116.0.5845.97

**Comment by nusr** [comment]
Changing image source from **/public/c2a8ae0cff16b1bf9bfe41f5160a84ea.jfif** to **/c2a8ae0cff16b1bf9bfe41f5160a84ea.jfif** will fix this problem.

**Comment by balazsorban44** [comment]
The above is correct. You do not need to append `/public` to the URL. See https://nextjs.org/docs/getting-started/installation#the-public-folder-optional
