### ISSUE TITLE
npx create-next-app@latest - no input except <ENTER>

### ISSUE THREAD

**Issue by jelmd** [vercel/next.js#54521]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.13
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

CLI (create-next-app)

### Link to the code that reproduces this issue or a replay of the bug

https://nextjs.org/

### To Reproduce

npx create-next-app@latest

### Describe the Bug

It is impossible to configure anything when running `npx create-next-app@latest` because it seems to accept the <ENTER> key, only - neither any letter combination of N[o] nr Y[es].

### Expected Behavior

It should allow to enter 'y' or 'n' at least.

### Which browser are you using? (if relevant)

FF

**Comment by joulev** [comment]
It accepts Enter and left/right arrow keys.

**Comment by jelmd** [comment]
OMG!

**Comment by balazsorban44** [comment]
This is coming from the underlying CLI prompt package we use.

They seem to have: https://www.npmjs.com/package/prompts#confirmmessage-initial

But we implemented the Yes/No questions via: https://www.npmjs.com/package/prompts#togglemessage-initial-active-inactive

Changing it would probably be disruptive. You can do what https://github.com/vercel/next.js/issues/54521#issuecomment-1692910807 said.
