### ISSUE TITLE
`redirect` does not take `basePath` into account

### ISSUE THREAD

**Issue by jim-king-2000** [vercel/next.js#54546]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 11 Home China
    Binaries:
      Node: 20.5.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: export
```

### Link to the code that reproduces this issue or a replay of the bug

no link

### To Reproduce
```javascript
import { redirect } from 'next/navigation';


export default function RootPage() {
  redirect('/cn');
}
```
### Describe the Bug

Since the basePath is `/abc`. We expect the code above to redirect `/abc` to `/abc/cn`.

### Expected Behavior

But it redirects to `/cn` without taking `basePath` into account.

**Comment by balazsorban44** [comment]
#54277 was supposed to fix this, can you verify `next@canary`

**Comment by jim-king-2000** [comment]
> #54277 was supposed to fix this, can you verify `next@canary`

Sure. I'll verify it ASAP.

**Comment by jim-king-2000** [comment]
Verified. Fixed in canary.
