### ISSUE TITLE
Docs: Potentially wrong example (because `export const revalidate` might not work outside special files)

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#54547]
### What is the improvement or update you wish to see?

In the documentation page linked below there is this example

```tsx
// utils/get-item.ts
import { cache } from 'react'
 
export const revalidate = 3600 // revalidate the data at most every hour
 
export const getItem = cache(async (id: string) => {
  const item = await db.item.findUnique({ id })
  return item
})
```

which shows `revalidate` being used in a file that is not a segment file (`page.tsx`, `layout.tsx`, or `route.ts`). Is it intended? Because I feel like this might not work. I haven't tried this example myself, but a user in the Discord server checked and [saw that it didn't work](https://discord.com/channels/752553802359505017/752647196419031042/1142783941632340020):

<img width="641" alt="image" src="https://github.com/vercel/next.js/assets/44609036/ebdbecd5-3aa0-4898-b56d-dcc7faff5080">

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#example

**Comment by Diego-0110** [comment]
I've also followed that documentation section to apply revalidation in a personal project and it doesn't work. But, when I export the revalidate constant in the Server Component that calls the function, which is 'page.js', works.
There is a similar 'issue' open: [https://github.com/vercel/next.js/issues/54434](https://github.com/vercel/next.js/issues/54434)

**Comment by joulev** [comment]
Ah yes indeed. This issue is a duplicate of that one so I'll close this one.
