### ISSUE TITLE
React canary version used although 18.2 is specified in package.json

### ISSUE THREAD

**Issue by GabiGrin** [vercel/next.js#54553]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
Binaries:
  Node: 18.17.0
  npm: 9.8.1
  Yarn: N/A
  pnpm: 8.6.12
Relevant Packages:
  next: 13.4.20-canary.5
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/GabiGrin/nextjs-issue-repro

### To Reproduce

1. Define a specific version of React, i.e. `18.2.21`
2. Print `React.version` 

### Describe the Bug

Next.js is using a different version of React (in my case, it is `18.3.0-canary-dd480ef92-20230822`), looks like it's coming from `dist/compiled/react`

PS: I got to this bug while debugging a different issue, app freezing -> https://github.com/FlydeHQ/playground (play.flyde.dev) when using a specific component (`@flyde/flow-editor`), hoping that it would work in the correct React version

### Expected Behavior

The specified React version would be used.
I.e that  https://nextjs-issue-repro.vercel.app/ would show `18.2.21`

### Which browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

Vercel

**Comment by balazsorban44** [comment]
Hi, this is going to be the case when you are using the App Router, as it's pulling in some APIs that are not yet available in other React channels.

**Comment by GabiGrin** [comment]
Thanks for the explanation @balazsorban44!
