### ISSUE TITLE
favicon does not honor the assetPrefix config option and cannot be overridden / added to the head

### ISSUE THREAD

**Issue by ctsstc** [vercel/next.js#54579]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.7
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/ctsstc/next-js-favicon-asset-prefix-bug

### To Reproduce

Use the `assetPrefix` run a build/deploy, check the route that the `icon.png` is being requested from does not include the `assetPrefix` from the Next Config options.

### Describe the Bug

It seems when utilizing the `assetPrefix` option in Next Config, that the favicon is still trying to request from the root of the project which does not work when deployed for me given that this is hosted under a subpath and requires special route handling.

Everything else seems to be prefixing the resources properly.

I verified the asset is available under the prefix path.

Context: I'm utilizing the app router with the `icon.png` in the root of the app directory.

I've tried removing the icon file, and explicitly throwing a `Head` tag with a an absolute path to an icon and it seems to strip it from the render/build.

ie: 

```tsx
<Head>
  <link
    rel="icon"
    href="https://nextjs.org/favicon.ico"
    type="image/png"
  />
</Head>
```

### Expected Behavior

The favicon should prefix the `assetPrefix` to it.

<sub>[NEXT-1564](https://linear.app/vercel/issue/NEXT-1564/favicon-does-not-honor-the-assetprefix-config-option)</sub>

**Comment by huozhi** [comment]
The static icon files will be generated as static routes like other pages/custom routes in app router as the assetPrefix is for static files so it won't apply to it.

The `next/head` is a noop in app router. Prefer to use metadata API to define the icons if they're deployed separately.
Check the [metadata API docs](https://nextjs.org/docs/app/building-your-application/optimizing/metadata) for more details 
```js
export const metadata = {
  icon: [...]
}
```
