### ISSUE TITLE
cannot use font loaded by next/font

### ISSUE THREAD

**Issue by kiuka** [vercel/next.js#54573]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 16.19.1
      npm: 9.7.2
      Yarn: 1.22.19
      pnpm: 8.6.9
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (next/font)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/kiuka/nextjs-font

### To Reproduce

Run npm run dev and check the output, the fonts are differ when I use the built-in variable and when I try to use it through css variable

### Describe the Bug

Not able to use the CSS variable when loading fonts through the localFont (or the google fonts) from next/font

### Expected Behavior

var(--font-source-code-pro) should be working according the documentation

### Which browser are you using? (if relevant)

Chrome 100.0.4878.0

**Comment by FourwingsY** [comment]
Yep, It seems just a fallbacks are working in development mode.
I also digging this problem.

**Comment by G9000** [comment]
any solution to this? Or bug still persist

**Comment by kiuka** [comment]
I figured meanwhile, I think its not clear in the documentation, but you have to add the class of the fonts to the body in order to use it.

So in my case:

`
import localFont from 'next/font/local';

const source_serif_pro = localFont({
  src: '../../fonts/SourceSerifPro-Black.otf',
  weight: '900',
  style: 'normal',
  variable: '--font-source-serif-pro',
});

...

      <body className={`${source_serif_pro.variable}`}>
`

And then I can use the variable in other CSS classes.
