### ISSUE TITLE
Websocket issue with latest version of NextJS

### ISSUE THREAD

**Issue by pierre-lgb** [vercel/next.js#54589]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.9
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/pierre-lgb/nextjs-custom-server-issue

### To Reproduce

1. To see the **issue** ( >= v13.4.13-canary.0)
- Download the repository
- Run `yarn install` then `yarn run dev`
- Go to http://localhost:3000
- Open dev tools in "Network" tab, then select "WS". 
You should see a lot of requests like below:
![image](https://github.com/vercel/next.js/assets/83542054/7847a212-a8cb-44ba-86af-1ffbfc71ac21)

2. To see the **expected behavior** ( < v13.4.13-canary.0)
- Change next version to next@13.1.0 : `yarn add next@13.1.0`
- Run `yarn run dev`
- Go to http://localhost:3000
- Open dev tools in "Network" tab, then select "WS".
You should see a single request like below:
![image](https://github.com/vercel/next.js/assets/83542054/20c615cb-4a06-449a-977d-760e70285012)
 

### Describe the Bug

With latest version of Next.js, websocket connection requests to the same server as the one used by Next.js are not working. The issue doesn't happen when creating a separate server on a different port (e.g. http://localhost:3001) for websocket connections.

### Expected Behavior

As shown in the second screenshot, a single request should be made and stay pending.

**Comment by pierre-lgb** [comment]
After trying different versions, it seems that the issue appeared between v13.4.12 and v13.4.13-canary.0. I downgraded `next` to `v13.14.2` and it's working well.

**Comment by hvqzao** [comment]
I'm facing the same issue.
Issue confirmed in `next@13.4.16` and `next@13.4.19`. Application worked properly up to (including) `next@13.4.12`.
I'm not using `app` folder, only `pages`.

**Comment by beckinator-cenith** [comment]
I'm having the same issue as well. All websocket connections to the custom server are prematurely closed causing the app to try new connections. In `next@3.4.13` (including the canary releases) there is a server side exception saying there was an error proxying the request: `Failed to proxy http://127.0.0.1:35453/ Error: socket hang up`. `next@3.4.14 - next@3.4.20-canary.15` (latest version available right now) there's no server side exception logged just client side exceptions stating the websocket closed prematurely with an ambiguous code 1006. Without a workaround or fix, any next version above `next@3.4.12` is unusable with a custom server using websockets.

**Comment by RonaldErnst** [comment]
Still not working in `next@13.5.x`

**Comment by huozhi** [comment]
Close as duplicate as #49334, please follow up there

**Comment by RonaldErnst** [comment]
Still having the same issue when using trpc's websockets. I'm using a custom server that is also running a WS server on top.
Adding the following to `next.config.js` did not work:
```javascript
experimental: {
    serverComponentsExternalPackages:['@trpc/server', '@trpc/next', "ws", "@trpc/react-query"]
},
```
This issue might not be related to server components since I'm using the `pages` directory and appears not to depend on the WS library.
