### ISSUE TITLE
Npm run build(next build) failed on Windows server, but works on macOs

### ISSUE THREAD

**Issue by fenes** [vercel/next.js#54607]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows Server 2022 Standard
    Binaries:
      Node: 20.5.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime), Operating System (Windows, MacOS, Linux), Package manager (npm, pnpm, Yarn)

### Link to the code that reproduces this issue or a replay of the bug

npx create-next-app

### To Reproduce

just create a new project on windows server

### Describe the Bug

When I build on macOs M1 , it works perfectly, but if I tried on windows server, error occurs.
Error :
TypeError: Cannot read properties of null (reading 'useMemo')
    at exports.useMemo (C:\XX\node_modules\react\cjs\react.production.min.js:25:208)

What am I missing?
node -version:v20.5.1
npm -version:9.8.1

### Expected Behavior

Builds perfectly, it should not be platform dependent

**Comment by pietrofxq** [comment]
I just tried to create a blank project on windows and `next dev` doesn't work there either. Localhost 3000 doesn't load anything. It works fine on Mac

**Comment by apophis51** [comment]
hey I ran that same command and also got that bug (i'm also windows)   however if I update the package by running 'npm i -g create-next-app'  before I run npx create-next-app  I get it running on windows just fine.  Give that a try?
