### ISSUE TITLE
Docs: Error 500 on Runtime Configuration page

### ISSUE THREAD

**Issue by landsman** [vercel/next.js#54637]
### What is the improvement or update you wish to see?

I noticed error 500 on the page.

### Is there any context that might help us understand?

Nope.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/next-config-js/runtime-configuration

<sub>[DX-1981](https://linear.app/vercel/issue/DX-1981/docs-error-500-on-runtime-configuration-page)</sub>

**Comment by huozhi** [comment]
Hi we fixed the 500 issue and the right link is [nextjs.org/docs/pages/api-reference/next-config-js/runtime-configuration](https://nextjs.org/docs/pages/api-reference/next-config-js/runtime-configuration). Now the bad link is returning 404 now.

Can you share where did you get that link? Seems I couldn't find it from the docs site
