### ISSUE TITLE
Server side debugging hitting incorrect lines (Typescript project)

### ISSUE THREAD

**Issue by tomitrescak** [vercel/next.js#54651]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 7.13.5
    Relevant Packages:
      next: 13.4.20-canary.9
      eslint-config-next: 13.4.4
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

Server Side

### To Reproduce

I need a guidance on how to report this. Is there any way I can debug this? I cannot see the generated source maps.

### Describe the Bug

I have fairly large project done in typescript. For some time it has been impossible to debug server side as the breakpoints are not hit. It seems like they are off by few lines. The cliend side debugging work perfectly fine.

I downloaded Replay but it seems that is captures only the client side.

I tried two ways of debugging server side as per instructions on your web page.
In VS code sometimes the correct breakpoint is hit, but already on second run it is lost.
The Chrome devtools way is a no go as it does not eve load the correct files and I cannot find my original typescript files there.

### Expected Behavior

The application hits the desired breakpoint.

**Comment by tomitrescak** [comment]
To provide more context. After fresh server restart some breakpoints are correctly hit ... from then all its all downhill. Please let me know if there is any way for me to debug it ... if not we will try to distill the repro, but it may take a lot of time as our app is huge.

**Comment by Joviks** [comment]
@tomitrescak I had the same/a similar problem, for me the "solution" appears to be a combination of deleting the dist folder (if it exists) and removing all comments from the file you want to debug. Don't ask me why this works (for us), but it does.

**Comment by tomitrescak** [comment]
Yes, this seems to be working now as well for me.
