### ISSUE TITLE
Error: `Cannot redefine property: $$id` in `action-proxy.ts`

### ISSUE THREAD

**Issue by shunkakinoki** [vercel/next.js#54655]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.1
      npm: 9.8.0
      Yarn: 1.22.19
      pnpm: 8.6.10
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

WIP

### To Reproduce

WIp

### Describe the Bug

Cannot build the action w/ the server proxy

### Expected Behavior

Builds without bug

**Comment by kristinlindquist** [comment]
In case anything short of a minimal repo helps: I also see this on 13.4.19 but not on 13.4.18. While it seems unlikely to be the cause, I am on MacOS like the OP. I'm using app router.

**Comment by shanehoban** [comment]
Also seeing this on 13.4.19 - working on 13.4.18

**Comment by matbee-eth** [comment]
Seeing it on 13.5

**Comment by rawi96** [comment]
I don't know if it helps but:

I had the same error because i was exporting the server action wrong.

/src/app/page.tsx
```
"use client";

import { myServerAction } from "./my-server-action";

export default function ClientComponent() {
  const handleClick = () => {
    console.log("console log from client");
    myServerAction();
  };

  return <button onClick={handleClick}>execute server action</button>;
}

```


/src/app/my-server-action.ts
```
"use server";

export const myServerAction = () => {
  console.log("console log from server");
};

export default myServerAction;
```

Then I realized that I was exporting the server action twice. 1x where I define the function and 1x below as default.

As soon as I only do 1 of the two and adjust the import in the tsx page accordingly, it also works on next 13.5.4

**Comment by JoshuaHull** [comment]
I was putting together a reproduction and eventually reached the same realisation as rawi96 - if you have a file with the `"use server"` directive which is exporting a component/action once named and again as a default, you will hit this issue.

I've removed all instances of double exporting and am happily building on 13.5.

```tsx
"use server";

export const ProblematicComponent = () => {
  return <div>I am breaking the build on 13.5+ as I am exported twice</div>;
}

export default ProblematicComponent;
^^^^^^^ remove me
```

Reproduction is here:
https://github.com/JoshuaHull/nextjs-54665-repro

**Comment by lisboaa** [comment]
@JoshuaHull Nice, this really was a problem, I made the modification and it worked.

**Comment by collinversluis** [comment]
> I was putting together a reproduction and eventually reached the same realisation as rawi96 - if you have a file with the `"use server"` directive which is exporting a component/action once named and again as a default, you will hit this issue.
> 
> I've removed all instances of double exporting and am happily building on 13.5.
> 
> ```tsx
> "use server";
> 
> export const ProblematicComponent = () => {
>   return <div>I am breaking the build on 13.5+ as I am exported twice</div>;
> }
> 
> export default ProblematicComponent;
> ^^^^^^^ remove me
> ```
> 
> Reproduction is here: https://github.com/JoshuaHull/nextjs-54655-repro

Nice! This solves it for me. Odd but working. Thanks!

**Comment by samislam** [comment]
I am using the latest version of nextjs with the ap14p router.
Version 14.0.3 as of the time of writing the comment.

The problem in my case was a file in my source code which had the "use server" declarative, which was exporting a named export and a default export of the same variable.

```tsx
"use server"
export const SelectCompany = ()=> <div></div>
export default SelectCompany
```

The solution was to either use `export default` or `export const`. 
I removed the named export `export const`. And failed back to the default export, and the error message went away.

Anyway, it's a bug. But that's one work-around which may help someone to survive during development.

**Comment by chriscarrollsmith** [comment]
> I don't know if it helps but:
> 
> I had the same error because i was exporting the server action wrong. It worked on 13.4.18 but not on 13.4.19 and higher.
> 
> /src/app/page.tsx
> 
> ```
> "use client";
> 
> import { myServerAction } from "./my-server-action";
> 
> export default function ClientComponent() {
>   const handleClick = () => {
>     console.log("console log from client");
>     myServerAction();
>   };
> 
>   return <button onClick={handleClick}>execute server action</button>;
> }
> ```
> 
> /src/app/my-server-action.ts
> 
> ```
> "use server";
> 
> export const myServerAction = () => {
>   console.log("console log from server");
> };
> 
> export default myServerAction;
> ```
> 
> Then I realized that I was exporting the server action twice. 1x where I define the function and 1x below as default.
> 
> As soon as I only do 1 of the two and adjust the import in the tsx page accordingly, it also works on next 13.5.4

D'oh! Thanks for this. Turns out I had two export statements; one in the function declaration, and one at the end of the file. So, in effect, the server action was being redundantly initialized.

**Comment by auipga** [comment]
Thank you all! That helped.

Here is another case:

Wrong:
```ts
export const ping = some_fn
```
Correct:
```ts
export const ping = async () => await some_fn()
```

**Comment by steve-marmalade** [comment]
I am getting a similar error after upgrading from [v14.1.1-canary.9](https://github.com/vercel/next.js/releases/tag/v14.1.1-canary.9) to [v14.1.1-canary.10](https://github.com/vercel/next.js/releases/tag/v14.1.1-canary.10)

> TypeError: Cannot redefine property: $$id
    at Function.defineProperties (<anonymous>)
    at t.registerServerReference (/var/task/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:12:172882)
    at p (/var/task/.next/server/chunks/4491.js:6:132184)
    at 49364 (/var/task/.next/server/app/p/[dynamic]/s/[slug]/page.js:418:372)
    at Function.t (/var/task/.next/server/webpack-runtime.js:1:127)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async s (/var/task/.next/server/app/p/[dynamic]/s/[slug]/page.js:98:5427)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:16:408
    at async rg (/var/task/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:15:6309)
    at async rJ (/var/task/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:16:25525)

**Comment by jelling** [comment]
If anyone is using NX framework, here is another way this issue can happen:

- `serverActionX` is exported from `/server`
- this requires use `use server` at top of file
- but inside `serverActionX.ts` there is also a `use server` at the top.

Solution: remove `use server` from the implementation file. Doing the opposite will not work.
