### ISSUE TITLE
Suspense in production is blocking rather than showing fallback UI

### ISSUE THREAD

**Issue by Vk-jangid** [vercel/next.js#54667]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.20.2
      npm: 8.19.4
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.16
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

n/a

### To Reproduce

Just create a component in the page.js and wrap any internal component with Suspense and add a fallback UI.
Deploy the application on the ec2 server with the "next build" & "next start".
The fallback UI doesn't come on the client side instead it waits for the complete UI to load.

### Describe the Bug

I am facing an issue with the suspense streaming.

I have used suspense in the page.js and added a fallback UI for that (not using loading.js and instead using suspense in the component itself)
Everything is working fine in the DEV environment but in the PROD the suspense fallback is not showing at all instead it is waiting for the complete UI to load.

It is ruining the complete UX for the users as the user doesn't know that some background process is ongoing.

### Expected Behavior

As soon as the navigation starts or refreshes the page, the loading fallback UI should show up.

**Comment by pstachula-dev** [comment]
Have same problem after upgade from: 
13.4.8 to 13.4.19 - now with Supspense/or not - server component blocks whole page

**Comment by youweol-master** [comment]
I have similar problem in 13.4.19.
when use Suspense in production，the component inside<Suspense> will display only after interaction with the page，for example click the page or scroll.

**Comment by pstachula-dev** [comment]
I found a solution to make Suspense work properly on normal pages that are not dynamic, e.g. [id].

You must have it enabled:
`export const dynamic = "force-dynamic";`

And page must not have:
`'use client'`

**Comment by wscotten** [comment]
Still seeing this issue in 15.2.  Blocking my upgrade atm.

**Comment by raphaelbadia** [comment]
I noticed the same issue. I realized that it was caused by an issue with tree shaking (#55943). 

My loading page included one small component from my component library, that pulled my whole package and made the loading.js so heavy that next hadn't the time to load the loading suspense boundary. 

At least that's how I understand it.

**Comment by TheBaronRojo** [comment]
Hello, i have the same issue in next 13.5.4 when is deployed in AWS Amplify. This problem doesn't happens in dev mode or running local build.

I developed a project using suspense and loading.jsx. 

Loading.jsx fallback is perfect, but with suspense in Aws Amplify, the page frozes and doesn't show the fallback, when the loading finish, the suspense show their children.

My repository

[https://github.com/TheBaronRojo/Loadingtest](url)

And the Aws Amplify project

[https://master.d3mh90mxynovfi.amplifyapp.com/suspense/subsuspense](url)

**Comment by jvandenaardweg** [comment]
Found out i'm experiencing the same.

To quote myself, with a reproduction case:

> #54667



> I guess my issue lies in the use of `<Suspense>` on a page to have fine grained control over what component is loading, instead of a page wide loading indicator.
> 
> Using Vercel's app router demo to demonstrate:
> 
> No issue here when using a generic loading.tsx file: https://app-router.vercel.app/loading
> 
> But the issue is here "Streaming with Suspense": https://app-router.vercel.app/streaming
> 
> When you throttle the connection, using loading.tsx instantly shows a indicator. Which is good. But using the same throttled connection on the Streaming With Suspense demo prevents anything from being shown until a certain point. Not really clear when that exactly is.
> 
> Both also tested with the latest NextJS version locally and with a deploy on Vercel.
> 
> So the issue lies in the use of `<Suspense>` with a fallback on a page.tsx. When I switch over to using the loading.tsx the issue dissapears in my project. But that's not what I hoped, I really want to use the Suspense fallback on a per component basis and not have a loading.tsx on the page level.
> 
> edit: issue about this: #54667

**Comment by jvandenaardweg** [comment]
> I found a solution to make Suspense work properly on normal pages that are not dynamic, e.g. [id].
> 
> You should have it enabled: `export const dynamic = "force-dynamic";`

Tried this, but it does not work. When you throttle the network connection you'll still see the same behaviour: the loading indicator is not instant or will not show up.

**Comment by jvandenaardweg** [comment]
@Vk-jangid or @leerob  can you remove the label `please add a complete reproduction` ? There's a reproduction case in my comment above

**Comment by imaxisXD** [comment]
So its a bug I was struggling with my code , thanks @jvandenaardweg  for sharing a live example

**Comment by Jordaneisenburger** [comment]
Having the same issue as the OP, I have multiple components wrapped in `Suspense` inside a `page.tsx` marked it with "force-dynamic" but when I click on a link that navigates to that page, nothing happens and the site looks unresponsive and only navigates once all the Suspense boundaries are resolved. 

In local development it works as expected Link navigates instantly and I see the fallback UI, smells like a Vercel hosting issue.

**Comment by pstachula-dev** [comment]
@Jordaneisenburger 

Do you have `'use client'` in that page.tsx?

**Comment by Jordaneisenburger** [comment]
@pstachula-dev the `page.tsx` itself doesn't have `'use client'` but it has multiple client components inside `Suspense` boundaries. According to the NextJS docs from a `page.tsx` you can pass a promise to the components like so `const dataPromise = getData(slug, searchParams);` I thought this might the issue as maybe it somehow tries to resolve it already.

But here is where its gets weird: It works on iphones and Macbooks and locally on my windows but when hosted on vercel it doesn't work on windows (all in chrome)

**Comment by Jordaneisenburger** [comment]
> Found out i'm experiencing the same from a different issue here: [#43548 (comment)](https://github.com/vercel/next.js/issues/43548#issuecomment-1755556341)
> 
> To quote myself, with a reproduction case:
> 
> > I guess my issue lies in the use of `<Suspense>` on a page to have fine grained control over what component is loading, instead of a page wide loading indicator.
> > Using Vercel's app router demo to demonstrate:
> > No issue here when using a generic loading.tsx file: https://app-router.vercel.app/loading
> > But the issue is here "Streaming with Suspense": https://app-router.vercel.app/streaming
> > When you throttle the connection, using loading.tsx instantly shows a indicator. Which is good. But using the same throttled connection on the Streaming With Suspense demo prevents anything from being shown until a certain point. Not really clear when that exactly is.
> > Both also tested with the latest NextJS version locally and with a deploy on Vercel.
> > So the issue lies in the use of `<Suspense>` with a fallback on a page.tsx. When I switch over to using the loading.tsx the issue dissapears in my project. But that's not what I hoped, I really want to use the Suspense fallback on a per component basis and not have a loading.tsx on the page level.
> 
> So, to summarize:
> 
> 1. Go to https://app-router.vercel.app/streaming
> 2. Throttle your connection in Dev Tools, using slow/fast 3G or something
> 3. Click "Edge Runtime" tab (or Node Runtime, it doesn't really matter which one)
> 
> You'll notice it takes a while to load but the Suspense fallback loading indicator will not show up. Where you would expect to have that loading indicator to be shown instantly, like with a page wide loading.tsx
> 
> Code: https://github.com/vercel/app-playground/tree/main/app/streaming
> 
> I think this is because the code for showing the fallback lives on the server, instead of the client? So it needs to do a fetch first to even know if it should show a loading indicator. But that's a big issue when you have a sub optimal connection, which can happen anywhere. So wether to show a loading indicator or not should live in the client, not the server. Or should be known already by using the prefetch in the background on page load. Please correct me if i'm wrong on any of this, I'm kinda guessing here as I don't know much about the NextJS/React internals.

Even on a fast 1GB connection if I go to https://app-router.vercel.app/streaming and click on either "Edge Runtime" or "Node Runtime" nothing happens and then after x amount of time we navigate to the page we clicked on.

**Comment by ernestograndoli** [comment]
I have the same issue. I'm working with next Js lastest version, when I code in my localhost everything is working as expecting, also in vercel I have not trouble to see the loading fallback in suspect component. But when I deploy to Amplify is not working. Actually I tried adding a delay for 8 second to try if in any time load my components but Im only can see the page is loading in browser tab and the page render after the delay is done. I don't know what to try. I set the build Amplify to use a node js docker image version 18 and the last version of next Js but is not working. If anyone have a solution appreciate it.

**Comment by AlexKvazos** [comment]
I can confirm the same issue on Digital Ocean.

**Comment by ernestograndoli** [comment]
I solved using a loading.tsx from next and then the suspense where I want to use it. But if you put the suspense in you page without loading previously I think next still waiting to render the page from the server and for that you can see you suspense loading. Maybe is a posible solution.

**Comment by ChristophWolfPCG** [comment]
I'm having the same issue. Suspense works fine when running npm build and start locally, even after deleting buildDir.

@ernestograndoli can you elaborate? i can't quite follow

**Comment by blenky36** [comment]
I've been experiencing issues with `<Suspense />` blocking page navigations from server components. This sample repo demonstrates the page being blocked until all async actions in a server component are resolved, even when wrapped in a `<Suspense />`. 

Is this a bug or am I lacking understanding of intended functionality? 

https://suspense-broken-demo.vercel.app/
https://github.com/blenky36/suspense-broken-demo

**Comment by Sathosk** [comment]
I'm facing the same issue, I'm using docker with the dockerfile provided by vercel repository, it works locally the production build, but when I run the container on an EC2 machine the suspense doesn't work, so the page blocks until fully rendered on the server instead of streaming the component.

I have tried using force-dynamic with no success. Anybody has any clue as to why this happens?

**Comment by siduck** [comment]
anyone found a workaround yet? mine works on vercel but not on other hosting platforms

**Comment by Charlesgln** [comment]
Same problem here,works well in dev mode but once deployed into aws suspense blocking.

**Comment by siduck** [comment]
> Same problem here,works well in dev mode but once deployed into aws suspense blocking.

same with azure here man, we got to make the site production ready in few days and this issue's a real blocker.  Its weird that it works when hosted on vercel

**Comment by leerob** [comment]
1. Can you reproduce on your local machine with the same setup you are deploying to production?
2. For example, are you using Docker with the [provided Dockerfile example](https://github.com/vercel/next.js/tree/canary/examples/with-docker)? I am assuming this is not a static export.

It would be helpful to verify that a Dockerized app running locally can or cannot reproduce this.

**Comment by Jordaneisenburger** [comment]
> 1. Can you reproduce on your local machine with the same setup you are deploying to production?
> 2. For example, are you using Docker with the [provided Dockerfile example](https://github.com/vercel/next.js/tree/canary/examples/with-docker)? I am assuming this is not a static export.
> 
> It would be helpful to verify that a Dockerized app running locally can or cannot reproduce this.

Hi @leerob as mentioned above this issue also happens on https://app-router.vercel.app/streaming if you open this link in a incognito tab and click on the "Edge runtime" button you can see that it blocks navigation. I believe this to be Vercels demo environment should this be sufficient as a reproduction environment ?

**Comment by eeek76** [comment]
> Hello, i have the same issue in next 13.5.4 when is deployed in AWS Amplify. This problem doesn't happens in dev mode or running local build.
> 
> I developed a project using suspense and loading.jsx.
> 
> Loading.jsx fallback is perfect, but with suspense in Aws Amplify, the page frozes and doesn't show the fallback, when the loading finish, the suspense show their children.
> 
> My repository
> 
> [https://github.com/TheBaronRojo/Loadingtest](url)
> 
> And the Aws Amplify project
> 
> [https://master.d3mh90mxynovfi.amplifyapp.com/suspense/subsuspense](url)
> 
> "Update"
> 
> In Vercel this problem doesn't happen
> 
> [https://loadingtest.vercel.app/](url)

@leerob

**Comment by Sathosk** [comment]
> 1. Can you reproduce on your local machine with the same setup you are deploying to production?
> 2. For example, are you using Docker with the [provided Dockerfile example](https://github.com/vercel/next.js/tree/canary/examples/with-docker)? I am assuming this is not a static export.
> 
> It would be helpful to verify that a Dockerized app running locally can or cannot reproduce this.

@leerob Yes, I am actually running the exact same image that is being used on production. I have even tried building the image on the EC2 machine and running it locally to see if there was any difference and it works locally but not on the EC2 machine. I use standalone output.

Due to this issue, I had to withdraw from doing fetch calls on server components whenever there's a http request, instead, I am forced to doing it in a client component since I can't find a solution that works in production on the EC2.

**Comment by siduck** [comment]
> > 1. Can you reproduce on your local machine with the same setup you are deploying to production?
> > 2. For example, are you using Docker with the [provided Dockerfile example](https://github.com/vercel/next.js/tree/canary/examples/with-docker)? I am assuming this is not a static export.
> > 
> > It would be helpful to verify that a Dockerized app running locally can or cannot reproduce this.
> 
> @leerob
> 
> 1. No,  I am actually running the exact same image that is being used on production. I have even tried building the image on the EC2 machine and running it locally to see if there was any difference and it works locally but not on the EC2 machine.  The suspense only fail to work on the EC2 machine.
> 2. Yes I am using this example. I'm using standalone export.
> 
> Due to this issue I had to withdraw from doing fetch calls on server components, instead, I am forced on doing it in a client component since I can't find a solution that works in production on the EC2.

i face similar issue but it works on our vercel hosting , not the azure hosting. so we moved to vercel hosting temporarily

**Comment by KoaLaYT** [comment]
After I [disabled buffering in Nginx conf](https://github.com/vercel/ai/issues/215#issuecomment-1605363922), it works.

**Comment by Sathosk** [comment]
> After I [disabled buffering in Nginx conf](https://github.com/vercel/ai/issues/215#issuecomment-1605363922), it works.

In my case, we don't have an Nginx server running behind the container. Instead, we have AWS API Gateway pointing to it. I'm not sure if there is a way to disable proxy buffering on the gateway, but I believe it's not an option for us.

**Comment by siduck** [comment]
> After I [disabled buffering in Nginx conf](https://github.com/vercel/ai/issues/215#issuecomment-1605363922), it works.

can confirm this fixed issue with out azure vm too

**Comment by Vk-jangid** [comment]
> After I [disabled buffering in Nginx conf](https://github.com/vercel/ai/issues/215#issuecomment-1605363922), it works.

I am using AWS and suspense is now working after disabling the buffering in nginx.

**Comment by leerob** [comment]
Thanks folks! Made a PR to add this note to disable buffering for self-hosting with streaming in the docs.

**Comment by syed-yawar** [comment]
> Hello, i have the same issue in next 13.5.4 when is deployed in AWS Amplify. This problem doesn't happens in dev mode or running local build.
> 
> I developed a project using suspense and loading.jsx.
> 
> Loading.jsx fallback is perfect, but with suspense in Aws Amplify, the page frozes and doesn't show the fallback, when the loading finish, the suspense show their children.
> 
> My repository
> 
> [https://github.com/TheBaronRojo/Loadingtest](url)
> 
> And the Aws Amplify project
> 
> [https://master.d3mh90mxynovfi.amplifyapp.com/suspense/subsuspense](url)
> 
> "Update"
> 
> In Vercel this problem doesn't happen
> 
> [https://loadingtest.vercel.app/](url)

@TheBaronRojo Have you found the solution for this on AWS Amplify?

**Comment by TheBaronRojo** [comment]
@syed-yawar Hello, No, I still haven't found a solution
