### ISSUE TITLE
Broken Features Associated with --experimental-https

### ISSUE THREAD

**Issue by jd-carroll** [vercel/next.js#54696]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 3.6.2
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.20-canary.8
      eslint-config-next: 13.4.20-canary.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

Check steps below

### To Reproduce

1) `create-next-app --typescript`
2) `npm install next@canary`
3) Create a (fictional) middleware handler:
```typescript
export function middleware(request: NextRequest) {
  const pathname = request.nextUrl.pathname;
  if (pathname ===  '/') {
    return;
  }
  const localizedPath = '/'; // any magic path you want
  const localizedUrl = new URL(localizedPath, request.url);
  return NextResponse.rewrite(localizedUrl);
 }
```
4) Run `next dev --experimental-https` with the appropriate certs (or locally generated)
5) Navigate to any non-root path

### Describe the Bug

The specific issue above is that when using `--experimental-https` && middleware which rewrites the url, the incoming `request.url` has an `http` protocol but you still need to re-write the url with `https`.

There are quite a number of places where it appears `http://` is hard coded:
1) server-ipc (this bug)
2) next-image-loader
3) app-renderer
4) metadata resolvers
5) api-utils
6) ....

I am not familiar enough with all of these utilities to say for sure if these are bugs or not.

Additionally, there seems to be a repeated use of `http://n` in URL construction that I do not completely follow.

However...

### Expected Behavior

I would expect that all features available on the standard `http` dev server to work for `https`

More specifically to the reproduction steps, **I would expect the protocol of the incoming request url passed to middleware on a dev server to match the protocol of web server host.**

<sub>[NEXT-1572](https://linear.app/vercel/issue/NEXT-1572/broken-features-associated-with-experimental-https)</sub>

**Comment by OlegLustenko** [comment]
Got the same issue and made a work around for dev env

**Comment by ztanner** [comment]
Hi @jd-carroll , I can no longer reproduce the middleware issue via your repro steps. We've removed the internal IPC workers so it seems likely that this was fixed in the latest version of Next. Going to close this out, but if you're still encountering the issue, please reply with a reproduction and I can take a look.
