### ISSUE TITLE
non-pre-generated dynamic pages will cause unexpected hard refresh when routing on Vercel via `generateStaticParams`

### ISSUE THREAD

**Issue by Howard86** [vercel/next.js#54698]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 16.20.0
      npm: 8.19.4
      Yarn: 1.22.19
      pnpm: 8.6.7
    Relevant Packages:
      next: 13.4.20-canary.11
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Data fetching (gS(S)P, getInitialProps), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Howard86/vercel-nextjs-dynamic-path-reload/tree/main

### To Reproduce

This issue only happens when deploying on Vercel, running it locally will not have issues.

1. (Optional) clone this [repo](https://github.com/Howard86/vercel-nextjs-dynamic-path-reload) and deploy to a Vercel project
2. Access pathname [/dynamic/two](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/two) on a browser 
3. Open browser network tab on the side
4. Click `toggle` button (this will call `router.push` on the same `pathname` appending new search params)
5. It will unexpectedly cause the whole page to hard refresh and land on [/dynamic/two?modal=1](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/two?modal=1) with a black modal open

Following the same step above on [/dynamic/one](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/one) will not cause the hard refresh.

### Describe the Bug

Browser unexpectedly hard refreshes when using `router.push` or `router.replace` to the same `pathname` with a search param on a non-pre-generated dynamic path via `generateStaticParams`

e.g. 
- on `/app/dynamic/[text]/page.tsx`, we are adding `generateStaticParams` to only pre-generate `/dynamic/one` without `/dynamic/two`. Also adding a `toggle` button so it uses `router.push` to the same `pathname` appending some `searchParams` (e.g. [/dynamic/two](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/two) to [/dynamic/two?modal=1](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/two?modal=1))
- Clicking `toggle` button on path [/dynamic/one](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/one) will work fine
- Clicking `toggle` button on path [/dynamic/two](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/two) will cause hard refresh

However, when cling the `toggle` button again on path [/dynamic/two?modal=1](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/two?modal=1) to navigate to [/dynamic/two](https://vercel-nextjs-dynamic-path-reload.vercel.app/dynamic/two)) to close the modal, it will work smoothly without hard refresh.

Note: 
- This only happens when deploying on Vercel, running it locally with `npm run build && npm run start` will work fine
- Such modal behaviour is controlled by a client-side component [ModalWrapper](https://github.com/Howard86/vercel-nextjs-dynamic-path-reload/blob/main/app/ModalWrapper.tsx) using `useSearchParams`, which is used in [root layout](https://github.com/Howard86/vercel-nextjs-dynamic-path-reload/blob/main/app/layout.tsx#L18) together with `Suspense`
- By completely removing `generateStaticParams`, both dynamic pages will work fine (e.g. [/dynamic/one](https://vercel-nextjs-dynamic-path-reload-git-bugfix-re-e46c12-howard86.vercel.app/dynamic/one) &  [/dynamic/two](https://vercel-nextjs-dynamic-path-reload-git-bugfix-re-e46c12-howard86.vercel.app/dynamic/two)  deployed via a preview on a new [branch](https://github.com/Howard86/vercel-nextjs-dynamic-path-reload/tree/bugfix/remove-generate-static-params) 

### Expected Behavior

Browser should not hard refresh when using `router.push` or `router.replace` to the same `pathname` with a search param on a non-pre-generated dynamic path via `generateStaticParams`

More specifically,
- Developers should be able to use `router.push` and `router.replace` on dynamic path, and controls UI behaviours with `useSearchParams` regardless usage of  `generateStaticParams`
- Users should be able to navigate on dynamic paths without hard refreshes

### Which browser are you using? (if relevant)

Should not be relevant but tested with Safari 16.5, Chrome 116.0.5845.110, Firefox 109.0.1

### How are you deploying your application? (if relevant)

Vercel

NEXT-1585

**Comment by anttiriski** [comment]
I am experiencing the same bug on Vercel production builds. Non pre-generated pages hard refresh many times a second and the page is completely unaccessible. Pages generated in the build time behave correctly.

**Comment by meerface** [comment]
Hi all, we are experiencing this bug too!
