### ISSUE TITLE
Testmode playwright breaks when `setExtraHTTPHeaders` is called

### ISSUE THREAD

**Issue by joshuajaco** [vercel/next.js#54706]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.4.0
      npm: 8.12.1
      Yarn: 1.22.19
      pnpm: 7.2.1
    Relevant Packages:
      next: 13.4.20-canary.11
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/joshuajaco/next-testmode-playwright-issue

### To Reproduce

Checkout [this repository ](https://github.com/joshuajaco/next-testmode-playwright-issue) and run `npm run test`.
This will run the playwright tests which fail with the following error:
```
[WebServer] - error Error: No test info
```

### Describe the Bug

When calling `page.setExtraHTTPHeaders` inside of a playwright test, the testmode breaks.
This is because the `Next-Test-Proxy-Port` and `Next-Test-Data` headers are removed.

Also, for some reason `extraHTTPHeaders` is `undefined` in my test, so even when spreading `extraHTTPHeaders` does not work.
```ts
await page.setExtraHTTPHeaders({ ...extraHTTPHeaders });
```

Related to https://github.com/microsoft/playwright/issues/26751

### Expected Behavior

Either `page.setExtraHTTPHeaders` does not remove the testmode headers or `extraHTTPHeaders` contains the headers so we can spread them when calling `page.setExtraHTTPHeaders`.

**Comment by joshuajaco** [comment]
@dvoytenko any ideas on how to fix this?

As a workaround we currently set the headers ourselves again whenever we call `page.setExtraHTTPHeaders`:

```ts
await page.setExtraHTTPHeaders({
  ...extraHTTPHeaders,
  'Next-Test-Proxy-Port': String(_nextWorker.proxyPort),
  'Next-Test-Data': testInfo.testId,
  'Custom': 'foo',
});
```

**Comment by dvoytenko** [comment]
@joshuajaco I see the issue. Yeah, I think it's probably possible to fix this via `page.route()`. Let me try that.

**Comment by dvoytenko** [comment]
@joshuajaco this should fix the issue: https://github.com/vercel/next.js/pull/55087
