### ISSUE TITLE
`x-invoke-path` doesn't exist on `headers()` when running on Vercel.

### ISSUE THREAD

**Issue by Issaminu** [vercel/next.js#54711]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed Aug 23 17:46:49 UTC 2023
    Binaries:
      Node: 20.5.1
      npm: 9.8.1
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Issaminu/skyline-app/tree/new-skyline

### To Reproduce

* Run the repo locally => check the title of your tab in the browser, it's the same as the route you're currently on.
* Deploy the repo to Vercel => check the title of your tab in the browser, it becomes `DefaultTitle` for all routes, which is wrong.

### Describe the Bug

[The `generateMetadata()` function in `/app/layout.tsx` has a `headers()` call ](https://github.com/Issaminu/skyline-app/blob/f3effa3038aa6faad0e913b5bbcd55090050be33/app/layout.tsx#L14)to get list of headers that came with the request. it then uses the `x-invoke-path` to catch the current route. the route is then prettified a bit (simple string manipulation) and finally the `title` is returned from `generateMetadata`. 
The goal of this is to dynamically set the `title` of the page depending on it's route.
For example `/store/hoodies/dark` would become into title: `Store › Hoodies › Dark`.
This works well in a local server. But when deploying to Vercel, the invoked `headers()` no longer contains the `x-invoke-path` property, which is what I'm using to know which route the user is on.
 

### Expected Behavior

I expect `headers()` to contain `x-invoke-path` when running on a Vercel deployment.

### How are you deploying your application? (if relevant)

Vercel

**Comment by Issaminu** [comment]
Original discussion: #50189.

**Comment by balazsorban44** [comment]
The repo is private, so I cannot see your code. But in any case, `generateMetadata` receives all the parameters that you can use to generate the title you want. See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#parameters

For static (not relying on dyn) metadata, using `metadata` is [recommended](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#generatemetadata-function:~:text=If%20metadata%20doesn%27t,rather%20than%20generateMetadata).

`x-invoke-path` is not a documented API and should not be relied on.

**Comment by Issaminu** [comment]
@balazsorban44 Sorry I forgot the repo is private, [here's a gist for the generateMetadata function](https://gist.github.com/Issaminu/a2592d809cc8a7b497c8ec5d8f611945).
As for the solution you've provided, I think you may have misunderstood what I'm trying to do. I'm trying to **automatically generate the `title` property for all routes in `generateMetadata` based on the page's URL.** 
The idea is to extract the URL from `headers()` (or maybe the Request object), then do some string manipulation to turn the string **`www.example.com/home/dashboard`** into the `title` becoming **`Home › Dashboard`**.

`generateMetadata` **only receives the params for dynamic routes**, which, while useful, does not work with static routes.
`export const metdata` also doesn't work as well as it has to be added to every single page in the app. which is a huge annoyance for apps with hundreds/thousands of pages.

The workaround that  [@jmacbhc suggested](https://github.com/vercel/next.js/discussions/50189#discussioncomment-6597167) is utilizing `headers()` and accessing the `x-invoke-path` property to get the path. **This solution doesn't work when deploying on Vercel.**.

**The solution to this issue is basically an equivalent of `usePathname()` that can work in Server Components.**

**Comment by lushkant** [comment]
+1 for this, This should be officially supported come on 😅

**Comment by Issaminu** [comment]
Update: as [@iamursky suggested](https://github.com/vercel/next.js/discussions/50189#discussioncomment-6899338), injecting the pathname into the request headers while it's still in the middleware makes it possible to capture it in `layout.tsx`.

`middleware.ts`:
```ts
const requestHeaders = new Headers(req.headers);
const pathname = req.nextUrl.pathname;
requestHeaders.set("x-url", pathname);
```
`app/layout.tsx`:
```tsx
export async function generateMetadata({ params }: any): Promise<Metadata> {
  const headersList = headers();
  const pathname = headersList.get("x-url") || "DefaultTitle";
  const title = prettifyPathname(pathname);
  return { title: title };
}
```
Although I should stress that this is just a workaround, and **it does not actually solve the issue at hand**. The limits on what's `generateMetadata` has access to IS constraining, and it's should not be the case that a `headers()` call behaves differently depending on wether it's running locally or deployed to Vercel.

**Comment by lbittner-pdftron** [comment]
+1 - this issue should not be closed. This issue is blocking us from migrating to app directory. Additionally, the above workaround does not work for me.

**Comment by Issaminu** [comment]
@lbittner-pdftron Have you verified that your middleware does indeed run?

It's possible that the reason you don't get a `x-url` header in your `layout.tsx` is that your middleware function didn't even run, possibly due to [your `matcher` configuration](https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher).
