### ISSUE TITLE
`process.version` is undefined in app dir route

### ISSUE THREAD

**Issue by Perfect7M** [vercel/next.js#54739]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.12
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/platforms/tree/main

### To Reproduce

1. Install https://github.com/octokit/octokit.js into project. 
2. Import it in `app/api/generate/route.ts`
3. Make a call to that endpoint and get 500

### Describe the Bug

`process.version` is not available in app router api endpoint

### Expected Behavior

`process.version` is available like many nodejs libraries expect

**Comment by balazsorban44** [comment]
`process.version` is a Node.js API, while you are referring to an endpoint that is configured to use the Edge runtime instead.

https://github.com/vercel/platforms/blob/7ded19df0220acad5ae4280f9ebc139bcb1fa64c/app/api/generate/route.ts#L11

Ref: https://nodejs.org/api/process.html#processversion
