### ISSUE TITLE
Form are being submitted twice in nextjs canary

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#54746]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.0.0: Fri Aug 18 00:02:20 PDT 2023; root:xnu-10002.1.11~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.7
    Relevant Packages:
      next: 13.4.20-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Fredkiss3/nextjs-form-double-submission

### To Reproduce

1. Clone the project and run it 
2. Go to the link `/other` and then navigate back (either with the back button or link in the header)
3. Click on the `submit` button of the form
4. Observe the network tab

https://github.com/vercel/next.js/assets/38298743/48f7da51-7239-4719-acc0-2898444c4e74

### Describe the Bug

When a user navigates aways and back with `next/link` and resubmits a form which uses a server action, the form get submitted twice. 

This error seems to have appeared in `next@13.4.20-canary.1`, up to  `next@13.4.20-canary.0` it was working as expected

### Expected Behavior

The form should only ever be submitted once, not twice.

<sub>[NEXT-1589](https://linear.app/vercel/issue/NEXT-1589/form-are-being-submitted-twice-in-nextjs-canary)</sub>

**Comment by user-0a** [comment]
This still appears to be broken (updated to `"next": "13.4.20-canary.21"`)

**Comment by ztanner** [comment]
Hi @user-0a , could you open a new issue with a reproduction? Testing these changes with the latest canary against the initially submitted repro, and the action only posts once:

https://github.com/vercel/next.js/assets/1939140/e9ea5e5e-178b-4bec-bf5c-bf1fe32b7860

**Comment by OtisTemler** [comment]
Maybe related (?) https://github.com/vercel/next.js/issues/55805 (even though not using form actions...)
