### ISSUE TITLE
router.push has no way to refresh the page completely

### ISSUE THREAD

**Issue by raphaelbadia** [vercel/next.js#54766]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
yarn run v1.22.19
$ /private/tmp/router-push-replace/node_modules/.bin/next info

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.8
    Relevant Packages:
      next: 13.4.20-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A


✨  Done in 2.28s.
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Data fetching (gS(S)P, getInitialProps)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/raphaelbadia/router-push-refresh/blob/main/app/login/page.tsx#L21

### To Reproduce

Clone and open the [reproduction](https://github.com/raphaelbadia/router-push-refresh) the navigate to the "login" page a login.

The layout is updated.

Open the file `app/login/page.tsx` at line `21` and comment the `router.refresh()` line.
Do the same for the file `app/logout/page.tsx` at line `18`.

Refresh the page. Try to logout and login. The UI is not updated anymore.

### Describe the Bug

Having to call both `router.push()` and `router.refresh()` to get a full page reload when changing the page is cumbersome and can lead to errors, as `router.push` is not guaranteed to be done before `router.refresh()` kicks in : it could lead to refreshing the wrong page.

### Expected Behavior

It would be nice to have an option to do `router.push('/', { refresh: true })` to tell Nextjs to refresh the whole page including the layout for login/logout scenarios.

**Comment by Abdullah-SoftDev** [comment]
Yeah i tried this, getting same problem. I think you should try it using server action.

**Comment by devjiwonchoi** [comment]
@Abdullah-SoftDev Server Actions don't handle client-side js.

@raphaelbadia Do you mean something like `window.location.reload()` on the client side, but in Server Components?

**Comment by timneutkens** [comment]
Have a look at this discussion in which I've explained the expected behaviors: https://github.com/vercel/next.js/discussions/54075

**Comment by raphaelbadia** [comment]
@devjiwonchoi not in server side, I'd like to have something like `window.location.replace('/home')` baked inside Nextjs, that refreshes the whole react tree to avoid a full page refresh. 

Currently if I try to use `router.replace('/home')` or `router.push('/home')` after logging in, it won't refresh the layout.

I have to do 
```
router.push(`/home`)
router.refresh(); // refresh the layout
```
