### ISSUE TITLE
Global context & data is lost between custom server and Next.js router/renderer

### ISSUE THREAD

**Issue by coltonehrman** [vercel/next.js#54782]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.20-canary.12
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router, Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime), Standalone mode (output: "standalone")

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/relaxed-phoebe-jncmvg

### To Reproduce

1. Use `next` version `13.4.13` or higher
2. Setup a custom server.
3. Use `nconf` (a singleton module)
4. Modify `nconf` store in custom server.
5. Try to access the modified `nconf` object in Next.js context. (ie: pages/, app/, gSSP, API route, etc.)

### Describe the Bug

All global context and data is lost between the custom server context and the Next.js context.

As you can see below, the global (singleton) module was cached and worked across the custom server and Next.js gSSP in **13.4.12**, but doesn't work in versions **13.4.13** or higher.

#### Custom server code
<img width="770" alt="Screenshot 2023-08-31 at 9 57 18 AM" src="https://github.com/vercel/next.js/assets/12456288/3226ff0b-ea37-49f5-8b4e-1be6bc59020f">

#### Next.js 13.4.12
<img width="1800" alt="Screenshot 2023-08-31 at 9 53 55 AM" src="https://github.com/vercel/next.js/assets/12456288/b927dd71-b5e9-417c-b2be-dd0cdab4ee8d">

### Next.js 13.4.19
<img width="1800" alt="Screenshot 2023-08-31 at 9 54 32 AM" src="https://github.com/vercel/next.js/assets/12456288/c6a4f562-0377-4870-86b3-80ad60827610">

Link to related issue:

- [Extending request while using a custom server/standalone mode #54440](https://github.com/vercel/next.js/issues/54440)

### Expected Behavior

Global data stays intact between both contexts.

**Comment by danieljee** [comment]
I don't know if this is a similar issue but a singleton module loses context in every request in route handlers. It gets reinstantiated every time.

**Comment by shaunwarman** [comment]
We think the fix is to leverage
https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages
