### ISSUE TITLE
The development environment for "next13" is experiencing slow page loading

### ISSUE THREAD

**Issue by FreeDrifter** [vercel/next.js#54781]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Thu Jun  8 23:57:12 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_X86_64
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.6.3
    Relevant packages:
      next: 13.4.6
      eslint-config-next: 13.4.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6

warn  - Latest canary version not detected, detected: "13.4.6", newest: "13.4.20-canary.12".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

https://github.com/FreeDrifter/next-demo

### What browser are you using? (if relevant)

Chrome114

### Describe the Bug

In the "next13" development environment, the route switching is extremely slow.

![image](https://github.com/vercel/next.js/assets/33836381/b6f86a51-69f6-43ee-a47f-a856374d04e8)

### Expected Behavior

I hope that during development environment runtime, the routing can perform swift transitions.

### To Reproduce

1. clone example: https://github.com/FreeDrifter/next-demo
2. pnpm install
3. pnpm dev
4. performing page transitions.

**Comment by eben-vranken** [comment]
Just skimmed through your code real quick.

`<a className="home-hot-pet">
<Image width={0} height={0} src={KejiImage.src} alt="" />
<span>柯基</span>
</a>`

For links in Nextjs, I would recommend you use `next/Link`, this would allow for client-side navigation.

Besides this, `next/Link` also provides prefetching functionality, which would allow your users to load routes in the background without them noticing, which will greatly decrease route transition times.

**Comment by FreeDrifter** [comment]
> 

Delete this section of code and use the <Link> of next for navigation. The navigation will still be slow in the development environment.

**Comment by eben-vranken** [comment]
But it will be very optimized for the production environment! `next/Link` also prefetches pages which will also help with routing speed optimization.

**Comment by FreeDrifter** [comment]
> But it will be very optimized for the production environment! `next/Link` also prefetches pages which will also help with routing speed optimization.

Thank you. I understand what you mean. I have already removed the 'a' tags from the example code and added 'next/Link' for navigation. Building and running it is not an issue. However, the problem of slow navigation in my development environment has not been resolved. It's affecting my development efficiency, and I'm eager to understand the reasons behind the slow navigation in the development environment and hope to find a solution.

![image](https://github.com/vercel/next.js/assets/33836381/5e2fa51c-d6e4-458c-8506-54abb9268e62)

**Comment by eben-vranken** [comment]
Slow loading times in a local Next.js development environment can be caused by various factors. These include a cold server start, large JavaScript bundles, complex React components, slow APIs, inefficient development setups, lack of caching, excessive use of Hot Module Replacement (HMR), and resource limitations. Optimizing code, pre-building applications, and monitoring performance can help mitigate these issues. 

❗ Keep in mind that slow development times may not accurately reflect production performance, so it's crucial to test your application in a production-like environment.

**Comment by timneutkens** [comment]
Tracking here: https://github.com/vercel/next.js/issues/48748#issuecomment-1702424480.

The reproduction doesn't use canary.
