### ISSUE TITLE
Correction in content grammar

### ISSUE THREAD

**Issue by okoyecharles** [vercel/next.js#54857]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
https://github.com/vercel/next.js/blob/1fc4b22dd359c93306aa307d6b81a35a64bbcdba/examples/with-passport-and-next-connect/pages/api/user.js#L11
```

### Which example does this report relate to?

examples/with-passport-and-next-connect

### Describe the Bug

There are several grammatical errors across this example's comment. Although it  might not be a big problem, it is definitely an issue for me.

Here is a link to one:
https://github.com/vercel/next.js/blob/1fc4b22dd359c93306aa307d6b81a35a64bbcdba/examples/with-passport-and-next-connect/pages/api/user.js#L11

### Expected Behavior

A better and revised grammatically accurate content.

### To Reproduce

In order to avoid readability issues for other developers

**Comment by balazsorban44** [comment]
Thanks, would you like to open a PR to fix them? 🙏
