### ISSUE TITLE
NEXT_PUBLIC_* Environment Variables Missing in Browser Context

### ISSUE THREAD

**Issue by FelippeChemello** [vercel/next.js#54866]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #202305171336 SMP PREEMPT_DYNAMIC Wed May 17 13:45:19 UTC 2023
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 7.13.5
    Relevant Packages:
      next: 13.4.20-canary.15
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/nifty-shape-tjf8sp

### To Reproduce

Just print `process.env` it returns an empty object (`{}`)

```js
console.log(process.env)
```

### Describe the Bug

I have observed a change in behavior with process.env in the browser context in the latest versions of Next.js. When attempting to access process.env, it now returns an empty object ({}) instead of the expected environment variables. This change has led to problems when attempting to parse or validate environment variables using libraries such as ZOD or env-var, as they rely on process.env to access the specified environment variables.

This issue only occurs in the browser context and does not affect server-side rendering (SSR). Additionally, environment variables prefixed with NEXT_PUBLIC_* are also inaccessible in the browser context.

Code: 
```js
export default function Home() {
  return (
    <div>
      <h3>Accessing process.env</h3>
      <span>{JSON.stringify(process.env)}</span>
      <br />
      <h3>Accessing directly the environment</h3>
      <span>{process.env.NEXT_PUBLIC_EXAMPLE}</span>
    </div>
  );
}
```

Client Output:
![image](https://github.com/vercel/next.js/assets/29099474/a9cc2d18-6097-4db7-bdca-56a11ddf6473)

### Expected Behavior

To access all environment variables prefixed with NEXT_PUBLIC_* directly within the process.env object without having to individually specify each variable name. This would enable me to parse, validate, and work with all of them simultaneously.

**Comment by michalvadak** [comment]
`NEXT_PUBLIC_` variables are inlined into the code at the built time. 

> In order to make the value of an environment variable accessible in the browser, Next.js can "inline" a value, at build time, into the js bundle that is delivered to the client, replacing all references to process.env.[variable] with a hard-coded value.

https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser

**Comment by balazsorban44** [comment]
The above comment is correct.

For the App Router behavior, here is a more specific link to the docs: https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser.

This ensures that only used environment variables end up in the bundle.
