### ISSUE TITLE
'use client' clock 'Unknown root exit status'

### ISSUE THREAD

**Issue by opr-inzn** [vercel/next.js#54895]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.1.0
      npm: 9.8.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/affectionate-mestorf-q3syz5

### To Reproduce

Import clock.tsx in root layout.tsx

### Describe the Bug

I have a clock component that is imported into my RootLayout. 

```
'use client'

import { useState, useEffect } from 'react'

export default function Clock() {
    const [date, setDate] = useState(
        new Date().toLocaleString('de-DE', {
            hour: '2-digit',
            minute: '2-digit',
        })
    );

    useEffect(() => {
        const intervalId = setInterval(() => {
            setDate(
                new Date().toLocaleString('de-DE', {
                    hour: '2-digit',
                    minute: '2-digit',
                })
            );
        }, 1000);

        return () => {
            clearInterval(intervalId);
        };
    });

    return (
        <div className={`w-10 text-right`}>
            {date.split(':')[0]}
            <span className='animate-blink'>:</span>
            {date.split(':')[1]}
        </div>
    )
}
```

Locally, everything works as expected. When deployed, JS does not appear to load and after a few seconds in React Error 329 'Unknown root exit status.' It's a bit weird, since also if only this is deployed, it seems to work, but in combination with other components, it will fail. [Only Clock](https://clock-nextjs13.vercel.app/)

### Expected Behavior

Load JS and render page, display clock.

### How are you deploying your application? (if relevant)

Vercel

**Comment by johannordling** [comment]
Hello man!

I am running into a similar issue, would you mind sharing how you solved it? 🙏🏻

**Comment by opr-inzn** [comment]
@johannordling For the clock it was fairly easy. Apparently we need to check for everything now and can't apply certain things to a useState. I still have a similar issue with another component, but for the clock the fix was this

```
'use client'

import { useState, useEffect } from 'react'

export default function Clock() {
    const [date, setDate] = useState<string>();

    useEffect(() => {
        setDate(
            new Date().toLocaleString('de-DE', {
                hour: '2-digit',
                minute: '2-digit',
            })

        );

        const intervalId = setInterval(() => {
            setDate(
                new Date().toLocaleString('de-DE', {
                    hour: '2-digit',
                    minute: '2-digit',
                })
            );
        }, 1000);

        return () => {
            clearInterval(intervalId);
        };
    }, []);

    return (
        <div className={`w-10 text-right`}>
            {date?.split(':')[0]}
            <span className='animate-blink'>:</span>
            {date?.split(':')[1]}
        </div>
    )
}
```

**Comment by johannordling** [comment]
Thank you for your response. It seems like my problem was related to passing Date objects from a server component to a client component (them being non-serializable). Super weird that the error only happens on Vercel but not locally.

**Comment by ajames14-chwy** [comment]
I am hitting this same error but only when deployed (aws ecs) no errors get logged server side I get the 329 error in the browser console only.

**Comment by johannordling** [comment]
Whenever I've gotten that error is when there is problem with the client/server components interaction.

Like above, when passing non-serializable props from server to client component (e.g. dates, function etc.).

Also, make sure to define all components using either ""use client"" or "import "server-only"". This fixed a 329-issue for me.
