### ISSUE TITLE
Root route group renders root not-found incorrectly

### ISSUE THREAD

**Issue by tom-sherman** [vercel/next.js#54892]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.13.0
      npm: 8.13.2
      Yarn: 1.22.19
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.4.20-canary.15
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App Router

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/tom-sherman/next-not-found-route-group-bug

### To Reproduce

1. Run the repo
2. Go to `/foo/a`

### Describe the Bug

When you use `notFound()` inside of a route group at the root of the app directory and have a root `not-found.tsx` it's not rendered, instead the default Next.js not found is rendered inside of your root layout.

<img width="1006" alt="image" src="https://github.com/vercel/next.js/assets/9257001/d1933d08-0d47-4a0d-9626-fc29021961f2">

eg. https://next-not-found-route-group-bug.vercel.app/foo/a

This doesn't happen if the route group is anywhere other than the root eg. https://next-not-found-route-group-bug.vercel.app/nested/foo/a

### Expected Behavior

Root not-found should render inside the layout as it does with undefined routes eg. https://next-not-found-route-group-bug.vercel.app/nested/foo/a or https://next-not-found-route-group-bug.vercel.app/undefined

<sub>[NEXT-1588](https://linear.app/vercel/issue/NEXT-1588/root-route-group-renders-root-not-found-incorrectly)</sub>

**Comment by tom-sherman** [comment]
Relates to #51075

**Comment by devjiwonchoi** [comment]
Thanks for the investigation! Are you planning to open a PR?

**Comment by devjiwonchoi** [comment]
@huozhi Seems like need some adjustment around here, do you mind if I try this issue?

https://github.com/vercel/next.js/blob/2b9ffb009cccc4b596ee438042bd4cc774bc18e8/packages/next/src/build/webpack/loaders/next-app-loader.ts#L328-L333

**Comment by huozhi** [comment]
@devjiwonchoi A bit late to see the message, I've filed #54931 for the fix 🙏

**Comment by devjiwonchoi** [comment]
Will learn from it. Thank you!
