### ISSUE TITLE
Grammatical error in examples README

### ISSUE THREAD

**Issue by okoyecharles** [vercel/next.js#54919]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Desktop/next.js/examples/with-passport-and-next-connect
```

### Which example does this report relate to?

examples/with-passport-and-next-connect

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

After going through the next.js and passport example on Github I noticed a slight grammatical error in the README.md file and decided to open an issue. 

### Expected Behavior

I expect the Next.js documentation examples on Github to have been revised and proofread in order to avoid any errors... as it could distract some learners (Just like me who's opening an issue 😅).

### To Reproduce

For simplicity, Here is the link to the README containing this issue.
https://github.com/vercel/next.js/blob/canary/examples/with-passport-and-next-connect/README.md (3rd paragraph)

<img width="989" alt="error-screenshot" src="https://github.com/vercel/next.js/assets/102174805/9a905472-249d-4ac8-a1d5-f55e4421a499">

That should be "For demo purposes"

**Comment by okoyecharles** [comment]
I have created a PR

https://github.com/vercel/next.js/pull/54921

**Comment by balazsorban44** [comment]
Thanks! I think opening an issue for typos is not necessary, since there is not much to investigate. Feel free to just open PRs in the future for this, if you have the time/intention to. Thanks for the PR! 💚

**Comment by okoyecharles** [comment]
Alright @balazsorban44, I will make sure to open a PR next time.
