### ISSUE TITLE
relax pinned postcss and zod versions in next dependencies to avoid 2 versions in node_modules

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#54947]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/stefanprobst/next-issue-deps

### To Reproduce

- `pnpm create next-app next-issue-repro --app --import-alias "@/*" --no-eslint --no-src-dir --tailwind --ts`
- `cd next-issue-repro`
- `pnpm why postcss`
- see both v8.4.14 (pinned by next) and v8.4.29 installed

### Current vs. Expected behavior

next.js has [both `postcss` and `zod` pinned to exact versions](https://github.com/vercel/next.js/blob/canary/packages/next/package.json#L96-L99) in its dependencies, so users adding these to their project's dependencies will likely end up with two versions of the same package.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #202308161732 SMP PREEMPT_DYNAMIC Wed Aug 16 17:41:09 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.7.0
    Relevant Packages:
      next: 13.4.20-canary.15
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by balazsorban44** [comment]
Thanks, this is intentional to have better control over Next.js' own dependencies with regards to security/breaking changes. If you are experiencing a bug because of this, please open a separate issue. 🙏
