### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by elementISH** [vercel/next.js#54943]
### What is the improvement or update you wish to see?

the "What's in Next.js?" section in the home page contians different sized cards which is not a good design approach, the cards should be divided equally in size.

### Is there any context that might help us understand?

some cards are smaller than others and spaces aren't well distributed

### Does the docs page already exist? Please link to it.

https://nextjs.org/

**Comment by balazsorban44** [comment]
The homepage is designed by our design team, style is objective, but thanks for the feedback anyway!
