### ISSUE TITLE
NextJS Firebase Hosting: API routes with POST request and body timeout

### ISSUE THREAD

**Issue by ritvij14** [vercel/next.js#54958]
### Link to the code that reproduces this issue or a replay of the bug

https://stackoverflow.com/questions/77020369/nextjs-api-route-post-request-does-not-work-with-firebase-hosting

### To Reproduce

The structure is this:

`src/pages/api/apiTest.ts`

This is the code in apiTest.ts:

```typescript
import type { NextApiRequest, NextApiResponse } from "next";

type ResponseData = {
  message: string;
};

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<ResponseData>
) {
  if (req.method !== "POST") {
    res.status(405).send({ message: "Only POST requests allowed" });
  }

  res.status(200).json({ message: "Hello from Next.js!" });
}

export const config = {
  api: {
    bodyParser: false,
  },
};
```

Now deploying it to Firebase Hosting using:
```bash
firebase deploy --only hosting
```

### Current vs. Expected behavior

When I do a GET Request:

[Results with GET](https://i.stack.imgur.com/99QNN.png)

But when I do a POST Request:

[Result with POST](https://i.stack.imgur.com/RHKM1.png)

Current Behaviour: POST request times out with 408 status code.

Expected behaviour: POST request should work fine even with sending a body.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.12.1
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: N/A
      react: N/A
      react-dom: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

I tried this -> https://github.com/vercel/next.js/issues/7960#issuecomment-569971709

and got this:
```bash
- warn Next.js can't recognize the exported `config` field in route "/api/apiTest":
Unsupported node type "UnaryExpression" at "config.api.bodyParser".
The default config will be used instead.
Read More - https://nextjs.org/docs/messages/invalid-page-config
```

and also tried putting the `bodyParser` to false directly but nothing works.

**Comment by balazsorban44** [comment]
It was also a duplicate of #50166

Please remember to search for opened issues before opening a new one, and upvote the existing one instead if it applies to you, or add your own reproduction as a comment. :pray:
