### ISSUE TITLE
Custom server renderToHTML does not work with next 13.4

### ISSUE THREAD

**Issue by thilohaas** [vercel/next.js#54977]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/thilohaas/nextjs-custom-server/tree/main
https://codesandbox.io/p/github/thilohaas/nextjs-custom-server/main

### To Reproduce

1. Start a new nextjs project with `npx create-next-app@latest`
2. Add a server.js
```
const { createServer } = require('http');
const { parse } = require('url');
const next = require('next');

const dev = process.env.NODE_ENV !== "production";
const hostname = 'localhost';
const port = process.env.PORT || 3001;
// when using middleware `hostname` and `port` must be provided below
const app = next({ hostname, port, dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  createServer(async (req, res) => {
    try {
      const parsedUrl = parse(req.url, true);
      const { pathname, query } = parsedUrl;

      if (pathname.startsWith('/_next') || pathname.startsWith('/__next')) {
        await handle(req, res, parsedUrl);
      } else {
        const html = await app.renderToHTML(req, res, pathname, query);
        res.end(html);
      }
    } catch (err) {
      console.error('Error occurred handling', req.url, err);
      res.statusCode = 500;
      res.end('internal server error');
    }
  }).listen(port, (err) => {
    if (err) throw err;
    console.log(`> Ready on http://${hostname}:${port}`);
  });
});
```
3. Change the package.json dev script to: `"dev": "node server.js",`
4. run `npm run dev`
5. open http://localhost:3001

### Current vs. Expected behavior

I expect it to display the welcome page but instead i get an error from the next server:
```
Error: Invariant ensurePage called outside render worker
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.20-canary.16
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by sreimer15** [comment]
I'm seeing this error as well, when using next-dev-https

**Comment by KODerFunk** [comment]
For me this problem is also related to this one: https://github.com/vercel/next.js/issues/53466
Obstacles have appeared in large projects with their own infrastructure (Kube).
These problems are associated with the use of Custom-Server, which is a great need for additional collection of metrics, custom logging, control of response headers and status, etc. I also need the ability to run in one thread so that the `AsyncLocalStorage` context is saved and other global mechanics work.

On versions higher than `13.4.12` (I confirm, the problem appears with `13.4.13-canary.0`) it became impossible to create a custom-server. Now when calling methods, and even render, I get errors when calling server methods: `Invariant ... called outside render worker`.

The Next server is initializing, but it seems to be isolated from my Fastify server, or the new code is broken.
@ijjk It seems to me that you added these changes that affected an important part of the community.

**Comment by JaviCodx** [comment]
We are having the same issue with a custom Express server

**Comment by salman-mazhar** [comment]
We are facing the same issue when using renderToHTML with a custom http server, is there a temporary work around?

**Comment by KODerFunk** [comment]
@salman-mazhar We are waiting for @ijjk.

**Comment by jiebaibai** [comment]
@ijjk  13.5.5也有这个问题，自定义server.js之后，app.renderToHTML异常，catch里的error为：
TypeError: Cannot read properties of undefined (reading 'ensurePage')
<img width="327" alt="image" src="https://github.com/vercel/next.js/assets/10113095/461d7b06-c472-4fa5-873a-fdd561f64a8b">

**Comment by linhucontorion** [comment]
@jiebaibai please use English to report your issue, so others can understand, thanks

**Comment by jiebaibai** [comment]
> @jiebaibai please use English to report your issue, so others can understand, thanks

> @ijjk 13.5.5 also has this problem, after customizing server.js, app.renderToHTML exception，catch error is：
> TypeError: Cannot read properties of undefined (reading 'ensurePage')
![image](https://github.com/vercel/next.js/assets/10113095/1b7f3261-0f32-452a-b5fe-fa4c65fae448)

**Comment by QianKuang-nyu** [comment]
Also face a similar issue in Custom Server. Our AssertPrefix is partially working.

**Comment by gustavoalvesm** [comment]
Same problem here with custom server + renderToHTML + hydrate components :disappointed: any temporary solution?

![image](https://github.com/vercel/next.js/assets/42223761/0ef4b063-5afd-4bb8-82af-8a504bea4379)

**Comment by ESCxjl** [comment]
We are facing the same issue when using renderToHTML with a custom http server, anyone can help me ?

**Comment by chngjunjie** [comment]
We are facing the same issue with hapi js. renderToHTML issue , version 13.4 

The isRenderWorker is always undefined in next-dev-server. So it will work if we turn off the development mode, build the dist folder and run it without next server. 
![image](https://github.com/vercel/next.js/assets/56791652/724cbef6-34cd-4413-b433-4ab3d90bb68f)

**Comment by SouthLink** [comment]
Same issue with Next 14.0.4 with custom server.

**Comment by duzgunemreozkan** [comment]
do not use custom next server and manage routers via next.config.js

**Comment by redguard1** [comment]
I have a same problem with next 14.1.0 with custom server. Any update for this issue ?

**Comment by mildfuzz** [comment]
Also seeing this error

**Comment by mildfuzz** [comment]
@duzgunemreozkan yeah, you mentioned. 

Maybe you might elaborate on how you are able to replicate the functionality of Express in the next.config.js, that would be helpful

**Comment by azraelgarden** [comment]
Same error here (Next 14. while trying to work with Hydrate and Stencil (Web Components).
`TypeError: Cannot read properties of undefined (reading 'ensurePage')`

**Comment by mildfuzz** [comment]
Looking through the code, seems like it *might" only be an issue with the
dev server. Might be worth seeing if it will run in production mode

**Comment by vaishnavi-jadhav-amla** [comment]
Iam facing the same issue. Iam not able to use renderToHTML on custom server. Iam using next 13.4. Any workaround for this issue. I also tried on the latest version but it still not worked.

**Comment by rtrys** [comment]
I'm seeing the same error with custom server (I'm using Hapi)

**Comment by ChangWei-Chang** [comment]
Any update or workaround on this ? We are planning to upgrade to next 14.2.3 from 12 and see this issue.

**Comment by Rylab** [comment]
We ran into this problem too, it's with renderToHtml only in dev mode. We got around it by calling app.render in dev mode instead.

**Comment by rv-dswanson** [comment]
> We ran into this problem too, it's with renderToHtml only in dev mode. We got around it by calling app.render in dev mode instead.

This worked for my team also, going from `13.2.3` to `14.2.4`

**Comment by lzkui2013** [comment]
Aslo face the same thing，when  use customServer to get the page html to cache in redis。

`const html = await app.renderToHTML(req, res, pathname, query);`

Alway error: Invariant: dynamic responses cannot be unchunked. This is a bug in Next.js

**Comment by 6ixB** [comment]
Hey, I'm also facing the same issue, are there any updates for this? I'm using Next.js version 14.2.4.

**Comment by goooseman** [comment]
Fixed by using `render` instead of `renderToHtml`

**Comment by ijjk** [comment]
Hi, the `renderToHtml` API is not a public API/not documented nor used in any examples. So the response here https://github.com/vercel/next.js/issues/54977#issuecomment-2354102135 saying to use the proper public API `render` is correct. 

> If you want to work with the html generated, this is not an option

This is not supported with streaming as otherwise you are buffering the response to capture the HTML if you wanna do transforms on the stream which is highly risky that would be a use case for middleware or similar. 

I'm gonna close this as it doesn't seem to be a valid/supported use case.
