### ISSUE TITLE
Double render (Serverside) in App Dir

### ISSUE THREAD

**Issue by B33fb0n3** [vercel/next.js#55003]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/B33fb0n3/doublerenderissue/

### To Reproduce

1. Generate build code via `next build`
2. Start the server via `next start`
3. Navigate to `/data/whatever`
4. Check the logs and you see 2 times _"data called"_

### Current vs. Expected behavior

I expect that the external API only once called, but in this case (and every time it invalidates) it will be called 2 times.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: Windows
      Arch: x64
      Version: 11
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: N/A
      pnpm: 7.16.0
    Relevant packages:
    "autoprefixer": "10.4.15",
    "eslint": "8.47.0",
    "eslint-config-next": "13.4.19",
    "next": "13.4.20-canary.16",
    "react": "18.2.0",
    "react-dom": "18.2.0"
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

**Comment by mwawrusch** [comment]
Maybe it's standard React behavior - see here: https://xerosource.com/why-api-is-called-twice-in-react/

**Comment by B33fb0n3** [comment]
@mwawrusch it is in react the case, yes. And yes it’s because of the strict mode. In my case we have 3 different angles: 1. Server components (no react) 2. no strict mode 3. no useEffect (your link) because point one.

Maybe you saw a useEffect Hook in my code or maybe you saw something with react in my code or maybe you saw even the strict mode in my code then please send me a link the line. Thanks!

**Comment by icyJoseph** [comment]
In Next.js apps, strict mode is activated through `next.config.js`:

- https://nextjs.org/docs/app/api-reference/next-config-js/reactStrictMode

**Comment by B33fb0n3** [comment]
Oh I haven't seen that. 

It says 
> React's [Strict Mode](https://react.dev/reference/react/StrictMode) is a **development mode only** feature for highlighting potential problems in an application.

So in my case that's not the problem. You can see in my step one to reproduce the issue, that I build the app. So this issue is only in production and not in development environment.

**Comment by icyJoseph** [comment]
Aha, sorry I jumped straight to the comments. 

Then it has to be this: https://github.com/vercel/next.js/discussions/52934#discussioncomment-6498597

**Comment by B33fb0n3** [comment]
That looks like it is not solvable from the current situation. But yeah, that's maybe the problem :/
Thanks! :)

**Comment by balazsorban44** [comment]
Hi, this is currently expected, good point by @icyJoseph. We are exploring other behaviors in the future.
