### ISSUE TITLE
`next dev` on Windows fails with `invariant expected app router` when using Edge Runtime

### ISSUE THREAD

**Issue by sebastianroming** [vercel/next.js#55013]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vietvp1/nextapp

### To Reproduce

1. Clone the repo
2. Install all dependencies
3. `npm run dev`
4. Open `localhost:3000` in the browser - the error is shown in the terminal​

### Current vs. Expected behavior

**Current behavior:**
When using `export const runtime = "edge";` in `page.tsx`, an error is thrown:

```
error Error: invariant expected app router to be mounted
  at HomePage (./components/HomePage/index.tsx:14:78)
```

**Expected behavior:** 
No error should be thrown while accessing the page.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
C:\dev\nextapp>npx --no-install next info

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.16.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.16
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime), Operating System (Windows, MacOS, Linux)

<sub>[NEXT-1591](https://linear.app/vercel/issue/NEXT-1591/next-dev-on-windows-fails-with-invariant-expected-app-router-when)</sub>

**Comment by imniloy** [comment]
When using export const runtime = "edge"; in page.tsx, an error is thrown in the production build but dev mode works fine.
Can anyone help me.
[Error: invariant expected app router to be mounted]

**Comment by styfle** [comment]
Looks like this was introduced in [next@13.4.8](https://github.com/vercel/next.js/releases/tag/v13.4.8) since 13.4.7 works without error.

I'm guessing the issue is somewhere in [webpack-config.ts](https://github.com/vercel/next.js/blob/canary/packages/next/src/build/webpack-config.ts) but I haven't found the root cause.

**Comment by alperozhb** [comment]
Is there any update on this issue? Does it exist on 13.5?
