### ISSUE TITLE
bug: anchor in URL breaks useSearchParams hook

### ISSUE THREAD

**Issue by ozzyfromspace** [vercel/next.js#55044]
### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/upbeat-dubinsky-9d4qpz

### To Reproduce

1. On `/` page, create a next/link with an href that correctly references an anchor (id) AND one or more params, eg: `/services?#gallery?featuring=vercel`. **Ensure that anchor comes before param(s) (related to bug)**
2. Create /services page and add any element id from previous step: `id="gallery"`
3. On /services page, extract token like so:
```
// in the client-side component:

const params = useSearchParams()
const token = params.get("featuring") // string or null
console.log({ token })
```
4. Click next/link to be redirected from `/` to `/services`
5. Remove anchor from href, and click to be redirected to `/services`
6. Add anchor to href again, and remove params from href
7. Click the link to be redirected to `/services`

### Current vs. Expected behavior

**Expected behavior**
The link is properly parsed by the useSearchParams hook, and correctly returns the value associated with the key-value pair in the URL

**Actual behavior**
1. Without the anchor tag, useSearchParams **correctly** parses the URL and returns the param(s)
2. With the anchor tag, useSearchParams *fails* to parse the URL and returns the param(s)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Additional context

Ensuring that the params come BEFORE any other url entities does not break the useSearchParams hook (tested). This leads me to believe there's an "order" bug while parsing the URL.

**Comment by icyJoseph** [comment]
Hi,

If I open my browser console, and do:

```js
let url = new URL("/services?#gallery?featuring=vercel", document.baseURI)
```

And then, I log `url.search` or `url.searchParams` it is empty... However, the `url.hash` contains the `#gallery?featuring=vercel` information.

Are we sure this is not expected behavior? Note that my example does not even use Next.js APIs.

Could you link me to some specs, or docs, which talk about how to handle this situation?

**Comment by ozzyfromspace** [comment]
@icyJoseph I suppose I may have the wrong idea here. I'll read into it. Thanks for the response ✨

**Comment by ozzyfromspace** [comment]
Resolved.
