### ISSUE TITLE
Docs: App Router Optimizing -> Testing

### ISSUE THREAD

**Issue by JerrodSmithFlex** [vercel/next.js#55057]
### What is the improvement or update you wish to see?

Currently the App Router documentation does not cover the Testing section of how to test Next.js for enterprise installs. The Pages router does have a Testing section, I would like to see this new section so I can configure Next.js for exhaustive testing.

### Is there any context that might help us understand?

Currently the App Router documentation does not cover the Testing section of how to test Next.js for enterprise installs. The Pages router does have a Testing section, I would like to see this new section so I can configure Next.js for exhaustive testing.

**Comment by balazsorban44** [comment]
Hi, this is being explored currently: https://github.com/vercel/next.js/pull/54989, https://twitter.com/leeerob/status/1698758756924825723

Documentation is going to follow up, the docs team is working on it!
