### ISSUE TITLE
Docs:  Please add dark mode for learn nextjs documentation 

### ISSUE THREAD

**Issue by apoorvapendse** [vercel/next.js#55055]
### What is the improvement or update you wish to see?

Making the learn next docs in dark mode would be super useful because new learners would mostly spend time there over other documentation 

### Is there any context that might help us understand?

none

### Does the docs page already exist? Please link to it.

 https://nextjs.org/learn/foundations/about-nextjs

**Comment by MaximMaximS** [comment]
I think it would be better to update it to app router first. According to leerob, it's being  worked on. https://github.com/vercel/next.js/issues/53271#issuecomment-1664600813

**Comment by leerob** [comment]
Working on it!
