### ISSUE TITLE
Next.js should not start on "bad ports"

### ISSUE THREAD

**Issue by dandrei** [vercel/next.js#55050]
### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/stupefied-parm-nkr2wn

### To Reproduce

1. A Next.js application in production (`npm run start`) on a "bad port" (as defined by the fetch standard, e.g. `4045`).
2. Access a page that uses a "next/image" component.

### Current vs. Expected behavior

The demonstrative example showcases the loading of a "next/image" component .
It loads fine in development mode, but fails in production when running on a "bad port":
- the page displays a broken image
- the output from `next start` will display a stacktrace like:

```
upstream image response failed for /_next/static/media/test.37141d1a.png TypeError: fetch failed
    at Object.fetch (node_modules/next/dist/compiled/undici/index.js:1:26669)
    at async invokeRequest (node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
    at async node_modules/next/dist/server/next-server.js:359:35
    at async imageOptimizer (node_modules/next/dist/server/image-optimizer.js:537:13)
    at async cacheEntry.imageResponseCache.get.incrementalCache (node_modules/next/dist/server/next-server.js:598:60)
    at async node_modules/next/dist/server/response-cache/index.js:99:36 {
  cause: Error: bad port
      at makeNetworkError (node_modules/next/dist/compiled/undici/index.js:2:55255)
      at mainFetch (node_modules/next/dist/compiled/undici/index.js:2:29022)
      at fetching (node_modules/next/dist/compiled/undici/index.js:2:28803)
      at fetch (node_modules/next/dist/compiled/undici/index.js:2:26721)
      at Object.fetch (node_modules/next/dist/compiled/undici/index.js:1:26638)
      at globalThis.fetch (node_modules/next/dist/server/node-polyfill-fetch.js:30:26)
      at invokeRequest (node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:18)
      at node_modules/next/dist/server/next-server.js:359:74
      at imageOptimizer (node_modules/next/dist/server/image-optimizer.js:537:19)
      at NextNodeServer.imageOptimizer (node_modules/next/dist/server/next-server.js:354:16)
```

The stacktrace explains what's going on:
- The image optimizer attempts to fetch the image for optimization, using the `undici` implementation of `fetch`.
- Because the server is running on a "bad port", `undici` throws an error.

The result is a production deployment that should work fine, but none of the images load, because the optimizer crashes when attempting to fetch them.

Here's how the fetch standard defines a "bad port":
https://fetch.spec.whatwg.org/#bad-port

One possible solution could be to mirror Undici's list of "bad ports", and raise it as an issue when running Next.js in production.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.20-canary.18
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

<sub>[NEXT-1608](https://linear.app/vercel/issue/NEXT-1608/nextjs-image-optimizer-bug-caused-by-undici-when-running-on-a-bad-port)</sub>

**Comment by balazsorban44** [comment]
> One possible solution could be to mirror Undici's list of "bad ports", and raise it as an issue when running Next.js in production.

Isn't this what's happening already? You are showing the stack trace that Next.js is outputting.

On the client, we don't want to expose more information than necessary. Currently, you should be seeing something like `"url" parameter is valid but upstream response is invalid` as the response.

**Comment by dandrei** [comment]
In this particular case, I think it would be justified to have Next.js warn users about running on certain ports that are certain to crash in production, otherwise the user has to debug an issue that's not even technical, but originates in an arbitrary constraint imposed by a dependency, which is itself an implementation detail.

**Comment by styfle** [comment]
This isn't just an implementation detail of `undici`. All browsers block these ports too (I tested Chrome, Firefox, Safari).

Next.js should probably just hard error as soon as you try to start with one of those ports since no one will be able to visit your web app.

**Comment by balazsorban44** [comment]
You could add a similar check to exit the `next start` process like it's down here:

https://github.com/vercel/next.js/blob/df76f6633fe192e04b88ace62a00ccc9bb833d86/packages/next/src/cli/next-start.ts#L53-L63

Same for `next dev` here:

https://github.com/vercel/next.js/blob/df76f6633fe192e04b88ace62a00ccc9bb833d86/packages/next/src/cli/next-dev.ts#L254-L257

**Comment by olingern** [comment]
👋  I opened a PR [here](https://github.com/vercel/next.js/pull/55237) for just the `next start` command and wanted to get feedback on approach / testing before moving on to `next dev`
