### ISSUE TITLE
TypeError: Cannot read property 'startTime' of undefined in Emulator Pixel Android 9

### ISSUE THREAD

**Issue by angelamelinda** [vercel/next.js#55084]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
n/a
```

### Which example does this report relate to?

next hydration

### Describe the Bug

When I run the Next.js app as a webview in Simulator Pixel Android 9, I got this error `TypeError: Cannot read property 'startTime' of undefined`

If I click the first error line, it shows this error
`default.startSpan("navigation-to-hydration",{startTime:performance.timeOrigin+e.startTime,`

I think it's not from my code but from the Next.js code

![image](https://github.com/vercel/next.js/assets/19211116/7b52cb9a-e887-4f0f-8102-8e48193dd6b3)

### Expected Behavior

No error

### To Reproduce

Run the app in Simulator Pixel Android 9

**Comment by timtyrrell** [comment]
https://github.com/vercel/next.js/issues/55084

**Comment by tchenu** [comment]
We got the same error with fresh Next.js install on Firefox < 102

**Comment by balazsorban44** [comment]
We recently updated things around this, please upgrade to `next@canary` to try it out.

In any case this was not a proper bug report, please use the proper bug template next time, attaching a reproduction that we can look, into.

_Sidenote, Android 9 has reached it's end of life FWIW_

I'm closing this, if the above did not fix your issue, please open a new bug report as asked, thanks!
