### ISSUE TITLE
Docs: Which versioning scheme does Next.js adhere too?

### ISSUE THREAD

**Issue by petertflem** [vercel/next.js#55097]
### What is the improvement or update you wish to see?

Hello! 👋 

I have tried to figure out what versioning scheme Next.js adheres to, but without luck. If this is not in the documentation (I might just have missed it), could it be added? It would be useful to know if it is semantic versioning, etc. If it is in the docs, could someone provide a link? 😄 

### Is there any context that might help us understand?

I want to upgrade Next.js from 13.4.2 to 13.4.19, and it will be easier if I know there are no breaking changes, which it shouldn't be if Next.js adheres to semantic versioning.

**Comment by balazsorban44** [comment]
Hi, the Next.js documentation is always pointing to the `latest` version of `next`. It is following semantic versioning, so you should not experience breaking changes between patch and minor releases. If you do, it's considered a bug, and you can report them as such and we will look into it.

Certain features can be added in minor releases, those are usually indicated at the top of the page so you know when they became available.

Ref: https://github.com/vercel/next.js/blob/9bb9f07e82357eeb4a15f9c1f5ecb21d600dd433/contributing/repository/release-channels-publishing.md

**Comment by petertflem** [comment]
Thanks! 😄
