### ISSUE TITLE
Images in static directory fail to load when domain based i18n is configured (Pages dir)

### ISSUE THREAD

**Issue by jonathandsouza** [vercel/next.js#55092]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/jonathandsouza/nextjs-i18n-image-loading-issue

### To Reproduce

1.  edit the hosts file to add the following entries  (::1 nl.website.com, ::1 de.website.com)
2. Checkout & run the application in development mode (npm run dev) (Note: the issue is also reproducible in Next prod build)
3. Open the page (nl.website.com) and observe that the images load correctly. 
4. Open the page (de.website.com) and observe that the images fail to load. The following error is displayed on the console. 

![image](https://github.com/vercel/next.js/assets/6910063/b152b4b7-b5e1-4a16-8e7d-c17933e80fa6)

### Current vs. Expected behavior

Current Behaviour: Images fail to load when domain-based i18n is configured in a NextJS app. 
Expected Behaviour: Images should load correctly. 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Internationalization (i18n)

### Additional context

The functionality works as expected on version 13.4.12. We first noticed the problem in version 13.4.19. 

Subsequently, I have been able to reproduce this issue on the latest canary (^13.4.20-canary.19)

**Comment by cosieLq** [comment]
Maybe related to #54159 ?

**Comment by jonathandsouza** [comment]
@cosieLq I am not sure how this is related to  #54159.  I have a suspicion this is related to internatio

I am closing this issue since a similar issue has already been raised in #54765
