### ISSUE TITLE
"lint": "next lint" never start 

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [vercel/next.js#55094]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js

### To Reproduce

So I have this script in package.json from the default nextjs installation (using create-next-app)

```json
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
```

if I do pnpm lint it does everysingle time and it never run the lint

```
 info Loaded env from /Users/FRANCESCO.ZUPPICHINI/Documents/ai-callcenter/.env.local
? How would you like to configure ESLint? https://nextjs.org/docs/basic-features/eslint
- ready ESLint has successfully been configured. Run next lint again to view warnings and errors.

```

### Current vs. Expected behavior

should actually run the linting

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112
    Binaries:
      Node: 20.3.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by IsabellaRey** [comment]
I'm seeing this too just now

**Comment by IsabellaRey** [comment]
Note there is no `.eslintrc.json` file generated in the root folder - is that what the problem is?

If I add one manually, running `npm run lint` again seems to be running the actual linting

**Comment by devjiwonchoi** [comment]
@FrancescoSaverioZuppichini @IsabellaRey Please provide a repro so as to investigate.

**Comment by devjiwonchoi** [comment]
@IsabellaRey If that is the case, add `.eslintrc.json` as:

```json
{
  "extends": "next/core-web-vitals"
}
```

**Comment by IsabellaRey** [comment]
Repro steps are as described by @FrancescoSaverioZuppichini:
1. create bare-bone web app with `create-next-app`
2. ensure package.json has scripts.lint = "next lint"
3. run `npm run lint`

Expected:
the first run of `npm run lint` generates the appropriate `.eslintrc.json` file in the root folder. Subsequent runs do the actual linting

Actual:
the first run of `npm run lint` does not generate a config file. Subsequent runs keep asking the user which configuration they want to set up, only to tell them it's already set up (which it isn't)


@devjiwonchoi thanks - I'll be adding a config file manually as a temporary workaround, but please note that this is not in line with the docs: https://nextjs.org/docs/app/building-your-application/configuring/eslint
Half of the point of prompting the user seems to be auto-generating that config file

**Comment by devjiwonchoi** [comment]
I've checked that `create-next-app` does create the default `.eslintrc.json`.

**Comment by IsabellaRey** [comment]
@devjiwonchoi thanks for looking into this.

I should add in my case I actually started with a Nextjs template which does not include eslint to start with:
it's the recommended template with Redux:

https://github.com/vercel/next.js/tree/canary/examples/with-redux

`npx create-next-app --example with-redux with-redux-app`

**Comment by devjiwonchoi** [comment]
Fixing this issue will resolve that also, appreciate you for sharing.

**Comment by devjiwonchoi** [comment]
In order to make this issue clear, I'll port this issue.
