### ISSUE TITLE
Prop drilling an action breaks it

### ISSUE THREAD

**Issue by darklight9811** [vercel/next.js#55154]
### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/vibrant-haze-zp45l6

### To Reproduce

1. create an async component that wraps an server action prop as a function inside of it

### Current vs. Expected behavior

From what I can gather, the compiler is seeing the child component as an action instead of a react component, so it's breaking because it thinks its not a proper server action.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.13-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by lubieowoce** [comment]
in your repro, you have
```
"use server";

export async function Container(props) {
  ...
}
```
this is incorrect if you want Container to be a server component. `"use server"` should only be used for files that export actions.

**Comment by balazsorban44** [comment]
Closing as per the above comment https://github.com/vercel/next.js/issues/55154#issuecomment-1786280317
