### ISSUE TITLE
Client side javascript is not working from 13.4.17

### ISSUE THREAD

**Issue by zsombor-barabas** [vercel/next.js#55179]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/zsombor-barabas/next-hydration-bug-reproduction

### To Reproduce

1. Start the application with npm run dev (I suggest using the node:16.13.2 docker image so the environment is guaranteed to be the same)
2. Open the port in the browser, check the console, the `rendered` log won't be there, hydration is not working javascript is not running client side.
3. run `npm i next@13.4.16`
4. restart the application with `npm run dev`
5. visit the correct port in your browser, check the console, the `rendered` log will be there, hydration is working, javascript is running on the client side.

### Current vs. Expected behavior

I expect the log to appear after 13.4.17 as well.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
I used the node:16.13.2 docker image.
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tested with multiple versions I verified that something went wrong between `13.4.16` and `13.4.17`

**Comment by subzero10** [comment]
I am facing the same as well. Downgrading to `13.4.16` resolves the issue.

**Comment by lucacavallaro** [comment]
same issue here (with `13.4.19`)

**Comment by mark-durbin-ucf** [comment]
I have encountered this same issue for v13.4.19 on two Windows 10 machines, but not my Windows 11 machine. On the Windows 10 machines, downgrading to 13.4.16 solved the issue.

**Comment by icyJoseph** [comment]
Hi,

Y'all need to upgrade your Node.js versions:

- https://github.com/vercel/next.js/issues/54269#issuecomment-1685109739
- https://github.com/vercel/next.js/issues/54269#issuecomment-1685110362

**Comment by balazsorban44** [comment]
Closing as per the comment above. Feel free to open a new issue if you are still experiencing this! Don't forget a reproduction. "Same issue" is not actionable from out side, unfortunately. :pray:
