### ISSUE TITLE
Refresh on routing to specific route (/index/[id])

### ISSUE THREAD

**Issue by aryan-wayne** [vercel/next.js#55174]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/aryan-wayne/nextjs-index-route

### To Reproduce

1. install npm packages and run the project
2. there are 3 button that map to the home, asset and index page
3. by clicking on asset button in home page we see the router.push work properly with no refresh in browser
4. by clicking on index button router.push always refresh the browser to index page

### Current vs. Expected behavior

Following the steps from the previous section, I expected clicking on index button has same behavior of clicking on asset with no refresh on browser.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operation System:
Mac, Windows, Linux
Binaries:
Nextjs: 13.4.19
Node: 18.12.1
npm: 8.19.2
```

### Which area(s) are affected? (Select all that apply)

App Router, Page Router

### Additional context

I tested this project on many platforms and all of them had same result. It seems create index directory name in pages folder and make [id] folder inside of it create an issue in nextjs that can not handle locally routing inside browser and always refresh in routing to /index/[id] path

**Comment by ans-ashkan** [comment]
I have the same issue and I can verify that provided repro also applies to my case

**Comment by arefweb** [comment]
Did you find any solution for that? because I have the same problem.

**Comment by msajadpourr** [comment]
i have same issue too, any solution?

**Comment by Mohammadshamchi** [comment]
Hey Guys,
Hope you well I asked this from Google and got this Answer : 
The workaround for this issue is to rename the index directory to something else. For example, you could rename it to home. This will prevent the router from trying to route to the index.js file when you click on the link to the index page.

You can also use the useRouter hook to manually control the routing. This way, you can prevent the router from refreshing the page when you click on the link to the index page.

Here is an example of how to use the useRouter hook to prevent the page from refreshing:

```
import Router from 'next/router';

const App = () => {
  const router = useRouter();

  const handleClick = () => {
    // Prevent the router from refreshing the page
    router.push('/index/[id]', { replace: false });
  };

  return (
    <div>
      <button onClick={handleClick}>Go to Index Page</button>
    </div>
  );
};
```
The replace: false option tells the router to not replace the current page with the new page. This will prevent the page from refreshing.

**Comment by aryan-wayne** [comment]
> Hey Guys, Hope you well I asked this from Google and got this Answer : The workaround for this issue is to rename the index directory to something else. For example, you could rename it to home. This will prevent the router from trying to route to the index.js file when you click on the link to the index page.
> 
> You can also use the useRouter hook to manually control the routing. This way, you can prevent the router from refreshing the page when you click on the link to the index page.
> 
> Here is an example of how to use the useRouter hook to prevent the page from refreshing:
> 
> ```
> import Router from 'next/router';
> 
> const App = () => {
>   const router = useRouter();
> 
>   const handleClick = () => {
>     // Prevent the router from refreshing the page
>     router.push('/index/[id]', { replace: false });
>   };
> 
>   return (
>     <div>
>       <button onClick={handleClick}>Go to Index Page</button>
>     </div>
>   );
> };
> ```
> 
> The replace: false option tells the router to not replace the current page with the new page. This will prevent the page from refreshing.

Hi Mohammad.
Thank you for the response. Unfortunately rename the directory is not an option for us and using "replace" option in useRouter is not working for me, by the way I couldn't  find this option in router.push in Next.js documentation or maybe it's not in 13 version.

**Comment by aryan-wayne** [comment]
If anyone has this problem I think this solution can help:
I used one catch all page like this => [...path]/index.tsx. With this approach any routes are available to next router but has some side effect, for example you do not have 404 page and you should handle it by your own by creating some kind of react router config switch and show pages you want and send not found to your 404 page.

By the way this issue fixed in next 14 App router.
