### ISSUE TITLE
Docs: MDX metadata refers error

### ISSUE THREAD

**Issue by thomaszdxsn** [vercel/next.js#55190]
### What is the improvement or update you wish to see?

In [Configuring: MDX | Next.js](https://nextjs.org/docs/pages/building-your-application/configuring/mdx#frontmatter) it writes about use metadata in mdx, but it is wrong variables name.

```mdx
export const meta = {
  author: 'Rich Haines',
}
 
# My MDX page
```

If you `export const meta`, it would nothing happen. same issue on https://github.com/vercel/next.js/issues/50734 too.

The correct way to resolve this issue, is `export const metadata`

### Is there any context that might help us understand?

nothing

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/configuring/mdx#frontmatter

**Comment by icyJoseph** [comment]
Isn't this a different kind of meta? When you parse the MDX document, that object is part of the content, and typically you can access it as `frontmatter.data.author` for example, which you can then use to render UI or various other things. 

Here for example: https://github.com/vercel/next.js/blob/92e1b3fef9088aa646eecd8d95611e26751412f7/examples/blog/scripts/gen-rss.js#L22

**Comment by thomaszdxsn** [comment]
> Isn't this a different kind of meta? When you parse the MDX document, that object is part of the content, and typically you can access it as `frontmatter.data.author` for example, which you can then use to render UI or various other things.
> 
> Here for example:
> 
> https://github.com/vercel/next.js/blob/92e1b3fef9088aa646eecd8d95611e26751412f7/examples/blog/scripts/gen-rss.js#L22

Not the same thing, your example is parse frontmatter, it is yaml like text.

But according to doc, the MDX file can use `export const meta` syntax, and it not work. But you can use `export const metadata` it is work like plain jsx file.

![CleanShot 2023-09-12 at 15 28 04](https://github.com/vercel/next.js/assets/23616426/b5cfea68-b2c8-4877-9e74-66c3ec0c772b)

**Comment by icyJoseph** [comment]
Yeah, but that's what I mean, the example you are linking is talking about auto extracting the frontmatter. 

In other words, you need to export both `metadata` and/or `meta`. They are not exclusive.

**Comment by icyJoseph** [comment]
Right, for example: https://github.com/orgs/mdx-js/discussions/2075#discussioncomment-3082493

Its two different things. 

https://github.com/vercel/next.js/issues/50734 I mean, I can see the confusion, but it is two different things. 

Using meta in MDX is not a Next.js thing, it originated elsewhere, for example: https://v0.mdxjs.com/advanced/transform-content

**Comment by thomaszdxsn** [comment]
I see, thanks very much
