### ISSUE TITLE
Next JS On-Demand Revalidation not working in the production environment. 

### ISSUE THREAD

**Issue by shaileshvit** [vercel/next.js#55219]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.12.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.1.6
      react: 18.2.0
      react-dom: 18.2.0
warn  - Latest canary version not detected, detected: "13.1.6", newest: "13.4.20-canary.23".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

examples/cms-sanity/pages/api/revalidate.js

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

next build

### Describe the Bug

We have a NextJS front end, We have implement the on-demand ISR API on the /api/revalidate path, which is called whenever Contentful(CMS) content published.  We have never used time-based ISR. The API is called and the page is updated immediately in the Live website,  but after few minutes the page getting reverted with old content, even though the API is called properly in the log without any error. In non-prod it is working as expected and content are not reverting after few mins. 

Webhook url - https://www.xxxxxx.com/api/revalidate

Next JS Application path:  src/pages/api/revalidate.js

export default async function handler(req, res) {

    if (req.method !== "POST") {
        return res
            .status(400)
            .json({ error: "Invalid HTTP method. Only POST requests are allowed." })
    }

    // check for the secret token
    if (req.headers.secret !== process.env.SECRET_TOKEN) {
        return res.status(401).json({ message: "Invalid token" })
    }

    try {
        // check that body is not empty
        const body = req.body
        if (!body) {
            return res.status(400).send("Bad request")
        }
        const type = body.type
        const slug = body.slug ? body.slug.trim() : null
        switch (type) {
        case "author":
        case "listingPage":
        case "productInfoPage":

            await res.revalidate(`/en-us/${slug}`)

            return res.json({ revalidated: true, "slugToRevalidate": `${slug}` })        
        default:
            return res.json({ revalidated: false,"slugToRevalidate":"NA" })
        }
        
    } catch (err) {
        return res.status(500).send({
            error: err.message,
            message: "Error revalidating"
        })
    }
}

### Expected Behavior

Whenever the /api/revalidate API call, force update the page content in the Live.

### To Reproduce

Webhook url - https://www.xxxxxx.com/api/revalidate

Next JS Application path:  src/pages/api/revalidate.js

export default async function handler(req, res) {

    if (req.method !== "POST") {
        return res
            .status(400)
            .json({ error: "Invalid HTTP method. Only POST requests are allowed." })
    }

    // check for the secret token
    if (req.headers.secret !== process.env.SECRET_TOKEN) {
        return res.status(401).json({ message: "Invalid token" })
    }

    try {
        // check that body is not empty
        const body = req.body
        if (!body) {
            return res.status(400).send("Bad request")
        }
        const type = body.type
        const slug = body.slug ? body.slug.trim() : null
        switch (type) {
        case "author":
        case "listingPage":
        case "productInfoPage":

            await res.revalidate(`/en-us/${slug}`)

            return res.json({ revalidated: true, "slugToRevalidate": `${slug}` })        
        default:
            return res.json({ revalidated: false,"slugToRevalidate":"NA" })
        }
        
    } catch (err) {
        return res.status(500).send({
            error: err.message,
            message: "Error revalidating"
        })
    }
}

**Comment by leerob** [comment]
I was not able to reproduce this with the starter code here.
