### ISSUE TITLE
Next.js on Vercel transforming CSS to invalid syntax - from "@media screen and ..." to "@mediascreenand"

### ISSUE THREAD

**Issue by Southclaws** [vercel/next.js#55246]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Southclaws/storyden

### To Reproduce

I know this isn't a minimal repro but I haven't had time to create one yet. It's also a bit weird because the bug, from what I can tell, does not occur locally, it only occurs *sometimes* while running on Vercel.

A thread with some details: https://twitter.com/Southclaws/status/1701288780638879882
Another issue which I thought was the cause but wasn't: https://github.com/chakra-ui/panda/issues/1345#issuecomment-1712930988

The live CSS is here: https://demo.storyden.org/_next/static/css/1e6cc1a8cc0d24b0.css

The code is here: https://github.com/Southclaws/storyden/tree/main/web

### Current vs. Expected behavior

I would expect CSS to be minified properly on Vercel, I'm not sure if this is some special treatment of Next.js apps on Vercel specifically as it's not happening locally - even outside of dev.

It seems that on Vercel, *all* spaces are being stripped from the CSS file:

<img width="421" alt="image" src="https://github.com/vercel/next.js/assets/1636971/f15c2493-4192-4cbd-aed7-f76c9c5bfa60">

In this example, the top row is the css loaded from http://localhost:3000/_next/static/css/1e6cc1a8cc0d24b0.css and the bottom row is the css loaded from https://demo.storyden.org/_next/static/css/1e6cc1a8cc0d24b0.css exactly the same file, running in `next build && next start` locally, just there are zero syntactical spaces in the CSS served from Vercel.

Locally, I see 136 space characters and on Vercel's served CSS I see 19 - which are all from font names in quotes. Which is interesting because it implies whatever is removing the spaces is AST-aware, it's removing spaces from the CSS syntax itself, but not from string literals such as `Helvetica Neue"`.

In addition to this, the bug seems intermittent. So sometimes I can `curl` the CSS file and it's fine and others it's not fine. I haven't written any edge node specific code in my project, so it's not behaving differently based on any criteria, it's just serving PostCSS from Panda with all the defaults applied.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Node: 20.1.0
      npm: 9.6.4
      Yarn: 1.22.19
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I've hit an interesting new bug, I noticed a lot of styles suddenly stopped working in production. Particularly, one of my media query driven layouts that should hide and show the device-specific navigation component, which falls back to mobile.

Checking the actual css, I can see why the styles aren't loading, the syntax is not even valid CSS. Several instances of `@media screen and (...` have turned into `@mediascreenand(...` which is very odd.

Annoyingly, I can't reproduce this locally, it generates fine:

<img width="158" alt="image" src="https://github.com/chakra-ui/panda/assets/1636971/0d3c7e6f-9fed-4f8d-8a5c-ff897e14ea58">

However, the live site, built with the exact same Next.js, Panda, etc versions (I would assume, it's on Vercel so... who knows what they're doing)

<img width="291" alt="image" src="https://github.com/chakra-ui/panda/assets/1636971/16879d99-9f7b-4e53-9fb9-a054965529f9">

Perhaps a minification issue? But I've never seen this, either with Panda or any other CSS tooling.

**Comment by iamtchelo** [comment]
Hey @Southclaws, how is it going? 👋🏽

Any updates about that? I'm getting the same issue using a `CRA` app.

**Comment by Southclaws** [comment]
I think there are multiple issues here, some related to Vercel and some not.

I think a [bug in Panda CSS](https://github.com/chakra-ui/panda/issues/1325) actually caused the invalid CSS, which caused this code:

```css
  .max-w_container\.sm {
    max-width: container.sm;
  }
```

which resulted in [this file](https://github.com/Southclaws/storyden/blob/b5f7989c23e32c413c9356d218687d01e62e11a4/web/styled-system/styles.css#L735) to be minified by something (Next.js? Vercel?) during deployment. The invalid CSS syntax above caused the minifier to strip all spaces after the `container.sm` for whatever reason.

Then, that invalid CSS got stuck in Vercel's cache which is why it only appeared _sometimes_ (even after a no-cache refresh, both with the keyboard shortcut and with "Disable cache" selected in the browser - this may indicate a bug in Vercel's infrastructure either not adhering to cache invalidation headers or just not propagating that cache invalidation across its edge nodes.)

Either way, the problem eventually went away, I had to wait for the cache to naturally expire I think.

**Comment by Southclaws** [comment]
I think what I would love to see from Next.js or Vercel here is when minifying content from my codebase, if it's invalid then simply skip transforming the content entirely and just serve as-is, this would make investigating codegen pipeline issues much much simpler.

And as for the cache... well it's a cache so, I expect shenanigans 🤷

**Comment by Southclaws** [comment]
Okay scratch that it's still happening, everything I said above seems to be wrong.

No idea where the bug is not, everything works fine locally but not on Vercel so it looks like a Vercel issue.

**Comment by iamtchelo** [comment]
I'm facing the same issue related to invalid CSS syntax because there are a lot of `Stitches` components in my app and Panda's build isn't skipping it. Even though I think isn't a huge problem in order Browser might ignore it since none of new components won't use these styles.

After troubleshooting I noticed that `Cloudflare` minify CSS option was enabled for cached files, then I disabled it and is working as expected now 🙌🏽.

These guides helped me with it:
* [Auto-Minify](https://developers.cloudflare.com/speed/optimization/content/auto-minify/)
* [Default Cache Behavior](https://developers.cloudflare.com/cache/concepts/default-cache-behavior/)

I don't know how minify process works in Vercel under the hood, but you could enable only cache and not minify while your app isn't full with Panda whether it makes sense to you.

**Comment by Southclaws** [comment]
Oh my god @iamtchelo thank you so much! This has been driving me insane 

<img width="695" alt="image" src="https://github.com/vercel/next.js/assets/1636971/72d86068-811c-400d-8917-6519ef60ba45">

I didn't even consider CF, I forgot it was part of our production stack 😅 

Disabling only the CSS optimisation on Cloudflare has solved it, it's not intermittently serving invalid CSS now, but 100% of the time serving the correct content.

It seems their system is sometimes happy with the content and other times not. Perhaps different edge nodes are running different versions of their software...
