### ISSUE TITLE
Error in latest canary: Uncaught SyntaxError: Unexpected token '<' (at

### ISSUE THREAD

**Issue by nicholasgriffintn** [vercel/next.js#55251]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/nicholasgriffintn/next-repo-template

### To Reproduce

1. start the application
2. Navigate to http://localhost:3000/
3. page is blank, should see errors in console log

<img width="844" alt="Screenshot 2023-09-11 at 23 24 09" src="https://github.com/vercel/next.js/assets/12116098/e51c0613-8d23-48a3-9e2f-ff3507ebf463">

### Current vs. Expected behavior

There is no error if downgraded to `13.4.12` (other versions don't work with custom server).

Would expect it to load without error.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
NA
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

It's been hard to make reproductions for any errors with custom server and next lately, I don't know what this error is and it isn't even the one that I was making a repro for!

Haven't been able to update our next version for nearly 8 releases now...

**Comment by ztanner** [comment]
Hi, since your custom server is forwarding `nextHandler` as-is to express, the handler is being called with an invalid third argument (express' `next()` function). If you modify your code to something like the code below, it should behave properly:

```
  app.get("*", nonceMiddleware, (req, res) => {
    nextHandler(req, res);
  });
  ```
