### ISSUE TITLE
lint TP1004 fs.existsSync(???*0*) is very dynamic

### ISSUE THREAD

**Issue by duypham90** [vercel/next.js#55259]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

-

### Describe the Bug

Show Warning on console.log

### Expected Behavior

No show warining

### To Reproduce

Packge.json add option ` --turbo --show-all`
```
npx create-next-app@latest
```
<img width="577" alt="Screenshot 2023-09-12 at 11 57 28" src="https://github.com/vercel/next.js/assets/86216577/a0f7ccb1-d883-45be-a862-c3e397faa5a8">

```json
{
  "name": "nextjs-docker",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbo --show-all",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "20.6.0",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "eslint": "8.49.0",
    "eslint-config-next": "13.4.19",
    "next": "13.4.19",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.3",
    "typescript": "5.2.2"
  }
}

```
<img width="1163" alt="Screenshot 2023-09-12 at 11 55 24" src="https://github.com/vercel/next.js/assets/86216577/c9175242-1099-4682-9c26-6d15b68c6a0e">

**Comment by balazsorban44** [comment]
The log output has been refactored in the latest `canary` and this should not show up anymore. You can upgrade to `next@canary` or wait for the next `latest` release.

_Note: In the future, please report bugs using the [bug report template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml)._

**Comment by duypham90** [comment]
@balazsorban44 
I noted.
Thank you
