### ISSUE TITLE
Docs: Next.js & Cypress Out-of-the-Box Documentation 

### ISSUE THREAD

**Issue by davidlbowman** [vercel/next.js#55281]
### What is the improvement or update you wish to see?

The newest version of Next.js isn't compatible with Cypress out-of-the-box. You need to change the value of `"moduleResolution":` from `"bundler"` to `"node"`  in  `tsconfig.json`.

```json
// tsconfig.json
        "module": "esnext",
        "moduleResolution": "node", // Cypress requires bundler => node
```

This isn't reflected on the Next.js documentation <https://nextjs.org/docs/pages/building-your-application/optimizing/testing>, although is reflected in the `--example with-cypress with-cypress-app` <https://github.com/vercel/next.js/blob/canary/examples/with-cypress/tsconfig.json>.  I also needed to add `"baseUrl": "./"` to my `"compilerOptions": { ... }` in `tsconfig.json`.

Also worth mentioning, they recommend you use the script `"cypress: open": "cypress open"` and not `"cypress": "cypress open". <https://docs.cypress.io/guides/getting-started/opening-the-app>

### Is there any context that might help us understand?

I created the application yesterday using the latest versions of everything. 

```json
{
    "name": "next-demo",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "lint": "next lint",
        "cypress:open": "cypress open"
    },
    "dependencies": {
        "@types/node": "20.6.0",
        "@types/react": "18.2.21",
        "@types/react-dom": "18.2.7",
        "autoprefixer": "10.4.15",
        "cypress": "^13.1.0",
        "eslint": "8.49.0",
        "eslint-config-next": "13.4.19",
        "next": "13.4.19",
        "postcss": "8.4.29",
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "tailwindcss": "3.3.3",
        "typescript": "5.2.2"
    }
}
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/optimizing/testing

**Comment by KSSaiTeja** [comment]
i am interested to work on this issue. I would be happy if some more information is provided about the work should be done

**Comment by sdkdeepa** [comment]
Please see PR raised: https://github.com/vercel/next.js/pull/55801

**Comment by KSSaiTeja** [comment]
ok thanks for the reply.

**Comment by sdkdeepa** [comment]
This PR has been merged. Hence we can close this issue.
