### ISSUE TITLE
Internationalization and not-found page not render

### ISSUE THREAD

**Issue by AlexandreMouyen** [vercel/next.js#55313]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.17.1
      npm: N/A
      Yarn: N/A
      pnpm: 8.6.7
    Relevant Packages:
      next: 13.4.20-canary.26
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

app-dir-i18n-routing

### What browser are you using? (if relevant)

Chrome

### Describe the Bug

When following the Internationalization example, with dynamic lang routing and a middleware, the _not-found.tsx_ file is not render but he NextJs default one.
My _no-found.tsx_ file is located under the dynamic lang (or locale) segment because I want to be able to translate it.

![image](https://github.com/vercel/next.js/assets/27637370/f177b4ee-88b3-475e-91f4-04c46fcaddf4)

I moved all my root file under the dynamic segment as the instruction describe it:

![image](https://github.com/vercel/next.js/assets/27637370/a43afafc-c18e-4aff-8c16-cbfb37163440)

Of course, when I have a root _layout_ and a _no-found.tsx_ files under /app, it is working as expected but without the lang parameter available.

### Expected Behavior

The _not-found.tsx_ file must be render with the lang props.

### To Reproduce

Clone the app-dir-i18n-routing repo, add a simple _not-found.tsx_ file under [lang] repository.

```js
import Link from 'next/link'

export default function NotFound() {
  return (
      <div>
        <h2>Not Found</h2>
        <p>Could not find requested resource</p>
        <Link href="/">Return Home</Link>
      </div>
  )
}
```

Then trigger any route, for example : http://localhost:3000/en/foo.
It is the default 404 page invoked not the previous created one.

**Comment by htkimura** [comment]
Hi @AlexandreMouyen!
1. Where can I clone the `app-dir-i18n-routing` repo to reproduce it?
2. In the [documentation](https://nextjs.org/docs/app/building-your-application/routing/internationalization), the dynamic route is called `lang`, not `locale`. Have you checked this?

**Comment by AlexandreMouyen** [comment]
1. Here the repo : https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing
2. I am using the app router
3. Does not matter, same issue in the example

Thanks

**Comment by htkimura** [comment]
@AlexandreMouyen 
I downloaded the repository, reproduced your bug and managed to resolve it.
I just needed to move my `not-found.tsx` file out of the dynamic route, placing it in the `app` folder.
However, as all pages needs a `layout.tsx`, I just needed to move it to the `app` folder as well and fix the i18n import, obviously.
![image](https://github.com/vercel/next.js/assets/40922048/ea143dbd-4b15-4e37-b857-59fd57cf52cf)
I have read this [discussion](https://github.com/vercel/next.js/discussions/50518) to solve the problem.
I hope this solves your issue :D

**Comment by AlexandreMouyen** [comment]
I am so sorry, but I said that this solution is working but I cannot translate my not-found file like this.
But I may have a clue with the discussion. 

Thanks

**Comment by AlexandreMouyen** [comment]
Dude thank you so much! It is working fine! :D

Very good workaround.

**Comment by AlexandreMouyen** [comment]
Dude thank you so much! It is working fine!

Very good workaround.

**Comment by Minhnhat0408** [comment]
Hey guys, I also follow that https://github.com/vercel/next.js/tree/canary/examples/app-dir-i18n-routing tutor and my folder is basically the same to it. However my problem is: because the middleware always redirect all route to [lang] folder hence there is no way to have metadata in the root url like ('https://example.com/'). I've tried all the possible solutions ( like adding layout.tsx and page.tsx outside the [lang] and inside the app, ignore the layout.tsx in the middleware) but I all doesn't work :
this is my folder structure :
<img width="181" alt="image" src="https://github.com/vercel/next.js/assets/63915841/21b12070-6d01-4e1d-af3f-eeb25a28c0c8">
and also this is the github link: https://github.com/Minhnhat0408/Hub-Media. 
Hope that you guys can help me with it

**Comment by AlexandreMouyen** [comment]
Hi @Minhnhat0408,

I am not really sure I understand what do you want exactly but I needed to add headers for my /api routes so I handle it on the middleware.

Here the matcher: (without excluding /api)

```js
export const config = {
  matcher: [
    // Skip all internal paths (_next)s
    "/((?!_next/static|_next/image|favicon.ico|robots.txt).*)",
  ],
};
```

And inside my middleware I do:

```js
// API middleware
  if (pathname.startsWith("/api")) return NextResponse.next();
```

Like this, all my API route are without the [locale] dynamic routing.

**Comment by Minhnhat0408** [comment]
No, my api route still work fine, cuz the matcher ignore it already, you don't have to code it that way. My problem is with the metadata (opengraph image, title description) like this:
<img width="286" alt="image" src="https://github.com/vercel/next.js/assets/63915841/12457edd-9bb0-4c42-8c1c-780c5974d38a">
You can see that the link without /[lang] is like a fake link 😭. But with the lang 'en' it looks good, that is the metadata power :((.
but I have the problem with it. Do your app has it. tks you anyways, also i do make a issue if you have any idea you can help me out at https://github.com/vercel/next.js/issues/55856 tks very much.

**Comment by AlexandreMouyen** [comment]
My domain name is not good and I do not have description (TODO) but for me it is looks like to work:

![image](https://github.com/vercel/next.js/assets/27637370/0c4c0aeb-a492-4528-bf24-1df9b7840d28)

My default locale is en-US

**Comment by Minhnhat0408** [comment]
wait can I have the github of your code how you do that 💯  or at least just the folder structure and middleware.ts file. Thank you alot maybe this can solve my problem.

**Comment by AlexandreMouyen** [comment]
Yes sure this is my src structure:

![image](https://github.com/vercel/next.js/assets/27637370/84181b8a-c883-46ac-811e-cc0ac4162300)

And this is my middleware:

```js
export async function middleware(request: NextRequest) {
  // Check if there is any supported locale in the pathname
  const {
    nextUrl: { pathname },
  } = request;
  const pathnameIsMissingLocale = LOCALES.every(
    (locale) =>
      !pathname.startsWith(`/${locale}/`) && pathname !== `/${locale}`,
  );
  const acceptLanguage =
    request.headers.get("accept-language") || DEFAULT_LOCALE;
  const headers = {
    "accept-language": acceptLanguage === "*" ? DEFAULT_LOCALE : acceptLanguage,
  };
  const languages = new Negotiator({ headers }).languages() || [DEFAULT_LOCALE];
  const defaultLocale = match(languages, [...LOCALES], DEFAULT_LOCALE);
  const token = await getToken({ req: request });
  const absolutePath = pathnameIsMissingLocale
    ? pathname
    : removeLocaleFromPath(pathname);
  const isApiRoute = pathname.startsWith("/api");
  const passToken = passTokenSecurity(token as JWT | null, absolutePath);
  const passAdmin = passAdminSecurity(token as JWT | null, absolutePath);
  const locale = pathnameIsMissingLocale ? defaultLocale : findLocale(pathname);

  if (pathnameWhiteList.some((p) => pathname.startsWith(p)))
    return NextResponse.next();

  // API routes security check
  if (isApiRoute) {
    if (!passToken) return unauthorized();
    if (!passAdmin) return forbidden();
    return NextResponse.next();
  }

  // UI routes security check
  if (!passAdmin)
    return NextResponse.rewrite(new URL(`/${locale}/not-found`, request.url));
  if (!passToken)
    return NextResponse.rewrite(
      new URL(`/${locale}/unauthorized`, request.url),
    );

  // UI redirect if there is no locale
  if (pathnameIsMissingLocale)
    return NextResponse.redirect(
      new URL(`/${locale}/${pathname}`, request.url),
    );
  return NextResponse.next();
}

export const config = {
  matcher: [
    // Skip all internal paths (_next)s
    "/((?!_next/static|_next/image|favicon.ico|robots.txt).*)",
  ],
};
```

I also have this on my layout.tsx:
```js
export async function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: {
    template: `%s | ${process.env.NEXT_PUBLIC_APP_NAME}`,
    default: process.env.NEXT_PUBLIC_APP_NAME || "Next Template",
  },
  description: "A really complete NextJs template, using Tailwindcss.",
  generator: "Next.js",
  applicationName: process.env.NEXT_PUBLIC_APP_NAME || "Next Template",
  referrer: "origin-when-cross-origin",
  keywords: ["Next.js", "React", "JavaScript", "Tailwindcss"],
  authors: [{ name: "Alexandre Mouyen" }],
  creator: "Alexandre Mouyen",
  publisher: "Alexandre Mouyen",
};
```

Hope it's helps

**Comment by Minhnhat0408** [comment]
wait can I have your repo link 😓 . So you only have layout.tsx in the [locale] and no other file like layout or page outside it. How does it still have metadata. Is your middleware detect current locale and then when navigate, you don't have to pass in the href '/en-Us/services', only '/services' and it auto merge the 'en-Us' (even if they are in en, and switch to fr  it still detect current locale which mean fr). I really really need your repo or if not, can you add me to your discord or something so I can contact with you realtime to fix my bug. thanks alot I hope that you reply soon.
my discord server: https://discord.gg/nsW9SxuD
my discord name MinhMatMong.
