### ISSUE TITLE
`Docs:` `Proposal:` Translation of Next.js Documentation into Spanish

### ISSUE THREAD

**Issue by emapeire** [vercel/next.js#55350]
### What is the improvement or update you wish to see?

Our primary aim is to introduce multilingual documentation within the Next.js framework, starting with the translation of existing content into Spanish:

1. **Translation of Existing Documentation:** The central objective is the translation of the current Next.js documentation from English to Spanish, including guides, tutorials, API references, and documentation pages.

2. **Tailored Content for the Audience:** Translated documentation will be carefully crafted to meet the needs of Spanish-speaking developers, employing clear, concise language to make complex technical concepts accessible.

3. **Collaboration with a Local Team:** A dedicated team of translators and developers is ready to contribute their expertise to ensure the quality and consistency of the translated content, with regular updates to align with Next.js releases.

4. **Community Engagement:** Beyond catering to Spanish-speaking developers, introducing Spanish documentation encourages broader community involvement, fostering discussions, contributions to development, and knowledge sharing.

### Is there any context that might help us understand?

Certainly, providing context is crucial to grasp the rationale behind our proposal:

1. **Language Barriers for Spanish-speaking Developers:** Spanish-speaking developers often face language barriers when trying to comprehend technical documentation in English, hindering their ability to use Next.js effectively.

2. **Global Reach of Next.js:** The absence of localized documentation limits Next.js's potential user base, particularly in Spanish-speaking regions.

3. **Inclusivity and Diversity:** This proposal aligns with Next.js's core principles of inclusivity and diversity, welcoming developers from diverse linguistic backgrounds.

4. **Global Impact:** Addressing the language barrier allows Next.js to better serve developers worldwide, broadening its reach and influence.

5. **Collaborative Effort:** Our proposal involves collaboration with a dedicated team of translators and developers, ensuring the quality and accuracy of the translated documentation.

### Does the docs page already exist? Please link to it.

[nextjs.org](https://nextjs.org)

**Comment by Leprekus** [comment]
I'd love to help out in this task. I am fluent in English and a Native Spanish speaker. Please count me in moving forward.

**Comment by balazsorban44** [comment]
Thank you!

I forwarded this suggestion to our docs team.

As of writing, we think translations would be nice, but we haven't decided yet about how this would look like.

The feedback/interest is appreciated! :green_heart:

**Comment by emapeire** [comment]
> I'd love to help out in this task. I am fluent in English and a Native Spanish speaker. Please count me in moving forward.

Hey @Leprekus if you want to contribute with us, you can join our community on [Github](https://github.com/frontendcomputing) and on [X](https://twitter.com/nextjsargentina). Thanks for you interest!
