### ISSUE TITLE
Server running out of memory with 13.4.19

### ISSUE THREAD

**Issue by MariuzM** [vercel/next.js#55363]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/vercel/next.js

### To Reproduce

Still having `Server running out of memory` issue on 13.4.19 with App Router. 

Nextjs team what are you doing to fix this? Its been really long and still there are issue with this. How are you testing your version when you say App Router is stable but clearly its not... 

### Current vs. Expected behavior

Don't have memory leak issues

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.6.1
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by MariuzM** [comment]
Also my RANT, your advertisement that App Router is Stable is BS, sorry.

**Comment by MariuzM** [comment]
I'm also using Railway App and i cant be sure if this affect Prod or not. I'm the only one using the App right now.
<img width="405" alt="image" src="https://github.com/vercel/next.js/assets/36937039/0bae5617-b0dd-49a8-9260-036f0c1ba936">

**Comment by balazsorban44** [comment]
Check out https://github.com/vercel/next.js/issues/54708. Please read Tim's message carefully.

A link to our own repository is not a valid reproduction. :confused: Please link to yours in the mentioned issue above. Do test out `next@canary` too as fixes are constantly landing there.

**Comment by MariuzM** [comment]
@balazsorban44 guys this i wide issue that people are facing, linking to a private reproduction is not as easy as you guys might think, and also this is not something that will happen straight away even if i have hello world type app.

**Comment by MariuzM** [comment]
@balazsorban44 i dont get why the Railway production log is marked as off topic when i actually show a log of the usage...

**Comment by schoettler** [comment]
> Also my RANT, your advertisement that App Router is Stable is BS, sorry.

Having the same issue. 

I'm running (On a `Dockerfile`, in a `gitlab-runner` 16gb pod):
```
DEBUG=* NODE_OPTIONS=\"--max-old-space-size=8192\" next build"
```

I notice a lot of:
```
next:jsconfig-paths-plugin skipping request as it is inside node_modules
```

Ends up with:
```

<--- Last few GCs --->

[135:0x7f6ae83c20c0]    18734 ms: Scavenge 655.5 (689.9) -> 653.3 (696.2) MB, 15.81 / 0.00 ms  (average mu = 0.993, current mu = 0.992) allocation failure; 
[135:0x7f6ae83c20c0]    18798 ms: Scavenge 661.9 (696.4) -> 659.7 (703.1) MB, 16.67 / 0.00 ms  (average mu = 0.993, current mu = 0.992) allocation failure; 
[135:0x7f6ae83c20c0]    18882 ms: Scavenge 669.0 (703.8) -> 662.4 (709.6) MB, 32.21 / 0.00 ms  (average mu = 0.993, current mu = 0.992) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: NewSpace::EnsureCurrentCapacity Allocation failed - JavaScript heap out of memory
```
I've tried many tweaks, like:
```
const nextConfig = {
  output: 'standalone',
  experimental: {
    esmExternals: false
  }
};
```

But none seem to make it. It runs fine in my 32gb 8core host machine. Do we need to use gigapods for our CI/CD (?).

**Comment by schoettler** [comment]
@MariuzM Lucky you made it work!

We have nearly no images, but wanted to give it a try anyway. Still failed. 

![image](https://github.com/vercel/next.js/assets/1758136/6512510d-96f4-4f14-9fff-e92c5cedc65b)

**Comment by schoettler** [comment]
Different error when using `node:20.7-slim`
![image](https://github.com/vercel/next.js/assets/1758136/679c9c83-55ec-4932-abe9-2c9395050991)
