### ISSUE TITLE
Unable to run dev server with custom hostname

### ISSUE THREAD

**Issue by terrymun** [vercel/next.js#55364]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/terrymun/nextjs-hostname

### To Reproduce

1. Check out https://github.com/terrymun/nextjs-hostname
2. Run `yarn`
3. Add the following entry to your `/etc/hosts` file:

```text
127.0.0.1  local.my-domain.com
```

4. Run `yarn dev`. It is an alias to the command `yarn next dev -p 4567 -H local.my-domain.com`

Docs on the `-H` flag: https://nextjs.org/docs/pages/api-reference/next-cli#development

### Current vs. Expected behavior

Notice that the server is started at `127.0.0.1:4567` instead of `local.my-domain.com:4567`, despite the `-H` flag being set to the value of `local.my-domain.com`.

<img width="363" alt="Screenshot 2023-09-14 at 11 13 59" src="https://github.com/vercel/next.js/assets/5593067/9a39b033-8360-488e-8898-5f73a570de2b">

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.4.20-canary.28
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I noticed this bug as I was upgrading from next@13.4.12. I have then progressively tested each patch version (there is no 13.4.14) and this is the outcome:

| Version             | Does `-H` flag work? |
|:--------------------|:---------------------|
| `13.4.12`           | ✅                   |
| `13.4.13`           | ✅                   |
| `13.4.15`           | ❌                   |
| `13.4.16`           | ❌                   |
| `13.4.17`           | ❌                   |
| `13.4.18`           | ❌                   |
| `13.4.19`           | ❌                   |
| `13.4.20-canary.28` | ❌                   |

**Comment by DuCanhGH** [comment]
It's just the logging, and I've also fixed that (not released to `@canary` yet though). Notice that if you visit http://local.my-domain.com:4567 the page probably still works.

**Comment by terrymun** [comment]
@DuCanhGH Oh thank you! I was so focused on the logging that I didn’t check if the actual custom hostname works or not 😅

**Comment by ztanner** [comment]
As mentioned the logging for this should be fixed in canary. 
<img width="361" alt="CleanShot 2023-09-16 at 10 45 27@2x" src="https://github.com/vercel/next.js/assets/1939140/4e144551-72b3-442d-adb5-8613814c5be2">

Going to close this out feel free to reply if you're still seeing any issues. Thanks!

**Comment by terrymun** [comment]
Thanks for the update @ztanner 👏
