### ISSUE TITLE
Module exports from `next/image` for esm is not correct

### ISSUE THREAD

**Issue by HasikSylphon** [vercel/next.js#55384]
### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/practical-nobel-yzz2df

### To Reproduce

1. add `"type": "module"` to `package.json`, and rename next config to `next.config.mjs`.
2. import `Image` component from `next/image` and render it.
3. start `pnpm dev` and you will see a error page.

### Current vs. Expected behavior

Current: replace `<Image>` to `<Image.defualt>` in JSX, or rename `index.js` to `index.jsx` will work properly.

Expected: just `<Image>` in `index.js` is OK.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 16.17.0
  npm: 8.15.0
  Yarn: 1.22.19
  pnpm: 7.1.0
Relevant Packages:
  next: 13.4.20-canary.28
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

### Additional context

Dive into the `next/dist` code, I found that there is a compatible transform code in bottom of `shared/lib/head.js`:

```js
if ((typeof exports.default === 'function' || (typeof exports.default === 'object' && exports.default !== null)) && typeof exports.default.__esModule === 'undefined') {
  Object.defineProperty(exports.default, '__esModule', { value: true });
  Object.assign(exports.default, exports);
  module.exports = exports.default;
}
```

but no in `shared/lib/image-external.js`.

**Comment by balazsorban44** [comment]
Thanks, tracked in https://github.com/vercel/next.js/issues/52216, there is an open PR #53943 as well.
