### ISSUE TITLE
Docs: Get static paths fallback value issue

### ISSUE THREAD

**Issue by z4nr34l** [vercel/next.js#55432]
### What is the improvement or update you wish to see?

There is an error with example od Dynamic Routes fallback value for Pages Router (value `true` is not working, giving build errors).

### Is there any context that might help us understand?

Reproducing guide:
1. Clone [this repo](https://github.com/z4nr34l/nextjs-preprender-reproduce.git)
2. Run `next build` or `pnpm run build` inside
3. Watch it giving SSG errors

- [x] I'll prepare PR shortly to fix that.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-paths

**Comment by leerob** [comment]
https://github.com/vercel/next.js/pull/55433#issuecomment-1724706069
