### ISSUE TITLE
exports is not defined in Open-Graph ImageResponse(page route api)

### ISSUE THREAD

**Issue by iga00257** [vercel/next.js#55430]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/va3y/grammy-next-edge/blob/next/pages/api/bot.ts

### To Reproduce

Run the dev server and access the route
the og-image issue is the same as the repo url above

```
import { ImageResponse } from '@vercel/og'
import { NextRequest } from 'next/server'

export const config = {
  runtime: 'edge',
}

export default async function handler(request: NextRequest) {
  const { searchParams } = request.nextUrl
  return new ImageResponse(
    (
      <>
        <div
          style={{
            position: 'relative',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            width: '100%',
            height: '100%',
          }}
        />
      </>
    ),
    {
      width: 1200,
      height: 630,
    },
  )
}

```

### Current vs. Expected behavior

in next-13.4.3 the image response work well, but in next 13.16

I got the error in terminal , seems like exports is not supported in 
```
- error Error [ReferenceError]: exports is not defined
- ReferenceError: exports is not defined
    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/compiled/@vercel/og/index.edge.js:3:23)
    at (middleware)/./node_modules/next/dist/compiled/@vercel/og/index.edge.js (/Users/Project/shop-frontend/build/server/pages/api/og/product.js:1845:1)
    at __webpack_require__ (/Users/Project/shop-frontend/build/server/edge-runtime-webpack.js:37:33)
    at Function.fn (/Users/Project/shop-frontend/build/server/edge-runtime-webpack.js:295:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
If any issue is relation with my problem please tell me thanks

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.5.0
    Binaries:
      Node: v20.5.0
      npm: 9.8
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.16-canary.4
      eslint-config-next: 13.4.4
      react: 18.2.6
      react-dom: 18.2.4
      typescript: 5.0.4
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

**Comment by PeterKow** [comment]
Same here, even example code from doc doesn't work, also update nextjs and @vercel/og to latest

**Comment by Ushlerdop** [comment]
@iga00257 @PeterKow hey guys, hello!
 Have you found a solution?

**Comment by dnzg** [comment]
Have the same problem :(

**Comment by tomtobac** [comment]
hey, same issue here.

**Comment by kdy1** [comment]
Closing as fixed on the canary.
<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/dd8074f6-f8eb-4ebb-aa90-7f3b0ad0fad3">
