### ISSUE TITLE
Docs: suggest users to install `sass` as dev dependency instead of dependency

### ISSUE THREAD

**Issue by shuuji3** [vercel/next.js#55444]
### What is the improvement or update you wish to see?

Install `sass` to Use Built-In Sass Support | Next.js - https://nextjs.org/docs/messages/install-sass

When the `sass` package is missing, Next.js shows the above link in the message. But this page suggests installing `sass` as a dependency (not dev dependency), which contradicts the instruction in the main documentation (Styling: Sass | Next.js - https://nextjs.org/docs/pages/building-your-application/styling/sass)

### Is there any context that might help us understand?

Use `--dev` option to install `sass` as dev dependency as explained in the main documentation (Styling: Sass | Next.js - https://nextjs.org/docs/pages/building-your-application/styling/sass).

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/install-sass

**Comment by shuuji3** [comment]
I'm going to send a PR to solve this issue. 🙂

**Comment by leerob** [comment]
It actually doesn't matter, both work 😄 You'll notice that `create-next-app` puts all of the deps inside `dependencies`, as it speeds up installs.

**Comment by shuuji3** [comment]
OK, I didn't know that background. Thank you for reviewing 👍🏻
