### ISSUE TITLE
`useParams` return object values can be `undefined`

### ISSUE THREAD

**Issue by mikedidomizio** [vercel/next.js#55479]
### Link to the code that reproduces this issue or a replay of the bug

[Example repo](https://github.com/mikedidomizio/nextjs-useparams)

[NextJS code](https://github.com/vercel/next.js/blob/canary/packages/next/src/client/components/navigation.ts#L167-L175) 

### To Reproduce

- clone the demo project `git clone git@github.com:mikedidomizio/nextjs-useparams.git`
- install deps `npm install`
- run it `npm run dev`
- go to `http://localhost:3000/test` -> renders fine ✅

| Renders fine |
| - |
| ![CleanShot 2023-09-16 at 13 07 56](https://github.com/vercel/next.js/assets/5728044/c354171c-756a-4354-8a00-a1a5c6a6a98e) |

- go to `http://localhost:3000` -> throws error ❌

| Fails because value inside client component is actually undefined |
| - |
| ![CleanShot 2023-09-16 at 13 08 17](https://github.com/vercel/next.js/assets/5728044/d585701e-8374-4f5c-9ed7-7bae966de491) |

### Current vs. Expected behavior

# Current behaviour

`useParams` is used in client components and since this could potentially be used under a page where the route param is missing, the return type def does not necessarily match reality.

The return type is [`Params`](https://github.com/vercel/next.js/blob/canary/packages/next/src/client/components/navigation.ts#L129-L131) which states the value is `string | string[]`

![CleanShot 2023-09-16 at 12 43 24](https://github.com/vercel/next.js/assets/5728044/1aa2b6cc-2642-4854-8885-0229503467d2)

# Expected behaviour

- Return type should include `undefined`.  The developer should have to check that the param is not `undefined`.  This forces the developer to consider that the value might be `undefined`, handle it accordingly, and avoid things blowing up or working incorrectly.

![CleanShot 2023-09-16 at 13 11 23](https://github.com/vercel/next.js/assets/5728044/c1d6290d-9655-4c7f-bf80-216bd18994c6)

Side note: I think `useParams` should have a different return type than `Params` that can also have value `undefined`.  `Params` is used with function `getSelectedParams` that is definitely returning type `Params` (`{}` if nothing).

## Pros:

- Safer type - a client component could be used in many different ways and not covering your butt could result in issues.

## Cons:

- Having to have logic to check values (additional code complexity) - the developer would be forced to have to check the value before they could use it, but that's a good thing.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 8.7.1
    Relevant Packages:
      next: 13.4.20-canary.33
      eslint-config-next: 13.4.20-canary.33
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

**Comment by balazsorban44** [comment]
This is expected. As per the docs:

> useParams is a Client Component hook that lets you read a route's [dynamic params](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes) filled in by the current URL.

Meaning it is intended to be used under a dynamic route, while you are accessing it in the `app/pahe.js` file, which has no dynamic segments.

**Comment by mikedidomizio** [comment]
Hey @balazsorban44.  I've updated the repo with maybe a clearer (and slightly better) example.  The client component does not understand/care under which dynamic route it's rendering under.

```
app 
├── [post]
│   └── page.tsx
│       └── Component
│           └── ChildComponent (const {post} = useParams) ✅
└── team
    └── [people]
        └── page.tsx
            └── Component
                └── ChildComponent (const {post} = useParams) ❌
```

In a more complex project, a component that uses `useParams` could be many many layers deep, and maybe hard to see until something blows up.

**Comment by GabenGar** [comment]
If the client component doesn't care at which route it renders then it shouldn't have `useParams()` and instead accept the params needed as props. This will also make clear which route requires which params, type-wise.

**Comment by mikedidomizio** [comment]
I guess saying client component "does not care" wasn't right to say as it comes off that the client component should be kept unaware of routes, which maybe it should be kept unaware for simplicity.  Regardless, the return value type does not match what the actual return value could be.  We're fighting the Typescript return type here by saying it's always returning `string | string[]` when that's not true.  It'd be very easy to move routes around and have issues arise, but I guess that'd probably be expected.  Hopefully whoever would have E2E tests to catch this, but otherwise it could go unnoticed.

I understand there's a few ways to work around this issue and maybe better practices like moving `useParams` up and keep the child component(s) simple and void of `useParams`.  It still feels like just moving `useParams` around and you'd probably still end up having to type narrow to either `string` or `string[]` to pass the value in as a prop.

- I guess depending on one's setup, moving components that use `useParams` is always possibly going to be a bit shaky.  Maybe people have accepted that.
- The types don't match the actual return values, but perhaps people are fine with that.
