### ISSUE TITLE
Fetch logging on edge is not working

### ISSUE THREAD

**Issue by gadicc** [vercel/next.js#55495]
### Link to the code that reproduces this issue or a replay of the bug

https://github.com/gadicc/nextjs-fetch-config-weirdness

### To Reproduce

1. `npm run dev` (in one terminal)
2. `npm run test` (in another terminal)

```
 ✓ Compiled /api/configRuntime/route in 126ms (15 modules)
 GET /api/configRuntime 200 in 303ms
 │ GET http://ifconfig.me/ 200 in 4ms (cache: HIT)

 ✓ Compiled /api/runtime/route in 611ms (117 modules)
 GET /api/runtime 200 in 702ms
```

### Current vs. Expected behavior

To my best understanding both routes should behave identically, as the only difference between the two files is:

```ts
// api/configRuntime/route.ts
export const config = { runtime: "edge" }

// api/runtime/route.ts
export const runtime = 'edge'
```

With `config.runtime`, fetch caching works as is shown in the console output above.
With `runtime`, there is no indication that any fetching occurred.

I did notice the big difference in compiled modules in the `runtime` route, so maybe these two setups are meant to behave very differently, but I couldn't find any mention of it in the docs.

**There is no way to sidestep this since `build` fails with the deprecated `config` const**.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Wed, 06 Sep 2023 21:01:01 +0000
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.20-canary.33
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)

<sub>[NEXT-1661](https://linear.app/vercel/issue/NEXT-1661/fetch-caching-on-edge-breaks-when-moving-from-configruntime-to-segment)</sub>

**Comment by huozhi** [comment]
In app router this export syntax of page/route config is not supported. Please checkout the [docs of route segment config](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config)
```ts
export const config = { runtime: "edge" }
```

So it's actually using the node runtime.


The fetch logging on edge was not working properly, I filed #56108 could fix this

**Comment by gadicc** [comment]
Ahhhh gottcha!  Ok great, thanks so much for the quick resolution! :pray:
