### ISSUE TITLE
Extending req/res objects in custom server/standalone mode for App router

### ISSUE THREAD

**Issue by coltonehrman** [vercel/next.js#55548]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js/issues/54440

### To Reproduce

See https://github.com/vercel/next.js/issues/54440

### Current vs. Expected behavior

See https://github.com/vercel/next.js/issues/54440

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
Binaries:
  Node: 16.20.1
  npm: 8.19.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.4.20-canary.37
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.0.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Standalone mode (output: "standalone")

### Additional context

Is this behavior suppose to exist for App router?

Based on the docs here, it seems that extending/modifying the Request object and accessing it in the App router is not possible. How will these use cases which were supported in Pages router be supported in App router?

<img width="695" alt="Screenshot 2023-09-18 at 2 57 04 PM" src="https://github.com/vercel/next.js/assets/12456288/8862e569-74aa-4e95-9566-9f8f8440c3c8">

**Comment by nicholasgriffintn** [comment]
Yeah this is the last thing holding us off from app router if the speed improvements are actually effective (not tried in a while), can't move off of custom server without having to host a proxy in front of next either, so don't really want to do that...

**Comment by kenreis** [comment]
Is this something that will be addressed. We are currently looking into transitioning to the App router, but we rely on extending the req object through our custom server set up. Not having access to the extended request object is a blocker for us.
