### ISSUE TITLE
not able to set cookie from route handler, when making server call

### ISSUE THREAD

**Issue by bharat5604** [vercel/next.js#55549]
### Link to the code that reproduces this issue

https://github.com/bharat5604

### To Reproduce

i am making api call on server component, with access token and refresh token, 
while calling and getting access token from refresh token i am not able to update cookie from route handler i am using route handler as a proxy api

### Current vs. Expected behavior

i am making api call on server component, with access token and refresh token, 
while calling and getting access token from refresh token i am not able to update cookie from route handler i am using route handler as a proxy api

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
i am making api call on server component, with access token and refresh token, 
while calling and getting access token from refresh token i am not able to update cookie from route handler i am using route handler as a proxy api
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

import { NextResponse } from 'next/server';
// import { TOKEN_NAME } from “…”;
import { cookies } from 'next/headers';

export const POST = async (request) => {
  const reqBody = await request.json();
  const { accessToken } = reqBody;
  cookies().set('is-jon-cool', 'absolutely');
  return new Response('working');
};

**Comment by balazsorban44** [comment]
Note, you cannot set cookies from server components. It's hard to tell more without a full reproduction, but that's likely the issue.

Please refer to the docs: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options
