### ISSUE TITLE
Docs: Incorrect Behavior in Matcher Configuration Documentation

### ISSUE THREAD

**Issue by Depender-Sethi** [vercel/next.js#55558]
### What is the improvement or update you wish to see?

The documentation on the page [Building Your Application: Routing Middleware](https://nextjs.org/docs/pages/building-your-application/routing/middleware#matcher) contains inaccurate information regarding the behavior of the matcher configuration for named parameters.

<img width="678" alt="image" src="https://github.com/vercel/next.js/assets/32180131/2f532ac1-c550-406c-9497-95bd75806205">

### Is there any context that might help us understand?

`"next": "13.4.19",`

The documentation currently states:

```javascript
export const config = {
  matcher: "/about/:path",
};
```

It suggests that `/about/:path` matches paths like `/about/a` and `/about/b` but not `/about/a/c`. However, in reality, it matches only the `/about` route itself, behaving the same as `matcher: "/about"` (it doesn't match the second segment of the path).

Additionally, the documentation mentions:

"Configured matchers can use a regular expression enclosed in parentheses: `/about/(.)` is the same as `/about/:path*`"

However, `/about/(.*)` matches only the nested segments of the route (AFTER the `/about`), like `/about/a` or `/about/a/b`.
The middleware will run only on the nested route(s) and not on the `/about` route itself.
Whereas, `/about/:path*` will match `/about` |  `/about/a` | `about/a/b` | `about/a/b/c`

I would appreciate it if the documentation could be updated to accurately reflect the behavior of the matcher configuration, as this could lead to confusion for users.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/routing/middleware#matcher

<sub>[DX-2088](https://linear.app/vercel/issue/DX-2088/docs-incorrect-behavior-in-matcher-configuration-documentation)</sub>

**Comment by shiroyasha9** [comment]
I was able to confirm the behavior that is mentioned here. I am willing to work on this issue and update the documentation accordingly, but the question to be answered before that is - is this a bug or the actual intended usage feature?

The thing about `/about/:path` definitely seems to be a bug, as I believe it should have intercepted `/about/a`
The difference between the regular expression vs the other method is definitely something that should be documented.

**Comment by m-sanders** [comment]
This is a bug.

This has been reported as a bug here: https://github.com/vercel/next.js/issues/53840
