### ISSUE TITLE
the new hook `useFormState` does not work with progressive enhancement

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#55580]
### Link to the code that reproduces this issue

https://github.com/Fredkiss3/form-errors-pe

### To Reproduce

1. Start the application in development (next dev)
2. try to submit the form 
    1. you will see that there are errors which are shown in the form 
4. Now Disable JavaScript and submit the form
5. No error will be shown

### Current vs. Expected behavior

Following the steps from the previous section, i expected the form to behave the same with or without JavaScript enabled with using progressive enhancement, but it seems like it only works only within the client as of now. 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.0.0: Tue Aug 22 02:11:55 PDT 2023; root:xnu-10002.1.11~16/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 8.7.1
    Relevant Packages:
      next: 13.4.20-canary.40
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by shuding** [comment]
Yep, with #55584 Next.js will support this case!

**Comment by Fredkiss3** [comment]
The PR has been merged, so i am closing this issue
