### ISSUE TITLE
Route Interception not yet supported with Turbopack

### ISSUE THREAD

**Issue by padmaia** [vercel/next.js#55592]
### Link to the code that reproduces this issue

https://github.com/vercel-labs/nextgram

### To Reproduce

Run `next dev --turbo` with app that uses route interception

### Current vs. Expected behavior

It should work

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
n/a
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

<sub>[WEB-1609](https://linear.app/vercel/issue/WEB-1609/route-interception-not-yet-supported-with-turbopack)</sub>

**Comment by ForsakenHarmony** [comment]
done
