### ISSUE TITLE
Invalid next.config.js option `optimizePackageImports`

### ISSUE THREAD

**Issue by jasongerbes** [vercel/next.js#55611]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/vercel-next-js-reproduction-template-go8s7s

### To Reproduce

1. Create a new Next.js application: `npx create-next-app@latest`
2. Update the `next.config.js` to match the example below
3. Run `npm run dev`

```js
// next.config.js

/** @type {import('next').NextConfig} */
const nextConfig = {
  optimizePackageImports: [],
}

module.exports = nextConfig
```

### Current vs. Expected behavior

Current behaviour:

```
 ⚠ Invalid next.config.js options detected: 
 ⚠     The root value has an unexpected property, optimizePackageImports, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, configOrigin, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactProductionProfiling, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, target, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
```

Expected behaviour:

As per the [Next.js 13.5 blog post](https://nextjs.org/blog/next-13-5#optimized-package-imports), and [v13.5.1 release notes](https://github.com/vercel/next.js/releases/tag/v13.5.1), `optimizePackageImports` should be a valid option.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 16.18.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 8.3.1
Relevant Packages:
  next: 13.5.1-canary.1
  eslint-config-next: 13.5.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by DenisBessa** [comment]
It works inside `experimental`, even though this information is not on the documentation.
