### ISSUE TITLE
Docs: Markdown not turned into HTML in Dynamic Routes section of Tutorial

### ISSUE THREAD

**Issue by arob26inson** [vercel/next.js#55633]
### What is the improvement or update you wish to see?

The Next.js blog tutorial's example repo uses an older version of the remark library, version 14.0.2. However, running `npm install remark remark=html` will install 15.0.1, which fails to convert markdown into HTML.

## With Remark ^15.0.1 
<img width="1273" alt="image" src="https://github.com/vercel/next.js/assets/120530116/ae4a174c-503f-4fc2-87e6-10afc14acf10">

## With Remark ^14.0.2
<img width="1182" alt="image" src="https://github.com/vercel/next.js/assets/120530116/0d0576de-10fc-44fa-8870-1f64470e9c9e">

On the "Render Markdown" page of the tutorial, `npm install remark remark-html` could be replaced with `npm install remark@^14.02 remark-html` to fix this

### Is there any context that might help us understand?

Picture of relevant code snippet:
<img width="502" alt="image" src="https://github.com/vercel/next.js/assets/120530116/ac142571-2eae-46d7-860e-cfeb93a6a846">

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/basics/dynamic-routes/render-markdown

**Comment by leerob** [comment]
We have since updated the official tutorial: https://nextjs.org/learn

https://github.com/vercel/next-learn
