### ISSUE TITLE
Bugs encountered when testing new features of next.js

### ISSUE THREAD

**Issue by lwt09** [vercel/next.js#55639]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
    Binaries:
      Node: 20.5.1
      npm: 9.8.0
      Yarn: N/A
      pnpm: 8.6.12
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

https://github.com/lwt09/next-feature-demo

### Describe the Bug

I tried to test all the new features of next13 through the official [document](https://nextjs.org/docs), but encountered problems with cache and several other features.

I have listed all the bugs I encountered in the project. [project-address](https://github.com/lwt09/next-feature-demo#%E6%B5%8B%E8%AF%95%E5%BC%82%E5%B8%B8%E7%9A%84-demo)

Below are all the use cases I tested ： 
- APP ROUTER
  - [x] page.tsx
  - [x] layout.tsx
  - [x] error.tsx
  - [x] loading.tsx
  - [x] not-found.tsx
  - [ ] default.tsx ==> [Document is still being written](https://nextjs.org/docs/app/api-reference/file-conventions/default)
  - [ ] template.tsx
  - [x] (group-route)
  - [x] [dynamic-route]
  - [x] @folder-route （parallel-routes）
  - [ ] (..)route (intercepting-routes)
  - [x] router-action (Link + useRouter)
  - [ ] middleware
- Route-handler
  - [x] route.tsx
  - [ ] cache (error!!)
- render
  - [x] server-component
    - [x] static-render
    - [x] dynamic-render
    - [x] stream-render
  - [x] client-component
  - [x] mix-component
- data-fetch
  - [x] fetch API
  - [x] cache
    - [x] broswer-router-cache
    - [x] full-route-cache
    - [x] request-memoization
    - [x] data-cache
- other
  - [x] load script
  - [x] meta data
  - [x] lazy-load
- db
  - [x] prisma
    - [x] postgresql
- socket
  - app 路由下暂不支持 socket, 看 issue 也是切了个 pages 目录出来写 socket
- build!
  - issue:
    - to check
- next-cli
  - [ ] next.config.ts
  - [ ] cli action (eg. create-next-app)

### Expected Behavior

I hope that the conclusions of all cases can be consistent with the documentation

### To Reproduce

All test cases are listed in the app directory. You can try to reproduce the problem through the directory name.

**Comment by Tzxhy** [comment]
next 13.5.1  (..)route (intercepting-routes) failed.  next 13.4.19 works.

**Comment by balazsorban44** [comment]
Thanks, but it's unclear to me what the report is about specifically.

Could you open more focused issue reports, using the [bug report template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml)?


Ideally, a bug report should focus on a single problem, with a clear/minimal reproduction and reproduction steps, explaining how to reproduce that issue.

Make sure to test your code with `next@canary` too (especially after https://nextjs.org/blog/next-13-5) which includes some 400+ bug fixes!

Thanks!
