### ISSUE TITLE
(^13.5.1) dev server rendering duplicate SVG when manipulating SVG in useEffect

### ISSUE THREAD

**Issue by ryparker** [vercel/next.js#55632]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/next-13-5-6-dev-d3-zoom-render-bug-4w6ncz?file=%2FREADME.md

### To Reproduce

1. Run the dev server
2. Click any state in the map SVG to trigger a zoom animation.
3. Notice how the map will render twice. The original map will persist, and a duplicate map will render and zoom into the state.

Next v13.4.20-canary.3

https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.3

Next v13.4.20-canary.2 (expected behavior)

https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.2

### Current vs. Expected behavior

I expected the same behavior as in the previous Next version (v13.4.20-canary.2).

[CodeSandbox - First broken nextjs version (v13.4.20-canary.3)](https://codesandbox.io/p/sandbox/next-13-5-6-dev-d3-zoom-render-bug-4w6ncz?file=%2FREADME.md)

[CodeSandbox - Last working nextjs version (v13.4.20-canary.2)](https://codesandbox.io/p/sandbox/next-13-5-1-dev-d3-zoom-render-bug-working-on-13-4-19-6d779s?file=/README.md:6,47)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 20.5.1
      npm: 9.8.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: v13.4.20-canary.3
      eslint-config-next: 13.5.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

- Working in [v13.4.20-canary.2](https://www.npmjs.com/package/next/v/13.4.20-canary.2)
- Breaks in [v13.4.20-canary.3](https://www.npmjs.com/package/next/v/13.4.20-canary.3)

- This only occurs in dev, prod build/server is fine.

**Comment by al-tron** [comment]
Just wanted to add to this in case it can offer any more insight into the issue. I'm also experiencing duplicate renders on an OpenLayers (v8.0.0) map instance in dev only with Next.js 13.5.1 and above. Nothing has changed in my OpenLayers implementation and it was working in Next.js v13.4.x.

**v13.5.4-canary.9** 
![Screenshot 2023-10-02 180812](https://github.com/vercel/next.js/assets/47892953/b25fff2c-99d6-4782-972a-d49d130e8195)

v13.4.17
![Screenshot 2023-10-02 181120](https://github.com/vercel/next.js/assets/47892953/08834189-e2ee-4014-b74a-22346bc2e3cf)

**Comment by ryparker** [comment]
Still occurs in v14

**Comment by ryparker** [comment]
It seems to have something to do with React strict and a change implemented in next v13.5.1.

Workaround is to set `reactStrictMode: false,` to `next.config.js`

**Comment by ivangrimaldo** [comment]
Hi @ryparker the problem with change to false the value of `reactStricMode` for a big application is that many components take advantage of Next.js restrict mode enabled, and throws many errors. Is really important to solve the problem.

One solution that I found in Stackoverflow, is remove the node in the return of the useEffect:

```
  useEffect(() => {
    return () => {
      d3.selectAll('element').remove();
    }
  }, [])
```

Isn't the best solution but works. 

Did you find an other solution?

**Comment by ryparker** [comment]
> Hi @ryparker the problem with change to false the value of `reactStricMode` for a big application is that many components take advantage of Next.js restrict mode enabled, and throws many errors. Is really important to solve the problem.
> 
> One solution that I found in Stackoverflow, is remove the node in the return of the useEffect:
> 
> ```
>   useEffect(() => {
>     return () => {
>       d3.selectAll('element').remove();
>     }
>   }, [])
> ```
> 
> Isn't the best solution but works.
> 
> Did you find an other solution?

Yes, in my particular D3 example I ended up implementing a similar workaround.

```ts
 const existingG = svg.select('g');
    if (existingG) {
      existingG.remove();
    }
```

The recent nextjs update is what revealed this issue, so I assumed it was nextjs's fault. However it turns out that the bug was introduced in [`v13.4.20-canary.3`](https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.3) which is where `reactStrictMode` was enabled by default for the app router (PR #53375 ). 

For those who are experiencing this issue, knowing that `reactStrictMode` is the root cause is helpful. However I agree that disabling `reactStrictMode` is not a good solution, as the benefit of `reactStrictMode` is that it reveals code smells.

I've learned that this double rendering in strict mode is intentional. It's even explicitly pointed out in [React's docs](https://react.dev/reference/react/StrictMode#fixing-bugs-found-by-double-rendering-in-development):

> [React assumes that every component you write is a pure function.](https://react.dev/learn/keeping-components-pure) This means that React components you write must always return the same JSX given the same inputs (props, state, and context).
> 
> Components breaking this rule behave unpredictably and cause bugs. To help you find accidentally impure code, Strict Mode calls some of your functions (only the ones that should be pure) twice in development. This includes:
> - Your component function body (only top-level logic, so this doesn’t include code inside event handlers)
> - Functions that you pass to [useState](https://react.dev/reference/react/useState), [set functions](https://react.dev/reference/react/useState#setstate), [useMemo](https://react.dev/reference/react/useMemo), or [useReducer](https://react.dev/reference/react/useReducer)
> - Some class component methods like [constructor](https://react.dev/reference/react/Component#constructor), [render](https://react.dev/reference/react/Component#render), [shouldComponentUpdate](https://react.dev/reference/react/Component#shouldcomponentupdate) ([see the whole list](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects))

This might still be a bug on D3's side or at least a documentation opportunity as the cause of this issue is not obvious.
