### ISSUE TITLE
Docs: CSS issue on https://nextjs.org/learn/foundations/about-nextjs

### ISSUE THREAD

**Issue by lennguyen** [vercel/next.js#55634]
### What is the improvement or update you wish to see?

Go to the URL https://nextjs.org/learn/foundations/about-nextjs, you will see the **Start Now** button with layout issue:

a.invert.jsx-1878252255 {
    margin: 0;
    : 0;
    border-radius: 7px;
    color: white;
    background: #0070f3;
    box-shadow: 0 4px 14px 0 rgba(0,118,255,0.39);
    : 0;
    padding: 0 2rem;
    height: 2.5rem;
    line-height: 2.5rem;

Should remove `: 0;` in the CSS.

### Is there any context that might help us understand?

Just CSS issue for Start Now button.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/foundations/about-nextjs

**Comment by leerob** [comment]
Fixed
