### ISSUE TITLE
307 redirect loop when using locale together with middleware in 13.5.1

### ISSUE THREAD

**Issue by c0per** [vercel/next.js#55648]
### Link to the code that reproduces this issue

https://github.com/c0per/307-loop-i18n-middleware

### To Reproduce

1. set `defaultLocale` to something different than `preferredLocale` (from header `accept-language`)
2. npm run dev
3. access `http://localhost:3000/en` or `http://localhost:3000/fr` or `http://localhost:3000` or with trailing slash

### Current vs. Expected behavior

<img width="1904" alt="image" src="https://github.com/vercel/next.js/assets/60544162/f3ae5e4f-5f9c-4fd2-9e73-06f878725bf1">

Currently, Next.js 13.5.1 will stuck in 307 loop if:
- turn on `localeDetection` (which is enabled by default)
- set `defaultLocale` different from user's `preferredLocale`
- use a middleware

Expected behavior:

It doesn't stuck.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.5.1
      eslint-config-next: 13.5.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Internationalization (i18n)

<sub>[NEXT-2627](https://linear.app/vercel/issue/NEXT-2627/307-redirect-loop-when-using-locale-together-with-middleware-in-1351)</sub>

**Comment by c0per** [comment]
I tried to track down this bug.

(I'm not sure about the following investigation)
1. When accessing `localhost:3000/en`, nextjs do a "internal" redirect to `/` with locale set to `en`. **Won't send redirect request to browser**
2. Then nextjs will handle `/` request.

Now `detectedLocale` becomes `preferredLocale` (`accept-language`, in this case `en`)
<img width="524" alt="image" src="https://github.com/vercel/next.js/assets/60544162/091c980b-4201-4941-8763-d35090d31845">

Since `detectedLocale (en) !== defaultLocale` (`fr` in the example), nextjs will send a redirect request to `localhost:3000/en`.
<img width="586" alt="image" src="https://github.com/vercel/next.js/assets/60544162/9479980a-4e54-4139-be05-41763ce1f1a8">

 Thus it's stuck.

**Comment by c0per** [comment]
The bug first appears in version `13.4.20-canary.24`, `13.4.20-canary.23` is fine.

**Comment by SanderRuusmaa** [comment]
Yup, I was waiting for the default locale fix (since it broke after 13.4.12) and now in 13.5.1 the documented default locale prefixing is broken resulting in an infinite loop. Mentioned this here as well.
https://github.com/vercel/next.js/issues/54217#issuecomment-1727466409

**Comment by philipheinser** [comment]
Similar issue https://github.com/vercel/next.js/issues/54495

**Comment by Zerebokep** [comment]
Same issue here, upgrading > 13.4.19 breaks the app with the 307 redirect loop.

**Comment by ioExpander** [comment]
Same issue here. 307 redirect loops on /en after upgrading Next.js.

**Comment by jeremymarc** [comment]
same here

**Comment by danielbarion** [comment]
We are having the same issue, but after testing the Canary releases, I saw the issue started on: 

https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.24

23 works as expected
https://github.com/vercel/next.js/releases/tag/v13.4.20-canary.23

**Comment by raRaRa** [comment]
Same issue.

**Comment by c0per** [comment]
An easy workaround would be turning off `detectLocale`.

Accessing `/page` will go to `/${default locale}/page` instead of `/${accept-language header in user request}/page`.

**Comment by raRaRa** [comment]
Client-side routing is also broken with localization when middleware file is present. The locale always becomes the default locale when clicking on a <Link /> that routes do something such as https://page.com/de - it returns 404. If I do a refresh on that route (server-side routing) then it works.

**Comment by piekczyk** [comment]
> An easy workaround would be turning off `detectLocale`.
> 
> Accessing `/page` will go to `/${default locale}/page` instead of `/${accept-language header in user request}/page`.

this doesn't work

**Comment by masnormen** [comment]
Does the Next team even acknowledge this issue?

Seems to only affect the index route for me.

**Comment by marcinciarka** [comment]
Confirming that:
- having i18n
- having middleware
- having the _not default_ language set in the browser preferences
- up to date next version

breaks the homepage view. Removing one of them fixes the issue (not a fix at all...). Removing locale detection breaks Link components (goes to default language on a page change).

**Comment by raRaRa** [comment]
Based on how things are done in Nextjs App router, I don't really see a fix coming any time soon (almost feels like we're being pushed to the App router). I think the best way forward is to handle i18n manually, without having Nextjs do it magically. 

That means you could follow the strategy on how it's being done in the App router:
1. Create segment for languages, e.g. `/pages/[language]/...`
2. Create page level context that stores the locale, so that you could do something like `const { locale } = usePageContext()` instead of using `useRouter`
3. (optional) Use middleware to detect locale and URL re-write/redirect based on that.

**Comment by soulchild** [comment]
Just ran into this as well. No fix yet, not even an acknowledgement. 

Having to deal with these kinds of issues with every patch- or minor-level Next.js upgrade is getting so frustrating and really makes me wonder if Next.js is still on the right trajectory. Putting that much energy into stuff like RSCs and leaving existing users in the dust with stuff like this will eventually come back to bite you, Vercel. Make the foundations work (middleware AND i18n in the same app is not that unusual, isn't it?), then move on to the fancy stuff.

**Comment by franknoel** [comment]
I have the same issue on v14.0.3 with the pages router. 
Turning off locale detection does fix the issue.

**Comment by raRaRa** [comment]
I ended up removing all NextJS specific locales, which means I had to create a language slug for each language and do some other manual things. In the end it works better and is more bullet proof against breaking changes. This is also the way forward in the App router AFAIK.

**Comment by soulchild** [comment]
This just goes to show that people are losing faith in Vercel and Next.js, IMHO. If we can't use the features a framework provides out of fear they might break at any time, why use a (more fully featured) framework at all? Oh, sorry, I forgot: Streaming components, form fields submitting directly to functions... Who needs working I18n and middlewares if you can have the future™️? 😄

**Comment by mataspetrikas** [comment]
here's something that has worked for us, maybe it will help someone too - In the i18n config, disable the nextJs locale detection, like:

```js
{
  locales: ['en', 'de', 'ja'],
  defaultLocale: 'en',
  defaultNS: 'common',
  localeDetection: false,
 }
```

**Comment by valleywood** [comment]
@raphaelsaunier Thank you so much! 😍 
This actually solved my issue both with the middleware being called and not forcing me to use `trailingSlash: false`.

Was trying something similar like this before but wasn't able to get my rexep right I guess.
Have a wonderful weekend!

**Comment by joaogarin** [comment]
Facing the same problem thanks for pointing out a possible workaround (even if loosing language detection is not that great)

**Comment by EvilaMany** [comment]
Same here. Have infinite redirect problem using next 14

**Comment by TrevorThomp** [comment]
Would love to see an update on this so we can upgrade to v14 for now we are pinned to v13.

**Comment by LoicFpa974** [comment]
> @raphaelsaunier Thank you so much! 😍 Your code together with `localeDetection: false` actually solved my issue both with the middleware being called and not forcing me to use `trailingSlash: false`.
> 
> Was trying something similar like this before but wasn't able to get my regExp right I guess.
> 
> Sounds great if you are able to provide a reproduction repo because is would be good to have both middleware and localeDetection working simultaneously, now it seems one have to choose. 🙏
> 
> Have a wonderful weekend!

Hello, is it possible to provide us a complete example for disabling localeDetection without i18n, please?

Thanks in advance!

Best 
Loïc

**Comment by lass-tanzen** [comment]
Using next@14.0.4

Having the same 307 loop problem when localeDetection is true and using middleware.
I don't want to disable the localeDetection because it is an amazing feature, that the user is automatically redirected to the right locale url.

But if I add a middlwware.ts the 307 problem occurs.

```
// middleware.ts
export async function middleware(req: NextRequest) {
  console.log('hello')
}

**Comment by MartinDavi** [comment]
@leerob This broke our production environment. This ticket has a reproduction in it. What more needs to happen to get responses from Vercel?

**Comment by krzysiek1507** [comment]
Hey @samcx. Sorry for pinging but would you be able to take a look?

**Comment by Omar-Al-Ashi** [comment]
For me, I was able to fix this issue with adding `trailingSlash: true` to my next.config.js.

Try it and let me know if it fixes the issue

**Comment by masnormen** [comment]
hi, i tried to fix this in #62435. kindly check it out

**Comment by petrovmiroslav** [comment]
The issue still reproduce in v14.1.2.
Redirect loop appears after adding any middleware.ts, even if it looks like
```
import {NextResponse} from "next/server";

export const middleware = () => {
  return NextResponse.next();
};
```

**Comment by petrovmiroslav** [comment]
The issue still reproduces in v14.1.2.
Redirect loop appears after adding any middleware.ts, even if it looks like
```
import {NextResponse} from "next/server";

export const middleware = () => {
  return NextResponse.next();
};
```

**Comment by samcx** [comment]
@petrovmiroslav Can you share with us a <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> ?

**Comment by petrovmiroslav** [comment]
[https://github.com/petrovmiroslav/next_redirect_loop_issue](https://github.com/petrovmiroslav/next_redirect_loop_issue)
I tested in Chrome 121.0.6167.184

**Comment by diegopalat** [comment]
@ijjk in which version of next your pr is going to be included? thanks!

**Comment by samcx** [comment]
@diegopalat It's also perfectly fine to use the latest canary!

**Comment by ijjk** [comment]
Hi, the above fix is now available in `v14.1.3`, please update and give it a try!

**Comment by balonso-bemobile** [comment]
It's not fixed. Infinite loop appears without the 307 redirect.

**Comment by samcx** [comment]
@balonso-bemobile Can you create a <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> with those so we can take a look?

**Comment by ioExpander** [comment]
> Hi, the above fix is now available in `v14.1.3`, please update and give it a try!

I've tested on my side and I had to delete the build cache for the issue to dissapear. After that, so far, I'm not able to reproduce the redirect loop even with different combinations of the browser locale and defaultLocale settings.

It would be great to hear from others before sending this to production. 🚀

**Comment by balonso-bemobile** [comment]
@samcx here is the repo which reproduces the issue: https://github.com/borjalo/middleware-307-repro

Attaching video also:
https://github.com/vercel/next.js/assets/117664913/c715ff68-3250-4a62-b1e7-ff2fe7c8d0db

**Comment by ken-blanchard** [comment]
I still have the redirect loop on 14.1.3. When I open my dev tools with [disable cache] the looping stop.

I've cleared my build folder, cleared cache, problem persists.

I notice this in the network tab when the looping happens. 
![image](https://github.com/vercel/next.js/assets/118181922/3cd27184-672b-411e-a81f-e8da44ee35ae)

**Comment by samcx** [comment]
@balonso-bemobile I'm not see any middleware or `i18n` config in your <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture>!

@ken-blanchard Can you share a <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> ?

**Comment by balonso-bemobile** [comment]
@samcx now I've added it, sorry. [https://github.com/borjalo/middleware-307-repro](url)

**Comment by samcx** [comment]
@balonso-bemobile I was not able to replicate this.

Can you also clarify why you'd want to add an rewrite here instead of relying on the default behavior when you add `i18n` in your `next.config.js`?

**Comment by balonso-bemobile** [comment]
@samcx Weird! 😕 I basically want to get the user country from Cloudfront headers.

**Comment by samcx** [comment]
@balonso-bemobile Thank you for the clarification. Is the rewrite still required after getting the Cloudfront headers (still confused with this part)?
