### ISSUE TITLE
Multiple next-router-worker instances duplicated

### ISSUE THREAD

**Issue by azvyae** [vercel/next.js#55649]
### Link to the code that reproduces this issue

https://github.com/azvyae/minimal-repro

### To Reproduce

Just run the application with `npm run dev` then stop the app, the `next-router-worker` wont dismissed and duplicated many times, eating resources

### Current vs. Expected behavior

Here are the screenshot provided

![Screenshot_20230920_164708](https://github.com/vercel/next.js/assets/44611397/fe946a40-21dc-431d-92bc-4d6ac7b875e1)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #7-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 23 15:37:39 UTC 2023
    Binaries:
      Node: 20.3.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: 8.6.6
    Relevant Packages:
      next: 13.5.1-canary.1
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by balazsorban44** [comment]
@azvyae could you try the latest canary? :pray:

https://github.com/vercel/next.js/issues/55631#issuecomment-1727519715

**Comment by azvyae** [comment]
Can confirm that the #55631 and this issue is solved on Next.js v13.5.2-canary.0
