### ISSUE TITLE
Page rerender client component on start

### ISSUE THREAD

**Issue by mkalafior** [vercel/next.js#55651]
### Link to the code that reproduces this issue

https://github.com/mkalafior/next-test/tree/main

### To Reproduce

1. create next app
2. create page.tsx
3. create simple client component
4. add this code to it:
```
  useEffect(() => {
    console.log('mount')
    return () => {
      console.log('unmount')
    }
  }, [])
```
5. run dev mode

### Current vs. Expected behavior

Component is unmounted without specific reason (in console you'll see mount->unmount->mount). On 13.4.12 it works okey.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 3.2.4
      pnpm: 7.14.2
    Relevant Packages:
      next: 13.5.1-canary.1
      eslint-config-next: 13.5.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by balazsorban44** [comment]
This is expected if React Strict Mode is on, which is the case by default.

Read more: https://nextjs.org/docs/app/api-reference/next-config-js/reactStrictMode
