### ISSUE TITLE
Custom server & App router don't share require cache

### ISSUE THREAD

**Issue by coltonehrman** [vercel/next.js#55660]
### Link to the code that reproduces this issue

https://github.com/helloitsjoe/next-custom-server-repro

### To Reproduce

1. Install the repo
2. Log the require cache inside custom server
3. Log the require cache inside App router
4. Run the app
5. Inspect logs

### Current vs. Expected behavior

In the screenshot, you can see the custom server require cache above the red line and below the red line is the App router RSC require cache. They do not match at all and this results in singleton modules breaking when uses across custom server and Next.js App router.

<img width="1800" alt="Screenshot 2023-09-20 at 8 41 39 AM" src="https://github.com/vercel/next.js/assets/12456288/d6f66c35-0539-46e9-9e10-85f02ebb177b">

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
Binaries:
  Node: 16.20.1
  npm: 8.19.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.1
  eslint-config-next: 13.5.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Standalone mode (output: "standalone")

**Comment by coltonehrman** [comment]
More specific issue than https://github.com/vercel/next.js/issues/54782

**Comment by sleeporsmile** [comment]
Perhaps for me this problem leads to a white screen and status code 304
<img width="1728" alt="Screenshot 2023-09-21 at 00 24 57" src="https://github.com/vercel/next.js/assets/43747618/e7a5e3c4-bba9-4e08-bb62-711222ae65ab">

**Comment by sleeporsmile** [comment]
<img width="1726" alt="Screenshot 2023-09-25 at 08 25 48" src="https://github.com/vercel/next.js/assets/43747618/45d18dc1-25b6-45d5-913e-9ee4d3ddb856">

**Comment by the-digital-anarchist** [comment]
This still seems to be a issue, I got the same results running in to 304 in Nextjs 13.5.6. With a custom server.

**Comment by coltonehrman** [comment]
This seems to be resolved by using the new experimental config option - https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages
