### ISSUE TITLE
Dynamic imports in npm packages leads to hydration error ( broken >= 13.2, works <= 13.1.0)

### ISSUE THREAD

**Issue by valleywood** [vercel/next.js#55669]
### Link to the code that reproduces this issue

https://github.com/valleywood/reproduction-app-dynamic-component-hydration-error-pages

### To Reproduce

1. Start the application in development (next dev)
2. Go to localhost:3000
Leads to the following hydration error:

<img width="985" alt="Skärmavbild 2023-09-20 kl  17 48 25" src="https://github.com/vercel/next.js/assets/3974008/3d74537b-d38b-4775-9c1f-954f96ddcc87">

Code for the imported package can be found here:
https://github.com/valleywood/reproduction-app-dynamic-component-hydration-error-package

### Current vs. Expected behavior

It should be possible to import a component from another npm repo that contains a dynamically loaded component.
There should be no hydration errors when doing this (and there should be no need of adding `{ ssr: false }` on those components

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 8.3.1
      Yarn: 1.22.10
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2-canary.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Dynamic imports (next/dynamic)

### Additional context

If I import the same component non-dynamically it works fine (but that would of course affect the bundle size)

**Comment by tobbas** [comment]
I can confirm that this is an error fra 13.2.0, works as i should in 13.1.0.
Would be great if someone could look at this.

As a note if someone could look further at this, I had to add `@valleywood:registry=https://npm.pkg.github.com` to my `npmrc` file to be able to install your package.

**Comment by valleywood** [comment]
For those of you that don't want to checkout the reproduction repos here is the code:

**In next solution:**
```
import StartPage from '@valleywood/reproduction-app-dynamic-component-hydration-error-package/index';

export default function Home() {
  console.log('StartPage');
  return <StartPage />;
}
```

**In npm package:**
Page:
```
import React from 'react';

import dynamic from 'next/dynamic';

const Component = dynamic(
  () => import('./Component'), 
);

export const Page = () => {
  return (
    <div>
      Test
      <Component />
    </div>
  );
  
};

export default Page;
```

Dynamically loaded component
```
import React from 'react';

const Component = () => {
  const [num, setNum] = React.useState(0);
  React.useEffect(() => {
    setTimeout(() => {
      setNum(num + 1);
    }, 3000);
  }, [num]);
  return <div>Test Inner {num}</div>;
};

export default Component;
```

**Comment by valleywood** [comment]
Did some more digging into which version this error was introduced in and it showed to be this release:
[v13.1.7-canary.5](https://github.com/vercel/next.js/releases/tag/v13.1.7-canary.5)

Looking into the release notes for that particular release I suspect that it might be this PR that caused this error:
https://github.com/vercel/next.js/pull/45565

@huozhi or @ijjk Can you please have a look at it 🙏 ? (it is preventing us from stepping up to newer version than 13.1.7-canary.4)

**Comment by icyJoseph** [comment]
The reproduction repository makes no sense at all. And I don't mean that with any loaded meaning. 

How can I reproduce this? Is it App router? Pages router? I am trying to break it on a Stackblitz example, but nothing...

Is the issue that your dynamically imported component doesn't have a client directive?

**Comment by valleywood** [comment]
@icyJoseph Can you clarify what you mean with it making no sense at all? 🤔  It's a bare minimum reproduction example. Clone it, run `yarn install` and `yarn dev` and go to `localhost:3000` and you'll notice that you get a hydration error. If you have cloned the code you can see that it is the pages router that is implemented in the reproduction example?

Pages router uses a StartPage component **from another npm package** (the source code is also available in the reproduction example). The StartPage component dynamically imports a component named Component and it is this dynamical import that causes the hydration error. If i change to static import the hydration error goes away.

This error cannot be reproduced without having a next solution that imports a component from another npm-package so unfortunately it can be reproduced in your stackblitz example (which also uses the App router).

However it should be easy to clone the repo attached to this issue and set it up locally on your machine.

**Comment by icyJoseph** [comment]
Ah apologies, I had clicked on this...

- https://github.com/valleywood/reproduction-app-dynamic-component-hydration-error-package

I see, I'll give it another go, but then this is not similar to the issue I'm chasing. 

Have you tried to trigger it by linking a local package or trying to use workspaces?

**Comment by valleywood** [comment]
> Ah apologies, I had clicked on this...
> 
> * https://github.com/valleywood/reproduction-app-dynamic-component-hydration-error-package
> 
> I see, I'll give it another go, but then this is not similar to the issue I'm chasing.
> 
> Have you tried to trigger it by linking a local package or trying to use workspaces?

Tried in workspace as well (we are developing using workspaces to have hot reloads for changes in our npm packages) and the error is the same.

**Comment by icyJoseph** [comment]
Ah but then 🤔 it might be the same thing, ugh. I ran out of time today. I'll have to set-up a local repository then, if workspaces trigger the same issue then it shall take no time.

Sorry for not being thorough when inspecting your OP.

And as to why the method/source of importing matters... 🤔🤷‍♂️ I'll also look at the commits that happened around that canary.

**Comment by valleywood** [comment]
@icyJoseph Did you ever get the possibility to dig into this any further? 🤔

**Comment by icyJoseph** [comment]
@valleywood sorry, I've been under a mountain of work... and I didn't hear anything back from other issue I was chasing either

Did you try out with Next 14?

**Comment by valleywood** [comment]
@icyJoseph Still the same issue with Next 14. Tested it today with 14.0.3-canary.5.
Really disappointed that it has been almost 2 months since posted this issue and still it hasn't been dispatched by the Next maintainers and no one is assigned to have a look at it.

I've put a lot of effort into tracing the exact commit that introduced this error. I've created a repository that with a bare minimum of code can reproduced the error and still the issue is in Open-mode with no one seeming to care.

Also tested updating to Node 20+ and Yarn 4+ but same error:

```
 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.9.0
      npm: 10.1.0
      Yarn: 4.0.1
      pnpm: N/A
    Relevant packages:
      next: 13.1.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by icyJoseph** [comment]
@valleywood I might be totally wrong here, but shouldn't your tsconfig, have:

```json
 "module": "ESNext",
```

**Comment by valleywood** [comment]
> @valleywood I might be totally wrong here, but shouldn't your tsconfig, have:
> 
> ```json
>  "module": "ESNext",
> ```

@icyJoseph Unsure of which of the two repos you are referring to but typescripts module configuration is case-insensitive if you are referring to the tsconfig file here: `reproduction-app-dynamic-component-hydration-error-pages/tsconfig.json`

However i don't think that ESM/CommonJS mode is related to this bug.

It might actually be the case that this has never worked. I tested to make the dynamically loaded a bit bigger than just containing `Test Inner {num}`. I added a couple of thousands of dummy chars to the component and suddenly i got the same error even if i reverted to Next version `13.0.0` which actually indicates that the problem has been there all the time.

This dependency chain might not ever have worked:
**Next app => Npm package => Component => Dynamically loaded component** (using dynamic from next/dynamic)

If I remove that the dynamically loaded component (as well as the component that loads it) is place in another npm package everything works fine i.e.
**Next app => Component => Dynamically loaded component** (using dynamic from next/dynamic) works just fine

**Comment by valleywood** [comment]
> In the "package" repository you should have esnext, but you have commonjs.
> 
> And I think that the issue might be the import function and how it is being resolved when transpiling the code.

I've tried this now and made the other changes needed to convert the reproduction package to a ES Module but it didn't make any difference when it comes to the hydration error. 

(Also it wont be as easy to convert my real projects from exporting CommonJS to ESM, believe me, I wasted a lot of time on that a while ago 😅)

**Comment by huozhi** [comment]
@valleywood can you update your reproduction that to be able to install the package from npm directly or contain the package inside the repro? I've tried the approach mentioned above but still cannot install packages from your reproduction.

> As a note if someone could look further at this, I had to add @valleywood:registry=https://npm.pkg.github.com/ to my npmrc file to be able to install your package.

**Comment by valleywood** [comment]
@huozhi Updated the reproduction package to be available from npm (moving it from github)
https://www.npmjs.com/package/reproduction-app-dynamic-component-hydration-error-package

Also updated the reproduction repo that uses the reproduction package to now also point to the npmjs version of the package.

Also granted you access to the package repo.

Note that the key takeaway is this:

From https://github.com/valleywood/reproduction-app-dynamic-component-hydration-error-package/blob/master/index.tsx

```
// This leads to hydration error in the next-project
const Component = dynamic(
  () => import('./Component'), 
);

// Switching from dynamic to this makes the hydration error go away in the next-project
//import Component from './Component';
```

**Comment by vunguyen10111995** [comment]
I still got the problem when trying to import dynamic component with ssr.
Can you guys help me?

**Comment by huozhi** [comment]
If you're using any `next/dynamic` inside 3rd party packages, you need to have ESM export and have it transpiled by next.js with [transpilePackages config](https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages) in next.config.js. Otherwise they're not be picked up as `next/dynamic` components. The reason is `next/dynamic` need special transform.

If you're using CJS, like below.
```js
const { default: dynamic } = require('next/dynamic')

dynamic(() => ....)
```
Next.js is not able to i dentify the `next/dynamic` calls and apply the proper transform
