### ISSUE TITLE
Server doesn't dynamically load pages/api routes without manual restart

### ISSUE THREAD

**Issue by diogomartino** [vercel/next.js#55672]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/charming-estrela-5hdk46

### To Reproduce

1. Start next server
2. Create an API route (`/src/page/api/test.js`)
```javascript
export default async function handler(req, res) {
  res.status(200).json({ message: "Hello World" });
}

```
3. Try to access http://localhost:3000/api/test

### Current vs. Expected behavior

**Current** 
404 not found

**Expected**
See the endpoint output

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2
    Binaries:
      Node: 18.17.1
      npm: 9.6.7
      Yarn: 1.22.19
      pnpm: 7.33.5
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

This only happens with the first route added. Tested in `13.5.2-canary.2`.

**Comment by desneck** [comment]
[Next 13 App Router Routing](https://nextjs.org/docs/app/building-your-application/routing)

Also, with the app router using handler as the name of the function in the app router is no longer valid use the HTTP method names as the function names instead here is an example API route in Javascript: 

app/api/[YOUR_API]/route.js (Putting you apis in a "api" folder is not necessary)

```
app/api/[YOUR_API]/route.js (Putting you apis in a "api" folder is not necessary)

import { NextResponse } from "next/server";

export async function GET() {

   //SOME LOGIC TO GET THE DATA(This api was used with prisma orm)

  return new NextResponse.json([YOUR_DATA], { status: 200 });
}

//As such if we want to implement a post method to this route : 

export async function POST(Request) {

//YOUR POST LOGIC

return new NextResponse.json() 
}
```
etc...

**Comment by diogomartino** [comment]
@desneck I didn't know that app router already had support for server side routes. If I'm not mistaken when the app router launched the only way we could make an api was exactly as I was doing, I was not aware it had changed. Thank you!
