### ISSUE TITLE
Minification causes "TypeError: Expected signal to be an instanceof AbortSignal" error with NextJS 13.5 + Azure Blob Storage 12.16.0

### ISSUE THREAD

**Issue by jorupp** [vercel/next.js#55682]
### Link to the code that reproduces this issue

https://github.com/jorupp/next-azure-blob-repro

### To Reproduce

1. Set `STORAGE_ACCOUNT_NAME` and `STORAGE_ACCOUNT_KEY` to the name/key of an Azure Storage account (it doesn't need to have any blob containers or blobs in it).
2. `npm run build`
3. `npm run start`
4. Go to <http://localhost:3000>

### Current vs. Expected behavior

Expected: show the number of blob containers in the storage account.

Actual:
```
TypeError: Expected signal to be an instanceof AbortSignal
    at new G (C:\projects\personal\next-azure-blob\.next\server\chunks\786.js:29:45773)
    at C:\projects\personal\next-azure-blob\.next\server\chunks\786.js:29:47293
    at new Promise (<anonymous>)
    at Object.J [as default] (C:\projects\personal\next-azure-blob\.next\server\chunks\786.js:29:47245)
    at eN.fetch (C:\projects\personal\next-azure-blob\.next\server\chunks\786.js:2:4247)
    at eN.sendRequest (C:\projects\personal\next-azure-blob\.next\server\chunks\786.js:2:1989)
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.17.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2-canary.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

Reverting to 13.4.19 works.  13.4.20-canary.18 works too.  13.4.20-canary.19 doesn't work.

From reviewing https://github.com/vercel/next.js/compare/v13.4.20-canary.18...v13.4.20-canary.19, I suspected https://github.com/vercel/next.js/commit/30da48fcd28b1fc07dcfa06d89b28bec95897d10, where I found `experimental.serverMinification`.  Setting that to `false` in `next.config.js` avoids the issue.

<sub>[WEB-1676](https://linear.app/vercel/issue/WEB-1676/minification-causes-typeerror-expected-signal-to-be-an-instanceof)</sub>

**Comment by jorupp** [comment]
oops, forgot to go back and pick "minification" in the "areas affected" after I figured out that opt-out worked around the issue.

**Comment by lucgagan** [comment]
> From reviewing https://github.com/vercel/next.js/compare/v13.4.20-canary.18...v13.4.20-canary.19, I suspected https://github.com/vercel/next.js/commit/30da48fcd28b1fc07dcfa06d89b28bec95897d10, where I found experimental.serverMinification. Setting that to false in next.config.js avoids the issue.

Thank you a 1000x times!

`experimental.serverMinification` is what was causing my issue too.

https://github.com/vercel/next.js/issues/55683

As far as I can tell, this was enabled and not documented anywhere.

**Comment by jorupp** [comment]
@lucgagan did you search for "85825" in `.next/server/chunks/662.js` to see if you could tell what target library may have been the issue?  I wonder if something that can do an allow/block list for minification may be helpful here (if that's even allowed by the underlying tool).

**Comment by lucgagan** [comment]
It was due to `@napi-rs/image` dependency. Removing it fixed the problem of crashing.

**Comment by alex-statsig** [comment]
https://github.com/vercel/next.js/issues/55833

Causing production issues for me as well, should this not be enabled by default? In my case I think it was `mongoose` dependency

**Comment by feedthejim** [comment]
hey, thanks for opening the issue. Seems an issue with the swc minifier. We're investigating. Also opening a ticket to move it to non experimental config, thanks for the callout @lucgagan

**Comment by crisu83** [comment]
> From reviewing https://github.com/vercel/next.js/compare/v13.4.20-canary.18...v13.4.20-canary.19, I suspected https://github.com/vercel/next.js/commit/30da48fcd28b1fc07dcfa06d89b28bec95897d10, where I found experimental.serverMinification. Setting that to false in next.config.js avoids the issue.

Thanks also 1000x times! This also fixed my issue that was preventing me from uploading files with [@google-cloud/storage](https://www.npmjs.com/package/@google-cloud/storage) from Vercel.

**Comment by hongweitang** [comment]
> Thanks also 1000x times! Adding `serverMinification: false` also fixed my issue that was preventing my app from uploading files with [@google-cloud/storage](https://www.npmjs.com/package/@google-cloud/storage) on Vercel (even though it worked fine locally). I'm using `next@13.5.3`.

Updated to 13.5 and couldn't understand why my build started to fail. `Setting serverMinification: false` helped my build too.

**Comment by kdy1** [comment]
I'm investigating, and seems like this is about SWC minifier breaking `node-fetch`, which is a super common package of ser ver side node js apps
