### ISSUE TITLE
Building with transpilePackages and runtime config on Windows machine produces Windows-only require paths

### ISSUE THREAD

**Issue by longzheng** [vercel/next.js#55697]
### Link to the code that reproduces this issue

https://github.com/longzheng/next-transpile-windows-path-repro

### To Reproduce

1. Open repro project in a Windows environment
2. Install packages `npm install`
3. Build next `npm run build`
4. Copy `.next` folder onto a Linux/macOS machine
5. Run Next server with `npx next start`
6. See server error in terminal

```
% npx next start

  ▲ Next.js 13.5.2
  - Local:        http://localhost:3000

 ✓ Ready in 124ms
Error: Cannot find module 'next/dist\shared\lib\runtime-config.external.js'
Require stack:
- /Users/long/Desktop/test/.next/server/pages/index.js
- /Users/long/Desktop/test/node_modules/next/dist/server/require.js
- /Users/long/Desktop/test/node_modules/next/dist/server/next-server.js
- /Users/long/Desktop/test/node_modules/next/dist/server/next.js
- /Users/long/Desktop/test/node_modules/next/dist/server/lib/start-server.js
- /Users/long/Desktop/test/node_modules/next/dist/cli/next-start.js
- /Users/long/Desktop/test/node_modules/next/dist/lib/commands.js
- /Users/long/Desktop/test/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /Users/long/Desktop/test/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/Users/long/Desktop/test/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at 290 (/Users/long/Desktop/test/.next/server/pages/index.js:1:1394)
    at t (/Users/long/Desktop/test/.next/server/webpack-runtime.js:1:127)
    at 637 (/Users/long/Desktop/test/.next/server/pages/index.js:1:1285)
    at t (/Users/long/Desktop/test/.next/server/webpack-runtime.js:1:127) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/long/Desktop/test/.next/server/pages/index.js',
    '/Users/long/Desktop/test/node_modules/next/dist/server/require.js',
    '/Users/long/Desktop/test/node_modules/next/dist/server/next-server.js',
    '/Users/long/Desktop/test/node_modules/next/dist/server/next.js',
    '/Users/long/Desktop/test/node_modules/next/dist/server/lib/start-server.js',
    '/Users/long/Desktop/test/node_modules/next/dist/cli/next-start.js',
    '/Users/long/Desktop/test/node_modules/next/dist/lib/commands.js',
    '/Users/long/Desktop/test/node_modules/next/dist/bin/next'
  ]
}
```

### Current behaviour

The issue is specific to the combination of two Next.js features, runtime configuration and transpile packages.

**runtime configuration https://nextjs.org/docs/pages/api-reference/next-config-js/runtime-configuration**

I need to use runtime configuration on the server-side with `getServerSideProps`

```tsx
// src/pages/index.tsx
export const getServerSideProps = async () => {
  const { serverRuntimeConfig, publicRuntimeConfig } = getConfig();

  return { props: {} };
};
```

**transpilePackages https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages**

I need to support IE 11 and need to transpile Next.js because otherwise the the client chunks are [not ES5 compatible](https://github.com/vercel/next.js/issues/53821). 

```js
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ['next'],
}
 
module.exports = nextConfig
```

With the combination of the two, when built from a Windows environment, the build output of the server-side JavaScript file `.next\server\pages\index.js` contains the following `require` path with double forward slashes. 
```js
{e.exports=require("next/dist\\shared\\lib\\runtime-config.external.js")}
```
[Full file here](https://gist.github.com/longzheng/aa824bb70d088fdcedc35a0cd0bba6c5)

When built from a Linux/macOS environment, it's 
```js
{e.exports=require("next/dist/shared/lib/runtime-config.external.js")}
```
[Full file here](https://gist.github.com/longzheng/3cac441cb47315146f46ebb73a9ec5a7)

(AFAIK if I run the macOS build with Unix path in Windows environment is fine, but the reverse is not.)

### Expected behaviour
I expect to be able to build from a Windows environment that can be run in a Linux environment.

I expect the output file `.next\server\pages\index.js` to contain 

```js
{e.exports=require("next/dist/shared/lib/runtime-config.external.js")}
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2-canary.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, SWC transpilation

**Comment by kdy1** [comment]
I think https://github.com/vercel/next.js/pull/58517 will fix this, but I need to verify

**Comment by kdy1** [comment]
I'll revisit this once https://github.com/vercel/next.js/pull/60876 is merged

**Comment by kdy1** [comment]
Closing as fixed on next@latest
