### ISSUE TITLE
Docs: If you use translate in chrome, the links start to break and cause an error on the client side

### ISSUE THREAD

**Issue by TrySquadDF** [vercel/next.js#55766]
### What is the improvement or update you wish to see?

I would like to see that the documentation does not break when using the translator in google chrome.
![bugs](https://i.imgur.com/1QBFpsK.gif )

### Is there any context that might help us understand?

when I language through the chrome translate tool some part of the routing stops working

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs

**Comment by Cyral** [comment]
This is a longstanding issue with React and Google translate, not Next: https://github.com/facebook/react/issues/11538
