### ISSUE TITLE
favicon file overwrites icons defined in metadata

### ISSUE THREAD

**Issue by KirillTregubov** [vercel/next.js#55767]
### Link to the code that reproduces this issue

https://github.com/KirillTregubov/nextjs-icons-issue

### To Reproduce

1. Start the application in development (next dev)
2. Inspect Source
3. Verify that `<link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="16x16">` is the only icon in `<head>`

### Current vs. Expected behavior

Following the steps from the previous section, I expect all icons defined in [`app/layout.tsx`](https://github.com/KirillTregubov/nextjs-icons-issue/blob/main/app/layout.tsx) under `export const metadata` to appear in the `<head>` element. But I observe that only `<link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="16x16">` (the favicon) is present.

In other words, my goal is to use both your recommended approach of including a `favicon.ico` file in the correct place, and defining additional (read: different) icons using the `metadata` export.

This correct behaviour can be observed on the [`works` branch](https://github.com/KirillTregubov/nextjs-icons-issue/tree/works), which shows that the issue is a direct result of the `favicon.ico` file handling in `app`. I realize that the reproduction template does not place the favicon in `app`, but both the default template and the [docs](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#favicon) instruct users to place it there.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 18.17.1
      npm: N/A
      Yarn: N/A
      pnpm: 8.7.5
    Relevant Packages:
      next: 13.5.3-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

### Additional context

I find it inconsistent that the `reproduction-template` includes the `favicon.ico` in the `public` folder instead of the `app` directory.

Also please note that your `next info` command has a bug. I am actually on Windows 11 Home, but it says I am on Windows 10.

**Comment by hipdev** [comment]
Hello, you don't need to pass the icons in the Metadata object.
As the [documentation says](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#icon), you just have to put them at the root of the app directory, just make sure to use appropriate icons and give them a name according to the type of icon you want to generate. Nextjs will automatically evaluate the files' metadata and create the appropriate tags within the head.

In the branch that you have as "works", you are trying to manually tell the icons, you just need to add these to the public directory, but I think it is better that you follow the option that is officially recommend in the documentation.

**Comment by KirillTregubov** [comment]
> Hello, you don't need to pass the icons in the Metadata object. As the [documentation says](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#icon), you just have to put them at the root of the app directory, just make sure to use appropriate icons and give them a name according to the type of icon you want to generate. Nextjs will automatically evaluate the files' metadata and create the appropriate tags within the head.
> 
> In the branch that you have as "works", you are trying to manually tell the icons, you just need to add these to the public directory, but I think it is better that you follow the option that is officially recommend in the documentation.

Hey @hipdev! I originally ran into this issue because I was trying to create a link to an SVG `mask-icon` icon used by Safari for the favicon and touch bar (at least in Safari 16). Even if I was to follow your advice and use their filesystem-based approach, they currently only support setting the `favicon` (not applicable), `icon` (which replaces the favicon in Chrome) or `apple-touch-icon` (which is a separate icon used for Safari "favourites" and the iOS bookmark icon) this way.

What I was trying to do, and the underlying bug I'm reporting, is that I wanted to use both their recommended approach with the `favicon.ico` file and define additional icons using the Metadata object. However, this results in only the favicon being included in the generated `<head>` element.

**Comment by hipdev** [comment]
Ohh, now I get it, thanks for clarifying @KirillTregubov 😄, and you're totally right, for the time being there is no a way to mix them, I checked locally, so in order to have a mask-icon you will have to  move any default supported icons inside the app folder to the public folder and use the Metadata object only.

I found this about the topic.
https://github.com/vercel/next.js/issues/48392 

This is a good issue, would be better to allow a mix of both.

**Comment by Rubeanie** [comment]
> > Hello, you don't need to pass the icons in the Metadata object. As the [documentation says](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#icon), you just have to put them at the root of the app directory, just make sure to use appropriate icons and give them a name according to the type of icon you want to generate. Nextjs will automatically evaluate the files' metadata and create the appropriate tags within the head.
> > In the branch that you have as "works", you are trying to manually tell the icons, you just need to add these to the public directory, but I think it is better that you follow the option that is officially recommend in the documentation.
> 
> Hey @hipdev! I originally ran into this issue because I was trying to create a link to an SVG `mask-icon` icon used by Safari for the favicon and touch bar (at least in Safari 16). Even if I was to follow your advice and use their filesystem-based approach, they currently only support setting the `favicon` (not applicable), `icon` (which replaces the favicon in Chrome) or `apple-touch-icon` (which is a separate icon used for Safari "favourites" and the iOS bookmark icon) this way.
> 
> What I was trying to do, and the underlying bug I'm reporting, is that I wanted to use both their recommended approach with the `favicon.ico` file and define additional icons using the Metadata object. However, this results in only the favicon being included in the generated `<head>` element.

It's not a perfect solution, but my workaround involved setting it on the client side through JavaScript.
```javascript
'use client';

import { useEffect } from "react";

export default function Client() {
  useEffect(() => {
    let link = document.querySelector("link[rel='mask-icon']");
    if (!link) {
      link = document.createElement('link');
      link.rel = 'mask-icon';
      link.href = '/pwa/safari-pinned-tab.svg';
      link.color = "#ed5f68";
      document.head.appendChild(link);
    }
  }, []);

  return null;
}
```

**Comment by DaZiYuan** [comment]
I hope to point favicon.ico to the CDN address, because the serverless service I use will waste a calculation if I request ip/faviocn.ico. Is there any solution to solve this?

**Comment by ideletemyself** [comment]
> > > Hello, you don't need to pass the icons in the Metadata object. As the [documentation says](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#icon), you just have to put them at the root of the app directory, just make sure to use appropriate icons and give them a name according to the type of icon you want to generate. Nextjs will automatically evaluate the files' metadata and create the appropriate tags within the head.
> > > In the branch that you have as "works", you are trying to manually tell the icons, you just need to add these to the public directory, but I think it is better that you follow the option that is officially recommend in the documentation.
> > 
> > 
> > Hey @hipdev! I originally ran into this issue because I was trying to create a link to an SVG `mask-icon` icon used by Safari for the favicon and touch bar (at least in Safari 16). Even if I was to follow your advice and use their filesystem-based approach, they currently only support setting the `favicon` (not applicable), `icon` (which replaces the favicon in Chrome) or `apple-touch-icon` (which is a separate icon used for Safari "favourites" and the iOS bookmark icon) this way.
> > What I was trying to do, and the underlying bug I'm reporting, is that I wanted to use both their recommended approach with the `favicon.ico` file and define additional icons using the Metadata object. However, this results in only the favicon being included in the generated `<head>` element.
> 
> It's not a perfect solution, but my workaround involved setting it on the client side through JavaScript.
> 
> ```js
> 'use client';
> 
> import { useEffect } from "react";
> 
> export default function Client() {
>   useEffect(() => {
>     let link = document.querySelector("link[rel='mask-icon']");
>     if (!link) {
>       link = document.createElement('link');
>       link.rel = 'mask-icon';
>       link.href = '/pwa/safari-pinned-tab.svg';
>       link.color = "#ed5f68";
>       document.head.appendChild(link);
>     }
>   }, []);
> 
>   return null;
> }
> ```

Thank you! I spent a very long time trying to find a way to accomplish this as well. I hope they add support for this so we can just add it to the app root dir like the other icons. Thanks again.

**Comment by silash35** [comment]
Still having the same problem. I'm on Next.js version 14.2.3

The following code
```ts
export const metadata: Metadata = {
  ...
  icons: {
    shortcut: "/favicon.ico",
    other: {
      rel: "mask-icon",
      url: "/icons/safari-pinned-tab.svg",
      color: "#f45d22",
    },
  },
};
```
has no effect. Just because there are icons in the app folder, it ignores those in the metadata.

**Comment by rubby-c** [comment]
Still a problem, the metadata is straight up ignored even if there are no icon files in the app folder.
