### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by juskek** [vercel/next.js#55807]
### What is the improvement or update you wish to see?

I tried to use the example shown in [docs](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment) for keeping server code out of client by using the server-only package.

My VSCode is showing the following error:
![image](https://github.com/vercel/next.js/assets/57725347/04ae531d-7c54-4682-a7db-8f2b6f98e493)

### Is there any context that might help us understand?

I'm trying to use it in:
- app
  - page.tsx

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#keeping-server-only-code-out-of-the-client-environment

**Comment by leerob** [comment]
Good answer @joulev!
