### ISSUE TITLE
Next 13.5 server actions hang indefinitely client side 

### ISSUE THREAD

**Issue by kyb3r** [vercel/next.js#55814]
### Link to the code that reproduces this issue

https://github.com/kyb3r/server-action-failing

### To Reproduce

1. Click login on the home page, the middleware will redirect you to /dashboard
2. Now click the submit button, which triggers a server action
3. We are now in a infinite loading state and we cannot access the result from the server action

### Current vs. Expected behavior

Following the steps in the previous section, we never get the result from the server action and we are in a loading state forever. I expect to be able to get the result of the server action. 

In next@13.4.19 this issue did not exist, and if you run the same code on that version it works.

Also something to note is that, if you load /dashboard directly by refreshing the page, the server action works normally. But this issue gets triggered only when we get redirected to /dashboard from middleware. (When you click the login button, we go to /login but get redirected by `middleware.ts` to /dashboard)

If you replace the return statement in the server action with a `redirect()` from `next/navigation`, this issue also prevents redirects due to the infinite loading state.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: N/A
  pnpm: 8.4.0
Relevant Packages:
  next: 13.5.3-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Additional context

This issue also exists in production if deployed to vercel

<sub>[NEXT-1654](https://linear.app/vercel/issue/NEXT-1654/next-135-server-actions-hang-indefinitely-client-side)</sub>

**Comment by OtisTemler** [comment]
Interestingly... I can sometimes observe the same behaviour on my reproduction as well. The server action just never gets resolved correctly and those the client side code never gets to run afterwards. 🤔 / https://github.com/vercel/next.js/issues/55805

**Comment by 4lejandrito** [comment]
I am experiencing this error right now. My server action does never resolve and I get stuck in an infinite loading state. It only happens after a navigation, the second time the same action is triggered by a button click it works fine.

**Comment by lukaskai** [comment]
Same issue here. 13.5.2 release broke it, 13.4.8 works great

**Comment by subvertallchris** [comment]
I am also encountering this. One spot where I have reproduced it is related to a server action that is called from two different pages. My reproduction flow is:

1. Visit page 1 and click the button to trigger a Server Action. This sends a payload and expects a response.
2. Visit page 2 and click the button to trigger the same Action with a different payload. The response hangs and my console says `Fetch failed loading: POST`. 

It works immediately if I then dismiss the loading modal and try the action again. Same view, no changes. If I click the button repeated on the page without navigating, it also works normally!

**Comment by subvertallchris** [comment]
I've been trying for hours and cannot find a workaround other than using `a` tags instead of `Link`. It might also be worth noting that I can reproduce this consistently in local and Node.js development. If anyone finds a better workaround, please share, this is a bad one. :-(

**Comment by kyb3r** [comment]
Thanks for the fix @ztanner, amazing work!

**Comment by 4lejandrito** [comment]
Just tested it and it works! Thanks so much!

**Comment by subvertallchris** [comment]
@ztanner you made my weekend, thank you so much for making this happen on a Friday night!
