### ISSUE TITLE
Form server action firing twice

### ISSUE THREAD

**Issue by Nisfan** [vercel/next.js#55845]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #33-Ubuntu SMP PREEMPT_DYNAMIC Tue Sep  5 14:49:19 UTC 2023
Binaries:
  Node: 19.6.1
  npm: 9.4.0
  Yarn: 1.22.19
  pnpm: 8.7.6
Relevant Packages:
  next: 13.5.3-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

next-forms

### What browser are you using? (if relevant)

brave

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Go to the homepage using the navigation link and click the `Add to Cart` button to submit the form. If you click the button a second time, it will work as expected. To reproduce this issue, you need to navigate from the homepage again.

### Expected Behavior

The form submission action should run only once.

### To Reproduce

1. Clone https://github.com/Nisfan/nextjs-form-double-submission and run it using `pnpm dev`
2. Click `products` link on the home page
3. Click `Machines` link
4. Click Add to cart button
5. Check your terminal; the "addToCart" console log is printed twice.

[Screencast from 2023-09-23 01-09-50.webm](https://github.com/vercel/next.js/assets/22009890/2e4defa5-a8b1-4b76-8224-14b5abb91c93)

https://github.com/Nisfan/nextjs-form-double-submission

<sub>[NEXT-1655](https://linear.app/vercel/issue/NEXT-1655/form-server-action-firing-twice)</sub>

**Comment by hmvmpire** [comment]
Here is your Mistake 
`<button type="submit" disabled={pending}>{pending ? "submitting" : children}</button>`

**Comment by Nisfan** [comment]
@hmvmpire, If the button is within a form, the default behavior is submit.

**Comment by hmvmpire** [comment]
no you have to mention the type of button @Nisfan 
form only do action on button type submit inside it.

**Comment by Nisfan** [comment]
@hmvmpire, 

> The button submits the form data to the server. This is the default if the attribute is not specified for buttons associated with a <form>, or if the attribute is an empty or invalid value
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
