### ISSUE TITLE
Could not navigate to parallel routes with Link component with client-side error

### ISSUE THREAD

**Issue by AnthonyZhang220** [vercel/next.js#55848]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.3-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

docs/02-app/01-building-your-application/01-routing/08-parallel-routes.mdx

### What browser are you using? (if relevant)

116.0.5845.188 (Official Build) (64-bit) (cohort: Stable) 

### How are you deploying your application? (if relevant)

next dev

### Describe the Bug

In the modal example of parallel routes from the doc, we can use parallel routes like this:
![image](https://github.com/vercel/next.js/assets/57048461/f0e29e18-775e-4289-97ae-a5895969f411)
While I almost have the identical folder structure as the modal example, when I click on the login or sign-up button in my header, which supposedly should direct me to the "/login" route, it stays on the "/home" route. The page reports a client-side error "application error: a client-side exception has occurred", and the error in the console isn't very clear and it seems to be related to the router in react.
My folder structure:
![image](https://github.com/vercel/next.js/assets/57048461/0b7a416d-fc50-46e8-b3fe-4eff92165f19)
<Header/>
```
<Link href="/login">
  <Button
    label="Login"
    color="#121314"
    bgColor="#ffffff"
    radius={10}
    paddingX={10}
    paddingY={5}
  />
</Link>
```

### Expected Behavior

I am using parallel routes for my login and signup page using a modal, where the modal is imported from a client-side UI component in my components folder. As the user clicks on the login or signup button, the login or signup modal should pop up, and it should be parallel to any of my root routes.

### To Reproduce

here is my github repo: https://github.com/AnthonyZhang220/nextjs-social-app
Run `npm install` and `npm run dev` to start the project.
In the "/home" route, then click the login button in the header to reproduce the error.

**Comment by REDAMANS** [comment]
Same happened to me, i've followed every step of the documentation but it still reproduces this client-side error

**Comment by Sandy-1711** [comment]
Same here. 
I deployed a multi-page website, here is the 
[link](https://web-accuracy.netlify.app).
When using back button or switching between pages, it shows client side exception error. Check for browser console. 
Earlier I thought It could be because I was trying to access the window.innerWidth in useEffect, but even after I fixed it it is showing me the same error.
