### ISSUE TITLE
Encountered typo on CLI (start/dev) after updating to >=13.5.2

### ISSUE THREAD

**Issue by ray-1337** [vercel/next.js#55871]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/pensive-saha-464fjc

### To Reproduce

Just start the application by using [`npm test`](https://codesandbox.io/p/sandbox/pensive-saha-464fjc)

### Current vs. Expected behavior

**Current behavior:**
> TypeError: Cannot read properties of undefined (reading '0')

**Expected behavior:**
It should works, just like `next dev`.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
CodeSandbox-

Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 16.17.0
  npm: 8.15.0
  Yarn: 1.22.19
  pnpm: 7.1.0
Relevant Packages:
  next: 13.5.3-canary.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

### Additional context

This also happens on nextStart CLI as well.

[next-start](https://github.com/vercel/next.js/blob/canary/packages/next/src/cli/next-start.ts#L35)
[next-dev](https://github.com/vercel/next.js/blob/canary/packages/next/src/cli/next-dev.ts#L131)

I don't know why there is an underscore after `args`.

**Comment by moseffect21** [comment]
I think they changed the way they run the server.
Here is an example of how it was before and how it is now.
![image](https://github.com/vercel/next.js/assets/52028340/314174e1-5abb-44a8-9e36-f964960d3361)

**Comment by ray-1337** [comment]
Man, I didn't think about that earlier. Nice approach.

**Comment by balazsorban44** [comment]
Calling the CLI as the above has not been a documented approach and such, there is no semver guarantees between minor/patch releases. See https://github.com/vercel/next.js/issues/55871#issuecomment-1735097574 for a possible solution.

Optionally refer to the `output: "standalone"` option that will always create a correct `server.js`.

https://nextjs.org/docs/app/api-reference/next-config-js/output#automatically-copying-traced-files
