### ISSUE TITLE
Tailwind hot reload does not work with @latest version using app directory

### ISSUE THREAD

**Issue by tommaay** [vercel/next.js#55881]
### Link to the code that reproduces this issue

https://github.com/tommaay/next-latest-tailwind-issue

### To Reproduce

- Create new NextJS app with `npx create-next-app@latest` and choose to add `Tailwind` and to use `App Router`.
- Start the dev server.
- Open up the root page make any changes to any className styling and you should see that it does not update immediately. It will only update after refreshing the behavior.

The issue is on the latest version of `13.5.2`. I tested it on a previous version for a project I recently worked on which is `13.4.12` and hot reloading for Tailwind works on that version.

### Current vs. Expected behavior

Current: Updating Tailwind CSS classes is not updating and hot reloading.

Expected: The styles should update as changes are made and the file is saved.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.3.1
Relevant Packages:
  next: 13.5.3-canary.3
  eslint-config-next: 13.5.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by tommaton** [comment]
@tommaay did you get this resolved at all as I've tried version `13.5.4` today and it still fails to reload Tailwind CSS
