### ISSUE TITLE
Error while trying HTTPS support for development --experimental-https

### ISSUE THREAD

**Issue by aayman997** [vercel/next.js#55891]
### Link to the code that reproduces this issue

https://github.com/aayman997/test-https

### To Reproduce

1. Create a new Next.js project with version 13.5.0 or above
2. Edit dev script to be `"dev": "next dev --experimental-https"`
3. Run the development server

### Current vs. Expected behavior

Current behavior:
An error occurred while generating a self-signed certificate and the server started with HTTP

Expected behavior:
the self-signed certificate should be created usually and the server run with HTTPS

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: Windows 11 Pro
  Arch: x64
  Version: 22H2
Binaries:
  Node: 18.18.0
  npm: 9.8.1
Relevant Packages:
  next: 13.5.2
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by aayman997** [comment]
error message
![image](https://github.com/vercel/next.js/assets/24213589/2dce9757-f9da-4c3b-86ab-e09886a3841b)
`> my-app@0.1.0 dev             
> next dev --experimental-https

 ⚠ Self-signed certificates are currently an experimental feature, use at your own risk.
   Attempting to generate self signed certificate. This may prompt for your password
 ⨯ Failed to generate self-signed certificate. Falling back to http. Error: Command failed: C:\Users\ahayman\AppData\Local\mkcert\mkcert-v1.4.4-windows-amd64.exe -install -key-file C:\
Users\ahayman\test cer\my-app\certificates\localhost-key.pem -cert-file C:\Users\ahayman\test cer\my-app\certificates\localhost.pem localhost 127.0.0.1 ::1
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at createSelfSignedCertificate (C:\Users\ahayman\test cer\my-app\node_modules\next\dist\lib\mkcert.js:123:37)
    at async runDevServer (C:\Users\ahayman\test cer\my-app\node_modules\next\dist\cli\next-dev.js:282:35)
    at async C:\Users\ahayman\test cer\my-app\node_modules\next\dist\cli\next-dev.js:298:9
    at async Span.traceAsyncFn (C:\Users\ahayman\test cer\my-app\node_modules\next\dist\trace\trace.js:105:20)
    at async nextDev (C:\Users\ahayman\test cer\my-app\node_modules\next\dist\cli\next-dev.js:297:5)
    at async main (C:\Users\ahayman\test cer\my-app\node_modules\next\dist\bin\next:156:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 33308,
  stdout: null,
  stderr: null
}
 ⚠ Port 3000 is in use, trying 3001 instead.
 ⚠ Port 3001 is in use, trying 3002 instead.
  ▲ Next.js 13.5.2
  - Local:        http://localhost:3002

 ✓ Ready in 3.1s
`

**Comment by aayman997** [comment]
Issue reproduced and fixed in [PR](https://github.com/vercel/next.js/pull/55947)
summary there was an error while generating self-signed certificate if there is a folder name that has a space

**Comment by joacub** [comment]
https://github.com/vercel/next.js/issues/55971
