### ISSUE TITLE
Docs: Table rendered in MDX in Images api reference doc

### ISSUE THREAD

**Issue by sheleoni** [vercel/next.js#55904]
### What is the improvement or update you wish to see?

A proper render of the table in the Props section of the Image component docs.

## Source URL
https://nextjs.org/docs/pages/api-reference/components/image
## Issue
Was checking the `<Image />` docs today, seems like the table is not being rendered properly. Happens on both page router & app router docs.
<img width="924" alt="image" src="https://github.com/vercel/next.js/assets/85994674/1d55520d-fd8e-46b7-9811-c1543e4b3fbe">

## Potential Solution
The improper rendering of the table is probably caused by adding `<div style={{ overflowX: 'auto', width: '100%' }}>` before the table ([ref](https://github.com/vercel/next.js/blame/ea148f3581ee9a8a0575b4266f740e0c34387e7f/docs/02-app/02-api-reference/01-components/image.mdx#L42)). Removing it would probably solve the issue.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/components/image

**Comment by leerob** [comment]
Fixed!
