### ISSUE TITLE
High Total Blocking Time in <Image> with placeholder="blur"

### ISSUE THREAD

**Issue by korosu** [vercel/next.js#55913]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/empty-platform-ph7l6k?file=%2Fapp%2Fpage.tsx%3A11%2C1-12%2C1

### To Reproduce
 <Image> with placeholder="blur"
Edit:**sorry I did a mistake** , I can't reproduce it in standalone section
I can only show 2 pages , the only difference is one have blur and one not 
there are big different in lighthouse/[PageSpeed Insights](https://pagespeed.web.dev/) score

https://native.59188866.xyz/          =with blur
https://optimized.59188866.xyz/        =without blur

### Current vs. Expected behavior

with placeholder="blur" will have very high TBT in lighthouse

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.16.1
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: standalone
```

### Which area(s) are affected? (Select all that apply)

App Router

### with placeholder="blur"
![2023-09-24 19.18.11.png](https://s2.loli.net/2023/09/25/5Hcu76C91x8Rsla.png)
![2023-09-24 19.20.44.png](https://s2.loli.net/2023/09/25/fqDhV3JnoLj1EAH.png)

### without placeholder="blur"
![2023-09-24 19.20.09.png](https://s2.loli.net/2023/09/25/gaAcSsn72lBzQxo.png)
![2023-09-24 19.20.51.png](https://s2.loli.net/2023/09/25/qdTS3xfWKePBLVD.png)

**Comment by zanhk** [comment]
Maybe it's a chrome bug as even applying a blur effect to my svg give me the same problem 

```
.footer-background ellipse {
		filter: blur(150px);
}
```

with this went from 100ms to 13,830 ms (100% perfromance to 58)

**Comment by REstolSurf** [comment]
Same problem here. With placeholder="blur" set in the header img TBT = 2600ms to 3500ms, without blur TBT= 0 to 30ms in pagespeed insights , but not testing in lighthouse using chrom devtools.
