### ISSUE TITLE
'"react-dom"' has no exported member named 'experimental_useFormState'. Did you mean 'experimental_useFormStatus'?

### ISSUE THREAD

**Issue by starcraft04** [vercel/next.js#55919]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/happy-dew-pqkvt6?file=%2Fapp%2Fpage.tsx%3A3%2C73

### To Reproduce

1. Go to page.tsx in the App folder
2. Look at the line import { experimental_useFormState as useFormState } from 'react-dom'
3. It says: '"react-dom"' has no exported member named 'experimental_useFormState'. Did you mean 'experimental_useFormStatus'?

### Current vs. Expected behavior

We should be able to use the useFormState. By the way, the useFormStatus is well recognised and can be used...

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Nextjs config:
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverActions: true,
  },
};

module.exports = nextConfig;

package json:
{
  "name": "kraainembc-ssr",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "prettier": "prettier --write ."
  },
  "engines": {
    "node": ">=18.0.0",
    "npm": ">=9.0.0",
    "yarn": "please-use-npm"
  },
  "dependencies": {
    "@clerk/localizations": "^1.25.2",
    "@clerk/nextjs": "^4.23.5",
    "@headlessui/react": "^1.7.17",
    "@heroicons/react": "^2.0.18",
    "@prisma/client": "^5.2.0",
    "@radix-ui/react-alert-dialog": "^1.0.4",
    "@radix-ui/react-navigation-menu": "^1.1.3",
    "@radix-ui/react-popover": "^1.0.6",
    "@radix-ui/react-slot": "^1.0.2",
    "@types/node": "20.5.9",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.0.0",
    "date-fns": "^2.30.0",
    "eslint": "8.48.0",
    "eslint-config-next": "13.4.19",
    "lucide-react": "^0.274.0",
    "next": "13.4.19",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-day-picker": "^8.8.2",
    "react-dom": "18.2.0",
    "react-hot-toast": "^2.4.1",
    "svix": "^1.12.0",
    "tailwind-merge": "^1.14.0",
    "tailwindcss": "3.3.3",
    "tailwindcss-animate": "^1.0.7",
    "typescript": "5.2.2"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.7.1",
    "@commitlint/config-conventional": "^17.7.0",
    "@tailwindcss/forms": "^0.5.6",
    "@typescript-eslint/eslint-plugin": "^6.6.0",
    "prettier": "^3.0.3",
    "prisma": "^5.2.0"
  }
}
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Additional context

I tried to use this in my application in a form to be able to use the server action as described in the link:
https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#how-server-actions-work

Under Error Handling...

**Comment by chungweileong94** [comment]
@starcraft04 It's one of the new hooks (https://github.com/vercel/next.js/pull/55564) that yet to have the type definition, if you ignore the type error it will work just fine.

**Comment by sayantank** [comment]
> @starcraft04 It's one of the new hooks (#55564) that yet to have the type definition.

So, how would one use it then? :/

**Comment by joulev** [comment]
Type definition is being under review in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66726. Subscribe to that PR and upgrade to the latest version of `@types/react-dom` when it's released.

In the meantime I guess just `// @ts-expect-error` because it's only a TypeScript issue due to the lack of type definition.

**Comment by pawelblaszczyk5** [comment]
There is a better option than `// @ts-expect-error`, you can manually copy and create declarations for this hook in your project 😃 

Create a file named e.g. `react.d.ts` in your project and copy this content into it:

```
declare module "react-dom" {
  function experimental_useFormState<State>(
    action: (state: State) => Promise<State>,
    initialState: State,
    permalink?: string
  ): [state: State, dispatch: () => void];
  function experimental_useFormState<State, Payload>(
    action: (state: State, payload: Payload) => Promise<State>,
    initialState: State,
    permalink?: string
  ): [state: State, dispatch: (payload: Payload) => void];
}
```

You should have properly typed `experimental_useFormState` now, you can also reference this project as an example: https://github.com/pawelblaszczyk5/form-state-test

**Comment by esponges** [comment]
I expected this feature to be experimental, but not so experimental that its not even typed

**Comment by connerdassen** [comment]
> There is a better option than `// @ts-expect-error`, you can manually copy and create declarations for this hook in your project 😃
> 
> Create a file named e.g. `react.d.ts` in your project and copy this content into it:
> 
> ```
> declare module "react-dom" {
>   function experimental_useFormState<State>(
>     action: (state: State) => Promise<State>,
>     initialState: State,
>     permalink?: string
>   ): [state: State, dispatch: () => void];
>   function experimental_useFormState<State, Payload>(
>     action: (state: State, payload: Payload) => Promise<State>,
>     initialState: State,
>     permalink?: string
>   ): [state: State, dispatch: (payload: Payload) => void];
> }
> ```
> 
> You should have properly typed `experimental_useFormState` now, you can also reference this project as an example: https://github.com/pawelblaszczyk5/form-state-test

This is overwriting the rest of the types for me: 
![image](https://github.com/vercel/next.js/assets/33068114/634b31e0-f483-4ede-ba74-429e9403765d)

**Comment by pawelblaszczyk5** [comment]
> > There is a better option than `// @ts-expect-error`, you can manually copy and create declarations for this hook in your project 😃
> > Create a file named e.g. `react.d.ts` in your project and copy this content into it:
> > ```
> > declare module "react-dom" {
> >   function experimental_useFormState<State>(
> >     action: (state: State) => Promise<State>,
> >     initialState: State,
> >     permalink?: string
> >   ): [state: State, dispatch: () => void];
> >   function experimental_useFormState<State, Payload>(
> >     action: (state: State, payload: Payload) => Promise<State>,
> >     initialState: State,
> >     permalink?: string
> >   ): [state: State, dispatch: (payload: Payload) => void];
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should have properly typed `experimental_useFormState` now, you can also reference this project as an example: https://github.com/pawelblaszczyk5/form-state-test
> 
> This is overwriting the rest of the types for me: ![image](https://user-images.githubusercontent.com/33068114/270485519-634b31e0-f483-4ede-ba74-429e9403765d.png)

Ah, thanks for spotting this, fixed the example and code snippet 😃

**Comment by starcraft04** [comment]
Hi all,

First thanks a lot for taking this time to support me. I understand but my problem is that on my environment on my local machine, if I reproduce the exact code of the web page : https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations#how-server-actions-work in the section error handling, I get the following error when trying to load the page:

Unhandled Runtime Error
TypeError: (0 , react_dom__WEBPACK_IMPORTED_MODULE_7__.experimental_useFormState) is not a function or its return value is not iterable

So it tells me it is more than the typescript. You can see my package.json above, even though I have set everything as experimental in my next js config file:
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverActions: true,
  },
};
module.exports = nextConfig;

It still cannot find the experimental_useFormState :(.

I have asked a friend and he also installed everything with the same package.json and end up with the same problem...

**Comment by starcraft04** [comment]
Now I changed in my package.json the version from "next": "13.4.19" to "next": "13.5.1" and it seems that it only complains about the typescript. So is this feature only available in 13.5 and not before?

Sorry for the trouble as it was anyway a very good learning on the typescript part...

**Comment by chungweileong94** [comment]
> Now I changed in my package.json the version from "next": "13.4.19" to "next": "13.5.1" and it seems that it only complains about the typescript. So is this feature only available in 13.5 and not before?

Yes, from what I know this feature only available starting from 13.5.

> Now the only typescript error that I have is that the function export async function create(prevState: any, formData: FormData) is shouting about prevState being of type any...

I don't think this is NextJS nor typescript error, but a ESLint errors/warnings, but the `prevState` type should be the same as the `create` function return type.

**Comment by esponges** [comment]
Have you been able to make the `pending` work from `useFormStatus`? Overriding the type declarations makes the TS error go away and the action can be invoked as per the docs, but I have not been able to make the `pending` one work yet

**Comment by pawelblaszczyk5** [comment]
> Have you been able to make the `pending` work from `useFormStatus`? Overriding the type declarations makes the TS error go away and the action can be invoked as per the docs, but I have not been able to make the `pending` one work yet

You need to render the component that uses `useFormStatus` as a child component to the `form` that you submit 😃

**Comment by esponges** [comment]
> > Have you been able to make the `pending` work from `useFormStatus`? Overriding the type declarations makes the TS error go away and the action can be invoked as per the docs, but I have not been able to make the `pending` one work yet
> 
> You need to render the component that uses `useFormStatus` as a child component to the `form` that you submit 😃

Thanks! that solved it. That's a weird API though...

**Comment by balazsorban44** [comment]
Closing in favor of #56041
