### ISSUE TITLE
An error occurred when using the third-party library `async-validator` in Nextjs

### ISSUE THREAD

**Issue by shaxutang** [vercel/next.js#55933]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home China
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.3-canary.3
  eslint-config-next: 13.5.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-turbo

### What browser are you using? (if relevant)

Chrome 117.0.5938.92

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

I created a project using the turbo example `design-system`, in the ui module. I introduced the third-party library `async-validator`, but I got an error when using it.
![image](https://github.com/vercel/next.js/assets/68894989/a72c22e4-54bb-48f2-b460-d969d2ded5ff)
![image](https://github.com/vercel/next.js/assets/68894989/53c2970c-1ce9-448b-b24f-8314513d1ff7)
![image](https://github.com/vercel/next.js/assets/68894989/a6006742-e05b-429f-963e-07443c59f4e6)

### Expected Behavior

I hope `async-validator` can be used normally in nextJs

### To Reproduce

I tried many ways, but in the end I found that after adding the following configuration to package.json under the ui module, this error will appear. If I delete it, everything will be normal.
![image](https://github.com/vercel/next.js/assets/68894989/194c7ab2-99b4-4cfe-98e2-84bbec8714e1)
Currently, this problem is only found in nextjs, but not in vite.

repo: https://github.com/shaxutang/next-asynv-validator-bug

**Comment by balazsorban44** [comment]
After some digging, this seems to be an upstream issue, see https://github.com/yiminghe/async-validator/issues/312
