### ISSUE TITLE
Forwarded request headers are null

### ISSUE THREAD

**Issue by razvanMiu** [vercel/next.js#55942]
### Link to the code that reproduces this issue

https://github.com/razvanMiu/nextjs-forwarded-headers-issue

### To Reproduce

1. Start application in development (npm run dev)
2. Check logged value of `X-Forwarded-Host` header

### Current vs. Expected behavior

Following the steps from the previous section, I expected the `X-Forwarded-Host` to return the current host but I get `null` instead.
I use `X-Forwarded-Host` to forward the server name of nginx and it worked as expected in nextjs <= 13.4.12

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.5.1
      npm: 9.8.0
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.5.2
      eslint-config-next: 13.5.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

The first version that introduced the bug is `13.4.13-canary.0` since reverting to `13.4.12` works as expected

<sub>[NEXT-1663](https://linear.app/vercel/issue/NEXT-1663/forwarded-request-headers-are-null)</sub>

**Comment by juanpin-humane** [comment]
I can confirm this repro steps, it's stopping me from adopting 13.5
