### ISSUE TITLE
CSS Background image not work with unstable_getImgProps()

### ISSUE THREAD

**Issue by officialrajdeepsingh** [vercel/next.js#56009]
### Link to the code that reproduces this issue

https://github.com/officialrajdeepsingh/feedback-unstable_getImgProps

### To Reproduce

1. Clone the following repo: https://github.com/officialrajdeepsingh/feedback-unstable_getImgProps 
2. Run `pnpm dev`

### Current vs. Expected behaviour

First, check out the component.

```tsx
import { unstable_getImgProps as getImgProps } from "next/image";

export default function Home() {
 
  const defaultImageProperty = {
    alt: "follower image",
    width: 1224,
    height: 724,
  };
  const { props: { srcSet: follower } } = getImgProps({
    ...defaultImageProperty,
    src: "/follower.jpg",
  });

/* 
   Example: 1
   background-image: image-set("platypus.png" 1x, "platypus-2x.png" 2x);
*/

/*
  Example : 2
   background-image: -webkit-image-set(
     url("small-balloons.jpg") 1x,
     url("large-balloons.jpg") 2x
   );
   background-image: image-set(
     url("small-balloons.jpg") 1x,
     url("large-balloons.jpg") 2x
   );
*/
    return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      {/* */}
     
      <h1 className="mb-12">Image background with unstable_getImgProps</h1>
      <span>Error: {follower}</span>
      <div
        style={{
          backgroundImage: `image-set('${follower}')`,
          height: "300px",
          backgroundRepeat: "no-repeat",
        }}
        className="container bg-cover bg-center bg-no-repeat mb-12 bg-center h-[1224px] mx-auto"
      >
      </div>
    </main>
  );
}


```
To understand the error or bug

The `{follower}` return following URL.
```
'/_next/image?url=%2Ffollower.jpg&w=1920&q=75 1x, /_next/image?url=%2Ffollower.jpg&w=3840&q=75 2x'
```
It works fine with srcSet, because srcSet accept following path.

```
srcset="logo-768.png 1x, logo-768-1.5x.png 1.5x"
```

But when we use with image-set following URL, it does not expect by `image-set` function.

```css
/* correct */
  background-image: image-set("image-1x.png" 1x, "image-2x.png" 2x);

/* in correct or Bug*/
  background-image:image-set('/_next/image?url=%2Ffollower.jpg&w=1920&q=75 1x, /_next/image?url=%2Ffollower.jpg&w=3840&q=75 2x')
```
## Learn more
[image-set](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set)
[srcSet](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
## Operating system:
Ubuntu 23.04

## Packages:
Chrome: Version 117.0.5938.62 (Official Build) unknown (64-bit)
Node: v18.13.0
pnpm: 8.7.6 
nextjs: 13.5.2
react: 18.2.0
react-dom: 18.2.0
typescript: 5.2.2
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

### Additional context

I test locally with Next.js 13.5.2 and 13.5.4-canary.0 release.

<sub>[NEXT-2122](https://linear.app/vercel/issue/NEXT-2122/css-background-image-not-work-with-unstable-getimgprops)</sub>

**Comment by styfle** [comment]
Unfortunately, `img.srcSet` attribute and `image-set()` css function are not compatible (these are web standards that happen to be different for some reason).

However, I created a PR to update the docs with a function that can convert this string:
- #60739
