### ISSUE TITLE
hydration error caused by next/link legacy

### ISSUE THREAD

**Issue by andrei9669** [vercel/next.js#56022]
### Link to the code that reproduces this issue

https://github.com/andrei9669/next-bug

### To Reproduce

1. start the application
2. open the app

### Current vs. Expected behavior

right now, I get hydration error
expected is to not get it

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.4-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

**Comment by joulev** [comment]
You are nesting <a> (from dangerouslySetInnerHtml) inside another <a> (from JSX). Nesting <a> in <a> is not allowed and results in hydration errors.

**Comment by andrei9669** [comment]
huh, I understand why it is not allowed overall but I fail to understand why would it cause hydration error.

**Comment by joulev** [comment]
I don't know how the hydration engine works behind the scenes, so I can't comment on that, but in general I agree with [this comment on r/nextjs](https://www.reddit.com/r/nextjs/comments/15iya61/comment/juxokgw/?utm_source=share&utm_medium=web2x&context=3)

> 9 times out of 10 hydration errors are due to invalid html. Browsers are very forgiving with bad html and may automatically insert correcting tags. This causes a mismatch between what the server sends and what is rendered on the client.

**Comment by andrei9669** [comment]
aaaah, makes sense, thanks. I will close the post
