### ISSUE TITLE
TypeScript error when using `useFormState`

### ISSUE THREAD

**Issue by leerob** [vercel/next.js#56041]
Hey folks, leaving an issue open here in case people search for this. Currently, there's a TS error you can safely ignore when importing `useFormState`. This is dependent on an upstream issue being merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66726

### Example

```jsx
'use client'
 
 // @ts-ignore
import { experimental_useFormState as useFormState } from 'react-dom'
import { experimental_useFormStatus as useFormStatus } from 'react-dom'
import { createTodo } from '@/app/actions'
 
const initialState = {
  message: null,
}
 
function SubmitButton() {
  const { pending } = useFormStatus()
 
  return (
    <button type="submit" aria-disabled={pending}>
      Add
    </button>
  )
}
 
export function AddForm() {
  const [state, formAction] = useFormState(createTodo, initialState)
 
  return (
    <form action={formAction}>
      <label htmlFor="todo">Enter Task</label>
      <input type="text" id="todo" name="todo" required />
      <SubmitButton />
      <p aria-live="polite" className="sr-only">
        {state?.message}
      </p>
    </form>
  )
}
```

**Comment by pawelblaszczyk5** [comment]
Linking other issue where workaround has been mentioned 😃 https://github.com/vercel/next.js/issues/55919

**Comment by esponges** [comment]
What if i'd wanted to pass arguments to `createTodo`? It's not clear how to type in the docs, and since there are no type declarations yet 🤔

**Comment by Nechir-89** [comment]
I used 

// @ts-expect-error
import { experimental_useFormState as useFormState } from 'react-dom'

and this error displayed in the terminal

 Attempted import error: 'experimental_useFormState' is not exported from 'react-dom' (imported as 'useFormState').

**Comment by ronilsonalves** [comment]
> I used 
> 
> 
> 
> // @ts-expect-error
> 
> import { experimental_useFormState as useFormState } from 'react-dom'
> 
> 
> 
> and this error displayed in the terminal
> 
> 
> 
>  Attempted import error: 'experimental_useFormState' is not exported from 'react-dom' (imported as 'useFormState').
> 
> 

Did you tried to comment with //@ts-ignore ? Are you using Next.js >13.5 version?

Here //@ts-ignore running with this version have worked.

**Comment by Nechir-89** [comment]
> > I used 
> > 
> > 
> > 
> > // @ts-expect-error
> > 
> > import { experimental_useFormState as useFormState } from 'react-dom'
> > 
> > 
> > 
> > and this error displayed in the terminal
> > 
> > 
> > 
> >  Attempted import error: 'experimental_useFormState' is not exported from 'react-dom' (imported as 'useFormState').
> > 
> > 
> 
> Did you tried to comment with //@ts-ignore ? Are you using Next.js >13.5 version?
> 
> Here //@ts-ignore running with this version have worked.

I did try @ts-ignore and got the same error, im having v13.4, do you think the only solution is to update next to v13.5

**Comment by pawelblaszczyk5** [comment]
> > > I used
> > > // @ts-expect-error
> > > import { experimental_useFormState as useFormState } from 'react-dom'
> > > and this error displayed in the terminal
> > > Attempted import error: 'experimental_useFormState' is not exported from 'react-dom' (imported as 'useFormState').
> > 
> > 
> > Did you tried to comment with //@ts-ignore ? Are you using Next.js >13.5 version?
> > Here //@ts-ignore running with this version have worked.
> 
> I did try @ts-ignore and got the same error, im having v13.4, do you think the only solution is to update next to v13.5

13.4 uses older experimental React version which don’t include this hook. So you need to upgrade to 13.5 to use it 😃

**Comment by jakobpack** [comment]
Updating `next' to the latest version, currently `13.5.4` fixed the issue for me.

**Comment by esponges** [comment]
> > > > I used
> > > > // @ts-expect-error
> > > > import { experimental_useFormState as useFormState } from 'react-dom'
> > > > and this error displayed in the terminal
> > > > Attempted import error: 'experimental_useFormState' is not exported from 'react-dom' (imported as 'useFormState').
> > > 
> > > 
> > > Did you tried to comment with //@ts-ignore ? Are you using Next.js >13.5 version?
> > > Here //@ts-ignore running with this version have worked.
> > 
> > 
> > I did try @ts-ignore and got the same error, im having v13.4, do you think the only solution is to update next to v13.5
> 
> 13.4 uses older experimental React version which don’t include this hook. So you need to upgrade to 13.5 to use it 😃

`13.5.4` (latest) still throws the error, I tried `rm -rf node_modules && npm i` before posting this.

**Comment by meech-ward** [comment]
rm -rf .next

**Comment by rfackroyd** [comment]
Hey all, make sure you use the `next.config.js` setting to enable Server Actions:
```
module.exports = {
  experimental: {
    serverActions: true,
  },
}
```
This fixed it for me (I should have set it up front anyway) and explained the error well.

**Comment by JoshWilliams92** [comment]
I was having the same issue with next.js 13.4. I manually installed next@latest react@latest react-dom@latest and the issue persists. After adding // @ts-ignore on the file above import { experimental_useFormState as useFormState } from "react-dom" seemed to fix the issue for me.

**Comment by ctjlewis** [comment]
For now, just pin these versions of the types packages:

```json
{
  "@types/react": "18.2.23",
  "@types/react-dom": "18.2.8",
}
```

**Comment by BaileySimrell** [comment]
<img width="463" alt="Screenshot 2023-10-13 at 8 29 07 PM" src="https://github.com/vercel/next.js/assets/6186817/39a6311b-46ed-4ddc-98f1-6741ba5a9f3d">

I'm able get the import error to go away with ts-ignore, however can't get this thing to compile 

<img width="895" alt="Screenshot 2023-10-13 at 8 29 20 PM" src="https://github.com/vercel/next.js/assets/6186817/3be68f6b-dba4-4d54-9910-c6fe0041cabc">

**Comment by yafkari** [comment]
Error still occuring in `next.js 13.5.5`.

This made the trick for now:

```
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
//@ts-ignore
import { experimental_useFormStatus as useFormStatus } from "react-dom";
```

**Comment by Neftyr** [comment]
Hello guys

To fix linting error I have just changed below packages from:

```json
    "react": "^18",
    "react-dom": "^18",
```

Into:

```json
    "react": "18.2.0",
    "react-dom": "18.2.0",
```

**Comment by morellodev** [comment]
Hi all, the issue still persists on `next@13.5.6` and `@types/react-dom@18.2.14`.

In particular, `@types/react-dom@18.2.14` declares `useFormState` and `useFormStatus` as exported members of `react-dom`, so the following works at the type level:

```ts
import { useFormState, useFormStatus } from "react-dom";
```

but at runtime both of them are `undefined`.

To make things work, I still have to use this workaround:

```ts
import {
  // @ts-expect-error
  experimental_useFormState as useFormState,
  // @ts-expect-error
  experimental_useFormStatus as useFormStatus,
} from "react-dom";
```

but doing so breaks the type inference on `useFormState` usage:

```ts
const [formState, formAction] = useFormState(action, initialState);
//     ^ any      ^ any
```

**Comment by jmd01** [comment]
@morellodev try adding `"types": ["react-dom/experimental"]` to your `tsconfig.json`

```
{
  "compilerOptions": {
    ...
    "types": ["react-dom/experimental"],
  }

```

And then use the import as normal:
```
// MyForm.tsx
import { useFormState } from 'react-dom'
import { useFormStatus } from 'react-dom'

```

I'm using the following versions:
```
  "devDependencies": {
    "@types/react-dom": "18.2.13",
    ...
  }
```

**Comment by morellodev** [comment]
@jmd01 @shawnmclean The issue we are having is due to a misalignment between the members exported by `react-dom` and the types definitions from `@types/react-dom`.

The canary `react-dom` version shipped with Next.js exports `useFormState` and `useFormStatus` with the `experimental_` prefix, while the type defs say they are not prefixed.

**Comment by jmd01** [comment]
@shawnmclean @morellodev I had to also use the latest next, react, react-dom. This is working for me now:

```
    "@types/react": "18.2.29",
    "@types/react-dom": "18.2.13",
    "react": "experimental",
    "react-dom": "experimental",
    "next": "canary",
```
https://github.com/jmd01/next-forms

**Comment by KushibikiMashu** [comment]
@jmd01 
Thanks!  This is also working 👍 

```
{
  "dependencies": {
    "next": "canary",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@types/react": "18.2.30",
    "@types/react-dom": "18.2.14",
  }
}
```

**Comment by neatonk** [comment]
As an alternative to the above workarounds, you can use this shim with next@13.5.6:

```ts
// file: react-dom-shim.ts
import {
  //@ts-expect-error
  experimental_useFormState,
  //@ts-expect-error
  experimental_useFormStatus,
  // types are defined, but exports are not :(
  useFormState as undefined_useFormState,
  useFormStatus as undefined_useFormStatus
} from "react-dom"

export const useFormState = experimental_useFormState as typeof undefined_useFormState
export const useFormStatus = experimental_useFormStatus as typeof undefined_useFormStatus
```

**Comment by morellodev** [comment]
Nice trick @neatonk 👍 BTW, I find a little odd that we have to do all sorts of workarounds in order to get things work, and it is even odder that the official docs and examples from Vercel are misleading.

**Comment by Neftyr** [comment]
We can also switch to JavaScript, no issues there haha

**Comment by Jacob-Daniel** [comment]
Since updating to Next.js 14, the error persisted when importing 'experimental_useFormState':

` // @ts-ignore
import { experimental_useFormState as useFormState } from 'react-dom'`

However the error went away removing 'experimental_useFormState', '@ts-ignore' is still required:

`// @ts-ignore
import { useFormState, useFormStatus } from "react-dom";`

`		"@types/react": "18.2.23",
		"@types/react-dom": "18.2.8",`

**Comment by omburj** [comment]
for https://github.com/vercel/next.js/tree/canary/examples/next-forms
correcting the verion of reac-dom to latest resolves the pnpm run build error
"@types/react": "^18.2.34",
"@types/react-dom": "^18.2.14",
   
OR
option 2 use what @leerob prescribed above add 
2.1
 // @ts-ignore
to the start of add-form.tsx and delete-form.tsx 
2.2
and replace experimental_useFormState with  useFormState 
//import { experimental_useFormState as useFormState } from 'react-dom'
//import { useFormStatus } from 'react-dom'
2.3
and finally remove experimental serverrun from next.config.js making it simple 3 lines as below
/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = nextConfig

**Comment by leerob** [comment]
Yeah, I'd recommend just upgrading to the latest versions for the new types 😄

**Comment by omburj** [comment]
It means alot coming from the author himself to second my suggestion! Thank
you @leerob
😊
BTW, Lee, Just FYI, the latest Node v20 and Next v14 combination is not
getting compiled on AWS amplify.

**Comment by havgry** [comment]
I'm running into `Module '"react-dom"' has no exported member 'useFormStatus'` with @types/react-dom@18.2.14 while 18.2.13 seems to work just fine suggesting it might be more complicated than just updating to the latest versions to resolve the type error. This combination works for me:

```
"@types/react": "18.2.36",
"@types/react-dom": "18.2.13",
```

Just putting it out there in case it helps someone else.

**Comment by rush86999** [comment]
upgrading to the latest versions does not work. 👎

**Comment by leerob** [comment]
I've confirmed everything now works on the latest version of Next.js + types, and updated our example as well.

https://github.com/vercel/next.js/pull/60052

If you are still seeing an issue, please restart your TS server or ensure you have the right TS server selected in your IDE, as there might be multiple.
![CleanShot 2023-12-30 at 14 19 24@2x](https://github.com/vercel/next.js/assets/9113740/1c086438-c4c9-4d7e-b594-43fa81eedaa0)
