### ISSUE TITLE
React-dom included twice to the bundle

### ISSUE THREAD

**Issue by IvanKalinin** [vercel/next.js#56063]
### Link to the code that reproduces this issue

https://github.com/IvanKalinin/next-bundle-bug

### To Reproduce

1. Create a new next project following the docs using the app directory router.
2. Install all dependencies and add the bundle analyzer
3. Build the app and analyze the bundle

### Current vs. Expected behavior

Analyzing the bundle I've found that react-dom is included twice. In the framework chunk and in another chunk with hashed name. Which adds 30-50% (~40kb) of the size to the first load.
<img width="1445" alt="image" src="https://github.com/vercel/next.js/assets/12299212/69f57890-488d-4314-aeaa-33b93bc637bc">

Also despite using only the app folder, it uses the app and main entrypoints.
<img width="404" alt="image" src="https://github.com/vercel/next.js/assets/12299212/989d1952-7dc4-4034-a70b-708f252d9127">
<img width="420" alt="image" src="https://github.com/vercel/next.js/assets/12299212/af72e2ad-d02e-46ce-b93a-e2642a32129d">

I have neither additional dependencies nor custom components. Just a clear installation.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000

Binaries:
  Node: 18.12.1
  npm: 9.4.0

Relevant packages:
  next: 13.5.4-canary.1
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by icyJoseph** [comment]
Hi,

I think one of them is from the old pages router. 

You can verify that, this is not an issue, when you got to an app-router page, the contents of framework-hash are now transferred to the browser. You can literally see the Chrome Dev Tools Network tab reporting how much is actually transferred, and in the list of downloaded stuff framework-hash is nowhere to be seen.

What you have is the static bundle analyser output, which yeah, has detected that a framework chunk was created, and it should probably not have been created, if the app is pure App Router based. I do believe the Next.js is on the verge of finally separating the builds. 

Here's a somewhat similar claim, and my counter argument (from way back this year)

**Comment by balazsorban44** [comment]
As pointed out, the bundle analyzer result is currently expected, but it does not mean it's loaded twice, thanks for the explanation @icyJoseph!
