### ISSUE TITLE
Env Vars without NEXT_PUBLIC Prefix Render on Client-side with App Router

### ISSUE THREAD

**Issue by arakelovd** [vercel/next.js#56064]
### Link to the code that reproduces this issue

https://github.com/vercel/vercel/tree/main/examples/nextjs

### To Reproduce

Using the App router in Next.js, setting an environment variable in the .env file without prefixing it with NEXT_PUBLIC_ still renders the value on the client, unlike the behavior in the Pages router.

Reproduction steps:

1. Clone the Vercel Next.js example app router: https://github.com/vercel/vercel/tree/main/examples/nextjs, create a `.env` file with `NAME=Serge`.

2. Update page.js as follows:

```tsx
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex">
        Hello {process.env.NAME}
      </div>
    </main>
  )
}
```

3. Run `npm run dev` to see the issue.

### Current vs. Expected behavior

Based on the app router documentation, environment variables without the NEXT_PUBLIC_ prefix should not be accessible on the client-side, and should only be accessible in the Node.js environment.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.3
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by matamatanot** [comment]
This is the expected behavior.
The environment variables are not accessible from client side. They are just rendered in JSX elements and run as RSC.
It should not be accessible with 'use client'.
