### ISSUE TITLE
globalThis.process is undefined on client side only

### ISSUE THREAD

**Issue by lhwdev** [vercel/next.js#56070]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/throbbing-sound-twc9fp?file=%2Fnext.config.js%3A6%2C1

### To Reproduce

1. Access globalThis.process in client side
2. It returns undefined

### Current vs. Expected behavior

I don't know if `globalThis.process` being undefined is expected behavior, but I thought it should be consistent with `process`.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 16.17.0
  npm: 8.15.0
  Yarn: 1.22.19
  pnpm: 7.1.0
Relevant Packages:
  next: 13.5.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Additional context

In one file, I defined a variable named `process`, to find out that I need to node `process.env` object.
I was to lazy to rename that `process` variable in the same file, I used `globalThis.process` to access `env`. Vscode and `next lint` did not show any error, and it worked well in server side.
In one day, however, as soon as I used that file in client side, they show me error saying `Cannot read properties of undefined (reading 'env')` ...

**Comment by balazsorban44** [comment]
This is expected. On the client, environment variables are inlined, so you can only access them directly, not the whole `process`.

See: https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser
