### ISSUE TITLE
Route interception not working as expected when using NextResponse.rewrite

### ISSUE THREAD

**Issue by mastoj** [vercel/next.js#56072]
### Link to the code that reproduces this issue

https://github.com/mastoj/nextgram

### To Reproduce

1. Start application in dev mode
2. Go to start page
3. Click photo
4. Refresh page
5. Go back
6. Click another photo

### Current vs. Expected behavior

Actual: In step 3. above a modal is shown, but not in step 6.

Expected: The modal should be shown in step 6 as well.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
Binaries:
  Node: 18.16.1
  npm: 9.5.1
  Yarn: 1.22.19
  pnpm: 8.6.10
Relevant Packages:
  next: 13.5.4-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime)

### Additional context

This could potentially impact any application that does internationalization using the path and rewriting in middleware to add the market/country or whatnot to render the right page.

**Comment by danestves** [comment]
Actually getting this error too, I thought it was me, I'm using next-intl and seeing that behavior, I need to refresh the page to be able to make the intercept route to render the modal

**Comment by mastoj** [comment]
> Actually getting this error too, I thought it was me, I'm using [next-intl](https://linear.app/vercel/issue/NEXT-intl) and seeing that behavior, I need to refresh the page to be able to make the intercept route to render the modal

Yeah, I would expect any solution that leverage rewrites to have the problem, and I’m pretty sure next-intl does.

**Comment by mastoj** [comment]
@feedthejim @ztanner 

It still doesn't work as one would expect, and I tried with version 14.0.4-canary.32.

You can use this branch to test: https://github.com/mastoj/nextgram/tree/with-middleware

1. npm run dev
2. click an image - modal shows - correct
3. close - works
4. click another image - modal shows - correct
5. refresh - photos page shows - correct
6. go back - shows list again - correct
7. **click on the image you came from - the page shows and not the modal - incorrect**
8. click another image and the modal shows - correct

**Comment by Contraboi** [comment]
@feedthejim @ztanner

It does not work for me either. I've also tried with version 14.0.4-canary.32.

Facing the same issue as @mastoj.

**Comment by ztanner** [comment]
Looks like there's a separate issue here, in addition to the one that was fixed! Taking a look.

**Comment by mastoj** [comment]
Verified in my sample that it works as expected.
