### ISSUE TITLE
 Server rendered routes with hashes do not work with browser back/forward navigation

### ISSUE THREAD

**Issue by benhonda** [vercel/next.js#56112]
### Link to the code that reproduces this issue

https://github.com/benhonda/nextjs-router-bug

### To Reproduce

1. Go to https://nextjs.org/docs
2. Click on any of the "hashed" routes (located in the right-hand sidebar on desktop screens)
3. Navigate to a different page by clicking on a page route (located in the left-hand sidebar on desktop screens)
4. Click the back button on your browser. The URL changes and the page may scroll, but the page content remains from Step 3.

### Current vs. Expected behavior

Currently, the URL changes and the page may scroll, but the page content does not change.

I expect the page to navigate back to the previous content (as specified in the URL) and for my scroll position to be at the specified hash.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
OS:
MacOS Monterey 12.6.8
Intel chip


Tested browsers:
Firefox 117.0.1, Chrome 117.0.5938.92, Safari 16.5.2
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

**The "Link to the code that reproduces this issue" just leads to an empty template but I have a good excuse - I swear!**
I came across this issue in my local development, where I needed to set hash links to footnotes for A11y purposes, however since the issue also appears to be present on [the nextjs docs site](https://nextjs.org/docs), I decided to just use that as my example for convenience.

**Comment by stijnwesterhof** [comment]
I don't see this issue happening on the docs, but I do experience this in my app. Currently also looking for a solution...

**Comment by evoX0** [comment]
Same here
next 14.0.1

**Comment by bircha** [comment]
I can reproduce the bug in our project. Any plans for a fix?

**Comment by arshseraphic** [comment]
I have similar issue, using next 14.2.3 App Router.

I am on page 

https://www.bettingtipsafrica.com/betting-sites/

then i click Countries in right sidebar which take me to hash link

https://www.bettingtipsafrica.com/betting-sites/#other-countries

When i choose some country or click any link in footer or header , for example i click Tanzania

https://www.bettingtipsafrica.com/betting-sites/tanzania/

it take me to page and show correct content, which is good, now when i click back button in browser, 

url changed to https://www.bettingtipsafrica.com/betting-sites/#other-countries. 

which is also fine. but content did not change

content still showing of page https://www.bettingtipsafrica.com/betting-sites/tanzania/

It should be showing content of 

https://www.bettingtipsafrica.com/betting-sites/#other-countries

**Comment by stefan-girlich** [comment]
Confirming the behavior described by @arshseraphic using `"next": "14.2.4"` with app router.

**Comment by Maxnikit** [comment]
Having same issue using "next": "14.2.5" with app router. Has anybody found a workaround?

**Comment by bootleq** [comment]
Same behavior with `"next": "14.2.16"` app router.

As a workaround, I add below component to global layout, hold `pathname` internally, listen to `popstate` event, force a `router.replace` when detecting the pathname didn't follow URL change.

```typescript
"use client"

import { useState, useEffect, useCallback } from 'react';
import { useRouter, usePathname } from 'next/navigation';

export default function FollowHashRoute() {
  const [latestPath, setLatestPath] = useState('');
  const pathname = usePathname();
  const router = useRouter();

  const onPopState = useCallback((e: PopStateEvent) => {
    const newPathname = new URL(document.location.href).pathname;

    if (newPathname !== latestPath) {
      setLatestPath(newPathname);
      router.replace(document.location.href);
    }
  }, [router, latestPath]);

  useEffect(() => {
    window.addEventListener('popstate', onPopState);

    return () => {
      window.removeEventListener('popstate', onPopState);
    };
  }, [onPopState]);

  if (pathname !== latestPath) {
    setLatestPath(pathname);
  }

  return null;
}
```
