### ISSUE TITLE
SWC minification generates incorrect code

### ISSUE THREAD

**Issue by nam-aalto** [vercel/next.js#56125]
### Link to the code that reproduces this issue

https://github.com/nam-aalto/swc-minify-bug

### To Reproduce

# Works correctly in development
1. `npm run dev`
2. Open http://localhost:3000
3. See: `neverUndefined value: "[1,2]"`

# Works correctly in production with `swcMinify:false`
1. Set swcMinify to false in next.config.js
2. `npm run build && npm start`
3. Open http://localhost:3000
4. See: `neverUndefined value: "[1,2]"`

# Works **incorrectly** in production with `swcMinify:true`
1. Set swcMinify to true in next.config.js
2. `npm run build && npm start`
3. Open http://localhost:3000
4. See: `neverUndefined value: ""`

### Current vs. Expected behavior

The value `neverUndefined` returned from `getThings()` function should always be an array. But when using SWC minification, it is `undefined` instead.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC minifier (swcMinify: true)

**Comment by kdy1** [comment]
<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/99ef785b-04b5-4a61-b3b7-7c8dffa8c943">

Closing as fixed
