### ISSUE TITLE
ChunkLoadError on production build 

### ISSUE THREAD

**Issue by amit548** [vercel/next.js#56130]
### Link to the code that reproduces this issue

https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing

### To Reproduce

1. Build next js(13.5.3) application for production
2. Start the app using npm run start
3. Browsing the website for sometime
4. Suddenly ChunkLoadError appear on the console and whole website is crashed
5. After restart the server errors are automatically fixed
6. It happens every time(loop)

### Current vs. Expected behavior

ChunkLoadError should not happen.

### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: N/A
  pnpm: 8.7.6
Relevant Packages:
  next: 13.5.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router, Routing (next/router, next/navigation, next/link)

### Additional context

I deployed next.js production app on Ubuntu, after deploying it worked as expected but sometime later app automatically throw some ChunkLoadError on the console not sure why
![IMG_20230928_110523_455](https://github.com/vercel/next.js/assets/36206377/b9b389a3-d9a9-4f16-9d5c-4e0bdfdfba6c)
![IMG_20230928_110553_559](https://github.com/vercel/next.js/assets/36206377/8b6d79f2-0732-4347-856b-4c95bd1ff91a)

**Comment by domosedov** [comment]
[same problem](https://github.com/vercel/next.js/issues/54008)

**Comment by schimi-dev** [comment]
Related to https://github.com/vercel/next.js/issues/55697 https://github.com/vercel/next.js/issues/55624

**Comment by poorscousertommy8** [comment]
The developers of Next.js are currently looking at the problem. Please continue to monitor here https://github.com/vercel/next.js/issues/54008 (a next developer has reported there).

**Comment by balazsorban44** [comment]
There is an issue opened for this at #54008 so closing in favor. Please post your reproduction there, but note that the repository linked has a 4-month-old Next.js version. Make sure to test it with `next@canary` before posting. Also, try to minimize the reproduction as much as possible (is mongoose really necessary to reproduce the issue?).

if relevant, please post your reply to #54008, thanks!
