### ISSUE TITLE
next.js 12.3.4 breaks `html { scroll-behavior: smooth; }` in firefox and safari

### ISSUE THREAD

**Issue by arantebw** [vercel/next.js#56156]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/naughty-feather-xwczm6

### To Reproduce

1. Scroll to the bottom footer section of the page.
2. Click a navigation link.

### Current vs. Expected behavior

The smooth scroll behavior breaks in Firefox and Safari.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.13-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Additional context

We are using Next.js 12.3.4 in production where the issue persists.

**Comment by balazsorban44** [comment]
Thanks, please note that we do not backport fixes to older major versions unless it's security-related. Please upgrade to the latest version and feel free to open a new issue if you are still experiencing the same problem.
