### ISSUE TITLE
Middleware generates unexpected _next/data requests

### ISSUE THREAD

**Issue by gudvinga** [vercel/next.js#56157]
### Link to the code that reproduces this issue

https://github.com/gudvinga/next-js-middleware-issue

### To Reproduce

1. Start application (yarn next dev)
2. Click link on the page
3. Check network

### Current vs. Expected behavior

**Current:**
Each `link` from `next/link` generates a `/_next/data/**` requests, even if the page is without getInitialProps, getServerSideProps and getStaticProps. You can use `shallow` to avoid running these functions again, and `prefetch={false}`, but even then the request will be on the link hover.
Either way, this request is unexpected and causes a 404 page to be displayed.

**Expected**
Adding a middleware.ts to a project should not cause unnecessary `/_next/data/**`requests.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103
Binaries:
  Node: 16.20.1
  npm: 8.19.4
  Yarn: 1.22.18
  pnpm: 8.7.1
Relevant Packages:
  next: 13.5.4-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

**Comment by balazsorban44** [comment]
This is expected. There is a prefetch request made to make sure that Middleware redirects/rewrites are correctly handled even on client-side navigations.

**Comment by gudvinga** [comment]
> This is expected. There is a prefetch request made to make sure that Middleware redirects/rewrites are correctly handled even on client-side navigations.

But why?
Adding a middleware to the project breaks the original behavior of the links and the router, all links start `prefetching`.
In our case, we have getInitialProps in _app.ts (yes, I know this is very bad and we want to move away from this behavior) and `_next/data` requests trigger the rendering page on the server.
