### ISSUE TITLE
useEffect is called 2 times

### ISSUE THREAD

**Issue by ialse** [vercel/next.js#56171]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/confident-mcnulty-l9xvdh

### To Reproduce

1. Open example by link
2. Open devTools
3. Touch refresh page in codesandbox
4. in console useEffect is called 2 times

### Current vs. Expected behavior

useEffect is called 2 times but should be called once.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.3
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by diaz-hfc** [comment]
If you use strict mode the hooks are called two times: https://react.dev/reference/react/StrictMode#enabling-strict-mode-for-entire-app

**Comment by ialse** [comment]
closed

**Comment by ialse** [comment]
close
