### ISSUE TITLE
Docs: Make it clear whether `getServerSideProps` is guaranteed to complete before a request is served to the client

### ISSUE THREAD

**Issue by hjniermann** [vercel/next.js#56189]
### What is the improvement or update you wish to see?

It is not obvious in the documentation on how to guarantee that data will be fetched during server-side rendering before the page is served. I have data on my page that MUST be fetched from another server before I can send it to the client. It is recommended to use `getServerSideProps` to do this, but it never explicitly says it GUARANTEES the method will complete before the response is sent to the client.

I am looking to migrate my calls of `getInitialProps` to `getServerSideProps` in order to solve this problem, but it's still not clear to me whether `getServerSideProps` will fulfill this. It appears `getInitialProps` lost this ability at some point from 9 -> 10.

### Is there any context that might help us understand?

Take this example:

```
// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://.../data`)
  const data = await res.json()
 
  // Pass data to the page via props
  return { props: { data } }
}
 
export default function Page({ data }) {
  // Render data...
}
```

Let's say we make a request to render a Page, but our fetch call is slow. Page renders without the props passed to it by getServerSideProps. Does it then send the rendered page (without the appropriate props) before the call from `getServerSideProps` has completed?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props

**Comment by balazsorban44** [comment]
In the docs, it says:

> Next.js will pre-render this page on each request using the data returned by getServerSideProps.

Meaning it will block the sending of the page until it is pre-rendered.

**Comment by hjniermann** [comment]
I wouldn't define that as clear. `getInitialProps` does the same thing, but is non-blocking.
