### ISSUE TITLE
Next 13.5 breaks hooks inside MDX components

### ISSUE THREAD

**Issue by mordechaim** [vercel/next.js#56183]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/crazy-hooks-zj6yy5

### To Reproduce

1. Start the application
2. Watch the error pop up

### Current vs. Expected behavior

All imports from react should resolve properly, but it throws an error as follows:

```
Error: Cannot read properties of null (reading 'useState')
```

The server logs the following:

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 ⨯ node_modules/react/cjs/react.development.js (1622:20) @ useState
 ⨯ TypeError: Cannot read properties of null (reading 'useState')
    at DemoState (./app/demo.mdx:17:80)
    at stringify (<anonymous>)
null
 ⨯ node_modules/react/cjs/react.development.js (1622:20) @ useState
 ⨯ TypeError: Cannot read properties of null (reading 'useState')
    at DemoState (./app/demo.mdx:17:80)
    at stringify (<anonymous>)
digest: "2090206657"
null
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 20.5.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.4-canary.6
  eslint-config-next: 13.4.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, MDX (@next/mdx)

### Additional context

This only happens for the App Router. Pages continues to work properly

**Comment by balazsorban44** [comment]
`useState` is only available in client components, meaning you need to add the `"use client"` directive to your page, where you import the MDX component. The issue then should go away.

Ref: https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#when-to-use-server-and-client-components

Also, check out the documentation on how to properly set up `@next/mdx`: https://nextjs.org/docs/app/building-your-application/configuring/mdx#nextmdx

**Comment by mordechaim** [comment]
Pardon me for not properly recreating the reproduction.

I can confirm this occurs even when using the `"use client"` directive in `page.js`. In fact, it perfectly worked on Next 13.4.

I've updated the CodeSandbox.

**Comment by mordechaim** [comment]
@balazsorban44 any chance this issue will be reopened with my updated repro or should I open a new issue?
