### ISSUE TITLE
How to use HTTP/2 with React.JS / Next.JS!?!

### ISSUE THREAD

**Issue by khteh** [vercel/next.js#56199]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js/blob/canary/examples/with-http2/server.js

### To Reproduce

```
const app = next({ dev, hostname, port, dir: __dirname })
const server = http2.createSecureServer({
  key: fs.readFileSync('server.key'),
  cert: fs.readFileSync('server.crt')
})
app.prepare().then(() => {
})
    server.on('request', (req, res) => {
      console.log(`request ${req.url}`)
        app.render(req, res, req.url || '/', req.query)
      })    
    server.listen(port, (err) => {
      if (err) {
        console.error('Failed to start server', err)
        process.exit(1)
      } else {
        console.log(`HTTP/2 server listening on port: ${port}`)
      }
    })
}).catch(err => next(err))
```

### Current vs. Expected behavior

`- error unhandledRejection: TypeError: Cannot read properties of undefined (reading 'end')`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Ubuntu 23.04
```

### Which area(s) are affected? (Select all that apply)

Not sure, Package manager (npm, pnpm, Yarn), Standalone mode (output: "standalone")

**Comment by balazsorban44** [comment]
Let's track the example-related issue in #50270
