### ISSUE TITLE
Building project with default `metadataBase` will result with broken path

### ISSUE THREAD

**Issue by BeroBurny** [vercel/next.js#56210]
### Link to the code that reproduces this issue

https://github.com/BeroBurny/metadata-url

### To Reproduce

1. setup (the is some additional information in readme)
2. build project `vercel build`
3. deploy it `vercel deploy --prebuilt`
This will produce a build that contains metadata paths with `localhost:300` that cannot be deployed anywhere as it will result `404` for users

to fix this behavior you can literally remove `http://localhost:3000` from all places where is used and will work fine

## Current
Currently, page will contain the full URL but is not needed

```html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preload" href="/_next/static/chunks/webpack-bf1a64d1eafd2816.js" as="script" fetchpriority="low">
    <script src="/_next/static/chunks/fd9d1056-bdbc21787612b876.js" async=""></script>
    <script src="/_next/static/chunks/864-2c350c1e805e4a45.js" async=""></script>
    <script src="/_next/static/chunks/main-app-162fd94f9d2a73de.js" async=""></script>
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1838">
    <meta property="og:image:height" content="931">
    <!--     Check This URL Here             👇 -->
    <meta property="og:image" content="http://localhost:3000/opengraph-image.png?b133443553340dc8">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image:type" content="image/png">
    <meta name="twitter:image:width" content="1838">
    <meta name="twitter:image:height" content="931">
    <!--     Check This URL Here             👇 -->
    <meta name="twitter:image" content="http://localhost:3000/twitter-image.png?b133443553340dc8">
    <script src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js" nomodule=""></script>
    <meta name="d41d8cd98f00b204e9800998ecf8427e_lib_detect" id="d41d8cd98f00b204e9800998ecf8427e_lib_detect">
</head>
```
You can find a deployed site here https://metadata-1kebb4lao-beroburny.vercel.app/

## Expected
```html
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preload" href="/_next/static/chunks/webpack-bf1a64d1eafd2816.js" as="script" fetchpriority="low">
    <script src="/_next/static/chunks/fd9d1056-bdbc21787612b876.js" async=""></script>
    <script src="/_next/static/chunks/864-2c350c1e805e4a45.js" async=""></script>
    <script src="/_next/static/chunks/main-app-162fd94f9d2a73de.js" async=""></script>
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1838">
    <meta property="og:image:height" content="931">
    <!--     Check This URL Here             👇 -->
    <meta property="og:image" content="/opengraph-image.png?b133443553340dc8">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image:type" content="image/png">
    <meta name="twitter:image:width" content="1838">
    <meta name="twitter:image:height" content="931">
    <!--     Check This URL Here             👇 -->
    <meta name="twitter:image" content="/twitter-image.png?b133443553340dc8">
    <script src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js" nomodule=""></script>
    <meta name="d41d8cd98f00b204e9800998ecf8427e_lib_detect" id="d41d8cd98f00b204e9800998ecf8427e_lib_detect">
</head>
```
You can find a deployed site here https://metadata-973uqdhi2-beroburny.vercel.app/

## Additional
Result URL used on discord
![image](https://github.com/vercel/next.js/assets/6376047/16ac232c-8271-468b-a166-f296ff1ee8cb)

Or this tool can be used to preview https://www.opengraph.xyz/

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2
Binaries:
  Node: 16.19.1
  npm: 8.19.3
  Yarn: 3.4.1
  pnpm: N/A
Relevant Packages:
  next: 13.5.4-canary.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata (metadata, generateMetadata, next/head)

### Additional context

Found similar issues

* https://github.com/vercel/next.js/issues/49859
   * this one would be if relative path is been used
* https://github.com/vercel/next.js/issues/48106

**Comment by huozhi** [comment]
You need to specify the `metadataBase` when you deploy the app, it's required for social platform to resolve the social images, relative path won't work well on every app.

You should see the warning `metadata.metadataBase is not set for resolving social open graph or twitter images`

**Comment by BeroBurny** [comment]
Enforcing `localhost:300` will cause problems that definitely would work on every app.

What if I do not know the `metadataBase` URL beforehand?
In the case of manually building and deploying with a local machine or CI/CD
for example `vercel build && vercel deploy --prebuilt` will get a URL at the end of the deployment

**Comment by huozhi** [comment]
You can set the metadataBase to `VERCEL_URL` for preview env, checkout the [metadataBase docs](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase)

```js
metadataBase: new URL(`https://${process.env.VERCEL_URL}`)
```

In this case the url is dynamic, but still provided through env variable
