### ISSUE TITLE
Server action hangs in form when Javascript is disabled

### ISSUE THREAD

**Issue by jchamale** [vercel/next.js#56286]
### Link to the code that reproduces this issue

https://github.com/jchamale/next-bug-runtime.git

### To Reproduce

1. Start the server development
2. Open the page, then open dev tools
3. Disable Javascript
4. Reload page 
5. Fill the form and submit
6. The request will never finish
7. Changing the runtime on the home page to `edge` is working fine.
8. The bug was tested in Chrome and confirmed in Safari

### Current vs. Expected behavior

The server action should work no matter what the runtime is. It seems that adding a middleware will break the server action for being ran if JS is disabled.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.3
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime)

### Additional context

I tested in latest version as well with the same result.

```sh
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.4-canary.8
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

**Comment by Janhouse** [comment]
I am seeing the same behavior with next 13.5.4 when JavaScript is disabled.  As soon as I add a middleware (even an empty one), request is kept open forever and nothing happens.
