### ISSUE TITLE
Error improvement

### ISSUE THREAD

**Issue by nicitaacom** [vercel/next.js#56346]
### What is the improvement or update you wish to see?

![image](https://github.com/vercel/next.js/assets/39565703/620863aa-3682-40be-b2b9-4da0891aa960)

I want to see in which file I should use 'use client'

### Is there any context that might help us understand?

Use smth link onClick or async/await to get this error

**Comment by leerob** [comment]
This is a react error, but we'd certainly like to find ways to make this better regardless. Thank you 🙏
