### ISSUE TITLE
ReactDOM seems to be imported twice

### ISSUE THREAD

**Issue by EliasVal** [vercel/next.js#56400]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-pages

### To Reproduce

1. Build the application with the bundleAnalyzer installed and enabled
2. react-dom.production.min.js seems to be imported twice
![image](https://github.com/vercel/next.js/assets/46247153/4cf726c5-0125-4107-b5c1-7b0301feee59)

### Current vs. Expected behavior

Only one import of react-dom, instead of twice.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.4
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Package manager (npm, pnpm, Yarn)

### Additional context

Ignore the provided link :^)

I tested with both NPM and PNPM with the same result.

**Comment by icyJoseph** [comment]
In short, no it is not: https://github.com/vercel/next.js/issues/56063

The long winded version is that the pages router bundle is still output. Ultimately to the client's browser, only one will be sent.
