### ISSUE TITLE
react-pagination (and possibly other libs) render incorrectly on PROD only

### ISSUE THREAD

**Issue by andreiciceu** [vercel/next.js#56406]
### Link to the code that reproduces this issue

https://github.com/andreiciceu/nextjs-react-paginate-bug

### To Reproduce

1. setup
```
yarn install
yarn build
yarn start
```
2. open page

### Current vs. Expected behavior

Current (13.5.4):
![image](https://github.com/vercel/next.js/assets/9255607/47b57252-f269-403f-825b-61957047c7c4)
browser console:
```
(react-paginate): The pageCount prop value provided is not an integer (undefined). Did you forget a Math.ceil()?
```

Expected (13.5.1):
![image](https://github.com/vercel/next.js/assets/9255607/62a5d32a-5e82-45f1-b6f1-5e48222bb88f)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
OS: MacOS,Alpine Linux (doesn't seem to be OS related)
Node: v16.19.0
Yarn: 1.22.19
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

This is visible when running the production build only. DEV works ok.
Issue present on both Pages and App Router, and with or without dynamic (no SSR rendering).
Downgrading to 13.5.1 solves the problem

**Comment by lzagata-duo** [comment]
Same issue on node v18.17.0

**Comment by richlawson** [comment]
Downgrading to 13.5.3 resolved.

**Comment by Tea-Key1** [comment]
I have same issue. In develop environment, it properly works. But, In runtime environment, the worning happened.
so, there are something wrong in building process.

_(react-paginate): The pageCount prop value provided is not an integer (undefined). Did you forget a Math.ceil()?_

**Comment by MikeMatrix** [comment]
Same issue here using
Node v18.17.1
next@13.5.4
react-paginate@8.2.0

From the looks of it, somehow it creates children of the same component instead of what it's supposed to create.
![image](https://github.com/vercel/next.js/assets/1426581/730d5bc5-3ce3-4271-ac4d-5f17e930a086)

From initial debugging it looks like the outer symbol `o` and the inner symbol `o` are different Components during development, but end up being the same Component during production.

Rolling back has resolved my issue for now.

**Comment by extralsc** [comment]
I have the same issue.
Node v18.17.1
Next 13.5.4
React paginate 8.1.4

I dev mode it works fine, in prod i have the same issue as above.

**Comment by sheetalsindhu** [comment]
I was too getting the same issue, downgraded my package to Next 13.4.13 and React paginate 8.1.4.

**Comment by SM2DevLLC** [comment]
Any update on this issue? Kind of a big problem.

**Comment by camcamcamcam** [comment]
The issues seems to have started at [this commit](https://github.com/vercel/next.js/commit/83c18deafe4f133f74ef2b1e0512228098d48cba)

**Comment by camcamcamcam** [comment]
It has something to do with the SWC minifier. If you set `keep_fnames` to `false` in `packages/next/src/build/webpack/plugins/terser-webpack-plugin/src/index.ts` then this problem goes away.

> keep_fnames (default false) -- Pass true to not mangle function names. Pass a regular expression to only keep function names matching that regex. Useful for code relying on Function.prototype.name.

So this is why it works in dev, but not prod.

**Workaround**
You can add `swcMinify: false` to your next.config.js file. (I'm not sure if you can pass options to the SWC minifier directly, but that would be nice)

**Comment by lzagata-duo** [comment]
Thanks @camcamcamcam , I can confirm that setting swcMinify to false worked for me on Next.js 13.5.5

**Comment by Ishfaque-techno** [comment]
I have the same issue.
Next 13.5.4
React paginate 8.2.0
In dev mode it works fine, in prod i have the same issue as above. I have added swcMinify: false, still it's not working.

**Comment by Pratikkumbhani5** [comment]
@Ishfaque-techno I have same issue with this versions.
I solve this issue with downgrade react-paginate version to 8.2.0 -> 8.1.3 
this is working on both mode dev and prod.

**Comment by jeremymarc** [comment]
I still have the issue with react-paginate 8.1.3 and next 13.5.6

**Comment by Jasermon** [comment]
Same issue

next@13.5.6
react-paginate@8.2.0

**Comment by elvisciuffetelli** [comment]
Same issue with next 14.0.0 and react-paginate 8.1.5

**Comment by bhushanzade** [comment]
I have save issue with version react-paginate@8.2.0 & next@13.5.6

But its resolved using downgrading version to react-paginate@8.1.3

**Comment by manuarora700** [comment]
Downgrading to react-paginate@8.1.3 works.

Current Next.js version = 12.3.6

**Comment by sugan-ysquare** [comment]
> @Ishfaque-techno I have same issue with this versions. I solve this issue with downgrade react-paginate version to 8.2.0 -> 8.1.3 this is working on both mode dev and prod.

tqs it worked

**Comment by ColeTownsend** [comment]
We basically rewrote our own and didn't have the worst time.

```tsx
import { useCallback, useMemo, useState } from "react";

interface Props {
  previousLabel?: string;
  nextLabel?: string;
  pageCount: number;
  onPageChange: (...args: any) => void;
  pageRangeDisplayed?: number;
  breakLabel?: string;
  pageLinkClassName?: string;
  previousClassName?: string;
  nextClassName?: string;
  disabledClassName?: string;
  breakClassName?: string;
  containerClassName?: string;
  activeClassName?: string;
  gap?: Record<string, string>;
  forcePage?: number;
}

const CustomPagination = ({
  previousLabel = "Prev",
  nextLabel = "Next",
  pageCount,
  onPageChange,
  pageRangeDisplayed = 2,
  breakLabel = "...",
  pageLinkClassName,
  previousClassName,
  nextClassName,
  disabledClassName,
  breakClassName,
  containerClassName,
  activeClassName,
  gap = { marginRight: "4px" },
  forcePage,
}: Props) => {
  const [currentPage, setCurrentPage] = useState(forcePage || 0);

  const handlePageClick = useCallback(
    (page: number) => {
      onPageChange({ selected: page });
      setCurrentPage(page);
    },
    [onPageChange],
  );

  const pages = useMemo(() => {
    const pages = [];
    const leftSide = pageRangeDisplayed / 2;
    const rightSide = pageRangeDisplayed - leftSide;

    for (let i = 0; i < pageCount; i++) {
      const label = i + 1;
      let className = pageLinkClassName;
      if (i === currentPage) className += ` ${activeClassName}`;

      if (
        i === 0 ||
        i === pageCount - 1 ||
        (i >= currentPage - leftSide && i <= currentPage + rightSide)
      ) {
        pages.push(
          <button key={i} onClick={() => handlePageClick(i)} className={className} style={gap}>
            {label}
          </button>,
        );
      } else if (
        (i < currentPage - leftSide && i === 1) ||
        (i > currentPage + rightSide && i === pageCount - 2)
      ) {
        pages.push(
          <span key={i} className={breakClassName} style={gap}>
            {breakLabel}
          </span>,
        );
      }
    }

    return pages;
  }, [
    currentPage,
    pageCount,
    pageRangeDisplayed,
    pageLinkClassName,
    activeClassName,
    breakClassName,
    breakLabel,
  ]);

  return (
    <div className={containerClassName}>
      <button
        onClick={() => handlePageClick(currentPage - 1)}
        className={
          currentPage === 0 ? `${previousClassName} ${disabledClassName}` : previousClassName
        }
        disabled={currentPage === 0}
        style={gap}
      >
        {previousLabel}
      </button>

      {pages}

      <button
        onClick={() => handlePageClick(currentPage + 1)}
        className={
          currentPage === pageCount - 1 ? `${nextClassName} ${disabledClassName}` : nextClassName
        }
        disabled={currentPage === pageCount - 1}
      >
        {nextLabel}
      </button>
    </div>
  );
};

export default CustomPagination;
```

**Comment by gustaveWPM** [comment]
Hello,
Same issue here.

Downgrading to React Paginate v8.1.3 has hotfixed this for me too.

I'm using Next v14.0.1

**Comment by cngvc** [comment]
> I still have the issue with react-paginate 8.1.3 and next 13.5.6

8.1.0 will work

**Comment by arshseraphic** [comment]
any update on this?

**Comment by quoc2401** [comment]
I'm also having this issue with `"next": "14.0.1"`, `"react-paginate": "8.2.0",`.
Upgrading `"next": "14.0.2"` worked for me.

**Comment by ViktoriiaMurzhak** [comment]
To solve this problem, use the following versions:
 "react-paginate": "8.1.3",  "next": "13.5.6",
 
 and delete the symbol next to the version value "^"

**Comment by Noitidart** [comment]
> It has something to do with the SWC minifier. If you set `keep_fnames` to `false` in `packages/next/src/build/webpack/plugins/terser-webpack-plugin/src/index.ts` then this problem goes away.
> 
> > keep_fnames (default false) -- Pass true to not mangle function names. Pass a regular expression to only keep function names matching that regex. Useful for code relying on Function.prototype.name.
> 
> So this is why it works in dev, but not prod.
> 
> **Workaround** You can add `swcMinify: false` to your next.config.js file. (I'm not sure if you can pass options to the SWC minifier directly, but that would be nice)

Another lib impacted is `npm i simple-crypto-js@legacy` (which install v2.5.1) (legacy is needed to support browsers without native crypto module per readme of the lib).

The error that happens in prod is `TypeError: can't access property "sqrt", Math is undefined`.

Setting `swcMinify: false` in next 14.0.2 however it warns that in next 15 this option is gone.

**Comment by angelovdev** [comment]
Disabling SWC resulted in an error in Terser for me. Downgraded to 13 as 14 is apparently still experimental.

```
6117.js from Terser
Unexpected token: punc ({) 
```

**Comment by nadeem-golflan** [comment]
getting the same issue
Next 13.5.4
React paginate 8.2.0

**Comment by styles102** [comment]
> It has something to do with the SWC minifier. If you set `keep_fnames` to `false` in `packages/next/src/build/webpack/plugins/terser-webpack-plugin/src/index.ts` then this problem goes away.
> 
> > keep_fnames (default false) -- Pass true to not mangle function names. Pass a regular expression to only keep function names matching that regex. Useful for code relying on Function.prototype.name.
> 
> So this is why it works in dev, but not prod.
> 
> **Workaround** You can add `swcMinify: false` to your next.config.js file. (I'm not sure if you can pass options to the SWC minifier directly, but that would be nice)

This worked for me. Thanks

**Comment by emresates** [comment]
Nextjs 14.0.0 same issue,
Downgrading to react paginate 8.1.3 worked

**Comment by Jasermon** [comment]
update to next 14.0.3 worked for me
here is my package.json
```

{
  ...
  "dependencies": {
    ...
    "next": "^14.0.3",
    "react-paginate": "^8.2.0",
    ...
  },
  ...
}
```

Note: I build my project with npm

**Comment by richlawson** [comment]
This also worked for me, thanks:
> update to next 14.0.3 worked for me

I was able to remove the `swcMinify: false` workaround that I had used previously.

**Comment by talal-uxbert** [comment]
Faced the same issue. Working fine on dev mode, but broke on test and prod environments.
Adding `swcMinify: false` worked like a charm <3

**Comment by ThemePure** [comment]
in my case i install 
"next": "^13.5.1",

and pagination component false server side rendering 
const Pagination = ({ handlePageClick, pageCount }: IProps) => {
  return (
    <>
      <ReactPaginate
        breakLabel="..."
        activeClassName="active"
        nextLabel={<i className="fal fa-angle-right"></i>}
        onPageChange={handlePageClick}
        pageRangeDisplayed={5}
        pageCount={pageCount}
        previousLabel={<i className="fal fa-angle-left"></i>}
        renderOnZeroPageCount={null}
      />
    </>
  );
};

export default dynamic(() => Promise.resolve(Pagination), {
  ssr: false
})

it will be works

**Comment by Juanfe98** [comment]
I was having the same issue working with 
    "next": "14.0.0",
    "react": "^18",
    "Node": 18
I solved the issue upgrading next to 14.0.3 and NodeJS to 20+

**Comment by nassimessaidi** [comment]
To resolve this issue, downgrade to `react-paginate@8.1.3`. You can do this by using the following commands:

Using Yarn:
```bash
yarn add react-paginate@8.1.3
```
Or using npm:
```bash
npm install react-paginate@8.1.3
```
Alternatively, you can manually update your package.json file. Change:

```json
"react-paginate": "^8.1.3",
```
to:
```json
"react-paginate": "8.1.3",
```
without the ^ symbol. After making this change, run:
```bash
npm install
```
or
```
yarn install
```


Note: I'm using **`"next": "13.5.4"`** in this configuration.

**Comment by Riyaz-khan-shuvo** [comment]
```"react-paginate": "^8.1.3",```

to:

```"react-paginate": "8.1.3",```

that works for me.

**Comment by ThemePure** [comment]
ok Thanks.

**Comment by astroboy-71** [comment]
I faced same issues. I think react-paginate module is not perfect!

I can fix it to downgrade the version of react-paginate as 8.1.3
Thanks for all of your time

**Comment by nkpremices** [comment]
Downgrading to `react-paginate@8.1.3` worked for me

**Comment by ArafathShemanto** [comment]
"react-paginate": "8.1.3" 
"next" : "14.0.0"

It works for me

**Comment by andreiciceu** [comment]
Will close it, as it's fixed in latest release
