### ISSUE TITLE
504 Error | Pro Member | Serverless

### ISSUE THREAD

**Issue by space1worm** [vercel/next.js#56413]
### Link to the code that reproduces this issue

https://github.com/space1worm/serverless-timeout-test

### To Reproduce

Hey everyone,

**Next.js version : 13.5.3**
**Dir: App Directory**

Do you have any ideas about why Vercel is returning a 504 error? I'm on the pro plan, and my serverless function is configured to run for a maximum of 5 minutes. my function for testing purposes needs 1.5m to execute.

In the logs, **I can see that the serverless function is returning a 200 status code,** and it's executing correctly. However, when I access it through postman, **after exactly 1 minute, it returns a 504 error.**

Everything works fine locally. What could be the issue?

**Here is step by step description how to reproduce:**
Go to -> https://test-liart-seven-84.vercel.app/
Click -> 'click to fetch' button

Expected behaviour -> after 1m30s you should see 'Hello World' text
Current behaviour -> Returns 504 Gateway Timeout Error

<img width="1201" alt="Screenshot 2023-10-04 at 14 47 25" src="https://github.com/vercel/next.js/assets/84189246/0f6b1ce7-b1ec-4abd-974e-5969caae5815">
<img width="1203" alt="Screenshot 2023-10-04 at 14 47 34" src="https://github.com/vercel/next.js/assets/84189246/b2163cea-c6e6-4f12-a405-7eb603fc8682">
<img width="837" alt="Screenshot 2023-10-04 at 14 50 28" src="https://github.com/vercel/next.js/assets/84189246/507df260-8630-4727-8cd4-2b49012507bb">
<img width="702" alt="Screenshot 2023-10-04 at 14 53 19" src="https://github.com/vercel/next.js/assets/84189246/46763dec-dd26-4c75-a076-05444af150a7">
<img width="708" alt="Screenshot 2023-10-04 at 14 53 27" src="https://github.com/vercel/next.js/assets/84189246/3f527109-8806-445e-9a1e-672d48c77569">

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.3
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

**Comment by swarnava** [comment]
Hi,

This issue should be fixed now!

**Comment by space1worm** [comment]
@swarnava Yes, thank you!

**Comment by pierroo** [comment]
Hi @swarnava not sure if you are aware, but I am also facing it now under the very same context, and it times out at just 15 seconds :/

**Comment by swarnava** [comment]
> Hi @swarnava not sure if you are aware, but I am also facing it now under the very same context, and it times out at just 15 seconds :/

The default timeout is 15 seconds on Pro plan now.  Have you tried increasing it using `maxDuration` property? https://vercel.com/docs/projects/project-configuration#functions

**Comment by swarnava** [comment]
You can set globally via Vercel.json or to specific serverless function as
instructed here:
https://vercel.com/docs/functions/serverless-functions#deploying-serverless-functions
