### ISSUE TITLE
failed to fetch still present

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [vercel/next.js#56456]
### Link to the code that reproduces this issue

https://github.com/AlvaroAquijeDiaz/toldyouso

### To Reproduce

1. start & login
2. go to `/secrets`

### Current vs. Expected behavior

should work

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 8.6.6
Relevant Packages:
  next: 13.5.5-canary.2
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

```
 ✓ Compiled /secrets/page in 483ms (1262 modules)
 ⨯ Internal error: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ⨯ Internal error: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
digest: "956933652"
```

I'm on the latest version, saw issues closed but this is still present even when deployed or when using `http://127.0.0.1:3000` is not fixing anything

**Comment by darthmaim** [comment]
@balazsorban44 #56528 auto-closed this issue erroneously
