### ISSUE TITLE
Docs: term of "Dynamic Route" are used incorrectly in diagram

### ISSUE THREAD

**Issue by progfay** [vercel/next.js#56464]
### What is the improvement or update you wish to see?

In the below diagram, the term "Dynamic Route" is used.
[![How static and dynamic rendering affects the Full Route Cache. Static routes are cached at build time or after data revalidation, whereas dynamic routes are never cached](https://nextjs.org/_next/image?url=%2Fdocs%2Fdark%2Fstatic-and-dynamic-routes.png&w=1920&q=100)](https://nextjs.org/_next/image?url=%2Fdocs%2Fdark%2Fstatic-and-dynamic-routes.png&w=1920&q=100)

https://github.com/vercel/next.js/blob/feca3ce21c8f49b5b96c9503e30941a13c9cd516/docs/02-app/01-building-your-application/04-caching/index.mdx#L296-L302

However, the term ["Dynamic Route"](https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes) means "the routes including [Dynamic Segments](https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes#convention)" like a `/blog/[slug]` .

### Is there any context that might help us understand?

https://github.com/vercel/next.js/issues/52512
https://github.com/vercel/next.js/issues/52545

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/caching#static-and-dynamic-rendering

**Comment by leerob** [comment]
"Dynamic Rendering" could make it more clear 👍
