### ISSUE TITLE
You can use className in next/link and many other props.

### ISSUE THREAD

**Issue by kasir-barati** [vercel/next.js#56488]
You can use className in next/link and many other props.

_Originally posted by @kmergen in https://github.com/vercel/next.js/issues/41850#issuecomment-1293907962_

Yes, that is right ([official doc](https://nextjs.org/docs/pages/api-reference/components/link#props)) but in the `LinkProps` we do not have it. Look at this code: https://github.com/vercel/next.js/blob/canary/packages/next/src/client/link.tsx#L110C54-L110C54

**Comment by kevinmitch14** [comment]
This is expected, next/link accepts props specific to the Next.js implementation but also accepts properties that you would normally find in a HTML anchor tag.

**Comment by kasir-barati** [comment]
Hmm, So how can I say that here in this code:
```ts
import classNames from 'classnames';
import { StaticImport } from 'next/dist/shared/lib/get-img-props';
import Image from 'next/image';
import Link, { LinkProps } from 'next/link';
import { PropsWithChildren } from 'react';

export interface SidebarLinkProps
    extends PropsWithChildren<LinkProps> {
    name: string;
    dataTest?: string;
    isActive?: boolean;
    // README: For some reason even though in the official doc it says that Link component supports className, but apparently in the LinkProps we do not have it: https://nextjs.org/docs/pages/api-reference/components/link#props
    className?: string;
    svgIcon?: string | StaticImport;
}

export function SideBarLink({
    name,
    dataTest,
    isActive,
    svgIcon,
    className,
    ...rest
}: SidebarLinkProps) {
    return (
        <Link data-test={dataTest} className={classNames()} {...rest}>
            {svgIcon && (
                <div className="">
                    <Image
                        alt={name + ' icon'}
                        className={classNames()}
                        src={svgIcon}
                    />
                </div>
            )}
            <span className="">{name}</span>
        </Link>
    );
}
```

As you see I had to define the className manually. and `LinkProps<HTMLAnchorElement>` does not work too

**Comment by kevinmitch14** [comment]
How about something like this? This should give you all the same props as the `<Link />` component and your own custom props on top.

```js
type CustomLinkProps = React.ComponentPropsWithoutRef<typeof Link> & {
  myCustomProp?: string;
  isActive: boolean;
  "data-test"?: string;
};

function CustomLink(props: CustomLinkProps) {
  return <Link {...props} />;
}
```

And using the Custom Link like so:
```js
<CustomLink
  className="bg-red-400"
  href={"/admin"}
  data-test="testing"
  myCustomProp="hello"
  isActive={true}
/>
```

`className` is not a prop on `InternalLinkProps`. The className prop on `next/link` comes from the combination of the types below, not solely `InternalLinkProps`.

```js
declare const Link: React.ForwardRefExoticComponent<Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, keyof InternalLinkProps> & InternalLinkProps & {
    children?: React.ReactNode;
} & React.RefAttributes<HTMLAnchorElement>>;
```

**Comment by balazsorban44** [comment]
Was moved to issues by accident. Please open a [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml) if you want to report an issue.

Link does support `className` as it inherits it from an anchor element: https://github.com/vercel/next.js/blob/canary/packages/next/src/client/link.tsx/#L262

![image](https://github.com/vercel/next.js/assets/18369201/ba3692d4-25ec-4efd-af34-882759b9fb91)

You can ask for further TypeScript help in discussions.
