### ISSUE TITLE
Docs: serverActions configuration not supported by Next.js 13 with Turbopack

### ISSUE THREAD

**Issue by schopra-ces** [vercel/next.js#56483]
### What is the improvement or update you wish to see?

I would like to check if experimental configuration for serverActions is supported in Next.js with turbopack. Couldn't find any information on supported configurations

### Is there any context that might help us understand?

![Issue](https://github.com/vercel/next.js/assets/143987917/d70a424a-51e5-40e2-b653-fdc00592b0fd)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/forms-and-mutations

**Comment by kevinmitch14** [comment]
Not ready yet, but looks like it could be coming soon.

https://github.com/vercel/next.js/pull/53890

**Comment by rohitvipin** [comment]
The experimental config (serverActions) is working with latest canary release - https://www.npmjs.com/package/next/v/13.5.5-canary.3

**Comment by balazsorban44** [comment]
Closing as pointed out above. See https://github.com/vercel/next.js/pull/53890
