### ISSUE TITLE
transpilePackages causes use of 'import.meta' outside a module, breaking dev mode

### ISSUE THREAD

**Issue by sawyerh** [vercel/next.js#56487]
### Link to the code that reproduces this issue

https://github.com/sawyerh/nextjs-pino-transpilePackages-bug

### To Reproduce

This bug happens when [`pino`](https://github.com/pinojs/pino) is in the `transpilePackages` config array.

Using the linked repo:

To reproduce the bug, run the application in dev mode:

```
npm run dev
```

You will see the following error:

```
 ⨯ ./node_modules/pino/browser.js
Module parse failed: Cannot use 'import.meta' outside a module (437:16)
|                 // still a Refresh Boundary later.
|                 // @ts-ignore importMeta is replaced in the loader
>                 import.meta.webpackHot.accept();
|                 // This field is set when the previous version of this module was a
|                 // Refresh Boundary, letting us know we need to check for invalidation or
```

To resolve the issue, remove `transpilePackages` from `next.config.js` and restart the server.

### Current vs. Expected behavior

`next dev` fails to run successfully when [`pino`](https://github.com/pinojs/pino) is in the `transpilePackages` config, but `next build && next start` works as expected. I expected `next dev` to also run successfully. 

I am transpiling `pino` in order to support Firefox versions prior to 71.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:30 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T8103
Binaries:
  Node: 18.12.1
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 8.4.0
Relevant Packages:
  next: 13.5.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Additional context

A similar `import.meta` error message was reported in https://github.com/vercel/next.js/issues/35110 however it's not caused by usage of `transpilePackages`.

<sub>[NEXT-2061](https://linear.app/vercel/issue/NEXT-2061/transpilepackages-causes-use-of-importmeta-outside-a-module-breaking)</sub>

**Comment by galaxynova1999** [comment]
isn't Pino a pure Node.js log tool? I don't think it is compatible with browser environment

**Comment by sawyerh** [comment]
> @sawyerh — were you able to find a workaround to this? cc: @lavelle

No

**Comment by niksbanna** [comment]
same issue here after deleting node_modules and reinstalling them
