### ISSUE TITLE
Query URL does not parse arraysint

### ISSUE THREAD

**Issue by sakgoyal** [vercel/next.js#56482]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/sad-fermi-ngdk3q

### To Reproduce

1. create api in page router
2. send query to api with array in parameters (`?inputArray=foo,bar,baz`)
3. check req.query object

### Current vs. Expected behavior

expected:
`req.query = {"inputArray" : ["foo", "bar", "baz"]}`

current: 
`req.query = {"inputArray" : "foo,bar,baz" }`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
(codesandbox)
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.0.8-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

Here is the code I use to convert it into an array. maybe something like this can be implemented?
```js
Object.keys(req.query).forEach(key => {
        if (typeof req.query[key] === 'string' && req.query[key]!.includes(',')) {
            const arr = (req.query[key]! as string).split(',');
            req.query[key] = arr;
        }
    });
```

**Comment by balazsorban44** [comment]
Hi, this is the expected behavior. `query` behaves similarly to [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParam), which also does not do this conversion

**Comment by sakgoyal** [comment]
So, what can I do to be able to parse array params correctly and have the query url variable hold an array instead? or is this not possible at all?
