### ISSUE TITLE
Issue that tells me nothing

### ISSUE THREAD

**Issue by nicitaacom** [vercel/next.js#56534]
### What is the improvement or update you wish to see?

exact step to fix this error

### Is there any context that might help us understand?

![image](https://github.com/vercel/next.js/assets/39565703/a7e774e3-6c21-4aae-90b9-9020831fdbdf)

I use redirect('/') and it throws me error message I don't want to do

**Comment by MaKTaiL** [comment]
Where are you importing "redirect" from?

**Comment by AbdelrhmanX7** [comment]
you can use useRouter.push('/') on client component
or you can use NextResponse.redirect

**Comment by balazsorban44** [comment]
Please use the bug report template.

**Comment by nicitaacom** [comment]
> Where are you importing "redirect" from?

I don't remember 
I fixed it using router from next/navigation

**Comment by nicitaacom** [comment]
> Where are you importing "redirect" from?

It doesn't matter

Issue in error without info about how to fix this error
