### ISSUE TITLE
Build breaking when importing JSBI in 13.5.4

### ISSUE THREAD

**Issue by jeremypress** [vercel/next.js#56550]
### Link to the code that reproduces this issue

https://github.com/jeremypress/next-issue-repro

### To Reproduce

1. run the application (this runs a built version of the app) https://replit.com/@jeremy/next-1354
2. notice the client side error
3. run the app on 13.5.3 https://replit.com/@jeremy/next-1353
4. notice no errors

Relevant code:
```typescript
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import JSBI from 'jsbi';
const modulePath = require.resolve('jsbi');
console.log(modulePath);


function MyApp({ Component, pageProps }: AppProps) {
  const x: JSBI = JSBI.BigInt(Math.floor(Math.random() * 10000));
  console.log(x);
  return <Component {...pageProps} />
}

export default MyApp
```

This package is linking to UMD via the "browser" entry, which isn't great, but something changed behavior wise between next 13.5.3 and next 13.5.4

### Current vs. Expected behavior

Following reproduction steps,
I did not expect this type error

`TypeError: Cannot call a class as a function`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Node 18, mac/linux, default next.config.js
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Additional context

I tried to original submit this with a repl, which I think should be a valid way to submit bugs 🤷🏻 

<sub>[WEB-1742](https://linear.app/vercel/issue/WEB-1742/build-breaking-when-importing-jsbi-in-1354)</sub>

**Comment by adri1wald** [comment]
I was going to create a separate issue for this but seems we're having the same problem. Attaching my repro here:

https://github.com/adri1wald/exceljs-repro/pulls

**Comment by kdy1** [comment]
This is a regression between `swc_core@v0.83.12` and `swc_core@0.83.28`

https://github.com/vercel/next.js/blob/76e06d55a8c42090dafda25ec31d9eeaa7ec647c/Cargo.lock#L6661-L6663

https://github.com/vercel/next.js/blob/1e8dca4a87113f9d6ce0505c90f9a3d89096cefd/Cargo.lock#L5811-L5813

**Comment by jeremypress** [comment]
Thanks for the quick look @kdy1

**Comment by kdy1** [comment]
The cause was a bug related to the new mangling option. I'll fix it soon and will send a PR, hopefully today.
