### ISSUE TITLE
> > I have the this issue when I try to access the **cookies()** from _next/headers_ in the edge runtime. is there a reason why I can't access it there?

### ISSUE THREAD

**Issue by nicitaacom** [vercel/next.js#56589]
> > I have the this issue when I try to access the **cookies()** from _next/headers_ in the edge runtime. is there a reason why I can't access it there?
> 
> What solved it for me was using the `@edge-runtime/cookies` lib from vercel and doing the following:
> 
> ```
> import { RequestCookies } from "@edge-runtime/cookies";
> import { createRouteHandlerClient } from "@supabase/auth-helpers-nextjs";
> 
> import type { Database } from "../types/db";
> 
> export function createEdgeHandlerClient(req: Request) {
>   const cookies = new RequestCookies(req.headers) as any;
>   return createRouteHandlerClient<Database>({ cookies: () => cookies });
> }
> ```

It worked for me!

_Originally posted by @orenlande in https://github.com/vercel/next.js/issues/45371#issuecomment-1702599668_
            
            
            And how you use supabaseServer?
            ```tsx
            const supabaseServer = createServerComponentClient({ cookies })

export default supabaseServer

            ```

**Comment by balazsorban44** [comment]
This looks like a comment converted to an issue by accident. Feel free to open a [proper bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml) if having trouble.
