### ISSUE TITLE
App router time base revalidation failure

### ISSUE THREAD

**Issue by ehsmsh** [vercel/next.js#56580]
### Link to the code that reproduces this issue

https://github.com/ehsmsh/nextjs-app-router-time-revalidation-bug

### To Reproduce

1. Build the application (yarn build)
2. Start the production server (yarn start)
3. Refresh the page a bunch of times
4. Open a private tab or a new browser (bypass cache)
5. Check the result

### Current vs. Expected behavior

The result should be revalidated based on:
```
export const revalidate = 1
```
but after some refreshes, it stops updating and returns a totally empty page. If it is stale in your current tab, try it in another browser or a private tab to bypass the browser cache and you'll see the empty page rather than the stale not revalidated data.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 18.17.1
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by clementdevos** [comment]
We also experience some kind of issue with this revalidation

**Comment by daynejones** [comment]
We have the same issue in production. We are statically generating most of our pages and then settings low revalidation numbers on individual fetches. After a while, all of these pages return 304's and Next.js doesn't render them unless they are in the browser cache. New requests are blank in the browser and delete the URL from Chrome.

The only fix I have found is to set force-dynamic on all routes. Has anyone else found a workaround? I have tried everything I can think of.

**Comment by ehsmsh** [comment]
Yes, the problem would be solved by force-dynamic, but then it will be server rendered on every request. It will not be static. I think the problem is with multiple cache layers enforced by app router, and this one specifically with the client cache which cannot by turned of based on the documentation.
Generally speaking, the cache system of the app router is a headache to work with, with so many problems unsolved!

**Comment by ehsmsh** [comment]
> We have the same issue in production. We are statically generating most of our pages and then settings low revalidation numbers on individual fetches. After a while, all of these pages return 304's and Next.js doesn't render them unless they are in the browser cache. New requests are blank in the browser and delete the URL from Chrome.
> 
> The only fix I have found is to set force-dynamic on all routes. Has anyone else found a workaround? I have tried everything I can think of.

Yes, the problem would be solved by force-dynamic, but then it will be server rendered on every request. It will not be static. I think the problem is with multiple cache layers enforced by app router, and this one specifically with the client cache which cannot by turned off based on the documentation.
Generally speaking, the cache system of the app router is a headache to work with, with so many problems unsolved!

**Comment by adamiku** [comment]
Looks like this was introduced in **v13.5.1**, it works fine for me with previous version e.g. **v13.4.19**
[changelog v13.5.1](https://github.com/vercel/next.js/releases/tag/v13.5.1)

**Comment by ehsmsh** [comment]
> Looks like this was introduced in **v13.5.1**, it works fine for me with previous version e.g. **v13.4.19**
> [changelog v13.5.1](https://github.com/vercel/next.js/releases/tag/v13.5.1)

I had the prblem with v13.4, tried the latest version for a probable fix, but it works just the same for v13.5 too.

**Comment by aslakson** [comment]
This is affecting one of our sites as well. The 403 status is returned but the response is empty resulting in the links to most pages in the navigation appearing to not work at all. Adding `force-dynamic` has had the affect of "fixing" the issue but this change is not ideal since there's nothing being statically rendered.

**Comment by gffuma** [comment]
Same problem here this bug prevent us to use static rendernig.

**Comment by ijjk** [comment]
Hi, this has been updated in `v14.0.2-canary.3` of Next.js, please upgrade and give it a try!

**Comment by zrtsky** [comment]
Thanks a lot 🙏🙏🙏
Does anyone know when we have a **stable** release for `14.0.2`?
