### ISSUE TITLE
`ResponseCookies#delete` does not work with `__Secure-`/`__Host-` cookie prefixes.

### ISSUE THREAD

**Issue by simoncave** [vercel/next.js#56632]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/suspicious-worker-939hzv

### To Reproduce

1. Open [the CodeSandbox](https://codesandbox.io/p/sandbox/suspicious-worker-939hzv).
2. Open Web Inspector.
3. Click _"Delete Cookie"_.
4. Click _"Delete Cookie (with set)"_.
5. Observe the `set-cookie` headers for the two requests in Web Inspector:
   - The first one is unexpectedly blocked by the browser.
   - The second one works as expected.

### Current vs. Expected behavior

The two buttons both attempt to delete a cookie. The `"Delete Cookie"` button demonstrates the current unexpected behavior. The `"Delete Cookie (with set)"` button demonstrates a workaround.

#### Delete Cookie

This button uses `ResponseCookies#delete`. It attempts to delete a cookie that uses [the `__Secure-` prefix](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#cookie_prefixes). When a cookie uses this prefix, it **must** use the `Secure` attribute, both when _setting_ the cookie and _deleting_ it, otherwise the `set-cookie` header will be blocked by the browser.

```tsx
cookies().delete({
  name: "__Secure-UsingDelete",
  secure: true,
  httpOnly: true,
  sameSite: "none",
})
```

##### Expected Behavior

The `set-cookie` header **should** include the `Secure`, `HttpOnly`, and `SameSite=none` attributes.

```
Set-Cookie: __Secure-UsingDelete=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Secure; HttpOnly; SameSite=none
```

##### Current Behavior

The `set-cookie` header **does not** include the `Secure`, `HttpOnly`, and `SameSite=none` attributes.

```diff
Set-Cookie: __Secure-UsingDelete=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
```

> [!WARNING]
> As the `set-cookie` header has the `__Secure-`, but does not use the `Secure` attribute, it is blocked by the browser:
>
> <img width="930" alt="Screenshot 2023-10-10 at 9 58 44 am" src="https://github.com/vercel/next.js/assets/327591/a0ec8dc0-9f55-46de-9560-5c0ee2c2e75b">

#### Delete Cookie (with set)

This button uses `ResponseCookies#set` as a workaround. It attempts to delete a cookie that uses [the `__Secure-` prefix](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#cookie_prefixes). When a cookie uses this prefix, it **must** use the `Secure` attribute, both when _setting_ the cookie and _deleting_ it, otherwise the `set-cookie` header will be blocked by the browser.

```tsx
cookies().set({
  name: "__Secure-UsingSet",
  value: "",
  expires: 0,
  secure: true,
  httpOnly: true,
  sameSite: "none",
})
```

The `set-cookie` header **does** include the `Secure`, `HttpOnly`, and `SameSite=None` attributes, as expected.

```
Set-Cookie: __Secure-UsingSet=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Secure; HttpOnly; SameSite=none
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.5-canary.4
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by joseocabarcas** [comment]
any news for that ? I have the same issue

**Comment by isoroka-plana** [comment]
I just ran into the same issue. Any reason why it doesn't work as expected? And what is the recommended workaround?

**Comment by joseocabarcas** [comment]
In my case a workaround I used `cookies().set({ ... })` with `expire = 0`

**Comment by ykzts** [comment]
Although not documented, `cookies().delete` can be given an object as an argument.

```typescript
// app/test/route.ts
import { cookies } from 'next/headers'

export function POST() {
  const cookieStore = cookies()

  cookieStore.delete({
    name: 'test',
    domain: '.example.com',
    path: '/test',
    secure: true,
  })

  return new Response(null, { status: 204 })
}
```

```console
$ curl -sI http://localhost:3000/test | grep set-cookie
set-cookie: test=; Path=/test; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Domain=.example.com
```
