### ISSUE TITLE
Back button from anchor link does not scroll to previous location

### ISSUE THREAD

**Issue by artainjast** [vercel/next.js#56643]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 16.18.0
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.5.1
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

with-turbo

### What browser are you using? (if relevant)

Chrome 117.0.5938.92

### How are you deploying your application? (if relevant)

other platforms

### Describe the Bug

I'm using ID to scroll the screen position to my element. It works fine, but the bug happens when I navigate back with the Chrome back button. it doesn't scroll to the last element.
this feature works on safari very smooth but it has some bugs on chromeSafarismoothly

### Expected Behavior

we expect to scroll to the last element with the id which we have in the URL.

### To Reproduce

https://github.com/vercel/next.js/assets/50679946/3872394d-ad21-4b68-ac70-afaa89b6bd90

**Comment by MohsinDev369** [comment]
I think this has nothing to do with next.js but how the browser history works, Check out [Browser history stack](https://developer.mozilla.org/en-US/docs/Web/API/History_API) to know more. 

One way to solve this is by just adding **replace** attribute to Next's Link tag so the link should look like this:

 ``<Link href={`/productPage/#${product}`} replace >code</Link>``  
 Notice that **replace** attribure .............................👆

you can read the [Nextjs Links component doc](https://nextjs.org/docs/app/api-reference/components/link#replace) to know more. 

Overall this is not a Next's issue I hope this helps. Happy Hacking 😸

**Comment by leerob** [comment]
I am not able to reproduce this issue. If you can consistently see this, please include a minimal reproduction in a new issue.
