### ISSUE TITLE
Errors with fresh create-next-app app using Tailwind

### ISSUE THREAD

**Issue by skoshx** [vercel/next.js#56656]
### Link to the code that reproduces this issue

https://github.com/skoshx/nextjs-create-app-error-tailwind-repro

### To Reproduce

1. Create application (`pnpx create-next-app@canary`)
2. Select settings: TypeScript (Yes), ESLint (yes), TailwindCSS (yes), use src dir? (No), App Router (yes), customize import alias? (No)
3. `pnpm dev`
4. View `localhost:3000`
5. We get the error:

./app/globals.css.webpack[javascript/auto]!=!./node_modules/.pnpm/next@13.5.5-canary.4_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!./node_modules/.pnpm/next@13.5.5-canary.4_react-dom@18.0.0_react@18.0.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./app/globals.css
TypeError: Cannot read properties of undefined (reading 'config')

**NOTE: This error does not occur if we create the project and select Tailwind CSS (No)**

### Current vs. Expected behavior

Current behavior: We get an error instantly if we run `pnpm dev` and view localhost:3000 or `pnpm build`. This error DOES NOT OCCUR if we don't use the Tailwind CSS in the setup.

Expected behavior: `pnpm dev` starts up the dev server and visiting localhost doesn't crash.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
Binaries:
  Node: 18.15.0
  npm: 9.5.0
  Yarn: 1.22.19
  pnpm: 8.6.0
Relevant Packages:
  next: 13.5.5-canary.4
  eslint-config-next: 13.5.5-canary.4
  react: 18.0.0
  react-dom: 18.0.0
  typescript: 5.0.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

**Comment by ig4e** [comment]
Same here. using npm instead fixes the problem is this pnpm related?

**Comment by lorenzo-co** [comment]
After testing with various library versions, I've identified the error to be linked with pnpm@8.6.0. Upgrading to pnpm@8.9.0 seems to resolve the issue.

Hope this helps!

**Comment by skoshx** [comment]
Thanks a lot for that @lorenzo-co , I was also on 8.6.0, weird bug!
