### ISSUE TITLE
Vercel deployment stopped working after update from 13.5.3 to 13.5.4

### ISSUE THREAD

**Issue by wojtekmaj** [vercel/next.js#56676]
### Link to the code that reproduces this issue

https://github.com/wojtekmaj/react-pdf/tree/main/sample/next-app

### To Reproduce

1. Get the code from the link above
2. Try and deploy to Vercel

### Current vs. Expected behavior

Vercel deployment should work.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 3.1.0
  pnpm: N/A
Relevant Packages:
  next: 13.5.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.0.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I've got multiple reports from users of react-pdf, a package to display PDF in React, that upon upgrading to Next.js 13.5.4 Vercel deployment no longer works. I've received confirmations that Next.js 13.5.3 was working fine. 

I have, frankly, zero experience with Vercel, I'm not sure how would I be able to test deployment there, and especially can't afford paying for a Vercel account for testing purposes.

The most unusual part about react-pdf configuration in Next.js (as well as Vite, Webpack…) is the way web worker is imported:

https://github.com/wojtekmaj/react-pdf/blob/main/sample/next-app/app/Sample.tsx#L12-L15

My users report that upon upgrading to 13.5.4, this results with:

```
Error: File /vercel/path0/.next/server/chunks/static/media/pdf.worker.min.6a40b659.js does not exist.
--
10:17:32.381 | at Job.emitDependency (/vercel/path0/node_modules/next/dist/compiled/@vercel/nft/index.js:1:39473)
10:17:32.381 | at async Promise.all (index 10)
10:17:32.382 | at async nodeFileTrace (/vercel/path0/node_modules/next/dist/compiled/@vercel/nft/index.js:1:35430)
10:17:32.382 | at async /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:251:28
10:17:32.383 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:105:20)
10:17:32.383 | at async collectBuildTraces (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:123:5)
10:17:32.500 | Error: Command "npm run build" exited with 1
```

See: https://github.com/wojtekmaj/react-pdf/issues/1630

<sub>[NEXT-1683](https://linear.app/vercel/issue/NEXT-1683/vercel-deployment-stopped-working-after-update-from-1353-to-1354)</sub>

**Comment by alexanderkalachev** [comment]
Several people including me encountered similar problem, except our apps wasn't able to deploy on Vercel because of failing to fetch data from Sanity.
Here is a discussion: https://github.com/sanity-io/next-sanity/issues/664
Downgrading from 13.5.4 to 13.5.2 enabled us to build apps on Vercel successfully.
