### ISSUE TITLE
Docs: example app with Prometheus (and possibly Grafana) integration

### ISSUE THREAD

**Issue by hamirmahal** [vercel/next.js#56681]
### What is the improvement or update you wish to see?

I think users would find it helpful if there was an example with Prometheus and Grafana integration that used TypeScript and the app router.

### Is there any context that might help us understand?

There's some interest in this topic, as you can see at https://github.com/vercel/next.js/discussions/16205.

**Comment by leerob** [comment]
We're focused on OpenTelemetry right now, but open to community contributions for examples.

https://nextjs.org/docs/app/building-your-application/optimizing/open-telemetry

**Comment by maniraj1234** [comment]
@leerob the doc doesn't have detailed steps. The setup isnt exporting logs unfortunately even after following all steps.

**Comment by leerob** [comment]
What do you mean by "isn't exporting logs"? Are you using OTEL and sending to a service?

**Comment by maniraj1234** [comment]
@leerob yes, I'm using OTEL, should we add any exporter service in the background? 

I have started the docker container as mentioned and added this to instrumentation. 
```
import { NodeSDK } from '@opentelemetry/sdk-node'
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http'
import { Resource } from '@opentelemetry/resources'
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions'
import { SimpleSpanProcessor } from '@opentelemetry/sdk-trace-node'
 
const sdk = new NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: 'kuberviz',
  }),
  spanProcessor: new SimpleSpanProcessor(new OTLPTraceExporter()),
})
sdk.start()
```

could you please help me with any sample repo link / detailed doc?
