### ISSUE TITLE
Docs: Mention the need to run npm run build first

### ISSUE THREAD

**Issue by Badrul-QAI** [vercel/next.js#56805]
### What is the improvement or update you wish to see?

I'm approaching this from the point of a newbie. I was following the instructions on this page:

`https://github.com/vercel/next.js/blob/canary/docs/01-getting-started/01-installation.mdx.`

Near the end it says  `Run npm run dev to start the development server.`

However this gives the error (on Windows at least):
`Error: ENOENT: no such file or directory, open ...`

I believe the instruction should read:
 `Run npm run build followed by npm run dev to start the development server.`

### Is there any context that might help us understand?

As described above...

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/blob/canary/docs/01-getting-started/01-installation.mdx

**Comment by IsomerX** [comment]
you do not need to run `npm run build` first, build command builds a production build while `dev` command is use for development server.
you can use `npm run start` after `npm run build` to start the production build. but you dont need to `build` before `dev`
