### ISSUE TITLE
Problem in server side execution in page dir

### ISSUE THREAD

**Issue by mohsen-salehi** [vercel/next.js#56871]
### Link to the code that reproduces this issue

https://github.com/mohsen-salehi/next-shop-full

### To Reproduce

1-save coockies and session in client 
2-authentication with that with next-auth 
3-check session in api (when i want save data in mongoDB the first i check session , but when i log session with getSession({req})
return null 
but i open api/auth/session is true i can see info from user 
in last version is ok but on new version had problem 

### Current vs. Expected behavior

I expect to get the relevant data from the server when I get the session, but it returns null .

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
{
  "name": "next-shop",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.17",
    "autoprefixer": "10.4.14",
    "bcryptjs": "^2.4.3",
    "formik": "^2.4.3",
    "js-cookie": "^3.0.5",
    "mongodb": "^6.0.0",
    "mongoose": "^7.6.0",
    "next": "13.5.4",
    "next-auth": "^4.20.1",
    "postcss": "8.4.27",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-toastify": "^9.1.3",
    "tailwindcss": "3.3.3",
    "yup": "^1.2.0"
  }
}
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by balazsorban44** [comment]
On server-side, you should be using `getServerSession`. See: https://next-auth.js.org/configuration/nextjs#getserversession
