### ISSUE TITLE
Docs: Problem with yandex metrics and app router. Need example or documentation

### ISSUE THREAD

**Issue by FierceGrandpa** [vercel/next.js#56882]
### What is the improvement or update you wish to see?

After switching to app router. Yandex Metrica no longer identifies the source in 99% of cases, and the web viewer records less than 2% of visits. There is probably an installation problem. Currently in the documentation you can only find examples from Google.

Plus, because of this, router events disappeared, I’m not sure that I wrote the hook correctly, I would like some kind of native solution from next.

Thank you in advance

### Is there any context that might help us understand?

```
layout.tsx


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" dir="ltr">
      <PreloadResources />
      <head>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
          m[i].l=1*new Date();
          for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
          k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
          (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

          ym(___, "init", {
          defer:true,
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true,
          webvisor:true,
          ecommerce:"dataLayerYa"
        });`,
          }}
        />
      </head>
      <body className={cn(montserrat.variable, roboto.variable)}>
        <noscript>
          <div>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="https://mc.yandex.ru/watch/___" style={{ position: "absolute", left: "-9999px" }} alt="" />
          </div>
        </noscript>
        <Suspense>
          <YandexMetrika />
        </Suspense>
        <Suspense>
          <ActivityGoal />
        </Suspense>
        <AppProvider>
          <Header />
          {children}
          <LayoutWidgets />
        </AppProvider>
      </body>
    </html>
  );
}
```

```
YandexMetrika.tsx

"use client";

import { useNavigation } from "../../hooks/useNavigation";

export default function YandexMetrika() {
  useNavigation({
    on: {
      routeChanged: ({ url }) => {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        window.ym(___, "hit", url);
      },
    },
  });

  return null;
}
```

```
useNavigation.tsx

import { usePathname, useSearchParams } from "next/navigation";
import { useEffect } from "react";

import { usePrevious } from "./usePrevious";

interface NavigationEvents {
  routeChanged: ({ url }: { url: string }) => void;
}

export const useNavigation = ({ on: { routeChanged } }: { on: NavigationEvents }) => {
  const pathname = usePathname();
  const prevPathname = usePrevious(pathname);

  const searchParams = useSearchParams();
  const prevSearchParams = usePrevious(searchParams);

  useEffect(() => {
    let url = window.origin + pathname;
    if (searchParams?.toString()) {
      url = url + `?${searchParams.toString()}`;
    }
    if (searchParams?.toString() !== prevSearchParams?.toString() || pathname !== prevPathname) {
      routeChanged({ url });
    }
  }, [pathname, prevPathname, prevSearchParams, routeChanged, searchParams]);
};
```

```
usePrevious.tsx

import { useEffect, useRef } from "react";

export const usePrevious = <T>(value: T) => {
  const ref = useRef<T>(value);
  useEffect(() => {
    ref.current = value;
  });
  return ref.current;
};
```

**Comment by FierceGrandpa** [comment]
I solved the problem. Next js added image preload yandex pixel. What causes ddos metrics

**Comment by domosedov** [comment]
> I solved the problem. Next js added image preload yandex pixel. What causes ddos metrics

can u share your solution?

**Comment by FierceGrandpa** [comment]
@domosedov Yes, I added a yandex pixel image to the application via dangerouslySetInnerHTML. So next js didn't optimize it via preload.

// layout.tsx

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
            m[i].l=1*new Date();
            for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
            k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
  
            ym(XXXXXX, "init", {
            defer:true,
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true,
            ecommerce:"dataLayerYa"
          });`,
          }}
        />
        <noscript
          dangerouslySetInnerHTML={{
            __html: `<div><img src="https://mc.yandex.ru/watch/XXXXXX" style="position:absolute; left:-9999px;" alt="" /></div>`,
          }}
        />
        <Suspense>
          <YandexMetrika />
        </Suspense>
        {children}
      </body>
    </html>
  );
}

// YandexMetrika.tsx

"use client";

export default function YandexMetrika() {
  useNavigation({
    on: {
      routeChanged: ({ url }) => {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        window.ym(XXXXXX, "hit", url);
      },
    },
  });

  return null;
}

// useNavigation.tsx

interface NavigationEvents {
  routeChanged: ({ url }: { url: string }) => void;
}

export const useNavigation = ({ on: { routeChanged } }: { on: NavigationEvents }) => {
  const isFirst = useRef(true);

  const pathname = usePathname();
  const prevPathname = usePrevious(pathname);

  const searchParams = useSearchParams();
  const prevSearchParams = usePrevious(searchParams);

  useEffect(() => {
    let url = window.origin + pathname;
    if (searchParams?.toString()) {
      url = url + `?${searchParams.toString()}`;
    }
    if (isFirst.current) {
      isFirst.current = false;
      routeChanged({ url });
    } else if (searchParams?.toString() !== prevSearchParams?.toString() || pathname !== prevPathname) {
      routeChanged({ url });
    }
  }, [pathname, prevPathname, prevSearchParams, routeChanged, searchParams]);
};

// usePrevious.tsx

export const usePrevious = <T>(value: T) => {
  const ref = useRef<T>(value);
  useEffect(() => {
    ref.current = value;
  });
  return ref.current;
};

**Comment by yuksak** [comment]
I was trying your solution but got this error: TypeError: window.ym is not a function. Wonder if you also had the same problem and solved it

**Comment by lu-perfect** [comment]
@yuksak  Yes, I also got this after updating to next 14. In production everything works fine, the problem is only in local development for me. I just checked for the existence of window.ym && ...

**Comment by leerob** [comment]
Looks like this is solved 😄
