### ISSUE TITLE
Docs: create-next-app has no test script

### ISSUE THREAD

**Issue by ekcrisp** [vercel/next.js#56886]
### What is the improvement or update you wish to see?

In  next.js/examples/with-jest/ it says to simply create a nextjs app with the scaffolding tool and run tests. The project the scaffolding tool produces does not have a test script, and no option was presented to the user asking if they wanted testing, this may be a bug in create-next-app. Also this documentation should include instructions for how to do that yourself for existing apps

### Is there any context that might help us understand?

create-next-app does not create a test script

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/tree/canary/examples/with-jest

**Comment by balazsorban44** [comment]
If you follow https://github.com/vercel/next.js/tree/canary/examples/with-jest#how-to-use it will have the following: https://github.com/vercel/next.js/blob/3e77d69ca0914a51f88aa1d9e42f2d36fa0db3c4/examples/with-jest/package.json#L7
