### ISSUE TITLE
Next.js 13.5.x fails to build a CommonJS lib that exports `rxjs` Observable

### ISSUE THREAD

**Issue by oliverlaz** [vercel/next.js#56897]
### Link to the code that reproduces this issue

https://github.com/oliverlaz/nextjs-rxjs-pages-reproduction

### To Reproduce

For easier reproduction, I created a Yarn monorepo with:
- `lib`: a package that exports an RxJS `Observable`
- `app`: a simple Next.js application that uses the "Pages Router"

1. Clone the reproduction repo
2. Run `yarn install` in it
3. Run `yarn build:all`

### Current vs. Expected behavior

Currently, the web app fails to compile with `next@13.5.5` and `next@canary`.
The same code runs fine when using `next@~13.4`.

```
[@nextjs-rxjs/app]: Process started
[@nextjs-rxjs/app]:    Linting and checking validity of types ...
[@nextjs-rxjs/app]:    Creating an optimized production build ...
[@nextjs-rxjs/app]:  ✓ Compiled successfully
[@nextjs-rxjs/app]:    Collecting page data ...
[@nextjs-rxjs/app]: TypeError: a.Observable is not a constructor
[@nextjs-rxjs/app]:     at 9155 (/Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/pages/index.js:1:1126)
[@nextjs-rxjs/app]:     at __webpack_require__ (/Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/webpack-runtime.js:1:145)
[@nextjs-rxjs/app]:     at 5784 (/Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/pages/index.js:1:542)
[@nextjs-rxjs/app]:     at __webpack_require__ (/Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/webpack-runtime.js:1:145)
[@nextjs-rxjs/app]:     at __webpack_exec__ (/Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/pages/index.js:1:1436)
[@nextjs-rxjs/app]:     at /Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/pages/index.js:1:1479
[@nextjs-rxjs/app]:     at __webpack_require__.X (/Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/webpack-runtime.js:1:2141)
[@nextjs-rxjs/app]:     at /Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/pages/index.js:1:1449
[@nextjs-rxjs/app]:     at Object.<anonymous> (/Users/oliverlaz/w/playground/nextjs-rxjs/packages/app/.next/server/pages/index.js:1:1521)
[@nextjs-rxjs/app]:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
[@nextjs-rxjs/app]: 
[@nextjs-rxjs/app]: > Build error occurred
[@nextjs-rxjs/app]: Error: Failed to collect page data for /
[@nextjs-rxjs/app]:     at /Users/oliverlaz/w/playground/nextjs-rxjs/node_modules/next/dist/build/utils.js:1171:15
[@nextjs-rxjs/app]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[@nextjs-rxjs/app]:   type: 'Error'
[@nextjs-rxjs/app]: }
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: 3.6.4
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.5
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC minifier (swcMinify: true), SWC transpilation

### Additional context

This issue started with Next.js 13.5, and it can be reproduced with every version up to the latest (at the time of writing, 13.5.5).

I suspect this to be related to the recent [Optimized Package Imports](https://nextjs.org/blog/next-13-5#optimized-package-imports) feature, as this error isn't present in earlier versions (tested with `13.4.19`).

I browsed through the open issues, and I found one that may be related as well:
- https://github.com/vercel/next.js/issues/55818

**Comment by adarshbyte** [comment]
there are so many open issues and this is frustating but i am still down with nextjs team

**Comment by kdy1** [comment]
<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/dfe2466e-f1d1-4dde-bda4-06c0ecdc90c5">


<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/131abbc8-996b-4879-8156-0e3866016bd1">


Closing as fixed
