### ISSUE TITLE
Unable to build because I get `getSetCookie is not a function` using nextjs starter 

### ISSUE THREAD

**Issue by luthfib** [vercel/next.js#56949]
### Link to the code that reproduces this issue

https://github.com/luthfib/auth0-nextjs-repro

### To Reproduce

1. Run `pnpm install`
2. Run `pnpm build`

Note included `.nvmrc` because this seems to only happen when on node version `18.11.0` and nextjs version `13.5.5` 

### Current vs. Expected behavior

Current behavior build fails with error `TypeError: e.getSetCookie is not a function`

Expected behavior would that this builds successfully.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.11.0
  npm: 8.19.2
  Yarn: N/A
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.6-canary.2
  eslint-config-next: 13.5.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

<sub>[NEXT-1691](https://linear.app/vercel/issue/NEXT-1691/unable-to-build-because-i-get-getsetcookie-is-not-a-function-using)</sub>

**Comment by grzegorzpokorski** [comment]
Related https://github.com/vercel/next.js/issues/56947

**Comment by balazsorban44** [comment]
Thanks, looking into this currently! As a workaround, you can make sure you are on at least Node.js 18.16

https://github.com/vercel/next.js/issues/56947#issuecomment-1766742445

**Comment by huozhi** [comment]
We patched a fix https://github.com/vercel/next.js/releases/tag/v13.5.6, please upgrade to the new version
