### ISSUE TITLE
App freezes when fetch() request is revalidated inside Root layout

### ISSUE THREAD

**Issue by Emiliano-Bucci** [vercel/next.js#56950]
### Link to the code that reproduces this issue

https://github.com/Emiliano-Bucci/next-fetch-revalidate-issue

### To Reproduce

1 npm run build
2 npm run start
3 refresh the browser (soft and hard) various times, close the tab and open a new http://localhost:3000/ tab
4 after a while the app should freeze

### Current vs. Expected behavior

The app shouldn't freeze.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Platform: macOs 14.0 (23A344),
Package Manager: npm
Nodejs: v18.18.2
Nextjs: canary
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I guess is related to this -> https://github.com/vercel/next.js/issues/56580

**Update**: It **seems** that with next@13.4.19 the problem doesn't occur

**Comment by Emiliano-Bucci** [comment]
Up.
This issue is still relevant with latest next js version
@timneutkens

**Comment by gffuma** [comment]
@Emiliano-Bucci this https://github.com/vercel/next.js/pull/57737 should fix also this issue

**Comment by Emiliano-Bucci** [comment]
@gffuma I confirm that with latest canary this issue is fixed! Thanks a lot man! :)
