### ISSUE TITLE
Docs: Lack whitespace in some `nextjs.org/learn/` chapters

### ISSUE THREAD

**Issue by serifold** [vercel/next.js#56977]
### What is the improvement or update you wish to see?

Add necessary whitespace to these sentences, such as:

![image](https://github.com/vercel/next.js/assets/80401151/c9c2de9f-69e9-48ad-8311-99c694ad6812)

### Is there any context that might help us understand?

I have tried in Firefox/Chrome/Edge, it always displays lacking whitespace, so it shouldn't be the browser's issue. Except the sentence above, there are some other similar typos in previous `nextjs.org/learn/`'s chapters, unfortunately I forgot to mark them while reading at that time, please find and fix them.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/seo/improve/third-party-scripts

**Comment by balazsorban44** [comment]
Thanks for the feedback! Currently, we are reworking the Next.js Learn guides and this will be addressed too!
