### ISSUE TITLE
Unable to run development server `

### ISSUE THREAD

**Issue by amartey-tricky** [vercel/next.js#56982]
### Link to the code that reproduces this issue

https://github.com/amartey-tricky/travel-app

### To Reproduce

* bun dev

### Current vs. Expected behavior

I expected the development server to be started but I observed 
![image](https://github.com/vercel/next.js/assets/102452248/5ae7b955-542d-4586-9eda-ecbd274be7a4)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 20.8.0
  npm: 9.8.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.5
  eslint-config-next: 13.5.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

TypeScript (plugin, built-in types)

**Comment by balazsorban44** [comment]
Which version of Bun are you using? I cannot reproduce this on my machine.

**Comment by balazsorban44** [comment]
This is an upstream issue in any case, but I see that they have already fixed it, probably just waiting to be released: https://github.com/oven-sh/bun/pull/6542
