### ISSUE TITLE
Font preloading isn't creating the appropriate tags and font manifest files are empty?

### ISSUE THREAD

**Issue by ThetripGr** [vercel/next.js#57008]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.16.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.6-canary.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

The installation step , npx create-next-app@latest

### What browser are you using? (if relevant)

irrelevant

### How are you deploying your application? (if relevant)

irrelevant

### Describe the Bug

I had a project running and i decided to use the new next/font feature to integrate my local fonts , but they do not seem to preload. I even created a fresh project with ```npx create-next-app@latest``` and the already included Google font on the app created doesn't produce a preload link tag inside the DOM. 

It seem the font-manifest and next font manifest files are remaining empty so next can't find the appropriate entries to create the preloads!

example of the json output file
```{"pages":{},"app":{},"appUsingSizeAdjust":false,"pagesUsingSizeAdjust":false}```

### Expected Behavior

Having preload tags in the DOM for declared fonts

### To Reproduce

just run  npx create-next-app@latest and check the DOM and the according font manifest files in the .next folder

**Comment by balazsorban44** [comment]
Please use the [bug report template](https://github.com/vercel/next.js/issues/new/choose) for reporting a bug
