### ISSUE TITLE
Docs: Add some real-world code to Vitest example, otherwise it doesn't help

### ISSUE THREAD

**Issue by silvenon** [vercel/next.js#57019]
### What is the improvement or update you wish to see?

I'd like to see a more realistic Vitest example, testing pages that are using Next.js-specific functionality like `next/router` or `next/navigation`. In its current state it won't help people test Next.js apps because pages are pretty much empty and are just being tested as regular components. There's no mocking or anything.

Alternatively I'd like Next.js docs to acknowledge Vitest, but say that Vercel doesn't yet offer an official way to test Next.js apps yet, but that there are community mocks out there like [next-router-mock](https://www.npmjs.com/package/next-router-mock). That way it's at least being honest and setting realistic expectations for developers.

### Is there any context that might help us understand?

As a developer who knows how to test I already know how to set up Vitest in a project, it's the same anywhere. I'm only looking for Next.js-specific parts, which the official example doesn't offer.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/optimizing/testing

**Comment by balazsorban44** [comment]
Hi, the Vitest example is available under https://github.com/vercel/next.js/tree/canary/examples/with-vitest if you have suggestions, we welcome PRs!

next-router-mock is mentioned on the page you linked: https://nextjs.org/docs/pages/building-your-application/optimizing/testing#community-packages-and-examples
