### ISSUE TITLE
Request is hitting cache with revalidation even with a hard refresh

### ISSUE THREAD

**Issue by eric-burel** [vercel/next.js#57039]
### Link to the code that reproduces this issue

https://github.com/eric-burel/incremental-304

### To Reproduce

1. Start the application **in production** `npm run build && npm run start`
2. Refresh the page a few time, the timestamp won't update
3. Open the page in another browser: you may get an empty page

## Current

The home page has a 10 second revalidation and shows a timestamp. It's a RSC and it also logs the timestamp during server render.

- The timestamp stops refreshing client-side, I get the statically rendered timestamp (I feel like it might update on the first render then stop updating but can't be more precise sorry)
- Yet the page is correctly re-rendered server-side, I see an up-to-date timestamp
![image](https://github.com/vercel/next.js/assets/7983005/20c916aa-f36e-44d0-ba62-96cecf79aecd)
- Hard refresh with shift+F5 in Chromium does't change the issue
- Opening another browser might also hit the cache, but I get an empty page

Response in Chrome:
![image](https://github.com/vercel/next.js/assets/7983005/fd6bae3e-17e8-4dc2-a240-4305e39525a7)

Response in Firefox (even worst because it's empty):
![image](https://github.com/vercel/next.js/assets/7983005/a9048c0a-2ae5-4da2-bdc7-a7c549d9548d)

## Expected
- If I hit refresh continuously, I should see a new timestamp after 10 seconds
- At least it should work with hard refresh or using another browser

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #34~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 13:12:03 UTC 2
Binaries:
  Node: 18.16.1
  npm: 9.5.1
  Yarn: 1.22.19
  pnpm: 7.6.0
Relevant Packages:
  next: 13.5.6-canary.7
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

**Comment by thijsadrmat** [comment]
Looks like the same issue as: https://github.com/vercel/next.js/issues/56018

**Comment by eric-burel** [comment]
Yes thanks for figuring the duplicate, I'll close in favour of #56018
