### ISSUE TITLE
Error with `generateStaticParams` function despite its existence

### ISSUE THREAD

**Issue by k-taro56** [vercel/next.js#57038]
### Link to the code that reproduces this issue

https://github.com/k-taro56/next-bug-report

### To Reproduce

Set up Next.js.
Add `output: 'export'` to `next.config.js` to enable static output.
Create a page that allows dynamic routing.
Create the `generateStaticParams` function and make it return an empty array.
Run `next build`.

Error Message:
`Error: Page "/[slug]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.`

### Current vs. Expected behavior

Current behavior:
An error is raised indicating that the generateStaticParams function does not exist.

Expected Behavior:
The generateStaticParams function should return an array with at least one element.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
Binaries:
  Node: 18.18.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.6-canary.7
  eslint-config-next: 13.5.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

App Router, Static HTML Export (output: "export")

<sub>[NEXT-1951](https://linear.app/vercel/issue/NEXT-1951/error-with-generatestaticparams-function-despite-its-existence)</sub>

**Comment by viktorronnback** [comment]
The repro code is missing any returned pages in the generateStaticParams function, for example: 

`export const generateStaticParams = () => [{ slug: "page" }];`

However I agree that the error message is misleading, if a maintainer agrees I could add a PR to improve the error message.

**Comment by airtonix** [comment]
@viktorronnback what about when the url looks like: 

```
/keystatic/[...params]
```

despite my `src/app/keystatic/[...params]/page.tsx` looking like: 

```
export default function Page() {
    return null;
}

export async function generateStaticParams() {
    return [{ params: [] }]
}
```
