### ISSUE TITLE
The page is breaking after revalidation in Next.js 13 when in app route mode, resulting in a blank white page.

### ISSUE THREAD

**Issue by sinaprgm1376** [vercel/next.js#57058]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Enterprise
Binaries:
  Node: 19.4.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.5.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

nothing

### What browser are you using? (if relevant)

firefox

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

I am experiencing a problem with nextjs 13.5.6 in app route mode. I create a basic Nextjs project and created a folder named "product-category" in the "app" folder. Inside that folder, I created a file named "page.js".

When the data is updated from the API and the revalidate operation is performed on the page, if the page is reloaded with Ctrl+F5, it displays the raw HTML for everyone and essentially doesn't return a blank white screen without any correct information.(in production)

### Expected Behavior

I expect that, as in previous versions and in the pages mode, the revalidate operation will be performed correctly and the page will be fully displayed.

### To Reproduce

return a blank screen page

**Comment by Shubhdeep12** [comment]
Please add a codesandbox link, that would be helpful

**Comment by pma9** [comment]
https://github.com/vercel/next.js/issues/56018
