### ISSUE TITLE
Unable to add multiple meta tags with the same name (app directory)

### ISSUE THREAD

**Issue by hishamank** [vercel/next.js#57051]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/staging-firefly-cf45hv

### To Reproduce

it's easy to reproduce, create a new next project, using the app directory 

use generateMetadata other field to add meta tags that require multiple ones with the same name

### Current vs. Expected behavior

I want to add multiple meta tags with the same name, **example** _music:song, citation_author..._

I was checking the `metadata-interface.d.ts` file 
`    other?: {
        [name: string]: string | number | Array<string | number>;
    } & DeprecatedMetadataFields;
`
using the `generateMetadata` function
```
export async function generateMetadata() {
  return {
    other: {
     'music:song:track': ['1','2','3']
    }
  };
}
```
is resulting in 
```
<meta name="music:song:track" content="1,2,3">
```
instead of 
```
<meta name="music:song:track" content="1">
<meta name="music:song:track" content="2">
<meta name="music:song:track" content="3">
```

And adding `<meta />` tags in  next `<head />` is not rendering too

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant Packages:
      next: 13.4.13-canary.13
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.3
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

<sub>[NEXT-1746](https://linear.app/vercel/issue/NEXT-1746/unable-to-add-multiple-meta-tags-with-the-same-name-app-directory)</sub>

**Comment by Shubhdeep12** [comment]
HI @huozhi is this a valid ask?

Because I can see here - [commit](https://github.com/vercel/next.js/commit/1b9fea7a8c2f76b96c5b3691c09237049c183bef) that for custom metadata tags(added under other) we just joined the content array. Whereas for other metadata tags, we mapped the tags if the content is an Array.

If this is a valid bug, I would love to fix this.

**Comment by Shubhdeep12** [comment]
Hi @balazsorban44 is it a valid bug?

**Comment by huozhi** [comment]
Wasn't covering this case before but sounds good to support 👍

**Comment by hishamank** [comment]
@huozhi thanks for your reply,   
I understand the goal of adding all metas to next metadata api and mainly my needs were around the new opengraph metas for music mentioned here[ https://developers.facebook.com/docs/opengraph/music]( https://developers.facebook.com/docs/opengraph/music)
but it's nice to have the option to add custom metas freely, and I think allowing the user to add a array of metas in others instead of an object would solve that
