### ISSUE TITLE
Docs: Open to including a guide on CSS Hooks?

### ISSUE THREAD

**Issue by nsaunders** [vercel/next.js#57067]
### What is the improvement or update you wish to see?

I would like to see a guide on how to use [CSS Hooks](https://css-hooks.com) in a Next.js app, within the _Styling_ section of the docs.

### Is there any context that might help us understand?

As you know, the simplest way to style an element is via the `style` prop. Of course, its many "feature gaps" (e.g. pseudo-classes and responsive design) drive people to complex solutions like CSS-in-JS, utility classes, and "zero-runtime" solutions. To name a few concerns:

* **CSS-in-JS**: performance, side effects, SSR challenges
* **Utility classes**: unfamiliar/arbitrary syntax, limited flexibility, upfront cost of loading of unused rulesets
* **Zero-runtime**: complex build processes

To be fair, these are clever solutions developed by talented people, but my point is that they could easily be viewed as "workarounds": People who are interested in these want to colocate the HTML and CSS, but there's no truly simple way to do it.

But what if the `style` prop can do more than we thought?

As it turns out, CSS Variables are "programmable", i.e. capable of toggling between _arbitrary values_ based on some condition, like a matching pseudo-class or media query. (If you'd like more detail, I've described how it works in a recent [blog post](https://nsaunders.dev/posts/css-madness-to-hooks#the-fallback-trick).)

CSS Hooks provides syntactic sugar over this technique, delivering a familiar authoring experience that could be summarized as "the `style` prop, but with advanced CSS capabilities".

Here's an example of how you can implement a hover effect using CSS Hooks:

```jsx
function Button(props: Props) {
  return (
    <button
      {...props}
      style={hooks({
        background: "white",
        hover: {
          color: "blue", // notice the arbitrary value
        },
      })}
    />
  );
}
```

As you can see, the `hooks` API is practically the same as the `style` prop itself, the key difference being the ability to nest additional style objects corresponding to each hook you'd like to take advantage of, whether that's a basic `hover`, `focus`, or `disabled` hook; or even a custom hook (yes, this system is fully configurable, and the API for that is dead simple as well). You can even compose hooks by additional nesting.

As a new project, I am trying to build awareness because I want to give people a familiar, flexible, and easy way to create engaging UIs, while at the same time helping them to simplify their tech stacks.

Would the Next.js team be willing to help me do that, by listing CSS Hooks in the _Styling_ section of the docs alongside Tailwind, CSS-in-JS, and CSS Modules?

Please let me know if you are open to a pull request. If so, I'll write up a guide on how to use CSS Hooks in a Next.js app.

Thank you for considering my request and, of course, for all your hard work on this fantastic framework.

### Does the docs page already exist? Please link to it.

No, but it would live within this section: https://nextjs.org/docs/app/building-your-application/styling

**Comment by akbng** [comment]
If you don't have any problems, I am willing to write the docs. I have went through your article and I need to test it on nextjs app router. I will need some time for that, and I may reach out to you for help if needed.

**Comment by balazsorban44** [comment]
Hi, thanks! Great project!

I think we could eventually add it to the docs, but it would be nice to see some adoption/maturity first. I see the package is a month old and doesn't have much adoption yet.

To begin, I think we could start with [adding an example](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md) and come back to this at a later point. Feel free to open a PR!
