### ISSUE TITLE
`dynamic = 'force-dynamic'` specified in `layout.tsx` is not applied in Next.js 13.5.4 or later

### ISSUE THREAD

**Issue by uniunitaro** [vercel/next.js#57075]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/fervent-orla-8w5pz6

### To Reproduce

Run `next build` in the above codesandbox, then run `next start`.

### Current vs. Expected behavior

Prior to 13.5.3, the `dynamic = 'force-dynamic'` setting in the layout file was successfully applied in all routes to which the layout file was applied.
In the codesandbox example, it is expected that the `searchParams` in the page props will be updated correctly when the "Add search params" link is clicked on both the home page and the `/newpage` page. However, in reality, they are only successfully updated on the top page, and not on the `/newpage` page.

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 16.17.0
  npm: 8.15.0
  Yarn: 1.22.19
  pnpm: 7.1.0
Relevant Packages:
  next: 13.5.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by AlandSleman** [comment]
I can confirm that this issue still persists on canary version 13.5.7-canary.11.
