### ISSUE TITLE
Docs: Incorrect command for creating next app using bun

### ISSUE THREAD

**Issue by braden-godley** [vercel/next.js#57097]
### What is the improvement or update you wish to see?

On the page [create-next-app](https://nextjs.org/docs/pages/api-reference/create-next-app) the command used to create a Next.js application using bun has a typo. There is an extra hyphen between 'create' and 'next'.

Solution is to delete the hyphen, so that the command becomes
`bun create next-app`

### Is there any context that might help us understand?

Not much to add.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/create-next-app

**Comment by AlandSleman** [comment]
Not sure which command you're referring to, there is only one bun related command which is `bunx create-next-app` which is working as expected.

**Comment by braden-godley** [comment]
Woopsie, thx.
