### ISSUE TITLE
[Examples] "with-aws-amplify" but with App Router instead of Pages Router

### ISSUE THREAD

**Issue by jeffpball** [vercel/next.js#57127]
### What is the improvement or update you wish to see?

I would like to see a repo created in addition to the existing ["with-aws-amplify"](https://github.com/vercel/next.js/tree/canary/examples/with-aws-amplify) repo, maybe titled "with-aws-amplify-approuter" that would provide the same Todo app but using App Router instead of Pages Router

### Is there any context that might help us understand?

Provide newcomers to Next.js and AWS Amplify a sample Todo app that uses App Router in addition to other features that are already implemented in the ["with-aws-amplify"](https://github.com/vercel/next.js/tree/canary/examples/with-aws-amplify) example repo, which uses the Pages Router

Note: I'm not sure if "Documentation" was the correct category to create an Issue for this topic. I didn't see a clear set of steps for requesting a new example repo.

**Comment by balazsorban44** [comment]
hi, generally we would just like to convert examples to App Router instead of maintaining multiple variants. Feel free to work on it if you like, open a PR, and we can review!

**Comment by Rakshit358** [comment]
Hey can I work on this please....

**Comment by adarshbyte** [comment]
https://github.com/vercel/next.js/issues/56844 aws-amplify package has issue running with turbopack, the amplify core developer say they are using some packages like "fs" which are optional to be compiled and compiled by turbopack but not by webpack. And hence breaking when i run npm run dev --turbo

**Comment by jeffpball** [comment]
> Hey can I work on this please....

Not sure if there is someone designated to say yes or no, but as far as I'm concerned you should go for it. I am going to try working on it too just for my own edification and will make a PR if I come up with anything good. I'll look out for any other PRs on that repo in case anyone gets to it before I do.

**Comment by its-kunal** [comment]
I would like to contribute to this issue.

**Comment by Marquis4484** [comment]
Can I contribute also?

**Comment by adarsh-drishya** [comment]
Instead of asking, create a PR ppl

**Comment by shanu-user** [comment]
I am not able to execute the with-aws-amplify project to see how todo app is designed and it's working.

**Comment by leerob** [comment]
We're planning to direct users to the official Amplify documentation versus this example, since they're maintaining the documentation and guidance on their side. Let me get a PR for this 🙏 

https://docs.amplify.aws/guides/hosting/nextjs/q/platform/js/
