### ISSUE TITLE
[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/home/kali/Documents/GitHub/23_store/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/home/kali/Documents/GitHub/23_store/.next/cache/webpack/client-development-fallback/0.pack.gz'

### ISSUE THREAD

**Issue by nicitaacom** [vercel/next.js#57128]
### Link to the code that reproduces this issue

https://github.com/nicitaacom/23_store

### To Reproduce

I got this error during developent
So to reproduce make git clone - pnpm i - pnpm dev
And check you console in terminal

### Current vs. Expected behavior

I got some warning I don't know how to fix
I want exact message how to fix this warning and get no warnings in my terminal console

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Debian 6.5.3-1kali2 (2023-10-03)
Binaries:
  Node: 18.13.0
  npm: 9.2.0
  Yarn: 1.22.19
  pnpm: 8.9.0
Relevant Packages:
  next: 13.5.3
  eslint-config-next: 13.5.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

**Comment by balazsorban44** [comment]
I was unable to reproduce this issue, but I also see you did not test with `next@canary` as pointed out in the bug report template. Please do. If this issue still reoccurs, please open a new issue with an up-to-date reproduction.

**Comment by nicitaacom** [comment]
> as pointed out in the bug report template. Please do

My bad  - Thank you for pointing this
This bug happens randomly that's why not always possible to reproduce it
