### ISSUE TITLE
<GoogleTagManager> types in @next/third-parties seem incorrect compared to e2e test usage

### ISSUE THREAD

**Issue by philwolstenholme** [vercel/next.js#57126]
### Link to the code that reproduces this issue

https://github.com/philwolstenholme/next-3p-gtm

### To Reproduce

<img width="1070" alt="image" src="https://github.com/vercel/next.js/assets/6339853/2b2269fa-b2f7-4d4e-bb42-f07311d32608">

* Clone example repo
* Run TS

```
Type '{ gtmId: string; }' is missing the following properties from type 'GTMParams': dataLayer, dataLayerName, auth, previewts(2739)
```

### Current vs. Expected behavior

The required props should match the examples in https://github.com/vercel/next.js/blob/canary/test/e2e/third-parties/pages/gtm.js#L11 where only the `gtmId` is needed.

```
<GoogleTagManager gtmId="GTM-XYZ" />
```

The extra options (datalayer name etc) are not needed as the `GoogleTagManager` has defaults: https://github.com/vercel/next.js/blob/v13.5.7-canary.11/packages/third-parties/src/google/gtm.tsx#L24-L32

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.7-canary.11
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```
```


### Which area(s) are affected? (Select all that apply)

TypeScript (plugin, built-in types)

### Additional context

_No response_

**Comment by philwolstenholme** [comment]
FYI @janicklas-ralph and @housseindjirdeh. The GTM component is looking good and I'm ready to use it, but I think the types might need adjusting to make some of the props optional?

**Comment by balazsorban44** [comment]
Looks like some props can be made optional. Feel free to open a PR!

https://github.com/vercel/next.js/blob/888c3a7439d5965d98bdcbcf5f249f2fe8d1a6f2/packages/third-parties/src/google/gtm.tsx#L13-L19

**Comment by philwolstenholme** [comment]
@balazsorban44 - good point! 😁 https://github.com/vercel/next.js/pull/57153
