### ISSUE TITLE
Docs: pull_request_template.md file not displaying in browser due to being commented out

### ISSUE THREAD

**Issue by DerenToy** [vercel/next.js#57172]
### What is the improvement or update you wish to see?

While reading the contributing.md file to contribute to Next.js, I checked the 'Pull Request Descriptions' section and opened the [pull_request_template.md](https://github.com/vercel/next.js/blob/canary/.github/pull_request_template.md) file to read it before making a contribution. However, I was met with an empty page. Upon downloading and inspecting the file, I noticed it was commented out. 

I would like the documentation to be viewable in the browser. 

While researching how to contribute, I was delighted to find something I could contribute to. 😄 

### Is there any context that might help us understand?

<img width="1706" alt="image" src="https://github.com/vercel/next.js/assets/64274085/36107ff2-ee4f-4063-9ba0-f4b6d7032a73">

**Comment by balazsorban44** [comment]
Thanks, this is intentional to keep the open pull request template text to a minimum. You can check out the content by clicking the `Code` button: https://github.com/vercel/next.js/blob/canary/.github/pull_request_template.md?plain=1
