### ISSUE TITLE
`openGraph.authors` listed in documentation but fails TypeScript checks

### ISSUE THREAD

**Issue by EvHaus** [vercel/next.js#57200]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/upbeat-wilson-6gc5h8?file=%2Fapp%2Flayout.tsx%3A17%2C3

### To Reproduce

Add the following export to any App router layout:

```ts
export const metadata: Metadata = {
	openGraph: {
		authors: ['Ev Haus'],
		type: 'website',
	},
};
```

### Current vs. Expected behavior

TypeScript will fails with:

```
Type '{ authors: string[]; type: "website"; }' is not assignable to type 'OpenGraph | null | undefined'.
  Object literal may only specify known properties, and 'authors' does not exist in type 'OpenGraphWebsite'
```

However the Next.js documentation ([here](https://nextjs.org/docs/app/api-reference/functions/generate-metadata#opengraph)) says the `authors` key is valid and supported.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jun 2 00:45:15 UTC 2023
Binaries:
  Node: 20.6.1
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A


warn  - Latest canary version not detected, detected: "13.5.6", newest: "13.5.7-canary.14".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
```

### Which area(s) are affected? (Select all that apply)

App Router, TypeScript (plugin, built-in types)

**Comment by Shubhdeep12** [comment]
Hey @EvHaus I guess authors are only valid when the type of open graph is an article or book. it is not valid when the type is set to website. that is the reason for getting an error here.

cc @balazsorban44 @huozhi

**Comment by EvHaus** [comment]
I see. That makes sense I suppose. I wonder if the documentation could be more clear about that. I was hoping to set all the `og:*` meta values once in the top layout and then only configure the ones I need to be different per page within each page.

**Comment by Shubhdeep12** [comment]
Yup you can do it. For the website you can specify the opengraph metadata on top in layout. And fir the pages with articles and their authors you can have metadata defined in the page. :)

**Comment by huozhi** [comment]
Hi you can reference to [The Open Graph protocol](https://ogp.me/) for more details of which fields can be listed as opengraph properties when it's in different types
