### ISSUE TITLE
Docs: Seeing Error in Browser While Clicking on Image on Doc

### ISSUE THREAD

**Issue by ankurdotcom** [vercel/next.js#57212]
### What is the improvement or update you wish to see?

Document Page :: https://nextjs.org/docs/app/building-your-application/routing

While click on Image getting error  on browser console :  https://nextjs.org/docs/app/building-your-application/routing#terminology

`
DOMException: HTMLDialogElement.showModal: Dialog element is not connected
    NextJS 7
3523-a425d1b36a8f299b.js:1:5644
`

Browswer user : Firefox , Version 115.3.0esr (64-bit)

### Is there any context that might help us understand?

While click on Image getting error  on browser console :  https://nextjs.org/docs/app/building-your-application/routing#terminology

`
DOMException: HTMLDialogElement.showModal: Dialog element is not connected
    NextJS 7
3523-a425d1b36a8f299b.js:1:5644
`

Browswer user : Firefox , Version 115.3.0esr (64-bit)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing#terminology

**Comment by Grinv** [comment]
I came across with the same problem here: https://nextjs.org/docs/app/building-your-application/caching
Browser Google Chrome Version 118.0.5993.96

**Comment by balazsorban44** [comment]
I could not reproduce this, it's likely a Firefox add-on or Chrome extension that causes the issue, so not a bug. Thanks for reporting though!
