### ISSUE TITLE
App Router behind SSL reverse proxy forces full page refresh instead of soft-navigation

### ISSUE THREAD

**Issue by JavierMartinz** [vercel/next.js#57338]
### Link to the code that reproduces this issue

Same nginx config

https://github.com/JavierMartinz/sample-project (using App Router, not working)
https://github.com/JavierMartinz/sample-project-pages-router (using Pages Router, working)

### To Reproduce

1. Run the the project in a production environment
2. Click on the "Go to SPA page" button. You will be redirected to another page.

### Current vs. Expected behavior

**Current**

If you are running this locally or through a Vercel vanity URL, you will see how a soft-navigation is performed. However, if you access this App through nginx proxy, you will be redirected with a full page reload.

**Expected**

If should do soft-navigation, without reloading the whole page.

## Sample project

You can check both behaviours with this sample project:

#### ❌ Reverse proxy to Vercel project using **App Router** -> doing full page refresh
https://sample-project-app-router.javimartinez.es/

#### ✅ Reverse proxy to Vercel project using **Pages Router** -> working (soft-navigation)
https://sample-project-pages-router.javimartinez.es/

#### ❌ Reverse proxy to self-hosted project using **App router** (NextJS built-in server) -> doing full refresh
https://sample-self-hosted-app-router.javimartinez.es/

#### ✅ Reverse proxy to self-hosted project using **Pages router** (NextJS built-in server) -> working (soft-navigation)
https://sample-self-hosted-pages-router.javimartinez.es/

#### ✅ Vercel vanity url to Vercel project using **App Router** -> working (soft-navigation)
https://sample-project-javiermartinz.vercel.app/

#### ✅ Vercel vanity url to Vercel project using **Pages Router** -> working (soft-navigation)
https://sample-project-pages-router-javiermartinz.vercel.app/

#### ✅ NextJS built-in production server running in local (Pages or App router) -> working (soft-navigation)
`next build && next start` and access to http://localhost:3000

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 20.8.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.7-canary.23
  eslint-config-next: 13.4.13
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

Whenever a link is clicked and navigation is fired, the browser does a full refresh instead of soft-navigation. However, this **only happens when using nginx and App Router**, if the app is accessed locally (App or Pages router), through (App or pages router) Vercel or with nginx and Pages router, the soft navigation of the SPA works.

I can confirm it still fails with latest canary and also since at least v13.

**Comment by JavierMartinz** [comment]
@timneutkens am I missing any header or anything? 🤔

**Comment by khuezy** [comment]
Do you get this on 13.5.6? I have a nginx proxy in front of my `node server.js` (standalone) and I don't have any hard navigations. Is your nginx doing proxy caching? If so, you can get hard navs when a new deployment references old caches, so you'll need to clear the cache before.

**Comment by JavierMartinz** [comment]
Yes, it happens with 13.5.6 and with v14 @khuezy. My nginx conf is

```
server {
  listen [::]:443 ssl;
  listen 443 ssl;

  # Configure SSL
  ssl_certificate        /etc/ssl/javimartinez.es.pem;
  ssl_certificate_key    /etc/ssl/javimartinez.es.key;

  # The host name to respond to
  server_name sample-project.javimartinez.es;

  # Remove trailing slash
  rewrite ^/(.*)/$ /$1 permanent;

  # Remove any url starting with index.php
  rewrite ^/index.php/(.*) /$1 permanent;

  client_max_body_size 25m;

  location / {
    proxy_pass              https://sample-project-javiermartinz.vercel.app;
    proxy_http_version      1.1;
    proxy_set_header        Upgrade $http_upgrade;
    proxy_set_header        Connection 'upgrade';
    proxy_set_header        Host sample-project-javiermartinz.vercel.app;
    proxy_ssl_server_name   on;
    proxy_cache_bypass      $http_upgrade;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

**Comment by JavierMartinz** [comment]
@khuezy I've found the cause of the issue I think. I installed nginx in a new server and used `HTTP` (port 80) instead of HTTPS and it started working. I modified the configuration to use `HTTPS` (port 443) and it fails as I described in the original issue.

My conclusion is that I'm probably missing a header or something that is making it fail. Users are connecting to reverse proxy through HTTPS, but `nginx` is using `HTTP` to communicate with NextJS built-in server.

However, it's failing when using Vercel and not a local NextJS server, because Vercel is using HTTPS. Hence, it must be an additional header/config what is missing.

**Comment by khuezy** [comment]
My Nginx config is also port 80 but there is a certificate for SSL 
I'm able to reproduce the hard reload when I didn't clear the cache, but when I do a full cache wipe, my links didn't hard reload

**Comment by JavierMartinz** [comment]
@khuezy I tried with the standalone server form Pages router documentation and still doesn't work for me. Could you please show me your nginx conf?

**Comment by khuezy** [comment]
I'm using this template: https://github.com/fly-apps/nginx-cluster
The only thing extra that I had to add was the `proxy_set_header origin <same as your proxy_pass>`
And in the `start.sh` before you execute `nginx`, you need to clear the cache, eg `rm -rf /data/nginx-cache/*` or if you want to clear a specific file/dir, use https://github.com/magiclen/nginx-cache-purge

**Comment by JavierMartinz** [comment]
For the record... it's not something (at least not only) wrong in nginx, but with App Router. I've set a new project only using `pages` router and same nginx configuration. It worked like a charm. So we can now conclude it's App Router.

**Comment by khuezy** [comment]
Yea that's very possible. I'm on 13.5.6 +app router w/ the nginx config above but I'm not getting any hard reloads.

**Comment by JavierMartinz** [comment]
I just updated the issue description, providing a project only using `Pages router`. As everyone can check, it works :) so it's something that was added when supporting the App Router.

**Comment by khuezy** [comment]
Try adding these headers:
next-url
rsc
next-router-prefetch
next-router-state-tree
accept

**Comment by JavierMartinz** [comment]
I finally found out the cause of the full page refresh. I was using nginx with [some configuration improvements](https://github.com/h5bp/server-configs-nginx/tree/main) from h5bp. The culprit was `text/x-component` media type, specifically [this line](https://github.com/h5bp/server-configs-nginx/blob/862527003373d66e5da3147b9fd42fd24fe2442f/h5bp/media_types/character_encodings.conf#L27)

As soon as I commented it out, it started working as it should. I guess they mess somehow with NextJS App Router and it's safe to remove it.
