### ISSUE TITLE
Docs: Debugging is missing

### ISSUE THREAD

**Issue by suchcodemuchwow** [vercel/next.js#57348]
### What is the improvement or update you wish to see?

- There is no debugging under Next.js (App Router) docs

### Is there any context that might help us understand?

- Debugging for Next.js (Pages Router) in Webstorm docs is lacking the server side debugging because the configuration provided is only for client side debugging not server side

I am having really hard time setting up debugging for my traditional turbo repo next.js application in Webstorm. I have visited almost all resources online Next.js/Turbo Repo/Webstorm Docs, Github Issues/Code Search, Reddit, Medium and couldn't find any material to at least figure out myself. It's unbelievable there is nothing you can find about Next.js debugging in Webstorm w/o Turbo Repo 

### Does the docs page already exist? Please link to it.

No page exist

**Comment by leerob** [comment]
We have this planned and will get to it, thank you 🙏

**Comment by suchcodemuchwow** [comment]
Thanks for fast reply 🤗
