### ISSUE TITLE
next dev bug: ReferenceError: performance is not defined

### ISSUE THREAD

**Issue by ymrdf** [vercel/next.js#57385]
### Link to the code that reproduces this issue

https://github.com/ymrdf/nextjs-bug-report

### To Reproduce

1. fellow this tutorial(https://nextjs.org/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs) to the step `Running the development server` and run `npm run dev`. or clone `https://github.com/ymrdf/nextjs-bug-report` and run `npm run dev`
2, you will get this error:
```

> next-test@1.0.0 dev /media/gao/1a0b122f-05c3-4067-8e69-4fc86ce7df23/work/test/next
> next dev

/media/gao/1a0b122f-05c3-4067-8e69-4fc86ce7df23/work/test/next/node_modules/next/dist/bin/next:57
performance.mark("next-start");
^

ReferenceError: performance is not defined
    at Object.<anonymous> (/media/gao/1a0b122f-05c3-4067-8e69-4fc86ce7df23/work/test/next/node_modules/next/dist/bin/next:57:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-test@1.0.0 dev: `next dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the next-test@1.0.0 dev script.
```

### Current vs. Expected behavior

expect to launch a nextjs dev server

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
running  `npx --no-install next info` or `npx next info`  will also produce this error `performance is not defined`

info:
next: 13.5.6
node: 14.21.3
npm:6.14.18
system: ubuntu 22.04.3 LTS
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by mrivotti** [comment]
Hello! I was getting the same error and i think the problem was having an old version of node installed. I updated node to version 20.9.0 and it started working. You have v14.21.3, maybe you are having the same issue. Hope this helps

**Comment by Kikky** [comment]
Node v16.20.2 on ubuntu 22.04.3 LTS is working fine for me

**Comment by Wdam** [comment]
node 14.17.3 same error

**Comment by Atifarooq** [comment]
Please use node v18, It works on it.

**Comment by chai-kung** [comment]
change version to node 16+ is work, but is there any solution for node 14 (my other projects won't run on higher version)

**Comment by ymrdf** [comment]
That update node can resolve this problem. They have said that nextjs depend on Node.js 18.17 or later on the document. I didn't notice it!

**Comment by Krushna-kp** [comment]
use node 18.17.0 version

**Comment by Wdam** [comment]
> That update node can resolve this problem. They have said that

sure

**Comment by MSameet** [comment]
Hey, I am facing the same issue, but it has not been resolved. I also installed Node 18.17.0.

**Comment by jmongi** [comment]
Hey, i have the same issue.

```
node version : v18.18.2
next version : 13.5.6
pnpm version: 7.33.6
`
``

**Comment by Wdam** [comment]
> Hey, i have the same issue.
> 
> ```
> node version : v18.18.2
> next version : 13.5.6
> pnpm version: 7.33.6
> ```

try the latest node

**Comment by safwen-kyo** [comment]
i have the same issue

**Comment by GoulartNogueira** [comment]
You need to upgrade your node version.

## For Ubuntu:
Use [n module from npm](https://www.npmjs.com/package/n) in order to upgrade node

``` bash
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

[Source](https://askubuntu.com/a/480642)
