### ISSUE TITLE
X-Forwarded-* Headers are overwritten

### ISSUE THREAD

**Issue by mrdrogdrog** [vercel/next.js#57397]
### Link to the code that reproduces this issue

https://github.com/mrdrogdrog/nextjs-x-forwarded-error

### To Reproduce

Hello,

Since one of the last updates nextjs is overwriting the `X-Forwarded-*` headers.
It even behaves differently if i'm using the application port directly or a reverse proxy.

If I open my browser on the application port `http://localhost:3000/` the headers are
```
x-forwarded-host: localhost:3000
x-forwarded-port: 3000
x-forwarded-proto: http
x-forwarded-for: ::1
```
These headers shouldn't be present here because this is a direct connection!

If I open my browser on the reverse proxy port `http://localhost:8081/` it outputs
```
x-forwarded-for: ::1
x-forwarded-host: localhost:8081
x-forwarded-proto: https
x-forwarded-port: 3000
```
Which is wrong because of the wrong x-forwarded-port and x-forwarded-host.

I also checked it using nginx so caddy is not doing anything wrong.

But try it yourself:

1. Run the given example
2. Start a reverse proxy (in my example I use [caddy](https://caddyserver.com/). The caddyfile is included in the repository. Just place the binary in the directory (or install caddy using a package manager) and run `caddy run` in the directory to start it)
3. Check the headers after visiting `http://localhost:8081` and `http://localhost:3001`

### Current vs. Expected behavior

Current: NextJS is overwriting these headers (probably while communicating between the main process and the render worker)
Expected: NextJS shouldn't overwrite these headers because we need it to verify that the user is connecting on the correct endpoint.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6020
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.7-canary.25
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

We use NextJS in https://github.com/hedgedoc/hedgedoc and it seems like we need to downgrade for now until that problem is solved because this is breaking one of our security measurements.

**Comment by phev8** [comment]
This might be related to the issue here: https://github.com/vercel/next.js/issues/54450
Which still happens with 14.0.0. I would really appreciate if there is a fix or a workaround so we can use latest NextJS versions again. (I did not hear or find anything other than stick with 13.4.12 release)

**Comment by Darren120** [comment]
> This might be related to the issue here: #54450 Which still happens with 14.0.0. I would really appreciate if there is a fix or a workaround so we can use latest NextJS versions again. (I did not hear or find anything other than stick with 13.4.12 release)

13.4.13 seems to also work. theres a PR thats addressing this rn  https://github.com/vercel/next.js/pull/57529
