### ISSUE TITLE
Docs: opengraph/twitter for catch-all routes

### ISSUE THREAD

**Issue by wscourge** [vercel/next.js#57403]
### What is the improvement or update you wish to see?

Due to the following error reported by [48162](https://github.com/vercel/next.js/issues/48162):

> Error: Catch-all must be the last part of the URL when using opengraph-image.tsx inside a catch-all route

[there's an inaccurate info](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image#params-optional):

<img width="1188" alt="image" src="https://github.com/vercel/next.js/assets/16985871/03a24352-bad5-44dd-afa9-c3ad4dc4e1f5">

### Is there any context that might help us understand?

I'd like the docs to present an example how to add `opengraph-image` and `twitter-image` properly to the `[...slug]` routes. 

@huozhi's [upvoted comment hacking it](https://github.com/vercel/next.js/issues/48162#issuecomment-1540040105) does not account for the incoming `{ params: { slug }` that is going to be needed in most cases.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image#params-optional

**Comment by leerob** [comment]
Closing this out as the incorrect line has already been removed from the docs. Sorry again about that 🙏 

https://github.com/vercel/next.js/pull/66355
