### ISSUE TITLE
Unable to get all dynamic route params in `layout.tsx`

### ISSUE THREAD

**Issue by Zyr0nX** [vercel/next.js#57429]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/7jqtls

### To Reproduce

1. Start the development server (next dev)
2. Navigate to /products/1/2

### Current vs. Expected behavior

Current:
```
ProductsLayout: {}
ProductIdLayout: {"productId":"1"}
ProductsLayout: {"productId":"1","variantId":"2"}
```

Expected:
```
ProductsLayout: {"productId":"1","variantId":"2"}
ProductIdLayout: {"productId":"1","variantId":"2"}
VariantIdLayout: {"productId":"1","variantId":"2"}
Variant page
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.7-canary.25
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

It works fine in `page.tsx`, only `layout.tsx` is affected

**Comment by magicspon** [comment]
> Layouts do not have access to the route segments below itself. To access all route segments, you can use [useSelectedLayoutSegment](https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segment) or [useSelectedLayoutSegments](https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segments) in a Client Component.

https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts

**Comment by timneutkens** [comment]
The reason layouts can't access all parameters is that partial rendering of layouts: https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#3-partial-rendering
