### ISSUE TITLE
Revalidate is not working

### ISSUE THREAD

**Issue by andrewdowis** [vercel/next.js#57451]
### Link to the code that reproduces this issue

https://github.com/andrewdowis/next-bug

### To Reproduce

1. Start the app in dev mode (`npm run dev`)
2. From menu, click `Revalidate`
3. From menu, click `No Store`
4. Wait 20 seconds, click `Revalidate`

### Current vs. Expected behavior

**Expected Behavior:** When revisiting the route, if 20+ seconds have passed, the timestamp on the `Revalidate` section will have updated

**Actual Behavior:** When revisiting the route, if 20+ seconds have passed, the timestamp on the `Revalidate` remains the same as it once on initial load until the browser itself is refreshed

The data on the JSON doesn't actually change ever, I'm not sure if that is a requirement - IE the fetch will only produce a re-render if the resulting data is different in any way.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
    Mac Sonoma 14.0
Browser:
    Chrome - Version 118.0.5993.96 (Official Build) (x86_64)
    Firefox - 118.0.2 (64-bit)
Binaries:
    Node: 16.19.0
    NPM:  8.19.3
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Additional context

I tested with `13.5.7-canary.27` and on node 18.17.0 as well. It did not work - the behavior was different than described above.

**Expected Behavior:** When revisiting the route, if 20+ seconds have passed, the timestamp on the `Revalidate` section will have updated

**Actual Behavior:** When revisiting the route, if 20+ seconds have passed, the timestamp on the `Revalidate`, the timestamp on the `Revalidate` will appear updated (yay!), but then would update every time I revisited the page following then regardless of if 20 seconds had passed or not. It only waited the 20 seconds to refresh the first time.

**Comment by ztanner** [comment]
Hi, as described in the caching docs ([link](https://nextjs.org/docs/app/building-your-application/caching#invalidation-1)), there are a couple of ways to invalidate the client side cache, but `revalidate` on a fetch request is not one of them. Specifying a revalidate period of 20 seconds on the fetch means that the server will return a cached version of that request for 20 seconds (so if you refreshed the page during that 20 second window, it will show the same data). But to immediately invalidate the client-side cache (which is used when navigating around the app), you'd need to use `revalidatePath`, `revalidateTag` in a server action ([docs ref](https://nextjs.org/docs/app/building-your-application/caching#data-cache-and-client-side-router-cache)) or `router.refresh()`.

We also have a deep-dive into how Next.js caching works located [here](https://github.com/vercel/next.js/discussions/54075).
