### ISSUE TITLE
Next 13: Pages catch all route triggers on api route call when opened in browser

### ISSUE THREAD

**Issue by zfeher** [vercel/next.js#57489]
### Link to the code that reproduces this issue

https://github.com/zfeher/next-bug-catch-all-intercepts-api

### To Reproduce

1. Start the application in development mode (or in production)
2. Open [api/hello](http://localhost:3000/api/hello) url in browser
3. Check server logs where you should find that pages catch all page and MyApp codes were run. Reloading the page in development will log these again and again.

Removing the catch all route page it works as expected (MyApp code is not run).

### Current vs. Expected behavior

Currently opening an api route triggers pages catch all page (and MyApp too). 

The expectation is that opening an api route in the browser doesn't trigger any page rendering because `api` is special and used to define api routes and not pages. 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 18.16.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

Tested this with 13.4.7, 13.5.6 and 13.5.7-canary.34.
App rotuer might have the same bug which I did not test.

Interestingly using a `pages/[slug1]/[...slugRest].tsx` works as a workaround so it seems only catch all route is affected.

**Comment by timneutkens** [comment]
Browsers will request the `favicon.ico` path when you open any url, which is matched in your catch all route, so this is not a bug. You can add `public/favicon.ico` or when using App Router you can add `app/favicon.ico`.

**Comment by zfeher** [comment]
Thank you for looking into it. Adding a `favicon.ico` worked in this case. 

The original project where we noticed this has a `public/icons/favicon.png` which is referenced in custom `_app.tsx`. Then that is the reason (plus catch all) why we run into this and took a while to figure out why it wants to render a page.
