### ISSUE TITLE
App router Increase body size limit Api routes

### ISSUE THREAD

**Issue by Biratus** [vercel/next.js#57501]
### Link to the code that reproduces this issue

https://codesandbox.io/s/next-with-api-forked-6cs9k8?file=/pages/api/test.js

### To Reproduce

I am reopening the issue [https://github.com/vercel/next.js/issues/52457](https://github.com/vercel/next.js/issues/52457) because the final comment : [https://github.com/vercel/next.js/issues/52457#issuecomment-1646086157](https://github.com/vercel/next.js/issues/52457#issuecomment-1646086157) was not answered.

Use the link [https://codesandbox.io/s/next-with-api-forked-6cs9k8?file=/pages/api/test.js](https://codesandbox.io/s/next-with-api-forked-6cs9k8?file=/pages/api/test.js) to reproduce

### Current vs. Expected behavior

In the pages router we can modify the body size limit with:
```
export const config = {
  api: {
    bodyParser: {
      sizeLimit: "5mb",
    },
  },
};
```
However there is no equivalent in the App Router. **It does work in development mode but fails during the build**

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #97~20.04.1-Ubuntu SMP Thu Oct 5 08:25:28 UTC 2023
Binaries:
  Node: 16.16.0
  npm: 8.11.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.4.7
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

To increase the body limit, do we need to define the api route the old way on the page router (so we can use ```export config```) or is there an alternative in the app router ?

**Comment by aryobenholzner** [comment]
Can please someone from the Next.js team answer this.
With pages API route it is possible, with server actions we can do it. There is nothing documented for app routers route handlers. Is there anything undocumented or do we need to fallback to pages or server actions?

**Comment by shuding** [comment]
You can use the `experimental.serverActions.bodySizeLimit` option:

https://nextjs.org/docs/app/api-reference/functions/server-actions#size-limitation

**Comment by TryingToImprove** [comment]
I have a problem like this for server actions.. @shuding 

Configured like this

```
/** @type {import('next').NextConfig} */
const nextConfig = {
    experimental: {
        serverActions: {
            bodySizeLimit: '500mb'
        }
    },
}

module.exports = nextConfig
```

and sending a large hidden input field caps the string at `1040434` chars however I can see that there is much more data in the payload but 

```
 async function create(formData: FormData) {
    "use server";
    console.log(formData.get("document")?.toString().length);
```

don't get it all..
