### ISSUE TITLE
@next/third-parties version 14 only lists Next 13 as peer dependency

### ISSUE THREAD

**Issue by philwolstenholme** [vercel/next.js#57516]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/flamboyant-cache-zm8gv4?file=%2Fpackage.json%3A15%2C29

### To Reproduce

1. Add `@next/third-parties` to a Next 13 project
2. Try to update to Next 14

### Current vs. Expected behavior

Expected: Can install Next 14 while using `@next/third-parties`

Current:

```
Error: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: shop-next@0.1.1
npm ERR! Found: next@14.0.0
npm ERR! node_modules/next
npm ERR!   next@"^14.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^13.0.0" from @next/third-parties@14.0.0
npm ERR! node_modules/@next/third-parties
npm ERR!   @next/third-parties@"^14.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/wolsph/.npm/_logs/2023-10-26T17_27_38_736Z-eresolve-report.txt
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.0
  npm: 10.2.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Package manager (npm, pnpm, Yarn)

### Additional context

https://github.com/vercel/next.js/pull/57515

**Comment by philwolstenholme** [comment]
https://github.com/vercel/next.js/pull/57515

**Comment by ArianHamdi** [comment]
> #57515

I would like to use this @next/third-parties without upgrading to next v14 so what happen in this case ?

**Comment by philwolstenholme** [comment]
> > #57515
> 
> I would like to use this @next/third-parties without upgrading to next v14 so what happen in this case ?

You could remain on `@next/third-parties` version `13.5.6` (or earlier), which would predate the changes made in this PR: https://github.com/vercel/next.js/blob/v13.5.6/packages/third-parties/package.json

**Comment by ArianHamdi** [comment]
> > > #57515
> > 
> > 
> > I would like to use this @next/third-parties without upgrading to next v14 so what happen in this case ?
> 
> You could remain on `@next/third-parties` version `13.5.6` (or earlier), which would predate the changes made in this PR: https://github.com/vercel/next.js/blob/v13.5.6/packages/third-parties/package.json .
> 
> We _could_ do this in the `peerDependencies`:
> 
> `"next": "^13.0.0 | ^14.0.0",`
> 
> But I'm not sure if it's worth it, if you want to stay on Next 13 you could just not update `@next/third-parties` to version 14.

I think `@next/third-parties` doesn't rely on any specefic feature in v14.
In the future they may add more components to this package so It would be good to use them in version < 14 too as it is not part of the next package.

so in this case I prefer `"next": "^13.0.0 | ^14.0.0"`

**Comment by philwolstenholme** [comment]
Good point – PR updated :) 

```
-    "next": "^13.0.0",
+    "next": "^13.0.0 || ^14.0.0",
```

**Comment by philwolstenholme** [comment]
Closed by https://github.com/vercel/next.js/pull/57515
