### ISSUE TITLE
Warning: Extra attributes from the server: data-redeviation-bs-uid

### ISSUE THREAD

**Issue by wolfDown** [vercel/next.js#57525]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
"dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.0.0"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10",
    "postcss": "^8",
    "tailwindcss": "^3",
    "eslint": "^8",
    "eslint-config-next": "14.0.0"
  }

nodejs version：20.9.0
npm version: 10.1.0
```

### Which example does this report relate to?

no

### What browser are you using? (if relevant)

chrome 118.0.5993.89

### How are you deploying your application? (if relevant)

Local

### Describe the Bug

When a newly created project is run, this warning occurs: Warning: Extra attributes from the server: data-redeviation-bs-uid Why

### Expected Behavior

no Warning

### To Reproduce

new project

**Comment by leerob** [comment]
Hey there. This might be from a Chrome extension. It's hard to tell without a reproduction.
