### ISSUE TITLE
Incorrect usage of `request.cookies.delete` in with-supabase example

### ISSUE THREAD

**Issue by asibilia** [vercel/next.js#57524]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 1.22.18
  pnpm: 8.1.0
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-supabase

### Describe the Bug

Typescript complains about the following code: https://github.com/vercel/next.js/blob/b9dd6c4ff6b025453504c6a5669094260c23ca1b/examples/with-supabase/middleware.ts#L41-L45

> Argument of type '{ domain?: string | undefined; encode?: ((value: string) => string) | undefined; expires?: Date | undefined; httpOnly?: boolean | undefined; maxAge?: number | undefined; path?: string | undefined; priority?: "low" | ... 2 more ... | undefined; sameSite?: boolean | ... 3 more ... | undefined; secure?: boolean | undef...' is not assignable to parameter of type 'string | string[]'.

> Object literal may only specify known properties, and 'name' does not exist in type 'string[]'

I was able to fix this type issue by updating to:
```ts
request.cookies.delete(name)
```

### Expected Behavior

There should not be a type error here.

### To Reproduce

run `npx create-next-app -e with-supabase`, run `next build`. Build command should fail on type checks.

**Comment by leerob** [comment]
https://github.com/vercel/next.js/pull/57562
