### ISSUE TITLE
Bun install is broken on v14.0.0

### ISSUE THREAD

**Issue by chuckstock** [vercel/next.js#57540]
### Link to the code that reproduces this issue

https://github.com/chuckstock/nextjs-bun-install-bug

### To Reproduce

1. create a fresh nextjs app with 14
2. Run bun install
3. Run next dev

Error:
```
/Users/charlieblackstock/repos/bun-latest/node_modules/next/dist/server/web/spec-extension/request.js:28
class NextRequest extends Request {
                          ^

ReferenceError: Request is not defined
    at Object.<anonymous> (/Users/charlieblackstock/repos/bun-latest/node_modules/next/dist/server/web/spec-extension/request.js:28:27)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at Module.mod.require (/Users/charlieblackstock/repos/bun-latest/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/charlieblackstock/repos/bun-latest/node_modules/next/dist/server/web/spec-extension/adapters/next-request.js:37:18)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    ```

### Current vs. Expected behavior

Dev doesn't run, it should run.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating system: MacOS
Bun version: 1.0.7
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by JoaquinBattilana** [comment]
I'm having the same problem with `pnpm`

**Comment by JoaquinBattilana** [comment]
In my case it was resolved by bumping the node version (i was using 16 and bumped to 20), seems like the minimum version was bumped in version 14 ( node `18.17` is the minimum)
https://nextjs.org/docs/pages/building-your-application/upgrading/version-14

**Comment by cosmictoby** [comment]
v16 support was dropped this release as per #56896 

> Bumped to 18.18.2 since it contained some security-related patches: https://nodejs.org/en/blog/vulnerability/october-2023-security-releases

**Comment by JesseKoldewijn** [comment]
As @JoaquinBattilana mentioned, the minimal Node.js version was bumped to node 18.17. So this would mean that this kind of behavior might be expected.

**Comment by jilherme** [comment]
![image](https://github.com/vercel/next.js/assets/74925460/b4a5fc23-a130-4796-b935-9bfa70d2f59c)

just need to upgrade node version to 18 or higher

**Comment by chuckstock** [comment]
> As @JoaquinBattilana mentioned, the minimal Node.js version was bumped to node 18.17. So this would mean that this kind of behavior might be expected.

Awesome this worked, thank you!

**Comment by agurumurthy96** [comment]
I followed the tutorial mentioned on the website - but as soon as I type npm run dev, I get the same error mentioned in this thread. I am using node version 18.17 which is the required version as per the Document. Can someone please help?
<img width="1156" alt="Screenshot 2023-10-28 at 3 08 25 AM" src="https://github.com/vercel/next.js/assets/83722798/713f2d65-d3a0-458f-b8b5-ae5f6945eccb">

**Comment by jilherme** [comment]
> I followed the tutorial mentioned on the website - but as soon as I type npm run dev, I get the same error mentioned in this thread. I am using node version 18.17 which is the required version as per the Document. Can someone please help? <img alt="Screenshot 2023-10-28 at 3 08 25 AM" width="1156" src="https://user-images.githubusercontent.com/83722798/278765542-713f2d65-d3a0-458f-b8b5-ae5f6945eccb.png">

there must be something wrong with the node version.

 I tried again but my system default version was running v16 and it gave the same error, so I changed to 18 and it worked. If you can provide a repo (if it's public) I can test to see if the problem is in your project, but prob not.

**Comment by agurumurthy96** [comment]
I have only used npx create-next-app@latest and then npm run dev, after which I received the error. Zero customization done, so not sure how sharing the repository would help in this case. FYI, I also modified the node version to 20 and tried running, but got the same error

**Comment by agurumurthy96** [comment]
> I have only used npx create-[next-app](https://linear.app/vercel/issue/NEXT-app)@latest and then npm run dev, after which I received the error. Zero customization done, so not sure how sharing the repository would help in this case. FYI, I also modified the node version to 20 and tried running, but got the same error

<img width="1147" alt="Screenshot 2023-10-28 at 3 49 10 AM" src="https://github.com/vercel/next.js/assets/83722798/45e5cc83-7967-46be-b45c-17cbb1d3bf95">

**Comment by JesseKoldewijn** [comment]
> I followed the tutorial mentioned on the website - but as soon as I type npm run dev, I get the same error mentioned in this thread. I am using node version 18.17 which is the required version as per the Document. Can someone please help?
> 
> <img width="1156" alt="Screenshot 2023-10-28 at 3 08 25 AM" src="https://github.com/vercel/next.js/assets/83722798/713f2d65-d3a0-458f-b8b5-ae5f6945eccb">
> 
> 

Unrelated since issue is specifically about the bun package manager w/ outdated/incompatible node version. 

But to solve your issue. Check the node version you're using and if you still get errors maybe remove the older versions of node from your system.
