### ISSUE TITLE
revalidate isn't working with next@13.5.6

### ISSUE THREAD

**Issue by abhie-sheik** [vercel/next.js#57575]
### Link to the code that reproduces this issue

https://github.com/abhie-sheik/nextjs-learning

### To Reproduce

1. Clone the repo
2. run ``` yarn ```
3. Create a prod build ``` yarn run build ```
4. Start the prod build ``` yarn run start ```

### Current vs. Expected behavior

Current behavior: As of now I've exported revalidate from ```app/page.tsx``` just to verify if that's working or not. Move the ```/new.md``` to ```blogposts``` directory, then refresh the page that should trigger the revalidation observe even after 10 seconds or  even after some more time the new post isn't displayed.
Expected behavior: As soon as a new blog is added in ```blogposts``` directory and the application is refreshed triggering the new builds the new post should be displayed after 10 seconds.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_ARM64_T8101 arm64
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.5.6
  react: ^18
  react-dom: ^18
  typescript: ^5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

### Additional context

I tested this code with ```next@13.5.6``` but it doesn't seem to work, however I tried downgrading the version to ```13.2.4``` and luckily that worked.

Apart from that just before raising the issue I tried this code with ```^14.0.1-canary.0``` and it still doesn't seem to work I guess this issue isn't addressed yet.

**Comment by ijjk** [comment]
Hi, this has been fixed in the latest canary of Next.js `v14.0.2-canary.22`, please update and give it a try!
