### ISSUE TITLE
The turbo package in nextjs 14 has a bug: EPERM: operation not permitted

### ISSUE THREAD

**Issue by peymanath** [vercel/next.js#57581]
### Link to the code that reproduces this issue

https://github.com/peymanath/terxine/tree/nextjs14-turbo

### To Reproduce

Hello everyone,
i'm using Turbo in the developer environment nextjs14, but I'm getting the following error.
Has anyone encountered this error?

Note: When I get this error that NEXTjs wants to render my routes.

```bash


   ▲ Next.js 14.0.0 (turbo)
   - Local:        http://localhost:3000

 ✓ Ready in 1161ms
 ○ Compiling /branchs/page ...
 ✓ Compiled /branchs/page in 3.9s
 ○ Compiling /_error ...
 ✓ Compiled /_error in 766ms
 ⨯ [Error: EPERM: operation not permitted, rename 'D:\Work\Development\Project\FrontEnd\Terxine\terxine\.next\build-manifest.json.tmp.jazqmzy5ees' -> 'D:\Work\Development\Project\FrontEnd\Terxine\terxine\.next\build-manifest.json'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'D:\\Work\\Development\\Project\\FrontEnd\\Terxine\\terxine\\.next\\build-manifest.json.tmp.jazqmzy5ees',
  dest: 'D:\\Work\\Development\\Project\\FrontEnd\\Terxine\\terxine\\.next\\build-manifest.json'
}
```

### Current vs. Expected behavior

When I use Turbo, this problem occurs and the fonts of my site do not load and the application does not work properly and it also gives this error, but without Turbopack there is no problem, the application works properly.

![image](https://github.com/vercel/next.js/assets/108142218/29619730-353f-4d56-8a6a-ee79de3ca7d5)

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.18.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.9.2
Relevant Packages:
  next: 14.0.1-canary.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Additional context

I am using version 13.5, today I wanted to change to 14 and use turbopack and I had this problem. I tested it when I use create-next-app, it works fine, but there is a problem with my project.

<sub>[PACK-1956](https://linear.app/vercel/issue/PACK-1956/the-turbo-package-in-nextjs-14-has-a-bug-eperm-operation-not-permitted)</sub>

**Comment by IhsenBouallegue** [comment]
same issue. Tried deleting the .next folder but didn't work. Sadly couldn't create a reproduction repo as I have a lot of code.

**Comment by iojcde** [comment]
```
 ⨯ [Error: EPERM: operation not permitted, rename 'C:\Users\jcde0\dksh-website\.next\app-build-manifest.json.tmp.0jdcitichqov' -> 'C:\Users\jcde0\dksh-website\.next\app-build-manifest.json'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\jcde0\\dksh-website\\.next\\app-build-manifest.json.tmp.0jdcitichqov',
  dest: 'C:\\Users\\jcde0\\dksh-website\\.next\\app-build-manifest.json'
}
 ⨯ [Error: EPERM: operation not permitted, rename 'C:\Users\jcde0\dksh-website\.next\server\middleware-build-manifest.js.tmp.oa55ccccoz' -> 'C:\Users\jcde0\dksh-website\.next\server\middleware-build-manifest.js'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'C:\\Users\\jcde0\\dksh-website\\.next\\server\\middleware-build-manifest.js.tmp.oa55ccccoz',
  dest: 'C:\\Users\\jcde0\\dksh-website\\.next\\server\\middleware-build-manifest.js'
}
```

**Comment by Tajmirul** [comment]
Same issue here. for now i just removed `--turbo`.

**Comment by tbenci** [comment]
Adding --turbo is the main reason we've upgraded. NextJS is a slow old pig and need speeding up. If --turbo is not working why bother.

**Comment by enricoros** [comment]
Same here. JetBrains IDE - how about you guys?

**Comment by zamry09** [comment]
Pada Jum, 10 Nov 2023, 2:49 PTG Enrico Ros ***@***.***>
menulis:

**Comment by ForsakenHarmony** [comment]
Is anyone running into this on an OS other than windows?

**Comment by peymanath** [comment]
> Doing some research, this is a problem with windows specifically.
> 
> See: [libuv/libuv#1981](https://github.com/libuv/libuv/pull/1981)
> 
> Antivirus might be locking the file preventing it from being renamed
> 
> So this isn't really a next.js bug, but we can add a retry to work around broken windows behaviour

I will check again
