### ISSUE TITLE
Docs: Sitemaps

### ISSUE THREAD

**Issue by pnodet** [vercel/next.js#57591]
### What is the improvement or update you wish to see?

The sitemap.ts file is documented [here](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap).

I think the documentation should also cover one of the great features, being able to fetch content and have a dynamic sitemap.

Without an example it might be confusing for readers if returning a promise as the same behavior.

### Is there any context that might help us understand?

```ts
import type {MetadataRoute} from 'next';
import glob from 'fast-glob';

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
	const filesPaths = await glob('**/page.mdx', {cwd: 'src/app/blog'});
	return [
		{
			url: 'https://acme.com',
			lastModified: new Date(),
			changeFrequency: 'yearly',
			priority: 1,
		},
		
		...filesPaths.map(filename => ({
			url: `https://acme.com/blog/${filename.replace(
				/\/page\.mdx$/,
				'',
			)}`,
			lastModified: new Date(),
			changeFrequency: 'weekly' as const,
			priority: 0.5,
		})),
	]
}
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

**Comment by leerob** [comment]
We can try to improve this in the future, thank you!
