### ISSUE TITLE
Docs: Incorrect heading structure for Next.js 14 codemods

### ISSUE THREAD

**Issue by mohab-sameh** [vercel/next.js#57593]
### What is the improvement or update you wish to see?

Fix the incorrect heading structure for both, `next-og-import` and `metadata-to-viewport-export` codemods.

### Is there any context that might help us understand?

Codemod names should be H5 instead of H4.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/upgrading/codemods#next-og-import

**Comment by its-kunal** [comment]
I want to fix this issue.

**Comment by mohab-sameh** [comment]
> I want to fix this issue.

@its-kunal Please check #57595 awaiting to be merged. No need for duplicate PRs.
