### ISSUE TITLE
Requests are not automatically deduped (Request Memoization)

### ISSUE THREAD

**Issue by yarikpetrenko** [vercel/next.js#57619]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/gallant-tree-4yxvwz

### To Reproduce

1. Start the dev server
2. Refresh page
3. You see 2 messages "hit" in the console (when you should see only one)

### Current vs. Expected behavior

1. Start the dev server
2. Refresh page
3. Only one message "hit" is displayed

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.0
  eslint-config-next: 13.4.13
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Additional context

After updating my project to next.js version 13.5.5 I started seeing that my Node.js (express )server returns a lot of 429 responses as I set rate limiting for all routes. After further investigation I discovered that starting from 13.5.5 fetch requests does not get deduped even when documentation says it should.

> Passing data between a parent layout and its children is not possible. However, you can fetch the same data in a route more than once, and React will [automatically dedupe the requests](https://nextjs.org/docs/app/building-your-application/caching#request-memoization) without affecting performance.

And this issue preserved on all versions above. Interesting thing is that when my local project on Next version 13.5.4 works fine and request get deduped, when I installed 13.5.4 on the codesandbox it didn't change anything.

On my opinion this is one of the most important features for app router so it's strange it doesn't work, and I'm worried that even it works fine with 13.5.4 on my local server it may not work on the production as it doesn't work with codesandbox.

**Comment by OlegLustenko** [comment]
Unfortunately this is a know issue, attaching as duplicate 

#52156

**Comment by yarikpetrenko** [comment]
Closed as duplicate in favour of https://github.com/vercel/next.js/issues/52126
