### ISSUE TITLE
`optimizePackageImports` no longer functional in v14

### ISSUE THREAD

**Issue by mwskwong** [vercel/next.js#57624]
### Link to the code that reproduces this issue

https://github.com/mwskwong/optimize-package-imports-bug

### To Reproduce

1. Create a Next.js project
2. Import any MUI component (`Button` in the example) using named import to `page.tsx`
3. Observe the bundle size

### Current vs. Expected behavior

**Current**
The entire `@mui/material` is included in the client bundle, despite this package is by default included in `optimizePackageImports`.

**Expect**
Only `Button` and its dependencies are included in the client bundle.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.3
  eslint-config-next: 14.0.1-canary.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Downgrade to Next.js 13.5 to observe the expected behavior.

<sub>[NEXT-1713](https://linear.app/vercel/issue/NEXT-1713/optimizepackageimports-no-longer-functional-in-v14)</sub>

**Comment by r34son** [comment]
Can confirm same issue with `@nextui-org/react`

**Comment by mwskwong** [comment]
Bump

**Comment by shuding** [comment]
We do have a test case for `optimizePackageImports` and `lucide-react` (but obviously we can't test all libs). I'll make sure to take a look at this one!
