### ISSUE TITLE
Open graph properties are not inherited in children routes metadata

### ISSUE THREAD

**Issue by Arctomachine** [vercel/next.js#57633]
### Link to the code that reproduces this issue

https://github.com/Arctomachine/next-metadata-open-graph-bug

### To Reproduce

1. Start server, open dev tools
2. Expand head tag
3. Remember og-related properties
4. Go to about page
5. Look at og-related properties for this page. They all are replaced by single title property. Link to image is also removed.
6. Look at twitter-specific properties. They are mostly the same, but link to image and image sizes are removed too.

![image](https://github.com/vercel/next.js/assets/29041820/5259e7e9-ecb2-4010-bd8f-270e6a251e06)
_Home page has all properties_

![image](https://github.com/vercel/next.js/assets/29041820/e9a64db2-ad31-48bd-a581-3f4d2dc85466)
_What remains on about page_

### Current vs. Expected behavior

Expected all open graph properties to be carried over from root layout metadata and only title to be updated. Instead all open graph properties are replaced by single title, links to image are removed (from twitter too)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
  Platform: win32        
  Arch: x64              
  Version: Windows 10 Pro
Binaries:                
  Node: 20.2.0           
  npm: N/A               
  Yarn: N/A              
  pnpm: N/A              
Relevant Packages:
  next: 14.0.1-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

**Comment by timneutkens** [comment]
The parent metadata can be accessed and passed along when extending it in a child, you can see that documented here: https://nextjs.org/docs/app/api-reference/functions/generate-metadata

The second parameter of `generateMetadata` is the parent data.
