### ISSUE TITLE
Local variable named `module` in an ESM node_module breaks build

### ISSUE THREAD

**Issue by devongovett** [vercel/next.js#57649]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/nextjs-module-repro-257rt8?file=%2Fpackages%2Ftest%2Ftest.mjs%3A5%2C1

### To Reproduce

Run `next build` in the above sandbox.

### Current vs. Expected behavior

Build fails. It should succeed.

```
Failed to compile.

./packages/test/index.mjs
export 'foo' (reexported as 'foo') was not found in './test.mjs' (module has no exports)

Import trace for requested module:
./packages/test/index.mjs
./app/page.js


> Build failed because of webpack errors
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.7.6
Relevant Packages:
  next: 14.0.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

As shown in the codesandbox, the problem is due to a file in node_modules that has a function that assigns to a local variable called `module`, with a property called `exports`.

```js
function test() {
  var module = { exports: {} };
  return module.exports;
}

export const foo = 2;
```

This seems to cause Next.js to think the file has no exports anymore. If you rename `module` to anything else it works fine. My guess is faulty CommonJS detection. That should only apply to the global `module`, not when a local variable that happens to be named `module` is defined. If this is found in node_modules, it is hard to workaround. This pattern is often found in CommonJS libraries that were published with an ESM wrapper.

**Comment by huozhi** [comment]
Should be fixed by #58967 already, upgrading to canary will work. Same as #57962
