### ISSUE TITLE
Server Actions Inside Slots Do not work as expected

### ISSUE THREAD

**Issue by joelrozen** [vercel/next.js#57665]
### Link to the code that reproduces this issue

https://github.com/joelrozen/nextgram

### To Reproduce

1. Install dependencies and start application (`npm i && npm run dev`)
2. Click a photo so it opens in the Modal
3. Click "Redirect Me" Button
4. Observe in server console "action triggered" gets logged, however the page never redirects back to '/'. Inspecting the form element of the modal also reveals that the form action is `javascript:throw new Error('A React form was unexpectedly submitted...` and none of the hidden nextjs form inputs are injected.
5. Hard refresh the photo route so that the image loads in the page instead of the Modal slot.
6. Observe HTML of form looks correct, click the "Redirect Me" button
7. Observer "action triggered" gets logged to server console and 1 second later, the page is redirected back to "/"

### Current vs. Expected behavior

Expect server actions inside forms to work consistently no matter where they're rendered (page, slots, intercepted/parallel routes etc).

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Binaries:
  Node: 18.18.1
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 7.13.4
Relevant Packages:
  next: 14.0.1-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

same behaviour observed when using useFormState

<sub>[NEXT-1812](https://linear.app/vercel/issue/NEXT-1812/server-actions-inside-slots-do-not-work-as-expected)</sub>

**Comment by chungweileong94** [comment]
Not sure if I am getting the same issue as this one. But I noticed that calling the `redirect` in server action will result in 404 page for some reason, in my case it's just a page with action without the intercept route.

I will create a simple repo once I able to do so.
