### ISSUE TITLE
Not-found missing pathname context when using force-static

### ISSUE THREAD

**Issue by Frumba** [vercel/next.js#57663]
### Link to the code that reproduces this issue

https://codesandbox.io/p/github/Frumba/not-found-reproduction

### To Reproduce

1. Go to the reproduction link
2. Navigate to `/customdomain/langnotfound`
3. Check the not found page with following message `Not found /h9shfw-3000.csb.app/customdomain`
4. Then go to `app/[domain]/[lang]/page.tsx` and uncomment the line 3 to add `force-static`
5. Check that the not found page is now showing `Not found -`

### Current vs. Expected behavior

Current:

I am trying to force static rendering in order to HIT cache on vercel when using dynamic routes. I also need to contextualize my not found page based on the params I get from the pathnames at least.

Today when trying to access headers in not-found, if you use force-static in the page.tsx next to it it's empty. As exepected from the documentation when using force-static headers is empty. I would still need a way to add more context to fill my not-found page wether it's through a param when calling notFound() function from next/navigation or a param in the notFound component.

Expected:

I know that streaming features in the case of app router prevent doing this easily, but does it exist any way of getting info from server on not-found pages when using force-static ?

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 3.6.3
  pnpm: 8.6.12
Relevant Packages:
  next: 14.0.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by cyber-nic** [comment]
Not sure if this is related, but I'm having trouble accessing headers NexJS v14 in _any context_. @Frumba wondering if you might be able to confirm or disprove my findings. Is `headers();` _ever_ returning header values for you?

**Comment by Frumba** [comment]
Is it possible to add the params equivalent to `useParams` in the NotFound props page when being created in a child path like here ?

**Comment by Frumba** [comment]
I solved this issue by transforming the not-found into a client component and getting the params from useParams. I lose the ability to render not found server side but it might not be so bad.
