### ISSUE TITLE
Meta theme-color is missing in the html, while meta viewport value is incorrect

### ISSUE THREAD

**Issue by Senbonzakura1234** [vercel/next.js#57680]
### Link to the code that reproduces this issue

https://github.com/Senbonzakura1234/debug-metadata

### To Reproduce

1/ run `next dev`

### Current vs. Expected behavior

- log show
```powershell
 ⚠ Unsupported metadata themeColor is configured in metadata export. Please move it to viewport export instead.
 ⚠ Unsupported metadata viewport is configured in metadata export. Please move it to viewport export instead.
```
those 2 meta field didn't rendered to the html

- change the code move themeColor and viewport option to viewport export:
```ts
export const viewport: Viewport = {
  themeColor: '#996c254d',
  width: '1024'
}
```

those 2 meta field rendered to the html, but getting `"viewport" is not a valid Next.js entry export value` error message in vscode.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home Single Language
Binaries:
  Node: 18.18.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.1
  eslint-config-next: 14.0.1-canary.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

ESLint (eslint-config-next), Metadata (metadata, generateMetadata, next/head)

**Comment by krychaxp** [comment]
what error message you have in vscode?

**Comment by Senbonzakura1234** [comment]
> what error message you have in vscode?

'"viewport" is not a valid Next.js entry export value

**Comment by wansaleh** [comment]
Me too.

<img width="626" alt="Screenshot 2023-10-29 at 1 09 47 PM" src="https://github.com/vercel/next.js/assets/340530/2cb4b83d-76ef-4bde-a10b-7486b14a2055">

**Comment by mtr1990** [comment]
Same error.

<img width="420" alt="image" src="https://github.com/vercel/next.js/assets/13531993/bb018492-557c-4f92-b502-bb494192ceea">

**Comment by Senbonzakura1234** [comment]
This either `eslint-config-next`'s issue or the generate metadata function's issue. Not sure which one.

**Comment by 0xJohnnie** [comment]
@Senbonzakura1234  Try checking out the codemod guide to transform your NextJS 13 code

https://nextjs.org/docs/app/building-your-application/upgrading/codemods#use-viewport-export

**Comment by Senbonzakura1234** [comment]
> @Senbonzakura1234 Try checking out the Codemods guide to migrate your Next JS 13 code for Next JS 14
> 
> https://nextjs.org/docs/app/building-your-application/upgrading/codemods#use-viewport-export

@0xJohnnie i did, and as i mentioned above, after migrate to the new `viewport` export, i got error message in vscode `"viewport" is not a valid Next.js entry export value`

**Comment by azizoid** [comment]
> @Senbonzakura1234 Try checking out the Codemods guide to migrate your Next JS 13 code for Next JS 14
> 
> https://nextjs.org/docs/app/building-your-application/upgrading/codemods#use-viewport-export

wow that is a smart advice, nobody ever thought about it. What is the point of the useless comments like read the docs. we do, that is why we are here. we follow the migration guides, it fails, we come and write here.

**Comment by azizoid** [comment]
You guys are lucky, in my case it does not even recognize `metadata-to-viewport-export` as codemod script
```
npx @next/codemod@latest metadata-to-viewport-export .
Invalid transform choice, pick one of:
```

**Comment by ThiLourenco** [comment]
Same error 

![image](https://github.com/vercel/next.js/assets/68729858/232772c7-a1c6-4852-9af4-f6d0c50b8acb)

**Comment by Senbonzakura1234** [comment]
> I don't think this issue is already solved.
> 
> As I [mentioned in the pull request](https://github.com/vercel/next.js/pull/57554#issuecomment-1785818057), the issue still exists in the canary version that includes the fix.

@davegomez what version does your project install? My is `next@latest` and it's fine now. You also need to update `eslint-config-next` to latest also, have you done it?

**Comment by azizoid** [comment]
@Senbonzakura1234 they fixed it over night with 14.0.1

**Comment by Senbonzakura1234** [comment]
> @Senbonzakura1234 I confirmed is fixed with the latest version.
> 
> Besides, I had a typo 😑.

Yeah :v saw that this morning

**Comment by Cypherball** [comment]
I found a temporary fix. Just export viewport after initalization.

```js
const viewport: Viewport = {
  colorScheme: 'light',
  themeColor: '#ffffff',
  width: 'device-width',
  initialScale: 1,
};

// Exporting this way to avoid NextJs 14 type error
export { viewport };
```

**Comment by IlirEdis** [comment]
I can confirm that i still get it in v14.0.1.
I get it in terminal window only on hot reload and not in full page reload.

<img width="906" alt="Screenshot 2023-11-02 at 21 30 06" src="https://github.com/vercel/next.js/assets/128377763/f35d5cc5-8edc-4a7c-9ab3-7c920129c41b">

**Comment by Senbonzakura1234** [comment]
> I can confirm that i still get it in v14.0.1. I get it in terminal window only on hot reload and not in full page reload.
> 
> <img alt="Screenshot 2023-11-02 at 21 30 06" width="906" src="https://user-images.githubusercontent.com/128377763/280119542-f35d5cc5-8edc-4a7c-9ab3-7c920129c41b.png">

@IlirEdis have you follow this migrate step https://nextjs.org/docs/app/building-your-application/upgrading/codemods#use-viewport-export

**Comment by KennStack01** [comment]
same!

Any update?

**Comment by Senbonzakura1234** [comment]
> same!
> 
> Any update?

@KennStack01 try upgrade to next latest and follow the migration guide here https://nextjs.org/docs/app/building-your-application/upgrading/codemods#use-viewport-export

**Comment by erikjung** [comment]
> "viewport" is not a valid Next.js entry export value

For those experiencing this in VS Code after updating to the latest Next.js version (`14.0.2` in my case), try restarting the TS server:

<img width="617" alt="Screenshot 2023-11-09 at 11 32 55 PM" src="https://github.com/vercel/next.js/assets/61204/caa05bdc-72f7-489a-a241-22960c75bd4e">

**Comment by larryhopecode** [comment]
> > what error message you have in vscode?
> 
> @krychaxp just like i said: `"viewport" is not a valid Next.js entry export value`

Same error her.
