### ISSUE TITLE
useEffect double render breaks browser APIs - Dev Only.

### ISSUE THREAD

**Issue by TheDormouse** [vercel/next.js#57688]
### Link to the code that reproduces this issue

https://github.com/TheDormouse/useeffectbug

### To Reproduce

1. Start the application in development
2. Observe the console on the '/' route - the useEffect is triggered twice, however the state value is only updated once.
3. Observe the console on the '/broadcastapi' route
4. The useEffect cleanup is called on page load, which disconnects the broadcast API in the browser.

### Current vs. Expected behavior

Current behavior: While in dev mode, useEffect is fired twice, and the cleanup function is called immediately on render. 

Expected behavior: useEffect is fired once without invoking the cleanup function

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 19.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
--- 
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tested this as far back as 13.1 with strict mode disabled, and it appears to be an issue there as well. This does not impact the production build, however this makes working with browser APIs in dev mode impossible.

**Comment by chris-trait** [comment]
This sounds like expected React behaviour: https://react.dev/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts

**Comment by TheDormouse** [comment]
> This sounds like expected React behaviour: https://react.dev/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts

With strict mode off as well? Is there any workaround for this?

**Comment by TheDormouse** [comment]
Issue resolved by disabling strict mode.

```js
/** @type {import("next").NextConfig} */
module.exports = {
  reactStrictMode: false,
};
```
