### ISSUE TITLE
Docs: reportWebVitals in app router

### ISSUE THREAD

**Issue by icco** [vercel/next.js#57715]
### What is the improvement or update you wish to see?

https://nextjs.org/docs/app/building-your-application/optimizing/analytics is empty compared to https://nextjs.org/docs/pages/building-your-application/optimizing/analytics and does not tell you how to use reportWebVitals, or if it's even supported in the app structure.

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/optimizing/analytics

**Comment by onukwilip** [comment]
From the image I captured, i think the docs covers the web vitals for the app routing system![image](https://github.com/vercel/next.js/assets/103827570/d95723d8-efe0-4c3d-a577-d93eb5ba229f)

**Comment by icco** [comment]
This doc does not explain how to configure or enable like it does for the
pages routing.
