### ISSUE TITLE
Docs: Typo in "Upgrading: Version 14" page

### ISSUE THREAD

**Issue by AnthonySchneider2000** [vercel/next.js#57725]
### What is the improvement or update you wish to see?

In the ["Upgrading: Version 14"](https://nextjs.org/docs/pages/building-your-application/upgrading/version-14) page, the statement: 
`To update to Next.js version 13`
should be
`To update to Next.js version 14` 

### Is there any context that might help us understand?

file location: [next.js](https://github.com/vercel/next.js/tree/canary)/[docs](https://github.com/vercel/next.js/tree/canary/docs)/[03-pages](https://github.com/vercel/next.js/tree/canary/docs/03-pages)/[01-building-your-application](https://github.com/vercel/next.js/tree/canary/docs/03-pages/01-building-your-application)/[08-upgrading](https://github.com/vercel/next.js/tree/canary/docs/03-pages/01-building-your-application/08-upgrading)
/[03-version-14.mdx](https://github.com/vercel/next.js/blob/canary/docs/03-pages/01-building-your-application/08-upgrading/03-version-14.mdx)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/upgrading/version-14

**Comment by Nayeem-XTREME** [comment]
Solved in https://github.com/vercel/next.js/pull/57723
