### ISSUE TITLE
Docs: [Minor] Layouts and routes diagram shows wrong alignment

### ISSUE THREAD

**Issue by arijitpatra** [vercel/next.js#57726]
### What is the improvement or update you wish to see?

Layouts and routes diagram shows wrong alignment

### Is there any context that might help us understand?

Here is the diagram:
![routes example, all items on the right side should move 1 level down to be correct](https://github.com/vercel/next.js/assets/7112824/6e1aa40e-98c3-4857-9f63-79fbf5bd2102)

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/creating-layouts-and-pages#practice-creating-the-dashboard-pages

**Comment by emapeire** [comment]
Hello @arijitpatra. I think the diagrama is wrong too. Here it's corrected:

<img width="910" alt="Captura de pantalla 2023-10-30 a la(s) 18 06 01" src="https://github.com/vercel/next.js/assets/63935846/fdead918-830b-4cde-a266-198e449631d2">

**Comment by arijitpatra** [comment]
Yes.

You can also put the arrows with the page.tsx files.

And one small correction in your diagram is the spelling of
dashboard/customers. :)

**Comment by leerob** [comment]
Fixed
![image](https://github.com/vercel/next.js/assets/9113740/56fb6cd2-ac7b-4686-a814-17797b475818)

**Comment by arijitpatra** [comment]
whoaaaa! thank you. :)
