### ISSUE TITLE
Using --turbo Flag With npm run dev Seems To Throw "Encountered two children with the same key, `0`" Error

### ISSUE THREAD

**Issue by RockyWearsAHat** [vercel/next.js#57743]
### Link to the code that reproduces this issue

https://github.com/RockyWearsAHat/nextKeysMustBeUniqueWhenUsingTurbo

### To Reproduce

likely have to npm install gsap / remove the GSAP import from FirstGSAPPage (there's no actual code that uses it, just the import, bug is not specific to GSAP as even after removing import gsap bug persists)

then

npm run dev

--turbo already declared in package.json

### Current vs. Expected behavior

Page expected to render without errors.

Page renders with errors that I generally associate with array.map when the objects don't have keys, but only when the --turbo flag is declared inside the the package.json

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.3
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

**Comment by federicocappellotto97** [comment]
Same, only with turbo i got Encountered two children with the same key, 0

**Comment by li-jia-nan** [comment]
+1
