### ISSUE TITLE
Docs: next-url

### ISSUE THREAD

**Issue by cyber-nic** [vercel/next.js#57762]
### What is the improvement or update you wish to see?

NextJS docs would be greatly improved with a detailed list of NextJS specific headers such as 'next-url'. Also, a recommended approach to obtaining the url pathname in server components would be a great addition as the headers() function does not always contain the desired information.

### Is there any context that might help us understand?

The [headers](https://nextjs.org/docs/app/api-reference/functions/headers) documentation would greatly benefit from the list of nextjs specific headers such as "next-url". Searching for 'next-url' in the docs produces no results, yet there are numerous examples online of its use to fetch the pathname in server components.

Furthermore, 'next-url' is unreliable as mentioned [here in stackoverflow](https://stackoverflow.com/questions/75815512/get-request-url-in-nextjs-server-component-inside-the-app-folder#:~:text=As%20far%20as%20I%20know%20is%20not%20possible%20directly%20access%20the%20request%20within%20a%20Server%20Component.). The 'next-url' header is **not** present when navigating directly to a NextJS page (app router) but will eventually show up with HMR (in my experience). The solution suggested in Stackoverflow works perfectly, but this does seem like a band-aid for a possibly misunderstood logic.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/headers

**Comment by leerob** [comment]
`next-url` is not something we recommend reading or using.

- https://github.com/vercel/next.js/issues/43704
- https://nextjs.org/docs/app#how-can-i-access-the-request-object-in-a-layout
