### ISSUE TITLE
Internal Error: do not use legacy react-dom/server APIs

### ISSUE THREAD

**Issue by jmuffat** [vercel/next.js#57771]
### Link to the code that reproduces this issue

https://github.com/jmuffat/nxt14-maplibre

### To Reproduce

- `npm run dev` 
- browse http://localhost:3000

### Current vs. Expected behavior

The page shows a map, with a marker.
That marker's popup needs `renderToString` to show react content

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.3
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

filing this issue since error message says :
`If you encountered this error, please open an issue on the Next.js repo.`

**Comment by jmuffat** [comment]
sorry, fixed it myself, there was a much simpler way than using `renderToString`

**Comment by bernaferrari** [comment]
what was your solution?

**Comment by jmuffat** [comment]
Unfortunately, the solution here isn't general, it is related to my use of MapLibre GL JS.

The solution is in the repro repo mentioned above, in the last commit titled "fix"
https://github.com/jmuffat/nxt14-maplibre/commit/f5867a8d5356f1cd03da6162d1e83b26c1e5ad7d

Basically, I was using `renderToString` to generate html that I then passed via `setHtml` to the popup. 
Instead, I generated a `<div/>` with the content and passed it via `setDOMContent` which is a call I did not notice when I wrote the initial version. The fact it doesn't use `react-dom/server` not only solves the next.js error, it is also much cleaner.

Note the use of an outer hidden `<div/>` to avoid the popup contents to show up inadvertently. In the actual code I am working on, that `<div/>` is in the Map code, like this: `<div className='hidden'>{children}</div>`. so that it doesn't have to be repeated for every marker or other other feature that might be added.

**Comment by sam3d** [comment]
This is the Next.js PR that broke this functionality: https://github.com/vercel/next.js/pull/56082

It was intentionally stripped out for optimisation reasons.

**Comment by sam3d** [comment]
Workaround for Next.js 14. Implements the same behaviour as the original `renderToString` except it avoids all of the warnings (and works on the edge runtime).

```ts
export async function renderToString(
  element: ReactElement<any, string | JSXElementConstructor<any>>,
): Promise<string> {
  const { renderToReadableStream } = await import("react-dom/server");

  const stream = await renderToReadableStream(element);
  const textStream = stream.pipeThrough(new TextDecoderStream());
  const reader = textStream.getReader();

  let result = "";
  while (true) {
    const { value, done } = await reader.read();
    if (done) break;
    result += value;
  }
  return result;
}
```
