### ISSUE TITLE
[Next 14] PPR doesn't work when app is deployed to Vercel

### ISSUE THREAD

**Issue by wlechowicz** [vercel/next.js#57781]
### Link to the code that reproduces this issue

https://github.com/wlechowicz/next14-ppr-vercel

### To Reproduce

1. Build the application locally with `next build`
2. Confirm that index page is built with PPR ![obraz](https://github.com/vercel/next.js/assets/24250766/4a06ba64-fa8b-4654-a62f-3174873dd3bf)
4. Start the application with `next start`
5. Visit app's URL
6. Observe in Network tab that the document connection stays open for ~3s and that the suspended component gets streamed in. 3s is an artificial delay in the async component added for demo purpose.
7. Deploy the app to Vercel
8. Notice that Build step on Vercel still shows PPR on index page 
![obraz](https://github.com/vercel/next.js/assets/24250766/df403354-3f1c-4f2a-90e2-3aba42eceee5)

9. Notice that in Deployment Summary, index is shown in **ISR Functions** section (should be in Functions instead?) 
![obraz](https://github.com/vercel/next.js/assets/24250766/1e0664dc-ca93-4425-abac-70dbf8279a3f)

10. Visit Vercel app URL, notice that PPR does not work, suspended components never get streamed in, the document connection is closed immediately and "Loading..." suspense fallback is shown forever. 
![obraz](https://github.com/vercel/next.js/assets/24250766/214bca8c-b0ee-45ac-9d49-7f849e3f0b02)

### Current vs. Expected behavior

Vercel deployment of the repro app available at https://next14-ppr-vercel.vercel.app/

Notice that the suspended component never goes out of fallback and you see "Loading..." forever.
PPR should work as expected when app is deployed as default Next.js app to Vercel.
Build step on Vercel deployment shows that page is generated with PPR, but the suspended components do not get streamed into place, ever. 

With PPR off, he same page gets built as a lambda and the suspense fallback issue described here does not happen.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
(Irrelevant, issue is on Vercel)

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1-canary.5
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Static HTML Export (output: "export")

**Comment by wlechowicz** [comment]
Might be worth noting that Vercel does not offer Node 20, so the app is running on Node 18 instead.

**Comment by Galanthus** [comment]
Same problem, once deployed `revalidateTag` is not working, and getting many random network errors only when deployed. Node version on Vercel is 19x. While, next 14 requires Node 20. Till then I am sticking to latest 13.5.7 version.

**Comment by msphn** [comment]
@Galanthus nextjs 14 does not require node 20, but node 18 as per docs. Where did you take that from?

**Comment by pawelblaszczyk5** [comment]
Same for me, I've also managed to reproduce it. 
Vercel deployment link: https://ppr-vercel-test.vercel.app
GitHub link: https://github.com/pawelblaszczyk5/ppr-vercel-test

Moreover, it seems like it causes hydration to fail/doesn't happen at all. You can see the button at the bottom of a page not functioning properly. I've also checked the node versions, Next.js requires `>=18.17.0` (per https://github.com/vercel/next.js/blob/7cea497626ac2fe5e130807917faf9e0e6cd9f2e/packages/next/package.json#L320) and it's the exact version used on Vercel when you select `18.x`. Verified by using `process.version` during rendering, you can also see it at the top of the page.

**Comment by wlechowicz** [comment]
You leaked the flag in next.config types 🤷 😄
