### ISSUE TITLE
[NextJS 14] Cannot use experimental.typedRoutes with --turbo

### ISSUE THREAD

**Issue by Audrey-Ann** [vercel/next.js#57790]
### Link to the code that reproduces this issue

[CodeSandBox](https://codesandbox.io/p/sandbox/github/vercel/next.js/tree/canary/examples/reproduction-template-pages?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clodmfzcw00083b6j2jtt352s%2522%252C%2522sizes%2522%253A%255B42.69417475728156%252C57.30582524271844%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clodmfzcv00033b6jqnczxeyl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clodmfzcv00053b6j59xpm8zv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clodmfzcw00073b6jlflpt2ib%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clodmfzcv00033b6jqnczxeyl%2522%253A%257B%2522id%2522%253A%2522clodmfzcv00033b6jqnczxeyl%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clodmg398003n3b6jj6k3hpwi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnext.config.js%2522%252C%2522id%2522%253A%2522clodmgmq700jf3b6jhotdb4bi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clodmg398003n3b6jj6k3hpwi%2522%257D%252C%2522clodmfzcw00073b6jlflpt2ib%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clodmfzcw00063b6jgpc7ge10%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clodmfzcw00073b6jlflpt2ib%2522%252C%2522activeTabId%2522%253A%2522clodmfzcw00063b6jgpc7ge10%2522%257D%252C%2522clodmfzcv00053b6j59xpm8zv%2522%253A%257B%2522id%2522%253A%2522clodmfzcv00053b6j59xpm8zv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clodmhr1h011y3b6jdm78dlc5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clodmhr6z000ldxgcdgrjaj2a%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clodmhr1h011y3b6jdm78dlc5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### To Reproduce

1. in `next.config.js` add `typedRoutes: true` under the experimental object: 
```
   experimental: {
        typedRoutes: true,
    },
```

2. Run `npm run dev --turbo`

### Current vs. Expected behavior

Expected:
- The application should build and run successfully
```
   ▲ Next.js 14.0.0
   - Local:        http://localhost:3000
   - Environments: .env.local
   - Experiments (use at your own risk):
     · turbo
     · typedRoutes

 ✓ Ready in 7.6s
```

Actual: 
- The application build is failing because the `experimental.typedRoutes` is not supported: 

```
 ▲ Next.js 14.0.0 (turbo)
   - Local:        http://localhost:3000
   - Environments: .env.local
   - Experiments (use at your own risk):
     · turbo
     · typedRoutes

 ✓ Ready in 13.7s
 ⨯ You are using configuration and/or tools that are not yet
supported by Next.js with Turbopack:


- Unsupported Next.js configuration option(s) (next.config.js)
  To use Turbopack, remove the following configuration options:
    - experimental.typedRoutes
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Relevant Packages: 
- next 14.0.1
- react 18.3.0-next-fecc288b7-20221025
- react-dom 18.2.0
- typescript 5.2.2

next.config.js

/** @type {import('next').NextConfig} */
const nextConfig = {
    webpack(config) {
        config.module.rules.push({
            test: /\.svg$/i,
            issuer: /\.[jt]sx?$/,
            use: ['@svgr/webpack'],
        })
        return config
    },
    experimental: {
        typedRoutes: true,
        turbo: {
            rules: {
                '*.svg': {
                    loaders: ['@svgr/webpack'],
                    as: '*.js',
                },
            },
        },
    },
};

module.exports = nextConfig;
```

### Which area(s) are affected? (Select all that apply)

App Router, Internationalization (i18n)

### Additional context

The `experimental.typedRoutes` is required since the application uses Typescript and localized routes. The `--turbo` options is such an amazing addition to NextJS 14 since it was a pain to develop locally... However I cannot use it yet and optimize my development experience unfortunately. 

Thanks very much for your guidance and help!

**Comment by maiveasna24** [comment]
Hi, @Audrey-Ann In my opinion the next 14.0.1 supports all of the turbo automatic config. no need to configure in next-config.
it works normally for me

**Comment by KingBael09** [comment]
Currently you can't use `--turbo` with experimental features

**Comment by timneutkens** [comment]
This is not a bug, the message points out that you can't use this particular option with Turbopack yet as it's not implemented yet, we're focusing on stable options first, experimental features will be added later.

**Comment by Audrey-Ann** [comment]
@timneutkens thanks for the response, do we have an idea when the experimental features will be supported or when the typedRoutes won't be an experimental feature anymore?
