### ISSUE TITLE
Stripe Webhook Throws Unhandled Promise Rejection

### ISSUE THREAD

**Issue by vpaul18** [vercel/next.js#57825]
### Link to the code that reproduces this issue

https://github.com/vpaul18/vercel-bug/blob/main/api/stripeWebhook

### To Reproduce

This is the most dumbed-down version of a webhook.

`
export const config = {
  api: {
    bodyParser: false,
  },
};

export default async function handler (request, response){

  // Deny all requests that are not of type "POST"
  if (request.method === "POST") {
    //read the signature ...

    console.log("Received")
    response.status(200).json({ received: true });
  } else {
    response.status(405).end("Method Not Allowed");
  }
};
`

Yet it *ALWAYS* throws this error (only when hosted on Vercel) `
6807d9fc-f4a7-443b-9efc-ea8c980cd554	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: fetch failed","reason":{"errorType":"TypeError","errorMessage":"fetch failed","cause":{"errorType":"ConnectTimeoutError","errorMessage":"Connect Timeout Error","code":"UND_ERR_CONNECT_TIMEOUT","name":"ConnectTimeoutError","message":"Connect Timeout Error","stack":["ConnectTimeoutError: Connect Timeout Error","    at onConnectTimeout (node:internal/deps/undici/undici:8522:28)","    at node:internal/deps/undici/undici:8480:50","    at Immediate._onImmediate (node:internal/deps/undici/undici:8511:13)","    at process.processImmediate (node:internal/timers:476:21)","    at process.callbackTrampoline (node:internal/async_hooks:130:17)"]},"stack":["TypeError: fetch failed","    at Object.fetch (node:internal/deps/undici/undici:11576:11)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: fetch failed","    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    at process.emit (node:events:529:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
[ERROR] [1698772401310] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 400.
Error: Runtime exited with error: exit status 128
Runtime.ExitError`.

### Current vs. Expected behavior

Expected: be able to read webhook.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Home
    Binaries:
      Node: 19.4.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: N/A
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

This issue has also been mentioned here: https://github.com/vercel/next.js/discussions/48885#discussioncomment-7360120.

**Comment by timneutkens** [comment]
This is using the top level `api` directory, which is not Next.js. Please use Vercel discussions for this question: https://github.com/orgs/vercel/discussions
