### ISSUE TITLE
Encountering CSP Errors After Cloning and Running the with-strict-csp Sample

### ISSUE THREAD

**Issue by ShihTingJustin** [vercel/next.js#57865]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.12.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.10.0
Relevant Packages:
  next: 14.0.2-canary.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-strict-csp

### What browser are you using? (if relevant)

Microsoft Edge 118.0.2088.76 

### How are you deploying your application? (if relevant)

No

### Describe the Bug

I followed the [documentation](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy) and cloned the [with-strict-csp](https://github.com/vercel/next.js/tree/canary/examples/with-strict-csp) sample to try out the Content Security Policy (CSP) with Next.js 13. However, upon running the sample, I encountered the following errors:

from localhost/:1
```
Refused to load the script 'https://.../' because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-ZjY2NjkxMTUtODY0NC00ZmFjLWJlZmYtN2M1MzdmZjJjNzM5' 'strict-dynamic'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

from main-app.js?v=1698832174659:1535
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'nonce-ZjY2NjkxMTUtODY0NC00ZmFjLWJlZmYtN2M1MzdmZjJjNzM5' 'strict-dynamic'".

    at (app-pages-browser)/./node_modules/.pnpm/next@14.0.2-canary.3_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@next/react-refresh-utils/dist/runtime.js (main-app.js?v=1698832174659:1535:26)
    at options.factory (webpack.js?v=1698832174659:704:31)
    at __webpack_require__ (webpack.js?v=1698832174659:37:33)
    at __webpack_exec__ (main-app.js?v=1698832174659:1812:61)
    at main-app.js?v=1698832174659:1813:37
    at webpackJsonpCallback (webpack.js?v=1698832174659:1376:39)
    at main-app.js?v=1698832174659:9:61
```

![image](https://github.com/vercel/next.js/assets/56827791/e0167560-94e6-482b-aef4-a5d046e18939)

### Expected Behavior

I expected the sample to run without any CSP-related errors

### To Reproduce

1. Clone the with-strict-csp sample from the [Next.js examples repository](https://github.com/vercel/next.js/tree/canary/examples/with-strict-csp).
1. Run `pnpm i` to install dependencies.
1. Run `pnpm dev` to start the development server.
1. Open the browser and navigate to http://localhost:3000.
1. Observe the aforementioned errors in the console.

**Comment by HIppei** [comment]
@ShihTingJustin 
You have to specify Script source in page.tsx(jsx) that you want to run instead of leaving it as the sample is. Or just return <div/>, then you can see the response header has CSP and Nextjs's scripts have nonce.

**Comment by ShihTingJustin** [comment]
@HIppei
Thanks for replying. I remove `<Script />` and only return `<div>123</div>`, but the `Uncaught EvalError` is still there.


![image](https://github.com/vercel/next.js/assets/56827791/96959a80-093a-43cb-b5d2-3077cad0e736)

**Comment by HIppei** [comment]
@ShihTingJustin 
Sorry for late replying. When you run it in Dev env, you need to add `unsafe-eval` to CSP. If you run `npm build && npm start`, you will not face the problem.

You can refer the `middleware` below. I have rearranged some parts for simplicity.

```
import { NextResponse } from 'next/server';

export function middleware() {
  const nonce = Buffer.from(crypto.randomUUID()).toString('base64');
  const cspHeader = `
    default-src 'self';
    script-src 'self' 'nonce-${nonce}' 'strict-dynamic' ${
    process.env.NODE_ENV === 'development' ? "'unsafe-eval'" : ''
  };
    style-src 'self' 'nonce-${nonce}';
    img-src 'self' blob: data:;
    font-src 'self';
    object-src 'none';
    base-uri 'self';
    form-action 'self';
    frame-ancestors 'none';
    block-all-mixed-content;
    upgrade-insecure-requests;
`;

  const responseHeaders = new Headers();

  // Response headers
  responseHeaders.set(
    'Content-Security-Policy',
    // Replace newline characters and spaces
    cspHeader.replace(/\s{2,}/g, ' ').trim()
  );

  return NextResponse.next({
    headers: responseHeaders,
  });
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    {
      source: '/((?!api|_next/static|_next/image|favicon.ico).*)',
      missing: [
        { type: 'header', key: 'next-router-prefetch' },
        { type: 'header', key: 'purpose', value: 'prefetch' },
      ],
    },
  ],
};

```

**Comment by ShihTingJustin** [comment]
@HIppei 
Thank you for the example and the thorough explanation, it works!
