### ISSUE TITLE
Docs: messages/webpack-build-worker-opt-out is 404

### ISSUE THREAD

**Issue by MonstraG** [vercel/next.js#57876]
### What is the improvement or update you wish to see?

When building my project I see
```
⚠ Custom webpack configuration is detected. When using a custom webpack configuration, the Webpack build worker is disabled by default. To force enable it, set the "experimental.webpackBuildWorker" option to "true". Read more: https://nextjs.org/docs/messages/webpack-build-worker-opt-out
```

Following the link I see 404.

### Is there any context that might help us understand?

not really

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/webpack-build-worker-opt-out

**Comment by alex-kinokon** [comment]
For anyone stumbling on this error, here’s the deleted doc:

> ### Webpack Build Worker Opt-out
> #### Why This Error Occurred
> The Next.js config contains custom webpack configuration, as a result, the webpack build worker optimization was disabled.
>
> The webpack build worker optimization helps alleviate memory stress during builds and reduce out-of-memory errors although some custom configurations may not be compatible.
>
> #### Possible Ways to Fix It
> You can force enable the option by setting `config.experimental.webpackBuildWorker: true` in the config.

**Comment by alex-kinokon** [comment]
For anyone stumbling on this error, here’s the deleted doc:

> ### Webpack Build Worker Opt-out
> #### Why This Error Occurred
> The Next.js config contains custom webpack configuration, as a result, the webpack build worker optimization was disabled.
>
> The webpack build worker optimization helps alleviate memory stress during builds and reduce out-of-memory errors although some custom configurations may not be compatible.
>
> #### Possible Ways to Fix It
> You can force enable the option by setting `config.experimental.webpackBuildWorker: true` in the config.

which, by the way, does not work, so don’t try to add it.

**Comment by AwesomeDevin** [comment]
1

**Comment by codemile** [comment]
Adding the flag to my `next.config.js` on a Nx workspace project seemed to resolve the issue, but I don't understand what this flag was for or why.

```
    experimental: {
        webpackBuildWorker: true
    },
```

**Comment by webjay** [comment]
I would also like to know why I need `experimental`?
This is why I need to have a custom webpack:
https://github.com/getsentry/sentry-javascript/discussions/9424#discussion-5800971

**Comment by levino** [comment]
For me this happens when I use `withMdx` following the [docs](https://nextjs.org/docs/app/building-your-application/configuring/mdx).

**Comment by bensonbjacob** [comment]
I can't find anyway to resolve the "Custom Webpack Configuration". I'm simply unable to build my app at this point.

**Comment by luismmadeirac** [comment]
I was getting the same error running with v14.0.1 when udpated to version 14.0.3 the error seems to be fixed.

**Comment by feedthejim** [comment]
this should be fixed in the latest version
