### ISSUE TITLE
Docs: Are you interested in an `decode-formdata` example?

### ISSUE THREAD

**Issue by fabian-hiller** [vercel/next.js#57887]
### What is the improvement or update you wish to see?

I think that my library [`decode-formdata`](https://github.com/fabian-hiller/decode-formdata) enhance the DX when using Server Actions. Therefore it could make sense to add an example to the docs.

### Is there any context that might help us understand?

When the values of a form are encoded to `FormData` to send them to the server, some information is lost. Using my library, you can decode `FormData` into a simple JavaScript object and supplement the information that was lost during encoding.

A simple example is included in our [README](https://github.com/fabian-hiller/decode-formdata/blob/main/README.md).

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/server-actions

**Comment by balazsorban44** [comment]
Hi, I think [adding an example](https://github.com/vercel/next.js/blob/canary/contributing/examples/adding-examples.md) to begin with would be nice! Feel free to open a PR, and we can review it, thanks!
