### ISSUE TITLE
--experimental-https doesn't allow for extending NODE_EXTRA_CA_CERTS

### ISSUE THREAD

**Issue by alex-way** [vercel/next.js#57958]
### Link to the code that reproduces this issue

https://github.com/alex-way/next-js-https-overwriting-node

### To Reproduce

1. Start the application `pnpm dev`
2. Observe the console log being `C:\Users\USERNAME\AppData\Local\mkcert/rootCA.pem` rather than the NODE_EXTRA_CA_CERTS

## Current behaviour

`NODE_EXTRA_CA_CERTS` environment variable is overwritten from the user-specified value and set to  `C:\Users\USERNAME\AppData\Local\mkcert/rootCA.pem`

## Expected behaviour

NODE_EXTRA_CA_CERTS shouldn't be overwritten, or NextJS should allow us to extend the value so we can set our own value for `NODE_EXTRA_CA_CERTS`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Enterprise
Binaries:
  Node: 20.8.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by ztanner** [comment]
Hi, you can override all of the self-signed certificate options: https://github.com/vercel/next.js/blob/6c6ac700b221f2018a03b05c16224055b15629f4/packages/next/src/cli/next-dev-args.ts#L10-L12

`--experimental-https-ca` will be used for `NODE_EXTRA_CA_CERTS` if specified.
