### ISSUE TITLE
`fetch` cache and `unstable_cache` not caching correctly on Vercel since `14.0.2-canary.6` 

### ISSUE THREAD

**Issue by pawelblaszczyk5** [vercel/next.js#57978]
### Link to the code that reproduces this issue

https://github.com/pawelblaszczyk5/revalidate-vercel-test

### To Reproduce

1. Go to https://revalidate-vercel-test.vercel.app/fetch-cache-test or https://revalidate-vercel-test.vercel.app/revalidate-tag-test
2. Refresh
3. Observe the random number being changed despite it being cached in code

### Current vs. Expected behavior

I tried the reproduction with different canaries after spotting that it works with latest stable and doesn't work on canary. It turns out since exactly `14.0.2-canary.6` version the `fetch` cache and `unstable_cache` doesn't seem to be cached properly on Vercel. It works locally, but after deployed the fetch/function are always re-invoked. 

Here in my code you can see these resources being marked for cache 

https://github.com/pawelblaszczyk5/revalidate-vercel-test/blob/4c4cd9f732515be45c18734e7d985fa24bf312ba/app/fetch-cache-test/page.tsx#L13

https://github.com/pawelblaszczyk5/revalidate-vercel-test/blob/4c4cd9f732515be45c18734e7d985fa24bf312ba/app/revalidate-tag-test/page.tsx#L14

Expected behavior would be to be cached properly on Vercel

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Fri Oct 13 09:27:54 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.6.2
Relevant Packages:
  next: 14.0.2-canary.6
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

### Additional context

Here is a deployment on the first not working canary: https://revalidate-vercel-test.vercel.app/fetch-cache-test
Here is a deployment with last working canary (`14.0.2-canary.5`): https://revalidate-vercel-test-ij8w5h8b9-pawelblaszczyk5.vercel.app/fetch-cache-test

There're two URLs affected by this issue on each of this pages `/fetch-cache-test` and `/revalidate-tag-test`. There is also server action for revalidating these tags.

**Comment by pawelblaszczyk5** [comment]
Still applicable, now on "stable" `14.0.2.` release 😅

**Comment by erzr** [comment]
I'm also experiencing this, I've tested a few scenarios:

* `fetch` request directly in page.tsx, fetch caches as expected.
* Creating an instance of our API client, which uses `fetch` internally, inside of page.tsx and retrieving data through it, fetch caches as expected.
* Using a server component exported from our component library package, which uses our API client to fetch data internally, does not cache as expected. Suspect it's not getting the patched `fetch` function?

Bottom scenario worked prior to 14.0.2.

**Comment by collinversluis** [comment]
I'm seeing the same thing here. "fetch" and "unstable_cache" are running every time on vercel but not on local builds
