### ISSUE TITLE
Router.push is very slow even in production mode in AWS Amplify

### ISSUE THREAD

**Issue by dev-gush** [vercel/next.js#57986]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/thirsty-glade-99c4tt?file=%2Fapp%2Fsecond-page%2Fpage.tsx%3A2%2C19

### To Reproduce

1. create a router from `useRouter` hook from 'next/navigation`
2. use the router with function call `router.push` to change page

### Current vs. Expected behavior

The Router is very slow in changing the page view, it should be faster.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
-- DOES NOT APPLY --
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I am running my nextjs application in AWS Amplify, even in production mode the `router.push` takes a lot of time to change the page.

**Comment by timneutkens** [comment]
Unfortunately there is nothing we can do based on this report. The reproduction is showing a barebones hello-world Next.js application, we have no control over AWS Amplify hosting and can't make optimizations there.

The provided  reproduction is using a very old canary version of Next.js 13:

<img width="293" alt="CleanShot 2023-11-09 at 14 34 39@2x" src="https://github.com/vercel/next.js/assets/6324199/73cf9f10-04b1-49ca-b4e2-34a839c43f84">

I've created a separate codesandbox with next build + next start, as you can see the navigation is instant: https://rv6tzn-3000.csb.app/
Sandbox: https://codesandbox.io/p/sandbox/kind-pasteur-rv6tzn?file=%2Fapp%2Fpage.tsx%3A4%2C44
