### ISSUE TITLE
next/font with local font renders font differently with turbopack

### ISSUE THREAD

**Issue by gabooh** [vercel/next.js#57992]
### Link to the code that reproduces this issue

https://github.com/gabooh/next-font-bug

### To Reproduce

1. Start the app with next dev, keep the tab open
2. Start the app with next dev --turbo, compare the two rendered pages
3. the one ran with --turbo is not rendered correctly

Running with next build && next start is ok, renders the same as with next dev.

See the screenshot : 
![Screenshot_20231103_162141](https://github.com/vercel/next.js/assets/3327028/8bd7f2ab-1c96-4083-834c-8c2a79409592)

Top render is next dev --turbo, bottom one is next dev

### Current vs. Expected behavior

The font / text is not rendered correctly in the case of the next dev --turbo run.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #10-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 13 13:49:38 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.6.3
Relevant Packages:
  next: 14.0.2-canary.10
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

**Comment by sokra** [comment]
should be fixed by https://github.com/vercel/turbo/pull/6382, but I haven't verified. Latest canary has this change.

**Comment by gabooh** [comment]
Indeed, it's fixed in Next.js 14.0.2.
Thank you @sokra !
