### ISSUE TITLE
Docs: Please publish blog updates as RSS feed

### ISSUE THREAD

**Issue by CodingSpiderFox** [vercel/next.js#57993]
### What is the improvement or update you wish to see?

Please publish the updates under https://nextjs.org/blog/rss and/or https://nextjs.org/blog/feed as XML.

### Is there any context that might help us understand?

I use Thunderbird Mail as RSS reader
I want to stay updated but I can't find a RSS / ATOM feed for https://nextjs.org/blog

**Comment by wwwdepot** [comment]
`https://nextjs.org/feed.xml`

**Comment by ztanner** [comment]
Indeed, the link shared above looks correct. Thanks!

**Comment by CodingSpiderFox** [comment]
Awesome, thanks :)
