### ISSUE TITLE
Route Groups not working in the latest version of Next

### ISSUE THREAD

**Issue by ARKA0001** [vercel/next.js#58028]
### Link to the code that reproduces this issue

https://github.com/ARKA0001/job-circuit

### To Reproduce

1. Start the development server using the command "npm run dev"
2. Create a directory like this (noAuth) and a default index.js with some random content
3. From main page.js try to navigate to **(noAuth)/** using router.push()
4. If we use App router it is supposed to navigate to that URL but it is showing 404 error

### Current vs. Expected behavior

Current behavior : 

Showing 404 Page cannot be found error

Expected Behavior : 

Navigate to the page that is under route group

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Here is my initial package.json

{
  "name": "job-circuit",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.0.2-canary.11",
    "react": "^18",
    "react-dom": "^18",
  }
}
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

**Comment by njarraud** [comment]
You shall do `router.push('/Onboarding')`not `router.push('/(noAuth)/Onboarding')`.

**Comment by Isaac-Tait** [comment]
I am experiencing this issue too in `14.0.1` When I create an `about.js` page and put it in `src/app` or `src/app/pages` and navigate to the about page (local and production) it returns a 404 error

**Comment by divodeuxsevres** [comment]
Im currently facing the same issue,
my project structure looks exactly like this:
- (admin) > dashboard > page.tsx
- (web) > page.tsx
- (dev) > test > page.tsx

for some reason only the routes in web folder are working.
im using mac, next.js 14 with turbo

**Comment by timneutkens** [comment]
As @njarraud mentioned route groups are not part of the url, so you can't actively router.push to them. For the other comments they don't sound exactly related to the initial report. Please open a new issue with a reproduction repository so that we can have a look.
