### ISSUE TITLE
Server Action Hydration issue

### ISSUE THREAD

**Issue by RootedXpert** [vercel/next.js#58049]
### Link to the code that reproduces this issue

https://github.com/RootedXpert/crm-portal/tree/develop

### To Reproduce

Server Action Hydration issue in page under dynamic routes

HTML from server:
![image](https://github.com/vercel/next.js/assets/52459940/a6bdf03e-d8b3-4af3-b2a5-ac52f9a902e4)

HTML After Hydration
![image](https://github.com/vercel/next.js/assets/52459940/827cf8fe-a8ed-4f4d-a68d-b028636a97a5)

### Current vs. Expected behavior

Current Behavoir:
![image](https://github.com/vercel/next.js/assets/52459940/074ab2fd-694c-439c-bf2e-6b4ae1296dd5)

Expected behavior 
No hydration error warning

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
System:
  Platform: Windows
  Arch: x64
  Version: windows 11 home 22H2
Binaries:
  Node: 18.17.1
  npm:10.2.0
Relevant Packages:
  next: 14.0.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by masterbater** [comment]
If you have something to render on client side or any side effects, use useEffect

**Comment by RootedXpert** [comment]
I don't require any client side rendering I am looking to implement without client component all my component are server rendering I wanted to implement login page using server action

**Comment by masterbater** [comment]
> I don't require any client side rendering I am looking to implement without client component all my component are server rendering I wanted to implement login page using server action

Its impossible to make all components or page all server side. Your ui state, your ui changes (themes), form,  etc. local state?
You got that error, since you might have made some state that not sync with server and client hydration. 
'use client' is not a purely client its what SSR behavior in nextjs 12

**Comment by masterbater** [comment]
> I don't require any client side rendering I am looking to implement without client component all my component are server rendering I wanted to implement login page using server action

Its impossible to make all components or page all server side. Your ui state, your ui changes (themes), dom manipulation etc.?
You got that error, since you might have made some state that not sync with server and client hydration. 
'use client' is not a purely client its what SSR behavior in nextjs 12

**Comment by RootedXpert** [comment]
If i remove action in form or do ssr false i dont see hydration error i am seeing this error only after adding server action 

Here is server action 
![image](https://github.com/vercel/next.js/assets/52459940/0afd4d9c-1a97-4bdd-a30f-55daa9518d01)

Here is my Sign Form 
![image](https://github.com/vercel/next.js/assets/52459940/49661b81-4e39-46a6-93ba-fdf28e1b6d4c)

Here is the sign page
![image](https://github.com/vercel/next.js/assets/52459940/36a9d80a-1373-4225-b7fd-9f617fa6c871)

Here is 18n File
![image](https://github.com/vercel/next.js/assets/52459940/f0de6ecc-5b7f-4065-a45f-437c4b694ad6)

**Comment by RootedXpert** [comment]
in my screen shot above we can cleary see the difference in html attributes under form element
![image](https://github.com/vercel/next.js/assets/52459940/64c514b9-187a-4e02-8313-ecc3ca4655b0)

**Comment by RootedXpert** [comment]
> > I don't require any client side rendering I am looking to implement without client component all my component are server rendering I wanted to implement login page using server action
> 
> Its impossible to make all components or page all server side. Your ui state, your ui changes (themes), dom manipulation etc.? You got that error, since you might have made some state that not sync with server and client hydration. 'use client' is not a purely client its what SSR behavior in nextjs 12

There is no ui state chnage no dom manipulation or theme changes

**Comment by tfarhan00** [comment]
Is the <Button /> component contain some client-side code?

**Comment by RootedXpert** [comment]
> Is the `<Button />` component contain some client-side code?

Nope 
![image](https://github.com/vercel/next.js/assets/52459940/eda71386-40d6-4398-9e93-e6a80cf411f6)

**Comment by RootedXpert** [comment]
This issue was resolved after this pr https://github.com/vercel/next.js/pull/59175
