### ISSUE TITLE
https://nextjs.org/learn-pages-router/ dark mode not working!!!

### ISSUE THREAD

**Issue by DanielOberlechner** [vercel/next.js#58067]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
I don't know if this report should be created here, but I didn't find another place.
If you open https://nextjs.org/learn-pages-router/ and try to set at the bottom the dakr mode nothing changes. I tried it with 3 different browsers on macOS Sonoma Developer Preview.
```

### Which example does this report relate to?

https://nextjs.org/learn-pages-router/

### What browser are you using? (if relevant)

Chrome Beta

### Describe the Bug

See the description above

### Expected Behavior

The background place should  be dark but instead everything is white.
Here is a youtube video to demonstrate:
https://youtu.be/qJnMdWbpMaY

### To Reproduce

https://youtu.be/qJnMdWbpMaY

**Comment by leerob** [comment]
Dark mode only exists for the new version currently, we'll be working to move this over 👍
