### ISSUE TITLE
images.domains is deprecated when standalone not using that options

### ISSUE THREAD

**Issue by Hyodori04** [vercel/next.js#58074]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/peaceful-taussig-kf6gyp?file=%2Fpackage.json%3A5%2C27

### To Reproduce

1. build next app as standalone mode without config images.domain 
2. build
3. show warning 
`The "images.dominas" configuration is deprecated. Please use "images.remotePatterns" configuration instead.`

### Current vs. Expected behavior

the warning should not be showed up

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 4.0.1
  pnpm: 8.10.0
Relevant Packages:
  next: 14.0.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by saicharan-gevme** [comment]
Same issue for me, after upgrading my Next from 13.2.4 to 14.0.0

**Comment by 9vitorconti** [comment]
Same here after upgrading to 14.0.0

**Comment by SachinJadeja** [comment]
images.domains is deprecated inside NextJs 14 please use [images.remotePatterns](https://nextjs.org/docs/pages/api-reference/components/image#remotepatterns) instead

Example
`const nextConfig = {
    images: {
        remotePatterns: [{
            protocol: 'https',
            hostname: 'avatars.githubusercontent.com',
        }],
    }
};`

**Comment by VVIERV00** [comment]
To align your next.config.js with the latest Next.js configuration standards, you'll need to modify the images property from domains to remotePatterns. Here’s an example:

Before:

```
module.exports = {
  images: {
    domains: ["lh3.googleusercontent.com"],
  },
}
```
After:


```
module.exports = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'lh3.googleusercontent.com',
        pathname: '**', // This allows all paths under the specified hostname
      },
    ],
  },
}
```
For further details check out the [official documentation](https://nextjs.org/docs/pages/api-reference/components/image#configuration-options).

**Comment by Hyodori04** [comment]
> I see you are not even defining images at all in the config, try to empty define images remotePatterns. Here’s an example:
> 
> Before:
> 
> ```
> module.exports = {
> }
> ```
> 
> After:
> 
> ```
> module.exports = {
>   images: {
>     remotePatterns: [
>       {
>         protocol: 'https',
>         hostname: "aaaaaa.ai',
>         pathname: '**',
>       },
>     ],
>   },
> }
> ```
> 
> For further details check out the [official documentation](https://nextjs.org/docs/pages/api-reference/components/image#configuration-options).

I apply this solution. But same warning happens.

when look at build file(server.js),  remotePatterns is applied well. But domains options is filled with duplicated value of my serivce hostname (ex aaaaaa.ai)

```
"domains":["aaaaaa.ai"," aaaaaa.ai"]
"remotePatterns":[{"protocol":"https","hostname":"aaaaaa.aii","pathname":"**"}]
```
