### ISSUE TITLE
Docs: broken download for SVG logo & wordmark on homepage

### ISSUE THREAD

**Issue by franky47** [vercel/next.js#58083]
### What is the improvement or update you wish to see?

On the [Next.js homepage](https://nextjs.org/) on Desktop, one can right-click the ▲ / NEXT.JS logo on the top-left corner to copy the assets as SVG:

<img width="362" alt="CleanShot 2023-11-06 at 14 18 20@2x" src="https://github.com/vercel/next.js/assets/1174092/de753971-7f9d-4d8f-b594-20ba3595dd5e">

However, upon doing so, an error is logged in the console:

```txt
Uncaught Error: Internal Error: do not use legacy react-dom/server APIs. If you encountered this error, please open an issue on the Next.js repo.
  renderToStaticMarkup
  onSelect
  onClick
  ...
```

### Is there any context that might help us understand?

I'd like to use the assets for a blog post og:image. In the mean time, I've copied the rendered SVG from the devtools.

### Does the docs page already exist? Please link to it.

https://nextjs.org/

**Comment by leerob** [comment]
We're tracking this and will get it fixed. Thank you and apologies for the issue here.

**Comment by franky47** [comment]
Thanks Lee!

**Comment by opeologist** [comment]
@leerob where are you tracking this issue? i'm attempting to use `renderToStaticMarkup` in my next app to output some html for a tooltip package, and am getting this error now. i'd like to follow progress on resolving this issue, so i know how to fix this problem for my usecase once it's been fixed. thank you!
