### ISSUE TITLE
Middleware setup

### ISSUE THREAD

**Issue by akmaluddin** [vercel/next.js#58092]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/runtime-sea-8chr7s?file=%2Fmiddleware.ts%3A12%2C48

### To Reproduce

Observe CodeSandbox

### Current vs. Expected behavior

The middleware is not being triggered and no redirects are happening

This seems to be prevalent with quite possibly page extension config

In my current setup, next@14.0.1, the middleware I have is located at the same level as my pages directory and I am observing this error

```
next/server should not be imported outside of pages/_middleware.js
```

however moving it into pages folder, I am not observing the middleware being triggered

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
"dependencies": {
    "next": "canary",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "20.4.5",
    "@types/react": "18.2.18",
    "typescript": "5.1.3"
  }
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

**Comment by Nayeem-XTREME** [comment]
Seems like the issue is happening from the `next.config.js` file:

```
/** @type {import("next").NextConfig} */
module.exports = {
  reactStrictMode: true,
  pageExtensions: ["page.tsx", "page.ts"],
};
```

After removing the `pageExtensions` option, the middleware is working as expected.

**Comment by akmaluddin** [comment]
Yeap, I noted that the bug may arise with the pageExtensions option

Is there a way to have both `pageExtensions` and the middleware? Otherwise this has to be clearly communicated and documented

In my opinion I should not be limited to having either or cause again in my opinion these two shouldnt conflict with each other

**Comment by eddiesholl** [comment]
Just stumbled on this myself. Does anyone have any thoughts on where the bug might be happening? Or ideas for workarounds?

**Comment by akmaluddin** [comment]
@eddiesholl unfortunately the workaround is to not use pageExtension options if you require the middleware

**Comment by eddiesholl** [comment]
OK I can report back some partial success with this issue. I've found a workaround, and the likely cause of the bug.

A solution / workaround is to include the middleware as a valid page file. Note the config item is called `pageExtensions`, so you're configuring the file name suffixes that can be treated as pages. Something like:
- add an entry `middleware.ts` to your `pageExtensions` config item
- name your middleware file `<anything>.middleware.ts`
- it should now be included in the processing pipeline long enough for the middleware content to be detected

Would love to know if there are any ugly side effects of including it like this.

The offending code that triggers the problem looks to be here:
https://github.com/vercel/next.js/blob/faa44210340d2ef19da6252e40a9b3e66f214637/packages/next/src/server/lib/router-utils/setup-dev-bundler.ts#L1908C24-L1908C24

If a page does not pass the 'valid page file' test, the processing bails out, before the middleware config can be extracted from it.

**Comment by samcx** [comment]
@akmaluddin Thank you for sharing!

If you rename your middleware file to `middleware.page.ts`, which is necessary when you use [Page Extensions](https://nextjs.org/docs/pages/api-reference/next-config-js/pageExtensions), your Middleware will indeed run.

Let me know if that helps!
