### ISSUE TITLE
With turbopack example uses webpack for build step

### ISSUE THREAD

**Issue by 42shadow42** [vercel/next.js#58103]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: N/A
  pnpm: 8.9.0
Relevant Packages:
  next: 14.0.2-canary.14
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-turbopack

### How are you deploying your application? (if relevant)

next start

### Describe the Bug

When using the example build script there is no option to enable turbopack specfied so it falls back to webpack build processes, making it significantly different then that dev run.

Furthermore when correcting the script with the --experimental-turbo flag on build, the example fails to run properly, because the entry scripts do not load on the browser.

### Expected Behavior

1. It should build with turbopack.
2. The page should load with interactivity

### To Reproduce

1. Create a project using the template.
2. Update the build script to include the --experimental-turbo flag.
3. Server the package using the start script
4. Observe a 404 in the network pane of the browser indicating it couldn't bootstrap the react scripts

**Comment by 42shadow42** [comment]
It appears the only reason this is having problems is the resource is not fully url encoded when requesting the resource, when url encoding the [] symbols the resources become available.

**Comment by timneutkens** [comment]
https://nextjs.org/blog/next-14#nextjs-compiler-turbocharged

We're focusing on development first. Builds will follow after development is fully landed.
