### ISSUE TITLE
Next.js 14 On-demand ISR error

### ISSUE THREAD

**Issue by iCanbolat** [vercel/next.js#58106]
### Link to the code that reproduces this issue

https://github.com/iCanbolat/feedbacker/blob/main/src/app/(feedbacker)/feedbacker/page.tsx

### To Reproduce

I was following the vercel [docs](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#on-demand-revalidation) to implement on-demand ISR . Its okay on local but when i build it gives an error. 

code -> [Repo](https://github.com/iCanbolat/feedbacker/blob/main/src/app/(feedbacker)/feedbacker/page.tsx)

thanks for any help..

### Current vs. Expected behavior

> error: Type 'OmitWithTag<{ [key: string]: any; todos: any; }, keyof PageProps, "default">' does not satisfy the constraint '{ [x: string]: never; }'.
> 'string' index signatures are incompatible.
> Type 'any' is not assignable to type 'never'.
> 
> 27 | // Check the prop type of the entry function
> 28 | checkFields<Diff<PageProps, FirstArg<TEntry['default']>, 'default'>>()
> | ^
> 29 |
> 30 | // Check the arguments and return type of the generateMetadata function
> 31 | if ('generateMetadata' in entry) {

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next:14,
node:20,
react:18.2
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

**Comment by AlejandraAlmeida** [comment]
Hi, I just had the same problem:
previous code
`export default function MainPage(**_isUserActive?: boolean, profile?: string_**) {
  // TODO provisional
  return redirect('/login');
}`

I was passing these parameters in the app/page.tsx, then I deleted them, and now it works. Check the pages.
