### ISSUE TITLE
Tailwind with middleware redirect not working

### ISSUE THREAD

**Issue by adithep** [vercel/next.js#58117]
### Link to the code that reproduces this issue

https://github.com/adithep/next-tailwind-bug

### To Reproduce

1. start server (next dev)
2. navigate to home
3. Be redirected to login page by middle ware
4. Tailwind class not working. (You do not see the underline)

### Current vs. Expected behavior

Current behavior: Text has not underline 
Expected behavior: Text has underline

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 14.0.2-canary.18
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

**Comment by timneutkens** [comment]
Middleware is very low level, it runs in front of *all request* in the way you've set it up, so you have to make sure you're not redirecting e.g. JavaScript file requests, basically anything in the `_next` path.

https://github.com/adithep/next-tailwind-bug/blob/main/middleware.ts#L6-L8

**Comment by devjiwonchoi** [comment]
@adithep Hope this helps.

```ts
export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
```

Ref: https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher
