### ISSUE TITLE
Server Actions does not work in unmount

### ISSUE THREAD

**Issue by khuezy** [vercel/next.js#58112]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/lingering-rain-jk29hd

### To Reproduce

1. Go to https://codesandbox.io/p/sandbox/lingering-rain-jk29hd
2. Click on "Click me" to call the server actions
3. See "Hello" in terminal
4. Click "Go away"
5. See error

```
 TypeError: __webpack_modules__[moduleId] is not a function
    at Object.__webpack_require__ [as require] (/workspaces/sandbox/.next/server/webpack-runtime.js:33:42)
```

### Current vs. Expected behavior

When making a server actions call in a component unmount, it should work.

```
  useEffect(() => {
    return () => {
      serverAction();
    };
  }, []);
```

But it crashes with error:
```
 TypeError: __webpack_modules__[moduleId] is not a function
    at Object.__webpack_require__ [as require] (/workspaces/sandbox/.next/server/webpack-runtime.js:33:42)
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Next 14.0.1, on any platform... see codesandbox
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

The latest canary doesn't work in the sandbox environment.

<sub>[NEXT-1710](https://linear.app/vercel/issue/NEXT-1710/server-actions-does-not-work-in-unmount)</sub>

**Comment by alexnunan** [comment]
I'm having the same issue, calling a server action and getting this error. Every so often it works, seemingly at random. Please let me know if you find a solution.

**Comment by RootedXpert** [comment]
Facing the same issue while using server action along withIntercepting Routes 

![image](https://github.com/vercel/next.js/assets/52459940/5705d2c4-0197-40a6-b9a6-2e22a8e24bc4)

Feature are working standalone but if we are combined and used then they are breaking 
ie for dynamic routes Intercepting Routes is  not working 404 error 
dynamic routes along with server action with ssr facing hydration issue

https://github.com/vercel/next.js/issues/57776
https://github.com/vercel/next.js/issues/58049

**Comment by khuezy** [comment]
This is fixed in the latest canary, via https://github.com/vercel/next.js/pull/59369
