### ISSUE TITLE
Metadata is not generated for intercepting routes

### ISSUE THREAD

**Issue by max-mayorov** [vercel/next.js#58123]
### Link to the code that reproduces this issue

https://github.com/max-mayorov/nextgram

### To Reproduce

The project is also deployed on Vercel - https://nextgram-chi.vercel.app

1. Click on the photo to show intercepting modal : shows modal, but page title stays "NextGram"
2. Navigate to a photo by URL https://nextgram-chi.vercel.app/photos/1 or do a hard reload: photo page is loaded, title is correct "Photo # 1"

### Current vs. Expected behavior

When intercepting modal page is shown (scenario 1):
Expected: page title should be "Intercepted Photo # 1"
Actual: page title is "NextGram"

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Not relevant, happens on local and on Vercel.

On local:
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.18.2
  npm: N/A
  Yarn: N/A
  pnpm: 8.8.0
Relevant Packages:
  next: 14.0.2-canary.18
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

**Comment by Abioze** [comment]
I have the same problem, but when I try your link, it works. Did you resolve the problem?
