### ISSUE TITLE
<Image> component crashes when image url lacks filename, e.g. `/.png`

### ISSUE THREAD

**Issue by jakst** [vercel/next.js#58139]
### Link to the code that reproduces this issue

https://github.com/jakst/next-image-error-repro

### To Reproduce

1. Start the dev server
2. Open the app
3. The render crashes with the following error
```
Error: Invalid src prop (https://github.com/.png) on `next/image`, hostname "github.com" is not configured under images in your `next.config.js`
See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host
```

### Current vs. Expected behavior

I expected the page to render, but with a missing image.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64
Binaries:
  Node: 21.0.0
  npm: N/A
  Yarn: 4.0.0
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.2-canary.18
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

### Additional context

This happened when switching from the deprecated images.domains in next.config
```javascript
const nextConfig = {
  images: {
    domains: ["github.com"],
  },
}
```

To the new remotePatterns
```javascript
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "github.com",
      },
    ],
  },
}
```

They are both valid and contain the "github.com" hostname, so the error message is misleading. But also, the error shouldn't be shown at all because the URL is valid.

**Comment by joey-ma** [comment]
Running into the same issue here on `"next": "14.0.1"`, relating to 
`⨯ Error: Invalid src prop (https:.../.../...jpg) on `next/image`, hostname "images.ctfassets.net" is not configured under images in your next.config.js` 
when it is added to the `nextConfig.images.remotePatterns (following docs [here](https://nextjs.org/docs/app/api-reference/components/image#remotepatterns))

tried simple downgrading to `14.0.0` & `13.5.6`, but the issue remains. Both syntax produced the same error message.
```ts

      {
        protocol: 'https',
        hostname: 'images.ctfassets.net',
      },
```
```ts
      {
        protocol: 'https',
        hostname: 'images.ctfassets.net',
        port: '',
        pathname: '/*/*/*/*.*',
      },
```

I'm only migrating from a different project that currently works on `13.5.6`, so I'm not sure what could be the reason or the fix at the moment.

Is Next.js 14 using a different image-loader?
`⨯ node_modules/next/dist/shared/lib/image-loader.js (41:26) @ defaultLoader`
