### ISSUE TITLE
Not showing any errors while Building on local. but vercel doesn't build next.js app without showing any errors.

### ISSUE THREAD

**Issue by mthakur5** [vercel/next.js#58168]
### Link to the code that reproduces this issue

https://github.com/mthakur5/www.haroth.com

### To Reproduce

npm run build

when running same web app in localhost. building time was 18-20 min. but when i trying to build on vercel it is not showing any errors, even it is conconfusing because building time was more than 45 min. but build stop in 6 min. without any errors.

https://imgur.com/o3Ofzmx

Please find attached picture above.

### Current vs. Expected behavior

This project should build in 20-25 min.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "sitemap": "node generateSitemap.js"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.9.5",
    "@vercel/analytics": "^1.0.2",
    "axios": "^1.4.0",
    "dotenv": "^16.3.1",
    "framer-motion": "^10.12.18",
    "js-cookie": "^3.0.5",
    "next": "13.4.7",
    "next-auth": "^4.22.1",
    "next-sitemap": "^4.2.3",
    "nextjs-progressbar": "^0.0.16",
    "node-cron": "^3.0.2",
    "nodemailer": "^6.9.4",
    "onesignal": "^0.1.2",
    "otp-gen-agent": "^1.1.2",
    "qs": "^6.11.2",
    "razorpay": "^2.9.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.45.1",
    "react-hot-toast": "^2.4.1",
    "react-icons": "^4.10.1",
    "react-multi-carousel": "^2.8.4",
    "react-otp-input": "^3.0.2",
    "react-redux": "^8.1.1",
    "react-responsive-carousel": "^3.2.23",
    "react-spinners": "^0.13.8",
    "sharp": "^0.32.4",
    "shortid": "^2.2.16",
    "sitemap": "^7.1.1"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.14",
    "eslint": "8.44.0",
    "eslint-config-next": "13.4.7",
    "postcss": "^8.4.24",
    "tailwindcss": "^3.3.2"
  }
}
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I have tested in localhost and it working fine. took 18-20 min. for build while app.

i don't understand what is wrong with this. please help me asap.

**Comment by timneutkens** [comment]
<img width="1022" alt="CleanShot 2023-11-09 at 16 26 19@2x" src="https://github.com/vercel/next.js/assets/6324199/5aef4dd2-fb92-475b-973a-d78d523d3f86">

Can't access the provided repository but there are 2000 log lines that you can open in the provided screenshot.

**Comment by mthakur5** [comment]
sir you can visit repository, i have locked because i didn't know when you will reply. apologise for it.

Thank you for considering this.

**Comment by mthakur5** [comment]
> <img alt="CleanShot 2023-11-09 at 16 26 19@2x" width="1022" src="https://user-images.githubusercontent.com/6324199/281782276-5aef4dd2-fb92-475b-973a-d78d523d3f86.png">
> Can't access the provided repository but there are 2000 log lines that you can open in the provided screenshot.

i have monitor every line in 2000 & further. there is not "Red error", i have also build in local and it is fine. even i have tried to build in my ec2 instance. there is also fine builded.

sir you can visit repository. please refresh your browser.

Thank you for considering this.

**Comment by mthakur5** [comment]
anyone help me?

 i don't understand why this project build properly in localhost or ec2. while hosting on vercel it failed? i have to switch vercel to aws amplify.

**Comment by timneutkens** [comment]
<img width="1800" alt="CleanShot 2023-11-15 at 13 02 51@2x" src="https://github.com/vercel/next.js/assets/6324199/5eb66d06-558b-499c-9907-0e363b857ebe">

The repository is not available still.

**Comment by mthakur5** [comment]
> <img alt="CleanShot 2023-11-15 at 13 02 51@2x" width="1800" src="https://user-images.githubusercontent.com/6324199/283109768-5eb66d06-558b-499c-9907-0e363b857ebe.png">
> The repository is not available still.

hi Tim, 

see this is public for Now. this is available only a week. because it production site. i can't keep in public. tim 

Try to understand TIM.

![Capture](https://github.com/vercel/next.js/assets/138131563/e47ee9b9-2f10-4e60-adda-775cbd15be8d)


https://imgur.com/DHHin3F

**Comment by mthakur5** [comment]
someone help me please, i am still figuring out why i can't publish on vercel. i couldn't even update my production site.
