### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by zjy365** [vercel/next.js#58177]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 20.4.0
      npm: 9.7.2
      Yarn: 1.22.19
      pnpm: 8.6.7
    Relevant packages:
      next: 13.1.6
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Which example does this report relate to?

hello-world

### What browser are you using? (if relevant)

Chrome 119.0.6045.105

### How are you deploying your application? (if relevant)

docker image

### Describe the Bug

Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useRef')
    at useRef (/Users/jingyang/work/sealos/frontend/node_modules/.pnpm/registry.npmmirror.com+react@18.2.0/node_modules/react/cjs/react.development.js:1630:21)
    at useModal (file:///Users/jingyang/work/sealos/frontend/node_modules/.pnpm/@chakra-ui+modal@2.3.1_@chakra-ui+system@2.6.1_framer-motion@10.16.4_react-dom@18.2.0_react@18.2.0/node_modules/@chakra-ui/modal/dist/chunk-TJ2Q5ITW.mjs:23:21)
    at Modal (file:///Users/jingyang/work/sealos/frontend/node_modules/.pnpm/@chakra-ui+modal@2.3.1_@chakra-ui+system@2.6.1_framer-motion@10.16.4_react-dom@18.2.0_react@18.2.0/node_modules/@chakra-ui/modal/dist/chunk-MSA2NPQT.mjs:51:17)
    at renderWithHooks (/Users/jingyang/work/sealos/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/jingyang/work/sealos/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/jingyang/work/sealos/frontend/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    
    
monorepo     
The root project dependencies are as follows
```
  "devDependencies": {
    "@chakra-ui/cli": "^2.4.1",
    "prettier": "^2.8.8"
  },
  "dependencies": {
    "@chakra-ui/anatomy": "^2.2.1",
    "@chakra-ui/next-js": "^2.1.5",
    "@chakra-ui/react": "^2.8.1",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "framer-motion": "^10.16.4",
    "typescript": "^5.2.2"
  }
```
Subproject dependencies
```
 "dependencies": {
    "@chakra-ui/icons": "^2.1.1",
    "@chakra-ui/system": "^2.6.1",
    "@kubernetes/client-node": "^0.18.1",
    "@next/font": "13.1.6",
    "@tanstack/react-query": "^4.35.3",
    "ansi_up": "^5.2.1",
    "axios": "^1.5.1",
    "date-fns": "^2.30.0",
    "dayjs": "^1.11.10",
    "echarts": "^5.4.3",
    "i18next": "^22.5.1",
    "immer": "^9.0.21",
    "js-cookie": "^3.0.5",
    "js-yaml": "^4.1.0",
    "jszip": "^3.10.1",
    "lodash": "^4.17.21",
    "nanoid": "^4.0.2",
    "next": "13.1.6",
    "next-i18next": "^13.3.0",
    "nprogress": "^0.2.0",
    "prettier": "^2.8.8",
    "react": "18.2.0",
    "react-day-picker": "^8.8.2",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.46.2",
    "react-i18next": "^12.3.1",
    "react-markdown": "^8.0.7",
    "github-markdown-css": "^5.2.0",
    "react-syntax-highlighter": "^15.5.0",
    "sass": "^1.68.0",
    "sealos-desktop-sdk": "workspace:*",
    "zustand": "^4.4.1"
  },
  "devDependencies": {
    "@svgr/webpack": "^6.5.1",
    "@types/js-cookie": "^3.0.4",
    "@types/js-yaml": "^4.0.6",
    "@types/lodash": "^4.14.199",
    "@types/node": "18.13.0",
    "@types/nprogress": "^0.2.1",
    "@types/react": "18.0.27",
    "@types/react-dom": "18.0.10",
    "@types/react-syntax-highlighter": "^15.5.7",
    "eslint": "8.33.0",
    "eslint-config-next": "13.1.6",
    "svg-inline-loader": "^0.8.2",
    "webpack-bundle-analyzer": "^4.9.1"
  }
```

### Expected Behavior

Dependencies cannot be changed. If there are changes, pnpm run dev will fail.

### To Reproduce

I think it might be related to this, but I don't see a solution
https://github.com/vercel/next.js/issues/49355

**Comment by icyJoseph** [comment]
Have you tried creating a module where you do something like:

```tsx
'use client'
export * from ''@chakra/ui-system";
```

And use that module instead when importing chakra stuff? 

Or alternatively import and re-export only the things you need

Or yet another alternative, turn some of your components into client components, specifically those that use Chakra.

**Comment by zjy365** [comment]
I tried copying the dependencies of the root project to the sub-project and no errors were reported. Is it a dependency problem?

I don't know if anyone else has encountered this problem
