### ISSUE TITLE
Support params and searchParams props for the loading file of a route

### ISSUE THREAD

**Issue by theoludwig** [vercel/next.js#58179]
### Link to the code that reproduces this issue

https://github.com/theoludwig/nextjs-feature-loading-with-params

### To Reproduce

1. `npx create-next-app@latest`
2. Create a Dynamic Route with `params` (and potentially `searchParams`) with its loading page, for example:
	```sh
	├── about
	│   └── [slug]
	│       ├── loading.tsx
	│       └── page.tsx
	```
	Example of Route: `/about/slug-test?param1=abc&param2=123` 
3. Add a slow data request (for example simulated with `setTimeout`) to see the Loading page.
4. Use the `searchParams` and `params` props in both the page and loading page.
5. `npm run dev`
6. Go to <http://127.0.0.1:3000/about/slug-test?param1=abc&param2=123>, and notice that the `params` and `searchParams` props are not displayed while being in the loading state (but displayed when it's not loading anymore).

Example of the code:
```tsx
import Link from 'next/link';

import { getAPIData } from '@/lib/getAPIData';

export interface AboutBySlugPageProps {
  params: {
    slug: string;
  };
  searchParams: {
    param1?: string;
    param2?: string;
  };
}

const AboutBySlugPage: React.FC<AboutBySlugPageProps> = async (props) => {
  const { params, searchParams } = props;

  const data = await getAPIData();

  return (
    <main className="m-4">
      <h1 className="mt-6 text-3xl">About Page</h1>

      <ul>
        <li>
          <Link href="/" className="text-blue-500">
            Home Page
          </Link>
        </li>
      </ul>

      <section>
        <p>slug: {params.slug}</p>
        <p>param1: {searchParams.param1}</p>
        <p>param2: {searchParams.param2}</p>
        <div>
          Data: <pre>{JSON.stringify(data, null, 2)}</pre>
        </div>
      </section>
    </main>
  );
};

export default AboutBySlugPage;
```

### Current

![image](https://github.com/vercel/next.js/assets/25207499/182efa6a-0d8f-4140-a262-25dc672e3944)

You can see that `param1`, `param2` and `slug` is not displayed during loading.

### Expected

![image](https://github.com/vercel/next.js/assets/25207499/7d682d74-2225-41df-b013-4d2686855434)

Display the values from the props while loading.
The idea is not to make an API Request as it's not the role of the loading page, but there are some circumstances where it makes sense to display the raw url data when it's loading.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2
Binaries:
  Node: 20.9.0
  npm: 10.2.1
  Yarn: 1.22.19
  pnpm: 8.7.0
Relevant Packages:
  next: 14.0.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

**Comment by michaelangeloio** [comment]
@theoludwig have you tried adding the following to your JSX?

```tsx
import Link from 'next/link';

import { getAPIData } from '@/lib/getAPIData';

export interface AboutBySlugPageProps {
  params: {
    slug: string;
  };
  searchParams: {
    param1?: string;
    param2?: string;
  };
}

const AboutBySlugPage: React.FC<AboutBySlugPageProps> = async (props) => {
  const { params, searchParams } = props;

  const data = await getAPIData();
 
const someRandomHash = uuid() // <--- make a uuid for each request as an example

  return (
    <main className="m-4">
      <h1 className="mt-6 text-3xl">About Page</h1>

      <ul>
        <li>
          <Link href="/" className="text-blue-500">
            Home Page
          </Link>
        </li>
      </ul>

      <section key={someRandomHash} > 
      { /** key above here **/ }
        <p>slug: {params.slug}</p>
        <p>param1: {searchParams.param1}</p>
        <p>param2: {searchParams.param2}</p>
        <div>
          Data: <pre>{JSON.stringify(data, null, 2)}</pre>
        </div>
      </section>
    </main>
  );
};

export default AboutBySlugPage;
```

You can try setting the key as the search Param itself. This _should_ cause the tree to notice the state change and thus start the render.

https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#3-partial-rendering

**Comment by theoludwig** [comment]
Thanks for your reply @michaelangeloio!

I don't think you understood the problem I'm trying to solve, when it's not anymore in the loading state, there are correctly the searchParams and params displayed. I'm talking about the loading state.
Using a key on section doesn't  change anything.

**Comment by N1ve5h** [comment]
Unfortunately, it looks like you can not pass props through loading.tsx as Next.js only wants to pass Static Code (just HTML). I would recommend that you use [Suspense](https://nextjs.org/learn/dashboard-app/streaming).

Loading.tsx waits for the getAPIData() then whole page to load whereas Suspense will allow the page to load then whatever is wrapped inside it.

**Comment by theoludwig** [comment]
> Unfortunately, it looks like you can not pass props through loading.tsx as Next.js only wants to pass Static Code (just HTML). I would recommend that you use [Suspense](https://nextjs.org/learn/dashboard-app/streaming).
> 
> Loading.tsx waits for the getAPIData() then whole page to load whereas Suspense will allow the page to load then whatever is wrapped inside it.

Yeah, I believe this the only way to fix it for the moment, it is to wrap the page with Suspense, then inside have a server component do the `getAPIData()` request, and as fallback a Loading component, with the searchParams/params props given, that would work. :+1:

But from my understanding, it is basically what Next.js does for the `loading.tsx` file, and also the url has already been parsed to know which page it refers to when it's in loading state, so I don't see any problem to give those props to the loading.tsx component. :thinking: 

I think, Next.js should handle that case, but at least we know a workaround now, but still odd to do it that way IMO, would rather to have same behavior as the page for the loading.

**Comment by theoludwig** [comment]
Closing, as stated in https://github.com/vercel/next.js/pull/58510#issuecomment-1867049498, the solution to this use case is to use Suspense inside a Page instead of the loading file.
