### ISSUE TITLE
Docs: create-next-app doesn't explain what the src option is all about

### ISSUE THREAD

**Issue by ryzokuken** [vercel/next.js#58191]
### What is the improvement or update you wish to see?

It would be helpful, especially for first time users of `create-next-app` to understand what the "use the src directory" option is all about.

### Is there any context that might help us understand?

The directory structure of Next.js applications is quite specific and to an outsider, this choice is quite confusing. At the very least, there should be some more context here to understand what the implications of this choice are and the background.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/create-next-app

**Comment by leerob** [comment]
We have this documented here, if you search for `src` directory 😄 

https://nextjs.org/docs/getting-started/project-structure

**Comment by ryzokuken** [comment]
@leerob sure, but within the context of `create-next-app` it never comes up. Perhaps link to from the API reference and optionally from the CLI help text to help newcomers make the right choice?
