### ISSUE TITLE
createPortal node is rendered below

### ISSUE THREAD

**Issue by rainyEra** [vercel/next.js#58213]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/pensive-heisenberg-z55pzx?file=%2Fapp%2Fdrawer.tsx%3A11%2C11

### To Reproduce

https://github.com/vercel/next.js/assets/79323963/b06a0c7a-e31c-42c5-a8f1-5e2106102513

createPortal doesn't support natively SSR, so you have to use useEffect — document will be available. However , if your application is medium~ size w different layouts, then node will be rendered below root node, and if you want to open drawer — it will not show up.

1. Medium size application with layouts
2. createPortal somewhere
3. Node is rendered below
4. You are not able to interact with your Portal node

Server side — document is not defined, client side — node is bellow root element. It would be such a pleasure if developers could interact with root node and renderToString everything they need.

### Current vs. Expected behavior

Explained everything above

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next 14.0.1 App
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

**Comment by torresgol10** [comment]
The createPortal must work with "use client" because it needs the document to interact.

Actually your example is working correctly, you just need a top-0 to the createPortal element.

I hope this is helpful.

**Comment by rainyEra** [comment]
> The createPortal must work with "use client" because it needs the document to interact.
> 
> Actually your example is working correctly, you just need a top-0 to the createPortal element.
> 
> I hope this is helpful.

Yes, you are right, much thanks!
