### ISSUE TITLE
Array.toSorted, toSliced, toReversed polyfills missing

### ISSUE THREAD

**Issue by MonstraG** [vercel/next.js#58242]
### Link to the code that reproduces this issue

https://github.com/MonstraG/toSorted-polyfill-missing-nextjs

### To Reproduce

1. In reproduction template, update typescript to latest - 5.2.2
2. Put following in the Home file:
```
return [3,1,2,4].toSorted().toSpliced(1, 2).toReversed().map(x => <div key={x}>{x}</div>)
```
3. run app and open it in Safari 15.6

### Current vs. Expected behavior

Expected: 
```
4
1
```
on the screen

Actual:
Exception: `.toSorted is not a function`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Wed Oct 25 13:06:34 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 10.2.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.2-canary.25
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

See also https://github.com/vercel/next.js/discussions/44148.
Without this, [claim of supporting safari 12](https://nextjs.org/docs/architecture/supported-browsers) is invalid. 
There may be additional polyfills missing.

**Comment by MichalSalek** [comment]
The same. browserlist in a package.json or target in a tsconfig file changes give nothing.

**Comment by MichalSalek** [comment]
Nice, you proved to be faster with pr 😃 thanks

**Comment by marcklingen** [comment]
Same issue, users on Firefox 113 (May 2023)

**Comment by marcklingen** [comment]
@timneutkens the polyfills would be super helpful for our projects and I would love to see them merged

**Comment by MonstraG** [comment]
> @timneutkens the polyfills would be super helpful for our projects and I would love to see them merged

In the meantime, you can view the pr and add the same imports in your projects manually.

**Comment by thijsvandiessen** [comment]
I think it is better to use your own polyfill. For example utilising https://polyfill.io/ 
Not all projects need to support all browsers.

**Comment by MonstraG** [comment]
> I think it is better to use your own polyfill. For example utilising https://polyfill.io/ Not all projects need to support all browsers.

Next.js says they support safari 12: https://nextjs.org/docs/architecture/supported-browsers. At the moment that seems to be a lie?

**Comment by MonstraG** [comment]
> What's a good place to put them when using the app router?

In pages router I just put them in _app.tsx, in app router I would guess the top-level layout?

**Comment by utenma** [comment]
> I think it is better to use your own polyfill. For example utilising https://polyfill.io/ Not all projects need to support all browsers.

for a service to be useful needs to add support for the new 4 array methods

**Comment by RaenonX** [comment]
Opened https://github.com/vercel/next.js/pull/64725 because https://github.com/vercel/next.js/pull/58421 seems stale.

**Comment by MonstraG** [comment]
> Opened #64725 because #58421 seems stale.

I guess my pr is not fresh out of the oven, but I wouldn't call it stale. No maintener ever reviewed it so I did nothing to it.

**Comment by RaenonX** [comment]
> > Opened #64725 because #58421 seems stale.
> 
> I guess my pr is not fresh out of the oven, but I wouldn't call it stale. No maintener ever reviewed it so I did nothing to it.

Ah damn. I saw someone approved it but then another guy commented, no any other changes or conversations thereafter so I thought it's stale 😨

**Comment by RaenonX** [comment]
Per Tim from next.js on the PR (https://github.com/vercel/next.js/pull/64725) I opened before, they are unlikely to add such polyfill in. This means that we will need to add our custom polyfill if needed. 

This is how the polyfill should be added in next.js 14 app router. https://github.com/RaenonX-PokemonSleep/pokemon-sleep-ui/commit/b9fb52339a085f7ed632688dd5fb9278e8f862eb
