### ISSUE TITLE
Module not found: Can't resolve 'next/og'

### ISSUE THREAD

**Issue by wiscaksono** [vercel/next.js#58252]
### Link to the code that reproduces this issue

https://github.com/wiscaksono/wiscaksono-site/tree/og-images

### To Reproduce

1. Deploy it on vercel

### Current vs. Expected behavior

<img width="773" alt="image" src="https://github.com/vercel/next.js/assets/63142229/e7d1d7e3-015c-4aab-9840-62128880dc45">

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Binaries:
  Node: 18.18.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Additional context

I just want to deploy my fresh next app to the vercel, and then failed to compile, even am using the latest next js (14.0.1), it works when i build on my local machine, but not works on the vercel.

**Comment by duncan-tincello** [comment]
I see this error too. as soon as I add the example code from [https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#generate-icons-using-code-js-ts-tsx](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#generate-icons-using-code-js-ts-tsx)

**Comment by ruchernchong** [comment]
I am also faced with this error.

**Comment by choi-eugene** [comment]
any idea?

**Comment by wiscaksono** [comment]
> any idea?

no

**Comment by duncan-tincello** [comment]
I found a workaround - add `@vercel/og` and import that, eg.
`import { ImageResponse } from "@vercel/og";`

**Comment by timneutkens** [comment]
Please make sure that there is a reproduction provided. The linked repository is not public.

**Comment by wiscaksono** [comment]
> Please make sure that there is a reproduction provided. The linked repository is not public.

Hi, sorry about it, i updated the repo url

**Comment by ruchernchong** [comment]
> I found a workaround - add `@vercel/og` and import that, eg.
> 
> `import { ImageResponse } from "@vercel/og";`

Yeah. This works, knowing that it worked fine with the /pages directory before.

**Comment by timneutkens** [comment]
@wiscaksono so is it fixed in the latest version? Unclear why it was closed.

**Comment by ruchernchong** [comment]
> @wiscaksono so is it fixed in the latest version? Unclear why it was closed.

Yeah @wiscaksono have you already found a solution for this?

**Comment by wiscaksono** [comment]
maybe there are still bugs in `next/og`, but now I use `@vercel/og` and it works fine and without problems.

**Comment by ruchernchong** [comment]
> maybe there are still bugs in `next/og`, but now I use `@vercel/og` and it works fine and without problems at least for now.

Same here. Using `@vercel/og` too

**Comment by huozhi** [comment]
Hey I tried to redeploy your og route in a bare nextjs app (only having that route), there's no error on deployment. I'm using 14.0.2. Would you mind trying it again? And do you see that error locally?

**Comment by choi-eugene** [comment]
Hi. I updated next version to  14. 
(in my package.json  "next": "^14.0.0",   "@types/react": "18.2.7",
  "@types/react-dom": "18.2.4", ) 
Then the issue just gone. Good luck.

**Comment by ruchernchong** [comment]
> Hi. I updated next version to 14. (in my package.json "next": "^14.0.0", "@types/react": "18.2.7", "@types/react-dom": "18.2.4", ) Then the issue just gone. Good luck.

What is the exact version in your lockfile?

There were problems reported even on Next v14

**Comment by huozhi** [comment]
`ImageResponse` should be imported from `next/og` in `next@14`, should be imported from `next/server` in `next@13`.
Can you make sure it's imported correctly in your app? If it doesn't work can you share a reproduction?

I couldn't repro the issue on vercel by simplifying the reproduction from this issue
https://github.com/vercel/next.js/issues/58252#issuecomment-1814307016

**Comment by fahmij8** [comment]
happened to me too in next 13.5.4 
I supposed @vercel/og is the solution
