### ISSUE TITLE
Setting basePath causes parallel dynamic route modals to break

### ISSUE THREAD

**Issue by hmacafee** [vercel/next.js#58268]
### Link to the code that reproduces this issue

https://github.com/hmacafee/nextgram_basepath

### To Reproduce

Including a fork of the `nextgram` repo here: https://github.com/hmacafee/nextgram_basepath

1. Clone the fork
2. Run the app locally by running `yarn`, `yarn run dev`
3. Navigate to `localhost:3000/test-path` to see the app
4. Click any of the images to see the broken modal behavior 

### Current vs. Expected behavior

The root route no longer displays behind the modal. The root route should still display behind the modal when using parallel dynamic routes for a modal, but it no longer does when employing a `basePath`.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.2-canary.27
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

**Comment by omerman** [comment]
Experiencing this as well.

**Comment by ztanner** [comment]
Thanks for the report! This should be resolved by https://github.com/vercel/next.js/pull/60485
