### ISSUE TITLE
ReferenceError during build

### ISSUE THREAD

**Issue by aslamwebsite** [vercel/next.js#58290]
### Link to the code that reproduces this issue

https://github.com/aslamwebsite/ss-group

### To Reproduce

<html>
<body>

Error occurred prerendering page "/about-us". Read more: https://nextjs.org/docs/messages/prerender-error
--
14:19:32.574 | ReferenceError: document is not defined
14:19:32.574 | at Object.<anonymous> (/vercel/path0/build/server/chunks/538.js:1:196)
14:19:32.574 | at 21470 (/vercel/path0/build/server/chunks/538.js:1:10212)
14:19:32.574 | at __webpack_require__ (/vercel/path0/build/server/webpack-runtime.js:1:146)
14:19:32.577 | at 64677 (/vercel/path0/build/server/chunks/677.js:1:455)
14:19:32.577 | at __webpack_require__ (/vercel/path0/build/server/webpack-runtime.js:1:146)
14:19:32.577 | at 70908 (/vercel/path0/build/server/app/about-us/page.js:1:2184)
14:19:32.577 | at __webpack_require__ (/vercel/path0/build/server/webpack-runtime.js:1:146)
14:19:32.578 | at A (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:5655)
14:19:32.578 | at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:8070
14:19:32.578 | at H._fromJSON (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:35:8466)
14:19:32.764 | ReferenceError: window is not defined

</body>
</html>

### Current vs. Expected behavior

NA

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
{
  "name": "aslam-project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@accessible/accordion": "^2.0.0",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@mui/icons-material": "^5.14.14",
    "@mui/material": "^5.14.15",
    "aos": "^2.3.4",
    "axios": "^1.6.0",
    "bootstrap": "^5.3.2",
    "cloudinary-react": "^1.8.1",
    "framer-motion": "^10.16.4",
    "gsap": "^3.12.2",
    "lg-thumbnail": "^1.2.1",
    "lg-zoom": "^1.3.0",
    "lightgallery": "^2.7.2",
    "locomotive-scroll": "^4.1.4",
    "next": "13.5.6",
    "next-navigation": "^1.0.6",
    "odometer": "^0.4.8",
    "react": "^18.2.0",
    "react-countup": "^6.4.2",
    "react-dom": "^18",
    "react-intersection-observer": "^9.5.2",
    "react-map-interaction": "^2.1.0",
    "react-parallax": "^3.5.1",
    "react-scroll": "^1.9.0",
    "react-scroll-into-view": "^2.0.2",
    "react-scroll-parallax": "^3.4.2",
    "react-slick": "^0.29.0",
    "react-zoom-pan-pinch": "^3.3.0",
    "slick-carousel": "^1.8.1",
    "smooth-scrollbar": "^8.8.4"
  },
  "devDependencies": {
    "eslint": "^8",
    "eslint-config-next": "13.5.6"
  }
}
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

When I started deploying the project on vercel.com this error occurred on my screen & unable to publish my project on vercel. please help me out.

**Comment by astrit** [comment]
@aslamwebsite please try to rename the issue ✌️

**Comment by spencersmb** [comment]
Having the same issue with both static and dynamic pages that don't always throw and error each time I try and build

**Comment by aslamwebsite** [comment]
> @aslamwebsite please try to rename the issue ✌️

Same errors are coming. I have tried many times.

**Comment by sFritsch09** [comment]
related to 👉🏼 #58576

**Comment by DenisSkendaj** [comment]
A workaround is to disable SSR on specific components.
On my other project worked. Check here:
https://nextjs.org/docs/messages/react-hydration-error
https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#skipping-ssr

**Comment by huozhi** [comment]
Please file a new issue, the reproduction link doesn't contain the `/about-us` page anymore, the package.json provided doesn't match with the reproduction
