### ISSUE TITLE
Fetches Come Through Uncached in 14.0.2-canary.6

### ISSUE THREAD

**Issue by laugharn** [vercel/next.js#58306]
### Link to the code that reproduces this issue

https://github.com/madeincookware/cache-regression-repro

### To Reproduce

4. Visit a deployment of the repo on 14.0.1 https://cache-regression-repro-4tdgf5dex-madein.vercel.app
5. See that the caching behavior behaves as expected
1. Visit a deployment of the repro on 14.0.3-canary.0 https://cache-regression-repro-95zmmzx5n-madein.vercel.app
2. See that the first request is cached
3. Refresh, and see that the data is fetched freshly each time

### Current vs. Expected behavior

The data from the fetch should continue to be cached until it is invalidated.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: N/A
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.3-canary.0
  eslint-config-next: 14.0.3-canary.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

### Additional context

We traced this one back to a commit that happens between canary.5 and canary.6.

**Comment by pawelblaszczyk5** [comment]
I think that’s the same as this issue reported by me - https://github.com/vercel/next.js/issues/57978
