### ISSUE TITLE
Custom environment variables are undefined in component during dynamic rendering in Docker container

### ISSUE THREAD

**Issue by pdcarroll** [vercel/next.js#58316]
### Link to the code that reproduces this issue

https://github.com/pdcarroll/nextjs-env-repro

### To Reproduce

1. Run `docker build -t nextjs-repro .`
2. Run `docker run -p 3000:3000 nextjs-repro`
3. Navigate to `http://localhost:3000` -- An env variable from the `.env.local` file should be rendered in the page (see https://github.com/pdcarroll/nextjs-env-repro/blob/main/app/page.tsx#L98) but it is blank (undefined)

The variable will render in the page as expected in the following scenarios:
1. Running in dev (`npm run dev`) or prod (`npm start`) mode
2. Running in Docker only when [this line](https://github.com/pdcarroll/nextjs-env-repro/blob/main/app/page.tsx#L8) is commented out to avoid dynamic rendering

### Current vs. Expected behavior

Current:
- Custom environment variables are **not** defined in a streamed server component within a **dynamically** rendered page running in a Docker container
- Custom environment variables **are** defined in a streamed server component within a **dynamically** rendered page running in dev or prod mode locally on macOS
- Custom environment variables are **are** defined in a streamed server component within a **statically** rendered page running in a Docker container

Expected:
- Consistent behavior, either defined in all runtime environments, or undefined in all 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:39:52 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_X86_64
Binaries:
  Node: 18.15.0
  npm: 9.5.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3-canary.2
  eslint-config-next: 14.0.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

App Router, Standalone mode (output: "standalone")

**Comment by akwirick** [comment]
Looks like you aren't copying that .env file into your final `runner` image [see link](https://github.com/pdcarroll/nextjs-env-repro/blob/e40de154075496e9bbb219d1a0c880695b91941f/Dockerfile#L37)

You'll need to add another COPY step if you want that file to be loaded at runtime.

**Comment by pdcarroll** [comment]
@akwirick Thanks for the clarification, that makes sense. I found that I can also use an `.env.production` file instead of `.env.local` (without needing to explicitly copy the file) in the Docker container.
