### ISSUE TITLE
Image Component with AWS Throws 400 Errors and Unsupported image format in Production 

### ISSUE THREAD

**Issue by RajrupDasid** [vercel/next.js#58311]
### Link to the code that reproduces this issue

https://github.com/RajrupDasid/nextjs_resume_blog_symmetrical-system/issues/59

### To Reproduce

The problem is not appearing in development mode but in production mode.
where i am fetching image data from aws ,
this error has been occurred all of a sudden with out even merging or deploying any changes

nextjs version - 13.5.4

example code

```
 {posts &&
        posts.length > 0 &&
        posts.map((post: Post) => (
          <div
            className="bg-gradient-to-r from-gray-900 to-purple-900 max-w-sm rounded overflow-hidden mt-10 h-180 shadow-lg fcards"
            key={post._id}>
            <Link href={`${encodeURIComponent(post.slug)}`}>
              <Image
                src={`${
                  mode === "debug"
                    ? `${local}/${post.thumbnail}`
                    : post.thumbnail
                }`}
                alt="post images"
                className="w-full"
                width={400}
                height={700}
              />
              <div className="px-6 py-4">
                <div className="font-bold text-xl mb-2">{post.title}</div>
                <div
                  className="text-white text-base w-40 overflow-hidden"
                  dangerouslySetInnerHTML={{
                    __html: DOMPurify.sanitize(truncateContent(post.content)),
                  }}></div>
              </div>
            </Link>
          </div>
        ))}
```
next.config.js configuration - 
images: {
      domains: ["s3.us-west-2.amazonaws.com","127.0.0.1"],
      formats: ['image/webp','image/avif'],
    },
. 
error detail - 
Request URL:

https://www.webstackpros.net/_next/image/?url=https%3A%2F%2Fs3.us-west-2.amazonaws.com%2Fwebstackstatic.webstackpros.net%2Fab69c81b-b2e3-4d65-b216-1355af4d82e6%2FzLCDwjCeKwQjpCJVoFNlLo%2F6SnMnTob0diEpH7LvNms18PHXcH.webp&w=640&q=20
Request Method:
GET
Status Code:
400 Bad Request
Remote Address:
[2600:9000:253f:1e00:18:68bd:400:93a1]:443
Referrer Policy:
strict-origin-when-cross-origin. 
response of the error - Unsupported image format.

just 5 hour ago when i last checked the site was running 5 hour later with out even deploying anything error given. 

one thing to mention , Images inside <Image /> tag is only not rendering, ckeditor uploaded images are working fine .
can anyone please help me to resolve the issue?

### Current vs. Expected behavior

Images should need to render because i have not done anything wrong , or did not made any changes to backend server . donot know what cusing the error

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating system
server compute - AWS Amplify,
local Compute - Ubuntu 22.04

"dependencies": {
    "@types/dompurify": "^3.0.5",
    "@types/node-cron": "^3.0.11",
    "axios": "^1.6.1",
    "dompurify": "^3.0.6",
    "dotenv": "^16.3.1",
    "framer-motion": "^10.16.4",
    "html-react-parser": "^4.2.10",
    "isomorphic-dompurify": "^1.9.0",
    "next": "13.5.4",
    "node-cron": "^3.0.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-icons": "^4.11.0",
    "react-query": "^3.39.3",
    "react-router-dom": "^6.18.0",
    "react-toastify": "^9.1.3",
    "sharp": "^0.32.6",
    "universal-cookie": "^6.1.1"
  },
  "devDependencies": {
    "@types/node": "^20.9.0",
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.53.0",
    "eslint-config-next": "13.5.4",
    "postcss": "^8.4.31",
    "sass": "^1.69.5",
    "tailwindcss": "^3.3.5",
    "typescript": "^5.2.2"
  }
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

### Additional context

![Screenshot from 2023-11-11 10-48-48](https://github.com/vercel/next.js/assets/60233333/18f9242d-cbd6-48e8-bdcb-b243f258bd63)

**Comment by WoongE** [comment]
I am suffering this issue, too. Help me please.

**Comment by leonanderson88** [comment]
I have the same issue.
Exactly as described above, it was working fine and then as of 2 days ago it stopped working during a routine deploy of new page content. No upgrade to environment or packages. 

Hosting on AWS Amplify. I have tried versions 14.0.3, 13.5.6 and 13.4.12. No luck with any of them.

The error output from CoudWatch Logs reports
`The requested resource isn't a valid image for /company_logo. jpg received text/html; charset-utf-8`

The error is thrown from next/dist/server/image-optimizer.js on roughly line 569.

The image-optimizer.js file uses the following lines to retrieve non absolute images. 
It might have something to do with the way the mock request but not sure.

The Image Optimization works for externally hosted images. I have tried it using images hosted with Stripe.com by adding the remotePatterns. 

It just doesn't work for relative images.  

> try {
            const mocked = (0, _mockrequest.createRequestResponseMocks)({
                url: href,
                method: _req.method || "GET",
                headers: _req.headers,
                socket: _req.socket
            });
            await handleRequest(mocked.req, mocked.res, _url.default.parse(href, true));
            await mocked.res.hasStreamed;
            if (!mocked.res.statusCode) {
                console.error("image response failed for", href, mocked.res.statusCode);
                throw new ImageError(mocked.res.statusCode, '"url" parameter is valid but internal response is invalid');
            }
            upstreamBuffer = Buffer.concat(mocked.res.buffers);
            upstreamType = detectContentType(upstreamBuffer) || mocked.res.getHeader("Content-Type");
            const cacheControl = mocked.res.getHeader("Cache-Control");
            maxAge = cacheControl ? getMaxAge(cacheControl) : 0;
        } catch (err) {
            console.error("upstream image response failed for", href, err);
            throw new ImageError(500, '"url" parameter is valid but upstream response is invalid');
        }
if (upstreamType) {
        upstreamType = upstreamType.toLowerCase().trim();
        if (upstreamType.startsWith("image/svg") && !nextConfig.images.dangerouslyAllowSVG) {
            console.error(`The requested resource "${href}" has type "${upstreamType}" but dangerouslyAllowSVG is disabled`);
            throw new ImageError(400, '"url" parameter is valid but image type is not allowed');
        }
        const vector = VECTOR_TYPES.includes(upstreamType);
        const animate = ANIMATABLE_TYPES.includes(upstreamType) && (0, _isanimated.default)(upstreamBuffer);
        if (vector || animate) {
            return {
                buffer: upstreamBuffer,
                contentType: upstreamType,
                maxAge
            };
        }
        if (!upstreamType.startsWith("image/") || upstreamType.includes(",")) {
            console.error("The requested resource isn't a valid image for", href, "received", upstreamType);
            throw new ImageError(400, "The requested resource isn't a valid image.");
        }
    }

**Comment by leonanderson88** [comment]
The error is thrown from next/dist/server/image-optimizer.js on roughly line 569. When it reads text/html instead of image/* mime type.

Something about the way it is reading the files from the server isn't right. Perhaps the mock request. The files are being read into the buffer but the mime type isn't correct.

**Comment by ChoiYongWon** [comment]
have you solve this problem?

**Comment by ilhamkukuh** [comment]
same issue with me

**Comment by WendaoLee** [comment]
This was just a annotaion for anyone who just want to use `<Image>`  showing images without optimization from the components:

A bad solution(really bad,so I donnot think it was a solution) may help is add [unoptimized](https://nextjs.org/docs/pages/api-reference/components/image#unoptimized) props to the `<Image>`,which disable the `<Image>`'s optimization。

**Comment by styfle** [comment]
This sound similar to another issue that was fixed on canary 

- See https://github.com/vercel/next.js/issues/59123#issuecomment-1921730080

**Comment by styfle** [comment]
Since the links from the original post no longer work, I'm going to close this since there is no way to verify.

- (this is 404 Not Found) https://github.com/RajrupDasid/nextjs_resume_blog_symmetrical-system/issues/59
- (this is DNS_PROBE_FINISHED_NXDOMAIN) https://www.webstackpros.net/_next/image/?url=https%3A%2F%2Fs3.us-west-2.amazonaws.com%2Fwebstackstatic.webstackpros.net%2Fab69c81b-b2e3-4d65-b216-1355af4d82e6%2FzLCDwjCeKwQjpCJVoFNlLo%2F6SnMnTob0diEpH7LvNms18PHXcH.webp&w=640&q=20
