### ISSUE TITLE
Next.js 14.0.2 'Request is not defined'

### ISSUE THREAD

**Issue by fabriciolak** [vercel/next.js#58339]
### Link to the code that reproduces this issue

https://github.com/fabriciolak/devstore

### To Reproduce

1. Install `next@14.0.2`
2. Run `npm run dev`.
3. Observe the "Request is not defined" error in the console.

### Current vs. Expected behavior

Bug Description: When running the "next dev" script from the package.json file in a project using Next.js version 14.0.2, an error occurs stating "Request is not defined". 

Expected Behavior: When running the "next dev" script, the development server should start without any errors.

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home Single Language
Binaries:
  Node: 16.20.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.2
  eslint-config-next: 14.0.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by mwskwong** [comment]
The min. Node.js version of Next.js has been bumped to v18, while you are using v16.

**Comment by fabriciolak** [comment]
> The min. Node.js version of Next.js 14 has been bumped to v18, while you are using v16.

Oh. I was not aware of the version I was using. Closing issue.
