### ISSUE TITLE
next-forms won't build

### ISSUE THREAD

**Issue by briangflett** [vercel/next.js#58499]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3-canary.9
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

next-forms

### What browser are you using? (if relevant)

N/A

### How are you deploying your application? (if relevant)

N/A

### Describe the Bug

npm run build fails with the message 
./app/add-form.tsx
Attempted import error: 'experimental_useFormState' is not exported from 'react-dom' (imported as 'useFormState').

I tried upgrading to a more recent version of react-dom, and I it did recognize useFormState, but then it gave me a the error
Type error: No overload matches this call.

___________________________________________________________________________________________________________________________________
Complete message for the first test ...
> build
> next build

   ▲ Next.js 14.0.3-canary.9

 ⚠ Compiled with warnings

./app/add-form.tsx
Attempted import error: 'experimental_useFormState' is not exported from 'react-dom' (imported as 'useFormState').

Import trace for requested module:
./app/add-form.tsx

   Linting and checking validity of types  ..Failed to compile.

./app/add-form.tsx:3:10
Type error: '"react-dom"' has no exported member named 'experimental_useFormState'. Did you mean 'experimental_useFormStatus'?

  1 | 'use client'
  2 |
> 3 | import { experimental_useFormState as useFormState } from 'react-dom'
    |          ^
  4 | import { useFormStatus } from 'react-dom'
  5 | import { createTodo } from '@/app/actions'

___________________________________________________________________________________________________________________________________
Complete message for the second test ...
> build
> next build

   ▲ Next.js 14.0.3-canary.9
   - Environments: .env

 ✓ Creating an optimized production build
 ✓ Compiled successfully
   Linting and checking validity of types  ...Failed to compile.

./app/add-form.tsx:22:31
Type error: No overload matches this call.
  Overload 1 of 2, '(action: (state: { message: string; }) => { message: string; } | Promise<{ message: string; }>, initialState: { message: string; }, permalink?: string | undefined): [state: { message: string; }, dispatch: () => void]', gave the following error.
    Argument of type '(prevState: any, formData: FormData) => Promise<{ message: string; }>' is not assignable to parameter of type '(state: { message: string; }) => { message: string; } | Promise<{ message: string; }>'.
      Target signature provides too few arguments. Expected 2 or more, but got 1.
  Overload 2 of 2, '(action: (state: { message: string; }, payload: FormData) => { message: string; } | Promise<{ message: string; }>, initialState: { message: string; }, permalink?: string | undefined): [state: ...]', gave the following error.
    Argument of type '{ message: null; }' is not assignable to parameter of type '{ message: string; }'.
      Types of property 'message' are incompatible.
        Type 'null' is not assignable to type 'string'.

  20 |
  21 | export function AddForm() {
> 22 |   const [state, formAction] = useFormState(createTodo, initialState)
     |                               ^
  23 |
  24 |   return (
  25 |     <form action={formAction}>

### Expected Behavior

It should build successfully

### To Reproduce

npm run build

**Comment by briangflett** [comment]
To get this to build successfully I needed to upgrade react and react-dev to the canary versions, and add this code to the add-form and delete-form modules...

const initialState = {
  message: "inital state",
  formData: null,
}

**Comment by jaloveeye** [comment]
I solved it by doing the following
`useFormState<State, FormData>`

dependencies
 - next 14.0.3
