### ISSUE TITLE
Layouts of root level parallel routes do not render properly

### ISSUE THREAD

**Issue by jfangrad** [vercel/next.js#58506]
### Link to the code that reproduces this issue

https://github.com/jfangrad/parallel-routes-issue/

### To Reproduce

1. Start the application in development
2. Notice the UI shows only 
![Screenshot 2023-11-15 at 2 09 35 PM](https://github.com/vercel/next.js/assets/11445215/5363c930-b0e9-47d9-a7ce-fe32f8d14959)

3. Change the value of `isRoute1` in `src/app/layout.tsx` to `false` and save
4. Notice the UI now shows 
![Screenshot 2023-11-15 at 2 10 29 PM](https://github.com/vercel/next.js/assets/11445215/d9c77414-57da-4324-ac8d-13d8e53b12ad)

### Current vs. Expected behavior

Following the steps above, at **step 2** I expected to see output of
```
Test route 1 layout
Page 1 content
```

But instead only saw output of
```
Page 1 content
```

For some reason the layout for `route1` parallel route is being ignored but the layout for `route2` is not.

A bandaid solution that allowed both layouts to render properly was to put a `(default)` (or any group name) route group as the direct child of each parallel route and then place all files inside that route group. For some reason this change allows the layout for both parallel routes to work.

**Note:** Ran with both `14.0.2` and `^14.0.3-canary.9` but saw the same output.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.3-canary.9
  eslint-config-next: 14.0.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tried recreating in a sandbox but the I could not reproduce in that enviroment.

However I was able to produce this bug in more than one next project (one on v13 and and clean slate v14)

**Comment by LucasHang** [comment]
I'm expriencing the same bug in Next@14.0.2

I have that structure:
![image](https://github.com/vercel/next.js/assets/38769565/3c242dfe-7001-435d-9f34-50956e36b4bf)

The only layout that seems to be loaded correctly is @operation:
![image](https://github.com/vercel/next.js/assets/38769565/8fa2933b-d840-4e8b-b192-1aab398d15bd)

When redirecting to @business, it loads almost correctly, but using @operation layout metadata.

When redirecting to @admin, it also uses @operation layout, but this time it does not load the components of the layout:
![image](https://github.com/vercel/next.js/assets/38769565/d0457cba-43aa-4493-a587-86d69a7060fa)

**Comment by ztanner** [comment]
Hi there,

Parallel routes are meant to be used within a shared layout. We do not currently support creating a separate `layout.tsx` file per slot. The valid files for a slot are `error`, `loading`, `default`, and `page`. 

Could you clarify the use-case behind having a layout for your slot?

**Comment by LucasHang** [comment]
I suppose we thought that parallel routes could be used for complex and "root" cases, like having a @public and @admin wich one with its layout.tsx, children and routes. But, as you clarified, it is meant to be used only for simpler cases that results in a page.tsx instead of a complex structure. Is that right?

**Comment by pingustar** [comment]
> Hi there,
> 
> Parallel routes are meant to be used within a shared layout. We do not currently support creating a separate `layout.tsx` file per slot. The valid files for a slot are `error`, `loading`, `default`, and `page`.
> 
> Could you clarify the use-case behind having a layout for your slot?

the conditional rendering example in the documentation suggests otherwise.

https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#conditional-routes

in this example you have dashboard and login ... which I need different layouts for.

**Comment by LucasHang** [comment]
> > Hi there,
> > Parallel routes are meant to be used within a shared layout. We do not currently support creating a separate `layout.tsx` file per slot. The valid files for a slot are `error`, `loading`, `default`, and `page`.
> > Could you clarify the use-case behind having a layout for your slot?
> 
> the conditional rendering example in the documentation suggests otherwise.
> 
> https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#conditional-routes
> 
> in this example you have dashboard and login ... which I need different layouts for.

I agree that this example creates a false expectative of using parallel routes for complex and ramificated use cases.
But looking now, I guess that they are trying to show a root path (like "/home") that can show login or dashboard given the user auth state, while the other supposable routes are not **under** this layouts (a logic checking authentication would end up redirecting an unathorized user to the root path, that would show login page, for example).

So we can imagine something like:
- path "/home" (shows dashboard or login)
- path "/anything" (shows anything)

The layout where parallel routes are defined is under "home" folder. Thereby "/anything" is a independent route, not under parallel logic.
