### ISSUE TITLE
Custom cache handler doesn't work with ESM

### ISSUE THREAD

**Issue by kevva** [vercel/next.js#58509]
### Link to the code that reproduces this issue

https://github.com/kevva/next-cache-handler-issue

### To Reproduce

1. Run `npm run dev`
2. A `ERR_REQUIRE_ESM` error is thrown

### Current vs. Expected behavior

I expect the app to run/build in ESM, not crash.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64
Binaries:
  Node: 20.8.0
  npm: 10.2.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.2
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

**Comment by karlhorky** [comment]
Currently, ESM projects and JavaScript don't work so well with Next.js. There are a few different open issues.

If you generate a fresh `create-next-app` app and then add `"type": "module"`, it crashes right away:

- https://github.com/vercel/next.js/issues/54777
