### ISSUE TITLE
ES6 imports in Tailwind config crashes as postcss-loader treats it as CJS module

### ISSUE THREAD

**Issue by Gryso** [vercel/next.js#58538]
### Link to the code that reproduces this issue

https://github.com/Gryso/tailwind-es6-imports

### To Reproduce

1. npm run dev
2. project crashes right away

### Current vs. Expected behavior

As tailwind support es6 modules it should be possible to import another es6 modules, but project crashes with 
```
./src/app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./src/app/globals.css
Error: Cannot find module '@/testPlugin'
Require stack:
- /home/potato/workspace/tailwind-es6-imports/tailwind.config.ts
Import trace for requested module:
./src/app/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./src/app/globals.css
./src/app/globals.css

```

Both tailwind and postcss should be supporting ES6 modules at this point so i think problem is somewhere in next configuration.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.17
  pnpm: N/A
Relevant Packages:
  next: 14.0.3-canary.9
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

- I also tried `type:module` in package.json with postcss.config as `cjs` also with postcss config removed and defined only in package.json but that did not work either
- I managed to make it work by exporting testPlugin as commonJS module but i really hate to mix them.
- I saw [video](https://www.youtube.com/watch?v=QJlTWj30krw) of someone doing similar thing and it worked for him so it seems it was functional at some point but i do not know what versions was he running on as he used shadcn template 5 months ago.

**Comment by JesseKoldewijn** [comment]
Are you sure it doesn't have anything to do with the import alias usage? Have you tried a relative path import instead as well?

**Comment by Gryso** [comment]
Yes you are right. It did not occur to me at all that aliases might be the problem. I just let editor do its thing. Can you explain what is the issue with aliases here. (I have file included in tsconfig in my actual project it still does not work)

**Comment by JesseKoldewijn** [comment]
Nonetheless in all ways this inherently isn't an issue on the Next.js end and think this issue therefore should be closed. And glad to hear ya got it to work with an alternative import btw🤙
