### ISSUE TITLE
Invalid Cache-Control duration provided for 404 page at _next/data path

### ISSUE THREAD

**Issue by Yizhachok** [vercel/next.js#58548]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/vigorous-silence-l8p7rj

### To Reproduce

Unfortunately, I can't guarantee that this steps will help to reproduce the issue because we can't get this error even on stage environment while testing before prod. The reason I think is that there are not such heavy traffic as we have on prod server and cache behaviour is used more intensively. But main steps look like this:

1. Deploy application on prod environment
2. Open page in browser
3. Rebuild and redeploy application
4. Move mouse over example link (trigger prefetch for not existent data path like /_next/data/5wiVU6nBdrKfod9WX7DSQ/test-path.json)

### Current vs. Expected behavior

**Currently**

Periodically server throw such error in console (not for every 404 paths but for /_next/data/* as I have found). JSON output at bottom this is custom log to find URL that trigger error.

<img width="823" alt="Server error" src="https://github.com/vercel/next.js/assets/1171048/0bd4e863-4493-4608-97bb-d1eeeaf36f63">

**Expected**

Server responds with 404 page without errors for any not existed path.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020
Binaries:
  Node: 18.13.0
  npm: 8.19.3
  Yarn: 1.22.19
  pnpm: 7.2.1
Relevant Packages:
  next: 14.0.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I have migrated from 13.4.10 to 14.0.1. Tested upgraded site for 1 week on dev and stage env and didn't reach this issue. After new version has been deployed to prod env, we started to see such error very intensively.

I have found that in `packages/next/src/server/base-server.ts` in 14.0.0 has been added this code

```js
      // If the cache entry has a revalidate value that's a number, use it.
      else if (typeof cacheEntry.revalidate === 'number') {
        if (cacheEntry.revalidate < 1) {
          // This is added code for debug purposes (message from here exist in screenshot)
          console.error(JSON.stringify({url: req.url, pathname: pathname}));
          throw new Error(
            `Invariant: invalid Cache-Control duration provided: ${cacheEntry.revalidate} < 1`
          )
        }

        revalidate = cacheEntry.revalidate
      }
```

But in code above we have

```js
      // If this is a preview mode request, we shouldn't cache it. We also don't
      // cache 404 pages.
      if (isPreviewMode || (is404Page && !isDataReq)) {
        revalidate = 0
      }
```

and in code at the bottom we have

```js
cacheEntry.revalidate = revalidate
```

And that's why (I think so) sometimes we have `typeof cacheEntry.revalidate === 'number'` == true and `cacheEntry.revalidate < 1` == true in one of next requests.

For now I see hotfix solution for my project in removing of this condition (because it didn't get this error in any other cases).

**Comment by lindseybradford** [comment]
We're also experiencing this issue.

**Comment by Yizhachok** [comment]
The problem is not reproducing in 14.1.0.
