### ISSUE TITLE
Headers are no longer part of the request in release 14.0.2.

### ISSUE THREAD

**Issue by nordicgit70** [vercel/next.js#58542]
### Link to the code that reproduces this issue

https://github.com/nordicgit70/nextjs-app

### To Reproduce

1. Start the application in dev mode.
2. Open the default page.
3. Check the header printed in the terminal log.

### Current vs. Expected behavior

My use-case was using `x-invoke-path` which is no longer available. Currently no header contains the URL path.
Several other headers are no longer available after my upgrade from 13.4.12 to 14.0.2.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Windows x64.
Node 18.18.2
npm 9.8.
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Additional context

This is an undocumented and breaking change. Without the path I cannot set metadata on the server.

```
host localhost:3000
user-agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
accept text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
accept-language en-US,en;q=0.5
accept-encoding gzip, deflate, br
connection keep-alive
cookie appSession=....
upgrade-insecure-requests 1
sec-fetch-dest document
sec-fetch-mode navigate
sec-fetch-site none
sec-fetch-user ?1
x-forwarded-host localhost:3000
x-forwarded-port 3000
x-forwarded-proto http
x-forwarded-for ::ffff:127.0.0.
```

**Comment by nordicgit70** [comment]
The related issue https://github.com/vercel/next.js/issues/46618 was closed. A use-case to have the path available in React Server Component and/or during SSR is to be able set meta-data.

**Comment by timneutkens** [comment]
x-invoke-path or anything like it was accidentally part of the headers, not a public api and not something you can rely on. Going to close this issue as it's about internals changing.

**Comment by nordicgit70** [comment]
@timneutkens I ask you to re-open as also the `next-url` is missing. 
What is otherwise the recommended approach to get the URL path on the server in `generateMetadata`?

**Comment by nordicgit70** [comment]
Link to similar issue https://github.com/vercel/next.js/issues/43704.
