### ISSUE TITLE
A NextRequest error occurs when starting with npm run dev after nextjs version 14

### ISSUE THREAD

**Issue by 202780181** [vercel/next.js#58563]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
macOs 13.5.2
node: v16.16.0
npm: 8.11.0 
nextJs: 14.0.3
```

### Which example does this report relate to?

ReferenceError: Request is not defined

### What browser are you using? (if relevant)

Chrome 119.0.6045.123

### How are you deploying your application? (if relevant)

npm run dev

### Describe the Bug

run dev with npm and the Request is not defined

![image](https://github.com/vercel/next.js/assets/27540653/2417c2e9-5d5e-4300-9fde-8270ab533d00)

### Expected Behavior

The dev service works properly

### To Reproduce

There was an issue after starting the cli using the next official step, but I was able to run it properly after switching to version 13

**Comment by zeyios** [comment]
![image](https://github.com/vercel/next.js/assets/10176630/1ea5b10d-a469-4ae3-ae5e-d7229af89aca)

**Comment by 202780181** [comment]
Got it. Thanks
