### ISSUE TITLE
cli build summary mentions getStaticProps even in app router only projects

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#58602]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js/tree/canary/packages/create-next-app

### To Reproduce

1. `pnpm create next-app .`
2. `pnpm install && pnpm run build`
3. see SSG "uses getStaticProps":

```
○  (Static)   prerendered as static content
●  (SSG)      prerendered as static HTML (uses getStaticProps)
λ  (Dynamic)  server-rendered on demand using Node.js
```

### Current vs. Expected behavior

expected: no mention of `getStaticProps` when pages router is not used

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #202310102154 SMP PREEMPT_DYNAMIC Tue Oct 10 22:00:30 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.10.5
Relevant Packages:
  next: 14.0.4-canary.2
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

**Comment by balazsorban44** [comment]
Here is my output:
```
> next build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
 ✓ Generating static pages (5/5) 
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    5.13 kB        89.3 kB
└ ○ /_not-found                          885 B          85.1 kB
+ First Load JS shared by all            84.2 kB
  ├ chunks/184-d3bb186aac44da98.js       28.9 kB
  ├ chunks/30b509c0-f3503c24f98f3936.js  53.4 kB
  └ other shared chunks (total)          1.87 kB


○  (Static)  prerendered as static content
```

You might be on an older version of Next.js try running `pnpm create next-app@latest` to make sure that CNA is not stuck on a stale version. If you still see this issue then, you can open a new bug report, but please provide your code as the reproduction so we can investigate. Thanks!
