### ISSUE TITLE
Combination of dynamic routes, folder grouping and rewrites doesn't work on Vercel

### ISSUE THREAD

**Issue by SergeySypalo** [vercel/next.js#58628]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/cocky-blackburn-gd4fc5

### To Reproduce

I have a page app\(articles)\(movies)\genres\[genre]\page.js

```
import MovieList from '../../../../../components/movie-list'

import posts from '../../../../../data/posts'
import movies from '../../../../../data/movies'

export async function generateStaticParams() {	
	return [...new Set(movies.flatMap(movie => movie.genre))].map(genre => ({'genre': `best-${genre}-movies`}))   
}

export default function Posts({ params }) {
   const post = posts.find(post => post.slug == params.genre)	
	return <>      
		<MovieList post={post} genre={params.genre.replace('best-','').replace('-movies','')} />
	</>
}
```

and here is my next.config.js

```
const movies = require('./data/movies')

module.exports = {	
	images: {
		formats: ['image/avif', 'image/webp'],
	},
	async rewrites() {
		const rewrites = [...new Set(movies.flatMap(movie => movie.genre))].map(genre => ({
			source: `/best-${genre}-movies`,
			destination: `/genres/best-${genre}-movies`,
		}))		

		return rewrites
	}
}
```

### Current vs. Expected behavior

on localhost everything works as expected, but when deployed to Vercel I'm getting empty page on my website, when following a link to that page.
But if I refresh the page, or just paste a URL and press enter, the page displayed as expected.
You can check it live: https://sypalo.com/best-romance-movies, just navigate in movies section and try to refresh the page

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

tried to upgrade to NextJS 14.0.4-canary 3 - same issue on Vercel, while even on SandBox everything seems to be working

**Comment by aadarsh-nagrath** [comment]
Weird that it works locally but acts up on Vercel, huh? 🤔
pagination route conflicting with the movie genre routes
Your workaround, moving the main page pagination to a subfolder and adding rewrite rules is a bit quirky but gets the job done for now. <> Definitely agree </> This needs some proper investigation and fixing.

**Comment by SergeySypalo** [comment]
yes, as part of testing to make sure I'm not messing up with something I created a new repo
[https://github.com/SergeySypalo/nextjs14](https://github.com/SergeySypalo/nextjs14)
a new Vercel project and here you can see
before moving pagination to a subfolder:
[nextjs14-hirqhs1v8-sergeysypalo.vercel.app](https://vercel.com/sergeysypalo/nextjs14/6zwSSvTEy3WMh9nTkasp1aStzu8j)
there are text at the top left corner:
[Best comedy movies on Node 20](https://nextjs14-hirqhs1v8-sergeysypalo.vercel.app/best-comedy-movies)
[Page 2](https://nextjs14-hirqhs1v8-sergeysypalo.vercel.app/2)
when you visit each page, you wll see that each has a prefix "My blog - page" which is only in pagination

After moving pagination to a subfolder:
[nextjs14-buppd81gs-sergeysypalo.vercel.app](https://vercel.com/sergeysypalo/nextjs14/3WyMwcNmxqyUDvY5gLqsrNhxBeHF)
if you navigate to movies page you will see as expected only: best-comedy-movies

I know the example is not as ideal, but it was rather a quick test with the NextJS demo app.
