### ISSUE TITLE
Cannot catch an error when calling a server action

### ISSUE THREAD

**Issue by 4lejandrito** [vercel/next.js#58638]
### Link to the code that reproduces this issue

https://github.com/4lejandrito/next-server-action-error-issue

### To Reproduce

1. `npm i`.
2. `npm t` will reproduce it automatically. To reproduce it manually go to the next step.
3. `npm run dev`.
4. Open `http://localhost:3000` in Firefox.
5. Open the dev tools, and click on request blocking.
6. Add `localhost` as blocking pattern.
7. Click the button on the page.

### Current vs. Expected behavior

* **Expected:** Nothing happens (as there is [a catch clause](https://github.com/4lejandrito/next-server-action-error-issue/blob/main/app/component.tsx#L12C26-L12C43)).
* **Actual:** A client error next message is displayed.

In version `14.0.1` the catch clause is run, from `14.0.2` on it isn't.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:21:34 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8112
Binaries:
  Node: 18.18.1
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.5.0
Relevant Packages:
  next: 14.0.4-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Additional context

Without this I cannot show a fallback UI when a network error occurs.

<sub>[NEXT-1715](https://linear.app/vercel/issue/NEXT-1715/cannot-catch-an-error-when-calling-a-server-action)</sub>

**Comment by 4lejandrito** [comment]
This is the stacktrace of the network error when using `14.0.4-canary.6`:

```
Uncaught TypeError: NetworkError when attempting to fetch resource.
    trackUsedThenable react-dom.development.js:8585
    useThenable react-dom.development.js:11373
    use react-dom.development.js:11394
    use react.development.js:1806
    useUnwrapState use-reducer-with-devtools.js:79
    Router app-router.js:203
    renderWithHooks react-dom.development.js:11009
    updateFunctionComponent react-dom.development.js:16163
    beginWork$1 react-dom.development.js:18359
    callCallback react-dom.development.js:20461
    invokeGuardedCallbackImpl react-dom.development.js:20510
    invokeGuardedCallback react-dom.development.js:20585
    beginWork react-dom.development.js:26763
    performUnitOfWork react-dom.development.js:25587
    workLoopSync react-dom.development.js:25303
    renderRootSync react-dom.development.js:25258
    recoverFromConcurrentError react-dom.development.js:24475
    performConcurrentWorkOnRoot react-dom.development.js:24420
    workLoop scheduler.development.js:261
    flushWork scheduler.development.js:230
    performWorkUntilDeadline scheduler.development.js:534
```

**Comment by 4lejandrito** [comment]
I've added [an automated test ](https://github.com/4lejandrito/next-server-action-error-issue/blob/main/cypress/e2e/test.cy.ts)to the reproduction repo. The issue can be reproduced by running `npm test`.

**Comment by 4lejandrito** [comment]
This regression was introduced in `14.0.2-canary.7` (it works on cannary.6).

**Comment by 4lejandrito** [comment]
It seems https://github.com/vercel/next.js/pull/56497 might have caused this regression. 

I cannot show fallback UI on error now when manually calling server actions 😢 .

**Comment by LHDi** [comment]
I can reproduce as well.

**Comment by 4lejandrito** [comment]
Still reproducible on `14.0.4-canary.40`.

**Comment by 4lejandrito** [comment]
Still reproducible on `14.0.5-canary.5`.

**Comment by 4lejandrito** [comment]
Still reproducible on [v14.0.5-canary.18](https://github.com/vercel/next.js/releases/tag/v14.0.5-canary.18).

**Comment by dan-overton** [comment]
Still reproducible on `14.1.1-canary.6` . @shuding is this scheduled in to be fixed or is it a low priority? It's not a great user experience, and It's making me wonder if it's best to give server actions a little more time before we adopt them.

**Comment by abencun-symphony** [comment]
We're also seeing this issue and it's very serious, we can't recover properly on the client side without catching the exception in our case.

**Comment by 4lejandrito** [comment]
Fixed! Thanks so much!
