### ISSUE TITLE
Link prefetch not working

### ISSUE THREAD

**Issue by l-czarkowski** [vercel/next.js#58644]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/prefetch-not-work-gs3l2r

### To Reproduce

1. Go to https://gs3l2r-3000.csb.app/
2. Wait 4 seconds
3. Click on the "slow" link
4. The page did not download before clicking

![image](https://github.com/vercel/next.js/assets/151439156/77b47205-2f8d-42b7-8de7-49414f039b6d)

### Current vs. Expected behavior

after waiting 4 seconds, the page should load immediately after clicking the "slow" link

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
next@14.0.3
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Additional context

nextjs version 13.4.10 works fine

Example:
https://g9rnsc-3000.csb.app/
https://codesandbox.io/p/sandbox/prefetch-work-g9rnsc

![image](https://github.com/vercel/next.js/assets/151439156/214cc944-c3e9-46e7-8ef6-86ea37c0ac33)

**Comment by ztanner** [comment]
Hi, as described in the prefetching [docs](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#1-prefetching), dynamic routes are only prefetched up to the closest loading boundary. Because your slow page uses `headers`, it opts into dynamic rendering.
