### ISSUE TITLE
Slower page loads

### ISSUE THREAD

**Issue by dawudarif** [vercel/next.js#58652]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
Binaries:
  Node: 20.7.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

page size and slow load

### What browser are you using? (if relevant)

chrome, also tested in edge

### Describe the Bug

I have simple pages in my next app that have a bundle size of approx 12 MBs and it takes too long to load the problem is that the pages are simple from or just simply displaying data. I also removed heavy components and tested lazy loading but it still doesn't work. The code can be checked here:
` https://github.com/dawudarif/budget-manager.git`

### Expected Behavior

It is a simple budget manager nothing too complex. Well I tested the same code in react and changed nothing changed except the link components and other react equivalents and size of the pages in react just add upto in just less than a Kb and also load faster.

this one is the screenshot from using next js and the bundle sizes are more than 10 MBs (selected one and the last one)
![nextjs](https://github.com/vercel/next.js/assets/99706520/fe273da0-5f23-449a-9cee-605be9d3d774)

and this one is from react (selected one and the last one)
![react](https://github.com/vercel/next.js/assets/99706520/aef22d02-5ea3-4807-bbe6-41f5cb8b4832)

you can check there is a huge difference b/w sizes, the load times in react are in milliseconds and in next js they are in like 8-10 seconds.

### To Reproduce

` https://github.com/dawudarif/budget-manager.git`

**Comment by Cow258** [comment]
You can check the bundle by using `https://www.npmjs.com/package/@next/bundle-analyzer` to figure out why the size is so big

**Comment by timneutkens** [comment]
You have to check production bundle size by running `npm run build` and then `npm run start`. In development, which is what these screenshots are (i.e. includes webpack-hmr line), there are no optimizations enabled.
