### ISSUE TITLE
AWS ECS Docker deploy not working due to HOSTNAME env variable being overridden

### ISSUE THREAD

**Issue by samshelley** [vercel/next.js#58657]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.3
Next.js Config:
  output: standalone
```

### Which example does this report relate to?

with-docker

### Describe the Bug

#44627 allowed the user to specify a `$HOSTNAME` environment variable. This seems to break deployment to AWS ECS unless you explicitly set `HOSTNAME=0.0.0.0` in the task definition configuration because by default the AWS ECS instance sets $HOSTNAME to what looks to be the container id.

The `with-docker` example has been updated to include:
`ENV HOSTNAME "0.0.0.0"`

This, however, does not seem to work as `0.0.0.0` is the default value and so it can still be overwritten (which it is by AWS) to the container id. The only fix I have found to work is to explicitly set the environment variable in the task.

I'm not sure the best way to fix this, maybe just document the behavior? I am unfamiliar with a method in a docker that lets you set an environment variable such that it _can't be overriden_. One way to fix it would be to change the variable name to `NEXT_HOSTNAME`, but is it too late given that this already shipped?

### Expected Behavior

Running the standalone server app with `node server.js` should start the server. Instead you get the error message described in this comment: https://github.com/vercel/next.js/issues/54093#issuecomment-1684912389

### To Reproduce

Deploy the with-docker container example to ECS with the latest version of next.js

**Comment by padupuy** [comment]
Hi @samshelley ! 
With ECS you can override the HOSTNAME with a parameter , see the doc : 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#ContainerDefinition-hostname

i.e : 

```
"ECS_SERVICES": {
                COMMON['application_name']: {
                    "ECSType": "FARGATE",
                    "ContainerCpu": "1024",
                    "ContainerMemory": "4096",
                    "ExposedPort": 80,
                    "Envvars": {
                        "HOSTNAME": "0.0.0.0"
                    }
                }
            },

```

**Comment by samshelley** [comment]
> Hi @samshelley ! With ECS you can override the HOSTNAME with a parameter , see the doc : https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#ContainerDefinition-hostname
> 
> i.e :
> 
> ```
> "ECS_SERVICES": {
>                 COMMON['application_name']: {
>                     "ECSType": "FARGATE",
>                     "ContainerCpu": "1024",
>                     "ContainerMemory": "4096",
>                     "ExposedPort": 80,
>                     "Envvars": {
>                         "HOSTNAME": "0.0.0.0"
>                     }
>                 }
>             },
> ```

Thanks @padupuy -- I actually did do this to resolve the issue for myself. Just trying to help others to save them time since the `with-docker` example as written doesn't work out of the box.

**Comment by hhokaribonx** [comment]
@padupuy Is fargate considered here(just querying)? because right there in the section of your link, it states:
> If you're using the awsvpc network mode, the hostname parameter isn't supported.

and fargate only supports awsvpc mode.

**Comment by samshelley** [comment]
I think the link provided might actually be unrelated to the issue. In my experience the issue is that there is an environment variable (`HOSTNAME`) set automatically be AWS that needs to be overridden. I did this in FARGATE and it solve the problem.

**Comment by padupuy** [comment]
> @padupuy Is fargate considered here(just querying)? because right there in the section of your link, it states:
> 
> > If you're using the awsvpc network mode, the hostname parameter isn't supported.
> 
> and fargate only supports awsvpc mode.

@hhokaribonx I'm sorry, but I have no idea about this.

**Comment by fursich** [comment]
Just stumbled upon this. We ended up specifying HOSTNAME env var when launching server.js process.

On the Dockerfile ([official sample here](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile)):

```diff
# set hostname to localhost
- ENV HOSTNAME "0.0.0.0"

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
- CMD ["node", "server.js"]
+ CMD HOSTNAME="0.0.0.0" node server.js
```

I'll be submitting a PR to update these samples - hope that helps!

**Comment by monim67** [comment]
I got it working setting up `HOSTNAME` environment variable on fargate task definition, cdk code below:

```ts
      taskImageOptions: {
        family: props.projectName,
        image: ContainerImage.fromEcrRepository(repository),
        containerPort: 3100,
        environment: { PORT: "3100", HOSTNAME: "0.0.0.0" },
      },
```

**Comment by fursich** [comment]
Just wanted to thank you everyone for positing/addressing this issue, which gave me a hint for the reason why my nextjs container is not properly running.

For those who might come across the issue in the future, I'd propose you to follow [the instruction here](https://github.com/vercel/next.js/issues/58657#issuecomment-1862128656).

(the official doc is updated with #59756 , but that doesn't mean *your dockerfile* reflects that change..)

You could also tweak HOSTNAME to listen on your infrastructure (e.g. changing ecs task definition as suggested), but please be aware that it might not be a fundamental solution for long run.
HOSTNAME env var setting in your dockerfile is not working as it is, so you might have trouble once the nextjs changes how to treat default hostname fallback internally (as [clearly explained above](https://github.com/vercel/next.js/issues/58657#issuecomment-1847389728))

Hope it helps somebody's day :)

**Comment by bestickley** [comment]
>  Is fargate considered here(just querying)? because right there in the section of your link, it states...

@hhokaribonx, this comment threw me off, because you're right that the AWS Docs state that Fargate doesn't support `hostname` as a _Container Definition Parameter_, BUT Fargate does support `HOSTNAME` as an environment variable as evidenced by others who have commented on this issue.

Could you please strike through or correct your comment above so it doesn't lead other astray? Thanks!
