### ISSUE TITLE
Reading search params through useSearchParams() hook causes multiple reenders

### ISSUE THREAD

**Issue by juliomuhlbauer** [vercel/next.js#58684]
### Link to the code that reproduces this issue

https://github.com/juliomuhlbauer/use-search-param-ark

### To Reproduce

1. Go to: https://use-search-param-ark.vercel.app/search-param
2. Open the console
3. Change the select value
4. Check the reenders in console

### Current vs. Expected behavior

Following the steps above, it should render only 1 time after updated.
It is reender like 300-400 times.

https://github.com/vercel/next.js/assets/53458125/78477ffd-8ace-4816-9782-6201c465bb7d

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.18.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.5
  eslint-config-next: 14.0.4-canary.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

**Comment by N-Ziermann** [comment]
I've taken a look at your example and saw that your actually isn't with next.js, but with the fact that you pass props to your select elements that are recreated every render.
The "defautValue" and the items object both get recreated every time the component rerenders, thus causing another render.
I've also forked your repo to show you a possible solution.
Here you go: https://github.com/juliomuhlbauer/use-search-param-ark/commit/58ca6ffd706dbbe97cad9e78aa0c1cbf751d3de6

**Comment by juliomuhlbauer** [comment]
Thanks!
But as this is setting the defaultValue, it doesn't track back and forth navigation.
I made an example using as a value: https://use-search-param-ark.vercel.app/search-param-value
But with useMemo without deps, it wouldn't work, because it doesn't update.

**Comment by N-Ziermann** [comment]
Considering that your own code works perfectly fine (including the forward and backward navigation actions) when you replace the Ark Select Tag with a vanilla HTML Select Tag, I'm pretty sure the issue isn't with next.

Just replace your select with this:

        <select
          value={selectedCity ?? undefined}
          onChange={(e) => {
            console.log('changed to:', e.target.value);
            const params = new URLSearchParams(searchParams);

            params.set('city', e.target.value);

            router.push(`/search-param?${params.toString()}`);
          }}
        >
          {items.map((item) => (
            <option key={item.value} value={item.value}>
              {item.label}
            </option>
          ))}
        </select>

And you should have a working example.

**Comment by iamhectorsosa** [comment]
@juliomuhlbauer did you had any luck with this issue? I'm pretty sure this is a next situation. I'm using barebones Next app and I'm encountering the same issue.

**Comment by iamhectorsosa** [comment]
I actually tested this with Radix and encountered this problem. I replaced the same component with Vite and all good

**Comment by juliomuhlbauer** [comment]
Can you share a reproduction?
