### ISSUE TITLE
Since v14.0.2, using revalidatePath in nested Parallel Routes prevents router.back from functioning

### ISSUE THREAD

**Issue by zaru** [vercel/next.js#58715]
### Link to the code that reproduces this issue

https://github.com/zaru/nested-parallel-routes

### To Reproduce

1. Click the "Open drawer" button.
2. Click the "Open modal" button.
3. Click the "Revalidate submit" button.
4. The modal is expected to close but does not close.

### Current vs. Expected behavior

Executing router.back() is expected to clear the Slot of Parallel Routes and close the modal, but in reality, the modal does not close. However, the URL and History do go back one step.

This unexpected behavior occurs when revalidatePath() is executed within ServerActions.

https://github.com/zaru/nested-parallel-routes/blob/c459d5d2b7425b5cc9b7c44cada8e001de02c5f4/src/app/%40modal/modal/action.ts#L7

I can close the modal when I don't execute revalidatePath(), but I'm having trouble updating the screen to the latest version without it.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.12.1
  npm: 9.6.6
  Yarn: 3.6.3
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.6
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

This was working correctly in Next.js versions prior to v14.0.1.

**Comment by zaru** [comment]
"Unexpected behavior" refers to the modal not closing.
https://github.com/vercel/next.js/assets/235650/eec2fe0d-d8f0-4bd7-a811-645a33a1c494

"Expected behavior" refers to the modal closing as intended.
https://github.com/vercel/next.js/assets/235650/e80325ae-8648-4a9a-ae34-eb0503763005

**Comment by scastiel** [comment]
I’m having the same issue with `14.0.4` and `14.0.5-canary.14`. The code is working fine with `14.0.1`. 😢

**Comment by michaelcummings12** [comment]
Having this issue with 14.0.5-canary.16. It ** looked ** like it was supposed to be fixed in .15, but doesn't appear so. 

https://github.com/vercel/next.js/pull/59585

14.0.1 is the last working version for me.

**Comment by sinafath** [comment]
same issue on 14.0.5-canary.18

**Comment by jasonbert** [comment]
I think this behaviour may be related to the issue described here, difference is I'm revalidating by tag.

I've got a modal displaying a blog post coming from a parallel/intercepted route, which has a "favourite" (heart) toggle button that calls a server action and revalidates the cache by tag. When "closing" the modal (`router.back()`), the route changes but doesn't remove the modal.

1) Trigger modal/parallel/intercepted route by clicking on blog link (`next/link`).
![image](https://github.com/vercel/next.js/assets/2347572/45a3ea50-44ab-48c1-9902-676f4ae14ae9)

2) Click on "favourite" toggle button, triggers server action and revalidates by tag.
![image](https://github.com/vercel/next.js/assets/2347572/cda2932c-eb38-4dcd-9bf5-ab2b8642cf52)

3) Click on "close" (X) button to close the modal (`router.back()`). **The route has changed, but the modal hasn't been removed.**
![image](https://github.com/vercel/next.js/assets/2347572/670a2b91-9689-4757-b56d-c408a426be88)


Modal Component
```typescript
'use client'

import { useRouter } from "next/navigation";
import React, { MouseEventHandler, PropsWithChildren, useCallback, useEffect, useRef } from 'react';
import { Heading2 } from '../heading';
import styles from './index.module.scss';

interface ModalProps extends PropsWithChildren {
    header?: string | React.ReactNode
    footer?: React.ReactNode
    onClose?: () => void
}

export default function Modal({ children, header, footer, onClose }: ModalProps) {
    const overlay = useRef(null);

    const handleClose = useCallback(() => {
        if (onClose) onClose();
    }, [onClose]);

    const handleClick: MouseEventHandler = useCallback((e) => {
        if (onClose && e.target === overlay.current) {
            onClose();
        }
    }, [onClose]);

    const handleKeyDown = useCallback((e: KeyboardEvent) => {
        if (onClose && e.key === "Escape") onClose();
    }, [onClose]);

    useEffect(() => {
        document.addEventListener("keydown", handleKeyDown);
        return () => document.removeEventListener("keydown", handleKeyDown);
    }, [handleKeyDown]);

    return (
        <div ref={overlay} className={styles.Modal} onClick={handleClick}>
            <div className={styles.Modal__container}>
                <div className={styles.Modal__header}>
                    {header &&
                        <div className={styles.Modal__headerContent}>
                            {typeof header === 'string' ?
                                <Heading2>{header}</Heading2> :
                                header
                            }
                        </div>
                    }
                    <div className={styles.Modal__headerClose}>
                        <button onClick={handleClose} className={styles.Modal__headerCloseButton}>X</button>
                    </div>
                </div>
                <div className={styles.Modal__content}>
                    {children}
                </div>
                {footer &&
                    <div className={styles.Modal__footer}>
                        <div className={styles.Modal__footerContent}>
                            {footer}
                        </div>
                    </div>
                }
            </div>
        </div>
    )
}

export function RouterModal(props: ModalProps) {
    const router = useRouter();
    const handleClose = useCallback(() => {
        if (props.onClose) {
            props.onClose();
        }

        router.back();
    }, [router]);

    return <Modal {...props} onClose={handleClose} />
}
```

Action
```typescript
'use server'

export async function toggleBlogFavoriteAction(blogId: string) {
    await toggleBlogFavorite(blogId);

    revalidateTag(BLOG_FAVORITES_CACHE_TAG);
}
```

Component
```typescript
'use client';

import { startTransition, useOptimistic } from "react";
import { PrimaryButton } from "~f/framework/button";
import { toggleBlogFavoriteAction } from "./blogAction";

export default function BlogFavoriteToggleButton({ blogId, isFavorite }: { blogId: string, isFavorite: boolean }) {
    const [optimisticIsFavorite, setOptimisticIsFavorite] = useOptimistic(isFavorite);

    async function toggle() {
        startTransition(() => {
            setOptimisticIsFavorite(!optimisticIsFavorite);
        });

        await toggleBlogFavoriteAction(blogId);
    };

    return (
        <PrimaryButton onClick={toggle} style={{ minWidth: 50 }}>{optimisticIsFavorite ? '❤️' : '🖤'}</PrimaryButton>
    )
}
```

Source: https://github.com/scorado-ltd/scorado-examples-nextjs-cosmos
Next.js: `14.0.4`

**Comment by aryzle** [comment]
experiencing the same problem in 14.1.0

**Comment by aryzle** [comment]
this is looking great on the latest canary version `14.2.0-canary.48`, thank you!!
