### ISSUE TITLE
Docs: Allow people copy some specific part of code. So annoying

### ISSUE THREAD

**Issue by websorokinweb** [vercel/next.js#58739]
### What is the improvement or update you wish to see?

Allow people copy some specific part of code

### Is there any context that might help us understand?

I can only copy the full code from doc

**Comment by kelihansen** [comment]
I am also finding that I can't copy single lines of code out of the examples at https://nextjs.org/docs

**Comment by Vsevolod-Shustov** [comment]
As a temporary fix, get stylebot or any other userstyle extension and use `code * {user-select: auto}` style.

**Comment by leerob** [comment]
This might have been a bug previously, but appears to be fixed. I can copy both individual lines + click the copy button to get the whole snippet. Thank you!
