### ISSUE TITLE
10X Build Slowdown in the Latest Next.js Version

### ISSUE THREAD

**Issue by MartinXPN** [vercel/next.js#58759]
### Link to the code that reproduces this issue

https://github.com/MartinXPN/next-slow-build-reproduction

### To Reproduce

```shell
npm run build     # (~500s) This will build the app with the latest Next.js version
npm uninstall next && npm install next@13.4.19 && rm -rf .next
npm run build     # (~40s) This will build the app with the previous Next.js version
```

### Current vs. Expected behavior

It currently takes more than 10x longer to build a project with a large client-side component compared to the previous next.js version. This REALLY hurts the developer experience!
It should take way quicker to build the whole project and produce the production build.

For this small project, it took ~500s to build with the latest Next.js version, while it used to take only ~40 with the 13.4.9 version.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
    Binaries:
      Node: 18.18.2
      npm: 9.8.1
      Yarn: 1.22.20
      pnpm: N/A
    Relevant Packages:
      next: 14.0.3
      eslint-config-next: 14.0.3
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Dynamic imports (next/dynamic)

### Additional context

I've also reproduced this with a large form using react-hook-form and zod.
This started happening since I upgraded from next@13.4.9 to next@13.5.2 and above.

**Comment by belgattitude** [comment]
Same for me with ag-grid…(page router). Works fast with 13.5

**Comment by MartinXPN** [comment]
I was speculating that this might have been caused by the partial pre-rendering changes, but if this happens in the pages router as well, then I guess the underlying issue might be something else.

**Comment by MartinXPN** [comment]
Using the latest version of Next.js actually resulted in a 20x build slowdown on my actual project (not the reproduction above) making each build ~40 minutes instead of 2. I've mentioned it in the discussion: https://github.com/vercel/next.js/discussions/55710

**Comment by sandercoffee** [comment]
My yarn dev was 3s now Ready in 62.9s WTF 

yarn run v1.22.19
$ cross-env FORCE_COLOR=1 next dev
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000
   - Experiments (use at your own risk):
     · instrumentationHook

 ✓ Compiled /instrumentation in 337ms (23 modules)
 ✓ Ready in 62.9s

**Comment by MartinXPN** [comment]
@timneutkens @leerob is there any chance to bring the build speed back? This really hurts the developer experience. I used to go live in 2 minutes. Now that turned to 40 minutes.

**Comment by samcx** [comment]
@MartinXPN Thank you for submitting an issue!

I was able to replicate the issue with your <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture>. Will be digging into this!

**Comment by samcx** [comment]
A fix has been pushed to the latest canary → https://github.com/vercel/next.js/releases/tag/v14.1.1-canary.1! Can you let us know if this is no longer an issue?

**Comment by MartinXPN** [comment]
Thank you so much for making this improvement @samcx ! It was really painful to wait for 40 minutes for a single build.
Seems like there was a substantial improvement in the build time.
But unfortunately, the speed (at least on my main production project) is still far from what it used to be with the `13.4.9` version. It used to take only 2 minutes to build the whole project. It takes 10 minutes now.
This is a huge improvement compared to the 40 minutes it used to take with the stable version, but the canary version is still not as fast as the `13.4.9` used to be.

**Comment by MartinXPN** [comment]
@samcx , one unrelated issue with the latest canary version is that it throws an error during the build process (related to svelte even though I don't use it):

```
warning Error running install script for optional dependency: "/vercel/path0/node_modules/@sveltejs/kit: Command failed.
Directory: /vercel/path0/node_modules/@sveltejs/kit
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite' imported from 
/vercel/path0/node_modules/@sveltejs/kit/src/exports/vite/utils.js
```
I don't use vite. I don't use svelete. The project only uses `next.js`.

**Comment by MartinXPN** [comment]
@samcx @ijjk , I don't think this issue should be closed. 
Even though the #60859 brought a substantial improvement, it's still far from the `next@13.4.9` build time speed.
I just checked locally on an `M2 Max` Macbook (using the reproduction repo - https://github.com/MartinXPN/next-slow-build-reproduction):
* `next@13.4.9`: 36.73s.
* `next@14.1.1-canary.1`: 52.20s.

A huge improvement from the `next@14.1.0` version but still pretty slow. This is even slower on a larger codebase with many large client-side components.

**Comment by ijjk** [comment]
@MartinXPN yeah there is an increase still expected as https://github.com/vercel/next.js/pull/54411 now causes more compilation during the server pass which previously wasn't being done but is required for `app` to function fully.
