### ISSUE TITLE
Multiple x-forwarded-proto headers breaks middleware

### ISSUE THREAD

**Issue by Jonas-PFX** [vercel/next.js#58764]
### Link to the code that reproduces this issue

https://github.com/Jonas-PFX/NextJS-Dupe-Headers-Bug

### To Reproduce

Start the application with npm run dev (or npm run build and npm run start).
Make a curl request to your local server with one header:
```curl http://localhost:3000 -H "x-forwarded-proto: https"```

This works.

Make a curl request to your local server with duplicate header:
```curl http://localhost:3000 -H "x-forwarded-proto: https" -H "x-forwarded-proto: https"```

This results in a '400 - Bad request' response.

### Current vs. Expected behavior

Currently, with duplicate x-forwarded-proto headers, we get 400 bad request: 
![bild](https://github.com/vercel/next.js/assets/52192169/a56944d7-b632-4004-a4b4-fe0d2224938c)

Expected result would be a successful response.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Binaries:
  Node: 20.6.1
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

This stopped working in version 14.0.2 and only happens when you use middleware. The content of the middleware does not matter.  Removing the middleware file makes it work again.

This is a problem when behind multiple proxys such as cloudflare -> HA proxy -> nextjs.

**Comment by flynhigher** [comment]
It's the same thing but this also fails.
curl http://localhost:3000 -H "x-forwarded-proto: https,https"

**Comment by hamza-void** [comment]
Hey @Jonas-PFX thanks for the fix, how did you figure it out ? i don't see any errors when running npm run dev? did you start by where nextjs throws 400 bad request ? thanks again.

**Comment by Jonas-PFX** [comment]
> Hey @Jonas-PFX thanks for the fix, how did you figure it out ? i don't see any errors (TypeError) when running npm run dev? did you start by where nextjs throws 400 bad request ? thanks again.

After upgrading to 14.0.2, I started getting `400 bad request` on all requests.

Since the requests didn't even hit my middleware I figured there's not much I can do in my own code.

I didn't see the same behavior locally, and since my prod server is behind two proxies (cloudflare and HA proxy), I bypassed them to rule out any issues there. Those requests worked fine.

Used `netcat` to see the difference between a request that went through the proxies vs one that was made directly to the server.

Made a `curl` request directly to the nextjs server with the same headers as a request from the proxies would have, got `400 bad request`.

Tested one by one until I found the header causing the error, which was `x-forwarded-proto`.

Looked for any PR that went in to 14.0.2 and affected headers. Found [this change](https://github.com/vercel/next.js/commit/1caa58087a428666bb14d40dbc159b9a768b075d#diff-c49c4767e6ed8627e6e1b8f96b141ee13246153f5e9142e1da03450c8e81e96fR1744) which pretty obviously did not consider multiple headers. Reverted that change locally and everything worked again.

**Comment by Bahlaouane-Hamza** [comment]
Love that netcat part, much appreciated @Jonas-PFX 🔋👌

**Comment by nima-ca** [comment]
Any updates??
same problem here

**Comment by phev8** [comment]
We had previously (v13.4.12+) issues with middleware in combination of multiple x-forwarded-proto headers:
https://github.com/vercel/next.js/issues/54450

After upgrading to 14.0.4 that issue turned into this one.
