### ISSUE TITLE
Docs: CSP Example headers duplication

### ISSUE THREAD

**Issue by mike667** [vercel/next.js#58766]
### What is the improvement or update you wish to see?

Hello. Please check example [here](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy). Maybe I don't understand something, because I ask first before pull request.

1. Why do we need set **Content-Security-Policy** twice?
```
  const requestHeaders = new Headers(request.headers)
  requestHeaders.set('x-nonce', nonce)
 
  requestHeaders.set(
    'Content-Security-Policy',
    contentSecurityPolicyHeaderValue
  )
 
  const response = NextResponse.next({
    request: {
      headers: requestHeaders,
    },
  })
  response.headers.set(
    'Content-Security-Policy',
    contentSecurityPolicyHeaderValue
  )
```

2. Why do we need copy **request headers** to **response headers**?
In the docs:
```
const requestHeaders = new Headers(request.headers)
const response = NextResponse.next({
    request: {
      headers: requestHeaders,
    },
  })
```

In my application:
```
  const middlewareResponse = NextResponse.next();

  // add CSP headers
  const cspHeader = `
    # same as in docs
`;
  // Replace newline characters and spaces
  const cspHeaderPrepared = cspHeader.replace(/\s{2,}/g, " ").trim();

  middlewareResponse.headers.set("Content-Security-Policy", cspHeaderPrepared);
```

### Is there any context that might help us understand?

1. It's not critical, but I think it's a mistake that CSP header set twice.
2. I don't like request headers returns in response headers in my application. So I disabled it.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy

**Comment by leerob** [comment]
This has been updated 🙏
