### ISSUE TITLE
Calling revalidatePath() or revalidateTag() in Server Actions that are triggered from Intercepting Routes breaks useFormStatus() and useFormState()

### ISSUE THREAD

**Issue by flsilva** [vercel/next.js#58772]
### Link to the code that reproduces this issue

https://github.com/flsilva/next-v14-revalidate-issue-1

### To Reproduce

1. Visit https://next-v14-revalidate-issue-1.vercel.app
2. Scroll down and fill in the **name** input text.
3.  Click the **Submit** button in the **/src/app/page.tsx** box.
4. It works as expected. The **Submit** button changes to **Submitting...** and after 3 seconds it changes back to **Submit**, and you can see the Server Action's response.
5. Click **Nav to /foo** to visit the Intercepting Route **/foo**.
6. Fill in the **name** input text in either form.
7. Click the **Submit** button in either form.
8.  It doesn't work as expected. The **Submit** button changes to **Submitting...** but never changes back to **Submit**, and we never get the Server Action's response. Client Components never re-render.

### Current vs. Expected behavior

When we're at the **/foo** Intercepting Route we should see the same behavior we see when we're at the root route **/**, i.e., after clicking the **Submit** button it should change to **Submitting...** and after 3 seconds it should change back to **Submit**, and we should see the Server Action's response.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.9
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I can reproduce the issue in **v14.0.4-canary.9** on localhost and Vercel.

Code changes that results in the same behavior:

1. Changing **revalidatePath('/')** to **revalidatePath('/', 'page')**.
2. Changing **revalidatePath('/')** to **revalidatePath('/', 'layout')**.
3. Changing **revalidatePath('/')** to **revalidatePath('/foo')**.
4. Changing **revalidatePath('/')** to **revalidatePath('/foo', 'page')**.
5. Changing **revalidatePath('/')** to **revalidatePath('/foo', 'layout')**.
6. Replacing **revalidatePath()** with **revalidateTag('anything')**.

Code changes that results in the expected behavior:

1. If we comment out the **revalidatePath('/')** line of code in **action.ts** everything works as expected because we're not relying on cached data in this app.

Routing structure:

```
app
├── @intercept
│   ├── (.)foo
│   │   └── page.tsx
│   ├── [...catchAll]
│   │   └── default.tsx
│   └── default.tsx
│   └── page.tsx
├── foo
│   └── page.tsx
├── layout.tsx
└── page.tsx
```

Relevant code:

app/action.ts

```typescript
"use server";

import { revalidatePath } from "next/cache";

export const action = async (
  previousState: string | undefined,
  formData: FormData
) => {
  const name = formData.get("name");
  await new Promise((resolve) => setTimeout(resolve, 3000));
  revalidatePath("/");
  return `name: ${name} | Math.random(): ${(Math.random() * 100).toFixed(2)}`;
};
```

app/MyForm.tsx

```typescript
"use client";

import { useFormState } from "react-dom";
import { SubmitButton } from "./SubmitButton";
import { action } from "./action";

export const MyForm = () => {
  const [result, formAction] = useFormState(action, undefined);

  return (
    <form action={formAction}>
      <input type="text" name="name" placeholder="Name" autoComplete="off" />
      <SubmitButton />
      <p>Response: {result}</p>
    </form>
  );
};
```

app/SubmitButton.tsx

```typescript
"use client";

import { useFormStatus } from "react-dom";

export const SubmitButton = () => {
  const { pending } = useFormStatus();
  return (
    <button type="submit" disabled={pending}>
      {pending ? "Submitting..." : "Submit"}
    </button>
  );
};
```

Replay:

![next-v14-revalidate-issue-1](https://github.com/vercel/next.js/assets/544957/d36e32a7-9bd0-44fd-af24-c4d809ee8344)

<sub>[NEXT-1815](https://linear.app/vercel/issue/NEXT-1815/calling-revalidatepath-or-revalidatetag-in-server-actions-that-are)</sub>

**Comment by ahrbil** [comment]
@flsilva I don't know if this is related to your issue, but have you noticed the action prop value on the form tag?
`action="javascript:throw new Error('A React form was unexpectedly submitted. If you called form.submit() manually, consider using form.requestSubmit() instead. If you\'re trying to use event.stopPropagation() in a submit event handler, consider also calling event.preventDefault().')"`
🤔

**Comment by gipeey** [comment]
i'm here with the same issue too
![image](https://github.com/vercel/next.js/assets/75357493/0950206b-20b0-40ea-ae14-61c859b32bf7)

**Comment by balazsorban44** [comment]
Thanks, we will look into this! Anyone having a similar issue, please note that "same issue" without a reproducible code example is not useful. Please post your _minimal_ reproduction, that we can have a look to verify, once a a fix has been made :pray:
