### ISSUE TITLE
When application only has next-auth as API routes, the next-auth routes are unable to be hit on Vercel

### ISSUE THREAD

**Issue by jnwu** [vercel/next.js#58787]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.0
Relevant Packages:
  next: 13.5.4
  eslint-config-next: 13.4.19
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

next-auth

### What browser are you using? (if relevant)

Chrome 119.0.6045.159

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When `next-auth` is the only API route used in a Next app, the routes (from `next-auth`) could not be used, the following error message results. This is happening only on deployment on Vercel.

An example route from `next-auth` would be `/api/auth/csrf`.

```
Error: EMFILE: too many open files
```

Presently, the workaround is to add another dummy route.

### Expected Behavior

When hitting the route `/api/auth/csrf` from `next-auth`, the response returns the `csrf` JSON payload

### To Reproduce

1. Setup a Next app with only `next-auth` API routes (no other routes)
2. Deploy to Vercel
3. Access `/api/auth/csrf`

**Comment by balazsorban44** [comment]
Closing based on https://twitter.com/balazsorban44/status/1727731117640315032
