### ISSUE TITLE
Docs: Incorrect Definition of `image` for `ImageResponse`

### ISSUE THREAD

**Issue by unimu-cic** [vercel/next.js#58802]
### What is the improvement or update you wish to see?

I would like to update the code snippet on https://vercel.com/docs/functions/edge-functions/og-image-generation/og-image-examples#using-a-local-image. By the way, I did not find any references to this part of the doc in Vercel's repos; are these parts not open source yet?

**Current version:**
```TypeScript
// TypeScript
import { ImageResponse } from 'next/og';
// App router includes @vercel/og.
// No need to install it.
 
export const runtime = 'edge';
 
export async function GET() {
  const image = await fetch(new URL('./image.png', import.meta.url)).then(
    (res) => res.arrayBuffer(),
  );
 
  return new ImageResponse(
    (
      <div
        style={{
          display: 'flex',
          background: '#f6f6f6',
          width: '100%',
          height: '100%',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <img width="256" height="256" src={imageData} />
      </div>
    ),
    {
      width: 1200,
      height: 630,
    },
  );
}
```
The variable `image` should be `imageData`.

### Is there any context that might help us understand?

I've noticed a documentation error in the code snippet provided for generating an image with ImageResponse in the Next.js documentation. The TypeScript version code snippet declares `image` to receive the image arrayBuffer, but uses `imageData` as the value in `ImageResponse`.

### Does the docs page already exist? Please link to it.

https://vercel.com/docs/functions/edge-functions/og-image-generation/og-image-examples#using-a-local-image

**Comment by leerob** [comment]
Thank you, I will fix this!
