### ISSUE TITLE
CSS fast refresh is not working in Firefox with --turbo

### ISSUE THREAD

**Issue by Arctomachine** [vercel/next.js#58826]
### Link to the code that reproduces this issue

https://github.com/Arctomachine/next-css-fast-refresh-reproduction

### To Reproduce

1. Start server in dev mode with `--turbo` flag and open page in Firefox (tested at version 119)
2. Go to globals.css and change background color - it works
3. Change color again - previous color is still displayed
4. Reload page manually - color is updated now

### Current vs. Expected behavior

Styles are updated only first time they are changed, starting from 2nd time changes are not updated until manual page reload.
Should update after every change without manual reload.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
  Platform: win32        
  Arch: x64              
  Version: Windows 10 Pro
Binaries:                
  Node: 20.2.0           
  npm: N/A               
  Yarn: N/A              
  pnpm: N/A              
Relevant Packages:
  next: 14.0.4-canary.11
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Additional context

Could be similar problem to #43396, but for `--turbo`
Each change successfully prints `[Fast Refresh] rebuilding` into console regardless of style updates

<sub>[PACK-2135](https://linear.app/vercel/issue/PACK-2135/css-fast-refresh-is-not-working-in-firefox-with-turbo)</sub>

**Comment by ForsakenHarmony** [comment]
This should be fixed with https://github.com/vercel/turbo/pull/7013
