### ISSUE TITLE
prependData does import to other partials

### ISSUE THREAD

**Issue by PaulSinghDev** [vercel/next.js#58837]
### Link to the code that reproduces this issue

https://github.com/PaulSinghDev/prepend-data-nextjs-issue

### To Reproduce

1. Setup the prependData flow using `sassOptions`
2. Create a styles folder
3. Add a partial for something like `_colors.scss`
4. Create a component
5. Add an SCSS module and another partial
6. Try to use your color variable in the second partial
7. `@use` the new partial in the main SCSS module for the component
8. Import the SCSS module to component
9. Use the component in your app

### Current vs. Expected behavior

Expected: The app will compile and the SCSS will render as normal with the color variable added in

Actual: Get an undefined variable error

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
OSX: macOS 13.6.1 (22G313)
VSCode: Version: 1.84.2 (Universal)
NextJS: 14.0.3
SASS: 1.69.5
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by EliHood** [comment]
If you use ```import``` instead of ```use``` it will work. Are you suggesting that ```use``` should work still ?

**Comment by EliHood** [comment]
Have you tried appending ```as *``` ?

E.g

```@use "./some-partial" as *;```

**Comment by PaulSinghDev** [comment]
@EliHood yeah it still has the same error/behaviour. I feel like this is something to do with the `_some-partial.scss` file being ignored by the `prependData` rule.

**Comment by KenTay198** [comment]
I faced the same issue, seems to be related to the --turbo flag on the next dev. When I remove it, my variables.scss file is correctly set so it might just be that prependData isn't working with turbo dev for the moment.

**Comment by timneutkens** [comment]
Had a look at this but it seems there's a misconception about what `prependData` would do, the underlying option that handles this is only prepending what you provided to the entrypoint, in this case the entrypoint would be `SomeComponent.module.scss`, everything imported from there would not magically get the additionalData prepended. Here's a sandbox that shows what it would look like manually adding the prependData: https://codesandbox.io/p/github/PaulSinghDev/prepend-data-nextjs-issue/csb-3nz6nh/draft/immutable-snowflake?file=%2Fsrc%2Fcomponents%2FSomeComponent%2FSomeComponent.module.scss%3A7%2C1

More info here: https://webpack.js.org/loaders/sass-loader/#additionaldata



@KenTay198 your case is different, I just opened a PR for the issue you ran into: #62397
