### ISSUE TITLE
Server action throws uncaught exception on network error

### ISSUE THREAD

**Issue by kevva** [vercel/next.js#58843]
### Link to the code that reproduces this issue

https://github.com/kevva/next-server-action-network-error

### To Reproduce

1. Start the application (`npm run dev`)
2. Go to `/` and click "Submit", the server action should be called every 5s
3. Stop the server to simulate a network error

### Current vs. Expected behavior

So, I found this issue while building a magic link login in a React Native `WebView`. In my submit handler I'm polling for a login result by retrying calling a server action. However, when switching apps to open the magic link and then switching back, the app throws an exception. This is because in a `WebView` on iOS all requests seem to be cancelled when switching apps and Next.js doesn't seem to handle network errors in server actions very well.

The current behaviour don't let me catch the error at all, even though wrapping the server action in a `try/catch`. The expected behaviour would be to not throw before I can catch the error myself.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64
Binaries:
  Node: 21.2.0
  npm: 10.2.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by 4lejandrito** [comment]
Possible dupe https://github.com/vercel/next.js/issues/58638?

**Comment by kevva** [comment]
@4lejandrito, yeah 100%.
