### ISSUE TITLE
Issues with Default Language Routing and Router Interceptor in Next.js /app Directory (i18n)

### ISSUE THREAD

**Issue by RexGalicie** [vercel/next.js#58857]
### Link to the code that reproduces this issue

https://github.com/RexGalicie/app-route-i18-test

## Scenario 1: Non-default Language Selection (Works as Expected)
- **Action**: Select a non-default language (any language other than English `en`).
- **Action**: Click on a test page.
- **Expected Behavior**: The modal page is displayed correctly, as intercepted from the route. No issues are observed.

## Scenario 2: Default Language Selection and Inconsistency
- **Action**: Select the default `en` language.
- **Action**: Click on a test page.
- **Initial Behavior**: The modal test page appears correctly the first time and sometimes even on the second click.
- **Inconsistent Behavior**: On subsequent clicks, the interceptor does not function as expected. Instead of loading the new content, it only opens a cached link as a modal.
-**Note**: To reproduce use all links, and client routing as after refresh page it allows open ones, but on second or third test link nothing happen 
- **Error**: No specific error is observed in the console in this scenario, contrasting the earlier `SEGMENT MISMATCH` error.

## Issue with Middleware and Router Interceptor
The inconsistency with the router interceptor, especially when handling the default language, is a significant concern. It seems to work correctly for non-default languages but fails to maintain consistent behavior for the default language. This affects the user experience and potentially impacts SEO due to improper URL handling.

Recording:

https://github.com/vercel/next.js/assets/6573958/39b01df7-f3c2-4466-a456-b5f1cf0d8a78

### Current vs. Expected behavior

The desired outcome is for the default language (English) content to be served directly from the root URL (example.com/) without redirection to /en, and for the router interceptor to function consistently across all navigational scenarios.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: 1.22.19
  pnpm: 8.6.2
Relevant Packages:
  next: 14.0.4-canary.13
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.8.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by PxlSyl** [comment]
Hello, if I understood correctly, there is no support for i18n with the router app... Therefore it is up to the developers to implement i18n and to choose the setup and libraries carefully. If you are interested, I created a complete fork of a blog template, with i18n integration which works perfectly. You can therefore copy the setup for your own projects. Here's the repo : https://github.com/PxlSyl/tailwind-nextjs-starter-blog-i18n/tree/main

**Comment by RexGalicie** [comment]
@PxlSyl, thanks for your input!

In my case, everything functions perfectly except for the part related to [intercepting routes](https://nextjs.org/docs/app/building-your-application/routing/intercepting-routes) as described in the Next.js documentation. When using a non-default language (like `/de`), everything works as expected. Route interception works flawlessly, for example, when navigating to `/de/test/1`, it correctly triggers the interception from `(.)test`.

However, I encounter issues with the default route (`/`). Initially, when I access the default route, the intercept route is correctly recognized and handled. But, as soon as I navigate back and try to access to other dynamic id , the interceptor fails to behave as expected.

Here's a screenshot illustrating the issue:
![Issue Screenshot](https://github.com/vercel/next.js/assets/6573958/9f612467-289b-4516-84fd-437400281c92)

The inconsistency in behavior with the default route is quite puzzling and is what I'm primarily concerned about.

**Comment by RexGalicie** [comment]
@PxlSyl I'll check your repo tomorrow

**Comment by PxlSyl** [comment]
I think it's more related to the llibrary you're using than related to next.js (https://github.com/i18nexus/next-i18n-router) There's tons of i18n libraries, with differences in the setup so you might ask them in the issues for your specific setup?

**Comment by PxlSyl** [comment]
Adding my middleware won't solve your problem, since the setup is not the same

**Comment by RexGalicie** [comment]
@PxlSyl  i did replicate with your project same scenario

I did PR and branch https://github.com/PxlSyl/tailwind-nextjs-starter-blog-i18n/pull/2
u can test it as well 

https://github.com/vercel/next.js/assets/6573958/528cbfa1-7d0c-4765-b8f9-278e5def5bc7

**Comment by RexGalicie** [comment]
I do believe it is NextJs it self, as faced issues with interception when use query params as well

**Comment by RexGalicie** [comment]
@PxlSyl 
FYI
seems it has been fixed by https://github.com/vercel/next.js/pull/59094
I'll do a few testing around

**Comment by RexGalicie** [comment]
Thanks @balazsorban44  
All good so far with latest canary 
BTW I faced one more related but not sure if it is issues or expected behaviour, related to route interceptor.
For instance, if open page via SSR like  test/id -> and on this page action which add query params like `test/id?filter=all`, route intercept this route and open modal in my case on top of test/id, this case i have this page already opened with modal of the same page, i do expect if page open via SSR, route should not intercept same page again. 

Cheers

**Comment by RexGalicie** [comment]
@balazsorban44 
FYI 
https://github.com/vercel/next.js/issues/59440
