### ISSUE TITLE
I am unable able to deploy one of my blog application due to some issues . I am Unable to resolve it 

### ISSUE THREAD

**Issue by Manoj-kumar-C** [vercel/next.js#58860]
### What is the improvement or update you wish to see?

I wish to add more  information about deployment of the API from localhost to vercel . It will be very helpful 

![image](https://github.com/vercel/next.js/assets/90634510/44c28e6e-744d-4459-8747-75c573dcc827)

My Github Repo : https://github.com/Manoj-kumar-C/blog

### Is there any context that might help us understand?

I dont know how to deploy the app to vercel . Tried alot with Developers and documentation . Pleasee update it . Thank you

**Comment by JesseKoldewijn** [comment]
Since you have your project on Github, you can link your repo to a Project in the Vercel dashboard.

**Comment by Manoj-kumar-C** [comment]
I have already done . It shows some error 
![image](https://github.com/vercel/next.js/assets/90634510/2950a744-f0cd-4f01-b11b-53f4f4f3ebcc)


This is the latest updated Github Repo that I have uploaded now 
https://github.com/Manoj-kumar-C/blog-test

The main issue is that i have developed with respect to Local system . After development  I have the doubts to deploy to the vercel . I have resolved all the issues . This is only one issue to be fixed 

![image](https://github.com/vercel/next.js/assets/90634510/975d018f-2575-46d1-8ee8-6e21db6b9084)


![image](https://github.com/vercel/next.js/assets/90634510/55631268-8276-44a7-af3a-2f2935b657f4)


For the helper.js I dont know How to replace the base URL 

I need to resolve error

**Comment by Manoj-kumar-C** [comment]
I have read the docs but I didnt find any information to solve this one particular issue . But I have solves all the error by reading the docs . This is the only one issue to be fixed

**Comment by JesseKoldewijn** [comment]
The fetch is failing on build due to SSR + attempting to fetch from localhost. Which doesn't work.

**Comment by Manoj-kumar-C** [comment]
How to resolve it

**Comment by Manoj-kumar-C** [comment]
Can We connect through Linkedin dude

**Comment by JesseKoldewijn** [comment]
> How to resolve it

You should call the fetch function directed towards the actual url and not localhost. Besides since this is not a framework issue you should convert this issue into a discussion in my opinion. But that's not my call.

If you need some help with it, feel free to convert this issue into a discussion. 👍

**Comment by Manoj-kumar-C** [comment]
You just clone the repo and deploy to the vercel . How to resolve the error . It is a js file in the directory . It tried to import as localhost and then Imported the data with respect to directory and with respect to url . This are three ways that works fine in local system .

But these three ways doesn't work . Can you provide the exact base url . If you deployed it correctly . 
I know the want the error is but I don't know to resolve it

**Comment by Manoj-kumar-C** [comment]
I think you dont understand what is the real problem that I am facing dude

**Comment by JesseKoldewijn** [comment]
okey dude, I'm trying real hard to be understanding here with the issue at hand. 

the following things are inherit issues:
1. localhost is only available locally
2. the getPost call is used server-side only, so you don't need to do a fetch. just import the posts data directly
3. fetch uses a network protocol called http/https which dont support remote path file calls

I wish you good luck with figuring this out while hopefully keeping the previously mentioned points in mind. And have a nice weekend.

**Comment by Manoj-kumar-C** [comment]
😅

**Comment by Manoj-kumar-C** [comment]
You Can Done by Deploying the Fetching Data in another Area and then changing the BASEURL
