### ISSUE TITLE
ISR revalidation is using stale data

### ISSUE THREAD

**Issue by hallatore** [vercel/next.js#58909]
### Link to the code that reproduces this issue

https://github.com/hallatore/revalidate-bug

### To Reproduce

1. Build the app and run `npm run start`
2. Open frontpage http://localhost:3000
3. Note: The frontpage reloads every second
4. Observe how the time is only updating every ~10 seconds. (It should be every ~5 seconds)

### Example code

page.tsx
```typescriptreact
async function Page() {
  const response = await fetch(
    "http://worldtimeapi.org/api/timezone/Europe/Oslo",
    {
      next: {
        revalidate: 5,
      },
    }
  );

  const json = (await response.json()) as { datetime: string };

  return (
    <p>{json.datetime}</p>
  );
}

export default Page;
```

## Current behavior
Page revalidation is getting (mostly) stale fetch data, causing every second revalidation to reuse old data.

## Expected behavior
The page derives it's revalidation from the fetch call. So it makes sense that when the page is revalidated it's because it should be re-rendered with updated fetch data. 

The time in the example should update every ~5 seconds.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.6.2
Relevant Packages:
  next: 14.0.4-canary.16
  eslint-config-next: 14.0.4-canary.16
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

**Comment by hallatore** [comment]
This causes 50% of the page renderings to be useless. It's confusing that revalidate: 60 means on a fetch calls means your page will update it's data every 2 minutes.

**Comment by hallatore** [comment]
I tested a bit more locally. Finding this bug to be quite strange.

- If I refresh multiple times per second, then the time is only updated every 10+ seconds.
- If I refresh slower, like every 2 seconds, I sometimes get a new time after 5+ seconds.

**Comment by hallatore** [comment]
I think I tracked it down to a race condition somewhere in the code.
If I add a 100ms delay to the start of my function, then the fetch call always return fresh data.

Example video. Second half is with 100ms delay added to start of function.
https://github.com/vercel/next.js/assets/365605/8ef92e43-fdb3-4f0c-91a3-cb87f6dacb8e



Example code where it now seems to work:
```
async function Page() {
  await new Promise((resolve) => setTimeout(resolve, 100));
  const response = await fetch(
    "http://worldtimeapi.org/api/timezone/Europe/Oslo",
    {
      next: {
        revalidate: 5,
      },
    }
  );

  const json = (await response.json()) as { datetime: string };

  // Note: function is run twice for some reason. This is a different bug: https://github.com/vercel/next.js/issues/58736
  console.log("local", new Date().toLocaleTimeString());
  console.log("fetch", json.datetime.substring(11, 19));
  console.log("");

  return (
    <div>
      <h1>Time should update every 5 seconds. Not every 10.</h1>
      <p>local: {new Date().toLocaleTimeString()}</p>
      <p>fetch: {json.datetime.substring(11, 19)}</p>
    </div>
  );
}

export default Page;
```

**Comment by hallatore** [comment]
I also found that this bug also happens if the page has a revalidate and the fetch has nothing.

Uncomment the await at the top of the function magically fixes the bug
```
export const revalidate = 5;

async function Page() {
  // Note: Uncomment this to "fix the bug"
  //await new Promise((resolve) => setTimeout(resolve, 100));

  const response = await fetch(
    "http://worldtimeapi.org/api/timezone/Europe/Oslo"
  );

  const json = (await response.json()) as { datetime: string };

  return (
    <div>
      <h1>Time should update every {revalidate} seconds.</h1>
      <p>local: {new Date().toLocaleTimeString()}</p>
      <p>fetch: {json.datetime.substring(11, 19)}</p>
    </div>
  );
}

export default Page;
```

**Comment by hallatore** [comment]
Turned on `NEXT_PRIVATE_DEBUG_CACHE = true` in .env.local and got the following output.
Notice the first one sets the fetch call before the page-function is run. the second one doesn't set fetch at all.

```
// output when it works
using filesystem cache handler
not using memory store for fetch cache
get /index undefined app true
get 03c3d5ae7e21018aa8db4b0559be1e18e9f2e94e9dc15d94e7360c6345b0fd3b [] fetch true
set 03c3d5ae7e21018aa8db4b0559be1e18e9f2e94e9dc15d94e7360c6345b0fd3b
local 11:27:59
fetch 11:28:00
set /index

---

// output where fetch uses state data
using filesystem cache handler
not using memory store for fetch cache
get /index undefined app true
get 03c3d5ae7e21018aa8db4b0559be1e18e9f2e94e9dc15d94e7360c6345b0fd3b [] fetch true
local 11:28:04
fetch 11:28:00
set /index
```

**Comment by hallatore** [comment]
Found the culprit.

This line here: https://github.com/vercel/next.js/blob/canary/packages/next/src/server/lib/incremental-cache/index.ts#L467

If I change it to `const isStale = age >= revalidate` then everything works as expected.

When the page revalidates at the exact time it's going stale then age and revalidate er equal.

**Comment by torleifhalseth** [comment]
Tore på sporet!

Great work @hallatore 🎖️ I really hope this solves the unpredictable revalidation 🤞
