### ISSUE TITLE
Roboto flex from next/font/google is missing XOPQ axes

### ISSUE THREAD

**Issue by yohimik** [vercel/next.js#58913]
### Link to the code that reproduces this issue

https://github.com/yohimik/next-roboto-flex-repro/tree/main

### To Reproduce

1. Import Roboto_flex from next/font/google
2. Specify XOPQ axe in the axes array
3. Expect an "Invalid axe value error"

### Current vs. Expected behavior

XOPQ axes value should work without error

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Node 20.10
Next 14.0.3
Platform any
```

### Which area(s) are affected? (Select all that apply)

Font optimization (next/font)

### Additional context

Linking Google Fonts issue regarding Roboto flex missing axes
https://github.com/google/fonts/issues/5975
In addition, I think it's not a good idea to throw a not ignorable error while using axes as it requires a lot of time to create an issue, wait for an answer, and finally release a tiny fix. Warning should be enough

**Comment by yohimik** [comment]
up

**Comment by yohimik** [comment]
up

**Comment by yohimik** [comment]
up

**Comment by yohimik** [comment]
bump

**Comment by yohimik** [comment]
a possible workaround is to use [Fontsource](https://fontsource.org/)

**Comment by justvitalius** [comment]
XOPQ property appeared in nextjs 14.2.4
I just encountered such an issue and fixed it by updating the library version from 14.0.3
