### ISSUE TITLE
Dynamic routes not working within parallel routes

### ISSUE THREAD

**Issue by borisghidaglia** [vercel/next.js#58937]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/bold-ives-x6zpnx-x6zpnx

### To Reproduce

Click on the "Go to test page" link

### Current vs. Expected behavior

Current behavior:

The dynamic `slug` route segment is never reached, be it through navigation (clicking on the "Go to test page" link) or by reloading when already on the `/test` route.

Expected behavior:

The dynamic `slug` route segment is reached and the `Title` component inside `app/@title/[slug]/page.tsx` renders the slug param.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
# Latest

Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.2
  eslint-config-next: 14.0.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A

# Canary

Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.17
  eslint-config-next: 14.0.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Thanks for your work 🙏

**Comment by borisghidaglia** [comment]
I managed to find what the problem was.

In the sandbox, I mix a regular route and a dynamic route inside a parallel route.

A is the regular route. The `app/test/` folder.
B is the dynamic parallel route. The `app/@title/[slug]/` folder.

I found that when calling the url `/test`, A is reached, but not B.

However, when turning A into a dynamic route by replacing it by an `app/[slug]/` folder, then calling the url `/test` reaches A and B successfully.

I don't know if it is the expected behavior or not.

**Comment by ztanner** [comment]
Hi @borisghidaglia! Thanks for the report. I believe you're correct: a regular page segment (e.g., `test` will look for a corresponding parallel route (e.g., `@title/test`). If it can't find one, it'll match the `default` component. It won't attempt to match with the dynamic param, unless your page was also `[slug]`.

If the intent is to create something akin to breadcrumbs, you could update your `@title` slot's `[slug]` page to be a `[...slug]` instead. Catch-all params are special cased to allow this less specific matching. This will match `/test`, `/foo`, `/bar`, ...etc. 

I'm going to close this as I believe you've found a workaround, but happy to follow-up in case you have any additional questions!
