### ISSUE TITLE
Docs: Error deploying project in vercel

### ISSUE THREAD

**Issue by Prathapkarumanchi** [vercel/next.js#58931]
### What is the improvement or update you wish to see?

In Chapter 6, when we are connecting our repo in Vercel and trying to deploy the project, the build fails.

Reason:- `invoice/table.tsx` contains images that don't have an `alt` tag

### Is there any context that might help us understand?

![image](https://github.com/vercel/next.js/assets/53927098/7696ef05-0d21-4a84-87bd-0c3ef2f33816)

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/setting-up-your-database

**Comment by touseefrana552** [comment]
<Image src="invoise.png" alt="Invoice" />
    you need to ensure that all img elements in your React components have an alt attribute. The alt attribute provides alternative text for screen readers and improves the accessibility of your application.

**Comment by leerob** [comment]
I believe this has been fixed now, thank you.
