### ISSUE TITLE
Docs: how to call Route Handler within client conponent

### ISSUE THREAD

**Issue by skorphil** [vercel/next.js#58952]
### What is the improvement or update you wish to see?

I would like to see more explanation what is "call route handler"
https://github.com/vercel/next.js/discussions/58896

### Is there any context that might help us understand?

Now there is no examples of calling route handlers

**Comment by wmlutz** [comment]
I can't find a good example either. Documentation [page](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) needs an example section.

**Comment by Judahmeek** [comment]
@delbaoliveira @leerob 
Y'all are the ones who created and approved https://github.com/vercel/next.js/pull/53793.

Can either of you give us some insight into how we're supposed to call Route Handlers in a Client Component?

All the documentation on Route Handlers is about how to create them, but not how to use them.

**Comment by leerob** [comment]
A route handler would be serving as a public API endpoint in this context. So, from a client component, you would call it using `useEffect`, or a data fetching library like `swr`. This is similar to API Routes in the Pages Router, or general client-side data fetching in React.
