### ISSUE TITLE
Multiple x-forwarded-proto headers breaks standalone

### ISSUE THREAD

**Issue by Bahlaouane-Hamza** [vercel/next.js#59031]
### Link to the code that reproduces this issue

https://github.com/Bahlaouane-Hamza/nextjs-dup-headers-standalone

### To Reproduce

1. Build the app in standalone mode `npm run build`
2. Run `node .next/standalone/server.js`
3. Make a curl request to your local server with multiple headers: `curl -I http://localhost:3000/ -H "X-Forwarded-Proto: https" -H "X-Forwarded-Proto: https" ` 
4. The app redirect to https://0.0.0.0:3000/home

### Current vs. Expected behavior

Currently, the Curl with multiple headers redirects to https://0.0.0.0:3000/home
```bash
HTTP/1.1 307 Temporary Redirect
location: https://0.0.0.0:3000/home
Connection: keep-alive
Keep-Alive: timeout=5
```
Expected behavior should redirect to /home
```bash
HTTP/1.1 307 Temporary Redirect
location: /home
Connection: keep-alive
Keep-Alive: timeout=5
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 7.27.0
Relevant Packages:
  next: 14.0.4-canary.18
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

Under same conditions, the initial issue was instead of getting redirect, it was giving 400 bad request Next end up trying the parse `https,https://localhost:3000` . This was fixed by the patch included in the reproduction repository (the same reported at https://github.com/vercel/next.js/issues/58764 ). The same fix apply here but at `next/dist/server/lib/router-utils/resolve-routes.js`

This is a problem when running Next behind multiple proxys such as F5 -> HA proxy -> NextJS.

**Comment by sitole** [comment]
Same for us, we are running Next.js behind Nginx proxy that sets `X-Forwarded-Proto` but Next ignores it and resolves it ass `https` when traffic is in `http`.
