### ISSUE TITLE
Using route groups without top-level root layout causes favicon.ico to not being added into head 

### ISSUE THREAD

**Issue by AuroPick** [vercel/next.js#59089]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/favicon-test-45ydwx
### To Reproduce

1. create new project
2. create new route group inside the app folder
3. copy everything inside the route group

I want to create a route group that will use header and footer layout. Currently we only have one layout but later we can alse have layout without header and footer so I want to do this before having multiple layouts.

this is standard folder structure
![Screenshot 2023-11-29 at 23 32 35](https://github.com/vercel/next.js/assets/53499802/fae7eb53-5375-4db9-8e97-b22f74f91c55)
![image](https://github.com/vercel/next.js/assets/53499802/786fa2af-adc5-4ea3-937a-19240241f3b9)

as you can see favicon is added correctly

I created a route group named (with-header-and-footer)

![Screenshot 2023-11-29 at 23 29 57](https://github.com/vercel/next.js/assets/53499802/3022c94e-f882-4369-b108-ce46baf36366)
![Screenshot 2023-11-29 at 23 31 46](https://github.com/vercel/next.js/assets/53499802/3b148f79-9eb0-4962-bd51-1cc3c3fe06c3)

as you can see there is no favicon

### Current vs. Expected behavior

favicon.ico should be added successfully, but is is not

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:57 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.15
  pnpm: 6.11.0
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata (metadata, generateMetadata, next/head)

### Additional context

I have tried both version 14.0.3 and 14.0.4-canary.27

**Comment by Jon1VK** [comment]
From the docs: "The favicon image can only be located in the top level of app/."

You have moved also the favicon.ico file to the group folder. As so it won't be picked up by Next.js

**Comment by AuroPick** [comment]
I tried but it didn't work. If you also using a apple-icon. You also have to move it to outside of the group.

This works

![Screenshot 2023-11-30 at 08 52 42](https://github.com/vercel/next.js/assets/53499802/9482a7e0-2412-4e9a-bf66-85497c98fbd0)
