### ISSUE TITLE
Docs: Guidance on allowing multiple user agent rules with varying allow/disallow.

### ISSUE THREAD

**Issue by janderson-watchbox** [vercel/next.js#59178]
### What is the improvement or update you wish to see?

Allow multiple userAgent rules in robots.ts to block on an agent by agent basis.

```
rules: [
    {
        userAgent: '*',
        allow: ['*'] // or '*'
    },
    {
        userAgent: 'Bytespider', // or ['Bytespider', 'Bytedance']
        disallow: ['*']
    },
    {
        userAgent: 'Bytedance',
        allow: ['*']
    }
]
```

### Is there any context that might help us understand?

Documentation suggests that only a single UserAgent rule may be used.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots

**Comment by donsn** [comment]
According to the [documentation](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots#robots-object), you can use multiple user agents. Just pass in an array of `user agents` to the` rules` property, just as you described

**Comment by 808vita** [comment]
Hey @janderson-watchbox I think nextjs can already handle your requirement. Please customise the below code block to your need and please report back. 
I was able to find a robots ts file within nextjs repo -> inside test folder - [the link to robots ts file](https://github.com/vercel/next.js/blob/canary/test/e2e/app-dir/metadata-dynamic-routes/app/robots.ts) hope this helps.
```
import type { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: 'Googlebot',
        allow: ['/'],
      },
      {
        userAgent: ['Applebot', 'Bingbot'],
        disallow: ['/'],
        crawlDelay: 2,
      },
    ],
    sitemap: 'https://example.com/sitemap.xml',
    host: 'https://example.com',
  }
}
```

**Comment by 808vita** [comment]
@leerob can you assign me this task for updating the relevant documentation ?
Thanks.

**Comment by leerob** [comment]
This was shipped!
