### ISSUE TITLE
Docs: guide setting up a next.js project with stripe still uses the pages directory

### ISSUE THREAD

**Issue by kalvinyuu** [vercel/next.js#59192]
### What is the improvement or update you wish to see?

update the article so it uses the app directory 

### Is there any context that might help us understand?

making it easier to set up stripe with a nextjs 13 project

### Does the docs page already exist? Please link to it.

https://vercel.com/guides/getting-started-with-nextjs-typescript-stripe

**Comment by leerob** [comment]
Thanks, we'll be working on update many different guides and examples that use the Pages Router to use App in the coming months / years. If you're looking for a good App Router example right now, check out https://github.com/vercel/commerce
