### ISSUE TITLE
Docs: next CLI options for dev, build

### ISSUE THREAD

**Issue by itzsrikanth** [vercel/next.js#59226]
### What is the improvement or update you wish to see?

It would be helpful if the options that `next dev` can take would be listed in both the documentation and the [CLI's help option](https://github.com/itzsrikanth/next.js/blob/3aa62d1fff4e47fa9cb3288e23268d1393794e24/packages/next/src/cli/next-dev.ts#L116)

### Is there any context that might help us understand?

Some options like `--turbo` and some experimental flags are not mentioned. Similarly, `--build-mode` for `next build` etc.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/next-cli#development

**Comment by leerob** [comment]
Having `--turbo` and `--build-mode` documented makes sense!
