### ISSUE TITLE
Next.js gives 404 on Intercepting Routes with nested route groups

### ISSUE THREAD

**Issue by fedetorre** [vercel/next.js#59279]
### Link to the code that reproduces this issue

https://github.com/fedetorre/nextgram

### To Reproduce

I have a complex nextjs project with the same problem, I tried to reproduce my project structure with the nextgram demo for debugging purpuse.

Steps to reproduce:
1. Checkout the project
2. yarn install
3. yarn dev
4. Open the browser on [localhost:3000](http://localhost:3000)
5. Click to an image, the url change but renders the 404 page, in the [original nextgram demo](https://github.com/vercel-labs/nextgram) a modal will be open with the clicked image
6. If you refresh the page the image appear and the server does not give 404

### Current vs. Expected behavior

I'm expecting that the modal opens with the image and the 404 page will not be rendered.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.40
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

### Additional context

This is the current behaviour
[Screencast from 05-12-2023 10:19:44.webm](https://github.com/vercel/next.js/assets/2004681/f4174d32-5e99-441e-ac8e-cfe34c9b813c).

My production application is deployed on vercel but the problem also exists on local development environment.

<sub>[NEXT-1813](https://linear.app/vercel/issue/NEXT-1813/nextjs-gives-404-on-intercepting-routes-with-nested-route-groups)</sub>

**Comment by ForsakenHarmony** [comment]
This is actually expected behavior as you're switching layouts (in the repro even the root layout)
