### ISSUE TITLE
bug: serverActions.bodySizeLimit is ignored

### ISSUE THREAD

**Issue by TryingToImprove** [vercel/next.js#59277]
### Link to the code that reproduces this issue

https://github.com/TryingToImprove/next-app-router-body-size-issue

### To Reproduce

1. Start the application
2. Click submit button
3. It should not throw a error because the data posted is not the same size as what is expected

### Current vs. Expected behavior

Should not fail - `bodySizeLimit` should work

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.11.0
Relevant Packages:
  next: 14.0.4-canary.40
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

Relevant code is here: https://github.com/TryingToImprove/next-app-router-body-size-issue/commit/6efd384f55d30fcdb26bc72a2252689c0f44e562

**Comment by LavransBjerkestrand** [comment]
I'm having the same problem, set it to `64mb` but in reality it just stays at `1mb`/`1,048,576 bytes`. Tried numerical values but same result

**Comment by TryingToImprove** [comment]
I have done some investigation I think I have figured out what the issue is.

When using a Server Action as a action on a `form` the request to the server is a `multipart` request whereas making the request in a click handler it a normal request.

When making a `multipart` request next have a different way of handling the decoding of the data where it uses `busboy` without any configurations. If `busboy` is used without any configuration the default limit for a field is `1MB` which is way it get truncated.

The place where `busboy` is used is here: https://github.com/vercel/next.js/blob/canary/packages/next/src/server/app-render/action-handler.ts#L467-L470

I am able to get it work by applying this

```
--- a/packages/next/src/server/app-render/action-handler.ts
+++ b/packages/next/src/server/app-render/action-handler.ts
@@ -463,8 +463,11 @@ export async function handleAction({

         if (isMultipartAction) {
           if (isFetchAction) {
+            const readableLimit = serverActions?.bodySizeLimit ?? '1 MB'
+            const limit = require('next/dist/compiled/bytes').parse(readableLimit)
+
             const busboy = require('busboy')
-            const bb = busboy({ headers: req.headers })
+            const bb = busboy({ headers: req.headers, limits: { fieldSize: limit } })
             req.pipe(bb)

             bound = await decodeReplyFromBusboy(bb, serverModuleMap)
```

However there seems to be a mismatch for how `next` and `busboy` handle size limits. `next` sets the limit for the entire body whereas `busboy` is for each of the fields.

I am not sure how to proceed from here.

**Comment by mikeacre** [comment]
I am having this issue as well.. form were working no problem with server actions not all of a sudden today I am having this issue. 

Why do devs just randomly decide to implement this kind of behavior? None of the config changes are working and now my forms are limited to 1MB which is insane.

**Comment by nikmatswace** [comment]
I'm also having this problem, having forms limited to 1 MB is a really rough situation to be in if you want to do any kind of image/file uploading.

I'm at Next 14.0.4, is there any kind of workaround?

**Comment by TryingToImprove** [comment]
> I'm also having this problem. Forms being limited to 1 MB is a really rough situation to be in if you want to do any kind of image/file uploading.
> 
> I'm at Next 14.0.4, is there any kind of workaround?

I think you would be able to do it with a client-side fetch and a API route.

```
function submit(formData){
   fetch('/api/upload', { method: 'POST', body: formData })
}

<form action={submit}>...
```

**Comment by IVEN21** [comment]
I'm having the same issue, I persist to handle file form submission in server action rather in client.

**Comment by JaedonSpurlock01** [comment]
I am also having this issue as well. I am trying to upload JSON data to Amazon S3.

**Comment by oxylabsweb** [comment]
Have the same problem. I am sending base64 file string and the data that is received in server action is always limited to 1048576 characters.

**Comment by sendmenas** [comment]
Have the same problem. I am sending base64 file string and the data that is received in server action is always limited to `1048576` characters.
