### ISSUE TITLE
Adding a middleware causes additional requests to /_next/data/**/*.json and their reponses are empty `{}`.

### ISSUE THREAD

**Issue by inside** [vercel/next.js#59295]
### Link to the code that reproduces this issue

https://github.com/inside/repro-next-data-empty-object

### To Reproduce

1. Clone this repo
1. `npm install`
1. `npm run build`
1. `npm start`
1. Open your browser to `http://localhost:3000`
1. Open the devtools
1. Go to the network tab
1. Notice each additional `_next/data` request for each link to a page

![network-tab](https://github.com/vercel/next.js/assets/107884/6df0aab1-3218-42d2-bb67-b1a6ec126a77)

9. Click on either of the request
9. Click on the `Response` tab
9. Notice the empty json response like this `{}`

![request-response](https://github.com/vercel/next.js/assets/107884/01d1dcdf-c550-4117-9c0f-8324ac23ba52)

### Current vs. Expected behavior

**BUG:**

When a middleware is active like this one: `src/middleware.js`, additional requests are made with an empty response `{}`.

A request url example looks like this: `http://localhost:3000/_next/data/K-vmVE_c03yQwV9UdiOv2/page1.json` and its reponse is empty `{}`.

**EXPECTED BEHAVIOR:**

No additional request should be performed. This is the case if you deactivate the middleware.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 7.11.0
Relevant Packages:
  next: 14.0.4-canary.41
  eslint-config-next: 13.5.6
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

If you access the url `http://localhost:3000/_next/data/K-vmVE_c03yQwV9UdiOv2/page1.json` directly in your browser, the `page1` will be displayed like if we are accessing this url `http://localhost:3000/page1`

**Comment by warpdesign** [comment]
May already have been reported #56157
This appears to be intented?

**Comment by inside** [comment]
It probably is. Nevertheless this features has caused huge traffic and cpu spikes and we rolled back the activation of nextjs middlewares. Moreover these requests aren't cached which can explain the spikes:

![image](https://github.com/vercel/next.js/assets/107884/f882b854-148e-4e5c-a190-e339618c4cfd)

In the meantime, we will deactivate the link prefetch of `next/link` to move forward.

**Comment by ijjk** [comment]
In the latest canary these requests are no-ops, they shouldn't cause CPU spikes or incur additional rendering/data fetching and further in the latest version these requests won't have an incorrect status code.
