### ISSUE TITLE
Build error -  Cannot get final name for export 'defaultParsers'

### ISSUE THREAD

**Issue by samasri** [vercel/next.js#59344]
### Link to the code that reproduces this issue

[CodeSandBox](https://codesandbox.io/p/devbox/dev-forked-7zx9k3?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpsupguy00063b6f0n8zl7tk%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpsupguy00023b6fqfr6rd44%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpsupguy00043b6f3twvybzn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpsupguy00053b6f153b8q88%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpsupguy00023b6fqfr6rd44%2522%253A%257B%2522id%2522%253A%2522clpsupguy00023b6fqfr6rd44%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clptxmn5e00023b6enpw2ikw4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fproduct%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clptxmn5e00023b6enpw2ikw4%2522%257D%252C%2522clpsupguy00053b6f153b8q88%2522%253A%257B%2522id%2522%253A%2522clpsupguy00053b6f153b8q88%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpsupguy00043b6f3twvybzn%2522%253A%257B%2522id%2522%253A%2522clpsupguy00043b6f3twvybzn%2522%252C%2522activeTabId%2522%253A%2522clpuaj05e011v3b6e3q8lfcoc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522clpuaj05e011v3b6e3q8lfcoc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### To Reproduce

1. Run `yarn next build` in the codesandbox terminal
2. The error appears in the terminal while compiling

### Current vs. Expected behavior

**Current**

Failed to compile.

```
./backend/package/index.ts + 8 modules
Cannot get final name for export 'defaultParsers' of ./node_modules/@ucast/mongo/dist/es6m/index.mjs


> Build failed because of webpack errors
error Command failed with exit code 1.
```

**Expected**

I expect the app to build successfully

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.4-canary.42
  eslint-config-next: 13.4.19
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.6
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

[Similar issue](https://github.com/vercel/next.js/issues/58643) has been reported earlier and marked as resolved

<sub>[NEXT-1820](https://linear.app/vercel/issue/NEXT-1820/build-error-cannot-get-final-name-for-export-defaultparsers)</sub>

**Comment by rafalzawadzki** [comment]
Same here:
```
> next build

   ▲ Next.js 14.0.4-canary.47
   - Environments: .env

Failed to compile.

./node_modules/.pnpm/posthog-node@3.1.3/node_modules/posthog-node/lib/index.esm.js + 49 modules
Cannot get final name for export 'default.request' of ./node_modules/.pnpm/axios@1.6.2/node_modules/axios/index.js

> Build failed because of webpack errors
   Creating an optimized production build  . ELIFECYCLE  Command failed with exit code 1.`
```

**Comment by samasri** [comment]
Thank you Huozhi, appreciated!

**Comment by huozhi** [comment]
I think the [above solution](https://github.com/vercel/next.js/issues/59344#issuecomment-1846128759) will be the final, as `@prisma/client` is not able to be bundled, and `@cals/prisma` is dependent on it.
