### ISSUE TITLE
Hot reload fails with Turbopack for unencoded (css) chunks in some monorepo setups

### ISSUE THREAD

**Issue by abergenw** [vercel/next.js#59357]
### Link to the code that reproduces this issue

https://github.com/abergenw/next-turbo-css-hot-reload

### To Reproduce

1. Run the reproduction app `npm install && cd packages/app && npm run dev`
2. Edit `LocalTestComponent.scss` and watch hot reload work
3. Edit `TestComponent.scss` and watch hot reload fail

### Current vs. Expected behavior

`TestComponent.scss` lives in a separate package and the chunk name is prefixed with `[project]`. When hot reload is triggered, the `<link/>` tag for this chunk is looked up with the url encoded href for the chunk, leading to the following error:

```
Error: No link element found for chunk
static/chunks/[project]_packages_ui_components_TestComponent_module_scss_module_46ad83.css
```

The original `<link/>` tag is expected to be url encoded but it's not, leading to hot reload failing in this case.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: N/A
  pnpm: 8.11.0
Relevant Packages:
  next: 14.0.4-canary.47
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

<sub>[PACK-2136](https://linear.app/vercel/issue/PACK-2136/hot-reload-fails-with-turbopack-for-unencoded-css-chunks-in-some)</sub>

**Comment by padmaia** [comment]
I'm getting `Error: No link element found for chunk static/chunks/[project]_packages_fd22bf._.css` even when I try to update the local component now. We'll look into it.

**Comment by ForsakenHarmony** [comment]
This should be fixed
