### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by givehug** [vercel/next.js#59364]
### What is the improvement or update you wish to see?

Please add context, with pathname, headers, and everything else to app router page as an argument (as in getServerSideProps). Please also add documentation about how to use it. Thank you.

### Is there any context that might help us understand?

No

**Comment by balazsorban44** [comment]
Hi, it sounds like you are looking for these:

- https://nextjs.org/docs/app/api-reference/file-conventions/page
- https://nextjs.org/docs/app/api-reference/functions/headers

See also:

- https://nextjs.org/docs/app#how-can-i-access-the-request-object-in-a-layout
- https://nextjs.org/docs/app#how-can-i-access-the-url-on-a-page
