### ISSUE TITLE
@vercel/speed-insights/next creates hydration errors

### ISSUE THREAD

**Issue by Thanaen** [vercel/next.js#59379]
### Link to the code that reproduces this issue

https://github.com/Thanaen/next-speedinsights-repro

### To Reproduce

1. Deploy the app on vercel
2. Go to the website and look at the logs

### Current vs. Expected behavior

Expected: No console errors
Current: Hydration errors in console ([418 ](https://legacy.reactjs.org/docs/error-decoder.html/?invariant=418)& [423](https://legacy.reactjs.org/docs/error-decoder.html/?invariant=423))

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 21.1.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4-canary.47
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context
https://next-speedinsights-repro.vercel.app/

**Comment by tobiaslins** [comment]
Hey!

Make sure to add the component in the `body`, otherwise Next.js can't rehydrate!

```tsx
<html lang="en">
      <body className={inter.className}>
         {children}
         <SpeedInsights /> 
      </body>
</html>
```

With that it should work!

**Comment by Thanaen** [comment]
Ah, I didn't think that putting the component outside the body could cause problems! Thanks for the quick reply!

**Comment by wadehammes** [comment]
Im still getting hydration errors from this if I include in the pages/_app.tsx file:

<img width="2168" alt="image" src="https://github.com/vercel/next.js/assets/222170/12ad8259-5587-4434-9048-67b33a960888">

<img width="904" alt="image" src="https://github.com/vercel/next.js/assets/222170/0b89a585-40c6-4965-b292-f7d9f70ff69d">

Removing SpeedInsights from here makes the error go away.

**Comment by tobiaslins** [comment]
Hey @wadehammes !

Which Next.js version are you using? Can you please create us a reproduction example repo so we can investigate further? Thanks!

**Comment by wadehammes** [comment]
> Hey @wadehammes !
> 
> 
> 
> Which Next.js version are you using? Can you please create us a reproduction example repo so we can investigate further? Thanks!

Latest 14.0.4

**Comment by tobiaslins** [comment]
Hey @wadehammes !

Can you please create us a new repository with code that reproduces that error? Thanks a lot!

**Comment by wadehammes** [comment]
> Hey @wadehammes !
> 
> 
> 
> Can you please create us a new repository with code that reproduces that error? Thanks a lot!

Unfortunately, I'm on holiday until the new year. Also, our set up is so unique (styled components, contentful, react query, etc) it may be hard to replicate in a small, simplified code base. I may be able to give temp access to our repo to you when I'm back though.
