### ISSUE TITLE
Minification causes "TypeError: Expected signal to be an instanceof AbortSignal" error with NextJS 14.0.4 + Azure Blob Storage 12.17.0

### ISSUE THREAD

**Issue by fujita-h** [vercel/next.js#59432]
### Link to the code that reproduces this issue

https://github.com/fujita-h/next-azure-blob-repro

### To Reproduce

1. Set `STORAGE_ACCOUNT_NAME` and `STORAGE_ACCOUNT_KEY` of an Azure Storage account (it doesn't need to have any blob containers or blobs in it).
2. `npm run build`
3. `npm run start`
4. Go to http://localhost:3000

### Current vs. Expected behavior

Expected: Show the number of blob containers in the storage account.
Actual: Got error below
```txt
TypeError: Expected signal to be an instanceof AbortSignal
    at new oA (/home/azureuser/next-azure-blob-repro/.next/server/app/page.js:2:33643)
    at /home/azureuser/next-azure-blob-repro/.next/server/app/page.js:2:35119
    at new Promise (<anonymous>)
    at oL (/home/azureuser/next-azure-blob-repro/.next/server/app/page.js:2:35070)
    at oK.fetch (/home/azureuser/next-azure-blob-repro/.next/server/app/page.js:2:44079)
    at oK.sendRequest (/home/azureuser/next-azure-blob-repro/.next/server/app/page.js:2:41832)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #18~22.04.1-Ubuntu SMP Tue Nov 21 19:25:02 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

This problem can be prevented by setting `experimental.serverMinification` to `false`.
Similar to #55682

**Comment by fujita-h** [comment]
The results for 14.0.4-canary were as follows:

- 14.0.3 - **works**
- 14.0.4-canary.10 - **works**
- 14.0.4-canary.16 - **works**
- 14.0.4-canary.17 - **works**
- 14.0.4-canary.18 - **works**
- 14.0.4-canary.22 - **fails**
- 14.0.4-canary.30 - **fails**
- 14.0.4-canary.40 - **fails**
- 14.0.4 - **fails**
- 14.0.5-canary.4 - **fails**

**Comment by ilia-os** [comment]
Im experiencing the same error when upgrading nextjs from 14.0.3 to 14.0.4 : `TypeError: Expected signal to be an instanceof AbortSignal`
The error happens when I build my api route with `revalidate`.
All it does is querying some Airtable data via airtable js client 0.12.2. I wonder if it could also "morph" `fetch` implementation?

Disabling `nextConfig.experimental.serverMinification = false` OR removing route `revalidate` option solves the issue.

**Comment by LizDodion** [comment]
also seeing this in 14.0.4. going to try and downgrade to 14.0.3.

It fails consistently in CI but locally it failed initially then worked

**Comment by triggertoo** [comment]
You can opt out packages from server components bundling by using [serverComponentsExternalPackages](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages). That way, you do not have to disable the serverMinification.

To opt out `@azure/storage-blob` from server components bundling, you can do the following in your `next.config.js`:
```js
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['@azure/storage-blob'],
  },
};

module.exports = nextConfig;
```
