### ISSUE TITLE
Custom server not working for App Router feature

### ISSUE THREAD

**Issue by blackcater** [vercel/next.js#59453]
### Link to the code that reproduces this issue

https://github.com/blackcater/bug-report.next-custom-server

## Project structure

- `server`: is a extremely simple server with express, only single file `server.js`.
- `ui`: is a Next.js app, generated with `npx create-next-app`. **App Router**

### Install dependencies

```bash
pnpm install
```

### Next.js is fine

```bash
pnpm dev:ui
```

### Run custom server

```bash
pnpm dev:server
```

<h1>Tailwindcss not working....</h1>

```log
warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
warn - https://tailwindcss.com/docs/content-configuration
```

### Run `express.js` in `ui` directory

`express.js` file in `ui` directory is a copy of `index.js` in `server` directory.

```bash
pnpm dev:ui:server
```

<h1>Everything is fine now!</h1>

### Current vs. Expected behavior

Current: When custom server is in a different directory from next.js root dir. Tailwindcss will not woking.

Expected: Tailwindcss should working.

Maybe postcss not working instead.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.21
  pnpm: 8.12.0
Relevant Packages:
  next: 14.0.5-canary.5
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by blackcater** [comment]
Anyone can help me?

**Comment by kcoet** [comment]
Having the same problem. I have tried version **14.1.1-canary.10** it doesn't seem to be fixed. Has someone managed to solve this problem?

**Comment by Edwin-Luijten** [comment]
Same here, have the same setup using next: 14.2.4
