### ISSUE TITLE
`[...catchall]` routes do not work with turbopack

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#59502]
### Link to the code that reproduces this issue

https://github.com/Fredkiss3/turbopack-parallel-routes-bug

### To Reproduce

1.  Start the dev server with turbopack : `npm run dev -- --turbo`
2. Open the home page and navigates to`/other` using the links on the header, you will see that only the content of the parallel route in `@parallel/page.tsx` is shown when navigating
3. While on `/other` reload the page, the content will disappear, not even default.tsx is shown.

### Current vs. Expected behavior

Turbopack doesn't consider `[...catchAll]` routes and instead renders an empty content, while it works fine on webpack.

## Current behavior :
https://github.com/vercel/next.js/assets/38298743/d23fdde6-e687-445d-9a1c-6f94f98da9fe

## Expected behavior :
https://github.com/vercel/next.js/assets/38298743/d82d46fc-8fff-42d9-bd88-c0a37e64b251

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 8.7.1
Relevant Packages:
  next: 14.0.5-canary.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

<sub>[NEXT-2038](https://linear.app/vercel/issue/NEXT-2038/[catchall]-routes-do-not-work-with-turbopack)</sub>

**Comment by Fredkiss3** [comment]
cc @ztanner
I think this was implemented in webpack in this [PR](https://github.com/vercel/next.js/pull/58215), but turbopack support is not there yet.

**Comment by subvertallchris** [comment]
Just chiming in to confirm this. Fingers crossed for a fix soon!
