### ISSUE TITLE
useRouter not working in a child client component

### ISSUE THREAD

**Issue by Andriy-Kulak** [vercel/next.js#59515]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
"next": "^14.0.0"
```

### Which example does this report relate to?

none

### What browser are you using? (if relevant)

n/a

### How are you deploying your application? (if relevant)

this is in localhost

### Describe the Bug

`useRouter` does not work in child client component. Can someone please explain why `useRouter` is not working in a "use client" component? I know I can use `Link` but in more complex async scenarios like form submission, that is not an option. Can anyone help?

**Parent Server Component `dashboard/page.tsx`**
```ts
import ClaimsDashboard from "@/components/ClaimsDashboard";
import getClaims from "@/hooks/getClaims";

export default async function Dashboard() {
  const { data, error } = await getClaims();
  return (
    <>
      <ClaimsDashboard data={data} />
    </>
  );
}
```

Child Client `ClaimsDashboard` component
```ts
"use client";

import { DetailedClaim } from "@/types";
import { useRouter } from "next/navigation";
import Header from "../Header";
import SecondaryCTA from "../SecondaryCTA";

export default async function ClaimsDashboard({
  data,
}: {
  data: DetailedClaim[] | null;
}) {
  /const router = useRouter();
  return (
    <>
      <Header cta={<ButtonAccount />} />
      <SecondaryCTA
        text="Create New"
        icon={null}
        onClick={() => router.push("/dashboard/create")}
      />
    </>
  );
}

### Expected Behavior

I expect to be able to use `useRouter` in client components.

### To Reproduce

create a server component and put a "use client" component in it with `useRouter`. it will not work. I get error below.

```
async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.
```

**Comment by aazarkhish** [comment]
I think the error message is clear and the problem is not useRouter. 
The problem is ClaimsDashboard being a client component should not be an async function.

**Comment by Andriy-Kulak** [comment]
ah ok if I remove the await data then it works. ok interesting. thanks for reply
