### ISSUE TITLE
@next/third-parties: The 'src' URL for Google Tag Manager does not match what Google wants me to configure

### ISSUE THREAD

**Issue by bourquep** [vercel/next.js#59511]
### Link to the code that reproduces this issue

https://github.com/bourquep/gtm-url-issue-repro

### To Reproduce

1. Start the application (`next dev`)
2. Open the Chrome Network inspector
3. Observe that the GTM script is being fetched via the `https://www.googletagmanager.com/gtm.js?id=${gtmId}` URL

However, the tag that Google Ads wants me to install is supposed to be fetched via the `https://www.googletagmanager.com/gtag/js?id=${gtmId}` URL

### Current vs. Expected behavior

I expected the GTM script to be fetched from `https://www.googletagmanager.com/gtag/js?id=${gtmId}`, but it is being fetched from `https://www.googletagmanager.com/gtm.js?id=${gtmId}`

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.7
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

I'm not sure if `/gtag/js?id=${gtmId}` works for all GTM scripts, all I know is that I started a Google Ads campaign which asks me to install the script from that URL, and not `/gtm.js?id=${gtmId}`.

**Comment by housseindjirdeh** [comment]
Hi @bourquep! Google Tag Manager is particularly the `gtm.js` file and lets you manage many tags, including Google Ads, through their admin panel. The `next/third-parties` library provides a component for Google Tag Manager, but not Google tag at a high-level, although the Google Analytics component uses `gtag.js`. You have a few options here:

1. Switch to using Google Tag Manager and load Google Ads through there. See this [help guide](https://support.google.com/tagmanager/answer/7582054?hl=en#:~:text=Tag%20Manager%20fully%20supports%20Google,Manager%20is%20already%20in%20use.&text=If%20you%20were%20using%20GA4,upgraded%20to%20the%20Google%20tag) for details. That way you can use the GTM component
2. Include the `gtag` script manually.

If this is a one-off, the second option is fine. If you plan on including more tags in the future and are planning to use GTM anyway, then the first option might make sense for you.

Let me know if you have any questions. Will close this issue for now but happy to re-open if needed.

**Comment by bourquep** [comment]
@housseindjirdeh Thank you for the detailed reply! I will look into option 1, thank you!
