### ISSUE TITLE
Default value of property "prefetch" in Link component

### ISSUE THREAD

**Issue by onehitdragon** [vercel/next.js#59529]
### Link to the code that reproduces this issue

https://github.com/onehitdragon/my-app

### To Reproduce

0. I use Link in "next/link"
1. I specify "prefetch" property in Link component:
![image](https://github.com/vercel/next.js/assets/83100703/a1e5f1bc-db04-4d4e-ab36-006ac153ca9d)
2. I enter "/" route and open devtool->network it show:
![image](https://github.com/vercel/next.js/assets/83100703/c724afd8-e708-4d29-9be0-76c8d225e5c8)
Prefetch work perfect.
3. But when i remove "prefetch" property in Link component, and rebuild(next build && next start):
![image](https://github.com/vercel/next.js/assets/83100703/2872a43b-41bd-42d6-b2bb-397936e58b4e)
4. Repeat step 2.
![image](https://github.com/vercel/next.js/assets/83100703/42a5ca69-9e5e-4ce6-a02d-865be2e05095)
It only fetch to "home?_rsc=acgkz" and it dont fetch page-7c1c3ff05fe.js file so prefetch fail.
I read document (https://nextjs.org/docs/app/api-reference/components/link#prefetch) prefetch property "Defaults to true"

### Current vs. Expected behavior

i dont want to specify "prefetch" property in Link component.

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

**Comment by OlegLustenko** [comment]
Behavior was changed, check description in this PR
https://github.com/vercel/next.js/pull/48383
