### ISSUE TITLE
Router.query has missing parameters when using a catch-all rewrite in comination with middleware

### ISSUE THREAD

**Issue by WartClaes** [vercel/next.js#59561]
### Link to the code that reproduces this issue

https://github.com/WartClaes/nextjs-middleware-rewrite-bug

### To Reproduce

1. run `yarn build`
2. run `yarn start`
3. go to `http://localhost:3000`
4. click on the first link (/detail/foo/bar/123)
5. validate output of `router.query`
6. click on the second link (/article/foo/bar/123)
7. validate output of `router.query`

### Current vs. Expected behavior

*Current behaviour*
On the rewritten route, the `slug` query parameter is missing

*Expected behaviour*
On both routes, the `slug` query parameter should be present

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64

Binaries:
      Node: 18.18.2
      npm: 9.8.1
      Yarn: 1.22.17
      pnpm: N/A

Relevant packages:
      next: 13.0.4-canary.5
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Additional context

This issue only happens when running the builded version of the app. When in dev mode it all works as expected.

It seems to be that the issue lies with the combination of a catch-all rewrite and the existence of the `middleware.ts` file. When removing the middleware file it all works as expected.

I narrowed it down to `next@13.0.4-canary.5`. All previous canary version work fine, but here it stops.

**Comment by WartClaes** [comment]
@ijjk @timneutkens any ideas on how to fix this (I'm tagging you two because you are the most active here)? This is a blocker in upgrading Next to a newer version. Since I'm not the only one running into this issue. There are a lot of them in the issue list it seems. 

It might be nice to at least have a response if it's possible to even fix it? (or if there is no intention anymore to support the pages router). That would at least give us an idea if we are able to continue using Next.

**Comment by tommarien** [comment]
We are willing to submit a pr for this, but we have no clue where to start looking for this problem, we are blocked from upgrading to latest next because of this, please advise!

**Comment by Pjai1** [comment]
@ijjk Any suggestion on how to best proceed here? 🙏

**Comment by WartClaes** [comment]
@ijjk @timneutkens any suggestions on how we can fix this issue?

**Comment by tommarien** [comment]
Please advise, we need to upgrade to have this fixed https://github.com/vercel/next.js/discussions/19693

**Comment by tommarien** [comment]
@ijjk @timneutkens Thanks both ❤️

**Comment by WartClaes** [comment]
Thanks guys!
