### ISSUE TITLE
Can't Deploy v14 to Azure Static Web Apps because Azure doesn't support Node v 20

### ISSUE THREAD

**Issue by rebeccapeltz** [vercel/next.js#59582]
### Link to the code that reproduces this issue

https://github.com/rebeccapeltz/demo-azure-nextjs-client-server-static

### To Reproduce

1.  Install Next v14.0.2 in your app
2. Test locally and see that it runs as expected
3. Set up Static Web App on Azure linked to Github
4. Push to GitHub
5. Check GitHub Actions and see error about needed Node v20
6. Add engines to package.json ` "engines": {"node": ">=20.0.0"}`
7. Push to GetHub
8. Check GitHubActions and see error that Node v20 not  supported

<img width="678" alt="neednode20" src="https://github.com/vercel/next.js/assets/354444/f16a853c-a9d9-4b74-8acd-83449fdd8411">
<img width="958" alt="node20notallowed" src="https://github.com/vercel/next.js/assets/354444/a8113e92-0c77-4edd-a041-12efed1f9f4b">

### Current vs. Expected behavior

Currently you can host a Next app on Azure if the version of Next is < 14

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
This is my local system - not sure how to run next info on Azure 
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
    Binaries:
      Node: 20.8.0
      npm: 10.2.4
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.8
      eslint-config-next: 13.3.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
    Next.js Config:
      output: standalone
```

### Which area(s) are affected? (Select all that apply)

Operating System (Windows, MacOS, Linux)

### Additional context

I am hosting my application on Azure Static Web Applications which uses GitHub Actions.

**Comment by OlegLustenko** [comment]
But v18 should be enough for Nextjs 14

**Comment by wyattjoh** [comment]
Our most recent release only requires Node.js `>=18.17.0`:

https://github.com/vercel/next.js/blob/c9f859e6bea4a547d3946e99c5242bb419155598/packages/next/package.json#L321-L323

Which seems to be supported: https://learn.microsoft.com/en-us/azure/static-web-apps/languages-runtimes#api
