### ISSUE TITLE
Docs: The navigation title on the Vitest testing page is incorrect.

### ISSUE THREAD

**Issue by NEKOYASAN** [vercel/next.js#59609]
### What is the improvement or update you wish to see?

The navigation title of the Vitest Testing page is **Jest** when the Pages Router is selected.
When App Router is selected, it is displayed without any problem

### Is there any context that might help us understand?

Here is a screenshot of the current version
|App Router | Pages Router |
|------------|--------------|
|<img width="300" alt="App Router Image" src="https://github.com/vercel/next.js/assets/17000370/cfeafcde-a6af-4f39-ad11-818b6774aea3"> | <img width="300" alt="Pages Router Image" src="https://github.com/vercel/next.js/assets/17000370/22b3eeaf-6334-41a0-8a6b-f93a2d3247d6"> |

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/testing/vitest

**Comment by leerob** [comment]
This has been fixed, thank you!
