### ISSUE TITLE
Argument of type '"replace"' is not assignable to parameter of type 'RedirectType | undefined'

### ISSUE THREAD

**Issue by pawix135** [vercel/next.js#59608]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/next-navigation-redirect-type-error-zml87d

### To Reproduce

1. Open CodeSandbox
2. Go to `/app/api/route.ts`
3. Check the `redirect` error
![invalid_type](https://github.com/vercel/next.js/assets/20132206/173a9cb6-4b8d-4abf-97f2-6177e3f2ff38)
![invalid_type2](https://github.com/vercel/next.js/assets/20132206/7e2a4756-ce90-40f7-a40e-a069ba978905)
![invalid_type3](https://github.com/vercel/next.js/assets/20132206/4e218aef-22ae-4739-ad39-4671cd6feccc)

### Current vs. Expected behavior

Currently `redirect("/some/path", "replace" | "push")`  shows invalid argument type.
Ideally, there shouldn't be any errors as the expected behavior :/

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.12
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link), TypeScript (plugin, built-in types)

### Additional context

I've tested it on next@14.0.4 and next@14.0.5-canary.12. 
Used TypeScript@5.3.2 `node_modules/typescript/lib` and default VS Code Version TypeScript@5.3.2.

**Comment by mshokoya** [comment]
it look like RedirectType is a enum not string
<img width="767" alt="sc" src="https://github.com/vercel/next.js/assets/13862160/bc1818d4-4432-4fa0-a7bc-8e438eb1e7ad">

**Comment by mshokoya** [comment]
> ### Link to the code that reproduces this issue
> https://codesandbox.io/p/sandbox/next-navigation-redirect-type-error-zml87d
> 
> ### To Reproduce
> 1. Open CodeSandbox
> 2. Go to `/app/api/route.ts`
> 3. Check the `redirect` error
>    ![invalid_type](https://private-user-images.githubusercontent.com/20132206/290433726-173a9cb6-4b8d-4abf-97f2-6177e3f2ff38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTY5ODUsIm5iZiI6MTcwMjU5NjY4NSwicGF0aCI6Ii8yMDEzMjIwNi8yOTA0MzM3MjYtMTczYTljYjYtNGI4ZC00YWJmLTk3ZjItNjE3N2UzZjJmZjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIzMzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYzcwNWVhYTYwMzU1MDllMjA5NjdkYTU0YjczNjk3MjlkMWRkOWUxYWMyNzNiY2FhMGUxNzE4OTFhM2QzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.If4vdEo2w-wgz86s_ld7p-j_bj53ffDVgocOtJA63RU)
>    ![invalid_type2](https://private-user-images.githubusercontent.com/20132206/290433851-7e2a4756-ce90-40f7-a40e-a069ba978905.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTY5ODUsIm5iZiI6MTcwMjU5NjY4NSwicGF0aCI6Ii8yMDEzMjIwNi8yOTA0MzM4NTEtN2UyYTQ3NTYtY2U5MC00MGY3LWE0MGUtYTA2OWJhOTc4OTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIzMzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTVkNTRkYjQ3Y2Y5MTZjZjUwMTkwN2I5YTQ5YzljY2E1NjVjYzU3ZmY0YTUzMTM2OGQ4NTUwZGU4MzBjM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.au_Yiu7zlkRuryR-sAuXxznTkg-TN0UJxC9ArD6ddXY)
>    ![invalid_type3](https://private-user-images.githubusercontent.com/20132206/290434410-4e218aef-22ae-4739-ad39-4671cd6feccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1OTY5ODUsIm5iZiI6MTcwMjU5NjY4NSwicGF0aCI6Ii8yMDEzMjIwNi8yOTA0MzQ0MTAtNGUyMThhZWYtMjJhZS00NzM5LWFkMzktNDY3MWNkNmZlY2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDIzMzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTVkZGFiMDdhZDBlMDE0YTMwOTE3NDU1NDM1ODQ0ZTRhODIxNDRhNzM5YjRjYzhiY2ExZmE1YTllNDNmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NHa6qYsCX2oZteqUANlyVaxFQcLmE7E07OCh1hBNjAQ)
> 
> ### Current vs. Expected behavior
> Currently `redirect("/some/path", "replace" | "push")` shows invalid argument type. Ideally, there shouldn't be any errors as the expected behavior :/
> 
> ### Verify canary release
> * [x]  I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> ```shell
> Operating System:
>   Platform: win32
>   Arch: x64
>   Version: Windows 10 Pro
> Binaries:
>   Node: 20.10.0
>   npm: N/A
>   Yarn: N/A
>   pnpm: N/A
> Relevant Packages:
>   next: 14.0.5-canary.12
>   eslint-config-next: 14.0.3
>   react: 18.2.0
>   react-dom: 18.2.0
>   typescript: 5.3.2
> Next.js Config:
>   output: N/A
> ```
> 
> ### Which area(s) are affected? (Select all that apply)
> Routing (next/router, next/navigation, next/link), TypeScript (plugin, built-in types)
> 
> ### Additional context
> I've tested it on next@14.0.4 and next@14.0.5-canary.12. Used TypeScript@5.3.2 `node_modules/typescript/lib` and default VS Code Version TypeScript@5.3.2.

It looks like RedirectType is a enum, not a string

<img width="767" alt="sc" src="https://github.com/vercel/next.js/assets/13862160/33ccf25e-278a-4f47-9908-9ab1c08cde63">

**Comment by mshokoya** [comment]
it looks like RedirectType is a enum, not a string.

Here's an example of how to use it:
<img width="764" alt="Screenshot 2023-12-14 at 23 51 40" src="https://github.com/vercel/next.js/assets/13862160/a2793a2b-256c-4370-93d3-7dc2701455c0">

**Comment by pawix135** [comment]
@mshokoya You're right... Thanks for help.
