### ISSUE TITLE
Docs: give examples of how to make data flow upwards in RSC

### ISSUE THREAD

**Issue by barroudjo** [vercel/next.js#59614]
### What is the improvement or update you wish to see?

Sometimes a layout has components that need data that can only be fetched in a lower route segment (for example because in that lower route segment we have access to the dynamic param that is used in the fetching of data).
What are the recommended patterns for making that data available to the layout (or layout components) ? I haven't seen that answered in the documentation.

I'm assuming it will involve client components, because layouts RSC can only be used when the state it has is shared across the pages it is used in, and in this case the state changes.

I solved it in my own way, and I can post it here, but before I'd like to see if there is already a recommended pattern that I somehow missed ;-).

### Is there any context that might help us understand?

This situation is not described in the  [router FAQ](https://nextjs.org/docs/app#frequently-asked-questions), and parallel routes don't solve it either.

**Comment by nicnocquee** [comment]
I had this problem before and someone mentioned to use parallel route and it worked! https://x.com/goncy/status/1718971331524354267?s=20

**Comment by barroudjo** [comment]
> I had this problem before and someone mentioned to use parallel route and it worked! https://x.com/goncy/status/1718971331524354267?s=20

Thanks @nicnocquee ! But I think (as the name "parallel routes" suggests), this only works if the parallel route / "pseudo layout" where I want the data to be available is at the route segment with the dynamic param in my example.
But in my case I want that layout to be above, because it is shared by all routes.

**Comment by OhKai** [comment]
You are right that you need a Client Component for that, since the layout won't be re-rendered on route navigations below it. 
Next provides some hooks for that purpose that update Client Components when the child route segments change:
https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segment

**Comment by barroudjo** [comment]
> You are right that you need a Client Component for that, since the layout won't be re-rendered on route navigations below it. Next provides some hooks for that purpose that update Client Components when the child route segments change: https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segment

You are right ! Thanks ! That use case could maybe be made clearer in the documentation.
