### ISSUE TITLE
Docs: Ability to trace Hydration errors by filename.

### ISSUE THREAD

**Issue by mdtausifiqbal** [vercel/next.js#59628]
### What is the improvement or update you wish to see?

I want to easily trace hydration errors by filename and line-no.

### Is there any context that might help us understand?

Error: Hydration failed because the initial UI does not match what was rendered on the server.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/react-hydration-error

**Comment by leerob** [comment]
Agreed, this would be a nice improvement! This isn't a documentation change, but we'll take this into consideration regardless.
