### ISSUE TITLE
Docs: Wrong index.html in "Getting Started with React"

### ISSUE THREAD

**Issue by andrehora** [vercel/next.js#59630]
### What is the improvement or update you wish to see?

In the page "Getting Started with React" (https://nextjs.org/learn/react-foundations/getting-started-with-react), the second `index.html` currently is:

```html
<html>
  <body>
    <div id="app"></div>
    <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script type="text/jsx">
      const app = document.getElementById('app');
      ReactDOM.render(<h1>Develop. Preview. Ship.</h1>, app);
    </script>
  </body>
</html>
```

However, it should be:

```html
<html>
  <body>
    <div id="app"></div>
    <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <script type="text/javascript">
      const app = document.getElementById('app');
      ReactDOM.render(<h1>Develop. Preview. Ship.</h1>, app);
    </script>
  </body>
</html>
```

... so that we can have the error: `Uncaught SyntaxError: expected expression, got '<'`

### Is there any context that might help us understand?

The actual example is not working as expected.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/react-foundations/getting-started-with-react

**Comment by dotslashbit** [comment]
Working on it

**Comment by leerob** [comment]
We recently updated this to React 18, please let me know if it works for you!

https://nextjs.org/learn/react-foundations/getting-started-with-react
