### ISSUE TITLE
ISR works correctly but at build time is treated as static

### ISSUE THREAD

**Issue by StefanoLazzaroni** [vercel/next.js#59653]
### Link to the code that reproduces this issue

https://github.com/surething171/bug

### To Reproduce

1. Build the application using `npm run build`
2. Check in the console the response:
"Route (app)                              Size     First Load JS
┌ ○ /                                    137 B            82 kB
└ ○ /_not-found                          875 B          82.7 kB
+ First Load JS shared by all            81.8 kB
  ├ chunks/938-5e061ba0d46125b1.js       26.7 kB
  ├ chunks/fd9d1056-735d320b4b8745cb.js  53.3 kB
  ├ chunks/main-app-573a74cf423875d0.js  221 B
  └ chunks/webpack-b8871e92601e993d.js   1.64 kB

○  (Static)  prerendered as static content"

3. Execute the application using `npm run start`
4. The application correctly invalidates the cache but in the terminal, using `npm run build`, it says that / is STATIC

### Current vs. Expected behavior

Expected behavior: Static generated + JSON content (ISR)
Actual behavior: Static generated

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.8.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by wyattjoh** [comment]
This is actually correct! Next.js says that the page was "prerendered as static content". When ran with `next start` or deployed to Vercel, after the revalidation time has expired (after 3 seconds), a subsequent request will serve the stale version and send a revalidation request in the background so that the next request will return the updated value.

**Comment by StefanoLazzaroni** [comment]
Ok, but why then, using pages, it says this:
Route (pages)                              Size     First Load JS
┌ ● / (ISR: 10 Seconds) (612 ms)           286 B          78.2 kB
├   /_app                                  0 B            77.9 kB
└ ○ /404                                   182 B          78.1 kB
+ First Load JS shared by all              79.4 kB
  ├ chunks/framework-7ed162ceef4c09d0.js   45.2 kB
  ├ chunks/main-fdf56fc4602be5bb.js        31.6 kB
  ├ chunks/pages/_app-a095711f9a975fe3.js  298 B
  ├ chunks/webpack-8fa1640cc84ba8fe.js     750 B
  └ css/bd5813b2469d935d.css               1.52 kB

○  (Static)  prerendered as static content
●  (SSG)     prerendered as static HTML (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
   
One of the two console logs are wrong, and imo having the console telling you that in / there is a revalidation every 10 seconds is more accurate.

**Comment by StefanoLazzaroni** [comment]
@wyattjoh
