### ISSUE TITLE
Docs: correct wrongly highlighted lines 

### ISSUE THREAD

**Issue by Arsalan04** [vercel/next.js#59709]
### What is the improvement or update you wish to see?

Lines 40-42 should be highlighted
![image](https://github.com/vercel/next.js/assets/40821503/513738c7-1bd5-4b93-95a4-2ec374883ed4)

### Is there any context that might help us understand?

The documentation is for practising streaming components using React Suspense.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/streaming

**Comment by Abhinavcode13** [comment]
**Highlighted** in the sense? @Arsalan04
