### ISSUE TITLE
Parallel routes with catch-all segments cause error "could not find the module in the React Client Manifest"

### ISSUE THREAD

**Issue by RJFelix** [vercel/next.js#59747]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/stoic-booth-mqhx92

### To Reproduce

Have a Next app with some parallel routes with catch-all segments, where some parallel route page.tsx files import components, possibly including non-default exports. Example structure:

```
/app
  layout.tsx
  /[locale]
    layout.tsx
    /dashboard
      layout.tsx
      /@header
        /[...dir]
          /components
            MyLink.tsx
          page.tsx
      /[instanceId]
        layout.tsx
        /home
          page.tsx
```

with this file content, and otherwise minimal content as normal:

```
// app/[locale]/dashboard/layout.tsx
export default function DashboardLayout({ children, header }) {
  return (
    <main>
      <nav>{header}</nav>
      <article>{children}</article>
    </main>
  )
}

// app/[locale]/dashboard/@header/page.tsx
import MyLink, { BonusLink } from "./components/page.tsx"

export default function Header() {
  return (
    <div>
      <MyLink href="/some-path" />
      <BonusLink href="/another-path" />
    </div>
  )
}

// app/[locale]/dashboard/@header/components/MyLink.tsx
import Link from "next/link"

export function BonusLink({ href }) {
  return <Link href={href}>Bonus link</Link>
}

export default function MyLink({ href }) {
  return <Link href={href}>Linky link</Link>
}
```

1. Run the Next dev server **without Turbopack**
2. Navigate to `/en/dashboard/abc123/home`
3. Errors

### Current vs. Expected behavior

Expected behavior: should render the page + parallel routes according to the layout tree.

Actual behavior: errors about not finding modules in the React Client Manifest:

```
 ✓ Compiled /[locale]/dashboard/[instanceId]/home in 1201ms (488 modules)
 ⨯ Error: Could not find the module "/workspaces/workspace/app/[locale]/dashboard/@header/components/MyLink.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
 ⨯ Error: Could not find the module "/workspaces/workspace/app/[locale]/dashboard/@header/components/MyLink.tsx#BonusLink" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
 ⨯ Error: Could not find the module "/workspaces/workspace/app/[locale]/dashboard/@header/components/MyLink.tsx#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)
digest: "1645395023"
 ⨯ Internal error: Error: Could not find the module "/workspaces/workspace/node_modules/next/dist/client/link.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at /workspaces/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:263710
    at eN (/workspaces/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:263905)
    at /workspaces/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:278460
    at Array.toJSON (/workspaces/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:279650)
    at stringify (<anonymous>)
    at /workspaces/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:266006
    at ez (/workspaces/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:266085)
    at eH (/workspaces/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:266486)
    at Timeout._onTimeout (/workspaces/workspace/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:262984)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

Note: it seems to work fine with Turbopack enabled, but I can't use it in my app yet because it lacks full Sass support.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: arm64
  Version: #1 SMP PREEMPT Tue Oct 10 20:38:06 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 10.2.5
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 13.4.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.0.3
```

### Which area(s) are affected? (Select all that apply)

App Router, Dynamic imports (next/dynamic), Routing (next/router, next/navigation, next/link)

### Additional context

Side note - I'm only trying to do this because `@parallel/default.tsx` doesn't seem to work with nested dynamic routes, or something like that; the parallel routes 404 rather than fall back to their `default.tsx`. I haven't been able to narrow down that issue to a report that meets the criteria, though. I'd prefer to use a structure like this, which seems fine by the docs but doesn't work on routes not matched by a specific page.tsx:

```
   /dashboard
      layout.tsx
      /@header
        default.tsx <-- shown for everything that doesn't have a matching page.tsx
        /[instanceId]
          /page-with-different-header
            page.tsx <-- only shown for this particular route
```

<sub>[NEXT-1908](https://linear.app/vercel/issue/NEXT-1908/parallel-routes-with-catch-all-segments-cause-error-could-not-find-the)</sub>

**Comment by CalebMacdonaldBlack** [comment]
Are they any updates on this one? 

Are there any ideas as to what might be causing it?

**Comment by samura** [comment]
I have the same issue: I have a `@menu` slot in which I designed 2 different navigations: one for admin and one for users, using the routes `/a/*` and `/b/*`. For that I used the slot path: `@menu/a/[...catchAll]/page.tsx` but I'm getting the same error.

**Comment by khanhtn91** [comment]
I have the same issue, the error shows when I import any client component in [...catchAll]

**Comment by sbkobaidze** [comment]
I have the same issue,

> I have the same issue, the error shows when I import any client component in [...catchAll]/layout.tsx

Exact same situation on my side as well.
