### ISSUE TITLE
`maxDuration` not a valid next.js entry export value

### ISSUE THREAD

**Issue by steveafrost** [vercel/next.js#59753]
### Link to the code that reproduces this issue

https://github.com/steveafrost/vercel-rsc-maxDuration

### To Reproduce

1. Clone & open repository
2. Follow [Next.js instructions](https://nextjs.org/docs/app/building-your-application/configuring/typescript#typescript-plugin) to "Select Typescript Version" within VSCode and use the Workspace Version
3. Observe `export const maxDuration = 60` within page.tsx has a Typescript error from Next.js with message `"maxDuration" is not a valid Next.js entry export value.`

### Current vs. Expected behavior

Current Behavior
- Typescript error when initializing and assigning maxDuration within a `page.tsx` file using App Router

Expected Behavior
- No type error and additional info provided like `export const revalidate = 300` provides within same file. This expected behavior comes from the documentation provided in route-segment-config [here](https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#maxduration)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: macOS
  Version: 14.2
Binaries:
  Node: 20.10.0
  pnpm: 8.12.1
```

### Which area(s) are affected? (Select all that apply)

App Router, TypeScript (plugin, built-in types)

### Additional context

I retested using next@canary which was 14.0.5-canary.18 at the time of this writing. The bug exists in this latest canary version as well. If I select "Use VSCode Version" for Typescript it selects 5.3.2 and the error goes away but there is no additional context on hover like there is for `revalidate`.

The use case I have is a RSC which calls a Server Action in a separate file w/ "use server" at the top.

**Comment by nuthinking** [comment]
Since we are at it, `export const maxDuration = 45;` doesn't work on my Pro account (not an edge function). How can it be so hard to change the timeout? Opened a ticket.

**Comment by bacqueyrisses** [comment]
I'm having the same issue. Exporting the constant works as expected but leaves an error in the IDE. 
![CleanShot 2023-12-21 at 16 22 03@2x](https://github.com/vercel/next.js/assets/96829831/3038df0b-848f-41e3-b9af-e0669b8e3cf5)

**Comment by chrysb** [comment]
Same issue.

**Comment by samcx** [comment]
Closing this since this has been fixed recently!

**Comment by magoz** [comment]
@samcx is the fix only available in canary?

**Comment by bacqueyrisses** [comment]
> @samcx is the fix only available in canary?

Yes! The fix should be out soon in the stable version.
