### ISSUE TITLE
Parallel routes inside the root layout will cause the params prop to be undefined

### ISSUE THREAD

**Issue by mabouguerra** [vercel/next.js#59809]
### Link to the code that reproduces this issue

https://github.com/mabouguerra/parallel-routes-issue

### To Reproduce

1. Start the application in development (npm run dev)
2. Navigate to `/login`
3. Observe the message in the terminal

### Current vs. Expected behavior

I have an app that implements localization as shown in the [docs](https://nextjs.org/docs/app/building-your-application/routing/internationalization), and when I tried to add a parallel route to the root layout, I get these warnings/errors in the terminal (although the app itself works normally):

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
 ⨯ app/[lang]/layout.js (1:63) @ lang
 ⨯ TypeError: Cannot read properties of undefined (reading 'lang')
    at RootLayout (./app/[lang]/layout.js:8:49)
    at stringify (<anonymous>)
> 1 | export default function RootLayout({ children, auth, params: { lang } }) {
    |                                                               ^
  2 |   return (
  3 |     <html lang={lang}>
  4 |       <body>
  ``` 
  
What's interesting is when I put all the pages in a routes group and create a layout for them there, everything seems fine. As you can see the `with-group` branch of the repo above.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by ztanner** [comment]
Thanks for the report! This should be fixed by https://github.com/vercel/next.js/pull/60401
