### ISSUE TITLE
Open graph image doesn't work in production in vercel

### ISSUE THREAD

**Issue by nicnocquee** [vercel/next.js#59853]
### Link to the code that reproduces this issue

https://github.com/nicnocquee/vercel-og-nextjs/tree/main

### To Reproduce

1. Go to https://vercel.com/docs/functions/edge-functions/og-image-generation/og-image-examples#
2. Click Deploy, to deploy to vercel
3. Then go to `<vercel deployment url>/api/dynamic-image?username=hello`
4. Nothing appears.

### Current vs. Expected behavior

Expected to see the dynamically generated image. But instead got empty image and errors in the backend:

```
TypeError: Fetch API cannot load: blob:noto-sans-v27-latin-regular.5dda3fca77107598.ttf
    at (node_modules/next/dist/compiled/@vercel/og/index.edge.js:18788:19)
    at (webpack/bootstrap:21:0)
    at (node_modules/next/dist/esm/server/og/image-response.js:8:17)
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:05 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6031
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 4.0.2
  pnpm: 8.12.1
Relevant Packages:
  next: 14.0.5-canary.22
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata (metadata, generateMetadata, next/head), Middleware / Edge (API routes, runtime)

### Additional context

Running the production build locally worked. Only when running in Vercel it doesn't work.

**Comment by frantic** [comment]
Same — all prod usages of `@vercel/og` are turning 200 and an empty page. Same warning in the logs.

Testing few versions of `@vercel/og`, `0.5.0` is broken, but `0.0.16` seems to work. Most likely it's a Vercel server issue with serving that font, 0.0.16 doesn't seem to be using it.

**Comment by ofhouse** [comment]
Hello folks,
we had an [incident](https://www.vercel-status.com/incidents/chv6qxv3szlm) on Vercel that prevented og images from being generated correctly.

We have since implemented & rolled out a fix.
Can you please try to create a new deployment to see if the error still persists?

**Comment by nicnocquee** [comment]
Yes it's fixed now! Thanks!
