### ISSUE TITLE
Static and dynamic metadata not working

### ISSUE THREAD

**Issue by darincon** [vercel/next.js#59873]
### Link to the code that reproduces this issue

https://github.com/darincon/metadata-issues

### To Reproduce

1. Start the application in development (npm run dev)
2. Inspect page and check for title and description in <head>

### Current vs. Expected behavior

**Current behaviour**
Using static and dynamic metadata doesn't work and the metadata is not inserted in the html document.

**Expected behaviour**
Using static and dynamic metadata should result in the webpage to have those tags inserted within the `<head>` of the html document

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata (metadata, generateMetadata, next/head)

### Additional context

I tested the code in different projects and different Next versions including the latest canary. Neither static nor dynamic metadata works.

Using `<Head>` and `<meta>` works as intended

**Comment by JonShort** [comment]
I think to use static / dynamic metadata in the style of your example the project needs to be built with [app router](https://nextjs.org/docs/app)

The example is using the [pages router](https://nextjs.org/docs/pages), which requires `<Head>` to be used - see docs here - https://nextjs.org/docs/pages/api-reference/components/head

Here's an example of how the metadata for your example would be added using the pages router:

```diff
+ import Head from "next/head";

import Layout from "@/components/layout"

- export const metadata = {
-  title: "Create Next App",
-  description: "Generated by create next app",
- }

export default function Home() {
  return (
    <Layout>
+      <Head>
+        <title>Create Next App</title>
+        <meta name="description" content="Generated by create next app" />
+      </Head>
      <div>This is an example</div>
    </Layout>
  )
}
```

**Comment by darincon** [comment]
Using `<head>` and `<meta>` works fine but the static and dynamic metadata is a a lot better when you have a lot of properties.

Is it really a requirement to use app router for this? I haven't found anything specifying that static or dynamic metadata doesn't work with pages router

**Comment by darincon** [comment]
Found it. @JonShort is right. Dynamic and Static metadata is only for App Router. Closing this issue
