### ISSUE TITLE
Next API routes are being pre-rendered during build

### ISSUE THREAD

**Issue by Deepacks** [vercel/next.js#59905]
### Link to the code that reproduces this issue

https://github.com/Deepacks/next-issue-api-router

### To Reproduce

1. Clone the project
2. Install node modules
3. Run build with `npm run build`

### Current vs. Expected behavior

In the app folder there are:

1. a "Root route" ("/")
2. an API route ("/api")

The build is generating the "/" route, as expected.
Then it also tries to pre-render the "/api" route, which is unexpected.

**The api route contains code that should only run in a server environment, not during build time.** 

This causes the build to fail:
```
> Export encountered errors on following paths:
        /api/route: /api
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.12.1
Relevant Packages:
  next: 14.0.5-canary.25
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime)

### Additional context

I am deeply sorry if i misunderstand what is actually going on, but this is the result of several hours of trying.

The researches I have made on the internet yielded no results.
The researches I have made via chat bots only showed me that they were just as perplexed as me.
Nothing useful was found nowhere.

Thank you for your kind help.

**Comment by Fredkiss3** [comment]
Hello @Deepacks ,  This is an intended behavior of nextjs, by default api routes with only `GET` functions are statically generated : https://nextjs.org/docs/app/building-your-application/routing/route-handlers#behavior and you can opt-out of this : https://nextjs.org/docs/app/building-your-application/routing/route-handlers#opting-out-of-caching

**Comment by Deepacks** [comment]
Hello @Fredkiss3, thank you for pointing out the relevant documentation.

I managed to solve the issue, but it was something a bit different:
Even though i was opting-out of the caching, by using all of the four possible ways, i was still getting a failed connection to the Redis server.

This is because i am instantiating the Redis client in a separate file.
If i create a new connection in every function everything works as expected.

So, by importing a class that contains the Redis client, which is only used inside of the function, is enough to make the failed connection error appear.
I am sure that is because of something more fundamental that i don't quite get yet.

Thank you again for your help.
