### ISSUE TITLE
redirect inside try/catch block in server action throws NEXT_REDIRECT error

### ISSUE THREAD

**Issue by renanleonel** [vercel/next.js#59930]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/youthful-hopper-h96xf2?file=%2Flib%2Factions.ts%3A32%2C20

### To Reproduce

1. Start application with next dev
2. fill the form
3. next redirect error

### Current vs. Expected behavior

expected: redirect to /info
curr: error in redirecting

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
System:
    OS: Windows 11
  Binaries:
    Node: 21.1.0 
    pnpm: 8.12.0 
  npmPackages:
    next: ^14.0.4 => 14.0.4
    next-auth: 5.0.0-beta.4 => 5.0.0-beta.4
    react: 18.2.0 => 18.2.0
```

### Which area(s) are affected? (Select all that apply)

App Router

**Comment by DenisSkendaj** [comment]
Same Problem here

**Comment by zce** [comment]
Because APIs such as `redirect` and `notFound` interrupt program execution by throwing exceptions that Next.js can handle.

You may need to move them outside of the try catch.
