### ISSUE TITLE
Next14. app router with custom sever cannot setAssetPrefix

### ISSUE THREAD

**Issue by CreateSun** [vercel/next.js#59940]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/vercel-next-js-reproduction-template-go8s7s

### To Reproduce

1. create a custom app server from `next({ .... })` and express()
2. when app server has prepared, app.setAssetPrefix('https://google.com')

```
const app = next({ dev, hostname, port });
app.prepare().then(() => {
  const server = express();
  server.all("*", async (req, res) => {
    try {
      /** add prefix to assets */
      app.setAssetPrefix("https://www.google.com");
      await handle(req, res, parsedUrl);
    } catch (err) {
      res.statusCode = 500;
      res.end("internal server error");
    }
  });
  server.listen(port, () => {
    console.log(`> Ready on http://${hostname}:${port}`);
  });
});
```

<img width="1119" alt="image" src="https://github.com/vercel/next.js/assets/47080570/167f4956-2bf9-4990-b830-d141b48a0f11">

### Current vs. Expected behavior

**Current**: when i get 'http://localhost:3000', link scripts's src was like '/_next/static/xxxxxx.js' in the source code, 

**Expected** : it should be like 'https://google.com/_next/static/xxxxxx.js'

**Does Next 14 not support custom server setAssetPrefix in app router?**

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 18.16.0
  npm: 9.5.1
  Yarn: N/A
  pnpm: 7.32.3
Relevant Packages:
  next: 14.0.2
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

latest support version
app router: 13.4.2
pages router: 13.4.12

### Which area(s) are affected? (Select all that apply)

App Router
Page Router

**Comment by nicolaturcato** [comment]
Same happens to me starting from v13.5, it used to work perfectly fine until v13.4.7.
Not relevant if app or page router, it doesn't work for both.
Following up and looking forward to have a fix in order to run the upgrade.

**Comment by CreateSun** [comment]
Following up and I tried old version to verify this feature.
Finally , next@13.4.2 was the latest version support setAssetPrefix method in app router

**Comment by CreateSun** [comment]
flowing up

**Comment by shaunwarman** [comment]
# Overview
Seeing the same issues for anything after 13.2

Example repository setup. You can choose the branch as the nextjs version if you want to pull the repo down and test. I notice that next.config.js assetPrefix works, but setting it dynamically in code with a custom server is not working in later versions.

Repo link:

# Versions

## 13.2 (13.2.4)
https://github.com/shaunwarman/nextjs-setprefix-bug/tree/13.2

next.config.js assetPrefix - `https://cdn.staticprefix.com/abc/123/` - ✅ working
<img width="775" alt="Screenshot 2024-01-08 at 9 34 22 AM" src="https://github.com/vercel/next.js/assets/1986128/fb625fbc-4595-4583-a7b4-b8fa858a69c5">

dynamic app.setAssetPrefix - `https://cdn.dynamicprefix.com/abc/123/` - ✅  working

## 13.3 (13.3.4)
https://github.com/shaunwarman/nextjs-setprefix-bug/tree/13.3

next.config.js assetPrefix - `https://cdn.staticprefix.com/abc/123/` - 🛑 not working
dynamic app.setAssetPrefix - `https://cdn.dynamicprefix.com/abc/123/` - 🛑  not working

Error stack

```
TypeError: Cannot set properties of undefined (setting 'current')
    at prepareHostDispatcher (/Users/shaunwarman/Development/Source/paypal/my-app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:1896:37)
    at createRequest (/Users/shaunwarman/Development/Source/paypal/my-app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:8299:3)
    at /Users/shaunwarman/Development/Source/paypal/my-app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:10126:19
    at new Promise (<anonymous>)
    at Object.renderToReadableStream (/Users/shaunwarman/Development/Source/paypal/my-app/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.edge.development.js:10092:10)
    at /Users/shaunwarman/Development/Source/paypal/my-app/node_modules/next/dist/server/node-web-streams-helper.js:195:117
    at NextTracerImpl.trace (/Users/shaunwarman/Development/Source/paypal/my-app/node_modules/next/dist/server/lib/trace/tracer.js:86:20)
    at renderToInitialStream (/Users/shaunwarman/Development/Source/paypal/my-app/node_modules/next/dist/server/node-web-streams-helper.js:195:37)
    at /Users/shaunwarman/Development/Source/paypal/my-app/node_modules/next/dist/server/app-render/app-render.js:937:92
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  page: '/'
}
```

## 13.4 (13.4.19)
https://github.com/shaunwarman/nextjs-setprefix-bug/tree/13.4

next.config.js assetPrefix - `https://cdn.staticprefix.com/abc/123/` - ✅  working

<img width="775" alt="Screenshot 2024-01-08 at 9 54 00 AM" src="https://github.com/vercel/next.js/assets/1986128/19a58422-c9f9-40ac-beb5-df85f614a01d">

dynamic app.setAssetPrefix - `https://cdn.dynamicprefix.com/abc/123/` - 🛑  not working

<img width="775" alt="Screenshot 2024-01-08 at 9 55 04 AM" src="https://github.com/vercel/next.js/assets/1986128/622a8a52-3bc8-4199-96da-500b870b1d2b">

## 14 (14.0.4)
https://github.com/shaunwarman/nextjs-setprefix-bug/tree/14.0

next.config.js assetPrefix - `https://cdn.staticprefix.com/abc/123/` - ✅  working

<img width="775" alt="Screenshot 2024-01-08 at 9 58 03 AM" src="https://github.com/vercel/next.js/assets/1986128/ebd4c75b-089b-48a1-826b-7062da105ebb">


dynamic app.setAssetPrefix - `https://cdn.dynamicprefix.com/abc/123/` - 🛑  not working

<img width="775" alt="Screenshot 2024-01-08 at 9 58 47 AM" src="https://github.com/vercel/next.js/assets/1986128/adf175d1-e670-4e2c-8118-cadff9b925eb">

**Comment by adanperez** [comment]
We are running into the same issue.  When running a custom server, the build assets for app router pages are not using the asset prefix that is set at runtime with `app.setAssetPrefix("./custom");`. App router pages are only using the `prefix` setting that is set at build time in the app router page's `page_client-reference-manifest.js`.

```
globalThis.__RSC_MANIFEST=(globalThis.__RSC_MANIFEST||{});globalThis.__RSC_MANIFEST["/page"]={"moduleLoading":{"prefix":"/some-other/-url/_next/",
```

**Comment by shaunwarman** [comment]
We found that correctly setting the `assetPrefix` in `next.config.js` even at startup was a workaround.

**Comment by adanperez** [comment]
@shaunwarman are you doing the following?
- Make a production build with some string like`/production` for `assetPrefix` in `next.config.js`  
- Then when you run that prod build `yarn start`, use a different string for `assetPrefix` in `next.config.js`, something like `/THIS_IS_A_TEST` 

When I do this I see a mix of of asset prefixes being used of both `/production` and `/THIS_IS_A_TEST` 

![image](https://github.com/vercel/next.js/assets/444935/af1afa78-e8cc-4889-8a81-52cbf3c30be2)

This is the same behavior I see when using a custom server and using `app.setAssetPrefix` function.

I am using Next.js 14.0.4.

**Comment by CreateSun** [comment]
this is work but not enough. i need to add prefix dynamicly when a client request send to my app.



---Original---
From: "Shaun ***@***.***&gt;
Date: Fri, Jan 26, 2024 22:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vercel/next.js] Next14. app router with custom sever cannotsetAssetPrefix (Issue #59940)




 
We found that correctly setting the assetPrefix in next.config.js even at startup was a workaround.

**Comment by shaunwarman** [comment]
Actually @adanperez coming back to this it does seem like there are some links using the build time value of `assetPrefix` in `next.config.js` 🤔 - luckily we haven't released anything yet as we were hoping for the setAssetPrefix to get patched.

**Comment by AntiMoron** [comment]
app router, next@14.1.0 next.config.js `assetPrefix` not working...

See my configuration
![image](https://github.com/vercel/next.js/assets/6587734/2e131672-9398-4444-b077-fbe40c22b54a)
See my website, only on the index page this configuration worked. other pages not working:

![image](https://github.com/vercel/next.js/assets/6587734/c9e4359a-043f-43ba-84d9-f201ed4a7c1f)



https://www.chatbotsgpt.org/resource/blog

![image](https://github.com/vercel/next.js/assets/6587734/2f4f974a-0dad-4836-bda9-0663a4dc7602)

**Comment by shaunwarman** [comment]
After some discussion from nextjs core team, it sounds like there are some precompiled files at build time (turbopack) that aren't subject to runtime changes. This essentially means no support for `setAssetPrefix` going forward.

We'll look at leveraging the relative URLs and serving static assets from the application directly and/or add some smart rewrite rules in our CDN / edge configuration to map relative static asset URL to our central CDN URL.

**Comment by adanperez** [comment]
> After some discussion from nextjs core team, it sounds like there are some precompiled files at build time (turbopack) that aren't subject to runtime changes. This essentially means no support for `setAssetPrefix` going forward.

@shaunwarman do you have a link to the discussion?

**Comment by shaunwarman** [comment]
Wow! @ijjk does this fix cases for

> with partial prerendering the shell that is generated for all routes will include eager Link tags as those are known at build time

**Comment by ijjk** [comment]
Would be good to confirm once a new canary is up, if you are still seeing that specific issue please open a fresh issue and we can investigate it separately

**Comment by shaunwarman** [comment]
Using the same repo referenced above: https://github.com/shaunwarman/nextjs-setprefix-bug

Installing `next@14.1.1-canary.36` and I still see the mixed asset prefix (build time and setAssetPrefix) being used.

<img width="489" alt="Screenshot 2024-02-05 at 10 10 16 PM" src="https://github.com/vercel/next.js/assets/1986128/bd5db992-6082-4bc7-ba7b-98a6804cafdf">

build time: `cdn.staticprefix.com`
setAssetPrefix: `cdn.dynamicprefix.com`

**Comment by ijjk** [comment]
Hmm, why is the `assetPrefix` differing between build and runtime? Any routes that are statically optimized during build time would have differing `assetPrefix`'s

**Comment by shaunwarman** [comment]
well the setAssetPrefix should take over all is the expectation, but I think I heard that:

> Turbopack hardcodes the assetPrefix in app router, so it can’t change between build/start
> reason for that is that it’s pretty hard to reason about assetPrefix per-request because it won’t work with any static content, and when Partial Prerendering lands all routes would be at least partially static
> And with partial prerendering the shell that is generated for all routes will include eager Link tags as those are known at build time

**Comment by shaunwarman** [comment]
So our approach going forward looks like we'll keep relative paths to static assets across all environments. We'll keep our CDN sync mechanism to get assets to our CDN (origin) before a new version of the application is deployed. We'll then have to map a proxy or rewrite rule at CDN, edge, router based on hostname (knowing what is production) and send `<hostname>/_next/static/*` -> `<prod_cdn>/<some_static_namespace_to_map_to>/_next/static/*`.

**Comment by gaojude** [comment]
> well the setAssetPrefix should take over all is the expectation, but I think I heard that:
> 
> 
> 
> > Turbopack hardcodes the assetPrefix in app router, so it can’t change between build/start
> 
> > reason for that is that it’s pretty hard to reason about assetPrefix per-request because it won’t work with any static content, and when Partial Prerendering lands all routes would be at least partially static
> 
> > And with partial prerendering the shell that is generated for all routes will include eager Link tags as those are known at build time

The usage of setAssetPrefix is vague to me now given the explanation above. If it's no longer supported, we should just remove it.
