### ISSUE TITLE
Docs: The useSelectedLayoutSegment(s) in parallel routes does not match the actual running result

### ISSUE THREAD

**Issue by OldSmokeGun** [vercel/next.js#59968]
### What is the improvement or update you wish to see?

update useSelectedLayoutSegment(s) in parallel routes to correct actual running results

### Is there any context that might help us understand?

![image](https://github.com/vercel/next.js/assets/30717069/4d5ff22f-f91e-43b8-b944-9ace8c1e0120)

this is my directory structure

![image](https://github.com/vercel/next.js/assets/30717069/36f438b8-dc1d-4a56-aad0-b08e063b421d)

this is my code in example5/layout.js

![image](https://github.com/vercel/next.js/assets/30717069/42942b1a-f066-4c18-884b-132713da55b1)

this is the result of my program running

if follow the documentation step, the result that navigate to @header/bar should be bar, but the actual result is children

so, what's the problem?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#useselectedlayoutsegments

**Comment by chungweileong94** [comment]
Yeah, I was curious why it doesn't behave the same as the doc mentioned. It's either a bug or the doc is outdated. 

This is one of my code examples where I have to do weird check like `segment === "children"`

https://github.com/chungweileong94/nextjs-parallel-route-dialog/blob/main/src/app/_components/modal-slot.tsx
