### ISSUE TITLE
Problems with Revalidating Cached Data on Next.js 14.0.4

### ISSUE THREAD

**Issue by sellimenes** [vercel/next.js#59969]
### Link to the code that reproduces this issue

https://github.com/sellimenes/revalidate-bug

### To Reproduce

1. On local development, everything works as expected.
2. On Vercel deployment (or any other deployment), the cached data revalidation is not working as intended.
3. Vercel deployment link: https://revalidate-bug.vercel.app/change-settings

### Current vs. Expected behavior

Expected Behavior:
When the WebsiteName in the database is updated, triggering "revalidateTag" should revalidate the data on all pages without requiring a manual page refresh.

Current Behavior:
After triggering "revalidateTag," a manual page refresh is still required to load the updated data.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112
Binaries:
  Node: 20.5.1
  npm: 9.8.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

**Comment by salieflewis** [comment]
Currently experiencing something similar when using `revalidatePath`

**Comment by leerob** [comment]
This appears to work for me – are you seeing something different?

https://github.com/vercel/next.js/assets/9113740/31a1625f-1c41-4c7a-b314-97fc88ea8fe9

**Comment by sellimenes** [comment]
> This appears to work for me – are you seeing something different?
> 
>  CleanShot.2023-12-27.at.10.58.12.mp4

At the same page, all ok, but if you go to Main Page, for example, you won't see the new data.

https://github.com/vercel/next.js/assets/23125375/a66ed26f-13f8-4f54-8eec-e8861e20c9eb

**Comment by leerob** [comment]
Correct, this is currently the intended behavior. You can learn more about caching and see workarounds here: https://github.com/vercel/next.js/discussions/54075

Side note: in that thread, and in upcoming months, we're working on ways to simplify caching in Next.js.

**Comment by salieflewis** [comment]
@sellimenes please share if you uncover the nuance of this, cause to my understanding it seems like after running `revalidateTag` you shouldn't be seeing stale date on the index route.

**Comment by sellimenes** [comment]
> @sellimenes please share if you uncover the nuance of this, cause to my understanding it seems like after running `revalidateTag` you shouldn't be seeing stale date on the index route.

As I understand, it is currently working that way. I also think that you should not be seeing old data when you change pages. I guess we need to wait for further updates.

**Comment by TrustyTechSG** [comment]
Im also keep having this caching issue, there are multiple times only after we click the "Purge Everything" button from vercel console and then the fetch request start to return latest data after revalidateTag call. and then all things start to work normally. but some times later (days/weeks), everything start all over again.

**Comment by leerob** [comment]
Was linked back here with this question:

> I need the revalidateTag function to revalidate or refetch data in all routes. However, it seems that this feature is not available yet. Do you have any plans to implement it?

You can do `revalidatePath('/', 'layout')` for this!

https://nextjs.org/docs/app/api-reference/functions/revalidatePath#revalidating-all-data
