### ISSUE TITLE
Docs: Telemetry stability

### ISSUE THREAD

**Issue by devmanbr** [vercel/next.js#59963]
### What is the improvement or update you wish to see?

when will telemetry no longer be an experimental feature?

### Is there any context that might help us understand?

It's been a long time since the telemetry feature (using OpenTelemetry) was introduced into Next, and sometimes it seems like there are advances in every area, and this one, which is very important, seems to be falling by the wayside.

It is important that you prioritize this aspect to make it stable as soon as possible.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/optimizing/open-telemetry

**Comment by leerob** [comment]
Hey! We'll share more information in release notes as we make progress with OpenTelemetry support. If you have feedback or questions, please open a discussion here 😄
