### ISSUE TITLE
bug(cna): versions pinned at major breaks version resolution for pnpm

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#60008]
### Link to the code that reproduces this issue

https://github.com/juliusmarminge/nextjs-static-promise-context

### To Reproduce

#56177 pinned versions installed to the major, which works (installs latest) in every package manager except pnpm since that resolves to the lowest possible (annoying, yes....). See screenshot, it installs react 18.0.0 for example...

![CleanShot 2023-12-28 at 23 31 50](https://github.com/vercel/next.js/assets/51714798/08576da0-b7f1-4741-9d09-e4c2c6d72822)

```bash
> pnpm create next-app@canary

✔ Would you like to use TypeScript? … No / Yes
✔ Would you like to use ESLint? … No / Yes
✔ Would you like to use Tailwind CSS? … No / Yes
✔ Would you like to use `src/` directory? … No / Yes
✔ Would you like to use App Router? (recommended) … No / Yes
✔ Would you like to customize the default import alias (@/*)? … No / Yes
Creating a new Next.js app in /Users/julius/dev/static-repro.
```

### Current vs. Expected behavior

installs lowest matching version (e.g. react 18.0.0 instead of 18.2.0)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.6.2
Relevant Packages:
  next: 14.0.5-canary.29
  eslint-config-next: N/A
  react: 18.0.0
  react-dom: 18.0.0
  typescript: 5.0.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

**Comment by stefanprobst** [comment]
is this still the case with pnpm 8.7 and above (see https://github.com/pnpm/pnpm/pull/6987)?

**Comment by juliusmarminge** [comment]
Looks like behavior is reverted in a newer version. I use corepack and so I never really worry about what version I'm on though, the repos `packageManager` field decides that for me (which there isn't one when you're not in a project). Updated my global one and now it resolves to latest:

![CleanShot 2023-12-29 at 00 40 05](https://github.com/vercel/next.js/assets/51714798/5d22a7a8-88a4-452f-a924-60aea7809aab)

Still not sure if the current behavior of setting just a major is very resilient though...

**Comment by balazsorban44** [comment]
The recommendation here is to upgrade pnpm as pointed out in https://github.com/vercel/next.js/issues/60008#issuecomment-1871620723
