### ISSUE TITLE
`Uncaught Error: invariant expected app router to be mounted` when I am on the screen that is outside my main route which is a group routes without affecting routing 

### ISSUE THREAD

**Issue by WMLondo** [vercel/next.js#60027]
### Link to the code that reproduces this issue

https://github.com/WMLondo/template-app.git

### To Reproduce

1. Check the README file with all the needed to the project works.
2. Go to `/auth/login` and check the console of the navigator.

### Current vs. Expected behavior

By making a parallel path for my auth part of my application I did not expect to receive the error in the console which does not happen when I add the folder in the route path. 

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
Platform: Window 11
Version: 10.0.22631 Build 22631
Binaries:
Node : v21.4.0
npm: 10.2.5
Relevant Packages:
@prisma: "^5.7.1",
bcryptjs: "^2.4.3",
next: "14.0.4",
next-auth: "^5.0.0-beta.4",
react: "^18",
react-dom: "^18",
zustand: "^4.4.7"
ts-node: "^10.9.2",
typescript: "^5.3.3"
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tried moving the auth folder into my (shop) folder and the error disappears, I also saw issues related to this and it seems as if it was affected by useRouter, which I am not using in my project since I am using the new NextJS App Router, maybe if someone knows the reason why this error occurs and how to fix it without having to put it in the (shop) folder, the problem does not affect the application as a whole only disables the hot reloaded so to reflect a change I have to reload the page each time.

**Comment by oSethoum** [comment]
am having the same issue and frankly I have no idea where the problem is or which page.

**Comment by chavda-bhavik** [comment]
Found this solution from [Stackoverflow](https://stackoverflow.com/a/74601107/13206506),

Here is the exact section from [documentation](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required)

> The root layout must define <html> and <body> tags since Next.js does not automatically create them.

Adding <html> and <body> tag in https://github.com/WMLondo/template-app/blob/main/src/app/auth/layout.tsx might solve issue @WMLondo

**Comment by plsdev89** [comment]
Yeah, could solve the issue after including html, body tag to layout.tsx

**Comment by WMLondo** [comment]
A solution its the next:
https://github.com/vercel/next.js/issues/60027#issuecomment-1876866244
