### ISSUE TITLE
Docs: sir vercel is blocking my github user account

### ISSUE THREAD

**Issue by ataabdullah** [vercel/next.js#60022]
### What is the improvement or update you wish to see?

sir vercel is blocking my github user account

### Is there any context that might help us understand?

sir vercel is blocking my github user account

**Comment by ataabdullah** [comment]
plz check this issue

**Comment by samcx** [comment]
Hi there

Please reach out to registration@vercel.com to assist you on this!

I will be closing this issue as this is not related to a <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> issue.
