### ISSUE TITLE
Cannot use server-only with Vitest and API Route - App Router

### ISSUE THREAD

**Issue by Meags27** [vercel/next.js#60038]
### Link to the code that reproduces this issue

https://github.com/Meags27/next-vitest-test/tree/main

### To Reproduce

1. Download ZIP of code
2. npm install to install dependencies
3. npm run test and you will see the error "Error: This module cannot be imported from a Client Component module. It should only be used from a Server Component."

### Current vs. Expected behavior

I am trying to import a Next.js API route into a Vitest test file to test the API. 
However, I get the error mentioned above when using 'server-only' at the top of the file (which I want to be able to use). 

The error shows up with using jsdom or node as the environment.

However, with jest, the error does not show up when using node as the environment. But when using jsdom and Jest, it would say "ReferenceError: Response is not defined"

Apparently it was fixed in September, but I believe that was only for Jest and not Vitest https://github.com/vercel/next.js/pull/54891

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:        
  Platform: win32        
  Arch: x64              
  Version: Windows 10 Pro
Binaries:                
  Node: 18.17.1          
  npm: N/A               
  Yarn: N/A              
  pnpm: N/A              
Relevant Packages:       
  next: 14.0.5-canary.31 
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Additional context

I tested this with 14.0.4 and also tested the latest canary.

**Comment by waigel** [comment]
Hey @Meags27 ,

you can try to mock the "server-only" import in your vitests.
This should work: 

```tsx
vi.mock("server-only", () => {
  return {
    // mock server-only module
  };
});

```

**Comment by Meags27** [comment]
> Hey @Meags27 ,
> 
> you can try to mock the "server-only" import in your vitests. This should work:
> 
> ```tsx
> vi.mock("server-only", () => {
>   return {
>     // mock server-only module
>   };
> });
> ```

Thank you, that works!!
