### ISSUE TITLE
Docs: Data Cache Tag Based Revalidation has improper typescript export

### ISSUE THREAD

**Issue by KempfCreative** [vercel/next.js#60034]
### What is the improvement or update you wish to see?

In the [Tag Based Revalidation](https://vercel.com/docs/infrastructure/data-cache#tag-based-revalidation) code examples, the typescript example has an incorrect import from `next/server`:

`import { Request, NextResponse } from 'next/server';`

This results in a TS runtime error of: `Module '"next/server"' has no exported member 'Request'.ts(2305)`

The examples should be modified to say:
`import { NextRequest, NextResponse } from 'next/server';`

### Is there any context that might help us understand?

No added context.

### Does the docs page already exist? Please link to it.

https://vercel.com/docs/infrastructure/data-cache#tag-based-revalidation

**Comment by MadhuSaini22** [comment]
Can I work on this fix?

**Comment by leerob** [comment]
Thank you! I will fix this (in the Vercel documentation).
