### ISSUE TITLE
Turbopack is incompatible with `sharp`

### ISSUE THREAD

**Issue by n1ckoates** [vercel/next.js#60035]
### Link to the code that reproduces this issue

https://github.com/n1ckoates/sharp-turbopack-issue

### To Reproduce

1. Import `sharp` and execute it (`sharp()`).
2. Start the application in development mode with Turbopack enabled (`next dev --turbo`)
3. Observe error.

### Current vs. Expected behavior

I expected sharp to work properly, as it does when not using Turbopack.

Instead, an error is thrown:
```
Error: Could not load the "sharp" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
    npm install --force @img/sharp-linux-x64
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.13.1
Relevant Packages:
  next: 14.0.5-canary.30
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

<sub>[PACK-2183](https://linear.app/vercel/issue/PACK-2183/turbopack-is-incompatible-with-sharp)</sub>

**Comment by Cow258** [comment]
```js
// next.config.js
const nextConfig = {
  webpack: (cfg, options = {}) => {
    cfg.externals.push('sharp')
    const { webpack } = options
    const regex = /^sharp$/
    cfg.plugins.push(new webpack.IgnorePlugin({
      resourceRegExp: regex,
    }))
  }
}
```
here are some config for webpack,
sharp must add into external for using it,
i may need to find a way to config it to be external with Turbopack config

**Comment by n1ckoates** [comment]
I can confirm this issue is fixed - closing this.
