### ISSUE TITLE
I have the same problem. How can we set cookies other than in the middleware? Can someone show an example on how to set a cookie from a route handler as said possible in the docs? This became a life-or-death matter to me, I've been stuck for 2 days trying to figure out how I can manage to create a simple cookie...

### ISSUE THREAD

**Issue by kamaleldinmostafa** [vercel/next.js#60075]
I have the same problem. How can we set cookies other than in the middleware? Can someone show an example on how to set a cookie from a route handler as said possible in the docs? This became a life-or-death matter to me, I've been stuck for 2 days trying to figure out how I can manage to create a simple cookie...

_Originally posted by @kapsule-studio in https://github.com/vercel/next.js/issues/51875#issuecomment-1641438751_

**Comment by kmvan** [comment]
How about this: https://github.com/vercel/next.js/tree/canary/examples/with-cookies-next

**Comment by samcx** [comment]
Hi @kamaleldinmostafa, please [open a new issue](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) so the full template is used with the required information so we can properly triage this issue!
