### ISSUE TITLE
next/image failed to use the custom loader when using `next dev --turbo`

### ISSUE THREAD

**Issue by mhughdo** [vercel/next.js#60097]
### Link to the code that reproduces this issue

https://github.com/mhughdo/nextjs-bug-reproduction-app

### To Reproduce

 Run `pnpm dev`

### Current vs. Expected behavior

Current:
- Next is showing the `missing loader prop` error when using the custom loader
<img width="963" alt="image" src="https://github.com/vercel/next.js/assets/15611134/82c0da19-671f-4091-aad4-aee059fb1a40">
Expected behavior:
- The image could be loaded properly

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
 Arch: arm64
 Platform: darwin
 Version: Darwin Kernel Version 23.0.0
Binaries:
 node: v20.8.0
 pnpm: 8.13.1
Packages
 next: Next.js 14.0.5-canary.34 (turbo)
 react: 18.2.0
 react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image), Turbopack (--turbo)

<sub>[PACK-2190](https://linear.app/vercel/issue/PACK-2190/nextimage-failed-to-use-the-custom-loader-when-using-next-dev-turbo)</sub>

**Comment by Bahlaouane-Hamza** [comment]
I can confirm, i think this is related to https://github.com/vercel/next.js/commit/946c9c5c46091604b8a9c73260bfe26ece70de23

which introduce 
```js
// @ts-ignore - This is replaced by webpack alias
import defaultLoader from 'next/dist/shared/lib/image-loader'
```
Which is supposed to replaced by Webpack here
https://github.com/vercel/next.js/blob/canary/packages/next/src/build/create-compiler-aliases.ts#L114

I believe the equivalent webpack aliasing mecanic is here https://github.com/vercel/next.js/blob/canary/packages/next-swc/crates/next-core/src/next_import_map.rs, but this does not contain any ref to image-loader

I'm not sure we can add alias to https://swc.rs/docs/configuration/swcrc

@styfle any guidance on this please ?

**Comment by mhughdo** [comment]
@Bahlaouane-Hamza

Thank you for your solution. I can confirm that it fixed the problem for now.
