### ISSUE TITLE
[RFC] cleaning distDir on next build

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#6009]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently Next.js will keep the `distDir` (by default `.next`) when running `next build` because some deployment strategies involve running `next build` while the production application is running. However in most cases you actually want to start with a clean directory. For example when running `next export` after the build and Next.js having been in development mode before the build, this would cause HMR files to be written to the export out directory as outlined in #5554.

## Describe the solution you'd like

One solution is cleaning distDir by default and providing an option to opt-out of this behavior. I'd like to get some feedback on this though.

**Comment by Janpot** [comment]
Maybe only clean the HMR files?

**Comment by timneutkens** [comment]
It's not just HMR files. It's static files in `.next/static/development/pages`. It's the development runtime in `.next/static/webpack`. If you run `next build` multiple times you'd have multiple `.next/static/<buildid>/pages` folders etc.

**Comment by Janpot** [comment]
Do you know what's the rationale behind running `next build` on a project that is already started in production? Are they using `nodemon` or something to automatically restart their server when it updates? And if they are, then doesn't that mean they also suffer from old build files leaking on their file system? And if that's the case, I guess they (maybe unknowningly) suffer from the same problem, and need some sort of cleaning solution as well. (although it rather sounds like an antipattern to me)

**Comment by timneutkens** [comment]
Probably a good idea to cc @DullReferenceException @alexindigo @ztanner

**Comment by alexindigo** [comment]
@timneutkens Sounds like you're proposing to **auto** clean up distDir prior running `export` step? Or you just talking about `build` step?

**Comment by Janpot** [comment]
could it be an idea to clean at the end of the build? i.e.
1. store timestamp `startTime`
2. run build
3. remove all files that were last modified before `startTime`

**Comment by timneutkens** [comment]
Sounds like too much complexity imo. 
The point is that in certain builds you want to keep the old files. The main question I'm asking is if it would break the deployment process of users like Trulia, I doubt it will, just making sure.

**Comment by Janpot** [comment]
> Sounds like too much complexity imo.
Completely agree.

**Comment by alexindigo** [comment]
@timneutkens if it's just build then we're good :)

![rimraf](http://ia.gs/e90550014ec6/Image%202019-01-09%20at%2011.41.12%20AM.png)

**Comment by timneutkens** [comment]
Right exactly what I thought 💯

**Comment by ztanner** [comment]
+1, this makes total sense and would not break things for us.

**Comment by sergiodxa** [comment]
Why not release with opt-in flag (let's say `--clean-dist`) and an extra flag to opt-out (`--no-clean-dist`) not doing anything and then in the next release remove the opt-in and make clean distDir default making opt-out required?

That way if you need to keep it you have a major version to add the `--no-clean` and be prepared to update to next version. The build command could warn about the usage without `--no-clean-dist` in next version in order to let people know they need to either add it or add `--clean-dist` flag.

**Comment by timneutkens** [comment]
We're already going to have a major version with current changes.

**Comment by iamstarkov** [comment]
> `next build` would start with `rm -rf .next` basically. `export` needs the result of `next build`

it sounds good to me and that's exactly what I ended up doing for my blog

**Comment by satazor** [comment]
Just a reminder related to this feature:

If we are going to remove the `distDir` as a "pre" build step, we should disable the babel-loader cache so that it doesn't produce files that won't be used. The babel cache will therefore be only useful in dev.

**Comment by petvas** [comment]
I get this Warning message when we build for production:
Warning: No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache
The Docs says: https://github.com/zeit/next.js/blob/master/errors/no-cache.md
> Note: If this is a new project, or being built for the first time in your CI, you can ignore this error. However, you'll want to make sure it doesn't continue to happen and fix it if it does!

Based on the docs it says (mayeb I miss understand) but ./next/cache should exist when we build production build. Removing ./next folder would prevent that. But if we don't remove it the static folder gets bigger and bigger with every build, what is not good for production deployment.

**Comment by timneutkens** [comment]
@petvas `.next/cache` would be ignored in this RFC.

**Comment by ha-ku** [comment]
Are there any further progress about this RFC? I still find next keeping the old version of static files after `next build` is performed.

**Comment by AndrewRayCode** [comment]
I'm not sure if this is from the same issue, but when developing locally, then running
```
next build
next export
```

I get a never-ending list of:

```
6557f073caf41dee7851.hot-update.json                                                                 100%   43     0.8KB/s   00:00
1.7c098274f66f6c6c3991.hot-update.js                                                                 100% 9111    16.5KB/s   00:00
1.b3347dcff2efeb29cec9.hot-update.js                                                                 100%   28KB 109.6KB/s   00:00
1.ab3250b2c5eb9527f594.hot-update.js.map                                                             100% 8396    94.6KB/s   00:00
1.5263a20a0a6cd904f145.hot-update.js                                                                 100% 9002    18.1KB/s   00:00
1.bdae25d1623ba611a08d.hot-update.js                                                                 100% 6427    13.3KB/s   00:00
1.2aedeef3a474eed07ad8.hot-update.js                                                                 100%   10KB  38.5KB/s   00:00
45a164be94cbd52deeec.hot-update.json                                                                 100%   43     0.1KB/s   00:00
1.a7bb361a0404e13b5189.hot-update.js                                                                 100%   11KB  75.5KB/s   00:00
1.58069868f21c29300c39.hot-update.js.map                                                             100% 8571    70.4KB/s   00:00
deb3ac7eebca8574bf7d.hot-update.json                                                                 100%   43     0.4KB/s   00:00
```

Adding `rm -r out .next` in scripts in package.json for build fixes it, although I'm worried about what, if anything, I'm losing by nuking the `.next` folder

**Comment by MuhammedAO** [comment]
Hi i seem to be experiencing this same issue. my question is would there be a problem if just add the .next folder to my git ignore because it really messing up my files when i want to add files and make commits.. i get a whole bunch of webpack stuff screaming in my face.

**Comment by stovmascript** [comment]
@MuhammedAO Definitely do that. Build output files should not be in your repo. They get recreated anytime you build. Unless there's a specific reason to have such files checked into source control, this principle should apply to any project.

**Comment by dpyzo0o** [comment]
What's the status of this RFC?
