### ISSUE TITLE
Docs: Incremental Static Regeneration example link 404 in Pagerouter

### ISSUE THREAD

**Issue by CreateSun** [vercel/next.js#60155]
### What is the improvement or update you wish to see?

 I would like to see more examples of how to use Incremental Static Regeneration but [Next.js Commerce](https://nextjs.org/commerce) was 404

### Is there any context that might help us understand?

https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#error-handling-and-revalidation

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#error-handling-and-revalidation

**Comment by vordgi** [comment]
The same is in the project's Readme - https://github.com/vercel/commerce/tree/v1.

However, the demo is https://demo.vercel.store/

_I wanted to immediately change the link in the documentation to the demo, but I realized that previously there was a special page with different goodies, so let the vercel team answer exactly how it should be now_

**Comment by samcx** [comment]
Hi there,

[https://nextjs.org/commerce](https://nextjs.org/commerce) no longer `404`s!

Thanks for reporting!
