### ISSUE TITLE
Problem importing some packages in version 14.0.5-canary.36

### ISSUE THREAD

**Issue by mattiaz9** [vercel/next.js#60197]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/hungry-lumiere-g4wjml

### To Reproduce

1. Start the app in development

### Current vs. Expected behavior

Importing a package called `canvas-confetti` cause the error: `exports is not defined`.
The expected behaviour is to import the package without throwing an error.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.14.0
Relevant Packages:
  next: 14.0.5-canary.36
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested it with previous canary versions such as `14.0.5-canary.35` and it worked fine.
The problem started happening with the latest `14.0.5-canary.36`.

<sub>[NEXT-1975](https://linear.app/vercel/issue/NEXT-1975/problem-importing-some-packages-in-version-1405-canary36)</sub>

**Comment by joacub** [comment]
Still happening, try using react-pdf, material ui exporting to excel using a worker.
