### ISSUE TITLE
global-error.tsx doesn't work

### ISSUE THREAD

**Issue by Amerehei** [vercel/next.js#60245]
### Link to the code that reproduces this issue

https://github.com/milovangudelj/tests

### To Reproduce

It has been reported several times, I tried in Next.js 13 and 14. The `global-error.tsx` doesn't work

Similar issues: 
https://github.com/vercel/next.js/issues/55462
https://github.com/vercel/next.js/issues/50119
https://github.com/intuita-inc/cal.com-demo/pull/24

### Current vs. Expected behavior

By adding `global-error.tsx` we should be able to customize error page when root `layout.tsx` throws error

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 20.5.0
  npm: 9.8.1
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.39
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next start (local)

### Additional context

N/A

**Comment by LarsEjaas** [comment]
I experience the same thing. 
Adding: `throw new Error('test error')` in the root layout is not caught by the `app/global-error.tsx` file as explained here: https://nextjs.org/docs/app/building-your-application/routing/error-handling#handling-errors-in-root-layouts

I experience this on Next 14.0.4

**Comment by avetisk** [comment]
> It has been reported several times, I tried in Next.js 13 and 14. The `global-error.tsx` doesn't work

Indeed, this is a recurring issue.

Sometimes I feel like the team is focused on new features more than fixing issues :/

**Comment by ggomaeng** [comment]
Experiencing the same issue. How am I supposed to test it?

**Comment by Amerehei** [comment]
As a temporary workaround you can use `ErrorBoundary` in the root `layout.tsx`

```ts
export default function RootLayoutWithErrorBoundary({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ErrorBoundary FallbackComponent={GlobalError}>
      <RootLayout>{children}</RootLayout>
    </ErrorBoundary>
  )
}
```

**Comment by A7med3bdulBaset** [comment]
> As a temporary workaround you can use `ErrorBoundary` in the root `layout.tsx`
> 
> ```ts
> import { ErrorBoundary } from 'react-error-boundary'
> 
> export default function RootLayoutWithErrorBoundary({
>   children,
> }: {
>   children: React.ReactNode
> }) {
>   return (
>     <ErrorBoundary FallbackComponent={GlobalError}>
>       <RootLayout>{children}</RootLayout>
>     </ErrorBoundary>
>   )
> }
> ```

This is not a right solution.

Next.js throws some errors and catch them to handle some logic for example: `redirect()` is 
```js
function redirect() {
  throw new RedirectError()
}
```
there are some similar cases like opting out of static rendering to dynamic, etc...

When you make an Error Boundary, you need to re-throw them again

**Comment by Amerehei** [comment]
@A7med3bdulBaset I have no problem with `redirect()` and `notFound` they work well

**Comment by huozhi** [comment]
We had a fix for global-error in v14.0.5-canary.53, can you try to upragde to see if it resolves your issue? If it still breaks, lmk I'll take look, thanks! 🙏

**Comment by Amerehei** [comment]
Yes, It works on v14.0.5-canary.53

**Comment by huozhi** [comment]
Thanks for confriming, close as fixed
