### ISSUE TITLE
undefined LAZY_INITIALIZED when in canary release

### ISSUE THREAD

**Issue by dalist1** [vercel/next.js#60256]
### Link to the code that reproduces this issue

https://github.com/dalist1/reedee

### To Reproduce

1. Start the application in dev mode using `next dev`.
2. Loads for a while and errors out.

### Current vs. Expected behavior

When I run `next dev` on the canary release, it errors out with `LAZY_INITIALIZED`.
It however starts correctly when using `latest` instead of `canary`.
It started happening after `canary` .20 release. 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #18~22.04.1-Ubuntu SMP Tue Nov 21 19:25:02 UTC 2023
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.11.0
Relevant Packages:
  next: 14.0.5-canary.39
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

![image](https://github.com/vercel/next.js/assets/52313111/afc56709-48d6-427a-9dd7-9da18dfa19bb)

**Comment by guiccbr** [comment]
This is still happening when for a fresh next app: `npx create-next-app@latest` (14.1.0).
