### ISSUE TITLE
POSTGRES DB works in local machine but when i deployed it is not

### ISSUE THREAD

**Issue by najeebputhiyallam** [vercel/next.js#60313]
### Link to the code that reproduces this issue

https://github.com/najeebputhiyallam/myportfolio2024

### To Reproduce

Works fine in Local Machine or my PC. but once i deploy it is not working 
![Screenshot 2024-01-06 172123](https://github.com/vercel/next.js/assets/1217672/d79ba2e8-b9ef-4590-8c18-fc155faa37a2)

### Current vs. Expected behavior

It should insert Data to DB

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by waigel** [comment]
Are you able to verify that the environment variable `POSTGRES_URL` is set to vercel.com for your environment?
https://vercel.com/docs/storage/vercel-postgres/quickstart#review-what-was-created

**Comment by najeebputhiyallam** [comment]
i added the env.local varibales generated by vercel to my local .env file and added to gitignore. inside vercel those values are already prefilled i only connected to the project.
