### ISSUE TITLE
Emotion SWC Component Selectors error when styled options fed into the styled function

### ISSUE THREAD

**Issue by brendanmorrell** [vercel/next.js#60338]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/emotion-swc-component-selector-options-q9r6dy

### To Reproduce

1. start the app in dev
2. load the home/root page. the emotion component selectors error shows
3. got to pages.tsx. notice that the options object is defined in a variable. comment out the styled function that uses the options object defined in a variable and uncomment the component that in-lines an options object.
4. refresh the page
5. the error will go away

### Current vs. Expected behavior

The SWC transform should work whether the options object in the styled function call is in-lined or defined separately in a variable. Instead, it only works if in-lined.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.5-canary.41
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC minifier (swcMinify: true), SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Component selectors break when feeding in a variable as the second option to ```styled(``` as in ```styled('div', options)```. when I put an inline options object in as the second argument, everything works fine (as in ```styled('div', {})```), but if I define the options argument in a variable and then feed it in  (```const options ={}; styled('div', options)```), I get the error ```
Error: Component selectors can only be used in conjunction with @emotion/babel-plugin, the swc Emotion plugin, or another Emotion-aware compiler transform.```

this is in a completely fresh build with nothing but next and emotion, the swc compiler set to emotion, and the emotion-root-layout-registry set up exactly as it is in the next example repo/ @Andarist's example is in the emotion github repo.

here is a codesandbox

https://codesandbox.io/p/devbox/emotion-swc-component-selector-options-q9r6dy

    "@emotion/react": "^11.11.3",
    "@emotion/styled": "^11.11.0",
    "eslint": "8.54.0",
    "eslint-config-next": "^14.0.3",
    "next": "^14.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.3.2"

**Comment by kdy1** [comment]
I think the transform for component selectors is not implemented in the swc plugin.

https://github.com/swc-project/plugins/tree/main/packages/emotion/transform
