### ISSUE TITLE
create-next-app js templates don't use the .jsx extension

### ISSUE THREAD

**Issue by hichemfantar** [vercel/next.js#60391]
### Link to the code that reproduces this issue

https://github.com/hichemfantar/nextjs-js-example

### To Reproduce

1. run `npx create-next-app@latest`
2. choose any js example
3. files containing JSX have a `.js` extension

### Current vs. Expected behavior

JSX files have a `.js` extension
They should be have a `.jsx` extension like the ts examples have a `.tsx` extension

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.21
  pnpm: 8.13.1
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by leerob** [comment]
https://github.com/vercel/next.js/pull/60392#issuecomment-1902483600
