### ISSUE TITLE
Navigating from page to page (same dynamic segment) remounts

### ISSUE THREAD

**Issue by danvoyce** [vercel/next.js#60395]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/currying-dust-jf5mtr

### To Reproduce

1. Create a single dynamic page segment (App router), e.g `[id]/page.tsx`
2. Add Links that navigate to the same segment, but changes the `id` e.g `/${Number(id) + 1}` 
3. Notice that entire component is remounted

You can either inspect the DOM or simply check the console to notice it remounting each time you go from page to page.

This issue has been raised a few times already and seems to be going nowhere, so I'm trying again (🙏)

- https://github.com/vercel/next.js/issues/49553
- https://github.com/vercel/next.js/issues/48082
- https://github.com/vercel/next.js/issues/44793

An [RFC has also been created](https://github.com/vercel/next.js/discussions/50711) 6 months ago, but again is going nowhere 😔

### Current vs. Expected behavior

I've created some basic examples of the expected behaviour where the page does not remount: 

- NextJS (pages router): https://codesandbox.io/p/devbox/admiring-voice-8hsgnd
- Remix: https://codesandbox.io/p/devbox/adoring-minsky-t7kpvq

This is the user experience we've been used to since pretty much the dawn of React and is working as expected on the Pages router, so why has this now changed?

This is a huge shame, a poor UX and goes against the whole React ethos around keeping DOM updates to a minimum.

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
Binaries:
  Node: 20.5.0
  npm: 9.8.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.0
  eslint-config-next: 14.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

**Comment by lmatteis** [comment]
Hey @danvoyce ! What is happening behind the scenes (I believe) is that each time you route to `/[id]` the page for that component is downloaded - which in this case contains `id` amount of monkeys.

If you don't want to lose state then you shouldn't download it! That's at least the idea behind the behavior Next implemented here.

A better approach would be for a page to just return a single monkey (not N amount) and use server actions to load more. Check an example here: https://cursed-next-patterns.t3.gg/pagination

And link to the example https://github.com/t3dotgg/cursed-next-patterns/blob/main/src/app/pagination/helpers/server-data.tsx

Hope this helps!

**Comment by danvoyce** [comment]
Thanks @lmatteis, I think my example may not have portrayed the issue as well as it could. The `id` is needed so the page can be indexed / shared etc and keep the relevant state. The monkeys are simply there to show something has changed when the user navigates.

[This RFC](https://github.com/vercel/next.js/discussions/50711) does a much better job of explaining things!

I'll update the examples when I get a mo...

**Comment by danvoyce** [comment]
@rauchg do you have any input on this or can we consider this the way it is?

**Comment by tom-sherman** [comment]
Pages (and layouts) conceptually have a key of the current route, I believe this is in the docs somewhere that Next.js renders your page essentially like this: `<Page key={request.url} />`. This mirrors a native navigation and is required to prevent displaying stale data I believe.

Depending on why the remounts are a problem for you will affect what the solution is. For example if the problem is that browser state is being blown away, you can life that component up to the closest stable layout. In your repro that is the root layout, but you can add more nested ones if required with route groups.

**Comment by danvoyce** [comment]
Thanks for the comments @tom-sherman. My examples are very basic to avoid any confusion, but they might actually be too basic 😅

For my specific use case I want to fetch data based on the `id` in the url, so doing that in the layout isn't an option.

It feels like we've now optimised heavily for the initial page load, but at the same time completely ditched the nice SPA experience we're so used to.

I see that [this RFC](https://github.com/vercel/next.js/discussions/50711) has just come back to life, so it might be worth pulling our efforts together there to see if it can gain some attention from the powers above

**Comment by lmatteis** [comment]
@danvoyce do you have a more real-world use case?

**Comment by tom-sherman** [comment]
> For my specific use case I want to fetch data based on the id in the url

A server component fetch has anything to do with a client component remounting. You can usually lift the client state up out of the part that's remounting if you need to.

Can you be more specific about why unmounting is a problem in your components?

**Comment by danvoyce** [comment]
> @danvoyce do you have a more real-world use case?

Some real world examples 😅

App router version: https://codesandbox.io/p/devbox/awesome-zeh-2z8nn9

Pages router version: https://codesandbox.io/p/devbox/stoic-heisenberg-5xmvc2

Still somewhat simplified, but this is the basis of a current UI I am building, where I'm ultimately querying a database for an image, and then displaying it.

My ultimate wish is to have the initial page load done on the server, a la app router, but with subsequent navigations (to the same page but different slug) done on the client, a-la pages router.

I've not implemented it in the example, but it would be relatively trivial to create a nice transition in the pages router example, making the UX a lot nicer. AFAIK this is not be possible with the app router as the DOM tree for this is removed.

**Comment by lmatteis** [comment]
Yeah page transitions are a problem: it's one of their most upvoted issues https://github.com/vercel/next.js/issues/49279

Regarding the actual examples you provided, I still don't see what's the issue with the app router version? They look and feel the same to me, or am I missing something?

**Comment by danvoyce** [comment]
@lmatteis yeah still too simple 😅

Ultimately this issue is a convoluted way of saying exactly what you're saying, that page transitions don't work. Hadn't come across that issue you linked to so will check it out. Going to close this issue now as I think it's finally getting some attention, and it looks like it's being discussed in a few other places also! 

Thanks for all your input guys!
