### ISSUE TITLE
Docs: add an example of setting up a subdomain using the app directory.

### ISSUE THREAD

**Issue by kalvinyuu** [vercel/next.js#60406]
### What is the improvement or update you wish to see?

add some documentation about how to set up subdomains using the app directory.

### Is there any context that might help us understand?

an article or add it to docs there is nothing about it anywhere online and i thought there might be some information about it how to route it on the next.js documentation.

**Comment by leerob** [comment]
Here you go! https://vercel.com/guides/nextjs-multi-tenant-application
