### ISSUE TITLE
next/link bug not-found

### ISSUE THREAD

**Issue by mthmcalixto** [vercel/next.js#60408]
### Link to the code that reproduces this issue

https://github.com/mthmcalixto/redesign-tabnews.com.br

### To Reproduce

Enter a page that occurs 404 error.

which as: /93489384

Try pressing any link that contains "next/link"

### Current vs. Expected behavior

**Current:** The current behavior does not redirect to the page that is in the next/link, for example href="/", the url changes to the home page but nothing happens.

**Expected behavior:** Need to redirect the page to the page that is in href="/"

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
Binaries:
  Node: 20.5.1
  npm: 10.2.5
  Yarn: 1.22.21
  pnpm: 8.13.1
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by mthmcalixto** [comment]
fixed using: app/[...not_found]/page.tsx:

import { Metadata } from 'next'
import { notFound } from 'next/navigation'

```tsx
export const metadata: Metadata = {
  title: '404 - Not Found · TabNews - Unofficial Redesign',
}

export default function NotFoundCatchAll() {
  notFound()
}
```

**Comment by mthmcalixto** [comment]
fixed using: app/[...not_found]/page.tsx:

```tsx
import { Metadata } from 'next'
import { notFound } from 'next/navigation'

export const metadata: Metadata = {
  title: '404 - Not Found · TabNews - Unofficial Redesign',
}

export default function NotFoundCatchAll() {
  notFound()
}
```

**Comment by aibrahim3546** [comment]
@mthmcalixto how do you find the solution for this? I can't find it in the documentation.

**Comment by mthmcalixto** [comment]
> @mthmcalixto how do you find the solution for this? I can't find it in the documentation.

I found it in some answers, not sure why this occurs yet.
