### ISSUE TITLE
Naming a route "reklama" causes it to throw ChunkLoadError no matter what.

### ISSUE THREAD

**Issue by HristovCodes** [vercel/next.js#60417]
### Link to the code that reproduces this issue

[Link to sandbox](https://codesandbox.io/p/devbox/cranky-visvesvaraya-tgq8vc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr664es90008356hrs7d5ucu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr664es90002356hbkkatein%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr664es90006356hjex32w9j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr664es90007356hlvj4trhc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr664es90002356hbkkatein%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr664es80001356hwtt7txlx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr664es90002356hbkkatein%2522%252C%2522activeTabId%2522%253A%2522clr664es80001356hwtt7txlx%2522%257D%252C%2522clr664es90007356hlvj4trhc%2522%253A%257B%2522id%2522%253A%2522clr664es90007356hlvj4trhc%2522%252C%2522activeTabId%2522%253A%2522clr66ahn100ap356h5qhen2s8%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clr66ahn100ap356h5qhen2s8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr664es90006356hjex32w9j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr664es90003356hgpm22dut%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clr664es90004356hp26vpzn9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clr664es90005356hd4ae4jqx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clr664es90006356hjex32w9j%2522%252C%2522activeTabId%2522%253A%2522clr664es90003356hgpm22dut%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### To Reproduce

Renaming the route to anything for example "ad" or "reklami" fixes it.
This is important in our case, because  the work "reklama" means advertisement in our language.

I believe the error could also be webpack relate, but I'm posting here as well.

### Current vs. Expected behavior

1. Visit the sandbox.
2. Click on the "/reklama" route, app breaks.
3. Rebuild it and click on "/reklami", page loads fine with no errors.

Expected behavior: 
The route to work fine no matter the name, if there is a reserved name or something it should be mentioned in the documentation.

### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)
Binaries:
  Node: 20.10.0
  npm: 10.2.5
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

Locally I tried a lot of different things after reading different issues in this repository I found out that presumably the problem comes from a cache problem and that deleting the build folder and clearing browser cache fixes the problem. Well I tried that, along with completely rebuilding the project from scratch, deleting node_modules folder and installing fresh. Nothing seems to fix it other than renaming the route.

**Comment by gudvinga** [comment]
@HristovCodes Try disabling your adblock or other browser extension that blocks ads.
![image](https://github.com/vercel/next.js/assets/31861355/0ba57092-985c-4e89-89c7-615fb1aca48f)

**Comment by HristovCodes** [comment]
It is in fact because of an extension I had, I don't know how I didn't even think of that.
Thank you, next time before posting I'll think it through in the morning and not after a long day of work 😄 
Closing this thread, the solution was to disably my adblocker.
