### ISSUE TITLE
Next-intl loads wrong translation file

### ISSUE THREAD

**Issue by gadcam** [vercel/next.js#60416]
### Link to the code that reproduces this issue

https://github.com/gadcam/repro-turbo-next-intl

### To Reproduce

1. Go to `examples/example-app-router`
2. Start the app with `npx next dev --turbo`
3. Browse http://localhost:3000/
4. Try switching language to `German` and then to the Unknown language

### Current
It uses the German translation file.

### Expected
It uses the French translation file (reproducible if you remove the `--turbo` of the command).

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.8.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, Internationalization (i18n), Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The issue was first reported in next-intl repository https://github.com/amannn/next-intl/issues/718#issuecomment-1879783230
Here is a hack that seems to provide the expected behavior https://github.com/amannn/next-intl/issues/718#issuecomment-1879791303 it might help to understand what is going on.

<sub>[PACK-2224](https://linear.app/vercel/issue/PACK-2224/next-intl-loads-wrong-translation-file)</sub>

**Comment by ForsakenHarmony** [comment]
The issue is most likely trying to use dynamic expressions in `import()` here: https://github.com/gadcam/repro-turbo-next-intl/blob/bd72a3a3d7523dee1a06ecf60ad7ab8033ef00c4/examples/example-app-router/src/i18n.ts#L14

This is not supported yet, the tracking issue is #56531
