### ISSUE TITLE
Vercel no longer sees all the pushes

### ISSUE THREAD

**Issue by devbewill** [vercel/next.js#60434]
### Link to the code that reproduces this issue

https://github.com/devbewill/site2024/commit/48f81fda58c17510d5f1ae9a2ae86eafb1bd03af

### To Reproduce

1- push on the main branch (github)
2- a new commit is pushed correctly on github
3- Vercel don't trigger the new build as I haven't pushed nothing
4- if I try to push manually providing the commit link vercel deploy correctly.

### Current vs. Expected behavior

1- push on the main branch (github)
2- a new commit is pushed correctly on github
3- Vercel see the new push and trigger a new build deploy

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
Binaries:
  Node: 19.8.1
  npm: 9.5.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

Vercel no longer sees all the pushes I make on github and therefore does not trigger any deployments.
This happens on ALL the repos I hosted on vercel and not only one.

**Comment by devbewill** [comment]
I see now that I have a build error message as a reply to the commits from vercel bot saying:
`Resource is limited - try again in 19 hours (more than 100, code: "API-deployments-free-per-day").`
[commit link](https://github.com/devbewill/site2024/commit/b25ff2f1326c2361c484a9c9e8fc5dbfb2763a41)

but in the free plan, the deployment limit is 100\day today I've tried deployed 3 times only  :( I don't understand what happened and how I can fix

**Comment by samcx** [comment]
@devbewill This is not related to a <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> bug. I recommend reaching out to Vercel Support if the guide below does not help!

- https://vercel.com/guides/why-aren-t-commits-triggering-deployments-on-vercel

I will be closing this issue in the meantime.
