### ISSUE TITLE
Docs: Include note on redirect('/route') that it should be used in a finally block if using a try catch in server action

### ISSUE THREAD

**Issue by dwolrdcojp** [vercel/next.js#60448]
### What is the improvement or update you wish to see?

```typescript
export async function deleteItem(itemId: string) {
  try {
    const session = await auth();
    const userId = session?.user?.name;

    const resp = await prisma.item.delete({
      where: { id: itemId },
    });

    return {
      message: `Successfully updated ${resp.name}`,
    };
  } catch (e: unknown) {
    if (e instanceof Error) {
      console.error(e);
      return { message: `Server Error: Failed to delete ${e.message}` };
    } else {
      console.error(e);
      return { message: "Unkown Server Error: Failed to delete" };
    }
  } finally {
    redirect("/inventory");
    revalidatePath(`/inventory/${itemId}`);
    revalidatePath("/inventory");
  }
}
```

Currently if you try to redirect from within the try statement in a server action triggered from a client component it won't work. You must move it into a finally block or outside the try catch. 

The docs currently have an example without a try catch. In real projects almost all server actions are being executed with try catch for error handling. 

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/redirect#client-component

**Comment by kevinmitch14** [comment]
Looks like this is being worked on here in https://github.com/vercel/next.js/pull/60435

Also mentioned in https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#redirecting, but agree, it is easy to miss.

**Comment by dwolrdcojp** [comment]
Nice! Yeah that's exactly the example the api reference page for redirect needs. 

After the first time I read through all the base docs I haven't really gone back through them and I mostly just goto the reference pages now. 

Thanks

**Comment by delbaoliveira** [comment]
Thank you for raising this @dwolrdcojp, we added it to the docs linked above. But also, here's a PR adding the note to the `redirect` API reference: https://github.com/vercel/next.js/pull/61138
