### ISSUE TITLE
With all remotePatterns allowed for images, some image URLs are still rejected

### ISSUE THREAD

**Issue by WillCalderwood** [vercel/next.js#60483]
### Link to the code that reproduces this issue

https://github.com/WillCalderwood/next-bug

### To Reproduce

1. Start the application and you'll receive the error

```
Error: Invalid src prop [(https://bioage.typepad.com/.a/6a00d8341c4fbe53ef02c8d3a82122200d-600wi)](http://localhost:3000/admin/news/(https://bioage.typepad.com/.a/6a00d8341c4fbe53ef02c8d3a82122200d-600wi)) on `next/image`, hostname "bioage.typepad.com" is not configured under images in your `next.config.js`
See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host
```

### Current vs. Expected behavior

The image `https://bioage.typepad.com/.a/6a00d8341c4fbe53ef02c8d3a82122200d-600wi` is not allowed when all image remotes are set as valid with:
```
 images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**",
      },
      {
        protocol: "http",
        hostname: "**",
      },
    ],
  },
```

The image should not be throwing an error.

Note: It works correctly with `unoptimized={true}` specified.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.8.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.47
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by coltonehrman** [comment]
@WillCalderwood Seems to be a "qwerk" with the [micromatch](https://github.com/micromatch/micromatch) lib which is used to generate a RegEx based on globs. I messed around with this a bit and was able to produce a working pathname glob for this URL. This issue is the `.` inside the pathname.

```
module.exports = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
        pathname: '/.*/**',
      },
      {
        protocol: 'http',
        hostname: '**',
        pathname: '/.*/**',
      },
    ],
  },
}
```
