### ISSUE TITLE
Nested parallel routes slot rendered after navigating back

### ISSUE THREAD

**Issue by Inlustra** [vercel/next.js#60541]
### Link to the code that reproduces this issue

https://codesandbox.io/p/github/maxch-aa/next-intercepted-route/csb-9ps8vh/draft/weathered-tdd?file=%2Fsrc%2Fapp%2Fnesting%2Fpage.tsx%3A14%2C19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr9qp2rc00083b6jui8r4pww%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr9qp2rc00023b6j3yd5k3lj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr9qp2rc00053b6jkjcql32w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr9qp2rc00073b6jk5b3oadc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr9qp2rc00023b6j3yd5k3lj%2522%253A%257B%2522id%2522%253A%2522clr9qp2rc00023b6j3yd5k3lj%2522%252C%2522activeTabId%2522%253A%2522clr9rvrfq01my3b6jjg1i9nk4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9qp2rb00013b6jt3lq5htb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr9qvmm400023b6jcfyw44u4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fnesting%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252Fnext%252Fdist%252Fcompiled%252Fwebpack%252Fbundle5.js%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522endLineNumber%2522%253A1%252C%2522startColumn%2522%253A170035%252C%2522endColumn%2522%253A170035%257D%255D%252C%2522id%2522%253A%2522clr9rvrfq01my3b6jjg1i9nk4%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clr9qp2rc00073b6jk5b3oadc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9qp2rc00063b6j28b5sto8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fnesting%2522%257D%255D%252C%2522id%2522%253A%2522clr9qp2rc00073b6jk5b3oadc%2522%252C%2522activeTabId%2522%253A%2522clr9qp2rc00063b6j28b5sto8%2522%257D%252C%2522clr9qp2rc00053b6jkjcql32w%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9qp2rc00033b6j3qzupkb6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clr9qp2rc00043b6jxlc8q8xz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr9epqzv004oedishqjx73ia%2522%257D%255D%252C%2522id%2522%253A%2522clr9qp2rc00053b6jkjcql32w%2522%252C%2522activeTabId%2522%253A%2522clr9qp2rc00033b6j3qzupkb6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### To Reproduce

1. Navigate to /nesting
2. Click a photo (To navigate to /nesting/photos/1)
3. Click back (To navigate back to /nesting)

Tested up to Canary 52

### Current vs. Expected behavior

The parallel route slot (@modal) is still rendered after navigating back.

I would expect the parallel route slot to clear the layout slot and render either the default or the Catch All

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.5-canary.52
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

Tested on both canary and stable

**Comment by Inlustra** [comment]
Upgrading to [v14.0.5-canary.65](https://github.com/vercel/next.js/releases/tag/v14.0.5-canary.65) still causes the same issue.

**Comment by Inlustra** [comment]
Upgrading to v14.1.0 still causes the same issue.

**Comment by roker16** [comment]
Very disappointing ... waiting is too long... critical issues are not being given priority. my all nested routes inside parallel routes are broken on refresh / back. Information sill persist till 14.1.3

**Comment by graup** [comment]
Also have this problem. Related issues: #58796 #61206 #52720

Tagging @ztanner and @feedthejim who have been trying to get parallel routes working for a while.

**Comment by Inlustra** [comment]
I think it's important to be clear what the issue is here.
In this particular nested routing case, if you navigate back, the `default.tsx` is *not* rendered, the nested parallel route is still rendered. 

On refresh, from my testing, everything works correctly.

Example: 
/nesting/photos/1 -> nesting/photos/[id].tsx is rendered
*navigate back*
/nesting/photos -> nesting /photos/[id].tsx is still rendered 

Refreshing  at `/nesting/photos` fixes the issue, resulting in the default.tsx being rendered

**Comment by ztanner** [comment]
Closing this as I haven't heard back and cannot reproduce the original issue. But please don't hesitate to follow-up in case there's something I missed. Thank you!
