### ISSUE TITLE
building when parallel route use, if you use generaterMetadata use together, occurs error.

### ISSUE THREAD

**Issue by SeungYn** [vercel/next.js#60572]
`###` Link to the code that reproduces this issue

https://github.com/SeungYn/nextjs-bug-parallel

### To Reproduce

building when parallel route use, if you use generaterMetadata use together, occurs error.

### Current vs. Expected behavior

Type error: Layout "src/app/wrapperr/[id]/layout.tsx" does not match the required types of a Next.js Layout.
  "generateMatadata" is not a valid Layout export field.  but if remove generateMetadata , error not ocurs 
  
  ``` import { ReactNode } from 'react';

export function generateMatadata({
  params: { id },
}: {
  params: { id: number };
}) {
  return { title: 'test' };
}

export default function Layout({
  children,
  route1,
  params: { id },
}: {
  children: React.ReactNode;
  route1: ReactNode;
  params: { id: number };
}) {
  return (
    <div>
      {/* {children}
      {route1} */}
    </div>
  );
}
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:46 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T8101
Binaries:
  Node: 20.4.0
  npm: 9.7.2
  Yarn: 1.22.11
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by Jon1VK** [comment]
You have a typo in your code. You have `generateMatadata`, should be `generateMetadata`

**Comment by ztanner** [comment]
Indeed -- fixing that typo should fix the build error that says there's an invalid export.
