### ISSUE TITLE
Docs: next/font/google missing fonts

### ISSUE THREAD

**Issue by konstantin-lukas** [vercel/next.js#60605]
### What is the improvement or update you wish to see?

I'm not sure if this is a documentation issue or a bug but when I'm trying to use next/font/google it is missing the font "Afacad". I couldn't find anything in the documentation about this. So, I'm not sure if next/font/google only supports a subset of fonts available on Google fonts, or "Afacad" was left out unintentionally. 

### Is there any context that might help us understand?

Here's an example of two existing fonts and the missing "Afacad"
`import {Josefin_Sans, Playfair_Display, Afacad} from 'next/font/google';

export const josefin = Josefin_Sans({
    subsets: ['latin'],
    display: 'swap',
})

export const playfair = Playfair_Display({
    subsets: ['latin'],
    display: 'swap',
})

export const afacad = Afacad({
    subsets: ['latin'],
    display: 'swap',
})`
I'm on next version 14.0.4 and here's the link to the font on Google fonts: https://fonts.google.com/specimen/Afacad

**Comment by leerob** [comment]
Hey there! Yes, its possible there are some fonts missing inside of Next.js from the Google Fonts registry. If you click into the source of `next/font/google`, or use your editor autocomplete, you can see the available options. Sorry about the confusion here.
