### ISSUE TITLE
Worker not compiling correctly, window is undefined in files after canary 14.0.5-canary.19

### ISSUE THREAD

**Issue by joacub** [vercel/next.js#60644]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/trusting-glade-g3l38y?file=%2Fapp%2Fpage.tsx%3A7%2C1

### To Reproduce

pnpm install
pnpm dev

show the console and see the window is undefined

### Current vs. Expected behavior

window var is undefined and should be defined as this is in the browser context

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
after any canary 14.0.5-canary.19
```

### Which area(s) are affected? (Select all that apply)

App Router, SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

canary 14.0.5-canary.19 works perfectly

**Comment by joacub** [comment]
some one checking on this ?

**Comment by joacub** [comment]
plesaee some one can take care of this, this is a blocker. nextjs cant be used any more if you are using workers.

**Comment by joacub** [comment]
related:
https://github.com/vercel/next.js/issues/59603

**Comment by joacub** [comment]
@yf-yang

**Comment by kdy1** [comment]
Problematic release: https://github.com/vercel/next.js/releases/tag/v14.0.5-canary.20

**Comment by arclogos132** [comment]
Doesn't seem to work on 14.1.0

**Comment by arclogos132** [comment]
Doesn't seem to work on 14.1.1-canary.42 as well

**Comment by yf-yang** [comment]
Isn't it a correct behavior?
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#web_workers_api
If I got it right, in web worker, only `self` is available.

**Comment by joacub** [comment]
> Isn't it a correct behavior? https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#web_workers_api If I got it right, in web worker, only `self` is available.
> 
> > workers run in another global context that is different from the current [window](https://developer.mozilla.org/en-US/docs/Web/API/Window). Thus, using the [window](https://developer.mozilla.org/en-US/docs/Web/API/Window) shortcut to get the current global scope (instead of [self](https://developer.mozilla.org/en-US/docs/Web/API/Window/self)) within a [Worker](https://developer.mozilla.org/en-US/docs/Web/API/Worker) will return an error.

not it is not, this was working before perfeclty

**Comment by Hdanzo** [comment]
Works on 14.1.1-canary.52
