### ISSUE TITLE
Layout template Metadata isn't picked up by the direct home page

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#60666]
### Link to the code that reproduces this issue

https://github.com/Fredkiss3/metadata-home-page-bug

### To Reproduce

1. Start the app with `next dev`
2. Open the app and you will see the title will show only `Home`
3. You can click to go to `/child` and now the title will show `Child - metadata bug`
4. If you move the page to a group (for ex: `/app/(home)/page.tsx`, Now the title will say `Home - metadata bug`

### Current vs. Expected behavior

the title template for the metadata isn't picked up by the direct children of the root layout, `(home)` is expected to show `Home - metadata bug` but it only take the title from the page directly ignoring completely the template at the layout.

This doesn't happens for child routes or pages defined in route groups. 

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 8.7.1
Relevant Packages:
  next: 14.0.5-canary.58
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

**Comment by A7med3bdulBaset** [comment]
The first case (page.tsx in the same level as layout.tsx) is expected and documented:
https://nextjs.org/docs/app/api-reference/functions/generate-metadata#template

> ## Good to know:
> `title.template` applies to child route segments and not the segment it's defined in. This means:
>  - `title.default` is required when you add a `title.template`.
>  - `title.template` defined in `layout.js` will not apply to a title defined in a `page.js` of the same route segment.

**Comment by Fredkiss3** [comment]
That's a little annoying but it's not a big deal, so I am going to close this one.
