### ISSUE TITLE
Error digest from Server Action is not logged server-side

### ISSUE THREAD

**Issue by Winwardo** [vercel/next.js#60684]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/competent-firefly-9ncwrh?file=%2Fapp%2Fpage.tsx%3A18%2C7

### To Reproduce

1. Make a client side button which calls a server action.
2. Server action throws an error.
3. Client catches an error which has a digest.

### Current vs. Expected behavior

Client side receives a digest, but this is not logged anywhere (that I can find) on the server.
This means that you can't search the logs for this digest to find out what caused it.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed), Other (Deployed)

### Additional context

When a server action throws an error, in production this is hashed into a digest that is sent to the client. This is a security mechanism that lets developers track errors, without potentially leaking sensitive information like stack-traces to end-users.
This digest is only accessible in the browser.

It would be incredibly helpful if this digest was logged on the server as well. This means the browser could track the error (to say Sentry), and then this can be tied to a server-tracked error too.

Note the documentation explicitly states:
> The message property contains a generic message about the error and the digest property contains an automatically generated hash of the error that can be used to match the corresponding error in server-side logs.
https://nextjs.org/docs/app/building-your-application/routing/error-handling#handling-server-errors

However, as the digest *is not logged on the server*, it is not possible to match the corresponding error.

Based on a quick look through the code, I've found this function `createErrorHandler` might be a reasonable place to incorporate this change.
https://github.com/vercel/next.js/blob/ab7b0f59fb0d793fb4ee593ae93f7e08bab23b5b/packages/next/src/server/app-render/create-error-handler.tsx#L91

I have put together a minimal change that I believe could help here:
https://github.com/Winwardo/next.js/pull/1/files

There is a related issue on React GitHub, where other people would like to pass error codes from the server to client: https://github.com/facebook/react/issues/27362 "[Feature Request]: RSC error - allow error.code or an other specialized prop to be forwarded to the client #27362"

Thanks 👍

**Comment by OtisTemler** [comment]
Can confirm, same issue here no error digest in the log's. If the server-action explodes and we catch the error via error.tsx we receive an error digest but it's simply not logged out.
