### ISSUE TITLE
before unload event - how to change default message "Changes you made may not be saved"?

### ISSUE THREAD

**Issue by nicitaacom** [vercel/next.js#60696]
### Link to the code that reproduces this issue

https://github.com/nicitaacom/acc2-beforeunload-custom-message/blob/development/app/page.tsx

### To Reproduce

1. `git clone https://github.com/nicitaacom/acc2-beforeunload-custom-message/blob/development/`
2. `pnpm i`
3. `pnpm dev`
4. Enter more then 3 characters in input
5. Press `ctrl+R` (or reload page)
6. See error 

### Current vs. Expected behavior

I expect custom message
I got default message

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09)
Binaries:
  Node: 20.0.0
  npm: 9.6.4
  Yarn: 1.22.21
  pnpm: 8.13.1
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

I tried to fix this issue myself but without result
I didn't found solution that work for my case
`window.confirm` doesn't work as well

**Comment by islamBelabbes** [comment]
After some research, it turns out that it's not possible to display custom messages. for security reasons.
you can read more :
https://stackoverflow.com/questions/38879742/is-it-possible-to-display-a-custom-message-in-the-beforeunload-popup

**Comment by nicitaacom** [comment]
> After some research, it turns out that it's not possible to display custom messages. for security reasons ( in modern browsers at least ). you can read more : https://stackoverflow.com/questions/38879742/is-it-possible-to-display-a-custom-message-in-the-beforeunload-popup

Ok thank you
