### ISSUE TITLE
Docs: configure Server Actions body size limit is undefined

### ISSUE THREAD

**Issue by amplicity** [vercel/next.js#60755]
### What is the improvement or update you wish to see?

```
Unhandled Runtime Error
Error: Body exceeded undefined limit.
To configure the body size limit for Server Actions, see: https://nextjs.org/docs/app/api-reference/server-actions#size-limitation
```

This link leads to a 404. Very frustrating.

https://nextjs.org/docs/app/api-reference/server-actions#size-limitation

### Is there any context that might help us understand?

This link has been a 404 for some time now, and it's very frustrating because server actions are now out of experimental mode. This page needs to be fixed/corrected.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/server-actions#size-limitation

**Comment by delbaoliveira** [comment]
Thank you for reporting the broken link @amplicity 🙏🏼  Fixed here: https://github.com/vercel/next.js/pull/60960
