### ISSUE TITLE
Docs: Fix typo

### ISSUE THREAD

**Issue by pedrohmelo** [vercel/next.js#60786]
### What is the improvement or update you wish to see?

On the oficial tutorial for Next.JS, i found a mispelled word ("displayed"). At the paragraph below:

"You can use the clsx library introduced in the chapter on [CSS styling](https://nextjs.org/learn/dashboard-app/css-styling) to conditionally apply class names when the link is active. When link.href matches the pathname, the link should **displayed** with blue text and a light blue background."

I guess the correct phrase should be "should be displayed" or "should display". Also, you guys did a awesome work in this tutorial, i'm learning a lot from it, thanks for your great work! :)

### Is there any context that might help us understand?

Description above is enough.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/navigating-between-pages#pattern-showing-active-links

**Comment by leerob** [comment]
Thank you! Will fix.
