### ISSUE TITLE
All client pages rendering twice

### ISSUE THREAD

**Issue by Badestrand** [vercel/next.js#60784]
### Link to the code that reproduces this issue

https://github.com/Badestrand/nextjs-bug-renders-twice

### To Reproduce

Super basic barebones app:
<img width="218" alt="Screenshot 2024-01-17 at 17 15 58" src="https://github.com/vercel/next.js/assets/1368810/60717e62-cb39-4772-af6b-674fd60850db">

```jsx
// layout.jsx
"use client"

import {useEffect} from 'react'

export default function RootLayout({children}) {
	useEffect(() => {
		console.log('RootLayout mounted', new Date().getTime())
	}, [])
	return (
		<html>
			<head></head>
			<body>{children}</body>
		</html>
	)
}
```

```jsx
// page.jsx
"use client"

export default function Page() {
	console.log('Page', new Date().getTime())
	return <div>Page...</div>
}
```

### Current vs. Expected behavior

Expected behaviour is that when I go to http://localhost:3000/page that RootLayout as well as Page is rendered once each.

Current behaviour is that both components are rendered twice at the same time:
```
// console output
RootLayout mounted 1705508291367
RootLayout mounted 1705508291367
Page 1705508291427
Page 1705508291427
```

This is problematic because all API calls are executed twice.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.6.0
  pnpm: N/A
Relevant Packages:
  next: 14.0.5-canary.63
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by Badestrand** [comment]
I think this is related to issue https://github.com/vercel/next.js/issues/49115 which was closed only due to inactivity.

**Comment by leoBergerot** [comment]
The problem you're facing is likely linked to two specific issues : [#58736](https://github.com/vercel/next.js/issues/58736) and [#60562](https://github.com/vercel/next.js/issues/60562).

**Comment by OlegLustenko** [comment]
Have you tried to remove React Strict Mode?

https://react.dev/reference/react/StrictMode

![Screenshot_20240117-213003.png](https://github.com/vercel/next.js/assets/11524061/27a37d23-9d66-48c0-944f-dc82e3a39f6d)

**Comment by Badestrand** [comment]
> Have you tried to remove React Strict Mode?
> 
> https://react.dev/reference/react/StrictMode

You are right, this seems to be the culprit! It seems it is on by default since 13.4 and I didn't get the memo about that, didn't even ever hear about strict mode until now.

I found out how to disable it: https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode

IMO this behaviour should be at least mentioned in the Next.js docs somewhere, that all your components get rendered twice.

**Comment by leoBergerot** [comment]
So, the issue is not the same regarding double rendering and double fetching in this example in production when React strict mode is disabled. Does anyone have an explanation for this? https://codesandbox.io/p/devbox/sleepy-http-78m2hw?file=%2Fnext.config.js%3A2%2C19 
<img width="1403" alt="Capture d’écran 2024-01-17 à 22 03 15" src="https://github.com/vercel/next.js/assets/24389962/f6978a44-3cf0-4c80-b30d-d0ae575c8640">
