### ISSUE TITLE
 NextJS 14 layout re-render when changing route

### ISSUE THREAD

**Issue by smitkhanparaZuru** [vercel/next.js#60861]
@timneutkens 
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/happy-stallman-tlztle?file=%2Fapp%2Ftest%2F%5Bid%5D%2Fpage.tsx

### To Reproduce

first create build and after start to build, visit the /test route, click the button few times to increase the count, click the "go to id 1/2" button to go to leaf segment, and the count will reset

### Current vs. Expected behavior

the layout should not re-render

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 12.0.9
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.8.4
Next.js Config:
  output: N/A


warn  - Latest canary version not detected, detected: "14.1.0", newest: "14.1.1-canary.1".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local)

**Comment by smitkhanparaZuru** [comment]
@timneutkens 

Additionally, try one other thing.
Include some server action in the Root layout file. after create build and start build.

For example : 

```
  const cookieStore = cookies().getAll();

  console.log(cookieStore);
```
  
See the magic The layout is not rendered.

I was unaware of the reason behind this occurrence.

**Comment by cbratschi** [comment]
The leaf elements use a dynamic route. This could be related to:

https://github.com/vercel/next.js/discussions/50711

**Comment by timneutkens** [comment]
https://codesandbox.io/p/devbox/jolly-rumple-r384gg?file=%2Fapp%2Flayout.tsx%3A10%2C30

https://r384gg-3000.csb.app/test

Seems to be working fine? Please don't ping maintainers randomly.
