### ISSUE TITLE
Plyr-react library with Next.js 14

### ISSUE THREAD

**Issue by timomedia** [vercel/next.js#60862]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/hidden-frost-mpdjj?file=%2Fsrc%2FHLS.tsx

### To Reproduce

I am using plyr-react in a Next.js 14.1.0 environment and pages using plyr-react (5.3.0) fail to load or build with errors of type

### Current vs. Expected behavior

```
⨯ node_modules\plyr\dist\plyr.min.mjs (1:7201) @ document
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
    at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
    at eval (./components/player.tsx:11:68)
    at (ssr)/./components/player.tsx (\.next\server\app\[movie]\page.js:249:1)
    at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
    at eval (./app/[movie]/movieDetail.tsx:7:76)
    at (ssr)/./app/[movie]/movieDetail.tsx (\.next\server\app\[movie]\page.js:194:1)
    at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
null
```

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

I didn't have this problem when I worked on my site with next.js 14.0.0, but now I upgraded everything I have it all the time, this blocks the build.

**Comment by AntonyJudeShaman** [comment]
By default, Next.js executes code on the server side where the DOM is not defined. To address this, you can use the useEffect hook. This hook allows you to perform actions on the client side, ensuring that the DOM is available.

**Comment by brkcrdk** [comment]
You got to import plyr dynamically.

**Comment by johnsi15** [comment]
> ### Link to the code that reproduces this issue
> https://codesandbox.io/p/sandbox/hidden-frost-mpdjj?file=%2Fsrc%2FHLS.tsx
> 
> ### To Reproduce
> I am using plyr-react in a Next.js 14.1.0 environment and pages using plyr-react (5.3.0) fail to load or build with errors of type
> 
> ### Current vs. Expected behavior
> ```
> ⨯ node_modules\plyr\dist\plyr.min.mjs (1:7201) @ document
>  ⨯ ReferenceError: document is not defined
>     at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
>     at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
>     at eval (./components/player.tsx:11:68)
>     at (ssr)/./components/player.tsx (\.next\server\app\[movie]\page.js:249:1)
>     at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
>     at eval (./app/[movie]/movieDetail.tsx:7:76)
>     at (ssr)/./app/[movie]/movieDetail.tsx (\.next\server\app\[movie]\page.js:194:1)
>     at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
> null
> ```
> 
> ### Verify canary release
> * [x]  I verified that the issue exists in the latest Next.js canary release
> 
> ### Provide environment information
> ```shell
> Operating System:
>   Platform: win32
>   Arch: x64
>   Version: Windows 10 Pro
>   Node: 20.10.0
>   npm: N/A
>   Yarn: N/A
>   pnpm: N/A
> Relevant Packages:
>   next: 14.1.0
>   eslint-config-next: 14.1.0
>   react: 18.2.0
>   react-dom: 18.2.0
>   typescript: 5.2.2
> Next.js Config:
>   output: N/A
> ```
> 
> ### Which area(s) are affected? (Select all that apply)
> App Router
> 
> ### Which stage(s) are affected? (Select all that apply)
> next dev (local), next build (local)
> 
> ### Additional context
> I didn't have this problem when I worked on my site with next.js 14.0.0, but now I upgraded everything I have it all the time, this blocks the build.

Hi @timomedia I used Dynamic Imports as @brkcrdk mentioned, I'll leave you an example:

```ts
export function Video() {
  const [importedComponent, setImportedComponent] = useState<ReactElement | null>(null)

  useEffect(() => {
    const importComponent = async () => {
      const myModule = await import('plyr-react')
      const Plyr = myModule.default
      setImportedComponent(<Plyr {...plyrProps} />)
    }

    importComponent()
  }, [])

  return (
    <section className='aspect-video mx-16 mt-20 mb-28'>
      {importedComponent}
    </section>
  )
}
```

**Comment by timomedia** [comment]
> > ### Link to the code that reproduces this issue
> > https://codesandbox.io/p/sandbox/hidden-frost-mpdjj?file=%2Fsrc%2FHLS.tsx
> > ### To Reproduce
> > I am using plyr-react in a Next.js 14.1.0 environment and pages using plyr-react (5.3.0) fail to load or build with errors of type
> > ### Current vs. Expected behavior
> > ```
> > ⨯ node_modules\plyr\dist\plyr.min.mjs (1:7201) @ document
> >  ⨯ ReferenceError: document is not defined
> >     at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
> >     at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
> >     at eval (./components/player.tsx:11:68)
> >     at (ssr)/./components/player.tsx (\.next\server\app\[movie]\page.js:249:1)
> >     at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
> >     at eval (./app/[movie]/movieDetail.tsx:7:76)
> >     at (ssr)/./app/[movie]/movieDetail.tsx (\.next\server\app\[movie]\page.js:194:1)
> >     at __webpack_require__ (\.next\server\webpack-runtime.js:33:42)
> > null
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Verify canary release
> > 
> > * [x]   I verified that the issue exists in the latest Next.js canary release
> > 
> > ### Provide environment information
> > ```shell
> > Operating System:
> >   Platform: win32
> >   Arch: x64
> >   Version: Windows 10 Pro
> >   Node: 20.10.0
> >   npm: N/A
> >   Yarn: N/A
> >   pnpm: N/A
> > Relevant Packages:
> >   next: 14.1.0
> >   eslint-config-next: 14.1.0
> >   react: 18.2.0
> >   react-dom: 18.2.0
> >   typescript: 5.2.2
> > Next.js Config:
> >   output: N/A
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Which area(s) are affected? (Select all that apply)
> > App Router
> > ### Which stage(s) are affected? (Select all that apply)
> > next dev (local), next build (local)
> > ### Additional context
> > I didn't have this problem when I worked on my site with next.js 14.0.0, but now I upgraded everything I have it all the time, this blocks the build.
> 
> Hi @timomedia I used Dynamic Imports as @brkcrdk mentioned, I'll leave you an example:
> 
> ```ts
> export function Video() {
>   const [importedComponent, setImportedComponent] = useState<ReactElement | null>(null)
> 
>   useEffect(() => {
>     const importComponent = async () => {
>       const myModule = await import('plyr-react')
>       const Plyr = myModule.default
>       setImportedComponent(<Plyr {...plyrProps} />)
>     }
> 
>     importComponent()
>   }, [])
> 
>   return (
>     <section className='aspect-video mx-16 mt-20 mb-28'>
>       {importedComponent}
>     </section>
>   )
> }
> ```

Thank you

**Comment by igoroalonge** [comment]
I've found an easier way to fix it, just import using the **dynamic** function like:

```ts
const Plyr = dynamic(() => import("plyr-react"), { ssr: false });
```

**Comment by kwiromeo** [comment]
> I've found an easier way to fix it, just import using the **dynamic** function like:
> 
> ```ts
> import dynamic from 'next/dynamic'
> const Plyr = dynamic(() => import("plyr-react"), { ssr: false });
> ```

This fixed my issue.

**Comment by timneutkens** [comment]
There's an issue on that library: https://github.com/chintan9/plyr-react/issues/873. This is not a Next.js issue but an issue in the library used as it's reading `document` in the module scope. `document` is not available in server environments. Additionally this indicates that the library is not fully compatible with React as it tries to read/modify `document` outside of `useEffect`.
