### ISSUE TITLE
Having a certain `browserslist` config breaks React imports

### ISSUE THREAD

**Issue by chevsky** [vercel/next.js#60909]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/naughty-pare-hypr4c?file=%2Fpackage.json%3A6%2C17

### To Reproduce

1. Create a new Next.js app using `npx create-next-app@latest`
2. Add `"browserslist": ["Chrome 119"]` config to `package.json`
3. Go to `app/page.js` and import something from React like `import { useState } from "react"`
4. `npm run dev`

### Current vs. Expected behavior

Dev server output:
```sh
✓ Ready in 2.8s
 ○ Compiling / ...
 ⚠ ./app/page.tsx
Attempted import error: 'jsxDEV' is not exported from 'react/jsx-dev-runtime' (imported as '_jsxDEV').

Import trace for requested module:
./app/page.tsx
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.6.12
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

Changing Browserslist value to `["Chrome 118"]` or lower fixes the issue.

**Comment by chevsky** [comment]
Similar issue https://github.com/vercel/next.js/issues/60897#issuecomment-1900802891

**Comment by alitas** [comment]
As a workaround, adding `"Chrome 118"` into the browserslist seems to solve the problem. Both `["Chrome 118"]` and `["Chrome 118", "Chrome 119"]` work fine, but `["Chrome 119"]` by itself doesn't. 

Even the following works as long as we have the Chrome 118 there.

```
[development]
Chrome 118
last 1 chrome version
last 1 edge version
last 1 firefox version
last 1 safari version
```

**Comment by atstoyanov** [comment]
> As a workaround, adding `"Chrome 118"` into the browserslist seems to solve the problem. Both `["Chrome 118"]` and `["Chrome 118", "Chrome 119"]` work fine, but `["Chrome 119"]` by itself doesn't.
> 
> Even the following works as long as we have the Chrome 118 there.
> 
> ```
> [development]
> Chrome 118
> last 1 chrome version
> last 1 edge version
> last 1 firefox version
> last 1 safari version
> ```

Don't forget to clear the `.next` folder after the `package.json` update. For me it didn't work until I removed the .next folder.

**Comment by linkm-ampere** [comment]
Same similar issue when moving from 14.0.4 to 14.1.0, where everything else in the system is unchanged.
Seems to break all imports from React:

`Attempted import error: 'useContext' is not exported from 'react' (imported as 'useContext').`
`Attempted import error: 'createElement' is not exported from 'react' (imported as 'React').`
so forth and so on.

as well as the jsx one.

**Comment by edatcd** [comment]
Just jumping in to add that I'm also getting the same issue, and am using the 'Chrome 118' workaround for now.

**Comment by chevsky** [comment]
The core issue has been fixed in https://github.com/vercel/next.js/pull/61791, so we need to wait for the next stable version.

Until then, keep `Chrome 118` in your `browserslist` config as a workaround.
