### ISSUE TITLE
`next build` fails for parallel routes w/ edge runtime

### ISSUE THREAD

**Issue by aplr** [vercel/next.js#60917]
Running `next build` in a project w/ parallel routes + edge runtime enabled results in a "no such file or directory default_client-reference-manifest.js" build error.

This issue happens since 4.1.0, builds were running through smoothly until trying to update.

This bug only appears when enabling the edge runtime. When the edge runtime is not enabled, the build does not fail.

### Link to the code that reproduces this issue

https://github.com/aplr/next_parallel_routes_default_build_issue

### To Reproduce

1. Implement parallel routes w/ default.tsx fallback as described in [the docs](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes)
2. Turn on the edge runtime in your root `layout.tsx`
3. Run `next build`
4. Watch the build fail

### Current vs. Expected behavior

Current: build error
Expected: no build error

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 21.5.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.14.1
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

Build logs

```
> next_parallel_routes_default_build_issue@0.1.0 build
> next build

   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
Error: ENOENT: no such file or directory, open '/next_parallel_routes_default_build_issue/.next/server/app/@modal/hi/default_client-reference-manifest.js'
    at readFileSync (node:fs:453:20)
    at evaluateInContext (/next_parallel_routes_default_build_issue/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/context.js:375:50)
    at getRuntimeContext (/next_parallel_routes_default_build_issue/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/sandbox.js:70:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /next_parallel_routes_default_build_issue/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1088:29
    at async Span.traceAsyncFn (/next_parallel_routes_default_build_issue/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/trace/trace.js:151:20) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/next_parallel_routes_default_build_issue/.next/server/app/@modal/hi/default_client-reference-manifest.js'
}

> Build error occurred
Error: Failed to collect page data for /hi/default
    at /next_parallel_routes_default_build_issue/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1258:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.
```

<sub>[NEXT-2241](https://linear.app/vercel/issue/NEXT-2241/next-build-fails-for-parallel-routes-w-edge-runtime)</sub>

**Comment by mattiaz9** [comment]
I can add that this issue started appearing since `next@14.0.5-canary.41`.
Rolling back to `next@14.0.5-canary.40` will make the error disappear.
