### ISSUE TITLE
Docs: broken link in Data Fetching: Server Actions and Mutations

### ISSUE THREAD

**Issue by pwbriggs** [vercel/next.js#60953]
### What is the improvement or update you wish to see?

The "Data Fetching: Server Actions and Mutations" page has a broken link, `https://react.dev/docs/forms#handling-multiple-submit-buttons`, at [line 526](https://github.com/vercel/next.js/blob/canary/docs/02-app/01-building-your-application/02-data-fetching/02-server-actions-and-mutations.mdx#L526). I'm not sure what it's supposed to link to (I'm not a Next.js user), but maybe https://react.dev/reference/react-dom/components/form#handling-multiple-submission-types?

### Is there any context that might help us understand?

Originally reported at reactjs/react.dev#6566.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#nested-elements

**Comment by delbaoliveira** [comment]
Thank you for reporting the broken link @pwbriggs  🙏🏼  Addressed here: https://github.com/vercel/next.js/pull/60960
