### ISSUE TITLE
Calling revalidatePath() or revalidateTag() in Server Actions triggered by Intercepting Routes breaks routing

### ISSUE THREAD

**Issue by flsilva** [vercel/next.js#60950]
### Link to the code that reproduces this issue

https://github.com/flsilva/next-v14-revalidate-issue-2

### To Reproduce

Steps to reproduce bugs 1 and 2:

1. Visit https://next-v14-revalidate-issue-2.vercel.app

2. Fill in the **name** input text at **Default children slot box**.

3. Click the **Submit** button below the input field.

4. It works as expected. The **Submit** button changes to **Submitting...** and after 3 seconds it changes back to **Submit**, and we can see the Server Action's response.

5. Click **Nav to /foo** to visit the Intercepting Route **/foo**. Navigating to it works as expected, i.e., you'll see **/src/app/@intercept/(.)foo/page.tsx** content at the **intercept slot box**.

6. Fill in the **name** input text in the form at **intercept slot box**.

7. Click the **Submit** button in below the input text.

8. The form submission works as expected, but we have a bug here. The content at **Default children slot box** goes away, but it shouldn't. This is **bug 1**.

9. Do it again (second time), i.e., fill in the **name** input text in the form at **intercept slot box**, without refreshing the browser. **It does work**.

10. Do it again (third time), i.e., fill in the **name** input text in the form at **intercept slot box**, without refreshing the browser. **It does NOT work**.

11. We have another bug. We get a behavior equivalent to a hard reload. The page at **intercept slot box** goes away, and **/src/app/foo/page.tsx** is rendered at **Default children slot box**, exactly as if we did a manual hard reload. This is **bug 2**.

### Current vs. Expected behavior

Current behavior is described in the steps to reproduce above.

Expected behavior:

For **bug 1**: The content at **Default children slot box** shouldn't go away.

For **bug 2**:

a. The content at **intercept slot box** shouldn't go away.
b. The **/src/app/foo/page.tsx** shouldn't get rendered at **Default children slot box**.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.4 // Latest available version is detected (14.1.1-canary.4).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

I can reproduce the issue in v14.1.1-canary.4 on localhost and Vercel.

Code changes that results in the same behavior:

1. Changing revalidatePath('/') to revalidatePath('/', 'page').
2. Changing revalidatePath('/') to revalidatePath('/', 'layout').
3. Changing revalidatePath('/') to revalidatePath('/foo').
4. Changing revalidatePath('/') to revalidatePath('/foo', 'page').
5. Changing revalidatePath('/') to revalidatePath('/foo', 'layout').
6. Replacing revalidatePath() with revalidateTag('anything').

Code changes that results in the expected behavior:

1. If we comment out the **revalidatePath('/')** line of code in **action.ts** everything works as expected **because we're not relying on cached data in this app**, showing that the bug only happens when we use that function.

Routing structure:

```
app
├── @intercept
│   ├── (.)foo
│   │   └── page.tsx
│   └── default.tsx
├── foo
│   └── page.tsx
├── layout.tsx
└── page.tsx
```

Relevant code:

app/action.ts

```ts
"use server";

import { revalidatePath } from "next/cache";

export const action = async (
  previousState: string | undefined,
  formData: FormData
) => {
  const name = formData.get("name");
  await new Promise((resolve) => setTimeout(resolve, 3000));
  revalidatePath("/");
  return `name: ${name} | Math.random(): ${(Math.random() * 100).toFixed(2)}`;
};
```

Replay:

![next-v14-revalidate-issue-2](https://github.com/vercel/next.js/assets/544957/f29e78d9-59f8-4d31-8ba3-b0ec7709f245)

<sub>[NEXT-2852](https://linear.app/vercel/issue/NEXT-2852/calling-revalidatepath-or-revalidatetag-in-server-actions-triggered-by)</sub>

**Comment by flsilva** [comment]
@gipeey @zitooo @ahrbil @OlegLustenko @arikchakma You might be interested to know about this issue, as you engaged in a related one (this one https://github.com/vercel/next.js/issues/58772), preventing us of doing precisely the same thing: using revalidateTag() and revalidatePath() in Intercepting Routes. Please give this a thumbs up if you find this relevant, as it helps the core team to prioritize issues to work on.

**Comment by flsilva** [comment]
Upgraded Next to latest canary: v14.1.1-canary.5. Same behavior.

**Comment by flsilva** [comment]
Upgraded Next to latest canary: v14.1.1-canary.37. Same behavior.

**Comment by flsilva** [comment]
Upgraded to latest canary v14.1.1-canary.62 and got the same behavior.

**Comment by flsilva** [comment]
Upgraded to 14.2.0-canary.0. Same behavior.

**Comment by steve-marmalade** [comment]
@flsilva do you think this is the same issue that's being tracked in https://github.com/vercel/next.js/issues/51714 ?

**Comment by flsilva** [comment]
@steve-marmalade I tried to access the sandbox to look into the code but got 404, so not sure but if I understand correctly that's probably using router.refresh(), in which case it's not the same as here I'm not using it, but it's definitely related.

**Comment by flsilva** [comment]
Upgraded to 14.2.0-canary.29 and got the same behavior.

**Comment by sim391calado** [comment]
I've upgraded to 14.2.0-canary.33 and some part of the bug was fixed. In terms of doing server actions seems that it doesn't break anymore, but intercepting modal is automatically closing after calling a server action 3 times.

**Comment by schimi-dev** [comment]
When `revalidatePath` is called on an intercepted route where the page has dynamic `params` these params are `undefined` when revalidation triggers a rerender of that page.

**Comment by sim391calado** [comment]
> When `revalidatePath` is called on an intercepted route where the page has dynamic `params` these params are `undefined` when revalidation triggers a rerender of that page.

For me it's working well now, and the params are not showing undefined on my dynamic intercepting route. Make sure you update to the latest canary.

**Comment by BobbiSixkiller** [comment]
For me, if i call a server action with revalidateTag on a form submission rendered inside a modal (implemented using intercepted route pattern) the router doesn't work. On successful form submission I try to navigate back but instead a route that is being intercepted is rendered.
