### ISSUE TITLE
Modal with parallel routes multiple fetch bug

### ISSUE THREAD

**Issue by sergitejada** [vercel/next.js#60990]
### Link to the code that reproduces this issue

https://github.com/sergitejada/example-parallel-bug

### To Reproduce

1. start the app
2. go to a list page
3.  click a item, load the modal, 
4. close the modal, see multiple list page fetchs 

### Current vs. Expected behavior
![image](https://github.com/vercel/next.js/assets/49126831/81fd7b10-2800-41d0-852c-5f1a61dba537)

[screen-capture (2).webm](https://github.com/vercel/next.js/assets/49126831/af4997fa-8838-4d47-b6e3-8ac51b4d9b84)
Pararllel route with a modal are fetching multiple times i mean it's a error

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 21.4.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by ztanner** [comment]
Hi there -- thanks for the reproduction. I don't have access to the local API you're using, but I tested your reproduction against the latest canary and wasn't observing the behavior you described.

I've attached a video below, where I'm explicitly logging in the spots that you were calling `127.0.0.1:4000/api`:


https://github.com/vercel/next.js/assets/1939140/c38d899d-b66b-47ea-ae98-cd2a5fbbfe42

I'm going to close this, but let us know if you still aren't able to get it working after testing the latest canary, and we can investigate further. Thank you!
