### ISSUE TITLE
Bug using async/await in child component while parent has 'use client'

### ISSUE THREAD

**Issue by temito93** [vercel/next.js#60999]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/temo-nextjs-bug-sthkff

### To Reproduce

Wrap page component or children in root layout with component which is 'use client'

### Current vs. Expected behavior

Im wrapping page server component with StoreProvider (which is client component) in RootLayout.
I should get an error for using async/await but there is no error. everything is in client component and 
because of async/await sometimes it gives me an error and mostly it runs without any compilation issues.

```
//Root Layout
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/MainHeader/MainHeader";
import { NextIntlClientProvider, useMessages } from "next-intl";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "",
  description: "",
};

export default function RootLayout({ children, params: { locale } }) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <StoreProvider>
          <NextIntlClientProvider messages={messages}>
            <MainHeader />
            {children}
          </NextIntlClientProvider>
        </StoreProvider>
      </body>
    </html>
  );
}

//Provider component

"use client";
import { store } from "@/lib/store";
import { useRef } from "react";
import { Provider } from "react-redux";

export default function StoreProvider({ children }) {
  const storeRef = useRef();
  if (!storeRef.current) {
    // Create the store instance the first time this renders
    storeRef.current = store();
  }

  return <Provider store={storeRef.current}>{children}</Provider>;
}

//This is my server page.jsx
import { universities } from "@/services/api";
import Universities from "@/components/pages/Universities/Universities";
import Container from "@/components/Container/Container";

const UniversityPage = async () => {
  const universitiesData = await fetch(universities, {
    cache: "no-store",
    headers: { accept: "application/json" },
  });

  const data = await universitiesData.json();

  console.log("server fetch", data);

  return (
    <Container>
      <Universities data={data} />
    </Container>
  );
};

export default UniversityPage;

```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112
Binaries:
  Node: 18.16.0
  npm: 9.6.7
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by ArnaudBand** [comment]
You're using async/await in a component (`UniversityPage`), and you're wrapping that component with a client-side component (`StoreProvider`). Sometimes, you expect errors related to async/await, but you're not always getting them.

Here's why:

1. **Client vs. Server Execution**: The `StoreProvider` is for the client side, and it doesn't directly deal with async/await in server-side code. Async/await issues are usually more relevant on the server side.

2. **Async on the Server**: When you use `async` in `UniversityPage`, it tells Next.js that this component might involve server-side logic during the initial request. However, Next.js might decide to run it on the client side for subsequent navigations if there are no specific data fetching requirements.

3. **Client-Side Behavior**: If `UniversityPage` runs on the client side, async/await may not always cause errors. It depends on various factors like timing and conditions during client-side execution.

For consistent server-side execution and to catch potential async/await issues, you can use Next.js data fetching methods like `getServerSideProps`. This ensures that data fetching happens on the server side during the initial request, helping to avoid inconsistencies between client and server execution.

**Comment by temito93** [comment]
@ArnaudBand Thanks for your reply. I understood what you wrote but nextjs shouldn't let me write async/await in client component.

**Comment by bonface221** [comment]
@temito93  A server component wrapped in a client component  is executed on the server 😁

same way we use component libraries like chakra ui and still use async and await in the child server components
