### ISSUE TITLE
Regression: Setting `distDir` with  `{output: 'export'}` causes error in 14.1.0. 

### ISSUE THREAD

**Issue by DarkGuy10** [vercel/next.js#61041]
### Link to the code that reproduces this issue

https://github.com/DarkGuy10/next-bug-repro

### To Reproduce

1. Start the application in development mode (next dev)
2. Visit local url

### Current vs. Expected behavior

Prior to 14.1.0, the development server worked properly.

After upgrading, here's the errors i get:
```
# Console
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000

 ✓ Ready in 2.3s
 ○ Compiling / ...
 ✓ Compiled / in 3.2s (522 modules)
 ○ Compiling /not-found ...
 ✓ Compiled /not-found in 1054ms (495 modules)
 ⨯ Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: X:\GitHub\next-bug-repro\build\server\middleware-manifest.json
Not found: X:\GitHub\next-bug-repro\build\server\middleware-manifest.json
Not found: X:\GitHub\next-bug-repro\build\server\middleware-manifest.json.js
Not found: X:\GitHub\next-bug-repro\build\server\middleware-manifest.json.json
Not found: X:\GitHub\next-bug-repro\build\server\middleware-manifest.json.node

Require stack:
...
```
_Screenshot from my browser:_

![image](https://github.com/vercel/next.js/assets/62807269/cf68af57-5c39-416f-ab69-8bca33e64333)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Reverting to 14.0.4 fixes the problem.
Also, the error happens only when setting both `{distDir: 'build'}` and `{output: 'export'}` together. Individually, they work just fine.
I've checked the latest canary version (14.1.1-canary.7), and the issue still persists.

**Comment by samcx** [comment]
@DarkGuy10 Thank you for submitting an issue!

It looks like we pushed a 🐛 up with our bot that was incorrectly closing issues—that has since been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture>!
