### ISSUE TITLE
Memory leak with Next.js 14.1.0 with Turbopack

### ISSUE THREAD

**Issue by steelbrain** [vercel/next.js#61063]
### Link to the code that reproduces this issue

_

### To Reproduce

1. `yarn dev`
2. Watch the memory usage go up

### Current vs. Expected behavior

I expect the memory usage to stabalise around 2GB, just like with the non-turbo run

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 3.6.4
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I have reproduced the same error in Next.js 14.1.1-canary.7. I cannot share the full project but I can very reliable reproduce this. So please let me know what debug output can I generate and then share with you to help debug this.

<img src="https://github.com/vercel/next.js/assets/4278113/591a5d24-afdd-477c-8041-af7618675fa3">

**Comment by ForsakenHarmony** [comment]
It's not a memory leak, unfortunately turbopack just uses a lot of memory right now to be fully incremental.
