### ISSUE TITLE
Parallel route is not using default after a client-side navigation

### ISSUE THREAD

**Issue by benjamintd** [vercel/next.js#61139]
### Link to the code that reproduces this issue

https://github.com/benjamintd/next-parallel-routes-repro

### To Reproduce

When running the built (or dev) version locally (npm run build && npm run start):
Heading to "http://localhost:3000/" works
Heading to "http://localhost:3000/about" works
Navigation between the home and "/sign-in" pages works, client-side navigation included
However, navigation between "/about" and "/" (via the "Close" button) keeps the modal open.
This has been tested on next@14.1.0 and next@canary (14.1.1-canary.9)

### Current vs. Expected behavior

The Close button should render the home page with the default (i.e. empty) modal, not the /about modal.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 7.28.0
Relevant Packages:
  next: 14.1.1-canary.10 // Latest available version is detected (14.1.1-canary.10).
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

**Comment by ztanner** [comment]
Hi, it looks like this behavior is expected with how your app is structured.

The specific part of the parallel routes [documentation](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes) that talks about this behavior is:

> [Soft Navigation](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#5-soft-navigation): During client-side navigation, Next.js will perform a [partial render](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#4-partial-rendering), changing the subpage within the slot, while maintaining the other slot's active subpages, even if they don't match the current URL.

In other words, since the `@modal` slot was active on the `/about` page, but has no match on the `/` page, navigation will keep the slot that was previously active rather than triggering the `default` fallback. To get the behavior you're describing, you could add catch-all page to the `@modal` slot that returns `null`, as described in the [dismissing a modal](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#dismissing-a-modal) section. Let me know if you have any questions about this behavior or can't get it to work!

**Comment by ammar-oker** [comment]
I faced the same issue which seemed weird given that `router.back()` closes the modal but `router.push('/')` doesn't. I worked around this issue by conditionally rendering the modal based on the current route. not sure if this is the best approach though.

```tsx
'use client';

import { usePathname, useRouter } from "next/navigation";

export default function Modal() {
  const router = useRouter();
  const pathname = usePathname();

   // this workaround is needed to prevent the modal from rendering on the wrong route
  if (pathname !== '/modal') {
    return null;
  }

  const handleClose = () => {
    // router.back(); // this changes the URL and closes the modal
    router.push('/'); // this changes the URL but does not close the modal
  }

  return (
    <div style={{ border: '1px solid blue', padding: 12 }}>
      <h2>Modal</h2>
      <button onClick={handleClose}>Close modal</button>
    </div>
  );
}

```

**Comment by ammar-oker** [comment]
> Hi, it looks like this behavior is expected with how your app is structured.
> 
> The specific part of the parallel routes [documentation](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes) that talks about this behavior is:
> 
> > [Soft Navigation](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#5-soft-navigation): During client-side navigation, Next.js will perform a [partial render](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#4-partial-rendering), changing the subpage within the slot, while maintaining the other slot's active subpages, even if they don't match the current URL.
> 
> In other words, since the `@modal` slot was active on the `/about` page, but has no match on the `/` page, navigation will keep the slot that was previously active rather than triggering the `default` fallback. To get the behavior you're describing, you could add catch-all page to the `@modal` slot that returns `null`, as described in the [dismissing a modal](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#dismissing-a-modal) section. Let me know if you have any questions about this behavior or can't get it to work!

@ztanner btw the link you shared doesn't seem to be addressing this issue

**Comment by lxia1220** [comment]
> > Hi, it looks like this behavior is expected with how your app is structured.
> 
> > 
> 
> > The specific part of the parallel routes [documentation](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes) that talks about this behavior is:
> 
> > 
> 
> > > [Soft Navigation](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#5-soft-navigation): During client-side navigation, Next.js will perform a [partial render](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#4-partial-rendering), changing the subpage within the slot, while maintaining the other slot's active subpages, even if they don't match the current URL.
> 
> > 
> 
> > In other words, since the `@modal` slot was active on the `/about` page, but has no match on the `/` page, navigation will keep the slot that was previously active rather than triggering the `default` fallback. To get the behavior you're describing, you could add catch-all page to the `@modal` slot that returns `null`, as described in the [dismissing a modal](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#dismissing-a-modal) section. Let me know if you have any questions about this behavior or can't get it to work!
> 
> 
> 
> @ztanner btw the link you shared doesn't seem to be addressing this issue

can be hacked with [...catchAll] return null;

It's strange that there is no consistency on some parallel route features

**Comment by ztanner** [comment]
> > Hi, it looks like this behavior is expected with how your app is structured.
> > The specific part of the parallel routes [documentation](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes) that talks about this behavior is:
> > > [Soft Navigation](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#5-soft-navigation): During client-side navigation, Next.js will perform a [partial render](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#4-partial-rendering), changing the subpage within the slot, while maintaining the other slot's active subpages, even if they don't match the current URL.
> > 
> > 
> > In other words, since the `@modal` slot was active on the `/about` page, but has no match on the `/` page, navigation will keep the slot that was previously active rather than triggering the `default` fallback. To get the behavior you're describing, you could add catch-all page to the `@modal` slot that returns `null`, as described in the [dismissing a modal](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#dismissing-a-modal) section. Let me know if you have any questions about this behavior or can't get it to work!
> 
> @ztanner btw the link you shared doesn't seem to be addressing this issue

Sorry, looks like the headings changed, so the link isn't jumping to the same spot anymore. But I was linking to the "Closing a Modal" section on that page, which means the `[...catchAll]` approach mentioned in the above comment. 

`router.back()` closes the modal because it returns the router to the previous state. `router.push` is like clicking a link, so it follows the rules of parallel routes, which is to say that it will continue to render whatever was in that slot position until there's a new match, or until you reload the page.

@lxia1220 can you clarify which features aren't consistent? We're working on improving the DX surrounding parallel routes so would love to better understand what you mean.
