### ISSUE TITLE
[Block] 14.1.0 `next dev` throw error Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'useLayoutEffect').

### ISSUE THREAD

**Issue by tianyingchun** [vercel/next.js#61185]
### Link to the code that reproduces this issue

https://github.com/tianyingchun/next-issue

### To Reproduce

1. yarn install
2. yarn dev

### Current vs. Expected behavior

throw error in `next dev mode` 
```shell
- info Server env(s) validation successful:
- info Server env(s) validation successful:
   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env

 ✓ Ready in 4s
 ✓ Compiled /src/middleware in 91ms
 ✓ Compiled (148 modules)
 ○ Compiling /[locale]/[...rest] ...
 ⨯ ./node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.mjs
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'useLayoutEffect').

Import trace for requested module:
./node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.mjs
./node_modules/@mui/base/Unstable_Popup/Popup.js
./node_modules/@mui/base/Unstable_Popup/index.js
./node_modules/@mui/base/index.js
./node_modules/@mui/material/Popover/Popover.js
./node_modules/@mui/material/Popover/index.js
__barrel_optimize__?names=Popover!=!./node_modules/@mui/material/index.js
./node_modules/material-ui-popup-state/es/HoverPopover.mjs
./src/components/LocaleSwitcher/LocaleSwitcher.tsx
 ⨯ ./node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.mjs
Attempted import error: 'useLayoutEffect' is not exported from 'react' (imported as 'useLayoutEffect').

Import trace for requested module:
./node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.mjs
./node_modules/@mui/base/Unstable_Popup/Popup.js
./node_modules/@mui/base/Unstable_Popup/index.js
./node_modules/@mui/base/index.js
./node_modules/@mui/material/Popover/Popover.js
./node_modules/@mui/material/Popover/index.js
__barrel_optimize__?names=Popover!=!./node_modules/@mui/material/index.js
./node_modules/material-ui-popup-state/es/HoverPopover.mjs
./src/components/LocaleSwitcher/LocaleSwitcher.tsx
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
```

yarn build works fine.

### Provide environment information

```bash
- info Server env(s) validation successful:

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 4.0.2
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

1. ` next dev ` can works correct on `   "next": "14.0.4",`
2. ` next dev ` can  not works correct on `   "next": "14.1.0",`
3. `next build` can works correct both on 14.0.4 and 14.1.0****

**Comment by cthacker-udel** [comment]
Very similar bug: #60890

**Comment by zamarawka** [comment]
I encountered exactly the same error after update on 14.1.0.
Every import from react with error

**Comment by limpep** [comment]
Getting the same error

**Comment by NewEditOfficial** [comment]
> I encountered exactly the same error after update on 14.1.0. Every import from react with error.
> 
> Don't understand how, but
> 
> ```
> rm -rf .next
> ```
> 
> with remove `browserList` from `package.json` helps to run app..

I was getting same error this tip resolved it temporarily until its fixed.👍

**Comment by gaojude** [comment]
> I encountered exactly the same error after update on 14.1.0. Every import from react with error.
> 
> Don't understand how, but
> 
> ```
> rm -rf .next
> ```
> 
> with remove `browserList` from `package.json` helps to run app..

what if i do need this field for other purposes? is there a way for next.js build to not look at the browserList field even when its there?

**Comment by mrksph** [comment]
This is a joke, how do you suggest to  upgrade to the latest version with stupid errors like this? Thank god all I have to do is delete a .next folder and a property from package.json.... When will this fix be released? @huozhi ?

Btw, thanks for the work around @s0h311

**Comment by huozhi** [comment]
We had a fix in https://github.com/vercel/next.js/pull/61791 and released in v14.1.1-canary.44 for this issue, please upgrade to any canary versions above that one

**Comment by Eunkyung-Son** [comment]
This error occurs during build time on pages using the edge runtime.
![image](https://github.com/vercel/next.js/assets/68625841/9069078a-194d-4fd9-91fd-18b1a08af237)
![image](https://github.com/vercel/next.js/assets/68625841/73a794df-9fcd-4365-9966-c7fc9d679784)

**Comment by rakibatomnixima** [comment]
still having this error on latest canary build on edge runtime
