### ISSUE TITLE
next/dynamic in client components cause css to be loaded to late

### ISSUE THREAD

**Issue by iljamulders** [vercel/next.js#61212]
### Link to the code that reproduces this issue

https://github.com/iljamulders/nextjs-dynamic-css

### To Reproduce

1. Start the application in development (next dev) OR production (next build && next start)
2. Go to http://localhost:3000/pages-route and http://localhost:3000/app-route
3. In the `app-route` the css is not loaded as soon as possible.
4. This leads to [Cumulative Layout Shift (CLS)](https://web.dev/articles/cls) and an ugly website.

Pages router             |  App router
:-------------------------:|:-------------------------:
![pages](https://github.com/vercel/next.js/assets/6195121/ef4e7876-d32a-4be8-8ef8-c935d678442a)  |  ![app](https://github.com/vercel/next.js/assets/6195121/bcf67d2f-afd9-45b7-98a4-eea76f035f60)

### Current vs. Expected behavior

When using [next/dynamic](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#nextdynamic) inside a client component in the app router I expect the css for that component to be loaded as soon as possible.

Just as in the pages router.

```tsx
// app/default-layout-app/DefaultLayoutApp.tsx
'use client'

import dynamic from "next/dynamic";

const TestWithCss = dynamic(() => import('../../components/test-with-css/TestWithCss'))

const someCondition = true;

export default function DefaultLayoutApp() {
    return (
      <>
        <h1>App, css delay:</h1>
        {
          someCondition &&
          <TestWithCss />
        }
      </>
    );
  }
```

```tsx
// components/test-with-css/TestWithCss.tsx

import styles from './TestWithCss.module.scss'

export default function TestWithCss() {
    return (
      <div className={styles.background}>
        <p>
          In the pages router the css is loaded as soon as possible: correct <br />
          In the app router the css is loaded way to late: incorrect
        </p>
        <p>
          This leads to <a href="https://web.dev/articles/cls">Cumulative Layout Shift (CLS)</a> and an ugly website
        </p>
      </div>
    );
  }
  
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 20.9.0
  npm: 10.2.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.12 // There is a newer canary version (14.1.1-canary.13) available, please upgrade!
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Dynamic imports (next/dynamic)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed), Other (Deployed)

**Comment by ben519** [comment]
Curious, why are you loading css with a dynamic import? My understanding is that CSS _should_ be loaded in the page `<head>` which is one of the first things the server sends to the client.

**Comment by iljamulders** [comment]
@ben519 

We have a complex website where content editors can create pages in a headless cms with 30+ components (sections, etc) they can plug into these pages. On average a page contains around ~5 of these components. Loading the js and css for 30+ components while a users is only seeing ~5 would be a shame.

This is where next/dynamic comes into play, and works perfectly fine in the pages router!
When the pages router detects a dynamic component being rendered (during the server rendering) it will add the css to the `<head>`

Example:
```tsx
// pages/[[...url]].tsx

import React, { ReactElement } from 'react'
import dynamic from 'next/dynamic'
import { GetServerSideProps, NextPage } from 'next'

// For this example the types are made up or set to any!

type CatchAllProps = {
    sections: {
        name: 'sectionHero' | 'sectionGoogleMaps' | 'sectionProductOverview' | 'whatever' // 30+
        props: any
    }[]
}

export const getServerSideProps: GetServerSideProps<CatchAllProps> = async (context) => {
    const response = await fetch(`https://some-headless-cms.com/url?${context.req.url}`)
    const sections = await response.json()

    return {
        props: {
            sections
        }
    }
}

const SECTIONS: {[key: string]: React.ComponentType<any>} = {
    sectionHero: dynamic(() => import('components/sections/hero/SectionHero')),
    sectionGoogleMaps: dynamic(() => import('components/sections/map/SectionGoogleMaps')),
    sectionProductOverview: dynamic(() => import('components/sections/map/SectionGoogleMaps'))
    // + 30 more
}

const CatchAll: NextPage<CatchAllProps> = ({ sections }) => {

    const sectionsToRender: ReactElement<any>[] = []

    sections.forEach(section => {
        sectionsToRender.push(React.createElement<any>(SECTIONS[section.name], section.props))
    })

    return <>
        {sectionsToRender}
    </>
}

export default CatchAll
```

But in the the new app router, the css is loaded to late. This is not documented in the documentation, nor in the breaking changes between 12 and 13/14. Now that I look at it further, I don't even see the js code splitting taking place when the dynamic (client) component is loaded from a server component 🤔

**Comment by hamlim** [comment]
We've found the same exact limitation as well, experimented with a few options in this reproduction repo also: https://github.com/hamlim/next-dynamic-app-router-bug

One possible solve we found was hoisting the styles up to a server component and importing them there. Our use case is a bit more complex than the original issue, but is effectively the same bug.
