### ISSUE TITLE
Socketio not working in PROD but working in DEV

### ISSUE THREAD

**Issue by Dun-sin** [vercel/next.js#61232]
### Link to the code that reproduces this issue

https://github.com/dun-sin/whisper

### To Reproduce

Can't reproduce this in dev.
Look at it here in prod: whischat.vercel.app

### Current vs. Expected behavior

Current: getting 404 in the console
expected: should connect like in dev env

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
Binaries:
  Node: 20.11.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by devodii** [comment]
Hey dun-sin.
It works great 
As a matter of fact, we're using next js /app dir  with socket io to handle the conversations in [tarotmaster.ai](https://tarotmaster.ai)

The only issues that we experience is that the terminal always gets messy (with soo many errors from socket.io as i do not think it is fully compatible with it), again this is why i love to stick with react.

But, it builds the application properly, and that's all we want :)

**Comment by Dun-sin** [comment]
> Hey dun-sin. It works great As a matter of fact, we're using next js /app dir with socket io to handle the conversations in [tarotmaster.ai](https://tarotmaster.ai)
> 
> The only issues that we experience is that the terminal always gets messy (with soo many errors from socket.io as i do not think it is fully compatible with it), again this is why i love to stick with react.
> 
> But, it builds the application properly, and that's all we want :)

doesn't work for me tho, thanks for letting me know it works for you but it doesn't help me here
