### ISSUE TITLE
Calling headers or cookies from a function imported into RSC works but errors on build

### ISSUE THREAD

**Issue by rydonahue1** [vercel/next.js#61276]
### Link to the code that reproduces this issue

https://github.com/t3-oss/create-t3-app

### To Reproduce

1. Build a basic t3 app with TRCP
2. Remove the `no_store` call in the main page component
3. `npm run build`
4. DYNAMIC_SERVER_USAGE error gets thrown on build

### Current vs. Expected behavior

This occurs because the TRPC api call references `headers`, which technically works within the app, however only causes issues within the build process itself.

In fact calling the same endpoint from within a route handler works fine and does not happen to throw errors during build in the same way it does from the RSC. Ideally, since the function itself is actually working within the context of the RSC, I think it would be ideal to allow the build script to not throw an error when using it in this fashion as having to rely on work arounds such as `no_store` or `headers` being called from the top of your RSC that have no purpose other than bypassing this build error seems to be a bit of an anti-pattern.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

<sub>[NEXT-2297](https://linear.app/vercel/issue/NEXT-2297/calling-headers-or-cookies-from-a-function-imported-into-rsc-works-but)</sub>

**Comment by huozhi** [comment]
Seems it's working now, I'm trying with the `pnpm create t3-app@latest` command to create a repro and it build successfully. Do you have a repro link that we can directly checkout and test the build failure?

**Comment by rydonahue1** [comment]
> Seems it's working now, I'm trying with the `pnpm create t3-app@latest` command to create a repro and it build successfully. Do you have a repro link that we can directly checkout and test the build failure?

It works only because of the` no_store` above the RSC with the trpc api call. For some reason when building, Next doesn't detect the `headers()` function being called from `trpc/server.ts`. The `no_store` is simply there to get this error to go away on build, so if a developer forgets to mark every RSC with `no_store` then it will break the deploy.

Personally, I got around this by wrapping the trpc call in a wrapper function that requires me to pass in `headers` from my RSC so I can't accidentally forget, but that still feels a bit hackish since the `headers` call is just ran again where it is actually used.

**Comment by balazsorban44** [comment]
Closing as https://github.com/vercel/next.js/issues/61276#issuecomment-1916561430 and https://github.com/vercel/next.js/issues/61276#issuecomment-1916562077 have not been followed up as asked. If you still have this issue, please open a new bug report with an attached minimal, public github repo tested with `next@canary`, so we can investigate further.
