### ISSUE TITLE
Docs: Use `npm i -g` Instead of `yarn global add` on Dockerfile Example

### ISSUE THREAD

**Issue by rafaelcalpena** [vercel/next.js#61293]
### What is the improvement or update you wish to see?

Using `npm i -g pnpm` would be better than `yarn global add pnpm` because `npm` is always installed on the host, but `yarn` might not be depending on the project.

This change could also be applied to the multi-environment examples: https://github.com/vercel/next.js/blob/canary/examples/with-docker-multi-env/docker/development/Dockerfile#L15

### Is there any context that might help us understand?

I tried to use this Dockerfile as a starting point, but it failed when I attempted to build a `pnpm` project (monorepo) with Next as an app.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/deploying#docker-image

**Comment by samcx** [comment]
@rafaelcalpena Thank you for submitting an issue!

I will be submitting a <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture> for this.

**Comment by rafaelcalpena** [comment]
Fantastic! @samcx thank you for quickly submitting a PR with the fix!
