### ISSUE TITLE
with-strict-csp example fails with CSP related errors

### ISSUE THREAD

**Issue by frankimhof** [vercel/next.js#61316]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.11.0
Relevant Packages:
  next: 14.1.1-canary.20 // Latest available version is detected (14.1.1-canary.20).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-strict-csp

### What browser are you using? (if relevant)

brave 1.62.153

### Describe the Bug

Running the [with-strict-csp](https://github.com/vercel/next.js/tree/canary/examples/with-strict-csp) example app using `pnpm run dev` fails with the following errors in the browser console

```
Refused to load the script 'https://.../' because it violates the following
Content Security Policy directive:
"script-src 'self' 'nonce-YWMxYjA0ZTQtOGIyYS00MmY4LTk4YjctZjNjZTRiNTdkNGZl' 'strict-dynamic'".
Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed
source of script in the following Content Security Policy directive:
"script-src 'self' 'nonce-YWMxYjA0ZTQtOGIyYS00MmY4LTk4YjctZjNjZTRiNTdkNGZl' 'strict-dynamic'".
```

### Expected Behavior

The app runs and the page loads.

### To Reproduce

1. Download the example `pnpm create next-app --example with-strict-csp with-strict-csp-app`
2. Install dependencies `pnpm i`
3. run in developer mode `pnpm run dev`
4. Visit localhost:3000 in your browser and see the browser console output

<sub>[NEXT-2739](https://linear.app/vercel/issue/NEXT-2739/with-strict-csp-example-fails-with-csp-related-errors)</sub>

**Comment by samcx** [comment]
@frankimhof I think the first error just requires an working URL. The 2nd one had a <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture> that was merged, so just need to wait for the next release!
