### ISSUE TITLE
Docs: Is that in the wrong place?

### ISSUE THREAD

**Issue by trojanyao** [vercel/next.js#61315]
### What is the improvement or update you wish to see?

Move `redirect` related "Good to know" item from "`useRouter` hook" to "redirect function" section.

### Is there any context that might help us understand?

Why mentioned `redirect` in "`useRouter` hook" section? It's confusing. Should that be put in "redirect function" section? 

<img width="719" alt="Xnip2024-01-29_18-07-07" src="https://github.com/vercel/next.js/assets/22811809/df4a002f-b10d-4640-91d3-327cce0bc0c8">

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/redirecting#userouter-hook

**Comment by samcx** [comment]
@trojanyao It's similar to this page → https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#userouter-hook. I will be pushing up a <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture> to update this!
