### ISSUE TITLE
Server actions are executed on client when imported from an external package

### ISSUE THREAD

**Issue by Anduyosh** [vercel/next.js#61318]
### Link to the code that reproduces this issue

https://github.com/Anduyosh/next-server-actions-monorepo

### To Reproduce

1. Install all the dependencies.
2. Build the monorepo internal packages (`yarn build`, `npm run build`...)
3. Start the application and internal packages in development (`yarn dev`, `npm run dev`...)
4. Open a browser and access to `localhost:3000`. You will be redirected to `/login`.
5. Open the DevTools console and click on the _Sign in to your account_ button. The `login` server action is called.

### Current vs. Expected behavior

Following the steps from the previous section, I expected the `login` server action (from the `@next-server-actions-monorepo/actions` internal package) to be executed on the server, as the bundled file has the `"use server;` directive on top. However, the server action is being executed on the client (as the message from the DevTools console demonstrates).

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.17 // Latest available version is detected (14.1.1-canary.17).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested my reproduction against different releases (both stable and canary) with the same results. Note that the reproduction is in a context of a monorepo with internal packages that are built with `tsup` (although the `"use server;` directive is added on top of the bundled file using the `esbuild` banner option).

I assume that `next` doesn't really know that the `@next-server-actions-monorepo/actions` package is a server actions file despite being marked with `"use server;`. Other things I've tried:

- Add the `"use server;` directive inside the action block.
- Pass the imported action as a prop to the `LoginForm` component insted of using the `useFormState` hook.
- Adding the package to `transpilePackages` array in `next.config.js`.

I don't know if this is intended. In case it is, is there any workaround I can implement in order to tell `next` that it should treat that package as a server actions file?

**Comment by huozhi** [comment]
Verified with canary, this issue is fixed now w/wo turbopack, even when you don't have it defined in `transpilePackages`. Close it as fixed

**Comment by Anduyosh** [comment]
I also verified it on my repository and it now works perfectly ([v14.2.0-canary.13](https://github.com/vercel/next.js/releases/tag/v14.2.0-canary.13) in my case). Thank you! I really appreciate it!
