### ISSUE TITLE
next/image with {width: 100%, height: auto} causes wrapper element to be higher than the image itself

### ISSUE THREAD

**Issue by arosicki** [vercel/next.js#61398]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/9tg493

### To Reproduce

1. Insert next/image with {width: 100%, height: auto}, pass image dimensions for aspect ratio
2. Wrap the element with div element (add background-color, so the size difference is visible)
3. Add padding around the page so the issue is visible
**If viewing codepen start here** 
5. Start the app in development mode (or any other, occurs both in built apps and in dev mode)
6. Scroll to the bottom of / page
7. Wrapper div is 5px higher than next image despite no explicit size set

### Current vs. Expected behavior

Current: wrapper div is 5px higher than the image
Expected: wrapper div is same size as next image

### Provide environment information

```bash
# My system:
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: standalone

# Codepen:
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

For everyone else who's having this issue setting {marginBottom: -5px} on the div wraping next/image is a solution for now

**Comment by Timer** [comment]
This is the expected behavior of the platform's `<img>` tag out of the box. `<img>` defaults into `display: inline`, meaning it's rendered while respecting `line-height`.

This can be resolved in one of two ways:

1. In your parent component with the background, set `line-height: 0`
2. On your image, change to `display: block` or another mode that doesn't respect `line-height`.
