### ISSUE TITLE
Browser Navigation causes "Unhandled Runtime Error: async/await is not yet supported in Client Components"

### ISSUE THREAD

**Issue by stefandunn** [vercel/next.js#61418]
### Link to the code that reproduces this issue

https://github.com/stefandunn/Personal-Site---NextJS-Issue-Replication

### To Reproduce

1. Yarn install the dependencies `yarn install`
2. Run the application in development `yarn dev`
3. Go to http://localhost:3000/
4. Click on [Test Blog Post](http://localhost:3000/blog/hello-world/)
5. Wait for page to load
6. Click on "Home" button
7. Wait to go home /.
8. Use the browser navigation button to go back to the Blog post page.
9. Then use the browser navigation button to go forward back again to the homepage.

### Current vs. Expected behavior

**Current:**
Upon navigating out of a previously visited async page, you encounter the "Error: async/await is not yet supported in Client Components, only Server Components" error.
<img width="988" alt="300985430-35291afa-ab4a-4852-bd66-8676df9bb8e9" src="https://github.com/vercel/next.js/assets/873567/b33b6cfc-6e31-45df-b423-b8dac07d5a4c">

It's like the async has not been cleaned up from the previous route or is still pending elsewhere. The only file using `use client` is [this file](https://github.com/stefandunn/Personal-Site---NextJS-Issue-Replication/blob/master/src/components/Homepage/Techstack/Techstack.tsx) which has no `async` invocation or child component using an async invocation either.

**Expected:**
To behave in the same fashion as clicking on the "Home" button (next/link component)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
Binaries:
  Node: 20.5.0
  npm: 10.3.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

I have also tested with a static export and get a "Application error: a client-side exception has occurred (see the browser console for more information)." error when serving the static website.

**Comment by icyJoseph** [comment]
Hi,

In this file: 

- https://github.com/stefandunn/Personal-Site---NextJS-Issue-Replication/blob/master/src/components/Homepage/Techstack/Techstack.tsx

You opt into `use client`, and that file own the TechIcon component, by direct import.

If we look at `TechIcon`:

- https://github.com/stefandunn/Personal-Site---NextJS-Issue-Replication/blob/master/src/components/Homepage/TechIcon/TechIcon.tsx

```tsx
import React from "react";
import { TechIconProps } from "./TechIcon.types";

export const TechIcon: React.FC<TechIconProps> = async ({
  icon: { default: Icon },
  name,
}) => {
  return (
    <div className="flex flex-col gap-3 items-center">
      <Icon className="h-10 w-auto" />
      <span className="text-sm">{name}</span>
    </div>
  );
};
```

We see that you have made it `async` ~ That's the problem. Remove that `async` expression.

**Comment by stefandunn** [comment]
> Hi,
> 
> In this file:
> 
> * https://github.com/stefandunn/Personal-Site---NextJS-Issue-Replication/blob/master/src/components/Homepage/Techstack/Techstack.tsx
> 
> You opt into `use client`, and that file own the TechIcon component, by direct import.
> 
> If we look at `TechIcon`:
> 
> * https://github.com/stefandunn/Personal-Site---NextJS-Issue-Replication/blob/master/src/components/Homepage/TechIcon/TechIcon.tsx
> 
> ```tsx
> import React from "react";
> import { TechIconProps } from "./TechIcon.types";
> 
> export const TechIcon: React.FC<TechIconProps> = async ({
>   icon: { default: Icon },
>   name,
> }) => {
>   return (
>     <div className="flex flex-col gap-3 items-center">
>       <Icon className="h-10 w-auto" />
>       <span className="text-sm">{name}</span>
>     </div>
>   );
> };
> ```
> 
> We see that you have made it `async` ~ That's the problem. Remove that `async` expression.

Thank you so much! I really should have seen that myself.
