### ISSUE TITLE
Favicon does not prepend basePath.

### ISSUE THREAD

**Issue by TomppaPackage** [vercel/next.js#61487]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/heuristic-newton-9y9j2p?file=%2Fnext.config.js%3A3%2C20

### To Reproduce

1. Build The Application
2. Run the Application
3. Eagerly look for the presence of the Favicon, only to discover it is not there.
4. Look through the html source to discover that Next is looking for Favicon at `/favicon.ico` instead of `/app/favicon.ico`

### Current vs. Expected behavior

Currently, when `basePath` is set, the autogenerated HTML metadata will search for the presence of a Favicon at `/favicon.ico`

My expectation would be that `basePath` is prepended, and favicon will be fetched from `/app/favicon.ico`

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 4.0.2
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

**Comment by davelin18yufan** [comment]
Hey, your reproduce link is invalid.

By default, Next.js automatically looks for the favicon image file at top level of `/app` and compiles it into a `<link>` tag placed in the `<head>`. It's not evident from here, so the issue might need to be investigated within your files.

You can refer to [here](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons for more information.)

**Comment by TomppaPackage** [comment]
> Hey, your reproduce link is invalid.
> 
> By default, Next.js automatically looks for the favicon image file at top level of `/app` and compiles it into a `<link>` tag placed in the `<head>`. It's not evident from here, so the issue might need to be investigated within your files.
> 
> You can refer to [https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons](here) for more information.

My apologies, you are correct. Upon closer inspection, I can't reproduce the issue within the Sandbox either - It must be down to my configuration.

Closing this, will update if I find a solution, but this doesn't appear to be a bug with Next.
