### ISSUE TITLE
VSCode server-side debugging not working with turbopack

### ISSUE THREAD

**Issue by KajSzy** [vercel/next.js#61493]
### Link to the code that reproduces this issue

https://github.com/KajSzy/vscode-turbopack-debug

### To Reproduce

1. Setup breakpoint in `source/page.tsx`
2. Launch debug option `Next.js: debug server-side with turbo`

### Current vs. Expected behavior

Debugging should stop at selected breakpoint as it works without turbopack (when using `Next.js: debug server-side without turbo` config)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.13.1
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[PACK-2365](https://linear.app/vercel/issue/PACK-2365/vscode-server-side-debugging-not-working-with-turbopack)</sub>

**Comment by ForsakenHarmony** [comment]
This might be a source mapping issue, we just merged some fixes to that.
Can you try with the latest canary version?

**Comment by KajSzy** [comment]
Yes, its working with `14.1.1-canary.42` release
