### ISSUE TITLE
How to API call on server side when using Context API

### ISSUE THREAD

**Issue by krishnaacharyaa** [vercel/next.js#61494]
### Link to the code that reproduces this issue

https://github.com/krishnaacharyaa/nextjs-explore

### To Reproduce

1. Start the application
a. npm i
b. npm run dev

Run the app on localhost:3000

As i am using the Context Provider to manage state in the Nextjs application. I get access to any state variable using `useAppContext` which is available only on the client side. 

My use case is make server call using the variable state form the context API

Ex: In  `components\ThirdColumnComponent\SummaryDocumet.tsx` I want to make server side API call. How can I do? Presently using the old scholl `useEffect(()=>{},[])`

### Current vs. Expected behavior

Call API server side in the application using the Context API/ Context Provider. 

Current:
In  `components\ThirdColumnComponent\SummaryDocumet.tsx`  I am using useEffect and fetching client side.

Expectation:
Call the api `http://localhost:3000/api/summary/${selectedDocument?.DocumentId}` server side

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Enterprise
Binaries:
  Node: 20.11.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A


warn  - Latest canary version not detected, detected: "14.1.0", newest: "14.1.1-canary.27".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Data fetching (gS(S)P, getInitialProps)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I want to use Context because i want to avoid the props passing, But at the same time I want to fetch the API data from the server side. How can i achieve both at a same time...

Is there any suggested way?

**Comment by icyJoseph** [comment]
Hi,

Before I take a look, I think you should strongly consider opening discussion items, rather than issues. 

- https://github.com/vercel/next.js/discussions

Tons of people are willing to help over there. Here we should report actual faults in the framework. From the discussions we can arrive to the conclusion of whether or not an issue ought to be opened. 

I should also say that this is a personal take, and not related to the Vercel core team at all.

**Comment by krishnaacharyaa** [comment]
Sure @icyJoseph, sorry.
https://github.com/vercel/next.js/discussions/61515 Opened the discussion.

Kindly let me know your thoughts on this when you get some time to spare :)
