### ISSUE TITLE
EDGE_FUNCTION_INVOCATION_FAILED OAuthStrategy.js

### ISSUE THREAD

**Issue by avoirsolutions** [vercel/next.js#61516]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 11 Pro
    Binaries:
      Node: 20.9.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.9
      eslint-config-next: 13.5.6
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.8.4
    Next.js Config:
      output: N/A
```

### Which example does this report relate to?

wix-commerce-ticketing-nextjs-template

### What browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I have a solution running locally and when I deploy it under Vercel, I get teh following error:
[GET] [middleware: "middleware"] / reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
and then:
Error: something went wrong
    at (node_modules/@wix/sdk/build/auth/oauth2/OAuthStrategy.js:353:14)
    at (node_modules/@wix/sdk/build/auth/oauth2/OAuthStrategy.js:54:31)
    at (middleware.ts:21:17)
    at (node_modules/next/dist/esm/server/web/adapter.js:145:19

The solution is a clone of "Wix Events and eCommerce Next.js starter" (https://vercel.com/templates/next.js/wix-commerce-ticketing).

I am not sure what I am doing wrong if I am honest. As I said, it runs in dev on my machine.

Any pointers would be greatly appreciated.

### Expected Behavior

The home page should load without error

### To Reproduce

go to the home page: https://wix-events.vercel.app/

**Comment by balazsorban44** [comment]
It looks like the SDK is swallowing the error at line 353 here, which is a bit unfortunate: https://unpkg.com/browse/@wix/sdk@1.7.6/build/auth/oauth2/OAuthStrategy.js

You could try contacting Wix to gather more info. One guess, make sure that this variable is correctly set: https://github.com/wix/wix-commerce-ticketing-nextjs-template/blob/fb66a225cc7fc0271adb5029f3530f3b479e928b/.env.template#L2

This doesn't look like a Next.js-related issue though, so closing.
