### ISSUE TITLE
Docs: Fix Typo

### ISSUE THREAD

**Issue by cin4ed** [vercel/next.js#61540]
### What is the improvement or update you wish to see?

Misspelled word "Futhermore" instead of "Furthermore".

### Is there any context that might help us understand?

Found in the following paragraph:

"**Futhermore**, in production, whenever [<Link>](https://nextjs.org/docs/api-reference/next/link) components appear in the browser's viewport, Next.js automatically prefetches the code for the linked route in the background. By the time the user clicks the link, the code for the destination page will already be loaded in the background, and this is what makes the page transition near-instant!"

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/navigating-between-pages

**Comment by samcx** [comment]
Pushing up a fix for this!
