### ISSUE TITLE
[Next.js HMR not working] the server reloads but nothing changes in the browser (turbopack & turborepo)

### ISSUE THREAD

**Issue by regisrex** [vercel/next.js#61556]
### Link to the code that reproduces this issue

https://github.com/vercel/turbo/tree/main/examples/with-tailwind

### To Reproduce

It's the normal flow of setting up the default turborepo project.
1. clone the repo
2. run `pnpm install`
3. run `turbo dev`
4. try to modify something in `apps/web/src/app/page.tsx`
The server reloads but the browser hmr socket does not work

### Current vs. Expected behavior

I expected to preview the changes in the browser that was made in step(4) without reloading the page fully ( using Ctrl+R)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I thought that the issues is caused by the turbo but in their issues page, I rode somewhere that it is not their problem

**Comment by ForsakenHarmony** [comment]
Can't reproduce, though I did have to update `turbo` to `1.12.2` so the ui package would compile the CSS properly.

**Comment by regisrex** [comment]
Check this repro: https://github.com/regisrex/next-14-issues-repro2
