### ISSUE TITLE
next/image loading issue (what happened to #58248)

### ISSUE THREAD

**Issue by iuliancmarcu** [vercel/next.js#61566]
### Link to the code that reproduces this issue

https://github.com/iuliancmarcu/nextjs-local-image-issue-repro

### To Reproduce

set up this repository that has the minimal setup for reproducing this issue:

[https://github.com/iuliancmarcu/nextjs-local-image-issue-repro](https://web.archive.org/web/20240121233857/https://github.com/iuliancmarcu/nextjs-local-image-issue-repro)

Instructions:

- clone project
- run create_cert_and_add_hostname.sh - this will self-sign a certificate, add it to the keychain, and add a local.mycorp.app entry in /etc/hosts
- run npm install && node server.js
- open https://local.mycorp.app:3000 in your browser and see the image not loading

Please let me know if you need any more info 😁

### Current vs. Expected behavior

Current:
Workaround is needed for custom servers to handle the internal paths.

Expected:
Everything works out the box.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 20.5.1
  npm: 9.8.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image optimization (next/image, next/legacy/image)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

### Additional context

There was already an issue open for this (#58248 - https://web.archive.org/web/20240121233857/https://github.com/vercel/next.js/issues/58248) but it seems to have been deleted?

**Comment by temrb** [comment]
I'm also facing similar issue; 

https://github.com/vercel/next.js/discussions/61926

**Comment by iuliancmarcu** [comment]
Hey @samcx, I remember you had a look on this issue before, asking for a repo with a full reproduction. Do you have any news regarding this issue and whether there is any fix being prepared for it?

The loader mitigation works for simple scenarios, but I have thousands of usages of `next/image` in the app, some with static image urls, others with dynamic.

**Comment by samcx** [comment]
@iuliancmarcu Not sure how the issue got deleted, but we reported it to GitHub to investigate.

Thanks for flagging me again! I will try to take look 🔜

**Comment by temrb** [comment]
@iuliancmarcu you're right-- it has become a hassle to have a loader for many image components i have. Image works fine if just use `<img ... />`... i don't know if this is new feature of next/image or bug or something

**Comment by iuliancmarcu** [comment]
@samcx yes, the issue only happens when you have a custom server - we need that to use a custom domain on local to avoid some CORS issues, but also to have a HTTPS server with our certs in production

**Comment by styfle** [comment]
The original issue was deleted by the author.

This issue was fixed in PR https://github.com/vercel/next.js/pull/61471

I confirmed with the following:

```
git clone https://github.com/iuliancmarcu/nextjs-local-image-issue-repro
cd nextjs-local-image-issue-repro
bash create_cert_and_add_hostname.sh
npm install next@latest
npm run build
node server.js
```
