### ISSUE TITLE
Docs: Make it clear that NEXT_PUBLIC_ variables cannot be modified at runtime

### ISSUE THREAD

**Issue by dsosborn** [vercel/next.js#61580]
### What is the improvement or update you wish to see?

The way the docs are worded, they make it sound like if you use a NEXT_PUBLIC_* variable in a server action with noStore() that it will change at runtime.  This is not the case—if you want to use runtime env variables, but must NOT be prefixed with NEXT_PUBLIC_.

Additionally I would love to see more examples of how to use runtime variables in a docker image, where you build once and use different runtime env variables in different environments.

### Is there any context that might help us understand?

I'm using Next with Sanity preview-kit in a docker image across multiple environments. I was looking for a solution to build my image once and use it in different environments with different runtime env values that would pull content from different datasets. The confusion from the docs set me back a bit in troubleshooting, as I had tested using runtime variables (with a non-public variable) and was operating under the assumption I had a working solution.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#runtime-environment-variables

**Comment by balazsorban44** [comment]
This should be covered already here:

https://nextjs.org/docs/app/building-your-application/configuring/environment-variables#runtime-environment-variables:~:text=if%20you%20build,at%20build%20time

And here:
https://nextjs.org/docs/app/building-your-application/deploying#environment-variables:~:text=To%20read%20runtime,with%20different%20values.

**Comment by dsosborn** [comment]
Yes those things exist elsewhere in the docs, but in the section about _Runtime Environment Variables_ it really misses the opportunity to plainly state that NEXT_PUBLIC_ environment variables cannot be modified at runtime. It states "With the App Router, we can safely read environment variables on the server during dynamic rendering." without specifying that this doesn't apply to NEXT_PUBLIC_* variables. The note from your first link would be an excellent point to make in _this_ section. 

Furthermore, this whole runtime section should be rewritten. It's an App-router-specific section that refers to incrementally adopting the App router. Seems like it's copy and pasted from old Pages router docs.
