### ISSUE TITLE
Docs: beforeInteractive docs say to use app.layout, but the code example shows Document

### ISSUE THREAD

**Issue by kyjoconn** [vercel/next.js#61594]
### What is the improvement or update you wish to see?

Please clarify where beforeInteractive scripts should live when using the pages router.

This paragraph says to use app.layout, but the code example shows Document

<img width="950" alt="image" src="https://github.com/vercel/next.js/assets/58443406/877c5f50-9384-4ddf-ac49-640c5f3f3098">

### Is there any context that might help us understand?

It's unclear where to put beforeInteractive scripts when using the pages router

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/components/script#beforeinteractive

**Comment by kyjoconn** [comment]
Hey @samcx the update makes it clear that the code should be placed in `pages/_app.js`

but the code sample still shows _document.js not _app.js?

**Comment by samcx** [comment]
@kyjoconn My bad! Let me push up a new change.

**Comment by samcx** [comment]
@kyjoconn Yeah it should be `_document.js` — my bad for that!
