### ISSUE TITLE
Turbo: `tailwind.config.ts` + `turbo`, not working when updating tailwind config

### ISSUE THREAD

**Issue by tszhong0411** [vercel/next.js#61607]
### Link to the code that reproduces this issue

https://github.com/tszhong0411/nextjs-debug/tree/tailwind-ts-bug

### To Reproduce

1. Open [codesandbox](https://codesandbox.io/p/github/tszhong0411/nextjs-debug/tailwind-ts-bug)
2. Change the color of special class in `tailwind.config.ts`
3. The nextjs app doesn't reload

### Current vs. Expected behavior

Current:
The app doesn't reload after updating the tailwind configuration.

Expected:
The app will reload after updating the tailwind configuration.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.15.1
Relevant Packages:
  next: 14.1.1-canary.27 // Latest available version is detected (14.1.1-canary.27).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The situations for updating:

- `tailwind.config.js` without turbo: ✅
- `tailwind.config.ts` without turbo: ✅
- `tailwind.config.js` with turbo: ✅
-  `tailwind.config.ts` with turbo: ❌

<sub>[PACK-2393](https://linear.app/vercel/issue/PACK-2393/turbo-tailwindconfigts-turbo-not-working-when-updating-tailwind-config)</sub>

**Comment by ForsakenHarmony** [comment]
Will be fixed in the next canary after #61682 is merged.
