### ISSUE TITLE
Cookies in POST response from server action + redirect() are overridden by streamed GET response cookies

### ISSUE THREAD

**Issue by technikhil314** [vercel/next.js#61611]
### Link to the code that reproduces this issue

https://github.com/technikhil314/nextjs-parallel-routes-sample/tree/chore/steaming-cookie-issue?expand=1

### To Reproduce

1. Clone the repo `git clone -b chore/steaming-cookie-issue git@github.com:technikhil314/nextjs-parallel-routes-sample.git`
2. run `npm ci`
3. run `npm run dev`
4. open `http://localhost:3000`
5. click on `Redirect me to /route1` button
6. Observe that on redirection [the cookie set in server action](https://github.com/technikhil314/nextjs-parallel-routes-sample/blob/chore/steaming-cookie-issue/src/app/page.tsx#L6) does not get dropped on browser

### Current vs. Expected behavior

*Expected Result*
After sucessful redirection with streaming both cookies should be dropped on browser

*Actual Result*
Only one of the cookie gets dropped on browser (more explanation in demo example)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.10
  pnpm: 7.17.0
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Other (Deployed)

### Additional context

This is possible only in custom server setup based on top of self created express app and/or as per nextjs docs as well

**Comment by technikhil314** [comment]
I am already in process to raise PR. Hopefully PR gets merged in time.

**Comment by devraj** [comment]
@technikhil314 do you know if this is local to `14.1.0` or is this something that affects `14.0.x` as well?

**Comment by technikhil314** [comment]
@devraj I believe its happening in 14.0.0 as well
https://github.com/vercel/next.js/blob/v14.0.0/packages/next/src/server/app-render/action-handler.ts#L197

**Comment by devraj** [comment]
> @devraj I believe its happening in 14.0.0 as well https://github.com/vercel/next.js/blob/v14.0.0/packages/next/src/server/app-render/action-handler.ts#L197
> 

Thanks for pointing this out. I am pretty sure I am seeing the same behaviour having tried to downgrade.

> Again this is possible only if you have custom server. https://nextjs.org/docs/pages/building-your-application/configuring/custom-server
>

Interesting. I am seeing a similar behaviour running the `next` server on a `node-21` container in `aws-eks`, The cookie is set using in `redirect` as part of a `POST` request and reset if a `GET` request is fired or at times if a user navigates away and returns to the original page that set the cookie.

I'll keep investigating my particular instance and post any findings on this thread.

Appreciate you taking time to post your comments.

**Comment by technikhil314** [comment]
oh yeah that might be race condition there. Just so I understand the usecase you have. 
1. user goes to localhost:3000
1. does some action that triggers a call to server action
    - this server action then calls redirect of next/navigation
1. nextjs does its due delligence of internally calling the GET
1. and returns response to browser as if its a respone of POST server action
1. user then quickly naviates to some page while nextjs is streaming response for POST server action
1. during this navigation the cookies are lost and when user hits browser back button those are not found again
is that correct understanding? @devraj

**Comment by devraj** [comment]
> 6. during this navigation the cookies are lost and when user hits browser back button those are not found again
>    is that correct understanding? @devraj

That sounds like an appropriate description of my situation. Another scenario is if a `client` component renders (on say a user action) and that causes `nextjs` to revalidate the `get` request it overrides the cookies as well.

In my use case my cookie contains a `jwt` that an authentication api generated (used by server actions to exchange data with the backend api) and essentially renders the application in a deadlock where the client state does not match the server.

**Comment by technikhil314** [comment]
@devraj may be then the pr I have raised should fix your issue too. do you have any repo where you are able to reproduce this?

**Comment by devraj** [comment]
> @devraj may be then the pr I have raised should fix your issue too. do you have any repo where you are able to reproduce this?

Thanks for the PR, our app is a little complicated as it was consuming an external API. I will try and put some time together and extract the code in a demo repository for reference.

I'll post an update here as soon as I have something.
