### ISSUE TITLE
run npm start and npm run dev at the same time

### ISSUE THREAD

**Issue by valtido** [vercel/next.js#61612]
Original issue is now closed so I have created this, to bring attention to issue #2685 (see link below)
Using next.config.js you can achieve the same effect using the following 

```js
/** @type {import('next').NextConfig} */
module.exports =
	(phase, { defaultConfig }) => {
		if (phase === PHASE_DEVELOPMENT_SERVER) {
			return {
				/* development only config options here */
				distDir: '.next.development',
				reactStrictMode: true,
			};
		}

		return {
                         /* production only config options here */
			distDir: '.next',
			reactStrictMode: true,
		};
	}
```
Then you will need to use a `PORT=9000 next dev` on dev so it runs on a different port to the default so they don't clash.

Original issue.
             Unfortunately, that's not supported.

_Originally posted by @arunoda in https://github.com/vercel/next.js/issues/2685#issuecomment-318967762_

**Comment by ztanner** [comment]
Feel free to share this knowledge if you see anyone asking about it! I'm going to close this as issues are meant for bug reports.
