### ISSUE TITLE
bug?: new `MiddlewareConfig` type doesn't match runtime behavior and docs

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#61705]
> Is this type correct? It doesn't match the docs where we can have a `matcher: string` attribute: https://nextjs.org/docs/app/building-your-application/routing/middleware#example

![CleanShot 2024-02-06 at 09 10 37@2x](https://github.com/vercel/next.js/assets/51714798/4528fcbf-7ac4-43ae-bf59-260f69b8efd7)

_Originally posted by @juliusmarminge in https://github.com/vercel/next.js/issues/61576#issuecomment-1928501424_
            

<sub>[NEXT-2375](https://linear.app/vercel/issue/NEXT-2375/bug-new-middlewareconfig-type-doesnt-match-runtime-behavior-and-docs)</sub>

**Comment by juliusmarminge** [comment]
Reproduction repo if needed: https://github.com/juliusmarminge/next-auth-type-mismatch

**Comment by apostolos** [comment]
This is still not fixed.

<img width="1043" alt="image" src="https://github.com/vercel/next.js/assets/41679/ef89a11d-ebef-4cb9-b8b3-42d831b34ee6">

The interface `MiddlewareMatcher` has `regexp` and `originalSource` whereas the runtime expects `source`.

Following the types results in Next.js dying with the following error message:

```source` is missing, invalid fields: originalSource,regexp for route {"originalSource":"/:path*","regexp":"/((?!api|_next/static|_next/image|favicon.ico).*)","missing":[{"type":"header","key":"next-router-prefetch"},{"type":"header","key":"purpose","value":"prefetch"}]}```
