### ISSUE TITLE
Routing from a param page to a child page while changing the current param case (same string different case) crashes

### ISSUE THREAD

**Issue by axpro** [vercel/next.js#61722]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/vigilant-river-y8rs8r?file=%2Fapp%2F%5BparamA%5D%2Fpage.js%3A9%2C48&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsagjayy0006396hrym868ke%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsagjayy0002396h9vms2eu0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsagjayy0004396ho5vh4r7s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsagjayy0005396htb4wv336%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B57.24198755283389%252C42.75801244716611%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsagjayy0002396h9vms2eu0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsagjayx0001396h2am7fv6i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsah2dng0002396glgt8qoq2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A48%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A48%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252F%255BparamA%255D%252Fpage.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsagjayy0002396h9vms2eu0%2522%252C%2522activeTabId%2522%253A%2522clsah2dng0002396glgt8qoq2%2522%257D%252C%2522clsagjayy0005396htb4wv336%2522%253A%257B%2522id%2522%253A%2522clsagjayy0005396htb4wv336%2522%252C%2522activeTabId%2522%253A%2522clsagmhj100lt396hi4r1ehlw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clsagmhj100lt396hi4r1ehlw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clsagjayy0004396ho5vh4r7s%2522%253A%257B%2522id%2522%253A%2522clsagjayy0004396ho5vh4r7s%2522%252C%2522activeTabId%2522%253A%2522clsagmb6k00jm396hkprjfloi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clsagmb6k00jm396hkprjfloi%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### To Reproduce

1. start the app
2. open dev tools
3. click on "/ParamA" link
4. click on "/paramA/paramB" link
5. see dev tools network requests and wait for error to appear

### Current vs. Expected behavior

The app should route to the new param page

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.36 // Latest available version is detected (14.1.1-canary.36).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[NEXT-2377](https://linear.app/vercel/issue/NEXT-2377/routing-from-a-param-page-to-a-child-page-while-changing-the-current)</sub>

**Comment by ztanner** [comment]
Great reproduction -- thank you for reporting. I will have a PR to fix shortly.

**Comment by sndalama-data443** [comment]
@ztanner Noticed affected areas only list the App Router. However, i am experiencing this bug with the Pages Router aswell.
