### ISSUE TITLE
Docs: Switch to a recommendation of an ESM Next Config file

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [vercel/next.js#61720]
### What is the improvement or update you wish to see?

I would love to see Next.js no longer recommend a CJS Config file

### Is there any context that might help us understand?

Many projects like serwist: https://github.com/serwist/serwist/discussions/66 require an ESM config file or are already set up with a CJS Config file like T3: https://github.com/t3-oss/create-t3-app.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/next-config-js

<sub>[DX-2354](https://linear.app/vercel/issue/DX-2354/docs-switch-to-a-recommendation-of-an-esm-next-config-file)</sub>

**Comment by balazsorban44** [comment]
I think this makes sense, given that our CLI tool also generates `.mjs` now. https://github.com/vercel/next.js/pull/60494

**Comment by leerob** [comment]
I am okay with the current state of the documentation that recommends both equally. I do not want to start a CJS / ESM debate 😄
