### ISSUE TITLE
Error export next/font localFont() instance as a constant

### ISSUE THREAD

**Issue by cody-ta** [vercel/next.js#61764]
### Link to the code that reproduces this issue

https://github.com/cody-ta/font-instance-export-error

### To Reproduce

Run next build or npm run build to see the build error.

### Current vs. Expected behavior

Should build successfully.

vs.

![CleanShot 2024-02-07 at 17 44 59@2x](https://github.com/vercel/next.js/assets/8092790/025a0b9d-379d-4997-bcc4-699045612da4)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.14.3
Relevant Packages:
  next: 14.1.1-canary.42 // Latest available version is detected (14.1.1-canary.42).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Font optimization (next/font)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

As mentioned in the doc: [nextjs.org/docs/app/building-your-application/optimizing/fonts#reusing-fonts](https://nextjs.org/docs/app/building-your-application/optimizing/fonts#reusing-fonts). It is recommended to:

> Export it as a constant.

I need to be able to access font.style.fontFamily in case of using `react-map-gl` (mapbox-gl).
```ts
import { inter } from "@/app/layout";

import "mapbox-gl/dist/mapbox-gl.css";
import React from "react";
import Map from "react-map-gl";

export default ({ children }: { children: React.ReactNode }) => {
  return (
    <Map
      id="map"
      mapStyle={process.env.NEXT_PUBLIC_MAPBOX_STYLE_URL}
      mapboxAccessToken={process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
      localFontFamily={inter.style.fontFamily}
      ...
    />
  );
};
```

**Comment by lorenzorzd** [comment]
I had a similar problem when following Shadcn docs. 

Solved the problem by declaring the font as a const but not exporting it.

```
import { Inter as FontSans } from "next/font/google" 

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html>
            <body  className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme='dark'
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}


```
