### ISSUE TITLE
Version 14.1.0 prefetch={true} preload css doesn't working

### ISSUE THREAD

**Issue by repcolding** [vercel/next.js#61816]
I checked the version ```next@14.1.0``` and ```14.0.3-canary.7```. Specifying prefetch={true}. And the result is terrible:

```next@14.1.0```: No preloading of css
```next@14.0.3-canary.7```: css is preloaded

```ts
const Folder: FC<IFolder> = ({ children, label, className, href = '#' }) => {
  return (
    <Link
      prefetch={true} // next@14.1.0 and next@14.0.3-canary.7
      scroll={false}
      href={href}
      className={cn(styles.folder, className)}
    >
      {children}

      <div className={styles.label}>{label}</div>
    </Link>
  )
}
```

### ```next@14.0.3-canary.7```

![next@14.0.3-canary.7](https://github.com/vercel/next.js/assets/120719830/70258baf-df08-4c59-b5a9-f5439c686d21)

```prefetch={true}``` preload css is working

---

### ```next@14.1.0```

![next@14.1.0](https://github.com/vercel/next.js/assets/120719830/f8a10871-df72-4fc5-b513-51424e887017)

```prefetch={true}``` preload css doesn't working

_Originally posted by @repcolding in https://github.com/vercel/next.js/issues/61259#issuecomment-1933614004_

**Comment by arestov-work** [comment]
I have the same shit, please decide faster

**Comment by Henryyy-Hung** [comment]
I have encountered the same bug, which causing the html content displayed before css has been loaded.
