### ISSUE TITLE
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function. Next v14.1.0 with @headlessui/react v1.7.18

### ISSUE THREAD

**Issue by ryota-murakami** [vercel/next.js#61834]
### Link to the code that reproduces this issue

https://github.com/ryota-murakami/next-headlessui-popover-import-error

### To Reproduce

1. `pnpm dev` -> open localhost:3000
2. you'll hit the error

### Current vs. Expected behavior

# Current
Not working `@headlessui/react` `<Popover />` component with `TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function.`  error.

# Expected
Working without error.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.15.1
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

- app code

```tsx
import { Popover } from '@headlessui/react'
export default function Home() {
  return (
    <Popover className="relative">
      <Popover.Button>Solutions</Popover.Button>

      <Popover.Panel className="absolute z-10">
        <div className="grid grid-cols-2">
          <a href="/analytics">Analytics</a>
          <a href="/engagement">Engagement</a>
          <a href="/security">Security</a>
          <a href="/integrations">Integrations</a>
        </div>


      </Popover.Panel>
    </Popover>)
}

```

- error trace
```
~/r/next-headlessui-popover-import-error (main|✚2) $ pnpm dev

> @ dev /Users/ryota.murakami/repository/next-headlessui-popover-import-error
> next dev

   ▲ Next.js 14.1.1-canary.44
   - Local:        http://localhost:3000

 ✓ Ready in 2.2s
 ○ Compiling /not-found ...
 ✓ Compiled /not-found in 2.3s (418 modules)
 ○ Compiling / ...
 ✓ Compiled / in 552ms (452 modules)
 ⨯ node_modules/.pnpm/@headlessui+react@1.7.18_react-dom@18.2.0_react@18.2.0/node_modules/@headlessui/react/dist/internal/portal-force-root.js (1:66) @ eval
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/Users/ryota.murakami/repository/next-headlessui-popover-import-error/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/ryota.murakami/repository/next-headlessui-popover-import-error/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__ (/Users/ryota.murakami/repository/next-headlessui-popover-import-error/.next/server/webpack-runtime.js:33:42)
    at eval (./app/page.tsx:7:105)
    at (rsc)/./app/page.tsx (/Users/ryota.murakami/repository/next-headlessui-popover-import-error/.next/server/app/page.js:141:1)
    at Function.__webpack_require__ (/Users/ryota.murakami/repository/next-headlessui-popover-import-error/.next/server/webpack-runtime.js:33:42)
    at async Promise.all (index 0)
digest: "2386039412"
null

```

**Comment by Durgaprasad-Budhwani** [comment]
The `Popover` component from `@headlessui/react` decided it's only going to perform its magic when it's on the `client-side`, not so much a fan of the `server-side` rendering scene.

To untangle this web, the solution's pretty straightforward: sprinkle a little "use client" magic at the very start of your file. It's like whispering to the code.

------
"Let's make the digital world smaller! Connect with me across the web on these social platforms and let's create, share, and inspire together." ✨🌐 #StayConnected

[![LinkedIn](https://img.icons8.com/color/48/000000/linkedin.png)](https://www.linkedin.com/in/durgaprasad-budhwani/) [![Twitter](https://img.icons8.com/color/48/000000/twitter.png)](https://twitter.com/DurgaprasadDP)

#### Solved 07

**Comment by ryota-murakami** [comment]
@Durgaprasad-Budhwani Thanks! It works!
