### ISSUE TITLE
Docs: Sub bullet point rendering incorrectly as numbered list

### ISSUE THREAD

**Issue by Luceium** [vercel/next.js#61838]
### What is the improvement or update you wish to see?

In the authentication docs, there is a numbered list where each item should have bullet points underneath. Oddly, it's rendered as more numbers in the list but, shaded to be darker.
![image](https://github.com/vercel/next.js/assets/79354255/5494b277-f1cd-4d84-910d-16447a1339d9)

I found the code responsible at https://github.com/vercel/next.js/edit/canary/docs/02-app/01-building-your-application/09-authentication/index.mdx on lines 335 - 343.
I rendered the associated text on my end and it appears to be fine:
ex.
1. topic 1
    - sub point
3. topic 2

A solution could be adding one more space to each bullet point to bring the space count from 3 to 4 which helps with github's markdown.

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/authentication

**Comment by SaiGanesh21** [comment]
Hi @Luceium. In the PR that I have raised it says that my branch is out of date with canary. In order to pull the latest changes to my branch should I run `git merge canary` or `git pull origin canary  --no-rebase` ?
