### ISSUE TITLE
In web worker, typeof window === 'undefined' is falsely bundled to `true`

### ISSUE THREAD

**Issue by yf-yang** [vercel/next.js#61858]
### Link to the code that reproduces this issue

https://github.com/yf-yang/next-webworker-bug

### To Reproduce

1. pnpm i
2. pnpm dev
3. open the window, click the button

### Current vs. Expected behavior

Expected:
Web worker started, then debugjs can log a message "worker started" (console log level should be "verbose")
Current:
Error: Uncaught ReferenceError: window is not defined

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.14.3
Relevant Packages:
  next: 14.1.1-canary.45 // Latest available version is detected (14.1.1-canary.45).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

The error is this line in `debug.js`:
https://github.com/debug-js/debug/blob/f66cb2d9f729e1a592e72d3698e3b75329d75a25/src/browser.js#L119-L121
``` javascript
if (typeof window !== 'undefined' && window.process ...) {
  ...
}
```
In the bundled output file `.next/static/chunks/_app-pages-browser_app_worker_js.js`, this line is transpiled to
``` javascript
if (true && window.process ...) {
  ...
}
```
The bundled output is wrong, because in web worker, `window` does not exist.

NOTE: This bug does not exist in next@13.5.6
> Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.14.3
Relevant Packages:
  next: 13.5.6
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A

<sub>[NEXT-2418](https://linear.app/vercel/issue/NEXT-2418/in-web-worker-typeof-window-===-undefined-is-falsely-bundled-to-true)</sub>

**Comment by yf-yang** [comment]
@kdy1 Is it a swc issue?

**Comment by kdy1** [comment]
No, it's not

**Comment by kdy1** [comment]
And this is duplicate

**Comment by yf-yang** [comment]
Ah, sorry for that.

https://github.com/vercel/next.js/issues/60644 (I think the issue may be incorrect because window should be undefined in web worker)

**Comment by yf-yang** [comment]
Also duplicates https://github.com/vercel/next.js/issues/61740
The same behavior: 14.0.5-canary.19 is OK, 14.0.5-canary.20 is broken.

I think both https://github.com/vercel/next.js/issues/60644 and https://github.com/vercel/next.js/issues/61740 does not address the issue correctly. `window` should be `undefined`, but `typeof window === 'undefined'` should be false in a web worker context. (Or, does webpack create a window variable for workers?)

**Comment by yf-yang** [comment]
@huozhi Is it related to #59569?

**Comment by yf-yang** [comment]
I highly suspect #59569 is the root cause. `isAppBrowserLayer` does not imply this is the browser, it could be the web worker, where `window` object is not available. If I got it right, swc-loader is not configured correctly due to the problem.

See also: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#web_workers_api
The first paragraph.

**Comment by hiromaily** [comment]
I'm using web worker and loaded worker code depends on dependencies which check window objejct.
It used to be working without any problems at Next.js version 14.0.4 or older. However it failed after upgrading next.js to 14.1.0. This error occurs both production and dev.
```
minimal.js:28 Uncaught ReferenceError: window is not defined
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/protobufjs/src/util/minimal.js:28:68)
```

**Comment by yf-yang** [comment]
Thanks and happy new year :)
