### ISSUE TITLE
Modal Opened with Parallel Route Remains Visible After Navigation in Next.js 14

### ISSUE THREAD

**Issue by RexGalicie** [vercel/next.js#61991]
### Link to the code that reproduces this issue

https://github.com/RexGalicie/paralel-route-test

### To Reproduce

- Clone the provided repository (Note: you would include the link to your repository here).
- Run next dev to start the development server.
- Navigate to a page that opens another page in a modal using the parallel route feature.
- From the modal, navigate to a test page by clicking on a link or button designed for this purpose.

https://github.com/vercel/next.js/assets/6573958/8868c3b8-6be6-4f46-aec0-b97730366347

Observe that the navigation to the test page occurs, but the modal remains open, overlaying the content of the test page.

### Current vs. Expected behavior

The modal remains open and visible on the screen even after successfully navigating to a normal page, overlaying the content of the newly navigated page.

The modal should automatically close or provide a mechanism to be closed programmatically when navigating away from the modal route to a normal page route.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.12.1
Relevant Packages:
  next: 14.1.1-canary.51 // Latest available version is detected (14.1.1-canary.51).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by xvvvyz** [comment]
You need to add a catch-all route as described here:

https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#closing-the-modal

However, there is this bug with Turbopack:

https://github.com/vercel/next.js/issues/59502

So add the catch-all route and remove the --turbo flag and it should work in theory...

**Comment by ztanner** [comment]
Yeah, what @xvvvyz has said is correct! Using a catch-all is how you'd get the parallel route to disappear when navigating to a route that doesn't have a matched slot.

Just wanted to add that we're working on bringing catch-all support to Turbopack as well. Going to close this issue out but you can track progress of that in the issue linked above. Thank you!
