### ISSUE TITLE
`flex: 1 1 0` compiled to `flex: 1 1`

### ISSUE THREAD

**Issue by benmerckx** [vercel/next.js#62002]
### Link to the code that reproduces this issue

https://github.com/benmerckx/next-flex-bug

### To Reproduce

Check compiled css

### Current vs. Expected behavior

The `flex-basis` value is omitted. But the browser default of 0% is not the same as the absolute 0 value.

Input css: `flex: 1 1 0;`
Compiled css: `flex: 1 1;`
Expected css: `flex: 1 1 0;`

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: Ubuntu 20.04.0 LTS Tue Feb 13 2024 17:05:09 GMT+0100 (Central European Standard Time)
Binaries:
  Node: 18.18.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.14.0
Relevant Packages:
  next: 14.1.1-canary.51 // Latest available version is detected (14.1.1-canary.51).
  eslint-config-next: 13.5.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

**Comment by icyJoseph** [comment]
Hi,

This is done by PostCSS, it is called flexbug-4. 

There's an already opened issue over there: https://github.com/luisrudge/postcss-flexbugs-fixes/issues/59 

Their recommended workaround is to use units, particularly %:

- https://github.com/philipwalton/flexbugs?tab=readme-ov-file#flexbug-4

Or you could disable it if you like...

The configuration used by Next.js is roughly:

```json
{
  "plugins": [
    "postcss-flexbugs-fixes",
    [
      "postcss-preset-env",
      {
        "autoprefixer": {
          "flexbox": "no-2009",
          "grid": "autoplace"
        },
        "stage": 3,
        "features": {
          "custom-properties": false
        }
      }
    ]
  ]
}
```

Taken from:

- https://nextjs.org/docs/pages/building-your-application/configuring/post-css#default-behavior
- https://github.com/vercel/next.js/blob/4e03b85cee2cb7119f4766abb71fc930f825acc8/packages/next/src/build/webpack/config/blocks/css/plugins.ts#L89

And there you could disable the bug4 fix with:

In `postcss.config.json`:

```json
{
  "plugins": [
    ["postcss-flexbugs-fixes", { "bug4" : false }],
    [
      "postcss-preset-env",
      {
        "autoprefixer": {
          "flexbox": "no-2009",
          "grid": "autoplace"
        },
        "stage": 3,
        "features": {
          "custom-properties": false
        }
      }
    ]
  ]
}
```

You'd need to install `postcss-preset-env` and `postcss-flexbugs-fixes` though.

Here it is in action:

- https://stackblitz.com/edit/github-bzlm5z?file=postcss.config.json,app%2Fpage.css

Run `npx next build` and `cat .next/static/css/<some-hash-name>.css` and you'll see it:

<img width="887" alt="Screenshot 2024-02-13 at 17 46 58" src="https://github.com/vercel/next.js/assets/21013447/55351b90-fbdb-456a-8036-4355fec21420">

**Comment by benmerckx** [comment]
Thanks for the detailed answer, I guess there's nothing actionable for Next.js here.
