### ISSUE TITLE
next/image or img cannot read static images in production

### ISSUE THREAD

**Issue by hrithiqball** [vercel/next.js#62027]
### Link to the code that reproduces this issue

https://github.com/hrithiqball/e-jobpack/tree/50-upload-image

### To Reproduce

1. copy .env.example and wite DATABASE_URL to local db, NEXTAUTH_URL=http://localhost:3000, random string for secret and resend api key
2. npx prisma db push
3. npx prisma db seed
4. npx next build

directory of web
1. npx next dev
2. go to asset tab top screen 
3. click the name of the asset (add asset if it is empty) and upload the image on left side

### Current vs. Expected behavior

I built an uploader function that can upload image to the server and saved in public/image/[assetId]/fileName. 
![image](https://github.com/vercel/next.js/assets/87375380/19373f15-62de-4ec5-9701-13384be33f48)

The image is saved and can be displayed during `next dev` however on `next start`, it reads the images as string and rendered alt as it is not a valid image but text. however it works fine and i can display the image immediately an can read the image.

`next start` behaviour
![start env](https://github.com/vercel/next.js/assets/87375380/eca25fc0-b5fd-4a48-8ea1-4fb18df29f06)

`next dev` behaviour
![dev env](https://github.com/vercel/next.js/assets/87375380/571351f1-9965-4f7e-8bce-23ec19640a93)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

App Router, Image optimization (next/image, next/legacy/image), Middleware / Edge (API routes, runtime)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

I tested the <img /> and it still doesnt work. it will work however, if i rebuild it using `npx next build`. the image will load happily, but if add new image, it does not read. i am suspecting that the image is not built as static image during runtime

**Comment by hrithiqball** [comment]
After testing out some test to see if image can be load on server, i tried manually place the image. Is there any workaround or missing configs that makes the server not load the image?

`next start` behaviour
![manual place](https://github.com/vercel/next.js/assets/87375380/26ecf608-e1ca-425c-a4c7-c13b66edcbcf)

`next dev` behaviour
![works](https://github.com/vercel/next.js/assets/87375380/f2d687af-5bd3-40e0-b214-9b4c0a23b41d)

**Comment by ztanner** [comment]
Hi, thanks for the report. As described in our [Static Assets](https://nextjs.org/docs/app/building-your-application/optimizing/static-assets) docs, only files stored in the `public` directory at build time will be served by Next.js. Files added at request time won't be available. We recommend using a service like [Vercel Blob](https://vercel.com/docs/storage/vercel-blob) or AWS S3 for persistent file storage.
