### ISSUE TITLE
Async/Await Not Supported in Client Components Despite Documentation Claims

### ISSUE THREAD

**Issue by Kayeddy** [vercel/next.js#62030]
### Link to the code that reproduces this issue

https://github.com/Kayeddy/threadsClone-Web

### To Reproduce

1. Clone the linked repository.
2. Open the repo in vs code and run 'npm i' to install necessary dependencies.
3. After installing necessary dependencies run 'npm run dev', which will start up the application on the default localhost:300 server
4. Head to the website and sign in (No user data is collected on registration).
5. On the root page (Home) try to click the like button of any Thread.
6. The error will pop up as soon as you hit the like button.

### Current vs. Expected behavior

**Current Behavior:** When trying to like a post by invoking the handleThreadLike async function—which calls a server action function—and attempting to update the component to reflect the latest changes using React's useState hook within a client component in Next.js, the application throws an error indicating that async/await is not supported in client components.

**Expected Behavior:** According to the latest Next.js documentation, async/await should be supported in client components when using the app router directive. The expected behavior is for the handleThreadLike function to execute without errors, allowing for the asynchronous liking of a post.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
Binaries:
  Node: 21.2.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A


warn  - Latest canary version not detected, detected: "14.1.0", newest: "14.1.1-canary.52".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

* The issue occurs both in the development and production builds of the application.

* Deployment platform: The issue has been reproduced both locally and on Vercel.

* Browser: The issue has been observed in multiple browsers (Chrome, Opera, Firefox).

* The use of state was initially attempted but was commented out due to the same error. A useRef hook is currently being used as a workaround.

This issue seems to contradict the latest documentation regarding the app router and client components in Next.js, suggesting either a regression or a documentation oversight.

**Comment by icyJoseph** [comment]
Where it the documentation do they say that they support async/await in client components?

**Comment by Kayeddy** [comment]
> Where it the documentation do they say that they support async/await in client components?

Hello Joseph, thanks for taking the time to reply.
In regards to your question, I will leave the link to the specific section of the Docs that makes this assumption, and I will also leave a screenshot as to the example code within the Docs. 

Link: https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations

<img width="500" alt="Screenshot 2024-02-13 200537" src="https://github.com/vercel/next.js/assets/57167218/1eef7ebc-b9a9-4c81-b7e2-80f284c8ca72">

**Comment by icyJoseph** [comment]
Fixed/answered by https://github.com/vercel/next.js/discussions/62031#discussioncomment-8463011

**Comment by ztanner** [comment]
Thanks @icyJoseph! I'm going to close this as I believe the documentation linked above seems correct -- the component isn't using async/await, only the `onClick` callback is async. 

Client components (`"use client"`) cannot currently be made async, which is why you see an error about it. There's some more information on why this is the case in the [React RFC](https://github.com/acdlite/rfcs/blob/first-class-promises/text/0000-first-class-support-for-promises.md#why-cant-client-components-be-async-functions). Don't hesitate to open a PR with any docs improvements that you think would make this clearer! 🙏

**Comment by Kayeddy** [comment]
Many thanks to you both for your help, I appreciate it.

Kind regards.
