### ISSUE TITLE
Docs: incorrect (or old?) links used in Learn Pages Router

### ISSUE THREAD

**Issue by yamanidev** [vercel/next.js#62060]
### What is the improvement or update you wish to see?

Apologies if this is the wrong repository to open an issue in. I tried looking for the right one to issue a PR, but I was unable to find it.

At the end of the article, the URLs used for the links for _`paths` key documentation_ and _`fallback: false`_ are incorrect.
- _`paths` key documentation_  takes to [this](https://nextjs.org/docs/pages/building-your-application/data-fetching#the-paths-key-required)
Correct link: https://nextjs.org/docs/pages/api-reference/functions/get-static-paths#paths

- _`fallback: false`_ takes to [this](https://nextjs.org/docs/basic-features/data-fetching#fallback-false)
Correct link: https://nextjs.org/docs/pages/api-reference/functions/get-static-paths#fallback-false

Could you share the link to the repository of the tutorial? I have a couple of PRs to submit.

### Is there any context that might help us understand?

No.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn-pages-router/basics/dynamic-routes/implement-getstaticpaths

**Comment by icyJoseph** [comment]
Hi,

I think that material might not be open source. Though you can go to the next-learn repository and open an issue there. 

Link:

**Comment by yamanidev** [comment]
Thought so too... that's unfortunate.

Thank you :)

**Comment by samcx** [comment]
Pushing up a fix for this!

**Comment by yamanidev** [comment]
@samcx I noticed other mistakes in the same docs, where can I open an issue?

**Comment by samcx** [comment]
@yamanidev It's unfortunately private. Are you finding it all over the Learn Pages Router course?

**Comment by yamanidev** [comment]
@samcx correct. They might not be groundbreaking, but they're improvements still

**Comment by samcx** [comment]
@yamanidev Can you clarify which ones? A lot of these links are already covered via redirect, so not entirely sure which ones are breaking/not-redirecting to a correct one.

**Comment by yamanidev** [comment]
I might disappoint, but here they are haha.

Applying consistent capitalization would be nice here
![image](https://github.com/vercel/next.js/assets/65856786/ea0a4e83-c121-4108-bf50-d3d1a46c5874)

**Comment by yamanidev** [comment]
Consistent use of the package manager that the documentation started with (or list other options in all instances?): [link](https://nextjs.org/learn-pages-router/seo/crawling-and-indexing/robots-txt)
![image](https://github.com/vercel/next.js/assets/65856786/b6fea8c5-6b30-4474-a565-685d70859220)

**Comment by yamanidev** [comment]
Consistent use of _browser extensions_ (which is how most people refer to them) with the _Quick Review_ section where they were indeed called as _extensions_: [link](https://nextjs.org/learn-pages-router/seo/improve/lighthouse)
![image](https://github.com/vercel/next.js/assets/65856786/5db5fccf-93c0-4dce-a5c4-d29baa44d685)

**Comment by yamanidev** [comment]
Spacing between _and_ and _`height`_: [link](https://nextjs.org/learn-pages-router/seo/improve/dynamic-import-components)
![image](https://github.com/vercel/next.js/assets/65856786/da5ee09e-8a0d-418c-8b12-452f03098fbc)
