### ISSUE TITLE
`revalidatePath` with `type = "layout" | "page"` does not invalidate the data cache

### ISSUE THREAD

**Issue by juliesaia** [vercel/next.js#62071]
### Link to the code that reproduces this issue

https://github.com/juliesaia/revalidate-path-test

### To Reproduce

1. next dev
2. Click revalidate dynamic route (page) or (layout)
3. Wait 5 seconds, click revalidate dynamic route again
4. Click link to dynamic route, verify that server (rendered) time and fetched (external from API) are not in sync

### Current vs. Expected behavior

`revalidatePath("/dynamic/1", "layout")` should invalidate the cached result from `fetch`. Without this functionality, it's impossible to invalidate a subset of paths.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.54 // Latest available version is detected (14.1.1-canary.54).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

<sub>[NEXT-3302](https://linear.app/vercel/issue/NEXT-3302/revalidatepath-with-type-=-layout-or-page-does-not-invalidate-the-data)</sub>

**Comment by toonverbeek** [comment]
Can confirm this is happening for me as well, running 14.1.0. Trying to revalidate the root layout in my case does not trigger revalidation of sub paths.

**Comment by spiritanand** [comment]
`revalidatePath("/any-path "page");`

not working for me. I have to either manually refersh or use `router.refresh()`, which is not ideal since there will be no way for me to refetch the server component in case it is mutated by another server component (server actions)

**Comment by brandon-carlisle** [comment]
I faced a similar issue while using revalidatePath on a dynamic route and specifying "page" or "layout" as the type. When I omitted the second argument in revalidatePath, the cache was revalidated.

**Comment by vitor-antonio** [comment]
Same thing here on my side, using revalidatePath with `'page'` or `'layout'` doesn't trigger revalidation when navigating back to my dynamic path `/page-2`. Only started working when I've updated nextjs to version **14.2.3** and removed the second param for `revalidatePath`.

**Comment by ztanner** [comment]
Hi @juliesaia -- it looks like there might be some confusion from the docs around how the `type` argument is meant to be handled.

I've submitted a PR that attempts to clarify it. When you call `revalidatePath("/dynamic/1", "page")` or `revalidatePath("/dynamic/1", "layout")`, you're revalidating a cache tag that doesn't exist. 

For your dynamic segment, the possible cache tags are `/dynamic/[id]/layout` and `/dynamic/[id]/page`. If you only want to revalidate the fetch for the specific page, calling `revalidatePath("/dynamic/1")` (without `type`) is correct. If you want to revalidate the fetch cache for all of the dynamic routes, you'd call `revalidatePath("/dynamic/[id]", "page")`. And if you only wanted to revalidate the fetches in the layout, you'd call `revalidatePath("/dynamic/[id]", "layout")`.
