### ISSUE TITLE
Turbopack is incompatible with `sharp` when using `plaiceholder`

### ISSUE THREAD

**Issue by baszalmstra** [vercel/next.js#62088]
### Link to the code that reproduces this issue

https://github.com/baszalmstra/sharp-turbopack-issue

### To Reproduce

1. Use `plaiceholder` as indicated in the examples (see the reproducer)
2. Run `next dev --turbo`
3. Observe the error.

### Current vs. Expected behavior

I expected plaiceholder  and sharp to work properly, as it does when not using Turbopack.

Instead, an error is thrown:

```
Error: Could not load the "sharp" module using the win32-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=win32 --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    ```

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 21.6.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.54 // Latest available version is detected (14.1.1-canary.54).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Note that this is very similar to https://github.com/vercel/next.js/issues/60035 and that example does indeed work for me as well. It's when I introduce `plaiceholder` when things go south. 

This also happens for me on linux (WSL).

<sub>[PACK-2521](https://linear.app/vercel/issue/PACK-2521/turbopack-is-incompatible-with-sharp-when-using-plaiceholder)</sub>

**Comment by kdy1** [comment]
# Investigation

`sharp` uses their own logic for loading of the binding, and I think there's no nft logic for this pattern.

<img width="1840" alt="image" src="https://github.com/vercel/next.js/assets/29931815/28d82e90-b031-4fda-80ed-c4d0f254097a">

**Comment by jmikrut** [comment]
Hey @kdy1 — I am seeing this issue on canary still, even though the PR above was merged. Has the PR above made it into a canary version yet? 

I'm on `next@14.1.2-canary.5`
