### ISSUE TITLE
Bug with back navigation to async page

### ISSUE THREAD

**Issue by Ol1va** [vercel/next.js#62136]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/next-js-nav-bug-7k8zk6?file=%2Fapp%2Fpage.tsx

### To Reproduce

Go to https://codesandbox.io/p/devbox/next-js-nav-bug-7k8zk6?file=%2Fapp%2Fpage.tsx and there will be an instruction on how to reproduce this bug. PLEASE NOTE that to be able to reproduce this bug, you need to open page in separate browser tab.

### Current vs. Expected behavior

Current: on back navigation page is requested many times and eventually crushes.
Expected: page loads on back navigation.

### Provide environment information

```bash
Relevant Packages:
  next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), Other (Deployed)

### Additional context

I think I might have found a bug concerning navigating back to async page component.
I have two pages: the first one is an async component (Page A) and the second one is a plain component (Page B). When I navigate from Page B to Page A, the application crashes. Also, there's lots of requests in network to Page A.
For now I switched to version of Next 14.0.2, which doesn't have this bug.

**Comment by manaten** [comment]
I encountered the same issue on Next 14.1.0, but it seems to no longer reproduce after updating to the latest canary version.

**Comment by ztanner** [comment]
Hi - thank you for the report. I believe this has been fixed by #62383 and I can no longer reproduce it with your reproduction against the latest canary. Please let us know if you're still running into this issue after upgrading.

**Comment by Jee-on** [comment]
This problem make me crazy for a while. It seems like it has been resolved now. thank you

**Comment by Ol1va** [comment]
No more problems after upgrading to version 14.1.3!
