### ISSUE TITLE
`next dev --turbo` errors when rendering MDX files

### ISSUE THREAD

**Issue by staticshock** [vercel/next.js#62179]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/elastic-snyder-yck5dq

### To Reproduce

1. Run `npx create-next-app@latest next-demo`
2. Follow [Next.js instructions](https://nextjs.org/docs/app/building-your-application/configuring/mdx) for setting up MDX.
3. Run `next dev --turbo`
4. Navigate to MDX route in the browser.

### Current vs. Expected behavior

Here's the error I'm seeing when I navigate to an MDX page after the steps above:

![Screenshot 2024-02-16 at 9 25 57 PM](https://github.com/vercel/next.js/assets/13100/2a9cff43-b06c-4415-b7af-21fc521bd418)

`next dev` and `next build && next start` both work fine; only `next dev --turbo` is affected.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.15.1
Relevant Packages:
  next: 14.1.1-canary.58 // Latest available version is detected (14.1.1-canary.58).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

MDX (@next/mdx), Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by kdy1** [comment]
You shuold enable `experimental.mdxRs`.

```js

const withMDX = require('@next/mdx')()

/** @type {import("next").NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  pageExtensions: ['js', 'jsx', 'mdx', 'ts', 'tsx'],

  experimental: {
    mdxRs: true
  }
};

module.exports = withMDX(nextConfig)


```

works
