### ISSUE TITLE
React Fragments Not Working the Same Way In Server Components

### ISSUE THREAD

**Issue by richardmarquet** [vercel/next.js#62177]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/nextjs-shadcn-aschild-ssr-error-nlqvkm

### To Reproduce

The link here has the code that breaks

https://codesandbox.io/p/sandbox/nextjs-shadcn-aschild-ssr-error-nlqvkm

To be specific, right here:

      <TableBody>
        <Collapsible asChild>
          {/* This fragment does not work as expected in SSR */}
          <>
            <TableRow>
              <TableCell className="">
                <CollapsibleTrigger asChild>
                  <div>test</div>
                </CollapsibleTrigger>
              </TableCell>
            </TableRow>
            <CollapsibleContent asChild>
                <h1>stuff</h1>
            </CollapsibleContent>
          </>
          </Collapsible>
      </TableBody>

You can make it work by making the file where this appears a client component

### Current vs. Expected behavior

I _assume_ that a server component should respect the React Fragment as one component. Instead it does not and basically acts as if the fragment is not there at all. Client components do not have this issue.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.1-canary.58 // Latest available version is detected (14.1.1-canary.58).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This is my first time filing a bug so my apologies if any expected contexts are missing.

**Comment by coffeecupjapan** [comment]
@richardmarquet 
Hi. I investigate this issue and find that key-less fragment is not serialized as wrapper in React Server Component.

See Comments here 

https://github.com/facebook/react/blob/c1fd2a91b1042c137d750be85e5998f699a54d2a/packages/react-server/src/ReactFlightServer.js#L723-L724

Therefore, you can avoid error to be shown using fragment setting key like codes below.

```javascript
<React.Fragment key="somekey">
  <TableRow>
  ...
</React.Fragment>
```

I hope it would help.

**Comment by richardmarquet** [comment]
For some reason this won't fix my local environment, but this fix does work on CodeSandbox so it's probably something on my end. Thank you
