### ISSUE TITLE
Can't load local fonts if using a custom _document.tsx

### ISSUE THREAD

**Issue by jordanlambrecht** [vercel/next.js#62172]
### Link to the code that reproduces this issue

https://github.com/jordanlambrecht/nextjs-local-fonts-issue

### To Reproduce

1. Using Tailwind and Page Router, create an app that uses a custom app and a custom document
2. Create fonts.ts 
3. Add fonts to /public/fonts
4. Attempt to get Tailwind to recognize them.

```
// _app.tsx

import type { ReactElement, ReactNode } from 'react'
import type { NextPage } from 'next'
import type { AppProps } from 'next/app'
import '../styles/globals.css'

export default function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page)
  return <>{getLayout(<Component {...pageProps} />)}</>
}
```

```
// _document.tsx

import { Html, Head, Main, NextScript } from 'next/document'
const MyDocument = () => {
  return (
    <Html lang='en-US'>
      <Head></Head>
      <body className={`px-4 bg-egg max-w-screen overflow-x-hidden`}>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}

export default MyDocument
```

```
// tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontFamily: {
      gilroy: ['var(--font-gilroy)', 'sans-serif'],
    },

    extend: {
      //Tried putting it both in theme and extend
      fontFamily: {
        gilroy: ['var(--font-gilroy)', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
```

### Current vs. Expected behavior

As far as I know, I don't believe there is a way to use the next/font/local module when also using a custom _document.tsx page. Since _document.tsx cannot have the module imported, it has to be done in _app.jsx. However, wrapping everything in _app and importing the variable there defeats the purpose of a custom _document. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Tue Dec 19 20:55:03 PST 2023; root:xnu-10002.80.20.505.4~2/RELEASE_ARM64_T6000
Binaries:
  Node: 21.4.0
  npm: 10.4.0
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Font optimization (next/font)

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

I've tried a multitude of different things. The only solution so far is to wrap everything in _app.tsx in a div and apply the style there, which isn't really a great solution.

At first I tried to load the fonts directly into _app.tsx with no luck. My most recent attempt was to put them in ./styles/fonts.ts
No errors are thrown in a dev env, but the fonts are not listed as resources when inspecting in a browser.

**Comment by samcx** [comment]
@jordanlambrecht The `var(--font-gilroy)` doesn't seem to be defined anywhere.

![CleanShot 2024-02-20 at 23 05 55@2x](https://github.com/vercel/next.js/assets/28912696/fc557c2e-9e5c-43e0-81bd-87101982e090)

```
gilroy: ["Gilroy", "sans-serif"],
```

**Comment by samcx** [comment]
@jordanlambrecht I will be closing this in the meantime! Let me know if there's still an issue here and I will re-open the issue.
