### ISSUE TITLE
App router : ISR always regenerates dynamic routes even when called with same params

### ISSUE THREAD

**Issue by lolo-io** [vercel/next.js#62195]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/white-surf-3t2zj3?file=%2Fapp%2F%5Bslug%5D%2Fpage.tsx%3A7%2C43

### To Reproduce

1- `npx create-next-app@latest` -> Choose App Router
2- Create a [slug] dynamic route and create a `page.tsx` file with a minimal content and a `console.log`
3- `export const revalidate = 30;` in `[slug]/page.tsx`
4- `yarn build && yarn start` to start a production build
5- Load `localhost:3000/anyslug`
6- Refresh multiple times within 30 seconds

### Current vs. Expected behavior

- Current : 
`console.log` outputs log on every refresh.

- Expected : 
`console.log`  should output log only once within a 30 seconds window.

### Provide environment information

```bash
nextjs 14.1.0
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next start (local)

### Additional context

`revalidate` was working as intended for dynamic routes with Page Router.

**Comment by coffeecupjapan** [comment]
@lolo-io 
Hi. I investigate this issue and find that key-less fragment is not serialized as wrapper in React Server Component.

See Comments here 

https://github.com/facebook/react/blob/c1fd2a91b1042c137d750be85e5998f699a54d2a/packages/react-server/src/ReactFlightServer.js#L723-L724

Therefore, you can avoid error to be shown using fragment setting key like codes below.

```javascript
<React.Fragment key="somekey">
  <TableRow>
  ...
</React.Fragment>
```

I hope it would be help.

**Comment by lolo-io** [comment]
I found a solution/workaround for this. 

Add this to your route component to enable ISR for dynamic pages :

    export const dynamicParams = true
    export const generateStaticParams = async () => []

`export const generateStaticParams = async () => []` will _'enable'_ generating static versions of pages, but generate none at build time (empty array).
`export const dynamicParams = true` will allow to generate pages for params that have not been generated at build time.

I think it was somehow similar with Pages Router.

I don't know if this is a workaround or the correct way things should be, so I'll leave the issue open for now but feel free to close it if this is actually not a bug.

**Comment by white0dew** [comment]
but your soultion maybe not work

**Comment by joostmeijles** [comment]
> but your solution maybe not work

It does not work, see https://github.com/vercel/next.js/issues/65814#issuecomment-2164901366

**Comment by pepew-le-boss** [comment]
This works:
```javascript
export const revalidate = 30
export const dynamic = "force-static"
```

**Comment by joostmeijles** [comment]
> This works:
> 
> ```js
> export const revalidate = 30
> export const dynamic = "force-static"
> ```

It does not work, see https://github.com/joostmeijles/route-handler-stale/pull/3 and verify that visiting https://routehandler-stale-git-t-7e7c78-joost-meijles-projects-e8f38b93.vercel.app/items-dynamicparams/a returns `X-Vercel-Cache: STALE`

<img width="564" alt="image" src="https://github.com/vercel/next.js/assets/4342282/db84c794-9850-4e31-a92f-ac951733d378">

**Comment by pepew-le-boss** [comment]
When I do this, build and start the app:

```javascript
export const revalidate = 10
export const dynamic = "force-static"

export default async function SlugPage({ params }: { params: { slug: string } }) {

  console.log("slug", params.slug)

  return (
    <div>{params.slug}</div>
  )
}
```

If I spam the reload button on that page (for a given slug) I will see the log only every 10s.
If I change the slug (even before the 10s), I will see the log only the first time and then every 10s.

**Comment by samcx** [comment]
@pepew-le-boss Just tested Route Handlers—you don't need to have a `export const dynamic = "force-static"` to have the revalidate behavior, but if you use `force-static`, the behavior will always be static (a dynamic action will not bail out of static).

**Comment by samcx** [comment]
@lolo-io Closing this as this is the expected behavior unless you use `export const dynamic = "force-static"` or `export const generateStaticParams = async () => []`. I have updated the <picture data-single-emoji=":docs:" title=":docs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/docs/172e1b9b7d137b8a.png" alt=":docs:" align="absmiddle"></picture> as well for this!
