### ISSUE TITLE
Intercepting + Dynamic Routes, Jumping the page causes a forced refresh

### ISSUE THREAD

**Issue by zhengzhu-1m** [vercel/next.js#62207]
### Link to the code that reproduces this issue

https://github.com/bosinc/next-bug

### To Reproduce

1.  https://next-bug-vert.vercel.app
2. click `Page any` button

### Current vs. Expected behavior

When accessing dynamic interception routes, the page will be forced to refresh.
Note: 
 1. The bug will only be triggered in the vercel deployment environment
 2. The local development environment works normally

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103
Binaries:
  Node: 18.18.0
  npm: 10.1.0
  Yarn: 1.22.19
  pnpm: 8.15.3
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by ericmatthys** [comment]
I have come across a similar issue and found that I can reproduce it locally when using the edge runtime, but with the nodejs runtime it only seems to happen when deployed to Vercel.
