### ISSUE TITLE
Unable to import CSS file with SVG font using Turbo

### ISSUE THREAD

**Issue by frastefanini** [vercel/next.js#62241]
### Link to the code that reproduces this issue

https://github.com/frastefanini/next-with-slick

### To Reproduce

1. Start the app in dev mode without Turbo (`npm run dev`)
2. Everything is fine
3. Restart the app using Turbo (`npm run dev:turbo`)
4. It throws a "module not found" error
5. Stop the application
6. Switch to the `patch` branch
7. Run `npm i` to apply patches
8. Start the app in dev mode with Turbo
9. Everything is fine

### Current vs. Expected behavior

Seems like Turbopack can't handle CSS files importing SVG fonts. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
Binaries:
  Node: 20.8.1
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.13.1
Relevant Packages:
  next: 14.1.1-canary.61 // Latest available version is detected (14.1.1-canary.61).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[PACK-2539](https://linear.app/vercel/issue/PACK-2539/unable-to-import-css-file-with-svg-font-using-turbo)</sub>

**Comment by timneutkens** [comment]
This is fixed on next@canary 🎉 Here's the reproduction sandbox using canary: https://codesandbox.io/p/github/frastefanini/next-with-slick/csb-367r9q/draft/recursing-rain?file=%2Fpages%2Findex.tsx%3A6%2C30
