### ISSUE TITLE
typedRoutes: after build ts error "not an existing route" (dev ok)

### ISSUE THREAD

**Issue by chrisweb** [vercel/next.js#62335]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/morning-shape-pnj5zf?file=%2Fapp%2Ffoo%2Fpage.mdx

### To Reproduce

start dev server `npm run dev`
visit /foo and /bar
file **.next/types/link.d.ts** now contains 3 routes

start build `npm run build`
file **.next/types/link.d.ts** now contains ONLY 1 route
build fails, ts error "Type error: "/foo" is not an existing route."

### Current vs. Expected behavior

build should produce same **.next/types/link.d.ts** file as does dev runtime

webpack plugin ignores pages that have a .mdx (or .md, .markdown, ...) extension

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
  Available memory (MB): 32681
  Available CPU cores: 16
Binaries:
  Node: 20.11.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.67 // Latest available version is detected (14.1.1-canary.67).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

MDX (@next/mdx), Routing (next/router, next/navigation, next/link), TypeScript (plugin, built-in types)

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed), Other (Deployed)

### Additional context

as far as I can tell this problem has always existed

**Comment by rusakovic** [comment]
confirm the issue.

```
Type error: "/" is not an existing route. If it is intentional, please type it explicitly with `as Route`.

   5 |   return (
   6 |     <Link
>  7 |       href="/"

```

**Comment by chrisweb** [comment]
A workaround (until this is fixed) is to only enable the typed links in development, which is where it is the most useful anyway and disable them in prod (as this is where the bug occurs)

To enable **typedRoutes in development** only, you can do so by using the next config **phase** parameter, to check if current phase is **PHASE_DEVELOPMENT_SERVER**, an example next.config.mjs would look like this:

```mjs
import { PHASE_DEVELOPMENT_SERVER } from 'next/constants.js'

const nextConfig = (phase) => {

    /** @type {import('next').NextConfig} */
    const nextConfigOptions = {
        experimental: {
            // experimental typescript "statically typed links (routes)"
            // https://nextjs.org/docs/app/building-your-application/configuring/typescript#statically-typed-links
            typedRoutes: phase === PHASE_DEVELOPMENT_SERVER ? true : false,
        },
    }

    return nextConfigOptions

}

export default nextConfig;
```

**Comment by luchsamapparat** [comment]
@chrisweb are you sure this works? With that configuration, no types are generated at all, even when I run `next dev`.

**Comment by chrisweb** [comment]
@luchsamapparat this bug report is only when using mdx pages (page.mdx, or any other markdown extension), so if your problem is not about mdx pages, please open a discussion and tag me there

yes I'm sure it works, my reproduction example on codesandbox has the types for all routes (on dev), you can look at the `.next/types/link.d.ts` file and you will see that it contains:

  type StaticRoutes = 
    | `/`
    | `/foo`
    | `/bar`

however in production the foo and bar routes are missing as those are mdx pages, this is why I did a [PR](https://github.com/vercel/next.js/pull/62402) which is an attempt to fix this

the [workaround I suggested](https://github.com/vercel/next.js/issues/62335#issuecomment-2053666663) is about disabling type checking for routes in production to make sure deployments don't fail, it is just that so it does not alter how typed routes work in dev mode

I have no ideas what your problem is as I have no code to look at (but if you open a discussion and if I have some time I could check it out), however one thing I did in dev for my project is make sure all my routes use the Route type (which fixes a lot of messages about type errors (but again not related at all to bug report of this issue):

```
import Link from 'next/link'
import type { Route } from 'next'

interface IMenuItem {
    pathname: string
    text: string
}

const Navigation: React.FC = () => {

    const menuItems: IMenuItem[] = [
        { pathname: '/', text: 'Home' },
        { pathname: '/foo', text: 'Foo' },
        { pathname: '/bar', text: 'Bar' },
    ]

    return (
        <nav>
            {menuItems.map((menuItem) => {
                return (
                    <Link
                        href={menuItem.pathname as Route}
                        key={menuItem.pathname}
                    >
                        {menuItem.text}
                    </Link>
                )
            })}
        </nav>
    )
}

export default Navigation
```

it is very important to import the Route type from 'next' and then apply it to all href value to make sure Next.js understands it is a route and not just a string: **href={menuItem.pathname as Route}**
