### ISSUE TITLE
Turbo fails: Module not found if ts path is outside of current project

### ISSUE THREAD

**Issue by wodka** [vercel/next.js#62409]
### Link to the code that reproduces this issue

https://github.com/wodka/turb-bug-paths

### To Reproduce

1. go into the `client` folder
2. `npm run dev` without turbo works and displays the headline
3. `npm run dev:turbo` with turbo fails with a module not found

### Current vs. Expected behavior

I do expect turbo to work with paths that are defined in tsconfig

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.1.1-canary.69 // Latest available version is detected (14.1.1-canary.69).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[PACK-2646](https://linear.app/vercel/issue/PACK-2646/turbo-fails-module-not-found-if-ts-path-is-outside-of-current-project)</sub>

**Comment by sokra** [comment]
It's expected that Turbopack limits all filesystem access to be inside of the "root" directory. Mostly of security and

But the "root" directory can be something other than the "project" directory, and next.js already has some logic to automatically detect the "root" directory, e. g. by `pnpm-lock.json`.

But sometimes that fails, but there is a (weird) workaround to that. You can set the root path in the next.config.js. But the config option has a weird name: `experimental.outputFileTracingRoot`. Pass the absolute path you need as "root" directory.

Nonetheless, we should improve the error message to point out that the path is outside of the root directory.
