### ISSUE TITLE
Getting "Cannot find module 'next/headers' or its corresponding type declarations" error while trying to deploy to vercel.

### ISSUE THREAD

**Issue by mayank1513** [vercel/next.js#62478]
### Link to the code that reproduces this issue

https://github.com/mayank1513/nextjs-themes-ultralight

### To Reproduce

1. fork the repo and deploy to Vercel.

### Current vs. Expected behavior

All the examples build and work very well locally and on GitHub code spaces. However, when trying to deploy to Vercel, it fails and shows the following error.

```
../../lib/nthul/src/server/server-target/server-target.tsx:2:25
Type error: Cannot find module 'next/headers' or its corresponding type declarations.
```

Expected behavior: The app should build and deploy normally on Vercel.

### Provide environment information

```bash
Vercel

Tested with node 16, 18 and 20. Fails on all.
```

### Which area(s) are affected? (Select all that apply)

Package manager (npm, pnpm, Yarn), Turbopack (--turbo), TypeScript (plugin, built-in types)

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by balazsorban44** [comment]
https://github.com/mayank1513/nextjs-themes-ultralight/blob/24b3f05ede31c0444727af77cb6d73b829eb4f82/lib/nthul/package.json#L47-L56 looks like `next` is only added as an optional peer dependency. So it's likely not installed and such the import will fail.

You likely want to add it as a dev dependency for build to succeed.

(Note: the project did not use Turbopack, but Turborepo, which are different things. See https://turbo.build/)
