### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module when use antd

### ISSUE THREAD

**Issue by cjy4979** [vercel/next.js#62472]
### Link to the code that reproduces this issue

https://github.com/cjy4979/frontEndTemplate

### To Reproduce

create a next project and install antd
``` bash
yarn add antd 
# or
npm install antd
```
``` tsx
import { Button } from 'antd'
import React from 'react'

const Homepage = () => {
  return (
    <div>
      <Button>test</Button>
    </div>
  )
}
export default Homepage
```
then
``` bash
yarn dev
# or
npm run dev
```
then you can see this error

### Current vs. Expected behavior

just import an antd ui, and error occured
 ⨯ E:\working\myfrontend-project\node_modules\@ant-design\icons\es\components\Context.js:1
import { createContext } from 'react';
SyntaxError: Cannot use import statement outside a module

it is similar to issue #58817, but https://github.com/vercel/next.js/issues/58817#issuecomment-1927036489 closed.

### Provide environment information

```bash
placform:windows windows 11 22H2
NodeJs: v20.10.0
yarn: v1.22.21
antd: ^5.14.2
next: 14.1.0
```

### Which area(s) are affected? (Select all that apply)

App Router, Dynamic imports (next/dynamic), ESLint (eslint-config-next)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by cjy4979** [comment]
solved with transpilePackages

**Comment by romelgomez** [comment]
Hi @cjy4979, please elaborate more, transpilePackages?  is not clear to me how you solve it.

**Comment by romelgomez** [comment]
I do this, and it resolves the issue. 

https://github.com/ant-design/ant-design/issues/46053#issuecomment-1827836587

> I have a project with the same problem, so in the `nextjs.config.js` file I added this line:

```
transpilePackages: [ "antd", "@ant-design", "rc-util", "rc-pagination", "rc-picker", "rc-notification", "rc-tooltip", "rc-tree", "rc-table" ],

```
