### ISSUE TITLE
Tailwind CSS code Splitting doesn't work

### ISSUE THREAD

**Issue by leo-cheron** [vercel/next.js#62477]
### Link to the code that reproduces this issue

https://github.com/leo-cheron/nextjs-issue-tailwind-splitting

### To Reproduce

The reproduction repo showcases a project with 2 pages:
- [Home](https://nextjs-issue-tailwind-splitting-git-main-internets.vercel.app/)
- [Subpage](https://nextjs-issue-tailwind-splitting-git-main-internets.vercel.app/page)

Both pages will load the same unique CSS file.

Production build contains a single generated CSS files:
![image](https://github.com/vercel/next.js/assets/418965/15d487c9-6e8a-4c01-a651-5e2a07dbf973)

### Current vs. Expected behavior

When compiling for production using Tailwind, CSS code splitting fails and a single file is generated for the whole project, despite having multiple pages. This impact negatively performances any non SPA project.

Expected behaviour: A global CSS chunks should be generated, and each page / component should load it's own CSS chunk.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.17
  pnpm: 8.15.3
Relevant Packages:
  next: 14.1.1-canary.71 // Latest available version is detected (14.1.1-canary.71).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Module resolution (CJS / ESM, module resolving)

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed), Other (Deployed)

**Comment by nhducit** [comment]
This is how Tailwind works. Next.js cannot do anything here.

**Comment by jantimon** [comment]
MS Teams created atomic styles (so basically similar to tailwind but auto generated) from their code resulting in a 1 MB .css file:

https://github.com/mui/material-ui/issues/38137#issuecomment-1912696700

> Why it matters? In a large application, you must preload CSS for the entire app. You can't load something later without incurring a performance hit.

**Comment by samcx** [comment]
@leo-cheron Tailwindcss by default generates 1 CSS file, as mentioned by @nhducit!

**Comment by leo-cheron** [comment]
> @leo-cheron Tailwindcss by default generates 1 CSS file, as mentioned by @nhducit!

I guess I'have to combine it with modules to manually split some heavy chunks.

**Comment by oliviertassinari** [comment]
I would be very interested in a benchmark on the cost of not having code spitting for Tailwind CSS. There seems to be a cost:

- https://youtu.be/nWcexTnvIKI?si=2Yea9mRcgVtMY19i&t=1312 unused CSS has a network work, a CSS parsing cost, and a continuous runtime style resolution runtime cost each time a change in the DOM happens.

<img width="409" alt="SCR-20240310-ucqw" src="https://github.com/vercel/next.js/assets/3165635/ef3e9014-fdf9-4648-8942-23d13a51ad29">

- https://github.com/reactwg/react-18/discussions/108 React tech lead encourages to code split Tailwind CSS:

> If you extract everything into literally a single CSS file for your whole site you might get away with just putting a <link> https://github.com/reactwg/react-18/discussions/106 and call it a day. That might not be such a bad idea for many small sites that use atomic CSS or reusable rules like tailwind. Those tend to plateau in their size growth.
> 
> However, even in those systems you eventually tend to grow out of them and loading all CSS up front becomes a bad idea. In those cases you want to inject CSS files based on if they're used by the components you're rendering on the server.
