### ISSUE TITLE
Issues with intercepting routes in dev mode

### ISSUE THREAD

**Issue by Schmavery** [vercel/next.js#62470]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/dev-mode-route-intercept-bug-6rxwz9

### To Reproduce

Note that there's no styling in order to simplify the example, so calling it a "modal" is a bit of a stretch. This is a simplification of https://github.com/vercel/nextgram, where I also experience the issue.

1. Start application: `next dev`
![image](https://github.com/vercel/next.js/assets/2154522/503610ac-1743-4fac-87ff-31ed233be2ba)

2. Click "Open Modal" to open the "photos modal". Works as expected.
![image](https://github.com/vercel/next.js/assets/2154522/bee00321-822d-4e26-8672-88b320039c15)

3. Refresh the page to see the photos page (no modal). Works as expected.
![image](https://github.com/vercel/next.js/assets/2154522/b8b54a3c-fa02-4daf-af96-4853771638ef)

4. Edit any page, ex: in `app/page.tsx` add "!" to the "Open Modal" text.
![image](https://github.com/vercel/next.js/assets/2154522/4f5f5ac5-6e37-4080-aa48-16aa995260a6)

6. Allow the photos page to reload automatically. The photos page now shows the modal rendering with the photos page as the "background"
![image](https://github.com/vercel/next.js/assets/2154522/44dc3dfd-06df-45c4-8178-c2b4862e67f8)

### Current vs. Expected behavior

I would expect the hotreload to have no visible effect, but instead it seems to cause the route to be suddenly intercepted. I'm not sure if this is a bug in the implementation (this repros on https://github.com/vercel/nextgram as well) or in the route interception logic during dev mode.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I've tested this on latest canary (14.1.1-canary.70), 14.1.0 and 14.0.0 and all exhibit the same issue.
I first ran into it in a project I was developing in Windows, so I tried the running the nextgram repo locally (on canary) to see if it was a problem with my code. When that had the same bug, I tried in WSL with the same result. In making this issue I verified that it also happened in the codesandbox env.

Thanks! <3

**Comment by xvvvyz** [comment]
Possibly related to https://github.com/vercel/next.js/issues/60844
