### ISSUE TITLE
14.1: Router Cache is applied only to first page load. After 30s it's refetching on every navigation (inconsistency issue)

### ISSUE THREAD

**Issue by burithetech** [vercel/next.js#62504]
### Link to the code that reproduces this issue

https://github.com/burithetech/nextjs14.1-routercache-bug/tree/main/src/app

### To Reproduce

1. `git clone git@github.com:burithetech/nextjs14.1-routercache-bug.git`
2. `cd nextjs14.1-routercache-bug`
3. `npm run dev`
4. Open [http://localhost:3000](http://localhost:3000)
5. Click on "Current time page"
6. During first 30 seconds (Router Cache) the page is cached on the client side - so when you're clicking on the navigation nothing should be fetched.
7. After 30 seconds, every click or navigation on "Current time page" makes requests and Router Cache is no more populated.

### Current vs. Expected behavior

**Current:** After 30 seconds, every click or navigation on "Current time page" makes requests and cache is no more populated or used.

**Expected:** I would expect that after 30 seconds only a single request would be made and then another 30 second cache interval would be applied. This is very confusing in terms of the docs and consistency of the behaviour.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.14.2
Relevant Packages:
  next: 14.1.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

**Comment by ztanner** [comment]
Hi, thanks for the report. This was resolved in #61573 (which landed in [v14.1.1-canary.64](https://github.com/vercel/next.js/releases/tag/v14.1.1-canary.64).
