### ISSUE TITLE
using `promise` in `generateMetadata` along with `loading.tsx` cause page fetched several times (on development)

### ISSUE THREAD

**Issue by remove158** [vercel/next.js#62515]
### Link to the code that reproduces this issue

https://github.com/remove158/generate-metadata-bug-report

### To Reproduce

1. create route `/` and `/test` with `/page.tsx` , `/test/page.tsx` and `/test/loading.tsx`
2. in `/page.tsx` just navigate to `/test`
```tsx
import Link from "next/link";

export default function Home() {
	return (
		<main className="flex min-h-screen flex-col items-center justify-between p-24">
			<Link href="/test">test</Link>
		</main>
	);
}
```
3. in `/test/loading.tsx` just make loading text
``` tsx
export default function loading() {
	return <div>loading</div>;
}
```
4. in `/test/page.tsx` implement `generateMetadata()` with `promise`
```tsx
import { Metadata } from "next";

export default function page() {
	console.count("page load");
	return <div>page</div>;
}

export async function generateMetadata(): Promise<Metadata> {
	await new Promise((r) => setTimeout(r, 50, "some value"));
	console.count("generate metadata");
	return {};
}


```
5. run in development mode `bun dev` and  go to `http://localhost:3000`
6. click `<Link>test</Link>` and you will navigate to `/test`
7. You will see message `generate metadata` and `page load` print several times
> its not gonna happen if u go to `http://localhost:3000/test` directly

![Screenshot 2567-02-26 at 05 28 54](https://github.com/vercel/next.js/assets/23172564/3acd4957-602e-4e2d-bb13-97a3d605255c)

### Current vs. Expected behavior

Current
- `page` and `generateMetadata` called several times

Expected
- `page` and `generateMetadata` called once

### Provide environment information

```bash
Operating system:
	Platform: darwin
	Arch: intel
	Version: macOS Sonoma 14.2.1 (23C71) 
Binaries:
	bun: 1.0.20

"dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.1.0"
  },
"devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "eslint": "^8",
    "eslint-config-next": "14.1.0"
  }
```

### Which area(s) are affected? (Select all that apply)

Metadata (metadata, generateMetadata, next/head)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I don't see this problem on productions.

If you go directly to `/test` you won't encounter this problem.

**Comment by jimmycrequer** [comment]
I had the same issue and solved it by upgrading `next` to the latest version (14.2.3).
Maybe related to #61117 ?
