### ISSUE TITLE
Page does not render on changing the routes using link component

### ISSUE THREAD

**Issue by NidhiSharma63** [vercel/next.js#62520]
### Link to the code that reproduces this issue

https://github.com/NidhiSharma63/snapgram/tree/converting-into-nextjs

### To Reproduce

Using this [url](https://snapgram-nextjs-ecru.vercel.app/) try to navigate between pages.

![gif for snapgram](https://github.com/vercel/next.js/assets/99652555/4b858ffc-4b4d-4e95-8399-82dc83949df7)

### Current vs. Expected behavior

I'm expected to change the content for every routes

### Provide environment information

```bash
Operating system - window - 64-bit operating system
"next": "^14.1.0"
"react": "^18.2.0",
"react-dom": "^18.2.0",
"node": v21.1.0
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

I'm deploying my application on vercel. the above issue is not happening in localhost but in production it is happening.

**Comment by mskp** [comment]
Dear Next.js team, Please provide a proper solution to this issue. It's that simple: "We, as developers, want to develop a website using Next.js with smooth navigation." Is that even possible, or should we switch to another framework? Even if it is because of caching, please provide a proper solution to opt out of it; the solutions mentioned in the docs are not working.

**Comment by ztanner** [comment]
Hi @NidhiSharma63 , can you clarify why your app contains this rewrite rule?
https://github.com/NidhiSharma63/snapgram/blob/converting-into-nextjs/client/vercel.json#L2C29-L2C34

```
{
  "rewrites": [{ "source": "/(.*)", "destination": "/" }]
}
```

I believe this might be the source of the bug.

**Comment by NidhiSharma63** [comment]
@ztanner thanks for your solution. yes this rewrites rules causing the issue.

**Comment by ztanner** [comment]
Great! I'll close this then, but feel free to open a new issue if you encounter a bug.
