### ISSUE TITLE
`redirect(...)` with search params doesn't work in 14.1.1

### ISSUE THREAD

**Issue by chungweileong94** [vercel/next.js#62525]
### Link to the code that reproduces this issue

https://github.com/chungweileong94/next-bug-redirect-with-search-params

### To Reproduce

1. Start the application with `next dev`
2. Click the "Add some search params" button

### Current vs. Expected behavior

Expected: 
- It should display the current search parameters on the page.
- The middleware `req.nextUrl` should contain search params

Current:
- It didn't show any search params on the page until we refreshed the page manually. 
- The middleware `req.nextUrl` doesn't contains any search params

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.14.0
Relevant Packages:
  next: 14.1.1-canary.72 // Latest available version is detected (14.1.1-canary.72).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

It was working before in 14.1 and prior to that version. 
Note that the "Clear search params" link on the page also doesn't work as expected, if you click on the "Add some search params" button and click the link afterward.

<sub>[NEXT-2620](https://linear.app/vercel/issue/NEXT-2620/redirect-with-search-params-doesnt-work-in-1411)</sub>

**Comment by coffeecupjapan** [comment]
@chungweileong94 
It is definitely a bug of Next.js, so I open a PR.
I hope it would help. 

https://github.com/vercel/next.js/pull/62582
