### ISSUE TITLE
Changed Cookies Not Sent Upon router.refresh()

### ISSUE THREAD

**Issue by grichards** [vercel/next.js#62621]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64
  Available memory (MB): 65536
  Available CPU cores: 12
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.15
  pnpm: 6.11.0
Relevant Packages:
  next: 14.1.1-canary.77 // Latest available version is detected (14.1.1-canary.77).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

n/a

### Describe the Bug

Cookie data is used in a server component to modify a fetch call.

Cooke state is modified in a client component  (using js-cookie).

router.refresh() is called in the client component after the cookie state is modified.

The modified cookie state is not sent to the server in the request header.

The prior cookie state is sent instead.

### Expected Behavior

The current state of the browser cookie should be sent with router.refresh()

### Abbreviated Example Code

In a context provider:

```
export function SelectedVehicleContextProvider({ children }: { children: ReactNode }) {
/*...*/

  // If a new vehicle is selected, persist it to cookie
  useEffect(() => {
    if (selectedVehicle) {
      const selectedVehicleString = JSON.stringify(selectedVehicle)
      Cookies.set('selectedVehicle', selectedVehicleString, { expires: 365 })
    } else {
      Cookies.remove('selectedVehicle')
    }
  }, [selectedVehicle])

/*...*/
}
```

In a client component using the context provider:

```
export default function VehicleSelector({ onVehicleSelect }: { onVehicleSelect?: () => void }) {
/*...*/

      setSelectedVehicle(selectedVehicleData)

      router.refresh()


/*...*/
}
```

With that code, after router.refresh() executes, you will see an RSC request to the server and if you inspect the Request headers, you will see that the cookies value is from the previous state.

**Comment by balazsorban44** [comment]
For a bug report, please use the bug report template: https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml
