### ISSUE TITLE
Docs: Offering Help with Chinese Documentation Translation

### ISSUE THREAD

**Issue by weijunext** [vercel/next.js#62623]
### What is the improvement or update you wish to see?

I wish to see more Chinese translations in the official Next.js documentation. Although Next.js is already very popular, users in the Chinese community still face language barriers, especially those for whom English is not their first language. By providing more comprehensive Chinese documentation, we can not only help existing Chinese users understand and use Next.js better but also enable more potential Chinese developers to get in touch with and learn this powerful framework. I am willing to participate in this translation work, whether it involves translating new documents or proofreading and improving existing Chinese translations.

### Is there any context that might help us understand?

As a web developer who has been using Next.js for project development for a long time, I deeply understand the importance of high-quality documentation for learning and applying technology. I know that good documentation translation not only needs to accurately convey the original meaning but also consider language habits and regional differences in technical terminology. I believe that providing Chinese documentation can significantly enhance the attractiveness of Next.js to Chinese developers and lower the learning curve. I hope my background and experience can contribute to the improvement and expansion of Next.js's Chinese documentation.

**Comment by balazsorban44** [comment]
Hi, there is currently no active project working on internationalizing the Next.js documentation.

However, a community-maintained Chinese version is available at https://www.nextjs.cn/docs. You can try reaching out to them if they need help.

(**Note, despite what the footer claims, Vercel has no affiliation with the site, so any mistakes made there are out of responsibility for the Vercel team.**)

**Comment by weijunext** [comment]
> Hi, there is currently no active project working on internationalizing the Next.js documentation.
> 
> 
> 
> However, a community-maintained Chinese version is available at https://www.nextjs.cn/docs. You can try reaching out to them if they need help.
> 
> 
> 
> (**Note, despite what the footer claims, Vercel has no affiliation with the site, so any mistakes made there are out of responsibility for the Vercel team.**)

Hi, thanks for your reply. Regarding https://nextjs.cn, their documentation version is too outdated. I’ve tried reaching out to them but got no response. 

I think I’ll set up my own Next.js documentation translation website, and I’ll make sure it stays up-to-date with https://nextjs.org’s documentation. I’m looking forward to the day when my work gains recognition from the community.
