### ISSUE TITLE
Next in Vercel - SSG page with fetch `cache: no-store` responds with `404 Not Found` page

### ISSUE THREAD

**Issue by fullyherge** [vercel/next.js#62634]
### Link to the code that reproduces this issue

https://github.com/fullyherge/vercel-cache-repro

### To Reproduce

1. Install dependencies
2. Run locally - `npm run build` => `npm run start`
3. Go to `localhost:3000/no-store` and note that it functions
4. Deploy to Vercel - `vercel link` => `vercel deploy`
5. Go to the deployed site (mine is here: [`no-store`](https://vercel-cache-repro-fullystudios-fully-studios-team.vercel.app/no-store))
6. Note that it does not function - instead gives `404 Not Found`

### Current vs. Expected behavior

It gives an error.
I expect the page to render, just like in local environment.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 18.18.2 // Also tested v20
  npm: 9.8.1
  Yarn: 1.22.21
  pnpm: 8.9.2
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0 // Also tested on canary
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Data fetching (gS(S)P, getInitialProps)

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

Also posted my initial discussion here: https://github.com/orgs/vercel/discussions/5935

**Comment by dominicbachmann** [comment]
This is similar to https://github.com/vercel/next.js/issues/62697

**Comment by samcx** [comment]
@fullyherge Taking a look!

@dominicbachmann I'm not sure that's a duplicate, as this issue indicates that `no-store` results in a `404`.

**Comment by ijjk** [comment]
Hi, a fix has now been landed/rolled for this, please re-deploy your project and give it a try!
