### ISSUE TITLE
`import.meta.url` does not work with turbopack 

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#62650]
### Link to the code that reproduces this issue

https://github.com/Fredkiss3/import-meta-not-working-with-turbopack

### To Reproduce

1. Clone the project
2. Run `npx next dev --turbo`
3. Open the browser, you will see this error

<img width="1010" alt="image" src="https://github.com/vercel/next.js/assets/38298743/c56a89b6-4f5e-49d1-b84e-155bad2cdba7">

### Current vs. Expected behavior

If you run `npx next dev` (without `--turbo` flag), you will see that `import.meta.url` resolves to the current file correctly : 

<img width="927" alt="image" src="https://github.com/vercel/next.js/assets/38298743/1a176745-4eda-4b05-bcc8-4585db3dcd7e">

It seems like turbopack doesn't yet support the `import.meta.url` in ESM projects. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.15.3
Relevant Packages:
  next: 14.1.1-canary.78 // Latest available version is detected (14.1.1-canary.78).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[PACK-2625](https://linear.app/vercel/issue/PACK-2625/importmetaurl-does-not-work-with-turbopack)</sub>

**Comment by ForsakenHarmony** [comment]
It's still missing edge runtime support unfortunately

Can you give some more context on what the actual use case of `import.meta.url` is in the project you're using it in?

**Comment by Fredkiss3** [comment]
In our project we use `import.meta.url` to fetch fonts and generate OG images using `next/og` :

https://github.com/modularcloud/explorer/blob/f9ebfe386a927cce0f3863131e070ae6e210166f/apps/web/app/api/og/route.tsx#L45-L47

**Comment by ForsakenHarmony** [comment]
For future reference:
This is one of the failing tests from `test/e2e/app-dir/metadata-dynamic-routes/index.test.ts`
Specifically the "should handle custom fonts in both edge and nodejs runtime" case

**Comment by timneutkens** [comment]
`test/e2e/app-dir/metadata-dynamic-routes/index.test.ts` is fully passing now, please give it another try using next@canary @Fredkiss3 🙌

**Comment by Fredkiss3** [comment]
@timneutkens Tried with `next@canary` (`14.2.0-canary.33`) and `next@latest` (`14.1.4`) and the issue is still there.

**Comment by Fredkiss3** [comment]
Ok this issue seems to have been fixed in `canary` when using `new URL("...", import.meta.url)`. 

I don't know a usecase other than using it with `new URL()` so I will close this issue.
