### ISSUE TITLE
https://nextjs.org/learn/dashboard-app/improving-accessibility

### ISSUE THREAD

**Issue by jay-s-p** [vercel/next.js#62693]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
at top it showing:
--18725e4edd23a47d x-next-cache-tags: _N_T_/layout,_N_T_/(next-site)/layout,_N_T_/(next-site)/learn/layout,_N_T_/(next-site)/learn/[...slug]/layout,_N_T_/(next-site)/learn/[...slug]/page,_N_T_/learn/dashboard-app/improving-accessibility vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch


and at last it showing
--18725e4edd23a47d--
```

### Which example does this report relate to?

learn next.js section

### What browser are you using? (if relevant)

edge

### How are you deploying your application? (if relevant)

-

### Describe the Bug

![image](https://github.com/vercel/next.js/assets/53110999/566f3c75-125d-4072-a00e-4bf244761284)

![image](https://github.com/vercel/next.js/assets/53110999/1825c658-6e78-40f3-82a8-2ded578af556)

### Expected Behavior

remove that text

### To Reproduce

just open the site

**Comment by ztanner** [comment]
Thank you for the heads up! This has been fixed.
