### ISSUE TITLE
Docs: on vercel.com/docs/storage/vercel-postgres/quickstart anchor link not working

### ISSUE THREAD

**Issue by andreasoikon** [vercel/next.js#62718]
### What is the improvement or update you wish to see?

Not sure if this the right place to write this but I didn't find anywhere else.

In the Vercel documentation about Vercel Postgres, in the [Quickstart guide](https://vercel.com/docs/storage/vercel-postgres/quickstart) there is an anchor link not working.

In the second line --> "If you'd prefer to deploy a template, head to the [Templates](https://vercel.com/docs/storage/vercel-postgres/quickstart#Templates) section." the letter _t_ of the templates word in the url should be small t and not uppercase T because the link is not working.

### Is there any context that might help us understand?

No added context needed

### Does the docs page already exist? Please link to it.

https://vercel.com/docs/storage/vercel-postgres/quickstart

**Comment by ViKi10000** [comment]
can i work on it?

**Comment by leerob** [comment]
Thanks, we'll fix this on the Vercel side.
