### ISSUE TITLE
Docs: suggest delete or edit link of ther read-only methods of URLSearchParams.

### ISSUE THREAD

**Issue by nayounsang** [vercel/next.js#62710]
### What is the improvement or update you wish to see?

Learn more about other read-only methods of [URLSearchParams](https://developer.mozilla.org/docs/Web/API/URLSearchParams), including the [getAll()](https://developer.mozilla.org/docs/Web/API/URLSearchParams/getAll), [keys()](https://developer.mozilla.org/docs/Web/API/URLSearchParams/keys), [values()](https://developer.mozilla.org/docs/Web/API/URLSearchParams/values), [entries()](https://developer.mozilla.org/docs/Web/API/URLSearchParams/entries), [forEach()](https://developer.mozilla.org/docs/Web/API/URLSearchParams/forEach), and [toString()](https://developer.mozilla.org/docs/Web/API/URLSearchParams/toString).

* I talk about this part.
* I think  [URLSearchParams](https://developer.mozilla.org/docs/Web/API/URLSearchParams) alone explains it well.
* If i try to access the link such as getAll(),keys(),..., i will meet "PAGE NOT FOUND" of MDN docs. **Because it is supported only in EN-US docs.**
* Therefore, the docs deletes those and  mentions that mdn docs about "URLSearchParams" has all the explanations. or edit link.

### Is there any context that might help us understand?

[URLSearchParams](https://developer.mozilla.org/docs/Web/API/URLSearchParams)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/use-search-params

**Comment by balazsorban44** [comment]
These links will redirect correctly, i.e. if I visit https://developer.mozilla.org/docs/Web/API/URLSearchParams/getAll it opens https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/getAll for me.

Also, I can see that other translated versions have these pages too:

https://developer.mozilla.org/ja/docs/Web/API/URLSearchParams/getAll
https://developer.mozilla.org/zh-CN/docs/Web/API/URLSearchParams/getAll

Hence, I think our docs links should work fine. :thinking:
