### ISSUE TITLE
14.1.1 version introducing breaking change for cookies()

### ISSUE THREAD

**Issue by alimek** [vercel/next.js#62727]
### Link to the code that reproduces this issue

https://github.com/alimek/next-bug

### To Reproduce

```
export const getToken = cache(() => {
  const cookieStore = cookies();
  const token = cookieStore.get("token")?.value;

  return token ?? 'no-token';
});

export const getLanguage = cache(() => {
  const cookieStore = cookies();
  const language = cookieStore.get("language")?.value;

  return language ?? 'pl-pl';
});
```

when calling getLanguage() or getToken() it should return always string, after upgrade to 14.1.1 its Promise 

### Current vs. Expected behavior

Current

 ```
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 const token = getToken();
 const language = getLanguage();

  return (
    <html lang={language} suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <Client value={token} />
      </body>
    </html>
  );
}
```

generating 

```html
<html lang="[object Promise]">
...
</html>
```
instead

```html
<html lang="pl-pl">
...
</html>
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 4.1.0
  pnpm: 8.7.0
Relevant Packages:
  next: 14.1.1
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

<sub>[NEXT-2660](https://linear.app/vercel/issue/NEXT-2660/1411-version-introducing-breaking-change-for-cookies)</sub>

**Comment by pookmish** [comment]
This appears very similar to an issue I found with 14.1.1. It's not cookies or headers, but I'm using `graphql-request` and with 14.1.0 I was able to just do something like `await getMyGraphqlClient().Query()`. With 14.1.1 I have to do `await (await getMyGraphqlClient()).Query()`. I wonder if something is unnecessarily wrapping functions in async?

I confirmed the issue occurs with 14.1.2-canary.1

**Comment by pookmish** [comment]
For my issue I discovered by having `"use server";` at the top of the file, Next would convert all functions into async functions. As soon as I removed the `"use server"`, it went back to expected behavior.

**Comment by feedthejim** [comment]
hey thanks for reporting, we're hoping to fix the issue today or tomorrow! we will trigger a patch then

**Comment by shuding** [comment]
Hey everyone! It turned out to be a bug that previously it's allowed to mark synchronous functions with `"use server"`, as explained in #62821. With that PR we're improving the messages so it can error earlier.

**Comment by alimek** [comment]
so, every function now which is in "use server" file must be asynchronous

For mine use case, I was just using "use server" to mark exported function to just force run it on the server, which I am not sure now if that is really the thing

I am now thinking if `import "server-only"` would be better for the use case? so I dont have to use `await` to get value from cookie as example?

**Comment by shuding** [comment]
Yes @alimek, `import "server-only"` is exactly for that use case. Even if you mark a file with `"use server"`, client modules are still able to import and invoke these functions (Server Action calls). But if you use `import "server-only"` and try to import it into the client you'll directly get an error.

**Comment by alimek** [comment]
cool, thanks for clarification 👍

**Comment by ADTC** [comment]
I have the below function which is used to get the cookie value, but now it gets a Promise. It broke my application.

```tsx
'use server'

import { cookies } from 'next/headers'

// Definition:
export const getCookie = (name: string) => cookies().get(name)?.value

// Usage:
const myCookie = getCookie('myCookie')
```

How do I best fix this right now? I recently moved from Next version `14.1.0` to `14.1.3`. I think I can temporarily treat it as a Promise and use `await`:

```tsx
// Definition: no change

// Usage:
const myCookie = await getCookie('myCookie')
```
This got it working again. TypeScript warns though: 'await' has no effect on the type of this expression. ts(80007)

The question is: **Will it break in a future release?** Non-Promise values should fall through `await` expressions without any error, [but side effects regarding execution order can occur.](https://stackoverflow.com/a/55263084/1134080)

**Comment by alimek** [comment]
@ADTC  assuming you had same problem like me, If you want to force your function be only available on server, change `'user server'` to `import 'server-only';` and it should work.

**Comment by ADTC** [comment]
After a bit more reading, I seem to gather that all functions in a file that starts with `'use server'` are now automatically async functions, even if they look synchronous.

And this is a permanent expectation of Server Actions that **_won't_** be reverted in a future release of Next.js. Is that right?

In that case, I infer that the best fix is to also change the definition to make it `async`. (Another more explicit way is to construct and return a `new Promise`.)

```tsx
// Definition:
export const getCookie = async (name: string) => cookies().get(name)?.value

// Usage:
const myCookie = await getCookie('myCookie')
```

---

@alimek _(You commented after I wrote the above already.)_ In my case, I cannot make your suggested change because I'm using these methods in client components as Server Actions. But yes, that's another possible solution if your methods are meant for server use only.
