### ISSUE TITLE
Parallel routes don't show all slot loading.tsx on stable version

### ISSUE THREAD

**Issue by Katsukiniwa** [vercel/next.js#62722]
### Link to the code that reproduces this issue

https://github.com/Katsukiniwa/parallel-routes-bug

### To Reproduce

1. clone repository
2. run `pnpm install`
3. access `http://localhost:3000/dashboard`

### Current vs. Expected behavior

# Current

Next.js render only @customers/loading.tsx and @sales/loading.tsx

# Expected

I expect Next.js render all slots loading.tsx(@customers/loading.tsx and @sales/loading.tsx and @books/loading.tsx)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:59 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6030
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.15.4
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

This issue don't occur v14.1.1-canary.15, but occur on v14.1.1-canary.14, 14.1.0 and 14.1.1.
On v14.1.1-canary.15 release,  https://github.com/vercel/next.js/pull/61115 is a only PR that related to parallel routes, so this issue may be already fixed

**Comment by ztanner** [comment]
Hi @Katsukiniwa -- thank you for the report. It was indeed fixed in the canary you linked, but it wasn't part of 14.1.1 and will be in the next stable release. In the meantime, the latest canary should have the fix until it hits stable. Apologies and thanks for the patience.
