### ISSUE TITLE
Docs: How to use react cache with server actions if "use server" files only allow async exports?

### ISSUE THREAD

**Issue by yannxaver** [vercel/next.js#62860]
### What is the improvement or update you wish to see?

From 14.1.2 "use server" files only allow async exports. How can we utilize react cache now?

### Is there any context that might help us understand?

https://github.com/vercel/next.js/pull/62821

**Comment by sannajammeh** [comment]
ref: https://github.com/vercel/next.js/pull/62821#issuecomment-1977557075

**Comment by yannxaver** [comment]
Okay, I see. Seems like the problem is more about project structure / code organization. So far I haven't used "use server" files exclusively for mutations.

I have one "use server" file per entity and this file includes "get" and "post" requests. I use React cache for the "get" requests. Seems like this structure won't work anymore and I need to create two separate files for get and post requests

**Comment by chungweileong94** [comment]
I do agree that you not suppose to use React cache with server action, as it literally does nothing. However, library that produces server action (async function) will cause the same error as well, as the code will get transpiled into Promise instead of `action.constructor.name === "AsyncFunction"`

**Comment by laurens-mesure** [comment]
I understand that caching mutations does nothing, but why limit this? It breaks colocation of getters and setters in a single file.

**Comment by darekrossman** [comment]
How would the following (from the docs on react `cache`) be handled now? Currently, this is broken...
```
import { cache } from 'react'
 
export const getItem = cache(async (id: string) => {
  const item = await db.item.findUnique({ id })
  return item
})
```

**Comment by darekrossman** [comment]
Server Actions aside, this still appears to be an issue

 > Its worth noting that this currently breaks the example shown in the documentation around using React.cache currently: https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-third-party-libraries

_Originally posted by @bduff9 in https://github.com/vercel/next.js/issues/62926#issuecomment-1984256120_

**Comment by mordechaim** [comment]
This is an absolute breaking change. I use React.cache to colocated getters (accessed in server components) and mutations.

**Comment by mordechaim** [comment]
**Workaround for `React.cache`**:

```js
import { cache as reactCache } from 'react'

export const cache = fn => {
    const cachedFn = reactCache(fn)
    return async (...params) => {
        return await cachedFn(...params)
    }
}
```

**Comment by chungweileong94** [comment]
> **Workaround for `React.cache`**:
> 
> ```js
> import { cache as reactCache } from 'react'
> 
> export const cache = fn => {
>     const cachedFn = reactCache(fn)
>     return async (...params) => {
>         return await cachedFn(...params)
>     }
> }
> ```

I'm not sure about the details, but chances are we are not supposed to call `cache(...)` within a function, I might be wrong. But maybe we should do it like this instead, more code but safer?
```ts
import { cache } from 'react'

const _fn = cache(async () => {
    return "...";
})

export const fn = async (...params) => {
    return _fn(...params)
}
```

**Comment by mordechaim** [comment]
Your code is useful when you colocate the cached function inside the server actions file. My version is a utility you could use as a dropin replacement to React.cache

> but chances are we are not supposed to call cache(...) within a function

Tested, works perfectly. The only requirement is that the cached function shouldn't change identity so that's why I create `cachedFn` outside the returned async function.

**Comment by chungweileong94** [comment]
Looks like the stricter "use server" check has been reverted in the latest canary version #63200.

In the meantime, you use this wrapper to workaround any async function produced by the library
```ts
function asyncFunction<T extends (...params: any[]) => Promise<any>>(fn: T) {
  return async (...params: Parameters<T>) => fn(...params);
}
```

**Comment by shuding** [comment]
The `"AsyncFunction"` requirement has been reverted (so I think this issue can be closed now, thanks everyone!). 

It's totally fine to co-locate data access utilities, however this requirement **still applies** and we need to be careful. All functions exported from a `"use server"` file will become async once imported, even if they're defined as sync functions.
