### ISSUE TITLE
Docs: Wrong Example Code

### ISSUE THREAD

**Issue by theDeal** [vercel/next.js#62947]
### What is the improvement or update you wish to see?

On [this Page](https://nextjs.org/docs/app/api-reference/functions/generate-sitemaps)
The TS Type from the function sitemap is wrong.

**Right Now:**
```
export default async function sitemap({
  id,
}: {
  id: number
}): MetadataRoute.Sitemap {
  // Google's limit is 50,000 URLs per sitemap
  const start = id * 50000
  const end = start + 50000
  const products = await getProducts(
    `SELECT id, date FROM products WHERE id BETWEEN ${start} AND ${end}`
  )
  return products.map((product) => ({
    url: `${BASE_URL}/product/${product.id}`
    lastModified: product.date,
  }))
}
```
**Corrected Version:**

```
export default async function sitemap({
  id,
}: {
  id: number
}): Promise<MetadataRoute.Sitemap> {
  // Google's limit is 50,000 URLs per sitemap
  const start = id * 50000
  const end = start + 50000
  const products = await getProducts(
    `SELECT id, date FROM products WHERE id BETWEEN ${start} AND ${end}`
  )
  return products.map((product) => ({
    url: `${BASE_URL}/product/${id}`,
    lastModified: product.date,
  }))
}
```

**Difference:**

`: MetadataRoute.Sitemap ` to `: Promise<MetadataRoute.Sitemap>`

### Is there any context that might help us understand?

Should be understandable

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

**Comment by balazsorban44** [comment]
You can edit this file here: https://github.com/vercel/next.js/edit/canary/docs/02-app/02-api-reference/04-functions/generate-sitemaps.mdx
