### ISSUE TITLE
Turbo causes a symlinked pages directory to only return 404 errors

### ISSUE THREAD

**Issue by frostme** [vercel/next.js#63006]
### Link to the code that reproduces this issue

https://github.com/frostme/nextjs-turbo-symlink/tree/main

### To Reproduce

1. pnpm prepare (symlinks the pages directory)
2. pnpm dev --turbo (to start the server)
3. Navigate to localhost:3000 and notice a 404 error page
4. Navigate to localhost:3000/example and notice a 404 error page

### Current vs. Expected behavior

While symlinking a directory as the pages directory (for example `ln -s pages-example pages`), while using turbopack (`--turbo`) navigating to any page returns a 404 error. I would expect turbopack to be able to follow the symbolically linked pages just like next does without turbo.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.17
  pnpm: 8.15.2
Relevant Packages:
  next: 14.1.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested my production against the most recent canary version (14.2.0-canary.6) and this was still occurring. I also tested this against all 13.x, and 14.x versions and this experience seems to have been consistently present throughout.

<sub>[PACK-2718](https://linear.app/vercel/issue/PACK-2718/turbo-causes-a-symlinked-pages-directory-to-only-return-404-errors)</sub>

**Comment by timneutkens** [comment]
This has been resolved in https://github.com/vercel/next.js/pull/68195
