### ISSUE TITLE
Docs: No Release Note for 14.1.3

### ISSUE THREAD

**Issue by anatawa12** [vercel/next.js#63085]
### What is the improvement or update you wish to see?

There is no release note for 14.1.3. Could you write release note for 14.1.3 for us?

### Is there any context that might help us understand?

git tag and npm release for 14.1.3 is exists but github release is not exists. For most other releases, there are release notes on github release.

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/releases/tag/v14.1.3

**Comment by balazsorban44** [comment]
https://github.com/vercel/next.js/commits/next-14-1/?since=2024-03-05&until=2024-03-06 here are the changes. will make sure to get some release notes out

**Comment by huozhi** [comment]
Thanks for reporting! We just published the [v14.1.3 release note](https://github.com/vercel/next.js/releases/tag/v14.1.3)
