### ISSUE TITLE
Docs: Adding the page for - https://nextjs.org/docs/messages

### ISSUE THREAD

**Issue by kishoreandra** [vercel/next.js#63086]
### What is the improvement or update you wish to see?

Maybe having a page for the route as it says [messages](https://nextjs.org/docs/messages) which is a 404 now ..

### Is there any context that might help us understand?

I was routed to this page - [hydration warning url](https://nextjs.org/docs/messages/react-hydration-error#solution-3-using-suppresshydrationwarning) and here I could see the path being `/messages/message` .. but there is no such page exist as per the route at all, I mean one would expect to have the messages under `https://nextjs.org/docs/messages` ... 

Thank you and hope it makes sense

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages

**Comment by balazsorban44** [comment]
Hi, we don't currently have a list view for our errors, but I passed this suggestion along to our Docs team, thanks!
