### ISSUE TITLE
Page title is not dynamically updating

### ISSUE THREAD

**Issue by caseyocampo** [vercel/next.js#63083]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Information after running `npx --no-install next info`:

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 21.5.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.14.1
Relevant Packages:
  next: 14.2.0-canary.11 // Latest available version is detected (14.2.0-canary.11).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

blog-starter

### What browser are you using? (if relevant)

Chrome Version 122.0.6261.112 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

The page title is not dynamically updating.

### Expected Behavior

The page title should update when a blog link is clicked.

### To Reproduce

1. Deploy a fresh [starter-blog](https://vercel.com/templates/next.js/blog-starter-kit) template from Vercel

    - Here is my [fresh install on GitHub](https://github.com/caseyocampo/blog-starter-kit-original)
    - Here is the [live example site](https://blog-starter-kit-original.vercel.app/)

4. Run `npm install` then `npm run dev` to start the development environment

    -  Visit the homepage: [http://localhost:3000](http://localhost:3000)
    - Observe the current page title: Next.js Blog Example with Markdown

7. Navigate to a blog post: [Dynamic Routing and Static Generation](https://blog-starter-kit-original.vercel.app/posts/dynamic-routing)

    - Observe that the page title is still: Next.js Blog Example with Markdown

Note: the [official demo of the starter-blog](https://next-blog-starter.vercel.app/) appears to be working as expected.

**Comment by haydenbleasel** [comment]
@caseyocampo Had a quick look, I believe this is just because the exported metadata on the `[slug]/page.tsx` is missing title and description. Only the openGraph data is being updated:

https://github.com/vercel/next.js/blob/canary/examples/blog-starter/src/app/posts/%5Bslug%5D/page.tsx#L56

As such, it's falling back to the parent `layout.tsx` component metadata.

Haven't tested yet but I wager it could be fixed by updating the line I linked to say:

```
return {
    title,
    openGraph: {
      title,
      images: [post.ogImage.url],
    },
  };
```

**Comment by caseyocampo** [comment]
Hey @haydenbleasel, looks like that did the trick! Interesting how the starter template isn't shipped with that. Do you see any reason for it being left out? If not, I can make a PR to include that title property.

**Comment by haydenbleasel** [comment]
Nice one! Yeah it could use a PR to fix. Interesting that there's a difference in how metadata fallbacks work in prod v dev.

**Comment by caseyocampo** [comment]
[PR is up!](https://github.com/vercel/next.js/pull/63110)! Yeah, agreed. Just trying to keep us on our toes I guess 😅

**Comment by caseyocampo** [comment]
Opening issue until [PR to fix](https://github.com/vercel/next.js/pull/63110) is merged.
