### ISSUE TITLE
Turbopack: Can't resolve url in pre-compiled CSS

### ISSUE THREAD

**Issue by kevinfiol** [vercel/next.js#63102]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/uswds-css-turbopack-v9r3xx?file=%2Fapp%2Fglobals.css

### To Reproduce

1. Bootstrap new Next.js app `npx create-next-app@latest` with App Router
2. Add `@uswds/uswds`: `npm install @uswds/uswds`
3. Configure the dev script to use Turbopack: `next dev --turbo`
4. Import the uswds css:
```css
/* app/globals.css */
@import '@uswds/uswds/css/uswds.css';
```
5. Run `npm run dev`.
6. See this error:

![image](https://github.com/vercel/next.js/assets/4752973/2e024e38-9239-4f9c-897e-c6f049b42fe6)

### Current vs. Expected behavior

Bug: Can't use pre-compiled CSS library with Turbopack dev mode

Expected: CSS to compile normally

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Enterprise LTSC 2021
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[PACK-2717](https://linear.app/vercel/issue/PACK-2717/turbopack-cant-resolve-url-in-pre-compiled-css)</sub>

**Comment by ForsakenHarmony** [comment]
@kevinfiol can you try the latest canary release?
