### ISSUE TITLE
Turbopack does not generate a `layout` file if missing

### ISSUE THREAD

**Issue by devjiwonchoi** [vercel/next.js#63103]
### Link to the code that reproduces this issue

https://github.com/devjiwonchoi/repro-next-turbo-create-missing-root-layout

### To Reproduce

1. Install dependencies `pnpm i`
2. Run as turbo by `pnpm dev --turbo`
3. Access `http://localhost:3000`
4. It should generate a `layout` file, but it doesn't
5. For comparison, run `pnpm dev`

### Current vs. Expected behavior

If access `http://localhost:3000` turbopack should generate a `layout` file on the dev server.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.12 // Latest available version is detected (14.2.0-canary.12).
  eslint-config-next: 14.2.0-canary.12
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Ensure to retry the dev test on https://github.com/vercel/next.js/pull/63053 after this fix.

<sub>[PACK-2716](https://linear.app/vercel/issue/PACK-2716/turbopack-does-not-generate-a-layout-file-if-missing)</sub>

**Comment by devjiwonchoi** [comment]
@ForsakenHarmony Hi, due to #63759 should this issue be considered as not planned?

> Unsupported features
>  - Creating a root layout automatically in App Router.
>    - This behavior is currently not supported since it changes input files, instead, an error will be shown for you manually add a root layout in the desired location.

**Comment by timneutkens** [comment]
This has been documented: https://nextjs.org/docs/architecture/turbopack#unsupported-features
