### ISSUE TITLE
Expected polyfills (like Promise.withResolvers) are not inserted

### ISSUE THREAD

**Issue by kodai3** [vercel/next.js#63104]
### Link to the code that reproduces this issue

https://github.com/kodai3/pollyfill-minimal-repo

### To Reproduce

1. Start the application
2. Open `http:localhost:3000` on (iOS) Safari < 17.4 (You won't see the error on the latest Chrome as expected)
3. Click `Click to Find Pollyfill`
4. You see the error `Promise.withResolvers is not a function.`

### Current vs. Expected behavior

I assume it is not properly polyfilled. 

`SWC`'s builtin definitions for `core-js` are updated [here](https://github.com/swc-project/swc/pull/7715) and poyfill for likes of [`Promise.withResolvers`](https://github.com/zloirock/core-js/commit/45bb1c4ff94c84597acf1bc2de767c8d6e3077bc) are added and released at [v1.3.73](https://github.com/swc-project/swc/milestone/430?closed=1). Latest `Next.js` uses `swc_core` v0.87.19 which include [@swc/core@1.3.81 ~ @swc/core@1.3.105](https://swc.rs/docs/plugin/selecting-swc-core#v082x--v087x), so the upade should be applied to the application as well, isn't it ?

I made sure `browserslist` on package.json are respected and [passed to the swc option](https://github.com/vercel/next.js/blob/canary/packages/next/src/build/swc/options.ts#L463-L469) just in case. 
(Even though compiled browserslist version is behind like [this](https://github.com/vercel/next.js/pull/60827) again and there is difference in outputs, it is not related I think)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.3
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Other (Deployed)

**Comment by allicanseenow** [comment]
Would love to have an update for this
