### ISSUE TITLE
Page shows outdated content after `router.refresh()` if multiple suspense boundaries are present

### ISSUE THREAD

**Issue by yannxaver** [vercel/next.js#63126]
### Link to the code that reproduces this issue

https://github.com/yannxaver/nextjs-multiple-suspense

### To Reproduce

Click refresh button

### Current vs. Expected behavior

Outdated content should be fully replaced with new content

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 20.9.0
  npm: 10.4.0
  Yarn: 1.22.19
  pnpm: 8.14.2
Relevant Packages:
  next: 14.2.0-canary.13 // Latest available version is detected (14.2.0-canary.13).
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

**Comment by MostafaWaleed0** [comment]
If you're using data caching mechanisms, ensure that the cache is invalidated or refreshed appropriately when data changes. Stale data in the cache can lead to displaying outdated content.

**Comment by leerob** [comment]
👋 Thanks for opening this. The issue here is that you are using the same `key` for both Suspense boundaries. In general, you shouldn't need to key them anyway. If you remove that, this works as expected.

For a similar example demonstrating fetching and revalidating, you might explore something like this:

```jsx
// page.tsx
import { getUser, getNewYorkTime, getLondonTime } from '@/queries';
import { Await } from '@/components/await';
import { Button } from '@/components/button';
import { Suspense } from 'react';

export default async function Home() {
  const user = await getUser();

  return (
    <div>
      <Suspense fallback={<div>Fallback a...</div>}>
        <Await promise={getNewYorkTime()}>
          {(data) => <div>a: {data}</div>}
        </Await>
      </Suspense>

      <Suspense fallback={<div>Fallback b...</div>}>
        <Await promise={getLondonTime()}>
          {(data) => <div>b: {data}</div>}
        </Await>
      </Suspense>

      <Button />
    </div>
  );
}
```

```jsx
// queries.ts
export const getNewYorkTime = async (): Promise<string> => {
  const response = await fetch(
    'http://worldtimeapi.org/api/timezone/America/New_York'
  );
  const data = await response.json();
  return data.datetime;
};

export const getLondonTime = async (): Promise<string> => {
  const response = await fetch(
    'http://worldtimeapi.org/api/timezone/Europe/London'
  );
  const data = await response.json();
  return data.datetime;
};

export const getUser = async (): Promise<string> => {
  const response = await fetch('https://api.vercel.app/pokemon/1');
  const data = await response.json();
  return data.name;
};
```
```jsx
// button.tsx
'use client';

import { refreshAction } from '@/actions';

export function Button() {
  return (
    <form>
      <button formAction={refreshAction}>Refresh</button>
    </form>
  );
}
```
```jsx
// actions.ts
'use server';

import { revalidatePath } from 'next/cache';

export async function refreshAction() {
  revalidatePath('/');
}
```

**Comment by yannxaver** [comment]
> The issue here is that you are using the same key for both Suspense boundaries.

Why is this an issue? Is this documented anywhere?

> In general, you shouldn't need to key them anyway.

`key` is necessary to show the suspense again on refresh. (as far as I know)

> If you remove that, this works as expected. I was able to confirm this with the reproduction (thanks for providing that).

Based on this, I have removed `key` on the main branch in the reproduction repository and it's not showing the suspense on refresh now. https://github.com/yannxaver/nextjs-multiple-suspense/tree/main

> For a similar example demonstrating fetching and revalidating, you might explore something like this:

I have implemented these code snippets in the `leerob` branch in the reproduction and it's also not showing the suspense on refresh. https://github.com/yannxaver/nextjs-multiple-suspense/tree/leerob
