### ISSUE TITLE
Absolute Imports and Module Path Aliases not working in production with vercel

### ISSUE THREAD

**Issue by Ebrahim-Ramadan** [vercel/next.js#63214]
### Link to the code that reproduces this issue

https://github.com/Ebrahim-Ramadan/ramadanhabitstracking/blob/main/app/contact/page.js

### To Reproduce

 everyting works just fine in dev mode, even while `npx next build` and `npx next start` nothing gets broken, once deploying in vercel, it says it can not resolve some imported absolute modules paths, but I am 100% sure how it works and it's not my first time to deploy a kind of this application with jsconfig.json-based config to work with. it just crashes this time i dunno why

### Current vs. Expected behavior

![image](https://github.com/vercel/next.js/assets/65041082/044d12a6-d8fb-43d9-ab01-0e85fb6263a4)
however this is how jsconfig.json looks like
```
{
  "compilerOptions": {
    "baseUrl": "."
  }
}
```
I also tried 
```
"compilerOptions": {
    "paths": {
      "@/*": ["./*"]
    }
  }
```
and
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["components/*"]
    }
  }
}
```
but these all produced the same issue

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0
Binaries:
  Node: 18.17.1
  npm: 9.5.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.4.20
  eslint-config-next: 13.4.20
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Font optimization (next/font), Module resolution (CJS / ESM, module resolving), Static HTML Export (output: "export")

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by devjiwonchoi** [comment]
Hi, I'd like to look at this, but I assume you fixed it?

**Comment by Ebrahim-Ramadan** [comment]
> Hi, I'd like to look at this, but I assume you fixed it?
Hhh

**Comment by divyenduz** [comment]
I am also experiencing this, when I do `yarn --production` the subsequent "next build" fails. I double checked that all the `devDependencies` are correct (and should be dev dependencies).

**Comment by devjiwonchoi** [comment]
@divyenduz Since I fixed a similar issue, I'd be glad to examine your case. Can you share a repro so I can do so?

**Comment by Ebrahim-Ramadan** [comment]
> Hi, I'd like to look at this, but I assume you fixed it?
yeah it was a 1-day issue with vercel, didn't happen again to me since

**Comment by timmypidashev** [comment]
Started a new day to this issue as well, everything worked perfectly fine yesterday, today nextjs just doesn't want to import anything. Removed all temporary files, reinstalled the project and tried all the above jsconfig/tsconfig options but to no avail. At this point im just going to yarn init a new project and copy paste my existing work into a new next instance :sweat_smile:
