### ISSUE TITLE
App Router metadata not compiled in HTML but is part of scripts

### ISSUE THREAD

**Issue by jahirfiquitiva** [vercel/next.js#63308]
### Link to the code that reproduces this issue

https://github.com/jahirfiquitiva/metadata-example

### To Reproduce

1. Create a new Next.js project
2. Deploy the project.

#### Current:

The page metadata is part of the scripts like this:
```html
<script>self.__next_f.push([1,"9:[[\"$\",\"meta\",\"0\",{\"name\":\"viewport\",\"content\":\"width=device-width, initial-scale=1\"}],[\"$\",\"meta\",\"1\",{\"charSet\":\"utf-8\"}],[\"$\",\"title\",\"2\",{\"children\":\"Create Next App\"}],[\"$\",\"meta\",\"3\",{\"name\":\"description\",\"content\":\"Generated by create next app\"}],[\"$\",\"link\",\"4\",{\"rel\":\"icon\",\"href\":\"/favicon.ico\",\"type\":\"image/x-icon\",\"sizes\":\"16x16\"}],[\"$\",\"meta\",\"5\",{\"name\":\"next-size-adjust\"}]]\n5:null\n"])</script>
```

![Shot 2024-03-14 at 21 50 46@2x](https://github.com/vercel/next.js/assets/10360816/46e6d00e-742f-4529-b295-e4d6758217a0)

#### Expected:
The page should not include this script and the metadata should be injected or included in the page `head` during build time.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.23 // Latest available version is detected (14.2.0-canary.23).
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router, Metadata (metadata, generateMetadata, next/head)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), Vercel (Deployed)

**Comment by gnoff** [comment]
Hi @jahirfiquitiva the metadata is made as part of the static page. The script data you are pointing out is hydration data for React to hydrate the page and make it interactive. You can read more about why Next.js does this here: https://github.com/vercel/next.js/discussions/42170#discussioncomment-8880248
