### ISSUE TITLE
Using `--turbo` with `next-mdx-remote/rsc` throws `ModuleBuildError`

### ISSUE THREAD

**Issue by devjiwonchoi** [vercel/next.js#63318]
### Link to the code that reproduces this issue

https://github.com/devjiwonchoi/repro-next-turbo-mdx-remote-rsc

### To Reproduce

1. `pnpm i`
2. `pnpm dev`
3. Open `http://localhost:3000`

### Current

```sh
Package next-mdx-remote (serverComponentsExtenalPackages or default list) can't be external
The request next-mdx-remote/rsc matches serverComponentsExtenalPackages (or the default list), but it can't be external:
The package seems invalid. require() resolves to a EcmaScript module, which would result in an error in Node.js.
```

### Expected

It should not throw

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:11 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.23 // Latest available version is detected (14.2.0-canary.23).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This issue has been introduced at [`next@14.1.1-canary.64`](https://github.com/vercel/next.js/releases/tag/v14.1.1-canary.64)
Related PR: https://github.com/vercel/next.js/pull/62235

This works when using `webpack` only (`next dev`)

<sub>[PACK-2927](https://linear.app/vercel/issue/PACK-2927/using-turbo-with-next-mdx-remotersc-throws-modulebuilderror)</sub>

**Comment by devjiwonchoi** [comment]
Update: I published [remote-mdx](https://www.npmjs.com/package/remote-mdx), a fork of `next-mdx-remote`, and resolved the output.

IMHO this is still a bug since webpack can handle this package.

**Comment by ctjlewis** [comment]
Thank you @devjiwonchoi. cc @leerob

**Comment by FairyPenguin** [comment]
Any updates on this,

Same issue with  - "next": "14.2.0-canary.56",

**Comment by FairyPenguin** [comment]
Any updates on this,

Same issue with  - "next": "14.2.0-canary.56",


> Update: I published [remote-mdx](https://www.npmjs.com/package/remote-mdx), a fork of `next-mdx-remote`, and resolved the output.
> 
> IMHO this is still a bug since webpack can handle this package.

Thanks @devjiwonchoi  worked for me on  "14.2.0-canary.56"

**Comment by devjiwonchoi** [comment]
@Pilaton https://stackoverflow.com/questions/75831268/next-js-13-server-and-client-components-confusion

**Comment by Pilaton** [comment]
@devjiwonchoi What exactly is this topic supposed to help me with?
`remote-mdx` gives an error when passing an 'Image' component to it.

```jsx
const components = { Image };

<MDXRemote components={components} source={mdx} />
```

I haven't had time yet to see if the problem is in `remote-mdx` or next 14.2

**Comment by bcigdemoglu** [comment]
I get the following error with `remote-mdx`:

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'useState')

Call Stack
f.exports.r.useState
node_modules/.pnpm/remote-mdx@0.0.4_react@18.2.0/node_modules/remote-mdx/dist/index.js (1:31840)
S
node_modules/.pnpm/remote-mdx@0.0.4_react@18.2.0/node_modules/remote-mdx/dist/index.js (1:56687)
```

**Comment by timneutkens** [comment]
@bcigdemoglu can you open a new issue with a reproduction as you're mentioning another library it seems.

**Comment by devjiwonchoi** [comment]
@Pilaton @bcigdemoglu Hi, please open an issue at https://github.com/devjiwonchoi/remote-mdx/issues

**Comment by devjiwonchoi** [comment]
@bcigdemoglu did some update on it, could you try the latest version?

**Comment by devjiwonchoi** [comment]
@Pilaton the error seems to be with mishandling client / server component, not on nextjs or remote-mdx

Open issue w repro to remote-mdx repo, I'll be glad to take a look!

**Comment by dcodesdev** [comment]
Using `next@14.2.3` same issue

**Comment by leerob** [comment]
```js
const nextConfig = {
  transpilePackages: ['next-mdx-remote'],
}

export default nextConfig;
```

^ Temporary workaround, duplicate issue here (https://github.com/vercel/next.js/issues/64525) which is being worked on (open PR https://github.com/vercel/next.js/pull/64918).

**Comment by devjiwonchoi** [comment]
@leerob @ForsakenHarmony I may be wrong but since the package I published `remote-mdx` is [also a Native ESM package](https://www.npmjs.com/package/remote-mdx?activeTab=code), the reason for the error may be different.
 
The error message I received is from the code below when the file is ESM, but the syntax is not ESM.

https://github.com/vercel/next.js/blob/270a9db0567808db5d53e7a18c7be0a4710796e8/packages/next-swc/crates/next-core/src/next_server/resolve.rs#L416-L423
 
Therefore, I suspected having CommonJS syntax on the ESM module (.js file).

Where the output of `next-mdx-remote`'s [`./dist/rsc.js`](https://www.npmjs.com/package/next-mdx-remote?activeTab=code) should be ESM syntax but has CJS syntax in it, resulting an error I believe.

**Comment by papadavis47** [comment]
I ran into this issue when upgrading packages today for my blog . The workaround mentioned by @leerob did the trick for me.
