### ISSUE TITLE
Dynamic routing in Next.js doesn't work (404)

### ISSUE THREAD

**Issue by SR0725** [vercel/next.js#63335]
### Link to the code that reproduces this issue

https://github.com/SR0725/ziphus-alpha/blob/c4d3fc797d86be2b628630f039c2f637caf02c65/apps/web/src/app/card/%5Bid%5D/page.tsx

### To Reproduce

Dynamic routing in Next.js doesn't work 
![image](https://github.com/vercel/next.js/assets/62081739/3c1c1577-e7ae-4f4f-925c-5ae6a10bd8f5)
![image](https://github.com/vercel/next.js/assets/62081739/157ded93-589c-487b-8f6b-9246a2818cc5)

### Current vs. Expected behavior

I tried to create a dynamic routing page.tsx.
But it didn't go to the page.tsx as expected.
Instead, it returns 404.
It's worth mentioning that not-found.tsx also failed.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Education
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.3
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

**Comment by alexkunin** [comment]
Your link does not have `app/card/page.tsx`, but your screenshot has it. Can you update your repo to include missing file, please? Without it, things work as expected, according to [docs](https://nextjs.org/docs/app/building-your-application/routing/colocation):

> [...] even though route structure is defined through folders, a route is not publicly accessible until a page.js or route.js file is added to a route segment.

**Comment by SR0725** [comment]
Sorry, it was my fault. After waking up from sleep and checking my code, I realized that there was a severe error in my setting of next.config.js rewrites, which caused this issue. The problem is solved now! Thank you for your assistance.
