### ISSUE TITLE
Error boundary reset doesn't seem to work

### ISSUE THREAD

**Issue by raulrpearson** [vercel/next.js#63369]
### Link to the code that reproduces this issue

https://github.com/raulrpearson/nextjs-error-reset-test

### To Reproduce

To test Next.js's error boundary components, I created an [error component](https://github.com/raulrpearson/nextjs-error-reset-test/blob/b697f4349c7420aa1ef987d83261dcb768a5f8ed/app/error.tsx) at the top level (not global) following [the docs](https://nextjs.org/docs/app/api-reference/file-conventions/error).

Under the `/throws-sometimes` path, I created [a component](https://github.com/raulrpearson/nextjs-error-reset-test/blob/2c0494b9bc98f6bf9fe5d86e66e46e204943e652/app/throws-sometimes/page.tsx) that throws randomly (50% chance):

```tsx
export const dynamic = 'force-dynamic'

export default function Page() {
  const randomValue = Math.random()
  console.log(randomValue)

  if (randomValue > 0.5) throw new Error('Boom!')

  return <p>All good</p>
}
```

Steps to reproduce:

1. Start application.
2. Navigate to `/throws-sometimes`. If no error is thrown, you'll get the "all good" message.
3. Refresh page until an error is thrown.
4. Click on the "retry" button and see that nothing happens.

Every "retry" click seems triggers a client-side re-render because new errors are logged in the browser's console, but no network requests are triggered, so I can't see how this will ever succeed. I suspect the serialised RSC payload has cached the result of `Math.random()`. This doesn't seem right, specially given that the page component is marked as "force-dynamic".

Vercelly deployed [here](https://nextjs-error-reset-test.vercel.app/throws-sometimes).

### Current vs. Expected behavior

I would expect the `reset` function received by error components to actually retry the RSC re-render.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:06 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.19.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.0-canary.26 // Latest available version is detected (14.2.0-canary.26).
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

**Comment by byseop** [comment]
@raulrpearson 
I think your example component is a server component.
Vercel says "Error components must be Client Components".
Try with 'use client'.

**Comment by poorvasingh04** [comment]
Did you try using `"use client";` in page.tsx?

As per nextjs documentation here - https://nextjs.org/docs/app/building-your-application/rendering/client-components

> `"use client" is used to declare a boudary between a Server and Client Component modules. This means that by defining a "use client" in a file, all other modules imported into it, including child components, are considered part of the client bundle.`

> `"use client" doesn't need to be defined in every component that needs to be rendered on the client. Once you define the boundary, all child components and modules imported into it are considered part of the client bundle.`

**Comment by coffeecupjapan** [comment]
@raulrpearson 

I guess you want to render `page.tsx` in server side not client side, but `reset` function only re-render the Error boundary's content, and therefore server component generated in server side only re-render the same result.

> An error component can use the reset() function to prompt the user to attempt to recover from the error. When executed, the function will try to re-render the Error boundary's contents. If successful, the fallback error component is replaced with the result of the re-render.

see doc https://nextjs.org/docs/app/building-your-application/routing/error-handling#recovering-from-errors
and code https://github.com/vercel/next.js/blob/0c1a531e1d6a1831cb261bc2fbd0f17816e68bef/packages/next/src/client/components/error-boundary.tsx#L108-L110

I think you have to make api in backend somehow and add `use client` in your `page.tsx` and fetch the server result.

**Comment by poorvasingh04** [comment]
Another workaround could be to use `useRouter()` from `next/navigation` and call `router.refresh()` in useEffect in `error.tsx`

**Comment by Atliac** [comment]
You can use `window.location.reload()`, `router.replace()`, or `router.push()`, but **not** `router.refresh` to reset the page.

```
'use client';
import { useRouter, usePathname } from "next/navigation";
import { useEffect } from "react";
export default function Error({
    error,
    reset,
}: {
    error: Error & { digest?: string }
    reset: () => void
})
{
    const router = useRouter();
    const path_name = usePathname();
    useEffect(() =>
    {
        // note, `return router.refresh;` doesn't work
        // because server-side components are cached, causing the error component to re-render with outdated data before the refresh completes.
        return () => { router.replace(`${path_name}?t=${Date.now()}`); }; // or router.push(`${path_name}?t=${Date.now()}`);
    }, [router, path_name]);
    return (
        <>
            <p>
                Error: {error.message}<br />
            </p>
            <p>
                <button onClick={reset}>Reset by Soft Navigation</button><br />
                <button onClick={() => { window.location.reload(); }}>Reset by Hard Navigation</button>
            </p>
        </>
    );
}
```

**Comment by raulrpearson** [comment]
Thanks for everyone trying to help. I asked about this in the Build UI Discord and Ryan published a great [video worth watching](https://www.youtube.com/watch?v=idEL0dv2V1A) with the best explanation/approach for this that I've found.

As it seems this is the intended behaviour and not a bug, I'll close the issue. Maybe this could be explained better in the Next.js docs. Feel free to reopen this issue or open a new one if you feel strongly about that and want to ask for it.

**Comment by Atliac** [comment]
You need to call the `startTransition()` function to re-render both client-side and server-side components in a synchronized manner. 

1. `reset()` re-renders only the client-side components.
1. `router.refresh()` re-renders only the server-side components.
1. `startTransition()` wraps both `reset()` and `router.refresh()`, ensuring that both client-side and server-side components are re-rendered together. 

```
'use client';
import { useRouter } from "next/navigation";
import { startTransition } from "react";
export default function Error({
    error,
    reset,
}: {
    error: Error & { digest?: string }
    reset: () => void
})
{
    const router = useRouter();
    function handleReset()
    {
        startTransition(() =>
        {
            // calling order does not matter
            reset();
            router.refresh();
        });
    }
    return (
        <>
            <p>
                Error: {error.digest}
            </p>
            <p>
                <button onClick={handleReset}>Reset</button>
            </p >
        </>
    );
}
```
