### ISSUE TITLE
pdfjs-dist failed to load its dependency - Module not found: Package path . is not exported from package /node_modules/pdfjs-dist/node_modules/path2d-polyfill

### ISSUE THREAD

**Issue by hpardess** [vercel/next.js#63385]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/pdf-viewer-v52xpl

### To Reproduce

```
"use client"
import { useRef, useState } from 'react';
// import * as PDFJS from "pdfjs-dist";
import * as PDFJS from 'pdfjs-dist/build/pdf.min.mjs';

const TestPage = () => {
const [pdfPages, setPdfPages] = useState([]);

  const displayImage = async() => {
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');

    const uint8Array = pdfPages[0];
    console.log(uint8Array)
    const pdfDoc = await PDFJS.getDocument(uint8Array);

    // Get the first page of the PDF document.
    const page = await pdfDoc.getPage(1);

    // Render the page to an image.
    const imageData = await page.render({
        canvasFactory: new PDFJS.CanvasFactory(),
    });

    // Put the image data on the canvas.
    ctx.putImageData(imageData, 0, 0);

    // Display the canvas.
    ctx.drawImage(canvas, 0, 0);
  };

return (
    <section className="pb-[120px] pt-[150px]">
<canvas ref={canvasRef} />
</section>
  );
};

export default TestPage;

```

Here is the error

```

 ⨯ ./node_modules/pdfjs-dist/build/pdf.min.mjs:21:262714
Module not found: Package path . is not exported from package /project/node_modules/pdfjs-dist/node_modules/path2d-polyfill (see exports field in /project/node_modules/pdfjs-dist/node_modules/path2d-polyfill/package.json)

https://nextjs.org/docs/messages/module-not-found
```

<img width="584" alt="Screenshot 2024-03-17 at 1 19 09 PM" src="https://github.com/vercel/next.js/assets/6196491/e48ef2ac-1db8-4a50-ac7f-11f735e4d86e">

### Current vs. Expected behavior

pdfjs-dist failed to load its dependency

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023;
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

<sub>[NEXT-3323](https://linear.app/vercel/issue/NEXT-3323/pdfjs-dist-failed-to-load-its-dependency-module-not-found-package-path)</sub>

**Comment by mmo80** [comment]
Check out [my repo](https://github.com/mmo80/pdfja-nextjs-bug) for similar bug. Got it working with api route but throws error when executing same code as a server action.

**Comment by timneutkens** [comment]
![CleanShot 2024-05-06 at 08 49 26@2x](https://github.com/vercel/next.js/assets/6324199/c1d37191-8551-4737-b08c-4e8f06532918)

Seems this package never worked? Looking at the minified code there's a lot of highly dynamic `import()` calls. Seems it's meant to be loaded through a `<script>` tag or something like that, not being bundled by a bundler.

**Comment by timneutkens** [comment]
Did some more digging and created a proper reproduction of what I think you mean with this issue: https://codesandbox.io/p/devbox/pdf-viewer-forked-vcf42f?file=%2Fnext.config.js%3A4%2C65

It's related to top level await breaking module loading in React Server Components.

**Comment by timneutkens** [comment]
Opened a separate issue for the Turbopack issue: https://github.com/vercel/next.js/issues/65406

**Comment by gurkerl83** [comment]
It seems PDF.js recognized issues with using top-level await in certain environments and has opted out of this strategy. For more information, please see here https://github.com/mozilla/pdf.js/pull/18051

Maybe this helps, 
Thx!

**Comment by samcx** [comment]
> It seems PDF.js recognized issues with using top-level await in certain environments and has opted out of this strategy. For more information, please see here https://github.com/mozilla/pdf.js/pull/18051

Thank you for the update @gurkerl83! Closing this issue.
