### ISSUE TITLE
CSS file is not loaded when there are Parallel Routes with [...catchAll] present.

### ISSUE THREAD

**Issue by msundberg** [vercel/next.js#63465]
### Link to the code that reproduces this issue

https://github.com/msundberg/css-bug

### To Reproduce

1. Start the application in development mode.
2. Load the sub-page at http://localhost:3000/sub in your browser (tested with Chrome, both Windows and MacOs).
3. Click "Home" link. 
4. Root page is loaded but without page.css (no read background).
5. Reload page and page.css will be loaded (red background),

### Current vs. Expected behavior

Current behavior is that the page is loaded without page.css when using "soft navigation". A "hard reload" will load the CSS.
Expected behavior is that the CSS should be loaded both using "soft navigation" and on full reload.

Everything works as expected If the @fizbin/[...catchAll] folder is removed.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024
  Available memory (MB): 7938
  Available CPU cores: 4
Binaries:
  Node: 20.10.0
  npm: 10.2.5
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.0-canary.30 // Latest available version is detected (14.2.0-canary.30).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by G3EORG3E** [comment]
I am experiencing the same issue when using parallel routes and CSS modules. When navigating on the client side, the CSS sometimes fails to load. This can affect the entire page or just some sublayouts. This issue make this parallel routes feature totally unusable...

**Comment by lionkeng** [comment]
@msundberg 
I forked your example. 
Would this workaround work for you? See here: https://github.com/msundberg/css-bug/compare/main...lionkeng:css-bug:main
