### ISSUE TITLE
Using open graph metadata results in duplicate metadata for twitter

### ISSUE THREAD

**Issue by mysticflute** [vercel/next.js#63489]
### Link to the code that reproduces this issue

https://github.com/mysticflute/duplicate-metadata-bug

### To Reproduce

1. Start the application.
2. View the open graph and twitter `meta` tags in the `head`.
3. Additional duplicate twitter meta tags are automatically added, even though they are not in the source code.

### Current vs. Expected behavior

The [official twitter card documentation](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup) specifies that it will use the values from `og:title` and `og:description` meta tags, among others, if `twitter:title` and/or `twitter:description` are not specified, respectively.

1)
When you add `og:title`, Next.js automatically adds `twitter:title` to the html output with the same value, but this is unnecessary duplication.

2)
If you have a regular meta description (`<meta name="description" .../>`), then add `og:description`, Next.js automatically adds a `twitter:description` with the value from the regular meta description, *not* the open graph one. This is unintuitive, and there's no way to avoid it besides duplicating the `og:description` value into the `twitter:description`, resulting in unnecessary duplication in both the source code and the output.

Ultimately, I should be able to start by specifying open graph values, then selectively override or specify additional twitter values only where necessary. This results in cleaner markup. Next.js is automatically adding duplication preventing this from being possible. This should apply to all metadata, including images.

<img width="762" alt="Screenshot 2024-03-19 at 14 03 24" src="https://github.com/vercel/next.js/assets/327116/902dcbdb-6e3f-4253-8f79-5a964027328a">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Sun Dec 17 22:12:45 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.11.1
  npm: 10.4.0
  Yarn: 1.22.22
  pnpm: 8.15.5
Relevant Packages:
  next: 14.2.0-canary.31 // Latest available version is detected (14.2.0-canary.31).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata (metadata, generateMetadata, next/head)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

<sub>[NEXT-3073](https://linear.app/vercel/issue/NEXT-3073/using-open-graph-metadata-results-in-duplicate-metadata-for-twitter)</sub>

**Comment by coffeecupjapan** [comment]
@mysticflute 
I think for second case, there is a way to patch.

@huozhi 

Hi. I want to ask one thing since it is related to https://github.com/vercel/next.js/pull/57857.
For second case of this issue, 

> If you have a regular meta description (<meta name="description" .../>), then add og:description, Next.js automatically adds a twitter:description with the value from the regular meta description, not the open graph one. This is unintuitive, and there's no way to avoid it besides duplicating the og:description value into the twitter:description, resulting in unnecessary duplication in both the source code and the output.

I think we can add function like below in `postProcessMetadata`. And this could help prioritize `openGraph title and description` information over `normal meta title and description` information, prevent developers from adding duplicate `description and title` for twitter and openGraph.

```javascript
function inheritFromMetadataAndOpenGrapth(
  metadata: ResolvedMetadata,
  twitterTarget: (WithTitle & WithDescription) | null,
  openGraphTarget: (WithTitle & WithDescription) | null
) {
  if (twitterTarget && openGraphTarget) {
    if (!hasTitle(twitterTarget) && hasTitle(openGraphTarget)) {
      twitterTarget.title = openGraphTarget.title
    } else if (!hasTitle(twitterTarget) && !hasTitle(openGraphTarget)) {
      twitterTarget.title = metadata.title
    }
    if (!twitterTarget.description && openGraphTarget.description) {
      twitterTarget.description = openGraphTarget.description
    } else if (!twitterTarget.description && metadata.description) {
      twitterTarget.description = metadata.description
    }
  }
}
```

**Comment by huozhi** [comment]
Yea agree the 2nd one make sense, could be an improvement for the metadata title/description fallback strategy. Let twitter title/desc fallbacks to opengraph ones first, if they're still not present then fallback to metadata top ones
