### ISSUE TITLE
TypeError: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by AdamZajlerDDH** [vercel/next.js#63517]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/fast-cdn-x3g4e8?file=%2Fpackage.json

### To Reproduce

Here is a minimum reproduction on codesandbox (from https://github.com/vercel/next.js/issues/36422): https://codesandbox.io/s/fast-cdn-x3g4e8

### Current vs. Expected behavior

Provide support for `object.hasOwn`

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #25-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 14:58:39 UTC 2024
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.4
      eslint-config-next: 13.2.4
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

We detect over 354K errors in Sentry.
![image](https://github.com/vercel/next.js/assets/162283251/6181826b-1537-4049-a357-2eda694c06ee)
![image](https://github.com/vercel/next.js/assets/162283251/a27947f5-9153-400b-b8df-ecb949f722de)
on older browsers that dont support `object.hasOwn`. 

Is there way that you can add polyfill for this? Or is it avilable in newest versions of Next, than 13.2.4?

**Comment by balazsorban44** [comment]
Hi, the latest versions of Next.js (14.1.4) as of writing has this included: https://github.com/vercel/next.js/pull/60437

we don't packbort features/minor fixes like this though, mostly only security related patches. Please upgrade to the latest of Next.js!
