### ISSUE TITLE
next dev --turbo errors when turborepo internal package imports node native module

### ISSUE THREAD

**Issue by dbrxnds** [vercel/next.js#63510]
### Link to the code that reproduces this issue

https://github.com/dbrxnds/turbo-crypto-repro

### To Reproduce

1. Start the application using `next dev --turbo`
2. Open app in web browser
3. Should see error right away

### Current vs. Expected behavior

It currently gives an import error, even though the code does work. Strangely it also seems to happen without using `--turbo` in the reproduction, this does not happen in our own codebase. There it works without turbopack.

In our own application this same issue occurs for Prisma imports that come from our `mysql` internal workspace. So i'm not sure if its necessarily related to node native modules, but this allowed for the easiest/most minimal reproduction.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.15.4
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```
EDIT: Updated `next` from 14.1.3 to 14.1.4 to make sure it still occured. It does.

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This has been an issue for us basically ever since we have tried to use turbopack for dev. Early on we assumed it was just due to turbopack maturity so we waited a while and tried again. At this point we feel like it may be related to something else.

**Comment by balazsorban44** [comment]
The issue seems to be unrelated to Turbopack/Turborepo. 

https://github.com/dbrxnds/turbo-crypto-repro/blob/63f82a9856925bdbe35a6c4d1c7bc86bce99c5a1/packages/ui/src/button.tsx#L4

here, you are importing Node.js internals in a client component, which is not allowed, as it will run in the browser as well.

If you only need `randomUUID()`, you can just call `crypto.randomUUID()` directly without any Node.js import, as it's available in all major browsers already.

> In our own application this same issue occurs for Prisma imports that come from our mysql internal workspace. So I'm not sure if it's necessarily related to node native modules, but this allowed for the easiest/most minimal reproduction.

I would check the same, make sure you aren't using Prisma in a client component directly. Without seeing the code it's hard to make further assumptions though.

**Comment by dbrxnds** [comment]
Hi @balazsorban44, thank you for the response.

I updated the repo to better represent the issue we have. We still use the pages router, and sometimes import our prisma client instance into a page file to use in `getServerSideProps`. I've updated the repo to reflect this.

Would you like me to open a new issue or?

**Comment by dbrxnds** [comment]
Hi @balazsorban44, thank you for your response!

I updated the repo to better reflect our exact situation. For example, we still use the pages router and API routes. 
If you run the updated repo using webpack it works, turbopack it doesn't. No longer importing any server stuff in the client, just the API route that is being called by the button.
