### ISSUE TITLE
`next dev --turbo` errors when importing Prisma using turborepo internal package

### ISSUE THREAD

**Issue by dbrxnds** [vercel/next.js#63566]
I opened an issue previously using the same reproduction repository, but have since updated it to better reflect our actual issue.

### Link to the code that reproduces this issue

https://github.com/dbrxnds/turbo-crypto-repro

### To Reproduce

1. Run `pnpm generate` inside `packages/database` 
2. Start the application using next dev --turbo
3. Open app in web browser
4. Click button
5. See error in terminal

### Current vs. Expected behavior

It currently gives an import error when triggering the API route.
```bash
TypeError: __TURBOPACK__imported__module__$5b$project$5d2f$packages$2f$database$2f$src$2f$client$2e$ts__$5b$api$5d$__$28$ecmascript$29$__$7b$exports$7d$__.PrismaClient is not a constructor
```

I would expect this to work without an error, as it does when not using `--turbo`

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.15.4
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by dbrxnds** [comment]
Update: So `canary` seems to fix the issue in the reproduction. But the error still occurs for us in our main project, although slightly better error message: 
```bash
TypeError: {imported module [project]/packages/mysql/src/index.ts [ssr] (ecmascript) <exports>}.PrismaClient is not a constructor
```

![image](https://github.com/vercel/next.js/assets/32268383/330c902a-87c4-49c2-9680-0652b62504c7)

Still looking to see if we can reproduce it

**Comment by dbrxnds** [comment]
Last update: We got turbopack working! Final issue required us to export `PrismaClient` seperately. So:
```ts
// before
export * from "@prisma/client"

// after
export * from "@prisma/client"
export { PrismaClient } from "@prisma/client"
```

**Comment by timneutkens** [comment]
That `export *` issue is also resolved on next@canary. Just verified it on your reproduction: https://codesandbox.io/p/github/dbrxnds/turbo-crypto-repro/csb-jfvmvz/draft/vigorous-platform?file=%2Fpackages%2Fdatabase%2Fprisma%2Fschema.prisma%3A8%2C5

When using Turbopack it's recommended to use next@canary until we release the release candidate (which will happen soon) as there's hundreds of fixes on the canary branch for Turbopack.
