### ISSUE TITLE
Docs: Add RSS support for the blog

### ISSUE THREAD

**Issue by kuchta** [vercel/next.js#63589]
### What is the improvement or update you wish to see?

Please add RSS to the blog

### Is there any context that might help us understand?

No

### Does the docs page already exist? Please link to it.

https://nextjs.org/blog

**Comment by devjiwonchoi** [comment]
Hi, I'd recommend opening a `discussion` at https://github.com/orgs/vercel/discussions for more accurate response!

**Comment by amyegan** [comment]
The feed is currently available at https://nextjs.org/feed.xml

**Comment by devjiwonchoi** [comment]
Awesome, thank you!

**Comment by kuchta** [comment]
Thank you @amyegan ❤️ It's strange I can't find it linked in the page...
