### ISSUE TITLE
Redirect doesn't work for API route handler

### ISSUE THREAD

**Issue by damianfilipek81** [vercel/next.js#63756]
### Link to the code that reproduces this issue

https://github.com/damianfilipek81/next-redirect-problem

### To Reproduce

1. Start the application using pnpm dev
2. We're doing fetch inside `page.tsx` 
```ts
  useEffect(() => {
    (async() => await fetch("http://localhost:3000/api/getExample"))()
  }, [])
  ```
  so we should be redirected to `/page1` since in `getExample` we're doing redirection
```ts
import { redirect } from "next/navigation";

export async function GET() {
  redirect("/page1")
}
```

### Current vs. Expected behavior

Expected behavior: We should be redirected to /page1 since we're using `redirect(/page1)` method inside `GET` `src/app/api/getExample/route.ts`.
Current behavior: We can see in network devtool that `page1` is actually fetched 
<img width="830" alt="image" src="https://github.com/vercel/next.js/assets/75132129/defe33a8-cdc7-4c7f-8cc7-980c00c7200e">
but nothing happens, website stays on `/`

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.21
  pnpm: 8.10.5
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

I tested this on `14.1.0` `14.1.4` and `14.2.0-canary.44` and it doesn't work on all of them.

**Comment by taipo1** [comment]
I could reproduce this. 

a work for now might be to use the 
`NextResponse.redirect("/page1", statusCode)`

**Comment by damianfilipek81** [comment]
Actually `NextResponse.redirect("http://localhost:3000/page1", 307)` doesn't work either. For now i couldn't find any way to redirect from API route handler.

**Comment by taipo1** [comment]
ah my bad can confirm

**Comment by nicnocquee** [comment]
I think that's how fetch works. You're supposed to read the response and get the redirected URL.

```typescript
useEffect(() => {
    ;(async () => {
      const resp = await fetch('/api/getExample')
      console.log(resp.redirected ? resp.url : 'Not redirected')
    })()
  }, [])
``` 

To see that the `redirect` works in the route handler, go to the `http://localhost:3000/api/getExample` directly from the browser. 

If you want to be redirected from `useEffect`, you should use `useRouter`:

```typescript
import { useRouter } from 'next/navigation'


  const router = useRouter()
  useEffect(() => {
    router.push('/api/example')
  }, [router])
```

**Comment by ajin-iqness** [comment]
> Actually `NextResponse.redirect("http://localhost:3000/page1", 307)` doesn't work either. For now i couldn't find any way to redirect from API route handler.

I have this similar weird behaviour after NextJs been updated from `14.1.4` to `14.2.1` when redirecting from `/login` based on `auth` status using below code in my `middleware.ts`. I do use App Router.

```
const dashboardUrl = new URL('/dashboard/overview', nextUrl)
return NextResponse.redirect(dashboardUrl)
```

Dashboard->Overview page has been loaded on the screen but the url has not been updated on browser. It stayed on `/login`. If I reload the page, url is getting updated automatically to `/dashboard/overview`. I couldn't fix this but when downgraded back to `14.1.4`, issue is been automatically resolved. Strange.

**Comment by Kappaequiscu** [comment]
> I have this similar weird behaviour after NextJs been updated from `14.1.4` to `14.2.1` when redirecting from `/login` based on `auth` status using below code in my `middleware.ts`. I do use App Router.

I update from 14.0.4 to 14.2.3 andim having this issue. When i logout, the page does redirect to login but the url doesn't change.

```typescript
const intlMiddleware = createIntlMiddleware({
  locales,
  defaultLocale: "ca",
  localePrefix: "always",
});

const testPagesRegex = (pages: string[], pathname: string) => {
  const regex = `^(/(${locales.join("|")}))?(${pages
    .map((p) => p.replace("/*", ".*"))
    .join("|")})/?$`;
  return new RegExp(regex, "i").test(pathname);
};

const handleAuth = async (req: NextRequest, isAuthPage: boolean, isProtectedPage: boolean) => {
  const session = await auth();
  const isAuth = !!session?.user;

  if (!isAuth && isProtectedPage) {
    let from = req.nextUrl.pathname;
    if (req.nextUrl.search) {
      from += req.nextUrl.search;
    }
    return NextResponse.redirect(new URL(`/auth/login?from=${encodeURIComponent(from)}`, req.url));
  }

  if (isAuth && isAuthPage) {
    const url = req.nextUrl.clone();
    const fromValue = url.searchParams.get("from");
    return NextResponse.redirect(new URL(fromValue ?? "/home", req.nextUrl));
  }

  return intlMiddleware(req);
};

export default async function middleware(req: NextRequest) {
  const isAuthPage = testPagesRegex(authPages, req.nextUrl.pathname);
  const isProtectedPage = testPagesRegex(protectedPages, req.nextUrl.pathname);

  return await handleAuth(req, isAuthPage, isProtectedPage);
}

export const config = {
  matcher: ['/((?!.+\\.[\\w]+$|_next).*)', '/', '/(api|trpc)(.*)',],
};
```

**Comment by LJ950** [comment]
I am having this problem in version `14.0.3`. When fetching the route below the browser network shows the 307 `Temporary Redirect` to the correct location however the page doesn't reload at the new location.

```
import { redirect } from "next/navigation";

export async function POST(request: Request): Promise<Response> {
  try {
     // do stuff
  } catch (error) {
    console.log(error);
    throw new Error("Error logging in");
  }

  redirect("/members/dashboard");
}
```

**Comment by leerob** [comment]
I am not able to reproduce on the latest `canary`:

```ts
import { redirect } from 'next/navigation';

export async function GET(request: Request) {
  redirect('/test');
}
```

However, this does cause an issue it seems:

```ts
export async function GET(request: Request) {
  return Response.redirect('/test');
}
```

Noted here: https://github.com/vercel/next.js/issues/67966
