### ISSUE TITLE
Request for docs/guide: How to share data from components in two different routes in next14 app router ?

### ISSUE THREAD

**Issue by manacy-keyvalue** [vercel/next.js#63762]
### What is the improvement or update you wish to see?

Need clear documentation in nextjs 14 approuter on how to handle scenarios where data needs to be shared between components in different routes

### Is there any context that might help us understand?

I'm using next 14 app router. I have a use-case where i need to share data from components in two different routes. In page router or react, we used to keep the data in global store and re-use that data. But with app router in next 14, I came across documentation where we are only supposed to create one store per request.
"No global stores - Because the store should not be shared across requests, it should not be defined as a global variable. Instead, the store should be created per request."
But the use-case still exists in my project. How can I handle this use-case adhering to the nextjs docs to follow single store per request.

The use case involves a form-filling feature (Feature A) where users need to select an item from a separate route. Upon selecting an item, users return to the form in Feature A, where the selected item needs to be populated along with any previously entered form data. This requires seamlessly transferring data between routes and preserving form state across navigations.

How can I maintain form data and a selected item across route navigations in Next.js 14 without violating the recommendation of a single store per request ?

Related discussion thread:
https://github.com/vercel/next.js/discussions/63761

**Comment by balazsorban44** [comment]
There are multiple ways of achieving this.

Note, there is nothing inherently wrong with using some client components and global context, (ie. using React Query). Depending on the data being passed between routes, you can also use search params, `sessionStorage`, a temp. entry in a database (similar to a "cart" feature), etc.

It's hard to give a project-specific recommendation though, so this is best to keep as a discussion, which you already opened.
