### ISSUE TITLE
Docs: localized sitemap example is broken

### ISSUE THREAD

**Issue by FelDev** [vercel/next.js#63764]
### What is the improvement or update you wish to see?

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#generate-a-localized-sitemap

The localized sitemap example looks like this
```ts
import { MetadataRoute } from 'next'
 
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://acme.com',
      lastModified: new Date(),
      alternates: {
        languages: {
          es: 'https://acme.com/es',
          de: 'https://acme.com/de',
        },
      },
    },
    {
      url: 'https://acme.com/about',
      lastModified: new Date(),
      alternates: {
        languages: {
          es: 'https://acme.com/es/about',
          de: 'https://acme.com/de/about',
        },
      },
    },
    {
      url: 'https://acme.com/blog',
      lastModified: new Date(),
      alternates: {
        languages: {
          es: 'https://acme.com/es/blog',
          de: 'https://acme.com/de/blog',
        },
      },
    },
  ]
}
```

If I copy paste that example, it doesn't work.
> Object literal may only specify known properties, and 'alternates' does not exist in type '{ url: string; lastModified?: string | Date | undefined; changeFrequency?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never" | undefined; priority?: number | undefined; }'
![Screenshot 2024-03-27 at 09 34 36](https://github.com/vercel/next.js/assets/17578204/6350611c-301a-4bae-b45f-3b783fa5aec1)

Also, when selecting "javascript" instead of "typescript", the example disapears.

![Screenshot 2024-03-27 at 09 36 20](https://github.com/vercel/next.js/assets/17578204/a38aad3f-2d77-4be5-bf8d-db066c000e9b)

### Is there any context that might help us understand?

I literally copy pasted the example from the docs.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#generate-a-localized-sitemap

**Comment by canisminor1990** [comment]
+1

**Comment by seob171** [comment]
https://github.com/vercel/next.js/releases/tag/v14.2.0-canary.34

**Comment by balazsorban44** [comment]
Closing as per https://github.com/vercel/next.js/issues/63764#issuecomment-2024598358, which is the correct answer to this issue.

**Comment by Almuhanad-1** [comment]
> you have to upgrade next.js version
> 
> https://github.com/vercel/next.js/releases/tag/v14.2.0-canary.34

how to prevent dependency conflicts after updating to  "next": "^14.2.0-canary.52"?
I get conflicts with "@next/third-parties" and "next-intl"

**Comment by abdullahzt** [comment]
@Almuhanad-1 

You need to override the dependency for those packages

```
  "overrides": {
    "next-intl": {
      "next": "14.2.0-canary.34"
    },
    "@next/third-parties": {
      "next": "14.2.0-canary.34"
    }
  },
```

For me this does solve the npm i error, but I am not able to get the sitemap.
