### ISSUE TITLE
Docs: Add `Component` to structure

### ISSUE THREAD

**Issue by guylepage3** [vercel/next.js#63769]
### What is the improvement or update you wish to see?

First of all. This is hands down the best doc structure recommendations I've ever seen. 👏🏻 Amazing work!

> https://nextjs.org/docs/getting-started/project-structure

Having said that, there seems to be one item, the `component` folder and files structure, that imo should be added as well.

I currently am noticing folks colocating more and more their `components` into their `app` folder. I feel as though this should be the `default` recommendation and if there are any corner cases they can be mentioned below the structure recommendation.

Also, I have noticed about a 50/50 split of folks placing an `index.ts` file in their component folder and exporting from there.

I'm completely impartial to how this is handled but a recommendation from the `Structure` page would be extremely helpful.

Let's get this rolling and then I'll do a quick PR.

### Is there any context that might help us understand?

The above description describes the issue and possible solution.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/getting-started/project-structure

**Comment by balazsorban44** [comment]
Hi, thanks for the suggestion, but the linked page is aimed to give you a description of the Next.js conventions/required file structure. Having a `components` folder is not required and might confuse if we recommend it. I.e. you can also colocate your components right next to `page.tsx` files as well, as these are ignored by Next.js.

Whether you want to use a `components` folder should remain a project-level consideration.
