### ISSUE TITLE
Update the swc doc, not functioning well on Termux 

### ISSUE THREAD

**Issue by Habib-0007** [vercel/next.js#63760]
### What is the improvement or update you wish to see?

I would like to see an update on the swc on how to specifically setup swc on Android phone through Termux, it's not making my next app start and there's no good resource talking about it.

### Is there any context that might help us understand?

This is what it says when you try to run a nextjs app on Termux :

![Screenshot_20240314-110434](https://github.com/vercel/next.js/assets/109099706/8a425a3d-3235-4b9c-8e54-176369ceccb8)
![Uploading Screenshot_20240314-113103.png…]()

**Comment by leerob** [comment]
Hey there. We do not currently have plans to support Termux on Android. If that changes in the future, we will updated the documentation to reflect this :pray:
