### ISSUE TITLE
`loading.tsx` cannot be displayed properly in parallel routes.

### ISSUE THREAD

**Issue by caohonghai** [vercel/next.js#63793]
### Link to the code that reproduces this issue

https://github.com/caohonghai/parallel-routes-loading

### To Reproduce

- `pnpm i`
- `pnpm dev`
- `http://localhost:3000/dashboard`

### Current vs. Expected behavior

# Current

Next.js does not render `@team/loading.tsx` and `@analytics/loading.tsx`

# Expected

I expect rendering `@team/loading.tsx` and `@analytics/loading.tsx` when entering `/dashboard`

### Provide environment information

```bash
Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 7.11.0
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by Marius-Adam** [comment]
create route group inside parallel slot

```
├── @hero
|   ├── (group)
|   |   └── page.tsx
|   ├── loading.tsx
└── layout.tsx
```

**Comment by ztanner** [comment]
Hi, it looks like this issue has been fixed on our latest canary. Here's a quick video of me running the app:

https://github.com/vercel/next.js/assets/1939140/8530ed04-8515-4b59-97df-ff93880af708

Please let us know if you're having any issues making it work after upgrading, and we can take a look!
