### ISSUE TITLE
Memory Leak in Edge Runtime

### ISSUE THREAD

**Issue by floatingdino** [vercel/next.js#63796]
### Link to the code that reproduces this issue

https://github.com/floatingdino/nextjs-edge-memory-bug

### To Reproduce

1. Run test command `npm run test`
2. (Optionally) Turn off edge runtime on `app/page.js` and run test command again

### Current vs. Expected behavior

When requesting pages in edge runtime, I expect the memory footprint to remain consistent or self-correct spikes as shown when using the Node runtime

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: 8.10.2
Relevant Packages:
  next: 14.1.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

App Router, Middleware / Edge (API routes, runtime)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

Edge runtime memory usage:
<img width="841" alt="Screenshot 2024-03-28 at 2 15 45 pm" src="https://github.com/vercel/next.js/assets/3883037/170a88d2-419d-4a57-9f48-51bea674722c">
Node runtime memory usage:
<img width="823" alt="Screenshot 2024-03-28 at 2 15 51 pm" src="https://github.com/vercel/next.js/assets/3883037/cb182dce-3833-43f4-89b1-ac7124a9f74e">

When deploying on Vercel, this seems to be fine (I assume each request is serverless and the memory footprint is completely cleansed once the connection is closed) however, when deploying with Docker, this inevitably causes OOM issues. This doesn't seem to be a Docker-specific issue as running with node locally also exhibits memory inflation.

**Comment by chane81** [comment]
@floatingdino 
I'm not sure if this will help, but in my case, I was using Next.js version 14.2.2, Node.js 18 (in a Docker environment), and middleware (with edge runtime). While other services using Next.js 14 didn't experience memory leaks, the environment using middleware did show memory leak issues.
After conducting various tests, I resolved the memory leak issue by changing the Node version in Docker from 18 to 22.11.0 (LTS).

[before] - docker node.js version 18
![CleanShot 2024-11-11 at 13 09 36@2x](https://github.com/user-attachments/assets/906a6c98-d0f4-4201-afae-21d579e5266e)

[after] - docker node.js version 22.11.0 alpine
![CleanShot 2024-11-11 at 13 11 13@2x](https://github.com/user-attachments/assets/f9d7a0d3-4d84-4df2-beda-9e761da818ba)

![CleanShot 2024-11-11 at 13 12 56@2x](https://github.com/user-attachments/assets/fe0cf380-2cce-4c02-beca-1506f3a9fdf1)

**Comment by Fonger** [comment]
We had the same issue as @chane81 described.

Are you using node.js 20.16.0 or 20.17.0? If so, please try 20.18.0, or 20.15.1
There's some bugs in underlying undici fetch in these node.js versions.

https://github.com/nodejs/node/issues/54274

**Comment by floatingdino** [comment]
Thanks @chane81 @Fonger for your input, upgrading my environment from node v20.10 to v22.11 solved the memory leak in my environment.
