### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for '__next_img_default' in undefined

### ISSUE THREAD

**Issue by ojj1123** [vercel/next.js#63803]
### Link to the code that reproduces this issue

https://github.com/ojj1123/next-custom-loader-issue-repro

### To Reproduce

1. pnpm install
2. pnpm dev
3. and then you can see the issue below:

## Expected behavior
I want to configure the image loader globally.
[Nextjs docs](https://nextjs.org/docs/pages/api-reference/components/image#loaderfile) describes that I can configure the image loader at `next.config.js`:
```js
const nextConfig = {
  images: {
    loader: 'custom',
    loaderFile: '/custom-loader.ts',
  },
};

export default nextConfig;
```

## Current
But currently, nextjs occurs this error:
It is shown at either App router or Page router
```
TypeError: Cannot use 'in' operator to search for '__next_img_default' in undefined
```

<img width="1202" alt="스크린샷 2024-03-28 16 10 53" src="https://github.com/vercel/next.js/assets/33178048/e7c81cb5-7976-46ff-b86f-9c8fd9a7a681">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.15.4
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Image optimization (next/image, next/legacy/image)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

This error occurs at `getImgProps`

https://github.com/vercel/next.js/blob/0c21ff7df6f3cfc4b494bb78a354b68d7117ac96/packages/next/src/shared/lib/get-img-props.ts#L286-L294

`rest.loader` is what the user pass `loader` function at Image's `loader` prop. **But I didn't pass the custom loader at `Image` component so then the value of `loader` variable above would be `defaultLoader`.** `__next_img_default` property is only in `defaultLoader` for [checking whether or not the user pass the custom `loader`](https://github.com/vercel/next.js/blob/0c21ff7df6f3cfc4b494bb78a354b68d7117ac96/packages/next/src/shared/lib/image-loader.ts#L69-L71). I don't know why the value is `undefined`

#### Update
**If setting `images.loaderFile` at `next.config.js`, `defaultLoader` module is resolved as `config.images.loaderFile` during build. So we have to export loader function as default.** https://github.com/vercel/next.js/issues/63803#issuecomment-2026850654
https://github.com/vercel/next.js/blob/b434ea401cf2b12fca35e2ad7543f284b273254f/packages/next/src/build/create-compiler-aliases.ts#L112-L119

Nextjs internally import/export `defaultLoader` as a default function
https://github.com/vercel/next.js/blob/29d53c87ea53336cf1e436119975d8e53bc28827/packages/next/src/shared/lib/image-external.tsx#L7-L8

After build, the build assets is like:
```ts
// next.config.js
const nextConfig = {
  images: {
    loader: 'custom',
    loaderFile: '/custom-loader.js'
  }
}

// custom-loader.js
// ⚠️ named export
export function customLoader({ src }) {
  return src
}
```
**Since custom loader is exported as a named, `defaultLoader.default` is `undefined`**
```ts
// build asset for getImgProps.js
 import defaultLoader from '/custom-loader.js' // Resolve through webpack alias

...
 let loader: ImageLoaderWithConfig = rest.loader || defaultLoader.default // ⚠️ defaultLoader.default is undefined
  
 // Remove property so it's not spread on <img> element 
 delete rest.loader 
 delete (rest as any).srcSet 
  
 // This special value indicates that the user 
 // didn't define a "loader" prop or "loader" config. 
 const isDefaultLoader = '__next_img_default' in loader 
...
```

**Comment by ojj1123** [comment]
https://github.com/vercel/next.js/tree/c9439b5654432df6488e178e5ade6f4ad2d1cf6a/test/integration/next-image-new/loader-config

But why this test pass?

Next.js version for test environment : `Next.js 14.2.0-canary.48`

<img width="1017" alt="스크린샷 2024-03-29 13 40 26" src="https://github.com/vercel/next.js/assets/33178048/8237d9f9-de89-4e12-a5f5-6fed29d6a884">


### Repro
https://github.com/ojj1123/next-custom-loader-issue-repro/tree/with-next-canary

**So I try to upgrade nextjs version to Next.js 14.2.0-canary.48 and then reproduce it, but the error occurs.**

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.15.5
Relevant Packages:
  next: 14.2.0-canary.48 // Latest available version is detected (14.2.0-canary.48).
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

**Comment by ojj1123** [comment]
I found the reason.
Nextjs docs describes that [the loader file must ONLY export a default function](https://arc.net/l/quote/siuqxvdh)
so I did export as a default and then resolve this issue.

```diff
diff --git a/custom-loader.ts b/custom-loader.ts
index 461b1e3..d0af4f9 100644
--- a/custom-loader.ts
+++ b/custom-loader.ts
@@ -2,6 +2,10 @@

 import { ImageLoaderProps } from 'next/image';

-export function customLoader({ src, width, quality }: ImageLoaderProps) {
+export default function customLoader({
+  src,
+  width,
+  quality,
+}: ImageLoaderProps) {
   return `${src}?url=${encodeURIComponent(src)}&w=${width}&q=${quality || 75}`;
 }
```

BTW, How about supporting  a `named export`?
some people(also me) use the eslint rule, [`import/no-default-export`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-default-export.md). Currenly whenever using the custom loader, I have to turn off this rule manually. For flexibility, I suggest supporting a `named export` for loader.

**Comment by devjiwonchoi** [comment]
Hi, I'd say it is similar to how the `next.config.js` is imported, where it also requires a default export.
Since Next.js doesn't support multiple loaders, it is hard to target which one to import with named exports.

**Comment by ojj1123** [comment]
> Since Next.js doesn't support multiple loaders, it is hard to target which one to import with named exports.

Yeah, I agree with you.
Nextjs replaces `defaultLoader` with custom loader (`images.loaderFile`) through webpack `config.resolve.alias`

https://github.com/vercel/next.js/blob/b434ea401cf2b12fca35e2ad7543f284b273254f/packages/next/src/build/create-compiler-aliases.ts#L112-L119

https://github.com/vercel/next.js/blob/29d53c87ea53336cf1e436119975d8e53bc28827/packages/next/src/shared/lib/image-external.tsx#L7-L8

But I think it's good to warn for the user to named-export the loader function. Is it possible?

**Comment by devjiwonchoi** [comment]
Yeah, an accurate error message is always preferred. Mind if I open a PR? Feel free to open one if you'd like to!

**Comment by ojj1123** [comment]
Oh, so Could I try to PR? I want to investigate and resolve this issue!

**Comment by devjiwonchoi** [comment]
Yeah for sure! Ping me if you want to discuss anything. 😄
