### ISSUE TITLE
Required AUTH_SECRET in latest version

### ISSUE THREAD

**Issue by LoisDuplain** [vercel/next.js#63831]
### Link to the code that reproduces this issue

https://github.com/LoisDuplain/next-auth-example

### To Reproduce

There are two branches on the reproduction repository:

The main branch for the latest version of next, next auth... including the bug
And a "previous version" branch to show how it behaved before (the behaviour that should be correct).

To reproduce it juste git clone and execute `npm run build`
Then switch to "previous-version" branch and execute `npm run build`

### Current vs. Expected behavior

In the latest version of next with next auth, the AUTH_SECRET environment variable is mandatory, whereas it wasn't before.

It's not logical that it should be, because I need to deploy the same software several times for different customers, for example. So I'm not going to have fun recompiling my software 20 times for each customer just to have a different AUTH_SECRET.

### Provide environment information

```bash
System:
- OS: Windows 11 10.0.22631
- CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
- Memory: 4.64 GB / 15.91 GB

**Binaries:**
- Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
- Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
- npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
- pnpm: 8.15.3 - ~\AppData\Local\pnpm\pnpm.EXE

**Browsers:**
- Edge: Chromium (123.0.2420.65)
- Internet Explorer: 11.0.22621.1

**npmPackages:**
- next: ^14.1.4 => 14.1.4 
- next-auth: ^5.0.0-beta.16 => 5.0.0-beta.16 
- react: ^18.2.0 => 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local), Other (Deployed)

**Comment by king0120** [comment]
@LoisDuplain was running into this today. It's actually an issue with the `next-auth` package, not in next itself. 

Looks like they are aware of this and it was accidentally pushed in beta.16, downgraded to beta.15 for now and things seem to be fine.

**Comment by LoisDuplain** [comment]
Yes, I saw that earlier, but I hadn't taken the time to close the issue, thank you.

> @LoisDuplain was running into this today. It's actually an issue with the `next-auth` package, not in next itself.
> 
> Looks like they are aware of this and it was accidentally pushed in beta.16, downgraded to beta.15 for now and things seem to be fine.

**Comment by LoisDuplain** [comment]
https://github.com/nextauthjs/next-auth/issues/10432
