### ISSUE TITLE
Parallel Routes not working as expected in the development

### ISSUE THREAD

**Issue by akmtagline** [vercel/next.js#63863]
### Link to the code that reproduces this issue

https://github.com/akmtagline/next-14

### To Reproduce

1. Make sure you are running the development server, not the production build.
2. Go to the /dashboard route.
3. Click on the "Recent"
4. Reload the page
5. Click on the "Default" link
6. You should see a blank page

### Current vs. Expected behavior

**Current Behavior:**
I have a dashboard page that has three parallel routes `statistics`, `orders`, and `notifications`. The `notifications` route has a nested route `recent`. On the dashboard page, I have a link to the `dashboard/recent` page. Clicking on it shows the "Default" link and reloading it shows the default pages for parallel routes other than notifications. Now, if I click on the default link it shows the dashboard page with no content inside it.

**Expected Behavior:**
If I click on the Recent link, then reload the recent page, and click on the "Default" link to go to the dashboard, it should show all of the content for the dashboard page instead of showing a blank page.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: 8.15.5
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

https://github.com/vercel/next.js/assets/134274836/29e32a2a-d19f-44bc-ae3a-a0eb8bc9df48

Codesandbox: https://codesandbox.io/p/devbox/distracted-darkness-32gch2

**Comment by ztanner** [comment]
Hi, it looks like this issue was already fixed on Canary. Here's a quick video of me running your app:


https://github.com/vercel/next.js/assets/1939140/94482653-30ea-421c-9b51-cbfe30c863ca


Let us know if for some reason you're still not able to get it working after upgrading and we can take a look!
