### ISSUE TITLE
 [Failed to find Server Action "a944...". This request might be from an older or newer deployment]- Using Server action in parallel routes causing unexpected error

### ISSUE THREAD

**Issue by nikhil-nibhoria** [vercel/next.js#63915]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/staging-sun-vrs3dq?file=%2Fapp%2Flayout.tsx%3A27%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clufa2mj300073j6gltadjt0w%2522%252C%2522sizes%2522%253A%255B68.10606060606061%252C31.89393939393939%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clufa2mj300023j6g7idbrduj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clufa2mj300043j6g747u7ctk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clufa2mj300063j6gz2lw3efb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.573557935347%252C48.426442064653%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clufa2mj300023j6g7idbrduj%2522%253A%257B%2522id%2522%253A%2522clufa2mj300023j6g7idbrduj%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clufa2mj300063j6gz2lw3efb%2522%253A%257B%2522id%2522%253A%2522clufa2mj300063j6gz2lw3efb%2522%252C%2522activeTabId%2522%253A%2522clufezpkf051d3j6gu1r68sxm%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clufezpkf051d3j6gu1r68sxm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clufa2mj300043j6g747u7ctk%2522%253A%257B%2522id%2522%253A%2522clufa2mj300043j6g747u7ctk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clufa2mj300033j6gjv8bcbyf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clufa2mj300033j6gjv8bcbyf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### To Reproduce

1. Start application in development mode (next dev)
2. You will see two "div" side by side with headings - "@Left" and "@Right".
3. Click on "Go to LeftPage1" Link.
4. Click on "Go to RightPage1" Link.
5. Click on "Submit" button in the left div.

### Current vs. Expected behavior

Current: 
The server action "getData" doesn't work and an error comes on the dev Terminal: "Error: Failed to find Server Action "a944...". This request might be from an older or newer deployment. Original error: Invariant: Couldn't find action module ID from module map."

Expected:
The server action "getData" should work and response data should show in the left div below the "Go to LeftPage2" Link after clicking the "Submit" button.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.2.0-canary.50 // Latest available version is detected (14.2.0-canary.50).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

I tested this functionality on production version v14.1.4 and found that the issue is there as well. 
Also, just to summarize: The submit button works fine if it's clicked while being on "/leftPage1". It fails when I hit the "Submit" button when I am **not** on "/leftPage1".

**Comment by taskrider2022** [comment]
I have the same problem.

In my system I load a list from the backend, share it to i client component. In the client component I load additional data to the list items. If I click on on of the items to go to a new route (detailpage) a get this error.

**Comment by nikhil-nibhoria** [comment]
> I have the same problem.
> 
> In my system I load a list from the backend, share it to i client component. In the client component I load additional data to the list items. If I click on on of the items to go to a new route (detailpage) a get this error.
> 
> `Operating System: Platform: macos/linux Binaries: Node: 20.11.0 npm: 10.2.4 Relevant Packages: next: 14.1.4 react: 18.2.0 react-dom: 18.2.0 typescript: 5.4.3`
> 
> EDIT:
> 
> If I load the list not in a parallel route it works as designed. If i would load the list over a parallel route a became this error.

So just to confirm, if you click on the item to go to a new route, you call a server Action from the old/previous route, right?
