### ISSUE TITLE
Improve Metadata API documentation

### ISSUE THREAD

**Issue by uxuySafe** [vercel/next.js#63930]
### What is the improvement or update you wish to see?

I hope your website documentation is easy to read and provides a clear introduction to the API. For example, it is very difficult for me to set up a meta using app router. It feels like the most uncomfortable document I have ever seen. It is also recommended to support multiple languages.

### Is there any context that might help us understand?

https://nextjs.org/docs/app/building-your-application/optimizing/metadata    I want to set up <meta content="yes" name="apple-mobile-web-app-capable" />, but it takes me a long time to find out how to set it up from the documentation. Because I used this latest version before, I regret it very much. If that were the case, I wouldn’t recommend it to my friends.

<sub>[DX-2396](https://linear.app/vercel/issue/DX-2396/improve-metadata-api-documentation)</sub>

**Comment by chahatbhatia1** [comment]
@balazsorban44 I would like to know about the `manifest` property in the metadata object. After upgrading to Next.js 14 version, we are experiencing a CORS issue while requesting the manifest json file. 
This is due the fact that when we include the `manifest` in the generateMetadata function, it is appending a link tag like this:
```html
<link rel='manifest' href='link to manifest json file...' crossOrigin='use-credentials' />
```
Could you please help how can we remove this crossOrigin='use-credentials' attribute from manifest?

**Comment by leerob** [comment]
We are open to community contributions here 🙏
