### ISSUE TITLE
Facing An error occured in `next/font`.

### ISSUE THREAD

**Issue by darshan-sr** [vercel/next.js#63952]
### Link to the code that reproduces this issue

https://github.com/darshan-sr/chatmermaid/blob/main/app/layout.tsx

### To Reproduce

1. start the server in dev mode `npm run dev`

<img width="970" alt="Screenshot 2024-04-02 at 12 42 08 AM" src="https://github.com/vercel/next.js/assets/96766940/4cf19d1f-4bbe-43aa-a68d-6ec381cdb69f">

### Current vs. Expected behavior

Expecting this bug to be explained or fixed

### Provide environment information

```bash
Operating System:
    Github Codespace
    32GB RAM | 128GB ROM
    8 core
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by devjiwonchoi** [comment]
I could not reproduce. Does this error appear when using different package manager like pnpm? Could you verify it also throws on the latest canary version?

**Comment by darshan-sr** [comment]
Hello @devjiwonchoi , This issue is resolved!
