### ISSUE TITLE
Turbo side effect import

### ISSUE THREAD

**Issue by juliusmarminge** [vercel/next.js#63963]
### Link to the code that reproduces this issue

https://github.com/juliusmarminge/test-trpc-types-access

### To Reproduce

1. `bun install`
2. `bun dev` # works
3. `bun dev --turbo` # crashes with error

![CleanShot 2024-04-02 at 10 26 12@2x](https://github.com/vercel/next.js/assets/51714798/c263af53-2a0c-46be-8a54-7c19ce3515d6)

### Current vs. Expected behavior

Running with turbo crashes while webpack works. Would like turbo to work as well

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.13.1
Relevant Packages:
  next: 14.2.0-canary.52 // Latest available version is detected (14.2.0-canary.52).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Error is caused by this side effect (not great on our side to have this perhaps) 
![CleanShot 2024-04-02 at 10 30 02@2x](https://github.com/vercel/next.js/assets/51714798/a4542a8b-f2f5-4586-a942-fcbdcf03d30a)

I think this is sort of a bug in trpc too tbf, but since it worked in webpack but not turbo I reckon something might be wrong in turbo too

<sub>[PACK-2924](https://linear.app/vercel/issue/PACK-2924/turbo-side-effect-import)</sub>

**Comment by mischnic** [comment]
This is working as expected since next@15.0.0-canary.6 (so June 2), 15.0.0-canary.5 is the last broken version

Diff for that version range in Next.js: https://github.com/vercel/next.js/compare/v15.0.0-canary.5...v15.0.0-canary.6
Diff for Turbopack bump: https://github.com/vercel/turbo/compare/turbopack-240528.2...turbopack-240531.2

**Comment by timneutkens** [comment]
Going to close this, will re-open if Julius finds it doesn't work for their internal case 👍
