### ISSUE TITLE
Re-exporting metadata from workspace package fails

### ISSUE THREAD

**Issue by petter** [vercel/next.js#63971]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/nextjs-metadata-reexport-nrkj34?file=%2Fnext-app%2Fapp%2Fpage.tsx%3A5%2C39

### To Reproduce

1. Start the application in dev mode
2. Visit `/`

### Current vs. Expected behavior

If I try exporting metadata through a workspace package (in a server component) it fails if the workspace package is being imported somewhere in a client component. This results in the following error:

```
../package/src/page.tsx
Error: 
  × You are attempting to export "metadata" from a component marked with "use client", which is disallowed. Either remove the export, or the "use client" directive. Read more: https://nextjs.org/
  │ docs/getting-started/react-essentials#the-use-client-directive
  │ 
  │ 
    ╭─[/workspace/package/src/page.tsx:9:1]
  9 │     return <h1>{data}</h1>;
 10 │   }
 11 │   
 12 │   export const metadata = {
    ·                ────────
 13 │     title: 'Hello from package!',
 14 │   };
 15 │   
    ╰────
```
In the linked example I'm re-exporting metadata from the workspace package, `"package"`, in the root route's `page.tsx`. `page.tsx` is not marked with `"use client"`, and the workspace package's `page.tsx` isn't marked with "use client" either. However, I'm still getting the error seen above.

It also seems to not behave as a client component, as the async component that is being re-exported from the workspace package is only streaming in the resulting jsx from rendering on the server.

Removing the usage of the workspace package in `error.tsx` stops the issue from happening, and I'm able to re-export metadata correctly:
![image](https://github.com/vercel/next.js/assets/25374940/c441cdad-8484-4cde-8ba8-feb3e45b0ac7)

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.2.0-canary.52 // Latest available version is detected (14.2.0-canary.52).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

I've only tested with local workspace packages.

Also happens on 14.1.0.

**Comment by devjiwonchoi** [comment]
Hi, it is because you are barrel exporting, which makes your `index.ts` treated as a client component, thus `packages/page` is also a client component.

Try barrel export with splitted client and server components.

**Comment by petter** [comment]
Ah, I see. I got it working now, thanks! 😄 
https://codesandbox.io/p/devbox/nextjs-metadata-reexport-server-client-entrypoints-wvpndt?file=%2Fnext-app%2Fapp%2Fpage.tsx%3A3%2C17
