### ISSUE TITLE
Nonce doesn't applied to all scripts using turbopack

### ISSUE THREAD

**Issue by r34son** [vercel/next.js#64037]
### Link to the code that reproduces this issue

https://github.com/r34son/profile

### To Reproduce

1. pnpm i
2. add --turbo to next dev
3. run pnpm dev

### Current vs. Expected behavior

few scripts without nonce
<img width="1283" alt="image" src="https://github.com/vercel/next.js/assets/43549299/1649d3e8-2dbd-4c99-b7b9-49b7addeab49">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: N/A
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.0-canary.55 // Latest available version is detected (14.2.0-canary.55).
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[PACK-2973](https://linear.app/vercel/issue/PACK-2973/nonce-doesnt-applied-to-all-scripts-using-turbopack)</sub>

**Comment by r34son** [comment]
any thoughts on this?

**Comment by timneutkens** [comment]
Created a significantly simpler reproduction: https://codesandbox.io/p/github/r34son/profile/csb-7xqzp4/draft/reverent-hill?file=%2Fsrc%2Fapp%2F%5Blocale%5D%2Flayout.tsx

In the future please make sure that the reproduction linked is not a large application as it causes significant overhead/delays in fixing the issue as we have to manually figure out what you meant exactly being the root cause of the issue. I.e. I just spent 40 minutes deleting your application code.

**Comment by timneutkens** [comment]
Added a failing test: https://github.com/vercel/next.js/pull/65508

**Comment by timneutkens** [comment]
Fixed it in https://github.com/vercel/next.js/pull/65508, thank for the report!

**Comment by r34son** [comment]
@timneutkens Great news! Thank you!

**Comment by r34son** [comment]
@timneutkens Found one more place where nonce isn't applied. Here in webpack chunk nonce is undefined somehow:
<img width="940" alt="image" src="https://github.com/vercel/next.js/assets/43549299/dc557faf-8370-423e-baed-1be7a68450a9">
I tried to reproduce it`s locally, but no luck. Only fires in prod https://r34s0n.tech/en
Will try to investigate more, but maybe you have some thoughts why it can happen?
