### ISSUE TITLE
Cannot deploy nextjs-with-supabase

### ISSUE THREAD

**Issue by patrickdundas** [vercel/next.js#64045]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Vercel deploy button, url is: https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fvercel%2Fnext.js%2Ftree%2Fcanary%2Fexamples%2Fwith-supabase&project-name=nextjs-with-supabase&repository-name=nextjs-with-supabase&demo-title=nextjs-with-supabase&demo-description=This%20starter%20configures%20Supabase%20Auth%20to%20use%20cookies%2C%20making%20the%20user%27s%20session%20available%20throughout%20the%20entire%20Next.js%20app%20-%20Client%20Components%2C%20Server%20Components%2C%20Route%20Handlers%2C%20Server%20Actions%20and%20Middleware.&demo-url=https%3A%2F%2Fdemo-nextjs-with-supabase.vercel.app%2F&external-id=https%3A%2F%2Fgithub.com%2Fvercel%2Fnext.js%2Ftree%2Fcanary%2Fexamples%2Fwith-supabase&demo-image=https%3A%2F%2Fdemo-nextjs-with-supabase.vercel.app%2Fopengraph-image.png&integration-ids=oac_VqOgBHqhEoFTPzGkPd7L0iH6
```

### Which example does this report relate to?

nextjs-with-supabase

### What browser are you using? (if relevant)

Both Chrome and Firefox

### Describe the Bug

After adding a new supabase project for the integration, the vercel deployment page gets stuck permanently on "completing installation". The nextjs-with-supabase deployment / creation does not complete past this step on either Chrome or Firefox.
![image](https://github.com/vercel/next.js/assets/6844039/c36564b6-4443-4766-a942-2b0b38448363)

### Expected Behavior

Deployment works as expected

### To Reproduce

Deploy nextjs-with-supabase via the vercel nextjs templates page. Cannot get past step 2 "Add Integrations" (Supabase)

**Comment by devjiwonchoi** [comment]
Hi, I think this issue is from Vercel, so I ported your issue to https://github.com/orgs/vercel/discussions/6422.
I'll let you know if anything comes up.

**Comment by samcx** [comment]
@devjiwonchoi Yes this is not a <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> related issue! Thank you for adding there.
