### ISSUE TITLE
Next does not add nonce to link rel="preload" tag

### ISSUE THREAD

**Issue by arackaf** [vercel/next.js#64091]
### Link to the code that reproduces this issue

https://github.com/arackaf/next-csp-repro

### To Reproduce

npm install and then run the project.

Use **Chrome** and hit page http://localhost:3000/page2 

Note the csp error in the console 

> Refused to load the script 'http://localhost:3000/script.js' because it violates the following Content Security Policy directive: "script-src self 'nonce-ZDQ4ZTBhYTEtNmM2MC00ODNkLTgwNWQtMGZkN2M5Zjg3OGM0' 'strict-dynamic' 'unsafe-inline' https: 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

This is almost certainly caused by the <link tag Next inserts 

```html
<link rel="preload" href="/script.js" as="script">
```

When I change 

```html
<Script src="/script.js" nonce={nonce} />
```

to

```html
<script src="/script.js" nonce={nonce} />
```

the csp error goes away (though a hydration warning happens, presumably because of the nonce). 

### Current vs. Expected behavior

No csp error 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.15
  pnpm: 6.11.0
Relevant Packages:
  next: 14.1.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Metadata (metadata, generateMetadata, next/head)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by r34son** [comment]
Maybe related https://github.com/vercel/next.js/pull/56995

**Comment by feedthejim** [comment]
yeah I just pulled and tested on canary, there's no error on canary anymore @arackaf

**Comment by arackaf** [comment]
The linked case does not at all accurately describe what seems to be the problem. The script tag I'm seeing DOES have a nonce, but the link tag does not. I ran with canary, and the script tag continues to have the nonce, but now the link tag does as well. And the error disappears. 

So it appears the linked PR fixed this issue, as well as whatever was being reported, so I'll close.
