### ISSUE TITLE
Turbopack: CommonJS require import of 'canvas' fails to resolve when using react-pdf library

### ISSUE THREAD

**Issue by oliverjohns** [vercel/next.js#64165]
### Link to the code that reproduces this issue

https://github.com/oliverjohns/turbopack-import-problem-example

### To Reproduce

follow the repo readme
1. start application with npm run dev -- --turbo
2. click the route "to test page"
3. then watch the error occur

### Current vs. Expected behavior

Current behavior:
When using react-pdf according to the code example provided and running `npm run dev -- --turbo`, the commonjs import  of canvas fails, giving us this input:

```
./node_modules/pdfjs-dist/build/pdf.js:6247:19
Module not found: Can't resolve 'canvas'
  6245 | class NodeCanvasFactory extends _base_factory.BaseCanvasFactory {
  6246 |   _createCanvas(width, height) {
> 6247 |     const Canvas = require("canvas");
       |                    ^^^^^^^^^^^^^^^^^
  6248 |     return Canvas.createCanvas(width, height);
  6249 |   }
  6250 | }

https://nextjs.org/docs/messages/module-not-found
```

Expected behavior
Following the steps I expected turbopack to be able to handle this import of react-pdf/canvas since it works in Webpack without any issues.

### Provide environment information

```bash
Operating system:
MacOS ARM M3

Node version: v20.9.0
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by padmaia** [comment]
This looks fixed on the latest canary (14.2.0-canary.63)

**Comment by oliverjohns** [comment]
> This looks fixed on the latest canary (14.2.0-canary.63)

This is not fixed on `14.2.0-canary.63` , neither on the latest `14.2.1`. I have tested both versions.

This issue should be reopened.

**Comment by oliverjohns** [comment]
@padmaia

**Comment by chris-trait** [comment]
This is broken for me too, on version `14.2.2`, turbopack is unusable.

**Comment by timneutkens** [comment]
@oliverjohns I just checked the reproduction but it compiles fine, here's the codesandbox for it: https://codesandbox.io/p/github/oliverjohns/turbopack-import-problem-example/csb-3jzc72/draft/jovial-rubin?file=%2Fsrc%2Fapp%2Ftestpage%2Fpage.tsx%3A5%2C25

@chris-trait please open a new issue with a reproduction so that we can take a look. Thanks!
