### ISSUE TITLE
Discrepancy in searchParams between server and client after clicking `Link`

### ISSUE THREAD

**Issue by kachkaev** [vercel/next.js#64170]
### Link to the code that reproduces this issue

https://github.com/kachkaev/next-js-search-params-mismatch-mwe

### To Reproduce

1. Clone reproduction repo, run `pnpm install` and  `pnpm dev` (or `pnpm build; pnpm start`).

1.  Navigate to http://localhost:3000/?a=1&b=3 in a new tab. Observe this page (no issues so far):
    
    <img width=371 src=https://github.com/vercel/next.js/assets/608862/e1b58713-0464-45a9-ac14-05a2db62503a>

1. Click on `<Link />` components at the bottom of the page, observe changes in displayed values for `a` and `b`. All good still.

   https://github.com/vercel/next.js/assets/608862/996ad1dc-442b-48d4-b08d-01251bac21b3

1. Navigate to a link that takes you to `/`, i.e.  that unsets _both_ `a` and `b`.

#### Observed state
❌ `searchParams` in `page.tsx` is equal to the original value (the one we saw on initial page load).
✅ `useSearhParams()` returns correct values for `a` and `b`.

<img width=371 src=https://github.com/vercel/next.js/assets/608862/f7af5add-48fa-4789-a228-5b3457f50eda>

#### Expected state
Both sources of `searchParams` should be in sync (which can be observed after full page reload):

<img width=371 src=https://github.com/vercel/next.js/assets/608862/984755dc-9556-402d-abf8-9766e62a3d61>

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.1
  npm: 10.5.0
  Yarn: 4.0.0
  pnpm: 8.10.5
Relevant Packages:
  next: 14.2.0-canary.61 // Latest available version is detected (14.2.0-canary.61).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

If all initial page query params are unset, the bug does not manifest itself. So it’s important to start with something like http://localhost:3000/?a=1&b=3 and not just http://localhost:3000.

---

This bug has implications on pages like e-commerce catalogs which can be filtered. Imagine someone sends you a link to

https://example.com/products?category=shoes&color=red

You’ll see filter controls in the UI and start clicking:
↓
https://example.com/products?category=shoes&color=green
↓
https://example.com/products?category=tshirts&color=green
↓
https://example.com/products?category=tshirts
↓
https://example.com/products?category=tshirts&color=red
↓
...

As long as there is at least one query param in the URL, all works well. But as soon as you navigate to no filters, the catalog will look broken. The URL will be https://example.com/products but the content will be for `?category=shoes&color=red` (the initial state of the app router).  The only way to see the whole catalog will be to refresh the page.

**Comment by kachkaev** [comment]
Looks like I have found a workaround. It might be good enough for most people before the issue is fixed in Next.js itself:

https://github.com/kachkaev/next-js-search-params-mismatch-mwe/pull/1

https://github.com/vercel/next.js/assets/608862/5bf13cfb-6176-4b8f-aaee-c23954fa2423

**Comment by dmaksimov** [comment]
Experiencing this issue as well.

The search params are in sync up until you navigate to the page without any search params.

**Comment by samburgers** [comment]
Discovered this issue too, and made a clickable minimal reproduction here:
https://nextjs-queryparams.vercel.app/

Source:
https://github.com/samburgers/nextjs-queryparams/blob/main/app/page.tsx

**Comment by icyJoseph** [comment]
Ahh, we've also hit this one after a major leap from 14.1.x to 14.2.x territory. 

Same issue reported here: https://github.com/vercel/next.js/issues/65030

@balazsorban44 - sorry for pinging you, but do you think you could drop some thoughts on this issue?

**Comment by icyJoseph** [comment]
Another update, it might just be a coincidence, but changing staleTime dynamic to zero, seems to do the trick...

- https://nextjs.org/docs/app/api-reference/next-config-js/staleTimes

Perhaps the introduction of staleTimes, causes this issue?

**Comment by icyJoseph** [comment]
@ztanner Hi, sorry for pinging you on this one, in all honesty I haven't tested this issue in the canaries released this past week, but would you mind investigating what's going on here? Is it expected behavior, or has a bug indeed been introduced?

I think the links here, https://github.com/vercel/next.js/issues/64170#issuecomment-2078197117, are pretty much all you need to see the issue.

**Comment by devjiwonchoi** [comment]
@kachkaev @icyJoseph Just tested `next@14.3.0-canary.73`, and it seems to be fixed! Please note that `next@canary` currently requires the `react@canary` as well :)

**Comment by kachkaev** [comment]
This is brilliant, many thanks @devjiwonchoi 👏

**Comment by icyJoseph** [comment]
Fantastic! Also verified this on a couple of project now. Awaiting a new release now.
