### ISSUE TITLE
Docs: Switchers (App Router/Pages Router, TypeScript/JavaScript) not working on mobile browsers

### ISSUE THREAD

**Issue by ViktorYermak** [vercel/next.js#64292]
### What is the improvement or update you wish to see?

Description:
The documentation website's switchers (**App Router/Pages Router** and **TypeScript/JavaScript**) are malfunctioning on **mobile browsers**.

Steps to Reproduce:
Open the docs website on your mobile device.
Navigate to a webpage that utilizes switcher components.
Attempt to interact with a switcher by tapping on it.

Expected Behavior:
Tapping the switcher should open a dropdown menu displaying available options.

Actual Behavior:
Tapping the switcher does not trigger the dropdown menu to appear.

### Is there any context that might help us understand?

Mobile browsers:
Chrome Mobile
Safari on iOS

Components:
Switchers App Router/Pages Router, TypeScript/JavaScript

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs

<sub>[DX-2427](https://linear.app/vercel/issue/DX-2427/docs-switchers-app-routerpages-router-typescriptjavascript-not-working)</sub>

**Comment by ViktorYermak** [comment]
Probably partially related to #62992

**Comment by delbaoliveira** [comment]
Thank you for raising this @ViktorYermak, this issue should be fixed now 🙏🏼
