### ISSUE TITLE
Huge CLS if app uses both next/dynamic and React.ContextAPI

### ISSUE THREAD

**Issue by KirillEvtushenko** [vercel/next.js#64327]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/new-https-vnj5df

### To Reproduce

1. Refresh the page
2. Notice CLS as page loads

Alternative:
https://github.com/KirillEvtushenko/app-router-dynamic-imports-react-context-issue
Follow the README.

### Current vs. Expected behavior

When using next/dynamic with React.createContext, I expect that it will work the same way as without React.createContext. 

Current behaviour:

https://github.com/vercel/next.js/assets/102147606/b8b4db93-4419-495d-b6d4-8a699a5603eb

Expected behaviour:

https://github.com/vercel/next.js/assets/102147606/add0ca42-28f7-4087-8c91-f49d7c9f1c99

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.18
  pnpm: 8.6.5
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Dynamic imports (next/dynamic)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

Tested on both `"next": "14.1.4"` and `"next": "14.2.0-canary.65"`. Issue reproduces.

After hours of investigation, I can conclude that CLS (not actually a CLS, but disappearing and appearing of all content) appears only if app has **multiple levels** of dynamic imports along with **React.ContextAPI**.

So if we move all dynamic imports to the single registry or we remove Context Provider, there won't be any issue with CLS.
But having dynamic imports in multiple registries and having Context Provider are both valid cases, so the issue looks critical.

Please note that all components are "use client" components. That is made in order to avoid any composition complexities with RSC. 
The issue is similar to the https://github.com/vercel/next.js/issues/64060, but it has an important difference: this issue reproduces only for **multiple registries** with dynamic imports + React.ContextAPI.

**Comment by huozhi** [comment]
Let's track this in #64060 as it's the same issue
