### ISSUE TITLE
The not-found file is 0B when the project is build, resulting in page 500 when the not-found is accessed. But it works fine in dev environment

### ISSUE THREAD

**Issue by BblythePan** [vercel/next.js#64343]
### Link to the code that reproduces this issue

https://github.com/paalmorholmen/nextjs-not-found-ssr-link-bug/tree/main

### To Reproduce

1, npm run build
2, npm start

### Current vs. Expected behavior

current: resulting in error code 500 when visiting the 404 page.
Expected： The 404 page can be accessed successfully after the build

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 20.9.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

![Image20240411223352](https://github.com/vercel/next.js/assets/165253635/7fba4fe8-70b4-4279-99ac-fa6446d3f1cd)
As shown in the figure, I set the not-found file, but when packaged with "npm run build", the file size is 0, resulting in error code 500 when visiting the 404 page

**Comment by timneutkens** [comment]
Tried running the application but can't reproduce this, here's a codesandbox: https://codesandbox.io/p/github/paalmorholmen/nextjs-not-found-ssr-link-bug/csb-44vn4m/draft/festive-bird

https://44vn4m-3000.csb.app/_not-found

When trying the latest version the not-found showing up as 0B is also resolved:

```
Route (app)                              Size     First Load JS
┌ ƒ /                                    5.46 kB         105 kB
├ ƒ /_not-found                          139 B          99.9 kB
└ ƒ /api                                 139 B          99.9 kB
+ First Load JS shared by all            99.8 kB
  ├ chunks/624-8f1cf429150c4157.js       45.3 kB
  ├ chunks/c877f30b-58a177cec124aa49.js  52.6 kB
  └ other shared chunks (total)          1.88 kB
```
