### ISSUE TITLE
AMP Components do not render with App router.

### ISSUE THREAD

**Issue by atul-vashisht** [vercel/next.js#64354]
### Link to the code that reproduces this issue

https://github.com/atul-vashisht/amp-err

### To Reproduce

1. Start creating Next.js App with Create Next.js CLI.
2. Select APP Routing feature.

### Current vs. Expected behavior

With App router I am unable to render AMP components.
A minimal code is here.
https://github.com/atul-vashisht/amp-err

### Provide environment information

```bash
"react": "^18",
"react-dom": "^18",
"next": "14.1.4"

node --version v20.12.1
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next start (local)

### Additional context

If I use pages instead of App routing, my AMP component renders successfully.

**Comment by balazsorban44** [comment]
Hi, currently AMP support in the App Router is not planned.
