### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME] on Windows Using [npm run dev]

### ISSUE THREAD

**Issue by Ahmed-Elgendy25** [vercel/next.js#64372]
### Link to the code that reproduces this issue

https://github.com/Ahmed-Elgendy25/Next.js

### To Reproduce

1- Clone the project: https://github.com/Ahmed-Elgendy25/Next.js "v14.2.0"
2- npm run dev

### Current vs. Expected behavior

 After I did (npx create-next-app@latest) and tried to run the project with (npm run dev)...
I expected to see the default homepage of next.js, but it says: 
It tells me: 

An error occurred in next/font.

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)

at defaultLoad (node:internal/modules/esm/load:130:3)

at ModuleLoader.load (node:internal/modules/esm/loader:403:13)

at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:56)

at new ModuleJob (node:internal/modules/esm/module_job:67:26)

at #createModuleJob (node:internal/modules/esm/loader:297:17)

at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:254:34)

at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:235:17)

at async ModuleLoader.import (node:internal/modules/esm/loader:322:23)

⨯ app\layout.tsx

An error occurred in next/font.

![next-bug](https://github.com/vercel/next.js/assets/108876019/b2dbeac0-084a-4e25-ae8e-a13d2e4aa51d)
![next-bug2](https://github.com/vercel/next.js/assets/108876019/cf90deb6-a62c-43ff-9da0-94f9c9e51fa4)

### Provide environment information

```bash
Operating System:
 Platform: win32
 Arch: x64
 Version: Windows 10 Pro (22H2)

Binaries:
 Node:v20.12.2
 npm:10.5.2
 Yarn: N/A
 pnpm: N/A

Relevant Packages:
 "react": "^18"
 "react-dom": "^18"
 "next": "14.2.0"
 "eslint-config-next": "14.2.0"
 "typescript": "^5",
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

**Comment by jawad-multani** [comment]
I am facing the same issue. Any solution?

**Comment by DivineDemon** [comment]
I'm facing the same issue currently. Please fix!

**Comment by campbell-frost** [comment]
same errors using yarn add create-next-app for me

**Comment by Mikoyzskie** [comment]
I'm getting the same issue, thought it was my npm or node.

**Comment by Shank0071** [comment]
npx create-next-app@14.1.0 works. The above issue occurred while installing 14.1.4 onwards for me. For the time being using version 14.1.0 will do the job I guess

**Comment by elmerdotdev** [comment]
Yes we also had to create our projects using version 14.1.0 instead of the latest version as a temporary fix

**Comment by jthomazini** [comment]
I have the same error; I have just installed node js and created the Nextjs app with npx create-next-app@latest
Need to install the following packages:
create-next-app@14.2.0
Ok to proceed? (y)
√ What is your project named? ... hello-world
√ Would you like to use TypeScript? ... No / Yes
√ Would you like to use ESLint? ... No / Yes
√ Would you like to use Tailwind CSS? ... No / Yes
√ Would you like to use `src/` directory? ... No / Yes
√ Would you like to use App Router? (recommended) ... No / Yes
√ Would you like to customize the default import alias (@/*)? ... No / Yes
Creating a new Next.js app in D:\Development\VSC\Nextjs\course\hello-world.

added 360 packages, and audited 361 packages in 1m

133 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Success! Created hello-world at D:\Development\VSC\Nextjs\course\hello-world

npm run dev

> hello-world@0.1.0 dev
> next dev

  ▲ Next.js 14.2.0
  - Local:        http://localhost:3000

 ✓ Starting...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
 ✓ Ready in 7.1s

I have disabled telemetry:
npx next telemetry disable

Then I tried again:
npm run dev

> hello-world@0.1.0 dev
> next dev

  ▲ Next.js 14.2.0
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1446ms

And then I got the error:

src\app\layout.tsx
An error occurred in `next/font`.

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:239:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:403:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:285:56)
    at new ModuleJob (node:internal/modules/esm/module_job:67:26)
    at #createModuleJob (node:internal/modules/esm/loader:297:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:254:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:235:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:322:23)

**Comment by jorchsg** [comment]
Here is a temprary solution.

https://github.com/vercel/next.js/issues/64371#issuecomment-2050735468

**Comment by automatefreely** [comment]
This actually works

> npx create-next-app@14.1.0 works. The above issue occurred while installing 14.1.4 onwards for me. For the time being using version 14.1.0 will do the job I guess

**Comment by Azoonex** [comment]
There is no next version 14 yet

**Comment by Azoonex** [comment]
There is no next version 14 yet
You can from 
use npx create-next-app@14.1.0

**Comment by HOTLancerX** [comment]
update Node.js v21.7.3

**Comment by robiuzzaman4** [comment]
After creating a next app by using ` npx create-next-app@latest` command, the app gets created using the next js v14.2.0. But it has the above issue. Now I fixed this issue by following this temporary solution. [https://github.com/vercel/next.js/issues/64371#issuecomment-2050735468](https://github.com/vercel/next.js/issues/64371#issuecomment-2050735468)

**Comment by timneutkens** [comment]
Closing as duplicate of https://github.com/vercel/next.js/issues/64371

**Comment by cassiossantos** [comment]
> Yes we also had to create our projects using version 14.1.0 `npx create-next-app@14.1.0` instead of the latest version as a temporary fix

Tks! Worked for me.

**Comment by Joshua-takyi** [comment]
i even restarted my IDE now i've lost all extensions lol ..i  knew everything was working well last night

**Comment by Ananyajadon** [comment]
even i create a new project and tried to change the location of every folder still this error showing

**Comment by Azoonex** [comment]
You Can install v @14.1.0 
and continue until is completely stable

**Comment by yeabnoah** [comment]
I installed the latest version, but it wasn't working as expected. Instead, I used `npx create-next-app@14.1.0 `and that worked successfully.

**Comment by Arghya003** [comment]
using npx create-next-app@14.1.0 . is actually working. I dont why this error is occurring. anyone got a clue?

**Comment by HamzaAmar** [comment]
It' s happen to me also at the first it work correctly but after I change the font the error occur ??

**Comment by Azoonex** [comment]
The latest version has a problem that the developers of Next are dealing with. Please change the version 
``` npx create-next-app@14.1.0 ```

**Comment by mohammadrezagohari** [comment]
14.1.0 version still has this error

**Comment by nabily4e-dev** [comment]
I renamed my `postcss.config.js` file to `postcss.config.cjs`. This resolved the issue for me.

**Comment by Balyeet1** [comment]
> I renamed my `postcss.config.js` file to `postcss.config.cjs`. This resolved the issue for me in Next.js v14.2.1.

Im using 14.2.0-canary.66 Next version, and this worked for me, thanks.
