### ISSUE TITLE
Next 14. x reported an error when using scss loader 

### ISSUE THREAD

**Issue by machinister** [vercel/next.js#64388]
### Verify canary release

- [x] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32483
  Available CPU cores: 20
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.1-canary.0 // Latest available version is detected (14.2.1-canary.0).
  eslint-config-next: 14.2.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

scss

### Describe the Bug

current
Scss was successfully compiled, but the program reported an error. After deleting the configuration of sass loader in next.config.mjs, the error will no longer be reported. However, the scss global variable is invalid, even if a custom loader is used to replace scss loader, an error will still be reported
Problem details： https://github.com/vercel/next.js/issues/64385

### Expected Behavior

expect
compile and modify styles correctly

### To Reproduce

1、npx create-next-app@latest
2、define the public/const. scss file and define the scss variable
3、define the app/index. module. scss file to use the scss variable const. scss and introduce index. module. scss in the app/layout
4、configure sass-loader in nextconfig.mjs
5、npm run dev
6、error
address: https://stackblitz.com/edit/stackblitz-starters-pkyxk2?description=The%20React%20framework%20for%20production&file=app%2Findex.module.scss,app%2Fpage.tsx,public%2Fconst.scss,next.config.mjs,package.json,app%2Flayout.tsx&title=Next.js%20Starter

**Comment by Netail** [comment]
To use sass in a nextjs project, you only have to add sass as a dependency. 
You can pass additional options to the sass loader by the [sassOptions attribute in the next config](https://nextjs.org/docs/app/building-your-application/styling/sass#customizing-sass-options).

```
const nextConfig = {
  reactStrictMode: true,
  sassOptions: {
    additionalData: `@import "/public/const.scss";`,
  },
};
```

Further more; don't place sass files in the public folder as these will be statically served.

**Comment by timneutkens** [comment]
Indeed adding sass-loader is not needed.
