### ISSUE TITLE
Does Suspence not work with Page Router

### ISSUE THREAD

**Issue by childrentime** [vercel/next.js#64387]
### Link to the code that reproduces this issue

https://github.com/childrentime/next-stream-pagerouter

### To Reproduce

I tried using Suspense in the PageRouter, and the page rendering works fine. However, using Suspense did not reduce the server-side rendering time. It seems to include the time taken by the promise within Suspense.

<img width="937" alt="image" src="https://github.com/vercel/next.js/assets/58261676/8f5525c6-6138-46ad-a9f3-163ace660d97">

### Current vs. Expected behavior

Expected Behavior:  Waiting for server response time should reduce to `getServerSideProps` promise time.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:52 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T8122
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.21
  pnpm: 8.15.3
Relevant Packages:
  next: 14.2.0 // Latest available version is detected (14.2.0).
  eslint-config-next: 14.2.0
  react: 18.3.0-canary-bb0944fe5-20240313
  react-dom: 18.3.0-canary-bb0944fe5-20240313
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by timneutkens** [comment]
Indeed, in order to leverage streaming you have to use App Router.

**Comment by childrentime** [comment]
@timneutkens I only want to use streaming rendering and don't want to use server components. Since I feel like this would be very costly for my team members to learn and migrate, is there any way to do it?
