### ISSUE TITLE
next.js 14.2 breaks styled-jsx interpolation

### ISSUE THREAD

**Issue by jigsawye** [vercel/next.js#64389]
### Link to the code that reproduces this issue

[reproduce link](https://codesandbox.io/p/devbox/hardcore-curran-xxkvm8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluwflp3b00073b6fa9vqd2me%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluwflp3b00023b6fdi2e6k9a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluwflp3b00043b6fnabpchd4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluwflp3b00063b6fxmiwrtdt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluwflp3b00023b6fdi2e6k9a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluwflp3b00013b6f34b8f8fb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluwfm6md00403b6fjp0pzwsu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Flayout.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluwflp3b00023b6fdi2e6k9a%2522%252C%2522activeTabId%2522%253A%2522cluwfm6md00403b6fjp0pzwsu%2522%257D%252C%2522cluwflp3b00063b6fxmiwrtdt%2522%253A%257B%2522id%2522%253A%2522cluwflp3b00063b6fxmiwrtdt%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cluwfo4xv00tw3b6flb1v7vy3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluwfo4xv00tw3b6flb1v7vy3%2522%257D%252C%2522cluwflp3b00043b6fnabpchd4%2522%253A%257B%2522id%2522%253A%2522cluwflp3b00043b6fnabpchd4%2522%252C%2522activeTabId%2522%253A%2522cluwg9qi901cx3b6fr4v09ooo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cluwfn46000ca3b6f21bcduf8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cluwg9qi901cx3b6fr4v09ooo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cluwg9qov000gdjio83gueu9t%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### To Reproduce

Opening the reproduction URL reveals that the output is not as expected.

layout.tsx
```tsx
"use client";

const color = "color: red;";

export default function RootLayout({ children }) {
  return (
    <html>
      <head />
      <body>{children}</body>
      <style jsx global>
        {`
          body {
            ${color}
          }
          body p {
            font-size: 72px;
          }
        `}
      </style>
    </html>
  );
}
```

page.tsx
```tsx
/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  return <p>hello</p>;
}
```

### Current vs. Expected behavior

The body selector in the output style is missing the closing brace

<img width="571" alt="image" src="https://github.com/vercel/next.js/assets/8567270/139facaa-4d9c-4d4d-98cd-6ad3a0dfa8fb">

<img width="336" alt="image" src="https://github.com/vercel/next.js/assets/8567270/a1e0053b-93f6-486e-9776-a6f72f77c308">

In the previous version 14.1.4, the output appears as expected

<img width="582" alt="image" src="https://github.com/vercel/next.js/assets/8567270/0a812b28-ddb4-45a4-bcda-c414b49d1173">

<img width="342" alt="image" src="https://github.com/vercel/next.js/assets/8567270/3bb7c171-58d0-4221-8de6-f5bc27869741">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 18.20.0
  npm: 10.5.0
  Yarn: N/A
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.0 // Latest available version is detected (14.2.0).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

SWC transpilation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

<sub>[PACK-2947](https://linear.app/vercel/issue/PACK-2947/nextjs-142-breaks-styled-jsx-interpolation)</sub>

**Comment by kdy1** [comment]
https://github.com/swc-project/plugins/pull/283 should fix this

**Comment by kdy1** [comment]
Next turbopack update will fix this issue as https://github.com/vercel/turbo/pull/7955 is merged

**Comment by kdy1** [comment]
This is fixed by https://github.com/swc-project/plugins/pull/283

https://github.com/vercel/next.js/blob/637015524079dc382203e0c4162607b3fe6e7838/Cargo.lock#L5038
