### ISSUE TITLE
Server Actions: Blocking Behaviour

### ISSUE THREAD

**Issue by Exitium-DEV** [vercel/next.js#64396]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/tender-visvesvaraya-lp7gn4?file=%2Fapp%2Fpage.tsx%3A8%2C49

### To Reproduce

1. Start the application
2. Click the button to call a server action, sent count should increment by 1, and settled count by 1 a second later (when the action settled)
3. Spam the button, you will see that each action is queued, and the queued actions may not execute until the previous action settles

### Current vs. Expected behavior

Actions should not be blocking.

Currently an action (action A) called in a project will prevent any other actions (actions B and C) from running until action A has settled, and likewise action C will not be called until action B settles

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.2.0-canary.9 // There is a newer canary version (14.2.1-canary.0) available, please upgrade! 
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
```

### Which area(s) are affected? (Select all that apply)

Server Actions

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

Tested on latest canary.

No option for server actions in "Which area(s) are affected? (Select all that apply)"

**Comment by remorses** [comment]
This is the expected behaviour unfortunately to make things like `useOptimistic` work

https://github.com/vercel/next.js/discussions/50743

**Comment by ahmad5149** [comment]
May be this will work for you .
https://stackoverflow.com/a/78329141/14045850

**Comment by samcx** [comment]
I can confirm this is by design.

Why? To prevent things such as inconsistent states from navigation aborting, client fetching, etc.

There is definitely room for possible improvements with Server Actions (e.g., batching) that the team is looking at. But today, for your example, I think `useOptimistic` might be a great use-case!
