### ISSUE TITLE
14.2 breaks lint option --report-unused-disable-directives

### ISSUE THREAD

**Issue by Kamahl19** [vercel/next.js#64402]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/stoic-morse-kdqd86

### To Reproduce

1. use next 14.2.0
2. update lint command to be `"lint": "next lint --report-unused-disable-directives error"`
3. npm run lint

### Current vs. Expected behavior

Up until 14.1.4 it lints properly and reports unused directives. 14.2.0 throws an error "Invalid project directory provided, no such directory: /workspace/error". For some reason it appends the "error" to the project dir

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
  Available memory (MB): 65536
  Available CPU cores: 12
Binaries:
  Node: 20.11.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.0 // Latest available version is detected (14.2.0).
  eslint-config-next: 14.2.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

CLI (create-next-app), ESLint (eslint-config-next)

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

This seems to start happening in 14.2.0-canary.0 and it seems to be connected to updating the commander because the `directory` here https://github.com/vercel/next.js/blob/c9c074c18d8d67f891672f361bc7084d512bec26/packages/next/src/bin/next.ts#L285 now happens to be 'error'

**Comment by samcx** [comment]
@Kamahl19 Looking into this!

**Comment by samcx** [comment]
@Kamahl19 Upon closer look, I believe this should be a Boolean flag → https://eslint.org/docs/latest/use/command-line-interface#--report-unused-disable-directives.

I'm not sure how it's breaking now for you, but any value without a `--` will default to the `[directory]` Argument.

**Comment by Kamahl19** [comment]
@samcx eslint 9 has changed it, however I am using eslint 8. When I downgrade to 14.1.4 it works, 14.2.0 breaks it

**Comment by samcx** [comment]
@Kamahl19 It looks like we need to rename this to https://eslint.org/docs/v8.x/use/command-line-interface#--report-unused-disable-directives-severity, instead of https://eslint.org/docs/v8.x/use/command-line-interface#--report-unused-disable-directives

I don't think it's because Eslint 9 (we're still on Eslint 8)

**Comment by samcx** [comment]
@Kamahl19 Can confirm it works with `v14.2.1-canary.3`!
