### ISSUE TITLE
Upgrading Next 14.2 broke how dd-trace is compiled and tries to bring in a devDependency of dd-trace

### ISSUE THREAD

**Issue by drobannx** [vercel/next.js#64419]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/pensive-star-go8s7s

### To Reproduce

We have an `instrumentation.ts` file defined in the root with a register function as follows:

```ts
if (process.env.NEXT_RUNTIME === 'nodejs') {
  await import('./instrumentation/tracer');
}
```

Inside of `tracer.ts`

```
import tracer from 'dd-trace';

if (process.env.NODE_ENV === 'production') {
  tracer.init();
}
```

### Current vs. Expected behavior

Previously when running `next dev` there were no build issues at all. Once upgrading to 14.2.0, I now receive these error messages:

```
Module not found: Can't resolve 'graphql/utilities'
```

When I look at `dd-trace` package.json, graphql is listed as a devDependency. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.2.0 // Latest available version is detected (14.2.0).
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
  dd-trace: 4.20.0
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by coltonehrman** [comment]
Looks to be related to https://github.com/vercel/next.js/issues/64403#issue-2240289659

**Comment by drobannx** [comment]
Thanks. I think it looks to be related. I'm not sure how I missed that issue when I was looking. I can close this one.
