### ISSUE TITLE
make normal error output when global-error is filled incorrectly

### ISSUE THREAD

**Issue by MrOxMasTer** [vercel/next.js#64452]
### Link to the code that reproduces this issue

https://github.com/MrOxMasTer/shopco/commit/cc1b46827f2389fe5375391a8044b8747cd4afe2

### To Reproduce

1. run "npm run dev" WITHOUT turbo

### Current vs. Expected behavior

there was no error

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

Make a normal error output! how am I supposed to know from this error what my problem was?

![image](https://github.com/vercel/next.js/assets/59291123/a8566cba-264e-483b-b73a-b42c3cfc7e81)

And fix the turbo. You have it ignoring this error at all, but in normal 'dev' and 'build' you can see the error perfectly well.

And what does 'use server' have to do with it if the problem is in 'use client'?

<sub>[PACK-2977](https://linear.app/vercel/issue/PACK-2977/make-normal-error-output-when-global-error-is-filled-incorrectly)</sub>

**Comment by kdy1** [comment]
I can't reproduce by creating `app/error.js` with 

```js


export default function Error() {
    return <div>Error</div>
}
```

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/0ce5d8ad-19b4-44f4-bec2-f8635c9d6ba8">
