### ISSUE TITLE
`next dev` and `next build` crashing in `next@>=14.2.1-canary.4` on Linux

### ISSUE THREAD

**Issue by steve-marmalade** [vercel/next.js#64468]
### Link to the code that reproduces this issue

https://github.com/marmalade-labs/canary-crash

### To Reproduce

Run any of the following (possibly only affects Linux):

- `pnpm dev`
- `pnpm run build`
- Deploy to Vercel

## pnpm dev
```
➜  canary-crash git:(main) pnpm dev

> canary-crash@0.1.0 dev /home/stevie/code/canary-crash
> next dev

  ▲ Next.js 14.2.1-canary.4
  - Local:        http://localhost:3000

 ✓ Starting...
➜  canary-crash git:(main) 
➜  canary-crash git:(main) echo $?
0
➜  canary-crash git:(main) 
```

## pnpm build
```
➜  canary-crash git:(main) pnpm run build -d

> canary-crash@0.1.0 build /home/steve/code/canary-crash
> next build "-d"

  ▲ Next.js 14.2.1-canary.4

   Creating an optimized production build ...
➜  canary-crash git:(main) 
➜  canary-crash git:(main) echo $?
0
```

## Deploy to Vercel (with Node v 18)

```
  ▲ Next.js 14.2.1-canary.4
   Creating an optimized production build ...
 ⚠ Attempted to load @next/swc-linux-x64-gnu, but an error occurred: /vercel/path0/node_modules/.pnpm/@next+swc-linux-x64-gnu@14.2.1-canary.4/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node: ELF load command past end of file
 ⚠ Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
 ⨯ Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
> Build error occurred
Error: Jest worker encountered 1 child process exceptions, exceeding retry limit
    at ChildProcessWorker.initialize (/vercel/path0/node_modules/.pnpm/next@14.2.1-canary.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/index.js:1:11580)
    at ChildProcessWorker._onExit (/vercel/path0/node_modules/.pnpm/next@14.2.1-canary.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/index.js:1:12545)
    at ChildProcess.emit (node:events:529:35)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12) {
  type: 'WorkerError'
}
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 01:47:33 +0000
  Available memory (MB): 31886
  Available CPU cores: 8
Binaries:
  Node: 18.18.2
  npm: 10.5.2
  Yarn: 1.22.22
  pnpm: 8.15.5
Relevant Packages:
  next: 14.2.1-canary.4 // Latest available version is detected (14.2.1-canary.4).
  eslint-config-next: 14.2.1-canary.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router, Operating System (Windows, MacOS, Linux)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), Vercel (Deployed)

### Additional context

This may be a Linux-only issue, since @ztanner was not able to reproduce, per https://github.com/vercel/next.js/issues/64432#issuecomment-2054075569

One possible clue is that https://www.npmjs.com/package/@next/swc-linux-x64-gnu/v/14.2.1-canary.4 has an unpacked size of 88.2 MB whereas https://www.npmjs.com/package/@next/swc-linux-x64-gnu/v/14.2.1-canary.3 has an unpacked size of 131 MB. So maybe there was an issue generating this linux build artifact in the latest canary?

**Comment by vordgi** [comment]
Same thing. Ubuntu (_Github workflow_):

![image](https://github.com/vercel/next.js/assets/91429106/09926224-aaf2-4d73-8216-89ee3136a8ef)

_On Windows it works with no problems_

**Comment by steve-marmalade** [comment]
Confirmed that this is still an issue in `14.2.1-canary.5`.

FWIW https://www.npmjs.com/package/@next/swc-linux-x64-gnu/v/14.2.1-canary.5 is also 88MB, so that theory still stands (although it now seems unlikely it was due to a flaky build).

**Comment by mwskwong** [comment]
> Same thing. Ubuntu (_Github workflow_):
> 
> ![image](https://private-user-images.githubusercontent.com/91429106/322286735-09926224-aaf2-4d73-8216-89ee3136a8ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNDgyNDYsIm5iZiI6MTcxMzE0Nzk0NiwicGF0aCI6Ii85MTQyOTEwNi8zMjIyODY3MzUtMDk5MjYyMjQtYWFmMi00ZDczLTgyMTYtODllZTMxMzZhOGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAyMjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNGMwODQ4MGY0ZjMzZDU2YzA5MGNkYWVkN2RhYWIzNGZjZDc5ZWY3ZGQzMjIzYWY1NTUyODVlODljOTA4NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._75IiAgFa3Y70GIsZ32WRdsmXrURXDbT7v5fMgsMX6g)
> 
> _On Windows it works with no problems_

Yep, I have a Windows machine and it works normally if I run `next build`, but as soon as I deploy to Vercel, which is using Linux, I either get a pretty generic error:

```
Error: No serverless pages were built
```

Or sometimes a more specific one:

```
 ⚠ Attempted to load @next/swc-linux-x64-gnu, but an error occurred: /vercel/path0/node_modules/@next/swc-linux-x64-gnu/next-swc.linux-x64-gnu.node: ELF load command past end of file
 ⚠ Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
 ⨯ Failed to load SWC binary for linux/x64, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
> Build error occurred
Error: Jest worker encountered 1 child process exceptions, exceeding retry limit
    at ChildProcessWorker.initialize (/vercel/path0/node_modules/next/dist/compiled/jest-worker/index.js:1:11580)
    at ChildProcessWorker._onExit (/vercel/path0/node_modules/next/dist/compiled/jest-worker/index.js:1:12545)
    at ChildProcess.emit (node:events:529:35)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12) {
  type: 'WorkerError'
}
Error: Command "npm run build" exited with 1
```

It is not reproducible as soon as I roll back to `14.2.1-canary.3`.

**Comment by franky47** [comment]
Same issue in [`nuqs`](https://github.com/47ng/nuqs/actions/workflows/test-against-nextjs-release.yml), `next build` started failing with `14.2.1-canary.4`, and still does with `14.2.1-canary.5`. 14.2.1-canary.3 passes fine.

The worst part of this is that Turborepo caches the failed output, so retries will use the failed cache.

**Comment by mmiszy** [comment]
Same issue on Vercel:
`Error: Command "pnpm run build" exited with SIGBUS`

**Comment by faresharmali** [comment]
Having the same issue with vercel 
![image](https://github.com/vercel/next.js/assets/53355769/ead73d18-cf3d-401b-8f56-e1c8807d9232)

**Comment by timneutkens** [comment]
Landed https://github.com/vercel/next.js/pull/64493 and triggered a new canary release. Will monitor when it's published.

**Comment by franky47** [comment]
@timneutkens I can confirm `14.2.1-canary.6` fixed the build issue.

https://github.com/47ng/nuqs/actions/runs/8688135747

**Comment by steve-marmalade** [comment]
Awesome, thanks @timneutkens
