### ISSUE TITLE
Turbopack issue with including dependency via 'link:'

### ISSUE THREAD

**Issue by dinkelspiel** [vercel/next.js#64472]
### Link to the code that reproduces this issue

https://github.com/dinkelspiel/turbopack-issue-dependency-link

### To Reproduce

1. Clone the repository
2. Enter the `./app` directory
3. Run `pnpm install`
4. Run `pnpm dev`

### Current vs. Expected behavior

The current behavior is that the local library included in the package.json via `"library": "link:../library"`, if running with the `--turbo` flag. Can't resolve the local repository and gives a `Module not found: Can't resolve 'library/hw'` but if the project isn't running with the `--turbo` flag the library is found and the project works.

The expected behavior is that the `--turbo` flag and the regular dev works the same and that the `--turbo` flag finds the local dependency.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000
  Available memory (MB): 15302
  Available CPU cores: 16
Binaries:
  Node: 20.12.1
  npm: 10.5.0
  Yarn: N/A
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ForsakenHarmony** [comment]
This is expected behavior, Turbopack doesn't support reading files (or symlinks) outside your project directory.

There is a workaround, which is setting `experimental.outputFileTracingRoot` in `next.config.js`

`next.config.mjs`
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
	experimental: {
    	outputFileTracingRoot: path.join(__dirname, '../'),
	}
};

export default nextConfig;
```

**Comment by timneutkens** [comment]
Up to date documentation:
https://nextjs.org/docs/app/api-reference/config/next-config-js/turbopack#root-directory
