### ISSUE TITLE
`next dev --turbo` unable to import ESM-only packages when marked with `serverComponentsExternalPackages`

### ISSUE THREAD

**Issue by dstaley** [vercel/next.js#64525]
### Link to the code that reproduces this issue

https://github.com/dstaley/next-turbo-external-esm

### To Reproduce

1. `npm run dev:turbo`
2. Get error "The package seems invalid. require() resolves to a EcmaScript module, which would result in an error in Node.js."
3. `npm run dev`
4. Confirm that the page renders

### Current vs. Expected behavior

Current behavior:
```
Package srcset (serverComponentsExtenalPackages or default list) can't be external
The request srcset matches serverComponentsExtenalPackages (or the default list), but it can't be external:
The package seems invalid. require() resolves to a EcmaScript module, which would result in an error in Node.js.
```

Expected behavior:
When running with `next dev --turbo` ESM-only packages that have been marked with `serverComponentsExternalPackages` should still be correctly imported.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Jan 11 04:09:03 UTC 2024
  Available memory (MB): 32101
  Available CPU cores: 16
Binaries:
  Node: 18.19.0
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Module resolution (CJS / ESM, module resolving), Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This reproduction uses the [`srcset`](https://www.npmjs.com/package/srcset) package which is ESM-only.

<sub>[PACK-2967](https://linear.app/vercel/issue/PACK-2967/next-dev-turbo-unable-to-import-esm-only-packages-when-marked-with)</sub>

**Comment by RPDeshaies** [comment]
As a general FYI, the same issue also affects [Shiki](https://shiki.style/) 

![localhost3000en-uscomponentsaccordions (Arc - CleanShot) 2024-06-06 at 12 31 49](https://github.com/vercel/next.js/assets/6224111/af6a0748-596a-4eb8-adb4-1fc855ca1b24)

**Comment by Rahim-444** [comment]
I'm having the same issue here, did you find a solution?
