### ISSUE TITLE
Naver WebToon Poster Image upstream 403 Error

### ISSUE THREAD

**Issue by INIRU** [vercel/next.js#64533]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:59 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

Image optimization (next/image, next/legacy/image)

### What browser are you using? (if relevant)

Arc 1.38.0 (48670)

### How are you deploying your application? (if relevant)

next dev (local)

### Describe the Bug

There is an error that the image of the Naver WebToon could not get as a 403 upstream error.

```bash
% curl https://image-comic.pstatic.net/webtoon/800506/thumbnail/thumbnail_IMAG21_21640049-34da-44e5-82d7-bbb7aca3a3f8.jpg -I
HTTP/2 403 
server: AkamaiGHost
mime-version: 1.0
content-type: text/html
content-length: 501
expires: Tue, 16 Apr 2024 01:44:32 GMT
date: Tue, 16 Apr 2024 01:44:32 GMT
```

```bash
upstream image response failed for https://image-comic.pstatic.net/webtoon/800506/thumbnail/thumbnail_IMAG21_21640049-34da-44e5-82d7-bbb7aca3a3f8.jpg 403
```

### Expected Behavior

Then you will see this error (also related to https://github.com/vercel/next.js/issues/53715 and https://github.com/vercel/next.js/issues/56025 issue)

### To Reproduce

1. termial `npx create-next-app`

2. Add the following syntax to src/app/page.tsx
```tsx
// /app/page.tsx

import Image from 'next/image';

export default function Home() {
  return (
    <main className='flex min-h-screen flex-col items-center justify-between p-24'>
      <Image
        width={52}
        height={52}
        alt='2'
        src={
          'https://image-comic.pstatic.net/webtoon/800506/thumbnail/thumbnail_IMAG21_21640049-34da-44e5-82d7-bbb7aca3a3f8.jpg'
        }
      ></Image>
    </main>
  );
}
```

3. `npm run dev` and  Access http://localhost:3000

**Comment by shnoru1** [comment]
The 403 error you're encountering is an upstream error and is not related to Next.js. From the request you sent, it seems like an additional header indicating that the request is coming from your browser is required. To resolve this error, you can add the 'user-agent' header appropriately.
As an example, you can use the following curl command to make a successful request:
`curl -vvv https://image-comic.pstatic.net/webtoon/800506/thumbnail/thumbnail_IMAG21_21640049-34da-44e5-82d7-bbb7aca3a3f8.jpg -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.21 (KHTML, like Gecko) Chrome/19.0.1042.0 Safari/535.21' --output image.jpg
`

**Comment by INIRU** [comment]
Can I add a header to the NextJS Image Component???

**Comment by shnoru1** [comment]
Yes, you can add header on fetch method.
