### ISSUE TITLE
redirect in Server Actions & route.push do not work in Intercepting Routes anymore

### ISSUE THREAD

**Issue by K1NXZ** [vercel/next.js#64535]
### Link to the code that reproduces this issue

https://github.com/K1NXZ/nextjs-intercept-redirect

### To Reproduce

1. Start the application with `pnpm dev`
2. Navigate to `http://localhost:3000`
3. Click a link to open an intercepting route
4. Submit a form

### Current vs. Expected behavior

I expected to get redirected to the root `/` but nothing happens after submitting a form and performing a server action.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.15.6
Relevant Packages:
  next: 14.3.0-canary.4 // Latest available version is detected (14.3.0-canary.4).
  eslint-config-next: 14.3.0-canary.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

I noticed this bug got introduced in 14.2.0 and is still in 14.3.0-canary.4.

**Comment by mubashir-zenkoders** [comment]
I am too getting the same issue, programmatical routing is not working inside server actions.

**Comment by denexapp** [comment]
common ztanner W
