### ISSUE TITLE
Can't resolve child_process when using any of cron packages

### ISSUE THREAD

**Issue by andrejmoltok** [vercel/next.js#64547]
### Link to the code that reproduces this issue

https://github.com/andrejmoltok/oceans5js

### To Reproduce

1. Start the app with `npm run dev`
2. Click on `SignIn` link
3. Error occurs

### Current vs. Expected behavior

I want to use cron-jobs in my next app with node-cron pacakge. I tried other cron packages but yielded the same error of `Can't resolve child_process`

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01)
  Available memory (MB): 7824
  Available CPU cores: 4
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I am testing this on the latest version of NextJS 14.2.1

**Comment by timneutkens** [comment]
https://github.com/andrejmoltok/oceans5js/blob/2cb61e18702501a65339d9ac2cfd704d8c028921/src/actions/signin/accountUnLockCron.ts#L4

You forgot to add `"use server"` to the actions.
