### ISSUE TITLE
Different behavior with and without `--turbo` flag in `next dev` command

### ISSUE THREAD

**Issue by masakinihirota** [vercel/next.js#64552]
### Link to the code that reproduces this issue

https://github.com/masakinihirota/next_dev_i18n

### To Reproduce

Description:

I am experiencing different behaviors when running the `next dev` command with and without the `--turbo` flag in my Next.js application.

Problem
The language conversion function in i18n does not work.

Steps to reproduce:

1. Run `next dev` command without `--turbo` flag.
2. Cannot convert from English to Japanese.
4. Run `next dev --turbo` command.
5. I can convert from English to Japanese.

Expected result:

The behavior of the application should be consistent regardless of whether the `--turbo` flag is used.

Actual result:

The behavior of the application differs when the `--turbo` flag is used compared to when it is not used.

Additional information:

I am running a DB called Supabase with Back.
This is not related to the problem part, but this code will not work without setting environment variables.

### Current vs. Expected behavior

next 14.1.0
The language conversion did not work when running with

>>ncu -u
- next 14.1.0
+ next 14.2.1

When I updated Next.js.
It stopped even starting.

### Provide environment information

```bash
>  npx --no-install next info

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 28563
  Available CPU cores: 12
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.1
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@masakinihirota By the way, this is the error I get when I try to build your project. We recommend not requiring any steps like this when creating a [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) so we can expedite the process for everyone as we go through issues.

![CleanShot 2024-04-17 at 15 06 32@2x](https://github.com/vercel/next.js/assets/28912696/93ee11c6-1e82-45ff-abdc-359404480457)

**Comment by masakinihirota** [comment]
https://github.com/masakinihirota/next_dev_i18n

Edited to work at minimum.

``package.json
  "dev": "next dev --turbo",.

````

Start the local server.

```terminal
pnpm run dev

````

http://localhost:3000
English to Japanese conversion is not working on the top page.

----------------------------------------

Drop the local server once.

Edit.

```package.json
  "dev": "next dev",.

```

Start the local server.

```terminal
pnpm run dev

````

http://localhost:3000
The English to Japanese conversion is working as expected on the top page.



Translated with www.DeepL.com/Translator (free version)
