### ISSUE TITLE
Docs: [Bug] I cannot switch to page router docs in mobile

### ISSUE THREAD

**Issue by afiiif** [vercel/next.js#64560]
### What is the improvement or update you wish to see?

Step to repro:
1. Open https://nextjs.org/docs in **mobile browser**.
    - Or, use touch simulation
3. Tap on "Using App Router"
4. Result:
    - Current: nothing happened
    - Expect: dropdown to choose app router docs or page router docs

![ezgif-4-cf35b9f193](https://github.com/vercel/next.js/assets/43276538/1ca69d34-3875-419a-b398-6268c72fdad9)

### Is there any context that might help us understand?

-

**Comment by icyJoseph** [comment]
Yeah, I can also reproduce this, on real devices too.

**Comment by ViktorYermak** [comment]
Duplicate of #64292

**Comment by samcx** [comment]
Closing since this is a duplicate.
