### ISSUE TITLE
 Error in parallel route using Turbopack for next dev

### ISSUE THREAD

**Issue by nctay** [vercel/next.js#64600]
### Link to the code that reproduces this issue

https://github.com/nctay/next-turbopack-parallel-routes

### To Reproduce

1.Start the application in development with turbopack enabled (next dev --turbo)

### Current vs. Expected behavior

Expected correctly working dev server using parallel routes and turbopack.

Got this error starting dev:

```
> next dev --turbo

  ▲ Next.js 14.2.1 (turbo)
  - Local:        http://localhost:3000

 ✓ Starting...
[Error: Invalid segment Parallel("comments"), catch all segment must be the last segment (segments: [Static("news"), Group("page"), CatchAll("slug")])

Debug info:
- Execution of get_entrypoints_with_issues failed
- Execution of Project::entrypoints failed
- Execution of AppProject::routes failed
- Execution of directory_tree_to_entrypoints_internal failed
- Execution of directory_tree_to_entrypoints_internal failed
- Execution of directory_tree_to_entrypoints_internal failed
- Execution of directory_tree_to_entrypoints_internal failed
- Execution of directory_tree_to_loader_tree failed
- Invalid segment Parallel("comments"), catch all segment must be the last segment (segments: [Static("news"), Group("page"), CatchAll("slug")])] {
  code: 'GenericFailure'
}
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.0
  npm: 10.4.0
  Yarn: 1.22.22
  pnpm: 8.15.1
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Routing (next/router, next/navigation, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested my reproduction against latest stable release [14.2.1](https://www.npmjs.com/package/next/v/14.2.1) and  latest canary release [14.3.0-canary.6](https://www.npmjs.com/package/next/v/14.3.0-canary.6). Can reproduce the same issue on both.

Disabling turbopack option for dev resolves this error.

<sub>[PACK-2975](https://linear.app/vercel/issue/PACK-2975/error-in-parallel-route-using-turbopack-for-next-dev)</sub>

**Comment by fax1ty** [comment]
https://github.com/vercel/next.js/pull/63879#issuecomment-2033293246

**Comment by samcx** [comment]
@nctay Thank you for sharing! I was able to replicate this issue. Our team will take a look!

**Comment by nctay** [comment]
@ForsakenHarmony I don't quite understand why is this not an issue. There's an example repo with simplified version of real feature of our project. It's just a page with slug in url, this page has parts of content that depends on slug value and can be loaded in parallel/simultaneously.

**Comment by ForsakenHarmony** [comment]
@nctay but why not just import the components, I don't see why you would put them in a parallel route?
The whole point there is that the parallel route can do independent routing (or fall back to a default, or contain an interception)

Maybe your example is missing something that would explain why you want to put things in a parallel route?

**Comment by fax1ty** [comment]
Any news?

**Comment by samcx** [comment]
@nctay Let us know if the comment earlier made sense or if you still believe this is an issue!
