### ISSUE TITLE
Turbopack: CommonJS require import of 'canvas' fails to resolve when using react-pdf library

### ISSUE THREAD

**Issue by oliverjohns** [vercel/next.js#64657]
### Link to the code that reproduces this issue

https://github.com/oliverjohns/turbopack-import-problem-example

### To Reproduce

follow the repo readme
1. start application with npm run dev -- --turbo
2. click the route "to test page"
3. then watch the error occur

### Current vs. Expected behavior

Current behavior:
When using react-pdf according to the code example provided and running `npm run dev -- --turbo`, the commonjs import  of canvas fails, giving us this input:

```
./node_modules/pdfjs-dist/build/pdf.js:6247:19
Module not found: Can't resolve 'canvas'
  6245 | class NodeCanvasFactory extends _base_factory.BaseCanvasFactory {
  6246 |   _createCanvas(width, height) {
> 6247 |     const Canvas = require("canvas");
       |                    ^^^^^^^^^^^^^^^^^
  6248 |     return Canvas.createCanvas(width, height);
  6249 |   }
  6250 | }

https://nextjs.org/docs/messages/module-not-found
```

Expected behavior
Following the steps I expected turbopack to be able to handle this import of react-pdf/canvas since it works in Webpack without any issues.

### Provide environment information

```bash
Operating system:
MacOS ARM M3

Node version: v20.9.0
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

My previous issue was closed #64165 , so I opened a new one to highlight this problem. The issue is not solved in on 14.2.0-canary.63 , neither on 14.2.1 .

**Comment by wyattjoh** [comment]
Please do not open duplicate issues, adding comments to the original issue should be sufficiant.

I've tested this on `14.1.4` and the most recent `14.2.1` and both seem to be rendering the PDF viewer for the reproduction you've attached. Note that your reproduction didn't include a PDF file at `public/123`, after adding one, it seemed to work as expected.
