### ISSUE TITLE
After adding the middleware, the webpage appears twice

### ISSUE THREAD

**Issue by caixingyue** [vercel/next.js#64668]
### Link to the code that reproduces this issue

https://github.com/mui/material-ui/tree/master/examples/material-ui-nextjs-ts

### To Reproduce

1.download code:
curl https://codeload.github.com/mui/material-ui/tar.gz/master | tar -xz --strip=2  material-ui-master/examples/material-ui-nextjs-ts

2.install code:
npm i

3.create a middleware to src:
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
export function middleware(request: NextRequest) {
  return NextResponse.next()
}
export const config = {
  matcher: ['/((?!api|_next/static|_next/image|.*\\.png$).*)'],
}

4.open http://localhost:3000/about
5.multiple accesses appear on the terminal
![WX20240417-232403@2x](https://github.com/vercel/next.js/assets/39073687/4e25d350-4260-4dda-aadd-4063c014387b)

### Current vs. Expected behavior

I only ran the page once and got GET /about twice in the terminal 

GET /about 200 in 168ms
 GET /about 200 in 159ms
 GET /favicon.ico 200 in 7ms

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 20.11.0
  npm: 10.5.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@caixingyue This should be fixed in [v14.3.0-canary.6](https://github.com/vercel/next.js/releases/tag/v14.3.0-canary.6)! → https://github.com/vercel/next.js/pull/64549
