### ISSUE TITLE
14.2.1 next dev --turbo still fail

### ISSUE THREAD

**Issue by fungilation** [vercel/next.js#64684]
### Link to the code that reproduces this issue

pnpm add @types/js-cookie (3.0.6) -> `import Cookies from 'js-cookie' in any app` code

### To Reproduce

next dev --turbo

### Current vs. Expected behavior

terminal errors on `next dev --turbo`

```
 ⨯ ./src/components/layout/index.tsx:4:1
Module not found: Can't resolve 'js-cookie'
  2 | import { useRouter } from 'next/router'
  3 | import { useAuthenticationStatus } from '@nhost/nextjs'
> 4 | import Cookies from 'js-cookie'
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  5 |
  6 | import Navbar from 'components/navbar'
  7 | import Footer from 'components/footer'

https://nextjs.org/docs/messages/module-not-found


 ⨯ ./node_modules/.pnpm/slick-carousel@1.8.1_jquery@3.7.1/node_modules/slick-carousel/slick/slick-theme.css:17:159
Module not found: Can't resolve './fonts/slick.svg#slick'
  15 |     src: url('./fonts/slick.eot');
  16 |     src: url('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('svg');
> 17 | }
     |  ^
  18 | /* Arrows */
  19 | .slick-prev,
  20 | .slick-next

https://nextjs.org/docs/messages/module-not-found
```

### Provide environment information

```bash
next info                                                                                               

Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 21.7.3
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 9.0.2
Relevant Packages:
  next: 14.2.1 // Latest available version is detected (14.2.1).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

blitz -v                                                                                              ```
Blitz version: 2.0.8 (local)
macOS Sonoma | darwin-x64 | Node: v21.7.3

 Package manager: pnpm

  System:
    OS: macOS 14.4.1
    CPU: (8) x64 Apple M1
    Memory: 384.93 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
  npmPackages:
    @blitzjs/auth: ~2.0.8 => 2.0.8
    @blitzjs/next: ~2.0.8 => 2.0.8
    @blitzjs/rpc: ~2.0.8 => 2.0.8
    @prisma/client: Not Found
    blitz: ~2.0.8 => 2.0.8
    next: ^14.2.1 => 14.2.1
    prisma: Not Found
    react: ~18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ~5.3.3 => 5.3.3
```
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Next 14.2.1, together with Blitz 2.0.8

**Comment by timneutkens** [comment]
Replied here: https://twitter.com/timneutkens/status/1785593430820659644
