### ISSUE TITLE
Docs: Bundle Analyzer recommended code leads to warning when turbopack is enabled

### ISSUE THREAD

**Issue by sean-rallycry** [vercel/next.js#64739]
### What is the improvement or update you wish to see?

adjust the code example to only wrap the analyzer when in active use

### Is there any context that might help us understand?

when running in turbo mode with the bundle analyzer wrapper the following warning is displayed:

 ⚠ Webpack is configured while Turbopack is not, which may cause problems.
 ⚠ See instructions if you need to configure Turbopack:
  https://nextjs.org/docs/app/api-reference/next-config-js/turbo

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/optimizing/bundle-analyzer

**Comment by delbaoliveira** [comment]
Thank you @sean-rallycry, closing this issue since you've opened a [PR](https://github.com/vercel/next.js/pull/64740). We can follow up from there.
