### ISSUE TITLE
Redirecting to same page (with different parameters) does not reload the entire page

### ISSUE THREAD

**Issue by gmantri** [vercel/next.js#64793]
### Link to the code that reproduces this issue

https://github.com/gmantri/nextjs-ssr-redirect-issue

### To Reproduce

1. Clone the repository.
2. Navigate to the project folder and then to `my-app` folder.
3. Run the app using `npm run dev`.
4. Click on `Add Client Item` a couple of times. You should see some lines added.
5. Now click on `Click Me` button to call redirect.
6. The time on the 1st line changes however you will notice that the items added via `Add Client Item` still remains. 

### Current vs. Expected behavior

In my application, I fetch some items from the server and display them. Then I fetch some more items on the client side. Now I want to reload the page with some different query parameters. Currently I am noticing that the content I fetched through the server-side call is getting changed however the content I fetched via client-side calls still remains on the page. I was expecting that my entire page will be reloaded and I will only see the content I fetched via server-side call. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.2.2 // Latest available version is detected (14.2.2).
  eslint-config-next: 14.2.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by schimi-dev** [comment]
What you describe is actually the intended behaviour of the framework. Client-side state should be preserverd, so unlike the path `params` the `searchSarams` are not part of the `key` recreating a page. Whenever the dynamic params change client side state of that page is reset. Whenever the searchParams change that state is not reset.

**Comment by gmantri** [comment]
@schimi-dev - Thanks for the reply. Can you point me to the documentation which talks about this behavior? This [link](https://nextjs.org/docs/app/building-your-application/routing/redirecting#redirect-function) does not mention anything regarding this. Also, why separate behavior when redirecting to the same page and a different page? When I redirect to another page (that I have previously visited), the client-side state on that page is not preseverd.

**Comment by schimi-dev** [comment]
This is the corresponding pull request: 
https://github.com/vercel/next.js/pull/49047

You can check out the commits to view the files in the Next.js code. Basically, params are part of the page key, searchParams are not. This behaviour is intended and also specified in an explicit test case. Generally, the mental model seems to be server centric routing with SPA like behaviour, therefore as much  client-side state as makes sense is preserved by the framework. However, I agree that this should probably also be part of the docs and not only derivable from a PR and the source code.

**Comment by gmantri** [comment]
@schimi-dev - Thanks for sharing the PR.
