### ISSUE TITLE
Docs: 'use client' documentation is unclear about SSR

### ISSUE THREAD

**Issue by sergey-hippo** [vercel/next.js#64797]
### What is the improvement or update you wish to see?

'use client' documentation doesn't make it clear, that client components are also rendered on server and participate in hydration. Also, 'use client' docs don't show any way to write a component that bypasses hydration and is only rendered on client.

### Is there any context that might help us understand?

https://github.com/vercel/next.js/issues/46518#issuecomment-1448048879

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/rendering#client-components

**Comment by philwolstenholme** [comment]
I think the page that Tim linked to in https://github.com/vercel/next.js/issues/46518#issuecomment-1448048879 got edited by the docs team and split out into multiple pages. You can see Tim linked to the `#client-components` fragment, but that doesn't exist on the '[Rendering](https://nextjs.org/docs/app/building-your-application/rendering)' page anymore. Instead, all the client component info got moved to [this page](https://nextjs.org/docs/app/building-your-application/rendering/client-components) which has the SSRing mentioned in the first sentence:

> Client Components allow you to write interactive UI that is [**prerendered on the server**](https://github.com/reactwg/server-components/discussions/4) and can use client JavaScript to run in the browser.

If you search the docs for 'disable SSR' the only result is https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#skipping-ssr which has a 'Skipping SSR' page. Maybe the client components page could link to that page somewhere?

**Comment by sergey-hippo** [comment]
@philwolstenholme oh, I see, so my confusion was mostly caused by an out-of-date link.

Regarding `skipping-ssr`, what are advantages of `dynamic(() => import(` approach versus pure React approach like described [here](https://stackoverflow.com/questions/53139884/next-js-disable-server-side-rendering-on-some-pages/57512843#57512843)?

**Comment by leerob** [comment]
Closing this as addressed from:

> Client Components allow you to write interactive UI that is https://github.com/reactwg/server-components/discussions/4 and can use client JavaScript to run in the browser.
