### ISSUE TITLE
Parallel routing with intercepting on as modal / page have unexpected behavior

### ISSUE THREAD

**Issue by yaba101** [vercel/next.js#64808]
### Link to the code that reproduces this issue

https://github.com/yaba101/parallel-intercept-routing

### To Reproduce

1. First, run the development server: pnpm run dev
2. Go to /
3. Click Sign in button ( which trigger modal )
4. hard refresh the page
5. click sign-up button ( which open modal on to off sign-in, not as a page
[Screencast from 2024-04-20 02-28-08.webm](https://github.com/vercel/next.js/assets/63213576/b5729417-3200-483a-992a-ff8a66d5348b)
) 

### Current vs. Expected behavior

Current:
on hard refresh the modal changed to page and when to try navigate between as page it open modal on top of current page.
Expected:
on hard refresh the modal changed to page and when to try navigate between as page it should navigate as page not trigger modal.
[Screencast from 2024-04-20 02-28-08.webm](https://github.com/vercel/next.js/assets/63213576/2e1858fe-7528-45f4-98b0-56771778c525)

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #26-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar  5 21:19:28 UTC 2024
  Available memory (MB): 15801
  Available CPU cores: 8
Binaries:
  Node: 20.11.1
  npm: 10.5.0
  Yarn: N/A
  pnpm: 8.15.5
Relevant Packages:
  next: 14.2.2 // Latest available version is detected (14.2.2).
  eslint-config-next: 14.2.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

**Comment by ztanner** [comment]
Hi @yaba101! With route interception, any soft navigation that matches the intercepted route will trigger the interception. However, you can make use of route groups with different layouts to have finer control over which layout renders the interception modal + page, versus just rendering the page, without changing your URL structure. You can learn a bit more about route groups [here](https://nextjs.org/docs/app/building-your-application/routing/route-groups).

I've re-created your app in CodeSandbox (didn't get the styles loaded, but I added some special text to the modal components so you could tell the difference): https://codesandbox.io/p/devbox/amazing-curie-3m37tz?file=%2Ftailwind.config.ts%3A81%2C1.

Here's a quick video, after I made the changes to your reproduction:

https://github.com/vercel/next.js/assets/1939140/0e679fd0-10aa-4fc7-95c1-d512812c85cf


Going to close this out as it doesn't look like there's a bug here, but don't hesitate to ask any follow-up questions!

**Comment by yaba101** [comment]
@ztanner Thank you so much for your response!
so making the intercepting route to routing grouping is the fix ?
