### ISSUE TITLE
[turbopack]: importing `tailwind/tailwind.css` fails with `serverComponentsExternalPackages` error

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#64837]
### Link to the code that reproduces this issue

https://github.com/stefanprobst/issue-turbopack-tailwind

### To Reproduce

1. clone [repo](https://github.com/stefanprobst/issue-turbopack-tailwind)
2. `pnpm install`
3. `pnpm run dev` (`next dev --turbo`)
4. open http://localhost:3000 and see error message (see below)

### Current vs. Expected behavior

**current:**

importing `tailwind/tailwind.css` fails with the following error message when running `next dev --turbo`:

![Screenshot_20240421_082509](https://github.com/vercel/next.js/assets/20753323/c1703568-ae28-49c6-972c-9276853e8501)

```
 ⨯ ./node_modules/.pnpm/tailwindcss@3.4.3/node_modules/tailwindcss/tailwind.css
Package tailwindcss (serverComponentsExternalPackages or default list) can't be external
The request tailwindcss/tailwind.css matches serverComponentsExternalPackages (or the default list), but it can't be external:
Only .mjs, .cjs, .js, .json, or .node can be handled by Node.js.
```

**expected**:

importing `tailwind/tailwind.css` should work, like it does with webpack (running `pnpm next dev` without `--turbo` works fine).

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2
  Available memory (MB): 32032
  Available CPU cores: 4
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.5
Relevant Packages:
  next: 14.3.0-canary.14 // Latest available version is detected (14.3.0-canary.14).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[PACK-3013](https://linear.app/vercel/issue/PACK-3013/[turbopack]-importing-tailwindtailwindcss-fails-with)</sub>

**Comment by henrybabbage** [comment]
Experiencing the same issue

**Comment by ForsakenHarmony** [comment]
You probably don't want to import `tailwind/tailwind.css` as that will completely ignore your tailwind config.

Currenlty the best way is to use it through postcss: https://tailwindcss.com/docs/installation/using-postcss

**Comment by ForsakenHarmony** [comment]
Ah, you're right, seems we need to add an exception for CSS files as externals.

**Comment by henrybabbage** [comment]
Any fix for this error? Seeing this too.
