### ISSUE TITLE
local dev server is painfully slow

### ISSUE THREAD

**Issue by 0meenakshi0** [vercel/next.js#64905]
### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.17.0
      npm: 9.6.7
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.2
      eslint-config-next: 13.4.2
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.5
```

### Describe the Bug

local development server is taking too long to start and frequently crashes; which is counterproductive.
We have tried looking for basic causes that can be contributing to it but nothing substantial was picked. We need help is figuring out the reason.

### Expected Behavior

Local dev server shouldn't eat up all of your memory and shouldn't be extremely slow.

### To Reproduce

It's an enterprise app; we will need to add some one to the repo. Please let us know who can help here from nextjs team and we shall extend the access rights.

**Comment by samcx** [comment]
@0meenakshi0 I highly recommend working to upgrade to the latest so you can use the latest improvements and fixes to the local development server (e.g., https://nextjs.org/blog/next-14-2#turbopack-for-development-release-candidate).

In the meantime, we will not be able to triage any issues without a <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> and not on the latest Next.js version.
