### ISSUE TITLE
Docs: Pages and layouts section not opening 

### ISSUE THREAD

**Issue by prathu9** [vercel/next.js#65015]
### What is the improvement or update you wish to see?

Fix pages and layouts for app router documentation, currently it is showing 404 not found page.

### Is there any context that might help us understand?

I was going through `Routing` section for **App Router** in next.js documentation. 
I tried to open `Pages and Layouts` section but it shows 404 page not found.

![image](https://github.com/vercel/next.js/assets/30414105/08b036bf-d748-485e-89cf-50f6e8e8eabf)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/pages

**Comment by samcx** [comment]
@prathu9 Can you share with us which link led to this page?

**Comment by prathu9** [comment]
@samcx I have shared link above

**Comment by samcx** [comment]
@prathu9 Fixing!

**Comment by samcx** [comment]
@prathu9 <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> !

**Comment by prathu9** [comment]
Yes it is fixed, Thanx 👍
