### ISSUE TITLE
Page won't rerender when initial searchparam is removed

### ISSUE THREAD

**Issue by LuiGeeDev** [vercel/next.js#65030]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/admiring-bush-58lfx2

### To Reproduce

1. Start the application.
2. Try clicking 'Change Query' button.
3. It will change query and the page will show query: newQuery.
4. As query stays on browser's url, refresh the browser.
5. Try clicking the button again.
6. URL changes, but page won't show query removed.

### Current vs. Expected behavior

Current: Page won't rerender when the initial query has removed. (It works when it is changed)
Expected: Page render again when the initial query has removed, like when it changed.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.2.0-canary.9 // There is a newer canary version (14.3.0-canary.22) available, please upgrade! 
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ezengaston** [comment]
Same issue here! So far, removing error.js has solved the problem for me.

**Comment by ezengaston** [comment]
I notice that in my case removing error.js solves the problem.

**Comment by LuiGeeDev** [comment]
Maybe some workaround who doesn't want to downgrade.
```
const params = new URLSearchParams(searchParams.toString());
params.delete('your-param'); // this doesn't work now with bug.
params.set('your-param', ''); // this will still work.
```

**Comment by icyJoseph** [comment]
We are experiencing this as well. Has there been any release notes, and such that would indicate, that this is the expected behavior?
