### ISSUE TITLE
SWC panicks when processing nested `styled-jsx` tags

### ISSUE THREAD

**Issue by sjchmiela** [vercel/next.js#65066]
### Link to the code that reproduces this issue

https://github.com/sjchmiela/swc-unwrap-panic

### To Reproduce

1. Start the application in development.
2. Open main page.
3. Observe Build Error 500 page being rendered and the following error being logged in console:

```
thread '' panicked at /Users/geist/.cargo/registry/src/index.crates.io-6f17d22bba15001f/styled_jsx-0.73.13/src/visitor.rs:597:44:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Current vs. Expected behavior

Instead of throwing a build error I expected the builder to throw the ["Nested `styled-jsx` tags detected" error](https://nextjs.org/docs/messages/nested-styled-jsx-tags). When SWC is disabled and Babel is transpiling code, this, more readable, error _is_ thrown.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 9.0.1
Relevant Packages:
  next: 14.3.0-canary.23 // Latest available version is detected (14.3.0-canary.23).
  eslint-config-next: N/A
  react: 18.3.0
  react-dom: 18.3.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Runtime, SWC

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

<sub>[NEXT-3241](https://linear.app/vercel/issue/NEXT-3241/swc-panicks-when-processing-nested-styled-jsx-tags)</sub>

**Comment by kdy1** [comment]
https://github.com/swc-project/plugins/pull/294 should fix it. I'll close this issue with a dependency update PR
