### ISSUE TITLE
Problem with Next.js Turbo Mode and Non-English Characters.

### ISSUE THREAD

**Issue by snickee4115** [vercel/next.js#65117]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/nextjs-turbo-mode-non-english-problem-d97vp3?file=%2Fapp%2Fpage.tsx%3A13%2C5

### To Reproduce

1.Enable turbo mode
2.Create a new component file or open an existing one within your Next.js project, such as page.tsx.
3.Insert or ensure the presence of non-English characters (e.g., Japanese, Chinese, Thai) in the file
4.Ensure the file contains the 'use client' directive.
5.Make a change in the file and observe the reloading behavior.

### Current vs. Expected behavior

In turbo mode, when editing files containing languages other than English and files with 'use client', pages should not reload repeatedly. Hot reload should work properly.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.3.0-canary.26 // There is a newer canary version (14.3.0-canary.28) available, please upgrade! 
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I have tested with older versions of Next.js and found that reloading works normally until v14.1.1-canary.12. However, starting from v14.1.1-canary.13, this issue began to occur.

<sub>[PACK-3018](https://linear.app/vercel/issue/PACK-3018/problem-with-nextjs-turbo-mode-and-non-english-characters)</sub>

**Comment by Infectious-Smile** [comment]
+1

**Comment by timneutkens** [comment]
Thanks for the report! We'll take a look 💯
