### ISSUE TITLE
14.3.0-canary.28 fails with `node-module-in-edge-runtime`

### ISSUE THREAD

**Issue by r34son** [vercel/next.js#65118]
### Link to the code that reproduces this issue

https://github.com/r34son/profile/tree/v1.11.0

### To Reproduce

Issue reproduces only in docker
Build docker image on https://github.com/r34son/profile/tree/v1.11.0

Started after updating from 26 to 28 canary https://github.com/r34son/profile/commit/034541787ec900d5301a39ccd390991f097f7cf2

### Current vs. Expected behavior

Logs: https://github.com/r34son/profile/actions/runs/8861843720/job/24334139717#step:10:462

### Provide environment information

```bash
Docker on github actions
```

### Which area(s) are affected? (Select all that apply)

Runtime

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

**Comment by r34son** [comment]
I guess here is the fix #65112

**Comment by ztanner** [comment]
> I guess here is the fix #65112

Indeed! I’ve triggered a canary with the patch. Let us know if you are still encountering issues.
