### ISSUE TITLE
Error occurs when opening client page with turbopack enabled in "output: export" mode

### ISSUE THREAD

**Issue by By-Ha** [vercel/next.js#65151]
### Link to the code that reproduces this issue

https://codesandbox.io/p/github/By-Ha/next_error/master

### To Reproduce

1. enable turbopack, set output to export and mark 'use client' in any page
2. error occurred

### Current vs. Expected behavior

Current: 
![image](https://github.com/vercel/next.js/assets/46854508/4be03523-75ee-4e52-999d-93968bf4eab6)
Expected: 
render page

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 65350
  Available CPU cores: 20
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Output (export/standalone), Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ForsakenHarmony** [comment]
@By-Ha can't access the reproduction, are you still running into this on the latest turbo canary?

**Comment by timneutkens** [comment]
Verified this has been resolved on `next@canary`.
