### ISSUE TITLE
 React does not recognize the `fetchPriority` prop on a DOM element.

### ISSUE THREAD

**Issue by KDederichs** [vercel/next.js#65161]
### Link to the code that reproduces this issue

https://github.com/KDederichs/fetch-prio-reproducer

### To Reproduce

npm install 
jest

### Current vs. Expected behavior

```
jest
  console.error
    Warning: React does not recognize the `fetchPriority` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fetchpriority` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
        at img
        at /Users/USER/source_code/fetch-priority-reproducer/node_modules/next/src/client/image-component.tsx:212:5
        at /Users/USER/source_code/fetch-priority-reproducer/node_modules/next/src/client/image-component.tsx:372:5
        at Home

      4 | describe('Tests', () => {
      5 |     it('it renders without warning', async () => {
    > 6 |         const {container} = render(
        |                                   ^
      7 |             <Home/>
      8 |         )
      9 |     })

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3757:7)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3803:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3827:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:9541:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9830:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10950:3)
      at completeWork (node_modules/react-dom/cjs/react-dom.development.js:22232:17)
      at completeUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26632:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26607:5)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26505:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26473:7)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25777:74)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:47:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:180:26)
      at render (node_modules/@testing-library/react/dist/pure.js:271:10)
      at Object.<anonymous> (app/page.spec.tsx:6:35)
```

Should be no error there

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.15.1
Relevant Packages:
  next: 14.3.0-canary.30 // Latest available version is detected (14.3.0-canary.30).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image (next/image)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

<sub>[NEXT-3273](https://linear.app/vercel/issue/NEXT-3273/react-does-not-recognize-the-fetchpriority-prop-on-a-dom-element)</sub>

**Comment by saifbechan** [comment]
Having the same issue. Rolled back to NextJS v14.2.2 and React v18.2.0 and the issue is not there.

**Comment by daybert** [comment]
same waring, any use of Image from Next/Image

**Comment by chadlinden** [comment]
Same as https://github.com/facebook/react/issues/25682 ? Regression?

**Comment by styfle** [comment]
To be clear, the warning only happens when running jest, not `next dev` or `next build`, correct?

This sounds like an issue with `@testing-library/react`, not `next`.

**Comment by tr1s** [comment]
Same issue here after updating Next from `14.2.2` to `14.2.3` and React from `18.2.0` to `18.3.1`.

Rolling back Next to `14.2.2` did not fix the error, however, keeping Next at `14.2.3` and rolling just React back to `18.2.0` fixed the error.

@styfle this happens using `next dev`, I don't have any testing libraries in my `package.json`. This seems to be an issue with the latest React update.

**Comment by styfle** [comment]
I see. This also seems to impact Pages Router + react@18.3.1

- PR with the fix https://github.com/vercel/next.js/pull/65235

**Comment by shinwonse** [comment]
Was this issue solved? I have same issue with it 😢

**Comment by styfle** [comment]
This is fixed on the canary channel.

You can try it out today with `npm install next@canary`, thanks!

**Comment by Islam-AbdElhakiim** [comment]
@styfle Thank you it solved my issue, but can you explain to me what was the issue and how this package solved it?

**Comment by bungandy** [comment]
Happened on next 13.5.6 and react 18.2.0

**Comment by umachaVail** [comment]
@styfle After migrating from Next 12 to Next 13 (13.5.6), the react version was also bumped up to 18.3.1. Thus, projects with Next 13 are also being impacted by this error and we don't have the option to jump to the canary version without migrating to Next 14 first. A quick fix would be to drop the react version of our project to avoid the issue but that could lead to some problems down the line as well. Could there be a release for Next 13 to fix this issue?

**Comment by ktran1201** [comment]
So the solution is to upgrade NextJS to latest version?

**Comment by umachaVail** [comment]
> So the solution is to upgrade NextJS to latest version?

The fix for the issue is included in the latest canary versions of NextJS (which are released daily), I don't know of a stable release with the fix.

**Comment by osanchezestoko** [comment]
> This is fixed on the canary channel.
> 
> You can try it out today with `npm install next@canary`, thanks!

Canary didn't worked for me

**Comment by pritamgudekar** [comment]
> ### Link to the code that reproduces this issue
> https://github.com/KDederichs/fetch-prio-reproducer
> 
> ### To Reproduce
> npm install jest
> 
> ### Current vs. Expected behavior
> ```
> jest
>   console.error
>     Warning: React does not recognize the `fetchPriority` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `fetchpriority` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>         at img
>         at /Users/USER/source_code/fetch-priority-reproducer/node_modules/next/src/client/image-component.tsx:212:5
>         at /Users/USER/source_code/fetch-priority-reproducer/node_modules/next/src/client/image-component.tsx:372:5
>         at Home
> 
>       4 | describe('Tests', () => {
>       5 |     it('it renders without warning', async () => {
>     > 6 |         const {container} = render(
>         |                                   ^
>       7 |             <Home/>
>       8 |         )
>       9 |     })
> 
>       at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
>       at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
>       at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3757:7)
>       at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3803:21)
>       at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3827:3)
>       at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:9541:5)
>       at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9830:5)
>       at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10950:3)
>       at completeWork (node_modules/react-dom/cjs/react-dom.development.js:22232:17)
>       at completeUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26632:16)
>       at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26607:5)
>       at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26505:5)
>       at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26473:7)
>       at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25777:74)
>       at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
>       at act (node_modules/react/cjs/react.development.js:2582:11)
>       at node_modules/@testing-library/react/dist/act-compat.js:47:25
>       at renderRoot (node_modules/@testing-library/react/dist/pure.js:180:26)
>       at render (node_modules/@testing-library/react/dist/pure.js:271:10)
>       at Object.<anonymous> (app/page.spec.tsx:6:35)
> ```
> 
> Should be no error there
> 
> ### Provide environment information
> ```shell
> Operating System:
>   Platform: darwin
>   Arch: arm64
>   Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103
>   Available memory (MB): 16384
>   Available CPU cores: 8
> Binaries:
>   Node: 20.11.0
>   npm: 10.2.4
>   Yarn: 1.22.19
>   pnpm: 8.15.1
> Relevant Packages:
>   next: 14.3.0-canary.30 // Latest available version is detected (14.3.0-canary.30).
>   eslint-config-next: N/A
>   react: 18.3.1
>   react-dom: 18.3.1
>   typescript: 5.1.3
> Next.js Config:
>   output: N/A
> ```
> 
> ### Which area(s) are affected? (Select all that apply)
> Image (next/image)
> 
> ### Which stage(s) are affected? (Select all that apply)
> next dev (local)
> 
> ### Additional context
> _No response_
> 
> [NEXT-3273](https://linear.app/vercel/issue/NEXT-3273/react-does-not-recognize-the-fetchpriority-prop-on-a-dom-element)

I am using render() from "@testing-library/react" or "@testing-library/jest-dom" BUT facing the same issue in the following circumstances:

1. "next": "14.2.3"
2. "react": "^18"
3. "jest": "^29.7.0",

Could you please provide any workaround on this?

**Comment by styfle** [comment]
Change `"react": "^18"` to `"react": "18.2.0"`

**Comment by gino23odar** [comment]
> Change `"react": "^18"` to `"react": "18.2.0"`

neither this nor the canary fix the issue for me.
"next": "14.2.3", "react": "^18.2.0", "jest": "^29.7.0"

**Comment by arnfinn** [comment]
> > Change `"react": "^18"` to `"react": "18.2.0"`
> 
> neither this nor canary fix the issue for me. "next": "14.2.3", "react": "^18.2.0", "jest": "^29.7.0"

Try `"react": "18.2.0"` (without `^`). `"react": "^18.2.0"` will install react 18.2.0 *or higher*.

**Comment by pixelmultiplo** [comment]
Same error on react 18.3

**Comment by guillermo-avalos** [comment]
Yup, just updated to React 18.3.1 and see this error for the first `Image` component it finds.

**Comment by uphiago** [comment]
same here, fixed after `"react": "18.2.0"` and `"react-dom": "18.2.0"`

**Comment by vicasas** [comment]
This keeps happening, I don't understand why it is closed. It should be noted that this only happens to me when I run my tests. It does NOT happen when doing `npm run dev` or `npm run build/start`

I'm using:

- `next` 12.2.3
- `jest` 29.7.0
- `@testing-library/react` 15.0.7
- `@testing-library/jest-dom` 6.4.5

**Comment by pheonix5** [comment]
> mesmo aqui, corrigido depois e `"react": "18.2.0"``"react-dom": "18.2.0"`

Perfeito, aqui funcionou, WORKKKK

**Comment by NebraskaCoder** [comment]
> I hope this mock fixes the issue. Hit thumbs up if it works and thumbs down if it didnt. And let me know the error.
> 
> ```
> jest.mock('next/image', () => {
>   const MockedImage = ({ src, alt, fetchPriority, ...props }) => {
>     return (
>       <img src={src} alt={alt} data-fetch-priority={fetchPriority} {...props} />
>     );
>   };
>   MockedImage.displayName = 'MockedImage';
>   return MockedImage;
> });
> ```

Here is a better mock for Typescript support (placed in `__mocks__/next/image.tsx`), which also works for plain Javascript projects and won't break if ref is used:

```tsx
/* eslint-disable @next/next/no-img-element */

import React, { useMemo } from "react";

import type {
  StaticImageData,
  StaticRequire,
} from "next/dist/shared/lib/get-img-props";

type ImageProps = React.DetailedHTMLProps<
  React.ImgHTMLAttributes<HTMLImageElement>,
  HTMLImageElement
>;

type ModifiedImageProps = Omit<ImageProps, "src"> & {
  src?: string | (StaticRequire | StaticImageData);
};

const NextImage = React.forwardRef<any, ModifiedImageProps>((props, ref) => {
  const { src, alt, ...rest } = props;

  const imageSrc = useMemo(() => {
    if (!src) {
      return undefined;
    }

    if (typeof src === "string") {
      return src;
    }

    if ("default" in src) {
      return src.default.src;
    }

    return src.src;
  }, [src]);

  return (
    <img
      ref={ref}
      src={imageSrc}
      alt={alt}
      {...rest}
    />
  );
});

NextImage.displayName = "Image";

export default NextImage;
```

**Comment by styfle** [comment]
This is fixed in [next@14.2.4](https://github.com/vercel/next.js/releases/tag/v14.2.4)

**Comment by guillermo-avalos** [comment]
> This is fixed in [next@14.2.4](https://github.com/vercel/next.js/releases/tag/v14.2.4)

Yup. I can now confirm it’s been fixed in 14.2.4

**Comment by cobalt88** [comment]
Thank you for getting this fixed. Its one of those errors I haven't been able to get rid of for a while now lol.

**Comment by o-faro** [comment]
Just ran into this problem for the first time now. next@14.2.4 was already installed. Together with react@18.3.1and  jest@29.7.0
