### ISSUE TITLE
Docs:  Image onLoadingComplete code block does not show on 'use client'

### ISSUE THREAD

**Issue by RobiulMan** [vercel/next.js#65173]
### What is the improvement or update you wish to see?

 api-reference => components => image on the onLoadingComplete  code black does not show 'use client'  
https://nextjs.org/docs/pages/api-reference/components/image#onloadingcomplete

Below next.js doc:

![image](https://github.com/vercel/next.js/assets/49164744/c1906d62-48e4-4343-91e4-0f31d18f847e)

Next.js  GitHub repository code block has 'use client'

Below next.js github repo:

![image](https://github.com/vercel/next.js/assets/49164744/85723a42-79c0-4ab7-ac22-7a89d53cb0b9)

### Is there any context that might help us understand?

```jsx
'use client'

<Image onLoadingComplete={(img) => console.log(img.naturalWidth)} />
```

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/components/image#onloadingcomplete

**Comment by bitttttten** [comment]
Are you are looking at the "pages" doc, the "app" docs have the use client derective since only the app router supports react server components: https://nextjs.org/docs/app/api-reference/components/image#onloadingcomplete
