### ISSUE TITLE
Fail to patch lock while when a dependency is depending on a different version of Next.js

### ISSUE THREAD

**Issue by mwskwong** [vercel/next.js#65182]
### Link to the code that reproduces this issue

https://github.com/mwskwong/next-patch-lockfile-fail

### To Reproduce

Run `next dev` or `next build` and observe the terminal output.

#### Current

Dependencies are as follow:
```
├── next@14.3.0-canary.31
└─┬ react-email@2.1.2
  └── next@14.1.0
```

Next.js is trying to patch the lock file for the Next.js v14.1.0. It failed to do so, and threw the following error:

```log
 ⚠ Found lockfile missing swc dependencies, patching...
 ⨯ Failed to patch lockfile, please try uninstalling and reinstalling next in this workspace
TypeError: Cannot read properties of undefined (reading 'os')
    at fetchPkgInfo (/node_modules/next/dist/lib/patch-incorrect-lockfile.js:73:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async patchIncorrectLockfile (/node_modules/next/dist/lib/patch-incorrect-lockfile.js:162:26)
```

#### Expected
Such error should not be thrown

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.3.0-canary.31 // Latest available version is detected (14.3.0-canary.31).
  eslint-config-next: 14.3.0-canary.31
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

So far, this doesn't seem to impact the main application, including `next dev` and `next build`.

There isn't seem to have any issues on starting the React Email dev server, which is based on Next.js either.

**Comment by GabrielCev** [comment]
I have the same issue, after update i have this line in my webpack-config.js:
```
if (parseInt(_react.default.version) < 19) {
    throw new Error('Next.js requires react >= 19.0.0 to be installed.');
}
```
react 19.0.0 is not released yet and in Beta.
commenting this out will result in the same error as above

**Comment by joshwcomeau** [comment]
Running into the same issue after updating to React 19 / Next 15. When starting a dev server, I see:

```bash
  ▲ Next.js 15.0.0-rc.0
  - Local:        http://localhost:8020
  - Environments: .env.local
  - Experiments (use with caution):
    · scrollRestoration

 ✓ Starting...
 ⚠ Found lockfile missing swc dependencies, patching...
 ⨯ Failed to patch lockfile, please try uninstalling and reinstalling next in this workspace
TypeError: Cannot read properties of undefined (reading 'os')
    at fetchPkgInfo (/Users/joshu/work/blog-v3/node_modules/.pnpm/next@15.0.0-rc.0_@babel+core@7.24.6_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f_kxxc2t6qs3v2xlyoy2gzfdrn64/node_modules/next/dist/lib/patch-incorrect-lockfile.js:73:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async patchIncorrectLockfile (/Users/joshu/work/blog-v3/node_modules/.pnpm/next@15.0.0-rc.0_@babel+core@7.24.6_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f_kxxc2t6qs3v2xlyoy2gzfdrn64/node_modules/next/dist/lib/patch-incorrect-lockfile.js:162:26)
 ✓ Ready in 3s
```

Uninstalling and reinstalling Next had no effect. Fortunately, however, things still seem to work. Here's the rest of the debug info:

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 9.1.4
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 14.1.0
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

**Comment by SukkaW** [comment]
@joshwcomeau This will be fixed by #66515

**Comment by sdbeng** [comment]
Just checking the dashboard repo, while running pnpm -dev, it compiles fine but got the same locfile missing warning now with the rc.56
TypeError: Cannot read properties of undefined (reading 'os')
    at fetchPkgInfo (/Users/su/dashboard-next/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.56_react-dom@19.0.0-rc-f38c22b244-20240704_react@19.0.0-rc-f38c22b244-20240704/node_modules/next/dist/lib/patch-incorrect-lockfile.js:73:25)
    
node: v20.16.0
OS: sonoma 14.5
pnpm: v9.6.0

**Comment by ikushlianski** [comment]
Works for me now as of August 12, 2024 after updating the following dependencies:

```
    "next": "15.0.0-canary.111",
    "react": "19.0.0-rc-187dd6a7-20240806",
    "react-dom": "19.0.0-rc-187dd6a7-20240806"
```

Mind the React and React DOM versions. They need to be updated as you update `next`

**Comment by GabrielCev** [comment]
thanks @ikushlianski these versions fixed the issue for me

**Comment by rubben-ruiz** [comment]
@ikushlianski great!

**Comment by SukkaW** [comment]
@ijjk We might wanna close the issue now since it appears that my PR #66515 did resolve the issue.

**Comment by brokenhoax** [comment]
vercel might want to update their getting-started courseware as I ran in to this issue when working through the tutorial. This will scare noobs. 😆  [Next.js tutorial link here](https://nextjs.org/learn/dashboard-app/getting-started)
