### ISSUE TITLE
Support history state in Next.js router

### ISSUE THREAD

**Issue by alanhamlett** [vercel/next.js#65269]
### What is the update you wish to see?

Using app router, we can no longer push state to the next page when navigating. This is a feature depended on by many modern web apps, and IMO should be added back to the Next.js router.

https://github.com/vercel/next.js/pull/58335 tried to solve it by monkeypatching window.history.pushState, but that's error prone and the wrong solution.

Currently the only solution app devs are left with is forking next's router to allow pushing state.

### Is there any context that might help us understand?

https://github.com/vercel/next.js/pull/58335#issuecomment-1846134361

**Comment by alanhamlett** [comment]
Closing in favor of [this discussion](https://github.com/vercel/next.js/discussions/35654).

**Comment by timneutkens** [comment]
https://github.com/vercel/next.js/discussions/35654#discussioncomment-9294232
