### ISSUE TITLE
issue with `use`, string value works but object value fails to compile

### ISSUE THREAD

**Issue by rashidul0405** [vercel/next.js#65272]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/use-use-x3pns4

### To Reproduce

1. `pnpm run dev`
2. shows compiler error
3. Comment out line 14 from [`app/components/button.tsx` ](https://codesandbox.io/p/devbox/use-use-x3pns4?file=%2Fapp%2Fcomponents%2Fbutton.tsx%3A14%2C1-15%2C1)
4. it works now

### Current vs. Expected behavior

while using `use`, context value as a string works fine but context value as an object is not working.

String value working fine: `components/theme-provider.tsx`
```
<ThemeContext.Provider value="dark">
  {children}
</ThemeContext.Provider>
```
Here theme value is either dark or light, which is a string.

Object value is not working: `components/user-provider.tsx`
```
<UserContext.Provider
  value={{
    firstName: "Tom",
    lastName: "Brady",
  }}
>
  {children}
</UserContext.Provider>
```

AND reading value using `use` from context returns empty object
```
console.log("theme", theme);
console.log("user", user);
````
outputs
```
theme {}
user {}
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.3.0-canary.36 // Latest available version is detected (14.3.0-canary.36).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, Runtime, Upstream

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

none of the versions are working including canary. Not sure whether this one is a React issue or Next!!!

**Comment by poorvasingh04** [comment]
This is because you are trying to use React client hook in a server component. Did you read this? - https://nextjs.org/docs/messages/react-client-hook-in-server-component

**Comment by rashidul0405** [comment]
yeah, this was the case for a long time. I guess I read that `use` can be used both on server and client component. and also on react.dev it's documented as API instead of hooks https://react.dev/reference/react/use

**Comment by ElectricCodeGuy** [comment]
I use it together with together with suspense  in server components

Exmaple


```
export default function MainPage({ params }: { params: { category?: string[] | [] } }) {
  const session = getSession();
  const categoryArray = params.category || [];
  const category = categoryArray[0] ? decodeURIComponent(categoryArray[0]) : 'default';
  const item = categoryArray.length > 1 ? decodeURIComponent(categoryArray[1]) : '';
  const itemTitles = getItemTitles(category);

  return (
    <div>
      <Sidebar itemTitles={itemTitles} selectedTitle={item} category={category} />
      <div>
        <div>
          {!item ? (
            <Suspense fallback={<DefaultContentSkeleton />}>
              <DefaultContent />
            </Suspense>
          ) : (
            <Suspense key={item} fallback={<ItemContentSkeleton />}>
              <ItemContent category={category} item={item} />
            </Suspense>
          )}
        </div>
        <div>
          <ChatComponent />
        </div>
      </div>
    </div>
  );
}

function ItemContent({ category, item }: { category: string; item: string }) {
  const [keyName, selectedItemDetails, itemDetails] = use(
    Promise.all([
      fetchKeyName(item, category),
      fetchSelectedItemDetails(item, category),
      fetchItemDetails(item),
    ])
  );

  if (!itemDetails || itemDetails.length === 0) {
    return <NoDataFallback />;
  }

  // Restructure the data
  const restructuredItemData = itemDetails.map((item) => {
    // Perform data restructuring logic here
    // ...

    return {
      ...item,
      // Add restructured properties
    };
  });

  return (
    <ItemPageContent
      itemData={restructuredItemData}
      selectedItemDetails={selectedItemDetails}
      category={category}
      item={item}
      key={item}
    />
  );
}

function DefaultContent() {
  const [{ totalCount, categoryCount }, newItems] = use(
    Promise.all([getItemCounts(), getNewestItems()])
  );

  return (
    <DefaultPage
      totalCount={totalCount}
      categoryCount={categoryCount}
      newItems={newItems}
    />
  );
}
```

From my understanding when reading the React Docs since the "use" hook is a React Hook and have nothing to do with Next, you can use this use hook in combination with a nested component inside a suspense boundary to first load some components and to show a loading state for larger components. It works really well :)

**Comment by rashidul0405** [comment]
@ElectricCodeGuy it's recommended to use async/await for data fetching?
>When fetching data in a [Server Component](https://react.dev/reference/rsc/use-server), prefer async and await over use. async and await pick up rendering from the point where await was invoked, whereas use re-renders the component after the data is resolved.

https://react.dev/reference/react/use#caveats

**Comment by rashidul0405** [comment]
@eps1lon @delbaoliveira created the issue here from X https://x.com/sebsilbermann/status/1785979252686385321

**Comment by eps1lon** [comment]
Does it not compile or does it just silently return the wrong context value? Is it the default that it returns or always an empty object?

**Comment by eps1lon** [comment]
It should fail compilation since `use(SomeContex)` implies you import a file using `createContext` in a server component. This is not supported since React Context is a client-only feature.

You should see an error similar to "createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component"

**Comment by rashidul0405** [comment]
`use` is client-only feature.
