### ISSUE TITLE
lint TP1006

### ISSUE THREAD

**Issue by artola** [vercel/next.js#65280]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/goofy-ritchie-39dq82

### To Reproduce

1. start the app (`next dev --turbo`) or `yarn dev` (already modified for turbo).
2. the app contains 2 links for 2 routes, click to navigate:
  - /foo = the console has NO ERROR printed
```typescript
import { NextResponse, type NextRequest } from "next/server";
import path from "node:path";

export async function GET() {
  const p = path.resolve("./foo.txt");

  return new NextResponse("NO ERROR :)");
}
```
  
  - /bar = the console has ERROR printed
```typescript
import { NextResponse, type NextRequest } from "next/server";
import path from "node:path";

function getPath(target: string) {
  return path.resolve(target);
}

export async function GET() {
  const p = getPath("./foo.txt");

  return new NextResponse("ERROR :(");
}
```  

**Note**: Even if the function `getPath` is defined within the GET still the linter show errors:

```text
 ✓ Compiled /bar in 156ms
 ⚠ ./app/bar/route.ts:5:10
lint TP1006 path.resolve(???*0*) is very dynamic
  3 |
  4 | function getPath(target: string) {
> 5 |   return path.resolve(target);
    |          ^^^^^^^^^^^^^^^^^^^^
  6 | }
  7 |
  8 | export async function GET() {

- *0* arguments[0]
  ⚠️  function calls are not analysed yet


 GET /bar 200 in 205ms
 ⚠ ./app/bar/route.ts:5:10
lint TP1006 path.resolve(???*0*) is very dynamic
  3 |
  4 | function getPath(target: string) {
> 5 |   return path.resolve(target);
    |          ^^^^^^^^^^^^^^^^^^^^
  6 | }
  7 |
  8 | export async function GET() {

- *0* arguments[0]
  ⚠️  function calls are not analysed yet


 GET /bar 200 in 27ms
```

### Current vs. Expected behavior

Linter should understand these calls, otherwise I should know what to do :)

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 14.3.0-canary.36 // Latest available version is detected (14.3.0-canary.36).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
Done in 1.76s.
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Same behavior in latest as in canary 15.0.0-canary.19.

<sub>[PACK-3045](https://linear.app/vercel/issue/PACK-3045/lint-tp1006)</sub>

**Comment by Adnanear** [comment]
I can confirm, the same issue is happening to me on NextJS ^14.2.3

**Comment by jimapl** [comment]
Any idea if this will land in the 14.x version some time soon?
Hard to develop without Turbo. And am unable to run dev in Turbo now.
Using path, fs and in route handlers.

**Comment by artola** [comment]
> I cloned the repo locally and can't see an issue when visiting `/foo` or `/bar` with `next dev --turbo`. Can you try the latest `canary` with `react@beta` and `react-dom@beta` and see if the issue persists?

@lfades I did update the sandbox the canary 162 and peer react/react-dom and there is no error anymore with the linter.
Then, this issue does not persist in @canary 162 at least. Thanks!
