### ISSUE TITLE
Sass variables do not work in the Turbopack dev mode

### ISSUE THREAD

**Issue by OttoG** [vercel/next.js#65367]
### Link to the code that reproduces this issue

https://github.com/OttoG/turbopack-sass-variables-issue

### To Reproduce

1. Start the application with `next dev --turbo` (mapped to `npm run dev` in the issue reproduction `package.json`).
2. Visit http://localhost:3000/ in a web browser.
3. Note that `undefined` is displayed where `#012345` (the content of an exported Sass variable) is expected.

### Current vs. Expected behavior

If instead the application is started with `next dev` (mapped to `npm run dev-conventional` in the issue reproduction `package.json`), the expected result is displayed.

The file `variables.module.scss`, with the following content, exports a css class and a variable.

```scss
$test-color: #012345;
.variablesTest {
  color: $test-color;
}
:export {
  testColor: $test-color;
}
```

According to the documentation – https://nextjs.org/docs/app/building-your-application/styling/sass#sass-variables – Sass variables are supposed to work, and they do work in conventional dev mode, as well as with production builds – they just do not seem to work with Turbopack. Any exports declared in `:export` rules are missing from the imported object in Turbopack dev mode. (The class name works just fine in both types of dev mode.)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112
  Available memory (MB): 24576
  Available CPU cores: 8
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.3.0-canary.38 // Latest available version is detected (14.3.0-canary.38).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I had the same problem with Next 14.0.4. Also, this problem does not seem to be mentioned in the list of unsupported Turbopack features: https://nextjs.org/docs/architecture/turbopack#unsupported-features

<sub>[PACK-3040](https://linear.app/vercel/issue/PACK-3040/sass-variables-do-not-work-in-the-turbopack-dev-mode)</sub>

**Comment by timneutkens** [comment]
We leverage https://lightningcss.dev/ in Turbopack which does not support the :import and :export ICSS rules. Docs: https://lightningcss.dev/css-modules.html

We'll document this better in the docs.
