### ISSUE TITLE
pdfjs-dist fails to compile with Turbopack (webpackIgnore comment not respected)

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#65406]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/pdf-viewer-forked-h3gdsc?file=%2Fcomponents%2FTestPage.tsx

### To Reproduce

1. Open https://codesandbox.io/p/devbox/pdf-viewer-forked-h3gdsc?file=%2Fcomponents%2FTestPage.tsx
2. Observe the compilation failing with `Module not found` (example: https://h3gdsc-3000.csb.app/)

### Current vs. Expected behavior

`pdfjs-dist` ships with a webpack specific ignore comment (:til: that is a feature) as they use `import()` to load a file based on an option being passed in. 

Specifically `const worker = await import(/* webpackIgnore: true */ this.workerSrc);` fails to compile as it can't find `this.workerSrc` statically.

I'm not sure what the best behavior is for this, adding support for the comment or ignoring such imports when they don't include a path.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.6
Relevant Packages:
  next: 14.3.0-canary.40 // Latest available version is detected (14.3.0-canary.40).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

This is failing on all versions with Turbopack as it doesn't support the ignore comment. 

<sub>[PACK-3046](https://linear.app/vercel/issue/PACK-3046/pdfjs-dist-fails-to-compile-with-turbopack-webpackignore-comment-not)</sub>

**Comment by timneutkens** [comment]
This issue came out of https://github.com/vercel/next.js/issues/63385#issuecomment-2095335459

**Comment by enricoros** [comment]
Experiencing the same, so adding a screenshot of `next dev --turbo` below:

![image](https://github.com/vercel/next.js/assets/32999/e482091c-d107-4709-8301-aff263e4fd5a)

**Comment by timneutkens** [comment]
@enricoros adding screenshots of CLI output is not helpful in general. If you want to share that you're running into the same issue you can use GitHub's emoji reactions on the initial post to add a 👍

Thanks!

**Comment by husseinraoouf** [comment]
@timneutkens  this is the only thing preventing me from using turbopack with `next dev` now, shouldn't we add a test for the `webpackIgnore` to make sure turbo have 100% compatibility with current webpack setup in nextjs and to better to show in the areweturboyet.com

**Comment by dmkotan** [comment]
Used bun patch. [patch-package](https://www.npmjs.com/package/patch-package) should work too.

```diff
diff --git a/build/pdf.mjs b/build/pdf.mjs
index 0eb6cb7e84d5085db76d9388b4853302e307303b..a3bc7b54f7b79d7a418c80f27e1685a438808af0 100644
--- a/build/pdf.mjs
+++ b/build/pdf.mjs
@@ -11936,7 +11936,8 @@ class PDFWorker {
       if (this.#mainThreadWorkerMessageHandler) {
         return this.#mainThreadWorkerMessageHandler;
       }
-      const worker = await import( /*webpackIgnore: true*/this.workerSrc);
+      // https://github.com/vercel/next.js/issues/65406
+      const worker = await import( /*webpackIgnore: true*/this.workerSrc ?? "./pdf.worker.mjs");
       return worker.WorkerMessageHandler;
     };
     return shadow(this, "_setupFakeWorkerGlobal", loader());
```

**Comment by gurkerl83** [comment]
It seems Vercel has made progress in handling Workers within Turbopack. As of Next.js 15.0.0-canary.148, the previously reported error has been resolved. This error was still present in canary.146, but no longer appears in the latest canary release.

Thx!

**Comment by timneutkens** [comment]
Thanks for checking @gurkerl83 this issue has indeed been resolved, we added support for `webpackIgnore` and `turbopackIgnore` and it's available on `next@canary`, will be in Next.js 15 RC.2 soon!
