### ISSUE TITLE
Dockerfile [4/4] Step 6/14 - /app/public no such file or directory

### ISSUE THREAD

**Issue by RapTho** [vercel/next.js#65423]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: arm64
  Version: #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07)
Binaries:
  Node: 18.19.0
  npm: 9.2.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: standalone


warn  - Latest canary version not detected, detected: "14.1.4", newest: "14.3.0-canary.42".
        Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
        Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

https://github.com/vercel/next.js/tree/canary/examples/with-docker

### What browser are you using? (if relevant)

Firefox but not relevant

### How are you deploying your application? (if relevant)

Podman / Docker

### Describe the Bug

I use the `app router` and want to containerize my app. I follow the example at [https://nextjs.org/docs/app/building-your-application/deploying#docker-image](https://nextjs.org/docs/app/building-your-application/deploying#docker-image)

I modified my next.config.js to add 
```
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
    output: "standalone",
};

export default nextConfig;
```

The build fails toawrds the end of the provided Dockerfile. It seems like the build doesn't produce the folder /app/public and thus copying fails.

```bash
[4/4] STEP 6/14: COPY --from=builder /app/public ./public
Error: building at STEP "COPY --from=builder /app/public ./public": checking on sources under "/home/raphael/.local/share/containers/storage/vfs/dir/2b164ac12a727ba1be3468a918d7c70e69263b5390573ecd4fe782ca3393a771": copier: stat: "/app/public": no such file or directory
```

### Expected Behavior

The container image builds successfully

### To Reproduce

Build the container

**Comment by icyJoseph** [comment]
Do you have a `public` directory? Could you paste the tree of your app?

**Comment by RapTho** [comment]
My bad, deleted it. Thought it'd be created by the npm run build script. I'll close the issue. Thanks!
