### ISSUE TITLE
Next Build fails with start <= end assertion failed

### ISSUE THREAD

**Issue by rishabh3112** [vercel/next.js#65436]
### Link to the code that reproduces this issue

https://github.com/rishabh3112/next-bug-large-repo

### To Reproduce

1. Clone repo: https://github.com/rishabh3112/next-bug-large-repo
2. `npm install`
3. `npm run build`

### Current vs. Expected behavior

At my company, We have a fairly large monorepo and it uses next 14 with swc minification, plugins and transforms enabled. Recently our build has started to fail with following:

```
thread '<unnamed>' panicked at <HOME_DIR>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_common-0.33.9/src/input.rs:31:9:
assertion failed: start <= end
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Expected behaviour would be for build to not fail for our codebase.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.6.0: Sun Dec 17 22:57:33 PST 2023; root:xnu-8020.240.18.706.2~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.17.1
  npm: 9.6.7
  Yarn: 3.2.4
  pnpm: N/A
Relevant Packages:
  next: 14.0.4 (reproducable in latest 14.2.3 and canary)
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC, Webpack

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

We have investigated the issue and found out the cause for this.
Please check them ( hope you find them helpful ): https://github.com/rishabh3112/next-bug-large-repo?tab=readme-ov-file#investigations

I am willing to contribute / discuss issue in more detail if needed.

**Comment by icyJoseph** [comment]
Should this be taken to SWC then? https://github.com/swc-project/swc/issues the maintainer these is very effective 🎉

**Comment by rishabh3112** [comment]
@icyJoseph Thanks for suggestion, will raise this with `swc` as well. Although I think issue is from both nextjs side (i.e. `next-swc`) and from `swc` side.

**Comment by rishabh3112** [comment]
Raised the same here: https://github.com/swc-project/swc/issues/8932
