### ISSUE TITLE
Docs: Some Tags in "Layouts and Templates" page are not showing properly in the Firefox browser 

### ISSUE THREAD

**Issue by Ravichandra-C** [vercel/next.js#65498]
### What is the update you wish to see?

Tags are not showing properly in Firefox 

![image](https://github.com/vercel/next.js/assets/17808008/5b34707c-5f6a-4a89-ada5-25e92d7e5d96)

However They are showing properly in chrome

![image](https://github.com/vercel/next.js/assets/17808008/96e8a662-18a9-4621-89cc-0e04c19036bc)

### Is there any context that might help us understand?

We should show the tags properly in firefox too

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/layouts-and-templates

**Comment by enochval** [comment]
@Ravichandra-C I want to work on this issue, can you assign it to me?

**Comment by Ravichandra-C** [comment]
Looks like this is showing properly now!, Not sure how. Sorry for the inconvenience caused. Closing the issue.
