### ISSUE TITLE
Docs: Link documentation -  Remove 'With URL Object' section

### ISSUE THREAD

**Issue by mfernandez97** [vercel/next.js#65505]
### What is the update you wish to see?

I would like to see the '[With URL Object](https://nextjs.org/docs/app/api-reference/components/link#with-url-object)' section removed.

### Is there any context that might help us understand?

The app router does not support dynamic hrefs as stated [here](https://nextjs.org/docs/messages/app-dir-dynamic-href).

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/components/link#with-url-object

**Comment by samcx** [comment]
@mfernandez97 Can you clarify what part of that docs link explains that App Router does not support dynamic hrefs?

**Comment by mfernandez97** [comment]
@samcx Apologies, I entered the wrong url, have since updated it! [https://nextjs.org/docs/messages/app-dir-dynamic-href](https://nextjs.org/docs/messages/app-dir-dynamic-href) states:

> The "Dynamic href is not supported in the App Router" error happens when you try to use a dynamic href with next/link in the app directory.
The new client-side router in Next.js does not use a mapping of dynamic routes to URLs, but rather it leverages the URL directly. This means it doesn't support dynamic href use.
