### ISSUE TITLE
Parallel route RSC does not unmount when navigating back to a `default.tsx`

### ISSUE THREAD

**Issue by PupoSDC** [vercel/next.js#65510]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/strange-flower-7nz5gd?file=%2Fapp%2Fissue%2F%40table%2Fpage.tsx

### To Reproduce

1. Click the link to "open the modal"
2. Click the link to "close the modal". 
3. "Modal" remains open.

### Current vs. Expected behavior

The modal implementation follows the recommendation from the [docs](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#closing-the-modal). 

When you click the link to open modal, you navigate to `/modal/3` which causes de modal slot, to render the modal. 
When you clicl the link to close the modal, you navigate back to `/` which should cause the modal to unmount. but it does not. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.1
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

**Comment by ztanner** [comment]
Hi, did you mean to share a different CodeSandbox? The one you shared is working fine for me.

https://github.com/vercel/next.js/assets/1939140/02dae4c6-3c59-4525-b5ce-0e05060d0cbe

**Comment by PupoSDC** [comment]
I acidentaly fixed the sandbox with someone elses advice. The issue seems to be specific for `default.tsx`. 
I've reverted the changes so the sandbox is working again.

**Comment by darthmaim** [comment]
> I acidentaly fixed the sandbox with someone elses advice
How did you accidentally fix it? #50284 is full of ugly workarounds, so maybe your workaround works better than those until this is fixed...

**Comment by PupoSDC** [comment]
Replacing the `default.tsx` with a `page.tsx`. It's not a 1 to 1 replacement, as it does not achieve the same functionality. But it fixed the issue on my specific use case.

**Comment by ztanner** [comment]
Glad you got it working! It sounds like the behavior you were running into is expected behavior for `default.tsx`, described in a bit more detail here: https://nextjs.org/docs/app/api-reference/file-conventions/default

`default.js` is only used when the slot is first unmatched (ie, on page load). On soft navigations, whatever was in the slot will remain active, if it doesn't match to a `page.tsx`.
