### ISSUE TITLE
Hot reload causes tab to hang and crash

### ISSUE THREAD

**Issue by erikshestopal** [vercel/next.js#65537]
### Link to the code that reproduces this issue

https://github.com/erikshestopal/next-reload-bug

### To Reproduce

Instructions are in `app/_components/form-element.tsx` in the repo. 

### Current vs. Expected behavior

**Current behavior**
Hot reloading a component that uses `z.function` from the `zod` library causes the tab to hang with high CPU usage. 

**Expected behavior**
Tab should not hang. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 19.0.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 9.0.1
Relevant Packages:
  next: 14.3.0-canary.50 // Latest available version is detected (14.3.0-canary.50).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Performance, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by DavidShestopal** [comment]
Running into this as well. Help asap
