### ISSUE TITLE
Docs: Pages Router Authentication links broken

### ISSUE THREAD

**Issue by jeff-ramos-dev** [vercel/next.js#65530]
### What is the update you wish to see?

In the Pages Router docs, under Building Your Application > Authentication there is an Authorization section that recommends creating a Data Access Layer, using Data Transfer Objects, and using Middleware. Each of these have a link associated with them. The Middleware link is fine, but each of the other links have issues:

1. The Data Access Layer link should point to the heading on the page (https://nextjs.org/docs/pages/building-your-application/authentication#creating-a-data-access-layer-dal-1), but it instead points to a broken link (https://nextjs.org/docs/pages/building-your-application/authentication#creating-a-data-access-layer-dal). Simply updating the url would fix this issue.
2. The Data Transfer Object link should point to a section on using Data Transfer Objects, but this section only exists on the **_app router_** documentation (https://nextjs.org/docs/app/building-your-application/authentication#using-data-transfer-objects-dto), not on the **_pages router_** documentation. This section would need to be added to the pages router documentation.

### Is there any context that might help us understand?

The "Using Data Transfer Objects (DTO)" section in the app router documentation would not be able to be shared by both docs, as the code example in the app router builds off of code which doesn't match the pages router example. An example specific to the pages router would need to be written and included in the <Pages Only> content.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/authentication#authorization

**Comment by itscrisu** [comment]
Looks like this happens on App router too

Broken link: https://nextjs.org/docs/app/building-your-application/routing/pages (**app router**) 

Working link: https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts (**pages router**)

**Comment by jeff-ramos-dev** [comment]
> Looks like this happens on App router too
> 
> Broken link: https://nextjs.org/docs/app/building-your-application/routing/pages (**app router**)
> 
> Working link: https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts (**pages router**)

Where did you find that broken link? All of the app router links I see concerning pages and layouts seem to be linked correctly.

**Comment by jeff-ramos-dev** [comment]
Since my original issue was fixed, I'll close this issue. 

@itscrisu feel free to open a new issue about the links you found.
