### ISSUE TITLE
Docs: Minor syntax error in the streaming doc 

### ISSUE THREAD

**Issue by aykutkardas** [vercel/next.js#65609]
### What is the update you wish to see?

I noticed minor thing in the document.

Expected:
```js
const revenue = await fetchRevenue() // delete this line
```
<img width="1014" alt="image" src="https://github.com/vercel/next.js/assets/7966133/794d77ea-a27f-45a4-9c0f-b57177d84795">

### Is there any context that might help us understand?

no

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/streaming#streaming-a-component

**Comment by pilladipesh33** [comment]
Can you assign it to me I just started contributing to open-source it will be a good first issue

**Comment by maxhaomh** [comment]
Create an issue here: https://github.com/vercel/next-learn 
The course is independent of the NextJs docs.

Thanks

**Comment by aykutkardas** [comment]
> Create an issue here: https://github.com/vercel/next-learn The course is independent of the NextJs docs.
> 
> Thanks

Thanks. ✨  https://github.com/vercel/next-learn/issues/673
