### ISSUE TITLE
`<Link` breaking when there is padding or margin attached

### ISSUE THREAD

**Issue by nikitavoloboev** [vercel/next.js#65739]
### Link to the code that reproduces this issue

https://github.com/kuskusapp/kuskus/tree/73856f275ed41e59bb649d873e88841979a47b47

### To Reproduce

repo: https://github.com/kuskusapp/kuskus

on this commit: https://github.com/kuskusapp/kuskus/tree/73856f275ed41e59bb649d873e88841979a47b47

links here: https://github.com/kuskusapp/kuskus/blob/73856f275ed41e59bb649d873e88841979a47b47/components/Header.tsx#L29

don't work

related next.js help discord discussion: https://discord.com/channels/752553802359505017/1239882716539916288

100% bug with Next.js

if I remove `mt-8 ml-10` `<Link` starts working.

### Current vs. Expected behavior

`<Link` works even with those classNames

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031
  Available memory (MB): 131072
  Available CPU cores: 16
Binaries:
  Node: 21.7.2
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 9.1.1
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by nikitavoloboev** [comment]
https://github.com/vercel/next.js/assets/6391776/2d1f7a31-206c-450f-9b31-d118cc2b61b5

repro as video

someone on Discord suggested to try rename `link` to `smthElse`, it did not help.

**Comment by icyJoseph** [comment]
Could you try to setup a reproduction demo, perhaps at Stackblitz? just write next.new into your URL search bar.

Also, could you try to programmatically trigger `.click()` from the browser console?

**Comment by nikitavoloboev** [comment]
Ok was issue with another element messing it up with `position: fixed`. It's resolved now.
