### ISSUE TITLE
Add option to enable Turbopack with `create-next-app`

### ISSUE THREAD

**Issue by leerob** [vercel/next.js#65924]
### What is the update you wish to see?

`create-next-app` currently shows a list of options when setting up your Next.js application. 

![CleanShot 2024-05-18 at 09 14 41@2x](https://github.com/vercel/next.js/assets/9113740/14441bdb-dd07-42d9-be1f-c3e327d1fbd8)

We'd like to add an option that matches the other style for Turbopack. It should default to No until it is stable. Please use the following format for the option:

> Would you like to use Turbopack for `next dev`? (RC) … No / Yes

It's worth noting there are multiple different templates (e.g. App Router, non-App Router, Tailwind, non-Tailwind) and we'll need to make sure selecting this option works for all of them.

The specific code change needed is to change the `package.json` script for `dev` from `next dev` to `next dev --turbo`.

### Is there any context that might help us understand?

The docs page should also be updated in the PR to include the new option.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/create-next-app

**Comment by leerob** [comment]
Woohoo! Thank you three, we can combine efforts now 😄

**Comment by devjiwonchoi** [comment]
@mertcanaltin Hi, awesome work!! I'd propose combining to @Arindam200's PR as this "issue" was encouraging new contributors to Next.js!

**Comment by mertcanaltin** [comment]
Of course, we can combine it, everyone was great, thank you for your efforts :heart:

**Comment by Arindam200** [comment]
Thanks @devjiwonchoi @mertcanaltin for your Support!

**Comment by leerob** [comment]
We did it! Thank you all so much 🥳

**Comment by mirasayon** [comment]
We are the future
