### ISSUE TITLE
Is Middleware need to be cached?

### ISSUE THREAD

**Issue by LowScarlet** [vercel/next.js#65956]
### Link to the code that reproduces this issue

https://github.com/LowScarlet/portfolio-api/tree/main/frontend/website

### To Reproduce

1. create middleware.ts
2. add some code like
```tsx
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

// Main
export default async function mainMiddleware(request: NextRequest) {
  console.log("Running!")

  return NextResponse.next();
}

export const config = {
  matcher: [
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
```
3. Add two regular page like
Home1/page.tsx
```tsx
'use client'

import Link from "next/link";

export default function Home() {
  return (
    <main>
      <Link href={'/home2'}>Next Page</Link>
    </main>
  );
}
```
Home2/page.tsx
```tsx
'use client'

import Link from "next/link";

export default function Home2() {
  return (
    <main>
      <Link href={'/home'}>Pre Page</Link>
    </main>
  );
}
```

https://github.com/vercel/next.js/assets/64282946/377c9dbb-e74b-485f-88ac-c3684910cc22

https://github.com/vercel/next.js/assets/64282946/60cefd61-6a1b-4ec3-b756-860f9ddaeda9

### Current vs. Expected behavior

The middleware should still run every time the page changes

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 12072
  Available CPU cores: 4
Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Its work if we use random query, you can check the last video  (So the point is middleware has been cached)

**Comment by gustaveWPM** [comment]
Btw, it can be a pain with Auth. Using the next/prev btns can lead to still display a cached protected page after logout.

**Comment by ztanner** [comment]
Hi -- the behavior you're observing relates to the [client router cache](https://nextjs.org/docs/app/building-your-application/caching#router-cache).

If you'd like to disable the client router cache so that every request hits the server, you can disable it by modifying your `next.config.js` as follows:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    staleTimes: {
      dynamic: 0,
    },
  },
}

module.exports = nextConfig
```

You can learn more about this configuration option [here](https://nextjs.org/docs/app/api-reference/next-config-js/staleTimes).

**Comment by LowScarlet** [comment]
> Member

thats cool, i will try it

**Comment by gustaveWPM** [comment]
> Hi -- the behavior you're observing relates to the [client router cache](https://nextjs.org/docs/app/building-your-application/caching#router-cache).
> 
> If you'd like to disable the client router cache so that every request hits the server, you can disable it by modifying your `next.config.js` as follows:
> 
> ```js
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   experimental: {
>     staleTimes: {
>       dynamic: 0,
>     },
>   },
> }
> 
> module.exports = nextConfig
> ```
> 
> You can learn more about this configuration option [here](https://nextjs.org/docs/app/api-reference/next-config-js/staleTimes).

Already saw this, but it didn't resolve all my issues. :/
Also, I'm trying to invalidate the client router cache, using a router.refresh, which still doesn't seem to fix my issue.

Maybe I will open an issue for that. /shrug
