### ISSUE TITLE
middleware redirect doesn't change the url on router.refresh()  - App Router

### ISSUE THREAD

**Issue by Saman-Safaei-Dev** [vercel/next.js#65970]
### Link to the code that reproduces this issue

https://github.com/Saman-Safaei-Dev/next-bug

### To Reproduce

1- create a middleware to redirect from "/" to "/dashboard" with a condition ( for example when a cookie exists )
2- navigate to "/" and make this condition true, then call router.refresh()
3- you are in dashboard page but look at the url

### Current vs. Expected behavior

current: the url remains the "/"
expected: the url should change to "/dashboard"

### Provide environment information

```bash
Operating System:
  Platform: Windows 11
  Arch: x64
  Version: 23H2
Binaries:
  Node: 18.20.2
  npm: 10.5.0
Relevant Packages:
  next: 14.2.3
  next-intl: 3.10.0
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.3
```

### Which area(s) are affected? (Select all that apply)

Middleware, Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by gaojude** [comment]
Server correctly returns 307 for the `router.refresh()` RSC request.

![image](https://github.com/vercel/next.js/assets/32973745/bf8f413b-a614-4d0f-9193-0482bf6aeb78)

A fetch for the new location is also fired.
![image](https://github.com/vercel/next.js/assets/32973745/4eb8e7d5-e7ab-4d61-82c0-71c559a6f70c)

My guess would be that `refresh-reducer` fails to set the browser history to the new location.
