### ISSUE TITLE
Component Reinitialization Issue with `loading.tsx` and `revalidateTag` 

### ISSUE THREAD

**Issue by nikolay-gipp-sibe** [vercel/next.js#66029]
### Link to the code that reproduces this issue

https://github.com/nikolay-gipp-sibe/nextjs-loading-revalidate-issue

### To Reproduce

1. `npm install`
2. `npm run dev`
3. Open the project in your browser:
Navigate to http://localhost:3000/

4. Click on the button on the page:
You will find a button labeled "Click me".

5. In the browser console, you will see the logs from useEffect being displayed again, indicating the re-initialization of the LifecycleLogger component. The logs should show "Component mounted" again, followed by "Component unmounted" if the component was reinitialized.

### When the `loading.tsx` file is present in the project: ###

Clicking the button that calls `revalidateTag` causes the `useEffect` in `LifecycleLogger` to run again on the first click, leading to re-initialization of the component.
Subsequent clicks do not cause `useEffect` to run again, and the component behaves as expected after the first click.

![With loading tsx](https://github.com/vercel/next.js/assets/149572523/8ad6c5b9-29dc-4d2d-a546-4a60a5a706f4)

### When the `loading.tsx` file is not present: ###

The `useEffect` in `LifecycleLogger` runs only once on the initial render.
Clicking the button does not cause `useEffect` to run again, and the component behaves as expected.

![Without loading tsx](https://github.com/vercel/next.js/assets/149572523/ebcd158f-5605-4a29-8327-ffd8d23feb47)

## Expected Behavior: ##

The useEffect in LifecycleLogger should run only once on the initial render, regardless of the presence of loading.tsx.
Clicking the button that calls `revalidateTag` should not cause the `useEffect` to run again, preventing re-initialization of the `LifecycleLogger` component on the first click when loading.tsx is present.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 61293
  Available CPU cores: 16
Binaries:
  Node: 22.1.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app, Pages Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by gaojude** [comment]
Should be fixed by https://github.com/vercel/next.js/pull/66061
