### ISSUE TITLE
MSW Turbopack fails to import

### ISSUE THREAD

**Issue by joaopedrodcf** [vercel/next.js#66058]
### Link to the code that reproduces this issue

https://github.com/joaopedrodcf/nextjs-bug-msw

### To Reproduce

1. Yarn
2. Yarn dev --turbo
3. Open localhost:3000 and an error will appear

<img width="1134" alt="image" src="https://github.com/vercel/next.js/assets/11476152/fed0bd39-24a7-43cf-9450-506df4427969">

### Current vs. Expected behavior

`yarn dev` works correctly but `yarn dev --turbo` doesn't work

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.22
  pnpm: 9.1.1
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This is the least complex setup I could create to showcase that when using turbo it breaks, I also tried to install the latest canary and the problem still persisted, [14.3.0-canary.75](https://www.npmjs.com/package/next/v/14.3.0-canary.75)

I thought I remember that back in the day I could run with turbo and with msw but I tried a bunch of older versions and it didn't work.

**Comment by timneutkens** [comment]
Thanks for the clear reproduction! Did some digging and created an even more minimal reproduction + test in #66128 👍 We'll take a look into fixing this.

**Comment by joaopedrodcf** [comment]
@timneutkens thank you so much for the reply, and for creating a super simple reproduction step + test 🙏

**Comment by timneutkens** [comment]
I've added the `typeof window` inlining feature to Turbopack here: https://github.com/vercel/turbo/pull/8211 and updated the PR shared above to implement it: https://github.com/vercel/next.js/pull/66128

Checking locally it passes the tests with those changes 🙌

**Comment by timneutkens** [comment]
Triggered a new canary with the fix, will be available in 15-30mins.

**Comment by joaopedrodcf** [comment]
Worked perfectly 🙏
