### ISSUE TITLE
Next 14 is not working properly in docker on windows with bun, but normal at local terminal

### ISSUE THREAD

**Issue by devhik0** [vercel/next.js#66068]
### Link to the code that reproduces this issue

https://github.com/devhik0/crm-saas

### To Reproduce

1. Look at Docker file and try to build and run it in docker or kubernetes and see the error below.

### Current vs. Expected behavior

Expected runs properly, but giving this error 

```sh
. > kubectl logs client-app-depl-6f88ddb4b5-4z74x
$ next start
  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000

 ✓ Starting...
145 |         var _middlewareManifest_middleware_, _middlewareManifest_middleware;
146 |         const buildIdPath = _path.default.join(opts.dir, opts.config.distDir, _constants.BUILD_ID_FILE);
147 |         try {
148 |             buildId = await _promises.default.readFile(buildIdPath, "utf8");
149 |         } catch (err) {
150 |             if (err.code !== "ENOENT") throw err;


                                                                        ^
error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
      at /app/node_modules/next/dist/server/lib/router-utils/filesystem.js:150:247

error: script "start" exited with code 1
```

### Provide environment information

```bash
OS: Windows 11
Node: 20
Bun: 1
```

### Which area(s) are affected? (Select all that apply)

Runtime

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local)

### Additional context

Everything normal at local setup, it's only happens at docker. Also here the link for discussion about this: 

https://github.com/vercel/next.js/discussions/65740

**Comment by tpdewolf** [comment]
I have the same issue
Next 14.2.3

.next folder in docker only includes these files and folders
```
cache
prerender-manifest.js
package.json
routes-manifest.json
```

**Comment by devhik0** [comment]
I can't see what it includes cuz it's crashing due to that build error above.

**Comment by tpdewolf** [comment]
@devhik0 You can ssh into the image by running `docker run --rm -it myimage:latest sh`

I do notice that it does work when I build the image in Github actions on ubuntu latest. When i'm building it on Mac m1 with `--platform=linux/amd64` it doesnt create all files in `.next`

**Comment by devhik0** [comment]
@tpdewolf Haha, weird. Cuz my docker is building the image at GitHub actions for Linux x64 but when I pull it from dockerhub and put into kubernetes / run in docker, it's giving build error. :)

**Comment by devhik0** [comment]
@tpdewolf Yes, but it's not working in docker and giving that error. But same with you at GitHub actions it's passing. I thought my OS kinda preventing or breaking something about that image, cuz i can't run image in any way. Maybe dockerfile could be a problem

**Comment by Hulow** [comment]
hey,
almost the same for me:

- I use Next.js 14.2.3.
- The docker image run correctly on my local env but it gets stuck when i run the image on a ubuntu server.
- I build my image FROM node:20-slim

**Comment by devhik0** [comment]
So, update: Check your Dockerfile and other files to make sure its copying all files and have right permissions.
Here i ll share what i changed and how it fixed everything.
```Dockerfile
# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 as base
WORKDIR /app

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun install

# install with --production (exclude devDependencies)
RUN mkdir -p /temp/prod
COPY package.json bun.lockb /temp/prod/
RUN cd /temp/prod && bun install --production

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED 1

# RUN bun run test #todo: add here after adding tests
RUN bun run build

# copy production dependencies and source code into final image
FROM base AS release
WORKDIR /app

# Set correct permissions for nextjs user and don't run as root
RUN adduser crm
RUN chown crm:bun .
USER crm

COPY --from=install /temp/prod/node_modules node_modules
COPY --from=prerelease --chown=crm:bun /app/.next ./.next
COPY --from=prerelease /app/node_modules ./node_modules
COPY --from=prerelease /app/package.json ./package.json
COPY --from=prerelease /app/public ./public
CMD ["bun", "run", "build"]
# run the app
EXPOSE 3000/tcp
CMD ["bun", "start" ]
```
If needs use it as reference
