### ISSUE TITLE
Turbopack error on edge runtime(middleware): `Error [TypeError]: _react.default.createContext is not a function`

### ISSUE THREAD

**Issue by chungweileong94** [vercel/next.js#66162]
### Link to the code that reproduces this issue

https://github.com/chungweileong94/turbopack-edge-error-bug

### To Reproduce

1. Start the app
2. Open the app in the browser

### Current vs. Expected behavior

**Expected:**
- Turbopack should be able to build the code without any issue

**Current:**
- Turbopack throw `Error [TypeError]: _react.default.createContext is not a function`

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.15.7
Relevant Packages:
  next: 14.3.0-canary.80 // Latest available version is detected (14.3.0-canary.80).
  eslint-config-next: N/A
  react: 19.0.0-beta-04b058868c-20240508
  react-dom: 19.0.0-beta-04b058868c-20240508
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I'm not exactly sure which part of the codebase is causing the issue. However, I either removed the middleware, or removed everything related to `next-auth` from the middleware, and everything works fine again.

Note that the code works fine without Turbopack, and it used to work with Turbopack in the previous nextjs version.

**Comment by kyb3r** [comment]
I'm having the same issue

**Comment by fernandojbf** [comment]
In my project, the issue appears with Webpack using `next-intl`

**Comment by fernandojbf** [comment]
@timneutkens using webpack, i continue to see the same issue:

<img width="516" alt="image" src="https://github.com/vercel/next.js/assets/9076868/9ac75a9a-522c-466d-b318-9cf7156db9a2">

**Comment by OlegLustenko** [comment]
the same issue

![image](https://github.com/vercel/next.js/assets/11524061/36e2f3d1-4cd4-4631-a431-13526d6c4835)

**Comment by timneutkens** [comment]
Please open a new issue with a reproduction. It's expected that createContext is not available in middleware / route handlers, they're bundled in the same way as server components nowadays to ensure that things like `client-only` / `server-only` work correctly.

**Comment by fernandojbf** [comment]
> Please open a new issue with a reproduction. It's expected that createContext is not available in middleware / route handlers, they're bundled in the same way as server components nowadays to ensure that things like `client-only` / `server-only` work correctly.

I can observe that i was using a dependency on the middleware that was using react context. removing that dependency made it working again

**Comment by liuhuapiaoyuan** [comment]
How to solve it in the end?

**Comment by kyb3r** [comment]
my issue is with authjs v5 as well, any workaround?

**Comment by chungweileong94** [comment]
@liuhuapiaoyuan @kyb3r The latest canary version should resolved this.

**Comment by timneutkens** [comment]
As said above: please open a new issue with a reproduction.

Then we can have a look 🙂
