### ISSUE TITLE
Docs: Issue Next 14 generate a localized sitemap

### ISSUE THREAD

**Issue by wh0sumit** [vercel/next.js#66167]
### What is the update you wish to see?

I am experiencing an issue with the sitemap generation using the alternates key for localized URLs. 

here is the link : https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

### Is there any context that might help us understand?

The generated XML does not reflect the expected format when alternates are included. 

However, when I remove the alternates key, the sitemap is generated correctly.

### To Reproduce

- Use Next.js version ^14.2.3.
- Implement the sitemap generation with alternates as shown in the documentation.

### Here is the code used:

```jsx

import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: 'https://acme.com',
      lastModified: new Date(),
      alternates: {
        languages: {
          es: 'https://acme.com/es',
          de: 'https://acme.com/de',
        },
      },
    },
    {
      url: 'https://acme.com/about',
      lastModified: new Date(),
      alternates: {
        languages: {
          es: 'https://acme.com/es/about',
          de: 'https://acme.com/de/about',
        },
      },
    },
    {
      url: 'https://acme.com/blog',
      lastModified: new Date(),
      alternates: {
        languages: {
          es: 'https://acme.com/es/blog',
          de: 'https://acme.com/de/blog',
        },
      },
    },
  ];
}


```

### Expected behavior
The generated XML sitemap should correctly reflect the alternate language URLs.

### Actual behavior
The XML sitemap does not format the alternate language URLs as expected. Instead, it shows an incorrect structure.

### Screenshots

With alternates (incorrect format):

![image](https://github.com/vercel/next.js/assets/76095902/3f1cd574-6974-41b5-a870-22d63f467a64)

Without alternates (correct format):

![image](https://github.com/vercel/next.js/assets/76095902/1bb76b58-29bf-48fa-8b3a-173c29d45cac)

System information

OS: Windows
Browser: Chrome
Version of Next.js: 14.2.3
Version of Node.js: 21.7.1

Additional context :

I am unsure whether this is a bug in the implementation or a documentation issue. Please advise if there is an alternative way to achieve the correct sitemap structure with alternates or if this feature can be improved.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap

**Comment by Kirill-Ponomarenko** [comment]
Yeah, I have this to. Even copying exact example from docs gives this issue

I managed to track down it to the
https://github.com/vercel/next.js/blob/canary/packages/next/src/build/webpack/loaders/metadata/resolve-route-data.ts#L68

```
 content += `<xhtml:link rel="alternate" hreflang="${language}" href="${
          languages[language as keyof typeof languages]
        }" />\n`
```

If I remove `:link` part, website starts to serve xml file as is. But I guess it's invalid sitemap. And I don't understand what exactly brakes it. I followed data up to here
https://github.com/vercel/next.js/blob/canary/packages/next/src/build/webpack/loaders/next-metadata-route-loader.ts#L240
And it's fine. Have no idea what brakes it later

**Comment by GrahamQuan** [comment]
same error here with next@14.1.4
1. output `sitemap.xml` not correct
2. typescript type error

```ts
type MetadataRoute.Sitemap = {
    url: string;
    lastModified?: string | Date | undefined;
    changeFrequency?: "weekly" | "always" | "hourly" | "daily" | "monthly" | "yearly" | "never" | undefined;
    priority?: number | undefined;
}[]
```
there is no type for `alternates`

ps: their demo is also not working.

**Comment by gabriel-logan** [comment]
I'm having same issue,

https://github.com/vercel/next.js/issues/66363

**Comment by gabriel-logan** [comment]
VI aqui que se voce acessar view-source:http://localhost:3000/sitemap.xml o site map na verdade esta sendo gerado corretamente, se tu olhahr tambem o network response, aparentemente esta sendo gerado corretamente, mas não tenho certeza.

Network 
![image](https://github.com/vercel/next.js/assets/96627244/5d315afe-df2d-4196-9780-9773cbe27b42)

View Source
![image](https://github.com/vercel/next.js/assets/96627244/d0d26acd-be72-4b77-a4ad-8920f4736f60)

**Comment by huozhi** [comment]
It needs to follow the spec of google international sitemap docs: https://developers.google.com/search/docs/specialty/international/localized-versions

The XML is valid for crawler to read and the content type is expected. It's only the view source panel is not correctly displaying that content properly. If you have other problems about crawler indexing the sitemap with errors, please let us know.
