### ISSUE TITLE
Server action redirect does not show content as it streams in if layout uses suspense

### ISSUE THREAD

**Issue by efouts** [vercel/next.js#66199]
### Link to the code that reproduces this issue

https://github.com/efouts/bug-with-server-action-redirect-with-layout-using-suspense

### To Reproduce

1. pnpm dev
2. Wait for all suspended content to load (~5s)
3. Click "Server action with redirect"
4. Observe no suspense fallbacks and no update until the new request stream is completed. (~5s)

### Current vs. Expected behavior

Current behavior - Suspense within layout is not respected when redirecting from a server action. The page waits until the full render is complete, similar to if the suspense boundary was not there.

Expected behavior - Navigate immediately upon receiving the 303 and show the suspense fallback on the new page with no change to layout content.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: N/A
  pnpm: 8.15.8
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

### Additional context

- Verified the behavior exists on 14 canary
- Minimal reproduction deployed @ https://bug-next-redirect-within-layout-with-suspense.vercel.app/
- If you click the server action button prior to the suspended content in the layout being loaded, it behaves as expected.
- The issue does not occur if you remove the data fetching component and suspense from the layout.
- If you change the layout to a template, it works as expected. Using a template, the page fallback and template fallback are shown immediately.

**Comment by ztanner** [comment]
Hi - thank you for the report.

I believe this is expected behavior. `Suspense` that already triggered a fallback won't be re-triggered in this case, as described in the Suspense [docs](https://react.dev/reference/react/Suspense):

> If Suspense was displaying content for the tree, but then it suspended again, the fallback will be shown again unless the update causing it was caused by [startTransition](https://react.dev/reference/react/startTransition) or [useDeferredValue](https://react.dev/reference/react/useDeferredValue).

React automatically wraps form actions in a `startTransition`. To implement loading behavior for a server action, you can leverage an API like `useTransition`, as described [here](https://react.dev/reference/react/useTransition#displaying-a-pending-visual-state-during-the-transition).
