### ISSUE TITLE
Docs: Broken link in Docs Contribution Guide

### ISSUE THREAD

**Issue by alpedia0** [vercel/next.js#66194]
### What is the update you wish to see?

I would like to fix the broken link.

### Is there any context that might help us understand?

The link "Grammarly: Grammar and spell checker" is broken as it leads to a 404 page.
The link can be found in the [contribution guide](https://nextjs.org/docs/community/contribution-guide) underneath [extensions](https://nextjs.org/docs/community/contribution-guide#extensions)

![image](https://github.com/vercel/next.js/assets/107801475/bb7e2ed7-1f1e-4763-9b27-a437d9d3e7a1)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/community/contribution-guide#extensions

**Comment by samcx** [comment]
@alpedia0 It looks like extension has been removed and archived. Going to remove it from our <picture data-single-emoji=":docs:" title=":docs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/docs/172e1b9b7d137b8a.png" alt=":docs:" align="absmiddle"></picture> !
