### ISSUE TITLE
app/sitemap.ts is not served at /sitemap.xml on NextJS 15RC

### ISSUE THREAD

**Issue by yekta** [vercel/next.js#66232]
### Link to the code that reproduces this issue

https://github.com/amannn/nextjs-bugrepro-sitemap

### To Reproduce

1. Run the app
2. Visit `/sitemap.xml`

### Current vs. Expected behavior

For `app/sitemap.ts` to be served at `/sitemap.xml` instead of being served at `/sitemap`. I suspect this started happening after this pull request was merged: https://github.com/vercel/next.js/pull/65507

Someone else has experienced the same problem and raised it in that pull request.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031
  Available memory (MB): 65536
  Available CPU cores: 16
Binaries:
  Node: 20.5.1
  npm: 9.8.0
  Yarn: N/A
  pnpm: 9.1.0
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: N/A
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

This is seems to be working with NextJS 14.2.3. The problem is happening on NextJS 15.0.0 RC 0.

**Comment by huozhi** [comment]
It's an expected breaking change as the PR description mentioned, that we don't appending `.xml` extension for the dynamic `sitemap.ts` routes anymore.
If you're using `sitemap.xml` static file convention, it stills works as `/sitemap.xml`, but if you're using any dynamic routes with `.ts` or `.js` extension, the url is now `/sitemap` , and will be `/sitemap/[id]` if you're generating multi sitemaps with `generateSitemaps()` API.

We mentioned in the blog post but didn't mention it as breaking change, I've updated the [blog post](https://nextjs.org/blog/next-15-rc) that it's mentioned as below now
> [Breaking] Remove .xml extension for dynamic sitemap routes and align sitemap URLs between development and production (PR)

**Comment by yekta** [comment]
> It's an expected breaking change as the PR description mentioned, that we don't appending `.xml` extension for the dynamic `sitemap.ts` routes anymore. If you're using `sitemap.xml` static file convention, it stills works as `/sitemap.xml`, but if you're using any dynamic routes with `.ts` or `.js` extension, the url is now `/sitemap` , and will be `/sitemap/[id]` if you're generating multi sitemaps with `generateSitemaps()` API.
> 
> We mentioned in the blog post but didn't mention it as breaking change, I've updated the [blog post](https://nextjs.org/blog/next-15-rc) that it's mentioned as below now
> 
> > [Breaking] Remove .xml extension for dynamic sitemap routes and align sitemap URLs between development and production (PR)

Thanks for the explanation. So there is no way NextJS recommended way to serve the dynamic sitemap at `/sitemap.xml`, do I get this right?

**Comment by kiyasov** [comment]
As a solution you can add rewrites to next.config.js

```
async rewrites() {
    return [
      {
        source: "/sitemap.xml",
        destination: "/sitemap",
      },
    ];
}
```

**Comment by huozhi** [comment]
I had a PR (#66477) to improve the sitemap url generation, where we can always get a `.xml` for both single route and dynamic routes. This will resolve the migration pain
