### ISSUE TITLE
Docs: .optimizePackageImports is showing compression docs

### ISSUE THREAD

**Issue by PepijnSenders** [vercel/next.js#66266]
### What is the update you wish to see?

OptimizePackageImport Docs :)

### Is there any context that might help us understand?

Check it [here](https://nextjs.org/docs/pages/api-reference/next-config-js/optimizePackageImports)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/next-config-js/optimizePackageImports

**Comment by prkagrawal** [comment]
This is strange, everything seems to be in place. For now here are the [original docs](https://github.com/vercel/next.js/blob/97c92a24f2f831788ad7e73a0eac4f05dc30caf9/docs/02-app/02-api-reference/05-next-config-js/optimizePackageImports.mdx)

**Comment by Juneezee** [comment]
It's already fixed in https://github.com/vercel/next.js/pull/64439. It's just that the documention site hasn't been updated.
