### ISSUE TITLE
when server proxy sse request, browser would receive data until the response end

### ISSUE THREAD

**Issue by xiefenga** [vercel/next.js#66263]
### Link to the code that reproduces this issue

https://github.com/xiefenga/nextjs-sse-proxy-reproduce

### To Reproduce

1. run `pnpm run dev` start nextjs project
2. run `pnpm run sse` start sse server
3. open page and click request button
4. you will find the response is blocking

<img width="1287" alt="image" src="https://github.com/vercel/next.js/assets/50828665/7cc476a8-9ff4-43ff-98c8-35e0195ac49f">

### Current vs. Expected behavior

The browser receives the service's response data in real time

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.11.0
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Performance

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed), Other (Deployed)

**Comment by prkagrawal** [comment]
Change `Cache-Control` to `'Cache-Control': 'no-cache, no-transform',` and it should work.

**Comment by xiefenga** [comment]
it works, thanks

> Change `Cache-Control` to `'Cache-Control': 'no-cache, no-transform',` and it should work.
