### ISSUE TITLE
Turbopack dev server and HMR consuming too much memory and freezing at code changes.

### ISSUE THREAD

**Issue by devhik0** [vercel/next.js#66326]
### Link to the code that reproduces this issue

https://github.com/devhik0/crm-saas

### To Reproduce

1. Run `next dev --turbo` and check Memory values at task manager, htop etc. 
Also check VS Code's process explorer via `F1 > Open Process Explorer` 
and look for `"<path>\nodejs\node.exe" <path-to-app>\node_modules\next\dist\server\lib\start-server.js`

### Current vs. Expected behavior

That process above is consuming around 1GB memory at idle state (just running and no code change), thus code change reflections taking around > 30s to appear on UI. Here is the latest hmr result: 
```
○ Compiling /tasks ...
✓ Compiled in 39.9s (sometimes around 60)
✓ Compiled /tasks in 18.2s
```

Expected: faster rebuilds to see what happens at UI in short time and less memory consumption

I think there is a memory leak at somewhere in process. 

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 16280
  Available CPU cores: 4
Binaries:
  Node: 20.10.0
  bun: 1
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Module Resolution, Performance, Runtime, Turbopack, TypeScript

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Here i am sharing process info from my system to show what is happening actually:

![memory](https://github.com/vercel/next.js/assets/151969082/e0db2a3f-896c-491e-ac97-c48a94ab35c2)

The process with red is : `<path>\nodejs\node.exe" <path-to-app>\node_modules\next\dist\server\lib\start-server.js`

Also this is from process explorer at vscode:

![process](https://github.com/vercel/next.js/assets/151969082/51de9322-0109-42dd-aad4-5b53df172dc6)

**Comment by devhik0** [comment]
Anything ?

**Comment by timneutkens** [comment]
Can you try next@canary first, currently it's on the latest stable version but Turbopack is in active development: https://github.com/devhik0/crm-saas/blob/master/client-app/package.json#L35

**Comment by louisgv** [comment]
Seeing a similar issue running on Mac. It's smoking ~5GB of CPU:

<img width="948" alt="Screenshot 2024-06-18 at 2 08 15 PM" src="https://github.com/vercel/next.js/assets/6723574/5dd757f7-2c9d-47ff-8c02-1455ae92cbce">

Updated from 14.1.4 -> 14.2.4

**Comment by devhik0** [comment]
Well I tried even next 15@rc and without turbo, still my dev server takes around 1gb memory and takes near minutes to compile.

That's why I tried turbopack but saw that still same or even slower i could say. Without turbo it's compiling in 30s and showing hmr changes at page, but with turbo it's not triggering that compile and taking much more time to reload. That s the problem 

I m okay for high memory usage but I am expecting a finished process instead freeze or hang

**Comment by devhik0** [comment]
Well I tried even next 15@rc and without turbo, still my dev server takes around 1gb memory and takes near minutes to compile.

**Comment by devhik0** [comment]
You know that problematic repo, i will provide .env file to run it properly. Probably your machine are better than mine so I am also thinking my system specs are low to run my project

**Comment by timneutkens** [comment]
Can you try to run the steps to grab a trace as well so that we have numbers for your machine? Thanks!

**Comment by devhik0** [comment]
Here is files [link](https://file.io/tY7TsEM1QOvW)

**Comment by devhik0** [comment]
Anything?

**Comment by timneutkens** [comment]
Hey @devhik0 sorry I couldn't get around to looking into this yet, could you create a new share link as the old one expired. Thanks!

**Comment by devhik0** [comment]
Hey @timneutkens here is files, please download before expire :) [files](https://file.io/KLfaNex9Gfqu)

**Comment by timneutkens** [comment]
@devhik0 seems you're not using Turbopack 🤔 The trace indicates it's using webpack, is that expected?

**Comment by devhik0** [comment]
Yes it's webpack, turbopack gives similar results like freezing. We can go with webpack @timneutkens

**Comment by timneutkens** [comment]
The Turbopack trace has much more context on memory usage, so I'd like to receive that if possible, especially in the case where you're saying it freezes 👍

**Comment by devhik0** [comment]
@timneutkens Actually i only want a solution for current situation cuz i won't use turbopack for a long while.

**Comment by timneutkens** [comment]
Regardless please share the trace file as that allows me to investigate further.

**Comment by devhik0** [comment]
I shared files already you can find inside of it @timneutkens

**Comment by timneutkens** [comment]
It's not the Turbopack trace, which is what I requested above. You only shared a webpack trace which we can't use to investigate memory usage.

Overall 1GB memory usage with the amount of code and modules you're compiling with webpack does not seem off / high.

**Comment by timneutkens** [comment]
Okay I guess I'll close the issue then 👍 In the initial issue you said you were using `--turbo` btw 😄
