### ISSUE TITLE
Docs: inaccuracy in React Foundations (Chapter 4)

### ISSUE THREAD

**Issue by garysassano** [vercel/next.js#66362]
### What is the update you wish to see?

The docs claim that you will get an error at this point:

![image](https://github.com/vercel/next.js/assets/10464497/1379d470-f5a0-4d41-ad77-1e9916fd1d50)

In reality, the code will actually work out of the box.

### Is there any context that might help us understand?

I found it weird at first, but then I noticed that Chrome runs Babel for you in the background.

![image](https://github.com/vercel/next.js/assets/10464497/7b1ed5d8-b270-4b10-a1fd-0b3deff3be33)

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/react-foundations/getting-started-with-react

**Comment by prkagrawal** [comment]
There is a typo in docs, this `<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>` script was supposed to be added in the step after this one, without it the browsers will not display anything (chrome included), although I also didn't see any error.

**Comment by garysassano** [comment]
I never added that line in my code and it still worked.

**Comment by delbaoliveira** [comment]
Yes, the code snippet is not right, I'll update it. Thank you @prkagrawal. 

@garysassano I'm still getting the error with no babel script and no `type="text/jsx"`. Wonder what's different about your browser 🤔 

![CleanShot 2024-06-05 at 16 36 00@2x](https://github.com/vercel/next.js/assets/32464864/c0176fbc-5bae-4d59-becf-a1532e429fbe)
