### ISSUE TITLE
Cannot use Sharp in v15.0.0-canary.1

### ISSUE THREAD

**Issue by jpwallace22** [vercel/next.js#66364]
### Link to the code that reproduces this issue

https://github.com/jpwallace22/personal-site/pull/171

### To Reproduce

1. Add sharp `yarn add sharp`
2. Build on Vercel

### Current vs. Expected behavior

Current: 
```
Error: Could not load the "sharp" module using the linux-x64 runtime
```
Expect:
No errors, build as normal. (as it does on local and before upgrading to canary)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 20.7.0
  npm: 9.8.1
  Yarn: 4.2.2
  pnpm: 8.15.0
Relevant Packages:
  next: 15.0.0-canary.1 // Latest available version is detected (15.0.0-canary.1).
  eslint-config-next: 14.1.0
  react: 19.0.0-rc-6f23540c7d-20240528
  react-dom: 19.0.0-rc-6f23540c7d-20240528
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Module Resolution

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

I tried against the latest `canary` version with `yarn v4`. I also tried downgrading `sharp` to `32.6`

**Comment by oliviupis** [comment]
Watching! I'm having the same problem.......

**Comment by inderjotx** [comment]
I had the same issue and i am doing using Next15 as well with react compiler . @jpwallace22  Did you find any solution ?

**Comment by jpwallace22** [comment]
> I had the same issue and i am using Next15 as well with react compiler . @jpwallace22 Did you find any solution ?

Still no solution. Though I think I might be able to avoid it by serving the images from the `public` dir for now. The vast majority of my images are served from a cdn, so there are only a couple that are actually bundled. I'll try it out and report back.

**Comment by jpwallace22** [comment]
I was able to solve by: 
1. ensuring that I was using a modern package manager (not yarn v1) 
2. adding the  `ENABLE_EXPERIMENTAL_COREPACK=1` env variable to my build

https://vercel.com/docs/deployments/configure-a-build#corepack
cc @oliviupis @inderjotx

**Comment by oliviupis** [comment]
@jpwallace22 I fixed it also doing this steps:

1. switch from yarn to pnpm
2. remove sharp from package.json
3. in vercel settings add custom commands for build, dev, package install pointing to pnpm
4. update node version to 20.x

I think there is an issue with yarn. Don't add extra configs because that can complicate things in the future 

CC @inderjotx

**Comment by jpwallace22** [comment]
@oliviupis To each their own. The tooling I am using doesn't work as well with `pnpm` as `yarn` (and my whole org is yarn based) so changing package managers would be more of a hassle in this situation for me. 
Not to mention, I'm already running `corepack` in my local and CI so keeping it the same makes sense. 

I am a little curious about removing `sharp` from your `package.json` though. How do you consume it now?

**Comment by oliviupis** [comment]
@jpwallace22 Sharp from what I understood is by default in next and you should add it manually only if you have the error that complains about it.

**Comment by jpwallace22** [comment]
@oliviupis Yeah, I think it uses it by default for image optimizations. However, we use `sharp` in the app. Not just with the framework. And as I mentioned, I am already invested in `corepack`, so I would prefer to keep enabled e2e. 

note: 
Corepack is marked experimental so they can iterate on its CLI faster, but it's already the preferred way to install package managers - both for `yarn` and for `pnpm`.

**Comment by oliviupis** [comment]
@jpwallace22 Thank you for the tip! <3
