### ISSUE TITLE
Use of deprecated dependency that leaks memory in `eslint-config-next` (inflight 1.0.6)

### ISSUE THREAD

**Issue by RicardoGEsteves** [vercel/next.js#66413]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/isseu-eslint-config-next-ktgz2l?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwulxgl70007356ngp6nx4kl%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwulxgl70002356nrnjhimww%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwulxgl70004356nhjt4if2y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwulxgl70006356n5h1aikjz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwulxgl70002356nrnjhimww%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwulxgl60001356n229dtv8i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clwulxgl70002356nrnjhimww%2522%252C%2522activeTabId%2522%253A%2522clwulxgl60001356n229dtv8i%2522%257D%252C%2522clwulxgl70006356n5h1aikjz%2522%253A%257B%2522id%2522%253A%2522clwulxgl70006356n5h1aikjz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwulxgl70005356n8i3tm1f4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwulxgl70005356n8i3tm1f4%2522%257D%252C%2522clwulxgl70004356nhjt4if2y%2522%253A%257B%2522id%2522%253A%2522clwulxgl70004356nhjt4if2y%2522%252C%2522activeTabId%2522%253A%2522clwum3o1h00d7356npsbf5yjo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwulxgl70003356n7bkv7az0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520i%2520next%2520eslint-config-next%2522%252C%2522id%2522%253A%2522clwulzout0084356n8e4tt97w%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clwum3o1h00d7356npsbf5yjo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwum3nq2001fdifm8py46e70%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### To Reproduce

Just check dependencies

### Current vs. Expected behavior

.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Linting

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Inflight is deprecated and have a vulnerability known, It leaks memory and it's not supported anymore.
Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

**Comment by alamenai** [comment]
Same issue here :

![image](https://github.com/vercel/next.js/assets/20143684/f2e3d269-bc0f-462f-8c87-e2ef3f69e6b3)

**Comment by KhoiUna** [comment]
Same issue.

**Comment by GustavoOS** [comment]
eslint 8.57.0 was marked deprecated, and we can't upgrade it as eslint-config-next does not support newer eslint versions

**Comment by ztanner** [comment]
Thanks for the report -- I took a look via `npx create-next-app@canary` and confirmed that `inflight` was a transitive dependency as part of `eslint@8`. As of canary, we no longer install eslint v8 by default, and by extension this package is no longer installed.
