### ISSUE TITLE
Docs: Wrong link for UseFormState.

### ISSUE THREAD

**Issue by Iwan-LMX** [vercel/next.js#66450]
### What is the update you wish to see?

When click `useFormSate` will jump to `useActionState` in React.

[Here are the link](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-validation-and-error-handling)

### Is there any context that might help us understand?

![image](https://github.com/vercel/next.js/assets/61894298/de851a1d-6f2f-482e-a668-203d6296d638)
![image](https://github.com/vercel/next.js/assets/61894298/2021edd1-5dd4-4b0d-9c03-ae148bc08187)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-validation-and-error-handling

**Comment by Iwan-LMX** [comment]
`useFormSate` is the old function used by react, please update it in next.js document.
[It is `useActionState` for now!](https://react.dev/blog/2024/04/25/react-19#new-hook-useactionstate)

**Comment by delbaoliveira** [comment]
Hey @Iwan-LMX, ah I see, looks like react.dev has a redirect from `useFormState` to `useActionState`

But your point is valid, we've updated the name in the [Next.js 15 RC docs](https://rc.nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#:~:text=Once%20the%20fields,useActionState), these changes will be merged into the main docs once version 15 is stable.
