### ISSUE TITLE
Monorepo self-referencing package imports don't resolve in certain cases with Turbopack

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#66487]
### Link to the code that reproduces this issue

https://github.com/vercel/next.js/pull/66486

### To Reproduce

⚠️ I've already opened a failing test here: https://github.com/vercel/next.js/pull/66486

For the original reproduction these are the steps:
1. Clone repository: https://github.com/juliusmarminge/turbo-self-referencing
2. Run commands:
```
pnpm install
cd internal-pkg
pnpm build
cd ../next-app
pnpm dev
```
3. Open http://localhost:3000
4. Observe the error

### Current vs. Expected behavior

Expected: No build error
Current:
![CleanShot 2024-06-03 at 11 23 51@2x](https://github.com/vercel/next.js/assets/6324199/20458352-d2b6-4f62-86a0-e2863af5c364)

```
./internal-pkg/dist/index.js:1:1
Module not found: Can't resolve '@repo/internal-pkg/env'
> 1 | import { env } from '@repo/internal-pkg/env';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 |
  3 | console.log({
  4 |     env

https://nextjs.org/docs/messages/module-not-found
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: <redacted>
  Available memory (MB): 49152
  Available CPU cores: 16
Binaries:
  Node: 18.20.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: 8.15.7
Relevant Packages:
  next: 15.0.0-canary.7 // Latest available version is detected (15.0.0-canary.7).
  eslint-config-next: 15.0.0-canary.7
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by vhpx** [comment]
I still get this problem on the latest next.js 15 canary (canary.156), how can I resolve this issue?

**Comment by mischnic** [comment]
@vhpx Please open a new issue with a reproduction.

This specific case was fixed by https://github.com/vercel/turborepo/pull/8820 / https://github.com/vercel/next.js/pull/68070
