### ISSUE TITLE
Client side navigation not working properly in latest next@rc for dev

### ISSUE THREAD

**Issue by mastoj** [vercel/next.js#66508]
### Link to the code that reproduces this issue

https://github.com/mastoj/nextndc/tree/d62710243254e47a1a7a339756b6ac5bddd13fe0

### To Reproduce

1. Clone repo
2. Run pnpm install
3. Run pnpm run dev
4. Goto /slides/1
5. Click arrows to advance between the slides

### Current vs. Expected behavior

After upgrading to the latest RC release my slides are not loading. When running on a previous version on next@14 everything worked fine both in dev mode and production mode. You can also see the app running here: https://nextndc.vercel.app/slides/1, so it works fine when built but dev mode doesn't work.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
  Available memory (MB): 65536
  Available CPU cores: 12
Binaries:
  Node: 18.17.0
  npm: 9.6.7
  Yarn: 1.22.21
  pnpm: 9.1.0
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 14.2.3
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Using the following version that does't work

    "next": "15.0.0-rc.0",
    "react": "19.0.0-rc.0",
    "react-dom": "19.0.0-rc.0",

Previous version 14 and react 18 worked fine.

**Comment by ztanner** [comment]
Hi, this appears to be a bug with framer-motion's compatibility with React 19: https://github.com/framer/motion/issues/2668

Setting `NextConfig.reactStrictMode: false` seems to work as a stopgap, but I'd recommend keeping an eye on framer for an actual solution to the problem.

**Comment by steve-marmalade** [comment]
@mastoj - FYI that `framer-motion@12.0.0-alpha.0` has been released which adds support React 19: https://github.com/framer/motion/pull/2667
