### ISSUE TITLE
Intercepted route not generating metadata

### ISSUE THREAD

**Issue by tonyjara** [vercel/next.js#66510]
### Link to the code that reproduces this issue

https://github.com/tonyjara/nextgram-repro

### To Reproduce

Start the app, click any image. The metadata doesn't change.
[live demo](https://nextgram-repro.vercel.app)

### Current vs. Expected behavior

Current: click an image and the metadata stays the same
expected: click the image, the modal opens and the metadata title changes

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.9.2
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata, Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

Last stable version that I got it to work is 14.1.4, after that they all present the same issue.

**Comment by samcx** [comment]
@tonyjara Closing this in favor of https://github.com/vercel/next.js/issues/72938
