### ISSUE TITLE
Anchor download does not start a download

### ISSUE THREAD

**Issue by GustavoOS** [vercel/next.js#66567]
### Link to the code that reproduces this issue

https://github.com/GustavoOS/next-bug

### To Reproduce

1. Run the application in dev mode (pnpm run dev will do)
2. Access the root page
3. Click the download anchor

### Current vs. Expected behavior

Currently the file is opened in the browser, in the same tab as the site was being displayed

Expected to start a download, giving the name "file.jpg" to the downloaded copy.

### Provide environment information

```bash
Operating System:
Windows 11
Node 20.13.1
NextJS 14.2.3 app router
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

### Additional context

I tried other alternatives, which includes the ones described by https://www.geeksforgeeks.org/how-to-download-pdf-file-in-reactjs/ , with client component and dynamic imports. Neither have worked to make anchor to start a download, as the usual HTML5 options.

**Comment by seung-juv** [comment]
Not a bug in nextjs, but the origin is not the same, so it is not downloading.
https://stackoverflow.com/a/52089582
