### ISSUE TITLE
Redirection (redirect function) does not work in a server action with trycatch

### ISSUE THREAD

**Issue by sawa-ko** [vercel/next.js#66669]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/serene-napier-go8s7s?file=%2Fapp%2Fpage.tsx%3A5%2C1

### To Reproduce

1. Create a server action like this

```ts
'use server';

import { redirect } from 'next/navigation';

export default async function TestAction(formData: FormData) {
    const withTry = formData.get('try-catch');

    if (withTry === 'on') {
        try {
            console.log('Redirect with trycatch')
            redirect('/test');
        } catch (error) {}
    } else {
        console.log('Redirect without trycatch')
        redirect('/test');
    }

    return '';
}
```

2. Use the server action in the form
```tsx
import TestAction from './action';

/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  return (
    <form action={TestAction}>
      <label htmlFor="try-catch">With try-catch</label>
      <input type="checkbox" name="try-catch" id="try-catch" />
      <button type="submit">Update User Name</button>
    </form>
  );
}
```

3. You can see that if you try to use the redirect function with trycatch it does nothing, but without it it works.

### Current vs. Expected behavior

Currently if you try to use the nextjs redirect function in a trycatch it doesn't work, it doesn't do anything and there is no error message.

But if you use it outside of a trycatch it works fine, and also without any error message, it's something weird.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 16164
  Available CPU cores: 16
Binaries:
  Node: 22.2.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by icyJoseph** [comment]
This is as per documentation. The redirect function throws, and you are "swallowing" the thrown error within your catch block.


![Image](https://github.com/vercel/next.js/assets/21013447/c7215a2d-e146-4106-a5d0-0ad0934b89ce)

**Comment by sawa-ko** [comment]
I see, thanks.
