### ISSUE TITLE
Cannot set Content-Type header for api route response (pages router)

### ISSUE THREAD

**Issue by AshConnolly** [vercel/next.js#66801]
### Link to the code that reproduces this issue

https://github.com/AshConnolly/nextjs-headers-test

This repo was made with `npx create-next-app@latest`, pages router, and I only added [this single line](https://github.com/AshConnolly/nextjs-headers-test/blob/main/pages/api/hello.ts#L12) in the api route.

### To Reproduce

View [this codesandbox](https://codesandbox.io/p/github/AshConnolly/nextjs-headers-test/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxbx226f00063b6mwldu0kkc%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxbx226f00023b6mttdljpr9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxbx226f00043b6mf2y5im4i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxbx226f00053b6mj5t4s0l2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxbx226f00023b6mttdljpr9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbx226f00013b6mozj03yeg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxbx226f00023b6mttdljpr9%2522%252C%2522activeTabId%2522%253A%2522clxbx226f00013b6mozj03yeg%2522%257D%252C%2522clxbx226f00053b6mj5t4s0l2%2522%253A%257B%2522id%2522%253A%2522clxbx226f00053b6mj5t4s0l2%2522%252C%2522activeTabId%2522%253A%2522clxbx3u6500dc3b6m8bulubp0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clxbx3u6500dc3b6m8bulubp0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxbx226f00043b6mf2y5im4i%2522%253A%257B%2522id%2522%253A%2522clxbx226f00043b6mf2y5im4i%2522%252C%2522activeTabId%2522%253A%2522clxbx2pxj005r3b6mfg7ggbc4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxbx226f00033b6mbr0p17yk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxbx22j6000tdahl3kv02dv9%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxbx2pxj005r3b6mfg7ggbc4%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). Or run this next.js project locally - https://github.com/AshConnolly/nextjs-headers-test 

Look at network tab. See how the api 'hello' request has the content type 'application/json; charset=utf-8'
It does not have application/pdf as set in the api route:
```
export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>,
) {
  res.setHeader("Content-Type", "application/pdf");
  res.status(200).json({ name: "John Doe" });
}
```
I followed [the docs here](https://nextjs.org/docs/pages/api-reference/next-config-js/headers#cache-control) for how to use setHeader.

### Current vs. Expected behavior

I expect the content-type header in the response to match whatever string I provide it in the api route when using res.setHeader().

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 21.1.0
  npm: 10.2.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

API route headers

### Which stage(s) are affected? (Select all that apply)

none - its an api issue.

### Additional context

I also tried setting it config like:
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async headers() {
    return [
      {
        source: '/api/hello',
        headers: [
          {
            key: 'Content-Type',
            value: 'application/pdf',
          },
        ],
      },
    ]
  },
};

export default nextConfig;
 ```
Which also did not work, which is a slight relief due to its terribly awkward DX.

**Comment by icyJoseph** [comment]
Is the issue here that, `.json` implicitly, sets the header for you though? 

- https://github.com/vercel/next.js/blob/ac46ffe08f5cdd8490dfef4226d0116724c0ebd2/packages/next/src/server/api-utils/node/api-resolver.ts#L393

That one assigns the `sendJson` function to the `NextApiReponse` object, which in turn:

- https://github.com/vercel/next.js/blob/ac46ffe08f5cdd8490dfef4226d0116724c0ebd2/packages/next/src/server/api-utils/node/api-resolver.ts#L120-L125

Forces the header to `application/json`.

To send a pdf, you need to do something different. You can google a solution, most use a stream to send the chunks to the client.

**Comment by AshConnolly** [comment]
Thanks for the reply @icyJoseph!

I'm actually not trying to send a pdf. I need to send a custom content-type header, like 'application/hello', that will send a json payload. 

So you know how I would achieve this? How do I get around next js overwriting my setHeader()?

**Comment by icyJoseph** [comment]
Use the `send` helper:

```js
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next';

export default function handler(req: NextApiRequest, res: NextApiResponse) {
  res.setHeader('Content-Type', 'application/pdf'); 
  res.status(200).send(JSON.stringify({ name: 'John Doe' }));
}
```

Then again, this will really cause some strange behavior, because a browser might try to actually show a pdf if you go to that endpoint.

**Comment by AshConnolly** [comment]
Thanks @icyJoseph, that work around does the job! Cheers! 😃
