### ISSUE TITLE
Error happens when route handler called with suspense enabled

### ISSUE THREAD

**Issue by nononcrust** [vercel/next.js#66816]
### Link to the code that reproduces this issue

https://github.com/nononcrust/nextjs-suspense-route-handler

### To Reproduce

1. Start the application in development (next dev)
2. navigate to home ('/')
3. useSuspenseQuery (GET /api/posts) immediately gets called
4. Uncaught Error happens: The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.

### Current vs. Expected behavior

when route handlers called with suspense enabled, I expected it to work as normal, but I observed an error on console as below.

<img width="1411" alt="Screenshot 2024-06-13 at 12 05 58 PM" src="https://github.com/vercel/next.js/assets/94950829/2151a01e-ea31-4504-a12a-bc81dac6b3ec">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: 1.22.21
  pnpm: 8.14.0
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by nononcrust** [comment]
resolved changing absolute URL to full URL

**Comment by icyJoseph** [comment]
During SSR, fetch/axios is happening on the server, and there there's no base URL go from, so a relative path is not really applicable, and it ends up causing the operation to fail.

You need to change how you do this. What they seem to recommend in that data fetching library is to fetch on the server, and use that result as hydration data for your hooks. I think if you read through this guide, it will eventually make sense: https://tanstack.com/query/v5/docs/framework/react/guides/advanced-ssr

**Comment by nononcrust** [comment]
What I'm trying to do is make api call exclusively on client. When using useQuery it doesn't query on build as I expected but after changing it to useSuspenseQuery it gets called on build time. is There any way to solve this problem?
