### ISSUE TITLE
Turbopack: --turbo couldn't dayjs molude resolution within cal-heatmap library.

### ISSUE THREAD

**Issue by ryota-murakami** [vercel/next.js#66826]
### Link to the code that reproduces this issue

https://github.com/ryota-murakami/reproduction-turbopack-can-not-find-dayjs-local-module

### To Reproduce

1. pnpm install
2. pnpm dev --turbo
3. You'll encounter the issue

If you run with `pnpm dev`, the issue not happen.

### Current vs. Expected behavior

# Expect Behavior(current 'next dev' behavior)
Show heatmap correctly.

![Screenshot 2024-06-13 at 20 56 44](https://github.com/vercel/next.js/assets/5501268/eefecf24-8e57-4e89-9ae1-296acfcf043f)

# Current Behavior

Build error turbo couldn't resolve `import("dayjs/locale/~`.

![Screenshot 2024-06-13 at 20 57 41](https://github.com/vercel/next.js/assets/5501268/01138351-264e-4fdb-965e-dce8554b1adc)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 22.2.0
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: 9.3.0
Relevant Packages:
  next: 15.0.0-canary.28 // Latest available version is detected (15.0.0-canary.28).
  eslint-config-next: N/A
  react: 19.0.0-rc-6f23540c7d-20240528
  react-dom: 19.0.0-rc-6f23540c7d-20240528
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I'd like to create UI similar to Github weed, so I tried [Cal-Heatmap](https://cal-heatmap.com/) library in side project.  
I use to `next dev --turbo` by default so I encountered this issue.

I'm glad to this report will help Turbopack get a little closer to Webpack's drop in replacement. 😄

**Comment by ForsakenHarmony** [comment]
The import unfortunately is too dynamic for turbopack to analyze, I'm not sure if this is something that can be fixed soon.

**Comment by ryota-murakami** [comment]
@ForsakenHarmony Thanks for your hard work on this project! I noticed that the import is too dynamic for Turbopack to analyze. Hope this can be resolved. Keep up the great work!

**Comment by timneutkens** [comment]
@sokra mentioned we'll likely have to support the `.concat` case as webpack analyzes it too

**Comment by ForsakenHarmony** [comment]
Will be fixed with the next canary after turbopack is updated

**Comment by ryota-murakami** [comment]
@ForsakenHarmony Thank you!
