### ISSUE TITLE
Turbopack: Failed to compile (turbo) with (react-pdf) 

### ISSUE THREAD

**Issue by yasseralsaidi** [vercel/next.js#66839]
### Link to the code that reproduces this issue

https://github.com/yasseralsaidi/turbowithreactpdf

### To Reproduce

1. pnpm install
2. pnpm dev --turbo
3. you'll encounter the issue

### Current vs. Expected behavior

i expect to run normally, but when use turbo it failed to compile, so i back to use it without --turbo

### Provide environment information

```bash
"react": "^18",
   "react-dom": "^18",
   "next": "14.2.4",
   "react-pdf": "^9.0.0"
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

![screenshot-localhost_3000-2024 06 13-17_16_38](https://github.com/vercel/next.js/assets/70948326/b4d91b4f-8c06-4f44-a53d-5dc5de3fe4d7)

**Comment by jcorrie** [comment]
I'm having the same issue.

**Comment by kdy1** [comment]
Closing as duplicate of https://github.com/vercel/next.js/issues/65406
