### ISSUE TITLE
The Edge Function "middleware" size is 1.01 MB and your plan size limit is 1 MB. Though the file is 173kb

### ISSUE THREAD

**Issue by danielanitsa** [vercel/next.js#66895]
### Link to the code that reproduces this issue

https://github.com/danielanitsa/book-summary-app

### To Reproduce

1. Go to my github repo named "book-summary-app"
2. clone the repo
3. install the dependencies and run "bun run build"

You will see:
![Screenshot_1](https://github.com/vercel/next.js/assets/104932432/fb5f7059-2ed8-4f5c-9872-8b4b1c63226e)

4. Go to vercel and try to host the app

You will see this:

![Screenshot_2](https://github.com/vercel/next.js/assets/104932432/adfcb7fd-0f2e-496c-ab3d-a2cf75a1e572)

### Current vs. Expected behavior

The expected behavior was to host the web app without any issues since I followed the docs, however I get this weird and absurd error despite not exceeding any limits that vercel puts

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #4355-Microsoft Thu Apr 12 17:37:00 PST 2024
  Available memory (MB): 16255
  Available CPU cores: 12
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

I switched node js versions and re-installed all the packages. I went from using v22.0.3 to v20.14.0 LTS. Also I switched from next js 14.2.2 to next js 14.2.4

**Comment by Tittoh** [comment]
I have this problem too after upgrading to Next.js 14.2.4

**Comment by icyJoseph** [comment]
Set this up: https://www.npmjs.com/package/@next/bundle-analyzer

Three browser windows will open up. One of them is the middleware bundle, what do you see there?

**Comment by danielanitsa** [comment]
![middleware_size_screenshot](https://github.com/vercel/next.js/assets/104932432/91c571eb-368b-4e4c-a464-85360533f830)

As you can see @icyJoseph , this isnt even close to 1MB  that vercel says. What should I do?

**Comment by icyJoseph** [comment]
Ok, time to reach out to the Vercel Support team. They ought to be able to tell you why your Middleware is so large, according to their metric.

**Comment by danielanitsa** [comment]
Due to inactivity and impossible way to fix this, I am closing this issue. Thanks to everyone in here for contributing
