### ISSUE TITLE
global-error.tsx doesn't work next.js 14+

### ISSUE THREAD

**Issue by pathliving** [vercel/next.js#66905]
### Link to the code that reproduces this issue

https://nextjs-global-error.vercel.app/en
https://github.com/pathliving/nextjs_global_error

### To Reproduce

I create a repo https://github.com/pathliving/nextjs_global_error to show that `global-error.tsx` cannot catch errors from root `layout.tsx`

### Current vs. Expected behavior

`global-error.tsx` should handle errors from root `layout.tsx` as described in the [official documentation](https://nextjs.org/docs/app/api-reference/file-conventions/error#global-errorjs)

### Provide environment information

```bash
Operating System:
  Arch: arm64
  Version: MacOS Sonoma 14.5
Binaries:
  Node: 20.13.1
  npm: N/A
  Yarn: N/A
  pnpm: 8.15.7
Relevant Packages:
  next: latest
  react: latest
  react-dom: latest
  typescript: 5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Internationalization (i18n), Runtime

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local)

### Additional context

N/A

**Comment by HackerQED** [comment]
+1, I encounter this too
