### ISSUE TITLE
Layout is re-rendered when server action is called

### ISSUE THREAD

**Issue by festusyuma** [vercel/next.js#66961]
### Link to the code that reproduces this issue

https://github.com/festusyuma/next-issue-test

### To Reproduce

1. start application in dev mode
2. navigate to url
3. click on the next buttom
4. log on layout will be printed for almost every click to indicate the layout was rendered again on the server

5. checkout to react-hook-form and repeat steps 1 - 4, same thing will happen when using react-hook-form
6. checkout to react-hook-form-api and repeat 1-4, this will not re-render the layout when calling external api

https://photos.app.goo.gl/L2faEJPxTYDUibeBA (video sample)

### Current vs. Expected behavior

Expected behaviour: Layout should not be re-rendered when server action is called
Current behaviour: Layout is re-rendered when server action is called. this happens even when you have children and grandchildren layout. it is re-rendered from top to bottom

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Thu May 30 21:30:12 PDT 2024; root:xnu-11215.0.31.511.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: 8.15.8
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app, Developer Experience, Performance

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), Other (Deployed)

**Comment by InsightfulFuture** [comment]
This appears to be resetting state in my app

**Comment by techgerm** [comment]
We're experiencing the same this as well - is this expected behavior?

**Comment by wyattjoh** [comment]
This seems expected as you're calling `redirect` within the server component which causes the whole page to get re-rendered.

**Comment by festusyuma** [comment]
> This seems expected as you're calling `redirect` within the server component which causes the whole page to get re-rendered.

@wyattjoh is that the expected behaviour?

**Comment by festusyuma** [comment]
> This seems expected as you're calling `redirect` within the server component which causes the whole page to get re-rendered.

@wyattjoh Also if you check the react-hook-form branch, you can see I am not doing a redirect in the server action and this behaviour still occurs. 

Please can this be re-opened?. or has a fix been done already

**Comment by festusyuma** [comment]
> > This seems expected as you're calling `redirect` within the server component which causes the whole page to get re-rendered.
> 
> @wyattjoh Also if you check the react-hook-form branch, you can see I am not doing a redirect in the server action and this behaviour still occurs.
> 
> Please can this be re-opened?. or has a fix been done already

@wyattjoh 

This is a recording of this exact behaviour without redirect in the server action. this reason you added is false. I will appreciate if you can re-open this ticket. I have created 3 branches to show it in 2 ways with issues and one that works properly, that is when no server action is involved. 

https://photos.app.goo.gl/f3QLgXunuTbPNeuq8

**Comment by festusyuma** [comment]
@wyattjoh Closing and refusing to re-open the issue even after I have provided video recording showing that your statement is false isn't really nice. 2 weeks

The least you could've done was left the issue as is instead of closing it. I will be recreating this issue again
