### ISSUE TITLE
Turbopack doesn't correctly handle catch-all segments in nested route groups

### ISSUE THREAD

**Issue by grahamorrell** [vercel/next.js#67045]
### Link to the code that reproduces this issue

https://github.com/NorthLink-Digital/turbo-catch-all-issue

### To Reproduce

Above repo is plain create-next-app with minimal folders/pages added to recreate the issue

Start in normal dev mode (pnpm dev)
- hit http://localhost:3000/admin <- will see ADMIN PAGE (correct)
- hit http://localhost:3000/foo <- will see CMS PAGE (correct)

Start in dev turbo mode (pnpm dev:turbo)
- hit http://localhost:3000/admin <- will see CMS PAGE (INCORRECT!)
- hit http://localhost:3000/foo <- will see CMS PAGE (correct)

### Current vs. Expected behavior

Following the steps in the previous section, when running with turbo, when hitting http://localhost:3000/admin I should see ADMIN PAGE not CMS PAGE

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 32603
  Available CPU cores: 8
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: 8.6.10
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by timneutkens** [comment]
Thanks for the report! Very helpful 🙏
