### ISSUE TITLE
Unexpected Caching Behavior with revalidate in Next.js

### ISSUE THREAD

**Issue by unisol1020** [vercel/next.js#67070]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/serene-napier-go8s7s

### To Reproduce

	1.	Create a Next.js page without the revalidate property.
	2.	Observe that there is no caching.
	3.	Add the revalidate property with a value (e.g., revalidate: 2).
	4.	Notice that the data is cached indefinitely, with only a hard reload bypassing the cache.

### Current vs. Expected behavior

        •	No caching occurs without the revalidate property.
	•	Setting the revalidate property results in permanent caching, bypassed only by a hard reload.
	
	•	Pages should have default caching behavior without explicitly setting revalidate.
	•	The revalidate property should control caching according to the specified interval.

### Provide environment information

```bash
Next.js version: 14.x
Node.js version: 20.x.x
Browser: Chrome
Operating System: macOS


### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

We suspect that we might have configured our project incorrectly, leading to this caching issue. Any guidance or fixes would be greatly appreciated.

**Comment by salos1982** [comment]
Have the same issue
