### ISSUE TITLE
RSC Fetch Logging deduplicates requests if they share the same URL, even if POST bodies are different

### ISSUE THREAD

**Issue by switz** [vercel/next.js#67103]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/serene-napier-go8s7s?file=%2Fapp%2Fpage.tsx%3A2%2C33

### To Reproduce

1. create an RSC app + set fullUrl logging
2. make several fetch POST requests to the same URL w/ different bodies
3. check logs
4. add Math.random() to the URL params to make the paths different

### Current vs. Expected behavior

current:

```
 GET /home 200 in 10709ms
 │ POST http://localhost:8080/v1/graphql 200 in 63ms (cache skip)
 │ │ Cache skipped reason: (cache: no-cache)
```

expected:
```
 GET /home 200 in 177ms
 │ POST http://localhost:8080/v1/graphql 200 in 18ms (cache skip)
 │ │ Cache skipped reason: (revalidate: 0)
 │ POST http://localhost:8080/v1/graphql 200 in 42ms (cache skip)
 │ │ Cache skipped reason: (cache: no-cache)
 │ POST http://localhost:8080/v1/graphql 200 in 44ms (cache skip)
 │ │ Cache skipped reason: (cache: no-cache)
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.13.0
  npm: 8.1.0
  Yarn: 1.22.19
  pnpm: 8.15.7
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 14.2.3
  react: 19.0.0-rc-3563387fe3-20240621
  react-dom: 19.0.0-rc-3563387fe3-20240621
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by feedthejim** [comment]
Closing as this does not actually include a valid repro.

**Comment by switz** [comment]
Apologies, I pasted the wrong link, you can re-open this: https://codesandbox.io/p/devbox/serene-villani-fmyxrz?file=%2Fapp%2Fpage.tsx
