### ISSUE TITLE
With turbopack, re-exports such as "export * from '@prisma/client' are not processed correctly (monorepo)

### ISSUE THREAD

**Issue by tomitrescak** [vercel/next.js#67195]
### Link to the code that reproduces this issue

https://github.com/vercel/turbo/tree/main/examples/with-prisma

### To Reproduce

I am suing standard starter for turbobuild with prisma

1.  Add the following code to "app/page.tsx"

```
import * as Prisma from "@repo/database";
console.log(Prisma);
```

2. Run "pnpm generate" to generate your DB (change to sqlite if you need)
3. Run "pnpm dev --turbo"
4. Observer that none of the "re-exports" from the database are available (only "prisma", which is re-exported specifically)
5. Run "pnpm dev"
6. See that all exports are now available

### Current vs. Expected behavior

Currently, when re-exporting from prisma/client in a turborepo the exports are NOT included.

I want to be able to re-export from package in turborepo with "export * from '@prisma/client'

I have enums and other structures that I need to be exported.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 21.7.2
  npm: 10.5.2
  Yarn: 1.22.19
  pnpm: 9.4.0
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 14.2.4
  react: 19.0.0-rc-107a2f8c3e-20240617
  react-dom: 19.0.0-rc-107a2f8c3e-20240617
  typescript: 5.5.1-rc
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by tomitrescak** [comment]
FYI, the following does not work with turbopack, only with webpack:

```
export * from "@prisma/client";
```

This does work with turbopack

```
export { AchievementType, PrismaClient } from "@prisma/client";
```

Not optimal.

**Comment by ForsakenHarmony** [comment]
Can't reproduce on the latest canary, if you're still running into this can you create your own repository with a repro?

Linking to a template is not ideal
