### ISSUE TITLE
Docs: Dashboard-App Chapter 7 - Mismatch between screenshots and current state of RevenueChart

### ISSUE THREAD

**Issue by stevenlybeck** [vercel/next.js#67225]
### What is the update you wish to see?

Screenshots on https://nextjs.org/learn/dashboard-app/fetching-data should be changed to match what actually happens for people who have followed the chapters up to this point.

### Is there any context that might help us understand?

The page says `Then, uncomment the <RevenueChart/> component, navigate to the component file (/app/ui/dashboard/revenue-chart.tsx) and uncomment the code inside it. Check your localhost, you should be able to see a chart that uses revenue data.`

In fact, the code currently included in the project for the RevenueChart component (https://github.com/vercel/next-learn/blame/main/dashboard/starter-example/app/ui/dashboard/revenue-chart.tsx) has commented out the part that renders a graph.

So people who have followed the tutorial up to Chapter 7 will not see the graph displayed as shown in the screenshot at https://nextjs.org/learn/dashboard-app/fetching-data#fetching-data-for-revenuechart

The same seems to be true for the LatestInvoices component - the screenshot in the tutorial at https://nextjs.org/learn/dashboard-app/fetching-data#fetching-data-for-latestinvoices - does not match because in the code at https://github.com/vercel/next-learn/blob/main/dashboard/starter-example/app/ui/dashboard/latest-invoices.tsx - most of the component's function has been commented out.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/fetching-data

**Comment by delbaoliveira** [comment]
Hey @stevenlybeck, the instruction you mentioned above tells the user to navigate to the component and uncomment the code inside it. Was it not clear that you should also uncomment the code inside the component? 

If so, we can update the wording for clarity.

**Comment by leerob** [comment]
Updated, thanks!
