### ISSUE TITLE
Docs: Next 15 RC docs still have outdated information about caching

### ISSUE THREAD

**Issue by kasraghoreyshi** [vercel/next.js#67238]
### What is the update you wish to see?

According to Next 15 RC announcement, fetch requests and GET route handlers are not cached by default anymore but the [docs still imply](https://rc.nextjs.org/docs/app/building-your-application/caching#:~:text=By%20default%2C%20data,are%20cached) that they are, so they should be updated accordingly to avoid confusion or to be an accurate reference about the new caching behavior

### Is there any context that might help us understand?

I tried to make a PR but I noticed both the RC docs and the actual live docs are located in the same branch, or at least that's how it seems by clicking the "Edit this page" button on the said page

### Does the docs page already exist? Please link to it.

https://rc.nextjs.org/docs/app/building-your-application/caching

**Comment by delbaoliveira** [comment]
Thank you raising this @kasraghoreyshi 🙏🏼 , here's the PR to update it: https://github.com/vercel/next.js/pull/67279
