### ISSUE TITLE
Could not locate an example named "with-stripe-typescript"

### ISSUE THREAD

**Issue by Olanetsoft** [vercel/next.js#67310]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
npm ERR! npx canceled due to missing packages and no YES option: ["next@14.2.4"]

npm ERR! A complete log of this run can be found in: /mypath/
```

### Which example does this report relate to?

https://github.com/vercel/next.js/tree/canary/examples/with-stripe-typescript

### Describe the Bug

I ran into an error running the following command:

```
npx create-next-app --example with-stripe-typescript with-stripe-typescript-app
```

The Error:

```
Could not locate an example named "with-stripe-typescript". It could be due to the following:
 1. Your spelling of example "with-stripe-typescript" might be incorrect.
 2. You might not be connected to the internet or you are behind a proxy.
 ```

### Expected Behavior

To create the project example.

### To Reproduce

From your terminal run the following:

```
npx create-next-app --example with-stripe-typescript with-stripe-typescript-app
```

**Comment by ztanner** [comment]
Hi, I was unable to reproduce this issue. Please check to ensure that you had network connectivity and aren't behind any sort of firewall restrictions that would prevent you from retrieving this URL: https://api.github.com/repos/vercel/next.js/contents/examples/with-stripe-typescript

![CleanShot 2024-07-03 at 11 47 58@2x](https://github.com/vercel/next.js/assets/1939140/de0c30ce-99ce-4785-a3cc-bfefe6a73a4a)
