### ISSUE TITLE
Your Team encountered an unknown problem. Please reach out to our support team for details. Learn More

### ISSUE THREAD

**Issue by OmarRayes98** [vercel/next.js#67316]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
NEXT_PUBLIC_SANITY_PROJECT_ID="wwggeit9"
NEXT_PUBLIC_SANITY_DATASET="production"
```

### Which example does this report relate to?

Your Team encountered an unknown problem. Please reach out to our support team for details. Learn More

### Describe the Bug

Your Team encountered an unknown problem. Please reach out to our support team for details. [Learn More](https://vercel.com/help)

### Expected Behavior

.

### To Reproduce

Your Team encountered an unknown problem. Please reach out to our support team for details. [Learn More](https://vercel.com/help)

**Comment by ztanner** [comment]
Hi - it doesn't seem like there's enough information in your post for us to investigate. As this error sounds specific to a Vercel deployment, please follow the suggestion in the error message and open a support ticket.
