### ISSUE TITLE
The RSC payload includes server data from all segments, including those from shared layout

### ISSUE THREAD

**Issue by gkielwasser** [vercel/next.js#67347]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/practical-sunset-ngmmgq

### To Reproduce

1. build the application
2. open developer tab to be able to inspect XHR requests
3. Navigate to `/lang/page-1`
4. observe RSC payload related to page-2

### Current vs. Expected behavior

I expect the server data from the shared layout not to be included in the RSC payload of each subpage. This data should be loaded once, just like the layout template.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.0-canary.49 // Latest available version is detected (15.0.0-canary.49).
  eslint-config-next: N/A
  react: 19.0.0-beta-04b058868c-20240508
  react-dom: 19.0.0-beta-04b058868c-20240508
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next start (local), Vercel (Deployed)

### Additional context

This can only be seen on production to be able to see the RSC payload of the page.

As soon as a server component will pass data to a client component, those data seems to be added to the RSC payload.

If numerous pages contain a client component with data provided by a common server component, the RSC payload between these pages will be highly redundant.

Navigating from `/lang/page-1` to `/lang/page-2` won't make re-render the `/lang` shared layout. We retrieve data that won't be used during navigation.

**Comment by wyattjoh** [comment]
In order to minimize costs associated with running serverless functions, the current implementation creates these RSC payloads statically, and therefore can't do the special logic around minimizing the RSC payload size. If these pages were instead set to render via:

```
export const dynamic = "force-dynamic"
```

Then you'd see the RSC payloads minimized. Work related to partial prerendering will help with some of this in the future, but it's a bit out.

**Comment by gkielwasser** [comment]
I guess it should be turned in a discussion but i don't get how we can then share data accross pages? 

Let's say I have 1'000 pages sharing the same 10KB of common data that will be used by client components. How can I then share those data between those pages in order to:
1- avoid having the same common data stored in cache for those 1'000 pages
2- avoid a user session which visits or prefetch n of those pages will download n times those common data
3- avoid turning all the leafs of those pages to dynamic pages (using force-dynamic) in case those pages are purely static pages and should be built once and then served from the cache
4- avoid loading those common data client side

Thanks a lot!
