### ISSUE TITLE
Docs: Update Nextjs template for supabase

### ISSUE THREAD

**Issue by SlavenDj** [vercel/next.js#67349]
### What is the update you wish to see?

Update supabase code for supabase latest update

### Is there any context that might help us understand?

The signature '(supabaseUrl: string, supabaseKey: string, options: SupabaseClientOptions<"public"> & { cookieOptions?: any; cookies: CookieMethodsServerDeprecated; cookieEncoding?: "raw" | ... 1 more ... | undefined; }): SupabaseClient<...>' of 'createServerClient' is deprecated.

### Does the docs page already exist? Please link to it.

https://supabase.com/docs/guides/auth/server-side/nextjs

**Comment by ekremkenter** [comment]
I have opened a PR for this. #67413
