### ISSUE TITLE
It wont load i cant deploy websites or import them from github

### ISSUE THREAD

**Issue by Xavielu** [vercel/next.js#67405]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
deployment not working so i stay on chrome an cant advance to editing my boilerplate
```

### Which example does this report relate to?

deployment

### What browser are you using? (if relevant)

chome Version 126.0.6478.127 

### How are you deploying your application? (if relevant)

through github but i cant becuase i cant see my repositors 

### Describe the Bug

every time i try to see my repositories on vercel they never load and when I click add github account it sends be to a about blank page and i have not found a solution to this i try to use boilerplates and thye dont intergrade with my GitHub I've made multiple accounts to see this problem  and i have tried 

Import Third-Party Git Repository → but my  git scope never loads i have left it loading in the background for two hours it just keeps on loading

### Expected Behavior

i want to see my git repositories and import or use boilerplates

### To Reproduce

no syntax error

**Comment by ztanner** [comment]
Hi, this doesn't sound like a Next.js issue and you have not provided any information for us to look into the problem.

If this is related to deploying on Vercel, please see https://vercel.com/help.
