### ISSUE TITLE
@next/mdx not compatible with --turbo

### ISSUE THREAD

**Issue by goatyeahh** [vercel/next.js#67453]
### Link to the code that reproduces this issue

https://github.com/goatyeahh/next-mdx-turbo-bug

### To Reproduce

1. Start the app
2. Go to "/"

### Current vs. Expected behavior

 ⨯ Error: Expected process result to be a module, but it was ignored

Debug info:
- Execution of get_written_endpoint_with_issues failed
- Execution of <AppEndpoint as Endpoint>::write_to_disk failed
- Execution of Project::emit_all_output_assets failed
- Execution of VersionedContentMap::insert_output_assets failed
- Execution of all_assets_from_entries failed
- Execution of AppEndpointOutput::output_assets failed
- Execution of AppEndpoint::output failed
- Execution of get_app_page_entry failed
- Execution of <FileSystemPath as ValueToString>::to_string failed
- Execution of AssetIdent::path failed
- Execution of Module::ident failed
- Execution of ProcessResult::module failed
- Expected process result to be a module, but it was ignored

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: 1.22.19
  pnpm: 9.4.0
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ywwa** [comment]
works when you add following to `next.config.js`

```js
  experimental: {
    mdxRs: true,
  },
```

**Comment by samcx** [comment]
The above comment is true—you need to be using the experimental flag if you want to use this with `--turbo`.

https://nextjs.org/docs/app/building-your-application/configuring/mdx#using-the-rust-based-mdx-compiler-experimental

![CleanShot 2024-09-10 at 16 21 00@2x](https://github.com/user-attachments/assets/5a6854f3-571b-48b0-b02e-facf0d509985)

The team has been made aware of this! We should definitely add a better error message in there.

I will be marking this as closed since it does work with the experimental flag.

**Comment by lauri865** [comment]
But it doesn't really allow any of the previous configuration of @next/mdx, does it @samcx? E.g. adding remark/rehype plugins.

**Comment by samcx** [comment]
> But it doesn't really allow any of the previous configuration of @next/mdx, does it @samcx? E.g. adding remark/rehype plugins.

@lauri865 I have not actually tried (it is experimental) yet. Curious if this is what you've experienced <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>
