### ISSUE TITLE
sitemap.ts generates /sitemap endpoint instead of /sitemap.xml

### ISSUE THREAD

**Issue by vojtechmares** [vercel/next.js#67481]
### Link to the code that reproduces this issue

https://github.com/vojtechmares/bug-nextjs-sitemap-url

### To Reproduce

1. Start app `pnpm run dev`
2. Go to `/sitemap.xml`, get 404 error
3. Go to `/sitemap`, get the actual sitemap

### Current vs. Expected behavior

I expect according to docs that `app/sitemap.ts` file in the app router directory will create a public `/sitemap.xml` endpoint, but the sitemap is accessible at `/sitemap` instead

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.8.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.2.0
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 14.2.3
  react: 19.0.0-rc-935180c7e0-20240524
  react-dom: 19.0.0-rc-935180c7e0-20240524
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Documentation, Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

I am using the Next.js 15-RC with React 19 and experimental React Compiler

**Comment by devjiwonchoi** [comment]
Hi, could you try the latest version of canary? We had a fix for similar issue.

**Comment by vojtechmares** [comment]
I can confirm, updating to latest canary release (at the time of writing [v15.0.0-canary.55](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.55)) fixed the issue.

Thanks @devjiwonchoi !
