### ISSUE TITLE
Docs:  *.mjs type file missing

### ISSUE THREAD

**Issue by sorydi3** [vercel/next.js#67548]
### What is the update you wish to see?

add opcion for `next.config.mjs` file type

### Is there any context that might help us understand?

My docker build was failing because of this. I was unsure whether the `next.config.js` and `next.config.mjs` file type was the same. I had to google it to find out it indeed was the same file.

### Does the docs page already exist? Please link to it.

https://github.com/vercel/next.js/tree/canary/examples/with-docker

**Comment by leerob** [comment]
Hey! This is updated on `canary` and the latest RC docs. It will be live with v15 stable.

https://rc.nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#pending-states

**Comment by leerob** [comment]
Going forward, we are going to recommend using `next.config.ts` (which is now live on `canary`).
