### ISSUE TITLE
Docs: supported versions

### ISSUE THREAD

**Issue by aalvarado** [vercel/next.js#67604]
### What is the update you wish to see?

I'm looking for information on what the currently available versions for Nextjs are and what are the dates until they're supported.

Been looking around the site and docs and have not been able to find this information.

I'm working with someone who has version 11 and reviewing what steps are necessary to update to the latest stable release

### Is there any context that might help us understand?

Versioned docs would be nice, or a migration path for those with old outdated versions 

### Does the docs page already exist? Please link to it.

no

**Comment by delbaoliveira** [comment]
Hey @aalvarado, I don't think we have specific documentation on how long versions are supported for, but we tend to backport security fixes. As for features, these are added to the latest minor versions. 

We have version-specific upgrade guides here:

- [Version 12](https://nextjs.org/docs/pages/building-your-application/upgrading/version-12)
- [Version 13](https://nextjs.org/docs/pages/building-your-application/upgrading/version-13)
- [Version 14](https://nextjs.org/docs/pages/building-your-application/upgrading/version-14) 
- [Migrating to the App Router](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration) if you're going down this path.

**Comment by aalvarado** [comment]
Great, I appreciate the links. I saw this page and was wondering if I might have missed the source. https://endoflife.date/nextjs .
