### ISSUE TITLE
Use createPaginationContainer cause to look for an un-existing query

### ISSUE THREAD

**Issue by stalinb87** [vercel/next.js#67614]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/7tc9th?file=%2F.codesandbox%2Ftasks.json

### To Reproduce

1. Setup a next js application using relay js
2. Create a component using the createPaginationContainer
3. Navigate to a page using that component

### Current Behavior
It fails to load because is trying to look for a query that doesn't exist it always looks for `to.graphql.js` 
<img width="962" alt="image" src="https://github.com/vercel/next.js/assets/2779135/6a367d11-c342-48e5-9269-d82f6b0a0573">

### Expected behavior
It should load the page without error

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.12.1
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

SWC

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

The relay compiler seems to be ok with this; if I run `pnpm relay-compiler`, it works fine

**Comment by kdy1** [comment]
It looks like an issue of regex for capturing the operation name.

Workaround would be removing `query to` in the comment.
```
# Pagination query to be fetched upon calling 'loadMore'.

```

**Comment by kdy1** [comment]
https://github.com/swc-project/plugins/pull/333 should fix this

**Comment by stalinb87** [comment]
That was it, I removed the comment, and it is working, thanks
