### ISSUE TITLE
Unable to connect to localhost the npm run dev is creashing | Thing is react js website is running fine but getting issue with nextjs only

### ISSUE THREAD

**Issue by nlaky1** [vercel/next.js#67701]
### Link to the code that reproduces this issue

https://github.com/nlaky1/website-youtube-video

### To Reproduce

start application 
hit localhost
server crashes

### Current vs. Expected behavior

application should start

### Provide environment information

```bash
mac m1 air
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tried all the available solution 
1. flush DNS
2. disable firewall
3. reinstalled node
4. tried with 0.0.0.0
5. thing is react js website is running fine but getting issue with nextjs only

**Comment by archanaagivale30** [comment]
@nlaky1 I tried to reproduce your issue but it's not reproduced on my system. The Application is working fine.

Environment: Macbook Pro M1

<img width="1365" alt="Screenshot 2024-07-15 at 12 00 14 PM" src="https://github.com/user-attachments/assets/0fa736a8-e78a-4266-bcc0-83c2a1d82806">
<img width="545" alt="Screenshot 2024-07-15 at 12 01 05 PM" src="https://github.com/user-attachments/assets/d6d658a0-c8b4-4e93-8c3d-6929b25e2d1e">

Can u share more details if still you are facing issue.

**Comment by icyJoseph** [comment]
It works fine here, https://stackblitz.com/github/nlaky1/website-youtube-video?file=README.md as well... maybe you have some network settings that you are not aware of? can you start any next.js project at all? Like `npx create-next-app`?

**Comment by nlaky1** [comment]
Hi Joseph,

Thanks for your reply it happened because of the some path issue

**Comment by icyJoseph** [comment]
Alright, but then if you did get it sorted out, please close the issue :)

**Comment by nlaky1** [comment]
resolved
