### ISSUE TITLE
Bug with unmatched Routes 

### ISSUE THREAD

**Issue by Robz187** [vercel/next.js#67719]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32695
  Available CPU cores: 12
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

parallel-routes

### What browser are you using? (if relevant)

Opera-GX

### How are you deploying your application? (if relevant)

local

### Describe the Bug

when i hard reload the parallel unmatched route the app shows me the not-found.tsx instead of the default.tsx

### Expected Behavior

I created like in the docs example page 2 @folders with a page.tsx and 1 default.tsx in the analytics folder and 1 in the root @team folder now when i expected the browser to render the default.tsx.

### To Reproduce

If you want to reproduce the bug just create your own https://nextjs.org/docs/app/building-your-application/routing/parallel-routes

**Comment by Robz187** [comment]
I will send a public github repo asap

**Comment by Robz187** [comment]
https://github.com/Robz187/nextjs-prob
I created the GitHub repo, but it seems bugged. If you look at both dashboards, they have the same code, except that one dashboard has 2 parallel routes and the other has more. The one with 2 routes works with the default.tsx, but the one with more information and pages does not work if you hard reload from the archive.

**Comment by ztanner** [comment]
> https://github.com/Robz187/nextjs-prob I created the GitHub repo, but it seems bugged. If you look at both dashboards, they have the same code, except that one dashboard has 2 parallel routes and the other has more. The one with 2 routes works with the default.tsx, but the one with more information and pages does not work if you hard reload from the archive.

Hi @Robz187 -- your `@users/default.tsx` component is spelled wrong. Notice it's `dafault.tsx` rather than `default.tsx`:
https://github.com/Robz187/nextjs-prob/blob/main/src/app/problem-dashboard/%40users/dafault.tsx

**Comment by Robz187** [comment]
Hi @ztanner -- thanks for your help i was stuck on this 10h but i guess 4 eyes are better than 2
