### ISSUE TITLE
Docs: server actions and mutations pending states

### ISSUE THREAD

**Issue by roycanani** [vercel/next.js#67720]
### What is the update you wish to see?

I would like to refactor the Pending states section [here](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#pending-states). Currently the example is using useFormStatus, but the rest of the documentation and the correct and updated way to do so is using `const [state, serverAction, isLoading] = useActionsStatus(...)`

### Is there any context that might help us understand?

As described before, the way to get pending state is much easier and cleaner.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#pending-states

**Comment by leerob** [comment]
Hey! This is updated on `canary` and the latest RC docs. It will be live with v15 stable.

https://rc.nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#pending-states
