### ISSUE TITLE
Failed to load SWC binary for win32/x64

### ISSUE THREAD

**Issue by Jobwafula** [vercel/next.js#67766]
### Link to the code that reproduces this issue

https://github.com/Jobwafula/hack-repairs.git

### To Reproduce

1.clone the repository
2.run npm install
3.run npm run dev 
The following error is encountered
![image](https://github.com/user-attachments/assets/996806cf-e590-440a-8b54-bb9c9c282feb)

### Current vs. Expected behavior

I expected the development server to start but instead  i got the error failed to load swc

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
  Available memory (MB): 7607
  Available CPU cores: 4
Binaries:
  Node: 18.18.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by kelvinsekx** [comment]
@Jobwafula how did you go around this?
I am experiencing the exact problem.

**Comment by kelvinsekx** [comment]
https://nextjs.org/docs/messages/failed-loading-swc
This solves it. Looks like it is a common problem. Delete node_modules & package-lock, then reinstall.

**Comment by timneutkens** [comment]
Going to close this issue as there haven't been new reports, it usually means your package manager indeed did not install in the correct folder.
