### ISSUE TITLE
Docs: Incorrect version history for sitemap adding changeFrequency and priority attributes to sitemaps

### ISSUE THREAD

**Issue by gnoyixiang** [vercel/next.js#67834]
### What is the update you wish to see?

The update should be in version 13.4.14
There is no update on when the `alternates` attribute was added.

### Is there any context that might help us understand?

Currently, the documentation is stating that the changeFrequency and priority attributes were added to sitemaps in version 13.4.5. But looking through the source code versions, the attributes were first added in 13.4.14

![image](https://github.com/user-attachments/assets/ada129c8-7bcf-440d-b7ea-36968ee22523)
![image](https://github.com/user-attachments/assets/ff7a2533-825f-421a-bb43-858ff94ccea3)
![image](https://github.com/user-attachments/assets/930f3a85-d927-4059-9de6-7950410317fc)

The `alternates` attribute was only added in version 14.2.0
![image](https://github.com/user-attachments/assets/bf7a919f-3c88-4971-a0bd-f6617ae3fabb)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap#version-history

**Comment by archanaagivale30** [comment]
@gnoyixiang Updates to the documentation PR have already been merged https://github.com/vercel/next.js/pull/66478.

**Comment by gnoyixiang** [comment]
> @gnoyixiang Updates to the documentation PR have already been merged #66478.

Thanks for the updates. But I believe `alternates` is still missed out.
