### ISSUE TITLE
<Link> component  make the page refresh new request ??

### ISSUE THREAD

**Issue by Bader975** [vercel/next.js#67836]
### Link to the code that reproduces this issue

https://github.com/Bader975/wajeeh

### To Reproduce

in this code Link making http request to the server why ?
<li className={classes["nav-link"]}>
          <Link href="/login">Login </Link>
        </li>

### Current vs. Expected behavior

it should be client-side navigation between routes there shuold not be refresh to the page 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 12
Binaries:
  Node: 20.15.1
  npm: 10.7.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

it should be client-side navigation between routes there shuold not be refresh to the page

**Comment by ztanner** [comment]
Hi, it looks like this is because you're using route groups to create multiple root layouts, and then navigating to a page in a different root layout.

This behavior is expected as described in the [docs](https://nextjs.org/docs/app/building-your-application/routing/route-groups#creating-multiple-root-layouts):

> Navigating across multiple root layouts will cause a full page load (as opposed to a client-side navigation). For example, navigating from /cart that uses app/(shop)/layout.js to /blog that uses app/(marketing)/layout.js will cause a full page load. This only applies to multiple root layouts.

**Comment by Bader975** [comment]
thank you that's right 
but how to solve it though ?
@ztanner

**Comment by ztanner** [comment]
You will need to move the pages into the same root layout. If the only reason to have a separate layout is so that you can show the nav bar on the index page, then consider moving the nav bar component only into the index page.

**Comment by Bader975** [comment]
Thank you , you are right @ztanner 🙏🏻
