### ISSUE TITLE
RSC request prevent on prefetch false

### ISSUE THREAD

**Issue by karthyTartLabs** [vercel/next.js#67886]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/xenodochial-link-5g95h4

### To Reproduce

- When I mouseover on a link in a web page, I want to prevent the RSC(.json) request. I tried to use the prefetch attribute in the link to prevent the RSC request call, but it didn't work.

### Current vs. Expected behavior

I expected to prevent the .json request call while mouseover on a Link. But it's not working

### Provide environment information

```bash
next: 13.5.6
react: 18.3.1
```

### Which area(s) are affected? (Select all that apply)

Pages Router

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by icyJoseph** [comment]
Did you try with a later version of Next.js?

**Comment by feedthejim** [comment]
The .json is not an RSC request on the Pages Router, it's the getServerSideProps content as a json value. We don't support opting out of the hover behaviour, however you could work around this by handling the event yourself and using router.push
