### ISSUE TITLE
Docs: definition of ServerComponent

### ISSUE THREAD

**Issue by heygsc** [vercel/next.js#67881]
### What is the update you wish to see?

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#unsupported-pattern-importing-server-components-into-client-components

In this document, if we do not use SSR specific things such as next/header in our ServerComponent, we can still import ServerComponent in the ClientComponent without any errors.Hope for more detailed explanation.

### Is there any context that might help us understand?

If a more detailed restriction/definition of ServerComponent is added in the document, such as ServerComponent must use something unique to SSR in order to be unable to be used in ClientComponent. Would this be better?

By the way, **import** SSR specific features into ServerComponent may not result in errors, but it needs to be **imported** and **used**, perhaps related to tree-shaking?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#unsupported-pattern-importing-server-components-into-client-components

**Comment by Anshgrover23** [comment]
@heygsc [https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#supported-pattern-passing-server-components-to-client-components-as-props](url) refer to this link to see the better explanation for this beside the above thing.

**Comment by Anshgrover23** [comment]
@heygsc hope I am not wrong and it will help you

**Comment by heygsc** [comment]
> @heygsc [https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#supported-pattern-passing-server-components-to-client-components-as-props](url) refer to this link to see the better explanation for this beside the above thing.

@Anshgrover23 Yes! This is what I am looking for. Thank you.

**Comment by Anshgrover23** [comment]
@heygsc welcome.
