### ISSUE TITLE
Docs: `pages/optimizePackageImports` points at `compress` instead

### ISSUE THREAD

**Issue by MonstraG** [vercel/next.js#67915]
### What is the update you wish to see?

https://nextjs.org/docs/pages/api-reference/next-config-js/optimizePackageImports

This page has contents of this page:

https://nextjs.org/docs/pages/api-reference/next-config-js/compress

### Is there any context that might help us understand?

App router docs are fine: https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/next-config-js/optimizePackageImports

**Comment by MonstraG** [comment]
Hmm, that was fixed in #64439, but still not live.

**Comment by samcx** [comment]
@MonstraG I believe it is <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> in our Release Candidate <picture data-single-emoji=":docs:" title=":docs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/docs/172e1b9b7d137b8a.png" alt=":docs:" align="absmiddle"></picture> → https://rc.nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports, which should be merged hopefully 🔜 !

Thanks for letting us know though.
