### ISSUE TITLE
Gravatar Error On Build

### ISSUE THREAD

**Issue by TJBriggs** [vercel/next.js#67979]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031
  Available memory (MB): 36864
  Available CPU cores: 14
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 4.9.5
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

cms-wordpress

### What browser are you using? (if relevant)

Chrome Version 126.0.6478.183 (Official Build) (arm64)

### How are you deploying your application? (if relevant)

Working Locally

### Describe the Bug

After running `npx create-next-app --example cms-wordpress cms-wordpress-app` and then updating the WORDPRESS_API_URL in .env.local, I then run `npm run dev`. I get the following error in my terminal:

```
 ⨯ Error: Invalid src prop (http://1.gravatar.com/avatar/729ae85bf62b9917e93538db2f2688ca?s=96&d=mm&r=g) on `next/image`, hostname "1.gravatar.com" is not configured under images in your `next.config.js`
See more info: https://nextjs.org/docs/messages/next-image-unconfigured-host
```
I followed the troubleshooting steps in the "See more info" link here: [https://nextjs.org/docs/messages/next-image-upgrade-to-13](https://nextjs.org/docs/messages/next-image-upgrade-to-13)

`npx @next/codemod next-image-to-legacy-image .`

and

`npx @next/codemod next-image-experimental .`

Unfortunately, the error above persists and the the `npm run dev` command continues to fail.

### Expected Behavior

The example project builds and runs as expected.

### To Reproduce

Run: `npx create-next-app --example cms-wordpress cms-wordpress-app` 
Then run: `npm run dev`.
You should get the error I'm seeing in my terminal.

**Comment by Juneezee** [comment]
As described in the error page https://nextjs.org/docs/messages/next-image-unconfigured-host, have you configured your `images.remotePatterns` config in `next.config.js` like so?

```js
module.exports = {
  images: {
    remotePatterns: [
      {
        protocol: 'http',
        hostname: '1.gravatar.com',
      },
    ],
  },
}
```

**Comment by ztanner** [comment]
Closing this as I believe the above response & the link in the error message should provide enough information for debugging this, and no repro was given to demonstrate an issue in the framework.
