### ISSUE TITLE
Error instance not preserved in `onRequestError`

### ISSUE THREAD

**Issue by kevva** [vercel/next.js#68004]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/dank-wood-nfdggc

### To Reproduce

1. Start the application by running `pnpm dev`
2. Click the button
3. Check the server logs, `This is a FooError` is never logged even though it's clearly that

### Current vs. Expected behavior

Currently the error instance is lost in `onRequestError` which makes it hard to check what kind of error is thrown and do different logging etc depending on that.

The expected behaviour would be for the error to be preserved. 

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.0-canary.75 // Latest available version is detected (15.0.0-canary.75).
  eslint-config-next: N/A
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Instrumentation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

It might be by design to throw a `DigestError` here, but it makes `onRequestError` kinda useless in comparison to what it could be since you have no idea what type of errors that are thrown.

**Comment by kevva** [comment]
@huozhi, I know you worked on the `onRequestError` feature. How would you advice handling cases like this where you need to know which kind of error that was thrown? Maybe I don't want to log **all** errors, maybe I have some other logic for some other errors.

```js
const onRequestError = error => {
  if (error instanceof MyCustomError) {
    doSomeThingDifferent();
    return;
  }

  console.error(error);
};
```

If you want to keep `error` as a `DigestError`, the source error could be added to the context or something.

**Comment by huozhi** [comment]
If you're throwing an error in RSC layer, the error will be processed by react renderer and then being collected by the error reporter. So far we cannot get the actual instance or class of it as the thrown one could be anything and React needs to serialize it to a general error that can also be sent to client. From bundling perspective, the `MyCustomerError` is also bundled separately in the instrumentation entry and the page entry, they would beccome two separate classes. So instanceof might not work as expected here.

You could give it some other special property for example `digest` property that it will still be reused by react renderer and preserved during rendering serialization.
