### ISSUE TITLE
[turbopack] Module factory is not available for packages that dynamically import other packages 

### ISSUE THREAD

**Issue by aidenybai** [vercel/next.js#68077]
### Link to the code that reproduces this issue

https://github.com/aidenybai/next-turbopack-dynamic-import-repro

### To Reproduce

1. `cd my-app`
2. `npm install`
3. `npm run dev`

![image](https://github.com/user-attachments/assets/12168367-1d5b-499c-a6a7-bdc4456e67a6)

### Current vs. Expected behavior

Packages that dynamically `import()` other packages should not throw error, should be properly bundled.

More info on repro: https://github.com/aidenybai/next-turbopack-dynamic-import-repro?tab=readme-ov-file#repro-instructions

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031
  Available memory (MB): 36864
  Available CPU cores: 14
Binaries:
  Node: 22.0.0
  npm: 10.5.1
  Yarn: 1.22.10
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I've had this fail with all dynamic imports on pages router

**Comment by timneutkens** [comment]
This is already fixed on next@rc. 14.2.5 is quite behind on Turbopack changes, would recommend using next@rc or next@canary with Turbopack when trying it. We'll add a warning on next@latest soon to ensure this is made clear 👍 

When reporting issues please make sure you check `next@canary`, which the issue template asks for. Thank you!
