### ISSUE TITLE
Weird Error happened after i have deployed my next app 

### ISSUE THREAD

**Issue by habeeb-nasr-12** [vercel/next.js#68104]
### Link to the code that reproduces this issue

https://github.com/habeeb-nasr-12/airbnb-next.git

### To Reproduce

```
'Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3914844493'
```
i am getting this error after i  have deployed my project with the some hours, i am not sure why i am getting this error ?
i am using next 14 with app router with Prisma , i have checked that every thing is fine especially   adding the env variables 

### Current vs. Expected behavior

it should work fine as it in the local but i didnt 

### Provide environment information

```bash
next 14 (app router)
```

### Which area(s) are affected? (Select all that apply)

Output (export/standalone)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

![image](https://github.com/user-attachments/assets/80b79972-3b03-415d-9886-49cd5a681edc)

**Comment by icyJoseph** [comment]
Do you have access to server side logs? You don't seem to be using export, nor, standalone 🤔

**Comment by ztanner** [comment]
Seems like you were able to figure it out as that app doesn't appear to have an error when visiting it! Feel free to open up an issue with more information about the error you're seeing in logs in case you weren't able to get it working.
