### ISSUE TITLE
Serving with turbo fails when node-cron is used: Server relative imports are not implemented yet

### ISSUE THREAD

**Issue by kl-thamm** [vercel/next.js#68101]
### Link to the code that reproduces this issue

https://github.com/klein-aber/minimal-example-node-corn-turbo

### To Reproduce

We have node cron in our next project, that we setup in instrumentation.ts. It is just one, very simple task.
However we need to switch to tubo asap, because otherwise our compilation times in dev are painfully slow (even on well equipped hardware). The thing that stops us from doing this is an error related to the node-cron module when running yarn dev --turbo:

```
 ⨯ ./node_modules/node-cron/src/background-scheduled-task
Module not found: Can't resolve '/ROOT/node_modules/node-cron/src/background-scheduled-task/daemon.js'
```

I have seen some related issues, but that was related to importing static assets. Is there any way I can fix this on my end except removing node-cron?

I originally posted this in turbo, because I have seen that issues related to turbo were moved to the turbo repo in the past, but turbo moved it here.

### Current vs. Expected behavior

Expected: Serve the app with turbo
Current behaviour: App crashes 

### Provide environment information

```bash
Tested it on many different systems (Mac, Docker with Ubuntu, Ubuntu on machine..) , its the same behaviour everywhere.
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by mischnic** [comment]
The full error message with the latest canary is
```
 ⨯ ./node_modules/.pnpm/node-cron@3.0.3/node_modules/node-cron/src/background-scheduled-task
Module not found: Can't resolve '/ROOT/node_modules/.pnpm/node-cron@3.0.3/node_modules/node-cron/src/background-scheduled-task/daemon.js'
server relative imports are not implemented yet. Please try an import relative to the file you are importing from.


https://nextjs.org/docs/messages/module-not-found


 ⨯ ./node_modules/.pnpm/node-cron@3.0.3/node_modules/node-cron/src/background-scheduled-task/index.js:29:28
Module not found: Can't resolve '/ROOT/node_modules/.pnpm/node-cron@3.0.3/node_modules/node-cron/src/background-scheduled-task/daemon.js'
  27 |     start() {
  28 |         this.stop();
> 29 |         this.forkProcess = fork(daemonPath);
     |                            ^^^^^^^^^^^^^^^^
  30 |
  31 |         this.forkProcess.on('message', (message) => {
  32 |             switch(message.type){



https://nextjs.org/docs/messages/module-not-found
```

**Comment by kl-thamm** [comment]
I dont really understand what `serverComponentsExternalPackages` (in 14.2.5) or `serverExternalPackages` (in 15) does, but it seems like the fix is just adding `node-cron` to that by default. I tried adding it to `serverComponentsExternalPackages` manually before and it does not address the bug - I am still getting an error, first when running the instrumentation.ts and then a build error when trying to use the frontend so I am a bit doubtful this would indeed fix the bug?
