### ISSUE TITLE
The error page is generated together with the normal page

### ISSUE THREAD

**Issue by drax314** [vercel/next.js#68189]
### Link to the code that reproduces this issue

https://github.com/drax314/next-error-render

### To Reproduce

1. npm install
2. npm run build && npm run start
3. go to http://localhost:3000/a/b
4. check the server console

### Current vs. Expected behavior

For every request, I can see that not only the page itself but also the error page is being rendered on the server:
 
Let's say we add console.log() to the homepage and the error page(_error.tsx). 

Then I would expect to see server output like this after few requests:
```
...
✓ Starting...
✓ Ready in 254ms
> Page.render
> Page.render
> Page.render
```

But console looks like this:

```
...
✓ Starting...
✓ Ready in 254ms
> Page.render
> ErrorPage.render
> Page.render
> ErrorPage.render
> Page.render
> ErrorPage.render
```

The browser console looks fine - only `> Page.render` is there, so this happens only on the server.

It almost looks like something in the background is doing st wrong, and that is generating an error page

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64
  Available memory (MB): 65536
  Available CPU cores: 16
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.22
  pnpm: 9.5.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Pages Router, Performance, Runtime

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local)

### Additional context

I managed to trace this issue back to Next.js 13.5.6. Wasn't trying older versions.

I also noticed that this issue can be observed only when these conditions are met:

- the page is SSR or SSG
- the path to the page includes at least one dynamic segment (`[a]/[page].tsx`)
- the _app.tsx exposes App.getInitialProps
- must be `next start`, not `next dev`
- Config must include `productionBrowserSourceMaps: true`
- The browser must have Javascript turned on - without JS, the issue won't appear

**Comment by icyJoseph** [comment]
I can't reproduce:

```console

> my-app@0.1.0 build
> next build

  ▲ Next.js 14.2.5

 ✓ Linting and checking validity of types
   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Collecting page data
Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
Read more: https://nextjs.org/docs/messages/opt-out-auto-static-optimization

 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (pages)                             Size     First Load JS
┌   /_app                                 0 B            78.4 kB
├ ƒ /[a]/[page]                           322 B          78.7 kB
└ ƒ /404                                  324 B          78.7 kB
+ First Load JS shared by all             78.4 kB
  ├ chunks/framework-cfa9d4eb87c8a3c3.js  45.2 kB
  ├ chunks/main-423c55ba40a83c6f.js       32.1 kB
  └ other shared chunks (total)           1.1 kB

ƒ  (Dynamic)  server-rendered on demand


> my-app@0.1.0 start
> next start --port 3004

  ▲ Next.js 14.2.5
  - Local:        http://localhost:3004

 ✓ Starting...
 ✓ Ready in 246ms
> Page.render
```

Going to `localhost:3004/a/b`, only logs that. Are you sure that you don't have other tabs open pointing to `localhost:3004/` or rather, the root path?

**Comment by drax314** [comment]
@icyJoseph Arrgh! Thanks to your comment, I did some more investigation and it is thanks to some browser extension... I'll be damned for this. Sorry for wasting your time :/

**Comment by icyJoseph** [comment]
No worries! It happens! Web dev is so complex these days 😅
