### ISSUE TITLE
[15.0.0-canary.77] - Introduced `45kb` bundle size increase from baseline

### ISSUE THREAD

**Issue by sannajammeh** [vercel/next.js#68190]
### Link to the code that reproduces this issue

https://github.com/sannajammeh/next-15-bundle-size

### To Reproduce

1. Run `pnpm install` - this should install `next@15.0.0-canary.76`
2. Run `pnpm build`
3. Observe the following build output:
```bash
  ▲ Next.js 15.0.0-canary.76

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (5/5)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    5.25 kB        96.1 kB
└ ○ /_not-found                          895 B          91.8 kB
+ First Load JS shared by all            90.9 kB
  ├ chunks/30-1f8632f1e67d748f.js        37.3 kB
  ├ chunks/f0ab610f-ee281ebe47d689aa.js  51.7 kB
  └ other shared chunks (total)          1.87 kB
```
4. Run `pnpm add next@15.0.0-canary.77`
5. Run `pnpm build` and observe the following build output:
```bash
  ▲ Next.js 15.0.0-canary.77

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (5/5)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    5.25 kB         141 kB
└ ○ /_not-found                          894 B           137 kB
+ First Load JS shared by all            136 kB
  ├ chunks/22349d5f-9cfcc05da94b45b1.js  51.7 kB
  ├ chunks/750-4b2fc9eb4516e55c.js       82.6 kB
  └ other shared chunks (total)          1.93 kB
```

6. Run `pnpm add next@canary` to install latest canary
7. Run `pnpm build` and observe that the result is the same as `canary.77` 

### Current vs. Expected behavior

It makes no sense why a canary bump would add 45 kb of JS to the bundle. Running `@next/bundle-analyzer` shows the issue:

### Canary 76 - No `react-dev-overlay` present in client bundle:
![image](https://github.com/user-attachments/assets/87216e53-db88-4ab2-a2a0-e1831c61b0d4)

### Canary 77 - `react-dev-overlay` is suddenly present:
![image](https://github.com/user-attachments/assets/7be2cb3d-366e-4de4-9414-1cf543aa5d3e)

### Expected
There should be zero `react-dev-overlay` in a production build. This issue is present on the latest canary

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
Binaries:
  Node: 20.11.0
  npm: 10.3.0
  Yarn: 1.22.22
  pnpm: 9.5.0
Relevant Packages:
  next: 15.0.0-canary.77 // There is a newer canary version (15.0.0-canary.85) available, please upgrade!
  eslint-config-next: 15.0.0-canary.85
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.5.4
Next.js Config:
  output: N/A
 ⚠ There is a newer canary version (15.0.0-canary.85) available, please upgrade!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Performance

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

This issue is present in all canaries from 77 and onward.

**Comment by icyJoseph** [comment]
Ah, this PR https://github.com/vercel/next.js/commit/eb23134e9b575bf26460e17280aa1d94f90528d6 introduced this line:

https://github.com/vercel/next.js/blob/eb23134e9b575bf26460e17280aa1d94f90528d6/packages/next/src/client/components/router-reducer/fetch-server-response.ts#L32

Which is how the react-dev-overlay ends up in the prod build.

I can try to make a PR...

**Comment by icyJoseph** [comment]
Although, strangely enough:

```js
    // We may navigate to a page that requires a different Webpack runtime.
    // In prod, every page will have the same Webpack runtime.
    // In dev, the Webpack runtime is minimal for each page.
    // We need to ensure the Webpack runtime is updated before executing client-side JS of the new page.
    if (process.env.NODE_ENV !== 'production' && !process.env.TURBOPACK) {
      await waitForWebpackRuntimeHotUpdate()
    }
```

This bit should've taken it out of the prod build 🤔

**Comment by sannajammeh** [comment]
> Although, strangely enough:
> 
> ```js
>     // We may navigate to a page that requires a different Webpack runtime.
>     // In prod, every page will have the same Webpack runtime.
>     // In dev, the Webpack runtime is minimal for each page.
>     // We need to ensure the Webpack runtime is updated before executing client-side JS of the new page.
>     if (process.env.NODE_ENV !== 'production' && !process.env.TURBOPACK) {
>       await waitForWebpackRuntimeHotUpdate()
>     }
> ```
> 
> This bit should've taken it out of the prod build 🤔

I assume the import is not treeshaken properly.

**Comment by icyJoseph** [comment]
Still investigating though... there wasn't that many commits between those two canary releases, and that one PR uses the react-dev-overlay... so it is likely the issue, but we need to confirm it somehow

**Comment by icyJoseph** [comment]
I ran a build, and was able to find, `waitForWebpackRuntimeHotUpdate`, on two files:

```console
.next/static/chunks/234-d6d77aeb04037f37.js
.next/server/chunks/665.js
```

If I build on canary 76... I get no results 🤔

**Comment by icyJoseph** [comment]
So, a further exploration:

```console
next-15-bundle-size on  main [!] via  v20.15.1 at 
➜ rg waitForWebpackRuntimeHotUpdate .next -l
.next/static/chunks/234-d6d77aeb04037f37.js
.next/server/chunks/665.js
next-15-bundle-size on  main [!] via  v20.15.1 at 
➜ rg '.next/static/chunks/234-d6d77aeb04037f37.js' .next -l
.next/server/pages/404.html
.next/server/app/_not-found.html
.next/server/app/index.html
```

The chunk that contains, `waitForWebpackRuntimeHotUpdate`, is referenced in some pages, such as `app/index.html`.

**Comment by icyJoseph** [comment]
And, one more update, removing that code from the given file, in `node_modules`, `next/dist/client/components/router-reducer/fetch-server-response.js`, and then building, fixes the issue, so I guess, that's a good indicator, that indeed that PR introduced this issue
