### ISSUE TITLE
Docs: Clarity on the width and height properties of the Image component

### ISSUE THREAD

**Issue by NickWoodward** [vercel/next.js#68228]
### What is the update you wish to see?

Might be a mistake on my part, but I feel like the docs are in need of a bit of clarity on the width and height attributes of the Image component?

[Here](https://nextjs.org/docs/pages/api-reference/components/image#width) they're defined as representing the rendered sizes:

> The width property represents the rendered width in pixels, so it will affect how large the image appears.

But [here](https://nextjs.org/docs/pages/building-your-application/optimizing/images#remote-images) it states that they do not:

> The width and height attributes are used to infer the correct aspect ratio of image and avoid layout shift from the image loading in. The width and height do not determine the rendered size of the image file.

Feel like it should be the latter, the intrinsic values, so that it's inline with the `<img>` tag?

### Is there any context that might help us understand?

As above

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/components/image#width

**Comment by Tim-Zj** [comment]
Hi @NickWoodward,
Thanks for pointing out the inconsistency in the documentation regarding the `width` and `height` attributes of the `Image` component. I'm currently working on a fix to clarify this in the docs. I'll keep you posted on the progress and provide a link to the PR once it's ready.
Best regards,  
Tim

**Comment by Tim-Zj** [comment]
Hi @NickWoodward,
I've updated the documentation to clarify that the `width` and `height` properties represent the intrinsic dimensions of the image, similar to the `width` and `height` attributes in the HTML `<img>` tag. These properties are used to infer the correct aspect ratio and avoid layout shift during loading, and do not determine the rendered size of the image, which is controlled by CSS.

You can find the updated documentation in this [[PR].](https://github.com/vercel/next.js/pull/68248#issue-2434013460)
Best regards,  
Tim

**Comment by Tim-Zj** [comment]
This issue is addressed in PR #68248
