### ISSUE TITLE
Server actions reset uncontrolled and break controlled forms

### ISSUE THREAD

**Issue by Arctomachine** [vercel/next.js#68232]
### Link to the code that reproduces this issue

https://github.com/Arctomachine/server-action-form-reset

### To Reproduce

Controlled component 1:
1. Enable rerender highlights in react dev tools
2. Check all checkboxes and fill input
3. Submit form
4. Checkboxes reset to unchecked, states are still true, sever console prints all checked correctly. Input keeps value
5. Submit form again without changing anything
6. Server console prints no checkboxes at all
7. Check one of checkboxes. No rerenders happen, states are unchanged, but now only this checkbox is checked.
8. Uncheck this checkbox. Component rerenders and syncs state with view. Component works normally until next submit.

Controlled component 2:
1. Enable rerender highlights in react dev tools
2. Uncheck all checkboxes and fill input
3. Submit form
4. Checkboxes reset to checked, states are still false, sever console prints no checkboxes. Input keeps value
5. Submit form again without changing anything
6. Server console prints all checkboxes checked
7. Uncheck one of checkboxes. No rerenders happen, states are unchanged, but now only this checkbox is unchecked.
8. Check this checkbox. Component rerenders and syncs state with view. Component works normally until next submit.

Uncontrolled component:
1. Check all checkboxes and fill input
2. Submit form
3. Whole form resets

### Current vs. Expected behavior

Current: form (view) resets after submit with server action. If form is controlled, all states (react) remain. Text fields retain value, checkboxes reset to their initial value and no further rerenders happen until view matches state.
Expected: keep all values in form unchanged after submit regardless of component type.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32720
  Available CPU cores: 12
Binaries:
  Node: 20.12.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.86 // Latest available version is detected (15.0.0-canary.86).
  eslint-config-next: N/A
  react: 19.0.0-rc.0
  react-dom: 19.0.0-rc.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

**Comment by chungweileong94** [comment]
Unfortunately, this is one of the breaking changes in React 19, where all uncontrolled form inputs will get reset after form submit. The proper way to handle this is to return the original submitted values from server action, then reset all the inputs manually with `defaultValue` props.

https://github.com/facebook/react/issues/29034#issuecomment-2308598414

**Comment by ztanner** [comment]
Closing this as I believe https://github.com/facebook/react/issues/29034 is the best place for this discussion and isn't actionable within Next.js. Using `onSubmit` rather than `action` as described [here](https://github.com/facebook/react/issues/29034#issuecomment-2143595195) seems like a suitable workaround if you wish to opt-out of the default React behavior.
