### ISSUE TITLE
Warning when "key" prop is after a spread operator

### ISSUE THREAD

**Issue by someden** [vercel/next.js#68277]
### Link to the code that reproduces this issue

https://github.com/someden/spread-operator-and-key

### To Reproduce

1. Start the application in development (next dev).
2. And you will see a warning in terminal and in browser console: "Each child in a list should have a unique "key" prop".

Codesandbox example: https://codesandbox.io/p/github/someden/spread-operator-and-key/main

Example of warning in terminal:

<img width="2056" alt="Screenshot 2024-07-29 at 19 08 14" src="https://github.com/user-attachments/assets/9e5d31d1-74b4-48cc-b0c6-f82d6d52d617">

Example of warning in browser console:

<img width="1448" alt="Screenshot 2024-07-29 at 19 24 14" src="https://github.com/user-attachments/assets/fc7e5baa-07f8-4087-b037-ec07cbcd40a7">

This warning appears if key prop in component comes after a spread operator and component has at least to children, like this:
```jsx
<Component {...props} key="key">
  <div>hello</div>
  <div>world</div>
</Component>
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.6
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

Also the same issue in next v14.2.1

### Which area(s) are affected? (Select all that apply)

Not sure, Script (next/script), Turbopack, SWC, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

It looks like a continuation of the issue: https://github.com/vercel/next.js/issues/55642

**Comment by someden** [comment]
@kdy1 yes, I'm using `key` after the spread operator and this causing the warning.
There is no warning if I will use `key` before the spread operator.

This will cause warning:
```
<Component {...props} key="key">
  <div>hello</div>
  <div>world</div>
</Component>
```

And this won't:
```
<Component key="key" {...props}>
  <div>hello</div>
  <div>world</div>
</Component>
```

This also won't:
```
<Component {...props} key="key">
  <div>hello</div>
</Component>
```

So, @kdy1 could you reopen this issue?

**Comment by kdy1** [comment]
No. The current behavior is correct.

**Comment by someden** [comment]
@kdy1 do you mean I should not use `key` prop after spread operator? Only before?
