### ISSUE TITLE
run next dev specify a port in .env file not working

### ISSUE THREAD

**Issue by JianJroh** [vercel/next.js#68313]
### Link to the code that reproduces this issue

https://stackblitz.com/edit/stackblitz-starters-jx5h7b?file=package.json

### To Reproduce

1. Add `PORT=4000` in .env file
2. Run `next dev`

### Current vs. Expected behavior

Current: run in default port 3000.
Expected: run in specify a port  4000.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
Binaries:
  Node: 20.13.1
  npm: N/A
  Yarn: N/A
  pnpm: 9.4.0
Relevant Packages:
  next: 14.0.3
  eslint-config-next: 14.0.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Script (next/script)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

If i do this it work.
1. run `$env:PORT=4000` in powershell
2. run `next dev`

**Comment by AliRazaDev27** [comment]
We can't set port through .env file , for detailed info.
https://nextjs.org/docs/app/api-reference/next-cli
![image](https://github.com/user-attachments/assets/b575227e-dc5d-4bf4-9e84-ce64657e6241)
