### ISSUE TITLE
Sccs compiling Turbopack issue

### ISSUE THREAD

**Issue by Rnbsov** [vercel/next.js#68311]
### Link to the code that reproduces this issue

https://github.com/Rnbsov/scss-turbopack-repruduction-example

### To Reproduce

1. Start application in development via `npm run dev`

### Current vs. Expected behavior

Expected behavior is converting scss files to css I guess. But instead it seems to add `.css` extension to `.scss` files and try to parse them as just `.css`. Not sure though

It's working with  `swcMinify: true`, but when using `--turbo` it fails

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro    
  Available memory (MB): 8044
  Available CPU cores: 4     
Binaries:
  Node: 20.15.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.91 // Latest available version is detected (15.0.0-canary.91).    
  eslint-config-next: N/A
  react: 19.0.0-rc-76002254-20240724
  react-dom: 19.0.0-rc-76002254-20240724
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@Rnbsov This may be a duplicate issue, but can confirm that this is an issue!

**Comment by samcx** [comment]
@Rnbsov The issue here is actually because there is invalid css.

```
input.defaultCheckbox::before path {
	fill: currentColor;
}

```

There cannot be a selector after the `::before`. If you remove it, it'll work. There is an issue with non-Turbopack Webpack css parser allowing this, so we'll be improving the error for this.

Let me know if that clarifies!

**Comment by Rnbsov** [comment]
Yeah, that explains everything

**Comment by samcx** [comment]
@Rnbsov Great!

I will be closing this issue in the meantime.
