### ISSUE TITLE
next build creates a `.next` folder when `output: 'export'` and `distDir`

### ISSUE THREAD

**Issue by Janpot** [vercel/next.js#68316]
### Link to the code that reproduces this issue

https://stackblitz.com/edit/stackblitz-starters-cru4sx?file=next.config.js

### To Reproduce

1. Run `rm -rf .next foo && npx next build`
2. Run `ls .next`
3. Remove `output: 'export'` from `next.config.js`
4. Run `rm -rf .next foo && npx next build`
5. Run `ls .next`

### Current vs. Expected behavior

A `.next` folder doesn't exist in both cases. `distDir` was set to `foo`. the output lives in the `foo` directory.
instead, in the export case, both a `. next` and `foo` directory are created.

This is a very minor issue, if at all.

### Provide environment information

```bash
(on stackblitz)

npx next info

    Operating System:
      Platform: linux
      Arch: x64
      Version: Ubuntu 20.04.0 LTS Tue Jul 30 2024 10:15:33 GMT+0200 (Central European Summer Time)
    Binaries:
      Node: 18.20.3
      npm: 10.2.3
      Yarn: 1.22.19
      pnpm: 8.15.6
    Relevant Packages:
      next: 13.5.1
      eslint-config-next: 13.5.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```
```


### Which area(s) are affected? (Select all that apply)

Output (export/standalone)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

_No response_

**Comment by samcx** [comment]
@Janpot On the latest canary, here is what I'm seeing.

- Without `output: export` → I see a `/foo` directory which is basically the `.next` directory
- With `output: export` → I see both a `/.next` directory and the `/foo` directory, which is the static build from `output: export`

**Comment by Janpot** [comment]
> * With output: export → I see both a `/.next` directory and the `/foo` directory, which is the static build from `output:` export

Exactly. I would expect it to only create a `/foo` directory. Not a huge problem for us, just thought it wasn't intentional.
