### ISSUE TITLE
Next/head no longer works for pages router

### ISSUE THREAD

**Issue by pearcircuitmike** [vercel/next.js#68346]
### Link to the code that reproduces this issue

https://github.com/pearcircuitmike/replicate-codex

### To Reproduce

npm run dev on the provided repo and inspect the pagesource. You will see zero meta from the metatags component rendered in the pagesource. You can check the deployed version at the public URL as well and you'll see it's not present any more there either. 

### Current vs. Expected behavior

I import a MetaTags.js component, in index.js for example...

```
import React, { useEffect, useState } from "react";
import MetaTags from "../components/MetaTags.js";
...

export default function Home() {
  const [isMobile] = useMediaQuery("(max-width: 480px)");
  ... a bunch more...

 ...

  return (
    <>
      <MetaTags
        title={"Your Roadmap to the AI Revolution - AIModels.fyi"}
        description={
          "AImodels.fyi scans repos, journals, and social media to bring you the ML breakthroughs that actually matter, so you spend less time reading and more time building."
        }
      />
     ...rest of component
     </>
}
```

I expect that when I view the pagesource, the meta would be there. It is not. This also means no OG images generated for social sharing, etc. ... NOTE that the meta IS there when you inspect the console. 

This is following the *exact* implementation specified in the docs which no longer works: https://nextjs.org/docs/pages/api-reference/components/head

In /components/MetaTags, for reference:

```import Head from "next/head";

export default function MetaTags({
  title = "AI Models",
  description = "Explore the world of AI Models.",
  socialPreviewImage = "",
  socialPreviewTitle = "",
  socialPreviewSubtitle = "",
}) {
  // Access the environment variable; it returns a string
  const baseUrl = process.env.NEXT_PUBLIC_SITE_BASE_URL;

  // Construct the URL with encoded parameters for dynamic social media images
  const ogImageUrl = `${baseUrl}/api/og?image=${encodeURIComponent(
    socialPreviewImage
  )}&title=${encodeURIComponent(
    socialPreviewTitle
  )}&subtitle=${encodeURIComponent(socialPreviewSubtitle)}`;

  return (
    <Head>
      <meta httpEquiv="content-language" content="en" />
      <title>{title}</title>
      <meta name="description" content="HELLO" />
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={baseUrl} />
      <meta property="og:image" content={ogImageUrl} />
      <meta property="og:type" content="website" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta property="twitter:description" content={description} />
      <meta property="twitter:image" content={ogImageUrl} />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:25 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8110
  Available memory (MB): 24576
  Available CPU cores: 8
Binaries:
  Node: 21.7.1
  npm: 10.5.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.4 // There is a newer version (14.2.5) available, upgrade recommended! 
  eslint-config-next: 14.2.4
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 4.9.5
Next.js Config:
  output: N/A
 ⚠ There is a newer version (14.2.5) available, upgrade recommended! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

This app is hosted on Vercel, and this issue wasn't present and Head was working until 4-6 weeks ago.

**Comment by pearcircuitmike** [comment]
You'll notice a response to this stackoverflow question is based on a similar failure: https://stackoverflow.com/questions/57794743/head-tags-doesnt-change-in-dynamic-page-with-next-head

**Comment by icyJoseph** [comment]
Hi,

You have this bit:

```js
  if (loading) {
    return <div>Loading...</div>; // Or your custom loading component
  }
```

That loading flag comes from:

```js
  const { user, loading } = useAuth();
```

And the `useAuth` hook return this _initial_ state:

```js
  const [state, setState] = useState({
    user: null,
    loading: true,
    firstTimeUser: false,
    hasActiveSubscription: false,
  });
```

And the loading flag, as expected, changes only through user interaction, or useEffect.

This is important, because it is a pitfall that many run into. 

> I wrote PR that updating the docs to mention this pitfall, but I haven't had time to keep up with it, https://github.com/vercel/next.js/pull/63532

So what is going on? During the SSR pass, your custom App, in `_app`, hits the `if (loading) {}` branch, and just renders a div with inner text `Loading`.

> If you open your site, with JavaScript disabled, you'll see the Loading text. 
> You can also do view-source:https://your-site-url.domain, and will see Loading text there

The problem is then, that this return statement, never happens! So your page `Component` is not rendered, and that's why the MetaTags component rendering output is nowhere to be seen!

```js
// this never happens on the server side render pass
  return (
    <RouteGuard>
      {/* other components */}
                  <Component {...pageProps} /> 
```

One way to try and fix this is to pass the `loading` prop to your page (or consume it through context from `useAuth`), and then, render what can be rendered while we are at the initial state, and then have a branch that returns `null`, and instead of having `_app` branch out like that, overlay the UI with the `Loading...` text. 

It is really up to you how you fix this issue, but I hope it is clear that it is not a Next.js issue, rather, it is caused by your code.

**Comment by samcx** [comment]
@icyJoseph Thanks for responding! I'll look to have your <picture data-single-emoji=":docs:" title=":docs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/docs/172e1b9b7d137b8a.png" alt=":docs:" align="absmiddle"></picture> <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture> reviewed as well <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>
