### ISSUE TITLE
Metadata is not rendered in head element

### ISSUE THREAD

**Issue by Merynek** [vercel/next.js#68350]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/sweet-rumple-cfk56m
### To Reproduce

Build or run dev task to build next.js project
in root layout.
```
import Head from "next/head";

export const metadata: Metadata = {
  title: "test",
  other: {
    "agd-partner-manual-verification": "",
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <Head>
        <meta name="agd-partner-manual-verification" />
      </Head>
      <body>{children}</body>
    </html>
  );
}

```

### Current vs. Expected behavior

Currently Metatag is not rendered in head.

### Provide environment information

```bash
"next": "15.0.0-canary.94",
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Other (Deployed)

**Comment by icyJoseph** [comment]
Hi,

```js
import Head from "next/head";
```

`next/head` is a Pages Router API, it is not supported in App Router. 

- https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#step-3-migrating-nexthead

**Comment by Merynek** [comment]
> Hi,
> 
> ```js
> import Head from "next/head";
> ```
> 
> `next/head` is a Pages Router API, it is not supported in App Router.
> 
> * https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#step-3-migrating-nexthead

Oh ok, but when I have exported metadata its same problem.

**Comment by icyJoseph** [comment]
I see it, view-source:https://fnc5rz-3000.csb.app/

```html
<meta name="agd-partner-manual-verification"/>
```

When doing:

```jsx
export default function RootLayout({ children }) {
  return (
    <html>
        <meta name="agd-partner-manual-verification" />
      <body>{children}</body>
    </html>
  );
}
```

I think the problem, when using the metadata object, might be that you have it as an empty string value, try with:

```jsx
export const metadata: Metadata = {
  title: "test",
  other: {
    "agd-partner-manual-verification": "abc",
  },
};
```

**Comment by icyJoseph** [comment]
Possibly fixed by https://github.com/vercel/next.js/pull/68262, I think ~~

**Comment by samcx** [comment]
@Merynek I'll be closing this issue for now. Let us know if this is working for you on the latest canary, which includes the possible fix shared by @icyJoseph!
