### ISSUE TITLE
Middleware return NextResponse.error() unexpectedly triggers 404 instead of 500 error

### ISSUE THREAD

**Issue by jooa7878** [vercel/next.js#68383]
### Link to the code that reproduces this issue

https://github.com/jooa7878/nextjs_middleware_to_error_boundary_repo/

### To Reproduce

install and run `next dev`

### Current vs. Expected behavior

**Expected Behavior**
When the API call fails and `NextResponse.error()` is called in the catch block, it should trigger a 500 error and render the `error.tsx` component.

**Actual Behavior**
Instead of a 500 error, a 404 error is triggered, and the `not-found.tsx` component is rendered.

**Code Example**
```typescript
import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export async function middleware(request: NextRequest) {
  try {
    const res = await fetch('https://api.example.com/data')
    if (!res.ok) throw new Error('API call failed')
    // Process response
  } catch (error) {
    // Expecting this to trigger a 500 error
    return NextResponse.error()
  }
}
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I've tried various methods such as `NextResponse.json({error}, {status:500})`, but none of them resulted in the error being caught by `error.tsx` (error-boundary).
* When using `NextResponse.json({error}, {status:500})`, it only displays the error message as white text on a black screen, without invoking the error boundary.

To work around this issue, I've implemented the following tricky solution:
1. In the middleware, instead of using `NextResponse.error()`, I'm using:
   ```typescript
   return NextResponse.rewrite(new URL('/error', request.url))
   ```
2. I've created an app/error/page.tsx file with the following content:
    ```typescript
    'use client'

    import { useEffect } from 'react'

    export default function ErrorPage() {
      useEffect(() => {
        throw new Error('This is error from middleware')
      }, [])

      return null
    }

    ```
3. The error thrown in error/page.tsx is then caught by error.tsx.
4. While this method works, it has a significant drawback: it doesn't allow for detailed logging of the original error that occurred in the middleware.

### Questions

* Is this the intended behavior for NextResponse.error() in middleware?
* If not, is there a workaround to force a 500 error and use error.tsx instead of not-found.tsx?
* Is there documentation that explains this behavior that I might have missed?
* Is the behavior of NextResponse.error() triggering a 404 instead of a 500 related to the runtime environment of the middleware?

Thank you for your time and assistance in resolving this issue.

**Comment by samcx** [comment]
@jooa7878 Thank you for submitting an issue!

> Is this the intended behavior for NextResponse.error() in middleware?
I don't believe that is the use case of for `NextResponse.error()`. This is actually just an extension of `Response.error()`, which to be fair, is obscure in it's use case → https://developer.mozilla.org/en-US/docs/Web/API/Response/error_static.

>Is the behavior of NextResponse.error() triggering a 404 instead of a 500 related to the runtime environment of the middleware?
To be fair, I'm not sure why it's doing this, but I don't recommend using `NextResponse.error()` for error handling. I recommending using `NextResponse.redirect()` to redirect to a different page, such as if you are no longer authenticated, redirect to `/login` (or NextResponse.json()).

I think there are some confusion with Error Boundaries. Error Boundaries are designed to catch errors in the context of the Server Components, Server Actions. Middleware lives in a different context (at the Edge), so it also not possible to send network errors down to an Error Boundary.

Let me know if that clarifies things!

**Comment by jooa7878** [comment]
@samcx,
Thank you for your detailed response. 👍🏻

I was considering using NextResponse.error() to track errors that occur when calling the authentication verification API within the middleware. 

Since it’s not possible to call a `logger`(customized object which in /utils, importing `winston` npm package) within the catch block of middleware running in the edge runtime, I just thought that, for logging, redirecting to an `error boundary (error.tsx)` is the proper solution and might help centralize the logging process.

Thank you again for your response. I will close this issue.
