### ISSUE TITLE
Google Tag Manager - Failed to execute 'getValue' on 'CookieDeprecationLabel': Illegal invocation

### ISSUE THREAD

**Issue by mikeyamato** [vercel/next.js#68380]
### Link to the code that reproduces this issue

https://github.com/mikeyamato/gtm-console-error

### To Reproduce

Apply `GoogleTagManager` just like how the [example is shown](https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-tag-manager) and paste in a Google tag id. 

### Current vs. Expected behavior

Running the code will throw the following error:
<img width="688" alt="Screenshot 2024-07-31 at 19 13 53" src="https://github.com/user-attachments/assets/ed470316-f4c9-4028-8706-2a7207606b8b">

The link in the error message takes me here:
<img width="696" alt="Screenshot 2024-07-31 at 19 14 00" src="https://github.com/user-attachments/assets/6a2e4ddb-c474-4d72-81e3-60b2b1ae048b">

I expect no error to be thrown in the dev console. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
  Available memory (MB): 32768
  Available CPU cores: 16
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 3.4.1
  pnpm: 7.30.1
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Performance, Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local), Vercel (Deployed)

### Additional context

The funny thing is that events are correctly being recorded by Google Analytics even while an error is being thrown in the console. This goes for all environments, dev & prod.  

Additionally, no error is thrown if a fake GTM tag id is used (ie. using `GTM-XYZ` vs `GTM-MS5ZZXSS`)

**Comment by benStre** [comment]
I don't think this is a next.js issue - I get the same error when I inject the google tag manager with a simple script tag. I think something has gone wrong here on the Google side.

**Comment by jigius** [comment]
there is the [complain]( https://support.google.com/tagmanager/thread/288419928/error-failed-to-execute-getvalue-on-cookiedeprecationlabel?hl=en) about the issue

**Comment by mikeyamato** [comment]
Since this isn't a Next.js issue I will be closing this ticket.

**Comment by znayer** [comment]
Same issue here, just popped up today

**Comment by fatihyuksell** [comment]
> I don't think this is a next.js issue - I get the same error when I inject the google tag manager with a simple script tag. I think something has gone wrong here on the Google side.

I also experience this problem when I buy flutter web build. The problem occurs independently with any framework. I think it is caused by Google like other comments.

**Comment by Kamit6337** [comment]
This issue comes only in production in next js and not in development.

In development, when I try to use google oauth, it works fine. But as soon, I click on login with Google, it shows this error in url "https://vwflex.vercel.app/api/auth/error"

**Comment by yugal1107** [comment]
This issue is occuring due to usage of google analystics in web application as it is using third party cookies. 
In my PC , this issue is occuring in chrome but not in brave.
It's not vercel issue.
