### ISSUE TITLE
`next/font` no longer works with "Inter" and "slnt" axes enabled

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next.js#68395]
### Link to the code that reproduces this issue

https://github.com/stefanprobst/issue-next-fonts-inter-slnt

### To Reproduce

clone repo, install deps, run `pnpm run build`.

see error message:

```
Failed to fetch `Inter` from Google Fonts.}
Failed to fetch font `Inter`.
URL: https://fonts.googleapis.com/css2?family=Inter:slnt,wght@-10..0,100..900&display=swap

Please check if the network is available.

Retrying 1/3...
Failed to fetch font `Inter`.
URL: https://fonts.googleapis.com/css2?family=Inter:slnt,wght@-10..0,100..900&display=swap

Please check if the network is available.

Retrying 2/3...
Failed to fetch font `Inter`.
URL: https://fonts.googleapis.com/css2?family=Inter:slnt,wght@-10..0,100..900&display=swap

Please check if the network is available.

Retrying 3/3...
Error [NextFontError]: Failed to fetch font `Inter`.
URL: https://fonts.googleapis.com/css2?family=Inter:slnt,wght@-10..0,100..900&display=swap

Please check if the network is available.
```

### Current vs. Expected behavior

font download should work (as it did until recently)

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2
  Available memory (MB): 15893
  Available CPU cores: 4
Binaries:
  Node: 20.16.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Font (next/font)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

see https://github.com/google/fonts/issues/7985 for upstream changes

when downloading Inter directly from google, the embed link is: 

```
https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap
```

while `next/font` tries the following url, which now fails:

```
https://fonts.googleapis.com/css2?family=Inter:slnt,wght@-10..0,100..900&display=swap
```

**Comment by CypherpunkSamurai** [comment]
I'm having the same error on node 22 and node lts (20) versions. any workaround would be appreciated.

For the time being i'm downgrading.

**Comment by ljs19923** [comment]
Same error

**Comment by peguerosdc** [comment]
I am facing a similar error. Not sure if it's related, but it also started to happen unexpectedly:

```
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap: incorrect header check

Retrying 1/3...
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap: incorrect header check

Retrying 2/3...
Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap: incorrect header check

Retrying 3/3...
FetchError: Invalid response body while trying to fetch https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap: incorrect header check
    at Gunzip.<anonymous> (/Users/user/dev/mindora/node_modules/next/dist/compiled/node-fetch/index.js:1:53082)
    at Gunzip.emit (node:events:532:35)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'Z_DATA_ERROR',
  code: 'Z_DATA_ERROR'
}
 ⨯ Failed to download `Manrope` from Google Fonts. Using fallback font instead.
```

It happens with `Manrope` and `Inter`.

**Comment by CypherpunkSamurai** [comment]
The google font urls are broken. When requesting multiple font's it's giving timeout errors.

It is not a network issue as online IDEs also have this error.

**Comment by stefanprobst** [comment]
this seems to also make a next.js test fail, see https://github.com/vercel/next.js/pull/68475#issuecomment-2266291641

```
Snapshot name: `getFontAxes errors Invalid axes value 1`

- Snapshot  - 1
+ Received  + 1

  Invalid axes value for font `Inter`, expected an array of axes.
- Available axes: `slnt`
+ Available axes: `opsz`
```

**Comment by CypherpunkSamurai** [comment]
did google update their api again? or did next push a breaking change?

**Comment by samcx** [comment]
@stefanprobst Taking a look at this! I think we just need to update our test so https://github.com/vercel/next.js/pull/68639 merges, and the correct embed URL is used.

**Comment by samcx** [comment]
Interesting, the Google font data still doesn't include `ital`, but it didn't include `opsz` → https://github.com/vercel/next.js/pull/68639/files. I'll keep this issue open until this changes!

In the meantime, a new canary release should come out very soon with the update.

**Comment by stefanprobst** [comment]
@samcx if i understand the upstream change correctly, there is no `ital` *axis*, but two separate files, one for `font-style: normal` and one for `font-style: italic`. see: https://github.com/google/fonts/issues/2386#issuecomment-1564659606

**Comment by stefanprobst** [comment]
also, will the updated font data be backported to next.js 14.x?

**Comment by mlmetzner** [comment]
I am having similiar issues with Roboto.

**Comment by samcx** [comment]
@mlmetzner Try [v15.0.0-canary.110](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.110)!

@stefanprobst Yes, I added to the queue for 14.2.6. No exact date for when that's released, but hopefully you can start using the canary in the meantime!

I'll be closing this issue in the meantime. 🙇🏼

**Comment by ljs19923** [comment]
@samcx Im not sure to understand what's the current solution?

Thank you

I was using, 

import { Inter } from "next/font/google
const inter = Inter({ subsets: ["latin"], axes: ["slnt"] });


 <style jsx global>{`
                      :root {
                        --font-inter: ${inter.style.fontFamily};
                      }
                    `}</style>

**Comment by samcx** [comment]
@ljs19923 here's the updated `axes` value.

![CleanShot 2024-08-19 at 14 41 27@2x](https://github.com/user-attachments/assets/81e68c79-c4e8-4735-8351-b478129b68bb)
