### ISSUE TITLE
empty environment variables handled different between server and client

### ISSUE THREAD

**Issue by david-keefe** [vercel/next.js#68401]
Empty environment variables (or "") are not consistent between server and client.

Zod throws a validation error on the client after validating properly on the server.

### Link to the code that reproduces this issue

https://github.com/david-keefe/nextjs-env-var-issue

### To Reproduce

1. Run `pnpm build` and see a successful build
2. Run `pnpm start` and see an application error and a Zod validation error in browser console

Note: `pnpm dev` also validates on the server and errors in the browser.

### Current vs. Expected behavior

I would expect server and client handling of the empty environment variable to be the same.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Oct  4 21:26:23 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 9.6.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Environment Variables

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

- Upgrading to Next.js v15 canary results in the expected behaviour
- Downgrading to Next.js v14.1.4 results in the expected behaviour
- Adding a non-empty string in `.env` works as expected

**Comment by ijjk** [comment]
Closing as fixed by https://github.com/vercel/next.js/pull/65248 which will be included in a release soon
