### ISSUE TITLE
Use of cryptographically weak pseudo-random number generator

### ISSUE THREAD

**Issue by monicavis** [vercel/next.js#68433]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/patient-cdn-spcszn

### To Reproduce

1 - Ran **Semgrep** scanning for vulnerability.

2 - getting this issue mentioned below in the node module for nextJs

This rule identifies use of cryptographically weak random number generators.\nUsing cryptographically weak random number generators like crypto.pseudoRandomBytes() \nand Math.random() for security-critical tasks can expose systems to significant \nvulnerabilities. Attackers might predict the generated random numbers, compromising \nthe integrity and confidentiality of cryptographic operations. This could lead to \nbreaches where sensitive data is accessed or manipulated, authentication mechanisms \nare bypassed, or secure communications are intercepted, ultimately undermining the \nsecurity of the entire system or application.\n\nMitigation strategy:\nReplace the use of these cryptographically weak random number generators with \ncrypto.randomBytes(), a method provided by Node.js's crypto module that \ngenerates cryptographically secure random numbers. This method should be used \nfor all operations requiring secure randomness, such as generating keys, tokens, \nor any cryptographic material.\n\nSecure Code Example:\n\nconst crypto = require('crypto');\nconst secureBytes = crypto.randomBytes(256);\nconsole.log(`Secure random bytes: ${secureBytes.toString('hex')}`);\n\n

### Current vs. Expected behavior

Current - Vulnerability in node module

Expected - Vulnerability should not come after scanning by Semgrep

### Provide environment information

```bash
Operating system :Windows 11
Binaries :
Node : 20.11.1
npm : 10.2.4
Yarn : 1.22.19

Relevant packages
next : 14.2.4
eslint-config-next : 14.1.0
react :18
react-dom:18
typescript : 5
```

### Which area(s) are affected? (Select all that apply)

Webpack

### Which stage(s) are affected? (Select all that apply)

next build (local), Other (Deployed)

### Additional context

After the yarn build, it becomes vulnerable in chunks and points to the nextJS packages.

I found Math.random() in the following

/node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js
/node_modules/next/dist/client/components/react-dev-overlay/pages/hot-reloader-client.js
/node_modules/next/dist/client/index.js
/node_modules/next/dist/compiled/web-vitals/web-vitals.js
/node_modules/next/dist/shared/lib/router/router.js

**Comment by icyJoseph** [comment]
Interesting finds. 

I think, while going through the list you provided, and the uses of Math.random provided, it is important to keep this in mind:

>  for security-critical tasks can expose systems to significant \nvulnerabilities

So now, let's see what's happening

> /node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js
> /node_modules/next/dist/client/components/react-dev-overlay/pages/hot-reloader-client.js

These are used during `next dev` time, and are not packaged onto the production build. Both of them are trying to create an opaque unique identifier for the overlay, on the client.

```js
let __nextDevClientId = Math.round(Math.random() * 100 + Date.now()) // app
// pages/hot-reloader-client.js
window.__nextDevClientId = Math.round(Math.random() * 100 + Date.now()) // pages
``` 



> /node_modules/next/dist/client/index.js
> /node_modules/next/dist/compiled/web-vitals/web-vitals.js
> /node_modules/next/dist/shared/lib/router/router.js

**Comment by icyJoseph** [comment]
Interesting finds. 

I think, while going through the list you provided, and the uses of Math.random provided, it is important to keep this in mind:

>  for security-critical tasks can expose systems to significant \nvulnerabilities

So now, let's see what's happening

> /node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js
> /node_modules/next/dist/client/components/react-dev-overlay/pages/hot-reloader-client.js

These are only used during dev time, not in production builds, so it should be ok... most likely not the cause of the analysis failure.

Both of them are trying to create an opaque unique identifier for the overlay, on the client.

```js
let __nextDevClientId = Math.round(Math.random() * 100 + Date.now()) // app
// pages/hot-reloader-client.js
window.__nextDevClientId = Math.round(Math.random() * 100 + Date.now()) // pages
``` 

> /node_modules/next/dist/client/index.js

I don't know if this one is potentially problematic, it is just trying to give each performance entry a unique identifier. It doesn't seem to be sensitive, nor secret, but could definitely be patched for getRandomValues.

https://github.com/vercel/next.js/blob/99a92826f6c01d9064a828feba96a617f46803f9/packages/next/src/client/index.tsx#L858-L860

> /node_modules/next/dist/compiled/web-vitals/web-vitals.js

Upstream issue in the web-vitals package. Has to be fixed here:

https://github.com/GoogleChrome/web-vitals/blob/dc0ee2b1560533e4e2a38b270d316764fe0775de/src/lib/generateUniqueID.ts#L22-L24

Once it is fixed there, Next.js has to update/re-add it into the compiled dependencies.

> /node_modules/next/dist/shared/lib/router/router.js

A bit unsure about this one, maybe getRandomValues should be used. Can't think of a way that an attacker could use this to abuse the router, or other parts. It just generates a pseudo-unique identifier for each entry in the history. 

https://github.com/vercel/next.js/blob/99a92826f6c01d9064a828feba96a617f46803f9/packages/next/src/shared/lib/router/router.ts#L613C1-L615

**Comment by monicavis** [comment]
Hi, @icyJoseph got this issue when we ran **semgrep** scan for vulnerability.

**Comment by samcx** [comment]
> These are only used during dev time, not in production builds, so it should be ok... most likely not the cause of the analysis failure.

Can confirm that this is only used during dev, so there is no security vulnerability going on here. We do welcome a PR for this though! In the meantime, I will close this PR since there is no real security vulnerability going on.
