### ISSUE TITLE
Strange behavior of anchor links

### ISSUE THREAD

**Issue by MrOxMasTer** [vercel/next.js#68545]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/next15-anchor-link-698s83

### To Reproduce

1. Open the "open" link
2. To understand that the menu does not open
3. Restart the page
4. See the open menu and the "close" link
5. Try to close using the "close" link
6. To understand that it does not close again and try to reload the page
7. To understand that the menu has closed and the "close" button is missing

Normal transitions work on headers for example, but together with target in css, for some reason so laggy and dumb. Something with caching, but it's strange even for caching

### Current vs. Expected behavior

Current: The menu does not open using the link
Expected behavior: So that everything opens on time and doesn't lag.

### Provide environment information

```bash
Available CPU cores: 2
Binaries:
  Node: 20.12.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.15.6
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 15.0.0-rc.0
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Possible solutions to this problem:

Disable javascript on the client
Replacing the Link component with a regular a tag
But with this variation, then when the Link component is pressed after a, the menu does not close (although maybe the problem here is that I don't fully understand how target works).

**Comment by AsadSaleh** [comment]
I think you should use:
```<Link href="/menu">Open</Link>```

Instead of:
```<Link href={"#menu"}>Open</Link>```

This topics is covered in the Next.js official beginner guide. I really recommend you to read it. https://nextjs.org/learn.

**Comment by AsadSaleh** [comment]
I think this is not the problem of Next.js itself. 

I recommend @MrOxMasTer to close this issue. Instead, you can utilize tools like ChatGPT / Claude AI to help you generate a correct code for this.

**Comment by MrOxMasTer** [comment]
> For example:
> 
> ```
> const [open, setOpen] = useState(false);


I was interested in building a more fault-tolerant system, rather than using a banal option in the form of useState, which does not work with js disabled...

**Comment by AsadSaleh** [comment]
I see.

I hope you find your answer.

**Comment by ztanner** [comment]
Hi @MrOxMasTer --

This is an unfortunate side effect of the CSS `target:` pseudoselector not working well with single page apps that make use of the history API (`window.history.pushState` / `window.history.replaceState`) to handle navigations, rather than doing full document requests via a regular anchor link (`<a href="...">...</a>`).

For reference:
- https://github.com/whatwg/html/issues/639#issuecomment-1030914480

There's not much we can do on the Next.js side without potentially breaking a lot more common cases.

**Comment by MrOxMasTer** [comment]
> This is an unfortunate side effect of the CSS `target:` pseudoselector not working well with single page apps that make use of the history API (`window.history.pushState` / `window.history.replaceState`) to handle navigations, rather than doing full document requests via a regular anchor link (`<a href="...">...</a>`).

So the `Link` component does not use the `a` tag internally, but the `window.history` tag? How does it continue to work with js disabled?

**Comment by ztanner** [comment]
> So the `Link` component does not use the `a` tag internally, but the `window.history` tag? How does it continue to work with js disabled?

It renders an anchor tag. If JavaScript is disabled, it will behave as a regular anchor link. When JavaScript is enabled, the app is progressively enhanced to instead use `window.history` APIs, to avoid needing to do a full document fetch when navigating and unlock other framework features.
