### ISSUE TITLE
svg with fragment not support when use --turbo option

### ISSUE THREAD

**Issue by hhniao** [vercel/next.js#68575]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/lingering-glitter-zflv69

### To Reproduce

1. update package.json then is work
```
// it is work 
"scripts": {
    "dev": "next dev",
  },
// it is not work
"scripts": {
    "dev": "next dev --turbo",
  },
```
2. or update node_modules/slick-carousel/slick/slick-theme.css 
```
-- url('./fonts/slick.svg#slick')
++ url('./fonts/slick.svg') 
```
so it is mean turbo not support *.svg#fragment?

### Current vs. Expected behavior
![image](https://github.com/user-attachments/assets/375e366a-8d55-4dd1-bcc2-c4a06d0db236)
throw error
```
Failed to compile

Next.js (14.2.4) out of date [(learn more)](https://nextjs.org/docs/messages/version-staleness) (turbo)
./node_modules/.pnpm/slick-carousel@1.8.1_jquery@3.7.1/node_modules/slick-carousel/slick/slick-theme.css:17:159
Module not found: Can't resolve './fonts/slick.svg#slick'
  15 |     src: url('./fonts/slick.eot');
  16 |     src: url('./fonts/slick.eot?#iefix') format('embedded-opentype'), url('./fonts/slick.woff') format('woff'), url('./fonts/slick.ttf') format('truetype'), url('./fonts/slick.svg#slick') format('svg');
> 17 | }
     |  ^
  18 | /* Arrows */
  19 | .slick-prev,
  20 | .slick-next

https://nextjs.org/docs/messages/module-not-found
```

expect work with *.svg#fragment

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.0-canary.103 // Latest available version is detected (15.0.0-canary.103).
  eslint-config-next: N/A
  react: 19.0.0-beta-04b058868c-20240508
  react-dom: 19.0.0-beta-04b058868c-20240508
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context
how can i to do before you fix it?
_No response_

**Comment by samcx** [comment]
@hhniao Can you try the latest canary? I do not see an error with `next dev`.

**Comment by timneutkens** [comment]
This has indeed been fixed already @samcx  👍

**Comment by hhniao** [comment]
@samcx @timneutkens  it is error with `next dev --turbo`

**Comment by samcx** [comment]
@hhniao Are you testing on the latest canary?
