### ISSUE TITLE
Dynamic routes slug value not accessible in sitemap file

### ISSUE THREAD

**Issue by sangeethkumarsg** [vercel/next.js#68610]
### Link to the code that reproduces this issue

https://github.com/sangeethkumarsg/next-dynamic-route-issue-sitemap-reproduction

### To Reproduce

1. Start the application in `npm run dev`
2. Navigate to the url : `http://localhost:3000/sitemaps/1/category/sitemap.xml`
3. You can see page is showing as 500 error
4. In server console, you can see that the dynamic route param is undefined.

### Current vs. Expected behavior

Ideally the dynamic path variable should be accessible inside the page. Here the parameter is showing as undefined. It is working if the file name is page.tsx, but not working for sitemap.ts file.
I want to create a siemap with `/sitemaps/1/category.xml`. If not that path then `/sitemaps/1/category/sitemap.xml` should also be fine. But my dynamic parameter is not showing. Attaching screenshots:
<img width="1351" alt="Screenshot 2024-08-07 at 12 26 27 PM" src="https://github.com/user-attachments/assets/c43dd218-f8ef-466a-aabc-804fa9461aa7">
<img width="1727" alt="Screenshot 2024-08-07 at 12 27 01 PM" src="https://github.com/user-attachments/assets/baccc355-975c-4f8a-855e-63682a80427b">
<img width="1035" alt="Screenshot 2024-08-07 at 12 28 03 PM" src="https://github.com/user-attachments/assets/6c3b429b-b1a8-41bb-8236-51d2e8ccd9bb">

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.106 // Latest available version is detected (15.0.0-canary.106).
  eslint-config-next: N/A
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

I tested the application in my local with `npm run dev` and `npm run build && npm start` as well. Both same result in my local.

**Comment by samcx** [comment]
@sangeethkumarsg Thank you for submitting an issue—taking a look!
