### ISSUE TITLE
Not found `icon` and `apple-icon` with slots from canary.107

### ISSUE THREAD

**Issue by Marukome0743** [vercel/next.js#68650]
### Link to the code that reproduces this issue

https://github.com/Marukome0743/not-found-icons

### To Reproduce

1. Run `create-next-app@canary`
2. Add `icon` and `apple-icon` images to app folder
3. Make [slots folder](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#slots) like `@modal`
4. Run `next dev`
5. Check `<head>` tag components and only show `favicon.ico`

### Current
![スクリーンショット 2024-08-08 142345](https://github.com/user-attachments/assets/b22cb4c2-3a25-420e-9878-92e0ec5a420a)

### Expected
![スクリーンショット 2024-08-08 142505](https://github.com/user-attachments/assets/3dffe345-61d8-4627-ab37-18562ac9b46c)

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sat Jun 29 07:01:04 UTC 2024
  Available memory (MB): 15881
  Available CPU cores: 8
Binaries:
  Node: 22.5.1
  npm: 10.8.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.108 // Latest available version is detected (15.0.0-canary.108).
  eslint-config-next: N/A
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This issue has happend since [Fix favicon merging with customized icons](https://github.com/vercel/next.js/pull/67982) commit.

The all icons appear unless [slots](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#slots) exist.

**Comment by samcx** [comment]
@Marukome0743 Thank you for submitting an issue!

Can confirm that PR caused this regression. Our team will be taking a look!
