### ISSUE TITLE
Modal stays there even when navigating away

### ISSUE THREAD

**Issue by patrick91** [vercel/next.js#68687]
### Link to the code that reproduces this issue

https://github.com/patrick91/modal-slots-next-js

### To Reproduce

Start the app and then click the links, here's a video too:

https://github.com/user-attachments/assets/1cd57eb4-eb4e-416f-baa2-83c96f72eef9

### Current vs. Expected behavior

I expect the modal to go away when clicking the link (or using router.push)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031
  Available memory (MB): 36864
  Available CPU cores: 14
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.22
  pnpm: 8.15.5
Relevant Packages:
  next: 15.0.0-canary.109 // Latest available version is detected (15.0.0-canary.109).
  eslint-config-next: N/A
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation, Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

This seems to be same as https://github.com/vercel/next.js/issues/49662 which is marked as fixed, but I don't think that's the case since I was able to reproduce the issue

**Comment by ztanner** [comment]
Hi -- please check out the parallel route docs on [closing a modal](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#closing-the-modal) as I believe it should clarify how to implement the behavior you're describing.
