### ISSUE TITLE
eslint-plugin-next → fast-glob only matching files

### ISSUE THREAD

**Issue by yunsii** [vercel/next.js#68752]
### Link to the code that reproduces this issue

https://github.com/mrmlnc/fast-glob/blob/da648078ae87bce81fcd42e64d5b2b1360c47b09/src/settings.ts#L182-L183

### To Reproduce

With the same next rootDir config, it will print the warning message after I upgrade @next/eslint-plugin-next from ^14.2.4 to 15.0.0-canary.111:

> Pages directory cannot be found at . If using a custom path, please configure with the `no-html-link-for-pages` rule in your eslint config file.

After my deep investigation, The PR https://github.com/vercel/next.js/pull/67261 try to replace glob with fast-glob is incompatible. CC @SukkaW 

### Current vs. Expected behavior

Context rootDir is invalid now

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
Binaries:
  Node: 22.6.0
  npm: 10.8.2
  Yarn: 1.22.10
  pnpm: 8.6.10
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.0.0
  react-dom: 18.0.0
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by icyJoseph** [comment]
Do you have a small reproduction repository? or configuration example? so that we can directly test on the getRootDirs functions?

**Comment by yunsii** [comment]
I just encounter this issue by developing my package when I update eslint-plugin-next to v5.1.0-beta-26f2496093-20240514

You can reproduct it directly by call `processRootDir` function https://github.com/vercel/next.js/blob/939251bf65633c6b330bdcd6476e651bbc16efa2/packages/eslint-plugin-next/src/utils/get-root-dirs.ts#L7-L11

Because fast-glob only match files by default, so call `processRootDir` with any valid directory will get empty array result. I think the simple fix is:

```diff
const processRootDir = (rootDir: string): string[] => {
-  // Ensures we only match folders.
-  if (!rootDir.endsWith('/')) rootDir += '/'
-  return globSync(rootDir)
+  return globSync(rootDir, { onlyDirectories: true })
}
```

**Comment by SukkaW** [comment]
> Because fast-glob only match files by default, so call `processRootDir` with any valid directory will get empty array result. I think the simple fix is:
> 
> ```diff
> const processRootDir = (rootDir: string): string[] => {
> -  // Ensures we only match folders.
> -  if (!rootDir.endsWith('/')) rootDir += '/'
> -  return globSync(rootDir)
> +  return globSync(rootDir, { onlyDirectories: true })
> }
> ```

Nice, you can submit a PR!

**Comment by yunsii** [comment]
> you can submit a PR!

I just want to do so before, but there is only 40-minute video on how to contribute, even no ducument completely, so I give up 😂

I think it should be easy to fork from canary branch, submit a commit and create a PR directly?

**Comment by icyJoseph** [comment]
> > you can submit a PR!
> 
> I just want to do so before, but there is only 40-minute video on how to contribute, even no ducument completely, so I give up 😂
> 
> I think it should be easy to fork from canary branch, submit a commit and create a PR directly?


Mmm 🤔 did you search the repository? 

- https://github.com/vercel/next.js/blob/canary/contributing/core/developing-using-local-app.md#set-as-a-local-dependency-in-packagejson

And yeah, fork the repository to your account, clone that to your dev machine, make a branch from canary, and push that branch, with your changes, then make a PR from your branch to next.js' canary.


Make sure to add a test as well!

**Comment by yunsii** [comment]
Ok, I'm working on it.

**Comment by yunsii** [comment]
Draft PR https://github.com/vercel/next.js/pull/68773

It's so strange, the new test case should not pass, I will investigate it later 😅

**Comment by samcx** [comment]
@yunsii Re-running the CI in the PR so you can check if your test is passing.
