### ISSUE TITLE
Strange multi-zone pattern（奇怪的多区域模式）

### ISSUE THREAD

**Issue by lanmingle** [vercel/next.js#68753]
### Link to the code that reproduces this issue

https://github.com/lanmingle/nextjs-multi-zones-issue-report

### To Reproduce

enable next 14.2.5 version

1. cd demo1
npm run dev
2. cd demo2
npm run dev
3. open your browser and click Navigation（打开浏览器访问，点击导航）
4. view the results of the navigation（查看导航的结果）
5. when using client mode, navigation becomes uncontrollable（当使用客户端模式时，导航变得不可控）
6. build production and run time, and everything turns out weird（构建生产与运行时，一切结果都变得奇怪）

next 14.2.5 version: is cache demo2 page (use server)

toggle next 15.0.0-rc.0 version
1. when using client mode, navigation becomes uncontrollable（当使用客户端模式时，导航变得不可控）
2. build production and run time, and everything turns out weird（构建生产与运行时，一切结果都变得奇怪）

next 15.0.0-rc.0 version :  is not cache demo2 page (use server)

the result of using turbo is consistent（测试是否使用 turbo 结果一致）

### Current vs. Expected behavior

It should perform normally, whether or not client mode is used, and when running in production mode, it should be consistent with the development environment.

不论是否使用客户端模式，都应该正常执行，当运行在生产模式时，应该与开发环境一致。 

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16301
  Available CPU cores: 8
Binaries:
  Node: 20.13.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A

---

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16301
  Available CPU cores: 8
Binaries:
  Node: 20.13.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-rc.0
  eslint-config-next: 14.2.5
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by samcx** [comment]
@lanmingle Thank you for submitting an issue!

Can you be more specific how it becomes "uncontrollable"—what exactly is the behavior that makes it seem weird?
