### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by YASHMANIC** [vercel/next.js#68784]
### What is the update you wish to see?

import { OpenAIStream, StreamingTextResponse } from "ai" import { Configuration, OpenAIApi } from "openai-edge" is deprecated or not i can see it in your docs but my ide says deprecated****

### Is there any context that might help us understand?

import { OpenAIStream, StreamingTextResponse } from "ai" import { Configuration, OpenAIApi } from "openai-edge" is deprecated or not i can see it in your docs but my ide says deprecated****

**Comment by samcx** [comment]
As `ai` is not related to Next.js, please refer to our [Vercel Community](https://vercel.community/c/help/9) for Vercel-related (`ai` is a Vercel-owned package) questions!
