### ISSUE TITLE
Standalone Output doesn't work

### ISSUE THREAD

**Issue by Charismara** [vercel/next.js#68824]
### Link to the code that reproduces this issue

https://github.com/Blutmond-Team/CloudSettings-API/tree/dev/dockerize

### To Reproduce

1. Install pnpm
2. Run `pnpm i`
3. Run `pnpm build`

### Current vs. Expected behavior

An error occurs which prevents the project from building.

The Project builds just fine without the `output: 'standalone'` option set.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32548
  Available CPU cores: 32
Binaries:
  Node: 20.14.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.7.0
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Output (export/standalone)

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by feedthejim** [comment]
Please provide a slimmed-down repro + include the actual error in the issue!
