### ISSUE TITLE
Docs: Missing custom Partytown configuration for `Script` with `strategy="worker"`

### ISSUE THREAD

**Issue by guisehn** [vercel/next.js#68943]
### What is the documentation issue?

Next.js is missing documentation about Partytown configuration for its usage with the `Script` component.

### Is there any context that might help us understand?

The [`Script`](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts) component with the `strategy` prop set to `worker` uses [Partytown](https://partytown.builder.io/) under the hood.

Users may need to customize [Partytown options](https://partytown.builder.io/configuration) such as `forward`, `loadScriptsOnMainThread`, and `resolveUrl`, to allow for third party scripts such as Segment and Google Tag Manager to work properly.

Next.js allows customizing Partytown options by specifying a `script` tag with `data-partytown-config` inside `Head`:

```jsx
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        <script
          data-partytown-config
          dangerouslySetInnerHTML={{
            __html: `
              partytown = {
                lib: "/_next/static/~partytown/",
                debug: true
              };
            `,
          }}
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
```

This used to be documented on `docs/basic-features/script.md`, as you can see on the [pull request that originally introduced the `worker` strategy](https://github.com/vercel/next.js/pull/34244/files#diff-62dbdb4bc703f7997ea259ad68d8e823d9fafed1e9571155e01c4de21abb6b47R165-R197), but this doc page was removed (potentially unintendedly) on https://github.com/vercel/next.js/pull/50701, and there's no longer mention of Partytown configuration in Next.js docs.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/optimizing/scripts#strategy

**Comment by samcx** [comment]
@guisehn I don't think think this is missing →

- https://nextjs.org/docs/app/building-your-application/optimizing/scripts#offloading-scripts-to-a-web-worker-experimental
- https://nextjs.org/docs/pages/building-your-application/optimizing/scripts#offloading-scripts-to-a-web-worker-experimental

**Comment by samcx** [comment]
@guisehn Thank you for submitting an issue.

It's unlikely we need to add this for an experimental feature (sometimes, less is better for documentation), as you can work this out via this next section → https://nextjs.org/docs/app/building-your-application/optimizing/scripts#inline-scripts.

**Comment by guisehn** [comment]
@samcx IMO even being an experimental feature, it's a problem to not have this in the docs, because:

1. Third party tracking scripts are, as I see it, the 90% use case for web worker scripts. And most of them need to expose a variable to the main thread (e.g. `dataLayer` for Google Tag Manager, or `analytics` for Segment). This is only possible if we configure the `forward` option of Partytown.

2. There are important details specific to Next's implementation that need to be done to configure it. For instance, you must add a `data-partytown-config` attribute to the script that is configuring partytown ([see relevant code](https://github.com/vercel/next.js/blob/4c1cf26c8c7b4a0d83ba4ea4daf960f2726da2f5/packages/next/src/pages/_document.tsx#L225-L245)), and you need to pass `lib: "/_next/static/~partytown/"` again. This requirement is not part of Partytown. It's part of Next. And it's not documented anywhere.

If we don't put this on the main script page, any chance we could put it somewhere else? Maybe in a dedicated page, and without using `dangerouslySetInnerHTML`?
