### ISSUE TITLE
[turbo] an unexpected Turbopack error occured

### ISSUE THREAD

**Issue by EliasVal** [vercel/next.js#68974]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/gracious-dust-go8s7s

### To Reproduce

1. Start turbo with `NEXT_TURBOPACK_TRACING=1`

### Current vs. Expected behavior

Currently turbopack does not work at all, since version `15.0.0-canary.92`, `.91` is the last version where turbopack works, otherwise it is just stuck on `Compiling / ...`. I tried `NEXT_TURBOPACK_TRACING=1` to see what's wrong and it dumped the following error (see additional context)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32457
  Available CPU cores: 24
Binaries:
  Node: 20.16.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.117 // Latest available version is detected (15.0.0-canary.117).
  eslint-config-next: 15.0.0-canary.102
  react: 19.0.0-rc-8269d55d-20240802
  react-dom: 19.0.0-rc-8269d55d-20240802
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I'd also like to add that the project is part of a pnpm monorepo.
The codesandbox is just an empty project since I can't seem to be able to replicate it anywhere but I'm still stuck on Next.js `15.0.0-canary.91`, which is probably not ideal

```log
Panic: panicked at crates\napi\src\next_api\project.rs:282:76:
called `Result::unwrap()` on an `Err` value: ParseError { kind: Other(None) }
Backtrace:    0: napi_register_module_v1
   1: napi_register_module_v1
   2: BrotliDecoderSetParameter
   3: napi_register_module_v1
   4: napi_register_module_v1
   5: napi_register_module_v1
   6: napi_register_module_v1
   7: napi_register_module_v1
   8: napi_register_module_v1
   9: BrotliDecoderSetParameter
  10: BrotliDecoderSetParameter
  11: BrotliDecoderSetParameter
  12: napi_register_module_v1
  13: napi_register_module_v1
  14: napi_register_module_v1
  15: napi_register_module_v1
  16: napi_register_module_v1
  17: napi_register_module_v1
  18: napi_register_module_v1
  19: napi_register_module_v1
  20: napi_register_module_v1
  21: napi_register_module_v1
  22: BaseThreadInitThunk
  23: RtlUserThreadStart
```

**Comment by lubieowoce** [comment]
> The codesandbox is just an empty project since I can't seem to be able to replicate it anywhere but I'm still stuck on Next.js 15.0.0-canary.91, which is probably not ideal

Does that codesandbox fail in the way you describe when you run it locally?

**Comment by EliasVal** [comment]
> If you pull that codesandbox code down and run `next dev --turbo` locally, does it also fail in the way you describe? Or is it only failing in the pnpm monorepo project you mentioned? We can't do much here if we don't have _some_ way of reproducing this


It seems to only reproduce in my monorepo. Is there anything I could do about it?

**Comment by EliasVal** [comment]
@lubieowoce I just went through the monorepo's dependency tree and there were two things I've changed:
Removed next from the root `package.json`
Resolved `There are cyclic workspace dependencies` warnings

and the issue seems to be fixed!
