### ISSUE TITLE
Your Team encountered an unknown problem. Please reach out to our support team for details. Learn More

### ISSUE THREAD

**Issue by mundanecoder** [vercel/next.js#69040]
### Link to the code that reproduces this issue

https://github.com/mundanecoder/Coders-Boutique/tree/main

### To Reproduce

while deploying i got the issue

### Current vs. Expected behavior

Your Team encountered an unknown problem. Please reach out to our support team for details. [Learn More](https://vercel.com/help)

getting this issue while trying to deploy

### Provide environment information

```bash
windows
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by samcx** [comment]
@mundanecoder Please look to provide more useful information and label the issue correctly (e.g., affecting the deploy stage, not the `next build` local stage).

Since it's not clear whether this is a Next.js issue, I will be closing this in the meantime.
