### ISSUE TITLE
Docs: Learn Next.js Chapter 9

### ISSUE THREAD

**Issue by bigliuliu** [vercel/next.js#69084]
### What is the documentation issue?

[Chapter9](https://nextjs.org/learn/dashboard-app/streaming)

![2024-08-20_160419](https://github.com/user-attachments/assets/7cb37a4a-d592-4861-a41e-3b8cafe59a43)
According to the context , we didn't add any skeletons to the customers pages ,so customers pages won't display skeleton.

### Is there any context that might help us understand?

Please delete `and customers pages as well.`  As the guide did ,only invoices page will loading skeleton.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/streaming

**Comment by samcx** [comment]
@bigliuliu Hi there!

These Learn course issues should be reported in different repository instead. →

![CleanShot 2024-08-20 at 13 43 48@2x](https://github.com/user-attachments/assets/54f7f694-18ab-4615-852f-b24a12e6a7bd)
