### ISSUE TITLE
Redirects don't work in production.  The page times out

### ISSUE THREAD

**Issue by Elindo586** [vercel/next.js#69106]
### Link to the code that reproduces this issue

https://github.com/Elindo586/estuff/tree/main/app/my

### To Reproduce

I am trying to do re-directs in two different ways.

1.  The way I would like better using this code here: https://github.com/Elindo586/estuff/blob/main/app/my/othersocial/%5Blink%5D/%5Bemail%5D/route.js

^^ This code should work by clicking an external link directed to the site with the extension /my/othersocial/[link]/[email]
The code works fine from my localhost, but not working on the live website as the page times out.

2.  An alternative way also doesn't seem to be working, and page also times out
    using frontend page here to send data to the api and redirect: https://github.com/Elindo586/estuff/blob/main/app/my/social/%5Blink%5D/%5Bemail%5D/page.js
... then the api to work with the front page would be this: https://github.com/Elindo586/estuff/blob/main/app/my/trackclick/route.js

I have checked my environment variables and they are working OK. 

Why is it that I am not able to get a re-direct? 

I need to make sure to send an email with the information from the dynamic slugs, and then send the re-direction once the information for the email has been processed. 

    
    

### Current vs. Expected behavior

Current:
Pages times out when visiting the live website, but it works fine from localhost

Expected:
Once you visit the route from the live website, it should send an email telling me that variable ${email} has clicked a link, and then redirects the user to a proper website given from the variable ${link}

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16263
  Available CPU cores: 8
Binaries:
  Node: 20.12.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // Latest available version is detected (14.2.5).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Documentation, Middleware, Navigation, Pages Router, Runtime, Testing

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

The problem is when the site is uploaded to Vercel.  It works fine from localhost.

**Comment by ztanner** [comment]
How long does it take for the email to be sent? It sounds like you might be hitting the default serverless execution limits, which can be configured via `maxDuration`: https://vercel.com/docs/functions/configuring-functions/duration

If you're still running into troubles, I'd suggest opening a Vercel [support ticket](https://vercel.com/help) or community post, as GitHub issues are specifically for bugs or feature requests within the framework regardless of where it's hosted.

**Comment by Elindo586** [comment]
Thanks..

According to the Vercel information the max duration is already 15 seconds if I am reading it properly.

I also put it on the route.js to increase it to 10 according to the data you linked.  Not sure if I am doing it properly.

Anyway, the error remains.

I have posted it on the community, but of course haven't gotten an answer and I am looking elsewhere, and I saw people with similar issues and didn't see an answer there either.

I will try to open a ticket at Vercel... . and wait... hopefully I get some feedback soon.

**Comment by ztanner** [comment]
> Thanks..
> 
> According to the Vercel information the max duration is already 15 seconds if I am reading it properly.
> 
> I also put it on the route.js to increase it to 10 according to the data you linked. Not sure if I am doing it properly.
> 
> Anyway, the error remains.
> 
> I have posted it on the community, but of course haven't gotten an answer and I am looking elsewhere, and I saw people with similar issues and didn't see an answer there either.
> 
> I will try to open a ticket at Vercel... . and wait... hopefully I get some feedback soon.

Can you clarify what the error is?
