### ISSUE TITLE
Docs: Creating new Next.js project with TypeScript does not add TypeScript lint rules

### ISSUE THREAD

**Issue by LuckyT89** [vercel/next.js#69184]
### What is the documentation issue?

On the ESLint page of the documentation there is a section named TypeScript. It says that when creating a new project set up to use TypeScript, it should add TypeScript-specific lint rules and the content of the .eslintrc.json file should look like this:
```
{
  "extends": ["next/core-web-vitals", "next/typescript"]
}
```

However, when I create a new Next.js project by running `npx create-next-app@latest` and select the option to use TypeScript in the prompts that follow, it does not add the TypeScript lint rules and the .eslintrc.json file looks like this:
```
{
  "extends": "next/core-web-vitals"
}
```

### Is there any context that might help us understand?

It seems these lint rules are not being added when creating a new project with TypeScript. I am not sure if this is the intended behavior and it is an issue with the documentation that needs to be updated, or it is a bug that needs to be fixed. 

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/configuring/eslint

**Comment by flavio-dev** [comment]
same problem here

**Comment by flavio-dev** [comment]
hello @LuckyT89 I also have this problem. Worst tho: running the command `next lin` now returns an error if you update your eslintrc to what is suggested on the documentation:

```
{
  "extends": ["next/core-web-vitals", "next/typescript"]
}
```

ERROR:
```
next lint
Failed to load config "next/typescript" to extend from.
```

**Comment by robcaldecott** [comment]
It would be great to get this working as documented. I'm trying to enable the `@typescript-eslint/consistent-type-imports` rule but the missing `next/typescript` plugin is stopping it from working.

**Comment by psylone** [comment]
It appears that the `next/typescript` linter rules are supposed to be part of the `eslint-config-next` package. However, if you check the [latest published version](https://www.npmjs.com/package/eslint-config-next?activeTab=code), you'll notice that it only includes the `core-web-vitals` rules. This suggests that the `next/typescript` linter rules simply haven't been published yet.

**Comment by samcx** [comment]
@flavio-dev What version of <picture data-single-emoji=":nextjs:" title=":nextjs:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/nextjs/2a85d633ae594556.png" alt=":nextjs:" align="absmiddle"></picture> are you using? I am not getting this error on the latest canary.

**Comment by CesarCarrillo91** [comment]
Same issue here. I'm using next version: `14.2.5`

**Comment by samcx** [comment]
@CesarCarrillo91 Can you confirm if this is working for you on the latest canary?

**Comment by CesarCarrillo91** [comment]
@samcx - not working for me on `15.0.0-canary.130`.

**Comment by apomortsev** [comment]
It looks like `next lint` (using the latest canary) installs an older `eslint-config-next` version that is missing the `eslint-config-next\typescript.js` file. Manually updating `pnpm update eslint-config-next@v15.0.0-canary.130` brings the missing file in and resolves the `Failed to load config "next/typescript" to extend from.` error.

**Comment by d-kunrath** [comment]
@apomortsev this worked for me, thank you.

**Comment by LuckyT89** [comment]
@kleekich21 I see the commit you made for this issue. Hopefully this will make it so that when you create a new project using `npx create-next-app@latest` and select TypeScript, it will set up the correct linting rules without needing any other setup. Thanks!

**Comment by samcx** [comment]
@apomortsev Thank you for the clarification.

The PR that <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> the issue will be backported to `14.2.7`, which likely will be released later today! Afterwards, you should be able to `npx create-next-app@latest` and have the correct linting rules.

In the meantime, I will be closing this issue! Please be on the look for the new minor release → https://github.com/vercel/next.js/releases.

**Comment by Lovely-Ruby** [comment]
> It looks like `next lint` (using the latest canary) installs an older `eslint-config-next` version that is missing the `eslint-config-next\typescript.js` file. Manually updating `pnpm update eslint-config-next@v15.0.0-canary.130` brings the missing file in and resolves the `Failed to load config "next/typescript" to extend from.` error.

thanks

**Comment by LuckyT89** [comment]
@samcx I tried creating a new app today with `npx create-next-app@latest` and selecting TypeScript. I can see it is now using Next version 14.2.7 but the .eslintrc.json file is still missing next/typescript and only includes next/core-web-vitals. I may have misunderstood your comment above, it sounded like once 14.2.7 was released the issue would be fixed. It seems like the PR that @kleekich21 made which has the commit that fixes this (https://github.com/f-lab-edu/thumbnails/pull/4/commits) is still open.

**Comment by samcx** [comment]
@LuckyT89 Unfortunately, it wasn't added to `14.2.7`, but we are looking to update this still! Stay tuned for updates → https://github.com/vercel/next.js/releases.

Not sure what https://github.com/f-lab-edu/thumbnails/pull/4/commits is about, as this is not in the :nextjs: repo :thinkies:

**Comment by LuckyT89** [comment]
@samcx Whoops my bad- I saw in the thread above there was a commit made that referenced this issue, I didn't realize it was not actually for this repo. 

Thanks for the update, I will look out for this change in the future.

**Comment by eren-amundsen** [comment]
> hello @LuckyT89 I also have this problem. Worst tho: running the command `next lint` now returns an error if you update your eslintrc to what is suggested on the documentation:
> 
> ```
> {
>   "extends": ["next/core-web-vitals", "next/typescript"]
> }
> ```
> 
> ERROR:
> 
> ```
> next lint
> Failed to load config "next/typescript" to extend from.
> ```

same issues

> It looks like `next lint` (using the latest canary) installs an older `eslint-config-next` version that is missing the `eslint-config-next\typescript.js` file. Manually updating `pnpm update eslint-config-next@v15.0.0-canary.130` brings the missing file in and resolves the `Failed to load config "next/typescript" to extend from.` error.

it works for me, thank😊, the latest version of eslint-config-next is "15.0.0-canary.134"
