### ISSUE TITLE
Sass built-in support doesn't work

### ISSUE THREAD

**Issue by flavio-dev** [vercel/next.js#69185]
### Link to the code that reproduces this issue

https://github.com/flavio-dev/error-sass-next

### To Reproduce

1. start the application next dev
2. notice the problem: 
```
⨯ ./src/app/page.module.scss
To use Next.js' built-in Sass support, you first need to install `sass`.
Run `npm i sass` or `yarn add sass` inside your workspace.`
```
even tho sass (and node-sass) are installed

### Current vs. Expected behavior

i'm expecting it to work like the documentation suggests it.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64
  Available memory (MB): 32768
  Available CPU cores: 8
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.6 // Latest available version is detected (14.2.6).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

reproduction steps:
`npx create-next-app@latest`
I said yes to typescript

then change the `page.module.css` to `page.module.scss`, and of course change in page.tsx to `import styles from "./page.module.scss";`

run `next dev` and notice the error asking you to install sass

installing `sass` following instructions: `npm i sass`

run `next dev`, same error.

installing `node-sass` as I read somewhere this would solve the problem

run `next dev`, still same error.

**Comment by Netail** [comment]
`node-sass` is the old sass library. To install sass, use `npm i sass`

**Comment by flavio-dev** [comment]
Hi @Netail ,

no I `npm install sass` as mentioned in my initial post, following the guidelines. So you are saying that for you it works? 

I just `npm uninstall node-sass` and run `next dev` and still have the problem:

<img width="745" alt="Screenshot 2024-08-23 at 14 10 12" src="https://github.com/user-attachments/assets/c729e0af-0489-4607-beac-7d30877fa128">

I pushed what you suggested onto my repo. In this current state of the repo, I have the error.

Did you install sass globally maybe? What's your version of npm?

```
npm -v
10.8.2

node -v
v20.17.0
```

**Comment by Netail** [comment]
>So you are saying that for you it works?
yes

**Comment by flavio-dev** [comment]
@Netail hey so I found out that if I run the application with

```npm run dev```

it works, but if I run 

``` next dev```

it doens't....

any idea on why?

**Comment by Netail** [comment]
Ohh interesting, nice find.

> any idea on why?

That, I have no idea

**Comment by flavio-dev** [comment]
I'll document the output in my console here:

```
npm run dev

> error@0.1.0 dev
> next dev

  ▲ Next.js 14.2.6
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1515ms
 ○ Compiling / ...
 ✓ Compiled / in 5.2s (547 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 GET / 200 in 5372ms
 GET /_next/static/webpack/032d6542e9d8688b.webpack.hot-update.json 404 in 5395ms
 GET / 200 in 33ms
 GET / 200 in 29ms
```

vs


```
next dev   
  ▲ Next.js 14.2.6
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 1782ms
 ○ Compiling / ...
 ⨯ ./src/app/page.module.scss
To use Next.js' built-in Sass support, you first need to install `sass`.
Run `npm i sass` or `yarn add sass` inside your workspace.

Learn more: https://nextjs.org/docs/messages/install-sass
 ⨯ ./src/app/page.module.scss
To use Next.js' built-in Sass support, you first need to install `sass`.
Run `npm i sass` or `yarn add sass` inside your workspace.

Learn more: https://nextjs.org/docs/messages/install-sass
 ⨯ ./src/app/page.module.scss
To use Next.js' built-in Sass support, you first need to install `sass`.
Run `npm i sass` or `yarn add sass` inside your workspace.

Learn more: https://nextjs.org/docs/messages/install-sass
 GET / 500 in 6572ms
```

out of curiosity, @Netail would you mind testing on your end with `next-dev` and with `npm run dev`?

**Comment by Netail** [comment]
`npm run dev` runs correctly. How do you run `next` as a command (without a package manager) in your console? Did you install it globally?

**Comment by flavio-dev** [comment]
yes I installed `next` globally.... and that's maybe why this is not working!

gonna remove it from my global installs and use `npm run dev` from now on.

**Comment by flavio-dev** [comment]
i think this the the solution so I will close this ticket! Thank you @Netail for your support.

**Comment by Netail** [comment]
> i think this the the solution so I will close this ticket! Thank you @Netail for your support.

No problemo :)
