### ISSUE TITLE
 location hash change doesnt trigger hashchange event

### ISSUE THREAD

**Issue by AmirShafikhani** [vercel/next.js#69256]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/bitter-framework-zmcyr4?file=%2Fapp%2Fpage.tsx%3A1%2C1-37%2C21

### To Reproduce

im trying to create a hash based routing in next 14 but the window hashchange event does'nt trigger when i change the location hash in these ways:

<Link href="/#some-hash">Link to #some-hash</Link>

<Link href={{ hash: "some hash" }}>Link to #some-hash</Link>

<Link href="/#some-hash" legacyBehavior><a>Link to #some-hash</a></Link>

<Link href={{ hash: "some hash" }} legacyBehavior><a>Link to #some-hash</a></Link>

i have even tried to push using the router like this:

router.push("#some-hash");

but non of them triggers the hashchange event.

the only way that i get succeed was using the window itself to change the hash like this:

window.location.hash = "some hash"

but i wanna use next js router to implement this. any thoughts?

### Current vs. Expected behavior

i expected at least an event listener to be triggered or sth else that would help us to create hash based minimal routing systems

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 16220
  Available CPU cores: 16
Binaries:
  Node: 20.15.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by simonri** [comment]
You can use `useParams()` for this. Keep in mind though that the hash is only client side and will never be send to the server. 

The following code allows you to listen to hash changes:

```js
const params = useParams();

useEffect(() => {
  console.log(window.location.hash);
}, [params]);
```

**Comment by AmirShafikhani** [comment]
worked tnx ❤️

**Comment by m-sanders** [comment]
This is working as expected.
