### ISSUE TITLE
The whole thing about being unable to disable edge runtime in middleware is a huge shame for Next.js and all its users. How do I disable edge runtime in middleware??

### ISSUE THREAD

**Issue by 0x00000000000000000000000** [vercel/next.js#69261]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/boring-bohr-go8s7s

### To Reproduce

**The Edge runtime does not support all Node.js APIs. Some packages will not work. Learn more about the unsupported APIs in the [Edge Runtime](https://nextjs.org/docs/app/api-reference/edge#unsupported-apis).**

Since you did not support all Node.js APIs, you should allow user to opt in/out from edge runtime for middleware. Did you all really try hard to squeeze out revenue from Vercel hosting?

### Current vs. Expected behavior

<img width="638" alt="image" src="https://github.com/user-attachments/assets/db70dd2b-48a9-4091-b903-3d51a8732d13">

Current:
Middleware runtime is not able to switch to Node.js runtime

Expected Behaviour:
Middleware runtime is able to switch to Node.js runtime

### Provide environment information

```bash
macOS
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by feedthejim** [comment]
since you already commented on #46722, I assume you're aware this is a duplicate
