### ISSUE TITLE
Docs: A conflicting formulation was found

### ISSUE THREAD

**Issue by nicevlhjfihtqngkldl** [vercel/next.js#69278]
### in the link below, it said fetch will cache default:
https://nextjs.org/docs/app/building-your-application/caching
![image](https://github.com/user-attachments/assets/5c3f5c2f-46f6-459e-a5a5-6088b60987d0)

### but in this link, it said fetch won't cache default.
https://nextjs.org/docs/app/api-reference/functions/fetch
![image](https://github.com/user-attachments/assets/9eab9bff-c3f3-4f84-ac5c-86b7725b5919)

### Is there any context that might help us understand?

next.js 15,app router

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/caching

**Comment by AdityaSrivastava185** [comment]
Hello @nicevlhjfihtqngkldl  , I want some more clarity about the issue , can you please explain me about it  more please , it will help me to understand it more better and work on it

**Comment by nicevlhjfihtqngkldl** [comment]
> Hello @nicevlhjfihtqngkldl , I want some more clarity about the issue , can you please explain me about it more please , it will help me to understand it more better and work on it

Sorry, I think I misunderstood the meaning of the document.
request memoization and fetch are for different scenarios.
The document is right.
