### ISSUE TITLE
Importing modules from Internal package fails with turbopack

### ISSUE THREAD

**Issue by romulovalez** [vercel/next.js#69426]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/zealous-frog-89zfjh

### To Reproduce

1. Start nextjs `pnpm install && cd apps/nextjs && pnpm dev` (if you are testing on codesandbox just execute task dev)
2. It will throw Error `Module not found: : Can't resolve...` referencing the import from the internal package.

### Current vs. Expected behavior

We're trying to use an [internal package](https://turbo.build/repo/docs/core-concepts/internal-packages) from the monorepo in nextjs, executing `next dev --turbo` should work as intended (showing 'world' on screen), but it is failing. If we remove `--turbo` it works correctly.

This is the same error as this issue: https://github.com/vercel/next.js/issues/41961 but on turbopack (--turbo), on this issue the fix was to add this config to next.config.mjs:

```js
        ...,
	webpack: (webpackConfig, { webpack }) => {
		webpackConfig.resolve.extensionAlias = {
			'.js': ['.ts', '.tsx', '.js', '.jsx'],
			'.mjs': ['.mts', '.mjs'],
			'.cjs': ['.cts', '.cjs'],
		};
		return webpackConfig;
	},
        ...,
```

But on turbopack (--turbo) there is no equivalent or an automatic handling of this scenario.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:27 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.19.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 9.5.0
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 14.2.5
  react: 19.0.0-rc-7771d3a7-20240827
  react-dom: 19.0.0-rc-7771d3a7-20240827
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

It's happening on both stable and canary releases.

**Comment by romulovalez** [comment]
I made an e2e test to demonstrate this issue: https://github.com/vercel/next.js/issues/69426#:~:text=Add%20tests%20to%20import%20internal%20esm%20package%20%2369530

**Comment by Ipriyankrajai** [comment]
I'm also facing same Issue while Importing modules from Internal package.

**Comment by timneutkens** [comment]
To set expectations this is currently not a priority because you're customizing the webpack configuration, can't say if/when this will be implemented right now.

**Comment by karlhorky** [comment]
## Workaround

[`allowImportingTsExtensions` from TypeScript 5.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#allowimportingtsextensions) with `.ts` file extensions seems to be an option to get the dev server to resolve:

CodeSandbox: https://codesandbox.io/p/devbox/laughing-leavitt-7293td?file=%2Fapps%2Fesm-package%2Ftsconfig.json%3A9%2C1

![Screenshot 2024-10-11 at 18 48 53](https://github.com/user-attachments/assets/c1fbec8d-6997-4913-ba93-4fefe5930a5e)

In a notable turnaround of the TypeScript team, since TypeScript 5.7, there is a `--rewriteRelativeImportExtensions` option which will allow tsc to understand `.ts*` imports:

- https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-beta/#path-rewriting-for-relative-paths

**Comment by timneutkens** [comment]
The underlying thing you're trying to configure around mapping `.cjs` -> `.cts` etc. is now supported by default: https://github.com/vercel/next.js/pull/71635

Going to close this issue as the root problem that required you to customize is fixed 👍

**Comment by nlwillia** [comment]
> The underlying thing you're trying to configure around mapping `.cjs` -> `.cts` etc. is now supported by default: #71635
> 
> Going to close this issue as the root problem that required you to customize is fixed 👍

So far as I can tell, this _isn't_ fixed for [just wanting to use `.js` in imports](https://www.typescriptlang.org/docs/handbook/modules/theory.html#typescript-imitates-the-hosts-module-resolution-but-with-types) (which I would expect to be most people concerned about this).  I tried `15.0.2-canary.6`, and the `extensionAlias` config was still needed for next to build, and `--turbo` was not able to resolve those same module specifiers.
