### ISSUE TITLE
Image optimizer rejects requests for remote images with _next/image in the URL (v14.2.7)

### ISSUE THREAD

**Issue by igordanchenko** [vercel/next.js#69456]
### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-14-2-7-image-bug?file=app%2Fpage.tsx

### To Reproduce

1) Download the sandbox - https://stackblitz.com/edit/nextjs-14-2-7-image-bug?file=app%2Fpage.tsx
2) `npm install && npm run dev`
3) Open http://localhost:3000
3) Observe the broken image

### Current vs. Expected behavior

Image optimizer in v14.2.7 rejects image requests for *remote images* that contain `_next/image` in the URL path.

Scenario:

1) Next.js app uses images coming from external CMS (the images are hosted on 3rd-party domains)
2) Some of the remote images just happen to be sourced from 3rd-party domains that also use Next.js and thus contain `_next/image` in their URL path
3) Starting with v14.2.7 image optimizer rejects image requests for such *remote images*

As far as I can tell, this change comes from #68628

While I understand the need to avoid recursive image optimizer calls within the same app, the current implementation seems overly restrictive. Image optimizer should not reject requests for *remote images* specified in the `remotePatterns` as the app doesn't have control over what images are coming from an *external* CMS.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 20.16.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.7 // Latest available version is detected (14.2.7).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image (next/image)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

**Comment by huozhi** [comment]
This is the expected behavior, `_next/image` images are already optimized. It could lead to duplicated optimization or unexpected failures during image opt phase. If you're using that url you should use `unoptimized` prop for the `<Image>` components where it loads the optimized images
