### ISSUE TITLE
Docs: location of cached images is wrong

### ISSUE THREAD

**Issue by rickgm** [vercel/next.js#69471]
### What is the documentation issue?

the actual location is "_next/images", but the documentation states:
<img width="897" alt="image" src="https://github.com/user-attachments/assets/f39a1586-5208-47e8-b786-cf1f7e6a9917">

### Is there any context that might help us understand?

see above

**Comment by samcx** [comment]
@rickgm This is actually true, on the disk. When you access the images, you do `_next/images` (a difference between where it's stored and how you access it).
