### ISSUE TITLE
Next v14 Double Render

### ISSUE THREAD

**Issue by enchorb** [vercel/next.js#69498]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/naughty-dream-4kmzfm?file=%2Fapp%2Fpage.tsx%3A11%2C1

### To Reproduce

See Issue: https://github.com/vercel/next.js/issues/58736

### Current vs. Expected behavior

See Issue: https://github.com/vercel/next.js/issues/58736

### Provide environment information

```bash
N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

More context in this issue: https://github.com/vercel/next.js/issues/58736

This seems to be already fixed with https://github.com/vercel/next.js/pull/67680 however I see it is going into v15 (https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.70).

Can we get a PR into v14 as it is preventing us from upgrading past v14.1

**Comment by ztanner** [comment]
Hi -- due to the scale of this refactor, it has to go out in a major release and is not easily backported to v14. As this is not a critical bugfix or security fix it will be part of the 15 release.
