### ISSUE TITLE
Docs: Documentation incorrectly says database calls will opt in to server side rendering by default

### ISSUE THREAD

**Issue by LelouBil** [vercel/next.js#69504]
### What is the documentation issue?

[This example in the documentation](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching#fetching-data-on-the-server-with-an-orm-or-database) says 
> This example would opt your Next.js application into [server-side rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering).

But since there are no calls to unstable_noStore() in the page it is indeed still using the default which is static site generation.

### Is there any context that might help us understand?

[This other section of the documentation](https://nextjs.org/docs/app/building-your-application/rendering/server-components#switching-to-dynamic-rendering) says the conditions for a route to be static.

Next.js doesn't see *custom* uncached data requests, so it seems like unstable_noStore() is really needed, however the page I linked does not say this information and so is misleading.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching

**Comment by samcx** [comment]
@LelouBil This is correct!

If you want to push up a quick <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture> to fix this, that will be great.

**Comment by LelouBil** [comment]
Fixed by #69695
