### ISSUE TITLE
Favicon.ico link not using `sizes="any"`

### ISSUE THREAD

**Issue by seamuslowry** [vercel/next.js#69553]
### Link to the code that reproduces this issue

https://github.com/seamuslowry/real-true-science-facts/tree/bug/no_any

### To Reproduce

1. run `npm run build`
2. note that the generated `out/index.html` file has `<link rel="icon" href="/favicon.ico" type="image/x-icon" sizes="16x16"/>`

### Current vs. Expected behavior

According to the [documentation](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#favicon), generated `head` data from `favicon.ico` should use `sizes="any"`. In this case, it uses `sizes="16x16"`. And the sizes field generated is based on the sizes of the images in `favicon.ico`

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26)
  Available memory (MB): 31740
  Available CPU cores: 20
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.7
  eslint-config-next: 14.2.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.5
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Documentation, Metadata, Output (export/standalone)

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local), Other (Deployed)

**Comment by devjiwonchoi** [comment]
@seamuslowry @archanaagivale30
Sorry for the confusion. we had a behavior change at https://github.com/vercel/next.js/pull/53343 but the docs weren't up to date, and we've updated now.
Thank you for your report!
