### ISSUE TITLE
Turbopack fails to compile code referring to `shiki` though Webpack can compile it

### ISSUE THREAD

**Issue by exKAZUu** [vercel/next.js#69562]
### Link to the code that reproduces this issue

https://github.com/exKAZUu/turbopack-shiki-issue

### To Reproduce

1. `git clone https://github.com/exKAZUu/turbopack-shiki-issue`
2. `cd turbopack-shiki-issue`
3. `npm install`
4. `npm run dev` (it works as expected WITHOUT `--turbo` flag)
5. `npm run dev-turbo` (it DOESN'T work WITH `--turbo` flag. It shows the following error.)

```
 ⨯ ./node_modules/shiki/dist/index.mjs
Package shiki (serverExternalPackages or default list) can't be external
The request shiki matches serverExternalPackages (or the default list), but it can't be external:
The package seems invalid. require() resolves to a EcmaScript module, which would result in an error in Node.js.
```

### Current vs. Expected behavior

`npm run dev` works well, but `npm run dev-turbo` doesn't work.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8122
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 22.7.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.138 // Latest available version is detected (15.0.0-canary.138).
  eslint-config-next: N/A
  react: 19.0.0-rc-7771d3a7-20240827
  react-dom: 19.0.0-rc-7771d3a7-20240827
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested both Next.js `15.0.0-canary.138` and `14.2.7` and the results are same.
My reproduction repo is based on https://github.com/vercel/next.js/issues/64434#issuecomment-2067587679

**Comment by exKAZUu** [comment]
Does https://github.com/vercel/next.js/issues/64525 relate this issue ...?

**Comment by timneutkens** [comment]
![CleanShot 2024-09-10 at 16 04 53@2x](https://github.com/user-attachments/assets/f0e6f8ab-d685-4cbe-89cb-00d7beb0c699)

Codesandbox: https://codesandbox.io/p/github/exKAZUu/turbopack-shiki-issue/main

It already works on canary, it's expected that it doesn't work on 14.2.7, but it's fixed on canary.

Btw this code is invalid:

```tsx
import dynamic from "next/dynamic";

export default function Home() {
    const ShikiViewer = dynamic(
        () => import("./ShikiViewer"),
        {ssr: false}
    );
    return <ShikiViewer/>;
}
```

Should be:

```tsx
import dynamic from "next/dynamic";

 const ShikiViewer = dynamic(
    () => import("./ShikiViewer"),
    {ssr: false}
);

export default function Home() {
    return <ShikiViewer/>;
}
```
