### ISSUE TITLE
Conditional parallel route fetches data from all matched routes even if they aren't rendered

### ISSUE THREAD

**Issue by Yhprum** [vercel/next.js#69623]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/compassionate-wildflower-fhkfvd?workspaceId=16efbd00-a546-4c4a-a71b-de3c7612dd00

### To Reproduce

1. start the dev server
2. navigate to `/parallel`
3. Both `this data is fetched on route test1` and `this data is fetched on route test2` will be logged on the server

### Current vs. Expected behavior

I expected only `this data is fetched on route test1` to be logged on the server, since that is the only page that is being rendered, however I see the logs from both pages indicating that they will both fetch data when the route is navigated to.

I am following the [conditional routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#conditional-routes) guide where I have the same `/dashboard` url display different data based on if the logged in user is a user or admin, but it tries to fetch data for both, which causes unnecessary data fetching and sometimes errors.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16316
  Available CPU cores: 8
Binaries:
  Node: 20.9.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.7 // Latest available version is detected (14.2.7).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Other (Deployed)

### Additional context

I'm hosting on heroku using the default settings, but this appears in dev as well

**Comment by ztanner** [comment]
Hi, thanks for the report! 

This is indeed a current limitation of parallel routes that we aware of. We're currently tracking it in the following issue, so I'm going to close this in favor of that one. 

- https://github.com/vercel/next.js/issues/53292
