### ISSUE TITLE
Unable to compile sass when using dynamic import and --turbo.

### ISSUE THREAD

**Issue by NazmusSayad** [vercel/next.js#69643]
### Link to the code that reproduces this issue

https://github.com/NazmusSayad/next-turbo-sass-bug

### To Reproduce

1. Start the app in dev mode with --turbo

### Current behavior:

After starting in dev mode with --turbo, it's stuck and nothing is happening.
![image](https://github.com/user-attachments/assets/bfddcb3f-535f-46c2-9b27-e1b2351734b7)
![image](https://github.com/user-attachments/assets/7a5ac8f9-d11a-4fe7-bbd5-a89897a61238)

And this is consuming a lot of my resources.
![image](https://github.com/user-attachments/assets/f6cc7034-7bde-4d0b-8478-772b38c906db)

And with a slightly larger project, where I found this bug, it's taking even more.
![image](https://github.com/user-attachments/assets/01d2e0b1-acda-4b0a-afb9-dd05be1fa4d4)

*NOTE: This is also happening in projects with typescript*

---

### Excepted:
> The results were generated after importing normally instead of using dynamic import.

This should just work like normal.
![image](https://github.com/user-attachments/assets/5d53bdce-366e-43b7-85d6-c2d188fcb0cb)

It is taking fewer resources here.
![image](https://github.com/user-attachments/assets/2fc7bc95-7ffc-42c5-bf81-52349c9cd502)

### Provide environment information

```bash
### System 1:
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32442
  Available CPU cores: 20
Binaries:
  Node: 20.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.7 // Latest available version is detected (14.2.7).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A


### System 2:
Operating System:
  Platform: linux
  Arch: x64
  Version: #23~22.04.1-Ubuntu SMP Thu May  9 17:59:24 UTC 2024
  Available memory (MB): 7930
  Available CPU cores: 2
Binaries:
  Node: 20.16.0
  npm: 10.8.1
  Yarn: 1.22.22
  pnpm: 9.7.1
Relevant Packages:
  next: 14.2.7 // Latest available version is detected (14.2.7).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Lazy Loading, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested multiple node versions. It's the same.

**Comment by bgw** [comment]
Relaying some internal discussions about this: @sokra investigated and discovered that this issue is caused by us trying to build the same sass file once for the server, and once for the client. We get non-deterministic results because the sass code uses `random()`, which then causes an infinite loop of invalidation logic.

**This is a legitimate bug** which we intend to fix, but if you want a quick workaround, you can use a seeded random number generator, e.g. https://stackoverflow.com/a/32968963
