### ISSUE TITLE
i did not get "/hrms/_next/data/[hash]/[file].json" after build 

### ISSUE THREAD

**Issue by Tabish221** [vercel/next.js#69725]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
const nextConfig = {
    trailingSlash: true,
    output: 'export',
    basePath: '/hrms',
    images : {
        unoptimized : true
    },
}

module.exports = nextConfig;
```

### Which example does this report relate to?

with-prefetch

### How are you deploying your application? (if relevant)

in cpanel

### Describe the Bug

when i hover in Link prefetch request give me 404 response

prefetch hitting url "hrms/_next/data/[hash]/[file].json"

### Expected Behavior

file prefetch

### To Reproduce

![prefetch-issue](https://github.com/user-attachments/assets/8853926b-35cd-45ca-8c58-ec7bf7f32c4a)

**Comment by samcx** [comment]
@Tabish221 Please resubmit using the correct issue template (the [bug report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) one, not the example one) when reporting a possible confusion or 🐛 so we have the information to take a look!
