### ISSUE TITLE
Invalid Metadata properties caused by Route Group and Parallel Route at the same Level

### ISSUE THREAD

**Issue by serhiiminin** [vercel/next.js#69778]
### Link to the code that reproduces this issue

https://github.com/serhiiminin/nextjs-metadata-merging-issue/

### To Reproduce

1. Start the application.
2. Click on the "Product" link.
3. Observe the title of the browser tab.

### Current vs. Expected behavior

**Expected Result:** The browser tab displays the title of the "Product" page.

**Actual Result:** The browser tab displays the current URL instead of the page title. This issue is resolved after refreshing the page. (I tried adding `default.tsx` files at every level, thinking the issue might be related to parallel routes, but it didn't resolve the problem)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 9.9.0
Relevant Packages:
  next: 14.2.8 // Latest available version is detected (14.2.8).
  eslint-config-next: 14.2.8
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), Other (Deployed)

**Comment by huozhi** [comment]
This is fixed in patch release 14.2.9, please upgrade Next.js to that version, thanks 🙏
