### ISSUE TITLE
Docs: The docs say Next.JS 14 supports experimental PPR but anecdotal evidence says otherwise

### ISSUE THREAD

**Issue by boylec** [vercel/next.js#69791]
### What is the documentation issue?

When I enable PPR in 14.2.8 I get the following when attempting to build:

"The experimental.ppr preview feature can only be enabled when using the latest canary version of Next.js"

But the docs imply that PPR can be used in Next.JS 14.
https://nextjs.org/docs/app/api-reference/next-config-js/ppr#enabling-ppr-version-14

### Is there any context that might help us understand?

No

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/next-config-js/ppr#enabling-ppr-version-14

Also: https://nextjs.org/docs/messages/ppr-preview contradicts the doc/link above.

**Comment by EfstathiadisD** [comment]
It doesn't support it. Don't know why but it's like that for almost a Year. Pretty solid technique since NextJS 13. We announce stuff but it doesn't work 1 Year later..

**Comment by samcx** [comment]
@boylec Thanks for flagging! Taking a look <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>
