### ISSUE TITLE
Version info in error page shows different font sizes

### ISSUE THREAD

**Issue by mamuso** [vercel/next.js#69813]
### Link to the code that reproduces this issue

https://github.com/mamuso/nextjs-error-font-sizes

### To Reproduce

1. Start the application and visit your localhost. 
2. You should see an error

### Current vs. Expected behavior

You will see that the Next version number and the text after it have different sizes.

<img width="588" alt="CleanShot 2024-09-06 at 19 35 51@2x" src="https://github.com/user-attachments/assets/680a6e66-9c95-4c93-a2e6-279e91131e3c">

I'd expect to see all text in the same font size

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 11
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.22
  pnpm: 9.9.0
Relevant Packages:
  next: 15.0.0-canary.144 // Latest available version is detected (15.0.0-canary.144).
  eslint-config-next: N/A
  react: 19.0.0-rc-7771d3a7-20240827
  react-dom: 19.0.0-rc-7771d3a7-20240827
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@mamuso Thank you for submitting an issue and submitting a PR! Taking a look.
