### ISSUE TITLE
Standalone Output doesn't work with PNPM

### ISSUE THREAD

**Issue by Charismara** [vercel/next.js#69858]
### Link to the code that reproduces this issue

https://github.com/Charismara/nextjs-output-pnpm-issue

### To Reproduce

1. Create a new Project
2. Install dependencies with pnpm
3. Add `output: "standalone"` to your nextjs config file
4. Build Project with pnpm
5. --> Run into the following error:
``` 
Failed to copy traced files for C:\Users\****\IdeaProjects\pnpm-issue\.next\server\pages\_document.js Error: EPERM: operation not permitted, symlink 'C:\Users\****\IdeaProjects\pnpm-issue\node_modules\.pnpm\next@14.2.8_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\next' -> 'C:\Users\****\IdeaProjects\pnpm-issue\.next\standalone\node_modules\next'
```

### Current vs. Expected behavior

An error occurs which prevents the project from building.

The Project builds just fine without the output: `standalone` option set.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32548
  Available CPU cores: 32
Binaries:
  Node: 20.14.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.7.0
Relevant Packages:
  next: 14.2.8 // Latest available version is detected (14.2.8).
  eslint-config-next: 14.2.8
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Output (export/standalone)

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by JesseKoldewijn** [comment]
I've not seen this issue before if I'm gonna be honest. But I'd imagine that this could be a windows specific issue. 

I can take a look at this matter when I'm off work perhaps.

**Comment by JesseKoldewijn** [comment]
Even on windows I wasn't able to reproduce, apart from when I was brute forcing too restrictive directory permissions.

**Comment by Charismara** [comment]
Is there any additional information i could provide to find a workaround for me or make it more reproducable for you?

**Comment by JesseKoldewijn** [comment]
> Is there any additional information i could provide to find a workaround for me or make it more reproducable for you?

It seems to be a local file permission issue. So since this would be related to local setup and not directly related to Next.js I think this would be out of scope. 

But nonetheless, I think one of the easiest workarounds would be to use WSL (Windows Subsystem Linux) which still has its pitfalls but would at least resolve this issue.

**Comment by ezeparziale** [comment]
Run the terminal as an administrator. I tested your repository on my Windows machine, and it worked perfectly.

**Comment by Charismara** [comment]
> Run the terminal as an administrator. I tested your repository on my Windows machine, and it worked perfectly.

That seems to work. Thank you :)
