### ISSUE TITLE
HTTP Error 500.1002 - Internal Server Error

### ISSUE THREAD

**Issue by aiet7** [vercel/next.js#69886]
### Link to the code that reproduces this issue

https://github.com/aiet7/myautopilot_next_src

### To Reproduce

Deployment working fine for the past 5 months, all of a sudden getting internal error because it can not locate the build in wwwroot.  No changes have been made to the deployment process.  Is there an internal issue in terms of Next.js v 13.4.1?

### Current vs. Expected behavior

Not being able to deploy via Azure Web App Service

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.14.1
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.4.1
      eslint-config-next: 13.4.1
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

**Comment by ztanner** [comment]
Hi - this sounds like an issue with the platform you're deploying to (from the looks of it, Azure). If everything is working with `next build` and `next start` you'll probably need to contact their support for troubleshooting steps.

Closing this as it's not actionable by our team.
