### ISSUE TITLE
`<a> ... </a> ` tag is used, instead of `<Link> ... </Link>` tag in basic template generated while creating a new next project.

### ISSUE THREAD

**Issue by shvamabps** [vercel/next.js#69908]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/cool-frost-fxis37?file=%2Fapp%2Fpage.tsx%3A33%2C56

### To Reproduce

1. Create a new nextjs project
2. Open `page.tsx` file
3. Check all the `<a>...</a>` tag occurrences.

### Current vs. Expected behavior

![image](https://github.com/user-attachments/assets/18035d45-225f-4d24-ad5f-a3f7fb380ee5)
Here `<a> </a>` tag is used for links.

Expected

![image](https://github.com/user-attachments/assets/c978d904-c8ff-46d5-bc9e-82b70a13cf47)
But since NextJs provides `Link` Tag for links, why not use that.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024
  Available memory (MB): 15759
  Available CPU cores: 4
Binaries:
  Node: 22.8.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: 9.10.0
Relevant Packages:
  next: 14.2.9 // Latest available version is detected (14.2.9).
  eslint-config-next: 14.2.9
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Here, all the `a` tag occurrences need to be replaced by `Link` tag which can be imported from `import Link from "next/link";`

**Comment by cedric-kany** [comment]
The <Link> tag is only useful for internal pages as Next.js can prefetch that sites. For external links or other links like mailto it doesn't matter which one you use but I tend to use <a> for external and <Link> for internal links.

**Comment by shvamabps** [comment]
According to you, does the usage of Link for different scenarios as you have mentioned, makes any difference in the performance of the web app?

**Comment by samcx** [comment]
> The <Link> tag is only useful for internal pages as Next.js can prefetch that sites. For external links or other links like mailto it doesn't matter which one you use but I tend to use <a> for external and <Link> for internal links.

This is true!

> According to you, does the usage of Link for different scenarios as you have mentioned, makes any difference in the performance of the web app?

Yes it does. You always want to use `<Link>` when navigating within your app, from Page to Page. It's going to do a client-side navigation (SPA-like navigation), versus a whole refresh of the page.

Since this is a non-issue, I will be closing this!
