### ISSUE TITLE
Web components styling not work with CSS Modules

### ISSUE THREAD

**Issue by alkorlos** [vercel/next.js#69924]
### Link to the code that reproduces this issue

https://github.com/alkorlos/nextjs-issue-css-modules-web-components

### To Reproduce

1. Start the application in development (next dev)
2. You can see that the styles haven't been applied to the web component Hello World

### Current vs. Expected behavior

Native web components, such as this one:
```html
<hello-world class="hello-world">
  <template shadowrootmode="open">
    <span part="span">Hello World!</span>
  </template>
</hello-world>
```

Can be styled with similar styles:
```css
.hello-world {
  background: red;
}

.hello-world::part(span) {
  color: green;
}
```

I expect that this should work with Next.js as well.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Enterprise
  Available memory (MB): 16228
  Available CPU cores: 4
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.9 // Latest available version is detected (14.2.9).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

**Comment by samcx** [comment]
@alkorlos Thank you for submitting an issue!

It looks this just works on the latest canary (always make sure to test issues on the latest canary as well).

![CleanShot 2024-09-11 at 15 30 07@2x](https://github.com/user-attachments/assets/31d668b8-f103-4e09-97e4-47dcd3ff1586)

I will be closing this issue in the meantime!
