### ISSUE TITLE
Cannot add dynamic application/json+oembed using app router

### ISSUE THREAD

**Issue by Prushka** [vercel/next.js#70004]
### Link to the code that reproduces this issue

https://github.com/Prushka/photosite

### To Reproduce

NextJS 13+ app router: There's no option to add a header in this format using generateMetadata:
`<link type="application/json+oembed" href="https://....json" />`

See: https://oembed.com/

### Current vs. Expected behavior

I expect to be able to add oEmbed Json as a metadata or header inside a page or layout.
The <Head> component only seems to work in pages route.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Fri Aug 16 19:18:40 PDT 2024; root:xnu-11215.40.42~4/RELEASE_ARM64_T6020
  Available memory (MB): 65536
  Available CPU cores: 12
Binaries:
  Node: 22.8.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.10 // Latest available version is detected (14.2.10).
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by abhi12299** [comment]
what's the issue? I'm able to add the tag and it is showing up in the `head` tag.

**Comment by Prushka** [comment]
> what's the issue? I'm able to add the tag and it is showing up in the `head` tag.

How were you able to add the tag?
The only way I found to get around this issue is to add the link as an icon:

```js
icons: {
        other: {
            rel: 'alternate',
            url: `oembed_url`,
            type: 'application/json+oembed'
        },
    },
```

**Comment by abhi12299** [comment]
Yes, this is what I did too. does this not solve your problem?

**Comment by Prushka** [comment]
> Yes, this is what I did too. does this not solve your problem?

Yes. I only found out this later. I just don't think a link in a header should be in the icon fields. It's more like a hack to me than a solution.
