### ISSUE TITLE
Docs: The explanation for "Dynamic Routes" is incorrect.

### ISSUE THREAD

**Issue by hirotomoyamada** [vercel/next.js#70124]
### What is the documentation issue?

In the "Optional Catch-all Segments", if params is `{}`, can't reach `/shop`. The correct value should be `{ slug: undefined }`.

### Is there any context that might help us understand?

Just need to change the params from `{}` to `{ slug: undefined }`.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#optional-catch-all-segments

**Comment by ijjk** [comment]
Closing per https://github.com/vercel/next.js/pull/70126#pullrequestreview-2307518205
