### ISSUE TITLE
Modal with parallel routes and dynamic routes catch-all segments

### ISSUE THREAD

**Issue by mrneverflatz** [vercel/next.js#70185]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32690
  Available CPU cores: 16
Binaries:
  Node: 18.20.4
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.8 // There is a newer version (14.2.11) available, upgrade recommended!
  eslint-config-next: 14.2.8
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

no example

### What browser are you using? (if relevant)

latest chrome, firefox

### Describe the Bug

the markup is well-rendered with title, but in the browser cant see the title changed, even in inspect element the title tag is dissapear

this happen except in the `/app/page.tsx`

### Expected Behavior

i setup folder structure like this
![image](https://github.com/user-attachments/assets/d994b39d-09b6-4477-91df-f6db6e8d0404)
the idea is to capture searchParams on any levels to popup the modal window by doing this /some-routes?modal=tier&tierId={idTier}&etc...

everything is working fine, i manage to capture the searchParams, but every generateMetaData failed to update title tag in browser

### To Reproduce

1. create parallel routes @modal/default.tsx
- default.tsx just render null
2. create dynamic routes catch-all segments `@modal/[...]/page.tsx
- page.tsx capture all logic to render the modals by get all searchparams send by the main segments

**Comment by samcx** [comment]
@mrneverflatz Please re-open this issue with the other [issue template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) so we have all the information we need to properly diagnose the issue!
