### ISSUE TITLE
Docs: Import React from "react" not added on the manual installation

### ISSUE THREAD

**Issue by ukpagrace** [vercel/next.js#70211]
### What is the documentation issue?

```
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

```
import react isn't added and also the type "npm i --save-dev @types/react" to be installed.

### Is there any context that might help us understand?

When only the code above is used, it throws an error react not found and when react is installed, you also have to install the type as well.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/getting-started/installation

**Comment by YacineBenzo** [comment]
Normally, React 17+ and Next.js don’t need import React from 'react', older TypeScript versions (before v4.1) might still expect it. If you're intending to use Next, then you can choose to use typescript or not.

**Comment by ukpagrace** [comment]
Thanks, I added target for Es5 and that solved it
