### ISSUE TITLE
Module not found: Can't resolve '_http_common'

### ISSUE THREAD

**Issue by kettanaito** [vercel/next.js#70262]
### Link to the code that reproduces this issue

https://github.com/mswjs/msw/issues/2291

### To Reproduce

Please follow the reproduction steps in the linked issue above.

## Current

Next.js throws an error, unable to import a built-in `_http_common` module in Node.js.

## Expectd

Next.js properly imports the built-in module.

### Provide environment information

```bash
Irrelevant, this is a webpack configuration issue.
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Runtime, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

I believe this is caused by the Next's default webpack config not listing `_http_common` in `config.externals`. 

Any thoughts on listing _all_ built-in Node.js modules as external?

```js
{
  // All built-in modules in Node.js must be treated as external.
  externals: require('module').builtinModules
}
```

I'm proposing this because contributors report that adding `_http_common` into `config.externals` helps them. This should be handled on Next's side.

**Comment by vishakha94** [comment]
Facing the same issue with the NextJS and MSW setup. 

<img width="717" alt="Screenshot 2024-09-20 at 12 03 30 PM" src="https://github.com/user-attachments/assets/dc428f71-3136-46dc-a317-fe08d5cb87e0">

**Comment by kettanaito** [comment]
@vishakha94, that's expected since the newest versions of MSW rely on the built-in `HTTPParser` in Node.j to parse outgoing Socket packets. I haven't experienced this issue when working with other frameworks. The `_http_common` import must be configured correctly on Next's side as external because it's a built-in module. Looks like webpack is trying to import it from your `node_modules`, and fails in the process.
