### ISSUE TITLE
icon file don't working in sub route

### ISSUE THREAD

**Issue by Debbl** [vercel/next.js#70345]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:51:54 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.11.0
Relevant Packages:
  next: 14.2.13 // Latest available version is detected (14.2.13).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: export
```

### Which example does this report relate to?

no

### What browser are you using? (if relevant)

chrome 129.0.6668.58

### How are you deploying your application? (if relevant)

netlify

### Describe the Bug

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons
This document. Saying I can set route icon by add a `icon.svg` file on app directory, but it's not working, so I manually set icons.
```ts
export const metadata: Metadata = {
  title: "code-diff",
  description: "a code-diff tool for comparing code",
  icons: ["code-diff/icon.svg"],
};
```
on `next@14.2.5` https://github.com/Debbl/tools.aiwan.run/tree/068d4e99744c12d78b83be78f05f4a885e4be3a0 is working

when I update next to 14.2.13, the icon link don't generate.
https://github.com/Debbl/tools.aiwan.run/tree/34c355d98075495f852ed39ccb18297d36530e6c

### Expected Behavior

Correctly generate website icons based on icon files

### To Reproduce

working https://github.com/Debbl/tools.aiwan.run/tree/068d4e99744c12d78b83be78f05f4a885e4be3a0
no working https://github.com/Debbl/tools.aiwan.run/tree/34c355d98075495f852ed39ccb18297d36530e6c

**Comment by samcx** [comment]
@Debbl Please also use the correct [issue template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml)!
