### ISSUE TITLE
Docs: Pages functions used as examples for App directory

### ISSUE THREAD

**Issue by quick007** [vercel/next.js#70370]
### What is the documentation issue?

App content still talks about pages only apis, i.e. `getStaticProps`.

### Is there any context that might help us understand?

n/a

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/module-not-found

**Comment by samcx** [comment]
@quick007 Although the examples are primarily using Pages Router examples, the error still applies to App Router (e.g., `import useSWR from 'swr'`).
