### ISSUE TITLE
`revalidatePath()` does not revalidate layout when followed by `redirect()`

### ISSUE THREAD

**Issue by tom-sherman** [vercel/next.js#70483]
### Link to the code that reproduces this issue

https://github.com/tom-sherman/next-redirect-revalidate-bug

### To Reproduce

1. Start the application
2. Increase the counter to set a value in the cookie
3. Press reset

### Current vs. Expected behavior

Current behaviour:

Layout is not revalidated/refreshed

Expected behaviour:

Layout to be revalidated

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Wed Jul 31 20:49:39 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.9.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 9.1.0
Relevant Packages:
  next: 15.0.0-canary.168 // Latest available version is detected (15.0.0-canary.168).
  eslint-config-next: N/A
  react: 19.0.0-rc-5d19e1c8-20240923
  react-dom: 19.0.0-rc-5d19e1c8-20240923
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

### Additional context

This works on v15 RC but broken on latest canary.

**Comment by mateuszaliyev** [comment]
I was about to create an issue myself when I found this one. This bug has been a source of many problems for us. It occurs only when calling `redirect` after `revalidatePath` or `revalidateTag`.
