### ISSUE TITLE
Next.js 14.2.x bundler mangles `\\b` in template literals

### ISSUE THREAD

**Issue by silas** [vercel/next.js#70500]
### Link to the code that reproduces this issue

https://github.com/silas/nextjs-issue-70500.git

### To Reproduce

1. `npm install`
2. `npm run build`

### Current vs. Expected behavior

`npm run build` should complete successfully.

This is the difference between a working and non-working build:

```patch
$ git diff 592f5ba...0a0e772
diff --git a/src/app/demo.ts b/src/app/demo.ts
index cc8e1f1..f8c8f45 100644
--- a/src/app/demo.ts
+++ b/src/app/demo.ts
@@ -1,3 +1,3 @@
-const demo = '{"match":"\\b"}';
+const demo = `{"match":"\\b"}`;

 export { demo };
```

The working version produces:

```json
{"match":"\\b"}
```

And the non-working version produces:

```json
{"match":"\\\b"}
```

You can try the working build by running:
1. `git checkout 592f5ba`
2. `npm run build`

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:31 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: 9.11.0
Relevant Packages:
  next: 14.2.13 // Latest available version is detected (14.2.13).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Webpack

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

This issue was uncovered in https://github.com/shikijs/shiki/issues/784

It's possible this is related to webpack, but the upstream default settings for `webpack@4` and `webpack@5` don't cause this issue.

#### Versions

It looks like this stopped working in [14.2.0-canary.66...14.2.0-canary.67](https://github.com/vercel/next.js/compare/v14.2.0-canary.66...v14.2.0-canary.67):

```
14.1.4            working
14.2.0-canary.66  working
14.2.0-canary.67  non-working
14.2.0            non-working
14.2.13           non-working
14.2.14           non-working
```

**Comment by fuma-nama** [comment]
Some news, I've tested on Next.js 15 canary, it works as expected. It seems like they fixed it on canary but is not ported to 14.

**Comment by ztanner** [comment]
Hi,

Thanks for the report! I can confirm this is fixed in Next@15. Please let us know if you're still having any issues after upgrading.
