### ISSUE TITLE
Next/Link is prefetching the current page being viewed

### ISSUE THREAD

**Issue by dannytlake** [vercel/next.js#70535]
### Link to the code that reproduces this issue

https://github.com/dannytlake/next-prefetch-bug-current-route

### To Reproduce

Start in production mode, view network tab.
- `pnpm build && pnpm start`
- visit http://localhost:3000
- open network tab
- Click on the Page2 link.
- Refresh the browser 
- See the prefetch request to `page2_rsc` - this should not be occurring

![image](https://github.com/user-attachments/assets/8fe77b7b-91f3-44ea-a416-958c42868947)

### Current vs. Expected behavior

Current: The Next/Link component is prefetching the current page being viewed, unnecessarily consuming network + cpu resources

Expected: The Next/Link component should not prefetch links pointing to the current page being viewed.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.16.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 8.15.9
Relevant Packages:
  next: 15.0.0-canary.171 // Latest available version is detected (15.0.0-canary.171).
  eslint-config-next: 14.2.7
  react: 19.0.0-beta-26f2496093-20240514
  react-dom: 19.0.0-beta-26f2496093-20240514
  typescript: 5.5.4
Next.js Config:
```

### Which area(s) are affected? (Select all that apply)

Navigation, Performance

### Which stage(s) are affected? (Select all that apply)

next start (local), Vercel (Deployed)

### Additional context

This bug also occurs in next@14 (v14.2.13 at time of writing)

**Comment by samcx** [comment]
@dannytlake Thank you for submitting an issue!

Our team is already looking to fix this issue <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>

**Comment by dannytlake** [comment]
Thank you @samcx + @ztanner !
