### ISSUE TITLE
Turbo is unable to compile source with pdfjs

### ISSUE THREAD

**Issue by Matts** [vercel/next.js#70555]
### Link to the code that reproduces this issue

https://github.com/Matts/pdfjs-and-turbo-incompat

### To Reproduce

See https://github.com/mozilla/pdf.js/discussions/18804 & https://github.com/vercel/turborepo/issues/9195

Create a nextjs + turbo project
Follow the example installation at https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples
You will receive a compilation error from turbopack (see image below)
it seems that turbo pre-interprets import statements and tries to resolve them. I see that there is a webpack ignore statement, possibly there has to be a similar statement for turbo

![image](https://github.com/user-attachments/assets/3d9c689f-666c-44b0-9c13-55db5a374e8c)

### Current vs. Expected behavior

Currently, the server crashes even though everything should only be run on client, furthermore the actual piece of code is never even referenced or called.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.7.0
  npm: 10.1.0
  Yarn: N/A
  pnpm: 8.6.10
Relevant Packages:
  next: 14.2.13 // Latest available version is detected (14.2.13).
  eslint-config-next: 14.2.13
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by timneutkens** [comment]
This has already been fixed. Please verify with `next@canary`. Thanks!

**Comment by Matts** [comment]
Hi, after some tinkering I got it working on next@canary! Thanks. Will this change get backported to nextjs 14? (as we kinda need this fix)

**Comment by timneutkens** [comment]
Unfortunately we can't backport these changes to 14.x because 14 holds a much earlier version of Turbopack. The release candidate for Turbopack is part of Next.js 15 release candidate: https://nextjs.org/blog/next-15-rc. The upcoming 15 release candidate 2 will mark Turbopack for development as stable.

Going to close this issue as it's fixed already 👍

**Comment by gruckion** [comment]
Would be nice if you link the bugs to the PRs so I can review the fix
