### ISSUE TITLE
Fast Refresh always triggers a full reload with Chinese characters

### ISSUE THREAD

**Issue by rquanx** [vercel/next.js#70586]
### Link to the code that reproduces this issue

https://github.com/rquanx/next-fast-refresh-error

### To Reproduce

1.start application with next dev --turbo
2.create client component with any chinese characters，render in page
3.Any changes in the client component will always trigger a full reload

### Current vs. Expected behavior

current: fast refresh full reload
expected: fast refresh would not full reload

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home China
  Available memory (MB): 32462
  Available CPU cores: 20
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 9.10.0
Relevant Packages:
  next: 14.2.13 // Latest available version is detected (14.2.13).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by mischnic** [comment]
I could reproduce it with your code sample. Upgrading to the latest canary version (`pnpm add next@canary`) appears to fix it.

**Comment by rquanx** [comment]
> I could reproduce it with your code sample. Upgrading to the latest canary version (`pnpm add next@canary`) appears to fix it.

I know canary is available, but the canary version is stable enough to go into production

**Comment by rquanx** [comment]
> I could reproduce it with your code sample. Upgrading to the latest canary version (`pnpm add next@canary`) appears to fix it.

@mischnic I know canary is available, but the canary version is stable enough to go into production
