### ISSUE TITLE
`<Script />` components do not resolve in consistent order

### ISSUE THREAD

**Issue by GabenGar** [vercel/next.js#70709]
### Link to the code that reproduces this issue

https://github.com/GabenGar/repros/tree/main/nextjs/script-inconsistent-load-order

### To Reproduce

Steps are in the `README.md`

## Current
`<Script />` elements declared like this:
```tsx
<body>
  <Script defer src="alpha.js" />
  <Script defer src="beta.js" />
  <Script defer src="gamma.js" />
  <Script defer src="delta.js" />
</body>
``` 
Do not behave more-less the same as:
```html
<body>
  <script defer src="alpha.js" ></script>
  <script defer src="beta.js" ></script>
  <script defer src="gamma.js" ></script>
  <script defer src="delta.js" ></script>
</body>
```

As in they run in an undefined order.

## Expected
`<Script />` elements declared like this:
```tsx
<body>
  <Script defer src="alpha.js" />
  <Script defer src="beta.js" />
  <Script defer src="gamma.js" />
  <Script defer src="delta.js" />
</body>
``` 
Behave more-less the same as:
```html
<body>
  <script defer src="alpha.js" ></script>
  <script defer src="beta.js" ></script>
  <script defer src="gamma.js" ></script>
  <script defer src="delta.js" ></script>
</body>
```

As in run in the order they are declared after NextJS hydration step. 

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10
Binaries:
  Node: 20.9.0
Relevant Packages:
  next: 14.2.13
  eslint-config-next: 14.2.13
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Documentation, Script (next/script)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

I am converting a pre-modules javascript codebase to react. The stack is standard html/js/css fare and javascript files are written in a way that they call the functions, declared in other files, from global scope, so their load order is important.
The html looked like this:
```html
<!DOCTYPE html>
<html>
  <head>
    ...
  </head>
  
  <body>
    ...
    <script src="alpha.js" ></script>
    <script src="beta.js" ></script>
    <script src="gamma.js" ></script>
    <script src="delta.js" ></script>
  </body>
</html>
```

The first thing I did is changing like this:
```html
<!DOCTYPE html>
<html>
  <head>
    ...
    <script defer src="alpha.js" ></script>
    <script defer src="beta.js" ></script>
    <script defer src="gamma.js" ></script>
    <script defer src="delta.js" ></script>
  </head>
  
  <body>
    ...
  </body>
</html>
```

And that worked without (obvious) breaks. So it's basically an ad-hoc SPA, down to having a single HTML file.

The next step is I want to convert the markup to JSX without changing the behaviour. It wasn't trivial because the html already contained inline event callbacks which referred to global symbols from those scripts, but after some work I ended up writing a ES module `epsilon`, which basically assigns all the callbacks on the first react render AFTER all those scripts presumably ran. 
```tsx
import { useEffect } from "react";
import { initCallbacks } from "#epsilon";

export default function IndexPage() {
  useEffect(() => initCallbacks(), []);

  return <>...</>
}
```

Now I have vanilla scripts `alpha`/`beta`/`gamma`/`delta` (in this order of running) which should not be sent through bundler as they are riddled with side effects and the module `epsilon` which is bog-standard ESM running in react lifecycle.

The only problem I have is I don't know how to coordinate those two groups within nextjs codebase. At first I tried `<script>` elements within [custom document](https://nextjs.org/docs/pages/building-your-application/routing/custom-document), since it's a logical place for them to be in, considering the inputs.
```tsx
import { Html, Head, Main, NextScript } from 'next/document'
 
export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body>
        <Main />
        <script defer src="alpha.js" ></script>
        <script defer src="beta.js" ></script>
        <script defer src="gamma.js" ></script>
        <script defer src="delta.js" ></script>
        <NextScript />
      </body>
    </Html>
  )
}
```
But it instantly gets hit with hydration error, which makes sense since they run and transform DOM before NextJS hydration kicks in. I have to have them somewhere in the `_app` or `index` page and it looks like [`<Script />`](https://nextjs.org/docs/pages/api-reference/components/script) fits the bill, so I ended up with this:
`/pages/index.tsx`
```tsx
import { useEffect } from "react";
import { initCallbacks } from "#epsilon";

export default function IndexPage() {

  return (
    <>
      ...
      <Script defer src="alpha.js" />
      <Script defer src="beta.js" />
      <Script defer src="gamma.js" />
      <Script defer src="delta.js" onLoad={() => initCallbacks()} />
    </>
  )
}
```

And that how I arrived at the current problem, since it only seldom works.

**Comment by abhi12299** [comment]
Adding more context here for reference: https://javascript.info/script-async-defer#:~:text=Deferred%20scripts%20keep%20their%20relative%20order%2C%20just%20like%20regular%20scripts.

The relative order of scripts has to be ensured by the browser.

**Comment by abhi12299** [comment]
@GabenGar can you provide a simpler reproduction? I tried to repro this here: https://codesandbox.io/p/devbox/xgh4tg

It seems that this is working fine on both dev and start commands.

**Comment by GabenGar** [comment]
@abhi12299 
Actually no, the size of scripts and their amount, along with giant markup, might be contributing to the race condition. Also your "repro" runs in `app` folder instead of `pages` in mine (surely you could've picked up on this fact) and the scripts . This might or might not be relevant to how `<Script />` behaves.

**Comment by abhi12299** [comment]
Updated the repro to use `pages` directory. The `Script` tag behaves differently now - the order is only guaranteed when the `strategy` is set to `beforeInteractive`. In all other cases, the order is seemingly random, despite the fact that in the HTML, the script tags are placed in the right place.

**Comment by abhi12299** [comment]
@GabenGar maybe open a new issue with https://codesandbox.io/p/devbox/xgh4tg as the repro example - i think it replicates your issue with minimal code

**Comment by abhi12299** [comment]
Also, this is working fine when using app directory: https://codesandbox.io/p/devbox/3q537j

**Comment by GabenGar** [comment]
> the order is only guaranteed when the strategy is set to `beforeInteractive`

Isn't that basically running vanilla scripts, so would incur hydration errors the same way using `<script>` tags in the `_document`?
Not using `app` router either because I plan to have client-side dynamic route segments which aren't supported atm.
Though I found the solution and it came down conditionally rendering `<Script />` components on client only, which seems to load them in order (at least I don't get any hydration and global symbol access errors):
```tsx
import { useEffect, useState } from "react";
import { initCallbacks } from "#epsilon";

export default function Page() {
  const [isClient, switchClient] = useState(false);
  
  useEffect(() => {
    switchClient(true);
  }, []);
  
  return (
    <>
      {isClient && (
        <>
          <Script defer src="alpha.js" ></Script>
          <Script defer src="beta.js" ></Script>
          <Script defer src="gamma.js" ></Script>
          <Script defer src="delta.js" onLoad={() => initCallbacks()} ></Script>
        </>
      ) }
    </>
  )
}
```
