### ISSUE TITLE
`generateMetadata` is not called anymore if it is in `page.tsx`, it's called only from `layout.tsx` when upgrading from v14.2.7 to v14.2.8, making all the pages dynamic titles to disappear.

### ISSUE THREAD

**Issue by RazvanRauta** [vercel/next.js#70717]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/practical-silence-f2sz85?workspaceId=a8fd7a94-21d9-4864-97fb-6ae7e1b980d5

### To Reproduce

1. Upgrade nextjs to `v14.2.8`

2. Create some pages with the following folder structure:
```
| [ lang ]
│   layout.tsx <-------  generateMetadata () =>   return { title: "Layout" };
│
└───( group )
|   group-layout.tsx
|
│   └───page 1
│       │   page.tsx         <-------  generateMetadata () =>   return { title: "Page 1" };
│       │   page-content.txt
|
│   └───page 2
│       │   page.tsx        <-------  generateMetadata () =>   return { title: "Page 2" };
│       │   page-content.txt

```
3. The title from `layout.tsx` is shown, not the one from `page.tsx`. If the `generateMetadata` function is deleted from `layout.tsx`, no title is shown in the browser tab. 

4. Downgrade nextjs to `v14.2.7` and the titles from `page.tsx` are back without any changes.

### Current vs. Expected behavior

`generateMetadata` should work like before v14.2.8

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: arm64
  Version: #1 SMP Wed Jul 17 10:51:09 UTC 2024
  Available memory (MB): 7839
  Available CPU cores: 11
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.1.0
Relevant Packages:
  next: 14.2.8 // There is a newer version (14.2.14) available, upgrade recommended! 
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Metadata

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

### Additional context

The bug was introduced in `v14.2.8`.

**Comment by samcx** [comment]
@RazvanRauta The behavior in 14.2.8 is the correct one—you should not be able to `generateMetadata` in a Client Component → https://nextjs.org/docs/app/api-reference/functions/generate-metadata.

What's interesting is that you split up the `generateMetadata` and the Client Component, so Next.js was not able detect that `generateMetadata` was in a Client Component.

If you combine them →
![CleanShot 2024-10-02 at 12 40 38@2x](https://github.com/user-attachments/assets/af23e517-86a9-442b-a879-05be841f04cd)

**Comment by samcx** [comment]
Closing for now, but let me know if you have any further questions or concerns!
