### ISSUE TITLE
Page query change via <Link> does not trigger loading.tsx or suspense

### ISSUE THREAD

**Issue by moltco** [vercel/next.js#70727]
### Link to the code that reproduces this issue

https://github.com/moltco/nextjs-loading-suspense

### To Reproduce

1. Start the application in development `next dev`, open `http://localhost:3000`
2. On the home page, click the "Click Here to Load Data". The initial loading.tsx file will show "LoadData loading.tsx..." message.
3. When on the LoadData page, click any of the Page1, Page2, Page3 links which will navigate to the same page, just change query to ?page=1, 2, 3.
4. The page loads (with delay) but the loading.tsx does not kick in and neither does the Suspense
5. Now try manually adding ?page=2 in the browser nav bar and the loading.tsx will kick in as expected.

### Current vs. Expected behavior

Page query parameter change via <Link> component should trigger at least loading.tsx, ideally should trigger the Suspense as well.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 196316
  Available CPU cores: 32
Binaries:
  Node: 20.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.14 // Latest available version is detected (14.2.14).
  eslint-config-next: 14.2.14
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation, Pages Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

I tested against  next 15.0.0-canary.176 but got the same result.

**Comment by ztanner** [comment]
Hi @moltco,

React's default behavior is to not show a Suspense boundary for a tree if it has already triggered a fallback. In this case, when you first navigate to `/LoadData`, the fallback is triggered. Subsequent requests to `?page2` or `?page3` won't re-trigger that Suspense boundary unless you explicitly tell React to do so.

One way to do that in this case would be to create a `layout.tsx` for your `LoadData` page that re-keys the children based on the value that you want to trigger the Suspense boundary, e.g.:

```
"use client";

import { useSearchParams } from "next/navigation";
import React from "react";

export default function Layout({ children }: { children: React.ReactNode }) {
  const searchParams = useSearchParams();
  console.log(searchParams);
  return (
    <React.Fragment key={searchParams.get("page")}>{children}</React.Fragment>
  );
}
```
