### ISSUE TITLE
dangerouslyAllowSVG is making app crash  when url do not have a .svg ending

### ISSUE THREAD

**Issue by Abolfazl-ghodrati-k** [vercel/next.js#70760]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2
  Available memory (MB): 9811
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.22
  pnpm: 6.35.1
Relevant Packages:
  next: 14.2.5 // There is a newer version (14.2.14) available, upgrade recommended! 
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
 ⚠ There is a newer version (14.2.14) available, upgrade recommended! 
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which example does this report relate to?

svg

### Describe the Bug

im using api.dicebear as a service to provide gravatars base on users name.
the issue here is that next is checking config and if dangerouslyAllowSVG is true and src url ends with .svg then do something.

i believe since my url do not support the format and im setting dangerouslyAllowSVG in config my app crashes and some of tailwind classes are not translated or even some jsx content gets disapperared.

for example here is an url with my gravatar svg.

https://api.dicebear.com/9.x/initials/svg?seed=Ahmad+Mousavi

### Expected Behavior

it should simply render svg and remove any optimization in next image

### To Reproduce

just pase provided url in next image src and set allowsvg config in  next config

**Comment by samcx** [comment]
@Abolfazl-ghodrati-k Please make sure to use the correct [issue template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) so we have the needed information for triaging the issue!
