### ISSUE TITLE
Docs: All images are broken

### ISSUE THREAD

**Issue by zachwolf** [vercel/next.js#70915]
### What is the documentation issue?

All images are failing to load with

```
400: BAD_REQUEST
Code: INVALID_IMAGE_OPTIMIZE_REQUEST
```

<img width="1624" alt="Screenshot 2024-10-07 at 11 09 39 AM" src="https://github.com/user-attachments/assets/31c9975d-26ea-455f-84b3-8a39a17382ac">
<img width="1624" alt="Screenshot 2024-10-07 at 11 09 51 AM" src="https://github.com/user-attachments/assets/34a16386-5bad-4f92-a3a3-74c798736193">
<img width="1624" alt="Screenshot 2024-10-07 at 11 13 33 AM" src="https://github.com/user-attachments/assets/8dda10d3-d194-4a8c-87b9-476ed23af727">
<img width="1624" alt="Screenshot 2024-10-07 at 11 15 19 AM" src="https://github.com/user-attachments/assets/6103a7e5-46aa-41b2-bd8c-5fe470f56be9">
<img width="1624" alt="Screenshot 2024-10-07 at 11 15 25 AM" src="https://github.com/user-attachments/assets/6a003de7-88cb-462b-b376-83705c3c2284">

### Is there any context that might help us understand?

Tested this on two different macs, both Chrome and Safari

**Comment by samcx** [comment]
@zachwolf 

This has already been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture>—thank you for submitting an issue!
