### ISSUE TITLE
Docs: Error 404. Page not found when I go to https://nextjs.org/docs/messages/react-hydration-error

### ISSUE THREAD

**Issue by TheCukitoDev** [vercel/next.js#70923]
### What is the documentation issue?

When I go to https://nextjs.org/docs/messages/react-hydration-error i see this error: 
![image](https://github.com/user-attachments/assets/c9dd362e-6772-4fe3-9a7f-44e65c376f80)

### Is there any context that might help us understand?

I only know i were working fine and i refreshed the page and it appeared the Canary Release docs and the v13 docs appart to the v14 docs

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/messages/react-hydration-error

**Comment by Nilomiranda** [comment]
@TheCukitoDev if you really need to access the content of the page, you can check the markdown [here](https://github.com/vercel/next.js/blob/37ea26bde0ed98e1186f4ef05d2c8f71ddb636e5/errors/react-hydration-error.mdx)

**Comment by TheCukitoDev** [comment]
Don't worry i went to web archive to see It. I postee this to see why is It causing this

**Comment by Nilomiranda** [comment]
This can be closed, page is back.
