### ISSUE TITLE
Docs: Dynamic Server Usage Error on Build with Missing Documentation Link

### ISSUE THREAD

**Issue by SlavenDj** [vercel/next.js#70935]
### What is the documentation issue?

When running pnpm build, the build completes successfully, but I receive the following error message:
Dynamic server usage: Route /api/fetch-grants couldn't be rendered statically because it used `request.url`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error

The error points to a page on Next.js documentation, but the link provided (https://nextjs.org/docs/messages/dynamic-server-error) does not exist, and I am unable to find any further guidance.

### Is there any context that might help us understand?

No

**Comment by Marukome0743** [comment]
I can see https://nextjs.org/docs/messages/dynamic-server-error after Next.js v15.0.0 release.
Would you check it?

**Comment by SlavenDj** [comment]
Yes there is.
