### ISSUE TITLE
Some node:crypto APIs cause TypeError during build with Docker

### ISSUE THREAD

**Issue by Marukome0743** [vercel/next.js#71015]
### Link to the code that reproduces this issue

https://github.com/Marukome0743/node-crypto

### To Reproduce

1. Clone the above reproduction repo.
2. Run `docker build .`
3. The below error will happen

> $ next build
> unhandledRejection 16 |     const nodeCrypto = require('node:crypto');
> 17 |     // require('node:crypto').getRandomValues is an alias for
> 18 |     // crypto.getRandomValues which is extended in web-crypto.tsx
> 19 |     // require('node:crypto').randomUUID is not an alias for crypto.randomUUID
> 20 |     const _randomUUID = nodeCrypto.randomUUID;
> 21 |     nodeCrypto.randomUUID = function randomUUID() {
>          ^
> TypeError: Attempted to assign to readonly property.
>     at /usr/src/app/node_modules/next/dist/server/node-environment-extensions/node-crypto.js:21:5
>      at /usr/src/app/node_modules/next/dist/server/node-environment.js:11:1
>      at /usr/src/app/node_modules/next/dist/build/utils.js:141:1
>      at /usr/src/app/node_modules/next/dist/build/swc/options.js:28:7
>      at /usr/src/app/node_modules/next/dist/build/swc/index.js:76:7

### Current vs. Expected behavior

No error

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  Available memory (MB): 15901
  Available CPU cores: 8
Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: N/A
  pnpm: 9.6.0
Relevant Packages:
  next: 15.0.0-canary.181 // Latest available version is detected (15.0.0-canary.181).
  eslint-config-next: N/A
  react: 19.0.0-rc-2d16326d-20240930
  react-dom: 19.0.0-rc-2d16326d-20240930
  typescript: 5.3.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

I checked the changes at #70939.

https://github.com/vercel/next.js/blob/6ae92cc93920a639be81eaec59d0bee393785748/packages/next/src/server/node-environment-extensions/node-crypto.tsx#L15-L25

`nodeCrypto.randomUUID` type is `UUID` of string.
In addition, `use strict` forbidden assign primitive value.
Thus TypeError happens.
`nodeCrypto.randomInt` has also an error due to number type.

There is no error if I remove `"use strict"` line from node-crypto.js in the dist folder. 

I am hosting via Docker, and if I build in my local machine, I cannot reproduce the same issue.

I tested my reproduction against different canary releases, and the first one that introduced the bug was [15.0.0-canary.181](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.181), since reverting to [15.0.0-canary.179](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.179) works.

**Comment by wottpal** [comment]
Same issue here

**Comment by gnoff** [comment]
Thanks. We landed a change in the latest canary that detects when certain APIs are called when an experimental flag is on but it seems in some environments this patch is incompatible. Will fix today and include in the next canary release

**Comment by ijjk** [comment]
Hi, this issue seems to be specific to bun which isn't officially compatible so ideally you re-open this issue with bun so they are aware of the incompatibility with node's handling.

**Comment by wottpal** [comment]
@ijjk What do you mean by bun isn't officially compatible? https://vercel.com/changelog/bun-install-is-now-supported-with-zero-configuration

@gnoff Happy to open a new issue, or did you already fix it anyways?

**Comment by gnoff** [comment]
Patches that fail to install will warn when this lands: https://github.com/vercel/next.js/pull/71043

This is an example where Bun is incompatible with Node.js in a way that Next relies upon so if you run Next.js with bun instead of node you may get inconsistent results. In this case the patches only affect an experimental flag however in the future we expect this to become default framework behavior so for bun to be compatible with Next.js and vice versa there will need to be some way to achieve in Bun what we do in Node.js.

There are likely other ways in which Next.js is not fully Bun compat in that Next.js is designed and tested against Node.js not Bun.

**Comment by Marukome0743** [comment]
I confirmed just show console.error instead of throwing error with [15.0.0-canary.182](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.182).
I appreciate nice patch!
