### ISSUE TITLE
Navigating with parallel routes not being detected on route path.

### ISSUE THREAD

**Issue by alexfoxy** [vercel/next.js#71011]
### Link to the code that reproduces this issue

https://github.com/alexfoxy/nextgram-main

### To Reproduce

1. Start the application
2. Go to localhost:3000/users
3. Press on a block, then press the "x" to go back to "/users". This works as expected.
4. Open a new tab, go to localhost:3000.
5. Press on a block, opens the modal, but when you press "x" the route changes back to "/" but the modal remains visible.

### Current vs. Expected behavior

Current behaviour shown below. The expected behaviour works on the "/users" route, but fails on the "/" route. 
https://github.com/user-attachments/assets/8e10a788-0d57-4beb-97c9-03db9e8f0590

Current behaviour: When the route is updated, the modal does not hide.
Expected behaviour: When the route is updated the modal should hide.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:12 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 3.6.4
  pnpm: 9.12.1
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: N/A
  react: 19.0.0-rc-fb9a90fa48-20240614
  react-dom: 19.0.0-rc-fb9a90fa48-20240614
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ztanner** [comment]
Hi, thanks for the report. See my comment [here](https://github.com/vercel/next.js/issues/66502#issuecomment-2147971523) to understand this behavior a bit better. The gist is that you’ll need to make sure there’s a parallel route that matches the / page (and returns `null`), otherwise it will remain mounted on soft navigations.

**Comment by alexfoxy** [comment]
@ztanner Thanks I have resolved it following your other comments suggestion.
