### ISSUE TITLE
redux example double `use client`

### ISSUE THREAD

**Issue by andrevenancio** [vercel/next.js#71085]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
not relevant
```

### Which example does this report relate to?

with-redux

### Describe the Bug

Introduced in [this PR](https://github.com/vercel/next.js/commit/7d4821de6f44b9356318886a6e899c96fe2910c3) there are two "use client" in https://github.com/vercel/next.js/blob/7d4821de6f44b9356318886a6e899c96fe2910c3/examples/with-redux/app/components/Nav.tsx

### Expected Behavior

not relevant

### To Reproduce

not relevant

**Comment by lumirlumir** [comment]
It is fixed in the latest canary release.

https://github.com/vercel/next.js/blob/canary/examples/with-redux/app/components/Nav.tsx
