### ISSUE TITLE
Can't create `/sitemap` route in canary

### ISSUE THREAD

**Issue by darthmaim** [vercel/next.js#71119]
### Link to the code that reproduces this issue

https://github.com/darthmaim-reproductions/vercel-next.js-71119

### To Reproduce

1. Start the application with `npm run dev`
2. Visit http://localhost:3000/sitemap
3. Observe 404 even though the route exists

### Current vs. Expected behavior

Currently it is not possible to create a /sitemap route in the latest canary versions, even though I am not using any features from https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap (like `sitemap.ts`/`generateSitemaps`/...).

This should just be a normal route.

Renaming the route to anything else (for example `site-map`) makes the route work.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  Available memory (MB): 15953
  Available CPU cores: 8
Binaries:
  Node: 22.5.1
  npm: 10.8.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-rc.0 // Latest available version is detected (15.0.0-rc.0).
  eslint-config-next: 15.0.0-rc.0
  react: 19.0.0-rc-f994737d14-20240522
  react-dom: 19.0.0-rc-f994737d14-20240522
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

This was probably broken by #66477 (cc @huozhi) in https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.24, because this is still working in https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.23.

**Comment by darthmaim** [comment]
I know about those features (and linked to it in my issue description). But I don't want to use any of the Next.js sitemap features, I just want to have a normal route at `/sitemap`.

**Comment by 1chooo** [comment]
> I know about those features (and linked to it in my issue description). But I don't want to use any of the Next.js sitemap features, I just want to have a normal route at `/sitemap`.

You are right, sorry that I provide you the wrong answer.
