### ISSUE TITLE
Use Set-Cookie header instead of x-middleware-set-cookie

### ISSUE THREAD

**Issue by robinvandenb** [vercel/next.js#71110]
### Link to the code that reproduces this issue

https://github.com/robinvandenb/next-middleware-cookies

### To Reproduce

1. Install ['iron-session'](https://github.com/vvo/iron-session/tree/main)
2. Try to save any information to the session in `middleware.ts`
```typescript
const session = await getIronSession<SessionData>(request, response, sessionOptions);
session.user = 'John Doe';
await session.save();

return response;
```
3. Access the session in the `page.tsx` through the `cookies()` method
```typescript
const session = await getIronSession<SessionData>(cookies(), sessionOptions);
console.log({ session }); // { session: {} } on first load.
```

### Current vs. Expected behavior

**Current behaviour**
'iron-session' writes the session data safely and correctly to a `Set-Cookie` header available on the response. 
cookies() does not pick up `Set-Cookie` header, and thus the session is not found.

After testing around a little bit. I see that `iron-session` explicitly writes to the `Set-Cookie` header as other NodeJS servers would. Meanwhile, Next expects the cookie to be written as follows: `response.cookies.set(name, value)` thus not following the standard procedure and writes that cookie away to a `X-Middleware-Set-Cookie` header, which in its term is found by `cookies()` cfr. #49442 

**Expected behaviour**
`cookies()` also picks up any value from the `Set-Cookie` header that was written in the middleware. Enabling the session to be written correctly and available on the first render.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 18.20.4
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.2.15 // Latest available version is detected (14.2.15).
  eslint-config-next: 13.5.6
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Middleware

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Other (Deployed)

**Comment by ztanner** [comment]
Hi @robinvandenb -- Next.js middleware relies on manipulation of response cookies via `NextResponse.cookies` which has a `set` property on it.  This is described in the ["Using Cookies"](https://nextjs.org/docs/canary/app/building-your-application/routing/middleware#using-cookies) section of the middleware documentation>

We use a proxy to track `set` requests to this cookies object and do the appropriate plumbing to provide it to `cookies()` in the same request.

It seems the `save` method of `iron-session` explicitly appends the `set-cookie` response header: https://github.com/vvo/iron-session/blob/f5ac7e56cfa41cedddacf272614dbd25731a30ac/src/core.ts#L189

This will still work in that it'll set the cookie in the response, but the additional conveniences around immediately propagating the cookies to the `cookies()` API will be lost, as you're observing.

One thing you could do to work around this is read the cookies that iron-session sets on your `NextResponse` and manually append those, for example:

```ts
import { getIronSession } from "iron-session";
import { NextRequest, NextResponse } from "next/server";
import { SessionData, sessionOptions } from "./config/authentication";
import { parseSetCookie } from "@edge-runtime/cookies";

export default async function middleware(request: NextRequest) {
  const response = NextResponse.next();
  const session = await getIronSession<SessionData>(
    request,
    response,
    sessionOptions
  );
  session.user = "John Doe";
  await session.save();

  const setCookieResponse = response.headers.get("set-cookie");
  const { name, value } = parseSetCookie(setCookieResponse);

  response.cookies.set(name, value);

  return response;
}
```

I'll be closing this as it's not currently something we're able to address in Next.js.
