### ISSUE TITLE
Docs: Issue with Next Conf banner visibility in the right-hand menu

### ISSUE THREAD

**Issue by Magnarius** [vercel/next.js#71133]
### What is the documentation issue?

Issue with Next Conf banner visibility in the right-hand menu

### Is there any context that might help us understand?

I encountered a problem with the visibility of the Next Conf banner in the right-hand menu on the documentation page: [API Reference - Image component](https://nextjs.org/docs/pages/api-reference/components/image).

### Problem Description:
- When there are many elements in the right-hand menu, the Next Conf banner is not visible.
- If I scroll down to the footer, the banner becomes visible, but it overflows out of the menu block due to the max-height restriction and overlaps the footer content.
### My screen resolution:
1470 x 956 pixels.

This issue may affect users with similar screen resolutions or smaller screens when there is a long list of items in the right-hand menu.

Thank you for looking into this!

![image](https://github.com/user-attachments/assets/97a9d41a-8ffa-4eca-87c9-ca7c7514c855)
<img width="1448" alt="Снимок экрана 2024-10-11 в 09 15 17" src="https://github.com/user-attachments/assets/db56fa1b-6adf-42c0-995d-2a791eb5b13d">

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/api-reference/components/image

**Comment by samcx** [comment]
@Magnarius Thank you for sharing! We are already tracking this internally, so will be closing this in the meantime.
