### ISSUE TITLE
`Cannot find module 'unknown'` with absolute imports in `turbo`

### ISSUE THREAD

**Issue by wingsofovnia** [vercel/next.js#71141]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/blazing-dew-qcg68h?workspaceId=66389b18-cf6e-4f9d-a33d-4e2051cd2f24

### To Reproduce

1. Try to `import` a file dynamically with `@`-absolute import

```
export async function loadMessages(locale: Locale): Promise<AbstractIntlMessages> {
  try {
    return (await import(`@/i18n/${locale.location}`)).default
  } catch (e) {
    throw new Error(`Failed to load locale: ${e}`)
  }
}
```

2. This code runs fine in `next dev`, but not in `next dev --turbo`:

```
 ⚠ ./i18n/config.ts:56:19
Module not found
  54 |   try {
  55 |     // must be prefixed statically, see https://github.com/webpack/webpack/issues/6680#issuecomment-370800037
> 56 |     return (await import(`@/i18n/${locale.location}`)).default
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  57 |   } catch (e) {
  58 |     throw new Error(`Failed to load locale: ${e}`)
  59 |   }
```

Workaround: use relative import, `../i18n/${locale.location}` in my case.

### Current vs. Expected behavior

* `import`ing with correct `@`-absolute paths works
* No regression with/without `--turbo`

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
Binaries:
  Node: 20.16.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.2.15 // Latest available version is detected (14.2.15).
  eslint-config-next: 14.2.15
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by mischnic** [comment]
This is already fixed in the canary versions (`pnpm add next@canary`) since version `15.0.0-canary.118` by https://github.com/vercel/next.js/pull/68274 .

**Comment by wingsofovnia** [comment]
@mischnic will it be backported to 14.x?
