### ISSUE TITLE
Docs: "Incremental Static Regeneration" links are broken in Stable docs

### ISSUE THREAD

**Issue by sebastiancarlos** [vercel/next.js#71282]
### What is the documentation issue?

The page https://nextjs.org/docs/app/building-your-application/data-fetching/fetching has several links to a "Incremental Static Regeneration" page (https://nextjs.org/docs/app/building-your-application/data-fetching/incremental-static-regeneration) which doesn't exist, leading to a 404 page.

### Is there any context that might help us understand?

N/A

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/data-fetching/fetching

**Comment by samcx** [comment]
@sebastiancarlos It looks like this has been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> already!
