### ISSUE TITLE
Docs: Missing documentation about route groups and loading page behavior

### ISSUE THREAD

**Issue by gmoniava** [vercel/next.js#71321]
### What is the documentation issue?

In the "Learn" tutorial (https://nextjs.org/learn/dashboard-app/streaming#fixing-the-loading-skeleton-bug-with-route-groups) it is mentioned how using route groups you can make such that `loading` page of a parent route doesn't get used also by routes which are on a lower level.

Citing:

> Since loading.tsx is a level higher than /invoices/page.tsx and /customers/page.tsx in the file system, it's also applied to those pages.

...

> Create a new folder called /(overview) inside the dashboard folder. Then, move your loading.tsx and page.tsx files inside the folder:

However, this is only mentioned on the "Learn" tutorial and not on the official docs. This behavior should be explained and added on the official docs too for people who did not follow the "Learn" tutorial.

### Is there any context that might help us understand?

N/A

---

_NB: I think this was supposed to be opened as discussion I am not sure, anyway for some reason I thought I was opening a discussion but it seems I opened it as an issue. If it is problematic feel free to move it there._

**Comment by samcx** [comment]
@gmoniava Good point! We can add this to this → https://nextjs.org/docs/app/building-your-application/routing/route-groups#examples <picture data-single-emoji=":loading:" title=":loading:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/loading/fa531af0d6940856.gif" alt=":loading:" align="absmiddle"></picture>
