### ISSUE TITLE
Fonts from next/font/google stopped working suddenly on localhost (dev mode)

### ISSUE THREAD

**Issue by Baukaalm** [vercel/next.js#71364]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:54:26 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T8112
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: 4.1.1
  pnpm: N/A
Relevant Packages:
  next: 14.1.0
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

no

### Describe the Bug

I was using Google Fonts with the next/font/google package in my Next.js project, and they were working fine. However, the fonts suddenly stopped loading on localhost without any apparent changes to the code or configuration. The styles revert to default system fonts instead of the expected Google Fonts.

### Expected Behavior

**

### To Reproduce

Fonts from next/font/google stopped working suddenly on localhost

**Comment by benpixel** [comment]
I've got similar problem but on production using 15.0.0-rc.1. Class generated by `<body className={font.variable}>` ends up not having any styles attached. Adding it manually via inspector fixes the problem and shows the proper font.
 
![CleanShot 2024-10-16 at 12 22 02](https://github.com/user-attachments/assets/f38f7244-8b7b-4e8e-8e15-42ae6ad06d53)

**Comment by atissedrescaleway** [comment]
We have the same issue when we updated from `14.2.14` to `14.2.15`, the fonts are not loaded correctly.


We're using `Inter` and `Space_Grotesk` from `next/font/google`

`fonts.ts` : 
```
import { Inter, Space_Grotesk } from 'next/font/google';

const inter = Inter({...});

const spaceGrotesk = Space_Grotesk({...});
```


`_app.tsx` :

```
import { interFontClass, spaceGroteskFontClass } from '../styles/fonts';

...
            <Layout classNames={[interFontClass, spaceGroteskFontClass]}>
```

`Layout.tsx` :

```
export const Layout = ({
  children,
  classNames,
}: {
  children: ReactNode;
  classNames: string[];
}) => <div className={cx(classNames, 'container')}>{children}</div>;
```


![image](https://github.com/user-attachments/assets/a5b8aba0-3085-4000-a4c4-e4551ca60bd9)

**Comment by Baukaalm** [comment]
I re-cloned the repository of my project, and that solved the issue for me.

**Comment by JamieByrneHDRUK** [comment]
Is this possibly external to next? Nosing over: [update-google-fonts.js](https://github.com/vercel/next.js/blob/canary/scripts/update-google-fonts.js) could it be font's are disappearing because they're no longer in that response from : [googles fonts](https://fonts.google.com/metadata/fonts). I'm seeing fonts dropping after rebuilds, not just locally but in environment's.

**Comment by JamieByrneHDRUK** [comment]
So for us, yesterday: https://fonts.google.com/metadata/fonts was not returning our font, today it is.

But take note it may have a different ID (ours did...), so if your going off of id like:
```
const theme = createTheme({
    typography: {
        fontFamily: [
            "__Source_Sans_3_32aa65",
            "__Source_Sans_3_Fallback_32aa65",
        ].join(",")
        ...
```

You may need to be doing something like:
```
import { Source_Sans_3 } from "next/font/google";

const sourceSans3 = Source_Sans_3({
    subsets: ["latin"],
    display: "swap",
});
const theme = createTheme({
    typography: {
        fontFamily: fontFamily: sourceSans3.style.fontFamily,
        ...
```

**Comment by leerob** [comment]
Hey there – please follow the issue template to include a minimal reproduction and open a new issue 🙏 Thank you!

**Comment by vedantmishra69** [comment]
I deleted the ``.next`` folder and it solved the issue for me.
