### ISSUE TITLE
Bug Report: Type Error in API Route Exports in Next.js

### ISSUE THREAD

**Issue by HyeokjaeLee** [vercel/next.js#71387]
### Link to the code that reproduces this issue

https://github.com/HyeokjaeLee/briend/blob/bug/1.0.0/src/utils/createApiRoute.ts

### To Reproduce

Create an API route using the App Router (src/app/api/auth/unlink-account/route.ts).

Define a function with any HTTP method (e.g., POST, GET).

Pass a second parameter to the function.

Try to build the project.

The following type errors appear during the build:

Type "Promise<unknown>" is not a valid type for the function's second argument.
Type "{}" is not a valid type for the function's second argument.
Type "undefined" is not a valid type for the function's second argument. Expected "RouteContext", got "undefined".

### Current vs. Expected behavior

**Current Behavior:**
When defining an API route, the second parameter of the exported function throws type errors like Promise<unknown>, {}, or undefined being invalid.
RouteContext type is expected but cannot be found or imported, causing the build to fail.

**Expected Behavior:**
The second parameter of the API route functions should correctly accept the appropriate RouteContext type (or equivalent) without throwing type errors.
The RouteContext type should be importable or properly inferred by Next.js.

### Provide environment information

```bash
Operating System:
  Platform: mac
  Architecture: arm m2
  Version: 15.0(24A335)
Binaries:
  Bun: 1.1.26
Relevant Packages:
  "next": "15.0.0-rc.1"
  "@types/node": "^20.16.11"
  "@types/react": "npm:types-react@19.0.0-rc.1"
  "@types/react-dom": "npm:types-react-dom@19.0.0-rc.1"
  "@types/react-transition-group": "^4.4.11"
  "@typescript-eslint/eslint-plugin": "^7.18.0"
  "@typescript-eslint/parser": "^6.21.0"
```

### Which area(s) are affected? (Select all that apply)

TypeScript

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by darthmaim** [comment]
Your types are wrong, the 2nd parameter is not a promise.

**Comment by HyeokjaeLee** [comment]
> Your types are wrong, the 2nd parameter is not a promise.

I thought it changed in version 15.

**Comment by HyeokjaeLee** [comment]
I solved it the following way

`type ApiRoute<TContext extends Record<string, unknown>, TResponse> = (
  req: NextRequest,
  context: {
    params: Promise<TContext>;
  },
) => Promise<NextResponse<TResponse>>;`
