### ISSUE TITLE
StaticIndicator toast is causing a11y issues

### ISSUE THREAD

**Issue by makepanic** [vercel/next.js#71419]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000
  Available memory (MB): 31305
  Available CPU cores: 16
Binaries:
  Node: 22.5.1
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 9.6.0
Relevant Packages:
  next: 15.0.0-rc.1 // Latest available version is detected (15.0.0-rc.1).
  eslint-config-next: 14.2.15
  react: 19.0.0-rc-cd22717c-20241013
  react-dom: 19.0.0-rc-cd22717c-20241013
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

app-dir-i18n-routing

### Describe the Bug

When using https://github.com/dequelabs/axe-core e.g. via playwright, static pages cause issues due to the toast not using a valid a11y landmark.

This only appears after updating to next@15 rc.

I'm unsure if this is ok as it's in development mode but we're currently running our playwright tests against dev and axe-core is complaining:

```
Object {
+     "description": "Ensure all page content is contained by landmarks",
+     "help": "All page content should be contained by landmarks",
+     "helpUrl": "https://dequeuniversity.com/rules/axe/4.10/region?application=playwright",
+     "id": "region",
+     "impact": "moderate",
+     "nodes": Array [
+       Object {
+         "all": Array [],
+         "any": Array [
+           Object {
+             "data": Object {
+               "isIframe": false,
+             },
+             "id": "region",
+             "impact": "moderate",
+             "message": "Some page content is not contained by landmarks",
+             "relatedNodes": Array [],
+           },
+         ],
+         "failureSummary": "Fix any of the following:
+   Some page content is not contained by landmarks",
+         "html": "<div class=\"nextjs-static-indicator-toast-text\">",
+         "impact": "moderate",
+         "none": Array [],
+         "target": Array [
+           Array [
+             "nextjs-portal",
+             ".nextjs-static-indicator-toast-text",
+           ],
+         ],
+       },
+     ],
```

### Expected Behavior

The toast or static indicator component should use a a11y landmark. I've checked and `role="alert"` should fit the best.
After adding the role to the element, axe-core isn't throwing that test error anymore.

### To Reproduce

Check that the `class="nextjs-static-indicator-toast-text"` element is in a valid a11y landmark.

**Comment by samcx** [comment]
@makepanic Thank you for submitting an issue!

I added a comment in the <picture data-single-emoji=":pr:" title=":pr:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/pr/876af7e7d65e1595.png" alt=":pr:" align="absmiddle"></picture>
