### ISSUE TITLE
Api route and sitemap are 0kb on build

### ISSUE THREAD

**Issue by wispyco** [vercel/next.js#71448]
### Link to the code that reproduces this issue

https://github.com/wispyco/uipatternfactory

### To Reproduce

1. run yarn build
2. view build tree

### Current vs. Expected behavior

Current

Route (app)                              Size     First Load JS
┌ ○ /                                    149 B           224 kB
├ ○ /_not-found                          880 B          94.5 kB
├ ● /[slug]                              148 B           224 kB
├   ├ /p=animated-circular-navigation
├   ├ /p=animated-navigation
├   ├ /p=animated-keyboard
├   └ [+3 more paths]
├ ƒ /api/code-convert                    0 B                0 B
└ ○ /sitemap.xml                         0 B                0 B
+ First Load JS shared by all            93.6 kB
  ├ chunks/2117-e52a872263eb281e.js      31.8 kB
  ├ chunks/fd9d1056-7e2f47df778b58ec.js  53.6 kB
  └ other shared chunks (total)          8.2 kB

○  (Static)   prerendered as static content
●  (SSG)      prerendered as static HTML (uses getStaticProps)
ƒ  (Dynamic)  server-rendered on demand

expected SiteMap and code-convert to have some size of Bytes.

### Provide environment information

```bash
Node.js v20.16.0

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:12 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6020
  Available memory (MB): 65536
  Available CPU cores: 12
Binaries:
  Node: 20.16.0
  npm: 10.9.0
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.2.15 // Latest available version is detected (14.2.15).
  eslint-config-next: 14.2.15
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

Everything works fine local, and next build and next start. But when I deploy to the server the api route gets 500.

**Comment by JesseKoldewijn** [comment]
I'll take a look at your reproduction report in a bit. But I'm pretty sure the 500 error is unrelated to the displayed byte size of the api route and other files

**Comment by wispyco** [comment]
Ok thank you hopefully you can discover the issue. I am getting the exact same error on another repo i just pushed and locally it works 

again all my routes in that app are 0b

Route (app)                              Size     First Load JS
┌ ○ /                                    403 kB          491 kB
├ ○ /_not-found                          873 B            88 kB
├ ƒ /api/categorize-with-ai              0 B                0 B
├ ○ /api/folders                         0 B                0 B
├ ƒ /api/get-card                        0 B                0 B
├ ○ /api/get-cards                       0 B                0 B
├ ƒ /api/get-content                     0 B                0 B
├ ƒ /api/save-categories                 0 B                0 B
├ ƒ /api/save-folders                    0 B                0 B
├ ƒ /api/save-notes                      0 B                0 B
└ ƒ /api/update-card                     0 B                0 B
+ First Load JS shared by all            87.2 kB
  ├ chunks/117-4b74385e4dc45e6c.js       31.6 kB
  ├ chunks/fd9d1056-91aa9495991b9c80.js  53.6 kB
  └ other shared chunks (total)          1.92 kB

**Comment by JesseKoldewijn** [comment]
I can tell you one thing already. The build output doesn't contain any typescript files, so doing an fs read call onto tsx files wont work either way on a deployment

**Comment by JesseKoldewijn** [comment]
FYI the pattern you want wouldn't work either way since all components get compiled into a per page chunk. meaning the wont have separate files per component on production. The only reason why this setup works locally is because you have the source-code locally.

**Comment by wispyco** [comment]
Ok I will have to rethink how to get the code on demand, thanks for you help

**Comment by JesseKoldewijn** [comment]
@wispyco no probs! Perhaps a fetch through github to the raw code file could work? It would probably be the least intrusive solution
