### ISSUE TITLE
Dynamic `resourceQuery` isn't passed in Webpack loader with Turbopack enabled

### ISSUE THREAD

**Issue by dimaMachina** [vercel/next.js#71453]
### Link to the code that reproduces this issue

https://github.com/dimaMachina/repro-next/tree/turbopack-dynamic-resource-query

### To Reproduce

Run `pnpm dev`

### Current vs. Expected behavior

See in console

```text
[test-loader.js] this.resourceQuery [ '?static=567&dynamic=' ]
```

Expected to see:

```text
[test-loader.js] this.resourceQuery [ '?static=567&dynamic=123' ]
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020
  Available memory (MB): 98304
  Available CPU cores: 12
Binaries:
  Node: 20.15.1
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.12.1
Relevant Packages:
  next: 15.0.0-canary.196 // Latest available version is detected (15.0.0-canary.196).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by dimaMachina** [comment]
My code looks like https://github.com/shuding/nextra/blob/ca0283c014eea63747306df2a575cd9148b4e65b/packages/nextra/src/server/page-map.ts#L158-L160

where [`page-map-placeholder.ts`](https://github.com/shuding/nextra/blob/v4-30/packages/nextra/src/server/page-map-placeholder.ts) is just placeholder file, which will be converter later by Webpack loader

https://github.com/shuding/nextra/blob/ca0283c014eea63747306df2a575cd9148b4e65b/packages/nextra/src/server/loader.ts#L77-L92

**Comment by mischnic** [comment]
In a function like this, Turbopack won't be able to pass that locale to the Webpack loader.
```js
export async function getPageMap(locale = '') {
  const { pageMap } = await import(
    `./page-map-placeholder.js?locale=${locale}`
  )
  return pageMap
}
```
Because that argument is not known statically.

**Comment by dimaMachina** [comment]
Thank you, as a possible solution I have in mind - since I know all possible values of `locale` at build time I can write loader for the file where `getPageMap()` function lives and replace function body:

```js
export async function getPageMap(locale = '') {
  const { pageMap } = await import(
    `./page-map-placeholder.js?locale=${locale}`
  )
  return pageMap
}
```

with

```js
export async function getPageMap(locale = '') {
  let result
  switch (locale) {
    case 'ru':
      result = await import('./page-map-placeholder.js?locale=ru')
      break;
    default:
      result = await import('./page-map-placeholder.js?locale=en')
  }
  return result.pageMap
}
```

**Comment by timneutkens** [comment]
Lockbot is a bit too eager, looking into fixing that 🙏
