### ISSUE TITLE
Getting `Error: Cannot find module './test.mdx?static=567&dynamic=123'` for dynamic import with interpolated `resourceQuery`

### ISSUE THREAD

**Issue by dimaMachina** [vercel/next.js#71454]
### Link to the code that reproduces this issue

https://github.com/dimaMachina/repro-next/tree/cannot-find-module-for-dynamic-import

### To Reproduce

Run `pnpm dev`

### Current vs. Expected behavior

See in console

```text
 ⨯ Error: Cannot find module './test.mdx?static=567&dynamic=123'
    at /Users/dmytro/Desktop/repros/repro-next/.next/server/app/page.js:25:11
    at async Home (./app/page.jsx:11:36)
```

I expected to see no errors as with turbopack `next dev --turbo` enabled

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020
  Available memory (MB): 98304
  Available CPU cores: 12
Binaries:
  Node: 20.15.1
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.12.1
Relevant Packages:
  next: 15.0.0-canary.196 // Latest available version is detected (15.0.0-canary.196).
  eslint-config-next: 14.1.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@dimaMachina Are you saying you're getting the error with or without Turbopack?

- x-ref: https://github.com/vercel/next.js/issues/71461#issuecomment-2427640357

**Comment by dimaMachina** [comment]
@samcx In this repro, I am getting an error `without` Turbopack.

I also added Turbopack mdx loader config
https://github.com/dimaMachina/repro-next/blob/fddd448908bcfe26b37ab793e2feb6be923111f1/next.config.mjs#L8-L16 and if you try to run this repro `with` turbopack `next dev --turbo` you will not get any error but dynamic `resourceQuery` isn't passed to loader, so I created another issue for it in https://github.com/vercel/next.js/issues/71453

Also, this repro isn't related to the MDX loader at all, if I add dummy `foo.jsx` and after I dynamically import it like `await import(`./foo?static=${STATIC}&dynamic=${DYNAMIC}`)` I am getting the same error

```
 Error: Cannot find module './foo?static=567&dynamic=123'
    at /Users/dmytro/Desktop/repros/repro-next/.next/server/app/page.js:25:11
    at async Home (./app/page.jsx:11:36)
```

**Comment by samcx** [comment]
@dimaMachina So unfortunately, this is a limitation with webpack.

Is it possible to clarify what's the use case for importing like this, versus using https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#example?

**Comment by dimaMachina** [comment]
@samcx  My dynamic import isn't a route or page, it's a file which should be converted by Webpack loader based on `resourceQuery` value

**Comment by dimaMachina** [comment]
https://github.com/vercel/next.js/issues/71453#issuecomment-2431810574
