### ISSUE TITLE
NextJS Router Cache (my guess) doesn't preserve `<video>` `muted` attribute

### ISSUE THREAD

**Issue by johnslemmer** [vercel/next.js#71460]
### Link to the code that reproduces this issue

https://github.com/johnslemmer/video-muted-bug

### To Reproduce

deployed at https://video-muted-bug.vercel.app/ and ready to demonstrate.

Steps to recreate:

- Easily seen by loading the home page (you will see a video auto play and be muted)
- click the link to go to the about page
- click the link to come back to home page
  - the video will now be auto playing but also playing sound
  - if you check the elements in DevTools you will see the `muted` attribute no
    longer exists on the video element. Which feels like a Router Cache issue.

Code is pretty simple, the weird `innerHTML` set is done to show how not having
`muted` cached properly can lead to undesirable audio playing on, for all
intents and purposes, what was a muted video from the developer's perspective.

### Current vs. Expected behavior

Here is a gif showing the current  behavior.

https://github.com/user-attachments/assets/35fb2765-c423-432a-a0f4-2b3574276056

Expected would be that `muted` would be preserved.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 20.15.0
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: 9.4.0
Relevant Packages:
  next: 14.2.15 // Latest available version is detected (14.2.15).
  eslint-config-next: 14.2.15
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed)

**Comment by ztanner** [comment]
Hi @johnslemmer -- thanks for the report. I don't think this relates to Next.js as it's React that's doing the rendering here. I found a React issue [here](https://github.com/facebook/react/issues/10389) that I think describes the behavior you're observing and there's a handful of discussion around the correct behavior.

I'm going to close this as I don't believe it's a Next.js issue.
