### ISSUE TITLE
Docs: V15 RC 2 was released as V15 RC 1

### ISSUE THREAD

**Issue by fuzing** [vercel/next.js#71496]
### What is the documentation issue?

According to this [blog post](https://nextjs.org/blog/next-15-rc2), V15 RC2 was released on Oct 15th, but npmjs still shows RC1 as the latest release.  That said, the npmjs RC1 release contains updates through Oct 15th, so I'm suspecting that RC2 was released as RC1 (again).

There are a bunch of folks talking about this online (won't go into the expletives), but would suggest that someone fixes this pronto!!

### Is there any context that might help us understand?

See above

**Comment by SaveliiLukash** [comment]
The release from **May 23rd, 2024** is [Next.js 15 RC (1)](https://nextjs.org/blog/next-15-rc)
Also known and marketed as **RC1** for regular people who start their counting from 1.
The package version is **15.0.0-rc.0** - starts from 0.

The realese from **October 15th, 2024** is [Next.js 15 RC 2](https://nextjs.org/blog/next-15-rc2)
Also known as **RC2** 
The package version is **15.0.0-rc.1**

This mismatch does indeed cause some confusion 😅 Made for programmers, marketed for regular people

**Comment by leerob** [comment]
The releases are 0 indexed – so the first RC was RC0, the second is RC1. Sorry for the confusion!
