### ISSUE TITLE
usePathname() not integrated with native History API on Pages Router

### ISSUE THREAD

**Issue by denk0403** [vercel/next.js#71530]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/y2scxp

### To Reproduce

1. Make sure the CodeSandbox preview is running on `https://y2scxp-3000.csb.app`.

    - If not, run `npm run dev` in the CodeSandbox terminal.

2. Navigate to [page 1 (/pages1)](https://y2scxp-3000.csb.app/pages1) on the Pages Router using the URL bar.

3. Open up the Browser DevTools console and clear it.

4. Press the "Go to Pages Page 2" button. Note the URL updates but nothing is logged to the console.

---

5. Now navigate to [page 1 (/app1)](https://y2scxp-3000.csb.app/app1) on the App Router using the URL bar.

6. Clear the Browser DevTools console again.

7. Press the "Go to App Page 2" button. Note the URL updates AND we see `<NavigationEvents>` rerender and log the `currentPathQuery`.

### Current vs. Expected behavior

Current Behavior:
- Using the native history API for navigation in Pages Router does **not** trigger a re-render of components that use `usePathname()` and remain mounted.

Expected Behavior:
- Using the native history API for navigation in Pages Router does trigger a re-render of components that use `usePathname()` and remain mounted.

### Provide environment information

```bash
See CodeSandbox link.
```

### Which area(s) are affected? (Select all that apply)

Navigation, Pages Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@denk0403 Can you clarify how exactly we're supposed to replicate this issue (e.g., step by step navigation)?

**Comment by denk0403** [comment]
@samcx The reproduction steps are in the linked repo's README, but I have now copied them over to my first comment.
Let me know if you need further clarification.

**Comment by gaojude** [comment]
The [shallow routing](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#using-the-native-history-api) via history.pushState is only relevant to App Router. Doing that in Pages router would not cause usePathname to re-render with the new path. I don't think that this is a bug.

**Comment by denk0403** [comment]
@gaojude Could you shed light on why this is intended behavior? The [docs for `usePathname()`](https://nextjs.org/docs/app/api-reference/functions/use-pathname) suggest it should be compatible with the pages router, so I would expect it to behave mostly the same as in app router. This is also important for the codebase I'm working in while we are migrating from Pages Router to App Router.

**Comment by gaojude** [comment]
> @gaojude Could you shed light on why this is intended behavior? The [docs for `usePathname()`](https://nextjs.org/docs/app/api-reference/functions/use-pathname) suggest it should be compatible with the pages router, so I would expect it to behave mostly the same as in app router. This is also important for the codebase I'm working in while we are migrating from Pages Router to App Router.

Because in Pages router, you could leverage the ["shallow" config](https://nextjs.org/docs/pages/building-your-application/routing/linking-and-navigating#shallow-routing) to achieve shallow routing, whereas there was no way to do shallow routing before we added integration with history.pushState.

In your specific migration case, one way you can do in the migration period is to hoist the navigation handlers to a context, and inject different implementations when the component is used in App/Pages directory.
