### ISSUE TITLE
Next js is double rendering components 

### ISSUE THREAD

**Issue by devqueue** [vercel/next.js#71545]
### Link to the code that reproduces this issue

https://github.com/devqueue/next-double-render

### To Reproduce

1. Clone the rep
2. bun i
3. bun dev

### Current vs. Expected behavior

I looked up the same issue and found #35822 as suggested I set the strict mode to false 

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
};

export default nextConfig;
```

still i am facing the same isssue, this is making front end design extremely difficult 
<img width="1440" alt="Screenshot 2024-10-21 at 8 22 05 AM" src="https://github.com/user-attachments/assets/876f42d6-c43d-497f-9218-6add93d391fb">

Need help with this.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:49:48 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 20.0.0
  npm: 9.6.4
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.2.15 // Latest available version is detected (14.2.15).
  eslint-config-next: 14.2.15
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by lubieowoce** [comment]
In development, Next.js uses React's "strict mode". Rendering components twice is one of the things StrictMode does. See the React docs for more: https://react.dev/reference/react/StrictMode#reference
