### ISSUE TITLE
Exported value is undefined sometimes when using `export * from 'module'`

### ISSUE THREAD

**Issue by NazmusSayad** [vercel/next.js#71556]
### Link to the code that reproduces this issue

https://github.com/NazmusSayad/next-bug-export-all-from

### To Reproduce

1. Generate the Prisma module using "npx prisma generate" or "npm run prisma".
2. Now run dev mode with `--turbo`
3. Go to http://localhost:3000

#### Current behavior:
![image](https://github.com/user-attachments/assets/846d82d2-c5e3-4803-b4ad-183782e450f3)

#### Expected behavior:
![image](https://github.com/user-attachments/assets/e8a8c7cb-9dec-497c-8511-d405875fa2d3)
*NOTE: This photo is taken from dev mode without `--turbo`*

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32442
  Available CPU cores: 20
Binaries:
  Node: 20.18.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.15 // Latest available version is detected (14.2.15).  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I attempted to use `export * from './my-local-file'`, but it functions perfectly without resulting in any undefined values.
I don't know what the issue is with Prisma. I thought it might be related to Prisma, but it works perfectly when I don't use the `--turbo` flag.

**Comment by samcx** [comment]
@NazmusSayad A lot of Turbopack fixes were added in v14 canary and not v14 stable, and now with the just now released v15 stable (Turbopack dev is stable).

I'm not getting the issue with Turbopack on v15!

**Comment by NazmusSayad** [comment]
Should I just install next@15?
Doesn't that have any breaking changes?

**Comment by samcx** [comment]
@NazmusSayad No you don't have to—I was just pointing out that Turbopack dev isn't stable on the latest v14 stable, so it is fine that this isn't working with Turbopack dev on v14 stable.
