### ISSUE TITLE
I get recreate error when I use redirect in approuter 

### ISSUE THREAD

**Issue by ikaasraa** [vercel/next.js#71559]
### Link to the code that reproduces this issue

asd

### To Reproduce

[Error]  Server  Error: NEXT_REDIRECT

The above error occurred in the <Page> component.

React will try to recreate this component tree from scratch using the error boundary you provided, RedirectErrorBoundary.

[Error] Error: Rendered more hooks than during the previous render.

The above error occurred in the <Router> component.

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundaryHandler.

### Current vs. Expected behavior

[Error]  Server  Error: NEXT_REDIRECT

The above error occurred in the <Page> component.

React will try to recreate this component tree from scratch using the error boundary you provided, RedirectErrorBoundary.

[Error] Error: Rendered more hooks than during the previous render.

The above error occurred in the <Router> component.

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundaryHandler.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:26 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8103
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 4.5.0
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-rc.1
  eslint-config-next: 15.0.0-rc.1
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
  typescript: 5.6.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Not sure, Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by lubieowoce** [comment]
It's a bit hard to tell from the issue description, but i'm guessing this is a duplicate of https://github.com/vercel/next.js/issues/71555
