### ISSUE TITLE
Error: NEXT_REDIRECT error when redirecting on server after navigating via <Link>.

### ISSUE THREAD

**Issue by mtansk** [vercel/next.js#71555]
### Link to the code that reproduces this issue

https://github.com/mtansk/nextrederr

### To Reproduce

1. npm run dev
2. click next "Link" component which leads to a page that performs next redirect.
3. get browser console error and, sometimes, node console unknown url scheme error.

### Current vs. Expected behavior

Expeted: redirect without an error.
Current: console error.

The error appears only when using "Link" component, "a" element works as expected.

![image](https://github.com/user-attachments/assets/55e15fbc-a9bc-4241-97c4-74d9f5d10a1c)
![image](https://github.com/user-attachments/assets/0bb1acb7-ba4a-476b-86f2-898e1ec4cc9e)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16349
  Available CPU cores: 4
Binaries:
  Node: 20.12.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.202 // Latest available version is detected (15.0.0-canary.202).
  eslint-config-next: N/A
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app, Developer Experience, Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Error appears after RC 2. RC 1 was ok. Didn't check other canaries

**Comment by lubieowoce** [comment]
I can reproduce this: https://github.com/lubieowoce/next-redirect-error-71555
(created my own because the code you linked is just a blank CRA app)

**Comment by mtansk** [comment]
Pushed local changes to my initial repruduction at https://github.com/mtansk/nextrederr

**Comment by elie222** [comment]
Facing same issues here: https://github.com/elie222/inbox-zero/pull/249

Started happening after upgrading to Nextjs 15

**Comment by mtansk** [comment]
@lubieowoce do you consider 404 and unknown scheme errors as part of this same issue? The screenshots are from my reproduction.
![image](https://github.com/user-attachments/assets/cb7e8548-9a5c-4c75-83c2-809d2bb5d523)
![image](https://github.com/user-attachments/assets/a9235ec0-0564-493b-9cac-2e58e042c508)

**Comment by lubieowoce** [comment]
@mtansk I'm Pretty sure that those source map errors (404 & "Unknown url scheme") are unrelated. Although some of the source map 404s might be due to unexpected next internals appearing in the stack trace or something, so they'd go away when we fix this

(also i can't reproduce the ones that you're seeing in the terminal)
