### ISSUE TITLE
Docs: Not found next-config-js/partial-prerendering on stable Version

### ISSUE THREAD

**Issue by Marukome0743** [vercel/next.js#71593]
### What is the documentation issue?

I can't see https://nextjs.org/docs/app/api-reference/next-config-js/partial-prerendering.
However canary docs(https://nextjs.org/docs/canary/app/api-reference/next-config-js/ppr) is valid.

### Is there any context that might help us understand?

This seems to redirect `ppr` to `partial-prerendering` docs path on v15.0.0 stable vesion docs.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/next-config-js/partial-prerendering

**Comment by samcx** [comment]
@Marukome0743 Thank you for submitting an issue!

Can you tell us where you're seeing that link?

**Comment by Marukome0743** [comment]
Thank you for a very quick response!
I check from [rendering/partial-prerendering](https://nextjs.org/docs/app/building-your-application/rendering/partial-prerendering) and [next-config-js](https://nextjs.org/docs/app/api-reference/next-config-js) pages.
In addition, siderbar navigation(API Reference/next.config.js Options) also show 404 error under stable version.

**Comment by Marukome0743** [comment]
Now that I can see  https://nextjs.org/docs/app/api-reference/next-config-js/ppr and https://nextjs.org/docs/app/api-reference/next-config-js/partial-prerendering
