### ISSUE TITLE
Docs: "Getting Started" Route Missing in Next.js Docs

### ISSUE THREAD

**Issue by CraGit** [vercel/next.js#71629]
### What is the documentation issue?

**Broken Route:**
Clicking the "Getting Started" button tries to navigate to https://nextjs.org/docs/getting-started, but this route does not exist.

**Steps to Reproduce:**

Visit [Next.js Documentation](https://nextjs.org/docs)
Click the "Getting Started" button.
Observe that the URL leads to a non-existent route.

### Is there any context that might help us understand?

The issue was found while navigating the Next.js documentation. I clicked the "Getting Started" button, expecting to be redirected to the "Getting Started" guide. However, the route https://nextjs.org/docs/getting-started does not exist. It appears that this route was either removed or never properly linked, which can confuse new users trying to follow the standard onboarding process.

**Comment by sydhrs** [comment]
Clicking on "Getting Started" takes you to /docs. This might be the actual path for the docs index. If you click on items under "Getting Started", the route is docs/getting-started/${itemName}. 

Getting Started should be appended in the URL path too as all other top level nodes

**Comment by CraGit** [comment]
<img width="205" alt="Screenshot 2024-10-22 at 20 30 58" src="https://github.com/user-attachments/assets/f32a157a-52af-45c8-a130-957df8ccfc94">
Check the screenshot, the button says "Next -> Getting Started", but clicking on it takes you to the same page you are already on. Confusing and a really bad user experience.

**Comment by sydhrs** [comment]
That takes you on top of the page as getting started is actually the index of the docs.

**Comment by CraGit** [comment]
But it is not **Next**, but the **same** page. Even worse, top of the same page.

**Comment by samcx** [comment]
@CraGit This seems to be <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> now!
