### ISSUE TITLE
In nextjs version 15.0.0 Clerkprovider is not working on Layout page. Error - In route / headers were iterated over. `headers()` should be awaited before using its value.

### ISSUE THREAD

**Issue by avidev-creator** [vercel/next.js#71624]
### Link to the code that reproduces this issue

https://github.com/avidev-creator/nextjs-v15-clerk.git

### To Reproduce

1. create next app - bun create next-app@latest .
2. install clerk - bun i @clerk/nextjs
3. go to src/app/layout.tsx
4. Add clerkprovider
5. run the app - bun run dev
6. Error - In route / headers were iterated over. `headers()` should be awaited before using its value.

### Current vs. Expected behavior

Expected it to work like usual but now showing error in Nextjs 15 Stable release.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:13 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8112
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 22.6.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0 // Latest available version is detected (15.0.0).
  eslint-config-next: 15.0.0
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Runtime, TypeScript

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ciocanraul22** [comment]
I have a similar issue when using Auth0 NextJS SDK, in the following way:
1. API route set up - `/api/auth/[auth0]/routejs`.
2. Route file contains `import { handleAuth } from "@auth0/nextjs-auth0";
export const GET = handleAuth();`

And that's about it.
The error message i receive server-side is the following:
`Error:  In route /api/auth/[auth0] a param property was accessed directly with `params.auth0`. `params` should be awaited before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis`

**Comment by davecarlson** [comment]
This is a clerk issue, not nextjs - so this should be closed.

See related on clerk https://github.com/clerk/javascript/issues/4374

**Comment by avidev-creator** [comment]
This is not just Clerk issue this is also happening with Auth 0
