### ISSUE TITLE
Docs: Is onRequestError stable?

### ISSUE THREAD

**Issue by rshaul** [vercel/next.js#71634]
### What is the documentation issue?

https://nextjs.org/docs/app/api-reference/file-conventions/instrumentation#onrequesterror-optional

onRequestError docs say: `This API is available in Next.js canary.` in the docs. Which makes me think it is not stable.

### Is there any context that might help us understand?

However the blog post states that it is stable.

https://nextjs.org/blog/next-15#instrumentationjs-stable

Not sure which one is correct!

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/file-conventions/instrumentation#onrequesterror-optional

**Comment by samcx** [comment]
@rshaul Thanks for reporting! We are taking a look <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>
