### ISSUE TITLE
Docs: Next 14 documentation is missing

### ISSUE THREAD

**Issue by vicasas** [vercel/next.js#71637]
### What is the documentation issue?

After updating the docs to the new version of Next.js 15, the docs of version 14 have been lost on the page.

### Is there any context that might help us understand?

This happened after the release of Next.js v15.

E.g. https://nextjs.org/docs/13 works, but https://nextjs.org/docs/14 does not exist.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs

**Comment by musjj** [comment]
Yeah, it's nuts that documentation is insta-killed literally the moment v15 is released. I'm not ready to migrate to v15 yet, so I still need the v14 docs (and so do many other people). For now I'm reading it via https://github.com/nextjsargentina/next.js-docs/blob/main/public/pdf/next.js_v14_documentation.pdf

**Comment by samcx** [comment]
@vicasas Thank you for submitting an issue and flagging this!

@musjj The v15 stable documentation you're looking at is still largely the right documentation for v14. There are still some tweaks and additions that need to be done, so we are working on it!

**Comment by samcx** [comment]
This has been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> now!

![CleanShot 2024-10-22 at 16 52 27@2x](https://github.com/user-attachments/assets/65466d91-3a17-4ed9-9913-1fe562789ccf)
