### ISSUE TITLE
Server side redirect() throws a Error: NEXT_REDIRECT when navigating clientside

### ISSUE THREAD

**Issue by chriseling** [vercel/next.js#71650]
### Link to the code that reproduces this issue

https://github.com/chriseling/nextjs-redirect-repro

### To Reproduce

1. yarn dev
2. click the link to navigate client side to /redirect
3. the /redirect page.tsx has a server side redirect back to /
4. note the client side error

### Current vs. Expected behavior

I expected to be able to navigate client side to the page and then be redirected.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64
  Available memory (MB): 40960
  Available CPU cores: 16
Binaries:
  Node: 22.0.0
  npm: 10.5.1
  Yarn: 1.22.22
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.0 // Latest available version is detected (15.0.0).
  eslint-config-next: 15.0.0
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I noticed this error when upgrading to NextJS 15.0.0

**Comment by ztanner** [comment]
Thanks for the report! This has been fixed by https://github.com/vercel/next.js/pull/71583

**Comment by kevinmitch14** [comment]
@ztanner Still having similar issues

- try/catch in form onSubmit
- call action directly
- action redirects
- catch in onSubmit is triggered with redirect error

**Comment by kevinmitch14** [comment]
```tsx
// Client
<form
  onSubmit={async (e) => {
    try {
      e.preventDefault();
      await action();
    } catch {
      alert("Error");
    }
  }}
>
  <button>Click me</button>
</form>
```


```tsx
// actions.ts
"use server";

import { redirect } from "next/navigation";

export async function action() {
  redirect("/new");
}

```

**Comment by kevinmitch14** [comment]
Related: https://github.com/vercel/next.js/issues/71650
