### ISSUE TITLE
Docs: Static Indicator still use an old image

### ISSUE THREAD

**Issue by Marukome0743** [vercel/next.js#71676]
### What is the documentation issue?

There is an old image about [Static Indicator](https://nextjs.org/docs/app/api-reference/next-config-js/devIndicators#appisrstatus-static-indicator).
![スクリーンショット 2024-10-23 100757](https://github.com/user-attachments/assets/2f3a0fa5-6f2f-49b1-a4c6-315b86acd983)

## Old
![static-indicator](https://github.com/user-attachments/assets/2e332a0a-98e8-4a40-acf9-dcfde3e4b4af)

## New
![static-route-light](https://github.com/user-attachments/assets/482e97c0-6f1a-438e-86c9-7b2efc3177d0)

x-ref: [Static Route Indicator](https://nextjs.org/blog/next-15#static-route-indicator)

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/next-config-js/devIndicators#appisrstatus-static-indicator

**Comment by samcx** [comment]
@Marukome0743 This has been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> !
