### ISSUE TITLE
Old Content Persists After Navigation in Next.js on Chrome

### ISSUE THREAD

**Issue by johackim** [vercel/next.js#71670]
### Link to the code that reproduces this issue

https://github.com/johackim/my-minimal-nextjs-issue-reproduction/

### To Reproduce

1. `git clone https://github.com/johackim/my-minimal-nextjs-issue-reproduction/`
2. `yarn`
3. `npm run dev`
4. Go to http://localhost:3000
5. Click on the "Go to test page" link at the bottom of the homepage
6. Scroll down

### Current vs. Expected behavior

Old page content remains visible below new page after navigation in next.js on Chrome/Chromium :

https://github.com/user-attachments/assets/971bba77-c449-42e0-b701-aa0fed70e291

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000
  Available memory (MB): 7943
  Available CPU cores: 4
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 15.0.0 // Latest available version is detected (15.0.0).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by ztanner** [comment]
Hi, I'm unable to reproduce this on Chrome version `130.0.6723.59`. Can you share a bit more information about what version of Chrome you're using? Could you also ensure that you don't have any extensions enabled or experimental Chrome features?

**Comment by johackim** [comment]
Hello @ztanner, thanks for your answer.

My version of chrome is `130.0.6723.58`.

I have nothing but a fresh setup of Chrome:

````sh
google-chrome-stable --user-data-dir=/tmp/chrome
````

Actually, it seems to work with the new version `130.0.6723.69`. Maybe a Chrome bug.

**Comment by HelloImGabriel** [comment]
I have this same issue in Chrome and with Edge too, seems to happen only when I use the Link component, I'm on the bottom of the page, and the page is considerably longer than the page I'm navigating to... the bug behaviour it's pretty consistent even in a fresh Next app

**Comment by johackim** [comment]
The problem seems to be resolved in the new version of Chrome
