### ISSUE TITLE
bug npm run dev --turbo compiling material-tailwind error globals.css

### ISSUE THREAD

**Issue by metacop** [vercel/next.js#71684]
### Link to the code that reproduces this issue

https://github.com/metacop/materialtailwindbug.git

### To Reproduce

there is a bug when compiling the project with --turbo. but without turbo it works, i am installing the material package tailwind 3v beta
[](https://www.material-tailwind.com/docs/v3/react/guide/next)
following these instructions.

when running with --turbo

![image](https://github.com/user-attachments/assets/641946cc-b83e-4c6e-95c2-ad2c67782d37)

but without --turbo

![image](https://github.com/user-attachments/assets/56f3b039-6bbe-42ab-87bf-a467580ef58f)

I don't know if more tests are needed for the turbo to work at 100%.

I uploaded the repository [](https://github.com/metacop/materialtailwindbug.git) there is only 1 extra package when I run npx create-next-app.

 "@material-tailwind/react": "^3.0.0-beta.23",

globals.css
![image](https://github.com/user-attachments/assets/e2f834ee-3ec4-4e49-a9eb-a00b77a78702)

page.tsx
![image](https://github.com/user-attachments/assets/bf6bdf6a-8d80-43fb-99ac-52c64e36853b)

layout.tsx
![image](https://github.com/user-attachments/assets/af0000da-35cd-43f4-a82d-825e42afd7d0)

I feel this happens when we change the configuration of tailwind.config.ts, rather we change the bases of tailwinds.

![image](https://github.com/user-attachments/assets/89a57f86-7fae-41e7-9132-e3633ef0ce2c)

### Current vs. Expected behavior

xxxx

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 31702
  Available CPU cores: 24
Binaries:
  Node: 21.7.3
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0 // Latest available version is detected (15.0.0).
  eslint-config-next: 15.0.0
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by samcx** [comment]
@metacop The css parser with Turbopack is stricter than with webpack.

![CleanShot 2024-10-22 at 22 15 15@2x](https://github.com/user-attachments/assets/62767825-37c9-4e3f-a205-1f45228310f8)

**Comment by metacop** [comment]
> @metacop The css parser with Turbopack is stricter than with webpack. This is highlighting a bug in your own application, previously that selector would be ignored by the parser causing unexpected behavior.
> 
> ![CleanShot 2024-10-22 at 22 15 15@2x](https://github.com/user-attachments/assets/62767825-37c9-4e3f-a205-1f45228310f8)

Is there a flag to not be strict or less strict with the css parser?

**Comment by timneutkens** [comment]
There is no flag to change the parsing, this is intentional to make sure broken CSS causes a compiler error given that otherwise it gets ignored in the browser making it fail at runtime.

I've reached out to @robinmalfait from Tailwind to figure out in what case Tailwind generates such a selector, your application seems to be using some way to create arbitrary selectors.

**Comment by timneutkens** [comment]
Robin's reply (sharing with their permission):

> It is generated by Tailwind CSS because they wrote something like `[&_data-slot=icon]:h-5` , in this case the value in the square brackets before the `:` means that it is an "arbitrary variant". Essentially it allows you to write a raw CSS selector as an escape hatch if some feature in Tailwind CSS is not supported.The issue is that they want to write this instead `[&[data-slot=icon]]:h-5`  because the first set of `[]` indicate that it is an arbitrary variant, the second set of `[]` is the actual attribute selector.This now produces the expected output of:

```css
.\[\&\[data-slot\=icon\]\]\:h-5[data-slot="icon"] {
  height: 1.25rem; /* 20px */
} 
```

> To go a step further, we do have `data-*` variants in Tailwind CSS so this can be simplified to just `data-[slot=icon]:h-5`.

> That said, I'll track this internally to make sure we don't generate it in the first place.

**Comment by metacop** [comment]
> Robin's reply (sharing with their permission):
> 
> > It is generated by Tailwind CSS because they wrote something like `[&_data-slot=icon]:h-5` , in this case the value in the square brackets before the `:` means that it is an "arbitrary variant". Essentially it allows you to write a raw CSS selector as an escape hatch if some feature in Tailwind CSS is not supported.The issue is that they want to write this instead `[&[data-slot=icon]]:h-5`  because the first set of `[]` indicate that it is an arbitrary variant, the second set of `[]` is the actual attribute selector.This now produces the expected output of:
> 
> ```css
> .\[\&\[data-slot\=icon\]\]\:h-5[data-slot="icon"] {
>   height: 1.25rem; /* 20px */
> } 
> ```
> 
> > To go a step further, we do have `data-*` variants in Tailwind CSS so this can be simplified to just `data-[slot=icon]:h-5`.
> 
> > That said, I'll track this internally to make sure we don't generate it in the first place.

so if it comes from tailwind they should adjust it?. or vercel?. i agree that --turbo is strict with the generated css. but this prevents to lift the project. what should i do then if it is not a bug from vercel? nothing?

**Comment by timneutkens** [comment]
Yeah this is not a bug in Next.js, you'd run into a similar issue when using other bundlers (i.e. Parcel). Would recommend raising an issue with the library you're using that tries to bypass Tailwind built-in classes and uses that `data-slot` thing 👍
