### ISSUE TITLE
Upgrading to Next v15.0.0 throws a directly accessed param warning

### ISSUE THREAD

**Issue by aastopher** [vercel/next.js#71690]
### Link to the code that reproduces this issue

https://github.com/auth0-developer-hub/web-app_nextjs_javascript_hello-world

### To Reproduce

Download this project,
https://github.com/auth0-developer-hub/web-app_nextjs_javascript_hello-world
configure the local env on a free auth0 account or replace with next auth provider.

upgrade package with these dependencies
```
"@typescript-eslint/parser": "8.11.0",
"@auth0/nextjs-auth0": "3.5.0",
"axios": "1.7.7",
"eslint": "9.13.0",
"eslint-config-next": "15.0.0",
"next": "15.0.0",
"react": "18.2.0",
"react-dom": "18.2.0",
"swr": "2.2.5"
```

run the project, attempt to login or directly access the `/api/auth/login` route (or appropriate auth route).

This will result in the following error.

```
Error:  In route /api/auth/[auth0] a param property was accessed directly with `params.auth0`. `params` should be awaited before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
```

### Current vs. Expected behavior

Current:
```
Error:  In route /api/auth/[auth0] a param property was accessed directly with `params.auth0`. `params` should be awaited before accessing its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
```

Expected:
Handle error, consider cases where the param is accessed directly.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
  Available memory (MB): 15644
  Available CPU cores: 8
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.0 // Latest available version is detected (15.0.0).
  eslint-config-next: 15.0.0
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Pages Router

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Reproduction URL

`/api/auth/login`

### The issue

Next v15.0.0 now requires auth params to be awaited. Currently the handleAuth and handleLogin access the params directly, causing an error to be thrown by Next.

Similar [issue](https://github.com/nextauthjs/next-auth/issues/12092) logged and closed recently on next-auth repo.

**Comment by DanielRivers** [comment]
This is correct, it's a bug with auth0 nextjs SDK, Kinde auth SDK had to be updated to support, they will have to do the same.

**Comment by samcx** [comment]
@DanielRivers Thank you for clarifying!

**Comment by zeemaarCA** [comment]
import { use } from "react";

export default function EditPost({ params }: { params: Promise<{ id: string }> }) {
const { id } = use(params);
return()
}
This solution works for me.

**Comment by Bahaa-Sobhy** [comment]
@zeemaarCA is it a temporary workaround?

@DanielRivers So, should we wait for an official fix to this bug?

@samcx What have you done? are you waiting for an official fix to this bug?

@aastopher any news? it's been 2 weeks now 🙂

thanks everybody in advance!

**Comment by samcx** [comment]
@Bahaa-Sobhy This is the expected behavior. 3rd party libraries will need to update. We adjusted how the warning is handled (the PR mentioned by Zack).

**Comment by DanielRivers** [comment]
@Bahaa-Sobhy As @samcx said, this is not something for next.js to fix

**Comment by Bahaa-Sobhy** [comment]
@samcx do you mean it's a fault of 3rd party libraries? can you name them so we can se if we could get substitutions.

@DanielRivers 

So should we adopt this solution as the official and permanent way to use params?
```

import { use } from "react";

export default function EditPost({ params }: { params: Promise<{ id: string }> }) {
const { id } = use(params);
return(// some codes ...)
}
```

As you guys know, `params` is being used in hundreds of files and components, if once adopted this code and updated all these files, it will be hard to again update and make different changes.

also a note - if I understood correctly - and if it's the documented way to use `params` in Next 15.x i wonder how would people upgrade old apps from 13.x and 14.x ? these apps will broke for this change!?

**Comment by samcx** [comment]
@Bahaa-Sobhy We've built Codemods for these exact scenarios → https://nextjs.org/docs/app/building-your-application/upgrading/codemods#next-async-request-api (e.g., upgrading to async params).

We're also working/assisting with 3rd-party libraries to update to these breaking changes! To clarify, this is not something new in the OSS space. Another example of breaking changes which required dependent packages to update is ESLint v8 to v9.

**Comment by Bahaa-Sobhy** [comment]
@samcx Thanks for your attention;
so to be clear: we're going to permanently handle the `params` as `async` `Promise` & `await`, this is not a bug, this is not temporary decision that NextJS gonna change in the future.
Am I correct?

Thanks for your valuable time

**Comment by samcx** [comment]
> this is not a bug, this is not temporary decision that NextJS gonna change in the future.

Yes, this is a permanent breaking change as of the v15 major release.

> I saw now Codemods provided by your link 🙂, so, if we install it, we will not need to do changes to our code (no need to change the code to be awaitable params)

Yes, the Codemods were made to assist you in upgrading (so you don't have to manually update each params).

**Comment by samcx** [comment]
I recommend using the `--help` option if you're not sure about a CLI tool (available on almost all CLI tools).

``
npx @next/codemod@latest --help
```

```
npx @next/codemod@latest next-async-request-api .
```

In the snippet, the `<transform>` is `next-async-request-api`. The `.` means you're going to apply to every file in your directory. The documentation lists several different transforms for the respective upgrade scenarios.

**Comment by Bahaa-Sobhy** [comment]
Thank you so much @samcx 
Now everything is clear, and I tried `npx @next/codemod@latest next-async-request-api --force`
then it asked me about the directory and I types `app/`
then it wrote some lines such as:
```

fatal: not a git repository (or any of the parent directories): .git
WARNING: Unable to determine if git directory is clean. Forcibly continuing.
✔ On which files or directory should the codemods be applied? … /app
Executing command: jscodeshift --no-babel --ignore-pattern=**/node_modules/** --ignore-pattern=**/.next/** --extensions=tsx,ts,jsx,js --transform /Users/bahaa/.npm/_npx/04c93779852ad6b7/node_modules/@next/codemod/transforms/next-async-request-api.js /app
Skipping path /app which does not exist. 
No files selected, nothing to do. 
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 0.001seconds 
```

another try:

```
npx @next/codemod@latest next-async-request-api "app/*" --force

fatal: not a git repository (or any of the parent directories): .git
WARNING: Unable to determine if git directory is clean. Forcibly continuing.
Executing command: jscodeshift --no-babel --ignore-pattern=**/node_modules/** --ignore-pattern=**/.next/** --extensions=tsx,ts,jsx,js --transform /Users/bahaa/.npm/_npx/04c93779852ad6b7/node_modules/@next/codemod/transforms/next-async-request-api.js app/---page.jsx app/--layout.tsx app/--page.tsx app/favicon.ico app/globals.css app/layout copy.tsx
Processing 4 files... 
Spawning 4 workers...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
All done. 
Results: 
0 errors
4 unmodified
0 skipped
0 ok
Time elapsed: 0.165seconds 
```

then I tries again:

```
npx @next/codemod@latest next-async-request-api --force 

fatal: not a git repository (or any of the parent directories): .git
WARNING: Unable to determine if git directory is clean. Forcibly continuing.
✔ On which files or directory should the codemods be applied? … app/api
Executing command: jscodeshift --no-babel --ignore-pattern=**/node_modules/** --ignore-pattern=**/.next/** --extensions=tsx,ts,jsx,js --transform /Users/bahaa/.npm/_npx/04c93779852ad6b7/node_modules/@next/codemod/transforms/next-async-request-api.js app/api
Processing 8 files... 
Spawning 8 workers...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
Sending 1 files to free worker...
All done. 
Results: 
0 errors
7 unmodified
0 skipped
1 ok
Time elapsed: 0.266seconds 
```


then last try:

```
 npx @next/codemod@latest next-async-request-api --force 

fatal: not a git repository (or any of the parent directories): .git
WARNING: Unable to determine if git directory is clean. Forcibly continuing.
✔ On which files or directory should the codemods be applied? … app/*/*.*
Executing command: jscodeshift --no-babel --ignore-pattern=**/node_modules/** --ignore-pattern=**/.next/** --extensions=tsx,ts,jsx,js --transform /Users/bahaa/.npm/_npx/04c93779852ad6b7/node_modules/@next/codemod/transforms/next-async-request-api.js app/(protected)/--layout.tsx app/(protected)/layout-working.tsx app/(protected)/layout.tsx app/(visitors)/--layout.jsx app/(visitors)/--page.jsx app/(visitors)/not-found.jsx app/auth/layout.tsx app/fonts/GeistMonoVF.woff app/fonts/GeistVF.woff app/helpers/StaticExport.tsx app/helpers/basic.tsx app/helpers/utils.ts
Processing 10 files... 
Spawning 9 workers...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
All done. 
Results: 
0 errors
10 unmodified
0 skipped
0 ok
Time elapsed: 0.229seconds 
```


when I reviewed some page.tsx I found no modifications 😞

and on `npm run dev` i get the same error about params and searchParams being awaitable !

**Comment by Bahaa-Sobhy** [comment]
@samcx I appreciate your time and efforts with me... Thank you so much.

In regards to my last reply, I found out it was my mistake when I defined the path;
In case that someone else face this issue, here's the way, don't define the path, let the command apply on all the directory,
when I left this line empty and just hit the return, it worked and I see the modifications in the page.tsx:

`npx @next/codemod@latest next-async-request-api --force`

```
fatal: not a git repository (or any of the parent directories): .git
WARNING: Unable to determine if git directory is clean. Forcibly continuing.
✔ On which files or directory should the codemods be applied? … .  👈🏻
Executing command: jscodeshift --no-babel --ignore-pattern=**/node_modules/** --ignore-pattern=**/.next/** --extensions=tsx,ts,jsx,js --transform /Users/bahaa/.npm/_npx/04c93779852ad6b7/node_modules/@next/codemod/transforms/next-async-request-api.js .
Processing 248 files... 
Spawning 9 workers...
Sending 28 files to free worker...
Sending 28 files to free worker...
Sending 28 files to free worker...
Sending 28 files to free worker...
Sending 28 files to free worker...
Sending 28 files to free worker...
Sending 28 files to free worker...
Sending 28 files to free worker...
Sending 24 files to free worker...
All done. 
Results: 
0 errors
233 unmodified
1 skipped
14 ok
Time elapsed: 1.002seconds 
```

**Comment by redmonkez12** [comment]
> import { use } from "react";



> import { use } from "react";
> 
> export default function EditPost({ params }: { params: Promise<{ id: string }> }) { const { id } = use(params); return() } This solution works for me.

it doesn't work on server for me

**Comment by juddin0802** [comment]
Utilize this approach within a client component in Next.js 15, featuring React 19.
import { useParams } from 'next/navigation';

const { workspaceUrlSlug } = useParams();


In API:

export const GET = async (request, context) => {
  // Await `context.params` to handle it properly in an async context that comes with Next.JS 15
  const { params } = context;
  const { workspaceId } = await params; // Await the params here
  
  
Seniors have suggested other methods, and you can also research online. However, the methods I mentioned have worked well for me.y.

**Comment by udurgesh6** [comment]
You're getting this error because in Next.js 15, params is actually a Promise that needs to be awaited. Here is how you can fix this,

```
export default async function Page({ params}: {
  params: Promise<{userId: number}>,
}) {
  const userId = (await params).userId;
  return <div></div>
}
```

**Comment by umeshbisht1** [comment]
> const { id } = use(params);
thanks buddy for the help💖💖💖💖💖💖💖💖

**Comment by IkkeLucky** [comment]
I have at least found 5 bugs in my (now broken) app since the update to next v15, amazing how all those bugs are still there

**Comment by Kaushallrai** [comment]
Huge thanks to the team for the @next/codemod next-async-request-api tool! It saved me a lot of time and helped resolve the issue in my project. Keep up the amazing work!
