### ISSUE TITLE
Nextjs 15 Create Next App Default Template Hydration Error

### ISSUE THREAD

**Issue by devaoto** [vercel/next.js#71703]
### Link to the code that reproduces this issue

https://github.com/devaoto/elyzen-nxt

### To Reproduce

- Create next app with:
bunx create-next-app@15.0.1 myproj
√ Would you like to use TypeScript? ... No / Yes (Yes)
√ Would you like to use ESLint? ... No / Yes (Yes)
√ Would you like to use Tailwind CSS? ... No / Yes (Yes)
√ Would you like your code inside a `src/` directory? ... No / Yes (Yes)
√ Would you like to use App Router? (recommended) ... No / Yes (Yes)
√ Would you like to use Turbopack for next dev? ... No / Yes (Yes)
√ Would you like to customize the import alias (@/* by default)? ... No / Yes  (No)
Run: bun run dev

### Current
When I run the development server I get the error:
Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used with the default template.

The hydration error is causing by these:
-cz-shortcut-listen="true"
-__processed_781b3edc-1642-4df7-b879-4c81b67a0d7d__="true"
-bis_register="W3sibWFzdGVyIjp0cnVlLCJleHRlbnNpb25JZCI6ImVwcGlvY2VtaG1ubGJoanBsY2drb2ZjaWllZ29t..."

I did not change anything, I just ran the dev command after initializing.

### Expected Behavior: To run the development server without any issues

I'm not entirely sure if it's caused by the runtime or the template had issues :/

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 7999
  Available CPU cores: 4
Binaries:
  Node: 20.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app, Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by anmol-me** [comment]
Hi, How did you solve the issue?

**Comment by zulalnb** [comment]
Facing the same issue
