### ISSUE TITLE
Next Link component scroll={false} not working as expected

### ISSUE THREAD

**Issue by Behnoudmst** [vercel/next.js#71725]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/beautiful-sun-9j5vg7

### To Reproduce

check this code sand box

### Current vs. Expected behavior

when the Link with scroll={false} is clicked, it should display top of the page, but it restores the scroll location

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.1-canary.3 // Latest available version is detected (15.0.1-canary.3).
  eslint-config-next: 14.2.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

### Additional context

I tested this on latest canary release and it still does not work as expected.

**Comment by lubieowoce** [comment]
I think you might be misunderstanding the `scroll` prop. If you're expecting `<Link href="/test">` to scroll to the top of the page (when navigating from `/`), you want `scroll={true}`, (which [is the default, so you don't need to pass it at all](https://nextjs.org/docs/pages/api-reference/components/link#scroll)).

**Comment by Behnoudmst** [comment]
> I think you might be misunderstanding the `scroll` prop. If you're expecting `<Link href="/test">` to scroll to the top of the page (when navigating from `/`), you want `scroll={true}`, (which [is the default, so you don't need to pass it at all](https://nextjs.org/docs/pages/api-reference/components/link#scroll)).

please check the documentation: 
[https://nextjs.org/docs/app/api-reference/components/link#scroll](url)

It says: 

SCROLL
Defaults to true. The default scrolling behavior of <Link> in Next.js is to maintain scroll position, similar to how browsers handle back and forwards navigation. When you navigate to a new [Page](https://nextjs.org/docs/app/building-your-application/routing/pages), scroll position will stay the same as long as the Page is visible in the viewport. However, if the Page is not visible in the viewport, Next.js will scroll to the top of the first Page element.

When scroll = {false}, Next.js will not attempt to scroll to the first Page element.

**Comment by lubieowoce** [comment]
> However, **if the Page is not visible in the viewport**, Next.js will scroll to the top of the first Page element.

When you're navigating from `/` to `/test`, `/test` is not in the viewport yet, so it will be scrolled to the top, like the docs describe.

**Comment by Behnoudmst** [comment]
Okay thanks for your help. I must have mis-understood the docs.
