### ISSUE TITLE
redirect() error from action caught in try/catch on client

### ISSUE THREAD

**Issue by kevinmitch14** [vercel/next.js#71740]
### Link to the code that reproduces this issue

https://github.com/kevinmitch14/redirects2

### To Reproduce

Click submit button
Invoke server action that redirects
Error caught in try/catch block

### Current vs. Expected behavior

Error not caught in try/catch

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 22.8.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 8.15.1
Relevant Packages:
  next: 15.0.2-canary.0 // Latest available version is detected (15.0.2-canary.0).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

This was introduced in 15.0.0-canary.160

**Comment by poorvasingh04** [comment]
Hi @kevinmitch14 As per nextjs [documentation](https://nextjs.org/docs/app/building-your-application/routing/redirecting#redirect-function):

> redirect internally throws an error so it should be called outside of try/catch blocks.

Did you try calling redirect in `finally` block?

**Comment by kevinmitch14** [comment]
The try/catch is on the client, not in the action where redirect() is being called

```tsx
// Client
<form
  onSubmit={async (e) => {
    try {
      e.preventDefault();
      await action();
    } catch {
      alert("Error");
    }
  }}
>
  <button>Click me</button>
</form>
```


```tsx
// actions.ts
"use server";

import { redirect } from "next/navigation";

export async function action() {
  redirect("/new");
}

```

**Comment by kevinmitch14** [comment]
Related: https://github.com/vercel/next.js/issues/71650

**Comment by poorvasingh04** [comment]
what about moving `await action();` to finally?

**Comment by lubieowoce** [comment]
This is intended behavior: https://github.com/vercel/next.js/pull/69945

If you'd like to filter out internal next.js errors, consider using [unstable_rethrow](https://nextjs.org/docs/app/api-reference/functions/unstable_rethrow)

**Comment by kevinmitch14** [comment]
@lubieowoce so to allow for a regular redirect, you now need to do:

```tsx
<form
  onSubmit={async (e) => {
    try {
      e.preventDefault();
      await action();
    } catch (error) {
      unstable_rethrow(error);
    }
  }}
>
  <button>Click me</button>
</form>
```

Docs:
>Invoking the redirect() function throws a NEXT_REDIRECT error and terminates rendering of the route segment in which it was thrown.

**Comment by kevinmitch14** [comment]
The redirect still happens, and the catch block is also being triggered.

**Comment by kevinmitch14** [comment]
@lubieowoce can you explain what the internal next.js error is actually doing here then? Because even with the try/catch block, the redirect is still happening. So it's not like the catch block is swallowing the redirect or anything, like what happens when you call redirect in an action.
