### ISSUE TITLE
Turbo config only accepted in experimental [Next.js 15]

### ISSUE THREAD

**Issue by sombrilla** [vercel/next.js#71750]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/exciting-kepler-go8s7s

### To Reproduce

1. Add turbo config in next.config.js/mjs
2. Start dev server
3. Logs show:
```
Invalid next.config.mjs options detected: 
 ⚠     Unrecognized key(s) in object: 'turbo'
```

### Current vs. Expected behavior

According to the [docs](https://nextjs.org/docs/app/api-reference/next-config-js/turbo) turbo config is not experimental and doesn't require the config to be wrapped in `experimental`.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.2-canary.0 // Latest available version is detected (15.0.2-canary.0).
  eslint-config-next: N/A
  react: 19.0.0-rc-45804af1-20241021
  react-dom: 19.0.0-rc-45804af1-20241021
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Documentation, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

Tested as well on `15.0.1` stable

**Comment by samcx** [comment]
@sombrilla Thank you for submitting an issue!

Looks like a fix was already pushed up, but just making 1 extra additional change.
