### ISSUE TITLE
Next.js v15 is being installed with ESLint v8

### ISSUE THREAD

**Issue by silvenon** [vercel/next.js#71763]
### Link to the code that reproduces this issue

https://github.com/silvenon/repro/tree/nextjs-v15-eslint-v8

### To Reproduce

1. create an app using `npx create-next-app@latest`
2. ensure that ESLint is set to "Yes"

### Current vs. Expected behavior

Currently it installs ESLint v8, but I expected v9 considering that Next.js v15 says that it supports v9. Did I misunderstand what that meant?

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.18.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.9.0
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app, Linting

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by samcx** [comment]
@silvenon It is on our to-do list! We have not added it to `create-next-app` yet since I believe there are a few improvements to be done (e.g., I believe using flat config looks funky right now versus the old config).

Nonetheless, ESLint v9 is fully supported in v15.

**Comment by martinkadlec0** [comment]
Is there any example of how a flat config for v9 could look like (with vitals & next config with typescript) ? There are some hacky solutions out there from before the official support, but can't find anything new after the release.

**Comment by Jochem-W** [comment]
> Is there any example of how a flat config for v9 could look like (with vitals & next config with typescript) ? There are some hacky solutions out there from before the official support, but can't find anything new after the release.

I ended up using the solution outlined [here on the ESLint docs](https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config). Not sure if there's a better solution currently, but it works for me in VS Code and when running `next` commands.

```mjs
// eslint.config.mjs
import { FlatCompat } from "@eslint/eslintrc"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
})

/** @type {import('eslint').Linter.Config[]} */
const configs = [
  ...compat.extends("next/core-web-vitals"),
  ...compat.extends("next/typescript"),
]

export default configs

```

**Comment by Sparticuz** [comment]
This should work
```ts
import nextPlugin from "@next/eslint-plugin-next";

export default [
  {
    name: "Next Plugin",
    plugins: {
      "@next/next": nextPlugin,
      rules: {
        ...nextPlugin.configs.recommended.rules,
        ...nextPlugin.configs["core-web-vitals"].rules,
      },
    },
  },
];
```

**Comment by hongz1** [comment]
@Sparticuz - It does not work. I ran "npm run lint", error message is shown: "Cannot convert undefined or null to object".

However, @Jochem-W approach works well.

**Comment by mcorbelli** [comment]
Do we know when ESLint 9 will be compatible with Next.js 15? Is there any roadmap?

**Comment by ztanner** [comment]
Thanks for the report! This has been addressed in https://github.com/vercel/next.js/pull/71371, which is currently on canary and will land on the next v15 stable.

**Comment by heresandyboy** [comment]
> Thanks for the report! This has been addressed in #71371, which is currently on canary and will land on the next v15 stable.

Hi, how can I get a look at what the exact correct recommended eslint setup is for the latest 15 canary?

**Comment by samcx** [comment]
@heresandyboy You can see it by toggling on `eslint` in the canary version of create next app!

```
pnpm create next-app@canary
```

**Comment by heresandyboy** [comment]
Thank you, I should have edited my post as that became obvious to me after writing! Thank you, it will help anyone else looking.

On that not though, I did think the latest version released was including the latest canary, ran that, got a json file for eslint, so had to manually upgrade to a mjs file to get everything to work as I wanted. Let me know if json is going to stop being default

**Comment by samcx** [comment]
> I did think the latest version released was including the latest canary, ran that, got a json file for eslint, so had to manually upgrade to a mjs file to get everything to work as I wanted.

Are you referring to this? When I checked, that hasn't been updated to use the flat config/v9 yet. →

```
pnpm create next-app@latest
```

For Create Next App, the default Eslint file will be the flat config.

**Comment by metatxn** [comment]
@samcx  i'm getting an error `Cannot serialize key parse in parser: Function values are not supported.` with create-next-app example when running `npm run lint`. This example uses ***next v15.1.0*** and ***eslint v9***. i'm using javascript.

**package.json**

```
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "next": "15.1.0"
  },
  "devDependencies": {
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "eslint": "^9",
    "eslint-config-next": "15.1.0",
    "@eslint/eslintrc": "^3"
  }
}

```

**eslint.config.mjs**

```
import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [...compat.extends("next/core-web-vitals")];

export default eslintConfig;

```

**Comment by samcx** [comment]
@metatxn I was not able to replicate this with Create Next App:

```
p create next-app@latest
```

![CleanShot 2024-12-12 at 08 49 08@2x](https://github.com/user-attachments/assets/09172b1d-ee22-480a-ba6d-deae5ffd9952)

**Comment by Ankit1598** [comment]
@samcx I believe there might be an issue with the JS version.

![image](https://github.com/user-attachments/assets/7473f947-cda5-4a29-8532-4dd8010c1859)

I tested the setup twice: once with the `--ts`(left) flag and the other time with the `--js`(right) flag. The test with `--ts` ran without any issues, but the one with `--js` failed with the error:
`Cannot serialize key "parse" in parser: Function values are not supported.`

**Comment by samcx** [comment]
@Ankit1598 I see. I was able to replicate the issue! Will be pinging the team.

**Comment by metatxn** [comment]
@samcx I was able to fix it using the below config in the `eslint.config.mjs` file. Basically its the same config as TS version.
```
const eslintConfig = [...compat.extends("next/core-web-vitals", "next/typescript")];
```

**Comment by srghma** [comment]
`const eslintConfig = [...compat.extends("next/core-web-vitals", "next/typescript")];`  and `pnpm install typescript`

**Comment by zhjrcc** [comment]
@srghma There's no need to do this：pnpm install typescript

**Comment by srghma** [comment]
@zhjrcc I generated my project with --js, I had an error `Cannot serialize key "parse" in parser: Function values are not supported` on `pnpm lint`

**Comment by metatxn** [comment]
> @samcx I was able to fix it using the below config in the `eslint.config.mjs` file. Basically its the same config as TS version.
> 
> ```
> const eslintConfig = [...compat.extends("next/core-web-vitals", "next/typescript")];
> ```

@srghma try this. it worked for me with JS verson as well.

**Comment by anvithshenoy** [comment]
> > @samcx I was able to fix it using the below config in the `eslint.config.mjs` file. Basically its the same config as TS version.
> > ```
> > const eslintConfig = [...compat.extends("next/core-web-vitals", "next/typescript")];
> > ```
> 
> @srghma try this. it worked for me with JS verson as well.

The command `npm run lint` works well with this. Although using `npx eslint .` would produce numerous errors along with some fixable warnings. Is there any fix for it? 

_PS: Sorry if it's a dumb question. I am currently learning as much as possible._
