### ISSUE TITLE
Dev with Turbo fails to parse CSS Modules :global

### ISSUE THREAD

**Issue by matheusgrieger** [vercel/next.js#71805]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/jovial-kilby-t95gx5

### To Reproduce

1. Start the application in dev with turbo mode
2. See CSS source parsing error

### Current vs. Expected behavior

Expected the CSS Modules to work with the `:global` selector, applying the styles accordingly as per [their documentation](https://github.com/css-modules/css-modules/blob/master/docs/composition.md#exceptions). This is especially important for styling third-party libraries. The current behavior throws a parsing error when on Turbo mode, but works fine on regular dev mode.

### Provide environment information

```bash
Node.js v18.20.3

Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  Available memory (MB): 19867
  Available CPU cores: 8
Binaries:
  Node: 18.20.3
  npm: 10.7.0
  Yarn: 4.5.1
  pnpm: N/A
Relevant Packages:
  next: 15.0.1
  eslint-config-next: 15.0.0-rc.1
  react: 19.0.0-rc-45804af1-20241021
  react-dom: 19.0.0-rc-45804af1-20241021
  typescript: 5.5.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by kdy1** [comment]
This is intentional. Please see `Unsupported features` section of https://lightningcss.dev/css-modules.html
