### ISSUE TITLE
Docs: unstable_cache recommendation to use 'use cache' directive link leads to 404

### ISSUE THREAD

**Issue by sombrilla** [vercel/next.js#71839]
### What is the documentation issue?

On the [unstable_cache](https://nextjs.org/docs/canary/app/api-reference/legacy-apis/unstable_cache) docs, there's a tip to use the directive 'use cache' with a link pointing to: https://nextjs.org/docs/canary/app/api-reference/legacy-apis/app/api-reference/directives/use-cache which leads to a 404.

Link should be pointing to: https://nextjs.org/docs/canary/app/api-reference/directives/use-cache

### Is there any context that might help us understand?

Unrelated to mentioned issue, but seems like `unstable_cache` is now a legacy API and recommendation is to use the `use cache` directive. During today's conference an example was shown live on how to use the new directive plus tag revalidation, which used both `unstable_cache` and `use cache`. 
Docs are not super clear on how to handle these cases.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/canary/app/api-reference/legacy-apis/unstable_cache

**Comment by gruckion** [comment]
Would be good to get a dead link checker in place too then.
