### ISSUE TITLE
Domain routing i18n adds default locale to link href's

### ISSUE THREAD

**Issue by gijsbotje** [vercel/next.js#71848]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/nice-bose-p9y9lt?workspaceId=8c42ce9b-a788-4790-894d-50229e1eadea

### To Reproduce

The codesandbox is a simplified setup of our site and config. This should be run with domain routing.

### Current vs. Expected behavior

In the example code, the link components that are resolved on the server, get the default locale as an infix. An example of where this happens is on [diamondsbyme.com/rings/](https://www.diamondsbyme.com/rings/). The menu and product links are structured as a relative link with the locale, even if it is the default locale (en) for that domain, resulting in the link being `https://www.diamondsbyme.com/en/rings/`.
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/eb4bc766-af12-4beb-bf40-a5ff9b3c1ad0">

This should just resolve to `https://www.diamondsbyme.com/rings/` on the server, as it did previously. On previous deployments this behavior wasn't present. When the link is resolved via client side routing, the default locale is not present in the href. This can be tested on the example link by navigating via the menu to, for example, “Men's rings”. The products will change and not have the default locale infix in the href, it even is the complete URL.
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/b6a9f1ac-38be-47d5-b5cc-72d9a1acf6c7">

Refreshing the page will include the default locale again as a relative link.
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/fb89d9dc-8e4d-4f82-bdd3-6bef57292de4">

I've downgraded to 14.2.10 and even to 14.2.3 but the issue still persists.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64
  Available memory (MB): 40960
  Available CPU cores: 16
Binaries:
  Node: 21.6.2
  npm: 10.2.4
  Yarn: 1.22.22
  pnpm: 9.12.2
Relevant Packages:
  next: 14.2.10 // An outdated version detected (latest is 15.0.1), upgrade is highly recommended!
  eslint-config-next: 14.2.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Internationalization (i18n), Navigation, Pages Router

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by gijsbotje** [comment]
When I look at the deployment output in Vercel, the links do not contain the locale. It's only the server HTML response that has this issue. Is there something that happens on the Vercel side that changed recently?

**Comment by gijsbotje** [comment]
I've also tried rolling back to old deployments that did not show this behavior. The version that cache that still existed for those old deploys showed the correct links, after a revalidation the same issue occurs.

**Comment by gijsbotje** [comment]
Some more details about the affected sites.

DiamondsByMe is hosted in 6 different projects on Vercel, each having their own domain for their locale. This was done to lower the total cost of hosting 6 languages from 1 project. They all use the same repository, therefore 'nl' being the overall default locale. Each domain is assigned one locale in the i18n configuration.

The domains are registered with Cloudflare and requests are proxied through there. No workers are active, only caching for the JSON files (which seem to be unaffected by this issue, as client side rendered links are correct).

**Comment by lubieowoce** [comment]
there's a trick to get domain-based locale working locally (in `next start`), you can do
```js
/** @type {import("next").NextConfig} */
const nextConfig = {
  // ...
  i18n: {
    domains: [
      {
        domain: "nl.localhost", // <------
        // domain: "www.my-site.nl",
        defaultLocale: "nl",
      },
      {
        domain: "be.localhost",
        // domain: "www.my-site.be",
        defaultLocale: "nl-be",
      },
      // ...
     ]
  },
};

module.exports = nextConfig;
```
and then navigate to `nl.localhost:3000`, `be.localhost:3000` etc in the browser. but i wasn't able to reproduce what you described in this setup, could you try and see if you can get it to do that?

also, do you see any difference in behavior between static and dynamic pages?

**Comment by gijsbotje** [comment]
@lubieowoce Thanks for that trick, I'm going to use that more often.

Running a production build locally with this config works as expected.

What I've found for the deployment on Vercel, is that the prerendered page is correct, but once revalidated the links are rendered with the relative subpath. It almost looks like the server is unaware of what domain it is generating a response.

**Comment by ijjk** [comment]
Hi, this appears to be working fine on deployment with shared configuration and `v14.2.17`. Going to close this out if you are still have issues please share additional information and we can investigate further!

**Comment by gijsbotje** [comment]
@ijjk I don't understand this conclusion. Your test deployment doesn't link to i18n routes, or another domain for a different locale.

**Comment by ijjk** [comment]
The fix for this has been rolled out, please re-deploy and give it a try!

**Comment by gijsbotje** [comment]
@ijjk Will there be a backport release for v14? I've tried upgrading to v15 but ran into a lot of errors.

**Comment by ijjk** [comment]
@gijsbotje a backport isn't necessary for this, should only require a redeploy

**Comment by gijsbotje** [comment]
@ijjk aah I see. https://www.diamondsbyme.com/ has the correct links now. Thanks for the fix!
