### ISSUE TITLE
nextjs 15 dynamic import does not support ssr: false

### ISSUE THREAD

**Issue by philipheinser** [vercel/next.js#71852]
### Link to the code that reproduces this issue

https://nextjs.org/docs/app/building-your-application/upgrading/version-15

### To Reproduce

nextjs 15 dynamic import does not support ssr: false

### Current vs. Expected behavior

before settings ssr false on dynamic import in server component worked now it errors. breaking change not mentioned in migration guide.

### Provide environment information

```bash
arm64
```

### Which area(s) are affected? (Select all that apply)

Lazy Loading

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

**Comment by huozhi** [comment]
There're few new changes could upgrade by applying with upgrade codemod, for `next/dynamic` change, checkout `next/dynamic` codemod for v15 in [codemod docs](https://nextjs.org/docs/app/building-your-application/upgrading/codemods#transform-nextdynamic-imports-accessing-named-exports-to-return-an-object-with-a-default-property)
