### ISSUE TITLE
Source map error when accessing .env variables

### ISSUE THREAD

**Issue by mtansk** [vercel/next.js#71854]
### Link to the code that reproduces this issue

https://github.com/mtansk/next-scheme-error

### To Reproduce

1. npm run dev
2. go to /page1
3. reload the page
4. get an error

### Current vs. Expected behavior

Expected: accessing .env variables without errors.
Current: console error every time you try to access .env vars.
![image](https://github.com/user-attachments/assets/543caa4e-22d3-4048-8b99-1014b661a8c6)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro     
  Available memory (MB): 16349
  Available CPU cores: 4      
Binaries:
  Node: 23.0.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2-canary.6 // Latest available version is detected (15.0.2-canary.6).
  eslint-config-next: N/A
  react: 19.0.0-rc-1631855f-20241023
  react-dom: 19.0.0-rc-1631855f-20241023
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, Runtime, Turbopack, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I tested only .env.local vars and only on dev. 
The first version the issue has been met is RC2 of 15.0.0

**Comment by mtansk** [comment]
I noticed that the issue sometimes disappeares by itself. I didn`t change any single line of code but now my reproduction example works as expected. When I try to restart it - the error is displayed again.

**Comment by aelassas** [comment]
@unstubbable I am having the exact same error and this is related to turbopack. I realized that I only get the error when I have chrome dev tools open. When I switch to webpack, I don't get any error even if chrome dev tools are open. I hope this wil be fixed soon.

**Comment by sinanptm** [comment]
`SourceMap "data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpudWxsLCJzZWN0aW9ucyI6W3sib2Zmc2V0Ijp7ImxpbmUiOjUsImNvbHVtbiI6MH0sInVybCI6bnVsbCwibWFwIjp7InZlcnNpb24iOjMsInNvdXJjZXMiOlsidHVyYm9wYWNrOi8vW3Byb2plY3RdL2NvbXBvbmVudHMvZm9ybXMvYXV0aC9SZWdpc3RlckZvcm0udHN4Il0sInNvdXJjZXNDb250ZW50IjpbIid1c2UgY2xpZW50JztcclxuXHJcbmltcG9ydCB7IG1lbW8sIHVzZVN0YXRlIH0gZnJvbSBcInJlYWN0XCI7XHJcbmltcG9ydCB7IHpvZFJlc29sdmVyIH0gZnJvbSBcIkBob29rZm9ybS9yZXNvbHZlcnMvem9kXCI7XHJcbmltcG9ydCB7IHVzZUZvcm0gfSBmcm9tIFwicmVhY3QtaG9vay1mb3JtXCI7XHJcbmltcG9ydCB7IEJ1dHRvbiB9IGZyb20gXCJAL2NvbXBvbmVudHMvdWkvYnV0dG9uXCI7XHJcbmltcG9ydCB7XHJcbiAgRm9ybSxcclxuICBGb3JtQ29udHJvbCxcclxuICBGb3JtRmllbGQsXHJcbiAgRm9ybUl0ZW0sXHJcbiAgRm9ybUxhYmVsLFxyXG4gIEZvcm1NZXNzYWdlLFxyXG59IGZyb20gXCJAL2NvbXBvbmVudHMvdWkvZm9ybVwiO1xyXG5pbXBvcnQgeyBJbnB1dCB9IGZyb20gXCJAL2NvbXBvbmVudHMvdWkvaW5wdXRcIjtcclxuaW1wb3J0IHsgVGV4dGFyZWEgfSBmcm9tIFwiQC9jb21wb25lbnRzL3VpL3RleHRhcmVhXCI7XHJcbmltcG9ydCB7IE11bHRpU2VsZWN0IH0gZnJvbSBcIkAvY29tcG9uZW50cy91aS9tdWx0aS1zZWxlY3RcIjtcclxuaW1wb3J0IHsgUmFkaW9Hcm91cCwgUmFkaW9Hcm91cEl0ZW0gfSBmcm9tIFwiQC9jb21wb25lbnRzL3VpL3JhZGlvLWdyb3VwXCI7XHJcbmltcG9ydCB7IENhcmQsIENhcmRDb250ZW50LCBDYXJkRGVzY3JpcHRpb24sIENhcmRIZWFkZXIsIENhcmRUaXRsZSB9IGZyb20gXCJAL2NvbXBvbmVudHMvdWkvY2FyZFwiO1xyXG5pbXBvcnQgeyBBdmF0YXIsIEF2YXRhckltYWdlLCBBdmF0YXJGYWxsYmFjayB9IGZyb20gXCJAL2NvbXBvbmVudHMvdWkvYXZhdGFyXCI7XHJcbmltcG9ydCB7IExvYWRlcjIgfSBmcm9tIFwibHVjaWRlLXJlYWN0XCI7XHJcbmltcG9ydCB7IEFWQVRBUklNQUdFUywgR0VOREVSLCBHRU5SRVMgfSBmcm9tICdAL2NvbnN0YW50cyc7XHJcbmltcG9ydCB7IHJlZ2lzdGVyRm9ybVNjaGVtYSB9IGZyb20gXCJAL2xpYi91dGlscy9mb3JtLXZhbGlkYXRpb25cIjtcclxuaW1wb3J0IHR5cGUgeyB6IH0gZnJvbSBcInpvZFwiO1xyXG5pbXBvcnQgeyBjcmVhdGVVc2VyIH0gZnJvbSBcIkAvYWN0aW9ucy91c2VyLmF1dGhcIjtcclxuaW1wb3J0IHsgR2VucmVzIH0gZnJvbSBcIkAvdHlwZXMvZW50aXRpZXNcIjtcclxuaW1wb3J0IHsgdG9hc3QgfSBmcm9tIFwiQC9ob29rcy91c2UtdG9hc3RcIjtcclxuaW1wb3J0IHsgdXNlUm91dGVyIH0gZnJvbSBcIm5leHQvbmF2aWdhdGlvblwiO1xyXG5cclxuY29uc3QgUmVnaXN0ZXJGb3JtID0gKCkgPT4ge1xyXG4gIGNvbnN0IFtpc0xvYWRpbmcsIHNldElzTG9hZGluZ10gPSB1c2VTdGF0ZShmYWxzZSk7XHJcbiAgY29uc3Qgcm91dGVyID0gdXNlUm91dGVyKCk7XHJcblxyXG4gIGNvbnN0IGZvcm0gPSB1c2VGb3JtPHouaW5mZXI8dHlwZW9mIHJlZ2lzdGVyRm9ybVNjaGVtYT4+KHtcclxuICAgIHJlc29sdmVyOiB6b2RSZXNvbHZlcihyZWdpc3RlckZvcm1TY2hlbWEpLFxyXG4gICAgZGVmYXVsdFZhbHVlczoge1xyXG4gICAgICB1c2VybmFtZTogXCJcIixcclxuICAgICAgZW1haWw6IFwiXCIsXHJcbiAgICAgIGFnZTogJycsXHJcbiAgICAgIHByZWZlcmVuY2U6IFtdLFxyXG4gICAgICBnZW5kZXI6IFwibWFsZVwiLFxyXG4gICAgICBiaW86IFwiXCIsXHJcbiAgICAgIHBhc3N3b3JkOiBcIlwiLFxyXG4gICAgICBjb25maXJtUGFzc3dvcmQ6IFwiXCIsXHJcbiAgICAgIG5hbWU6IFwiXCIsXHJcbiAgICAgIGltYWdlOiBBVkFUQVJJTUFHRVNbMF1cclxuICAgIH0sXHJcbiAgfSk7XHJcblxyXG4gIGFzeW5jIGZ1bmN0aW9uIG9uU3VibWl0KHsgcHJlZmVyZW5jZSwgYWdlLCBjb25maXJtUGFzc3dvcmQsIHBhc3N3b3JkLCAuLi52YWx1ZXMgfTogei5pbmZlcjx0eXBlb2YgcmVnaXN0ZXJGb3JtU2NoZW1hPikge1xyXG4gICAgdHJ5IHtcclxuICAgICAgc2V0SXNMb2FkaW5nKHRydWUpO1xyXG4gICAgICBpZiAoY29uZmlybVBhc3N3b3JkICE9PSBwYXNzd29yZCkge1xyXG4gICAgICAgIGZvcm0uc2V0RXJyb3IoJ2NvbmZpcm1QYXNzd29yZCcsIHsgbWVzc2FnZTogJ1Bhc3N3b3JkcyBkbyBub3QgbWF0Y2gnIH0pO1xyXG4gICAgICAgIHJldHVybjtcclxuICAgICAgfVxyXG4gICAgICBjb25zdCByZXNwb25zZSA9IGF3YWl0IGNyZWF0ZVVzZXIoe1xyXG4gICAgICAgIGFnZTogYWdlLFxyXG4gICAgICAgIHByZWZlcmVuY2VzOiBwcmVmZXJlbmNlIGFzIEdlbnJlc1tdLFxyXG4gICAgICAgIHBhc3N3b3JkLFxyXG4gICAgICAgIC4uLnZhbHVlc1xyXG4gICAgICB9KTtcclxuXHJcbiAgICAgIGlmIChyZXNwb25zZSkge1xyXG4gICAgICAgIGlmIChyZXNwb25zZS5jb2RlID09PSA0MDkpIHtcclxuICAgICAgICAgIGZvcm0uc2V0RXJyb3IoXCJlbWFpbFwiLCB7IG1lc3NhZ2U6IHJlc3BvbnNlLm1lc3NhZ2UgfSk7XHJcbiAgICAgICAgfVxyXG4gICAgICB9IGVsc2Uge1xyXG4gICAgICAgIHRvYXN0KHtcclxuICAgICAgICAgIHRpdGxlOiBcIlJlZ2lzdHJhdGlvbiBTdWNjZXNzZnVsIPCfmoAuIFBsZWFzZSBMb2dpbiB0byBjb250aW51ZVwiLFxyXG4gICAgICAgICAgdmFyaWFudDogXCJzdWNjZXNzXCJcclxuICAgICAgICB9KTtcclxuICAgICAgICBmb3JtLnJlc2V0KCk7XHJcbiAgICAgICAgcm91dGVyLnB1c2goJy9sb2dpbicpO1xyXG4gICAgICB9XHJcbiAgICB9IGNhdGNoIChlcnJvcikge1xyXG4gICAgICBjb25zb2xlLmVycm9yKFwiUmVnaXN0cmF0aW9uIGZhaWxlZDpcIiwgZXJyb3IpO1xyXG4gICAgfSBmaW5hbGx5IHtcclxuICAgICAgc2V0SXNMb2FkaW5nKGZhbHNlKTtcclxuICAgIH1cclxuICB9XHJcblxyXG4gIHJldHVybiAoXHJcbiAgICA8Q2FyZCBjbGFzc05hbWU9XCJ3LWZ1bGwgbXQtNlwiPlxyXG4gICAgICA8Q2FyZEhlYWRlciBjbGFzc05hbWU9XCJzcGFjZS15LTFcIj5cclxuICAgICAgICA8Q2FyZFRpdGxlIGNsYXNzTmFtZT1cInRleHQtMnhsIGZvbnQtYm9sZFwiPkNyZWF0ZSBhbiBhY2NvdW50PC9DYXJkVGl0bGU+XHJcbiAgICAgICAgPENhcmREZXNjcmlwdGlvbj5cclxuICAgICAgICAgIEVudGVyIHlvdXIgZGV0YWlscyBhbmQgcHJlZmVyZW5jZXMgdG8gZ2V0IHN0YXJ0ZWRcclxuICAgICAgICA8L0NhcmREZXNjcmlwdGlvbj5cclxuICAgICAgPC9DYXJkSGVhZGVyPlxyXG4gICAgICA8Q2FyZENvbnRlbnQ+XHJcbiAgICAgICAgPEZvcm0gey4uLmZvcm19PlxyXG4gICAgICAgICAgPGZvcm0gb25TdWJtaXQ9e2Zvcm0uaGFuZGxlU3VibWl0KG9uU3VibWl0KX0gY2xhc3NOYW1lPVwic3BhY2UteS02XCI+XHJcbiAgICAgICAgICAgIDxGb3JtRmllbGRcclxuICAgICAgICAgICAgICBjb250cm9sPXtmb3JtLmNvbnRyb2x9XHJcbiAgICAgICAgICAgICAgbmFtZT1cIm5hbWVcIlxyXG4gICAgICAgICAgICAgIHJlbmRlcj17KHsgZmllbGQgfSkgPT4gKFxyXG4gICAgICAgICAgICAgICAgPEZvcm1JdGVtPlxyXG4gICAgICAgICAgICAgICAgICA8Rm9ybUxhYmVsPkZ1bGwgTmFtZSAqPC9Gb3JtTGFiZWw+XHJcbiAgICAgICAgICAgICAgICAgIDxGb3JtQ29udHUnderstand this warningAI`



also getting this log in Browser console  sometimes 

I thinks these two errors are related

**Comment by mniesen** [comment]
Could some give some example code of a page when this error occurs? (preferably the entire code of that page)

**Comment by aelassas** [comment]
@mniesen To reproduce the error:
- git clone https://github.com/mtansk/next-scheme-error
- cd next-scheme-error
- npm install
- npm run dev
- Go to http://localhost:3000 and open chrome dev tools
- go to /page1
- reload the page
- get an error

**Comment by alexfurtado22** [comment]
> @unstubbable I am having the exact same error and this is related to turbopack. I realized that I only get the error when I have chrome dev tools open. I don't get the error when chrome dev tools are closed.
> 
> When I switch to webpack, I don't get any error even if chrome dev tools are open.
> 
> I hope this wil be fixed soon.

You are right!  only when chrome dev tools are open.

**Comment by alexfurtado22** [comment]
You are right! only when chrome dev tools are open.

**Comment by dimitrov93** [comment]
I can confirm that the error occurs only when Dev Tools is open. Any fix?

**Comment by unstubbable** [comment]
> I can confirm that the error occurs only when Dev Tools is open. Any fix?

@dimitrov93 @alexfurtado22 The source mapping issues on Windows have been fixed in [15.0.3](https://github.com/vercel/next.js/releases/tag/v15.0.3) (via #72139). If you still encounter these errors under different circumstances, please open a new issue with a reproduction using the latest version. Feel free to tag me in the issue.

**Comment by alexfurtado22** [comment]
nope !! I can not resolve.

 i tried disable source maps in development:
 
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  productionBrowserSourceMaps: false,
 
};

export default nextConfig;

Still the same erro, only when chrome dev tools are open

 ▲ Next.js 15.0.2 (Turbopack)
   - Local:        http://localhost:3000
   - Environments: .env.local

 ✓ Starting...
 ✓ Ready in 5.3s
 ○ Compiling / ...
 ✓ Compiled / in 9.3s
 GET / 200 in 10915ms
Failed to get source map: [Error: Unknown url scheme] { code: 'GenericFailure' }

**Comment by alexfurtado22** [comment]
That's right

**Comment by alexfurtado22** [comment]
Upgrade to Next.js 15.0.3 solve the issue
