### ISSUE TITLE
Next.js 15 import alias not working with turbopack

### ISSUE THREAD

**Issue by aelassas** [vercel/next.js#71879]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32593
  Available CPU cores: 12
Binaries:
  Node: 20.17.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

turbopack

### Describe the Bug

I have a Next.js 15 project with two internal packages:
```
| - next-app/
| - packages/package1/
| - packages/package2/
```
I added aliases in tsconfig.json:
```js
{
  "compilerOptions": {
   ...
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"],
      ":package1": ["../packages/package1"],
      ":package2": ["../packages/package2"]
    },
  }
}
```
I have components using `:package1` and `:package2`:
```js
import * as package1 from ':package1'
import * as package2 from ':package2'

...
```

When I run the dev server without turbopack, it works fine. But when I try with turbopack I always get theses errors:
```
Module not found: Can't resolve ':package1'
Import map: aliased to relative "../packages/package1" inside of [project]/

Module not found: Can't resolve ':package2'
Import map: aliased to relative "../packages/package2" inside of [project]/
```

### Expected Behavior

It should import aliases without any error like without turbopack.

### To Reproduce

Create a Next.js 15 project with an internal package `package1`:
```
| - next-app/
| - packages/package1/
```
Add the alias in tsconfig.json:
```js
{
  "compilerOptions": {
   ...
    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*"],
      ":package1": ["../packages/package1"],
    },
  }
}
```

Import `:package1` in a page or component:
```js
import * as package1 from ':package1'
...
```

Run the dev server with turbopack.

**Comment by samcx** [comment]
@aelassas Please re-submit a new issue with this [issue template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml) so we have the right info to triage the issue!

**Comment by LukasDeco** [comment]
@aelassas did you open a new issue or find a solution? This is the exact problem I am having.

**Comment by aelassas** [comment]
@LukasDeco I opened a new issue: #71886
