### ISSUE TITLE
Fetch calls inside "use cache" functions cannot be revalidated

### ISSUE THREAD

**Issue by 0xd8d** [vercel/next.js#71924]
### Link to the code that reproduces this issue

https://github.com/DaniumX/Next.js-15-canary-use-cache-revalidate-bug

### To Reproduce

1. Start the project in dev mode
2. Click the "Purge Cache" button
3. Watch the function rerun (as proven by the console log) but the fetch call returning cached data

### Current vs. Expected behavior

Current behavior: The fetch call inside the revalidated function returns cached data.
Expected behavior: The fetch call inside the revalidated function returns fresh data, as it has no explicit cache headers.

https://github.com/user-attachments/assets/4f6d6cb9-9aaa-400e-8043-d41e5847f628

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 9.12.0
Relevant Packages:
  next: 15.0.2-canary.8 // Latest available version is detected (15.0.2-canary.8).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-1631855f-20241023
  react-dom: 19.0.0-rc-1631855f-20241023
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

**Comment by samcx** [comment]
@0xd8d Thank you for submitting an issue!

I was not able to replicate this.

Can you make sure you're on the latest React RC as well?

![CleanShot 2024-10-28 at 16 03 11@2x](https://github.com/user-attachments/assets/d0ba0f3b-2813-4c6c-8efa-740a59165f8b)

**Comment by 0xd8d** [comment]
> @0xd8d Thank you for submitting an issue!
> 
> I was not able to replicate this.
> 
> Can you make sure you're on the latest React RC as well?
> 
> ![CleanShot 2024-10-28 at 16 03 11@2x](https://private-user-images.githubusercontent.com/28912696/380917494-d0ba0f3b-2813-4c6c-8efa-740a59165f8b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTA2MTUsIm5iZiI6MTczMDE5MDMxNSwicGF0aCI6Ii8yODkxMjY5Ni8zODA5MTc0OTQtZDBiYTBmM2ItMjgxMy00YzZjLThlZmEtNzQwYTU5MTY1ZjhiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwM2Y4OGMzODdmNWZhYjMxNGNmNzNiOGMxMjQ4NjA1YWM0ODYzMGIxYjNjNDI4ZmFlYTUzNzlmOWZmYTJhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GWLJ57A2kT96pTN3mMHyFlSJ1y1ujBzcSw2Jykp9zfM)

That is so odd. I tried the latest RC as well, that made no difference. Below is a video detailing the exact steps I reckon you took to try to reproduce, so why aren't you able to but I am?


https://github.com/user-attachments/assets/7bc8362d-b673-49f8-bff9-6656c008e0ca

**Comment by samcx** [comment]
@0xd8d Can you also try refreshing your page and seeing if the problem persists?

**Comment by apostolos** [comment]
@0xd8d @samcx I'm seeing the same problem.

Here is a further reduced repro: https://codesandbox.io/p/github/apostolos/revalidate-tag/main

The value stays the same even after a refresh. Only revalidatePath forces the page to re-render.

I also went back until I found the canary build that introduced the problem. It was working up to v15.0.2-canary.6, something introduced the problem in v15.0.2-canary.7. Most likely this: https://github.com/vercel/next.js/pull/71793

**Comment by 0xd8d** [comment]
> @0xd8d @samcx I'm seeing the same problem.
> 
> Here is a further reduced repro: https://codesandbox.io/p/github/apostolos/revalidate-tag/main
> 
> The value stays the same even after a refresh. Only revalidatePath forces the page to re-render.
> 
> I also went back until I found the canary build that introduced the problem. It was working up to v15.0.2-canary.6, something introduced the problem in v15.0.2-canary.7. Most likely this: #71793

Thank god I'm not the only one. I was pulling my hair trying to figure out why I seem to be the only one experiencing this. I guess I'll downgrade to canary.6 in the meantime.

**Comment by unstubbable** [comment]
The error is tricky to reproduce, because it is masked when DevTools are open and the "Disable cache" checkbox is checked.
