### ISSUE TITLE
IOS Mobile Browser Back button incorrect routing on safari and chrome using nextjs 12.3.4 (Working fine on desktop and with router.back()))

### ISSUE THREAD

**Issue by sagardhamani-acko** [vercel/next.js#71953]
### Verify canary release

- [ ] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
"next": "^10.0.8",
 "next-redux-wrapper": "^8.1.0",
```

### Which example does this report relate to?

nextjs 12.3.4 

### What browser are you using? (if relevant)

IOS mweb safari and chrome

### Describe the Bug

We have build a multi-page journey using nextjs 12.3.4 where at some pages when we click back button it takes to some random page mostly the entry page of the journey. 
Tried a lot of debugging and even remove the router replace logic but no clue found yet.

The same thing is working great on desktop and also on the back button header on our page which we are handling using router.back()

Current issue 
1. entrypage --> 2. details page --> 3. personal details page --> 4.products page 

On click of back on products page the browser takes back to the entry page. Back button on 2 and 3 page works totally fine

### Expected Behavior

should go to 3 page when back clicked on 4 page

### To Reproduce

Not deployed anywhere yet.

**Comment by samcx** [comment]
@sagardhamani-acko Please re-submit your issue using the other [issue template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml), that way we have all info we need to triage your issue!
