### ISSUE TITLE
[turbopack] issues with module resolution (warnings) since recent Next.js 14.

### ISSUE THREAD

**Issue by ovflowd** [vercel/next.js#71998]
### Link to the code that reproduces this issue

https://github.com/nodejs/nodejs.org

### To Reproduce

1. Start `next dev` (or `turbo dev` or `npm run dev`
2. Warnings appear (not sure if they are bad or actionable)

### Current vs. Expected behavior

Current:

Warnings.

Expected:

No Warnings.

### Provide environment information

```bash
npx --no-install next info

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.11.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 14.2.15 // An outdated version detected (latest is 15.0.1), upgrade is highly recommended!
  eslint-config-next: 15.0.0-rc.1
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
 ⚠ An outdated version detected (latest is 15.0.1), upgrade is highly recommended!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by timneutkens** [comment]
Followed the reproduction steps but nothing shows up. 

```
• Packages in scope: @node-core/website, @node-core/website-i18n
• Running dev in 2 packages
• Remote caching disabled
@node-core/website:dev: cache bypass, force executing adf6fd09b8f6791e
@node-core/website:dev:
@node-core/website:dev: > dev
@node-core/website:dev: > cross-env SENTRY_SUPPRESS_TURBOPACK_WARNING=1 NODE_NO_WARNINGS=1 next dev --turbo
@node-core/website:dev:
  ▲ Next.js 14.2.15 (turbo)
@node-core/website:dev:   - Local:        http://localhost:3000
@node-core/website:dev:   - Experiments (use with caution):
@node-core/website:dev:     · turbo
@node-core/website:dev:     · largePageDataBytes
@node-core/website:dev:     · webpackBuildWorker
@node-core/website:dev:     · ...
@node-core/website:dev:
@node-core/website:dev:  ✓ Starting...
@node-core/website:dev:  ✓ Compiled in 556ms
@node-core/website:dev:  ✓ Ready in 2.2s
@node-core/website:dev:  ○ Compiling /[locale]/[[...path]] ...
@node-core/website:dev:  ✓ Compiled /[locale]/[[...path]] in 4.9s
@node-core/website:dev:  ✓ Compiled /[locale]/next-data/release-data in 135ms
@node-core/website:dev:  GET /en/next-data/release-data 200 in 770ms
@node-core/website:dev:  GET /en 200 in 6815ms
```

Seems you're also using Turbopack on 14.x where it was experimental. It's stable in Next.js 15.

Going to close this issue as there is no further investigation possible as the mentioned errors are not shared in the issue description. Feel free to open a new issue with more details 🙂

**Comment by ovflowd** [comment]
Hey there 👋 I forgot to mention you should actually open https://localhost:3000 on the browser first.

Also, this issue was not happening on any version prior the latest version of 14.x and we cannot upgrade yet to 15.x

**Comment by ovflowd** [comment]
Also, @timneutkens this is the logs we were getting:

```

@node-core/website:dev: WARN: resolving pattern (<dynamic> "/" <dynamic> "/" <dynamic> | <dynamic> "/" <dynamic> | <dynamic> "/" <dynamic> | <dynamic>) in [project]/apps/site leads to 27123 results
@node-core/website:dev: WARN: resolving pattern (<dynamic> "/pages" | <dynamic> "pages" | <dynamic> "/" <dynamic> "/" <dynamic> | <dynamic> "/" <dynamic> | <dynamic> "/" <dynamic> | <dynamic>) in [project]/apps/site leads to 27123 results
```

**Comment by timneutkens** [comment]
When you're on Next.js 14 you're missing hundreds of bugfixes as Turbopack was only marked as release candidate in Next.js 15 RC.1, would recommend upgrading first then checking if it still happens, if it still happens we can investigate.

I did open all routes I could navigate to, home as well as download and a bunch of the other routes in the application, didn't see those logs

**Comment by ovflowd** [comment]
> When you're on Next.js 14 you're missing hundreds of bugfixes as Turbopack was only marked as release candidate in Next.js 15 RC.1, would recommend upgrading first then checking if it still happens, if it still happens we can investigate.
> 
> 
> 
> I did open all routes I could navigate to, home as well as download and a bunch of the other routes in the application, didn't see those logs

Maybe worth mentioning OS was Windows? Could be an OS-specific bug.

I get that Next 15 id way better, but we're open source, short on resources, we'll try to upgrade as soooon as possible. Maybe it is as easy as just running the codemod!

**Comment by ovflowd** [comment]
@timneutkens can we reopen this issue? Reproducible with Next.15:

```
turbo 2.2.3

• Packages in scope: @node-core/website, @node-core/website-i18n
• Running dev in 2 packages
• Remote caching disabled
@node-core/website:dev: cache bypass, force executing a381b34af4d8546f
@node-core/website:dev: 
@node-core/website:dev: > dev
@node-core/website:dev: > cross-env SENTRY_SUPPRESS_TURBOPACK_WARNING=1 NODE_NO_WARNINGS=1 next dev --turbopack
@node-core/website:dev: 
   ▲ Next.js 15.0.2 (Turbopack)
@node-core/website:dev:    - Local:        http://localhost:3000
@node-core/website:dev:    - Experiments (use with caution):
@node-core/website:dev:      · turbo
@node-core/website:dev:      · largePageDataBytes
@node-core/website:dev:      · webpackBuildWorker
@node-core/website:dev:      · ...
@node-core/website:dev: 
@node-core/website:dev:  ✓ Starting...
@node-core/website:dev:  ✓ Compiled in 1153ms
@node-core/website:dev:  ✓ Ready in 2.7s
@node-core/website:dev:  ○ Compiling /[locale]/[[...path]] ...
@node-core/website:dev: WARN: resolving pattern (<dynamic> "/pages" | <dynamic> "pages" | <dynamic> "/" <dynamic> "/" <dynamic> | <dynamic> "/" <dynamic> | <dynamic> "/" <dynamic> | <dynamic>) in [project]/apps/site leads to 28965 results
@node-core/website:dev: WARN: resolving pattern (<dynamic> "/" <dynamic> "/" <dynamic> | <dynamic> "/" <dynamic> | <dynamic> "/" <dynamic> | <dynamic>) in [project]/apps/site leads to 28965 results
@node-core/website:dev:  ✓ Compiled /[locale]/[[...path]] in 10.1s
```

This is really annoying us. Can we use the 🃏 (card) of that we are an Enterprise customer too?

**Comment by timneutkens** [comment]
Did some digging and seems it might be OS specific, could you try cloning a clean version of the repository to double check it's not some leftover files etc. that cause the problem?

Related code: https://github.com/vercel/next.js/blob/1ce3913ef13a22c03d795df7cc8eec2cf0a7ee37/turbopack/crates/turbopack-core/src/resolve/mod.rs#L1377

Will ask someone on the team to take a look with Windows.

**Comment by ovflowd** [comment]
I forgot to mention it happened on macOS this time 🫠

**Comment by ovflowd** [comment]
Let me know if I can provide additional data! This is the PR with Next.js 15 -- https://github.com/nodejs/nodejs.org/pull/7155

**Comment by timneutkens** [comment]
Tried running it with the same steps on the PR but still not seeing the issue 😢

```
npm run dev

> dev
> turbo run dev

turbo 2.2.3

• Packages in scope: @node-core/website, @node-core/website-i18n
• Running dev in 2 packages
• Remote caching disabled
@node-core/website:dev: cache bypass, force executing 9a7f02565e86a3c7
@node-core/website:dev:
@node-core/website:dev: > dev
@node-core/website:dev: > cross-env SENTRY_SUPPRESS_TURBOPACK_WARNING=1 NODE_NO_WARNINGS=1 next dev --turbopack
@node-core/website:dev:
   ▲ Next.js 15.0.2 (Turbopack)
@node-core/website:dev:    - Local:        http://localhost:3000
@node-core/website:dev:    - Experiments (use with caution):
@node-core/website:dev:      · turbo
@node-core/website:dev:      · largePageDataBytes
@node-core/website:dev:      · webpackBuildWorker
@node-core/website:dev:      · ...
@node-core/website:dev:
@node-core/website:dev:  ✓ Starting...
@node-core/website:dev:  ✓ Compiled in 601ms
@node-core/website:dev:  ✓ Ready in 2.8s
@node-core/website:dev:  ○ Compiling /[locale]/[[...path]] ...
@node-core/website:dev:  ✓ Compiled /[locale]/[[...path]] in 5s
@node-core/website:dev:  ✓ Compiled /[locale]/next-data/release-data in 189ms
@node-core/website:dev:  GET /en/next-data/release-data 200 in 802ms
@node-core/website:dev:  GET /en 200 in 7013ms
```

**Comment by ovflowd** [comment]
Would it worth for me to add my .next folder?

**Comment by timneutkens** [comment]
Hmm I don't think the `.next` folder will have an effect unless you're somehow trying to import files from there, but yeah feel free to send it over as well.

**Comment by ovflowd** [comment]
Funny enough I wasn't able to reproduce it again :( -- Let's close this for now ✨

**Comment by timneutkens** [comment]
Thanks Claudio, let me know if you run into it again!
