### ISSUE TITLE
console logging circular references in Server Components causes error

### ISSUE THREAD

**Issue by souporserious** [vercel/next.js#72004]
### Link to the code that reproduces this issue

https://github.com/souporserious/next-15-circular-reference-console-bug

### To Reproduce

Try console logging a complex object like a class that has circular references in a Server Component:

```tsx
class A {
  other: B | null
  constructor() {
    this.other = null
  }
}

class B {
  a: A
  constructor(a: A) {
    this.a = a
    a.other = this
  }
}

const objA = new A()
const objB = new B(objA)

export default function Page() {
  console.log({ objA, objB })
  return null
}
```

You should get an error like this:

<img width="995" alt="image" src="https://github.com/user-attachments/assets/ddc467d2-10da-4b0e-ab6c-13f62195c346">

Downgrading to v14 works as expected.

### Current vs. Expected behavior

Any value should be able to be console logged.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
Binaries:
  Node: 21.2.0
  npm: 10.8.1
  Yarn: 1.22.21
  pnpm: 9.9.0
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: N/A
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by timneutkens** [comment]
@samcx can you triage this to the correct area? It's not related to webpack/Turbopack 👍

**Comment by samcx** [comment]
@souporserious Thank you for submitting an issue.

I was able to replicate the issue. Not sure what happened here, so we'll be taking a look!
