### ISSUE TITLE
Module parse failed: Bad character escape sequence

### ISSUE THREAD

**Issue by ultronstudio** [vercel/next.js#72014]
### Link to the code that reproduces this issue

https://github.com/ultronstudio/gomegle

### To Reproduce

1. Create new project using `npx create-next-app@latest [directory]`
2. Run dev after creating the project `npm run dev`
3. Visit localhost:3000

### Current vs. Expected behavior

I'm seeing this error now, but i expect no error at first run
![image](https://github.com/user-attachments/assets/b86433c1-a7ec-4439-8ed6-a8b586d0ef9f)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro Education
  Available memory (MB): 7489
  Available CPU cores: 12
Binaries:
  Node: 23.1.0
  npm: 10.9.0
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by dualdetail** [comment]
This is fixed in v15.0.2-canary.10. Try installing that version of nextjs and see if it works. Or you could wait until 15.0.2 is released
