### ISSUE TITLE
'TypeError: e.type._context is undefined' in some browsers

### ISSUE THREAD

**Issue by MartinGamesCZ** [vercel/next.js#72023]
### Link to the code that reproduces this issue

https://github.com/MartinGamesCZ/Newtonium_docs

### To Reproduce

1. Clone my project or even create new using "create-next-app", I used tailwind, app router and turbopack. You can do it without turbopack, not sure about tailwind and app router. Next v15 is required!
2. Start dev script (npm run dev / bun dev / yarn dev / ...)
3. Open the page in Zen browser (mozilla based, should also occur there, but I did not test that)

### Current vs. Expected behavior

Expected: The page just works
Current: The page works, but it spams error message below, and it slowly starts to lag the page (at least on my 2 core system)

![obrazek](https://github.com/user-attachments/assets/ff10252f-2494-475e-839a-f3b811ae82fd)

ConsoleError@http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_e72844._.js:695:9
handleClientError@http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_e72844._.js:794:17
[project]/node_modules/next/dist/client/components/globals/intercept-console-error.js [app-client] (ecmascript)/patchConsoleError/window.console.error@http://localhost:3000/_next/static/chunks/node_modules_next_dist_client_e72844._.js:907:56
overrideMethod@<anonymous code>:1:145535
i@http://localhost:3000/:10:2727
_/t.onCommitFiberRoot<@http://localhost:3000/:10:3052
onCommitRoot$1@http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:864:26
commitRootImpl@http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8090:23
commitRoot@http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8033:95
commitRootWhenReady@http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7647:19
performWorkOnRoot@http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:7623:44
performWorkOnRootViaSchedulerTask@http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_react-dom_1f56dc._.js:8379:26
performWorkUntilDeadline@http://localhost:3000/_next/static/chunks/node_modules_next_dist_compiled_107ce8._.js:2352:72

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2
  Available memory (MB): 9890
  Available CPU cores: 4
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: 8.14.1
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: N/A
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Runtime

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Tested only in Mozilla-based Zen browser, should also occur in Firefox, but I did not test that. Looks like client side issue, no errors on server-side. Occurs with and without turbopack. Does not occur on Chrome. Next v14 works as expected.

**Comment by MartinGamesCZ** [comment]
Tested on newest firefox, does not occur there. Only the Zen browser.

**Comment by MartinGamesCZ** [comment]
Works in incognito, probably issue with cache/some extension. When clicking on some error, I saw this:
![obrazek](https://github.com/user-attachments/assets/af1db395-9d33-4c04-923b-6338798fd456)

**Comment by MartinGamesCZ** [comment]
The problem disappears when disabling this extension: https://addons.mozilla.org/cs/firefox/addon/react-context-devtool/
Sorry for opening this issue if it is irrelevant, tested it a lot before opening the issue, did not think of extensions.

**Comment by ztanner** [comment]
Glad to hear you figured it out!
