### ISSUE TITLE
Docs: How to get started with turbopack?

### ISSUE THREAD

**Issue by badtant** [vercel/next.js#72025]
### What is the documentation issue?

Hi,

I'm updating to 15.0.1 and want to try turbopack when developing. I cant get it going though and the docs doesn't seem to help.

I'm adding --turbo to `next dev --turbo` (should it be --turbo or --turbopack?)
Then I'm getting this message "Webpack is configured while Turbopack is not, which may cause problems."
I'm looking at the link provided with the message (https://nextjs.org/docs/app/api-reference/next-config-js/turbo) and its suggesting to add turbo to my next config.

I'm adding `turbo: {}` and still getting the same message...
-  `turbo` isn't a part of the type NextConfig which confused me alot
-  I have webpack conf, should I duplicate that into turbo or should I migrate it to turbo or should I have both?

Thanks

### Is there any context that might help us understand?

Nothing more to add

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/next-config-js/turbo

**Comment by samcx** [comment]
@badtant Webpack configuration is not supported in Turbopack, but some loaders are supported → https://nextjs.org/docs/architecture/turbopack#unsupported-features.
