### ISSUE TITLE
 Failed to load external module next/dist/compiled/next-server/app-page.runtime.dev.js

### ISSUE THREAD

**Issue by georgefrg** [vercel/next.js#72077]
### Link to the code that reproduces this issue

https://github.com/georgefrg/test.git

### To Reproduce

1.Initialize nextjs project on windows 11 using turbopack. 
2.Run npm run dev
3.Compile and the error pops up
"Error: Failed to load external module next/dist/compiled/next-server/app-page.runtime.dev.js: TypeError: maybeGlobalAsyncLocalStorage.snapshot is not a function"

### Current vs. Expected behavior

i expected to see the initial nextjs project landing page and instead got the error mentioned above

### Provide environment information

```bash
Platform: win32
  Arch: x64
  Version: Windows 10 Home
  Available memory (MB): 7937
  Available CPU cores: 4
Binaries:
  Node: 19.7.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Script (next/script)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

this issue started after i upgraded to next 15 on my first project on the version

**Comment by k-boiko** [comment]
same here on MacOS 15.0.1

**Comment by alexbangert** [comment]
Same error here with upgraded project and [provided Link](https://github.com/georgefrg/test.git):

```
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:33 +0000
  Available memory (MB): 31984
  Available CPU cores: 32
Binaries:
  Node: 19.7.0
  npm: 9.5.0
  Yarn: 1.22.22
  pnpm: 9.12.3
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: N/A
Next.js Config:
  output: N/A
```

Error for  [provided Link](https://github.com/georgefrg/test.git) is not reproducable using following system:
```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.9.0
  npm: 10.2.1
  Yarn: 1.22.22
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.3
Next.js Config:
```

**Comment by devjiwonchoi** [comment]
Hi, thank you for reporting the issue!
The root cause of the issue is that `AsyncLocalStorage.snapshot` [was added in](https://nodejs.org/api/async_context.html#static-method-asynclocalstoragesnapshot) Node.js `19.8.0, 18.16.0`, but your Node.js version was `19.7.0`.

We improved the information about the supported Node.js version range at https://github.com/vercel/next.js/pull/72087 and published it in [15.0.3-canary.2](https://github.com/vercel/next.js/releases/tag/v15.0.3-canary.2).

Thank you again for the reporting!

**Comment by reydoblas** [comment]
Hi devjiwonchoi,

I am having the same issue after upgrading to Next.js 15 even when I am having Node v23.1.0, and even tried lower versions up to v18. I had already started a community discussion here https://github.com/vercel/next.js/discussions/72074 . Below are my setup details

OS: Ubuntu 24.04 LTS
Node: v23.1.0
npm: 10.9.0
React: 18.3.1

Any idea why it is still happening to me even with compatible versions of Node?

Thanks.

**Comment by devjiwonchoi** [comment]
@reydoblas When using the App Router, you need the React **RC** version.

```json
"dependencies": {
  "react": "19.0.0-rc.0",
  "react-dom": "19.0.0-rc.0"
}
```

Could you try the following and install the RC version of React?

**Comment by reydoblas** [comment]
@devjiwonchoi I've tried your suggestion but it breaks my other packages such as `Ant Design` due to dependency error. It might be that those packages doesn't support yet React 19 version since it is still an RC.
