### ISSUE TITLE
Passing const with JSX into client component throws error 

### ISSUE THREAD

**Issue by teamkuka** [vercel/next.js#72092]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16228
  Available CPU cores: 8
Binaries:
  Node: 20.12.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

app

### Describe the Bug

A const object that contains icons from "lucide-react" passed from a server component to a client component errors out with
```
[ Server ] Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
  {$$typeof: ..., render: function <IconName>}
```
Nextjs probably considers the use of JSX in a const as a function.

### Expected Behavior

I could display the Lucide Icons easily by passing that const (that is not a function!) to a client component

### To Reproduce

I define a const using icons from "lucide-react" in navElements.tsx
```
export const navElements = [
    { name: "Dashboard", url: ROUTES.dashboard, icon: HomeIcon},
    { name: "Account", url: ROUTES.account, icon: UserIcon},
    ...
  ] as const;
```
I pass this const from a static (server) component to a client component

` <ClientComp dashboardNavElements={dashboardNavElements} />`

```
"use client";

export default function ClientComponent({ dashboardNavElements }) {
  console.log(dashboardNavElements);
  return <div>Errors out</div>;
}
```

**Comment by teamkuka** [comment]
I had to use .tsx and not .ts where i declared my const. 
My bad. I close that

**Comment by osmandvc** [comment]
> Nextjs probably considers the use of JSX in a const as a function.

JSX under the hood is exactly that. It just gets transpiled into actual React function calls, which generate your components. One fix to your issue would be to pass the icons in a client component rather than server component.

**Comment by teamkuka** [comment]
Thank you for your answer and probably solution.
I actually managed to get it working using directly the jsx in my const
from
`icon: UserIcon`

to 
```
 icon: (
        <HomeIcon className="h-4 w-4 text-zinc-500 group-hover:text-zinc-700" />
      ),
```

Closing this.
