### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by Devian1988** [vercel/next.js#72130]
### Missing documentation about not to use folder structure /app/app/**
Problem: 
1. Create a normal NextJS app
2. under app folder create another folder "app" with an Example Page
3. create an Production Build and deploy it somewhere
4. Try to access your Example

As you will see you get an error trinig (in Browser console too) to access the Example.

Expected: Example will display or a hint that "App/app" is not allowed.

### Is there any context that might help us understand?

None

**Comment by samcx** [comment]
@Devian1988 Please re-submit your issue using this [issue template](https://github.com/vercel/next.js/issues/new?assignees=&labels=template:+bug&projects=&template=1.bug_report.yml), that way we have all the relevant info to triage your issue!

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
