### ISSUE TITLE
DynamicIO errors and hard reloads in dev mode

### ISSUE THREAD

**Issue by khuezy** [vercel/next.js#72150]
### Link to the code that reproduces this issue

https://github.com/khuezy/dynamiio_bug

### To Reproduce

Instructions in the repo:

1. npm i && npm run dev
2. go to http://localhost:3000
3. Open up developer console to see error logs
4. Click alternating on the A and B link fast until you see error. You have to click under 1s for each link.

### Current vs. Expected behavior

Navigating via `next/link` shouldn't cause app to reload. In non-trivial apps that are large, each page may take longer to load on initial render which triggers this error more frequently.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: N/A
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.3-canary.2 // Latest available version is detected (15.0.3-canary.2).
  eslint-config-next: N/A
  react: 19.0.0-rc-603e6108-20241029
  react-dom: 19.0.0-rc-603e6108-20241029
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I'm not sure if this is a production issue.

Example:
![dynamicio](https://github.com/user-attachments/assets/0cab653a-7fec-44f1-af23-e0c3b1ce5732)

If you remove the loading.tsx, error seems to goes away (99% sure) 

If you disable experimental.dynamicIO, the error goes away (100% sure)

**Comment by samcx** [comment]
@khuezy Thank you for submitting an issue!

I was able to intermittently replicate the issue. I will be sharing this with the team!
