### ISSUE TITLE
Docs: Use `useActionState` over `useFormState`

### ISSUE THREAD

**Issue by grzegorzpokorski** [vercel/next.js#72158]
### What is the documentation issue?

After promoting Next.js v15 as a stable version, which requires React v19 RC, I recommend updating the documentation. Specifically, we should replace useFormState with useActionState in sections explaining error handling and similar topics. (https://nextjs.org/docs/app/building-your-application/routing/error-handling).

### Is there any context that might help us understand?

Maybe reverting changes of [this](https://github.com/vercel/next.js/pull/69547) PR will be helpful.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/building-your-application/routing/error-handling

**Comment by samcx** [comment]
@grzegorzpokorski Thanks for sharing—taking a look!

**Comment by grzegorzpokorski** [comment]
I see that docs has been updated so I close that issue.
