### ISSUE TITLE
Type error in Next.js 15 API routes with dynamic params

### ISSUE THREAD

**Issue by Mohamad44p** [vercel/next.js#72185]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32513
  Available CPU cores: 16
Binaries:
  Node: 20.18.0
  pnpm: 9.12.3
Relevant Packages:
  next: 15.0.1
  eslint-config-next: 15.0.1
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

This is not related to a specific example, but rather to the core functionality of Next.js 15 API routes with dynamic parameters.

### What browser are you using? (if relevant)

Not applicable - this is a server-side/build-time issue.

### How are you deploying your application? (if relevant)

The issue occurs during the build process (`next build`), before deployment.

### Describe the Bug

n Next.js 15, there's a persistent type error when building an API route with dynamic parameters. The type checker expects the `params` object to be a Promise, which is inconsistent with the actual runtime behavior and previous versions of Next.js. This occurs in the generated type definitions file `.next/types/app/api/customers/[id]/route.ts`.
![Screenshot 2024-11-01 175245](https://github.com/user-attachments/assets/ceda6d1e-e186-4eea-a7b5-7bf9457a992d)

### Expected Behavior

The `params` object should be correctly typed as a simple object with string properties, not as a Promise. The build process should complete without type errors for valid API route implementations.

### To Reproduce

Create a new Next.js 15 project
Add an API route with dynamic parameters (e.g., `app/api/customers/[id]/route.ts`)
Implement GET, PUT, and DELETE handlers in this route
Run `next build`

You should see an error message similar to:
Type error: Type '{ __tag__: "GET"; __param_position__: "second"; __param_type__: { params: { id: string; }; }; }' does not satisfy the constraint 'ParamCheck<RouteContext>'.
  The types of '__param_type__.params' are incompatible between these types.
    Type '{ id: string; }' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]
    
    
    
    // app/api/customers/[id]/route.ts
import { NextRequest, NextResponse } from "next/server";

export async function GET(
  request: NextRequest,
  context: { params: { id: string } }
) {
  const { id } = context.params;
  return NextResponse.json({ id });
}

This minimal example triggers the type error during build, despite being a valid API route implementation.

This issue appears to be related to the type definitions in `.next/types/app/api/[id]/route.ts`, which are generated during the build process. The generated types seem to incorrectly define the `params` object as a Promise, causing type errors in otherwise correct code.
![Screenshot 2024-11-01 175440](https://github.com/user-attachments/assets/dee591ee-de79-4130-94b9-902f9bb8b865)

**Comment by moonlitgrace** [comment]
https://nextjs.org/docs/app/building-your-application/upgrading/version-15#route-handlers
could you try this?
```tsx
const { id } = await context.params;
```
