### ISSUE TITLE
[v15] intercepting routes not working

### ISSUE THREAD

**Issue by justinradomski** [vercel/next.js#72193]
### Link to the code that reproduces this issue

https://github.com/justinradomski/repro-next-intercept

### To Reproduce

1. Start the application in dev mode (npm run dev)
2. Open http://localhost:3000/, click the 'Interception link' to see the modal
3. Now run the project in production mode (npm run build npm start)
4. Click the 'interception link'. It navigates to the page instead of showing the modal

### Current vs. Expected behavior

Original comment from #67400: I expected the modal to keep working similar to how it does in dev mode, also in production mode.

After RC2: Modals don't work in dev OR production, instead the route just changes completely. 

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 64618
  Available CPU cores: 16
Binaries:
  Node: 20.15.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.0-rc.1
  react: 19.0.0-rc-cd22717c-20241013
  react-dom: 19.0.0-rc-cd22717c-20241013
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Parallel & Intercepting Routes

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed)

**Comment by ElectricCodeGuy** [comment]
I have this exact issue. It works in dev but in Production it just changes to a white screen and nothing happens. If I check the logs in Vercel it gives me status code 200, so no error? In my browser console i can see an error was thrown but it is hidden due to prod. Happen after I upgrade to Next 15. This bug is breaking my website with 2000 active users... I'm not sure how this get past testing...

**Comment by samcx** [comment]
@justinradomski @ElectricCodeGuy I was not able to replicate the issue on the latest canary.

![CleanShot 2024-11-04 at 16 27 09@2x](https://github.com/user-attachments/assets/53ad196c-fb65-42f2-b7f4-42fc09a210ee)
