### ISSUE TITLE
Cannot install dependencies after upgrading to Next 15 and React 19 RC

### ISSUE THREAD

**Issue by ravinggenius** [vercel/next.js#72204]
### Link to the code that reproduces this issue

https://github.com/ravinggenius/minecraft-tools/tree/react-19-blocks-package-install

### To Reproduce

1. clone project (`git clone https://github.com/ravinggenius/minecraft-tools.git minecraft-tools-react-19`)
2. `cd minecraft-tools-react-19`
3. `git checkout react-19-blocks-package-install`
4. install current dependencies (`npm ci`)

### Current vs. Expected behavior

I used the Next upgrade codemod tonight (2024-11-01) to upgrade to Next 15, which installed React 19 as one of the steps. Now I cannot install any new package or upgrade any existing package. Even installing current dependencies in a fresh git checkout gives me an error:

```shell
$ npm ci
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: react-i18next@15.0.2
npm error Found: react@19.0.0-rc-02c0e824-20241028
npm error node_modules/react
npm error   react@"19.0.0-rc-02c0e824-20241028" from the root project
npm error   peer react@"^18.2.0 || 19.0.0-rc-02c0e824-20241028" from next@15.0.2
npm error   node_modules/next
npm error     next@"15.0.2" from the root project
npm error   2 more (react-dom, styled-jsx)
npm error
npm error Could not resolve dependency:
npm error peer react@">= 16.8.0" from react-i18next@15.0.2
npm error node_modules/react-i18next
npm error   react-i18next@"^15.0.2" from the root project
npm error
npm error Conflicting peer dependency: react@18.3.1
npm error node_modules/react
npm error   peer react@">= 16.8.0" from react-i18next@15.0.2
npm error   node_modules/react-i18next
npm error     react-i18next@"^15.0.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/ravinggenius/.npm/_logs/2024-11-02T03_18_49_365Z-eresolve-report.txt
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:26 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8122
  Available memory (MB): 24576
  Available CPU cores: 8
Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by na-zi-ya** [comment]
I believe you need to update the package manager settings. Could you edit the package.json to add packageManager and specify the desired version to override? This should help ensure compatibility with the project.
```
{
  "packageManager": "npm@10.5.2",
  "overrides": {
    "react": "$react",
    "react-dom": "$react-dom"
  },
  "dependencies": {
    "again": "^0.0.1",
    "next": "15.0.1",
    "next-auth": "^5.0.0-beta.25",
    "react": "19.0.0-rc-69d4b800-20241021",
    "react-dom": "19.0.0-rc-69d4b800-20241021"
  }
}

```

**Comment by igordanchenko** [comment]
Duplicate #72026

**Comment by pipsyclone** [comment]
> "packageManager": "npm@10.5.2",

thanks mate

**Comment by ravinggenius** [comment]
Sorry for not responding. I set this aside to work on another feature. I haven't been able to make time to try your suggestion yet.

Can you explain what `"react": "$react"` is doing? I haven't come across that before.

**Comment by ravinggenius** [comment]
@na-zi-ya I finally was able to try your suggestion. It seems to have worked, so I'll close this issue. Thank you for your help.
