### ISSUE TITLE
Docs: It's confusing fetch 'no-store' cache option doesn't applied as a default on pre-renders

### ISSUE THREAD

**Issue by dante01yoon** [vercel/next.js#72213]
### What is the documentation issue?

https://nextjs.org/docs/app/api-reference/functions/fetch#optionscache

According to document itself, fetch itself  has `no-store` option as a default, but when I run build command, each page.tsx calling fetch with no option built as a prerendered as static content.

```
fetch(`https://...`, { cache: 'force-cache' | 'no-store' })
```

to let it be dynamic rendered page, I should use `no-store` explicitly as a cache option.

I can see https://nextjs.org/docs/app/building-your-application/data-fetching/fetching#fetching-data-on-the-server-with-the-fetch-api

```md
If you are not using any [Dynamic APIs](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering) anywhere else in this route, it will be prerendered during next build to a static page. The data can then be updated using [Incremental Static Regeneration](https://nextjs.org/docs/app/building-your-application/data-fetching/incremental-static-regeneration).

If you do not want to cache the response from fetch, you can do the following:
```

If I follow data fetching document, I think it is more likely to be built as a dynamic renders, but according to `fetching-data-on-the-server-with-the-fetch-api` section, I should explicitly use to avoid it prerendered as static content.  

It seems little confusing 

### Is there any context that might help us understand?

// app/characters/page.tsx
```tsx 
export const metadata: Metadata = {
  title: 'Characters',
}

export default async function CharacterPage() {
  const characterPromise = getCharacters();
  // ... 
}

```

```ts
export async function getCharacters(): Promise<{ results: Character[] }> {
  const res = await fetch(`${endpoint}/character`, {
    cache: 'no-store' // <- I should turn this option to avoid static render. 
  })
  if (!res.ok) throw new Error('Failed to fetch characters')
  const response = res.json();
  return new Promise((resolve) => setTimeout(() => resolve(response), 2500))
}
```

**Comment by samcx** [comment]
@dante01yoon Updating!
