### ISSUE TITLE
Docs: Next.js homepage doesn't reference latest stable version

### ISSUE THREAD

**Issue by rinald-ta** [vercel/next.js#72244]
### What is the documentation issue?

Next.js version 15 has been out for about two weeks now. I noticed that the homepage still references the previous stable release (version 14).

<img width="1670" alt="Screenshot 2024-11-03 at 20 39 28" src="https://github.com/user-attachments/assets/26a93b50-fb2c-4edc-8034-6e387d89d04f">

### Is there any context that might help us understand?

In the "What's in Next.js?" section, the Next.js version card hasn't been updated. It still points to the blog post on Next.js 14, when Next.js 15 is the latest stable release at the moment.

### Does the docs page already exist? Please link to it.

https://nextjs.org/

**Comment by samcx** [comment]
@rinald-ta This has been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture>!
