### ISSUE TITLE
`use cache` directive not work inside `use server` directive

### ISSUE THREAD

**Issue by ellemedit** [vercel/next.js#72252]
### Link to the code that reproduces this issue

https://stackblitz.com/edit/stackblitz-starters-vgtn3d?file=app%2Faction.ts

### To Reproduce

In case `use client` -> `use server` -> `use cache`, it fails to compile.

### Current vs. Expected behavior

I believe `use cache` inside `use server` should work as it's server boundary not client.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.16.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.0-canary.195 // There is a newer canary version (15.0.3-canary.5) available, please upgrade!
  eslint-config-next: 15.0.0-rc.0
  react: 19.0.0-rc-cd22717c-20241013
  react-dom: 19.0.0-rc-cd22717c-20241013
  typescript: 5.6.2
Next.js Config:
  output: standalone
 ⚠ There is a newer canary version (15.0.3-canary.5) available, please upgrade!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

dynamicIO

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by chungweileong94** [comment]
If I'm not wrong, I think you are not supposed to (or you can't) cache server action. It's only meant for all "GET" related requests.

**Comment by ellemedit** [comment]
I got this. This actually work but I overrided `use server` directive.

```ts
"use server"

export async function action() {
  "use cache"
  return getUserById2("test2");
}
```

This not work but

```ts
"use server"
export async function testAction2() {
  return getUserById2("test2");
}

async function getUserById2(id: string) {
  "use cache";

  return { id, point: Math.random() };
}
```

This works. I didn't know I was overriding
