### ISSUE TITLE
Docs: https://nextjs.org/docs next routing error

### ISSUE THREAD

**Issue by RainyNight9** [vercel/next.js#72303]
### What is the documentation issue?

https://nextjs.org/docs The next route error at the bottom of the documentation page

![1730772497799](https://github.com/user-attachments/assets/189e5795-3ae8-4514-9991-6fd0444ff009)

### Is there any context that might help us understand?

https://nextjs.org/docs Next route error at the bottom of the documentation page

Open the link and click on the location marked in the screenshot to see the problem

**Comment by samcx** [comment]
@RainyNight9 This is a duplicate of this → https://github.com/vercel/next.js/issues/71629
