### ISSUE TITLE
Cookies are not immedietly set when setting them in middleware, and reading them in page

### ISSUE THREAD

**Issue by samislam** [vercel/next.js#72317]
### Link to the code that reproduces this issue

https://github.com/shared-on-forums/next-cookie-unexpected

### To Reproduce

In my real application, I am trying to see if the user is logged in or not, if the user is logged in, I will show him a LOGOUT button. If he is not logged in, I want to show him a LOGIN button.

But I am getting a problem, that the cookie first time is being undefined when reading it, although it exists, the second time, it is there.

I made a reproducible example here:

I am trying to set a cookie in `middleware.ts` file, then I am trying to read it (for demo in this simple reproducible code) in one of the pages.

This is a nextjs15 project with app router. 

All with server components.

I am setting a cookie in middleware.ts, and I am making sure the cookie is ALWAYS set and there. Then In a page, In a nested server component, I am trying to read that cookie once again. But, I am getting `undefined`!

I open my browser, open dev tools, navigated to the cookies section, then, request localhost:3000, (my application). a cookie gets in, but in the page, the cookie value isn't printed, I am getting (cookie is UNDEFINED). This only happens the first time, but if you refresh the page, subsequent requests will see the cookie value and it works.

Look at the demo here:

[![enter image description here][1]][1]

Folder:
```
.
├── bun.lockb
├── next.config.ts
├── next-env.d.ts
├── package.json
├── src
│   ├── app
│   │   ├── cookie-block.tsx
│   │   ├── layout.tsx
│   │   └── page.tsx
│   ├── functions
│   │   └── auth-cookie.ts
│   └── middleware.ts
└── tsconfig.json
```

## File: src/middleware.ts
```typescript
import { NextResponse } from 'next/server'
import { getAuthCookie, setAuthCookie } from './functions/auth-cookie'

export default async function middleware() {
  // # ensure cookie exists
  const authToken = await getAuthCookie()
  if (!authToken) await setAuthCookie()
  return NextResponse.next()
}

export const config = {
  matcher: '/((?!_next/static|favicon.ico).*)',
}

```

## File: src/functions/auth-cookie.ts
```typescript
import { cookies } from 'next/headers'

const COOKIE_NAME = 'auth'

export const setAuthCookie = async () => {
  const cookieStore = await cookies()
  const hardcodedValue = 'abcd123'
  cookieStore.set(COOKIE_NAME, hardcodedValue, {})
}
export const getAuthCookie = async () => {
  const cookieStore = await cookies()
  const cookie = cookieStore.get(COOKIE_NAME)
  return cookie?.value
}

```

## File: src/app/page.tsx
```jsx
import { CookieBlock } from './cookie-block'

export default function Home() {
  return (
    <div className="bg-orange-400 flex justify-center h-screen w-screen items-center flex-col gap-y-16">
      <h1 className="font-extrabold text-4xl">This page is just for demo</h1>
      <CookieBlock />
    </div>
  )
}

```

## File: src/app/cookie-block.tsx
```jsx
import { getAuthCookie } from '@/functions/auth-cookie'
export const CookieBlock = async () => {
  const authToken = await getAuthCookie()
  return (
    <div className="bg-orange-700 text-center rounded-xl p-5">
      <h3 className="text-2xl font-bold">Your cookie is:</h3>
      <h4>
        <i>{authToken ?? 'IT IS UNDEFINED'}</i>
      </h4>
    </div>
  )
}

```

  [1]: https://i.sstatic.net/wsR7AnY8.gif

### Current vs. Expected behavior

I expect it to work. But it doesn't.

I found the solution to this by completly not using the
```
import { cookies } from 'next/headers'
```
package, because idk maybe only for this case, it is useless.

I used this directly instead and it worked
```ts
// # middleware.ts
export default async function middleware() {
  // # ensure cookie exists
  const res = NextResponse.next()
  const authToken = await getAuthCookie()
  if (!authToken) setAuthCookie(res) // 👈 pass the res, no need for async/await

  return res // 👈 return the res
}
```
```ts
// # auth-cookie.ts
const COOKIE_NAME = 'auth'

export const setAuthCookie = (res: NextResponse) => {
  const hardcodedValue = 'abcd123'
  return res.cookies.set(COOKIE_NAME, hardcodedValue, {})
}
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024
  Available memory (MB): 15931
  Available CPU cores: 4
Binaries:
  Node: 20.16.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.9.0
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: 15.0.2
  react: 19.0.0-rc-02c0e824-20241028
  react-dom: 19.0.0-rc-02c0e824-20241028
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure, create-next-app, Middleware

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Question is also asked on Stackoverflow here:
https://stackoverflow.com/questions/79157823/cookies-are-not-immedietly-set-when-setting-them-in-middleware-and-reading-them

I added for you two branches in the github repo, one for showing the problem, and one showing the solution of the problem.

**Comment by jonas-is-coding** [comment]
The root cause is that cookies() in Next.js doesn’t immediately make cookies available on the first request when set asynchronously in the middleware. Instead, setting the cookie through the response object itself ensures that it is immediately available.

### Solution

Instead of relying on cookies() for setting cookies asynchronously, the following solution passes the NextResponse object directly to the setAuthCookie function in middleware.ts:

**Updated middleware.ts:**
```javascript
import { NextResponse } from 'next/server'
import { getAuthCookie, setAuthCookie } from './functions/auth-cookie'

export default async function middleware() {
  const res = NextResponse.next()
  const authToken = await getAuthCookie()
  if (!authToken) setAuthCookie(res) // Pass `res` to ensure the cookie is immediately set
  return res // Return `res` to include the cookie in the response
}

export const config = {
  matcher: '/((?!_next/static|favicon.ico).*)',
}
```

**Updated auth-cookie.ts:**
```
const COOKIE_NAME = 'auth'

export const setAuthCookie = (res: NextResponse) => {
  const hardcodedValue = 'abcd123'
  res.cookies.set(COOKIE_NAME, hardcodedValue, {})
}
```

### Explanation
By setting the cookie directly on the NextResponse object, the cookie is available immediately, so it avoids the need for a page refresh. This approach bypasses the delay in accessing cookies when using cookies() in server components.
This approach works because res.cookies.set() ensures that the Set-Cookie header is included in the initial response. When NextResponse.next() alone is used, the cookie is not guaranteed to be part of the response headers on the first request, hence the undefined issue.

### Video
![CleanShot 2024-11-05 at 17 06 15](https://github.com/user-attachments/assets/732e9ccd-2606-4d7a-924f-b968c34b0fb9)

**Comment by ztanner** [comment]
Perfect responses above. Thank you!

**Comment by samislam** [comment]
I suggest making the default behavior of `{ cookies } from 'next/headers'` to give the newest cookie data, because that's what I expected when I first used it.
