### ISSUE TITLE
Error in Next.js with TRPC using Turbopack: Failed to get source map: [Error: Unknown url scheme] { code: 'GenericFailure' }

### ISSUE THREAD

**Issue by KUN1007** [vercel/next.js#72337]
### Link to the code that reproduces this issue

https://github.com/KUN1007/nextjs-trpc-turbopack-sourcemap-error

### To Reproduce

1. Clone the code from [the repository](https://github.com/KUN1007/nextjs-trpc-turbopack-sourcemap-error) and install dependencies.
2. Start the Turbopack-supported development environment using `pnpm dev:turbo`, and visit http://localhost:3000/patch/1. This will trigger the error:
``` shell
Failed to get source map: [Error: Unknown url scheme] { code: 'GenericFailure' }
```
<img width="580" alt="KUN_2024-11-05_16-01-00" src="https://github.com/user-attachments/assets/6e292d19-befd-4df6-a2e6-68d6fc9a87c1">

### Current vs. Expected behavior

Start the development environment using `pnpm dev` and visit http://localhost:3000/patch/1. Everything works correctly.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 16291
  Available CPU cores: 16
Binaries:
  Node: 22.11.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I've already reviewed these issues, but the solutions mentioned there don't apply to my situation.
https://github.com/vercel/next.js/discussions/71957
https://github.com/vercel/next.js/issues/71854

**Comment by unstubbable** [comment]
This issue is fixed in [15.0.3](https://github.com/vercel/next.js/releases/tag/v15.0.3) (via #72139).
