### ISSUE TITLE
"use cache" cannot call function from inside closure

### ISSUE THREAD

**Issue by romeovs** [vercel/next.js#72403]
### Link to the code that reproduces this issue

https://github.com/romeovs/use-cached-closures-repro

### To Reproduce

1. `next dev`
2. open <http://localhost:3000>

There will be the error:
```
[ Server ] Error: generate is not defined
```
3. edit `app/page.tsx` to use `../api/direct` instead of `../api/closure`
4. open <http://localhost:3000>, there will be no errors

### Current vs. Expected behavior

`"use cache"` should work inside functions closures, and should be able to use closed over values. This will help with wrapping third-party clients with a Next.js cache.

```
function defineClient() {
  function handler() {
    // from a library
    return client.fetch()
  }

  async function get() {
    "use cache"
     // this should be able to call handler but it fails
     return await handler()
  }

  return { get }
}
```

If that's not possible for some reason, I would like the Next.js compiler to make it clear in the error message and this should be documented somewhere. It would also seriously reduce the usefulness of the `"use cache"` pattern.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6031
  Available memory (MB): 36864
  Available CPU cores: 14
Binaries:
  Node: 20.18.0
  npm: 10.8.2
  Yarn: 1.22.21
  pnpm: 9.12.3
Relevant Packages:
  next: 15.0.3-canary.7 // Latest available version is detected (15.0.3-canary.7).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

dynamicIO

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed), Other (Deployed)

**Comment by TheCodby** [comment]
in this case, 'use cache' isn't working in development mode, but it works well when you run 'next build' and 'next start.' It might be helpful if this were mentioned in the documentation as well.

**Comment by unstubbable** [comment]
Closing over functions is not supported with `"use cache"`. Every closed-over variable that's used inside a `"use cache"` function needs to be serializable so that we can compute a stable cache key. See also https://nextjs.org/docs/canary/app/api-reference/directives/use-cache#good-to-know.

The error handling for this specific case will be improved with #73471. Thanks for reporting this deficiency!
