### ISSUE TITLE
Backward and forward caching issues

### ISSUE THREAD

**Issue by fliixy-bdh** [vercel/next.js#72408]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.16.0
  npm: 10.8.1
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  next: 15.0.3-canary.7 // Latest available version is detected (15.0.3-canary.7).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.5
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

app-directory

### What browser are you using? (if relevant)

Chrome 130.0.6723.116

### Describe the Bug

In nextjs 15 version, when you press the back and forward buttons, it keeps caching, is this the action you want??

### Expected Behavior

As far as I'm concerned, the data needs to be retrieved even when the back and forward buttons are pressed

### To Reproduce

```
import` Member from "@/components/member1";
import PostStoreProvider from "@/lib/PostStoreProvider";
import Link from "next/link";

export const dynamic = "force-dynamic";

function Page() {
  return (
    <>
      <Link href={"/"}>Back</Link>
      <Member />
    </>
  );
}

export default async function Layout() {
  // 1,2,3 random
  const random = Math.floor(Math.random() * 3) + 1;
  console.log("new Call!!");
  let data = await fetch(
    `https://jsonplaceholder.typicode.com/todos/${random}`,
    {
      cache: "no-store",
    }
  );
  let post = await data.json();
  console.log(post);

  return (
    <PostStoreProvider post={post}>
      <Page />
    </PostStoreProvider>
  );
}
```

**Comment by lfades** [comment]
The layout doesn't re-render when a navigation happens so your `fetch` doesn't get called again and that's intended behavior.

**Comment by fliixy-bdh** [comment]
When you use the Link tag, you can see that the layout is re-called

But I can't call back during the events going back and forward

![스크린샷 2024-11-07 오전 12 34 34](https://github.com/user-attachments/assets/4c2e0c8d-3fa3-4c0b-b63a-920b808cf514)

**Comment by ztanner** [comment]
This is documented [here](https://nextjs.org/docs/app/building-your-application/caching#client-side-router-cache):

> Pages are not cached by default, but are reused during browser backward and forward navigation.

You could purge the router cache via `router.refresh()` or calling `revalidatePath(...)` in a server action ([docs](https://nextjs.org/docs/app/building-your-application/caching#invalidation-1)). That way when you navigate back to the previous page, the router doesn't have a cache entry anymore and will require a server roundtrip.
