### ISSUE TITLE
next/font Roboto_Flex cannot have axis set

### ISSUE THREAD

**Issue by mclement18** [vercel/next.js#72413]
### Link to the code that reproduces this issue

https://github.com/mclement18/nextjs-font-bug-example

### To Reproduce

1. run the dev server using `npm run dev`

### Current vs. Expected behavior

I expect to be able to use the axes of the `Roboto_Flex` font since the type signature tells me that I can do it but I get the following error :
```
`next/font` error:
Axes can only be defined for variable fonts
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: arm64
  Version: #44-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 19:27:11 UTC 2024
  Available memory (MB): 17949
  Available CPU cores: 12
Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: 9.12.1
Relevant Packages:
  next: 15.0.3-canary.7 // Latest available version is detected (15.0.3-canary.7).
  eslint-config-next: N/A
  react: 19.0.0-rc-7c8e5e7a-20241101
  react-dom: 19.0.0-rc-7c8e5e7a-20241101
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Font (next/font)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

It does not work on the 14.2.17 release that we are using on our project.

**Comment by samcx** [comment]
@mclement18 Thank you for submitting an issue!

It looks like an update is needed. When I run the script `pnpm update-google-fonts` in our repo, I see some changes to the types.
