### ISSUE TITLE
Docs: 404 Not Found 

### ISSUE THREAD

**Issue by Gitstar-OC** [vercel/next.js#72499]
### What is the documentation issue?

There should be a page about configuring typescript at https://nextjs.org/docs/pages/building-your-application/configuring/typescript. As it appears at the top in google search as shown in the below screenshot. 

![image](https://github.com/user-attachments/assets/f128536a-6a0a-43ab-ae1d-ba40a0bcf788)

But it is showing a 404 not found error, which means there is nothing at the url. 

### Is there any context that might help us understand?

Yes, you can go to https://nextjs.org/docs/pages/building-your-application/configuring/typescript to see the error. I needed to configure my typescript config file. Is the markdown file deleted ?

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/configuring/typescrip

**Comment by samcx** [comment]
@Gitstar-OC I am not receiving this issue—it seems the issue has been <picture data-single-emoji=":fixed:" title=":fixed:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/fixed/66bb8455f24bd50e.png" alt=":fixed:" align="absmiddle"></picture> ?

Let me know if you are still experiencing the issue!

**Comment by Gitstar-OC** [comment]
Yes, It is fixed now. A redirect has been setup to a different url I guess. Thanks
