### ISSUE TITLE
Docs: 404 occur in chapter TypeScript that about  link "TypeScript plugin" from /learn/dashboard-app/getting-started

### ISSUE THREAD

**Issue by james-han** [vercel/next.js#72507]
### What is the documentation issue?

404 occur in chapter TypeScript that about link "TypeScript plugin"

### Is there any context that might help us understand?

you can find https://nextjs.org/learn/dashboard-app/getting-started#typescript , then click it  link “TypeScript plugin” ,404 occur in https://nextjs.org/docs/app/building-your-application/configuring/typescript#typescript-plugin

**Comment by OlegDev1** [comment]
Could you please upload a screenshot or give additional information? When i go to https://nextjs.org/docs/app/building-your-application/configuring/typescript#typescript-plugin or click on the link "TypeScript plugin" I am redirected to this page. Everything works as expected for me
![Screenshot 2024-11-08 at 17 02 33](https://github.com/user-attachments/assets/dd67824c-bdc6-4614-8908-2b41a907964e)

**Comment by ztanner** [comment]
It's loading for me too! Going to close this but let us know if you are still experiencing problems.
