### ISSUE TITLE
Intercepting Routes with Dynamic catch all segments

### ISSUE THREAD

**Issue by programming-with-ia** [vercel/next.js#72523]
### Link to the code that reproduces this issue

https://github.com/programming-with-ia/intercepting-test

### To Reproduce

1. start using `pnpm dev`

### Working
http://localhost:3001/templates/single -> http://localhost:3001/showcase/single is work
http://localhost:3001/templates/multi/slug -> http://localhost:3001/showcase/single is work

### Not Working
http://localhost:3001/templates/multi/slug -> http://localhost:3001/showcase/multi/slug doesn't work (this will show normal page not Intercepting page

### Current vs. Expected behavior

when
http://localhost:3001/templates/multi/slug -> http://localhost:3001/showcase/multi/slug show Intercepting page

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 16231
  Available CPU cores: 4
Binaries:
  Node: 20.17.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.8.0
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: 15.0.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, dynamicIO, Navigation, Parallel & Intercepting Routes, Performance

### Which stage(s) are affected? (Select all that apply)

next build (local), next start (local), Vercel (Deployed), Other (Deployed)

**Comment by Reflex2468** [comment]
From testing locally, I see this was fixed by: #51787 

But broken again after b914ad81927f592fa60ab7de8838652b542e8829

I'm not sure what the issue was from b914ad8, but locally, after changing the code in [`toPathToRegexp`]( https://github.com/vercel/next.js/blob/ef9d0969a050263403dd59573a09b345e75583a8/packages/next/src/lib/generate-interception-routes-rewrites.ts#L10) I was able to solve the issue.

```diff
function toPathToRegexpPath(path: string): string {
  return path.replace(/\[\[?([^\]]+)\]\]?/g, (_, capture) => {
    // path-to-regexp only supports word characters, so we replace any non-word characters with underscores
    const paramName = capture.replace(/\W+/g, '_')

    // handle catch-all segments (e.g. /foo/bar/[...baz] or /foo/bar/[[...baz]])
-     if (paramName.startsWith('...')) {
-       return `:${paramName.slice(3)}*`
+    if (capture.startsWith('...')) {
+       return `:${capture.slice(3)}*`
    }
    return ':' + paramName
  })
}
```

**Comment by programming-with-ia** [comment]
> Basically the replace of `/\W+/` also replaces the `...` with `_` so the the if statement two lines below always returns false

Nice

**Comment by programming-with-ia** [comment]
@Reflex2468 
Thanks

**Comment by programming-with-ia** [comment]
Does not work as expected with parallel routes.
