### ISSUE TITLE
Docs: "React Essentials" does not exist

### ISSUE THREAD

**Issue by makors** [vercel/next.js#72566]
### What is the documentation issue?

https://nextjs.org/docs/getting-started/react-essentials does not exist, and previously did.

### Is there any context that might help us understand?

This is referenced a decent bit throughout NextJS errors, and is a vital resource in helping people fix their code.

**Comment by samcx** [comment]
@makors Thank you for reporting! Fixing <picture data-single-emoji=":loading:" title=":loading:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/loading/fa531af0d6940856.gif" alt=":loading:" align="absmiddle"></picture>
