### ISSUE TITLE
declare const handled like const during analysis in Turbopack

### ISSUE THREAD

**Issue by timneutkens** [vercel/next.js#72576]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/eager-stonebraker-x42f67

### To Reproduce

Reproduction requires #71802 to have landed first.

- Install next@canary
- Run `next dev --turbo`
- Open homepage `/`
- It should show `my value` instead of `not set`

### Current vs. Expected behavior

Currently it shows `not set` when `declare const MY_MAGIC_VARIABLE: string` is in the file. Removing it shows the correct `my value`.

This code does not work with our `define` handling but works with webpack. When I remove the `declare const` it works. Looking at the AST output of SWC it seems declare const is a `VariableDeclaration` but has a property `declare: true` which it doesn't have for normal `const` assignment. Looking at the analyzer code we don't take `declare: true` into account so it's likely skipping replacement for `define` because we detect a `VariableDeclaration`  already in scope so it doesn't replace.

AST snippet:

```
    {
      "type": "VariableDeclaration",
      "span": {
        "start": 0,
        "end": 25
      },
      "ctxt": 0,
      "kind": "const",
      "declare": true,
      "declarations": [
```

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.0.4-canary.5 // Latest available version is detected (15.0.4-canary.5).
  eslint-config-next: N/A
  react: 19.0.0-rc-5c56b873-20241107
  react-dom: 19.0.0-rc-5c56b873-20241107
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local)

**Comment by kdy1** [comment]
Note: The fix in https://github.com/vercel/next.js/pull/72604 is going to be reverted with https://github.com/swc-project/swc/pull/10102 because it should be fixed from turbopack side.
