### ISSUE TITLE
app-dir-i18n-routing example does not currently pass type checking

### ISSUE THREAD

**Issue by dagoss** [vercel/next.js#72630]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Mon Jun 24 00:56:10 PDT 2024; root:xnu-8020.240.18.709.2~1/RELEASE_X86_64
  Available memory (MB): 8192
  Available CPU cores: 4
Binaries:
  Node: 22.11.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.4-canary.6 // Latest available version is detected (15.0.4-canary.6).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 4.9.5
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

app-dir-i18n-routing

### How are you deploying your application? (if relevant)

next build

### Describe the Bug

After cloning the example, without changing anything, run `npm run build`. The build fails with the following type error:

```
   Linting and checking validity of types  ..Failed to compile.

app/[lang]/layout.tsx
Type error: Type '{ children: ReactNode; params: { lang: "en" | "de" | "cs"; }; }' does not satisfy the constraint 'LayoutProps'.
  Types of property 'params' are incompatible.
    Type '{ lang: "en" | "de" | "cs"; }' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]
```
Setting `nextConfig.typescript.ignoreBuildErrors: true` allows the build to succeed.

### Expected Behavior

Build should not fail.

### To Reproduce

1. Clone example per instructions in README.md
2. Run `npm run build`

**Comment by samcx** [comment]
@dagoss It looks like we need to update this example to v15!
