### ISSUE TITLE
Failed to find server action/Cannot read properties of undefined (reading 'workers')

### ISSUE THREAD

**Issue by kevva** [vercel/next.js#72638]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/sweet-dan-qdctsl

### To Reproduce

1. Run `yarn && yarn build`
2. Run `cd apps/foo && yarn start`
3. Submit the form

### Current vs. Expected behavior

Current behaviour:

Sometimes when server actions are called they throw a `Failed to find server action/Cannot read properties of undefined (reading 'workers')` error. This is most likely due to Next.js not recognizing which server actions should be included on a page.

<img width="300" alt="image" src="https://github.com/user-attachments/assets/52a6509a-d509-496c-9d06-56115423b412">

Expected behaviour:

Server actions run without errors. Not sure how to better define it.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 23.2.0
  npm: 10.2.4
  Yarn: 4.5.1
  pnpm: N/A
Relevant Packages:
  next: 15.0.4-canary.5
  eslint-config-next: N/A
  react: 19.0.0-rc-5c56b873-20241107
  react-dom: 19.0.0-rc-5c56b873-20241107
  typescript: 5.6.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Output (export/standalone), Partial Prerendering (PPR), Runtime

### Which stage(s) are affected? (Select all that apply)

next start (local), Other (Deployed)

### Additional context

The reproduction example will work correctly, and it (always) works locally when running our application as well. On our deployment it's another thing though and I've been trying to figure out what's causing it for a few weeks now without any luck. I'm not sure how often it happens, because the app mostly works when I use it, but the logs and Sentry is telling me another story.

The code in the reproduction example works and looks mostly the same as in our application though so it should be a good representation of it. We have a internal package in our monorepo which exports server components and actions. We initiate the actions with some other server actions coming from the app that holds logic not suitable for the internal package. Then we wrap them in additional actions from the app that might do redirection or whatever when everything is done. Finally we pass them down to the server components from the internal package where they're sometimes called from a client component and sometimes directly from a server component.

We deploy this to Kubernetes running multiple containers and we set `generateBuildId` to the SHA for the current commit and `deploymentId` to the deployment ID in our pipeline so it should be consistent between builds and deploys. We're also setting the `NEXT_SERVER_ACTIONS_ENCRYPTION_KEY` to avoid any inconsistencies between containers. I've also included a minimal example of our `Dockerfile` (we're using a custom `node` image though so not sure it runs).

Is there some way to debug this? Would it be possible to add a flag to turn off [optimization](https://github.com/vercel/next.js/pull/69178) for unused server actions?

**Comment by kevva** [comment]
Downgrading to `15.0.0-canary.125` (the version just before the optimization of server actions was introduced) does completely fix the issue so I don't think there's anything wrong with how our environment is setup unless I'm missing something that was introduced after that.

**Comment by lemurki** [comment]
We have a similar problem with server action. We have a function to connect to the database through mysql2 library, which is called in server action.

Locally everything works fine, but in the production build when using server action the page crashes.

The problem is observed in version ‘15.0.3’ and higher.  And it is reproduced only when using server action. 

At the moment we have solved it by rolling back to ‘15.0.2’.

A similar problem was described here - https://github.com/sidorares/node-mysql2/issues/3213

The error message is identical to ours.

**Comment by kevva** [comment]
@lemurki, I feel like that is something different. The error `Cannot read properties of undefined (reading 'workers')` comes directly [from Next.js](https://github.com/vercel/next.js/blob/fe5ef9bb48a240238b7e6f139b993ae958ed4a3c/packages/next/src/server/app-render/action-utils.ts#L19-L23) itself when it tries to get and run a non-existing from the actions manifest. Yours does sound like it's coming from the module you're trying to use but I can't comment on why.

**Comment by lemurki** [comment]
@kevva I think the root of the problem in our project and yours is in optimising server action. 

That's why I wrote that the problem is similar :)

For curiosity sake, try to upgrade to version 15.0.2 and see if the server action problem remains in your project.

**Comment by kevva** [comment]
> I think the root of the problem in our project and yours is in optimising server action.

By optimizing I mean that Next.js is running an optimization that removes any server actions it thinks isn't in use from the actions manifest. This is so that they aren't exposed unnecessarily on pages that doesn't need them.

> For curiosity sake, try to upgrade to version 15.0.2 and see if the server action problem remains in your project.

It does remain.

**Comment by kevva** [comment]
I figured out our issue. It was indeed a misconfiguration in our environment since we have two different type of images being built (`x86` and `arm64`) and the encryption key for server actions is generated inside the `Dockerfile` so we ended up with different ones for the two images.
