### ISSUE TITLE
CSP with nonce does not work

### ISSUE THREAD

**Issue by deepankarit** [vercel/next.js#72749]
### Link to the code that reproduces this issue

https://github.com/deepankarit/nextjs

### To Reproduce

start the app (yarn dev)
Observe console logs in the browser

### Current vs. Expected behavior

**My Script as follows**
```
module.exports = {
  reactStrictMode: false,
  async headers() {
    return [
      {
        source: '/(.*)', // Apply these headers to all routes in your application.
        headers: [
          {
            key: 'Cache-Control',
            value:
              'max-age=900, no-cache, no-store, must-revalidate, pre-check=0, post-check=0, s-maxage=0',
          },
          {
            key: 'Content-Security-Policy',
            value: `default-src 'self'; object-src 'none'; form-action 'none'; script-src 'self'; report-to csp-endpoint;`,
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=86400; includeSubdomains; preload',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'Access-Control-Allow-Origin',
            value: 'https://*.goindigo.in',
          },
          {
            key: 'Access-Control-Allow-Methods',
            value: 'GET, POST, PUT, DELETE, OPTIONS',
          },
        ],
      },
    ];
  },
}
```

**Error look like this** 

Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-4/2nIlfwIVTJ1+JcNQ6LkeVWzNS148LKAJeL5yofdN4='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
Understand this errorAI
localhost/:1 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-gTyOjA8aRsBIkjMhpPUWfT1pjh0iUZZwPPM3SmWD1eE='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
Understand this errorAI
react-refresh.js:30 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
 
    at ./node_modules/next/dist/compiled/@next/react-refresh-utils/dist/runtime.js (react-refresh.js:30:26)
    at options.factory (webpack.js:654:31)
    at __webpack_require__ (webpack.js:37:33)
    at __webpack_exec__ (react-refresh.js:58:61)
    at react-refresh.js:59:37
    at webpackJsonpCallback (webpack.js:1202:39)
    at Array.forEach (<anonymous>)
    at webpack.js:1216:31
    at webpack.js:1218:12
    at webpack.js:1229:12
./node_modules/next/dist/compiled/@next/react-refresh-utils/dist/runtime.js @ react-refresh.js:30
options.factory @ webpack.js:654
__webpack_require__ @ webpack.js:37
__webpack_exec__ @ react-refresh.js:58
(anonymous) @ react-refresh.js:59
webpackJsonpCallback @ webpack.js:1202
(anonymous) @ webpack.js:1216
(anonymous) @ webpack.js:1218
(anonymous) @ webpack.js:1229Understand this errorAI

### Provide environment information

```bash
Operating System:
  Platform: Mac - Ventura
  Version: 13.4
  Available memory (MB): 4096
  Available CPU cores: 8
Binaries:
  Node: 22.1.0
  npm: 10.7.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 14.2.13
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Image (next/image), Navigation, Script (next/script)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local), Vercel (Deployed), Other (Deployed)

**Comment by sanderwapstra** [comment]
The nonce in https://www.npmjs.com/package/@next/third-parties isn't working either. It isn't added to the scripts. Should I create a separate ticket?
