### ISSUE TITLE
Docs: nextjs 15 fetch with default no-store is static

### ISSUE THREAD

**Issue by nazaninroozbahani** [vercel/next.js#73109]
### What is the documentation issue?

In this section:
https://nextjs.org/docs/app/building-your-application/data-fetching/fetching#fetching-data-on-the-server-with-the-fetch-api

in nextjs 15 the default of fetch cache is no-store and the link above says:
"If you are not using any [Dynamic APIs](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering) anywhere else in this route, it will be prerendered during next build to a static page."

but in this link:
https://nextjs.org/docs/app/building-your-application/rendering/server-components#switching-to-dynamic-rendering

"During rendering, if a [Dynamic API](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-apis) or uncached data request is discovered, Next.js will switch to dynamically rendering the whole route"

### Is there any context that might help us understand?

I think they are in coflict. Uncached data request is a case of dynamic rendering.

**Comment by samcx** [comment]
@nazaninroozbahani Thank you for sharing!

I think both ends needs to be clarified. My linked PR will clarify!

**Comment by samcx** [comment]
@nazaninroozbahani Pushed up a PR. I think some of the issues right are that these Documentation updates we are showing up in our Canary docs first, not our Stable docs (we're working on fixing that!).

I hope this clarifies.
