### ISSUE TITLE
Docs: Cookies function incorrectly documented as returning a Promise

### ISSUE THREAD

**Issue by Keith-Web3** [vercel/next.js#73175]
### What is the documentation issue?

There is incorrect information about the cookies function imported from `next/headers` returning a promise. From using it, I found that it actually returned a `ReadonlyRequestCookies` type and doesn't need to be awaited as most part of the cookies docs suggest.

### Is there any context that might help us understand?

The cookies function returns a `ReadOnlyRequestCookies` type and not a promise hence it doesn't need to be awaited as suggested by the docs.

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/app/api-reference/functions/cookies

**Comment by DevFromSiberia** [comment]
In the section below - ‘good to know’ - it says the following:

- Сookies is an asynchronous function that returns a promise. You must use async/await or React's [use](https://react.dev/reference/react/use) function to access cookies.
- In version 14 and earlier, cookies was a synchronous function. To help with backwards compatability, you can still access it synchronously in Next.js 15, but this behavior will be deprecated in the future.

What version do you have?

**Comment by Keith-Web3** [comment]
Oh! I see. Was on version 14, thanks for the clarification.
