### ISSUE TITLE
Error in newly initialized Next project [Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used]

### ISSUE THREAD

**Issue by prakhardubey2002** [vercel/next.js#73209]
### Link to the code that reproduces this issue

https://github.com/prakhardubey2002/Next-Ecommerce

### To Reproduce

npx create-next-app@latest
√ Would you like to use TypeScript? ...  Yes
√ Would you like to use ESLint? ... Yes
√ Would you like to use Tailwind CSS? ... Yes
√ Would you like your code inside a `src/` directory? ... No 
√ Would you like to use App Router? (recommended) ...Yes
√ Would you like to use Turbopack for next dev? ... No 
√ Would you like to customize the import alias (@/* by default)? ... No 

### Current vs. Expected behavior

No error should come as the project is just intialised but still "Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used" pops up

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 7927
  Available CPU cores: 8
Binaries:
  Node: 20.10.0
  npm: 10.8.3
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 15.0.3 // Latest available version is detected (15.0.3).
  eslint-config-next: 15.0.3
  react: 19.0.0-rc-66855b96-20241106
  react-dom: 19.0.0-rc-66855b96-20241106
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

![image](https://github.com/user-attachments/assets/a0e77128-df4a-422b-a431-0af2ce8114ad)

**Comment by icyJoseph** [comment]
Hi,

Unfortunately, at this time, there is some compatiblity issues with certain Browser extensions. This is a React issue that React 19 promises to solve.

Verify that this doesn't happen if you use an incognito browser window.

**Comment by nishant-10** [comment]
Facing similar issue, confirmed that the issue doesn't occur on incognito window.
But how do we patch the already made and running projects? I guess just re-install react and react-dom?

**Comment by icyJoseph** [comment]
- No, it's a problem with browser extensions. If users don't have those particular extensions, it'll be fine. 

- If the DOM node that's affected is the body tag you could add the supressHydrationWarning prop to it.

**Comment by prakhardubey2002** [comment]
@icyJoseph Yes the issue vanishes when incognito window is used

**Comment by icyJoseph** [comment]
Yeah, so you have a browser extension installed that edits the HTML before scripts are run on the page.

**Comment by icyJoseph** [comment]
Just guessing here, but is it perhaps Grammarly?

**Comment by prakhardubey2002** [comment]
@icyJoseph  yes i just uninstalled Grammarly extension and issue is gone now !
Thanks for the help!
