### ISSUE TITLE
Docs: NextJS compiler docs still list `swcMinify` config option

### ISSUE THREAD

**Issue by ryami333** [vercel/next.js#73267]
### What is the documentation issue?

On [this page](https://nextjs.org/docs/architecture/nextjs-compiler#minification) it states that you can disable the SWC minifier with the config option `swcMinify`, but as far as I'm aware it was removed in v15. If you use this option and do `yarn start` or `yarn dev` you get the following error message:

```
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'swcMinify'
```

### Is there any context that might help us understand?

No

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/architecture/nextjs-compiler#minification

**Comment by icyJoseph** [comment]
I think, you could make a PR. Probably just needs, https://github.com/vercel/next.js/blob/3d5aa278e6e0f8a5330f21a8d2f9fe305c1e36a1/docs/03-architecture/nextjs-compiler.mdx?plain=1#L243-L254 these bits to be deleted?

**Comment by ryami333** [comment]
No thank you
