### ISSUE TITLE
Server fetch is cached even when use "no-store" fetch cache value

### ISSUE THREAD

**Issue by zecka** [vercel/next.js#73589]
### Link to the code that reproduces this issue

https://github.com/zeckaissue/next-understand-cache-behaviours/tree/issue/no-store-fetch

### To Reproduce

1. yarn install
2. yarn build
3. yarn start
4. go to http://localhost:3000

### Current vs. Expected behavior

_**Why I create this issue ?** 
I have multiple caching issue in a hudge nextjs application. I saw multiple unexpected behaviours.
So I'm trying to deeply understand how nextjs cache work_

**What we have on this reproductible example**
There is an api route that return a timestamp without any cache-control header, in a page I call this api with 'no-store' option twice with a waiting time between two api call. I add log in cache-handler and in api route.

My expectation is to have different timestamp value and receive two time the log inside the api call.
But instead the timestamp value still the same and there is only one log from the api route.

Note that cache handler doesn't log anything, so no-store option disable cache handler but the value seems to be cached. 

So why nextjs cache value from this api call ? Is there another built in memory cache in nextjs ?

## api/no-max-age/route.ts
```ts
export async function GET() {
    console.log('FETCH demo no cache-control');
    return NextResponse.json({ time: Date.now() }, {
        status: 200,
    });
}
```
## page.tsx
```tsx
export default async function Home() {
    const result = await fetch('http://127.0.0.1:3000/api/no-max-age', { cache: 'no-store' })
    const json = await result.json()
    await wait(2000);
    const result2 = await fetch('http://127.0.0.1:3000/api/no-max-age', { cache: 'no-store' })
    const json2 = await result2.json()
    return <>time1: {{json.time}} time2: {{json2.time}}</>;
}
```

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.5.0
Relevant Packages:
  next: 14.2.20 // An outdated version detected (latest is 15.0.4), upgrade is highly recommended!
  eslint-config-next: 15.0.2
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local), Other (Deployed)

### Additional context

**Only on build not on dev**
If you try to reproduce with next dev (npm run dev), the behaviour is different

**Comment by hosino-t** [comment]
It's probably due to Request Memoization.
https://nextjs.org/docs/app/building-your-application/caching#request-memoization

**Comment by zecka** [comment]
Okay, so it's not a bug but rather a good feature.

I don't understand why I didn't come across this page in the documentation earlier. It answers many questions I had about how the Next.js cache works. Thank you for pointing me to this page.
