### ISSUE TITLE
Sass is not working

### ISSUE THREAD

**Issue by muhammadalizkhan** [vercel/next.js#73639]
### Link to the code that reproduces this issue

https://github.com/muhammadalizkhan/asyncdev

### To Reproduce

npm install
npm run dev

### Current vs. Expected behavior

The Below error im getting after npm run dev

![image](https://github.com/user-attachments/assets/94c3c363-6731-4df4-bd44-cbce7570a069)

this is **NavBar.module.scss** file

`.navbar {
  position: fixed;
  top: 10px;
  left: 50%;
  transform: translateX(-50%);
  background-color: white;
  width: 95%;
  max-width: 1280px;
  border-radius: 10px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
  z-index: 10;
  transition: all 0.3s ease;
}

.navbarContainer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0;
  height: 80px;
}

.navbarHeader {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-left: 20px;
  height: 100%;
  flex-shrink: 0;
}

.logoGroup {
  display: flex;
  align-items: center;
  gap: 12px;
}

.navbarLogo {
  display: flex;
  align-items: center;
}

.title {
  font-size: 30px;
  font-weight: bold;
  font-family: system-ui;
  color: black;
  line-height: 1;
}

.mobileToggle {
  display: none;
  background: none;
  border: none;
  padding: 8px;
  cursor: pointer;
  color: #4b5563;
  transition: color 0.3s ease;

  &:hover {
    color: #000;
  }
}

.navbarContent {
  display: flex;
  align-items: center;
  gap: 40px;
  padding-right: 0;
  height: 100%;
  transition: all 0.3s ease;
}

.navbarLinks {
  display: flex;
  align-items: center;
  gap: 32px;
  margin: 0 20px;
}

.navLink {
  color: #4b5563;
  font-size: 15px;
  font-weight: 500;
  text-decoration: none;
  transition: color 0.3s ease;
  white-space: nowrap;

  &:hover {
    color: #000;
  }
}

.scheduleButton {
  display: flex;
  align-items: center;
  background-color: black;
  color: white;
  font-weight: 500;
  font-size: 15px;
  text-decoration: none;
  padding: 0 24px;
  height: 100%;
  border-top-right-radius: 10px;
  border-bottom-right-radius: 10px;
  transition: background-color 0.3s ease;
  white-space: nowrap;
  
  &:hover {
    background-color: #333;
  }
}

.arrowIcon {
  width: 16px;
  height: 16px;
  margin-left: 8px;
}

@media (max-width: 768px) {
  .navbar {
    position: static;
    transform: none;
    margin: 10px auto;
    height: auto;
  }

  .navbarContainer {
    flex-direction: column;
    height: auto;
  }

  .navbarHeader {
    width: 100%;
    padding: 15px 20px;
    height: 80px;
  }

  .mobileToggle {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .navbarContent {
    height: 0;
    opacity: 0;
    overflow: hidden;
    flex-direction: column;
    align-items: flex-start;
    width: 100%;
    padding: 0 20px;

    &.isOpen {
      height: auto;
      opacity: 1;
      padding: 20px;
    }
  }

  .navbarLinks {
    flex-direction: column;
    align-items: flex-start;
    width: 100%;
    gap: 16px;
    margin: 0 0 20px 0;
  }

  .scheduleButton {
    width: 100%;
    justify-content: center;
    height: 50px;
    border-radius: 5px;
  }
}

`

### Provide environment information

```bash
{,
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "lucide-react": "^0.460.0",
    "next": "^15.0.4-canary.45",
    "particles.js": "^2.0.0",
    "react": "19.0.0-rc-66855b96-20241106",
    "react-dom": "19.0.0-rc-66855b96-20241106",
    "react-icons": "^5.3.0"
  },
  "devDependencies": {
    "@types/node": "^22.9.3",
    "@types/react": "^18.3.12",
    "sass": "^1.82.0",
    "tailwindcss": "^3.4.16",
    "typescript": "^5.7.2"
  }
}
```

### Which area(s) are affected? (Select all that apply)

Documentation, TypeScript, Webpack

### Which stage(s) are affected? (Select all that apply)

next dev (local), Other (Deployed)

### Additional context

Im facing this issue.

` ⨯ ./src/app/components/NavBar/NavBar.module.scss
To use Next.js' built-in Sass support, you first need to install `sass`.
Run `npm i sass` or `yarn add sass` inside your workspace.

Learn more: https://nextjs.org/docs/messages/install-sass
 ⨯ ./src/app/components/NavBar/NavBar.module.scss
To use Next.js' built-in Sass support, you first need to install `sass`.
Run `npm i sass` or `yarn add sass` inside your workspace.

Learn more: https://nextjs.org/docs/messages/install-sass
 ✓ Compiled / in 669ms (525 modules)
 GET /_next/static/webpack/c468e23a64e34906.webpack.hot-update.json 500 in 7287ms`

I install sass, also added this below lines in nextConfig.ts file, 
`import type { NextConfig } from 'next'
 
const nextConfig: NextConfig = {
  sassOptions: {
    implementation: 'sass-embedded',
  },
}
 
export default nextConfig` 

https://nextjs.org/docs/messages/install-sass
https://nextjs.org/docs/pages/building-your-application/styling/sass
https://nextjs.org/docs/pages/building-your-application/styling/sass

**Comment by muhammadalizkhan** [comment]
@icyJoseph you now about this?

**Comment by muhammadalizkhan** [comment]
./src/app/components/NavBar/NavBar.scss
To use Next.js' built-in Sass support, you first need to install `sass`.
Run `npm i sass` or `yarn add sass` inside your workspace.
 all files are working, just facing issue in these two, 

`
import React from 'react';
import "./ServiceComponent.scss"
import { FaCode, FaSync, FaBolt, FaCogs, FaMobileAlt, FaDatabase, FaShieldAlt, FaCloud, FaBug } from 'react-icons/fa';

const services = [
  { icon: <FaDatabase />, title: 'Custom Development', description: 'Get custom software perfectly built for your business to boost productivity and efficiency.' },
  { icon: <FaMobileAlt />, title: 'Mobile App Development', description: "Make your mobile app stand out from the crowd with Devsnic's Android and iOS development." },
  { icon: <FaCode />, title: 'Web Development', description: 'Deliver high-quality web development, design and functionality tailored for your business.' },
  { icon: <FaCogs />, title: 'DevOps', description: 'Speed up your development process and improve product quality with DevOps consulting and automation services.' },
  { icon: <FaShieldAlt />, title: 'Ecommerce Ecosystem', description: 'Keep your digital assets safe and protect your business from threats with our cybersecurity solutions.' },
  { icon: <FaSync />, title: 'UI/UX Development', description: 'Drive efficiency and growth with tailored and custom UI/UX solutions for your business.' },
  { icon: <FaCloud />, title: 'Cloud Migration & Management', description: 'Seamlessly transition your business operations to the cloud with secure and scalable solutions.' },
  { icon: <FaBug />, title: 'QA Testing & Automation', description: 'Improve your software’s reliability with our comprehensive QA testing services.' },
];

export default function ServiceComponent() {
  return (
    <div className="services">
      <h2 className="services-title">From Idea to Completion, we bring Full-Stack Expertise</h2>
      <div className="services-grid">
        {services.map((service, index) => (
          <div className="service-card" key={index}>
            <div className="service-header">
              <div className="service-icon">{service.icon}</div>
              <h3 className="service-title">{service.title}</h3>
            </div>
            <p className="service-description">{service.description}</p>
          </div>
        ))}
      </div>
    </div>
  );
}`

`'use client'

import React, { useState } from 'react';
import { ArrowUpRight, Menu, X } from 'lucide-react';
import "./NavBar.scss"
import Link from 'next/link';
import Image from 'next/image';
import asyncdevlogo from "../../assets/logo/asyncdevlogo.png";

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);

  const handleLinkClick = () => {
    setIsOpen(false);
  };

  return (
    <nav className="navbar">
      <div className="navbarContainer">
        <div className="navbarHeader">
          <div className="logoGroup">
            <Link href="/" className="navbarLogo">
              <Image
                src={asyncdevlogo}
                alt="AsyncDev Logo"
                width={50}
                height={50}
                priority
              />
            </Link>
            <Link href="/"><h1 className="title">AsyncDev</h1></Link>
          </div>
          
          <button 
            className="mobileToggle"
            onClick={() => setIsOpen(!isOpen)}
            aria-expanded={isOpen}
            aria-label="Toggle navigation"
          >
            {isOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>

        <div className={`navbarContent ${isOpen ? 'isOpen' : ''}`}>
          <div className="navbarLinks">
            <Link href="/Services" className="navLink" onClick={handleLinkClick}>Services</Link>
            <Link href="/Technology" className="navLink" onClick={handleLinkClick}>Technology</Link>
            <Link href="/About" className="navLink" onClick={handleLinkClick}>About</Link>
            <Link href="/Resources" className="navLink" onClick={handleLinkClick}>Resources</Link>
            <Link href="/Contact" className="navLink" onClick={handleLinkClick}>Contact</Link>
          </div>

          <Link href="/Contact" className="scheduleButton">
            Schedule Strategy Call
            <ArrowUpRight className="arrowIcon" />
          </Link>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
`

**Comment by icyJoseph** [comment]
I can't reproduce on the link you gave: https://stackblitz.com/edit/github-9uc4ykwa?file=src%2Fapp%2FScheduleCall%2FPage.tsx

It works fine, besides this Warning:

```console
./src/app/components/NavBar/NavBar.module.scss
Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api

Import trace for requested module:
./src/app/components/NavBar/NavBar.module.scss
./src/app/components/NavBar/Navbar.tsx
```

**Comment by muhammadalizkhan** [comment]
Yup, code is working, with this 

More info: https://sass-lang.com/d/legacy-js-api
 ✓ Compiled in 615ms (759 modules)
 GET / 200 in 375ms
Deprecation [legacy-js-api]: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
 ✓ Compiled in 873ms (759 modules)
 GET / 200 in 187ms
Deprecation [legacy-js-api]: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
 ✓ Compiled in 611ms (759 modules)
 GET / 200 in 605ms
 ✓ Compiled in 391ms (414 modules)
 GET / 200 in 145ms
 GET / 200 in 237ms
 GET /favicon.ico 200 in 56ms
Deprecation [legacy-js-api]: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
 ✓ Compiled in 552ms (759 modules)
 GET / 200 in 375ms
Deprecation [legacy-js-api]: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

More info: https://sass-lang.com/d/legacy-js-api
 ✓ Compiled in 602ms (759 modules)
 GET / 200 in 208ms

**Comment by muhammadalizkhan** [comment]
this is working on my side, 

nextconfig.js
`
/** @type {import('next').NextConfig} */
 

const nextConfig = {
  sassOptions: {
    implementation: 'sass-embedded',
  },
}
 
module.exports = nextConfig`
