### ISSUE TITLE
Inconsistency between Local and Vercel related to Cache Data

### ISSUE THREAD

**Issue by GeorgeHulpoi** [vercel/next.js#73683]
### Link to the code that reproduces this issue

https://github.com/GeorgeHulpoi/nextjs-vercel-data-cache-bug

### To Reproduce

1. Build project.
2. Start project.
3. Go the the home page (you will see a v4 code).
4. Refresh the page multiple times (the same v4 code should be rendered).
5. Access  `/api/revalidate-tag`.
6. Refresh the home page and you should see a new v4 code.

### Current vs. Expected behavior

Based on the following line from docummentation [Data Cache and Full Route Cache](https://nextjs.org/docs/app/building-your-application/caching#data-cache-and-full-route-cache):
- Revalidating or opting out of the Data Cache will invalidate the Full Route Cache, as the render output depends on data.

Based on this premise, means that I have a page that is fetching from an API with a tag, revalidating that tag will revalidate the whole page.

On local, the behavior works as expected. The issue arise on Vercel. Doing the same reproduction described above, seems to not revalidate the Full Route Cache (try 2-3 times).

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 14189
  Available CPU cores: 16
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.21
  pnpm: 8.15.7
Relevant Packages:
  next: 15.0.4 // Latest available version is detected (15.0.4).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

**Comment by GeorgeHulpoi** [comment]
I've tested to check if is related with characters from tag (the bug is still present).

Also, seems like the first revalidation works. Future revalidation doesn't work.

**Comment by ztanner** [comment]
Hi,

I visited the URL of your deployed repo and it appears to be working fine. See video below.

https://github.com/user-attachments/assets/d18fb02d-95e6-4777-9647-b0faa7bcab67

I tried multiple times and it seemed successful each time. If you're observing incorrect behavior only on the Vercel platform, you might want to open a [support ticket ](https://vercel.com/help)so that it can be investigated by the infrastructure team.

**Comment by GeorgeHulpoi** [comment]
For those who have a similar problem, you may need to set `CDN-Cache-Control` and/or `Vercel-CDN-Cache-Control`.

Nonetheless, there is still a issue with Vercel described here: https://vercel.community/t/bug-data-cache-sometimes-is-stuck/2979
