### ISSUE TITLE
create-next-app init app started with error

### ISSUE THREAD

**Issue by shezhangzhang** [vercel/next.js#73725]
### Link to the code that reproduces this issue

https://github.com/shezhangzhang/test-next

### To Reproduce

1. npx create-next-app@latest
2. then everything use default
3. npm run dev
4. got this error:
<img width="1235" alt="image" src="https://github.com/user-attachments/assets/a3a1b220-45c9-4faf-a854-abfb71b53cef">

### Current vs. Expected behavior

expected no error

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.10.0
  npm: 8.11.0
  Yarn: 1.22.18
  pnpm: 8.15.5
Relevant Packages:
  next: 15.0.4 // Latest available version is detected (15.0.4).
  eslint-config-next: 15.0.4
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I'm sure everything is default.

**Comment by shezhangzhang** [comment]
I wonder if it is related to `suppressHydrationWarning`?

**Comment by ztanner** [comment]
Please check to ensure that you don't have any DOM extensions enabled that might be interfering with the page HTML before React hydrates. I was unable to reproduce this on any of the recent stable releases of Next.js.
