### ISSUE TITLE
CodeSandbox minimal reproduction example is broken

### ISSUE THREAD

**Issue by mattpodolak** [vercel/next.js#73747]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/boring-cookies-go8s7s

### To Reproduce

1. open the CodeSandbox minimal reproduction link provided by NextJS
2. open preview

### Current vs. Expected behavior

get this error:

```
Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used
```

preview should render

### Provide environment information

```bash
N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by ztanner** [comment]
lease check to ensure that you don't have any browser extensions enabled that might be interfering with the page HTML before React hydrates. I was unable to reproduce this on any of the recent stable releases of Next.js.
