### ISSUE TITLE
JavaScript heap out of memory during next build (Next 15.1)

### ISSUE THREAD

**Issue by pchab** [vercel/next.js#73793]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/distracted-forest-vhlczj?workspaceId=ws_LGaEwH7iNTCahs4YK1orjP

### To Reproduce

1. Have a moderately complex page to build (generateStaticParams + parallel routes)
2. `next build`
3. process will crash `JavaScript heap out of memory` (usually during the 'Collecting page data' step)

### Current vs. Expected behavior

`next build` process doesn't crash.

### Provide environment information

```bash
Binaries:
  Node: 22.12.0
  npm: 10.9.0
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.1.1-canary.0 // Latest available version is detected (15.1.1-canary.0).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.3.3
Next.js Config:
  output: N/A


(Also tested with node 20)
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

### Additional context

The crash doesn't happen if I reduce the size of the array returned by `generateStaticParams` or if I remove a couple parallel routes. This happens on all platform I tested: Vercel, locally and on codesandbox.io.
This used to work correctly with `next@15.0.4`.

**Comment by icyJoseph** [comment]
Hi, could you move this to a Stackblitz instead of codesandbox? Just type `next.new` into your browser address bar, and redo the example there.

**Comment by pchab** [comment]
https://stackblitz.com/edit/nextjs-vo1ozofj

**Comment by pchab** [comment]
On stackblitz, the build doesn't crash but never completes and stay indefinitely on the `collecting page data` step

**Comment by icyJoseph** [comment]
I tried to use workers to get the build going, but...

```console
uncaughtException [Error: Worker terminated due to reaching memory limit: JS heap out of memory] {
  code: 'ERR_WORKER_OUT_OF_MEMORY'
}
```

Otherwise, you get the:

```console
<--- Last few GCs --->

[26998:0x138040000]    21645 ms: Scavenge 4051.8 (4120.5) -> 4049.6 (4123.7) MB, 6.1 / 0.0 ms  (average mu = 0.452, current mu = 0.157) allocation failure; 
[26998:0x138040000]    21653 ms: Scavenge 4055.0 (4123.7) -> 4052.4 (4142.0) MB, 6.5 / 0.0 ms  (average mu = 0.452, current mu = 0.157) allocation failure; 
[26998:0x138040000]    23958 ms: Mark-sweep 4065.0 (4142.0) -> 4056.9 (4150.2) MB, 2298.2 / 0.0 ms  (average mu = 0.253, current mu = 0.026) allocation failure; scavenge might not succeed


<--- JS stacktrace --->
```

And so on... so I guess, we have to debug the build script? 🤔

**Comment by icyJoseph** [comment]
Alright, I've done a binary search/bisect, which ever, and found that this has been introduced at `15.0.4-canary.50`:

- https://github.com/vercel/next.js/releases/tag/v15.0.4-canary.50

Now it is time to check the changes introduced on that canary.

**Comment by icyJoseph** [comment]
Now I've been able to make a build work, by checking out this commit:

- 1ed81f734c20f1f8d9e8f144eb4526001cf16371

Which happens right before, this was merged https://github.com/vercel/next.js/pull/73358

Checking out, 92b3dd2de809dfa90bdb6c1c05c3493f475293c8, where #73358 sits, triggers the error, so in all likelihood, the error comes from that ISR fix for empty `generateStaticParams`

**Comment by icyJoseph** [comment]
🤔 

https://github.com/vercel/next.js/blob/7061f9428f692cc3de006b70bf85daa6fd7893a0/packages/next/src/build/segment-config/app/app-segments.ts#L115-L120


```js
   // Recursively process parallel routes <--- 🤔 x100?
   for (const parallelRouteKey in parallelRoutes) { 
     const parallelRoute = parallelRoutes[parallelRouteKey] 
     await processLoaderTree(parallelRoute, [...currentSegments]) 
   } 
 } 
```

Could that be the issue? But why, does it build up to 2x or so pages, but fails at several

**Comment by icyJoseph** [comment]
Alright, so I found the issue I think,

```console
    { slug: 'grault' },  { slug: 'garply' },  { slug: 'waldo' },
    { slug: 'fred' },    { slug: 'plugh' },   { slug: 'xyzzy' },
    { slug: 'thud' },
    ... 707181 more items
```

Within, `buildAppStaticPaths`, at the `builtRouteParams`, that can't be right... some checks are failing to contain this madness

**Comment by icyJoseph** [comment]
Just to keep on dumping info, if I take again, 1ed81f7, and run a build, the max I see is 28 items in the `parentsParams`, whereas, taking the 92b3dd2, causes this massive growth

**Comment by icyJoseph** [comment]
One more thing before signing off.

I think these lines:

https://github.com/vercel/next.js/blob/2de9722011e9f14c301fa0df099fd3591d047682/packages/next/src/build/segment-config/app/app-segments.ts#L111-L113

Are introducing a lot of repeated routes, which ends up with the, https://github.com/vercel/next.js/blob/2de9722011e9f14c301fa0df099fd3591d047682/packages/next/src/build/utils.ts#L1331-L1334 `parentParams` growing exponentially.

If I do this tweak:

```ts
    // If this is a page segment, we know we've reached a leaf node associated with the
    // page we're collecting segments for. We can add the collected segments to our final result.
    if (name === PAGE_SEGMENT_KEY) {
      currentSegments.forEach((seg) => {
        if (
          segments.some(
            (other) =>
              other.name === seg.name &&
              other.filePath === seg.filePath &&
              other.param === seg.param
          )
        ) {
          return
        }
        segments.push(seg)
      })
    }
```

Then things build fine.

**Comment by pchab** [comment]
@icyJoseph Thanks a lot for your investigation so far. To give you an order of magnitude, I noticed the issue on an application where generateStaticParams is an array of 14 elements with 7 parallel routes (in a dashboard like page).
So not a massive amount of static params.

**Comment by icyJoseph** [comment]
@pchab yeah, I saw that it gets extremely bad very quickly with the number of parallel routes. This must be fixed soon!
