### ISSUE TITLE
Router asPath doesn't match between SSR and CSR 

### ISSUE THREAD

**Issue by LineGu** [vercel/next.js#73892]
### Link to the code that reproduces this issue

https://github.com/LineGu/next-issue-reproduction

### To Reproduce

1. Run `yarn dev`
2. navigate to `/auto-export?query=true`
3. See error

### Current vs. Expected behavior

When navigating to an auto-export page with a query string, the query string information is included in the asPath during the hydration phase. It causing a mismatch between the SSR and CSR.

<img width="1618" alt="image" src="https://github.com/user-attachments/assets/7b862414-43eb-4546-860f-10fbccdae928" />

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.3.0: Thu Dec 21 02:29:41 PST 2023; root:xnu-10002.81.5~11/RELEASE_ARM64_T8122
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.15.0
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: 9.6.0
Relevant Packages:
  next: 15.1.0 // Latest available version is detected (15.1.0).
  eslint-config-next: 15.1.0
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Pages Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local), Vercel (Deployed), Other (Deployed)

### Additional context

similar issue to https://github.com/vercel/next.js/issues/8660

**Comment by icyJoseph** [comment]
I think this error is already expected, and there's a way to avoid it, documented here:

- https://nextjs.org/docs/pages/api-reference/functions/use-router#router-object

> Using the asPath field may lead to a mismatch between client and server if the page is rendered using server-side rendering or [automatic static optimization](https://nextjs.org/docs/pages/building-your-application/rendering/automatic-static-optimization). Avoid using asPath until the isReady field is true.

<img width="661" alt="Screenshot 2024-12-16 at 13 03 42" src="https://github.com/user-attachments/assets/e5d18fb0-c14a-4720-8e44-a7b62196e91d" />

**Comment by LineGu** [comment]
Oh, it’s an expected error. I thought it was a bug because the timing of asPath changes differs between auto-export dynamic pages and regular auto-export pages. Thank you!
