### ISSUE TITLE
Supabase example has duplicate utils for cn.ts

### ISSUE THREAD

**Issue by damiensedgwick** [vercel/next.js#73942]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
bunx next info
/bin/sh: yarn: command not found
/bin/sh: pnpm: command not found

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.2.0: Fri Dec  6 19:00:33 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T8122
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.1.0 // Latest available version is detected (15.1.0).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```
```


### Which example does this report relate to?

with-supabase

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

_No response_

### Describe the Bug

There is duplication of code for the classNames utility. It currently exists in 2 places with this example. Both in `lib/utils.ts` and in `utils/cn.ts` when creating a new project using `bunx create-next-app -e with-supabase`.

### Expected Behavior

It should only be declared in one location.

### To Reproduce

Create a new project using `bunx create-next-app -e with-supabase` and check the 2 locations shared in the description.

**Comment by damiensedgwick** [comment]
Hey @samcx! I see you've been experimenting with labels—looks fun! 🎉

I'm happy to help fix this example, but it would be great to confirm how we want to proceed.

In my local setup, I removed the utils directory and called the cn helper from the lib folder. However, I noticed that when a Shadcn component is installed, it expects the cn function to be in utils/cn instead of lib/cn.

It seems like we might need to update `components.json` to point to the correct location or stick with using `utils/cn`.

Let me know your thoughts!

**Comment by samcx** [comment]
@damiensedgwick Sorry was testing the label and realized this was using the correct issue template <picture data-single-emoji=":lol:" title=":lol:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/lol/5986e156eca2154f.png" alt=":lol:" align="absmiddle"></picture> 

Always feel free to open a PR and ping me on the PR (no need to ask permission for opening PRs)! I would always double-check if there is an open PR(s) already to fix the issue.
