### ISSUE TITLE
Server action throws when accessing headers if invoked before hydration

### ISSUE THREAD

**Issue by jonathanhefner** [vercel/next.js#73992]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/nice-rgb-xsqkxt

### To Reproduce

1. Start the application in development.
2. Open the preview in a dedicated browser tab.
3. Disable JavaScript in that tab using the browser's dev console ([Chrome instructions](https://developer.chrome.com/docs/devtools/javascript/disable); in Firefox, click the cog wheel menu in the upper right corner of the debugger).
4. Refresh the tab.
5. On the application root page, click the "Action without headers" button.  Notice that the action _works_ and the browser is successfully redirected.
6. Navigate back.
7. On the application root page, click the "Action with headers" button.  The action _does not work_.  The following error appears in the server log:
    ```
     ⨯ Error: `headers` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
        at headers (app/actions.ts:11:16)
       9 |
      10 | export async function actionWithHeaders() {
    > 11 |   (await headers()).get("referer");
         |                ^
      12 |   redirect(`/result/${Date.now()}`);
      13 | }
    ```

### Current vs. Expected behavior

I expect the `actionWithHeaders()` action to succeed just like the `actionWithoutHeaders()` action.  If for some reason that isn't possible, I expect a more accurate error message (`headers` is, in fact, being called inside a request scope).

### Provide environment information

```bash
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
  Available memory (MB): 4102
  Available CPU cores: 2
Binaries:
  Node: 20.9.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.10.2
Relevant Packages:
  next: 15.1.1-canary.6 // Latest available version is detected (15.1.1-canary.6).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

**Comment by OlegLustenko** [comment]
We have similiar issue, but it happens for pages with prefetch.
headers and cookies are in fact called in server actions, but we are getting the same issue and only in `production` builds

```bash
 ⨯ Error: `headers` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
    at headers (app/actions.ts:11:16)
```

I have a hard times trying to build an easy example for it. However it seems like ALS loosing context between prefetching

**Comment by AdamMikacich** [comment]
Having the same issue (also occurs with cookies as they're assigning a Set-Cookie header). Here is a simple example that you can test in a fresh Next.js install.

``` tsx
import { cookies } from "next/headers";

export async function setCookieAction() {
  "use server";

  // Works with JavaScript enabled (and loaded)
  // Otherwise: Error: `cookies` was called outside a request scope.
  const cookieStore = await cookies();
  cookieStore.set("myCookie", "myValue");
}

export default function Page() {
  return (
    <form action={setCookieAction}>
      <button type="submit">Set Cookie</button>
    </form>
  );
}
```

**Comment by OlegLustenko** [comment]
Hey @unstubbable ! Thanks for attention for this issue!

It still reproduces in our case, not all the time but all the time for full prefetching requests

**Comment by unstubbable** [comment]
@OlegLustenko I don't understand how prefetching is related to this progressive enhancement issue with server actions. Can you elaborate?

**Comment by OlegLustenko** [comment]
@unstubbable sure! Sorry for not following a proper issue format with reproducing code-base
I had hard time reproducing this issue in a fresh code-base.

I recorded a short video explaining some cases, in our case it's pretty flaky bug that appearing on some pages but all the time with prefetching

https://github.com/user-attachments/assets/a9218701-34b7-4616-bc10-f25b1cc0a210

If I can provide more information I'll be glad to! It also fine if we should open a new issue for this

**Comment by unstubbable** [comment]
Yeah, so this doesn't seem to be related to server actions that are sent before hydration at all. Can you please try to reduce your case to a minimal reproduction and create a new issue with it?
