### ISSUE TITLE
Error: TAR_BAD_ARCHIVE: Unrecognized archive format

### ISSUE THREAD

**Issue by gengooro** [vercel/next.js#74024]
### Link to the code that reproduces this issue

https://github.com/gengooro/my-app

### To Reproduce

1. Create a fresh nextjs project ( npx create-next-app@latest )
2. And let it install.

![Screenshot 2024-12-17 at 9 55 17 PM](https://github.com/user-attachments/assets/2d25b2b8-9f95-4ed2-8657-192e6c737379)

### Current vs. Expected behavior

Current behavior: while installing the initial `npm install` packages it gives error:
`npm warn tar TAR_BAD_ARCHIVE: Unrecognized archive format
npm error code TAR_BAD_ARCHIVE
npm error TAR_BAD_ARCHIVE: Unrecognized archive format
npm error A complete log of this run can be found in: /Users/xxxx/.npm/_logs/2024-12-17T13_50_41_194Z-debug-0.log`

Expected behavior: it should install the packages without any errors.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0
Binaries:
  Node: 22.12.0
  npm: 11.0.0
  bun: 1.1.39
Relevant Packages:
  next: 15.1.0
  react: 11.0.0
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

Initially i thought there's something wrong with my node. i reinstalled node 2 times and the error was not resolved, so i tried creating react app via vite, and nodejs projects and it worked flawless. So i guess the issue is with the `npx create-next-app@latest`

**Comment by thoilemba** [comment]
Check this issue: [[BUG] npm fails install of any packages - TAR_BAD_ARCHIVE #7893
](https://github.com/npm/cli/issues/7893)

**Comment by thoilemba** [comment]
For me, it worked when using VPN.
The error for me is "304 https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz 1607ms". You can check it in the log file.
The error occurred because the network connection was likely causing issues while downloading the cssesc package (in your case maybe another package) from the npm registry.
Or try using the npmmirror: npm config set registry https://registry.npmmirror.com

**Comment by ztanner** [comment]
Thanks for the report - however, this appears to be an issue with the npm registry itself, and not Next.js related.
There was an incident yesterday related to that error message -- here's the latest status on it: https://status.npmjs.org/incidents/bxvmmvlqzfds

**Comment by gengooro** [comment]
I guess the issue was with my WIFI/Ethernet. After i restarted my computer it did work without any issues.
