### ISSUE TITLE
`params` are awaited well but the warning, `params` should be awaited before using its properties. is still displayed

### ISSUE THREAD

**Issue by ErwannRousseau** [vercel/next.js#74402]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.15.2
Relevant Packages:
  next: 15.1.3 // Latest available version is detected (15.1.3).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Which example does this report relate to?

with-turbopack

### Describe the Bug

I encountered an issue after upgrading my Next.js project to version 15 and applying the required changes to support asynchronous `params`. Specifically, I'm seeing the following error when using the `--turbopack` flag during development:

```sh
✓ Compiled /[lang]/blog/[slug] in 2.6s
Error: Route "/[lang]/blog/[slug]" used `params.lang`. `params` should be awaited before using its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at Array.map (<anonymous>)
```

The issue disappears if I:
1. Disable the `--turbopack` flag by running `next dev` without it.
2. Move the `opengraph-image.png` file from `/app/[lang]/blog/opengraph-image.png` to the root of the `/app` directory.

However, moving the file is not the desired behavior, as I want the `opengraph-image.png` to reside under `/app/[lang]/blog`.

### Comment

Here is the structure of my `app/` directory:

```sh
app/
├── [lang]
│   ├── blog
│   │   ├── [slug]
│   │   │   └── page.tsx
│   │   ├── opengraph-image.png
│   │   └── page.tsx
│   ├── layout.tsx
│   ├── loading.tsx
│   ├── page.tsx
│   ├── robots.ts
│   └── sitemap.ts
├── api
│   └── like
│       └── route.ts
├── apple-icon.png
├── favicon.ico
├── globals.css
└── studio
    ├── [[...index]]
    │   └── page.tsx
    └── layout.tsx
```

My `package.json` development script:
```json
"dev": "next dev --turbopack",
```

I updated the code in my app as per the Next.js 15 migration guide:

```ts
export async function generateMetadata(
  props: Readonly<{
    params: Promise<{ lang: Locale }>;
  }>,
): Promise<Metadata> {
  const { lang } = await props.params;

//...

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}>) {
  const { lang } = await params;
```

I've done it wherever necessary.

### Expected Behavior

The application should compile and run without errors when using the `--turbopack` flag, and the `opengraph-image.png` file should remain at `/app/[lang]/blog` without causing warnings or errors.

### To Reproduce

Steps to reproduce the issue:

1. Use the following `app/` directory structure:

   ```sh
   app/
   ├── [lang]
   │   ├── blog
   │   │   ├── [slug]
   │   │   │   └── page.tsx
   │   │   ├── opengraph-image.png
   │   │   └── page.tsx
   │   ├── layout.tsx
   │   └── page.tsx
   ├── globals.css

   ```
   or clone [ErwannRousseau/portfolio](https://github.com/ErwannRousseau/portfolio), but not sure it's very simple to run cause you might need env variables.
3. Add `"dev": "next dev --turbopack"` to your `package.json`.
4. Use the updated async `params` handling as shown in the code snippet above.
5. Run `dev` process with `--turbopack` enabled.
6. Observe the error when navigating to `/[lang]/blog` and `/[lang]/blog/[slug]`

Disabling `--turbopack` or moving the `opengraph-image.png` to the root of `/app` resolves the issue, but this is not the intended behavior.

**Comment by Netail** [comment]
I think you created an issue under the wrong issue template;
![image](https://github.com/user-attachments/assets/f740d86c-35b1-40d1-a214-e6b5cff7db8e)
The second one is meant for issues with one of the NextJS examples in here: https://github.com/vercel/next.js/tree/canary/examples
