### ISSUE TITLE
Possible to pass state to next/router?

### ISSUE THREAD

**Issue by bryan** [vercel/next.js#771]
With react-router I was able to do: 

`browserHistory.push({ pathname: "/", state: { message: 'This is a message forwarded in a state.' } })`

Is it possible to do something like this using next/router or a way to redirect the user and also pass some value over to the new page?

**Comment by arunoda** [comment]
Currently that's not possible and I don't think we'll support it immediate future.

**Comment by arunoda** [comment]
But let's open this and see whether we really really need this.

**Comment by nkzawa** [comment]
I think you should do this by passing query parameters.

**Comment by bryan** [comment]
I mean you can achieve a similar thing by passing in query parameters like nkzawa said, but I'd rather not pollute my the url with `http://www.example.com/?message=This%20is%20a%20long%20message%20forwarded%20to%20be%20displayed` and would rather have a state transfer like how react-router does it.

**Comment by rauchg** [comment]
You can use `as` to disguise the URL

**Comment by bryan** [comment]
Well I suppose so, but if I were to use `as`, the pathname doesn't retain the actual pathname in props.url.pathname, which means more things to pass into the query. It's just _cleaner_ to have it pass the state. 

I'm porting over a project to next.js and haven't run into any major compatibility problems since I found ways to refactor codes to make it work, it's just inconvenience and verbosity at this point that can be improved and all this issue is.

Thanks all for your input.

**Comment by timneutkens** [comment]
Closing this cause of inactivity 👍

**Comment by sergiodxa** [comment]
You can save any required state in localStorage, sessionStorage, a variable, a Redux store, etc. and then use it in getInitialProps (checking you are running client side).

**Comment by egaleme** [comment]
i think nextjs should start supporting react-touter

**Comment by vaibhavi3t** [comment]
I want same functionality.

Earlier I was using CRA and there I used to send state to routed component. I wants same functionality with nextjs. 

What @sergiodxa suggested in workaround but library support will be good.

**Comment by todesstoss** [comment]
Same here, would be great if it will be possible pass data with `Router.push()` and retrieve it later with `withRouter`

**Comment by namy16** [comment]
I want same functionality. Any update on this ?

**Comment by namlq93** [comment]
> I want same functionality. Any update on this ?

me too

**Comment by allicanseenow** [comment]
Another question related to this issue is:
- I don't want to pollute my URL when I call the Router.push() and I want to pass a state to the next component. Is there any way to do it? Using localStorage or cookie is a bad practice as they are not directly controlled by React hooks or the old React lifecycle

**Comment by abdulhadi1995** [comment]
I have a scenario where I have a clickable component. clicking it would open its details page. With current next.js i can pass the projects id and then get the details using useEffect and axios call but since i already have the data i really wished i could send the state to that page.

**Comment by avin-kavish** [comment]
Would be nice to have this.

@sergiodxa Yes, there are many ways to pass temporary messages but the advantage of having it tied to the router is that we don't have to write extra code to manage the life cycle of the values we pass around. They will be tied to router navigation events and unavailable in other contexts.

For example, If I push it to my redux store, then I have to exclude it from being persisted to local storage and also the message on the receiving end.

If I add it the query string it becomes a perma link that uses can bookmark and later return to.

But it I can push it to the next page and only the next page via `router.push` I don't have to make any compensations; the value will only be available in that context.

Very similar to [connect-flash](https://github.com/jaredhanson/connect-flashl)

**Comment by Divlo** [comment]
No solution since Jan 15 2017 ?
We need that feature : 
> Same here, would be great if it will be possible pass data with `Router.push()` and retrieve it later with `withRouter`

**Comment by davidebukali** [comment]
Would be nice to have this in nextjs

**Comment by azamiya** [comment]
if you want to hide query params, just use like this

```
Router.push(`/main?userName=${userName}`, 'main')
```

than the main page, you can see only `/main` on url and
`console.log(Router.route)` shows query

```
pathname: "/main"
query: {userName: "fadsfasd"}
asPath: "main"
```

**Comment by avin-kavish** [comment]
oh yeah, that's true. Btw I find it really awkward that router requires two strings. `react-router` works beautifully without, why does this?

**Comment by francisrod01** [comment]
For those who want to make it, you can use `Context Api`.

Next.js provides the `router.push()` passing `shallow: true` as a prop.
It's the most simple state management to do that.
https://nextjs.org/docs/api-reference/next/router#routerpush

**Comment by timneutkens** [comment]
Willing to reconsider this, however it needs a **great** proposal on how to prevent users from shooting themselves in the foot using history state given you can't access history state server-side for example, it would be very easy to cause hydration issues.

Do note that re-opening this does not mean that I'm not going to write a RFC for this feature, that would be up to the people that want to have this feature.

**Comment by myoneflag** [comment]
`
    Router.push({
      pathname: '/',
      query: { message: 'This is a message forwarded in a state.' }
    }, '/')`

**Comment by umakantp** [comment]
More than 2 years and still waiting for state feature

**Comment by avin-kavish** [comment]
> ` Router.push({ pathname: '/', query: { message: 'This is a message forwarded in a state.' } }, '/')`

This is still not internal state, it's a query string with a mask feature, which is quite an odd thing to do in my opinion.

**Comment by pxwee5** [comment]
I'm not super familiar with React ecosystem. But it appears that you can do
```
router.push(
  { pathname: '/hello-world' }, 
  '/hello-world/2', 
  { step: 2 }
);
```

When you go back and check before PopState, the option prop will contain `{ step: 2 }`.

**Comment by likerRr** [comment]
> I'm not super familiar with React ecosystem. But it appears that you can do
> 
> ```
> router.push(
>   { pathname: '/hello-world' }, 
>   '/hello-world/2', 
>   { step: 2 }
> );
> ```
> 
> When you go back and check before PopState, the option prop will contain `{ step: 2 }`.
> 
> We only need this in the `router` object.

It seams like another temporal hack, not intentional behavior. Expected options are listed in the [docs](https://nextjs.org/docs/api-reference/next/router#routerpush). But something similar to this would be great to have as expected behavior

**Comment by pxwee5** [comment]
@likerRr Apparently all of the options parameter is being passed to `window.history.state`. So with my example:
`window.history.state == { step: 2 }`

**Comment by likerRr** [comment]
> @likerRr Apparently all of the options parameter is being passed to `window.history.state`. So with my example:
> `window.history.state == { step: 2 }`

Seems like it is. Anyway, until it's documented, it can't be used in prod, because logic can be changed anytime :disappointed:

**Comment by ken-nah** [comment]
Would be nice if next js considered this

**Comment by TrongTrinh** [comment]
This worked for me, you can use
https://github.com/vercel/next.js/issues/771#issuecomment-612018764

1: in the Subscription page: 
const handleClick = useCallback((mount) => {
        Router.push(`/payment?mount=${mount}`, '/payment');
    }, []);
2: in Payment Page
useEffect(() => {
        const {
            query: { mount },
        } = Router;
        !mount && Router.push('/campaign-overview/subscription');
        console.log('PaymentVM:React.FC -> mount', mount);
    }, []);

you can see value of `mount` in console browser.

**Comment by meilechwieder** [comment]
I understand the issue and the convinience of passing along state in history.push. Would the following be a temporary solution?

Have a global context then have a local state which is initially set to null. In useEffect, map global state to local state. Then, If state is null, return loader, else return component with data of the local state. So the first render will always have the loader, then after useEffect, component will rerender with data from state. Furthormore, we can set another useEffect which should be triggered if something changes in global context and map again local to global.

Also, cant we just use the browser's history.pushState, as well as a local location state, and upon pushing state, setting a value to local location state which should trigger a useEffect run. Then have a JS swich statment which evaluates the location and returns components based on the location. And if we wanna get to the same component without history.pushState, we can make the location a dynamic next query param. -- did not try it, just trying to think of workarounds.

**Comment by meilechwieder** [comment]
I understand the issue and the convenience of being able to  pass along state in router.push. 

Would the following be a temporary solution?

Use the browser's history.pushState, as well as a local useState of a location string, and upon pushing state, setting a value to local location state to the new location. An update to the location string state should trigger a useEffect run. Then have a JS swich statment which evaluates the location and returns components based on the location. And if we wanna get to the same component without history.pushState (for exp. if the user refreshes the page), we can make the location a dynamic next query param. -- did not try it, just trying to think of workarounds.

**Comment by meilechwieder** [comment]
> For those who want to make it, you can use `Context Api`.
> 
> Next.js provides the `router.push()` passing `shallow: true` as a prop.
> It's the most simple state management to do that.
> https://nextjs.org/docs/api-reference/next/router#routerpush

What if in my in my getServerSideProps, i make to calls, one of which should be redone for every load, and one should only be loaded with a condition. For that, `Shallow: true` would not help much becuase its not a state manager, its either refetch all server side props, or dont do it at all.
An example of this scenario would be if I make two seperate call for the main content of the page and then another call to get the navigation links. In an initial render, I want both calls to be on the server, but then, I already have the nav links in memory so I dont need to refetch them. Thats why we need state. And our code would be awful it for every `<Link/>` we pass in a bounch of query params with our state. (Actually, as Im writing, Im thinking of making an HOC Link which should go the the specified href and send along a query object with the current state so I wouldnt need to write the state object in each `<Linke/>`, I'll only handle this in the HOC)

**Comment by marcelalburg** [comment]
Hello, 

are there any explanations from the vercel / next team, why it would be problematic to pass a state to the router/link ? It looks like this topic is required by a lot of people (even from me - and i don't see any valid reason against this in this chat).

My usecase is tostore the scroll position (not of the page, the scroll position from an overflow:hidden div), so that a user can go back and have the same position inside this div as before. 

I could imaging to have a[ state property](https://github.com/vercel/next.js/blob/bbc1a21c749c423e842586ab116889c9f9c7024e/packages/next/client/link.tsx#L21) for the [NextLink](https://nextjs.org/docs/api-reference/next/link).

`<Link ... sate={{ value: 1 }}>LInk that store the State </Link>
`

This param can be passed to the [router push](https://github.com/vercel/next.js/blob/bbc1a21c749c423e842586ab116889c9f9c7024e/packages/next/client/link.tsx#L145). The next framework is using already the state for their purpose.

I and mostly all in this thread would appreciate if request can be added to the code. 

Thanks a lot for all your nice work and the nextjs framework

**Comment by rodbs** [comment]
I'd also be interested in having this functionality of passing state to next/router. Thx!

**Comment by marcin-kochanek** [comment]
Me too!

**Comment by timneutkens** [comment]
As said earlier: https://github.com/vercel/next.js/issues/771#issuecomment-622362614

**Comment by marcelalburg** [comment]
Okay, I agree, this is a valid concern.

**Comment by meilechwieder** [comment]
> Hello,
> 
> are there any explanations from the vercel / next team, why it would be problematic to pass a state to the router/link ? It looks like this topic is required by a lot of people (even from me - and i don't see any valid reason against this in this chat).
> 
> My usecase is tostore the scroll position (not of the page, the scroll position from an overflow:hidden div), so that a user can go back and have the same position inside this div as before.
> 
> I could imaging to have a[ state property](https://github.com/vercel/next.js/blob/bbc1a21c749c423e842586ab116889c9f9c7024e/packages/next/client/link.tsx#L21) for the [NextLink](https://nextjs.org/docs/api-reference/next/link).
> 
> `<Link ... sate={{ value: 1 }}>LInk that store the State </Link> `
> 
> This param can be passed to the [router push](https://github.com/vercel/next.js/blob/bbc1a21c749c423e842586ab116889c9f9c7024e/packages/next/client/link.tsx#L145). The next framework is using already the state for their purpose.
> 
> I and mostly all in this thread would appreciate if request can be added to the code.
> 
> Thanks a lot for all your nice work and the nextjs framework

Actually, you can do it with hidden query params. In nextjs you can redact query params with the `as` prop on the `<link/>` component or with the second argument for the `router.push` method.

**Comment by marcelalburg** [comment]
@meilechwieder : Thanks for this idea. It's not a clean solution but with a dedicated React  Link Component (only for this scrolling case) it could work out without creating so much dept.

**Comment by sughodke** [comment]
You can use HTML5 `replaceState` to clean up the window location.

```
history.replaceState(null, '', `/post/${id}`);
```

https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState

**Comment by mv29** [comment]
I am still waiting for this functionality, hope it gets implemented in near future.

**Comment by fultonm** [comment]
Yeah this feature is really needed.
