### ISSUE TITLE
typing of pageProps in AppInitialProps is not generic

### ISSUE THREAD

**Issue by itskibo** [vercel/next.js#8784]
# Bug report

## Describe the bug

AppInitialProps.pageProps is typed as `any`
- typing props as `AppProps & { pageProps: CustomPageProps }` does not fix this
- asserting `this.props` as `AppProps & { pageProps: CustomPageProps }` does not fix this
- module augmentation does not fix this (or I failed to do it properly, but this is highly unwanted anyway)

## To Reproduce

Minimal reproduction (Codesandbox does not allow for Next and TypeScript, but type hinting is still there):
https://codesandbox.io/s/appinitialprops-incorrent-type-u0xx4

To test with TypeScript itself:
1. run `yarn create next-app`
2. rename `*.js` -> `*.tsx`
3. create `pages/_app.tsx` with at least the following content:
    ```typescript
    import App from "next/app";

    export default class extends App {
        render() {
            const { Component, pageProps } = this.props;

            return <Component {...pageProps} />;
        }
    }
    ```

## Expected behavior

Able to specify the type of `pageProps` through the use of generics, with the default set to `unknown` or an empty object or whatever is deemed valid as a default type, like:
```typescript
interface AppInitialProps<P extends object = {}> {
    pageProps: P
}
```

## System information

- Version of Next.js: 9.0.5

## Additional context

Some "hacky" workarounds through type asserting:
- `this.props.pageProps as CustomPageProps`
- `const { pageProps } = { ...this.props, pageProps: this.props.pageProps as CustomPageProps }`

Neither are really wanted imho, I think more people would prefer to be able to type this through generics instead of asserting it.

**Comment by itskibo** [comment]
Solved this using a functional component, although I still feel like this isn't the correct solution as this is undocumented:

```typescript
import { NextComponentType } from "next";
import dynamic from "next/dynamic";
import NextApp, { AppContext, AppInitialProps, AppProps } from "next/app";
import React from "react";

import { BaseLayoutProps } from "../typings/Layout";
import { BasePageProps } from "../typings/Page";

const App: NextComponentType<AppContext, AppInitialProps, Partial<BasePageProps> & AppProps> = (props) => {
  const { Component, pageProps: { layout = void 0, ...pageProps} } = props;

  if (typeof layout !== "undefined") {
    const Layout = dynamic<BaseLayoutProps>(() => import(`../layouts/${layout.type}`));

    return <Layout>
      <Component {...pageProps} />
    </Layout>
  }

  return <Component {...pageProps} />;
}

App.getInitialProps = NextApp.getInitialProps;

export default App;
```

**Comment by FDiskas** [comment]
I think that this should not be closed :/

**Comment by FDiskas** [comment]
I used this like so:
```tsx
import { NextPage } from 'next';

interface MyProps extends AppProps {
    foo?: string
}

const App: NextPage<MyProps> = () => {}
```

But this still not correct way. For example if I use 
```ts
import { appWithTranslation } from 'next-i18next';

export default appWithTranslation(MyApp);
```
and `i18n` will be awailable within `pageProps`

**Comment by GiancarlosIO** [comment]
is there a solution for this? looks like this is still a problem in nextjs v11 😢

**Comment by pixelass** [comment]
We use it like this:

next.js v11
Using next-i18next for localization

```tsx
import { AppProps as NextAppProps } from "next/app";
import { appWithTranslation } from "next-i18next";
import React, { createContext, useContext } from "react";

export interface AppProps extends NextAppProps<PageProps> {
	pageProps: {
		foo: string;
		/* Your Page Props */
	};
}

// Use case: A Custom provider that needs access to foo
const MyContext = createContext({foo: "bar"});
const { Provider: MyProvider } = MyContext;

const App: NextPage<AppProps> = ({ Component, pageProps }) => {
	/* Things you want to do in the app */
	return (
		<MyProvider value={pageProps.foo}>
			<Component {...pageProps} />
		</MyProvider>
	);
}

export default appWithTranslation(App as ComponentType<NextAppProps>);
```

**Comment by pixelass** [comment]
I changed my workaround to this: (less assertion)

```tsx
import { AppProps, NextPage } from "next/app";
import { appWithTranslation } from "next-i18next";
import React, { createContext } from "react";

interface PageProps {
	foo: string;
	/* ...more page props */
}

interface MyAppProps extends AppProps<PageProps> {
	pageProps: PageProps;
}

// Use case: A Custom provider that needs access to foo
const MyContext = createContext({foo: "bar"});
const { Provider: MyProvider } = MyContext;

const App: NextPage<AppProps> = ({ Component, pageProps }: MyAppProps) => {
	/* Things you want to do in the app */
	return (
		<MyProvider value={pageProps.foo}>
			<Component {...pageProps} />
		</MyProvider>
	);
}

export default appWithTranslation(App);
```

**Comment by itskibo** [comment]
Been a long time since I closed this issue, but it is still prevalent to this day, so I will reopen it for discussion.

**Comment by FDiskas** [comment]
It is actually documented, but for `getServerSideProps` I still get `any`
![Screenshot from 2021-08-23 12-48-48](https://user-images.githubusercontent.com/468006/130427353-0020f861-9afe-463c-9b96-6e57126ad5ed.png)

https://nextjs.org/docs/basic-features/data-fetching#typescript-use-getstaticprops

**Comment by pixelass** [comment]
@FDiskas The issue occurs in the `_app.{jsx,tsx}` file. The linked docs talk about general pages. The App does not know about the adjustments in pages, or their server or static page methods. It's a totally different context, therefore typescript does not know about it. 

I think, ATM the only fix is to either use a technique as described by me, or look into module augmentation (Read about it here https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-8.html#augmenting-globalmodule-scope-from-modules)

**Comment by FDiskas** [comment]
I landed with something like this.
```tsx
import * as React from 'react';
import { NextPage, GetServerSideProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

interface ServerSideProps {
    initialData: {
        testData: string;
    };
}

type PageParams = {
    requestId: string;
    id: string;
};

const Demo: NextPage<ServerSideProps> = ({ initialData }) => (
    <div className={styles.root}>Demo Page with {initialData.testData}</div>
);

export const getServerSideProps: GetServerSideProps<ServerSideProps, PageParams> = async ({
    locale,
    defaultLocale,
}) => {
    const initialData = {
        testData: 'test data',
    };

    return {
        props: {
            ...(await serverSideTranslations(locale ?? (defaultLocale as string), ['common'])),
            initialData,
        },
    };
};

export default Demo;
```

**Comment by soutovnc** [comment]
disregard if you already understand, but currently I start as follows:

```
import { AppProps } from 'next/app'

import '../styles/global.scss'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <h1>Testing...</h1>  
    </>
  ) 
}

export default MyApp

```

**Comment by espipj** [comment]
Hey! This is still what I would say a _bug_ in the types. In fact is leading people to wonder around stackoverflow finding workaround and hacks ([example](https://stackoverflow.com/questions/64722812/what-typescript-type-should-nextjs-app-tsx-component-and-pageprops-be)). I'm happy to work on this issue to fix it adding a generic type. 😃

**Comment by balazsorban44** [comment]
You can now use `import { AppProps } from "next/app"` which takes an optional generic:

`_app.tsx`:
```ts
import { AppProps } from "next/app"

export default function App({ Component, pageProps }: AppProps<{foo: "bar"}>) {
  pageProps.foo // is type "bar"
...
}
```

Please make sure you are on `next@latest` for this.
