### ISSUE TITLE
Non-hoisted styled-jsx dependency breaks styles

### ISSUE THREAD

**Issue by ctavan** [vercel/next.js#9325]
# Bug report

## Describe the bug

When `styled-jsx` with a version other than the one bundled with Next.js is manually added as a dependency to a Next.js project, style loading is delayed leading to an unstyled initial rendering flash.

## To Reproduce

Reproduction in: https://github.com/ctavan/next.js-reproduce-styled-jsx-bug/commits/master

Adding `styled-jsx` as a dependency manually produces the buggy behavior: https://github.com/ctavan/next.js-reproduce-styled-jsx-bug/commit/489616fc9156ee9a089eb25f646e4ef10a037e36

## Expected behavior

Adding `styled-jsx` as a dependency manually should either not produce the bug or lead to a build-time error/warning in Next.js (or it should be at least documented that you should not add another version than the bundled one of `styled-jsx` to a Next.js project).

## Screenshots

Here's how the `<head>` looks like, when there is NO additional `styled-jsx` dependency. Note that the `<style>` tags are included _before_ `chunk/0.js` is loaded in a blocking fashion:

<img width="684" alt="working" src="https://user-images.githubusercontent.com/508118/68287212-a1e35480-0082-11ea-80ac-2596f02b2f58.png">

Here's how the `<head>` looks like, when there is an additional `styled-jsx` dependency (different version than the one bundled with Next.js). Note that the `<style>` tags are included _after_ `chunk/0.js` is loaded in a blocking fashion leading to html content flashing unstyled until `chunk/0.js` has been loaded:

<img width="687" alt="broken" src="https://user-images.githubusercontent.com/508118/68287341-db1bc480-0082-11ea-9578-903d1e1e7c1b.png">

## System information

- OS: macOS
- Version of Next.js: 9.1.2

**Comment by Timer** [comment]
Adding a warning when someone tries to install `styled-jsx` themselves sounds reasonable to me.

**Comment by ctavan** [comment]
@Timer any pointer of where and how this could be done? I'm happy to contribute.

**Comment by Timer** [comment]
We don't really have any prior art, so it's open for exploration. Maybe similar to how we check if minification was disabled.

**Comment by olingern** [comment]
I would probably hook into [`preinstall` or `postinstall`](https://docs.npmjs.com/misc/scripts) depending if you want to throw an error ( pre-installation ) or warn ( post-installation ). 

It does get complicated if you want to give a user a warning that references the correct package. For example, if `styled-jsx` was loaded as a child or peer dependency, you would want to warn the user with the parent, offending package that is in their `package.json`. From doing some work on yarn in the past, I can say this becomes complex quick unless you're handy with graphs and DFS.

An easier way might be to just check if the user's `node_modules` directory contains `styled-jsx` and then warn give an ambiguous warning, i.e. _"It looks like one of your packages is using styled-jsx, which causes issues with Next.js."_

**Comment by joncursi** [comment]
Is there a way to import `styled-jsx` "through" `next`?

Most of my CSS is defined in separate files that get imported into the main component files, which kinda forces me to install my own version of `styled-jsx` in my `package.json`.

As described in this issue thread, this opens up the developer to package versioning issues between `styled-jsx` and `next`.

**Comment by cleverboy32** [comment]
so  what can i do to fix this question
