### ISSUE TITLE
Fatal error running firebase on server and client side together (database loaded twice error)

### ISSUE THREAD

**Issue by rcmenezes** [vercel/next.js#9620]
# Bug report

## Describe the bug
I'm getting `Error: FIREBASE FATAL ERROR: Database initialized multiple times. Please make sure the format of the database URL matches with each database() call. ` when I try to run firebase both from my node/express server as well as from the client side, crashing the app. A few things worth noting:
- I have this exact same setup running on other projects where this error doesn't happen
- This project with the issue also running fine for a while, but stopped working rather suddenly. Can't really remember if I changed anything that caused this though :(
- If I remove firebase from either the client or server, it works
- I've tried upgrading all packages, cleaning it all up and installing fresh, didn't work
- I contacted Firebase, they were able to replicate and said this was an issue with Next, not with Firebase

## To Reproduce
I created a mcve here: https://github.com/rcmenezes/firebase-issue-mcve
It has already an .env file with a disposable firebase project and its credentials, but you can use any other firebase project to test. So, just run the app with yarn dev and try to access the page on http://localhost:3000

## Expected behavior
For the error to be gone and it not crash :)

## System information
- OS: Mac 
- Browser (if applies): error happens on all browsers
- Version of Next.js: tested on 9.1.2 and 9.1.4

Thanks a lot for any help!

**Comment by Herlevsen** [comment]
I think it might be a race condition of some sort. I remember having a similar issue.

Try doing it like this instead:

```js
export function getFirebaseApp() {
  if (firebase.apps.length > 0) return firebase.app();

  const config = {
   apiKey:  process.env.FIREBASE_API_KEY,
   authDomain: process.env.FIREBASE_AUTH_DOMAIN,
   databaseURL: process.env.FIREBASE_DATABASE_URL,
   projectId: process.env.FIREBASE_PROJECT_ID,
   storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
   messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID
 };

 return firebase.initializeApp(config)
}

const firebase = getFirebaseApp()
const database = firebase.database();
const auth = firebase.auth();

export { firebase, auth, database as default };
```

**Comment by rcmenezes** [comment]
Thanks for the suggestion @Herlevsen. I've tried that, but still having the same issue. I have a suspicion that it isn't about how Firebase is initialized (even though the error seems to be about that) because I have the same init setup in other Next projects and it has always worked fine.

**Comment by rcmenezes** [comment]
OK, I think I figured this out, at least partially. It seems like the issue is that when pages get rendered on the server-side, the firebase database was being initialized already, then initialized again on the client-side, crashing it. 

I fixed the issue with this check on the client-side db initialization:
`const database = process.browser ? firebase.database() : undefined`

But I have no clue if there are any side effects to this? Also, this seems to explain why some of my projects work and some don't with the same setup - the difference has to be on some "magic" being done by Next.js while rendering or processing pages on the server, that ends up triggering (or not) the firebase database initialization twice. 

Any thoughts on a more definitive solution to this?

**Comment by Herlevsen** [comment]
On the server you are using firebase-admin to initalize the app and on the "client" you are using firebase/app. As you probably know, the server calls your client code when you `return handle(req, res);`. I guess firebase-admin and firebase/app is not supposed to be running simultaneously. Do you actually need firebase in your server code?

**Comment by eezing** [comment]
I’m using Firebase auth and saw and error like this; fixed it the same way as @Herlevsen. To prevent Firebase client from loading during SSR, my init calls are made within a React useEffect hook.

**Comment by eezing** [comment]
@rcmenezes, PR for your mcve: https://github.com/rcmenezes/firebase-issue-mcve/pull/1

Lazy loading firebase client from client code resolves the issue.

**Comment by Giacomellivinicius** [comment]
> @rcmenezes, PR for your mcve: https://github.com/rcmenezes/firebase-issue-mcve/pull/1
> 
> Lazy loading firebase client from client code resolves the issue.

Link out :(
