### ISSUE TITLE
Detect when user leaves the page

### ISSUE THREAD

**Issue by lcswillems** [vercel/next.js#9662]
# Feature request

## Is your feature request related to a problem? Please describe.

I would like to detect when the user leaves the page. I count 3 ways of leaving a page:
- by clicking on a link
- by doing an action that triggers `router.back`, `router.push`, etc...
- by closing the tab (i.e. when `beforeunload` event is fired)

I know this kind of issue has already been opened [here](https://github.com/zeit/next.js/issues/2236) or [here](https://github.com/zeit/next.js/issues/2694), but they had been magically closed (using some `duplicate` trick) without providing any solution.

Being able to detect when a page is leaved is very helpful for, for example, alerting the user some changes have not been saved yet.

## Describe the solution you'd like

I would like something like:

```
router.beforeLeavingPage(() => {
    // my callback
})
```

**Comment by St1myL** [comment]
+1 :+1: for this feature

**Comment by italoayres** [comment]
Have you seen [the docs foi Router events ?](https://nextjs.org/docs#router-events). It may do the trick.

**Comment by lcswillems** [comment]
Yes, I seen it. But it doesn't. There is no way to cancel a route.

**Comment by lexxanatoli** [comment]
Any updates about this feature request?

**Comment by grapgrapMMT** [comment]
I want to prevent go to back when click browser back button or mouse back button too.

**Comment by srcnalt** [comment]
Needed this feature just now.

**Comment by asterikx** [comment]
I think this functionality is essential for any website with forms or editable content to prevent data loss.

React Router v6 has very convenient hooks for showing a `window.confirm dialog` with the given message when the user tries to navigate away from the current page.

See [`usePrompt(message: string, when = true)`](https://github.com/ReactTraining/react-router/blob/dev/packages/react-router-dom/index.tsx#L368) and [`useBlocker(blocker: Blocker, when = true)`](https://github.com/ReactTraining/react-router/blob/dev/packages/react-router/index.tsx#L364).

How can such functionality be realized within Next.js?

I would have expected a very similar API in Next.js. I would contribute, but I'm not familiar with Next.js routing internals (React Router leverages React Context API).

**Comment by LdsDannyStaten** [comment]
I would certainly like this feature as well

**Comment by ScottAgirs** [comment]
A much needed feature 💯

**Comment by pedroview** [comment]
Thus is become a growing issue, please vercel hear our cry. 
Have anyone tried tool, I expect it to do the work since it's built on react and I didn't seen any reliance on react-router

**Comment by closquet** [comment]
useEffect(() => {
    return () => {
     // do something
    };
  }, []);

**Comment by eagleeyejack** [comment]
Was looking for a solution similar to this and found this in the Next JS docs, has solved my problem as I was looking to use local storage when the user navigated to a different page/route.

https://nextjs.org/docs/api-reference/next/router#usage-6

Might help if you're stuck like I was 🤘🏻
