### ISSUE TITLE
Example "with-graphql-hooks" is not working with server side rendering

### ISSUE THREAD

**Issue by a-marcel** [vercel/next.js#9865]
# Bug report

## Describe the bug

When i build the with-graphql-hooks example and run check the server side rendered html output, the grpahql data is not part of the response.

## To Reproduce

Inside the examples/with-graphql-hooks folder

```
npm install
npm run dev
curl http://localhost:3000
```

## Expected behavior

I expect (based on the code) that the graphql examples renders the result of the graphql response inside the server side generated html.

During my debugging i figure out that the graphql client is created multiple times and because of that, different threads working with different graphql clients. This result into an empty ssrPromises attribute and an empty state: https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/with-graphql-client.js#L24

https://github.com/zeit/next.js/blob/canary/examples/with-graphql-hooks/lib/init-graphql.js#L20

I'm not sure why it's called multiple times, but this line above will create (and this is correct) every time a new client.

I found a similar issue here with apollo: https://github.com/zeit/next.js/pull/8917

**Comment by rbelow** [comment]
Hello everyone! @timneutkens do you have a sense why?

>  the graphql client is created multiple times and because of that, different threads working with different graphql clients

**Comment by Gytjarek** [comment]
@Timer recenly you've updated next.js example https://github.com/vercel/next.js/tree/canary/examples/with-graphql-hooks to the static generation. I'm checking the example I see that `useQuery` hook doesn't render server side. It just returns the loading statement
